### ISSUE TITLE
[DomCrawler] Support form input[type=reset]

### ISSUE THREAD

**Issue by adrienbrault** [symfony/symfony#10013]
Looking at https://github.com/symfony/symfony/blob/26b5cf3e4eb93046efb36449c3eb09b7357c7c24/src/Symfony/Component/DomCrawler/Form.php#L358-L384 it seems that it is not yes supported.

This seems to be the reason why the https://github.com/Behat/MinkBrowserKitDriver build is broken.

https://travis-ci.org/Behat/MinkBrowserKitDriver/builds/16026325

**Comment by jakzal** [comment]
@stof so do we need to do anything here?

**Comment by stof** [comment]
Closing because there is indeed nothing to do for such button in the normal usage of the DomCrawler form system
