### ISSUE TITLE
[Filesystem] dumpFile not compatible with streams

### ISSUE THREAD

**Issue by pablodip** [symfony/symfony#10018]
This is because it creates a normal file with `tempnam` and then renames it, but renaming between different streams is not possible:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Filesystem/Filesystem.php#L457

I discovered this when trying to use a virtual file system (https://github.com/mikey179/vfsStream) for tests, trying to pass it as the kernel root dir, but not being able because the kernel uses the `ConfigCache`, and this last the filesystem `dumpFile`:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/ConfigCache.php#L98

**Comment by stof** [comment]
@ericduran the issue is that file_put_contents is not atomic (it can write part of the content and then fail)

**Comment by ericduran** [comment]
@stof yep :) I get the issue, I guess the real question is do I prefer having test coverage with something that is not atomic or no test coverage with something that is atomic :-/ I went with the test coverage over reliability ha, kinda ironic.

**Comment by fabpot** [comment]
PR #14970 has been closed because it was not finished and the original author does not have time to finish the work. Anyone can take over the work of course.
