### ISSUE TITLE
[Process] Process Builder support for pipe command lines

### ISSUE THREAD

**Issue by cordoval** [symfony/symfony#10025]
Creating an issue here in accordance with https://github.com/alchemy-fr/BinaryDriver/issues/2 . @romainneutron could you please tell me how may we implement this, do i push a failing test for this first so we can pin point the problem? Thanks you rock man!

**Comment by dshiryaev-plesk** [comment]
Is there a way to do this now ?

**Comment by sstok** [comment]
You can use `\Symfony\Component\Process\ProcessUtils::escapeArgument` to escape the arguments, but that's deprecated 😐 OK...

You can always an string, but you will need to manually escape the arguments.
https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36#sanitizing-input-for-safe-shell-parsing

**Comment by nicolas-grekas** [comment]
@sstok NOOOoooo :)
Do never manually escape args, that's a very bad practice.
Just use "prepared" command lines:
```php
$p = new Process('cmd1 $VAR1 | cmd2 $VAR2');
$p->run(null, array('VAR1' => 'value1', 'VAR2' => 'value2');
```

**Comment by dshiryaev-plesk** [comment]
Thank you!

**Comment by sstok** [comment]
@nicolas-grekas Thanks for the tip 👍

**Comment by nicolas-grekas** [comment]
Nope, replacement has always been preformed by the shell, using env vars yes.

**Comment by staabm** [comment]
> 
> 
> @sstok NOOOoooo :)
> Do never manually escape args, that's a very bad practice.
> Just use "prepared" command lines (>=3.3):
> 
> ```
> $p = new Process('cmd1 "$VAR1" | cmd2 "$VAR2"');
> $p->run(null, array('VAR1' => 'value1', 'VAR2' => 'value2'));
> ```

@nicolas-grekas this no longer works on symfony/process 4.x. strings are not longer allowed for the command. how should those args be passed instead then?

**Comment by lyrixx** [comment]
`Process::fromShellCommandline()`
