### ISSUE TITLE
Make DependencyDecoration available without compiling the conatiner

### ISSUE THREAD

**Issue by movetodevnull** [symfony/symfony#10034]
Setting up Abstract Definition with some Arguments.
<code>
$container->setDefinition( 'class_abstraction', new Definition() )
		          ->setAbstract( true )
		          ->addArgument( new Reference( 'SomeRef' ) );
</code>

Then register some service like this
<code>
$container->setDefinition( 'class_implementation', new DefinitionDecorator( 'class_abstraction' ) )->setClass( 'MyImplClass' );
</code>

Then retriefing the Definition for the implementing class
<code>
$def = $container->getDefinition('class_implementation');
</code>
doesn't have a reference to the Argument configured in its parent.

First after compiling the container
<code>
$container->compile();
$def = $container->getDefinition('class_implementation');
print_r( $def );
</code>
the Definition shows the argument "inherited" of its parent Definition.

It would be great if the decoration is done on ->getDefinition and you don't have to call ->compile() first.

**Comment by fabpot** [comment]
Closing as the docs has been updated now.

**Comment by xabbuh** [comment]
@fabpot Afaics, `createService()` has not been updated yet (talking about definition decorations as mentionend in https://github.com/symfony/symfony/issues/10034#issuecomment-32481465). Is this something that shouldn't be adapted?

**Comment by stof** [comment]
@xabbuh if we say that we don't support creating a service without compiling the container, this is not an issue anymore. A compiled container cannot contain DefinitionDecorator instances
