### ISSUE TITLE
[Security] Add target_path_parameter, use_referer, etc options to logout listener

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#10047]
We are using crossdomain authentication (site1.com - authentication server, site2.com - dependent site). And after logout from dependent site we fine oneself on authentication server.

**Comment by curry684** [comment]
Should we still consider this relevant in 2019? The scenario you describe with authentication servers is standardized with OAuth2 these days, and that wouldn't cause these issues. So I'm not really sure we have a need to disclose this any more, and as shown in #23599 it's not quite trivial to adapt.

**Comment by chalasr** [comment]
I'm going to close this issue as it's 5 years old and it didn't bring much reactions from the community. You can still write your own `logout_success_handler` to solve this on your end.
