### ISSUE TITLE
[Validator] Add a domain validator constraint

### ISSUE THREAD

**Issue by elnur** [symfony/symfony#10088]
Currently, Symfony has only a URL constraint, but sometimes you just want to validate a domain without the protocol. There should be a constraint for domains.

**Comment by xabbuh** [comment]
@fabpot Can we really assume that this is closed? The feature added in #12956 allows to validate the DNS entries of the URL being validated, but the constraint still requires the string to be validated to be a URL (due to the pattern that enforces it to have a protocol).

**Comment by johnny-bit** [comment]
In php7 there's nice `FILTER_VALIDATE_DOMAIN` that fan be used with `filter_var()` to create simple callback validator before there's domain validator introduced.

BTW: If one were to create PR would it be better to supplement URL validator with domain validation or create separate DomainValidator?

**Comment by sylfabre** [comment]
@xabbuh @fabpot We have developed a DomainValidator at AssoConnect. Would you accept a PR for this validator or is it out of Symfony scope?
