### ISSUE TITLE
[Feature] Integrate PsySH in dev mode

### ISSUE THREAD

**Issue by vicb** [symfony/symfony#10094]
It would be great to be able to debug exception in dev mode with [PsySH](http://psysh.org/).

I've not yet look at the details and how hard this could be but using a REPL to debug misbehaved code is something really useful - This is something avaiable in the [Python Pylons framework](http://pylonsbook.com/en/1.0/tracking-down-problems-and-handling-errors.html).

/cc @bobthecow

**Comment by Markcial** [comment]
ping! any code samples, updates or a project started on this, should i work from scratch?

**Comment by lyrixx** [comment]
All my code is a very quick & dirty code.

But you can have a look to: https://github.com/dpb587/ti-debug which is a good start.

**Comment by fabpot** [comment]
Looks like it's not that easy. If anyone can create a PR, that would be great; closing this issue in the meantime.

**Comment by aar0nr** [comment]
If you're looking for a simple CLI for the container, kernel, and parameters, check out https://github.com/theofidry/PsyshBundle
