### ISSUE TITLE
[Form] Labels' translation with pluralization

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#10108]
Cannot translate properly labels which translation strings are available in "singular | plural" form.
Take a look at this example.

##### Translations
```
simple:
    translation:
        image: '{1} Image | [2,Inf] Images'
```

##### Form's Type class
```
public function buildForm(FormBuilderInterface $builder, array $options) {
    $builder->add('image', null, array(
        'label' => 'simple.translation.image',
        'translation_domain' => 'messages'
    ));
}
```

There is no possibility to say into add() method to translate given translation key in plural form. In the example above I expect the "Images" label, but it's impossible. Reason of this situation is that texts of labels, buttons etc. are always translated with ```trans``` instead of ```transchoice``` filter:

```
# vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig
<label (...)>{{ label|trans({}, translation_domain) }}</label>
```

Could you, please, add support for the plural translation?

**Comment by abdeltiflouardi** [comment]
+1

**Comment by aitboudad** [comment]
Closing as the related PR was closed.

**Comment by yanict** [comment]
Hi,
even after investigating during hours, I don't see a correct solution to this.
could @lavoiesl  or @aitboudad give some inputs ?

I'm working on symfony 2.7.
I have a choice field and its labels need to be translated in plural.
I was thinking to use the %count% parameter but still, I don't understand how I can pass a parameter to the translation there.

Thanks a lot for your help.

**Comment by kniziol** [comment]
@yanict solution is here: https://github.com/symfony/symfony/pull/10125#issuecomment-112468612. You should override block of label that has translation with pluralization.
