### ISSUE TITLE
[Routing] Get all matched routes (add method which not stops on the first matched candidate)

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#10113]
I'm using Symfony-CMF RoutingBundle with NestedMatcher http://symfony.com/doc/master/cmf/components/routing/nested_matcher.html . And for the route provider / route filter I should get all matched routes. Now it is not possible, I've copypasted bunch of code from `UrlMatcher` class.

**Comment by TomasVotruba** [comment]
@Koc Could you send PR for this feature?

**Comment by nicolas-grekas** [comment]
I'm closing here because the issue is old and no implementation has been provided yet.
Feel free to submit a PR of course.
