### ISSUE TITLE
Twig Exception Controller - Rendering paths

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#10183]
The showAction in Symfony\Bundle\TwigBundle\Controller\ExceptionController does not seem to listen to the additional Template Loaders I have added. Is this by design or should it still use the Template Loaders?

If I dump $this->twig->getLoader() it displays the chained loader I have created. It just doesn't use the correct path to the error template.

Basically I have a template loader that loads templates from app/Resources/themes/[theme name]/[bundle]/* as priority. This currently works for all the other bundles I have in there except TwigBundle.

vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Loader/FilesystemLoader.php
```php
try {
            $file = parent::findTemplate($logicalName);
            echo $file.'<br/>';
        }
...
```

I am echo'ing the filename to the templates above. All template paths are correct except for when an exception is thrown and it tries to render the correct exception file.

**Comment by fabpot** [comment]
Indeed, the exception controller does not use the loader at all. If you have a look at the code, you will see the `findTemplate` method where the logic to find the exception template is implemented.
