### ISSUE TITLE
[Security] Use Form component for form authentication

### ISSUE THREAD

**Issue by Brammm** [symfony/symfony#10262]
I've decided to use a model and a FormType for my Login form. This works great and is in my opinion a lot neater than the default approach in the docs (with the manually typed inputs etc...). 

However, it seems to me that it's impossible to validate the form. By validating the form, I mean adding constraints on the Login model and having them validated with `$form->handleRequest($request); if ($form->isValid()) ...`. This could be powerful as it would allow you firstly to make sure no empty credentials are checked and also because you could validate a username (e.g. it must be a valid email). 

I'm going through the code and as far as I can tell Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener would have to be coupled with the form component. I understand why this is not the case at the moment. 

Is it possible to create a different Listener, one that is coupled with the Form component?

**Comment by coudenysj** [comment]
Any suggestions to this approach? I'm trying to do the same (and actually trying to add a captcha field after x failed logins), but since I cannot intercept the posted form, I cannot add logic to it.

Is it an option to post the form to the same action and forward the request after the first validation?

**Comment by Brammm** [comment]
Iltar over on Freenode #symfony has experience with this iirc, you should consult with him.

**Comment by nurolopher** [comment]
I have the same problem with validation. Want to show required messages when both username(email) and password are empty.

**Comment by jkufner** [comment]
As I see it, it is completely wrong to have [login form](https://symfony.com/doc/current/security/form_login_setup.html) in the authentication layer. There should be no form_login security provider at all.

The proper way of logging in should be to create an ordinary controller with an ordinary form (using any  component/library a programmer wants). Once this form is submitted, validated and CSRF checked, the controller should retrieve credentials from it and then ask authenticator to authenticate the user using the provided credentials. The authenticator will do whatever it needs to and return success/failure back to the controller. If successful, the controller will send redirect to a client. If the login failed, the controller should show the login form again (with some error message).

Therefore I think, the best way to deal with form_login and stuff like UsernamePasswordFormAuthenticationListener is to throw them away completely.

**Comment by nickbass72** [comment]
@jkufner You are absolutely right!
