### ISSUE TITLE
[Form] preferred_choices are not repeated in the main list

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#10271]
Hello,

I am using the preferred_choices option for the first time and i am seeing that preferred choices are not duplicated in the main list.

I think it can cause trouble with users witch not pay attention that there are a preferred list or when default value witch is not in the preferred list is already selected (User will search alphabetically and maybe will not look to the top of the list).

Is there a way to repeat preferred values in main list ?
Maybe it should be the default symfony behavior ?

**Comment by nicolas-grekas** [comment]
I think this is valid also and would expect the value to be duplicated in the list

**Comment by ostrolucky** [comment]
There needs to be decision made if this is bug or feature request. This issue is marked as a bug, but PR review says this is feature.

**Comment by xabbuh** [comment]
see #32658

**Comment by Seb33300** [comment]
See my pull request which was closed.
