### ISSUE TITLE
[Security] getUsername in UserInterface is confusing

### ISSUE THREAD

**Issue by ged15** [symfony/symfony#10316]
Symfony Security component's [UserInterface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/User/UserInterface.php#L78) defines a method `getUsername`. The purpose of this method is to provide an identifier for the user. In some cases however, a username is not used as the identifier for a user (i.e. in Facebook you create a username only after registration, the email is used instead to identify the user; e-commerce solutions, in order to simplify user registration, also use the email to identify).
IMO, the user interface should not define a `getUsername` method, but rather a `getIdentifier`. I believe that this was the original intention of the `getUsername` method, but the naming turned out to be somewhat confusing.
If there would be interest and +1s from the community and the maintainers, I would gladly submit a PR respecting BC.

**Comment by backbone87** [comment]
The registration is called "username/password" not "identifier/password" or "email/password". you **do** have a username and thats the email. `return $this->getEmail();`

A better clarification imho would be to rename the `UserInterface` to `UsernamePasswordIdentityInterface`, which also hints the fact, that this *should not* **be** your entity/model, but something that is *derived* from it. it also tributes to the fact, that a user can have multiple identities (aliases or actual different sets of permissions) under that he wants to operate. According to that we could rename `UserProviderInterface` to `IdentityProviderInterface`.

**Comment by JHGitty** [comment]
Identity sounds better! :+1:

**Comment by Tarhab** [comment]
Is this still an issue?

**Comment by iltar** [comment]
As far as I know, yes. I recently started rewriting from Simple\* to Guard. I ended up using the `getUsername` for the identifier of the authenticated visitor. I also ended up having to implement a salt, password, roles etc. Now I've ended up with several objects, that basically receive an identifier in the constructor and have a `getUsername` to return it.

**Comment by ossinkine** [comment]
@iltar How is your work going? Are there any dates when we can see the result? Is there an understanding of how this should look in the next milestone?

**Comment by iltar** [comment]
I have no opensource code to illustrate the solution, but the fact that it's called a `username` is still an issue. It's not something I've been working on to fix in Symfony as of yet.

**Comment by ricknox** [comment]
In my honest opinion I think that the whole `UserInterface` is redundant. But to sum up: I use, and I see it a lot, it breaks down to this when you only use e-mail addresses:

```php
<?php declare(strict_types=1);

class Foo implements UserInterface, \Serializable
{
    /**
     * @var string
     */
    private $email;

    // ...

    /**
     * {@inheritdoc}
     */
    public function getUsername()
    {
        return $this->email;
    }

    // ...
}
```

For this issue, I see the `->getUsername()` is used in [many places](https://github.com/symfony/symfony/search?q=getUsername). Making it superfluous will be tricky. I think renaming it to `getIdentity` would be better, however, it will cause "Why is this code here" when looking at this part of the code: https://github.com/symfony/symfony/blob/a94e29f1ebe2ffaa37981769bb61e68f5e737402/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L47-L55 To sum up, this is really tricky as `getUsername` is everywhere. I am really interested to see what @iltar has in mind.

Oh and @wouterj already did something some time ago in #21068 but @javiereguiluz ruled it as to wait for the [survey of 2017](https://symfony.com/blog/symfony-community-survey-2017-results) and then the issue got closed. Time to shred some light on this issue as the security component really needs some love.

**Comment by sstok** [comment]
Basically **the token** should be concerned with the password (if any) and Roles/attributes, the "user" could be anything the implementer wants to use, a User Entity, a string or a UUID Value object.

We can keep the UserInterface (but deprecate it), to ensure existing implementations keep working while allowing more flexibility. There is however one problem, if you start using an incompatible value any existing implementation could break when this relies on a UserInterface to be returned.

**Comment by iltar** [comment]
I'm still of opinion that the `UserInterface` should probably never be used outside anything related to the security component/bundle. It could be a data container during the (re-)authentication process each request, but never leak into the session or application. Instead, I would like to make it easier to obtain the domain object representing the current user (Argument Value Resolver). If you need custom values that help identify the current user, you can use token attributes for that.

Obtaining the current domain object could be done with an abstraction.

```php
// names are probably bad
final class TokenToDomainObjectResolver implements TokenObjectResolverInterface
{
    // ... constructor and dependencies
    public function makeDomainObject(TokenInterface $token): mixed
    {
        return $this->userRepository->find($token->getIdentityValue()); // new method?
    }
}

// allows this in controller
public function fooAction(User $user);
```

```yaml
security:
    # ...
    firewall:
        main:
            # ...
            # again, the name is bad
            token_to_domain_object_resolver: App\Security\TokenToDomainObjectResolver
```

This way it should be possible to never expose the UserInterface in your application. However, this has 2 downsides.
 - While it's a bad practice, it'll be harder to obtain the User if it's not passed along methods (event listeners for example). This could in turn be resolved by creating a service that uses the same converter, should be 2 lines of code.
 - It'll be an extra query to query user interface (but might be cached for example)

**Comment by curry684** [comment]
We're looking at redesigning the entire authentication part of security for 5.0 which would outright drop both `UserInterface` and its `getUsername` method as it looks now.

(disclaimer: given the amount of legacy we'd likely provide a B/C layer with the old interface)

As the discussion is being centralized at #30914 I think we can close this issue.
