### ISSUE TITLE
session_start causes ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by mktcode** [symfony/symfony#10332]
We just moved our Symfony2.3 project to another server and now we encounter the following problem:

The routes /login and _wdt/9d5405 result in a ERR_EMPTY_RESPONSE error in Google Chrome (and all other browsers showing their specific error messages). The error occurs in both, prod and dev environment.

I tracked it down to be related with session_start in Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:148

Here I opened a Question on Stackoverflow with a little bit mor detail but no suitable answer:
http://stackoverflow.com/questions/21262958/symfony-2-session-start-causes-err-empty-response

The Problem was the PHP Version 5.4.20. We tested 5.3.17 and 5.5.9. Both function well. Except 5.4.20. But I still want to know what exaclty causes this error. This could then result in a Symfony fix to deal with this version of PHP.

**Comment by Tobion** [comment]
I don't think we can do much here if you don't debug this yourself. Pleae reopen if you have more information.
