### ISSUE TITLE
[3.0] [Form] Find out whether checkbox was unchecked in PATCH request

### ISSUE THREAD

**Issue by gquemener** [symfony/symfony#10364]
Related topic: https://github.com/symfony/symfony/issues/1341

Hello

There's a problem using the `$clearMissing` option while submitting checkbox input that I don't know if it was mentionned before.

On chrome, and probably on all browsers, checkboxes are not submitted in the request when unchecked which is handled by the `BooleanToStringTransformer` to reverse transform `null` into `false`.

So it means that only way, with Symfony, to set a checkbox value to false is not to send this checkbox in the request content, which is then cleared from the form if we use the `$clearMissing` option, which means that it is not possible to set checkbox value to false when using the `$clearMissing` option with the current SF2 implementation.

It seems to me that this case should be handled by Symfony.

I got several solutions in mind to support it:

- Do not clear checkbox from form even even if using `$clearMissing`
- Implement a whitelist option to the form that'll not clear mentionned fields even if using `$clearMissing`
- Update the `BooleanToStringTransformer` to reverse transform something else than `null` into `false`. It will allows to use a `hidden` fields (for example) with the view transformer added on it, and to consider its value as false in some case (like when it's an empty string, or 0, or No, or whatever that can be configured).

What's your thoughts about that? Sorry if that already came up in the discussion, I did a quick search but couldn't find some relevant tickets about it.

**Comment by zim32** [comment]
Same problem.Any ideas?

**Comment by zim32** [comment]
Solution is to add hidden input just above your checkbox with value "false" and add custom view data transformer 
```php
public function reverseTransform($value)
{
    if($value === 'false'){
        return null;
    }else{
        return $value;
    }
}
```

I propose to close this ticket.

**Comment by jakzal** [comment]
@gquemener is @zim32's solution satisfactory for you or do we still need some kind of a built-in support?

**Comment by gquemener** [comment]
@jakzal For me it's enough

**Comment by liverbool** [comment]
@zim32 @gquemener How to add `hidden` field?

**Comment by spackmat** [comment]
`BooleanToStringTransformer::reverseTransform` accepts null since Symfony 2.0. The `Form::submit` accepts null values since Symfony 2.3.

So don't add hidden inputs, but just send JSON (or other nullable-formatted) payload and set the checkbox-value to null. HTTP-POST doesn't allow other values than strings, so you must PATCH with a payload-format allowing `null` as a value. [See my StackOverflow-answer on this](https://stackoverflow.com/a/46056461/2564552).

**Comment by goulashsoup** [comment]
I don't know when it was added, but at least in Symfony 6 `CheckboxType` accepts a `false_values` option, submit values that are interpreted as `false`. With that a hidden input with value `"false"` is sufficient:

```php
$builder
    ->add('boolField', CheckboxType::class, [
        'false_values' => ['false'],
    ])
;
```

```twig
<input type="hidden" name="{{ form.boolField.vars.full_name }}" value="false">
{{- form_widget(form.boolField) -}}
```

Form will submit
- `"1"` when checkbox checked
- `"false"` when checkbox is NOT checked
