### ISSUE TITLE
Passing objects to Route generator

### ISSUE THREAD

**Issue by nick4fake** [symfony/symfony#10395]
For Symfony2 Router with the help of standart bundle (sensio extra) we can write ParamConverters to convert request param=>object. Is there any standart way to use reversed convertion?

Now we must do something like this:
path('DevBlogBundle_post_show',{'post':post.id})
While a better way would be:
path('DevBlogBundle_post_show',{'post':post})

I've found even example jist:
https://gist.github.com/stevelacey/3226510
1. Maybe, we should think about adding such functionality to future releases of, for example, sensioFrameworkExtra bundle?
2. If there is no such functionality, is bundle providing such extension would be needed?

Thanks.

**Comment by iltar** [comment]
I wrote a bundle that does exactly this: https://github.com/iltar/http-bundle. There's no need for additional twig functions, custom routers or custom generators. 

Please take a look and see if there's anything missing.

**Comment by javiereguiluz** [comment]
In the past, I was 👍  about this feature ... but now I'm strongly 👎 . Why?

* You write your templates once ... but execute them continuously. So the execution of templates must be fast, including URL generation.
* All the proposed solutions hurt performance:
  * @iltar solution is valid, but a bit boring and verbose. You need to write resolvers for each object, etc.
  * If we use PropertyAccess to find the route attributes *automagically* from the passed objects, everything is automated, but it will seriously hurt performance.

So, not using objects and passing the routes attributes individually is not bad at all to me. I recommend to close this proposal as "won't fix". Thanks!

**Comment by iltar** [comment]
> You need to write resolvers for each object, etc.

Small side note, I try to make things as little effort as possible, therefore things like entities are recognized and simply use the identifier value.

> If we use PropertyAccess to find the route attributes automagically from the passed objects, everything is automated, but it will seriously hurt performance

My only concern with this, are batch jobs. You won't often create links with objects in them, so is this really overhead each call? Isn't the path it needs to take, cached?

**Comment by javiereguiluz** [comment]
@iltar I'm still 👎  because this is being lazy once (*when writing the route*) and paying for it all your life (*worse performance when generating URLs in templates*).

**Comment by Zzortell** [comment]
@javiereguiluz Writing programs to save human's time by using machine's time... This is the goal of programming, and the goal of Symfony too! This seems not to be a valid argument as we do not generate so much routes. Moreover, we could do that in a way it will be fast to interprete. I particularly liked @ScreamingDev [proposal](https://github.com/symfony/symfony/issues/22161).

**Comment by stof** [comment]
@Zzortell `we do not generate so much routes` is a wrong assumption. I have cases generates thousands URLs in the page (and I know other peoples have such cases too, which is why we have a strong focus on performance for the Routing component, even though most recent improvements were on the matching side)

And @ScreamingDev's proposal in the issue you linked causes issues for matching (what would the request attribute look like after matching when the placeholder uses an object access syntax ?)

**Comment by nicolas-grekas** [comment]
Closing here as it looks like we don't want this in core, and [it's already doable in a bundle](https://github.com/symfony/symfony/issues/10395#issuecomment-134051312).
