### ISSUE TITLE
[Config] Referencing to parameters, which has default values in configuration, always returns default value.

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#10422]
I trying to use third-party bundle. (http://knpbundles.com/ornicar/ApcBundle). This bundle requires me to provide `ornicar_apc.host` config value. I am trying to re-use existing configuration value `router.request_context.host`, which is overrided in my `parameters.yml`, but third-party bundle always compiled with default configuration value `localhost`. After some time of debugging I found:

1st step: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L50 loading configuration for the `framework` extension. Keep in mind: `$container` already have loaded valid value for `router.request_context.host`.

2nd step: This line: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L306 loads default config value for `router.request_context.host` parameter value and rewriting existing "normal" value.

3rd step: Thrd-party bundle uses overwriten value of `router.request_context.host` parameter.

Could you help me with resolving this bug?

**Comment by jakzal** [comment]
@Strate would you mind checking if #13912 fixed this issue for you?

**Comment by stof** [comment]
Closing as there is no feedback and this indeed looks like the issue fixed by #13912 

Please reopen an issue in case the issue still happen
