### ISSUE TITLE
[Form] Checking if a form is "modified"

### ISSUE THREAD

**Issue by albertofem** [symfony/symfony#10438]
Hi, I don't know if Symfony already has this feature, but I stumbled upon this problem, where I need to check whether the data submitted to the form differs from the default one as defined in the types. There is a method right now, `isEmpty()`, but only checks if the data has been set or not.

Do you think such a feature would be useful at all?

**Comment by fabpot** [comment]
Closing as nobody stepped up to implement something like this.

**Comment by haivala** [comment]
I have User entity and edit form for it's email and other profile data. This would be really handy in this case because I would like to check if the email has changed before requiring user to validate the modified email with an actual email to the new address. I don't even need the old data.

**Comment by thejoelinux** [comment]
To you who are lurking here and have lost all hope, read this and be comforted. Trying to know if the form was modified so you can decide to notify the user in the controller, hey ?

In Symfony 7 you can have a `#[ORM\HasLifecycleCallbacks]`attribute on your entity class, then a method with a `#[ORM\PreUpdate]` attribute.

So when you persist the entity, the method will be called - I use it to position the `updatedAt` property, like :
```
    #[ORM\PreUpdate]
    public function setUpdatedAtAutomatically()
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
        $this->setUpdated();
    }
```

But see the `$this->setUpdated();` line ? This is just a non-persisted property of the entity so I could check if there really was an update at the manager level.

So back in my controller, after the flush :
```
if ($entity->getUpdated()) {
    $this->addFlash(
        'success',
        new TranslatableMessage('The entity has been modified')
    );
}
```

Hope it will be useful.
