### ISSUE TITLE
Fix url validator to accept underscore in sub-domain name

### ISSUE THREAD

**Issue by adicosoi** [symfony/symfony#10467]
Url validator accept as valid an url like the following: 
http://testsub+domanin.domanin.com:8080/test

but does not accept 
http://test_sub_domanin.domanin.com:8080/test

The problem seems to be here:
 symfony / src / Symfony / Component / Validator / Constraints / UrlValidator.php 
Line 28:                ([\pL\pN\pS-]+.)+[\pL]+                   # a domain name

The fix can be as simple as replacing \pS (mathematical symbol) with \pP (punctuation character) or even better i think \pPc (Connector Punctuation character)

**Comment by killerwolf** [comment]
+1

**Comment by apfelbox** [comment]
@boekkooi @iltar :+1:

**Comment by dunglas** [comment]
IMO it would benefit to more developers and projects to complete the `ext/filter` of PHP instead of writing a new Component for that. Btw native languages such as C are more performant and more convenient to do that kind of things than PHP.

**Comment by iltar** [comment]
@dunglas That beats the purpose of php imo. Yes it's faster, but not everyone can add/change/install that. Take for example the icu component, that gave a lot of troubles.

**Comment by dunglas** [comment]
@iltar troubles with the ICU component is mostly related to Linux and BSD distributions policies. Enhancing `ext/filter` (that is already well packaged) without adding new external dependencies to the core (no external libraries) will be included everywhere when new PHP version will be packaged.

**Comment by iltar** [comment]
@dunglas That means it would be released with php 7? You can't really depend on php releases as framework as you will have to keep supporting lower versions as well. Changes/bug fixes/ etc will all come too late for users that can't or won't upgrade to the latest php versions.

**Comment by dunglas** [comment]
@iltar progressive enhancement is doable (and already done in Symfony). The Validator component can require PHP 5.5 for instance but some specific features or validators require 7. The Validator can (and must) be enhanced but it actually do the job.

**Comment by nicolas-grekas** [comment]
Shall we close this one? It's already old, and if nobody dared implementing the feature since then, it's maybe because nobody really cares in real apps?

**Comment by pborreli** [comment]
we already closed #6759 for the following reason : [Internet Explorer Won’t Allow Cookies On (sub)domains With Underscores](https://ma.ttias.be/internet-explorer-wont-allow-cookies-subdomains-underscores/ ) should we close this again ?

**Comment by RFreij** [comment]
@pborreli I can understand it got closed in 2013, but shoudn't it be fixed in present times now IE is actually obsolete?
