### ISSUE TITLE
[Validator] Implement MessageExtractor

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#10504]
A message extractor for the Validator component would be a helpful extension:
- the extractor should scan a list of directories for classes that extend `Constraint`
- the values of all properties named `$message` or `$*Message` should be extracted

For each extracted message, the following data (or similar) should be collected:
- file
- line
- class
- property

**Comment by ostrolucky** [comment]
3rd party extractor has been implemented for this idea at https://github.com/php-translation/extractor I think this issue can be closed as there is no clear goal and is unlikely OP will provide one.
