### ISSUE TITLE
Extract the class resolving logic out of the controller resolver

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#10529]
It would be kinda cool to move the class resolving logic (class name vs. service)
and make it available in other places

https://drupal.org/node/2165475 has such a class, which certainly would be different for symfony.

Is this a doable thing in the first place?

**Comment by TomasVotruba** [comment]
This seems like a good feature proposal. Since Symfony components are integrated in Drupal 8, it would make even more sense.

What needs to be done here?

**Comment by fabpot** [comment]
Closing as it seems that the linked issue on Drupal has been resolved.
