### ISSUE TITLE
app/console list finds a namespace ambiguous if it only consists of sub-namespaces

### ISSUE THREAD

**Issue by kachkaev** [symfony/symfony#10531]
If, for example, a project consists of the following commands:

```
my-website:admin:do-something
my-website:admin:do-something-else
my-website:data:blah
my-website:data:blah-blah
```
calling ```app/console list my-website``` causes an exception:

```
 The namespace "my-website" is ambiguous (my-website:admin, my-website:data).
```
This does not look like what would be expected. Adding a command into ```my-website```  namespace directly (e.g. ```my-website:test```) helps to avoid the issue – command listing starts working fine.

Perhaps, the problem is in [Symfony\Component\Console\Application::getNamespaces()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L473) – this method registers only one namespace per command, so parent namespaces remain unknown unless they contain any commands directly.

**Comment by nacmartin** [comment]
I am having a look at this.
