### ISSUE TITLE
[3.0] [Form] Forbid PUT + File upload

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#10541]
> Quoting someone else:
> 
> > HTTP semantics has it that PUT on a resource should replace
> > the resource with the representation sent in the request. The
> > resource is expected to have a equivalent, if not bitwise equal,
> > representation as the request.
> > See also the lastest HTTP clarifications.
> 
> That means that multipart/form-data is usually wrong with PUT.
> 
> I understand that the Form component does encourage this, as simply adding a file element is expected to work. But it would be preferable to fix the Form component and forbid mixing PUT with file elements than working around it and against HTTP semantics. ping @webmozart
> 
> What you should do instead is PUT the content of your upload to the very same URL that you use to GET it.
> Or use POST instead of PUT, because POST has the required semantics.
> 
> An other major problem with the proposed patch is that IF the MIME multipart parsing algorithm should be implemented, it should be against the many relevant RFCs, be tested against variations found into the wild, be stream efficient (should not expect that everything fits in memory), etc. Many subjects that the C source code of PHP has implemented, tested and validated in real life situations. But having our own in Symfony is a hard work.

See https://github.com/symfony/symfony/pull/10381#issuecomment-36726684

**Comment by vincent-dravert** [comment]
Merci @lyrixx , je commencais a me prendre la tete sur ce sujet pour un vieux projet. J'espere que tu vas bien. Cheers.

**Comment by lyrixx** [comment]
I don't think it's useful to keep this issue open. I'm closing it.
But We can re-open it if someone want to.
