### ISSUE TITLE
[Form] Show existing file in FileType

### ISSUE THREAD

**Issue by bradlis7** [symfony/symfony#10696]
This may not be a common problem, but I have a file collection on an entity, and when I create the form, it's not obvious if a file exists when the <input> field is placed. They just look like blank file uploaders. In the image below, row 1 has an attachment, row 2 does not. How do I tell?

![capture](https://cloud.githubusercontent.com/assets/7062604/2684718/01241cd2-c1bd-11e3-9b08-5ce5f86be3b5.PNG)

I know that developing a workaround might not be too difficult on my end, but it sure isn't obvious. The only thing I've found is http://stackoverflow.com/questions/17683976/symfony-2-file-field-value-is-always-empty.

I know that you can't assign a value to a file input type, so I don't have a real answer on how to do it. Ideally, you would put a text input, that has the value, but when you click it, it turns into a file input, and a browse window pops up, but that would require JavaScript.

In my case, I wouldn't mind making the user delete the collection row and adding a new row, but not everyone might want that.

**Comment by bradlis7** [comment]
I'm no longer actively using Symfony, so you can close this if it's not something that someone else may need.

**Comment by Dumorya** [comment]
Hi,
I clearly have the same problem and need this feature. Does it have been developed since?
