### ISSUE TITLE
[Console] Events and InputDefinition problematic

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#10695]
When listening to the console.command event and trying to access information there are some problems:

1. <del>You cannot acess arguments or options in the InputInterface like `$input->getOption('myoption');` because they are not parsed yet. It's done only later by the application.
A workaround is something like `$command->mergeApplicationDefinition(); $input->bind($command->getDefinition());` inside your listener.
IMO the input should already have to params bound before the listener. Otherwise the input is pretty useless in listeners. Since people might want to add arguments/options dynamically in a listener (see 2.), the definition probably also needs to be bound after the listener just as now. So it should be done before and after the listener automatically.</del> Solved by #15938

2. Modifying the inputdefinition in a listener does not really work with the help. One can add options/arguments to some commands dynamically like in http://php-and-symfony.matthiasnoback.nl/2013/11/symfony2-add-a-global-option-to-console-commands-and-generate-pid-file/. But this will not properly work with the help display because running the help for a command (app/console mycommand --help) will actually run the HelpCommand and an event for this command. Thus the definition is not modifying for the "mycommand" but for the help. So the changed definition is not displayed.

**Comment by jaredm4** [comment]
+1. The arguments are not compiled until $command->run() is executed. The argument parsing should happen prior to the run. Additionally, to not introduce breaking changes, we could possibly add a new Event that happens after parsing them, so that the COMMAND event still happens before parsing.

**Comment by Tobion** [comment]
Closing this as the first main point has been fixed. I don't see a solution for the second one about the help. In theory the help could be different depending on arguments or any other runtime config. So there seems no generic way to adjust the help when a command is reconfigured using a listener.

**Comment by PunKeel** [comment]
Thanks for having this fixed :)
