### ISSUE TITLE
Registering new session bag does not initialize it

### ISSUE THREAD

**Issue by Imunhatep** [symfony/symfony#10707]
If the session is already loaded:

Currently session handlers allow dynamically register new attribute bags, but does not initialize them on registering. And does not throw any exception that created session attribute bag is not saving any data to session.

Developer have to define custom session service and register all bags there  (before session loads) or initialize bags by hands.

Symfony 2.4.2

**Comment by digilist** [comment]
I just ran into this issue, too. It was really annoying, to understand that the session has to be started afterwards. I currently see two options to fix this:

1. Call the `initialize()` method of the SessionBag from within the registerBag() method of the SessionStorage if the session was already started (similar to the code in `loadSession()`). Something like this:

    ```php
        public function registerBag(SessionBagInterface $bag)
        {
            $this->bags[$bag->getName()] = $bag;
    
            if ($this->isStarted()) {
                $session = &$_SESSION;
                $key = $bag->getStorageKey();
                $session[$key] = isset($session[$key]) ? $session[$key] : array();
                $bag->initialize($session[$key]);
            }
        }
    ```
    The `loadSession()` methods accepts an optional session variable. I do not see how and where this parameter is used, so I am not sure what to do here.
2. Forbid adding a bag after the session was started. In this case, an exception should be thrown and the documentation needs to be updated.

I'd prefer the first way. What do you think? I can provide a fix for this, if you agree.

**Comment by fabpot** [comment]
I think we should go with option 2.
