### ISSUE TITLE
generic solution to injecting action parameters by type hint

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#10710]
Currently ``ControllerResolver`` is responsible for determining the parameters to pass to controller actions. It does so via ``Reflection`` matching request attribute names to action parameter names. For parameters using the ``Request`` type hint it however knows to inject the ``Request`` instance.

Now in FOSRestBundle we have a need to inject parameters by type hint. Which leads to having to do the same work again. See for example:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/745

So it might make sense to provide some way to tell the ``ControllerResolver`` for whatever  other type hints to look for and what attributes to map them to.

**Comment by xabbuh** [comment]
Closing here as this now is a thing thanks to @iltar's great work in #18308.
