### ISSUE TITLE
Security token should be a member of Request object

### ISSUE THREAD

**Issue by drscre** [symfony/symfony#10754]
The current solution seems to have some kind of an architectural flaw (or maybe just my misunderstanding of what Request is)

'security.context' service is not request scoped but is used in a way like it always holds the token for the current(?) request.

To me this looks like an implicit assumption which is not completely obviouis. 

``` php
function someAction(Request $request)
{
    // Can I be sure that this token corresponds to $request? How? 
    $this->get('security.context')->getToken();
}
```

I think the flow should be more explicit:

Request enters an application -> Firewall examines the request and assigns token to it -> request with token is handed in to the controller.

**Comment by chalasr** [comment]
Closing for the reason given by @Tobion, Request must not be aware of Security as it is part of HttpFoundation.
