### ISSUE TITLE
PropertyPath unable to map a simple_array

### ISSUE THREAD

**Issue by coma** [symfony/symfony#10825]
I have an entity with something like:

``` PHP
/**
 * @ORM\Column(type="simple_array")
 * @Assert\All({
 *     @Assert\NotBlank,
 *     @Assert\Length(min=12)
 * })
 */
private $words;
```

And a form with something like:

``` PHP
->add('words', 'collection', [
    'type' => 'text',
    'allow_add' => true,
    'allow_delete' => true,
    'prototype' => true
])
```

And the `PropertyPath` keeps throwing an `InvalidPropertyPathException` here:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyPath.php#L125

Debugging I've found that it's trying to parse `data.entity.words.[__1398852784581__].[__1398852784581__]` as a propertyPath, and the regex fails with the last part `.[__1398852784581__]`.

Without `@Assert\All` it works just fine, `$words` holds an array of strings as expected and no exception is thrown.

I'm not sure if this is a bug or a misunderstanding.

**Comment by javiereguiluz** [comment]
I'm closing this issue because it hasn't received any response in more than 3 years. Thanks for understanding it.
