### ISSUE TITLE
[Form][Testing] Insulate on Client breaks on file uploads in functional testing

### ISSUE THREAD

**Issue by zajax** [symfony/symfony#10846]
Running Symfony 2.4.3, I believe it's an issue in 2.4.4 as well

If the Client is insulated, it tries to serialize() the data to pass to the Process. serialize() fails on UploadedFile.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Client.php#L145

That line serializes the request, but if request contains UploadedFile it fails.

Demonstration code:

Have a form with a file upload field named "file" and submit button named "submit"

```
$client = static::createClient($options, $server);
$client->insulate(true);
$crawler = $client->request("GET", $url);
$form = $crawler->selectButton("form[submit]")->form();
$form['form[file]']->upload("path/to/some/file");

$client->submit($form); // FAILS WITH BELOW TRACE
```

```
There was 1 error:

1) ...Test::test...
Exception: Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed

/.../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:145
/.../vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:368
/.../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:123
/.../vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:332
/.../...Test.php:74
```

**Comment by ostrolucky** [comment]
This is a duplicate issue of https://github.com/symfony/symfony/issues/19572 and should be closed in similar fashion.

**Comment by nicolas-grekas** [comment]
Agreed
