### ISSUE TITLE
[Form] String to Array DataTransformer throws exception

### ISSUE THREAD

**Issue by chbruyand** [symfony/symfony#10842]
Using a ModelTransformer to transform datas from an array (Model Data), to a string - for instance a comma-separeted-list of words (Norm Data) works really fine. But I can't get the reverse working. The problem comes from the ResizeFormListener that 
                 expects data to be array (or equivalent) in it's FormEvents::PRE_SET_DATA handler. But as the FormEvents::PRE_SET_DATA is propagated BEFORE the ModelTransformation takes place, Symfony\Component\Form\Form:l341, an exception is thrown.

To quickly illustrate that, and starting from a fresh symfony 2.3.13, you can modify the following files http://pastebin.com/WxHfziyX and visit /demo/contact. The same problem appears on 2.4.4.

If I modify the Symfony\Component\Form\Extension\Core\EventListener\ResizeFormListener to apply the data transformers in preSetData(), everything works fine.

Am I missing something ?

**Comment by mpoiriert** [comment]
@chbruyand  I have exactly the same problem. Did you find the solution ?
