### ISSUE TITLE
[Console] Add method to InputInterface that would allow to operate with input stream

### ISSUE THREAD

**Issue by maxromanovsky** [symfony/symfony#10844]
Currently `InputInterface` operates only with arguments passed to the Application.
I suggest to add a method that would allow to operate with an input stream (`STDIN` in case of CLI application).
This would help with decoupling `TwigBridge`'s `LintCommand` from direct usage of `STDIN` (#10843). Also it would simplify unit testing of such components.

**Comment by niels-nijens** [comment]
This feature would greatly improve testability of commands, especially when commands are using style classes like `SymfonyStyle` as it's 'hard' to get to the question helper and set a custom input stream.

But I guess this feature can't be implemented before 4.0?

**Comment by chalasr** [comment]
I opened #18999 based on your proposal (depreciated `QuestionHelper::setInputStream` in favor of `Input::setStream`), it should be mergeable before 4.0.
