### ISSUE TITLE
[BC BREAK] after validator branch merge

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#10868]
After the Validator refactoring branch has been merged I'm unable to remove the other bundles validator file. This is especially annoying as child bundle cannot override the parent's bundle validation.

This was broken by removing fetching the the validator configuration from container parameter in 9b204c9354453.

The doctrine bridge also uses this [functionality](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/DoctrineValidationPass.php#L54).

**Comment by webmozart** [comment]
I just discovered this issue again. What's the current status?

**Comment by mvrhov** [comment]
I'd say it's still present. My code is running the with the fix described above. But I'd say that the code in doctrine bridge still doesn't work.

**Comment by alexislefebvre** [comment]
Hi @mvrhov, is this issue still relevant?

**Comment by mvrhov** [comment]
Looking at the linked doctrine code I'd say yes.

**Comment by nicolas-grekas** [comment]
@mvrhov would you be able to provide a fix?
