### ISSUE TITLE
[SecurityBundle] Add Docs for SecurityFactoryInterface

### ISSUE THREAD

**Issue by langj** [symfony/symfony#10870]
The methods of the SecurityFactoryInterface do not have any comments. It would be helpfull if there were comments describing how the methods should be implemented and how the are used.

http://symfony.com/doc/2.3/cookbook/security/custom_authentication_provider.html
is describing the Interface a bit, but especially the signature of the create method is unclear.

**Comment by WouterJ** [comment]
I believe this is also a code issue, a very important one. The interface doesn't have PHPDocs, making it very hard to understand it. While the docs can help with this, PHPDoc should also be enough for experienced users to know what to do.

At the moment, one has to find implementations of the interface to know what the methods should do or what the arguments mean and what should be returned.

I would vote to reopen this issue
