### ISSUE TITLE
[Console] Automatic Exception logging

### ISSUE THREAD

**Issue by maxromanovsky** [symfony/symfony#10895]
There is an inconsistency between HTTP and CLI APIs when it comes to exception handling: by default Symfony logs an exception using `\Symfony\Component\HttpKernel\EventListener\ExceptionListener::logException()`.
CLI API only renders an exception to `OutputInterface`.
There is [an entry in Cookbook](http://symfony.com/doc/current/cookbook/console/logging.html#enabling-automatic-exceptions-logging) that describes how to implement such functionality, but I suggest to implement it in the Framework itself and enable by default.

**Comment by Tobion** [comment]
:+1: to make this happen
