### ISSUE TITLE
[HttpFoundation] Mock file session should expose generated mock file path

### ISSUE THREAD

**Issue by jcart** [symfony/symfony#10903]
I'm looking to persist the session mock file between tests in a known state using MockFileSessionStorage. However, I have no possibility to currently access the file path.

Since the existing storage class contains behavior on generated paths, my only option is to mimic in my own classes the generated file path based on the existing symfony2 configuration for this path (which is not fully parameterized):
    <argument>%kernel.cache_dir%/sessions</argument>
and hope any behaviour never changes.

I think it should either expose the generated mock file path or receive a strategy as a dependency that can otherwise be consumed by my own classes to re-generate the same path.

I'm happy to submit a pull request, but I'm wondering if I have somehow overlooked something.

**Comment by javiereguiluz** [comment]
Is this feature request still relevant? Do others miss this too? Thanks!

**Comment by jakzal** [comment]
I think we can close this, since no one for the past two years has commented on this issue.

I also don't think it's the right way to approach the problem. If the goal is to put the session in a known state than the session object should be used directly (or the application should do it).
