### ISSUE TITLE
[FrameworkBundle] [DependencyInjection] Separate container:debug command from bundle

### ISSUE THREAD

**Issue by kherge-old2** [symfony/symfony#10969]
I am in the process of developing a console application that will use the DependencyInjection component for managing commands and helpers, independent of the Symfony framework.

I remembered that the framework provides its own command to dump the contents of the service container, and would love to incorporate that feature into my application. Unfortunately, I have to install `symfony/framework-bundle` and its dependencies to get access to the command.

Does this sound like something that could be separated into its own package?

**Comment by fabpot** [comment]
Right now, the command needs access to `debug.container.dump`, which is something specific to the bundle. Also, the way the output is generated (in several formats is tied to the way it's handled with other command in the bundle.) So, even if we could provide such a command outside of the bundle, it's just impractical to do so.
