### ISSUE TITLE
[Security] Adding providerKey to AnonymousToken

### ISSUE THREAD

**Issue by carlalexander** [symfony/symfony#11006]
I apologize if this is covered elsewhere. I couldn't find any mention in articles, docs or issues. Is there a specific reason why `AnonymousToken` doesn't get the `providerKey` while all other `AbstractToken` subclasses do?

I am trying, programatically, to determine which firewall emitted an `AnonymousToken` and saw that it was not stored in the token.

I can create a PR to add it. I just wasn't sure if there was a security issue related to it so figured I'd ask first.

**Comment by curry684** [comment]
@wouterj this request makes sense, can it be integrated into your work at https://github.com/symfony/symfony/issues/30765?

**Comment by wouterj** [comment]
Given that there has not been much activity on this issue and `AnonymousToken` will be removed in Symfony 6, I think it's safe to close this one.
