### ISSUE TITLE
[HTTPFoundation] Session doesn't check if the session has been started

### ISSUE THREAD

**Issue by gena01** [symfony/symfony#11005]
So I ran into this recently. Specifically here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Session.php#L173

When using session_fixation_strategy set to "migrate" or "invalidate" and using a custom Auth provider that doesn't touch the session, then the session is never started/loaded. So migrate()/invalidate() methods try to manipulate "storage" and weird things happen.

I had to hard force the session to do start() otherwise i wouldn't get a session cookie among other things. Ideally there should be a check in migrate() or invalidate() method(s) to see if the session has been started before trying to do anything with it.

**Comment by javiereguiluz** [comment]
@nicolas-grekas after your recent work on Session, I wonder if this old issue is still relevant. Thanks!

**Comment by nicolas-grekas** [comment]
I don't know, but it's definitely too old, let's close. Please resubmit with a reproducer if you think something should be fixed.
