### ISSUE TITLE
[FrameworkBundle] The resource type of the default router is not overridable

### ISSUE THREAD

**Issue by lavoiesl** [symfony/symfony#11018]
It is possible to change the `router.resource` parameter, but the resource type option is unavailable, making it impossible to override it without manipulating the Service Definition. If the resource file is changeable, I believe the resource type should be as well.

Service definition:
https://github.com/symfony/symfony/blob/76ccb280fbb966d3d1c612a8dff600cc2228bc58/src/Symfony/Bundle/FrameworkBundle/Resources/config/routing.xml#L59

Compiler pass:
https://github.com/symfony/symfony/blob/76ccb280fbb966d3d1c612a8dff600cc2228bc58/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L311

Reverse issue : symfony/AsseticBundle#289

**Comment by WouterJ** [comment]
The resource type option is available and is called `type`. See https://github.com/symfony/symfony/blob/76ccb280fbb966d3d1c612a8dff600cc2228bc58/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L314-316 and http://symfony.com/doc/current/reference/configuration/framework.html#type

**Comment by xabbuh** [comment]
Closing as this is no bug as explained by @WouterJ.
