### ISSUE TITLE
cache:clear interesting side effects

### ISSUE THREAD

**Issue by Remper** [symfony/symfony#11098]
So after upgrading from 2.3.* to 2.5.* we started to get those warnings on a composer install:

```
Warning: file_put_contents(<path to project>/app/cache/dev/annotations/18ee525f115490bd711348d8a1a0a99df0993dc7#__construct.cache.php): failed to open stream: No such file or directory in <path to project>/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php on line 197
PHP Warning:  file_put_contents(<path to project>/app/cache/dev/annotations/18ee525f115490bd711348d8a1a0a99df0993dc7#createQueryBuilder.cache.php): failed to open stream: No such file or directory in <path to project>/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php on line 197
```

A whole bunch of them for every FileCacheReader's attempt to dump cache. Obviously, cache dir doesn't exist, but Doctrine have no idea about it. Of course, it means that if we clear cache with warmup afterwards everything works perfectly.
After a brief investigation a figured out those facts:
- This is started happening in 2.4.0-BETA2 (2.4.0-BETA1 is fine)
- Doctrine is executing somewhere around ConsoleEvents::TERMINATE event and after cache is cleared it tries to dump entities/repositories
- But before 2.4.0-BETA2 Doctrine was doing it's stuff before the actual cache clearance, so error never happened

### Answer ###

And you know what? I found the reason!
Well... in our project we are using custom logging processor that dumps some session-related debug info into the extra section. This particular processor does depend from Container so Symfony injects one via constructor.
The thing is, that after 2.4.0-BETA1, Symfony is generating additional DEBUG level log event after the cache is cleared, which triggers monolog, which triggers our processor, which is getting things from the container. But since container is constructed lazily — it constructs everything that goes with it at this very moment — Doctrine included. And because Doctrine doesn't expect that cache folders doesn't exist — it fails miserably.

I don't believe that this is a Symfony bug in it's essence, but I think that it is a good idea to somehow "mute" any additional execution (e.g. console.terminate event) for this particular Command.

**Comment by fabpot** [comment]
Closing this issue as we are well aware of the cache:clear command limitations. Unfortunately, the only "fix" would be to make it totally independent of Symfony.
