### ISSUE TITLE
[Security] Remember me and multiple firewalls

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#11127]
It appears if you have multiple firewalls with the remember me functionality enabled, they override each other.

Should the remember me key be stored with the firewall name appended? As we are dealing with security, may be best to hide the firewall name though and do substr(sha1('firewall name here'), 0, 10)

What do you think?

**Comment by xabbuh** [comment]
Can we close this given that the documentation has been improved now (see symfony/symfony-docs#5021)?
