### ISSUE TITLE
[Feature][Security] Add a TraceableFirewall

### ISSUE THREAD

**Issue by benja-M-1** [symfony/symfony#11134]
In my current application I have some performance issues. The profiler showed me that Symfony spends a lot of time in one of the configured firewalls but I need more informations to debug. We could wrap security listeners as regular listeners are in debug mode to collect time spend inside.

What do you think? I can work on it.

**Comment by thomas-koch-comsolit** [comment]
I think this issue could become easier to solve when we provide a Firewall class that can be retrieved as a service and contains all informations about the active firewall: https://github.com/symfony/symfony/issues/14435#issuecomment-110004138
This informations can than also be made available in the debugbar.

**Comment by chalasr** [comment]
👍  just spent two hours at debugging the authentication process of a "complex" firewall (multiple listeners, including several guard authenticators) using dumps and xdebug. 
I think that listing which authentication listeners have been called and which have not would be great. I'm looking at it.

**Comment by chalasr** [comment]
See #23105

**Comment by chalasr** [comment]
should be moved to done via #23105 in https://github.com/symfony/symfony/projects/4

**Comment by xabbuh** [comment]
@chalasr done
