### ISSUE TITLE
Ability to authentication a User directly

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#11158]
_(this issue is part of the ["DX" ("Developer eXperience") initiative](http://symfony.com/blog/making-the-symfony-experience-exceptional) introduced by Symfony project)_

Normally, we don't authenticate a user directly, the firewall handles all of that. But sometimes, we do! I realize that security is super-customizable (e.g. different token classes, etc), but it's always been a bit crazy that you can't simply - if you want to - login a user right from a controller (for example). People do this anyways all the time anyways, for example, after registration [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/LoginManager.php#L45).

Is it possible to support this? It would also allow people to handle security a bit more themselves if they wanted to, which for simple cases (e.g. traditional username+password login), I don't see an issue (I see authentication as _needing_ to happen via a listener before the controller only for things like API token authentication).

**Comment by chalasr** [comment]
I think #19819 might help.

**Comment by javiereguiluz** [comment]
Closing as fixed by #14673 thanks to the `authenticateUserAndHandleSuccess()` method: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php#L87
