### ISSUE TITLE
getRootDir isn't always reliable

### ISSUE THREAD

**Issue by mdavis1982** [symfony/symfony#11223]
The following code:

```php
public function getRootDir()
{
    if (null === $this->rootDir) {
        $r = new \ReflectionObject($this);
        $this->rootDir = str_replace('\\', '/', dirname($r->getFileName()));
    }

    return $this->rootDir;
}
```

Which is present [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L366) can fail in 2.5 if you're using the Symfony 3 folder structure, resulting in files being written to `app/cache` and `app/logs` rather than `var/cache` and `var/logs`. This can fail easily in `AppKernel.php`.

I came across this issue when using Behat 3 with Symfony 2.5... Upon doing `bin/behat --init "@SomeBundle"` I ended up with an `app/cache` folder, and an `app/logs` folder.

**Comment by fabpot** [comment]
Symfony SE now overrides getCacheDir and getLogsDir properly for Symfony 3.0.
