### ISSUE TITLE
Update public services XSD location

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#11266]
http://symfony.com/schema/dic/services/services-1.0.xsd
is not in sync with 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd
(expression as valid value for argument_type missing)

**Comment by Gladhon** [comment]
+1

**Comment by xabbuh** [comment]
I am in favour of removing the published files from symfony.com as long as we do not version the files in some way.

**Comment by giosh94mhz** [comment]
:+1: 

Just updated to symfony 2.7, removed all deprecated syntax, and now Eclipse complain that about `factory` is an invalid tag.

Wouldn't it be easier to have `XSD` version in sync with Symfony? IMO is the easiest way, since you are already putting much effort with this numbering. Also, I know you have a `grep -re 2\.7` somewhere :)

**Comment by backbone87** [comment]
@giosh94mhz you can use the eclipse xml catalog to get rid of the warnings:
window > preferences > xml > xml catalog > add:
location: path/to/your/local/symfony/services.xsd
key type: schema location
key: http://symfony.com/schema/dic/services/services-1.0.xsd

after that clean and full rebuild projects

i use this as a temporary workaround

**Comment by javiereguiluz** [comment]
I'm glad to say that this issue has been finally fixed. The file http://symfony.com/schema/dic/services/services-1.0.xsd is now in sync with Symfony's file. We are taking measures to prevent this issue from happening again in the future. Thank you all for the patience.

**Comment by giosh94mhz** [comment]
@backbone87 This is exactly what I did :)
@javiereguiluz Thank you! Please, consider also changing `1.0` version to `$symfonyVersion` for future releases, if it makes sense.

**Comment by Gladhon** [comment]
@javiereguiluz as @WouterJ pointet out, you really need to update the version of xml, if there are changes. Perhaps you can introduce this with sf3
