### ISSUE TITLE
[Session] "getFlashBag" interfacing issue

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#11279]
When you want the FlashBag to set a message, you'd like to do getFlashBag on the session. However, you can only achieve this by type hinting an injection on the Session\Session object. The Session\SessionInterface doesn't contain the "getFlashBag" method thus you can't use the Request::getSession();

If you do want to get the flash bag from it, you can try "getSession()->getBag('flash bag name')". However, that doesn't guarantee that you get the flash bag that was inserted because you don't know the name.

It's a minor inconvenience that has multiple custom solutions, but I've seen this issue come around a couple of times already in "#symfony".

**Comment by iltar** [comment]
Closing this issue as it seems like it's not a priority to fix as a work-around is available.

**Comment by ShinDarth** [comment]
it looks like this is still an issue
