### ISSUE TITLE
[Finder][Feature] limit results

### ISSUE THREAD

**Issue by claudebossy** [symfony/symfony#11290]
Hello,

It'd be nice to have a way to limit the results.
For example in a folder with lots of subfolders I wanted to find the first folder that has a .pdf file inside it.
So I used the filter but at the end I got all the folders with a .pdf inside it.
Then I do a `foreach` and `break;` after the first iteration.
I think it'd good to be able to limit the number of result so the finder can also stop earlier. It'd be best performance-wise.

Thanks.
Claude

**Comment by javiereguiluz** [comment]
Closing it because the issue can be solved as explained by @stof. Besides, this feature hasn't been requested by other users, so for now we won't add it to the component. Thanks for understanding it.

**Comment by jeroendesloovere** [comment]
Example code for the solution which @stof provided:
```
$finder = new Finder();
$finder
    ->files()
    ->depth('== 0')
    ->name('/\.(jpg|jpeg|png|tif|tiff)$/i');

foreach (new LimitIterator($finder->getIterator(), 0, 100) as $file) {
    // Do something for the first 100 files
}
```
