### ISSUE TITLE
[Translation] translation:debug doesn't check for translation strings in PHP files and functions in Twig templates

### ISSUE THREAD

**Issue by standaniels** [symfony/symfony#11293]
When debugging the translation of the app translation strings in PHP files (e.g. controllers) aren't included in the output, neither are some translation string in Twig templates.

For example, this translation string in a controller is missing:

``` php
<?php
namespace Acme\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $translator = $this->get('translator');

        return $this->render('AcmeBlogBundle:Default:hello.html.twig',
            array(
                'message' => $translator->trans('hello.world')
            )
        );
    }
}
```

And this one in a Twig template is missing too:

``` html
<div>
    {{ form_row(form.submit, { 'label': 'button.submit'|trans }) }}
</div>
```

**Comment by piotrantosik** [comment]
Is there a agreement on adding extraction translations from PHP files, for example, controllers?
It needs this functionality, and I can write it.

**Comment by weaverryan** [comment]
I think we need this, and moreover a system where you can add your own extractors (I don't know if this exists now). If there's some external library (I'm not talking about JMS) that already does this well that we can leverage, all the better.

**Comment by Aerendir** [comment]
I've the same issue: there are some translations that are marked as unused while they are used in form types and in controllers.

JMStranslationBundle doesn't have debug features (and I think it shouldn't): it is an helper to write translations, but I think that Symfony itself should check for the completeness as the tool used to write translations is irrelevant: someone may also like to write them by hand, for example.

I think the translator should be fixed. My 2 cents.

**Comment by asprega** [comment]
Is there a newer issue regarding this missing feature or is it just a dead discussion?

**Comment by fabpot** [comment]
We would be more than happy to improve how it works and add more locations where translations can be extracted from. If anyone is willing to work on this, we would be more than happy to review pull requests and merge them.

**Comment by burroz** [comment]
I think that if there is a functionality like debug:translation then it should all consider translations in php as for example labels in form types keep popping up in debug:translation as unused even if they are used in forms - just to give one example. This makes it pretty difficult to keep the translation file clean,...

**Comment by yceruto** [comment]
I checked this and we can close here since both features are already supported.
