### ISSUE TITLE
[DX] Add a JsonSerializable implementation to FormErrorIterator and FormError.

### ISSUE THREAD

**Issue by goabonga** [symfony/symfony#11309]
Every time when i need to return form errors to json I need to transform manually errors in my controller like:

``` php
/** @var array $errors */
$errors = array();
/** @var FormError $error */
foreach($form->getErrors(true) as $error)
{
    $errors[] = array('message'=>$error->getMessage());
}
$response = new JsonResponse();
$response->setData(array(
    'errors' => $errors
));
```

but with this simple implementation we can do:

``` php
/** @var JsonResponse $response */
$response = new JsonResponse();
$response->setData(array(
    'form'=>array(
            'errors' => $form->getErrors(true)
    )
));
```

I do not see if this implementation can have any adverse side effect.

**Comment by webmozart** [comment]
Hi @goabonga, thank you for proposing this feature! I think this is a good idea. However, we can only add this with Symfony 3.0 as before that we need to support PHP 5.3.

We should find out what information of a FormError is typically needed when returning errors from an API. Things that come to mind:

* the error message
* the code of the underlying exception/constraint violation? (via `getCause()`)
* maybe the field/property path that the error occurred on?

I'm not sure about all of this. Any input @lsmith77?

**Comment by goabonga** [comment]
Hi @webmozart, 

It's can be "formidable" if next version respect the jsonapi specification.
(the specification introduce error objects. http://jsonapi.org/format/#error-objects ).

What do you think about it ?
