### ISSUE TITLE
[DX] Single point of entry

### ISSUE THREAD

**Issue by xtrasmal** [symfony/symfony#11310]
Can I have this:

    No more app_dev.php  or app.php

Just 

    index.php

So what about environments?

    config/app.yml

What would be in it?

    app
        environments:   ['local'=>'local.domain', 'dev'=>'dev.mysite']

--- 

Then I propose an environment detection that loops trough the array in the app config
and loads the right config files, ONLY if they are present. Else they will fall back to default.

So.. how would that look like? Folder structure:
The current situation and the default config file for persistence info:

    config/database.yml

Then if I would like to have a different config for dev:

    config/dev/database.yml

This will override only the differences. For example.. the password or db user

Then if I would like to have a different config for staging:

    config/staging/database.yml

Great!

**Comment by fabpot** [comment]
Closing as there is nothing preventing developers to do whatver they want in Symfony. The SE does have an opinionated way of doing it, and that's not going to change.
