### ISSUE TITLE
Clear Cache prod environment when change EventSubscriber class name

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#11354]
I´ve found a bug when you try to clear cache with

<code>php app/console cache:clear --env=prod</code>

If a XXXSubscriber class name change, when you try to clear cache it says:

<code>Class 'yyy\MyBundle\EventListener\XXXSubscriber' not found in /var/www/yyy/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 142</code>

Of course i change class name in XXXSubscriber.php file and in services.yml definition

<code>
    yyy.xxx:
        class: XXXSubscriber
        tags:
            -  { name: kernel.event_subscriber }
</code>

Im in Symfony 2.5 on Elementary OS x64

**Comment by fabpot** [comment]
Closing this issue as we are well aware of the cache:clear command limitations. Unfortunately, the only "fix" would be to make it totally independent of Symfony.
