### ISSUE TITLE
symfony/security-acl: newly created ACL are putted incomplete into cache

### ISSUE THREAD

**Issue by tspycher** [symfony/symfony#11363]
putInCache gets only called once:
https://github.com/symfony/security-acl/blob/master/Dbal/AclProvider.php#L192

This code as example:
```
       $acl = $aclProvider->createAcl($objectIdentity);
       $acl->insertObjectAce($sid, $mask, 0 , true);
       $aclProvider->updateAcl($acl);
```
Leads into an imcomplete ACL in the cache where no ACE's are attached. Flushing the ACL Cache or explicit removing of the ACL from the cache solves the problem but seems unnecessary.

fixing updateAcl method seems more feasible where the entry in the cache gets updated as well.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
