### ISSUE TITLE
PropertyAccessor should recursively create missing arrays on write

### ISSUE THREAD

**Issue by thkoch2001** [symfony/symfony#11366]
Hi,

it's a very common pattern to create a two dimensional array in a loop like this:

```php
$output = [];
foreach($input as $value) {
  $level1 = $value->foo;
  if(!isset($output[$level1]) $output[$level1] = [];
  $output[$level1][] = $value;
}
```

This can be solved elegantly in Java with Guavas Multimap[1] and in Python with defaultdict. The PropertyAccess component would be a fitting place for such functionality in Symfony, e.g.:

```php
  $output = [];
  $accessor->setValue($output, "[${level1}][]", $value);
```

[1] https://code.google.com/p/guava-libraries/wiki/NewCollectionTypesExplained#Multimap
[2] https://docs.python.org/2/library/collections.html#collections.defaultdict

**Comment by Tobion** [comment]
Closing as I don't see the connection between PropertyAccess component and the thing you are trying to do. Also why bother about something that takes 4 lines of code.
