### ISSUE TITLE
[DX] Improving Vagrant support

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#11395]
The problem
-----------

When using Vagrant and Symfony, you'll end up with some problems when trying to
access `app_dev.php` controller because of the following check:

```php
// web/app.php
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !(in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1')) || php_sapi_name() === 'cli-server')
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
```

Your Vagrant host IP will always be different from `127.0.0.1` and therefore,
Symfony will prevent you to access `app_dev.php` controller.

The solution
------------

The obvious solution is to manually add the host IP (e.g. `192.168.56.1`) to the
previous condition, but this doesn't look like a professional way to fix this problem.

After talking with @frastel he proposed me the following alternative. We could introduce a new server variable (e.g. `SYMFONY__TRUSTED_HOSTS`) and then, modify the dev controller (the resulting code may be a bit ugly):

```php
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || (
        //BC
        !in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1', '192.168.0.1'))
        &&
        // the new way
        (
            isset($_SERVER['SYMFONY__TRUSTED_HOSTS'])
            && !in_array(@$_SERVER['REMOTE_ADDR'], explode(',', $_SERVER['SYMFONY__TRUSTED_HOSTS']))
        )
    )
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check ' . basename(__FILE__) . ' for more information.');
}
```

The last step would be to set up this variable with the web server. For instance, if you use nginx:

```
location ~ ^/(app|app_dev|config)\.php(/|$) {
   ...
   fastcgi_param SYMFONY__TRUSTED_HOSTS 192.168.0.1,192.168.56.1;
   ...
}
```

**Comment by kimausloos** [comment]
@javiereguiluz I found this while looking for a solution for this kind of problem. This works for me: https://github.com/kimausloos/symfony-standard/commit/1feac8dfa5ffd02adf55c01e4613b51c7ebd5bd0

Any feedback or do I create a pull request?

**Comment by timglabisch** [comment]
:+1: for this solution

**Comment by jeremy-derusse** [comment]
@javiereguiluz What's about providing an `app_env.php` which use the the `SYMFONY_ENV` environment variable (see https://gist.github.com/gerryvdm/f633eda0b8dd194143e2).
Vagrants users can easily add a `SetEnv SYMFONY_ENV dev` in the apache configuration (or `fastcgi_param SYMFONY_ENV dev;` in Nginx)

**Comment by kimausloos** [comment]
@jeremy-derusse as an extra file and not a replacement for app_dev.php you mean? Because replacing app_dev.php would mean developers wo are not using environment variables are unable to use the dev environment.

Anyway, I will have a look at the feedback @xelaris gave and create a pull request later tonight.

**Comment by javiereguiluz** [comment]
@kimausloos I don't really know what to say because I personally don't use Vagrant.

@jeremy-derusse the Symfony console actually uses that trick to set the environment and the debug options (see https://github.com/symfony/symfony-standard/blob/2.7/app/console#L18-19). I don't know the reasons why the front controllers don't use that trick.

**Comment by xelaris** [comment]
@jeremy-derusse @javiereguiluz I think the main reason for the separated front controllers is to enable simple switching between the environments in the browser. It also enables to keep the individual front controllers clean and simple while allowing different setups (e.g. AppCache/ApcClassLoader in prod, umask(0000) in dev). Finally all app_* files can be simply removed on prod deploy.
While an app_env.php could be added in addition, I don't see the benefits of such a front controller.

**Comment by jeremy-derusse** [comment]
@javiereguiluz exactly, I use the same environment variable on purpose... 
This is (probably) not done in SE front controllers for simplicity:
- editing an virtualhost could be hard for beginners (that why we also have a .htaccess). 
- letting the developper to tests his application in prod environment without reloading his the server

@xelaris the main avantage of an app_env controller, his to get rid of IP checking. 
I'm tired (as every symfony's developer who simply comment those security lines), each times I start or I join an existing project: to search my IP, to edit the app_dev.php or to edit the vhost and reload the web server.
BTW, merging app.php and app_dev.php [produce a 25 lines of code script](https://gist.github.com/jeremy-derusse/63158457a6d04e06a8dc) (included umask and ApcClassLoader)

**Comment by xelaris** [comment]
@jeremy-derusse Choosing the app environment (e.g. via an environment parameter) and limiting access this environment (e.g. via IP checking) are two separate things IMO. If you configure your server to run your app in dev enviroment, you might nevertheless like to limit access to this enviroment.
If not, what is most likly true in case of a vagrant environment with host-only network, one could also set a simple `SYMFONY__ENABLE_NON_PROD_FRONT_CONTROLLER` server environment parameter and add a check for the existents in the non-prod front controllers. This would in a way correspont to `php_sapi_name() === 'cli-server'` and would also keep the possibility to switch between environments via URL.

**Comment by timglabisch** [comment]
:-1: for app_env

**Comment by jeremy-derusse** [comment]
@xelaris indeed, I mixed environment and checking. 
IMO, The `SYMFONY__ENABLE_NON_PROD_FRONT_CONTROLLER` could be good alternative to the check by IP.

```
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !(
        in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1')) 
        || php_sapi_name() === 'cli-server'
        || false !== getenv('SYMFONY__ENABLE_NON_PROD_FRONT_CONTROLLER')
    )
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
```

**Comment by fabpot** [comment]
Closing this issue as it's outside of the scope of Symfony core anyway. The snippet discussed is in the SE anyway.

**Comment by kimausloos** [comment]
@fabpot should I close pullrequest https://github.com/symfony/symfony-standard/pull/768 too?

**Comment by fabpot** [comment]
The one on SE should not be closed as it is something different.
