### ISSUE TITLE
Disabling account does not log user out on next request if the logged in user is one being disabled

### ISSUE THREAD

**Issue by mtotheikle** [symfony/symfony#11402]
Disabling the users account who is logged in will not log them out in the next request that they make. However, if a different user disables a different account such as an admin disabling a users account then the user being disabled will be logged out automatically on the next request the newly disabled user makes.

This seems to cause confusion for developers when say a logged-in user is disabling their own account. It would be great if the next request would then follow the same logic as if the user account was disabled by a different user. Without this working the same as if some other user disables a users account you must manually set the token to null to log the user out. You then lose the security firewall logic for how to handle invalid tokens.

I think a beginner would have some challenges with with this but maybe I'm mistaken. Thoughts and input?

cc/ @landr0id

**Comment by chalasr** [comment]
This issue seems outdated. `AdvancedUserInterface` has been deprecated in 4.x, you need to make your user class implement `EquatableInterface` and if the refreshed user is not equal to the session one, it will be deauthenticated.
