### ISSUE TITLE
simple_form doesn't work with AdvancedUserInterface

### ISSUE THREAD

**Issue by dante2008** [symfony/symfony#11424]
How to reproduce:

1. Create a `User` class which implements `AdvancedUserInterface`
1. Create a custom authenticator
1. Set up a firewall to use `simple_form` with the authenticator you just created
1. Try to login

Google Chrome shows me with error message "Redirect Loop". However, if I change the `User` class to implement `UserInterface`, it works.

You can clone [this repo](https://github.com/dante2008/simple-form-issue) and replicate this bug.

Login path: `/login`

**Comment by WouterJ** [comment]
I'm sorry. I'm unable to reproduce this bug locally on Symfony 2.6.9 and 2.7.1. This means it either got fixed (your example used 2.5, which does no longer support bug fixes) or you had something else causing this redirect loop.

I think it's safe to close this, what do you think?

**Comment by xabbuh** [comment]
I'm closing here.

@dante2008 Feel free to reopen if you can provide more information about how to reproduce your issue.
