### ISSUE TITLE
[Form] Dynamically modifying options for collection items

### ISSUE THREAD

**Issue by landaire** [symfony/symfony#11467]
I've come across a situation where I'm using a `collection` type with the options `allow_add` and `allow_delete` enabled, and the `type` is some custom form type (we'll call it `foo_bar`), and I want to be able to disable the entire `foo_bar` if some condition is met with its data.

Current options:
1. Disable each `foo_bar` child in the `PRE_SET_DATA` event.
2. Add another form layer (`collection` -> `x_y_z` -> `foo_bar`) - and provide a data normalizer.
3. Set the `vars['disabled']` element to `true` for each `$view->children` in the `finishView` method like so:

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $foo = $form->getData();

        $disable = $foo ? $foo->shouldBeDisabled() : false;

        if ($disable) {
            foreach ($view->children as $child) {
                $child->vars['disabled'] = true;
            }
            $view->vars['disabled'] = true;
        }
    }

Option 1 would be avoided because it's a lot nicer to set `disabled` on `foo_bar` rather than it's children. Setting `disabled` on the parent also gives you the `disabled` variable in your twig template so you can modify the widget accordingly (for example if you have a "remove" button and want to disable it if the item is disabled).

Option 2 gets messy.

Option 3 would be avoided because that doesn't provided any guarantee of data integrity. If someone modifies the DOM tree to remove those from the form, the form system will assume that the user has removed those items.

I'd like to propose some method of dynamically setting options for the parent form based off of the data provided. Something like a new event before PRE_SET_DATA is called that allows you to mutate the `$builder`.

I also was discussing with a coworker just providing a callback for an element in the `$resolver->setDefaults` array which provides some object that lets you get the data and return an appropriate value based off of that. He identified a couple of issues with this idea, such as if you modify the data in `PRE_SET_DATA`, what happens then?

cc: @mtotheikle

**Comment by webmozart** [comment]
Closed for the reasons explained in #11477.
