### ISSUE TITLE
[Form] PATCH requests should not succeed if constraints fail

### ISSUE THREAD

**Issue by jmcclell** [symfony/symfony#11493]
If I construct two objects Foo and Bar, such that:

```php
class Foo
{
    /** @var Bar */
    public $bar;
}

class Bar
{
}
```

whereby Foo hasOne Bar, I would expect that a form constructed with a data_class of Foo would validate all properties of Foo which have constraints regardless of whether or not a default value for $bar is set. Instead, the form passes validation even if other fields in Foo which have constraints should fail, provided that I have set a default value for $foo->bar.

It's easier to demonstrate than explain:

https://github.com/jmcclell/recursive-validator-bug-test-case

In this repo, there is a single test class at `src/Acme/DemoBundle/Tests/Controller/DemoControllerTest.php` with two test cases. One hits a route where I do not define a default value for Foo::bar and one where I do. Both test cases provide an empty request to the route. I am expecting a 400 response in both cases, but as you can see, where I set the default I get a 200 response, even though Foo::Baz does not have its constraints met.

This means that if I were to place business logic inside the Form::isVaid() conditional which depends on the entities being validated, I am going to get entities that I cannot trust to be valid if the client sends a malformed (in this case, empty) request.

Curiously, if I run the object through the Validator manually, it performs as expected and returns the proper list of validation errors. It appears to be specific to form validation.

I ran into this bug with a specific setup of mine, so you'll notice a few things:

1. CSRF protection is disabled (my project is a RESTful API which is AJAX only)
2. Forms have no names (my client does not wrap its request in a namespace)
3. I am using submit() vs handleRequest() because in my specific case I need to strip out extra fields because forms do not support extra fields yet
4. I am using annotated constraints, in the test case you can find them in the `src/Acme/DemoBundle/Entity` folder for both the `Foo` and `Bar` entites

**Comment by guilhermeblanco** [comment]
I'd add to this list the issues I've faced while trying to make GET requests to work: https://gist.github.com/guilhermeblanco/287e67fff9d1dcbc2f13

**Comment by Paxton** [comment]
Any updates on this? This behaviour is still present as far as I am aware.

**Comment by devantoine** [comment]
+1

It's been more than two years this issue has been raised. With REST API being more and more used, lot of people with face this issue.

**Comment by xabbuh** [comment]
Can you confirm that the changes proposed in #30265 will fix this issue?
