### ISSUE TITLE
failed container cache warmer do not trigger cache re-generation on next request

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#11526]
Say I have a cache warmer that fails due to an exception. The container is already written, so on the next request the cache warmer is not triggered again.

I wonder if we need to somehow ensure that in such cases the entire cache is considered tainted so that it gets regenerated on the next request?

Right now I think Bundle developers assume that their compiler passes have executed without error and therefore do not handle the case when they may have failed due to an exception.

**Comment by javiereguiluz** [comment]
Closing it because this can be solved via documentation as mentioned by @lsmith77. See https://github.com/symfony/symfony-docs/pull/6215.
