### ISSUE TITLE
[DX] Can we handle permissions in an easier way

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#11563]
Hi guys!

After a conversation at symfony/symfony-docs#4070, we wondered: might it be possible to handle permissions (to the `cache` and `logs` dirs) in a way that's consistently and easily handled?

When you start with Symfony (unless you're using the built-in server), you will immediately hit permissions issues. They're annoying because they hit a new user very early, and the fix varies wildly based on your system: http://symfony.com/doc/current/book/installation.html#book-installation-permissions

Can we do better? I believe that permissions are set to 755 and not 777 due to security concerns, probably concerns on a shared server. Is that even accurate?

Thanks!

**Comment by fabpot** [comment]
This is definitely something that is addressed in the documentation as I still don't see what we can do in the core to simplify this. So, I'm closing it now as I don't anything actionnable.
