### ISSUE TITLE
BUG Upgrade Sf 2.5 too many open files running tests

### ISSUE THREAD

**Issue by entering** [symfony/symfony#11566]
````
PHP Warning:  include(/private/var/www/uniplaces/vendor/phpunit/phpunit/src/Framework/TestFailure.php): failed to open stream: Too many open files in /private/var/www/uniplaces/vendor/composer/ClassLoader.php on line 378
```

A lot of files of test.log appear:
````
php54   4470 entering   59w   REG    1,2 2305175512  8428713 /private/var/www/uniplaces/app/logs/test.log
php54   4470 entering   60w   REG    1,2 2305175512  8428713 /private/var/www/uniplaces/app/logs/test.log
...
```

And they grow over and over to > 200

If I downgrade to Sf 2.4 is stable on 2/3 files without any change on the code.

**Comment by spezifanta** [comment]
We are still having this problem.

**Comment by jakzal** [comment]
@spezifanta would you mind to check if the issue persists with xdebug disabled?

**Comment by asentner** [comment]
@jakzal I am having the issue only with xdebug open. Do you know the background behind this? I have not found much online.

**Comment by jakzal** [comment]
see http://bugs.xdebug.org/view.php?id=1070

**Comment by asentner** [comment]
Perfect! Thank you.

**Comment by WouterJ** [comment]
So this bug is related to xDebug? In that case, save to close?
