### ISSUE TITLE
[Console] Option with optional argument always returning null whether specified or not

### ISSUE THREAD

**Issue by EdwardIII** [symfony/symfony#11572]
From the docs (http://symfony.com/doc/current/components/console/introduction.html#using-command-options):

```
It is also possible to make an option optionally accept a value (so that --yell
or --yell=loud work). Options can also be configured to accept an array of values.
```

In practice it doesn't seem to work this way. When creating a Command like this:

``` php
    <?php
                ->addOption(
                    'createfile',
                    null,
                    InputOption::VALUE_OPTIONAL,
                    'Do not delete the file, specify argument to choose an alternative filename'
                )


    ...

                $createfile = $input->getOption('createfile');
                var_dump($createfile); // returns NULL
```

And calling it like this:

```
php app/console my:command --createfile
```

The value of $createfile is null, even though the switch is present. 

I can't find any way to identify that the command is present _unless it has a value_.
i.e.    `php app/console my:command --createfile='/tmp/somefile.txt'` does what you'd expect and returns the string "/tmp/somefile.txt".

I can see no other way of identifying whether this option is present?

There seems to be some code supporting the idea that you get a different return value if the option is provided but with no optional value present:

https://github.com/symfony/symfony/blob/2.5/src/Symfony/Component/Console/Input/ArgvInput.php#L234

This looks like it should provide you with an empty string if this parameter is provided but has no value, however in my tests count($this->parsed) was 0, which meant that this inner block could never get executed.

I checked out the unit tests for ArgvInput but couldn't find a test that seemed to be based on this particular use case:

https://github.com/symfony/symfony/blob/2.5/src/Symfony/Component/Console/Tests/Input/ArgvInputTest.php

Symfony version 2.5.2 - app/dev/debug

**Comment by c33s** [comment]
### workaround

command definition:
```
$this
    ->setName('demo:greet')
    ->setDescription('Greet someone')
    ->addOption('yell', null, InputOption::VALUE_OPTIONAL, 'If set, the task will yell in uppercase letters')
;
```

in the execute method
```
$result1 = $input->hasParameterOption('--yell');
$result2 = $input->getOption('yell');
```

console
```
php ./bin/console demo:greet
// $result1 == false
// $result2 == null

php ./bin/console demo:greet --yell
// $result1 == true
// $result2 == null

php ./bin/console demo:greet --yell=foo
// $result1 == true
// $result2 == foo
```
code example:
```
//only set build if option was set. if set with no value, set it to empty (default value)
if ($input->hasParameterOption('--build')) {
    $build = $input->getOption('build');
    if (!is_array($build)) {
        $build = explode('.', $build);
    }
    $builder->setBuild($build);
}
```

**Comment by andkirby** [comment]
Yeah, this is really overhead to check such options...
```
    /**
     * Check if empty password option passed
     *
     * @param \Symfony\Component\Console\Input\InputInterface $input
     * @return bool
     */
    protected function hasEmptyPasswordOption(InputInterface $input)
    {
        return null === $input->getOption('password') && $input->hasParameterOption('-p')
               && $input->hasParameterOption('--password');
    }
```
Is there any simpler way?..

**Comment by dguhl** [comment]
@andkirby You might want to use an array for the call.

```php
    /**
     * Check if empty password option passed
     *
     * @param \Symfony\Component\Console\Input\InputInterface $input
     * @return bool
     */
    protected function hasEmptyPasswordOption(InputInterface $input)
    {
        return null === $input->getOption('password') 
            && ($input->hasParameterOption(['-p', '--password']));
    }
```

**Comment by andkirby** [comment]
@dguhl, yeah, I didn't know the method `hasParameterOption` may get an array.
Thanks.

**Comment by dotmpe** [comment]
hasParameterOption is the key that makes this usable, for years I believed the InputOption::VALUE_OPTIONAL part of console was broken, in favour of "BC". 

It is not mentioned on https://symfony.com/doc/current/console/input.html, while "there is no way you can distinguish when the option was used without a value" is.

**Comment by algorhythm** [comment]
I've written an more resuable function that can answer the question for any option

    public function wasOptionUsed(string $optionName): bool
    {
        // raises an error if option doesn't exists
        $this->input->getOption($optionName);

        $option = $this->getDefinition()->getOption($optionName);
        $name = $option->getName();
        $shortcut = $option->getShortcut();

        return $this->input->hasParameterOption([
            '--' . $name,
            '-' . $shortcut,
        ]);
    }
