### ISSUE TITLE
Integrate unique request id

### ISSUE THREAD

**Issue by hacfi** [symfony/symfony#11573]
With the introduction of the DX label I was wondering whether you support the idea of integrating a unique request id. I know you can easily add it yourself but I think it’s useful in most projects.

My suggestion would be to allow to pass a generated environment variable if you already generate one before (I’m using https://github.com/newobj/nginx-x-rid-header for example) or generate one if not available. We could also have a look at how to use it in monolog. You should be able to configure whether to pass it to the frontend or not (`X-Request-Id` header).

**Comment by fabpot** [comment]
@asm89 The only requirement for integration into Symfony would be to convert `RequestId` into a proper listener.

**Comment by psampaz** [comment]
this would be a great feature :+1:

**Comment by psampaz** [comment]
I'm interested in working on this one and create a proper listener as @fabpot proposed, but I need to clarify some things first:

1. @stof you said that "If you generate it only in Symfony, some logs will not have the request id yet." Why this? If the listener has the highest priority (Before DebugHandlersListener) wouldn't it be ok?

```
[Event] kernel.request
+-------+----------------------------------------------------------------------------------+
| Order | Callable                                                                         |
+-------+----------------------------------------------------------------------------------+
| #1    | Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure()    |
| #2    | Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest()   |
| #3    | Symfony\Component\HttpKernel\EventListener\DumpListener::configure()             |
| #4    | Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest()  |
| #5    | Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest()   |
| #6    | Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest()     |
| #7    | Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest()     |
| #8    | Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest() |
| #9    | Symfony\Component\Security\Http\Firewall::onKernelRequest()                      |
| #10   | Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest()    |
+-------+----------------------------------------------------------------------------------+
```

2. What is the proposed way to generate unique ids? Is there something build in Symfony? Adding a depedency on https://github.com/ramsey/uuid is acceptable?

thanks

**Comment by dosten** [comment]
@phramz I think that he's talking about (apache|nginx|etc) logs.

**Comment by nicolas-grekas** [comment]
> What is the proposed way to generate unique ids

http://php.net/random_bytes

**Comment by babaorum** [comment]
Since, this issue is still open I guess you are still searching for an appropriate way to do this.
I just add the following monolog processor for my current project : 
```php
<?php

namespace App\Monolog\Processor;

class RequestIdProcessor
{
    private const HEADER = 'X-Request-Id';

    /**
     * @var null|string 
     */
    private $requestId;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestId = $this->id($requestStack);
    }

    public function processRecord(array $record): array
    {
        $record['extra']['request_id'] = $this->requestId;

        return $record;
    }

    private function id(RequestStack $requestStack): string
    {
        $request = $requestStack->getCurrentRequest();
        if ($request === null || !$request->headers->has(self::HEADER)) {
            return \bin2hex(\random_bytes(30));
        }

        return $request->headers->get(self::HEADER);
    }
}
```

Do you see any downsight on this solution ?

FYI: I used bin2hex around random bytes to get something simpler to manipulate.

**Comment by fabpot** [comment]
Closing as there is no traction on this issue. If one wants to submit a PR for that feature, that would be great.
