### ISSUE TITLE
public class variables of Custom validation constraint class are changed in Custom validation constraint validator class

### ISSUE THREAD

**Issue by mseshachalam** [symfony/symfony#11581]
Hi,

Symfony version is 2.3.18
I followed the http://symfony.com/doc/current/cookbook/validation/custom_constraint.html to create my custom constraint to validate a class. The constraint class has some public properties so they can be accessed in the validator class on constraint object, but some of the variable vaules are modified(set to other variables of the class).
dump of the constraint class in the validate function of Validator class
![validatoe](https://cloud.githubusercontent.com/assets/5608918/3825907/f7fb1b94-1d59-11e4-93fe-2382d4f8b0c1.png)

My Constraint class is 

```php
<?php

namespace BigPicture\FlamingoBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation(name="CampaignQuestionPrompt")
 * @Target({"CLASS", "ANNOTATION"})
 */
class CampaignQuestionPrompt extends Constraint
{
    public $questionMessage = 'Question text can not be empty';
    public $promptMessage = 'Either text or image is required else both can be present';
    
    public $xMessage = 'Hola';
    public $message = 'hi';
    
    public $subPath = 'question';
    
    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }
    
}
```

**Comment by mseshachalam** [comment]
@webmozart

**Comment by WouterJ** [comment]
I can't reproduce this bug on Symfony 2.7. I've used exactly the same constraint class as you did and all properties show up correctly in the validator.

As this issue is some months old, did you find the problem already? As it's labelled as unconfirmed for so long, I propose to close this issue.

**Comment by mseshachalam** [comment]
Thank you for checking. I am not sure about now. closing :+1:
