### ISSUE TITLE
[HttpFoundation] Request::isSecure does not check whether the proxy is trusted

### ISSUE THREAD

**Issue by ged15** [symfony/symfony#11583]
Hello!

```Request::isSecure``` checks whether there is at least 1 trusted proxy set (```(bool)self::$trustedProxies```), then validates the headers:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1129

```php
    public function isSecure()
    {
        if (self::$trustedProxies && self::$trustedHeaders[self::HEADER_CLIENT_PROTO] && $proto = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_PROTO])) {
            return in_array(strtolower(current(explode(',', $proto))), array('https', 'on', 'ssl', '1'));
        }

        return 'on' == strtolower($this->server->get('HTTPS')) || 1 == $this->server->get('HTTPS');
    }
```

Shouldn't it actually check whether the proxy is actually trusted by validating its IP address here?

**Comment by xabbuh** [comment]
Is this still an issue given the changes that were made in #14166?

**Comment by ricardclau** [comment]
Hi @xabbuh 

The new code looks much better so I am pretty sure the original issue is fixed with it. 
In fact, some users issues seem to confirm it (https://github.com/symfony/symfony/issues/15360)
