### ISSUE TITLE
Add a dedicated object to store a route name + parameters and accessible route object.

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#11642]
In Drupal we are dealing a lot with a common pattern: Provide the parameters for the url generator
and execute it later, if needed. 

Therefore we introduced an object which basically has the following constructor:

```php
class Url (bikeshed!!) {
    public function __construct($route_name, array $route_parameters) {}
}
```

Beside of having an object to manipulate and carry around, this for example saves you to use the url generator in too many places.

Once you add the route object as well to that object  (or load it from outside) you can even do check access to a potentially generated link without having to execute
a full kernel flow. This is a huge point for example, when generating a menu with a couple of links.

I wonder whether such an object could be useful inside symfony itself.

**Comment by javiereguiluz** [comment]
Closing it because some Symfony Core members, such as @stof, doesn't seem to agree with this idea.

**Comment by dawehner** [comment]
Well, its clear that the usecase of symfony is not that unopinionated that it claims to be.
