### ISSUE TITLE
ESI handler should not accept Surrogate-Capability from untrusted servers

### ISSUE THREAD

**Issue by dbu** [symfony/symfony#11664]
If there is a Varnish proxy configured as per [symfony doc](http://symfony.com/doc/current/cookbook/cache/varnish.html) this will actually not matter. But if the backend happens to be accessible directly, this exposes the esi urls which is not nice. 

Some users also use ESI with the symfony built-in cache, in which case symfony is reachable from the outside by design.

**Comment by javiereguiluz** [comment]
Closing it because at the end this wasn't a bug or security problem and the discussion stalled. Thank you all for the discussion.
