### ISSUE TITLE
[DX][DependencyInjection] Why MergeExtensionConfigurationPass restores original container params after extension configs merging?

### ISSUE THREAD

**Issue by fduch** [symfony/symfony#11693]
I have heavy SF2-based application that is built approximately in 40 minutes on the build server  because of great amount of assets with assetic filters to be compiled, different caches and etc. 
So if there is a need sometimes to make hotfix in application parameters (for example we need quickly change database host inside `parameters.yml`) - we should rebuild the application after fixes and wait for a while..

In order to workaround this drawback i wrote console command that allows to make *very quick* regeneration of *only* container cache after small changes made in application parameters  in emergency situations  right  on production backend. Obviously this parameters changes should not affect any caches except container cache, therefor it must be done carefully and only when it is emergency needed. 

This command works similar to `cache:clear` command - it also generates temporary kernel to regenerate caches but it does not invoke cache warmers  - it only boots the temporary kernel instead (invokes kernel `boot` method).
In order not to lose original container parameters (that can be set using environment variables during build process) i extend original Kernel class for temporary kernel object (just like `cache:clear` does)  by extending `getKernelParameters` method:
```php
//code for generation of tmp kernel - similar to the corresponding one in cache:clear command
$parentContainerParameters = var_export($this->getContainer()->getParameterBag()->all(), true);
// initializing other placeholders like $namespace, $class, $parentClass..
$code = <<<EOF
<?php
namespace $namespace
{
    use Symfony\Component\Config\ConfigCache;

    class $class extends $parentClass
    {
        // container builder inside the tmp kernel becomes now _all_ the parent container parameters
        protected function getKernelParameters()
        {
            return $parentContainerParameters;
        }
        //... some other extensions of the original Kernel class
    }
}
EOF;
```
So this approach works as expected in case of refreshing container cache after changing parameters set on application level (in application level configs - config.yml, parameters.yml, etc), but it DOES NOT work for example with parameters that is generated in bundle extensions using parameters set on application level. For example if i have *application.parameter1* set in `parameters.yml` and such bundle config in `config.yml`:

```yml
my_bundle:
    bundle_parameter: '%application.parameter1%'
```
.. and such code in MyBundleExtension:

```php
namespace Company\Bundle\MyBundle\DependencyInjection;

use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class MyBundleExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);
        $container->setParameter('my_bundle.container.parameter', $config['bundle_parameter']);
    }
}
```

The purpose is in `MergeExtensionConfigurationPass` behavior: it [RESTORES](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L57) original container parameters that are set on application level (just like application-level definition and aliases) after merging of extension configs. 

The main questions are: 
1. Why it is necessary? Does the main idea dictate to have "pure" application-level parameters and definitions (restored after changes made in bundle extensions) in the next compiler passes (that execute after merge pass)?
2. Which is right approach to solve problem in my use case?

Thanks in advice!

**Comment by javiereguiluz** [comment]
Closing it because the discussion stalled a few years ago and one of the mentioned bugs was fixed meanwhile. Please, reopen if you don't agree. Thanks!
