### ISSUE TITLE
URL's like http://.com or http://..com are considered valid by the UrlValidator

### ISSUE THREAD

**Issue by alinalexandru** [symfony/symfony#11702]
I think that URL's like http://.com or http://..com should not be considered valid.

**Comment by danielrose28** [comment]
I'm kind of new to this symfony triage initiative and would love to help with whatever I can. What would be a good next step for this issue? Thanks for any help/advice?

**Comment by nikita2206** [comment]
It is a valid URL according to [RFC 3986](https://tools.ietf.org/html/rfc3986). It defines grammar for hostname as the following:
```abnf
hostname = IP-literal / IPv4address / reg-name
reg-name = *( unreserved / pct-encoded / sub-delims )
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded = "%" HEXDIG HEXDIG
sub-delims = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```
In the end you interpret a URL `http://.com` as `{scheme: "http", hostname: ".com"}` where hostname `.com` is identical to `com`

**Comment by xabbuh** [comment]
Closing this issue as according to the RFC these URLs are valid.
