### ISSUE TITLE
Symfony 3.0 proposed backward incompatible changes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#11742]
This is a meta-issue that groups all the proposed backward incompatible changes for the upcoming Symfony 3.0 version. It includes more information than [the 3.0 milestone](https://github.com/symfony/symfony/milestones/3.0) because sometimes people propose ideas in the comments of the issues and pull requests.

#### Commands

* Make `assets:install` even smarter and create symlinks by default (without providing the `--symlinks` option) ([ref](https://github.com/symfony/symfony/pull/11312))
* ...

#### Console

* ~~As one may want to rely on the asset helper to generate URIs outside from a request (i.e., in a command-line, for sending e-mails), it should not depend on the request service, but rather on request_stack, in order to be available in a wider scope. ([ref](https://github.com/symfony/symfony/issues/11653), [related](https://github.com/symfony/symfony/pull/10264))~~
* `InputInterface` operates only with arguments passed to the Application. I suggest to add a method that would allow to operate with an input stream (`STDIN` in case of CLI application). ([ref](https://github.com/symfony/symfony/issues/10844))
* ~~`Symfony\Component\Console\Output\OutputInteface` should include the following methods: `isQuiet`, `isVerbose`, `isVeryVerbose` and `isDebug`. ([ref](https://github.com/symfony/symfony/pull/10214), [ref](https://github.com/symfony/symfony/pull/11115), #13086)~~
* ~~remove the shell feature (not that useful and bad side-effects see #11750)~~
* ...

#### DependencyInjection

* ~~Remove the concept of "scopes" for services. ([ref](https://github.com/symfony/symfony/issues/10557#issuecomment-38811755) #15693)~~
* ~~Remove all the `*.class` container parameters that define the namespace of the classes of the services ([ref](https://github.com/symfony/symfony/issues/11881) #14070)~~
* ...

#### DomCrawler

* Add support for fallback hidden fields. ([ref](https://github.com/symfony/symfony/issues/11689))
* ~~Cleaning the Crawler API. ([ref](https://github.com/symfony/symfony/issues/15849))~~
* ...

#### Forms

* `IntegerType` should be used for whole integers as the name suggests and not for floats. ([ref](https://github.com/symfony/symfony/issues/10240))
* `NumberType` should be used for floats (rendering as an `input[type="number"]`), and have a new option (for instance `support_locale_strings`) so that it renders as `input[type="text"]` and has the relevant attached `NumberToLocalizedStringTransformer`. ([ref](https://github.com/symfony/symfony/issues/10240))
* Remove duplicated HTML attributes. Right now, the attributes passed in the `attr` option are rendered both in the `<form>` tag and in the `<div>/<table>` tag of the form. ([ref](https://github.com/symfony/symfony/issues/7709))
* ...

#### FrameworkBundle

* ~~Methods of the base `Controller` class should be `protected` instead of `public` ([ref](https://github.com/symfony/symfony/issues/11294))~~
* Removed unused logger from DelegatingLoader, see #6298
* ...

#### HttpFoundation

* ~~Remove the request service ([ref](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack))~~
* Lazy initialization of Request headers. This can be a perfomance improvement for all requests which does not operate with request headers (almost all?) ([ref](https://github.com/symfony/symfony/issues/10077))
* ~~`Request->getRequestFormat()` should only rely on the request attributes. ([ref](https://github.com/symfony/symfony/pull/8967))~~
* Deprecate session as a service ([ref](https://github.com/symfony/symfony/issues/10557))
* ...

#### HttpKernel

* ~~Remove `isClassInActiveBundle()` method from `Kernel` and `KernelInterface` ([ref](https://github.com/symfony/symfony/issues/11652))~~

#### Security

* ~~`supportsClass` and `supportAttribute` are actually never used in Symfony except by voters themselves. They should be removed from the `VoterInterface`. ([ref](https://github.com/symfony/symfony/pull/11183/files#r14050436))~~
* A clear exception should be thrown if no voters voted on an attribute. So if you did a typo (e.g. `CREETE` instead of `CREATE`), you'd see a clear message, rather than nobody voting and access being granted/denied 100% of the time based on your voting strategy. ([ref](https://github.com/symfony/symfony/pull/11183/files#r14747264))
* Update UserInterface and UserProviderInterface to change the name of the methods `getUsername()` and `loadUserByUsername()` because they are confusing. You can identify your users bu email for example, so hardcoding `username` doesn't look right ([ref](https://github.com/symfony/symfony/issues/10722), [ref](https://github.com/symfony/symfony/issues/10316))
* ~~Deprecate SecurityContext and move its code to the AuthorizationChecker and TokenStorage. ([ref](https://github.com/symfony/symfony/pull/11690))~~
* Remove the RoleInterface and the Role class in favor of using strings only for roles: https://github.com/symfony/symfony/pull/8313#issuecomment-29796993 
* ...

#### Translation

* Replace custom and *hackish* solutions ([PR 4884](https://github.com/symfony/symfony/pull/4884), [PR 5547](https://github.com/symfony/symfony/pull/5547)) by the standard `MessageFormatter` PHP class. ([ref](https://github.com/symfony/symfony/issues/6009))
* ...

#### Web Profiler

* ~~Remove the import/export feature of the Web Profiler. ([ref](https://twitter.com/fabpot/status/504996074684448768)) -> see #15709~~
* ...

**Comment by Koc** [comment]
ref #9233, https://github.com/symfony/symfony/issues/6036#issuecomment-60523194

**Comment by Tobion** [comment]
I updated the description with current state.

**Comment by fabpot** [comment]
#15709 deprecates the profiler:import/export commands

**Comment by Tobion** [comment]
@fabpot there is still a "remove prototype scope (https://github.com/symfony/symfony/issues/12585#issuecomment-68245554)" todo item which would mean removing the "shared" flag on the DI again which was just added. Is it really wanted?

**Comment by WouterJ** [comment]
@Tobion this was discussed shortly during last meeting: https://gist.github.com/Nicofuma/2f75343c73aa75577b52#file-symfony-metting-L34-L81

**Comment by Tobion** [comment]
I see. It seems people agreed that the removing shared=false is not needed as it already exists and is documented (via prototype) and doesn't cause overhead. Factory use-cases also exist. So I'm removing that point from the list.

**Comment by fabpot** [comment]
`shared` should be kept.

**Comment by stof** [comment]
I added https://github.com/symfony/symfony/issues/15849 in the list. I already thought about this in the past (always in cases when I was reviewing PRs related to optimizing the component btw), but it looks like I never opened an issue to discuss it.

**Comment by javiereguiluz** [comment]
Closing this issue because we're so close to Symfony 3 launch that it no longer makes sense to have this meta-issue.

**Comment by dosten** [comment]
@javiereguiluz Maybe we can create a new issue with the pending issues or rename this one to target 4.0

**Comment by javiereguiluz** [comment]
@dosten I think it would be better to create a new issue.
