### ISSUE TITLE
[DX] Don't throw exceptions in twig when exception was thrown

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#11755]
Whenever an exception is thrown during the rendering of the template, you get 2 exceptions:

1. A Twig exception saying that the template could not be rendered because of an exception (including the previous exception message)
2. The previous exception

The first exception message is often way to long to be usefull and the second can quickly be missed. Why don't we just only show the second exception?

**Comment by fabpot** [comment]
Closing as the behavior comes from Twig, not Symfony. I've created an issue on Twig to gather feedback about removing the "extra" exception for Twig 2 (see twigphp/Twig#1587).
