### ISSUE TITLE
DependencyInjectionContainer id naming problem.

### ISSUE THREAD

**Issue by ivokoster** [symfony/symfony#11761]
Configured a service in the services.php with the id: 'testbundle.test_this'
Using it works perfect, except one strange behavior.

Calling it in your front controller with:
$this->get('testbundle.testthis');
Will throw no error, and gives you a NEW copy on the class, and replaces it in its container.
Calling $this->get('testbundle.test_this') afterwards will give you the NEW object.

Expected behavior: a error thrown of unknown id.

**Comment by fabpot** [comment]
As this is an edge which would break BC if we try to fix it, I think it's safe to mark this one as a won't fix.

**Comment by stof** [comment]
@fabpot Given that these generated methods are internal APIs, we could use a different replacement for underscores rather then using the empty char (the current generation turns snake case ids into camel cased method names, but this does not play well with the fact that PHP methods are case insensitive)

**Comment by fabpot** [comment]
@stof Indeed, we could keep the underscore.

**Comment by stof** [comment]
except we currently use the underscore to replace dots (which would then conflict). We need to find another way to replace dots in such case

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by oscherler** [comment]
It’s a highly mind-boggling problem if the affected service has an event listener (or maybe also a compiler pass) affecting it: getting the service with a missing or extra underscore in the name will give you a new instance that hasn’t had the listener run on it. It can take a while to determine where the problem comes from.

So yes, it’s an edge case, but a very time-consuming one.

How performant does the conversion from service name to method name have to be? Could `strtr` be replaced by something else? The conversion is done every time `get` or `has` is called, but that’s not something that should be done inside a loop, for example, so maybe a small performance hit would be acceptable?

**Comment by stof** [comment]
Well, we are now using a method map to handle. The remaining thing to fix this issue would be to make it the authoritative way for compiled container by dropping entirely the check for protected methods on the container.
@fabpot @nicolas-grekas what do you think about this change ? I'm all in favor of it. Regarding BC, it would break things only for people writing their own dumper for compiled container. And if we want to preserve BC, we could keep the existing logic, but only when the methodMap is empty (throwing a deprecation notice saying that the dumper should be updated to the new way)

**Comment by nicolas-grekas** [comment]
Looks like a good idea. I don't think we'd need to keep BC at this level, extending the generated protected methods would be really fragile anyway imho.

**Comment by stof** [comment]
the question is not about extending the generated protected methods, but about the way the list of compiled services are detected.
In previous versions (before the introduction of the methodMap to solve a related issue), the logic was based purely on detecting whether the factory method was defined in the class. Today, we could use the methodMap exclusively for that (and it *may* be faster by avoiding to do string transformations but doing a simple key lookup in an array). But if people are using the component standalone by writing a container by hand, they might not define the methodMap, and relying on the method detection logic.

Btw, I think keeping BC would not be hard. And the impact for people using the dumped container in Symfony would be limited to a ``if(empty($this->methodMap)`` extra check (returning false and so no extra logic) when trying to access (or check ``has()``) for a non-existent service. Any known service would already return earlier anyway.

**Comment by nicolas-grekas** [comment]
LGTM, let's try this way, BC bridge included then!

**Comment by stof** [comment]
I will work on it

**Comment by stof** [comment]
here you go

**Comment by oscherler** [comment]
A big (belated) thank you for your work on this. I would have liked to tackle it, but I lacked some understanding of how the container works. And also, you were so quick. ;)
