### ISSUE TITLE
[CSSSelector] Not works CSS selector :nth-child

### ISSUE THREAD

**Issue by Sorbing** [symfony/symfony#11803]
Does not work the next CSS selector: `li:nth-child(-n+6)`. I use:
```
$items = $page->findAll('css', 'li:nth-child(-n+6)');
```
Returns 0 items. jQuery successfully finds the necessary elements on the page.

**Comment by aik099** [comment]
If built xpath is correct, then this isn't an issue with this CssSelector component I guess.

**Comment by xabbuh** [comment]
@Sorbing Are you able to provide a failing test case?

**Comment by jakzal** [comment]
@Sorbing are you able to provide a failing test case @xabbuh was asking for, or perhaps a little snippet of code so we could reproduce your issue?

**Comment by Sorbing** [comment]
Hmm, I tried to reproduce the error but all works fine.. And I can not remember what I used a bunch of packages.
It's example works:
```php
use Symfony\Component\DomCrawler\Crawler;

require("vendor/autoload.php");

$html = file_get_contents("./example.html");
$crawler = new Crawler($html);
$crawler->filter('li:nth-child(-n+6)')->each(function(Crawler $node, $i) {
    echo $node->text() . ", ";
});

// output: 1, 2, 3, 4, 5, 6, 
```
File `example.html`:
```html
<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li>7</li>
    <li>8</li>
    <li>9</li>
</ul>
```
I think the issue can be closed. Thank you for your time.
