### ISSUE TITLE
[DX] Call $form->createView() automatically

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#11818]
A mistake that I frequently see is that people forget to call `createView()` when passing a form to the view. What do you think about converting `FormInterface` instances to `FormView` objects automatically by calling `createView()`, for example, in a listener?

**Comment by fabpot** [comment]
Closing as there is apparently no way to implement this in a generic way that would work well in all cases.

**Comment by MaPePeR** [comment]
Apparently this behavior was implemented in 6.2 or 6.3 without a changelog entry, and it's a breaking change and there seems to be no way to unsubscribe from this, besides wrapping forms as arrays to protect them from this "DX", that could have been solved with a hint in the Exception Message?

Previously you could pass a `Form` directly to a template and call `createView()` multiple times on the same `Form` - e.g. as part of a loop:

```twig
{% for key, value in something %}
    <!--- render something -->
    {% set subForm = form.createView() %}
    {{ form_start(subForm) }}
    {{ form_widget(subForm.some_hidden_field, {attr: {value: key}}) }}
    {{ form_end(subForm) }}
{% endfor %}
```

This allowed to easily reuse the same `Form` multiple times on the same page e.g. for multiple rows of data. Like suggested [here (8k views)](https://stackoverflow.com/questions/31337409/how-to-render-same-form-multiple-times-in-symfony2) and [here (6k views)](https://stackoverflow.com/questions/36286012/symfony3-render-multiple-time-same-form).

Is there another documented way of achieving this that I'm missing? Haven't found any so far.

**Comment by wouterj** [comment]
It is mentioned in the CHANGELOG-6.2.md file in the release, as well as on https://symfony.com/blog/new-in-symfony-6-2-dx-improvements#simpler-form-rendering

If you need more help, I recommend to use one of the [support channels](https://symfony.com/support). Not many people are notified of new messages on old and solved issues :)

**Comment by stof** [comment]
> This allowed to easily reuse the same `Form` multiple times on the same page e.g. for multiple rows of data. Like suggested [here (8k views)](https://stackoverflow.com/questions/31337409/how-to-render-same-form-multiple-times-in-symfony2) and [here (6k views)](https://stackoverflow.com/questions/36286012/symfony3-render-multiple-time-same-form).

Rendering the same form multiple times on the page would lead to duplicate ids, which are invalid HTML and will break accessibility (as labels won't be associated to the correct input).
