### ISSUE TITLE
[Form] add "locales" option to LocaleType

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#11847]
It would be nice to have an option named for instance `allowed_locales`, that when set, would cause the widget to display only locales that appear in it, and would throw an exception if one of them can't be found in `Intl::getLocaleBundle()->getLocaleNames()` keys. If this is something that you think would be useful, I can write the code and make a PR.

**Comment by Hanmac** [comment]
i also vote for that. i need that for some other choices.

another idea for that feature which can be done in the parent choice type
would be an callback which is used as filter to check if that element should be in that list or not.

**Comment by sstok** [comment]
I will take a stab at this 👍

**Comment by yceruto** [comment]
See another alternative to achieve it https://github.com/symfony/symfony/pull/18334

**Comment by xabbuh** [comment]
closing in favour of the more generic #32657
