### ISSUE TITLE
Add (or fix) the missing Dependency in Twig bundle

### ISSUE THREAD

**Issue by ddebernardy** [symfony/symfony#11876]
The Twig Bundle masquerades as being standalone but its ExceptionListenerPass class in fact depends on a templating.engines parameter which I believe is defined here:

https://github.com/symfony/FrameworkBundle/blob/master/Resources/config/templating.xml

**Comment by fabpot** [comment]
Closing this ticket. The Twig bundle is not meant to be used standalone, the Twig bridge is. I've opened a PR trying to make the bundle less dependent on FrameworkBundle and be able to move things more in the bridge for better reusability.
