### ISSUE TITLE
[SecurityBundle] SwitchUserListener deal with attemptSwitchUser and LogicException

### ISSUE THREAD

**Issue by spike31** [symfony/symfony#11879]
Hi,

I would like to know how you deal with the SwithUserListener and the LogicException here : https://github.com/symfony/symfony/blob/397687f345f4ea83f344a54275f4bc328ac2d4b4/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L91    ?

Example, from your backend you switch on user, then you change again with an other user and you have a LogicException. Ok.
So with on the kernel.exception I can get this exception but I don't know if this LogicException is throw from this Listener or an other.

May be we need a specific exception.

This was introduced by this PR https://github.com/symfony/symfony/pull/3580

**Comment by Soullivaneuh** [comment]
I agree with the issue. Currently, if we wan't to properly handle it, we have to do tricky things like exception message compare. Not very reliable.

Having an `AlreadySwitchedUserException` or something like that would be largely enough and not hard to implement IMHO.

> Just hide it if the user is already impersonating someone

If the end user have multiple windows of your website containing this button, he will ran on the issue in any case.

**Comment by Shoplifter** [comment]
Maybe instead of throwing an exception at all it's time to reconsider/reopen this old issue  https://github.com/symfony/symfony/issues/12797 again?

There  have been (now outdated) solutions around to tackle this problem:
http://shout.setfive.com/2014/11/25/symfony2-making-impersonating-a-user-more-friendly/
https://adayinthelifeof.nl/2015/02/24/advanced-user-switching/

**Comment by xabbuh** [comment]
If I understand the issue correctly, there's not much we can do with the current implementation though having something like #27348 implemented would solve this issue too. So I am closing here in favour of #27348.
