### ISSUE TITLE
Use classes and interfaces to represent the shipped ICU data

### ISSUE THREAD

**Issue by bojanz** [symfony/symfony#11887]
This issue discusses the new intl API that's being made in #9206.
I've opened it because I believe this discussion is outside the scope of that PR (and would probably have a very different target version).
The current code also has the same approach (API with static methods).

The ICU data ships with definitions for currencies, countries, languages and more.
However, since the API imitates ICU itself, it feels odd and less PHP-like.
Instead of returning objects with the relevant information, the central service has a static method per relevant property that returns an array.

Here's a currency example:
```php
$currencyCode = 'EUR';
$numericCode = Currency::getNumericCode($currencyCode):
$fractionDigits = Currency::getFractionDigits()
$name = Currency::getName($currencyCode);
$symbol = Currency::getSymbol($currencyCode);
```

Now let's compare that to how commerceguys/intl does it:
```php
$repository = new CurrencyRepository();
// Get the USD currency using the default locale (en).
$currency = $repository->get('USD');
echo $currency->getCurrencyCode();
echo $currency->getNumericCode();
echo $currency->getFractionDigits();
echo $currency->getName();
echo $currency->getSymbol();
```

In the second example we get an object implementing the CurrencyInterface.
This is important because in most ecommerce scenarios there is a need for the admin to modify existing currencies or define custom new ones, which leads to currencies being stored in the database.  So, a Doctrine entity can implement the CurrencyInterface and behave just as the currency created from default definitions, as far as the rest of the system is concerned.

webmozart said:
> It does not represent individual I18N objects (currencies, locales etc.) as objects - for performance > reasons. For example, if you need a list of locale names, initializing an array of hundreds of Locale > objects first adds noticeable overhead. 

I'm not convinced because we already have the cost of all those arrays storing the names, symbols, fraction digits, etc. Arrays have been shown to be very expensive.
Having an array of typed objects instead provides a much cleaner API that can integrate nicely with other components and systems. If there's a performance impact, it's well worth it, but I'm prepared to do benchmarks.

**Comment by bojanz** [comment]
We're a month away from the 2.7 freeze, and I'm still interested in making this happen, but I'm unable to find a good way forward.

The fact is that the entire currency is not a value object. A currency value object needs only a currency code. The rest is definitely entity-like. A currency can change fraction digits (due to inflation) while still not becoming a different currency, for example. Same for locale specific names.
This is a problem discussed at http://verraes.net/2013/11/value-objects-and-user-interfaces/ where the proposed solution was to have both an entity and a value object which represents only the three letter code. (This entire argument applies the same to countries, currencies, languages).

The second part of webmozart's suggestion was to have Currency::get() load the currency itself, by calling the repository internally. This couples the object to the repository, and means that overriding the repository needs to be done by calling a global Currency::setRepository(), which feels very unclean. As I mentioned previously, storing currencies in the database is very common for an ecommerce application, and having to figure out where to do the global override doesn't feel good.

**Comment by peterrehm** [comment]
Any progress in this regards? I am closing the related #12775 as @webmozart discarded the proposal in #12804 in favor of this PR.

**Comment by webmozart** [comment]
Thinking about this again after some time passed, I think that we don't need to and won't be able to fit every use case. Projects that need value objects for currencies, languages or others mostly have specific requirements.

In order to move things forward, I think we should focus on providing convenient access to CLDR data only. See #18368.
