### ISSUE TITLE
[feature request][web profiler] show listener priority

### ISSUE THREAD

**Issue by mrbase** [symfony/symfony#11915]
it would be really useful if we could have the weight of listeners in the profiler panel, eks:

Event name | Listener | Weight
---------------- | ----------- | -------
kernel.request | ErrorsLoggerListener::injectLogger | xxx

**Comment by dupuchba** [comment]
@mrbase @stof any news on this one ? I need to retreive listeners priority for my project ?

**Comment by javiereguiluz** [comment]
This can be closed as "fixed" because the redesigned web profiler already displays the listener priorities.

**Comment by kix** [comment]
@javiereguiluz, thanks!
