### ISSUE TITLE
[Yaml] Improve exception messages for unsupported features

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#11911]
There are quite a [some issues](https://github.com/symfony/symfony/issues?q=is%3Aopen+is%3Aissue+label%3AYaml) for the Yaml component which are related to parts of the Yaml specification that are (currently) not supported. Instead of throwing a raw ``ParseExcetion`` we should try to detect when someone uses such an unsupported feature and throw a more meaningful message like "Feature foo is not supported by the Yaml component".

**Comment by fabpot** [comment]
Closing as I still think this is not worth it or even impossible. Of course, anyone can prove me wrong by submitting a PR :)
