### ISSUE TITLE
[Validator] Replace Date, DateTime and Time by Timestamp

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#11925]
At the moment, we have three constraints for validating date/time values:
- `Date` accepts `\DateTime` instances and 'Y-m-d' strings
- `DateTime` accepts `\DateTime` instances and 'Y-m-d H:i:s' strings
- `Time` accepts `\DateTime` instances and 'H:i:s' strings

I think that's a bit confusing. Usually, a value should not be a `\DateTime` _or_ a string, but either of them; if it is a string, it should usually match a specific pattern.

Therefore I propose to deprecate all three constraints. The `\DateTime` case can be solved with the `Type` constraint already:

``` php
/**
 * @Assert\Type('\DateTime')
 */
private $createdAt;
```

The second case would be covered by a new `Timestamp` constraint which accepts a format as argument as [supported by PHP](http://de2.php.net/manual/en/function.date.php):

``` php
/**
 * @Assert\Timestamp('Y-m-d')
 */
private $createdAt;

/**
 * @Assert\Timestamp('c')
 */ 
private $iso8601Date;
```

This would fix #11919 and replace #11821.

**Comment by gimler** [comment]
actually i run into this problem @webmozart do you have time to implement it? if not i can do this for symfony 3.0.

**Comment by lepiaf** [comment]
Should I add deprecation on Date, DateTime and Time validators ?

**Comment by Jean85** [comment]
I agree with @Tobion, this change will make not possible to accept multiple formats for the same input..

**Comment by lepiaf** [comment]
As @javiereguiluz said in https://github.com/symfony/symfony/pull/21905#issuecomment-284709362, what do you think about reworking DateTimeValidator to include this change and deprecate TimeValidator and DateValidator?

**Comment by nicolas-grekas** [comment]
Closing as this is old, and @Tobion raised a point that is not answered since years.
