### ISSUE TITLE
[ExpressionLanguage] Support callables

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#11938]
I think it would be useful to support the execution of callables in the ExpressionLanguage component in order to support dynamic extension. Is this possible?

``` php
$language->evaluate('matchesConstraint(value)', array(
    'value' => $value,
    'matchesConstraint' => function ($value) { ... },
));
```

**Comment by nicolas-grekas** [comment]
Closing as this is an old issue, and having pending hard to implement things doesn't help if we don't have implementers.
