### ISSUE TITLE
Symfony/console - change to be a pure CLI router not a dispatcher

### ISSUE THREAD

**Issue by Danack** [symfony/symfony#11974]
Hi, this is a BC feature request for Symfony 3. Also let me apologize in advance if I come across as rude - the symfony/console is almost really great - but the feature change below is needed to allow it to be re-usable imho.

Currently the Symfony/console library does two main things, parse the command line options to choose which command to run, and then execute that command.

If you're using constructor dependency injection in your code, this makes it very hard to use the library in a sane way. All of the possible commands that could be run have to be completely constructed, along with all of their dependencies, which is not desirable. This kind of forces you to use Service Locator to get the dependencies for your objects. Service locators are almost always bad - but just in general having a library make other bits of code have to be written in a certain way is bad.

I think it would be much better if the console library just did the parsing and routing, and returned a [ParsedCommand](https://github.com/Danack/Console/blob/master/lib/Danack/Console/Command/ParsedCommand.php) object which contained all of the information needed to execute the required code for the command, but left the actual 'dispatch' of the callable to other code.

I've actually done this in my fork: https://github.com/danack/console It's obviously not a big change to the actual code, though it almost certainly requires a major version to be done.

So after the refactor using the Console commands would look more like:

``` php
//Setup a command
$helloWorldCallable = function ($name) {
    echo "Hello world, and particularly $name".PHP_EOL;
};

//Create a command that will call the closure
$callableCommand = new Command($helloWorldCallable, 'greet');
$callableCommand->addArgument('name', InputArgument::REQUIRED, 'The name of the person to say hello to.');


//This callable requires a DB connection - but because it is never called, the program
$backupCallable = function (DBConnection $dbConnection) {
     // runs a backup process on the database.
};

//Create a command that will call the closure
$backupCommand = new Command($backupCallable, 'backup');

$console->add($callableCommand);
$console->add($backupCommand);


//Setup a console application
$console = new Application();


try {
    //Returns ParsedCommand on success or throws exception on parse error
    $parsedCommand = $console->parseCommandLine();
}
catch(\Exception $e) {
    $output = new BufferedOutput();
    $console->renderException($e, $output);
    echo $output->fetch();
    exit(-1);
}

//Execute the callable with the parsed params.
$provider = new Auryn\Provider();
$provider->execute(
    $parsedCommand->getCallable(),
    tagScalarParams($parsedCommand->getParams())
);

```

Obviously any library that acts as a DIC capable of executing code could be used, Auryn is used just as an example.

Thoughts?

**Comment by J7mbo** [comment]
> This is easy to use only in case you rely on an auto-wiring container, and we don't have this in Symfony.

We have something *close* to it though, with `autowire: true` as of 2.8, right?

**Comment by javiereguiluz** [comment]
Closing it because we're trying to fix this issue in a different way. See #22734. Thanks!

**Comment by Danack** [comment]
@javiereguiluz The solution that has been raised in that ticket seems complex and a workaround for the fundamental problem that combining the 'routing' of commands with the dispatching of commands is a 'bad idea', which is why most modern frameworks separate those two concerns in HTTP contexts; not separating them in CLI contexts seems just the wrong thing to do.

Separating the 'routing' and dispatching of CLI commands would allow for a simpler solution than having lazy loading 'magic' going on, which always makes it harder to reason about what is actually happening inside an application.

I realise github comments are never the best place to discuss philosophical differences in software architecture - do you guys have a more appropriate place to discuss this?

**Comment by nicolas-grekas** [comment]
See #23510 btw

**Comment by nicolas-grekas** [comment]
I don't see what's complex with implemeting `CommandLoaderInterface`. Basically, it's what you say: a intermediary "router" between names and commands.

**Comment by Danack** [comment]
> I don't see what's complex with implementing CommandLoaderInterface

It requires you tie things that are being executed with the thing that does the executing. This is not a good design in HTTP; it is also not a good design in CLI.

Danack commented on 21 Sep 2014:
> And just to re-iterate, it doesn't need to be a command class - it can be any callable *i.e closure, string that represents a function name, static or public method on a class and reflection methods, for example a plain function would be called as:

People should be able to dispatch 'just' functions, rather than being forced to create classes.
