### ISSUE TITLE
Add helpers for the new console style guide

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#12014]
The problem
-----------------

  *  We want to define and enforce a style guide for Symfony commands (see https://github.com/symfony/symfony/issues/11784)
  * There is already a proposal for this style guide (https://github.com/symfony/symfony-docs/issues/4265)
  * We need to make it really easy to follow the style guide once it's approved.

The solution
----------------

The first obvious proposal would be to add more helpers to [FormatterHelper](https://github.com/symfony/Console/blob/master/Helper/FormatterHelper.php), such as `formatTitle()`, `formatSectionTitle()`, `formatList()`, `formatDebugInfo()`, `formatNoteBlock()`, etc.

Anyway, I would prefer to read your opinions about better and more concise solutions.

**Comment by fabpot** [comment]
@javiereguiluz There is probably some tickets to create as follow-ups of this one.
