### ISSUE TITLE
[Console] Colors in Command Name and Description

### ISSUE THREAD

**Issue by aequasi** [symfony/symfony#12051]
Not sure if this is desired, but you can specify format options when defining a `Command`'s name and description.

```php
protected function configure()
{
    $this
        ->setName('<fg=blue>acme:demo</fg=blue>')
        ->setDescription('<fg=blue>Acme Demo Command Example</fg=blue>');
}
```
Putting a fg style on the description seems to function fine, adding a color to the description, but adding a color to the name puts it at the top of the list, and looks a little janky.

**Comment by fabpot** [comment]
Don't think there is anything to do here.
