### ISSUE TITLE
[Form] Add "list" attribute to HTML5 fields

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#12068]
Certain html5 input types like `text`, `url`, `range`, `color` etc support the `list` attribute by implemented a `datalist`.  Even though its trivial to add this to your own code without too much effort, it might be nice to support this out of the box as well by supporting  the `choice` or `choice_list` options which generate the datalist automatically.

See [this site](http://www.wufoo.com/html5/attributes/05-list.html) for more information.

An example, the following would be supported:

```
        $form = $this->createFormBuilder()
                ->add('city', 'text', array(
                    'datalist' => array('Amsterdam', 'Paris', 'Rome', 'Milan')   // Array or ChoiceListInterface 
                ))
                ->getForm();
```

Generates something like:

```
<div>
    <label for="form_city" class="required">City</label>
    <input type="text" id="form_city" name="form[city]" required="required" list="form_city_datalist"/>
    <datalist id="form_city_datalist">
        <option>Amsterdam</option>
        <option>Paris</option>
        <option>Rome</option>
        <option>Milan</option>
    </datalist>
</div>
```

Example: http://jsfiddle.net/8qb2tb5n/

On non-supporting browsers, this will fall back to not using the list at all.

**Comment by DavidBadura** [comment]
for simple text fields: https://gist.github.com/DavidBadura/94e8636f8fec5d9a2a03

**Comment by pawansingh123** [comment]
The option "datalist" does not exist occurred when i tried the same code

**Comment by xabbuh** [comment]
I am closing this old issue as it seems nobody is interested in making it happen.

**Comment by Nayte91** [comment]
Hello, Currently playing around with datalist, and following the mdn page, it seems that datalist is literraly an extension of input; As such, a TypeExtension is the right candidate, and getExtendedTypes() list will be something like:

```php
public static function getExtendedTypes(): iterable
{
    return [
        TextType::class,
        SearchType::class,
        UrlType::class,
        TelType::class,
        EmailType::class,
        PasswordType::class,
        NumberType::class,
        DateType::class,
        TimeType::class,
        DateTimeType::class,
        RangeType::class,
        ColorType::class,
    ];
}

public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setDefined(['suggested_values']);
}
```

Template extension will be easy, as linking the datalist tag by id to a "list" attribute for the input.

Main concern is more around the type of the 'suggested_values' value:

```php
if (isset($options['suggested_values'])) {
    //Test if suggested values is an array, it will be simple like below
    $view->vars['choices'] = $options['suggested_values'];
    //Test if suggested is a closure, pass the parameter
    //Test if suggested is a class, find how to fetch elements (extend DoctrineType ?)
    //Test if enum to throw, as Enum should not be allowed, it's just suggestions but Enums are hard choices
}
```
I wonder if I can implement the features of the DoctrineType inside my 'suggested_values' array key, where value will be an array of options? If I can do so, it will be quite easy to pass just a classname, and it will automatically fetch values (just have to define which property of the classes will be displayed). If it's not that simple... Well, it's not that simple.
