### ISSUE TITLE
[Console] Refactor the Console component for lazy-loading of commands

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#12063]
Commands have to be instantiated to be registered in the console application:

``` php
$application = new Application();
$application->add(new GreetCommand);
```

That's a problem, for example if you have commands with big dependency graphs: it loads all the dependencies in memory. It's also not very practical when using `Symfony\Console` outside of the framework: integrating it with a DI container is not practical.

I would like to discuss a new way to register commands which would allow them to be lazy loaded. That requires to have the definition of their names outside of the command itself (else the lazy loading is useless).

To do this, there are several options. 
### 1. Closures

The first one would be to leave the opportunity to provide a callable that returns the command:

``` php
$commandFactory = function () {
    return new GreetCommand();
}

$application = new Application();
$application->add($commandFactory, 'greet');
```

That option is BC compatible, but not that good for DX, not very practical.
### 2. CommandResolver

This is inspired by how HttpKernel works.

``` php
$application = new Application();
// Classic command
$application->addCommand('greet', array('Acme\AcmeDemoBundle\Command\GreetCommand', 'execute'));
// Invokable class (i.e. implements __invoke())
$application->addCommand('greet', 'Acme\AcmeDemoBundle\Command\GreetCommand');

// first parameter: the command name
// second parameter: a way to identify the command (string or array)
```

The HttpKernel uses a `ControllerResolver` to create controllers. The Console component could have a `CommandResolverInterface`:

``` php
interface CommandResolverInterface
{
    /**
     * @param string|array $command
     * @return callable|false A PHP callable representing the Command,
     *                        or false if this resolver is not able to determine the command
     */
    public function getCommand($command);
}
```

That would leave the option to implement this interface using any DI container.

That option could be made BC compatible. However it requires more work and it's a big change in the component.

---

I would really favor the second solution (or something similar). I've read the discussions about that topic, I know opinions are diverse.

**I just want to emphasize that I don't want to make Symfony\Console too similar to HttpKernel**. Some have suggested that in the past (me included), and I know this won't happen. I am not suggesting to merge Request and Input for example. I am just suggesting to separate the command routing from the command creation, just like it is in HttpKernel.

**Comment by gnugat** [comment]
Is this issue still relevant? If so, will it still be taken into account for the next release (2.7)?

**Comment by mnapoli** [comment]
Bumping again, we are having the problem in [Piwik](https://github.com/piwik/piwik) too.

We can't afford instantiating all the commands with all their dependencies (and their dependencies…) just to start the console, that could potentially lead to loading **the whole application** in memory… (I'm exaggerating just a bit :p)

**Comment by gnugat** [comment]
I'd like to also highlight the following use case: displaying help using database (for example to set an option's default value).
This is currently impossible in a symfony full stack application, as it would prevent it from being installed: in order to create the database and the schema, we need to run some console commands, which means loading all commands including the one which tries to make a database query to set the default value of an option.

Just my two cents :) .

**Comment by webmozart** [comment]
I also had this problem when using the Console component for Puli. I refactored the component into https://github.com/webmozart/console, which is usable now.

You can see examples of its usage here:

* https://github.com/puli/cli/blob/master/src/PuliApplicationConfig.php
* https://github.com/puli/web-resource-plugin/blob/master/src/Console/WebConsoleConfig.php

I'm not sure whether it makes sense to replace the Symfony Console component by that implementation for 3.0.

**Comment by mnapoli** [comment]
@webmozart I had a look before at your package and I really love it. However it's really far from the current state of Symfony Console (probably for good reasons), that's the main downside I see.

**Comment by funivan** [comment]
@mnapoli I create PR #16438 . Can you check it and said if this logic cover your needs.
Your custom command resolver can create commands when they are really needed by Application.

For example `CustomCommandResolver` https://github.com/funivan/symfony/blob/console-command-resolv/src/Symfony/Component/Console/Tests/Fixtures/CustomCommandResolver.php
This class hold reference map `name => command class`
When Application invoke `$commandResolver->get('lazy')` Our command resolver create command and return it.


@gnugat hello =) Show help without command initialization is possible with `CommandResolver`. 
How you can do this: 
- create custom command resolver
- add method `getCommandHelp($commandName)`;
- create custom command `ShowHelp` and register it
- in `ShowHelp` command just invoke `$commandResolver->getCommandHelp($id)`

If we create `getCommandsDescription` in commandResolver interface we can refactor `ListCommand` to access only command names, not objects. So by default application will initialize all commands and return their description. But for lazy loading we can implement any logic (for example store description in cache)
```php
foreach($resolver->getAllName() as $name){
    $output->writeln($name .'    '. $resolver->getCommandDescription($name));
}
```

**Comment by funivan** [comment]
Is there any progress in this issue ?

**Comment by TomasVotruba** [comment]
For forthcoming, check PR #16438 16438

**Comment by mnapoli** [comment]
@TomasVotruba FYI I had open #13946 at the time too.

**Comment by TomasVotruba** [comment]
@mnapoli Thanks for reference.

**Comment by fezfez** [comment]
see this other solution https://github.com/fezfez/symfony-console-di

**Comment by chalasr** [comment]
See also #22734
