### ISSUE TITLE
[Console] Problems with ConsoleOutput

### ISSUE THREAD

**Issue by bgalileo** [symfony/symfony#12097]
I'm not entirely sure this is a bug in symfony, but I cannot reproduce it without using symfony/console, so I thought I'd report it here.

We have an Intranet application which uses several Symfony components and (among other things) manages connection information for different servers. Since we need to mount some of those servers via SSHFS, I created a mount script which simply calls the Intranet application:

`/sbin/mount.server`:

``` php
#!/usr/bin/env php
<?php

// … setting $intranet_path and parsing $argv into $arguments …

$exitCode = 0;
passthru("php {$intranet_path}/console.php mount {$arguments}", $exitCode);
exit($exitCode);
```

Intranet application: `console.php` (simplified):

``` php
<?php
class MountCommand extends Command {
    protected function configure() {
        $this->setName('mount')
             ->addArgument('SERVER', InputArgument::REQUIRED)
             ->addArgument('MOUNTPOINT', InputArgument::REQUIRED);
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        if (posix_getuid() !== 0) {
            return 1;
        }

        $server = $input->getArgument('SERVER');
        $mountpoint = $input->getArgument('MOUNTPOINT');

        // … get connection information from the database

        $process = new Process(
            sprintf(
                'sshfs -o %5$s,password_stdin %2$s@%1$s:%3$s %4$s',
                escapeshellarg($ssh_host),
                escapeshellarg($ssh_user),
                escapeshellarg($ssh_folder),
                escapeshellarg($mountpoint),
                escapeshellarg($ssh_options)
            ), null, null, $ssh_password, 60, []
        );
        $process->run();
        if ($process->isSuccessful()) {
            return 0;
        } else {
            return 1;
        }
    }
} 

$app = new Symfony\Component\Console\Application();
$app->addCommands([new MountCommand()]);
$app->run();
```

When I run `mount -t server {SERVER} /mnt/{SERVER}` now, it mounts the server but the mount command does not return until I run `umount /mnt/{SERVER}` in a different terminal. `ps` and `pstree` show me that the php process which ran `console.php` exited, but the php process which ran `/sbin/mount.server` won't collect its defunct `sh` child process. This does not seem to be a bug in `passthru()`, since I got the same behavior when I replaced `/sbin/mount.server` with a shell script and tried to let autofs mount some servers automatically (automount refuses to collect its child process until the server is unmounted).

Why am I reporting this as a bug in the Console component? When I replaced `console.php` with a PHP script which doesn't use symfony/console, the problem did not occur anymore. It also does not occur if I replace

``` php
$app->run();
```

with

``` php
$app->run(null, new NullOutput());
```

After days of debugging I still have no idea what exactly is happening, but the `ConsoleOutput` class seems to be doing something which causes this weird behavior.

**Comment by nicoschoenmaker** [comment]
Managed to reproduce what I think is the essence of this bug. Save this file as `bug.php` in a folder that has `symfony/console` available.
```php
<?php
use Symfony\Component\Console\Output\ConsoleOutput;

require 'vendor/autoload.php';

echo 'Start' . PHP_EOL;

function run() {
    $output = new ConsoleOutput();
    // Run a child command that you want to run independantly
    exec('sleep 2 > /dev/null 2> /dev/null &');
}

run();
echo 'PHP script end' . PHP_EOL;
register_shutdown_function(function () { echo 'shutdown called' . PHP_EOL; });
```
Running `php bug.php` works as expected (within milliseconds).
Running `php -r 'passthru("php bug.php");'` takes two seconds to run!

Expected: a command that executes in milliseconds.
```
Start
PHP script end
shutdown called
```

Actual: a command that waits for the 2 second sleep of the child process.

**Comment by nicolas-grekas** [comment]
Closing as this should be fixed by using the new 3.3 way of creating processes (and have "exec" be autoprefixed then.)

**Comment by mb-g** [comment]
FYI: With PHP 7.2 and Symfony 4.3, the unwanted behavior can still be reproduced. `mount2.php` from the above example will hang at the `exit()` call until the processes spawned by `sshfs` exit. This behavior differs from what happens when you call `sshfs` in your shell.
The only workaround is using `StreamOutput(fopen('php://output', 'w'))` instead of `ConsoleOutput()`.

**Comment by arnegroskurth** [comment]
The bug still reproduces with PHP 7.4 and `symfony/process` 5.2.7.

Any news on this?
