### ISSUE TITLE
[HTTPFoundation] The ResponseHeaderBag::set method should be aware of Set-Cookie header

### ISSUE THREAD

**Issue by ajgarlag** [symfony/symfony#12111]
When a ResponseHeaderBag is built, if a `Set-Cookie` header is set, it should be parsed to fill the internal `cookies` property.

Code:

``` php
$responseHeaderBag = new \Symfony\Component\HttpFoundation\ResponseHeaderBag();
$responseHeaderBag->set('Set-Cookie', 'FOO=bar; path=/; domain=example.org');
echo count($responseHeaderBag->getCookies());
```

Actual output: `0`
Expected output: `1`

**Comment by fabpot** [comment]
Closing as nobody stepped up to do an actual implementation.
