### ISSUE TITLE
Vary headers not taking effect if passed as Array in response object.

### ISSUE THREAD

**Issue by epicwhale** [symfony/symfony#12118]
I am seeing a difference in caching behaviour between using ```$response->setVary(["Accept-Encoding", "X-Foo-A", "X-Foo-B"]);```  v/s using ```$response->setVary("Accept-Encoding, X-Foo-A, X-Foo-B"); ```

The first one sends the correct Vary headers, but does not actually cache it.. if I try querying the same URL with a different value for one of the headers, it gives me the same cached response with a cache HIT instead of missing it. Basically the Vary header response seems to be sent, but is not taking an actual effect on the Caching rules.

BUT, the second one works as expected. Querying the same URL with a different value for one of the vary headers gives a Cache Miss. 

I am using symfony's app cache for testing.

Notes on my setup:

1. I am using Symfony's HTTP Cache Kernel
2. I am using FOSRestBundle
3. I am using Postman to create / inspect the response
4. Using symfomy 2.4

**Comment by pmalmsten** [comment]
I also encountered this bug today using Synfony 2.6.4 stable (commit 23b647f1e4eeb24a457d3c47f5f5046377d5a3bf).

From a response object generated by the application, printed using var_dump:

```
["vary"]=>
  array(2) {
    [0]=>
    string(15) "Accept-Encoding"
    [1]=>
    string(6) "Cookie"
  }
```
However, at multiple places in Symfony\Component\HttpKernel\HttpCache\Store, the implementation of the storage layer for AppCache, the vary header array is treated as a single-element array. 

Here's a key example from `lookup` on line 130:

```php
           if ($this->requestsMatch(isset($entry[1]['vary'][0]) ? $entry[1]['vary'][0] : '', $request->headers->all(), $entry[0])) {
```
The vary header array is indexed at element 0, returning only the first member. The `requestMatch` method then receives only one "Vary" header as an argument when considering whether a request matches, and therefore determines matches incorrectly.

**Comment by jakzal** [comment]
@epicwhale @pmalmsten could any of you guys see if #14635 fixes your issue?
