### ISSUE TITLE
AJAX requests not excluded as expected

### ISSUE THREAD

**Issue by romqin** [symfony/symfony#12122]
I just tried the new feature [AJAX requests in the web debug toolbar](http://symfony.com/blog/new-in-symfony-2-6-ajax-requests-in-the-web-debug-toolbar) by replacing `"symfony/symfony": "~2.5"` with `"symfony/symfony": "2.6.*@dev"` (don't know if there is a better solution for doing it) and I saw something weird :

![capture d ecran 2014-10-04 02 17 45](https://cloud.githubusercontent.com/assets/334432/4514080/ed632dc2-4b5b-11e4-8016-bd43b1e43cf1.png)

I would have your opinion before doing a PR for solving this problem.

The default configuration for the option `excluded_ajax_paths` is `^/bundles|^/_wdt`.
But the web debug toolbar is visible only in `dev` and the urls are `app_dev.php/...`.
So, I thought of 2 solutions:

1. update the standard edition `app/config/config_dev.yml` file by adding in the web_profiler : `excluded_ajax_paths: "^/app_dev.php/bundles|^/app_dev.php/_wdt"`
2. add the environment in the default value of `excluded_ajax_paths`

What do you think ?
Is there a better solution ? Or the problem is just because I didn't use it the right way.

**Comment by romqin** [comment]
I'm agree with @layanto and @Tobion

**Comment by fabpot** [comment]
:+1: for removing `/bundles` from the regex.
