### ISSUE TITLE
[Debug] publish symfony_debug on brew and pecl

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#12154]
The symfony_debug extension should be available with brew and pecl.

**Comment by rcross** [comment]
For easier reference, it was pointed out that the extension is located here https://github.com/symfony/Debug/tree/master/Resources/ext

**Comment by nicolas-grekas** [comment]
For building on Windows, be could borrow ideas from:
https://github.com/phalcon/zephir/blob/master/appveyor.yml

**Comment by nicolas-grekas** [comment]
Closing as the ext is not going to be supported on PHP 7, thus it will die eventually.
