### ISSUE TITLE
document fields and logic related to account and credentials expiration

### ISSUE THREAD

**Issue by thkoch2001** [symfony/symfony#12177]
The AdvancedUserInterface in the Security Component[1] provides fields and functions which might be useful for our project[2][3] but are not documented:

* isAccountNonExpired()
* isCredentialsNonExpired()

The strange naming suggests that those functions were copied from spring-security[4]. Is there something to learn in the spring documentation about how to expire credentials?

* How can the credentials_expire_at column be filled with a date N days after now on every password change?
* How can a user still change the password, if the password is already expired? The user can't login to reach the password-change action.
* How to warn the user about the passoword expiration some days in advance?

[1] Symfony\Component\Security\Core\User\AdvancedUserInterface
[2] http://stackoverflow.com/questions/24610229/how-to-use-the-credentials-expired-property-in-symfony-advanceduserinterface
[3] https://groups.google.com/forum/#!topic/symfony2/1R3lNWB5H4w
[4] http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/core/userdetails/UserDetails.html

**Comment by gondo** [comment]
however this will be used in the future be aware, that `isCredentialsNonExpired` nor `checkPostAuth` are called when user is authenticated via RememberMe functionality. (i've spent fair amount of time trying to figure how this whole thing work #13712)

**Comment by javiereguiluz** [comment]
Closing it as fixed. The PHP class now defines PHPdoc for these methods and the docs explain them briefly here: http://symfony.com/doc/current/cookbook/security/entity_provider.html#forbid-inactive-users-advanceduserinterface
