### ISSUE TITLE
[HttpKernel] unserialize() conflicts with extended constructor

### ISSUE THREAD

**Issue by KingCrunch** [symfony/symfony#12232]
[`Kernel::unserialize()`](https://github.com/symfony/symfony/blob/8e42756c375ac73d4fc2a00a24a23281bb3be082/src/Symfony/Component/HttpKernel/Kernel.php#L807) prevents one from extending the constructor. Even when I overwrite `serialize()` and `unserialize()` something tries unserialize my custom `AppKernel`-class with some inappropiate during cache creation.

**Comment by iltar** [comment]
@KingCrunch this issue isn't present for me anymore and I don't think this will be fixed. Is the issue still something you consider should be fixed?

**Comment by KingCrunch** [comment]
I am a little bit confused of this phrase

> this issue isn't present for me anymore and I don't think this will be fixed.

If it isn't present anymore, it is fixed, right? 

However, back in the days I used a different approach, thus for me it is not relevant anymore, what doesn't mean, it doesn't exists, or that it can affect other people.

**Comment by iltar** [comment]
This issue was for our custom kernel implementation for symfony1 migration, but most of our apps have been migrated to a point where we no longer need it.

**Comment by javiereguiluz** [comment]
Let's close this issue because @KingCrunch and @iltar no longer consider it relevant. We'll reopen it if we get more reports about this. Thanks!
