### ISSUE TITLE
[Form] Always submit GET forms if present in request

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#12244]
Currently, GET forms are only submitted if the request method is GET. If the URL however contains the GET parameters of the form (e.g. "filter[sort]", "filter[direction]"), and a POST request is sent (f.i. to submit a different form "blog") to the URL containing the filter parameters, the parameters should be written into the form again.

This can be done manually by calling

```php
if ('GET' !== $request->getMethod()) {
    $filterForm->submit($request->query->get('filter'));
}
```

However, would it be better to *always* consider a GET form submitted if the corresponding parameter is available in the query string?

**Comment by HeahDude** [comment]
What if there is some GET parameters that are not related to the form ?

They would be always submitted whereas they are meant for other purpose.

Would this even work in that case without setting `allow_extra_fields` to `true` ?

It seems impossible to distinguish different cases, I don't see how this could be handled globally by the component.
I think it should be up to the dev to know what to do with extra parameters, like merging them before submission or "manually" call different form submission as @webmozart suggested.

**Comment by webmozart** [comment]
@HeahDude I agree. The fix I described in the issue should be good enough for those rare cases.

**Comment by ostretsov** [comment]
It's possible just to clone `Request` object and set `GET` method before handling.
