### ISSUE TITLE
[Form] Emit warning if submitting an empty form

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#12262]
A warning should be logged if a form is submitted that contains no fields apart from the (automatically added) CSRF token. See #11774.

**Comment by HeahDude** [comment]
So it should happen in `Form::submit()` after the `PRE_SUBMIT` event has been processed to take into account dynamic addition of fields, right ?

**Comment by webmozart** [comment]
Thinking about the BC impacts of this change, there could be forms that contain a collection form only and are allowed to be submitted without items being added to the collection. Those forms would then trigger warnings if submitted without fields, even though that is a normal situation for them. Implementing more functionality to suppress the warnings doesn't justify the (small) benefit IMO.
