### ISSUE TITLE
[HttpFoundation] Can't set status code 202 together with a Location: header

### ISSUE THREAD

**Issue by danilogiacomi** [symfony/symfony#12289]
I'm basically reopening an old issue [https://github.com/symfony/symfony/issues/8267] here as it still doesn't behave as expected.

As stated in http://tools.ietf.org/html/rfc7240#section-4.1 it is valid to have a Location header along with a 202 StatusCode in a HTTP response, still symfony forces it to be a 302, even if you try to set it manually.

**Comment by fabienwarniez** [comment]
Is this bug up for grabs? I want to contribute to Symfony and this bug seems to be in my league.

**Comment by fabpot** [comment]
@fabienwarniez Sure, looks like an easy pick (except if the conversion is done by PHP itself.)

**Comment by danilogiacomi** [comment]
Actually the problem is inside PHP, so there isn't much to do in Symfony to fix that.

I guess this issue is just invalid
