### ISSUE TITLE
[3.0] [Validator] Remove Blank/NotBlank constraint

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#12300]
I think that the Blank/NotBlank constraints should be removed in 3.0. It's not quite clear what the constraints do (see #9961) and I guess we're better off if we just removed it. People can use other, more specific constraints instead, such as True, Length, Count etc.

**Comment by webdevilopers** [comment]
:+1:

**Comment by TomasVotruba** [comment]
3.0 is already here.
What's current state of this? What would be the suggested replacement?

**Comment by webmozart** [comment]
@TomasVotruba The problem is, as @stof said, that we can only deprecate these constraints if we remove the `'' !== $value` checks from all *other* constraints validators. Otherwise empty strings will be ignored by all validators.

Any other solutions or can we only do this as part of the 4.0 release?

**Comment by TomasVotruba** [comment]
@webmozart Ok, that sound clear to me. Can prepare PR if this gets accepted.

**Comment by HeahDude** [comment]
I'm 👎 here in the way it is described, what we should do is:

- document that `false` is invalid with `NotBlank` as for empty string and null,
- better document difference between `NotBlank` and `NotNull` (the last one having to be used for boolean types)
- deprecated invalid behavior for invalid state of `false` with `Blank`,
- rename `Blank` and `NotBlank` to `Empty` and `NotEmpty` that would better reflect what it does mimicking PHP wording and behavior.

**Comment by xabbuh** [comment]
Let's close here in favour of #27876.
