### ISSUE TITLE
[Validator] Throw exception if caching a non-serializable constraint

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#12302]
Origin of this ticket: 

Currently, metadata caching fails if a constraint is not serializable. The only core constraint that is susceptible to this problem is the Callback constraint when used with an object method or closure:

``` php
// OK
new Callback(array('SomeClass', 'validateMe'));
new Callback('validateMeFunction');

// Not OK
new Callback(array($this, 'validateMe'));
new Callback(function ($value, $context) { ... });
```

When trying to serialize the last two constraints, an error is raised (#10083) that is a little hard to debug.

Two solutions come to mind:
- Disallow closures/objects methods in Callback and require _all_ constraints to always be serializable. I don't quite like this, since I find passing closures to Callback very useful (e.g. in the "constraints" option of the Form component). After all, caching is not always necessary.
- Add a method `isSerializable()` to `Constraint`. This would return `true` by default and `false` in edge cases. If caching is turned on, `GenericMetadata::addConstraint()` checks `isSerializable()` and fails if an unserializable constraint is added.

The second solution adds minor overhead (the additional function call in `addConstraint()`), but only if metadata is not cached. I prefer that solution since it maintains the current flexibility, but returns a useful error message when a constraint is not serializable.

What do you think?

**Comment by uwej711** [comment]
See https://github.com/symfony/symfony/pull/20740 for a possible fix

**Comment by nicolas-grekas** [comment]
I'm closing this one, because #20793 fixes the Symfony related part, and the remaining part is fixed by using Symfony Cache, which handles serialization failures properly (no exception, no write).
