### ISSUE TITLE
Fatal error working with Doctrine

### ISSUE THREAD

**Issue by SweetLemonade** [symfony/symfony#12307]
When I'm getting data from the DB, it's okay. But if I persist or update some data, the profiler shows in explain query of the "START TRANSACTION" and "COMMIT" following:

>Catchable fatal error: Argument 2 passed to Doctrine\DBAL\Connection::resolveParams() must be of the type array, null given, called in /symfony-app.loc/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 702 and defined in /symfony-app.loc/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1366

It's working fine, but queries execute much slower and I worry about it.

What is the problem?

**Comment by fabpot** [comment]
Can we close this one?

**Comment by SweetLemonade** [comment]
Yes.
