### ISSUE TITLE
[Validator] Decouple type validation from constraint validators

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#12312]
Several issues have been raised in the past because of the validator's inconcistent type validation. Some constraints through UnexpectedTypeExceptions, others add constraint violations, others ignore unexpected types. This should be fixed.

An indepth preliminary discussion of this topic can be found here:
https://github.com/symfony/symfony/issues/10221#issuecomment-34960446

The way I envision this to happen is by changing the `Type` constraint to a meta-constraint (like `Valid` or `Traverse`), which is handled by the validation engine directly. Currently, this constraint specifies:
1. what type an element should have (or any)
2. what violation message should be added if the type does not match

``` php
/**
 * @Type("int", message="This field expects an integer.")
 * @GreaterThan(0)
 */
private $price;
```

While the `$type` option of the `Type` constraint is mandatory at the moment, it will become optional. Instead, each constraint will have a new method returning the accepted types:

``` php
class GreaterThan extends Constraint
{
    // ...

    public function getAcceptedTypes()
    {
        return array(self::INT, self::FLOAT);
    }
}
```

Now the validation engine will take care that a given value matches the types expected by each constraint. If not, a constraint violation will be added. The `Type` constraint can be used to customize the violation message:

``` php
/**
 * @Type(message="The price should be a number.")
 * @GreaterThan(0)
 */
private $price;
```

We need to change `GenericMetadata::addConstraint()` to validate the compatibility of the defined constraints:
- When adding a normal constraint, the expected type should be set to the intersection of all "accepted types" (dependent on the validation group). If the expected type is empty, the constraints conflict and an exception should be thrown.
- When adding a `Type` constraint, the expected type is set manually. Again, check that there are no conflicts with the other constraints on that property.

The constraint validation process can then be adapted in the following way:
1. Get the expected type for the current node
2. Get the actual type (`gettype()`) of the node's value
3. Check that the actual type matches one of the expected types. Otherwise, raise a constraint violation.
4. Validate all "normal" constraints. Only validate a constraint if the node's value is not `null` or if `null` is in the expected types of that constraint.

Consequences:
- While the `Type` constraint currently accepts any type for which either `is_<type>()` or `ctype_<type>()` is defined _or_ which is a class name, that would be restricted to the results of `gettype()` and `get_class()`. A BC layer needs to be provided in some way.

Related issues:
- #6799
- #9502
- #11076
- #11083
- #11590
- #11956
- #12163

**Comment by webdevilopers** [comment]
:+1:

**Comment by k3nn7** [comment]
Hey, it looks like this topic is dead for some time. Is it because there is some other solution or workaround for this problem?

I'm currently struggling with one of the issues described here (`UnexpectedTypeException` is thrown e.g. from `Length` constraint even if I use it together with `Type("string")` constraint).

Because of that I need to either do some preliminary validation/data transformation (but I will hide some errors or won't be able to easily group all of them together) to make sure that types are right or wrap validators with some custom `Composite` constraint that will ignore `UnexpectedTypeException` (but it has security problems described in previous comments).

**Comment by lordjancso** [comment]
I would live to have some workaround or a fix. Still no news?
I already asked it in #17758.
