### ISSUE TITLE
[Validator] Access container array in Expression/Context

### ISSUE THREAD

**Issue by slavafomin** [symfony/symfony#12315]
Hi!

We can use [Expression](http://symfony.com/doc/current/reference/constraints/Expression.html) constraint on the object's property and [object itself will be accessible from inside the expression via `this` keyword](http://symfony.com/doc/current/reference/constraints/Expression.html#reference-constraint-expression-option). However, when validating plain arrays instead of objects, we can't access array itself, in this case `this` has a `null` value. I think we should also allow entire array to be accessed from inside the expression.

Here's example of how it can be used with form builder:
https://gist.github.com/slavafomin/805d36fe671fbdc3aced

**Comment by Arkemlar** [comment]
After 3 years seems like this feature still not implemented.. sad.

**Comment by fabpot** [comment]
@Arkemlar ... which means nobody stepped up to implement it. Would you like to give it a go?

**Comment by Engerim** [comment]
@fabpot I would try to implement it, it seems not so complicated.

**Comment by yceruto** [comment]
Related to https://github.com/symfony/symfony/issues/22403 ;)
