### ISSUE TITLE
Handling exception thrown in contoller rendered by twig

### ISSUE THREAD

**Issue by coviex** [symfony/symfony#12334]
in Bundle:Article:show.html.twig:5:

```twig
{{ render(controller('Bundle:Comment:list')) }}
```

in Comment::listAction():

```php
throw $this->createNotFoundException();
```
result:

> An exception has been thrown during the rendering of a template ("Not Found")
> in Bundle:Article:show.html.twig at line 5.
> 500 Internal Server Error - Twig_Error_Runtime
> 1 linked Exception: NotFoundHttpException

...

> CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: 
> "An exception has been thrown during the rendering of a template ("Not Found") 
> in "Bundle:Article:show.html.twig" at line 5." 
> at /vendor/twig/twig/lib/Twig/Template.php line 294

if I throw that same exception from `Article:showAction()` it shows my custom error template from `app/Resources/TwigBundle/views/Exception`.
I wonder if "linked" exception could also be handled automatically.

**Comment by fabpot** [comment]
This is controller by the the `ignore_errors` options that you can pass to the `render()` function.
