### ISSUE TITLE
[Kernel] deprecate X-Status-Code

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#12343]
The handling of the `X-Status-Code` header in der kernel introduced in https://github.com/symfony/symfony/commit/788e5eb730ad1c0436c519cf0b878fc48b854044 is a hack and just introduced as a workaround. First of all it's magic (why this header?) and second of all it disallows to actually return such a header because it's removed automatically. So you cannot send a response with this header even if you need to.
It should be deprecated and replaced by a better solution. Alternatives:
1. practically there already exists a solution without this magic header: http://stackoverflow.com/a/26520225/1382727
2. or better add a `GetResponseForExceptionEvent::allowSuccessfulResponse` setter/getter to the event. When true (default false), it will use the Response status code even if it's a 2xx for an exception.

**Comment by stof** [comment]
@desarolla2 have you got any result on this ?

**Comment by desarrolla2** [comment]
Nop, sorry.

**Comment by devsdmf** [comment]
Updates ?

**Comment by jameshalsall** [comment]
@devsdmf I've created a PR with this work
