### ISSUE TITLE
[DX][Form] Defining validation groups on form field level should throw an error

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#12342]
Talk is cheap, show me the code:
```php
class MyFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('foo', 'text', [
            'constraints'       => new Constraints\Length(['min' => 6]),
            'validation_groups' => 'Bar',
        ]);
    }
 }
```
I expected this code to be equivalent to:
```php
class MyFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('foo', 'text', [
            'constraints'  => new Constraints\Length(['min' => 6, 'groups' => 'Bar']),
        ]);
    }
 }
```
But it is not, validation groups are not respected in the first case.

If it cannot be fixed before 3.0, then it can at least throw an error like:

`You cannot define validation groups to a form field, consider passing it as an option to your constraints.`

**Comment by xabbuh** [comment]
Closing here as I think we won't change the behaviour of the Form component's Validator extension. 

However, the bahaviour of how the option is evaluated (only on the root form) is something that must be document to mitigate confusion. We have an issue for this in the docs repository (see symfony/symfony-docs#4401) and we will appreciate any contribution to fix that long standing issue.
