### ISSUE TITLE
[HttpFoundation] Response status logic not according to RFC

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#12347]
`isRedirect`: why is 201 considered a redirect, but 305 or 300 not? Also it does not check whether there is a Location header at all. So without Location header, 201 is definitely not a redirect.

**Comment by fabienwarniez** [comment]
What is the difference between these 2 methods?

**Comment by phansys** [comment]
@fabienwarniez, like @alexislefebvre said ```Response::isRedirection()``` returns true if response's status code is between 300 and 399 accordingly to [RFC2616](http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) (see also [this document](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) at w3.org) while ```Response::isRedirect()``` is focused on a more practical uses; only return true if the status code is one of these: ```201```,  ```301```,  ```302```,  ```303```,  ```307```,  ```308``` and if location argument is given, it performs an equals check against ```Location``` header. Note that except the first one, the rest are in the desired range (>=300, <400) while as today from 309 to 399 are unassigned. I think the reason for this behavior (as @Tobion said) is that often when a resource is created (201) the returned response points to it.

**Comment by ro0NL** [comment]
@Tobion is there any reason to keep it this way? This ticket is almost 2 years old.. so it looks like it's not going to change. But why? Cant we agree 201 is _not_ a redirect?

**Comment by scaytrase** [comment]
Any news here? I've faced this as a bug, that within `dev` env the redirect interception occures for me instead of returning proper JSON response from controller (is 201 with JSON valid here, yes?), so it' really a bug here
