### ISSUE TITLE
Router 3.0 improvements

### ISSUE THREAD

**Issue by harikt** [symfony/symfony#12357]
Hi, 
I am sure this will not be for 2.x series. Somethings that I like if you are making the 3.0 move.

I have been looking the https://github.com/symfony/Routing/blob/48c201da53b7c3b787609b0f6702456b86939577/Matcher/RequestMatcherInterface.php#L38

and the method 

```php
     public function matchRequest(Request $request)
    {
        $this->request = $request;

        $ret = $this->match($request->getPathInfo());

        $this->request = null;

        return $ret;
    }
```

defined in https://github.com/symfony/Routing/blob/48c201da53b7c3b787609b0f6702456b86939577/Matcher/RequestMatcherInterface.php#L38

for the request is made to null. And the only functionality is to get the path and pass to the match method.

Why not remove the matchRequest itself ?

So it can be made like 

```php
$parameters = $matcher->match($request->getPathInfo());
```

Also I am seeing the Request from Context can be moved out to make a bundle to wrap the Router and Http rather than keeping inside the class.

I would like to see Symfony 3.0 as much more better standalone components. And bundles which wraps the components so they can use Symfony/RouterHttpFoundationBundle/Router or something like that for easy usage. So others who make use of standalone don't need to bother too much.

Thank you for hearing.

**Comment by Tobion** [comment]
Closing as stof explained why the request object is set before and after the matching. So it cannot be removed.
