### ISSUE TITLE
Process doesn't work as expected if command contains exclamation mark on Windows

### ISSUE THREAD

**Issue by borekb** [symfony/symfony#12350]
I'm using Symfony Process to execute [wp-cli](http://wp-cli.org) commands and one of them was something like this:

    wp post create --post_title="Hello VersionPress!" --post_date="2011-11-11 11:11:11"

If I executed this command on Windows `cmd` it worked fine but when Symfony Process ran it, the post title was created as "Hello VersionPress11:11" and the data was generally not right, even though the command technically succeeded (no error).

After some experimenting, it seems that **the exclamation mark is somehow a problem**. When I removed it, all worked fine. Is that a bug in Symfony Process on Windows or maybe some kind of misconfiguration on my side?

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback. If the issue persist in a supported Symfony version, please reopen the issue. Thanks!
