### ISSUE TITLE
[Form] Count constraint with handleRequest and a PATCH request

### ISSUE THREAD

**Issue by pierregaste** [symfony/symfony#12361]
Hi,
I try to apply the Count constraint in one of my form element, which is submitted with the PATCH method (http_method_override enabled).
I used ```$form->handleRequest()``` to submit my form and ```$form->isSubmitted() && $form->isValid()``` to check if I can process the form.

When I do this with the POST method, the constraint Count correctly apply and the form is not valid. Logic.
When I do this with the PATCH method, the constraint "Count" is not apply and the form is valid. Not logic.
When I do this with the PATCH method and the ```$form->submit()``` method, the constraint is correctly apply and the form is not valid. I don't understand why it's work.

Is using the ```handleRequest``` with a PATCH method could create some types of troubles ?

I reproduce my problem in a simple Symfony project and you could check my code here : 
https://gist.github.com/pierregaste/2704f4117ed583ea6095

Thanks for helping!

**Comment by HeahDude** [comment]
As explained by @ogizanagi with a PATCH method fields without submitted data are ignored so validation does not happen.

This old issue can be closed as it is an expected behavior: validation happens only after binding.
