### ISSUE TITLE
Translation not processing trans tags

### ISSUE THREAD

**Issue by a-carvallo** [symfony/symfony#12414]
In a twig template inside AcmeDemoBundle :

``` twig
{% trans %}trans tag will not appear{% endtrans %}
{{ 'trans filter will appear'|trans }}
{{ 'transchoice filter will appear'|transchoice(1) }}
{% transchoice 1 %}transchoice tag will appear{% endtranschoice %}
```

php app/console translation:debug en AcmeDemoBundle

```
+----------+--------------------------------+--------------------------------+
| State(s) | Id                             | Message Preview (en)           |
+----------+--------------------------------+--------------------------------+
| x        | trans filter will appear       | trans filter will appear       |
| x        | transchoice filter will appear | transchoice filter will appear |
| x        | transchoice tag will appear    | transchoice tag will appear    |
+----------+--------------------------------+--------------------------------+

Legend:
 x Missing message
 o Unused message
 = Same as the fallback message
```

"trans tag will not appear" is missing in the output.

Symfony version : 2.5.6

System tested :
Windows 8.1 Pro, Apache 2.4.4, PHP 5.4.16
Ubuntu 14.04,  Apache 2.4.7, PHP 5.5.9

**Comment by stof** [comment]
@alex-cc Trans tags with the plural tag are not meant to be used in Symfony, because they are not using the Symfony Translation system. The Twig-extensions I18n implementation uses gettext directly.

If you want an extractor for this extension, ask the Twig-extensions project, not Symfony.

**Comment by WouterJ** [comment]
> If you want an extractor for this extension, ask the Twig-extensions project, not Symfony.

Seems to indicate that this issue can be closed. Or do we want this issue to be transformed into a "make the extractors more dynamic to support other twig extensions" feature request?

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" in Symfony project ... but maybe it will be fixed in the Twig extensions project. Thanks!
