### ISSUE TITLE
console config:debug wrong output when using prependExtensionConfig 

### ISSUE THREAD

**Issue by markus-rothenbacher** [symfony/symfony#12438]
When changing the config of a different Bundle, as described here:
http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html
it works perfect as described.

But when I run "console config:debug" on the Bundle I have changed the configuration for, it does not show my changes via the prependExtensionConfig method and only shows the parameters from the config.yml

So in short: config:debug is not able to debug prependExtensionConfig statements.

PS: I am using Symfony 2.5.6

**Comment by davide-romanini** [comment]
This bug is still present in 2.6.1. This significantly limits the usefuleness of the `debug:config` command, since tipically you need it to cope with complex dynamic configurations.
