### ISSUE TITLE
Symfony 2.6, error with Impersonate User

### ISSUE THREAD

**Issue by williamdelvalle** [symfony/symfony#12435]
I'm getting an error when I try to impersonate a user, this error only happens with symfony 2.6 and I get the "access denied" message or redirects me to the login page, I clarify that I'm using a user with role ROLE_ALLOWED_TO_SWITCH

**Comment by javiereguiluz** [comment]
I'm closing this issue because it refers to Symfony 2.6, which is no longer maintained.

@williamdelvalle thanks for reporting this issue. If you updated the application to Symfony 2.7 or higher and the error persists, please reopen this issue or create a new one with more details. Thanks!

**Comment by agiratech-mani** [comment]
@javiereguiluz : i am using Symfony 2.8.4, Am having the same issue.

**Comment by xabbuh** [comment]
@agiratech-mani Can you open a new issue? The best would be if it also included the steps to reproduce your problem (for example, you can fork the Symfony Standard Edition, make the needed changes, and link to it).
