### ISSUE TITLE
$event->getData() returns null for an embedded collection form

### ISSUE THREAD

**Issue by Djevil83** [symfony/symfony#12442]
Hi, 

 My problem is the same that this one => #6128.

I tried to retrieve an entity with $event->getData() in an embedded form like this:

```php
$builder
        ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            var_dump($event->getData());
            exit();
        });
```

but the var_dump($event->getData()); always return null when in the parent form the collection field has the option 'allow_add' => true. When i change this option to 'allow_add' => false, the $event->getData() return the entity as expected.

Could you please fix this bug ?

My symfony version is : 2.5.6

**Comment by leechao** [comment]
I have the same problem here and I'm currently working on a 2.7.3 version of Symfony. 
Is there any fix planned ?

**Comment by igdr** [comment]
I have the same issue with collection type, there are items when I call get method directly, but in form this field has empty value

**Comment by Isinlor** [comment]
i was struggling with this as well. This bug occurs because in `Symfony/Component/Form/Extension/Core/Type/CollectionType.php:32` CollectionType is adding prototype:
```
        if ($options['allow_add'] && $options['prototype']) {
            $prototype = $builder->create($options['prototype_name'], $options['type'], array_replace(array(
                'label' => $options['prototype_name'] . 'label__',
            ), $options['options']));

            $builder->setAttribute('prototype', $prototype->getForm());
        }
```

It should be enough to set option 'prototype' to false in collection configuration. It seems like generating prototypes based on data is more a feature request than a bug.

**Comment by umpirsky** [comment]
I am facing the same issue.

For me, if I set `'prototype' => false`, `PRE_SET_DATA` is never dispatched.

**Comment by umpirsky** [comment]
My workaround was to trigger event on child collection form from parent:

```php
class ParentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) {
            $event->getForm()->get('children')->getConfig()->getEventDispatcher()->dispatch(
                FormEvents::POST_SET_DATA,
                $event
            );
        });
...
```

**Comment by umpirsky** [comment]
I have reproduced it against latest symfony-standard https://github.com/umpirsky/symfony-standard/commit/4cef1a8404973da8d4704e760bb6f3dd82e2a7c0.

/cc @webmozart

**Comment by umpirsky** [comment]
I figured it out. It was my data that was wrong.

For the reference I tried to reproduce it, and it worked:

Symfony 2.7: https://github.com/umpirsky/symfony-standard/commit/8f8d19a97d56713a9026592d5542056a723cab46
Symfony 3: https://github.com/umpirsky/symfony-standard/commit/4cef1a8404973da8d4704e760bb6f3dd82e2a7c0

**Comment by webmozart** [comment]
Does this mean we can close this issue?

**Comment by umpirsky** [comment]
@webmozart As far as I tested, it works.

The tricky part was that my data was wrong, for example I passed array in one format, and expected was in different format.

No error, no warning, just `$event->getData()` returns `null`.

**Comment by Isinlor** [comment]
@webmozart It's not a bug. There is simply no way to use dynamic form type (i.e. modified based on `$event->getData()` results) as a prototype, but people are still trying to do this and get confused. It should be documented how to handle such situation - one must handle prototype generation and related logic on his own.

**Comment by ScreamZ** [comment]
+1, passed so many time, unable to handle case with prototype...

**Comment by HeahDude** [comment]
Hi @ScreamZ, there has been a lot of issues opened about that and they are all closed.

The 'PRE_SET_DATA' listener of an entry form of a `CollectionType` is called for every entry including the prototype when `prototype` option is not `false` and `allow_add` option is `true`.

Consider using the workaround mentioned in https://github.com/symfony/symfony/issues/6128#issuecomment-65076206 if you are using symfony <= 2.7
or `prototype_data` option introduced as of 2.8.

Cheers

**Comment by skrosoft** [comment]
In my case, the problem is that I want to add field, depending of the value of the getData() instance and the EventListener doesnt allow me to add field to the form.
