### ISSUE TITLE
[Constraints] New Entity Count constraint

### ISSUE THREAD

**Issue by Paxton** [symfony/symfony#12455]
Hi,

I am proposing a new constraint that validates the count of entities cannot exceed specified maximum using specified fields.

**Not like existing count constraint which is used on specific field**

More like UniqueEntity.

E.g.

``` php
/**
 * @ORM\Entity
 * @CountEntity(
 *     fields={"account"},
*      max=5,
 *     message="You cannot have more than {{max}} services."
 * )
 */
class Service
{
    /**
     * ... Some relation here ...
     * @ORM\Column(type="integer")
     */
    public $account;
}
```

So what happens in background, Symfony makes a count query using configured DBAL with the specified fields as discriminators, if the result exceeds max, then a violation is raised.

This would be an extremely helpful constraint used on almost any entity that can be created by user, especially via APIs to limit abuse.

I am aware that this example could be achieved by setting count constraint on the inverse side of relation. However, this is not always the case. You might want to stop the system creating entities that do not have relations when their count exceeds certain amount. 

Thanks

**Comment by Paxton** [comment]
@stof

I think this constraint is applicable to only fresh entities, and I think that's fine, in fact, even better. Given you are PATCH'ing and existing entity, you probably wouldn't want this behavior.

**Comment by xabbuh** [comment]
This looks like an edge case to me that should rather live outside the Validator component. Therefore I am closing here. Thank you for proposing anyway.
