### ISSUE TITLE
[yaml] #-sign inside string literals inside collections are seen as comments

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#12478]
When using collections, string literals starting with # are still seen as comments, and are stripped. However, it works correctly in normal items.

      test: |
        foo
        # bar
        baz
      collection:
        - one: |
            foo
            # bar
            baz
        - two: |
            foo
            # bar
            baz

This will result in:

      Array(
          [collection] => Array (
                  [0] => Array( [one] => foo\nbaz )
                  [1] => Array( [two] => foo\nbaz )
          )
          [test] => foo\n#bar\nbaz
      )

while expected:

      Array(
          [collection] => Array (
                  [0] => Array( [one] => foo\n#bar\nbaz )
                  [1] => Array( [two] => foo\n#bar\nbaz )
          )
          [test] => foo\n#bar\nbaz
      )

I've checked with the yaml pecl extension, and this works as expected.

**Comment by jezhalford** [comment]
I'm seeing this issue too - a fix would be a wonderful thing.

**Comment by xabbuh** [comment]
see #16860
