### ISSUE TITLE
http_cache with validation will build the content twice

### ISSUE THREAD

**Issue by GDmac** [symfony/symfony#12484]
Contrary to the docs, http://symfony.com/doc/current/book/http_cache.html#varying-the-response
> ... If two people request the same URI of a cacheable resource, the second person will receive the cached version ...

If the cache is empty, the cache will be build twice for the two requests.

**Expected**: request A generates the response for the uri and stores in cache, 
request B waits untill (locked) cache is ready.
**Experienced**: request A generates the response for the uri and stores in cache,
request B also generates the response for the uri and also stores in cache.

**Comment by fabpot** [comment]
Indeed, there is no lock mechanism in the HttpCache sub-system. For this, you should use a "real" reverse proxy like Varnish.

**Comment by GDmac** [comment]
The docs should then probably not mention the above
> ... If two people request the same URI of a cacheable resource, the second person will receive the cached version ...

**Comment by xabbuh** [comment]
@GDmac The docs don't assume that two people request the same resource "at the same time", but one after another. Though feel free to open an issue on the documentation repository if you think that this should be clarified.
