### ISSUE TITLE
`interger` and `number` do not return correct `empty_data`

### ISSUE THREAD

**Issue by hpatoio** [symfony/symfony#12499]
Given this simple form. 

``` php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('votes', 'text', array('empty_data' => 0))
        ;
    }
```

If I leave the field `votes` empty when I submit the form `$form['votes']->getData()` gives me `0`

If I change the field type to `number` or `integer`

``` php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('votes', 'number', array('empty_data' => 0))
        ;
    }
```

`$form['votes']->getData()` gives me `null`

Is this the correct behavior ? Is this related to #5906 ?

**Comment by xabbuh** [comment]
The `empty_data` option expects the given data to be in the format of the type's view data. In case of the `NumberType`, this must be a string as this is what will be received during submission of the form. Therefore, the observed behaviour is expected and you must use the string `'0'` to achieve what you are trying to do. Thus, I am closing here as this is no bug. Thank you for understanding.
