### ISSUE TITLE
The Filesystem component cannot rename between different drives

### ISSUE THREAD

**Issue by stof** [symfony/symfony#12533]
Because it only tries the PHP `rename` function, the Filesystem component inherits its limitation about being restricted to a single drive.
See https://github.com/symfony/symfony-installer/issues/46#issuecomment-63951753 for an issue caused by that.

composer implemented a fallback logic to be able to rename between drives: https://github.com/composer/composer/blob/edd4b2f984821fa696f1be848f9d5b5aea449537/src/Composer/Util/Filesystem.php#L260
It might be worth integrating it in the Filesystem component

**Comment by LewisW** [comment]
Just for reference if anyone is using Docker, there's a high chance they will come across this problem if their cache directory is originally created in a separate layer (i.e. at the build stage).

**Comment by andrerom** [comment]
Can confirm this issue during docker build, had to do a `rm -Rf app/logs/* app/cache/*` first in the RUN step that triggered this indirectly via composer install.
