### ISSUE TITLE
Count constraint 'min'=>1 applied against file field type with 'multiple'=>true is ignored

### ISSUE THREAD

**Issue by nurikabe** [symfony/symfony#12547]
For example:

``` php
    $builder = $this->get('form.factory')->createBuilder();
        $form = $builder
            ->add('documents', 'file', array(
                'required' => false,
                'multiple' => true,
                'constraints' => array(
                    new Count(array('min'=>1)),
                )
            ))
            ->add('submit', 'submit')
            ->getForm()
        ;
```

This validates true even if no file is selected.  If min is greater than one, however, the constraint behaves as expected and the form fails with "This collection should contain # elements or more."

Experiencing this in both 2.5.7 as well as 2.6.0-BETA1.

**Comment by hhamon** [comment]
Can this issue be closed?

**Comment by Tobion** [comment]
This ticket doesn't make sense to me. It's an optional field. The count constraint will make the field pass when it's not set. So whatever you set as `min` doesn't matter when the file field is not set by the user.

**Comment by nurikabe** [comment]
@Tobion That's counter-intuitive to me.  I would assume `Count(array('min'=>1))` would require at least one file to be uploaded.

**Comment by Tobion** [comment]
All constraints allow `null` to support optional fields. There is alot of info available on this.

**Comment by jakzal** [comment]
see https://github.com/symfony/symfony/issues/10221#issuecomment-34769066 and #11956

**Comment by Tobion** [comment]
But if this the comments in https://github.com/symfony/symfony/issues/12547#issuecomment-65315690 and 
> This validates true even if no file is selected. If min is greater than one, however, the constraint behaves as expected and the form fails with "This collection should contain # elements or more."

are true, then this seem strange to me. When no file is uploaded then the value should be null and not an array with an empty string.

**Comment by yceruto** [comment]
It's a bug then? IMHO this require a view data transformation if `multiple` option is enabled, to ensure that `null` value is returned when no file is uploaded:

```
public function reverseTransform($array)
{
    // multiple files always must be an array
    // even when no file is uploaded (in this case array(null))
    if (!is_array($array)) {
        throw new TransformationFailedException('Expected an array.');
    }

    // this remove the empty item when no file is uploaded (i.e. array(null) --> array())
    // and ensures that each item must be a File object
    $array = array_filter($array, function ($value) {
        return $value instanceof File;
    });

    // return null if there aren't files uploaded
    if (0 === count($array)) {
        return;
    }

    // otherwise, return the array of File objects
    return $array;
}
```
