### ISSUE TITLE
BinaryFileResponse sends accept-ranges header on non-safe methods

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#12556]
It seems that `BinaryFileResponse` class always sets the `Accept-Ranges` header, even when a non-safe method (`POST`, `PUT` etc) is used. This causes issues because additional requests sent by the browser will automatically be converted to `GET`. 

For instance, when generating a PDF from a `POST` action will most likely fail as the browser will directly try the same URL again with a `range` header, but with a `GET`.

It would be an easy fix to check for unsafe request method and set `Accept-Range` header to either `bytes` or `none`.

**Comment by fabpot** [comment]
@jaytaph Can you provide a patch?

**Comment by jaytaph** [comment]
@fabpot Yes, I can write one up..
