### ISSUE TITLE
Filipino language missing?

### ISSUE THREAD

**Issue by nurikabe** [symfony/symfony#12583]
As far as I can tell the ISO 639-2 code for Filipino ("fil") was supported up through Symfony 2.2 but has since been removed from Symfony 2.3+.  Oversight?

**Comment by javiereguiluz** [comment]
In #18019 we've updated the internationalization data to its latest version. @nurikabe could you please verify if this issue has ben fixed? Thanks!

**Comment by jakzal** [comment]
@javiereguiluz I just confirmed this is indeed a bug. Locale aliases are currently not considered as valid locales.

**Comment by javiereguiluz** [comment]
@jakzal thanks for working on this and for contributing a solution!
