### ISSUE TITLE
[Hackday] [2.7] Deprecate PRE_BIND, BIND and POST_BIND form events

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#12601]
**NOTE**: This issue is part of the "SymfonyCon 2014 Madrid Hackday" effort to add logs for every 2.7 deprecated feature. This is needed before removing those features in 3.0 version. Please, add you name in a comment of this issue if you are going to work on this.

-----

The events `PRE_BIND`, `BIND` and `POST_BIND` were renamed to `PRE_SUBMIT`, `SUBMIT` and `POST_SUBMIT`.

Before:

```php
$builder->addEventListener(FormEvents::PRE_BIND, function (FormEvent $event) {
   // ...
});
```

After:

```php
$builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
   // ...
});
```

The form constants are marked as deprecated, but I don't know if we should also generate logs whenever they are used from any part of the code. If this is not necessary, please close this issue.

**Comment by stof** [comment]
the deprecation warning has been added in https://github.com/symfony/symfony/pull/12968
