### ISSUE TITLE
[DX][VarDumper] expand all items of an array

### ISSUE THREAD

**Issue by larsborn** [symfony/symfony#12612]
That was the first thing, coming to my mind, when I dumped an array: I had to manually expand all elements, if I want to get an overview.

If nobody objects, I would start to implement something like an "expand all" link somewhere.

**Comment by taylankasap** [comment]
**Option**+**click** (**alt**+**click** in Windows, I think) is shortcut for expand all in some applications (Chrome DevTools, Firefox DevTools, OS X Finder etc.). It would be nice to have in here too.

**Comment by nicolas-grekas** [comment]
alt+click would be great then

**Comment by larsborn** [comment]
ok, I'll look into the options that don't require jQuery as a dependency (since I think this would be kind of overkill). Any objections?

**Comment by nicolas-grekas** [comment]
No jquery, only plain old JS, that'd be perfect

**Comment by larsborn** [comment]
what's the minimal `support browser versions then? For this developer component it might be slightly higher than MSIE 6?

**Comment by nicolas-grekas** [comment]
I'd say IE9 at least, IE8 if you can get it, but certainly not below

**Comment by larsborn** [comment]
k, thanks for your feedback!

**Comment by garygreen** [comment]
Any news on this? Would love to have alt+click for expand all

**Comment by nicolas-grekas** [comment]
@larsborn do you need some help? 2.7 is going feature freeze soon. If you want, I can take care of finishing your patch. Please tell me what you prefer.

**Comment by larsborn** [comment]
currently working on it. I don't know, which keycode the apple-key on apple-keyboards has, so I'll first stick to the ALT-Key on PC keyboards (code 18).

**Comment by larsborn** [comment]
finished (details see PR under https://github.com/symfony/symfony/pull/12757)
