### ISSUE TITLE
[Hackday] [2.7] Add a deprecation note about the new Core/Resources/ directory

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#12657]
**NOTE**: This issue is part of the "SymfonyCon 2014 Madrid Hackday" effort to add logs for every 2.7 deprecated feature. This is needed before removing those features in 3.0 version. Please, add you name in a comment of this issue if you are going to work on this.

If you need it, this Gist explains how to generate the deprecation note:

https://gist.github.com/javiereguiluz/a5514ec6cde2a63be441

-----

The `Resources/` directory of the `Security` component was moved to `Core/Resources/`. I don't know if it's possible to generate deprecation notices in this case.

**Comment by stof** [comment]
@javiereguiluz AFAIK, it is not possible to throw such warning, as it would have to be thrown in places using this folder in other codebase than Symfony (we are using the new path).
So I'm closing the issue
