### ISSUE TITLE
[Form][Validation] Validation readonly and disabled forms

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#12799]
As per specification the validation must be skipped for disabled types (http://www.w3.org/TR/html5/forms.html#concept-fe-disabled). 

Strange is somehow that the validation must be skipped also for readonly fields.
(http://www.w3.org/TR/html5/forms.html#the-readonly-attribute) This is currently
not reflected in the Symfony implementation and makes imho also not much sense.

Currently readonly fields are validated hence it can happen that the readonly attribute
is changed on the client side which makes sense, in theory the values could be altered
as well.

Also I found out if you have a disabled element in your form it is not validated. If however
an constraint in another form element fails the errors of the disabled form type will be shown.
If no other constraint fails the error will not be shown.

@webmozart What do you think about an "real" read_only field which behaves as "disabled" with the difference that it will be validated rather than deprecating it? I think this is the common behavior users expect when using read_only and we could teach it accordingly.

Also is it intended that errors to a disabled form element will be shown in case another constraint fails?

I think I would have a look at it if you let me know your thoughts.

Relates to #10658

**Comment by stof** [comment]
This spec is talking about disabling the *client-side* validation for readonly fields, because the user cannot alter them directly (they are meant to be modified by JS only).
However, it does not make sense to disable the server side validation IMO, because the value submitted by the readonly field is still bound from the client data (this is the difference between readonly and disabled in the HTML spec). The server side cannot trust the way this value is altered, given that readonly is only a hint for the UI anyway.

**Comment by peterrehm** [comment]
@stof But as of now you have either the choice of readonly and disabled. Readonly can be altered, disabled fields can not be altered. But for the disabled fields there is no validation. I see the use case of a real readonly field that behaves like disabled but with validation. The spec says for disabled fields must not be validation. But I think this is a use case when you have e.g. permission based read only fields but the field must be validated.

**Comment by stof** [comment]
@peterrehm if you disable the server-side validation for readonly fields, which are still bound from the submitted data, it means you are trusting user input blindly. This would be a security issue.
the HTML spec is talking about **client-side** validation (where disabling the validation might make sense, because the browser is also expected to disable the interaction with the field)

**Comment by peterrehm** [comment]
@stof It seems you misunderstood my comment. We have to differentiate between readonly with potential updates and strict readonly. The first one can be realized with the readonly attribute/type 
where the field will always be validated but can be updated as well.

The closest we have right not regarding a strict read only type is disabled. This does not accept any
data but and that is the problem omits validation also on server side. I would like to have such strict disabled type. What do you think regarding this?

**Comment by Tobion** [comment]
Closing as I agree with @stof. Even after reading

**Comment by peterrehm** [comment]
@Tobion Let me try once more to make the issue I am seeing more clear. 

The way how validation is applied on readonly and disabled fields is confusing.
Fields of a readonly field will always be validated, of a disabled field only if another
constraint fails as well.

The goal is to get a disabled field which will be validated. This makes sense if for instance
you have permissions in your app and some fields may only be altered based on the permissions
of the user. It can happen that a user cannot define specific settings as other items are not defined
for which he does not have the permission, but he sees the fields as disabled.

Does this make the issue more clear?

**Comment by Tobion** [comment]
If you feel something must be changed, please provide a PR.

**Comment by peterrehm** [comment]
I will do once it is discussed, otherwise I might waste my time. Could I explain it now better to you?

**Comment by Tobion** [comment]
Why would you validate things that cannot be changed by a user? You do not need to validate stuff that the app has set itself. I don't get it.

**Comment by Tobion** [comment]
And I'm pretty sure whatever you try to achieve can be done with a listener.

**Comment by peterrehm** [comment]
To give you a practical example, a user can select 2 options in a select field when configuring a quote. 
Option one is to exclude the installation cost, option 2 is to include the cost. If you want to include the installation the installation must be configured. If he has not the permissions to edit that he will see blank fields and will be unable to save that form and will get an error.

````php
class Quote {
    // ...

    private $installation; // included or excluded

    /**
    * @Assert\NotBlank(groups="installationIncluded")
    */
    private $installationText; 

    /**
    * @Assert\NotBlank(groups="installationIncluded")
    */
    private $installationCost;
}
````

At least it is a bug to me that the constraints on installationText and installationCost, if they are disabled in the form, will only raise errors if another field fails as well. 

Working around that is possible, I did that already. I just like to address and fix issues when I run into them. If in this case not wanted, no problem, we can leave it as is.
