### ISSUE TITLE
[OptionResolver] (Default) null values are not allowed since 2.6

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#12809]
```php
$resolver->setDefaults([
    'my_option' => null,
]);
$resolver->setAllowedValues([
    'my_option' => ['one', 'two', 'three'],
]);
```

With this configuration, the option `my_option` must be defined because it can't be null.

Is this wanted? I can't find any note about this on [the upgrade guide](https://github.com/symfony/symfony/blob/2.6/UPGRADE-2.6.md).

This causes an `InvalidOptionsException` with HWIOAuthBundle. We now have to define all options or wait for a bundle update: see [options configuration](https://github.com/hwi/HWIOAuthBundle/blob/d691f6d038ca4d55f75b7f6097f8feb2e316209e/OAuth/ResourceOwner/GoogleResourceOwner.php#L64) where `access_type` was optional.

**Comment by stof** [comment]
Well, this is indeed a BC break in one case: when your default value is not allowed by your validation of allowed values.

However, this means that your option resolution forbids people to pass you the option with its default value explicitly. This looks like a broken setup IMO.
Should we really revert the other bugfixes we made to support this weird use case ? I think people should rather fix their value validation to allow their default value.

**Comment by Tobion** [comment]
I also think the old behavior was not intended to work and just worked accidentally. The current behavior is the better one. To support the use-case you only have to add `null` to the allowed values.

**Comment by JasonHanley** [comment]
Although I agree that throwing the exception is certainly more "correct", and HWIOAuthBundle is clearly doing the wrong thing -- From an end user perspective, the new check prevents anyone from upgrading to 2.6 until every dependency they have that relies on the old behavior is updated. I've had to require "symfony/symfony": "2.5.*" in all my projects pending a resolution.

**Comment by weaverryan** [comment]
@JasonHanley brings up a good point. Is there any reason we shouldn't re-allow null now and deprecate this "feature" for removal in 3.0?

**Comment by Tobion** [comment]
I'd rather consider this a bug that was fixed. And reintroducing a bug seems bad.
It's quite obvious that it's a bug considering that allowed __values__ and allowed __types__ behave differently. So null values are ignored for allowed values but if you set allowed types, then null is not ignored. The difference are these two lines [array_key_exists](https://github.com/symfony/symfony/commit/aa890aedfcaa471251a49788e730d6f114efcaf5) vs [isset](https://github.com/symfony/symfony/blob/2.5/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L302)

**Comment by Tobion** [comment]
Closing because it was a bug fix in @stof and my opinion. I added a test to keep this logic in place.

**Comment by stof** [comment]
@weaverryan The BC break is not about null specifically. It is about any mismatch between the default value and the allowed values. Symfony 2.5 was also allowing you to defined the allowed values as being ``array(1, 2, 3)`` and then setting the default value to ``4``.
The only way to avoid the BC break is to revert the whole bugfix. Adding a special case for ``null`` would not keep BC.
