### ISSUE TITLE
[HttpFoundation] The DbalSessionHandler should be updated to reflect the enhancments from #10931

### ISSUE THREAD

**Issue by hanikesn** [symfony/symfony#12812]
The DbalSessionHandler was updated for 2.6 to use a binary format and use locking. The DbalSessionHandler and DbalSessionHandlerSchema should be updated, too.

**Comment by stof** [comment]
The only advantage I see in the DBAL connection is that it connects to the DB lazily rather than connection on instantiation

**Comment by Tobion** [comment]
The PdoSessionHandler supports lazy connection as well.

**Comment by dincho** [comment]
> The PdoSessionHandler supports lazy connection as well.

Thank you!

**Comment by nicolas-grekas** [comment]
Closing: DbalSessionHandler has been removed in 4.0.
