### ISSUE TITLE
Custom error pages + ajax json response + php template engine with embedded $view->render() = fail

### ISSUE THREAD

**Issue by alanhartless** [symfony/symfony#12817]
I'm not sure if there can be a solution to this but I'm loading content mainly through ajax and thus I have a "delegating" render function in the controller that checks for xml request and returns json if true or the full html if not.  I also have a custom controller handling custom error pages.  Everything works great except in the scenario that an exception occurs when using $view->render inside a template.  Since the php engine uses ob_start to capture the content, the buffer is spit out when an exception occurs.  Symfony then renders the exception via my extended controller and correctly formats into json.  The problem is the contents of the buffer is spit out when ob_start hits the exception thus leading to some html then the json string the exception handler generates; which of course breaks the ajax response handling as its invalid json.  My current work around is basically parsing it javascript side to extract the json string.  

Any thoughts?

**Comment by stof** [comment]
Note that this issue has been resolved for Twig. So the PHP templating engine could also solve this issue (but it requires someone to work on this)

**Comment by fabpot** [comment]
Closing as nobody seems to care enough to actually work on a fix.

**Comment by angularjs-rootscopeaaron** [comment]
> Note that this issue has been resolved for Twig. So the PHP templating engine could also solve this issue (but it requires someone to work on this)





https://tiberiusnative-base.github.io/erb864/
