### ISSUE TITLE
[HttpFoundation] Move Session Support Away

### ISSUE THREAD

**Issue by timglabisch** [symfony/symfony#12839]
most issues in the HttpFoundation Component are related to Sessions. 

The HttpFoundation is described as:
The HttpFoundation component defines an object-oriented layer for the HTTP specification.

if you read the http specification there is nothing related to sessions, even more sessions are violating the idea of a stateless protocol.

Sessions are just a concept how to use cookies in combination with a server side key value store.
If you take a look at the HttpFoundation, now it knows a lot about our server side key value stores like the filesystem memcached, pdo, mongo, memcache. this has nothing todo with "an object-oriented layer for the HTTP specification".

i don't want to say that we should not support the concept of sessions. the idea is just to accept that sessions are not related to http.

consider the difference:

```
 $request->getSession()->get('foo')
```

vs

```
$sessionStorage->byRequest($request)->get('foo')
```

so it would be up to any kind of session storage to know about rfc6265

**Comment by JHGitty** [comment]
:+1: I think a new component for sessions would be the best way.

**Comment by TomasVotruba** [comment]
@JHGitty I agree. E.g. [Laravel already did it](https://github.com/illuminate/session).

What do you think about it? I might try to decouple it.

**Comment by ostrolucky** [comment]
Related: https://github.com/symfony/symfony/issues/10557

**Comment by mfrieswyk** [comment]
@fabpot Status Bump? This issue seems stale.
