### ISSUE TITLE
OptionsResolverInterface Should Include the new OptionsResolver Methods

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#12830]
Examples:

- [`setDefined`](https://github.com/symfony/symfony/blob/79a5fdd738e084427ed263cde40e7d6ed401225e/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L330)
-  [`setNormalizer`](https://github.com/symfony/symfony/blob/79a5fdd738e084427ed263cde40e7d6ed401225e/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L398)

The signature for `setAllowedValues` is different in `OptionsResolver` as well and there are probably a few other examples.

While `OptionsResolverInterface` is deprecated things like the Form component still use it. It would be great to know those new methods are available so changes could be made in in components that still depend on the interface now in preparation for its removal in 3.0. [Adding methods to interfaces](https://github.com/symfony/symfony/blob/79a5fdd738e084427ed263cde40e7d6ed401225e/UPGRADE-2.6.md#validator) doesn't seem like a BC break, or, if it is, Symfony is already doing it.

**Comment by Tobion** [comment]
In 2.7 you can use `configureOptions(OptionsResolver $resolver)` without the interface. And we don't add the new method to the deprecated interface to avoid BC break.
