### ISSUE TITLE
CSSSelector breaks on DOMDocument containing HTML elements with namespaces

### ISSUE THREAD

**Issue by jslegers** [symfony/symfony#12852]
[`PHPPowertools/DOM-Query`](https://github.com/PHPPowertools/DOM-Query) is the first component of the [`PHPPowertools`](https://github.com/PHPPowertools) framework that has been released to the public. It's purpose is similar to that of [`technosophos/querypath`](https://github.com/technosophos/querypath) but it's implementation is far more true to both jQuery's syntax and its semantics. For example, `PHPPowertools/DOM-Query` lets you do stuff like this :

````php
// Add a span tag with classes 'icon' and 'icon-printer' to all buttons
$H->select('body')->select('button')->add('span')->addClass('icon icon-printer');
````
------
````php
// Use a lambda function to set the data-val attribute of all gallery images
$H->select('.gallery li img')->attr('data-val', function( $i, $val) {
    return $i . " - " . $val->attr('class') . " - photo by Kelly Clark";
});
````

Under the hood, it uses [`symfony/CssSelector`](https://github.com/symfony/CssSelector) for converting ***[CSS selectors](http://www.w3.org/TR/CSS/)*** to ***[XPath queries](http://www.w3.org/TR/xpath/)***

What was still lacking until today, is proper support for HTML5. This has been solved by using [`Masterminds/html5-php`](https://github.com/Masterminds/html5-php)'s HTML loading and saving instead of native DOMDocument loading.

To allow `Masterminds/html5-php` and `symfony/CssSelector` to play well together, I needed to modify `Masterminds/html5-php` to prevent HTML elements from being generated with the `http://www.w3.org/1999/xhtml` namespace as the selectors generated by `symfony/CssSelector` failed to do their job.

Is support of namespaced HTML elements a missing feature in this component or is this merely an option that I overlooked?

-------------

See also https://github.com/PHPPowertools/DOM-Query/issues/1 and https://github.com/Masterminds/html5-php/issues/67.

**Comment by jakzal** [comment]
ping @jslegers

**Comment by fabpot** [comment]
Closing as there is no more feedback.
