### ISSUE TITLE
[Form][Translation] Add option for formatting choice's labels

### ISSUE THREAD

**Issue by cleentfaar** [symfony/symfony#12880]
Following after the recently added `label_format` option, i wondered if it was worth also adding an option to format a `choice`-field's choices?

`label_format` PR: https://github.com/symfony/symfony/pull/12050

Getting PR ready to show what I mean...

**Comment by aitboudad** [comment]
I think we can accomplish this by using the option `choice_label`

```php
$builder->add('foo', 'choice', array(
    ...
    'choice_label' => function ($choice, $key) {
        return 'form.choice.'.$key;
    },
));
```
For the reference: http://symfony.com/blog/new-in-symfony-2-7-choice-form-type-refactorization
