### ISSUE TITLE
[Validator] Allow set "required" option, when using the Validator Component standalone.

### ISSUE THREAD

**Issue by brpaz** [symfony/symfony#12907]
Hello.
I am working on a project where I have some plain php objects that I want to use the Validator component on them.
The problem is I cant set "required" option without using forms.
Maybe create a new Assert or allow each validator to receive a "required" option. Then it will only check the other asserts if the required option is true.

What do you think?

**Comment by webmozart** [comment]
Hi @brpaz, as the other posters mentioned, you won't see any error if the `$gender` field contains `null`. If you want to mark the field as "requried", at a `NotNull` constraint to the field.

If you experience your problems for other "empty" values than `null` (such as `""`), you should make sure to convert the empty value to `null` in your model.
