### ISSUE TITLE
AbstractAuthenticationListener incorrectly assumes your token is a UsernamePasswordToken

### ISSUE THREAD

**Issue by bkosborne** [symfony/symfony#12921]
I'm working on my own auth provider that has its own token and authentication listener class. I'm making use of all the helpful abstract classes, including `AbstractAuthenticationListener`. The top of the class indicates:

> The AbstractAuthenticationListener is the preferred base class for all browser-/HTTP-based authentication requests.

However, [it assumes that you're using a `UsernamePasswordToken`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php#L200) in the private `onFailure` method (when clearing the token on auth failure). Since it's private I can't override it.

I don't have a solution, but if this is a "won't fix" then we should at least indicate in the class doc block that a `UsernamePasswordToken` must be used, and not just a `TokenInterface`

**Comment by chalasr** [comment]
I'm going to close this issue as it is getting old and did not receive any feedback from the community. If anyone think this is issue is still relevant, feel free to submit a PR that makes the token clearing logic customizable from child implementations (e.g. by adding a protected `clearToken()`).
