### ISSUE TITLE
FileSystem::copy() with $override = false can still override (overwrite) the target file

### ISSUE THREAD

**Issue by borekb** [symfony/symfony#12937]
The API of FileSystem::copy() is unintuitive and its docs are probably flawed. It says:

    @param bool    $override   Whether to override an existing file or not

But that's not true, even if `$override` is false the target might be overwritten if it's older than origin. Generally, I would expect

    $fs->copy($origin, $target, false);

not to overwrite my $target but it does. Either the docs should make this very clear or the behavior should ideally be changed but that would probably mean a breaking change. Anyway, if #10547 gets a go ahead I think that the time comparison "magic" should be removed or at least hidden behind some appropriately named parameter.

**Comment by stof** [comment]
Can you send a PR updating the phpdoc ?

**Comment by borekb** [comment]
So is the method description suggested in https://github.com/symfony/symfony/issues/12937#issuecomment-67892246 OK? If so, I'll open a PR.

**Comment by rgomezcasas** [comment]
Hey, I think override must be boolean, overrides or not, but never depending on the last modification date...

**Comment by javiereguiluz** [comment]
For what is worth, PHP's [copy() function](http://php.net/copy) always overrides:

![php_copy](https://cloud.githubusercontent.com/assets/73419/10604349/06bb8d06-7724-11e5-81a4-f7b659f45064.png)
