### ISSUE TITLE
OptionsResolver still implements OptionsResolverInterface

### ISSUE THREAD

**Issue by ibrasho** [symfony/symfony#12945]
I tried to search for a similar issue but I could find none.

I'm using the OptionsResolver as a component in a package I'm writing.

In 2.6, the `OptionsResolver` class still implements the `OptionsResolverInterface` interface.
So if the interface is auto-loaded by default the `trigger_error()` call in the `OptionsResolverInterface.php` is executed. And I get the following error: The "Symfony\Component\OptionsResolver\OptionsResolverInterface" interface was deprecated in version 2.6 and will be removed in 3.0. Use "Symfony\Component\OptionsResolver\OptionsResolver" instead.

Am I forgetting something?

**Comment by Tobion** [comment]
Closing as the interface deprecation triggers have been removed.
