### ISSUE TITLE
[Serializer] Xml prefixed attributes and shorttags not supported

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#12986]
I'm busy reading/writing some .xml files from Microsoft Office (.docx) formatted files. The `decode` of the `word/settings.xml` seems to be fine, but there are some differences:

Decode input (as found in original file)
```
<w:zoom w:percent="100"/>
```
The array returned by the `XmlEncoder::decode` contains:
```
w:zoom [
   @percent => 100,
   #
]
```
When I `encode` the array back to xml again, the "prefixed attributes" is wrong:
```
<w:zoom percent="100"></w:zoom>
```
Two things seem to go wrong with the `XmlEncoder`

1. The property prefix `e:` is not preserved
2. Nodes without content are not closed as shorttag

**Comment by Rvanlaak** [comment]
@dunglas this maybe is fixed with the last serializer makeover?

**Comment by jakzal** [comment]
@Rvanlaak could you provide a simple script that would reproduce your issue?

What I've tried is:

```php
use Symfony\Component\Serializer\Encoder\XmlEncoder;

$xml = '<?xml version="1.0" encoding="UTF-8" ?><root><w:zoom w:percent="100" xmlns:w="http://example.com"/></root>';
$xmlEncoder = new XmlEncoder('root');
var_dump($decoded = $xmlEncoder->decode($xml, 'xml'));
var_dump($xmlEncoder->encode($decoded, 'xml'));
```

It dumps:

```
string(0) ""
string(36) "<?xml version="1.0"?>
<root></root>
"
```

**Comment by fabpot** [comment]
Closing as there is no feedback anymore.

**Comment by Rvanlaak** [comment]
:+1: for closing it now, will put making a reproducible test case on my own todo list.
