### ISSUE TITLE
BinaryFileResponse X-Sendfile support for stream wrappers

### ISSUE THREAD

**Issue by Sander-Toonen** [symfony/symfony#12990]
Right now the combination of X-Sendfile does not work with stream wrappers when using the BinaryFileResponse.

Setup: Nginx proxies X-Accel-Redirect files to an object store and the Symfony app accesses the object store using for instance Gaufrette.

Issue: BinaryFileResponse uses getRealPath to create the default path to the file. Stream wrapped files return an empty string here.

Solution: When ``$this->file->getRealPath();`` is empty, let ``$path`` fall back to ``$this->file->getPathname();``. This way users can map stream wrappers to a Nginx location using the ``X-Accel-Mapping`` header.

**Comment by marcojanssen** [comment]
@Sander-Toonen Could you please add the test so we can merge it? If you don't have time at the moment let me know i'll add it for you

**Comment by Sander-Toonen** [comment]
@marcojanssen To be honest, I have no idea how I could test this. My PHPUnit knowledge doesn't reach very far. If you could write a test or point me in the right direction, I would very much appreciate that.

**Comment by marcojanssen** [comment]
@Sander-Toonen Looked at it and think we should add a test covering the streaming file.

https://github.com/Sander-Toonen/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Tests/BinaryFileResponseTest.php#L156

Is the test for a file, so if we add a test the same way with a stream we should be there right?

We could create a stream as with php://memory then server that to the prepare method, not sure if this is the 100% correct way though.

@stof @jakzal What do you guys think?
