### ISSUE TITLE
Setting default value for form choice not possible 

### ISSUE THREAD

**Issue by loki-sama** [symfony/symfony#13029]
The form element choice does not behave as other form elements. If coice form element is set to a value at creation this value is not use, for other elemts the default value can be set this way.  

```pgp
<?php
/**
 * @Entity
 */
class myEntity {
   /**
     * @var colum $colum
     *
     * @ORM\Column(name="colum", type="integer", nullable=true)
     */
    private $colum = 1;    //does not set default

    /**
     * @var integer $int
     *
     * @ORM\Column(name="int", type="integer")
     */
    private $int = 15;    //does set default value
```

**Comment by stof** [comment]
Can you show your form type too ? For me, it sets the value using the value of the property, and I'm quite sure we have tests covering this

**Comment by fabpot** [comment]
Closing as there is no feedback from the reporter anymore. @loki-sama Feel free to reopen with more details.
