### ISSUE TITLE
Core User class returning roles as strings instead of Role objects

### ISSUE THREAD

**Issue by Turneliusz** [symfony/symfony#13037]
I'm using Symfony 2.6

~~~yaml
system_users:
  memory:
    users:
      my_admin: { password: "xxx", roles: 'ROLE_ADMIN' }
~~~

for that the container looks like:

~~~php
    /**
     * Gets the 'security.user.provider.concrete.system_users' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * This service is private.
     * If you want to be able to request this service from the container directly,
     * make it public, otherwise you might end up with broken code.
     *
     * @param bool    $lazyLoad whether to try lazy-loading the service with a proxy
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider A Symfony\Component\Security\Core\User\InMemoryUserProvider instance.
     */
    public function getSecurity_User_Provider_Concrete_SystemUsersService($lazyLoad = true)
    {
        // (...)
        $instance = new \Symfony\Component\Security\Core\User\InMemoryUserProvider();

        $instance->createUser(new \Symfony\Component\Security\Core\User\User('my_admin', 'xxx', array(0 => 'ROLE_ADMIN')));

        return $instance;
    }
~~~

which is triggering an exception __Call to a member function getRole() on a non-object__:

> (...)
Dec 19 15:28:54 damian-ThinkPad-T440p [3861]: PHP  18. XXX\Bundle\AdminBundle\Security\Voter\AdminAccessVoter->isGranted($attribute = *uninitialized*, $object = *uninitialized*, $user = *uninitialized*) /home/damian/PhpstormProjects/vendor-backend/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php:76
Dec 19 15:28:54 damian-ThinkPad-T440p [3861]: PHP  19. Symfony\Component\Security\Core\Role\RoleHierarchy->getReachableRoles($roles = *uninitialized*) /home/damian/PhpstormProjects/vendor-backend/src/XXX/Bundle/AdminBundle/Security/Voter/AdminAccessVoter.php:65
Dec 19 15:28:54 damian-ThinkPad-T440p [3861]: request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getRole() on a non-object" at /home/damian/PhpstormProjects/vendor-backend/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Role/RoleHierarchy.php line 43 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException: Error: Call to a member function getRole() on a non-object at /home/damian/PhpstormProjects/vendor-backend/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Role/RoleHierarchy.php:43)"} []

as Core User code looks like:

~~~php
    private $roles;

    public function __construct($username, $password, array $roles = array(), $enabled = true, $userNonExpired = true, $credentialsNonExpired = true, $userNonLocked = true)
    {
        // ...

        $this->roles = $roles;
    }

    /**
     * {@inheritdoc}
     */
    public function getRoles()
    {
        return $this->roles;
    }
~~~

`UserInterface::getRoles()` defines:

~~~php
    /**
     * Returns the roles granted to the user.
     * (...)
     * @return Role[] The user roles
     */
    public function getRoles();
~~~

Am I doing something wrong or it's a bug?

**Comment by CMatias** [comment]
When executing this piece of code:

`$this->roleHierarchy->getReachableRoles($user->getRoles())`

I get the following error:  "Error: Call to a member function getRole() on string". Because Symfony is treating strings as role objects on Symfony/Component/Security/Core/Role/RoleHierarchy.php.

$reachableRoles = $roles;
        foreach ($roles as $role) {
            if (!isset($this->map[$role->getRole()])) {
                continue;
            }

Shouldn't the code be changed to something like? 

    if(is_string($role)) {
    $my_role = $role; 
    } 
    else {
    $my_role = $role->getRole();
    } 

    if (!isset($this->map[$my_role]) { ....

**Comment by CMatias** [comment]
Hey, this commit does not solve the issue as role objects are still being treated as strings in the RoleHierarchy.php file. 

I've implemented the patch on my side (the phpDoc change) and the "Error: Call to a member function getRole() on string" persists.

**Comment by xabbuh** [comment]
@CMatias Can you please show the complete stack trace of that error and a way to reproduce your issue?

**Comment by xabbuh** [comment]
@CMatias Closing here as I now understand your issue which is related to how you use the `RoleHierarchy` class. The `RoleHierarchyInterface` clearly states that the passed arguments must be objects implementing the `RoleInterface`: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Role/RoleHierarchyInterface.php#L27 If your `User` class can return strings in `getRoles()`, you need to make sure to convert them yourself before passing them to `getReachableRoles()`.

**Comment by CMatias** [comment]
This issue stood with us for a long time. As we upgraded to 2.8 the new way of voting with decisionManager no longer required us to do that fix. Sorry and thanks for the help.
