### ISSUE TITLE
[security] Base ACL exceptions on the RuntimeException

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13154]
All the [ACL exceptions](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Acl/Exception/Exception.php) are based on the generic `\Exception` class. This is only done in a three different components (CSS, Config and the Security ACL). 

I would suggest a change to `\RuntimeException`, as this is a more detailed exception, giving users the opportunity to deal with the exceptions in a cleaner way (easier distinguish between runtime and logic exceptions for one) and to be more consistent with the rest of the exceptions defined in Symfony, which all rely on the SPL exceptions.

It can break backward compatibility when exception handling is done on both `RuntimeException` and `Exception`, and not on any of the ACL exceptions directly, although I doubt this will ever be the case.

**Comment by fabpot** [comment]
@jaytaph Seems like a good idea.

**Comment by alex-moreno** [comment]
I'm trying to find easy picks to collaborate and this seems a good one. I'll give it a go if that's OK? 

Thank you.

**Comment by jakzal** [comment]
@alex-moreno go for it :+1:

**Comment by alex-moreno** [comment]
just to double check, the only class we are changing here is Acl/Exception/Exception, right? Not the other three referenced.

Thank you.
