### ISSUE TITLE
Wish/Improvement: Store original exception in FlattenException

### ISSUE THREAD

**Issue by nagmat84** [symfony/symfony#13168]
Symfony\Component\Debug\Exception\FlattenException does not store the original exception. In consequence, any property of the original exception that is not particularly handled by FlattenException gets lost. For example, if the original exception implements the interface HTTPExceptionInterface, the status code and headers a copied over. It would be nice to have a more general solution.

My problem at hand is the following: I implemented some additional exceptions that are actually derived from AccessDeniedHTTPException, BadRequestHTTPException and son on. These customized exception classes are augmented by some properties. Moreover I implemented a custom ExceptionController (derived from the standard ExceptionController from the TWIG bundle) and registered it as a service. The problem: I cannot access the additional properties of my custom exception classes, because they are lost as the ExceptionController only obtains a FlattenException.

**Comment by fabpot** [comment]
Not sure if we want to cover these cases. Storing the original exception is out of questions of course, and I don't see how we could generically get all properties in a meaningful way.

**Comment by dejayc** [comment]
@fabpot That's kind of surprising.  You're saying that you're shutting down all ability for wrapped exceptions to relay all sorts of useful information that is presently only preserved within the augmented (extended) exception classes.

If we're creating our own ExceptionController, such a controller would most certainly want the ability to access bundle-specific augmentations that are provided via bundle-specific exception classes.  I don't see a good reason to deny access to such customization, and thus forcing developers to find other "sanctioned" ways to pass this customized information through the several stratified layers of a Symfony app.

What is the problem with storing the original exception?  At the very least, you could make any logic that wraps exceptions check to see if the original exception implements a certain interface to provide customized exception attributes, and if so, invoke an appropriate method within that interface to copy such properties into the wrapped exception.

**Comment by nicolas-grekas** [comment]
FlattenException's main property is being serializable. Always. Having the original exception embedded would break this essential property.

**Comment by dejayc** [comment]
@nicolas-grekas I think FlattenException would be serializable even if having an embedded exception, no?

**Comment by dejayc** [comment]
Also, removing the original exception makes it totally impossible to have a custom exception controller that uses instanceof, class_implements, etc. to determine the appropriate course of action.  I can't help but think this would impose limitations on Bundles that would otherwise try to do intelligent things in response to certain exceptions.

**Comment by thejahweh** [comment]
I've encountered the same problem. I had to display only a error number. Luckily the code property can be used for this purpose.

@fabpot It would be possible with a interface which describes a method to get the detail information from the exceptions. Like the HttpExceptionInterface:
```php
interface FlattenDetailsInterface
{
    public function getDetails(): array;
}
```
and in the FlattenException another getter to get the details?

**Comment by stof** [comment]
@dejayc the original exception may not be serializable (as its stack trace can reference non-serializable objects, for instance a PDO connection). In such case, FlattenException cannot keep it while staying serializable (at least not without excluding it from the serialization).
