### ISSUE TITLE
[Console] Introduce a --profile option

### ISSUE THREAD

**Issue by jjanvier** [symfony/symfony#13189]
Hello guys,

What about introducing a `--profile` option display timing and memory usage information. Composer provides this option and it's really useful. The result look like `Memory usage: 278.13MB (peak: 1077.8MB), time: 61.4s`

Is it interesting for you ? Are there some weirdness I don't see to achieve this or is it doable quite easily or  ? If so, I'd happy to submit a PR.

**Comment by fabpot** [comment]
I'm very against this feature. I don't see why we would add a debug feature by default to all console applications created with the Console component.

**Comment by KingCrunch** [comment]
At least on Linux `time` and similar tools do the same for arbitrary commands.  I can't imagine there is nothing like this on Windows or Mac. However, this makes a built-in profile superfluous imo
