### ISSUE TITLE
[security] Inconsistent configuration dump

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13196]
I found something that I don't think is a bug by itself, but doesn't really strike me as completely correct behaviour neither.

When I dump the security configuration on the console, I will not see any authentication mechanism configurations, like form_login, x509, http_basic etc, but after I clear the cache without warming up, these configuration settings are correctly dumped. 

```
$ php app/console config:dump-reference security
   firewalls:            # Required

        # Prototype
        name:
            pattern:              ~
            host:                 ~
            .......
            anonymous:
                key:                  54a5a642d6404
            switch_user:
                provider:             ~
                parameter:            _switch_user
                role:                 ROLE_ALLOWED_TO_SWITCH
    access_control:
        requires_channel:     null

        # use the urldecoded format
        path:                 null # Example: ^/path to resource/
        host:                 null

$
```

```
$ php app/console clear:cache --no-warmup
$ php app/console config:dump-reference security
   firewalls:            # Required

        # Prototype
        name:
            pattern:              ~
            host:                 ~
            .......
            anonymous:
                key:                  54a5a642d6404
            switch_user:
                provider:             ~
                parameter:            _switch_user
                role:                 ROLE_ALLOWED_TO_SWITCH
            x509:
                provider:             ~
                user:                 SSL_CLIENT_S_DN_Email
                credentials:          SSL_CLIENT_S_DN
            simple_preauth:
                provider:             ~
                authenticator:        ~
            form_login:
                provider:             ~
                remember_me:          true
                success_handler:      ~
                .......
    access_control:
        requires_channel:     null

        # use the urldecoded format
        path:                 null # Example: ^/path to resource/
        host:                 null

$
```

The reason for this is that the authentication security listeners are added through the addSecurityListenerFactory() in the [securityBundle::build()](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/SecurityBundle/SecurityBundle.php#L39) method, which only gets called when creating a new cache. 

Once the cache has been build, the security listener factories aren't added so the [MainConfiguration](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php#L295) cannot find their configuration. 

I think the configuration dump should be consistent regardless if it was cached or not. Maybe there could be a way to add the securityListenerFactories at some other place so the configurations will always show up?

**Comment by aitboudad** [comment]
I'll work on this one

**Comment by jakzal** [comment]
Duplicate of #11037.
