### ISSUE TITLE
Symfony2 / Windows / Apache2.2 crashes with HttpBasic Authentication Provider

### ISSUE THREAD

**Issue by julianrubisch** [symfony/symfony#13190]
Hello everybody,

while trying to set up a REST API with Symfony2 using Basic HTTP Authentication, I'm observing a strange bug that seems to be related to these:

- https://github.com/symfony/symfony/issues/3216
- http://serverfault.com/questions/375691/symfony2-on-windows-with-apache-php-and-mysql-app-dev-php-will-not-load
- http://stackoverflow.com/questions/9001232/err-connection-reset-with-symfony2-but-not-with-php-script

meaning, Apache crashes without any entries to the logfiles (symfony's prod.log, php's php_error.log), except for

    [Mon Dec 29 20:21:37 2014] [notice] Parent: child process exited with status 0 -- Restarting.
    ...
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Child process is running
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Acquired the start mutex.
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Starting 64 worker threads.
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Starting thread to listen on port 443.
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Starting thread to listen on port 80.
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Starting thread to listen on port 443.
    [Mon Dec 29 20:21:38 2014] [notice] Child 6416: Starting thread to listen on port 80.

in Apache's error.log. In the browser, I get a 101 error (ERR_CONNECTION_RESET).

The bug seems to be related to the http_basic Authentication Provider in security.yml:

    security:
        encoders:
            Test\MyBundle\Entity\AdminUser:
                algorithm: plaintext
    
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    
        providers:
            users:
                 entity: { class: TestMyBundle:AdminUser, property: loginname }
    
        firewalls:
            main:
                pattern:    ^/
                http_basic: 
                    realm: "Secured Area"
                    provider: users
                #anonymous: true
                stateless: true
                security: true
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
    
        access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER}

Commenting out *http_basic* while uncommenting *anonymous*, and clearing the cache leads to a working web-app. However, for the purpose of this REST service I need Basic Auth.

For clarity, here's a little snippet from the Controller, which really at the moment does nothing other than rendering all database entries:

    /**
     * @QueryParam(name="responsible", default="null", description="Responsible User")
     * 
     * @return offers
     */
    public function getOffersAction(ParamFetcher $paramFetcher) {
    
        $em = $this->getDoctrine()->getManager();
    
        $logger = $this->get('logger');
    
        $entities = $em->getRepository('TestMyBundle:Offer')->findAll();
        $logger->info("Entity #0: " . $entities[0]->getAdminUser() );
    
        $view = new View($entities);
    
        return $this->get('fos_rest.view_handler')->handle($view);
    
    } // "get_offers" [GET] /offers

My configuration is: Windows Server 2003, PHP 5.3.29, Apache 2.2, Symfony 2.5.8, FOSRestBundle

I've tried:

- clearing/warming the cache
- setting git config --global core.autocrlf input and re-installing vendors
- re-saving TwigBundle/TwigEngine.php (though I'm actually just rendering JSON and as mentioned above, without authentication it does work fine)

Is this a known issue? If yes, can you point me to the patch? If no, any pointers on how I could track down the file that is crashing Apache? Or is this a FOSRestBundle-related bug?

thanks for looking into this,
Julian

**Comment by fabpot** [comment]
Hi @julianrubisch. First of all, thank you for the very detailed post. Unfortunately, those kind of questions should be asked on the mailing-list where people will be able to help you much better than here. If at some point, it turns out that there is a bug in Symfony, creating an issue here will be the best action to do. But as this is not sure yet, discussing your problem on the mailing-list is much better.
