### ISSUE TITLE
Invalid email address accepted by validator

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#13202]
The following email addresses were accepted by the "Email" constraint but are not valid according to RFC 2822, 3.6.2.

ally,.barajas@gmail.com
madmax 50 @ yahoo .com

**Comment by xabbuh** [comment]
@stevenmusumeche Do you use the [strict validator](http://symfony.com/doc/current/reference/constraints/Email.html#strict) or only the simple regular expression?

**Comment by stevenmusumeche** [comment]
I am using annotations, I was not aware of the strict option.

@Assert\Email(groups={"join_mailing_list", "join_mailing_list_simple"})

**Comment by xabbuh** [comment]
Does it work as expected if you set the `strict` option to `true`?

```php
@Assert\Email(strict = true, groups={"join_mailing_list", "join_mailing_list_simple"})
```

Beware that maybe have to install the `egulias/email-validator` library first using Composer.

**Comment by xabbuh** [comment]
@stevenmusumeche ping

**Comment by stevenmusumeche** [comment]
Sorry, yes, that solves the problem.
