### ISSUE TITLE
Can't edit event object on kernel.controller event.

### ISSUE THREAD

**Issue by motammem** [symfony/symfony#13221]
Event object in kernel.controller event is not editable, for an example checkout [here](http://stackoverflow.com/questions/27754401/convert-values-of-route-parameters-dynamically-in-symfony-2).

**Comment by iltar** [comment]
You're not changing the event object, you're changing the return values of the attributes which are not return by reference. If you want to overwrite them, you should set them back in the bag. 

I recommend to use the [`#symfony` IRC channel](http://symfony.com/irc) for cases like this, no need to post it here

**Comment by motammem** [comment]
Even if you set $event object to null there will be no problem.

**Comment by iltar** [comment]
It's called [Pass by Reference](http://php.net/manual/en/language.references.pass.php), you can't unset the object from inside a scope. It will still exist in the scope where the method was called. 

This is not a "bug" in Symfony, it's how php and other programming languages work.

**Comment by motammem** [comment]
I understand what "Pass by Reference" is. But I'm still confused how this works in this specific case can you show me how we can change event object with an example please?
