### ISSUE TITLE
mkdir racecondition from #11697 exists in HttpFoundation too

### ISSUE THREAD

**Issue by ben-joostens** [symfony/symfony#13228]
The bug described in issue #11697 also appears in  [Symfony/Component/HttpFoundation/File/File.php#L133](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/File/File.php#L133)

I've applied the same fix as in this commit to overcome it: https://github.com/kcassam/symfony/commit/c3485b0ae9544d0cace12b530f53f122bf23a54b

Strangely enough, this bug has been known for a long time and is [supposed to be patched](http://git.php.net/?p=php-src.git;a=commit;h=f32d2ac3aaa7d4af7c348b00ebebb9ae64955704), but it's still happening with php 5.6.4 on debian wheezy.

Should I patch my php manually? Do I make a PR with the fix for HttpFoundation?

**Comment by fabpot** [comment]
see #13645 where I've tried to update the code where it makes sense
