### ISSUE TITLE
Allow the user to get the MasterRequest from Twig

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#13247]
When you render a controller from Twig, it creates a new Request for this controller, descending in the request stack tree:
```twig
{{ render(controller('AcmeDemoBundle:Demo:menu')) }}
```
 
So, in this controller, if you inject the request in the method like this:
```php
namespace Acme\DemoBundle\Controller;
class DemoController {
    public function menuAction(Request $request) {
        //...
    }
}
```
The request passed as argument is the new one, so you won't have the route name nor the route attributes. And for a controller that returns a menu, it can be quite annoying. For this, actually you'll have to inject them manually by passing them as argument to the `controller` function in Twig, or by retrieving the master request with this instruction:
```php
$request = $this->container->get('request_stack')->getMasterRequest();
```
And all the parameters that you want to use in Twig have to be sent manually to the view, which adds some instructions in the controller.
 
What I propose is to change the behavior in the `GlobalVariables` class (which corresponds to the `app` var in Twig, if I understand well) in order to get the master request directly from twig. 

Actual method in `2.6` and `master`:
```php
public function getRequest()
{
    if ($this->container->has('request_stack')) {
        return $this->container->get('request_stack')->getCurrentRequest();
    }
}
```
 
What I'd propose is this:
```php
public function getRequest($master = false)
{
    if ($this->container->has('request_stack')) {
        if ($master) {
            return $this->container->get('request_stack')->getMasterRequest();
        } else {
            return $this->container->get('request_stack')->getCurrentRequest();
        }
    }
}
```
 
Then we still have some BC because any request retrieved will be the current, but simply passing "true" as argument will retrieve the master request. Great for controllers that generates menus, headers, footers, shop orders or baskets, etc.
 
What do you think about it ?

**Comment by iltar** [comment]
I don't think your action should know about multiple requests, let alone your template. I think that the best way to transfer this, is to pass along the values from request A to request B. In your actions you could most likely use `someAction($_route)` as [described in the docs](http://symfony.com/doc/current/book/routing.html#route-parameters-and-controller-arguments).

**Comment by fabpot** [comment]
@iltar is right; as calling a controller as a sub-request can be easily moved to become an ESI (where you don't have access to the master request), this is not a feature that we want to implement in Symfony core.

**Comment by Pierstoval** [comment]
Didn't thought about ESIs, by the way, you're both right, thanks for answering :smiley:

**Comment by karl-casas777** [comment]
@fabpot I think Symfony really needs to be able to get the master request on the twig. I encountered this problem many times. Solutions for this are not that clean and even though we can pass the variable for each include or render controller it would be quiet ugly when we have to pass a variable many times for it to reach the nth included twig. I think @Pierstoval 's solution is viable. Even though we don't have the master request on ESI's it would greatly help if we have them on other included twigs. The use case for controllers to be moved to become ESI are minimal and it wouldn't hurt for the developer to include the necessary variable at this time. At the very least the variables are only included when they have to be included explicitly

**Comment by jakzal** [comment]
@karl-casas777 you can easily use Pierstoval's code and register your own global variable in your project(s). This is rather an edge case than something that majority needs, and therefore that's not something that belongs to core. Especially that it would make ESI and controller rendering strategy no longer interchangeable.

**Comment by Pierstoval** [comment]
To avoid the problems with these kind of includes, I try to avoid depending on master request in my renders/ESIs and move all "previous" renders in twig includes where I always get the current request.
