### ISSUE TITLE
Feature Request: Allow column spans for Console Tables

### ISSUE THREAD

**Issue by mrthehud** [symfony/symfony#13253]
Lowest priority: It'd be nice to have the ability to tell Table to render a string that spans across all columns of a table. I think it'd be slightly nicer than simply printing a line below the table. 

For example, allow Table to render the following:

    +---------------+--------------------------+------------------+
    | ISBN          | Title                    | Author           |
    +---------------+--------------------------+------------------+
    | 99921-58-10-7 | Divine Comedy            | Dante Alighieri  |
    | 9971-5-0210-0 | A Tale of Two Cities     | Charles Dickens  |
    +---------------+--------------------------+------------------+
    | And another 10000 records that are not shown here!          |
    +---------------+--------------------------+------------------+

**Comment by jakzal** [comment]
Thanks for this suggestion. I'm only closing it as the #13368 covers both column and row spans.

**Comment by mrthehud** [comment]
Sounds good to me =)
