### ISSUE TITLE
[security] missing exception wrapper

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13265]
The [handleLogoutException](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L166) states:

        Logout exception occurred; wrapping with AccessDeniedHttpException

however, there is never any wrapping done. It seems that either the log message is wrong, or the method is missing the actual wrapping, which would be something like:

      throw new AccessDeniedHttpException('Logout exception occurred', $exception);

**Comment by WouterJ** [comment]
Thanks for reporting this confusing log message, Joshua!

This has been fixed by https://github.com/symfony/symfony/pull/13418 . That means this issue can be closed now.
