### ISSUE TITLE
asset install in dev breaks classes.php

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#13266]
During a post-install in composer, I run `app/console assets:install --env=dev --no-debug`. After updating from 2.5 to 2.6, I get a fatal error in `app_dev.php`.  If I remove this line, it will work properly.

```
Fatal error: Cannot redeclare class Symfony\Component\Debug\ErrorHandler in /home/ivanderberg/projects/mijn/www/cache/myhostnet/dev/config/classes.php on line 1766
```

The problem is that `Debug::enable();` in app_dev.php calls `ErrorHandler::register()` _before_ the class cache is loaded. For some reason, the `ErrorHandler` gets included in the classes.php file. This is not the case for prod for example.

I've found the following: [FrameworkExtension.php#L151](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L151). 

When I run the asset command, the whole class gets added to `classes.php`. If I run it without, it only gets added to `classes.map` and `classes.php.meta`, but never to `classes.php`. I've tested this in a fresh 2.6 application and it works fine, even _with_ the `assets:install`. 

So my questions:
 - Why is the class body of `ErrorHandler` not in `classes.php` even though it's stated in the Extension?
 - Can this class be removed from the list as it might break in dev in certain installations? Or
 - How can I make sure it's only added when it's not in dev?

I'm not sure why it fails for me, but it makes sense. It already gets autoloaded in `Debug::enable()` while `$kernel->loadClassCache()` is executed after that with the same class in there because the bundle registers it. In the prod env everything works fine, because `Debug::enable()` isn't loaded first.

It seems like `assets:install` adds the `ErrorHandler` to `classes.php` somehow, but I could be wrong.

**Comment by iltar** [comment]
I have to add that I do load the class cache in the console application. Without loading this in the console application when running the `assets:install` command, it seems to work just fine. Is the `ErrorHandler` class body stripped from the classes.php?

If it is, I would like to take this into account when I'm creating a PR for the class cache docs.

**Comment by k0pernikus** [comment]
While upgrading an existing project from symfony2.3 to 2.6 I ran into a similar problem when accessing the site in dev mode. Though running `app/console assets:install` yields in no exception in my case. The hint to disable `Debug::enable()` call in the `app_dev.php` made the site work again.

**Comment by Parad0X** [comment]
@iltar we just ran into this too. In our case we had to add ```Debug::enable()``` in ```app_dev.php```. It only really matters that ```Debug::enable()``` loads ```ErrorHandler``` class. If it's not loaded then Symfony will add it to ```classes.php``` causing redeclaration error next time your run ```app/console```.

**Comment by shirirules** [comment]
we are facing the same problem...
once we add Debug::enable(), the cannot redeclare class error happens...
Clearing the cache does not help either(the second time you reload the page, it does not work anymore).
Is there a quick fix for that?

**Comment by iltar** [comment]
Indeed seems to be related to the `Debug::enable()`. I will close this issue as I have personally managed to fix this.

@shirirules only enable the Debug when the debug should be enabled, check app/console in the standard edition.
