### ISSUE TITLE
[security] Missing foreign key relation in acl_object_identities to acl_classes

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13263]
The `acl_object_identities` table has a field named `class_id`, which points to an entry in the `acl_classes` table, however, there seems to be a foreign key relation missing here. The same `class_id` field can also be found in the `acl_entries` table, where a foreign key relation is set.

**Comment by stof** [comment]
Can you provide a PR to fix this ?

**Comment by jaytaph** [comment]
@stof yes, but i was curious if this was indeed a bug, or if there is an underlying reason for this.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
