### ISSUE TITLE
[Process] Run a process within a webrequest

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#13261]
I have a browser triggered php-script which is ment to start a process. The `Process` class then wants to use `/dev/tty` which on my Ubuntu 14 LTS is only readable as root per default.

that means no matter which process I start it runs into  a Warning and finally dies:

```
Warning: proc_open(/dev/tty): failed to open stream: No such device or address in XXX/vendor/symfony/process/Symfony/Component/Process/Process.php on line 291
```

Should `setTty` also throw exceptions when `/dev/tty` is not readable?

**Comment by staabm** [comment]
I am running into the issue right here: https://github.com/sensiolabs/melody/blob/master/src/SensioLabs/Melody/Runner/Runner.php#L50

**Comment by staabm** [comment]
//cc @jeremy-derusse @lyrixx

**Comment by stof** [comment]
@romainneutron ping

**Comment by lyrixx** [comment]
( @romainneutron is on holidays for 10 days)

**Comment by staabm** [comment]
@romainneutron any updates on this?

**Comment by romainneutron** [comment]
Hello,

sure, an exception should be thrown in case `/dev/tty` does not exist

**Comment by bdossantos** [comment]
+1, Same issue with a melody task launched by a cron job ...
