### ISSUE TITLE
[Security][Bug] urlRedirectAction suddenly triggers security (BC break?)

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#13277]
I have a login based on parameters:
```
@Route("/hash/{hash}/", name="login-hash", requirements={"hash"=".+"})
```

This works fine in 2.5 but breaks in 2.6. The reason I have the trailing slash, is the automatic redirect. However, the security component also listens to this url and gets triggered as of 2.6.

Url I visit: `/app_dev.php/hash/99abf956e3d21a6b607ce38d3d5ce6a1`

Some information:
```
    firewalls:
        hash:
            pattern: ^/hash/.*
```

This combination gives me the following attributes:
```
object(Symfony\Component\HttpFoundation\ParameterBag)[32]
  protected 'parameters' => 
    array (size=8)
      '_controller' => string 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction' (length=79)
      'path' => string '/hash/99abf956e3d21a6b607ce38d3d5ce6a1/' (length=39)
      'permanent' => boolean true
      'scheme' => null
      'httpPort' => int 80
      'httpsPort' => int 443
      '_route' => string 'login-hash' (length=10)
      '_route_params' => 
        array (size=5)
          'path' => string '/hash/99abf956e3d21a6b607ce38d3d5ce6a1/' (length=39)
          'permanent' => boolean true
          'scheme' => null
          'httpPort' => int 80
          'httpsPort' => int 443
```

As you can see, this gets a nice redirect. However, the security component picks up this url and starts validating. It sees that it matches the url but my parameter `{hash}` is empty.

### There are 2 ways of fixing this

Solution 1: add a second route:
```
@Route("/hash/{hash}") // sequence matters in this case!
@Route("/hash/{hash}/", name="login-hash", requirements={"hash"=".+"})
``` 

Solution 2: I modify my `security.yml`:
```
    access_control:
        # protect everything
+       - { path: ^/hash/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*,    roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        hash:
-           pattern: ^/hash/.*
+           pattern: ^/hash/.*/
```

### Expected behavior
The redirect should be done with the trailing slash and _then_ the security component should hook in like it used to.

I have no idea when this exactly broke, but my guess is somewhere in pre-2.6.0

**Comment by jaytaph** [comment]
I tried to replicate this issue, but i cannot seem to get it running properly in 2.5.x neither. I'm testing with basic http auth, and both 2.5 and 2.6 seem to return a redirectResponse from the routerListener (as expected), but both versions return an "overridden" 401 response  from the firewall.

**Comment by iltar** [comment]
@jaytaph what does your route, access_control and firewall definition look like?

**Comment by jaytaph** [comment]
@iltar:

    security:
        providers:
            in_memory:
                memory:
                  users:
                    foo:
                      password: foo
                      roles: ROLE_FOO
        encoders:
            Symfony\Component\Security\Core\User\User: plaintext
        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            hash:
                pattern: ^/hash/.*
                http_basic: ~
        access_control:
          - { path: ^/.*,    roles: IS_AUTHENTICATED_FULLY }


The route:

    class DefaultController extends Controller
    {
        /**
         * @Route("/hash/{hash}/", name="login-hash", requirements={"hash"=".+"})
         */
        public function indexAction($hash)
        {
            return new Response('HASH: '.$hash, 200);
        } 
    }

**Comment by iltar** [comment]
What if you add:
```
        secured_area:
            pattern:               ^/.*
            context:               secured_area #add this to the hash firewall as well
```

**Comment by iltar** [comment]
After a lot of testing and help from @jaytaph, it seems to be the same case in 2.5. I triggered it because of the trailing slash in my route. Because it's a redirect, it won't match the `{hash}` parameter and proceeds to return this redirect response.

The problem is that the Security still hooks in as the security firewall matches on that url. I disgree with this behavior but fixing it could cause a lot of apps to break. Any suggestions? If it can be fixed, should it be done on 3.0 only?

**Comment by xabbuh** [comment]
@iltar Isn't this an issue anymore?

**Comment by iltar** [comment]
@xabbuh, not sure as it is fixed by setting the security with trailing slash as well. The behaviour in symfony is too complex to fix this specific behaviour because of when this controller is determined.

Maybe this is an issue, but the way its fixed makes sense.
