### ISSUE TITLE
[security] Removing UsernamePasswordFormAuthenticationListener in favor of using the SimpleFormAuthenticationListener

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13281]
Right now, the only difference between the `UsernamePasswordFormAuthenticationListener` and the `SimpleFormAuthenticationListener` is the fact that the authentication provider can be injected. All other code inside is equal. 
I think it would be fairly easy to remove the `UsernamePasswordFormAuthenticationListener` altogether, and let the `form_login` factory insert the `SimpleFormAuthenticationListener` with a custom authentication provided that creates the UsernamePasswordToken. 

This way, we could get rid of the whole `UsernamePasswordFormAuthenticationListener` class, and the duplicated code.

**Comment by iltar** [comment]
I think the whole `form_login` and `simple_form` share a lot of code and setup. It would be really nice to have the `form_login` user the `simple_form` as a starter. It's terribly confusing for people who try to implement their own authentication.

**Comment by fabpot** [comment]
Closing as the Simple*Listener will be deprecated in 3.1 (see #15873)
