### ISSUE TITLE
[Form] reading initial communication packet  Symfony2.4.10

### ISSUE THREAD

**Issue by nearly** [symfony/symfony#13284]
Test on Symfony2.4.10
      get the url  [demo/contact] ,submit and throw follow Exception: An exception occured in driver: SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 111 .
     anyone can solve it, thank you.

**Comment by iltar** [comment]
You might want to give a bit more information, besides of that, 2.4 is not supported anymore. I suggest you visit the [IRC Channel](http://symfony.com/irc). This issue tracker if for Symfony issues and not for help with debugging your code.

**Comment by nearly** [comment]
after install latest Symfony2.4.10, go to the url:localhost/app_dev.php/demo/contact,  content submit and throw the front problem, but a few day  before i install symfony2.4 ,it work fine.  if mysql connect set right, it work fine.  but before it work fine however mysql connect set right or not. thank you.

**Comment by fabpot** [comment]
@nearly Can you use IRC or the mailing-list for support? Thanks.
