### ISSUE TITLE
Form using Validator Constraint File - Max File Size not validating correctly, element returns NULL

### ISSUE THREAD

**Issue by 0mars** [symfony/symfony#13291]
When submitting a file greater than the max file size, and then trying to get the UploadedFile, it returns null instead of an UploadedFile instance.
```php
use Symfony\Component\Validator\Constraints\File;
// adding form element
$form->add('my_file', 'file', [
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF',
                    ])
                ]
            ]);
```
```php
// in controller
$form->submit($this->getRequest()->request->all());
var_dump($form->get('my_file')->getData());
```
*Actual:*
```php
NULL
```
*Expected:*
```php
Symfony\Component\HttpFoundation\File\UploadedFile Object
```

**Comment by lscholten** [comment]
I tried to recreate this issue in a fork of the Symfony Standard Edition (v2.6)

I came to the following conclusions, which are summarized in the DefaultController (https://github.com/lscholten/symfony-standard-issue-13291/blob/2.6/src/AppBundle/Controller/DefaultController.php)

You passed all request data to the submit function: 
```
$form->submit($this->getRequest()->request->all());
```
This won't work correctly since all request data (not just the form data) is submitted. I fixed it and recreated your issue by using:
```
$form->submit($this->getRequest()->request->get($form->getName()));
```
And indeed, the `var_dump` resulted in `NULL`.

What happens is that `$this->getRequest()->request` only contains the actual form data, and not the file data, this is available in `$this->getRequest()->files`. To make it work, I submitted the file data together with the request data:
```
$form->submit(
    array_merge(
        $this->getRequest()->request->get($form->getName()),
        $this->getRequest()->files->get($form->getName())
    )
);
```

However, this could've all been avoided when using the recommended method `$form->handleRequest(...)` as I've demonstrated in the last action. (http://symfony.com/doc/current/book/forms.html#book-form-handling-form-submissions)
```
$form->handleRequest($request);  // $request is in injected into the action
```


Conclusion: probably not a Symfony bug

**Comment by humanoyd** [comment]
The weird thing is that, if the file does not exceed max size you don't need to do an array_merge, it works perfectly, and if the mime type validation fails, its also reported on the form errors, but its not the case for maxSize

**Comment by jakzal** [comment]
@lscholten excellent analysis!

@humanoyd I just tried on @lscholten's fork and it indeed works as expected, consistently, no matter what the file size is. Could you please try it on that fork and alter the code so it shows how to reproduce your problem?

**Comment by humanoyd** [comment]
Checkout out the code, tried
expected-behavior: With a PDF exceeds max size (18 MB)
```php
/**
     * @Route("/app/expected-behaviour", name="expected_behaviour")
     */
    public function expectedBehaviourAction()
    {
        $form = $this->createFileForm();

        if ($this->getRequest()->getMethod() === "POST") {
            $form->submit(
                array_merge(
                    $this->getRequest()->request->get($form->getName()),
                    $this->getRequest()->files->get($form->getName())
                )
            );

            var_dump($form->get('my_file')->getData());
        }

        return $this->render('default/index.html.twig', ['form' => $form->createView()]);
    }
```

Getting:
```
Warning: array_merge(): Argument #1 is not an array
500 Internal Server Error - ContextErrorException 
```

**Comment by jakzal** [comment]
@humanoyd what's `upload_max_filesize` set to in your `php.ini`?

**Comment by humanoyd** [comment]
UPDATE: if the file exceeds upload_max_filesize, exception is thrown:
```
Warning: array_merge(): Argument #1 is not an array
500 Internal Server Error - ContextErrorException 
```

Only $form->handleRequest($request); works properly with files greater than the upload_max_filesize

**Comment by humanoyd** [comment]
Here is the analysis of 3 cases
```php
    private function createFileForm()
    {
        return $this->createFormBuilder()
            ->add('my_file', 'file', [
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF',
                    ])
                ]
            ])
            ->add('field2','text',['required'=>true])
            ->add('submit', 'submit')
            ->getForm();
    }
```
```php
    /**
     * @Route("/app/original-not-working2", name="original_not_working")
     */
    public function orginalNotWorkingAction()
    {
        $form = $this->createFileForm();

        if ($this->getRequest()->getMethod() === "POST") {
            $form->submit($this->getRequest());
            var_dump($form->get('my_file')->getData());
        }

        return $this->render('default/index.html.twig', ['form' => $form->createView()]);
    }
```
Using 
```upload_max_filesize = 8M```

### 1. Case 1
File: *some-file.odt* 
size: *1.2KB*

**Expected:**
Error: Please upload a valid PDF
**Actual:**
Error: Please upload a valid PDF

### 2. Case 2:
File size greater than validation rule, but less than php's upload_max_filesize
File: *some-file2.odt* 
size: *7MB*
**Expected:**
The file is too large. Allowed maximum size is 2 MB.
**Actual:**
The file is too large. Allowed maximum size is 2 MB.

### 3. Case 3:
File size greater than post_max_size 
File: *some-file3.odt* 
size: *11MB*
**Expected:**
The file is too large. Allowed maximum size is 2 MB.
**Actual:**
Nothing, No errors, even on other form fields

**Comment by humanoyd** [comment]
@jakzal pushed the code to:
https://github.com/humanoyd/symfony-standard-issue-13291

**Comment by jakzal** [comment]
@humanoyd excellent! I'll have a look later today or tomorrow.

**Comment by jakzal** [comment]
Looks like it was introduced when moving `post_max_size` from `FormValidator` to request handlers in #11924. As @humanoyd noticed when using `submit()` the form passes validation, even though the uploaded file was bigger than the allow post size.

In both cases (`handleRequest()` and `submit()`) a warning is trigger.

**Comment by Tobion** [comment]
To sum up: You have to use `handleRequest` to get max post size validation logic because it's part of the request handling. At submit time it's not done anymore because if the max post size is exceeded, the post content is empty. This is also why why you have the above `Warning: array_merge(): Argument #1 is not an array 500 Internal Server Error - ContextErrorException ` in your own code.
The only problem is that the max post size validation is missing when using `submit($request)` as trying to fix in #16088. But this approach is deprecated anyway. Feel free to open a new issue or PR for this.

**Comment by MgFrobozz** [comment]
I've encountered the same problem when the file size exceeds upload_max_filesize and when using handleRequest. Config details below.

In HttpFoundationRequestHandler.php::handleRequest,
$this->serverParams->getPostMaxSize() returns 576716800
$this->serverParams->getContentLength() returns null
and it never reaches $form->addError(...)

In ServerParams.php::getContentLength,
$_SERVER['CONTENT_LENGTH'] is not set
however, print_r($_SERVER) shows
[HTTP_CONTENT_LENGTH] => 600001284

I think getContentLength needs to check both CONTENT_LENGTH and HTTP_CONTENT_LENGTH.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Util/ServerParams.php shows the same issue

Config:
symfony 2.5.12
Ubuntu 14.04.4 LTS

**Comment by darius-v** [comment]
how handleRequest() works for you? For me it goes into block where is such comment " // Don't submit the form if it is not present in the request" .

I checked form name is 'form'.
