### ISSUE TITLE
[Form][DI] Register form type as service with empty form name

### ISSUE THREAD

**Issue by egeloen** [symfony/symfony#13308]
Hey!

I'm currently creating a REST API using the form component. Some of my form types use dependencies and so, are registred as services with the `form.type` tag and the `alias` property. 

In a REST context, it would be nice to use forms with an empty root name in order to be more user friendly but I'm a little bit stuck since we can't register forms in the container with empty name and alias it to a virtual name in order to use it.

Can someone point me why the `alias` property and the form type name must be equal? Is there any hope to add this feature and futhermore, how can it be added?

**Comment by jakzal** [comment]
The only place where we rely on these two names to be the same is the [DependencyInjectionExtension](https://github.com/symfony/symfony/blob/e2ac5dfc78c426cc7f434b0953c62f4534823b91/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php#L46-L53), which throws an exception if `form.type` doesn't match the `alias`. 

From user's perspective, it would be odd if you were adding a field, or creating a form with `$builder->add('field', 'my_type')` and `my_type` wouldn't match the name of the form. We also need them to match to get appropriate service from the  container. It's hard to change this convention at this point.

As written in [the docs](http://symfony.com/doc/current/book/forms.html#handling-form-submissions):

> If you need more control over exactly when your form is submitted or which data is passed to it, you can use the submit() for this. Read more about it in the cookbook.

To workaround your problem you can do something like:

```php
$form->submit(['my_type' => $request->request->all()]);
```

**Comment by egeloen** [comment]
@jakzal Thanks for your answer. Let's close this one since the workaround sounds like a good solution and the submit seems here for this kind of use cases.

**Comment by egeloen** [comment]
Just for the record, the workaround is even more simple:

``` php
$form->submit($request->request->all());
```

Thanks @jakzal

**Comment by stof** [comment]
An empty form type name is not valid (you would have issues about creating unique empty identifiers). Keep in mind that the form name and the form type name are 2 separate concepts (even though the controller shortcut uses the type name as name of the form)
