### ISSUE TITLE
Deprecated Unescaper is being used Yaml itself

### ISSUE THREAD

**Issue by antonioribeiro** [symfony/symfony#13306]
It's being used here https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Yaml/Inline.php#L263

And causing

    [ErrorException]
    Constant ENCODING in class Symfony\Component\Yaml\Unescaper is deprecated since version 2.5 and will be removed in 3.0.

**Comment by fabpot** [comment]
@antonioribeiro Thanks for noticing it. We are very-well aware of these warnings and we are working as fast as possible to cleanup our codebase. Unfortunately, it takes a lot of time and it will probably be "influx" for another couple of weeks. Very sorry about the inconvenience.

**Comment by fabpot** [comment]
fixed now

**Comment by antonioribeiro** [comment]
Thank you, sir!
