### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#13311]
Since updating from v2.6.1 to v2.6.3 I am getting the following exception:

```
An exception has been thrown during the compilation of a template ("The template does not support the "bundle" parameter.") in "@AcmeDemo/template.html.twig".
```

template.html.twig extends:

```
{% extends 'base.html.twig' %}
```

May relate to a835b18203fbe8a0cd2cf99c4967cf683f83d051, https://github.com/symfony/symfony/pull/12894, https://github.com/symfony/AsseticBundle/issues/331

**Comment by trsteel88** [comment]
fyi, this is occurring on v2.6.3 on the Symfony Standard version as well.

To replicate install https://github.com/symfony/symfony-standard v2.6.3

Go to "/app/example" and the page will display.

Now, open base.html.twig and change:

```twig
{% block stylesheets %}{% endblock %}
```

to:

```twig
{% block stylesheets %}
    {% stylesheets filter='cssrewrite,?yui_css'
        'bundles/framework/css/body.css'
    %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock stylesheets %}
```

You will now get the error.

**Comment by fabpot** [comment]
Have you tried to use the latest version of Assetic as @stof mentioned that he fixed the issue?

**Comment by trsteel88** [comment]
@fabpot, there was a commit for it here https://github.com/symfony/AsseticBundle/commit/ae29934ccb666fe21d685037a6b2246f4013730a

I have tried forcing ~1.3@dev and dev-master but I still get the same error. Looks like this might be better suited in the assetic repo. Let me know if you would like me to close this issue.

**Comment by fabpot** [comment]
Let's keep this issue open until we find out how to fix this problem. @stof Can you have a look?

**Comment by mvar** [comment]
Interesting issue. Somehow one project runs successfully with newest Symfony and Assetic bundle versions, another fails on all Assetic blocks in template. `@dev` version of Assetic bundle fixes the issue.

**Comment by javiereguiluz** [comment]
@trsteel88 I can confirm the same error when using the following dependencies:

```json
"symfony/symfony": "2.6.3",
"symfony/assetic-bundle": "~2.3",
```

But when I change them for the following, everything works again:

```json
"symfony/symfony": "2.6.3",
"symfony/assetic-bundle": "dev-master",
```

**Comment by kniziol** [comment]
@javiereguiluz same for me.

I have replaced
```"symfony/assetic-bundle": "~2.3"```
with
```"symfony/assetic-bundle": "2.5.*@dev"```
and the problem is gone.

So, why there is no any information in documentation or version of the ```symfony/assetic-bundle``` isn't higher? It's annoying.

**Comment by trsteel88** [comment]
Hmmm looks like I was updating the component instead of the bundle. Will give this a go when I'm back at a computer.

**Comment by svassaux** [comment]
yes, same bug here. I chose to stay with symdony 2.6.1 cause I prefer not to play with @dev versions.

**Comment by edwines** [comment]
Same issue in the LTS `2.3`

Bad to know that when I do some `composer update` in a project with stable dependencies will generate this kind of breaks.

**Comment by Kaz-** [comment]
I'm having this issue with LTS 2.3 too, just after a `composer update`, can I use `"symfony/assetic-bundle": "dev-master"`to fix the issue ?

**Comment by trsteel88** [comment]
This has been resolved with the stable release of AsseticBundle v2.6.0 (https://github.com/symfony/AsseticBundle/releases/tag/v2.6.0)
