### ISSUE TITLE
[Form] add field in case of error

### ISSUE THREAD

**Issue by ghostika** [symfony/symfony#13318]
It's somewhere a feature request, I want to have a symfony form, where in case of an error or after certain amount of failed form submission , I can show up a captcha field. I spent some time on it and tried to solve the problem, with form event listeners to add or remove this additional field, but I couldn't get it work.
If someone has an idea for this, then I would be glad to read it, if not then this would be a feature request.

**Comment by ogizanagi** [comment]
What is bothering you in order to do that ? A new form type based on event listeners and the session for instance (to store the number of attempts) might be a solution. But I don't think it should be a new feature in Symfony, as the captcha system might be provided from different implementations, so bundles will be the best to fit the need.

**Comment by ghostika** [comment]
The captcha was just an example, the problem is, the form can't be changed after submission, so I can't build this workflow.

**Comment by ogizanagi** [comment]
In fact, this is not a real issue, as you have many workarounds for those kind of problematic, using event listeners on child forms.
You might either:
- Wrap your form into another one, and bind a POST_SUBMIT event listener on the child form (your form)
- Bind a POST_SUBMIT event listener on the last child of the form, excluding the eventual fields used for the captcha.

Basic example for the first solution:

```php
class CaptchableType extends AbstractType
{
    function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $wrappedForm = $options['form_instance'];
        $formOptions = $options['form_options'];
        $maxAttempts = $options['form_options'];

        $builder
            ->add('wrapped_form', $wrappedForm, $formOptions);

        $builder->get('wrapped_form')->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event) use ($maxAttempts){

            if($maxAttempts <= $nbAttempts = $this->session->get('nb_attempts')) {
                $event->getForm()->getParent()->add('captcha', 'captcha_form_type', array());
            }

            if(!$event->getForm()->isValid()) {
                $this->session->set('nb_attempts', ++$nbAttempts);
            }
        });
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setRequired(array(
                'form_instance',
                'max_attempts',
            ))
            ->setOptional(array(
                'form_options',
            ));
    }

    public function getName()
    {
        return 'captchable_form';
    }
}
````
```php
# In a controller:$yourFormDatas = //...
$yourFormOptions = //...

$form = $this->createForm('captchable_form', array(
    'wrapped_form' => $yourFormDatas,
), array(
    'form_instance' => new YourForm(),
    'form_options' => $yourFormOptions,
));
```

(The session usage was just an example)

**Comment by ghostika** [comment]
@ogizanagi First of all, I would like to thank you for the detailed answer and especially the example code. I used a lot the symfony form, but I never thought about to use it like this, as you suggested in the first tip.
I tried all 3 of your suggestions, but I couldn't make it work actually. With the first suggestion, checking if the subform ( the original one ) is valid didn't worked, it showed that it's valid but it wasn't and even if I dumped the errors there, it was empty, but if the request went through I saw in the debug toolbar and also in my frontend the form errors.
With the other 2 solution the problem was the same. If at the initial load of the form, I remove the extra field, then at submission there will be no value there, so if at submission, for example in presetdata, i'm not removing the extra field ( what has validation constraints ) then even if everything else in my form is valid, that one will be invalid and the submission fail. 
This is the same problem if I don't use event listeners.

**Comment by ogizanagi** [comment]
You're welcome.
Well, I might try it when I've some time for that, but actually, it seems that the [`ValidationListener`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php) only validate the form from the root. Then the `isValid` method on subforms will not work. I never tried such a thing (i.e embedded form validation before the root form), so I misled you with some tricks used for similar cases, but not with the same concerns.

**Comment by ogizanagi** [comment]
Hi there.
I took a little of my time in order to find a way to build the desired workflow with the current form component.
If you're still searching a way to achieve this, you could have a look to https://github.com/ogizanagi/symfony-13318 and the main [Controller](https://github.com/ogizanagi/symfony-13318/blob/master/src/Acme/DemoBundle/Controller/CaptchableFormController.php#L21).
You can test the form behavior on the `app_dev.php/demo/captchable-form/example` URL.

The `CaptchaType` is not aware of the attempts storage logic, but it could be easily thought.
EventDispatcher could also be used in order to centralize the attempts when the form is submitted & invalid.

I agree this is not an easy way to achieve such a workflow, and that the ability to update the form after submission should ease this.

**Comment by HeahDude** [comment]
A possible workaround would be to increment the value of a hidden field `_attempts` on each submission and add the desired field when necessary.

Form events should allow to do this without much work.

**Comment by webmozart** [comment]
@ogizanagi It should be possible to solve the validation issue by putting the option

~~~php
'constraints' => new Valid(),
~~~

onto the embedded form.

This use case should actually not be *that* complicated to solve. To expand on the previous example, I would attempt the following solution:

~~~php
class YourType extends AbstractType
{
    function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // your calls to ->add() here
        ;
        
        $actualAttempts = $this->session->get('nb_atempts', 0);
        
        if ($actualAttempts > $options['max_attempts']) {
            $builder->add('captcha', CaptchaType::class, [
                // don't map to your data object
                'mapped' => false,
            ]);
        }

        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($options){
            if ($event->getForm()->isValid()) {
                $this->session->remove('nb_attempts');
            } else {
                $this->session->set('nb_attempts', $this->session->get('nb_attempts') + 1);
            }
        }, -100); // low priority to run after ValidationListener
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class' => // your data class
        ]);
        
        $resolver->setRequired('max_attempts');
    }
}
~~~

Something like this should work.

**Comment by ghostika** [comment]
@webmozart thanks, I will try this out

**Comment by webmozart** [comment]
Let me know if you face any more problems. :)
