### ISSUE TITLE
The YAML parser fails on some valid YAML patterns

### ISSUE THREAD

**Issue by Azenet** [symfony/symfony#13345]
Valid YAML, parses successfully : 
```
listeners:
  - port: 12345
    stuff: asd
```

Valid YAML, parses successfully : 
```
listeners:
- port: 12345
```

Valid YAML, parse fails : 
```
listeners:
- port: 12345
  stuff: asd

Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Unable to parse at line 3 (near "  stuff: asd").'
```

Code used : 
```php
<?php

require_once('vendor/autoload.php');
use Symfony\Component\Yaml\Parser;

$yaml = new Parser();
$yaml->parse(file_get_contents('test.yml'));
```

**Comment by aitboudad** [comment]
I'll work on it

**Comment by fabpot** [comment]
Supporting all YAML features is not our goals, we just implement what we need for configuration files.

@aitboudad I'm not sure if it's worth working on this one. Let's do it only if we can have a minimal impact on the existing code.

**Comment by stof** [comment]
@fabpot the issue is that this is the default formatting for YAML files dumped in other languages (Ruby for instance). This makes the interoperability harder if this format is not supported

**Comment by xabbuh** [comment]
However, this issue is the same as #8093 (and probably also #10885 and #11019).
