### ISSUE TITLE
The folder named r+e.gex[c]a(r)s breaks our build

### ISSUE THREAD

**Issue by MatthewHarrigan** [symfony/symfony#13350]
We run rpmbuild as part of our build process and the folder /src/Symfony/Component/Finder/Tests/Fixtures/r+e.gex[c]a(r)s/ seems to be linked to a "error: File not found by glob: ..." error. Presumably the some character in the folder name is being treated as a wild card or something strange?

**Comment by jakzal** [comment]
What operating system is your CI running on?

re #11984 #11989

**Comment by MatthewHarrigan** [comment]
Centos

**Comment by jakzal** [comment]
Could you paste the full error message?

**Comment by MatthewHarrigan** [comment]
We use a grunt plugin that wraps the creation of RPMs called easy_rpm, it's running this on our CI that's failing. We're not running the Symfony tests as part of the build. If we remove the r+e.gex[c]a(r)s folder before the following step then the RPM creation works.

Running "easy_rpm:dist" (easy_rpm) task
Creating RPM folder structure at /var/lib/jenkins/workspace/kandltimelines/kandltimelines/target/tmp-eyD1KYxq9g
Copying files to tmp directory
Generating RPM spec file
Building RPM package
Execute: rpmbuild -bb --buildroot /var/lib/jenkins/workspace/kandltimelines/kandltimelines/target/tmp-eyD1KYxq9g/BUILDROOT/ tmp-eyD1KYxq9g/SPECS/kandltimelines-1277-noarch.spec
Error: error: File not found by glob: /var/lib/jenkins/workspace/kandltimelines/kandltimelines/target/tmp-eyD1KYxq9g/BUILDROOT/usr/share/kandltimelines/vendor/symfony/finder/Symfony/Component/Finder/Tests/Fixtures/r+e.gex[c]a(r)s/dir/bar.dat
File not found by glob: /var/lib/jenkins/workspace/kandltimelines/kandltimelines/target/tmp-eyD1KYxq9g/BUILDROOT/usr/share/kandltimelines/vendor/symfony/finder/Symfony/Component/Finder/Tests/Fixtures/r+e.gex[c]a(r)s/dir/bar.dat
Warning: Task "easy_rpm:dist" failed. Use --force to continue.

**Comment by jakzal** [comment]
It looks like a bug in the easy_rpm plugin, not Symfony.

**Comment by MatthewHarrigan** [comment]
Fair enough. It is a strange name for a folder but I suppose r+e.gex[c]a(r)s is a valid. I'd consider finding another way to test this though as it's likely to cause other strange issues: it's probably best to stick to upper, lowercase ".", "_". Happy to close though.

**Comment by jakzal** [comment]
It was implemented to fix a specific issue (#11970), and checking for lowercase ".", "_" is not enough in this case. 

I'd advice to try fixing the easy_rpm plugin first, and if that fails, reopen this issue with proposition how to solve it differently.

**Comment by JunaidBabu** [comment]
Getting a similar error while uploading the laravel app to Google App Engine.

ERROR appcfg.py:1909 Invalid character in filename: vendor/symfony/finder/Tests/Fixtures/r+e.gex[c]a(r)s/dir/bar.dat

**Comment by cyannick** [comment]
Also getting the same error as @JunaidBabu:
ERROR appcfg.py:1910 Invalid character in filename: vendor/symfony/finder/Tests/Fixtures/r+e.gex[c]a(r)s/dir/bar.dat

**Comment by jmar83** [comment]
Here: https://www.svnforum.org/forum/opensource-subversion-forums/apache-subversion-1-8-support/80273-errors-working-copy-is-not-up-to-date-svn-commit-failed-filesystem-has-no-item

Regards,
Jan
