### ISSUE TITLE
Callback validation constraint - method gets wrong parameter

### ISSUE THREAD

**Issue by jumika** [symfony/symfony#13362]
Hi!

I'm trying to use the callback validation constraint. The documentation says that above symfony 2.4 i should introduce the parameter of the validation method as Symfony\Component\Validator\Context\ExecutionContextInterface

However i get this error message when i submit my form and it tries to validate my entity:
Catchable Fatal Error: Argument 1 passed to Jumi\AgroalfaBundle\Entity\Message::validate() must be an instance of Symfony\Component\Validator\Context\ExecutionContextInterface, instance of Symfony\Component\Validator\ExecutionContext given

These are my use statements:
```
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
```
Here is my validate method:
```
    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context) {
        if(!$this->email && !$this->tel) {
            $context->buildViolation('A telefonszám vagy az e-mail cím mezőt kötelező kitölteni!')
                ->atPath('tel')
                ->addViolation();
        }
    }
```
In my composer.json this is required:
"symfony/symfony": "2.6.*"

**Comment by jakzal** [comment]
**Please use mailing list for support questions.**

Depending on Symfony version you use, and the validation api version you'll need a type hint with a different interface. See http://symfony.com/doc/2.5/reference/constraints/Callback.html#the-callback-method

>  if you're using the older 2.4 validation API, you'll need this instead
> use Symfony\Component\Validator\ExecutionContextInterface;

**Comment by jumika** [comment]
Thank you for your answer. I've found out that this was my fault. I've set framework.validation.api to 2.4 in config.yml before and forgot about it.
