### ISSUE TITLE
[CSS] WebProfiler, break-word

### ISSUE THREAD

**Issue by nicovak** [symfony/symfony#13366]
Class ".sf-reset .block" should have "word-break: break-all;"  like specified here http://www.w3schools.com/cssref/css3_pr_word-break.asp

The CSS file is 
/src/Symfony/Bundle/FrameworkBundle/Resources/public/css/body.css

**Comment by jakzal** [comment]
Why? Could you paste before/after screenshots and possibly send a pull request?

**Comment by nicovak** [comment]
I did an exception for you : 
![screen](http://i.imgur.com/owkghJY.png "screen")

We can try other property for break-word.

**Comment by fabpot** [comment]
@nicovak Any chance you can provide a pull request for this change that indeed looks like a good idea?

**Comment by nicovak** [comment]
@fabpot Done, https://github.com/symfony/symfony/pull/13637
