### ISSUE TITLE
[Process][Windows] Command line executable with spaces

### ISSUE THREAD

**Issue by tomzx** [symfony/symfony#13360]
Hi,

I'm using a library which makes use of Symfony's `Process` library. Furthermore this library uses the `ExecutableFinder` class. `ExecutableFinder` is used to find where my `git` executable is located, which it is able to do so.

However, when it is time to create and run the process, things do not work as expected. 

`Process` generates the following command line

`cmd /V:ON /E:ON /C "(C:\Program Files (x86)\Git\cmd\git.EXE --version) 1>"E:\php\tmp\sf_B41A.tmp" 2>"E:\php\tmp\sf_B41B.tmp""`

which, if executed directly in `cmd.exe`, returns the follwing:

`\Git\cmd\git.EXE was unexpected at this time.`

If I inspect the process object itself, it is not possible to retrieve the reason why it failed from either stdOut or stdErr.

After taking a quick look, it seems like the issue is that the executable needs to be escaped with a set of double quotes ("). Thus the command line that should be generated should look like

`cmd /V:ON /E:ON /C "("C:\Program Files (x86)\Git\cmd\git.EXE" --version) 1>"E:\php\tmp\sf_B41A.tmp" 2>"E:\php\tmp\sf_B41B.tmp""`

which, if executed in `cmd.exe`, works as expected.

Are clients (people using the `Process` library) suppose to deal with that issue themselves, or should `Process` be handling that?

**Comment by xabbuh** [comment]
Do you use the `ProcessBuilder` or do you build the command-line on your own and pass it to the `Process` constructor?

**Comment by tomzx** [comment]
The [library](https://github.com/klaussilveira/gitter/blob/master/lib/Gitter/Client.php#L69) builds the command-line itself and passes it as a string to the `Process` constructor.

```php
$process = new Process($this->getPath() . ' ' . $command, $repository->getPath());
```

`$this->getPath() ` is basically

```php
$finder = new ExecutableFinder();
$path = $finder->find('git', '/usr/bin/git');
```

**Comment by stof** [comment]
Then the issue is in your library. If you are not using the ProcessBuilder, you need to take care of escaping each part of the command yourselves. The Process class cannot do it for you because it cannot know whether a space is here to separate arguments or because you forgot to escape an argument.
The ProcessBuilder on the other hand is handling escaping for you, because it knows about each part of the command

**Comment by tomzx** [comment]
@stof Alright, thanks, I'll send them a PR using ProcessBuilder.
