### ISSUE TITLE
[Console][Table] Add support for colspan/rowspan

### ISSUE THREAD

**Issue by tomzx** [symfony/symfony#13368]
Much like an HTML table, it would be nice to be able to specify colspan/rowspan on the data of the table.

My suggestion on how the users would use it is as follow:

To specify a `colspan`/`rowspan`other than 1 (default), the user calls `addRow`/`addRows`/`setRow`/`setRows` with a new parameter `$options`. The `$options` parameter is an array where the key is the row cell number and the value is an array of properties that apply to that cell. In this case, `colspan` and `rowspan`.

```php
$table->addRow(['data', 'data', 'data']);
$table->addRow(['data', 'data'], [
	0 => [
		'colspan' => 2,
	],
	1 => [
		'rowspan' => 3,
	],
]);
$table->addRow(['', '']);
$table->addRow(['', '']);
```

```
+------+------+------+
| data | data | data |
+------+------+------+
| data        |      |
+-------------+      +
|      |      | data |
+-------------+      +
|      |      |      |
+-------------+------+
```

Equivalent html

<table>
    <tr>
        <td>data</td>
        <td>data</td>
        <td>data</td>
    </tr>
    <tr>
        <td colspan="2">data</td>
        <td rowspan="3">data</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</table>

```html
<table border="1">
    <tr>
        <td>data</td>
        <td>data</td>
        <td>data</td>
    </tr>
    <tr>
        <td colspan="2">data</td>
        <td rowspan="3">data</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</table>
```

**Comment by xabbuh** [comment]
Something similar (support for "colspans") was asked for in #13253.

**Comment by aitboudad** [comment]
look interesting, so I'll work on it :)
