### ISSUE TITLE
FrameworkBundle - Fallback locale

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#13373]
Ok, so within the translator documentation (http://symfony.com/doc/current/components/translation/introduction.html#fallback-locales) you can set multiple fallback locales. However, in the framework bundle, the fallback config option is a "scalarNode" and doesn't allow you to set an array (https://github.com/symfony/FrameworkBundle/blob/master/DependencyInjection/Configuration.php#L463)

Within the extension, it is checking if the value is an array (https://github.com/symfony/FrameworkBundle/blob/master/DependencyInjection/FrameworkExtension.php#L645). However, you can't actually set an array or you get the error:

```
InvalidTypeException in ScalarNode.php line 36:
Invalid type for path "framework.translator.fallback". Expected scalar, but got array.
```

Rather than using scalarNode, should this be changed to arrayNode?

**Comment by ihsanudin** [comment]
+1
