### ISSUE TITLE
[security] Acl doesn't cache misses.

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13379]
The [AclProvider](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/AclProvider.php) is able to cache queried entries in order to speed up the process of handling multiple calls to the same object identifier. However, it does not cache any misses. This means that a miss can result in multiple calls to fetch the ACL records for a non-existing OID, when we already have established that no such OID exists in the first place.

Maybe it would be a good idea too to store this information into the cache as well, so we can immediately thrown an `AclNotFoundException` without querying the database.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
