### ISSUE TITLE
[Console][Table] Apply options/style to table cells

### ISSUE THREAD

**Issue by tomzx** [symfony/symfony#13370]
It would be nice if `Table` was able to be styled as much as a HTML table can.

Use case: Center some cells

I think the way we can approach this with the current implementation is to add an optional `$options` parameter to the methods adding/setting rows.

The array would look as such:

``` php
[
    cellNumber => [
        propertyA => value,
        propertyB => value,
        colspan => value,
        rowspan => value,
        align => left|center|right,
        format => '<info>%s</info>',
    ]
]
```

By using keyed cell number (for a single row), we can specify data for only specific cells (does not force the user to specify an empty array for each cell).

Any undefined property implies the default values for the table.

**Comment by dupuchba** [comment]
Do you any other use case other than center a cell ?

**Comment by tomzx** [comment]
This issue is a generalization of #13368. The main objective is to have as much flexibility and features as an HTML table would provide us with.

At one point I considered that the solution to the table problem would be to have php generate an html table which would then be given to the `Table` helper, which in turn, would convert it to something that can be rendered in a console.

Thus the main points of interest are:

* Background/foreground coloring
* Alignment
* Cell merging
* Border styling

**Comment by aitboudad** [comment]
@tomzx in #13438, I used TableCell where we can can specify data for cell,
so I think this is an easy task and I see 2 ways to fix this:

1- Introduce a new TableCellStyle:
```php
$table->addRow([new TableCell("data", ['style' => new TableStyleCell()]), 'data']);
```
2- add  more option in table TableStyleCell:
```php
$cellOption = [
    'rowspan' => 1,
    'colspan' => 2,
   'format' => '%s',
   'align'    => 'left',
];
$table->addRow([new TableCell("data", $cellOption), 'data']);
```

@fabpot what would be your preferred way ?

**Comment by aik099** [comment]
I also recently had a need to have odd/even table row colors or a way to individually color a row/cell. So :+1: for this.

**Comment by freezy-sk** [comment]
:+1:

**Comment by regniblod** [comment]
I also recently had a need to add background color to some cells depending on the context. So 👍 for this.

Is there any update?

**Comment by fabpot** [comment]
I think someone needs to implement it and submit a pull request. Sounds like an interesting feature to me.

**Comment by andrewtch** [comment]
@fabpot , is it still needed?

**Comment by fabpot** [comment]
I think so :)

**Comment by andrewtch** [comment]
So what would you prefer? TableCellStyle / options array as stated above or some:

```
$table->setFormatterCallback(function ($col, $row, $value, $options) {
    $options['format'] = $col == 0 ? '<error>%s</error>' : '<info>%s</info>';

    return $options;
});
```

**Comment by andrewtch** [comment]
@fabpot ping )

**Comment by wapmorgan** [comment]
+1, Need availability for styling table cells. I'd prefer declarative definition (via array or TableCellStyle).

**Comment by Cosmologist** [comment]
+1
