### ISSUE TITLE
[Config] Race condition and filemtime

### ISSUE THREAD

**Issue by lisachenko** [symfony/symfony#13377]
Hello, Symfony team!

I want to discuss the behaviour of Config component with checking of file modification time. Currently cache is considered as fresh only when the filemtime of cache is **greater** than the filemtime of resource.

However, I noticed that for small applications on nice hardware resource creation time and cache creation time can be within one second, so Config component will think that the cache is stale, but this is wrong. 

I want to propose to add an additional `strictFilemtimeCheck` flag for the constructors of resources which will be true by default. When this flag is false, then the check will be not strict and will include an equal sign. Then, developers will be able to decide what to do when filemtime is equal: consider this as stale/fresh cache.

**Comment by fabpot** [comment]
Changing greater by greater of equal sound like the easiest thing to do without any bad impacts.
