### ISSUE TITLE
[2.6] FlattenException

### ISSUE THREAD

**Issue by baptistedonaux** [symfony/symfony#13381]
I run my app with Symfony 2.6. Whin I have a exception, this message is thrown.
```
PHP Fatal error:  Cannot redeclare class Symfony\Component\Debug\Exception\FlattenException in /home/baptiste/Project/pole-gestion.fr/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php on line 25
```

I think that it's linked at the inclusion of FlattenException into Symfony\Component\HttpKernel\Exception\FlattenException which is deprecated.

**Comment by stof** [comment]
which version of HttpKernel are you using ?

**Comment by Tobion** [comment]
Ref #13372

**Comment by chubidu** [comment]
In case i'm not missing something: looking at [FlattenException](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Debug/Exception/FlattenException.php#L254-L284), the class seems defined twice since commit [1d68ad...](https://github.com/symfony/symfony/commit/1d68ad326548b7f8fd991cdbb126961cd26310be) (Branch 2.6)

**Comment by nicolas-grekas** [comment]
@chubidu 1d68ad did not duplicate it but moved it around. The pb can occurs if you update the Debug component but not the HttmKernel, thus @stof 's question. Which version of the Debug+HttpKernel do you have @baptistedonaux ? Can you please look at your composer.lock file?

**Comment by baptistedonaux** [comment]
I'm using Symfony 2.6.3. 
I don't arrive to identified the real version used.
For debug, it's the same version of Symfony.For HttpKernel it's more complicated. It's ~2.1 | ~2.2 | ~2.2 | v2.6.3.

Sorry for this ******* help.

**Comment by xabbuh** [comment]
@baptistedonaux You can get the actually installed versions by running `composer show -i`.

**Comment by baptistedonaux** [comment]
Thank you, but it's a symfony dependency. It's not display.

**Comment by baptistedonaux** [comment]
@stof @nicolas-grekas Sorry, I shuffle between projects. My app run with Symfony 2.5.

**Comment by sandermarechal** [comment]
I have the same problem, also using Symfony 2.6.3. Grepping the composer.lock it seems that means that symfony/debug and symfony/http-kernel is also 2.6.3.

**Comment by bpec** [comment]
Quick solution 
(if your enviroment currently is not suitable to update)
1. open this file:
..../vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php
2. put the whole second class definition to top

**Comment by baptistedonaux** [comment]
@bpec Temporarily, you can also delete the inheritance.

**Comment by seydu** [comment]
You can require a Specific version. In my case, using Silex, I added
"symfony/http-kernel":     "2.6.1"
in my composer.json.
But if you do so you have to watch for potentiel conflicts or errors that migth pop up, and remember to remove it later on.

**Comment by Glideh** [comment]
I have this error from time to time with Symfony 3.1.0.
I didn't find the origin yet.
