### ISSUE TITLE
[2.2] add out of the box support for refreshUser strategies

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#1338]
while users might want to do other optimizations I think there are 3 main strategies most users will need that imho we should support out of the box

1) fetch on every request
this is what we have today
2) fetch every X requests
3) fetch after Y amount of seconds

See also http://groups.google.com/group/symfony-devs/browse_thread/thread/4eaa8d045227d9e2

**Comment by weaverryan** [comment]
:-1: I think we should fix this in the docs. Simply: the biggest use would be with the EntityUserProvider, and it has too many edge cases

**Comment by weaverryan** [comment]
Closing as this has a -1 vote from 2 core members (Fabien and I). But, i've opened a docs issue - symfony/symfony-docs#5534 as there are some people that seem to be looking for this.
