### ISSUE TITLE
[DX] Use the current user provider for logout_*() functions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#13394]
### The problem

Although they are not commonly used, SecurityBundle provides some useful functions called `logout_path()` and `logout_url()` ([see reference](http://symfony.com/doc/current/reference/twig_reference.html#logout-path)).

In regular Symfony applications I don't use them because I always know exactly the URL or the route name associated with the logout action. However, when developing some code that can be integrated in any Symfony application I can no longer know the logout URL and I must use `logout_*()` functions.

The problem is that these functions, obviously, require the name of the user provider to generate the URL. But again, I cannot know the name of the user provider for the Symfony application which is going to use this software.

### The solution

The current solution seems verbose and a bit weird to me:

```php
<a href="{{ logout_path(app.security.token.providerKey) }}">Close session</a>
```

What do you think about making this argument optional? If you set it, the URL is generated for that provider. If you don't set the argument, the function automatically selects the right provider for the current user:

```php
<a href="{{ logout_path() }}">Close session</a>
```

**Comment by jaytaph** [comment]
@javiereguiluz There currently is already a pull request for exactly this: #13342. The original issue is #12160

**Comment by javiereguiluz** [comment]
@jaytaph my bad! I'm really sorry. Closing as duplicate.

**Comment by jaytaph** [comment]
No worries.. More people requesting this, means that it's a good feature to implement :)
