### ISSUE TITLE
[Security] AbstractVoter returns ACCESS_GRANTED when the vote result is ACCESS_DENIED

### ISSUE THREAD

**Issue by DrBenton** [symfony/symfony#13393]
The current implementation of the AbstractVoter doesn't make a strict check of the result of the underlying Voter result:
```php
// Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php

if ($this->isGranted($attribute, $object, $token->getUser())) {
    // grant access as soon as at least one voter returns a positive response
    return self::ACCESS_GRANTED;
 }
```
(see [here](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L76))

But in PHP, if `-1` is casted to *bool*, it is `true`!
 * Therefore, when the Voter returns ACCESS_ABSTAIN (which value is `0`), this condition is not true and the AbstractVoter returns the correct value. 
 * But when the Voter returns ACCESS_DENIED (which value is -1), the condition is true and the AbstractVoter returns ACCESS_GRANTED.

I can submit a PR with that simple following change, but before that I would like to be sure that this is really a bug, and not a feature -)
```php
// A possible fix:
if (self::ACCESS_GRANTED === $this->isGranted($attribute, $object, $token->getUser())) {
    // grant access as soon as at least one voter returns a positive response
    return self::ACCESS_GRANTED;
}
```

**Comment by jaytaph** [comment]
Only the `vote()` method of an voter should return an `ACCESS_GRANTED`, `ACCESS_DENIED` or `ACCESS_ABSTAIN`. 

The abstract `isGranted()` method you are referring to should return a boolean value. This is also defined in the docblock of the [method](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L110)

**Comment by DrBenton** [comment]
My mistake, sorry! Thank you for your explanation :-)
