### ISSUE TITLE
[ExpressionLanguage] Why not a service ?

### ISSUE THREAD

**Issue by florianv** [symfony/symfony#13404]
I'm wondering why the `ExpressionLanguage` is not a service. 

Currently it is lazily created in the classes needing it, for example [ExpressionValidator](https://github.com/symfony/symfony/blob/43c05650c664f6b164a332237b8da485acb1a995/src/Symfony/Component/Validator/Constraints/ExpressionValidator.php#L106), [UrlMatcher](https://github.com/symfony/symfony/blob/d0d7ae24e4d8ec27ff6992fd51d7d090424942be/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L250). Making it a service would allow to use a `ParserCacheInterface` to cache all expressions which are currently re-parsed at each request.

Now with the added [ExpressionFunctionProviderInterface](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/ExpressionLanguage/ExpressionFunctionProviderInterface.php) wouldn't be better to create a `expression_language.function_provider` tag to register them and use setter injection where the `ExpressionLanguage` is needed ?

**Comment by WouterJ** [comment]
Each component that supports expressions has its own ExpressionLanguage with its own functions.

**Comment by florianv** [comment]
My main concern was not being able to leverage the `ParserCacheInterface` which could be shared by multiple languages.

**Comment by fabpot** [comment]
I haven't checked, but from what I remember, all current expression usages in the core framework are for features that are cached as PHP files, where the expression totally disappears after the first request.

**Comment by stof** [comment]
@fabpot not the security expressions. This one would deserve using the cache
