### ISSUE TITLE
FatalErrorException Deprecation Throwing Errors

### ISSUE THREAD

**Issue by makoa** [symfony/symfony#13416]
The FatalErrorException.php file in Debug/Exception references the old HttpKernel file (and even defines it in the namespace).  When it references the old file, it throws the following error (since it's not defined in the file).  The only way I've found to get it to throw the errors properly and show the symfony debug page is to comment out the "use Symfony\Component\HttpKernel\Exception\FatalErrorException as LegacyFatalErrorException;" line and remove the "extends LegacyFatalErrorException" clause to the definition of FatalErrorException.  Not sure what's supposed to happen but it's not working.

The application I'm building is using Symfony components but relies on most of the component frameworks.

PHP is version 5.4.36.

![screen shot 2015-01-14 at 6 58 28 pm](https://cloud.githubusercontent.com/assets/829745/5751866/5c878a04-9c1f-11e4-896e-098d5f176a7f.png)

Log:
[Thu Jan 15 02:45:23 2015] [error] [client 10.0.2.201] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The autoloader expected class "Symfony\\Component\\HttpKernel\\Exception\\FatalErrorException" to be defined in file "/var/sites/kulasisdev/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/Exception/FatalErrorException.php". The file was found but the class was not in it, the class name or namespace probably has a typo.' in /var/sites/kulasisdev/vendor/symfony/debug/Symfony/Component/Debug/DebugClassLoader.php:186\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')\n#1 /var/sites/kulasisdev/vendor/symfony/debug/Symfony/Component/Debug/Exception/FatalErrorException.php(25): spl_autoload_call('Symfony\\\\Compone...')\n#2 /var/sites/kulasisdev/vendor/symfony/debug/Symfony/Component/Debug/DebugClassLoader.php(151): require('/var/sites/kula...')\n#3 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')\n#4 /var/sites/kulasisdev/vendor/symfony/debug/Symfony/Component in /var/sites/kulasisdev/vendor/symfony/debug/Symfony/Component/Debug/DebugClassLoader.php on line 186, referer: http://kulasisdev.kaaihili.com/login

**Comment by nicolas-grekas** [comment]
This is strange. Can you please revert your changes then swap the definition of both classes? Does it work better?

**Comment by ahilles107** [comment]
i have this same problem after updating vendord today morning

**Comment by nicolas-grekas** [comment]
Could you please try this:

open `vendor/symfony/debug/Symfony/Component/Debug/Exception/FatalErrorException.php`
then swap the two classe declarations in that file (declare Symfony\Component\\**HttpKernel**\Exception\FatalErrorException before Symfony\Component\\**Debug**\Exception\FatalErrorException)

**Comment by ahilles107** [comment]
Fatal error: Maximum function nesting level of '2000' reached, aborting! in /var/www/newscoop/newscoop/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php on line 282

**Comment by ahilles107** [comment]
```
....
1980	0.5939	13145568	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1981	0.5939	13146200	call_user_func_array ( )	../FlattenException.php:282
1982	0.5939	13146704	flattenArgs ( )	../FlattenException.php:282
1983	0.5939	13147056	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1984	0.5939	13147688	call_user_func_array ( )	../FlattenException.php:282
1985	0.5939	13148192	flattenArgs ( )	../FlattenException.php:282
1986	0.5939	13148544	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1987	0.5939	13149176	call_user_func_array ( )	../FlattenException.php:282
1988	0.5939	13149680	flattenArgs ( )	../FlattenException.php:282
1989	0.5939	13150032	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1990	0.5939	13150664	call_user_func_array ( )	../FlattenException.php:282
1991	0.5939	13151168	flattenArgs ( )	../FlattenException.php:282
1992	0.5939	13151520	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1993	0.5939	13152152	call_user_func_array ( )	../FlattenException.php:282
1994	0.5939	13152656	flattenArgs ( )	../FlattenException.php:282
1995	0.5939	13153008	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1996	0.5939	13153640	call_user_func_array ( )	../FlattenException.php:282
1997	0.5939	13154144	flattenArgs ( )	../FlattenException.php:282
1998	0.5939	13154496	Symfony\Component\HttpKernel\Exception\FlattenException->__call( )	../FlattenException.php:0
1999	0.5939	13155128	call_user_func_array ( )	../FlattenException.php:282
```

**Comment by nicolas-grekas** [comment]
Thanks, can you please paste the beginning of the stack trace?
I'm surprised by the line number (282): if you swaped the classes declaration, this call to call_user_func_array should be at the beginning of the file (around line 40)

**Comment by nicolas-grekas** [comment]
Ok and other try sorry! Can you please also swap the classes in FlattenException.php ? (you did it in FatalErrorException.php right?)

**Comment by ahilles107** [comment]
@nicolas-grekas - yes, swaping classes in ```FatalErrorException.php``` and ```FlattenException.php``` solved issue.

**Comment by makoa** [comment]
My issue doesn't include FlattenException so, @nicolas-grekas , what would you like me to do?  I've tried swapping the namespace lines to no avail.  Same error.

**Comment by makoa** [comment]
I made the changes to Symfony\Component\Debug\Exception\FatalErrorException per the debug fix #13420 and left the implementation of FatalErrorException.  It worked.  Not sure if you intended the file to be an empty class implementation.

**Comment by n1c01a5** [comment]
https://github.com/symfony/symfony/issues/13543

Any idea?

**Comment by makoa** [comment]
Don’t know.  I haven’t had any issues since updating the file to match your changes.  Haven’t checked to see if it is merged into earlier tags though.
