### ISSUE TITLE
Alternatives (when command not found) are in wrong order

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#13419]
I would suggest to use an alphabetical sorting.

If you are with me, a PR will follow.

![bildschirmfoto 2015-01-15 um 10 13 03](https://cloud.githubusercontent.com/assets/995707/5754964/742f8f82-9c9f-11e4-85cc-5dc06ba0e938.png)

**Comment by peterrehm** [comment]
I think this would be a good improvement, unsorted is rather difficult to read.

**Comment by malarzm** [comment]
Duplicate of https://github.com/symfony/symfony/issues/10893

**Comment by flip111** [comment]
@OskarStark please review possible implementation in https://github.com/symfony/symfony/issues/10893#issuecomment-71388802

**Comment by OskarStark** [comment]
@flip111 i will have a look soon!
