### ISSUE TITLE
Deprecation errors break templates

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#13413]
[This line](https://github.com/sonata-project/SonataAdminBundle/blob/5626abfbab92c590a8b68f5125f639c2eb75cf98/Resources/views/CRUD/base_edit_form.html.twig#L14) in the SonataAdminBundle:

```jinja
action="{{ admin.generateUrl(url, {'id': admin.id(object), 'uniqid': admin.uniqid, 'subclass': app.request.get('subclass')}) }}" {{ form_enctype(form) }}
```

Creates this cache:

```php
echo $this->env->getExtension('form')->renderer->searchAndRenderBlock((isset($context["form"]) ? $context["form"] : $this->getContext($context, "form")), 'enctype')            trigger_error('The helper form_enctype(form) is deprecated since version 2.3 and will be removed in 3.0. Use form_start(form) instead.', E_USER_DEPRECATED);
```

Which, as we all can see, is not a valid PHP syntax, resulting in:

 > Parse error: syntax error, unexpected 'trigger_error' (T_STRING), expecting ',' or ';' in cmf-sandbox\app\cache\dev\twig\43\6e\9319fdb52820d90de99a64a00c8e7083a846034d0b9b5621fd24ec5ad7a2.php on line 64

**Comment by fabpot** [comment]
This one has been removed a long time ago, you are probably using an old version of Symfony 2.7.

**Comment by WouterJ** [comment]
Hmm, not very long ago iirc. I'll update my vendors and close/comment after it. Thanks for your quick response!

**Comment by fabpot** [comment]
@WouterJ Were you able to check if upgrading fixed the issue?

**Comment by WouterJ** [comment]
To be honest, I limited my composer.json versions to `2.6.*` to avoid the hassle of using 2.7. But I trust you that this is fixed and if it isn't, I'm sure someone else will open an issue soon.
