### ISSUE TITLE
JsonResponse is ignoring charset

### ISSUE THREAD

**Issue by dbpolito** [symfony/symfony#13410]
When we have an JsonResponse, it sets the Content-Type without charset, this happens because of this check:

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Response.php#L288

Is there a reason for not setting charset to application/json responses or this is really a bug? If this is a bug, please let me know what branch i should send a PR for fixing this.

I can confirm this is happening >2.3.

**Comment by stof** [comment]
A JSON response is always UTF-8 anyway (otherwise it is invalid JSON)

and the check you linked is necessary to avoid breaking responses for non-text content types (adding the charset for an image response would be wrong)

**Comment by dbpolito** [comment]
I was thinking something like:

````
} elseif ((0 === stripos($headers->get('Content-Type'), 'text/') || 0 === stripos($headers->get('Content-Type'), 'application/json')) && false === stripos($headers->get('Content-Type'), 'charset')) {
````

And using it at an API of mine, because it's not returning charset, the encoding being in use is: `windows-1252`.

**Comment by stof** [comment]
@dbpolito if you return JSON encoded as windows-1252, clients will not be able to decode it (invalid JSON). And PHP should even complain when encoding it

**Comment by dbpolito** [comment]
That's why i opened this ticket, we should explicit set charset to UTF-8, which is our default charset.

Or we can change here:

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/JsonResponse.php#L170

````php
$this->headers->set('Content-Type', 'application/json; charset=UTF-8');
````

**Comment by stof** [comment]
My point is that ``application/json`` does not need a charset. The JSON specs defines that JSON is encoded in UTF-8. So if your JSON parser tries to use a different charset, it is a broken parser, not a JSON parser.

**Comment by derrabus** [comment]
@dbpolito: Why is it a problem for you that there is no charset defined in the `Content-Type` header?

**Comment by dbpolito** [comment]
Well, i presumed this was the issue, as i did this change and fixed the problem, but the main issue ended to be something else and worked without this change, weird...

Anyway, i think we can close this one, sorry about it.

**Comment by ksimka** [comment]
Hi.

I have the same issue. @stof, I agree that for machines charset is not necessary on application/json, but for humans it is. For example, debugging an api that has responses with cyrillic or other non-latin chars. Without `charset=utf-8` browser will show a mess.

Is it really a problem to let people set charset on their responses?
