### ISSUE TITLE
CommandTester::execute() doesn't accept optional arguments

### ISSUE THREAD

**Issue by aimeos** [symfony/symfony#13415]
Handing over optional argument isn't possible in the first parameter of CommandTester::execute(). Only required arguments are allowed. Otherwise, an exception is thrown.

**Comment by jakzal** [comment]
Could you give an example of a command and a test that doesn't work for you?

**Comment by aimeos** [comment]
The Aimeos web shop bundle contains a "aimeos:setup" command and a test for it (https://github.com/aimeos/aimeos-symfony2/blob/master/Tests/Command/SetupCommandTest.php):

$command = $application->find( 'aimeos:setup' );
$commandTester = new CommandTester( $command );
$commandTester->execute( array( 'command' => $command->getName(), 'site' => 'unittest' ), array( 'option' => 'setup/default/demo:0' ) );

The $commandTester->execute() doesn't add the --option=setup/default/demo:0 to the aimeos:setup command if called like above and if the "'option' => 'setup/default/demo:0'" is part of the first array an exception is thrown because only arguments are allowed and no options.

**Comment by xabbuh** [comment]
`option` is treated as an argument if you don't prefix it with `--`. You should actually call `execute()` like this (you can also have a look at [the cookbook](http://symfony.com/doc/current/cookbook/console/console_command.html#testing-commands)):

```php
$commandTester->execute(array(
    'command' => $command->getName(),
    'site' => 'unittest',
    '--option' => 'setup/default/demo:0',
));
```

**Comment by jakzal** [comment]
All the input (**arguments** and **options**) should be passed as the first argument to the `execute()` method - `$input`:

```php
$commandTester->execute(array(
    'command' => $command->getName(), 
    'site' => 'unittest' , 
    'option' => 'setup/default/demo:0' 
));
```

See the related documentation: http://symfony.com/doc/current/components/console/introduction.html#testing-commands

Second argument of the `execute()` method is not about command options, but execution options (see https://github.com/symfony/Console/blob/master/Tester/CommandTester.php#L45-L49).

```
