### ISSUE TITLE
twig vs php templating

### ISSUE THREAD

**Issue by nimasdj** [symfony/symfony#13422]
Does Symfony have plan to drop php templating in favor if twig templating?

**Comment by fabpot** [comment]
see https://github.com/symfony/symfony/issues/12897

**Comment by nimasdj** [comment]
Thanks.

**Comment by nimasdj** [comment]
Sorry, I don't know if issues are searchable that I search before opening an issue?

**Comment by xabbuh** [comment]
@nimasdj GitHub offers a lot of possibilities to search for issues. You can simply enter a term in the text field above the issue list or [use more advanced filter options](https://help.github.com/articles/searching-issues/).
