### ISSUE TITLE
Debug Component: php_sapi_name check for development server should be 'cli-server'

### ISSUE THREAD

**Issue by JDrew9** [symfony/symfony#13425]
Lines 48 to 54 of Symfony\Component\Debug\Debug currently check for PHP's built-in server like this:
```php
if ('cli' !== php_sapi_name()) {
    ini_set('display_errors', 0);
    ExceptionHandler::register();
} elseif ($displayErrors && (!ini_get('log_errors') || ini_get('error_log'))) {
    // CLI - display errors only if they're not already logged to STDERR
    ini_set('display_errors', 1);
}
```
However, the SAPI name that's returned by the built in server is 'cli-server' not 'cli', so it's not triggering the correct statement group in that situation.

**Comment by fabpot** [comment]
We are not checking for the built-in web server here, but whether we are on the CLI or not.

**Comment by JDrew9** [comment]
Ah, my mistake. Thanks anyway!
