### ISSUE TITLE
[Console] reduce package size

### ISSUE THREAD

**Issue by Flyingmana** [symfony/symfony#13423]
currently the size of the Dist Package is 1.3M big,

```
du -h -d 2
8.0K 	./Console/Logger
20K  	./Console/Event
56K  	./Console/Descriptor
32K  	./Console/Formatter
760K	./Console/Tests
20K  	./Console/Question
144K	./Console/Helper
72K  	./Console/Input
12K  	./Console/Tester
36K  	./Console/Output
20K  	./Console/Resources
32K  	./Console/Command
1.3M	./Console
1.3M	.
```

Is it feasible to exclude the tests for dist packages?

**Comment by TomasVotruba** [comment]
:+1: Good idea, same as [Doctrine has](https://github.com/doctrine/doctrine2/blob/master/.gitattributes).

But I don't know what is Symfony policy for ignoring files on export.

**Comment by fabpot** [comment]
see #6605
