### ISSUE TITLE
Cant post datetime with years before of 2009 or after 2021 inclusive

### ISSUE THREAD

**Issue by lucachaco** [symfony/symfony#13426]
For some really weird reason i get validation failed for this datetime field. It works fine for the 2010-1020 interval. Any other year out of that interval i get validation failed.

Request

url -X POST -d '{"client":10,"tax_rate":10, "date_of_issue":{"date":{"year":2009,"month":3,"day":5},"time":{"hour":3,"minute":3}}, "sales_order_lines":[{"item":4,"quantity":2,"price":2343}],"payments":[{"amount":34,"method":"CASH","notes":"notas largas"}]}' http://api.facturacohete.com/app_dev.php/sales_orders --header "Content-Type:application/json" -v -u xxx:xxx

response:

{"code":400,"message":"Validation Failed","errors":{"children":{"taxRate":[],"dateOfIssue":{"errors":["This value is not valid."],"children":{"date":{"children":{"year":[],"month":[],"day":[]}},"time":{"children":{"hour":[],"minute":[]}}}},"client":[],"salesOrderLines":{"children":[{"children":{"price":[],"quantity":[],"item":[]}}]},"payments":{"children":[{"children":{"amount":[],"method":[],"notes":[]}}]}}}}

This is my form ->

    $builder
        ->add('taxRate')
        ->add('dateOfIssue')
        ->add($builder->create('client', 'text')->addModelTransformer($transformer))
        ->add('salesOrderLines', 'collection', array(
            'type' => new SalesOrderLineType(),
            'allow_add' => true,
            'allow_delete' => true,
            'options' => array(
                'em' => $options['em'],
            )
        ))->add('payments', 'collection', array(
            'type' => new PaymentType(),
            'allow_add' => true,
            'allow_delete' => true
        ));

**Comment by xabbuh** [comment]
see also FriendsOfSymfony/FOSRestBundle#937

**Comment by aitboudad** [comment]
As I know the default value of years is [five years before to five years after the current year](http://symfony.com/doc/current/reference/forms/types/datetime.html#years) when widget option is set to choice.
So you need to change widget option to single_text or updating the default value:

```php
->add('dateOfIssue', null, array(
    'years' => range(2000, date('Y')),
));
```

**Comment by lucachaco** [comment]
You are right @aitboudad. Thank you very much man.
