### ISSUE TITLE
[Security] Setting DefaultAuthenticationFailureHandler options more than once doesn't work

### ISSUE THREAD

**Issue by petert82** [symfony/symfony#13433]
I _think_ there is bug in the DefaultAuthenticationFailureHandler's `setOptions` method which means that if it is called more than once, only the options from the _last_ call will be applied.

For example, given this:

``` php
// Assume $handler is an instance of DefaultAuthenticationFailureHandler
$handler->setOptions(array('foo' => 'bar'));
$handler->setOptions(array('baz' => 'qux'));
```

I would expect this when I call `getOptions`:

``` php
array(
    'failure_path' => null,
    'failure_forward' => false,
    'login_path' => '/login',
    'failure_path_parameter' => '_failure_path',
    'foo' => 'bar',
    'baz' => 'qux',
)
```

But what I would actually get is (note the missing `foo` key):

``` php
array(
    'failure_path' => null,
    'failure_forward' => false,
    'login_path' => '/login',
    'failure_path_parameter' => '_failure_path',
    'baz' => 'qux',
)
```

Since `setOptions` is called by the DefaultAuthenticationFailureHandler constructor, this means that when overriding the `security.authentication.failure_handler` service, any custom options provided as service arguments are lost when `setOptions` is called later.

From a quick glance at the code DefaultAuthenticationSuccessHandler would exhibit the same behaviour.

It seems to me that the `setOptions` method in both of these classes should be doing something more like this, unless the current behaviour is intentional?

``` php
$this->options = array_merge($this->defaultOptions, $this->options, $options);
```

**Comment by jaytaph** [comment]
It seems to be a bug indeed, although i'm not sure if one should need to call `setOptions` manually, as options are passed by the constructor and merged with the default options. 

I think you provide a  good fix that would at least allow the possibility to call setOptions multiple times without destroying existing options.

**Comment by petert82** [comment]
Yeah, it's possibly worth noting that in the actual case we noticed this, we have an overridden `security.authentication.failure_handler` service being passed a custom `options` array into its constructor, and there is a subsequent call to `setOptions` (I think from somewhere in the SecurityBundle) that is resulting in our custom options being erased.

**Comment by jaytaph** [comment]
However... rereading this again.. i think `setOptions()` is ok here,..  I would say that adding additional items should be done with something like `addOptions()`. I don't know if adding additional methods is allowed without BC breaks though.

**Comment by petert82** [comment]
But, even ignoring the issue of setting extra options, with the behaviour as it stands, the options provided to the constructor interact quite strangely with options provided via `setOptions`.

For example, say I construct a `DefaultAuthenticationFailureHandler` with this as its `$options`:

```php
array(
    'login_path' => '/my-login-path',
)
```

And then call `setOptions` with these options:

```php
array(
    'failure_forward' => true,
)
```

I end up with an options array that looks like this:

```php
array(
    'failure_path' => null,
    'failure_forward' => true,
    'login_path' => '/login',
    'failure_path_parameter' => '_failure_path',
)
```

My `login_path` has been replaced with the default value. This seems quite counter-intuitive, to say the least - essentially, as is, I have to get the current options, merge my changes into them and then apply the result of that via `setOptions` if I don't want to accidentally lose a previously set option.

**Comment by xabbuh** [comment]
I am closing here as this is the expected behaviour. DX may be improved by adding a docblock clarifying the behaviour if someone wants to send a PR for that.
