### ISSUE TITLE
Better memory releasing on kernel shutdown

### ISSUE THREAD

**Issue by stof** [symfony/symfony#13448]
currently, shutting down the kernel (between tests generally) is doing several steps:

- running the shutdown logic of each bundle
- removing the container reference from each bundle
- removing the container reference from the kernel

At this point, we consider that the container is meant to be out of scope.

However, as soon as a service is aware of the container, we get a cyclic object graph because of the service reference hold by the container. This means that none of the services will be garbage collected by the refcount.

I suggest adding a ``clear()`` method on the container (and a ``ClearableContainerInterface`` used by the kernel to know whether it can clear the container) which would clear the list of service instances (``$this->services``, ``$this->scopedServices`` and ``$this->scopeStacks``). this would remove the reference hold by the container itself, meaning that most services will then be able to be collected by the refcount (cyclic references inside the service object graph should be rare, given the only way to achieve them is to add a reference at runtime. the container prevents having cyclic service references). And the container itself will then be collected once all container aware services are.

what do you think about that @fabpot and @nicolas-grekas ?

**Comment by stof** [comment]
@nicolas-grekas @fabpot any feedback here ?

**Comment by nicolas-grekas** [comment]
Why not :) Some questions : Are there more use cases than tests ? Is the benefit worth it ? What would be the overhead of doing this ? Where would you call clear() ? What would be the downsides ? Would it be possible/a good idea to unset only the services that were given the container but not the other ?

**Comment by stof** [comment]
@nicolas-grekas production overhead ? none. The shutdown method of the kernel is not called for web requests.
And no, removing only services in which the container was injected would not solve it. We would also need to remove references to any services referencing them to remove circular references (cycles can involve much more than 2 objects). Removing all references is much easier (and faster) than trying to remember where we inject the container.

And for tests, the benefit is worth it IMO. People are reporting regularly that their functional testsuites are leaking.

**Comment by stof** [comment]
@fabpot any feedback on this idea ?

**Comment by gonzalovilaseca** [comment]
@stof I've implemented this clear() method in our quest to solve the memory buildup in Behat. IIRC it didn't made much of a difference in terms of memory release, but I can double check.

**Comment by stof** [comment]
@gonzalovilaseca if your own object graph for services is cyclic, this will indeed not help much, because you will still need to rely on GC rather than refcount. However, in most cases, it should not be cyclic because of the DIC restrictions (it prevents cycles by default). And maybe your issues are coming from other places (make sure you use DoctrineBundle 1.4 for instance as 1.3 does not clear the entity manager on shutdown)

**Comment by gonzalovilaseca** [comment]
@stof I called GC explicitly after clearing the services. As I said I'm going to double check as it might help you.

**Comment by fabpot** [comment]
Looks like a great idea. There is actually one more use case and I did an equivalent patch for it some time ago: being able to use the kernel to respond to n HTTP requests before dying.

**Comment by stof** [comment]
I will implement it after my vacations (so after July 14th)

**Comment by stof** [comment]
Actually, I implemented it before, given it was very easy
