### ISSUE TITLE
symfony 2 profiler bar throws javascript error in IE8

### ISSUE THREAD

**Issue by pjordaan** [symfony/symfony#13447]
In IE8 and 9 the symfony 2 profiler throws a javascript error caused by the ajax requests logged.

IE8 and 9 do not have  have a addEventListener object in XMLHttpRequest, but use attachEvent instead.

For IE8 and 9, in base_js.html.twig instead of ``this.addEventListener("readystatechange", function() {``
it should be ``this.attachEvent("onreadystatechange", function () {``

**Comment by stof** [comment]
Can you send a pull request ?

**Comment by javiereguiluz** [comment]
@pjordaan thanks for reporting this error and for taking the time to open this issue.

As @stof said, the best thing for us would be to have a pull request which we can easily merge on symfony's maintained branches. As you already have made PR to Symfony in the past, I guess you have no problems at all with this process. If not, please tell us and we'll look for other contributor to take over this issue. Thanks!

**Comment by aik099** [comment]
I wonder, why jQuery wasn't used to attach event, which would have solved the problem once and for all.

**Comment by fabpot** [comment]
@aik099 because we are not using jQuery... just plain JavaScript in the Web Profiler.

**Comment by aik099** [comment]
In fact I've found 2 more places, where `addEventListener` is used.

**Comment by aik099** [comment]
@weaverryan , I'd recommend using my fix #13636 instead. Can you please test it for me?

**Comment by pyrech** [comment]
Indeed, I think the changes made in #13636 are more complete than in #13634

**Comment by wvdweij** [comment]
No problem, only in ie8 and lower. Using this in the eventHandler refers to the document object instead of the caller object... So additional code should be written to handle the this context.

**Comment by aik099** [comment]
> No problem, only when using attachEvent, the keyword this in the eventHandler refers to the document object instead of the caller object

I've solved this in https://github.com/aik099/symfony/commit/04f3f43d455ef18201ce82e2c3091930383fe10a
