### ISSUE TITLE
ObjectChoiceList closed for extension?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#13459]
https://github.com/symfony/Form/blob/master/Extension/Core/ChoiceList/ObjectChoiceList.php#L48

Why is this property set to private and not protected? I would like to use this property in my child class. Will access to this property modify the operation of the parent class too much? Not sure were this stands on the open/closed principle.

Thanks for support

**Comment by merk** [comment]
Why cant you call the parent constructor with the property path you require from your inheriting class?

**Comment by flip111** [comment]
I can, wouldn't that just be a workaround though?

**Comment by merk** [comment]
Doesnt seem like a workaround to me.

**Comment by stof** [comment]
@flip111 making everything protected is not about opening for extension. It is about opening for hacking by allowing to access all internal state. Calling the parent constructor is not a hack (avoiding to call a parent constructor could be considered as a hack as it might leave the class in a broken state)

**Comment by flip111** [comment]
@stof in this particular case would it be a hack as well? If so i will close the issue.

**Comment by merk** [comment]
Its an optional argument, if you dont want to provide it you don't have to - as long as you still call the parent constructor.

**Comment by HeahDude** [comment]
The `ObjectChoiceList` class has been deprecated in 2.7 and removed in 3.0. The current `ChoiceListFactory` allow dynamic parameters.

Should be closed as fixed by #14050 imo.

**Comment by jakzal** [comment]
@flip111 I'll close this for now. If you'd like some other property visibility to be changed, please provide a justification (a use case). Thank you.
