### ISSUE TITLE
[Console] Provide a command interface.

### ISSUE THREAD

**Issue by slbmeh** [symfony/symfony#13454]
Rather than stemming from a base class at the root have command implement a command interface.

Scenario I have an installer interface that retrieves metadata relevant to an install command, these installers currently all extend command, the installer command passes it's consumed installers to the application in a run sequence.  I would like to be able to accept installers that have any command implementation without checking that the command is an instanceof installer within each method that requires it be of both types.

**Comment by zebba** [comment]
If you could provide some pseudo-code to understand your use-case would be helpfull.

Currently I would assume defining your commands as a services and tag them seems to be a valid approach but without an actual use-case this might not be a valid option.

**Comment by jakzal** [comment]
I too fail to see a need for an interface here.

**Comment by slbmeh** [comment]
https://gist.github.com/slbmeh/e8452798c7473449c94f

Not providing an interface hinders the option of development extension paths. Yes, it isn't difficult to type check all of the classes and interfaces that are implemented, but it isn't as clean as it should be.

The application I'm currently working on has different drivers for my *Installation Command Consumer* which need to assert that it is the installer type that it handles, but also must assert that it is a command. It doesn't care what kind of command, that's insignificant because it just gets passed to the application.

**Comment by slbmeh** [comment]
Oh, forgot to note. I'm not using symfony standard, just the console component. So I have no DI container to tag services.

**Comment by WouterJ** [comment]
````php
class InstallerConsumingCommand extends Command {
    public function addInstaller(Command $installer) {
        if ($installer instanceof InstallationCommandInterface) {
          throw new \InvalidArgumentException('You need to implement InstallationCommandInterface');
        }
        $this->installers[] = $installer;
    }
}
````

````
abstract class InstallationCommand extends Command
{}

class InstallerConsumingCommand extends Command {
    public function addInstaller(InstallationCommand $installer) {
        $this->installers[] = $installer;
    }
}
````

**Comment by slbmeh** [comment]
That scenario is in the gist. I didn't think suggesting abstraction would have been taken with such criticism. I know how to work around it. My thought was if I'm hitting a wall of multiple inheritance others may as well.
