### ISSUE TITLE
[Security] Authentication providers are not typehinted

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13480]
It seems that authentication providers are added through an array in the [AuthenticationProviderManager](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L45), but are not checked on implementation of the [AuthenticationProviderInterface](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authentication/Provider/AuthenticationProviderInterface.php).

This means that any call to `supports` and `authenticate` might fail. As providers can only be added through the constructor, it's trivial to add a check on the instance and thrown `InvalidArgumentException` if not correct.

**Comment by unkind** [comment]
What does make this case specific? It looks like there are many similar cases without checks. There is [no support](https://wiki.php.net/rfc/arrayof) of `Foo[]` in the type hinting as well for performance purposes.

**Comment by jaytaph** [comment]
I don't think it's a special case per se.. and if this happens on more places, this should be addressed as well.

**Comment by dunglas** [comment]
As @unkind said, what about the performance impact?

**Comment by jaytaph** [comment]
@dunglas I do not see any performance impacts here. The iteration is done in the constructor, which is only done once when requesting the authentication manager service from the container.

**Comment by unkind** [comment]
My point is consistency. For consistency's sake the same check should appear everywhere if this case is not special. So if we talk about performance issues, we should take into account all cases.

**Comment by jaytaph** [comment]
@unkind I guess that makes sense. I could see if I can get a list of where all these checks should happen.

**Comment by jakzal** [comment]
I'm :-1: for this. The method contract is defined in the docblock, and there's no much value in verifying types of a collection as anyone trying to pass anything breaking the contract will quite quickly learn he made a mistake. 

I just feel we're trying to fix something that's not broken.

**Comment by jaytaph** [comment]
@jakzal This implies type-hinted arguments should not be used anymore, as the docblock already provides this information? No attacks, I'm honestly trying to find your rationale for your argument.

I disagree with fixing something that isn't broken. IMO, it IS broken: you can add anything (as long as it's a non-empty array), and the method will assume it's an object of `AuthenticationProviderInterface`. Assume, being the correct keyword here, as nothing is stopping you from adding anything else from PHP's point-of-view.  I'd rather see that Symfony stays in control and throws an exception and decent message to a user, than just letting PHP break. It makes more sense code-wise from the framework-perspective (validating, not assuming correct arguments), and from the developers perspective (notifying them of incorrect data).

I agree with the fact that this is a workaround for the fact that type-hinted arrays are not supported (yet?) in PHP, but as long as this is not happening in PHP, why not do the checks ourselves? There are many "instanceof" checks around in the code already. This would be just another one.

**Comment by unkind** [comment]
@jaytaph I think it isn't worth it to solve this language limitation with this boilerplate code with O(n) complexity. It is a language issue, not Symfony's one.

**Comment by fabpot** [comment]
I understand both point of views really. But as doing it only at one place does not seem to make much sense to me, I err on the side of a won't fix here.

**Comment by jaytaph** [comment]
@fabpot I understand. Would it make sense to see on which places in the Symfony codebase these issues arise as well? I think something could be detected fairly quickly..  If there aren't many of these cases, it might be worthwhile to fix them all in one go?

**Comment by fabpot** [comment]
@jaytaph Consistency is the key here. If analysing the code proves that we would only add such checks in a couple of places, I would be fine adding them; but if it reveals that there are dozens of occurrences, I would not change anything.

**Comment by jaytaph** [comment]
I haven't looked yet, but i just stumbled across a precedent:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/FormRegistry.php#L57

**Comment by unkind** [comment]
You can find them with `@param\s*[A-Z]\S+\[\]`.
