### ISSUE TITLE
Twig Dump big data ends in max execution timeout

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#13486]
sometimes I get a max_execution_timeout when I dump() big data in twig.

**Comment by WouterJ** [comment]
Can you maybe show us how you did it? (e.g. which code, what do you pass to dump?)

**Comment by alexander-schranz** [comment]
just `{{ dump(app) }}` should reproduce the issue

**Comment by stof** [comment]
what is dump here: the function from the Twig_Extension_Debug in Twig core, or the function from the Symfony 2.6+ VarDumper component ?
and if it is the first case, are you used the XDebug-powered ``var_dump`` or the dumb PHP builtin implementation ?

**Comment by alexander-schranz** [comment]
The Twig core without xDebug. On another system where i tried i did not get an max execution timeout but an allowed memory size exhausted error.

**Comment by stof** [comment]
@alexander-schranz the Twig core is using ``var_dump`` internally for the ``dump()`` function. Without the special XDebug implementation, ``var_dump`` can indeed produce crazy behavior. For instance, if your object graph or your array contains a circular reference, dumping it will produce an infinite loop. This is exactly why XDebug overwrites the function with its own implementation which includes safeguards.

**Comment by alexander-schranz** [comment]
so this is a problem with the php var_dump not only for twig?
then the issue can be closed.

**Comment by fabpot** [comment]
Sure, Twig only provides a wrapper on top of standard PHP functions.
