### ISSUE TITLE
[DI] symfony/expression-language should be required in composer.json not only in dev?

### ISSUE THREAD

**Issue by fduch** [symfony/symfony#13484]
Nowadays i have an issue with unit-testing of my own component that depends on symfony/dependency-injection package.

Suppose i set symfony/dependency-injection as a `require-dev` dependency in composer.json of my library (let's name it packageA) and i have some setUp method inside phpunit test class just like this:
```php
protected function setUp()
{
    $this->container = $this->getMock('Symfony\Component\DependencyInjection\ContainerBuilder');
}
```
Given symfony/expression-language is defined as require-dev dependency of symfony/dependency-injection it will not be installed during executing `composer install` inside the root folder of packageA.
Besides ContainerBuilder's `addExpressionLanguageProvider` method requires `ExpressionFunctionProviderInterface` (which is the part of symfony/expression-language) prior to it's signature.
Hence attempt to generate the mock for ContainerBuilder will raise an error like this:
`Declaration of Mock_ContainerBuilder_78c0a5e1::addExpressionLanguageProvider() should be compatible with Symfony\Component\DependencyInjection\ContainerBuilder::addExpressionLanguageProvider(Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface $provider)`.
(Since mock class inherits method signatures from the original class it's object can not be instantiated because ExpressionFunctionProviderInterface could not be found).

This use case is in fact the only example of that expression-language package is needed not only for developing of dependency-injection (which is the the one require-dev was created for).
So why dependency-injection's dependencies (including symfony/expression-language) are defined as `require-dev` deps despite this packages are needed not only for developing purposes of dependency-injection package?

**Comment by Tobion** [comment]
Same as in #12828 it's an optional dependecy.

**Comment by stof** [comment]
This exception is actually just because PHPUnit_MockObject is crappy and is not able to mock methods typehinting undefined classes (which is perfectly valid in PHP, as long as you don't need to call the method, in which case you will probably need the class to exist to be able to build the argument). This issue is not impossible to fix: both Prophecy and Mockery support mocking the ContainerBuilder properly because they don't suffer this limitation. However, I doubt PHPUnit will implement this in their mocking library given that PHPUnit 4.5 (scheduled to be released in 2 weeks) has a builtin integration of Prophecy.

**Comment by fduch** [comment]
Thank you guys for explanation.
But i have still one question more. Since expression-language is soft dependency and it involves only additional functionality for di package why it doesn't represent in dependency-injection's composer.json `suggest` section?

**Comment by fabpot** [comment]
@fduch My take on the `suggest` section of `composer.json` is that it is useless. If it were just for me, I would remove all such sections in Symfony :)

**Comment by fduch** [comment]
@fabpot previously i was a little bit confused with some aspects of usage of `suggest` and partially `require-dev` in Symfony. Now (since I've read your current post) this thing is much clear for me :)
