### ISSUE TITLE
Translator: Show fallback if found string is empty

### ISSUE THREAD

**Issue by hansnilsson** [symfony/symfony#13483]
When using gettext, if the translation is empty, the original string is used. With Translator, the empty string is used, which makes the UI have gaps in it.

**Comment by stof** [comment]
The translator is using the translation id when it does not have a translation for it: https://github.com/symfony/symfony/blob/3d174a4058c5252c9a0a4cc561546069362ad5a9/src/Symfony/Component/Translation/MessageCatalogue.php#L131 So the behavior you describe here is really weird

**Comment by hansnilsson** [comment]
The code checks for isset, which by default all strings are in .po files, even the un-translated ones. 

For example:

`messages.es_ES.po`:
```
msgid "Reports"
msgstr ""
```

With this translation file, the returned string will be empty, not the original source.

**Comment by hansnilsson** [comment]
Adding an `!empty()`check makes it behave like I expect it to.
`if (isset($this->messages[$domain][$id]) && !empty($this->messages[$domain][$id])) {`

**Comment by stof** [comment]
Well, why do you keep empty strings in the .po files ? As far as Symfony is concerned, an empty string is a valid value. the absence of value is ``null`` (or not having the key at all).

**Comment by hansnilsson** [comment]
Sure we could remove the strings that are not translated directly, but for
me the expected behavior was for it to behave like gettext does.

onsdag 21 januari 2015 skrev Christophe Coevoet <notifications@github.com>:

**Comment by fabpot** [comment]
I tend to agree with @hansnilsson that the behavior would be better if we were ignoring empty translations. Who would want to translate something as an empty string anyway?

**Comment by Triiistan** [comment]
Although it does not look like a very good idea in practice, I have seen people use empty translations in projects to have more/less content for different languages and to specifically avoid translation fallback.

**Comment by hansnilsson** [comment]
@Triiistan Yeah, that is a positive side effect of this behaviour.

FWIW: I've added a pull request here: https://github.com/symfony/symfony/pull/13494 and some more discussion.

**Comment by Tobion** [comment]
Closing as the corresponding PR was also closed.
