### ISSUE TITLE
Form configuration inherited then merged back with parent ??

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#13490]
I have
`FirstType extends ChoiceType`
`getParent()` of `FirstType ` = `choice`

`SecondType extends FirstType`
`getParent()` of `SecondType ` = `first`

Because i want to inherit both the object functionality as well as the template (which looks at the `getParent()` return value). I'm using the `ObjectChoiceList` class as i decided my norm data should be the object. However the `ChoiceToValueTransfomer` [which is registered in](https://github.com/symfony/Form/blob/master/Extension/Core/Type/ChoiceType.php#L82) `ChoiceType` is used three times! After being used once [it throws an exception](https://github.com/symfony/Form/blob/master/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L43) on the second try because the input value is no longer a scalar. I don't understand what's going on here because i'm used to the child class being called, and if it doesn't provide the method then the parent class being called. Not the top parent class method being called 3x for every child in the chain.

**Comment by stof** [comment]
@flip111 you should not use PHP inheritance between your type classes when using the form type hierarchy. Extend from AbstractType instead

**Comment by flip111** [comment]
Thanks @stof

**Comment by stof** [comment]
@flip111 The DoctrineType class in the DoctrineBridge is not a form type by itself (it is an abstract class btw)

**Comment by flip111** [comment]
Thanks @stof
