### ISSUE TITLE
[Serializer] Manage php JsonSerializable

### ISSUE THREAD

**Issue by shouze** [symfony/symfony#13496]
As it's a great enhancement from `php 5.4`: http://php.net/manual/en/class.jsonserializable.php should be cool the Serializer component would manage objects that implement this interface. Thoughts?

**Comment by dunglas** [comment]
The ObjectNormalizer (#13257) is a good candidate to implement this feature. However, I cannot see a way yo make it compliant with serialization groups and how to handle deserialization support.

**Comment by hatembr** [comment]
This is an excellent suggestion. In an API for example, every "returnable" object could provides its own Json representation.
I was forced to move away from the Serializer and JMS because they do not recognize classes that implement the JsonSerializable interface.

**Comment by eddiejaoude** [comment]
> I was forced to move away from the Serializer and JMS because they do not recognize classes that implement the JsonSerializable interface

@hatembr what did you use/do instead?

**Comment by hatembr** [comment]
For now, in one of the projects I am working on, I had ti use a simple an basic solution. I had to build my own classes that managed the API responses in JSON format.
Basically, every entity/document that could be returned by the API has to implement an interface which itself extends JsonSerializable and provides the correct resource name and the fields that represent the object, in addition to some extra internal stuff.
Everything is cooked inside JsonSerialize which is pretty straightforward, all it does is it returns an array with exact and needed fields. No extra processing is required, no annotations to read etc.
The rest of the work is done by the classes that build up the response and which assemble the different objects to be returned. At the end, every object is then converted to the Json representation it provided, natively.
I can't say where this stands performance-wise, compared to the old annotation-based way, though.
The project I am working on is still at its very beginning, the code and classes are still subject to big changes, but I think I will stick with this approach, it is a nice experiment.

**Comment by boekkooi** [comment]
Why not implement a normalizer for this? Something like https://gist.github.com/boekkooi/5a7d59981739fa0ea5f0

**Comment by dunglas** [comment]
Yes it can be done that way. Groups can even be supported (iterate over the resulting array and remove keys not in applicable groups).

Do you want to work on a PR?

**Comment by boekkooi** [comment]
I wish I had the time to work on this but I'm sorry to say that I really don't have the time.
I just had this code so I wanted to point out a way to do this.
