### ISSUE TITLE
[PropertyAccess] Boolean properties accessor looks for setIsXXX instead of setXXX

### ISSUE THREAD

**Issue by ninsuo** [symfony/symfony#13493]
From SensioLabs Insight, we have the following rule:

> Boolean property accessor should not be setIsXXX nor getIsXXX but setXXX and isXXX.

But if I replace `setIsMain` by `setMain`, I get the following exception:

> [NoSuchPropertyException] Neither the property "isMain" nor one of the methods "addIsMain()"/"removeIsMain()", "setIsMain()", "isMain()", "__set()" or "__call()" exist and have public access in class "Fuz\AppBundle\Entity\FiddleTemplate".

I'm using:

```php
    protected $isMain = true;

    public function setMain($isMain)
    {
        $this->isMain = $isMain;
        return $this;
    }

    public function isMain()
    {
        return $this->isMain;
    }
```

**Comment by ogizanagi** [comment]
Your property's name should rather be `main` than `isMain`.
Then you shouldn't have any issue anymore with the mutators.

**Comment by ninsuo** [comment]
Well this makes lots of sense.

Thanks @ogizanagi
