### ISSUE TITLE
[DX][WebProfilerToolbar] Show number of Exceptions in search results

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#13497]
The Profiler search is a really great way to localize a specific request. Quite often I find myself searching through multiple results to find the request that triggered the Exception I've been looking for.

Proposal: _add the number of Exceptions as also shown in the menu in the search result table._

**Comment by elementaire** [comment]
Does the pull request https://github.com/symfony/symfony/pull/13034 cover your need ?

**Comment by Rvanlaak** [comment]
Probably it is when an extra field is added to the search form. For now I don't know exactly or the http statuscode does match with the Exceptions, so will have to test this to be sure about it.

**Comment by fabpot** [comment]
Closing as an exception should lead to a non-200 HTTP status code.
