### ISSUE TITLE
[Validator] drop grapheme_strlen as default option

### ISSUE THREAD

**Issue by masakielastic** [symfony/symfony#13491]
`grapheme_strlen` standalone is not suitable for the purpose of security since there is no restriction of the byte size of one grapheme cluster.

```php
// U+0061 U+00E5
$str = "a".str_repeat("\xCC\x8A", 100000);
var_dump(
    1 === grapheme_strlen($str),
    1 === preg_match_all('/\X/u', $str)
);
```

A lot of combining characters can be also used for visual [mischief](http://stackoverflow.com/questions/11978912/how-to-protect-against-diacritics-aka-unicode-combining-characters-zalgo). When using `grapheme_strlen` for validation, the byte size of string or the number of code points should be validated together.

Intl module provide `grapheme_extract` for truncating string based on byte size or the number of code points without destroying grapheme clusters.

```php
$str = "a\xCC\x8A"."bcde";
var_dump(
    "a\xCC\x8A"."b" === grapheme_extract($str, 4, GRAPHEME_EXTR_MAXBYTES),
    "a\xCC\x8A" === grapheme_extract($str, 2, GRAPHEME_EXTR_MAXCHARS)
);
```

The example of restricion for the size of one grapheme cluster is 128 bytes or  32 characters based on Stream-Safe Text Format: [UAX15-D3](http://unicode.org/reports/tr15/#Stream_Safe_Text_Format). The examples of huge grapheme cluster are [U+FDFA](http://www.charbase.com/fdfa-unicode-arabic-ligature-sallallahou-alayhe-wasallam) (18 characters) and [HAKṢHMALAWARAYAṀ](http://blogs.msdn.com/b/shawnste/archive/2010/01/25/most-combining-characters-in-a-unicode-glyph-character-whatever.aspx) (9 characters)

**Comment by stof** [comment]
I don't understand what your bug report or proposal is here

**Comment by nicolas-grekas** [comment]
See #13527
