### ISSUE TITLE
[Form] [Validation] When validating, ignore entity fields that are not a part of the form.

### ISSUE THREAD

**Issue by shideon** [symfony/symfony#13498]
When we create a form that's tied to an entity (meaning we pass an entity to createForm()), Form->isValid() should not validate the entire entity. Or there should at least be an option to disable this behavior.

I have my form type and an entity. When there's a direct mapping between the 2 all works well. However, if I add a property to my entity with a constraint, Form->isValid() calls will fail if the field's value doesn't pass. This means the form will validate entity fields that aren't a part of the form.

The only solution I've seen posed is to use validation groups on the entity but this is implying validation rules on my entities that may not be accurate (perhaps my validation constraints on my entity are all the defaults. Requiring me to group constraints for form handling in another layer doesn't seem right). Form validation should validate form fields. If the form wants to work with entity fields, it would ideally only validate the fields that are specified in the form (or be configurable).

**Comment by ogizanagi** [comment]
This will be a huge BC break and does not follow what the `Form` component is intended to do when used with an entity, ***i.e*** transforming user's submitted data into a valid entity. 
Most of the time, an entity can't boil down by each properties taken apart from each others, and need to be validated in its entirety.
As the [book](http://symfony.com/doc/current/book/forms.html#form-validation) states : 
> In the previous section, you learned how a form can be submitted with valid or invalid data. In Symfony, validation is applied to the underlying object (e.g. Task). In other words, **the question isn't whether the "form" is valid, but whether or not the $task object is valid after the form has applied the submitted data to it**. Calling $form->isValid() is a shortcut that asks the $task object whether or not it has valid data.

If you need to do what you are suggesting, without using validation groups on the entity, disable the entire entity validation and add constraints directly on the form itself: 

```php 
class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', 'text', [
            'constraints' => [ 
                new NotBlank(['groups' => ['form_validation_only'] ]) ,
            ] 
        ]);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Task',
            'validation_groups' => ['form_validation_only'],
        ));
    }
}
```

Of course it will mean your validation logic will be tied to your form and might be duplicated with the one attach to your entity. But AFAIU, that's pretty much what you're intending to achieve.

**Comment by shideon** [comment]
Thank you for the update.

> ...does not follow what the Form component is intended to do when used with an entity, i.e transforming user's submitted / raw data into a valid entity.
...
> In other words, the question isn't whether the "form" is valid, but whether or not the $task object is valid after the form has applied the submitted data to it.

My problem is the implication that the form should be making a valid entity out of form input. Perhaps I want my form's input to give me a partially built entity that I build later and validate on my own. As it is now, I cannot do that unless I do my form/data relationships on my own or I use validation groups. Validation groups are probably fine but something does not feel right when I'm adding validation groups to my *entity* solely for my *form*. There's no other reason for me to add the group.

IMHO, my form should be validating user input. The form should be validating itself. If there is some functionality that validates a form against the entity it relates with, that's fine but it should be related only to the fields of the form or I should be able to change that behavior. The form fields **are** the validation group.

> This will be a huge BC break (if set as the default behavior)

Maybe an addition could keep BC but I need to dig in. A simple way to either disable the form's entity validation or decide which entity fields to validate *at the form level* would be ideal.

> Of course it will mean your validation logic will be tied to your form and might be duplicated with the one attach to your entity. But AFAIU, that's pretty much what you're intending to achieve.

My issue for this particular case is that an unrelated entity constraint is failing on my Form->isValid() call which I don't want. Pretty sure validation groups are the way forward for this case but I thought I'd bring this up.

**Comment by ogizanagi** [comment]
I understand your point. But how is the `form` component supposed to achieve that ? (*i.e* only validating its fields).
Maybe using the [`validateProperty` method](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Validator/Validator/ContextualValidatorInterface.php#L65) for each entity fields present in the form, here in the [FormValidator](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L54), if a new option (`partial` or whatever) is set to true in a form tied to an entity.

BTW, I do not think this is possible using the 2.4 form API (as far as I see, we're unable to use the `validateProperty` method from the old [ExecutionContext](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Validator/ExecutionContext.php). 
As this would be a new feature, I don't know if it does matter.

**Comment by shideon** [comment]
I'll try to hop on over the wknd and take a look. I haven't looked at Form or Validation components much.

**Comment by shideon** [comment]
So for now I ended up doing what I usually have to when working with an entity in the form. I just manually handle the data for the form type by passing my entity into it then setting 'data' for each field from this entity. This solution is fine. Just wish Symfony kept the form/entity a little less coupled so that we can pass the entity to createForm() and have things just work.

I'll look into Form and Validation when I have time but I'd imagine this is something that can be addressed in v3, not 2 since BC isn't an issue.

**Comment by ogizanagi** [comment]
I'll might work on it too this week end. Working 10minutes on it yet, it was kind of trivial to reproduce the desired behavior for a root entity form and form API > 2.4, introducing a new `partial_validation` form option. But the real problem will be dealing with embedded entity forms.

I think it will be totally targetable to the 2.7 branch, as a new feature, as long as the default behavior is kept, with the `partial_validation` set to false by default.
However, Im' not sure about the community and deciders opinion about such a feature, as I'm not really convinced that will be a legitimate usage of the `form` component...

**Comment by shideon** [comment]
Relevant. http://stackoverflow.com/questions/19793767/does-symfony-2-support-partial-form-binding

I didn't see the 2nd param to submit()

**Comment by ogizanagi** [comment]
This will only remove unsubmitted (not present in the request) forms fields, avoiding to erase original entity data, but you will deal with the same issues about validation of the whole object.

**Comment by shideon** [comment]
Right.

I think the easiest solution would be to allow a flag (somewhere... haven't looked yet) to disable entity validation in the form.

**Comment by stof** [comment]
@shideon validation groups are precisely meant for this use case. The form will then be responsible to transform the user-submitted into a valid entity according to the ``step1`` rules. What these rules are is the job of the validator.

Disabling the validation entirely is not possible currently. However, you can achieve a similar behavior by setting it to use a validation group which does not have any constraint defined

**Comment by shideon** [comment]
Hey @stof, I've thought more on it and I agree.

The reason I felt slightly uncomfortable about validation groups was because it felt odd defining those groups in my entity for something external/unrelated. But after thinking, I realized the only reason it felt like that was because I was thinking of the validation groups as being defined in the entity **via annotations** for something unrelated to the entity. But when I think of the general/abstract idea of validation groups (no matter how they're defined), you are right and they solve the problem just fine. So... it's a non issue.

Thanks for all the work!

**Comment by shideon** [comment]
And regardless, defining them in the entity isn't that bad. I think I was originally turned off to the idea that a form should **always** make a valid entity. But, as you said, I can work around this.
