### ISSUE TITLE
trouble after update

### ISSUE THREAD

**Issue by yahou-serious** [symfony/symfony#13507]
Hi,
I updated vendors (Symfony 2.6.0 => 2.6.3)
After that, i have this error : 
```
Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InactiveScopeException' with message 'You cannot create a service ("request") of an inactive scope ("request")
```
Here is my class: 
```
namespace App\CoreBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class CustomCompilerPass implements CompilerPassInterface
{

    public function process(ContainerBuilder $container)
    {
        $connection_service = 'doctrine.dbal.default_connection';

        if ($container->hasDefinition($connection_service)) {

            $def = $container->getDefinition($connection_service);

            $args = $def->getArguments();
            $args[0]['driverClass'] = 'App\CoreBundle\Driver\DynamicConnectionDriver';
            $args[0]['driverOptions'][] = array(new Reference('service_container'));

            $def->replaceArgument(0, $args[0]);
        }
    }

}
```
DynamicConnectionDriver class:
```
namespace App\CoreBundle\Driver;

use Doctrine\DBAL\Driver\PDOMySql\Driver;

class DynamicConnectionDriver extends Driver
{

    public function connect(array $params, $username = null, $password = null, array $driverOptions = array())
    {
        $container = $driverOptions[0][0]->get('service_container');

        $request = $container->get('request');

        if ($request->getHost() != $container->getParameter('manager.host')) {
            $params['dbname'] = $container->get('app_core.core')->getDbName();

            return parent::connect($params, $username, $password, array());
        }

    }

}
```
the error come from "$request = $container->get('request');"

Thanks !

**Comment by cordoval** [comment]
does this happen in cli and on the browser both? also passing the container as a driver option seems very wrong, would you try the request_stack rather, but definitely the error says it all no?

**Comment by yahou-serious** [comment]
It happen in both cases. I don't know request_stack. I'll search elements on request_stack. Thanks

**Comment by jakzal** [comment]
The issue seems to be similar to #12278 and https://github.com/doctrine/DoctrineBundle/issues/351, but I failed to reproduce it locally. I've used your compailer pass and dynamic connection classes. Please fork symfony standard edition and re-create your issue on a new branch.

P.S. You shouldn't use the request scope anymore (see http://symfony.com/blog/new-in-symfony-2-4-the-request-stack).

P.S. 2 It's probably a bad idea to rely on a Request in your DB connection. You definitely shouldn't rely on request being available and handle situations when it's not.

**Comment by yahou-serious** [comment]
Thank you!

To explain, I have two connections. A "core" that will get the bdName parameter in the database. And "Default" will be the customer connection. That's why I need the request object.

I have several database. A "core" and the others are customers databases. Names of customer databases are stored in the database "core". That's why I need to get the "host" to find out which customer base to connect.

I am open to suggestions to better manage the multitenancy.

**Comment by jakzal** [comment]
@yahou-serious shall you reproduce your problem on a fork of standard edition? I'm after a minimum amount of code reproducing your problem.

**Comment by yahou-serious** [comment]
Yes, i'll do it.. Thanks
