### ISSUE TITLE
[HttpFoundation] Host value retrieved from X-Forwarded-Host header despite no trusted proxy

### ISSUE THREAD

**Issue by fideloper** [symfony/symfony#13514]
## Synopsis

Two issues, both related.

### Primary Issue:

Within `Symfony\Component\HttpFoundation\Request`, the Host value is retrieved from the `X-Forwarded-Host` header despite having no Trusted Proxy set.

### Secondary ("downstream") Issue
This has a downstream affect of also affecting the `getPort()` function. If no trusted proxy is set, it falls back to checking against the Host. If the host is found, it checks for a port and, finding none, falls back to either port 80 or 443.

In the above scenario, the host is found if `X-Forwarded-Host` is set despite no trusted proxy being used, as described. Therefore the Port is always going to be returned 80 or 443, and never the SERVER_PORT for X_FORWARDED_PORT values.

## Relevant Code

This is relevant code from `Symfony\Component\HttpFoundation\Request`.

Getting the Host:
```php
public function getHost()
    {
        if (self::$trustedProxies && self::$trustedHeaders[self::HEADER_CLIENT_HOST] && $host = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_HOST])) {
            $elements = explode(',', $host);

            $host = $elements[count($elements) - 1];
        } elseif (!$host = $this->headers->get('HOST')) {
            if (!$host = $this->server->get('SERVER_NAME')) {
                $host = $this->server->get('SERVER_ADDR', '');
            }
        }

        // trim and remove port number from host
        // host is lowercase as per RFC 952/2181
        $host = strtolower(preg_replace('/:\d+$/', '', trim($host)));

/* Rest of method is omitted */
```

The offending code here is in the `elseif conditional: `$host = $this->headers->get('HOST')`, which set's the $host value to the "trusted header" X_FORWARDED_HOST, effectively by-passes the use (or disuse, in this case) of trusted proxy settings.

**This may be the main bug**. The HeaderBag  object somehow ignore HTTP_HOST and uses X_FORWARDED_HOST, so `$this->headers->get('HOST')` returns the incorrect (since no trusted proxy is set) host value. See my tests below.

At this point in execution, there is no trusted proxy set (I haven't set one - again, see tests below) and so both the primary condition and the secondary `elseif` fail, so code execution jumps down to the `strtolower` call. 

However the code at `$host = strtolower(...)` depends on the `$host` variable being set, which it is in the `elseif` condition. **Overall, the host is getting set to the X_FORWARDED_HOST value despite no trusted proxy being used.**

Getting the port:

```php
public function getPort()
    {
        if (self::$trustedProxies) {
            // Code execution doesn't reach here, no trusted proxy set
        }

        if ($host = $this->headers->get('HOST')) {
            if ($host[0] === '[') {
                $pos = strpos($host, ':', strrpos($host, ']'));
            } else {
                $pos = strrpos($host, ':');
            }

            if (false !== $pos) {
                return intval(substr($host, $pos + 1));
            }

            return 'https' === $this->getScheme() ? 443 : 80;
        }

        return $this->server->get('SERVER_PORT');
    }
```

* Trusted proxied aren't set, so `X_FORWARDED_PORT` is never checked.
* $host value DOES make that condition pass, as it gets the X_FORWARDED_HOST value, as described above
* Porn returned therefore will also be, incorrectly in these conditions, either 443 or 80

## Tests

The following PHPUnit test code found there issues:

```php
<?php

use Illuminate\Http\Request;

class TrustedProxyTest extends PHPUnit_Framework_TestCase {

    public function test_request_does_not_trust()
    {
        $req = $this->createProxiedRequest();

        $this->assertEquals('127.0.0.1', $req->getClientIp(), 'Assert untrusted proxy x-forwarded-for header not used');
        $this->assertEquals('http', $req->getScheme(), 'Assert untrusted proxy x-forwarded-proto header not used');

        // Possible Symfony bug resulting in failure of these tests:
        //$this->assertEquals('lb.internal.net', $req->getHost(), 'Assert untrusted proxy x-forwarded-host header not used');
        //$this->assertEquals(8888, $req->getPort(), 'Assert untrusted proxy x-forwarded-port header not used');

        /*
         * getHost() retrieves host from X_FORWARDED_HOST despite TrustedProxy settings. Unsure if this is intentional.
         * getPort() relies on this, as $host variable is retrieved successfully when X_FORWARDED_HOST exists, again
         *           despite having no Trusted Proxies set. The HOST is retrieved, but with no port set, it falls back
         *           to port 80 or 443, so in this test, "80" is returned. (It's not returning X-Forwarded-Port value,
         *           however, so it has that going for it. Port DOES rely on trusted proxies correctly).
         *
         * The bug is likely in how $host is set in getHost() method.
         */
    }

    protected function createProxiedRequest($serverOverRides=[])
    {
        // Add some X-Forwarded headers and over-ride
        // defaults, simulating a request made over a proxy
        $serverOverRides = array_replace([
            'X_FORWARDED_FOR' => '173.174.200.38',         // X-Forwarded-For   -- getClientIp()
            'X_FORWARDED_HOST' => 'serversforhackers.com', // X-Forwarded-Host  -- getHosts()
            'X_FORWARDED_PORT' => '443',                   // X-Forwarded-Port  -- getPort()
            'X_FORWARDED_PROTO' => 'https',                // X-Forwarded-Proto -- getScheme() / isSecure()
            'SERVER_PORT' => 8888,
            'HTTP_HOST' => 'lb.internal.net',
            'REMOTE_ADDR' => '127.0.0.1',
        ], $serverOverRides);

        // Create a fake request made over "http"
        $request = Request::create('http://serversforhackers.com/tag/proxy','GET',[],[],[],$serverOverRides,null);

        return $request;
    }
}
```

## My Questions

I'm making an issue before a PR because  want to make sure others with knowledge of HTTP and Symfony can prove or deny my understanding of getting the HOST value and it's adherence to Trusted Proxies. Right now it ignores them, in a way that feels like a bug, but might instead be clever code.

* Should the Host value be ignoring trusted proxies?
* Am I correct in that the Port value is therefore incorrectly set?

Let me know if I can clarify any of this!

**Comment by merk** [comment]
The conditional in getHost() that you're talking about has 3 conditions and the 3rd that you're talking about does not get evaluated unless the first 2 evaluate to true.

`$host = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_HOST])` never runs unless `trustedProxies` and `trustedHeaders` are set as appropriate.

Have you set a breakpoint to confirm that it is in fact this code that is causing your problem?

**Comment by fideloper** [comment]
That's correct, noticed that and updated accordingly in last few minutes. Note that this still has the issue. The `elseif` condition is setting the $host value, which is getting it from the `HeaderBag`,which at this point has the `HOST` set to the value of `X_FORWARDED_HOST` value, which is the base issue it seems.

Thanks for the fast response!

**Comment by merk** [comment]
I dont see how this code can possibly do what you're describing: 

* If trustedProxies is set, tries to find a trustedHeader for X_FORWARDED_FOR, and if set, uses that
* If not found, uses the HOST header
* If not found, uses the SERVER_NAME
* Else use the SERVER_ADDR

Related tests:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Tests/RequestTest.php#L733-739
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Tests/RequestTest.php#L1470-1536

My suggestion would be to use xdebug and breakpoints to look at why your code is behaving badly. Could it be that you've configured trustedProxies in another test and not reset them?

**Comment by merk** [comment]
Specifically, look at what goes on inside Request::create() in your test - make sure everything follows logically and submit a failing test case for Request if there is indeed a problem.

**Comment by fideloper** [comment]
Looks like using $uri "http://serversforhackers.com" over-rode the HTTP_HOST and thinking about it now, that makes sense because it wouldn't be accurate portrayer of the HTTP request received when behind a proxy.

Creating my rest request like this: `$request = Request::create('http://localhost:8888/tag/proxy','GET',[],[],[],$serverOverRides,null);` generated fully passing tests, so it's one of expecting HTTP to come in in a way which makes sense - which of course is totally reasonable!

Thanks for pointing these out to me, really appreciate your time!

**Comment by fideloper** [comment]
@merk - 

Last note, on your items here:

* If trustedProxies is set, tries to find a trustedHeader for X_FORWARDED_FOR, and if set, uses that
* If not found, uses the HOST header
* If not found, uses the SERVER_NAME
* Else use the SERVER_ADDR

The HOST ends up being set by the $uri inside of the `Request::Create` method:

```php
        $components = parse_url($uri);
        if (isset($components['host'])) {
            $server['SERVER_NAME'] = $components['host'];
            $server['HTTP_HOST'] = $components['host'];
        }
```

This ends up getting passed to `ServerBag`, which ends up returning an array of headers to be eventually consumed by `HeaderBag`. 

(This all makes sense according to the HTTP spec on getting the host, just an interesting sidenote if you're interested).

Thanks
