### ISSUE TITLE
Potential bug in DoctrineBridge EntityChoiceList

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#13529]
When using the `EntityType` on an entity that has more than one identifier field then it can happen that another entity is used as the one the user selected. In other words:

1. Server fetches a list of entities and maps those to HTML values
2. User A takes his time to fill in the form
3. User B inserts new entity
4. User A submits form, value now maps to another entity

https://github.com/symfony/DoctrineBridge/blob/master/Form/ChoiceList/EntityChoiceList.php#L406
`idAsValue` is not `true` because https://github.com/symfony/DoctrineBridge/blob/master/Form/ChoiceList/EntityChoiceList.php#L113

https://github.com/symfony/Form/blob/master/Extension/Core/ChoiceList/ObjectChoiceList.php#L244
`valuePath` does not evaluate to `true` because of 5th argument in https://github.com/symfony/DoctrineBridge/blob/master/Form/ChoiceList/EntityChoiceList.php#L128

Reverts to default behaviour that will enumerate the choices in the order they were given https://github.com/symfony/Form/blob/master/Extension/Core/ChoiceList/ChoiceList.php#L410-L424

Please note that i did NOT run into this bug, i have not tested this. I just read the code. But i wanted to post anyway to anyone who concerns it.

**Comment by kix** [comment]
@flip111, it would be great if you could supply a failing test case in a pull request :)

**Comment by jakzal** [comment]
This is not really something we can prevent.

**Comment by flip111** [comment]
@jakzal well there is an identifier available, given it consist out of multiple fields. But at least it means that the Entity has it's own Identity. One would have to store all fields beloging to the entity, then use a query with this data to get the field from database again. If you say it's not possible, perhaps it's better to not support this behaviour at all. I can see people pulling hairs for something that should *just work*.
