### ISSUE TITLE
Setting external parameters in Elastic Beanstalk

### ISSUE THREAD

**Issue by Looted** [symfony/symfony#13526]
I'm trying to use external parameters in AWS Elastic Beanstalk. I set the container parameters and they are visible via ssh both in shell and vhost config. When composer install runs however (during deployment) I get:

     [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                  
     You have requested a non-existent parameter "compass.bin".

Of course when I hardcode compass bin, another external var comes up with an error. This doesn't happen on the local machine. Any ideas what could be the cause?

**Comment by jakzal** [comment]
Closing, as this is Beanstalk's environment issue and there's not much we can do it (see the related [SO question](http://stackoverflow.com/questions/28150756/symfony2-environmental-variables?noredirect=1#comment44683286_28150756)).
