### ISSUE TITLE
[Debug] Muted with @ operator E_RECOVERABLE_ERROR missing from logs

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#13523]
Hello Symfony guys!
I have found error in Debug component, the case shown below.

1. Write poor code, which will generates E_RECOVERABLE_ERROR (for example, casting object of class without `__toString` method to string)
2. Place `@` operator before your code
3. `\Symfony\Component\Debug\ErrorHandler::handle` will not handle this error, because it was muted. Muted, in this case, means that `error_reporting()` will return 0 inside handling method.
4. `\Symfony\Component\Debug\ErrorHandler::handle` almost always returns `false`, including this case. So, script is terminating now (without any logging inside `\Symfony\Component\Debug\ErrorHandler::handle` method)
5. Execution comes to `\Symfony\Component\Debug\ErrorHandler::handleFatal`, where we could find check:
```
if (!$error || !$this->level || !($error['type'] & (E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_PARSE))) {
    return;
}
```
Our error has type `E_RECOVERABLE_ERROR`, so, check became positive and execution returns from this method immediatelly. Also, without any logging.

Seems, that it should be fixed by adding `E_RECOVERABLE_ERROR` to check on step 5. What do you think?

**Comment by nicolas-grekas** [comment]
The `handle()` method is deprecated and never used since 2.6 (`handleError()` is used now). The behavior you're describing is now totally different (`E_RECOVERABLE_ERROR`s are always turned to exceptions now). You should update if possible.
