### ISSUE TITLE
[Form][2.6] Placeholder and OptionsResolver

### ISSUE THREAD

**Issue by sebastianblum** [symfony/symfony#13524]
Dear symfony-Team,

I created a demo to reproduce the problem:

https://github.com/sebastianblum/symfony-standard/commit/0e4b1c01ff1befaef01ebfef73cf7b51cc07da7d

in the example, the entity "Inquiry" references one "office" and I want to display a select box with the placeholder label, introduced in symfony 2.6. Before 2.6, it was empty_data.
see http://symfony.com/doc/current/reference/forms/types/entity.html#placeholder

In the controller, it works as expected, see the running unit test here:
https://github.com/sebastianblum/symfony-standard/blob/0e4b1c01ff1befaef01ebfef73cf7b51cc07da7d/src/AppBundle/Tests/Controller/DefaultControllerTest.php

    <?php
    public function testFormWithPlaceholder()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertSame('pleaseselect.label', $crawler->filter('option')->text());

    }

but if I want to test the FormType, I got an error:

There was 1 error:

1) AppBundle\Tests\Form\InquiryTypeTest::testInquiryType
Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "placeholder" does not exist. Known options are: "action", "attr", "auto_initialize", "block_name", "by_reference", "compound", "data", "data_class", "disabled", "empty_data", "error_bubbling", "inherit_data", "label", "label_attr", "label_format", "mapped", "max_length", "method", "pattern", "post_max_size_message", "property_path", "read_only", "required", "translation_domain", "trim", "virtual".

/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php:738
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:109
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:87
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:102
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:109
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:268
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:216
/Users/sebastianblum/Downloads/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:39
/Users/sebastianblum/Downloads/symfony-standard/src/AppBundle/Tests/Form/InquiryTypeTest.php:17

this is my test:
https://github.com/sebastianblum/symfony-standard/blob/0e4b1c01ff1befaef01ebfef73cf7b51cc07da7d/src/AppBundle/Tests/Form/InquiryTypeTest.php

    <?php
    class InquiryTypeTest extends TypeTestCase
    {
        public function testInquiryType()
        {
            $inquiryType = new InquiryType();

            $form = $this->factory->create($inquiryType, new Inquiry());
            $this->assertTrue($form->isSynchronized());

            $view = $form->createView();
            $children = $view->children;

            $this->assertSame(array_keys($children), array('name', 'office'));
        }
    }

I'm not sure, if this is a bug or my FormTypeTest is wrong.
Thank you very much for helping me, Sebastian

**Comment by ahonymous** [comment]
Hi!!!
You must create an extension method in the your test. Example: http://symfony.com/doc/current/cookbook/form/unit_testing.html#adding-custom-extensions

**Comment by sebastianblum** [comment]
@ahonymous no, that's not the point in this case.

@webmozart can you please have a short look?

**Comment by xabbuh** [comment]
@sebastianblum In your form type, you don't specify the type of your `office` field. So the Form component will guess one using the registered type guessers. You will have to register the `DoctrineOrmTypeGuesser` from the Doctrine bridge in your tests to get the same behaviour.

**Comment by sebastianblum** [comment]
thank you very much @xabbuh
