### ISSUE TITLE
Better getRoles() annotation in UserInterface

### ISSUE THREAD

**Issue by lrlopez** [symfony/symfony#13530]
Hi,

When I run one of my projects over [Scrutinizer](https://scrutinizer-ci.com) I realized that the return type stated in the annotation of the method `UserInterface::getRoles()`is [`Role[]`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/User/UserInterface.php#L50). This is correct, but most (if not all) examples return an array of strings instead. It works, but it just doesn't look right.

Have you considered to modify the annotation in the interface so it look like this?

```php
interface UserInterface
{
    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * [...]
     *
     * @return Role[]|array The user roles
     */
    public function getRoles();
```
(notice the alternate return type in the `@return` annotation)

Even the provided example returns an array of strings.

**Comment by xabbuh** [comment]
see #13037 and #13146

**Comment by lrlopez** [comment]
Thanks @xabbuh , it seems I didn't look up for related issues deep enough. Closing the issue.
