### ISSUE TITLE
MoFileLoader issues a warning on missing translation

### ISSUE THREAD

**Issue by sproctor** [symfony/symfony#13547]
When I load an .mo with no missing translations, I get no warnings. When I load an .mo with untranslated strings, I get a warning printed for each one:

Warning: fread(): Length parameter must be greater than 0 in vendor/symfony/translation/Symfony/Component/Translation/Loader/MoFileLoader.php on line 141

Adding a check to $length < 1 before this fixes the issue.

**Comment by jakzal** [comment]
I failed to reproduce. Would you mind to provide a failing test?

**Comment by sproctor** [comment]
Test case:
```
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Translation\Translator;
use Symfony\Component\Translation\MessageSelector;
use Symfony\Component\Translation\Loader\MoFileLoader;

error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('html_errors', 1);

$lang = "fr";
$translator = new Translator($lang, new MessageSelector());
$translator->addLoader('mo', new MoFileLoader());
$translator->addResource('mo', "locale/$lang/LC_MESSAGES/messages.mo", $lang);

echo $translator->trans("Week");

?>
```

I have this running on my site so you can see the output. http://www.php-calendar.org/trans-bug.php

In MoFileLoader.php on line 141 it uses $length that is read from the file and the value is not checked.

**Comment by jakzal** [comment]
@sproctor could you also upload an example message.mo somewhere? My test case looked similar to yours, but I've tried it on a .po file converted to .mo.

**Comment by sproctor** [comment]
Yeah, it's there. http://www.php-calendar.org/locale/fr/LC_MESSAGES/messages.mo
