### ISSUE TITLE
[DX][Security] make it easy to throw Exceptions with User visible error messages

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#13542]
In my AJAX controller I just want to throw an Exception if something goes wrong that the user can handle and I want to include a message that should be shown to the user, e.g.:

``` php
  throw new UserMessageException('Report can not be deleted. There are still members related to this report.');
```

The json response built by the TwigBundle however just includes the error message from the 500 HTTP Code and I'd need to go into exception.message to display the exception message to the user.

On the other hand there might be exception messages that are not save to be displayed to the user. So there should be an interface to tag Exceptions which error messages for the user.

On the other hand it's a security issue that all exceptions are included in the json response. There might be Exception messages with sensitive information.

I know that I could easily write the necessary Interface, ExceptionController and json serializer in my own app. But I think this is general enough to be provided by symfony or some extension bundle.

**Comment by thomas-koch-comsolit** [comment]
The FOSUserBundle had a related issue and 'solved'(?) it with a solution that is applicable only to their bundle:
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1411

**Comment by iltar** [comment]
@thomas-koch-comsolit I prefer to add a message key to those exceptions. The message key is what ever you want to throw through the translation. This makes it possible to define a user-friendly error without bringing out sensitive information.

**Comment by stof** [comment]
@thomas-koch-comsolit no, it is not applicable only to FOSUserBundle. The fix done in the bundle is about using the feature added in the Security component in 2.2

**Comment by ogizanagi** [comment]
I opened an [issue](https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/332) some time ago about similar concerns on the [SensioFrameworkExtraBundle](https://github.com/sensiolabs/SensioFrameworkExtraBundle) repository (opened here as the referenced problematics were about this bundle and annotations, but the solution should certainly be owned by the symfony core).

The translatable message key will be a great advancement, but IMO, not sufficient for most advanced cases, where we might need to collect errors reasons in order to provide the best resolution case for the end user.

**Comment by iltar** [comment]
Sounds like somehow, the error should be translated to a human friendly message. A handler using either a mapping or `getMessageKey` would be sufficient for most cases. In any other cases, a custom handler could do the trick. I think this should be done (somewhere) in the standard `ExceptionController`.

**Comment by ogizanagi** [comment]
We agree that the `messageKey` is a straightforward solution, sufficient for most cases.

However, one of the cases I pointed out in my issue was voters:
> sensiolabs/SensioFrameworkExtraBundle#311 @Security annotations and voters, where even adding the possibility to add a message directly into the annotation might not be enough for advanced cases were multiple conditions could lead to the denied access (Voters decisions).

How will the `messageKey` be populated ? A way to populate it from the voter itself should be provided, as the voter is most likely the best to reveal from where comes the error exactly, and provide a concrete & accurate message to the end user.
But, what if the `access_decision_manager.strategy` is set to `consensus ` for example ? Which voter's `messageKey` should be used ?

**Comment by flip111** [comment]
:+1:

**Comment by javiereguiluz** [comment]
@weaverryan do you think we could take some ideas from this contribution of yours (http://symfony.com/blog/new-in-symfony-2-8-dx-improvements#easier-custom-authentication-errors) to solve this issue? Or are they totally different things? Thanks!

**Comment by chalasr** [comment]
I'm closing this issue as it is four years old and things have changed meanwhile. 
If you think the problem is not solved, please comment so we can consider to reopen, or open a new issue that takes all the improvements made to the component into account.
Thanks.
