### ISSUE TITLE
Better handling of implementation of deprecated interfaces

### ISSUE THREAD

**Issue by stof** [symfony/symfony#13544]
Currently, the DebugClassLoader logs a warning for classes implementing a deprecated interface (or extending a deprecated class) but ignores classes in the Symfony namespace.
This is good for deprecations coming from Symfony, but not for any other project providing their own BC layer, as seen in https://github.com/twigphp/Twig/issues/1612

A better solution would to skip the warning when the class is in the same root namespace than the interface (and taking care of PEAR-like convention for classes in the global namespace)

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
I like it. A general rule is better than an exception.

**Comment by nicolas-grekas** [comment]
Should be fixed by #13665
