### ISSUE TITLE
Form DateType and Intl problem

### ISSUE THREAD

**Issue by ghostika** [symfony/symfony#13546]
I recently updated my project from and older 2.5.X version for the newest 2.6.X version, and in one of my form, where I use the Birthday form type, with select box representation, the months select box got replaced with the short names instead of just the number representation, only on my staging and prod system.
After digging into this thing, I realised, php5-intl package wasn't installed on the server.
After installation is fine, but I thought the latest 2.6 version should work without the intl extension, is it not like that?
Without the intl extension, the right locale is not set for the IntlDateFormater, the value for \Locale::getDefault() was en, even though I set the locale in the config.yml for an other locale.
Is this a bug or this is intended?

**Comment by phansys** [comment]
Which locale you tried?

**Comment by phansys** [comment]
If it isn't "en", check [this comment](http://symfony.com/blog/new-in-symfony-2-6-farewell-to-icu-component#comment-19258) from @stof.

**Comment by ghostika** [comment]
The locale is 'hu' , but I solved the problem by installing the intl package. This issue is more of a question, if this is right in this way or this is a bug.

**Comment by stof** [comment]
To support other locales than ``en``, you indeed need the intl extension. The stub implementation only provides support for ``en``

**Comment by ghostika** [comment]
Ok, thanks for the answer, then I close this issue.
