### ISSUE TITLE
[DX] [TwigBundle] Allow to configure date and number formats

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#13552]
The problem
-----------------

When using Twig as a standalone project, you can define the date and number format as follows:

```php
$twig = new Twig_Environment($loader);
$twig->getExtension('core')->setDateFormat('d/m/Y', '%d days');
```

When using Twig inside a Symfony application, you have to use code like this to define this setting:

```php
$this->get('twig')->getExtension('core')->setDateFormat('d/m/Y', '%d days');
```

Even worse, some people recommend to create [a request listener to set this setting](http://stackoverflow.com/questions/9886058/how-can-i-set-the-default-date-format-for-twig-templates-in-symfony2).

In my opinion, having to create a listener, adding ugly code to my controllers and hurting application performance just to set the number or date format for my Twig templates is wrong.

The solution
----------------

TwigBundle should expose two new configuration options called `number_format` and `date_format` to simply configure these settings.

**Comment by alsar** [comment]
:+1:

**Comment by fabpot** [comment]
should be easy enough for  a PR.

**Comment by smolinari** [comment]
Date and number formats, including currencies, should be part of the locale and set according to the locale set for the current user. I believe this extension for Twig also has a way to handle this properly. http://twig.sensiolabs.org/doc/extensions/intl.html

Scott

**Comment by henrikbjorn** [comment]
Or what about people just use the date filter and provide it with a format ?

**Comment by javiereguiluz** [comment]
@smolinari you are right, but most of the times, applications don't want to display dates in *"the appropriate default format for the locale you are using"*. If the application wants to display the numbers and/or dates in a special format, it should be able to do it easily, independently from the locale.

@henrikbjorn of course it's possible to do that. But defining one configuration parameter in one file seems better than defining the exact same date/number format hundreds of times in your application templates.

**Comment by Rvanlaak** [comment]
:+1: from me [already since Feb '13](http://stackoverflow.com/a/15067573/1794894)

**Comment by smolinari** [comment]
@javiereguiluz - what sort of use case would warrant a special format?

Scott

**Comment by javiereguiluz** [comment]
@smolinari all of them. If I understand your previous comment correctly, you are saying: *"you don't need this option because dates should always be formatted according to the default style defined for the locale"*.

And I'm saying: *"applications should display dates as they wish. It doesn't matter wether that format matches the default format for the given locale or not. "*.

**Comment by smolinari** [comment]
All of what? I didn't say this option isn't needed at all. I am saying, a well programmed application will follow locales for proper formatting, because the locale is the basis for such formatting. It is part of decent i18n. 

Scott

**Comment by javiereguiluz** [comment]
@smolinari we have different opinions on this. I think that an application can be well designed even when it uses any date format different from *"the good one according to the locale"*.

**Comment by smolinari** [comment]
We'll have to agree to disagree then. Like I said, I am not against an easier way to format, however, it shouldn't stop a bundle from properly doing i18n and that means formatting according to the user's locale.

Scott

**Comment by Rvanlaak** [comment]
I think doing proper i18n is differs from having an application that does not use i18n and just need a simple way to modify their date and number formatting.

**Comment by smolinari** [comment]
I would still like to understand. What use case(s) do you have, where you need to format dates and numbers differently than the locale the application is running in/for? What formats are being used? Can you give an example?

Scott

**Comment by Rvanlaak** [comment]
The usecase:

> an application that does not use i18n and just need a simple way to modify their date and number formatting

This could be a simple API to connect a Javascript frontend with

**Comment by javiereguiluz** [comment]
@smolinari I would say the opposite: I can't imagine a non-trivial application which doesn't need to format dates in a custom way.

Imagine that you store the datetime `lastConectedAt` property in a user entity. Then, in the application you display this value in three different parts:

  * In the administration backend, you display it as `Y-m-d H:i:s`.
  * In the email sent to the user to recover his/her password, you show it as `l, F jS Y`
  * In the Twig template you use a JavaScrpt library to display fuzzy dates, so you display it as a timestamp: `U`

If I understand you correctly, you say that the application should display the date in the exact same way in these three cases.

**Comment by smolinari** [comment]
The application should certainly show the date with time or just the date, as needed, but in the format of the user's locale, just as that extension I linked to does. For instance, a German would want 24h time and not a.m and p.m. If your application only has one usergroup and a single locale, you set your default local and everything will work off of that. 

What's interesting is that extension also allows custom formatting too.;) Looks like a really cool extension to me.:)

Scott

**Comment by dincho** [comment]
> All of what? I didn't say this option isn't needed at all. I am saying, a well programmed application will follow locales for proper formatting, because the locale is the basis for such formatting. It is part of decent i18n.

:+1:

**Comment by Rvanlaak** [comment]
@dincho decent i18n is something different than enable simple, non-i18n agnostic applications to configure the Twig date format in my opinion ;-)

**Comment by smolinari** [comment]
Blog post about this. http://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration

Scott
