### ISSUE TITLE
Twig not escaping the same way in dev and in prod

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#13571]
Hi everybody,

I've been running in an issue since few days, and I've not been able to find where it come from.

I'm using Twig to build my javascript files (compiling several .js.twig files). But everytime I display a variable, a translations, or a path, it is not excaped the same way in DEV than in PROD.

In DEV mode, I've all the special characters escaped like "\x2Fapp_dev.php\x2Fmy\x2Droute" when it is not in PROD.

This is troubling for 2 reason: First, as you can see, the url are not displayed well in DEV, so the app is not working... And second, when it happens to have new line character in some string, everything goes right in DEV as it is encoded, but in PROD, it does not work because it dump a real new line in the middle of the string which stop the javascript of course. So I'm not abble to localize the problem in DEV because the behavior is not similar.

Is there a special configuration that make Twig excape differently in DEV and in PROD? I've check my config_dev.yml and config_prod.yml files, but it's the defaults one, so I don't find anything there.

Thanks for you help.

**Comment by Tobion** [comment]
Please ask support questions on the mailing list. As you don't provide any code or config whatsoever, it's impossible to reproduce.

**Comment by Vinorcola** [comment]
I'm building an example and I publish it as soon as possible
