### ISSUE TITLE
[Routing] Load routes via Puli

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#13575]
I think Puli (http://puli.io) can also be used for routes because they also have a name to reference them and they are meant to be shared across libraries.

Advantages:
- if Puli becomes the standard to reference resources in symfony, it would make things consistent to offer the same approach for routes and we can reuse puli functionality
- enabling/disabling routes via puli (which currently means importing or not importing the routing files)
- overwriting routes via puli map
- metadata for freshness check

Unfortunately, I think we cannot use the Puli mapping name as route name. As one resource only has one name, but we currently allow multiple routes be defined in one file, this cannot work. Otherwise we would need to change it to one route per file.

Symfony routing component would provide a binding type like `symfony/routing` or special subtypes for the different formats (e.g. `symfony/routing/annotation` when reading the route definitions from controller phpdocs).

Users would bind their routes to the type and the routing component would load them via the discovery mechanism. Currently when importing routes, people can customize things like the `prefix` or #12141. I think in Puli it translates to http://docs.puli.io/en/latest/discovery.html#binding-parameters, e.g. `puli bind /acme/blog/routes/*.yml symfony/routing/yml --param prefix="/blog"`. But the problem is that the end-user who enables the routes might want to overwrite some settings without overwriting the whole route resource. So I guess the user would disable the above binding provided by the blog bundle and instead make a custom binding like `puli bind /acme/blog/routes/*.yml symfony/routing/yml --param prefix="/myprefix"`.
The whole `import` feature within routing files would not be need anymore. And in theory one could get rid of the symfony/config dependency in the routing. But for the time beeing one would need a solution that works both with puli type binding and routing config loading.

@webmozart what do you think?

**Comment by Tobion** [comment]
A first implementation could be provided externally by https://github.com/puli/symfony-bridge and https://github.com/puli/symfony-bundle

**Comment by sstok** [comment]
Using Puli as resource-type will be the most flexible I think.

I actually thought about some similar a while back.
https://gist.github.com/sstok/a965a4bf0b6162e07273

**Comment by stof** [comment]
@Tobion the issue with your proposal is that the order of routes is meaningful. Imports are making this possible while your proposal removes the possibility to control the order.
I also makes it harder to load some routes only in some environments (loading Assetic routes only in environments where the assetic controller is used for instance, or loading the webprofiler styles only in dev)

**Comment by Tobion** [comment]
You can control the order of routes with a priority parameter when binding.

**Comment by stof** [comment]
@Tobion except that this means the priority is controlled by the package providing the routes, not by the project using them, right ?

**Comment by Tobion** [comment]
I think people can change the priority by using a custom binding, as I exemplified above with a custom prefix.

**Comment by jrobeson** [comment]
this sounds cool, it'd be nice to see Puli used here.

**Comment by webmozart** [comment]
I think that's a good idea!

About the customization of bindings: In the long run (hopefully in the final version), Puli will prompt you when packages with new bindings are installed/updated. You'll get a prompt along these lines:

```
$ composer update
...
New bindings were discovered in the "acme/blog" package: enable/disable/customize?
/acme/blog/routes/*.yml symfony/routing-yml (prefix: /blog) [enable]: customize
Parameter "prefix" [/blog]: /my-blog
```

The net effect will be that the binding of the "acme/blog" package itself is disabled and a customized binding is placed in the application package.

I also want to add a "bind --update --interactive" command (or similar) for editing existing bindings. So the usage of bindings will be much easier than the current version.

**Comment by javiereguiluz** [comment]
I'm afraid that I must close this as "won't fix" because Puli project lost traction and it no longer has activity :(
