### ISSUE TITLE
Getting POST parameter from Request. When did this change?

### ISSUE THREAD

**Issue by luxilio** [symfony/symfony#13585]
Hello,

`$request->get('name');` returns **null** for a POST parameter. In version 2.6.2 it was working fine. I couldn't find anything about the change in the release log. So with a fresh installation of the latest version, 2.6.4, the code now must be `$request->get('form')['name']`.

However, for a web service, I'm not using a form, so I cannot access `$request->get('form');`. How can I access the **POST** parameters now?

This is my code:
```php
public function postUsersAction(Request $request)
  {
    $userManager = $this->container->get('fos_user.user_manager');
    $user = $userManager->createUser();
    $user->setUsername($request->get('username'));
    $user->setEmail($request->get('email'));
    $user->setPlainPassword($request->get('password'));
    $user->setEnabled(true);

    $validator = $this->get('validator');
    $errors = $validator->validate($user, array('Registration'));
    if (count($errors) == 0) {
      $userManager->updateUser($user);
      return $user;
    } else {
      return $errors;
    }
  }
```

Thank you

**Comment by Tobion** [comment]
There was no change. For POST params use `$request->request->get()`. Please use the mailing list for support questions the next time.

**Comment by luxilio** [comment]
I didn't open an issue for support. `$request->request->get('name')` returns **null** while `$request->request->all()` returns this:

```php
array (size=1)
  'form' => 
    array (size=3)
      'name' => string 'tobion' (length=6)
      'send' => string '' (length=0)
      '_token' => string '0GEV20VserZgdKFNgggvikXR4EnQ8Iw-_ixKrvuyS04' (length=43)
```

I'm going to install 2.6.2 and run the same code.

**Comment by stloyd** [comment]
And that __totally correct__. Your code should be:
```php
$data = $request->request->get('form');
var_dump($data['name']);

**Comment by luxilio** [comment]
So my app was running fine in 2.6.2 and in 2.6.4 I get nulls. Was this change documented? I lost some good hours figuring what was wrong (starting debugging a web service); maybe documenting this would help others to update their code accordingly.

**Still, my problem**: If I don't have a form, how can I get the POST parameter in my method postUsersAction()?

**Comment by jrobeson** [comment]
@luxilio : you're supposed to use $request->request->get('field') and always should have been as it's more explicit than the $request->get(), but it does sound like what you were using shouldn't have been broken.

I think this bug should be reopened until the folks actually understand what you said.

**Comment by jrobeson** [comment]
@stloyd : if @luxilio had working code before the upgrade.. and then it stopped working, then this is a legitimate bug.

**Comment by jakzal** [comment]
Might be related to #12537. @jrobeson would you mind to rollback [changes in the `Request::get()`](https://github.com/symfony/symfony/pull/12537/files) to see if it brings the old behaviour?

**Comment by javiereguiluz** [comment]
@luxilio thanks for reporting this issue.

@Tobion and @stloyd are right about using `$request->request->get()` to be more efficient ... but you are right about the behavior change of the `get()` method.

As stated in the PHPdoc of [the get() method](https://github.com/symfony/HttpFoundation/blob/master/Request.php#L719-755):

```php
    /**
     * Gets a "parameter" value.
     *
     * This method is mainly useful for libraries that want to provide some flexibility.
     *
     * Order of precedence: GET, PATH, POST
     *
     * Avoid using this method in controllers:
     *
     *  * slow
     *  * prefer to get from a "named" source
     *
     * It is better to explicitly get request parameters from the appropriate
     * public property instead (query, attributes, request).
     *
     * @param string $key     the key
     * @param mixed  $default the default value
     * @param bool   $deep    is parameter deep in multidimensional array
     *
     * @return mixed
     */
    public function get($key, $default = null, $deep = false) { ... }
```

So it's clear that using `get()` is **perfectly valid** and it should work as expected. 

In my opinion, this issue should be reopened and treated as a bug.

**Comment by Tobion** [comment]
So what is the bug? Can somebody provide reproducible code please.

The code provided in https://github.com/symfony/symfony/issues/13585#issuecomment-72824467 is obviously wrong as @stloyd also explained.

**Comment by javiereguiluz** [comment]
According to @luxilio, this is the bug:

```
$request->get('name'); returns null for a POST parameter
In version 2.6.2 it was working fine.
```

**Comment by luxilio** [comment]
This is the code I'm using:
```php
public function contactAction(Request $request) {
        $form = $this->createFormBuilder()
            ->add('name', 'text')
            ->add('send', 'submit')
            ->getForm();

        $form->handleRequest($request);

        if($form->isValid()) {
            var_dump($request->request);
            die(var_dump($request->request->get('name')));
        }

        return $this->render('default/index.html.twig', array('form' => $form->createView()));
    }
```
The result:
```php
object(Symfony\Component\HttpFoundation\ParameterBag)[8]
  protected 'parameters' => 
    array (size=1)
      'form' => 
        array (size=3)
          'name' => string 'symfony' (length=7)
          'send' => string '' (length=0)
          '_token' => string '0GEV20VserZgdKFNgggvikXR4EnQ8Iw-_ixKrvuyS04' (length=43)

null
```

**Comment by javiereguiluz** [comment]
@luxilio this code doesn't match your first bug report. You said:

```
$request->get('name'); returns null (for a POST parameter)
```

And now you are saying:

```
$request->request->get('name') returns null
```

**Comment by luxilio** [comment]
Both methods return **null**. It's clear that something changed, because now I need to use: `$request->get('form')['name']`. I remember that I was using `$request->request->get()` without any problems.

I have no problems using the new way. But with a webservice without any form, it's impossible to get the post parameter. Off-topic: I read your book. Thanks a lot. Cheers from Madrid.

**Comment by Tobion** [comment]
Just a tip: use empty form name. And people still didn't explain why the wrong code is supposed to work.

**Comment by javiereguiluz** [comment]
@Tobion the original bug report was as follows:

```
$request->get('name'); returns `null` when the `name` parameter is passed via POST.
```

If that's true, then this is a bug, because `get()` should return both GET and POST parameters.

**Comment by jakzal** [comment]
> $request->get('name'); returns `null` when the `name` parameter is passed via POST.
> If that's true, then this is a bug, because get() should return both GET and POST parameters.

This is not true. I have just tested it with a simple script:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
var_dump($request->get('name'));
```

The following request:

```bash
curl --data 'name=Javier' 'http://localhost:8000/'
```
returns:

```bash
string(6) "Javier"
```

@luxilio the result of your last example is the same for both 2.6.2 and 2.6.4. You're getting `null` as you're requesting `name` rather than `form` as mentioned earlier by others.

Please provide a fork of Standard Edition with your problem reproduced, as it's clearly not the example you given.

**Comment by javiereguiluz** [comment]
@jakzal thanks for taking the time to investigate this issue. It appears that the original bug report wasn't precise.

In any case, Symfony is a complex *beast*, so testing the Request component in isolation is not enough to prove that everything works right (it could be a valid test to prove that something works wrong). Although this is **not** the case for this issue, other parts of Symfony could affect the request parameters and introduce some bugs even if Request component is working right.

**Comment by luxilio** [comment]
Then it must be something with my system. Last week it was working fine, then I installed PEAR and the internationalization extension using brew on Yosemite. Testing again some days after this change I couldn't get any parameters. I'll investigate and I'll come back to you. Thank you

**Comment by jakzal** [comment]
@javiereguiluz it works with the full stack too. I only showed a simple example here for practical reasons.

**Comment by jakzal** [comment]
@luxilio feel free to reopen if you manage to reproduce. Thanks!

**Comment by ZakClayton** [comment]
I've just started to get this issue. I feel it maybe something to do with how i have set the value for the field.

I am required to pass the entity ID through the post request if it existed. I know there are many methods for this and i probably have not chosen the correct one but nether the less that is not the issue.

I have a field called **shopId** which is also set in my **Shop** entity and has getters and setters. Along with this field i also have some arbitrary **Shop** data that will be saved / updated depending on whether the ID is present.

The **shopId** value is set through the twig template with a simple:
`{{ form_widget(form.shopId, {'attr': { 'value' : 1 }}) }} ;`

When i dump `$request->request->all()` **shopId** has a value of **1** but ...
`$request->request->get('shopId')` = **null**
 `$request->get('form_name')['shopId']` = **1**

Sorry to reopen this but i thought it may provide some insight or maybe i can help investigate further?

**Comment by xabbuh** [comment]
> When i request a field:
`$request->request->get('name') = null`

The correct way would be `$request->request->get('form_name')['name']`

**Comment by ZakClayton** [comment]
So as suspected it wasn't a bug at all just user error. Thank you for confirming and sorry for re-opening.

**Comment by yellow1912** [comment]
This issue is rather old and closed so I'm not sure if I should bring it back to life or should open a new one. I have just recently run into a similar bug upgrading from 2.8 to 3.1

My route config looks like this

```
core.frontend.partial.get:
    path: /partial/get/{dir}
    defaults:
        _controller: CoreBundle:Partial:get
       dir: null
    options:
        expose: true

```

Within my controller, I use

`$request->get('dir')`

After upgrading, the above code returns null and only $request->query->get('dir') returns the correct value. Did I miss something important in the changelog?

**Comment by xabbuh** [comment]
@yellow1912 Since Symfony 3.0 the `get()` method first returns a request attribute before checking query parameters (see #16076). It looks like we forgot to update the upgrade instructions accordingly (see #20209 for the fix).

**Comment by Tobion** [comment]
@yellow1912 so you use a `dir` parameter both as a path placeholder as well as a query param?

**Comment by yellow1912** [comment]
@Tobion thank you, already fixed in my system, it was an easy fix once you know what has gone wrong. This is however still a change in the working behavior of this method, and I hope people who run into the same issue upgrading from 2.x will find the information here useful :)

**Comment by Saint-Cyr** [comment]
I'm spending so many hours ... just to find a parameter from AJAX call both POST & GET But nothing work !  trying allmost all the necessary methode of the Request::API ...dumping the resulat but still NULL  or int(0) ...unstable because few months ago everything where fine and even my old script does not work. I'm using SF 2.8 full stack.

Ajax call:

`if (this.value.length >= 3 || this.value == '')

                                {
                                    var s = $('#keyWord').val();
                                    //alert(s);
                                    $.ajax({
                                        url: "http://localhost/Nwt10/web/app_dev.php/product-search",
                                        type:"get",
                                        data: {'keyWord':'Content of data1 '},
                                        success: function(result){
                                                    $("#mainPage").html(result);
                                                },
                                        error:  function (xhr) {
                                            alert('Error.....AJAx');
                                        }
                                    });`

I've try each one of all the methode bellow and also the Request method in the Ajax call accordently.

`public function indexAction(Request $request)
 {
        if($request->isXmlHttpRequest()){

            //$request = $this->container->get('request_stack')->getCurrentRequest();
            //$request = $this->get('request');
            //$keyWord = $request->query->get('keyWord');
            //$keyWord = $request->request->get('keyWord');
            //$keyWord = $request->get('keyWord');
            //$keyWord = $request->request->getInt('keyWord');
            //$keyWord = $request->query->all();
            return new Response(var_dump($keyWord));
        }`

**Comment by sstok** [comment]
@Saint-Cyr Please use a http://symfony.com/support channel. IIRC $.ajax() data only works for POST, but I haven't used jQuery in over a year.

**Comment by emimarz** [comment]
some interesting comment

if the input form doesn't have name the parameter never arrive to object request

**Comment by Qkenkenu** [comment]
Hi,
symfony 3.2.13
In case you have FormType for entity
and set 
```

	public function getBlockPrefix()
	{
		return 'app_bundle_some_form_type';
	}
```

in your controller you can get POST only by

`dump($request->get('app_bundle_some_form_type')['somearrayfield'] );`

but unfortunetly due to Symfony/Component/HttpFundation/ParameterBag.php method

 ```
   /**
     * Sets a parameter by name.
     *
     * @param string $key   The key
     * @param mixed  $value The value
     */
    public function set($key, $value)
    {
        $this->parameters[$key] = $value;
    }
```


you are unable to change in any way $request 

`$request->request->set("app_bundle_some_form_type", $var);`
//['xx']['xx']
//("xxx", $x)['xxx']

but if you don't set name in your FormType, you can change the value of passed parameter

is it correct behavior?

best regards,
P.

**Comment by xabbuh** [comment]
You need to fetch the data with `$request->request->get('app_bundle_some_form_type')`. This will return an array which you can modify as needed an write it back using `$request->request->set()`.

**Comment by xabbuh** [comment]
But you may also want to look into [form events](https://symfony.com/doc/current/form/events.html) if you need to modify the data that is submitted to your form.

**Comment by Qkenkenu** [comment]
hi, xabbuh,

was trying already by

$data = $request->request->get('app_bundle_some_form_type');
$data['keyname'] = 222
dump($data['keyname']); //works

but in any way I can't do it on $request

**Comment by xabbuh** [comment]
I do not understand what you mean. But anyway, as we do not use GitHub for support please use one of the [support channels](https://symfony.com/support) for your question. Thank you for understanding.

**Comment by Traveling-salesman** [comment]
https://preprocessor.space/questions/encountering-an-empty-array-in-a-php-script-when-transmitting-form-data-via-ajax-using-the-post-method

**Comment by Avsy** [comment]
> [@Saint-Cyr](https://github.com/Saint-Cyr) Please use a http://symfony.com/support channel. IIRC $.ajax() data only works for POST, but I haven't used jQuery in over a year.

**Comment by Avsy** [comment]
@jakzal @yellow1912

**Comment by Avsy** [comment]
#58628
