### ISSUE TITLE
[WebProfilerToolbar] When $request->request->all() is over 4kb, the contents are outputted to the browser.

### ISSUE THREAD

**Issue by bobdenotter** [symfony/symfony#13595]
Hi, I'm helping somebody debug his web-app on crappy shared hosting. Whenever he does a `POST` request which is over **4kb**, it is output to the browser, before the rest of the request. As soon as it dips _below_ 4kb, all is well.

As far as I can tell it happens somewhere in the 'collection' part of the request. Output buffering is disabled.

See screenshot: 

![screen shot 2015-02-04 at 17 07 55](https://cloud.githubusercontent.com/assets/1833361/6044097/6bc6098c-ac91-11e4-9c8e-43efecd56c33.png)

PHPinfo here: http://www.pb-ac.com/phpinfo.php

If I disable the WebProfilerToolbar the issue goes away. Any ideas as to where I should start digging?

**Comment by stof** [comment]
it would be great to provide a project reproducing this, to allow debugging it

**Comment by jakzal** [comment]
@bobdenotter does it behave the same way on a vanilla installation of Symfony Standard Edition?

**Comment by javiereguiluz** [comment]
@bobdenotter maybe it's related to a wrong cookie? 4kb is the usual limit for cookie size.

**Comment by bobdenotter** [comment]
Hi all, 

I opened this issue over 8 months ago. I did a fresh install of Bolt on the same host, but couldn't reproduce it anymore. It's probably either fixed on the server or in Symfony. (I think it was using SF 2.4 back then)

Let's just close this, but thanks for looking into it! ^_^
