### ISSUE TITLE
[Doctrine][Bridge] EntityType: If the choices property has incorrect value, then EntityChoiceList makes findAll() instead

### ISSUE THREAD

**Issue by m00t** [symfony/symfony#13605]
I am not sure whether this is an intended behavior or not, need some comments before I can start to work on PR.

Given form builder step:

``` php
        $builder->add('price', 'entity', array(
            'class' => 'Namespace\Price',
            'choices' => $this->pricesRepository->getAllPricesByUser($this->user),
            'property' => 'name',
            'label' => 'Price',
            'placeholder' => 'Empty'
        ));
```

`getAllPricesByUser()` returns array of entities and everything works fine. But then I implemented pagination and changed `getAllPricesByUser()` to return an instance of some custom `PaginatedCollection` class (which appears to not be an instance of `\Traversable`). And after that `EntityChoiceList` began to draw all prices from all users (and tests of cause does not see that, because you can not test every choice list this way).

So I think `EntityChoiceList` should throw an exception when created with `$entities` other than `array`, `null` or `\Traversable`

**Comment by jakzal** [comment]
I agree we should throw an exception. 

Choices are passed to the `EntityChoiceList`, which expects [an array, \Traversable or null](https://github.com/symfony/DoctrineBridge/blob/master/Form/ChoiceList/EntityChoiceList.php#L95). It does not check for `null` though. It actually [assumes entities should be loaded](https://github.com/symfony/DoctrineBridge/blob/master/Form/ChoiceList/EntityChoiceList.php#L108) if something else than `array` or `Traversable` is passed.

I think we should either honor `EntityChoiceList`'s contract and do not pass anything that's not an `array`, `Traversable` or `null`, or throw an exception from `EntityChoiceList`.

**Comment by fabpot** [comment]
Anyone willing to work on a fix?

**Comment by xabbuh** [comment]
I am not sure it's worth it to spend any time here. The `EntityChoiceList` class was already removed in Symfony 3.

**Comment by fabpot** [comment]
Ok, closing then.
