### ISSUE TITLE
Redirect loop from loadbalancer

### ISSUE THREAD

**Issue by avtarcnk** [symfony/symfony#13603]
Hello,

We have two application server behind a load balancer. While redirecting from http to https, the request goes in a redirect loop. The same work fine which testing without load balancer. We are using Radware load balancer.

Symfony version : 2.6

Avtar

**Comment by jameshalsall** [comment]
So it's probably an issue with your load balancer?

**Comment by malarzm** [comment]
@avtarcnk I'm not sure if I had redirect loop problem, but setting @framework.trusted_proxies@ in config helped me when I had issues with SSL and load balancer

**Comment by Tobion** [comment]
As @malarzm explained you need to configure both the load balancer and symfony correctly, so symfony knows its an HTTPS request. If there is an actual bug, feel free to reopen.
