### ISSUE TITLE
Symfony pluralization bugs with "Device"

### ISSUE THREAD

**Issue by malavsky** [symfony/symfony#13613]
"Device" pluralized to "Devouse" and also "feedback" to "foodback"

symfony 2.6.4

**Comment by aivus** [comment]
:+1:

**Comment by WouterJ** [comment]
I can confirm `feedback -> foodback`, but `device -> devouse` works perfectly (at least in 2.3). See also https://github.com/symfony/symfony/pull/13618

**Comment by malavsky** [comment]
I have Component entity with oneToMany relation to ComponetToDevice entity. For admin I use SonataAdminBundle. When I build a form to edit Component entity with sonata_type_collection type for 'componentToDevice' field . I got a error that symfony can not find addComponentToDevice or setComponentToDevice and propouse me setComponentToDevouce and etc.

**Comment by WhiteEagle88** [comment]
@malavsky You got a error that symfony can not find "addComponentToDevouce()"/"removeComponentToDevouce()", "setProjectFeedback()", "componentToDevouce()", "__set()" or "__call()" exist and have public access in class "...\MainBundle\Entity\Component"."

**Comment by aivus** [comment]
> but `device -> devouse` works perfectly

@WouterJ do you really think is it correct behavior?
`device` should stay `device` after `StringUtil::singularify()`

**Comment by WouterJ** [comment]
@aivus the plural of "device" is "devices". `StringUtil::singularify('devices')` returns 3 options, one of them is "device" (the correct one). See also my PR.
