### ISSUE TITLE
[Process] wait() fails on Windows using Cygwin

### ISSUE THREAD

**Issue by thasmo** [symfony/symfony#13612]
When running a process with `Process->run()` it never ends successfully, when executed from within a Cygwin environment, because the `wait` method produces an infinite loop on lines 359-360. The reason is that the directory separator in Cygwin is `/` but `$this->processPipes->areOpen()` still fails because apparently this doesn't work in Cygwin. I guess this is because Cygwin runs on Windows after all.

When using the PHP version of Cygwin there's a constant available called `PHP_OS` which has the content of `CYGWIN` that could be used to check if PHP is running in the Cygwin environment. The value varies for different Cygwin versions, sometimes it's `CYGWIN_NT-5.1` or similar.

Probably there are more places where this would have to be implemented to get full Cygwin support.

I'd appreciate it, if Cygwin gets considered to be supported.

**Comment by nicolas-grekas** [comment]
The Process component has been refactored recently. Please reopen if the issue still holds.
