### ISSUE TITLE
missing dependency for debug-bundle

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#13614]
`symfony/config` should be added [to this list](https://github.com/symfony/debug-bundle/blob/master/composer.json#L18-L23) because of [these classes](https://github.com/symfony/debug-bundle/blob/master/DependencyInjection/Configuration.php#L14-L15)

**Comment by flip111** [comment]
Which brings me to the idea ... can there be some kind of tool that checks for missing dependencies?

**Comment by fabpot** [comment]
That's not a hard requirement. You can use most of the features without using the config (think Silex for instance).

**Comment by WouterJ** [comment]
@fabpot in that case, it should be extracted into a bridge and a bundle, shouldn't it?

**Comment by flip111** [comment]
@fabpot thanks for clearing it up that it is not a hard requirement. I was using this bundle with silex and will notify the author of the relevant bundle. For reference: https://github.com/jeromemacias/Silex-Debug/blob/master/DebugServiceProvider.php#L68

**Comment by stof** [comment]
@fabpot Given that the DebugBundle does not provide much more than the configuration, it might make sense to define it as a dependency though

**Comment by nicolas-grekas** [comment]
@stof https://github.com/jeromemacias/Silex-Debug uses the template but not the configuration, so there seems to be a use case already without the strict dep on Configuration
