### ISSUE TITLE
Missing Routing parameters docs

### ISSUE THREAD

**Issue by FusionDev-OpenSource** [symfony/symfony#13623]
In the URL http://symfony.com/doc/current/reference/configuration/framework.html it says that the page should have all accepted configuration for diverse topics, including Routing. However I can't find any docs on all values accepted by Routing. For example, there is the type: annotations, but it is no documented what other types exists, or even what other parameters exists. I would appreciate hola on how I can find out these parameters. Mayor a config file? Thanks

**Comment by fabpot** [comment]
Can you open an issue on the symfony/symfony-docs repository? This is where the documnetation i managed. Thanks a lot.

**Comment by WouterJ** [comment]
see https://github.com/symfony/symfony-docs/issues/4973
