### ISSUE TITLE
[Forms][RFC] Names should be customizable

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#13631]
There are many example where names should be customizable. Here are 2 examples:

1. I want to make a search type. I would like my URL to be something like `mywebsite.com/search?q=foo`, of course in my code I don't want to have `q` but maybe something like `query` that is really more understandable, but right know I need to build my for exacly like it is in my request.
2. I want to make an API with special fields and keep the full control on my code (be able to modify any field in my entities and so on). Here i just haven't any easy way to make a type, I need to inject something in the middle of the request and my type, too bad since we have an handleRequest method that should do the job.

*I'm not sure to be clear, I hope so, do not hesitate to ask for explaination.*

About a solution, I imagine something like that could be great:

```php
<?php
$builder->add('foo', 'text', ['name' => 'bar']);
```

Of course that mean some serious changes in the FormFactory element, but there's no BC Break.

What do you think about ? Maybe if you like the idea I can handle it.

**Comment by iltar** [comment]
If I get it right, you want to map `bar`` to `data.foo`? Can't you manually translate q to query before binding?

**Comment by ogizanagi** [comment]
I wasn't sure about the concrete use cases you exposed, but then I thought about another case I was confronted some times ago, that might be solved by such a feature: https://github.com/symfony/symfony/issues/10176#issuecomment-68448571
Maybe this could help advocate for this feature.

**Comment by Nek-** [comment]
My bad. Indeed the property_path do the job. Actually it's weird from the first look at the feature but that's the best way to perform my examples.

So for those who does not understand everything, here is how to use property path:

```php
<?php

namespace You\AppBundle\Entity;

class Article
{
    private $title;
}
```

```php
<?php

namespace You\AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;

class ArticleType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('something', 'text', ['property_path' => 'title']);
    }

    /**
     * The getName return nothing to avoid names like "name_of_type[something]"
     */
    public function getName')
    {
        return '';
    }
}
```

**Comment by stof** [comment]
@Nek- Please don't use an empty name for your form type. this is causing issues. Instead, you should create a named form instead of using the form type name as form name (form names can be empty, while type names should not and must be unique in the project)

**Comment by Nek-** [comment]
@stof by creating a form you mean using a form builder instead of using a form type ? Actually it's bind to  an entity so that's weird, isn't it ?

**Comment by stof** [comment]
@Nek- I meaning using ``$formFactory->createNamed`` (or ``$formFactory->createNamedBuilder``) rather than ````$formFactory->create`` (or ``$formFactory->createBuilder``). This way, you can control the form name explicitly instead of making it reuse the same name than the form type.

This involves not using the ``createForm`` shortcut of the controller though (there is no shortcut for the creation of named forms)

**Comment by Nek-** [comment]
That's definitively true. I edited my post.
