### ISSUE TITLE
[Security] Unable to use AuthorizationChecker::isGranted() in cli applications

### ISSUE THREAD

**Issue by korotovsky** [symfony/symfony#13635]
```php
// \Symfony\Component\Security\Core\Authorization\AuthorizationChecker::isGranted()
final public function isGranted($attributes, $object = null)
{
    if (null === ($token = $this->tokenStorage->getToken())) {
        throw new AuthenticationCredentialsNotFoundException('The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.');
    }
    ...
}
```

There is any way/workaround to use it in CLI?

**Comment by stof** [comment]
Well, you should set a token in the TokenStorage before being able to use the security system. In the CLI, there is no firewall running to authenticate the user so you would need to perform this step manually.

**Comment by korotovsky** [comment]
@stof Okay, Thanks. 

And I have the similar question related to Security component.

What is the better way to use ACL system to check permissions for another user in Web? (Not current from token).

**Comment by jaytaph** [comment]
@korotovsky You might be able to ask this directly to the access decision manager, just like `isGranted()` does:

    return $this->accessDecisionManager->decide($token, $attributes, $object);

where the `$token` is a manually created token for the new user. Or use isGranted() directly, but switch the current token with a new token before making the call (and replacing the original token back afterwards).

**Comment by jakzal** [comment]
Closing as this is not really a bug.
