### ISSUE TITLE
bootstrap_3_layout.html.twig template should be traitable

### ISSUE THREAD

**Issue by krzysztof-alboszta** [symfony/symfony#13639]
shouldn't the template `bootstrap_3_layout.html.twig`  be reusable in the same way as `form_table_layout.html.twig` in the traitable inheritance

changing 
```
    {% extends 'form_div_layou.html.twig %}
```
into
```
    {% use 'form_div_layout.html.twig %}
```
as it was made for the `form_table_layout.html.twig` here: https://github.com/symfony/symfony/commit/6737bd36bd39f491ea2936551d7db72e29b944fd
would give the possibility to reference block from that template like it is described in docs:
http://symfony.com/doc/current/cookbook/form/form_customization.html#referencing-blocks-from-inside-the-same-template-as-the-form

**Comment by jakzal** [comment]
Would you mind submitting a PR?

**Comment by krzysztof-alboszta** [comment]
sure!
I've just tried with quick-pull-request but I will prepare the proper one yet today

**Comment by noyg** [comment]
+1
