### ISSUE TITLE
[PdoSessionHandler] Remember me lifetime not use

### ISSUE THREAD

**Issue by baptistedonaux** [symfony/symfony#13643]
I use PdoSessionHandler with Symfony 2.6. I try to configure "Remember me" option but when checkbox is checked, the session lifetime doesn't change.

In Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler, the session lifetime is given by PHP configuration with it :
```$maxlifetime = (int) ini_get('session.gc_maxlifetime');```

This option is it settable by Symfony configuration or only per php.ini ?

**Comment by jakzal** [comment]
The `lifetime` option in remember me settings sets a lifetime of the remember me cookie, not a lifetime of the session. See http://symfony.com/doc/current/cookbook/security/remember_me.html for more.

**Comment by baptistedonaux** [comment]
Sorry, I confused !
