### ISSUE TITLE
Should we make twig extension functions for accessing ICU Data ?

### ISSUE THREAD

**Issue by kcassam** [symfony/symfony#13641]
Tell me if it would be a good idea to add a extension/twig folder, containing a IcuExtension.php with those functions : 

```
public function getFunctions()
{
    return array(
        new \Twig_SimpleFunction('languageName', array($this, 'getLanguageName')),
        new \Twig_SimpleFunction('scriptName', array($this, 'getScriptName')),
        new \Twig_SimpleFunction('countryName', array($this, 'getCountryName')),
    );
}

public function getLanguageName($language, $region = null, $displayLocale = null)
{
    return Intl::getLanguageBundle()->getLanguageName($language, $region, $displayLocale);
}

public function getScriptName($script, $language = null, $displayLocale = null)
{
    return Intl::getLanguageBundle()->getScriptName($script, $language = null, $displayLocale = null);
}

public function getCountryName($country, $displayLocale = null)
{
    return Intl::getRegionBundle()->getCountryName($country, $displayLocale = null);
}
```

So we can use them in twig like that for ex

```
{{ languageName('en') }}
{{ languageName('en', null, 'de') }}
```

If it's a good idea, I'll make a PR.

K.

**Comment by Tobion** [comment]
Your issue title is definitely not a "Good idea". Also this looks more something for the twig extension repo instead of symfony core.

**Comment by stof** [comment]
@Tobion given that it depends on the symfony/intl component, it would actually be something for the twig-bridge, not fo the Twig-extensions package

**Comment by kcassam** [comment]
A new Extension called IntlExtension in Symfony\Bridge\Twig\Extension\ seems fine to me.

Note : Filters defined here (http://twig.sensiolabs.org/doc/extensions/intl.html) depend on intl component as well, but have been put in vendor/twig/extensions/lib/Twig/Extensions/Extension/Intl.php.

**Comment by jrobeson** [comment]
@Tobion : don't youo think that was a little harsh?

**Comment by Tobion** [comment]
It's called humor.

**Comment by kcassam** [comment]
Original title was bad indeed ! :)

**Comment by kcassam** [comment]
Original title was bad indeed ! :)

**Comment by stof** [comment]
@kcassam the filters in Twig-extensions don't depend on ``symfony/intl``, they depend on classes of the intl extension (and ``symfony/intl`` provide stubs implementations for them)

**Comment by ro0NL** [comment]
@stof what exactly is wrong with twig-extensions depending on symfony/intl? This is what the component is for right, allowing things like `localizeddate` to work more or less consistently with or without the intl extension...

**Comment by fabpot** [comment]
There is nothing wrong as it can be done in both repositories, but it makes more sense to do this in the bridge as its goal is exactly that: bridging Symfony and Twig.

**Comment by ro0NL** [comment]
Fair enough.. personally i'd prefer `composer require symfony/intl + twig/extensions` and have _full_ intl support.

**Comment by HeahDude** [comment]
Should the intl extension then be moved from Twig to the bridge by deprecating them in `twig/twig-extensions` so we can can use stubs for the other filters?

**Comment by fabpot** [comment]
Sure, I think it makes sense.

**Comment by Hanmac** [comment]
i think we should begin small with the ResourceBundle things first.
that wouldn't even deprecate the ones in twig/twig-extensions.

then later we can extend it with options like in #20053

today i am again at a point where i would need it, but it didnt exist jet.

**Comment by stof** [comment]
Exposing the ICU data and exposing the formatters from ext-intl are 2 separate topics IMO. Exposing ext-intl can totally be kept in Twig-extensions, where it **already** lives, as it does not need any dependency on symfony/intl (symfony/intl only provides a partial polyfill in case you don't have ext-intl, but the Twig extension does not need to be aware of it).
Exposing the additional ICU data should indeed be done in the bridge. but it can be a separate Twig extension instead of asking to deprecate ``Twig_Extensions_Extension_Intl``.

**Comment by Hanmac** [comment]
@stof: yeah i think you are right.
the ICU data with the ResourceBundle should be done sonewhere in symfony (probably in the twig bridge?)
for that, #20053 might be a good way to start.

with doing it split, `Twig_Extensions_Extension_Intl` might be not need to be deprecated,
but i would like it if it would be extended to support attributes.

PS: i didn't noticed that symfony/intl was only i polyfill until i did try other languages xD

**Comment by fabpot** [comment]
Implemented in https://github.com/twigphp/Twig/pull/3108
