### ISSUE TITLE
[Router] Optimization: use strncmp insteadof strpos

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#13658]
strpos === 0 is used in the dumped router files to match static initial parts of a route.
Shouldnt be strncmp === 0 be faster than strpos === 0?

Also another nice followup optimization can be done, since strncmp returns -1 for "smaller" strings and 1 for "larger" strings:
```php
$c = strncmp($request, $route, $length);
if($c < 0) {
  // only routes that have a "smaller" initial part need to be checked
} elseif($c == 0) {
  // initial part matches, match the next part
} else {
  // only routes that have a "larger" initial part need to be checked
} 
```

I didnt run any performance tests for this, so its just an idea.

**Comment by fabpot** [comment]
If you can prove with a bench that it is faster, why not; until then, this is pure speculation.

**Comment by nicolas-grekas** [comment]
Already proposed: this is slower, see #10294

**Comment by backbone87** [comment]
I found similar tests through google, but these (like the ones in #10294) are working with very short strings. strpos should decrease in performance as `strlen($haystack) / strlen($needle)` grows (in the router context this means: `strlen($request) / strlen($staticInitialPart)`), while strncmp performance should scale with `min(strlen($haystack), strlen($needle))`.
And the main net performance gain, should be in the usage of the return value of strncmp, to optimize the following matching process in case of a part mismatch.

**Comment by Tobion** [comment]
So at which string length would strncmp be faster?

**Comment by backbone87** [comment]
https://gist.github.com/backbone87/131fca67e40f7100b094

```
Benching strpos short short...
0: 0.33007788658142
1: 0.39355492591858
2: 0.36621117591858
Benching strncmp short short...
0: 0.36425685882568
1: 0.36132907867432
2: 0.36230397224426
99.82%

Benching strpos short long...
0: 0.31836009025574
1: 0.32128882408142
2: 0.31738305091858
Benching strncmp short long...
0: 0.36914014816284
1: 0.37011694908142
2: 0.36523485183716
115.41%

Benching strpos short short mismatch...
0: 0.29980421066284
1: 0.296875
2: 0.296875
Benching strncmp short short mismatch...
0: 0.3486328125
1: 0.34765601158142
2: 0.34863305091858
116.94%

Benching strpos short long mismatch...
0: 0.29296898841858
1: 0.29394507408142
2: 0.29199290275574
Benching strncmp short long mismatch...
0: 0.35351514816284
1: 0.3486328125
2: 0.3525390625
120.00%

Benching strpos long short...
0: 0.32031297683716
1: 0.32519507408142
2: 0.3212890625
Benching strncmp long short...
0: 0.36035084724426
1: 0.36132907867432
2: 0.36132788658142
112.02%

Benching strpos long long...
0: 0.32031202316284
1: 0.32226610183716
2: 0.32324194908142
Benching strncmp long long...
0: 0.36425805091858
1: 0.36718702316284
2: 0.36523485183716
113.55%

Benching strpos long short mismatch...
0: 0.36035108566284
1: 0.35839891433716
2: 0.35839819908142
Benching strncmp long short mismatch...
0: 0.34765601158142
1: 0.34960913658142
2: 0.34863305091858
97.10%

Benching strpos long long mismatch...
0: 0.3505859375
1: 0.35156297683716
2: 0.34960889816284
Benching strncmp long long mismatch...
0: 0.34765601158142
1: 0.345703125
2: 0.34570288658142
98.79%
```

The most interessting are the "* short mismatch" cases, because:
a) static prefixes of routes tend to be short
b) there are much more mismatches during routing, then matches

Conclusion: Just switching from strpos to strncmp, without using the benefit of evaluating the return value of strncmp, doesnt provide any meaningful improvement, if any at all.
But that followup improvement could reduce the required matches by up to 50%, if everything is in the normal distribution.

**Comment by stof** [comment]
@backbone87 but this would make the dumper code insane IMO, given that the order of routes is meaningful. Doing a division based on the first route is not always possible depending of how other routes are looking like

**Comment by backbone87** [comment]
@stof The partition is always possible since we only take the static prefixes into account anyway for the whole string comparism optimization.
