### ISSUE TITLE
[Routing] Adding RouteCollections doesn't take into account the prefix

### ISSUE THREAD

**Issue by brendo** [symfony/symfony#13654]
I'm using Routing Component v2.6.4. 

In my application I have a 'master' `RouteCollection`, which holds all the routes for an entire API. The API is comprised of applications, and each application provides their own set of routes via their own `RouteCollection` object. The applications set a prefix on their `RouteCollection` so they can just define the `$path` as `/hello/` instead of `/apps/example/hello` using `RouteCollection->setPrefix`.

I have a build script that amalgamates all the application `RouteCollection` objects into the single 'master' `RouteCollection` (using `RouteCollection->addCollection`) and I've noticed that if two applications provide the same `$path`, they will be cobbled together and the 'last' application's routes will win.

I would of expected that both Routes would be allowed in the 'master' `RouteCollection` because they have different prefixes?

Here is a [sample gist](https://gist.github.com/brendo/a493d37fdb033c4edb04) which demonstrates the problem I'm facing. In this example, I am expecting two return routes, `/a/hello` and `/b/hello`/.

Is this a bug?

**Comment by brendo** [comment]
Looking back in the Routing history, I think this _used_ to work, but [this commit](https://github.com/symfony/Routing/commit/b472b17a60b9730c61a68e99439df9e4f460607d) stopped respecting prefixes - not intentionally, just as the result of removing deprecated functions. 

The new merge using only the route name seems too simple now, as it will not handle routes from different collections having the same name, but different prefixes.

**Comment by ihsanudin** [comment]
``<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

$masterRoutes = new RouteCollection();

$routesA = new RouteCollection();
$routesA->add('helloa', new Route('/hello', array('controller' => 'foo')));
$routesA->addPrefix('/a/');

$routesB = new RouteCollection();
$routesB->add('hellob', new Route('/hello', array('controller' => 'foo')));
$routesB->addPrefix('/b/');

$masterRoutes->addCollection($routesA);
$masterRoutes->addCollection($routesB);

var_dump($masterRoutes->all());exit;``

I think it will be work for your case

**Comment by brendo** [comment]
Yes @ihsanudin that does, because each route is then given a unique name. This seems a little bizarre to me, as I'm now required to have a unique name for the route as well as a unique path.

**Comment by ihsanudin** [comment]
Why? It just for a route collection not a route... You just add a name for each of route collections

**Comment by Tobion** [comment]
The route names must be unique ever since. Otherwise you cannot generate a path for them which you do by specifying the name. The path must not be unique and is up to you.

**Comment by ihsanudin** [comment]
i think if add $name in param of addCollection is not problem and not effect in code base
