### ISSUE TITLE
Ajax query works when adding new post but doesn't work when update an entity in a select box

### ISSUE THREAD

**Issue by houssem04** [symfony/symfony#13653]
I have two Select box one for the Countries and the second for the cities and the second one depends from the selected choice of the first one.

All things work fine when adding a new post and when I select a country , cities related are displayed correctly , **but when trying do update a Travel**, Ajax query to display cities doesn't work when change a country .

**I must to click on submit button to display the new list of cities**. I can't understand what's wrong

Controller

    /**
    * @ParamConverter("agence", options={"mapping": {"agence_slug":"slug"}})
    */
	public function newAction(Agence $agence, Request $request)
    {
		$em = $this->getDoctrine()->getManager();
		$travel = new Travel();
		$form = $this->createForm(new TravelType($agence), $travel);

		if ($request->getMethod() == 'POST')
		{
			//...
		}

        return $this->render('AppBundle:Dashboard/Travel:new.html.twig',
		array(
			'form'   => $form->createView() ,
			'agence' => $agence,
			));
    }

	/**
    * @ParamConverter("agence", options={"mapping": {"agence_slug":"slug"}})
	* @ParamConverter("travel", options={"mapping": {"travel_id":"id"}})
    */
    public function editAction(Travel $travel, Agence $agence, Request $request)
	{

		$em = $this->getDoctrine()->getManager();

		$form = $this->createForm(new TravelEditType($agence), $travel);
		
		if ($request->getMethod() == 'POST')
		{
			//...
		}

        return $this->render('AppBundle:Dashboard/Travel:edit.html.twig',
		array(
			'form' => $form->createView() ,
			'travel' => $travel,
			'agence' => $agence,
			));
    }

**travelType** and it works good

    namespace AppBundle\Form;

    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use Symfony\Component\Form\FormEvents;
    use Symfony\Component\Form\FormEvent;

    //........
    use Symfony\Component\Form\FormInterface;
    use AppBundle\Entity\Country;

    class TravelType extends AbstractType
    {
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
      
      ->add('country', 'entity', array(
         'required' => true,
         'class' => 'AppBundle:Country',
         'property' => 'en',
         'multiple' => false,
         'expanded' => false,
         'label' => 'ِCountry',
         'empty_value' => ''ة ))
      //....
      
      $formModifier = function (FormInterface $form, Country $country = null) {
            $cities = null === $country ? array() : $country->getCities();

            $form->add('destination', 'entity', array(
                'class'       => 'AppBundle:CityWorld',
                'choices'     => $cities,
                'multiple' => false,
                'expanded' => false,
                'property'    => 'name',
                'label' => 'Destination'));
        };

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier) {
                // this would be your entity, i.e. SportMeetup
                $data = $event->getData();

                $formModifier($event->getForm(), $data->getCountry());
            }
        );

        $builder->get('country')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                // It's important here to fetch $event->getForm()->getData(), as
                // $event->getData() will get you the client data (that is, the ID)
                $country = $event->getForm()->getData();

                // since we've added the listener to the child, we'll have to pass on
                // the parent to the callback functions!
                $formModifier($event->getForm()->getParent(), $country);
            }
        );

        $builder->addEventListener(FormEvents::POST_SUBMIT, function ($event) {
            $event->stopPropagation();
        }, 90000000000000); // Always set a higher priority than ValidationListener

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Travel'
        ));
    }

    public function getName()
    {
        return null;
    }
    }

This is **TravelEditType**

    namespace AppBundle\Form;

    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use Symfony\Component\Form\FormEvents;
    use Symfony\Component\Form\FormEvent;
    //........
    use Symfony\Component\Form\FormInterface;
    use AppBundle\Entity\Country;

    class TravelEditType extends TravelType
    {
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
	    parent::buildForm($builder, $options) ;
		
     }

     public function getName()
     {
        return null;
     }
    }

This is the form and javascript code
    
    
    <form method="post" action="" class="form-horizontal" role="form" {{ form_enctype(form) }} >

     {{ form_widget(form.country, { 'id': 'country' }) }}

     {{ form_widget(form.destination, { 'id': 'city' }) }}
    
    //.............
    </form>

    <script type="text/javascript">
	var $county = $('#country');

	$county.change(function () {
		// ... retrieve the corresponding form.
		var $form = $(this).closest('form');

		var data = {};
		data[$county.attr('name')] = $county.val();
		// Submit data via AJAX to the form's action path.
		$.ajax({
			url: $form.attr('action'),
			type: $form.attr('method'),
			data: data,
			success: function (html) {
				// Replace current position field ...
				$('#city').replaceWith(
						// ... with the returned one from the AJAX response.
						$(html).find('#city')
				);
				// Position field now displays the appropriate positions.
			}
		});
	});
</script>

I the code is as the example Dynamic Generation for Submitted Forms in the documentation http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html#cookbook-form-events-submitted-data

**Comment by jakzal** [comment]
I'm terribly sorry to close this, but we only use github for bugs and features.

Please ask support questions on the mailing list or use other [available channels](http://symfony.com/mailing-lists).
