### ISSUE TITLE
Asset problem

### ISSUE THREAD

**Issue by clementlyon** [symfony/symfony#13669]
I have an error with the last version of the devel branch (commit f82fc7684b) :

Twig_Error_Syntax in ExpressionParser.php line 568: The function "asset" does not exist in "base.html.twig" at line 7

It seems that the "made the assets optional" previous commit maked this error...

Any idea ?

**Comment by stof** [comment]
@clementlyon can you try again ?

**Comment by clementlyon** [comment]
I have still the error...

In fact the problem is in touch with the symfony/framework-standard-edition

I launch

composer create-project symfony/framework-standard-edition . 2.7.x-dev

And the error is the same
 Twig_Error_Syntax in ExpressionParser.php line 568: The function "asset" does not exist in "base.html.twig" at line 7

In ./app/Resources/views/base.html.twig we have 

<link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />

And I think this cause trouble...

Maybe now in the symfony/framework-standard-edition the optional assets must be fix ?

**Comment by xabbuh** [comment]
Should be fixed once that #13672 is merged.

**Comment by clementlyon** [comment]
Thanks, it works fine now with #13672 merge !
