### ISSUE TITLE
[Form] Translate timezones in TimezoneType

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#13662]
Just as LanguageType etc provide translated options, the TimezoneType should as well. It could do so using http://php.net/manual/en/intltimezone.getdisplayname.php (PHP >= 5.5).

`IntlTimeZone::getDisplayName` returns the same name for each UTC offset. So we probably would not display it for each timezone but instead allow grouping over different things. I'd suggest to add some form of grouping option that can be `region|country|name|offset`.
- region (default): stays as currently done, e.g. `Europe`
- country: group by `DateTimeZone::getLocation()['country_code']` and translate with `Locale::getDisplayRegion`
- name: group by `IntlTimeZone::getDisplayName`, e.g. `Central European Standard Time (CET)`
- offset: group by `IntlTimeZone::getRawOffset` as `UTC+x`

With #12148 it would be easy to implement by just setting a default `group_by` closure that - based on the above option - calls the appropriate methods.

**Comment by Tobion** [comment]
Some tests: http://3v4l.org/bsRXL#v5512

**Comment by stof** [comment]
> With #12148 it would be easy to implement by just setting a default group_by closure that - based on the above option - calls the appropriate methods.

even better implementation: setting a default ``group_by`` which chooses the right grouping closure based on the other option instead of choosing each time a timezone is grouped

**Comment by rvanlaak** [comment]
Did some related changes myself, found out that quite some countries only have one timezone. That would make grouping them by country less useful. 

We decided not to group by offset, but to sort by offset. There even are offsets of 15 minutes, so that also made grouping quite unclear.

So I'd say that the only useful grouping would be to group by region or name. :+1:

**Comment by c960657** [comment]
PR #17628 adds a translations of all time zones names.

I agree that the UX of the timezone picker can be improved, but this is a separate issue whose solution is not obvious, so I suggest we restrict this ticket to the actual translation of the English city names.

**Comment by Tobion** [comment]
Closing as this can be implemeted user-land easily and it's not definite which values to use e.g. short or long display name.
