### ISSUE TITLE
Form Validation (handleRequest, submit)

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#13663]
It seems to be impossible to create a form type which got dynamicly modified fields (http://symfony.com/doc/2.3/cookbook/form/dynamic_form_modification.html), which and using validation. This is cause the validation get triggered on handleRequest or submit instead of on isValid. Which means i can choose between submit the data and get errors or not submit em, and got old form informations.

**Comment by dominikzogg** [comment]
http://symfony.com/doc/2.3/cookbook/form/dynamic_form_modification.html#suppressing-form-validation would probably help if the form type is not embedded

**Comment by jakzal** [comment]
Could you give an example, including an expected and the actual behaviour?

**Comment by dominikzogg** [comment]
@jakzal 

Well lets take a form type like the one within the symfony doc and add a submit button.

```{.php}
// src/AppBundle/Form/Type/SportMeetupType.php
namespace AppBundle\Form\Type;

// ...
use Symfony\Component\Form\FormInterface;
use AppBundle\Entity\Sport;

class SportMeetupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('sport', 'entity', array(
                'class'       => 'AppBundle:Sport',
                'empty_value' => '',
            ));
            ->add('submit', 'submit)
        ;

        $formModifier = function (FormInterface $form, Sport $sport = null) {
            $positions = null === $sport ? array() : $sport->getAvailablePositions();

            $form->add('position', 'entity', array(
                'class'       => 'AppBundle:Position',
                'empty_value' => '',
                'choices'     => $positions,
            ));
        };

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier) {
                // this would be your entity, i.e. SportMeetup
                $data = $event->getData();

                $formModifier($event->getForm(), $data->getSport());
            }
        );

        $builder->get('sport')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                // It's important here to fetch $event->getForm()->getData(), as
                // $event->getData() will get you the client data (that is, the ID)
                $sport = $event->getForm()->getData();

                // since we've added the listener to the child, we'll have to pass on
                // the parent to the callback functions!
                $formModifier($event->getForm()->getParent(), $sport);
            }
        );
    }

    // ...
}
```

Within a sample controller we do something like this:

Controller:

```{.php}
$form = $this->createForm(new SportMeetupType(), $entity);
if('POST' === $request->getMethod()) {
    $form->handleRequest($request);
    if($form->get('submit')->isClicked()) {
        if($form->isValid())
        {
            ....
        }
    }
}
```

Know add a javascript logic which listen on each change of the field sport and submit the form (without click the button submit).

Based on the method name this should work fine, cause it seems the validation events get triggered on `isValid`, but this is allready happened at the `handleRequest` which means there are probably some validators fail.

**Comment by jakzal** [comment]
I'm not sure if I understand you.

> Based on the method name this should work fine, cause it seems the validation events get triggered on isValid,

This assumption is wrong. 

Getter methods (those prefixed with *get*, *is*, *has* etc), usually do not perform any operations and do not have side effects. Their purpose is to return or check the state. 

Methods that actually do the work are usually verbs, that reflect operations (actions) - like `validate`, `submit` or `handleRequest`.

**Comment by dominikzogg** [comment]
@jakzal i know that isValid does nothing, and thats whats wrong in my view, cause this way its not possible to perform just a js submit without validation (to get context related entity in this case), even if i don't want it, until the "real" submit button get called. The only way is to erase all ->errors on each form and subform with a reflection, which is more than weird.

**Comment by ogizanagi** [comment]
Can't you just skip validation using a inexistant validation group if the request comes from js ?

**Comment by dominikzogg** [comment]
@ogizanagi This helps as long i add a hidden field if there is no choices on dynamic field

```{.php}
$formModifier = function (FormInterface $form, $country) {
    $cantons = Address::getPossibleCantons($country);
    if(count($cantons) > 0) {
        $form->add('canton', 'choice', array(
            'required' => false,
            'choices' => $cantons,
        ));
    } else {
        $form->add('canton', 'hidden', array('mapped' => false));
    }
};
```

**Comment by ma-gu-16** [comment]
is this still the way to go? or is there any other solution ? ive got the same problem actually. 

i want to show new form elements after submit without validation this new just appeard empty elements. with second submit it has to be validated.  

thank you.
