### ISSUE TITLE
[Validator] Callback Constraint - No violations

### ISSUE THREAD

**Issue by david-fanin** [symfony/symfony#13664]
Hello!

I think there a bug with the "callback" constraint. Indeed, the "getViolations" method returns no violations whereas the "not blank" constraint is not satisfied.

This is a very simplified version of my code:

```php
class User
{
	// ...

	public static function loadValidatorMetadata(ClassMetadata $metadata)
	{
		$metadata->addGetterConstraint('email', new Assert\NotBlank(array(
			'groups' => array(
				'connexion',
			),
		)));

		// ...

		$metadata->addConstraint(new Assert\Callback(array(
			'callback' => 'checkUser',
			'groups' => array(
				'connexion'
			),
		)));
	}

	public function checkUser(ExecutionContextInterface $context)
	{
		var_dump($context->getViolations());// Prints "array()"
	}
	
	// ...
}
```

**Comment by webmozart** [comment]
Hi @david-fanin, thank you for reporting this issue! What you experience is not a bug. You cannot rely on the constraints being executed in any particular order. Hence you also cannot check whether a constraint caused an error from the validator of another constraint.

The only mechanism to enforce validation in a particular order is a group sequence. [Read the documentation](http://symfony.com/doc/current/book/validation.html#group-sequence) for more information about that.

In your case, the code would probably look something like this:

```php
class User
{
    // ...

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addGetterConstraint('email', new Assert\NotBlank(array(
            'groups' => 'email',
        )));

        // ...

        $metadata->addConstraint(new Assert\Callback(array(
            'callback' => 'checkUser',
            'groups' => 'checkUser',
        )));

        $metadata->setGroupSequence(array('email', 'checkUser'));
    }

    public function checkUser(ExecutionContextInterface $context)
    {
        // Only called if constraints in group "email" succeeded
    }

    // ...
}
```

**Comment by david-fanin** [comment]
Hi, thank you for your reply. The given solution works!

However, I also used this solution for an another case where I have an "Assert\True" instead of an "Assert\Callback" and it does not work in this case. And yet, I have followed the example of the documentation.

My code :
```
class User
{
    // ...

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addGetterConstraint('email', new Assert\NotBlank(array(
            'groups' => array(
                'requestPassword',
            ),
        )));

        $metadata->addGetterConstraint('matchUserEmail', new Assert\True(array(
            'groups' => array(
                'requestPassword2',
            ),
        )));

        $metadata->setGroupSequence(array(
            'User',
            'requestPassword',
            'requestPassword2',
        ));
    }

    // ...
}
```

I pass the following groups to the "CreateForm": `array('requestPassword', 'requestPassword2')`

I made a mistake?

My symfony version is 2.6.6.
