### ISSUE TITLE
Translator performance

### ISSUE THREAD

**Issue by theUniC** [symfony/symfony#13676]
Hi,

I wonder if there is any way to use custom Message Catalogues in the Translator component. I've found that the default implementation is unusable when there are lots of translations (actually, I'm working with ~7 Mb of translation generated files in several locales). I've been googling a lot, but not been able to find documentation regarding this topic.

Thanks.
Christian.

**Comment by jrobeson** [comment]
i think if you could generate a profile with xdebug or xphrof that would probalby help the team figure out the bottlenecks.

**Comment by jakzal** [comment]
or... profile your app with [blackfire](https://blackfire.io/) and share the profile with us.

**Comment by theUniC** [comment]
The case is that each time I've to retrieve a translation, the translation service not only loads the validation, form, security and routing translations, but it has to load around ~100Mb of additional translations in memory. Just to retrieve a single translation in a single language.

**Comment by Tobion** [comment]
See #2570

**Comment by ostrolucky** [comment]
This issue seems outdated, there have already been PRs which improve performance. ping @javiereguiluz

**Comment by javiereguiluz** [comment]
OK, let's close as "fixed" ... and we can create new issues for other specific issues about translator performance. Thanks!
