### ISSUE TITLE
[ExpressionLanguage] Extract compiling logic from nodes

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#13682]
I've an use case where I need to compile expressions in other languages such as Javascript. Symfony Expression Language is language agnostic.

For now, I've implemented a visitor to traverse the node tree and compile in other languages but would be nice to have a interface for implementing my own compiler logic.

Any other suggestion?

**Comment by fabpot** [comment]
ExpressionLanguage is not really language agnostic as it does provide an evaluation mode which is only for PHP. So, providing a way to compile into other language without the evaluation part would look weird at best. I think that your current way is actually the best thing to do.

**Comment by marcospassos** [comment]
Fabien, thanks for your thoughts. However, I belive there is another way to
look at this. The compilation part may be language agnostic once the
evalution only makes sense at PHP level. You may want to evaluate your
expression no matter the language you want to compile to. For a given
parameter set, the evaluation result must be the same, independently of the
language you're compiling to. In that way, the result of compilation is the
evaluation for other languages itself.

Em segunda-feira, 16 de fevereiro de 2015, Fabien Potencier <
notifications@github.com> escreveu:
