### ISSUE TITLE
[Routing] Optimize the way the UrlMatcher is generated

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#13681]
It follows  #12099.
 
This matcher is IMO really dirty.

It searches for routes with a whole bunch of methods, hosts and all, and even if each route is different in its requirements, we know that there are a "fix" amount of requirement types which can all have their own "priority", each with a wildcard `*` to allow non-required elements.

Here is an example of a priority usage (all beginning with wilcard check, and after that, specific check):
- host
    - prefix
        - methods
            - requirements

This may creates a few duplicates for multiple methods, but it may get rid of these old and dirty `goto` inside the matcher for example. The best point IMO is that it would really more "flatten" the matcher.
 
I don't know if this issue is relevant enough for Symfony, but feel free to close it if it really does not suit :)

**Comment by Tobion** [comment]
What exactly are you proposing? Please clarify with code snipped or a PR. Also how is this related to the referenced ticket?

**Comment by fabpot** [comment]
I'm closing this ticket even if optimization is a good topic; but rhetorical issues do not help. The only way to make things better is to actually propose some changes and prove that it would make things faster for most users.
