### ISSUE TITLE
WebProfiler timeline: define custom categories / colors

### ISSUE THREAD

**Issue by nickygerritsen** [symfony/symfony#13680]
The WebProfilerBundle timeline currently defines the categories (and colors) used in `@WebProfiler/@WebProfiler/Collector/time.html.twig`.

However, we want to add a custom category to it (because we added a custom data collector using the stopwatch service).

Although it is technically possible to overwrite the whole template in `app/Resources`, this is not really easy for two reasons:

* You can not include the parent template (right? I get maximum function nesting errors), so you must overwrite everything
* We are developing a bundle for others to use that would automatically add the category to the timeline and we thus can not add things in `app/Resources`

I think it would be better to have some way to configure these colors outside of the template.

**Comment by fabpot** [comment]
I did not make the colors configurable back then as it's quite rare that people add many different kind of information on the graph. It just does not seem worth the effort.

**Comment by nickygerritsen** [comment]
The problem now is mostly that I can not add an extra category, as only the categories in the colors-list are used :)

**Comment by jeremyFreeAgent** [comment]
An easy quick win should be adding some basic colors like that:
```
{% if colors is not defined %}
    {% set colors = {
        'default':                '#aacd4e',
        'section':                '#666',
        'event_listener':         '#3dd',
        'event_listener_loading': '#add',
        'template':               '#dd3',
        'doctrine':               '#d3d',
        'propel':                 '#f4d',
        'child_sections':         '#eed',
        'blue':                   '#0ff',
        'red':                    '#f00',
        'yellow':                 '#ff0',
    } %}
{% endif %}
```
What do you think?

**Comment by nickygerritsen** [comment]
I guess this would already be more useful.

Would another easy idea not be to move the `{% set colors = ... } %}` to a separate twig file? Then we can override only that one.

**Comment by jeremyFreeAgent** [comment]
@nickygerritsen IMHO moving it in another file only to override seems weird.

**Comment by nickygerritsen** [comment]
Why is that? By default it still has the same settings as normal but then I can overwrite it in `app/Resources` without overwriting the whole twig file

**Comment by jeremyFreeAgent** [comment]
I think the best way to do what you want should be adding a configuration for colors in the WebProfilerBundle...

**Comment by nickygerritsen** [comment]
Yes this seems the nicest way, but @fabpot seems to think something like that would not be worth the effort :)

**Comment by stof** [comment]
@fabpot third-party bundles might include their own stopwatch events. And currently, the core hardcodes a bunch of colors, including for things which are not in core (propel queries for instance)

**Comment by okdewit** [comment]
+1.

Currently writing a reusable bundle which performs various time-consuming tasks, and profiling is a must. 
This bundle is meant for distribution via composer, and I want third-party users to have the option to be able to clearly distinguish which of their actions should be optimised, in the same way Doctrine profiling currently works.

**Comment by javiereguiluz** [comment]
I propose to close this issue as "won't fix". The small benefit provided would require us to complicate the code a lot.

---

The solution is to use the sections and categories provided by the Stopwatch component. For example, KnpMenuBundle does this right:

1) It defines several sections and categories in their stopwatch events:

![stopwatch_events](https://cloud.githubusercontent.com/assets/73419/12445763/85cebaf2-bf66-11e5-9b75-0d6ee498a602.png)

2) The timeline displays several Knp sections and inside of them, the different events:

![timeline](https://cloud.githubusercontent.com/assets/73419/12445775/996855d2-bf66-11e5-8118-23bd6f850911.png)

The only limitation is that you can't change the color of your sections, but you can create as many sections as needed.

**Comment by jeremyFreeAgent** [comment]
Usage of sections seems suitable.
