### ISSUE TITLE
Problems with Locale::getDefault() in Entity? [Always empty]

### ISSUE THREAD

**Issue by toolpixx** [symfony/symfony#13695]
I have i little bit trouble with:

```php
#Entity/User.php
...
use Symfony\Component\Locale as Locale;
...
public function getLocale() {
        return (null !== $this->locale) ? $this->locale : Locale::getDefault();
}
```

but the follow is work for me, but isn't the value from my config.yml. It is the default value from my php.ini.

```php
#Entity/User.php
...
use Symfony\Component\Locale as Locale;
...
public function getLocale() {
        return (null !== $this->locale) ? $this->locale : locale_get_default();
}
```

Is that a bug or correct? Or how i can get the default-locale in my entity?

Thanks and regards
Andreas

**Comment by Tobion** [comment]
There is no such class `Symfony\Component\Locale`. You probably mean `\Locale`
