### ISSUE TITLE
Bad {@inheritdoc} usage?

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony#13696]
According to [the current PHPDoc standard](http://phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag) and upcoming [PSR-5](https://github.com/php-fig/fig-standards/pull/169/files), the `{@inheritdoc}` tag is misused in Symfony code base.

It should be used to import the description of a parent class/method/property in a the description of the child class but not to explicitly mark the doc as inherited (it's implicit).

Example of current usage in Symfony (bad):
```php
/**
 * The interface description.
 */
interface MyInterface
{
}

/**
 * {@inheritdoc}
 */
class Child implements MyInterface
{
}
```

Example of usage conforming to PHPDoc standards:
```php
/**
 * The interface description.
 */
interface MyInterface
{
}

// the doc will be automatically inherited
class Child implements MyInterface
{
}
```

This is espicially annoying when trying to extract the applicable documentation with standard parsers such as [phpDocumentator Reflection](https://github.com/phpDocumentor/Reflection).
For first case (Symfony), it will return `{@inheritdoc}`. For the second example `The interface description.` as intended.

I think it can be fixed on the whole code base using a simple `sed` command. What do you think about that?

**Comment by WouterJ** [comment]
I believe the reason for the `{@inheritdoc}` usage in the Symfony code base is to make a difference between not documented methods and those that are inherited.

E.g. if you where looking at a very vague named method in the `Child` source code (there is a high change this can happen) and there was no PHPdoc, you would just assume that this method is not documented and that you're left with the hard job of finding out what the method does. However, when you see `{@inheritdoc}`, you know that you just have to look at `MyInterface`.

Also note that Sami, the PHPdoc parser used and created by Symfony community, is able to parse `{@inheritdoc}` correctly.

Please note this sentence in the phpDocumentor documentation you linked to:

 > Currently some applications have DocBlocks containing just the {@inheritDoc} inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.

 > However, it does make clear that an element has been explicitly documented (and thus not forgotten). **As such we are working to include a new (normal) tag in the PHPDoc Standard @inheritDoc that will serve that purpose.**

So I would propose to not remove these and just wait for this progress and update it if there is a new standard tag for this.

**Comment by dunglas** [comment]
@WouterJ I'm aware of the behavior of SAMI but unlike phpDocumentator it is not usable as a standalone library to extract metadata from classes.
I fully agree with the need of marking an element as explicitly documented. Maybe using the non-standard ˋ@inheritDoc` tag (as stated in your quote) instead of the current "reassignment" would be better (not break current libraries). Another solution is to patch phpDocumentator Reflection to support the Symfony convention but not sure that they will be happy to break the standard.

For the use case background, I'm creating a component to extract the type of a property from it's metadata (Doctrine ORM mapping, setter typehint, Symfony validator mapping or... phpDoc): http://github.com/dunglas/php-property-info

**Comment by fabpot** [comment]
I'm closing this issue for now as we are indeed using the tag to mark methods as being documented (via inheritance.) So, removing those tag now is out of question. Whenever there is a clear standard that emerges with a proper solution for our use case, I would more than happy to reconsider this issue, but until then, there is nothing we can do.
