### ISSUE TITLE
Symfony logout under HHVM does not work.

### ISSUE THREAD

**Issue by damiencal** [symfony/symfony#13709]
I am unable to logout using the default symfony 2.6 (+Security Bundle) user authentification under HHVM but works perfectly under PHP5-FPM 5.5.9

**Comment by WouterJ** [comment]
I'm unable to reproduce this using the standard `form_login` and `logout` setup. I can perfectly login and logout using the configured URLs.

I'm using HHVM 3.5.1 on Ubuntu 14.04 (homestead).

Can you please fork the [standard edition](https://github.com/symfony/symfony-standard) and add the minimal code needed to reproduce your issue (and also some details on what "does not work" means)?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.

@damiencal Feel free to reopen when you can provide more information.
