### ISSUE TITLE
`error_bubbling` fails on `inherit_data` form in embedded form

### ISSUE THREAD

**Issue by marfillaster** [symfony/symfony#13702]
Given 
A as top-level form
B as embedded form of A
C with inherit_data form of B
Where C `error_bubbling` set to false.

Unmapped error of C bubbles up to A

Known affected
`"symfony/symfony": "~2.6"`

**Comment by javiereguiluz** [comment]
@marfillaster I'm sorry we didn't reply to you on time. I'd like to ask you if you can reproduce the reported issue in a Symfony version which is currently supported (2.7 or higher). Thanks!

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.

@marfillaster Feel free to provide more information and we can reopen here.
