### ISSUE TITLE
[DX] [Form] form isSubmitted isValid

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#13706]
Hi,

According to the [symfony best practices part on form] (http://symfony.com/doc/current/best_practices/forms.html#handling-form-submits)
 it could be great to only have one function to do the "job" of this part

before
``` if ($form->isSubmitted() && $form->isValid()) {} ```

after
``` if ($form->isSubmittedAndValid()) {} ```

I know the the isSubmitted is only here so that the logic is more understandable when reading, but is redundant to write both, no?

**Comment by jakzal** [comment]
Technically `isValid()` is `isSubmittedAndValid()`. We can't change the name before 3.0 though.

**Comment by 94noni** [comment]
I know, that, so why to put the isSubmitted in the doc, devs are maybe going to use both methods for nothing at the end :) 
Anyway, thank you

**Comment by javiereguiluz** [comment]
@94noni the last paragraph of the Forms chapter of the Best Practices book explains why we use that method:

```
Second, we recommend using $form->isSubmitted() in the if statement for clarity. 
This isn't technically needed, since isValid() first calls isSubmitted(). But without 
this, the flow doesn't read well as it looks like the form is always processed (even 
on the GET request).
```

**Comment by 94noni** [comment]
Hi @javiereguiluz , 
I know but as a dev, writing two methods when one is useless its kind of boring :)
that is why I asked here why not create a single method to do the job of both if the readability is needed?
ty

**Comment by javiereguiluz** [comment]
@94noni ok, now I understand you :)  And you are right ... and sadly, @jakzal is also right and we cannot change this until Symfony 3.

**Comment by 94noni** [comment]
Fine, just asking if possible for the future (3.0)
personally I used to only check the valid, but for new comers, I'm sure that this kind of best practices will bored them ;)
I close tis issue, thank you both
