### ISSUE TITLE
addXxx() and removeXxx() not being called when using ArrayCollection

### ISSUE THREAD

**Issue by Falc** [symfony/symfony#13705]
I have found a weird behaviour related to forms, adders/removers and ArrayCollection.

My app has two main entities: `Server` and `IP`. I've defined a OneToMany association in Server and a ManyToOne association in Entity. I have omitted unrelated (but working) code, so it looks like this:

```php
class Server
{
    /**
     * @ORM\OneToMany(targetEntity="IP", mappedBy="server")
     */
    protected $ips;

    public function __construct()
    {
        $this->ips = new ArrayCollection();
    }

    public function addIP(IP $ip)
    {
        $this->ips[] = $ip;
        $ip->setServer($this);

        return $this;
    }

    public function removeIP(IP $ip)
    {
        $this->ips->removeElement($ip);
        $ip->setServer(null);
    }

    public function getIPs()
    {
        return $this->ips;
}
```

```php
class IP
{
    /**
     * @ORM\ManyToOne(targetEntity="Server", inversedBy="ips")
     * @ORM\JoinColumn(name="server_id", referencedColumnName="id")
     */
    protected $server;

    public function getServer()
    {
        return $this->server;
    }

    public function setServer(Server $server = null)
    {
        $this->server = $server;

        return $this;
    }
}
```

An IP can be asigned to a server and a Server can have many IPs assigned. The IP entity is the owning side since the ManyToOne association is defined there.

The goal is to allow to assign/unassing IPs in the Server form. The ServerType looks like this:

```php
class ServerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('ips', 'collection', [
            'label'         => 'IPs:',
            'type'          => 'entity',
            'options'       => [
                'class' => 'ServerTestAppBundle:IP'
            ]
        ]);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class'    => 'ServerTest\AppBundle\Entity\Server'
        ]);
    }

    public function getName()
    {
        return 'servertest_server';
    }
}
```

The problem happens when editing a Server and assigning an IP. The form is valid and I can see (using `dump()`) that the `Server::$ips` ArrayCollection contains the new IP, but `IP::$server` is null so the association is not stored in the database because `IP::$server` is the owning side.

I thought the IPs were being assigned to the Server through `Server::addIP($ip)`, that would fix the owning/inverse problem because `addIP($ip)` sets the Server through `$ip->setServer($this)`. But neither `addIP()` nor `removeIP()` are being used.

But when `getIPs()` returns an array instead of an ArrayCollection everything works perfectly, `addIP()` and `removeIP()` are called and the association is stored in the database:

```php
class Server
{
    public function getIPs()
    {
        // Return as array ensures addIP() or removeIP() are called
        return $this->ips->toArray();

        // Return as ArrayCollection omits addIP() and removeIP()
        //return $this->ips;
    }
}
```

It seems that Symfony finds the add() and remove() methods from ArrayCollection and omits the ones defined in the entity, but uses them when they are not found (array). It is probably related to the PropertyAccessor component.

Is this a normal behaviour?
If that is the case, how could I add have custom adder an remover methods?

**Comment by stof** [comment]
you need to set the ``by_reference`` option to ``false`` in your collection field to tell Symfony it should call the adder and remover on the parent instead of modifying the collection by reference (by default, objects are changed by reference instead of calling a method on the parent in the object graph)

**Comment by Falc** [comment]
Initially I did set the by_reference option to false before opening the issue. I have tested it again with by_reference => false and the problem persists. I have a `dump()` in both `addIP()` and `removeIP()` and they are only called when `getIPs()` returns an array, but not when returning an ArrayCollection.

**Comment by dmaicher** [comment]
So this does not work?

```
$builder->add('ips', 'collection', [
            'label'         => 'IPs:',
            'type'          => 'entity',
            'by_reference' => false,
            'options'       => [
                'class' => 'ServerTestAppBundle:IP'
            ]
        ]);
```

**Comment by Falc** [comment]
I have been doing changes in the code these weeks. `ips` is no longer mapped as collection but as entity and IPs are attached to a server through ajax requests, and it works now adding `by_reference`.

Not sure if some other changes made the difference, so I am closing the issue for now.
