### ISSUE TITLE
remember me cookie is not invalidated/deleted on password change, credential expiration

### ISSUE THREAD

**Issue by gondo** [symfony/symfony#13712]
**scenarion:**
1. user log in with selected remember me. remember me cookie is created
2. administrator on different computer change user password, or set credentials as expired
3. user is still logged in until remember me cookie expire

**expected:**
once administrator change user password or set credentials as expired, user should be logged out and remember me cookie should be invalidated.

is there a way to make this happen on password change?

**Comment by jaytaph** [comment]
These things should be checked when creating a `RememberMeToken` (by calling `setUser`, which in turn calls the private `hasUserChanged` method). If anything has changed in the user data, it should set the rememberme-token to unauthenticated (password, salt, locked out etc).

I'm not 100% sure.. but it seems that in the in `rememberMeToken` constructor, the setUser is called correctly, but on the next line, it calls `parent::setAuthenticated(true);`, which set the rememberme cookie to be authenticated, even if the `setUser()` decided this wasn't the case.

I'm not able to dive into this at the moment, but maybe somebody could verify if this is the issue?

**Comment by gondo** [comment]
it seems like that in all implementation of `AbstractToken` use wrong logic.
all of them include this code:
```
$this->setUser($user);
parent::setAuthenticated(true);
```
what means that any previous result of `hasUserChanged` is being ignored.
BUT the catch is in the fact, that `hasUserChanged` is first called by `setUser`, called from `refreshUser` from `Symfony\Component\Security\Http\Firewall\ContextListener`
this first call of `setUser` properly check `hasUserChanged` and **sets the user**

that mens, any other call to `hasUserChanged` will always return `false` because of the check inside the function `if (null === $this->user) {`. this will always be `true` as user was already set.

that means, that even if we change the order of functions in class extending `AbstractToken` (f.e. in `RememberMeToken` to this order:
```
parent::setAuthenticated(true);
$this->setUser($user);
```
nothing will be solved, as secondary call to `setUser` will always pass `hasUserChanged` check.

the main problem is, that once `hasUserChanged` calls `$this->setAuthenticated(false);` than this triggers `RememberMeToken`. so even if there was some additional call to `hasUserChanged` inside `RememberMeToken` and this would again call `$this->setAuthenticated(false);`, this would again trigger `RememberMeToken` and there would be never ending cycle.

the proper solution should be, that once `hasUserChanged` decides to set `$this->setAuthenticated(false);`, than none of the `.. extends AbstractToken` should be called, and user should be logged out.

**Comment by gondo** [comment]
isn't this serious security bug? ping @fabpot @stof

**Comment by gondo** [comment]
i looked into this little more and here is what i found:
`hasUserChanged` is checking this:
- isAccountNonExpired
- isAccountNonLocked
- isCredentialsNonExpired
- isEnabled

`checkPreAuth` is checking this:
- isAccountNonExpired
- isAccountNonLocked
- isEnabled

`checkPostAuth` is checking this:
- isCredentialsNonExpired

**the problem** is, that when user is logged via `RememberMeToken` than `checkPostAuth` is not called and therefore `isCredentialsNonExpired` is never properly checked.

also it looks like that when user is logged via `RememberMeToken` the password is not checked, therefore there is no way to determine if password was changed. that means, that when changing use `password` we have to update somehow invalidate Remember me cookie. and that was/is my original problem. currently, there doesnt seems to be a way to do this.

**Comment by gondo** [comment]
ok, after even more debugging i figured out, that everything works as it should :)
the problem was, that when i was doing initial check with changing password and determining if user will be disconnected using remember me cookie, i was in fact checking user validating against PHP session and not against Remember me cookie.
there is `check hash` functionality when decoding cookie, what checks password.

however i am still not sure how the `isCredentialsNonExpired` should work, as `checkPostAuth` nor `isCredentialsNonExpired` are called when user is authenticated via Remember Me cookie
