### ISSUE TITLE
Get entity metadata in form extension

### ISSUE THREAD

**Issue by NovikovViktor** [symfony/symfony#13719]
Hello, I try to get entity metadata in form extension in my `buildView()` methood. When I do this:
` $entityMetadata = $this->validator->getMetadataFactory()->getMetadataFor('Acme\DemoBundle\Entity\Post');`, all works fine. But when I want to get class name from form config, like: 
`
$config = $form->getConfig();
$formData = $config->getDataClass(); // it equal to 'Acme\DemoBundle\Entity\Post'
`
But when I do this:
` $entityMetadata = $this->validator->getMetadataFactory()->getMetadataFor($formData);` , it throw me next error:
`Cannot create metadata for non-objects. Got: NULL`. I already read the many articles about that, but I didnt find any solution, except that I need to use dev Symfony2 version, where this but is fixed. Its true? Or I am doing something wrong?

**Comment by WouterJ** [comment]
`MetadataFactory#getMetadataFor()` will throw this exception only when the passed argument is not an object and not a string. From the exception message, we see you passed `null`.

This means that the `data_class` option is not explicitely set and the passed data is not an object (as the `data_class` will be derived from the passed data if not set). Can you please do a `var_dump($form->getData())` to see what the passed data is?

**Comment by NovikovViktor** [comment]
@WouterJ, yes I found that. Actualy `_token` field does not have any `data_class`. So thats all. Thanks for reply.

**Comment by WouterJ** [comment]
@NovikovViktor can you then please close this issue as it's solved?
