### ISSUE TITLE
[FrameworkBundle] Undefined index: templating

### ISSUE THREAD

**Issue by ddeboer** [symfony/symfony#13710]
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L59 assumes the `templating` key to be available, but shouldn’t there be an `isset` check, as `templating` can be optional?

**Comment by jakzal** [comment]
Good spot! I went back and forward with the condition in `ifTrue()` and this condition got eventually removed.
