### ISSUE TITLE
[PropertyAccess] Add french singular for words like typologies > typologie

### ISSUE THREAD

**Issue by CaporalDead** [symfony/symfony#13723]
Hi,

We just encountered a problem while using 'by_reference' attribute as false in a form which caused a NoSuchPropertyException because the StringUtil class in PropertyAccess doesn't handle correctly the case when for example you have "Typologies" (plural) that should be translated into "Typologie" and not "Typology".

I just add this case and a test case which covered the word "typologies" and it seems that it doesn't break other test cases.

I submit a PR #13721

**Comment by fabpot** [comment]
see #13721
