### ISSUE TITLE
PhpDumper always forces Expressions recompilation

### ISSUE THREAD

**Issue by davide-romanini** [symfony/symfony#13728]
I'm trying to convert the static/cached configuration of doctrine connections with a dynamic one, eg: in the static configuration I set some dummy values for db credentials but the real password is taken at runtime from a service call that for example reads the value from a env variable or other protected source. That allows also changing the variable without the need for cache clear.
The solution I'm testing involves creating a compiler pass overwriting all dbal connections definitions with an expression such as 'service("datasource_provider_service").getDataSource(...)'.
This works, but since I'm programmatically creating the expression I'd prefer to pass directly a ParsedExpression. And it fails, because PhpDumper *always* converts the Expression to string:

```
// PhpDumper 
...
} elseif ($value instanceof Expression) {
         return $this->getExpressionLanguage()->compile((string) $value, array('this' => 'container'));
}
```

There is a reason for that string cast?
Do you know for better native solutions to my specific use case (eg: arguments of a service "generated" dynamically from another service at runtime and never cached)?

**Comment by stof** [comment]
@davide-romanini all changes done in compiler passes are also cached. So just return a normal expression.
