### ISSUE TITLE
[Form] - CollectionType

### ISSUE THREAD

**Issue by zender** [symfony/symfony#13734]
I am trying to send string data to collection type form element EX: "1,2,3,4" then I hook to pre_submit event and trying to normalize the data like this: 
$data = is_string($event->getData()) ? explode(',', $event->getData()) : [];
$event->setData($data);

but event is not called and an exception is thrown instead:
"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Expected argument of type \"array or (\\Traversable and \\ArrayAccess)\", \"string\" given","class":"Symfony\\Component\\Form\\Exception\\UnexpectedTypeException"

I guess data type should be checked after pre_submit event is called otherwise I can not normalize the data.

Any advice?

thanks

**Comment by zender** [comment]
I found a fix - if I set priority to 1000 it works. Is that the normal behaviour?

**Comment by dosten** [comment]
Yes, you need to set your listener with a higher priority.

**Comment by zender** [comment]
thanks
