### ISSUE TITLE
[config] cannotBeEmpty does not work with booleanNode

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13736]
An issue that somebody found:

```
       $rootNode
            ->children()
                ->booleanNode('use_mock')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
```

when using:  use_mock: false in the config, it will throw a `InvalidConfigurationException`: `The path "config.use_mock" cannot contain an empty value, but got false.`

This will be thrown at line: https://github.com/symfony/symfony/blob/7185d50649e11d5f0c3191c85dd9af3e1d3b7e6f/src/Symfony/Component/Config/Definition/VariableNode.php#L87  where an `empty()` check on the boolean `false` will actually return true.

Is this a bug, or are there other ways to deal with booleanNodes in this situation?

Gist: https://gist.github.com/jaytaph/08906a3f38ca9f0867f8

(Same issue occurs when using a scalarNode() and using "0" as the config value)

**Comment by florianv** [comment]
What do you want to achieve ? This is the normal behavior of the `empty()` function: `false` is considered empty like `'0'` and some others like the empty string.

**Comment by jaytaph** [comment]
@florianv I understand how empty() works, and I understand how to work around this issue.

The main issue here, is that one does expect the functionality of "cannotBeEmpty" to make sure you must specify a value..  on a booleanNode, using either `true` or `false` are indeed values, and from a user point of view, you have complied to this rule.  The fact that is uses empty(),  is an implementation detail (a very deep implementation detail), that is not obvious, documented or otherwise from the outside world.

I would propose that `cannotBeEmpty()` either be documented better to emphasise that cannotBeEmpty *might* use `empty()` as an implementation detail, and therefore even supplying a perfectly correct value would still result in an exception, OR change the implementation to make sure that bool(false) or bool(true) will indeed work, as the name implies.

(there are precedents in this matter btw..  there is a FormUtil:isEmpty that evaluates empty arrays, and boolean(0) to true. In fact, it will only return false when data === null or when data === empty string. 
I think such a isEmpty() method this would be a much better match in this case as well..

**Comment by unkind** [comment]
> OR change the implementation to make sure that bool(false) or bool(true) will indeed work, as the name implies

Can you clarify what does "empty bool" mean for you?

**Comment by jaytaph** [comment]
Why is that?  Because cannotBeEmpty implies that you must specify a value. 'False' is indeed a value, even though an *implementation* decided otherwise.

It would be perfectly valid to ask the user to set an option on the config, which they must explicitly do so, without a default value. Imho, it makes no sense to me to be able to use cannotbeempty on a boolean, where you can only supply the value 'true'.

I would propose this to change. In a boolean context false is a perfectly valid option (in fact, it makes up 50% of the valid options).

**Comment by unkind** [comment]
> Why is that? Because cannotBeEmpty implies that you must specify a value.

`isRequired` does it.

**Comment by jaytaph** [comment]
Yes. You are correct. Cannotbeempty implies that the value cannot be empty. Specifying a value false, is in fact suplying a value.  The confusing part is that false is in this case threated as an empty. I understand that this is due to the implementation if empty(), but imho its not the same thing in this context

**Comment by SoboLAN** [comment]
I think @jaytaph is right and that this can be expanded to include any scalar value that the [empty()](https://php.net/manual/en/function.empty.php) function considers to be empty but is technically not (false, 0, 0.0, "0").

Shouldn't be too difficult to fix, although there are probably some corner cases (maybe in other Components ?) that rely on this behaviour. So extra care is probably needed here.

**Comment by WouterJ** [comment]
I agree that the current implementation is wrong. It's not only with `false`, but also with strings or numbers (the ones @SoboLAN showed). `numerOfX: 0` should not be invalid for an integer node with `->cannotBeEmpty()`. Currently, it is.

**Comment by xabbuh** [comment]
see #15170
