### ISSUE TITLE
[Validator] Email Validator does not work properly

### ISSUE THREAD

**Issue by filipgolonka** [symfony/symfony#13739]
Simple code:

    $email = 'email@domain.com@';
    $constraints = array(
        new \Symfony\Component\Validator\Constraints\Email(),
        new \Symfony\Component\Validator\Constraints\NotBlank()
    );

     $errors = $this->get('validator')->validateValue($email, $constraints);

     assert(count($errors) != 0);

This code is expected not to produce a warning, but it does.

**Comment by jakzal** [comment]
Could you paste the warning it produces please?

**Comment by filipgolonka** [comment]
PHP Warning:  assert(): Assertion failed in FILE on line LINE

The workaround is to enable strict validation and install egulias/email-validator:

    $email = 'email@domain.com@';
    $constraints = array(
        new \Symfony\Component\Validator\Constraints\Email(array(
            'strict' => true
        )),
        new \Symfony\Component\Validator\Constraints\NotBlank()
    );

     $errors = $this->get('validator')->validateValue($email, $constraints);

     assert(count($errors) != 0);

**Comment by SoboLAN** [comment]
I tried your code on the latest Symfony 2.6 release (2.6.4 to be more precise) and could not reproduce your issue.

`count($errors)` in my case is `0`.

What Symfony version did you use ?

**Comment by filipgolonka** [comment]
2.6.1. I will upgrade symfony in my project to 2.6.4 and will see, what happens. I will let here know, if the problem stil occurs.

**Comment by webmozart** [comment]
Closing due to lack of feedback.
