### ISSUE TITLE
PropertyAccessor wants to replace array when not needed

### ISSUE THREAD

**Issue by bananer** [symfony/symfony#13731]
This TestCase demonstrates the issue:

```
namespace Test;
use Symfony\Component\PropertyAccess\PropertyAccess;

class Bar {
    private $foo;

    public function setFoo($foo) {
        $this->foo = $foo;
    }

    public function getFoo() {
        return $this->foo;
    }
}

class A {
    private $bars;

    public function __construct() {
        $this->bars = array(
            'a' => new Bar(),
            'b' => new Bar(),
        );
    }

    public function getBars() {
        return $this->bars;
    }
}

class MyTest extends \PHPUnit_Framework_TestCase {

    public function testPropertyAccessor() {
        $accessor = PropertyAccess::createPropertyAccessor();

        $a = new A();

        $accessor->setValue($a, 'bars[a].foo', 'baz');

        $this->assertEquals('baz', $a->getBars()['a']->getFoo());
    }
}
```

I'm expecting the test case to pass.

Instead the following exception is thrown:
`Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Neither the property "bars" nor one of the methods "addBar()"/"removeBar()", "setBars()", "bars()", "__set()" or "__call()" exist and have public access in class "Test\A"`

I don't understand why PropertyAccessor wants to replace the "bars" array on my object.

I can work around the issue by adding an _empty_ setBars method to A, then the test case passes. So it's not like setting a new array is needed.

**Comment by jakzal** [comment]
I believe PropertyAccessor makes the Assumption that if you want to modify a property, there needs to be a way to set it back after it was read, even if it's an object. Your test passes with an empty `setBars()` method, as objects are passed by reference.

Changing this would break the following tests case:

```
class A {
    private $bars;
    
    public function __construct() {
        $this->bars = array(
            'a' => array('foo' => '1'),
            'b' => array('foo' => '2')
        );
    }

    public function getBars() {
        return $this->bars;
    }
}

class MyTest extends \PHPUnit_Framework_TestCase {

    public function testPropertyAccessor2() {
        $accessor = PropertyAccess::createPropertyAccessor();

        $a = new A();

        $accessor->setValue($a, 'bars[a][foo]', 'baz');

        $this->assertEquals('baz', $a->getBars()['a']['foo']);
    }
}
```

**Comment by bananer** [comment]
Thanks for looking into this. Shouldn't it be possible to check whether the end of the path is in an array or object, and only write changes back along the path if it's an array?

I was reading through the PropertyAccessor source and even though I don't quite understand most of it, there seems to be some way of tracking something is by value or by ref (IS_REF constant), maybe it's just not working right.

**Comment by Tobion** [comment]
I agree with @bananer that this seems to be a problem that can be fixed.
