### ISSUE TITLE
[Form] NativeRequestHandler overwrites $name param in handleRequest()

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#13746]
@webmozart 

I'm trying to debug an issue with the NativeRequestHandler related to: https://stackoverflow.com/questions/27104496/symfony-2-this-form-should-not-contain-extra-fields-validation-error-and-issu

* I'm using the form as a standalone component.
* My root form does not have a name defined.
* I'm uploading files

On [line 59](https://github.com/symfony/Form/blob/master/NativeRequestHandler.php#L59) `$name` is being set (in my case to "").

Further in the code on [line 101](https://github.com/symfony/Form/blob/master/NativeRequestHandler.php#L101) $name is being reset in the loop. In my case I have a child upload form with the name "userfile".

There for on [line 105](https://github.com/symfony/Form/blob/master/NativeRequestHandler.php#L105) `$name` is no longer empty.

I'm pretty sure this is causing issue when setting `$data` and in the `$form->submit()` on [line 129](https://github.com/symfony/Form/blob/master/NativeRequestHandler.php#L129).

Does this look like a bug to you @webmozart? I'm comparing code to the HttpFoundationRequestHandler to see if there's anything I can find.

Cheers Leevi

**Comment by leevigraham** [comment]
My Form

````php
<?php

namespace Deckee\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Test\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\Image;

class MemberPhotoType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'userfile',
            'file',
            array(
                'label' => 'Photo',
                'required' => false
            )
        );
    }

    public function getName()
    {
        return "";
    }
}
```

**Comment by Tobion** [comment]
getName should not be empty. You should only create a form with an empty name (using the appropiate method on the builder), but not have an empty type name.

**Comment by leevigraham** [comment]
@Tobion Sorry I don't follow. 

In my form I need to add a "ACT" param which is at the root of the form with no name prefix hence why I don't have a name on the form.

I can see that adding a name changes the way the $_FILES array is handled in the NativeRequestHandler given that the $_FILES array is now a nested array with the form name as the key.

Is it possible to add ACT at the root of the form if the MemberPhotoType is given a name?

**Comment by leevigraham** [comment]
Creating a form with the formFactory method createNamedBuilder (with no name) produces a form without a name:

```php
$form = $this->ee->deckee->formFactory->createNamedBuilder(
    null,
    new MemberPhotoType(),
    $data
)->getForm();
```
However the file processing is still throwing errors given the $_FILES array is no longer prefixed

**Comment by mpajunen** [comment]
@leevigraham The local variable reuse you pointed out originally does not look intentional.

I've submitted a PR with a basic fix and two new tests, including a case with a nameless form. At least the test case passes now, so the PR might fix your situation as well.

**Comment by leevigraham** [comment]
@mpajunen I didn't think the variable naming was right. I'll give this patch ago and see if it fixes the issue.
