### ISSUE TITLE
Constraint not producing error if entity variable is not equal to its column name

### ISSUE THREAD

**Issue by michalhabera** [symfony/symfony#13741]
```php
#SomeBundle/Entity/Some.php
...
class Some
{

    /**
     * @ORM\Column(type="string", name="menu_name", length=150)
     */
    protected $menuName;

    ...

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('menu_name', new Assert\Length(array("min"=>4, "minMessage"=>"Test error message.")));

    }

}
```

results in  
```
Property menu_name does not exist in class ... 
500 Internal Server Error - ValidatorException
```

If I change ```addPropertyConstraint()``` to property ```menuName``` error is not being shown in ```form_errors(form)``` since id of form_widget references to database column name, i.e. ```menu_name```.

Only solution I found is not to rename entity variables in annotation ```name``` attribute.

**Comment by Nek-** [comment]
Everything looks ok to me here: menu_name is not defined in the class, so obviously you cannot specify constraint on it. What's actually exists is your menuName attribute. Validation have nothing to do with database but is related to your class.

But I didn't understand the story with the id reference here... Can you be more clear?

**Comment by ogizanagi** [comment]
There is no issue there, as `addPropertyConstraint ` will add a constraint to the property named after the first argument. You do not define a property named `menu_name` in your class, but `menuName`. The field name in the DB has nothing to do with the validation component, as you're validating objects.
Did we missed something in order to understand your issue ?

**Comment by michalhabera** [comment]
You are right. I mixed up ```menu_name``` and ```menuName``` thus  I added  ```menu_name``` into form. I was getting no error since no ```menu_name```  property existed. Thanks guys.
