### ISSUE TITLE
[Validator] No interface for  ConstraintViolation::getConstraint() and getCause()

### ISSUE THREAD

**Issue by fago** [symfony/symfony#13748]
For Drupal, we are thinking about post-processing violations depending on accessible fields on a form (see https://www.drupal.org/node/2395831#comment-9643741). For that ConstraintViolation::getConstraint() would be handy to have, but getConstraint() and getCause() are not any interface.

I'm wondering whether there is any reason that those methods aren't in any interface? In particular, ConstraintViolation::getConstraint() would be handy to have.

**Comment by stof** [comment]
Adding them in the ConstraintViolationInterface before 3.0 was not possible (adding new methods in the interface is a BC break). Anyway, I'm not even sure why we have a ConstraintViolationInterface given that ConstraintViolation is an immutable value object. I don't see any reason to provide a separate implementation.

**Comment by fago** [comment]
I see - so it's safe to use them? Shouldn't we document that somehow then?

**Comment by stof** [comment]
@fago any method which is not tagged as ``@internal`` can be used. See our BC policy: http://symfony.com/bc

**Comment by fago** [comment]
I see, yes - but the documented return statement of ValidatorInterface is ConstraintViolationListInterface and consequently ConstraintViolationInterface only. So according to docs, the implementation could change?

**Comment by stof** [comment]
@fago Symfony itself already relies on these methods actually. And the only way to use a different implementation for the ConstraintViolation class is to replace the whole ExecutionContext IIRC, which itself requires using your own implementation of the Validator, so it won't happen in practice IMO.

**Comment by fago** [comment]
I see thanks. I agree and see it's unlikely to be changed, still there is nothing that documents that ConstraintViolation instances will be returned. Symfony already relying on that fact can make use confident it stays so - yes, but having documentation that states that accordingly would be better still.
