### ISSUE TITLE
API doc Symfony\Bundle\FrameworkBundle\Controller\Controller 2.6 not up to date

### ISSUE THREAD

**Issue by standaniels** [symfony/symfony#13743]
I noticed the ``addFlash`` method is not documented in the [controller's API](http://api.symfony.com/2.6/Symfony/Bundle/FrameworkBundle/Controller/Controller.html), but it was added in 2.6 according to [this blog post] (http://symfony.com/blog/new-in-symfony-2-6-new-shortcut-methods-for-controllers).

I mentioned this on IRC and xabbuh guessed the issue is that the new methods have been introduced protected and the API docs only render public ones.

**Comment by stof** [comment]
@fabpot I think it would be a good idea to include protected methods in the API doc, given that they are extension points
