### ISSUE TITLE
[Form] required attribute on an empty choice list

### ISSUE THREAD

**Issue by waldermort** [symfony/symfony#13757]
When using the Form 'choice' control, and when an empty ChoiceList is given, the form will output something like:

`<select multiple="multiple" class="form-control" required="required" name="groups[]"></select>`

Which fails HTML5 validation in both chrome and Firefox. To be honest, the multiple attribute should allow for zero selected elements. Removing the required attribute allows the form to be submitted.

I recommend the form control to not apply the attribute if there are no items.

**Comment by Tobion** [comment]
Just set required to false if you have no items.

**Comment by Tobion** [comment]
Closing as this would introduce magic.
