### ISSUE TITLE
[Console] posix_isatty(): could not use stream of type 'MEMORY'

### ISSUE THREAD

**Issue by ianbytchek** [symfony/symfony#13759]
Looks like this was resolved in #8939 ages ago. I'm getting this when trying to run a unit test.

```php
$command = Application::instance()->find('rollout');
$tester  = new CommandTester($command);
$tester->execute([
    'command'                => $command->getName(),
    Argument::DATABASE       => 'phpunit-great-todo',
    '--' . Option::DIRECTORY => 'vfs://great/mysql'
]);
```

```shell
posix_isatty(): could not use stream of type 'MEMORY'
 /vendor/symfony/console/Symfony/Component/Console/Output/StreamOutput.php:101
 /vendor/symfony/console/Symfony/Component/Console/Output/StreamOutput.php:56
 /vendor/symfony/console/Symfony/Component/Console/Tester/CommandTester.php:72
 /Test/Command/RolloutCommandTestCase.php:28
```

It seems that error suppression with `@` doesn't work. If I rewrite the method that fails with `try … catch`, it seems to be working fine. Perhaps this php-related, I am on 5.6.6? If the below the right thing to do I can send a PR.

```php
protected function hasColorSupport()
{
    if (DIRECTORY_SEPARATOR == '\\') {
        return false !== getenv('ANSICON') || 'ON' === getenv('ConEmuANSI');
    } elseif (!function_exists('posix_isatty')){
        return false;
    }
    try {
        return posix_isatty($this->stream);
    } catch (\Exception $exception) {
        return false;
    }
}
```

**Comment by iltar** [comment]
Can you check if the php.ini you're using for your unit-tests allows this? I've had a similar issue and one module was not loaded properly in my configuration.

**Comment by ianbytchek** [comment]
@iltar I'm googling but not finding much on what I should enable / allow? Do you know / remember what's part of php.ini that is?

**Comment by SpacePossum** [comment]
>It seems that error suppression with @ doesn't work.

You might want to check for: `xdebug.scream`

(http://xdebug.org/docs/all_settings
xdebug.scream
Type: boolean, Default value: 0, Introduced in Xdebug >= 2.1
If this setting is 1, then Xdebug will disable the @ (shut-up) operator so that notices, warnings and errors are no longer hidden.)

But maybe it is not related..

**Comment by iltar** [comment]
@ianbytchek I don't remember by head, I will see if I can find the module that needs enabling so you can check if that is actually present and activated.

**Comment by ianbytchek** [comment]
@SpacePossum good point re xdebug, it comes across unexpected at times, didn't think of it. Sadly that's not the issue here, besides `xdebug.scream` is `0`.

@iltar thanks, but just in case the posix module itself is on, I guess the fact that function exists indicates that. Be happy to know if that's something that I've missed.

**Comment by nick-jones** [comment]
@ianbytchek - do you have an error handler set that translates errors to exceptions? `posix_isatty` shouldn't throw any exceptions itself, so it's possible that some error handler is throwing one based on the `E_WARNING` triggered. Note that error suppression won't stop the error handler being called. If that is the case, then the error handler could be a bit cleverer - `error_reporting()` will return 0 where errors are being suppressed.

By the way, I'm not sure exactly what `posix_isatty()` is willing to accept, but assuming input/output streams are the only likely candidates, perhaps something like this would mean error suppression could be avoided?

```php
if (stream_get_meta_data($this->stream)['stream_type'] !== 'STDIO') {
  return false;
}
```

**Comment by ianbytchek** [comment]
@nick-jones thats it! I've read recently about `set_error_handler` and `@`, now that you mention it all comes together. So, yes, the exception is being thrown inside custom error handler. I guess I can fix this on my end.

I'm not sure we are talking about the same thing, the code suppression that causes an error is in [StreamOutput.php#L101] (https://github.com/symfony/symfony/blob/b001a79210eeac7c17a263d3713ec5c62f931a77/src/Symfony/Component/Console/Output/StreamOutput.php#L101) class. The code above is the suggested fix, though if that is caused by custom error handler that translates an error into exception, that might not be the real solution. In either case, I'm sure there is a proper approach to do this without error suppressions.

**Comment by javiereguiluz** [comment]
Closing it because it looks like an usage error instead of a real Symfony bug. Please reopen if you don't agree. Thanks!

**Comment by ianbytchek** [comment]
@javiereguiluz it's not a usage error, it's the use of error suppression in the framework instead of proper `try catch`, which is the cause of the issue. From what I remember, `set_error_handler` catches suppressed errors, which seems a little odd to me, and something the author of that code is not accounting for. There's a million reasons why error suppression is a bad practice, from performance to issues like this one.

This was awhile ago, but if https://github.com/symfony/symfony/blob/b001a79210eeac7c17a263d3713ec5c62f931a77/src/Symfony/Component/Console/Output/StreamOutput.php#L101 is still there, then the problem is still there. The suggested solution was changing suppression to use proper `try catch`. I tested this back in time, worked like a charm.

```php
protected function hasColorSupport()
{
    if (DIRECTORY_SEPARATOR == '\\') {
        return false !== getenv('ANSICON') || 'ON' === getenv('ConEmuANSI');
    } elseif (!function_exists('posix_isatty')){
        return false;
    }
    try {
        return posix_isatty($this->stream);
    } catch (\Exception $exception) {
        return false;
    }
}
```

I should have sent a PR for this, but wanted to figure out the reason why one worked and the other did't, which I did with @nick-jones's comment, and probably forgotten shortly after. Sorry. If you have a chance, please update the code.

**Comment by javiereguiluz** [comment]
@ianbytchek thanks for the info. I've created a PR in your behalf with the code that you provided: #17700. Let's see what others think about this change. Thanks!

**Comment by ianbytchek** [comment]
Thank you for taking care of that!

**Comment by fabpot** [comment]
Closing as the function does not return any exception by itself. This is probably related to a bad error handler.
