### ISSUE TITLE
[FrameworkBundle] [HttpKernel] InvalidArgumentException: Given expression is not a regex.

### ISSUE THREAD

**Issue by eeree** [symfony/symfony#13765]
We're getting constant InvalidArgumentExceptions in console when trying to clear an application cache with xdebug.scream enabled for cli. The reason why it happens is that application tries to send a wildcard instead of regex to Exporession component. I'm attaching images with call stacks and variables in local scope to illustrate an issue.
![symfony_regex_ap_dev](https://cloud.githubusercontent.com/assets/1375008/6320557/fb75549a-bae0-11e4-8488-947e2eb7396e.png)
![symfony_regex_command](https://cloud.githubusercontent.com/assets/1375008/6320556/fb73d052-bae0-11e4-9070-3b9e8ce4925b.png)
![symfony_regex_meta](https://cloud.githubusercontent.com/assets/1375008/6320558/fb76d680-bae0-11e4-9a77-28380422bd2b.png)

Symfony version: 2.3+
OS: Any
PHP version: Any
XDebug: On with xdebug.scream enabled

**Comment by hacfi** [comment]
@eeree This is excepted behaviour. According to the [SymfonyRequirements](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php#L513) `xdebug.scream` must be disabled to prevent those exceptions from popping up.

What happens here is that it first tries to convert the input to a Regex and then fallback to Glob if that doesn’t work:
https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Finder/Expression/Expression.php#L42-46

With `xdebug.scream` enabled this try catch is ignored.
