### ISSUE TITLE
[Config] Multidimensional (Prototype) arrays

### ISSUE THREAD

**Issue by SulivanDotEu** [symfony/symfony#13778]
Hi there,
I my project, I need to handle Multidimensional arrays in my configuration file. Here is what I try to achieve : 

    team:
        sales:
            - 'guy1@symfony.be'
            - 'guy2@symfony.es'

or this

    team:
        it:
            - 'guy1@symfony.be'
            - 'guy2@symfony.es'
        sales:
            - 'guy1@symfony.be'
            - 'girl3@symfony.fr'

or even this
    
    team:
        day:
            - day1@free.fr
        night:
            - gameofthrones@hbo.com

So I only know that team contains an array of array, that's it ! But I'll never know which index names they will have and that is a problem for me. I wonder if it was possible and if yes, how?
If not possible, I'll make a suggestion.

**Comment by stof** [comment]
```php
// $root is the root node of your config. I expect it to be instantiated
// previously by your Configuration class.
$root
    ->fixXmlConfig('team') // Rewrite <team> tags to a plural 'teams' array for XML configs
    ->children()
        ->arrayNode('teams') // 'team' in your example above, but a plural makes more sense for a list
            ->useAttributeAsKey('name') // First level is a map. In XML, it will be <team name="it">
            ->prototype('array')
                // normalize <team name="it"><member>1</member><member>2</member></team>
                // for XML, because nested prototyped arrays are not covered fully by builtin XML normalizations
                ->beforeNormalization()
                    ->ifTrue(function ($v) { return isset($v['member']); })
                    ->then(function ($v) {
                        return \Symfony\Component\Config\Definition\Processor::normalizeConfig($v, 'member');
                    })
                ->end()
                // Second level is a list, so no useAttributeAsKey call here
                ->prototype('scalar')->end()
           ->end()
        ->end()
    ->end()
```

The Yaml config will then look like this:

```yaml
my_bundle:
    teams:
        it:
            - 'guy1@symfony.be'
            - 'guy2@symfony.es'
        sales:
            - 'guy1@symfony.be'
            - 'girl3@symfony.fr'
```

the XML config would look like this:

```
<my_bundle:config>
    <my_bundle:team name="it">
        <my_bundle:member>guy1@symfony.be</my_bundle:member>
        <my_bundle:member>guy2@symfony.es</my_bundle:member>
    </my_bundle:team>
    <my_bundle:team name="sales">
        <my_bundle:member>guy1@symfony.be</my_bundle:member>
        <my_bundle:member>girl3@symfony.fr</my_bundle:member>
    </my_bundle:team>
</my_bundle:config>
```

If you don't care about XML, you can get read of the ``fixXmlConfig`` and the ``beforeNormalization`` stuff I added (but don't get rid of ``useAttributeAsKey`` even if the actual value passed as argument will not be important anymore for YAML)

**Comment by hacfi** [comment]
@stof Thanks for the useful example and explanation..quite helpful!

**Comment by SulivanDotEu** [comment]
thx a lot !
