### ISSUE TITLE
configureOptions is not taken into account (version 2.6.4)

### ISSUE THREAD

**Issue by ptsavdar** [symfony/symfony#13770]
I don't know if it's me, if I'm doing something wrong but it seems that the method configureOptions is not taken into account. Though the old and deprecated method setDefaultOptions seems to do the job just fine. Here is an example of my class. 

```php
class BitfieldType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new BitfieldToArrayTransformer());
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'bitfield';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'expanded' => true,
                'multiple' => true
            )
        );
    }

    /*public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'expanded' => true,
                'multiple' => true
            )
        );
    }*/
}
```

If I leave the configureOptions I get a select element, while with setDefaultOptions I get the desired group of checkboxes.

**Comment by xabbuh** [comment]
@ptsavdar `configureOptions()` is not available in Symfony 2.6, but will be part of Symfony 2.7.

**Comment by markitosgv** [comment]
Ok, im using 2.6 and this is the problem, is confusing because OptionResolverInterface is deprecated but we need still use it

**Comment by ptsavdar** [comment]
Ok, Thank you very much for the prompt reply.
