### ISSUE TITLE
ACL RoleSecurityIdentity doesn't work as expected with custom Role implementations

### ISSUE THREAD

**Issue by lrtz** [symfony/symfony#13775]
I have my custom Role implements RoleInterface so that I'm storing all the Roles to the database via doctrine as instructed over http://symfony.com/doc/current/cookbook/security/entity_provider.html#managing-roles-in-the-database

I suspect I have hit a bug in the way RoleSecurityIdentity is managed by the Symfony ACL component and I have tracked it down to https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Domain/RoleSecurityIdentity.php#L33

If I change this line so that it checks if the object is instance of RoleInterface instead of Role permission checking seems to work as expected

Otherwise the $role will be instance of the doctrine Role entity in the RoleSecurityIdentity __construct and function equals(SecurityIdentityInterface $sid) will always be false with consequent page loads.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
