### ISSUE TITLE
Phpunit test on 2.6 branch

### ISSUE THREAD

**Issue by razmo** [symfony/symfony#13786]
I would like to make a PR on the 2.6 branch but when i run phpunit test without any change (basic install: clone of the repository + composer install), i have this error.

```
PHP Fatal error:  Call to undefined method Mock_FormDataExtractorInterface_5855aaec::method() in /home/jamal/Development/web/bundles/symfony/src/Symfony/Component/Form/Tests/Extension/DataCollector/FormDataCollectorTest.php on line 501
```

Is anyone know why ?

**Comment by nicolas-grekas** [comment]
Maybe you should update phpunit?

**Comment by razmo** [comment]
:+1:
It works after update to the latest stable version.
Thanks !
