### ISSUE TITLE
VarDumper unable to dump specific stdClass

### ISSUE THREAD

**Issue by thebuh** [symfony/symfony#13784]
Sample code to reproduce can be boiled down to:

    $data = json_decode('{"1":{"var":"val"},"2":{"var":"val"}}');
    VarDumper::dump($data);

which results in 
( ! ) Notice: Undefined offset: 1 in vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php on line 73

( ! ) Notice: Undefined offset: 2 in vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php on line 73

( ! ) Fatal error: Cannot use object of type stdClass as array in vendor/symfony/symfony/src/Symfony/Component/VarDumper/Dumper/CliDumper.php on line 142

while var_dump and print_r are both able to show object just fine.

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, this should be fixed in #13785
Enjoy accessing the "1" key of your json decoded object, PHP makes it really annoying :)
