### ISSUE TITLE
assetic:dump causes RuntimeException (signal "6")

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#13781]
I'm trying to dump my assets on a virtual machine with 6GB of memory like this:

```
php ./app/console assetic:dump --verbose -e prod
```

I get the following error when it gets to one of my larger scss files:

```
[Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "6".
```

If I run this in the dev environment, it works:

```
php ./app/console assetic:dump --verbose -e dev
```

Is it running into some sort of memory limit? How I can I allocate more memory to the dump process?  I am using compass, uglifycss, and uglifyjs

**Comment by fabpot** [comment]
Thanks for the bug report. Unfortunately, I'm going to close this issue as Assetic is not part of Symfony. Can you report the problem to the Assetic project directly? Thank you.

**Comment by xabbuh** [comment]
Just for the records (in case anyone finds this issue having a similar one): see kriswallsmith/assetic#719 and fmarcia/UglifyCSS#25

**Comment by delboy1978uk** [comment]
For me (on a Mac), it was just a case of calling `brew update` and then `brew upgrade node`, then it all started working again. 

I noticed what the real error was when i tried manually running the command whilst pausing the code on a break point. It showed me:

```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.59.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
[1]    3324 abort      '/usr/local/bin/node' '/usr/local/bin/uglifyjs' '--compress' '-o'
```
