### ISSUE TITLE
[Validator] Number instances of validator service that has prototype scope is always 1

### ISSUE THREAD

**Issue by tienvx** [symfony/symfony#13797]
Problem: The validator service that has prototype scope is not created multiple times. So the number of instances is always 1.

How to reproduce:

* Clone the bundle from [GitHub](https://github.com/tienvx/reproduce-bundle)
* Enable the bundle, clear cache, etc.
* Go to /app_dev.php/validate-authors
* Check the result:
 * Expected: Number of instances is 10
 * Actually: Number of instances is 1

You can also run this command to test
```
phpunit -c app src/Tienvx/ReproduceBundle/
```

I followed [this instruction](http://php-and-symfony.matthiasnoback.nl/2011/11/symfony2-creating-a-validator-with-dependencies-make-it-a-service/) to create a validator service.
I followed this [document](http://symfony.com/doc/current/cookbook/service_container/scopes.html) to make the service of prototype scope.
Here is [the line](https://github.com/symfony/FrameworkBundle/blob/master/Validator/ConstraintValidatorFactory.php#L73) I think that cause the problem.

Sorry for my English! This is the first time I rise a bug for Symfony.

**Comment by jakzal** [comment]
I don't consider this as a bug. The service is requested from the container only once, and only a single instance is created. 

Why would this be an issue? What are you trying to achieve?

**Comment by stof** [comment]
The fact that the validator is loading constraint validators lazily indeed does not mean it loads them everytime to support scoped dependencies. This would either decrease performance for the common or would be a pain to manage.
If the loading was not lazy, the container would throw an exception when injecting the prototype-scoped service btw.

**Comment by webmozart** [comment]
Closing due to lack of feedback.
