### ISSUE TITLE
setDefaultOptions in form classes generated from CRUD

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#13792]
When we generate a form via the crud command `php app/console doctrine:generate:crud`, in the form type generated, we get the deprecated method of `public function setDefaultOptions(OptionsResolverInterface $resolver)` instead of `public function configureOptions(OptionsResolver $resolver)`.

Symfony version: 2.6.4.

**Comment by stof** [comment]
configureOptions is supported only in Symfony 2.7.

and the crud generator is in SensioGeneratorBundle, not in Symfony.
