### ISSUE TITLE
router:match doesn't work correctly with custom router implementation

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#13807]
In my application I use custom `\Symfony\Component\Routing\Matcher\UrlMatcherInterface::match`, which does not use `RouteCollection` in some cases. But `\Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand::execute` always asks a route collection from `route` service, and then constructs `TraceableUrlMatcher` with route collection. So, custom logic in my implemenation of `\Symfony\Component\Routing\Matcher\UrlMatcherInterface::match` is ignored.

Think it should be fixed, and I am ready to work on PR, but I want to discuss firstly. I think that we need just to call `match` method and write output (array of attributes) to console, if any. Is it a good solving of issue?

**Comment by stof** [comment]
Well, given that the RouterMatchCommand is meant to trace the matching of the route, it is forced to use a different matcher implementation (the UrlMatcherInterface only gives you the matching result).

**Comment by Strate** [comment]
@stof, but `router:match` command naming for me means that it should dump matching result. I suggest to change command signature to this:
1. Do current logic - try to find matching Route object and dump it, if any found.
2. If no route is found, simple call to `UrlMatcherInterface::match`, and, if there was no `ResourceNotFoundException` just dump array of matched attributes ot console output, with note about missing Route object
3. If there was `ResourceNotFoundException` treat it as missing route.

**Comment by fabpot** [comment]
Closing this old issue as there is no more activity.
