### ISSUE TITLE
Don't include PHPunit Bridge in core

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#13805]
The location of the `bootstrap.php` file depends on the installed package at the moment:

* When the Travis build does include a `symfony/symfony` package, the location is `vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bootstrap.php`
* When the Travis build doesn't install a specific symfony version (or just some components), the location is `vendor/symfony/phpunit-bridge/bootstrap.php`

As the installation of such a package is done inside the build script, it is very hard to predict this location. This makes it hard to have a common solution (for instance, all CMF repositories use the same bootstrap file, but not all include the `symfony/symfony` package).

This could be made much easier by removing the PhpUnit bridge from core, the location will then always be `vendor/symfony/phpunit-bridge/bootstrap.php`.

**Comment by nicolas-grekas** [comment]
We could also keep it in core to keep PRs and releasing standard, but move
it from replace to require-dev section in the root composer.json (and
remove autoload-dev). Would it work ?

**Comment by stof** [comment]
@nicolas-grekas if we remove it from replace, it will cause a bunch of issues because you will still have the codebase in the full repo itself. The goal of replace is to tell that the same code is already in the package to avoid getting classes twice

**Comment by xabbuh** [comment]
Would it be an option to add a class to the PhpUnit bridge whose only purpose is to load the `bootstrap.php` file (i.e. you would do something like `PhpUnitBridge::bootstrap()` instead of manually loading the file)?

**Comment by lyrixx** [comment]
Could this be solved with a if + file_exists , like we do with autoload.php ?
