### ISSUE TITLE
[Validator] Iban "FR76" is considered as valid

### ISSUE THREAD

**Issue by npotier** [symfony/symfony#13802]
Hi,

I have a problem with the IbanValidator. Iban "FR76" is considered as valid. 

The problem is that the Iban length according to the country is not tested ([step 1 of the validation algorithm](http://en.wikipedia.org/wiki/International_Bank_Account_Number#Validating_the_IBAN))

Following the current algorithm of ``IbanValidator.php``, the ``FR76`` string is converted to ``152776`` integer, and ``152776 % 7 `` is equal to 1, so the Iban is considered as valid.

I have reproduced the problem here : https://github.com/acseo/Validator/commit/4859db35b44ab72984481322b87cc9481b67e9d0

Do I understand it right ? Does anyone agree with this issue ?

**Comment by jakzal** [comment]
Indeed, looks like a bug.

**Comment by jakzal** [comment]
IBAN registry is officially maintained by swift: http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf

**Comment by npotier** [comment]
@jakzal ok. I can see two ways to fix it : 

1. The more complete is to check Iban length according to the country code. The proper way, but it means that source code needs to maintain information from the IBAN Registery
2. Check that Iban Length is at least > 14 characters without looking at the country code. Norway has the smallest Iban length (15 characters) according to the IBAN Registery.

What do you think ?
