### ISSUE TITLE
[SecurityBundle] EquatableInterface / Serializable issues

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony#13815]
Using the latest & greatest stable symfony 2.6.4 with AcmeDemoBundle, having followed http://symfony.com/doc/current/cookbook/security/entity_provider.html

All works great until you try to use the EquatableInterface to do the comparison checks to determine if the user has changed.

Remove the \Serializable from the class declaration and implement the EquatableInterface instead.

Trying to log in and getting this error (post-redirect to the default target path):

    ContextErrorException in SecurityDataCollector.php line 66: Catchable Fatal Error:
    Argument 1 passed to Symfony\Bundle\SecurityBundle\DataCollector
    \SecurityDataCollector::Symfony\Bundle\SecurityBundle\DataCollector\{closure}()
    must implement interface Symfony\Component\Security\Core\Role\RoleInterface, 
    boolean given

Indeed Xdebug shows the roles as an array of two booleans (in $token->getRoles() in https://github.com/symfony/SecurityBundle/blob/2.6/DataCollector/SecurityDataCollector.php#L66.

I have loaded fixtures for the user data and assigned two roles for the user.

All works great if you implement \Serializable.

The assumption that you can implement the EquatableInterface only is based on this doc http://symfony.com/doc/current/cookbook/security/custom_provider.html

Any ideas? Noticed in 2.7 the SecurityDataCollector had some major changes.

Running PHP 5.4.35

**Comment by stof** [comment]
@ptrm04 the user data need to be serializable. In case of Doctrine entities, implementing the Serializable interface is the only way to make it reliable (otherwise you will face issues with uninitialized proxies).
For other implementations of the user, letting PHP serialize the data on its own may be fine (and this is the case in the example of the doc btw).

**Comment by ptrm04** [comment]
@stof thanks! :-)
