### ISSUE TITLE
[Routing] Can't overwrite/extend UrlGenerator

### ISSUE THREAD

**Issue by austinh** [symfony/symfony#13821]
I have the following code

services.yml:
```
parameters:
    router.options.generator_class:  Acme\AppBundle\Routing\Generator\UrlGenerator
    router.options.generator_base_class:  Acme\AppBundle\Routing\Generator\UrlGenerator
```

Acme\AppBundle\Routing\Generator\UrlGenerator.php
```
<?php
namespace Acme\AppBundle\Routing\Generator;

use Symfony\Component\Routing\Generator\UrlGenerator as BaseUrlGenerator;

class UrlGenerator extends BaseUrlGenerator {

    public function generate($params, $context = array(), $absolute = false)
    {
        $url = parent::generate($params, $context, $absolute);

        // custom code here to modify urls
        $url .= "CUSTOM CODE BLAH";

        return $url
    }

}
```

However, nothing is happening. I believe it's because the cache class in appDevUrlGeneartor is using the default one and not my custom one. I have searched and found nothing that works.

Is this a bug? or am I doing it wrong?

**Comment by Tobion** [comment]
You also need to set the generator class in the router options: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Router.php#L115

**Comment by iltar** [comment]
Overwriting classes like that is not recommend, use [Service Decoration](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services) instead.

**Comment by austinh** [comment]
I have set the generator class as is shown above and it does not work.

I will try decorated services, but is there a reason this method will not work?

**Comment by iltar** [comment]
@austinh it will work, but this way of overwriting is deprecated. In the future, those parameters will no longer be available and you won't be able to overwrite them anymore.

**Comment by Tobion** [comment]
Closing as it's possible to change the UrlGenerator. For help in doing so please use the mailing list. Thanks

**Comment by stof** [comment]
@iltar the url generator is a special case, because it is generated in the cache.

@austinh the issue in your case is that the dumped class (which extends the provided class) does not call the parent ``generate`` method, given that its goal is precisely to generate an optimized version. So you would have to put your logic inside ``generateUrl``.
But a much better solution is to implement your logic in a different layer: instead of hooking into the cached url generator, hook at the router level by decorating it (this is how almost all bundles hooking into the routing are doing)

**Comment by o5** [comment]
I needed same as @austinh and I ended with [this](https://gist.github.com/o5/28077a3a20c093bd21731c9e6a299a81).

**Comment by yellow1912** [comment]
I need this as well, for getting the original configurations of a specific route since the URLGenerator does not expose its routeCollection. I wonder if using decorator is the right approach in this case?
