### ISSUE TITLE
Get lookup dirs from Finder

### ISSUE THREAD

**Issue by Whyounes** [symfony/symfony#13822]
I there a way to retrieve the lookup dirs from the finder? its private and has no getter!

**Comment by jakzal** [comment]
We only use github for feature development and bug reports. Please ask support questions on [the mailing list](http://symfony.com/mailing-lists) or [IRC](http://symfony.com/irc).

**Comment by Whyounes** [comment]
There is no one in the IRC, and i was asking, so i can add a getter and do a PR.

**Comment by jakzal** [comment]
Just bare in mind you'll need to justify the change. What's your use case?

**Comment by Whyounes** [comment]
I'm creating a documentation generator, and i want to get the directories selected by the user so i can look for a configuration file. Also, i found no one on the IRC channel

**Comment by Whyounes** [comment]
@jakzal no recommendations?

**Comment by jakzal** [comment]
I don't see how opening internals of Finder could help you with this. Since a user selected directories with a UI, you surely have access to these details?

**Comment by Whyounes** [comment]
i will be using the Symfony/Finder from console to generate to generate the documentation files

**Comment by xabbuh** [comment]
But you still need to build a user interface to collect the directories to search in. So you  will also be able to use it for something else than passing it to the `Finder`.

**Comment by Whyounes** [comment]
But why passing the same data in two different ways?

**Comment by stof** [comment]
@Whyounes the ``dirs`` property is far from being enough to know what the finder will find. It is only one of the settings configuring where to search.
