### ISSUE TITLE
[WebProfiler] Form panel js in the profiler is broken

### ISSUE THREAD

**Issue by maximecolin** [symfony/symfony#13824]
A javascript bug introduced in the #13636 PR breaks the form panel navigation in the web profiler.

**Comment by xabbuh** [comment]
This should have been fixed by #13729. Did you check that?

**Comment by maximecolin** [comment]
Yes, I checked, this PR fix the toolbar, not the form panel in the profiler.

**Comment by stof** [comment]
@xabbuh the ``buttons[i]`` vs ``tabs[i]`` was not.

@maximecolin cna you send a PR with the fix ?

**Comment by maximecolin** [comment]
@stof Only replace ```buttons[i]``` by ```tabs[i]``` is not enough to fix the bug, i try and there are other errors. That's why i didn't send a PR. I haven't looked further for a bug fix because i didn't know how the panel works and what isn't working on IE.

**Comment by xabbuh** [comment]
#13987 replaces `buttons[i]` with `tabs[i]`.

@maximecolin Can you please explain what else would need to be changed? Do you get other error messages after those changes?

**Comment by aitboudad** [comment]
@maximecolin I just updated #13987 , can you check now ?

**Comment by aitboudad** [comment]
fixed by #13987. Feel free to reopen if the problem persists.
