### ISSUE TITLE
Form Builder DateTime formatting fails without notice, docs unclear

### ISSUE THREAD

**Issue by ArlingtonHouse** [symfony/symfony#13833]
The format option doesn't always work with dropdown selects and doesn't throw an error or warning, see:
```
 $builder->add('publishedAt', 'datetime', array(
                'input'  => 'datetime',
                'widget' => 'choice',
                'years'=> array('2015', '2016'),
                'format' => 'MMM-dd-yyyy hh:mm: a',
                'label' => 'Schedule Date and Time'
            ))
```
This also fails without warning:
```
 $builder->add('publishedAt', 'datetime', array(
                'input'  => 'datetime',
                'widget' => 'choice',
                'years'=> array('2015', '2016'),
                'date_format' => 'MMM-dd-yyyy hh:mm: a',
                'label' => 'Schedule Date and Time'
            ))
```
While this successfully formats the date (but not time):

```
 $builder->add('publishedAt', 'datetime', array(
                'input'  => 'datetime',
                'widget' => 'choice',
                'years'=> array('2015', '2016'),
                'date_format' => 'MMM-dd-yyyy ',
                'label' => 'Schedule Date and Time'
            ))
```

There are also several types similar of format options described in the docs, which is confusing:

http://symfony.com/doc/current/reference/forms/types/date.html#format
http://symfony.com/doc/current/reference/forms/types/datetime.html#format http://symfony.com/doc/current/reference/forms/types/datetime.html#date-format

It isn't clear how we format the hour field with/without a leading zero, or whether or not an am/pm selection is possible.

Finally, I think a lot of people try to use php date formatting rather than ICU, that would also be a helpful error code for example. Thank you!

**Comment by xabbuh** [comment]
As explained in the [format option documentation](http://symfony.com/doc/current/reference/forms/types/datetime.html#format), this option only affects the `single_text` widget while your are using the `choice` widget in your first example.

What exactly happens in your second example where there format also contains time information for the date part?

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback and because it looks like a wrong usage. Please reopen if you don't agree. Thanks!
