### ISSUE TITLE
DX: Organisation of source files

### ISSUE THREAD

**Issue by henrypenny** [symfony/symfony#13838]
Symfony bundles are organised by the technical purpose of various files:

- Entities
- Controllers
- Listeners
- Views
- Configuration
etc...

I would like to be able to organise assets by their functional purpose:

- User
- Article
- Blog
- Product

E.g. the Product folder might look like:

    Product/ProductController.php
    Product/Product.php (entity)
    Product/product.html.twig
    Product/ProductListener.php
    Product/services.yml

This would avoid a lot of skipping between directories when working on one functional area.

Bundles are already doing this at a coarse grained level which is great, but I'd like the ability to break a single bundle up by functionality. Perhaps `sub-bundle` is a suitable term.
If it makes sense to split a specific functional item out into its own bundle then that's a no-brainer, but its not always warranted when you're dealing with finer grained functional divisions.

I think it would have the following advantages:
- Encourage developers to think about how decoupling their code more.
- Make refactoring into separate bundles easier.
- Easier for new developers to come into a project or for junior developers.

**Comment by WouterJ** [comment]
Nothing prevents you from using the structure you want.

However, some months back, a Symfony team specialized in teaching Symfony to beginners and some other Symfony devs have thought about how to best structure your code and a way lot more. This was all done to make the barrier as low as possible for beginners. The result was the pretty controversial [Best Pratices](http://symfony.com/doc/current/best_practices).
I don't think we have to move away from the structure decided back then too soon (but well, who am I? :)).

I see a big problem with your idea: Each directory will be a complete mess. Imagine a product, which has an admin (so 2 controllers), some actions (so let's say 10 templates), 4 entities, 4 repositories and a couple of other classes (5) with one config file.
That's a very simple case and it means that we already have 26 files in 1 directory. And they have all very different reponsibilities.

I also think that if we should avoid one thing, it should be to always encourage decoupling. Decoupling has been brought into the PHP community and now we decided that everything should be decoupled. The best practices were a very nice counter response: You ain't gonna need it. Why creating 5 bundles, all very decoupled with semantic config etc, when you are never going to use one of the five in another application? You just make your life harder for no reason.

**Comment by henrypenny** [comment]
One thing that I find a 'mess' is the huge number of use statements at the top of each class. Eg. a Twig extension is recommended to go in a /Twig/ folder on its own. So everything it uses in the same functional domain is in a different namespace.

However, your point about 'Nothing prevents you from using the structure you want' is well taken. Its probably a lack of config knowledge on my part, but I didn't know I could put views anywhere for example. But thinking about it I guess you're right for the most part.

So I'll close this. Thanks for your input.
