### ISSUE TITLE
HTTP request header removed by Symfony?

### ISSUE THREAD

**Issue by samuel4x4** [symfony/symfony#13849]
Hi,

I encounter troubles working in Symfony with HTTP request headers that contains the "_" character in their names. They are present in apache_request_headers() but not in $this->getRequest()->headers. It seems to be removed/skipped by Symfony?

It's about some headers we just receive as they are and we can't change their names.

I spent some time looking into the following classes, without understanding where the problem is:

Symfony\Component\HttpFoundation\HeaderBag
Symfony\Component\HttpFoundation\Request
Symfony\Component\HttpFoundation\Response

If anybody has any idea about this issue, please let me know.

Thanks!

**Comment by stof** [comment]
@samuel4x4 IIRC, ``apache_request_headers()`` returns more headers than what Apache passes to PHP natively through the CGI (available in ``$_SERVER``).

**Comment by samuel4x4** [comment]
@stof You're right, my header is also missing from $_SERVER, so it's not a Symfony issue.

Inspired by http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html, I put the following rule in my web/.htaccess:

RewriteRule .* - [E=HTTP_XXX_YYY:%{HTTP:xxx_yyy}]

and now my "xxx_yyy" header is returned also by Symfony. 

Thanks for help ;)
