### ISSUE TITLE
[VarDumper] Informations about methods ?

### ISSUE THREAD

**Issue by bonswouar** [symfony/symfony#13844]
In the official [blog post](http://symfony.com/blog/new-in-symfony-2-6-vardumper-component) @javiereguiluz said :
> [...] you'll get the full detail of those variables, including information about references, public/protected/private properties and methods [...]

But apparently there is no information about methods, only properties. And I can't find anything related to that.
Has this functionality been abandoned ? Why ? And if so, why not letting this as an option for example ?

By the way I was previously using [LadybugBundle](https://github.com/raulfraile/LadybugBundle), which was able to list methods. And I guess this project has stopped when the Symfony Dumper feature has started, as I stopped using it when I upgraded to SF 2.6.

**Comment by stof** [comment]
Well, listing methods is not really useful IMO. There is no state in methods and knowing the class allows you to know exactly what are the available methods. Adding that in the dump would only make the output much bigger.

Methods have never been dumped by the VarDumper as far as I remember the initial work. This looks like a mistake in the blog post.

**Comment by nicolas-grekas** [comment]
Yes, the blog post should not tell about methods.
I have a branch locally where I want to make a class reflection inspector in the debug toolbar.
This is not ready though. And it's something very different from VarDumper: as stof says, VarDumper is about dumping the *state* of a variable. But there is no state at all in Reflection information itself.

**Comment by bonswouar** [comment]
I understand your point of view (no state on methods), but still I found it pretty useful with LadybugBundle to able to see all the methods & proprieties available in one look..

Well if I'm the only one thinking it would be useful, I guess that's the reason why it hasn't been implemented ! ;)

I might just fork it to add this functionality, doesn't seem to be a lot.

**Comment by stof** [comment]
@bonswouar you should rather wait until the class reflection inspector is added in the debug toolbar rather than trying to add the feature in the VarDumper itself, where it won't be accepted (and the code of the dumper is not simple)

**Comment by bonswouar** [comment]
Thanks for your advice @stof, I probably should do that (I didn't take a look at the code of the dumper yet).
@nicolas-grekas , do you need any help implementing this class reflection inspector ? If you want to make this branch public I'd be glad to participate.

**Comment by stof** [comment]
> do you need any help implementing this class reflection inspector ? If you want to make this branch public I'd be glad to participate.

Knowing how code written by @nicolas-grekas looks like, you may change your mind after seeing the branch :smile: 
@nicolas-grekas it is still written with 1-letter names for all variables like the initial VarDumper ?

**Comment by nicolas-grekas** [comment]
Unfortunately, I had to use longer var names after you reviewed my code ;)

**Comment by bonswouar** [comment]
Well... At least, short variable names can save lots of disk space ! ;)

**Comment by stof** [comment]
@bonswouar are you developing your JS directly in minified files too ?

**Comment by bonswouar** [comment]
@stof, of course ! And actually I use white spaces only on Github and in Emails. :wink:
