### ISSUE TITLE
[ExpressionLanguage] Try to configure a service using a factory.

### ISSUE THREAD

**Issue by SulivanDotEu** [symfony/symfony#13841]
I'm trying to configure the framework session handler with a Expression language like this (in config_prod.yml) :

    framework:
        session:
            handler_id:  "@=service('my_session_factory').createSessionHandler()"

which is inspired by this example : http://symfony.com/doc/current/book/service_container.html#using-the-expression-language .
Unfortunatly, my service is not reconnized, I got an InvalidArgumentException : 

    The service definition "@=service('my_session_factory').createSessionHandler()" does not exist.

Is ExpressionLanguage only works with arguments? Should I be able to use ExpressionLanguage in this way?

My configuration : Symfony 2.6.4 with expression-language ~2.6

**Comment by mvrhov** [comment]
You can't use the expression language in configuration files.

**Comment by SulivanDotEu** [comment]
but the example here : http://symfony.com/doc/current/book/service_container.html#using-the-expression-language mention "app/config/config.yml". Am I Missing something? Because my first impression is this is contradictory

**Comment by xabbuh** [comment]
You can use the expression language when configuring your services, but you cannot use them for the bundle configurations.

**Comment by jakzal** [comment]
@SulivanDotEu qutoing the article you referenced:

> Expressions can be used in arguments, properties, as arguments with configurator and as arguments to calls (method calls).

Parameters are not supported.
