### ISSUE TITLE
how to find filed for error?

### ISSUE THREAD

**Issue by ahmadina** [symfony/symfony#13847]
hi
i use in validation for get error message :

~~~php
 $errors = [];

foreach ($form->getErrors(true) as $error) 
{
 $errors[] =  $error->getMessage();
 }
~~~

how to get field name ?

for example ouput data : 

['filed_name' : 'error message' , ... ]

**Comment by xabbuh** [comment]
@ahmadina Which Symfony version do you use?

**Comment by ahmadina** [comment]
@xabbuh i use silex and use package symfony/validator and symfony/form

**Comment by xabbuh** [comment]
@ahmadina Which version of the symfony/form package?

**Comment by ahmadina** [comment]
@xabbuh ~2.3

**Comment by xabbuh** [comment]
@ahmadina That's just a version constraint which would generally allow newer versions of the Form component. Though one of your other dependencies might tie the package to a `2.3.x` version. However, in newer Symfony versions, [FormError objects](http://api.symfony.com/2.6/Symfony/Component/Form/FormError.html) have a `getOrigin()` method that return the form causing this error.

**Comment by ahmadina** [comment]
@xabbuh Can I get my name in version 2.7.*@dev ?

**Comment by merk** [comment]
`composer show -i` shows installed versions
