### ISSUE TITLE
[WebProfiler] Variable dumps are stored in the wrong profile when subrequests are used.

### ISSUE THREAD

**Issue by mkrauser** [symfony/symfony#13842]
When subrequests are used, dumped variables (using dump()) are stored not in the request, they were created. This behaviour is different for regular subrequests and ESI-subrequests:

regular:
the dumps for the master reuqest and all subrequests are stored in the profile of the master request.

ESI:
all dumps are stored into the profile of the last subrequest. 

I tracked it down to the clone-index check in [DumpDataCollector:135](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/DataCollector/DumpDataCollector.php#L135). 

I setup a minimal project to demonstrate this issue [here](https://github.com/mkrauser/symfony-dump-demo)

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Well, without thinking about ESI, I made that on purpose: wherever you `dump()`, I wanted you to see the result in the toolbar. The way I did that is by linking dumps to the master requests and bypass the per-sub-request profiles. But this does not work for ESI you're right.

So, we have two options for a fix (it's more a new feature than a fix though):
- we could remove the need to have all dumps in the toolbar, and simplify everything. But that would force people to lookups for dumps in subrequests profiles, which are a few click away. I think this goes against DX
- we could have the toolbar search all profiles for dumps in every sub-req (esi or not) and display all of them (which means we'd keep the current DX when no ESI is involved, and "fix" ESI dumps)

**Comment by mkrauser** [comment]
I think each dump should be profiled in the request it was dumped. 

However, it would be really nice to have all dumps() including the ones from sub-requests viewed in the toolbar. Looking through subrequests for dumps is really bad. But it should be made clear where each dump comes from (the current request or which sub-request).

**Comment by fabpot** [comment]
Current behavior seems better (as explained by @nicolas-grekas)
