### ISSUE TITLE
[form] action attribute in html5

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13852]
In the [current html5 draft](http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-fs-action), i've read the following:

> The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces.

In the [current implementation](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/FormType.php#L207) of the `FormType` follows the HTML4 specification, which allows it to be available and empty in order to post to the same URI (this is nicely documented in the formtype as well).

However, on HTML5 this is not allowed anymore, and afaict, an empty `action` should be completely removed from the output in order to do the same. Since we cannot really know if a user is creating a  html4 or html5 site, maybe we should add an additional option to the form, that allows us to figure this out:

```
$form = $this->createFormBuilder(null, array(
    'method' => 'POST',
    'html5' => true,
));
```
renders:  `<form method="POST">`

```
$form = $this->createFormBuilder(null, array(
    'method' => 'POST',
));
```
renders:  `<form method="POST" action="">`

Since the `DateTimeType` also got a html5 option, it would be easier to have it directly in the formtype as well, as other types can automatically benefit from this information (like the rangeType, which could display `<input type=range` instead of some fallback in case we're not running html5-mode)

**Comment by Tobion** [comment]
Is a missing action attribute allowed in html4 and does it default to the same uri? Then we could just omit rendering it when it's empty.

**Comment by ogizanagi** [comment]
@Tobion : according to the W3C markup validation service, for HTML 4.01 Strict doctype:

> required attribute "ACTION" not specified
The attribute given above is required for an element that you've used, but you have omitted it...

**Comment by jaytaph** [comment]
@Tobion:

http://www.w3.org/TR/html401/interact/forms.html#h-17.3  suggests it is required. However, it MAY be empty according to section 4.2 of http://www.ietf.org/rfc/rfc2396.txt. 

In other words: it seems that they completely reversed the action attribute in html5:

attribute | html4 | html5
------------ | ------------- | -------------
action="http://foo" | yes | yes
action=""  | yes | no
no action specified | no | yes

I think this is correct, but there might be other people knowing more about this than me..  There might be addendums and other rfcs that might change the outcome (also, html5 is still draft, so theoretically, this can change)

**Comment by WouterJ** [comment]
Using `#` as value is valid HTML4 and HTML5 and posts to the current URL. What about using that? I'm not sure about adding an option for this.

**Comment by jaytaph** [comment]
I don't know if that is valid (and supported) behaviour. I must dive into the specs to verify. But I expect more knowledge people about this might already have an answer? If that works, I'd rather see that than the current implementation which is not valid html5 anyway.

**Comment by ThomasLandauer** [comment]
Somewhat related: For Ajax forms to work with AngularJS, the `action` attribute needs to be removed completely.

Right now, it looks like there is only a work-around solution for this, see: http://stackoverflow.com/questions/28499529/angularjs-and-symfony2-forms-or-how-to-remove-forms-action-attribute/

So I think a dedicated option to control `action` would certainly be a good idea :-)

**Comment by xabbuh** [comment]
@ThomasLandauer Does that mean AngularJS only plays well with HTML5 documents?

**Comment by ThomasLandauer** [comment]
@xabbuh: No, it's not actually an HTML 5 issue. AngularJS doesn't have `preventDefault()`. So when the form does have an `action` it *always* gets submitted - no matter if AngularJS already handled it or not.

I'm only mentioning this here cause (after HTML5-validity) AngularJS it a second reason to provide an option for `action`-management :-)

**Comment by jaytaph** [comment]
@ThomasLandauer @xabbuh Maybe an `"omit_action"` option? This would be fairly trivial to implement, and allows HTML5 compliant forms, plus fixes angularJS issues without (complex) overriding of the `form_start` block?

**Comment by ThomasLandauer** [comment]
@jaytaph: Yeah, certainly fine with me :-)

**Comment by Tobion** [comment]
I would propose to just not output an `action` attribute when the action is empty (to conform to HTML5) by default. HTML5 is already very well adopted. If people want to validate against HTML4, they can use `action='#'` as workaround. But it's not even really necessary as an HTML4 form without action still defaults to the current document AFAIK (so it would just be about conformance). This way we don't need ugly workarounds like new options or `action=false`.

**Comment by xabbuh** [comment]
The only bad thing is that this would semantically break for people shipping HTML4 right now with empty form actions (that's not very likely since the Symfony SE ships with an HTML5 base layout though). However, maybe that's a change that is acceptable for a new minor release (so best would be to have it in Symfony 2.8 then)?

**Comment by Tobion** [comment]
I'm fine with doing it in 2.8
