### ISSUE TITLE
PdoSessionHandler: Hight database load by deleting sessions

### ISSUE THREAD

**Issue by fadoe** [symfony/symfony#13858]
The problem is in PdoSessionHandler from Symfony 2.6 and MySQL:

When deleting sessions from database in close()-method, for all rows the time for lifetimeCol and timeCol is calculated. This will slow down the database and is not a good solution. How can it optimized?

**Comment by Tobion** [comment]
What load does it cause?

Solutions:
1. one could combine both columns and calculate it when writing, but that would not change anything unless you also place an index on it
2. you can just reduce the GC probability, see http://php.net/manual/de/session.configuration.php#ini.session.gc-probability

**Comment by fadoe** [comment]
Every time the sessions will deleted, the mysql server has a high load. The reason is, the two colums lifetimeCol and timeCol are added and checked. Test it with 600.000 sessions, mysql is working and the user is waiting.

1. Index is not working, because the times are calculated row by row. It only makes sense with one calculated column.
2. Yes, this could be a solution.

I think the current PdoSessionAdapter is not a good solution to store sessions in a table. This problem should be added to the documentation. We spend lot of time in this new PdoSessionHandler, time we need for other parts in our project. The old PdoSessionHandler works well.

**Comment by fadoe** [comment]
A good solution would be to create a new column for the calculated lifetime and time, updated when updating the session data. Now we can create a index and delete the sessions very easy.

**Comment by Tobion** [comment]
I open concrete steps to do based on this discussion in #13955 and #13956. So closing.
