### ISSUE TITLE
[VarDumper] Cannot add element to the array as the next element is already occupied

### ISSUE THREAD

**Issue by barryvdh** [symfony/symfony#13859]
I'm using the VarDumper component as a stand-alone component in a Magento store and came across this error:

> Warning: Cannot add element to the array as the next element is already occupied  in /vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/VarCloner.php on line 124

Stacktrace:

    #0 [internal function]: mageCoreErrorHandler(2, 'Cannot add elem...', '/var/www/html/c...', 124, Array)
    #1 vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/AbstractCloner.php(287): call_user_func('mageCoreErrorHa...', 2, 'Cannot add elem...', '/var/www/html/c...', 124, Array)
    #2 vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/VarCloner.php(124): Symfony\Component\VarDumper\Cloner\AbstractCloner->handleError(2, 'Cannot add elem...', '/var/www/html/c...', 124, Array)
    #3 vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/AbstractCloner.php(152): Symfony\Component\VarDumper\Cloner\VarCloner->doClone(Object(Vendor_Categories_Model_Resource_Link_Collection))
    #4 vendor/symfony/var-dumper/Symfony/Component/VarDumper/VarDumper.php(34): Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Object(Vendor_Categories_Model_Resource_Link_Collection))
    #5 [internal function]: Symfony\Component\VarDumper\VarDumper::Symfony\Component\VarDumper\{closure}(Object(Vendor_Categories_Model_Resource_Link_Collection))
    #6 vendor/symfony/var-dumper/Symfony/Component/VarDumper/VarDumper.php(38): call_user_func(Object(Closure), Object(Vendor_Categories_Model_Resource_Link_Collection))
    #7 vendor/symfony/var-dumper/Symfony/Component/VarDumper/Resources/functions/dump.php(21): Symfony\Component\VarDumper\VarDumper::dump(Object(Vendor_Categories_Model_Resource_Link_Collection))
    #8 htdocs/app/code/local/Vendor/Namespace/controllers/IndexController.php(19): dump(Object(Vendor_Categories_Model_Resource_Link_Collection))
    #9 htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Vendor_Categories_IndexController->testAction()
    #10 htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('test')
    #11 htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #12 htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
    #13 htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #14 htdocs/index.php(89): Mage::run('', 'store')
    #15 {main}

So that's this line: https://github.com/symfony/symfony/blob/0ab3bebf69a25c3475e71fe1013aa6c2417d39a0/src/Symfony/Component/VarDumper/Cloner/VarCloner.php#L124

Supressing the error gives a (probably) okay result. Any idea what could fix this? Gist of the files are here, but haven't narrowed it down much. https://gist.github.com/barryvdh/c475b90372a99e8951c2

**Comment by nicolas-grekas** [comment]
Can you please confirm the patch attached to #13860 fixes the pb?

**Comment by barryvdh** [comment]
It does.
