### ISSUE TITLE
yaml:lint does not support glob

### ISSUE THREAD

**Issue by dhoko** [symfony/symfony#13861]
Hi,

The command `yaml:lint` does not work as expected. We cannot use a pattern with it :-1:. 
Reading [YamlLintCommand.php](https://github.com/symfony/FrameworkBundle/blob/master/Command/YamlLintCommand.php#L68) I saw `'Please provide a filename or pipe file content to STDIN.'` so let's go.

```sh
[pdc]:~/dev/front [feat/angular-app] 
$ find src -type f -name '*.yml' ! -path '*node_modules*' | app/console yaml:lint                                      
KO in 
>> Unable to parse at line 1 (near "src/XXX/AngularBundle/Resources/public/i18n/en-EN/home.yml").
0/1 valid files
```

So it does not work, but... it works. :sweat: 

```sh
[pdc]:~/dev/front [feat/angular-app] 
$ app/console yaml:lint src/XXX/AngularBundle/Resources/public/i18n/en-EN/home.yml
1/1 valid files
```

Edit: 

Okay the exception is about the file content, It works if I do: 

```sh
cat src/XXX/AngularBundle/Resources/public/i18n/en-EN/home.yml | app/console yaml:lint
```
I think it should work without the file content input too.

**Comment by stof** [comment]
@dhoko your first example is not trying to lint STDIN input. It is trying to pass file paths through STDIN, which is not something we ever advocated. You cannot say it does not work as expected. It works exactly as expected: you should either provide the filename to lint, or send the content to lint through STDIN

**Comment by jakzal** [comment]
@dhoko not sure if it's worth to complicate the command to implement this use case, as what you need to do is possible already with something like:

```
find src -type f -name '*.yml' ! -path '*node_modules*' -exec app/console yaml:lint '{}' \;
```

**Comment by dhoko** [comment]
@stof Yup :) The main problem is not for stdin but a list of files/glob. It doesn't work.

@jakzal Thank you.
I found this one
```sh
find src -type f -name '*.yml' ! -path '*node_modules*'  | gawk '{print "app/console yaml:lint " $1; }' |  bash -x
``

**Comment by dhoko** [comment]
cf #13876
