### ISSUE TITLE
Check if Entity namespace exists after giving shortcut name

### ISSUE THREAD

**Issue by mikaelz** [symfony/symfony#13879]
Hi, I was generating CRUD entities with *doctrine:generate:crud* but I mistyped the shortcut name, typed Linda instead Lynda.
Wouldn't it be good to check namespace after giving the shortcut name?
![screen shot 2015-03-09 at 10 54 50 am](https://cloud.githubusercontent.com/assets/454800/6558339/f59c604e-c67b-11e4-997c-31b00c027dc3.png)

**Comment by stof** [comment]
the crud generator is not part of Symfony but of SensioGeneratorBundle. Please report it there instead.
