### ISSUE TITLE
Claim ownership of JMS Serializer?

### ISSUE THREAD

**Issue by andreaslarssen** [symfony/symfony#13875]
As the Symfony documentation references the [JMS Serializer](https://github.com/schmittjoh/serializer), would it be an idea to approach [schmittjoh](https://github.com/schmittjoh) with an offer to claim ownership of, or help further development of it?

It's a great tool that helps thousands of developers, but it has some hundred issues atm. A big organization like SensioLab getting behind it could really boost it.

**Comment by erichfosse** [comment]
+1

**Comment by fabpot** [comment]
It looks like that the code is maintained as I can see regular commits. I don't see how changing the owner ship would magically solves the issues and boost the development.

**Comment by javiereguiluz** [comment]
@andreaslarssen I don't have an opinion about JMS Serializer, but the built-in [Serializer component](http://symfony.com/components/Serializer) is recently getting a new life thanks to the hard work of @dunglas.

**Comment by andreaslarssen** [comment]
@javiereguiluz. I'm sure the built-in component has gotten better, but the [documentation](http://symfony.com/doc/current/components/serializer.html) still says 

> "A popular third-party library, JMS serializer, provides a more sophisticated albeit more complex solution. This library includes the ability to configure how your objects should be serialized/deserialized via annotations (as well as YAML, XML and PHP), integration with the Doctrine ORM, and handling of other complex cases.", implying that the built-in serializer 

...implying that the built-in one does not. At least there's no documentation for how to configure serialization on that level. 

@fabpot. There's no magic, just a larger community I guess? It's maintained, but it seems like he / they could use some more help. Last commit was two months ago, Symfony 2 days ago. It just seemed like a good idea to take an already terrific bundle and help it prosper instead of maintaining a parallel component with similar goals (I'm guessing).  Especially since Symfony already refers to it in it's documentation.

It was just an idea, really.

**Comment by fabpot** [comment]
Keep in mind that the new features @javiereguiluz talks about are new in the upcoming 2.7 version of Symfony (the note you are referring too should probably be removed now -- ping @dunglas). 

Anyway, the license is not MIT and as we already ship with a serializer, it's not going to happen. Closing now.

**Comment by andreaslarssen** [comment]
Reading the change log for 2.7, I see that the built-in serializer implements a lot of what the JMS Bundle has to offer. Which is nice.

**Comment by dunglas** [comment]
@andreaslarssen The doc is in process of being updated, see this PR for instance: https://github.com/symfony/symfony-docs/pull/4675/files

JMSSerializer still have advanced features (especially regarding XML support) that are unlikely to be added in the Symfony built-in Serializer. However, most of the "must have" features have been added to the built in component including groups support, circular references handling, property name converter, normalization of object having both publics properties and getters / setters...

IMO, we can update the doc to explain how to use the built-in Serializer instead of recommending using JMS Serializer. Any help is welcome.

**Comment by fabpot** [comment]
@dunglas At least, can you create a ticket on symfony-docs to avoid loosing this discussion?

**Comment by andreaslarssen** [comment]
Thanks! Looking forward to the release.
