### ISSUE TITLE
[DX] Minor improvement for the translation:debug output

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#13874]
Currently, `translation:debug` output uses a legend to show the state of each translation. Example:

```
+----------+----------------------------------------+------------------------------------------+
| State(s) | Id                                     | Message Preview (en)                     |
+----------+----------------------------------------+------------------------------------------+
| o        | what.is.component                      | What is a Component?                     |
| =        | the.components                         | The Components                           |
| o        | browserkit.summary                     | Simulates the behavior of a web browser. |
| x        | browserkit.description                 |                                          |
| o        | classloader.summary                    | Loads your project classes automatica... |
| x        | classloader.description                |                                          |
| ...                                                                                          |
+----------+----------------------------------------+------------------------------------------+

Legend:
 x Missing message
 o Unused message
 = Same as the fallback message
```

I find the legend confusing when the table is very long, which is usually the case. Moreover, the `State` column is wide enough to not use a legend and just display the labels.

That's why I propose to change this table a bit to look as follows:

```
+----------+----------------------------------------+------------------------------------------+
| State    | Id                                     | Message Preview (en)                     |
+----------+----------------------------------------+------------------------------------------+
| unused   | what.is.component                      | What is a Component?                     |
| same     | the.components                         | The Components                           |
| unused   | browserkit.summary                     | Simulates the behavior of a web browser. |
| missing  | browserkit.description                 |                                          |
| unused   | classloader.summary                    | Loads your project classes automatica... |
| missing  | classloader.description                |                                          |
| ...                                                                                          |
+----------+----------------------------------------+------------------------------------------+
```

**Comment by jakzal** [comment]
I don't have a preference, but if we proceed "equal" should be "same".

**Comment by javiereguiluz** [comment]
@jakzal thanks. I've replaced `equal` by `same`.

**Comment by xabbuh** [comment]
I'm not sure if *same* is easy to understand if you don't know the context. What about something like "not modified" or "not adapted"?

**Comment by jakzal** [comment]
Either "not modified" nor "not adapted" are misleading. The message is set to the same value as the id.

**Comment by jakzal** [comment]
How about "fallback"?

**Comment by xabbuh** [comment]
Yes, but this may indicate that you copied the translation file for the fallback language and forgot to translate one if the values. I have to any that this is not the only reason this happens though.

**Comment by xabbuh** [comment]
"fallback" sounds good. "default" could also be an option.

**Comment by timglabisch** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Let's recap this proposal:

**1)** If Symfony deciders don't like this idea, please close this issue as *won't fix*. Thanks.

**2)** If the idea is accepted, let's tag it as *Easy Pick*, because this is the ideal issue for someone who wants to submit his/her first pull request to Symfony.

The work to do is to replace the bottom "icon" legend by text labels inside the table:

```
+----------+----------------------------------------+------------------------------------------+
| State    | Id                                     | Message Preview (en)                     |
+----------+----------------------------------------+------------------------------------------+
| unused   | what.is.component                      | What is a Component?                     |
| fallback | the.components                         | The Components                           |
| unused   | browserkit.summary                     | Simulates the behavior of a web browser. |
| missing  | browserkit.description                 |                                          |
| unused   | classloader.summary                    | Loads your project classes automatica... |
| missing  | classloader.description                |                                          |
| ...                                                                                          |
+----------+----------------------------------------+------------------------------------------+
```

Labels are color-coded as follows:

  * `fallback` in the green color displayed by the `<info>` console tag
  * `missing` in red used for errors
  * `unused` in the yellow/orange color displayed by the `<comment>` console tag

**Comment by stof** [comment]
I agree it would be easier to understand. I vote for tagging as Easy-pick

**Comment by skafandri** [comment]
I added an *explicit-state* optional argument. The reason: we have some bash scripts that run `translation:debug` command and parse the output to send us some notifications or run some other scripts, so being able to keep the old output format would be nice to other people parsing the command output.

**Comment by xabbuh** [comment]
@skafandri Does it make sense to add a dedicated format for such parsers (like XML or YAML)?

**Comment by skafandri** [comment]
@xabbuh Absolutely, the problem is that this command (among others) doesn't support the `--format` option. As a future improvement, it would be nice that all commands supports the `--format` argument. For the actual case, is not only the format (currently being parsed with a regex) but the **expected values**. 
I don't see any problem keeping the old display style intact while adding a new option.

**Comment by javiereguiluz** [comment]
@skafandri I understand that you need to maintain the old behavior of the command for BC reasons. But introducing an option just to tweak the output of the command looks wrong to me. What about postponing these changes for Symfony 3.0?

**Comment by skafandri** [comment]
@javiereguiluz If this will be postponed to Symfony 3.0 then I would not be happy with this change because what I did here is kind of hackish :)
I suggest to have a base abstract command that abstracts common behaviours and provide helpers for output formatting (I know that they are already some helpers but I am referring to more powerful ones) the way JQgrid or most Java Swing components works.
If you like the concept, I can develop further my idea.
