### ISSUE TITLE
Translation PoFileLoader and locale_fallbacks 

### ISSUE THREAD

**Issue by Junker** [symfony/symfony#13881]
if some rows not translated(empty) in secondary language, then shows empty message instead fallback message. 
Fix:
    private function addMessage(array &$messages, array $item)
    {
    ......
        } elseif (!empty($item['ids']['singular'])) {
            if (!empty($item['translated']))
                $messages[stripcslashes($item['ids']['singular'])] = stripcslashes($item['translated']);
        }
    }

**Comment by xabbuh** [comment]
@Junker Is this the same as described in #13483?

**Comment by aitboudad** [comment]
I think it's the same of #13483 and to my knowledge the po dumper avoid dump and empty translated row.
