### ISSUE TITLE
http_method_override not working for PUT

### ISSUE THREAD

**Issue by advancingu** [symfony/symfony#13880]
In Symfony 2.6.4, I am submitting a form with a hidden ``_method`` field of value ``PUT`` to an application that has ``http_method_override`` set to ``true``.

The form submission however always fails with error ``This form should not contain extra fields.``. From the debug toolbar, I can see that the form was correctly submitted with ``POST`` together with the hidden ``_method`` field containing ``PUT``. If I remove the ``_method`` field and submit with ``POST`` everything works fine.

How is it possible that I am seeing this error? I can't find anything that is not according to the documentation of this feature.

**Comment by dmaicher** [comment]
Do you have a proxy (cache) in front of your app? Just asking because then you also need to do this:

https://github.com/symfony/symfony-standard/blob/2.7/web/app.php#L26

**Comment by advancingu** [comment]
I think it was caused by a bundle that was installed. I started a new, clean project in the same server environment, and the issue doesn't appear anymore. Closing for now.
