### ISSUE TITLE
Validator does not pass the object along all the time

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#13885]
I'm talking about the following piece of code:

````
        if (null !== $constraints) {
            // You can pass a single constraint or an array of constraints
            // Make sure to deal with an array in the rest of the code
            if (!is_array($constraints)) {
                $constraints = array($constraints);
            }

            $metadata = new GenericMetadata();
            $metadata->addConstraints($constraints);

            $this->validateGenericNode(
                $value,
                null,
                is_object($value) ? spl_object_hash($value) : null,
                $metadata,
                $this->defaultPropertyPath,
                $groups,
                null,
                TraversalStrategy::IMPLICIT,
                $this->context
            );

            $this->context->setNode($previousValue, $previousObject, $previousMetadata, $previousPath);
            $this->context->setGroup($previousGroup);

            return $this;
        }
````

Why should that piece of code ignore the original object entirely and pass NULL? Don't we want the context inside the validators still have access to it?

**Comment by webmozart** [comment]
The context has access to the object anyway via getValue(). Can you describe the problem you are facing?

**Comment by xabbuh** [comment]
ping @dawehner

**Comment by dawehner** [comment]
We (primarily @fago and @webmozart ) worked on rewriting our Validator to be less generic and just bound to our domain which was a huge success, given that its now actually understandable what is going on.

At least for myself I also don't remember exactly under which circumstances this errors appeared, so feel free to close it.

Thank you for the reminder :)
