### ISSUE TITLE
Why does the DebugHandlersListener's exceptionHandler configuration process depend on HttpKernel and not Kernel?

### ISSUE THREAD

**Issue by periklis** [symfony/symfony#13898]
While upgrading our application to symfony 2.6 incl. DebugBundle we ran into a strange behavior of our Tests on KernelEvent-based Events.

For example, putting in a simple Testcase the following runs into a LogicException:
```php
$requestEvent = new GetResponseEvent($this->appKernel, new Request(), null);
$this->dispatcher->dispatch(KernelEvents::REQUEST, $requestEvent);
```
```
LogicException: The exception handler must be a valid PHP callable.
```
After some backtracing in the debugger i could point the problem in DebugHandlersListener.php Line 96:
```php
if (!$this->exceptionHandler) {
    if ($event instanceof KernelEvent) {
        $this->exceptionHandler = array($event->getKernel(), 'terminateWithException');
```
The issue is located in our default symfony AppKernel setup, which extends from Symfony\Component\HttpKernel\Kernel and not from Symfony\Component\HttpKernel\HttpKernel. The method terminateWithException is only part of the HttpKernel. However, our Testcase is based on the standard WebTestCase of the Framebundle, which boots the Kernel found in the phpunit.xml directory, which is our default AppKernel.php

Can someone explain why the DebugHandlersListener has a dependency to HttpKernel? Is this an intended behavior or a bug?

**Comment by stof** [comment]
The kernel passed in the event is the one triggering the event, which is **not** the AppKernel but the HttpKernel. So you would have to perform additional debugging (or provide more info about your setup) to let us know where your event comes from with the wrong kernel)

**Comment by periklis** [comment]
Thanks for the fast response. Pointing to the fact that the event is triggered with a passed HttpKernel and **not** AppKernel resolved our issue.
False event setup:
```php
$requestEvent = new GetResponseEvent($this->appKernel, new Request(), null);
```
Corrent event setup:
```
$requestEvent = new GetResponseEvent($this->get('http_kernel'), new Request(), null);
```

**Comment by stof** [comment]
@periklis why are you triggering the event yourselves ?

**Comment by periklis** [comment]
@stof: These are some older testcases from symfony 2.1 times, where some developers tested own written events, which extend from KernelEvent. I think this issue points to some technical debt, which needs asap a clean up
