### ISSUE TITLE
[Serializer] Call  to a normalize() function on SerializerInterface in PropertyNormalizer 

### ISSUE THREAD

**Issue by Gasol** [symfony/symfony#13909]
I encounter the problem as following error message. Apparently, SerializerInterface does not have  normalize function. It must be mistake here.

```
PHP Fatal error:  Call to a member function normalize() on a non-object in 
/path/to/project/vendor/symfony/serializer/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php 
on line 71
```

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php#L71

**Comment by Gasol** [comment]
`Symfony\Component\Serializer\SerializerInterface` does not have normalize function, But `Symfony\Component\Serializer\Serializer` does.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L108

```php
<?php
if (!$this->serializer instanceof NormalizerInterface) {
    throw new LogicException(sprintf('Cannot normalize attribute "%s" because injected serializer is not a normalizer', $attribute));
}
```

So, I think the problem is:

1. Wrong type hinting in setSerializer, should be `Symfony\Component\Serializer\Serializer`, not `Symfony\Component\Serializer\SerializerInterface`
2. misuse of SerializerInterface (Obviously, $serializer is not a normalizer)

**Comment by dunglas** [comment]
@Gasol can you provide the code you made to initialize your serializer and normalizer? Is your Serializer an instance of `NormalizerInterface`?

1. The typehint is correct. If you don't typehint on the interface, use of custom serializers will be impossible.
2. The default Serializer is: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L38

IMO the proper fix is to add a check that the given `Serializer` implements `NormalizerInterface` in `PropertyNormalizer` as it is done in `ObjectNormalizer`.
