### ISSUE TITLE
[Form][Transformer][discussion] Transformer failing handling

### ISSUE THREAD

**Issue by leberknecht** [symfony/symfony#13910]
Hi! I want to discuss how the "transformer is not able to transform the given value" case is handled. Currently in modelToNorm, normToModel, normToView and viewToNorm methods, we iterate over the given transformers and if one fails, we say "ok, this will not work". 

Actually, there might be a transformer available that wont fail, so i think the current state is not optimal..? 

I think there are several things that we could do here:
a) try-catch the transform-operation, if one transformer doesnt fail, return the result => not cool, i think we dont wanna catch exceptions, as they are..well, exceptions. 
b) change the transformers to return for example "false" instead of throwing an exception, keep the foreach-loop, if one transformer doesnt fail, return that result. if all transformers fail => throw the exception. Problem here: what to do with transformers that are transformer something into boolean values?
c) Limit transformers to one transformer. If a new transformer is attached, throw away the old ones. => i've no idea what impact this would have on the rest of the framework..?
d) something completly different?

Ahoi!

**Comment by stof** [comment]
@leberknecht Transformers are not something meant to be used based on whether they can support the value or no. We have a stack of transformers, and each one must transform the value returned by the previous one.

Returning ``false`` on failure is impossible: it means a transformer cannot return ``false`` as a transformed value, which is a huge BC breaks

Limiting to 1 transformer is a huge BC break and would limit the flexibility of the Form component a lot. Adding a new transformer to transform the value returned by the previous transformer is a perfectly valid use case, and one of the reason the form hierarchy is so powerful.

I think your whole suggestions are based on the fact that you expect a totally different system for transformers than what the Form component contains.

**Comment by leberknecht** [comment]
Ahh! You are right, i misunderstood why we have the loop there! Sorry for that!
=> closed
