### ISSUE TITLE
What about injecting Doctrines Types easily ?

### ISSUE THREAD

**Issue by fpiccinali** [symfony/symfony#13917]
Hello,
we can inject doctrine.event_listener or doctrine.event_subscriber as service.
But there is no way to inject "Doctrine\DBAL\Types"

Use case:
- i want a new Doctrine/Type ZipCode from my bundle AdressBundle.
- i do not want to add the type in app/config.yml, i want it automatically when my bundle is activated. 

Today, i can add in AdressBundle/service.xml : 
```html
<parameters>
    <parameter key="doctrine.dbal.connection_factory.types" type="collection">
                <parameter key="zipcode" type="collection">
                    <parameter key="class">fazae\Adress\Doctrine\Types\ZipcodeType</parameter>
                    <parameter key="commented">true</parameter>
                </parameter>
</parameters>
```

But in this case it is no longer possible to add other DoctrineTypes from config.yml or from $container->loadFromExtension('doctrine'.... It is not "pluginable"

Is there another way to activate Doctrine Types ?

If not,  what about adding a new tag in services ?

Something like "doctrine.type": 
```html
<service id="doctrine.types.zipcode" class="fazae\Adress\Doctrine\Types\Zipcode">
            <tag name="doctrine.type"/>
        </service>   
```

I also tried with DoctrineListeners on loadClassMetaData. But it need to check all properties and annotations. This is not the best value.

If you think this demand is useful, I can take care of its implementation.

**Comment by aitboudad** [comment]
This feature is not related  to symfony, so can you report this to [DoctrineBundle](https://github.com/doctrine/DoctrineBundle) :)

**Comment by stof** [comment]
See https://github.com/doctrine/DoctrineBundle/issues/336#issuecomment-58882150 for my reasons why I think tagging a service is a very bad idea.

Closing in favor of https://github.com/doctrine/DoctrineBundle/issues/336 anyway.

**Comment by fpiccinali** [comment]
@stof. Thanks for the advice. I try your trick. 
When you said: "But registering a type is a matter of registering a class, not an instance", 
About tag twig.extensions: isn't it the same case ?

**Comment by stof** [comment]
@fpiccinali to answer you (even if it is late after your comment), no it is not. Twig expects receives instances when registering extensions. Doctrine expects receiving class names and will instantiate them itself (which is not friendly with DI but this decision was made early in the Doctrine development, when DI was not yet common in PHP)
