### ISSUE TITLE
Form behaves differently on checkboxes when using the bootstrap form theme

### ISSUE THREAD

**Issue by chuckypapa** [symfony/symfony#13926]
Hi. When I'm using the Bootstrap 3 form themes with my forms, it seems the checkbox's labels are always rendered, no matter what.

Using the following code:
```php
$form = $this->createFormBuilder()
	->add('field','checkbox',array(
		'label' => false,
	))
->getForm();

return $this->render('default/index.html.twig',[
	'form' => $form->createView(),
]);
```

```
{{ form_start(form) }}

	{{ form_widget(form.field) }}

{{ form_end(form) }}
```

The form does not show a label for the checkbox, however, if I enable the bootstrap form theme (same with the horizontal version):
```yaml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
```

The form will show a checkbox, and a label with text "Field"
I found no information about this behavior in the documentation.

Using the bootstrap theme also suppresses the form_label twig function.

So, the following code: 

```twig
{{ form_start(form) }}

	{{ form_label(form.field) }}
	<hr>
	{{ form_widget(form.field) }}

{{ form_end(form) }}
```

If **not using** the **bootstrap** theme, and form **label** is **not set to false**, produces
```
Field
*horizontal line*
*checkbox*
```

**not using** the **bootstrap** theme, and form **label** is set to **false**, produces
```
*horizontal line*
*checkbox*
```

**using** the **bootstrap** theme, and form **label** is **not set to false**, produces
```
*horizontal line*
*checkbox* Field
```

**using** the **bootstrap** theme, and form **label** is **set to false**, produces
```
*horizontal line*
*checkbox* Field
```

To actually hide the label, I have to set the label to show one space. Found no way to relocate it though.

I just tested this on a fresh install of  Symfony 2.6.4

What do you think?

**Comment by WouterJ** [comment]
Thank you for your investigation of this bug, @chuckypapa!

However, someone has already found this bug and fixed it in https://github.com/symfony/symfony/pull/13806 . That fix is now included in the 2.6.5 release (which is released last week). You can savely update to 2.6.5 and everything will work as expected.

So this issue can be closed :)
