### ISSUE TITLE
[Process] ExecutableFinder throws a warning if open_basedir is active and a non-existent directory is in the allowed directories list

### ISSUE THREAD

**Issue by a-chris** [symfony/symfony#13929]
On line 59 (https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Process/ExecutableFinder.php#L59) ExecutableFinder checks if paths in open_basedir php config are directories.
This check throws a php warning if one path is non-existent.

The only solution I can think about it is to suppress warning with the @ operator.

For reference: https://bugs.php.net/bug.php?id=69240

**Comment by cbj4074** [comment]
In my case, this is a problem all of a sudden, now that Laravel is using this method:

https://github.com/laravel/framework/commit/a4dd6e6f193a09c6ac33e4ec70f5ca8c31606675#diff-10d465d9a443ced0d8b1b9c8b9560ccfR41

I've submitted a Pull Request that provides a short-term workaround, until the underlying bug in PHP is fixed:

https://github.com/symfony/symfony/pull/16182

**Comment by cbj4074** [comment]
Thank you to everyone involved in addressing this issue! (On a Friday, no less!) Your timely attention is sincerely appreciated. Have a great weekend.
