### ISSUE TITLE
[Form] form_start doesn't care about passed in 'attr'

### ISSUE THREAD

**Issue by wideawake** [symfony/symfony#13936]
Hi,

with the following code in the rendered html I can't see any of my attributes given in the attr var of the form_start() function.

Framework Version 2.6

Thanks

```twig
{% extends ':default/widget:blank.html.twig' %}

{% block page_title %}Location{% endblock %}
{% block page_subtitle %}Edit{% endblock %}

{% block page_content %}
    {{ form_start(edit_form) }}

    {{ form_widget(edit_form) }}

    {% include ':default/table-actions:submit.html.twig' with {label: 'updatea', type: 'primary'} %}

    {{ form_end(edit_form) }}

    <br/><br/>
    {{ form_start(delete_form, { 'attr': {'class': 'just-testing', 'id': 'just-hoping'}}) }}
    {% include ':default/table-actions:submit.html.twig' with {label: 'delete', type: 'danger'} %}
    {{ form_end(delete_form) }}

{% endblock %}
```

**Comment by dupuchba** [comment]
There should not be any problems..

```
{%- block form_start -%}
    {% set method = method|upper %}
    {%- if method in ["GET", "POST"] -%}
        {% set form_method = method %}
    {%- else -%}
        {% set form_method = "POST" %}
    {%- endif -%}
    <form name="{{ name }}" method="{{ form_method|lower }}" action="{{ action }}"{% for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}{% if multipart %} enctype="multipart/form-data"{% endif %}>
    {%- if form_method != method -%}
        <input type="hidden" name="_method" value="{{ method }}" />
    {%- endif -%}
{%- endblock form_start -%}
```

Can you share your DeleteFormType ?

**Comment by wideawake** [comment]
Sure..
```php

return $this->createFormBuilder()
            ->setAction($this->generateUrl('route_delete', array('id' => $entity->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
```

**Comment by dupuchba** [comment]
Don't see anything un-usual, can you inspect the `element`and tell us how the form is generated ?

**Comment by wideawake** [comment]
I have already done and it has the class 'form-horizontal' but not the one I specified. And of course it doesn't have the id property set.

**Comment by jzawadzki** [comment]
it works fine for me on (almost) clear instalation (with both id & class)

You have form-horizontal class.
Are you using ```bootstrap_3_horizontal_layout.html.twig``` directly 
or you have some specific form theme applied that extend horizontal one?

**Comment by wideawake** [comment]
I'm using mopa bootstrap.. but I never faced this kind of issue..

**Comment by jzawadzki** [comment]
hmm there is no ```form-horizontal``` class used in mopa bootstrap
do you have anything set in ```config.yml``` under
```
framework:
    templating:
        form:
            resources:
```
or in 
```
{{ form_theme form ... }}
```
?

**Comment by wideawake** [comment]
nope..
and this is my mopa config:
```yml
mopa_bootstrap:
    form:   # Adds twig form theme  support
      show_legend: false
      checkbox_label: 'label' # default is both (label|widget|both)
    menu: ~  # enables twig helpers for menu
```

as you can see I'm using the default mopa configuration..

Mopa version is: v3.0.0-beta4

**Comment by dupuchba** [comment]
Can you trie to create the error in an empty project ?

**Comment by wideawake** [comment]
@jzawadzki already tested this aspect..

Do you think it's mopa related?

**Comment by wideawake** [comment]
Problem solved but I don't know how. I haven't updated deps through composer so nothing changed.

I'll report news as soon as I get some.

**Comment by jamm-kevin** [comment]
Same issue for about an half hour... : refreshing cache did the job to get it work
