### ISSUE TITLE
[Serializer][2.7] Simplify ClassMetadata replacement in the default metadata factory

### ISSUE THREAD

**Issue by Ener-Getick** [symfony/symfony#13931]
I think that it would be great to add a constant or something else in Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory that allows to simply replace the ClassMetadata.

If i extend the factory, i can't to change the class within copy the entire function getMetadataFor().

Is it possible to add a constant that contains the class namespace or just a function that returns the ClassMetadata instanciated ?

**Comment by dunglas** [comment]
Why don't you create a custom factory (not extending `Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory`) that implement the interface?

**Comment by Ener-Getick** [comment]
Because this factory is well made and integrates the majority of needs.
So, yes i can create a custom factory but i think this isn't productive.

**Comment by dunglas** [comment]
Maybe a `protected` factory method instead of a constant?

**Comment by Ener-Getick** [comment]
Yes it's probably the best. Do you want me to make a pull request ?

**Comment by dunglas** [comment]
It would be nice!

**Comment by Ener-Getick** [comment]
Moreover it may be split of the serializer ? 
This metadata factory is really great and could be used for other projects.
