### ISSUE TITLE
[Semantical Error] The annotation "@Symfony\Component\Validator\Tests\Constraints\NotBlank" in property Blog\ModelBundle\Entity\Post::$title does not exist, or could not be auto-loaded.  

### ISSUE THREAD

**Issue by redjanbet** [symfony/symfony#13932]
On this module:
<?php

namespace Blog\ModelBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Tests\Constraints as Assert;

/**
 * Post
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Post extends Timestampable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=150)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="body", type="text")
     * @Assert\NotBlank
     */
    private $body;

    /**
     * @var Author
     *
     * @ORM\ManyToOne(targetEntity="Author", inversedBy="posts")
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id", nullable=false)
     * @Assert\NotBlank
     */
    private $author;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return Post
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }
}

I'm having this error when i try to update the schema: 
php app/console doctrine:schema:update --force

------------------- Error ------------------
[Doctrine\Common\Annotations\AnnotationException]                                                                                                    
  [Semantical Error] The annotation "@Symfony\Component\Validator\Tests\Constraints\NotBlank" in property Blog\ModelBundle\Entity\Post::$title does n  
  ot exist, or could not be auto-loaded. 

Thank you in advance.

**Comment by jzawadzki** [comment]
You use wrong import (you have linked to tests not to actual code):
type
`use Symfony\Component\Validator\Constraints as Assert;`
instead of
`use Symfony\Component\Validator\Tests\Constraints as Assert;`

**Comment by ymRed** [comment]
Thank You jzawadzki.

**Comment by celinmariya** [comment]
I am getting error as,
[Doctrine\Common\Annotations\AnnotationException]                                                                                             
  [Semantical Error] The annotation "@Doctrine\ORM\Mapping\Entity" in class AppBundle\Entity\Book does not exist, or could not be auto-loaded.  
 when I try to execute the command       
  php bin/console doctrine:generate:entities AppBundle/Entity/Book .I am very new to symfony and don't Know from where to start.
My Book.php is (AppBundle\Entity)
<?php 
namespace AppBundle\Entity; 


use Doctrine\ORM\Mapping as ORM; 
 

/** 
 *  @IgnoreAnnotation("fn")
   * @ORM\Entity 
   * @ORM\Table(name = "Books") 
*/  
class Book { 
   /** 
   
      * @ORM\Column(type = "integer") 
      * @ORM\Id 
      * @ORM\GeneratedValue(strategy = "AUTO") 
   */ 
   private $id;  
   
   /** 
      * @ORM\Column(type = "string", length = 50) 
   */ 
   private $name;  
    
   /** 
      * @ORM\Column(type = "string", length = 50) 
   */ 
      
   private $author;
   /** 
      * @ORM\Column(type = "decimal", scale = 2) 
   */ 
   private $price; 
} 

Controller is
<?php
namespace AppBundle\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route; 
use Symfony\Bundle\FrameworkBundle\Controller\Controller; 
use Symfony\Component\HttpFoundation\Response;  

class BooksController extends Controller{ 
   /** 
      * @Route("/books/author") 
   */ 
   public function authorAction() { 
      return $this->render('store/author.html.twig');
   } 
}

?>

Autoload.php is
<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitfad6c26e074f2ac7475a9fe46f7b5d6b::getLoader();
