### ISSUE TITLE
[Console] Show description in help <command>

### ISSUE THREAD

**Issue by mnpenner** [symfony/symfony#13943]
When you run `<cli-tool> help <command>` it shows you the `Usage` and `Options` but not the command description. It would be nice to have the description in there too.

**Comment by fabpot** [comment]
I think it's not needed as besides the usage and the options, you also have the help, which is an extended description. The description is there for listing.

**Comment by cordoval** [comment]
If the description is just for listing then why it is displayed in other formats?
