### ISSUE TITLE
[Session] decrease gc probability

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#13956]
We changed the PdoSessionHandler and MongoDbSessionHandler to not return expired session data.
With that in place, PHP's default gc probability of 1/100 is unnecessary high. Every 100th request is slowed down for no reason. We should change that somehow by default to be lower. Maybe it's just something for the docs or the standard-distribution.
Deleting old rows also has negative impact on concurrency when a table scan has to be performed.

Todo: Check if NativeFileSessionHandler also checks expiry when reading, i.e. set gc probability to zero and see if old session data still returned.
Edit: Native php session handler does not seem to check the gc_maxlifetime at session start: http://3v4l.org/6J6ij (it returns expired session data when it has not been deleted). This makes no sense since session gc is called randomly so totally unreliable.

See also #13858

**Comment by robertfausk** [comment]
What about letting the check run on ```kernel.terminate```?
So no user won't have any impact.

**Comment by Tobion** [comment]
Not that easy because it doesnt work with the SessionHanlderInterface provided by PHP.

**Comment by Tobion** [comment]
What could be possible is to do the gc in the destructor of the session handler or provide an interface like `DelayableGarbageCollection` whose method is then called on a kernel.terminate event. But this is tricky, because the pdo connection is closed then already, so it would need to reconnect.

**Comment by javiereguiluz** [comment]
@Tobion do you still think we should do this change? Thanks.

**Comment by Tobion** [comment]
yes

**Comment by nicolas-grekas** [comment]
Closing: this is old, and the real best practice is to completely disable the session gc and replace it by a background task.
