### ISSUE TITLE
[DX][Security] Check for server PHP_AUTH_USER

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#13950]
For a server-side payment notification service we authorize the `$request->server` parameters `PHP_AUTH_USER` and `PHP_AUTH_PW`. For complex security annotations we can always implement the [Annotations of the JMSSecurityExtraBundle](http://jmsyst.com/bundles/JMSSecurityExtraBundle/master/annotations), but this seems a bit too much for this simple use-case:

```php
// Authentication check
if (
    $request->server->get('PHP_AUTH_USER') != $this->container->getParameter('security_user') ||
    $request->server->get('PHP_AUTH_PW') != $this->container->getParameter('security_pw')
) {
    throw $this->createNotFoundException();
}
```
What I'd like to propose is that the `@Security` annotation is able to compare the server parameters with the values from the container parameters:

```php
/**
 * @Security("php_auth('%security_user%', '%security_pw%')")
 */
public function showAction(Post $post)
```

**Comment by stof** [comment]
``@Security`` is related to the authorization layer, running voters based on the authenticated user. ``PHP_AUTH_USER`` and ``PHP_AUTH_PW`` on the other hand are related to authenticating the user.
What you need is to enable the http_basic authentication in your firewall.

**Comment by Rvanlaak** [comment]
Enabling http_basic authentication for that route could indeed solve this, but it would be a nice feature if such an easy check can be handled via annotations :+1: 

So, you think an annotation for such basic authentication checks is a no-go?

**Comment by stof** [comment]
@Rvanlaak the issue is that you are asking to mix the authentication and the authorization in the annotation, while they are different concerns.

**Comment by Rvanlaak** [comment]
Doesn't has to be the same annotation, the following would also be great. 

    @Authorization(user="%parameter%", password="%parameter%")

But I notice you aren't convinced of the ease this would offer? :+1:

**Comment by MacDada** [comment]
@Rvanlaak "username" and "password" are not "authorization" concern.

* Authentication deals with finding out who is the person accessing the app.
* Authorization deals with finding out if that person has access to a certain part of the app.

Please read the docs to understand more about this topic:

* http://symfony.com/doc/current/book/security.html
* http://symfony.com/doc/current/cookbook/security/index.html
* http://symfony.com/doc/current/components/security/index.html

Actually this link covers exactly what you're trying to achieve (basic auth):
http://symfony.com/doc/current/book/security.html

You can also use annotations to require specific role for the controller:
http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html

**Comment by Rvanlaak** [comment]
Thanks @MacDada , but I was well aware of most of those pages. My proposition would be to have a specific annotation to check for authentication parameters, to reduce boilerplate code. As nobody sees this as a viable usecase, I'll close this issue.
