### ISSUE TITLE
[Form] Handle document is broken after update to 2.6.5

### ISSUE THREAD

**Issue by drmonty** [symfony/symfony#13961]
After updating Symfony from 2.6.4 to 2.6.5 handling (MongoDB) `document` as Field is broken.

Example FormType:

```
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('terminal', 'document', array('label' => 'terminal', 'required' => false, 'class' => 'company\ExampleBundle\Document\Terminal'));
}
```

Submitted Form is not valid, Profiler told me:

```
Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[terminal] = 546e4a2d46139fca3b413051

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "terminal": The choice "546e4a2d46139fca3b413051" does not exist or is not unique

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
The choice "546e4a2d46139fca3b413051" does not exist or is not unique
```

But document `546e4a2d46139fca3b413051` exists and is unique. Reverting symfony back to 2.6.4 does not lead to this issue and submitted form is valid.

**Comment by drmonty** [comment]
This issue got introduced between commit [8299a44 and eabad39](https://github.com/symfony/symfony/compare/8299a44c27f555c3d299abf2d5e4b554740a6b82...eabad39dd5a93dc020bfb638c96dd774dac8c8d0)

**Comment by drmonty** [comment]
Reverting changes made by commit a10844587b4494c678e8e2095a05f1bb88d06cb2 fixed this issue

**Comment by fabpot** [comment]
ping @guilhermeblanco

**Comment by guilhermeblanco** [comment]
@fabpot will investigate

**Comment by guilhermeblanco** [comment]
@drmonty I need further information to complete the investigation.
We assume you are using a single identifier for your document and it is the field being fetched. We also consider that executing the following query returns a single instance:

```php
$dm->getRepository('company\ExampleBundle\Document\Terminal')->findBy(array(
    '<your_terminal_id_field>' => '546e4a2d46139fca3b413051',
));
```

Can you confirm this for me?

**Comment by drmonty** [comment]
@guilhermeblanco so far, yes, but it should be `findOneBy` instead of `findBy`.

```
$dm->getRepository('company\ExampleBundle\Document\Terminal')->findOneBy(array(
    '_id' => '546e4a2d46139fca3b413051',
));
```

**Comment by guilhermeblanco** [comment]
@drmonty you can't use findOneBy because of multiple => true should be also supported.

**Comment by drmonty** [comment]
@guilhermeblanco then an array will get returned, with one result.

**Comment by guilhermeblanco** [comment]
@drmonty which is expected. The problem you're having happens here:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L52

This happens explicitly when you have type = entity|document and multiple => false.
Can you try to dump the response there and check what it does get back for you?

**Comment by drmonty** [comment]
I've used the following line to dump:

```
error_log("choices: " . json_encode($choices) . ", value: " . json_encode($value));
```

in 2.6.4:

```
choices: [{"__initializer__":null,"__cloner__":null,"__isInitialized__":true}], value: "546e4a2d46139fca3b413051"
```

in 2.6.5:

```
choices: [], value: "546e4a2d46139fca3b413051"
```

**Comment by malarzm** [comment]
@guilhermeblanco @drmonty it exposed that ODM's ``DocumentRepository`` doesn't work properly when ``->findBy(array('id' => array($id)));`` is called however it does work when it is more Mongo-like: ``->findBy(array('id' => array('$in' => array($id))));``

**Comment by jmikola** [comment]
@drmonty: @guilhermeblanco, @malarzm, and I spoke about this and I believe the solution is a revert of a10844587b4494c678e8e2095a05f1bb88d06cb2 and create a new patch that ensures the EntityChoiceList always has a loader instance by defaulting the `query_builder` option to a new query builder if needed. Currently, the absence of a `query_builder` option meant that no loader would be instantiated. ORM and ODM both have loader implementations, which abstract `IN()` queries, and using those will clearly be more optimal than falling back to loading the entire table/collection (which @guilhermeblanco's original commit tried to optimize out).

**Comment by guilhermeblanco** [comment]
All: I'm currently working on a patch to address this
