### ISSUE TITLE
Circular reference exception thrown instead of FileLoaderException

### ISSUE THREAD

**Issue by Epskampie** [symfony/symfony#13963]
In Symfony 2.6.5 and higher, a FileLoaderImportCircularReferenceException is often thrown instead of the real error, making debugging extremely hard. I've written a small script to reproduce the error:

```javascript
# reproduce.sh
php symfony.phar new blog 2.6.5
cd blog/

echo '<?php
namespace AppBundle\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    /**
     * @Route("/reproduce", name="homepage" SYNTAX_ERROR_HERE)
     */
    public function indexAction()
    {
        return $this->render("default/index.html.twig");
    }
}
' > src/AppBundle/Controller/DefaultController.php

php app/console server:run
```

Run this script, then browse to http://127.0.0.1:8000/ . Expected output is a FileLoaderLoadException, but the result is a Circular reference exception.

I think this happens for a lot of exceptions, but I'm sure about this one.

**Comment by stof** [comment]
does it happen also on 2.6.4 or no ?

**Comment by Epskampie** [comment]
No, I've checked 2.6.4, and that version is fine.
Also, I've checked 2.7.x-dev, and the same error occurs there (although the output is slightly different with 2 exceptions shown instead of one).

**Comment by Epskampie** [comment]
Fixed: https://github.com/symfony/symfony/pull/14345
Closing.
