### ISSUE TITLE
data_class in configureOptions(OptionsResolver $resolver) in Form Classes not picked up

### ISSUE THREAD

**Issue by ppounder** [symfony/symfony#13976]
Tested in both 2.6.4 and 2.6.5

Although the 2.6 docs still show to use setDefaultOptions, this is available in FormTypeInterface anymore. And as OptionsResolverInterface is now deprecated, I've changed from:

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Acme\DemoBundle\Document\Enrolment',
        ));
    }

to 

     public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Acme\DemoBundle\Document\Enrolment',
        ));
    }

However I get the following error:
```
The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is   an instance of class Acme\Demo\Document\Enrolment. You can avoid this error by setting the "data_class" option to "Acme\DemoBundle\Document\Enrolment" or by adding a view transformer that transforms an instance of class Acme\DemoBundle\Document\Enrolment to scalar, array or an instance of \ArrayAccess.
```

(Also, unrelated possibly, the html5 date widget doesn't seem to work on the latest Firefox or IE).

Kind regards
Paul Pounder

**Comment by xabbuh** [comment]
The `configureOptions()` method will be part of Symfony 2.7. In Symfony 2.6, you still have to use `setDefaultOptions()`.

**Comment by ppounder** [comment]
Ok, I think I was just confused with the https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.6.md advising that OptionsResolverInterface being deprecated and my IDE showing it as deprecated too.

I'm running setDefaultOptions() even with the warnings and it's working ok. Guess that's why the docs still show setDefaultOptions too then :-)

Cheers, will close.

**Comment by xabbuh** [comment]
@ppounder What kind of warnings do you get? That shouldn't actually happen since the triggers were only added in the `2.7` branch.

**Comment by ppounder** [comment]
I'm using PHP Storm 7.1.3.

In my setDefaultOptions(OptionsResolverInterface $resolver) the OptionsResolverInterface is crossed out and it advises that it's deprecated.

    Referenced entity is deprecated. This usually means that you are advised to remove the usage or replace it with other construct

**Comment by xabbuh** [comment]
I see. PhpStorm also analyses `@deprecated` tags in docblocks. I guess there's nothing we can do here though.

**Comment by ppounder** [comment]
That's fine, I was just concerned in case I should have been using configureOptions in 2.6. But happy that everything is still working :-)
