### ISSUE TITLE
Yaml parser: if the first line starts with spaces, parsing fails

### ISSUE THREAD

**Issue by cirpo** [symfony/symfony#13977]
with this [commit and modification] (https://github.com/symfony/symfony/commit/33bf087a9b683482c75a95a6da177f11eb765763#diff-189db52345d99e1723694ec4a1eea841R201) is not possible anymore to parse lines that starts with spaces.  is the ``trim`` call intended? 

having spaces at the beginning of the line is breaking any yaml specs?

thanks

**Comment by xabbuh** [comment]
If I understand [the specification](http://www.yaml.org/spec/1.2/spec.html#id2788859) correctly, leading whitespaces are not allowed:

> In addition to a restricted character set, a plain scalar must not be empty, or contain leading or trailing white space characters.

**Comment by cirpo** [comment]
@xabbuh fine, but this breaks BC :)

**Comment by stof** [comment]
@cirpo what is your YAML file breaking after this change ?

**Comment by cirpo** [comment]
@stof I'm parsing a yaml file dynamically generated from a twig file. The twig file(s) contains spaces and I'm getting the `ParseException` : https://github.com/symfony/symfony/blob/d64cb493af3e09bd61495309dd22c8e5a8d2efc3/src/Symfony/Component/Yaml/Parser.php#L281L285

Basically the [condition](https://github.com/symfony/symfony/blob/d64cb493af3e09bd61495309dd22c8e5a8d2efc3/src/Symfony/Component/Yaml/Parser.php#L237) is false and goes to the [default switch case](https://github.com/symfony/symfony/blob/d64cb493af3e09bd61495309dd22c8e5a8d2efc3/src/Symfony/Component/Yaml/Parser.php#L281).

I faced this issue upgrading from Symfony 2.6.3 to Symfony 2.6.5. Everything was fine since Symfony 2.1, that's why I think this is a breaking change (and I don't have just one yaml generated file.

**Comment by xabbuh** [comment]
@cirpo Can you show a small example of such a file?

**Comment by cirpo** [comment]
Sure.
The template:
```twig
{% if locale("en_ae") and lang("en")%}
    { meta_description:'This is meta_description for {{ b.name }}', meta_keywords:'This is meta_keywords for {{ c.name }} twig Response', page_title:'This is page_title for {{ c.name }} twig Response' }
{% elseif locale("en_ae") %}
    { meta_description:'This is meta_description for {{ c.name }}' }
{% endif %}
```
It get parsed by Twig and then by the Yaml parser. 
```$this->value``` is 
```      { meta_description:'This is meta_description for xxxx',  meta_keywords:'This is meta_keywords for xxx twig Response', page_title:'This is page_title for xxx twig Response' }``` with some spaces at the beginning (and even inside, for example 'page_title'.

the comparison is done with ```trim($value)```, that, of course, will fail.

**Comment by stof** [comment]
@cirpo whitespaces are significant in YAML. So if you generate it from Twig, you must be very careful with whitespace control to ensure it is done right (and I would avoid this approch entirely and use the Yaml dumper to dump some YAML instead to ensure it is valid).

the issue in your case is that the YAML you are generating is invalid. so failing to parse it is expected

**Comment by cirpo** [comment]
@stof no doubt that is invalid in the yaml specs, we are not discussing it. We are discussing the fact that with sf 2.6.5 (probably even 2.6.4) you're breaking BC. My question is, is it fine? Maybe it prevents the upgrade for other ppl as well

**Comment by stof** [comment]
@cirpo if the Yaml parser was accepting an invalid input previously and does not accept it anymore, I would consider it as a bugfix. Accepting invalid YAML input and parsing it silently as if it was something else does not seem like a supported feature of the component IMO.

**Comment by jakzal** [comment]
I agree with stof. BC doesn't mean we keep all the discovered bugs in. It means we don't change behaviour considered to be correct. Otherwise we wouldn't be able to change any code in minor versions ;)

Unfortunately in this case someone was relying on an invalid behaviour, but notice it's even more likely that someone relies on a correct behaviour of more recent Symfony versions. Nothing we can (nor should) do about it.

**Comment by hacfi** [comment]
Not sure if related but currently I can’t parse my parameters.yml which was generated by incenteev/composer-parameter-handler because of a leading `#`. Looking into the issue at the moment.

**Comment by cirpo** [comment]
we solved on our side trimming the generated files before passing them to the parser.

I think we should close this issue. @stof ?
