### ISSUE TITLE
[TraceableEventDispatcher] incorrect removeListener behavior.

### ISSUE THREAD

**Issue by Akhristenko** [symfony/symfony#13972]
If we try to remove the listener from the dispatcher while dispatching an event, the listener wount be removed.
Simple example:
```php
$eventDispatcher = new TraceableEventDispatcher(new EventDispatcher(), new Stopwatch());
$listener = function ($event, $eventName, $dispatcher) use (&$listener) {
    $dispatcher->removeListener('foo', $listener);
};
$eventDispatcher->addListener('foo', $listener);
$eventDispatcher->dispatch('foo');
$result = count($eventDispatcher->getListeners('foo'));
// expected, that $result == 0, but actually $result == 1
```
That's why, starting from 380d8052ac4f4329c60bb82caed5ed8bf3f6cebe ContextListener works  incorrectly in the debug enviroment.

**Comment by xabbuh** [comment]
Reopening as we need to find a way to fix this for 2.3 too.

**Comment by jakzal** [comment]
@xabbuh any plans on preparing a fix for 2.3?

**Comment by xabbuh** [comment]
@jakzal Sorry, totally forgot about this. Thanks for the reminder. I try to come up with a fix today.

**Comment by xabbuh** [comment]
here we go: #14633
