### ISSUE TITLE
Infinite loop on circular alias references

### ISSUE THREAD

**Issue by speller** [symfony/symfony#13970]
If write following config:

```XML
		<service id="service" alias="service_alias"/>
		<service id="sevice_alias" alias="service"/>
```

Infinite loop will occur in the ResolveReferencesToAliasesPass class. Think such circular references should be catched and an exception should occur instead of falling into infinite loop.

**Comment by unkind** [comment]
I think it was already fixed in #12316.

**Comment by xabbuh** [comment]
@speller Which Symfony version do you use?

**Comment by speller** [comment]
I used old version, now this issue is fixed.Sorry for duplicate...

**Comment by WouterJ** [comment]
Can you please close this issue then, given it was fixed in newer releases of Symfony?

**Comment by xabbuh** [comment]
I'm happy that you're issue could be solved, @speller. Thus, I'm going to close here as we don't need to fix anything in Symfony. :)
