### ISSUE TITLE
[console] Exit code should not be capped, but masked

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#13996]
Inside the console [Application.php](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Application.php#L150), an exit code is capped to 255 if it is larger than 255. This is in agreement with Linux where exit codes are only valid in the 0-255 range. 

However, Linux by default (including most applications, like bash), do not cap, but mask the exit code with `& 255` instead. Accordingly, an application that exits with status code 300 will receive the exit code 44. In a symfony console application, this would be 255. 

Maybe this is something that might be changed as well in the application.php?

**Comment by Tobion** [comment]
Ref #8202

http://www.php.net/manual/en/function.exit.php

Exit statuses should be in the range 0 to 254, the exit status 255 is reserved by PHP and shall not be used. The status 0 is used to terminate the program successfully.

So in php terms we would need to mask with 254 which would also not be consistent with linux.

**Comment by KingCrunch** [comment]
@Tobion It's been a while I found a practical use for bit-operations, but if I remember correctly masking with `254` would mean, that you only can set even numbers, because the lowest bit is missing (`011 & 010 = 010`)

**Comment by jaytaph** [comment]
It seems that a simple php script:

      php -r 'exit(300);' ; echo $?

actually outputs 44 as well  (strace shows `exit_group(300)`, so php does not cap either).

Maybe it would even be better to not handle these situations after all, and remove the cap all together without replacing it with a mask?

**Comment by fabpot** [comment]
@jaytaph If PHP is doing the right thing for us, let's remove the logic on our side.

**Comment by jaytaph** [comment]
@fabpot I think that is a good idea.. however, I do not know what will happen on windows machines. Maybe somebody should verify if this behaviour is the same?

**Comment by Tobion** [comment]
@jaytaph on windows it's not masked. The code below returns 300. So I guess the masking is done by the linux console because in mingw your example also outputs 44.

```
php -r "exit(300);"
echo %ERRORLEVEL%
```

**Comment by jaytaph** [comment]
@Tobion  The cap is actually done by the linux exit_group system call: http://lxr.free-electrons.com/source/kernel/exit.c#L842 Here is the exit code masked with `0xFF` (and shifted, because the lower bits have different meanings, like core dumped,stopped, continued etc).

Same exit result (`44`) works on Darwin too.

It seems that under windows, exit codes are 32-bit signed integers (http://en.wikipedia.org/wiki/Exit_status#Windows), so here no filtering should take place anyway (an `exit(300)` seems valid).

Maybe we should thus get rid of the cap, and not even replace it with a mask? As every supported OS seems to handle this fine, and PHP doesn't really care either way (exit codes are passed directly to the OS), even the 255 reserved code seems to cause no issues (a quick scan through the php core doesn't even seem to suggest 255 should be considered reserved, maybe this is a remnant from past versions).

**Comment by stof** [comment]
Not capping has a severe issue: ``exit(256)`` will then become a 0 exit code on Linux, which is a success one. This is bad (especially as we can use the exception code as exit code)

**Comment by javiereguiluz** [comment]
Closing it for the reasons given by @stof in the previous comment and @Tobion in https://github.com/symfony/symfony/pull/17591#issuecomment-182896954.
