### ISSUE TITLE
Regression: symfony/dependency-injection 2.6.5 fails with PHP maximum nesting level

### ISSUE THREAD

**Issue by SvenRtbg** [symfony/symfony#13998]
I'm using Behat, which uses Symfony components. After updating to the most recent versions, the test failed with this PHP error:

PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Container.php on line 290
PHP Stack trace:
PHP   1. {main}() ***redacted***/vendor/behat/behat/bin/behat:0
PHP   2. Symfony\Component\Console\Application->run() ***redacted***/vendor/behat/behat/bin/behat:31
PHP   3. Behat\Testwork\Cli\Application->doRun() ***redacted***/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Behat\Testwork\Cli\Application->createCommand() ***redacted***/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:96
PHP   5. Symfony\Component\DependencyInjection\ContainerBuilder->get() ***redacted***/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:138
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->createService() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:490
PHP   7. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:941
PHP   8. array_map() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1007
PHP   9. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1007
PHP  10. array_map() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1007
PHP  11. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1007
PHP  12. Symfony\Component\DependencyInjection\ContainerBuilder->get() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1009
PHP  13. Symfony\Component\DependencyInjection\ContainerBuilder->createService() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:490
PHP  14. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:941
PHP  15. array_map() ***redacted***/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:1007
** continues until level 99 from here on **

This update introduced symfony/dependency-injection 2.6.5. When I exclude this version explicitly, 2.6.4 gets installed, and all Behat tests work as expected.

**Comment by nicolas-grekas** [comment]
Does it work when you disable xdebug?

**Comment by SvenRtbg** [comment]
Yes, it works without xdebug.

**Comment by stof** [comment]
Well, looks like the dependency graph is deep enough to reach the limit of 100.

Note that the default nesting limit is higher than 100 in the latest version of XDebug. 100 nested calls is pretty easy to reach when dealing with recursive structures

**Comment by SvenRtbg** [comment]
Setting xdebug.max_nesting_level = 112 works with the 2.6.5 version (111 fails). With the previous 2.6.4 I can get away with max_nesting_level = 91 (90 fails). So the new version increases the nesting by 21 levels for this particular case, or about 20%.

**Comment by iltar** [comment]
I think that in my development environment I have this at 1000, mainly because twig can also reach this number.

**Comment by derrabus** [comment]
We've encountered a similar problem with a Symfony full-stack application. Some change between 2.6.4 and 2.6.5 caused the dependency graph to be significantly deeper. @SvenRtbg, you could investigate with `git bisect` what change caused this problem, but I'm unsure if it's worth fixing, since as @stof and @iltar said, 100 is pretty low for that setting. In general, I would recommend something between 300 and 1000 for Symfony applications.

**Comment by fabpot** [comment]
Closing as there is nothing we can do. Having a limit of 100 is way too low for a typical app.

**Comment by dbaltas** [comment]
The default `max_nesting_level` has been [raised](https://github.com/xdebug/xdebug/pull/145) to 256 on xdebug 2.3.2
