### ISSUE TITLE
Configurator parameters format .. not a yaml nor a json ?  

### ISSUE THREAD

**Issue by Sshuichi** [symfony/symfony#14015]
If you go through the ACME configurator, the final pages states to paste a weird format (not even a json) in your parameters.yml , please check it out.

**Comment by xabbuh** [comment]
@Sshuichi Can you show the exact contents you were suggested to add to the `parameters.yml` file?

**Comment by cordoval** [comment]
I think this issue is documentation and not symfony issue. :+1: for closing this @fabpot or whoever is in charge these days.

**Comment by fabpot** [comment]
Closing as there is no feedback.

**Comment by Xosofox** [comment]
Some thing happened here, on a Win7/xampp install. Here is what ended up in parameters.yml


{ parameters: { database_host: 127.0.0.1, database_port: null, database_name: foo, database_user: bar, database_password: batz, mailer_transport: smtp, mailer_host: 127.0.0.1, mailer_user: null, mailer_password: null, secret: 31db4b7fb9014c0be76798c1c18c224d, database_driver: pdo_mysql, database_path: null } }
