### ISSUE TITLE
[DomCrawler] phpFiles array is generated wrongly for fields with more than one level

### ISSUE THREAD

**Issue by albe** [symfony/symfony#14021]
Symfony DomCrawler is broken for file uploads. It creates a wrongly formatted phpFiles array, when the submit field has more than one level, e.g. "post[upload]" will create

```php
    array(1) {
      ["post"]=>
      array(1) {
        ["upload"]=>
        array(5) {
          ["name"]=>
          string(0) ""
          ["type"]=>
          string(0) ""
          ["tmp_name"]=>
          string(0) ""
          ["error"]=>
          string(1) "0"
          ["size"]=>
          string(1) "0"
        }
      }
    }
```

instead of the expected that PHP creates

```php
    array(1) {
      ["post"]=>
      array(5) {
        ["name"]=>
        array(1) {
          ["upload"]=>
          string(13) ""
        }
        ["type"]=>
        array(1) {
          ["upload"]=>
          string(15) ""
        }
        ["tmp_name"]=>
        array(1) {
          ["upload"]=>
          string(27) ""
        }
        ["error"]=>
        array(1) {
          ["upload"]=>int(0)
        }
        ["size"]=>
        array(1) {
          ["upload"]=>
          int(0)
        }
      }
    }
```

**Comment by xabbuh** [comment]
Hi @albe, I'm not sure if I understand your issue. Can you please provide an example HTML snippet and how you used the DomCrawler component?

**Comment by albe** [comment]
Sorry for the short description. I'm using it in TYPO3 Flow currently for writing (functional) tests. There DomCrawler is used to simulate a browser to send a request from given HTML forms.
But the issue is really just DomCrawler\Form::getPhpFiles() method. That method should provide output that resembles PHP's $_FILES global variable, right?

So here is an example to show the behaviour:

    $html = <<<'HTML'
    <!DOCTYPE html>
    <html>
        <body>
            <form method="post">
                <input type="file" name="post[upload]" />
            </form>
        </body>
    </html>
    HTML;
    $crawler = new \Symfony\Component\DomCrawler\Crawler($html, 'http://localhost');
    $form = $crawler->filterXPath('//form')->form();
    var_dump($form->getPhpFiles());

The output is as given above, while submitting this form in a browser and handling it with PHP var_dump'ing $_FILES, it gives the expected output. Just let me know if you need any further information on this issue.

**Comment by jakzal** [comment]
> That method should provide output that resembles PHP's $_FILES global variable, right?

Correct. I think this is a bug, as here's what we promise in `getPhpFiles()` comment:

>  This method converts fields with the array notation (like foo[bar] to arrays) like PHP does.

*like PHP does* part is currently a lie. Looks like it never worked properly. There's even a test verifying invalid behaviour. Changing it at this point might be problematic due to BC promise :(

**Comment by albe** [comment]
Yeah ok, I understand that :) But really should be adressed in the next major update that is breaking BC

**Comment by albe** [comment]
I created a pull request with a possible solution that I use locally for the time being. That solution is not complete though, since getPhpValues (and maybe other places I don't know of) might need change too. Still in any case you consider fixing this, you can use that as base freely to your liking.

**Comment by dosten** [comment]
This can be closed?

**Comment by jakzal** [comment]
@dosten it hasn't been resolved in any way yet.
