### ISSUE TITLE
Change in EntityChoiceList causes errors in valid form field

### ISSUE THREAD

**Issue by coudenysj** [symfony/symfony#14025]
The change introduced in a10844587b4494c678e8e2095a05f1bb88d06cb2 causes fields that were valid in 2.6.4 to be invalid in 2.6.5.

When I revert that one commit in 2.6.5 the problem is fixed.

The error I get:

```
Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[bundle] = 550fe15080c7e16f5b8b4da0

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "bundle": The choice "550fe15080c7e16f5b8b4da0" does not exist or is not unique

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
The choice "550fe15080c7e16f5b8b4da0" does not exist or is not unique
```

The following line does not convert multiple values into an `$in` query:
```
$this->em->getRepository($this->class)->findBy(array($this->idField => $values));
```

**Comment by xabbuh** [comment]
@coudenysj Can you check if #13961 is the same and if then #13997 fixes the issue for you too?

**Comment by coudenysj** [comment]
@xabbuh It is the same issue, and looks like #13397 will fix it. Will try the patch tomorrow.

**Comment by coudenysj** [comment]
Duplicate of #13961. PR #13997 fixed this.
