### ISSUE TITLE
Symfony2 web profiler return 404 error, js code duplicate in footer

### ISSUE THREAD

**Issue by quaninte** [symfony/symfony#14020]
I just upgraded our project from symfony2.4 to symfony2.6, everything went fine except web profiler is not working correctly, when I page source code, I found web profiler's javascript code are being included twice.

And after web page is loaded, profiler alert "404 message".

I temporary fixed this problem by adding this code: Symfony/Component/HttpKernel/EventListener/ProfilerListener.php

```php
/**
 * Handles the onKernelResponse event.
 *
 * @param FilterResponseEvent $event A FilterResponseEvent instance
 */
public function onKernelResponse(FilterResponseEvent $event)
{
    // Start temporary fix
    static $ran = false;

    if (!$ran) {
        $ran = true;
        return;
    }
    // End temporary fix

    $master = $event->isMasterRequest();
    if ($this->onlyMasterRequests && !$master) {
        return;
    }
```
Can someone upgraded to 2.6, help me a way to solve this problem?

Picture of code duplicated http://i.stack.imgur.com/sW2DY.jpg

**Comment by quaninte** [comment]
After more debugging, I found the issue related to this file 

```php
# Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php

    private function preProcess($eventName)
    {
        $listeners = $this->dispatcher->getListeners($eventName);

        foreach ($listeners as $listener) {
            $this->dispatcher->removeListener($eventName, $listener);
            $info = $this->getListenerInfo($listener, $eventName);
            $name = isset($info['class']) ? $info['class'] : $info['type'];
            $this->dispatcher->addListener($eventName, new WrappedListener($listener, $name, $this->stopwatch, $this));
        }
    }
```

The newly added WrappedListener is duplicated with previous one

**Comment by 1ed** [comment]
You should fork https://github.com/symfony/symfony-standard and reproduce the problem to help people to come up with a fix if needed, but I have projects with 2.6 and the toolbar works as expected there.

**Comment by jeroendesloovere** [comment]
My Web Debug Toolbar also throws error popup... I've searched the internet and did not find a fix.
![schermafbeelding-2015-07-03-om-14 41 03](https://cloud.githubusercontent.com/assets/588616/8499351/33e45b88-2192-11e5-9cd2-8cf7cff5c788.jpg)

**Comment by bestform** [comment]
I can confirm a problem with the newly wrapped listeners in debug mode. 
It boils down to the same issue, where listeners are being called twice when in debug mode. Tried it with symfony 2.7.

**Comment by javiereguiluz** [comment]
After reading @bestform's explanation, I don't know if this issue is really a bug. Under "normal circumstances" (i.e. using the regular Symfony framework) I cannot reproduce it.

**Comment by Tobion** [comment]
To me, registering the `RegisterListenersPass` twice is a user error. So nothing we need to do here.

**Comment by stof** [comment]
and if the listeners are registered twice, I would even consider it as expected that they are called twice. the bug could be the deduplication when lazy-loading...

**Comment by bestform** [comment]
Yes, what @stof said.
That's what I meant to say by  "[...], that the getListeners method of the ContainerAwareEventDispatcher wouldn't ignore duplicates and load and return them twice, as they were added twice."
The  dispatcher should behave consistently no matter how it loads the the listeners.
