### ISSUE TITLE
[Translation] remove null domain inconsistency

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#14040]
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/TranslatorInterface.php uses `$domain = null` as default whereas https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/MessageCatalogueInterface.php uses `$domain = 'messages'` which currently means the same.

Imo we should
1. deprecate domain = null in 2.7 and remove it from 3.0
2. add a constant `TranslatorInterface::DEFAULT_DOMAIN = 'messages'`
3. change signature to `trans($id, array $parameters = array(), $domain = self::DEFAULT_DOMAIN, $locale = null);`
4. <del>https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L122 should also change translation_domain => messages or TranslatorInterface::DEFAULT_DOMAIN</del>

**Comment by stof** [comment]
Your 4th point is not possible, as it would mean that it cannot inherit it from the parent form anymore

**Comment by Tobion** [comment]
@stof true I also found #4328. But this shows that null domain has many different meanings across symfony.

Some reasoning for null domain: https://github.com/symfony/symfony/commit/2a5758f0820c1e8a540dfc1581063813b2f30ed1

**Comment by Tobion** [comment]
So to implement this we would basically need to revert #14041 in order to not throw deprecation warnings from twig or form.

**Comment by Tobion** [comment]
Remvong the `domain = null` might cause too much trouble for not much gain. So I would propose to go the opposite route to make things consistent.

1. add a constant TranslatorInterface::DEFAULT_DOMAIN = 'messages'
2. change signature of MessageCatalogueInterface to use null as well
