### ISSUE TITLE
[Form] EntityType breaks DocumentType n 2.3.26 upgrade

### ISSUE THREAD

**Issue by arendjantetteroo** [symfony/symfony#14054]
I've just upgraded my project from 2.3.25 to 2.3.26 and now one of my tests fails. 

A form with a document collection element is no longer working, the form returns "this value is not valid" on the id that is returned from the selectbox. This works fine in 2.3.25. 

Looking at the changes made to 2.3.26, nothing really stands out as what might cause this. 

Any pointers what i could look at?

**Comment by arendjantetteroo** [comment]
Run  a git bisect which points to the following commit: 
a10844587b4494c678e8e2095a05f1bb88d06cb2 is the first bad commit
commit a10844587b4494c678e8e2095a05f1bb88d06cb2
Author: Guilherme Blanco <guilhermeblanco@gmail.com>
Date:   Thu Feb 5 17:41:00 2015 +0000

    Optimize EntityType by only loading choices for values in the same way that EntityLoader customization does (if you provide a query_builder).

**Comment by arendjantetteroo** [comment]
Ok, so this is a known problem:  https://github.com/symfony/symfony/issues/13961 
@fabpot are there plans to release a new 2.3.x version soon?

**Comment by jakzal** [comment]
@arendjantetteroo closing as #13997 was merged.
