### ISSUE TITLE
ParseException in behat.yml 

### ISSUE THREAD

**Issue by sharanKumar** [symfony/symfony#14051]
behat,yml looks like this

    default:
      firefox:
       context:
           parameters:
                Browser_Name: firefox
       extensions:
                Behat\MinkExtension\Extension:            
                base_url: https://google.com
                javascript_session: selenium2
                browser_name: firefox
                goutte: ~
                selenium2: ~

I am getting this exception 

       [Symfony\Component\Yaml\Exception\ParseException]  Indentation problem in "D:\\mypgms\\behat.yml" at line 7 (near " extensions:").

Please let me know where i have gone wrong .

**Comment by jakzal** [comment]
Looks like indentation is not consistent in your file. Yaml is very white-space sensitive.

Anyway, we don't use github issues for support. Please use irc or mailing list. Thanks.
