### ISSUE TITLE
insulate() breaks functional tests

### ISSUE THREAD

**Issue by aimeos** [symfony/symfony#14062]
After adding $client->insulate() to our functional tests, they fail with the error below (see https://travis-ci.org/aimeos/aimeos-symfony2/jobs/55864940 for details):

Fatal error: Class 'Symfony\Component\HttpKernel\Kernel' not found in /home/travis/build/aimeos/aimeos-symfony2/Tests/Fixtures/app/AppKernel.php on line 9

Call Stack:
0.0001 621608 1. {main}() -:0
0.0003 638512 2. require_once('/home/travis/build/aimeos/aimeos-symfony2/Tests/Fixtures/app/AppKernel.php') -:6

ERROR OUTPUT: PHP Fatal error: Class 'Symfony\Component\HttpKernel\Kernel' not found in /home/travis/build/aimeos/aimeos-symfony2/Tests/Fixtures/app/AppKernel.php on line 9

PHP Stack trace:
PHP 1. {main}() -:0
PHP 2. require_once() -:6

**Comment by aimeos** [comment]
Any news on this? Our tests break regularly at the moment because of old data in the test session but it's completely random when this happens. insulate() seems that it could help if it would work.

**Comment by jakzal** [comment]
It's not a bug.

The script that's generated to run in a separate process [looks for an autoloader file](https://github.com/symfony/FrameworkBundle/blob/d90650905dbe8f99f13b8f2ef44051cf223a3482/Client.php#L169-L174) in the same directory the kernel is located. That's where the `autoload.php` file is located in a Symfony Standard Edition. 

Your Fixtures project doesn't have an autoloader. Either copy it from the Standard Edition (and adapt the paths), or include the composer's autoloader:

```php
<?php
// Tests/Fixtures/app/autoload.php

require_once __DIR__.'/../../../vendor/autoload.php';
```
