### ISSUE TITLE
[Security] Cannot modify token attributes when impersonating an user

### ISSUE THREAD

**Issue by ajgarlag** [symfony/symfony#14065]
I have an **authentication success listener** that adds a **required attribute** to the **authenticated token**, but I cannot use the switch user feature, because there is no way to add this attribute to the switched user token.

When the `SwitchUserFirewall` is triggered, it [creates a new `UsernamePasswordToken`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L139) with a least the `ROLE_PREVIOUS_ADMIN` so it creates a new authenticated token, but no `security.authentication.success` is dispatched, and my listener do not add the required attribute.

Then, a [`security.switch_user` event is dispatched](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L143), with a reference to the `Request` and to the `User`, but there is no reference to the created token, so there is no way to add the token attribute here.

So, I see two different solutions here:
1. Dispatch a `security.authentication.success` when the new authenticated `UsernamePasswordToken` is created (Not sure if this is BC)
2. Add a third optional parameter to the `SwitchUserEvent` constructor to reference the token.

I can submit a PR with the preferred option.

**Comment by Renrhaf** [comment]
Moreover, using the authorization checker service inside a listener to the switch user event can lead to some troubles. In my particular case I want to build some session data depending on the user role. But the token storage sill hold the previous user one, thus leading to incorrect data stored in my session.

So either we could add the token to the SwitchUserEvent here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L143

Either we could move the event dispatch after this line https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L87

What do you think ?

**Comment by xabbuh** [comment]
This was implemented in #21951.
