### ISSUE TITLE
Towards PHP 7 compatibility

### ISSUE THREAD

**Issue by stof** [symfony/symfony#14086]
PHP 7 is meant to be released at the end of the year. At this time, our supported versions will be 2.3, 2.6 (security-only), 2.7 and 3.0. Each of these versions will need to be compatible with PHP 7.

Currently, Travis is running our testsuite against PHP 7 nightly, showing that this goal is not yet reached.

A bunch of tests are triggering fatal errors. We should debug the reason for that, to see whether it is a regression in PHP (which should be reported to them as soon as possible) or something related to one of the PHP 7 BC breaks, requiring to fix our code:

- form tests: https://travis-ci.org/symfony/symfony/jobs/56106607#L355
- security tests: https://travis-ci.org/symfony/symfony/jobs/56106607#L411
- translation tests: https://travis-ci.org/symfony/symfony/jobs/56106607#L562 ``string`` cannot be used as class name (reserved because of scalar type hints)

Except these components where we cannot run tests because of these errors, the only remaining failures on PHP 7 for Symfony 2.3 (you can check Travis builds for other branches to see whether there are more in newer versions) are the parsing of hexadecimal numeric strings in XmlUtils and Yaml because PHP 7 does not cast them as int anymore. We will need to implement this conversion separately.
It would be great to start working on the PHP 7 compatibility soon (especially for the issue with class names being reserved because it might require deprecating a class name in favor of a new one, which should be done before the 2.7 release)

**Comment by Tobion** [comment]
For Translation component: #14087

**Comment by dosten** [comment]
The Security test seems to be a phpunit issue

**Comment by xabbuh** [comment]
@dosten Did you see an open issue at the PhpUnit repo?

**Comment by dosten** [comment]
@xabbuh No, i see that the error come from here https://github.com/symfony/security-core/blob/master/Tests/Authentication/Token/RememberMeTokenTest.php#L55-L62.
Seems that PHPUnit is not catching the exceptions in PHP7.

**Comment by Tobion** [comment]
That test doesn't make sense. You don't test against phpunit exceptions.

**Comment by Tobion** [comment]
See #14088

**Comment by stof** [comment]
See #14107 for the remaining work

**Comment by stof** [comment]
Reopening because we are not there yet.

We have some classes using reserved keywords in the Validator component (the ``True`` and ``False`` constraints for instance).
The only way to fix this is to rename the constraint to a different name and deprecate the old name (providing it through a class_alias for PHP 5.x to avoid defining a class with the reserved named for PHP 7). So we must do it before the 2.7 release to have the new constraint names in the LTS version.

We also have some test failures in the Debug, Translation and VarDumper components

**Comment by nicolas-grekas** [comment]
See #14204 for VarDumper

For Debug (and maybe also VarDumper), we'll have to wait until the new exception mechanism is stabilized

**Comment by stefanruijsenaars** [comment]
@stof what are the names we want to go with for the Null, True and False constraints? NullConstraint is not consistent with the other constraints... We'd also want to rename the NotNull constraint and the Validators.

**Comment by stefanruijsenaars** [comment]
I think #14228 is ready now, how are we doing otherwise with this issue?

**Comment by stefanruijsenaars** [comment]
Just crossposting @nicolas-grekas comments from #14228 which seems to help the tests a bit further along and exposes a fatal error for the Validator component. Possibly a PHP 7 bug or maybe it's something we can code around.

Anyone have a PHP 7 setup to debug this on?: https://travis-ci.org/symfony/symfony/jobs/61229099#L560

**Comment by stof** [comment]
Remaining issues on PHP 7:

- the fatal error in the Validator tests
- the YAML component failures

**Comment by changloong** [comment]
any update ?

**Comment by fabpot** [comment]
@changloong We've fixed a bunch of other errors, but not all of them. If you have some time, can you help us finish this one?

**Comment by changloong** [comment]
Hi @fabpot 

I think I can work on this and make some pull request when I pass my local test:)

**Comment by GrahamCampbell** [comment]
The debug component needs updating to correctly display throwables. This came up in laravel 5.2.

**Comment by fabpot** [comment]
@GrahamCampbell That's probably something for @nicolas-grekas :)

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by nicolas-grekas** [comment]
I'll fix that asap :-)

**Comment by GrahamCampbell** [comment]
Loosing the exception typehint from non-private methods on non-final classes is a bigish breaking change though. Does this mean many of the changes can only be made on symfony 3.0?

**Comment by mickaelandrieu** [comment]
@stof I met some issues with ParameterBag / ContainerBuilder too. I will try to make a relevant issue asap :/

**Comment by anacicconi** [comment]
Sorry if my question is not in the right place but this discussion made me realize that I cannot upgrade my project to PHP7 as I'm using Symfony 2.8. I just checked on Github and all 2.8 related tags have the old names for the constraints (True, False, Null...). If that's the case, do I have to upgrade to Symfony 3 in order to upgrade to PHP7? As Symfony 3.1 is not a LTS I thought it wasn't a good idea to use it on production. Am I right? How are you guys doing to have both a LTS Symfony version and PHP7 on production? Thanks!

**Comment by lyrixx** [comment]
Symfony 2.8 (and even 2.7) are compatible with PHP7. as you can see on [github](https://github.com/symfony/symfony/blob/v2.8.13/src/Symfony/Component/Validator/Constraints/True.php), the class `True` is deprecated. So if you don't use it, everything will be fine. Instead you should use `IsTrue`

**Comment by xabbuh** [comment]
@anacicconi All releases before Symfony 3.0 ship with both the legacy and the `Is`-prefixed class names (see for example [True](https://github.com/symfony/symfony/blob/v2.8.13/src/Symfony/Component/Validator/Constraints/True.php) and [IsTrue](https://github.com/symfony/symfony/blob/v2.8.13/src/Symfony/Component/Validator/Constraints/IsTrue.php)).

**Comment by anacicconi** [comment]
Oh, ok! I didn't understand that. So I can keep 2.8. Just out of curiosity, is it recommended to use Symfony3.1 on production?

**Comment by stof** [comment]
sure

**Comment by lyrixx** [comment]
@anacicconi sure. we are using it ;)

**Comment by anacicconi** [comment]
Ok, thanks ;)
