### ISSUE TITLE
[MonologBridge] add an expression language handler

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#14083]
Sometimes you need to decide which handler to call for log messages not only based on the minumum error level (which is the only available filter so far) but on some more complex logic like certain values in the log context.

For example: We have the use case to log into multiple channels from a single class because they must be handled differently. But that requires to inject multiple loggers in the class and thus the logging class decides where to log to.

Instead it would be better to add another handler that just triggers on these messages. So my idea is to add a `ExpressionLanguageHandler` to the MonologBridge that decorates another handler and just adds logic to `isHandling` via a configurable expression. On top of that one could add an `expression` config to the [MonologBundle](https://github.com/symfony/MonologBundle) that if given, wraps the handler with our decorator.

**Comment by stof** [comment]
Monolog has a FilterHandler allowing to use a callable to filter messages.

**Comment by Tobion** [comment]
Its not a callable to filter messages but a callable for a factory. So that doesn't help really.

**Comment by Tobion** [comment]
Closing because it could be handy but we actually didnt need multiple channels in a single class anymore and using the levels was enough at the end.
