### ISSUE TITLE
PSR-7 is being voted on. What is Symfony's position?

### ISSUE THREAD

**Issue by jrobeson** [symfony/symfony#14093]
PSR 7 is up for vote, but Symfony's representative (@webmozart) has not voted.

https://groups.google.com/forum/#!topic/php-fig/sI91hfu-qsE

**Comment by webmozart** [comment]
Hi @jrobeson, thanks for bringing this up. We are currently discussing this issue.

**Comment by ahundiak** [comment]
Is this discussion online somewhere?  I have a few thoughts on the issue and was wondering what the Symfony folks were thinking.

**Comment by Tobion** [comment]
@ahundiak it's not online. I found some issues with PSR-7 that I thought must be addressed before it can be interoperable. This is also the main reason why the vote got cancelled. But when these last things are solved, I assume symfony will vote +1.
Feel free to share your thoughts here.

**Comment by webmozart** [comment]
Hi @ahundiak, thanks for your interest! You can find most of the discussion on the PHP-FIG mailing list: https://groups.google.com/forum/#!forum/php-fig

There is no dedicated topic to "the symfony opinion" there though. The members of the Symfony core team discuss there as individuals, just like anyone else. Just check the various topics prefixed with [PSR-7] for our appearance.

Once a vote is held, the Symfony core team decides what to vote (in a private, but very unspectacular exchange of a few emails). As Symfony's representative, I'm posting that vote in the respective voting thread.

Does this make our process more transparent to you?

**Comment by ahundiak** [comment]
I have been learning from Symfony for 10+ years.  Not in the least bit concerned about transparency.

I was glad to see Symfony considering adopting psr-7.  One of the few things about the stack that I never really cared for was the lack of Request/Response interfaces which made it more challenging to use some of the follow on components (kernel handler, routing etc) with custom classes.  The abstract factory helped but you were still tied directly to the Symfony classes.  Regardless of what happens to psr-7 I do hope to see at least some http message interfaces in 3.0.

Work in psr-7 seems to be progressing.  A withoutHeader method has recently been added so we can delete headers.  I'd still like to see a withHeaders method so multiple headers (cors) could be added without multiple cloning.  I also think the interface could be simplified to just getHeader/withHeader but that's just me.

Lot's of other little things like the missing Request::hasHeader() method that hopefully will be added.  Or maybe all the Request::header stuff which only concern the Host header can be dropped completely.

It will also be interesting to see if Symfony will change from $request->headers->get() to $request->getHeader().  And from $request->getPath() to $request->getUri()->getPath().  Lots and lots of code will need to be changed.

**Comment by unkind** [comment]
@ahundiak the major issue with PSR-7 for Symfony is immutability IMO. It's not bad per se, but it implies huge BC break for Symfony as you can't simply modify request object, you have to also return it somehow in order to replace old one.

**Comment by ahundiak** [comment]
For the request object, immutability should not be a problem.  The request itself should not need to be changed, just the attributes.  So:
```php
  class SymfonyRequestInterface extends Psr7ServerRequestInterface
  {
    public function setAttribute($name,$value);
  }
```
Is all that should be needed.  Any existing code that updates the request object (except for attributes) after the object is instantiated really should be examined.

The response object is a bit more challenging.  We probably don't really want a $response->setMaxAge() to return a cloned object.  All I can think of is that these sorts of changes would actually be stored in the SymfonyResponse object and then merged during the $response->send process.  Awkward at best.

Having read only versions of the psr-7 interfaces(just the get methods) would be a partial solution but I doubt if that will happen.

I should make clear that all I would really like to see in Symfony 3.0 is:
```php
HttpKernelInterface::handle(SymfonyRequestInterface)
// instead of
HttpKernelInterface::handle(SymfonyRequest)
```
I don't really care what the SymfonyRequestInterface looks like, just that there is one.

**Comment by fabpot** [comment]
Interfaces for HTTP messages is a discussion we already had... and as you can imagine, I was against that. Why would you want an interface for a data object?

**Comment by ahundiak** [comment]
I followed that discussion which is why I never tried to raise the issue.  But based on some of the psr-7 posts, I figured that it might be back on the table for 3.x.

My reason for wanting the interfaces:  I want to be able to use the HttpKernel and the Routing components without being dependent on the actual Symfony Request/Response objects.

If we will never have Symfony interfaces on request/response objects then this whole discussion becomes moot for my purposes.

**Comment by unkind** [comment]
> it implies huge BC break for Symfony

I'm not right, Symfony can implement PSR-7 without fixing existing code. There is no BC break here. In your own codebase you can depend on PSR-7.

**Comment by jrobeson** [comment]
it is now up for vote again!  https://groups.google.com/forum/#!topic/php-fig/0baLqR6Rvcg

**Comment by jrobeson** [comment]
even though the outcome is no longer in doubt, i'd still like to see a vote from Symfony.

**Comment by Tobion** [comment]
We will vote, don't worry.

**Comment by jrobeson** [comment]
There's only 23ish hours left at this point.
