### ISSUE TITLE
esi_render fails on HTTP when it's loaded on HTTPS before

### ISSUE THREAD

**Issue by nicokaag** [symfony/symfony#14109]
We currently have a project with multiple edge side includes, and we noticed that sometimes it fails.
After investigating it for quite some time, we found what the actual problem is.

Our site is available in both HTTP and HTTPS. (We don't force people to use one or the other)

Now when someone visites the HTTPS version of the site, a cache file is generated in the http_cache directory.
This cache file contains the esi_render parts, and it hos it's own hash.
When you then visit the page over HTTP, none of the esi's are rendered, because the URISigner says that the hashes don't match. and therefor throw an AccessDeniedHttpException.

Steps to reproduce:
1. Create a cachable action with a template that loads another action over esi_render
2. Visit the page on http and see the nicely rendered block
3. Visit the page on https and see how it disappeared.
4. Check your error log for the AccessDeniedHttpException

Extra info:
* Symfony 2.5.*
* Apache

**Comment by jakzal** [comment]
@nicokaag would it be easy for you to verify if this is still broken in a more recent Symfony version (2.6/2.7)?

**Comment by nicokaag** [comment]
I tested it on a fresh Symfony 2.6.6 installation, and there it works fine.
In 2.6.6 it actually generates 2 different caches, which is good enough..

**Comment by jakzal** [comment]
@nicokaag 2.5 is not maintained anymore. Unless the problem exists in 2.3, I'd consider it fixed.

**Comment by javiereguiluz** [comment]
Closing it as fixed because it works in newer Symfony versions.
