### ISSUE TITLE
[Form] Add translation_params options in form type

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#14112]
Hello !

It is currently not possible to set the translation parameters to translate label form. Why not add ``translation_params`` (in relation to ``translation_domain``) options in form type ? For example :

```xml
<!-- app/Resources/messages.fr.xliff -->
<trans-unit id="187">
    <source>accept-terms</source>
    <target><![CDATA[Accepter les <a href="%link%" target="_blank">conditions</a>.]]></target>
</trans-unit>
```
```php
// src/AppBundle/Type/CartType.php
$builder
    ->add('acceptTerms', 'checkbox', array(
        'label' => 'accept-terms',
        'translation_params' => array('%link%' => '...')
    ))
;
```

**Comment by 94noni** [comment]
Hello

Why not adding the label in twig directly?

```
{{ form_label(
   form.acceptTerms, 
   'accept-terms'|trans(
      {'%link%': 'http://terms.com'}
   )) 
}}
```

**Comment by maidmaid** [comment]
Yes it works but the problem with your solution is the only way to do this. Using ``form``, ``form_row``, or ``form_label`` (without argument), it is not possible. Currently writing the label in the ``form_label`` function looks like this ([link](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L223)) :

```twig
{{ label|trans({}, translation_domain) }}
```
An empty array as parameter function...

Can set translation parameters with an option form would be better, no ?

**Comment by 94noni** [comment]
I understand your point
Maybe wait or ping somewone who can answer this need, or propose a PR direclty :)

**Comment by maidmaid** [comment]
Yes, waiting other point of view before to engage a PR :+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by stof** [comment]
The issue with this proposal is that we can have multiple things translated in a form (the label, the choices, etc...). And they would all need to receive their own parameters then (reusing the same does not make sense)

**Comment by aitboudad** [comment]
can we close this issue for the reason pointed out by https://github.com/symfony/symfony/pull/10125#issuecomment-112468612 ?
