### ISSUE TITLE
[Console][Helper][Table] - Render row by row

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#14117]
I've inspected the Table Helper class and realized that is not possible to render the table row by row. Would be nice if Table Helper had the capability to render a specific row by calling $table->renderRow($i). That way I can process a large amount of items and see in real time the results of each processing.

**Comment by javiereguiluz** [comment]
@tsantos84 the problem is that for most tables you need to know the entire table contents before displaying any single row. The reason is that the contents of the table determine its layout. Now that we've introduced the `colspan` and `rowspan` options, your need is even harder to provide.

**Comment by tsantos84** [comment]
@javiereguiluz Thanks for your reply. What you saying is that to calculate the width of the table, you need to know the entire content before, right? And the highest length will determine the width of that column. We are talking about `['column_width' => 'auto']`.  And what you think about to pass a static value when add the headers? Some thing like `['column_width' => 100`], where `100` refers to 100 characters. We'll have more control on table's size and all content that exceeds that width you can cut out.

**Comment by javiereguiluz** [comment]
That's exactly what I meant.

This problem is also suffered by browsers when rendering HTML tables. Their solution is to define a `fixed` attribute that can be applied to the `<table>` element. If set, the entire table will be displayed exactly as the first row of the table, no matter how bad the end result may be.

**Comment by tsantos84** [comment]
Hi @javiereguiluz. Sorry for long time without reply this issue. So, is not possible to work with tables like `<table>` in web browsers? I really can't see the problem in pass a fixed width for table's columns. But, if you still think that this feature is not possible for the moment, you can close this issue.

**Comment by stof** [comment]
@tsantos84 on the CLI, it is also much harder to wrap the content inside cells in case it becomes wider than the width attributed previously (because we must perform rendering line by line in the output).
So rendering the table without knowing the content will indeed be a huge pain.

**Comment by tsantos84** [comment]
@stof When you say "without knowing the content" are you saying the entire table's content or a content of a single row?

**Comment by stof** [comment]
the content of the entire table (rendering a row without the content of this row simply does not make sense)

**Comment by tsantos84** [comment]
Ok guys...closing this issue.

Thanks for your attention.

**Comment by javiereguiluz** [comment]
@tsantos84 thanks to you for proposing this idea. Althought this time the proposal didn't make it, please don't hesitate to submit new proposals in the future. Thanks.

**Comment by tsantos84** [comment]
@javiereguiluz thanks to your attention. Sometimes I have some ideas for Symfony Framework and its components. Opening an issue and exposing the idea is the best way or there is a special place to do it.

**Comment by javiereguiluz** [comment]
@tsantos84 in the past we had a `symfony-dev` mailing list to discuss about the development of the framework. But it was closed in favor of this GitHub repository. So you are right, this is the best place to open issues to discuss about the new or the existing Symfony features.

**Comment by tsantos84** [comment]
Ok @javiereguiluz. thanks.
