### ISSUE TITLE
[Config] Wrong exception thrown

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#14111]
I have a custom route loader. When an exception is thrown from within my loader, in this case it's a `ContextErrorException` for an invalid array key, the browser always shows a `CircularReferenceException`.

Digging into the Symfony code, I can see the problem.

On line 104 of the `Component\Config\Loader\FileLoader` class, the resource is added as a key to a static array. When an exception is thrown within the custom loader (line 106), that key is never cleared. Then, the WebDebugToolbar tries generating it's own routes. Because that static array still contains valid data, the first resource `routing_dev.yml` causes the circular reference to be thrown.

I think the key should also be unset within the `catch` block.

**Comment by xabbuh** [comment]
Is this the same as #14199?

@twifty Can you check if the changes from #14192 solve your issue?

**Comment by twifty** [comment]
@xabbuh I believe the two mentioned issues would cause the same error, however, the proposed fix does not work in my instance.

Debugging the fix, I see that the caught exception `$e` is already an instance of `FileLoaderImportCircularReferenceException`.

To reproduce the issue, create a custom route loader and throw any type of exception within the `load` method.

The command line output, when clearing the cache, shows the correct exception, the browser does not. Like I mentioned above, the routing component is run again after the initial exception which causes the circular reference.

**Comment by xabbuh** [comment]
closing in favor of #14342
