### ISSUE TITLE
[Form] Collection prototype no escaping

### ISSUE THREAD

**Issue by gkawka** [symfony/symfony#14142]
I have an issue with collection prototype. Its not escaped so it looks like other form fields on page.
Shouldn't be escaping here?
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L28

**Comment by HeahDude** [comment]
could you try the fix in #14405

**Comment by Tobion** [comment]
The documentation escapes it explicitly when rendering individually. Do you render the whole collection or under which circumstances do you have the problem?

**Comment by HeahDude** [comment]
@Tobion  @gkawka maybe the placeholder not prototype. Should be related to #14393 and #14165

**Comment by gkawka** [comment]
@Tobion well im confused - imo escaping should be done by default because its expected behaviour in other hand i can understand it collection element should be visible for frontend in dev cycle. I think best way whould be parametrize or something like that. For now its rather messy in html :(
In that case in all my projects i should create custom form themes just for create collection prototype expected behaviour :/

@HeahDude imo its just missing `| e` after `form_row` of prototype just like in @Tobion docs reference.

**Comment by marcojanssen** [comment]
@gkawka @Tobion It does seem to break the expected behavior that all values should be escaped by default, why does this have to be an exception?

**Comment by xabbuh** [comment]
This behaviour may not be ideal, but it has been this way all the time and is the documented way. So I changing it now would be a BC break for all existing applications (as placeholders would be escaped twice then). So I am going to close here as we cannot change it.
