### ISSUE TITLE
[DomCrawler] Remove nodes from Crawler

### ISSUE THREAD

**Issue by MetalMatze** [symfony/symfony#14152]
Hey,

I really like the DomCrawler Component and I'm using it for a project where I need to remove a child node from that given Crawler node.
I'm currently stuck on removing that node since there's no remove method or something like that.
On the web there's not much talking about this use case.

Any suggestions on how to do that, maybe adding that function?
Thanks.

**Comment by jakzal** [comment]
As [explained in the docs](http://symfony.com/doc/current/components/dom_crawler.html):

> The DomCrawler component eases DOM navigation for HTML and XML documents.

And also:

> While possible, the DomCrawler component is not designed for manipulation of the DOM or re-dumping HTML/XML.

DomCrawler is rather designed to extract details from DOM documents rather than modifying them.

What are you trying to achieve exactly?

**Comment by MetalMatze** [comment]
Oh, sorry for not seeing that...

The HTML looks like:

    <div class="content">
        <h2 class="gamma">Excerpt</h2>
        ...content html...
    </div>

I'm getting the `.content` Crawler node.

At first I filter the `h2.gamma` to get the excerpt text that I want in my database field.

After that I want everything inside that `.content` except the `h2.gamma` node which I extracted before.
I thought one could `->remove('h2.gamma')` from the node, somehow filter that or iterate over all nodes and `return false` on the node that I don't want anymore.

Maybe I need another library or function to do this.

**Comment by xabbuh** [comment]
There is the [reduce()](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/DomCrawler/Crawler.php#L377-387) method which makes it possible to filter your results based on a callback. Is that what you are looking for?

**Comment by MetalMatze** [comment]
So I tried this.
```php
$articleExcerptNode = $articleContentNode->filter('h2.gamma');

$articleContentNode = $articleContentNode->children()->reduce(function(Crawler $node) use ($articleExcerptNode) {
    if($node->html() == $articleExcerptNode->html()) {
        return false;
    }
});
```

It only returns the first node after `h2.gamma`. But I want everything after that headline...

**Comment by jakzal** [comment]
Since PHP passes objects by reference, and Crawler is basically a wrapper for [DOMNode](http://php.net/manual/en/class.domnode.php)s, it's technically possible already:

```php
<?php

use Symfony\Component\DomCrawler\Crawler;

require_once __DIR__.'/vendor/autoload.php';

$html = <<<HTML
<html>
<div class="content">
    <h2 class="gamma">Excerpt</h2>
    <p>...content html...</p>
</div>
<div class="content">
    <h2 class="gamma">Excerpt</h2>
    <p>...more content html...</p>
</div>
</html>
HTML;

$crawler = new Crawler($html, 'http://localhost');

// remove all h2 nodes inside .content
$crawler->filter('html .content h2')->each(function (Crawler $crawler) {
    $node = $crawler->getNode(0);
    $node->parentNode->removeChild($node);
});

// output .content nodes with h2 removed
$crawler->filter('html .content')->each(function (Crawler $crawler) {
    echo $crawler->html();
});
```

*If you use [melody](http://melody.sensiolabs.org), run* `melody run https://gist.github.com/jakzal/8dd52d3df9a49c1e5922` to give it a go.

**Comment by MetalMatze** [comment]
This works like a charm! Absolutely perfect.

Needed some time to think it through, but I get it now. Thanks and :+1: for [melody](http://melody.sensiolabs.org/).

**Comment by MetalMatze** [comment]
Thanks for pointing that out. It is the last thing I do with that node, so I guess I'm safe.
