### ISSUE TITLE
No token in esi fragment when outer layout is cached 

### ISSUE THREAD

**Issue by xcompass** [symfony/symfony#14168]
I'm trying to cache my app and found out there is no token populated in ESI fragment when outer layout is being cached. The ESI fragment is being included in the outer layout as following:

    render_esi(controller('somecontroller'))

The ESI fragment is set to no cache and outer layout is set to be cached for a period of time. I print out the toekn on both outer layout and ESI fragment with the following:

    {{ app.security.token }}

So first time, when there is no cache, both outer layout and ESI fragment are being processed, both print out correct token for the current logged in user. Then I refreshed page, now, the outer layout retrieved from cache and only ESI fragment is being processed. However, the token is empty inside the ESI fragment.

If I used render_esi(url('someurl')) it seems the token is populated correctly. I'm using latest version of symfony 2.6. Is it a bug?

**Comment by jakzal** [comment]
What kind of reverse proxy do you use? Varnish or Symfony's HttpCache?

**Comment by xcompass** [comment]
Using Symfony's HttpCache. Never tried it on Varnish.

**Comment by jakzal** [comment]
@xcompass I have failed [to reproduce your issue](https://github.com/symfony/symfony-standard/compare/2.6...jakzal:2.6-issue14168). Please provide a fork of [Symfony SE](https://github.com/symfony/symfony-standard) with this issue reproduced.

**Comment by jakzal** [comment]
@xcompass are you able to provide a fork with this issue reproduced?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.

@xcompass Feel free to reopen when you can provide more information.
