### ISSUE TITLE
[Symfony new installer] Fail under proxy

### ISSUE THREAD

**Issue by blag001** [symfony/symfony#14160]
Hello, 
I'm on unbuntu 14.04 and I can't fin a way to use the new symfony installer unde the corporate proxy.
- I've set the HTTP/HTTPS/FTP proxy under `Network > mandatory server`
- `export` in terminal HTTP/HTTPS/FTP proxy

I follow the 
```bash
$ sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
$ sudo chmod a+x /usr/local/bin/symfony 
```
(I set my proxy config for the curl part)
But when use the `symfony new test_project` I only have this : 
```bash
$ symfony new test_project
 Downloading Symfony...
                                             
  [GuzzleHttp\Exception\RequestException]                                      
  Error creating resource. [url] http://symfony.com/download?v=Symfony_Standa  
  rd_Vendors_latest.tgz [type] 2 [message] fopen(http://symfony.com/download?  
  v=Symfony_Standard_Vendors_latest.tgz): failed to open stream: Connection t  
  imed out [file] phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/  
  Adapter/StreamAdapter.php [line] 367                                         
            
new directory [version]
```
I don't find anything on google nor in the doc/help...
Any way to get the symfony ? (manual depreciate composer commande maybe ?)

Thanks,
Blag

**Comment by stloyd** [comment]
This is not Symfony Installer repository. Every issue with that product should be reported in its repository: https://github.com/symfony/symfony-installer

**Comment by javiereguiluz** [comment]
@blag001 thanks for reporting this issue. However, as @stloyd said, to keep things sorted, we discuss about the Symfony Installer in another repository. In fact, we already have an issue created to discuss about adding proxy support to the installer. Please check out https://github.com/symfony/symfony-installer/issues/124 and feel free to join the discussion. Thanks.

**Comment by blag001** [comment]
My bad, didn't see the didicate repo... :P 
Thanks.
