### ISSUE TITLE
[Form] How to determine a form is a prototype from CollectionType?

### ISSUE THREAD

**Issue by aramalipoor** [symfony/symfony#14175]
I'm creating a `TypeExtension` and want to add some variables into `$view->vars`, but how can I check if the form type that I'm currently visiting is actually [created from within a collection?](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php#L29-L34)

Is it even possible? If not is it a good idea to `setAttribute` on the prototype?
```php
// src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php#L29-L34
$prototype = $builder->create(
         $options['prototype_name'],
         $options['type'], array_replace(array(
                'label' => $options['prototype_name'].'label__',
         ), $options['options'])
);

$prototype->setAttribute('prototype_of', $builder);
$builder->setAttribute('prototype', $prototype->getForm());
```

**Comment by aramalipoor** [comment]
@stof /cc

**Comment by jakzal** [comment]
Please use the [mailing list](http://symfony.com/mailing-lists) or the [IRC channel](http://symfony.com/irc) for support questions.
