### ISSUE TITLE
[Form] formName conflict

### ISSUE THREAD

**Issue by alborq** [symfony/symfony#14177]
Hi. 
If name of form has a specific value like 'search' a new field is automaticly create in start of form...

**Comment by stof** [comment]
I don't understand what you mean

**Comment by maximecolin** [comment]
If you name your form type "search", the rendering of the form will display a search input before the others inputs.

This name already taken by ```Symfony\Component\Form\Extension\Core\Type\SearchType```, so the block "search_widget" is called when you render your form which has for consequency to render an extra search input. This is the same with "integer", "url", "email", ... This is how the form layout works, not sure we can do something. Do not named your form type as existing one.
