### ISSUE TITLE
Don't repeat the translations in the new Translation profiler panel

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#14183]
The problem
----------------

I was playing with the new 2.7 translation profiler and the Symfony Demo application. When I was in the backend homepage, where we display 10 rows of items with the buttons `Show` and `Edit` translated, I got the following:

![translation-profiler-default](https://cloud.githubusercontent.com/assets/73419/6967878/b5c1486e-d962-11e4-9f68-48b608c18ab6.png)

Repeating the same translations 20 times looks wrong to me.

The solution
----------------

The first solution would be to only display the unique translations used:

![translation-profiler-unique](https://cloud.githubusercontent.com/assets/73419/6967899/cfe3115a-d962-11e4-863e-f4c7ec838c92.png)

If you think that displaying the number of times a translation has been used is important, we could add a new column to the table:

![translation-profiler-extended](https://cloud.githubusercontent.com/assets/73419/6967914/e9327682-d962-11e4-9ccb-5c2cad7978d3.png)

And if you think it only makes sense to display this information when the translation has been used multiple times, we could display that information in a more subtle way:

![translation-profiler-subtle](https://cloud.githubusercontent.com/assets/73419/6967932/13d2c234-d963-11e4-8153-53c05bf96a9e.png)

**Comment by WouterJ** [comment]
:+1: for the last suggestion

**Comment by aitboudad** [comment]
@javiereguiluz I made a quick fix #14185 can you check it ?

**Comment by aitboudad** [comment]
@javiereguiluz thank you for your proposal :+1:
