### ISSUE TITLE
Fix choice lists refacto

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#14193]
Reminder issue for taking care of comments on #14050 (ping @webmozart )

**Comment by xabbuh** [comment]
see also #14165

**Comment by fabpot** [comment]
@webmozart Can you take care of this one ASAP? It means that tests are broken for now and that is going to block the first beta of Symfony 2.7.

**Comment by webmozart** [comment]
See #14200 for the CHANGELOG/UPGRADE update.

**Comment by webmozart** [comment]
See #14201 for the `trigger_error()` fix.

**Comment by webmozart** [comment]
See #14202 for a minor code fix.

**Comment by webmozart** [comment]
As [pointed out](https://github.com/symfony/symfony/pull/14050#issuecomment-88450422) by @stof, the deprecation policy of the new "choices_as_values" option is problematic. This needs to be fixed once #14200 is merged.

**Comment by webmozart** [comment]
The constructor arguments of the new `ChoiceView` class are unnecessarily reversed compared to the old one, which makes migration more difficult. There was some reason behind this change, but I can't recall, so the argument order should be reversed again to match the old class. This needs to be done once #14200 is merged.

**Comment by xabbuh** [comment]
Is there anything else we can do here? Given that we have a stable 2.7 release now, we should not swap constructor arguments in `ChoiceView` again, but keep the inconsistency now.

**Comment by nicolas-grekas** [comment]
@stof or @webmozart could you please see if you can do something about the deprecation policy ([see above](https://github.com/symfony/symfony/issues/14193#issuecomment-89335674) now that #14200 is merged?
