### ISSUE TITLE
[Translation] TranslationDataCollector issues PHP warning when nothing has been translated

### ISSUE THREAD

**Issue by sgehrig** [symfony/symfony#14209]
The `\Symfony\Component\Translation\DataCollector\TranslationDataCollector` issues a PHP warning when nothing has been translated. The profiler therefore does not complete successfully and the web debug toolbar fails to load in succession. 

The issue has been introduced in commit b470a5bfb6f9b7e484f4848c40a2f9d954400369. `\Symfony\Component\Translation\DataCollector\TranslationDataCollector::sanitizeCollectedMessages` uses

    return array_reduce($messages, function ($result, $message) {
        $messageId = $message['locale'].$message['domain'].$message['id'];
        if (!isset($result[$messageId])) {
            $message['count'] = 1;
            $result[$messageId] = $message;
        } else {
            $result[$messageId]['count']++;
        }

        return $result;
    });

but this returns `NULL` if `$messages` is an empty array. A possible solution would be to add an empty array as the initial parameter to the `array_reduce()` call, like this:

    return array_reduce($messages, function ($result, $message) {
        $messageId = $message['locale'].$message['domain'].$message['id'];
        if (!isset($result[$messageId])) {
            $message['count'] = 1;
            $result[$messageId] = $message;
        } else {
            $result[$messageId]['count']++;
        }

        return $result;
    }, array());

**Comment by aitboudad** [comment]
I'll look into it

**Comment by aitboudad** [comment]
@sgehrig fixed by #14210

**Comment by sgehrig** [comment]
@aitboudad: That was fast :-) THX! I was just starting do a setup for creating a pull request :-)

**Comment by aitboudad** [comment]
@sgehrig I didn't know you are working on it, so next time I'll ask you :D

**Comment by sgehrig** [comment]
@aitboudad: Just thought that this would have been an easy pick to start contributing...
