### ISSUE TITLE
ajax calls not shown in toolbar

### ISSUE THREAD

**Issue by sgiusto** [symfony/symfony#14219]
Since version 2.6.6 ajax calls are not detected by The debug toolbar

**Comment by 1ed** [comment]
This should be fixed by #14170. Could you please check?

**Comment by sgiusto** [comment]
Hello,

I confirm that applying the patch works!

BR

  Stefano

 

Da: Gábor Egyed [mailto:notifications@github.com] 
Inviato: domenica 5 aprile 2015 22.05
A: symfony/symfony
Cc: Stefano Giusto - Multimedia Point Srl
Oggetto: Re: [symfony] ajax calls not shown in toolbar (#14219) - Posta elettronica trovata in oggetto

 

This should be fixed by #14170 <https://github.com/symfony/symfony/pull/14170> . Could you please check? 

—
Reply to this email directly or view it on GitHub <https://github.com/symfony/symfony/issues/14219#issuecomment-89845406> . <https://github.com/notifications/beacon/ALQrnR3PV7XEq3dWRKqobI43kJ7EIqXDks5n8Y0DgaJpZM4D6hvh.gif> 



Stefano Giusto - Multimedia Point Srl

Mobile: +39 348 4098570
Phone: +39 031 563704
Fax: +39 031 563721
Email: sgiusto@mmpoint.it

Multimedia Point Srl

Sede Legale e operativa: Via Monte Rosa, 2 22079 Villa Guardia (CO) Italy 
Partita IVA e C.F: 02170630137 - R.E.A. Como  244640 - Cap.Soc. euro 10.200,00 i.v.  


Le informazioni contenute nella presente comunicazione e i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell 'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente per telefono allo 031563704. 

The information contained in this message is confidential and is intended for the addressee only. If you have received this message in error, please notify us as soon as possible. The unauthorised use, disclosure, copying or alteration of this message is forbidden. Multimedia Point will not be liable for direct, indirect or consequential damages arising from alteration of this message by a third party or as a result of virus infection. Information may be legally privileged.
