### ISSUE TITLE
[DependencyInjection] Make extensions storage case insensitive

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#14212]
```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\Extension;

class FooExtension extends Extension
{
	public function load(array $config, ContainerBuilder $container) {}

	public function getAlias()
    {
        return 'foo';
    }
}

class FooUpperExtension extends Extension
{
	public function load(array $config, ContainerBuilder $container) {}

	public function getAlias()
    {
        return 'FOO';
    }
}

$container = new ContainerBuilder();
$container->registerExtension(new FooExtension());
$container->registerExtension(new FooUpperExtension());

print_r($container->getExtensions());
```
This code returns:
```
Array
(
    [foo] => FooExtension Object
        (
        )

    [FOO] => FooUpperExtension Object
        (
        )
)
```
What do you think about making `registerExtension`, `getExtension` and `hasExtension` methods case insensitive? So, this code will return:
```
Array
(
    [foo] => FooUpperExtension Object
        (
        )
)
```

**Comment by Tobion** [comment]
AFAIK container service names are case insensitive. So it might make sense to do it for extensions as well.

**Comment by sstok** [comment]
:+1:

**Comment by dosten** [comment]
This must be done into the master branch? Because is a potential BC break.

**Comment by aitboudad** [comment]
:+1: , it should be done into master

**Comment by WouterJ** [comment]
:-1:, because:

* It's inconsistent with every other ID/name in the container (services, tags, ...)
* There is a good reason for this as the alias is used for the configuration. You don't have capitialized/uppercase setting names in your `config.yml`. E.g:
   ```yaml
   doctrine:
        auto_mapping: true

   DOCTRINE:
        something_else: 'foo'
   ```

**Comment by GromNaN** [comment]
:-1: This a problem of developer strictness. Using multiple case variations for the same identifier should be considered as a typo, more that a supported feature.

What about throwing an exception instead ?
