### ISSUE TITLE
buildViolation and translation

### ISSUE THREAD

**Issue by CharlyPoppins** [symfony/symfony#14224]
Hi,

I'm trying to use translation in **ExecutionContextInterface $context->buildViolation()**.

My translation is here : **Charly/AdminBundle/Resources/translations/messages.fr.yml** and the code is
```
$context->buildViolation('charly.test.ajouter')
				->atPath('erreurTest')
				->setParameter('{{ locale }}', $locale)
				->setTranslationDomain('CharlyAdminBundle')
				->addViolation();
```
did I miss something using **setTranslationDomain()** ?

**Comment by Tobion** [comment]
The file must be named after the translation domain. Also please ask questions on the mailing list, this issue tracker is for bugs only.

**Comment by CharlyPoppins** [comment]
Just for remembering :
```
->setTranslationDomain('CharlyAdminBundle')
```
has to be
```
->setTranslationDomain('validators') // for validators.xx.yml
```
or
``` 
->setTranslationDomain('messages') // for messages.xx.yml
```
etc...
