### ISSUE TITLE
[Translation] Enable debugging of all bundles translations

### ISSUE THREAD

**Issue by xelaris** [symfony/symfony#14237]
The discussion in PR #13443 arises the idea to add an `--all` flag to the `TranslationDebugCommand` to enable debugging translations of all bundles. This issue should save the idea.

**Comment by aitboudad** [comment]
@sgehrig this can be an easy pick for your first pull request ?

**Comment by sgehrig** [comment]
@aitboudad I tried to... Please be lenient ;-)
