### ISSUE TITLE
Problem with SourceCodeExtension.php\getControllerRelativePath function in Windows

### ISSUE THREAD

**Issue by cktdesign** [symfony/symfony#14239]
To recreate the problem just install symfony demo in windows and browse it. The problem happens because windows use a different directory separator than linux. Github escapes the windows directory separator so instead of it i will use the symbol " | " in the following sentences.
Original function uses the following code

$pathParts = explode('/src/', $absolutePath);

To fix it you could use

if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
            $pathParts = explode('||src||', $absolutePath);
            $relativePath = 'src||' . $pathParts[1];
        } else {
            $pathParts = explode('/src/', $absolutePath);
            $relativePath = 'src/' . $pathParts[1];
        }

or

if (DIRECTORY_SEPARATOR == '/') {
            $pathParts = explode('/src/', $absolutePath);
            $relativePath = 'src/' . $pathParts[1];    
} else if (DIRECTORY_SEPARATOR == '||') {
            $pathParts = explode('||src||', $absolutePath);
            $relativePath = 'src||' . $pathParts[1];    
}

**Comment by javiereguiluz** [comment]
@cktdesign thanks for reporting this issue. I'll take care of it right away!

By the way, since this is a Symfony Demo issue, next titme it'd be better if you report it directly at https://github.com/symfony/symfony-demo/issues  Thanks!

**Comment by javiereguiluz** [comment]
@cktdesign the proposed fix is ready at https://github.com/symfony/symfony-demo/pull/25  If you agree, please close this issue and let's move the discussion to the `symfony-demo` repository. Thanks.
