### ISSUE TITLE
[Filesystem] dumpFile() negates default file permissions

### ISSUE THREAD

**Issue by pkruithof** [symfony/symfony#14246]
The [`tempnam()`][0] function creates a temporary file with `0600` permissions, regardless of the umask. This requires that every `dumpFile()` call is followed by a `chmod()` to 'fix' the permissions. I would assume that the function does this for me, since other filesystem operations (eg: `copy` and `touch`) also create files with the default file permissions.

I found [this issue][1] that relates to this issue, and deprecated the argument in which you could set the permissions in the `dumpFile()` call. So, without being able to use the argument, I would prefer it if the created file has the right permissions. If not, the documentation for this function should specify this clearly, I think.

[0]: http://pl1.php.net/tempnam#refsect1-function.tempnam-description
[1]: https://github.com/symfony/symfony/issues/8205

**Comment by cs278** [comment]
There is a further issue, the `chmod()` needs to be applied after the file is written but **before** it is moved. The current order breaks the atomic nature of this method, as reads to the file by other users will fail until the mode is changed.

**Comment by hboomsma** [comment]
+1

**Comment by xabbuh** [comment]
The `chmod()` is still not present in 3.0 (the change wasn't merged from `2.8`into `3.0` in 9c2dbb608418bc46d648b50cd6e9db485d38f793).
