### ISSUE TITLE
Installing symfony 2.3.6 problem, any help

### ISSUE THREAD

**Issue by aftabusas** [symfony/symfony#14242]
![626b2b2b1e23a23e8d3b9a5c4e91a9c6](https://cloud.githubusercontent.com/assets/11830969/7018694/35609088-dd10-11e4-92fd-f3b779ebe1b7.png)
Hey, 
i'm new at installing and configuring frameworks.(web dev overall)
While installing symfony 2.3.6 i get this problem . 
 It asks to provide database_driver.

Some parameters are missing. Please provide them.
database_driver (pdo_mysql):
database_host (127.0.0.1):
database_port (null):
database_name (symfony):
database_user (root):
database_password (null):
mailer_transport (smtp):
mailer_host (127.0.0.1):
mailer_user (null):
mailer_password (null):
locale (en):en-gb
secret (ThisTokenIsNotSoSecretChangeIt):

Is there any need for me to configure something?

**Comment by dupuchba** [comment]
Is is the normal flow of the `symfony` installation. 
What it does => ask you basic `config`parameters in order to make it faster for you to write your application.
Don't worry, you can always change those parameters in `app/config/..`
***
I suggest you to read the documentation which is the best entry point in the SF world :-).

http://symfony.com/doc/current/book/index.html

**Comment by aftabusas** [comment]
Thank you for the answer. 
Is there any way to check symfony 2 from faults after installing? mayb through CMD?

**Comment by dupuchba** [comment]
From faults ?

**Comment by aftabusas** [comment]
I'm sorry for my bad english. To check if everything works OK ?

**Comment by javiereguiluz** [comment]
@aftabusas first of all, welcome to Symfony :)

I completely understand your doubts about the Symfony installation process. In fact, the old Symfony installation method (which is the one you are using) needed so many improvements, that we recently decided to change it completely:

  * Here you can find [a blog post introducing the new installe](http://symfony.com/blog/introducing-the-new-symfony-installer)
  * Here you can find [the new Symfony download page](http://symfony.com/download) which explains how to use the new Symfony installer.
  * Here you can find [the Symfony installation chapter](http://symfony.com/doc/current/book/installation.html) of the official book, which explains everything in detail.

So please, forget about the old installation method, and use the new Symfony installer. If you have any question, please ask!

**Comment by aftabusas** [comment]
Thank you for a great answer! 
Right now i'm trying to install it the new way.




![0f724b28f023fd6595eb9b99a21e196a](https://cloud.githubusercontent.com/assets/11830969/7019025/359be1e8-dd14-11e4-847d-ecd04c78765a.png)


after executing the command symfony new blog it is not recognised as an internal or external command.

**Comment by javiereguiluz** [comment]
Since you are using Windows, you don't have a global command called `symfony`. But don't worry, the solution is as easy as exeucting the `symfony` command locally:

![symfony_installer_windows](https://cloud.githubusercontent.com/assets/73419/7019112/d11ca1f0-dd0c-11e4-8a75-43b22a59b0ab.png)

**Comment by Tobion** [comment]
Please continue the discussion on the mailing list where support requests are handled. This issue tracker is for bugs/features only.

**Comment by javiereguiluz** [comment]
Here you can find the information about the Symfony mailing list: http://symfony.com/mailing-lists

@Tobion when you ask a user, specially a newcomer, to use the mailing list, please consider always adding the above URL. Thanks.

**Comment by Tobion** [comment]
@javiereguiluz it's the first hit when you enter "symfony mailing list" into google. I assume every developer should be able to find it even when we don't provide them a link directly. Just saying.

**Comment by jakzal** [comment]
@Tobion I'm with Javier on this one, although I'm guilty of not including the link myself from time to time. I believe this is not a big effort to include the link but it makes a real difference for newcomers. We should whatever we can to make their lives a bit easier :)
