### ISSUE TITLE
Sporadic failures in SigchildEnabledProcessTest

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#14244]
SigchildEnabledProcessTest::testIdleTimeoutNotExceededWhenOutputIsSent seems to be a volatile test.

**Comment by xabbuh** [comment]
Thank you for reporting this, @mpdude. However, I'm gonna close this nonetheless because we already have one issue covering this (see #14078).

**Comment by mpdude** [comment]
Sorry, missed that one as it did not contain the test class or method name.

Thanks!
