### ISSUE TITLE
Should Symfony integrates queue services support?

### ISSUE THREAD

**Issue by samuel4x4** [symfony/symfony#14240]
Hello,

"Sending emails is a classic task for any web application and one that has special complications and potential pitfalls. Instead of recreating the wheel, one solution to send emails is to use the SwiftmailerBundle, which leverages the power of the Swift Mailer library. This bundle comes with the Symfony Standard Edition." (http://symfony.com/doc/current/cookbook/email/email.html)

Very cool, almost all projects are sending emails, so it's very helpful to have Swift Mailer included, very good decision ;)

What about to be the same with queue services support included in the Symfony Standard Edition? This necessity is almost at the same level with the email support, from my point of view. It will be really nice to have a Symfony component providing an unified API across a variety of different queue services. 

@fabpot, what do you think?

**Comment by dupuchba** [comment]
IMO it is not part of the scope's framework as it is an architectural decision.

**Comment by Tobion** [comment]
Closing as this would be for symfony/standard-edition. Also I agree with @dupuchba that this doesn't belong in the standard edition. Also it's easy to add one of the existing bundles for queues yourself.

**Comment by samuel4x4** [comment]
Hello,

Thanks for feedback guys. You may be right, my idea comes from here: http://laravel.com/docs/master/queues. I used Laravel before Symfony, I'm still connected with what's happening in other frameworks. I think Symfony is the best option for me now, but I really was impressed by the queue support Laravel included in the last version. 

I hope nobody feel offended about this idea, I will continue thinking it's a good idea ;)

Have a nice day!

**Comment by dupuchba** [comment]
@samuel4x4 you have bundles that can help you do queue management. But again it is still an architectural decision :-).

**Comment by jrobeson** [comment]
i think there's still room for a RAD framework like laravel to be built on top of the symfony framework. Some have been started, but nothing has really gained traction yet :(
