### ISSUE TITLE
2.6.6 : AJAX requests in the web debug toolbar not working anymore

### ISSUE THREAD

**Issue by chandon** [symfony/symfony#14243]
With Symfony 2.6.6, AJAX requests in the web debug toolbar doesn't work anymore : no ajax query (counter remain at 0, and no profile for the requests in the dropdown list)

Going back to 2.6.5, AJAX requests in the web debug toolbar works again

**Comment by aitboudad** [comment]
@chandon https://github.com/symfony/symfony/issues/14219

**Comment by chandon** [comment]
ok thx
