### ISSUE TITLE
Should we not ramp Doctrine's default version to 2.5 in composer.json for the 3.0 release?

### ISSUE THREAD

**Issue by naroga** [symfony/symfony#14253]
Doctrine 2.5 has just been released, and Symfony is still using `<2.5 ` in composer.json. 2.5 breaks BC with 2.4- projects, so if we can't ramp it up in the 3.0 release, we won't be able to do so until 4.0, I think. Which means eventually we'll be using a deprecated version of doctrine as the default orm of the 3.x branch.

**Comment by 1ed** [comment]
I think you can use whatever version of Doctrine you want in your projects. https://github.com/symfony/symfony/search?l=json&q=doctrine&utf8=%E2%9C%93

**Comment by naroga** [comment]
@1ed, I realize we can use whatever version. I'm inquiring about switching the default vendor version. Soon, everyone installing the Symfony project will also be installing a deprecated version of Doctrine by default, and this should probably be fixed.

**Comment by xabbuh** [comment]
@naroga I fail to see what could be changed in Symfony. As far as I see, we don't forbid to use newer Doctrine packages and we also don't bind it anywhere to a particular minor version. However, changing the minimum minor version to something higher would be a BC break.

**Comment by jrobeson** [comment]
it's too early to worry about what version will be shipped in 3.0. I'm sure it will be updated at some point after the 2.7 release

**Comment by mpajunen** [comment]
I think this is related to the required Doctrine version [in symfony/standard](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L12).

The requirement was added in symfony/symfony-standard#774. There does not seem to be a good fix for it yet, but there are some proposed workarounds in symfony/symfony-standard#748.

**Comment by jrobeson** [comment]
@naroga : you should close this here and reopen  this in symfony-standard. . It might even work to just submit a PR to change the dependencies to default to 2.5 and skip opening the issue altogether.

**Comment by naroga** [comment]
I'll close this issue then. Thanks for the responses, @jrobeson, @mpajunen.

**Comment by Tobion** [comment]
See symfony/symfony-standard#797
