### ISSUE TITLE
Doctrine database drop

### ISSUE THREAD

**Issue by arodier-bulbthings** [symfony/symfony#14255]
Hi,

I have a symfony project with a database. In a testing environment, I run a script to drop and create the database from scratch.

If I use both the --if-exists and --force option, the database is not dropped, and I have this error message:
> Database for connection named `my_database_name` doesn't exists. Skipped.

However, if I remove the --if-exists option, it's working:
> Dropped database for connection named `my_database_name`

Unfortunately, I have to use the "--if-exists" option

**Comment by 1ed** [comment]
Maybe you are looking for this https://github.com/doctrine/DoctrineBundle/pull/401

**Comment by arodier-bulbthings** [comment]
Thanks, I will wait for this fix to be merged, and I will come back to update this bug report.

**Comment by cordoval** [comment]
The fix is merged @arodier-bulbthings, but it does not belong to a release but soon it will be. So i think we should close this.

**Comment by arodier-bulbthings** [comment]
Ok.
