### ISSUE TITLE
[WebProfiler] Ajax calls are not getting captured anymore in the WebProfiler tool bar (2.6.6)

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony#14251]

**Comment by javiereguiluz** [comment]
@ZCJ thanks for reporting this issue.

We're aware of it and we're fixing it in #14219.

**Comment by stof** [comment]
Closing this because the fix has already been merged in https://github.com/symfony/symfony/pull/14170 and we don't keep issues open when they are fixed (even though the fix is not yet released)
