### ISSUE TITLE
Twig widget form_rest() should also render hidden field _method if not yet rendered.

### ISSUE THREAD

**Issue by Mondane** [symfony/symfony#14261]
I have a form with the method set to PUT which I custom render in a template, ie. I'm not using 

``` twig
{{ form(form) }}
```

or

``` twig
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}
```

I do it more or less like this:

``` twig
<form>
  {{ form_errors(form) }}
  {# render the columns in a way I need #}
  {{ form_rest(form) }}
</form>
```

I believed adding the `form_rest(form)` was enough to make sure non-rendered fields were added (like the _token). It turns out, the hidden field _method, isn't rendered unless you use `form_start()`.

Shouldn't it be logical to have the form_rest also render the _method field if it isn't rendered so before?

The file that's rendering the form:

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig

**Comment by Tobion** [comment]
Makes sense to me since the hidden field _method should not be tied to the form_start as you can put the hidden field anywhere in the form and does not need to be at the start.

**Comment by xabbuh** [comment]
see #23254

**Comment by fmarchalemisys** [comment]
This patch is breaking `CollectionType.`

For a collection, `form_rest` is called without `form_start` or `form_end.` With this patch, `form_rest` adds one hidden `_method` to the global form for each item in the collection.

This is most damaging if the parent form uses POST and at least one child form is declared to use PUT. In that case, the added `_method` overrides the parent form method. Then, the parent form fails to validate as the submitted request method doesn't match the parent form method.

`form_rest` should not mess with the method if it is not the one responsible for writing the `<form>` tag (i.e. it is called through `form_widget_compound).`

**Comment by xabbuh** [comment]
@fmarchalemisys Do you want to submit a pull request?

**Comment by fmarchalemisys** [comment]
@xabbuh This is my very first pull request. I'm not sure I got it right. It doesn't show in the PR list (here is the PR in my fork: https://github.com/fmarchalemisys/symfony/pull/1).

**Comment by xabbuh** [comment]
@fmarchalemisys You need to create the PR on this repo. :) Try from here if that's easier for you: https://github.com/symfony/symfony/compare/2.7...fmarchalemisys:fmarchal-issue-14261?expand=1

**Comment by fmarchalemisys** [comment]
@xabbuh Thanks for the hint :) I expected Symfony's repo to be off-limit to me and, hence, a fork was required.

I'm now waiting to hear about the next thing I did wrong :)

**Comment by xabbuh** [comment]
@fmarchalemisys Thanks! 👍 Looks good so far. I just left a minor comment on your PR.
