### ISSUE TITLE
Upgrade ICU to version 55

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#14260]
We should upgrade the ICU data and tests to the latest version 55.

See also #14259 for a related issue.

**Comment by javiereguiluz** [comment]
Could someone with experience in this take care of this issue? The latest version of ICU is 56.1 (http://site.icu-project.org/download) but Symfony is two versions behind (we use 54.1).

There is a [update-data.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/Resources/bin/update-data.php) script in the Intl component which should make this task "not complicated".

**Comment by nicolas-grekas** [comment]
I'm not sure it's required now: the version we use is the one shipped with 5.5.9, which is exactly our lowest php requirement. Good enough IMHO, WDYT?

**Comment by javiereguiluz** [comment]
@nicolas-grekas I agree with you. Thanks for the info. Given that we won't upgrade the minimum PHP requirement at least until the end of 2017 (when Symfony 4.0.0 is released), should we close this issue?

**Comment by sstok** [comment]
Actually I do need 56.1, as that's the version installed by Homebrew.
Unless there is another way? I couldn't find anything in the docs about this issue.

**Comment by webmozart** [comment]
@nicolas-grekas I can't tell specifically what changed between 54.1 and 56.1, but generally it's advisable to upgrade as soon as possible. The CLDR data set gets better and better over time. Also, country names (or country borders) tend to change, and newer releases contain those changes. I was recently talking to a developer that was heavily relying on our CLDR data and complained about that data not being up-to-date. Hence I think we should reopen this one.

**Comment by webmozart** [comment]
I think right now it would be good to upgrade to ICU 55.1. That's the version shipped with the current PHP releases. At the moment, our Intl tests rely on our current ICU version (51.2). Upgrading to 55.1 would enable those tests on current PHP releases, where the tests are skipped right now.

**Comment by javiereguiluz** [comment]
Great. Is this a matter of just executing the existing [update-data.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/Resources/bin/update-data.php) script or is the process more involved?

**Comment by webmozart** [comment]
@javiereguiluz As far as I can tell, the upgrade is threefold:

* Run the script to update the data.
* Change the stub implementations of the Intl component (have they been moved to a Polyfill?) to mimic PHP's native classes based on ICU 55.1.
* Sometimes, an ICU upgrade causes tests to fail that contain date strings in assertions. For example, it could be that 52.1 localizes specific dates in one manner and 55.1 in another. Such tests need to be adapted to reflect the new ICU version. Those changes would be equivalent to the changes in the stub classes (e.g. if a date is formatted as `x` in ICU 52.1 and as `y` in 55.1, both the stub classes and the tests need to be changed to `y`).

**Comment by javiereguiluz** [comment]
@webmozart thanks for the info! Now we need to find a volunteer. Maybe @nicolas-grekas who already did this in the past? Thanks!

**Comment by HeahDude** [comment]
@webmozart Thanks for this heads-up, I'd love to try as it's quite challenging for me.

Be aware I may not be able to handle it though. Keep you posted ASAP :)

**Comment by jakzal** [comment]
@HeahDude have you done anything regarding this issue? I have started working on it, and then noticed you planned to try it yourself.

**Comment by HeahDude** [comment]
@jakzal, Not yet, I've been polishing some other PRs. Feel free to continue, when __webmozart__ told me about this issue, I read that you were waiting for a volunteer.

As you said, I could only "try" since I don't know yet how to handle it, but like my other works on symfony, I consider it a very good way to learn.

Feel free to continue, I'll have a look anyway just for myself :) thanks.

**Comment by jakzal** [comment]
Just FYI, travis still runs with ICU 4.8.1.1 :(

Not sure if we could do anything to run Intl tests on travis apart from compiling it ourselves (see https://github.com/travis-ci/travis-ci/issues/3616).
