### ISSUE TITLE
Server:run should error when port is already used

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#14275]
![sf-server-run-same-port](https://cloud.githubusercontent.com/assets/749025/7054568/aa73a742-de3d-11e4-88e2-3eef3974ae75.png)

The above screenshot are 2 terminal windows running at the same time on my PC. I don't think it should be possible to run 2 different applications on the same ip+port? Symfony should either fail and give a usefull description or check for another port to be available (e.g. 8080, 1234, etc.)

**Comment by dosten** [comment]
See #14063

**Comment by xabbuh** [comment]
#14063 fixes this only for the `server:start` command. But I agree that the same would be useful for the `server:run` command too.

**Comment by dosten** [comment]
can this be closed?

**Comment by xabbuh** [comment]
@dosten You can reference this ticket in your PR table under the fixed tickets label. It will then be closed automatically when your PR gets merged.

**Comment by dosten** [comment]
@xabbuh done!
