### ISSUE TITLE
Form View Transformer inconsistency

### ISSUE THREAD

**Issue by flack** [symfony/symfony#14276]
I'm not sure if this has been discussed already, but I couldn't find anything of relevance, so my apologies if I overlooked it.

I'm using a custom `CollectionType` to manage files (where each child consists of one `text` and one `file` field. You can upload new files or edit existing ones). I have a `ViewTransformer` that converts norm data into the format my templates need. It all works very well under normal circumstances, but when there is a validation error (from a different field in the same form) during form submit, the ViewTransformer is not running for new items in the collection (while the ones coming from storage work fine). 

I've debugged the problem and found out that this happens because during `setData()` the `ViewTransformer`is run before the children are processed (see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Form.php#L353), while in the `submit()` case, the children are processed with either the existing viewData (i.e. what came from `setData()`) or the submit data (see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Form.php#L610). The transformer on the parent is called afterwards (https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Form.php#L649)

So after `submit()`, my `CollectionType` has transformed `viewData`, while it's children have a mix of transformed and untransformed data (depending on whether there was a file upload or not).

So my question is: Is this the intended behaviour? And if so, how can I work around it?

**Comment by HeahDude** [comment]
Hi @flack, this indeed look like a bug but not easy to work around. That would greatly help if you could provide a fork of symfony standard to reproduce your issue. Thanks!

**Comment by flack** [comment]
ok, I will try to factor out my code and make a sample with sf standard edition. I don't have a lot of experience with sf full stack, so it might take a couple of days

**Comment by xabbuh** [comment]
@flack Any updates? :)

**Comment by jakzal** [comment]
@flack closing due to lack of feedback. We'll reopen as soon as you manage to provide code to reproduce your issue.

**Comment by flack** [comment]
Ys, that's alright with me. I've tried reproducing it with current Symfony, but I could only manage to do so if I had a slightly buggy converter. So either the problem has been fixed sometime between last year and now, or it has been an error on my part all along
