### ISSUE TITLE
[2.3] Reference mismatches

### ISSUE THREAD

**Issue by kalessil** [symfony/symfony#14273]
Additional (filtered) list of reference mismatches for #14206.

Where there is sense, following aggressive optimization possible (readability will suffer):
array_key_exists => isset + array_key_exists.
 
The last entry seems to have purpose, needs a short comment that it's designed this way.

```php
// src/Symfony/Component/DomCrawler/FormFieldRegistry.php:64
if (!array_key_exists($path, <$target>)) {

// src/Symfony/Component/PropertyAccess/PropertyAccessor.php:79
$this->writeIndex($objectOrArray, $property, <$value>);

// src/Symfony/Component/PropertyAccess/PropertyAccessor.php:81
$this->writeProperty($objectOrArray, $property, $singular, <$value>);

// src/Symfony/Component/DomCrawler/FormFieldRegistry.php:88
if (!array_key_exists($path, <$target>)) {

// src/Symfony/Component/HttpFoundation/Session/Attribute/NamespacedAttributeBag.php:91
if (null !== $attributes && array_key_exists($name, <$attributes>)) {

// src/Symfony/Component/PropertyAccess/PropertyAccessor.php:118
(is_array($objectOrArray) && !array_key_exists($property, <$objectOrArray>))

// src/Symfony/Component/HttpFoundation/Session/Attribute/NamespacedAttributeBag.php:133
if (null !== $array && !array_key_exists($part, <$array>)) {

// src/Symfony/Component/Security/Acl/Domain/Acl.php:539
$oldValue = $aces;
```

//cc @fabpot

**Comment by javiereguiluz** [comment]
@kalessil do you still consider this issue relevant or has it been replaced by other issues or pull requests? Thanks.

**Comment by javiereguiluz** [comment]
I'm closing this issue because it doesn't look very actionable. @kalessil please open a pull request instead so we can discuss about the actual proposed changes. Beware that if the changes decrease code readability, they will probably be rejected. Thanks!

**Comment by kalessil** [comment]
Since this not relevant for PHP7, I'd invest time into this.
