### ISSUE TITLE
Bootstrap horizontal layout possible bug

### ISSUE THREAD

**Issue by AntonioAmore** [symfony/symfony#14290]
I have following form controls
```php
   /** @var FormBuilderInterface $builder */
   $builder
            ->add('submit','submit', array(
                    'label' => 'Filter'
                ))

            ->add('clear','reset', array(
                    'label' => 'Clear filter'
                ));

```
Form template contains
```twig
{% extends 'bootstrap_3_horizontal_layout.html.twig' %}
```

Styling were applied to Filter. and not to Clear filter control.

I added to the ```bottom of bootstrap_3_horizontal_layout.html.twig``` following lines which fixed the issue:

```twig
{% block reset_row -%}
{% spaceless %}
    <div class="form-group">
        <div class="{{ block('form_label_class') }}"></div>
        <div class="{{ block('form_group_class') }}">
            {{ form_widget(form) }}
        </div>
    </div>
{% endspaceless %}
{% endblock reset_row %}
```
Platform: Symfony 2 Standard Edition 2.6.6

**Comment by dosten** [comment]
How do you applied the theme to the form?

**Comment by AntonioAmore** [comment]
```twig
{% form_theme a_form with ['ABundle:Form:a-form.html.twig'] %}
    {{ form(a_form) }}
```

**Comment by JHGitty** [comment]
> Best Practice
> Add buttons in the templates, not in the form classes or the controllers.

http://symfony.com/doc/current/best_practices/forms.html#form-button-configuration

**Comment by cordoval** [comment]
@JHGitty no, i think his context is different, he is grouping the buttons of certain filters together. Best practices are suggestions for beginners that may/may not apply for all cases.

**Comment by dosten** [comment]
@cordoval agree
@AntonioAmore btw, do you resolved your issue?

**Comment by AntonioAmore** [comment]
@dosten Actually yes - I had 2 ways to solve the issue from begining:
1. Add some css styles by button's selector
2. Patch ```bootstrap_3_horizontal_layout.html.twig``` - I copied the description of reset button from submit of the same twig, as mentioned on the top of the thread - the subj, actually.

So if add those lines, everything works fine, and I supposed we may update ```bootstrap_3_horizontal_layout.html.twig``` as I proposed.
