### ISSUE TITLE
E_USER_DEPRECATED in TwigExtension

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#14305]
the TwigExtension use the deprecated parameter `twig.form.resources` in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L58

**Comment by xabbuh** [comment]
IIRC, the parameter needs to be kept here as third-party bundles rely on it.

**Comment by cordoval** [comment]
@xabbuh is right, bundles like braincrafted bundle relies on this https://github.com/braincrafted/bootstrap-bundle/blob/develop/DependencyInjection/BraincraftedBootstrapExtension.php#L158-L170. but if you don't use these bundles or the bundles get updated then this warning does not show up. So i believe this ticket can be closed? @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Maybe we should open issues/PRs on the bundle we find that need to be updated, referencing this issue?

**Comment by cordoval** [comment]
yeah i believe so too and close this one.

**Comment by jderusse** [comment]
Indeed, the warning was not triggered by this line, but by a `twig.form.resources` in my config. Sorry for the inconvenience

**Comment by cordoval** [comment]
good catch though, now we can create tickets in other bundles to update them for 2.7. @nicolas-grekas do you think i should add a note like i did here https://github.com/symfony/symfony/pull/14321/files but for this case?
