### ISSUE TITLE
[EventDispatcher]Get priority on listeners/subscribers 

### ISSUE THREAD

**Issue by dupuchba** [symfony/symfony#14302]
Hello all,

I'd like to know if there is a way to retrieve listeners/subscribers priority. 
There is nothing specified  in the `EventDispatcherInterface`.
@stof as a merger of this component can you tell me ?

Another question I have is why we implicitly sort listeners in `getListeners` in the `EventDispatcher.php`. It's confusing to me because as a user of `getListeners` I am not aware that listeners are already sorted..

**Comment by stof** [comment]
@dupuchba there is no way to get the priorities.

regarding the fact that the listeners are returned sorted, feel free to send a PR improving the phpdoc to mention it.

**Comment by dupuchba** [comment]
@stof Ok, thx :-).

But what do you think about decoupling the sorting of listeners and their "getting". 
Besides is this the right design behavior to not being able to get priority ?

**Comment by stof** [comment]
@dupuchba how would you decouple it ? and we cannot return them not sorted. It would be a BC break. ``getListeners`` is expected to give the listeners in the order in which they will be called.

**Comment by dupuchba** [comment]
I don't know how to decouple it, it might be a terrible idea. I still added some information on the phpdoc https://github.com/symfony/symfony/pull/14304 .
My main goal is to fetch priorities, I have if it's possible and desirable

**Comment by dupuchba** [comment]
@stof just to continue on our discussion, do you see any value on being able to retrieve the priority of a given listener/subscriber ?

**Comment by jakzal** [comment]
there's already a discussion about it in #11263

**Comment by dupuchba** [comment]
@jakzal you just closed the other one :(

**Comment by stof** [comment]
@dupuchba the other one is not closed
