### ISSUE TITLE
Creating a route with an empty (optional) parameter doesn't work in Twig when using "merge"

### ISSUE THREAD

**Issue by LiNgOtT** [symfony/symfony#14314]
### Description
Building a URL in Twig with `path(..)` throws an error when route has a `null` value of an optional parameter.
This only happens, if you merge an array of parameters to the second argument of `path(..)`.
```
{{ path(app.request.attributes.get('_route'),app.request.attributes.get('_route_params')|merge({'page':loop.index})) }}
```

The parameter `$id` is null in this case and I got the error message below:

Seems to be a similar issue as reported here: #7316

### Controller action
```
     * @Route("/{_locale}/catalog/{id}/{page}", name="catalog")
     * @param string    $_locale    iso locale from request
     * @param int       $id
    public function catalogAction($_locale, $id = null, $page = 1)
```

### Twig template with `merge`
```
<a href="{{ path(app.request.attributes.get('_route'),app.request.attributes.get('_route_params')|merge({'page':loop.index})) }}">{{ i }}</a>
```

### Error
```
An exception has been thrown during the rendering of a template ("Parameter "id" for route "catalog" must match "[^/]++" ("" given) to generate a corresponding URL.") in catalog/main.html.twig at line 124.
```

### Twig template WITHOUT `merge`
... is working without any exceptions.
```
<a href="{{ path(app.request.attributes.get('_route'),app.request.attributes.get('_route_params')) }}">{{ i }}</a>
```

**Comment by Tobion** [comment]
Thanks for the detailed report. But this is the expected behavior.

What URL are you excepting to generate when `id` is not set (default `null`) but `page != 1`? There is no URL that can be generated to match your route. Lets say id is null and page is 2. It cannot genrate `/de/catalog/2` because its missing the id. And `/de/catalog//2` (empty id) does't make sense either.

**Comment by LiNgOtT** [comment]
My fault, you are absolutely right. 
Thank you so much for the explanation.
