### ISSUE TITLE
app/bootstrap.cache.app should end with a newline character

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#14327]
The file should end with a newline character.
Infact, each time I run the insight.sensio checks, it reports this issue.

Maybe a good thing if the generated file ends with a new line character.

**Comment by Aerendir** [comment]
Deepening into this issue, i found it is in reality caused by this file https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/bin/build_bootstrap.php

It is in the SensioDistributionBundle, different from Symfony package... What should have I to do now to move this issue from here to the proper location? o.O

**Comment by fabpot** [comment]
Yes, moving it to the bundle would be better. Thanks.

**Comment by Aerendir** [comment]
I have simply created a new issue there in the SensioDistributionBundle repo: https://github.com/sensiolabs/SensioDistributionBundle/issues/202

I'm closing this...
