### ISSUE TITLE
Question on bugfixing flow

### ISSUE THREAD

**Issue by cordoval** [symfony/symfony#14322]
perhaps now that 2.7 is about to go out, all from now fixes are going to go now to 2.7 from tomorrow right? not to 2.3 right? Someone is going to have to either back port things right? Or 2.3 is totally dying out right after 2.7 enters in place?

**Comment by nicolas-grekas** [comment]
http://symfony.com/roadmap?version=2.3#checker means fixes still go to 2.3 when possible
