### ISSUE TITLE
FileLoaderImportCircularReferenceException wrong on Symfony version 2.6.6 

### ISSUE THREAD

**Issue by juliomatcom** [symfony/symfony#14329]
Hi this is an error  that for some people must be confusing, when you dont add in a controller using annotations route the correct namespaces like:
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
```
and then you use : 
```
    * @Method({"GET"})
```

In some anotattion in a controller Symfony throw an Exception that says:

```
Whoops, looks like something went wrong.
1/1 FileLoaderImportCircularReferenceException in FileLoader.php line 97:
...
```

witch is wrong and confusing, thanks

**Comment by dosten** [comment]
Duplicated of #14199
