### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by byarabah** [symfony/symfony#14326]
Hi,

When I go on http://127.0.0.1:8000 or http://localhost:8000, I see the following message in the console (and nothing in browser):

[Symfony\Component\Process\Exception\RuntimeException]
   The process has-been Signaled signal with "11".
                                                           
server: run [-d | --docroot = "..."] [-r | --router = "..."] [address]

An idea?

I'm on Mac OS X Yosemite (10.10.3)

**Comment by dupuchba** [comment]
Some questions : 
- php version
- sf version
- os version

Anything that can help us understand the context

**Comment by byarabah** [comment]
PHP 5.5.20
Symfony 2.6
Apache/2.4.10 (Unix)
OS X Yosemite (10.10.3)

The problem occurs every time I test a page from browser. I make no particular change.

Thanks.

**Comment by xabbuh** [comment]
Can you please execute the `server:run` command with the `-vvv` option and check if you get a more detailed error message then?

**Comment by byarabah** [comment]
Yes,
More detailed error message:
Exception trace:
 () at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:367
 Symfony\Component\Process\Process->wait() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:210
 Symfony\Component\Process\Process->run() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/ProcessHelper.php:58
 Symfony\Component\Console\Helper\ProcessHelper->run() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerRunCommand.php:121
 Symfony\Bundle\FrameworkBundle\Command\ServerRunCommand->execute() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/b/Sites/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/b/Sites/test/app/console:27

**Comment by byarabah** [comment]
Now I see this error:
FileLoaderImportCircularReferenceException in FileLoader.php line 97:
Circular reference detected in "/Users/b/Sites/test/app/config/routing_dev.yml" ("/Users/b/Sites/test/app/config/routing_dev.yml" > "/Users/b/Sites/test/app/config/routing.yml" > "/Users/b/Sites/test/src/AppBundle/Controller/" > "/Users/b/Sites/test/app/config/routing_dev.yml").

**Comment by dupuchba** [comment]
What is the action that you are triing to execute ?

**Comment by xabbuh** [comment]
@byarabah Reading your last error message, can you please check if your issue is related to #14199 and if you are able to solve your issue that way?

**Comment by byarabah** [comment]
No, that does not solve.
@dupuchba I try to display page in browser

**Comment by xabbuh** [comment]
@byarabah Can you provide the steps needed to reproduce your issue? Or does this also happen with an unmodified Symfony Standard Edition?

**Comment by byarabah** [comment]
Problem solved. The cause was this route:
Route("/{Id}" name = "click_test" requirements = {id = "[0-9] +"})

Missing quotes around "id"

Thank you and sorry, the bug was me!
