### ISSUE TITLE
[FrameworkBundle] Bundled router files have hardcoded front controller names

### ISSUE THREAD

**Issue by willdurand** [symfony/symfony#14339]
Hi!

Not sure whether we can do anything for this, but [router_dev.php](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php) _et al._ require `app_[dev|test].php` front controllers, which might not exist. For instance, I use `index.php` files rather than `app.php`.

Because such files are not part of the Standard Edition (that is opinionated), I wonder if it would be possible to be less restrictive here. I don't really understand why those "routers" are needed to be honest, because a simple `php -S ... -t web/` does the job well (maybe for static files but I guess the built-in webserver is smart enough now).

Note that PR #14129 somehow solves this problem as one could run (but it requires extra characters to type...):

    app/console router:start --router=web/index.php

Regards,
William

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback from the community. Besides, as you said, Symfony already provides an alternative solution to this issue.
