### ISSUE TITLE
[Valdiator] PHP Fatal error:  Cannot use 'True' as class name as it is reserved 

### ISSUE THREAD

**Issue by BlackScorp** [symfony/symfony#14336]
Hello guys, i'am getting an error while running my tests on PHP 7

will be this changed somehow in the future?

https://travis-ci.org/Opentribes/Core/jobs/58144458

**Comment by stof** [comment]
Yes it will. See #14086 for the issue tracking this, and #14228 for the WIP fixing this. I'm closing this issue as duplicate.

**Comment by Orgoff** [comment]
I have a similar problem. I fix it when i change annotation "@Assert\True" by "@Assert\IsTrue" in my entity.

**Comment by vajiralasantha** [comment]
> I have a similar problem. I fix it when i change annotation "@Assert\True" by "@Assert\IsTrue" in my entity.

Confirmed working. Thanks.
