### ISSUE TITLE
ArrayChoiceList usage

### ISSUE THREAD

**Issue by maximecolin** [symfony/symfony#14350]
Hi,

I'm trying to replace a ChoiceList which is deprecated by an ArrayChoiceList as recommended in ChoiceList docblock.

Unfortunately I can't reproduce the wanted ChoiceList result with an ArrayChoiceList.

Before i had

```
'choice_list' => new ChoiceList(
    ['yes' => true,  'no'  => false], // html value => php value
    ['yes' => 'Oui', 'no'  => 'Non']  // html value => label
),
'expanded'  => true,
```

Which create a choice with 2 radio buttons, the html values were yes/no, the html labels were Oui/Non and the php values were true/false. Everything works fine.

Now I want to replace it by a ArrayChoiceList. I reproduce almost the same behavior using the following code :

```
'choice_list' => new ArrayChoiceList(
    ['Oui' => true, 'Non' => false], 
    function ($choice) { return true === $choice ? 'yes' : (false === $choice ? 'no' : null); }
),
'expanded'  => true,
```

The form is posted and data are saved well (true or false depending on the radio I checked) but the form isn't preset when I create the form with data. The form data is different from the entity data. I'm not sure if I'm not using it correctly or if there is a bug. The ArrayChoiceList doc is not clear.

![capture d ecran 2015-04-14 a 15 17 31](https://cloud.githubusercontent.com/assets/606766/7137430/df261b66-e2b9-11e4-9d7d-9d1c626bc48c.png)

![capture d ecran 2015-04-14 a 15 31 34](https://cloud.githubusercontent.com/assets/606766/7137641/65b2dcf4-e2bb-11e4-80d0-e5e9d5794d56.png)

**Comment by Tobion** [comment]
choice_list is deprecated as well. You can just use `choices` directly. See #14050

**Comment by stof** [comment]
@Tobion this is wrong. the ``choice_list`` option is not deprecated

@maximecolin what are you dumping for the form data

**Comment by adam187** [comment]
@stof Looks like it is

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L261

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L315

**Comment by maximecolin** [comment]
@stof I'm dumping ```form.newsletter.vars.data```

@Tobion Thanks, it looks like what I need, but I can't make it works neither.

First, ```'choice_value' => function ($choice, $key) { ... }```, i've got an error, $key parameter seems to be unexpected.

Then i try this way :

```
            'choices' => [
                'Oui' => true,
                'Non'  => false,
            ],
            'choices_as_values' => true,
            'choice_value' => function ($choice) {
                if (true === $choice) {
                    return 'yes';
                }

                if (false === $choice) {
                    return 'no';
                }

                return null;
            },
```

This is quite the same thing as the doc in the PR but it produce the same result as the ArrayChoiceList. The data are well saved, but no form preset from existing value.

I don't understand how it works.

**Comment by Tobion** [comment]
How do you create the form and field?

**Comment by maximecolin** [comment]
@Tobion Nothing strange. I used this form type before the choice update and it worked well. Since the update I can't make it works.

Before (works):

```php
class YesNoType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'translation_domain' => 'forms',
            'choice_list'        => new ChoiceList(
                [
                    'yes' => true,
                    'no'  => false,
                ],
                [
                    'yes' => 'yes_no.yes',
                    'no'  => 'yes_no.no',
                ]
            ),
        ]);
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'yes_no';
    }
}
```

After (doesn't work):

```php
class YesNoType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'translation_domain' => 'forms',
            'choices' => [
                'yes_no.yes' => true,
                'yes_no.no'  => false,
            ],
            'choices_as_values' => true,
            'choice_value' => function ($choice) {
                if (true === $choice) {
                    return 'yes';
                }

                if (false === $choice) {
                    return 'no';
                }

                return null;
            },
        ]);
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'yes_no';
    }
}
```

**Comment by althaus** [comment]
I've also run into some trouble with the `ArrayChoiceList` when I'm trying to replace a deprecated `SimpleChoiceList`. :(

**Comment by pandy06269** [comment]
I'm also having difficulty getting my head around the ArrayChoiceList class.  I have an array which contains a list of objects, keyed by the object ID.  I.e.

```
[101] => object(
  'name' => 'test',
  'isDefault' => 1
),
[102] => object(
  'name' => 'test 2',
  'isDefault' => 1
);
```

I want to display this in a select so that the "name" property of each object is the label of the select, and the ID (the array key) is the value.

When a user submits the form, I want the actual object to be returned from my form.

If I implement it like so, I get an increasing index as my "value" attributes (i.e. 0, 1, 2) and the actual array key as the label (i.e. 101, 102).
```
'choice_list' => new ArrayChoiceList($accountTypes)
```

If I implement the callable option, I get my ID as both the "value" attribute and the label:
```
'choice_list' => new ArrayChoiceList($accountTypes, function($obj)
        {
            if (is_null($obj))
            {
                return null;
            }

            return $obj->getUid();
        });
```

My "object" class has a __toString() method which returns the name property, but this doesn't seem to be used.

The documentation states the indicies of the array must be strings and must be unique, but this class seems to be backwards in that the array keys from the array I supply are used as the option labels. However a label can be unique - I could (theoretically) have 2 items labelled as "test" with 2 different IDs.

The documentation also says that if I want to use my own custom objects, I must use the 'choice_list' option, not 'choices' - but it seems like the only thing I can customise is the value. This doesn't make much sense to me.

I've also tried implementing by own ChoiceListInterface class, but again, all I can get it to render as the label is the array key (i.e. my ID) not the text.

Looks like I'll be back to dealing with key/value pairs in 'choice_list' for now.

**Comment by pandy06269** [comment]
http://symfony.com/blog/new-in-symfony-2-7-choice-form-type-refactorization

After a bit more Google'ing, turns out I needed the 'choice_label' option - very confusing. 

Why can I customise the value in a callback to ArrayChoiceList, but not the label?

Why can I then use the 'choice_label' option to specify the property the label is read from, but have to use a callable when I create my ArrayChoiceList to do this for the value? ('choice_value' doesn't work the same way - no error, but goes back to using 0, 1, 2... instead.)

Why does the choice field type use the array key as the label, instead of an object's __toString() method? (something I'm sure it did previously.)

**Comment by herodrigues** [comment]
Another thing that I can say is how to pass labelPath in an ArrayChoiceList?

I used to do like this with ObjectChoiceList, but since it is deprecated, how can I do this same thing with ArrayChoiceList?
```php
public function configureOptions(OptionsResolverInterface $resolver) {
        $productRepository = $this->productRepository;

        $choiceList = function (Options $options) use ($productRepository) {
            
            $choices = $productRepository->findAll();
            return new ObjectChoiceList($choices, 'getName', array(), null, 'id');
        };

        $resolver
                ->setDefaults(array(
                    'choice_list' => $choiceList,
                    'label' => 'cilli.form.product',
                    'empty_value' => 'cilli.form.select',
                ))
        ;
    }
```

**Comment by trsteel88** [comment]
I am with @herodrigues. I loved the ObjectChoiceList class. How do you replicate that functionality with the ArrayChoiceList?

**Comment by ureimers** [comment]
The main problem seems to be the lack of documentation for the new choice type. It's all very confusing and frustrating at the moment. For instance http://symfony.com/doc/current/reference/forms/types/choice.html#choice-list states, that `choice_list` is deprecated and that one should use `choice` or `choice_loader`. The `choice_loader` isn't documented anywhere. Asking google it seems that not a single person in the internet ( ;-) ) knows how to use the `choice_loader`.
I would be glad to provide some upgrade documentation in the form of "before" and "after" but honestly, right know I can't get my own deprecated `choice_list`s to work as `choice_loader`s using the (also undocumented) `DoctrineChoiceLoader` either.

**Comment by althaus** [comment]
@ureimers I started to update the reference https://github.com/symfony/symfony-docs/pull/5847 based on my experiences and the information I gathered from various documents. The missing doc is tracked in https://github.com/symfony/symfony-docs/issues/5179. Any help is appreciated.

**Comment by ureimers** [comment]
:+1:
Symfony's documentation is one of the keys of its success. I'm still a GIT noob, but will try my best if I find enough time.
In the end, maybe the choice type is just to complex to cover all its use cases for a comprehensive "before/after" and that's when a solid documentation comes into play.

**Comment by dodysw** [comment]
I noticed that ArrayChoiceList convert false values to empty string, which conflicted with with placeholder hiding logic. Placeholder is not generated if one of choice's value  already has an empty value. Is this related to this issue or shall I open a new issue?

**Comment by paradajozsef** [comment]
> I noticed that ArrayChoiceList convert false values to empty string

@dodysw There is already an issue about that: #17292

**Comment by dodysw** [comment]
You're right. Thanks, should've search first before posting.

**Comment by webmozart** [comment]
Hi all! Just to clear up some confusion in case somebody else reads this thread: I don't recommend to use ArrayChoiceList. With the `choice_*` options you can solve all of your problems.

> ```
> [101] => object(
>   'name' => 'test',
>   'isDefault' => 1
> ),
> [102] => object(
>   'name' => 'test 2',
>   'isDefault' => 1
> );
> ```

> I want to display this in a select so that the "name" property of each object is the label of the select, and the ID (the array key) is the value.

@pandy06269 You can achieve this in this way:

```php
$builder->add('property', ChoiceType::class, [
    'choices' => $objects, // as above
    'choice_label' => 'name', // ->name property
    'choice_value' => function ($object, $key) {
        return (string) $key; // key of the $objects array
    },
]);
```

@herodrigues You can pass the property path to the `choice_label` option now, as in the example I just gave.

In general, the API documentation should give you information about the functionality of the new classes. I agree however that the manual needs many improvements. If anybody wants to work on that, please don't hesitate to ping me (best via mail) for questions.

**Comment by webmozart** [comment]
Actually the current documentation isn't so bad: http://symfony.com/doc/current/reference/forms/types/choice.html

**Comment by webmozart** [comment]
See also https://github.com/symfony/symfony-docs/issues/6144

**Comment by herodrigues** [comment]
Thanks @webmozart :+1: 

I actually did that, but I forgot to comment it here.

**Comment by javiereguiluz** [comment]
Closing it as fixed because Bernhard has provided an alternative solution and he doesn't recommend to keep using ArrayChoiceList.
