### ISSUE TITLE
Show forwarded controller/sub request on the web dev toolbar

### ISSUE THREAD

**Issue by michaelcullum** [symfony/symfony#14358]
As it uses the request attributes it still detects it as the controller set by the router, if you forward to another controller it only detected as a sub request and not visible at first glance on the web dev toolbar. It could/should show any forwarded controllers/sub requests or at least the final controller that renders a response in the expanded information (on the web developer toolbar).

**Comment by javiereguiluz** [comment]
A forward performed with the `forward()` shortcut uses this code:

```php
        $path['_controller'] = $controller;
        $subRequest = $this->container->get('request_stack')->getCurrentRequest()->duplicate($query, null, $path);

        return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
```

I don't know how could we differentiate this request from other regular sub-requests to display it as a forward. If anybody knows, please tell me and I can try to add something to the Symfony Profiler.

**Comment by javiereguiluz** [comment]
I'm closing this for the same reasons explained by @stof here: https://github.com/symfony/symfony/issues/17501#issuecomment-175568777 and related to the limitations of the HTTP protocol. I'm sorry.

**Comment by HeahDude** [comment]
@javiereguiluz This is not the same as #17501, since in this case the kernel is already booted and handle the sub request without redirecting the browser, so we could add an attribute on the request like `'_redirected' => $from` to get it later

**Comment by javiereguiluz** [comment]
Let's reopen the issue to explore the idea provided by @HeahDude.

**Comment by HeahDude** [comment]
@javiereguiluz I finally managed to get an implementation working but I'm actually missing a way to add a nice arrow before the route name in the wdt as you suggested in your comment https://github.com/symfony/symfony/issues/17501#issuecomment-175554281
can you give me a hand on this ?

**Comment by HeahDude** [comment]
@michaelcullum @javiereguiluz see my proposal #17589

**Comment by javiereguiluz** [comment]
@HeahDude I was going to reply to your previous comment ... but this is not longer needed. You did it perfectly. Thanks!

**Comment by HeahDude** [comment]
@javiereguiluz with pleasure :) but I think it's not perfect actually I exported the svg from Abode Illustrator but coordinates looks weird even if this is working properly. Any clue ?

**Comment by javiereguiluz** [comment]
Actually, I was thinking about the icon. If some day we support redirects as well as forwards, maybe we would like to use:

* [This](http://fortawesome.github.io/Font-Awesome/icon/share/) for redirects
* Something between [this](http://fortawesome.github.io/Font-Awesome/icon/arrow-right/) and [this](http://fortawesome.github.io/Font-Awesome/icon/long-arrow-right/) for forwards

I can ask our designer to prepare these icons for the toolbar (he already prepared all the other icons).

**Comment by HeahDude** [comment]
@javiereguiluz great ! from my POV the long one is better

**Comment by HeahDude** [comment]
@javiereguiluz It seems that we may need an `redirect.svg` too after all ;)

**Comment by michaelcullum** [comment]
Thanks for taking the time to work on this @HeathDude. I agree with Javier regarding the images though.

**Comment by HeahDude** [comment]
Thank you @michaelcullum for pointing this as I must say that now I'm actually using it, it's pretty handy :) I'm waiting for some pretty arrows too ;)
