### ISSUE TITLE
Bug in getTemplating_Helper_AssetsService() Symfony 2.7-Beta 1

### ISSUE THREAD

**Issue by apfz** [symfony/symfony#14368]
This was triggered by having {{ tinymce_init() }} in a javascript block. 

An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper::__construct() must be an instance of Symfony\Component\Asset\Packages, string given, called in /my/directory/app/cache/dev/appDevDebugProjectContainer.php on line 5370 and defined"

**Comment by dosten** [comment]
Can you paste the generated `getTemplating_Helper_AssetsService()` method in `app/cache/dev/appDevDebugProjectContainer.php` ?

**Comment by apfz** [comment]
sorry I forgot. Here it is!

 <pre><code>
   /**
     * Gets the 'templating.helper.assets' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper A Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper instance.
     */
    protected function getTemplating_Helper_AssetsService()
    {
        return $this->services['templating.helper.assets'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper('', array());
    }
</code></pre>

The first parameter for AssetHelper is an empty string, where as we look at the constructor of AssetHelper, it actually expects a Asset\Packages object. 

<pre><code>
namespace Symfony\Bundle\FrameworkBundle\Templating\Helper;

use Symfony\Component\Asset\Packages;
use Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy;
use Symfony\Component\Templating\Helper\Helper;

/**
 * AssetsHelper helps manage asset URLs.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class AssetsHelper extends Helper
{
    private $packages;

    public function __construct(Packages $packages)
    {
        $this->packages = $packages;
    }
</code></pre>

**Comment by taemtha** [comment]
I got the same error here.
This happen if i calling an twig extension which need the 'templating.helper.assets' service.

```
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper::__construct() must be an instance of Symfony\Component\Asset\Packages, string given, called in /var/www/app/cache/dev/DevDebugProjectContainer.php on line 5428 and defined") in myapp/src/App/Resources/views/app.config.html.twig at line 9.
```

Generated code in the devcontainer:
```
    /**
     * Gets the 'templating.helper.assets' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper A Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper instance.
     */
    protected function getTemplating_Helper_AssetsService()
    {
        return $this->services['templating.helper.assets'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper('', array());
    }
```

**Comment by taemtha** [comment]
The faulty service is configured here:
./symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/templating.xml
```xml
       <parameter key="templating.helper.assets.class">Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper</parameter>


        <!--
            This service will be moved to templating_php.xml in version 3.0, it exists here for BC reasons.
        -->
        <service id="templating.helper.assets" class="%templating.helper.assets.class%">
            <tag name="templating.helper" alias="assets" />
            <argument /> <!-- default package -->
            <argument type="collection" /> <!-- named packages -->
        </service>
```

but the class:
./symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/Helper/AssetsHelper.php

has only the new construcor with the only parameter " Package $package"

```php
    public function __construct(Packages $packages)
    {
        $this->packages = $packages;
    }
```

**Comment by dosten** [comment]
@taemtha I don't find any code that replace the first argument with a default package, if you delete the `<argument /> <!-- default package -->` line, works?

**Comment by jakzal** [comment]
The first argument is [replaced by FrameworkExtension](https://github.com/symfony/FrameworkBundle/blob/4d4a85bed21604132db86d24d0af101518a18d50/DependencyInjection/FrameworkExtension.php#L593).

**Comment by dosten** [comment]
@jakzal that code replaces the default package and the packages into the `assets.packages` definition, AssetsHelper needs as first argument an instance of `Packages`, so this defintion is wrong, right?
```
<service id="templating.helper.assets" class="%templating.helper.assets.class%">
     <tag name="templating.helper" alias="assets" />
     <argument /> <!-- default package -->
     <argument type="collection" /> <!-- named packages -->
</service>
```
must be
```
<service id="templating.helper.assets" class="%templating.helper.assets.class%">
     <tag name="templating.helper" alias="assets" />
     <argument type="service" id="assets.packages" />
</service>
```
correct me if i'm wrong

**Comment by dosten** [comment]
The tests of AssetsHelper seems fine, but the definition seems wrong.

**Comment by xabbuh** [comment]
@apfz @taemtha Can you please check if the changes from #14419 solve your issue?

**Comment by markitosgv** [comment]
Same bug error with IvoryCKEditorBundle library

**Comment by xabbuh** [comment]
@markitosgv Can you please also check if #14419 goddess this for you?

**Comment by markitosgv** [comment]
@xabbuh test ok! solve IvoryCKEditorBundle problem too

**Comment by taemtha** [comment]
@xabbuh The changes from #14419 solves my issue! Thanks!

**Comment by apfz** [comment]
Yes this fixed it!
