### ISSUE TITLE
EventDispatcher multiple handlers in one Listener gives error

### ISSUE THREAD

**Issue by danaki** [symfony/symfony#14363]
My listener looks like that:

```
class PostPersonificationListener implements EventSubscriberInterface
{
    public function items1(ItemsEvent $event)
    {
        die('items1');
    }

    public function items2(ItemsEvent $event)
    {
        die('items2');
    }


    public static function getSubscribedEvents()
    {
        return array('knp_pager.items' => array(array('items1', 10), array('items2')));
    }
}
```

Just tried to implement multiple listeners with different priorities in one class followed documentation inside the class https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/EventSubscriberInterface.php

After app/console cache:clean get Notice: Array to string conversion 500 Internal Server Error - ContextErrorException in in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php at line 190

```
$key = $serviceId.'.'.$method;
```

**Comment by dupuchba** [comment]
@danaki can you provide a repo to simplify test or confirm that only implementing multiple listeners in one class make an internal error ?

**Comment by dosten** [comment]
@danaki what version are you using it?

**Comment by dupuchba** [comment]
@danaki can't reproduce your bug :(

**Comment by danaki** [comment]
"symfony/symfony": "2.6.*"

**Comment by xabbuh** [comment]
@danaki Will you be able to fork the Symfony Standard Edition and make the necessary changes that are required to reproduce your issue? Or at least describe the steps that make it possible to reproduce it?

**Comment by dupuchba** [comment]
@xabbuh :+1:

**Comment by stof** [comment]
@danaki why have you closed it ? Is it solved for you ? If yes, please describe what it was to help people who might face the same

**Comment by danaki** [comment]
Can't reproduce it manually, can't get to work custom events in Symfony since there're lack of documentation and free time. Tried with knp paginator items event like in example in topic starter -- gives the same error. So in conclusion can't expose my private project sources where the error reproduces and can't reproduce it on clean project.
