### ISSUE TITLE
Routing component has a dependency that is not specified in its composer.json

### ISSUE THREAD

**Issue by SoboLAN** [symfony/symfony#14376]
I ran into a bit of a problem while writing some code.

A project of mine depends on `Routing` component. When I was trying to write a unit-test for my code and mocking the `Router` class, PHPUnit (4.4.5) kept failing with the following error:

```
PHPUnit_Framework_MockObject_RuntimeException: Cannot mock Symfony\Component\Routing\Router::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded

Caused by
ReflectionException: Class Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface does not exist
```

As far as I can tell from [Router's source](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Router.php), it depends on `Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface`.

But, in [Routing's composer file](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/composer.json), the `ExpressionLanguage` component is specified in `require-dev`, which is incorrect.

Shouldn't it actually be in `require` ?

I added `"symfony/expression-language": "2.6.*",` dependency to my project's composer file and everything magically worked.

I made a Pull-Request with a fix for this: https://github.com/symfony/symfony/pull/14375

**Comment by xabbuh** [comment]
Thanks for reporting this @SoboLAN. However, the dependency on the ExpressionLanguage component is not a hard one. That's why it is only listed in the `suggest` section. So I'm going to close here. Please refer to #12828 for more information. Thank you.

**Comment by stof** [comment]
@SoboLAN the issue is that the PHPUnit mocking tool does not support mocking a class with typehints on non-existent methods. But as far as PHP is concerned, this is perfectly valid (a typehint does not trigger any autoloading).
Both Prophecy and Mockery are able to mock such classes properly btw.

**Comment by SoboLAN** [comment]
@stof Thanks. I already used Mockery in some projects and I like it, but in this case my team and I agreed to go with PHPUnit alone.

@xabbuh Even if the dependency is a very weak one, it's rather strange to not fix this problem. Personally, I tried the solution in the referred issue but it still doesn't work (and it intuitively makes sense that it won't). So, in order not to waste too much on this, I'll explicitly require `ExpressionLanguage` in my project.

If I ran into this issue, then there will be thousands and thousands of other people who will also run into it. Wouldn't it be easier to just change those 2 lines of code ?

PS: I'm sorry if I seem to have a bad tone, it's not intended that way.

**Comment by stof** [comment]
@SoboLAN as of PHPUnit 4.5, Prophecy is included in PHPUnit already

**Comment by stof** [comment]
@SoboLAN and there is **no** problem in Symfony. The only problem is that PHPUnit_Mock_Object does not support such case.

On a side note, you should mock the RouterInterface whenever possible rather than the Router implementation, and you won't face this issue at all (``addExpressionLanguageProvider`` is not part of the interface)

**Comment by SoboLAN** [comment]
@stof I'm so stupid ... of course I should've mocked the interface. Did it and it works. Thanks so much.
