### ISSUE TITLE
doctrine:generate:entities adds setters/getters to wrong class

### ISSUE THREAD

**Issue by michaelkonecny** [symfony/symfony#14379]
Imagine I have an entity such as:

    namespace Acme\DemoBundle\Entity;

    use Doctrine\ORM\Mapping as ORM;
    /**
     * Product
     *
     * @ORM\HasLifecycleCallbacks
     * @ORM\EntityListeners({"ProductListener"})
     */
    class Product {
        private $id;
        
        private $name;
    }

    class ProductListener {
       // ...
    
    }

If i run 

    php app/console doctrine:generate:entities AcmeDemoBundle:Product 

the new setters (setId, getId, setName, getName) get added to the ProductsListener class instead of the Product class, where they belong.

The command should check if it is adding the new setters/getters to the right class.

**Comment by phansys** [comment]
I think this check isn't done because command relies on passed entities follow PSR-0/4, thus only the entity class is expected to be found inside that file.

**Comment by michaelkonecny** [comment]
Ah, you're right, I should actually put it in a seperate file! I don't know why I didnt'.

Thank you!
