### ISSUE TITLE
Can't make new project on Centos 5.5

### ISSUE THREAD

**Issue by CuAnnan** [symfony/symfony#14389]
Centos 5.5
used the instructions on the website verbatim.

PHP Fatal error:  Call to undefined function Symfony\Installer\posix_getpwuid() in phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php on line 367

**Comment by dosten** [comment]
The error seems to be related to the Symfony Installer, can you open a PR in the symfony/symfony-installer repo?

**Comment by CuAnnan** [comment]
Sorry, new to this.
