### ISSUE TITLE
[HttpFoundation] There's no getter for Response::$statusText

### ISSUE THREAD

**Issue by mnpenner** [symfony/symfony#14388]
I'm trying to convert a Symfony Request object to a different (PSR7-compliant) request object, but there's no way for me to get the `$statusText`.

Can we get a getter please? There's one for statusCode, but not statusText.

**Comment by phansys** [comment]
Note that ```Response::$statusTexts``` var is public, thus you can get the text given any code. IE:

```php
$statusText = Response::$statusTexts[$response->getStatusCode()]
```

**Comment by mnpenner** [comment]
Yes, but `Response::$statusText` isn't necessarily equivalent to that since you can set it manually.

**Comment by phansys** [comment]
After check out [```Response::setStatusCode()```](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/Response.php#L485) this seems right. It would be a new feature. Would you mind open a PR against 2.8?

**Comment by Tobion** [comment]
The getter should be named after PSR-7.

**Comment by mnpenner** [comment]
@phansys Yeah, that's exactly what I'm talking about. You can set it, but not get it.

@Tobion i.e. `getReasonPhrase`? It's referred to as "status text" in Symfony though, are you sure it's a good idea to name it differently?

**Comment by Tobion** [comment]
Yes because that's according to RFC 2616.

**Comment by fabpot** [comment]
The status text does not bring any value and should not be relied on. That's why there is no getter in Symfony. I think that this should also be removed from PSR-7. As a matter of fact, it has been dropped from HTTP 2 altogether.

**Comment by fabpot** [comment]
I've just opened a PR on the PSR-7 repository: https://github.com/php-fig/fig-standards/pull/526

**Comment by mnpenner** [comment]
Submitted a PR. I'm not too familiar with the git/github ecosystem; hopefully I did that right.

Even if this is removed from PSR-7, I think Symfony should add the getter unless you plan on removing the setter.
