### ISSUE TITLE
[terminal] doctrine:generate:entity outside a bundle

### ISSUE THREAD

**Issue by lce-fr** [symfony/symfony#14387]
Currently it is only possible to generate entity inside bundle. However some practices recommends to put business logic outside bundle as much as possible. Therefore some projects uses the following folder hierarchy : 

src/ORM/Doctrine/Entity
src/Model
src/Transformer 

and an unique bundle in src/Vendor/AppBundle

Now if you want to generate the terminal entity, outputs will not match the architecture. I propose to fix that by doing the following : 

Check in GenerateDoctrineEntityCommand if the "prefix" property is set in  doctrine.orm.entity_manager.mappings from parameter.yml and in such case modify generation to match architecture. 

I have already done that for myself and I am starting to do it properly through the contributing process. 

Kind regards :)

**Comment by stof** [comment]
``doctrine:generate:entity`` is not part of Symfony itself, so this is the wrong issue tracker to report it. Please open an issue on SensioGeneratorBundle instead.

**Comment by lce-fr** [comment]
Sorry for the mistake, thanks !
