### ISSUE TITLE
[Form] Choice types with choice_list option breaks on 2.7

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#14382]
Form choice type with `choice_list` option seems to be broken on rendering since Symfony 2.7.

See the concerned ticket: https://github.com/sonata-project/SonataAdminBundle/issues/2916

And the concerned type: https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/ModelType.php#L103-L115

Can you confirm?

**Comment by HeahDude** [comment]
`@deprecated since version 2.7, to be removed in 3.0.
 *             Use {@link BaseChoiceListInterface} instead.`

**Comment by Soullivaneuh** [comment]
@HeahDude Thanks for this indication but deprecated does not mean BC break.

Upgrade from `2.6` to `2.7` **should not** break all related bundle. Normally no code modification had to be done, isn't it?

**Comment by Soullivaneuh** [comment]
BTW, using `ArrayChoiceList` instead of `SimpleChoiceList` does not resolve this issue.

**Comment by Soullivaneuh** [comment]
@fabpot @xelaris Having again exactly the same issue since upgrading from 2.7.1 to 2.7.2.

Any idea?
