### ISSUE TITLE
[finder] Command::addAtIndex() fails on adding Commands

### ISSUE THREAD

**Issue by jaytaph** [symfony/symfony#14384]
Even though it states it's supported, the [Command::addAtIndex](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Finder/Shell/Command.php#L290) fails when adding a `Command` to it. It works correctly with strings:

Works:

        $cmd1 = Command::create()->cmd("echo")->arg("--bar");
        $cmd1->addAtIndex('-E', 1);

Fails:

        $cmd1 = Command::create()->cmd("echo")->arg("--bar");
        $cmd2 = Command::create()->arg("-E");
        $cmd1->addAtIndex($cmd2, 1);

Before the `array_splice`, there must be a check to see if `$bit` is an instance of Command, and if so, it must be wrapped into an array first:  `$bit = array($bit)`. Otherwise it will just try to add the command's public properties instead.

**Comment by thunderer** [comment]
I reproduced this issue, exact error was:

```
PHP Notice:  Array to string conversion in %PATH%/symfony/src/Symfony/Component/Finder/Shell/Command.php on line 277
PHP Stack trace:
PHP   1. {main}() %PATH%/test.php:0
PHP   2. Symfony\Component\Finder\Shell\Command->join() %PATH%/test.php:18
PHP   3. implode() %PATH%/symfony/src/Symfony/Component/Finder/Shell/Command.php:277

Notice: Array to string conversion in %PATH%/symfony/src/Symfony/Component/Finder/Shell/Command.php on line 277

Call Stack:
    0.0003     126256   1. {main}() %PATH%/GitHub/test.php:0
    0.0051     334900   2. Symfony\Component\Finder\Shell\Command->join() /var/www/GitHub/test.php:18
    0.0051     335204   3. implode() %PATH%/symfony/src/Symfony/Component/Finder/Shell/Command.php:277
```

I applied mentioned fix and it solved the issue, tests pass as well. I'll work on a PR.

**Comment by jaytaph** [comment]
Didnt had the time to patch it up myself. Awesome work :)
