### ISSUE TITLE
[Validator] Property paths starting with 0 are broken

### ISSUE THREAD

**Issue by fago** [symfony/symfony#14394]
While working on upgrading Symfony validator API usage from 2.4 to 2.5 for Drupal, it turned out that propertypaths starting with 0 are broken. E.g. 0.value would result into value. I'll create a PR for that.

Also see https://www.drupal.org/node/2343035

**Comment by stof** [comment]
This property path ``0.value`` would mean accessing the property ``0`` of the object, and the ``value`` on it. ``0`` is an invalid property name in PHP. So what is the use case for such property path ?

**Comment by Berdir** [comment]
The case for that are lists. Our data structure are always lists of Field objects, represented by objects that implement ArrayAccess/Traversable.

**Comment by Tobion** [comment]
Array keys must be accessed with the index syntax, e.g. `[0]` in property path.
