### ISSUE TITLE
[2.7] [Form] Regression on non required ChoiceType handling

### ISSUE THREAD

**Issue by hhamon** [symfony/symfony#14393]
As of 03efce1b568379eac21d880e427090e43035f505, the `ChoiceType` is broken when dealing with empty value (or `required = false` option). Take the following simple example to illustrate the problem:

```php
<?php
// ...
class DefaultController extends Controller
{
    /** @Route("/bug") */
    public function bugAction(Request $request)
    {
        $form = $this
            ->createFormBuilder()
            ->add('assignee', 'choice', [
                'choices' => [
                    'james' => 'James',
                    'philip' => 'Philip',
                    'elisabeth' => 'Elisabeth',
                ],
                'required' => false,
            ])
            ->getForm()
        ;
        $form->handleRequest($request);
        
        if ($form->isValid()) {
            die('Yeah!');
        }

        return $this->render('default/bug.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}
```
The created form has one child field called `assignee`. It's a dropdown list of persons and it automatically includes an empty value when it's rendered thanks to the `required` option set to `false`. But when I submit the form with the empty value selected, an error message is displayed in the template saying: `This value is not valid.`. The data transformer used to convert the submitted view data asks the `ArrayKeyChoiceList` for the value `''`. But the latter doesn't have it so it throws a `TransformationFailedException`.

This regression affects all `choice` based form field types including `date`, `datetime`, `birthday`...

We still have less than 2 weeks before releasing Symfony 2.7.0, so this bug must be fixed asap.

@webmozart can you look at the fix or tell me where I should make the fix please?

**Comment by HeahDude** [comment]
Maybe symfony/Component/Form/Extension/Core/Type/ChoiceType.php line 251, but I don't know how to fix it.

**Comment by wcluijt** [comment]
I was experiencing this in my project after upgrading to 2.7.  I think it may be related to the `src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php` file change in https://github.com/symfony/symfony/commit/1d89922782922fe3bcacb09f91e8c3c992d29d3f, specifically the removal of this block of code (https://github.com/symfony/symfony/commit/1d89922782922fe3bcacb09f91e8c3c992d29d3f#diff-81585954baecb0c458557b7969974093L48):
```php
if ('' === $value || null === $value) {
    return;
}
```

When I added that back, the forms with non-required select dropdown fields with the empty option selected seemed to submit just fine.

**Comment by spackmat** [comment]
@wcluijt This fixes the problem for me, too: no more field errors for non required entity fields. Thanks!

**Comment by hhamon** [comment]
I'm not sure it's as easy as this fix because you could choose to have an « empty value » with a value. For example `---`.

**Comment by webmozart** [comment]
See #14465 for the implementation of @wcluijt's fix.

**Comment by sandermarechal** [comment]
Any updates on this? I'm suffering from the same problem.

**Comment by micayael** [comment]
Same question here :-)

**Comment by gyulaafodorr** [comment]
+1 :)

**Comment by webmozart** [comment]
#14465 was merged now.

**Comment by micayael** [comment]
:+1:

**Comment by ozzmaster** [comment]
I am having the exact same issue now in Symfony 3.1. Any way I can fix this?
