### ISSUE TITLE
[2.7][Form] label_attr in choice_attr for choice field when expanded

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#14404]
Since 03efce1 we can add attributes to options with 'choice_attr' and that's a really cool stuff among the bunch of features. Thanks for the job !

But when choice list is expanded it could be useful to pass attributes to option's label.

This throws an exception in twig rendering as html options attributes should not be arrays and they shouldn't except with this particular case of `label_attr` in `choice_attr`.

**Comment by Tobion** [comment]
As said in https://github.com/symfony/symfony/pull/14405/files#r28652029 `label_attr` in `choice_attr` is not correct. To support your use-case, we would need to add another option: `choice_label_attr` with the same logic as the other choice options.

**Comment by HeahDude** [comment]
ok, I take a look.

Thanks for the feed back.

**Comment by HeahDude** [comment]
I can't close ?
