### ISSUE TITLE
Fatal Error: Class 'Symfony\Component\Form\FormEvent' not found

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#14401]
On a production server running Symfony 2.6 fine for over a week, I suddenly started getting this error which broke the site:

php.EMERGENCY: Fatal Error: Class 'Symfony\Component\Form\FormEvent' not found {"type":1,"file":"/var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php","line":340,"level":30709,"stack":[]} []

Nothing was happening on the server at the time, the solution was to reboot Apache and clear the symfony cache.  Why would this happen without anything triggering it?

**Comment by Tobion** [comment]
Closing as this is not related to symfony and impossible to help with without any debug info. Maybe your (APC) cache got currepted or a PHP bug...
