### ISSUE TITLE
[Form] [DateType] Chaning month name

### ISSUE THREAD

**Issue by meskis** [symfony/symfony#14411]
Hello,

As I noticed, PHP natively has issue in month names in DateType and it uses PHP native month names. So is it possible to overwrite those when using date elements in forms?

**Comment by jakzal** [comment]
What's your issue with month names? 

It's not clear from your description if you've got problems using Datatype, or you're reporting a bug/feature request. If it's the first, we're not using github for support and you should use [the mailing list](http://symfony.com/mailing-lists) instead (all I can do is to point you to [the DateType reference](http://symfony.com/doc/current/reference/forms/types/date.html#months) docs). If it's the later, please explain what you're doing and what's expected and the actual outcome.

**Comment by meskis** [comment]
Ok, the question is: is it possible to overwrite month names in date form type? :)

**Comment by Tobion** [comment]
You can maybe translate them to something else or use a custom form type. Please ask questions on the mailing list.
