### ISSUE TITLE
PhpProcess seem to affect stream_sockets

### ISSUE THREAD

**Issue by cfhay** [symfony/symfony#14417]
Test environment:
OS: Windows 7 Pro 64Bit, SP1
PHP: 5.6.8 64Bit (CLI)
Symfony: 2.6.5

`stream_socket_server()` works from a script on the machine without problems. But when used in a script created by `PhpProcess`, it stops working. No idea why. When using `proc_open()` directly (both with the input file as parameter or as standard input), the problem doesn't appear. The problem doesn't appear on Linux neither.

Failing PHPUnit test:

```php
<?php

namespace Symfony\Component\Process\Tests;

use Symfony\Component\Process\PhpProcess;

class PhpProcessTest extends \PHPUnit_Framework_TestCase
{

    public function testSocket()
    {
        $socket = @stream_socket_server("tcp://127.0.0.1:1024"); //control test
        if(is_resource($socket) && get_resource_type($socket) === 'stream'){
            //run test only if socket creation otherwise works
            unset($socket);
            $phpProcess = new PhpProcess('<?php
                $socket = stream_socket_server("tcp://127.0.0.1:1024");
                echo get_resource_type($socket);
            ');
            $phpProcess->run();
            $this->assertEquals('stream', $phpProcess->getOutput());
            $this->assertEquals('', $phpProcess->getErrorOutput());
        }
    }

}
```

The error produced by the script in `PhpProcess` is:

```
Warning: stream_socket_server(): unable to connect to tcp://127.0.0.1:1024 (The operation completed successfully.)
```

**Comment by nicolas-grekas** [comment]
The Process component has been refactored recently, and I can't reproduce the issue.
Please reopen if it still holds.
