### ISSUE TITLE
Forget about app_<environment>.php

### ISSUE THREAD

**Issue by max-kovpak** [symfony/symfony#14428]
I think it's not very useful to write every time in browser app_< environment >.php. So I have some solution that I using in my projects: 
1) in parameters.yml add: 
```
parameters:
    environment: <environment name>
```
2) in app.php add code:
```php
try {
    $parser = new Symfony\Component\Yaml\Parser();
    $params = $parser->parse(file_get_contents(__DIR__.'/../app/config/parameters.yml'));
    $env = isset($params['parameters']['environment']) ? $params['parameters']['environment'] : 'prod';
} catch (Exception $e) {
    $env = 'prod';
}
```
And then set current environment to AppKernel.

**Comment by unkind** [comment]
[Symfony SE](https://github.com/symfony/symfony-standard) is better place for this kind of suggestion.

However, I think it would be easier to setup web-server properly so you can request "foo.dev", "foo.test", etc. to switch between environments.

**Comment by javiereguiluz** [comment]
@max-kovpak thanks for proposing this idea.

The main issue that I see with the proposal is that it would slow down the application a lot. Keep in mind that this file is executed for every single request, and this proposal would require to parse a YAML file each time.

Besides, it's not that bad to put the environment in the URL. Trust me that I'm very lazy and I love to simplify things, but in this case I don't think it's needed. While developing the application locally, you always use the `app_dev.php` and in production you always use the `app.php` controller. You only have to switch the file occasionally to test the production environment in your own machine. But I don't think that's an annoying issue.

**Comment by dosten** [comment]
Agree with @javiereguiluz but i like the idea of only one entry point. In a project i have only one entry point that uses the SYFMONY_ENV env var like in `app/console`.
```php
<?php

require_once __DIR__.'/../var/bootstrap.php.cache';
require_once __DIR__.'/../app/AppKernel.php';

use Symfony\Component\Debug\Debug;
use Symfony\Component\HttpFoundation\Request;

$env = getenv('SYMFONY_ENV') ?: 'prod';
$debug = getenv('SYMFONY_DEBUG') !== '0' && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$kernel->loadClassCache();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```
just my 2c

**Comment by jakzal** [comment]
We've already discussed an approach like this and it was rejected in the end: https://github.com/symfony/symfony/issues/11310#issuecomment-74035716

**Comment by max-kovpak** [comment]
@javiereguiluz you right, but maybe we can to think about this issue and make one entry point in a project. For example like in Laravel5 you have .env file where you set APP_ENV, it's really simple. We can remove $environment and $debug args from Kernel __construct and allow our application detect current environment hwithout us.
