### ISSUE TITLE
[Form] Allow "choices" option to be callable for "entity" type field

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#14427]
Use case: we need call custom method of repository for getting choices list. Currently we should inject em/repository into service for doing this. It would be nice add support of callable like:

```php
array(
    'choices' => function (CategoryRepository $categoryRepository) {
        return $categoryRepository->getCategoriesHierarchy();
    }
)
```

NB: I know that we can provide custom "query_builder" option for build it, but it isn't enough in this case. We should do some post-process actions with entities after they are loaded.

**Comment by thunderer** [comment]
If you set callable as field option value, something needs to detect that and run the whole parameter injection mechanism. I think that you'll be much better with injecting and calling that repository yourself than changing whole framework around such simple idea.

**Comment by webmozart** [comment]
Hi @Koc, thank you for taking the time to report this issue! @thunderer is right: You should inject the `CategoryRepository` into your form type and call it in `configureOptions()`. Automatic service injection is not possible for options.

**Comment by Koc** [comment]
But for the `query_builder` option we are injecting repository...

**Comment by Tobion** [comment]
Because query builder is doctrine specific form type. Choices aren't.

**Comment by Koc** [comment]
But `EntityType` extends `ChoiceType`

**Comment by webmozart** [comment]
@Koc What prevents you from injecting the repository into the form type and calling the method directly? We are trying not to add features for functionality that already works well. The code base is already pretty large and hard to maintain.

**Comment by Koc** [comment]
@webmozart did you mean pass repository via form option? If yes - it is inconvenient because I should inject Entity Manager into my services.

**Comment by webmozart** [comment]
No, inject it into the form type and declare the form type in the DIC configuration.

**Comment by Koc** [comment]
Ah, now I understand. I'm so lazy to declare my own form type. But this looks better sollution than now, thank you. I no way to add this feature in the core.

**Comment by webmozart** [comment]
You don't need to declare a new form type for the field. Just inject the service into the form type of your form.

**Comment by Koc** [comment]
@webmozart can you share some code snippet because I'm afraid that not fully understand your suggesion.
