### ISSUE TITLE
[TwigBundle] {% include myVariable %} doesn't use __toString() method of my composite view name

### ISSUE THREAD

**Issue by jessegreathouse** [symfony/symfony#14423]
In my twig template if I include another template like:

    {% include "MyBundle:Default:index-searchform.html.twig" with {form:form} %} 

it works fine.

But if I use a variable for the include path like this:

    {% include searchFormView with {form:form} %}

I get this error:

    Unable to find template "MyBundle:Default:index-searchform.html.twig" in     MyBundle::layout.html.twig at line 53.

searchFormView is a composite view name for AB testing that I expect should be used as a string with __toString()

    class CompositeViewName
    {
    ...
        /**
         * @return string
         */
        public function __toString()
        {
            $myStr  = $this->bundle . ':';
            $myStr .= $this->controller . ':';
            $myStr .= $this->action . '.';

            if (null !== $this->appMode) {
                $myStr .= $this->appMode . '.';
            }

            $myStr .= $this->composeVariation();

            $myStr .= $this->extension;

            return $myStr;
        }
    }

**Comment by jakzal** [comment]
I don't think this is a problem of TwigBundle. It's just like twig works. Not sure if this should be a supported use case, but the [Twig](https://github.com/twigphp/Twig) repository is more suitable to discuss this.

Btw, try casting it to string earlier:

{% include "" ~ searchFormView with {form:form} %}

**Comment by stof** [comment]
passing an object as template name to Twig is indeed not a supported usage
