### ISSUE TITLE
[Debug] ErrorHandler won't trace E_USER_DEPRECATED

### ISSUE THREAD

**Issue by boekkooi** [symfony/symfony#14425]
I'm not sure if this is a bug or just a mistake on my part but when I add:
```PHP
# app/AppKernel.php
// ....
class AppKernel extends Kernel
    public function boot()
    {
        if (true === $this->booted) {
            return;
        }
        parent::boot();

        \Symfony\Component\Debug\ErrorHandler::register(null, false)->traceAt(E_USER_DEPRECATED);
    }
    // ...
```

I would expect that the 'stack' would be filled for all `trigger_error( ..., E_USER_DEPRECATED)` calls and that this would be passed to the ErrorHandler logger but this seems not to happen.

Can someone help me figure out what is going wrong?

P.S. For now I just added ` || $type === E_USER_DEPRECATED` to [ErrorHandler::L400](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Debug/ErrorHandler.php#L400) to solve the problem.

**Comment by nicolas-grekas** [comment]
the trace is never logged when the deprecation is silenced. Did you exclude E_USER_DEPRECATED from the global error_reporting() level?

**Comment by nicolas-grekas** [comment]
Hum, traces are here when screaming is enabled, which is the default in debug mode.
Repeated occurrences of the same error log the trace only once.
Can you see the trace for the very first notice?

**Comment by boekkooi** [comment]
@nicolas-grekas Nope I have this problem even when I force  error_reporting to -1. 

Yeah when E_USER_DEPRECATED is screaming you get the trace but this won't help me when the first scream is from a third party bundle.

But setting `traceAt(E_USER_DEPRECATED)` won't trace anything. It really should at least trace the first one exception but not even that is happening.

**Comment by ninsuo** [comment]
Same here.

- Opened a question on SO without success: http://stackoverflow.com/questions/31125630/how-to-get-a-stacktrace-with-deprecated-method-calls

- error_reporting set to E_ALL

But no stack traces for deprecated calls.

Did somebody find a solution?

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Please test #15647

**Comment by ninsuo** [comment]
Thanks @nicolas-grekas!
