### ISSUE TITLE
Cannot redeclare class Symfony\Component\Finder\Adapter\AbstractFindAdapter

### ISSUE THREAD

**Issue by djave-co** [symfony/symfony#14447]
I've run into this error a couple of times today and I'm absolutely stumped – There isn't much of a Stack trace. I am running an install of Laravel.

    [2015-04-22 15:32:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot redeclare class Symfony\Component\Finder\Adapter\AbstractFindAdapter' in /var/www/web/website-name/htdocs/vendor/symfony/finder/Symfony/Component/Finder/Adapter/AbstractFindAdapter.php:28
    Stack trace:
    #0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
    #1 {main} [] []

Can anyone shed any light on this or let me know how to begin trouble shooting it?

**Comment by nicolas-grekas** [comment]
If that's on 2.7, can you please verify that #14450 fixes the issue?

**Comment by djave-co** [comment]
I'm on 2.5.* from a default Laravel 4.2 install

    symfony/finder                    v2.5.11            Symfony Finder 

https://github.com/laravel/framework/blob/4.2/composer.json

**Comment by jrobeson** [comment]
@djave-co : 2.5 only receives security fixes at this point (and even that will stop soon).

**Comment by nicolas-grekas** [comment]
Meanwhile, you can comment this line https://github.com/symfony/symfony/blob/2.5/src/Symfony/Component/Debug/ErrorHandler.php#L310
