### ISSUE TITLE
When no error handler is registered, empty ESI fragments are cached on error

### ISSUE THREAD

**Issue by Agares** [symfony/symfony#14440]
When using symfony's built in front proxy, when an ESI fragment raises php error/warning/notice, the front proxy caches an empty response.

**Comment by javiereguiluz** [comment]
@Agares are you experiencing this error in recent Symfony versions? If yes, could you please provide more details or even better, a simple Symfony Standard fork with the minimum code needed to produce this error? Thanks.

**Comment by HeahDude** [comment]
ping @Agares :) Any news here?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. We can reopen if @Agares can provide more information.
