### ISSUE TITLE
[Command] Improvements on generating entities

### ISSUE THREAD

**Issue by goncalomcunha** [symfony/symfony#14455]
Hello. When I generate an entity with the command

<code>php app/console doctrine:generate:entity --with-repository</code>

the repository always goes to the "Entity" directory. Since that with the new symfony demo application the repositories are stored in a "Repository" directory to be more organized, would it be possible to change that command so that the generated repository goes to the "Repository" directory? Or maybe an argument so we could change the location, something like "--repository-location=AppBundle\MyCustomDir"?

Another issue I would like to report is, whenever I generate a field with the type "decimal" I have no way to set the "precision" and "scale", it goes (10,0) by default. As well as the "nullable" property for every field types. Is it possibile to be prompted to enter all these options (with a default value) ?

**Comment by xabbuh** [comment]
@goncalomcunha The `doctrine:generate:entity` command is part of the SensioGeneratorBundle and there also is a pull request proposing this change (see sensiolabs/SensioGeneratorBundle#342).

**Comment by goncalomcunha** [comment]
What about the issue about precision/scale for decimals, and nullable for all fields? Where should I submit it? If there is none already

**Comment by xabbuh** [comment]
@goncalomcunha Please report that on the SensioGeneratorBundle repository (if it's not known yet).
