### ISSUE TITLE
[DX][WebProfiler] Remove session attribute

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#14461]
The request panel shows the attributes and flashes that are stored in the session. Quite often I find myself clearing the cache via the cli, in order to just remove a single session attribute of a single user. 

What about adding functions to remove attributes from the User's session directly from the Profiler? That would improve the developer's life a bit.

**Comment by fabpot** [comment]
I'm not a big fan of adding logic to the web profiler. Its main goal is to display data about past requests. Doing that from the CLI would probably be a better idea.

**Comment by Rvanlaak** [comment]
I agree on that, because it looks like changing the past. The goal should be to improve developer experience on this somehow, having to clear the entire cache is a bit odd.

**Comment by javiereguiluz** [comment]
@Rvanlaak since we won't add this feature in the web profiler for the given reasons, where would you like to add this feature? Is it really that common to have to remove one session attribute for one user? Thanks.

**Comment by Rvanlaak** [comment]
Back then it did look like a nice feature, but in the meanwhile the developer use case did not return for me. So, this can be closed for now.
