### ISSUE TITLE
Use array as container parameter in routing.yml

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#14476]
Why can I not use an array as container parameter in routing.yml ?

I need it here: https://github.com/lunetics/LocaleBundle/issues/148

```
resource: "@ExampleBundle/Resources/config/routing.yml"
prefix:   /{_locale}
requirements:
  _locale: %lunetics_locale.allowed_locales%
```

```
The container parameter "lunetics_locale.allowed_locales", used in the route configuration value "%lunetics_locale.allowed_locales%", must be a string or numeric, but it is of type array.
```

**Comment by Tobion** [comment]
The requirement must be a regex. A regex cannot be an array. What you probably want is something like `en|de|fr`.

**Comment by JHGitty** [comment]
Sure but then it is hardcoded two times. I like to only write it once into the config.yml.
