### ISSUE TITLE
[PhpunitBridge] Add a mode to show messages but exit with 0

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#14475]
With the CMF, we want to fix as many deprecated notices as possible. However, as we rely on SonataAdminBundle, there still are some unresolvable deprecated notices. This causes the build to fail.

We can use the `weak` mode and have a passing build, but this also hides the messages of the deprecations. This means new deprecated notices can be introduced without us noticing it. I think there should be another mode that still displays the messages, but exits with 0.

**Comment by Tobion** [comment]
:+1: IMO very important for upgrading as deprecations are often triggered by vendor code that you cannot fix easily but you still want to make your tests pass to actually use the new symfony version.

**Comment by stof** [comment]
I think this is a matter of removing the mode check in https://github.com/symfony/symfony/blob/87f83f7824742385f90f0d7cbb70b92743690052/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L60 to still register the details for non-legacy deprecations in weak mode.

I'm not sure we need a mode showing details without failing and another mode hiding details without failing. We can probably show details in weak mode directly.

what do you think ?

**Comment by craue** [comment]
:+1: for showing deprecation notices in weak mode.

**Comment by nicolas-grekas** [comment]
What about adding an allowed failures matrix line instead?

**Comment by craue** [comment]
@nicolas-grekas, (deprecation) notices are not failures.

**Comment by nicolas-grekas** [comment]
But that being said, if someone wants to create a PR for a weak-verbose mode, I won't object :-) 
I would object against making "weak" verbose thought: we can force filling ci logs. Even with the bridge, the output can be quite long!

**Comment by craue** [comment]
Running the same job twice is not nice, so I'd rather prefer the weak verbose mode.

**Comment by nicolas-grekas** [comment]
See #16789

**Comment by jakzal** [comment]
Can this be closed now?
