### ISSUE TITLE
Conditional loading of form types/type extensions

### ISSUE THREAD

**Issue by sam0delkin** [symfony/symfony#14487]
Hi, i'm working as a collaborator on [FormBundle](https://github.com/itedev/FormBundle). I have some questions, depending conditional loading of configs:
1) For now, we are using this structure for loading plugins configuration:
```php
    protected function loadPluginsConfiguration(FileLoader $loader, array $config, ContainerBuilder $container)
    {
        $serviceIds = $container->findTaggedServiceIds('ite_form.plugin');
        foreach ($serviceIds as $serviceId => $attributes) {
            /** @var $plugin ExtensionInterface */
            $plugin = $container->get($serviceId);
            $enabled = isset($config[$plugin::getName()]) && !empty($config[$plugin::getName()]['enabled']);
            $container->setParameter(sprintf('ite_form.plugin.%s.enabled', $plugin::getName()), $enabled);
            if ($enabled) {
                $plugin->loadConfiguration($loader, $config[$plugin::getName()], $container);
            }
        }
    }
```
so, if user choose to load plugin in config, then plugin configuration will be loaded.
I also found, that default form compiler pass not actually injecting type/type_extension instances into `form.extension` service. It use service id's, and then here is there loading function ([source]( https://github.com/symfony/Form/blob/master/Extension/DependencyInjection/DependencyInjectionExtension.php#L38-L56)):
```php
public function getType($name)
    {
        if (!isset($this->typeServiceIds[$name])) {
            throw new InvalidArgumentException(sprintf('The field type "%s" is not registered with the service container.', $name));
        }

        $type = $this->container->get($this->typeServiceIds[$name]);

        if ($type->getName() !== $name) {
            throw new InvalidArgumentException(
                sprintf('The type name specified for the service "%s" does not match the actual name. Expected "%s", given "%s"',
                    $this->typeServiceIds[$name],
                    $name,
                    $type->getName()
                ));
        }

        return $type;
    }
```
So, the question is: does it actually needed to implement enabling feature of this plugins, such as if no one will call this form type, then this service will not be actually created and the only one where we can have performance decrease is container building?
2) And what about type extensions. There is the same code, so if the type, that extension extends is not used in the project, then service will not be actually created.

So, the main question is performance/memory usage profits. Can someone describe me does it actually needed? Thanks.

**Comment by Tobion** [comment]
Please ask support questions on the mailing list. http://symfony.com/mailing_lists
Thanks
