### ISSUE TITLE
[2.3][SECURITY] cancelCookie in RememberMeService does not take option in to account

### ISSUE THREAD

**Issue by klaascuvelier** [symfony/symfony#14490]
The `cancelCookie` method in the AbstractRememberMeService uses the default values for `secure` and `httpOnly` to clear the cookie.
From a logical standpoint, a cookie is being deleted and it makes sense to not take into account the options, but from a technical standpoint, you are just settings a cookie with a certain value and expiration date so here as well the settings from config.yml should be used.

**Comment by klaascuvelier** [comment]
This also applies to newer version of Symfony, I am not sure how this will be handled.

**Comment by MacDada** [comment]
@klaascuvelier I've made PRs, but neither is merged yet: https://github.com/symfony/symfony/issues/14822
