### ISSUE TITLE
[Forms] Documentation about "compound" is insufficient

### ISSUE THREAD

**Issue by Narretz** [symfony/symfony#14493]
Currently, when your search for something like "Symfony form compound" this is the only thing this is showing up: http://symfony.com/doc/current/reference/forms/types/form.html#compound

For a beginner, this explains basically nothing. Would be nice if there was a more detailed documentation or a section in the cookbook.

**Comment by stof** [comment]
Documentation issues should be reported to https://github.com/symfony/symfony-docs/. The documentation is not maintained by the same team than the code. We have a dedicated team working on it (even though some people are in both teams).

**Comment by Narretz** [comment]
Thanks, good to know!
