### ISSUE TITLE
[HttpFoundation] Make makeDisposition static in ResponseHeaderBag

### ISSUE THREAD

**Issue by WiR3D-kNiGhT** [symfony/symfony#14504]
I have now reached a use case where I have a class that acts a lot like `StreamedResponse` but has the purpose of handling the headers, status codes, and outputting of data before the `Response` object is generated. 

The problem is that `makeDisposition` is not static (in the source there is no reference to any internal variables in `makeDisposition` in the `ResponseHeaderBag`) So I see no reason why it cannot be static. 
It will also then allows us to use `makeDisposition` ahead of the response object creation and pass the header along. instead of setting it after creation.

**Comment by jakzal** [comment]
Could you tell us more about what you're trying to do exactly? Once you start outputting, headers and content are usually known (even if content is being streamed you know the source).

We cannot make the method static as it would be a BC break.

**Comment by WiR3D-kNiGhT** [comment]
In my case i avoided the issue in the end. Since my initial attempt was wrong, unrelated to this. 

And since this is a BC break, you can close the issue. Convenience is less important and since there is no active use case anymore there is no need for this. 

I did make a factory that was creating response objects for me but needed to have some headers defined/determined before the response object was actually created. 

A refactor had me remove all that logic, which to be honest was kind of nasty anyway.
