### ISSUE TITLE
GLOB_BRACE error on SunOS

### ISSUE THREAD

**Issue by webbird** [symfony/symfony#14502]
As GLOB_BRACE is not available on Solaris (see https://php.net/manual/en/function.glob.php), one will get an error message

Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in PATH/Symfony/Component/Finder/Finder.php line 664

**Comment by dosten** [comment]
Hey @webbird can you check if the changes in #14503 fix your problem?

**Comment by dosten** [comment]
btw, you will need to do this:
```php
$finder->files()->in([
    'My/First/Directory',
    'My/Second/Directory',
    'My/Third/Directory',
]);
```
instead of this:
```php
$finder->files()->in('My/{First,Second,Third}/Directory');
```

**Comment by webbird** [comment]
Works for me. I changed function in() like this instead (works too):

            } elseif ($glob = glob($dir, ( defined('GLOB_BRACE') ? GLOB_BRACE | GLOB_ONLYDIR : GLOB_ONLYDIR ) )) {

**Comment by dosten** [comment]
Great, my change keep consistency with other places with the same problem. Ex: the `JSON_PRETTY_PRINT` constant, but your solution is perfectly valid.
