### ISSUE TITLE
Extending the datetime validator

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14510]
Would it be ok for the datetime validator to be extended with the following features (similar to Respect\Validation) ?

* Provide a custom format https://github.com/Respect/Validation/blob/master/docs/Date.md
* Provide min and max https://github.com/Respect/Validation/blob/master/docs/Min.md
* Provide an interval (between) https://github.com/Respect/Validation/blob/master/docs/Between.md

Possibly some of this can already be done with the LessThan and Range constraint ??

**Comment by dosten** [comment]
The second and third item can be done using the RangeValidator. See https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Validator/Constraints/RangeValidator.php

**Comment by dosten** [comment]
See #14521 for the first item.

**Comment by flip111** [comment]
Thanks

**Comment by SoboLAN** [comment]
First point is implemented in #14538
