### ISSUE TITLE
[Form] How to render a form as link or obtain the request parameters necessary to do so?

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#14514]
Assume I’ve got a `FormType` for some kind of database lookup. You can enter a query string, some fancy filter conditions and select the ordering of results you’d prefer.

Then, a straightforward controller uses this `FormType` to read the input from the `GET` `Request`, maybe by binding it into some object, and perform the database query. The view will then render a simple table with the results.

Now, in this view I would also like to output some links that lead to variations of the search query. For example, the table headings should be links that re-order the results; or below the table, there could be a suggestion like „Search for [link]some term[/link] instead“.

Of course, it would be great if those links could point to the same controller, the one that uses the `FormType` to read from the `Request`.

So, is there a simple way to obtain from a `FormType` (or `FormView`? or anything else?) all the parameters I need to add to a `Request` (that is, pass to the `UrlGenerator`) to make it look like one that would result when actually submitting the form?

My concern is that the form "knows" the mapping between the structure of the data array (or object) and the `Request` parameters. The request parameters need not be structured/named the same way as the internal data representation. 

Ideally, I would not need to know the exact details of this mapping in the view but could just provide an alternative data array or object when building the link.

Suggestions?

**Comment by mpdude** [comment]
@webmozart maybe you can help?

**Comment by HeahDude** [comment]
Hi @mpdude, I would advise you what I'm actually using in one of my projects, as it may fit your need.

Your `FormType` class instead of mapping "fields", could map a lot of sub form types, with different submit buttons and defining some special css class (by using the `attr` option) allows a lot of tweak on client side.

Then some few lines of jQuery should do the trick : prevent default submission, serialize sub forms (preparing them for request data thanks to `$('#sub_form_id).serialize()`) or any part of the main form and post it to the write route (with maybe some help form twig for generating url or FOSJsRoutingBundle).

**Comment by backbone87** [comment]
This is not quite as easy and at least with the current form impl not so good performance wise.

The best bet imho is to provide an external service for this:
```php
$currentFilter = new Filter;
$filterForm = $this->formFactory->create(FilterType::class, $currentFilter);
$filterForm->handle($request);

$hintFilter = clone $currentFilter;
$hintFilter->setConditionA(true);
$qs = $this->queryStringFromFormBuilderService->buildQueryString(FilterType::class, $hintFilter);
```

the `queryStringFromFormBuilderService` must create a new form of type FilterType with $hintFilter as data, then create the form view and loop over the leafs in the view tree and build the QS from key/value vars.

**Comment by webmozart** [comment]
@mpdude I think it should be easy enough to write a `form_url()` function for Twig that takes the `FormView` and loops over the fields and their values. Each `FormView` stores two attributes that you will need: `$form->vars['full_name']` stores the HTML name and `$form->vars['value']` stores the string value. With those, you can build the key-value pairs of your query string.

Hope this helps. :)

**Comment by mpdude** [comment]
For the record, there's a snippet that does this for non-empty fields. 

```php
        $params = [];
        
        foreach (new \IteratorIterator($view) as $item) {
            if ($item->vars['value']) {
                $params[$item->vars['full_name']] = $item->vars['value'];
            }
        }
        
        return $params;
```

@webmozart Do you consider the use case a legitimate one and would you support a PR to add such a helper function in Symfony?

**Comment by backbone87** [comment]
I think your example does not work with more deeply nested forms. You should use a `RecursiveIterator` with mode "leaf" and additionally filter for non-compound forms.
