### ISSUE TITLE
[Validator] Deprecate Date and Time constraints

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#14521]
What do you think about deprecating the `Date` and `Time` constraints in favor of add a `format` option to the `DateTime` constraint.
We can do that using the `DateTime::createFromFormat()` and `DateTime::getLastErrors()` to check if a date is valid based on a specific format.
What do you think? Can be this discussed?

**Comment by aitboudad** [comment]
I think it would be a good idea to have less constraints.

**Comment by flip111** [comment]
:+1:

**Comment by SoboLAN** [comment]
I disagree. I think it's better the way it is now because it's more explicit and therefore more intuitive.

**Comment by Tobion** [comment]
Related to #12389

**Comment by dosten** [comment]
@SoboLAN but it's less customizable. If i need to validate a date in this format: "d-m-Y" the constraint doesn't work.

**Comment by flip111** [comment]
@SoboLAN following the php date formatting options should also be intuitive for people who are new to symfony (but have prior php knowledge)

**Comment by WouterJ** [comment]
:+1:

**Comment by giovkanata** [comment]
:+1:

**Comment by dosten** [comment]
Check #14531 for a implementation of this.

**Comment by SoboLAN** [comment]
@dosten Ooooh damn. I also did an implementation with this: #14538 . Didn't know someone was already working on it. What is usually done in these cases ?

**Comment by webmozart** [comment]
While I like adding a "format" option, I don't think we should deprecate the Date and Time constraints. They are used frequently enough to warrant them (see discussion in #12389).

**Comment by dosten** [comment]
@webmozart I am okay with not deprecate the Date and Time constraints but i want to discuss about this.
@SoboLAN I think that the second PR is closed as duplicated, or if the implementación of the 2nd PR is better we close the first.
I will review your PR.

**Comment by gimler** [comment]
@SoboLAN & @doston your code looks simliar also my own implementation.

Can you add?
* Can you add errors and warnings as parameters to the violation.
* constraint `strict` option to allow ignoring the warnings

**Comment by dosten** [comment]
@gimler I don't know if makes sense add the errores and warnings as parameters and if this is a BC break.
Actually the warnings are about invalid date and time. Ex: 2015-02-29 and 14:65:00 which are two of three violations triggered by the constraint,  i'm :-1:  but this can be discussed in another PR because is out of the scope of this PR.

**Comment by dosten** [comment]
@fabpot I'm not sure if we should close this issue because talks about deprecating the `Date` and `Time` constraints in favor of the `DateTime` constraint + `format` option.

IMO the pros are:

- More powerful
- Less constraints to maintain
- Reduces the learning curve of the Validator component (I do not need to remember if I need the `Date`, `Time` or `DateTime` constraints)
- Don't require to learn any new DSL like #12389
- The `DateTime` constraint don't use any regex, so, maybe a performance gain (I need to benchmark this)

And the cons:

- A `DateTime` constraint configured to validate a time (ex. H:i:s) by default will add a violation with the message "This value is not a valid datetime." which is a bit odd.

**Comment by dosten** [comment]
Well, actually there is a veeeery small performance gain of 0,20% so the item about performance can be omitted.

**Comment by xabbuh** [comment]
If we do not deprecate the `Date` and `Time` constraint, we should imo add the `format` option to the `Date` constraint too.

**Comment by dosten** [comment]
@xabbuh but how this format will work? like the `DateTime` constraint? so, if I do:

```php
$validator->validate('23:09:13', new Date(['format' => 'H:i:s']));
```

this will work? so, we will have two constraint that works exactly the same but with a different name?

**Comment by webmozart** [comment]
@dosten The issue you reference (#12389) was actually *not* implemented and closed because we concluded that it's better to have several specialized constraints that are easy and intuitive to use, even if they partially overlap in functionality.

On the other hand, I think that dates/times should mostly be stored inside value objects anyway, which makes the two constraints a bit useless.

**Comment by dosten** [comment]
@webmozart Well, I don't find easy and intuitive the proposal of #12389.

Can you explain a bit more your point about value objects?

**Comment by webmozart** [comment]
I was talking about `DateTimeImmutable` or similar classes.

I reread this thread and related threads now. I agree with you that using the `DateTime` constraint with the `format` option is easy enough to use and more flexible than `Date` or `Time`. For me it's fine to go ahead and deprecate them.

**Comment by webmozart** [comment]
One more thing: What do you think about extracting the `format` option of `DateTime` into a new constraint `FormattedDate` which accepts string dates/times only? Then we can deprecate `DateTime` also.

I think it's a bit weird that `DateTime` accepts both strings and `DateTime` instances, which kind of contradicts the purpose of validation (asserting that a specific constraint is met). Also, you can't import the constraint and the class in the same file without having to alias either of them:

~~~php
use DateTime;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @DateTime
 */
private $someStringDate;

public function setDate(DateTime $dateTime)
{
    // ...
}
~~~

A new, specialized constraint with another name would solve these problems.

ping @javiereguiluz @xabbuh @weaverryan

**Comment by javiereguiluz** [comment]
I agree with @xabbuh's previous comment. I'd like to have a `format` option for each date constraint and use it like this:

```php
use Symfony\Component\Validator\Constraints as Assert;

class User
{
    /**
     * @Assert\Date(format = 'Ymd')
     */
     protected $dateOfBirth;

    /**
     * @Assert\Time(format = 'H:i')
     */
     protected $preferredNotificationTime;

    /**
     * @Assert\DateTime(format = 'YmdHis')
     */
     protected $signedUpAt;
}
```

**Comment by webmozart** [comment]
@javiereguiluz In that case, all three constraints have the 100% same implementation. Nothing would prevent you from passing "Ymd" to `Time`.

**Comment by javiereguiluz** [comment]
@webmozart I don't mind. We also have IbanValidator, IpValidator, IsbnValidator and IssnValidator which are (more or less) a specialized RegexValidator.

**Comment by flip111** [comment]
make DateTime Validator parent class of Date and Time Validator classes

**Comment by dosten** [comment]
@webmozart I'm :+1: on deprecating also the `DateTime` constraint in favor of a constraint that accept strings only, but I don't like too much the `FormattedDate` name :/

@javiereguiluz I find a bit confusing to have three constraints that can do the same thing, think about a new Symfony user. The main idea of this issue (IMO) is simplification.
Also, I think that your example is incorrect, any of these are a specialized regex constraint, AFAIK you can't validate a IP using a `IsbnValidator` but following your idea you can validate a date using the `Time` constraint which is a bit odd IMO.

@flip111 The implementation of the idea of @javiereguiluz is not a problem, but we should decide if this is a good idea.

**Comment by HeahDude** [comment]
I feel more comfortable using:
```php
use DateTime;
use Symfony\Component\Validator\Constraints as Assert;

class User
{
   // ...

    /**
     * @var DateTime
     * @Assert\DateTime(format = 'Y/m/d')
     */
     protected $dateOfBirth;

    /**
     * @var DateTime
     * @Assert\DateTime(format = 'H:i')
     */
     protected $preferredNotificationTime;

    /**
     * @var DateTime
     * @Assert\DateTime(format = 'Y-m-d H:i:s')
     */
     protected $signedUpAt;
}
```

**Comment by webmozart** [comment]
@javiereguiluz That comparison doesn't work. The constraints you mention are specialized. They differ from each other (even if only slightly). Here we are talking about three constraints with a 100% equivalent implementation. I agree with @dosten that this is unexpected and confusing. From my experience, users would expect different constraints to validate different things.

@HeahDude You put `@var DateTime` on your fields and validate that they are *strings* with a certain format. Something must be wrong here. :)

@dosten We can also go with `FormattedDateTime`, which is a bit longer. One advantage of `FormattedDate` is that it is in line with PHP's `date()` function (which also accepts time formats only).

The prefix "Formatted" makes sense to me, since we choose the (string) format in the "format" option. We could even make that option the default option:

~~~php
class Registration
{
    /**
     * @FormattedDate('Y/m/d')
     */
    private $dateOfBirth;

    /**
     * @FormattedDate('H:i')
     */
    private $startOfDay:
}
~~~

**Comment by javiereguiluz** [comment]
I didn't know that the three constraints would be exactly the same. Thanks for the explanations. I fully agree with you and we'd only need one constraint.

However, from the DX (developer experience) point of view, I can't understand why a "simple" option like the date format forces me to use a new constraint. This would be to me like having to use `Ip6Validator` instead of `IpValidator` if I want to validate IP6 addresses.

I don't like either the `Date` suffix because this can validate date, time and datetime. In my opinion, `DateTime` should be the name of this constraint.

**Comment by HeahDude** [comment]
@webmozart yes, definitely wrong :) I was trying to explicit the fact that whatever the string format is, I commonly use `\DateTime` objects to deal with them. So I tend to agree with @javiereguiluz that it feel more natural to use `DataTime` as constraint name.

But the fact that I got confused in my own example makes me realise that it may be far more understandable to use `FormattedDateTime`. From my POV, you made a really good point here.

**Comment by dosten** [comment]
So, all of us agree to deprecate the `Date` and `Time` constraints, great!
I like more the `DateTime` name but @webmozart have some interesting points, any feedback? @fabpot  @xabbuh @stof

**Comment by WouterJ** [comment]
I'm on @webmozart's side here, `@DateTime` would make me think I'm validating a DateTime object, but the reality is that a string is validated. On the other side, `@FormattedDate` sounds a bit strange.

What about keeping the `@Date` constraint? This is easy to understand, consistent with PHP's `date()` function, a nice short name and it doesn't cause confusion with the DateTime object.

**Comment by dosten** [comment]
@WouterJ LGTM

**Comment by javiereguiluz** [comment]
@WouterJ so if you want to validate a `time`, you must use a `@Date` constraint? And the same for a `DateTime`? To me DateTime looks "inclusive" (give me a date, a time or a datetime) but Date looks exclusive (this is only for dates, no times or datetimes allowed).

**Comment by WouterJ** [comment]
@javiereguiluz I agree with you if we purely look at it from a language point of view. However, Symfony is a PHP framework and if you want to display a time with PHP, you would do `date('H:i')`.

**Comment by webmozart** [comment]
@WouterJ I think `@Date` is a good alternative to `@FormattedDate` from a PHP developer's point of view. @javiereguiluz is right that the language is not the right one. But `date()` is common enough for this to be easily understandable, I think. We can blame PHP for that. :)

**Comment by xabbuh** [comment]
I am closing this old issue as it seems we don't find a consensus here.
