### ISSUE TITLE
Symfony2 form type entity add extra option

### ISSUE THREAD

**Issue by aguzmans** [symfony/symfony#14528]
I have the following Symfony form field, it's a drop down that loads from an entity:

->add('measureunit', 'entity', array('label' => 'Measure Unit',
            'class' => 'TeamERPBaseBundle:MeasureUnit',
            'expanded' => false, 'placeholder' => '',
            'multiple' => false, 'property' => 'abreviation'
        ))

As you can see I have added 'placeholder' => '' and everything works fine. Now, what I want is to have an extra option at the end of the list to add a let say 'New measure unit'. In other words the dropdown should display all the content of my entity, the empty value and another extra option called 'New measure unit' or what ever I want to call it. Is it possible? 
I have been looking around to be able to do something like that, and I have not managed.

**Comment by aguzmans** [comment]
My bad, apparently this does it, thank you: http://stackoverflow.com/questions/30013719/symfony2-form-type-entity-add-extra-option/30017673#30017673

**Comment by dosten** [comment]
Can you close this?
