### ISSUE TITLE
HHVM nightly is no longer supported on Ubuntu Precise

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#14532]
HHVM nightly is no longer supported on Ubuntu Precise. See travis-ci/travis-ci#3788 and facebook/hhvm#5220. We should remove `hhvm-nightly` from `.travis.yml`?

**Comment by stof** [comment]
I suggest running the testsuite on hhvm stable instead. We don't really need to rely on hhvm-nightly anymore here. hhvm would be fine too
