### ISSUE TITLE
Workaround for fixed SaveSessionListener bug no longer needed?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14535]
I'm not 100% sure about this one if it is an actual workaround for a bug or just a reference to a discussion.

https://github.com/symfony/symfony/blob/d0d7ae24e4d8ec27ff6992fd51d7d090424942be/src/Symfony/Component/HttpKernel/EventListener/SaveSessionListener.php#L31-L35

https://github.com/symfony/symfony/blob/7c026bb33e8ca96b285402f7fe7ae27a04a74ea9/src/Symfony/Component/HttpFoundation/Session/Storage/SessionStorageInterface.php#L91-L97

https://bugs.php.net/bug.php?id=61470

**Comment by Tobion** [comment]
Still relavant because of custom save handlers. PHP just introduced another inconsistency with the internal "files" save handler.
