### ISSUE TITLE
Workaround for fixed DebugClassLoaderTest bug no longer needed?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14537]
https://github.com/symfony/symfony/blob/42e3ecbe783ea10b73dd8868583698d4d401d083/src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php#L85

https://bugs.php.net/bug.php?id=65322

**Comment by iltar** [comment]
As long as PHP Version:	5.4.* is supported it's required. I think this can be removed for Symfony 3 but I'm not sure if 5.5.9+ is affected by this bug.

**Comment by nicolas-grekas** [comment]
I'm closing because error stacking is a feature that is not deprecated. It is used to workaround this bug, but keeping it as a feature is still relevant, until proven not :)
