### ISSUE TITLE
The options parameter in the createForm function doesnt allow custom field

### ISSUE THREAD

**Issue by xDaizu** [symfony/symfony#14553]
The options parameter in the createForm function doesnt allow custom field, like the documentation suggest. I don't know if this is a problem of the documentation being obsolete or a failure in the code, but the documentation, in the  ["Data transformers" section](http://symfony.com/doc/current/cookbook/form/data_transformers.html) suggests to do:

    $taskForm = $this->createForm(new TaskType(), $task, array(
        'em' => $this->getDoctrine()->getManager(),
    ));

and so I did, with the following code:

    $form = $this->createForm(new ActivityType(array('sessions' => $activityToEditSessionsTypes)), $activity, array(
            'em' => $em,
            'action' => $this->getRequest()->getUri(),
            'method' => 'POST'
        ));

and the option resolver throws the following error:

    *The option "em" does not exist. Known options are: "action", "allow_extra_fields", "attr"...yadda-yadda-yadda*

I know how to implement a workaround (actually, further down that very page you can find how to implement it as a services) but I think that when an example in the documentation doesn't work anymore, something somewhere should be changed.

Thanks for your time.

**Comment by phansys** [comment]
@xDaizu, regardless if it is configured as service or not, if you want to pass custom options to your form type, you must decelare them in ```TaskType::setDefaultOptions()``` (or ```TaskType::configureOptions()``` if you are using Symfony 2.7 or higher).

See [Adding the extension Business Logic](https://symfony.com/doc/2.7/cookbook/form/create_form_type_extension.html#adding-the-extension-business-logic) and [Defining the Field Type](https://symfony.com/doc/2.7/cookbook/form/create_custom_field_type.html#defining-the-field-type) for examples.

**Comment by Tobion** [comment]
Or set the appropriate `parent` for your form type to it "inherits" those options. If it still doesn't work, feel free to reopen with your concrete form code.
