### ISSUE TITLE
Problems with some ACL tables and utf8mb4 encoding

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#14560]
I'm in the process of converting our database from 'utf8' to 'utf8mb4' to support 4-byte unicode chars (emojis for example) and running the conversion queries a problem shows up with the length of some unique keys in the ACL schema which I can't control myself (well, of course I can but then in every migration I make afterwards these will come up and try to revert any ALTER TABLE I make to these tables)

```
mysql> ALTER TABLE acl_security_identities CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.
```

By default InnoDB can have a maximum index size of 767 bytes. With utf8 encoding, which uses at most 3 bytes per char, you get 255 characters. But in utf8mb4 you now can only index string columns with at most 191 characters. This InnoDB setting can be changed but you have to change all the database and table file formats (see http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/).

So my question would be if the default string lengths of 200 chars that the `acl_security_identities` and `acl_classes` unique keys have could be tuned to 191 chars, it's only 9 chars less, I guess it would not be a big problem.

Thanks!

**Comment by flip111** [comment]
AFAIK you can set the collation per column. For keys the simplest (fastest) collation is ideal.

**Comment by acasademont** [comment]
Yep, but if using doctrine that must be set at the mapping level and I can't access the mapping either. If not, every migration that I generate from that point onwards would try to reverse the changes. Besides, It's easier to only have one collation for the whole DB!

**Comment by flip111** [comment]
Perhaps you can elaborate a little bit on the "i can't access the mapping either" part with some code examples or references...

**Comment by MisatoTremor** [comment]
I think he speaks about that both field lengths ([``acl_classes.class_type``](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/Schema.php#L70) and [``acl_security_identities.identifier``](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/Schema.php#L148)) are hard coded in the security-acl components schema.

Since the Symfony book now advices to use utf8mb4 the ACL schema should be updated to reflect this _or_ the doc should be updated to advise changing the InnoDB settings as detailed in the  article linked by @acasademont.

**Comment by acasademont** [comment]
oops sorry i forgout to reply @flip111. Yes indeed it's what @MisatoTremor is saying, the mappings of the acl schema are in the symfony repo can't change them. Of course i can change the actual generated migration file by hand (that's what i did actually) but from now on i'll have to be careful in every "migration diff" i generate because doctrine will try to revert my manual changes.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.

**Comment by acasademont** [comment]
ok thanks!
