### ISSUE TITLE
'empty_data = true' to set default value of checkbox gives error.  

### ISSUE THREAD

**Issue by apfz** [symfony/symfony#14579]
I wanted to set the default value of a checkbox to checked in the following way:
<code><pre>$form->add('public', 'checkbox', array (
    'label' => 'Registration is public',
    'required' => false,
     'empty_data'=>true 
)); 
</pre></code>

but when i uncheck the box, it gives me an error: "This value is not valid."

Is this a bug?

**Comment by jakzal** [comment]
see #7139

**Comment by webmozart** [comment]
Hi @apfz, thank you for taking the time to report this issue! Could you check whether #15054 fixes your problem?

**Comment by HeahDude** [comment]
Hi @apfz, setting `empty_value` option will provide data `true` while the submition of the form if none is submitted.
If you want to set a default `true` value to your checkbox so it can appear checked in your view you should use the option `data` instead.

This issue may be close.

Status: reviewed

**Comment by apfz** [comment]
@HeahDude, would `data`  not always set the value to true, and always override the value of the property (public in this case)?

**Comment by HeahDude** [comment]
@apfz, no `data` is just about initializing, not submitting, you can still use the form as you intend (set data).

`empty_value` comes in place if you did not submitted data (in this case uncheck the checkbox). So you may not want to do this I think.

**Comment by Tobion** [comment]
@HeahDude You mixed up `empty_value`  (placeholder) and `empty_data` but otherwise it's correct.
So closing.

**Comment by HeahDude** [comment]
@Tobion, you're right, it was just a typo

**Comment by lil-works** [comment]
@apfz Exactly what happen for me

**Comment by csetoihid** [comment]
Need to set :
multiple: false 
expanded: false,
required: false
It works for me .
`type_options: { required: false, multiple: false} `

More details: https://symfony.com/doc/current/reference/forms/types/choice.html#empty-data
