### ISSUE TITLE
Cleanup symfony namespace on packagist

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#14574]
Since https://github.com/composer/packagist/issues/163#issuecomment-99673878 the symfony namespace should be cleaned up of repositories that do not belong to symfony. So maintainers of these repos do not have access to add more repos in the symfony namespace.

This is the list of false symfony namespaced repos:

- https://packagist.org/packages/symfony/framework-standard-edition-2
- https://packagist.org/packages/symfony/framework-standard-edition-copy
- https://packagist.org/packages/symfony/framework-standard-edition-gonzaga8200
- https://packagist.org/packages/symfony/vanguard-edition
- https://packagist.org/packages/symfony/sis-ejercicio-imagina
- https://packagist.org/packages/symfony/bootcamp-bundle
- https://packagist.org/packages/symfony/ivan-murillo
- https://packagist.org/packages/symfony/logreader-bundle
- https://packagist.org/packages/symfony/micro-services
- https://packagist.org/packages/symfony/proyecto-imagina-formacion

@fabpot @Seldaek

**Comment by Seldaek** [comment]
Thanks for listing them. I wiped those that were obvious tests, disused course material and random abandoned things. I am left with these two:

https://packagist.org/packages/symfony/logreader-bundle (seems abandoned but legit project at least)
https://packagist.org/packages/symfony/bootcamp-bundle (actually used)

I'll ping the two authors to see if they can rename and mark abandoned. The bootcamp bundle we might need to keep around for a bit as it seems to be in use, but after a while it can go and then it's all clear.

**Comment by iltar** [comment]
https://packagist.org/packages/symfony/symfony1

I'm actually still maintaining this, accepting and fixing pull requests that either fix bugs or make it forward compatible to newer PHP versions, which also include some minor dependency changes. It's a fork of the original symfony1 repository. However, without thinking I uploaded it as symfony/symfony1 back then as it was used internally under our own company github account with a private packagist.

There are quite a few people using this and every month I help out a few people on `#symfony` setting this up so they can either migrate or fix certain issues they've had. If necessary, I can change the package name as we are not officially the Symfony1 vendor.

_I personally would like to keep maintaining this and accept fixes without changing the vendor name as that would cause a lot of problems for a lot of people, if this is okay with you guys of course!_

**Comment by Tobion** [comment]
If it is kept, then there should not be 4 maintainers of symfony/symfony1 in packagist that all get access to symfony namespace.

**Comment by Rvanlaak** [comment]
Thanks for the cleanup. Found myself relying on number of downloads quite often. What about verifying namespaces by adding Github's organization users page? https://github.com/composer/packagist/issues/163#issuecomment-100143313

**Comment by dunglas** [comment]
@iltar for my information, what's pros and cons compared with https://github.com/LExpress/symfony1 ?

**Comment by iltar** [comment]
@dunglas from what I can tell, the main difference is that the fork you linked is actually being build upon, features such as a custom DI container. The version I maintain is nothing but bug/notice fixes, which limits the chance of introducing new bugs or breaking something by accident.

It's meant to provide compatibility with newer php versions and fix critical bugs, not to develop new websites with or improve older websites. If you want a DIC for example, I recommend doing it in another way, as done in: https://github.com/hostnet/hnDependencyInjectionPlugin. Last year I've used this to migrate from sf1 to sf2. A few weeks ago we've cleared out the last propel stuff and removed the dependency on symfony/symfony1.

**Comment by dunglas** [comment]
Thanks for explanations.

**Comment by fabpot** [comment]
Can we close this one now?

**Comment by Tobion** [comment]
No, there are still 2 projects not from symfony.

**Comment by Seldaek** [comment]
Only one is left of the two I listed earlier, I didn't get an email answer from them so I opened https://github.com/netgusto/Symfony-BootcampBundle/issues/1 - if nothing shows up in a while and the dl count in last 30days remains at zero I guess we can just delete it.

**Comment by Tobion** [comment]
So can we remove the bootcamp bundle? Still no reaction.

**Comment by Seldaek** [comment]
Well yeah what disturbs me a bit is that it is used somehow as per https://packagist.org/packages/symfony/bootcamp-bundle/stats so I'd rather not break someone's day if possible to avoid it.

**Comment by xabbuh** [comment]
The BootcampBundle was renamed too.

**Comment by Tobion** [comment]
Not really. The old one was just marked as deprecated. But as long as it exist, the owner still has access to the symfony namespace I assume.

**Comment by Seldaek** [comment]
I transfered the package to myself so that they don't have access anymore. I'll try and delete it eventually but as long as it has downloads it's nicer to keep it so people might get the abandoned warning.

**Comment by Tobion** [comment]
:+1:
