### ISSUE TITLE
[HttpFoundation] setUrl method for Request...

### ISSUE THREAD

**Issue by Athlon1600** [symfony/symfony#14575]
Is there a reason why Request class doesn't have a setUrl method? I really wish to do this:

```php
$request = Request::createFromGlobals();
$request->setUrl("http://www.yahoo.com");
```

but I can't without creating another instance of Request and copying all of its data minus the URL into the new.

**Comment by dupuchba** [comment]
I don't see the use case...

**Comment by Athlon1600** [comment]
I want to replicate an incoming Request to my server, and send it exactly as it is to another server like a Proxy.
```
POST /proxy.php?url=yahoo.com/comment.php
id=451,comment=gdfgdfgdf87g
```

doing this:

```php
$request = Request::createFromGlobals();
$request->setUrl($_GET['url']);
```

would be so easy, otherwise I would have to write my own Request wrapper even thought I'm already reusing so many of Symfony's components.

**Comment by dupuchba** [comment]
there is a method for that :-)
Look at the `duplicate` method of the `Request` class

**Comment by Athlon1600** [comment]
Duplicate doesn't work for that, I've already tried. Show me how I could accomplish that above using duplicate

**Comment by jakzal** [comment]
@Athlon1600 I'm not sure how do you plan to send an http foundation request to another server, as this is not the use case it accomplishes. 

The reason why there's no `setUrl()` method is that the URI is calculated from server variables. We have enough issues with the Request class being stateful and I vote :-1: for adding `setUrl()`.

You can indeed use `duplicate()` method to alter the URL:

`$request->duplicate(null, null, null, null, null, array('REQUEST_URI' => '/', 'HTTP_HOST' => 'http://www.yahoo.com'))`

**Comment by Athlon1600** [comment]
that works. You can close this now

**Comment by amiriskander** [comment]
@Athlon1600 How could you resend the duplicate request again after changing the URL?
