### ISSUE TITLE
[Security] Why is the username base64–encoded in TokenBasedRememberMeServices?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#14577]
Why is the username base64–encoded in https://github.com/symfony/Security/blob/master/Http/RememberMe/TokenBasedRememberMeServices.php#L106 ?

It is actually double encoded because all the cookie's data get encoded after all.

I couldn't find the explanation in git history and the reason isn't obvious (at least to me). Tests say that it is required but they don't say why.

A comment in the code (and/or the TestCase) could be useful – I can make a PR after I understand what's that for.

**Comment by GromNaN** [comment]
The username could contain the cookie delimiter (`:`). That would cause errors when decoding the cookie. 
https://github.com/symfony/Security/blob/master/Http/RememberMe/AbstractRememberMeServices.php#L262

**Comment by MacDada** [comment]
@GromNaN Thx, if that's correct, I'm gonna create a PR with a php comment so that nobody else has to ask and wonder ;-)

-------

BTW, why is it in the extending class(es) instead of putting it in the `AbstractRememberMeServices.php`?

Why risk that some implementation would "forget" about that?

-------

Maybe another PR with one of these:

1. Move the extra encoding to the abstract class (BC, so probably not).
2. Throw `InvalidArgumentException` (?) in `encodeCookie()` when any of `$cookieParts` contains `self::COOKIE_DELIMITER` (should not be considered BC?)
3. At least add info in `encodeCookie()`'s phpdoc that it is required not to pass a cookie part containing `self::COOKIE_DELIMITER`

**Comment by pschultz** [comment]
I agree that `AbstractRememberMeServices::encodeCookie` should do the Right Thing, no matter the input. There is actually a [possible bug in `PersistentTokenBasedRememberMeServices`](https://github.com/symfony/Security/blob/ad78f5a6/Http/RememberMe/PersistentTokenBasedRememberMeServices.php#L101-107), because the `$series` isn't encoded. And since the token provider can be replaced there is no guarantee the series doesn't contain a colon.

**Comment by MacDada** [comment]
@pschultz As for getting `$series` from the token, I've already removed that: https://github.com/symfony/symfony/pull/14581

**Comment by MacDada** [comment]
Alrighty, #14670 is on its way to "confirm" current behaviour, which actually I don't really like.

PHPDocs for `generateCookieValue()` and `generateCookieHash()` claim that they might throw `\RuntimeException` and they never do. It's like that from the beginning: https://github.com/symfony/symfony/commit/57ae50e8942f1a3ee9431c320b404fc1b016b87c#diff-21f867f85d132b1cd223867fe8ee66a4R126

My guess would be that they used to throw (not catch) exceptions, because `AbstractRememberMeServices` would, but it doesn't.

How about it does? I'm gonna remove the phpdocs (as this exception "shouldn't happen") but also throw `\InvalidArgumentException` in `encodeCookie()` when any of the `$cookieParts` contains `COOKIE_DELIMITER`.

This might be considered BC but IMHO it shouldn't – if any of the implementations passed `COOKIE_DELIMITER` in the parts, `decodeCookie()` would be broken.
