### ISSUE TITLE
[Security][Translation] “credentials” doesn't translate to “droits” in french

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#14584]
In files **security.fr.xlf**, “credentials” is translated to “droits” in sentences

- Authentication credentials could not be found.
- Invalid credentials.
- Credentials have expired.

but it translates to “identifiants”, so translations should be

- *Les identifiants d'authentification n'ont pas pu être trouvés.*
- *Identifiants invalides.*
- *Les identifiants ont expiré.* (“*expiré*” doesn't need a “s”.)

**Comment by dupuchba** [comment]
:+1:
