### ISSUE TITLE
[console] Required argument check passes with empty value

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#14594]
I've configured command like this (`configure` method):

```php
$this
	->setName('event:run')
	->setDescription('Executes an event')
	->addArgument(
		'event-name',
		InputArgument::REQUIRED,
		'The event name (e.g. "adm:OnDoSomething").'
	);
```

Then I'm executing it as `program event:run ""` in Bash and input validation passes (in build-in `validate` method) resulting in empty `event-name` argument value in the `execute` method.

I thought, that if argument is marked as required, then validation should fail:

* if argument not passed
* if argument is passed with an empty value

**Comment by aik099** [comment]
I think that in https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Input/Input.php#L76 line we should be doing `array_filter($this->arguments)` to remove all empty argument values.

Unfortunately this will be a BC break for people doing manual input validation to account for empty required argument values.

**Comment by Tobion** [comment]
Required just means that you expect an argument. And you got an argument. It's not about validation.

**Comment by Tobion** [comment]
Closing as changing it is a BC break and doesn't make sense. What if somebody expects an argument, but it might be empty? This wouldn't be possible anymore with your suggestion.

**Comment by aik099** [comment]
Exactly. But, what if I have an option configured with VALUE_REQUIRED. Then missing value would create validation error?
