### ISSUE TITLE
[Form][2.6][OptionsResolver] Weird behaviour with collection field not being transformed

### ISSUE THREAD

**Issue by wideawake** [symfony/symfony#14614]
Hi guys,

I'm experiencing a probably bug with Symfony 2.6.6.

I'm using configureOptions instead of setDefaultOptions in my Form Class.
I have a field of type collection, here is the code:
```
$builder
     ->add('titles', 'collection', array(
                        'allow_add' =>  true,
                        'allow_delete'  =>  true,
                        'type'      =>  new UserTitleType(),
                    ))
```

The UserTitleType class:

```
class UserTitleType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
            ->add('title')
            ->add('description')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'NS\AppBundle\Entity\UserTitle',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'usertitle';
    }
}
```

With such configuration the error I get when I submit a form (json with FOSRest) is:

*Catchable Fatal Error: Argument 1 passed to NS\UserBundle\Entity\User::addTitle() must be an instance of NS\AppBundle\Entity\UserTitle, array given*

By changing
```
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'NS\AppBundle\Entity\UserTitle',
        ));
    }
```
with
```
public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'NS\AppBundle\Entity\UserTitle'
        ));
    }
```

The message I get is:
*A new entity was found through the relationship 'NS\UserBundle\Entity\User#titles' that was not configured to cascade persist operations for entity*

which is the expect result even if I just need to configure the cascade persist.

Is this a bug? It seems that the transformation is not taking place.

**Comment by hugohenrique** [comment]
I am also the same problem.

**Comment by stof** [comment]
``configureOptions`` does not work on Symfony 2.6. It is only for 2.7+

**Comment by hugohenrique** [comment]
I'm using ~2.7

**Comment by stof** [comment]
@hugohenrique can you show me your code ?

**Comment by hugohenrique** [comment]
```php
namespace MyApp\AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BusinessHourFormType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'business_hour_type';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => MyEntity::class,
                'validation_groups'  => ['MyGroup'],
                'cascade_validation' => true,
                'csrf_protection' => false
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'businessHours',
            'collection',
            [
                'type' => 'my_custom_type',
                'label' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ]
        );
    }
}

**Comment by stof** [comment]
@hugohenrique please also paste the output of ``composer show symfony/symfony -i`` and the exact error message you are using

**Comment by hugohenrique** [comment]
The application is in production... I downgraded to version 2.7.2
And used "the old way", ie: ```configureDefaults``` to ```setDefaultOptions``` and functioned normally.
And this time the composer show ```symfony / symfony -i``` believe will not result expected.

But if you still need, I can catch.

**Comment by stof** [comment]
I don't understand what you mean when saying ``believe will not result expected``.

And  yes, I would like you to reproduce the issue to get the exact error message you have to help you. Because it you are actually running on 2.7.2, it simply cannot be the same issue than the original report (which was just about using a 2.7+ feature on 2.6 which cannot work)

**Comment by hugohenrique** [comment]
Ok @stof thank you!
I will try to reproduce exactly and send accurate information.

**Comment by jakzal** [comment]
@hugohenrique any news?

**Comment by hugohenrique** [comment]
Sorry for not playing before, but how much time has passed I can not more.
But I believe that the error occurred for some incompatibility with earlier versions of Doctrine and not the Form component.
I think that can be closed.

**Comment by jakzal** [comment]
@hugohenrique thanks! Feel free to reopen if you manage to reproduce.
