### ISSUE TITLE
[2.6][OptionsResolver] setDefault() is missing in OptionsResolverInterface

### ISSUE THREAD

**Issue by velosipedist** [symfony/symfony#14612]
...and therefore `@return` tags pointing to interface chained-return breaks IDE autocompletion and even raises "undefined method" warning.

I can fix it myself, which solution is better ?
- document `@return $this` instead of interface pointing?
- add missing methods to interface?

I'd prefer the first cause interface is deprecated anyway and not intended to be used further. Also, it won't break BC in existing 2.6-dependent projects.

**Comment by xabbuh** [comment]
We cannot add the method to the `OptionsResolverInterface` without breaking BC. If any, we could just update the return type in `OptionsResolver`.

**Comment by jakzal** [comment]
Regarding returning `$this` see #11577

**Comment by stof** [comment]
@jakzal the interface is deprecated. In 3.0, it is gone.

**Comment by Tobion** [comment]
Closing as this is about a deprecated thing we cannot change.
