### ISSUE TITLE
[Form][FileType] Make 'accept' attribute an option

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#14616]
Currently the `FileType` class allows you to set the `accept` attribute via the `attr` array:

```php
->add('inputImage', 'file', array(
    ...
    'attr' => array(
        'accept' => 'image/*'
    ),
    ...
))
```

Given that `required` and `multiple` are [supported and documented](http://symfony.com/doc/current/reference/forms/types/file.html), what about also adding `accept` to the class as a basic option, and add documentation about it to the cookbook?

http://www.w3.org/TR/2012/WD-html5-20121025/states-of-the-type-attribute.html#attr-input-accept

**Comment by inso** [comment]
https://github.com/symfony/symfony/issues/6732#issuecomment-94322372

**Comment by xabbuh** [comment]
:-1: for the reasons explained by @Tobion in https://github.com/symfony/symfony/issues/6732#issuecomment-94322372

**Comment by Rvanlaak** [comment]
The `accept` could actually be used in the backend logic right? 

:+1: for the argument of #6732 , because that's also possible when handled via the `attr` array.
