### ISSUE TITLE
Add a "cache" component

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#14624]
I think it would be great to have a generic interface for caching.
For this it would be nice to have a "cache" component.

> Symfony doesn't have Cache component, but some generic API would be useful in order to avoid explicit dependency on Doctrine Cache. Doctrine is just implementation detail.

See https://github.com/symfony/symfony/issues/6129#issuecomment-65939396

**Comment by Tobion** [comment]
See https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md
