### ISSUE TITLE
Doctrine memcache using connect rather than addServer

### ISSUE THREAD

**Issue by adrienbrault** [symfony/symfony#14629]
https://github.com/symfony/symfony/blob/b47b51187e63e342487f935a2cc60f31db60e73d/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php#L338-L340

Is there a reason the code is using `connect` rather than `memcache` ?

I would expect `connect` to be blocking, while with `addServer` the connection will happen only when trying to get/set from memcache

**Comment by javiereguiluz** [comment]
Since the change you propose is just one line of code:

```diff
-$memcacheInstance->addMethodCall('connect', array(
+$memcacheInstance->addMethodCall('addServer', array(
    $memcacheHost, $memcachePort,
));
```

What do you think about submitting a pull request to get feedback from the community? Thanks!
