### ISSUE TITLE
Missing dependency in debug-bundle

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14621]
When using DebugBundle standalone or with smaller frameworks like silex a needed dependency is not declared required when it should be.

Needed package: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Config/composer.json#L2

Mssing from declaration: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/DebugBundle/composer.json#L18-L23

Calling code: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/DebugBundle/DependencyInjection/Configuration.php#L22

**Comment by GromNaN** [comment]
Why do you need the Configuration class with Silex ? It is here to configure the Symfony DependencyInjection container.

**Comment by ogizanagi** [comment]
The package is in the [suggest](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/DebugBundle/composer.json#L30-L31) section, right ?
> "symfony/config": "For service container configuration"

**Comment by stof** [comment]
You cannot use the Configuration class for Silex, as it does not use this layer.

Btw, DebugBundle does not provide any value for usage in Silex: it contains only the integration with the fullstack framework. All the logic leaves in the VarDumper component

**Comment by nicolas-grekas** [comment]
@flip111 for Silex, see https://github.com/jeromemacias/Silex-Debug

**Comment by flip111** [comment]
I will investigate this some more. Please do not close yet

**Comment by iltar** [comment]
You shouldn't be using bundles outside of Symfony as that's what's bundles are designed for, I don't see why this shouldn't be closed yet.

**Comment by flip111** [comment]
Ok so some further investigation

@stof _DebugBundle does not provide any value for usage in Silex: it contains only the integration with the fullstack framework_  ... could be .. however the silex bundle requires it as dependency https://github.com/jeromemacias/Silex-Debug/blob/master/composer.json#L14

Looks like it has a dependency on the silex bundles for it's templates because of https://github.com/jeromemacias/Silex-Debug/blob/master/DebugServiceProvider.php#L68

So the configuration class is not instantiated ... but the reflection already causes a fatal error. A few questions:

1. Is the dependency on the symfony bundle valid to get the templates? I think yes
2. Should the bundle require all the packages where it's using classes from? I'm not sure what to think about this
3. Could there be a better way to get the templates path then reflection on the Configuration class? I'm not sure about this either ... but that is outside the scope of this issue.

**Comment by stof** [comment]
@flip11 the solution would be to use a different class in Silex-Debug for that (for instance the DebugBundle class itself)

**Comment by flip111** [comment]
@stof the author is trying to get the path to the symfony-debug ... i don't understand how knowing the path to silex-debug would help with that

**Comment by stof** [comment]
``in Silex-Debug`` was refering to ``in the in Silex-Debug code``

**Comment by flip111** [comment]
@stof ah yes ... my thought too. At first glance though all classes use yet other packages that are also not required or optional requirements. Also in the future such class could be updated with even more dependencies on other packages.

**Comment by stof** [comment]
Given that the bundle really contains only the config layer, it might make sense to add a required dependency on the config component though
