### ISSUE TITLE
PdoSessionHandler current transaction is aborted

### ISSUE THREAD

**Issue by serkorneev** [symfony/symfony#14641]
Sometimes i have problem: `PDOException: Exception 'PDOException' with message 'SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block' in /../vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php:546`

I am using PostgreSql.

**Comment by Tobion** [comment]
There are many possible reasons. Nothing we can do without you debugging the reason yourself. And not even giving us any information of your usage at all.

**Comment by serkorneev** [comment]
@Tobion I think I found problem. We begin transaction -> execute select query -> execute insert query (transaction breaks) -> execute select query in broken transaction.

**Comment by serkorneev** [comment]
I think we must execute rollback before select query in catch (or execute rollback and beginTransaction).

**Comment by Tobion** [comment]
We do not want to rollback the transaction but leave it open.

**Comment by Tobion** [comment]
What is the SQL state of the failed insert in line https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L542 ?

**Comment by serkorneev** [comment]
23000

**Comment by Tobion** [comment]
Seems like postgres does not allow to continue the transaction as easiliy as in mysql. See http://www.postgresql.org/message-id/200604020407.JAA21169@WS0005.indiatimes.com

So we either need to create a savepoint and rollback to that, or create a new transaction, or try to avoid the duplicate key at all. But since postgres does not support MERGE/UPSERT, it's complicated.
Btw, AFAIK just a few days ago postgres added support for UPSERT-like syntax, but that will take time to be available.

**Comment by serkorneev** [comment]
@Tobion thanks.

**Comment by Tobion** [comment]
@serkorneev can you try to add `$this->rollback(); $this->beginTransaction();` before the select statement im https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L546 and see if it fixes the problem? I think this should do the trick.

**Comment by serkorneev** [comment]
@Tobion yes, it fixes problem.

**Comment by Tobion** [comment]
The problem is, when we rollback the transaction at this point, we have the concurrency problem again, i.e. 2 connections both get rolled back before doing the SELECT FOR UPDATE in a new transaction. So one of them would not be blocking again. So we would need to wrap that code in a loop.

**Comment by kcivey** [comment]
We keep getting this intermittent error too. Does this mean PdoSessionHandler isn't really usable with Postgres yet?

**Comment by mvrhov** [comment]
I'd suggest using a trigger for Postgresql under 9.5
The example of such trigger can be found at [dovecot wiki](http://wiki2.dovecot.org/Quota/Dict)

**Comment by jeremylivingston** [comment]
Also getting this error. Is there a recommended solution? I'd be happy to provide a PR if one is needed.

**Comment by Tobion** [comment]
See #19101 for a fix.
