### ISSUE TITLE
[Form] Unable to define the "choices" option on a entity field when creating the field in eventlisteners.

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#14652]
I rewrote the question to be clearer :

In a Formtype, I want to create an "entity" field with some choices, dynamically.

But when I create this field in a FormEvent 
(like here http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html#cookbook-form-events-user-data ),
setting the "choices" option throws an error (Notice: Undefined offset: 0).

```
<?php
// When creating this field in the form it works

    public function buildForm($builder, array $options)
    {
		$myOptions = array("class"=>"AppBundle:User","choices"=>$this->em->getRepository('AppBundle:Users')->findAll());
	    $builder
            ->add('user','entity',$myOptions))
			->add('submit','submit');
    }

// When creating this field in a EventListenet it doesn't work

    public function buildForm($builder, array $options)
    {
        $builder
			->add('submit','submit');
		$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $form = $event->getForm();
			$myOptions = $form->get('user')->getConfig()->getOptions();
			$myOptions['choices'] = $this->em->getRepository('AppBundle:Users')->findAll();
			$form->add('user','entity',$myOptions));
        });
    }
```

**Comment by Alsatian67** [comment]
Of course this is just an example as simple as possible to reproduce the problem I have.
The real business logic tries to set the posted data as choices ...

**Comment by Alsatian67** [comment]
It is finally working, when I explicit only define the options which are important instead of reuse the full options :

```
<?php
    public function buildForm($builder, array $options)
    {
        $builder
			->add('submit','submit');
		$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $form = $event->getForm();
			$myOptions = $form->get('user')->getConfig()->getOptions();
			$choices = $this->em->getRepository('AppBundle:Users')->findAll();
			$form->add('user','entity',array("class"=>$myOptions['class'],"choices"=>$choices)));
        });
    }
```

Now I have a new problem (no bug), I want to do that on two FormEvents :

-	POST_SET_DATA (to populate the choice field with the current choices (=choices related to the entity I am editing))
-	POST_SUBMIT (to populate the choice with the posted choices loaded with AJAX, so that my posted choices can be validated).

-> My method can't be user for POST_SUBMIT, because I can't add a field on a submitted post.


Can someone explain me how I can change the available choices in the entity field without overwrite the field like I did it here ?

**Comment by jakzal** [comment]
@Alsatian67 we only use github for bug reports and pull requests. Please ask support questions on one of the [IRC channels](http://symfony.com/irc) or the [mailing list](http://symfony.com/mailing-lists).

**Comment by Alsatian67** [comment]
@jakzal , I opened a new topic in the google group a week ago.
It is still waiting to be approved. Is it normal ?

**Comment by LastKhode** [comment]
@Alsatian67 , how did you solved it cause i'm facing on similar situation and can't find any way to get it done.
The thing is to pass the choices possibility to the field when submit the form.

**Comment by Alsatian67** [comment]
@LastKhode 

ave a look on my [FormBundle](https://github.com/Alsatian67/FormBundle), it provide an "ExtensibleEntityType", the choices are populated in [this listener](https://github.com/Alsatian67/FormBundle/blob/master/Form/Extensions/ExtensibleSubscriber.php), using PRE_SET_DATA and PRE_SUBMIT events.
