### ISSUE TITLE
[TWIG] Rename $role of isGranted to $attribute

### ISSUE THREAD

**Issue by nagmat84** [symfony/symfony#14656]
The first parameter of Symfony\Bridge\Twig\Extension\SecurityExtension.isGranted(...) is called $role. This parameter is passed to the $attribute parameter of SecurityContextInterface.isGranted and then further down the path finally passed to the AccessDecisionManager.

This parameter is not restricted to being a role (aka "ROLE_SOMETHING") nor restricted to being a string. For example the ExpressionVoter expects the $attribute to be an instance of Expression.

That this parameter is called $role within TWIG is confusing because it leads to the wrong assumption that only roles are allowed. See also issue #14655.

**Comment by iltar** [comment]
Personally I find `$attribute` to be confusing too, when working with it, I always think it's the second parameter (the object in question). Maybe a full rename of the string variable we pass is a good idea;

**Comment by iamluc** [comment]
Maybe `$capability` ?

**Comment by stof** [comment]
Renaming a parameter here is a BC break, because Twig supports named parameters

**Comment by nagmat84** [comment]
I like $capability. If this is a BC break, perhaps this change could be
integrated into Symfony 3.0.0?

However, the documentation that says the type was a string can be changed
immediately. It is not a string, it can be any type as long as there is at
least one voter that supports it.

2015-05-18 17:31 GMT+02:00 Christophe Coevoet <notifications@github.com>:

> Renaming a parameter here is a BC break, because Twig supports named
> parameters
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony/issues/14656#issuecomment-103105304>.
>



-- 
Matthias Nagel
Parkstraße 27, 76131 Karlsruhe, Deutschland
Festnetz: +49-721-96869289, Mobil: +49-151-15998774
e-Mail: matthias.h.nagel@gmail.com, Skype: nagmat84

**Comment by fabpot** [comment]
Closing as renaming would not be possible without a hard BC break.
