### ISSUE TITLE
[Security] Documentation about VoterInterface.supportsAttribute(...) is wrong

### ISSUE THREAD

**Issue by nagmat84** [symfony/symfony#14655]
The documentation says that the parameter of VoterInterface.supportsAttribute( $attribute ) should be a string. But this is neither required nor inforced by the code. Actually, the child class ExpressionVoter even checks if $attribute is an instance of Expression.

**Comment by dosten** [comment]
Can you open a PR?

**Comment by nagmat84** [comment]
What is a PR and how do I open it?

**Comment by Green-Cat** [comment]
@nagmat84 It's a pull request, essentially a contribution to the project.
