### ISSUE TITLE
request_stack in service called by console command returns null

### ISSUE THREAD

**Issue by xurshid29** [symfony/symfony#14677]
Hi,
I have a service class with injected `request_stack` service, works ok. One of its methods uses this `request_stack` service to access some request object data. It works perfect when I call it by browser, but it returns `null` whenever I call it in my console command. Is this normal behavior? (SF 2.6.7)
short example:
```
class MyService
{
    private $requestStack;

   // constructor goes here

   public function test()
    {
        $request = $this->requestStack->getCurrentRequest();

        dump($request);
        die;
    }
}

class MyConsoleCommad extends ContainerAwareCommand
{
    ....
 
    protected function execute(InputInterface $input, OutputInterface $output)
    {
		$myService = $this->getContainer()->get('MY_SERVICE_ID');
        $myService->test();
    }
}
```

**Comment by stof** [comment]
This is perfectly expected. There is no HTTP request in a CLI command, so there is no current request in the stack.
And the return type of ``RequestStack::getCurrentRequest`` is ``Request|null``.
