### ISSUE TITLE
Stylesheets and javascript files randomly get internal server errors

### ISSUE THREAD

**Issue by kayvanbree** [symfony/symfony#14679]
Since this commit (https://github.com/symfony/symfony/commit/4d408525962b78abbb9f40d699d1b959aae2f8f1) stylesheets and javascript files are not found. The server randomly returns an internal server error when trying to load resources that were installed using the Assetic install command.

For example: 

    {% stylesheets filter='cssrewrite'
        'bundles/manager/css/style.css'
    %}
        <link href="{{ asset_url }}" rel="stylesheet" media="screen" type="text/css" />
    {% endstylesheets %}

The stylesheet returns a 500 internal server error, however, after reloading a couple of times the stylesheet returns 200 and some other stylesheet or javascript file is broken. Using the inspector in Google Chrome shows the stylesheets returns 500, but when you go to the requested link, the stylesheet loads perfectly fine.

When I comment out the lines added in (https://github.com/symfony/symfony/commit/4d408525962b78abbb9f40d699d1b959aae2f8f1) the code runs just OK.

**Comment by kayvanbree** [comment]
Please ask if more information is needed and I'll provide it.

**Comment by aitboudad** [comment]
just checked without any issue so I'm not sure it's related to the commit mentioned above. 
@kayvanbree would you mind forking the Symfony Standard and make the changes needed to reproduce it?

**Comment by xabbuh** [comment]
@kayvanbree Do you see something more verbose in the logs for the errored request?

**Comment by javiereguiluz** [comment]
I haven't experience the mentioned issue. @kayvanbree could you please provide more information of confirm if the error is gone? Thanks!

**Comment by jakzal** [comment]
There's no feedback since May last year. Let's close. 

@kayvanbree if you're still experiencing the issue, please provide more information and we'll reopen.
