### ISSUE TITLE
IpUtils::checkIp4() should allow `/0` networks

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#14674]
The `0.0.0.0/0` is a valid CIDR and every IP address falls into it.

I think `IpUtils::checkIp4()` should allow it

**Comment by dosten** [comment]
Do you have any reference about this?

**Comment by zerkms** [comment]
@dosten http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing ?

**Comment by zerkms** [comment]
http://tools.ietf.org/html/rfc4632

> In CIDR notation, a prefix is shown as a 4-octet
   quantity, just like a traditional IPv4 address or network number,
   followed by the "/" (slash) character, followed by a decimal value
   between 0 and 32 that describes the number of significant bits.

http://tools.ietf.org/html/rfc4632#section-3.1
