### ISSUE TITLE
Should the Response class finish the fast cgi request?

### ISSUE THREAD

**Issue by NigelGreenway** [symfony/symfony#14675]
The reason I ask is that if I want to run something after `$response->send()` on a server using fastcgi, nothing will run due to the following block:

```php
// snip
$this->sendHeaders();
$this->sendContent();

if (function_exists('fastcgi_finish_request')) {
    fastcgi_finish_request();
} elseif ('cli' !== PHP_SAPI) {
    static::closeOutputBuffers(0, true);
}

return $this;
// snip
```

Apache works fine when not using fastcgi, so should the `$response->send()` have the responsibility of killing the server process or should that be left to the application, like using the TerminableInterface or something similar.

Is this dangerous having different outcomes based on the type of web server it is being executed on?

**Comment by Tobion** [comment]
The terminate logic is still run after fastcgi_finish_request with https://github.com/symfony/symfony-standard/blob/2.7/web/app.php#L30
What bug do you experience or what exactly do you propose to change?

**Comment by NigelGreenway** [comment]
HI @Tobion,

Cheers for the quick response.

My experience is anything set to run after the `$response->send()` fails to execute.

I have found the following results:

Web server | PHP SAPI Name | Executes After `$response->send()`
----------------|----------------|-------------------------------------------------
Apache | apache2handler | true
Nginx | php-fpm | false
Hiawatha | php-fpm | false

However, if I comment out `fastcgi_finish_request()` like so, the code after `$response->send()` will execute fine.

```php
    public function send()
    {
        $this->sendHeaders();
        $this->sendContent();

        if (function_exists('fastcgi_finish_request')) {
//            fastcgi_finish_request();
        } elseif ('cli' !== PHP_SAPI) {
            static::closeOutputBuffers(0, true);
        }

        return $this;
    }
````

Am I missing something?

To get around the issue I have come across, I am doing the following

```php
    public function run(Request $request = null)
    {
        if (null === $request) {
            $request = Request::createFromGlobals();
        }

        $response = $this->handle($request);

//            $response->send();
        $response->sendHeaders();
        $response->sendContent();

        $this->terminate($request, $response);
    }
```

If I were to do a PR for it, I would simply change `Response::send` to:

```php
    public function send()
    {
        $this->sendHeaders();
        $this->sendContent();

        return $this;
    }
```

The reason being is that I believe the Response class should not be responsible for terminating the connection for the `fastcgi` or `cli` sapi.

#### Some extra info:

This was found by creating a @stackphp application. The issue turned up when I was trying to do some simple benchmarking where my `terminate` method was not being executed when I was running it through the `Stack\Builder` and `Stack\run`.

Cheers

**Comment by jakzal** [comment]
How did you verify that `terminate()` wasn't run?

**Comment by NigelGreenway** [comment]
hi @jakzal, I added a simple `echo` statement.

**Comment by jakzal** [comment]
It didn't work as code run after `fastcgi_finish_request()` is executed after the connection is closed. See [fastcgi_finish_request() docs](http://php.net/manual/en/function.fastcgi-finish-request.php) for more info.

**Comment by NigelGreenway** [comment]
Right, that makes more sense to me now, cheers @jakzal. (I did read that last night but it was late. :smiley:  )

So, if I wanted to append, say the results of the code runtime to the end of the response content, I would need to use `$response->setContent($response->getContent() .  _my_result_here_ )` if I want it to display further information?

**Comment by jakzal** [comment]
You can't append anything after response was sent. You should do this earlier, for example in a kernel.response listener.

**Comment by NigelGreenway** [comment]
Sorry, I meant before `$response->send()`.

Thank you for help.
