### ISSUE TITLE
[2.7][BC Break][Translation] Undocumented BC break regarding caching

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14689]
I'm using a custom translation loader where the loader is the resource, a database loader [like this one](https://github.com/maschmann/TranslationLoaderBundle/blob/master/Translation/DatabaseLoader.php#L93-L96). The problem is that as of symfony 2.7, the creating of the cache is slightly changed, it also serializes the resource now. Because my resource is using an entity manager to fetch the translations, it tries to serialize the EM and this of course fails.

A solution is to implement the `Serializable` interface or to use the `spl_object_hash()` instead.

https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Translation/Translator.php#L376-L379
```php
    // 2.6
    private function getCatalogueCachePath($locale)
    {
        return $this->cacheDir.'/catalogue.'.$locale.'.'.sha1(serialize($this->fallbackLocales)).'.php';
    }
```
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/Translator.php#L420-L428
```php
    // 2.7
    private function getCatalogueCachePath($locale)
    {
        $catalogueHash = sha1(serialize(array(
            'resources' => isset($this->resources[$locale]) ? $this->resources[$locale] : array(),
            'fallback_locales' => $this->fallbackLocales,
        )));
        return $this->cacheDir.'/catalogue.'.$locale.'.'.$catalogueHash.'.php';
    }
```

**Comment by fabpot** [comment]
ping @aitboudad

**Comment by aitboudad** [comment]
I didn't introduced anythink I tried to just to improve https://github.com/symfony/symfony/pull/13074, we can just use count to solve the serialize issue.
```php
        $catalogueHash = sha1(serialize(array(
            'resources' => isset($this->resources[$locale]) ? count($this->resources[$locale]) : 0,
            'fallback_locales' => $this->fallbackLocales,
        )));
```

**Comment by iltar** [comment]
Seems like a good fix to me :+1:

**Comment by stof** [comment]
@iltar Resources are **already** serialized in other places (in the .meta file of the ConfigCache for instance). so 2.6 was probably already serializing them, but in a different place.

**Comment by iltar** [comment]
@stof I don't know about that, but this is since 2.7 as you can see in the changes in the file. In 2.6 this works just fine but in 2.7 and 2.8 it's broken. I don't think the resource was serialized the same way as now in that case or I'm using a different strategy without knowing it.

**Comment by aitboudad** [comment]
fixed by #14705

**Comment by mpdude** [comment]
@stof Sure we're talking about the same kind of resource here?

**Comment by mpdude** [comment]
The problem that we tried to solve was that the Translator needs to use a different cache file when it is configured differently (think of resources added or removed or configured differently).

Just using the number of resources added will not suffice to cover all the (edge?) cases. 

I don't think the resources themselves have to be serializable (they are not necessariliy those put into the `ConfigCache`), we just need to be able to hash them.
