### ISSUE TITLE
[HttpFoundation] Get data from masterRequest

### ISSUE THREAD

**Issue by Shine-neko** [symfony/symfony#14697]
```php
$request = Request::create('/foo', 'GET', array('foo' => 'bar'));
$requestStack = new RequestStack();
$requestStack->push($request);
$masterRequest = $requestStack->getMasterRequest();
$masterRequest->attributes->get('foo') // is null
```
Is this a bug ?

**Comment by dosten** [comment]
What happend if you do `$request->attributes->get('foo')`?

**Comment by stof** [comment]
The third argument for ``Request::create`` does **not** populate ``Request#attributes``. It populates ``Request#query`` for a GET request and ``Request#request`` for other methods.

So it is not a bug. It is a misuse of the Request object.

**Comment by Shine-neko** [comment]
@stof if I use $request->get('foo')it works. 
however render(controller())  $request->request->all() & $request->query->all() is empty

**Comment by stof** [comment]
@Shine-neko ``render(controller())`` is a totally different topic than the onje you described here, and the creation on the Request in this case is not the one you described here.
``$request->request`` being empty in subrequests is expected (it is always empty for GET requests, and subrequests are always using GET). Regarding ``$request->query``, it depends how you create the subrequests. the query parameters are passed in the **third** argument of ``controller()`` (the second one is about populating ``$request->attributes``)
