### ISSUE TITLE
Translation files in components

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14701]
I noticed that not every bundle/ component is following the standards when it comes to translations. There are several components that contain translation files instead of the bundles. Is this done by design or should they be moved to their respective bundles? I can understand if they would be put there due to usage of them in the components as stand-alone, but they do seem to follow bundle standards. 

```yml
./Form/Resources/translations/*
./Security/Resources/translations/*
./Security/Core/Resources/translations/*
./Validator/Resources/translations/*
```

**Comment by aitboudad** [comment]
@iltar see https://github.com/symfony/symfony/pull/14561

**Comment by iltar** [comment]
What's the actual idea? Keep them in the component, but change the location once puli is supported?

**Comment by aitboudad** [comment]
yes, not changing the location but just follow bundle standards using puli.

**Comment by iltar** [comment]
Alright, so if it's by design, I guess you can close this :+1:

**Comment by fabpot** [comment]
It is by design to make the component reusable outside the full-stack framework (like Silex for isntance)
