### ISSUE TITLE
[2.6] Doctrine ClassMetadataFactory PHP 5.3 syntax error, unexpected '[', expecting ')'

### ISSUE THREAD

**Issue by PiotrLuczko** [symfony/symfony#14702]
```
$ php app/console doctrine:mapping:convert yml ./doctrine --from-database --force

Parse error: syntax error, unexpected '[', expecting ')' in /home/[cut]/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php on line 80
[2015-05-20 13:23:25] php.EMERGENCY: Fatal Parse Error: syntax error, unexpected '[', expecting ')' {"type":4,"file":"/home/[cut]/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php","line":80,"level":-1,"stack":[]}



  [Symfony\Component\Debug\Exception\FatalErrorException]
  Parse Error: syntax error, unexpected '[', expecting ')'



doctrine:mapping:convert [--filter="..."] [-f|--force] [--from-database] [--extend[="..."]] [--num-spaces[="..."]] [--namespace[="..."]] [--em[="..."]] to-type dest-path


$ php -v
PHP 5.3.29 (cli) (built: Apr 20 2015 15:48:10)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with IdeaCache v2.0, Copyright (c) 2006-2010, by home.pl
    with the ionCube PHP Loader v4.4.0, Copyright (c) 2002-2013, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies
```

**Comment by PiotrLuczko** [comment]
Using php 5.4, 5.5 and 5.6 everything is ok

**Comment by stof** [comment]
This is not a symfony error. The parse error is in a Doctrine file, not in Symfony.

and btw, the bug is in your own setup: Doctrine ORM 2.5+ requires PHP 5.4+, so using it on PHP 5.3 is invalid.

**Comment by Tobion** [comment]
@stof since symfony-standard now distributes the lock file, everybody that updates it must make sure that the composer update is done with php 5.3. otherwise it might install dependencies with are not compatible with the minimum requirements of symfony. how about adding the `platform` php 5.3 hard setting to composer.json of symfony-standard by default?

**Comment by Tobion** [comment]
and if somebody has a newer php version, he can remove the platform setting and update the dependencies

**Comment by hazasaad** [comment]
Symfony 2.8 Parse error: syntax error, unexpected ':', expecting ';' or '{' in c:\xampp\htdocs\myproject\path\to\AnnotationRegistry.php on line 50

how to solve this error

**Comment by hazasaad** [comment]
C:\xampp\htdocs\web-service>composer require --dev symfony/phpunit-bridge
Using version ^3.3 for symfony/phpunit-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/symfony 3.4.* is satisfiable by symfony/symf
ony[3.4.x-dev, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3] but these conflict with
 your requirements or minimum-stability.
  Problem 2
    - The requested package symfony/symfony (installed at v2.8.29, required as 3
.4.*) is satisfiable by symfony/symfony[v2.8.29] but these conflict with your re
quirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by NicoHaase** [comment]
@hazasaad: Which version of PHP are you running? This sounds like its PHP <7 and you try to use a more recent version of some class which is called AnnotationRegistry.php - is this a class coming from Symfony? According to your path, its more likely to be a class of your own project

**Comment by hazasaad** [comment]
@NicoHaase php 5.3.3 server php 5.6.31
i just update my symfony project 2.6 to 2.8

**Comment by hazasaad** [comment]
@NicoHaase from vendor annotionregistry.php

**Comment by NicoHaase** [comment]
Well, as I wrote: you try to run code for PHP 7 using PHP 5. That won't work, and this is completely valid behaviour. Try to downgrade doctrine/annotations to v1.4.0 or older

**Comment by hazasaad** [comment]
how to do @NicoHaase

**Comment by hazasaad** [comment]
need to edit in composer.json

**Comment by hazasaad** [comment]
"doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2"

**Comment by hazasaad** [comment]
how to update my php version

**Comment by NicoHaase** [comment]
Sorry, pal, but this is an issue tracker for the Symfony framework and not a general support forum. If you want to update the PHP version you are using on your computer, you should check out tutorials for this topic from other sources.

**Comment by Tobion** [comment]
http://symfony.com/support
