### ISSUE TITLE
ExceptionHandler - PHP Parse Error with Symfony 2.6.8-DEV

### ISSUE THREAD

**Issue by benstinton** [symfony/symfony#14703]
I've just upgraded to 2.6.8 from 2.4.3 and got the following error in app_dev.php

PHP Parse error: syntax error, unexpected ',', expecting ')' in /symfony/vendor/symfony/symfony/src/Symfony/Component/Debug/ExceptionHandler.php on line 383

Removing the extra , solves the issue

**Comment by burci** [comment]
It was introduced in #14699 pull request.

**Comment by benstinton** [comment]
Thanks for letting me know, should I close this issue?

**Comment by benstinton** [comment]
Thanks, should I close this issue?
