### ISSUE TITLE
[DOMCrawler] Replace \Closure by callable on each and reduce function

### ISSUE THREAD

**Issue by instabledesign** [symfony/symfony#14709]
Hi,

I suppose to change the \Closure by a callable and/or an array like ```[$this, 'methodName']``` on the [Crawler::each](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DomCrawler/Crawler.php#L343) and [Crawler::reduce]
(https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DomCrawler/Crawler.php#L377), because it's really exhausting to inject all needed param by ```use () ```

example: 
```php
$xml = <<<XML
<root>
    <foo>
        <bar>
            <baz>baz1</baz>
            <baz>baz2</baz>
        </bar>
        <bar>
            <baz>baz3</baz>
        </bar>
    </foo>
</root>
XML;

$crawler = new Crawler($xml);

$neededParam1 = 'examplecontent';
$neededParam2 = 'examplecontent';

$crawler->children()->filterXPath('//root/foo')->each(function (Crawler $fooCrawler) use ($neededParam1, $neededParam2) {
    // Do some operation
    $fooCrawler->children()->filterXPath('bar')->each(function (Crawler $barCrawler) use ($neededParam1, $neededParam2) {
        // Do some operation
        $barCrawler->children()->filterXPath('baz')->each(function (Crawler $bazCrawler) use ($neededParam1, $neededParam2) {
            // Do some operation with $neededParam1, $neededParam2
        });
    });
});
```

**Comment by instabledesign** [comment]
Can you add the RFC label too.?

**Comment by xabbuh** [comment]
@instabledesign done

However, regarding your suggestion: I understand your request and I believe that this would be a valuable change, but I am afraid that we would not be able to make it (at least not before Symfony 3.0) because of our [BC promise](http://symfony.com/doc/current/contributing/code/bc.html#changing-classes).

**Comment by dosten** [comment]
see #14330

**Comment by instabledesign** [comment]
Thx @dosten to reference it.

**Comment by jakzal** [comment]
closing in favour of #14330.
