### ISSUE TITLE
[SecurityBundle][DX] Extract the ACL to its own bundle

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14718]
_Maybe I'm over thinking this a bit and this can be dropped, but I feel like it is the right thing to suggest._

### What does the cookbook say?
First I'd like you to read the following snippets I got [from the cookbook](http://symfony.com/doc/current/cookbook/security/acl.html):
 > Using ACL's isn't trivial, and for simpler use cases, it may be overkill.

It uses [doctrine by default](http://symfony.com/doc/current/cookbook/security/acl.html#bootstrapping) but [isn't required by default](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/composer.json#L22-L27).
 > The ACL system requires a connection from either Doctrine DBAL (usable by default) or Doctrine MongoDB (usable with MongoDBAclBundle). However, that does not mean that you have to use Doctrine ORM or ODM for mapping your domain objects. You can use whatever mapper you like for your objects, be it Doctrine ORM, MongoDB ODM, Propel, raw SQL, etc. The choice is yours.

### Complexity for new users
Whenever I see questions coming by on `#symfony` related to the ACL, 99% of the time I recommend them to use custom voters as it's far easier to use and implement and covers 99% of their use-cases. 

Someone that wants to implement the ACL needs to have [understanding of Commands, the Security Component, the database layer](http://symfony.com/doc/current/cookbook/security/acl.html#bootstrapping) - which is doctrine by default - and (ACLs in general)[http://symfony.com/doc/current/cookbook/security/acl.html#creating-an-acl-and-adding-an-ace].

So it's not used very frequently, it's got a dependency on doctrine but can work with others and sits in the core, while things such as the monolog-bundle or assetics-bundle are required to be added manually.

### What would be the benefits of extracting it?
I've composed a small list of things I noticed.
 - <del>The `Core\Util` has a [ClassUtils](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Util/ClassUtils.php) that is based on the [doctrine ClassUtils](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Util/ClassUtils.php), but [only used in the ACL](https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=classutils), [the form uses the doctrine variant](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php#L22).</del> Fixed
 - It would reduce complexity and size of the `SecurityBundle`, the ACL config would be moved to its own part. 
 - The `DoctrineBridge` can provide the implementation required for the Doctrine ACL part, which
 - Means that doctrine is not longer a semi-hard dependency of the `Security Component`.
 - As the `Security Component` is rather big, extracting this away would increase maintainability for both packages.
 - <del>The acl-bundle would not be included in the standard-edition, the ACL might just scare them off when it comes to working on the security part of their app. I know I've spend some time on this part and it was just too complex to even consider using it for my migration project (sf1 to sf2).</del> Fixed

**Comment by fabpot** [comment]
I cannot agree more on this. Big :+1: from me.

@iltar Is that something you want to work on?

**Comment by iltar** [comment]
@fabpot I can always give it a shot but I do need some help from someone who has used the ACL as I have close to no experience with implementations. As it will result in a BC break, it needs to be tested thoroughly. Would this be an indication for 3.0 or 2.8? In theory a lot can already be moved in 2.8 using the same methods used before (extending the new component to cover BC breaks).

**Comment by fabpot** [comment]
I think we can extract it in 2.8 as we've done in the past for other parts of the framework. To be clear, are you only proposing to extract things from SecurityBundle to an AclBundle, or do you envision the move of the Security ACL component as well?

**Comment by iltar** [comment]
Extracting it from `symfony/security` might be an idea as well, luckily it's already a bundle on its own: `symfony/security-acl`. This means just the location has to be changed.
 - Remove `src/Symfony/Component/Security/Acl` from `symfony/symfony` and place it in it's own repository? 
 - update the `composer.json` in `symfony/security` to no longer replace/suggest `symfony/security-acl`.

When the bundle gets extracted, I suggest to start with the component as it might already solve some of the issues the bundle would have to fix otherwise. 

### Result
 - No more Acl in `symfony/security`.
 - Installing `symfony/security-acl` would be BC, it would be be placed back in `src/Symfony/Component/Security/Acl`.
 - No namespace/path changes, just not there by default.
 - Dependency on `symfony/security-core` (only `Security\Core` use statements found).


Downside would be that it would still contain some doctrine dependencies until the bundle/bridge are fixed.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by timglabisch** [comment]
awesome :+1:

**Comment by johnnypeck** [comment]
:thumbsup:

**Comment by iltar** [comment]
@fabpot What's the desired approach if I wanted to move the ACL Component out of `symfony/symfony`? Is it possible to turn https://github.com/symfony/security-acl into a real repository for that matter so I can extract it?

**Comment by fabpot** [comment]
First part is done now, the ACL component is now standalone as of 2.8. Next step is the bundle.

**Comment by fabpot** [comment]
I've also just created the bundle repository: https://github.com/symfony/AclBundle

**Comment by TomasVotruba** [comment]
@fabpot Awesome job, thanks!

**Comment by iltar** [comment]
@fabpot I can't fork it, I think it's a bit too empty.

**Comment by fabpot** [comment]
@iltar It's not empty anymore. I've just pushed some skeleton files.

**Comment by iltar** [comment]
Initial progress can be found here: https://github.com/iltar/AclBundle/tree/feature/extract-from-core

**Comment by xabbuh** [comment]
see symfony/acl-bundle#1 for the initial PR on the Acl bundle made by @iltar

**Comment by TomasVotruba** [comment]
Great job guys!

What is the current state of this?

I have no experience with using ACL in Symfony (I'm Voters guy), but if there is anything simple I could help with, I'd love to.

**Comment by iltar** [comment]
@TomasVotruba if you check the PR in the reply above you can see my progress, it's getting somewhere but it's not done yet. Feel free to add PRS to my repository and I can add them in the inital PR.

**Comment by Tobion** [comment]
@iltar Since extracting the acl part into it's own bundle will not be ready for 2.8/3.0, can we not just make `security-acl` an optional dependency of `security-bundle` in 2.8 (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/composer.json#L21) ?

`symfony/symfony` doesn't require `security-acl` anymore in 3.0. So `symfony/security-bundle` should not require `security-acl` as well. Otherwise we have inconsistent dependencies when you require `symfony/symfony` or `symfony/security-bundle`.

I think making it optional is all that is needed. If the `acl` config is not explicitly enabled, then the SecurityBundle doesn't need ACL anyway AFAIK. And the commands provided by the bundle (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/Command/SetAclCommand.php) are disabled if ACL is not configured.

**Comment by Tobion** [comment]
When we fix doctrine/DoctrineCacheBundle#76 symfony-standard 3.0 would not come with security-acl anymore.

**Comment by iltar** [comment]
@Tobion `security-acl` an optional dependency of `security-bundle`, how would you envision this? As there is no SecurityBundle without Security ACL. Personally I have been leaving this for 3.1, too much of a change for 2.8/3.0

I was thinking of making security.acl deprecated and let the security handle the injecting into the acl bundle if it's installed. This way the acl bundle stays clean and can require security-acl without problems. This bundle should act as a partial replacement as decided by the user. The downside is that this bundle will have to be kept in sync.

Maybe an exception can be made to have this ready for the next LTS and remove it by then? Personally I would just bump the framework to 4 already before it hits 3.3 (as semver allows this).

**Comment by Tobion** [comment]
> As there is no SecurityBundle without Security ACL.

The security-bundle doesn't work without security-acl? If that is the case than symfony/symfony MUST require security-acl. So either we can make it optional or it is broken currently.

**Comment by iltar** [comment]
@Tobion the security-bundle (or rather acl-bundle) is nothing more than configuration for the security-acl component. The security-bundle works perfectly fine without as long as the acl part is not configured. As soon as the acl is defined, it should have the acl component installed. 

Once the acl bundle is extracted, it should have a dependency on security-acl as it's designed to configure that specific component.

**Comment by Tobion** [comment]
>  The security-bundle works perfectly fine without as long as the acl part is not configured.

Exactly. That is why I said make it an optional dependency. Most people don't use the ACL part. And if they configure the ACL but do not have security-acl installed, we can just throw an exception.

**Comment by iltar** [comment]
For the security-bundle: optional, I agree (but isn't this already in 3.0?)

**Comment by Tobion** [comment]
It's not yet: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/composer.json#L21

**Comment by javiereguiluz** [comment]
Now that the Security ACL repo exists (https://github.com/symfony/security-acl) we could close this issue as fixed, right?

**Comment by WouterJ** [comment]
No, there still is no ACL bundle (it's all included in the security bundle).

**Comment by Tobion** [comment]
Two of the main benefits are already achieved (I updated the description). So creating an acl bundle would make still sense but IMO has low priority as it doesn't bring much value anymore. So IMO we can close the issue until someone actually want to work on it.

**Comment by WouterJ** [comment]
@Tobion well, if it's still valid, the issue should still be open imo.

**Comment by iltar** [comment]
I still have the PR open but I haven't found time to actually work on it from the 3.1 branch on.

**Comment by Tobion** [comment]
Closing in favor of https://github.com/symfony/acl-bundle/pull/1 then
