### ISSUE TITLE
[Console][Feature Request] Required options

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#14716]
Disclaimer: yes, I've seen https://github.com/symfony/symfony/issues/3524 and I cannot agree with it.

The problem with current implementation is that you cannot have the required options. Even though we do have required arguments it does not save us too much, since not all possible semantics can be covered with what we currently have.

Example: we need to accept a list of files and a list of processors to run against them.

We cannot use required array arguments for both since you cannot distinguish between a file name and a processor name in a reliable way.

We cannot use required array arguments and optional array options, since the options are, well, optional in this case.

So what we do is we follow either and put constraint checks manually.

So, what prevents Symfony from having required option parameters? Are there any *technical reasons* against that?

**Comment by jakzal** [comment]
@zerkms could you think of any existing command or application that requires you to provide options?

**Comment by zerkms** [comment]
@jakzal symfony requires `--env=prod` in production.

**Comment by jakzal** [comment]
@zerkms it's not an example of a required option. You only need to add it if you want to run a command in mode different than the default one (prod). It's still optional. 

I was asking for an example of any command that forces you to provide an option all the time. It doesn't have to be Symfony nor php. Any command.

**Comment by zerkms** [comment]
> You only need to add it if you want to run a command in mode different than the default one (prod). It's still optional.

The default one is not prod. At least in the default symfony distribution.

I will think of it, but still - how lack of other commands prevents symfony from having such a feature?

**Comment by jakzal** [comment]
> The default one is not prod

I meant: if you want to run it in prod.

> how lack of other commands prevents symfony from having such a feature?

I'd prefer to be consistent with globally accepted standards.

**Comment by zerkms** [comment]
> I meant: if you want to run it in prod.

If you want to run it in prod you **MUST ALWAYS** specify `--env=prod`

> I'd prefer to be consistent with globally accepted standards.

What are they? Any reference that is accepted and explicitly/implicitly followed?

**Comment by jakzal** [comment]
> If you want to run it in prod you MUST ALWAYS specify --env=prod

The key here is **IF** ;)

**Comment by stof** [comment]
@zerkms If you are forced to specify an option all the time (hint: this is not the case for ``--env`` as you put a IF in the sentence), it does not belong to the command options anymore. It should be an argument. Options are always optional. Otherwise it does not follow the semantic of CLI.

**Comment by jakzal** [comment]
> What are they? Any reference that is accepted and explicitly/implicitly followed?

Most of them comes from GNU and Unix standards. Some examples:
* http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
* http://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Options.html

**Comment by zerkms** [comment]
> It should be an argument

If only you can express it as an argument.

So guys, what stops Symfony as a general purpose framework have that and let developers to do what they want?

**Comment by saksmt** [comment]
@jakzal The example of required options:

 - `java -jar`
 - `nasm -f`
 - `dd`
 - `wicd-cli`
 - Any app related to some list's of data that can be edited, like todo-manager
 - Any app where key specifies the mode

**Comment by xabbuh** [comment]
I can see some limited use-cases where it would make life easier if Symfony offered an option to support required options. Though I an not convinced that we should support it out if the box as it means more code that must not break while providing little value

**Comment by salemgolemugoo** [comment]
"Option" is OPTIONAL by default

**Comment by zerkms** [comment]
@salemgolemugoo it depends on how you name it. I prefer the term "parameter"

**Comment by TomasVotruba** [comment]
@zerkms I know you suggestion makes sense in logical point of view. It's just that standard way is sometimes the best way to go to prevent many WTF issues by not following it. It's drawback per benefits.

Many apps depends on standard, and we don't know how they use it. So if there is an easy manual way to do so, it's better to go with it. I've seen and made many great packages with really cool and use api methods. But they were absolutely non-standard with wast majority of others. So now they're useless and removed. They work and follow the logic still.

**Solution for your use case**

In [ApiGen I made use required parameters](https://github.com/ApiGen/ApiGen#usage) like this.

```sh
apigen generate -s ./src -d ./docs
```

In command, delegate to [options resolver](https://github.com/ApiGen/ApiGen/blob/d3ba06f8325bac1d33fa67a7fb30bd4fd98fafaa/src/Console/Command/GenerateCommand.php#L299).

That [throws an exception, if parameters is missing](https://github.com/ApiGen/ApiGen/blob/d3ba06f8325bac1d33fa67a7fb30bd4fd98fafaa/src/Configuration/ConfigurationOptionsResolver.php#L271-L272).

**Comment by zerkms** [comment]
@TomasVotruba what "standard" you're referring to? As far as I know - there is no one.

**Comment by TomasVotruba** [comment]
@zerkms By "standard" I mean "people are used to use it like this for a long time". 

I use sidewalks not because it's somewhere written, but because I've seen other people does it. Not because it's written somewhere.

**Comment by zerkms** [comment]
@TomasVotruba and my point was to implement something that is convenient, not something that is artificially limited by a 30+ years old irrational decision.

**Comment by TomasVotruba** [comment]
@zerkms You can easily implement it by yourself.

**Comment by zerkms** [comment]
@TomasVotruba I can do and I do myself a lot of things.

This issue is a proposal to move further for the tool/community.

**Comment by javiereguiluz** [comment]
I'd say that we should close this issue as "won't fix".

@zerkms I agree with lots of the things you said ... but the proposed feature looks too narrow in its target. Besides, you can solve this problem by validating the options passed to the command and their values.

**Comment by TomasVotruba** [comment]
@javiereguiluz I agree with you :+1:

**Comment by zerkms** [comment]
That's sad that the suggestion that will not break anything but will make symfony for flexible for arbitrary is discarded.

But okay, let be it.

**Comment by Revisor** [comment]
If you reopen this request sometimes in the future, count me as a +1 vote.

I'd like to use what is now called "options" as required named arguments in order for a command to be understandable at first sight.
This
`command --dir=foo --strategy=bar --processor=baz`
is much more understandable than
`command foo bar baz`

I have made the `--dir=foo` options required in the code, of course, but in the command signature help they still show up as [optional].

**Comment by mattab** [comment]
fyi you can add helper method to do this yourself, [as we do in @Piwik](https://github.com/piwik/piwik/blob/3.x-dev/core/Plugin/ConsoleCommand.php#L33-L45)

```php

    protected function checkAllRequiredOptionsAreNotEmpty(InputInterface $input)
    {
        $options = $this->getDefinition()->getOptions();
        foreach ($options as $option) {
            $name  = $option->getName();
            $value = $input->getOption($name);
            if ($option->isValueRequired() && empty($value)) {
                throw new \InvalidArgumentException(sprintf('The required option %s is not set', $name));
            }
        }
    }
```

**Comment by zerkms** [comment]
@mattab a minor issue in your code: the `empty` in the condition would cause the false negatives when the value passed is `'0'`

**Comment by mattab** [comment]
Good spotting @zerkms - pull request welcome :-

**Comment by edmondscommerce** [comment]
I also need required options. Fair enough not to have them by default and require a little custom code. I took the above and came up with:

```php
    protected function checkAllRequiredOptionsAreNotEmpty(InputInterface $input)
    {
        $errors = [];
        $options = $this->getDefinition()->getOptions();
        foreach ($options as $option) {
            $name = $option->getName();
            $value = $input->getOption($name);
            if ($option->isValueRequired() && ($value === null || $value === '')) {
                $errors[] = sprintf('The required option --%s is not set or is empty', $name);
            }
        }
        if (count($errors)) {
            throw new \InvalidArgumentException(implode("\n\n", $errors));
        }
    }
```

**Comment by liverbool** [comment]
@edmondscommerce `$option->isValueRequired()` can't represent the required options it just require option's value.

It should be like this:
```php
private function checkAllRequiredOptionsAreNotEmpty(InputInterface $input)
    {
        $errors = [];
        $option1 = $this->getDefinition()->getOption('option1');

        /** @var InputOption $option */
        foreach ([$option1] as $option) {
            $name = $option->getName();
            $value = $input->getOption($name);

            if ($value === null || $value === '' || ($option->isArray() && empty($value))) {
                $errors[] = sprintf('The required option --%s is not set or is empty', $name);
            }
        }

        if (count($errors)) {
            throw new \InvalidArgumentException(implode("\n\n", $errors));
        }
    }
```

**Comment by Destroy666x** [comment]
Lack of required parameters makes OOP in commands more difficult for no reason... Example:
- abstract class X that configures an array parameter that should be required
- X extending class Y that configures a regular parameter that should be required

Using arguments for both is logically impossible. Using option for any requires additional checks mentioned above. I hope you will reconsider this.

**Comment by victortodoran** [comment]
One word comes to mind. Lazy

**Comment by lenar** [comment]
One phrase comes to mind: Rename "Options" to "Named Arguments"or something like that without the
ordering requirement of standard arguments. That way the semantics of word 'options' won't be showstopper. Much more useful.

**Comment by philraj** [comment]
The fact that arguments can be optional makes it hard to believe the argument that "options" are for optional values and arguments are better for required values. "Named arguments" is a better term, like @lenar and others suggest.

**Comment by c33s** [comment]
doesn't make it the most sense to introduce a `InputOption::REQUIRED`? see https://github.com/symfony/symfony/pull/48244

**Comment by DanielRuf** [comment]
> as required named arguments

I also need this. Because without that the order is relevant which can lead to manual errors. In the meantime I went with the solution provided by Piwik.
