### ISSUE TITLE
[Routing][3.0] make use of PSR-7

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#14723]
The routing component currently has two methods to match the request: `UrlMatcherInterface` and `RequestMatcherInterface`.

This sucks for implementations as people need to implement both and it is bad from an architecture perspective. It was only created as a workaround anyway. See also https://github.com/symfony-cmf/Routing/pull/116#issuecomment-68352907

For version 3.0 we should get rid of this. With the rise of PSR-7 it is also the perfect time to make use of these interfaces as well since we would break BC anyway. This of course requires https://github.com/symfony/psr-http-message-bridge so that the routing component can easily be integrated in symfony itself.

Here my vision:
- Keep the RequestMatcherInterface but with `public function matchRequest(Psr\Http\Message\RequestInterface $request);`
- Keep UrlGeneratorInterface and merge RequestContextAwareInterface into it with `public function setCurrentUri(Psr\Http\Message\UriInterface $uri);`. The context for generating URLs only needs to be a URI (for generating relative URLs) and not a full request (with method and headers). And it also currently has "global default parameters" (RequestContext::getParameters) which we need to incorporate with something like `setDefaultParameters(array $parameters)`. Currently there are also the `httpPort` and `httpsPort` on the context. This functionality should be moved to a `port` config on the route. This way it is also possible to generate/match routes with different ports which have the same schema. I guess it should be a `ports` config to be consistent with `schemes` which also allows multiple.
- Remove UrlMatcherInterface and RequestContext and RequestContextAwareInterface because it not needed anymore.

Open questions:
- Naming: 
  - `RequestMatcherInterface::matchRequest` vs `RequestMatcherInterface::match`
  - `UrlGeneratorInterface` vs `setCurrentUri(Psr\Http\Message\UriInterface $uri)`: URL from symfony vs URI from PSR-7
  - `UrlGeneratorInterface::generate` vs `UrlGeneratorInterface::generateUri` vs `UrlGeneratorInterface::generateUrl`

Changing everything to URI would probably be too big of a BC break. So I guess we have to live with the URL vs URI inconsistency. I think `matchRequest` and `generateUrl` are better because they are more explicit. But that would require a BC break in UrlGeneratorInterface which we could avoid if we just leave it `generate()` (and `match()`).

**Comment by Tobion** [comment]
Performance impact of request transformation of was an argument in core meeting. So this would need to be measured.

**Comment by stof** [comment]
Do we really need to change the method name in UrlGeneratorInterface ?

Regarding keeping RequestMatcherInterface, an interface using PSr-7 must be a different interface, not the current RequestMatcherInterface, otherwise it is a big BC break.

**Comment by Tobion** [comment]
> Regarding keeping RequestMatcherInterface, an interface using PSr-7 must be a different interface, not the current RequestMatcherInterface, otherwise it is a big BC break.

I think we need to discuss the goal of symfony 3 at next meeting. If the goal is that library authors can write code that is compatible with both symfony 2 and 3 at the same time, then we cannot do such a change indeed.
How about `PsrRequestMatcherInterface::matchPsrRequest`? Looks ugly, but ok.

> Do we really need to change the method name in UrlGeneratorInterface ?

No we do not need to as I explained. But then we keep the inconsistency `generate` vs `matchPsrRequest`.

**Comment by nicolas-grekas** [comment]
I think we can close here, to me, PSR-7 support is a very low priority and the benefit would be really thin.

**Comment by javiereguiluz** [comment]
I agree with Nicolas. Let's close. Thanks!

**Comment by Gemorroj** [comment]
@nicolas-grekas, @javiereguiluz 
In my case PSR-7 support would be useful for [RoadRunner](/spiral/roadrunner#example) routing
