### ISSUE TITLE
Use pattern matching to import resource 

### ISSUE THREAD

**Issue by kuldipem** [symfony/symfony#14731]
| Q             | A
| ------------- | ---
| Bug fix?      |  no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets |  no
| License       | MIT
| Doc PR        | no

I have following config file hierarchy i.e. using sonata  bundles 
* app
     * config
         * sonata (dir)
             - core.yml (config file for SonataCoreBundle )
             - admin.yml (config file for SonataAdminBundle )

in above case I can import resources in `config.yml` like 
```yaml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/* }
```
In this case, I have taken example of sonata bundles.

I am quite impress when I used node.js  package https://github.com/isaacs/node-glob, and I fill that symfony also have like these feature so I pulled a request.

**Comment by aitboudad** [comment]
Is going to be implemented in `2.8`, see #14700
