### ISSUE TITLE
[DependencyInjection] Incorrect order of prepending config from bundle extensions

### ISSUE THREAD

**Issue by kierate** [symfony/symfony#14748]
When using the `prependExtensionConfig()` across multiple bundles the final configuration is merged with an incorrect order.

For example let's say we want to set some value in `twig.globals` from FirstBundle and SecondBundle.

The FirstBundle extension would be something like this:
```php
class FirstBundleExtension extends Extension implements PrependExtensionInterface
{
    public function prepend(ContainerBuilder $container)
    {
        //...
        $config = array(
            'globals' => array(
                'my_config' => 'value from FirstBundle'
            )
        );
        $container->prependExtensionConfig('twig', $config);
    }
    //...
}
```
For SecondBundle this would be very similar:
```php
class SecondBundleExtension extends Extension implements PrependExtensionInterface
{
    public function prepend(ContainerBuilder $container)
    {
        //...
        $config = array(
            'globals' => array(
                'my_config' => 'value from SecondBundle'
            )
        );
        $container->prependExtensionConfig('twig', $config);
    }
    //...
}
```

In `AppKernel` the bundles are registered in order:

```php
$bundles = [
    //...
    new FirstBundle\FirstBundle(),
    new SecondBundle\SecondBundle(),
];
```

With all of that in place I would expect to use the `{{ my_config }}` value in Twig and get `value from SecondBundle`. Currently however I am getting `value from FirstBundle`. This happens because SecondBundle config gets prepended to the very beginning, but then upon merge gets overwritten by config set earlier in FirstBundle.

This affects all versions since 2.2.

**Comment by patrick-mcdougle** [comment]
Perhaps I don't fully understand your use case, but I'm not sure that this is the use case that `prepend()` is supposed to be for. As far as I can tell you're not doing anything that can't be done in a normal `load()` of a twig extension. See http://symfony.com/doc/current/cookbook/templating/twig_extension.html for more information.

**Comment by kierate** [comment]
The twig config was just an example here. This is more of a general problem when using `prependExtensionConfig()` (as described in http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html) in cases where multiple bundles prepend config for some other bundle.

To clarify my use case - I have two bundles that get enabled conditaionally (sometimes they're both there, sometimes there is just one of them), and both of them set config for my third bundle (BaseappBundle) which is always there.
I would like the order in which the bundles are registered in AppKernel to determine the final configuration for the application (so essentially for BaseappBundle in this case).

**Comment by pkamps** [comment]
The function is called 'prepend' so I guess it makes sense.

Still, I also have a problem with that feature. The order of how you register the bundles definitely affects the configuration. For the function 'prepend' you want to register more specific bundles before more generic bundles.
It's the opposite for other features, for example the 'MyBundleExtension::load' function.

Maybe there should be a function 'appendExtensionConfig'?

**Comment by roberto910907** [comment]
> If there is more than one bundle that prepends the same extension and defines the same key, the bundle that is registered first will take priority: next bundles won't override this specific config setting.

http://symfony.com/doc/3.4/bundles/prepend_extension.html#more-than-one-bundle-using-prependextensioninterface
