### ISSUE TITLE
symfony-var-dir no longer working

### ISSUE THREAD

**Issue by fbourigault** [symfony/symfony#14753]
In a project of mine, the symfony-var-dir is no longer recognized since I a dded AppKernel autoloading through the files mode.

I ran `git bissect` and the first bad commit is ouverture/ouverture@6d02b69d82b34e9fa687d5f1dae9ee62f4c26c17

To detect the error, I just noticed the existence of `app/cache` being not tracked by git.

I don't know why this change is breaking the `symfony-var-dir` and I'm requesting help!

Regards,
Fabien

**Comment by iltar** [comment]
@fbourigault My guess is that composer autoloads the file too early, at least compared to manually loading it. I hope this helps you debug.

**Comment by fbourigault** [comment]
@iltar thanks but I think I need to know how `symfony-var-dir` works to understand what's happening.

Does someone know how the `symfony-var-dir` is used by symfony framework (or at least where is the code which use it)?

**Comment by Tobion** [comment]
Please ask support questions on the mailing list:  http://symfony.com/mailing_lists

**Comment by smoench** [comment]
@fbourigault if the var dir doesn't exists the old behavior is being used

**Comment by fbourigault** [comment]
My var dir exists and is created as first task in post-install-cmd and post-update-cmd.

**Comment by jvasseur** [comment]
symfony-var-dir works by overriding part of the HttpKernel code dumped in bootstrap.php.cache

I guess your change made composer load the real version of the HttpKernel before the one in bootstrap.php.cache

**Comment by iltar** [comment]
@jvasseur That's what I more or less intended with my reply. Composer autoloads the app kernel before the require of the bootstrap.

**Comment by stof** [comment]
The overwriting of the methods in the bootstrap file is really a hack IMO, and we really need to find a better way to handle this before Symfony 3.

Btw, using the Symfony 3 directory structure is not the recommended way currently. We still need to improve some things.

But if you really want to use it, I suggest you to overwrite the methods explicitly in your AppKernel to be sure to have the right folders all the time.

**Comment by fbourigault** [comment]
Thank you for help. I will override methods like I just read it in https://www.pmg.com/blog/symfony-from-scratch/
