### ISSUE TITLE
Error parsing YAML on Validation Constraints

### ISSUE THREAD

**Issue by yorkknew** [symfony/symfony#14755]
Hello,

I don't know if it's normal or not but i have an error when i began my translate with {{ limit }} / {{ value}} and may be others.

Examples : 

// Resources\translations\validators.en.yml

valid: {{ value }} is not a valid email. -> Error parsing YAML, invalid file...

valid: '{{ value }}' is not a valid email. -> Error parsing YAML, invalid file...

valid: "{{ value }}" is not a valid email. -> Error parsing YAML, invalid file...

valid: Blablabla "{{ value }}" is not a valid email. -> OK!

I use SF 2.6.7

thank you.

**Comment by Tobion** [comment]
`{}` is used for inline maps. So you have to make the whole line a string. See also the yaml spec. Also please ask support questions on the mailing list: http://symfony.com/mailing_lists
