### ISSUE TITLE
Values not being written to array from Dom Crawler

### ISSUE THREAD

**Issue by phpmypython** [symfony/symfony#14767]
Im crawling a page with a table and im trying to setup an array that gets a new key set for each th.
This is the code i have.
~~~php
use Goutte\Client;
$client = new Client();

$crawler = $client->request('GET', 'http://ctj.org/corporatetaxdodgers/tax-dodgers.php?id=6');

$th = $crawler->filter('tr');
$data = array();
$th->reduce(function(\Symfony\Component\DomCrawler\Crawler $node, $i) use($data){
  if ($i === 0) {
    $node->filter('th')->each(function ($header){
      $data[$header->text()] = array();
    });
  }
});
var_dump($data);
~~~

When i run this ```$data``` is always empty. but if i ```print $header->text()``` i get the data just fine. 
Is there something i'm missing?

**Comment by dosten** [comment]
Please use the mailing list. Use `Crawler::each()`

**Comment by phpmypython** [comment]
What mailing list are you referring to? Also can you give some more context on the usage of ```Crawler::each```?

**Comment by dosten** [comment]
http://symfony.com/mailing-lists

I'm thinking in something like this:

```php
$th = $crawler->filter('tr:first-child th');

$keys = $th->each(function ($node, $i) {
	return $node->text();
});

$data = array_combine($keys, array_fill(0, count($keys), []));

var_dump($data);
```

**Comment by phpmypython** [comment]
That worked i appreciate your help thank you!!!
