### ISSUE TITLE
Inheritable permissions and three-state permission mask 

### ISSUE THREAD

**Issue by petrhanak** [symfony/symfony#14769]
i want to differentiate permisssions for only one domain object

so there are basically two states:
- allow all except one
- deny all except one

unfortunately symfony doesn't see difference between not setting permission and setting false

there should be easier way to allowing/denying one object without setting object-scope permissions for all of them, it's a bit overkill, right?

**Comment by javiereguiluz** [comment]
I'm sorry but I must close this proposal as "won't fix" because it didn't receive any feedback in more than two years. I hope you understand it and I wish you found an alternative solution for this. Thanks!
