### ISSUE TITLE
Exception on ObjectIdentity's constructor with $identifier == 0 

### ISSUE THREAD

**Issue by chielorenz** [symfony/symfony#14775]
Hi, working with ACL, calling:

```php
ObjectIdentity::fromDomainObject($obj);
```

with ``$obj``'s id set to 0, I get:

```
InvalidDomainObjectException: $identifier cannot be empty
```

This exception comes from the ``ObjectIdentity``'s construction where ``empty($identifier)`` is ``TRUE`` when ``$identifier`` is 0:

```php
final class ObjectIdentity implements ObjectIdentityInterface
{
    ...
    public function __construct($identifier, $type)
    {
        if (empty($identifier)) {
            throw new \InvalidArgumentException('$identifier cannot be empty.');
        }
        ...
    }
    ...
}
```

If ``$obj``'s id != 0 all works just fine.
Am I missing something obvious? Perhaps it should be ``!isset($identifier)``?

I'm using Symfony v2.6.5 and PHP v5.6.2, thanks.

**Comment by jakzal** [comment]
> Perhaps it should be !isset($identifier)?

This wouldn't work. You'd need to do something like:

```php
if (empty($identifier) && '0' !== (string) $identifier) {
    // ...
}
```

Feel free to submit a pull request. I think this is a valid use case, even though I'd rather avoid having an object with 0 as an id.

Btw, the `$identifier` is expected to be a string according to the docblock. Not sure if this is correct.

**Comment by chielorenz** [comment]
Why avoid having an object with 0 as an id? Doctrine is setting the first object's id to 0.

**Comment by iltar** [comment]
Doctrine doesn't do that by default.

**Comment by chielorenz** [comment]
You are right about the database, but why should I start the id from 1? Is starting from 0 a bad practice in some way?

**Comment by iltar** [comment]
I don't know if it's a bad practice because in theory you shouldn't be working with ids directly. However, a lot of checks (loose type checks I must add), compare 0 to false. Hence `if ($id)` would fail. I think it's more of an unwritten rule.

**Comment by xabbuh** [comment]
Since `$identifier` is a string, `'' === $identifier` would be sufficient, wouldn't it?

**Comment by jakzal** [comment]
> Since $identifier is a string, '' === $identifier would be sufficient, wouldn't it?

I'm not confident it'll always be a string, even though the docblock says it expects a string. [ObjectIdentity::fromDomainObject](https://github.com/symfony/security-acl/blob/master/Domain/ObjectIdentity.php#L69) calls `getId()` on the domain object. Most of the time it'll actually be an integer.

**Comment by xabbuh** [comment]
> I'm not confident it'll always be a string, even though the docblock says it expects a string. ObjectIdentity::fromDomainObject calls getId() on the domain object. Most of the time it'll actually be an integer.

Indeed, imho `fromDomainObject()` should cast the value returned by `getId()` to string then (see #14807).
