### ISSUE TITLE
Where is the login_check controller and can be override ?

### ISSUE THREAD

**Issue by FR33D0M5K135** [symfony/symfony#14774]
Hi everyone 

I open an issue to know if is possible to override the login_check in Symphony. 
Indeed, I would like allow to my users to connect with several emails. 
Could you please tell me where the login_check is and what I have to override. 

To information I use FosUserBundle

Thanks !

**Comment by dosten** [comment]
Please use the mailing lists https://symfony.com/mailing-lists

**Comment by FR33D0M5K135** [comment]
Done https://groups.google.com/forum/?hl=en#!topic/symfony2/YMbsXb3YVuI
Do I have to closed this issue ?

**Comment by dosten** [comment]
Yes please
