### ISSUE TITLE
[HttpFoundation] Memcache Set method needs expire time in seconds, no timestamp

### ISSUE THREAD

**Issue by imangh** [symfony/symfony#14789]
[MemcacheSessionHandler] in write method the last parameter of **memcache->set** is **time()+ TTL** but it should be only TTL because memcache Set method expect TTL in seconds and not expecting expiring time in Unix Timestamp.

[MemcacheSessionHandler]: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcacheSessionHandler.php#L90

**Comment by Tobion** [comment]
> expire
Expiration time of the item. If it's equal to zero, the item will never expire. You can also use Unix timestamp or a number of seconds starting from current time, but in the latter case the number of seconds may not exceed 2592000 (30 days).

http://php.net/manual/de/memcache.set.php

So either you are wrong or the documentation.

**Comment by imangh** [comment]
Yes, You are right and I don't have problem on linux but in windows memcache set do not work with  time() + TTL but work correctly only TTL so if both works it would be good Idea to change it to the simpler way.

**Comment by Tobion** [comment]
But seconds are limited to 2592000. So a timestamp is the better approach. If there is a bug on Memeche Windows please report it there.
