### ISSUE TITLE
Latest Composer Update for 2.6.9 caused site crash

### ISSUE THREAD

**Issue by Don87** [symfony/symfony#14787]
Hi, total novice here so forgive me if I am not reporting this is the right place.

I just updated my Symfony install to latest 2.6.9 and got the dreaded blank white screen, no errors thrown in prod.log but dev environment works well.

Error thrown in Apache log as follows
[Fri May 29 22:29:27.767122 2015] [:error] [pid 13195] [client 127.0.0.1:38753] PHP Warning:  require(/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/SensioFrameworkExtraBundle.php): failed to open stream: No such file or directory in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:29:27.767277 2015] [:error] [pid 13195] [client 127.0.0.1:38753] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/SensioFrameworkExtraBundle.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:29:43.135377 2015] [:error] [pid 13494] [client 127.0.0.1:38755] PHP Warning:  require(/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/SensioFrameworkExtraBundle.php): failed to open stream: No such file or directory in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:29:43.135662 2015] [:error] [pid 13494] [client 127.0.0.1:38755] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/SensioFrameworkExtraBundle.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:34:29.664431 2015] [:error] [pid 13462] [client 127.0.0.1:38781] PHP Warning:  require(/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php): failed to open stream: No such file or directory in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:34:29.665696 2015] [:error] [pid 13462] [client 127.0.0.1:38781] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:37:48.761479 2015] [:error] [pid 13767] [client 127.0.0.1:38791] PHP Warning:  require(/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php): failed to open stream: No such file or directory in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:37:48.762552 2015] [:error] [pid 13767] [client 127.0.0.1:38791] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:39:28.685986 2015] [:error] [pid 31823] [client 127.0.0.1:38793] PHP Warning:  require(/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php): failed to open stream: No such file or directory in /var/www/app/bootstrap.php.cache on line 2758
[Fri May 29 22:39:28.686553 2015] [:error] [pid 31823] [client 127.0.0.1:38793] PHP Fatal error:  require(): Failed opening required '/var/www/vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/EventListener/ControllerListener.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app/bootstrap.php.cache on line 2758

Struggled with this for a few minutes including deleting the /var/www/vendor/sensio folder then running composer install dint work so did it again and run composer update also dint work. Site was working perfect prior to update so what I did was manually change entry in composer.json for entry

......

from

"sensio/framework-extra-bundle": "~3.0",

to

"sensio/framework-extra-bundle": "3.0.7",
.....

i.e the previous version then composer update and everything worked again.

Don't know if its just my issue or a serious problem my site is working again so I do not need urgent help or anything just wanted to put this out there in case anyone else encounters the same issue.

**Comment by xabbuh** [comment]
I think that is related to sensiolabs/SensioFrameworkExtraBundle#357. You could manually remove the `app/bootstrap.php.cache` file and run `composer update` again.

Anyway, this is not a Symfony issue, but is related to the SensioFrameworkExtraBundle. So I'm gonna close here.

**Comment by gabriperego** [comment]
Just as a reference: APC is the reason of the issue on my side. Solved restarting apache.

**Comment by Don87** [comment]
@gabriperego 
Brilliant, thanks! I always wondered why I could update to the latest version on my Windows development machines but not on my production server. So I quickly tried your solution and I can confirm that this solves it. Its always nice to use the latest versions of all software so thanks. Only downside is that I use apc to save a lot of user data for example, I use it to convert FOSMessageBundle into a live chat solution by appending the users cached data every so seconds instead of updating MySQL, restarting Apache clears all this data. Anyway, I would probably upgrade to memcache or redis when I can afford to. Once again thanks for the solution, will keep this in mind for next time.
