### ISSUE TITLE
Move debug:container command from FrameworkBundle to DependencyInjection component

### ISSUE THREAD

**Issue by kherge** [symfony/symfony#14783]
I heavily rely on the **DepedencyInjection** component for one of my projects. A feature that I found to be extremely useful is the `debug:container` command from the **FrameworkBundle**. It would hugely cut down on the number of dependencies that Composer installs if this command were moved to the component instead of living in the bundle.

There is a precedence where a component provides integration with another component. The **EventDispatcher** component provides a compiler pass to register listeners and subscribers with the **DependencyInjection** component. It would make sense for the **DependencyInjection** component to provide a command that allows for debugging of a service container using the **Console** component.

To prevent any BC breaks, something like this could be done:

- Move `Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand` to `Symfony\Component\DependencyInjection\Command\ContainerDebugCommand`.
- Create a new `Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand` class that extends the one moved to `Symfony\Component\DependencyInjection\Command\ContainerDebugCommand`.

**Comment by GromNaN** [comment]
The `Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand` depends on `Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand` that depends on `Symfony\Bundle\FrameworkBundle\Console\Application` which depends on `Symfony\Component\HttpKernel\Kernel`.

To make the command `debug:container` available for every project that use only the DI and the Console components, that will require a larger refactoring that just renaming a class.

How are you using it if you don't use Symfony bundles ?

**Comment by kherge** [comment]
I re-implemented the `getContainerBuilder()` method, which seems to be the only dependency to the bundle. My implementation uses a helper that returns a container builder.

**Comment by javiereguiluz** [comment]
@kherge although your proposal is not wrong at all, I'm closing this as "won't fix" because of what @GromNaN explained. This change would require a big refactoring and it would provide little value to most of our users, because they already use the FrameworkBundle. Thanks for understanding it.
