### ISSUE TITLE
[Security] Custom RememberMeServices "template"

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#14780]
I'd like to create a custom [`RememberMeServicesInterface`](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Http/RememberMe/RememberMeServicesInterface.php) implementation, extending [`AbstractRememberMeServices`](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Http/RememberMe/AbstractRememberMeServices.php).

The problem is that [`RememberMeFactory` chooses between 2 hardcoded implementations](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php#L42) ("templates") and I would have to override one of them. 

That would be wrong because it would be:
- bad naming (why would I "reuse" i.e. "simplehash" template if my implementation is different?),
- not possible to use overridden implementation anymore.

How about a new config key in `remember_me` (how about just `template`?), so that I could point to a custom implementation? I can make a PR.

**Comment by MacDada** [comment]
If I were to make a PR, it would be nice if https://github.com/symfony/symfony/pull/14779 was merged first ;-)

**Comment by weaverryan** [comment]
@MacDada That makes good sense to me - add the new option, but keep the exact same old behavior if the option isn't specified. My vote for the name is `remember_me_services_id`. `template` is a bit abstract - it's kind of an implementation detail that we'll use your remember me service as a "template" internally. Anyways, better to just pick whatever you want, and we can discuss it further on the PR.

Cheers!

**Comment by javiereguiluz** [comment]
Let's close this feature request as "won't fix". It was asked for 4 years ago and didn't gain any traction from the community and we didn't receive similar requests in all this time. Thanks!
