### ISSUE TITLE
DI Container tries to evaluate percent signs during compilation.. but I don't want the parameter features

### ISSUE THREAD

**Issue by blockjon** [symfony/symfony#14784]
I'm trying to use the DI Container's ability to compile(). I have a service definition in which there's a class Foo which accepts an array into it's __construct(). The array has a string with percent signs in it. I do not want those percent signs to be interpolated but the parameter features are trying to treat the text between percent signs as a parameter.

To simply my question, assume I have this array which I want to send to a service:

```
array('a%b%c' => 'd%e%f');
```
How can I pass that into my service definition *without* the di container trying to resolve *b* and *e* as parameters?

I noticed if I use two percent signs in a row, that gets me the results I'm looking for. Is there a handy function which I can give my array to that will traverse through my entire array and double all of the percent signs?

**Comment by phansys** [comment]
@blockjon, that's the expected behavior [according to doc](http://symfony.com/doc/current/components/dependency_injection/parameters.html#parameters-in-configuration-files):
>The percent sign inside a parameter or argument, as part of the string, must be escaped with another percent sign

And, AFAIK, there is no available method to achieve what you want.

**Comment by blockjon** [comment]
Ok... For now my plan is just to double escape all of the parenthesis... something like this is what I'm thinking:
```

/**
 * Recursively will doubles any percent char found in strings within the array passed in.

 * @param $array
 * @return mixed
 */
function arrayPercentEscape($array)
{
    $escaper = function (&$value) {
        if (is_string($value)) {
            $value = str_replace('%', '%%', $value);
        }
    };
    array_walk_recursive($array, $escaper);
    return $array;
}
```
