### ISSUE TITLE
Symfony 2.6.8 Always Starting Session

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#14792]
I'm trying to remove all usages of sessions in my application on public pages in order to take advantage of caching with Varnish.  However, it seems that Symfony is setting a PHPSESSID even when I never initiate a session.  I checked the obvious things mentioned on this page: http://symfony.com/doc/current/cookbook/session/avoid_session_start.html

**Comment by patrick-mcdougle** [comment]
Another place to check is your php.ini. Is it possible that session.auto_start is being set somewhere?

**Comment by stevenmusumeche** [comment]
The issue was in am embedded controller accessing the session.  Not a symfony problem.
