### ISSUE TITLE
Console command doctrine:generate:entities crates whitespaces.

### ISSUE THREAD

**Issue by codeName007** [symfony/symfony#14794]
Steps to reproduce bug:

1) Installing the Symfony Installer:
````
sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
sudo chmod a+x /usr/local/bin/symfony
````
2) Creating the Symfony Application:
````
symfony new bug_justification
````
3) Create product entity:
````
cd bug_justification/
mkdir src/AppBundle/Entity
touch src/AppBundle/Entity/Product.php
````
4) Add next code to entity:
````php
<?php

namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
* @ORM\Entity(repositoryClass="AppBundle\Entity\ProductRepository")
* @ORM\Table(name="product")
*/
class Product
{
    /**
    * @ORM\Column(type="integer")
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;
    /**
    * @ORM\Column(type="string", length=100)
    */
    protected $name;
    /**
    * @ORM\Column(type="decimal", scale=2)
    */
    protected $price;
    /**
    * @ORM\Column(type="text")
    */
    protected $description;
}
````
5) Run console command:
````
php app/console doctrine:generate:entities AppBundle/Entity/Product
````
As result doctrine update entity file with additional code, and add methods like: getName, getPrice etc and this methods will have own phpDoc with whitespaces. And when you add this entity to git and try to check it with: `git diff --cached --check src/AppBundle/Entity/Product.php` you will receive something like:

![001](https://cloud.githubusercontent.com/assets/5052324/7899577/1147e804-0731-11e5-88c9-4ecf6908245c.png)

**Comment by jrobeson** [comment]
you need to file this bug in the SensioGeneratorBundle repository.

**Comment by codeName007** [comment]
Ok, thank you!

**Comment by phansys** [comment]
```doctrine:generate:entities``` is inside [doctrine/doctrine-bundle](https://github.com/doctrine/DoctrineBundle/blob/master/Command/GenerateEntitiesDoctrineCommand.php#L30).

**Comment by jrobeson** [comment]
ah, you're right. sorry @codeName007

**Comment by codeName007** [comment]
it's ok)
