### ISSUE TITLE
upgrade to 2.7.0 , test fails because of internal deprecation messages

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#14791]
Now when I run my test it stops at the first test with

```
1) MVMS\ApiBundle\Tests\Controller\AnalystControllerTest::testGetAnalystsWithoutSortReturnBadParameter
Symfony\Component\DependencyInjection\Definition::setFactoryMethod(createConnection) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead.

/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php:137
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:153
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:119
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:58
/vagrant/mvms/vendor/doctrine/doctrine-bundle/Doctrine/Bundle/DoctrineBundle/DependencyInjection/DoctrineExtension.php:68
/vagrant/mvms/vendor/doctrine/doctrine-bundle/Doctrine/Bundle/DoctrineBundle/DependencyInjection/DoctrineExtension.php:47
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:55
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:546
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:138
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:141
/vagrant/mvms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php:33
/vagrant/mvms/src/MVMS/ApiBundle/Tests/Controller/AnalystControllerTest.php:28
```

what I've tried so far:

  * make sure bootstrap.cache contains the ~E_USER_DEPRECATED
  * installed https://github.com/symfony/phpunit-bridge 
  * done ` export SYMFONY__DEPRECATIONS_HELPER=weak ` and ` export SYMFONY_DEPRECATIONS_HELPER=weak`

**Comment by uirapuru** [comment]
+1 same here

**Comment by SoboLAN** [comment]
If you have a service (or services) definition that looks like this:

```yaml
services:
    myservice:
        class:          MyClass
        factory_class:  MyClassFactory
        factory_method: createMyClass
```

Then that's what's causing the error you get.

Replace it with:

```yaml
services:
    myservice:
        class:     MyClass
        factory:  [MyClassFactory, createMyClass]
```

And the error will go away.

There was a discussion somewhere around here (which I can't find at the moment) where it was suggested to replace that error message with something more descriptive, so that developers know why it appears. As it turns out, it's worth discussing...

**Comment by xabbuh** [comment]
> There was a discussion somewhere around here (which I can't find at the moment) where it was suggested to replace that error message with something more descriptive, so that developers know why it appears. As it turns out, it's worth discussing...

see #14687 and #14798

**Comment by allan-simon** [comment]
thanks a lot , i'm going to try that and will update you.

**Comment by allan-simon** [comment]
I've replaced them all and still the same error

**Comment by SoboLAN** [comment]
After replacing, did you run `app/console cache:clear` ?

It shouldn't make a difference in development environments, but you never know....

**Comment by allan-simon** [comment]
@SoboLAN  I did,  that's how i spotted #14811 (which was actually my problem) , is there any possibility of some bundle calling setFactoryMethod or something like that ? (I use quite some bundles, though nothing too exotic)

**Comment by xabbuh** [comment]
@allan-simon The deprecation messages would be triggered by third party bundles that you use too. You could manually apply the changes proposed in #14798 to get more detailed messages about where the error was triggered.

**Comment by allan-simon** [comment]
@xabbuh , thank you I'm going to apply your patch on my local version

**Comment by althaus** [comment]
@SoboLAN Many thanks! That solved my issue with the KnpMenuBundle. :+1:

**Comment by althaus** [comment]
@allan-simon 

>is there any possibility of some bundle calling setFactoryMethod or something like that ?
I had such an issue with the ExerciseHTMLPurifierBundle as the method was used in the Extension class. So yes, bundles can do such things. The bundle needs to be updated like this:

**Comment by allan-simon** [comment]
@althaus , oh great, thanks for the tip

**Comment by pierrre** [comment]
The french documentation is not up to date.
http://symfony.com/fr/doc/current/components/dependency_injection/factories.html
It uses the old syntax:
```yaml
services:
    newsletter_manager:
        class:          "%newsletter_manager.class%"
        factory_class:  "%newsletter_factory.class%"
        factory_method: get
```

**Comment by fabpot** [comment]
@pierre Don't use the French docs.

**Comment by pierrre** [comment]
@fabpot OK, thanks!

**Comment by pierrre** [comment]
I don't see anything about this new syntax in the changelog or the "upgrade" documentation.
Am i missing something?

**Comment by xabbuh** [comment]
@pierrre You can take a look at http://symfony.com/doc/current/components/dependency_injection/factories.html.
