### ISSUE TITLE
[Process] Start method returns null

### ISSUE THREAD

**Issue by jagandecapri** [symfony/symfony#14796]
In the documentation, [start](http://api.symfony.com/2.7/Symfony/Component/Process/Process.html#method_start) returns the [Process](http://api.symfony.com/2.7/Symfony/Component/Process/Process.html).

However, it returns null instead.

Unit test
````php
    public function testStartMethodReturnsProcessInstance()
    {
        $process = $this->getProcess('echo foo');
        $process = $process->start();
        $this->assertInstanceOf('Symfony\Component\Process\Process', $process);
    }
````

**Comment by jagandecapri** [comment]
Submitted [patch](https://github.com/symfony/symfony/pull/14797)

**Comment by xabbuh** [comment]
This actually looks like an error in the API documentation generation to me ([in the 2.3 branch](http://api.symfony.com/2.3/Symfony/Component/Process/Process.html#method_start) this is generated properly).

@fabpot Any idea what's going wrong here?

**Comment by jagandecapri** [comment]
So, it's not supposed to return the process itself?

**Comment by fabpot** [comment]
This is indeed an API doc issue, not a problem in the code. See FriendsOfPHP/Sami#168
