### ISSUE TITLE
[DX][Templating] Include file locations in "Template could not be found" exception

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#14806]
When a template could not be found, the message currently only shows the locator that couldn't be located:

 > Unable to find template "default/index.html.twig".

It would be much nicier if it shows you where it did search for this locator, so people know where to put their files. E.g:

 > Unable to find template "default/index.html.twig" (tried: "app/Resources/default/index.html.twig")

 > Unable to find template "AcmeDemoBundle::index.html.twig" (tried: "app/Resources/AcmeDemoBundle/views/index.html.twig", "src/OverridenDemoBundle/Resources/views/index.html.twig", "vendor/acme/demo-bundle/Resources/views/index.html.twig")

**Comment by patrick-mcdougle** [comment]
I seem to remember this being a feature in the past, where'd it go?
