### ISSUE TITLE
[DX] How to create fake UploadedFile for functionnal test 

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony#14805]
Imagine I have a  REST API with a call for user to upload video, i don't want the file to be over 100mo 

How do I test that this limit is correctly applied without adding in the repository a file of 100mo , when checking the documentation of http://api.symfony.com/2.6/Symfony/Component/HttpFoundation/File/UploadedFile.html 

there's a mysterious parameter "test = false"  ,  which is explained nowhere which use it has,  I was thinking at first it was to be used in conjunction with an explicit size, an explicit mime-type etc.  to create a fake uploaded file.

So I think it would be great if 

  * that parameter test was explained more
  * if some hint was given to developer on how to create "fake files"  (I'm going to make some research if it does not exist , but the best would be something to create on the fly some fake file with a set of given property)

**Comment by jakzal** [comment]
> that parameter test was explained more

It is explained quite well in the property docblock:

```php
    /**
     * Whether the test mode is activated.
     *
     * Local files are used in test mode hence the code should not enforce HTTP uploads.
     *
     * @var bool
     */
    private $test = false;
```

> if some hint was given to developer on how to create "fake files"

It is explained in the [Functional tests docs](http://symfony.com/doc/current/book/testing.html#functional-tests). If there's anything missing in there, feel free to submit a PR/issue to the [docs repo](https://github.com/symfony/symfony-docs/).

**Comment by allan-simon** [comment]
well for the docblock, you understand that it defeat the purpose if as non-developer of symfony internals i have to discard the html doc to look into the code itself. 

for the doc, thanks to pointing the doc repo, I've created an issue

**Comment by dunglas** [comment]
Here is a working snippet: https://github.com/symfony/psr-http-message-bridge/blob/master/Tests/Factory/DiactorosFactoryTest.php#L114-L120

**Comment by allan-simon** [comment]
@dunglas , thanks,  yes good idea to use a temporary file to have an existing file path.
