### ISSUE TITLE
[Templating] PHP's app template location is invalid

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#14804]
Using `$this->render('default/index.html.php')` loads `app/Resources/default/index.html.php` instead of `app/Resources/views/default/index.html.php`.

*This bug was originally reported by @jxmallet in https://github.com/symfony/symfony-docs/pull/5318*

**Comment by weaverryan** [comment]
I can confirm this. Make sure you have the `php` engine enabled when trying it (if you don't, I think it uses the Twig engine, and the path works fine).

**Comment by jakzal** [comment]
Tests for the TemplateNameParser contain some cases which I'm not totally sure how should be handled. @weaverryan  @WouterJ could you confirm the following rules?
* `$this->render('/path/to/section/name.php')` => /path/to/section/name.php
* `$this->render('name.php')` => views/name.php
* `$this->render('name')` => views/name

**Comment by weaverryan** [comment]
@jakzal I'm not familiar with the first rule - the absolute `/path/to` - but that certainly makes sense.

But the second 2 look correct to me (assuming `views/name.php` means `app/Resources/views/name.php`). If these are in the test, and the test is passing (which of course it is), then it looks like there *isn't* a bug (but I know from trying it myself that there is).

**Comment by jakzal** [comment]
Sorry, I was writing this up in a hurry and didn't explain it very well. 

Currently for all three mentioned templates, the path is resolved as is (name.php => name.php). I propose to change this to fix this bug, as I expect these test cases are incorrect. They were introduced in https://github.com/symfony/symfony/pull/12894/files#diff-ee3107cee707eac6126b48a367e831e9R67.
