### ISSUE TITLE
How can I ignore deprecated messages in log related to 3rd party bundles

### ISSUE THREAD

**Issue by sivolobov** [symfony/symfony#14814]
After updating Symfony to 2.7 version it started to log DEPRECATED notices in the log. It is a good thing. And I want use the whole power of this feature.

But now it is very hard to find any deprecated notice related to my own bundle. Many of deprecations are from vendor folder. And I want to completely ignore vendor folder in this case. Then I will see messages related to my bundle only.

![2015-06-01 17 11 27](https://cloud.githubusercontent.com/assets/1647174/7911824/39115fa0-087b-11e5-962d-cdb886366f5f.png)

The question on SO: http://stackoverflow.com/q/30572234/2261177

**Comment by fabpot** [comment]
The best is to report the problem to the third-party bundle so that they can fix them ASAP.

I've just released new versions of the distribution bundle to remove usage of the deprecated `pattern` item.
