### ISSUE TITLE
[2.7][Asset] CDN & BasePath

### ISSUE THREAD

**Issue by sebastianblum** [symfony/symfony#14818]
Hello!

My plan is to use a CDN with //cdn.domain.tld and I want to use several packages for static assets, javascripts and stylesheets with individual prefix (base_path) and different version.

	framework:
	    assets:
	        base_urls: [%cdn.url%]
	        packages:
	            assets:
	                base_path: /assets/
	                version: v15
	            bower:
	                base_path: /bower_components/

I will get this exception:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L610

	if ($basePath && $baseUrls) {
        throw new \LogicException('An asset package cannot have base URLs and base paths.');
    }

Can someone explain why this is forbidden?

Thank you very much

**Comment by fabpot** [comment]
framework:
    assets:
        packages:
            assets:
                base_url: %cdn.url%/assets/
                version: v15
            bower:
                base_url: %cdn.url%/bower_components/

**Comment by sebastianblum** [comment]
Thank you very much @fabpot
