### ISSUE TITLE
upgrade 2.3 to 2.7

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#14817]
Hello,

is it possible to upgrade a project in 2.3 to 2.7?

if yes, How do I change my composer.json to install 2.7 with doctrine,twig..etc.

thank you for your help

**Comment by Tobion** [comment]
Yes it's possible. See https://github.com/symfony/symfony-standard/compare/2.3...2.7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Please use the mailing list for support questions next time. http://symfony.com/mailing_lists
