### ISSUE TITLE
Twig starts escaping '#' in CSS

### ISSUE THREAD

**Issue by mtijink** [symfony/symfony#14824]
After the update to symfony 2.7, twig started escaping CSS strings with a '#'. This breaks our website, which uses this to inject theme colors in the CSS.

Example:
{% set test = '#abc' %}
"{{ test }}"

Expected result (Symfony 2.6.7):
"#abc"

Result (Symfony 2.7):
"\23 abc"

**Comment by mtijink** [comment]
This might be related to #13401.

Is there some way to disable this on a filetype basis?

**Comment by Tobion** [comment]
Please have a look at the upgrade file when upgrading: #14666

**Comment by mtijink** [comment]
Sorry, I looked at the wrong upgrade file (the blog post links to the BETA-1 version of the UPGRADE-2.7.md)
