### ISSUE TITLE
JsonResponse hard to extend for purpose of overriding encoding defaults

### ISSUE THREAD

**Issue by Incognito** [symfony/symfony#14836]
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/JsonResponse.php#L38

There doesn't appear to be a way to override the default encoding through the constructor or inheritance.

Any objections to a PR where I move the flags into a protected property?

**Comment by hacfi** [comment]
With #9915 you can extend the JsonResponse, overwrite __construct, call the parent and then `$this-> setEncodingOptions(...);`

**Comment by Incognito** [comment]
I haven't run the code yet, but that appears to be destructive at first glance:

1. set encoding A
2. encodedA(data) == stored
3. Modify encoding to be value B
4. Decode without awareness of special encoding A rules.
5. Redo encoding with encoding type B
