### ISSUE TITLE
[RFC] Add 'skip_keys' option to LoaderInterface load method?

### ISSUE THREAD

**Issue by gonzalovilaseca** [symfony/symfony#14830]
In our scenario we are importing a bundle's ``.yml`` configuration file with the ``imports`` statement. 
We need to overwrite a config key in this imported file but we can not do it because it has the ``cannotBeOverwritten`` restriction.
So it would be great to have something like:
```
imports:
     - { resource: @SomeBundle/Resources/config/app/main.yml, skip_keys: [fos_rest.format_listener.rules]}
```
So that the file is imported, but the specified keys are skipped.
If this is something that can be useful I would do a PR with the needed changes.

**Comment by Tobion** [comment]
:-1: too edge case for core

**Comment by gonzalovilaseca** [comment]
ok, np!
