### ISSUE TITLE
[Form] How to detect null value from model in checkbox type

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#14839]
I've created a checkbox extension type that assigns a set of options to the form view on `finishView()` method. However, if the model data is `null`, I want to set an attribute like this:

    if (<condition>) {
        $formView->vars['attr']['data-indeterminate'] = "true"
    }

Which condition should I write to accomplish this goal?

**Comment by jakzal** [comment]
Please ask support questions on the [mailing list](http://symfony.com/mailing-lists), or one of the [IRC channels](http://symfony.com/irc).
