### ISSUE TITLE
[DependencyInjection] Configurator callable not resolved

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#14834]
I'm not entirely sure whether this is a bug. I'm trying to build a container manually with FrameworkBundle, TwigBundle and another bundle loaded with 2.7:
https://github.com/puli/symfony-bundle/blob/master/Tests/ContainerTest.php#L76

Upon running the test suite, the following error happens:

> 1) Puli\SymfonyBundle\Tests\ContainerTest::testTwigContainer
> Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The configure callable for class "Twig_Environment" is not a callable.
> 
> /home/bernhard/Entwicklung/Web/puli/symfony-bundle/vendor/symfony/dependency-injection/ContainerBuilder.php:989
> /home/bernhard/Entwicklung/Web/puli/symfony-bundle/vendor/symfony/dependency-injection/ContainerBuilder.php:490
> /home/bernhard/Entwicklung/Web/puli/symfony-bundle/Tests/ContainerTest.php:67

Apparently, the `Definition` object in the `[Definition, 'configure']` callable is not resolved prior to checking whether the callable is valid. I don't understand where this should be happening. Is this a bug or a mistake on my side?

To reproduce, you can clone https://github.com/puli/symfony-bundle and run `phpunit`.

**Comment by stof** [comment]
This is a missing change in https://github.com/symfony/symfony/pull/14030 when allowing to inline configurator services in 2.7. The case of Definition objects needs to be handled on https://github.com/symfony/symfony/blob/1dbf67ed667c99f0d08ad61bf2bf4d2ec9fbada1/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L985 too (it is handled properly for dumped containers, but the ContainerBuilder instantiation misses it)

**Comment by webmozart** [comment]
Awesome, thanks @stof. That's what I guessed. Fix here: #14835
