### ISSUE TITLE
[PHPUNIT-BRIDGE] Does not work with phpunit installed as dependency

### ISSUE THREAD

**Issue by matejvelikonja** [symfony/symfony#14849]
In most of our projects we use phpunit installed as project dev dependency, and we have to run `bin/phpunit`. The problem than occurs here https://github.com/symfony/phpunit-bridge/blob/master/bootstrap.php#L7. Since class `PHPUnit_TextUI_Command` is not loaded at that time yet and `phpunit-bridge` is than not initialised. Is there a way around this? Could it be possible to add some kind of different check?

**Comment by mbabker** [comment]
I actually just went through this same issue this morning.  My workaround for the moment is using a custom bootstrap file and requiring the PHPUnit bridge's bootstrap file in there since that bootstrap is called after `PHPUnit_TextUI_Command` is loaded.

**Comment by nicolas-grekas** [comment]
Can you please test with #14854?

**Comment by matejvelikonja** [comment]
@nicolas-grekas tested and now it works as it should.

**Comment by mbabker** [comment]
All's well here too, thanks!
