### ISSUE TITLE
[Email Validator] allow ANYTHING after a valid email address !!? Bug ? Feature ?

### ISSUE THREAD

**Issue by revollat** [symfony/symfony#14848]
If I put in in a form field : 

    erg@exemple.com anything I want

it will be VALIDATED even if it has an Email constraint !! (Is it a bug or a feature ??)

            ->add('email', 'email', array(
                'constraints' => array(
                    new Assert\Email(array())
                )
            ))

Note on used version :
symfony/symfony                          v2.6.6
swiftmailer/swiftmailer                  v5.4.0

If I try to use the field value with swift mailer I got 500 err  :

    Address in mailbox given [erg@exemple.com anything I want] does not comply with RFC 2822, 3.6.2.

So even symfony email validator OR swiftmail does not implement the RFC (for an email address format) correctly ... or am I missing something

The only hack I found is to add 

    'checkMX' => true

to the validator ...

**Comment by revollat** [comment]
in the documentation (http://symfony.com/doc/current/reference/constraints/Email.html) there is a "strict" option, it says :

    type: boolean default: false

    When false, the email will be validated against a simple regular expression. If true, then the     egulias/email-validator library is required to perform an RFC compliant validation.

Does it mean that by defaut the regular expression can validate things like :

    erg@exemple.com anything I want

is it "safe" ?

**Comment by dosten** [comment]
Seems to be a bug to me, the regex it's very simple: `/.+\@.+\..+/`. You can pass the option `strict => true` to use `egulias/email-validator` to validate the email.

**Comment by revollat** [comment]
yeah I just checked the default regexp is :  

    elseif (!preg_match('/.+\@.+\..+/', $value)) {

it looks so cheap :)

I thing a lot of people who are using symfony form with email validator and swiftmailer don't even know that if a user enter something like this in an "email" field :

    aaa@example.com or bbb@example.org

swiftmailer will complain and it will not work ... !
Why is the default regexp so permissive ?? any explanation ?

**Comment by xabbuh** [comment]
Can't we simply forbid whitespaces after the `@` character?

**Comment by revollat** [comment]
I'm not sure you can write that kind of specific test case ("not spaces after some character") with regex

**Comment by revollat** [comment]
or we can search for the position of the first "@" and then starting form that position looking for a space/tabs, .... 

maybe it will work ...

**Comment by revollat** [comment]
or even simpler : looking for a spaces/tabs wherever in the provided string ....

**Comment by revollat** [comment]
:( according to wikipedia (http://en.wikipedia.org/wiki/Email_address)

spaces between quote IS valid ... 

    " "@example.org (space between the quotes)

I begin to understand why the symfony validator delegate strict RFC validation to a third party library ... so many (edge) cases ... :)
