### ISSUE TITLE
[2.7] Routing - Error on migration to 2.7

### ISSUE THREAD

**Issue by johnkrovitch** [symfony/symfony#14850]
Hi,

after a migration from 2.6 to 2.7, I have this error when I try to clear cache : 
__Catchable Fatal Error: Argument 1 passed to Symfony\Component\Routing\Router::Symfony\Component\Routing\{closure}() must  be an instance of Symfony\Component\Config\ConfigCacheInterface, instance of Symfony\Component\Config\ConfigCache given__

I try to update all my dependencies to the latest available version, I try to keep only required Symfony bundle in AppKernel (Symfony\Bundle\FrameworkBundle\FrameworkBundle(), Symfony\Bundle\SecurityBundle\SecurityBundle(), Symfony\Bundle\TwigBundle\TwigBundle(), Symfony\Bundle\MonologBundle\MonologBundle(), Doctrine\Bundle\DoctrineBundle\DoctrineBundle()), but I still have this error. I try to manually remove cache, with the same result... I'm on PHP 5.6.4-4ubuntu6.

What am I missing ? A new or a removed configuration option ?

Thank you very much

**Comment by xabbuh** [comment]
Can you provide some more information (e.g. a complete stack trace)?

**Comment by johnkrovitch** [comment]
Sure.

[Symfony\Component\Debug\Exception\ContextErrorException]                                                                  
  Catchable Fatal Error: Argument 1 passed to Symfony\Component\Routing\Router::Symfony\Component\Routing\{closure}() must   
  be an instance of Symfony\Component\Config\ConfigCacheInterface, instance of Symfony\Component\Config\ConfigCache given    
                                                                                                                             
Exception trace:
 () at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:287
 Symfony\Component\Debug\ErrorHandler->handleError() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:287
 Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}() at n/a:n/a
 call_user_func() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCacheFactory.php:46
 Symfony\Component\Config\ConfigCacheFactory->cache() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:302
 Symfony\Component\Routing\Router->getMatcher() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:70
 Symfony\Bundle\FrameworkBundle\Routing\Router->warmUp() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/RouterCacheWarmer.php:45
 Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer->warmUp() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:138
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/myuser/Projets/MyProject/TdbEsms/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/myuser/Projets/MyProject/TdbEsms/app/console:27

**Comment by xabbuh** [comment]
Could you please show the output of `composer show -i` for your project?

**Comment by xabbuh** [comment]
And could you also show how your `composer.json` file looks like?

**Comment by johnkrovitch** [comment]
composer show -i

behat/behat                          v3.0.15             Scenario-oriented BDD framework for PHP 5.3
behat/gherkin                        v4.3.0              Gherkin DSL parser for PHP 5.3
behat/mink                           v1.6.1              Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver         v1.2.0              Symfony2 BrowserKit driver for Mink framework
behat/mink-bundle                    v1.4.2              Mink bundle for Symfony2
behat/mink-extension                 v2.0.1              Mink extension for Behat
behat/symfony2-extension             v2.0.0              Symfony2 framework extension for Behat
behat/transliterator                 v1.0.1              String transliterator
besimple/sso-auth-bundle             dev-master d8be760  SSO authentication your Symfony2 project 
bluebear/basebundle                  dev-0.2-dev 85242fd Base bundle for Symfony2
braincrafted/bootstrap-bundle        dev-master dd53559  BraincraftedBootstrapBundle integrates Bootstrap into Symfony2 b...
doctrine/annotations                 v1.2.4              Docblock Annotations Parser
doctrine/cache                       v1.4.1              Caching library offering an object-oriented API for many cache b...
doctrine/collections                 v1.3.0              Collections Abstraction library
doctrine/common                      v2.5.0              Common Library for Doctrine projects
doctrine/data-fixtures               v1.1.1              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.5.0              Database Abstraction Layer
doctrine/doctrine-bundle             v1.5.0              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       v1.0.1              Symfony2 Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    v2.2.0              Symfony DoctrineFixturesBundle
doctrine/inflector                   v1.0.1              Common String Manipulations with regard to casing and singular/p...
doctrine/instantiator                1.0.4               A small, lightweight utility to instantiate objects in PHP witho...
doctrine/lexer                       v1.0.1              Base library for a lexer that can be used in Top-Down, Recursive...
doctrine/orm                         v2.5.0              Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.1              Composer script handling your ignored parameter file
ircmaxell/php-math-parser            dev-master 71703ac  A simple shunting-yard based math parser and executor for PHP
jdorn/sql-formatter                  v1.2.17             a PHP SQL highlighting library
jquery/jquery                        1.11.1              
kriswallsmith/assetic                v1.2.1              Asset Management for PHP
kriswallsmith/buzz                   v0.14               Lightweight HTTP client
monolog/monolog                      1.13.1              Sends your logs to files, sockets, inboxes, databases and variou...
oneup/uploader-bundle                v1.3.1              Handles multi file uploads in Symfony2. Features included: Chunk...
psr/log                              1.0.0               Common interface for logging libraries
sensio/distribution-bundle           v3.0.28             Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.8              This bundle provides a way to configure your controllers with an...
sensio/generator-bundle              v2.5.3              This bundle generates code for you
sensiolabs/security-checker          v2.0.5              A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.0              Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.6.1              Integrates Assetic into Symfony2
symfony/monolog-bundle               v2.7.1              Symfony MonologBundle
symfony/swiftmailer-bundle           v2.3.8              Symfony SwiftmailerBundle
symfony/symfony                      v2.7.0              The Symfony PHP framework
twbs/bootstrap-sass                  v3.3.4              bootstrap-sass is a Sass-powered version of Bootstrap, ready to ...
twig/extensions                      v1.2.0              Common additional features for Twig that do not directly belong ...
twig/twig                            v1.18.1             Twig, the flexible, fast, and secure template language for PHP

**Comment by xabbuh** [comment]
Do you use some kind of byte code cache that holds an outdated version of the `Symfony\Component\Config\ConfigCache` class?

**Comment by johnkrovitch** [comment]
my composer.json

{
  "name": "MyProject - Tableau de Bord",
  "license": "proprietary",
  "type": "Symfony project",
  "autoload": {
    "psr-0": {
      "": "src/",
      "SymfonyStandard": "app/"
    }
  },
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "jquery/jquery",
        "version": "1.11.1",
        "dist": {
          "url": "http://code.jquery.com/jquery-1.11.1.js",
          "type": "file"
        }
      }
    }
  ],
  "require": {
    "php": ">=5.4",
    "symfony/symfony": "2.7",
    "doctrine/orm": "2.5",
    "doctrine/dbal": "2.5",
    "doctrine/doctrine-bundle": "1.5.0",
    "doctrine/doctrine-fixtures-bundle": "2.2.*",
    "twig/extensions": "1.2.0",
    "symfony/assetic-bundle": "2.6.1",
    "symfony/swiftmailer-bundle": "2.3.8",
    "symfony/monolog-bundle": "2.7.1",
    "sensio/distribution-bundle": "3.0.*",
    "sensio/framework-extra-bundle": "3.0.*",
    "incenteev/composer-parameter-handler": "~2.0",
    "ircmaxell/php-math-parser": "dev-master",
    "behat/behat": "3.0.*",
    "behat/symfony2-extension": "2.0.*",
    "behat/mink-bundle": "1.4.*",
    "behat/mink-extension": "2.0.*",
    "twbs/bootstrap-sass": "~3.3.0",
    "jquery/jquery": "1.11.*",
    "braincrafted/bootstrap-bundle": "dev-master",
    "besimple/sso-auth-bundle": "dev-master",
    "bluebear/basebundle": "dev-0.2-dev",
    "oneup/uploader-bundle": "~1.3"
  },
  "require-dev": {
    "sensio/generator-bundle": "~2.3"
  },
  "scripts": {
    "post-root-package-install": [
      "SymfonyStandard\\Composer::hookRootPackageInstall"
    ],
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ],
    "post-install-cmd": [
      "Braincrafted\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::install"
    ],
    "post-update-cmd": [
      "Braincrafted\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::install"
    ]
  },
  "config": {
    "bin-dir": "bin"
  },
  "minimum-stability": "stable",
  "extra": {
    "symfony-app-dir": "app",
    "symfony-web-dir": "web",
    "symfony-assets-install": "relative",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    }
  },
  "deploy": {
    "instance": "symfony2-tdbesms"
  }
}

**Comment by johnkrovitch** [comment]
I haven't any byte code caching, but APC from php standard installation. I tried to restart apache to remove any file cache

**Comment by johnkrovitch** [comment]
Ok, I found.... Git had failed a merge (I don't know why, magic...) in composer.json. It had two sections "post-install-cmd", so the buildBootstrap script were not called, and bootstrap.cache was never updated...

**Comment by johnkrovitch** [comment]
Thank you very much for your help :)
