### ISSUE TITLE
[DX][BC break][TwigBundle] Removed twig.options parameters breaks applications

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#14851]
In one application I am having a second twig environment where I only use a different loader, to be precise a string loader for some advance rendering. In the second environment I want to be able to leverage the same options to have access to the same settings as in the main environment.

Therefore I had this service definition:

````php
    app.core.twig_string_loader:
        class:        "Twig_Loader_String"

    app.core.twig_string:
        class:        "%twig.class%"
        arguments:    [@app.core.twig_string_loader, %twig.options%]
````

Actually it seems that many were using this parameter in their application. A GitHub search shows 3.855 occurences for the term "%twig.options%".

I understand as per #13476 that there is no BC promise on parameters, however as it looks like there were many using that parameter at least we should state a recommended upgrade path in the upgrade documentation.

**Comment by peterrehm** [comment]
An option is fixing this in a compiler pass:

````php
class TwigStringOptionsCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $twigOptions = $container->getDefinition('twig')->getArgument(1);
        $container->getDefinition('app.core.twig_string')->addArgument($twigOptions);
    }
}
````

However as Twig_Loader_String is deprecated I am now seeing if it is wanted to provide this function native in twig here twigphp/Twig/#1706

**Comment by stof** [comment]
The ``Twig_Loader_String`` is deprecated in Twig because it causes too much trouble (it is flawed by design). I suggest you to just create a service wrapping Twig (exposing the logic you used in https://github.com/twigphp/Twig/pull/1706 in the ``renderString`` method) instead of duplicating the Twig environment (which requires you to duplicate the registration of extensions too for instance, and also of loaders if you want to allow using inheritance or inclusion, etc...)

**Comment by peterrehm** [comment]
I posted the workaround here so others can see how it would be possible to still inject the options if needed for some purpose. For my use case there are two workarounds as you mentioned, if it will not be integrated into twig directly I will wrap it in another service.

**Comment by peterrehm** [comment]
Shall we close this right now? Still there might be quit some others affected depending on there use case, just a quick search on GitHub shows many occurences of %twig.options%
