### ISSUE TITLE
[2.7][FrameworkBundle] Cannot turn off "serializer"

### ISSUE THREAD

**Issue by guilhermeblanco** [symfony/symfony#14869]
Currently "serializer" is marked as `->canBeEnabled()`, but a check for enable setting is never inspected.
This means serializer is always existent in the code. Solution is to replace line 130:

```php
if (isset($config['serializer'])) {
```

To this:

```php
if ($this->isConfigEnabled($container, $config['serializer'])) {
```

However, I haven't sent a PR because you'll ask for tests and I'm quite busy atm... sorry! =)

**Comment by xabbuh** [comment]
Did you experience any real issue? The `serializer` service usually should not be loaded because [of this check](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L897-899).

**Comment by weaverryan** [comment]
I just tested it, and I don't think there's a bug, you can turn off the serializer by omitting its configuration entirely *or* setting `enabled: false`.

Closing this guy - @guilhermeblanco happy to say that none of us need to create a PR ;)
