### ISSUE TITLE
[Form] Add PSR-7 request handler

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#14865]
A request handler should be added that is able to handle PSR-7 requests.

Some sort of composite request handler should be added too so that the appropriate handler is used based on the type of the request.

**Comment by xabbuh** [comment]
What about having something like a `ChainRequestHandler` that is able to deal with `ChainableRequestHandler` implementations? A `ChainableRequestHandler` could be a `RequestHandlerInterface` implementation that also implements a `supports()` method.

**Comment by webmozart** [comment]
@xabbuh Sounds like a good idea!

**Comment by nicolas-grekas** [comment]
Closing as this is old, and PSR-7 didn't get traction (at least in Symfony-related world)

**Comment by mnavarrocarter** [comment]
@nicolas-grekas Would you be willing to reopen this? 

I'm a heavy user of PSR-7, but I love the Form Component: I use it in virtually all my projects. I have a custom `Psr7RequestHandler` that I currently copy-paste from project to project and I think the time has come to put it in a proper package.

I think something like that belongs to the Form Component, as the dependencies are very lightweight. Would you merge a PR with those classes? I would just be adding the classes so users of the standalone package can use them: no touching of the DI Provider and compiler passes.

If you wouldn't like this to be part of the Form package, I totally understand. I will put it in a personal package and link it to this issue so other people can find it.

**Comment by nicolas-grekas** [comment]
Maybe you'd like to contribute it to https://github.com/symfony/psr-http-message-bridge?

**Comment by mnavarrocarter** [comment]
Yeah, I though of that but I don't really want to require `symfony/http-foundation` every time I need `symfony/form` just for PSR-7. I also understand that you might not want to require `psr/http-message` in `symfony/form`, but that dependency is significantly smaller.

**Comment by stof** [comment]
@mnavarrocarter then I suggest putting that in your own package

**Comment by nicolas-grekas** [comment]
@mnavarrocarter can you submit a PR on https://github.com/symfony/psr-http-message-bridge?
I think we can make the dependency on http-foundation optional.

**Comment by mnavarrocarter** [comment]
@nicolas-grekas No problem at all. That works for me! 😃
