### ISSUE TITLE
[2.7][FrameworkBundle] Unable to turn off "assets"

### ISSUE THREAD

**Issue by guilhermeblanco** [symfony/symfony#14868]
Currently there is no way to deactivate assets definitions completely.
In an API based application, there're no assets to be served (besides profiler), but you just can't turn it off.
We should allow people to disable it... =)

**Comment by jakzal** [comment]
See #13672, specifically the https://github.com/symfony/symfony/pull/13672#issuecomment-74119546

We can't do anything about it before 3.0, where we'll disable all the framework bundle's components by default. This is not a big deal, as the asset services do not add any overhead if they're not used.

**Comment by javiereguiluz** [comment]
Closing it as fixed because in Symfony 3.0 you can disable assets (in fact, this caused a lot of issues for people upgrading to 3.0 because they are disabled by default ... we now enable them by default when the templating is activated too).
