### ISSUE TITLE
Placeholder DateType incompatible with widget single_text

### ISSUE THREAD

**Issue by Thorry84** [symfony/symfony#14860]
In the DateType the placeholder is passed as an array (year, month, day), but when the option widget is set to "single_text" the Twig template expects a string. Result is a notice regarding array to string conversion.

**Comment by Thorry84** [comment]
Created pull request https://github.com/symfony/symfony/pull/14862

**Comment by webmozart** [comment]
Closed for the reasons given in #14862.
