### ISSUE TITLE
No generate:crud for Symfony 2.6

### ISSUE THREAD

**Issue by mfivebusiness** [symfony/symfony#14875]
I spent around 5hs in order to provide a CRUD app to render my entities. I believe Symfon 1 was much more easier in this aspect. I wonder if you let me know how I can use doctrine:generate:crud.

Thanks

**Comment by dosten** [comment]
This is not related to symfony, you should open an issue in the correct repo https://github.com/sensiolabs/SensioGeneratorBundle

**Comment by jakzal** [comment]
As @dosten suggested CRUD feature is implemented in the SensioGeneratorBundle.

@mfivebusiness seek support on [the mailing list](http://symfony.com/mailing-lists) or one of [the IRC channels](http://symfony.com/irc).
