### ISSUE TITLE
Let switch_user dispatch security.interactive_login

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#14874]
We make use [of the sticky locale to set a User's locale in the session](http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html).

When a `switch_user` event is triggered, the session locale obviously stays the same. This would be solved if the `security.interactive_login` events are dispatched after/during a  `switch_user` event and a after a `_switch_user` `_exit` event.

Will there be a way to trigger these events myself right after those `switch_user` events? Does the Firewall trigger any events during the impersionation actions? They aren't [in the Cookbook](http://symfony.com/doc/current/cookbook/security/impersonating_user.html).

**Comment by ajgarlag** [comment]
You can listen to the `security.switch_user` event and send a PR to the Symfony Docs repo documenting this event.

**Comment by Rvanlaak** [comment]
Thanks @ajgarlag , did the docs PR  :+1:

**Comment by stof** [comment]
Closing as dispatching ``security.interactive_login`` in this case is semantically wrong. It is not an interactive login.
