### ISSUE TITLE
Upgrading to symfony 2.7, serialization problems

### ISSUE THREAD

**Issue by magr1983** [symfony/symfony#14870]
Hi everyone,
I'm upgrading my symfony project from 2.6 to 2.7 and after launch composer update with dependencies I got the following error when launching my website in localhost:

You cannot serialize or unserialize PDO instances. 
looking at the stack trace:

in vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php at line 425  -

            $catalogueHash = sha1(serialize(array(
                'resources' => isset($this->resources[$locale]) ? $this->resources[$locale] : array(),
                'fallback_locales' => $this->fallbackLocales,
            )));
            return $this->cacheDir.'/catalogue.'.$locale.'.'.$catalogueHash.'.php';
        }

I've looking for help at google and here and I haven't found anything. Any help would be appreciated because I have my work stopped beacause of this.

Best regards

**Comment by xabbuh** [comment]
Thank you for reporting this issue @magr1983. However, I'm going to close here as this was already reported in #14689.

**Comment by magr1983** [comment]
Thanks¡¡
