### ISSUE TITLE
Documentation doesn't mention _method override only works with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony#14876]
I have been trying to follow this snippet of code.

http://symfony.com/doc/current/cookbook/routing/method_parameters.html#faking-the-method-with-method

But it doesn't tell me I can't use it outside of a form.

There seems to be a conflict in the documentation, as it states:

```Forms automatically include a hidden field for this parameter if their submission method is not GET or POST```

Which, to me, implies it with GET or POST requests.

but code says:

```
    /**
     * Enables support for the _method request parameter to determine the intended HTTP method.
     *
     * Be warned that enabling this feature might lead to CSRF issues in your code.
     * Check that you are using CSRF tokens when required.
     * If the HTTP method parameter override is enabled, an html-form with method "POST" can be altered
     * and used to send a "PUT" or "DELETE" request via the _method request parameter.
     * If these methods are not protected against CSRF, this presents a possible vulnerability.
     *
     * The HTTP method can only be overridden when the real HTTP method is POST.
     */
    public static function enableHttpMethodParameterOverride()
    {
        self::$httpMethodParameterOverride = true;
    }
```

Specifically ```The HTTP method can only be overridden when the real HTTP method is POST.```

**Comment by jakzal** [comment]
Hi, if you feel like the docs need updating please submit an issue or a PR to the [symfony/symfony-docs](https://github.com/symfony/symfony-docs) repo. 

By the way, the problem is explained a bit more in details in [the Forms doc](http://symfony.com/doc/current/book/forms.html#book-forms-changing-action-and-method) referenced from the one you read:

> If the form's method is not GET or POST, but PUT, PATCH or DELETE, Symfony will insert a hidden field with the name _method that stores this method. The form will be submitted in a normal POST request, but Symfony's router is capable of detecting the _method parameter and will interpret it as a PUT, PATCH or DELETE request. Read the cookbook chapter "How to Use HTTP Methods beyond GET and POST in Routes" for more information.

**Comment by xabbuh** [comment]
refs symfony/symfony-docs#5352
