### ISSUE TITLE
[DX][Console] Use specific exception classes for not defined and ambiguous command names

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#14873]
The method [`Console\Application::find`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Application.php#L526) can throw an `\InvalidArgumentException` when the command name typed is not defined or ambiguous.

To avoid having such exception logged into my alert system I want to filter on these exceptions. But the class `\InvalidArgumentException` is too generic.

What about creating a domain specific class: `Symfony\Component\Console\Exception\CommandNotDefinedException` extending `\InvalidArgumentException` ?

As a bonus, this exception class would have an extra property `$alternatives` to store the suggested command names.

**Comment by stof** [comment]
This looks like a good idea to me.

Can you submit a PR to implement it in 2.8 ?

**Comment by GromNaN** [comment]
I'm doing iT.
