### ISSUE TITLE
[Translation][2.7] No way to directly send XLIFFFile with Translation Dumper

### ISSUE THREAD

**Issue by Incognito** [symfony/symfony#14881]
https://github.com/symfony/Translation/blob/decb41096e98a76e3759fdb042842b2f3838a6a1/Dumper/FileDumper.php

I really want to be able to send a file with Response object, but the format feature is protected and part of the logic to get to the string dump is baked into the file method.

I've resolved this in my code by hard-importing part of the components code and overriding the dump method and getting back the string (which is also kind of ugly and breaks the contract design), but it would be nice if there was a way to do this without writing a file.

**Comment by aitboudad** [comment]
Hi @Incognito 

With #15786 you can pass `save_handler` option into dumper to get content of file:
```php
$dumper->dump($catalogue, array('save_handler' => function ($content) use ($response) {
    $response->setContent($content);
}));
```

**Comment by Incognito** [comment]
:+1: That looks like it solves my problem. Thank you! Is there a ticket open for adding docs to this?

**Comment by aitboudad** [comment]
not yet :)
