### ISSUE TITLE
[2.7][Security] Undocumented BC break

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#14889]
I think that i have found a BC break introduced in #13323. I'm implementing my own AuthenticationListener, this is my code:

```php
<?php

use GuzzleHttp\ClientInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface;
use Symfony\Component\Security\Core\SecurityContextInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface;
use Symfony\Component\Security\Http\Firewall\AbstractAuthenticationListener;
use Symfony\Component\Security\Http\HttpUtils;
use Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface;

class MyAuthenticationListener extends AbstractAuthenticationListener
{
    private $guzzle;

    public function __construct(SecurityContextInterface $securityContext, AuthenticationManagerInterface $authenticationManager, SessionAuthenticationStrategyInterface $sessionStrategy, HttpUtils $httpUtils, $providerKey, AuthenticationSuccessHandlerInterface $successHandler, AuthenticationFailureHandlerInterface $failureHandler, array $options = array(), LoggerInterface $logger = null, EventDispatcherInterface $dispatcher = null, ClientInterface $guzzle)
    {
        parent::__construct($securityContext, $authenticationManager, $sessionStrategy, $httpUtils, $providerKey, $successHandler, $failureHandler, $options, $logger, $dispatcher);
    
        $this->guzzle = $guzzle;
    }

    // more code...
}
```

And my service definition:

```xml
<service id="security.authentication.my_authentication_listener" class="AppBundle\Security\Firewall\MyAuthenticationListener" parent="security.authentication.listener.abstract" abstract="true" public="false">
    <argument type="service" id="guzzle.client"/>
</service>
```

After the upgrade to 2.7 i'm getting this error: `Argument 1 passed to AppBundle\Security\Firewall\MyAuthenticationListener::__construct() must implement interface Symfony\Component\Security\Core\SecurityContextInterface, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage given`

The `security.authentication.listener.abstract` definition changed in 2.7. (https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/Resources/config/security_listeners.xml#L114 and https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/SecurityBundle/Resources/config/security_listeners.xml#L114)

**Comment by fabpot** [comment]
For abstract services, we should probably revert the changes.

ping @symfony/deciders

**Comment by stof** [comment]
indeed. And then overwrite the argument in child service definitions when needed

**Comment by fabpot** [comment]
@iltar Can you work on this one?

**Comment by iltar** [comment]
@fabpot yes I think a little bit too much has changed here. I'll write a patch as soon as I have time.

**Comment by iltar** [comment]
@fabpot @stof, The fix seems easy, simply change the service id from `security.token_storage` to `security.context` for those cases. However, this will introduce an additional deprecated notice for the majority of developers. My recommendation is to simply update the interface used here and document this requirement in upgrade 2.7.

**Comment by fabpot** [comment]
@iltar Can you submit a PR for the doc update?

**Comment by iltar** [comment]
@fabpot will do
