### ISSUE TITLE
PDOSession Handler sess_lifetime vs cookie_lifetime

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#14893]
I've got Symfony setup to store sessions in a database. I have my session cookies configured to last for 30 days.
```
framework:
    session:
        handler_id:  session.handler.pdo
        cookie_lifetime: 2592000 # 30 days
services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=3306;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% , db_table: symfony_sessions, lock_mode: 1 }
```
The session cookie expiration is being set correctly, however, the sess_lifetime value stored in the database is always 1440. How are these two values related? Shouldn't the sess_lifetime value be equal to the cookie_lifetime value? Otherwise, the session data gets cleared from the database long before the cookie expires.

**Comment by Tobion** [comment]
I don't understand how somebody is expecting help and is too lazy to even reference to original ticket and discussion. As this ticket only consists of questions, please ask support questions on the mailing list.

**Comment by stevenmusumeche** [comment]
The original ticket was mistakenly opened in the wrong repo, so that is why I didn't reference it.  I am not asking for support, I can fix this easily by setting gc_lifetime in my config.  I am opening this issue because it is not obvious from the documentation that you need to set both values if you want your sessions to live longer.
