### ISSUE TITLE
\Symfony\Component\HttpFoundation\Response::__construct should not call to $this->setDate

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#14906]
Constructing a response object is not for free. While performance does often not matters,
it matters for an HTTP Cache implementation, given how often its called.

Is there any reason why \Symfony\Component\HttpFoundation\Response::__construct() calls out to $this->setDate()?

There is also code in \Symfony\Component\HttpFoundation\Response::getDate(), which ensures that you return a valid object, in case none is set yet

**Comment by fabpot** [comment]
I think it can be safely moved to when we send the headers (so as late as possible)

**Comment by jakzal** [comment]
just to get this out of the way: #14912

**Comment by LionsAd** [comment]
To give some background, I micro-analyzed Drupal 8's page cache performance (100 runs each time, repeated several times, on a dedicated performance testing server):

- https://www.drupal.org/node/2501989#comment-10000905

Please ignore any composer autoloader or container parts, the most interesting thing is the raw response / request object construction.

Unfortunately people judge Drupal 8's performance still in comparison to Drupal 7, so please understand some of my frustration if it feels like there is nothing or not much we (as Drupal) can do about it.

If we can however get some micro-performance optimization tweaks into the stack, that would be great.

I'll open some issues and we'll see where it goes.

The nice thing of the PR #14912 is that just by setting our own date we could improve performance on the Response.

**Comment by jakzal** [comment]
@LionsAd could you verify if #14912 is improving anything in Drupal's performance?

**Comment by LionsAd** [comment]
Yes, will do, probably late today or early tomorrow.

**Comment by Tobion** [comment]
Changed in 2.8
