### ISSUE TITLE
[DiC][XmlFileLoader] The attribute 'factory' is not allowed

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#14907]
Based on https://github.com/symfony/symfony/blob/2.7/UPGRADE-3.0.md#dependencyinjection (which took affect from 2.7)
All `factory-*` attributes are deprecated in favor of single `factory` attribute.
But when you try to update it, it throws `The attribute 'factory' is not allowed`

So we must update `http://symfony.com/schema/dic/services` and `Symfony\Component\DependencyInjection\Loader\schema\dic\services\services-1.0.xsd` accordingly.

**Comment by jakzal** [comment]
`factory` is not an attribute, but an XML node. It is present in [the `services-1.0.xsd`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd#L83). 

The UPGRADE doc you referenced does mention factories are now configured in a similar way to configurators. See the related docs: http://symfony.com/doc/2.7/components/dependency_injection/factories.html
