### ISSUE TITLE
Update the form component

### ISSUE THREAD

**Issue by Moinax** [symfony/symfony#14910]
Can you please update the form component, so it stops using deprecated methods in his own code.

I think about "getOptionResolver" method which still call "setDefaultOptions" instead of "configureOptions".

Everything has been fixed in https://github.com/symfony/Form/commit/e12d8d63892aa93752acc027ce37212c1ee7c9d8, so a new release should fix the problem.

**Comment by xabbuh** [comment]
Can you please show where the deprecated code is actually still called? Or put in other words: Can you show a stack trace of a deprecation warning that is triggered by Symfony itself?

**Comment by romaricdrigon** [comment]
+1, I receive a bunch of those calls. Unfortunately, the stack trace is not diplayed.

**Comment by Moinax** [comment]
I can trigger the deprecated method if I use the createNamedBuilder from the form factory.

```php
   $form = $this->get('form.factory')->createNamedBuilder();
```

But as I said, it is already fixed in https://github.com/symfony/Form/commit/e12d8d63892aa93752acc027ce37212c1ee7c9d8

**Comment by stof** [comment]
@Moinax the commit you linked is the removal of BC layers in Symfony 3.0.

**Comment by Moinax** [comment]
@stof Ha yes you are right, we cannot simply use that commit, but what I meant is the "problem" has been soved there https://github.com/symfony/Form/blob/e12d8d63892aa93752acc027ce37212c1ee7c9d8/ResolvedFormType.php#L206

**Comment by xabbuh** [comment]
@Moinax Are you absolutely sure that it is neither your code nor code coming from a third-party package you are using that calls the deprecated method?

**Comment by Moinax** [comment]
Here is the pseudo trace we can find in the profiler

```
Called from ResolvedFormType::getOptionsResolver() at line 146
Called from ResolvedTypeDataCollectorProxy::getOptionsResolver() at line 201
Called from ResolvedFormType::getOptionsResolver() at line 109
Called from ResolvedFormType::createBuilder() at line 82
Called from ResolvedTypeDataCollectorProxy::createBuilder() at line 87
Called from FormFactory::createNamedBuilder() at line 106
Called from FormBuilder::create() at line 267
Called from FormBuilder::resolveChildren() at line 215
Called from FormBuilder::getForm() at line 221
Called from FormBuilder::getForm() at line 377
Called from CampaignController::designAction()
Called from call_user_func_array() at line 3094
Called from HttpKernel::handleRaw() at line 3056
Called from HttpKernel::handle() at line 3207
Called from ContainerAwareHttpKernel::handle() at line 2429
Called from Kernel::handle() at line 29
```

As explained, I only use the method 

```php
$this->get('form.factory')->createNamedBuilder()
```

When I follow the trace with PHPStorm, i finally come to https://github.com/symfony/Form/blob/2.8/ResolvedFormType.php#L206

**Comment by jakzal** [comment]
@Moinax `setDefaultOptions()` is still being called for BC. However, the deprecation warning is only triggered if your type provides the `setDefaultOptions()` instead of the `configureOptions()`.

**Comment by Moinax** [comment]
@jakzal maybe I don't see the BIG picture here, but I don't understand why you couldn't use the `configureOptions()` method in your own code in the 2.7 version.

On the other hand, the only thing I can see is that I add two custom form types to the 

```php
$this->get('form.factory')->createNamedBuilder()
```

And none of them implements/overrides the `configureOptions()` or `setDefaultOptions()` method (I use simple arrays for form data), but the debug toolbar give me two notices of deprecated call.

**Comment by jakzal** [comment]
> maybe I don't see the BIG picture here, but I don't understand why you couldn't use the configureOptions() method in your own code in the 2.7 version.

We must support the old method in case someone has overridden it. This means we cannot switch to `configureOptions()` until the `setDefaultOptions()` is removed (3.0).

I just tried to create a simple form on a clean Standard Edition installation:

```php
        $form = $this->get('form.factory')->createNamedBuilder('f')
            ->add('title')
            ->getForm();

        return $this->render('default/index.html.twig', ['form' => $form->createView()]);
```

I didn't get any deprecation warnings, while I do get them if I override `setDefaultOptions()` on a form type.

Please provide steps (preferably code) to reproduce your issue on a Standard Edition project.

**Comment by Moinax** [comment]
@jakzal Thanks for your answer on the big picture. 

I don't have the problem when I add a simple field like your 'title'  but I have it when I add a custom form type (declared as a service).

**Comment by xabbuh** [comment]
@Moinax Could you share your form type?

**Comment by jakzal** [comment]
@Moinax I have tried that as well. I'm only getting a warning if I override `setDefaultOptions()`, which is an expected behaviour. Please fork the Standard Edition and reproduce it on a new branch.

**Comment by Moinax** [comment]
My apologies to @xabbuh @jakzal & @stof 

I was looking at my forms, but forgot that a `FormType` is also used for "fields" and that we were using a "third-party" field for images.

That's the one that was triggering the error.

I guess https://github.com/symfony/symfony/pull/14905 will solve that kind of mistake.

Thank you again for your (waste of) time.

Regards,
