### ISSUE TITLE
[Serializer] Serializer improvements

### ISSUE THREAD

**Issue by Ener-Getick** [symfony/symfony#14924]
The symfony serializer is a great tool but it's probably underused now.

2.7 introduces the groups and I think that we could think to else fields we could create !

Firstly, the fields exposition isn't really present now. I suggest to add an ``Expose`` config (definable to ``true``/``false``) and the possibility to change a field serialized name ``ExportsAs``.
It could also be useful to implement virtual properties.

Besides that I think it's important to have the choice to split readable field and writable fields:
So I suggest to have a normal policy ``NormalizePolicy``, a readable policy  ``ReadablePolicy`` and a writable policy ``WritablePolicy`` on classes that define a default exposition, a default security (expression, overwritable) and a global security (expression, not overwritable).

We should develop maybe a verification mechanism too with a type verification and normalization.

If you don't see what I mean, I created some annotation classes : https://github.com/Ener-Getick/symfony/tree/ticket_14924/src/Symfony/Component/Serializer/Annotation.

Please give your feedbacks.

**Comment by dunglas** [comment]
It's not the current philosophy of the Serializer component. Adding such features is IMO a bad idea:
- it creates a bunch of ways to do things that can already be done currently
- it make the component harder to maintain
- it bloats (and probably slow down) the component

> `Expose` config (definable to `true`/`false`)
You can already use groups to do that. What's the use case not coverable with the existing feature?

> change a field serialized name `ExportsAs`

`ExportsAs` it's IMO a bad idea to use annotations for that (encourage inconsistencies). The name converter system can already be used to do such things: http://symfony.com/doc/current/components/serializer.html#converting-property-names-when-serializing-and-deserializing

> It could also be useful to implement virtual properties
I don't like that kind of things:
- it's doable only for normalization, not for denormalization
- it introduces a lot of magic
- it's more clear and easy to this using raw PHP (and groups if necessary)

> Besides that I think it's important to have the choice to split readable field and writable fields

Here again, this can definitely done with groups:

```php
use Symfony\Component\Serializer\Annotation\Groups;

class Test
{
    /** @Groups{"read"} */
    public $foo;
    /** @Groups{"read", "write"} */
    public $bar;
}
```

You can even adopt fine grained policy:
```php
use Symfony\Component\Serializer\Annotation\Groups;

class Test
{
    /** @Groups{"user-read", "admin-read", "admin-write"} */
    public $foo;
    /** @Groups{"user-read", "user-write", "admin-read", "admin-write"} */
    public $bar;
}
```

> We should develop maybe a verification mechanism too with a type verification and normalization.

Agree. There is work in progress on that topic: https://github.com/symfony/symfony/pull/14844#issuecomment-110495801

**Comment by dunglas** [comment]
For the `ExportsAs` feature. It can be done using a special name converter aware of the `ClassMetadata`.

**Comment by dunglas** [comment]
However, an improvement I want to add is a `@Depth` annotation. I've described the use case here: https://github.com/dunglas/DunglasApiBundle/issues/104#issuecomment-110644569

What do you think?

**Comment by Ener-Getick** [comment]
I didn't really explained why I think that the virtual properties are a good idea ...
Now, you have to add a ``@Groups`` annotation on a method to serialized it. 
But I think it's not really clear and it would be better to centralize that in a ``@VirtualProperties`` annotation. 

An example :
```php
/**
 * @VirtualProperties({
 *    "foo": {
 *        @Readable(getter="notUsualSetter"),
 *        @Writable(setter="getUserFoo", security="is_granted('ROLE_SUPER_ADMIN')")
 *    },
 *    "bar": {
 *        @Expose(security="is_granted('ROLE_USER')")
 *    }
 * })
 * @NormalizePolicy(defaultExposition=false)
 */
class FooClass
{
    ...
}
```

With the virtual properties, you can define for each method how it will be serialize and not just for the methods ``get|set|has|is``. Moreover you don't have to scroll on your entire class to find what you want.

For the exposition features, they are principally made to simplify the development and to don't have to worry about the security questions. (For example the plainPassword of the FOSUserBundle is writable in some cases but not readable.)

For the ``ExportsAs``, I don't know finally if it was a great idea. It could create inconsistencies but in some cases, you want to change a field name and that's maybe hard for a lot of people to create a new name converter ?

**Comment by Ener-Getick** [comment]
The ``@Depth`` annotation could be really useful in some cases. 
I just don't know if it's better to throw an exception or to do nothing because it's the user who defines the depth.
It could be fine to add a custom parameter to the annotation to define the comportment for each field and also add a general parameter that defines the default comportment.

**Comment by dunglas** [comment]
About `@Depth`, it will have the same behavior as for circular reference: allow to register a custom handler (a `\Callable`) and have a default handler that throw an exception.

**Comment by Ener-Getick** [comment]
About this thread, should I close it ? Or do we continue to discuss about new serializer features ?

**Comment by Ener-Getick** [comment]
Is that wanted that no metadata loaders are registered in the framework bundle configuration ?

```xml
<!-- Loader -->
<service id="serializer.mapping.chain_loader" class="Symfony\Component\Serializer\Mapping\Loader\LoaderChain" public="false">
    <argument type="collection" />
</service>

<!-- Class Metadata Factory -->
<service id="serializer.mapping.class_metadata_factory" class="Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory" public="false">
    <argument type="service" id="serializer.mapping.chain_loader" />
    <argument>null</argument>
</service>
```

**Comment by afurculita** [comment]
@Ener-Getick  `@Alias` annotation is in work in https://github.com/symfony/symfony/pull/15200 to implement the behaviour you described for `@ExportsAs`
