### ISSUE TITLE
[Security][Translation] duplicate translations

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#14920]
After updating Symfony I thought I could see the effect of https://github.com/symfony/symfony/pull/14601 but it doesn't happen because there is **two** translations folders into the security component.

I updated [Security/Resources/translations/security.fr.xlf](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Resources/translations/security.fr.xlf) but [Security/Core/Resources/translations/security.fr.xlf](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Resources/translations/security.fr.xlf) is used.

I don't know if it's legit but now that translations have diverged I think something must be done.

**Comment by stof** [comment]
The translations should be kept in sync. If they are not, we need to fix it (we have moved translations inside ``Security/Core`` because of the split of the security component into several components for subtree splits, but keeping them in the old location too for BC reasons)

**Comment by MatTheCat** [comment]
There is only two translations files in *Security/Core/Resources/translations* on the 2.3 branch. Shouldn't translations already be in sync on 2.3?

**Comment by stof** [comment]
This is because ``Security/Core/Resources/translations`` was not used on 2.3 yet. but new translations added after that as PR to newer branches were backported to 2.3 without removing the files and adding them again later when merging into newer branches for simplicity. Symfony 2.3 does not use this folder at all.

**Comment by MatTheCat** [comment]
Does it mean the sync should be done on the 2.7 branch?

**Comment by vincentaubert** [comment]
For me it should be fixed in the 2.6 branch.
As this branch is the oldest already maintained version of the security-core component.

**Comment by fabpot** [comment]
#14977 adds the missing changelog entry (FI, it has been changed for Symfony 2.4).
#14979 removes the obsolete translations in 3.0.
