### ISSUE TITLE
[bug][Security] LogoutHandlers not called when no session cookie

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#14939]
Problem:

1. Session cookie **is not** present (deleted, expired, invalid, etc)
2. RememberMe cookie **is** present
3. User is logging out
4. RememberMe cookie is not deleted

Alternatively:

1. Session cookie **is not** present (deleted, expired, invalid, etc)
2. User is logging out
3. No `LogoutHandlerInterface` implementation is called (because there is no token)

---

After debugging I see what happens:

1. `security.logout_listener` [is created](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L298)
2. `security.logout_listener` is given [`LogoutHandlerInterface`s](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/Logout/LogoutHandlerInterface.php): [1](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L323), [2](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L332), [3](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L337)
3. authentication listeners [are created](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L357) from factories, including [`RememberMeFactory`](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php)
4. `RememberMeFactory` [adds](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php#L51) its own `LogoutHandlerInterface`
5. Security listeners [are merged](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L359)
6. `Firewall` [iterates over listeners](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/Firewall.php#L67) and stops on the first giving `Response`.

Problem? Listeners are called in this order: `ChannelListener `, `ContextListener `, `ContainerAwareEventDispatcher `, **`LogoutListener`**, `UsernamePasswordFormAuthenticationListener`, **`RememberMeListener `**, `AnonymousAuthenticationListener`, `AccessListener`.

So if the user doesn't have a session cookie, `LogoutListener` **doesn't call** any `LogoutHandlerInterface`s, because [there is no token (yet)](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/Firewall/LogoutListener.php#L113).

---

IMHO `LogoutListener` should be called last, after other listeners, which might authenticate user before he/she is logged out. Otherwise none of the handlers are called.

In my situation it is crucial that `RememberMeServices` (as `LogoutHandlerInterface`) + `CookieClearingLogoutHandler` get called, because Symfony co–exists with non–Symfony app.

----

I don't know what's the correct solution, but as a fast hack it could work to:
* override `LogoutListener` and call `LogoutHandlerInterface`s manually with a dummy `TokenInterface` if there is no token yet,
* override `LogoutListener` and do custom actions here (but I believe `LogoutHandlerInterface`s should be used, as they might contain important logic),
* override [`LogoutSuccessHandlerInterface`](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/Logout/LogoutSuccessHandlerInterface.php), but same problem as above,
* override `FirewallMap` to change the order of listeners (as it should have already been done in `SecurityExtension`?).

**Comment by xabbuh** [comment]
@MacDada I am not sure if I completely understood your issue. Could you please have a look at #7104 and check if that issue is describing the same thing?

**Comment by MacDada** [comment]
@xabbuh Yep, it's the same thing, closing as duplicate.
