### ISSUE TITLE
[Translations][Bundles] bundle overrides not taken into account

### ISSUE THREAD

**Issue by drAlberT** [symfony/symfony#14942]
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   |  
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

If one wants to override (for example) error pages he can override the TwigBundle Exceptions templates.
If we want to make these templates locale-aware we could put them into `app/Resources/TwigBundle/translations/` and they will work .. **but** the translations system seems to have no way to extract or dump them ...

I think translations:[dump|update] should be overrides-aware and search for translations in every standard place a bundle could be overridden 

Hope to have been clear in my explanation :)

**Comment by aitboudad** [comment]
The translation doesn't take into the bundle hierarchy but the order of registering bundles in the kernel.
It's already reported in #3148 and we decided to explains this in the docs https://github.com/symfony/symfony-docs/issues/5193

**Comment by drAlberT** [comment]
Hi @aitboudad 
  maybe I'm not understanding, but I'm not talking of nested bundles ..

What should be the right way to override a bundle template still having the translation system work? 

I think the error pages example can be idiomatic .. how has to be handled is IMHO not clear in the other issues you linked .. but I'm pretty new to symfony2 so maybe I'm totally misunderstanding the entire problem

Thank you for your patience :)

**Comment by stof** [comment]
@drAlberT overriding bundle templates does not change anything to the translation system. These are 2 independent systems.

**Comment by drAlberT** [comment]
@stof  I know .. maybe I'm not be clear in my explanation of the problem ? ;(

I want to achieve the following goal:
  - use custom error pages templates
  - have them localised
  - have `app/console translation:*` tasks able to extract, compare and so on strings from the custom error templates  

AFAICS simply overriding TwigBundles templates I can't achieve my goal .. translations does not see them


Maybe I'm wrong in something basic .. but it should be a simple task

**Comment by drAlberT** [comment]
I worked around the problem moving error pages templates in a custom bundle (say CustomErrorsBundle or whatever you want call), override the Exception controller and the findTemplates() method 

(even here now everything works, but following the docs it was impossible to have it working :( )

This way I have a clean solution .. but the question became: is it the right approach? .. isn't it too tricky? it's not well documented IMHO ..

Thank you guys .. hope to have been clear now :D

**Comment by xabbuh** [comment]
@drAlberT What exactly did not work before? Providing translations for the messages or extract them from your templates?

**Comment by drAlberT** [comment]
App/console translations:* do not see the templates

So, yes, I can't extract them from templates

**Comment by drAlberT** [comment]
@xabbuh any news?

**Comment by aitboudad** [comment]
@drAlberT I look into it :)

**Comment by drAlberT** [comment]
:+1:  :)

**Comment by aitboudad** [comment]
fixed by #15038 and #15039.
