### ISSUE TITLE
Return "version" argument to "asset" function

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#14958]
http://symfony.com/doc/current/reference/configuration/framework.html#assets-version-format

> Some CDN's do not support cache-busting via query strings, so injecting the version into the actual file path is necessary. Thankfully, assets_version_format is not limited to producing versioned query strings.
> 
> The pattern receives the asset's original path and version as its first and second parameters, respectively. Since the asset's path is one parameter, you cannot modify it in-place (e.g. /images/logo-v5.png); however, you can prefix the asset's path using a pattern of version-%%2$s/%%1$s, which would result in the path version-5/images/logo.png.

https://github.com/symfony/symfony-docs/issues/4982

``` twig
{# absolute URLs - get the version with asset_version() and append it manually #}
{{ absolute_url(asset('logo.png')) ~ '?' ~ asset_version('logo.png') }}
```

Proposed solution doesn't respect `assets_version_format` but previous `asset('logo.png', version=5)` does.

**Comment by stof** [comment]
I don't understand what you are asking here. The title of the issue and the description seem to be related to 2 different things

**Comment by Koc** [comment]
Description demonstrates that this argument is really needed.

**Comment by xabbuh** [comment]
The example in the description could still be achieved with something like the following if I don't miss anything:

```twig
<img src="version-{{ asset_version('package_name) }}{{ asset('logo.png') }}">
```

**Comment by Koc** [comment]
So if I would change assets version format I should rewrite all of the templates according to the new format. Not so useful

**Comment by WouterJ** [comment]
According to http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component, you can configure the version format and version in the `asset` configuration and it will automatically be appended when using `asset()`.

**Comment by Koc** [comment]
What to do if I want specify version of concrete asset? In this case I should use concatenation

**Comment by javiereguiluz** [comment]
I'd close this as "won't fix" because:

* If this only affects to a handful of assets, then concatenating the version should not be a big deal.
* If it affects to lots of your assets, then you can define a package for them.

**Comment by Koc** [comment]
@javiereguiluz have you seen referenced commit above? Is it acceptable? If yes I can finish it and open PR

**Comment by Koc** [comment]
concatenation ois not possible with specific version format.

**Comment by nicolas-grekas** [comment]
@Koc can't this be achieved using a custom versioning strategy? did you give it a try? Shall we close otherwise?

**Comment by Koc** [comment]
I don't need this feature anymore :)
