### ISSUE TITLE
[Form] Deprecate "choices_as_values" => false

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#14951]
The value `false` for the "choices_as_values" option (= the current default value) should be deprecated in 2.8. This means that people need to manually set the option to `true` for all choice fields.

In Symfony 3.0, we can remove the code for handling the value `false` and deprecate the "choices_as_values" option altogether. In a future 3.x release, the option can be removed to complete the transition.

**Comment by webmozart** [comment]
See #14825 for more discussion on the motivation behind deprecating the option.

**Comment by Soullivaneuh** [comment]
Well, to continue here, I'll :-1: for this.

To resume why, just read @xabbuh say:

> @webmozart Maybe we should just provide an option that sets choice_label to function ($choice) { return $choice; }. Shouldn't be that hard to maintain in the component, but saves developers to write cumbersome and boring code.

**Comment by stof** [comment]
@Soullivaneuh ``choices_as_values`` is not directly to ``choice_label``. So you are talking about a different topic.
``choices_as_values`` controls where the choices are the keys or the values in the ``choices`` option. Symfony 2.0 shipped with choices as keys (and labels as values), which means that the easy syntax only works when your choices are integers or strings. Any other case (boolean choices for instance) required passing a ChoiceList object instead, making the usage more complex (especially for people forgetting that booleans cannot be used as keys as PHP just casts them to string silently).
This is the reason why this option has been introduced in 2.7 to be able to flip the array (while maintaining BC). the advantage is that any type of data can be used in this way (strings, integers, floats, booleans, objects, arrays)

**Comment by webmozart** [comment]
@stof He is talking about `choice_value`.

**Comment by xabbuh** [comment]
@webmozart Is this something you think we still need to consider for 2.8?
