### ISSUE TITLE
Validate userManager object.

### ISSUE THREAD

**Issue by KrissMcCone** [symfony/symfony#14960]
Hello. I create API and I want to add user with data received in array.

How can I validate userManager? Cos updateUser($user) allows to save user wihout primary data, or string instead of email.

$validator = $this->get('validator');
$errors = $validator->validate($user);

When the user is a object from $userManager->createUser() doesn't work.

Any idea? Thanks :)

**Comment by fabpot** [comment]
Please ask support questions on [the mailing list](http://symfony.com/mailing-lists). Thanks.
