### ISSUE TITLE
Configure path for asset helper

### ISSUE THREAD

**Issue by smajazayeri** [symfony/symfony#14968]
Hi there,

I wanna configure the path to my assets from /web to /foo/bar. According to your reference book http://symfony.com/doc/current/components/templating/helpers/assetshelper.html#configure-paths, it's possible. Unfortunately, it's not clear enough  what file should be added this line:
[code]$templateEngine->set(new AssetsHelper('/foo/bar'));[/code]

Any help or advice is appreciated. (I'm using Symfony 2.6)

**Comment by dosten** [comment]
Please ask questions on the [mailing list](http://symfony.com/mailing-lists).

**Comment by smajazayeri** [comment]
resolved by http://stackoverflow.com/questions/20874303/prefixing-asset-path-for-files-in-symfony2-and-twig.
The documentation of Symfony 2 has many lacks and it's not comparable with Symfony 1 at all.

**Comment by dosten** [comment]
You can send a PR to improve the docs :)
Can you close this?

**Comment by smajazayeri** [comment]
oh, cool. I didn't know that. I'm doing some dirty notes in my draft ;) for sure, after my deadline, I contribute to the symfony documentation.
