### ISSUE TITLE
[HttpFoundation] Support SplTempFileObject at BinaryFileResponse

### ISSUE THREAD

**Issue by jbruni** [symfony/symfony#14969]
Considering:
- BinaryFileResponse supports SplFileObject 
- SplTempFileObject extends SplFileObject 

One should expect it to support SplTempFileObject. But this is not the case.

An exception is thrown from https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L89 

It says:

```
FileNotFoundException in File.php line 41:
The file "php://temp" does not exist
```

**Comment by phansys** [comment]
IMO, this check:
```php
if ($checkPath && !is_file($path)) {
    throw new FileNotFoundException($path);
}
```
could be updated to something like:
```php
if ($checkPath && !is_file($path) && !(($fp = @fopen($path, 'r')) && fclose($fp))) {
    throw new FileNotFoundException($path);
}
```

**Comment by mihai-stancu** [comment]
Bump!

**Comment by nicolas-grekas** [comment]
Anyone willing to submit a PR with patch+test case?
Otherwise, let's close...

**Comment by xabbuh** [comment]
please take a look at #23785

**Comment by nicolas-grekas** [comment]
Closing as won't fix.
The linked PR failed, so this is not trivial.
If someone that actually needs that want to make it, please do.
