### ISSUE TITLE
cant create helper class in a Controller file

### ISSUE THREAD

**Issue by laurencefass** [symfony/symfony#14961]
Im just getting started with Symfony. I want to define a class to reference in my DefaultController:indexAction function. This is not working. Errors at the end of this post.

class Page
{
	public $title;
	public $body;
}

class DefaultController extends Controller
{
    /**
     * @Route("/home", name="homepage")
     */
    public function indexAction()
    {
	/* i want to use the class in here
    }
}

Output when trying to load the controller.

Class AppBundle\Controller\AppBundle does not exist in /home/rest2.symfony2.com/public_html/restServer/src/AppBundle/Controller/ (which is being imported from "/home/rest2.symfony2.com/public_html/restServer/app/config/routing.yml").
500 Internal Server Error - FileLoaderLoadException
1 linked Exception: ReflectionException »

 [2/2] FileLoaderLoadException: Class AppBundle\Controller\AppBundle does not exist in /home/rest2.symfony2.com/public_html/restServer/src/AppBundle/Controller/ (which is being imported from "/home/rest2.symfony2.com/public_html/restServer/app/config/routing.yml").  -

    in vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php at line 125  -
                            throw $e;
                        }
                        throw new FileLoaderLoadException($resource, $sourceResource, null, $e);
                    }
                }

**Comment by fabpot** [comment]
Please ask support questions on [the mailing list](http://symfony.com/mailing-lists). Thanks.

**Comment by laurencefass** [comment]
my posts here https://groups.google.com/forum/#!forum/symfony2 are not showing up and apparently not being added.

1. is it a bug that i cant simply add a class to a file and reference another class within that file?
2. where else can i submit a support issue as google groups not working for me?

thanks

**Comment by xabbuh** [comment]
@laurencefass When writing to the mailing list for the first time, it may take some time for your mail to show up.

**Comment by laurencefass** [comment]
many thanks.
