### ISSUE TITLE
Form type as a service reusing empty data objects

### ISSUE THREAD

**Issue by jbenezech** [symfony/symfony#14985]
I originally opened an issue in relation to the a2lix transformationBundle (https://github.com/a2lix/TranslationFormBundle/issues/183), but this seems to be an issue with the Form component.

When a form type is setup as a service and used more than once in a form, if the emptyData attribute of the form returns an object, the same object reference is reused across the form fields.

The testcase :

1 entity Main with two OneToOne relations to another entity Other (which just has a name field)

```
    /**
    * @var Other
    *
    * @ORM\OneToOne(targetEntity="Other", cascade="persist")
    */
    private $first;

    /**
    * @var Other
    *
    * @ORM\OneToOne(targetEntity="Other", cascade="persist")
    */
    private $second;
```

 A form type for the entity Other registered as a service

In the form type for Main:

```
        $builder
            ->add('first', 'othertype', array(
                'required' => false
                )
            )
            ->add('second', 'othertype', array(
                'required' => false
                )
            )
           ;
```

In the setDefaultOptions of the form type for Other:

```
'empty_data' => new Other(),
```

Upon saving that form, only 1 of the 2 fields will be persisted, with the value of the latest one.

This comes from the fact that when setting the property (mapDataToForms), the same object reference for Other is reused.

using a closure to set the empty_data solves this issue

```
'empty_data' => function (FormInterface $form) { return new Other(); }
```

**Comment by webmozart** [comment]
Hi @jbenezech, thank you for taking the time to report this issue! :) This is not a bug. Form types exist globally in your application. That means that if you set an object in the "empty_data" option, this object will be reused across all forms created for that type (as happened here). You also found the correct solution - to use a closure. :)
