### ISSUE TITLE
[Validator] [Profiler] Name of the validator who throw an error

### ISSUE THREAD

**Issue by gregoirepaqueron** [symfony/symfony#15003]
Hi,

Here is my case : 

- I have a ManyToOne relation field on an entity,  and put some Asserts on it : 

```php
/**
     * @Assert\NotNull(message="The BU location is required")
     * @Assert\NotBlank(message="The BU location is required")
     *
     * @ORM\ManyToOne(targetEntity="Acme\AppBundle\Entity\Country")
     * @ORM\JoinColumn(name="bu_country_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
     */
    protected $buCountry;
```

- When i set the field at null, i always have this error ``This value is not valid.``.

- The fact is not if i use wrong Assert on a ManyToOne relation, but currently with this standard message, i can't find which Validator throw this error message. So i'm force to test all with custom message to find the right.

Is there a way to find which Validator throw this error message ?

**Comment by stof** [comment]
``This value is not valid.`` looks like the error message set on the form when a DataTransformer is failing. Do you use a data transformer ?

**Comment by gregoirepaqueron** [comment]
Not on this field. Here is the field on the form : 

```php
$builder
            ->add('buCountry', 'entity', array(
                'multiple'      => false,
                'class'         => 'Acme\AppBundle\Entity\Country',
                'query_builder' => function ($repository) {
                        return $repository->getQueryCountryListByproviderType(Provider::PROVIDER_TYPE_BUSINESS_UNIT);
                    },
                'required'      => true,
                'label'         => 'BU location',
                'empty_value'   => '--------------------------'
            ))
```

**Comment by gregoirepaqueron** [comment]
By the way, i've found the reason why it didn't throw my custom message. The value was not really ``null`` but was "NULL" in a string format (god bless me).

But, is my issue about the name of the Validator in the Profiler isn't relevant ?

**Comment by stof** [comment]
in recent Symfony versions, there is. form errors have a cause, which will be the ConstraintViolation when they come from the validator, and the violation itself has a reference to the constraint. and in symfony 2.7+, it should be displayed in the profiler
