### ISSUE TITLE
Declaring a service with a leading slash leads to syntax errors in cached container

### ISSUE THREAD

**Issue by kix** [symfony/symfony#15001]
Here's my `services.xml`:

```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="my_abstract_soap_client" class="\SoapClient" abstract="true">
            <argument/>
        </service>
    </services>
</container>
```

When I clear cache, I get a syntax error:
```
$ php app/console cache:clear
PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in /.../app/cache/dev/appDevDebugProjectContainer.php on line 8819
```

Symfony is v.`2.3.29`.

I think this should be improved by either allowing leading slashes for service classes or by handling these cases and displaying a more descriptive error message.

**Comment by stof** [comment]
I don't see any leading slash in your snippet

**Comment by kix** [comment]
@stof, sorry, my bad.

**Comment by stof** [comment]
Trimming the leading slash in the dumper would indeed be a good idea

**Comment by boekkooi** [comment]
Very strange but I'm not sure how this can even be dumped, since it should throw a  [`"'\\SoapClient'" is not a valid class name for the "my_abstract_soap_client" service.`](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L364) when dumping. 

@kix are you sure that the given xml is correct? because when using a test like:
```PHP
$container = new ContainerBuilder();
$loader = new XmlFileLoader($container, new FileLocator(self::$fixturesPath . '/xml'));
$loader->load('services14.xml');

$dumper = new PhpDumper($container);
$dumper->dump();
```
I get the expected exception.

**Comment by Tobion** [comment]
I confirm the bahavior as described by @kix with latest symfony 2.6.
Either 
  - we trim the leading slash
  - throw an error

Trimming the leash would be more friendly, but unfortunately not consistent with #15079 which currently does not allow to use a leading slash. See also https://github.com/symfony/symfony/pull/15079#issuecomment-115262140

**Comment by kix** [comment]
@boekkooi, yes, you are right, this does happen now in my case, and looks like I cannot reproduce this. However, the thing seems to be about abstract services. I have this in my `services.xml`:

```
<services>
        <service id="my_abstract_soap_client" class="\SoapClient" abstract="true">
            <argument/>
        </service>

        <service id="my_real_soap_client" parent="my_abstract_soap_client"></service>
</services>
```
However, once I clear the cache, I get an error saying that `"'\\SoapClient'" is not a valid class name for the "my_real_soap_client" service.`. This could be misleading in some cases, I think.

@Tobion, can you supply any steps you've made to reproduce this issue?

**Comment by jibran** [comment]
FYI: Related drupal 8 issue https://www.drupal.org/node/2536736

**Comment by fabpot** [comment]
I'm :+1: with removing the leading `\`

**Comment by xabbuh** [comment]
see #15380
