### ISSUE TITLE
twig.debug parameter seems to be unused

### ISSUE THREAD

**Issue by Abam** [symfony/symfony#15009]
The `twig.debug` parameter in the TwigBundle seems to be unused.
Passing it to false doesn't disable the error view with stacktrace.
I have to pass kernel.debug parameter to false to get what I want.

After a look in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L158, it seems that the exception controller rely only on %kernel.debug%.
Is it the expected behavior ?

**Comment by stof** [comment]
twig.debug is about configuring the debug mode of the Twig_Environment. this indeed does not impact the exception controller at all

**Comment by Abam** [comment]
So to test custom error pages, we must deactivate kernel.debug ?

**Comment by stof** [comment]
no, you should use the dedicated feature: http://symfony.com/blog/new-in-symfony-2-6-error-page-previews

**Comment by Abam** [comment]
Ok, Thks.
It's not exactly what I am looking for but I'll give it a try.
