### ISSUE TITLE
VarDumper dump javascript error

### ISSUE THREAD

**Issue by ivoba** [symfony/symfony#15015]
in sf 2.6.9 i get javascript errors when using:

    dump($var);
    exit;

The error is:

    TypeError: root is null
    ....tagName) { f(e.target.parentNode, e); } }); }; root.addEventListener('mouseover...

$var is deeply nested object.
Then the toggle feature doesnt work anymore, the variable dump is shown however and is fully expanded.
Does dump only work in full rendered pages?

**Comment by nicolas-grekas** [comment]
Can you please post the generated html in a gist?

**Comment by ivoba** [comment]
Here is the gist: https://gist.github.com/ivoba/faf0cff10410024f87e0

the js error is from FireFox.
In Chromium its different:

    Uncaught TypeError: Cannot read property 'addEventListener' of null

**Comment by nicolas-grekas** [comment]
Thanks for the gist, see #15017 for the fix (hopefully)

**Comment by ivoba** [comment]
yes, just tried it. 
it works with the PR
