### ISSUE TITLE
Trailing slash in Request base url

### ISSUE THREAD

**Issue by Brainshack** [symfony/symfony#15016]
Hello,
I happen to run into the issue, that after logging in and out, I get redirected to a URL, which is corrupt. This shows, in the URL having multilple / at the start. I figured out, that this might relate to an issue in the URLGenerator. The problem occurs, in an application, that uses SonataAdminBundle.
In the Bundle. redirects are done to absolute URLs, like this:

```
$this->container->get('router')->generate($route, $attributes, UrlGeneratorInterface::ABSOLUTE_URL)
```

This generates the wrong URLs. I was able to track this problem to the UrlGenerator Class, at about line 277:

```
    if (self::RELATIVE_PATH === $referenceType) {
        $url = self::getRelativePath($this->context->getPathInfo(), $url);
    } else {

        $url = $schemeAuthority.$this->context->getBaseUrl().$url;
    }
```

$this->context->getBaseUrl() returns the URL, including app_dev.php/ . Since I couldnt figure out, where the baseUrl of the requestContext gets propagated, I came up with a simple, working fix:

```
 $url = $schemeAuthority.rtrim($this->context->getBaseUrl(), '/').$url;
```

trimming additional slashes works, however, I am not certain if this is the right place to tackle this issue. I personally think, that error lies deeper, in the baseUrl, which shouldn't have a trailing '/'. Can somebody point me to the point, where this is is propagated through the request?

**Comment by ewgRa** [comment]
Can you check how in RequestContext appears not right base url? Just add debug code in RequestContext::setBaseUrl method and if baseUrl not right - throw Exception and check call stack.

If it is go from Request::getBaseUrl, debug Request::prepareBaseUrl

**Comment by Brainshack** [comment]
It seems, that Request::prepareBaseUrl is not being called. However, the URL seems to be wrong in the Request Object itself. Here is the callstack: http://pastebin.com/b3fTFi0i

The request in the RequestContext is set inside the RouterListener:

RouterListener->onKernelFinishRequest & RouterListener->onKernelRequest

I can trace this back to app_dev.php

    $request = Request::createFromGlobals();
    var_dump($request->getBaseUrl());die;

This allready has the faulty URL

    string(13) "/app_dev.php/" 

However, when I try to debug inside the Request Object, there seems to be some sort of caching. The same goes for the HttpKernel. Alle the methods i try to debug dont seem to be called, which makes it hard to debug for me.

**Comment by ewgRa** [comment]
Check this http://symfony.com/doc/current/cookbook/debugging.html#disabling-the-bootstrap-file-and-class-caching

I think your request class loaded from app/bootstrap.cache.php, this is why your debug not working.

**Comment by Brainshack** [comment]
Okay, I know now what is wrong. In prepareBaseUrl, the Server Variable SCRIPT_NAME is being used to determine the baseUrl. This, for some reason, is 'app_dev.php/' . I would assume it not to have a trailing slash, but whatever.

However, at the very end of prepareBaseUrl, return rtrim($baseUrl, '/') is called. This does not happen, in my case. In my case, it returns here:

      if ($baseUrl && false !== $prefix = $this->getUrlencodedPrefix($requestUri, $baseUrl)) {
            // full $baseUrl matches
            return $prefix;
        }

Interesetingly, in the next IF Block, the return value again is trimmed:

         if ($baseUrl && false !== $prefix = $this->getUrlencodedPrefix($requestUri, rtrim(dirname($baseUrl), '/').'/')) {
            // directory portion of $baseUrl matches
            return rtrim($prefix, '/');
        }

In fact, every return value of prepareBaseUrl, that is not emtpy, is rtrim'd, except for this one. In my opinion, this is a bug, at least in version 2.6, which I am using.

**Comment by ewgRa** [comment]
Agree, can you write pull request for this? Cover this case by test in RequestTest and fix Request code?

I'm not a from core team, but also think that such cases can be handled by Symfony transparently, or at least throwing exceptions when SCRIPT_NAME ends on /.

**Comment by Brainshack** [comment]
So I checked, and this seems to be the case in 2.8 aswell. Now the question is, if this maybe happened on purpose. Looking into the history, this part doesnt seem to have changed since 2012. Would be cool, if someone from the core team would have a look into this and verifiy that this is indeed a bug. If so, I will happily create a PR for this :)

**Comment by ewgRa** [comment]
ping @stof

Is this is a bug when Request::getBaseUrl return url with / at the end? Seems it can be when some server params configured not well. Also seems there is can be another places that can work not well due to this configuration.

Must Symfony handle it transparently or throw Exception?

**Comment by ewgRa** [comment]
@Brainshack I think you can make PR that will be just make rtrim

**Comment by OskarStark** [comment]
sounds like a missconfiguration in the fastcgi_params

which webserver do you use?

oskar

**Comment by Brainshack** [comment]
We are using Apache 2

**Comment by OskarStark** [comment]
can you post your fastcgi_params ?

**Comment by Brainshack** [comment]
ping @stof Can you enlighten me what should be done here?

**Comment by stof** [comment]
why asking me when the question is asked by @OskarStark ?

And what should be done is fixing your server configuration indeed. It makes no sense to have a trailing slash in ``SCRIPT_NAME``. your script name does not end with a slash

**Comment by Brainshack** [comment]
So, but here is a thing:

I am using a standard puphet vagrant machine. I didn't modify any configuration at, so it is somewhat reasonable to assume, that I might not be the only one affected by this. Also, symfony's server check (app/check.php) does not list any errors in server configuration, so even if it is a server config issue, it might at least be feasible to check for that in check.php.

Since I am not a server admin, I don't really am sure what to look for here. And honestly, I still think it would just be plain better to make the behavior of said method consistent. Every return value is rtrim'd, except for that one case, that leads to this problem. So making that simple change, would lead to a less error prone implementation, without really any downsides.

@OskarStark could you please hint me to were to find the requested information?

**Comment by pradeshjm** [comment]
So what is the best way to fix this without having to change the Symfony code?

**Comment by BallisticPain** [comment]
http://symfony.com/doc/current/setup/web_server_configuration.html#web-server-apache-fpm

So we found out we had a newer version of Apache than 2.4.9 which then we used the answer of
```
    <FilesMatch \.php$>
        SetHandler proxy:fcgi://127.0.0.1:9000
    </FilesMatch>
```

Note: Make sure you don't have a trailing slash there either.

**Comment by javiereguiluz** [comment]
I'm closing this because it looks like a server misconfiguration. Thanks!
