### ISSUE TITLE
VarDumper suggested package

### ISSUE THREAD

**Issue by rcross** [symfony/symfony#15018]
I'm not sure why the VarDumper component has a suggested package of "ext-symfony_debug" 

I can't find that package on packagist or otherwise, and there doesn't seem to be any note or explanation to it in the issue where it was originally committed in, and its doesn't turn up in any other issues here. 

Can I suggest removing it as a suggestion if there isn't a reason for it (or it doesn't exist)?

**Comment by dosten** [comment]
All the deps that starts with ext-* are PHP extensions. The symfony debug extension is located [here](https://github.com/symfony/Debug/tree/master/Resources/ext). The next time ask questions on the [mailing lists](http://symfony.com/mailing-lists).

**Comment by rcross** [comment]
I thought that might've been the case, but I'm surprised that I couldn't figure that out on my own. I even searched for "symfony debug php extension" and didn't get any obvious results on the first page or two.

is there not a some way of better documenting or referencing that somewhere?

**Comment by rcross** [comment]
I should add that there are other examples of custom extentions on packagist as well using the virtual package feature. https://packagist.org/search/?q=ext-

**Comment by stof** [comment]
@rcross virtual packages appear on Packagist when a package says it provides an existing extension (which should be done only when your package provides a PHP implementation of the same API, otherwise you could create wonky situations).
Packagist is not a repository of PHP extensions. and the symfony_debug extension is indeed not available on pecl.php.net currently.

**Comment by rcross** [comment]
ok, there seemed to be examples from those results that appeared to be otherwise. (https://packagist.org/providers/ext-opendkim was one)

If it is not on packagist or on pecl, can I ask how someone would be expected find this extension?

**Comment by nicolas-grekas** [comment]
You aren't, someone needs to do the packaging work. Would like do to it? See e.g. #12154

**Comment by rcross** [comment]
I am not familiar enough with it to feel comfortable, but at least that answers the question and there is an issue to create the packaging. Thanks!
