### ISSUE TITLE
isRedirect() doesn't work with paths alone, contrary to documentation

### ISSUE THREAD

**Issue by gunderjt** [symfony/symfony#15021]
Hello,

According to the [testing documentation](http://symfony.com/doc/current/book/testing.html#your-first-functional-test) the Response method `isRedirect()`  is supposed to work with the url path alone

    // Assert that the response is a redirect to /demo/contact
    $this->assertTrue(
        $client->getResponse()->isRedirect('/demo/contact')
    );

However, it doesn't because the Location header string is usually the entire url ("http://localhost/demo/contact"), and thus, the equality comparison fails.  I've already written a patch that will allow a comparison with the path using the php parse_url function along with updated tests.

However, if `isRedirect()` is supposed to be used only with the entire url, then the documentation will need to be corrected.

**Comment by ewgRa** [comment]
> the Location header string is usually the entire url 

It depends on developer. Usually if it is redirect to same site - this is url without host. If it is redirect to external site - with host. But there is no rule as I know.

On my mind documentation is fine, if your code redirect with host - check in test that you redirect with host. If not - than test without. Another way is to follow redirect and assert Request path.

Another solution to add something like isRedirectTo(array_of_path_info) and check if there is some intersection with response redirect path info.

**Comment by Tobion** [comment]
Where does it say it works with the path alone? It just asserts the location header is the one given.

**Comment by Tobion** [comment]
> An obsolete version of the HTTP 1.1 specifications (IETF RFC 2616) required a complete absolute URI for redirection.[2] The IETF HTTP working group found that the most popular web browsers tolerate the passing of a relative URL[3] and, consequently, the updated HTTP 1.1 specifications (IETF RFC 7231) relaxed the original constraint, allowing the use of relative URLs in Location headers.[4]

https://en.wikipedia.org/wiki/HTTP_location
