### ISSUE TITLE
Extract the Templating component

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#15028]
Hi there!

This is a meta-issue with a list of things that we need to do in order to extract the Templating component from the core to his own repo ([symfony/Templating](https://github.com/symfony/Templating)).
The idea is to extract the Templating component in 2.8, so in order to do this we need to:
- [ ] Remove all the content from `src/Symfony/Component/Templating` and add `symfony/templating` as a dependency to keep BC. ([see PR](https://github.com/symfony/symfony/pull/15029)).
- [ ] Make the [symfony/Templating](https://github.com/symfony/Templating) repo writable.
- [ ] Move all code related to the Templating component to [symfony/templating-bundle](https://github.com/symfony/templating-bundle) (inital work can be found [here](https://github.com/dosten/templating-bundle)).

In 3.0 we need to:
- [ ] Remove the BC layer, remove `symfony/templating` dependency from the core.

If i'm missing something feel free to tell me. :)

**Comment by dosten** [comment]
The PR to remove the Templating component can be found here: https://github.com/symfony/symfony/pull/15029

**Comment by WouterJ** [comment]
Afaik, we haven't decided on the faith of the Templating component yet, did we?

**Comment by dosten** [comment]
IMO the future of the component is (almost) decided, see the last comments from #12897.

**Comment by javiereguiluz** [comment]
I'm closing this because at the end it was decided to deprecate the integration of Templating component into Symfony, but not the component itself. So nothing will change for the component itself.
