### ISSUE TITLE
[Form][BC-break] choice-list option breaks rendering of the form

### ISSUE THREAD

**Issue by aledeg** [symfony/symfony#15037]
I created a custom type which uses a custom *LazyChoiceList* object to load my choices. It was working from SF2.4 to SF2.6.
With SF2.7, I got the following error message:

> Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\ChoiceList\Factory \DefaultChoiceListFactory::Symfony\Component\Form\ChoiceList\Factory\{closure}() must be an instance of Symfony\Component\Form\Extension\Core\View\ChoiceView, array given

After investigation, the problem comes from the *createView* method in *Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory.php*.

As I am using deprecated code in 2.7, I use the first part of the code. Unfortunately, the closure can not work since it accepts only *LegacyChoiceView* objects and it receives arrays.

If one change the hint to array, the closure code won't work since an object is needed.
If one change the return type of the method *getRemainingView* from array to *LegacyChoiceView*, the array_map won't work since its second parameter must be an array.

I read 2.8 code and this code is still there.

**Comment by webmozart** [comment]
Hi @aledeg, thank you for taking the time to report this problem! Could you please upload a fork of symfony-standard that reproduces your problem?

**Comment by aledeg** [comment]
Hi @webmozart, I don't understand what you want me to upload. Could you give more information?

**Comment by webmozart** [comment]
Sure! Go to https://github.com/symfony/symfony-standard and click "Fork" on the top right to fork the Symfony Standard Edition to your own account (see https://help.github.com/articles/fork-a-repo/ for help). Reproduce the bug in this project, commit the code and push the branch to your fork. Then send me a link to your fork and the name of the branch. I will download the branch and *should* be able to see your bug exactly like you do. :)

Better now?

**Comment by aledeg** [comment]
Thanks for the explanation.

**Comment by aledeg** [comment]
@webmozart Here is the link to my [fork](https://github.com/aledeg/symfony-standard) and the name of my branch is *form-exception*

**Comment by trsteel88** [comment]
+1 - having the same issue
