### ISSUE TITLE
[PHP7] Unable to login using migrate session strategy & form_login

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#15033]
Steps to reproduce
---

 1. Install the symfony demo
 1. Run on PHP 7 (I used https://github.com/rlerdorf/php7dev )
 1. Go to `/login` of the demo and try to login

Now, you'll notice you can not log in (you'll always be redirected back to `/login` as anonymous user), although the credentials are valid and the authenticator succeeds.

Now, add `session_fixation_strategy: none` in `app/config/security.yml` and try (3) again. You'll notice everything works fine.

When using PHP 5.6 on the same vagrant box, both ways work perfectly.

Being far from a session expert, I have no idea why this is happening and if it's a bug in Symfony or PHP7.

**Comment by jakzal** [comment]
After a long debugging session, I figured out that the a reference to `$_SESSION` is lost after a call to `session_regenerate_id()`. We store the reference in session bags, so we don't have to operate on the `$_SESSION` directly.

I believe this is a PHP bug and reported it here: https://bugs.php.net/bug.php?id=70013

**Comment by jakzal** [comment]
Reopened since PHP guys don't treat it as a bug... See https://bugs.php.net/bug.php?id=70013:

> It is a BC break, but I'm not sure if the behavior before was correct.
> 
> References should normally be broken up before deletion…
> And session_regenerate_id() is exactly that: delete old session, create new session.

**Comment by jakzal** [comment]
Even if PHP is not going to fix it on their side, I think there's a solution. I'll send a PR later on.
