### ISSUE TITLE
BC-Break in default validator of ChoiceQuestion?

### ISSUE THREAD

**Issue by cmfcmf** [symfony/symfony#15032]
This comes from.https://github.com/matthiasnoback/symfony-console-form/issues/6

The bundle has this code:

``` php
use Symfony\Component\Console\Question\ChoiceQuestion;

/**
 * Inherits default behavior of ChoiceQuestion, but returns the value of a choice instead of its label
 */
class RawChoiceQuestion extends ChoiceQuestion
{
    public function getValidator()
    {
        $originalValidator = parent::getValidator();
        return function ($selected) use ($originalValidator) {
            $value = $originalValidator($selected); // this returns the choice's label in 2.6, BUT the choice's key in 2.7
            // Ignore below
            $choices = array_flip($this->getChoices());
            if (is_array($value)) {
                return array_intersect_key($choices, $value);
            } else {
                return $choices[$value];
            }
        };
    }
}
```

The `$originalValidator`, which is the `$defaultValidator`, [defined here](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Question/ChoiceQuestion.php#L122-L173), changed it's behaviour in between Symfony 2.6 and 2.7 (tested with 2.6.9 and 2.7.1). In Symfony 2.6.9, it returns the choice's label, i.e. 'English' and in 2.7 it returns the value, i.e. 'en'. 

The form builder is used "the 2.6 way" and was not changed during my tests.

``` php
$builder
            ->add('locale', 'choice', array(
                'label' => __('Select your default language'),
                'label_attr' => array('class' => 'col-sm-3'),
                'choices' => ['en' => 'English', 'de' => 'German'],
                'data' => 'en'
            ));
```

//cc @craigh, @guite, @matthiasnoback

**Comment by pjcdawkins** [comment]
This affected me too

**Comment by matthiasnoback** [comment]
There is something of a BC-break here. Previously, the default validator of `ChoiceQuestion` always returned the value, not the key, from the `$choices` array. Since 2.7 (not sure about the exact version) it returns the value *only* if the array is numerically indexed. If it's an associative array, it returns the key.

**Comment by sstok** [comment]
It seems allot more got broken https://github.com/symfony/symfony/pull/15271
With the PR I opened the tests hangs.

**Comment by nicolas-grekas** [comment]
Closing as fixing an old BC break is another BC break.
