### ISSUE TITLE
Form EntityType custom query_builder not working

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#15035]
Hi,

The following code was working in 2.6, but is broken in 2.7

I need to use the field options in the query builder, so I was advised to put the code in a normalizer to be able to get the options. 

Since version 2.7, EntityType expects (in method getQueryBuilderPartsForCachingHash) that the querybuilder is of type QueryBuilder and not a closure. 

Is there a solution to this?

```
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class CategoryType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'class' => 'AppBundle:Category',
            'language' => 'fr',
        ]);
        
        $resolver->setNormalizer('query_builder', function(Options $options, $value) {
            return function(EntityRepository $repo) {
                return $repo->createQueryBuilder('c')->select('c')->orderBy('c.title_'.$options['language'], 'ASC');
            };
        });
        
        $resolver->setNormalizer('property', function(Options $options, $value) {
            return 'title_'.$options['language'];
        });
    }

    public function getParent()
    {
        return 'entity';
    }

    public function getName()
    {
        return 'category';
    }
}
```

**Comment by webmozart** [comment]
Hi @guillaumesmo, thank you for reporting this issue! Why are you setting the "query_builder" via a normalizer? You should rather set the closure via `setDefaults()` (also for the "property" option), otherwise you overwrite the default query builder:

```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class CategoryType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'class' => 'AppBundle:Category',
            'language' => 'fr',
            'query_builder' => function (Options $options) {
                $language = $options['language'];

                return function(EntityRepository $repo) use ($language) {
                    return $repo->createQueryBuilder('c')->select('c')->orderBy('c.title_'.$language, 'ASC');
                };
            },
            'property' => function (Options $options) {
                return 'title_'.$options['language'];
            },
        ]);
    }

    public function getParent()
    {
        return 'entity';
    }

    public function getName()
    {
        return 'category';
    }
}
```

**Comment by guillaumesmo** [comment]
I was not aware that closures could be passed to defaults as well. It's much cleaner like this indeed. This would have been a BC issue but because I was using it wrong it doesn't count of course. 

Thanks for your help !

**Comment by webmozart** [comment]
You're welcome :)

**Comment by dnagirl** [comment]
It would be really nice if @webmozart 's example were part of the EntityType documentation. The [current documentation](http://symfony.com/doc/current/reference/forms/types/entity.html#ref-form-entity-query-builder) gives the impression that $options are inaccessible to the querybuilder property.

**Comment by xabbuh** [comment]
@dnagirl The Form component uses the OptionsResolver to configure the form types' options. Thus, you can rely on all the features the OptionsResolver component offers. The approach described by @webmozart is described here: http://symfony.com/doc/current/components/options_resolver.html#default-values-that-depend-on-another-option But please feel free to open an issue in the docs repository if you think that we can improve this somehow.
