### ISSUE TITLE
label_attr arguments ignored in bootstrap_3_layout

### ISSUE THREAD

**Issue by jonathanbull** [symfony/symfony#15046]
I'm using the bootstrap_3_layout. If I use form_label arguments, they are ignored:

    {{ form_label(form.foo, 'Foo', {'label_attr': {'class': 'bar'}}) }}

    <label>
       *default humanized label*
    </label>

This does not happen with form_div_layout:

    {{ form_label(form.foo, 'Foo', {'label_attr': {'class': 'bar'}}) }}

    <label class="bar">
       Foo
    </label>

**Comment by xabbuh** [comment]
@jonathanbull Unfortunately, I was not able to reproduce your issue. Does this happen for all form types? Could you provide a fork of the Symfony Standard Edition that reproduces this?

**Comment by jonathanbull** [comment]
@xabbuh Sorry, I realised shortly after I opened the issue that this only affects checkboxes:

    {{ form_widget(form.fooCheckbox) }}
    {{ form_label(form.fooCheckbox, 'Foo') }}

Could you please give it another go? If you're still unable to reproduce it, I'd be happy to provide that fork.

**Comment by xabbuh** [comment]
@jonathanbull The checkbox type is a bit special when using the Bootstrap theme as the label will already be handled by the widget. So `form_label()` will render nothing and you will have to pass label options to `form_widget()`:

```twig
{{ form_widget(form.foo, 'Foo', {'label_attr': {'class': 'bar'}}) }}
```

**Comment by xabbuh** [comment]
By the way, this will soon be reflected in the documentation on symfony.com when symfony/symfony-docs#5460 is merged.
