### ISSUE TITLE
Process on windows fails to save stdout to temporary file if file exists

### ISSUE THREAD

**Issue by low-ghost** [symfony/symfony#15041]
I know windows should mostly be an afterthought, but it seems that these lines
```php
$this->files = array(
     Process::STDOUT => tempnam(sys_get_temp_dir(), 'sf_proc_stdout'),
     Process::STDERR => tempnam(sys_get_temp_dir(), 'sf_proc_stderr'),
);
```
in ProcessPipes.php in version 2.5.x and WindowsPipes.php in more recent versions, create a temporary file called sf_xxxx.tmp when the stdout is too large. These files populate a temp directory and fail to be removed after usage (though they are empty at 0 bytes).

After running a few thousand processes (remember that they weren't deleting and this was over the course of a few weeks), process->start() and process->run() began to hang and fail with a simple timeout error pointing to those lines. Deleting the sf_... files restored normal execution.

Perhaps this deletion is already intended but is failing, or perhaps it needs to be implemented.

Here is an OutofProcPreport

Version=1
EventType=ShellBrowserCancel
ReportType=3
Consent=1
ReportIdentifier=1313c4f7-1697-11e5-a276-f816547970ba
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value={F3364BA0-65B9-11CE-A9BA-00AA004AE837}
Sig[1].Name=Problem Signature 02
Sig[1].Value=Local
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
FriendlyEventName=User canceled a hung navigation.
ConsentKey=ShellBrowserCancel
AppName=WindowsExplorer
AppPath=C:\windows\Explorer.EXE
ReportDescription=The user cancelled the navigation after 20 seconds.

**Comment by ewgRa** [comment]
There is function removeFiles in WindowsPipes.

Can you change @unlink($filename); to unlink($filename); and check any errors when it try to remove files?

**Comment by low-ghost** [comment]
Hey, sorry for the delay. I was working with windows at that point and both haven't accessed a windows machine since or, besides a few weeks into July, haven't worked with Symphony either. I'll close this under the assumption that unlink($filename) should have been working correctly and that this was most likely a permissions error of some kind. Thanks
