### ISSUE TITLE
Date form type isn't rendered correctly while using locale 'es'

### ISSUE THREAD

**Issue by esteban-filardi** [symfony/symfony#15042]
I add the date form type to the form by using

    $builder->add('fechaComprobante', 'date', array('data' => new \DateTime('now')));

Then in the view I simply render the complete form by using

    {{ form_widget(form) }}

I'm attaching two screenshots. The first screenshot was taken while using 'es' as the default locale. This is where the issue appears. There are two select input to select the day of the month.

![screenshot 86](https://cloud.githubusercontent.com/assets/1585383/8261242/4828d6da-169f-11e5-9ea1-2a46742976dc.png)

The second screenshot was taken while using 'en' as the default locale

![screenshot 84](https://cloud.githubusercontent.com/assets/1585383/8261246/4e63d45a-169f-11e5-93c5-f8d40af90827.png)

In this screenshot there's no problem. I've also tried setting the locale as 'fr' which didn't show any problem while rendering neither.

When the screenshots were taken there wasn't any form theme being used. If I use the bootstrap form theme the results are similar.

**Comment by phansys** [comment]
Maybe this is a issue with Intl. Could you please dump your intl info?

**Comment by esteban-filardi** [comment]
I'm not sure what you mean by dump intl info, but here's the output of phpinfo refering to intl

    intl

    Internationalization support => enabled
    version => 1.1.0
    ICU version => 54.1
    ICU Data version => 54.1

    Directive => Local Value => Master Value
    intl.default_locale => no value => no value
    intl.error_level => 0 => 0
    intl.use_exceptions => 0 => 0

**Comment by phansys** [comment]
Sure @esteban-filardi, I refered to that info.
I've tested your form in my env with latest 2.7-dev and there is no issue with the generated widget (my ICU version is 52.1); but the format in my widget is ```d m Y``` instead of ```d M Y``` (like seems to be in yours).
I didn't check with any 2.7 stable release, so it would be great if you can provide a standard-edition reproducing your problem.
Just check if you're not applying formating in some point and try to play with [these configs](http://symfony.com/doc/current/reference/forms/types/date.html#format) in order to find some clue.

**Comment by esteban-filardi** [comment]
Hi, I'm sorry I was busy. This is my first issue report so I have no experience in this.
I forked symfony-standard, clone the forked repository to my pc, checkout the 2.7 branch, create a new branch called 'issue', make the example and then commit and push the new branch. 

https://github.com/esteban-filardi/symfony-standard/tree/issue

The issue persisted in the simple example as it can be seen in the screenshot

![screenshot 89](https://cloud.githubusercontent.com/assets/1585383/8265780/7a1d58be-16e0-11e5-808e-85d106951802.png)

**Comment by webmozart** [comment]
I can reproduce this issue with locale "es_ES" and "format" set to `\IntlDateFormatter::FULL`.

**Comment by esteban-filardi** [comment]
I just wanted to add that I've tried the same simple example in an older version of php, and the form is render correctly there. Perhaps it is not a symfony2 form issue but an icu or intl issue as @phansys  said.

**Comment by webmozart** [comment]
@esteban-filardi The "issue" is that recent ICU versions changed the default format for es to contain quoted strings: `EEEE, d 'de' MMMM 'de' y`. Symfony didn't take care of quoted strings so far, but I'm trying to fix that.

**Comment by webmozart** [comment]
See #15065 for a fix.

**Comment by esteban-filardi** [comment]
I'm not sure if you are waiting for some feedback but just in case, I added the lines of your fix and the widget is rendered correctly now.
