### ISSUE TITLE
Oracle DbalSessionHandler is broken.

### ISSUE THREAD

**Issue by nuncanada** [symfony/symfony#15050]
There exists a Oracle bug with MERGE and CLOBs:
https://dev.icinga.org/issues/1362
(Notice that Oracle's proposed "fix" is only to throw a proper error message)

So you cannot reuse the same variable to bind a CLOB both to an INSERT and an UPDATE.
It will (intermittently) throw an ORA-0600 error...

A workaround is to bind the TEXT to 2 different variable names... dataInsert and dataUpdate for example...

**Comment by Tobion** [comment]
Could you provide a PR with the changes please? You seem to know what workaround to apply.

**Comment by Tobion** [comment]
Does this bug both affect `bindParam` and `bindValue`? Or only one of them?

**Comment by nuncanada** [comment]
I have implemented a workaround. Just need to test it at work to do the PR.
Em 20/06/2015 18:23, "Tobias Schultze" <notifications@github.com> escreveu:

**Comment by nuncanada** [comment]
The instance where the problem is happening uses bindParam, but as it is an
Oracle limitation(bug) when binding CLOBs I believe it should happen with
both...

$mergeStmt->bindParam(':data', $encoded, \PDO::PARAM_STR);
