### ISSUE TITLE
[RFC] Standarize alphabetical order of "use" declarations

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#15062]
If this proposal is approved, the **ordered_use** rule from [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/fbca2593178d02d77c06a7351dabb4e32d58590e/README.rst#usage) should be moved from **contrib** to **symfony** level.

Some refs:

* symfony/symfony-docs#5404
* FriendsOfPHP/PHP-CS-Fixer#397

**Comment by mmoreram** [comment]
+1 Happy to see this

**Comment by fabpot** [comment]
Not going to happen. Huge amount of work, tedious merge between merges, no benefits. Frankly, we have more important things to tackle.

**Comment by phansys** [comment]
Thanks for your feedback.
