### ISSUE TITLE
CardSchemeValidator - Maestro bad regexp

### ISSUE THREAD

**Issue by euskadi31** [symfony/symfony#15085]
Symfony v2.6.9
---------------------
Hello,
we have a reject of validation for a Maestro card our card that start by 56125 (we have the card right in front of us we're shure of it :D )
If we check the code the regexp doesn't match this number...
Can we update the support of Maestro card?

See: http://www.barclaycard.co.uk/business/files/Ranges_and_Rules_September_2014.pdf
See: https://github.com/symfony/Validator/blob/master/Constraints/CardSchemeValidator.php#L70

**Comment by javiereguiluz** [comment]
You are right. According to the official documents, the regexp for Maestro-based cards is wrong. I'm trying to fix it in #15086.

**Comment by xabbuh** [comment]
The fix provided in #15086 is not complete if a card number needs the full length of 19 digits (for example, validation would still fail with `5612559223580173965` or `6594371785970435599`.

**Comment by xabbuh** [comment]
see #15127
