### ISSUE TITLE
[question] How to ensure an element of an array is an array?

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#15081]
I'm not sure if it's just a question or a desired behaviour or a bug.

I've found problematic (impossible?) to validate if a given key of an array is an array itself.

Given this array:

    [
        'key' => 'value',
    ]

it's not possible (?) to create a constraint that would check if the `key` value is an array. (so this given input must be treated as invalid).

I tried

    $constraint = new Collection([
        'key' => new Required([
            new Type('array'),
            new Collection([
                'value' => new Required([
                    new NotBlank(),
                ]),
            ]),
        ]),
    ]);

but it throws an exception

    Symfony\Component\Validator\Exception\UnexpectedTypeException: Expected argument  of type "array or Traversable and ArrayAccess", "string" given

And this situation confuses me: I thought a validator might/must be configured in a way, when you can pass **literally anything** to it and expect a valid response: a result with violations list or lack of them. But definitely not an exception.

Am I missing something?

PS: a corresponding stackoverflow question I also asked: http://stackoverflow.com/q/31018218/251311

**Comment by dosten** [comment]
Please ask questions on the [mailing lists](http://symfony.com/mailing-lists).
