### ISSUE TITLE
[Form][BC-break] Translation for entity form type

### ISSUE THREAD

**Issue by pabgaran** [symfony/symfony#15082]
I just updated Symfony2 from 2.4 to 2.7. Besides a lot of deprecated calls, I have found one weird problem.

I have a "select" tag within a form and I get the options from database. In database are stored the translation keys, and always has worked fine, symfony showed the correct language in the form. But not now.

Some code and screenshots:

Form:

````
->add('category', 'entity', array(
    'empty_value' => 'Event.form.label.category_empty',
    'class' => 'EventBundle:Category',
    'choice_label' => 'name',
    'error_bubbling' => true,
    'constraints' => array(
        new NotBlank(array('message' => 'Event.form.error.category.notblank'))
    )
))
->add('subcategory', 'entity', array(
    'class' => 'EventBundle:Subcategory',
    'choice_label' => 'name',
    'error_bubbling' => true,
    'constraints' => array(
        new NotBlank(array('message' => 'Event.form.error.subcategory.notblank'))
    )
))
````
Template:
````
<div class="form-group col-sm-6 input-group">
    <label for="event_category" class="input-group-addon">{{ 'Event.form.label.category' | trans }}</label>
    {{ form_widget(form.category, { 'attr': { 'data-ott-subcaturl' : path('get_subcategories') , 'class' : 'form-control ev-category'} }) }}
</div>
<div class="form-group col-sm-6 input-group">
    <label for="event_subcategory" class="input-group-addon">{{ 'Event.form.label.subcategory' | trans }}</label>
    {{ form_widget(form.subcategory, { 'attr': { 'class' : 'form-control ev-subcategory'} }) }}
</div>
````

Form result with Symfony2.4:
![with2 4](https://cloud.githubusercontent.com/assets/1287902/8325982/f79f956a-1a5d-11e5-9d8d-c4a101c2c2bc.png)

Form result with Symfony2.7:
![with2 7](https://cloud.githubusercontent.com/assets/1287902/8325983/f7a18dc0-1a5d-11e5-98b6-c524ae1177d4.png)

As you see, the empty_value key is translated in both cases. And the option values keys does not appear in debugger, as if they didn't exist. I think is because translations load before doctrine, but I don't know how fix it.

**Comment by gnorby88** [comment]
Try to use translation domain:

->add('category', 'entity', array(
    'empty_value' => 'Event.form.label.category_empty',
    'class' => 'EventBundle:Category',
    'choice_label' => 'name',
    'error_bubbling' => true,
    'constraints' => array(
        new NotBlank(array('message' => 'Event.form.error.category.notblank'))
    ),
    'translation_domain' => 'AppBundle'
))

For me worked on the choice field:

                ->add('status', 'choice', array(
                        'choices' => Order::getStatusList(),
                        'required' => false,
                        'empty_data' => Order::getStatusList()[0],
                        'translation_domain' => 'AppBundle'
                    ))

**Comment by pabgaran** [comment]
It does not work. The problem isn't the domain, but the translations aren't detected by Symfony.

**Comment by aitboudad** [comment]
Hi @pabgaran,
In 2.7 we introduced the choice_translation_domain to avoid translating options,  for your case just set  choice_translation_domain to true.
see http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates#added-choice-translation-domain-domain-to-avoid-translating-options for more details
```php
->add('category', 'entity', array(
    'choice_translation_domain' => true,
));
```

**Comment by pabgaran** [comment]
This works fine!

Thank you @aitboudad
