### ISSUE TITLE
Doctrine mapping import ignores filter when checking tables for primary keys

### ISSUE THREAD

**Issue by markusgillmeister** [symfony/symfony#15084]
I ran into an issue when importing a mapping from a single table. The database has some tables without primary keys which are not important for my import. So I use the filter parameter to get only the single table. But doctrine does a complete database check and throws a MappingException when scanning the table without the primary key.

> console doctrine:mapping:import --em=customer **--filter="tbl_users"** AcmeHelloBundle xml

>  [Doctrine\ORM\Mapping\MappingException]
>  **Table tbl_abc has no primary key**. Doctrine does not support reverse engineering from tables that don't have a primary key.

I think it would be better if the mapping import only does the check on the mentioned table in the filter parameter und do the import.

**Comment by Tobion** [comment]
This command is provided by the doctrine bundle. Please open the issue there: https://github.com/doctrine/DoctrineBundle/blob/master/Command/ImportMappingDoctrineCommand.php
