### ISSUE TITLE
Inconsistency between FrameworkBundle and Security component

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#15099]
There is inconsistency between:

`Symfony\Bundle\FrameworkBundle\Controller\Controller`
```
protected function denyAccessUnlessGranted($attributes, $object = null, $message = 'Access Denied.')
{
    if (!$this->isGranted($attributes, $object)) {
        throw $this->createAccessDeniedException($message);
    }
}
```

and 

`Symfony\Component\Security\Core\Exception\AccessDeniedException`
```
public function __construct($message = 'Access Denied', \Exception $previous = null)
{
    parent::__construct($message, 403, $previous);
}
```

Difference is really small (`.`), but in our case it breaks our Twig `if` statement (not displaying default message at 403 page) when moving to controller's method instead of manually throwing exception. Of course I can fix our `if`, but I think those messages should be identical.

I propose introducing constant in `AccessDeniedException` which should be used as default value in constructor and also in `denyAccessUnlessGranted()`.

**Comment by iltar** [comment]
I agree that the message should be equal. That being said, maybe the message should move to a constant somewhere. My guess is that the message with the dot is correct.

_PS. I think that Symfony should start using translation keys instead of using default English messages to avoid these inconsistencies._

**Comment by Rvanlaak** [comment]
:+1: on translation keys, but that would introduce the translator as a dependency to every component right? ;-)

**Comment by fabpot** [comment]
Let's add a dot and done.

**Comment by Wirone** [comment]
@fabpot I insist on class' constant, because then it's possible to use it elsewhere, like `if ($message == AccessDeniedException::DEFAULT_MESSAGE)`. Using hardcoded strings may sooner or later be "problem" for someone, for example when you decide to remove the dot ;-)

**Comment by fabpot** [comment]
I'm against the constant for the exact reason you mention. You should never compare an exception message, it's not reliable.

**Comment by Wirone** [comment]
I would not dare to argue with you, @fabpot, but still I think class' const would at least guarantee consistency between `FrameworkBundle` and `Security` component (`denyAccessUnlessGranted()` should - in my opinion - always use the same default message as `AccessDeniedException`, class const would be simplest solution for that). I am convinced that nobody will remember this relation between 2 strings since they're in separate repos, so this inconsistency can raise again in any time.

It is up to developers if they want to rely on this message or not.

**Comment by Wirone** [comment]
@Rvanlaak as far as I see there are other exceptions in `Security` component which already have implemented `getMessageKey()` method and translations are in component's resources. So maybe `AccessDeniedException` also could have translation key.
