### ISSUE TITLE
Missing Blank Translation Messages

### ISSUE THREAD

**Issue by gnorby88** [symfony/symfony#15094]
Hi. I use JMS Translation Bundle and i generated and fixed translation messages but not all.
In Debug Toolbar -> Translation Stats i have blank messages which i can not translate.

![image](https://cloud.githubusercontent.com/assets/12827951/8349647/beae6044-1b1e-11e5-8341-d92dc398dc77.png)

How can i fix it ?

**Comment by xabbuh** [comment]
@gnorby88 Can you please check if your issue is related to #15048?

**Comment by xabbuh** [comment]
@gnorby88 #15048 has been merged. So I'm going to close here. Please let me know if the fixed provided there does not solve your issue.
