### ISSUE TITLE
[OptionsResolver] better readability, can provide PR

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#15103]
i would like to change this output from:
![bildschirmfoto 2015-06-25 um 15 03 28](https://cloud.githubusercontent.com/assets/995707/8354842/77e87d84-1b4b-11e5-92d5-a8050586d13f.png)

to:
![bildschirmfoto 2015-06-25 um 15 03 32](https://cloud.githubusercontent.com/assets/995707/8354848/7c8a2504-1b4b-11e5-9190-63771f51aa58.png)

what do you think?
If you like i can provide a PR

Oskar

**Comment by stof** [comment]
multiline exception messages are not always more readable. In logs for instance, newlines are often breaking things. So I'm not sure about this change.

However, I agree that the current exception message is not very readable.

**Comment by OskarStark** [comment]
hmm, you are right, let's see what the others say

**Comment by iltar** [comment]
Would it be possible for that specific component to call the logger and tell with `debug` which options _are_ available?

**Comment by OskarStark** [comment]
could be solution and should technically be possible, but do we want this?

what do you think @fabpot ?

**Comment by fabpot** [comment]
I agree with @stof that depending on the context, one or the other might be better. So, I think keeping the current way is better.

**Comment by OskarStark** [comment]
:+1:
