### ISSUE TITLE
[Console] Warning on console {command} -h

### ISSUE THREAD

**Issue by mikaelcom** [symfony/symfony#15105]
I have a repeated warning when I execute `php console wsdltophp:generate:package -h`.

My console file is here: https://github.com/WsdlToPhp/PackageGenerator/blob/develop/console.

My command class is here: https://github.com/WsdlToPhp/PackageGenerator/blob/develop/Command/GeneratePackageCommand.php.

The warning is: `PHP Warning: str_repeat(): Second argument has to be greater than or equal to 0 in /Users/jaan/Sites/PackageGenerator/vendor/symfony/console/Descriptor/TextDescriptor.php on line 82`.

Is it due to my own misunderstanding of how to use the `addOption` method? Or is it due to the Console component?

Thanks :smile:

**Comment by xabbuh** [comment]
see #15122
