### ISSUE TITLE
[Translation] Support context in XLIFF format

### ISSUE THREAD

**Issue by ste93cry** [symfony/symfony#15104]
Hello,
I faced for a project I'm working on a problem with the XLIFF format used by the translator component. I have two translations with the same source, but that are used in different contexts. Some time ago [this](http://symfony.com/blog/new-in-symfony-2-6-added-support-for-xliff-notes) news was posted saying that it was added support for the `note` tag and an example was given with the same `source` value but different meanings: it is exactly what I'm trying to do. However, it seems that the note tag is supported only on dumping because I'm unable to specify the context in the trans filter to get the right translations. I also tried using **JMSTranslationBundle**, however it appears that even using the `desc` and `meaning` filters I'm unable to solve this problem. I had a look at the translator cache in `app/dev` and I don't see anywhere the notes. The same issue was discussed in #2229. I think this is an important missing feature, and although I don't have the knowledge to implement this feature I would really like to see it in a near future.

**Comment by nud** [comment]
Same feature exists in gettext: https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

**Comment by nicolas-grekas** [comment]
Closing: this hasn't this been fixed already, see
https://symfony.com/blog/new-in-symfony-3-4-added-support-for-xliff-2-0-notes
