### ISSUE TITLE
[Filesystem] mirroring a symlink copies absolute file path

### ISSUE THREAD

**Issue by danepowell** [symfony/symfony#15118]
When using mirror(), I would expect that relative symlinks stay relative after they are copied, but instead they are converted to absolute references to the source directory.

For instance, given this symlink in the source directory:
```/source/bin/behat -> ../vendor/behat/behat```
(implicitly ```/source/bin/behat -> /source/vendor/behat/behat```)

After mirroring that directory, the expected result is:
```/target/bin/behat -> ../vendor/behat/behat```
(implicitly ```/target/bin/behat -> /target/vendor/behat/behat```)

But the actual result is:
```/target/bin/behat -> /source/vendor/behat/behat```

This was originally fixed in #9866, and then regressed in a8b8d33e942566fb858e78d35aa843d7fe77cb11

**Comment by COil** [comment]
:+1:
