### ISSUE TITLE
Netbeans Support?

### ISSUE THREAD

**Issue by qohelet** [symfony/symfony#15125]
Hi!
It appears there were some changes in Symfony and it doesn't work with Netbeans properly any more.
There are problems with the console (selecting symfony-2.7.zip or symfony-standard-2.8.zip):
![auswahl_124](https://cloud.githubusercontent.com/assets/13061154/8391655/ddf2dbf0-1ceb-11e5-9791-957b083c1be2.jpg)
![auswahl_125](https://cloud.githubusercontent.com/assets/13061154/8391664/09d8d65c-1cec-11e5-8c98-bc72fef22aaa.jpg)

I don't know how to make the console work with Symfony 2?

Symfony 1 seems to be completely impossible to use. Netbeans detects as default-script /usr/local/bin/symfony but can't work with it at all, symfony-standard-2.8.zip instead of the default-script leads to the same result:
![auswahl_126](https://cloud.githubusercontent.com/assets/13061154/8391675/68282348-1cec-11e5-9b65-f78c1633ddcc.jpg)

Unfortunately most tutorials online are outdated (2009-2010). Is there still any support for Netbeans or any manuals around?
Thank you

**Comment by Tobion** [comment]
If there is a problem in netbeans, you should open an issue on netbeans not on symfony.
Also I don't understand why you talk about symfony 2 and then suddenly jump to symfony 1.
