### ISSUE TITLE
Composer install fails with this message on hhvm

### ISSUE THREAD

**Issue by mseshachalam** [symfony/symfony#15124]
Generating autoload files
Updating the "app/config/parameters.yml" file
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
Unable to parse file "/home/shippable/workspace/src/bitbucket.org/abbiya/cuckoo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/../Resources/config/web.xml".
[InvalidArgumentException]
[ERROR 3067] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse the XML resource 'file:////home/shippable/workspace/src/bitbucket.org/abbiya/cuckoo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd'. (in in_memory_buffer - line 8, column 0)
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
[RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command.

**Comment by Macsch15** [comment]
In your php.ini put
```
hhvm.libxml.ext_entity_whitelist = file,http,https
```

**Comment by Tobion** [comment]
facebook/hhvm#3797

Please use the search before opening issues.

**Comment by mseshachalam** [comment]
@Tobion I understand you frustration. I haven't searched for it, feeling sorry for that. Thank you for giving me the input. Please remember that the number issues are not measure for the popularity for a repository. Thanks again.
