### ISSUE TITLE
[Security] Allow to override access decision strategy in isGranted

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#15130]
While rewriting the access decision strategy documentation, I discovered that it probably is quite strange to have this configured at a global level. To me, it makes more sense to specify the strategy on a usage basis.

For instance, imagine a `PersonalPost` object. 2 voters are related to this object: `UserIsAuthorOfPostVoter` and `UserIsAdminVoter`. If one of these grants access, the user is allowed to see this post. Strategy: *affirmative*

Now imagine the same application to have a `ViewRestrictedPost` object. This one has a `UserIsMemberVoter` and a `UserIsOlderThan18Voter`. In order to see this post, both voters should grant access. Strategy: *unanimous*

At the moment, unless I'm missing something, this is not possible to do without extending `AccessDecisionManager` to add a feature like this.

I imagine something like this would be much nicer:

```pp
if ($authorizationChecker->isGranted('VIEW', $personalPost, 'affirmative')) {
    // ...
}

if ($authorizationChecker->isGranted('VIEW', $viewRestrictedPost, 'unanimous')) {
    // ...
}
```

**Comment by iltar** [comment]
If I understand it correctly, the caller should now know about what's going to vote. IMO that's the wrong and the voter should determine whether it should or should not vote and what it should vote for the type of object passed along.

**Comment by WouterJ** [comment]
Hmm, you have a good point there, @iltar. But then, is there not another way we unglobal this. I don't believe a global setting is correct in this case.

**Comment by fabpot** [comment]
The is indeed not really configurable as changing the default value can lead to weird behavior with third-party bundles. That's probably a setting that we not document prominently; use cases are only when not using the security layer in Symfony itself.

**Comment by javiereguiluz** [comment]
I'm closing this because the access decision strategy is a feature we don't want to change in Symfony. I've opened https://github.com/symfony/symfony-docs/issues/6339 to try to improve the docs of this feature. Thanks!
