### ISSUE TITLE
[Translation] Disable translation of labels when expanded is used and choice_translation_domain is false

### ISSUE THREAD

**Issue by n0rbyt3** [symfony/symfony#15140]
Hi,

I use an entity field type and the choice_label option to render the label of the field "title". The "title" column contains a fully localized string, but when using the {{ form_label }} inside twig, the title will be translated using the messages domain (and marked as missing in the profiler). This can result to unexpected labels.

```
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('groups', 'entity', array(
        'class' => 'MyTestBundle:Group',
        'choice_label' => 'title',
    ));
}
```

There should be a way to disable the translation of the label completely and show the label as-is, but escaped. Setting "translation_domain" or "choice_translation_domain" to FALSE (as it should be done to disable labels completely) has no impact. The only workaround I have found is to use a non-existing domain, but this is a hack and will also call the translator. I also don't want to override the default label widget.

Disabling the translation of labels could also improve performance because no message catalogues have to be read by the translator.

**Comment by Tobion** [comment]
What  symfony version are you using?

**Comment by aitboudad** [comment]
Hi @n0rbyt3 
The issue is not only for `choice_label` and I think we must provide a way to skip translation for form field at all.

I would propose to  disable translation when `translation_domain` is set false something like `choice_translation_domain`

**Comment by Tobion** [comment]
I don't see why `choice_translation_domain: false` shouldn't do the trick here. Maybe you have a custom form theme, overwritten form blocks?

**Comment by n0rbyt3** [comment]
@Tobion I use symfony 2.7.1

I don't have a custom form theme and I don't want to use one. The disadvantage is that the whole ```form_label``` widget has to be overriden. If symfony changes the logic, I have to change it, too. It's too much overhead. And I also don't override any existing form block.

The current ```form_label``` widget contains the logic for not rendering labels (if label is set to false) so an extra condition to ```translation_domain: false``` is enough for all labels.

```choice_translation_domain: false``` doesn't work, because it will only override the original ```translation_domain``` in the form view. The template logic is not affected.

**Comment by stof** [comment]
Well, ``choice_translation_domain`` is meant to handle exactly this case. So it looks weird if it does not (unless you are using the ``expanded`` option to display it as radio buttons, as this indeed does not use the ``choice_translation_domain`` at all).

**Comment by n0rbyt3** [comment]
I use checkboxes, sorry, I missed ```expanded => true``` and ```multiple => true``` in my options. But independant of that the label should never gets translated when ```choice_label``` is used.

**Comment by stof** [comment]
@n0rbyt3 saying it should never be done seems wrong to me. We have no idea what the callable could be. It is perfectly valid to return translation keys from there.
``choice_translation_domain`` is what controls whether translations are used for choice labels or no (and the ``entity`` type disables translations by default).
We should fix the case of expanded forms to use this option though.

**Comment by Rvanlaak** [comment]
The `choice_translation_domain` handling also seems to be wrong for the `birthday` field type.

**Comment by stof** [comment]
Well, the birthday field type is not a choice type. It does not have a ``choice_translation_domain`` option. I think your issue there is a different one @Rvanlaak

**Comment by Rvanlaak** [comment]
Okay, you're right. But shouldn't the translation domain be implemented for many more types then?  The `DoctrineType` for instance does make use of the `choice_translation_domain` but I can not seem to get it working:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L310

**Comment by stof** [comment]
The doctrine type is a special choice type.

and as I said previously, the ``choice_translation_domain`` currently does not work for expanded choice forms, only for non-expanded ones (which is why I tagged this as bug and renamed the title a bit).

**Comment by arturmelo** [comment]
I've actually also stumbled upon this issue last friday and just made a [quick fix](https://github.com/Restless-ET/symfony/commit/5980156a39b57146744e953d7fd9501814179687) on [my fork](https://github.com/Restless-ET/symfony/tree/fix-choices-translation-for-expanded-choice-type).

I don't know if this is the best solution for this, but I can create a PR from this if you guys want.
I didn't make one yet because I've not verified the PHP templating yet.

**Comment by Restless-ET** [comment]
I've actually also stumbled upon this issue last friday and just made a [quick fix](https://github.com/Restless-ET/symfony/commit/5980156a39b57146744e953d7fd9501814179687) on [my fork](https://github.com/Restless-ET/symfony/tree/fix-choices-translation-for-expanded-choice-type).

I don't know if this is the best solution for this, but I can create a PR from this if you guys want.
I didn't make one yet because I've not verified the PHP templating yet.

**Comment by jvasseur** [comment]
I have a fix in mind that i think would be a bit more clean, i will make a PR when i come back from work.

**Comment by Senorihl** [comment]
Hi ! Is it related to `translation.WARNING: Translation not found. {"id":"Any label","domain":false, "locale":"fr"} []` ? Since my form generate fields from saved config I don't save translation keys but localized labels so I set `translation_domain` to `false`.
