### ISSUE TITLE
Bug in Request::createFromGlobals() when 80 port was explicitly specified

### ISSUE THREAD

**Issue by Hacker-CB** [symfony/symfony#15157]
We need to request http://192.168.0.1:80/test/

Usually this request is submitted like:
GET /test/

But some clients provides full path inside request body like:
GET http://192.168.0.1:80/test/

In this case:

$request=Request::createFromGlobals()
$request->server->parameters['QUERY_STRING'] contains value "80"

Seems that there is a bug.

How to represent:

export http_proxy="http://192.168.0.1:80/test/"
curl -X POST http://192.168.0.1:80/test/

**Comment by phansys** [comment]
According [IETF's RFC-2616](http://tools.ietf.org/html/rfc2616#section-5.1.2), the request URI is required to be absolute when the request is being made to a proxy; so it would be supported.

**Comment by phansys** [comment]
@Hacker-CB, which version are you using (Symfony / PHP)?
I tried to reproduce your issue but in my case, ```QUERY_STRING``` still empty:
```bash
curl --proxy http://test.local:80/test -X POST http://test.local:80/test
```
```php
$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
var_dump($request->server->get('QUERY_STRING')); // outputs: string '' (length=0)
```

**Comment by stof** [comment]
Well, I guess it has something to do with the config of your webserver, as it is the one sending such info to PHP.

**Comment by phansys** [comment]
Yes, maybe @Hacker-CB could try this test directly with the built-in server?

**Comment by jakzal** [comment]
@Hacker-CB any feedback?

**Comment by xabbuh** [comment]
closing due to the lack of feedback

@Hacker-CB Feel free to reopen when you can provide more information.
