### ISSUE TITLE
Symfony 2.7 upgrade breaks twig function asset() with version property

### ISSUE THREAD

**Issue by pjordaan** [symfony/symfony#15156]
In my project I upgraded to Symfony 2.7. After doing this it seems that the twig function asset() broke for me

I had
```twig
{{ asset('/bundles/blah.js', version=timestamp) }}
```

After the upgrade I had to write:
```twig
{{ asset('/bundles/blah.js') }}?{{ timestamp }}
```
If I didn't it returns in an error in AssetExtension, method getLegacyAssetUrl() line 111
It does ```$f = new \ReflectionProperty($currentVersionStrategy, 'format');``` there. $currentVersionStrategy is an instance of EmptyVersionStrategy which has no 'format' property, so it throws an error here.

I have no idea what is the good solution.

**Comment by iltar** [comment]
Possibly related to #14692

**Comment by xabbuh** [comment]
@pjordaan Can you please test if the changes from #15183 fix your issue?

**Comment by pjordaan** [comment]
yes, it was fixed, thx!
