### ISSUE TITLE
[HttpKernel][DX] Question: Unsupported Environments

### ISSUE THREAD

**Issue by zanderbaldwin** [symfony/symfony#15165]
Would there be any benefit to add something like `EnvironmentNotSupportedException` to the HttpKernel component? Would it be an improvement or just a wasted class?

**Context**: We have a console tool that spins up instances of a Symfony application with PHP's built-in server for testing, specifying the environment as an argument rather than a front-controller for each environment.

It would also help help with the error message in the terminal when an incorrect environment is passed to the console application, especially for those new to Symfony or new to developing for the console:

```bash
$ php app/console list -e badenv

  [Symfony\Component\HttpKernel\Exception\EnvironmentNotSupportedException]
  The string "badenv" is not a valid environment registered with the application.

  # Instead of...

  [InvalidArgumentException]
  The file "app/config/config_badenv.yml" does not exist.
```

Whether or not it should be thrown from `AppKernel::registerContainerConfiguration()` is another matter.

---
It's just an idea, though I'm not sure whether it would be a benefit to the Symfony community. Ideas?

**Comment by javiereguiluz** [comment]
@zanderbaldwin thanks for proposing this improvement. At Symfony project we're always looking for ways to improve error messages, so this is something to be considered.

However, the main problem I see it that environments are not formally registered anywhere. Front controllers can be named as you wish (`app_<env name>.php` is a convention, not a mandatory thing) and configuration files can also be named as you want (again, `config_<env name>.yml` is just an optional convention).

**Comment by zanderbaldwin** [comment]
I think that adding this exception to the framework would be good for people who wish to code in the functionality themselves. This wouldn't bring in any backwards-compatibility issues.

There would then be an opportunity to formalise environments in versions `2.8` or `3.0`.
An alternative to formalising environments would be to add something similar to the following in the [`symfony/symfony-standard`](https://github.com/symfony/symfony-standard) project, allowing end-users to remove and/or change as they see fit:

```php
<?php

use Symfony\Component\HttpKernel\Exception\EnvironmentNotSupportedException;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    // ...

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        if (!file_exists($config = $this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml')) {
            throw new EnvironmentNotSupportedException(sprintf(
                'The string "%s" is not a valid environment registered with the application.',
                $this->getEnvironment()
            ));
        }
        $loader->load($config);
    }
}
```

**Comment by fabpot** [comment]
As explained by @javiereguiluz, we don't "manage" environments in Symfony per se. And as demonstrated by your example above, that's something that you can easily add if that makes sense for you, no need to have built-in support in Symfony.

**Comment by zanderbaldwin** [comment]
Fair enough! It was a suggestion that I found useful in my own projects for the benefit of console end-users, so I'll keep using it - but since most developers wouldn't even bother using the exception themselves I can see that its addition to the framework doesn't have that much merit. Thanks for the feedback, @javiereguiluz and @fabpot! :)
