### ISSUE TITLE
[Form][Translation] Translate entity options

### ISSUE THREAD

**Issue by hiddewie** [symfony/symfony#15168]
I have the following setup. 
- A form with a single `entity` field (`multiple = false`, `expanded = false`).
- An array of `Role` entities, with at least the propery `name`. The property `name` is untranslated and contains the key of the translation.
- Symfony 2.7.1

I want to translate the options of the rendered `select`, just like the thing which happens normally when using a `choice` with normal key-value elements.

Code:
```
$builder -> add('role', 'entity', array(
        'class' => 'MyBundle:Role',
    	'choices' => $this -> roles,
       	'choice_label' => 'name',
       	'expanded' => false,
        'label' => 'admin.privileges',
));
```

**Comment by Tobion** [comment]
Enable the choice_translation_domain: http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates#added-choice-translation-domain-domain-to-avoid-translating-options

**Comment by hiddewie** [comment]
Thank you, I probably overlooked that new option.

**Comment by stof** [comment]
yeah, the ``entity`` type disables translations for choices by default, because returning a translation key from there is quite uncommon. so disabling them is a better default.
