### ISSUE TITLE
[Form][PhpEngine]  Breaking path change?

### ISSUE THREAD

**Issue by dragu** [symfony/symfony#15178]
Hi,

I've updated symfony forms from 2.6.4 to 2.7.1 and I get Exception: **No block "form_start" found while rendering the form.**

My form starts with: *$view['form']->start($form);* and this line causes problem. I took a deeper look and found that PhpEngine loads file *form_start.html.php* from *symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Resources/views/Form/form_start.html.php* in 2.6.4

It also try to load it from the same path in 2.7.1 but the file is located here: *symfony/framework-bundle/Resources/views/Form/form_start.html.php*

I use form component in non-symfony application if it could make a diffrence.

**Comment by stof** [comment]
@dragu how does your code configuring the form theme looks like ?

**Comment by dragu** [comment]
![image](http://replygif.net/i/1216.gif)

You've got the point. My TemplateNameParser was initiated with old path. Thanks

**Comment by stof** [comment]
@dragu I suggest you to avoid hardcoding the path to where FrameworkBundle get installed, and get it from the location of the code instead. You can have an example in https://github.com/symfony/symfony/blob/564c8e1ebe81231f678f431f6ff41b182c7dfe7f/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L670-674 for instance, where FrameworkBundle looks for the path to the Validator component

**Comment by dragu** [comment]
@stof quite a good idea, thanks
