### ISSUE TITLE
router:match throws a ResourceNotFoundException if route doesn't match

### ISSUE THREAD

**Issue by sberlinches** [symfony/symfony#15177]
I'm with SF2.7.1 and according to documentation:
http://api.symfony.com/2.0/Symfony/Component/Routing/Router.html#method_match

$router->match('/nonexistent-path/');
Must return false, but throws a ResourceNotFoundException.

**Comment by jvasseur** [comment]
You are looking at an old verions of the documentation, the documentation for Symfony 2.7 (http://api.symfony.com/2.7/Symfony/Component/Routing/Router.html#method_match) gives the correct method signature.

**Comment by sberlinches** [comment]
An alternative to avoid an exception?
I need handle that behaviour.

**Comment by xabbuh** [comment]
@sberlinches You could still catch the exception and do whatever you need to do in case the route does not match.
