### ISSUE TITLE
[Form] DefaultChoiceListFactory::flatten disrespects choices with same label different value

### ISSUE THREAD

**Issue by alaczi** [symfony/symfony#15181]
With Form version 2.7+

Imagine a situation of an expanded grouped choice field:

```php
$choices = array(
    'light' => array(
        'blue' => 'lightblue',
        'red' => 'lightred'),
    'dark' => array(
        'blue' => 'darkblue',
        'red' => 'darkred')
    );
$builder
    ->add('colors', 'choice', array(
        'choices' => $choices,
        'label' => false,
        'expanded' => true,
        'multiple' => true,
        'choices_as_values' => true,
    ));
```
With some templating magic you can come up something like this (and so, there is a reason to use grouping with expanded choices)..

![grouped_expanded_choice_list](https://cloud.githubusercontent.com/assets/3229101/8480836/e380bbc4-20d7-11e5-8e9e-635fdbee0527.png)

Now, the problem is that DefaultChoiceListFactory::flatten will merge the darkblue and lightblue into the same value key (both checkboxes will have the value="0") and upon postback the third checkbox value will be lightblue instead of the properly selected darkblue.
This concept works well with Symfony Form 2.6.

**Comment by Tobion** [comment]
Fixed by #15061
