### ISSUE TITLE
[Console] Closing stdout with >&- causes an error

### ISSUE THREAD

**Issue by amyboyd** [symfony/symfony#15180]
When closing the stdout in bash, using `>&-`, this error occurs in Symfony 2.7:

	$ app/console debug:config >&-
	PHP Warning:  fopen(php://stdout): failed to open stream: operation failed in /home/citypantry/project/api/vendor/symfony/symfony/src/Symfony/Component/Console/Output/ConsoleOutput.php on line 51
	PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The StreamOutput class needs a stream as its first argument.' in /home/citypantry/project/api/vendor/symfony/symfony/src/Symfony/Component/Console/Output/StreamOutput.php:50
	Stack trace:
	#0 /home/citypantry/project/api/vendor/symfony/symfony/src/Symfony/Component/Console/Output/ConsoleOutput.php(51): Symfony\Component\Console\Output\StreamOutput->__construct(false, 1, NULL, NULL)
	#1 /home/citypantry/project/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(120): Symfony\Component\Console\Output\ConsoleOutput->__construct()
	#2 /home/citypantry/project/api/app/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
	#3 {main}
	  thrown in /home/citypantry/project/api/vendor/symfony/symfony/src/Symfony/Component/Console/Output/StreamOutput.php on line 50

**Comment by jaytaph** [comment]
The fact that somebody or something closed a descriptor, should we reopen that handle?

**Comment by xabbuh** [comment]
What does `>&-` do?

**Comment by amyboyd** [comment]
It closes a file descriptor. See http://blog.apokalyptik.com/2007/10/24/bash-tip-closing-file-descriptors/

exec 0>&- # close stdin
exec 1>&- # close stdout
exec 2>&- # close stderr
