### ISSUE TITLE
Form builder renders attritbute required even with required set to false in default options

### ISSUE THREAD

**Issue by rrajkomar** [symfony/symfony#15191]
Hello,

I have the following code in my custom Form Type  which include choice lists, inputs and textareas and even though this code is present and in the profiler the required option and variables correctly resolve to false, all fields in my form have the required attribute set to required.

public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([

            'data_class' => '{Namespace\To\MyEntity}',
            'required' => false,
            'method' => 'POST'
        ]);
	}

**Comment by rrajkomar** [comment]
Edit : I found the cause of my issue, the rendering of the form is also based on the doctrine entity annotations (nullable :true/false).
Based on that information, how can I define a filtering form where the non-nullable fields would still be allowed a null value (no required attribute rendered)

**Comment by rrajkomar** [comment]
I just tried to solve this issue by adding a separate model layer to avoid the doctrine orm annotations on my validation classes and the issue stil appears everytime I use SF Assert annotations, the required options is not taken into account and neither are the specified validation groups : the required attribute gets generated everytime I use an Assert annotations.

Any advice on how to fix this issue ?

**Comment by Tobion** [comment]
> I have the following code in my custom Form Type which include choice lists, inputs and textareas

You have to set required = false on each individual field (inputs etc), and not on the compound form type.

**Comment by rrajkomar** [comment]
Actually, I found out that the Doctrine annotations wasn't responsible for this issue but the fact that the validation_groups is not taken into account when generating the form for the NotBlank annotations.

see #15314
