### ISSUE TITLE
Translation: XliffFileDumper metadata

### ISSUE THREAD

**Issue by timwhitlock** [symfony/symfony#15190]
Would it be possible to add "generator" metadata to XLIFF exports from the Translator component? 

I'm thinking something like this, using the specified [`<tool>`](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#tool_elem) element:
```xml
<file tool-id="symfony" source-language="en">
    <header>
        <tool tool-id="symfony" tool-name="XliffFileDumper" tool-version="2.7" />
    </header>
</file>
```
This will allow other software to handle specific intentions of the format. I currently export three different variations of XLIFF from my software, including one for Symfony and one for XCode. Importing files into the software is the hard part without a hint as to what flavour it is.

I'd contribute a code change myself, but I thought the maintainers would prefer to decide on best practice here.

**Comment by xabbuh** [comment]
@timwhitlock Do you have an example how other frameworks/tools handle this?

**Comment by timwhitlock** [comment]
Below is exported from my install of XCode 6.2

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd">
  <file original="en.lproj/Localizable.strings" source-language="en" datatype="plaintext">
    <header>
      <tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="6.2" />
    </header>
    <body>
      <trans-unit id="foo">
        <source>Foo Bar</source>
      </trans-unit>
    </body>
  </file>
</xliff>
```
Note that I've removed XCode's incorrect usage of the `build-num` attribute.

**Comment by xabbuh** [comment]
@timwhitlock Thanks

I'm not sure if this will help many people. But at the least it really does not hurt anyone and if it makes some peoples' lifes easier, I am not against this. :)

@aitboudad What do you think?

**Comment by aitboudad** [comment]
me too I am not against, @timwhitlock can you work on it  ?

**Comment by timwhitlock** [comment]
OK, I'll have a go. Thanks.
