### ISSUE TITLE
Security bug? on HttpException

### ISSUE THREAD

**Issue by bnd170** [symfony/symfony#15197]
I recently upgraded my version of Symfony from 2.3 to 2.7.

On my project I have a sidebar, which show the login and, if the user is logged, their user panel, with his avatar, his nickname and a couple of options like edit profile.

I have installed FOSUserBundle for it.

When Symfony2 launch an 404, 500, 401... exception error, randomly, the avatar and nickname displayed on the control panel, modified, showing data of another user.

In version 2.3 I had this never occurred.

It may be a bug¿

**Comment by phansys** [comment]
Symfony doesn't handle these concepts ("avatar", "nickname", "control panel"). Please, ask for help in the issue tracker of [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/issues) if you think there is a issue in the bundle.

**Comment by bnd170** [comment]
The problem is not with "avatar", "nickname" or "control panel" is with security context, because it showing data of another user when an exception throwed.

If im loged with my account for example, "bnd170", when Symfony throws a 404 error, on user panel shows "ivan" for example. Its so randomly.

**Comment by phansys** [comment]
Which user provider you're using? Can you try to reproduce it with ```in_memory``` provider by instance?

**Comment by bnd170** [comment]
To reproduce it with ´in_memory´ ill must to change a lot of things.

There is my provider:

´´´
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
´´´

**Comment by dosten** [comment]
If this is a security issue, this is the wrong place to discuss. @bnd170 please send an email to security [at] symfony.com

**Comment by bnd170** [comment]
Ok, thanks a lot @dosten

**Comment by javiereguiluz** [comment]
Closing it because the discussion was moved to the special Security mailing list.
