### ISSUE TITLE
[DependencyInjection] Inlining of large parameters

### ISSUE THREAD

**Issue by unkind** [symfony/symfony#15203]
Sometimes parameters can be large (long text, auto-generated maps, etc.) and we've noticed some performance impact because of inlining (the same parameter was injected in several services).

Does it make sense to introduce some kind of inlining strategy for `PhpDumper`? For instance, if value is larger than 1 KB, then do not inline parameter (i.e. use `$this->getParameter('large_parameter')` method call) in `PhpDumper::dumpParameter`. This also means that `ResolveParameterPlaceHoldersPass` should not resolve arguments.

**Comment by xabbuh** [comment]
Not sure if that really makes sense. Imo this sounds more like a use case where container parameters are simply not the right solution.

**Comment by fabpot** [comment]
I agree with @xabbuh here.

**Comment by unkind** [comment]
Of course there are other ways, we can use some kind of "config" dependency with lazy loading, etc., but can you clarify why it is "simply not right solution"? It works well without inlining, just pure infrastructure issue.

**Comment by xabbuh** [comment]
Well, the parameters are part of the container which will be loaded on every request. So having large parameters makes the container really big which isn't something you should usually do imho.

**Comment by unkind** [comment]
I think large parameters are not bad per se, but inlining them is. Having 5 KB parameter may be OK, but having 2 services with this parameter results in additional 10 KB (default value + 2 inlined ones), and moreover, PHP creates this parameter again (in case of `$this->getParameter('large_parameter')` PHP would use copy-on-write).

Also container can handle large parameters transparently. For example, leave them as `$this->getParameter('large_parameter')` and require file with that large parameter when it needed (lazy loading).

**Comment by fabpot** [comment]
I don't think having a 5k parameter is ok. Parameters are simple key/value pairs for making your app configurable. I fail to see how a configuration value could be as large as 5k.

**Comment by unkind** [comment]
Event listeners configuration can be more than 5 KB, routing configuration, etc. By now, you don't see doubled big parameter with listeners configuration, because it compiled into several method calls:
```
$b->addListenerService('foo', array(0 => 'bar_listener', 1 => 'onBar'), 0);
$b->addListenerService('baz', array(0 => 'qux_listener', 1 => 'onQux'), 0);
...
```
But with the following PR it will be simple parameter: #12521. It means that listeners configuration will be doubled (default value + inlined argument of `CompiledEventDispatcher`).

**Comment by javiereguiluz** [comment]
For what is worth, Node.js applies an optimization strategy similar to @unkind's idea:

  * Functions are always inlined ... unless they are "long"
  * Long function = contains more than 600 characters (including white spaces) or more than 196 AST nodes.

Source: http://jayconrod.com/posts/54/a-tour-of-v8-crankshaft-the-optimizing-compiler

**Comment by javiereguiluz** [comment]
At first I agreed with this proposal, but now I'm 👎 

Some context: I used a bundle that processed some config and stored it in a container parameter. This param was ~150 KB and it was injected in several services. At the end, I think that the problem wasn't Symfony inlining this param, but creating such a big param. Now I use Doctrine Cache (to be replaced soon by Symfony Cache) and store that config in the cache instead of a param.

So instead of a bug, I consider this behavior an early warning about when a param should be replaced by some cache mechanism or any other strategy.

**Comment by unkind** [comment]
@javiereguiluz you suggest to take care of such things manually. I suggest to make Container take care of itself, because Container knows about himself much better than others. After all, Container can use cache too.

By the way, did you notice #12521? What do you suggest to do in order to avoid big parameter here?

**Comment by javiereguiluz** [comment]
@unkind I'm sorry but I must close this as "won't fix" because at least 3 Core Team members are against it. Luckily, since this issue was open, Symfony added a new Cache component that could be used to store those large parameters.
