### ISSUE TITLE
[RFC] New component bootstrap.php.cache

### ISSUE THREAD

**Issue by liuggio** [symfony/symfony#15209]
It would be great to have a new component that incorporate the features that  bootstrap.php.cache  have with some improvements.

The key features:
- It could be used without a Symfony project.
- Ability to define userland classes into it (maybe into the [composer extra fields](https://getcomposer.org/doc/04-schema.md#extra)? )
-  It could be used only on production.

**Comment by iltar** [comment]
There is already a similar mechanism to "cache" code in the cache directory. The bootstrap is rather "hard"-coded at the moment. Maybe those features can be combined into a new component?

I'm not sure if it's a loose component at the moment.

**Comment by fabpot** [comment]
Everything you mention here is already possible:

* the "magic" is in the ClassLoader component
* in a Symfony project, you can add classes to a cache file in extensions.

**Comment by liuggio** [comment]
Yes it is, but the RFC was about a new explicit component to improve the expensive time autoloading classes.
