### ISSUE TITLE
[DX][Translator] Annotation to mark translation domain for controller

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#15211]
Twig already has the `trans_default_domain` since the beginning of 2012 via https://github.com/symfony/symfony/commit/ce6399e254d57fda8b4a98eab52bf79c57597507. It would be great if Controllers can also be marked to follow a certain translation domain, so the following code for translating Controller status messages can be cleaned up:

```php
// Simplified current situation
if ($status == true) {
    $this->get('translator')->trans('action.msg_success', array(), 'admin');
} else {
    $this->get('translator')->trans('action.msg_error', array(), 'admin');
}
```

```php
// Proposed situation

/**
 * @TranslationDomain("admin")
 * @Route("/admin")
 */
class MainController
{
}

// Or

/**
 * @TranslationDomain("admin")
 * @Route("/admin/index")
 */
public function indexAction()
{
    $this->get('translator')->trans('action.msg_success');
}

```
Because calling the translator service directly is recommended, and Twig uses an extension to keep track of the actual `default_trans_domain` implementing this would introduce an extra layer between the Translator and the Controller. 

https://github.com/symfony/symfony/issues/7135 already was closed because of that, but is there another way to solve this? By implementing an `Annotation` this could be bound to the controller class, or maybe also to an action.

**Comment by OskarStark** [comment]
:+1: like the idea

**Comment by aitboudad** [comment]
this look a nice idea, but we should provide a way to save the default domain in translator and then we can add Annotation in `SensioFrameworkExtraBundle`.

**Comment by xabbuh** [comment]
@aitboudad Is that needed? The solution could be to decorate the translator service with a custom one that makes it possible to exchange the default message domain (which could be done through the kernel events). But I agree that this should be done in SensioFrameworkExtraBundle if it gets implemented.

**Comment by aitboudad** [comment]
@xabbuh decorate the translator look good to me, who wants to work on it ? if no one I can work on it next week ^^

**Comment by Rvanlaak** [comment]
Also don't think the default translator should be touched. Do not know a lot about compiler passes or tagging services, but is that the way to go? 

Decorating the `translator` replaces it with another one right? How will this work for the `LoggingTranslator` on `DEV`?

**Comment by xabbuh** [comment]
@Rvanlaak The logging translator also just decorates the configured one.

**Comment by aitboudad** [comment]
@Rvanlaak right now we decorated the translator by two classes and I think it should be decorates after `LoggingTranslator` and `DataCollectorTranslator` (the last one as possible) to make sure we log the right domaine.

**Comment by Rvanlaak** [comment]
Is decorating the translator as late as possible just a matter of setting priority in the service definition? Or how can we do this, since the [Decorating Services chapter](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services) does not say anything about that.

**Comment by aitboudad** [comment]
setting priority for the compiler pass and not decorating, just registering `SensioFrameworkExtraBundle` after `FrameworkBundle` can solve the issue.

**Comment by Rvanlaak** [comment]
Then I'll dive into that, can't promise it will work but want to get a better understanding in creating annotations, decorating and compiler passes :+1: 

There also should be some sort of `enterNode` and `leaveNode` functionality as in https://github.com/symfony/symfony/commit/ce6399e254d57fda8b4a98eab52bf79c57597507 , should this happen based on the [`KernelEvents::REQUEST`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/HttpKernel.php#L128) and [`KernelEvents::RESPONSE`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/HttpKernel.php#L187)?

**Comment by sstok** [comment]
Be careful though with internal services (used during the controller execution that use the Translator service and don't provide an explicit domain for `trans()`.

What Twig does is set an internal variable thats used for every call to a translator method (just like passing the domain explicit when calling `trans()`) so it doesn't really change the original translator.

**Comment by ludekbenedik** [comment]
What about:

```php
public function indexAction()
{
    // Create decorated default translator
    $translator = $this->get('translator_factory')->createForDomain('admin');

    // Use "admin" as default domain
    $translator->trans('message1');
    $translator->trans('message2');
}
```

**Comment by Rvanlaak** [comment]
@aitboudad I did not found time for this yet, [you have](https://github.com/symfony/symfony/issues/15211#issuecomment-119104448)?

**Comment by aitboudad** [comment]
@Rvanlaak sure, here is an initial work https://github.com/aitboudad/SensioFrameworkExtraBundle/commit/d928ba230ee374254bb052b9b78fdbb3f8491cdf,  but I see one issue right now there is no way to limit this behavior for controller only, if we set default domain this change the default domain in twig too.

**Comment by Rvanlaak** [comment]
By which you mean that the same decorated translator is injected into Twig? Or isn't it injected and does Twig get it from the container in the extension? Otherwise changing priorities somewhere could solve that if I'm right?

**Comment by stof** [comment]
The issue with such feature is that it would force to have a global state in the translator and will not impact only translator calls done inside the controller (it is impossible to impact only the controller and not all other places using the translator, except by creating a separate translator service meant to be used in the controller, which would be really weird).
Twig can have this feature because ``{% trans_default_domain %}`` does not impact the translator.It impacts the template (changing the way it calls the translator). And this is possible thanks to the compiled nature of Twig: we have a chance to alter the code being executed.

**Comment by jvasseur** [comment]
This could be done by creating a trans shortcut method in the controller class (or in a trait) that gets the domain from the annotation and call the translator with the correct domain.

(Or a getTranslator method that returns a decorated translator instance)

**Comment by aitboudad** [comment]
Closing as there is no clean way to resolve the issue.
