### ISSUE TITLE
[Security] Ability to customize how token is serialized

### ISSUE THREAD

**Issue by Imunhatep** [symfony/symfony#15214]
Even if developer provides custom authentication listener, default ContextListener is the one responsible for serializing tokens.

I want to serialize tokens to json. Currently it could be achieved by configuring custom authentication provider as stateless and then manually register listener on "onKernelResponse", same as ContextListener does it. Is this official way to go or I'm missing something?!

**Comment by jakzal** [comment]
Tokens [are serialized with PHP's built in mechanism](https://github.com/symfony/security-http/blob/master/Firewall/ContextListener.php#L84). TokenInterface extends [Serializable](http://php.net/manual/en/class.serializable.php). All you need to do is to provide your own TokenInterface implementation, with a custom [serialization logic](https://github.com/symfony/Security/blob/master/Core/Authentication/Token/AnonymousToken.php#L69-L84).

What's the use case for serialising tokens as json?

**Comment by Imunhatep** [comment]
Thanks, but actually I can just apply [jsonSerializable](http://php.net/manual/en/class.jsonserializable.php) interface and use json_encode. serialize() is php built-in function, but it's Symfony2 that uses it, and there is no way (officially) to change this behaviour.

I want to use json cause generally it's shorter.

**Comment by javiereguiluz** [comment]
This feature request didn't gain much traction from the community, so let's close as "won't fix" (and hopefully is not needed thanks to the proposed alternative solution).
