### ISSUE TITLE
Missing check in Finder component for WindowsPipes.php

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#15215]
Composer does not work anymore here, i get this message:

```
←[37;41m                                     ←[39;49m
←[37;41m  [ErrorException]                   ←[39;49m
←[37;41m  fopen(): Filename cannot be empty  ←[39;49m
←[37;41m                                     ←[39;49m


←[32minstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optim
ize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]←[39m
```
(not sure why i am getting terminal codes, that's another issue)

I extracted the `composer.phar` and placed some debug points around fopen statements. Seems that this call fails `tempnam(sys_get_temp_dir(), 'sf_proc_stdout')` [here](https://github.com/symfony/Process/blob/e42521d38b122a2ad8a0efb4f9ccaad9dd04b90b/Pipes/WindowsPipes.php#L51-L52) 

There is no check if the function returns `false` and no exception is thrown.

Ini setting: `sys_temp_dir = "D:\dev\php\tmp"`. I forgot to recreate this directory when changing from a 64bits php to 32bits php.

PHP manual [states](https://secure.php.net/manual/en/function.tempnam.php): `If the directory does not exist or is not writable, tempnam() may generate a file in the system's temporary directory, and return the full path to that file, including its name.`

That `may` in `may generate a file` is not a promise that be relied on apparently

**Comment by xabbuh** [comment]
Indeed, looks like checking the return value of the `tempnam()` calls and providing better error messages would be more convenient.
