### ISSUE TITLE
[Form] expanded EntityType requires `data_class` option

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#15216]
Since we've updated to `2.7.1` the `EntityType` with `expanded: true` does not accept an entity as a default value anymore. A `LogicException` occurs when the user goes back to edit the entity, where `defaultData` is added to the builder:

> The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies\__CG__\AppBundle\Entity\Order\Subject. You can avoid this error by setting the "data_class" option to "Proxies\__CG__\AppBundle\Entity\Order\Subject" or by adding a view transformer that transforms an instance of class Proxies\__CG__\AppBundle\Entity\Order\Subject to scalar, array or an instance of \ArrayAccess.

```php
$defaultData = array();
if ($order->getSubject() instanceof Subject) {
	$defaultData['subject'] = $order->getSubject();
}
    	
$form = $this->createFormBuilder($defaultData)
    ->add('subject', 'entity', array(
       	'class' 	 => 'AppBundle:Order\Subject',
        'expanded'	 => true,
        'property'   => 'name',
    ))
    ->getForm()
;
```

The exception can be solved in two ways, by setting `expanded` to `false` or by defining `data_class`:

```php

// ...
    	
$form = $this->createFormBuilder($defaultData)
    ->add('subject', 'entity', array(
       	'class' 	 => 'AppBundle:Order\Subject',
       	'data_class' => 'AppBundle\Entity\Order\Subject',
        'expanded'	 => true,
        'property'   => 'name',
    ))
    ->getForm()
;
```
Looks like a BC break, think `EntityType` should resolve the `data_class` based on the `class` right?

**Comment by XWB** [comment]
You are not the only one experiencing this bug / BC break.

https://github.com/symfony/symfony/issues/14877

**Comment by Rvanlaak** [comment]
Thanks @XWB I'll close this one
