### ISSUE TITLE
[2.7] Twig_Error_Runtime: "The "native_profiler" extension is not enabled

### ISSUE THREAD

**Issue by chandon** [symfony/symfony#15228]
I'm using the templating service to internaly render mail templates in my application.

Since Symfony 2.7, when i do :

    this->get('templating')->render("TDP:Report:reportemailtemplate.html.twig")

i got this error only on "test" environment (but not with "dev" or "prod") : 

    request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "The "native_profiler" extension is not enabled in "TDP:Report:reportemailtemplate.html.twig" at line 1."

I don't manage to understand why i got this error

**Comment by utilisezlinux** [comment]
Clear your cache when switching environment…

**Comment by chandon** [comment]
Of course, the cache was cleared ! that's not the point... the problem is elsewhere

**Comment by utilisezlinux** [comment]
Ok, I was just giving my experience, I had the same problem until I cleared the cache between dev and prod switching. I did the thing twice, on 2 different servers… so there must be something else if it doesn't work for you.

**Comment by tumbochka** [comment]
The twig native profile extension is turned on automatically if the debug mode is on and turned off if the debug mode is off. So if you warming up the cache with debug mode on the twig templates are rendered with the profiler enabled. 
But if a test runs with debug off (for example Kris Wallsmith solution is used) the extension is disabled in the tests (but still enabled in pre-rendered templates), that cause the error.
Solution: before running tests clear the cache with debug mode off.
'''
app/console cache:clear --env=test --no-debug
'''
The cache will be cleared and warmed up without the twig profiler.

**Comment by chandon** [comment]
@tumbochka thanks for the tip. It was indeed linked to "debug" mode. 

I was testing by creating the kernel without any parameter. I've turned off debug while creating the kernel in my tests classes : 

    WebTestCase::createKernel(array('debug' => false));

This solve my issue.
