### ISSUE TITLE
[Console][Progress] regression of the progress bar

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#15227]
Actually, the regression of the progress bar is impossible :  [LogicException]  You can't regress the progress bar

I think this should be possible. It would make sense for example to show the memory usage of a long command against the memory limit. In this case, the regression of the progress bar make sense when the memory is released.

If you think this enhancement can be added, i can do the PR.

**Comment by stevenmusumeche** [comment]
+1

**Comment by iltar** [comment]
I don't agree with this in a progress bar nor is it the definition of progress. It sounds more like a percentage or absolute number bar that you're looking for.

**Comment by Tobion** [comment]
I think that not allowing regression seems like a limitation for no gain. So I'm :+1: to remove that.

**Comment by nykopol** [comment]
@iltar if we think about a progress bar where the total number of task to treat is not predetermined. For example at the start of de command the total number of item to import is 50 but during the importation, the number increase of 200. The progress meaning is respected, but the requested functionality remain the  same when the total number of tasks increase because the printed bar is a percentage.

**Comment by jameshalsall** [comment]
PR for this: https://github.com/symfony/symfony/pull/19824
