### ISSUE TITLE
translator service use a different class between prod & dev environments

### ISSUE THREAD

**Issue by loicfavory** [symfony/symfony#15224]
I'm using this example to create a LocaleListener to persist the locale during all the session : http://symfony.com/fr/doc/current/cookbook/session/locale_sticky_session.html

First, since Symfony 2.7 this example is not working anymore with ajax requests.
The locale is set in french in the request object in my Controller, but the locale of the translator service stay in english.

So I change the LocaleListener, passing the Translator service as a parameter of my LocaleListener, using @translator in my service.yml file.

When my app is in dev environment, the @translator is a Symfony\Component\Translation\DataCollectorTranslator but when I'm in prod environment it's a Symfony\Bundle\FrameworkBundle\Translation\Translator...

In dev mode I can pass a @translator.data_collector service as parameter of my LocaleListener, but in prod it's unknown.

I upgraded my app from older version, could it be the cause of the problem ?

**Comment by xabbuh** [comment]
In the dev environment, Symfony the `translator` service is decorated by a different implementation that is able to collect information about translations being used in order to add the translation section to the debug toolbar.

@loicfavory So this is totally expected. Did you experience any issue with this behaviour?

**Comment by loicfavory** [comment]
@xabbuh I thank you for this answer. I had an issue because I was using the DataCollectorTranslator type in the constructor method of my LocaleListener. So it was working in dev but not in prod. I changed it using the TranslatorInterface type, it's working now on both environment, but I'm glad to understand why it was different.

So no issue in fact.

**Comment by xabbuh** [comment]
@loicfavory Indeed, it's always a good idea to rely on an interface as long as you don't need a concrete implementation.
