### ISSUE TITLE
On unmatched route the app.user is null

### ISSUE THREAD

**Issue by clubdesarrolladores** [symfony/symfony#15221]
Hi, when i throw a HttpNotFoundException within a controller, a 404 error page is rendered. That is ok, i can show to the user a message like: "Hi USERNAME, are you lost?"
But if the exception is thrown by the kernel when it can't resolve a controller (route not found), the 404 error page is rendered but without the user in the twig's app.user variable. "Hi NULL, are you lost?"
It is ok this behavior?
PD: If after that 404 page, i go to another existing page, i have the same session i have before. It doesn't lose the credentials.

**Comment by jvasseur** [comment]
This appends because the routing is done before the security listener reloads the user from the session, so you don't have access to the user in the 404 page.

I'm not sure if there is a reason they are done in this order or if you can switch the priority of the listeners.

**Comment by Tobion** [comment]
This is a known limitation: http://symfony.com/doc/current/cookbook/controller/error_pages.html#avoiding-exceptions-when-using-security-functions-in-error-templates and #10159
