### ISSUE TITLE
[Security] Using 0 as username

### ISSUE THREAD

**Issue by Creaternal** [symfony/symfony#15237]
UserAuthenticationProvider not allow username "0"

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php#L65

**Comment by paragonie-scott** [comment]
It looks like if `getUsername()` fails, it is going to return `null`. Could this solve the problem?

```diff
-        if (empty($username)) {
+       if ($username !== null)) {
```

**Comment by boekkooi** [comment]
So the check should become `if (empty($username) && $username !== '0')`

**Comment by ro0NL** [comment]
Just my2cents.. the TokenInterface documents a string return value (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L67)

empty() should be avoived, imho.. as it makes things messy/unclear. Based on the documentation we should be able to just use `$token->getUsername()`, however if the username is optional we should expect a  NULL value.. `@return string|null` (a non empty string or null that is).

If concrete token classes adhere to this implementations can become much cleaner (`$username === null`).

**Comment by WouterJ** [comment]
:+1: for changing `empty(...)` to `null === ...` (which is also more common in the Symfony code-base).

**Comment by xabbuh** [comment]
see #15326
