### ISSUE TITLE
[DoctrineBridge]Implement container aware EntityListenerResolver

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#15232]
The doctrine documentation shows an example of entity listener resolver : 

```php
<?php
class MyEntityListenerResolver extends \Doctrine\ORM\Mapping\DefaultEntityListenerResolver
{
    public function __construct($container)
    {
        $this->container = $container;
    }

    public function resolve($className)
    {
        // resolve the service id by the given class name;
        $id = 'user_listener';

        return $this->container->get($id);
    }
}
```

This looks a lot like something that could be done in the doctrine bridge, allowing people to use services id instead of classnames when configuring their entity listeners, making the injection of services like, for instance, a mailer, very easy.

At the moment, if I need to use some services in an event, I use an event listener, which is called for every entity, and I first check the classname of the entity to make sure that the event actually applies to it (most of the times, an event only applies to one entity, doesn't it ?).

**Comment by xabbuh** [comment]
It looks to me that you are looking for the [entity listener support of the DoctrineBundle](http://symfony.com/doc/master/bundles/DoctrineBundle/entity-listeners.html).

Feel free to reopen if I misunderstood your issue. :)

**Comment by greg0ire** [comment]
Oh, indeed, it seems to solve my problem! Thanks a lot!

**Comment by greg0ire** [comment]
@xabbuh : turns out it does not work at all. Can you reopen this issue ? The problem is that my listener has a dependency, and that the default entity resolver builds my listener without its dependencies, like this : 

```
    /**
     * {@inheritdoc}
     */
    public function resolve($className)
    {
        if (isset($this->instances[$className = trim($className, '\\')])) {
           return $this->instances[$className];
        }

        return $this->instances[$className] = new $className();
    }
```

**Comment by xabbuh** [comment]
@greg0ire I don't understand your issue. [Here](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Compiler/EntityListenerPass.php#L55) the service you configured is registered as an entity listener. So `resolve()` should not create a new instance of your listener class. But anyway if there is an issue with the existing compiler pass, you are better off with reporting it on the DoctrineBundle repository so that it can be fixed there.

**Comment by greg0ire** [comment]
I guess I misused it somehow, probably because I tried registering the entityListener in the entity mapping with a classname. Maybe I should try again with a service id instead.

**Comment by greg0ire** [comment]
Ok, turns out my version of doctrine-bundle is too old, I don't even have this compiler pass. This explains that, sorry for the noise.
