### ISSUE TITLE
PDOSessionHandler fails in Prod Env in 2.7

### ISSUE THREAD

**Issue by alexgurrola** [symfony/symfony#15242]
I have followed instructions according to the article, [How to Use PdoSessionHandler to Store Sessions in the Database](http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html) to implement Sessions into a MySQL Database in Symfony 2.6.  This worked perfectly ~~in Symfony 2.6~~, but ~~after updating to Symfony 2.7~~, upon the expiration of a session, a user is unable to log in to the Production environment anymore.  Furthermore, cookies aren't created for users at this point.

I've checked all logs, reviewed Upgrade Documentation and the source code for the PDOSessionHandler and still cannot see what the issue is ~~that would have broken compatibility in Symfony 2.7~~.  Any further information in regards to this issue would be greatly appreciated.

**Comment by xabbuh** [comment]
Does that mean that anything works for you if switch to, for example, the native session handler when using Symfony 2.7?

**Comment by alexgurrola** [comment]
Correct.  I have not been able to recreate the bug in Native, so far, but I will be running the servers on Native for a few days to see if it shows up for anyone.

**Comment by alexgurrola** [comment]
So far, adding the line below in the ```config.yml``` file seems to have solved the issue.

```yml
framework:
    session:
        cookie_path: "/"
```

I noticed that the sessions were being created in our Database in the production environment by the PDO Handler, but for some reason the **cookie** wasn't being set, which I theorize has something to do with the variable not being present in the YAML file creating an odd call to the ```setcookie()``` function.

**Comment by alexgurrola** [comment]
After a few days of not clearing the cache, the issue returns, and only clearing the cache seems to allow further logins.  I'm very baffled by this issue.

**Comment by Tobion** [comment]
You got to debug that and tell us your findings. Otherwise there is zero things we can do for you. So unless you create a concrete bug report, there is no point is keeping this issue open.

Also, none of the session classes changed between 2.6 and 2.7 at all. So it cannot be caused by the upgrade as you say.

**Comment by jakzal** [comment]
ping @alexgurrola

**Comment by alexgurrola** [comment]
I can't seem to find where the bug lies and I haven't been able to find anything promising, yet, but I do have a quick workaround.  It's not a great one, so bear with me.

```sh
#!/bin/bash

sudo rm -rf 2.0/app/cache/*
mysql -h localhost -u root -p'password' global -e "truncate table global.user_sessions"
```

Basically, actually removing the cache completely and truncating all User Sessions allows people to log back in for a short while.  My presumption is that there is something not happening in terms of expiring sessions, cache files, etc, and I am still having trouble grasping exactly what it is that's causing the issue.  The next time it shows up, I will be gathering everyone's Session ID's to see if there's a trend with their session in the table and their inability to log in.

**Comment by alexgurrola** [comment]
### Deep Debugging after User reported locked Session

I managed to go through this issue, in a slow step by step process while collecting data, and I believe I have narrowed it down to only a few options, as explained below.

--------------

I don't need to truncate the `user_sessions` table, even though truncating the session table and clearing the cache does work, which leads me to believe there is a problem with the session itself.

The current session cookie that won't let them log in has BLOB data which is as follows:

```php
_sf2_attributes|a:2:{s:7:"history";a:3:{i:0;s:15:"/Member/Sign-In";i:1;s:5:"/Dash";i:2;s:1:"/";}s:26:"_security.main.target_path";s:32:"https://admin.sitetheory.io/Dash";}_sf2_flashes|a:0:{}_sf2_meta|a:3:{s:1:"u";i:1443463942;s:1:"c";i:1443463941;s:1:"l";s:8:"31536000";}
```

After clearing the website cache, then their local cookies and cache, they are finally able to log in.  Afterwards, the BLOB data looks like this:

```php
_sf2_attributes|a:2:{s:7:"history";a:2:{i:0;s:15:"/Member/Sign-In";i:1;s:6:"/Sites";}s:26:"_security.main.target_path";s:33:"https://admin.sitetheory.io/Sites";}_sf2_flashes|a:0:{}_sf2_meta|a:3:{s:1:"u";i:1443464979;s:1:"c";i:1443464979;s:1:"l";s:8:"31536000";}
```

Nothing seems to stand out to me here, so this leads me to believe there is a problem with one or more of the following procedures:

- [x] Garbage Collection
 - The Sessions Table doesn't seem to have any less rows as time progresses.
- [ ] Cookie / Session Expiration
 - The Cookies and/or Sessions aren't expiring properly since they both exist at the time of login but are locked to adding a User to the Session.
- [ ] Production Cache
 - The Development environment doesn't seem to have this issue.
- [ ] Session Configuration
 - User error can never be entirely ruled out

Each session entry in the database has a `sess_lifetime = 604800`, and my config.yml is as follows:

```yml
framework:
    session:
        #storage_id:          session.storage.native
        handler_id:           sitetheory_global.session
        name:                 "SITETHEORY"
        cookie_lifetime:      31536000
        cookie_path:          "/"
        cookie_domain:        "%cms.cookieDomain%"
        cookie_secure:        false
        cookie_httponly:      false
        gc_divisor:           100
        gc_probability:       1
        gc_maxlifetime:       604800
        save_path:            "%kernel.cache_dir%/sessions"
```

Furthermore, the variable `%cms.cookieDomain%` is set dynamically from the following snippet, which is loaded as a resource:

```php
$host = (!empty($_SERVER['HTTP_HOST'])) ? $_SERVER['HTTP_HOST'] : NULL;
$container->setParameter('cms.cookieDomain', (strpos($host, $container->getParameter('cms.domain.preview')) !== false) ? '.'.$container->getParameter('cms.domain.preview') : $host);
```

To ensure that any logins under *admin.sitetheory.io* carry over to domains that fall under the main preview domain of *.sitetheory.io*, the resource ensures the cookie is set to *.sitetheory.io*.

--------------

Hopefully this data gets our answer a bit closer to finding where this bug lies.  Your assistance is very much appreciated.

Thanks again,
Alex Gurrola

**Comment by alexgurrola** [comment]
@jakzal @Tobion Do you have any suggestions for further information I should gather or any particular direction I should dig into other than the four checkboxes above I am currently looking into?

**Comment by jakzal** [comment]
Do you realise that the following code is only executed first time the cache is generated?

```php
$host = (!empty($_SERVER['HTTP_HOST'])) ? $_SERVER['HTTP_HOST'] : NULL;
$container->setParameter('cms.cookieDomain', (strpos($host, $container->getParameter('cms.domain.preview')) !== false) ? '.'.$container->getParameter('cms.domain.preview') : $host);
```

**Comment by alexgurrola** [comment]
I did not know that Resources were cached, but removing that resource fixed the issue.  Thanks much.
