### ISSUE TITLE
Error in FrameworkBundle

### ISSUE THREAD

**Issue by mayeco** [symfony/symfony#15254]
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L830

Thank you, please fix

**Comment by mayeco** [comment]
@fabpot ping

**Comment by dosten** [comment]
The fix has been applied to the 2.7 branch, so i guess that we should wait until someone merge the 2.7 into the 2.8 and master branches.

**Comment by mayeco** [comment]
I just realised, thank you @dosten... closing this.
