### ISSUE TITLE
[2.7] A redirect response dead loop in dev environment

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#15255]
I create a kernel.request event listener like this:

    if ($this->requestStack()->getCurrentRequest()->attributes->get('_route') != '...') {
        $response = $this->httpUtils->createRedirectResponse( ... );
        $event->setResponse($response);
    }

There is a dead loop instead of error debugging page when an error occurs.

**Comment by jakzal** [comment]
Could you please fork symfony/symfony-standard and reproduce your issue on a new branch?

**Comment by zacharyzh** [comment]
Ok.

I am busy on my job now, and I will do it a few days later.

**Comment by fabpot** [comment]
Closing as there is no feedback. Feel free to reopen with more details.
