### ISSUE TITLE
[Console] No Nice Way to Add Custom Helpers to the Console Application

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#15258]
It doesn't seem like there is a nice way to add custom console helpers to the [Framework Bundle Application](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Console/Application.php).

Would it be possible to allow helpers to be added with a container tag -- `console.helper` or something like that? Would probably be very close to the way commands are tagged and checked in a [compiler pass](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddConsoleCommandPass.php) and added in the [application](https://github.com/symfony/symfony/blob/aefd16d4f3e33ce5e83ca061c74d73e0d1b6ba2c/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L109-L113).

**Comment by chrisguitarguy** [comment]
Assuming this gets a :+1: from someone on the Symfony team, I can build it.

**Comment by futjikato** [comment]
Is this issue solved in the meantime? Just stumbled across this missing feature.

**Comment by chrisguitarguy** [comment]
In your app bundle class, override `registerCommands` and add the helpers there. You could probably do a similar thing just in `app/console` if there's no `AppBundle`.

```php
use Symfony\Bundle\FrameworkBundle\Console\Application as FrameworkApplication;
use Symfony\Component\HttpKernel\Bundle\Bundle;

final class AppBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function registerCommands(Application $app)
    {
        if ($app instanceof FrameworkApplication) {
            $this->addHelpers($app);
        }

        return parent::registerCommands($app);
    }

    private function addHelpers(FrameworkApplication $app)
    {
        $container  = $app->getKernel()->getContainer()
        $app->getHelperSet()->set($container->get('your_helper'));
    }
}
```

**Comment by futjikato** [comment]
That is a possibility.
I created an abstract command and added them in there but your original request for a configuration option for console helpers is still valid in my opinion.

**Comment by TomasVotruba** [comment]
Maybe PR would be easier to discuss over?
