### ISSUE TITLE
Validation groups on submits and on the form type

### ISSUE THREAD

**Issue by pieter2627** [symfony/symfony#15265]
I am not sure if this is a issue with me trying to do something that is not possible or a bug, but I have the following case.

A multi-stage form that embeds other forms. Some of the embeded forms has dynamic validation groups set via the 'validation_groups' callback in their type. But trying to set the 'validation-groups' option on a submit (for the multi-stage to work) to the name of these embeded forms (second type of validation group from the book) does not trigger their callbacks.

This means that the dynamic groups for these embedded forms are not set correctly.

So am I trying to do something impossible or is this a bug?

*The [same question](http://stackoverflow.com/q/31204744/2727983) on SO with some code example if the above is not clear.*

**Comment by origaminal** [comment]
It seems like not a bug but an expected behavior: submitted button validation groups have precedence over type constraints and `Form::getClickedButton` returns a clicked button from a current form or parents. 

The case could be handled by submitting callable to `SubmitType`'s `validation_groups`.

**Comment by pieter2627** [comment]
@origaminal I ended up using the `getClickedButton` in the callable to exit it early before setting any groups.

Maybe there should be a way to have a `form_defaults_groups` - where only the defaults of certain forms' classes are used based on the submit clicked?

**Comment by pieter2627** [comment]
I think this issue can be closed.

What @orgaminal suggested of using a callable on the submit's `validation_groups` rather than an array works perfectly.

One thing, I can't remember seeing any documentation that a submit type's `validation_groups` property can take a callable. Is this somewhere, and if not can I add it as a cookbook entry and how?

**Comment by jakzal** [comment]
@pieter2627 validation group callables are documented here: http://symfony.com/doc/current/book/forms.html#groups-based-on-the-submitted-data

**Comment by pieter2627** [comment]
@jakzal thanks for the url, i'll also look at repo
