### ISSUE TITLE
Entity with name 'sort'

### ISSUE THREAD

**Issue by korvinko** [symfony/symfony#15274]
If I named field of entity 'order' I will get error:

Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO menu_items (title, link, order, menu_type) VALUES (?, ?, ?, ?)' with params ["test", "http:\/\/example.com", 1, "top_menu"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order, menu_type) VALUES ('test', 'http://texample.com', 1, 'top_menu')' at line 1" at D:\web\project\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'INSERT INTO menu_items (title, link, order, menu_type) VALUES (?, ?, ?, ?)' with params [\"test\", \"http:\\/\\/example.com\", 1, \"top_menu\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order, menu_type) VALUES ('test', 'http://example.com', 1, 'top_menu')' at line 1 

My entity:

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="menu_items")
 */
class MenuItem
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="text", name="title")
     **/
    protected $title;

    /**
     * @ORM\Column(type="text", name="link")
     **/
    protected $link;

    /**
     * @ORM\Column(type="integer", name="order", nullable=true)
     **/
    protected $order;

    /**
     * @ORM\Column(type="text", name="menu_type")
     **/
    protected $menuType;
```

**Comment by Waigie** [comment]
order is a reserved keyword in sql, so using it as unescaped column name would not work. You can change your column definition and escape it though.

```php
class MenuItem
{
    /**
     * @ORM\Column(type="integer", name="`order`", nullable=true)
     **/
    protected $order;

```

To escape the column name surround it with `` as seen above

**Comment by phansys** [comment]
@korvinko, this "issue" isn't related to Symfony, please close it and do your questions in the appropiate place ([Doctrine issue tracker](http://www.doctrine-project.org/jira/browse/DDC) by instance).
Thanks in advance.
