### ISSUE TITLE
Symfony\Component\Process\Process Bug in Windows Server

### ISSUE THREAD

**Issue by sn0opr** [symfony/symfony#15278]
I'm using the wkhtmltopdf.exe command line program to generate PDF from HTML
I'm using it through *Knp/Snappy* package which is using ```Symfony\Component\Process\Process``` to run the program in the cmd.
It works fine in my computer (Win 8.1 64bit and Win 7 32bit) but not in the deployment machine (Windows Server 2012 R2, 12GB, Intel Xeon 2.4 Ghz)

here is the code using Process class:
```
$binary = \Config::get('snappy.pdf.binary');
    $process = new Symfony\Component\Process\Process($binary.' http://localhost/gca/public/demandes-achat/1138/pdf processs.pdf');
    $process->run(function ($type, $buffer) {
        if (\Symfony\Component\Process\Process::ERR === $type) {
            echo 'ERR > '.$buffer;
        } else {
            echo 'OUT > '.$buffer;
        }
    });
```
I get a 60 seconds timeout error: 
```
Symfony\Component\Process\Exception\ProcessTimedOutExceptionGET /gca/public/test
The process "C:\xampp\htdocs\gca/wkhtmltopdf/bin/wkhtmltopdf.exe http://localhost/gca/public/demandes-achat/1138/pdf process.pdf" exceeded the timeout of 60 seconds
```
Knowing that wkhtmltopdf is working as expected using the windows cmd, I tried to use the the native PHP function ```exec()``` and it worked fine !
From this, I noticed that there is a problem with the Process class.

I opened an issue in the *Knp/Snappy* reposetory, it may help: https://github.com/KnpLabs/snappy/issues/169

Thank you

**Comment by sn0opr** [comment]
up

**Comment by jaytaph** [comment]
The actual command that will be executed by the process component might differ from what you expect. The reason for this has to do with some of the workarounds that is needed to capture output on file descriptors on windows systems.

You can display the ACTUAL executed command by added a simple `print` statement here: https://github.com/symfony/symfony/blob/5f36605e0e2264a1f52a8caa4bbe35a6f4ece8b4/src/Symfony/Component/Process/Process.php#L289

If you can give this information, it might shed a light on what might occur.

**Comment by sn0opr** [comment]
@jaytaph Sorry for the late,
here is the ```$commandeline``` print output:
```
cmd /V:ON /E:ON /C "(C:\xampp\htdocs\gca/wkhtmltopdf/bin/wkhtmltopdf.exe http://localhost/gca/public/demandes-achat/1024/pdf test.pdf) 1>"C:\Windows\Temp\sf_EC50.tmp" 2>"C:\Windows\Temp\sf_EC51.tmp""
```

**Comment by jaytaph** [comment]
@sn0opr No worries.You notice a different commandline here (including the redirections to some temp files). What happens when you run this EXACT command directly (so everything, including the "cmd").

**Comment by sn0opr** [comment]
@jaytaph I did the same exact command and I no output, just I wait about 1s and nothing happens
```
C:\Users\adminsimop>cmd /V:ON /E:ON /C "(C:\xampp\htdocs\gca/wkhtmltopdf/bin/wkhtmltopdf.exe http://localhost/gca/public/demandes-achat/1024/pdf test.pdf) 1>"C:\Windows\Temp\sf_EC50.tmp" 2>"C:\Windows\Temp\sf_EC51.tmp""
```

**Comment by jaytaph** [comment]
There should be output some in the temp files (`c:\windows\temp\sf_EC50.tmp` and `c:\windows\temp\sf_EC51.tmp`).

**Comment by osaris** [comment]
Same problem here on Windows 2008 R2 with Snappy, I'll try to dig into this problem.

**Comment by WouterSioen** [comment]
I have the exact same issue in a linux environment.

when I run the command on the CLI (in the exact same vagrant box), it runs in under a second:

```
vagrant@server:~$ time /vagrant/site/app/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --cookie 'PHPSESSID' 't5ekcbtu71fkks8ted0ikds3sv5pcmmp' 'http://site.dev/ticket/qQUD7Hx72qzs/3' '/vagrant/pos/src/Citymesh/AccessCode/../../../web/tickets/qQUD7Hx72qzs.pdf'
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

real    0m0.470s
user    0m0.024s
sys     0m0.024s
```

The Process component never gets out of the run method though. When I debug this using `dump` statements, it looks like `proc_get_status` keeps returning `true` for running key, even a long time after this process should have been ended.

Could this be an issue with proc_get_status? I can't find a php issue for this.

**Comment by WouterSioen** [comment]
Hmm, when I dump the Process after the timeout occurs, it looks like this:

```
Process {#321 ▼
  -callback: Closure {#322 ▶}
  -commandline: "time /vagrant/site/app/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '0' --margin-left '0' --margin-right '0' --margin-top '5mm' --page-height '80mm' --page-width '72mm' --cookie 'PHPSESSID' 't5ekcbtu71fkks8ted0ikds3sv5pcmmp' 'http://site.dev/ticket/jxdby86Bsrgm/3' '/vagrant/pos/src/Site/AccessCode/../../../web/tickets/jxdby86Bsrgm.pdf'"
  -cwd: "/vagrant/pos/web"
  -env: null
  -input: null
  -starttime: 1447405622.8217
  -lastOutputTime: 1447405622.8483
  -timeout: 10.0
  -idleTimeout: null
  -options: array:2 [▶]
  -exitcode: 143
  -fallbackExitcode: null
  -processInformation: array:8 [▶]
  -outputDisabled: false
  -stdout: null
  -stderr: """
    Loading pages (1/6)\n
    [>                                                           ] 0%\r[======>                                                     ] 10%\r
    """
  -enhanceWindowsCompatibility: true
  -enhanceSigchildCompatibility: false
  -process: Unknown resource @241
  -status: "terminated"
  -incrementalOutputOffset: 0
  -incrementalErrorOutputOffset: 0
  -tty: null
  -pty: false
  -useFileHandles: false
  -processPipes: UnixPipes {#324 ▶}
  -latestSignal: 15
}
```

So it looks like the output from wkhtmltopdf gets added to stderr instead of stdout. When I use the `--quiet` option, stderr stays empty and I still have the same issue though.

**Comment by ewgRa** [comment]
Can you write a Command or test that reproduce your problem? Without relations to vargant, snappy and so on, that just for example try to convert google homepage to pdf. It would be very helpful.

**Comment by WouterSioen** [comment]
Hmm, I've tested this further, and it seems only to fail if I add the `--cookie 'PHPSESSID' '<session-id>'` parameter to wkhtmltopdf. It thus seems that it's a snappy or even wkhtmltopdf issue. (I still don't know why this option makes the process component fail though)

**Comment by sn0opr** [comment]
@WouterSioen You are propably passing the URL of the page to wkhtmltopdf, why don't you pass the plain html text in your php code

**Comment by nicolas-grekas** [comment]
Can you make it work by using proc_open directly instead of exec?

**Comment by akovalyov** [comment]
@nicolas-grekas not sure if I understood your question. ['Symfony/Process'](https://github.com/symfony/process/blob/master/Process.php#L291) uses proc_open [only](https://github.com/symfony/process/blob/master/Process.php#L144).

**Comment by jakzal** [comment]
@akovalyov you said you've tried to use the the `exec()` function and it worked fine. Have you tried using `proc_open` directly? We're trying to see if this is a problem in the Process component, or perhaps an environment you use it on.

**Comment by akovalyov** [comment]
@jakzal it wasn't me, it was @sn0opr who tried it.
I apologize that I have made a senseless comment for @nicolas-grekas above - mixed up this issue with https://github.com/KnpLabs/snappy/issues/169.

As for my two cents, I think that the root of the issue is `wkhtmltopdf` here, which under certain conditions does not handle correctly the end of its lifecycle.

I am almost sure that http://php.net/manual/ru/function.proc-get-status.php returns `running` for `wkhtmltopdf` process however it has already returned code `143`, but I don't have any proofs for that. 
It would be interesting to check `processInformation` of that Process with timeout to verify this hypothesis. Maybe @WouterSioen could give a dump for that?

Maybe we should check [there](https://github.com/symfony/process/blob/master/Process.php#L1283) the exit code in `processInformation` as well?

BTW, indirect confirmation of this hypothesis is that fact that users started to complain about this issue when we dropped support for the embedded Process class and started to require `Symfony/Process`. [That class](https://github.com/KnpLabs/snappy/blob/f29edc4e53429deec2b394926a8f743a0ad2e28e/src/Knp/Snappy/Process.php#L52) was a simple `proc_open` wrapper.

**Comment by ewgRa** [comment]
@akovalyov @sn0opr Can you write a Symfony Command or test that reproduce your problem?

**Comment by ewgRa** [comment]
@WouterSioen Can you write a Symfony Command or test that reproduce your problem?

**Comment by WouterSioen** [comment]
I'll try to do this soonish.

**Comment by romainneutron** [comment]
Just set the timeout you want to use in the Process constructor:

For example for 42s timeout: `$process = new Symfony\Component\Process\Process($binary.' http://localhost/gca/public/demandes-achat/1138/pdf processs.pdf', null, null, null, 42);` or after object creation:
```
$process = new Process(...);
$process->setTimeout(42);
```

Use a timeout of `0` to disable timeout, see doc http://symfony.com/doc/current/components/process.html#process-timeout
