### ISSUE TITLE
feature switch user fail exit on 2.6.10 not on 2.6.9

### ISSUE THREAD

**Issue by zimzim62000** [symfony/symfony#15287]
Hello,

I use this nice feature.

Today, i update composer and i get symfony 2.6.10.

i use the default setting same the exemple on this page : 
(http://symfony.com/doc/current/cookbook/security/impersonating_user.html)

The feature work when i switch to a another user but when i try to switch out ( EXIT ), i'am automatically redirect on my login page and always logued with the another user.
I decrease symfony to 2.6.9 and the problem has disappeared.

So i can't upgrade my symfony version for now.

Thanks for your time 

ps : i know... i need update to symfony 2.7.x ! ;)

**Comment by xabbuh** [comment]
Could you share some related logs or could you provide a reproducible fork of the Symfony Standard Edition? Could also, by any change, check if reverting the change made in 01ee3f6cdae036caa839375f8854b41118e68ffd fixes your issue?

**Comment by jakzal** [comment]
@zimzim62000 we're not doing any bug fixes for 2.6 anymore. Can you reproduce this issue on 2.7?

**Comment by zimzim62000** [comment]
Hello,

Today, i had time to create new project to test only this feature with 2.6.9 - 2.6.10 - 2.6.11 - 2.7.2

I can't reproduce the same bug. so I think it comes from my project.

I think next month , i'll tried to upgrade  my project to 2.7.x .
We will see.
If the bug will reappear, i reopen my issue and post some logs.

Sorry for the inconvenience && Symfony for life

**Comment by jakzal** [comment]
@zimzim62000 Thanks for your efforts to reproduce it. Much appreciated.
