### ISSUE TITLE
Update 2.7.2 broke ChoiceQuestion

### ISSUE THREAD

**Issue by LorisZ** [symfony/symfony#15283]
I wrote a Command that uses ChoiceQuestion like shown in the docs [here](http://symfony.com/doc/current/components/console/helpers/questionhelper.html). It worked just fine before i updated to 2.7.2 and works again after a downgrade.

The Error: "Notice: Undefined index: <index>" where <index> is always the selection i made. 

Code where it happens:
```php
$dbTypes = array('integer', 'string', 'text', 'boolean', 'double', 'float', 'date', 'datetime');
$q = new ChoiceQuestion('Type(string): ', $dbTypes, 1);
            $type = $qh->ask($input, $output, $q);
```

Just from looking at the changelog, I'm suspecting  #15223 having to do something with it, can't say for sure though.

**Comment by cordoval** [comment]
this has been resolved and it is a duplicate @LorisZ please close

**Comment by cordoval** [comment]
related #15271

**Comment by LorisZ** [comment]
oh, sorry. Apparently i only searched the open issues.
