### ISSUE TITLE
Cookie date issue

### ISSUE THREAD

**Issue by negreanucalin** [symfony/symfony#15289]
This might be a php version issue but couldn't find any issues.
When building the Cookie object and dates are way in the future like 2085 (Imdb site has this big value).
DateTime object is created successfully 
```$date->getTimestamp(); //returns false```
I managed to 'fix' this as follows in Cookie.php:
```
private static function parseDate($dateValue){
    // trim single quotes around date if present
    if (($length = strlen($dateValue)) > 1 && "'" === $dateValue[0] && "'" === $dateValue[$length - 1]) {
            $dateValue = substr($dateValue, 1, -1);
    }
    //my edit - capture the year and force it to be smaller, the limit is imposed by the 4 byte signed integers
    preg_match('/([0-9]{4,5})/',$dateValue ,$result);
    if(isset($result[0])) {
        if($result[0] > 2038) {
            $dateValue = str_replace($result[0], 2038, $dateValue);
        }
    }
...
```
}
Any thoughts?

**Comment by iltar** [comment]
Are you running on a 32bit machine/compilation?

https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by xabbuh** [comment]
ping @negreanucalin

**Comment by negreanucalin** [comment]
Sorry for the huge delay, yes I have a 32bit compilation...
Thank you for the reply.

**Comment by xabbuh** [comment]
I am not convinced we should/can do anything about this on the Symfony side. I'd say you'd better switch to a 64 bit environment.

**Comment by negreanucalin** [comment]
Indeed
