### ISSUE TITLE
[HttpFoundation]

### ISSUE THREAD

**Issue by jleck** [symfony/symfony#15284]
Hi,

A recent change to Response.php in HttpFoundation has stopped compatibility with HHVM 3.3:

https://github.com/symfony/HttpFoundation/commit/82b63202be55551ad882fe1a6fbc681b6da345b3

```
$flags = PHP_VERSION_ID >= 50400 ? PHP_OUTPUT_HANDLER_REMOVABLE | ($flush ? PHP_OUTPUT_HANDLER_FLUSHABLE : PHP_OUTPUT_HANDLER_CLEANABLE) : -1;
```

The variable PHP_OUTPUT_HANDLER_REMOVABLE is not defined. I changed the line to `$flags = -1` and all is working again. I assume the version check just needs editing to exclude HHVM 3.3.

**Comment by fabpot** [comment]
Can you submit a pull request for that change?

**Comment by nicolas-grekas** [comment]
See #15291
