### ISSUE TITLE
ChoiceFormField: multiple select without [] does not work

### ISSUE THREAD

**Issue by nickygerritsen** [symfony/symfony#15281]
I want to submit a form that has the following select field:

```html
<select name="test" multiple="multiple">
  <option value="123">First value</option>
  <option value="456">Second value</option>
</select>
```

I.e. the field is named `test` and not `test[]`

If I want to submit such a form using BrowserKit, it will be submitted as (assuming I selected both options):
```
test[]=123&test[]=456
```

But that does not work. It should be submitted as:
```
test=123&test=456
```

Is it possible to fix this somehow?

**Comment by stof** [comment]
``test=123&test=456`` means that PHP will see only 1 value though, because it will reuse the same key. So we would have to submit only ``456`` actually in this case.
This might be a bit hard to implement in the current system though

**Comment by javiereguiluz** [comment]
Closing it because, as @stof said, this edge case would be very difficult to implement in the current component.

If this is only needed for tests, you could even do a simple `str_replace('[]=', '=')` on the query string to normalize its value before processing it or checking its value.
