### ISSUE TITLE
[Forms] Set choice_translation_domain to false for DateType?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#15298]
I use `BirthdayType` (for which parent `DateType` so the problem is the same).

```
->add('birthday', 'birthday', [
	'label' => 'my_custom.translation_message',
	'required' => true,
	'format' => 'dd MMMM yyyy',
//	'translation_domain' => false,
//	'choice_translation_domain' => false,
])
```

On Symfony 2.7.3 I get gazillion (more than 100) `missing message` warnings.

If I uncomment `choice_translation_domain` – the option is not recognized.

If I uncomment `translation_domain` – the warnings disappear, but my label does not get translated.

I believe, `DateType` and `BirthdayType` should have `choice_translation_domain` so that label does get translated while there would not be warnings for each year in the widget (`ChoiceType`).

**Comment by aitboudad** [comment]
the same as #15222, I'll fix that.
