### ISSUE TITLE
[voter] Unable to check if the user has an inherited role in a custom voter ?

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#15299]
In this example I tried to make a custom voter giving access when the user has role 'ROLE_ADMIN' or the inherited 'ROLE_AUTHOR' and is the owner of the entity.

Accessing user roles thrue UserInterface $user->getRoles(), I can't do if(in_array('ROLE_AUTHOR',$roles), because ROLE_AUTHOR is inherited.

It is also not possible to inject the security context, because custom voters are injected in.

Could you add a mechanism to resolve something like this ?
Or it exists already a solution ?

```
<?php
namespace AppBundle\Security;

use Symfony\Component\Security\Core\Authorization\Voter\AbstractVoter;
use Symfony\Component\Security\Core\User\UserInterface;

class MyVoter extends AbstractVoter
{
	const ADD = 'element_add';

    protected function getSupportedAttributes()
    {
        return array(self::ADD);
    }

    protected function getSupportedClasses()
    {
        return array('AppBundle\Entity\Elements');
    }

    protected function isGranted($attribute,$element,$user=null)
    {
        if (!$user instanceof UserInterface){
            return false;
        }

		$roles = $user->getRoles();
		switch($attribute){
            case self::ADD:
				if(in_array('ROLE_ADMIN',$roles)){return true;}
				if(in_array('ROLE_AUTHOR',$roles) && $user === $element->getUser()){return true;}

                break;
		}
		
        return false;
    }
}
```

**Comment by weaverryan** [comment]
This is related to #12360, and part of it is already fixed for 2.8 (in 2.8, you should be able to inject the `security.authentication.manager` service into your voter (which is really what you should use to check whether something "isGranted" from inside a voter - though for practical terms, using the security context / newer authorization checker is the same).

For now, you'll need to inject the entire container, then fetch the `security.authorization_checker` service (or `security.context` on older versions) and call `isGranted()` on it when you need it. That'll avoid the circular reference problem that's fixed, but only in 2.8. #12360 shows another approach.

Closing as this is a legitimate issue, but it's already partially fixed in 2.8 and the rest is covered by #12360.

Thanks!

**Comment by Alsatian67** [comment]
OK thank you for your help.
I had already changed my app with splited security context, but here I sadly forgot to use authorization_checker.

**Comment by Alsatian67** [comment]
I think the easiest way for me at this time were to copy the full role hierarchy in a custom service.

**Comment by Alsatian67** [comment]
@weaverryan , in 2.8 with the security.authentication.manager is it possible to check if a user beeing edited (not the current user) has an inherited role ?

**Comment by weaverryan** [comment]
@Alsatian67 You could certainly just collect the full role hierarchy yourself and check - like the appraoch in #12360. 

By using the security system "normally"? In theory, yes you could do this (though I've never tried it). But you'd need to inject the `AccessDecisionManager` class (service id `security.access.decision_manager`), create some sort of a Token (e.g. UsernamePasswordToken) that contains the target user and pass that to `isGranted` on the `AccessDecisionManager`.

**Comment by Alsatian67** [comment]
There is somethin I don't understand in #12360.
By : 
```
$reachableRoles = $this->roleHierarchy->getReachableRoles(...);
```

Why can't we put directly $user->getRoles() in the parenthesis ?
Are the user roles different to the token roles ?

**Comment by weaverryan** [comment]
@Alsatian67 You'd have something like this (assuming `$otherUser` is the user you're working with):

```php
$roles = $otherUser->getRoles();
$reachableRoles = $this->roleHierarchy->getReachableRoles($roles);
```

I see that the code from #12360 was a little unclear :).

**Comment by Alsatian67** [comment]
OK perfect.
This issue is now definitively closed.
