### ISSUE TITLE
[DX][Security] Introduce a class representing a/the current firewall

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#15294]
This issue came up: https://github.com/symfony/symfony/issues/11134#issuecomment-110008899, https://github.com/symfony/symfony/issues/14435#issuecomment-110004138, https://github.com/scheb/two-factor-bundle/issues/13#issuecomment-104435069

As of Symfony 2.6 we have `Symfony\Component\Security\Http\Firewall` which is actually a listener and `Symfony\Bundle\SecurityBundle\Security\FirewallContext`. But we don't have a class / inteface representing a Firewall.

We're currently introducing a two-factor auth scheme for parts of our application which is covered by a special firewall. Therefor we need to access the current firewall and the "regular" firewall and get information from it.

There might be more use cases where one wants to retrieve informations about the current or another firewall, so a class to represent firewalls and a method to retrieve those classes would be helpful:

``` php
interface Firewall
{
  function getKey();
  function getContext();
  function getRequestMatcher():
  function getProvider();
  /**
   * This function can be used to lookup firewall configuration
   * values that are not exposed with more specific methods.
   * @return array map of the firewall configuration
   */
  function getConfig();
}
```

**Comment by caponica** [comment]
:+1:

**Comment by thomas-koch-comsolit** [comment]
@caponica please add a use case! That might be more effective than simple +1.

**Comment by JHGitty** [comment]
+1 :+1: I was going to create an issue about adding firewall information to the Profiler but then I found this issue. Hopefully this will be done.

**Comment by videni** [comment]
👍

**Comment by chalasr** [comment]
See #19398

**Comment by proArtex** [comment]
Cannot access FirewallConfig in a controller since di^4. Could you make it public?
