### ISSUE TITLE
Failed to Install Data-Fixtures with Doctrine and Symfony2

### ISSUE THREAD

**Issue by NadjibBELLOUNDJA** [symfony/symfony#15300]
I added the docrtine-fixtures and the doctrine-fixtures-bundle to my dependencies in the composer.json, as follow:

{ "require": { "php": ">=5.3.3", "symfony/finder": "2.3.*", 
"doctrine/orm": "~2.2,>=2.2.3", 
"doctrine/doctrine-bundle": "~1.2", 
"doctrine/data-fixtures": "~1.1", 
"doctrine/doctrine-fixtures-bundle": "~2.2"
}

And then I did php-cli composer.phar update, which worked and displayed the right message on my terminal:

"Loading composer repositories with package information Updating dependencies (including require-dev) - Updating doctrine/data-fixtures (dev-master bd44f6b => v1.1.1) Checking out bd44f6b6e40247b6530bc8abe802e4e4d914976a

Writing lock file

Generating autoload files"

Bu when I go to the folder vendor/doctrine, I cannot find any data-fixtures repository. What is the issue? Why does composer not load it and why does it display success messages?

(PS: My solution was to add the doctrine-fixture repository manually but it doesn't solve the composer issue).

**Comment by phansys** [comment]
@NadjibBELLOUNDJA, please ask for support in the corresponding place. Based on your description, your issue has nothing to do with Symfony, but with composer.
Please close this ticket. Thank you.

**Comment by NadjibBELLOUNDJA** [comment]
Ok. Sorry about that then.

**Comment by xabbuh** [comment]
moved to composer/composer#4270
