### ISSUE TITLE
Change the default value of framework.session.cookie_httponly

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#15303]
Actually, the default value of `framework.session.cookie_httponly` is `false`, which allows javascript to read the sessionId.

To improve security, I think, we should add a BC Break by inverting this parameter.

**Comment by adamziel** [comment]
+1

**Comment by timglabisch** [comment]
:+1:

**Comment by fabpot** [comment]
Sounds reasonable to me for 2.8 or 3.0.
