### ISSUE TITLE
[DependencyInjection] Parameter Expansion in Service Ids

### ISSUE THREAD

**Issue by digitalkaoz** [symfony/symfony#15304]
It seems Parameter Expansion is not activated everywhere:

```xml
<container>
    <parameters>
        <parameter key="the_key">bazz</parameter>
    </parameters>

   <services>
     <service id="lol.boo" class="\MyClassA" />
     <service id="lol.cat" class="\MyClassB" />
     <service id="lol.bazz" class="\MyClassC" />

     <service id="the_service" class="\MyOtherClass" >
       <parameter type="service" id="lol.%the_key%" />
     </service>
   </services>
```

this throws:

```
 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "the_service" has a dependency on a non-existent service "lol.%the_key%".
```

this example is simplified. in my application the parameter comes from the ENV vars.

**Comment by Tobion** [comment]
This can be done with aliases. No need for such a feature.

**Comment by xabbuh** [comment]
Agreed, I don't see a real benefit for this feature.

**Comment by digitalkaoz** [comment]
No it cant be done with aliases if the injected Services are autogenerated
aswell depending on some variable configuration. Take foselasticabundle for
example. Index and Type based Services are generated depending on the Index
Name which itself is configurable.

Christian Flothmann <notifications@github.com> schrieb am Fr., 17. Juli
2015 19:51:

**Comment by digitalkaoz** [comment]
And in my eyes its a Bug because Parameters gets expanded everywhere else

Robert Schoenthal <seroscho@gmail.com> schrieb am Fr., 17. Juli 2015 20:41:

**Comment by fabpot** [comment]
It was done on purpose. Making everything configurable is not always desirable. In this case, it would make it impossible to introspect the Container easily as ids would then be dynamic, which is something I don't want to happen. Aliases were created to give some flexibility here. Anyway, the uses cases are really edge and I don't us adding such a feature as it has some drawbacks.

**Comment by digitalkaoz** [comment]
yeah but it cant be solved with aliases here...so whats the proposed solution?

**Comment by digitalkaoz** [comment]
as everything dynamic...creating a compiler pass and writing 20lines of boiler plate code maybe solves it, but thats clearly not a flexible solution as it would me the extend the pass everytime i inject such a dynamic service elsewhere...

**Comment by digitalkaoz** [comment]
not service would be dynamic just references so i dont see your point

**Comment by Tobion** [comment]
Using aliases and a compiler pass is done by many bundles and it has some important advantages: validation, documentation etc.
Using parameters for magically changing services has been discouraged already some time in symfony. For this reason the class parameters of services have been removed in symfony 3.0.

Also, for exactly for your use-case, there is already a shortcut available: http://symfony.com/blog/new-in-symfony-2-7-dependency-injection-improvements#added-an-auto-alias-compiler-pass

So I'm :-1: on supporting dynamic ids.

**Comment by digitalkaoz** [comment]
@Tobion you dnt get it. its not about class parameters. its about dynamic services based on some configuration or environmental name. as this wouldnt be "dynamic service ids" per se, it only expands service ids in references. so the removal in 3.0 is not affected by this. @fabpot see the PR #15305 for the fix and its affection. i dont see why this shouldnt be merged. it doesnt have any side effects.

**Comment by digitalkaoz** [comment]
my complete use-case:

```
//.env
SYMFONY__ELASTICSEARCH_INDEX=foo
```

```yml
//app/config/config.yml
fos_elastica:
    indexes:
        %elasticsearch_index%:
            types:
                product: ~
                page: ~
```

this would expose services like

```
fos_elastica.index.foo.product
fos_elastica.listener.foo.page
```

these services needed to be injected somewhere else.

as the complete naming of the services depends on an **ENV**  variable, on **configurational** Type  Names and some string *Concatenation* inside the bundle im lost with the current implementation. The attached (in PR) 3 Lines fixes it so i can do the following:

```xml
   <services>
     <service id="the_service" class="\MyOtherClass" >
       <parameter type="service" id="fos_elastica.index.%elasticsearch_index%.product" />
     </service>
```

i tried it with the auto-alias feature, that wont work as i need to still write a compiler pass and its not a configuration-only solution.

im ok with writing a pass, but thats just a boilerplate workaround for a trivial non inversive change. and i think its not as elegant as my proposed solution...

any opinions?

**Comment by xabbuh** [comment]
I don't see why you would need a pass for that example.

Instead of

```xml
<service id="the_service" class="\MyOtherClass" >
    <parameter type="service" id="fos_elastica.index.%elasticsearch_index%.product" />
</service>
```

you could use:

```xml
<service id="fos_elastica_index_alias">
    <tag name="auto_alias" format="fos_elastica.index.%elasticsearch_index%.product" />
</service>

<service id="the_service" class="\MyOtherClass" >
    <parameter type="service" id="fos_elastica_index_alias" />
</service>
```

**Comment by digitalkaoz** [comment]
your solutions has two disadvantages:

1. i need to create a second service (with all injections) again, those injections are dynamic again. (just to tag this new service)
2. i would need to do this with permutations of service names

**Comment by jvasseur** [comment]
@digitalkaoz I don't understand why you give your index a name based on an environment variable, why not giving it a fixed name an using it everywhere ?

**Comment by digitalkaoz** [comment]
because the app is distributed for many languages and countries. so we have `foo_es`, `foo_en`, `foo_de` and so on...

**Comment by jvasseur** [comment]
But you are only using one at the same time in the app ?

**Comment by digitalkaoz** [comment]
yes...currently, dont know what might happens in the future...i guess you are thinking of using the alias feature of the foselasticabundle?

**Comment by jvasseur** [comment]
I'm thinking that what you are trying to do is setting the index name in Symfony to change the index name in elasticsearch.
You can use a different name in symfony and elasticsearch with the index_name option.

**Comment by digitalkaoz** [comment]
mh good catch...that would work as long as its only 1 index...

but the idea of my PR is still relevant :)

**Comment by jakzal** [comment]
@digitalkaoz I suspect you felt a need for dynamic IDs, because the elastic search bundle uses them for two things: a service id and an index id. It's a smell to me. This is also an edge case which hardly ever happens, and should be rather avoided. 

Since you have now a more elegant way of solving your problem (explicitly define the index name), others already explained their concerns, and we don't have a use case anymore, I think we can close this. Feel free to reopen if you can find a good use case.

**Comment by digitalkaoz** [comment]
mh ok its not an edge as even doctrine does that, but ok. if nobody every felt the need for this, im ok with it. @jakzal
