### ISSUE TITLE
[Console] Enable option to two have two or more array arguments

### ISSUE THREAD

**Issue by enzolutions** [symfony/symfony#15308]
Right now is impossible to setup a command with two Array arguments in a comment, if you try to do something like this

``` php
protected function configure()
    {
        $this
          ->setName('generate:controller')
          ->setDescription($this->trans('commands.generate.controller.description'))
          ->setHelp($this->trans('commands.generate.controller.command.help'))
          ->addOption('module', '', InputOption::VALUE_REQUIRED, $this->trans('commands.common.options.module'))
          ->addOption(
              'class-name',
              '',
              InputOption::VALUE_OPTIONAL,
              $this->trans('commands.generate.controller.options.class-name')
          )
          ->addOption(
              'controller-title',
              '',
              InputOption::VALUE_OPTIONAL,
              $this->trans('commands.generate.controller.options.controller-title')
          )
          ->addOption(
              'method-name',
              '',
              InputOption::VALUE_IS_ARRAY,
              $this->trans('commands.generate.controller.options.method-name')
          )
          ->addOption(
              'route',
              '',
              InputOption::VALUE_IS_ARRAY,
              $this->trans('commands.generate.controller.options.route')
          )
          ->addOption('services', '', InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY, $this->trans('commands.common.options.services'))
          ->addOption('test', '', InputOption::VALUE_NONE, $this->trans('commands.generate.controller.options.test'));
    }
```

You get an error like this.

```
InvalidArgumentException]
  Impossible to have an option mode VALUE_IS_ARRAY if the option does not accept a value.
```

Would be great have this option in the near future.

**Comment by paxal** [comment]
I think the mode `InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY` is forbidden. Choose either one of them.

**Comment by jakzal** [comment]
What do you expect to happen if an option is configured with `InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY`?

**Comment by augustohp** [comment]
> I think the mode InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY is forbidden. Choose either one of them.

Hmn, not from what I see form the tests. There are [many][1] [test][2] [cases][3] that use this exaclty combination.

> What do you expect to happen if an option is configured with InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY?

An option that is not required, but can be specified one or multiple times. Making below issues of the command valid:

```
$ php app/console user:disable --notify john@doe.com --notify jane@doe.com user-id
$ php app/console user:disable user-id
```

[1]: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Tests/Input/InputOptionTest.php#L119
[2]: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Tests/Input/InputOptionTest.php#L142
[3]: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Tests/Input/InputOptionTest.php#L178

> Right now is impossible to setup a command with two Array arguments in a comment, if you try to do something like this

I don't know what you mean by "arguments in a comment", but you can specify as many array options you want. The problem I see with your configuration is that you should explicitly tell the option to be either **required** or **optional**:

```php
protected function configure()
{
    $this
        ->setName('generate:controller')
        ->setDescription($this->trans('commands.generate.controller.description'))
        ->setHelp($this->trans('commands.generate.controller.command.help'))
        ->addOption('module', '', InputOption::VALUE_REQUIRED, $this->trans('commands.common.options.module'))
        ->addOption(
            'class-name',
            '',
            InputOption::VALUE_OPTIONAL,
            $this->trans('commands.generate.controller.options.class-name')
        )
        ->addOption(
            'controller-title',
            '',
            InputOption::VALUE_OPTIONAL,
            $this->trans('commands.generate.controller.options.controller-title')
        )
        ->addOption(
            'method-name',
            '',
            InputOption::REQUIRED | InputOption::VALUE_IS_ARRAY,
            $this->trans('commands.generate.controller.options.method-name')
        )
        ->addOption(
            'route',
            '',
            InputOption::REQUIRED | InputOption::VALUE_IS_ARRAY,
            $this->trans('commands.generate.controller.options.route')
        )
        ->addOption(
            'services', 
            '', 
            InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY, 
            $this->trans('commands.common.options.services')
        )
        ->addOption(
            'test', 
            '', 
            InputOption::VALUE_NONE, 
            $this->trans('commands.generate.controller.options.test')
        );
}
```

Let us know if that helps.

**Comment by stof** [comment]
> An option that is not required, but can be specified one or multiple times. Making below issues of the command valid

an option is **never** required. What can be required is *passing a value* for the option (i.e. ``--notify`` vs ``--notify foo@example.org``)

**Comment by stof** [comment]
and the issue you have is that ``InputOption::VALUE_IS_ARRAY`` alone is equivalent to ``InputOption::VALUE_NONE | InputOption::VALUE_IS_ARRAY``. and if an option does not accept any value, it cannot get its value as an array.

**Comment by javiereguiluz** [comment]
Let's close this because the console component already lets you define two or more array options. Thanks!
