### ISSUE TITLE
[Form] WYSIWYG editor in core

### ISSUE THREAD

**Issue by fredck** [symfony/symfony#15316]
This is a follow up on a F2F talk with @lsmith77 and @webmozart.

I'm proposing including a wysiwyg editor (CKEditor) as part of Symfony's core, in my understanding as part of the Form component.

## Rationale

Rich text editing on web forms is a common requirement. Unfortunately there is usually little attention to the quality of this feature in the PHP world.

There are several solutions for this out there. This situation could sound good but it reflects actually a problem:

 * There are so many solutions that one gets confused. It is hard to find the most appropriate one so one may choose it by case.
 
 * The usual approach today is focused on simply putting the Symfony/PHP bridge in place. There is no attention on making the editor the best possible editing solution.
 
 * Because of the above, editing libraries are usually taken as is, being usually over-bloated on features and misconfigured.
 
 * As a result, the quality of the HTML landing on web applications is low, non-standard and definitely not ready for the future of the web.
 
The idea is bringing a solution that would fit well for 95% of the cases, still making it interchangeable with different approaches, if necessary on specific cases.

The pros:
 
 * It would be much easier for beginners to use a well defined core solution. Advanced developers would have no problems to extend it in the way they need.
 
 * Problem solved! No headache on having to figure out what is the right option out there, many times making a bad choice.
 
 * Quality HTML creation, enhancing the overall quality of the web.
 
## CKEditor

(Disclaimer: I'm part of the CKEditor team)

CKEditor is a leading editing library. It is the solution recently adopted by Drupal 8 and is extremely innovative. It provides all the tools needed for Symfony to successfully provide this solution and for end-users to have a stable editing experience.

The CKEditor team is proposing to cooperate with the Symfony core team to bring this feature to core, but coding and maintaining it, coordinated by the core team.

**Comment by GromNaN** [comment]
Indeed wysiwyg editor is a must-have for a lot of applications.

I've just found [`CKEditorBundle`](https://github.com/Ikimea/CKEditorBundle) that simply adds a form type `CKEditorType` ; isn't it enough ?

**Comment by jakzal** [comment]
There's few solutions out there. Some of them are more advanced then others, which I think shows complexity of this problem. I'm reluctant to support this in the core to be honest, especially if there are existing solutions available already.

**Comment by webda2l** [comment]
Already multiples bundles (http://knpbundles.com/search?q=ckeditor) with two majors https://github.com/trsteel88/TrsteelCkeditorBundle & https://github.com/egeloen/IvoryCKEditorBundle.

In my opinion, support an official bundle yes, integrate a new one to the core, no...
And the fact that Drupal use Ckeditor is not enough, will be somes questions likes why not a markdown editor, why not tinyMce, why not ...

**Comment by lsmith77** [comment]
based on open tickets I searched for, CKEditor and TinyMCE has the most tickets mentioning them .. but that was only 4 and 5 times respectively. Other editors I didn't really find mentioned as at all. Looking in the community the CMF and afaik also Sonata prefers CKEditor atm. So I think IF there is a winner atm it would be CKEditor but not sure if its lead is clear enough to give such strong preference to make it a core provided feature.

we can of course just take one of the above two Bundles and promote it on symfony.com.

**Comment by fabpot** [comment]
The question is: what do we need in core to support those editors? As there are some bundles out there, I suppose that there is nothing to add in core to make it possible in a bundle. that's a classic problem we have. Wouldn't it be better to officially approve one bundle and add it to the official documentation?

**Comment by fredck** [comment]
I know we're talking about different software, but I'll take Drupal as an example. They had like 10 different editor solutions and insisted that there should be no default one. They then decided to go with a "preferred" option, which was compatible with like 10 different editors. There was a big mess because too many options made people confused. And none of them were precisely optimized. Very bad results. Finally they decided to go with an editor into core with Drupal 8. And the same is happening with other CMSs.

Additionally, the point is not bringing "CKEditor" inside core. The idea is bringing the "WYSIWYG field" or "Rich Text Field" into core. It may come with CKEditor today but I would recommend doing it with a level of abstraction that it is not dependent on any editor. If a better option would ever appear in the future, you will be free to change the library included in core. Still the framework API will remain stable and the same, at the same time, taking benefit of all CKEditor can give to users today.

**Comment by liuggio** [comment]
The SF2 philosophy does not push for any architectural or infrastructural choices
(whether it be right or wrong)
and let you develop without third party software.
I'd vote for no on this one, 
but this would open a discussion about adding a layer over the SF core with explicit choices ...

**Comment by stof** [comment]
@fredck the point is, there is nothing to do in Symfony for a rich text field in forms, given that it is just a textarea from a backend PoV. The clean way to mark a field as needing a rich editor IMO is just to put an HTML class on the field to let the JS know it should initialize an editor here.
And contrary to Drupal, Symfony does not provide any JS for your interfaces. Making a choice in Drupal makes sense because they are providing the UI.

**Comment by fredck** [comment]
(1: User need) Let's exemplify this with core field types like "country" or "currency". They could also have been implemented by js, including a class on plain select elements. Still a user need has been identified and a dedicated solution provided. So let's leave apart the UI aspect for a moment and just see this as a field with a very specific purpose: rich editing that outputs HTML. I think we can clearly agree that this a real user need and that this is different than a plain textarea field.

(2: Browser limitations) What is being stated is that it is ok to solve user problems as long as there is native browser ways to solve it. So fortunately "country" and "currency" can be proposed. But browsers don't have an out of the box solution to solve (1).

What I wanted to bring to light is that (1) exists and it is valid to have it solved, just like other fields solve other problems. Otherwise what is the point of having these in core if we could have bundles for them?

But the only feasible way to solve (1) is by using a library that overcomes (2). The UI thing is simply a side effect to make it work, but what Symfony would provide is really a solution for a user need out of the box, mostly like other things in core do.

I understand this may be a strategical challenge, but it is definitely inline with Symfony's scope.

**Comment by yguedidi** [comment]
@fredck Do you mean something like an official form type that provide a textarea with common parameters as HTML data attributes like buttons in toolbar, allow upload, show source, etc...? Then each JS editor will use those attributes to configure itself.

If there is a common standard to configure JS editors, then a dedicated form type makes sense in core (like country or currency as they are a "fixed" list of values), but all the JS part should not be in core.

Unfortunatly, I don't think there is a common standard for WYSIWYG editors...

**Comment by lsmith77** [comment]
if I understand @fredck he is suggesting defining a form type for wysiwyg editors along with sensible options for this form type. the actual configuration would then be done inside a template for one specific wysiwyg editor we decide is the go to option (@fredck obviously hopes this will be CKEditor).

now the question is if we can find "sensible options" .. one thing that would make sense here is to be able to define "button groups" in the config that can then be used inside the template.

**Comment by fredck** [comment]
Yes, I think @lsmith77 described this perfectly.

As for the options, I would go with the basic needs that serve most of the users and have them as part of the SF2 documentation, leaving an additional "pass-through" option which would be delivered as is as editor configuration options so one could have deeper control of it, if needed.

The point is bringing an out-of-the-box well optimized solution for generic use.

**Comment by dunglas** [comment]
CKEditor is definitely the best WYWYWG editor available, however IMO Symfony must be 100% agnostic of JavaScript technologies and libraries. (I think that forms should be directly rendered in standalone Javascript apps than with server-side HTML generation but it's another topic.)

- until now, Symfony is not opinionated about frontend technologies. If we choose to promote CKEditor as "the official way", what's do we must stop? Is promoting Angular as "the official way" OK despite Flux/React?
- managing frontend libraries dependencies is a complex topic (maybe even more complex than in PHP) and we currently have no support for dependency managers such as Bower (and I think we shouldn't). How will we synchronize our releases/updated with CKEditor ones (I think that the CKEditor API evolve too)?
- It makes sense for high software tools such as Drupal to include CKeditor, but Symfony is a lower level layer

@fredck what do you think about publishing an "official CKEditor bundle for Symfony" instead of including CKEditor in the core? Maybe can you talk with @egeloen to brand its bundle (is very straightforward) as an official product?
We can then add a documentation entry on WYWYWG pointing to this official bundle (and alternatives if other WYWYG editors create their own bundles).

This discussion reminds me Assetic. It was a big step forward to include in the standard edition when Symfony 2 was released, but in 2015 pure client-side and Symfony agnostic solutions such as Grunt and Gulp are more appropriated in most cases.

**Comment by stof** [comment]
@fredck the comparison with the country and the money types are not fair. These types are not only about the client-side UI but also about the way the form is processed:
- the country type defines the choices as the list of countries
- the money type applies a data transformer on the submitted value

**Comment by JFOC** [comment]
Redactor Editor is nice, might be need OEM license.

**Comment by WouterJ** [comment]
@dunglas do not forgot that Symfony form does already favor front-end libraries over other libraries, Bootstrap for instance.

However, just as with bootstrap, I don't think it makes sense to include this feature into core. Symfony forms is more about handling request data than handling form rendering and for the request handling part, a WYSIWYG editor is just a textarea.

If there is a popular bundle out there, I welcome a Form cookbook article talking about using that bundle as an example to have rich text editors in your form (starting with doing it yourself and then mentioning "there is a bundle for that!"). This is exactly what we are pushing for in the docs at the moment, to have more mentions of obviously popular bundles solving common problems.

I think such a documentation would fix as much as pushing a rich text field to core code (as both actually come down to mentioning it in the official docs).

**Comment by iltar** [comment]
I agree with @WouterJ on this one. I think it's better to document a recommended Bundle for things like this, than put it in the core. Most people have a dependency on `symfony/symfony`, why should they get a WYSIWYG editor along with it? Out of perhaps 10 big Symfony 2 applications my company has, only 1 needs one of those editors.

My recommendation:
 - Work together with the community/developers to provide a good bundle that properly supports WYSIWYG with the "best" editor, but leave it 3rd party.
 - Document the "best" WYSIWYG Bundle in the documentation.

**Comment by timglabisch** [comment]
i am :-1: to support third party wysiwyg editors.
for me, it's fine to add a cookbook article how to use some third party wysiwyg editors.

**Comment by razmo** [comment]
I think that it should not be integrated in symfony core. 
:+1: for @iltar recommendations.

**Comment by ihsanudin** [comment]
:+1: for @WouterJ, i agree with you

**Comment by anacona16** [comment]
-1, There are more important things to include in the form component as dependent lists, not everyone needs CKEditor but most need a dependent list. And symfony philosophy is not include such libraries in the core, and that both things, CKEditor and dependent lists, existing bundles, so neither is as important as to be at the core.

**Comment by titomiguelcosta** [comment]
:-1: CKEditor integration is easy. In one of the projects I work on, all we have to do is add a class named ckeditor to a textarea and it gets activated. Agree with @WouterJ

**Comment by Macsch15** [comment]
:-1: CKEditorBundle is enough, not everyone needs WYSIWYG editor in core.

**Comment by dewos** [comment]
It would be nice to have instead a semi-official **FormExtraBundle** with inside some third party libs as new form types (CKEditor, Select2 etc...).

**Comment by JHGitty** [comment]
:-1: Do not add WYSIWYG editors to the Symfony core.
:-1: Add WYSIWYG editor bundles to official documentation.

**Comment by boekkooi** [comment]
This looks a lot like the discussion about form JavaScript validation (#4383). So I guess it will have the same outcome.

**Comment by javiereguiluz** [comment]
I'm closing this because most people seems to be against integrating a WYSIWYG editor in Symfony core. But I've created an issue in symfony-docs repo to discuss about having an official bundle for this and for integrating it in the framework documentation (see https://github.com/symfony/symfony-docs/issues/6248).
