### ISSUE TITLE
[2.7] Twig_Error_Runtime: "The "native_profiler" extension is not enabled

### ISSUE THREAD

**Issue by AntoineLemaire** [symfony/symfony#15318]
My issue is the same as https://github.com/symfony/symfony/issues/15228

```
[2015-07-21 00:20:55] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "The "native_profiler" extension is not enabled in "MessageBundle:Emails:new_message.html.twig" 
```

But clear cache on all environment (or only one) does not work.

```
app/console cache:clear --env=prod --no-debug
app/console cache:clear --env=dev --no-debug
app/console cache:clear --env=test --no-debug
```

Still have the problem on prod environment

**Comment by ianfp** [comment]
I'm a little concerned that, since upgrading to 2.7, clearing the cache "wrong" can (and has) broken my production server.

**Comment by AntoineLemaire** [comment]
Have you found a solution for your production ?

**Comment by fabpot** [comment]
@ianfp Not sure I understand what "incorrectly" means here. You should never use the same cache in dev and prod, and as a matter of fact, it did not work before. I think I'm missing something here.

**Comment by ianfp** [comment]
@AntoineLemaire I have a shell script that completely destroys the contents of the app/cache directory:

    rm -rf app/cache/*

I ran that and it seems to do the trick.

**Comment by ianfp** [comment]
@fabpot I think I may be the person who's missing something here. As you can see from my comment to @AntoineLemaire, I've been clearing the cache in an atypical manner for a long time now. I've simply been destroying everything in the `app/cache` directory and then letting it rebuild itself the first time a user accesses the site.

But I've never been using the same cache for dev and prod, as far as I know. After updating my production server, I always run my `rm -rf app/cache/*` script, and I've never had a problem until today. Is it possible that, by not running `cache:clear`, I've left myself open to the cache being incorrectly initialized?

**Comment by stof** [comment]
@fabpot I think this may be another case where cache:clear boots the kernel with the old cache during the cache:clear command, which might lead to weird behavior. If removing the cache manually solves the issue, it is very likely.

**Comment by AntoineLemaire** [comment]
@ianfp Thanks, I'm usually reluctant to do that in prod

So, problem 'solved' :+1:

**Comment by AntoineLemaire** [comment]
Finally, I re-open the issue because:

`rm -rf app/cache/*` works well,
I do `app/console cache:warmup --env=prod --no-debug --no-interaction` after, still working..

Now, if I go to a page with app_dev.php, or if I do `app/console cache:warmup --env=dev`, the problem is here again

**Comment by stof** [comment]
@AntoineLemaire this looks weird. The prod and dev caches are separate.

**Comment by AntoineLemaire** [comment]
@stof I know.
I'll do tests this night on production. I've no problem on local or preproduction.

**Comment by ianfp** [comment]
@AntoineLemaire You haven't overridden the cache directory (as described [here](http://symfony.com/doc/current/cookbook/configuration/override_dir_structure.html#override-the-cache-directory)), have you? Are there separate subdirectories under `cache/` for prod and dev?

**Comment by AntoineLemaire** [comment]
@ianfp Nop, is default configuration

I just run some tests. And I don't know where, and when the problem is occurred
Start with `rm -rf app/cache/* && php app/console cache:warmup --env=prod --no-debug --no-interaction`

No bug, perfect.
Go to a page with app_dev, still nothing.
Try warmup with env dev, still nothing x_X

Wait some minutes, try to check everywhere. During this time, my production continue (crons, jobs, visites...)

And without do nothing else, error is coming back. A mail which is sent when login fail generate it:

    [2015-07-24 05:04:30] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "The "native_profiler" extension is not enabled in "UserBundle:emails:inscription_reminder.html.twig"." at /var/www/project/current/app/cache/prod/classes.php line 3771 {"exception":"[object] (Twig_Error_Runtime(code: 0): The \"native_profiler\" extension is not enabled in \"UserBundle:emails:inscription_reminder.html.twig\". at /var/www/project/current/app/cache/prod/classes.php:3771)"} []

(I removed the cache and warmup near 4:45 AM) 

The only thing I'm sure is, when app/cache/dev is not generated, I don't have any error. (Nothing between 2:00PM and 5:AM on production)

**Comment by xabbuh** [comment]
Do you have (background) jobs that do weird things with the cache directory?

**Comment by AntoineLemaire** [comment]
Normaly not. Just stupids jobs to send mails, or populate documents into ElasticSearch

**Comment by xabbuh** [comment]
And jobs executed via cron? Would it be possible to disable all these jobs temporarily and do the same search for this issue (that you explained above) again?

**Comment by AntoineLemaire** [comment]
Unfortunately no, this is our real production, with all our clients.
And this don't happen in our preproduction server, or in local.

But, juste wake up (again), and saw that in our second front server, the problem was here without app/cache/dev folder, only prod....

I don't understand anything...

**Comment by ianfp** [comment]
@AntoineLemaire Did this problem begin after you upgraded to 2.7? I never saw this before then.

**Comment by AntoineLemaire** [comment]
@ianfp Yes. I did some test today, but this is WE, let's see monday is it's working !

**Comment by ianfp** [comment]
I just took @xabbuh's suggestion and checked my cron jobs, and sure enough, there was one running without `-e prod`. Perhaps the one time I saw this error, it was that cron job that initialized the cache.

But why would that make a difference? If the dev and prod caches are stored in different directories, why would a cron job initializing the dev cache have any effect on Apache, which uses the prod cache?

**Comment by stof** [comment]
@ianfp if you have the cron job running in the dev env but with the ``--no-debug`` option enabled, it may do weird things if you also use the dev env in debug mode (through ``app_dev.php`` for instance) as the default configuration to enable the profiler is based on the debug flag

**Comment by AntoineLemaire** [comment]
No errors in all the WE.
But the only thing I've changed, is add `--no-debug` to `jms-job-queue:run` which was already in `--env=prod`

weird...

**Comment by stof** [comment]
@AntoineLemaire this is weird because the console files should be turning debug mode off automatically for the prod environment (unless you have an old version of this file): https://github.com/symfony/symfony-standard/blob/b79913be0a529a2dea8005bd81aac0af1ffdc5f1/app/console#L19

@fabpot given that many configuration settings are relying on the debug mode to change the configuration, should be use a different cache folder for the debug and non-debug modes ?

**Comment by AntoineLemaire** [comment]
@stof Oh god... my app/console was so old. I've just change it. Let's see if the problem returns. Thanks

**Comment by ianfp** [comment]
My app/console is old, too! It appears to predate the Debug component. Thanks, @AntoineLemaire!

**Comment by xabbuh** [comment]
Do I understand correctly that your issue is solved and we can close this issue?

**Comment by AntoineLemaire** [comment]
It's good for me !

**Comment by fabpot** [comment]
Such problems should now be avoided thanks to twigphp/Twig#1824
