### ISSUE TITLE
It would be better if we can pass closure to the property option  of entity type

### ISSUE THREAD

**Issue by videni** [symfony/symfony#15329]
The reason why we need this  is because there are lots of cases that the label for entity type is  not a simple combination of properties of   a model, sometimes  that transform involves a dedicated service, we don't want to pass a service to model, which makes a model  dependent on upper level object. any body have a alternative to resolve this problem, please?

**Comment by xabbuh** [comment]
With Symfony 2.7, you should be able to pass any callable to the `choice_label` option of the choice type (which is extended by the entity type). Didn't that work for you?

**Comment by videni** [comment]
Thanks, I forgot to mention that  I am using symfony 2.5, is there a alternative in this version, I am not ready to upgrade ?

**Comment by xabbuh** [comment]
No, you will have to upgrade or backport the code on your own.

By the way, please be aware that Symfony 2.5 will even not receive any security related updates by the end of this month.

**Comment by xabbuh** [comment]
You can check the support state of the Symfony version you use with [the Symfony version checker](http://symfony.com/roadmap#checker).

**Comment by videni** [comment]
I see, thanks for your reminder.
