### ISSUE TITLE
[Validator] Callback constraint not called when applied to getter

### ISSUE THREAD

**Issue by janedbal** [symfony/symfony#15335]
Following example does not produce any output, but when the constraint is used on property (instead of its getter), is does.

``` php
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Constraints as Assert;

class Test {

    private $name;

    public function __construct($name) {
        $this->name = $name;
    }

    /**
     * @Assert\Callback({"MyValidator", "validate"})
     */
    public function getName() {
        return $this->name;
    }
}


class MyValidator {

    public static function validate($object, ExecutionContextInterface $context) {
        echo 'IT WORKS!';        
    }
}

$test = new Test('test');
$validator = Validation::createValidatorBuilder()->enableAnnotationMapping()->getValidator();
$violations = $validator->validate($test);
```

Tested on symfony/validator 2.7.2

**Comment by stof** [comment]
You are missing a ``@`` in your code, so there is no annotation in your snippet

**Comment by janedbal** [comment]
@stof Sorry about that typo. The problem is with correct annotation of course. I've fixed it in example.

**Comment by adamziel** [comment]
http://symfony.com/doc/current/reference/constraints/Callback.html

Defining Assert\Callback for class method will call that method. You want to define this constraint on the class level:

```php

/**
 * @Assert\Callback({"MyValidator", "validate"})
 */
class Test {

    private $name;

    public function __construct($name) {
        $this->name = $name;
    }

    public function getName() {
        return $this->name;
    }
}
```

**Comment by janedbal** [comment]
@adamziel Thanks for explanation, but is that really expected (and wanted) behaviour when I explicitly define the ```callback``` option?

**Comment by xabbuh** [comment]
That's the expected behaviour. If you add the `Callback` constraint to a method, this method will act as the callback to be called.
