### ISSUE TITLE
[ DependencyInjection] Container::getServiceIds() missing from any interface

### ISSUE THREAD

**Issue by znerol** [symfony/symfony#15336]
The public method `Container::getServiceIds()` is not declared in any interface. This method is used by several Symfony bundles both in test as well as in production code. It is also required in Drupal.

I guess an appropriate place for the method declaration would be in `IntrospectableContainerInterface`.

Could this go into 2.8 or should I only open up a PR for master?

**Comment by stof** [comment]
Adding it in an existing interface is not possible (it is a BC break). But we could indeed add a new interface for that.

**Comment by znerol** [comment]
Even if the interface lacks the `@api` tag?

**Comment by znerol** [comment]
Background on the `IntrospectableContainerInterface`: #3557

**Comment by stof** [comment]
@znerol adding methods in an interface is always a BC break. Even though non-api interfaces may be allowed to do such BC break according to our policy, we also have a note sayign that it should be avoided whenever possible. In the current case, it does not deserve a BC break IMO (thus we should probably tag IntrospectableContainerInterface as ``@api`` btw).
Thus, getting the list of service ids does not really belong to IntrospectableContainerInterface IMO. It is a different kind of feature than the one defined in the IntrospectableContainerInterface.

**Comment by znerol** [comment]
Diffing the container class and the interface I found some more which do not seem to be declared anywhere:

```
public function compile()
public function getParameterBag()
public function isFrozen()
```

Before I will cook up an interface for `getServiceIds()`, do you think that any of those methods is related enough such that I can include it also?

**Comment by fabpot** [comment]
I don't see why all methods should be in an interface.

**Comment by znerol** [comment]
Perhaps at least those which are used by other bundles/component/projects?

**Comment by fabpot** [comment]
But then again, why? what does it bring to the table? I mean, you can only type hint by one interface, so adding another one would not help, right?

**Comment by stof** [comment]
``compile`` does not make sense in the interface IMO. It is only useful during container building

**Comment by znerol** [comment]
I examined the usage of the other methods mentioned in one of my comments above. Those are indeed only used inside the component.

Regarding `getServiceIds()`, my goal is to understand whether it makes sense to declare that in some interface in Symfony. This is in order to make it possible for Drupal to specify what kind of container it requires. Since over there we also use `initialized()` a lot, the new method declaration either needs to go into `IntrospectableContainerInterface` or into a new child interface.

So, is it worth to submit a PR and if yes which approach should it implement?

**Comment by fabpot** [comment]
`initialized()` is indeed the only method that should have been in the interface, but it's not because it was added late in the game. I propose to add it to the interface in Symfony 3.0.

**Comment by znerol** [comment]
Filed #15346

@fabpot Does this mean that this issue here is a wont-fix?
