### ISSUE TITLE
[Form] Default value option

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#15334]
Hi! I propose to add an option called 'default' for form fields:

Before:

    $builder->add('assignedTo', 'entity');
    $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($authenticatedUser) {
                /** @var Issue $issue */
                $issue = $event->getData();

                if (null === $issue->getAssignedTo()) {
                    $issue->setAssignedTo($authenticatedUser);
                    $event->setData($issue);
                }
            }
        );

After:

    $builder->add('assignedTo', 'entity', ['default' => $authenticatedUser])

**Comment by jonag** [comment]
Isn't what the option [data](http://symfony.com/fr/doc/current/reference/forms/types/entity.html#data) do ?

**Comment by yceruto** [comment]
The documentation says otherwise: The default values for form fields are taken directly from the underlying data structure (e.g. an entity or an array). The data option overrides this default value.

The data option is "default value" if the instance is null, otherwise overrides this instance in my case.

**Comment by stof** [comment]
Well, why not setting the default value in the underlying object before binding the form ? This way, there would be no need for anything special.

**Comment by yceruto** [comment]
@stof True. That would be an option, but when we use Sonata or EasyAdmin have to overwrite controllers to handle this default value and would not be a good choice.

**Comment by yceruto** [comment]
@stof In some cases it's solved in the controller of the entity but when we need to access a service then it gets ugly.

**Comment by yceruto** [comment]
@stof it's also good practice to encapsulate this job within the form type (for reusability)

**Comment by yceruto** [comment]
@stof Even the option is useful although there is no object associated with the form.

Inside controller:

    $form = $this->createFormBuilder()
            ->add('filter', 'checkbox', ['default' => false])
            ->getForm();

    $form->handleRequest($request);

    if ($form->get('filter')->getData() === true) {
        //do something...
    }

In this case the filter field would show false by default. When filter is changed to true and submit form, continue true the filter value. This is not possible so simple with the `data` option.

**Comment by adamziel** [comment]
@yceruto You could listen to PRE_SET_DATA event dispatched by every form on it's creation:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L484

```php

        // Guarantee that the *_SET_DATA events have been triggered once the
        // form is initialized. This makes sure that dynamically added or
        // removed fields are already visible after initialization.
        if (!$this->defaultDataSet) {
            $this->setData($this->config->getData());
        }
```

**Comment by yceruto** [comment]
@adamziel In the header code use PRE_SET_DATA event.

There are many ways to configure a default value in Symfony:
- In the constructor of the entity (provided they have not used services or other entities instances),
- In the controller action, in the underlying object before binding the form,
````
     $issue = new Issue();
     $issue->setAssignedTo($this->getUser()); //default value

     //if I were to use this form again in another place, I could not forget the default value written above.
     $form = $this->createForm('issue', $issue);
````
- In a form type, using the PRE_SET_DATA event,
- Or making a form type extension that adds the `default` option to all forms (the best option for me),
- And maybe some more.

Maybe this could be seen as useless, but in my opinion is very basic for working with forms and all these ways could be summed up in one that encompasses all possibilities.

**Comment by yceruto** [comment]
won't fix :(
