### ISSUE TITLE
[DependencyInjection][3.0] Add initialized() to the ContainerInterface

### ISSUE THREAD

**Issue by znerol** [symfony/symfony#15346]
The `initialized()` method has been added to the container in order to check whether a service is already initialized quite late during Symfony 2 development (#3557). In order to prevent a BC break a new interface was added (`IntrospectableContainerInterface`).

Let's clean that up in 3.0 and move `initialized()` to the `ContainerInterface` and drop `IntrospectableContainerInterface`.

**Comment by stof** [comment]
Dropping IntrospectableContainerInterface in 3.0 would mean that it is harder to write code compatible with both 2.8 and 3.0 and wanting to know whether it can introspect the container.
Should we drop it in 3.0 or no ?

**Comment by stof** [comment]
The issue here is that the interface cannot be deprecated in 2.x, so it would mean it is a removal without deprecation, which is bad for the upgrade.

I suggest keeping the interface (with no extra method in it) in 3.x but deprecating it.

**Comment by znerol** [comment]
Fine, PR updated.
