### ISSUE TITLE
Mapping random key-value pair of XML payload in Symfony2

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#15341]
Hi,

I've open [an issue in here](https://github.com/schmittjoh/JMSSerializerBundle/issues/470) but since I'm not sure which place is the most appropriate one, I'm posting it here too. I hope no one gets annoyed by this, if so, I do apologise. Example uses `"jms/serializer-bundle": "0.13.0"` and based on Symfony app.

Thanks

**Comment by iltar** [comment]
It looks like this is about JMS Serializer and not Symfony.

**Comment by xabbuh** [comment]
Yeah, it looks like you have an issue with either the JMS Serializer or with its bundle. So I'm gonna close here. Feel free to reopen and provide more information if you think it's actually in issue in Symfony.
