### ISSUE TITLE
form can't map violation to corresponding form field automatically

### ISSUE THREAD

**Issue by videni** [symfony/symfony#15342]
As I know , an unmapped form filed , its value won't be validated,so I have to validate it manuallly, the purpose of  step 1 to demonstrate a child form named userContact is not mapped.
#1. unmapped child form 

``` php
 addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
             $data = $event->getData();
                $orderform = $event->getForm();
                $contactForm = $this->formFactory->createNamed('userContact',    
    vmsp_checkout_contact_type', $data, array(
                    'auto_initialize' => false,
                    'mapped' => false,
                    'label'=> false,
                    'error_bubbling'=>true,
                ));
                $orderform->add($contactForm);
```
#2. Map error manually:

``` php
 ->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event){
            $orderForm = $event->getForm();
            //validate userContact.
            $userContactForm=$orderForm->get('userContact');
            $userContact=$userContactForm->get('userContact')->getData();
            $violations=$this->validator->validate($userContact);
            $vm = new ViolationMapper();
            foreach($violations as $violation)
            {
                $vm->mapViolation($violation,$userContactForm);
            }
        });
```
# Question

I have set up validation rules for UserContact entity, one of the rule is to ensure that its userName is not empty.
When I submit empty userName, I can see that error in symfony debug tool bar, but that error message doesn't display in a web page, the error message is  supposed to be displayed under  userName field of child form userConact. so why symfony can't map the error automatically?anyway to do that?

**Comment by xabbuh** [comment]
Honestly, I do not understand what you are trying to achieve. Why are you actually disabling the mapping of form data if you then still want to validate the input data?

**Comment by stof** [comment]
there is an issue way to validate an unmapped field:

```php
$builder->add('subfield', TextType::class, array(
    // ...
    'mapped' => false,
    'constraints' => array(new Valid()),
);
```

**Comment by HeahDude** [comment]
The validation happens on the root of the form and often on a underlying entity, then fields are only validated by cascade.

Hence if a field is not mapped to the root, it is not part of the validation, this is expected IMO.

The solution given by @stof to attach constraints to a field thanks to the option that stands for it, is the way to go.

I think we can close this one.

**Comment by tmbdrogba** [comment]
What if we want to validate a mapped field that belongs to a non-mapped one ?

The validation does not happen, and there is no way to do it.

**Comment by HeahDude** [comment]
The way to do it is to attach a custom `POST_SET_DATA` event and use `Form::addError()` on the field you want.
