### ISSUE TITLE
[FrameworkBundle] Move session files outside the cache

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#15359]
In ea84bb025b4679903d31919c509638930f74318f , the default location for the session files was set to `%kernel.cache_dir%/sessions`. It means that every time the cache is cleared, everyone is logged out. The location is configurable though, so [working around this problem is quite easy](http://vvv.tobiassjosten.net/symfony/keep-symfony2-sessions-through-cache-clear/). Nevertheless, I think the default location should be changed to something else so that one does not have to make this location change on each project. I can make a PR if you can recommend a new default location (`app/data/sessions`? `var/sessions`? ).

**Comment by iltar** [comment]
I think that `var/sessions` is a good location as default in 3.0.

**Comment by greg0ire** [comment]
Ok. I'll work on master since this probably should be considered backwards-incompatible (deployment scripts could need some work, for instance).

**Comment by iltar** [comment]
You could make it configurable in the Kernel and make the default setting in 2.x still use the cache dir as standard.

**Comment by greg0ire** [comment]
It is already configurable (see link to blog post in my initial comment). For the moment, I'm kind of stuck because [I cannot run the test suite](https://github.com/symfony/symfony/issues/15363)

**Comment by fabpot** [comment]
In the Symfony SE 3.0 directory structure, sessions are under the var directory, so there is no change to be made in Symfony itself.

**Comment by greg0ire** [comment]
Ok, I guess this can be closed then.
