### ISSUE TITLE
cannot change http statusCode to 200 in the ExceptionListener

### ISSUE THREAD

**Issue by Filix** [symfony/symfony#15350]
I have an ExceptionListener, in the onKernelException function I init a new Response, and set statusCode to 200, but the page always returns a 500 statusCode.
How to change the statusCode to 200? 

I tried setting to other status code works well, such as 400, 502.. It seems that only 200 does not work

```
 public function onKernelException(GetResponseForExceptionEvent $event)
 {
        $response = new Response('hi', 200);
        $event->setResponse($response);
 }
```
the statusCode: 
![image](https://cloud.githubusercontent.com/assets/2655567/8851173/5502a470-3180-11e5-9239-13642d15d7ee.png)

**Comment by issei-m** [comment]
You can set the status code by setting `X-Status-Code` to the header:

```
 public function onKernelException(GetResponseForExceptionEvent $event)
 {
        $response = new Response('hi');
        $response->headers->set('X-Status-Code', 200);
        $event->setResponse($response);
 }
```

**Comment by issei-m** [comment]
btw, `X-Status-Xode` header is used in `HttpKernel::handleException` internally, and is removed in there. So it is never sent to the client.
See [doc](http://symfony.com/doc/current/reference/events.html#kernel-exception) for detail.

**Comment by Filix** [comment]
@issei-m Thanks a lot! It works!

**Comment by Loupax** [comment]
Just out of curiosity, why is this design in place?

**Comment by ansidev** [comment]
For Symfony version 3.3 or later:

```php
public function onKernelException(GetResponseForExceptionEvent $event)
{
        $response = new Response('hi');
        $event->allowCustomResponseCode();
        $event->setResponse($response);
}
```

**Comment by dcshiman** [comment]
you can set a new status code for the current response in kernel.response event subscribers
`public function onKernelResponse(FilterResponseEvent $event) {
        $response = $event->getResponse();
        $response->getStatusCode() !== \Symfony\Component\HttpFoundation\Response::HTTP_UNAUTHORIZED ? :
	        	$response->setStatusCode(\Symfony\Component\HttpFoundation\Response::HTTP_OK);
        $event->setResponse($response);
    }
`

**Comment by ansidev** [comment]
Please beautify your code snippet!

**Comment by dcshiman** [comment]
that was a fast response, i was working on it

**Comment by ansidev** [comment]
Use Markdown syntax ```php to highlight PHP code
