### ISSUE TITLE
Symfony2 security defaults for cookies

### ISSUE THREAD

**Issue by rcousens** [symfony/symfony#15353]
Hi,

Just seeking enlightenment regarding the default values for cookies with Symfony2. 

http://symfony.com/doc/current/reference/configuration/framework.html#cookie-httponly

Documentation here states the default value for cookie's created by the framework are for httponly to be set to false.

I've personally encountered numerous Symfony2 apps where existing XSS injection vulnerabilities resulting in identify theft could be easily mitigated by changing this value to true. Below is the relevant OWASP documentation:

https://www.owasp.org/index.php/HttpOnly

I can't help but wonder the rationale behind providing less than secure defaults? 

Cheers

**Comment by timglabisch** [comment]
+1 for setting `httponly: true` by default.

**Comment by sstok** [comment]
:+1: This is already the case for Security `remember_me`

**Comment by xabbuh** [comment]
I agree with you, but I'm closing nonetheless as this a duplicate of #15303.
