### ISSUE TITLE
ClassMapGenerator find class without name

### ISSUE THREAD

**Issue by sergiusd** [symfony/symfony#15351]
If use PHP 5.6 structure CLASS::class in code such as

    \Client\CommonApiV02C_Push::class

then method

    \Symfony\Component\ClassLoader\ClassMapGenerator::findClasses

find class with empty name

    array (
        0 => 'Client\\Common\\Api\\V02\\Test\\C\\PushTest',
        1 => 'Client\\Common\\Api\\V02\\Test\\C\\',
    )

Need to check for empty class name, or change the order of analysis

**Comment by WouterJ** [comment]
I can confirm this bug and fixed it by ignoring the `::class` constant (which is better than skipping empty class names imo) in https://github.com/symfony/symfony/pull/15376

Status: Reviewed

**Comment by stof** [comment]
I just though about another case leading to a similar output: anonymous classes on PHP 7
