### ISSUE TITLE
Login loop after upgrading from 2.3.30 to 2.3.31

### ISSUE THREAD

**Issue by acpbytron** [symfony/symfony#15352]
After upgrading from 2.3.30 to 2.3.31, when a user logs into the site they are redirected back to the login page even if the authentication was successful.

**Comment by jakzal** [comment]
Would you mind to fork the [Standard Edition](https://github.com/symfony/symfony-standard), and reproduce your issue on a new branch with minimum code involved?

**Comment by acpbytron** [comment]
Have investigated further.  

The problem occurred while processing the redirect to the default page.  

```
[2015-07-29 14:56:39] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". [] []
[2015-07-29 14:56:39] event.DEBUG: Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\BodyListener::onKernelRequest". [] []
[2015-07-29 14:56:39] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2015-07-29 14:56:39] event.DEBUG: Notified event "kernel.exception" to listener "FOS\RestBundle\EventListener\AccessDeniedListener::onKernelException". [] []
[2015-07-29 14:56:39] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2015-07-29 14:56:39] security.INFO: Authentication exception occurred; redirecting to authentication entry point (A Token was not found in the SecurityContext.) [] [
]
```

I deduced that the security token was not being stored in the session correctly.  I changed the session fixation strategy to NONE and logged in again -  the login redirected correctly.  I changed the strategy back to the default (migrate) and the login carried on redirecting correctly.

FYI I am on php version 5.5.9.

**Comment by jakzal** [comment]
Hm... could be related to #15243

**Comment by xabbuh** [comment]
@acpbytron Could you test if the issue persists for you when reverting the changes from #15243 locally?

**Comment by andy-morgan** [comment]
I have also encountered this issue (completely independantly), and locally reverting the changes from https://github.com/symfony/symfony/pull/15243 fixed the issue for me

**Comment by acpbytron** [comment]
Unfortunately,  I have been unable to replicate the issue since changing the fixation strategies.

**Comment by jakzal** [comment]
@andy-morgan I could not reproduce it. Is it possible you provide a failing test, or code that would prove this is an issue?

**Comment by andy-morgan** [comment]
I'll have a go. Our circumstances we're a bit strange (using SSO), but will see if I can recreate it using, the standard bundle.

It seems to be an issue when a previous session doesn't exist. For us if we'd logged in on a different site also under the SSO, and then visited the site the user should get logged in - this is where we were getting the redirect loop (it is not an issue when symfony is at 2.3.30).
* If we logged in via the site where I'd updated to 2.3.31 this was an issue, the redirect loop didn't happen
* When in the redirect loop, if I opened up the profiler in a new tab (thus creating a session), the redirect would work properly and everything was ok
* We have `require_previous_session` set to `false`. When I have changed this to `true`, then again the redirect loop doesn't happen

For the moment, setting `require_previous_session` to `true` has been our solution.

**Comment by andy-morgan** [comment]
@jakzal , I've tried to recreate it using the standard edition (https://github.com/andy-morgan/issue-15352/tree/issue-15352-on-2.3) but haven't been able to.

**Comment by jakzal** [comment]
@andy-morgan with no way to reproduce the problem we won't be able to solve it.

**Comment by seltzlab** [comment]
@jakzal I was facing a similar issue using the PDO session storage, the cookie was not sent in the response. Checking this commit https://github.com/symfony/symfony/commit/99b9c78b0034194d8ee27b9917e4d01fac8fb47f I realized that the problem was in loadSession(). Here the started property is set to true but the session looks like it's not started yet. Changing the call from loadSession() to start() (which include the loadSession()) seems to solve the problem.

**Comment by jakzal** [comment]
@seltzlab any chance for code (standard edition fork) that would reproduce the problem?

**Comment by xabbuh** [comment]
closing because of the lack of feedback

@acpbytron @andy-morgan @seltzlab Please feel free to reopen if you can come up with more information on how to reproduce your issue.
