### ISSUE TITLE
After upgrading from 2.6 to 2.7 https via CloudFlare stopped working for me

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony#15360]
I use CloudFlare in front of my Symfony application. On my server I have nginx with `set_real_ip_from` setting set to the IPs of CloudFlare. So that Symfony gets real user IP, not the trusted proxy's one. In my Symfony application I have `access_control` policy set to `requires_channel: https`. And now when I upgraded to 2.7 my app stopped working: I'm getting circular redirects from https url to https url, as Symfony doesn't consider the request secure anymore. I'm not sure what has changed and how to fix that properly. Could anyone propose a solution for that?

I found this issue #11583 but it's still open, and I'm not sure how it is related to my problem.

**Comment by xabbuh** [comment]
@denisvmedia Can you debug if and why `isSecure()` in the `Request` class returns `false`?

**Comment by denisvmedia** [comment]
@xabbuh yes, it returns false.

**Comment by denisvmedia** [comment]
@xabbuh it returns `false`, because the IP I'm getting is not in the `trusted_proxies` array (as it is changed by nginx to the real user's IP), but the thing is that it worked before 2.7.

**Comment by denisvmedia** [comment]
Check the code:

```php
        if ($this->isFromTrustedProxy() && self::$trustedHeaders[self::HEADER_CLIENT_PROTO] && $proto = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_PROTO])) {
            return in_array(strtolower(current(explode(',', $proto))), array('https', 'on', 'ssl', '1'));
        }

        $https = $this->server->get('HTTPS');

        return !empty($https) && 'off' !== strtolower($https);
```

The request is not from Trusted Proxes, and as such, all other conditions are not checked anymore. `$this->server->get('HTTPS')` is obviously not set (as internally nginx runs in non-secure http).

**Comment by xabbuh** [comment]
Which version did you run before updating to Symfony 2.7? Did that version contain the changes from #14166? If not, does your application on the old version still work when you apply the changes from #14166 manually?

**Comment by denisvmedia** [comment]
It was some dev commit of Symfony 2.6, bust yesterday I switched to 2.7.*. The version I used didn't contain the changes #14166 (as it was older). To be precise, this change affects the problem:

```php
//if (self::$trustedProxies && self::$trustedHeaders[self::HEADER_CLIENT_PROTO] && $proto = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_PROTO])) {
if ($this->isFromTrustedProxy() && self::$trustedHeaders[self::HEADER_CLIENT_PROTO] && $proto = $this->headers->get(self::$trustedHeaders[self::HEADER_CLIENT_PROTO])) {
```

This worked for me before because I have something on the list of `trusted_proxies`, but now when you started checking if the actual request really came from the proxy, it stopped working for me. I realize the reasons why this change was done, and probably it's a good idea in general. But in my case I don't know, how to make the things working properly (i cannot remove `set_real_ip_from` from nginx). So, I might set some extra field in nginx, or maybe I can do some settings in Symfony, I'm not sure...

P.S. Someone outside GitHub proposed me doing this:
```php
// web/app.php

// ...
Request::setTrustedProxies(array($request->server->get('REMOTE_ADDR')));
$response = $kernel->handle($request);
```
It should start working, but I'm not sure if it's the right way.

**Comment by ricardclau** [comment]
@denisvmedia Since you cannot know the IPs (as they may change) of your ELBs in a Cloud environment this is as good as it gets when you are running a Symfony2 application behind such load balancers architecture. 

Essentially, you are saying: "Yes, my application runs behind a set of ELBs and I trust them all". 

Hope this helps!

**Comment by denisvmedia** [comment]
@ricardclau I get it, but I'm wondering, is there any security risk doing it this way?

**Comment by ricardclau** [comment]
@denisvmedia Well, if the machine where your application is hosted has access from everywhere, all these HTTP headers can indeed be faked. So, essentially you should only enable access to these boxes from the ELB

**Comment by denisvmedia** [comment]
Ok, thank you. Closing.
