### ISSUE TITLE
[Console] Correct max width for ChoiceQuestion

### ISSUE THREAD

**Issue by miraage** [symfony/symfony#15368]
https://github.com/symfony/Console/blob/2.7/Helper/QuestionHelper.php#L160

Here is a wrong calculation for cyrillic values.

```php
- $width = max(array_map('strlen', array_keys($question->getChoices())));
+ $width = max(array_map('mb_strlen', array_keys($question->getChoices())));
```

**Comment by RusAlex** [comment]
Indeed, I also interested what is the policy in symfony
components. Where unicode allowed multibyte string functions have to
be used?

On Sat, Jul 25, 2015 at 06:12:52PM -0700, Mikhail Osher wrote:
>    [1]https://github.com/symfony/Console/blob/2.7/Helper/QuestionHelper.ph
>    p#L160
> 
>    Here is a wrong calculation for cyrillic values.
> 
> - $width = max(array_map('strlen', array_keys($question->getChoices())));
> + $width = max(array_map('mb_strlen', array_keys($question->getChoices())));
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
> References
> 
>    1. https://github.com/symfony/Console/blob/2.7/Helper/QuestionHelper.php#L160
>    2. https://github.com/symfony/symfony/issues/15368

-- 
Mr Alexander Pletnev
Development & Support
Viber: +79109209300
www.Benchmark54.com

**Comment by mheki** [comment]
solution is not that straightforward,  as `sprintf` doesn't count properly multibyte strings length. PR is on its way
