### ISSUE TITLE
Redirect loop on login page on AccessDenied when user is authenticated remember_me

### ISSUE THREAD

**Issue by moldcraft** [symfony/symfony#15370]
After I started authenticating the users with remember_me, when a logged in user opens a page that throws AccessDenied, it is redirected to login page, then that page throws AccessDenied, because only anonymous users can access it `@Security("not is_authenticated()")`, and a redirect loop happens.

I debugged the problem and reached [this line](https://github.com/symfony/symfony/blob/58efb98c6fa6d3d4f63cbaf31a6ca86e23782b2f/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L120), 
when I change `->isFullFledged($token)` to `->isRememberMe($token)` everything works fine: When an authenticated user opens an AccessDenied page, it remains on that page and sees the error message `Expression "not is_authenticated()" denied access.`

Is this a Symfony bug or I am doing something wrong?

**Comment by iltar** [comment]
@moldcraft I think that's the wrong way to check authentication. I think you could solve this by using `IS_AUTHENTICATED_FULLY` or `IS_AUTHENTICATED_REMEMBERED`: http://symfony.com/doc/current/cookbook/security/remember_me.html

**Comment by moldcraft** [comment]
I get it

```
if @Security(...) is False {
    if IS_AUTHENTICATED_FULLY {
        displayAccessDeniedPage()
    } else {
        redirectToLoginPage() 
    } 
}
```

Thank you
