### ISSUE TITLE
date form type should allow min, max as in html5

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [symfony/symfony#15375]
I'd like to be able to configure exact min and max values for date fields. I can specify a range for the years but that doesn't allow me to set the min to the current date.

**Comment by krocos** [comment]
I suppose it can help you [#3533](https://github.com/symfony/symfony/issues/3533), is it?

**Comment by Tobion** [comment]
As explained multiple times, `attr` can be used for this.
