### ISSUE TITLE
absolute_url replaces `asset`'s third argument but is not able to generate absolue urls for CLI-apps

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#15379]
`absolute_url` relies on the request stack which is empty for a CLI application.

Which means there is no official (easy) way to generate an absolute url in a CLI app anymore.

So it's either `absolute_url` should be fixed somehow or another way of doing that introduced.

PS: also asked it on a stackoverflow: http://stackoverflow.com/q/31665098/251311

**Comment by sandermarechal** [comment]
I am running into the same problem. IMHO the `absolute_url` function should fall back on the globally defined request context if no master request is available.

**Comment by sandermarechal** [comment]
Even worse, the deprecated behaviour of using the 3rd argument on `asset()` also does not work anymore, because it uses the HttpFoundationExtension internally.

**Comment by fabpot** [comment]
I've explained this in #15448
