### ISSUE TITLE
SessionHandler class not fully qualified

### ISSUE THREAD

**Issue by Johnny600** [symfony/symfony#15378]
Guys, this is caused by the class calling the same class that is reserved by PHP(SessionHandler())

You need to change this across the board and modify the code.

Regards,

David Mabaso - HackerJack

**Comment by Tobion** [comment]
Please provide details about your bug report. I don't understand what you mean.

**Comment by jakzal** [comment]
@Johnny600 your bug report is not clear to me either. Could you elaborate please?

**Comment by Tobion** [comment]
Closed because of no feedback.
