### ISSUE TITLE
[PropertyAccess] Field selector

### ISSUE THREAD

**Issue by endroid** [symfony/symfony#15373]
I think it would be nice to have a field selector in PropertyAccess that matches items that have a specific property value and allow expressions like `band.member[address.street=Abbey Road].firstName`. Is it possible to add this to the PropertyAccess component or are there reasons not to?

The same can be achieved by using the expression language component but this requires writing more logic. The above seems a much cleaner solution.

**Comment by vudaltsov** [comment]
I think, this is too much for the PropertyAccess component, because its purpose is to fetch data, not to make decisions about it. The issue could be closed, I think.

ping @xabbuh , @nicolas-grekas

**Comment by endroid** [comment]
Yes maybe it is.
