### ISSUE TITLE
SecurityDataCollector.php: Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by bokonet** [symfony/symfony#15377]
Hello,

we got the following php exeption: `Fatal error: Nesting level too deep - recursive dependency? in .../vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php on line 74`

The user / userRole configuration is the same as in our other projects, we use only 11 users and 2 userRoles with doctrine. After some google we could fix the error with changing the line 74
from
 `if (!in_array($role, $assignedRoles)) {`
to
`if (!in_array($role, $assignedRoles, TRUE)) {`

Is this a bad or good thing?

We found a lot of information in this thread:
http://stackoverflow.com/questions/3834791/fatal-error-nesting-level-too-deep-recursive-dependency#comment31801209_19097159

**Comment by iltar** [comment]
I've had a similar issue with entities which were recursive. `in_array` without true as 3rd argument will go though the objects and compare all scalars. Are your roles objects/entities with recursion?

If that fixes the issue, can you make a pull request to fix this?

**Comment by bokonet** [comment]
So, hopefully the pull request is correct...
@iltar: The user entity is related to the roles and backwards.
