### ISSUE TITLE
[2.7 BC break] Assetic-bundle throws error message in prod environment

### ISSUE THREAD

**Issue by XitasoChris** [symfony/symfony#15381]
When using the Assetic bundle to manage assets, I get an exception in prod environment:

> Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Symfony\Bundle\AsseticBundle\Templating\StaticAsseticHelper::__construct() must be an instance of Symfony\Component\Templating\Helper\CoreAssetsHelper, instance of Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper given, called in /srv/www/htdocs/myproject/app/cache/prod/appProdProjectContainer.php on line 307 and defined" at /srv/www/htdocs/myproject/vendor/symfony/assetic-bundle/Templating/StaticAsseticHelper.php line 33

From having a look at the code, it seems the problem is that in 2.7 the `templating.helper.assets` service has a different type:
> The templating.helper.assets was refactored and returns now an object of the type Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper instead of Symfony\Component\Templating\Helper\CoreAssetsHelper. You can update your class definition or use the assets.packages service instead. Using the assets.packages service is the recommended way. The templating.helper.assets service will be removed in Symfony 3.0. ([UPGRADE-2.7.md](https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md))

The Assetic bundle requires an instance of the (now deprecated) `Symfony\Component\Templating\Helper\CoreAssetsHelper` ([StaticAsseticHelper.php:33](https://github.com/symfony/AsseticBundle/blob/master/Templating/StaticAsseticHelper.php#L33)) but is now given the new class `Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper`.

This change was introduced in commit [f74a1f2dc34d8b141e1f4bfbbfa1dbb7d955fe42](https://github.com/symfony/symfony/commit/f74a1f2dc34d8b141e1f4bfbbfa1dbb7d955fe42).

It seems to me this is a backwards compatibility break which should be fixed for Symfony 2.7. Or do you think that the AsseticBundle should simply update their type hint (which also fixes the problem)?

**Comment by stepanets** [comment]
I've got the same error after update symfony from 2.3 to 2.7.2. This error occurs when I call foreach ($view['assetic']->javascripts(array(... in my php template. Is it bug or should I make something to fix it?

**Comment by Kevinrob** [comment]
This change is described in [UPGRADE-2.7.md](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.7.md) in section `FrameworkBundle`.
But I'm agree with you, this sound like a BC break!

**Comment by stepanets** [comment]
@Kevinrob this change about using CoreAssetsHelper in custom service, but I just use function out of box

**Comment by XitasoChris** [comment]
@stepanets Well, yes, but the Assetic-bundle defines such a "custom service" so the code in the would need to be changed according to that description. However, since the upgrade to 2.7 is only a minor version upgrade, I think that this should not have been broken in the first place.

**Comment by XitasoChris** [comment]
Could someone of the project contributors please comment whether this is something that will be fixed or not? The problem is that currently the AsseticBundle is broken. So if it is decided that Symfony does not fix this, then the AsseticBundle will need to be updated. However, if the AsseticBundle is updated now and Symfony decides to revert the change that introduced this issue, then the AsseticBundle will be broken again.

**Comment by stof** [comment]
@XitasoChris there is a PR fixing this in the bundle; https://github.com/symfony/AsseticBundle/pull/371 (and no, the way this is fixed in AsseticBundle would not break if the change gets reverted)

**Comment by XitasoChris** [comment]
@stof That's great to know, thank you! (The only downside is that this PR removed the type hint, but seems there is no other solution if we want to support Symfony 2.6 and 2.7 as those pass in different types.)

**Comment by xabbuh** [comment]
closing as this has been fixed with symfony/assetic-bundle#371
