### ISSUE TITLE
[Console] InvalidArgumentException - Incomplete definition. 'columns' required.

### ISSUE THREAD

**Issue by oliver13** [symfony/symfony#15388]
Hello,

I have made several changes to my enties. When I try to synchronise them to the database with the symfony console (php app/console doctrine:schema:update --force) I get this error :

[InvalidArgumentException] 
Incomplete definition. 'columns' required.

I have checked my definitions and cannot find the error. 
Would be very nice if someone can give me a hint where to look at.

Thanks in advance.

Symfony version 2.7.2
Doctrine version 2.5.1

**Comment by oliver13** [comment]
Ok, I found the reason why I got this error. There was a wrong index definition in one of my entities. Maybe it is possible to rename the error message ? It took me several hours to find this out.

**Comment by stof** [comment]
These messages are not coming from Symfony at all, so I'm closing this issue. Please report it to the Doctrine ORM project

**Comment by jurchiks** [comment]
Some more useful information - this error pops up if you have an index with `fields` defined, where the field is referencing a missing property in the entity. e.g. `#[ORM\Index(fields: ['version'])]` but no `private int $version`.
