### ISSUE TITLE
[Form] ValidatorTypeGuesser sets new default to input option

### ISSUE THREAD

**Issue by mvhirsch** [symfony/symfony#15387]
I just hitted a problem with the *ValidatorTypeGuesser*.
While using it sets the option *input* to "string" instead of the documented default value (as of *Form Field Reference*) to "datetime".

Steps to reproduce:

```
// my entity
class Employee
{
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthDate", type="date", nullable=true)
     */
    private $birthDate;
}
```

```
# validation.yml
AcmeBundle\Entity\Employee:
    properties:
        birthDate:
            - Date: ~
```

```
// Formtype
class EmployeeType extends AbstractType
{
    /**
     * {@inheritDoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('birthDate')
        ;
    }
```

After this, the webdebug toolbar will give me this about my "birthDate"-field (type date):

Passed options:
input => string

Resolved options:
input => string

This is caused by the following line:
https://github.com/symfony/Form/blob/master/Extension/Validator/ValidatorTypeGuesser.php#L117

I can provide a PR if you will confirm it as a bug.

**Comment by mvhirsch** [comment]
I'm sorry, I forgot to mention my symfony version is 2.7.2

**Comment by OskarStark** [comment]
i can reproduce this error

any idea @webmozart

**Comment by stof** [comment]
@mvhirsch using a ``Date`` or ``Datetime`` constraint on a field containing a DateTime object does not make sense. They will always be considered as being valid. These constraints are mostly meant to be used on properties containing a date stored as string

**Comment by mvhirsch** [comment]
@stof Both, the `Date` and `DateTime` constraint is capable of validating objects too.

I thought I should be able to use the `ValidatorTypeGuesser` for forms in combination of setting `\DateTime` objects on my entity while using the `Date` and/or `DateTime` constraints.

Doing it in a conventional way, I would set my type explicitly:

```
->add('birthDate', 'date')
```

And I'll get a `DateTime` object, not a string.
I think both ways should return the same type of data (either string OR `\DateTime`) not a mixed state.

**Comment by stof** [comment]
@mvhirsch they don't validate them. they consider them as being always valid: https://github.com/symfony/symfony/blob/7f745d72c004dc37572bb57cb772df1f2d8ac146/src/Symfony/Component/Validator/Constraints/DateTimeValidator.php#L36
this means that setting a Date constraint on a field where you store a DateTime object is simply totally useless (assuming your object does not allow passing other things than a DateTime of course)

**Comment by mvhirsch** [comment]
@stof okay, that's my fault and there is no issue (can be closed).

But I got one more question based on this new information: how can I use a TypeGuesser to automatically detect it as date field anyway?

**Comment by mvhirsch** [comment]
Found the solution by using the `Type` constraint:

```
birthDate:
    Type: { type: "\DateTime" }
```

**Comment by OskarStark** [comment]
thanks for sharing the solution @mvhirsch :+1:
