### ISSUE TITLE
Response header of Ajax Cross domain, is not working

### ISSUE THREAD

**Issue by skonsoft** [symfony/symfony#15394]
Hello,

I'm using Symfony 2.7.2. + jQuery 1.1

When i make an ajax call to another application B developped with Symfony, i got a cross domain error.

So, i changed the code of the controller of application B like this: 

```
         public function myAction()
    {
        $response = new Response();
//        header("Access-Control-Allow-Origin: *");
        $response->headers->set('Access-Control-Allow-Origin', '*');
        $response->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, PATCH, OPTIONS');
        $response->headers->set('Content-Type', 'text/plain');
        $response->send();
        $response->setContent('test');
        return $response;
    }
```

When i just use 

```
$response->headers->set('Access-Control-Allow-Origin', '*');
```
I get a header with 2 wilcards:

```
Access-Control-Allow-Origin *, *
```
This method is not working, beacause, the reponse object add an extra '*' wilcard.

The expected response header is: 
__Access-Control-Allow-Origin: *__

Is this a bug in Symfony Response object ?

Currently i'm using the native php solution:
```
header("Access-Control-Allow-Origin: *");
```

**Comment by bicpi** [comment]
Hi,
tried to reproduce, but did not see `Access-Control-Allow-Origin *, *` in the response, where did you see this?

But the main issue here may be that you're sending the response from the controller with `$response->send();`, you just need to return it, it gets sent by your front controller. When sending the response twice, Chrome debug toolbar shows the `Access-Control-Allow-Origin: *` header twice. Removing the `send()` leads to a single `Access-Control-Allow-Origin: *` header.

You may also have a look at [https://github.com/nelmio/NelmioCorsBundle]() for CORS support.

**Comment by skonsoft** [comment]
Thank bicpi for your response. 

When i just render the response (the normal way), i get another problem which is: the content-type is set to text/html despite that i have put $response->headers->set('Content-Type', 'text/plain');.

As a solution, i sent the headers before sending the reponse, so i get the text/plain.

I had made some tests in the response object, but i can not find the source of the problem. So, i continue using the native PHP header function.

**Comment by skonsoft** [comment]
You are right bicpi, the header was sent twice. By removing  ~~$response->send();~~  i get the right headers.

Thank you.  I close this issue.
