### ISSUE TITLE
symfony 2 configurator the path label problem

### ISSUE THREAD

**Issue by kabdessamad1** [symfony/symfony#15395]
hi all, 
in the database configuration the "path" label is not in the right place i guess because the "..symfony-form-column" width 430px in web/bundles/sensiodistribution/css/configurator.css line 28 if you increase the width to 432px its good

![screenshot-localhost 8888 2015-07-28 18-35-54](https://cloud.githubusercontent.com/assets/7712969/8938750/69219c32-3558-11e5-8efc-60e8cee99771.png)

**Comment by fabpot** [comment]
Closing as the configurator has just been removed from Symfony SE.
