### ISSUE TITLE
UserSwitch requires redirect?

### ISSUE THREAD

**Issue by wodka** [symfony/symfony#15391]
Hi, 

Right now the \Symfony\Component\Security\Http\Firewall\SwitchUserListener::handle() sets a RedirectResponse.

I would like to trigger for example a POST request that should already be executed as the "switched" user. This is working if I remove the $event->setResponse line.

But I guess this code is there for a reason? If not I'd create a new config option for the userswitch to work on the first request (this could then also work for stateless authentication)

br Michi

**Comment by stof** [comment]
@wodka switch user before submitting the POST request.
The way user switching is implemented currently indeed works only for stateful authentication methods

**Comment by wodka** [comment]
@stof yes, right now it is handled this way, but it can be changed pretty easily:

Setting the parameter security.authentication.switchuser_listener.class to my custom class:
```php
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\Security\Http\Firewall\SwitchUserListener as OriginalListener;

class SwitchUserListener extends OriginalListener
{
    public function handle(GetResponseEvent $event)
    {
        /**
         * this is to prevent the main user switch from setting the
         * redirect response / stopping the event propagation
         */
        $workaround = new GetResponseEvent($event->getKernel(), $event->getRequest(), $event->getRequestType());
        parent::handle($workaround);
    }
}
```

the thing is, I'm pretty sure that this was done for a reason (i.e. attack prevention like <img src="do_something_bad_to_otheruser?_switch_user=otheruser")

But those can be mitigated by other means.

**Comment by inmarelibero** [comment]
you can have a look at https://github.com/symfony/symfony/pull/12874

**Comment by javiereguiluz** [comment]
Let's close this old issue in favor of #27348 which proposes a refactor of this feature and implements the same idea of sending a POST request to switch users. Thanks!
