### ISSUE TITLE
[DX][WebProfiler] show $_SESSION content in toolbar

### ISSUE THREAD

**Issue by thkoch2001** [symfony/symfony#15396]
When working on authentication an firewalls it comes in handy to see the content of $_SESSION (or better the Symfony session wrapper) for each request. I was surprised not to find it in the request information. It seemed obvious to me that it should be there?

**Comment by bicpi** [comment]
Symfony session attributes are available in the profiler at *Request > Session attributes*. Do you need to see session values from outside Symfony's scope, i.e. a dump of `$_SESSION`?

**Comment by thkoch2001** [comment]
Sorry for the noise. I don't know why I didn't see it. Thank you!
