### ISSUE TITLE
[Security Voters] Can't use VoterInterface and AbstractVoter together in service tags ?

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#15407]
Related to #15404, I created a Voter implementing VoterInterface.
But, in my application I have also other voters extending the AbstractVoter class.

Since I inserted the first as service with the tag 'security.voter', the other voters are not called anymore.

AbstactVoters are working when I remove the VoterInterface,
VoterInterface is working when it is defined ...

```
services:
    voters.images_menu: # is a class implementing VoterInterface
        class:      AppBundle\Security\ImageMenuVoter
        public:     false
        tags:
           - { name: security.voter }
        calls:
            - [setEm,[@doctrine.orm.entity_manager]]

    voters.admin_member: # is a class extending AbstactVoter
        class:      AppBundle\Security\AdminMembersVoter
        public:     false
        tags:
           - { name: security.voter }
```

**Comment by dosten** [comment]
The default strategy is `affirmative`, so, the first voter that grant access stop the execution of the voter.

**Comment by Alsatian67** [comment]
OK but my ImageMenuVoter has this function : 

```
    public function supportsAttribute($attribute)
    {
        return in_array($attribute,array('image_menu'));
    }
```

Why is it stoping the execution of the voters when I do :
```
{% is_granted('admin_member_edit',member) %}
```

**Comment by jvasseur** [comment]
The security component doesn't call the supportsAttribue method so you have to do it yourself in your vote method and return ```VoterInterface::ACCESS_DENIED``` if the attribute isn't supported.

**Comment by Alsatian67** [comment]
OK thank you I didn't notice that in the documentation.
