### ISSUE TITLE
[Config] Enum node with 1 value not possible

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#15402]
Hi,

The enum node definition for the symfony config component is great.. but i cant specify only 1 option:
```
InvalidArgumentException in EnumNodeDefinition.php line 35:
->values() must be called with at least two distinct values.
```

Why is this limited? I.e. an enum with 1 option would still be an enum, imho.

We use some class property for the available values, so we have a single point of entrance where we can comment out an available value, ie;

```php
static private $values = ['a', 'b'];
// ...
->enumNode('foo')
   ->values(self::$values)
   ->defaultValue(reset(self::$values))
->end()
```

This way removing the available value 'b' enforces you to refactor the enum node to a scalar node with custom validation (in_array that is), almost like the enum type does ;-)

**Comment by stof** [comment]
What is the use case for a configuration settings if it does not allow to change the value ? this is why the enum node enforces having a choice currently

**Comment by javiereguiluz** [comment]
@stof apparently, @ro0NL starts with a proper parameter with several values, which is enum-compatible.

However, the values of this parameter change frequently and sometimes they remove all values except one. Obviously at this point the parameter is not an enumeration, but it was previously and it will be again in the future.

**Comment by javiereguiluz** [comment]
At first sight, this feature request looks legit. It would be nice to know the behavior of *1 element enums* in other languages and technologies (Java, Python, MySQL, etc.)

**Comment by ro0NL** [comment]
For MySQL it works;
```sql
CREATE TABLE `test` (
	`test` ENUM('a') NOT NULL
);
```

**Comment by javiereguiluz** [comment]
In case this feature request is accepted, there is a pull request to implement it: #15433.

**Comment by apfelbox** [comment]
I see no real reason (apart from ideology) to prevent single element enums. This seems like a pretty standard way to be forward-compatible. So no real reason to arbitrarily prevent it IMHO.
