### ISSUE TITLE
Add possibility attach event listener to master requests only

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#15436]
~90% of the `kernel.request` event listeners contains boilerplate code like

```php
        if (!$event->isMasterRequest()) {
            return;
        }
````

Imho we can provide new event like `kernel.master_request` and attach listeners to it.

**Comment by sstok** [comment]
:+1:

**Comment by stof** [comment]
Providing a new event is wrong: it means that such listeners will be forced to run before all normal request listeners or after them (depending on the order in which we trigger events), which will removes lots of flexibility compared to the current setup (the only way to hook in the proper place would be to keep using the existing event and the early return anyway)

**Comment by sstok** [comment]
~~One use-case is when you only need a listener to get information from the request.~~
But never mind my use-case :) I'm only doing that for BC (2.3 with no RequestStack).
*I guess its Monday again...*

**Comment by fabpot** [comment]
I'm also :-1: for this.

**Comment by jakzal** [comment]
Few times I felt the need for a master request event like this, but I quickly realised that it's actually better to have a single kernel.request event. What about ESI or ajax requests? They're master requests as well, and it's often needed to distinguish between them too. Should we make events for them?

I think the current way is the most simple and powerful in the same time.

I'm :-1: for introducing a new event.

However, I've got an idea on how to solve this without additional events. I'll give it a go, and either submit a PR here, or create a cookbook for documentation.
