### ISSUE TITLE
[Debug] Error page does not showing stack trace

### ISSUE THREAD

**Issue by ikhsan017** [symfony/symfony#15431]
Correct me if I am submitting issue on wrong repo, because I can't open an issue on symfony/debug

I have just did a composer update on a Silex based project, and all symfony components were updated from 2.7.2 to 2.7.3, but after update, the error page doesn't display any stack trace or meaningful information, as it only says

```
Whoops, looks like something went wrong.
```

here is how I enable the ErrorHandler and ExceptionHandler

```php
$app = new Silex\Application();

/* Load custom config container */
$app->register(new ConfigServiceProvider(), ['config.path' => APP_PATH . 'config']);
$app['config']->load('app');

/** here is where I enable the error handler *//
    ErrorHandler::register();
    ExceptionHandler::register($app['environment'] == 'development' && $app['debug']);

```

Silex web profiler is also enabled, and all exception are shown in the web profiler debug bar

**Comment by nicolas-grekas** [comment]
Only `Whoops, looks like something went wrong.` is displayed when the first arg of `ExceptionHandler::register()` is `true`
Are you really sure that `$app['environment'] == 'development' && $app['debug']` evaluates to `true`?
Looking at the Debug class, we register `ExceptionHandler` before `ErrorHandler`, can you try this change also?

**Comment by ikhsan017** [comment]
tried to hardcode ```ExceptionHandler::register(true)``` didn't change the output, still no stack trace printed out

also trying to dump ```var_dump($this->debug);``` in the ```ExceptionHandler::getContent```, but always get ```false```

will try to find another clue

**Comment by javiereguiluz** [comment]
@ikhsan017 did you manage to solve this issue? Thanks!

**Comment by ikhsan017** [comment]
Using symfony debug 2.8.x now, and yes, it solved

Thanks!

**Comment by monbro** [comment]
I had the same issue and it solved for me when I added the option when creating the silex app `$app = new Silex\Application(['debug' => true]);`
