### ISSUE TITLE
Improving the Symfony Web Debug Toolbar and Profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#15439]
This is a meta-issue to list all the bugs and improvements related to the [new Symfony toolbar](https://github.com/symfony/symfony/pull/15160) and the [new Symfony Profiler](https://github.com/symfony/symfony/pull/15523):

### Bugs

  * [x] The close icon is misaligned in Safari + OS X (fixed in https://github.com/symfony/symfony/pull/16023)

### Improvements

  * [x] The Ajax panel blinks indefinitely when a new request is done. It would be better to blink just for two seconds or so. It may get annoying. Fixed in #15744
  * [x] The toolbar template priorities have changed. It would be nice to tweak them further in order to add a "gap" between templates that allow developers to display custom panels between built-in panels. (fixed in https://github.com/symfony/symfony/pull/16023)

### Bugs

  * [ ] ...

### Improvements

  * ~~[ ] [Exception] Use a dark theme for code snippets (reuse the work done in #12363)~~
  * [x] [Logs] Use a pretty-JSON formatter for the log context. Make it expandable on click? Done in #17852 
  * ~~[ ] [Security] Display the Roles as a list instead of inline JSON~~
  * [ ] [Logs] Highlight some messages if possible (we can highlight contents enclosed by quotes in regular messages and we can also highlight Doctrine queries)
  * [ ] [Mailer] Add a way to see the rendered HTML contents instead of the raw source code for HTML emails.
  * [x] [Translation] Improve the `Show params` toggle
  * ~~[ ] [General] Reconsider the colors used for the status banner. Now: 3xx HTTP  = yellow, 4xx & 5xx = red, otherwise = green. Proposal: 3xx = green, 4xx = yellow, 5xx = red, otherwise = green~~

**Comment by iltar** [comment]
The ajax icon blinks till the request is over, personally I like this because you can see when it's still in progress of making the request. I think this is a nice feature and should remain as it is.

**Comment by derrabus** [comment]
In Symfony 2.7, debug toolbar and profiler shared the same design concepts (textured curved elements). Now that the toolbar got its new flat layout, shouldn't the profiler be adjusted to this look as well? At least the menu on the left side?

**Comment by javiereguiluz** [comment]
@derrabus absolutely! That is the next planned step. We're already in the sketch and mockup phase.

**Comment by derrabus** [comment]
Awesome. :-)

**Comment by stof** [comment]
@derrabus we decided to make it in 2 separate PRs to make things easier to review and manage

**Comment by gharlan** [comment]
> The ajax icon blinks till the request is over, personally I like this because you can see when it's still in progress of making the request. I think this is a nice feature and should remain as it is.

:+1:

**Comment by xabbuh** [comment]
I am also :+1: for keeping the blinking icon as an indicator.

**Comment by hason** [comment]
I have prepared an update of #12363. I will send PR after merging of #15523.

**Comment by xabbuh** [comment]
@javiereguiluz If the icon blinks even when all requests have finished, then this seems to be bug to me too. I just don't think it should stop blinking after a fixed time even if there are still requests being executed.

**Comment by mayeco** [comment]
:-1: for keeping the blinking icon... if you work with many ajax request like in a SPA you will never know when a request start or finished, is very bad :(

**Comment by noniagriconomie** [comment]
Hi, 

it could be cool as well to have the option "switch user" if user has this role.
an input can be present where we the username can be entered with a submit button

<img width="312" alt="capture d ecran 2015-11-25 a 17 13 49" src="https://cloud.githubusercontent.com/assets/13205768/11402458/55690cc2-9398-11e5-9bd8-27119b5b7f20.png">

+

Is there an option to disable translator check? or to remove it from the WDT and profiler?

Many thanks,

**Comment by javiereguiluz** [comment]
Closing this because it's hard to work with "meta-issues" which last a long time. Most of the things listed originally have already been implemented. The others are either not essential or very hard to implement, so we'll deal with them in separate PRs. Thanks!
