### ISSUE TITLE
Image absolute_url in email from CLI

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#15448]
Hi,

I m trying to send emails from the CLI (with a valid scheme/host)

- For the ``{{ url('app_homepage') }}`` => it works (cf http://symfony.com/doc/current/cookbook/console/sending_emails.html#configuring-the-request-context-per-command)
-  For the ``{{ absolute_url(asset('img/app.jpg')) }}`` => does not work

Is this a bug or I should use a different way to succeed ?

Many thanks for your answers,

Cheers,

**Comment by xabbuh** [comment]
What do you mean with "it doesn't work"? Do you get an error message? Is it maybe the same as #15384?

**Comment by noniagriconomie** [comment]
Hi @xabbuh 
thanks for your answer and time

Indeed the function does not return an absolute url with the context being explicitly defined.
- {{ url() }} => returns "http://domain.com" (with scheme and domaine defined)
- but not {{ absolute_url(asset('img/app.jpg')) }} => returns "/img/app.jpg" and not "http://domain.com/img/app.jpg"

**Comment by fabpot** [comment]
First, you must realize, even if it is counter-intuitive, that `url()` and `absolute_url()` are totally different things.

The first one (`url()`) is tied to the routing and gives the possibility to connect URLs with your code (controllers). When asking for an absolute URL, the router uses the Routing context to determine which host to use for instance.

The second one (`absolute_url()`) is tied to the generation of URLs for assets, or anything not related to your code. The function uses the current Request information to determine the host to use. As there is no request when on the CLI, this is empty, and it looks like it does not work correctly.

That explains the different behavior.

We could reuse the `router.request_context.host` parameter for asset generation, but I think it's not what we want. Instead, you should use the [Request Context Aware Assets](http://symfony.com/doc/current/components/asset/introduction.html#request-context-aware-assets) or depending or your needs, the [Absolute Assets and CDNs](http://symfony.com/doc/current/components/asset/introduction.html#absolute-assets-and-cdns) options.

**Comment by zerkms** [comment]
@fabpot 

> ou should use the Request Context Aware Assets

Well, you cannot use them, since the request does not exist.

**Comment by noniagriconomie** [comment]
@fabpot thank you for your answer

I know that they are in fact different, but I was thinking the behaviour could be the same (overriding the context in a CLI env)

I will try with the Absolute Assets and CDNs

But I think It could be usefull to have a twig extension or something like that to get an asset's full path from a CLI (many email are in fact sent from the CLI, email containing images as well)

Cheers !

**Comment by stof** [comment]
@fabpot the issue is that Request-aware assets are not compatible with generation in the CLI, while the previous implementation of absolute asset URLs was because we reused the parameters used to configure the RequestContext in the CLI (i.e. when it cannot be configured based on a Request).

Replacing a feature by a less powerful one was a bad idea here as it is a BC break.

**Comment by fabpot** [comment]
@stof Fine, can you submit a PR to fix this BC break?

**Comment by Rvanlaak** [comment]
Another problem we face with sending emails from CLI is that we have multiple TLDs (`.com`, `.nl`, ...) so partially solved it by mapping a locale against a host, and setting the `host` and `baseUrl` in the `router` context. 

Will this stay working for `asset_url`? Or should we also set the `host` and `baseUrl` somewhere else?

**Comment by noniagriconomie** [comment]
ping @all, any news about this issue?

I'am the only one who uses symfony commands which send emails containing images, images that I want to use with absolute url definded in the router context?

Many thanks!

**Comment by zerkms** [comment]
@noniagriconomie you're not the only one, I'm also suffering from it.

**Comment by breitsmiley** [comment]
I'm also suffering from it.

**Comment by noniagriconomie** [comment]
@xabbuh @fabpot @stof any news of that issue? Thank you.

**Comment by noniagriconomie** [comment]
@xabbuh @fabpot @stof 

Any news of that issue? 

If no, what is the best "hack way" to resolve this? Hardcode the domain?, inject it in all templates?

Many thanks :)

**Comment by xabbuh** [comment]
Status: Reviewed

see #17503 for a fix

**Comment by noniagriconomie** [comment]
thx a lot @xabbuh !

**Comment by patrickbussmann** [comment]
this is still an issue in 4.3.

    {{ absolute_url(asset('assets/images/header.png')) }}

results in

    http://localhost/assets/images/header.png

But even the settings as the request url contains a path.

    POST http://localhost/example/web/public/api/resetting/request

I expect something like

    http://localhost/example/web/public/assets/images/header.png
