### ISSUE TITLE
Excessive performance penalty while loading classes on Mac OS X in dev environment

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#15442]
### Problem

Due to [this PHP bug](https://bugs.php.net/bug.php?id=67220), Symfony execution on Mac OS X + `dev` environment is much slower than it should. The reason is this code in `Symfony\Component\Debug\DebugClassLoader.php`:

```php
// $caseCheck is 2 only on Mac OS X
if (2 === self::$caseCheck) {
    // realpath() on MacOSX doesn't normalize the case of characters
    $cwd = getcwd();
    $basename = strrpos($real, '/');
    chdir(substr($real, 0, $basename));
    $basename = substr($real, $basename + 1);
    // glob() patterns are case-sensitive even if the underlying fs is not
    if (!in_array($basename, glob($basename.'*', GLOB_NOSORT), true)) {
        $real = getcwd().'/';
        $h = opendir('.');
        while (false !== $f = readdir($h)) {
            if (0 === strcasecmp($f, $basename)) {
                $real .= $f;
                break;
            }
        }
        closedir($h);
    }
    chdir($cwd);
}
```

The combination of `chdir()`, `getcwd()` and `glob()` introduces a brutal penalty during application execution. In this [comparison profile](https://blackfire.io/profiles/compare/090f7a1c-0cf8-410b-9ab4-534c1657c078/graph?callname=main()&selected=&settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape) you can see a reduction of 23% in Wall Time and 54% in I/O time just by comenting out that code. I've made several comparisons and these improvements are consistent.

### Solution

The above code just checks if there is a case mismatch in the file name. This check is obviously nice for the `dev` environment, although you almost never make this failure. However, instead of checking this for all classes (~300-500 are loaded for a simple page) we could make the check aftwerwards, only if some error happens while loading the class.

Can anyone think of another solution to solve this performance penalty?

**Comment by nicolas-grekas** [comment]
I think the check is important, because even if a mistake does not happen often, it can have catastrophic consequences (it happened to us ;) ).
We might be able to add a bit of cache and enhance the perf.
Thanks for the analysis btw!

**Comment by stof** [comment]
@nicolas-grekas why does it need to change directory btw ?

**Comment by nicolas-grekas** [comment]
@stof to get the canonical directory name...

**Comment by stof** [comment]
@javiereguiluz the issue is that a case mismatch will not cause an autoloading failure on MacOS (as the filesystem is case insensitive). It will cause an error when deploying your code to a Linux server (with a case sensitive filesystem).

**Comment by nicolas-grekas** [comment]
Sorry, I don't have a proper setup on Mac to test correctly.
@javiereguiluz can you please test the following patch?

```diff
diff --git a/src/Symfony/Component/Debug/DebugClassLoader.php b/src/Symfony/Component/Debug/DebugClassLoader.php
index a2532d3..a620079 100644
--- a/src/Symfony/Component/Debug/DebugClassLoader.php
+++ b/src/Symfony/Component/Debug/DebugClassLoader.php
@@ -32,6 +32,7 @@ class DebugClassLoader
     private static $caseCheck;
     private static $deprecated = array();
     private static $php7Reserved = array('int', 'float', 'bool', 'string', 'true', 'false', 'null');
+    private static $darwinCache = array();
 
     /**
      * Constructor.
@@ -226,14 +227,27 @@ class DebugClassLoader
 
                 if (2 === self::$caseCheck) {
                     // realpath() on MacOSX doesn't normalize the case of characters
-                    $cwd = getcwd();
-                    $basename = strrpos($real, '/');
-                    chdir(substr($real, 0, $basename));
-                    $basename = substr($real, $basename + 1);
-                    // glob() patterns are case-sensitive even if the underlying fs is not
-                    if (!in_array($basename, glob($basename.'*', GLOB_NOSORT), true)) {
+                    $i = 1 + strrpos($real, '/');
+                    $basename = substr($real, $i);
+                    $real = substr($real, 0, $i);
+                    if (isset(self::$darwinCache[$i = strtolower($real)])) {
+                        $real = self::$darwinCache[$i];
+                    } else {
+                        $cwd = getcwd();
+                        chdir($real);
                         $real = getcwd().'/';
-                        $h = opendir('.');
+                        chdir($cwd);
+
+                        $j = 1;
+                        while (1 < $j = 1 + strpos($real, '/', $j)) {
+                            self::$darwinCache[substr($i, 0, $j)] = substr($real, 0, $j);
+                        }
+                    }
+                    // glob() patterns are case-sensitive even if the underlying fs is not
+                    if (false && in_array($real.$basename, glob($real.$basename.'*', GLOB_NOSORT), true)) {
+                        $real .= $basename;
+                    } else {
+                        $h = opendir($real);
                         while (false !== $f = readdir($h)) {
                             if (0 === strcasecmp($f, $basename)) {
                                 $real .= $f;
@@ -242,7 +256,6 @@ class DebugClassLoader
                         }
                         closedir($h);
                     }
-                    chdir($cwd);
                 }
 
                 if (0 === substr_compare($real, $tail, -strlen($tail), strlen($tail), true)
```

**Comment by nicolas-grekas** [comment]
@javiereguiluz can you please also try if removing this `false` in `if (false && `helps?

**Comment by stof** [comment]
@nicolas-grekas please don't use the ``$i`` variable name for different purposes in the patch. It makes the code much less readable and makes mistakes much more likely to happen when overwriting variables for a different purposes (yeah, I know you haven't submitted a PR for it yet, but this will give you a chance to change this before opening it)

**Comment by javiereguiluz** [comment]
@nicolas-grekas I've tested the given patch, but the results are not good :(

### Removing all the code

![removing_code](https://cloud.githubusercontent.com/assets/73419/9043660/57f46afc-3a17-11e5-99e5-4ca12054943b.png)

### Applying the patch

![patch_1](https://cloud.githubusercontent.com/assets/73419/9043667/66d89e94-3a17-11e5-93a4-62caa9f59334.png)

**Comment by javiereguiluz** [comment]
And these are the results or removing the `false &&` condition:

![patch_2](https://cloud.githubusercontent.com/assets/73419/9044063/51a96c9e-3a1a-11e5-8811-381e71a620f5.png)

**Comment by javiereguiluz** [comment]
I've tested the following simplified code:

```php
if (2 === self::$caseCheck) {
    // realpath() on MacOSX doesn't normalize the case of characters
    $cwd = getcwd();
    $basename = strrpos($real, '/');
    chdir(substr($real, 0, $basename));
    $fileSearch = glob($refl->getFileName().'*', GLOB_NOSORT);
    chdir($cwd);

    if (empty($fileSearch)) {
        throw new \RuntimeException(sprintf('Case mismatch between class and source file names: %s vs %s', $class, $real));
    }
}
```

Tests pass correctly on Mac, but the performance gain is very small:

![patch_3](https://cloud.githubusercontent.com/assets/73419/9046099/96516f64-3a28-11e5-8126-97e5649806df.png)

**Comment by nicolas-grekas** [comment]
@javiereguiluz, new patch in #15443

**Comment by javiereguiluz** [comment]
Before testing your new patch, I've simplified the code to the following:

```php
if (2 === self::$caseCheck) {
    if (empty(glob($real.'*', GLOB_NOSORT | GLOB_NOESCAPE))) {
        throw new \RuntimeException(sprintf('Case mismatch between class and source file names: %s vs %s', $class, $real));
    }
}
```

All tests pass correctly on Mac and the performance gain is significant:

![patch_4](https://cloud.githubusercontent.com/assets/73419/9046464/17bbfb8a-3a2b-11e5-8d48-cbf4a6f52293.png)

In any case, I guess I've made some error somewhere or I haven't taken into account something :)
