### ISSUE TITLE
[2.8][FrameworkBundle] Undefined index: name_converter

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#15449]
When loading a configuration where the `name_converter` parameter is missing, a notice is emitted:

```
Undefined index: name_converter
```

config.yml:

```
framework:
    serializer:
        enabled: true
```

Edit: the notice is generated here: https://github.com/symfony/symfony/blob/839e925dffff3d972b66ce950d5e44b32296ba7d/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L974

**Comment by xabbuh** [comment]
Thank you for reporting the bug @alekitto. I have opened a pull request to fix the issue in #15467.
