### ISSUE TITLE
[Form][2.7] How-to : Choice between complex data

### ISSUE THREAD

**Issue by armetiz** [symfony/symfony#15455]
Hi there;

I'm trying to build a quizz where answers are associated to price.
I'm not using Doctrine, just simple VO that I convert to Array

Here an answer collection :
```php
"answers" => array:2 [
     0 => array:2 [
         "name" => "Vol Air France, 17/08/15 à 15h"
         "price" => 1788
     ]
     1 => array:2 [
         "name" => "Vol Air France, 18/08/15 à 19h"
         "price" => 813
     ]
 ]
```

What I'm trying to do is :
- Checkbox / Radio where user will be able to select between each answers. I want to display name & price. Price could be passed using HTML attributes.
- When form is submitted, I want to be able to get selected answer with name & price.

Do you have any idea about how to do it ?

I already tried many things, but without success... 

Regards;

**Comment by stof** [comment]
uses these arrays in the array of choices. then use the ``choice_label`` and ``choice_attr`` options to provide them (note that I'm assuming you use Symfony 2.7+ here as it would be a real pain, for older versions, and setting attributes on choices was not even possible):

```php
$builder->add('selected_answer', 'choice', array(
    'choices' => $answerArray, // this is the array shown in your collection above for "answers"
    'choice_label' => function ($answer) { return $answer['name']; },
    'choice_attr' => function ($answer) { return array('data-price' => $answer['price']); },
    // any other form options you need
));
```

**Comment by armetiz** [comment]
Hi @stof, thanks for your tips.

The problem with this solution is that : The structure of the complex data is associated to "group_by" feature : http://symfony.com/blog/new-in-symfony-2-7-choice-form-type-refactorization#dynamic-choice-grouping

So, injected value to choice_label callback is not an "answer", but "name" / "price"

**Comment by stof** [comment]
arf, I forgot about the grouping. Using arrays as form values will be a pain then. I suggest you to use your VOs as choices without converting them to an array (and use the ``choice_value`` option to build a scalar value for them which can be used to compare choices to the selected value in case you don't use the same instance of your VO inside your array of choices and your object bound to the form as the comparison compares choice values strictly)

**Comment by HeahDude** [comment]
Hi @armetiz, what is the status os this issue ?
__stof__ provided a nice way to deal with your problem.
To avoid dealing with grouped choices you could cast the arrays to objects :
```php
// assuming symfony 2.7+
$form = $this->createFormBuilder()
            ->add('vols', 'choice', array(
                'choices' => array(
                    (object) array(
                        'name' => 'Vol Air France, 17/08/15 à 15h',
                        'price' => 1788,
                    ),
                    (object) array(
                        'name' => 'Vol Air France, 18/08/15 à 19h',
                        'price' => 813,
                    ),
                ),
                'choice_label' => 'name',
                'choice_attr' => function ($choice) {
                    return array('data-price' => $choice->price);
                },
                'choices_as_values' => true,
            ))
            ->getForm();
```

This should work as expected.

**Comment by xabbuh** [comment]
Closing here as this looks more like a support request than a bug report.

@armetiz Please let me know if you don't agree.
