### ISSUE TITLE
Many to many relation in YAML file don't output ON DELETE CASCADE 

### ISSUE THREAD

**Issue by shakaran** [symfony/symfony#15459]
I am not sure if I have to report this bug in Symfony or Doctrine since it is related.

My issue is detailed in StackOverflow:

http://stackoverflow.com/questions/31830131/many-to-many-relation-with-on-delete-cascade-with-symfony-and-doctrine

**Comment by fabpot** [comment]
Closing as this is only about Doctrine.

**Comment by shakaran** [comment]
ok, thanks, filled in Doctrine (if someone it is interested in follow the issue) http://www.doctrine-project.org/jira/browse/DDC-3868
