### ISSUE TITLE
[PropertyAccess] [StringUtil] Double ss at the end is not correct handled

### ISSUE THREAD

**Issue by Noles** [symfony/symfony#15453]
The singularify method should not remove in a singular word the final "s".

Current "singularify":
kiss -> kis
access -> acces
class - >clas

Should be:
kiss -> kiss
access -> access
class - >class

**Comment by PetrulisDotPro** [comment]
StringUtil::singularify is intended to transform plural form to singular form and your bunch of words are all already written in singular form.

Please look at the annotations above singularify method

    /**
     * Returns the singular form of a word.
     *
     * If the method can't determine the form with certainty, an array of the
     * possible singulars is returned.
     *
     * @param string $plural A word in plural form
     *
     * @return string|array The singular form or an array of possible singular
     * forms
     */
    public static function singularify($plural)
    {

Documentation says that the method requires plural form and not singular. That is why you get not expected result. The method is not intended to work with singulars.

**Comment by Noles** [comment]
@PetrulisDotPro  @fabpot  thats OK but than the function is wrong used in PropertyAccessor->writeProperty
Because in case I use "access" as form and entity field name, the "set" accessor which will be searched for is "setAcces". 

The property is only camelized before it is forwarded to "StringUtil::singularify"

```
private function writeProperty(&$object, $property, $value)
    {
        if (!is_object($object)) {
            throw new NoSuchPropertyException(sprintf('Cannot write property "%s" to an array. Maybe you should write the property path as "[%s]" instead?', $property, $property));
        }

        $reflClass = new \ReflectionClass($object);
        $camelized = $this->camelize($property);
        $singulars = (array) StringUtil::singularify($camelized);

        if (is_array($value) || $value instanceof \Traversable) {
            $methods = $this->findAdderAndRemover($reflClass, $singulars);
...
```
