### ISSUE TITLE
No locales known on (custom) error pages

### ISSUE THREAD

**Issue by Mondane** [symfony/symfony#15451]
I've customized my error pages and on those (and all other) pages, I've added a language switcher. The switcher is provide by https://github.com/lunetics/LocaleBundle and works flawlessly on all pages, even the debug variant of the error pages, but not on the actual error pages.

When I trigger a 404 page, I see an empty language switcher. Also, when I dump the locales in my twig template, I get an empty array. 

If this isn't a bug (I've seen this behaviour since at least symfony 2.5), how can I fix this? If it is a bug, is it easy to solve?

NB I've created a ticket about this long ago here https://github.com/lunetics/LocaleBundle/issues/114 but I think it's not their issue since the dump of the locales from the parameters is also empty.

**Comment by iltar** [comment]
@Mondane my best guess is that the listeners are triggered too late which causes them to not be triggered at all on a 404 (which is an exception).

**Comment by Mondane** [comment]
Is this something that should be fixed then in symfony?

2015-08-05 9:38 GMT+02:00 Iltar van der Berg <notifications@github.com>:

**Comment by jvasseur** [comment]
It's not, the bundle you are using explicitly sets the listener priority to have it triggered after the router listener (https://github.com/lunetics/LocaleBundle/blob/master/EventListener/LocaleListener.php#L185) so it's a problem in the bundle.

**Comment by Mondane** [comment]
I agree, I take it up with the bundle developers.
