### ISSUE TITLE
[Form] [2.7] Array of choices like ['string' => Object] and a ModelTransformer no longer working

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#15464]
Hi,

The following code in `2.6.x` was working

```php
$transformer = new MailTemplateToNumberTransformer($this->yMailManager, $this->entityManager, $this->site);

...
->add($builder->create('template', 'choice', [
    'label'   => 'form.report.ymail_template',
    'choices' => $this->getAvailableTemplates()
     ])->addModelTransformer($transformer)
);
```

```php
public function getAvailableTemplates()
{
    $template = array();

    foreach ($this->availableTemplates as $template) {
        $template[$template->getName()] = $template;
    }

    return $template;
}
```

A `dump($template);` would give an array of 
```php
array(
    'string' => Object
    'string2' => Object2
);
```

The `ModelTransformer` would transform the php Object to string, and vice versa depending on the situation.

I didn't find any instruction on upgrade note on how to take care of this to keep it working with `2.7`.

I get with `2.7.3` **Warning: Illegal offset type** as if the transformer was not called, OR the error was raised before calling it.

**reproducing the bug on a symfony standard edition here** : https://github.com/tristanbes/symfony-standard/tree/form-data-transformer

Thanks

**Comment by xabbuh** [comment]
@tristanbes Can you provide a fork of the Symfony Standard Edition that makes it easy to reproduce your issue?

**Comment by tristanbes** [comment]
Here's the link to the fork with the issue simplified and reproduced:
https://github.com/tristanbes/symfony-standard/tree/form-data-transformer

Simply launch builtin php webserver and go to homepage http://127.0.0.1:8000/app_dev.php

**Comment by tristanbes** [comment]
ping @webmozart @xabbuh @stof. Is there something else I can do to help identify the issue ?

**Comment by tristanbes** [comment]
Needs Review

**Comment by weaverryan** [comment]
@tristanbes you just forgot the "Status: " part :). But also, since you're provided a reproduced fork (which is awesome), this bug is technically reviewed and someone can action it.

Status: Reviewed

**Comment by stof** [comment]
@tristanbes choices should match the norm data of your field. Here, your model transformer means that the norm data is a string, not a Food object. I don't understand how this could have worked before (well, actually, I think I do: your transformer handles the case of receiving a Food object already. But this would break your edition form as the existing data would not be selected again)

And if you want your choices to be passed in the new way in your form, you need to set the ``choices_as_values`` option to ``true``

**Comment by tristanbes** [comment]
Well I do not understand quite right. Correct me if I'm wrong @stof :

The form is built with 2 enrties in the array (Food Object); 
Since the choice cannot take array of objects, we add a model transformer.

The model transformer is responsible to convert the Object into a string in order to pass it as a choice list innside the form 
And it's responsible of transforming back the string to the Object when the form is saved. (actually the code was commented out in the fork, because the form crashes before we could save it)

The problem appears upon page display either in create or edit form. Even if, like you said, the existing data would not be selected again, {which i can't confirm/infirm} I didn't have such error like : `Warning: Illegal offset type` 

Thanks :-)

**Comment by stof** [comment]
@tristanbes in 2.7, it is perfectly possible to have an array of objects in choices, when using the new API.
In 2.6, your implementation was a huge hack, because using an array of objects was totally not allowed for the simple API (the ``choices`` option) as choices were the keys in this array (and values were labels). The clean implementation was to use a ChoiceList object (probably an ObjectChoiceList) for that.

**Comment by tristanbes** [comment]
Thanks :-)

**Comment by gharlan** [comment]
@stof In 2.6 it was possible to use an array of objects even without a model transformer. But the objects had to implement `__toString`.

```php
class Template
{
    // ...

    public function __toString()
    {
        return $this->getName();
    }
}

$form->add('template', 'choice', [
    'choices' => $this->getAvailableTemplates(),
]);

if ($form->isValid()) {
    /** @var Template $template */
    $template = $form->get('template')->getData();
}
```

**Comment by bpesquet** [comment]
@stof I'm using the Symfony Form component with Silex 1.3 just like @gharlan.

How am I supposed to write this code in Symfony 2.7 ? I now get 'Illegal offset type' errors, 
the ObjectChoiceList solution you described seems [deprecated](https://gist.github.com/mickaelandrieu/5211d0047e7a6fbff925#form), and the Symfony docs I found don't describe this scenario.

Thanks in advance.

**Comment by stof** [comment]
@gharlan in 2.6, it was not possible. Choices were the **keys** in the array. You were using your objects as labels, not as choices.

**Comment by bpesquet** [comment]
@stof Thanks for answering. 

The following technique was working fine in Symfony 2.4 and (I think) 2.5.
```
// Domain class
class Practitioner {
  // ...
  public function __toString() {
      return $this->getFirstName() . ' ' . $this->getLastName();
  }
}

// DAO class
// Converts query result to an array of domain objects
$practitioners = array();
foreach ($result as $row) {
  $practitionerId = $row['practitioner_id'];
  // buildDomainObject() creates a Practitioner object 
  $practitioners[$practitionerId] = $this->buildDomainObject($row);
}

// Form type class
$builder->add('practitioner', 'choice', array(
  'label' => "Praticien",
  'choices' => $practitioners,
  'expanded' => false, 
  'multiple' => false,
  'mapped' => false  // this field is not mapped to an object property
))

// Route controller
if ($visitReportForm->isValid()) {
  // Retrieve practitioner id from form field
  $practitionerId = $visitReportForm->get('practitioner')->getData();
  // ...
}

I stll haven't figured out how to do now.

**Comment by stof** [comment]
@bpesquet and your domain objects are **not** the choices here, they are the labels (hwihc is why they need to be castable as string). The choices are the ids (which is clear from your controller code, as it gets an id at the end, not an object).
This still works in 2.7 but is deprecated (I think we miss the warning for such case).
The new way is to pass labels as key and choices (your form ids) as value here. This can totally be done too.

**Comment by bpesquet** [comment]
@stof I came to a working solution :

```
// ... (same as before)

// Form type class
$choices = array();
  foreach ($this->practitioners as $id => $practitioner) {
     $key = $practitioner->__toString();
     $choices[$key] = $id;
}
$builder->add('practitioner', 'choice', array(
  'choices' => $choices,
  'choices_as_values' => true,
  'choice_value' => function ($choice) {
    return $choice;
  },
  // ...
))
```
Uglier than before, but working nonetheless. Thanks for your help.
