### ISSUE TITLE
Error in "cache:clear --no-warmup"

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony#15471]
When I tried to update to from symfony 2.6.9 to symfony 2.6.11 , I get the below error , however when i revert to symfony 2.6.9, things work again. Any thoughts?

[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: type

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command.

**Comment by nicolas-grekas** [comment]
If you add the -v (verbose) option, what's the displayed stack trace?

**Comment by nicolas-grekas** [comment]
Oh, by the way, 2.6 is not supported anymore, you should move to 2.7

**Comment by xelan** [comment]
Did you try removing the cache manually? I had a similar issue during an Symfony upgrade, probably caused by stale cache files. After running the following commands,  it worked fine again.
```
rm -r app/cache/*
php app/console cache:clear --env=dev
php app/console cache:clear --env=prod
php app/console cache:warmup --env=prod
```

**Comment by ZCJ** [comment]
@nicolas-grekas it seems it is an issue with doctrine as when I only updated Symfony to 2.6.11, i didnt get an issue but when doctrine odm-bundle got updated, i got this issue. Anyways, I will move to 2.7. Many thanks.

**Comment by ZCJ** [comment]
Thank you @xelan , i tried that, but i didnt work. updating to 2.7 :)

**Comment by corozcop** [comment]
try installing php-zip and php-xml
