### ISSUE TITLE
[Translation] Missing messages while string is already translated by other translation domain

### ISSUE THREAD

**Issue by ricohumme** [symfony/symfony#15475]
Running Symfony 2.7.3 I get missing messages from strings which are already translated by another translation domain.
![missing translations](https://cloud.githubusercontent.com/assets/11029998/9107681/7c3741e6-3c29-11e5-9435-1714098fa944.JPG)

**Comment by stof** [comment]
Well, the question is why you are truing to translate them again in the ``messages`` domain if you translated them already.
The profiler simply shows you that you are doing it

**Comment by ricohumme** [comment]
It could be that the KnpMenuBundle is doing this without me knowing it. Let me check into that.

**Comment by ricohumme** [comment]
Can't find any reference of the MenuBundle doing that. Maybe I'm overlooking something? The missing translation do originate from the menu though. Any idea's ?

**Comment by stof** [comment]
KnpMenuBundle does not use the translator by default. but you may have a custom template using the translator.

**Comment by ricohumme** [comment]
The only reference to the translator I found when generating the menu is the following:
```php
$label = $this->container->get('translator')->transChoice($className, 2, array(), 'entities');
```
This translation is calling on the entities translation file. The result of the label is then translated again somewhere else.
I tried a find in path and came up with the following:
```twig
{% block label %}{% spaceless %}
    {% if options.allow_safe_labels and item.getExtra('safe_label', false) %}
        {{ item.label|raw }}
    {% else %}
        {{ item.label }}
        {#|trans(item.getExtra('translation_params', {}), item.getExtra('translation_domain', 'messages')) }}#}
    {% endif %}
{% endspaceless %}{% endblock %}
```
The commented part was causing the issue here.
Thanks for thinking with me.
