### ISSUE TITLE
Finder returning either forward or backwards slashes

### ISSUE THREAD

**Issue by fritzmg** [symfony/symfony#15472]
I noticed on a Windows installation, that when you use something like
```php
$dirs = Finder::create()->in('foo')->depth(0)->directories();
foreach( $dirs as $dir )
    echo $dir->getPathname();
```
`$dir->getPathname()` will return _either forward or backward slashes_ depending on the OS. Shouldn't this also be noramlized to forward slashes, since other functions in Symfony (e.g. [getRootDir](https://github.com/symfony/symfony/blob/v2.7.3/src/Symfony/Component/HttpKernel/Kernel.php#L355) also normalize to forward slashes?

If PHP's [FilesystemIterator](http://us.php.net/manual/en/class.filesystemiterator.php) class is used, there is a flag to automatically normalize the paths to forward slashes:

> **FilesystemIterator::UNIX_PATHS**
>    Makes paths use Unix-style forward slash irrespective of system default.

**Comment by fritzmg** [comment]
Related: #15474

**Comment by nicolas-grekas** [comment]
Issue #15474 is not related: it's on an other component. On Windows, the Finder should consistently use `\` whereas `/` should be used on other OSes.
The `FilesystemIterator::UNIX_PATHS` can't be set for now but that could be added. PR welcomed.

**Comment by javiereguiluz** [comment]
I agree with @nicolas-grekas here: in Windows we should definitely use `\` because that's the right path separator. @fritzmg it's true that there seems to be an inconsistency in `getRootDir()`, but that should be discussed in a different issue. Thanks!

**Comment by fritzmg** [comment]
Should I create a separate issue?

**Comment by javiereguiluz** [comment]
@fritzmg yes please. And if you find other places where we hardcode `/` even for Windows, please mention those too. Thanks!
