### ISSUE TITLE
Message post_max_size_message not translated

### ISSUE THREAD

**Issue by nickof** [symfony/symfony#15479]
When in a symfony application we upload a big file, this upload causes POST request to exceed PHP post_max_size variable defined in php.ini (if file size exceed post_max_size),
Symfony framework manage this error, but it seems there is a regression -->

In Vendor FormType.php, the function configureOptions set a default attribute 'post_max_size_message' => 'The uploaded file was too large. Please try to upload a smaller file.'

Then in NativeRequestHandler

    $form->addError(new FormError(
                    $form->getConfig()->getOption('post_max_size_message'),
                    null,
                    array('{{ max }}' => $this->serverParams->getNormalizedIniPostMaxSize())
     ));

As we can see, the message $form->getConfig()->getOption('post_max_size_message') is not translated. Or in twig the form errors are displayed without doing a {{ error|trans }} (see in vendor twig templates the definition of the block form_errors) then in our generated html pages we have form errors all translated but this one. All the form error messages must be translated before being passed as a parameter to new FormError(...).

There is the same problem in HttpFoundationRequestHandler.

I verified that all other new FormError(...) declared in vendors take a translated message as parameter and it's the case.

**Comment by gharlan** [comment]
I can confirm this.

**Comment by aitboudad** [comment]
The message is translated through [Validator component](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Validator/ExecutionContext.php)  not in twig here, would you mind forking the standard edition, to reproduce the issue?

**Comment by gharlan** [comment]
> The message is translated through Validator component

I guess it is not translated any more since this change: https://github.com/symfony/symfony/pull/11924
The validator component is bypassed, so the translation does not happen.

**Comment by stof** [comment]
hmm, this is indeed missing the translation here

**Comment by gharlan** [comment]
https://github.com/gharlan/symfony-standard/tree/issue-15479

When the `post_max_size` is catched, the CSRF error is triggered, too. This message is translated.

![screenshot 2015-09-03 15 28 19](https://cloud.githubusercontent.com/assets/330436/9659369/6d956860-5250-11e5-95b4-5e96f1a57701.png)

**Comment by aitboudad** [comment]
ok thanks I'll look into it

**Comment by gharlan** [comment]
> When the post_max_size is reached, the CSRF error is triggered, too.

Do you think this is a bug? Should I open a new issue for that?
