### ISSUE TITLE
[HttpKernel] Root directory values are inconsistent

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#15474]
In the `Kernel` class, the return value of the `getRootDir()` method is normalized (`str_replace('\\', '/', …)`).

```php
public function getRootDir()
{
    if (null === $this->rootDir) {
        $r = new \ReflectionObject($this);
        $this->rootDir = str_replace('\\', '/', dirname($r->getFileName()));
    }

    return $this->rootDir;
}
```

However, in the `app*DebugProjectContainer` class, it is not:

```php
public function __construct()
{
    $dir = __DIR__;
    for ($i = 1; $i <= 5; ++$i) {
        $this->targetDirs[$i] = $dir = dirname($dir);
    }
    …
}

protected function getDefaultParameters()
{
    return array(
        'kernel.root_dir' => $this->targetDirs[2],
    …
}
```

On Windows, this means that `$kernel->getRootDir()` outputs something different than `$container->getParameter('kernel.root_dir)`.

```php
echo $kernel->getRootDir();
// C:/xampp/htdocs/symfony-standard

echo $container->getParameter('kernel.root_dir');
// C:\xampp\htdocs\symfony-standard
```

I'd happily create a PR, however I am not sure how to solve the problem. Should the path normalization in the `getRootDir()` method be removed or should the cache class be adjusted?

**Comment by fabpot** [comment]
I think we should normalize both.

**Comment by leofeyer** [comment]
If we normalized both, the following code would fail on Windows:

```php
$rootDir = $kernel->getRootDir();
// C:/xampp/htdocs/symfony-standard

// Make the path of the current file relative to the root directory
$rootDir = str_replace($rootDir . DIRECTORY_SEPARATOR, __FILE__);

// Because:
//    $rootDir . DIRECTORY_SEPARATOR == C:/xampp/htdocs/symfony-standard\
//    __FILE__ == C:\xampp\htdocs\symfony-standard\web\app.php
```

**Comment by Pierstoval** [comment]
As the root dir is initialized [in the `Kernel` class constructor](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/Kernel.php#L87), maybe every reference to the kernel root dir should be equal to this method?

**Comment by leofeyer** [comment]
If we want to keep using constants such as `__FILE__`, `__DIR__` or simply `DIRECTORY_SEPARATOR`, we must not normalize the path. Otherwise all developers were forced to apply `strtr(__FILE__, '\\', '/')` to these constants.

**Comment by leofeyer** [comment]
I have created a pull request in #15567.
