### ISSUE TITLE
[YAML] Line breaks in folded blocks are handled incorrectly

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#15477]
Test:

```diff
diff --git a/src/Symfony/Component/Yaml/Tests/Fixtures/sfTests.yml b/src/Symfony/Component/Yaml/Tests/Fixtures/sfTests.yml
index 7a54f16..962e021 100644
--- a/src/Symfony/Component/Yaml/Tests/Fixtures/sfTests.yml
+++ b/src/Symfony/Component/Yaml/Tests/Fixtures/sfTests.yml
@@ -51,9 +51,9 @@ php: |
       '~',
     )
 ---
-test: Empty lines in folded blocks
+test: Empty lines in literal blocks
 brief: >
-  Empty lines in folded blocks
+  Empty lines in literal blocks
 yaml: |
   foo:
     bar: |
@@ -65,6 +65,19 @@ yaml: |
 php: |
   array('foo' => array('bar' => "foo\n\n\n  \nbar\n"))
 ---
+test: Empty lines in folded blocks
+brief: >
+  Empty lines in folded blocks
+yaml: |
+  foo:
+    bar: >
+
+      foo
+
+      bar
+php: |
+  array('foo' => array('bar' => "\nfoo\nbar\n"))
+---
 test: IP addresses
 brief: >
   IP addresses
```

Refer to [YAML 1.2 spec](http://www.yaml.org/spec/1.2/spec.html#id2796251) or even [YAML 1.0 spec](http://yaml.org/spec/1.0/#id2567537)

(Also, what you were calling "folded blocks" are actually "literal blocks")

**Comment by stof** [comment]
If you want to submit a patch, please open a pull request instead of pasting a diff in an issue. It makes things easier:

- our CI server runs tests for each PR, giving us the test output
- it gives you authorship on the change (we could achieve it but this would give more work to the one integrating your change, and require more git knowledge than getting one of your commits)

**Comment by javiereguiluz** [comment]
@teohhanhui thanks for proposing this improvement.

As @stof said, we need pull requests to be made in some specific format. I know that the first time this may seem scary or boring, but trust me, it's pretty easy if you follow the instructions described [in this article](http://symfony.com/doc/current/contributing/code/patches.html) of the Symfony docs. If you need any help, please ask us. Thanks!
