### ISSUE TITLE
Dynamically setting parameters.yml with composer install

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#15478]
Hi,

I know that:
> You can only set a parameter before the container is compiled

In general this may not be an issue for many but it would probably be needed in future, like I need it now so, is such thing below possible yet or is there a workaround?

Thanks

This:

```
parameters_dev.yml.dist
   my_key: todays_timestamp_{$timestamp}
```

would generate:

```
parameters.yml
   my_key: todays_timestamp_9845712365
```

after running `composer install`

**Comment by stof** [comment]
I don't understand how the sentence ``You can only set a parameter before the container is compiled`` relates to running ``composer install`` at all.

**Comment by BentCoder** [comment]
It is cited from here: http://symfony.com/doc/current/components/dependency_injection/parameters.html so I guess someone from SensioLabs can answer to that.

**Comment by stof** [comment]
I know where it is cited from. what I don't understand is how this documentation about when setting parameters in the container is allowed related to running composer install.
``composer install`` is totally separate from building and compiling the container.

**Comment by BentCoder** [comment]
Lets move away from that part for a sec. Is what I am asking possible?

**Comment by stof** [comment]
Doing something during ``composer install`` is possible by using composer scripts, which has nothing to do with Symfony (Symfony code is not running when you are running ``composer install`` except for scripts registered in your composer.json which may use it)

**Comment by BentCoder** [comment]
Solution

**1** (may look like a hack)

```
# app/config/config.yml
imports:
    - { resource: config.yml }
    - { resource: my_sexy_file.php }

<?php
// app/config/my_sexy_file.php
$container->loadFromExtension(
   'doctrine_cache',
   [
      'providers' => [
          'my_memcached_cache' => [
              'namespace' => 'hello_hello_'+time(),
           ],
      ],
   ],
);
```

**2** (DependencyInject extension version)

```
    public function prepend(ContainerBuilder $container)
    {
        $container->prependExtensionConfig(
            'doctrine_cache',
            [
                'providers' => [
                    'my_memcached_cache' => [
                        'namespace' => sprintf('hello_hello_%s', time()),
                        'type' => 'array',
                    ],
                ],
            ]
        );
    }
```

**Comment by jrobeson** [comment]
the closest you can come out of the box ( currently) is by using environment variables as per https://github.com/Incenteev/ParameterHandler/

**Comment by bitsbauer** [comment]
Look at this solution with combined setting env variable and running incenteev script from composer: http://stackoverflow.com/questions/39165408/composer-dynamically-set-parameters-variable
