### ISSUE TITLE
Placeholder widget not selected by default in Choice field when expanded = true

### ISSUE THREAD

**Issue by wiistriker** [symfony/symfony#15487]
I have such field:

```php
->add('foo', 'choice', [
    'required' => false,
    'expanded' => true,
    'choices' => [
        'foo' => 'Foo',
        'bar' => 'Bar'
    ],
    'placeholder' => 'Placeholder'
])
```

![Image](https://dl.dropboxusercontent.com/u/1999619/field_render.png)

Why my placeholder radio isn't selected? Is it expected behaviour? I also trying to set required => true for my field

**Comment by florianbelhomme** [comment]
In your controller, when you create the form, you can add the initial data (the second argument of the createForm method).
Which initial data are you using ?

**Comment by wiistriker** [comment]
@florianbelhomme empty array for this example

**Comment by PetrulisDotPro** [comment]
Placeholder can't be selected as default value. You can create choice with empty value.

    ->add('foo', 'choice', [
        'required' => false,
        'expanded' => true,
        'choices' => [
            '' => 'Placeholder',
            'foo' => 'Foo',
            'bar' => 'Bar'
        ],
    ])

**Comment by javiereguiluz** [comment]
Closing it because @PetrulisDotPro's comment showed how to solve this issue.
