### ISSUE TITLE
[ExpressionLanguage] numeric operator "range" is not working consistent with floats

### ISSUE THREAD

**Issue by orfin** [symfony/symfony#15485]
Hi,

in the ExpressionLanguage documentation there's a section about numeric operators: http://symfony.com/doc/current/components/expression_language/syntax.html#numeric-operators
with "range" operator:

> ``user.age in 18..45``
> This will evaluate to true, because user.age is in the range from 18 to 45.

imho it's confusing for an end-user as it sounds like the expression:

``20.25 in 18..45``

should also evaluate to true - of course it won't as "range operator" internally uses range function (http://php.net/manual/pl/function.range.php) instead of making comparision.

Is it possible to make it more consistent by evaluating such expression to: ``user.age >= 18 and user.age <=45``

instead of using "range" function?

Btw. range() is not an elegant way of doing such numeric comparision as it's just slow for that, especially when using big ranges: ``something in 0..10000000``

**Comment by disquedur** [comment]
It's BC break because `range()` can make a range of letter `a in a..z`. I'm not sure anyone has usage of it.

**Comment by stof** [comment]
and ranges created by ``18..45`` can be used for other things than ``in`` comparisons.

thus, ``in`` does not mean ``between``. So making a special case for the in range case would be very weird.

**Comment by orfin** [comment]
Documentation is clear. This operator is named "numeric" operator, there is not a word about letter ranges etc.

> user.age in 18..45
> This will evaluate to true, because user.age is in the range from 18 to 45.

Why if user.age=20.5 this statement returns false?

We're using ExpressionLanguage in our BusinessRulesEngine, mainly operated by non-IT employee. Symfony's documentation was clear for them - but real behaviour of "in range" is totally confusing.

So IMHO this section of documentation should be rewritten as it is not talking about the real behaviour.
Special "between" operator could be useful +1 :-)

**Comment by stof** [comment]
@orfin please open an issue on the symfony-docs repository requesting to clarify the doc
