### ISSUE TITLE
[BrowserKit] CookieJar can parse dates ater Jan 19 2038, but can't return timestamp for them

### ISSUE THREAD

**Issue by dbykadorov** [symfony/symfony#15488]
Symfony\Component\BrowserKit\Cookie::parseDate($dateValue):

When cookie from site contais expires date after January 19 2038 (e.g. Thu, 30-Dec-2049 21:00:00) the parseDate method can parse date correctly into \DateTime object:

<pre>
object(DateTime)[778]
  public 'date' => string '2049-12-30 21:00:00.000000' (length=26)
  public 'timezone_type' => int 2
  public 'timezone' => string 'GMT' (length=3)
</pre>

but \DateTime::getTimestamp() returns false (because int32 overflow?).

As the result I have exception:

<pre>
"The cookie expiration time "" is not valid" in 
vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Cookie.php at line 80
</pre>

It is possible to check such dates and fix them somehow? E.g. try to use \DateTime::format("U") which will return a string '2524510800' or set them to maximum allowed 32-bit timestamp? 

I have this issue for some sites and I can't get response from them...

**UPD:** this issue affects 32bit PHP only.

**Comment by JHGitty** [comment]
Yeah, that's the Year 2038 problem (int32 overflow of unix timestamp).

The php function DateTime::getTimestamp() should be working for 64bit systems:
``In 32-bit system the unix timestamp will overflow if the date goes beyond year 2038 and this method will return false. In 64-bit systems this function will still work as intended.``
Source: Comment 5, http://php.net/manual/en/datetime.gettimestamp.php

You can check it:
``Find out your platform is 64bit with var_dump(PHP_INT_SIZE === 8). If TRUE, your system is 64 bit.``
Source: http://stackoverflow.com/a/5319769

**Comment by JHGitty** [comment]
Please verify that you use the 64-bit version of PHP on a 64-bit operation system.
This issue is related to PHP and not to Symfony2 directly.

**Comment by dbykadorov** [comment]
Yes, I know that this issue related for 32-bit php only (and not Symfony). I've tested my code on another server (64bit RHEL + 64bit PHP) and all works fine.

But unfortunately I have 32bit php in my dev env for now =((

It is possible to check if result of the \DateTime::getTimestamp() call is false and return max available timestamp for it?

I'm using Symfony\Component\BrowserKit\Cookie via Guzzle - maybe it is possible to create my own cookie class or something else?

**Comment by JHGitty** [comment]
``It is possible to check if result of the \DateTime::getTimestamp() call is false and return max available timestamp for it?``
No, please do not try it! Change it in your application and not in the Symfony core files. Other developers would be really confused about it.

Do you really need the timestamp? Why? You can save the DateTime in a lot of difference ways.

**Comment by dbykadorov** [comment]
@JHGitty I do no need a timestamp here. But it needs for vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Cookie.php at line 80

I'm just make a Guzzle request (whic using BrowserKit component core files) and I need a workarround for this issue to get response with no exceptions when some site set cookie expiration date after January 19 2038.

**Comment by dbykadorov** [comment]
Just a local patch to test code locally before I'll upgrade my PHP and other software to x64 verstions (may will be useful for someone):

```php
// vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Cookie.php::parseDate

    private static function parseDate($dateValue)
    {
        // trim single quotes around date if present
        if (($length = strlen($dateValue)) > 1 && "'" === $dateValue[0] && "'" === $dateValue[$length - 1]) {
            $dateValue = substr($dateValue, 1, -1);
        }

        foreach (self::$dateFormats as $dateFormat) {
            if (false !== $date = \DateTime::createFromFormat($dateFormat, $dateValue, new \DateTimeZone('GMT'))) {
                if (!$timestamp = $date->getTimestamp()) {
                    $timestamp = 2146953600;
                }
                return $timestamp;
            }
        }

        // attempt a fallback for unusual formatting
        if (false !== $date = date_create($dateValue, new \DateTimeZone('GMT'))) {
            if (!$timestamp = $date->getTimestamp()) {
                $timestamp = 2146953600;
            }
            return $timestamp;
        }

        throw new \InvalidArgumentException(sprintf('Could not parse date "%s".', $dateValue));
    }
```

**Comment by macpatel** [comment]
@dbykadorov Thanks a bunch man! 
@JHGitty Can't we add this code as a preventive measure in cookie.php  in symphony itself, so that it works everywhere?

**Comment by pchigrin** [comment]
As a workaround use
`return (int) $date->format('U');`
instead of
`$date->getTimestamp()`
It will reduce integer to 32bit boundary.

**Comment by buttererror** [comment]
I had this problem and solved it, check my comment at this [link](https://github.com/FriendsOfPHP/Goutte/issues/259)
