### ISSUE TITLE
[Console] suggestion of deprecated functions

### ISSUE THREAD

**Issue by listerical85** [symfony/symfony#15486]
After running the deprecated command `config:debug` I get the following deprecated message.
![schermafbeelding 2015-08-07 om 11 40 03](https://cloud.githubusercontent.com/assets/6354017/9133105/145f3008-3cf9-11e5-8952-06edf238eaa1.png)

Which made me enter the new command, mistakenly omitting the config part, which resulted in the result below. As you can see it still suggests the deprecated commands as well. I was wondering if this is intended behavior or a bug. 

![schermafbeelding 2015-08-07 om 11 39 52](https://cloud.githubusercontent.com/assets/6354017/9133104/144a92f6-3cf9-11e5-9b77-0514b398a164.png)

**Comment by stof** [comment]
Have you use ``debug:config`` as new command ? The exception message make me thing you typed only ``debug``

**Comment by listerical85** [comment]
@stof That's correct and not what i ment sorry, I was thinking that the suggestions that follow after you make such a mistake should not contain deprecated commands. Is this definition more clear?

**Comment by stof** [comment]
@listerical85 the issue is that the console component does not have a concept of BC alias (or hidden alias) which should be hidden from suggestions

**Comment by listerical85** [comment]
@stof thanks for the answer, I was not aware of that, but thought i had the obligation to at least mention it.
