### ISSUE TITLE
[VarDumper] How to use without actually "dumping"

### ISSUE THREAD

**Issue by sebastianbergmann** [symfony/symfony#15496]
I would like to work on https://github.com/sebastianbergmann/phpunit/issues/1540 but have not yet figured out how to invoke VarDumper so that it returns a string (without colors) instead of printing to STDOUT.

**Comment by nicolas-grekas** [comment]
Cooool :-) Tell me if you need any help!
Here is your answer:
http://symfony.com/doc/current/components/var_dumper/advanced.html
In the dumper section

**Comment by sebastianbergmann** [comment]
Thanks!
