### ISSUE TITLE
[Console] Print command description in help output

### ISSUE THREAD

**Issue by nochso** [symfony/symfony#15498]
`list` will show the command descriptions:

```
Available commands:
  add   Save a command
  help  Displays help for a command
  list  Lists commands
```
However `help add` won't show the description:
```
Usage:
  add <shortcut> <cmd> [<desc>]
...
```
I'd suggest the following, at least as an option:
```
Save a command

Usage:
  add <shortcut> <cmd> [<desc>]
...
```

**Comment by javiereguiluz** [comment]
@nochso thanks for proposing an idea to improve Symfony.

In the past (see #13943) this same idea was rejected. So we can either close this issue for the same reasons ... or reconsider this idea. Let's see what others think about this!

**Comment by nochso** [comment]
Ah, I'll have to search closed issues next time.

As said in #13943, the help section can be used. However..
It might be a good compromise to only show the description when the Command help wasn't defined. That way description and help won't be shown at the same time while being a little more helpful.

**Comment by Nicofuma** [comment]
And what about displaying it if there isn't any help block?

**Comment by javiereguiluz** [comment]
@Nicofuma that's what @nochso suggested in his latest comment. I agree with both of you. This would be a easy to implement and useful compromise solution.
