### ISSUE TITLE
Serializer callbacks: Pass object as second argument

### ISSUE THREAD

**Issue by r0b-** [symfony/symfony#15499]
Hi,

it would be nice to have the attribute's object available in the callback.

Thanks
Rob

**Comment by PetrulisDotPro** [comment]
Hi, I think you can simply bind callback to object you are going to serialize and then use $this in your normalizer callback. However I would say that normalizer callbacks should be defined for some object's attribute. 

For example:

    $normalizer->setCallbacks([
        'Some\Namespace\Object::attribute' => $callback
    ]);

It should allow to define different callbacks for different objects using the same serializer.

Just my two cents

**Comment by r0b-** [comment]
thanks - bindTo would be a workaround, but unfortunately I have some deeply nested structures and it would be a lot of work to arrange the bindings before normalization...

**Comment by javiereguiluz** [comment]
Closing this old issue because the Serializer callbacks now have lots of arguments: https://symfony.com/doc/current/components/serializer.html#using-callbacks-to-serialize-properties-with-object-instances Thanks.
