### ISSUE TITLE
[Form][2.8] using built-in types triggers deprecation notices

### ISSUE THREAD

**Issue by craue** [symfony/symfony#15490]
When the built-in form types are used in a project, deprecation notices are triggered because these types still have a `getName` method. I've noticed this when [trying to update my bundle's code](https://github.com/craue/CraueConfigBundle/pull/22) in order to avoid deprecation notices with Symfony 2.8.

**Comment by Tobion** [comment]
But you should only get the deprecation when referencing form types by their name. If you use the FQCN you don't get a deprecation, do you?

**Comment by craue** [comment]
I don't see where I could still be using a deprecated name.

**Comment by stof** [comment]
Can you try again with the latest 2.8 branch ? A few places were missed during the form migration and so were still using deprecated APIs. They have been fixed a few days ago.

**Comment by craue** [comment]
@stof, did yesterday with the latest 2.8 commit and there are still [53 remaining deprecation notices](https://travis-ci.org/craue/CraueConfigBundle/jobs/79335371#L286).

**Comment by stof** [comment]
OK, I found the issue: in 2.8+, the core form type extensions are still registered with their legacy aliases in the form definitions instead using the new names

**Comment by craue** [comment]
Now the notices are gone (tested locally). Thank you, @stof.
