### ISSUE TITLE
[Security] How to prevent reuse of remember me cookie after user logged out

### ISSUE THREAD

**Issue by PouleR** [symfony/symfony#15508]
I've configured the remember me functionality as described on this page: http://symfony.com/doc/current/cookbook/security/remember_me.html

Security.yml:
            remember_me:
                key: "%secret%"
                lifetime: 604800 # One week
                path: /
                domain: ~
                always_remember_me: true
                secure: true

When I login into my application and I copy the REMEMBERME cookie (using EditThisCookie in Chrome) I can still use this cookie after I logged out. When I paste the cookie back I'm logged again.

How can I prevent that the cookie is being reused after an user logs out?

**Comment by sstok** [comment]
I think you need to use a custom storage for remember-me tokens, then when someone logs out you remove that token from the storage.

http://symfony.com/doc/current/cookbook/security/remember_me.html
And then the `token_provider`, it doesn't seem to be fully documented but you can use the https://github.com/symfony/DoctrineBridge/blob/master/Security/RememberMe/DoctrineTokenProvider.php with your own service definition.

**Comment by jakzal** [comment]
Closing as this is a support question really.
