### ISSUE TITLE
The templating-related shortcuts in the base controller should be usable without the Templating component

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15502]
In Symfony 2.7, we made it possible to use most features of Symfony without enabling the templating component (assuming you don't use a bundle relying on them of course).
However, we have 3 shortcut methods in the base controller which are not compatible with such setup and force the usage of the templating component:

- ``render``
- ``renderView``
- ``stream``

Most projects based on Symfony are probably relying on them, as this is the documented way to render templates.

All of them can be implemented on top of Twig directly quite easily. I suggest doing this in 2.8 in case the templating component is not available.

**Comment by fabpot** [comment]
:+1:

**Comment by aitboudad** [comment]
why not removing the deps in [TwigEngine](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/TwigEngine.php) instead ?

**Comment by stof** [comment]
@aitboudad TwigEngine is only about implementing the interface of the Templating component on top of Twig. Removing the deps in it does not make sense, as it is its goal.

**Comment by dosten** [comment]
IMO the templating component dependency cannot be removed until 3.0 in order to keep BC.

If Twig it's the only enabled engine, we can use it, if not, we should use the templating component.

Also, the template path is different when using Twig or the Templating component, so, doing this automatically can be a BC break.

**Comment by stof** [comment]
@dosten I'm not asking to stop using the templating component when it is available. I'm asking to be able to use the shortcuts when it is not.

and no, the template name is not different. You can have *more* syntaxes when using Twig directly (but this is also the case when Twig is the only engine enabled), but the ``bundle:folder:file.format.twig`` format is supported with Twig too (otherwise you could not use it when referencing a template from Twig itself)

**Comment by Koc** [comment]
Does anybody know what also missing when we using native twig without Templating component? For example stopwatch.

**Comment by WouterJ** [comment]
@Koc I think nothing will be used. Currently, lots of things are duplicated for Templating and Twig

**Comment by stof** [comment]
@Koc Stopwatch integration is indeed not supported there. It might be worth adding it (the native Twig profiler is great to know what happens in Twig itself, but it does not play well with the big picture or the request).

@WouterJ I don't understand your comment

**Comment by WouterJ** [comment]
@stof sorry, I wrote a bad sentence and wrongly understood @Koc's question (I thought he was talking about the stopwatch extension and not the TimedPhpEngine).

**Comment by Koc** [comment]
@stof what can you suggest? In what directions should i moving for adding stopwatch? I have only one sollution: override base template class and override render method.

**Comment by WouterJ** [comment]
@Koc can't you decorate the Twig_Environment and add the stopwatch functionality?

**Comment by Koc** [comment]
maybe. Also should look into node visitors http://php-and-symfony.matthiasnoback.nl/2013/01/symfony2-twig-collecting-data-across-templates-using-a-node-visitor/

**Comment by Koc** [comment]
Please do not close this ticket because some other features are missing, loke Stopwatch integration.

**Comment by fabpot** [comment]
@Koc Can you create another issue for Stopwatch? and close this one because this one is not about Stopwatch (except if you carefully read the whole discussion :)).

**Comment by Koc** [comment]
Ok, will do
