### ISSUE TITLE
[Security]: RememberMe parameter expected to be string

### ISSUE THREAD

**Issue by slde-gorillaman** [symfony/symfony#15509]
While debugging a problem with the remember me services I noticed that the AbstractRememberMeServices is checking the remember me parameter for strings only.
Is there a specific reason for this or is this a bug?
Our XMLHttpRequest has given the parameter as a boolean and therefore was not caught by the service.

https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/RememberMe/AbstractRememberMeServices.php#L318

**Comment by florianbelhomme** [comment]
The parameter come from Request which looking in the GET, PATH or POST. So the type is a string (cannot be something else), this is why the string representation of a bool value is checked.

**Comment by slde-gorillaman** [comment]
Turns out that the default behaviour is overriden. 
We are sending the login data via an XmlHttpRequest using a JSON object. 
The POST etc. data is empty but the HTTP_RAW_POST_DATA contains the JSON object. One of our bundles handles the onKernelRequest event and overrides the parameters by first decoding the JSON object and then calling `Request->request->replace` which leads to settings the remember_me parameter as a boolean.

Since this is not a standard behaviour I am leaving the issue closed for now, however such a scenario might occur frequently and it could be discussed whether or not to have a check for a boolean value as well.
