### ISSUE TITLE
[Validator] Email without strict flag is too liberal

### ISSUE THREAD

**Issue by kuldippujara** [symfony/symfony#15513]
before its checking for 
FILTER_VALIDATE_EMAIL

but now its not checking even basic validations for valid email.
like "kuldip pujara@gmail.com" it allow with space which must not allowed.

we can use regular expression from following 
https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

or we can use FILTER_VALIDATE_EMAIL if strict is false

**Comment by stof** [comment]
``FILTER_VALIDATE_EMAIL`` was used in previous versions of Symfony. but this is rejected many valid addresses

**Comment by dosten** [comment]
the regex it's to liberal, but changing it can be a BC break, you can mark the option `strict` to `true` so, you will use the [egulias/email-validator](https://github.com/egulias/EmailValidator) library.

**Comment by unkind** [comment]
> now its not checking even basic validations for valid email.
> like "kuldip pujara@gmail.com" it allow with space which must not allowed.

Can you you be more specific, please, what does "basic validations" mean? Reject email with space is "basic validation"? But that's not always true, the following email is valid: `"kuldip pujara"@gmail.com`.

**Comment by dunglas** [comment]
Are they but open on PHP.net about valid mail rejected by ext/filter? IMO the best solution is to fix PHP itself. I can work on that if necessary (I know well the filter extension).

**Comment by stof** [comment]
@dunglas I think there is already a bug reporting the fact that it does not validate emails properly

**Comment by stof** [comment]
And no, fixing PHP will *not* allow Symfony to switch to this feature again, until the min supported version is a fixed one (which will take a very long time)

**Comment by dunglas** [comment]
@stof I was not telling to switch back to ext/filter (I'm aware we can't as you explained) but it's not a reason to not fix PHP.
If you have the link to the bug entry or examples of patterns to fix please I'll try to fix it.

**Comment by stof** [comment]
@dunglas https://bugs.php.net/search.php?cmd=display&search_for=FILTER_VALIDATE_EMAIL

**Comment by dunglas** [comment]
OK it's mostly about IDN support? It's not as easy, I have patched PHP to support them but it adds a dependency to ICU and it adding such dependency needs a RFC... https://github.com/php/php-src/pull/890

**Comment by stof** [comment]
@dunglas not only. see https://github.com/symfony/symfony/issues/8771 for instance.
