### ISSUE TITLE
[Console] Warning when command alias is longer than commands name

### ISSUE THREAD

**Issue by madflow** [symfony/symfony#15511]
symfony git:(2.8)

When an alias of a command is longer than the commands name than  there is a warning in the terminal output. The reason seems to be that the maximum width of the command column is only calculated using the "names".

Is this wanted behaviour? Are we using it wrong?

```
<?php

require_once dirname(__FILE__).'/vendor/autoload.php';

use \Symfony\Component\Console\Application;
use \Symfony\Component\Console\Command\Command;

$app =  new Application();

$command = new Command('huba:huba:haba:haba:huba');
$command->setAliases(['huba:huba:haba:haba:huba:alias:huba']);

$app->add($command);
$app->run();
```
```
PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in ...vendor/symfony/console/Descriptor/TextDescriptor.php on line 210
```

Hackfix while debugging for me was changing TextDescriptor::getColumnWidth

to

```    /**
     * @param Command[] $commands
     *
     * @return int
     */
    private function getColumnWidth(array $commands)
    {
        $width = 0;
        foreach ($commands as $command) {
            $width = strlen($command->getName()) > $width ? strlen($command->getName()) : $width;
        }

        if(count($command->getAliases()) > 0) {
            $aliasMaxLength = max(array_map('strlen', $command->getAliases()));
            $width = $aliasMaxLength > $width ? $aliasMaxLength : $width;
        }

        return $width + 2;
    }
```

Tests still pass...

**Comment by stof** [comment]
your code does not work, because it only reads the aliases of the last command (and it breaks totally if there is no command at all btw, because the ``$command`` variable will not be defined in this case).

Anyway, code changes should be submitted as pull requests

**Comment by madflow** [comment]
You are right of course about the premature "fix". I should have left it out because it distracted from my intention to find out if it is "bug or not". I will consider a pull request. Thanks.

**Comment by dosten** [comment]
@madflow see #15515

**Comment by madflow** [comment]
@dosten I did a quick test with the example from above - the warning is not displayed anymore. Problem solved!
