### ISSUE TITLE
array_map should not be used with callbacks which can throw an exception

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15512]
When an array_map callback throws an exception, array_map triggers a warning, which causes debugging to become messy. See https://github.com/Behat/Behat/issues/775

**Comment by nicolas-grekas** [comment]
Fixed in PHP7/HHVM http://3v4l.org/DqdH5

**Comment by nicolas-grekas** [comment]
Would it be a good idea to handle this as a special case in the Debug component?
That would free us from thinking about the issue every time we use array_map...
That wouldn't work for people not using the component though.
We could do both: add a special the case in the Debug component and remove the use of array_map for code path that patently triggers exceptions.

**Comment by stof** [comment]
@nicolas-grekas I suggest doing both (if it is possible in the Debug component).
We already removed such usage from the CssSelector component a while ago.

**Comment by nicolas-grekas** [comment]
If I'm not wrong, there is nothing to do i the Debug component: the warning is not issued when an error handler is in place...
http://3v4l.org/kfu8v

**Comment by fabpot** [comment]
Still relevant?
