### ISSUE TITLE
[OptionsResolver] array of instance allowed type

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#15524]
It could be nice to have possibility to make this kind of requirement:

``` php
->setAllowedTypes('attachments', '\Swift_Attachment[]')
```

Basically, for this case, an array of `Swift_Attachment` objects.

It could be a good beginning waiting #4833.

**Comment by stof** [comment]
@Soullivaneuh the issue with that is that it cannot be implemented easily (it requires some parsing of the string, and looping over the array rther than just checking the value).

There is a workaround though:

```php
$resolver->setAllowedTypes('attachments', 'array')
    ->setAllowedValues('attachments', function (array $attachments) {
        // we already know it is an array as types are validated first

        foreach ($attachments as $attachment) {
            if (!$attachment instanceof \Swift_Attachment) {
                return false;
            }
        }

        return true;
    });
```

**Comment by Soullivaneuh** [comment]
Thanks for the workaround. I already did something similar but with a normalizer.

I let this issue open if somebody got some courage to handle it. ;-)

**Comment by EVODelavega** [comment]
@stof I've sent a PR that would enable typed array support, I've added a couple of simple test cases (`'\DateTime[]'` and `int[][]`), both of which seem to work just fine

**Comment by Soullivaneuh** [comment]
@EVODelavega Maybe you can propose a PR. Not sure if it should be on 2.7 or 2.8.

**Comment by EVODelavega** [comment]
@Soullivaneuh I've taken 2.8 as a starting point, but I should imagine I can patch 2.7 quite easily anyway, so if the maintainers want, I can create a PR, or mail a patch for 2.7 all the same

**Comment by stof** [comment]
@Soullivaneuh new features cannot be added in maintenance branches. So there is no discussion about 2.7 or 2.8: it cannot be 2.7 (you could discuss it between 2.8 and 3.0, but we already have the answer for this: if it is BC it goes in 2.x)

**Comment by Tobion** [comment]
Maybe this problem would also be solved with #4833, i.e. if you consider an array of something as an suboption with any key and it's corresponding type.

**Comment by stof** [comment]
@Tobion I don't think it can. Suboptions work fine when you know the expected children and can configure validation for them. This case is for a list of similar nodes.
If you look at these concepts in the Config Definition component, this is the difference between an array node and a prototyped array node.

**Comment by Tobion** [comment]
I know, but the same thing already is going on when not using suboptions. If you want to allow any option, you have to read the passed options and make them known to the resolver. The same would apply for suboptions.

**Comment by EVODelavega** [comment]
@Tobion I thought about ways to implement what you're hinting at, but decided not to do that because that, IMO, is beyond the scope of _allowed types_. Pre-defining a specific structure, including keys existing or not, and the types of the values they hold is something best left to a custom validator, or in a normalizer.

On the other hand, you could create a wrapper class that defines the given structure in full, and just write `$resolver->setAllowedTypes('foo', 'YourClass');` or, if my PR gets merged `$resolver->setAllowedTypes('foo', 'YourClass[]');`

**Comment by stof** [comment]
@Tobion associative arrays don't mean it is a set of keys defined by the form type. The option could be expectign an arbitrary map.
