### ISSUE TITLE
Method getClientIp in Request return wrong IP with a wrong x-forward-for 

### ISSUE THREAD

**Issue by skonsoft** [symfony/symfony#15525]
Hello,

I pass through a proxy (Squid) which add a header 'X-Forwarded-For' with a wrong IP. So the 'X-Forwarded-For' contains 'unknown'.

I tried to get the Client IP from Request Object like this:

```
$ip = $this->request->getClientIp();
```

Here, i got 'uknown' as IP instead of getting the REMOTE_ADDR when the 'X-Forwarded-For' is not set or is not valid as described in SF Doc.

To fix this, i have to add a test:

```
$ip = $this->request->getClientIp();
if($ip == 'unknown'){
    $ip = $_SERVER['REMOTE_ADDR'];
}
```
This is not the right way to do it, but i need a result in production...

Perhaps, we should fix this in 'getClientIps' method by checking if IP is not valid, so we should use the Remote ADDR.

Symfony version: 2.7.2

Note that i trusted all proxies by adding this code in my front Controller:
```
Request::setTrustedProxies(array($request->server->get('REMOTE_ADDR')));
```

Tip: To reproduce this bug, you can use any HTTP/REST client and  add 'X-Forwarded-For' header  with any  kind of bad values.

Thank you.

**Comment by stof** [comment]
this should indeed be handled inside ``getClientIps`` if ``unknown`` is a common bad value.

but anyway, I also suggest you to report the bug to Squid. Otherwise all your requests will be reported as coming from the Squid server IP.

**Comment by skonsoft** [comment]
Thank you Stof. i don't know if it a common bad value, but, we should fix that in getClientIps as i suggested. The problem is not closely to 'uknown' value, we can get any other bad value. The right way is to check the value extracted from x-forwarded-for if it's not a valid IP, we should use the REMOTE_ADDR.

Here is what i did in my service:

```
$ip = $this->request->getClientIp();

        //@see: https://github.com/symfony/symfony/issues/15525
        if(!$this->isValidPublicIP($ip)){ // check if the IP given by Sf Request is good. Otherwise, use the Native PHP REMOTE_ADDR
            $this->log(sprintf("Bad IP from SF: %s. Try the Remote ADDR\n", $ip));
            $ip = $this->request->server->get('REMOTE_ADDR');
        }
        
        if (!$this->isValidPublicIP($ip)) { // This is a seconf check. If does not pass,... there is a problem
            $this->log(sprintf("Not valid IP: %s \n", $ip));
            return null;
        }
```

I hope this code can give an idea to fix this issue.

**Comment by GromNaN** [comment]
Apparently, this is something that can be configured in Squid: http://www.squid-cache.org/Doc/config/forwarded_for/

	If set to "on", Squid will append your client's IP address
	in the HTTP requests it forwards. By default it looks like:

		X-Forwarded-For: 192.1.2.3

	If set to "off", it will appear as

		X-Forwarded-For: unknown

When Squid is used as a trusted reverse proxy, it must be configured with `forwarded_for on`. But apparently that's not the situation met by @skonsoft.

Here, Squid is an enterprise proxy (not trusted).

	      CLIENT          |         SERVER
	Browser   >  Squid    > Trusted Proxy > Symfony
	192.0.0.1   193.1.2.3      10.1.2.3

With trusted proxy, you get headers like this:

	Remote-Addr: 10.1.2.3
	X-Forwarded-For: unknown,193.1.2.3

You cannot return blindly return the `REMOTE_ADDR` when `X-Forwarded-For` contains an invalid IP address. Instead, an invalid IP address must be removed in [`Request::getClientIps()`](https://github.com/symfony/symfony/blob/v2.8.0-BETA1/src/Symfony/Component/HttpFoundation/Request.php#L825-L834).

**Comment by GromNaN** [comment]
`unknown` is a standardized value, but other "obfuscated" values can be set.
https://tools.ietf.org/html/rfc7239#section-6.2

**Comment by aivus** [comment]
What do you think about check ip address by `filtervar(..., FILTER_VALIDATE_IP)` here:
https://github.com/symfony/symfony/blob/9610602ab5df64118d8b2fabeca4a70d1eda4e11/src/Symfony/Component/HttpFoundation/Request.php#L830 and if it invalid - exclude it?

**Comment by GromNaN** [comment]
I was trying to implement this, but removing invalid IP addresses is incompatible with an existing test : 
[`RequestTest::testGetClientIpsForwarded() #1`](https://github.com/symfony/symfony/blob/9610602ab5df64118d8b2fabeca4a70d1eda4e11/src/Symfony/Component/HttpFoundation/Tests/RequestTest.php#L861)

This assert that if the `Forwarded` header contains `for="_gazonk"`, then this value is returned as client IP. We can ask @tony-co what were the motivations of [this test case](https://github.com/symfony/symfony/pull/11379/files#diff-ff258be5f9da1f743abc56d08e1affd3R895).

**Comment by aivus** [comment]
@GromNaN, I think `_gazonk` test case is wrong.

@stof, what do you think?

**Comment by GromNaN** [comment]
I've submitted a PR #16736
