### ISSUE TITLE
[3.0][Security] target path and security.exception_listener.class

### ISSUE THREAD

**Issue by yannickl88** [symfony/symfony#15534]
Hey all, I ran into this cookbook article http://symfony.com/doc/current/cookbook/security/target_path.html

Since in 3.0 the `.class` parameters will be gone (see https://github.com/symfony/symfony/issues/11881)  this method of overriding will no longer work. Also, since the `Symfony\Component\Security\Http\Firewall\ExceptionListener` does not implement an interface, It cannot be decorated properly without implementing the whole class again.

So, in 3.0 it would no longer be possible to change the default Target Path behavior if this is not refactored.

**Comment by yceruto** [comment]
I'm migrating a project from Symfony2 to Symfony3 with the same problem, any suggestion about this?

Status: Reviewed

**Comment by yceruto** [comment]
I leave here my solution in case someone needs it, I'm not completely sure if it's correct way, but at least it works as I expect.

```
// src/AppBundle/DependencyInjection/Compiler/ExceptionListenerPass.php;

class ExceptionListenerPass implements CompilerPassInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('security.exception_listener.admin');
        $definition->setClass('AppBundle\Security\Firewall\ExceptionListener');
    }
}
```
```
// src/AppBundle/AppBundle.php

class AppBundle extends Bundle
{   
    public function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new ExceptionListenerPass());
    }
}
```

**Comment by calarconpieriz** [comment]
Thanks @yceruto your solution worked for me. I was for 4 days trying to fix it with firewall listeners and handlers, but this is the best approach I found.

**Comment by xabbuh** [comment]
Closing here as this is an issue that will be addressed in the documentation.

**Comment by ptrm04** [comment]
Hi @xabbuh - do you have a link to an issue where it will be addressed?

So far found a brief mention of this at https://symfony.com/doc/current/security/form_login.html:

_Sometimes, redirecting to the originally requested page can cause problems, like if a background Ajax request "appears" to be the last visited URL, causing the user to be redirected there. For information on controlling this behavior, see Security._

Pointing to the security page (http://symfony.com/doc/current/security.html) which does not mention anything about it.

Thanks!

**Comment by yceruto** [comment]
@ptrm04 http://symfony.com/doc/3.2/security/target_path.html

@xabbuh for some unknown reason this topic does not appear since 3.3

**Comment by ptrm04** [comment]
Thank you @yceruto!

**Comment by xabbuh** [comment]
That document was removed in symfony/symfony-docs@1f7d4b51e2caceb3df1e45db91cf42fcac1f100d but I don't remember why. Maybe @weaverryan does.

**Comment by ptrm04** [comment]
ping @weaverryan - any ideas why that document was removed? It'd be nice to have one for Symfony 4 as many users will find it useful.
