### ISSUE TITLE
Difference between service translator in dev and prod

### ISSUE THREAD

**Issue by Hadrien45** [symfony/symfony#15539]
Hi,

I use Symfony 2.7.3.

In appProjectContainer.php, the service "translator" is just an alias for "translator.default" which uses this class (*Symfony\Bundle\FrameworkBundle\Translation\Translator*).

In appDevDebugProjectContainer.php, the service "translator" uses this class (*Symfony\Component\Translation\DataCollectorTranslator*).

Is it normal ?

Thanks

**Comment by stof** [comment]
yes it is normal. In dev, the translator service is decorated with a DataCollectorTranslator to integrate it in the profiler (and with a LoggingTranslator which integrates with the logger).

The only contract we do about the ``translator`` service is that it will implement ``Symfony\Component\Translation\TranslatorInterface``. If you want to typehint the service, use the interface, not the implementation.

**Comment by Hadrien45** [comment]
Thanks !
