### ISSUE TITLE
[Filesystem] rename: not possible to change the case of filename in case-insensitive filesystems

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#15540]
Example:

```php
$filesystem = new Filesystem();
$filesystem->rename('foo.txt', 'Foo.txt');
```

On my mac I get [this `IOException`](https://github.com/symfony/symfony/blob/7f745d72c004dc37572bb57cb772df1f2d8ac146/src/Symfony/Component/Filesystem/Filesystem.php#L272).

Workaround: Set `$overwrite` parameter to `true`.

**Comment by florianbelhomme** [comment]
It's not a bug : if your system is case insensitive the name 'foo.txt' and 'Foo.txt' are the same for him.
The rename function check if the targeted name exist before make the move, so the system response is : yes there's already something with this name, i'm case insensitive so "Foo" or "foo" are the same thing.

**Comment by nicolas-grekas** [comment]
@florianbelhomme is right. Yet, if you want to really do what you're saying, you have to rename twice: first to some random name, then back to the fixed-case name.

**Comment by nicolas-grekas** [comment]
or using $overwrite you're right :)
