### ISSUE TITLE
Recursive resolution of params in ENV submitted settings?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15548]
Sf-std 2.7:

I just tried `SYMFONY__FRAMEWORK__IDE='subl://%%f:%%l' php app/console server:run`
but this fails with `The service "blah" has a dependency on a non-existent parameter "f:". `

Whatever the number of `%` I put in front of `%`, the error is always the same, which makes me wonder if we have a bug here.

**Comment by stof** [comment]
Can you show me how you use this parameter though ? What is this ``blah`` service ?
Or better, provide a reproducing case based on the SE.

**Comment by nicolas-grekas** [comment]
nvm, I messed up with my SE...
