### ISSUE TITLE
[Bug] [Form] 2.7 - Form collection prototype required option

### ISSUE THREAD

**Issue by jeremywaguet** [symfony/symfony#15544]
When using the 'collection' form type with the 'required' option set to false, The rendered HTML is different between the form_widget() macro and the prototype. The macro does not output the required field contrary to the prototype field.

Form definition :
```
$formBuilder->add('emails', 'collection', array(
            'type' => 'email',
            'allow_add' => true,
            'required' => false
        ));
```
Twig Template : 
```
{% for emailField in form.emails %}
    {{ form_widget(emailField) }}
{% endfor %}
```
HTML output :
```
<input name="form[emails][1]" id="form_emails_1" type="email">
<input name="form[emails][2]" id="form_emails_2" type="email">
<input name="form[emails][3]" id="form_emails_2" type="email">
```
data-prototype:
```
<input type="email" id="form_emails___name__" 
name="form[emails][__name__]" required="required" class="" />
```
Is that, the expected result ? I would expect the prototype field not to contain 'required' as the form_widget() macro doesn't output the 'required' field

I know the 'option' parameter is supposed to do the job but as the 'required' parameter is supported, the prototype output should match the macro output.
```
'options' => array(
       'required' => false
  )
```

**Comment by stof** [comment]
I think this is because there is some special logic for the ``required`` option so that a child of a non-required field is also not required. but the prototype is not a child of the collection. It lives separately because it is special. So we would have to handle things specially for it.
We probably have the same issue for the inheritance of the translation domain btw.

@webmozart do you have an idea to fix it ?

**Comment by HeahDude** [comment]
@stof in which case can "translation_domain" inheritance of prototype become an issue ?

**Comment by HeahDude** [comment]
Inheritance of options for the prototype is not preserved, every option except 'label' is set to default by a call to `array_replace`:
```php
// Symfony/Component/Form/Extension/Core/Type/CollectionType.php

public function buildForm(FormBuilderInterface $builder, array $options)
{
    if ($options['allow_add'] && $options['prototype']) {
        $prototype = $builder->create($options['prototype_name'], $options['type'], array_replace(array(
                 'label' => $options['prototype_name'].'label__',
             ), $options['options']));
             $builder->setAttribute('prototype', $prototype->getForm());
     }
    ...
```
