### ISSUE TITLE
[2.6.11] [EventDispatcher] TraceableEventDispatcher resets event listener priorities

### ISSUE THREAD

**Issue by c1tru55** [symfony/symfony#15550]
Looks like bug #8426 is still not fixed

```php
foreach ($this->dispatcher->getListeners($eventName) as $listener) {
            $this->dispatcher->removeListener($eventName, $listener);
            $info = $this->getListenerInfo($listener, $eventName);
            $name = isset($info['class']) ? $info['class'] : $info['type'];
            $wrappedListener = new WrappedListener($listener, $name, $this->stopwatch, $this);
            $this->wrappedListeners[$eventName][] = $wrappedListener;
            $this->dispatcher->addListener($eventName, $wrappedListener); // default priority 0!
        }
```

**Comment by iltar** [comment]
2.6 no longer receives bugfixes, but it seems the same code in 2.7, 2.8 and the master:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L225-L235
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L225-L235
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L225-L235

**Comment by mheki** [comment]
Did you test that behaviour @c1tru55 ?
According to what @fabpot wrote here: https://github.com/symfony/symfony/issues/8426#issuecomment-24020311
> My conclusion is that we don't need to change the way the traceable event dispatcher work as it's more related to a misbehaving security layer (which is fixed now).

code you mentioned didn't have to be changed

**Comment by c1tru55** [comment]
@mheki it resets event listeners priority in dev environment for me (Symfony 2.6.11). In prod env all works fine.

**Comment by jakzal** [comment]
@c1tru55 is this still an issue in Symfony 2.7?

**Comment by xabbuh** [comment]
closing due to the lack of feedback

@c1tru55 Please feel free to reopen when you can reproduce your issue with Symfony 2.7 (or higher).
