### ISSUE TITLE
DOMCrawler plain text

### ISSUE THREAD

**Issue by gagvirus** [symfony/symfony#15556]
I am using Symfony's DomCrawler to fetch an information from website.
In one of the pages there is a text including non-html-encoded text like following :

`<a href="some-url.html">Lorem ipsum <<dolor sit>> amet </a>`
And when I try to crawl the text from the `<a>` tag using the `filterXPath()->text()` method I get `Lorem ipsum <`, because it behaves to symbols like broken html tags and simply ignores them.

Also, when i try to use $node->filterXPath('my-xpath/a')->html(), I also get broken html like following example :

<a href="some-url.html">Lorem ipsum &gt;</a>
So, my question is if there is any way to get the "plain" text out of the node ?

**Comment by dosten** [comment]
duplicated of #15504 please do not open a new issue, you can comment in the anoter issue. Also, as @stof and @jakzal said, there's not much we can do about it.

**Comment by gagvirus** [comment]
Sorry, my fault. Totally forgot that I already opened...
