### ISSUE TITLE
Report deprecations when running a cli app

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15568]
The deprecations could be summarized/aggregated in a similar way to our phpunit bridge, maybe with a new global cli option.

**Comment by stof** [comment]
@nicolas-grekas the trace should also be added in log messages for the profiler (the profiler panel is able to display the trace if it is passed in the logging context as ``trace``, but the Debug component does not pass it anymore)

**Comment by iltar** [comment]
I had a colleague checking 2.8 deprecations and he reported it to be nearly impossible to trace them unless you dig a lot in the code. :+1: for a stacktrace.

**Comment by javiereguiluz** [comment]
@stof's comment is very important. Right now the profiler looks like this for the deprecation messages:

![deprecation-logs](https://cloud.githubusercontent.com/assets/73419/9710695/6ef54b72-553d-11e5-8e14-00192840a3e9.png)

We display neither the trace nor the file name + line number, so this information is not very useful at the moment.

**Comment by nicolas-grekas** [comment]
@javiereguiluz are you sure you have the last version? Because we fixed this a few days ago...

**Comment by javiereguiluz** [comment]
I thought I had the latest version. Can you please point me to the relevant PR that change this? Thanks.

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/pull/15647

**Comment by javiereguiluz** [comment]
Thanks for the link! It now works like a charm:

![deprecation-stack-trace](https://cloud.githubusercontent.com/assets/73419/9711547/b136e5b6-5544-11e5-9271-8cfcd3948317.png)

![deprecation-stack-trace-expanded](https://cloud.githubusercontent.com/assets/73419/9711548/b34d3026-5544-11e5-890f-74ce5d463b0f.png)

**Comment by nicolas-grekas** [comment]
THis thread has been hijacked for adding a stacktrace, which is available no, closing, if someone else wants to create an other issue, or better a PR, please do.
