### ISSUE TITLE
kriswallsmith/assetic is offline, and breaks my symfony install

### ISSUE THREAD

**Issue by samayo** [symfony/symfony#15572]
So, my symfony install for `2.5.*` is getting broken, because this guys https://github.com/kriswallsmith/assetic assetic library is offline. 

Any way to resolve this issue?

**Comment by iltar** [comment]
@samayo for me it's working fine. However, it might be that github is down some times, there is no way to resolve this issue unless you can fix the github issue at hand.

This doesn't really seem like an issue for the symfony repository either.

**Comment by sstok** [comment]
https://status.github.com/ `15:21 UTC Executing a controlled failover to address an underlying hardware problem, a small number of repositories will be breifly unavailable.`

**Comment by samayo** [comment]
@iltar @sstok  I was not talking about github's status as you can see in this picture. http://i.stack.imgur.com/8T4M6.png only that repo was offline.

**Comment by stof** [comment]
@samayo the repo being offline is precisely the github failure, and is explained by the incident report of github (it was one of the repositories being impacted)

**Comment by stof** [comment]
btw, the error page in your screenshot even tells you to check their status website
