### ISSUE TITLE
The Monolog extras should appear in the logger panel too

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15577]
We current display the context of the message, which is a PSR-3 concept.
In 2.8, we also display the channel when available, which is a Monolog-only feature, recognizing that most Symfony projects are using Monolog for logging. There is another Monolog feature which is not displayed in the profiler: extras, i.e. the bucket where processors can attach extra info on the log record. It may be worth adding support for it

**Comment by sstok** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Where can I find more information about the usage of these "Monolog extras"? Thanks.

**Comment by WouterJ** [comment]
https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#adding-extra-data-in-the-records

So just the `'extra'` key in the record.

**Comment by stof** [comment]
Note that the first step to display them will be to update the [Monolog DebugHandler](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Monolog/Handler/DebugHandler.php) to include extras in the data passed to the logger collector. Once this is done, the profiler panel can be updated to display this info when it is available

**Comment by nicolas-grekas** [comment]
Closing as this is getting old, and nobody cared since then.
Ping @lyrixx because I know you like these things if you want to reopen :)

**Comment by lyrixx** [comment]
For now I'm fine with the extra. Thanks for the notif anyway.
