### ISSUE TITLE
Problem with opcache.save_comments / zend_optimizerplus.save_comments

### ISSUE THREAD

**Issue by samayo** [symfony/symfony#15576]
So, I installed fresh copy of symfony yesteday on CentOs7 running nginx and php-7 with this command  
```bash
composer create-project symfony/framework-standard-edition try.symfony "2.5.*"
```

I also generated a bundle `Samayo\FooBundle` using annotations and went ahead to install all the extensions symfony needs as shown in the `localhost/config.php` 

But,  when I browse `app_dev.php` or `app.php`  I get this error. 
```bash
AnnotationException: You have to enable opcache.save_comments=1 or zend_optimizerplus.save_comments=1
```

I tried to fix this still to no avail. 

Here is the output `php --ini`

```bash
[root@localhost ~]# php --
Configuration File (php.in
Loaded Configuration File:
Scan for additional .ini f
Additional .ini files pars
/etc/php.d/calendar.ini,  
/etc/php.d/ctype.ini,     
/etc/php.d/curl.ini,      
/etc/php.d/dom.ini,       
/etc/php.d/exif.ini,      
/etc/php.d/fileinfo.ini,  
/etc/php.d/ftp.ini,       
/etc/php.d/gd.ini,        
/etc/php.d/gettext.ini,   
/etc/php.d/gmp.ini,       
/etc/php.d/iconv.ini,     
/etc/php.d/intl.ini,      
/etc/php.d/json.ini,      
/etc/php.d/mbstring.ini,  
/etc/php.d/mysqlnd.ini,   
/etc/php.d/mysqlnd_mysqli.
/etc/php.d/opcache.ini,   
/etc/php.d/pdo.ini,       
/etc/php.d/pdo_mysqlnd.ini
/etc/php.d/pdo_pgsql.ini, 
/etc/php.d/pdo_sqlite.ini,
/etc/php.d/pgsql.ini,     
/etc/php.d/phar.ini,      
/etc/php.d/posix.ini,     
/etc/php.d/shmop.ini,     
/etc/php.d/simplexml.ini, 
/etc/php.d/sockets.ini,   
/etc/php.d/sqlite3.ini,   
/etc/php.d/sysvmsg.ini,   
/etc/php.d/sysvsem.ini,   
/etc/php.d/sysvshm.ini,   
/etc/php.d/tokenizer.ini, 
/etc/php.d/xml.ini,       
/etc/php.d/xml_wddx.ini,  
/etc/php.d/xmlreader.ini, 
/etc/php.d/xmlwriter.ini, 
/etc/php.d/xsl.ini,       
/etc/php.d/zip.ini
```
This is my opcache settings 
```bash 
[root@localhost ~]# php -ini | grep opcache                                                     
/etc/php.d/opcache.ini,                                                                         
opcache.blacklist_filename => /etc/php.d/opcache*.blacklist => /etc/php.d/opcache*.blacklist    
opcache.consistency_checks => 0 => 0                                                            
opcache.dups_fix => Off => Off                                                                  
opcache.enable => Off => Off                                                                    
opcache.enable_cli => Off => Off                                                                
opcache.enable_file_override => Off => Off                                                      
opcache.error_log => no value => no value                                                       
opcache.fast_shutdown => 1 => 1                                                                 
opcache.file_update_protection => 2 => 2                                                        
opcache.force_restart_timeout => 180 => 180                                                     
opcache.inherited_hack => On => On                                                              
opcache.interned_strings_buffer => 8 => 8                                                       
opcache.log_verbosity_level => 1 => 1                                                           
opcache.max_accelerated_files => 4000 => 4000                                                   
opcache.max_file_size => 0 => 0                                                                 
opcache.max_wasted_percentage => 5 => 5                                                         
opcache.memory_consumption => 128 => 128                                                        
opcache.optimization_level => 0xFFFFFFFF => 0xFFFFFFFF                                          
opcache.preferred_memory_model => no value => no value                                          
opcache.protect_memory => 0 => 0                                                                
opcache.restrict_api => no value => no value                                                    
opcache.revalidate_freq => 2 => 2                                                               
opcache.revalidate_path => Off => Off                                                           
opcache.save_comments => 0 => 0                                                                 
opcache.use_cwd => On => On                                                                     
opcache.validate_timestamps => On => On                                                         
[root@localhost ~]# php -ini | grep opcache                                                     
/etc/php.d/opcache.ini,                                                                         
opcache.blacklist_filename => /etc/php.d/opcache*.blacklist => /etc/php.d/opcache*.blacklist    
opcache.consistency_checks => 0 => 0                                                            
opcache.dups_fix => Off => Off                                                                  
opcache.enable => Off => Off                                                                    
opcache.enable_cli => Off => Off                                                                
opcache.enable_file_override => Off => Off                                                      
opcache.error_log => no value => no value                                                       
opcache.fast_shutdown => 1 => 1                                                                 
opcache.file_update_protection => 2 => 2                                                        
opcache.force_restart_timeout => 180 => 180                                                     
opcache.inherited_hack => On => On                                                              
opcache.interned_strings_buffer => 8 => 8                                                       
opcache.log_verbosity_level => 1 => 1                                                           
opcache.max_accelerated_files => 4000 => 4000                                                   
opcache.max_file_size => 0 => 0                                                                 
opcache.max_wasted_percentage => 5 => 5                                                         
opcache.memory_consumption => 128 => 128                                                        
opcache.optimization_level => 0xFFFFFFFF => 0xFFFFFFFF                                          
opcache.preferred_memory_model => no value => no value                                          
opcache.protect_memory => 0 => 0                                                                
opcache.restrict_api => no value => no value                                                    
opcache.revalidate_freq => 2 => 2                                                               
opcache.revalidate_path => Off => Off                                                         
opcache.save_comments => 0 => 0                                                                 
opcache.use_cwd => On => On                                                                     
opcache.validate_timestamps => On => On                                                         
```
**ANY** setting change to the above does not seem to have an effect to this error. 

The actual code that is causing this problem is found at 

```bash 
/path/to/try.symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationsReader.php
```
Here is the code (found inside `__construct()`)
```php 
if (extension_loaded('Zend Optimizer+') && (ini_get('zend_optimizerplus.load_comments') === "0" || ini_get('opcache.load_comments') === "0")) {
            throw AnnotationException::optimizerPlusLoadComments();
        }`
````
Using set_ini(); also does not seem to change anything. 

I tried to install symfony one more time, this time using yml instead of annotations for my bundle, but I still get the same error. 

I don't know why this framework is crashing even before a hello world example.

**Comment by iltar** [comment]
Is your webserver using the same PHP.ini as your CLI? Check that because they might differ.

BTW, 2.5 is old and not even support via security updates, I recommend to try again with 2.7.

**Comment by stof** [comment]
Such setting indeed cannot be changed efficiently with ``ini_set``. It should be changed in the php.ini.
And even if you use annotations in your own bundle, annotation-based features are still enabled by default in the SE. So you need a working setup.

On a side note, ``composer create-project symfony/framework-standard-edition`` is not the recommended way to create new projects anymore.

**Comment by stof** [comment]
hmm, I just spotted the fact that you said you use PHP 7. This ini setting does not exist anymore in PHP 7 actually (well, you can read it but it has no effect anymore and the value being read does not actually reflect the actual behavior). The doctrine/annotations library was fixed to handle this in 1.2.6, but the lock file of the symfony-standard repo in the 2.5 branch contains 1.2.3 for this library, precisely because it is not maintained anymore and so has not been updated after the fix (and Symfony fixes for PHP 7 compatibility have not been merged in 2.5 either btw).
So @iltar is right: you should use the current version

**Comment by samayo** [comment]
@stof && @iltar  Ok, I will use the current version and update you, I am using the `symfony new project` command, as there are no alternatives to using `composer create-project symfony/framework-standard-edition` that I know of.

**Comment by stof** [comment]
@samayo ``symfony new`` is precisely the alternative (no, it is **not** a proxy to ``composer create-project symfony/framework-standard-edition``)

**Comment by samayo** [comment]
Ok, another day, another symfony issue.. 

I installed it again using `symfony new project` and all the deps and here is the [error I get](blob:http://pasteboard.co/2a73dffd-a85c-43ed-acad-7f2c32516e73) Yes, I have enabled the debugger while generating a bundle. If I press `cancel` nothing happens, If I chose ok though, I get redirected `http://try.symfony/_profiler/568a3e` and shown `404` page.  The same thing happens if I go to `http://try.symfony/app_dev.php/hello` I get 404 Nginx page, as opposed to a symfony error page (since route is not defined) This has to be a symfony issue, as I have redirects enabled in nginx.

**Comment by WouterJ** [comment]
If you get a 404 error page of Nginx, it's a Nginx error.

**Comment by javiereguiluz** [comment]
@samayo please check if your Nginx config is the same as recommended in http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx

**Comment by samayo** [comment]
I am using this nginx setting. 

```php 
server{
    server_name                 try.symfony;
    root                        /var/www/sites/try.symfony/web/;
        
    location / {
        try_files $uri /app.php$is_args$args;
    }

    location ~ \.php$ {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
    error_page    404   /home/simon/www/errors/404.html;
    fastcgi_intercept_errors on;
   }
}
```
I tried replacing 
```bash
try_files $uri /app.php$is_args$args;
```
with 
```bash
try_files $uri /app_dev.php$is_args$args;
```
or just 
```bash 
try_files $uri $uri/ /app_dev.php?$query_string;
```

Still a 404 error. 

This did not happen, when I tried laravel, I installed them both .. it's only symfony issue

**Comment by samayo** [comment]
Ok, I'm closing the issue, for the late commers the fix was: 

1 - not to use `symfony2.5.*` with `php7`
2 - use the official symfony's nginx (server block) config  http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx 
But, if you are using TCP ports instead of the unix socket, then change the fastcgi_pass to `fastcgi_pass   127.0.0.1:9000;`

thanks @javiereguiluz  and others.

**Comment by blue928** [comment]
Earlier @stof mentioned that composer create-project is no longer the preferred way to create a new symfony project.

Lynda.com's only tutorial for Symfony references Symfony 2.5, and indeed the OPs question is the exact command from that tutorial. So, I'm sure that, like me as well, this is going to bring a lot of people to this page who are brand new Symfony who only have that tutorial to rely on.

Extending @stof 's comment a bit, here is the current page that touches this change:

http://symfony.com/doc/current/best_practices/creating-the-project.html

And here is the link to the explain in more detail the new setup process.

http://symfony.com/doc/current/setup.html

Sorry it's a bit off topic, but hopefully this will save a lot of headaches.
