### ISSUE TITLE
YAML: Support binary data

### ISSUE THREAD

**Issue by clever-systems** [symfony/symfony#15587]
I want to emit objects that contain binary data properties. I could not figure out if this is possible yet.

The Yaml 1.2 spec mentions binary as valid tag:
http://www.yaml.org/spec/1.2/spec.html#id2761292

There is a former issue #8094 that i did not grok.

**Comment by stof** [comment]
We indeed do not support the binary data

**Comment by xabbuh** [comment]
refs #15958

**Comment by xabbuh** [comment]
@fabpot Was there a reason to close? The pull request is still open.

**Comment by xabbuh** [comment]
see #17599 for an attempt to implement this
