### ISSUE TITLE
Handle booting problems gracefully

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#15581]
Some bundles, like JMSPaymentCoreBundle, [call the database in their boot method](https://github.com/schmittjoh/JMSPaymentCoreBundle/blob/master/JMSPaymentCoreBundle.php#L36). If the database is down, this results in an exception, which is not handled properly: I get a blank page on a symfony 2.3 site instead of the beautiful page our designer created for 500 errors. Is there a solution to that or is it too early in the execution process for symfony to register the error handler ?

**Comment by stof** [comment]
it is too early in the process to have the customized error page (which is handled by a controller and so requires a booted kernel).
In 2.6+, you would still get the Symfony basic error page in such case, assuming FrameworkBundle is registered before other bundles in the kernel (so that it boots before other bundles as the basic exception handler is registered when booting FrameworkBundle)

**Comment by stof** [comment]
btw, registering the custom type should not be done in the boot method but by adding it in the configuration of DoctrineBundle, to keep it done lazily (this can be achieved using a PrependExtension to inject stuff in the DoctrineBundle config, or through a compiler pass modifying the Doctrine config). This would avoid using the DBAL connection on boot.

**Comment by greg0ire** [comment]
Thanks for the detailed answers. I'm stuck in 2.3, so for the moment, we are considering wrapping part of `app.php` in a `try` `catch` block that will allow us to display a custom error page, but we feel there should be a better solution.

**Comment by greg0ire** [comment]
I'll try to have the PaymentCoreBundle fixed with your solution though (or even make a PR if I find some time to do so).

**Comment by greg0ire** [comment]
@stof : I managed to extract the type registration in a compiler pass as you advised, but I can't seem to be able to extract the part that marks where the type is marked as commented.

I guess that must be because it requires access to a service (`doctrine.dbal.default_connection`) and I am still building the container at the moment. 

How about keeping this code block in the `boot()` method, and wrap it in a try catch block so that it does not fail at boot, but later, when the customized error page is available ?

**Comment by stof** [comment]
@greg0ire the right way to handle it is to mark the type as commented in the Type class itself, as DBAL supports this natively since 2.3: https://github.com/doctrine/dbal/blob/bfe166af1e52b85f1101db19f3437ae87a7e291b/lib/Doctrine/DBAL/Types/Type.php#L329-L342

**Comment by stof** [comment]
and if you don't do it this way (for whatever weird reason), you should hook into the DoctrineBundle logic initializing commented types: https://github.com/doctrine/DoctrineBundle/blob/9d64747db385f26c223dafc52e9ce79c6510a5a3/ConnectionFactory.php

**Comment by stof** [comment]
> How about keeping this code block in the boot() method, and wrap it in a try catch block so that it does not fail at boot, but later, when the customized error page is available ?

that's not good, because it breaks the lazy-loading of the connection

**Comment by greg0ire** [comment]
Thanks a lot for the a lot for the tips, I shall try that this week-end.

**Comment by greg0ire** [comment]
@fabpot : should this really be closed ? Since I am stuck in 2.3, I still have no other solution than a try / catch in my front controller. And I believe the issue must hit 2.6+ if the framework bundle is not registered first.
