### ISSUE TITLE
Issues with the new "readline" support for QuestionHelper

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#15583]
Symfony added "readline" support for console in #15382. The feature works OK when using the arrow keys, but it suffers some issues:

1) It doesn't limit the arrow keys movement:

![console_readline_3](https://cloud.githubusercontent.com/assets/73419/9403454/a309f330-47e7-11e5-9bbd-53864addc996.gif)

2) If you delete or type new characters after arrow key movements, this happens:

![console_readline](https://cloud.githubusercontent.com/assets/73419/9403469/b5f7d020-47e7-11e5-8e7d-e2962d5baebb.gif)

![console_readline_2](https://cloud.githubusercontent.com/assets/73419/9403474/b9573896-47e7-11e5-910b-c4e7845f1936.gif)

------

This is the test script that I used with `symfony/console 2.8.x@dev`:

```php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$helper = new QuestionHelper();
$question = new Question('Enter the name of the bundle: ', '');
$bundle = $helper->ask(new ArgvInput(), new ConsoleOutput(), $question);
```

My `readline` configuration:

![php_readline](https://cloud.githubusercontent.com/assets/73419/9403490/e159cd0e-47e7-11e5-8476-bb09138040fc.png)

**Comment by jrobeson** [comment]
did you have the Insert key pressed at the time?

**Comment by javiereguiluz** [comment]
Not at the same time. I only press one key at a time.

**Comment by jrobeson** [comment]
not at the exact same time.. i meant like caps lock. the 2nd example looks like insert was enabled.

**Comment by javiereguiluz** [comment]
I don't have an insert key in my keyboard. In the examples I only pressed <kbd>→</kbd> <kbd>←</kbd> <kbd>Backspace</kbd> and the regular letters.

**Comment by mvhirsch** [comment]
I can reproduce the first bug on my fedora machine with php 5.6.13, but I can't reproduce the second one.

**Comment by OskarStark** [comment]
I can reproduce the first bug on my osx el capitain with php 5.5.29

the second example works on my machine

**Comment by WouterJ** [comment]
On a vagrant box with PHP 7 and readline 6.3, I am able to reproduce both issues.

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by javiereguiluz** [comment]
Thank you all for verifying this bug. In my opinion, this bug is so important that if nobody offers to solve it, we should revert this feature as soon as possible.

**Comment by jaytaph** [comment]
The problem seems that readline doesn't take into account the actual column it started. The question itself isn't printed by `readline()`, so it assumes it started on column 0..  you can see this behaviour in action by specifying `readline('foobar');` in `QuestionHelper.php`, that way, you shouldn't be able to return before the 6th column, (even `ctrl`-`a` would nicely go back to the 6th column).

I haven't looked into the actual readline from php itself, but unless there is a way to tell readline to use the current column-offset as its start, the quickest solution would be to add an addition newline before reading, or to print the actual question through the `readline()` function instead.

**Comment by jaytaph** [comment]
This works, although it's probably not the nicest solution:

https://gist.github.com/jaytaph/9a331f4ff6a116e7dc9e

**Comment by OskarStark** [comment]
indeed, looks like an offset problem...

@jaytaph could you please provide a PR with your fix?

That would be great :+1:

**Comment by jaytaph** [comment]
@OskarStark Created PR #16458

**Comment by OskarStark** [comment]
:+1:  thank you @jaytaph
