### ISSUE TITLE
[DX] Null Object pattern for 'LoggerInterface $logger'

### ISSUE THREAD

**Issue by AlexDpy** [symfony/symfony#15594]
I noticed that most of the time in Symfony, when a LoggerInterface is injected into a service and when it can be null, we do not use the null-object pattern.

Psr\Log has a NullLogger that can be used in this case. It says :
```php
/**
 * This Logger can be used to avoid conditional log calls
 *
 * Logging should always be optional, and if no logger is provided to your
 * library creating a NullLogger instance to have something to throw logs at
 * is a good way to avoid littering your code with `if ($this->logger) { }`
 * blocks.
 */
```

https://github.com/php-fig/log/blob/master/Psr/Log/NullLogger.php

If found 60 occurences of "if (null !== $this->logger)" in Symfony. Many of these could be avoided and the code could be clearer.

Before:
```php
    protected $logger;

    public function __construct(LoggerInterface $logger = null)
    {
        $this->logger = $logger;
    }

    public function foo()
    {
        if (null !== $this->logger) {
            $this->logger->info('foo');
        }
    }
    
    public function bar()
    {
        if (null !== $this->logger) {
            $this->logger->info('bar');
        }
    }
```

After:
```php
    protected $logger;

    public function __construct(LoggerInterface $logger = null)
    {
        $this->logger = null === $logger ? new NullLogger() : $logger;
    }

    public function foo()
    {
        $this->logger->info('foo');
    }
    
    public function bar()
    {
        $this->logger->info('bar');
    }
```

If you think it's a good idea, i can provide a PR.

**Comment by dosten** [comment]
This idea was proposed in a comment, but rejected for performance reasons.

**Comment by javiereguiluz** [comment]
@dosten I don't think that performance degrades too much by using this pattern. I've added a comment in the related PR to ask Symfony deciders to reconsider it.

**Comment by iltar** [comment]
I would recommend the following syntax:
```php
$this->logger = $logger ?: new NullLogger();
```

**Comment by nicolas-grekas** [comment]
I don't think this should be labelled DX at all: DX does not apply to the internal implementation, only to the interface we provide.
:-1: here: our internal implementation has to be as fast as possible. We don't know how people use our code.

**Comment by fabpot** [comment]
As it does not bring any "value", I'm closing this ticket.

**Comment by pilot911** [comment]
using null object is good solution... strange last comment from fabpot
