### ISSUE TITLE
[2.7] Entity Form Element

### ISSUE THREAD

**Issue by Thibautg16** [symfony/symfony#15607]
Hello guys,

Since 2.7 using Entity Form Elements, I have this error : 
The option "choice_name" with value array is expected to be of type "null" or "callable" or "string" or "Symfony\Component\PropertyAccess\PropertyPath", but is of type "array". 

My Controller : 
```php
// On ajoute les champs de l'entité que l'on veut à notre formulaire
$formBuilder
    ->add('nom',         'text')
    ->add('telecharge', 'entity', ['class' => 'SsiLicenceBundle:Telecharge', 'property' => 'nom'])
    ->add('Ajouter', 'submit');

// À partir du formBuilder, on génère le formulaire
$form = $formBuilder->getForm();
```
Prior to Symfony 2.7.0 everything works fine, including 2.6.11.

I need to change my FormBuilder or this is a bug?

Cordially,
@Thibautg16

**Comment by stof** [comment]
which PHP version are you using ?

**Comment by stof** [comment]
Note that the entity type is indeed broken in 2.7+ when using PHP 7.0-beta2 because of a bug in this PHP version (which has been fixed in beta3): https://3v4l.org/YUar6

**Comment by Thibautg16** [comment]
Hi,

It's with php7-nightly (Build Date 	Jul 21 2015 19:08:01).

I have update php7-nightly : 
# apt-get install php7-nightly
# cp /usr/local/php7/libphp7.so /usr/lib/apache2/modules/
# cp /usr/local/php7/php7.load /etc/apache2/mods-available/

Now it's : 
php7-nightly (Build Date 	Aug 28 2015 19:10:25 )

And is works fine, thanks for your help.

Cordially,
@Thibautg16
