### ISSUE TITLE
BrowserKit: Post data with fields using the same name?

### ISSUE THREAD

**Issue by georaldc** [symfony/symfony#15605]
Is it possible to submit form data with fields that use the same name? I'm trying to do file uploads on a form that reuses the same file field name multiple times for multiple uploads (not as an array) but BrowserKit's ```Client::submit()``` method only accepts an array for field values so re-using the same key would not work.

I unfortunately do not have control over the remote form source but was tasked by my superiors to come up with a solution to push data to it. I'm guessing the re-use of field names means that it does not use PHP to handle uploads.

**Comment by jakzal** [comment]
Is this even possible with a real browser? Could you give an example of such a form please?

**Comment by stof** [comment]
@jakzal it is possible with a browser, as the browser does not build an associative array for submitted data. the following data is valid:

```
field=value1&field=value2&field=value3
```

Such submitted data would not be handled properly by any system which parses the request body into an associative array though, as it would overwrite the key for subsequent values. and the PHP parsing of submitted data works this way (it is not the only language doing that btw). this is exactly why we use ``field[]`` for multiple selects as PHP will parse this as appending values (to represent the parsing logic, you could imagine that you replace any ``&`` by a semicolon to make separate statements and that you put ``$`` at the beginning of each statement to have valid variable names. and then look at the available variables).

@georaldc Given that BrowserKit also relies on an associative array to represent the data it will submit, it does not support this case.

**Comment by georaldc** [comment]
@stof Thanks, I thought that would be the case.

Anyway, I kind of figured out a way around this for now. I was using Goutte and because it using browserkit meant this would not work, I just used its underlying guzzle client to push out uploads through a normal multipart request, which allows you to reuse the same name key multiple times. This issue can be closed now for me.
