### ISSUE TITLE
Transient tests hunting

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15617]
Let's link travis/appveyor failures to this issue, and fix tests volatility.

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\Process\Tests\SimpleProcessTest::testMethodsThatNeedATerminatedProcess with data set #2 ('hasBeenStopped')
Symfony\Component\Process\Exception\RuntimeException: Unable to kill the process

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testAssignsDefaultTtlWhenResponseHasNoFreshnessInformationAndAfterTtlWasExpiredWithStatus304
Failed asserting that true is false.
 
C:\projects\symfony\src\Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTestCase.php:72
C:\projects\symfony\src\Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest.php:676

**Comment by EmanueleMinotto** [comment]
Don't know if it's related but using PHP 5.5.24 I have:

```
1) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testHitsCachedResponsesWithExpiresHeader
Failed asserting that false is true.

Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:509

2) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testHitsCachedResponseWithMaxAgeDirective
Failed asserting that false is true.

Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:533

3) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testHitsCachedResponseWithSMaxAgeDirective
Failed asserting that false is true.

Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:557

4) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testAssignsDefaultTtlWhenResponseHasNoFreshnessInformationAndAfterTtlWasExpired
Failed asserting that false is true.

Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTestCase.php:67
Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:617

5) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testAssignsDefaultTtlWhenResponseHasNoFreshnessInformationAndAfterTtlWasExpiredWithStatus304
Failed asserting that false is true.

Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTestCase.php:67
Development/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:666
```

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\Process\Tests\SigchildDisabledProcessTest::testCheckTimeoutOnStartedProcess
Failed asserting that exception message 'The process "c:\php\php.EXE -r "sleep(3);"" exceeded the timeout of 0.5 seconds.' contains 'This PHP has been compiled with --enable-sigchild. You must use setEnhanceSigchildCompatibility() to use this method.'.

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testFetchesFullResponseWhenCacheStaleAndNoValidatorsPresent
Failed asserting that false is true.
 
C:\projects\symfony\src\Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest.php:729

**Comment by stof** [comment]
@nicolas-grekas the first test seems like a wrong detection of the sigchild mode in the testsuite, or a wrongly overwritten test in case of sigchild.

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpFoundation\Tests\Session\Storage\MetadataBagTest::testDoesNotSkipLastUsedUpdate

Failed asserting that 1442561602 matches expected 1442561601.

/home/travis/build/symfony/symfony/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/MetadataBagTest.php:132

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testAssignsDefaultTtlWhenResponseHasNoFreshnessInformation

Failed asserting that 'public, s-maxage=11' matches PCRE pattern "/s-maxage=10/".

/home/travis/build/symfony/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:574

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpFoundation\Tests\Session\Storage\Proxy\AbstractProxyTest::testIsActive

ps_files_cleanup_dir: opendir(/var/lib/php5) failed: Permission denied (13)

/home/travis/build/symfony/symfony/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:40

/home/travis/build/symfony/symfony/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/AbstractProxyTest.php:95

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\Process\Tests\SigchildDisabledProcessTest::testSetStreamAsInput with data set #6 ('fwrite(STDOUT, $in = file_get... $in);', 1024)

Symfony\Component\Process\Exception\ProcessTimedOutException: The process "/usr/bin/hhvm --php -r 'fwrite(STDOUT, $in = file_get_contents('\''php://stdin'\'')); fwrite(STDERR, $in);'" exceeded the timeout of 5 seconds.

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:1226

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:356

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:210

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/AbstractProcessTest.php:187

**Comment by mpdude** [comment]
1) Symfony\Component\Process\Tests\SimpleProcessTest::testStopTerminatesProcessCleanly
A call to stop() is not expected to cause wait() to throw a RuntimeException
 
C:\projects\symfony\src\Symfony\Component\Process\Tests\SimpleProcessTest.php:158
 
Failed test [here](https://ci.appveyor.com/project/fabpot/symfony/build/1.0.850/job/rhxs717ghjh1ks8v)

**Comment by nicolas-grekas** [comment]
https://travis-ci.org/symfony/symfony/jobs/82110390#L864

1) Symfony\Component\Process\Tests\SigchildDisabledProcessTest::testIdleTimeoutNotExceededWhenOutputIsSent

A general timeout is expected.

Failed asserting that false is true.

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/AbstractProcessTest.php:863

**Comment by nicolas-grekas** [comment]
https://travis-ci.org/symfony/symfony/jobs/82623663#L755

1) Symfony\Component\Process\Tests\SimpleProcessTest::testSignal

Failed asserting that null matches expected 'Caught SIGUSR1'.

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/AbstractProcessTest.php:784

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/SimpleProcessTest.php:103

**Comment by nicolas-grekas** [comment]
https://travis-ci.org/symfony/symfony/jobs/82708583#L746

1) Symfony\Component\HttpFoundation\Tests\Session\Storage\Proxy\AbstractProxyTest::testIsActivePhp54

ps_files_cleanup_dir: opendir(/var/lib/hhvm/sessions) failed: Permission denied (13)

/home/travis/build/symfony/symfony/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:40

/home/travis/build/symfony/symfony/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/AbstractProxyTest.php:108

**Comment by nicolas-grekas** [comment]
https://ci.appveyor.com/project/fabpot/symfony/build/1.0.2254

There were 2 errors:
 
1) Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testFlash with data set #0 ('config.yml', true)
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "c:\php\php.EXE" exceeded the timeout of 60 seconds.
 
C:\projects\symfony\src\Symfony\Component\Process\Process.php:1204
C:\projects\symfony\src\Symfony\Component\Process\Process.php:350
C:\projects\symfony\src\Symfony\Component\Process\Process.php:204
C:\projects\symfony\src\Symfony\Component\BrowserKit\Client.php:332
C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Client.php:143
C:\projects\symfony\src\Symfony\Component\BrowserKit\Client.php:295
C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest.php:68
 
2) Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testTwoClients with data set #0 ('config.yml', true)
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "c:\php\php.EXE" exceeded the timeout of 60 seconds.
 
C:\projects\symfony\src\Symfony\Component\Process\Process.php:1204
C:\projects\symfony\src\Symfony\Component\Process\Process.php:350
C:\projects\symfony\src\Symfony\Component\Process\Process.php:204
C:\projects\symfony\src\Symfony\Component\BrowserKit\Client.php:332
C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Client.php:143
C:\projects\symfony\src\Symfony\Component\BrowserKit\Client.php:295
C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest.php:97

**Comment by nicolas-grekas** [comment]
https://travis-ci.org/symfony/symfony/jobs/84900056

1) Symfony\Component\HttpFoundation\Tests\ResponseTest::testGetDate

->getDate() returns the current Date if no Date header present

Failed asserting that '1' is less than 1.

/home/travis/build/symfony/symfony/src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:266

**Comment by nicolas-grekas** [comment]
https://travis-ci.org/symfony/symfony/jobs/87044092#L1064

1) Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens with data set #0 ('config.yml')
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "/usr/bin/hhvm --php" exceeded the timeout of 60 seconds.

/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:1204
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:350
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:204
/home/travis/build/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:352
/home/travis/build/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:143
/home/travis/build/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:315
/home/travis/build/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Tests/Functional/CsrfFormLoginTest.php:24

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\Process\Tests\ProcessTest::testZeroAsOutput
Failed asserting that null is identical to '0'.
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/ProcessTest.php:465

**Comment by nicolas-grekas** [comment]
PHP --enable-sigchild enhanced=1
1) Symfony\Component\Process\Tests\ProcessTest::testCallbacksAreExecutedWithStart
Failed asserting that null is identical to 'foo
'.
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/ProcessTest.php:147

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\Process\Tests\ProcessTest::testSetStreamAsInput with data set #6 ('fwrite(STDOUT, $in = file_get... $in);', 1024)
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "exec /usr/bin/hhvm --php -r 'fwrite(STDOUT, $in = file_get_contents('\''php://stdin'\'')); fwrite(STDERR, $in);'" exceeded the timeout of 5 seconds.
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:1150
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:364
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Process.php:203
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/ProcessTest.php:198

**Comment by nicolas-grekas** [comment]
With PHP 5.5
1) Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testAssignsDefaultTtlWhenResponseHasNoFreshnessInformationAndAfterTtlWasExpiredWithStatus304
Failed asserting that 'public, s-maxage=3' matches PCRE pattern "/s-maxage=2/".
/home/travis/build/symfony/symfony/src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php:650

**Comment by xabbuh** [comment]
[Symfony\Component\Process\Tests\ProcessTest::testGetIncrementalErrorOutput](https://travis-ci.org/symfony/symfony/jobs/106300979#L2373)
[Symfony\Component\Process\Tests\ProcessTest::testGetEmptyIncrementalOutput](https://travis-ci.org/symfony/symfony/jobs/106299621#L2270)

**Comment by nicolas-grekas** [comment]
1) Symfony\Component\HttpFoundation\Tests\RequestTest::testVeryLongHosts with data set #0 ('a.a.a.a.a.a.a.a.a.a.a.a.a.a.a....a.a.a')
Failed asserting that 2.6036610603333 is less than 1.
 
C:\projects\symfony\src\Symfony\Component\HttpFoundation\Tests\RequestTest.php:1790

**Comment by nicolas-grekas** [comment]
1) Symfony\Bundle\SecurityBundle\Tests\Functional\AuthenticationCommencingTest::testAuthenticationIsCommencingIfAccessDeniedExceptionIsWrapped
RuntimeException: Unable to create the cache directory (/tmp/3.1.0-DEV/StandardFormLogin/cache/securitybundleteststandardformlogin)
/home/travis/build/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:552
/home/travis/build/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:476
/home/travis/build/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:117
/home/travis/build/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:146
/home/travis/build/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php:33
/home/travis/build/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Tests/Functional/AuthenticationCommencingTest.php:18

**Comment by xabbuh** [comment]
```
1) Symfony\Component\Console\Tests\Helper\ProgressIndicatorTest::testDefaultIndicator
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
  - Starting...
- \ Starting...
+ - Advancing...
  \ Advancing...
- | Advancing...
- | Done...     
+ \ Done...     
  - Starting Again...
  \ Starting Again...
  \ Done Again...    
 '
 
C:\projects\symfony\src\Symfony\Component\Console\Tests\Helper\ProgressIndicatorTest.php:51
```

https://ci.appveyor.com/project/fabpot/symfony/build/1.0.7036#L964

**Comment by xabbuh** [comment]
Ah, looks like that test simply always fails on Windows.

**Comment by nicolas-grekas** [comment]
Happy to close this one eventually :)
