### ISSUE TITLE
Symfony 2.8 autodelete from vendor

### ISSUE THREAD

**Issue by gperdomor** [symfony/symfony#15618]
I don't know why, but i update mi composer.json to use symfony 2.8 and disappears from time to time in the folder vendor, having to run composer install/update again and again...

This happen in linux and osx, i don't test in windows

**Comment by dosten** [comment]
This is the wrong place, you should create an isue in the Composer repo.

**Comment by javiereguiluz** [comment]
@gperdomor the issue you are describing is really strange. I've been using 2.8-dev version for a long time and it doesn't happen to me. Maybe you can ask for support using any of the alternatives explained here: symfony.com/support

**Comment by disquedur** [comment]
It happened 2 or 3 time to me, using Windows and Cgwin. But I did not succeed to reproduce.

**Comment by gperdomor** [comment]
@javiereguiluz @disquedur @dosten i create the issue in the composer repository, if you can help to find why this happen, this is the link https://github.com/composer/composer/issues/4377
