### ISSUE TITLE
symfony2 demo app slow twig rendering in amazon ec2

### ISSUE THREAD

**Issue by anooxy** [symfony/symfony#15610]
I've been fighting with AWS for so long now, I can't find what's the issue.

I have set up two symfony demo apps at EC2 and MediaTemple respectively:

http://sampleaws.skooli.com
http://sampledev.skooli.com

Even in the demo app, when you run via app_dev you can see in the profiler that twig takes longer than usual at EC2. The EC2 instance is m3,large which is quite powerful for this task and MediaTemple plan is DV Developer Level 2. I initially thought the SSD I had was slow so I buffed it up to 150GB and it has 450IOPS. Is there any specific requirement for faster Twig loading?

This problem stemmed from the application I have built, which due to higher usage of db resources and bigger twig files, the difference is quite bigger.

See https://test.skooli.com (EC2) and https://dev.skooli.me (MediaTemple, mind the ssl key)

How can I pinpoint the exact problem?

**Comment by javiereguiluz** [comment]
@anooxy I recommend you to remove the `app_dev.php` controllers from the servers you linked. Even if this is a test, anyone can see the bundles of your application, the database queries performed to render the page, the configured routes, etc.

By the way, even if in both cases the time took by the database queries is roughly the same, in the slow server they are much more separated in time. Therefore, the total query + waiting time in the slow server is much longer. If you need more help, please consider using these Symfony support options: http://symfony.com/support

**Comment by javiereguiluz** [comment]
@anooxy I recommend you to remove the `app_dev.php` controllers from the servers you linked. Even if this is a test, anyone can see the bundles of your application, the database queries performed to render the page, the configured routes, etc.

By the way, even if in both cases the time took by the database queries is roughly the same, in the slow server they are much more separated in time. Therefore, the total query + waiting time in the slow server is much longer. If you need more help, please consider using these Symfony support options: http://symfony.com/support
