### ISSUE TITLE
[EventDispatcher] - removeListeners($eventName) ?

### ISSUE THREAD

**Issue by bkdotcom** [symfony/symfony#15628]
Feature request... 
it would be nice to have a "removeListener**s**" method or, make the 2nd parameter optional on `removeListener()`

currently:  if I want to remove every listener for an event I must

    $listeners = getListeners($eventname)
    foreach ($listeners as $listener) {
        removeListener($eventName, $listener);
    }

or extend EventDispatcher

seems quite inefficient compared to
`unset($this->listeners[$eventName]);`

**Comment by stof** [comment]
What is your use case for removing all listeners on an event ? I never had to do such thing

**Comment by jakzal** [comment]
ping @bkdotcom. What's your use case?

**Comment by bkdotcom** [comment]
sorry, I was certain I commented re my use case...

nuthshell:  I have a method that walks a array/object structure..   as it walks the structure it may add listeners that will be dispatched when the walker walks the the "node's" descendants
(Ie, this callback applies to this node and all descendants... etc)

When walking a new structure I would like to clear all the "structure walking" listeners and start with a clean slate...   A new EventDispatcher instance *could* be used each time but that has its own set of issues

**Comment by stof** [comment]
I think the right solution for your use case would be to use a new EventDispatcher instance. Reusing the same instance could lead to the assumption that attaching listeners before using your service would work (while they would get removed). It also means that listeners would not be allowed to reuse your traverser service inside themselves (on another data) as this would affect the next steps of the tree traversing for the main tree.
