### ISSUE TITLE
Help for fixing tests on Windows for 2.7

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15622]
Now that we run our tests on Windows, [we can see many failures on the 2.7 branch](https://ci.appveyor.com/project/fabpot/symfony/build/1.0.267). I'm calling for help for fixing them. Here is the list of components that have failures. PRs welcomed!

- [x] src/Symfony/Bridge/Twig
- [x] src/Symfony/Bundle/FrameworkBundle
- [x] src/Symfony/Bundle/SecurityBundle
- [x] src/Symfony/Component/Config
- [x] src/Symfony/Component/Console
- [x] src/Symfony/Component/Filesystem
- [x] src/Symfony/Component/Form
- [x] src/Symfony/Component/HttpFoundation
- [x] src/Symfony/Component/Locale
- [x] src/Symfony/Component/Process

**Comment by stof** [comment]
for the Twig bridge, this is easy: it is just a DIRECTORY_SEPARATOR mismatch between the expectation and the actual output
This is similar in FrameworkBundle.

for the UserPasswordEncoderCommandTest and the SymfonyStyleTest, I think we should just force the terminal width in the test to be sure the message does not get wrapped. The way the terminal width is detected on windows might give small values on AppVeyor.

for the FilesystemTest, this looks like a bug in the code of the test itself.

for the NumberToLocalizedStringTransformerTest, this looks weird. It is as if the Intl data were not respecting the expected config.

HttpFoundation should not be in the list as there is no failure. Marking it as resolved

**Comment by nicolas-grekas** [comment]
HttpFoundation fails on the PHP_EXT=0 job, this is also easilly resolved by using an explicit content type (already done for other tests)
