### ISSUE TITLE
[Process] Output is cut by height

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#15626]
I'm trying to run the `/usr/bin/mcedit` through the `Process` component by providing STDIN to it. Problem is, that opened editor window isn't at 100% for reasons unknown to me. If I try to use VIM instead it looks even worse.

Opened via Process:
![mcedit_via_process](https://cloud.githubusercontent.com/assets/1277526/9503271/942a3db0-4c3e-11e5-9280-8330b76e88f3.png)

Opened directly:
![mcedit_directly](https://cloud.githubusercontent.com/assets/1277526/9503297/b945710a-4c3e-11e5-93bf-4154e6fc5048.png)

Example PHP code (works):

```php
$spec  = array(STDIN, STDOUT, STDERR);
$pipes = array();
$cwd = getcwd();
$env = null;
$options = array();

$proc = proc_open(
	'/usr/bin/mcedit',
	$spec,
	$pipes,
	$cwd,
	$env,
	$options
);
$err = proc_close($proc);
```

Example PHP code (doesn't work):

```php
$process = new \Symfony\Component\Process\Process('/usr/bin/mcedit', null, null, STDIN, null);
$process->run(function ($type, $buffer) {
	if ( $type == \Symfony\Component\Process\Process::OUT ) {
		fwrite(STDOUT, $buffer);
	}
	else {
		fwrite(STDERR, $buffer);
	}
});
```

The `proc_open` call done in both examples are identical, so this might be something happening in a way how pipes are being handled to allow for real-time output capturing of the process.

Maybe mcedit is sending some coloring codes and somehow they are split across separate callback calls, that outputs them which makes them behave differently.

**Comment by aik099** [comment]
I've created https://gist.github.com/aik099/3a339181ac6985ebd1d0 gist where I've captured what comes in to output callback compared to what comes in to real STDOUT when Symfony Process isn't used.

Looks like /usr/bin/mcedit really thinks that Terminal window is smaller, when being executed by Symfony Process, because it sends different symbols to create editor (less tabs, less lines in editor).

**Comment by javiereguiluz** [comment]
@aik099 did you manage to find a solution for the described issue? If not, could you try playing with `$process->setTty(true);` or `$process->setPty(true);` method to see if you notice any difference? Thanks!

**Comment by aik099** [comment]
> `$process->setPty(true);`

This had no effect.

> `$process->setTty(true);`

This immediately helped. Thanks. But I have no idea why.

**Comment by aik099** [comment]
The only thing different when tty is set is this: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L298

**Comment by nicolas-grekas** [comment]
this is "normal" behavior: the width/height of a terminal is something that doesn't mean anything unless you use a tty stream, which is exactly what this `setTty` function enables.

**Comment by aik099** [comment]
But why does it prevent the output callback of a process from being called?
