### ISSUE TITLE
Symfony 2.3.31 kernel.debug integer instead of boolean

### ISSUE THREAD

**Issue by fpapadopou** [symfony/symfony#15633]
Hi! I'm trying to upgrade Symfony to version 2.3.31 (PHP 5.5.26), using *composer require*.
During the post-update *cache:clear* command execution I get the following exception

``` ShellSession
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]
Invalid type for path "twig.debug". Expected boolean, but got integer.
```

It looks like *kernel.debug* value is set to (int) 1 instead of (bool) true.

After a little browsing of the code I found out that the *configs* parameter provided to the TwigExtension *load* function looks like this:

``` php
array(2) {
  [0]=>
  array(3) {
    ["debug"]=>
    bool(true)
    ["strict_variables"]=>
    bool(true)
    ["globals"]=>
    array(22) {
      ... more custom values ...
    }
  }
  [1]=>
  array(1) {
    ["debug"]=>
    int(1)
  }
}
```
I guess composer tries to clear the cache with debug set to true, but it's already passed to the Twig config array. Should this "extra" debug field be there?

**Comment by stof** [comment]
Well, can you show your config files which contain configuration for Twig ?

**Comment by fpapadopou** [comment]
@stof  you were absolutely right. There was a double definition of the twig debug option in `config.yml` and `config_dev.yml`. However, it did work fine with versions up to 2.3.30 and started producing this error with version 2.3.31. 
Anyway, I'm closing the issue. Thanks a lot for the help!

**Comment by stof** [comment]
@fpapadopou in older 2.3 versions, we were less strict about the validation of the fact that Twig expects a boolean there, and so integers were accepted (invalid stuff were also accepted in other places in the Twig config where it would put Twig in an invalid state, which is why we added more validation)

**Comment by fpapadopou** [comment]
Well, that makes sense! Good to know. 
Thanks again
