### ISSUE TITLE
[Form][2.7] Choices groups with empty array fire 500 internal server error

### ISSUE THREAD

**Issue by falinsky** [symfony/symfony#15634]
Trying add an entity Field Type with choices like next throw ContextErrorException:

```php
'choices' => array(
   'first group' => array($object1, $object2),
   'empty group' => array(),
   'second group' => array($object3, $object4)
)
```

```
Notice: Undefined index:

in vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php at line 203 
```

**Comment by craue** [comment]
I noticed this as well while upgrading a project from Symfony 2.6 to 2.7. It didn't happen in 2.6.

**Comment by velikanov** [comment]
@falinsky, @craue, @aitboudad what's the correct behaviour?
do we need to show an empty optgroup or not to show it at all?

**Comment by aitboudad** [comment]
IMO it should be ignored (I made a quick fix #15662).

**Comment by falinsky** [comment]
@velikanov I think we should show an empty optgroup as was before.

**Comment by velikanov** [comment]
@falinsky I think that we should just ignore this optgroup…
but you have a point

and for the good, customisable way we need some kind of flag which allows us to show/hide the empty optgroups

**Comment by falinsky** [comment]
@velikanov It'd be great

**Comment by craue** [comment]
In Symfony 2.6.11, empty groups weren't rendered at all. So the patch is fine.
