### ISSUE TITLE
Use translator on error page

### ISSUE THREAD

**Issue by ghostika** [symfony/symfony#15638]
Hello,

I have a customized error page, what I want to translate for multiple language and in dev mode everything is ok, but in prod, it's simply doesn't work. Every other page is translated, only the error page not.

**Comment by WouterJ** [comment]
Did you try removing the cache? Do you see something interesting in the production logs?

**Comment by ghostika** [comment]
Yes, I deleted with ca:cl command but I also deleted by hand and I made a request.
If I write in any static text, that's there. But if I write out the value of `{{ app.request.locale }}` in prod env, then it's empty, but if I check the error page with the `/_error/404`  in dev env, then everything is ok.

**Comment by stof** [comment]
Well, some errors might happen earlier than the LocaleListener of Symfony setting the locale

**Comment by ghostika** [comment]
I'm using jms_i18n_routing, it looks like, that one doesn't set the locale right. Thanks.
