### ISSUE TITLE
[Form] Broken validation ChoiceType with query_builder

### ISSUE THREAD

**Issue by dkolzol** [symfony/symfony#15642]
``` php
// Symfony\Bridge\Doctrine\Form\ChoiceList\ORMQueryBuilderLoader.php
    public function getEntitiesByIds($identifier, array $values)
    {
         //...
         if (in_array($metadata->getTypeOfField($identifier), array('integer', 'bigint', 'smallint'))) {
            $parameterType = Connection::PARAM_INT_ARRAY;

            // Filter out non-integer values (e.g. ""). If we don't, some
            // databases such as PostgreSQL fail.
            $values = array_values(array_filter($values, function ($v) {
                return (string) $v === (string) (int) $v;
            }));
         } 
         //...
    }
}
```

On Windows (apache + php 32bit) bigint great 2147483647 always after (int) set to 2147483647: ((int) 2147483648) === 2147483647 // true 

```
$values = array_values(array_filter($values, function ($v) {
                return (string) $v === (string) (int) $v;
            }));
```

Its clears $values great then 2147483647 and breaks the validation ChoiceType

**Comment by HeahDude** [comment]
@dkolzol Could you please confirm this bug still exists in latest releases. There had been many fixes since you've opened this ticket.

Thanks!

**Comment by dkolzol** [comment]
I confirm. The bug is present in the recent 2.8.8 release.

**Comment by xabbuh** [comment]
I am not sure if we can do anything here. In my opinion when using such big integer you need to ensure that your PHP version is able to deal with these data too.

**Comment by xabbuh** [comment]
see #20499
