### ISSUE TITLE
Problem with ACL dependency when requiring symfony/symfony:2.8@dev

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#15648]
@WouterJ https://github.com/symfony/symfony/commit/7e9991ed69d7612586650fb18eeba7d5084de817

Symfony ACL v2.8 does not exists, only v2.8.x-dev. Should we use `self.version` instead?

**Comment by xabbuh** [comment]
@scaytrase Simply require `symfony/security-acl: ~2.8@dev` in your project's `composer.json`.

**Comment by scaytrase** [comment]
But I do not need acl. Symfony 2.8 is requiring ACL now (I've referenced a commit). But it references an incorrect version

**Comment by scaytrase** [comment]
I can reference you a failed travis build https://travis-ci.org/scaytrase/symfony-websms-bundle/jobs/77799261
Which now fails because of requiring ACL

**Comment by xabbuh** [comment]
If a package you use requires a non-stable version of another package, you have to require that package yourself or lower the [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by Tobion** [comment]
As @xabbuh explained. 2.8 is not released yet.

**Comment by WouterJ** [comment]
Please reopen, as this issue is completely valid.

The problem here is that I changed the composer.json file of symfony/symfony to include the `symfony/security-acl` dependency. It requires ~2.8.

Now, if someone installs `symfony/symfony`, Composer also needs to install the ACL dependency. However, 2.8 is not yet released: Composer fails (minimum-stability only works on the root package). The composer.json of symfony/symfony should be changed to `~2.8@dev` and the dev flag should be removed when 2.8 stable is released.

**Comment by jvasseur** [comment]
Setting the version to ```~2.8@dev``` wouldn't change anything, stability flags are ignored for non-root packages to.

**Comment by nicolas-grekas** [comment]
Would something prevent using ~2.7 or lower here?

**Comment by WouterJ** [comment]
Hmm, good question. @iltar as you did the changes, is there something that requires to use 2.8 instead of 2.7 after the split?

**Comment by iltar** [comment]
It should work with 2.7 afaik. Wouldn't it be better to have the branch alias set properly though? Because the dependency is only there to have symfony-acl by default in `<3.0.x`.

**Comment by scaytrase** [comment]
Is it not easier to reference `self.version` until we have acl/`2.8` released (as it was before with `replace` directive)? When we have it released we just could pin dependency to 2.8 and finally desync release process.

**Comment by jvasseur** [comment]
I'm not sure using self.version would work, i think it would work in the same way as the stability flag and get ignored.

**Comment by nicolas-grekas** [comment]
If acl is to be considered as independent, then putting ~2.7 is really the right way. Synchronized versions are only for synchronized components. This one starts its own life.
