### ISSUE TITLE
Generation problem (php app/console doctrine:schema:create)

### ISSUE THREAD

**Issue by MarkThink** [symfony/symfony#15640]
Affects Symfony Version 2.7.3:

fixbug: php app/console doctrine:schema:create 
I hope someone can answer why.
=========
Error: The following is fix the code, I do not know why there has also joined the event to generate a second time, resulting in such problems.

>[Doctrine\DBAL\Schema\SchemaException]                      
>  The table with name 'postgres.acl_classes' already exists. 

SchemaTool.php
```php
/**
     * Creates a Schema instance from a given set of metadata classes.
     *
     * @param array $classes
     *
     * @return Schema
     *
     * @throws \Doctrine\ORM\ORMException
     */
    public function getSchemaFromMetadata(array $classes)
    {
          .....

//        if ($eventManager->hasListeners(ToolEvents::postGenerateSchema)) {
//            $eventManager->dispatchEvent(
//                ToolEvents::postGenerateSchema,
//                new GenerateSchemaEventArgs($this->em, $schema)
//            );
//        }

        return $schema;
}
```

**Comment by dunglas** [comment]
If you ran this command two times that error is normal as tables already exist.

If you want to update your schema (on your development environment, never do that in production) run `app/console doctrine:schema:update`).

**Comment by MarkThink** [comment]
thinks! I run only once, and the database has no tables. This problem is because I caused the above code change, fix the problem caused this problem. If you do not fix the above problems, the following questions do not exist.

**Comment by MarkThink** [comment]
If these codes are not commented out, it will perform twice. This is the code I comment after solution to this problem.

**Comment by MarkThink** [comment]
I do not understand is that a data element has been created before, why repeat the process here to join the event.

**Comment by stof** [comment]
@MarkThink the event is triggered by Doctrine to provide an extension point in this place. what you should look for is which event listener is doing crap here. Removing the extension point entirely is not a bugfix. It is breaking a Doctrine feature.

**Comment by SteaveAshmore** [comment]
I am also facing the same issue, and cannot find answer anywhere, any help or guides?
@javiereguiluz can you help!!

**Comment by javiereguiluz** [comment]
@SteaveAshmore sadly I don't have a solution ... but @stof said that probably *"some event listener is the culprit"*. Maybe you can use Xdebug + PHPStorm to do a step-by-step execution and see what's going on.
