### ISSUE TITLE
[RFC][Form] option to set a translation domain for choice groups only

### ISSUE THREAD

**Issue by craue** [symfony/symfony#15644]
While upgrading a project from Symfony 2.6 to 2.7, I've noticed a special case of an entity form type using the `group_by` option: its choices don't need to be translated, but its group labels do.

When not setting `choice_translation_domain`, the group labels are rendered untranslated.
When setting `choice_translation_domain` to e.g. `true`, the group labels are rendered correctly with the downside of the choices being unnecessarily translated also.

What would be needed here is a **group_translation_domain** which defaults to the value of `choice_translation_domain` but can be set to a different value explicitly and will be used to translate group labels only. What do you think? (It would be nice to still have this in 2.7 as kind of a bugfix. :smirk:)

**Comment by Tobion** [comment]
:-1: Too many edge cases that we would need to support. Like the next one wants to translate some choices but not all. Just translate the group urself manually.

**Comment by craue** [comment]
> Just translate the group urself manually.

How? The only way I can think of would be overriding the Twig template for that specific field in my form theme.

**Comment by Tobion** [comment]
Or just translate the group name in the form type.

**Comment by craue** [comment]
To emphasize: I'm using the `group_by` option for an `entity` type.

**Comment by Tobion** [comment]
Can't you simply use a callable group_by that returns the translated value? I don't see the problem.

**Comment by craue** [comment]
Let me clarify what I mean...

entity:
```php
use Doctrine\ORM\Mapping as ORM;

class Task {

	const TYPE_SYSTEM = 'TASK_TYPE_SYSTEM';
	const TYPE_USER = 'TASK_TYPE_USER';

	/**
	 * @ORM\Column(name="title", type="string")
	 */
	protected $title;

	/**
	 * @ORM\Column(name="type", type="string")
	 */
	protected $type;

	// getters & setters

}
```

form type:
```PHP
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType {

	public function configureOptions(OptionsResolver $resolver) {
		$resolver->setDefaults(array(
			'class' => TaskType::class,
			'choice_label' => 'title',
			'group_by' => 'type',
		));
	}

	public function getParent() {
		return 'entity';
	}

}
```

translations (YAML):
```YAML
TASK_TYPE_SYSTEM: system task
TASK_TYPE_USER: user task
```

The title of each task should be rendered as-is, untranslated, while the type is a constant which has a translation.

**Comment by stof** [comment]
@craue ``group_by`` can be a callable rather than a property path (the property path is just turned into a callable using the PropertyAccess component).

```php
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Translation\TranslatorInterface;

class TaskType extends AbstractType {

    private $translator;

    public __construct(TranslatorInterface $translator) {
        $this->translator = $translator;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults(array(
            'class' => Task::class,
            'choice_label' => 'title',
            'group_by' => function ($choice) {
                if ($choice instanceof Task) {
                    return this->translator->trans($choice->getType());
                }
                // return null for other cases, for example when passing null here for the empty case
            },
        ));
    }

    public function getParent() {
        return 'entity';
    }
}
```

**Comment by craue** [comment]
Good to know. This should be documented! :smirk: Thank you, @stof.

**Comment by stof** [comment]
@craue please open an issue in the documentation if this is not documented (support for callables is new in 2.7)

**Comment by xabbuh** [comment]
FYI, someone opened a documentation pull request: symfony/symfony-docs#5755

**Comment by gowda1991** [comment]
# _sadasdsa_
