### ISSUE TITLE
Deprecated getEntityManager in LifecycleEventArgs

### ISSUE THREAD

**Issue by toniconca** [symfony/symfony#15643]
Hello,
As far as I know the function getEntityManager is deprecated since Symfony 2.1, but when I'm using a Doctrine event listener I must use getEntityManager instead of getManager.

Works this way...

    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        $em = $args->getEntityManager();
        // code...
    } 

I think it should be this....

    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        $em = $args->getManager();
        // code...
    }

**Comment by stof** [comment]
@toniconca getEntityManager is deprecated in the manager repository. Event objects are totally separate from that. this is **not** the same method.

and btw, this class is not part of Symfony at all.
