### ISSUE TITLE
[BrowserKit] Invalid Expires attribute should be ignored silently.

### ISSUE THREAD

**Issue by Naktibalda** [symfony/symfony#15656]
[BrowserKit Cookie](https://github.com/symfony/symfony/blob/464b67ed09668168cabfd77b6b3cfa26ceb1b0b0/src/Symfony/Component/BrowserKit/Cookie.php#L80) class throws an UnexpectedValueException if Expires attribute contains invalid value, but [RFC 6265](http://tools.ietf.org/html/rfc6265#section-5.2.1) states that "If the attribute-value failed to parse as a cookie date, ignore the cookie-av."

**Comment by xabbuh** [comment]
Actually, after thinking of this again I do not think that we need to change the constructor. It is documented that the expected value must be a string containing the expires timestamp. However, we indeed need to ignore invalid date formats when we are parsing a cookie header (i.e. inside the `fromString()` method). See #21462 for a fix.
