### ISSUE TITLE
Yaml parser incorrectly handles float-valued keys

### ISSUE THREAD

**Issue by Ocramius** [symfony/symfony#15667]
As per FriendsOfPHP/security-advisories#84, `Yaml#parse()` doesn't consider float keys, therefore following structure will parse incorrectly:

```yml
foo:
    1.2: "bar"
    1.3: "baz"
```

**Comment by Tobion** [comment]
So what is the actual and what the expected parsing? A reference to the yaml spec dealing with this would be nice as well.

**Comment by Ocramius** [comment]
Actual: only key `1` is defined (cast to `(int)` happens implicitly.

Expected: keys `"1.2"` and `"1.3"` are defined in the array.

In yaml, keys are arbitrary nodes as per http://www.yaml.org/spec/1.2/spec.html#key:%20value%20pair//

**Comment by stof** [comment]
@Tobion the Yaml spec will tell you that the key is the float ``1.2``. when setting a float key in a PHP array, it gets casted to int, which may be unexpected for someone using this Yaml file.
