### ISSUE TITLE
Question: use of Symfony commands

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#15669]
We all know there is too much commands provided by the Symfony console in the framework, but the question is: how can we decide which one are useful ? which ones should be provided in require-dev or in external Bundle ? which ones should be removed ?

This is why I need to help, I need you to answer a little survey about your use of Symfony commands.
Then I will publish the results and make a pull request to remove some commands, if needed.

=> https://fr.surveymonkey.com/r/6YZKQ8J

Of course, the results will be public and added here.

*Notes*:
* all aliases commands are removed in Symfony3 (/c @stof)
* acl commands are removed and probably moved to AclBundle (/c @iltar)

**Comment by stof** [comment]
@mickaelandrieu you should not have separate lines for aliases of the same command (``config:debug`` and ``debug:config`` are the same one). yoou should combine them in a single choice.

**Comment by mickaelandrieu** [comment]
@stof: I understand your point of view, but remove some aliases can be discussed too :)
I know some of them will be removed in Symfony 3, but for now users have theses available choices.

I will combine the results of aliases, trust me :)

**Comment by stof** [comment]
Well, aliases are already removed in 3.0 (or will be) as they are deprecated and are here for BC.

**Comment by iltar** [comment]
Please note that the ACL commands will be removed from the core with 3.0, I'm working on extracting it from the security bundle: https://github.com/symfony/AclBundle/pull/1

**Comment by mickaelandrieu** [comment]
@iltar @stof thanks for informations, I update my post :)

**Comment by tigitz** [comment]
Is there any clear technical drawback of having so many commands ?

In case you're thinking about removing some commands just for "clarity", did the number of commands blocked you in some kind of way at one point in your development process?

Did the blocking is so important that it's needed to remove legitimate use-cases that people, even in a minority, might need or use?

**Comment by mickaelandrieu** [comment]
@tigitz have many useless commands increase technical debt, for instance look this issue: https://github.com/symfony/symfony/issues/14138

this kind of task make me sad, because it's (mostly) a waste of time *if* theses commands are not used.

Also, my point is not to remove them, but to move them on Bundles, or - for some of them - make single command application (twig-linter, yaml-linter ?).

And, yes I don't like to see my command line tool full of commands that I don't need and that I "can't" remove because theses commands are mostly located into "required" bundles (Security/Framework bundles).

If it's only me, I can deal with it :) but maybe we can improve the framework to let the developpers decide which commands they realy need.

**Comment by fabpot** [comment]
The list does not make sense. Most of the commands are from bundles that are not even in this repository. Don't want the Assetic command, don't install the Assetic bundle, the same goes for Doctrine, Swiftmailer, ...

The poll is interesting to know which ones are mostly used, but all commands have their usage...

**Comment by mickaelandrieu** [comment]
@fabpot strongly disagree to this point, more than twenty commands come from "required bundles".

I'm very surprised to see you opposite to a debate based on objectives data :/

But you decide, of course.

**Comment by cordoval** [comment]
@mickaelandrieu I think your question is more geared towards your framework. I recommend what I do in my applications basically I plug only the commands I want and remove everything else. This is in full control of the user and it should not be left to default to symfony for two reaons. One is you will not always agree, this case. And Two I think for your framework you want certain usage. Business expectations are more important than the framework after all.

**Comment by tucksaun** [comment]
@mickaelandrieu most of the commands from your lists are from DoctrineBundle, so you should open the issue there then.

**Comment by mickaelandrieu** [comment]
> I recommend what I do in my applications basically I plug only the commands I want and remove everything else.
I think Symfony should provide by default few commands, and not all the commands any user may need once a year, maybe, on an edge case :/ but the debate is closed, sadly.

I will post the results in days, because I think theses informations can be interesting anyway.

@tucksaun good idea :) I will do it if the results show theses commands are not very used, thanks !
