### ISSUE TITLE
Unable to get parameters using {{app.request.query.get('name')}}  in template in Symphony

### ISSUE THREAD

**Issue by amitpanwar86** [symfony/symfony#15668]
Hi,

I am facing a problem in retrieving parameters directly in twig template .
I tried to get request parameter using : 
{{ app.request.query.get('name') }} - {{ app.request.query.get('address') }} in twig template.
But it dsnt render anything.
I also have checked above suggestion but there is no satisfactory answer.

Thanks,
A.

**Comment by javiereguiluz** [comment]
If `name` and `address` are query parameters, this definitely works ... unless you are using this code in a template rendered via a sub-request (with `render()` Twig function for example). Inspect the contents of the request query with `{{ dump(app.request.query) }}`. If this doesn't work, please ask in any of the following user support channels: http://symfony.com/support

**Comment by amitpanwar86** [comment]
I am not getting any data in dump.
Here is output of dump: 

ParameterBag {#9 ▼
  #parameters: []
}

**Comment by stof** [comment]
@amitpanwar86 how does your URL look like ? And are you using a subrequest ?

**Comment by amitpanwar86** [comment]
its looks like

/api/frontend/users/test/{name}/{address}"

**Comment by stof** [comment]
then the answer is easy: you are **not** passing the name and address as query parameters. They are part of the path, and match by the router. so there will be in the request attributes. Use ``app.request.attributes.get()``

**Comment by amitpanwar86** [comment]
Okay,
But i can see in debugger these parameters like: 

_route_params	: [name => amit, address => hello]
address	: hello
name	: amit

**Comment by stof** [comment]
but you see this in the route attributes, not in the route query params (which are dumped separately in the profiler

**Comment by amitpanwar86** [comment]
Okay i got it.

So my url should be look like :
url?name=amit&address=hello

Am i right? if not please correct me.
Thanks for your help.

**Comment by javiereguiluz** [comment]
@amitpanwar86 that's right. Your last example uses query parameters, so `app.request.query.get()` will work as expetected.

**Comment by javiereguiluz** [comment]
It's safe to close this support issue as "fixed".

**Comment by oussaki** [comment]
is this solved because none of the codes mentioned in this topic works for me !

**Comment by xabbuh** [comment]
@oussaki For support questions, please refer to one of the [support channels](https://symfony.com/support). We use GitHub issues only to discuss new features and for bug reports. Thank you for understanding.

**Comment by ajaybmishra37** [comment]
I does not worked for me as well.

**Comment by xabbuh** [comment]
Please open a new issue if you think that you discovered a bug and provide an example application that allows to reproduce it.
