### ISSUE TITLE
using parameters with - or . in "assets_base_urls" fatals in 2.7.3

### ISSUE THREAD

**Issue by penfold45** [symfony/symfony#15679]
Hi I am just trying to upgrade from 2.6.11 to 2.7.3

I have the following set up for assets_base_urls

        assets_base_urls:
           http: [%cdn.url%, %cdn-2.url%]
           ssl: [%cdn.url-ssl%, %cdn-2.url-ssl%]

Which works fine on 2.6.11

But for some reason it fatals with the following error on 2.7.3.

<code>
line":61,"function":"getSslUrls","class":"Symfony\\Component\\Asset\\UrlPackage","type":"->","args":[[null,"https://xxxxxx.cloudfront.net","https://xxxxx.cloudfront.net"]]}
</code>

Looks like the . and or the - are adding a null record to the list of urls. if I remove all the .'s and -'s then it works fine. for example

        assets_base_urls:
           http: [%cdnurl%, %cdn2url%]
           ssl: [%cdnurlssl%, %cdn2urlssl%]

**Comment by penfold45** [comment]
Think I may have found an issue. I am very surprised it works like this.

The null option in the above error appears to be coming from me.

I have "cdn.url" defined in config.yml and config_dev.yml

I intended the one in config_dev.yml to be an override but it appears to merge the params from both configs. Is this the intended behaviour? I have never noticed this type of behaviour before.

I can now easily fix the original error by putting a correct value in my config_dev.yml

**Comment by tiois** [comment]
Using the DEV environment, it should use the parameter defined in config_dev.yml. Otherwise, it should use the parameter defined in config.yml (or any environment specific config file like config_prod.yml).

**Comment by penfold45** [comment]
Yep that is what I would expect it to do but it is not.

**Comment by stof** [comment]
Can you create a reproducing case based on the symfony-standard ?

**Comment by xabbuh** [comment]
ping @penfold45 :)

**Comment by xabbuh** [comment]
closing due to lack of feedback

@penfold45 Please feel free to comment when you can provide a failing test case.
