### ISSUE TITLE
[Console] RFC for Symfony 3.0: Show errors even when --quiet is present

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#15680]
I'd like to discuss this (sort of BC breaking) change for 3.0. The problem is in most cases people use --quiet / -q when running a console app, they don't want any output but still expect output/details in case an error occurs.

I see a few options to handle this:

1. Check whether there is an <error> tag in the message and if so output no matter if verbosity is quiet or not
2. Only output exceptions that are caught by the Application, i.e. "uncaught" exception, regardless of the verbosity.
3. Add an optional parameter to OutputInterface::[write](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Output/OutputInterface.php#L46)/writeln, that would be defined as `$verbosity = self::VERBOSITY_NORMAL`. That would allow any write call to contain information about which verbosity level it should be written to. I think that would be quite nice because it also enables dropping a lot of conditionals like `if ($output->isVeryVerbose()) { $output->writeln(...); }`, those would become `$output->writeln('foo', OutputInterface::OUTPUT_NORMAL, OutputInterface::VERBOSITY_VERY_VERBOSE);` which reads a bit better, except for the constants being long as hell and the OUTPUT type sitting in the middle (not sure if that'd be too much of a BC break to add the new arg as second argument, I've never seen the output type being used in the wild, or maybe both could be cobbled together as a bitwise flag).

Point 3 would be nice either way I think, and it would allow some messages to pass through the quiet mode, so if you do a write with VERBOSITY_QUIET it would always be sent, but VERBOSITY_NORMAL and above wouldn't be sent in quiet mode. Similarly we could change the exception writing to be written on the quiet verbosity.

If anyone has another idea or comments that'd be appreciated.

**Comment by fabpot** [comment]
Point 3 sounds the best option.

**Comment by Seldaek** [comment]
@fabpot I think so too. I've discussed this a bit on IRC with Iltar and we thought it could also go into 2.8 if we turn the $type arg into a $flags arg that takes bit flags for either `OUTPUT_*` or `VERBOSITY_*`. That'd solve the long function call issue, but it requires changing the values of the constants. I don't know if that's acceptable in 2.8 or not. IMO people should know better than use the values, and I've never seen this arg used anywhere, so I would say it's ok but not sure what others think.

**Comment by fabpot** [comment]
Changing the values is fine by me, if not, defining constants is useless.

**Comment by javiereguiluz** [comment]
@Seldaek if I understand your proposal correctly, I think it's a bit contradictory:

**Problem**: if I run a command with `--quiet` I don't want to see any message.
**Solution**: define `VERBOSITY_QUIET` to allow commands to display messages when running them with `--quiet`

**Comment by WouterJ** [comment]
@javiereguiluz `--quiet` means that you don't want to have all informational messages (like "Clearing cache for `dev`"). You still want to see the error messages (e.g. "Unable to clear cache: No permission to remove dir `dev_old`").

**Comment by javiereguiluz** [comment]
@WouterJ yes, but I think these two things are different:

1) Let's change `--quite` behavior to supress all messages, except error messages.
2) Let's change some things to allow commands to show messages even in `--quiet` mode and change errors to always appear in quiet too.

I think the first point makes sense. But I don't understand the second one.

**Comment by WouterJ** [comment]
@javiereguiluz I think this is to be more flexible (e.g. allow errors that are not exceptions).

Btw, point (3) of this issue (and your second point) is not only about writing messages in quiet mode, it's also about improving to conditionally write in certain modes. E.g:
```diff
-if ($output->isVerbose()) {
-    $this->writeln('Some verbose message');
-}
+$this->writeln('Some verbose message', default, OutputInterface::VERBOSITY_VERBOSE);
```

**Comment by javiereguiluz** [comment]
@WouterJ the new code would be:

```php
$output->writeln('Some verbose message', OutputInterface::OUTPUT_NORMAL, OutputInterface::VERBOSITY_VERY_VERBOSE);
```

(which by the way is 114 chars long and the previous `if()` is just 71 chars)

My concern is that the new behavior would allow commands to display any message even when running in `--quiet` ... which is the exact same behavior as today.

**Comment by Seldaek** [comment]
@javiereguiluz the new code if we change $type to be a bitmask of options would be `$output->writeln('Some verbose message', OutputInterface::VERBOSITY_VERY_VERBOSE);` which is maybe still longer in characters but only one line and disturbs the code less with output conditionals that aren't really relevant to the code. 

Right now, in --quiet mode AFAIK it's impossible to output anything at all. I'd just like to change that because it's usually not what people mean by quiet, they just don't want any output if things go well. If you get an error in a CI build or something and you used --quiet to keep things lean in the output, then it fails but you don't know what happened retroactively which sucks. It's been requested a few times by Composer users.

If you *really* don't want any output ever, `>/dev/null` works fine..
