### ISSUE TITLE
[DependencyInjection]Uninformative message when encountering malformed yml file

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#15702]
When trying to clear the cache, I encountered this error:
> [Symfony\Component\Yaml\Exception\ParseException]                      
  A YAML file cannot contain tabs as indentation at line 18 (near "     "). 

Now this doesn't tell me any information on where this malformed yml file is.  
The reason is [This line](https://github.com/symfony/DependencyInjection/blob/master/Loader/YamlFileLoader.php#L307) in the `YamlFileLoader`.I think the exception should be caught, and a more informative message should be the set on the new exception.

**Comment by sstok** [comment]
The loading of the file is done here.
https://github.com/symfony/DependencyInjection/blob/master/Loader/YamlFileLoader.php#L300

But :+1: on making this more clear.

**Comment by xabbuh** [comment]
see #15731
