### ISSUE TITLE
BC break for collection type's prototype_data feature

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#15707]
related PR: https://github.com/symfony/symfony/pull/12314
related commit: https://github.com/symfony/symfony/commit/54bd6f76f86e5f778ad7c16e95ca2e0622466766

the way its currently implemented in this commit **is** a BC break since the prototype_data will **always** be used, even if legacy code not using prototype_data relies on the old behavior where the data option is used for the prototype form. i recommend revisiting this implementation and using code similar to the one i showed in my comment in the PR https://github.com/symfony/symfony/pull/12314#issuecomment-72348022

**Comment by xabbuh** [comment]
@backbone87 Could you provide a failing test case?

**Comment by jakzal** [comment]
@backbone87 ping

**Comment by backbone87** [comment]
Sorry, i am really busy atm.
Derived from the test case used in the PR:
```
public function testPrototypeData() {
  $form = $this->factory->create('collection', array(), array(
    'type' => 'text',
    'allow_add' => true,
    'prototype' => true,
    //'prototype_data' => 'foo', // in a legacy form this is not present
    'options' => array(
      'data' => 'bar',
    ),
  ));

  // this will fail, but is expected legacy behavior
  $this->assertSame('bar', $form->createView()->vars['prototype']->vars['value']);
}
```

**Comment by memphys** [comment]
Found same BC break in our project too. After update to 2.8 value attributes just disappeared in the prototype. Anyone can suggest a fast workaround for this without downgrading? I can work on a fix and PR but not too soon.

**Comment by HeahDude** [comment]
@backbone87 @memphys here's a possible fix :
```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['allow_add'] && $options['prototype']) {
            $prototype = $builder->create($options['prototype_name'], $options['entry_type'], array_replace(array(
                'label' => $options['prototype_name'].'label__',
            ), $options['entry_options'], ($options['prototype_data'] ? array(
                'data' => $options['prototype_data'],
            ) : array())));
            $builder->setAttribute('prototype', $prototype->getForm());
        }

**Comment by memphys** [comment]
@HeahDude thanks, but I already found PR with the original introduction of `prototype_data` and @backbone87 has already suggested a fix there. Seems like anyway this needs a fix in CollectionType inside Symfony. I'll make a PR tomorrow.

**Comment by memphys** [comment]
@xabbuh @jakzal @backbone87 made a PR but have some problems with the test. Tested the code in our project and it fixes the BC break. If you can help with some directions on the test, I'll try to finish it. Thanks.

**Comment by memphys** [comment]
Made new PR to correct branch. Sorry for inconvenience.

**Comment by HeahDude** [comment]
@memphys you should replace `entry_options` by `options` for legacy test

**Comment by HeahDude** [comment]
I suggest this implementation with a comment for depreciation :
```php
// Symfony/Component/Form/Extension/Core/CollectionType.php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['allow_add'] && $options['prototype']) {
            $prototype = $builder->create($options['prototype_name'], $options['entry_type'], array_replace(array(
                'label' => $options['prototype_name'].'label__',
            // check "$options['prototype_data'] for BC. Condition to be removed in 3.0.
            ), $options['entry_options'], ($options['prototype_data'] ? array(
                'data' => $options['prototype_data'],
            ) : array())));
            $builder->setAttribute('prototype', $prototype->getForm());
        }
        ...

**Comment by memphys** [comment]
@HeahDude so in 3.0 this BC is intended? I mean if no prototype_data is set, then it won't be filled from form data?

**Comment by HeahDude** [comment]
@memphis I just suppose it does, considering `CollectionTypeTest::testProrotypeData()` just before your added test, this should be the expected behaviour

**Comment by memphys** [comment]
@HeahDude ok, understood, thanks. But it sounds strange for me)
