### ISSUE TITLE
[DX] Defining a service as private still public available

### ISSUE THREAD

**Issue by cmodijk** [symfony/symfony#15703]
I'm currently using the public=false on my services but when a services is used twice in the container it becomes available inside the controller from the public side. I don't know if this is expected behaviour or not but I was a bit confused that this worked. If I look at the duped container i see that the private services are inlined but the private one which is used twice is not. 

If this is expected i think this should be documented.
* http://symfony.com/doc/current/components/dependency_injection/advanced.html

**Comment by cmodijk** [comment]
I think this sentence is ment to describe my situation so i'm closing this again. 

> This may or may not work, depending on if the service could be inlined. Simply said: A service can be marked as private if you do not want to access it directly from your code.

**Comment by WouterJ** [comment]
It is expected and also documented in the article you referenced:

 > **What makes private services special is that, if they are only injected once, they are converted from services to inlined instantiations (e.g. `new PrivateThing()`)**. This increases the container's performance.

**Comment by cmodijk** [comment]
@WouterJ Yeah, i found it tnx and i'm sorry again for creating this issue!
