### ISSUE TITLE
Add information about APC to symfony standard edition

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#15716]
In the Symfony Standard Edition (Symfony 2.7.x) there is an uncommented cache example in config_prod.yml with APC. But APC is not available for PHP5.5+.

I think there should be more information as comment next to the examples.

```yml
#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
```

**Comment by jakzal** [comment]
Thanks for reproting this. I agree we should deal with this issue. However, it should be reported to the https://github.com/symfony/symfony-standard. Could you please create a similar issue in that repository?

**Comment by JHGitty** [comment]
Oh, my mistake. Thanks!
I'll create a similar issue in that repository.
