### ISSUE TITLE
Oracle add duplicate slashes for ClassType of ObjectIdentity in ACL provider

### ISSUE THREAD

**Issue by imilyukov** [symfony/symfony#15723]
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/AclProvider.php#L536 - add duplicate slashesh and that not matching there:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/AclProvider.php#L196

Bug is defined with SonataAdminBundle ACL.

**Comment by fabpot** [comment]
Closing this issue as ACLs are not part of Symfony Core anymore (see #14718 for the initial discussion). It the issue still exists, you can create an issue on symfony/security-acl or symfony/acl-bundle. Thanks.
