### ISSUE TITLE
Error on WebProfiler/Profiler/results.html.twig with vendor\jms\\serializer\src\JMS\Serializer\Twig\SerializerExtension.php

### ISSUE THREAD

**Issue by nostub** [symfony/symfony#15726]
Hello eveybody, 
I have this error after having upgrated my configuration to symfony 2.7 when the web profiler loads :
 
An exception has been thrown during the compilation of a template ("Catchable Fatal Error: Argument 2 passed to Twig_Function::__construct() must be callable, string given, called in ...\vendor\jms\serializer\src\JMS\Serializer\Twig\SerializerExtension.php on line 53 and defined") in "@WebProfiler/Profiler/results.html.twig

I have this configuration in my composer : 
require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-cache-bundle": "dev-master",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "incenteev/composer-parameter-handler": "dev-master",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "doctrine/mongodb-odm": "1.0.*@dev",
        "doctrine/mongodb-odm-bundle": "3.0.*@dev",
        "jms/serializer": "dev-master",
        "jms/serializer-bundle": "dev-master",
        "friendsofsymfony/rest-bundle": "dev-master",
        "hwi/oauth-bundle": "dev-master",
        "nelmio/cors-bundle": "dev-master",
        "nelmio/api-doc-bundle": "@dev",
        "endroid/gcm-bundle": "dev-master",
        "jdare/clank-bundle": "dev-master",
        "richsage/rms-push-notifications-bundle": "dev-master",
        "snc/redis-bundle": "1.1.x-dev",
        "guzzle/guzzle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    }

The problem can be stopped by setting in config_dev.yml :
web_profiler:
    toolbar: false
but as the result I don't have the profiler and I would like to make this functionnality work again.

For information, I had the same kind of error with my forms but I resolved it by changing :
{{ form_row(f) }} to , {'label': 'some label'})

Somehow, I think that twig have changed a little and that is the cause for this error.
I would be very thankful for anyone who could have a start of answer on that matter.
Thanks in advance !!!

**Comment by stof** [comment]
This is a bug in JMSSerializerBundle, not in Symfony

**Comment by stof** [comment]
See https://github.com/schmittjoh/serializer/pull/490 for the fix

**Comment by stof** [comment]
btw, the solution to avoid the issue for now is to use the stable version of jms/serializer instead of the dev version. The regression has not been released yet

**Comment by nostub** [comment]
Hello Stof,  
Indeed you gave me the idea to put back the minimum-stability to stable and to launch the command "composer require jms/serializer-bundle". Everything is working fine now :)
Thank you very much for your help!
