### ISSUE TITLE
Getting wrong ExitCode on some Systems

### ISSUE THREAD

**Issue by knightsub7** [symfony/symfony#15727]
For example I have this little code snippet:
```php
require 'vendor/autoload.php';
$process = new \Symfony\Component\Process\Process('ls -alh');
$process->start();
while($process->isRunning()) {
    usleep(500);
}

var_dump($process->getExitCode());
```

On my vagrant machine this code give me the exit code 0.
On the server of our client this code return the exit code -1.

The vagrant machine is based puphpet/ubuntu1404-x64 and the server of our client is a suse linux (enterprise 12).

I've debugged that the call of proc_get_status() and proc_close() returns on the server the exit code -1, but in the vagrant machine I'm getting 0 for exit code from proc_get_status() as soon as running is marked as false. So the only difference I see is that the last call of proc_get_status returns me different exit codes. The function proc_close() is also returning the exit code -1 on the vagrant machine.

I'm not sure if it's a configuration issue on the server or the implementation is not correct for every linux distrubution...

Can anyone help me?

**Comment by stof** [comment]
can you check whether PHP is configured with ``--enable-sigchild`` on the server ?

**Comment by knightsub7** [comment]
How can I check this? In the phpinfo i can't find anything like this...

**Comment by stof** [comment]
well, make a search for ``--enable-sigchild`` in the phpinfo. If it does not appear, it is not compiled with sigchild

**Comment by knightsub7** [comment]
The option `--enable-sigchild` isn't either in the phpinfo of the server still in my vagrant machine.
Both systems are using php 5.5.

**Comment by bretrzaun** [comment]
Same problem here: the commands are executed successfully (regarding its output). However the exit code is still -1.

**Comment by fabpot** [comment]
Closing as there is nothing we can do without a script that we can use to reproduce the issue. There is something going on here but that's impossible to guess.

**Comment by bretrzaun** [comment]
@fabpot We don't know what information we should provide to help diagnosing this issue. We tried to provide a test script (see above) and the environments being used.
If you need more information, please let me know.
