### ISSUE TITLE
unable to rename file inside tmp folder

### ISSUE THREAD

**Issue by anuj331991** [symfony/symfony#15720]
I am facing the rename issue a lot: rename(\/tmp\/__CG__MyEntity.php.55eab1cb8bee30.16966444,\/tmp\/__CG__MyEntity.php), operation not permitted.Please suggest any fix for this.

**Comment by jakzal** [comment]
Please ask support questions on [http://stackoverflow.com/](stackoverflow.com). We only use github issues for reporting bugs and sending pull requests. Thank you :)
