### ISSUE TITLE
[2.7.4] Twig error when doing a cache:clear

### ISSUE THREAD

**Issue by chandon** [symfony/symfony#15732]
I've upgraded to Symfony 2.7.4

I got an error breaking the cache:clear command (and breaking my website). See below for the full stack trace. 
The only solution was to comment lines 583-585 of the file vendor/twig/twig/lib/Twig/ExpressionParser.php

    php app/console cache:clear --env=prod --no-debug

    Clearing the cache for the prod environment with debug false
    PHP Notice:  Undefined variable: test in vendor/twig/twig/lib/Twig/ExpressionParser.php on line 583
    PHP Stack trace:
    PHP   1. {main}() app/console:0
    PHP   2. Symfony\Component\Console\Application->run() app/console:27
    PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
    PHP   4. Symfony\Component\Console\Application->doRun() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
    PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
    PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
    PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
    PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
    PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:138
    PHP  10. Symfony\Bundle\AsseticBundle\CacheWarmer\AssetManagerCacheWarmer->warmUp() vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
    PHP  11. Assetic\Factory\LazyAssetManager->load() vendor/symfony/assetic-bundle/CacheWarmer/AssetManagerCacheWarmer.php:34
    PHP  12. Assetic\Factory\Loader\CachedFormulaLoader->load() vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:160
    PHP  13. Assetic\Extension\Twig\TwigFormulaLoader->load() vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php:59
    PHP  14. Twig_Environment->parse() vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php:38
    PHP  15. Twig_Parser->parse() vendor/twig/twig/lib/Twig/Environment.php:544
    PHP  16. Twig_Parser->subparse() vendor/twig/twig/lib/Twig/Parser.php:95
    PHP  17. Twig_ExpressionParser->parseExpression() vendor/twig/twig/lib/Twig/Parser.php:141
    PHP  18. Twig_ExpressionParser->getPrimary() vendor/twig/twig/lib/Twig/ExpressionParser.php:41
    PHP  19. Twig_ExpressionParser->parsePrimaryExpression() vendor/twig/twig/lib/Twig/ExpressionParser.php:84
    PHP  20. Twig_ExpressionParser->getFunctionNode() vendor/twig/twig/lib/Twig/ExpressionParser.php:144
    PHP  21. Twig_ExpressionParser->getFunctionNodeClass() vendor/twig/twig/lib/Twig/ExpressionParser.php:351
    PHP Fatal error:  Call to a member function getAlternative() on a non-object in vendor/twig/twig/lib/Twig/ExpressionParser.php on line 583
    PHP Stack trace:
    PHP   1. {main}() app/console:0
    PHP   2. Symfony\Component\Console\Application->run() app/console:27
    PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
    PHP   4. Symfony\Component\Console\Application->doRun() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
    PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
    PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
    PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
    PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
    PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:138
    PHP  10. Symfony\Bundle\AsseticBundle\CacheWarmer\AssetManagerCacheWarmer->warmUp() vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
    PHP  11. Assetic\Factory\LazyAssetManager->load() vendor/symfony/assetic-bundle/CacheWarmer/AssetManagerCacheWarmer.php:34
    PHP  12. Assetic\Factory\Loader\CachedFormulaLoader->load() vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:160
    PHP  13. Assetic\Extension\Twig\TwigFormulaLoader->load() vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php:59
    PHP  14. Twig_Environment->parse() vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php:38
    PHP  15. Twig_Parser->parse() vendor/twig/twig/lib/Twig/Environment.php:544
    PHP  16. Twig_Parser->subparse() vendor/twig/twig/lib/Twig/Parser.php:95
    PHP  17. Twig_ExpressionParser->parseExpression() vendor/twig/twig/lib/Twig/Parser.php:141
    PHP  18. Twig_ExpressionParser->getPrimary() vendor/twig/twig/lib/Twig/ExpressionParser.php:41
    PHP  19. Twig_ExpressionParser->parsePrimaryExpression() vendor/twig/twig/lib/Twig/ExpressionParser.php:84
    PHP  20. Twig_ExpressionParser->getFunctionNode() vendor/twig/twig/lib/Twig/ExpressionParser.php:144
    PHP  21. Twig_ExpressionParser->getFunctionNodeClass() vendor/twig/twig/lib/Twig/ExpressionParser.php:351
    
    
    
      [Symfony\Component\Debug\Exception\FatalErrorException]
      Error: Call to a member function getAlternative() on a non-object
    
    
    
    cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by Tobion** [comment]
Already fixed in https://github.com/twigphp/Twig/commit/dd446c0c650d688d36b93f1720eb268cc7e317b9
@fabpot twig needs a patch release for that. The new symfony 2.3 and 2.7 releases use that broken twig release.

**Comment by chandon** [comment]
Yes that's right, stof already fixed it !

**Comment by nick-denry** [comment]
Great! I have the same issue with the SonataAdminBundle. Instead of INFO message I've got "Error: Call to a member function getAlternative() on a non-object" with CRUD::base_edit_form.html.twig and deprecated "form_enctype(form)".

**Comment by xabbuh** [comment]
[Twig 1.21.2 is released](http://symfony.com/blog/twig-1-21-2-released) which solves the problem.
