### ISSUE TITLE
Browserkit: UnexpectedValueException in Cookie.php on Google App Engine

### ISSUE THREAD

**Issue by atrauzzi** [symfony/symfony#15739]
I'm not sure if this is a problem with the environment (GAE), or if it's an issue that Browserkit might benefit from handling...

I've been getting the following exception when trying to check a URL via Browserkit on Google App Engine:

![cookie expiration error](https://cloud.githubusercontent.com/assets/115199/9762194/8c1d0326-56c7-11e5-8d5b-a39ec2b14c74.png)

I've opened [a ticket](https://code.google.com/p/googleappengine/issues/detail?id=12326) with app engine just in case it's something on their end.  Even if it is, insights here might be able to help speed things along.  Otherwise, maybe this is a real bug?

**Comment by negreanucalin** [comment]
Are you using a 32 bit compilation?

**Comment by atrauzzi** [comment]
It appears to be 64bit, this shot was taken from running `phpinfo` on the live GAE environment:

![image](https://cloud.githubusercontent.com/assets/115199/9762737/ff19b808-56ca-11e5-8026-4f77b0e349fd.png)

**Comment by stof** [comment]
the question is not whether your OS is 64 bit, but whether PHP is (the 32bit version of PHP can run on 64bit systems)

**Comment by atrauzzi** [comment]
Hah, well look at that.  32bit came out when I ran `(PHP_INT_MAX == 2147483647)?'32-bit':'64-bit'` on the environment.

**Comment by xabbuh** [comment]
It doesn't seem that we can do anything in Symfony then about this issue.

**Comment by atrauzzi** [comment]
@xabbuh - Okay, so Symfony requires it be running on 64bit PHP?

**Comment by xabbuh** [comment]
@atrauzzi Not necessarily, but then you would to use short lifetime values for your cookies (and check other usages of dates in your code that would be affected by this too).

**Comment by atrauzzi** [comment]
@xabbuh Unfortunately this is happening with requests from servers outside of my own.  I don't have control over the lifetime in these cases.

I think the library should be able to handle this without me having to fudge or censor the information going into it by manipulating server variables.

**Comment by stof** [comment]
@xabbuh looking at the code, we could perfectly store the timestamp as a string internally rather than an integer. We never do anything else with the integer than casting it back to string anyway.

**Comment by xabbuh** [comment]
Hm indeed, I looked at the wrong `Cookie` class (the one from the HttpFoundation) where don't seem to suffer from this restriction.

**Comment by xabbuh** [comment]
Well, no, I think we can only fix this partially by not casting a passed string. However, the given example will still fail as the date string is parsed by PHP which returns false as the date is too great. Not sure what we should do in this case.

**Comment by stof** [comment]
@xabbuh IMO, it can be fixed entirely. I will try to work on it at the end of the week

**Comment by atrauzzi** [comment]
@stof - Thanks for looking into this, do you have any updates about the status of the fix?

**Comment by jameshalsall** [comment]
@atrauzzi I've opened a PR with a potential fix for this
