### ISSUE TITLE
Assetic problem, after updating to twig bridge 2.7.4 (from 2.7.3)

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#15730]
After updating my silex app https://github.com/dominikzogg/energycalculator, i get this error trying to use assetic with twig. Downgrade to the old composer.lock and run install fix the problem.

Fatal error: Call to a member function getAlternative() on null in /vagrant/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 583

Call Stack:
    0.0001     233480   1. {main}() /vagrant/app/console:0
    0.9740   17293176   2. Symfony\Component\Console\Application->run() /vagrant/app/console:18
    0.9821   17531496   3. Symfony\Component\Console\Application->doRun() /vagrant/vendor/symfony/console/Application.php:126
    0.9822   17532416   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/vendor/symfony/console/Application.php:195
    0.9874   17621224   5. Symfony\Component\Console\Command\Command->run() /vagrant/vendor/symfony/console/Application.php:886
    0.9875   17625608   6. Saxulum\AsseticTwig\Command\AsseticDumpCommand->execute() /vagrant/vendor/symfony/console/Command/Command.php:259
    0.9980   17753696   7. Saxulum\AsseticTwig\Assetic\Helper\Dumper->dump() /vagrant/vendor/saxulum/saxulum-assetic-twig-provider/src/Saxulum/AsseticTwig/Command/AsseticDumpCommand.php:28
    1.0846   17862256   8. Assetic\Factory\LazyAssetManager->getNames() /vagrant/vendor/saxulum/saxulum-assetic-twig-provider/src/Saxulum/AsseticTwig/Assetic/Helper/Dumper.php:56
    1.0846   17862520   9. Assetic\Factory\LazyAssetManager->load() /vagrant/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:195
    2.8708   27944344  10. Assetic\Extension\Twig\TwigFormulaLoader->load() /vagrant/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:160
    2.8755   27982720  11. Twig_Environment->parse() /vagrant/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php:38
    2.8755   27982720  12. Twig_Parser->parse() /vagrant/vendor/twig/twig/lib/Twig/Environment.php:544
    2.8755   27985152  13. Twig_Parser->subparse() /vagrant/vendor/twig/twig/lib/Twig/Parser.php:95
    2.8762   28006920  14. Twig_TokenParser_Block->parse() /vagrant/vendor/twig/twig/lib/Twig/Parser.php:187
    2.8762   28009872  15. Twig_Parser->subparse() /vagrant/vendor/twig/twig/lib/Twig/TokenParser/Block.php:45
    2.8765   28022488  16. Twig_ExpressionParser->parseExpression() /vagrant/vendor/twig/twig/lib/Twig/Parser.php:141
    2.8765   28022536  17. Twig_ExpressionParser->getPrimary() /vagrant/vendor/twig/twig/lib/Twig/ExpressionParser.php:41
    2.8765   28022536  18. Twig_ExpressionParser->parsePrimaryExpression() /vagrant/vendor/twig/twig/lib/Twig/ExpressionParser.php:84
    2.8765   28022536  19. Twig_ExpressionParser->getFunctionNode() /vagrant/vendor/twig/twig/lib/Twig/ExpressionParser.php:144
    2.8766   28024400  20. Twig_ExpressionParser->getFunctionNodeClass() /vagrant/vendor/twig/twig/lib/Twig/ExpressionParser.php:351

**Comment by dominikzogg** [comment]
If i upgrade anything except the bridge it runs fine

**Comment by GawainLynch** [comment]
This [commit](https://github.com/symfony/TwigBridge/commit/3a333148a7969df1841d2bb1c95e4034702a4c60) is the on responsible, reverting it fixes the problem.

**Comment by dominikzogg** [comment]
@GawainLynch thank you for taking a look into this.
Its a BC within a patch release, which is very bad.

**Comment by GawainLynch** [comment]
@dominikzogg it's given us bad breaks on Bolt, but not in Assetic specifically still tracking down what we have that needs updating.

@stof an easy fix might be?

**Comment by fabpot** [comment]
Sorry about the inconvenience. It's not a BC break but rather a bug in Twig that has been fixed now. If you upgrade to Twig 1.21.2, everything should work again.

**Comment by GawainLynch** [comment]
Confirmed here, thanks @fabpot

**Comment by dominikzogg** [comment]
@fabpot thank you works perfect
