### ISSUE TITLE
Extend template in child bundle fires a nested loop error

### ISSUE THREAD

**Issue by bertoost** [symfony/symfony#15755]
For example; when you have a "A\MyBundle" namespace and a "B\MyBundle". The B version is only loaded in certain situation and is a child bundle of "A\MyBundle". In this bundle there is a controller and a view etc.
The view's filename is "index.html.twig" and you want to override some blocks in the B version.
You can not create the same file and extend the A one. Like:

```twig
{# A\MyByndle:Dir:index.html.twig #}

{% block something %}
   ... default markup goes here ...
{% endblock %}
```

```twig
{# B\MyBundle:Dir:index.html.twig #}

{% extends 'A\MyBundle:Dir:index.html.twig' %}

{% block something %}
    ... something different ...
{% endblock %}
```

This will throw a "reached nested level" error. Read something about missing the scope in the template loader. There are also some fixes out there, but this should be fixed and covered by default I guess?!

For now I made override the controller and action too, and use another filename for the "index" view but this should be possible in terms of overriding bundles.

**Comment by stof** [comment]
the issue with this is that the child bundle is allowed to overwrite templates of the parent bundle. So ``A\MyBundle:Dir:index.html.twig`` is actually loading the template in the B bundle, meaning you are extending yourselves.
you need to be careful when usign bundle inheritance to overwrite things

**Comment by bertoost** [comment]
Yeah, but that should be possible right? :-) I understand the problem. But for PHP (controllers etc.) it is possible too.. To extend and call/use parent functionalities.

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. Since this has been asked a lot of times and there are several issues that ask the same, I've created a new issue to centralize the discussion. That's why I'm closing this and I invite you to join #17557 to help us implement this feature. Thanks!
