### ISSUE TITLE
[Form] sorting options by translated labels

### ISSUE THREAD

**Issue by er1z** [symfony/symfony#15758]
http://stackoverflow.com/questions/32227958/sort-form-field-choices-by-translated-labels

Right now there's no possibility to have choice list sorted without pre-sorting this list manually, earlier. But there's also no possibility to block translator from being invoked in view layer.

**Comment by Tobion** [comment]
You can translate the choices manually as explained on SO. And there is a possibility to disable translation of choices: http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates#added-choice-translation-domain-domain-to-avoid-translating-options
