### ISSUE TITLE
Tab is not aligned with content block in Documentation pages

### ISSUE THREAD

**Issue by irfanmomin** [symfony/symfony#15751]
Please see attached file, there is misalignment between first li of tab and content block. This is found in symfony 2.x documentation:
http://symfony.com/doc/current/book/page_creation.html
and might be possible on other pages too.
Thanks.

![create your first page in symfony the symfony book 2015-09-10 14-44-36](https://cloud.githubusercontent.com/assets/6543265/9784710/9b9aed64-57ca-11e5-912f-b856adb17389.png)

**Comment by Tobion** [comment]
Please open this issue on https://github.com/symfony/symfony-docs
Also mention your brower, OS etc as this is not reproducible on windows + chrome.

**Comment by irfanmomin** [comment]
Ok Thanks.
