### ISSUE TITLE
[Serializer] Introduce the concept of AttributeTransformer

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#15761]
Hi folks!

In a recent project I found that if some define a callback when normalize a object (i.e. Convert a DateTime object to a ISO8601 string) there isn't a easy way to convert the ISO8601 string into a DateTime object, so, I propose to introduce the concept of AttributeTransformers as a replacement of the concept of callbacks.
The idea is very similar to the concept of DataTransformers in the Form component.
We would have a interface that should be implemented by all transformers:

```php
<?php

namespace Symfony\Component\Serializer;

interface AttributeTransformerInterface
{
    public function transform($value);
    public function reverseTransform($value);
}
```

The `transform` method will be called in the normalization (Similar to the current behavior).
The `reverseTransform` will be called in the denormalization.

This will require a new method `AbstractNormalizer::setTransformer($attribute, AttributeTransformerInterface $transformer)`.

IMO this can be implemented in a BC way, the idea is deprecate the concept of callbacks in favor of the concept of attribute transformers.

**Comment by derrabus** [comment]
What would be the difference between a normalizer and a transformer in this context?

**Comment by dosten** [comment]
The normalizer converts a whole object into an array, a transformer convert a single property of this object into any thing you want (i.e A DateTime object into a ISO8601 string). Think that a transformer is an extended version of the "callbacks" provided by normalizers (http://symfony.com/doc/current/components/serializer.html#using-callbacks-to-serialize-properties-with-object-instances) but the callbacks only works in the normalization, if you want to denormalize an array into an object, you can't.

**Comment by derrabus** [comment]
I see. But if I had a normalizer that handles `DateTime` instances and a mechanism to indicate the type of a certain property (like described in #14844 for instance), would I still need those transformers?

**Comment by dunglas** [comment]
We do it the same way as described by @derrabus in API Platform: https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/DateTimeNormalizer.php
