### ISSUE TITLE
[Form][2.8] FormFactory::create ignores getBlockPrefix when generating the name

### ISSUE THREAD

**Issue by craue** [symfony/symfony#15760]
Form type:
```php
use Symfony\Component\Form\AbstractType;

class ModifySettingsForm extends AbstractType {

	public function getBlockPrefix() {
		return 'modifySettings';
	}

}
```
Now calling

1. `$this->get('form.factory')->createNamed('modifySettings', ModifySettingsForm::class)`
1. `$this->createForm(ModifySettingsForm::class)`

in a controller leads to different results when rendering the template. While in the 1st case the form name actually is `modifySettings`, it is `modify_settings_form` in the 2nd case, so the block prefix is ignored and the name is generated using the class name.

**Comment by holloway87** [comment]
The problem is when you provide a FQCN Name to the FormFactory the method getBlockPrefix on the type will never be called.

See FormFactory::createBuilder():
```php
if ($type instanceof ResolvedFormTypeInterface) {
    if (method_exists($type, 'getBlockPrefix')) {
        // As of Symfony 3.0, the block prefix of the type is used as
        // default name
        $name = $type->getBlockPrefix();
    } else {
        // BC
        $typeName = $type->getName();
    }
} elseif ($type instanceof FormTypeInterface) {
    // BC
    $typeName = $type->getName();
} else {
    // BC
    $typeName = $type;
}

if (null === $name) {
    if (false === strpos($typeName, '\\')) {
        // No FQCN - leave unchanged for BC
        $name = $typeName;
    } else {
        // FQCN
        $name = StringUtil::fqcnToBlockPrefix($typeName);
    }
}
```

So the $type is string and the first if block won't set the $name.  In the second if block it will use the else path and directly create the block prefix from the StringUtil class.  In the end the getBlockPrefix Method from the given form type will never be called, there isn't even an instance of it at that moment.

This is pretty annoying if you rely on your form block names (for example in JS).  The workaround for me is to provide the form type instance in the first place until it is fixed.

**Comment by craue** [comment]
Will this be fixed some day? Is it even considered to be a bug?

**Comment by craue** [comment]
Will there be a fix soon?

**Comment by javiereguiluz** [comment]
This bug has also happened to me while updating a Symfony application to 2.8.

**Comment by rainbow-alex** [comment]
Also encountered this, working around this bug with:

```
    /**
     * @return string
     * @see https://github.com/symfony/symfony/issues/15760
     */
    public function getBlockPrefix()
    {
        return $this->getName();
    }
```

**Comment by stof** [comment]
I have an idea to fix it, but I won't be able to work on it before a few days.

And this is indeed important to fix things as it also impacts the form theming for field-specific overwrites, so we must fix it before stable or we would break BC.

**Comment by COil** [comment]
Having the same issue with 2.8 beta1.

**Comment by craue** [comment]
Will this be taken care of before the release of 2.8?

/ping @webmozart

**Comment by fabpot** [comment]
@stof Have you any news about your idea? Would be nice to have a fix before stable.

**Comment by stof** [comment]
@fabpot here you are

**Comment by COil** [comment]
:+1:

**Comment by craigh** [comment]
thanks :+1:
