### ISSUE TITLE
Login via "Remember me" does not regenerate session ID

### ISSUE THREAD

**Issue by s12v** [symfony/symfony#15764]
Is it possible to configure "Remember me" to regenerate session ID, like the normal login does? It seems, by default, it keeps the old ID.

**Comment by Tobion** [comment]
See https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Http/Session/SessionAuthenticationStrategy.php#L22

Also please ask support questions on Stackoverflow. We only use issues for bugs and features.

**Comment by s12v** [comment]
@Tobion, `MIGRATE` is the default strategy: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php#L66
and it does work for normal login, but does not for "Remember me". It seems like a bug.

**Comment by s12v** [comment]
Steps to reproduce in the demo app:
- add "remember me" (config/view)
- open /en/login
- change your session ID to 11111
- log in
- notice session ID has been changed
- change session ID to 22222
- reload page
- you're still authenticated with the same session ID 22222
