### ISSUE TITLE
PdoSessionHandler fails saving serialized opjects

### ISSUE THREAD

**Issue by DerManoMann** [symfony/symfony#15779]
Using the new PdoSessionHandler (instead of the depecated legacy code) we do get errors saving session data since there are \0 bytes in the data.

After some digging I realized that the difference is that the legacy handler does base64 encode/decode and the new handler doesn't.
I suppose this does work with the databases explicitely supported, but it does break things for others.

Was this a concious decision to remove the encode/decode or could this be added again? I'd be happy to create a PR...\

EDIT: I should mention that I am using Sybase with dblib.

**Comment by Tobion** [comment]
See #10991

What does your table schema look like? Did you configure a binary column for the session data as documented in the class?

**Comment by DerManoMann** [comment]
data type is text in sybase and has been ever since. 
I will test binary and blob, thanks.

I am not against either, its just that it is a BC break for me.

**Comment by Tobion** [comment]
See the upgrade file. Thats why we introduced the the legacy one. Feel free to reopen when it doesnt work with binary.
