### ISSUE TITLE
Deprecated YAML::parse method is used

### ISSUE THREAD

**Issue by furious-snail** [symfony/symfony#15774]
When working on my project I get the following notice:
DEPRECATED - The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.
It looks like this happens when a separate, YAML file is used to map objects to database tables for Doctrine.
The solution for me was to modify this Yaml::parse($file) to this Yaml::parse(file_get_contents($file)) in vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php. But there are some other 23 occurrences for the same method usage.  I am not sure if my solution is good enough but maybe someone can submit the needed patch. I am just learning how to use Symfony and I don't want to submit patches until I am 100% sure of what I am doing.

Using:
Symfony 2.7.3
php 5.6.13
OS: Arch Linux

**Comment by Tobion** [comment]
Thanks for reporting this. But this comes from doctrine as you can see in the file path. Also this has been fixed already in doctrine 2.5: https://github.com/doctrine/doctrine2/commit/d3b1bf571bf01bc85d4f6b2732c70d2a44647e10
