### ISSUE TITLE
Add Stopwatch integration for Twig when Templating component is not enabled

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#15785]
ref https://github.com/symfony/symfony/issues/15502#issuecomment-135096440

**Comment by stof** [comment]
The way to implement this in Twig would be similar to the builtin Twig profiler: hooking in before and after nodes of the twig template, which were added for the profiler.

**Comment by fabpot** [comment]
Is it really needed now that we have the Twig profiler?

**Comment by stof** [comment]
@fabpot The Symfony timeline shows other things, for instance Doctrine queries. Being able to see that these queries happen during the rendering of a template is very handy.
The Twig profiling allows to see more details than what we can put in the timeline (putting all blocks in the timeline would be insane), but it does not combine well with other things.

**Comment by fabpot** [comment]
The Twig profiler already put Twig template rendering in the timeline.

**Comment by stof** [comment]
ah sorry, I forgot about the special ProfilerExtension available in the Symfony bridge. then my comment in #15502 was wrong and this can indeed be closed.
