### ISSUE TITLE
Symfony 2.7 PHPParser_Error on Translation extract 

### ISSUE THREAD

**Issue by sv3tli0** [symfony/symfony#15784]
Hi,
I have used some unexpected syntax and the translation extractor failed..

```
if( $someDateTime <= (new \DateTime('today'))){
```
The extractor died with this parser error
```
[PHPParser_Error]                 
Unexpected token ')' on line xxx  
```
I am not quite sure where to report that so don't judge me please :).

**Comment by stof** [comment]
Symfony does not use the PHPParser library to extract translations. I think you issue comes from an extractor provided by a third-party bundle (I know JMSTranslationBundle uses it for instance)
