### ISSUE TITLE
[Yaml] Yaml::dump() inserts unneeded newlines for arrays

### ISSUE THREAD

**Issue by kleijnweb** [symfony/symfony#15782]
I'm sure I'm not the first to notice, and maybe I didn't search well enough, but couldn't find an existing issue regarding this.

`Yaml::dump()` will produce arrays like this:

```yml
parameters:
  -
    name: username
    in: path
    description: 'name that need to be deleted'
    required: true
    type: string
  -
    in: body
    name: body
    description: 'Updated user object'
    required: true
    schema:
      $ref: '#/definitions/User'
```

Instead of the more readable and preferred:

```yml
parameters:
  - name: username
    in: path
    description: 'name that need to be deleted'
    required: true
    type: string
  - in: body
    name: body
    description: 'Updated user object'
    required: true
    schema:
      $ref: '#/definitions/User'
```

I first noticed this using "incenteev/composer-parameter-handler" (no mention of the issue there either), which will produce this:

```yml
# This file is auto-generated during the composer install
imports:
    -
        resource: parameters_base.yml
```

From a parameters.yml.dist which looks like this:

```yml
imports:
    - { resource: parameters_base.yml }
```

Obviously the inlining is configurable in `Yaml:dump`, the extra newline, as far as I can tell, is not.

**Comment by fabpot** [comment]
Both are valid, so there is no bug.

**Comment by kleijnweb** [comment]
Euhr.. Nobody said it was a bug, I said "more readable and preferred". Call it an "improvement".

**Comment by ddanielou** [comment]
Revisiting this after a few years… A quick and dirty workaround is to `preg_replace('/\-\n\s+/', '- ', Yaml::dump($array, 6))`. I used 6 as the inline level, adjust accordingly. Also, can't guarantee it won't mess with more complicated structures.

**Comment by adriangronau** [comment]
Adding to the dirty workaround, using an indent of two spaces aligns the properties of the array item nicely: `preg_replace('/\-\n\s+/', '- ', Yaml::dump($array, 6, 2))`

**Comment by donquixote** [comment]
Another version, which may be more robust in edge cases, e.g. if you have text that would cause false positives in the regex match.
```php
  function ymlDump(mixed $data, $inline = 99, $indent = 2, $flags = Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK): string {
    $marker = \uniqid('_', true);
    $dumper = new class($marker) extends Dumper {
      public function __construct(
        private string $marker,
      ) {
        parent::__construct(2);
      }
      public function dump($input, int $inline = 0, int $indent = 0, int $flags = 0): string {
        return $this->marker . parent::dump($input, $inline, $indent, $flags);
      }
    };
    $yml = $dumper->dump($data, $inline, $indent, $flags);
    $yml = \preg_replace(
      sprintf("@-\n%s +@", \preg_quote($marker, '@')),
      '- ',
      $yml,
    );
    $yml = \str_replace($marker, '', $yml);
    return $yml;
  }
```

**Comment by donquixote** [comment]
Note that this only works well if indentation = 2.
Otherwise it would look inconsistent.
```yml
map:
    submap:
        a: A
        b: B
list:  # which of these is better?
    - a: A
      b: B
    -   a: A
        b: B
```
