### ISSUE TITLE
XLIFF translates to blank if target tag is not set

### ISSUE THREAD

**Issue by janit** [symfony/symfony#15788]
Transifex (https://www.transifex.com) and possibly other tools create XLIFF like this for missing translations:

```
      <trans-unit id="758ec54e430e8ea2e6a1b38b60597aceb1991dc6" resname="Cash">
        <source>Cash</source>
        
        <jms:reference-file line="38">default/foo/bar.html.twig</jms:reference-file>
      </trans-unit>
```

This is missing the `<target>Cash</target>` tag if "Cash" is not translated. Rendering this with

```
<h1>{% trans %}Cash{% endtrans %}</h1>
```

Generates a blank output

```
<h1></h1>
```

where I would expect it to return the value of `<source>` if `<target>` is not defined.

Is this a mismatch in implementation of XLIFF or a conscious decision?

**Comment by aitboudad** [comment]
I think it was implemented (#15604), can you test with the latest version `2.7.4` ?

**Comment by janit** [comment]
Thanks. It looks like a fix. Is this available for 2.6?

**Comment by aitboudad** [comment]
2.6 is not maintained anymore

**Comment by janit** [comment]
Ok, I'll patch it myself then or just upgrade to 2.7 ASAP. Thank you very much!
