### ISSUE TITLE
[Security] Retrieving the authentication manager for the current security token

### ISSUE THREAD

**Issue by Drachenkaetzchen** [symfony/symfony#15806]
I need to find out which authentication provider was responsible for authenticating the security token.

Right now there seems to be no way to retrieve the authentication provider for the current security token.

Use case:
- An API has various authentication variants (LDAP, WSSE Token, FOSUser, HTTP Basic)
- Because it may happen that the same username exists, but may be assigned to different providers, a developer needs to be able to distinguish between the different authentication variants
- The `TokenInterface` does not allow us to find out with which authentication provider the token was generated
- The `AuthenticationProviderManager` does not allow us to check which token was generated by which authentication provider

I propose to modify the `AuthenticationProviderManager` to store the `AuthenticationProviderInterface` so that a developer can retrieve the `AuthenticationProviderInterface` via a call to `AuthenticationProviderManager->getProviderForToken(TokenInterface $token)`.

Another implementation, which may not be BC compatible, would be to extend `TokenInterface` so that it includes the `AuthenticationProviderInterface`.

**Comment by felicitus** [comment]
After overriding the `AuthenticationProviderManager` in my project I realized that there's more work to do. In fact, it doesn't seem to be possible to get the proper provider key as configured in the `security.yml` file.

**Comment by jakzal** [comment]
> developer needs to be able to distinguish between the different authentication variants

Why is this important for you? I don't see how it would matter where the user was returned from, if it's the same user in both sources. 

Have you considered making a distinction in the user class itself (or returning different implementations of users)?

**Comment by felicitus** [comment]
@jakzal this is important because different authentication providers require additional handling for example: Different logout implementations.

**Comment by xabbuh** [comment]
@felicitus Is there no way for you to somehow add more information to your actual `User` objects?

**Comment by felicitus** [comment]
@xabbuh If you tell me how, sure. But the user object is from `FOSUserBundle`, and the [FR3DLdapBundle](https://github.com/Maks3w/FR3DLdapBundle) and [EscapeWSSEAuthenticationBundle](https://github.com/escapestudios/EscapeWSSEAuthenticationBundle) simply return a `FOSUser` with no indication which of those bundles actually fetched the user.

**Comment by javiereguiluz** [comment]
Closing because this discussion stalled a long ago and we haven't receive more questions/petitions about this from other community members. Also, the proposed alternatives could work (although they require to update the User class). Thanks.
