### ISSUE TITLE
error in new toolbar/profiler: "The test "sameas" does not exist."

### ISSUE THREAD

**Issue by ctrl-f5** [symfony/symfony#15811]
Any page where the toolbar is present errors to the following exception:

```
The test "sameas" does not exist. Did you mean "same as" in @WebProfiler/Collector/form.html.twig at line 647
500 Internal Server Error - Twig_Error_Syntax
```

**Comment by stof** [comment]
The quick fix for your project would be to use Twig 1.x instead of the dev version of Twig 2.x.
We need to stop using the deprecated test though.
