### ISSUE TITLE
[Intl] - Not supported timezone (Pacific/Bougainville)

### ISSUE THREAD

**Issue by zender** [symfony/symfony#15810]
"Pacific/Bougainville" is not supported! 

$formatter = \IntlDateFormatter::create(
            'en',
            IntlDateFormatter::MEDIUM,
            IntlDateFormatter::MEDIUM,
            'Pacific/Bougainville'
        );

In this case $formatter returns NULL. If timezone is set to "Europe/Berlin" it works as expected.

Tested on  SF 2.7.3

**Comment by stof** [comment]
Are you using the intl extension or the stub implementation ?

**Comment by zender** [comment]
My bad :(
It is working when using Symfony\Component\Intl\DateFormatter\IntlDateFormatter. Not working with the stub. I am closing the ticket.
