### ISSUE TITLE
[HttpCache] occasionnal 503 error on locking request

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#15813]
I have this problem for a long time now: requests using HttpCache sometimes get caught in [the waiting loop](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L564). After a bit of monitoring I'm sure the request creating the lock doesn't take more than 2s so parallel requests shouldn't return a 503 code.

I couldn't reproduce the problem on my computer, maybe because it's fairly rare (say 0.01% of requests). Couldn't this be due to a missing `clearstatcache` in the [`isLocked`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L107) function?

**Comment by mpdude** [comment]
I have seen this as well, now watching.

**Comment by gnugat** [comment]
It also happens to me. Usually in development when I make a change in the code, clearing the cache fixes the issue.
Somehow I can't reproduce it :(

**Comment by MatTheCat** [comment]
After a blast of 503 I saw some lock files weren't deleted. No idea why for the moment.

**Comment by jakzal** [comment]
> Couldn't this be due to a missing clearstatcache in the isLocked function?

This shouldn't be the case. We use `unlink()` to remove the lock file and it clears the stat cache automatically.

**Comment by MatTheCat** [comment]
I'm pretty sure the problem is caused by `isLocked` returning `true` when it shouldn't. Do you have any idea of how can this happen?

**Comment by mpdude** [comment]
Maybe the lock files are created and then the process holding the lock crashes/terminates for some reason without removing the lock file?

Do you see this for a particular URL only or for different ones?

**Comment by mpdude** [comment]
I've just had one of these occurences and my logs show that at the beginning of the event, the kernel oom-killer terminated an Apache child process (I'm using the prefork MPM with the PHP Apache module).

That would support the hypothesis of stale .lck files lying around after sudden termination of PHP processes.

**Comment by mpdude** [comment]
The fstat cache seems to be an issue as well, see #16312

**Comment by MatTheCat** [comment]
> Do you see this for a particular URL only or for different ones?

All heavily accessed URL using cache.

> see #16312

I'm praying ^^

**Comment by mpdude** [comment]
Even with #16312 we have the possibility that a forcefully terminated process leaves a stale .lck file lying around.

**Comment by MatTheCat** [comment]
I only saw this once so it's not my main concern with this issue.
