### ISSUE TITLE
503 varnish when constructing dev cache since 2.3.32

### ISSUE THREAD

**Issue by Benschumi74** [symfony/symfony#15829]
Since symfony upgraded to 2.3.32, when an url haven't yet built is cache only in dev environnement, our server varnish respond directly a 503.
No error in prod environnement.
Without varnish they're no issue
With Nginx we have "upstream sent too big header while reading response header from upstream", we can solve this but no way in configuring varnish.

**Comment by stof** [comment]
Do you have a monolog handler for chromephp configured in your project ?

**Comment by Benschumi74** [comment]
Yes in the default config_dev.yml in app folder.
<code>

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

</code>

**Comment by jakzal** [comment]
@Benschumi74 does the error disappear if you disable the chromephp handler?

**Comment by stloyd** [comment]
This is due to bug, causing PHP-FPM + NGINX to segfault. See: https://github.com/symfony/symfony/issues/8413

**Comment by jakzal** [comment]
Indeed.
