### ISSUE TITLE
symfony api docs

### ISSUE THREAD

**Issue by rajendradbpb** [symfony/symfony#15834]
Hi ,
basically i am completely new to this platform , but really excited about the ease of fast development with symfony . The only thing i am struggling is the api documentation where we can fine all the basic classes , bundles  and their properties for  easy access . I have gone thorough [symfony official doc](http://symfony.com/doc/current/index.html) , but do we have anything like [As3 doc](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/) or [java doc](http://docs.oracle.com/javase/6/docs/api/)

Thanks

**Comment by L0rD59** [comment]
Hi,

Something like that ? : 

http://api.symfony.com/2.6/index.html

**Comment by rajendradbpb** [comment]
Thank you so much @L0rD59   , this is exactly what I was looking for .
