### ISSUE TITLE
[cache] - cache:clear warmup - rename premission denied on windows fix

### ISSUE THREAD

**Issue by nakashu** [symfony/symfony#15839]
### The problem:

php on windows got problem with renaming the active/running session file storage directory
the default location to store sessions for sylius/symfony apps is /app/cache/<env>/sessions.

When trying to rename the cache folder, with the active/running session php will complain a issue a warning permission denied code 5, as it is lock/blocked/used by php at that time.

It has nothing to do with permissions, as with admin account there are only few "really" protected files on win, and those are system files.

### The partial / more on the spot fix

It can be quick-fixed with the change of configuration in config.yml.
as @dmidz used to set the handler_id => null - the session handling will use the default php sessions, also with they save_paths. -- most of the time outside of the symfony app cache folder.

So the proper config to change for a quick fix on windows is the session.save_path to be outside of the cache folder.
```
#session: ~
session:
    # app/session - instead of app/cache/<env>/sessions
    save_path: %kernel.root_dir%/sessions 
    #handler_id: ~
```

### Symfony - FrameworkBudnle - CacheClearCommand
Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand
method: warmup
lines: ~130 and ~170

the rename problem would reappear in any symfony application, that start the session, while creating the dependency injection container.
The reason is creation of tempKernel inside of the warnup method.
```
$tempKernel->boot();
```
This creates a new Kernel, Di container, register all the bundles etc, and stars session if there are any calls for it. And again it will open file handlers and the problem with renaming will appear.

#### The FIX - probably the best/correct one
Change the end of the method to close the session for the tempkernel, so it will close file handlers.

change this:
```
...
@unlink($tempKernelFile);
...
```
to this:
```
...
$tempKernel->getContainer()->get('session')->save();
@unlink($tempKernelFile);
...
```

### Symfony - disallow session in CLI
- this is another possible fix, but will disallow some weird usecases like, storing some data to session by cli, then storing the session_id somewhere (file/db). 
- on the next run, by cli or whatever get the data from the session by the stored session_id
- but thats like super smelly and kind of stupid.
- also it would be enough to fix the cache clear method.

More on this and the research process can be found here:
[#3071#issuecomment-141682129](https://github.com/Sylius/Sylius/issues/3071#issuecomment-141682129)

**Comment by jakzal** [comment]
> the rename problem would reappear in any symfony application, that start the session, while creating the dependency injection container.

Why would anyone want to do this?

**Comment by nakashu** [comment]
@jakzal :) because they don't think. 
Mostly not on purpose, cause of bug, or inexperienced developer.

In case of Sylius where I found the bug was a bug after refactoring. Call to method in constructor of twig extension, that started the session.

The point still is: 
Currently it is possible to break the cache:clear funtionality by starting a session.
So should it be fixed, and how?

**Comment by nicolas-grekas** [comment]
It really makes no sense to use the session while warming up the container. Making it succeed even in that case is a non-goal to me.
