### ISSUE TITLE
validation_groups not working with One to One relationship

### ISSUE THREAD

**Issue by kristijanhusak** [symfony/symfony#15830]
In older versions (not sure which one), it was possible to set up validation groups in child entity ([MigrantType.php#L31](https://github.com/kristijanhusak/symfony_validation_groups/blob/master/src/AppBundle/Form/MigrantType.php#L31)), which properly triggers validation on parent entity when `@Assert\Valid` is set ([CaseFile#L34](https://github.com/kristijanhusak/symfony_validation_groups/blob/master/src/AppBundle/Entity/CaseFile.php#L34)). 

Validation works properly when no groups are set (lastName in Migrant entity), but when group is provided for assert ([Migrant.php#L29](https://github.com/kristijanhusak/symfony_validation_groups/blob/master/src/AppBundle/Entity/Migrant.php#L29)), validation is not working.

Here's the repo with issue: https://github.com/kristijanhusak/symfony_validation_groups

How to test:
- download repo
- composer install
- php app/console server:run
- localhost:8000 in browser
- submit the form

Expected behavior:
Both first and last name should not be blank.

What happens:
Only last name is validated properly, because it has no group set in Assert\NotBlank.

When you enter something for last name and submit, you can see that validation_groups are properly set on child entity.

I know it works when validation_groups are set on the parent entity, but that leads to bad code structure.

**Comment by deguif** [comment]
You could set the `cascade_validation` option to `true` on the `CaseFileType` form type and it should work.
PS: `@Assert\Valid` is deprecated and will be removed in 3.0

**Comment by kristijanhusak** [comment]
Yeah, that works. I tried using that option, but set it on `additionalInformation` as option, not as option for form.

How will `@Assert\Valid` work from 3.0?

**Comment by stof** [comment]
@deguif ``@Assert\Valid`` is not deprecated at all. the deprecated legacy system is precisely ``cascade_validation``.

@kristijanhusak validation groups must be set on the root form. ``@Assert\Valid`` is propagating the validation with the same groups.
Nested forms don't call the validator again themselves

**Comment by kristijanhusak** [comment]
@stof If `cascade_validation` is deprecated, how can we force this kind of validation?

In docs it says:
```
This cascades only the validation but not the use of the validation_groups option on child forms.
```

**Comment by stof** [comment]
@kristijanhusak ``validation_groups`` is never used in child forms, as they are not launching the validator themselves.

**Comment by sarcher** [comment]
I am encountering this problem as well with the 2.8 branch (not sure if present in 2.7). Implementing according to the [documentation here](http://symfony.com/doc/master/book/validation.html#validation-groups) does not result in the group from the root form being cascaded to the child.

For example, if I set `validation_groups` to `somegroup` on the root form, and have the `@Assert\Valid` on a one-to-one property, and then have a constraint like `@Assert\NotNull(groups={"somegroup"})` on a field of the embedded object, that field is not validated.

The only workaround I've been able to find is to use the deprecated `cascade_validation` option. I've tried a variety of combinations without much luck.

**Comment by xabbuh** [comment]
I am closing here as this is the expected behvaiour. If you want to validate constraints from the default group as well as constraints from another group to be validated, you need to pass them explicitly (`['Default', 'name_required]` for the example given).

@sarcher Your issue is a bit different than what was reported with this issue initially. If you are still able to reproduce it (best by making some changes to the Symfony Standard Edition), I would be happy to see you opening a dedicated issue and try to solve the bug based on your fork. Thank you!
