### ISSUE TITLE
[Console] Provide a method to translate Descriptors

### ISSUE THREAD

**Issue by enzolutions** [symfony/symfony#15842]
Working in project Drupal Console, I notice there are some string elements that can't be translated

Was easy overwrite methods **getDefaultInputDefinition** and **getLongVersion**

But translate Descriptors like TextDescriptor include to much effort and maybe an issue between version

You can see the re-implementation I have to do for Drupal Console project https://github.com/hechoendrupal/DrupalConsole/pull/880/files#diff-2f8b0158678648c4866cdd40cf90298fR1

Could you consider a way to enable translation support for general elements.

**Comment by fabpot** [comment]
We do not provide translation mechanism for non end-user facing features, like the console, which is only used by developers.

**Comment by Tobion** [comment]
I'd say it's not worth providing translations for developer messages and a nightmare to maintain. The symfony doc is also only maintained in English now: http://symfony.com/blog/discontinuing-the-symfony-community-translations

So I'm :-1:

**Comment by xabbuh** [comment]
I am also :-1: for the reasons given.
