### ISSUE TITLE
acl:set - Why do I need to specify an ID with --class-scope?

### ISSUE THREAD

**Issue by felicitus** [symfony/symfony#15841]
When using `acl:set` with `--class-scope`, it seems that I need to specify an ID:

```
app/console acl:set --class-scope --user=PartKeepr/AuthBundle/Entity/User:admin VIEW PartKeepr/PartBundle/Entity/Part

                                                                
  [InvalidArgumentException]                                    
  The code "PartKeepr/PartBundle/Entity/Part" is not supported  
                                                                
```

As it is a class scope, it shouldn't be necessary to specify an ID.

**Comment by dunglas** [comment]
This is a limitation of the underlying ACL component. Moreover you must ensure that an entry is present for every entities in the ACL table.

> When using the class scope, you must pass a valid id for the class type (that's why the command uses Acme/MyClass:42 instead of Acme/MyClass). Moreover, the permissions are not applied to all the objects of the same class but only to the objects of this class already present in the ACL table.

http://symfony.com/blog/new-in-symfony-2-6-the-acl-set-command
