### ISSUE TITLE
[Console] Update console help or fix argument parsing for the command

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#15845]
https://github.com/symfony/symfony/blob/73c7eae31757f6a6012aefc7091a6551665a66e1/src/Symfony/Component/Console/Application.php#L258 says that options should come before the command (`console [options] command [arguments]`) but this does not actually work if you pass an option with a value and no equal sign, like `console -d dValue command` as it will take dValue as the command name.

I think either docs should be fixed or ideally the parsing improved so that it doesn't do this, but that might not be realistic since the parsing depends on the command config.

(Forwarded issue from https://github.com/composer/composer/issues/3139)

**Comment by WouterJ** [comment]
The help message was wrong and is fixed by https://github.com/symfony/symfony/pull/13545 . 2.3.26+, 2.5.11+, 2.6.5+ and 2.7+ are now showing `command [options] [arguments]`, which is the correct order
