### ISSUE TITLE
2.8 Web Debug Toolbar Error with no logout firewall key

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#15853]
When using the new 2.8 web debug toolbar, the `Collector/security.html.twig` template uses the `logout_path()` Twig function to print the logout key. But, if you don't have a `logout` key configured, this will fail with something like:

>
An exception has been thrown during the rendering of a template
("No LogoutListener found for firewall key "main".") in @Security/Collector/security.html.twig
at line 39.

I don't know if we can detect whether there is a logout listener in the firewall or not, so we may need to remove this link.

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
I need some help trying to solve this issue. I tried to use a `try .. catch` block in the `SecurityDataCollector` and generate the logout URL directly using the `LogoutUrlGenerator`. But that class depends on lots of other services, so I don't know what to do.

**Comment by weaverryan** [comment]
@javiereguiluz maybe create a pull request with either the removal of the logout link or with some WIP/experimental "fix" to get some feedback. Unfortunately, I'm also not sure what to do initially.

Thanks for the quick reply on this, even though it's not mission critical yet :)

**Comment by javiereguiluz** [comment]
This was my very WIP attempt at fixing this:

```php
use Symfony\Component\Security\Http\Logout\LogoutUrlGenerator;

// ...

public function collect(Request $request, Response $response, \Exception $exception = null)
{
    if (null === $this->tokenStorage) {
        $this->data = array(
            // ...
            'logout_url' => null,
        );
    } elseif (null === $token = $this->tokenStorage->getToken()) {
        $this->data = array(
            // ...
            'logout_url' => null,
        );
    } else {

        try {
            $logoutUrl = new LogoutUrlGenerator($requestStack, $router, $securityTokenStorage);
        } catch(\Exception $e) {
            $logoutUrl = null;
        }

        $this->data = array(
            // ...
            'logout_url' => $logoutUrl,
        );
    }
}
```

But I can't access to $requestStack, $router, $securityTokenStorage from SecurityDataCollector :(

**Comment by jvasseur** [comment]
This wouldn't work anyway, you need to call the registerListener method on the LogoutUrlGenerator for each Logout listener. This is usually done by security extension (https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L340).

**Comment by weaverryan** [comment]
The only way I can see is to inject the `security.logout_url_generator` service into the SecurityDataCollector. It's pretty straightforward, and doesn't violate our BC policy (though adding optional arguments to public methods "should be minimized").

**Comment by javiereguiluz** [comment]
@weaverryan in #15861 I'm trying a solution based on your suggestion. Thanks!
