### ISSUE TITLE
[TwigBridge] `is_granted` should handle AuthenticationCredentialsNotFoundException

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#15863]
If you accidentally use `{% if is_granted('ROLE_EMPLOYEE') %}` in a view that does not have a Firewall/TokenStorage enabled the AuthorizationChecker throws an exception:
```
new AuthenticationCredentialsNotFoundException('The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.');
```

The solution is to use this:
```twig
{% if app.security.token is not null and is_granted('ROLE_EMPLOYEE') %}
```

Wouldn't it be better to just handle this exception inside SecurityExtension::isGranted and simply return `false`?

**Comment by ruudk** [comment]
Like this:

```php
    public function isGranted($role, $object = null, $field = null)
    {
        if (null === $this->securityChecker) {
            return false;
        }

        if (null !== $field) {
            $object = new FieldVote($object, $field);
        }

        try {
            return $this->securityChecker->isGranted($role, $object);
        } catch(AuthenticationCredentialsNotFoundException $exception) {
            return false;
        }
    }
```

**Comment by jaytaph** [comment]
With your fix, there would not be any difference between an error on having a non-existing firewall or an actual (valid) non-grant. 

A developer would most likely spend their time trying to figure out why the given role isn't available (as this is what happens from the template POV).

**Comment by ruudk** [comment]
Sure, but should a template designer worry about checking `app.security.token is not null`?

**Comment by iltar** [comment]
There should always be a token available (be it anonymous). This is fixed by adding `anon: ~` in your firewall. The only locations where it won't work, are error pages as the token might not be available at that point. Maybe for error pages a different solution can be found.

**Comment by ruudk** [comment]
Exactly, this happened on an error page.

**Comment by iltar** [comment]
If it's just for error pages, I suggest a different solution. Maybe you could overwrite the controller to set a custom yourself if non is present?

**Comment by lyrixx** [comment]
duplicates of https://github.com/symfony/symfony/issues/10159 ?

**Comment by xabbuh** [comment]
I agree with @lyrixx.
