### ISSUE TITLE
[console] CommandTester dos not work with phpunit versions > 4.1.* due to the way output buffering is managed.

### ISSUE THREAD

**Issue by localgod** [symfony/symfony#15877]
If you run the example code:
```php
use Acme\Console\Command\GreetCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class ListCommandTest extends \PHPUnit_Framework_TestCase
{
    public function testExecute()
    {
        $application = new Application();
        $application->add(new GreetCommand());

        $command = $application->find('demo:greet');
        $commandTester = new CommandTester($command);
        $commandTester->execute(array('command' => $command->getName()));

        $this->assertRegExp('/.../', $commandTester->getDisplay());

        // ...
    }
}

```

with phpunit in verbose mode you get this error:
```
Test code or tested code did not (only) close its own output buffers
```
This might be a phpunit issue.

Whatever the cause, the inability to test your console application with newer versions of phpunit is not optimal.

**Comment by stof** [comment]
The CommandTester does not use any output buffer.
Are you sure this is related to this test ? When trying this locally, I don't get any warning from PHPUnit (I'm using PHPUnit 4.8.9)

**Comment by WouterJ** [comment]
I used the exact same code in a Symfony 2.7 application with PHPunit 4.8.3 and the tests run succesfully.

You can view my code at [GitHub](https://github.com/WouterJ/symfony-standard/commit/4e97135c9e5d130dfacb97b33f1c444b9b2dae59) and the test result at [Travis](https://travis-ci.org/WouterJ/symfony-standard/builds/83541058). Can you please edit the code to include the most minimal code that produces this error?

**Comment by jakzal** [comment]
Closing as @WouterJ confirmed this works and there's no feedback from the reporter. 

@localgod feel free to reopen if you manage to provide code that reproduces the problem.

**Comment by localgod** [comment]
I will have time to look into this in a couple of weeks. Ill get back to you if I still encounter the problem with a more complete example.
