### ISSUE TITLE
request parameters is not available in route conditions

### ISSUE THREAD

**Issue by guilemos** [symfony/symfony#15876]
Hi guys! I'm trying to match some simple logic in my route condition using request bag parameters:

conditions: "request.attributes.get('institute') == 663"

This condition always returns false.

I notice that request, query and attributes bag are empty when UrlMatcher try to match the condition. In the controller, bags are available as expected.
```php
namespace Symfony\Component\Routing\Matcher;

class UrlMatcher implements UrlMatcherInterface, RequestMatcherInterface
{
...

public function matchRequest(Request $request)
    {
        $this->request = $request; // <<-- REQUEST BAGS ARE EMPTY. WHY?

        $ret = $this->match($request->getPathInfo());

        $this->request = null;

        return $ret;
    }
...
```

Thank you!

**Comment by Tobion** [comment]
Because when evaluating the condition (in the routing), the matched routing placeholders are not available yet. The request attributes are filled after the matching has happened. So they cannot be available the moment you are matching.

**Comment by guilemos** [comment]
Thank Tobion! I get it!

But, there's a reason for attributes are filled after matching? Ain't more interesting if it were available on the matching once we have the request object?

**Comment by david-vde** [comment]
@guilemos Hello! Did you find a solution for this issue ? I encounter the same problem on symfony 3.4. Quite annoying.

Thanks
