### ISSUE TITLE
Deprecate SimpleFormAuthenticationListener and SimplePreAuthenticationListener

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#15873]
Should be done in 3.1 to allow people to have more time to upgrade (see https://github.com/symfony/symfony/pull/14673#issuecomment-142533951)

**Comment by Tobion** [comment]
Why not 3.0? Doing it in 3.1 will give them _less_ time to upgrade.

**Comment by fabpot** [comment]
Wrote too fast. My idea was to deprecate them in 3.0 and remove them in 3.1.

**Comment by javiereguiluz** [comment]
Closing as fixed:

* SimpleFormAuthenticationListener was deprecated in Symfony 4.2: https://github.com/symfony/security/blob/4.2/Http/Firewall/SimpleFormAuthenticationListener.php#L32
* SimplePreAuthenticationListener was deprecated in Symfony 4.2: https://github.com/symfony/security/blob/4.2/Http/Firewall/SimplePreAuthenticationListener.php#L34
