### ISSUE TITLE
[security] Remove dependency on security-core from security-csrf

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#15872]
I'm currently trying to use symfony/form on its own and ran into the folowing problem. I need CSRF protection for the forms so I added symfony/security-csrf to my project. However this also installs symfony/security-core which I don't need at all.

I've looked around and the only classes from security-csrf which use something from security-core are `Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator` and `Symfony\Component\Security\Csrf\Exception\TokenNotFoundException`.

I want to implement `Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface` on my own anyway so I don't need the `UriSafeTokenGenerator` and the exception inheritance probably doesn't matter much.

So can the dependency be removed?

**Comment by ste93cry** [comment]
👍 I was watching too the `security-csrf` standalone package but I did not find any dependency on the `security-core`. There is a token storage that uses the `Session` class from the `HttpFoundation` component, but nothing more, at least from what I saw.

**Comment by ste93cry** [comment]
I saw that the dependency on the `security-core` package was removed, but the `composer.json` still requires it (at least on master). Is it an oversight?

**Comment by fabpot** [comment]
The PR was not merged.

**Comment by ste93cry** [comment]
You're right, sorry for not noticing it before. Is there any option we can get rid of the dependency of the package on `Symfony\Component\Security\Core\Exception\RuntimeException` for a new Symfony version (3.2 maybe?)

**Comment by enumag** [comment]
3.2 certainly not. Maybe 4.0? @fabpot?

**Comment by Hikariii** [comment]
https://github.com/symfony/symfony/pull/16494 is a PR on Symfony 2.8.
I gather this must be updated to a PR on 4.0?

**Comment by chalasr** [comment]
As proven in #16494, this would mean breaking BC. Closing.
