### ISSUE TITLE
[TwigBundle] FileSystemLoader::findTemplate BC with new argument

### ISSUE THREAD

**Issue by Moinax** [symfony/symfony#15885]
Why is there a new unused/undocumented argument $throw in version 2.7.4 on FileSystemLoader::findTemplate method ?

See https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/TwigBundle/Loader/FilesystemLoader.php#L66

**Comment by stof** [comment]
because this method is overwritten from Twig, and so the signature must be compatible with the Twig one. This is necessary for Twig 2.x compatibility.

**Comment by Moinax** [comment]
Ok, thank you for the explanation, but it still missing in the phpdoc and a small comment to explain this should be much appreciated. 

Regards, 

Jérôme

**Comment by stof** [comment]
Well, this is a method inherited from the parent. We don't duplicate doc in such case.
