### ISSUE TITLE
symfony 2.7.4 is slower than 2.7.3 in vagrant + virtualbox

### ISSUE THREAD

**Issue by zywj** [symfony/symfony#15883]
I had moved the vendor dir, cache dir and log dir out of the vagrant share folder as same as 2.7.3 

the time needs in two version 
2.7.3  < ~100ms
2.7.4  > ~500ms

**Comment by Alban-io** [comment]
I think you should install a profiler such as blackfire.io to find more information on your problem.

**Comment by stof** [comment]
having a profile before and after to see the comparison would indeed help understanding what is slower

**Comment by jakzal** [comment]
ping @ZYWJ

**Comment by javiereguiluz** [comment]
The latest 2.7 version is 2.7.9. @zywj could you please update your app and confirm if the reported slowness has been fixed? Thanks!

**Comment by zywj** [comment]
Oh, I'm very sorry. Now, I'm using VMWware to instead the virtualbox, and working in VM environment now.  
Sorry again.
