### ISSUE TITLE
[Validator] URL validation fails if there is no slash after domain prefix and before query string

### ISSUE THREAD

**Issue by smilesrg** [symfony/symfony#15891]
For example:
http://www.anyurl.com/?query=1 - valid URL
http://www.anyurl.com?query=1 - invalid URL (missing slash after ```.com``` and before ```query=1```)

I'm not sure if last url is valid according to RFC:
https://tools.ietf.org/html/rfc3986#page-16
https://tools.ietf.org/html/rfc3986#page-22

**Comment by SoboLAN** [comment]
Just to be extra clear, please answer these 2 questions:

1). Are you using `Symfony\Component\Validator\Constraints\Url` for validation ?
2). What Symfony version are you using ?

**Comment by smilesrg** [comment]
1. Yes
2. 2.5.12

**Comment by xabbuh** [comment]
Symfony 2.5 is not supported anymore. Do you experience the same behaviour with Symfony 2.7?

**Comment by jakzal** [comment]
It's still the case in both 2.3 and 2.7. The current behaviour is actually covered by tests (cases added in #3422).

**Comment by smilesrg** [comment]
@jakzal Thanks! I really didn't have time to reproduce it on both 2.3 and 2.7.
@SoboLAN @xabbuh please take a look at the PR

**Comment by zorji** [comment]
The issue is still not fixed. I left a comment in https://github.com/symfony/symfony/pull/16259
