### ISSUE TITLE
Form fields associated with an array property of an entity not validating with validation_groups

### ISSUE THREAD

**Issue by alanhartless** [symfony/symfony#15896]
This is similar to a couple other bug reports but they were closed and seemed to be related with objects associated with entity properties.  So hoping this is a different issue and fixable.

I have an entity, `Page()` that has an array property, `$settings`.  Settings is simple array because it's keys may be dynamic and thus can't be it's own entity with fixed properties.  

I have a `PageType()` form class that has a `SettingsType()` form embedded.  The `PageType()` has defaults defined as 

``` php
$resolver->setDefaults(array(
            'data_class' => 'Acme\PageBundle\Entity\Page',
            'validation_groups' => array(
                'Acme\PageBundle\Entity\Page',
                'determineValidationGroups'
            )
        ));
```

The `SettingsType()` has fields that are using the `constraints` options. 

Validation is happening in `Page::loadValidatorMetadata()` for the main entity but no matter what I've tried, Symfony seems to ignore the constraints for the fields in `SettingsType()`

I've tried various uses of `cascade_validation` which I understand is deprecated and tried using the `Assert\Valid()` for the `$settings` property but still the constraints are ignored.  If I remove the use of `validation_groups`, the constraints in `SettingsType` work.  But with it they are ignored.

Wondering if this is an issue with the use of an array property that is not mapped to it's own entity and thus it's own `loadValidatorMetadata()` function? Is there a way to work around this as like I said, I can't make `$settings` it's own entity due to the need for dynamically set keys.

Thanks!
Alan

**Comment by alanhartless** [comment]
My work around was to dump using validation_groups in favor of using a Callback constraint and handling the validation myself.  This is kind of a pain in the butt thought so hopefully there is an easy fix or I'm just doing something stupid and wrong!

Thanks!

**Comment by stof** [comment]
Only the root form calls the validator. Validating nested objects of the graph is then handled by the validator itself, based on the presence of ``@Assert\Valid`` on properties containing nested objects (if it is not there, it does not go validating it).

**Comment by alanhartless** [comment]
If I'm understanding correctly, I tried that but it still wouldn't catch the validations on the nested objects (in this case underlying array).

In the root form associated with the main entity, I had the equivalent of 

```
$metadata->addPropertyConstraint('settings',  new Assert\Valid());
```

In the entity's `loadValidatorMetadata()` function but that still ignored the `constraints` option for the fields in the `SettingsType` form type.

**Comment by xabbuh** [comment]
same as #15830?

**Comment by xabbuh** [comment]
When you validate the root form using the `Acme\PageBundle\Entity\Page` and `` validation groups, the constraint added to the nested `$settings` array must be in either of these groups too. I am closing this issue as what you describe is indeed intended behvaiour.
