### ISSUE TITLE
The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL

### ISSUE THREAD

**Issue by bnd170** [symfony/symfony#15897]
Hi community.

I'm having problems with Symfony2 in version 2.7.

I'm using FOSUserBundle provider of users.

The fact is that I have a sidebar where the user information is displayed when logged in, and if not I be the login form. In addition to filtering content dependent on whether the user is logged in or not.

To check if the user is logged using the function of the official documentation of Symfony2.
```
$this-> get ('security.authorization_checker') -> isGranted ('ROLE_USER')
```
And when you run the project in production, the whole server goes down and throws me log production between 60 and 120 lines like this:
```
[25/09/2015 17:01:42] request.CRITICAL: Uncaught Exception PHP Symfony \ Component \ Security \ Core \ Exception \ AuthenticationCredentialsNotFoundException. "The token contains no authentication token storage One possible reason May Be That there is no firewall for This URL configured. "at ...
```

I'm not provide documentation because, as I remember I have not made significant changes to settings beyond Symfony bundles incorporate some as KnpSnappy and the project is more than two years working with Symfony2.

If further documentation needed to resolve the error please ask me.

**Comment by iltar** [comment]
Please check IRC (freenode.net#symfony)/stack-overflow for questions or help, this issue tracker not for general question.

Usually IRC has enough people to help around.

**Comment by xabbuh** [comment]
Closing for the reason given by @Iltar.

**Comment by chrislebaron** [comment]
bnd170, were you able to find an answer for this?

**Comment by jmros** [comment]
@bnd170 any response¿ in symfony 3

**Comment by thilinadinith** [comment]
i also get the same issue. expect to have an answer without closing the issue

**Comment by linaori** [comment]
Please use one of the appropriate support channels: https://symfony.com/support

**Comment by colesnic89** [comment]
In my case it was usage `$this->security->isGranted()` in Console Command. So `$this->security->getToken()` returns `NULL`
