### ISSUE TITLE
[RFC] Be able to define users providers in two (or more) files

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#15894]
Right now, It's not possible to define users providers in two (or more) files.

It's caused by https://github.com/symfony/symfony/blob/06b493804632ca34eb089bbe2cd20f31bb9e32ed/src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php#L374

It was introduced by https://github.com/symfony/symfony/commit/0b8fef234724cb4cb3a4ab37466efe193a6c7708#diff-11df2572a68def120496f57a8eeff7afR184 (looks like there was no PR)

Actually, I don't really understand the rational behind this constraint.
I have commented this line in my project, and everything works fine.

The PR is quite easy, I can submit it as soon as you're OK with that.

**Comment by stof** [comment]
this line is about firewalls, not about user providers.

The reason for using this feature for firewalls is that the order of firewalls is a critical part of the configuration, and adding a new firewall in a subsequent file does not allow to control where it is inserted. The config of an existing firewall can be replaced entirely in subsequent files though

**Comment by lyrixx** [comment]
> this line is about firewalls, not about user providers.

oups, I fixed the link.

Anyway, I'm talking about user provider and not firewall. I understand it can be weird for firewalls. But I think it's safe for user providers as there is no orders.

**Comment by stof** [comment]
there is still one case: the first provider is used by default by firewalls if you don't configure which one they should use.

**Comment by lyrixx** [comment]
Indeed. But in that case, Users can safely configure it by adding the `provider` key. And so it becomes deterministic.

**Comment by iltar** [comment]
This would solve a lot of problems for me (if this is what I think it is). One of our shared bundles configures a lot of stuff for applications regarding logins so the applications don't have to define that all by them self as the config is usually the same. But in order to "merge" this, we need the following hack:

```php
        $container->prependExtensionConfig('security', [
            'providers' => [
                'chain_provider' => [],
                'hostnet'        => [],
                'in_memory'      => []
            ]
        ]);
```

This requires us to implement an extension file in our `AppBundle`, which needs to be solved as we still have to configure app stuff like this.
