### ISSUE TITLE
[2.7] No deprecation triggered for deprecated empty_value option

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#15908]
From `UPGRADE-2.6.md`:

> * The "empty_value" option in the types "choice", "date", "datetime" and "time"
>   was deprecated and replaced by a new option "placeholder". You should use
>   the option "placeholder" together with the view variables "placeholder" and
>   "placeholder_in_choices" now.
>
>   The option "empty_value" and the view variables "empty_value" and
>   "empty_value_in_choices" will be removed in Symfony 3.0.
>
>   Before:
>
>   ```php
>   $form->add('category', 'choice', array(
>       'choices' => array('politics', 'media'),
>       'empty_value' => 'Select a category...',
>   ));
>   ```
>
>   After:
>
>   ```php
>   $form->add('category', 'choice', array(
>       'choices' => array('politics', 'media'),
>       'placeholder' => 'Select a category...',
>   ));
>   ```
>
>   Before:
>
>   ```
>   {{ form.vars.empty_value }}
>
>   {% if form.vars.empty_value_in_choices %}
>       ...
>   {% endif %}
>   ```
>
>   After:
>
>   ```
>   {{ form.vars.placeholder }}
>
>   {% if form.vars.placeholder_in_choices %}
>       ...
>   {% endif %}
>   ```

There is no deprecation notice triggered when still using this option in 2.7.

**Comment by stof** [comment]
Well, triggering deprecations when accessing the array keys would be a huge pain: it means we would have to stop using an array for ``FormView::vars``

**Comment by WouterJ** [comment]
@stof I'm sorry for the confusion, it was talking more about configuring the `empty_value` option. In such case, there is no deprecation notice at the moment while it is a deprecated setting.

Even more, the current implementation means we can have both an `empty_value` and `placeholder` option with different values. In such cases, the `empty_value` option is simply silently ignored.

**Comment by stof** [comment]
@WouterJ if we don't have a deprecation warning when you pass the option, it is a mistake though.

**Comment by xabbuh** [comment]
see #15945 

Status: Reviewed
