### ISSUE TITLE
[Yaml Component] 

### ISSUE THREAD

**Issue by pelallemant** [symfony/symfony#15937]
Hi,

When I use the YAML Component in my project, I use `$dumper = new Symfony\Component\Yaml\Dumper();`

Then I do `$dumper->dump($myarray, 2)`.

When `$myarray` is not empty, the YAML file generated is nicely indented.

When `$myarray` is empty, the YAML file generated is `{    }` instead of an empty file. 

I think it's a forgotten feature.

**Comment by xabbuh** [comment]
Thank you for reporting this issue @pelallemant. Please see #9870 for some explanations of the current behaviour.

**Comment by xabbuh** [comment]
see #17728
