### ISSUE TITLE
Annotation for Validation Payload not working as expected

### ISSUE THREAD

**Issue by lbayerl** [symfony/symfony#15971]
I tried several ways to get the annotations working as mentioned here: http://symfony.com/doc/current/cookbook/validation/severity.html

As no one answered to this on StackOverflow I thought it might be a bug as well? Did someone successfully try this?

http://stackoverflow.com/questions/31701947/how-to-use-symfony-2-6-validations-payload-with-annotation#

**Comment by stof** [comment]
I posted the answer on SO
