### ISSUE TITLE
[RFC] Remove the distinction between api and non-api classes

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15977]
We introduced ``@api`` in the early days of Symfony to distinguish the public API, safe to be used thanks to BC, and less safe APIs.
However, none of the APIs introduced after Symfony 2.3 has been tagged as ``@api`` AFAIK. And on the other hand, we became much better at writing BC layers to maintain compatibility until the next major version.
Our BC policy is also lying about its goal: what it describes in the ``Regular`` column is a policy which does not provide BC (only partial BC). And in practice, we are much stricter in our code than what is described in this document (i.e. we provide BC for all classes, not only ``@api`` classes), defeating the ``@api`` distinction.

IMO, the real distinction we should have is between normal APIs (where BC is provided) and internal APIs (tagged as ``@internal``), which should not be used by people using Symfony (if they call an internal method themselves, they are on their own regarding upgrades).
Note that we already have the concept of internal APIs in Symfony (for instance callback functions needing to be public for PHP 5.3 compat, and turned into private ones in 3.0).

What do you think @symfony/deciders ?

**Comment by Tobion** [comment]
:+1: to remove api tags as they are unmaintained and only distinguish between `@internal` and the rest.
Also the notion of api tags is kinda ambiguous as there is no defined process of what and when is considered "api".

**Comment by xabbuh** [comment]
:+1: Not distinguishing makes it more clear and we can still add some classes as internal.

**Comment by fabpot** [comment]
:+1: The concept is interesting but it needs maintenance, which we never did. And as pointed bu @stof, we are getting better at keeping BC almost everywhere, so it's not as needed as it once was.

**Comment by Tobion** [comment]
Is it enough to remove the tags in 2.8? Or also since 2.3?

**Comment by stof** [comment]
Well, I suggest cleaning it in all branches, to avoid confusion.

And then, the doc should be updated to stop talking about this distinction (dropping it is mostly a job for the doc team, as this is where the concept is used)

**Comment by fabpot** [comment]
Doing it in 2.3 sounds good to me.

**Comment by Tobion** [comment]
I bet this will be a huge merging pain.

**Comment by stof** [comment]
@Tobion removing it in all branches means we have the merging pain only once, rather than having merge conflicts during the whole maintenance lifetime each time a phpdoc update is propagated to newer branches.

**Comment by xabbuh** [comment]
see symfony/symfony-docs#5735 for the docs changes

**Comment by dunglas** [comment]
:+1: but if we do that maybe should we add `@internal` on more classes (I think to normalizers in the Serializer Component or extractors in PropertyInfo for instance).

**Comment by fabpot** [comment]
@dunglas I think that's the whole idea: instead of whitelisting the API, we need to blacklist internal classes. We've done that already for some classes during the 2.8 development cycle and we need to do more of that.

**Comment by stof** [comment]
@dunglas normalizers are *not* an internal API. they are the extension point we provide to users, and so we expect to see implementations of the interface outside the component.
Internal classes/interfaces are classes/interfaces that a user should not be using directly when using Symfony. Any interface used to provide an extension point does not qualify for that.

**Comment by dunglas** [comment]
I'm not speaking about the interface but about implementations such as `ObjectNormalizer`. It's API can change in the way described by the old BC promise (not marked as `@api`).

**Comment by stof** [comment]
@dunglas no. It is simply that it was merged in Symfony after the last time we maintained the ``@api`` tags. this is one of the reason of the removal: our current set of ``@api`` tags is totally meaningless as it is far from being complete.

**Comment by stof** [comment]
and this class is still meant to be used by users of the component, so it is not internal.
