### ISSUE TITLE
Twig cache warmup missing / not being processed

### ISSUE THREAD

**Issue by iquito** [symfony/symfony#15982]
I use a very basic vanilla Twig configuration and just started creating my first Twig templates, and noticed my templates are not being cached.

When running ``php app/console debug:container --env dev --show-private --tag kernel.cache_warmer`` the TemplateCacheCacheWarmer service does not appear - this is also the case when reinstalling Symfony without doing any configuration or changes at all. When running ``php app/console cache:warmup`` in a new project, the twig directory in /app/cache/dev (or /app/cache/prod) is not being created and no templates are "warmed up".

Does template caching have to be enabled or configured? I could not find anything in the documentation or anywhere else on how to enable template warmup caching.

**Comment by yethee** [comment]
Seems, this issue related to #15034
You can try register `TwigBundle` before `FrameworkBundle` in `AppKernel::registerBundles()` of your project.

**Comment by iquito** [comment]
Thanks, that worked!

Is there any downside to loading TwigBundle before FrameworkBundle?
