### ISSUE TITLE
Unexpected result when calling setSharedMaxAge(0) on Response

### ISSUE THREAD

**Issue by wimvds** [symfony/symfony#15992]
Could somebody explain the reasoning behind the following? -> https://github.com/symfony/symfony/commit/053d83f557b53b61b4fb4bfa5b7522549a7e3859

I had a custom response, did a setPrivate call and afterwards setMaxAge & setSharedMaxAge to 0. I noticed my response got public because (when I looked into it) setSharedMaxAge does a setPublic call (which was merged in the PR mentioned above). I think this is a bit weird (the function does not do what you'd expect without looking at the code). Any thoughts on this?

**Comment by jameshalsall** [comment]
The notion of a "shared" cache is public, like an edge node in a CDN. When you set a shared TTL or max age then you're opting in to make the resource publicly cacheable. 

I don't think this is unexpected, unless I'm missing something.

**Comment by xabbuh** [comment]
I agree, if you want to have it private, just do not call `setSharedMaxAge()`.
