### ISSUE TITLE
[RFC] Improving the new command console styling

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#16000]
### Problem

The new Symfony console styles requires us to do the following:

```php
use Symfony\Component\Console\Style\SymfonyStyle;
// ...

protected function execute(InputInterface $input, OutputInterface $output)
{
    $output = new SymfonyStyle($input, $output);  // <-- this is the problem

    $output->title('...');
    $output->table('...');

    // ...
}
```

Overriding the original `$output` variable is a really bad practice, it introduces a lot of issues in some commands and it's ugly.

### Solution

I want to change the new `$output` variable by a new variable. Here are some suggestions. Please tell me which one you prefer or provide an alternative. Thanks!

```php
$helper = new SymfonyStyle($input, $output);

$helper->title('...');
$helper->table('...');

// ...

$iohelper = new SymfonyStyle($input, $output);

$iohelper->title('...');
$iohelper->table('...');

// ...

$io = new SymfonyStyle($input, $output);

$io->title('...');
$io->table('...');

// ...

$formatter = new SymfonyStyle($input, $output);

$formatter->title('...');
$formatter->table('...');

// ...
```

**Comment by javiereguiluz** [comment]
Any suggestion for the new variable name? I'm about to start redesigning the last commands. Thanks!

**Comment by iltar** [comment]
Just a wild suggestion:
```php
$render = new SymfonyStyle($input, $output);

$render->title('...');
$render->table('...');

```

**Comment by javiereguiluz** [comment]
@iltar thanks for the proposal, but I'd like to use a noun (`renderer` ?) instead of a verb (`render`).

**Comment by 1ed** [comment]
I like `$io` or maybe `$style` or `$stylize` or `$stylus` or `$stylist` :)

```php
$style = new SymfonyStyle($input, $output);

$style->title('...');
$style->table('...');
```

**Comment by xabbuh** [comment]
maybe `$styledRenderer` or `$styleRenderer`

**Comment by javiereguiluz** [comment]
Just a comment about your proposals: the "style" thing here is not that important. This feature is about being able to format output and input elements using a semantic API. In other words, I don't care about the style of the rendered title, I just care about having a simple `->title()` method which de-clutters my command code (I don't have to change the color of the title text, add spacing and `\n`, add an underline, etc.).

**Comment by pix-art** [comment]
+1 on renderer, the noun is already used on other cases like twig bridge. People will know what it means.

**Comment by weaverryan** [comment]
I kind of like `$io`. What some of us might not realize (me included until I saw Javier's suggestions), is that this isn't just an output or renderer, it also handles input.

**Comment by javiereguiluz** [comment]
Let's settle for `$io`, which is concise and clearly shows that this is both for input and output operations.
