### ISSUE TITLE
GAE: Direct file uploads not working

### ISSUE THREAD

**Issue by atrauzzi** [symfony/symfony#16002]
Please see this issue here on the Google App Engine bug tracker: https://code.google.com/p/googleappengine/issues/detail?id=12371

I'm currently using HttpFoundation via Laravel.

The basic gist of things is that on top of supporting wrapped file uploads via special URL, app engine has also included somewhat-more-recent support for direct file uploads to the memory of the handling process.  You can see more about it here: https://gae-php-tips.appspot.com/2015/03/09/direct-file-uploads-for-php-5-5/

Based on what I was able to determine, it looks like trying to get the real path to a file with a `vfs://` path results in `false` being returned.
This is obviously environment specific, although I'd love to be able to continue using Symfony's wrapper for uploaded files in my controllers.  Perhaps there's something that can be done to smooth this over?

**Comment by HeahDude** [comment]
Hi @atrauzzi, any news on this?

**Comment by atrauzzi** [comment]
Sadly I'm not using GAE anymore in my current projects (Docker!).  But perhaps this is still a valid situation to want to anticipate.  Just for the sake of anyone still stuck on GAE.

**Comment by xabbuh** [comment]
Closing here for now then. If someone is experiencing this problem again, we can consider to reopen.
