### ISSUE TITLE
UniqueEntity constraint should produce better messages when enforced on multiple fields

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#16022]
The `UniqueEntity` constraint ensures the uniqueness of an entity based on the value of some given fields. Now for a single field of the Entity the violation is built properly and the path can be retrieved via `ConstraintViolationInterface::getPropertyPath`. But when using multiple fields, the aforementioned method will return only the first field, and `ConstraintViolationInterface::getInvalidValue` will return will only the value for the first field.  
I have automated displaying error messages to the user from `ConstraintViolation` objects by using the `getMessage` , `getMessageParameters` and `getInvalidValue` of `ConstraintViolationInterface` implementing objects returned from the validator. I think the `fields` (or the `implode`d version) option should be added as a message parameter on the violation, and the value of all given fields (or maybe an associative array) should be returned when calling `ConstraintViolationInterface::getInvalidValue` on the violation built by `UniqueEntityValidator`.

**Comment by javiereguiluz** [comment]
I'm sorry but I must close this as "won't fix" because it didn't receive any comment or support from the community in almost two years. I hope you understand it. Thanks!
