### ISSUE TITLE
Controller action with no return but works. Bug or feature ?

### ISSUE THREAD

**Issue by beesofts** [symfony/symfony#16021]
It seems that I can have a controller method with no return to works, whereas i thought a method MUST always return a response one way or another. This happens when the method has at least one parameter.

In the two next samples, Route & Template annotation was imported, and I have a blade file on the expected folder.

This method leads to an error (a controller must return a response....) that is what I expected :
```
/**
 * @Route("test")
 * @Template
 */
public function testAction() {}
```
This method (note the parameter that is completly useless) renders and display the template targeted by the @Template annotation :
```
/**
 * @Route("test")
 * @Template
 */
public function testAction($uselessParam = null) {}
```

So bug or feature ?

**Comment by apfelbox** [comment]
That is a feature of the `@Template` annotation, see here:

> You can make it even more concise as all method arguments are automatically passed to the template if the method returns null and no vars attribute is defined

http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/view.html (way down at the end of the article)

**Comment by beesofts** [comment]
Ok thank you !
