### ISSUE TITLE
[HttpFoundation] finfo second parameter 'string found, path expected' error

### ISSUE THREAD

**Issue by czim** [symfony/symfony#16039]
On some systems (nginx/hhvm) we get an finfo() error for File / MimeTypeGuesser usage:

> finfo::finfo() expects parameter 2 to be a valid path, string given

This happens when the `magicFile` property on the `FileinfoMimeTypeGuesser` is null (or an empty string). The fix for this is to *only* pass in the second parameter for the `finfo()` constructor if it is not empty.

**Comment by xabbuh** [comment]
This sounds more like a bug in HHVM then (the docs explicitly say that you can pass `null`).

**Comment by fabpot** [comment]
Closing as this is apparently a bug in HHVM. Can you report it there? Thanks.
