### ISSUE TITLE
[Form] Expected "form", given "text"

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#16045]
Since upgraded to latests commit of SF 2.8, I randomly get this kind of error:

```
An exception has been thrown during the rendering of a template ("The extended type specified for the service "mopa_bootstrap.form.type_extension.static_text" does not match the actual extended type. Expected "form", given "text".") in cdn/show.html.twig at line 15.
```

This is BC break, a deprecation warning should be thrown instead IMO.

Searched about related issue, didn't found.

**Comment by stof** [comment]
@Soullivaneuh using mismatching thing could potentially lead to weird behaviors in the past, which would be hard to debug. We were missing the validation to warn you early about such mistakes.
You should fix your service definition to match the extended type of your class (or the opposite depending of which one is right)

**Comment by stof** [comment]
and note that it is not a deprecated feature. Mismatching extended types have never been meant to be supported properly. It was just not telling you that you made a mistake when configuring it and that it could do weird stuff later.

**Comment by Soullivaneuh** [comment]
Oh, I understand. But this problem is lot of external bundle use `text` string and broke application with 2.8.

We have to find a smoother solution IMHO.

And just to be sure: To fix it, we just have to replace 'text' (or anything else) by 'form' without any edge case issue?

**Comment by jvasseur** [comment]
The problem is that there is a mismatch between the extended type in the form extension class and in the service definition tag.

**Comment by stof** [comment]
@Soullivaneuh using ``text`` as extended type is fine, if this is the type you extend. what is invalid is giving a different extended type in the code and in the tag registering the extension lazily

**Comment by jakzal** [comment]
@Soullivaneuh have you fixed your issue? It doesn't look like we should do anything in Symfony? What's the external bundle you mentioned?

**Comment by Soullivaneuh** [comment]
This is actually related to [mopa/bootstrap-bundle](https://github.com/phiamo/MopaBootstrapBundle):

```
Symfony\Component\Form\Exception\InvalidArgumentException: The extended type specified for the service "mopa_bootstrap.form.type_extension.static_text" does not match the actual extended type. Expected "form", given "text".
```

**Comment by Tobion** [comment]
So this can be closed I guess.
