### ISSUE TITLE
[HttpFoundation] IpUtils::checkIp4 incorrectly handles CIDR notation with subnet 0.0.0.0/0

### ISSUE THREAD

**Issue by ultrafez** [symfony/symfony#16055]
The checkIp4 method in IpUtils is able to check whether an IP belongs to a particular subnet specified in CIDR notation, however it incorrectly states that all IP addresses are *not* members of the subnet 0.0.0.0/0.

This is due to the check on the size of the netmask in [`IpUtils::checkIp4`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/IpUtils.php#L71) - if the netmask is less than `-1`, then it immediately returns `false`, which is incorrect - all IPv4 addresses are members of the /0 subnet by default.

This can easily be fixed by adding a check for whether `$netmask === 0`, and if so, returning `true` immediately, since all IPs would be a member.

**Comment by stof** [comment]
would you mind sending a pull request with the fix (and a test ensuring that this does not get broken by mistake again in the future) ?

**Comment by ultrafez** [comment]
Looks like @lrlopez beat me to it - his pull request fixes my issue though.

**Comment by lrlopez** [comment]
@ultrafez, do you want to go ahead with your own PR? I can close it and delete the branch so you can proceed. I was just taking some snapshots for my students about how to contribute into an open-source project and this was an easy one to show.

**Comment by ultrafez** [comment]
@lrlopez sure, I'll submit one today, thanks

**Comment by lrlopez** [comment]
Closing in favor of #16177
