### ISSUE TITLE
Symfony Ldap component should be as optional as ACL 

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony#16066]
Hi,

I just saw that a new Security component was introduced: the security Ldap component.

We just removed the ACL component from the complete stack and I don't see why Ldap should be packaged within Symfony and btw in Symfony framework.

The need of Ldap is very rare, so I realy think this should be a suggested package instead of an hard dependency.

Regards.

**Comment by csarrazi** [comment]
Actually, LDAP is mainstream in the enterprise world, through Active Directory.

Also, even though the security component provides a user provider as well as an authentication provider, the Ldap component is still an optional dependency.

I mean, it's the same thing as Doctrine. We do provide a Doctrine bridge, even though you may not use a relational or document database in your application (web services, or Redis, for example).

**Comment by WouterJ** [comment]
@csarrazi except that Doctrine and ACL aren't included in `symfony/symfony`, while LDAP is.

**Comment by mickaelandrieu** [comment]
Hi @csarrazi,

if the Ldap component is already an optional dependency, do you agree to make it as a suggestion instead of a hard requirement ?

I don't think we can compare Doctrine use to Ldap use ^^: 99.9999% use a relational database, and probably 99.99% choose doctrine with Symfony.

But Ldap realy depend on your project, and should be included only when required.

Don't get me wrong, I thank you (and @lyrixx) for this component :)

**Comment by WouterJ** [comment]
@mickaelandrieu I didn't talk about the organization, but the `symfony/symfony` package. Which is exactly the same as is done with ACL

**Comment by mickaelandrieu** [comment]
Agree :) I'm in favor of a ``suggest`` section in ``symfony/symfony`` package for both acl & ldap components.

**Comment by lyrixx** [comment]
What is the benefit of doing that ?

Then you **can not compare** ldap and acl. It's totally two different things.

**Comment by mickaelandrieu** [comment]
This is what the ``suggest`` section is supposed to be: a list of external dependencies that you can add to your project **according** to your needs.

3 benefits:
* don't force each Symfony (framework) project to embed optional components
* enforce good practices: standalone components, and bridges created in the standard edition and *not* in the symfony/symfony package component: this is how Symfony Framework is supposed to be done.
* last - but very subjective - the framework is big enough. Let's composer and developpers choose which dependencies they need.

**Comment by iltar** [comment]
As the one who extracted the ACL (working on the bundle when I have time) and using LDAP, I can agree with the issue that it might not be the best to have it included by default. 

I think Symfony is reaching a point where a decision should be made on which components are considered core and which aren't. There's a lot of stuff in there I don't use but I'm still not sure if this is my own choice or Symfony's choice as in the end, I'm free to require only what I need using the subtree split.

**Comment by Taluu** [comment]
:100: for that.

**Comment by lyrixx** [comment]
What is the rational behind this issue? 

I mean, this issue can be "extended" by removing CssSelector or Finder or Process, etc ...

**Comment by nicolas-grekas** [comment]
symfony/symfony is kind of a metapackage. Having monolithic repository provides so many benefits.
One example is the releasing process. An other one that it allows cross-components patches. And so on.
I invite you to listen to https://www.youtube.com/watch?t=1235&v=W71BTkUbdqE

I you want to download less code, just require the components you need instead of symfony/symfony.
symfony/symfony is not a curated list of components and as such it could grow as big as we want.
symfony/symfony is about processes, methodology and the quality assurance it provides. All the code in this repo share the same quality level. Once something gets out, it diverges from this quality process. This should be allowed only when we want this exact result (quality divergence). Not because we want symfony/symfony to be '"light on lines of code"...

**Comment by Taluu** [comment]
Yup but why is the `Ldap` component here while the `Acl` are not ? This was exactly why the `Acl` was moved elsewhere.

**Comment by fabpot** [comment]
ACL was huge, not maintained anymore (nobody in the core team used it), highly dependent on Doctrine,  and more...

**Comment by lyrixx** [comment]
> This was exactly why the Acl was moved elsewhere.

**absolutely not** and again, I'm quoting myself:

> Then you can not compare ldap and acl. It's totally two different things.

**Comment by Taluu** [comment]
Just checked and saw, my bad. And then again I agree with @nicolas-grekas on the fact that `symfony/symfony` is a meta-package. So let's leave this as is.

Sorry for the previous reaction.

**Comment by mickaelandrieu** [comment]
@nicolas-grekas thank you for your video.

Still think we shouldnt embed all the world in Symfony framework: as one of the BlackFire team you can't say this choice don't have an impact on the global performance of your application.

Then, as a developper I want to choose which components I want to use when I work with the framework: this is not the case at all. Because of that, we have more and more dependencies between components (Security need HttpKernel, Event Listener, and so on can't be used except in another "Symfony application"). So I'm very skeptical on how this framework evolve day by day.

In all cases, for now, Symfony framework but also Symfony project can't be said as a "set of reusable components" but as a monolithic framework, that become bigger and bigger ...

And again @lyrixx, we understand that ldap and acl are differents, this is not issue here. The issue is that each time a new component is pushed on the organisation, all developpers MUST deal with it.

We can do better *easily*, we just don't want.

I won't insist, thanks for your answers.

**Comment by fabpot** [comment]
@mickaelandrieu You can't be serious about your last comment. There is a big difference between something being decoupled and how repositories are managed. Heck, you can even use the subtree-splits or the main repository, your choice.

**Comment by mickaelandrieu** [comment]
@fabpot I totaly agree with you, this is why I think the core team can manage all repositories in the same place *without* force any Symfony framework developper to depends on all components.

To be honest, I think my issue is more global than Ldap or Acl component.

For you: which components MUST be in Symfony Framework Standard Edition ? and which one should be only suggested ?

Sorry if my last comment was a little bit direct, but the issue (to me) is critical and this should be allowed to debate and not closed :/

**Comment by jpauli** [comment]
Does this guy know what a package is, and how Linux solved this pretty old problem building what's called package managers ? If you don't want the Earth to come, don't download a metapackage like symfony/symfony is ...

**Comment by mickaelandrieu** [comment]
@jpauli did you ever take a look to the composer.json inside `symfony/standard-edition` ? :)

**Comment by javiereguiluz** [comment]
@mickaelandrieu please remember that we are talking about the `symfony-standard` edition. This is not the "empty edition" or "the simplest edition". This is an opinionated edition which contains what the Symfony deciders think it's better to start developing a Symfony application.

**Comment by romainneutron** [comment]
> Still think we shouldnt embed all the world in Symfony framework: as one of the BlackFire team you can't say this choice don't have an impact on the global performance of your application.

Actually, if you don't use LDAP component and use an optimized autoloader dump, you won't see any difference at runtime. If I'm wrong, I'm open to a Blackfire graph :)

**Comment by mickaelandrieu** [comment]
thanks for information @romainneutron :)
