### ISSUE TITLE
[Security] Login _security.last_error captures any exception thrown

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony#16060]
The login form will capture any exception thrown during the call stack and display as the last error to the end user.

Simple examples:
* Shut down your database server and try to login. The error will be SQLSTATE[HY000] [2002] Can't connect [...]
* If you input incorrect database name in parameters.yml, that will reveal to the outer world your database username and the database name:
SQLSTATE[HY000] [1044] Access denied for user 'dbuser'@'127.0.0.1' to database 'topsecret'
* Now, if you extend your user object with an additional field and "forget" to run the migration, Doctrine will try to select the user with the new field, and that will display the entire failed query at the top of your login form, SELECT [all_fields_listed] FROM your_table.

Other examples could be non-database related.

It also won't log it at that time using monolog. The exception is silenced.

Tested using latest stable in both prod and dev environments. Of course, all the above *should* never happen and we should take care to run our migrations, keep the database server up and running etc. - but as Murphy’s law states that if something can go wrong, it inevitably will.

A workaround would be to check the error message and align with (Advanced)UserInterface checks, and for any other error messages, simply show "Unknown error" or re-throw a new Exception with the error message (still doesn't sound right though).

Has anyone come across this before?

**Comment by iltar** [comment]
Doesn't it trigger [this](https://github.com/symfony/symfony/blob/2655072bfdf5bef44c34495a01ec2470a82bcacb/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L104-L115)?

I'm not sure about the logging, but I do know you shouldn't show the exception to userland. The Authentication Exception has a `getMessageKey` which you can (optionally) translate.

**Comment by ptrm04** [comment]
@iltar I've just run it with xdebug, it never makes it to [this](https://github.com/symfony/symfony/blob/2655072bfdf5bef44c34495a01ec2470a82bcacb/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L104-L115), double checked no logs exist in dev.log / prod.log

**Comment by jakzal** [comment]
@ptrm04 I've tried to reproduce this on [symfony-demo](https://github.com/symfony/symfony-demo) by changing the database_path in parameters.yml to an invalid location. Error that's shown to the end user is "Authentication request could not be processed due to a system problem.". The SQL exception was logged by monolog.

Could you please provide steps on how to reproduce it on a fresh installation of symfony standard edition (or use  demo)?

**Comment by ptrm04** [comment]
@jakzal that is correct - I've just changed database host to something invalid i.e. 127.0.0.11 and I got "Authentication request could not be processed due to a system problem." too - your database config has to be "right" to reproduce it, it is the exception triggered by database server response that is causing this issue. So, make sure your database config params are correct, then shut down your database server and try to login, you'll receive a message similar to the first on the initial example error list. That's just one way to reproduce it.

To reproduce the second error message, drop the privileges for the user you use to connect to the database.

The third error message - involves changing your User entity and trying to login without running migrations on your database server. That would give you similar error message as in the third one in the list of errors.

Hope this helps.

**Comment by jakzal** [comment]
Thanks for the details. I'll double check tomorrow.

**Comment by jakzal** [comment]
@ptrm04 I still fail to reproduce this issue. Note that I'm using the [demo app](https://github.com/symfony/symfony-demo) to avoid dependencies on external projects like FOSUserBundle. Could you please provide a fork of [symfony-standard](https://github.com/symfony/symfony-standard) edition with your problem reproduced?

**Comment by ptrm04** [comment]
I had a brief moment to look at the symfony-demo app and this has shed some light on it all, the behavior I observed was based on the AcmeDemoBundle (now deprecated in favor for the symfony-demo app).

AcmeDemoBundle uses the following twig line in the login view to show the error (which effectively reveals the exception body such as ```[...]SQLSTATE[HY000] [2002] Connection refused[...]``` etc.:

    <div class="error">{{ error.message }}</div>

And symfony-demo app uses:

    <div class="error">{{ error.messageKey|trans(error.messageData, 'security') }}</div>

which will display the message key (translated if neccessary), hence not seeing the barebone ```error.message```

Also, the exception does get logged if your handler is on the *info* level:

    [2015-10-18 14:37:47] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): SQLSTATE[HY000] [2002] Connection refused at [...]

It'd probably be best to raise the level of the ```AuthenticationServiceException``` if the nested exception is critical or just inherit the severity (so that for example monolog can email this depending on the config) - otherwise this can be closed off.

Thanks @jakzal for looking into this - do you have a buy me a beer button? Take it you like beer based on your github pic! ;-)

**Comment by javiereguiluz** [comment]
Closing this old issue because it looks like there is nothing else left to do.

**Comment by ptrm04** [comment]
@javiereguiluz how about the follow on action to increase the severity from INFO to the actual severity of the inner / nested exception? Database being down is not an "INFO" level exception. Login form probably won't be the first place that you find out that your database is down, but for consistency and clarity it should get logged correctly.
