### ISSUE TITLE
[Console] SymfonyStyle makes output much longer for simple commands

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#16103]
I've updated a project to 2.8 to play around with the new features and one thing I noticed immediately is that SymfonyStyle makes the standard output much longer.

To give an example: After `composer update` has updated all deps, a script calls `cache:clear`.
**Output 2.7.x:**
```
$ composer update
...
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> ...
```
**Output 2.8.x:**
```
$ compose rupdate
...
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

> ...
```
As you see, it has gone from 1 line to 6 lines. The same happend with commands like `assets:install` (which has even more new lines, as it now displays a full table).

While I can clearly see that the consistent style is better (and the style is really nice), I have some concerns about the verbosity of the output.

For instance, I don't think comments should be displayed in normal verbosity. All information in the comment is already displayed in the status bar. When a user wants to be sure they're running the command with the correct settings (so they can stop the script before clearing), they should be fine with running `cache:clear -v`.

At the moment, I've added `--quiet` in my build script, but I don't like that. Symfony has 3 verbosity modes and only one quiet mode, let's use the verbosity modes to make a clear separation of important, less-important and debug output.

**Comment by javiereguiluz** [comment]
To give a bit more context to @WouterJ's comment, this is the full screenshot of Symfony 2.7 to 2.8 update:

![update_form_2_7_to_2_8](https://cloud.githubusercontent.com/assets/73419/10423999/a093f436-70cb-11e5-8cd5-3d6d8a4176b0.png)

**Comment by WouterJ** [comment]
Seems like nobody besides me cares, closing.
