### ISSUE TITLE
Introduce "Lock Account" Route for Remember Me

### ISSUE THREAD

**Issue by jeremylivingston** [symfony/symfony#16113]
Currently, the "logout" firewall destroys the remember me cookie if it is configured.

There are situations where sites may want their users to stay in a "remembered" state after signing out. An example could be displaying a header message that reads, "Welcome back, @jeremylivingston". The site could require that the majority of routes required IS_AUTHENTICATED_FULLY, but still open some to the IS_AUTHENTICATED_REMEMBERED state.

I propose the creation of a new logout route type that will "lock" the account and put it into this state. The route could have its own handlers, similar to the logout firewall, but it would run the same LogoutHandler classes as the actual logout route. Developers could still use the existing logout route if they'd like to destroy the remember me cookie.

I am open to suggestions for how to build this, whether it's a separate firewall type, a configuration within the remember_me firewall, or a configuration option within the logout firewall. I feel that the latter would be the least scaleable.

I'm happy to do the required work for this feature. I'd just like to make sure that it's something that the group would like to see added to the core. Thanks!

**Comment by iltar** [comment]
The `logout` key in the firewall is nothing more than a listener, such as the `form_login`, `anonymous` and `http_basic`. They are connected through the listeners using:  `Symfony\Component\Security\Http\Firewall\ListenerInterface`.

It is possible to create a listener that does a regular logout and then proceeds to update with `remember_me`.

**Comment by jeremylivingston** [comment]
@iltar, that approach would require the creation of a new firewall, including all of the boilerplate code found in the SecurityExtension to set it up, correct? It could benefit from all of the parameters in the existing firewall: path, target, invalidate_session, delete_cookies, handlers, success_handler, etc.

Do you think that something like this should be in the core, since it could be a common use-case for the remember_me functionality?

Let me know what you think. Thanks!

**Comment by jaytaph** [comment]
@jeremylivingston The handlers of the logout might not save you (the security token is actually removed AFTER the handling of the logout listeners), but, you might be able to create a simple logout handler that temporarily stores some information (i've logged out, and this was the original token), and with an additional listener on for instance `kernel.response` you could easily setup a remember-me cookie with that information, through the `PersistentTokenBasedRememberMeServices` most likely.

I think your use-case might not be one that many users need, but i really like to have such a feature available (especially if it's just a single simple configuration setting)

**Comment by iltar** [comment]
@jeremylivingston I do recommend it being a listener itself and it could be configured on an existing firewall.

**Comment by Rvanlaak** [comment]
You could [decorate](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services) the [`LogoutListener`](https://github.com/symfony/security-http/blob/master/Firewall/LogoutListener.php) and make your own `handle` implementation.

**Comment by javiereguiluz** [comment]
Let's close this because it's been almost 2 years without activity and some alternative solutions were proposed. Thanks!
