### ISSUE TITLE
[Form] Using a choice field with expended and mutliple lead bad HTML

### ISSUE THREAD

**Issue by Congelli501** [symfony/symfony#16124]
Using symfony form generator, with type "choice" and the data given bellow, the generated HTML contains invalid name.

```
{
    "choices": {
        "morning": "form.field_value.availability_time.morning",
        "afternoon": "form.field_value.availability_time.afternoon",
        "evening": "form.field_value.availability_time.evening"
    },
    "expanded": true,
    "multiple": true,
    "required": false,
    "label": "form.field_title.availability_time"
}
```

Generated HTML code:
```
<input type="checkbox" value="" name="form_recall[availabilityDay][]" id="form_recall_availabilityDay_0">
```

The name should contain something to distinguish checkboxes (like `form_recall[availabilityDay][monday]`)

The form is always considered as invalid.

Symfony version: 2.6.11

**Comment by xabbuh** [comment]
Which form generator are you talking about?

**Comment by Congelli501** [comment]
I use the form Factory in \Symfony\Component\Form\FormFactory, in the default symfony installation.

Does that answer your question ?

**Comment by xabbuh** [comment]
Well, but how do you map your configuration to the Form component?

**Comment by stof** [comment]
what makes you think it is bad HTML ? This HTML is valid

**Comment by xabbuh** [comment]
@stof It's semantically correct, but you have no way to determine which checkbox has been checked. However, I still think that this is related to some tool used to create the form type objects from the JSON config.

@Congelli501 Please leave some comment if you can provide more information about your setup and you still think that it is related to a bug in Symfony.

**Comment by stof** [comment]
@xabbuh the values of the checkboxes are different, so the backend can still know which checkboxes are checked, by looking at what got submitted.

**Comment by xabbuh** [comment]
As far as I understand the description all values are empty strings.

**Comment by stof** [comment]
Well, then this is an issue. But it is probably related to a mistake in the way the form is built, and we don't have the code building the form.

**Comment by Congelli501** [comment]
Yes, all the values are set to empty string.

I'll extract the code and post it shortly.

**Comment by Congelli501** [comment]
This bug was my fault, a bad JS code removed the value field of the checkboxes...
Sorry for the waste of time.
