### ISSUE TITLE
[2.6.11][2.6.x-dev] DEBUG_BACKTRACE_PROVIDE_OBJECT

### ISSUE THREAD

**Issue by wasikuss** [symfony/symfony#16120]
Hi, I have an error:
>    Notice: Use of undefined constant DEBUG_BACKTRACE_PROVIDE_OBJECT - assumed 'DEBUG_BACKTRACE_PROVIDE_OBJECT'
>    500 Internal Server Error - ContextErrorException 

in
>    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DumpDataCollector.php at line 74

`DEBUG_BACKTRACE_PROVIDE_OBJECT` was introduced in `php 5.3.6`. But according to [Packagist](https://packagist.org/packages/symfony/symfony#2.6.x-dev), `Symfony 2.6.11` or `Synfony 2.6.x-dev` require `php >= 5.3.3`.

lines

    $trace = DEBUG_BACKTRACE_PROVIDE_OBJECT | DEBUG_BACKTRACE_IGNORE_ARGS;
    if (PHP_VERSION_ID >= 50400) {
        $trace = debug_backtrace($trace, 7);
    } else {
        $trace = debug_backtrace($trace);
    }

can be fixed with

    if(PHP_VERSION_ID >= 50306) {
        $trace = DEBUG_BACKTRACE_PROVIDE_OBJECT | DEBUG_BACKTRACE_IGNORE_ARGS;
        if (PHP_VERSION_ID >= 50400) {
            $trace = debug_backtrace($trace, 7);
         } else {
            $trace = debug_backtrace($trace);
        }
    }
    else
        $trace = debug_backtrace();

**Comment by jrobeson** [comment]
Symfony 2.6 is only receiving security fixes and no bug fixes. You should upgrade your project to 2.7 which is LTS.

**Comment by xabbuh** [comment]
Symfony 2.6 does get receive bug fixes and Symfony 2.7 requires PHP 5.3.9 or higher.
