### ISSUE TITLE
[Feature Request][Config] deprecation handling for configuration options

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony#16140]
This ist just an idea yet.

What do you think? 
Does it make sense?

```php
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritdoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('app');
    
        $rootNode
            ->children()
                ->scalarNode('old_option')
                    ->isRequired()

                    // when you don't need the option anymore
                    ->isDeprecated()

                    // when you want to use another option instead
                    // (maybe also useful for renaming ?)
                    ->isDeprecatedBy('new_option')

                    // or
                    ->deprecatedBy('new_option')
                ->end()
                ->scalarNode('new_option')
                    ->isRequired()
                ->end()
            ->end()
        ;
        return $treeBuilder;
    }
}
```

**Comment by stof** [comment]
the hard part is that deprecating thing in favor of a new option generally requires to add some normalization on the parent node to rewrite things to use the new option. A call in the ``old_option`` node will not be allowed to alter the normalization of the ``app`` node to rewrite options.
Thus, it is not always a simple renaming. Other changes may be necessary on the value. So I'm not sure the renaming can be automated under such an easy API.

**Comment by OskarStark** [comment]
Hi @stof , thank you for your feedback.

I don't want to use ne thew node directly, but i want to easily ``trigger_error`` method to the user.
Now you have to handle it in the ``*Extension.php``.

I don't know this makes sense, but we have a problem here and i thought how to fix it.
sonata-project/SonataAdminBundle#3296

Using it directly would also mean to make the code working with both options, right?
From this point you have to add version numbers to your config component IMO ... and i don't really like that idea.

**Comment by stof** [comment]
@OskarStark no you don't. It is possible to do it in the configuration class directly. See in FrameworkBundle for the profiler config settings for instance: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L264

**Comment by OskarStark** [comment]
Thank you for the info @stof

**Comment by javiereguiluz** [comment]
I agree with @stof. So, @OskarStark would you agree to use `@trigger_error` inside the Configuration class as Symfony does for deprecating options? If yes, we can close this issue. Thanks!

**Comment by javiereguiluz** [comment]
Closing it as "fixed" thanks to the alternative solution provided by @stof.
