### ISSUE TITLE
[Validators] Assert Length min value does not work on null

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#16157]
[According to the documentation](http://symfony.com/doc/current/reference/constraints/Length.html):

>Validates that a given string length is between some minimum and maximum value.

If the validated property has a `null` value or is an empty string, specifying a min value won't generate any violations. Tested on PHP5.6 with Symfony2.7.

**Comment by unkind** [comment]
> It is important to notice that NULL values and empty strings are considered valid no matter if the constraint required a minimum length. Validators are triggered only if the value is not blank.

**Comment by Tobion** [comment]
All validators accept null and empty string. There are already alot of issues about this topic.

**Comment by theofidry** [comment]
If you specify a constraint "my property must be a string of at least 2 characters", you expect a violation to be raised for a null or empty string no matter how you look at it it's just weird. But if it's considered as the expected behaviour, fine, but put a word on it in the doc. So please the ticket @Tobion.

**Comment by theofidry** [comment]
My bad, didn't see your message @unkind, where is this message quoted from? Can't find it T.T

**Comment by jakzal** [comment]
@theofidry it's a quote from the documentation you referenced: http://symfony.com/doc/current/reference/constraints/Length.html#min

**Comment by theofidry** [comment]
Indeed I've found it later sorry about that, thanks @jakzal. But I still believe this should put a warning under the head title though.

**Comment by jakzal** [comment]
@theofidry agreed. Could you send a PR to symfony/symfony-docs?
