### ISSUE TITLE
Cannot create database via `app/console doctrine database:create`

### ISSUE THREAD

**Issue by k0pernikus** [symfony/symfony#16150]
This relates to #12278 yet I seem to still be experiencing it.

I have a symfony2.6.11 application, but I also upgraded to symfony2.7.5 in order to find out if it still persissts, and so it does.

I wanted to setup a new instance and create the database via:

    $ php app/console doctrine:database:create --if-not-exists

Yet I get this error message:
                                                                                                      
      [Doctrine\DBAL\Exception\ConnectionException]                                                
      An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'local_api'  
                                                                                            
      [Doctrine\DBAL\Driver\PDOException]                          
      SQLSTATE[42000] [1049] Unknown database 'local_api'
    
      [PDOException]                                               
      SQLSTATE[42000] [1049] Unknown database 'local_api'

I found a [bug report for the doctrine/doctrine-bundle][1], yet we are already using the fixed version 1.5.

I know that I can create them when I connect directly to my mysql database and run `CREATE DATABASE local_api`, yet I want my workflow to go through doctrine2.

And just to make absolutly sure that the issue is unrelated to my databse setup I ran:

    $ mysql --host=10.10.10.10 --user=foo --password=bar 
    mysql> CREATE DATABASE local_api;
    Query OK, 1 row affected (0.00 sec)
    mysql> Bye
    $ php app/console doctrine:database:create --if-not-exists
    Database `local_api` for connection named default already exists. Skipped.

I then can drop the database using

    php app/console doctrine:database:drop --force

Yet recreating it fails again with above mentioned error.

This errror also occurs while trying to clear the cache via:

    ./app/console cache:clear

So it seems related to how symfony2 initalized the whole db stack.

The verbose error message looks like this:

    [2015-10-06 17:26:28] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".  {"uid":"c9f3fb0"}
    [2015-10-06 17:26:28] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".  {"uid":"c9f3fb0"}
    Clearing the cache for the dev environment with debug true
      Clearing outdated warmup directory
      Warming up cache     
                                                                                           
      [Doctrine\DBAL\Exception\ConnectionException]                                        
      An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'local_api'  
                                                                                           
    Exception trace:
     () at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
     Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:133
     Doctrine\DBAL\DBALException::driverException() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:47
     Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
     Doctrine\DBAL\Connection->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
     Doctrine\DBAL\Connection->getDatabasePlatformVersion() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
     Doctrine\DBAL\Connection->detectDatabasePlatform() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
     Doctrine\DBAL\Connection->getDatabasePlatform() at ~/src/api/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:61
     Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1093
     ap_DevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1142
     ap_DevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php:35
     Symfony\Bridge\Doctrine\ManagerRegistry->getService() at ~/src/api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:226
     Doctrine\Common\Persistence\AbstractManagerRegistry->getManagers() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php:54
     Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
     Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at ~/src/api/app/bootstrap.php.cache:2641
     Symfony\Component\HttpKernel\Kernel->initializeContainer() at ~/src/api/app/bootstrap.php.cache:2411
     Symfony\Component\HttpKernel\Kernel->boot() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
     Symfony\Component\Console\Application->doRunCommand() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at ~/src/api/app/console:27
                                                           
      [Doctrine\DBAL\Driver\PDOException]                  
      SQLSTATE[42000] [1049] Unknown database 'local_api'  
    
    Exception trace:
     () at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
     Doctrine\DBAL\Driver\PDOConnection::__construct() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:45
     Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
     Doctrine\DBAL\Connection->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
     Doctrine\DBAL\Connection->getDatabasePlatformVersion() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
     Doctrine\DBAL\Connection->detectDatabasePlatform() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
     Doctrine\DBAL\Connection->getDatabasePlatform() at ~/src/api/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:61
     Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1093
     ap_DevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1142
     ap_DevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php:35
     Symfony\Bridge\Doctrine\ManagerRegistry->getService() at ~/src/api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:226
     Doctrine\Common\Persistence\AbstractManagerRegistry->getManagers() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php:54
     Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
     Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at ~/src/api/app/bootstrap.php.cache:2641
     Symfony\Component\HttpKernel\Kernel->initializeContainer() at ~/src/api/app/bootstrap.php.cache:2411
     Symfony\Component\HttpKernel\Kernel->boot() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
     Symfony\Component\Console\Application->doRunCommand() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at ~/src/api/app/console:27
                                                           
      [PDOException]                                       
      SQLSTATE[42000] [1049] Unknown database 'local_api' 
    
    Exception trace:
     () at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
     PDO->__construct() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
     Doctrine\DBAL\Driver\PDOConnection->__construct() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:45
     Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
     Doctrine\DBAL\Connection->connect() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
     Doctrine\DBAL\Connection->getDatabasePlatformVersion() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
     Doctrine\DBAL\Connection->detectDatabasePlatform() at ~/src/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
     Doctrine\DBAL\Connection->getDatabasePlatform() at ~/src/api/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:61
     Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1093
     ap_DevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/app/cache/de_/ap_DevDebugProjectContainer.php:1142
     ap_DevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService() at ~/src/api/app/bootstrap.php.cache:2155
     Symfony\Component\DependencyInjection\Container->get() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php:35
     Symfony\Bridge\Doctrine\ManagerRegistry->getService() at ~/src/api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:226
     Doctrine\Common\Persistence\AbstractManagerRegistry->getManagers() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php:54
     Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
     Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at ~/src/api/app/bootstrap.php.cache:2641
     Symfony\Component\HttpKernel\Kernel->initializeContainer() at ~/src/api/app/bootstrap.php.cache:2411
     Symfony\Component\HttpKernel\Kernel->boot() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
     Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
     Symfony\Component\Console\Application->doRunCommand() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at ~/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at ~/src/api/app/console:27
    
    
    cache:clear [--no-warmup] [--no-optional-warmers]

  [1]: https://github.com/doctrine/DoctrineBundle/issues/384
  [2]: https://github.com/symfony/symfony/issues/12278

**Comment by xabbuh** [comment]
Can you please show the output of `composer show -i`?

**Comment by k0pernikus** [comment]
@xabbuh Here you go:

```
$ composer show -i
doctrine/annotations                 v1.2.7             Docblock Annotations Parser
doctrine/cache                       v1.4.2             Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.3.0             Collections Abstraction library
doctrine/common                      v2.5.1             Common Library for Doctrine projects
doctrine/dbal                        v2.5.2             Database Abstraction Layer
doctrine/doctrine-bundle             dev-master 5674222 Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       v1.0.1             Symfony2 Bundle for Doctrine Cache
doctrine/inflector                   v1.0.1             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         dev-master e91bce5 Object-Relational-Mapper for PHP
elasticsearch/elasticsearch          v1.1.0             PHP Client for Elasticsearch
guzzle/guzzle                        v3.9.3             PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle
guzzlehttp/guzzle                    5.3.0              Guzzle is a PHP HTTP client library and framework for building RESTful web service clients
guzzlehttp/ringphp                   1.1.0              Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                   3.0.0              Provides a simple abstraction over streams of data
incenteev/composer-parameter-handler v2.1.1             Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
mailgun/mailgun-php                  v1.8               The Mailgun SDK provides methods for all API functions.
monolog/monolog                      1.17.1             Sends your logs to files, sockets, inboxes, databases and various web services
phpunit/php-code-coverage            2.2.3              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            1.3.4              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    1.0.7              Utility class for timing
phpunit/php-token-stream             1.4.8              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      4.1.6              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         2.1.5              Mock Object library for PHPUnit
pimple/pimple                        v1.1.1             Pimple is a simple Dependency Injection Container for PHP 5.3
predis/predis                        dev-master 6bc1a38 Flexible and feature-complete PHP client library for Redis
psr/log                              1.0.0              Common interface for logging libraries
react/promise                        v2.2.1             A lightweight implementation of CommonJS Promises/A for PHP
sebastian/comparator                 1.2.0              Provides the functionality to compare PHP values for equality
sebastian/diff                       1.3.0              Diff implementation
sebastian/environment                1.3.2              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   1.2.1              Provides the functionality to export PHP variables for visualization
sebastian/recursion-context          1.0.1              Provides functionality to recursively process PHP variables
sebastian/version                    1.0.6              Library that helps with managing the version number of Git-hosted PHP projects
sensio/distribution-bundle           v3.0.31            Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.10            This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v2.5.3             This bundle generates code for you
sensiolabs/security-checker          v3.0.1             A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.1             Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               2.8.1              Symfony MonologBundle
symfony/swiftmailer-bundle           v2.3.8             Symfony SwiftmailerBundle
symfony/symfony                      v2.7.5             The Symfony PHP framework
twig/extensions                      v1.3.0             Common additional features for Twig that do not directly belong in core
twig/twig                            v1.22.2            Twig, the flexible, fast, and secure template language for PHP
```

**Comment by xabbuh** [comment]
It looks like the issue in Doctrine DBAL was not fully resolved. Someone reported the same in doctrine/DoctrineBundle#461. For now, you can probably downgrade `doctrine/dbal` to `2.4.x` or configure your server version explicitly.

**Comment by fabpot** [comment]
Can we close this issue as this is not related to Symfony?

**Comment by k0pernikus** [comment]
@xabbuh  You were correct that downgrading dbal to 2.4 solved the issue.

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                
  - Removing doctrine/dbal (v2.5.2)
  - Installing doctrine/dbal (v2.4.4)
    Downloading: 100% 

$ php app/console doctrine:database:create
Created database for connection named `local_api`

@fabpot Yes, I think so.

**Comment by gognos** [comment]
I have the same problem on linux. Basically getting  The command "doctrine:database:create terminated with an error code: 1". It failed to create a database, and if the database exists and you try and reset you get    "doctrine:database:drop" terminated with an error code: 1. If you create the database first and choose No when asked to reset installation occurs without worry.

**Comment by k0pernikus** [comment]
@gognos What you can also try is setting the server expliclitly:

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname:         local_api
                user:           root
                password:       null
                host:           localhost
                driver:         pdo_mysql
                server_version: '5.5' # in case you are using mysql 5.5
```

**Comment by HeahDude** [comment]
Thanks @k0pernikus, you saved my day :) `server_version` is the right fix for me!

**Comment by ylastapis** [comment]
Thanks @k0pernikus, same as above with latest configuration

```
doctrine:
    dbal:
        server_version: '5.5' # in case you are using mysql 5.5
...
```

**Comment by OskarStark** [comment]
Setting this to

```yaml
doctrine:
    dbal:
        server_version: '5.7'
...
```

solved my problem, too 👍

**Comment by crashev** [comment]
@k0pernikus solution works, but why do we have to set it expliclitly to make it work?

**Comment by litvinab** [comment]
just for notice `server_version` instruction should be under `connection` section if you have few connections, otherwise it won't work.

```
doctrine:
    dbal:
        default_connection: master
        connections:
            master:
                driver:   "%database_driver%"
                host:     "%database_master_host%"
               ...
                server_version: '5.6'
                slaves:
                    slave1:
                        host:     "%database_slave_host%"
                        port:     "%database_slave_port%"
                        dbname:   "%database_slave_name%"
                        user:     "%database_slave_user%"
                        password: "%database_slave_password%"
                        charset:  UTF8
```

**Comment by duraki** [comment]
I'm getting this same error with **Symfony 4** & `doctrine/doctrine-bundle": "^1.8`. I tried hardcoding `server_version` but it's the same after cleaning the cache. I'm on MariaDB 10.2.8. Also tried different server versions but ain't helping.

```
doctrine:
  dbal: 
    charset: UTF8
    driver: mysqli
    url: "mysqli://root:password@maxscale"
    server_version: "10.2.8"
```

Any connection instance throws:

> An exception occurred in driver: failed to create new session

> failed to create new session
