### ISSUE TITLE
[ExpressionLanguage] Add contains operator

### ISSUE THREAD

**Issue by xavren** [symfony/symfony#16153]
It would be nice to have an operator to test existence of a substring in a string rather than use matches

"foobar" contains "bar"

**Comment by Ribeiro** [comment]
@xabbuh Maybe I can make a PR for this, but I´m not a PHP expert so where would be the best location for the contains operator? =)

**Comment by xabbuh** [comment]
@Ribeiro @xavren already opened a pull request (see #16154).

**Comment by Ribeiro** [comment]
@xabbuh Got it ;)

**Comment by xavren** [comment]
No need for this apparently
