### ISSUE TITLE
[2.8][Critical] Cache annotations folder bug

### ISSUE THREAD

**Issue by crash21** [symfony/symfony#16167]
Hello,

Starting from commit a1c7af1fbfb5ab412c930d76bd51ab188336caaf in Windows 7 I am starting to get an old bug. The cache/annotations folder instead of files has folders and these many other folders and so on. Cache clear command not ending and fails as it reaches windows path limit.

Check screenshot to see, I think it was happening some time in the past as well.

![symfony_bug](https://cloud.githubusercontent.com/assets/3415953/10342584/60af0e84-6d22-11e5-9afe-9a5cf6a930da.jpg)

To make it clear everything is fine until and 45a5b005d5f46086f4f1f176ce7b3ec7fb0df2ab, bug starting to happening in a1c7af1fbfb5ab412c930d76bd51ab188336caaf until 5326df084ebbf84273120384b06786af47139262  so far.

Anyone please has an idea? It's confirmed from 2 different projects and 2 different dev PCs.

Thanks a lot.

**Comment by peshi** [comment]
I can confirm this too, same issue here.

**Comment by Tobion** [comment]
This is a doctrine cache bug that will be fixed by doctrine/cache#94

**Comment by Ocramius** [comment]
This was fixed via doctrine/cache#94 and via doctrine/cache 1.5.0
