### ISSUE TITLE
getQueryString in a forwared request returns the query-string from the original request

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony#16169]
Is it an expected behavior: in a controller that receives a request from the other controller using a `forward()` call, calling `$request->getQueryString()` returns the original query-string? (`Request $request` is injected as an argument in the controller action definition).

As a workaround I had to replace `$request->getQueryString()` with `http_build_query($request->query->all())`.

**Comment by rpg600** [comment]
I think this it is a normal behavior: when you forward a request you actually duplicate the master request which is based on the php globals and do a sub request which is not, so you will have the same $_SERVER variable.
An easy solution is to call the method `overrideGlobals()` on the sub request which overrides the php globals according to the request parameters.

**Comment by jakzal** [comment]
This is a common problem related to mutability of the request class. See #6406.
