### ISSUE TITLE
Reading annotation cache for @Sensio\Bundle\FrameworkExtraBundle\Configuration\Route annotation fails 

### ISSUE THREAD

**Issue by sgehrig** [symfony/symfony#16168]
Reading a cached ``Sensio\Bundle\FrameworkExtraBundle\Configuration\Route`` annotation fails with

    Attempted to call an undefined method named "__set_state" of class "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route"

since the annotation cache has been switched to a ``Doctrine\Common\Cache\PhpFileCache`` instance. This happened with commit [ca69fa340c97e5ffc3287ca4e4c4574690dc2847](https://github.com/symfony/symfony/commit/ca69fa340c97e5ffc3287ca4e4c4574690dc2847) but may be a merge conflict.

**Comment by Tobion** [comment]
Yes the annotation cache cannot use `PhpFileCache` as it only supports objects that are `var_export`able, i.e. implement `__set_state` see https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/PhpFileCache.php#L81
So we need to use the generic FilesystemCache instead which uses `serialize`.

**Comment by nicolas-grekas** [comment]
@sgehrig can you please see if #16173 solves this issue?

**Comment by sgehrig** [comment]
Yes, @nicolas-grekas - that seems to solve the issue.
