### ISSUE TITLE
is there a easy way to add a event listener for a  specific firewall?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#16172]
I have several firewalls , such as admin, main,  I wanna add a event listener to the admin firewall ,not main,  because some checks can only be doing for admin firewall,  I know that we can do this like this post said [How to Create a custom Authentication Provider](http://symfony.com/doc/current/cookbook/security/custom_authentication_provider.html),but  I think this is a little complex for such need, anyone has a easy way to do this please?

**Comment by videni** [comment]
further explain, that post is about authentication when a user logins, but my case is that a user has authenticated successfully,and some works need to be done for all actions behind the admin firewall, not for a certain action.

**Comment by iltar** [comment]
You can use Authorization for that using either the `firewall.access_control` options or using `@Security`.  

If you want to do this check only once, you can use a login listener (on successful logins) and check the firewall via the token (`$providerKey` for some of them). If you want to add this check during login, you might be interested in configuring your own UserChecker, this feature will be added as of 2.8, but can already be "hacked" into 2.7. This will allow you to add a user checker per firewall.

**Comment by mheki** [comment]
If you can use 2.8 Guard component would be an easy solution for your problem.
Simply add a specific authenticator under your admin firewall and add required logic into `onAuthenticationSuccess` method

**Comment by lyrixx** [comment]
I did not test the following solution, but it should work and it's easy to implement.

You can add an [`access_control`](http://symfony.com/doc/current/cookbook/security/access_control.html) rule that match the same URL pattern than your firewall match (something like `/admin`.
On that rule, set the `role` to something like `ADMIN`. Then add a [voter](http://symfony.com/doc/current/cookbook/security/voters.html), that vote on  `ADMIN` role.

**Comment by videni** [comment]
@iltar , your way works for me.
