### ISSUE TITLE
Removal of development & testing files using .gitattributes

### ISSUE THREAD

**Issue by EmanueleMinotto** [symfony/symfony#16174]
Considering the number of downloads and to speed up the download, what about the removal of development & testing files using `.gitattributes`?

Reference: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by javiereguiluz** [comment]
This has been asked several times in the past: https://github.com/symfony/symfony/issues?utf8=%E2%9C%93&q=is%3Aissue+gitattributes  ... and it has always been rejected.

**Comment by EmanueleMinotto** [comment]
Ops, you're right.
