### ISSUE TITLE
kernel.name parameter will differ if cache warmup is used

### ISSUE THREAD

**Issue by matthewpeach** [symfony/symfony#16180]
Because a "TempKernel" with a name that differs to the real kernel name is used to warm up the cache in ```CacheClearCommand```, the ```kernel.name``` container parameter will be cached with a different value depending on whether warmup has occurred.

Simple demonstration:

```bash
# install latest symfony into a fresh project
php composer.phar create-project symfony/framework-standard-edition warmup-bug "2.7.*" --stability=dev

# clear the cache and warmup
php app/console cache:clear

# kernel.name is now "ap_"
grep kernel.name app/cache/dev/appDevDebugProjectContainer.php

# clear the cache without warmup
php app/console cache:clear --no-warmup

# run console with no arguments to cause a cache build
php app/console

# kernel.name is now "app"
grep kernel.name app/cache/dev/appDevDebugProjectContainer.php
```

Related code from ```CacheClearCommand->getTempKernel```:

```php
// the temp kernel class name must have the same length than the real one
// to avoid the many problems in serialized resources files
$class = substr($parentClass, 0, -1).'_';
// the temp kernel name must be changed too
$name = var_export(substr($parent->getName(), 0, -1).'_', true);
```

```php
public function getName()
{
    return $name;
}
```

**Comment by jakzal** [comment]
@jfsimon do you remember why the kernel name needed to be changed as your comment in https://github.com/symfony/symfony/commit/cc3a40ed7868d537fa2c59a6adf437795467ca5f#diff-ba3117e514933eed435af61c69ae9830R158 doesn't explain this?

**Comment by jfsimon** [comment]
@jakzal I guess it's because both kernels are started at the same time, but I don't remember exactly!

**Comment by jakzal** [comment]
The kernel name is used to generate the container class name, so indeed it needs to be different :+1:

**Comment by matthewpeach** [comment]
Just testing the fix made in #17183.

This does correct the cached value of ```kernel.name```, so grabbing it manually from the container works, but it doesn't fix the injection of ```kernel.name``` to a service. (Because the value came from ```$tempKernel``` during service generation.)

I was going to suggest that the temp kernel's name could be randomised, so a complete string replacement could be performed with minimal chance of replacing the wrong thing. But *"the temp kernel class name must have the same length than the real one to avoid the many problems in serialized resources files"* might rule that idea out.

Be ideal if the right name was used during generation but I'm assuming that's complicated. (Otherwise it would work that way already, right?)

Continuing to avoid the injection of ```kernel.name``` for now.

**Comment by jakzal** [comment]
@matthewpeach out of curiosity, what's the use case for injecting the kernel name to services? 

Does your problem persist if you override `getName()` in your kernel and return a fixed value?

**Comment by shane-l** [comment]
@jakzal our project (I work with @matthewpeach) uses 4 kernels which share some core services.

We inject the kernel name so our Sentry error dispatcher (which is shared across kernels) knows which kernel/site the error occurred on.

**Comment by jakzal** [comment]
I'm not sure what else we could do in the core. 

Did you try overriding `getName()` in your kernels and return a fixed value?

Also, you could try to inject the parameters with an expression:

```php
my_service:
    class: Foo
    arguments: ["@=parameter('kernel.name')"]
```

If any of these solves your issue we should probably document this problem with `kernel.name`.

**Comment by matthewpeach** [comment]
> Did you try overriding getName() in your kernels and return a fixed value?

This doesn't solve the problem; the value injected is still ```ap_``` instead of ```app```.

> arguments: ["@=parameter('kernel.name')"]

This does solve the problem and seems like a reasonable way to do it. :+1:

Using this method, the service as cached in the project container is:

```php
return $this->services['the_name_of_our_service'] = new TheNameOfOurClass($this->getParameter("kernel.name"));
```

Rather than:

```php
return $this->services['the_name_of_our_service'] = new TheNameOfOurClass('ap_');
```

Can confirm that our service has the correct value as well:

```php
$ourClass = $kernel->getContainer()->get('the_name_of_our_class');
dump($ourClass->getKernelName()); // "app" is output
```
