### ISSUE TITLE
[2.7] Generate entities required database connection

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#16188]
When i use this command to generate entity setters and getters:

    ./console doctrine:generate:entities AppBundle

I got this message:

    [Doctrine\DBAL\Exception\ConnectionException] 
    An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused

MySQL was installed on server only.

Sorry for my bad english.

**Comment by xabbuh** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/symfony2) to ask support questions. However, the `doctrine:generate:entities` command is not part of Symfony, but is provided by the Doctrine project.

**Comment by zacharyzh** [comment]
No. it's NOT a question. It's a bug. And this bug does not exists in previous version of Symfony.

**Comment by jrobeson** [comment]
it has it's own repository @zacharyzh  so report bugs there. they won't be accepted here.

**Comment by zacharyzh** [comment]
Got it.
