### ISSUE TITLE
[Symfony Console] requires Event Dispatcher for mocks

### ISSUE THREAD

**Issue by Gisleburt** [symfony/symfony#16181]
I don't know if this is a legitimate issue, however it is causing me a fair bit of pain.

I'm adding composer/composer to my project to trigger composer commands as part of a build processes. In order to unit test this, I need to mock Composer. The problem is that when I mock it, I get an Exception

`ReflectionException: Class Symfony\Component\EventDispatcher\EventDispatcherInterface does not exist`

It seems that Composer requires Symfony Console and `Symfony\Component\Console\Application` uses `Symfony\Component\EventDispatcher\EventDispatcherInterface`. 

However, Event dispatcher is only in require-dev. See: https://github.com/symfony/console/blob/master/composer.json

Further information can be found on my StackOverflow question here: http://stackoverflow.com/questions/32975108/mock-composer-in-phpunit-is-actually-running

I could resolve the issue by requiring it as one of my own dev dependencies, or by requiring-dev on all packages, however since I'm not developing Console, nor needing Event Dispatcher for my own code, it seems like I should be able to mock the console without issue.

Any thoughts?

**Comment by stof** [comment]
My suggestion is to use Prophecy (supported natively in PHPUnit 4.5+) or Mockery to create your mocks.
Typehinting a non-existent class is totally valid in PHP. But PHPUnit_Mock_Object does not support this case when creating a mock, while Prophecy and Mockery do support it.

**Comment by Tobion** [comment]
Closing as similar to #8200
