### ISSUE TITLE
[3.0/2.8] Forms as services, extended type, ArrayChoiceList

### ISSUE THREAD

**Issue by petforsberg** [symfony/symfony#16199]
I use SF 2.8 and try to prepare app for 3.0, watching depracated notes.

According to upgrade guidelines https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md getName() method was deprecated for form types. This however brings up some questions.

**1. How to access form defined as service?**
Previously, forms as services were accessed by aliases. Now there will be no aliases. How can I access this service then?

**2. Extended type**
For PHP 5.4 which I use for the app now, I cannot access ::class property. Temporily I'm using simply a string as name, such as:
    
    public function getExtendedType()
    {
        return 'Symfony\Component\Form\AbstractType';
    }

for my form types.

However, with this solution, SF depracated note still occurs:

    Returning a type name from FormTypeExtensionInterface::getExtendedType() is deprecated since version 2.8 and will be removed in 3.0. Return the fully-qualified type class name instead.

How can I get rid of this depracated note then?

**3. ArrayChoiceList**
Can I use Symfony\Component\Form\ChoiceList\ArrayChoiceList (using ChoiceListInterface inferface) somehow?

The problem is that with my current 2.8 SF, I get an error that SF expects Symfony\Component\Form\FormTypeInterface:

    An exception has been thrown during the rendering of a template ("Expected argument of type "string or Symfony\Component\Form\FormTypeInterface", "Symfony\Component\Form\ChoiceList\ArrayChoiceList" given")

Code in my custom Form Type:

            ->add('scope', new ArrayChoiceList($choices), array(
                                            //'choices' => $choices,
                                            'required' => false
                                        ))

BTW note commented "//'choices' => $choices," line - I removed it, but is still brings up questions why ArrayChoiceList is supposed to be *instantiated*, while other Form Types should be passed as *classes names* to "add" method of the form builder?

**Comment by WouterJ** [comment]
For (1), just use the FQCN. The Form component takes care of loading the service in such case.

You cannot extend AbstractType in (2). Use a concrete form type, like `Symfony\Component\Form\Extension\Core\Type\FormType`.

**Comment by petforsberg** [comment]
Thanx.

(1) ok, I'm actually doing it this way, but your reply ensures me that I'm doing it the proper way. I wasn't sure if using a string such as Symfony\Component\Form\Extension\Core\Type\FormType in place where service should be used doesn't add some overhead (e.g. if it was treated by SF as name, accidentally being a FQCN class name).

(2) Should I replace AbstractType with the Symfony\Component\Form\Extension\Core\Type\FormType then?

**Comment by Tobion** [comment]
(2) Yes.

Also please ask support questions on StackOverflow. We don't use github issues for questions. Thanks.

**Comment by petforsberg** [comment]
Ok. But isn't a deprecation note in this case an issue?

About (3), it seems to be an issue as well?

**Comment by Tobion** [comment]
You cannot add the ChoiceList as a form type. It must be something like `->add('scope', ChoiceType::class, array( choice options ))`

**Comment by petforsberg** [comment]
Thanx, I know.

But ChoiceType is now depracated, isn't it?

**Comment by Tobion** [comment]
Where does it say so?

**Comment by petforsberg** [comment]
I have the following deprecation message in SF 2.8:

    The Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.

**Comment by Tobion** [comment]
That is the CoiceList not the ChoiceType

**Comment by petforsberg** [comment]
Right. But I get the message anyway, here's my code:

    ->add('mediaTypes', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType' //....
