### ISSUE TITLE
LDAP Extension Requirement

### ISSUE THREAD

**Issue by michaelcullum** [symfony/symfony#16204]
Requiring `symfony/symfony` now will include the LDAP component which requires `ext-ldap` in it's own `composer.json` but composer will never check for `ext-ldap` when requiring `symfony/symfony`, only when composer specifically requires `symfony/ldap`.

Adding `ext-ldap` to the symfony/symfony `composer.json` also could be problematic as then it's adding an extra environment dependency (and a less common one) that the vast majority of symfony installations do not need.

**Comment by nicolas-grekas** [comment]
You said everything, adding ext-ldap to symfony/symfony is not an option and we can't do better :-)
