### ISSUE TITLE
[HttpKernel] Exceptions Responses are automatically sent

### ISSUE THREAD

**Issue by lce-fr** [symfony/symfony#16205]
When an exception occurs in dev environment, the exception is catched and converted to a response which provides our nice symfony exceptions. 

However it is sent automatically by Symfony\Component\HttpKernel\HttpKernel::terminateWithException() which does:

```php
$response = $this->handleException($exception, $request, self::MASTER_REQUEST);
$response->sendHeaders();
$response->sendContent();

```

What is the reason for breaking the Request->Response workflow for exceptions ? You could  send the response and let the front controller call response->send() as usual. 

I am integrating a symfony app with a reactphp event loop. With such setup, I cannot send exceptions response to the client, they are printed to the console sadly displaying the whole markup. 

[edit] I tried to override the aforementioned method but since handleException is private, I cannot call it from my subclass.

My current option is to output to an error.html file and display it with my browser.

**Comment by peterrehm** [comment]
This might help you: http://symfony.com/doc/current/cookbook/controller/error_pages.html#working-with-the-kernel-exception-event

**Comment by peterrehm** [comment]
@Ice-fr Did this solve your problem?

**Comment by javiereguiluz** [comment]
Closing it because lack of feedback usually means that the problem was solved. If the resource provided by @peterrehm didn't solve your problem, please reopen this issue. Thanks!

**Comment by fabpot** [comment]
Fixed now :)
