### ISSUE TITLE
errorNames attribute in @Assert\NotBlank

### ISSUE THREAD

**Issue by TaqiOfficial** [symfony/symfony#16214]
New to symofny framework, while coding using phpstrom it gives an optioin errorNames in NotBlank Assertion. I try to find it on documentatino but didn't get the details.
```
  /**
     * @var string
     *
     * @ORM\Column(name="course_code", type="string", length=30, unique=true)
     * @Assert\NotBlank(message="Course Code cannot be blank", errorNames={})
     */
    protected $courseCode;
```

**Comment by stof** [comment]
``errorNames`` is an internal property of the Constraint class. It does not make sense in the annotation (but the PhpStorm plugin does not know it)
