### ISSUE TITLE
YAML incorrectly parses tags starting with @ and `

### ISSUE THREAD

**Issue by neclimdul** [symfony/symfony#16234]
http://www.yaml.org/spec/1.2/spec.html#id2774157 specifies that the @ and ` characters are reserved for future use. Tags beginning with them are invalid unless quoted. 

Symfony's YAML component allows these to be parsed without fail which when used as direct or implicit validation of correctness allows developers to write invalid YAML.

**Comment by lsmith77** [comment]
I guess we could deprecate this behavior? IIRC we have been adding quotes in relevant places in the SE since a while now already.

**Comment by neclimdul** [comment]
If deprecated, could that deprecation come with some sort of "strict" toggle?

**Comment by LionsAd** [comment]
We would like to use this 'strict' mode for Drupal 8 - to ensure that no one relies on bad YAML files being parsed correctly and later gets bitten by that on production where the yaml extension is installed.

**Comment by lsmith77** [comment]
in general we work with deprecation warnings, which Drupal could of course interpret as failures, thereby making it a strict mode. but I could imagine a strict mode also. did either of you investigate creating a PR to make this happen?

**Comment by neclimdul** [comment]
I looked at it a while back but wasn't really able to figure out where the change should happen.

**Comment by derrabus** [comment]
This rule applies to tags only? So, in string values the `@` character may still me used unquoted?

**Comment by WouterJ** [comment]
This applies to any plain scalar

**Comment by derrabus** [comment]
In that case, a lot of apps/bundles will get fun here. :disappointed: 

```YAML
my_service:
    class: MyProject\MyClass
    arguments:
        - @my_other_service
```

**Comment by WouterJ** [comment]
Yes, indeed. Symfony and the documentation has changed its source to quote these strings for some years already, but I can imagine many bundles still having these unquoted. However, fixing it is quite easy and works on all versions (quoting a value that doesn't have to be quoted is never a problem), so maybe deprecating it isn't that much of a trouble.

**Comment by derrabus** [comment]
I know, the fix is trivial. I just wanted to point out that there's a lot of code out there that will be affected.

**Comment by maryo** [comment]
I think the strict mode is a better choice than deprecation. At least for me :). I still prefer the unquoted variant event it's invalid. It just looks ugly when it's quoted. It looks more like a reference to a service than a string when unquoted. I even recompiled libYaml and php-yaml to also accept this on project which uses this extension.

**Comment by fabpot** [comment]
We need to manage BC as everywhere else: deprecation warnings then removal. We've recently deprecated another behavior that was not in the YAML spec; I deprecated the "feature" in 2.8 (see #16201) and removed it in 3.0 (see #16203). We must do the same here.

**Comment by neclimdul** [comment]
@fabpot that seems entirely reasonable, thank you.

**Comment by fabpot** [comment]
@neclimdul see #16285 for the PR on 2.8
