### ISSUE TITLE
Best Practice Checker

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16243]
I think it would be nice to have a simple script which will check your code for Best Practice rules. It would just be a command or script file for developers. It could be like the ``app/check.php`` script.

What do you think about this idea?

**Comment by theofidry** [comment]
While the idea may be interesting, it's a task far more suited to a third-party tool like [Scrutinizer](https://scrutinizer-ci.com/), [SensioLabs Insight](https://insight.sensiolabs.com/) and such IMO.

**Comment by TomasVotruba** [comment]
I could give a help with this, if needed.

**Comment by Taluu** [comment]
Isn't this wgat https://github.com/FriendsOfPHP/PHP-CS-Fixer already does (and fixes the code too) ?

**Comment by JHGitty** [comment]
@Taluu There are more complex Best Practices for Symfony projects.
http://symfony.com/doc/current/best_practices/index.html

A "Best Practice Checker" could try to detect any violation against these Best Practices. This would be helpful for developers. It should just be a warning, the developer can choose if they really want to ignore any Best Practice. But it is important for new developers to know them.

**Comment by iltar** [comment]
I'm -1 for warnings, if anything it should give tips and not fail any checks if it's not according to the best practices. There's a lot of best practices I agree with but also some I don't (based on experiences).

**Comment by JHGitty** [comment]
@iltar You are right, "tips" are better. :+1:

**Comment by fabpot** [comment]
Closing as this definitively something that could be done by a third party tool.

**Comment by javiereguiluz** [comment]
@JHGitty at the end of this week, a new "Deprecation Detector" tool is going to be released for Symfony. Maybe you can reuse it to create a "Best Practice Detector" tool.
