### ISSUE TITLE
[Form] [Feature request] ajax forms

### ISSUE THREAD

**Issue by Tetragramat** [symfony/symfony#16249]
Hi I'm using symfony few years for a bit complex website full of a bit dynamic data.
I found that I need ajax forms, but complex ajax forms, not just change few text inputs by changing one select box.

I was trying figure out how do it and found only one possible way. Triple forms.
I'm bad in english, so here is an example:

``` php
// request form loads data into entity and makes possible for other forms generate fields
$requestForm = $this->createForm(new UnitType(), $unit);
$requestForm->handleRequest($request);

if ($request->get('isChange', false)) {
    // ajax form is clean form without validator messages, it also generates form fields
    $ajaxForm = $this->createForm(new UnitType(), $unit);
    // return some ajax response
}

// generates form fields and makes self submitted
$form = $this->createForm(new UnitType(), $unit);
$form->handleRequest($request);

if ($form->isValid()) {
    // process submited form
}
// return some standard response
```

I'm sucessfully using this about 2 years, but I think we need an upgrade.
I want siplify this into only single form.
Example:

``` php
$form = $this->createForm(new UnitType(), $unit);
$form->handleRequest($request);
$form->rebuildForm(); // I will explain this next

if ($request->get('isChange', false)) {
    $form->clearValidatorMessages();
    // return some ajax response
}

if ($form->isValid()) {
    // process submited form
}
// return some standard response
```

As you can see, all I need is reset validator messages (that sound pretty easy right?) and rebuild form.
Rebuilding form is not so simple, because everything dynamic use listeners. So, if you just call buildForm again, nothing will happen, because I'm modifing my forms with PRE_SET_DATA event.
Here is an simple example:

``` php
$builder->add('valueType', 'choice', array(
    'choices' => array(1 => 'value', 2 => 'percent'),
    'attr' => array(
        'class' => 'js-ajax-submit-on-change', // this is telling my js to submit form if this value change
    ),
));
$builder->add('value');

$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
    if ($event->getData()->getValueType() === 1) {
        $event->getForm()->add('value', 'number');
    } else {
        $event->getForm()->add('value', 'percent');
    }
}
```

So, I need to call again PRE_SET_DATA event.
I believe, you will find a way how to implement this feature.

Writing in english complex things is for me a bit hard, but I believe somebody will understand what I'm talking about.

**Comment by JHGitty** [comment]
Could you provide a full example as fork of the Symfony Standard Edition?

**Comment by Tetragramat** [comment]
a full example of what? Triple forms I'm using, what are just three identic forms in row? Or do you want non-existent example of simplified version?

I'm here just asking for the feature that would simplify creating ajax forms. I do not know how exactly do that. If I knew that, I would show you fork for review. 
Last thing is, I do not need that. Triple forms work fine. It is task for others to say what they will do. If they try simplify this, or add triple forms in documentation as example of ajax form, or just ignore this.

**Comment by kprzybylski** [comment]
If I understand you properly you can use http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html#suppressing-form-validation

**Comment by Tetragramat** [comment]
Yes, this looks like it would resolve part with validator messages for ajax form response, but still I need use second form for setting form fields.

**Comment by Tetragramat** [comment]
I think I have resolved this.
I added into form two listeners:

```php
$builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($options) {
	if ($options['isChange']) {
		$event->stopPropagation();
	}
}, 900);

$builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) use ($options) {
	if ($options['isChange']) {
		$event->getDispatcher()->dispatch(FormEvents::PRE_SET_DATA, new FormEvent($event->getForm(), $event->getData()));
	}
});
```

action:

```php
$form = $this->createForm(new UnitType(), $unit, array('isChange' => $request->get('isChange', false)));
$form->handleRequest($request);

if ($request->get('isChange', false)) {
	// return some ajax response
}

if ($form->isValid()) {
    // process submited form
}
// return some standard response
```

This work almost same as triple forms.

And I have question: 
Can it break something? Im calling second time PRE_SET_DATA event on same form inside SUBMIT event.

**Comment by Tetragramat** [comment]
I tried solve this with just form events, but it is not possible. Only possible way to build form fields and set data into entity is calling submit again in second form.

**Comment by xabbuh** [comment]
This does not look necessary to me. The problem itself can be solved with form events. If you need some help with them, I suggest to use one of the [support channels](https://symfony.com/support). Thank you for understanding.
