### ISSUE TITLE
Improve a deprecation message related to routes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#16246]
When using `_method` in some YAML route, you get this deprecation message:

```
The "_method" requirement is deprecated since version 2.2 and will be removed in 3.0.
Use the setMethods() method instead:
```

We could improve it as follows:

```
The "_method" requirement is deprecated since version 2.2 and will be removed in 3.0.
Use the "methods" option instead:
```

**Comment by stof** [comment]
And in Yaml, we could even provide the route name in the message, as we have it.

**Comment by javiereguiluz** [comment]
I can submit a PR, but I confess I didn't find the location where that deprecation is triggered.

**Comment by xabbuh** [comment]
@javiereguiluz It's triggered in the [sanitizeRequirement()](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Route.php#L652) method in the `Route` class. By the way, we improved the message the user gets in #14886. Could you check why this does not work for you?

**Comment by javiereguiluz** [comment]
Closing it as "fixed". When testing this in the Symfony Demo applicaiton, I get the new and better deprecation message:

![route_deprecation](https://cloud.githubusercontent.com/assets/73419/10564513/b08178d2-75b7-11e5-8ebf-4d45264c6c11.png)
