### ISSUE TITLE
[sensiolabs insight] Deprecated class FileCacheReader / ActionsExtension

### ISSUE THREAD

**Issue by Snowbaha** [symfony/symfony#16242]
Hi,

I am using SensioLabs Insight to check my Symfony 2.7.5 project and I have this new error : 

http://vgy.me/VL6qs4.png

> The 846826759222eeac8b8b34e803951c07468c406717a71aa7cd45edcdf3463c61_90 service uses the Symfony\Bundle\TwigBundle\Extension\ActionsExtension class, which has been deprecated in Symfony 2.2.

> The annotation_reader service uses the Doctrine\Common\Annotations\FileCacheReader class, which has been deprecated in Doctrine Annotations 1.2.3. Use the Doctrine\Common\Annotations\CachedReader class instead.

I update all the the composer.json but I still have this issue. I contacted the support who told me that the problem come from the Symfony build itself.

What do you think?

Is it something know?

**Comment by nicolas-grekas** [comment]
ActionsExtension must be kept for backwards-compatility, there is no way around.
FileCacheReader usage has been fixed in 2.8.
Thanks for reporting.

**Comment by tvlooy** [comment]
See here for a fix https://github.com/symfony/symfony/issues/16872#issuecomment-171798705
