### ISSUE TITLE
[Form] get rid of ValidatorInterface deprecation notices

### ISSUE THREAD

**Issue by craue** [symfony/symfony#16248]
I'm getting a lot of deprecation notices since #16101: **Passing an instance of Symfony\Component\Validator\ValidatorInterface as argument to the Symfony\Component\Form\Extension\Validator\EventListener\ValidationListener::__construct method is deprecated since version 2.8 and will be removed in 3.0. Use an implementation of Symfony\Component\Validator\Validator\ValidatorInterface instead: 1335x**, see [Travis log](https://travis-ci.org/craue/CraueFormFlowBundle/jobs/85108589#L327) (ignore the other notices).

Since I'm not using the validator directly, I guess some code of Symfony itself needs to be updated to get rid of them.

**Comment by stof** [comment]
See my PR for the fix. The condition detecting the deprecated usage was wrong

**Comment by craue** [comment]
I cannot say if the fix is correct, but at least the deprecation notices will be gone. :smirk:
Thanks.
