### ISSUE TITLE
[Console] The new backrounds are unreadable in putty

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#16257]
I run console commands mostly via putty. 
I haven't seen all the backgrounds yet, but at least the green one is unreadable.

![untitled](https://cloud.githubusercontent.com/assets/450008/10536246/f88e4e7c-73e9-11e5-8407-ff1e458d74b3.png)

**Comment by javiereguiluz** [comment]
I have a question about this: when running PHPUnit tests, do you have the same issues with the result bar or is it more readable?

![phpunit_green_background](https://cloud.githubusercontent.com/assets/73419/10564524/f5d55e62-75b7-11e5-8991-211257858673.png)

**Comment by mvrhov** [comment]
The tests don't pass in my environment so I cannot answer that.
```FAILURES!
Tests: 14639, Assertions: 27363, Errors: 11, Failures: 11, Skipped: 843, Incomplete: 12.
```

**Comment by stof** [comment]
@mvrhov use a subset of the testsuite which passes, by passing a path to some tests

**Comment by mvrhov** [comment]
For that I get black text on green background:

![untitled](https://cloud.githubusercontent.com/assets/450008/10577891/e8de1f70-766e-11e5-98fe-133e2ea437cf.png)

**Comment by javiereguiluz** [comment]
PHPUnit uses:

  * `'fg-black, bg-green'` for success ([see code](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/ResultPrinter.php#L356))
  * `'fg-black, bg-yellow'` for warnings ([see code](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/ResultPrinter.php#L367))
  * `'fg-white, bg-red'` for errors ([see code](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/ResultPrinter.php#L388))

Maybe we should do the same [in these functions](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Style/SymfonyStyle.php#L171-L201) defined in the `SymfonyStyle` class.

**Comment by xabbuh** [comment]
seems reasonable
