### ISSUE TITLE
[Translation] Improve the pluralization rule for French

### ISSUE THREAD

**Issue by maelsoucaze** [symfony/symfony#16256]
The [current pluralization rule for French](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Translation/PluralizationRules.php#L140) is not exactly right. Numbers like negatives (like *-4*) and decimals of 1 (like *1.78*) should also be considered as singulars, not plurals. Correct me if I'm wrong, but the current rule sets only 0, decimals of 0, and 1, as singulars, and the rest as plurals.

Something like that is better:
```php
return [
    if ($number >= 0 and $number < 2) {
        return 'singular';
    }
    else {
        return 'plural';
    }
]
```

(Sorry, I'm not a coder, so I can't really provide the appropriate patch myself)

**Comment by aitboudad** [comment]
Hi,
The pluralization rule expect `number` to be an integer and not a float type.
-  `Numbers decimals`: if we pass [($number  = (int) 1.78 = 1)](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Translation/Translator.php#L233) should be considered as singulars which is the current behavior.
- `Numbers negatives`: IMO the number should be  `>= 0`

**Comment by maelsoucaze** [comment]
I see you closed it, but what's about `>= 0`?

**Comment by stof** [comment]
CLDR pluralization rules only support non-negative integers. And this is logical: language pluralization rules are based on a quantity, which cannot be negative or non-integer. So there is no way to pass such value in a pluralization rule selector and have it give you a meaningful value.

**Comment by maelsoucaze** [comment]
Okay, thanks for the explaination! :)

**Comment by kylekatarnls** [comment]
> The pluralization rule expect `number` to be an integer and not a float type.

It should not! As explained @ghost 1.5 is singular in French, plural in English, so you can't have both working if you force the integer cast, remove this typing please:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/IdentityTranslator.php#L57

@fabpot There is still a linguistic bug about decimal, this should be re-open and decimal numbers should be properly handled in different languages groups according to language plural rule, not truncated for every language.
