### ISSUE TITLE
ResourceInterface::isFresh() deprecations

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#16260]
*(If you consider this as a user-support issue, close it and I'll add a question on StackOverflow)*

-----

I'm migrating a large Symfony application to 2.8.x-dev. When runing the test suite, I'm getting **tens of thousands** of deprecation messages like the following:

```
Resource checking through ResourceInterface::isFresh() is deprecated since 2.8
and will be removed in 3.0
```

In the **UPGRADE TO 2.8** file you can read something about [this Config deprecation](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#config). But we don't have custom resources, so I guess this is coming from Symfony.

Is this normal? Is this a well-known deprecation that still hasn't been fixed in 2.8.x-dev? Am I doing something wrong? Any clue to solve this? Thanks.

**Comment by iltar** [comment]
What about 3rd party bundles? They have not had the chance to implement it yet.

**Comment by javiereguiluz** [comment]
@iltar OK, that certainly might be the reason. I'll check bundles one by one. Thanks!
