### ISSUE TITLE
[Dependency Injection] Question about RemoveUnusedDefinitionsPass

### ISSUE THREAD

**Issue by mickadoo** [symfony/symfony#16275]
I read the symfony guidlines that third party services should be defined as private [here](http://symfony.com/doc/current/cookbook/bundles/best_practices.html).

But when I tried to do this and use my bundle (let's call it `AddSuperCommandBundle`) in another project (using composer) the service was removed by the `RemoveUnusedDefinitionsPass` because it was not referenced anywhere. The service is only used internally in the `AddSuperCommandBundle` bundle and shouldn't need to be used outside it. Does this mean I should avoid using internal services when creating a bundle?

**Comment by xabbuh** [comment]
Well, you need to inject the service in another service. Then it would not be removed by the compiler pass. If you want to retrieve the service using the `get()` method, the service should **not** be private.

**Comment by Tobion** [comment]
Please use Stackoverflow for questions. We only use github issues for bugs and features.
