### ISSUE TITLE
asset component does not seem to work with imagine_filter

### ISSUE THREAD

**Issue by svassaux** [symfony/symfony#16279]
The following does not work anymore:

```twig
<img src="{{ asset('images/user.png', 'images') | imagine_filter('default') }}" alt="Image de profil" class="img-circle whitebg" />
```

see http://stackoverflow.com/questions/33200339/symfony-2-7-asset-component-not-working-with-imagine-filter

**Comment by stof** [comment]
``Does not work`` does not help. What is the issue you have ?

**Comment by stof** [comment]
And IMO, this looks like a bug in the imagine_filter. The ``asset`` is able to set a version in the URL since Symfony 2.0 (it is one of the goals of this method)

**Comment by xabbuh** [comment]
Well, I too would expect there to be no version if the `version_format` option is set to an empty string (the cause for this might be the same as for #14832 and #15235).

**Comment by svassaux** [comment]
Sorry. The details abot does not work are in my link on stackoverflow. The url output with a version number is not handled properly by imagine_filter, indeed. But using a package name with the parameter version set to "~" still ouputs a version number. I can't find a way to not output a number for specific assets.

**Comment by trsteel88** [comment]
@svassaux this isn't a assetic issue. It is a imagine filter problem.

Imagine filter determines the path to the image. Since you are rewriting that path to a relative path with asset(), it's not going to work. Remember, the path you give you imagine_filter doesn't have to be an actual path. You can write loaders to handle something like '1234' to look in the database.

**Comment by svassaux** [comment]
@trsteel88 : I was using asset already and it used to work. So here this is the versioning that is causing the imagine_filter to not work. I understand the issue is in the imagine_filter. Do you have any idea as to how not ouput a version number for certain assets? Or another way to solve the issue ?

**Comment by trsteel88** [comment]
Did you update your imagine bundle? In one of the version updates they changed the paths from relative to absolute.

Sorry, I do not know how to append the asset version to an image.
