### ISSUE TITLE
[2.8] UriSafeTokenGenerator class issue

### ISSUE THREAD

**Issue by petforsberg** [symfony/symfony#16270]
SF error at Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator.php at line 56

    Attempted to call function "random_bytes" from namespace "Symfony\Component\Security\Csrf\TokenGenerator". 

e..g here https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php#l56

(Using PHP 5.4)

https://github.com/symfony/symfony/commit/f02973acd86d7520c180059b253ad23e5e58b6f8

http://php.net/manual/en/function.random-bytes.php from PHP 7.

**Comment by jeremyFreeAgent** [comment]
@petforsberg Make sure you have the `paragonie/random_compat` dependency in your project.

**Comment by Tobion** [comment]
You need to install dependencies: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Csrf/composer.json#L21

**Comment by petforsberg** [comment]
Thanx. Weird that composer didn't do this automatically when installing, though I removed its lock file.
