### ISSUE TITLE
How to manage project in vagrant with the vendor to be outside of synced folder

### ISSUE THREAD

**Issue by ZYWJ** [symfony/symfony#16282]
For speeding up symfony in vagrant + virtualbox,  I had been moved the directory `vendor` outside of the vagrant sync folder.   

When using `git` to manage project. It will occur that the local project is to be updated. But in the vagrant,  the vendor isn't to be updated.  

It is hard to develop.  Do you have any suggestions?

**Comment by Tobion** [comment]
Please ask support questions on Stackoverflow. Thank you.

**Comment by Tobion** [comment]
I'd suggest to update vendors inside vagrant then.
