### ISSUE TITLE
[Security] Easier authentication entry point decoration

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#16299]
Use case: I want to display a (flash) message to user when he needs to login to acces a secured page. By default he's only redirected to login page. That's fine. I just want to add the message.
I was examining what's the easiest way. And it looks to me like the easiest way is to define my own entry point and add a flash message inside the entry point.

Creating my own entry point is very simple. But i'd like to decorate the default one. And i don't know what is the default one because it depends on configuration. So i hardcoded it (in services configuration file) to decorate `security.authentication.form_entry_point.main` because that's the one it currently uses. If i switched from `form_login` to something else or after renaming the firewall key then it's needed to update the service configuration again.

=> I think it would be better to be able to somehow decorate it easier. To somehow pass the original entry point to the new one.

Or is it a bad idea which doesn't worth implementation?

**Comment by javiereguiluz** [comment]
I'm probably missing something, but if you only want to display a flash message in the login form page, why don't you create that message in the controller associated with the login form?

**Comment by HeahDude** [comment]
Hi @maryo The easiest way IMO is to allow anonymous access on the page and add a flash message in the controller when user is anonymous or load sensible data if user is granted

**Comment by maryo** [comment]
@HeahDude I want it for every secured action when the user is redirected to the login page which is done in the entry point in Symfony exactly here: https://github.com/symfony/security-http/blob/master/EntryPoint/FormAuthenticationEntryPoint.php#L50

@javiereguiluz I wanted to display a flash message only in case of anonymous user trying to access a secured page which results into redirection to login form. Every secured page, not just one particular action in one Controller. I think the entry point is exactly what i need. And decorating it works properly.

```php
namespace App;

class AuthenticationEntryPoint implements AuthenticationEntryPointInterface
{
    private $authenticationEntryPoint;

    public function __construct(AuthenticationEntryPointInterface $authenticationEntryPoint)
    {
        $this->authenticationEntryPoint = $authenticationEntryPoint;
    }

    /**
     * {@inheritDoc}
     * Notifies user about missing authentication using a flash message.
     */
    public function start(Request $request, AuthenticationException $authenticationException = null): Response
    {
        $session = $request->getSession();

        if ($session instanceof Session) {
            $session->getFlashBag()->add('fos_user_warning', 'You need to login to access this page.');
        }

        return $this->authenticationEntryPoint->start($request, $authenticationException);
    }
}
```

`security.yml`
```yaml
security:
    firewalls:
        main:
            entry_point: app.security.authentication_entry_point
# ...
```
```yaml
app.security.authentication_entry_point:
    class: App\AuthenticationEntryPoint
    arguments: [@security.authentication.form_entry_point.main]
# ...
```

Everything is actually OK. But it could be even better. The entry point class I posted which adds the desired flash message functionality is actually a decorator. It decorates **any** entry point. The original is `security.authentication.`**`form_entry_point.main`** when u set the decorator as an entry point for the **main** firewall.

The problem is the name of the original entry point service. It's an implementation detail. If I decided to rename the firewall, the name of the decorated entry point service would also change and you have to find it's name in the service container.

I have an idea.
This DI feature is available for implementing decorators in Symfony:
http://symfony.com/doc/current/components/dependency_injection/advanced.html
It adds the `"@bar.inner"` alias.

Ideally, when option like
`entry_point: app.security.authentication_entry_point`
is configured, it could automatically alter the service `app.security.authentication_entry_point` to become a decorator if it is not already a configured decorator. The alias `@app.security.authentication_entry_point.inner` could be used if needed.

**Comment by HeahDude** [comment]
The easiest way IMHO would be using a listener on `Kernel::Response` event.
```php
public function onKernelResponse(FilterResponseEvent $event)
{
    if (false === $event->isMasterRequest()) {
        return;
    }

    $response = $event->getResponse();

    if (false === $response instanceof RedirectResponse) {
        return;
    }

    $request = $event->getRequest();

    if ('/login' === $response->getTargetUrl()) {
        $request->getSession()->getFlashBag()->add(
                'fos_user_warning',
                sprintf('You need to login to access the page %s.', $request->getRequestUri())
        );
    }
}

**Comment by maryo** [comment]
@HeahDude :+1: Very nice trick :)

**Comment by HeahDude** [comment]
;)

**Comment by HeahDude** [comment]
This issue may be closed then.

**Comment by maryo** [comment]
Well, I still think that the "decoration by default" feature when replacing services with default behavior using a configuration file is not a bad idea. But probably a different issue could be created then. Closing.

**Comment by HeahDude** [comment]
:+1: But maybe hard to implement though.

**Comment by maryo** [comment]
I think it's actualy quite easy to implement.
I created another issue
https://github.com/symfony/symfony/issues/17821
