### ISSUE TITLE
ConstraintValidator::formatValue() sourround negative numeric values with " "

### ISSUE THREAD

**Issue by J-Ben87** [symfony/symfony#16305]
### Context

I use the `RangeValidator` with `min=0`.
When a value is validated, the `ConstraintValidator::formatValue()` is used to format the invalid parameters.

```
// Symfony\Component\Validator\Constraints\RangeValidator
$this->context->buildViolation($constraint->minMessage)
    ->setParameter('{{ value }}', $this->formatValue($value, self::PRETTY_DATE))
    ...
```

### Problem

When the validated value is a numeric string, the `formatValue()` method surrounds it with double quotes.

### Suggested improvement

Check if the value is numeric before checking if it's a string in the `formatValue()` method.

### Output message

**Current (custom)**:
```
The value "-1" should be 0 or more.
```

**Expected (custom)**:
```
The value -1 should be 0 or more
```

I'll submit a PR for this soon if you agree with that.

**Comment by J-Ben87** [comment]
I created a PR: https://github.com/symfony/symfony/pull/16330

**Comment by Tobion** [comment]
This is done on purpose to be able to infer the type of the value. Otherwise the `Type` constraint doesn't make sense as you don't know if it was a numeric string or int/float. The only alternative would be to use different formats for different constraints, e.g. skip the quotes for `Range` since the type doesn't really matter. But I don't think it's worth it and will only cause confusion. So I'm :-1: on this.

**Comment by J-Ben87** [comment]
I understand you point, but I'm still not sure the validator should be responsible for decinding the format of the output value. That `{{ value }}` parameter is meant to be used in the translated error message, but built this way, we can't customize it fully.

Anyway, a valid and easy way to change the formatted value is to override the desired `*Validator::formatValue()` method, in my case:

```
<?php

namespace LittleBigData\AppBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraints\RangeValidator as BaseRangeValidator;

/**
 * @author Benoit Jouhaud <bjouhaud@prestaconcept.net>
 */
class RangeValidator extends BaseRangeValidator
{
    /**
     * {@inheritdoc}
     */
    protected function formatValue($value, $format = 0)
    {
        $value = parent::formatValue($value, $format);

        if (is_numeric($value)) {
            return trim($value, '"');
        }

        return $value, $format;
    }
}
```

I will close my PR then, but maybe that discussion should remain somewhere to help people having the same question?
