### ISSUE TITLE
ContainerBuilder using array_map for resolving services

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#16314]
`ContainerBuilder` uses `array_map` to resolve services ([take a look here](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L973-L976)). If an exception is thrown during the process, warning is generated and all debugging is a lot harder. Is there any advantage of current solution? Can we use `foreach` instead?

**Comment by nicolas-grekas** [comment]
See #15512 for a some discussion around this issue. I don't know if we should really do something. For now, we said no need...
