### ISSUE TITLE
How to connect fabbot to private repo on github?

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#16311]

**Comment by stof** [comment]
Closing this as this is not an issue related to symfony.

@javiereguiluz I suggest mentionning this on the fabbot.io homepage though

**Comment by stof** [comment]
@andreybolonin note that most of the checks done by fabbot.io are done by running the PHP-CS-Fixer tool (half of the features mentioned on the homepage have been moved to the fixer itself since then).
and https://styleci.io/ provides a CI service running this tool for any repo.

**Comment by andreybolonin** [comment]
@stof Thanks!
