### ISSUE TITLE
Multiple translations in one file

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16313]
Is it currently possible to have multiple translations in one file?

I want to have 1 CSV file with 3 languages:

```
key;german;english;french
```

Is there any way to do this currently?

**Comment by stof** [comment]
Well, you could write a custom CSV loader loading the right column depending on the locale. you would still have to register the resource for each locale (meaning that the file will still be processed once per locale, not only all locales in the same parsing).

There is no builtin loader able to cover your case though. It requires writing a custom loader.

**Comment by JHGitty** [comment]
Yes, that is my problem: Currently there are 1 file per locale but I like to have multiple locales in one file.

**Comment by stof** [comment]
with your custom loader, you could have a single file, registered multiple times as resource (once per locale) and having the loader load the right column of the file depending on the locale

**Comment by aitboudad** [comment]
@JHGitty or just create a command to split the file to have one locale per file.

**Comment by JHGitty** [comment]
As I understand I can use the ``translation.loader`` tag to add an own loader. But how can I be sure that my loader is used for CSV files? There is already a CSV loader in Symfony itself but I like to load the CSV files with my own loader.

**Comment by aitboudad** [comment]
@JHGitty I recommand to put your csv files in a custom directory (app/translation-csv-files) and register  [SynchCsvFilesCommand](https://gist.github.com/aitboudad/9e9cbc65225045bbe3f0) command which will generate files compatible with the default csv loader.

```
php app/console translation:synch app/translation-csv-files
```
![selection_004](https://cloud.githubusercontent.com/assets/1753742/10688600/ed63a418-7964-11e5-9d2a-6335a2e7106b.jpg)

**Comment by JHGitty** [comment]
Thanks. But it would be nice to understand how I could replace the default CSV loader, just to know it. :+1:

**Comment by xabbuh** [comment]
@JHGitty You could replace the default `translation.loader.csv` with your implementation, for example.

I'm going to close here as there is nothing to be changed in the core.
