### ISSUE TITLE
[ExpressionLanguage] Add linter

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#16323]
In our project there is possibility write own custom rules. And currently no way check if this rules written correctly. Currently we are using workaround for it, but I think that should be linter.

``` php
$error = '';
set_error_handler(function($errno, $errstr) use (&$error) {
    $error = $errstr;
});

$expressionLanguage->compile($extendedPattern, array('title'));

restore_error_handler();

if ($error) {
    $errorElement
        ->with('categoryExtended.extendedPattern')
        ->addViolation($error)
        ->end();
}
```

**Comment by stof** [comment]
I don't understand why you use an error handler here. The compilation triggers exceptions on failures, not PHP errors (unless your own code does not handle errors properly, but this is a bug in your own functions, which should be catched by testing them)

**Comment by Koc** [comment]
for example we have defined function `ololo($a, $b)` and call they in the code `1 + ololo(2)` - as you see - this code is invalid and should raise an error. So linter should validate this case. Currently there is no any exception when we trying to compile this code (warning occurs)

**Comment by stof** [comment]
ah indeed, you are compiling the expression, not only parsing it. So such thing may indeed happen.

**Comment by fabpot** [comment]
Closing as nobody stepped up to implement such a validator.
