### ISSUE TITLE
[Form][2.8,3.0] Type guesser guesses alias instead of FQCN

### ISSUE THREAD

**Issue by hiddewie** [symfony/symfony#16332]
In the file `Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php` of branch `2.8` (and `master`), the quessed form types are the old aliases. They should be updated to quess the FQDN of the form type, as decided and implemented in #15079.

**Comment by Tobion** [comment]
Yeah I also raw that when working on #16302

**Comment by hiddewie** [comment]
If my PR is merged and 2.8 has been merged into master I'll create a new pull request with the same edits using the `::class` constant.
