### ISSUE TITLE
PostResponseEvent not extending KernelEvent

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#16342]
According to the [official docs](http://symfony.com/doc/current/components/http_kernel/introduction.html#creating-an-event-listener) all Kernel Events should extend `KernelEvent` but `PostResponseEvent` doesn't.   
I also have a valid use case for it, which follows:  
I'm storing the last accessed page by the user in the session, so I've registered a listener on `kernel.terminate` for that, but the request's info should only be stored, if it's a master request, however without the`PostResponseEvent` extending `KernelEvent` I have no way of knowing that.

**Comment by jakzal** [comment]
`kernel.terminate` is only dispatched on master requests.

**Comment by Tobion** [comment]
Closing for the reason provided by @jakzal. If the documentation needs clarification about this, please open an issue on symfony-docs.

**Comment by jakzal** [comment]
I still think we should fix this, at least for consistency.
