### ISSUE TITLE
Debug toolbar AJAX panel gets hidden permanently (2.8)

### ISSUE THREAD

**Issue by fracsi** [symfony/symfony#16349]
Debug toolbar AJAX icon is always hidden if there was no ajax call preceding loading the wdt.
In [`toolbar_js.html.twig`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig) [`Sfjs.renderAjaxRequests();`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig#L33) is called. This call hides the toolbar panel, because the `requestStack` variable is empty in [base_js.html.twig](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L99), so it goes straight to [`ajaxToolbarPanel.style.display = 'none';`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L175). The toolbar is hidden permanently. There is no code for showing it again.

**Comment by javiereguiluz** [comment]
This new behavior is the same we apply to other panels (Ajax, Doctrine, SwiftMailer, etc.). If there is no information, the panel is not shown.

**Comment by fracsi** [comment]
@javiereguiluz 
The icon is never shown if there was an ajax call after the wdt is loaded, and the icon is hidden by default.

**Comment by javiereguiluz** [comment]
@fracsi you are right. I can confirm this issue. I've created a pull request to fix it: https://github.com/symfony/symfony/pull/16350  Thanks.

**Comment by fracsi** [comment]
@javiereguiluz Thanks, that was fast.

**Comment by javiereguiluz** [comment]
*(@fracsi we usually keep issues open until the PR that fixes them is merged. Then, the tool we use to merge things closes issues automatically)*

**Comment by olix21** [comment]
No Ajax panel for me yet

**Comment by xabbuh** [comment]
@olix21 Can you please open a new ticket and provide some more information about your Symfony version?
