### ISSUE TITLE
composer install sets incorrect path to SymfonyRequirements.php in web/config.php

### ISSUE THREAD

**Issue by arrgson** [symfony/symfony#16348]
I have a Symfony installation with the `app` directory renamed to `server`. This is configured in `composer.json` via the `symfony-app-dir` setting. When I run `composer install` the path on line 15 in `web/config.php` (`require_once dirname ...`) is generated incorrectly. It appears to not respect the setting in `composer.json` and use `app` instead.

**Comment by Tobion** [comment]
Please open the issue on https://github.com/sensiolabs/SensioDistributionBundle where this is handled.
