### ISSUE TITLE
Catching fatal errors in console

### ISSUE THREAD

**Issue by gadelkareem** [symfony/symfony#16366]
Using Symfony 2.6 while $debug is true I was able to catch fatal errors using faulty register_shutdown_function(null) in console. Disabling debug mode I get an invalid callback error.

**Comment by iltar** [comment]
@gadelkareem have you tried upgrading to 2.7? I also recommend you to use [one of the support channels available](http://symfony.com/support) if you have questions about this.

To be honest, I don't think this is a bug, it's how the debugging/error handling is done in symfony.

**Comment by gadelkareem** [comment]
@iltar can you explain how in debug mode ```register_shutdown_function(null);``` does not show a warning?

**Comment by jakzal** [comment]
`register_shutdown_function(null)` will trigger `E_WARNING`, as `null` is not a valid callback (see http://php.net/register_shutdown_function). In the dev environment warnings are converted to exceptions.

Unless I misunderstood your report @gadelkareem , there's nothing to do here. If you disagree, please provide more details on what you're trying to do, what happens and what you expect to happen instead.

**Comment by gadelkareem** [comment]
@jakzal Exactly but the problem is that Symfony does not trigger this warning in dev environment neither does it throw an exception.

**Comment by jakzal** [comment]
@gadelkareem I have just tested it on 2.7 and it does trigger an exception. If you found a case where it doesn't work, please provide code that would help us reproduce it.
