### ISSUE TITLE
[VarDumper] Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by bonswouar** [symfony/symfony#16364]
With PHP 5.6.9, Symfony 2.6.11

I've got the following error :

> **PHP Fatal error:  Cannot access self:: when no class scope is active in /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php on line 25**

When I try to dump `$event` in a form `PRE_SET_DATA` event.

```php
$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
  die(dump($event));
});
```

But not on `POST_SET_DATA` events.

Any clue ?

Here is the full stack trace :
> PHP Stack trace:
PHP   1. {main}() /home/www/repos/web/app_dev.php:0
PHP   2. Symfony\Component\HttpKernel\Kernel->handle() /home/www/repos/web/app_dev.php:35
PHP   3. Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle() /home/www/repos/apps/myapp/bootstrap.php.cache:2406
PHP   4. Symfony\Component\HttpKernel\HttpKernel->handle() /home/www/repos/apps/myapp/bootstrap.php.cache:3165
PHP   5. Symfony\Component\HttpKernel\HttpKernel->handleRaw() /home/www/repos/apps/myapp/bootstrap.php.cache:3016
PHP   6. call_user_func_array:{/home/www/repos/apps/myapp/bootstrap.php.cache:3054}() /home/www/repos/apps/myapp/bootstrap.php.cache:3054
PHP   7. MyVendor\MyBundle\Controller\DevisController->devisEtape1Action() /home/www/repos/apps/myapp/bootstrap.php.cache:3054
PHP   8. Symfony\Bundle\FrameworkBundle\Controller\Controller->createForm() /home/www/repos/src/MyVendor/MyBundle/Controller/DevisController.php:102
PHP   9. Symfony\Component\Form\FormFactory->create() /home/www/repos/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:250
PHP  10. Symfony\Component\Form\FormBuilder->getForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:39
PHP  11. Symfony\Component\Form\FormBuilder->getForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:221
PHP  12. Symfony\Component\Form\FormBuilder->resolveChildren() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:215
PHP  13. Symfony\Component\Form\FormBuilder->create() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:267
PHP  14. Symfony\Component\Form\FormFactory->createNamedBuilder() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:106
PHP  15. Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy->buildForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:91
PHP  16. Symfony\Component\Form\ResolvedFormType->buildForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php:103
PHP  17. Symfony\Component\Form\Extension\Core\Type\CollectionType->buildForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:135
PHP  18. Symfony\Component\Form\FormBuilder->getForm() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php:33
PHP  19. Symfony\Component\Form\Form->initialize() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:226
PHP  20. Symfony\Component\Form\Form->setData() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:487
PHP  21. Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:341
PHP  22. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php:43
PHP  23. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/repos/apps/myapp/cache/dev/classes.php:1724
PHP  24. call_user_func:{/home/www/repos/apps/myapp/cache/dev/classes.php:1791}() /home/www/repos/apps/myapp/cache/dev/classes.php:1791
PHP  25. MyVendor\MyBundle\Form\Type\Webservice\AnimalType->MyVendor\MyBundle\Form\Type\Webservice\{closure}() /home/www/repos/apps/myapp/cache/dev/classes.php:1791
PHP  26. dump() /home/www/repos/src/MyVendor/MyBundle/Form/Type/Webservice/AnimalType.php:149
PHP  27. Symfony\Component\VarDumper\VarDumper::dump() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php:21
PHP  28. call_user_func:{/home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/VarDumper.php:38}() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/VarDumper.php:38
PHP  29. Symfony\Component\HttpKernel\EventListener\DumpListener->Symfony\Component\HttpKernel\EventListener\{closure}() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/VarDumper.php:38
PHP  30. Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DumpListener.php:46
PHP  31. Symfony\Component\VarDumper\Cloner\VarCloner->doClone() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:153
PHP  32. Symfony\Component\VarDumper\Cloner\AbstractCloner->castObject() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php:150
PHP  33. Symfony\Component\VarDumper\Cloner\AbstractCloner->callCaster() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:221
PHP  34. call_user_func:{/home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:266}() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:266
PHP  35. Symfony\Component\VarDumper\Caster\ReflectionCaster::castReflector() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:266
PHP  36. ReflectionClass->__toString() /home/www/repos/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php:25

**Comment by nicolas-grekas** [comment]
Thanks for the report, but 2.6 in not maintained anymore, you should upgrade to 2.7, which is also an LTS version. Can you reproduce the issue there?
