### ISSUE TITLE
Unable to load class "Symfony\Bundle\AsseticBundle\DefaultValueSupplier"

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#16367]
```composer update```, Symfony 2.8.x-dev

1) I removed ```new Symfony\Bundle\AsseticBundle\AsseticBundle()``` because of error:
```PHP Fatal error:  Class 'Symfony\Bundle\AsseticBundle\AsseticBundle' not found in .../app/AppKernel.php on line ...```

2) The next error shows up:
```Unable to load class "Symfony\Bundle\AsseticBundle\DefaultValueSupplier"```

What should I do now?

**Comment by Tobion** [comment]
Please ask support questions on stackoverflow. It looks like you might not have assetic bundle as a dependency in your composer.json.

**Comment by kniziol** [comment]
Yes, I haven't, because, as I wrote, I removed ```new Symfony\Bundle\AsseticBundle\AsseticBundle()``` because of error:
```PHP Fatal error:  Class 'Symfony\Bundle\AsseticBundle\AsseticBundle' not found in .../app/AppKernel.php on line ...```

```AsseticBundle``` was removed:
https://github.com/symfony/symfony-standard/commit/2bee277feb6c6a02e4828f772cd0945d841f6c51

What should I do now?

**Comment by xabbuh** [comment]
@kniziol It just means that AsseticBundle isn't included by default in the Symfony Standard Edition but you are completely free to add it to your project.

**Comment by kniziol** [comment]
@xabbuh Thanks, it's one of possible solutions. Is there any doc describing why ```AsseticBundle``` was removed?

**Comment by xabbuh** [comment]
@kniziol You can read the discussion in the related pull request: symfony/symfony-standard#860
