### ISSUE TITLE
To choose 2.8 or 3.0

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#16375]
Hi to all,

Actually, my website running with version 2.3,
I would like update my website but i dont know what is the best solution.
Do i have to choose 2.8 or 3.0 and what will be the  consequence of this choice.

Thank you

**Comment by TomasVotruba** [comment]
Hey, I'd recommend update do Symfony 2.8 (about to be released in November). It has all new features and informs about deprecations.
So it's compatible with 2.3. 

But first, I'd update to 2.7.

Symfony 3.0 will have new features, but no backwards compatibility.

**Comment by TomasVotruba** [comment]
Also, could you post your questions to http://stackoverflow.com/ under #symfony tag next time?

This issue tracker is rather for reporting bugs.

**Comment by strauss69400** [comment]
Alright.i will post on stackoverflow.
So the solution would be to update 2.7 or 2.8.

Thanks for your response.

**Comment by WouterJ** [comment]
Please do not blindly redirectly all user support questions to StackOverflow. StackOverflow is a Q/A site, it can only handle questions that have only one clear and correct answer.

Questions like this are primarily opinion based, it's all about recommendations. These questions are not on-topic for StackOverflow.

Thanks!

**Comment by TomasVotruba** [comment]
@WouterJ I'd say it's all about context and best practices. Like all IT related questions.

Putting that apart, what do you suggest?

**Comment by Tobion** [comment]
@WouterJ for technical questions there are always several solutions each having pros and cons. The best answer on SO would clearly show that. And this is just as true for this questions. So of course its suited for SO. Where else would you propose to ask this question then?

**Comment by WouterJ** [comment]
@Tobion questions about best practices are off-topic at StackOverflow by definition. Every question like "What do you recommend?" is not suited for StackOverflow.

Within the StackExchange communities, [programmers.SE](http://programmers.stackexchange.com/) is probably better suited (although we shouldn't just blindly redirect all these kind of questions to programmers.SE either).

I think we may be missing a good place to ask such questions at the moment in the support channels. People can of course always go to IRC to ask their question. But for people that don't want that, there is no good alternative yet other than asking on a random PHP forum in their country.
