### ISSUE TITLE
[Http Foundation] BinaryFileResponse should try to match "If-Range" header with file's MTime

### ISSUE THREAD

**Issue by chlabelek** [symfony/symfony#16376]
In BinaryFilesResponse.php's "prepare" method, the partial response is created only if no "If-Range" request header found, or if it matches the response's ETag.
Default behavior of this response is to not send ETag header, but Last-Modified, so we have no browser cache.
As per the spec, "If-Range" request header value may also be compared with the response's Last-Modified time.
And that would be usefull :-)

**Comment by javiereguiluz** [comment]
I'm closing this as a duplicate of #16540 (which already contains an associated pull request: #17602)
