### ISSUE TITLE
Check the password in DaoAuthenticationProvider is not working.

### ISSUE THREAD

**Issue by bulychev** [symfony/symfony#16383]
Checking https://github.com/symfony/symfony/blob/3909460c04e6b13858f2fa3b4e41ec68fdebf0a2/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php#L58 is not working because $currentUser and $user are same.

**Comment by iltar** [comment]
@bulychev please use one of [the appropriate community channels](http://symfony.com/support) to ask questions. If this is a bug report, please provide more information; What goes wrong? What should it do? What have you tried? etc.

**Comment by javiereguiluz** [comment]
I'm closing this because it looks like a support question. In that case, please use [the support channels](http://symfony.com/support) mentioned by @iltar.

If this is indeed a bug, please reopen this issue and provide more details about it. Thanks!
