### ISSUE TITLE
[DI Debug] Private Aliases not shown with debug:container

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#16388]
When running debug:container --show-private, it doesn't show private aliases. A scenario where this happens is when a private alias is used for a private service to optimize them away and prevent `Container->get()` usage.

My company has code that automates generating services for repositories, this follows a specific setup: `order.repository.clients_order_line` where `clients` is the entity manager (connection) name. This would result in a private alias: `order.repository.order_line` pointing at `order.repository.clients_order_line`. This code works perfect with one downside, private alias cannot be found back.

The naming follows a convention so we can always find it back one way or another, but we cannot find it using the `debug:container` command nor can an IDE such as PHPStorm find it as it's optimized away. I've been digging in the code and in `TextDescriptor::describeContainerServices()` this is not available.

My guess is that private aliases are optimized away if they are not used before hitting this code and is therefore a bug. If I wanted to find all un-used private services/alias, I would be unable to do so with the current setup.

**Comment by iltar** [comment]
Update, `RemovePrivateAliasesPass` is the one removing the aliases, which is quite frankly, really annoying in development. It doesn't remove public aliases, just the private ones.

Is there a way to keep those aliases so I can find back which ones are available?

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by javiereguiluz** [comment]
My vote is for closing this issue as "won't fix". I can't see a simple way to implement this feature (we can't for example disable the `removePrivateAliasesPass` in `dev` because we want to minimize the differences in the container built for dev and prod).

**Comment by nicolas-grekas** [comment]
Or, this command could recreate a container from loaders, and get private services from there, without running any compiler pass on this temporary container (that should be trashed one the command ends)

**Comment by jeremyFreeAgent** [comment]
@nicolas-grekas That will also help to have the real name of the private services. I like that.

**Comment by chalasr** [comment]
See #22385

**Comment by stof** [comment]
@nicolas-grekas not running compiler passes is not an option. Compiler passes can also *create* services (and alter dependencies between them).
We would need to disable only the removing pass.

**Comment by chalasr** [comment]
@stof that's what #22385 does.
