### ISSUE TITLE
ContextListener uses UserInterface::getUsername() method, which is not defined

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#16394]
https://github.com/symfony/symfony/blob/3909460c04e6b13858f2fa3b4e41ec68fdebf0a2/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L159

**Comment by iltar** [comment]
@pamil can you provide a bit more information about the issue?

**Comment by pamil** [comment]
@iltar I mean that `UserInterface` does not include `getUsername` method which result in calling unexisting method on `$user`.

**Comment by iltar** [comment]
It does have that method: https://github.com/symfony/symfony/blob/3909460c04e6b13858f2fa3b4e41ec68fdebf0a2/src/Symfony/Component/Security/Core/User/UserInterface.php#L78

**Comment by pamil** [comment]
Nevermind, I was renaming earlier `username` field to `email` on my user entity and PhpStorm did it so good, that it also renamed method in that interface :) Thanks for your help :)

**Comment by iltar** [comment]
@pamil for those question you can also come to `#symfony` on freenode, there's usually a bunch of people who can find that issue for you in a matter of minutes.

Github is not really meant for these kind of questions.

**Comment by pamil** [comment]
I know, I really thought I had find a bug and wasn't expecting that my local vendor code have been changed somehow.
