### ISSUE TITLE
[Stopwatch] Different behaviour if grouped with other tests

### ISSUE THREAD

**Issue by EmanueleMinotto** [symfony/symfony#16405]
I don't know if this is related to https://github.com/symfony/symfony/issues/14444 or not, but everytime I try locally the tests (branch 2.8) related to the Stopwatch I have this behaviour:

![2015-10-30 - 23:57:32](https://cloud.githubusercontent.com/assets/417201/10862779/3b2b1016-7fb7-11e5-911f-dbd538f5d869.png)

**Comment by TomasVotruba** [comment]
Oh, came across that yesterday too (3.0). Took me while to figure out it requires standalone run.

I'd be for make these test independent on outer timings.

Shall prepare PR?

**Comment by TomasVotruba** [comment]
It looks it's caused by one Symfony\HttpKernel test: https://github.com/symfony/symfony/blob/64917c726d2540bfe1d9f233cfaf04a4ebec5504/src/Symfony/Component/HttpKernel/Tests/Debug/TraceableEventDispatcherTest.php#L23

**Comment by jakzal** [comment]
@TomasVotruba great job! Are you working on a PR?

**Comment by TomasVotruba** [comment]
@jakzal I would love to, but I'm not exactly sure, why it's nulled. Got any idea?

I'll try checking tonite.

**Comment by jakzal** [comment]
@TomasVotruba I didn't look into this yet as I wouldn't like to duplicate your efforts :)

**Comment by TomasVotruba** [comment]
It looks like it's passing with:

`phpupnit` (my local phar file or vendor native PHPUnit binary)

but not with the custom script:

`php phpunit`.

**Comment by TomasVotruba** [comment]
It looks like it's not passing with the custom script:

`php phpunit`.

but my local phar file or vendor native PHPUnit binary:

`phpupnit` 


`phpunit.xml` setup:

```
<testsuites>
        <testsuite name="Symfony Test Suite">
            <directory>./src/Symfony/Component/HttpKernel/Tests/Debug/</directory>
            <directory>./src/Symfony/Component/Stopwatch/*</directory>
        </testsuite>
    </testsuites>
```

![screenshot from 2015-11-06 15 36 20](https://cloud.githubusercontent.com/assets/924196/10999490/8a45dd86-849c-11e5-9213-2b07d1e5ec70.png)
![Uploading Screenshot from 2015-11-06 15:36:20.png…]()

**Comment by TomasVotruba** [comment]
I've tried to delete `/.phpunit` directory and rerun the Symfony `phpunit` script and all passes well now.

**Comment by EmanueleMinotto** [comment]
@TomasVotruba sorry for the delay.

Changing the testsuite (in the phpunit.xml.dist) to:
```xml
    <testsuites>
        <testsuite name="Symfony Test Suite">
            <directory>./src/Symfony/Component/HttpKernel/Tests/Debug/</directory>
            <directory>./src/Symfony/Component/Stopwatch/*</directory>
        </testsuite>
    </testsuites>
```

I have all green tests on every tests execution (also after just the git clone and composer install).

![schermata 2015-11-10 alle 09 45 07](https://cloud.githubusercontent.com/assets/417201/11057996/ee0284f0-878f-11e5-9c7a-a7fa68f43ce4.png)

**Comment by nicolas-grekas** [comment]
@EmanueleMinotto did you delete the .phpunit folder the test using ./phpunit again?

**Comment by EmanueleMinotto** [comment]
@nicolas-grekas yes, also removing the `.phpunit` directory it works (always with the last testsuite I wrote above).

**Comment by nicolas-grekas** [comment]
So, is there still an issue? You had a legacy .phpunit installation and the issue has gone now isn't it?

**Comment by TomasVotruba** [comment]
For me it's gone.

**Comment by EmanueleMinotto** [comment]
yes, it's solved for me too, thank you

**Comment by nicolas-grekas** [comment]
cool
