### ISSUE TITLE
[validator] Collection constraint with empty string (invalid data)

### ISSUE THREAD

**Issue by Petah** [symfony/symfony#16412]
When sending invalid data, such as an empty string, and using a Collection constraint this throws an exception rather than adding a violation.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/CollectionValidator.php#L37

Is this expected? If so how do I validate a value that is expected to be a collection, but has been supplied invalid data?

**Comment by iltar** [comment]
It means people have been messing around with your data structure in case of forms. But in case of generic validation, I doubt this is intended.

**Comment by Petah** [comment]
I am using the validator standalone, not with the forms.

**Comment by xabbuh** [comment]
I think in this case you should combine this with the [Type constraint](http://symfony.com/doc/current/reference/constraints/Type.html). Or will the `Collection` constraint be evaluated anyway too?

**Comment by xabbuh** [comment]
Is there anything we need to do here?

**Comment by HeahDude** [comment]
ping @Petah :)

**Comment by xabbuh** [comment]
I am closing here for now.

@Petah Feel free to comment if you do not agree and we can reopen.

**Comment by Petah** [comment]
Well, hasn't really been an issue since, but I still think throwing an exception over adding a violation is weird for a validation library.

**Comment by adamcameron** [comment]
This seems to be the same as [13560](https://github.com/symfony/symfony/issues/13560) which is still open, but thought I'd comment in agreement with @Petah: if one passes the wrong type when validating a collection, that is a validation constraint violation, not an exception situation.

I will follow-up further on 13560.
