### ISSUE TITLE
[Security][Guard] GuardAuthenticationListener uses undefined logger instance

### ISSUE THREAD

**Issue by aeoris** [symfony/symfony#16415]
Every other use of `$this->logger` is preceded by a `null` check:

https://github.com/symfony/security/blob/master/Guard/Firewall/GuardAuthenticationListener.php#L80

**Comment by xabbuh** [comment]
@aeoris Good catch, do you want to create a pull request?

**Comment by aeoris** [comment]
@xabbuh yes, on it. :-)
