### ISSUE TITLE
[DomCrawler] Selecting attribute 2.8 BC break 

### ISSUE THREAD

**Issue by boekkooi** [symfony/symfony#16417]
As I was updating one of my packages I noticed that the test where all failing with 2.8. 
After some research I found out that the DomCrawler was not working as expected when selecting a attribute using `//div/@id`.

I created the following test for `CrawlerTest.php` that shows the break:
```PHP
    public function testFilterXPathAttribute()
    {
        $crawler = $this->createTestCrawler();

        $formIds = $crawler->filterXPath('//form/@action');
        $this->assertCount(1, $formIds, '->filterXPath() finds node attributes');
        $this->assertEquals('foo', $formIds->html(), '->filterXPath() returns the html of the found attribute');

        $divIds = $crawler->filterXPath('//form/@id');
        $this->assertCount(1, $divIds, '->filterXPath() finds node attributes');
        $this->assertEquals('FooFormId', $divIds->html(), '->filterXPath() returns the html of the first attribute');
    }
```

This BC break was introduced by #16058. (commit 9f362a12f616984676182f69aab18c662b47445d)

**Comment by stof** [comment]
this was not really a supported use case previously though, as more than half of the methods were triggering fatal errors in this case

**Comment by boekkooi** [comment]
I'm for the change made by https://github.com/symfony/symfony/pull/16058 but it is breaking code that was work from at least version 2.3 up to and including 2.7. 

Also when looking at 2.3 Crawler docblock this was saying "Crawler eases navigation of a list of \DOMNode objects." so I would say that fetching a attribute using `filterXPath` is a valid use case.
Maybe it is not a valid use case at the moment (since 2.5 is my guess) but wouldn't that mean this change should have been made in 3.0 with deprecation messages in 2.8?

**Comment by boekkooi** [comment]
Closing because 2.8 was release with this so I guess no one cares about some BC breaks

**Comment by jakzal** [comment]
@boekkooi the new behaviour was reverted where it makes sense in #17035
