### ISSUE TITLE
[DomCrawler] Cloned Crawler objects not usable because of overwritten getHash method

### ISSUE THREAD

**Issue by wasinger** [symfony/symfony#16421]
Since 2.8, DomCrawler overrides the SplStorage method "getHash($object)" for the purpose of displaying a deprecation message.
 
When a Crawler object is cloned this triggers [PHP Bug #67582 Cloned SplObjectStorage with overwritten getHash fails offsetExists()](https://bugs.php.net/bug.php?id=67582) and makes the cloned Crawler instance not working correctly (e.g. it's not possible to remove elements from them because methods detach() and removeAll() don't work).

Removing elements from cloned Crawler instances was not a problem up to Symfony 2.7. It's a regression that breaks some of my projects. 

The problem was introduced in [commit 997c650](https://github.com/symfony/symfony/commit/997c650c1c43139847b4e82871925ed31db514ef)

**Comment by jakzal** [comment]
@wasinger can you give me an example how to reproduce this behaviour?

**Comment by wasinger** [comment]
Here is how to reproduce it:

```php
use Symfony\Component\DomCrawler\Crawler;

$c = new Crawler('<html><head></head><body>Some HTML code</body></html>');
echo "Crawler has " . count($c) . " Elements\n"; // 1
$c1 = clone $c;
echo "Cloned Crawler has " . count($c1) . " Elements\n"; // 1

// Remove first node from Crawler
$c->detach($c->getNode(0));
echo "Crawler has " . count($c) . " Elements\n"; // 0

// Remove first node from cloned Crawler
$c1->detach($c1->getNode(0));
echo "Cloned Crawler has " . count($c1) . " Elements\n"; // Should be: 0, sf 2.7: 0, sf 2.8: 1
```

The last line prints "1" in Symfony 2.8 while it should be 0.

**Comment by jakzal** [comment]
Options I see here:
* Acknowledge this is a PHP bug and do nothing.

* Remove the overridden `getHash()` method. It means we wouldn't trigger a deprecation if someone called this method directly. To be honest I think it's quite unlikely that anyone would rely on `getHash()` without relying on other methods from the `\SplObjectStorage`.

* Don't call parent methods of `\SplObjectStorage`'s, but replicate their behaviour with an array of nodes. This might get messy and introduce new bugs.

**Comment by stof** [comment]
I suggest going for the second option

**Comment by jakzal** [comment]
Ok. I'll send a PR soon.
