### ISSUE TITLE
Using Windows to report a default value that is a filename ends up with double backslash.

### ISSUE THREAD

**Issue by rquadling** [symfony/symfony#16420]
If you have ...

```
->addOption('file', 'f', InputOption::VALUE_REQUIRED, 'The file', 'C:\folder\file.ext');
```

when you run with ```--help```, you get ...

```
  -f, --file=FILE The file. [default: "C:\\folder\\file.ext"]
```
  
The double backslash is incorrect.

NOTE: The default value is coming from a .env file and the value is specific to the user using the code and they are on OSx, Unix or Windows. But, if a user types this at the command line, it will be incorrect with the double backslash.

According to https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Descriptor/TextDescriptor.php#L242, outputting the JSON value rather than the literal value into the help would seem to be incorrect as it may not be appropriate in all circumstances (say the literal is NOT a filename but something else).

As ``TextDescriptor::formatDefaultValue()`` in its current form (i.e. using ``json_encode()`` rather than ``var_export()``) was introduced to fix bug https://github.com/symfony/symfony/issues/4193, I think the consideration of showing escaped backslashes was not considered.

Now whilst escaping backslashes is normally correct (and certainly is for JSON), it really isn't appropriate for text that represents a default value that a user will type at the command line.

**Comment by Tobion** [comment]
I think we could just replace `\\` with `\` in the resulting json. It's not valid json then anymore, but that doesn't matter. The main problem then is that there is no way to distinguish `'C:\new'` from `'C:'."\n".'ew'` (with newline). So all those escape sequences in JSON like newline, nullbyte etc would look the same as the plain value. But for humans I guess it should be obvious what is meant in context and those escape sequences are rather uncommon.

**Comment by rquadling** [comment]
Thank you.
