### ISSUE TITLE
Caching when doctrine:generate entities? 

### ISSUE THREAD

**Issue by ivaaaan** [symfony/symfony#16425]
I'm have a simple entity:
```php
<?php
/**
 * @Table(name="tickets")
 * @Entity(repositoryClass="AppBundle\Entity\TicketRepository")
 */
class Ticket 
{
   /**
     * @var \DateTime
     * @Column(type="datetime", name="created_at")
     * @Timestampable(on="create")
     */
    protected $createdAt;

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt = null)
    {
        $this->createdAt = $createdAt;
    }
}
```

Next I'm executing `app/console doctrine:generate:entities`. And when I'm tried to create new item like:
```php
$ticket = new Ticket(); 
//..
$em->flush();
```

I'm got an error: 
` Integrity constraint violation: 1048 Column 'created_at' cannot be null`

It's strange. 

For fix it i'm just clear all doctrine cache: 

`app/console doctrine:cache:clear-result`
`app/console doctrine:cache:clear-query`

**Comment by dupuchba** [comment]
by default entity are not null.
Try to add this annotation to your code : 

```
/**
     * @var \DateTime
     * @ORM\Column(type="datetime", name="created_at", nullable=true)
     * @Timestampable(on="create")
     */
    protected $createdAt;
```

Don't forget to import ORM annotations with 
```
use Doctrine\ORM\Mapping as ORM;
```

and to update your schema :-)

```
php app/console doctrine:schema:update --force
```

Feel free to close this issue if it's OK for you :-)

**Comment by ivaaaan** [comment]
Of Course if i'm will  add `nullable=true` it's will work. But i'm don't needed `null` in my `created_at` field

**Comment by jakzal** [comment]
Please use other channels (like IRC or StackOverflow) for support questions.

**Comment by ivaaaan** [comment]
But it's bug, not question. If i'm not execute `app/console doctrine:generate:entities` - all ok, but when I do it - i got error ` Integrity constraint violation: 1048 Column 'created_at' cannot be null`

**Comment by jakzal** [comment]
@ivaaaan fair enough. It's not a Symfony bug though. The command is provided by [DoctrineBundle](https://github.com/doctrine/DoctrineBundle). Please report it there.
