### ISSUE TITLE
Improve ConstraintValidator#buildViolation() documentation

### ISSUE THREAD

**Issue by m14t** [symfony/symfony#16427]
In [`UPGRADE-3.0.md`](https://github.com/symfony/symfony/blame/master/UPGRADE-3.0.md#L1187), it is advised to use `buildViolation()` instead of `addViolationAt()`, however as a part of Pull-Request #12016, this method was also marked as depreciated.

What is the preferred way to handle this situation?

**Comment by m14t** [comment]
For my current situation, where I have a class that extends `Symfony\Component\Validator\ConstraintValidator` all that was needed was to call `$this->context->buildViolation` instead of `$this->buildViolation`, but it is I'm not sure if the upgrade documents when `$this->context` is going to be an instance of `ExecutionContextInterface2Dot5` or not.

Also, it seems that [FileValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/FileValidator.php) extends [ConstraintValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/ConstraintValidator.php), but in several locations it calls `$this->buildViolation`, which does not seem to exist in Symfony 3.0...

**Comment by Flo-Raf** [comment]
This issue should be closed, because the documentation has been updated.
