### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by hjanuschka** [symfony/symfony#16422]
hello

 i am currently getting following deprecation notice - where i have no clue how to fix it, 
seems to be somewhere in `vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/FormExtension.php`  - maybe fixed in (https://github.com/symfony/symfony/pull/16331) ?

any help on how to get rid of the deprecation notices?

my composer.json packages:

            "php": ">=5.3.9",
            "symfony/symfony": "2.7.*",
            "doctrine/orm": "^2.4.8",
            "doctrine/doctrine-bundle": "~1.4",
            "symfony/assetic-bundle": "~2.3",
            "symfony/swiftmailer-bundle": "~2.3",
            "symfony/monolog-bundle": "~2.4",
            "sensio/distribution-bundle": "~4.0",
            "sensio/framework-extra-bundle": "^3.0.2",
            "incenteev/composer-parameter-handler": "~2.0",
            "ircmaxell/password-compat": "^1.0",
            "doctrine/doctrine-migrations-bundle": "^1.0",

 

    php.INFO: Defining the initRuntime() method in an extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended). {
    	"type":16384,"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":3373,"level":28928,"stack":[{
    	"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":3373,"function":"trigger_error"},{
    	"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":3219,"function":"initRuntime","class":"Twig_Environment","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php","line":126,"function":"loadTemplate","class":"Twig_Environment","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php","line":50,"function":"load","class":"Symfony\\Bridge\\Twig\\TwigEngine","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php","line":72,"function":"render","class":"Symfony\\Bridge\\Twig\\TwigEngine","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php","line":97,"function":"render","class":"Symfony\\Bundle\\TwigBundle\\TwigEngine","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":7585,"function":"renderResponse","class":"Symfony\\Bundle\\TwigBundle\\TwigEngine","type":"->"},{
    	"function":"onKernelView","class":"Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\TemplateListener","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php","line":61,"function":"call_user_func"},{
    	"function":"__invoke","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":1834,"function":"call_user_func"},{
    	"file":"/Users/h.januschka/backend/FXF/app/cache/dev/classes.php","line":1763,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php","line":124,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/bootstrap.php.cache","line":3112,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/bootstrap.php.cache","line":3071,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/bootstrap.php.cache","line":3222,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/app/bootstrap.php.cache","line":2444,"function":"handle","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/web/app_dev.php","line":29,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{
    	"file":"/Users/h.januschka/backend/FXF/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php","line":36,"args":["/Users/h.januschka/backend/FXF/web/app_dev.php"],"function":"require"}]} []
    
    
    {

regards

**Comment by stof** [comment]
@hjanuschka the update to account for the new Twig deprecations is only available in the dev versions of Symfony, not in stable releases yet (it will be part of the next stable releases.

so you have 3 solutions:

- use the dev version of Symfony instead of the stable one
- use Twig 1.22 instead of 1.23 (you will need to use 1.23 again later as the next Symfony releases will require 1.23+)
- ignore these deprecation warning for now, until the next Symfony release

**Comment by hjanuschka** [comment]
thx for clarification - i ll wait for the next release and till then ignore the warnings.
