### ISSUE TITLE
Lost parameter after upgrade

### ISSUE THREAD

**Issue by gaborwolters** [symfony/symfony#16435]
If not empty line at end of parameters.yml, then the last config line lost after upgrade.

Thank you!

**Comment by stof** [comment]
I don't understand what you mean. Can you provide more details ?

**Comment by gaborwolters** [comment]
An incorrect example:
"parameters:
    param1: value1
    param2: value2"

A correct example:
"parameters:
    param1: value1
    param2: value2
"

**Comment by jakzal** [comment]
@gaborwolters could you provide a code example that would reproduce your problem, including an expected and an actual output? It's hard to say what you mean with brief information you've provided.

I've got parameters.yml in my Symfony 2.7 based project, with no new line at the end of the file, and everything works as expected.

I also tried parsing the yams and it's loaded just fine:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

$p =  \Symfony\Component\Yaml\Yaml\Yaml::parse(file_get_contents(__DIR__.'/app/config/parameters.yml'));
var_dump($p);
```

**Comment by gaborwolters** [comment]
@jakzal  Thank you for your test code! I can see the last config parameter in parsed string.

The previous version is Symfony-2.3.33. If I parameters.yml copy to parameters.yml.dist, then the last line is not lost after upgrade.
