### ISSUE TITLE
Bug in Serializer component: Catchable Fatal Error: Object of class Symfony\Component\Serializer\Mapping\AttributeMetadata could not be converted to string

### ISSUE THREAD

**Issue by CornyPhoenix** [symfony/symfony#16445]
When you access the \Symfony\Component\Serializer\Normalizer\AbstractNormalizer::getAllowedAttributes method with `$attributesAsString = false`, you run into the following issue:

> Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Object of class Symfony\Component\Serializer\Mapping\AttributeMetadata could not be converted to string' in [.../Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php:207](https://github.com/symfony/serializer/blob/master/Normalizer/AbstractNormalizer.php#L207)

This is due to the fact that **array_unique** can only be used with arrays of scalars. As it includes instances of `AttributeMetadataInterface`, we get the exception.

Why there is no test case throwing this error is due to fact that this method never gets called with `$attributesAsString = false`. So I would propose to set the default value parameter for the parameter `$attributesAsString` to `true` or even remove the possibility to return `AttributeMetadataInterface[]`. (Because this error occurs, we know that nobody could have ever used this feature.)

I could fix this by myself by replacing the line of code with:

```php
        if ($attributesAsString) {
            $allowedAttributes = array_unique($allowedAttributes);
        }
        return $allowedAttributes;
```

Kind regards,
Konstantin

**Comment by jakzal** [comment]
@CornyPhoenix would you like to work on a pull request?

**Comment by CornyPhoenix** [comment]
Hey @jakzal, I proposed a PR! I primarily decided to take the most backward compatible solution by just checking with an `if` if array_unique can be applied. Unfortunately, I was not sure how to test this code, as none of the default normalizers is using the code this way. I could write a DummyNormalizer but I am not sure if it is sensible.

**Comment by dunglas** [comment]
IIRC this is not used anywhere and can be removed safely because, as you pointed out, it has never worked. It's a garbage from a refactoring in early development steps.

**Comment by CornyPhoenix** [comment]
But won't it break BC if we remove the third parameter? Or is it okay because PHP ignores superfluous arguments passed to a method?

**Comment by dunglas** [comment]
It looks ok to me but what do you think @symfony/deciders ?

On another hand having the ability to retrieve metadata can be handy in some contexts but you need to adapt your PR to uniquify the metadata collection.

**Comment by CornyPhoenix** [comment]
Actually, I think that removing duplicates is not necessary at all: The only implementation of the `ClassMetadataInterface` is `ClassMetadata` in which `addAttributeMetadata` is prohibited to have more then one `AttributeMetadataInterface` per attribute:

```php
    /**
     * {@inheritdoc}
     */
    public function addAttributeMetadata(AttributeMetadataInterface $attributeMetadata)
    {
        $this->attributesMetadata[$attributeMetadata->getName()] = $attributeMetadata;
    }
```

So why using `array_unique` at all?
