### ISSUE TITLE
Ability to get entity constraints and message in FormBuilder class

### ISSUE THREAD

**Issue by nicholasnet** [symfony/symfony#16449]
I think there should be a way to access all the entity constraints in Form class so that we can pass those information to client side without manually entering those constraints all over again in form class.

For example if we have code like this.
```
class User implements UserInterface, \Serializable
{
  /**
   * @var string
   *
   * @ORM\Column(name="first_name", type="string", length=64)
   * @Assert\NotBlank(message="First name cannot be blank")
   * @Assert\Length(max=64, maxMessage="First name cannot more than {{ limit }} characters long")
   */ 
   private $firstName;
}
```
I would like to access these constraints with messages in form class so that we pass down these information to twig. Like this

```
<input type="text" required="required" data-required-msg="First name cannot be blank" name="firstname" data-max-length="64" data-max-length-msg="First name cannot be more than 64 characters long">
```
Here data attribute should be customizable.

Currently this cannot be achieved without code duplication in either twig or in form class directly.

**Comment by jakzal** [comment]
It's already possible to [get this kind of information](https://gist.github.com/jakzal/5963621) from the metadata factory:

```php
$metadata = $this->container->get('validator')
    ->getMetadataFactory()
    ->getMetadataFor('AppBundle\Entity\Post');
```

You could expose it as javascript, or decorate it in a view object and pass it to twig. 

Do we really need any additional support in core?

**Comment by nicholasnet** [comment]
I think we do because form should be able to gather all the constraints if data class is used. Furthermore, your code does not consider the following
* Retrieval of formatted message (in case of length, message have placeholder) 
* Internationalization of message based on selected locale

Also I think code will be messy if same entity is used in different forms using different validation group since metadata retrieval process will have to be repeated.

These are the few reasons to have this feature.

**Comment by jakzal** [comment]
@nicholasnet I'm not saying you should write messy code and retrieve metadata directly from every form you create. You can abstract it away. I'm just saying it's possible.

Since you've got a use case, perhaps you should try implementing this outside of a framework. It can always be integrated back later. It'd be easier to decide if you had something working.

**Comment by nicholasnet** [comment]
@jakzal I am sure it is possible right now but how can we go about achieving this using form class alone is a question. I know extracting metadata is not a problem but how about extracting formatted message and the leveraging Symfony internationalization for those messages including constraints. 

I am more than happy to work on this feature I just need some guidance regarding how to achieve this.

**Comment by webmozart** [comment]
@nicholasnet Thank you for your suggestion! As was said before, this is possible in userland already. If there's a very good implementation that we could simply add to the core, I'd consider it. But otherwise I don't think we will implement and support this ourselves.

**Comment by mindaugasvcs** [comment]
I solved this using built-in PHP getAttributes method from \ReflectionProperty class. Is it better than using the validator and metadata?

**Comment by mindaugasvcs** [comment]
> I think there should be a way to access all the entity constraints in Form class so that we can pass those information to client side without manually entering those constraints all over again in form class.
> 
> For example if we have code like this.
> 
> ```
> class User implements UserInterface, \Serializable
> {
>   /**
>    * @var string
>    *
>    * @ORM\Column(name="first_name", type="string", length=64)
>    * @Assert\NotBlank(message="First name cannot be blank")
>    * @Assert\Length(max=64, maxMessage="First name cannot more than {{ limit }} characters long")
>    */ 
>    private $firstName;
> }
> ```
> 
> I would like to access these constraints with messages in form class so that we pass down these information to twig. Like this
> 
> ```
> <input type="text" required="required" data-required-msg="First name cannot be blank" name="firstname" data-max-length="64" data-max-length-msg="First name cannot be more than 64 characters long">
> ```
> 
> Here data attribute should be customizable.
> 
> Currently this cannot be achieved without code duplication in either twig or in form class directly.

You can partly achieve this by providing null to the 2nd argument of FormBuilder add method and forcing Symfony to guess the field type. Symfony will try to guess the field type and some options, like required, maxlength and pattern.
