### ISSUE TITLE
Restrict firewall to a specific request by IP

### ISSUE THREAD

**Issue by ste93cry** [symfony/symfony#16457]
In the project I'm working on I'm trying to restrict a firewall to a specific IP address/range. The ACL can already do this, and the firewall seems to support only `host` and `pattern` options. It would be cool if `ip` and `ips` options (same as `access_control`) could be added. This can be done using a custom request matcher, but I should duplicate all the logic of the host and pattern matching too if I want to use a combination of both

**Comment by sstok** [comment]
You can use a custom request_matcher service for more complex cases.

http://symfony.com/doc/current/components/security/firewall.html#a-firewall-for-http-requests
http://php-and-symfony.matthiasnoback.nl/2012/07/symfony2-security-using-advanced-request-matchers-to-activate-firewalls/

**Comment by ste93cry** [comment]
Yes, as I said in my first comment this is a possible solution, however the access_control option supports matching by IP addresses, so why shouldn't the firewall support them too?

**Comment by xabbuh** [comment]
Can you tell us more about your use case? Having the need to configure a firewall based on client information does not sound like a common use case to me.

**Comment by ste93cry** [comment]
a use case could be this: imagine you have two authentication providers (eg. `database` and `in-memory`). Both firewalls could be applied to all the routes, but users accessing a website from the Internet would use the `database` provider while users connecting to the website from inside the network of the server would use the `in-memory `provider.

**Comment by WouterJ** [comment]
It sounds more that you want to implement this on the UserProvider side instead of the firewall. There still is a firewall in both cases, you just want to get users from another provider.

A solution that can be already implemented is by creating a sort of chaining user provider, like:
```php
class ChoosingUserProvider implements UserProviderInterface
{
    private $externalUserProvider;
    private $internalUserProvider;
    private $requestStack;

    public function __construct(UserProviderInterface $externalUserProvider, UserProviderInterface $internalUserProvider, RequestStack $requestStack)
    {
        // ...
    }

    public function loadUserByUsername($username)
    {
        if (/* ... internal request */) {
            return $this->internalUserProvider->loadUserByUsername($username);
        }

        return $this->externalUserProvider->loadUserByUsername($username);
    }

    // ...
}
```

**Comment by javiereguiluz** [comment]
I agree with @WouterJ. A chained user provided (as shown by Wouter or using [the built-in one](http://symfony.com/doc/current/cookbook/security/multiple_user_providers.html) provided by Symfony) would be the best solution here.

Enabling/disabling firewalls just with the user IP seems a fragile solution to me.
