### ISSUE TITLE
[DependencyInjection] Container::set() is useless if the entry is an alias

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#16461]
In my integration tests I want to replace a service by a fake implementation. For example I want to temporarily replace the `event_dispatcher` by a mock that will store all triggered events:

```php
$container->set('event_dispatcher', $fakeDispatcher);
```

The problem is that `event_dispatcher` is an alias, and [`Container::get()` first resolves aliases before trying to find the entry](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/Container.php#L270-L272).

That makes `Container::set()` silently useless when setting an entry that is an alias.

IMO this is a bug, and I see 2 solutions (by order of preference), feel free to suggest alternatives:

- `set()` should erase any existing alias because it should just work
- `set()` should throw an exception if setting an alias

I can implement the solution if one is chosen.

**Comment by ro0NL** [comment]
3. Set the actually aliassed key?

**Comment by mnapoli** [comment]
Yes but:

- it's silently useless, which is very unhelpful
- it leads to this for example (what I use in some tests):

```php
$container->set('event_dispatcher', $dispatcher); // if debug=false
$container->set('debug.event_dispatcher', $dispatcher); // if debug=true
```

No great… At all.

I don't see a reason why `Container::set()` should not work in that case.

**Comment by Taluu** [comment]
I think the proper option should be the be able to erase that when building the container (`ContainerBuilder`) but on the `Container` it should be forbidden to do so

**Comment by mnapoli** [comment]
Why?

**Comment by Taluu** [comment]
Once the container has been built, it shouldn't be changed so easily IMO (I may be wrong though ; if it is the case, the option of replacing the service is still a good one IMO)

**Comment by stof** [comment]
@Taluu ``set`` makes sense at runtime, not during container building (the ContainerBuilder has the method, because you can keep using it as the runtime container when you don't dump an optimized container). during container building, you should be setting definitions

**Comment by wpeereboom** [comment]
@mnapoli Did you find or build a work arround ? I run into the same problems. I suggest the option to set and overwrite the existing alias makes most sense. Let me know if I can be at any help.

**Comment by mnapoli** [comment]
@wpeereboom I just opened a pull request to fix this: #17742

**Comment by wpeereboom** [comment]
@mnapoli Great, thanks

**Comment by Jean85** [comment]
This introduced an error in my case. 

When you have an alias of an alias, it overwrites just the first alias, without cascading.
This helped me uncover a bug, and I fixed it setting directly the root service instead of the alias; but I'm not sure if it creates a BC.

Example: Doctrine default EM

```
$container->set('doctrine.orm.entity_manager', $fake);
$container->get('doctrine')->getManager(); // !== $fake, it uses 'doctrine.orm.default_entity_manager', which aliases to the default connection EM

```
