### ISSUE TITLE
Hash of UploadedFile

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16479]
Is there any way to calculate the hash of an uploaded file?
Symfony\Component\HttpFoundation\File\UploadedFile

There is a PHP function for it:
http://php.net/manual/de/function.hash-file.php

Why is there no function like this?
```
$uploadedFile->calculateHash('sha256');
```

**Comment by sstok** [comment]
The `UploadedFile` extends file which in turn extends the `\SplFileInfo` class.
So you can get the actual temp-file location with `$uploadedFile->getPathname()`.

`hash_file('sha256', $uploadedFile->getPathname())`

**Comment by JHGitty** [comment]
What's about integrating this feature as official Symfony feature to the UploadFile class?

**Comment by Tobion** [comment]
Feel free to make a PR, but IMO it's not worth as there is already a way of doing it.
