### ISSUE TITLE
Error when submitting empty value for optional choice field in Propel

### ISSUE THREAD

**Issue by mcrawford-dayspring** [symfony/symfony#16478]
Issue #14583 was fixed for Doctrine, but is still broken for Propel and the Propel Bridge (PostgreSQL for the database). Submitting an empty value for a choice list gives the error:

```
Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
```

The code from the original post in #14583 (adjusted for PHP 5.3) seems to fix the problem:

``` PHP
public function getChoicesForValues(array $values)
    {
        if (empty($values)) {
            return array();
        } else {
            $first = reset($values);
            if (empty($first)) {
                return array();
            }
        }
```

**Comment by jakzal** [comment]
@mcrawford-dayspring what's actually being submitted in your case?

**Comment by mcrawford-dayspring** [comment]
Just an empty string is being submitted:

    string(0) ""

My field is defined as a ModelType with an empty_value property, and is not required by validation:

```PHP
->add('eventData', 'model', array(
        'class'       => 'zzzBundle\Model\EventData',
        'property'    => 'eventDateAndName',
        'empty_value' => '- NO EVENT SELECTED -',
        'query'       => EventDataQuery::create()
                    ->filterByEventDate(new DateTime(), Criteria::GREATER_THAN)
                    ->orderByEventDate(Criteria::DESC)
    ,
        'required'    => false,
))
```

**Comment by stood** [comment]
:+1 In ModelChoiceList for method getChoicesForValues values is not empty but the first value of array is empty.

**Comment by xabbuh** [comment]
closing here as the PropelBridge is no longer part of the Symfony core since 2.7
