### ISSUE TITLE
Data transformer didn't work on entity field type

### ISSUE THREAD

**Issue by bilougit** [symfony/symfony#16476]
I couldn't make the "harder example" of the data transformer page work on an entity field type http://symfony.com/doc/current/cookbook/form/data_transformers.html#harder-example-transforming-an-issue-number-into-an-issue-entity.

Created a class which implements DataTransformerInterface, which is called this way

```php
// My form
$builder
            ->add('state', 'entity', array(
                'placeholder'     => 'Choose a country',
                'class'           => 'espace\de\nom\State',
                'attr'            => $array,
                'choices'         => $options['states'],
                'invalid_message' => 'That is not a valid state key ',
            ));

$builder->get('state')->addModelTransformer(
    new MyTransformer($this->em)
);

// My transformer
class MyTransformer  implements DataTransformerInterface
{
     // Output of this is NULL
     public function transform($entity) {
          var_dump($entity); die('');
          .....
     }

    // This is never called, (obviously I took care of removing the debug stuff into transform
    // method first
    public function reverseTransform($string) {
          var_dump($string); die('');
    }
```

When I remove all die and var_dump, getErrors(true) on my form after handleRequest shows up:

```
This is not a valid state key
```

And the deeper one
```
Unable to reverse value for property path "state": The choice "LA" does not exist or is not unique
```

**Comment by stof** [comment]
you are not following the doc properly. they are **not** applying this on an ``entity`` type (which is already a choice between entities)

And your model transformer ``reverseTransform`` is called *after* the choice type did its work to find the right answer (and it receives an object or null as input btw, as the data of the form is an object at this point).
It is not called in your case before the submission fails in the entity type before reaching your transformer

**Comment by bilougit** [comment]
I'm a bit confused actually, you're not saying that we can't use model transformer with entity type if I understood your answer well.

Plus reverseTransform is not called because the submission fails. But the submission fails because it's can't reverse the received value to an object, that's why I wanted to used Transformers, to make the reverse succeed.

**Comment by stof** [comment]
@bilougit you can use model transformers in this case too. but not the one described in the doc, as this one is meant to be applied on a text field, and the entity type is not a text field

**Comment by steady-daddy** [comment]
@bilougit How were you able to solve the first part? I have the same issue. ReverseTransform not called after form submission and the form is giving invalid errors. I'm using a entity field type to display tags in a select field and trying to use a combination of selectize.js and data transformers to add new tag to the database.
My form looks like this:

```
        $builder
            ->add('tag', 'entity', array(
                'class' => 'AppBundle:Tags',
                'property' => 'name',
                'label' => 'Tag',
                'multiple'  =>  false,
                'expanded' => false
            ))
        ->add('save', 'submit');

        $builder->get('tag')
                ->addModelTransformer(new TagTransformer($this->manager));

```

**Comment by igorladela** [comment]
Same issues, but for "date" type:

`$builder
            ->add('fromDate', 'date', array(
                'widget'    => 'single_text',
                'format'    => 'yyyy-MM-dd',
                'html5'     => false,
                'label'     => false,
                'required'  => false
            ))
        ;

        $builder->get('fromDate')
          ->addModelTransformer(new StringToDateTransformer());`

`/**
 * Class StringToDateTransformer
 * @package BindrBundle\Form\DataTransformer
 */
class StringToDateTransformer implements DataTransformerInterface
{
    /**
     * Transforms an object (DateTime) to a string.
     * From Database to HTML
     *
     * @param  \DateTime|null $date
     * @return string
     */
    public function transform($date)
    {
        return new \DateTime($date);
    }

    /**
     * Transforms a string to an object (DateTime).
     * From HTML to Database
     *
     * @param  string $date
     * @return \DateTime|null
     * @throws TransformationFailedException if object (\DateTime) is not found.
     */
    public function reverseTransform($date)
    {
        if (null === $date) {
            return new \DateTime($date);
        }

        return $date->format('m Y');
    }
}`

**Comment by stof** [comment]
@steady-daddy as you use a model transformer, the reverse side runs *after* the selection of the choice in the entity type. So your issue is that you try to create the new tag too late (you do it after Symfony tries to use it, and so it already errorred saying it was not found)

**Comment by steady-daddy** [comment]
@stof So how would you create a new tag before Symfony try to use it. Some code example please.

**Comment by stof** [comment]
@steady-daddy the right place is probably using the ``PRE_SUBMIT`` event

**Comment by steady-daddy** [comment]
Complex stuff that. Thanks anyways, will try later and let you know if that works.

**Comment by MlleDelphine** [comment]
Did you find a good solution ?
I'm stuck even with PRE_SUBMIT event :/
