### ISSUE TITLE
Input File being nulled on form update

### ISSUE THREAD

**Issue by anacicconi** [symfony/symfony#16489]
Hello,

O the application I work, we upload a lot of files. We noticed that when we submit a form for the first time the value is well registered on database. However, when we update the form, if the field is blank, the value of the database will be updated to null.

We have been trying some workarounds. However, this time we decided to search for the right way to do it. I found many questions and suggestions on stackoverflow. Ex:

http://stackoverflow.com/questions/25291607/symfony2-how-to-stop-form-handlerequest-from-nulling-fields-that-dont-exist
http://stackoverflow.com/questions/22557340/symfony2-do-not-update-a-form-field-if-not-provided
http://stackoverflow.com/questions/19793767/does-symfony-2-support-partial-form-binding

I tried them all and nothing works. The only solution that works is not compatible with @Assert\Image so I think it is not the best one.

I wanted to post it here to have a feedback and to know how other people solved this problem.

This is my entity:

    namespace MyApp\CoreBundle\Entity\Test;
	
	use Doctrine\ORM\Mapping as ORM;
	use Knp\DoctrineBehaviors\Model as ORMBehaviors;
	use Symfony\Component\Validator\Constraints as Assert;
	
	/**
	 * @ORM\Table(name="test_input_file")
	 * @ORM\Entity()
	 */
	class TestInputFile
	{
	    /**
	     * @var integer
	     *
	     * @ORM\Column(name="id", type="integer")
	     * @ORM\Id
	     * @ORM\GeneratedValue(strategy="AUTO")
	     */
	    protected $id;
	
	    /**
	     * @ORM\Column(name="header", type="string", nullable=true)
	     */
	    protected $header;
	
	    /**
	     * Get id
	     *
	     * @return integer
	     */
	    public function getId()
	    {
	        return $this->id;
	    }
	
	    /**
	     * Set header
	     *
	     * $header
	     */
	    public function getHeader()
	    {
	        return $this->header;
	    }
	
	    /**
	     * Get header
	     *
	     * @return $header
	     */
	    public function setHeader($header)
	    {
	        $this->header = $header;
	
	        return $this;
	    }
	}

My Controller:

    /**
     * @Route("/{id}/inputfile/", requirements={"id" = "\d+"}, name="input_file")
     * @Template()
     */
    public function testInputFileAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $testInputFile = $em->getRepository('MyAppCoreBundle:Test\TestInputFile')->find($id);

        $form = $this->createForm(new TestInputFileType($testInputFile), $testInputFile);

        $form->handleRequest($request);

        if ($form->isValid()) {

            //Save entity
            $em = $this->getDoctrine()->getManager();
            $em->persist($testInputFile);
            $em->flush();

            return $this->redirectToRoute('input_file', array('id' => $testInputFile->getId()));
        }

        return array(
            'form' => $form->createView(),
            'testInputFile' => $testInputFile
        );
    }

My Twig:

    {{ form_start(form) }}
	{{ form_row(form.header) }}
	{{ form_widget(form._token) }}
	{{ form_end(form) }}

My Form Type:

       namespace MyApp\CoreBundle\Form\Type\Test;
	
	use Symfony\Component\Form\AbstractType;
	use Symfony\Component\OptionsResolver\OptionsResolverInterface;
	use Symfony\Component\Form\FormBuilderInterface;
	use Symfony\Component\Form\FormEvent;
	use Symfony\Component\Form\FormEvents;
	
	class TestInputFileType extends AbstractType
	{
	    protected $entity;
	
	    protected $currentField;
	
	    public function __construct($entity)
	    {
	        $this->entity = $entity;
	    }
	
	    /**
	     * @param FormBuilderInterface $builder
	     * @param array $options
	     */
	    public function buildForm(FormBuilderInterface $builder, array $options)
	    {
	        $builder
	            ->add('header', 'file', array(
	                'label' => 'header',
	                'data_class' => null,
	                'required' => false
	            ));
	
	        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) {
	            $this->currentField = $this->entity->getHeader();
	        });
	
	        $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
	            // Retrieve submitted data
	            $form = $event->getForm();
	            $inputFile = $form->getData();
	            $newHeader = $inputFile->getHeader();
	
	            // Verify if the form field is empty and if the field is set on database
	            // Set the value of database again to avoid deleting it
	            if (is_null($newHeader) && !is_null($this->currentField)) {
	                $inputFile->setHeader($this->currentField);
	            }
	        });
	    }
	
	    /**
	     * @param OptionsResolverInterface $resolver
	     */
	    public function setDefaultOptions(OptionsResolverInterface $resolver)
	    {
	        $resolver->setDefaults(array(
	            'data_class' => 'MyApp\CoreBundle\Entity\Test\TestInputFile'
	        ));
	    }
	
	    /**
	     * @return string
	     */
	    public function getName()
	    {
	        return 'test_input_file_form';
	    }
	}

So the solution I found is on the Form Type. I listen to the first event, get the value of the database, initialize a variable. Then I listen to a second event and set the property with this variable. It works, but it seems too much code to do solve a simple problem. Moreover, I can't use Assert Image anymore. Otherwise, the set fails:

    @Assert\Image(maxSize="1M", mimeTypes = {"image/png", "image/jpeg"}, mimeTypesMessage = "upload.bad_extension")

**Comment by anacicconi** [comment]
Sorry, I wasn't using the UploadedFile in the right way.

For those who have the same problem, use this link:

http://symfony.com/doc/current/cookbook/doctrine/file_uploads.html

Instead of this one:

http://symfony.com/doc/current/cookbook/controller/upload_file.html

**Comment by shubaivan** [comment]
Hello there
I have the same problem with edit form and I not undertand how to solve this problem ? 
After submit edit form I still have null in field `brochure` from example :( 

I create entity with attachment file, field `brochure`, after that I had file name in db in field `brochure`.
Then I open edit form, nothing changing, just submit, before in action did that part:

```

$product->setBrochure(
    new File($this->getParameter('brochures_directory').'/'.$product->getBrochure())
);

``` 
and after submitted form in action

```

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                /** @var Application $entity */
                $entity = $form->getData();
                $fileApp = $entity->getBrochure(); // null

```

why null ?

**Comment by etshy** [comment]
Same issue here.
For my part, I use mongo and store the files in db.
When I submit the form without an image in the FileType field, the image is deleted from Document.
How can we handle that ?

For now I set something like this in my `setAvatar` to avoid the null from Form submit to erase the Image:
  ```
  /**
     * @param Image $avatar
     */
    public function setAvatar(?Image $avatar): void
    {
        if (!$this->avatar instanceof Image || $avatar instanceof Image) {
            $this->avatar = $avatar;
        }
    }
```
and added a `removeAvatar` method to remove manually the avatar
```
    /**
     * Delete the Avatar
     */
    public function deleteAvatar(): void
    {
        $this->avatar = null;
    }
```

I guess you can do something similar for filePath too, but I don't know if my way of handling that is right.

**Comment by etshy** [comment]
Oh true, never tried to change the method to PATCH for edition.
I only used PATCh and PUT with API, not with 'normal' Form.

I'll definitely try that, Thanks.

**Comment by jonathangreco** [comment]
Sorry but can you be more explicit, maybe with a snippet, for what we should do to make this work ?

**Comment by etshy** [comment]
Change the method of your form with `$builder->setMethod('PATCH');`
It will create a hidden input to change the method used to submit the Form `<input type="hidden" name="_method" value="PATCH">`

Didn't tried yet, but I assume the `$form->handleRequest($request)` will detect the method and handle a PATCH instead of a PUT or a POST (updating only passed fields instead of all object's fields)

**Comment by Jelmerb** [comment]
> Sorry, I wasn't using the UploadedFile in the right way.
> 
> For those who have the same problem, use this link:
> 
> http://symfony.com/doc/current/cookbook/doctrine/file_uploads.html
> 
> Instead of this one:
> 
> http://symfony.com/doc/current/cookbook/controller/upload_file.html

I have followed this guide to the letter, still the field in the database gets overwritten with null. Has anyone found a good solution for this problem yet?

**Comment by DoobleD** [comment]
I have the exact same issue. Anyone found a solution ?

**Comment by DoobleD** [comment]
All right, after a bit of trouble, here is my workaround : 

First I get the original filename from my entity in the controller, before handling the request : `$filename = entity->getFile();`. 

In my form type, I added a hidden input with `mapped = false`. 

On the client side, I then use javascript to set that hidden input to some value only if the user changes the file (meaning: if he browses and select a file or if he removes the file previously set if any).

Back in my controller, after the handleRequest, I restore the original filename to my entity only if the hidden input has a no value and if there was an originale filename to begin with. In other words, I manually reset the filename in the entity to the original filename only if the user didn't change or remove the file.

This isn't probably super clean, but it avoids losing the original file if the user doesn't change anything, while also allowing him to actually remove the file if he wants to.
