### ISSUE TITLE
Runtime Notice: Accessing static property Proxies\__CG__\Bundle\Entity\Entity::$lazyPropertiesDefaults as non static. Symfony PropertyAccessor error

### ISSUE THREAD

**Issue by roundge** [symfony/symfony#16485]
Hi there, 

I have an error with Symfony 2.7.6 & Doctrine.
I try to serialize my 'Employee' Entity, which is a child of a Person superclass. This one has a relation with an 'Adresse' Entity.

When I serialize the Employee Entity, Symfony returns this error : 
>Runtime Notice: Accessing static property Proxies\__CG__\WebInscriptionBundle\Entity\Contact\Adresse::$lazyPropertiesDefaults as non static
>  500 Internal Server Error - ContextErrorException 

I understand the problem. Symfony try to access a property of my object, which is a proxy class. 
I've changed the 'fetch mode' to EAGER, but nothing's change.
The property of the probleme belong to the proxy class. It's the `public static $lazyPropertiesDefaults` .
This issue is similar to this : http://stackoverflow.com/q/31623080

Here's the line which failed : 
https://github.com/symfony/symfony/blob/v2.7.6/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L350

the property is static & public, but the getter __getLazyProperties isn't called, and symfony try to access as a public property ( $object->$property ).

So, the fetch mode EAGER seems to work (my entity is hydrated), maybe there is a mistake, a missing test ? 
I think the visibility of my variables are ok. 'Protected' in the superclass and 'private' in child Employee Entity.  Any ideas ? 

Thanks !

**Comment by stof** [comment]
Can you give a code snippet reproducing the issue ?

**Comment by roundge** [comment]
Ok thanks, I filter the code and post here soon

**Comment by roundge** [comment]
```
[...]
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

class PersonneController extends Controller {
[...]
    public function getPersonneInfosByIdAction($personneId){

      $em = $this->getDoctrine()->getManager();
      $encoders = array(new JsonEncoder());
      $onorm = new ObjectNormalizer();

      $normalizers = array($onorm);
      $onorm->setCircularReferenceHandler(function ($object) {
          return $object->getId();
      });
      $serializer = new Serializer($normalizers, $encoders);


      $personne = $em->getRepository('OCIMWebInscriptionBundle:Contact\Personne')->find($personneId);
      
      // Dump is fine. Entity is child of Personne (Employee) and have an Adresse which is hydrated
      // \Doctrine\Common\Util\Debug::dump($personne);

      return new Response($serializer->serialize($personne, 'json'));

    }
}
```

If I set manually a null Adresse before the serialization (`$personne->setAdresse(null)`) it happens to.

**Comment by roundge** [comment]
Adding a little test in /vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php do the trick. I think it's very inconsistent (I'm not a Symfony Core Developper), and maybe the error is higher.
Before:
https://github.com/symfony/symfony/blob/v2.7.6/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L349-L352
```
elseif ($classHasProperty && $reflClass->getProperty($property)->isPublic()) {
            $result[self::VALUE] = &$object->$property;
            $result[self::IS_REF] = true;
        } elseif ($reflClass->hasMethod('__get') && $reflClass->getMethod('__get')->isPublic()) { 
```
After:
```
        } elseif ($classHasProperty && $reflClass->getProperty($property)->isPublic()) {
          // I added this test
          if($reflClass->getProperty($property)->isStatic()){
            $result[self::VALUE] = &$object::$$property;
          }
          else{
            $result[self::VALUE] = &$object->$property;
          }
            $result[self::IS_REF] = true;
```
The static property is called here:  `&$object::$$property;` , although there is a getter called `__getLazyProperties()`...

 The entity is normally fetched in 'EAGER' mode, so why Doctrine/Symfony need to call $lazyPropertiesDefaults ?

**Comment by xabbuh** [comment]
I wonder if applying a fix similar to #16453 and #16454 to the `ObjectNormalizer` would solve your issue.

**Comment by nikos90** [comment]
I am facing the same problem too.
The #16453 and #16454 didn't work for me.

**Comment by nikos90** [comment]
i followed @roundge solution and needed to change one more thing in order to work for me.
i replaced this on line 363 :                 $result[self::VALUE] = &$object->{$access[self::ACCESS_NAME]};

with this: 

$reflClass = new \ReflectionClass($object);
                if($reflClass->getProperty($property)->isStatic()){
                    $result[self::VALUE] = &$object::$$property;
                }
                else{
                    $result[self::VALUE] = &$object->$property;
                }

**Comment by roundge** [comment]
thanks @xabbuh and @nikos90 . It seems to be the same problem. I'm waiting for the update to close this issue. Thanks to all of you.

**Comment by xabbuh** [comment]
@roundge Can you also take a look at the changes from #16462?

**Comment by roundge** [comment]
@xabbuh it could be the same problem, but on the 2.7.6 branch.
A PropertyAccess error while serializing an Entity. 
But the static property is trying to access is $lazyPropertiesDefaults in a doctrine proxy class. PropertyAccessor doesn't use the getter __getLazyProperties.
Sorry I'm not very comfortable with github and SF core yet.

**Comment by roundge** [comment]
hum ok I found this : #16463 for the 2.7 branch.

**Comment by roundge** [comment]
But the same problem occurs at line 437. https://github.com/dunglas/symfony/blob/f626f7f734a598501de861b6709196ec9480646f/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L437

**Comment by roundge** [comment]
In fact, the Symfony Serializer is trying to serialize a doctrine property `public static $lazyPropertiesDefaults` in the proxy class. 
If I exclude the property of the serialization, It works !
```
  $onorm = new ObjectNormalizer();
  $onorm->setIgnoredAttributes(array('lazyPropertiesDefaults'));
```
Is normal there is a doctrine proxy class whereas the entity is configured with `fetch: EAGER`

**Comment by stof** [comment]
> Is normal there is a doctrine proxy class whereas the entity is configured with fetch: EAGER ?

It is totally possible, as something else might have required the usage of a proxy earlier in Doctrine, and Doctrine will then continue using the same instance

**Comment by roundge** [comment]
Ok. So what could I do to solve the problem ? Ignoring the property $lazyPropertiesDefaults do the trick during the serialization, but this issue just happened to me / or someone have already been able to reproduce this issue ? 
I can try to create a PR and try to solve this if a bug is confirmed. (try, i'm a padawan)
I'll come back latter with more information.
Thanks you so much for your support and patience ;)
