### ISSUE TITLE
[Console] Exception event is only dispatched when exception occured in command

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#16497]
The description of the exception event is: "The EXCEPTION event occurs when an uncaught exception appears". However, it turns out it's only dispatched when an uncaught exception appears while running `Command#run()`.

I'm throwing an exception in the `console.COMMAND` event and it is still handled by the default exception handler, not by the custom exception listener.

Does it make sense to wrap the complete `doRunCommand()` or `doRun()` call? (just like the default exception handler does?)

**Comment by funivan** [comment]
From `ConsoleExceptionEvent` 
`* Allows to handle exception thrown in a command.`
Events can handle logic different then command. For example disable command run according to some status in database. If  `DataBaseException` appear in this event it will be handled by  the default exception handler, and I thinks this is right. 

`ConsoleExceptionEvent` indicate that there is something wrong in command during execution.

If you throw exception in `console.COMMAND` it doesn’t mean that command is invalid. IMHO
