### ISSUE TITLE
Add a new option to FormType "force_submit" 

### ISSUE THREAD

**Issue by guilhermeblanco** [symfony/symfony#16491]
By having this flag, it would force submission even if form is empty (no data through request)

Discussed with @webmozart , makes sense... further description to follow later.

**Comment by iltar** [comment]
Would this count for nested types? How would [`isSubmitted()`](https://github.com/symfony/symfony/blob/3909460c04e6b13858f2fa3b4e41ec68fdebf0a2/src/Symfony/Component/Form/Form.php#L663) work [in this example](https://github.com/hostnet/form-handler-component/blob/master/src/Simple/SimpleFormProvider.php#L62)?

**Comment by HeahDude** [comment]
@iltar @guilhermeblanco see #18053 for a BC implementation.

**Comment by guilhermeblanco** [comment]
@HeahDude thanks for working on it! =)

**Comment by HeahDude** [comment]
Should be closed (ref #18053).
