### ISSUE TITLE
Profiler bar calls deprecated methods

### ISSUE THREAD

**Issue by efalder413** [symfony/symfony#16495]
![screenshot from 2015-11-07 12 37 44](https://cloud.githubusercontent.com/assets/6841035/11017198/a74d300e-854c-11e5-94d1-2bd8a5d57536.png)

**Comment by jakzal** [comment]
re #16331

**Comment by jakzal** [comment]
@efalder413 see https://github.com/symfony/symfony/issues/16422#issuecomment-153041010
