### ISSUE TITLE
[Form] Setting reference for oneToOne relation from inverse side

### ISSUE THREAD

**Issue by 11ya** [symfony/symfony#16499]
Hello, community! I'm facing with a trouble in following situation.
I have mapped 2 entities and oneToOne relation between them.
**OwningSide.php**

``` php
class OwningSide
{
...
   /**
     * @var InverseSide
     *
     * @ORM\OneToOne(targetEntity = "InverseSide", inversedBy = "owner")
     * @ORM\JoinColumn(name = "inverse_id", referencedColumnName = "id", onDelete = "SET NULL")
     */
    private $inverse;
```

**InverseSide.php**

``` php
class InverseSide
{
...
   /**
     * @var OwningSide
     *
     * @ORM\OneToOne(targetEntity = "OwningSide", mappedBy = "inverse")
     */
    private $owner;
...
   public function setOwner($owner)
   {
      $this->owner = $owner;
      if ($owner) $owner->setInverse($this);
   }
```

I want to create form for setting this relation from inverse side:
**InverseSideFormType.php**

``` php
class InverseSideFormType extends AbstractType
{
   public function buildForm(FormBuilderInterface $builder, array $options)
   {
      $builder
         ->add('owner', 'entity', [
                'label' => 'Owner',
                'class' => 'AppBundle:OwningSide',
                'required' => false,
                //'by_reference' => false
            ])
  }
```

So I can successfully set up realtion between objects by handling request for this form, but i can't break this relation (set to NULL).
If I want to do this in setter for owner, I would set by_reference to 'false' for this field (like in tutorial for collection field and oneToMany relation), but I get the following exception:

```
Entities passed to the choice field must be managed. Maybe persist them in the entity manager?
```

(current entity in "owner" property is not managed)
So is there a decision to solve this problem in a proper way?

**Comment by iltar** [comment]
You can always avoid using entities as data objects, this would directly solve your problem. You could use a simple object which contains the data needed like a DTO (Data Transfer Object), which you can populate based on your entity. Based on this object, you can then create (or update) your entities and prevent them from getting into an invalid state.

**Comment by xabbuh** [comment]
I am closing here as this rather looks like a support question for which one of the [support channels](https://symfony.com/support) should be used.
