### ISSUE TITLE
[Form] Passing timezone settings from DateTimeType to DateType through model_timezone option

### ISSUE THREAD

**Issue by luads** [symfony/symfony#16518]
I came across an issue with daylight saving timezones where the day which changes the time is handled as a invalid date in PHP.

Since my form had a `DateType` field, I managed to fix this issue by setting both `model_timezone` and `view_timezone` to UTC. The same issue happened on a `DateTimeType` field, but setting the options didn't solve the error.

Looking further at the code, I realized that there's specific options been passed to the new `DateType` field created, and the timezone options aren't. This is the specific piece of code: https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php#L113

Adding `model_timezone` and `view_timezone` to this array solved my problem.

Am I missing something here, or this options should be passed to the `DateType` field?

**Comment by mvrhov** [comment]
setting default php timezone should also work as model and view timezone options are deprecated

**Comment by hisamu** [comment]
@mvrhov there's nothing wrong with php timezone. It's a specific issue with daylight saving time, on the exact day that 1 hour is increased here, making 00:00:00 of that day a invalid date, since it doesn't exist.

**Comment by jakzal** [comment]
@hisamu would you be able to provide a failing test case for this issue?

**Comment by mvrhov** [comment]
Maybe this is the same as https://github.com/symfony/symfony/issues/16368#issuecomment-159249951

**Comment by xabbuh** [comment]
Should have been fixed by #19541. Please comment and provide a small example application that allows to reproduce if you are still affected by this issue.
