### ISSUE TITLE
[Controller] Avoid hardcoding the status for the redirection in Controllers

### ISSUE THREAD

**Issue by jcchavezs** [symfony/symfony#16513]
The redirect and redirectToRoute methods from the Controller are using hardcoded default status code:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php

Can we use the constant values from Symfony\Component\HttpFoundation\Response instead?

**Comment by stof** [comment]
I don't understand what you mean. The default value of a method is always hardcoded: if you want to change it, the way to do it is to pass a value to the method instead of relying on the default

**Comment by jcchavezs** [comment]
@stof I was not finished with the description. Sorry for that.

**Comment by mvhirsch** [comment]
:+1: for using constants from ```Symfony\Component\HttpFoundation\Response```.
Would there be any side-effect with the PSR-7 bridge?
