### ISSUE TITLE
Mixing form types based on provided data

### ISSUE THREAD

**Issue by OndrejPiza** [symfony/symfony#16512]
Hi,

is it possible to change forms or add new ones based on provided data from request or DB?

I'm using ODM with MongoDB, and the nested documents can be very different, sometimes I need to specify my own form type, not just the "generated" one. For example for selecting images I have my own form type, problem is, that this image is in the nested document, or it can be more than 1 level deeper. 

So far I have been changing form types in the PRE_SET_DATA or PRE_SUBMIT form events. Is it the right way to achieve the behavior? 

I was experimenting with my own form type based on collection, but there is a big problem with collection, which only accepts numeric index, but I need key => value, so that I can from the key read the type and act according to it. Also I don't know how form determines if there is something deleted or added. Does it loops through the whole collection?

Thank you for any advice

**Comment by ewgRa** [comment]
Better to ask help for such questions at http://stackoverflow.com/questions/tagged/symfony
