### ISSUE TITLE
3 layers architecture and transactions management

### ISSUE THREAD

**Issue by Vicente69** [symfony/symfony#16525]
Hi all,

I don't open this issue for a bug report, but rather to start a discussion, and grab feedback about the [siouan/TransactionBundle][siouan-transaction-bundle].

Coming from the Java world, I spent the last 3 years working on an important amount of PHP applications, with or without framework (Symfony, Zend, etc). I learnt to use Symfony, Doctrine ORM and ODM, DI, ... well a good stack of good components. But actually I am still questioning myself. There are so many tutorials, documentation, about how to use PHP components and frameworks, on the web, but I find many of the published examples make a common mistake: throw away the layer architecture by accessing components in a non-visible layer.

Let me explain, generally, in a 3 layers application, components are spread in:
- the web/presentation layer at the top: HTTP controllers for web applications, TWIG views, mapping classes for forms, for example. As it sounds, this layer shall only deal with data presentation, and use the business layer to deal with the end-user expectation.
- the business layer in the middle: containing the heart of the application. Any business logic and model resides in this layer. This layer controls atomicity, consistency, isolation and durability of any service executed.
- the data/persistence/DAO layer at the bottom: components in charge of reading/writing data from/in a storage system (database, F/S, memory, or any interface). For instance, database connections, ORM/ODM, DBAL, object/entity managers, repositories, etc.

From a given layer, we shall never access components in an upper layer (data X-> business, business X-> presentation forbidden), or components in a non directly lower layer (presentation X-> persistence).

Unfortunately, digging into most of examples provided in the Symfony documentation, the business layer rarely appears: actions in controllers, or even forms, directly access the entity manager living in the persistence layer, or perform immediate business logic. The case of forms is really the best part I guess, as the data may be directly loaded from the form type class, whereas forms should only deal with mapping data coming from requests, and preparing data for responses. If I go further, transactions are managed by actions, whereas they shall be managed by business services. Therefore, it is very difficult to create reusable components, as the logic is in controllers' actions.

_Does it make sense for you too? Am I mistaken or missing something on my own?_

To me, many examples sound like great mistakes, and it doesn't help developers to keep their mind's clear, and design decoupled components with separated concerns/responsibilities. It is a pity, since the dependency injection engine is really powerful, but it is difficult to take advantage of its full capabilities. For example, controllers as presentation services shall be a standard recommendation in Symfony!

As explained at the top of this message, I've been working on a bundle to help developers correctly organize their business code, and not be scared with transaction management, and the inheritance of the transactional context in nested business service calls (for that matter, the awesome [JMSAopBundle][jms-aop-bundle] which brings at last AOP to the PHP world, provided a great help).

I would really appreciate feedbacks from the Symfony/Sensio teams about this discussion, and more precisely the benefits/drawbacks of the [siouan/TransactionBundle][siouan-transaction-bundle]. I think it can really help designing
applications with a good separation of components in layers, and pushing again the business layer in the foreground.

Thanks a lot for your help, comments, and feedbacks.
BR,
Vincent

[jms-aop-bundle]: <https://github.com/schmittjoh/JMSAopBundle>
[siouan-transaction-bundle]: <https://github.com/siouan/TransactionBundle>

**Comment by sstok** [comment]
The examples don't include these "complex" situations as it tends to overwhelm newcomers to the Symfony word. Just because it is not documented doesn't however mean you can't use these advanced techniques.

In fact @matthiasnoback gave a great number of presentations about this :+1: 
http://www.slideshare.net/matthiasnoback/hexagonal-architecture-messageoriented-software-design-symfony-live-berlin-2015

**Comment by Vicente69** [comment]
Hi @sstok,

Thanks for your answer.
I understand of course the need to introduce concepts step by step, in the documentation, but this is not exactly the subject I wanted some feedback. However, I took a look at the presentation, and I agree. I don't initiate this discussion to get some sources of learning, the web is plenty of interesting resources, and I guess I humbly have a good knowledge of framework mechanisms, design patterns, and application design principles more generally, but there's always to learn...

What are the ready-to-use solutions in Symfony to deal with transactions management efficiently?
How people today manages their transactions correctly (nested business calls, etc...), and is the bundle I mention relevant to you?

I try to explain why this bundle exists, why I think it can provide benefits to the community, because people are not tend to code everything in controllers, or even do a `begin_transaction` by hand. I can't see a good concrete example of a layered application, with transaction management explained in details (location, strategies, etc.), and I'm wondering if there's a reason for this?
Thanks again for your comment.

**Comment by jrobeson** [comment]
@Vicente69 : i think you muddied your question a bit there. Can you try it again with just the question and no comments on why the examples/docs are the way they are?

**Comment by Vicente69** [comment]
Sure, these are the 2 questions in the middle of my latest post :). Thanks

**Comment by jakzal** [comment]
I'm sorry to be closing this interesting discussion, but unfortunately it doesn't belong here. 

We're focusing on Symfony development here and there's nothing to do in the framework itself regarding your suggestions. Symfony only provides view and controller layers. Domain is totally up to you. Currently, there's nothing preventing you from implementing three layered architecture in Symfony. 

Perhaps it's more suitable for `symfony/symfony-docs` if you've got ideas on how to improve the documentation.

**Comment by Vicente69** [comment]
I understand, thanks to all of you..

**Comment by matthiasnoback** [comment]
@sstok Thanks for the mention!
@jakzal Very nice explanation about the "point" of Symfony. I'll keep that in mind. I'm currently rewriting part of my book "A Year with Symfony" because I want to provide some guidance for the domain part and how to connect everything.
