### ISSUE TITLE
StringUtil::singularify() does not convert "series" correctly

### ISSUE THREAD

**Issue by michal-szu** [symfony/symfony#16532]
I've got problem with propertyAccessor. 
I need to get singular form of property with name "DataSeries". 
StringUtil::singularify() transfomrs it to "DataSery" but it should be "DataSerie".

Maybe you should do something like doctrine inflector (https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php).

**Comment by thewilkybarkid** [comment]
Series is both singular and plural.

**Comment by TeLiXj** [comment]
Same problem with "Services", singularify transform this word into "Servicious" using the rule for mice-mouse.
This method is really needed in writeProperty method of PropertyAccessor class? If you have a camelized property, why search the singular word? I think this is a source of problems and should be deleted from this class, unless anybody can explain me why use it. Imagine if using other language distinct of English, will be funny...

**Comment by peter-gribanov** [comment]
I also faced the problem of converting word: **series**.

Link from [StringUtil](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/StringUtil.php#L27)

http://ru.scribd.com/doc/27703164/3271143-List-of-100-Irregular-Plural-Nouns-in-English
**Singular -> Plural**
series -> series

Agree with the @TeLiXj, name convert is a very dangerous thing. If you convert the parameter name, then make sure that checks for methods with the original name.

**Comment by peter-gribanov** [comment]
Must also add to the exclusion of the word: **news**
https://ru.scribd.com/doc/11537236/Singular-Plural-Nouns-Notes

**Comment by javiereguiluz** [comment]
Closing it as fixed by #17745.
