### ISSUE TITLE
[Validator] URL validation fails if there is no slash after domain prefix and before query string

### ISSUE THREAD

**Issue by zorji** [symfony/symfony#16536]
There was already a ticket reported and closed https://github.com/symfony/symfony/issues/15891

http://www.anyurl.com/?query=1 - valid URL
http://www.anyurl.com?query=1 - invalid URL (missing slash after .com and before query=1)

The fix fixed URL http://www.anyurl.com? but http://www.anyurl.com?query=1 still reported as invalid

**Comment by zorji** [comment]
Relevant ticket https://github.com/symfony/symfony/issues/15891
Relevant pull request https://github.com/symfony/symfony/pull/16259

**Comment by jakzal** [comment]
@zorji I added a fix with few more test cases in #16537. Feel free to test and review :)

**Comment by zorji** [comment]
@jakzal Thanks for the quick response
