### ISSUE TITLE
make sure that all traits with properties have accessors

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#16548]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1207#issuecomment-156702368

for example `ContainerAwareTrait` should get a `getContainer()` method. ideally 2.7 `ContainerAware` should get such a method as well :-/

**Comment by Tobion** [comment]
Why do you think this is necessary? I cannot extract it from the linked ticket.

**Comment by Tobion** [comment]
Based on https://twitter.com/lsmith/status/665519119853293568 I guess you mean

> I am using ContainerAwareTrait with the core Controller which is what I mean with mess: they cannot be combined which sucks

> 3v4l.org/l1qkE 

But I don't see how making a getter method available in the trait will change anything? As the property is still defined twice.

**Comment by Tobion** [comment]
As I suggested in https://github.com/symfony/symfony/pull/12595#issuecomment-140221735 IMO we should make the framwork controller a trait(s) as well, similar to silex.

**Comment by lsmith77** [comment]
this means that I can build a trait on top of ContainerAwareTrait while still expressing the exact contract .. otherwise I would need to access a property that isn't defined in the trait hoping that the user will know what to do on their own to fulfill the contract:

```
diff --git a/Controller/ContainerAwareControllerTrait.php b/Controller/ContainerAwareControllerTrait.php
index b03ecd2..feacbec 100644
--- a/Controller/ContainerAwareControllerTrait.php
+++ b/Controller/ContainerAwareControllerTrait.php
@@ -12,7 +12,7 @@
 namespace FOS\RestBundle\Controller;
 
 use FOS\RestBundle\View\ViewHandlerInterface;
-use Symfony\Component\DependencyInjection\ContainerAwareTrait;
+use Symfony\Component\DependencyInjection\ContainerInterface;
 
 /**
  * Trait for Controllers using the View functionality of FOSRestBundle.
@@ -22,7 +22,6 @@ use Symfony\Component\DependencyInjection\ContainerAwareTrait;
 trait ContainerAwareControllerTrait
 {
     use ControllerTrait;
-    use ContainerAwareTrait;
 
     /**
      * Get the ViewHandler.
@@ -32,9 +31,16 @@ trait ContainerAwareControllerTrait
     protected function getViewHandler()
     {
         if (!$this->viewhandler instanceof ViewHandlerInterface) {
-            $this->viewhandler = $this->container->get('fos_rest.view_handler');
+            $this->viewhandler = $this->getContainer()->get('fos_rest.view_handler');
         }
 
         return $this->viewhandler;
     }
+
+    /**
+     * Gets the Container associated with this Controller.
+     *
+     * @return ContainerInterface
+     */
+    abstract protected function getContainer();
 }
```

**Comment by nicolas-grekas** [comment]
I agree here: the original rfc for traits gives theoretical basis for methods, but almost none for properties, which are supported in traits just for convenience. At least that's what I recall from it.

**Comment by iltar** [comment]
Regarding this case, I agree with a `getContainer()`. I just don't think that `ContainerAware` is a good thing for your application.

**Comment by lsmith77** [comment]
I am also not a fan of ContainerAware .. in this particular case I am stumbling over this due to the Controller base class BTW

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because I think that in modern controllers we are very far from this ContainerAware thing and accessing the entire container ... but please reopen this if you think my reasoning is wrong. Thanks.
