### ISSUE TITLE
Conditioned constraint which depends on another variable of same object

### ISSUE THREAD

**Issue by ludekbenedik** [symfony/symfony#16543]
Hi,

when I make own Constraint and its Validator I found one problem.
If I need validate some property whose validation depends on another property and this validation is conditioned then I don't have access to the property in Validator because I don't have access to the object.

```php
class User
{
    public $var;
    public $dependentVar;


    public static function loadValidatorMetadata(ClassMetadata $classMetadata)
    {
        $classMetadata->addConstraint(new Assert\Callback('validateDependentVar'));
    }


    public function validateDependentVar(ExecutionContextInterface $context)
    {
        if ('some_condition') {
            $context
                ->getValidator()
                ->inContext($context)
                ->atPath('dependentVar')
                ->validate($this->dependentVar, new MyConstraint())
            ;
        }
    }
}

class MyConstraintValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        // If Constraint is used in callback then $object is NULL!
        $object = $this->context->getObject();
        
        if ($this->someService->isValid($value, $object->var)) {
            return;
        }
        
        $this->context
            ->buildViolation($constraint->message)
            ->addViolation()
        ;
    }
}
```

I found little trick:

```php
if ('some_condition') {
    $context
        ->getValidator()
        ->inContext($context)
        ->atPath('dependentVar')
        ->validate(MyConstraintData($this->dependentVar, $this->var), new MyConstraint())
    ;
}

class MyConstraintValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        if ($value instanceof MyConstraintData) {
            $dependentVarValue = $value->dependentVar;
            $varValue = $value->var;
        } else {
            $dependentVarValue = $value;
            $varValue = $this->context->getObject()->var;
        }
        
        if ($this->someService->isValid($dependentVarValue, $varValue)) {
            return;
        }
        
        $this->context
            ->buildViolation($constraint->message)
            ->addViolation()
        ;
    }
}
```

It's only example of my two more complicated constraints where I need to do this trick.

This problem can be solved by two different approaches:

 1. Add optionally `$constraints` parameter to `ValidatorInterface::validateProperty()` method.
    `validateProperty($object, $propertyName, $groups = null, $constraints = null)`
    If the `$constraints` is not NULL then the `$constraints` are used instead of property constraints.
 
 2. Do little trick like in example. So we can add common `ConstraintData` to unify solving of this problem. Something like:

```php
class ConstraintData
{
    public function __construct($value, array $parameters) {}
    
    public function getValue() {}
    
    public function getParameter($name) {}
}
```

Unfortunately Symfony 3 has lock adding of new features then only second approach is allowed I think.
Maybe this is very edge problem and everybody can solve this by own way.
I found this problem in two different cases and I never use these methods `ValidatorInterface::validateProperty()` and `ValidatorInterface::validatePropertyValue()` so
this feature is more important for me than these two methods ;)

**Comment by dmaicher** [comment]
Can't you not simply put the constraint on the `User` (as a class constraint)? Then you have access to the User instance and can validate the dependant properties easily.

**Comment by javiereguiluz** [comment]
@ludekbenedik did @dmaicher's comment solve your issue?

**Comment by webmozart** [comment]
I agree that this is most probably a usage problem. If you tell us more details about your actual use case we can maybe help you better. I don't think there's anything that needs to be changed in the framework here.

**Comment by xabbuh** [comment]
Closing here as this seems to be a usage problem.

@ludekbenedik Please let us know if you disagree so we can consider to reopen here.
