### ISSUE TITLE
Doctrine DQL with UTF-8 column names

### ISSUE THREAD

**Issue by damiengenthial** [symfony/symfony#16544]
I use Symfony 2.7 and Doctrine2 and I tried this DQL query:

    SELECT R.libellé 
    FROM IutFranceBundle:Regions R

and I got an error:

    [Syntax Error] line 0, col 15: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got '�'

I dug a little in doctrine code and found that regular expressions in Lexer cannot support UTF-8 characters. So I patched (only) 2 files:

    vendor/doctrine/lexer/lib/Doctrine/Common/Lexer/AbstractLexer.php
    vendor/doctrine/orm/lib/Doctrine/ORM/Query/Lexer.php

In the first I simply add the `'u'` modifier in method `getModifiers`, and then in the last I change the method `getCatchablePatterns`, replacing `a-z_` by `\w` (which stands for any letter or `_`).

I think the last patch can also be applied safely to the method `getCatchablePatterns` of :

    vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocLexer.php

It works now fine. Should it be possible to apply this patch to symfony/doctrine for future release ?

**Comment by Tobion** [comment]
This is about doctrine (https://github.com/doctrine/doctrine2) not symfony. Please open the issue at the corresponding project.
