### ISSUE TITLE
BinaryFileResponse incorrect behavior with If-range header

### ISSUE THREAD

**Issue by asmarovydlo** [symfony/symfony#16540]
According to w3c specification http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html,
in the request, If-range header can contains last modified date of file, but in BinaryFileResponse(symfony v2.6.8) only  etag accepted. 
As in current realization etag generating by  sha1_file function in takes much time with big files.

**Comment by bburnichon** [comment]
This bug is present in all current supported versions. i.e. 2.3, (2.6 whose support just ended), 2.7, 2.8, 3.0 & 3.1-dev
