### ISSUE TITLE
Again is_granted in twig on 404 error page in prod environment

### ISSUE THREAD

**Issue by wiistriker** [symfony/symfony#16542]
Doc says: "to avoid broken error pages in the prod environment, wrap calls in these templates with a check for app.user"

But checking app.user isn't what we really need.

```twig
{% if app.user and is_granted('IS_AUTHENTICATED_REMEMBERED') %}
  Hello, {{ app.user }}!
{% else %}
  Please login
{% endif %}
```

In prod env, if ResourceNotFoundException was throwed from appProdUrlMatcher (no route was matched at all), even authenticated user will see "Please login". Checking app.security.token in previous versions of sf2 handle this case, but now app.security is deprecated.

I found two way to solve this issue:
1) create catch-all route which will throw $this->createNotFoundException();
2) remove all is_granted checks from error templates.

Maybe you can provide me with more robust solution?

**Comment by stof** [comment]
@wiistriker checking ``app.security.token`` for the errors happening in the router is does not work, because the router runs before the firewall, and so you are never authenticated in such cases.
I don't see how checking ``app.security.token`` can solve your issue

**Comment by jakzal** [comment]
@wiistriker any feedback to stof's comment?

**Comment by wiistriker** [comment]
@stof i dont want to authenticate user, i just want to know in my template when we cant use "is_granted". Checking app.security.token in that case can help.

{% if app.security.token %} {# we are in firewall now #}
    {% if is_granted(..) %}Hello{% else %}Please login{% endif %}
{% else %}
{# we are not in firewall now and probably ResourceNotFoundException was thrown from url matcher #}    
{% endif %}

In that case user doesnt see any user-related blocks at all. Which is better (in my opinion) then showing "Please login"

**Comment by javiereguiluz** [comment]
Closing it as fixed because @wiistriker himself explained that he can use `app.security.token` to achieve his goal. Besides, the `if app.user` check is optional starting with Symfony 2.8, so there is no need to perform additional checks to prevent exceptions.
