### ISSUE TITLE
Why can't (shouldn't) primitive types be passed to AuthorizationChecker::isGranted

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#16554]
Naming the second Argument of `AuthorizationChecker::isGranted`, `"$object"`, implies that it should always be an object. Now this in itself imposes no hard restrictions, but the Implementation of [`AbstractVoter`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L61) in the 2.7 branch will cause errors, if a primitive is passed to the voter. Can this be fixed or is there a reason to it?

**Comment by GromNaN** [comment]
The PHPDoc if the method [`VoterInterface::vote`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authorization/Voter/VoterInterface.php#L57) specify that the `$object` parameter must be an object. 

Fixing the interface would be a problematic BC break for custom implementations.

**Comment by nicolas-grekas** [comment]
You should use `Voter` now instead of `AbstractVoter`
See #16601
