### ISSUE TITLE
[Security] AbstractVoter should not abstain when object == null

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#16556]
I was migrating our voters to use the `AbstractVoter` and I notice something strange.
In [2.7](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L61-L63) and in [2.8](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L65-L67), if nothing is passed for the `object` argument, the voter votes `ACCESS_ABSTAIN`. 

IMHO, this is wrong. For example, If a voter votes for `POST_CREATE`, I may have no `$object` parameters. and so the abstract voter should let the voter decide.

What do you think?

ping @Inoryy @weaverryan @WouterJ @Koc

**Comment by Koc** [comment]
I agree with you, but this logic was added when this voter was created https://github.com/symfony/symfony/commit/d3bafc6b48dd7c5112ef3d9baa54bd0795f5e0bc#diff-c46e9d9da2a0b7aa68e78b8e58369481R61 and changing behavior can be a BC-break.

**Comment by lyrixx** [comment]
@Koc Yes, I saw this diff. But I don't understand why. And this Logic prevent me to use the `AbstractVoter` so for me it's a bug.

**Comment by Inoryy** [comment]
@lyrixx your use case makes sense and in fact when I looked up the original PR, I've found that somebody has already encountered this issue [here](https://github.com/symfony/symfony/pull/11183/files#r21591562), I'm not sure if any action was taken though /cc @weaverryan

**Comment by weaverryan** [comment]
@lyrixx it was an oversight in the original AbstractVoter. So yes, it's a bug, but it needs to be fixed while keeping BC. I think there's another issue about this, where I suggested renaming this to AbstractObjectVoter and creating some other new abstract class with the desired functionality. So I think it's valid - someone should work on it for a future release.
