### ISSUE TITLE
[Form][3.0] Injecting parameters into form without type constructor

### ISSUE THREAD

**Issue by hiddewie** [symfony/symfony#16559]
Starting with 3.0, form types as objects are not supported anymore. Now we need to use the FQCN to use a form type. This is no problem, except when I need to inject extra data into my form type instance to use when adding form elements. 

How to do this in the new Symfony 3.0 way?

Before:

```php
class LinkType extends AbstractType {
	public function __construct ($choices) {
		$this->choices = $choices;
	}

    public function buildForm(FormBuilderInterface $builder, array $options) {
        // Add stuff to form
        // Use $this -> choices
    }

    public function configureOptions(OptionsResolver $resolver) {
        // Configuration
    }
}

// ...

$this -> createForm(new LinkType($choices), $data, $options);
```

After:
```php
class LinkType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        // Add stuff to form
        // Where do I get the choices?
    }

    public function configureOptions(OptionsResolver $resolver) {
        // Configuration
    }
}

//...

$this -> createForm(LinkType::class, $data, $options);
```

**Comment by Tobion** [comment]
Just as before. Define the form type as service and reference it as FQCN. It's just the naming that changed, not the way to do things.

**Comment by stof** [comment]
Register the form type in the form registry before using it (which is already how it *should* be done in previous versions as passing an instance can lead to weird things if the type is used at least twice).

When using the fullstack framework, the best way to register it is indeed through the DIC integration.

**Comment by hiddewie** [comment]
OK, thank you. I will look into injecting the required data into the form using DIC.

**Comment by stof** [comment]
@hiddewie the other possibility is that you should pass the needed data through the options of the form.
the way to know what is the right way to do it is to think about what would happen if the form type was used twice: would the choices be the same or no ? If yes, this goes in the constructor. If no, it should be an option.
A good example is the ``entity`` type: the Doctrine ManagerRegistry is a constructor argument, as it is a dependency of the form type itself. On the other hand, the query builder is an option of the form, as it changes each time you configure it.
