### ISSUE TITLE
[HttpKernel] Do we really need the log folder?

### ISSUE THREAD

**Issue by goetas** [symfony/symfony#16572]
on: 
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/Kernel.php#L588 (v2.8)
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L554 (master)

is explicitly requested to have the logs dir as writable, but if the while system is using monolog and the while logging system relies on it, why enforce this constraint?

As extra, the log dir can not be controlled via parameters.yml... this requires explicit code.

IMO, the only directory that should be required as "writable" is the cache dir.

**Comment by stof** [comment]
given that the log dir is only used by MonologBundle, we could indeed get rid of the log dir in the kernel. This architecture is mostly a reminder of early Symfony code before MonologBundle was there IMO.

**Comment by goetas** [comment]
Any chance to see it removed in 2.8 branch? (at least skipping the check and the exception....)

**Comment by Tobion** [comment]
@stof Aren't there also logs when building the container which might go there?

**Comment by stof** [comment]
no, they are stored alongside the dumped container, not in the logs dir

**Comment by iltar** [comment]
I can confirm that the only things put in the log directory, are the ones (if configured) from the monolog bundle configuration.

**Comment by TomasVotruba** [comment]
Ok, what needs to be done here?

**Comment by dosten** [comment]
@TomasVotruba there's an open PR here #16583

**Comment by fabpot** [comment]
I don't think this is something we need to fix, see my comment on #19063

**Comment by nicolas-grekas** [comment]
> If someone does not want the log dir, they can just point it to something under the cache dir, and be done with it. As the use case is really rare, I don't think we need to do anything in Symfony.

**Comment by stof** [comment]
I think that in 4.0, we can remove this from the kernel though, letting it be handled through the MonologBundle configuration

**Comment by goetas** [comment]
Can we re consider this? Or just re open it to not loose track of it again... Since @stof proposed to include it in 4.0.. But 5.0 is already out
