### ISSUE TITLE
[WebProfilerBundle] [2.8-BETA1] Timeline doesn't work on Firefox

### ISSUE THREAD

**Issue by hhamon** [symfony/symfony#16571]
It seems the timeline panel only works on Chrome but not on Firefox anymore (see screenshots) below:

![Chrome](https://cloud.githubusercontent.com/assets/235550/11209574/3e817ba6-8d22-11e5-8c3b-ba3bf005ca1e.png)
![Firefox](https://cloud.githubusercontent.com/assets/235550/11209576/43074430-8d22-11e5-88ed-6e4b575ddce8.png)

My Chrome version: 46.0.2490.86 (64-bit)
My Firefox version: 42.0

People at my training also experience the same issue.

**Comment by javiereguiluz** [comment]
I cannot reproduce on my Firefox 42 version (on Mac OS X):

![profiler_timeline_firefox](https://cloud.githubusercontent.com/assets/73419/11209639/b1719b46-8d22-11e5-818e-c8933ed6605e.png)

**Comment by hhamon** [comment]
hum strange!

**Comment by hhamon** [comment]
I forced to reinstall assets, refreshed the page and it worked... I can't explain why it bugged on Firefox the first time and not on Chrome.
