### ISSUE TITLE
Twig_Error_Runtime: Unable to generate a URL for the named route "_assetic_e65500c_0" as such route does not exist.

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#16579]
That's my layout.html.twig:

    {% extends '::base.html.twig' %}

    {% block stylesheets %}
        {{ parent() }}
        {% stylesheets 'css/src.mystyle.css' filter='?uglifycss' output='/assets/css/dist.*.css' %}
            <link rel="stylesheet" href="{{ asset_url }}" />
        {% endstylesheets %}
    {% endblock %}

It's works fine until I type in ```{% set currentRoute = app.request.attributes.get('_route') %}```.

    {% extends '::base.html.twig' %}

    {% set currentRoute = app.request.attributes.get('_route') %}
    
    {% block stylesheets %}
        {{ parent() }}
        {% stylesheets 'css/src.mystyle.css' filter='?uglifycss' output='/assets/css/dist.*.css' %}
            <link rel="stylesheet" href="{{ asset_url }}" />
        {% endstylesheets %}
    {% endblock %}

I got this exception:

    An exception has been thrown during the rendering of a template ("Unable to generate a URL for
    the named route "_assetic_e65500c_0" as such route does not exist.") 
    in AppBundle::layout.html.twig at line 7.

This error occurs only once and it was fixed after refresh the page.

Symfony 2.7.6 . Development environment.

Sorry for my bad english.

**Comment by iltar** [comment]
I had that exact same issue yesterday. After clearing the cache it seemed to be fixed though. I haven't been able to reproduce it.

**Comment by zacharyzh** [comment]
I move the line ```{% set currentRoute = app.request.attributes.get('_route') %}``` to the following of stylesheets block, the error was disappears, but when I move it to above of the stylesheets block and try to reproduce error, nothing happened.

**Comment by jakzal** [comment]
@zacharyzh what do you mean by "nothing happened"?

**Comment by zacharyzh** [comment]
@jakzal 

This issue can not be reproduced. It's disappeared after page refreshing.

**Comment by jakzal** [comment]
@zacharyzh cool, must've been caching issue then. Closing.

**Comment by zacharyzh** [comment]
@jakzal 

I just hope it will not happen in a production environment.

**Comment by stof** [comment]
@zacharyzh in prod, you should never run the assetic controller anyway, so it will not generate such routes

**Comment by zacharyzh** [comment]
OCD is so bad 😢
