### ISSUE TITLE
SymfonyStyle: Progress Bar Styling Logic Reversed ?

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#16577]
The `SymfonyStyle::createProgressBar()` currently looks like this:

```php
    public function createProgressBar($max = 0)
    {
        $progressBar = parent::createProgressBar($max);
        if ('\\' === DIRECTORY_SEPARATOR) {
            $progressBar->setEmptyBarCharacter('░'); // light shade character \u2591
            $progressBar->setProgressCharacter('');
            $progressBar->setBarCharacter('▓'); // dark shade character \u2593
        }
        return $progressBar;
    }
```

The `\\` is a check to see if we're in Windows. So, these styles are *only* shown in Windows. Is that backwards?

Ping @kbond I think this line originally came from your commit - maybe you remember what the issue was.

Thanks!

**Comment by kbond** [comment]
Right you are! Found this comment: https://github.com/symfony/symfony/pull/14057#discussion_r27306231 - looks like I copied the fix wrong.
