### ISSUE TITLE
[Form] NumberFormatter with scale null

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#16575]
As I understand it should is possible to use `null` as value for the `scale` option to avoid any rounding. However if you set scale to null an issue arises with the Intl NumberFormatter.

In

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php#L235

the precision wont be defined, but the issue is that the number will still be rounded according to the default regional settings due to NumberFormatter::MAX_FRACTION_DIGITS is set to 3 by default in my case.

Is there any option to work around that as I want to display the number as it has been entered. I have implemented custom validation to check a custom max scale.

**Comment by peterrehm** [comment]
Does anyone have any idea about that?

**Comment by xabbuh** [comment]
That's a misunderstanding IMO. If you do not want to have any rounding, you need to pass `0` explicitly (like done by the `IntegerToLocalizedStringTransformer`). Closing here as I do not think there is a bug.

**Comment by peterrehm** [comment]
But won‘t that round to a full integer?

**Comment by xabbuh** [comment]
You will have to define how the decimal value will be rounded. For example, `ROUND_DOWN` would just strip all decimals. I am not sure what use case you need to solve, but there are several rounding modes defined in the `NumberFormatter` class so you should be able to solve that.

But of course, if you still think there is an issue, please leave a comment with some more details and I will happily look at it.
