### ISSUE TITLE
[DebugBundle] findFile() from WebProfilerServiceProvider in Silex

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#16576]
When registering WebProfilerService in a Silex app you can find : 

    $app['profiler.templates_path.debug'] = function () {
        foreach (spl_autoload_functions() as $autoloader) {
            if (!is_array($autoloader) || !method_exists($autoloader[0], 'findFile')) {
                continue;
                }

                if ($file = $autoloader[0]->findFile('Symfony\Bundle\DebugBundle\DebugBundle')) {
                    return dirname($file).'/Resources/views'; // never returns
                }
            }
    };

with allows catching `dump($var)` and display it in the web debug toolbar.

But `return dirname($file).'/Resources/views';` is never reached because in `DebugClassLoader` in `symphony-debug-bundle` : 

    public function findFile($class)
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 2.5 and will be removed in 3.0.', E_USER_DEPRECATED);

        if ($this->wasFinder) {
            return $this->classLoader[0]->findFile($class);
        }
    }

`$this->wasFinder` is never `true`.

The solution I found is to change it to `$this->isFinder`

Is this right ?

**Comment by stof** [comment]
The right fix would be to change the way the WebProfilerServiceProvider.

**Comment by HeahDude** [comment]
Ok, it's because of debug mode enabled with `Debug::enable()` in my front controller.

I've found a fix : 

    $app['profiler.templates_path.debug'] = function () {
        foreach (spl_autoload_functions() as $autoloader) {
            if (!is_array($autoloader) || !method_exists($autoloader[0], 'findFile')) {
                continue;
                }

                //-> Start fix
                if ($autoloader[0] instanceof DebugClassLoader) {
                    foreach ($autoloader[0]->getClassLoader() as $loader) {
                        if (null !== $file = $loader->findFile('Symfony\Bundle\DebugBundle\DebugBundle')) {

                            return dirname($file).'/Resources/views';
                        }
                    };
                }
                //-> End fix

                if ($file = $autoloader[0]->findFile('Symfony\Bundle\DebugBundle\DebugBundle')) {
                    return dirname($file).'/Resources/views'; // never returns
                }
            }
    };

**Comment by HeahDude** [comment]
Closing as it's the wrong place for reporting and I could not reproduce this issue on a clean install
