### ISSUE TITLE
determine if process is running by pid

### ISSUE THREAD

**Issue by craftpip** [symfony/symfony#16589]
Hello, I'm using the process component, its awesome so far. 
The problem is, i start a process, and later in the future i want to determine if its running or not.

I tried to serialize the `$process`, but didn't work because of closures.
There there a perfect solution to this?

Thanks.

**Comment by ewgRa** [comment]
Did you check Process::getPid() ? 

Also better to ask such questions at http://stackoverflow.com/questions/tagged/symfony

**Comment by craftpip** [comment]
Got the pid from getPid(), however is there is better way to do it.

i will post the question on Stackoverflow. 
Thanks
