### ISSUE TITLE
Symfony 3 seems to be a bit slower than Symfony 2.8

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#16586]
I've compared some pages of the Symfony Demo app for both 2.8-dev and 3.0-dev. (I tested both apps separately, cleaning the caches, restarting the web server before each test, etc.) Results:

### Blog Index Page

  * URL: `/en/blog/`
  * Profile comparison: https://blackfire.io/profiles/compare/dac9474e-135a-43c4-9d3a-21418e15d270/graph
  * Symfony 3 is a bit faster (negligible):

![blog_index](https://cloud.githubusercontent.com/assets/73419/11237840/5b7318ee-8de2-11e5-9d77-6093414f73fa.png)

### Blog Post Page

  * URL: `/en/blog/posts/in-hac-habitasse-platea-dictumst`
  * Profile comparison: https://blackfire.io/profiles/compare/64392163-63eb-41f1-b8d0-1da356fdc8d8/graph
  * Symfony 3 is way slower:

![blog_post](https://cloud.githubusercontent.com/assets/73419/11237864/7ab8520a-8de2-11e5-8d3d-434d644789cf.png)

### Admin Index Page

  * URL: `/en/admin/post/`
  * Profile comparison: https://blackfire.io/profiles/compare/4caa5175-f964-445e-ba49-ef083fe5334f/graph
  * Symfony 3 is a bit slower (negligible):

![admin_index](https://cloud.githubusercontent.com/assets/73419/11237877/91599eec-8de2-11e5-8984-ee5bb988b8f5.png)

-----

These results are shocking to me because Symfony 3 removed thousands of lines of code and BC layers. I expected it to be a bit faster than 2.8 in most cases. Thoughts?

**Comment by stof** [comment]
The place being a lot slower seems to be related to making much more json_decode call in the Intl component. This looks weird to me, as the data are the same.

**Comment by ogizanagi** [comment]
@javiereguiluz : I also tried a comparison: https://blackfire.io/profiles/compare/787a8116-7948-4409-805a-8dea977adeca/graph
<img width="764" alt="screenshot 2015-11-19 a 19 40 50" src="https://cloud.githubusercontent.com/assets/2211145/11280265/7e184630-8ef5-11e5-974c-80e089d232dc.PNG">

Not sure why you get those results, but it seems pretty normal in those profiles.

**Comment by javiereguiluz** [comment]
Looking at @ogizanagi reuslts, I'm closing this issue as "unconfirmed". I'll keep profiling 2.8/3.0 applications to look for performance differences. Thanks!
