### ISSUE TITLE
"Cannot set session ID after the session has started" when generating csrf token within Behat test

### ISSUE THREAD

**Issue by toby-griffiths** [symfony/symfony#16594]
I'm trying to test that a user with the wrong permissions sees the correct response when visting a page that has a csrf token in the path.

I've added a Behat context step to create a csrf token using the 'security.csrf.token_manager', however then visit the page with this token in the path, I get a "Cannot set session ID after the session has started" 500 error.

Can anyone advise what I'm doing wrong, or how I work around this, please?

```
    /**
     * @When /^I go to the application admin archive page for "(?P<status>[^"]*)" application (?P<number>\d+) with a valid token$/
     *
     * @param string $status
     * @param int    $number
     */
    public function iGoToTheApplicationAdminArchivePageForApplicationWithAValidToken($status, $number)
    {
        $tokenManager = $this->kernel->getContainer()->get('security.csrf.token_manager');
        $token        = $tokenManager->getToken(ApplicationAdminController::CSRF_ARCHIVE);
        var_dump($token);

        $this->visitAdminPage('archive', $status, $number, ['token' => $token]);
    }
```

**Comment by Tobion** [comment]
Duplicate of #13450

**Comment by toby-griffiths** [comment]
Thanks for the info :+1:
