### ISSUE TITLE
How do I get access to the OutputInterface whilst adding commands?

### ISSUE THREAD

**Issue by rquadling** [symfony/symfony#16591]
Hi.

Not sure of the best approach for what I'm trying to do so some guidance would be appreciated.

I've got a set of commands (about 40, grouped by different namespaces). We are building this as a composer installable package for our developers (rather than having them in the main repo, these are outside of the application, but provide a set of dev related utilities for our applications).

Before adding the commands, I want to verify the existence of an appropriate .env file.

Easily done. But if it is missing, I would like to output an appropriate message using ``writeln()`` as this has ANSI colour support.

From this issue, I have a couple of questions.

1 - Should I be ``add()``-ing the commands in my application's constructor()?
2 - Is the ``$output`` accessible statically?

Pseudo code wise I'm doing something like this ...

``bin/dt_utils`` contains the instantiation script for our utility package.
``src/DTUtils.php`` main application class.
``DTUtils::__construct($name, $version)`` contains the checker for the .env file as well as the ``add()`` calls for the commands.

**Comment by xabbuh** [comment]
Please ask support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/symfony).

**Comment by rquadling** [comment]
Ha! Well. Yeah.
