### ISSUE TITLE
[3.0] Bump minimum PHP version to 5.6

### ISSUE THREAD

**Issue by colinodell** [symfony/symfony#16593]
Symfony 3 currently requires PHP 5.5.9 or higher.  However, [official support for 5.5 ended 4 months ago](https://secure.php.net/supported-versions.php), and security fixes will no longer be added after July 2016.

From what I can tell, [the 5.5.9 requirement was chosen](https://github.com/symfony/symfony/pull/12522) because it's the minimum version available for Ubuntu 14.04 LTS.  While I do understand that supporting these LTS users is important, I wonder whether that outweighs the fact that Symfony is explicitly supporting a now-unsupported version of PHP, especially when [upgrading to PHP 5.6 isn't too difficult](https://www.google.com/search?q=ubuntu+14.04+php+5.6).

I'm therefore curious what your thoughts would be on dropping support for 5.5 and requiring 5.6+ instead.

**Pros for bumping min version to 5.6:**

* Symfony's PHP support will align with the currently-supported PHP versions
  * No need to support 5.5 throughout the entire lifetime of Symfony 3
  * Encourages the community to upgrade to a modern PHP version
* PHP 5.5 / Ubuntu 14.04 users can still upgrade to Symfony 2.8 and use the latest features

**Cons:**

* Anyone not willing/able to upgrade from 5.5 to 5.6 will be stuck on Symfony 3.x
* This decision may affect other projects relying on components from 3.0

**I'm not strongly against 5.5 support - I just wanted to see how others feel about this.**

Perhaps it would be okay to drop 5.5 support if (for whatever reason) Symfony 3.0.0 is released after Ubuntu 16.04 LTS (assuming it ships with PHP 5.6 or 7.0)?

**Comment by fabpot** [comment]
This topic has already been discussed and we decided to support PHP 5.5.9. Symfony 3 is going to be released in two weeks for now, so not something we will change now.

**Comment by colinodell** [comment]
Understood, thanks!
