### ISSUE TITLE
[Process] Get Exception object in case Process errors

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#16602]
Is it possible to get a real `Exception` object in case a `Process` errors (e.g. is running into a `ErrorException`)?

I would like to handle the `Exception` from callsite, but atm I am only getting a string (exception-message+trace) from stdout

**Comment by stof** [comment]
I don't understand what you mean by saying ``a process is running into a ErrorException`` ?

do you mean that you run a php command in a sub-process and would like to get the Exception object of the sub-process into the main process ? This is impossible due to the nature of processes

**Comment by staabm** [comment]
> do you mean that you run a php command in a sub-process and would like to get the Exception object of the sub-process into the main process ?

exactly. I have a subprocess which runs a PHP skript and runs into a error and I would like to handle the Exception in the mainprocess. I guess I need some IPC magic to do that, but hoped that the Process component would also bring such things with it natively

**Comment by stof** [comment]
@staabm what you can do is serialize the exception in the subprocess, output it, and the deserialize the output in the main process (but this assumes that your exception is serializable, which is not always the case, and that your main process has access to all classes available in the subprocess too).

This is something you would build around the Process component, but the Process component won't handle it (as it also requires altering the script being run to handle errors there, and this would make the process component more specific than it is as it currently run any subprocess, whatever language is used to implement it).
