### ISSUE TITLE
missing: yaml:dump() option to export multi-line strings as string literal

### ISSUE THREAD

**Issue by schorsch3000** [symfony/symfony#16604]
Hi,
i Need to dump datastructures as Yaml, having multiline-strings as String-literals.
yaml::parse is able to read string in this format, mit you can't dump it.

So for now i have hacked  the dumper to do what i need, but that's not nice.
I would happily  implement that correct, write tests and documentation and send a pull-request, but i would like to here if that is something you would like to see in your code.
Also we should talk about how to trigger that behavior. Should i just add another Parameter $useStringLiteral = false ?

Greetings Schorsch

**Comment by fonsecas72** [comment]
Hi there, can you please provide some samples of the current and expected behaviour? 
I think it would ease things :)
:bee:

**Comment by schorsch3000** [comment]
Sure.
Maybe i should explain my needs before:
i have config-files which are written by people and by a script. These configfiles are in YAML, have mostly small values, like numbers, booleans or pathes, but also multiline-text.
So a human would write something like this:
````
boolean: true
number: 42
path: /dev/null
name: John Doe
loremIpsum: |
  Lorem ipsum dolor sit amet,
  consetetur sadipscing elitr,
  sed diam nonumy eirmod tempor
  invidunt ut labore et dolore
  magna aliquyam erat, sed
  diam voluptua. At vero eos
  et accusam et justo duo
  dolores et ea rebum.
  Stet clita kasd gubergren,
  no sea takimata sanctus
  est Lorem ipsum dolor
  sit amet.
````

Which is valid YAML, and YAML::parse() is fine to parse.

So maybe my script needs to increase the number in this configurationfile.
````
<?php
include 'vendor/autoload.php';
$config=Symfony\Component\Yaml\Yaml::parse(file_get_contents('test.yaml'));
$config['number']++;
echo \Symfony\Component\Yaml\Yaml::dump($config);
````

which will result in:
````
boolean: true
number: 43
path: /dev/null
name: 'John Doe'
loremIpsum: "Lorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,\nsed diam nonumy eirmod tempor\ninvidunt ut labore et dolore\nmagna aliquyam erat, sed\ndiam voluptua. At vero eos\net accusam et justo duo\ndolores et ea rebum.\nStet clita kasd gubergren,\nno sea takimata sanctus\nest Lorem ipsum dolor\nsit amet."
````

Which is totally fine and valid YAML, but quite annoying to edit by hand.
 
Also what's up with your bee? :)

**Comment by sstok** [comment]
:+1: Yes please!
