### ISSUE TITLE
BinaryFileResponse attachment doesn't work with non-ascii filenames

### ISSUE THREAD

**Issue by Yannik** [symfony/symfony#16603]
Hi everyone,

at the moment, it is impossible to create a BinaryFileResponse with a file which has a non-ascii filename:
```
<?php
function test_can_create_utf8_file_attachment_response() {
    touch('Täst');
    new Symfony\Component\HttpFoundation\BinaryFileResponse('Täst', 200, [], true, 'attachment');
}
```

This results in a ```InvalidArgumentException``` with message ```'The filename fallback must only contain ASCII characters.'```

The stacktrace for the exception is:
```
#0 symfony\http-foundation\BinaryFileResponse.php(161): Symfony\Component\HttpFoundation\ResponseHeaderBag->makeDisposition('attachment', 'T\xC3\xA4st', '')
#1 symfony\http-foundation\BinaryFileResponse.php(110): Symfony\Component\HttpFoundation\BinaryFileResponse->setContentDisposition('attachment')
#2 symfony\http-foundation\BinaryFileResponse.php(50): Symfony\Component\HttpFoundation\BinaryFileResponse->setFile('T\xC3\xA4st', 'attachment', false, true)
#3 test.php(3) : Symfony\Component\HttpFoundation\BinaryFileResponse->__construct('T\xC3\xA4st', 200, Array, true, 'attachment')
```` 

However, it is not possible to instantiate a BinaryFileResponse and pass a filename fallback.
In fact, when `setContentDisposition` is called without a fallback filename (as is done by `setFile`), according to the DocBlock:
```
     * @param string $filenameFallback A fallback filename, containing only ASCII characters. Defaults to an automatically encoded filename
```
the fallback filename should default to a automatically created ascii version. 
However, this does not happen:

```
    public function  setContentDisposition($disposition, $filename = '', $filenameFallback = '')
    {
        if ($filename === '') {
            $filename = $this->file->getFilename();
        }

        $dispositionHeader = $this->headers->makeDisposition($disposition, $filename, $filenameFallback);
    }
```

`$filenameFallback` is just left to be a empty string.
`makeDisposition` then sets the fallback filename to the (possibly utf8) filename gotten though `getFilename()`:

```
        if ('' == $filenameFallback) {
            $filenameFallback = $filename;
        }
```

which then causes the exception.

Possible solutions:
  1. Let `setContentDisposition` act as it's docblock describes and set the fallback filename to an automatically encoded version of the filename if no other fallback filename is given
  2. Pass filename and fallback filename in the constructur and change the docblock of `setContentDisposition`
  3. both

**Comment by xabbuh** [comment]
Status: Confirmed

see #16656

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by Yannik** [comment]
Thanks a lot for addressing this, @xabbuh! I [commented](https://github.com/symfony/symfony/pull/16656#issuecomment-159443270) on your pull request about maybe replacing the non-ascii chars with their nearest ascii equivalent instead of just replacing them with an underscore. I would be very grateful if you could consider this. Thanks, Yannik

**Comment by nicolas-grekas** [comment]
This is [RFC 2231](https://tools.ietf.org/html/rfc2231)
See also this old "paper" on the topic: http://greenbytes.de/tech/tc2231/
Doing transliterations works for western languages but is quite limited in the general case...

**Comment by JHGitty** [comment]
+1
Had the issue today. We really need this.
