### ISSUE TITLE
Form extensions are not correctly resolved for Entity type, when a field is readded

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#16616]
I'm using the following code to generate a `Form` ;

``` php
$b = $this->ff->createBuilder('form');
$b->add('field', 'text');
$b->add('test', 'entity', array('class' => MrpMaterial::class, 'depended_on_by' => 'field'));
$form = $b->getForm();
```

the `'depended_on_by'` option is a custom option, added by my own extension. now if I try add the Form Again using the following code, I get a 

> 'depended_on_by' option does not exist

 error, this didn't happen on Symfony 2.5, I'm currently on `2.7.7`:

``` php
$test = $form['test'];
$form->add('test', $test->getConfig()->getType()->getInnerType(), $test->getConfig()->getOptions());
```

The mentioned type extension extends the `entity` type, but if it extends `form`, this error won't occur, I have checked that `getInnerType()` in fact returns a `Symfony\Bridge\Doctrine\Form\Type\EntityType` Object, so what could be the problem here?

**Comment by Tobion** [comment]
Please try to use `$form->add('test', $test->getConfig()->getType()->getInnerType()->getName(), $test->getConfig()->getOptions());` and see if that helps. See https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/FormFactory.php#L187

**Comment by thedamnedrhino** [comment]
This would work for the entity type, but the extension adding and removing these form fields does this to all kind of fields, and it wouldn't work for fields not registered as a form type. So I would like to know if this is expected behaviour or a bug, since it didn't happen in the former version.

**Comment by thedamnedrhino** [comment]
I just read the code you linked. Is this a limitation or is there a philosophy behind it?

**Comment by Tobion** [comment]
I guess the commit history and related PRs might explain this limitation.

**Comment by Ymox** [comment]
Sorry to get back at this, I stumbled over a similar problem and came up here.

Apparently the link to line 187 could be no longer relevant, as the file was last modified on 2nd December 2015, and I observe the same behaviour currently with Symfony 3.0.

OP created the form "from scratch", I have a FormType in which I want to use the EntityType and the extension I made. It appears when I launch `debug.container`, but it is never even built, and of course options I placed along my EntityType fields that are defined in my extension are not recognized.  
I'm unsure the workaround proposed would work, and I don't know I could apply it in a form class.

Is there another workaround I can use until there is _the_ solution?

**Comment by xabbuh** [comment]
@thedamnedrhino I am not sure I understand the issue. Can you provide a small example project to make it reproducable? Or should we close here as the report is no longer valid?

**Comment by thedamnedrhino** [comment]
@xabbuh I think the issue might be solved in 3.x. I will report back once I confirm that.

**Comment by thedamnedrhino** [comment]
@xabbuh this is actually irrelevant in 3.x because passing form type __instances__ to `FormBuilder|Form->add()` is deprecated.

**Comment by xabbuh** [comment]
Thanks, closing then.
