### ISSUE TITLE
Install online missing text

### ISSUE THREAD

**Issue by Saphyel** [symfony/symfony#16617]
When you are doing the installation online (of the doctrine parameters) in this URL: app_dev.php/_configurator/step/0 in the form shows the label "h"  instead the label "Path"

**Comment by Tobion** [comment]
Please clarify your report. It's not understandable.

**Comment by Saphyel** [comment]
@Tobion updated

**Comment by Tobion** [comment]
The configurator comes from https://github.com/sensiolabs/SensioDistributionBundle so should be reported there. But the configurator is removed in the new versions anyway. So it's obsolete.

**Comment by javiereguiluz** [comment]
@Saphyel you are probably reading a very old tutorial or article because we removed the online Symfony configurator a while ago and we never promoted it. Did you read that information on symfony.com website?
