### ISSUE TITLE
Debug toolbar not visible in 2.8 ?

### ISSUE THREAD

**Issue by SoboLAN** [symfony/symfony#16613]
I decided to give Symfony 2.8 a little try. So, on a small application that I have, I upgraded it's `symfony/`symfony` dependency to `2.8.*@dev`.

Everything seems to be working surprinsingly well (except for the multitude of deprecation notices, but I expected those :D ).

However, I noticed that the debug toolbar is not visible in the profiler. And this is despite the fact that my `config_dev.yml` file contains this:

```yml
web_profiler:
    toolbar: true
    position: bottom
    intercept_redirects: false
```

This is really strange because I know for sure that the toolbar was always visible in the profiler when the application relied on 2.7. When I changed the symfony version in `composer.json`, I made no changes whatsoever to the configuration files.

Other stuff I've tried:

- accessing the profiler using other browsers
- clearing the cache
- making fresh requests
- checking that configuration names are still OK and weren't changed (using this page: http://symfony.com/doc/master/reference/configuration/web_profiler.html )

What am I missing ?

**Comment by weaverryan** [comment]
Does the web debug toolbar get injected into your HTML page? If so, does the AJAX request fire? Does it 500? If you go to `/_profiler`, do you see the entries listed there for recent pages?

Cheers!

**Comment by SoboLAN** [comment]
> Does the web debug toolbar get injected into your HTML page?

No, I checked the page's source and it's not there.

> does the AJAX request fire?

Nope, not according to Firebug.

> If you go to /_profiler, do you see the entries listed there for recent pages?

Yes, every request is listed in the profiler's homepage.

Everything works great, I have no PHP errors or warnings. DEV log files look OK.

I really have no idea what's going on. I will try requesting an older symfony commit (maybe from 2 weeks ago) and see how it goes.

**Comment by SoboLAN** [comment]
I added some `var_dump`s and saw that [this line](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L102) is executed.

So it's entering that `if` for some reason... which means the method `injectToolbar` is no longer executed.

**Comment by SoboLAN** [comment]
OK so I had XDebug turned off in `php.ini`. I turned it on and now all requests come back with the `X-Debug-Token` header, as the profiler itself says:

![xdebug on](https://cloud.githubusercontent.com/assets/6078542/11312143/f3ed9170-8fdc-11e5-9918-bdb49c6c6099.png)

However, when accessing `/_profiler`, this does not happen (which is in itself weird), which means that condition above is still `false`.

**Comment by weaverryan** [comment]
@SoboLAN good detective work on debugging the line that returns false. But `X-Debug-Token` has nothing at all to do with Xdebug - it's a coincidence. Instead, that's where the `Profiler` sets the WDT url: 

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/Profiler/Profiler.php#L215

First, check that this header is missing and that this *is* the reason the `if` statement in `WebDebugToolbarListener` exits. Then, find out why the `Profiler` isn't setting it.

Btw, the toolbar works fine on my machine. I doubt this is a bug, but it could be some edge case when upgrading... that maybe we need to tell people about.

**Comment by javiereguiluz** [comment]
> However, I noticed that the debug toolbar is not visible in the profiler.

This is by design. The new profiler doesn't load the toolbar because it's redundant.

**Comment by weaverryan** [comment]
@javiereguiluz ah, THANK YOU - I wasn't reading that this was only a page on the profiler (I thought it was an issue everywhere). And yes, this makes sense to me.

**Comment by SoboLAN** [comment]
Well that's too bad. Having the toolbar in the profiler would've been really cool because it summarizes very well most of the stuff you need to know about a specific request. It's going to be one of the things I will miss in 2.8.

At least now we know it's a feature, not a bug.

Thank you @weaverryan @javiereguiluz for your answers. I will close this.
