### ISSUE TITLE
[Var-dumper] Use HtmlDumper without the provided styles

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#16618]
ATM it is not easy to use the var-dumper and its HtmlDumper without all those styles which come with it.
As the default colors doesnt look good in our app I tried `setStyles`, which doesnt override builtin styles nicely, because it only overrides certain aspects.
That means I can override everything built in now, but new versions which might define new styles wont work (so no forward compatibility).

at best I could just do `$dumper->setStyles(array());` but this does not change anything.

best I can do is

``` php
                $styles = array(
                    'default' => '',
                    'num' => '',
                    'const' => '',
                    'str' => '',
                    'note' => '',
                    'ref' => '',
                    'public' => '',
                    'protected' => '',
                    'private' => '',
                    'meta' => '',
                    'key' => '',
                    'index' => '',
                );
                $dumper->setStyles($styles);
```

but the component still generates some styles with padding,margin with the `sf-dump` classes.
Also this kind of override generates a  lot of empty css selectors for nothing...

My use case is: re-use the existing expand/collapse functionality but without all the css brought with it.

**Comment by nicolas-grekas** [comment]
I think you could overwrite getDumpHeader to amend the default css/js or use setDumpHeader to completely overwrite the css/js by you own, would it work for your use case? See also setDumpBoundaries just in case

**Comment by staabm** [comment]
@nicolas-grekas thx for your feedback. the actual question is, if this kind of changes should be possible thru the class api or if it is not and therefore is meant to be achieved by subclassing..

**Comment by nicolas-grekas** [comment]
I think it can be done both ways:
- call the default getDumpHeader, alter its result then setDumpHeader
- or specialize getDumpHeader

I've no preference for now. Do you have one?

**Comment by staabm** [comment]
> call the default getDumpHeader, alter its result then setDumpHeader

sounds like something which heavily relies on impl. details... therefore I dont like it.

> or specialize getDumpHeader

This means I need to subclass and override, right?

Maybe just adding a flag to `setStyles` which indicates whether it should override all styles instead of a certain key only?
`setStyles` atm works like a method I would have named `putStyles` or `addStyles`...
`setXX` methods should override everything instead of changing things incrementally IMO. But this is something we cannot change without BC breaks..

**Comment by javiereguiluz** [comment]
@nicolas-grekas could you think about this feature request? If implemented, we could use VarDumper whenever we need to dump variables in Symfony (which is a very common need, as explained in #18074). Thanks!

**Comment by nicolas-grekas** [comment]
@staabm one year later, what's you stand on this one? Can we close this issue? Or would you like to work on a PR?

**Comment by staabm** [comment]
The recent releases work pretty well for us, so no need for further changes from my side.
