### ISSUE TITLE
[Var-Dumper] Mutliple var-dumping on a single html page

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#16619]
We would like to use the var-dumper in our debug tool, see https://github.com/filp/whoops/pull/320, in which we dump several vars on a single page.

The var-dumper atm generates a lot of inline `<style>`-tags and javascrpt - one for each dumpped var.
I guess for use-cases like this it would be helpfull to have a way to dump the css (and js) separately from the actual vars, so it wont get repeated over and over again.

**Comment by nicolas-grekas** [comment]
I think that if you use the same HtmlDumper instance several times, it won't dump header css/js several times. Does it work

**Comment by staabm** [comment]
@nicolas-grekas thanks for the feedback.

I just found the reason why I get all the stuff duplicated... I used a utility function which re-created a new Dumper on each call. As of now I use a static var to re-use the same instance, which makes things behave like intended.
