### ISSUE TITLE
Adding fallback routeName

### ISSUE THREAD

**Issue by zhil** [symfony/symfony#16623]
When I have routes
```
@Route("/test/", name="testRoute")
@Route("/test/page-{page}/", name="testRoutePaged", defaults={"page" = "1"})
```
It would be nice instead of /test/page-1/ get automatically /test/. So duplicate content will not be generated. It can be solved using 301 redirect from /test/page-1/ to /test/, but I see much more clean solution.

It could be done using something like "fallback" routeName, which will be used when all parameters equal default values, something like

```
@Route("/test/", name="testRoute")
@Route("/test/page-{page}/", name="testRoutePaged", defaults={"page" = "1"}, fallbackRouteName="testRoute")
```

Let me know if its acceptable and I will create PR.

Related issue https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/issues/54

**Comment by Tobion** [comment]
As already linked, this would be covered by #5424.
But the redirect would be needed anyway. Also in your case. What if somebody requests `/test/page-1/` manually. You still need to redirect then. Otherwise you still have duplicate content.

**Comment by zhil** [comment]
@Tobion yes, you are right, I misunderstand ticket #5424

it would be nice to redirect automatically to "most simple url", added note to that ticket
