### ISSUE TITLE
Symfony MongoDB configuration always uses same database for different bundles and mappings

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#16620]
Hi,

I wonder if this is a bug or I'm missing something hidden in footprint. My problem is, the config.yml configuration for mongodb always creates/uses the same database (`frontend_database`) although I have two options/databases for two different bundles. Would anyone know the solution for this issue?

**Usage**

 - `doctrine_mongodb.odm.frontendconn_document_manager` for *ApplicationFrontendBundle*
 - `doctrine_mongodb.odm.backendconn_document_manager` for *ApplicationBackendBundle*
 

**config.yml**

    doctrine_mongodb:
        default_database: frontend_database
        default_connection: frontendconn
        default_document_manager: frontendconn
        connections:
            frontendconn:
                server: mongodb://localhost:27017
                options:
                    connect: true
                    db: frontend_database
            backendconn:
                server: mongodb://localhost:27017
                options:
                    connect: true
                    db: backend_database
        document_managers:
            frontendconn:
                connection: frontendconn
                mappings:
                    ApplicationFrontendBundle: ~
            backendconn:
                connection: backendconn
                mappings:
                    ApplicationBackendBundle: ~

**Request payload**

    POST /frontend/mongo 200
    { "name": "Frontend Lig" }

    POST /backend/mongo 200
    { "name": "Backend Lig" }

**Result**

As you can see below, only `frontend_database` presents which includes *Backend Lig* record as well and `backend_database` is nowhere to be seen!

[![enter image description here][2]][2]

  [1]: http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#multiple-connections
  [2]: http://i.stack.imgur.com/6xFaO.png

**Comment by WouterJ** [comment]
As this is related to the MongoDBBundle, please report the issue in that repository: http://github.com/doctrine/DoctrineMongoDBBundle . This repository is purely for bugs/feature requests for the Symfony framework.

**Comment by BentCoder** [comment]
Moved to https://github.com/doctrine/DoctrineMongoDBBundle/issues/322
