### ISSUE TITLE
Annotating controller as a service/dependency component

### ISSUE THREAD

**Issue by chinmayzen** [symfony/symfony#16626]
So currently we can use `@Route` to specify a controller as a service

http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#controller-as-service

Shouldn't we have a separate annotation for it?

Instead of doing it this way:
```
/**
 * @Route(service="my_post_controller_service")
 */
class PostController
{
    // ...
}
```
How about this:

```
/**
 * @Controller("my_post_controller_service")
 */
class PostController
{
    // ...
}
```

Like in Java/Spring MVC we have `@Controller` , `@Service`, `@Component`, `@Resource` for Autowiring "beans".

**Comment by TomasVotruba** [comment]
I must say using @Route for service definition was really confusing for me.

**Comment by WouterJ** [comment]
As this is related to the SensioFrameworkExtraBundle, please report it on their repository instead of the symfony core one: http://github.com/sensiolabs/SensioFrameworkExtraBundle

**Comment by chinmayzen** [comment]
https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/386
