### ISSUE TITLE
Request Accept Header with multiple values returns inconsistent contains() responses

### ISSUE THREAD

**Issue by rupertjeff** [symfony/symfony#16646]
I'm building an API as part of a larger Laravel-based application and I'm trying to work through Content Negotiation as per the JSON API 1.0 specification. I'm using Postman to send a request with the snippet below:

```http
GET /generic/request HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
Accept: image/png
```

When I try to run `$request->headers->contains('Accept', 'application/vnd.api+json')` I receive `false`.

`$request->headers->get('Accept')` returns a string `"application/vnd.api+json, image/png"`.

Is this the expected functionality, or should I be doing something else instead? I perused the code, and it looks like `HeaderBag::contains()` runs `in_array()`, but as the `Accept` header is always coming back as a string, there's no exact match.

Thanks! Let me know if more information is needed, or if there's something I'm missing.

**Comment by derrabus** [comment]
[RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1) describes the Accept header as a comma-separated list of acceptable media types. In that context, your request with multiple Accept headers looks strange (also, a Content-Type header in a GET request doesn't make much sense). If you followed the standard, the request would look like this:

```HTTP
GET /generic/request HTTP/1.1
Accept: application/vnd.api+json, image/png
```

I haven't verified the behavior you described, but it looks like HTTP Foundation healed your malformed request. And even if it didn't: You application should be able to parse a "correct" Accept header and a `contains()` call is a bit too simple for that purpose.

**Comment by derrabus** [comment]
Do you know the `Request::getAcceptableContentTypes()` method? Maybe this little fellow does what you need. If you need something more powerful, you could try to use the `AcceptHeader` class directly.

```php
AcceptHeader::fromString($request->headers->get('Accept'))
```

**Comment by rupertjeff** [comment]
Yes, when the request is parsed, the `Accept` header is the comma separated list. It does seem like `HttpFoundation` fixed the header in that sense.

While I have worked around it, it seems like `$request->headers->contains('Accept', 'application/vnd.api+json')` should return `true`, because it does in fact contain that value within this example. I feel like it's counter-intuitive to use `contains` and receive `false` in this case.

I actually had to override code that was using `Request::getAcceptableContentTypes()` because I believe it was adding `*/*` as an acceptable content type, breaking the JSON API standards. (It's also possible that Laravel was doing that behind the scenes. I didn't investigate that one too far.)

I did not know about the `AcceptHeader` class, so I'll definitely look into that one. Thanks for the tips!

**Comment by derrabus** [comment]
Well that is how the `contains` method is implemented. It tests for exact matches and is therefor not the right tool to parse content negotiation headers. That's what the `AcceptHeader` class is for.

If any piece of code was magically adding `*/*` to the list of acceptable types, it would change the semantics of your request. That would be really bad. As far as I can tell, HTTP Foundation is not the evil player here. Testscrpt:

```php
<?php

use Symfony\Component\HttpFoundation\Request;

require __DIR__ . '/vendor/autoload.php';

$request = new Request;
$request->headers->set('Accept', 'application/vnd.api+json, image/png');

var_dump($request->getAcceptableContentTypes());
```
Output:
```
array(2) {
  [0]=>
  string(24) "application/vnd.api+json"
  [1]=>
  string(9) "image/png"
}
```

**Comment by rupertjeff** [comment]
Oooh, I like that. Much simpler than what I'm doing. I'll definitely jump back in and play some more here. Thanks!

My only sticking issue is that `HeaderBag::contains` uses `in_array` to do a string comparison. It's misleading when you're perusing the code. (I don't know if the documentation specifies this functionality; I'm of the mindset that I should be able to determine what something does by reading the code. That, and I was on an airplane without any WiFi.) Is there something I don't know about `in_array` that makes this method more effective?

**Comment by derrabus** [comment]
http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/HeaderBag.html#method_contains

> Returns true if the given HTTP header contains the given value.

I see your point. The method's documentation might be misleading in your case. Any suggestions for a better description? Submit a PR. :smiley:
