### ISSUE TITLE
[Expression-Language] Introduce the possibility of overriding builtin operators

### ISSUE THREAD

**Issue by priyadi** [symfony/symfony#16657]
Introduce the possibility to override builtin operators, and adding new ones. This can be used, for example, to replace the default PHP operators with bcmath functions.

This can also be useful to overcome the lack of operator overloading in PHP.

**Comment by fsevestre** [comment]
+1

We need this feature too. We ended up using a fork of the component where we override the operators but if you can provide a way to override the built-in operators, it would be awesome.

**Comment by sstok** [comment]
If you reuse the logic of https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Lexer.php#L367-L395 it should not be to hard getting this done.

```php
$l = new ExpressionLanguage();
$l->registerOperator($operator, callable $compiler, callable $evaluator, $precedence = 50);
```

I will try to add this :+1:

**Comment by fabpot** [comment]
@sstok indeed as the component is actually a subset of Twig. But I deliberately make some choices when designing the component and one of them was to only have one extension point: functions. So, I'm closing this issue as a won't fix.
