### ISSUE TITLE
Not able to upgrade to syfmony 2.7.7

### ISSUE THREAD

**Issue by Restless-ET** [symfony/symfony#16661]
Hi guys,

Not sure if this should be here or in the composer repository... but since I'm only getting this problem for the `symfony/symfony` package here it goes.

I'm having some struggles upgrading to symfony 2.7.7.

In composer.json file: `"symfony/symfony": "2.7.*"`

Doing `composer update symfony/symfony` I get:
```
Updating dependencies (including require-dev)                           
  - Removing symfony/symfony (v2.7.5)                        
  - Installing symfony/symfony (v2.7.6)
    Downloading: 100%  
```

I've already tried to clear my composer cache (`rm -rf ~/.composer/cache`) and still the same problem.
A simple `composer update` doesn't work either.
Any ideas?

Regards

**Comment by Tobion** [comment]
Can you try `composer update symfony/symfony --with-dependencies`. The twig library requirement was increased, so maybe it doesnt install the latest because you have old twig version.

**Comment by Restless-ET** [comment]
That was it, I had `twig/twig` restricted to `1.20.*` on my composer.json.

Thank you very much for your help and quick answer. :)

I'll close this...
