### ISSUE TITLE
[!] UPGRADE guides: Mention all breaking changes in 3.0?

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#16667]
So there is a very big inconsistency in the UPGRADE guides of Symfony. Back in the days where BC was not a Symfony thing, UPGRADE guides mentioned all breaking changes. When BC layers where introduced, deprecations weren't mentioned in the UPGRADE guides and only the removed features were added to the UPGRADE-3.0 guide (e.g. https://github.com/symfony/symfony/commit/8da61295a4826ba9766871e07011174f878a0955).

Somewhere around 2.4, deprecations were added to the UPGRADE-2.4 file and the UPGRADE-3.0 file didn't mention anything about the removed feature.

Now, the UPGRADE-3.0 file is far from complete. I think we should take care that every removed feature is mentioned in the UPGRADE-3.0 file, maybe linking to the older UPGRADE files for the full migration details.

**Comment by SoboLAN** [comment]
Sustained !

This will make a much easier upgrade from older Symfony versions, as you will reduce the amount of manual testing needed (which can be significant in applications that have dozens or even hundreds of bundles).

**Comment by xabbuh** [comment]
see #17405 which tackles upgrades coming from deprecations in 2.7

**Comment by xabbuh** [comment]
We should compare the upgrade files for 2.4, 2.5, and 2.6 too.
