### ISSUE TITLE
how to map a form error of parent form to children form field?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#16675]
I saw this document several times, but the example in this document is very confusing, I still can't understand why it assume a method 'matchingCityAndZipCode' exists , then assume it doesn't exist.  I think there should be an example that shows mapping any form error to any field of  form , child form  or parent.
[error-mapping](http://symfony.com/doc/current/reference/forms/types/text.html#error-mapping)

**Comment by Tobion** [comment]
Please open documentation issues at https://github.com/symfony/symfony-docs. Thanks
