### ISSUE TITLE
Any plan to make tests Independent?

### ISSUE THREAD

**Issue by su-xiaolin** [symfony/symfony#16674]
directory structure like below:
```
src
    Symfony
        Bridge
            ...
        Bundle
        Component
Tests
        Bridge
            Monolog
                Handler
                    ConsoleHandlerTest.php
                    ...
        Bundle
            ...
        Component
            ...
```

**Comment by nicolas-grekas** [comment]
No plan you're right. Why should we have one?

**Comment by su-xiaolin** [comment]
I have deep impression with tests of yii2 framework project(https://github.com/yiisoft/yii2), I can not give an clear reason, But it maybe to be more maintainable and to be more clear directory structure.

**Comment by stof** [comment]
Well, we keep tests alongisde the code because this allows to have tests in our subtree splits repositories.
Otherwise, we would indeed keep them separate (this was the case in the early days of Symfony, before we introduced subtree repos)

**Comment by su-xiaolin** [comment]
Well, for single repository, Is change structure to like below will be better?:
```
Monolog
    src
        Formatter
        Handler
            ConsoleHandler.php
        ...
    Tests
        Handler
            ConsoleHandlerTest.php
        ...
```

**Comment by nicolas-grekas** [comment]
this is exactly what we have, but on a component by component basis
See e.g. https://github.com/symfony/httpkernel which is an automatic subtree split from this bigger repos

**Comment by su-xiaolin** [comment]
Well, Maybe I got it, I recommand put source code in src folder, test file in tests folder, and composer.json .gitignore .travis.yml phpunit.xml ..etc file in the root folder, like my "notify" repo https://github.com/su-xiaolin/notify. It will make file structure more clear.

**Comment by stof** [comment]
@su-xiaolin this would force the main repo to have this structure inside each component, making autoloading configuration a huge pain (we cannot change the structure between the pain repo and subtree repos, otherwise it is not a subtree anymore)

**Comment by su-xiaolin** [comment]
How about to make component standalone instead of subtree repo, like zf2 project https://github.com/zendframework/zf2, That will achive our goal.

**Comment by Tobion** [comment]
That would make daily work harder. We already had this discussion. At the moment we do not plan to change the directory structure. Also with #16397 it should not really matter that much anymore that the tests are mixed with the src in the same root dir.
