### ISSUE TITLE
Constraint caching causes Callback to be executed only for the first group

### ISSUE THREAD

**Issue by rainbow-alex** [symfony/symfony#16671]
Callback constraints are cached and will only run for the first group they match.

In my case, I have a Callback constraint that in turn uses $context->getValidator() to validate other values. These values have constraints with various groups. If I start the validation off with multiple groups, the callback is only run for the first group. If it then uses constraints with other groups they are never enforced.

I can't seem to find a way to get hold of all the groups in the Callback body, or to run more validation in anything but the first (or default) group.

I believe the constraint cache is supposed to be a performance optimization, not affect behavior. Maybe callback constraints should be excluded from it?

**Comment by rainbow-alex** [comment]
Running 2.8.x-dev#3b99b3a6e71da0f7d3fb07cf5c728ad04a326416 btw

**Comment by rainbow-alex** [comment]
I also seem to be encountering the same issue with nested composite constraints. Even though the groups propagate correctly from child to containing constraint, the nested constraints are only executed for the first group.

**Comment by kezek** [comment]
+1

**Comment by SoboLAN** [comment]
Can you put together an [SSCCE](http://sscce.org/) that shows this behaviour ?

**Comment by rainbow-alex** [comment]
```php
<?php

namespace example;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory;
use Symfony\Component\Validator\Mapping\Loader\StaticMethodLoader;
use Symfony\Component\Validator\Validation;

// $ composer require symfony/validator
require "vendor/autoload.php";

class Example
{
    /** @var string[] */
    public $elements;

    /**
     * @param ClassMetadata $metadata
     */
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraints("elements", [
            new All([
                new NotBlank(["groups" => "strict"]),
                new Type("string"),
            ]),
        ]);
    }
}

$example = new Example;
$example->elements = ["foo", ""];

$validator = Validation::createValidatorBuilder()
    ->setMetadataFactory(new LazyLoadingMetadataFactory(new StaticMethodLoader()))
    ->getValidator();

// default validation
$violations = $validator->validate($example);
var_dump(count($violations)); // 0

// only "strict" validation
$violations = $validator->validate($example, ["strict"]);
var_dump(count($violations)); // 1

// default & "strict" validation
$violations = $validator->validate($example, [Constraint::DEFAULT_GROUP, "strict"]);
var_dump(count($violations)); // expected 1, but actually 0
```

@SoboLAN this exhibits the unexpected behavior both with symfony/validator 2.7.7 and 2.8.x-dev...

**Comment by webmozart** [comment]
This is actually the expected behavior. A constraint that belongs to multiple groups that are executed is validated only once. Groups are just a way to categorize constraints, the constraint validator should never let its logic depend on the group.

**Comment by rainbow-alex** [comment]
@webmozart If the constraint validator should not let its logic depend on the group, how is it expected that adding another group changes the end result? Doesn't this show that the All validator depends on the group?

**Comment by zhurinvs** [comment]
@webmozart, in this case, i can't understand, how Valid constraint validator works? It's a one constraint, but it must be validated through miltiple groups. Why RecursiveContextualValidator not skips it after validation through first group?
