### ISSUE TITLE
[Process] Issue with setTTY=true

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#16683]
There is an issue with `test1.php`. Because we are using
`$process->setTty(true);` the output of the process is not really wired with my
term output. It means, for example, I'm not able to direct STDOUT nor pipe the
execution of `php test1.php`.

It looks like it's a bug with the file descriptor. The Process component use my
tty FD and not the current process FD

```php
// test1.php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Process\ProcessBuilder;

$process = ProcessBuilder::create(['find', 'vendor'])->getProcess();
$process->setTty(true);
$process->run();
```

ping @romainneutron

**Comment by stof** [comment]
well, isn't this the expected behavior when using tty mode ?

**Comment by lyrixx** [comment]
I'm not sure.

**Comment by stof** [comment]
AFAIU, the tty mode is precisely meant to bind the process to the tty FD. If you want to get the output of the sub-process in your main process, you should not be using tty mode (which means your script above is probably using tty mode for the wrong reason)

**Comment by romainneutron** [comment]
Hello, I'm not very used with this TTY option... AFAIK it allows to pass the user fds to the underlying subprocess. This should be used when for example running à `new Process('vim')`. What is your use case, because for running `find vendor`, you should not use `->setTty(true)`?

**Comment by lyrixx** [comment]
We use it in melody. See the linked ticket to have a detailed report.

**Comment by romainneutron** [comment]
:) Yes, but it does not telle me why you're using `setTty(true)`. As @stof said, this is the expected behavior

**Comment by lyrixx** [comment]
Understood ;)

I'm closing this issue. If someone could find a workaround, please comment here ;)
