### ISSUE TITLE
Static code analysis failure on ApacheUrlMatcher

### ISSUE THREAD

**Issue by opb** [symfony/symfony#16680]
Hi there

I'm working on a project which requires static code analysis to be run on all code, using Checkmarx. The only outstanding issue we're seeing which isn't related to test suites is an alleged XSS vulnerability in ApacheUrlMatcher. I've included output from the test report below:

![checkmarx-symfony](https://cloud.githubusercontent.com/assets/778850/11420926/3f11081c-9429-11e5-8cb9-de522b536c9a.png)

Our current solution is to fork and add some sanitising into this class. But I wanted to report it in case it was something that is seen fit to address. I'm sure there's no actual vulnerability here, but it is getting flagged up.

Thanks

**Comment by Tobion** [comment]
The return value of ApacheUrlMatcher is not used as user output in symfony. So there cannot be an XSS vulnerability.

Do you use the ApacheUrlMatcher and use the return value as options for Guzzle? I'm sure you don't as it doesn't make sense. So this report from Checkmarx is wrong.

> Our current solution is to fork and add some sanitising into this class.
What sanitization?
