### ISSUE TITLE
Symfony2 cache issue while setting session save path dynamically

### ISSUE THREAD

**Issue by feridmovsumov** [symfony/symfony#16701]
I am trying to set session save path dynamically in Bundle extension class
```php
namespace AdminBundle\DependencyInjection;

class AdminExtension extends Extension{
...
   $sessionDir = $envDir . "session/store/$userDir/__sess";
   $container->setParameter("session.save_path", $sessionDir);
...
}
```
Symfony caches Extension class
```php
$sessionDir = $envDir . "session/store/12345/__sess";
```
So it make sessionDir equal to directory of user who make first call.

It works normal for first user but doesn't work for others.

What can I do to solve this problem?

I asked question on Stackoverflow http://stackoverflow.com/questions/33952177/symfony2-cache-issue-while-setting-session-save-path-dynamically

**Comment by mvrhov** [comment]
You can't configure your session directory dynamically.  Everything that's inside config files is cached at the first request.

**Comment by feridmovsumov** [comment]
I solved problem by writing my own NativeSessionHandler 
```php
class NativeFileSessionHandler extends NativeSessionHandler
{

    /**
     * @param ContainerInterface $container
     */
    public function __construct(ContainerInterface $container)
    {
       ...
        ini_set('session.save_path', $envDir . "session/storefront/$userDir/__sess");
        ini_set('session.save_handler', 'files');
    }

}
```

**Comment by Tobion** [comment]
as @mvrhov explained, the DI container cannot be used for things that are different on each request. I would suggest to use an event listener for this.
