### ISSUE TITLE
Deprecated choice_list option in ChoiceType?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#16716]
Do me miss a deprecation notice and a code update for this?

https://github.com/symfony/symfony/blob/743e670f4acbcb5863fd0248c97bd25050f3f44f/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L310

**Comment by xabbuh** [comment]
It is deprecated in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L257, but it seems we did not remove it entirely in #16075.

**Comment by webmozart** [comment]
As @xabbuh said, it seems to be correctly deprecated in 2.8. I think we can remove it in 3.0 and move the code in the closure to a private `createChoiceList()` method instead.

**Comment by webmozart** [comment]
see https://github.com/symfony/symfony/pull/16715
