### ISSUE TITLE
[WebProfilerBundle][2.7] Should debug bar have master request?

### ISSUE THREAD

**Issue by varloc2000** [symfony/symfony#16711]
Hello!

I implement `kernel.request` event listener for redirecting to the different route in some cases.
Filter sub requests as described in [doc](http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html)
```php
if (!$event->isMasterRequest()) {
            // don't do anything if it's not the master request
            return;
}
```

Then I make redirect if use authorized and etc.
```php
$event->setResponse(
                    new RedirectResponse($this->router->generate('fos_user_profile_edit'))
);
```

And checking for master request doesn't prevent from redirecting web profiler toolbar, so, in this case - toolbar missing and contain my target response of my redirect. 

It's ok that web profiler ajax is a master request? Or how to check this situation?

**Comment by jakzal** [comment]
Any request coming through a web server is a master request. You need to find other way to filter it out (like a request path etc). 

Closing as there's no bug here, and we don't use github issues for support questions.
