### ISSUE TITLE
URL validator somehow adds protocol to value before persisting entity

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony#16714]
```php
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Url()
     */
    private $url;
```

Then a form object that merely states the field name, bound together on my controller by ```$form->submit($request);```. 

Somehow, values without protocol not only pass validation (eg any alphanumeric string), but the persisted entity __contains__ the protocol.

If I remove the Url assertion from the entity, the persisted entity is saved with that value verbatim.

After checking the Request object (it receives the value verbatim, so no listener modifying incoming data) and the entity passed on to `createForm` before and after `submit`, It seems that something within `Symfony\Component\Form\Form::submit` is hydrating the entity (as it should) with a modified value (as it shouldn't), instead of the original one, based on this assertion.

This is on symfony 2.8-beta1 + FOSRestBundle.

**Comment by dosten** [comment]
This is the default behaviour when you use the `UrlType`, if you do not want to automatically prepend the url with the protocol, you must set the `default_protocol` to `null` when you add the url field.

**Comment by luispabon** [comment]
I don't understand, this is a validator. Why is it modifying data?

**Comment by luispabon** [comment]
For that matter:

```php
    /**
     * @var integer
     * @Assert\Type(type="integer")
     * @Assert\Range(min="0")
     */
    private $averageViewsPerVideo;
```

This is casting anything I pass on to an integer, for instance 8.46465432 gets persisted as 8.

**Comment by luispabon** [comment]
Now that I think of it, I am not using the UrlType either. This is just a field called $url which has a Url assertion associated with it.

**Comment by luispabon** [comment]
I am not using the UrlType on the form. I'm just adding a field called `url` on my form, then relying completely on annotation based validation to make sure data is sane.

This:
```php
    /**
     * @var integer
     * @Assert\Type(type="integer")
     * @Assert\Range(min="0")
     */
    private $averageViewsPerVideo;
```
This is casting everything I'm passing as an integer, for instance 8.1565 gets transformed to 8.

Unless I have something set up horribly wrong, there's something fundamentally wrong with form processing and validation. Validation rules should never modify any values, only check they're correct as per assertions or not.

**Comment by xabbuh** [comment]
If you do not configure the form type you want to use, Symfony will try to guess the most appropriate form type for you. To do that it can, for example, evaluate the configured validation constraints using the `ValidatorTypeGuesser` which among others looks for [Url](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L146) and [Range](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L156) constraints.
