### ISSUE TITLE
bootstrap.php.cache not build correctly

### ISSUE THREAD

**Issue by weberdominik** [symfony/symfony#16738]
Since the last update to 2.7.7 my boostrap.php.cache is not build correctly anymore. This specific part of it is missing:

namespace {
    error_reporting(error_reporting() & ~E_USER_DEPRECATED);
    $loader = require_once __DIR__.'/../app/autoload.php';
}

Was this removed in the last release? Without it the autoloading isn't working. If I manually add it everything works fine.

**Comment by jakzal** [comment]
See https://github.com/symfony/symfony-standard/pull/854

**Comment by weberdominik** [comment]
Thanks for the quick reply, that fixed it.
