### ISSUE TITLE
[DX][Profiler] Silenced Errors

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#16740]
I just had the situation of silenced errors in an app. It took me a bit to figure out where the silenced errors can be found (actually somewhere in between the debug messages).

What do you think about adding a separate tab for the silenced errors if technically possible?

<img width="760" alt="bildschirmfoto 2015-11-29 um 13 47 28" src="https://cloud.githubusercontent.com/assets/2010989/11457078/d43b376e-969f-11e5-9b6d-adcb300029b3.png">

Also I think it is a bit confusing that the error counts in the toolbar deviate from the error counts in the profiler sidebar

<img width="278" alt="bildschirmfoto 2015-11-29 um 13 47 44" src="https://cloud.githubusercontent.com/assets/2010989/11457079/d8e22d18-969f-11e5-9632-5fec6cb6c900.png">

**Comment by Tobion** [comment]
The log count in the sidebar is only about the deprecations as you can see from the coloring.

**Comment by peterrehm** [comment]
Okay so counts make sense, it is just when seeing 3 numbers it would be great to see them again in the profiler, not only in the toolbar.

But silenced errors as in this case a PHP notice are important and should be adressed. This relates to this PR https://github.com/symfony/symfony/pull/10466#issuecomment-37808597. At least a special tab could make sense instead of hiding them only into the Debug tab.

**Comment by JHGitty** [comment]
Great idea! :+1:
