### ISSUE TITLE
[Var-Dumper] Dont expand 1st level per default

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#16741]
ATM the var dumper renders a object expanded on the first level by default,
see http://i.imgur.com/PzebmFI.png

We would like to render it collapsed by default, but it seems there is no API to do that atm.
I guess there should be a option which defines how much "levels" are expanded by default of the given object/array.

wdyt?

Thanks, 
Markus

**Comment by nicolas-grekas** [comment]
This is parameter for the embeded JS. I see two ways to make this possible:
1. add a new method on HtmlDumper to configure the generated JS
2. or make it possible to prepend the generated JS with these params, without requiring any API change on HtmlDumper.

I prefer 2. for now, what do you think?

**Comment by staabm** [comment]
2 would also require a api change, because it requires a new method?

Atm the component does not define a JS api, does it? Should it have a js api which allows programmatically expand/collapse of the elements beeing rendered?
