### ISSUE TITLE
[2.8][Form] entry_type inconsistency

### ISSUE THREAD

**Issue by craigh** [symfony/symfony#16750]
In 2.8, the `entry_type` parameter in the collection type form accepts the old normal strings like `'email'` (according to the docs) but this is not how forms work going forward (3.0) in other usages. Shouldn't it require the FQCN `'Symfony\Component\Form\Extension\Core\Type\TextareaType'`

**Comment by Tobion** [comment]
It accepts both a name and FQCN in 2.8 and only FQCN in 3.0. If you experience something else please concrete bug report.

**Comment by craigh** [comment]
I hadn't tested it or experienced it. I was simply reading the docs: http://symfony.com/doc/2.8/reference/forms/types/collection.html#entry-type

**Comment by Tobion** [comment]
https://github.com/symfony/symfony-docs/issues/5588

**Comment by Tobion** [comment]
https://github.com/symfony/symfony-docs/pull/5909#issuecomment-160483912
