### ISSUE TITLE
[RFC][HttpKernel] Add ``getWebDir()`` method

### ISSUE THREAD

**Issue by afoeder** [symfony/symfony#16756]
I propose to introduce 

* an HttpKernel's method ``getWebDir`` which per default returns ``return $this->rootDir.'/../web'``. Besides, this method should be added to the ``\Symfony\Component\HttpKernel\KernelInterface``
* a kernel parameter ``kernel.web_dir`` added in ``\Symfony\Component\HttpKernel\Kernel::getKernelParameters`` working similar to the other ``get...Dir()`` invokations.

Remaining Questions:

* actual naming, is "web dir" appropriate, or should it be rather ``document root``, which is more generic but probably confusing
* ``realpath`` handling, the ``get...`` method should maybe already apply it to get rid of the ``../``; on the other hand, it might return ``false``.

**Comment by iltar** [comment]
I would like to have this feature as the default implementation of packages (bundles) are often `%kernel.root_dir%/../web`. This causes a lot of problems when your `(App)Kernel` is not located in the default location. One option would be to move the kernel to always be 1 level deep, but that's quite limiting if you ask me. Another option would be to have bundles configure this option manually, this goes either via config or as argument of a command (Assetic for example). This is additional configuration and might end up having to define this directory for multiple bundles.

I would go for the name `kernel.web_dir` as it's most consistent with the naming you'd expect for `/web` and would also be the easiest to find for developers when searching for it.

In theory such a small feature could easily be added to all current LTS and 3.0. I don't think the interface method can be added before we go to 4.0 though.

**Comment by stof** [comment]
I'm not sure that the kernel is the right place for it:

- the kernel itself does not need to know at all about it
- having to overwrite a kernel method is harder than being able to just overwrite a parameter, so we should avoid it when the kernel does not need to know about it before the container creation

Note that my arguments also apply to ``getLogDir``. And we indeed have an issue discussing whether it should be removed from the kernel: #16572

**Comment by fabpot** [comment]
This has been rejected in the past. Symfony itself does not care about the web directory and is totally agnostic about where you store your public assets.

**Comment by afoeder** [comment]
Well every App (and we are in an App(lication) context here) has intrinsincally its ``AppKernel`` class (``(Http)Kernel`` is abstract, just to mention). So it's _simple_ to override that method.

OK, but I see the point with @fabpot's comment... If any argument left, I would see it at least developer candy... What would be the best practice to this very common approach? I'd be in (for/to contribute) a best-practice-entry then.

**Comment by iltar** [comment]
I have encountered several cases where I needed to know the web-dir and the only solution was to add it in my own bundle. Would it be an idea to add it in the FrameworkBundle otherwise? Not sure if prefixing with `kernel.` would be right then.

**Comment by stof** [comment]
@iltar the fact that there is a webserver root directory does not mean that the kernel has to be aware of it.
Btw, even though ``$this->rootDir.'/../web'`` is the web dir of the symfony project, it does not mean that this is the configured document root (when I was on my previous computer, I was using ``http://localhost/<project>/web/app_dev.php`` to access my projects, to avoid creating new virtual hosts in WAMP each time I wanted to access another project)

@afoeder the fact that you have to overwrite a kernel method to replace the value of the parameter instead of redefining the parameter is something which confuses many users. So even if overwriting the method is simple, understanding that you need to overwrite the method to change the parameter is not.

**Comment by goetas** [comment]
@iltar I have some symfony web projects and i do not have at all a "web" dir handled by symfony.
(the "webdir" is handled by an external ad hoc application that invokes symfony simply as any other class)

**Comment by javiereguiluz** [comment]
Closing it because some Symfony Core members are against it. Moreover, as @stof said, we are now focused on removing instead of adding methods like this (e.g. removing `getLogDir()`).
