### ISSUE TITLE
Add CSS class to missing translations

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16764]
I have a lot of different translations. Often translations are missing in heavy development.
It would be great if a CSS class would be added to the missing translations.

Example in Twig:
```twig
{% trans %}Test{% endtrans %}
```

Result if translation is missing:
```html
<span class="translation-missing">Test</span>
```

This feature should ony be available in ``dev`` environment.

I know that this issue is not directly related to Symfony but maybe there could be any feature which could be helpful for this. This way to help developers could be a good way for other things too. Any idea?

**Could this feature be part of the Symfony Profiler?**

**Comment by stof** [comment]
injecting extra HTML in the output of translations seems like a bad idea to me (and it would not work for the trans filter as its output is not considered safe, and should not).

Note that the profiler already lists the missing translations since 2.7

**Comment by JHGitty** [comment]
@stof Yes but my partners like to have a more visual effect of missing translations. Do you have any idea how to do such things?

**Comment by WouterJ** [comment]
You can create a custom Twig NodeVisitor, visit each trans/transchoice tag and check if the translation is missing (using the utilities of the Translation component). You can then add the class in the NodeVisitor.

**Comment by iltar** [comment]
@WouterJ I was actually thinking of something similar in a special environment to make it possible to see which keys are being used for the specific translation. This would help out a lot for the department that wants to change the translation. Not sure how well that would perform though.

**Comment by aitboudad** [comment]
I think that's a good idea, which can allow inline editing of translations, I can made an initial work for this.

**Comment by iltar** [comment]
@aitboudad If you're really interested in doing so, could you take into account that not everything will be stored on the local filesystem? There's also API/database solutions with custom loaders so  a custom "saver" would be nice to implement.

**Comment by stof** [comment]
I suggest you to look at the existing bundles related to translation (unfortunately, knpbundles.com is down so you may need to wait a bit to use it to search for them). Many bundles exist for that, and one of them may be providing the UI you want.

**Comment by JHGitty** [comment]
@aitboudad @iltar Great idea! A custom saver would be the best solution. Maybe this idea could be done as bundle? I would use it! :+1:

**Comment by aitboudad** [comment]
I think so, I'm working on it right now ;)

**Comment by jelte** [comment]
This is actually a bad idea, and will break the moment you use a translation in an attribute of an html tag. 

```twig
<img src="..." alt="{{ 'some_text'|trans }}">
```

would result in invalid html
```html
<img src="..." alt="<span class="translation-missing">Test</span>">
```

I've worked on this and ended up using a custom tag such as `__translations__` which is replaced by javascript with a `span` tag after checking if it's in an attribute or not.

For my work I made a web translator bundle which does this, and gives the user a toolbar (like the debug bar) that allows them to then translate the missing ones. Sadly this is very project specific so I can't really link it.
I had to use a separate Profiler, DataCollector, etc. as we needed the client to be able to enable/disable this on production.

this works great, but not for large sites or with ajax.

**Comment by javiereguiluz** [comment]
I'm closing this feature request as "won' fix". The reason is that it's "impossible" to do it right in every case and this would break lots of pages. Besides, the profiler already provides this information (although it's not as visual and convenient as this feature request).
