### ISSUE TITLE
Forgotten to update EOM and EOL for 2.8 and 3.0

### ISSUE THREAD

**Issue by dosten** [symfony/symfony#16765]
Hi there!

Before the release of 2.8 and 3.0 you should update the EOM and EOL constants of the Kernel class (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L69-L70) actually the date in this constants are for the 2.7 version.

ping @fabpot

**Comment by fabpot** [comment]
You're right, fixed... but 2.8.0 has already been released.
