### ISSUE TITLE
Iconv is now a non-optional requirement

### ISSUE THREAD

**Issue by ged15** [symfony/symfony#16778]
Hello!
Firstly, thanks for the amazing work with the 2.8 release. Really appreciate where Symfony is taking the PHP community.
Since 2.8, the Doctrine DbalLogger depends on `ext-iconv` (https://github.com/symfony/symfony/commit/303f05baafc2267b72812c44670493433b7acb0f#diff-73a4d939fb81dde9644f37875a394d42R102). In the [reference for requirements](http://symfony.com/doc/current/reference/requirements.html) `ext-iconv` is listed as an optional requirement.
IMO it should be noted there that you either need the extension or the polyfill (the `iconv` polufill is not being installed when updating to Symfony 2.8 currently).

**Comment by stof** [comment]
A better solution might be to rely on mbstring in the DbalLogger instead of iconv, as we have the mbstring polyfill (and we were using mbstring when available previously).

@nicolas-grekas what do you think ?

**Comment by Tobion** [comment]
Thanks for opening, but this is a docs issue. Please open a ticket at https://github.com/symfony/symfony-docs
Fyi, according to https://github.com/sensiolabs/SensioDistributionBundle/pull/231 iconv is always preinstalled. Or do you have a php version where iconv is not available?

**Comment by ged15** [comment]
It was disabled on an Arch Linux dev machine.

**Comment by derrabus** [comment]
@stof: The mbstring polyfill internally uses iconv to emulate the mbstring functionality. So switching to mbstring wouldn't change anything.

Maybe this change of requirements should be reflected in the UPGRADE-2.8.md/UPGRADE-3.0.md documents.

**Comment by derrabus** [comment]
To clarify: The iconv extension in compiled into php by default, yet it is still technically possible to disable it when compiling php. But at least I haven't seen anyone doing this for quite a while now.

**Comment by Tobion** [comment]
@derrabus it would change something if mbstring is installed instead of iconv (which this ticket is about).

**Comment by derrabus** [comment]
> it would change something if mbstring is installed

@Tobion: True, I did not think of that constellation.

**Comment by derrabus** [comment]
So, we could basically fix this by replacing all calls to the iconv extension with calls to mbstring. I can work on this during the HackDay. Should I?

/ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
iconv is now a mandatory requirement in 2.8 so the doc needs to be fixed.
but we don't clutter the composer.json files with ext-iconv (same as we don't mention ext-tokenizer)
it's enabled by default, that's enough

**Comment by nicolas-grekas** [comment]
adding ext-iconv would prevent using the polyfill btw
and we don't want to require the polyfill by default

**Comment by derrabus** [comment]
Okay, in this case, I've added a small note to the UPGRADE-2.8 file, see #16856.
