### ISSUE TITLE
Issue with symfony3 installer

### ISSUE THREAD

**Issue by sameg14** [symfony/symfony#16770]
I decided to install symfony3 today and ran into an issue. I am on an ubuntu14 virtualbox VM on a mac. 
I ran the following commands from the website to install the installer
```
sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
sudo chmod a+x /usr/local/bin/symfony 
```
I then used the installer to create a new project
```
symfony new project3
```

I then encountered the following error
```
PHP Warning:  require(/var/www/project3/app/SymfonyRequirements.php): 
failed to open stream: 
No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265

PHP Fatal error:  require(): Failed opening required '/var/www/project3/app/SymfonyRequirements.php' 
(include_path='.:/usr/share/php:/usr/share/pear') 
in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
```

**Comment by cameronmurphy** [comment]
+1

**Comment by weaverryan** [comment]
This is caused by the symfony-installer. It's been fixed, but the latest version (of the installer) may not be downloading correctly. You can of course clone https://github.com/symfony/symfony-standard in the mean time :)
