### ISSUE TITLE
UTF8 characters in Test-URL not handled properly by parse_url()

### ISSUE THREAD

**Issue by SimonSimCity** [symfony/symfony#16776]
To tell the story: I lately updated from 2.4.10 to 2.7.7 and saw some of my tests failing. One of them was a functional test, requesting the URI `/file/protected/Uploaded/2 - English title 2 (ﬁ) здесь.mp3?download=1`.

After some debugging I found the method `Request::create()` containing the method `parse_url()`.

Here are my test-results for that one:

```
php > var_dump(parse_url("http://localhost/2 - English title 2 (ﬁ) здесь.mp3?download=1"));
array(4) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(9) "localhost"
  ["path"]=>
  string(41) "/2 - English title 2 (?_) зде?_?_.mp3"
  ["query"]=>
  string(10) "download=1"
}
php > 
```

Do we expect, that the URI, given by a test, always to be urlencoded? If no, I would like to see the `Symfony\Component\BrowserKit\Client` updated to either warn the user if his URL contains non-ASCII characters or to update the URI to urlencode the URI.

As a usual browser also would update the URI it sends to the server, I would like to see this in the Symfony client as well :wink:

**Comment by seeschloss** [comment]
It works for me, are you sure you are using UTF-8?

**Comment by Tobion** [comment]
Cannot reproduce as well: https://3v4l.org/5hXSH

**Comment by SimonSimCity** [comment]
@seeschloss, @Tobion Could you imagine what setting in PHP could be responsible for that? I just tried it using different PHP versions on both Linux and Mac OS X.

It works, as you said, on Linux though ... but it doesn't on OS X.

Can you please double-check that?

**Comment by nicolas-grekas** [comment]
I think it's related to your locale

**Comment by SimonSimCity** [comment]
@nicolas-grekas Are there different defaults for charsets on OS X and Linux? I called `php -i` on both and compared the outcome: there were some extensions installed on the one that weren't on the other, but nothing related to charsets or locales.

**Comment by seeschloss** [comment]
@SimonSimCity try typing ```locale``` in a terminal?

The variables shown should all say something like en_US.**UTF-8**, otherwise your terminal is probably giving input to PHP in something else than UTF-8. I have no idea what could be the default charset on OS X (and there isn't really a default charset on Linux, it all depends on the choices of your distribution).

Also I don't think anything on PHP's side has control over this.

... And if your locale is *something*.UTF-8 then I have no idea what could be happening.

**Comment by SimonSimCity** [comment]
@seeschloss To proof it's not dependent on the input-locale, I serialized it first:

    var_dump(parse_url(urldecode("http%3A%2F%2Flocalhost%2F2+-+English+title+2+%28%EF%AC%81%29+%D0%B7%D0%B4%D0%B5%D1%81%D1%8C.mp3%3Fdownload%3D1")));

This still returns the reported result on OS X and the expected one on my Linux machine.

On my OS X machine, I have the locale-settings `LC_*="C"` but on the linux machine it's `LC_ALL=en_US.UTF-8`. But also setting all `LC_*` variables to `en_US.UTF-8` didn't help.

**Comment by Tobion** [comment]
Maybe your console cannot display those chars. If you have a reproducible test case you should report the bug to the PHP bug tracker. It's not specific to symfony.

**Comment by SimonSimCity** [comment]
If someone stumbles over this, see: https://bugs.php.net/bug.php?id=52923
