### ISSUE TITLE
Console 3.0.0 - broken formatting when using inherited ProgressBar on PHP 5.6

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/symfony#16781]
This is a manifestation of the following PHP bug: https://3v4l.org/diTRh

We use inherited ProgressBar (to control progress bar output based on verbosity) and on Symfony 3.0.0 and PHP 5.6 this error occurs:

```
Call to private method Symfony\Component\Console\Helper\ProgressBar::getStepWidth()
from context 'MyApp\Console\ConsoleProgressBar'
```

It's because of the following piece of code (in `private static function initPlaceholderFormatters`):

```php
'current' => function (ProgressBar $bar) {
    return str_pad($bar->getProgress(), $bar->getStepWidth(), ' ', STR_PAD_LEFT);
},
```

[As seen on 3v4l](https://3v4l.org/diTRh), this bug only manifests when a descendant of ProgressBar is passed to the anonymous function.

I'm not sure what is the right solution. Maybe the ProgressBar methods called in closures initialized in `initPlaceholderFormatters` should be public.

**Comment by jakzal** [comment]
Why are you extending the progress bar?

**Comment by ondrejmirtes** [comment]
To hide it when the verbosity is under a certain level:

```
class ConsoleProgressBar extends \Symfony\Component\Console\Helper\ProgressBar
{

	/** @var \Symfony\Component\Console\Output\OutputInterface */
	private $output;

	/**
	 * @param \Symfony\Component\Console\Output\OutputInterface $output
	 * @param integer $max
	 */
	public function __construct(\Symfony\Component\Console\Output\OutputInterface $output, $max = 0)
	{
		parent::__construct($output, $max);

		$this->output = $output;
		$this->setFormat($max > 0 ? 'debug' : 'debug_nomax');
	}

	public function display()
	{
		if ($this->output->getVerbosity() >= \Symfony\Component\Console\Output\OutputInterface::VERBOSITY_VERBOSE) {
			parent::display();
		}
	}

	public function finish()
	{
		parent::finish();

		if ($this->output->getVerbosity() >= \Symfony\Component\Console\Output\OutputInterface::VERBOSITY_VERBOSE) {
			$this->output->writeln('');
		}
	}

}

```

**Comment by javiereguiluz** [comment]
> To hide it when the verbosity is under a certain level:

The usual way to solve this would be:

```php
if ($output->isVerbose()) {
    // display the progress bar ...
    $progress = new ProgressBar($output, 100);
    // ...

    // ... and display the new line after finishing the progress bar
    $output->write("\n");
}
```

**Comment by ondrejmirtes** [comment]
Yeah, of course, but I don't want to repeat this code for every command, hence the solution with inheriting ProgressBar and using the inherited class instance.

**Comment by ondrejmirtes** [comment]
But it doesn't worry me anymore because we are on PHP 7 :) So if no one else complains about it, you can close this issue.
