### ISSUE TITLE
Foro

### ISSUE THREAD

**Issue by ebcamps** [symfony/symfony#16787]
I wonder that bundle could be used to create a forum where these issues were of an evaluation are displayed and can comment on these issues.

**Comment by stof** [comment]
This does not belong to the issue tracker of the framework (and btw, it probably already exists)

**Comment by javiereguiluz** [comment]
@ebcamps for this kind of questions to the community, it's better to use any of the alternatives provided in [symfony.com/support](http://symfony.com/support)
