### ISSUE TITLE
Consistency suggestion: empty UploadedFile(multiple) = array with 1 null entry

### ISSUE THREAD

**Issue by appeltaert** [symfony/symfony#16782]
Would be better to keep it just NULL just like a file field without multiple=true, and not an array with 1 NULL entry.
A expected NULL result would make it consistent with testing tools. Right now you need conditional validation just because tests fail without it.

**Comment by stof** [comment]
I don't understand what you mean. Can you provide more details ?

**Comment by appeltaert** [comment]
Sure, for example a simple file field:
```
$builder->add('file', 'file', [
    'multiple' => true,
]);
```
Post it with no files selected and you'll end up with:
```
array (
  0 => NULL,
)
```
While not having multiple=true would result in just ```NULL```

**Comment by stof** [comment]
well, the right output in such case would be ``array()`` though, not ``null``.

**Comment by appeltaert** [comment]
```array()``` would be fine also, since that would evaluate to false, but right now it has 1 entry of NULL. So when testing you need additional tools to make it consistent, since submitting the same form with behat/browserkit driver does give the result of ```NULL```

**Comment by MatTheCat** [comment]
This behavior is definitely weird. Is there any plan to make it consistent?

**Comment by nicolas-grekas** [comment]
Closing as this is old, and it looks like it's been fixed already, see
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/FileType.php

**Comment by MatTheCat** [comment]
Yep https://github.com/symfony/symfony/commit/36b7ba64f4a27c742be010f855d0fb27bfccfb76#diff-0534aa56bada30cd02d85c1dac6ea59b did it.
