### ISSUE TITLE
FileSystem doesn't handle "broken" file_exists()

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#16783]
I'm unable to clear my cache with `console cache:clear` because `file_exists()` returns a wrong value (`false`). So FileSystem can not execute `rmdir` later on because the directory is not empty (because symfony didn't delete the file because it thought it was not there)

https://github.com/symfony/symfony/blob/779833be057b720f2b7ecd4f8a38ace1fd98d828/src/Symfony/Component/Filesystem/Filesystem.php#L157

This happens when the path+filename is 259 characters or longer. See also: http://superuser.com/a/467814

below you can see a test script demonstrating this problem

```php
<?php
$foo = 'D:\\dev\\http\\timey\\app\\cache\\dev_old\\annotations\\72\\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b.doctrinecache.data';
$bar = 'D:\\dev\\http\\timey\\app\\cache\\dev_old\\annotations\\72\\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b315d.doctrinecache.data';
$foo_obj = new \SplFileInfo($foo);
$bar_obj = new \SplFileInfo($bar);
var_dump($foo, file_exists($foo), file_exists($foo_obj));
var_dump($bar, file_exists($bar), file_exists($bar_obj));
```

console:
```
D:\dev\http\tproj>php del.php
string(258) "D:\dev\http\timey\app\cache\dev_old\annotations\72\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e43
6f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b.doctrinecache.data"
bool(true)
bool(true)
string(262) "D:\dev\http\timey\app\cache\dev_old\annotations\72\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e43
6f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b315d.doctrinecache.data"
bool(false)
bool(false)

D:\dev\http\tproj>dir D:\dev\http\tproj\app\cache\dev_old\annotations\72\
 Volume in drive D is Data
 Volume Serial Number is 2E83-BAB4

 Directory of D:\dev\http\tproj\app\cache\dev_old\annotations\72

01-12-2015  15:09    <DIR>          .
01-12-2015  15:09    <DIR>          ..
01-12-2015  15:04                 9 5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c65722367657441
6e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b.doctrinecache.data
01-12-2015  15:01                 9 5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c65722367657441
6e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b315d.doctrinecache.data
               2 File(s)             18 bytes
               2 Dir(s)   7.241.150.464 bytes free
```

I get this problem while upgrading from symfony 2.7 to symfony 2.8
My platform is windows 7 64 bits running PHP 5.6.10

**Comment by flip111** [comment]
For those people who are going to say "unfortunately that's a limitation of running php on windows" .. this can also be "handled" be throwing an appropriate exception

**Comment by ewgRa** [comment]
Can you try "\\?\D:\" instead of "D:\"

?

**Comment by ewgRa** [comment]
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx

and http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows 

more related

**Comment by ewgRa** [comment]
Sorry,  "\\\\?\"

**Comment by flip111** [comment]
you mean `\\?\` right? so in php with escaping that would be `\\\\?\\D:\\blabla`

**Comment by ewgRa** [comment]
You have output, just try this and that. Sorry, I haven't Windows nearby now and can check.

**Comment by flip111** [comment]
I tried this

```php
<?php
$foo = '\\\\?\\D:\\dev\\http\\tproj\\app\\cache\\dev_old\\annotations\\72\\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b.doctrinecache.data';
$bar = '\\\\?\\D:\\dev\\http\\tproj\\app\\cache\\dev_old\\annotations\\72\\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b315d.doctrinecache.data';
$foo_obj = new \SplFileInfo($foo);
$bar_obj = new \SplFileInfo($bar);
var_dump($foo, file_exists($foo), file_exists($foo_obj));
var_dump($bar, file_exists($bar), file_exists($bar_obj));
```

false, false, false, false

**Comment by flip111** [comment]
Here is a workaround using file system functions. Which i think is ugly but better than not working at all ...

```php
$path_info = pathinfo($bar);
$cwd = getcwd();
chdir($path_info['dirname']);
exec('DIR /x', $lines);
foreach ($lines as $line) {
  if (preg_match('/\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}\s+[\d.]+\s(?P<shortname>[^\s]+)\s(?P<longname>.*)/', $line, $regs)) {
    if ($regs['longname'] === $path_info['basename']) {
      exec('DEL '.$regs['shortname']);
    }
  }
}
chdir($cwd);
```

**Comment by Tobion** [comment]
I already provided a bugfix for the underlying problem: https://github.com/doctrine/cache/pull/107
And also tested long UNC (`\\?\`) but it doesn't work with PHP API.

@flip111 I wonder how those long path could be created on your system? Normally it fails when creating those long path in the first place.

**Comment by flip111** [comment]
@Tobion file paths can be longer, but i'm not sure which process of functions created this in the first place. You want me to figure that out? It's nice that you fixed doctrine, still it's a FileSystem issue as well. By the way do you know if there is a php bug filed about this? I searched but couldn't find.

**Comment by Tobion** [comment]
The only thing I could image is that [`$filesystem->rename`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L96) succeeds to rename the cache dir to `..._old` and thus all files that were on the edge of MAX_PATH and then too long. But I'm surprised that renaming a dir succeeds if it results in "invalid" files but renaming a file to a too long path does not work (which I tested in doctrine/cache).

**Comment by Tobion** [comment]
See also #15547

**Comment by Tobion** [comment]
Closing as the original problem is solved. The problem with Long UNC is that they don't work reliably across most filesystem functions. So its hard to use.

**Comment by flip111** [comment]
:-1:  I find this really unintelligible decision to close this issue, where as symfony advertise re-use of components. So that kind of implies that FileSystem can be used with any library other then being called from composer. Secondly Symfony components introduce tons of abstractions and checks on OS and php versions so that the raw functions become easier to use. I'd say just _because_ the native file system functions are hard to use that FileSystem has a great opportunity to actually manage this instead of letting the bug be silent. Have you thought about the burden on the programmer if (s)he has to manually traverse a directory and check UNC length, before passing it of to FileSystem (which will traverse it a second time) ??

**Comment by nicolas-grekas** [comment]
Dealing with extra-long-paths behaviors/bug would add a significant overhead+complexity for an edge case that should instead be avoided.

**Comment by flip111** [comment]
> The art of programming is the art of organizing complexity, of mastering multitude and avoiding its bastard chaos as effectively as possible.

Dijkstra (1970) "Notes On Structured Programming" (EWD249), Section 3 ("On The Reliability of Mechanisms"), p. 7.

**Comment by Tobion** [comment]
@flip111 feel free to make a PR to implement this. And now that we have AppVeyor, you could actually write automated tests to prove that it's working.

**Comment by flip111** [comment]
@Tobion i might consider that if this is marked as an issue. Makes no sense to make a PR for something that is considered a non-issue. In other words: why do a PR when nobody wants this fixed??

By the way i did some investigating on other file system functions.

* `file_exists`, `is_readable`: same problem, just return false without any warning (258 is max length)
* `mkdir`, `filesize`, `touch` give PHP Warnings
* `mkdir` has a maximum of  247 characters which is a bit surprising.
* FileSystem uses a lot of permission related functions `chmod chgrp fileperms` which don't work on windows, i assume it's a no-op

Anyway the only real issue seem to be `file_exists` and `is_readable` because the rest is not silent or not relevant.

**Comment by flip111** [comment]
I just got confirmation from laruence that php does dead code elimination. So for this issue that would mean if you branch code bases on a bunch of constants (or expressions that evaluate to a constant) then you don't pay any performance penalty for the branch check. So since this concerns windows, other OSses should not suffer from the extra added code. @nicolas-grekas not sure if you meant that with overhead, or if you were referring to extra lines of code

**Comment by nicolas-grekas** [comment]
I meant both... If perf is not impacted on non-Windows that's great. But for example calling exec() is really risky: it opens potential doors to command line injections. I'm e.g. really not confident in escapeshellargs being safe on Windows (see how we wrap this function in the Process component).
If you want to try a PR that is properly tested and does not make the full class unreadable just for dealing with this edge case, please do :) But if you thing you have better to do, I'd personally be fine with it :)

**Comment by flip111** [comment]
@nicolas-grekas i don't feel confident enough to use `exec()` so i will try to do a PR based on throwing an exception as suggested in [my second comment](https://github.com/symfony/symfony/issues/16783#issuecomment-160987976). By the way, don't understand your last sentence ...

**Comment by nicolas-grekas** [comment]
An exception looks fine to me!

**Comment by flip111** [comment]
Reported https://bugs.php.net/bug.php?id=71103

**Comment by weltling** [comment]
May i as everyone interested to check https://github.com/php/php-src/pull/1854? The Windows builds are linked in the description. Though be aware that the path segment limitation still persists, even if long path is supported.

Thanks.

**Comment by flip111** [comment]
@weltling tested with same script and directory/file structure as in https://bugs.php.net/bug.php?id=71103 (except that D drive is now C drive) with php version from http://windows.php.net/downloads/snaps/ostc/win_mb_path_w_onlly/2016-05-28/php-7.1.0-dev-Win32-VC14-x64.zip the bug as reported on php.net seems resolved, output:

```
string(258) "C:\dev\http\tproj\app\cache\dev_old\annotations\72\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b.doctrinecache.data"
bool(true)
bool(true)
string(262) "C:\dev\http\tproj\app\cache\dev_old\annotations\72\5b53796d666f6e795c42756e646c655c5477696742756e646c655c436f6e74726f6c6c65725c457863657074696f6e436f6e74726f6c6c657223676574416e64436c65616e4f7574707574427566666572696e67405b416e6e6f745d5d5b315d.doctrinecache.data"
bool(true)
bool(true)
```

Did not test `is_readable`

**Comment by weltling** [comment]
@flip111 great! I've added this to the tests in the patch https://github.com/weltling/php-src/blob/win_mb_path_w_only/ext/standard/tests/file/windows_mb_path/test_long_path_bug71103.phpt . TS should be fine here as well. If you have some more test cases, please let me know.

Thanks a lot!
