### ISSUE TITLE
Validator ApcCache in Symfony 3

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#16793]
The class `Symfony\Component\Validator\Mapping\Cache\ApcCache` had been remove in Symfony 3.

But the service still exists: https://github.com/symfony/symfony/blob/3.0/src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.xml#L31
And it's still the default (commented) value in Symfony SE: https://github.com/symfony/symfony-standard/blob/master/app/config/config_prod.yml#L6

**Comment by ogizanagi** [comment]
Good catch !
It should be fixed in the above PR.
