### ISSUE TITLE
{% form_type my_form _self %} with Twig 1/2

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#16804]
The `_self` keyword was deprecated/removed in Twig 1/2. What's the proper way to write the following code?

```html+jinja
{% form_theme my_form _self %}
```

The docs say:

> As of Twig 1.x, the _self global variable is deprecated except for usage in the from and the import tags. In Twig 2.0, _self is not exposed anymore but still usable in the from and the import tags.

The `form_theme` tag is not in that list (naturally, as its not a core Twig feature).

**Comment by dosten** [comment]
Actually I use the template name instead of _self. `{% form_theme my_form "AppBundle::index.html.twig" %}`

**Comment by stof** [comment]
@webmozart you can indeed pass the template name rather than the Twig_Template instance. I just opened an issue on Twig to add a new special variable giving the name of the current template only (giving the Twig_Template instance had security implications, which is why it is deprecated)

**Comment by fabpot** [comment]
This one can be closed as `_self` has been un-deprecated now.
