### ISSUE TITLE
3.0.0 cache:clear still not works

### ISSUE THREAD

**Issue by bschmithuysen** [symfony/symfony#16808]
Hey,

the console command cache:clear throws an exception cause of to long file names under windows.

    php bin/console cache:clear

throws

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Warning: file_get_contents(C:\PhpStormProjects\Test\var\cache\de_\annotations\d3\5b53796d666f6e795c42756e646c655c4672616d65776f726b42756e646c655c436f6e74726f6c6c65725c436f6e74726f6c6c65722363726561746541636365737344656e696564457863657074696f6e405b416e6e6f745d5d5b315d.doctrinecache.data): failed to open stream: Invalid argument

Is there a solution?

**Comment by ewgRa** [comment]
I think it is same problem as in #16783 or https://github.com/symfony/symfony/pull/15547
