### ISSUE TITLE
[3.0.0] [gitignore] Could not open input file: app/console

### ISSUE THREAD

**Issue by jpyzio** [symfony/symfony#16815]
After "git clone" project (Symfony 3) and type "composer install".

```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
[...]
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): 
[...]
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
  Could not open input file: app/console                                     
  .                                                                          
                                                                             
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]
```
In: vendor/sensio/distribution-bundle/Composer/ScriptHandler.php:464 function "is_dir($options['symfony-var-dir'])" returns false, because when  method "clearCache" is executed, directory "var" in project is not exist and composer try execute app/console instead bin/console.

The problem is in symfony default .gitignore file. It adds "/var" and all of subdirectories to ignore. After cloning the repository above method can not work properly.

After fix it, composer can not find "bin/console" file, it is ignored too. 

Resolve:

```
# .gitignore
/app/config/parameters.yml
/build/
/composer.phar
/vendor/
/web/bundles/
/var/bootstrap.php.cache
/var/SymfonyRequirements.php
/var/cache/*
!/var/cache/.gitkeep
/var/logs/*
!/var/logs/.gitkeep
/var/sessions/*
!/var/sessions/.gitkeep
/phpunit.xml
```

Example:
Clone this default project:
git clone https://github.com/jpyzio/symfony3-demo && cd symfony3-demo && composer install

**Comment by Tobion** [comment]
You're not using the correct gitignore that comes with v3.0.0. See #863

**Comment by arrgson** [comment]
I don't think that is the problem ...

I install using the symfony installer (installs 3.0.0). Commit to git. Clone on another computer. Run composer install and I get the same problem. .gitignore includes "/bin/" which it shouldn't anymore. So ... yes, it's the "incorrect" .gitignore, but it is the one created by "symfony new ...".

**Comment by Tobion** [comment]
Please report to https://github.com/symfony/symfony-installer then

**Comment by Tobion** [comment]
https://github.com/symfony/symfony-installer/issues/211
