### ISSUE TITLE
Add Yaml::parseFile() as short for Yaml::parse(file_get_contents())

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony#16817]
Most examples in the documentation describe Yaml::parse(file_get_contents(...)) or $yaml->parse(file_get_contents(...)) and not a Yaml::parse('') or $yaml->parse(''). I think it is the most used way and for readability of code implementing this a parseFile method, calling file_get_contents internally, could be added. I'm happy to create a PR for this.

**Comment by SenseException** [comment]
Using a file path in `Yaml::parse()` got deprecated for a reason. Adding a new method just for using a file name would only be a convenience.

**Comment by fabpot** [comment]
:-1: from me. I prefer simple primitives that allow any usages instead of adding specific methods.

**Comment by Tobion** [comment]
As said, passing a filename was removed because it violates single-responsibility.
