### ISSUE TITLE
Security - Using a Custom Query to Load the User does not work

### ISSUE THREAD

**Issue by itrascastro** [symfony/symfony#16811]
Symfony 3.0
PHP 5.6.11
Mac OS
PHP Built in webserver

I am following this part of the documentation: 

http://symfony.com/doc/current/cookbook/security/entity_provider.html#using-a-custom-query-to-load-the-user

to enable authentication with a custom query.

So I remove the 'property' entry at 'security.yml' file. And I take this message when I try to login:

"Authentication request could not be processed due to a system problem."

Same code worked for me in symfony 2.7.7. Same Entity, same entity repository ...

If I use 'property: username' it works.

This works:

    providers:
        db_users:
            entity:
                class: AppBundle:User
                property: username

This does not work:

    providers:
        db_users:
            entity:
                class: AppBundle:User

My code:

https://github.com/itrascastro/Symfony-Classroom-3.0/tree/session-4-security

**Comment by stof** [comment]
The doc has not yet been updated for 3.0 here. There has been a change here (and 2.8 would have triggered a deprecation warning telling you about it).

**Comment by stof** [comment]
hmm, the UPGRADE-2.8.md file misses a bunch of deprecations though

**Comment by itrascastro** [comment]
Can you please tell me how I have to proceed to enable authentication with a custom query?

**Comment by stof** [comment]
implement ``Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface`` instead in your repository (which is simpler as it avoids defining other methods never used by the EntityUserProvider).
2.8 supports both ways, but 3.0 only supports the new way

**Comment by itrascastro** [comment]
Thank you, it works perfect and the code is now more clean

**Comment by xabbuh** [comment]
FYI, the docs will be fixed soon too (see symfony/symfony-docs#5993).

Anyway, closing here as there is nothing wrong with the code.
