### ISSUE TITLE
[Config] Some NodeDefinition::cannotBeEmpty() should throw an exception

### ISSUE THREAD

**Issue by Ener-Getick** [symfony/symfony#16812]
Several  ``NodeDefinition::cannotBeEmpty()`` has been deprecated in #15170 in favour of [throwing an exception](https://github.com/symfony/symfony/pull/15170#issuecomment-119538615) in 3.0.
These deprecations have been removed in #15685 but the exceptions haven't been added.

So my question is: Is it too late to add them in 3.0 ?

**Comment by stof** [comment]
they should be added IMO (otherwise the 2.8 deprecation does not make sense).

@fabpot @nicolas-grekas what do you think ?

**Comment by nicolas-grekas** [comment]
I guess yes.
@Ener-Getick can you do a PR again branch 3.0 please?

**Comment by Ener-Getick** [comment]
Sure I'll do that in a few minutes.

**Comment by Ener-Getick** [comment]
Done, see #16816
