### ISSUE TITLE
[WEB PROFILER] - Debug bar z-index conflict

### ISSUE THREAD

**Issue by nicovak** [symfony/symfony#16824]
The new debug bar z-index property enters in conflict with twig `dump` function.

The class `.sf-dump` has a z-index of `100000` and the `.sf-toolbarreset` has a z-index of `99999`
The `.sf-dump` should have `99998` or below.

**Comment by egogarcia** [comment]
To reproduce:

Create a new 2.8 project with the installer. On the demo application, add some top margin (ex: 500px), and scroll the page down, to see the var_dump show over the debug bar. Below, is a picture example

<img width="1275" alt="captura de pantalla 2015-12-05 a les 10 26 36" src="https://cloud.githubusercontent.com/assets/1496402/11607112/d7d26ad8-9b3a-11e5-91fa-a8593ac02eb2.png">
