### ISSUE TITLE
[Validator] UniqueEntity constraint with multiple entity manager

### ISSUE THREAD

**Issue by CharlyPoppins** [symfony/symfony#16833]
Hi,

I just found out that UniqueEntity was not working on the planned entity manager.

Unfortunately I can't hardcode it in my entity cause it's subject to change
´´´
@UniqueEntity("code", em="myManager", repositoryMethod="testUniqueEntity")
´´´ 

How can I solve my problem ?

**Comment by iltar** [comment]
Hello @CharlyPoppins, can you check [the support page](http://symfony.com/support) to see what the best way is to ask your questions? This is not really an issue related to the framework and I'm pretty sure that people on StackOverflow or IRC can help you further.

> sorry for the lazy copy-paste

**Comment by CharlyPoppins** [comment]
I've already spent jours wandering on every topic about **@UniqueEntity**, on http://api.symfony.com/2.7/ and http://www.doctrine-project.org/api/orm/2.2/ 
I've have no clue of where I can find answers :s

**Comment by jakzal** [comment]
@CharlyPoppins sorry you can't find help, but we're not using github for support questions. It's already hard to cope with the number of issues we've got open.

**Comment by CharlyPoppins** [comment]
Hi again,
after looking everywhere fr a solution / functionality, I thought maybe it's just a bug.
Here's an example of my code that exposte the strange behaviour :
I'm working on entity **Test** which entity manager "em3" then during validation method  **testUniqueEntity** the entity manager is "em1"

```
* @UniqueEntity("code", repositoryMethod="testUniqueEntity")
```

```
public function testUniqueEntity($params) {
    $em = $this->getEntityManager();
    //var_dump($em->getConnection()->getDatabase()); => display "em1"
    $qb = $this->createQueryBuilder('p')
    ->andWhere('p.code = :code')
    ->setParameter('code', $params["code"])
    ->andWhere('p.deletedAt IS NULL');
    return $qb->getQuery()->getOneOrNullResult();          
}
```
