### ISSUE TITLE
Use Apcu_fetch instead of apc_fetch

### ISSUE THREAD

**Issue by layanto** [symfony/symfony#16830]
Since minimum supported PHP for Symfony 3 is 5.5.9, maybe time to use apcu_fetch instead of apc_fetch. This way no need to enable APC backward compatibility mode with Apcu as APC does not exist for PHP 5.5 anyway. Especially with PHP 7, APC backward compatibility in Apcu is not enabled by default.

**Comment by Tobion** [comment]
The only non-deprecated class using APC is `ApcClassLoader`.
I think we could also deprecate all those cache specific class loaders and instead provide a ?`DoctrineCachedClassLoader` similar to what we did for `validator.mapping.cache.apc`. See discussion in #16822

Then it's only a mapper of also adding a `ApcuCache` in https://github.com/doctrine/cache

**Comment by layanto** [comment]
Good idea to deprecate this and  use Doctrine Cache instead. There already is a PR on this for Doctrine Cache.

https://github.com/doctrine/cache/pull/112#commits-pushed-f45ed2f

**Comment by catch56** [comment]
I don't see any mention of the classloader in https://github.com/symfony/symfony/pull/16822, and for me at least, it's important to keep the classloader and actual cache systems separate - the classloader is required long before the container is available.

**Comment by nicolas-grekas** [comment]
Fixed by #17358
