### ISSUE TITLE
[monolog-bridge] 2.8 allows http-kernel 3.0 but uses interface that has been removed

### ISSUE THREAD

**Issue by anlutro** [symfony/symfony#16837]
The package `symfony/monolog-bridge` in version 2.8 has [a requirement for `symfony/http-kernel ~2.4|~3.0.0`](https://github.com/symfony/monolog-bridge/blob/5c4494db50c038642581f69c106c33e525c638ec/composer.json#L23), but it [uses](https://github.com/symfony/monolog-bridge/blob/2.8/Logger.php#L15) [an interface](https://github.com/symfony/http-kernel/blob/d2c7a898299aede828379907d4a222f04d68d007/Log/LoggerInterface.php) that has been removed in 3.0.

As far as I can tell, either the version constraint should be fixed, or [this commit](https://github.com/symfony/symfony/commit/0fa072c859f6197f498ed096dcbef2eaa2267a2d) should be backported into 2.8.

**Comment by Tobion** [comment]
The commit cannot be backported to 2.8 as it would be a bc break. So the other solution seems right.

**Comment by derrabus** [comment]
I've submitted a PR that fixes the composer.json file. But we should probably add a test that actually instantiates the `Symfony\Bridge\Monolog\Logger`.
