### ISSUE TITLE
[web-profiler-bundle] [DX] Toolbar ajax should show the request from top to button

### ISSUE THREAD

**Issue by AlmogBaku** [symfony/symfony#16831]
When you make an ajax request, the most recent request is showed on button- which is a bit confusing.

### Steps to reproduce
1. Do dozens of request using ajax
2. Take a look on the ajax tool in the web-profiler-toolbar

### Results
You need to scroll down in order to see your recent request. But you can get confused and click on the first one.

### Expected results
Most recent request should show on top.

**Comment by apfelbox** [comment]
Big :+1:

**Comment by tgabi333** [comment]
What if the order remains the same, but after you open the list its scrolled down (and if a new row appended it scrolls down again to see the latest), so this way the last ajax call will be closer to your mouse.

**Comment by felipsmartins** [comment]
+1

**Comment by erickr** [comment]
@tgabi333 Would be doable, the request id could be used as an html anchor, assuming all requests on the profile-page have one defined.
