### ISSUE TITLE
Debug Symfony\Component\Validator\Constraints

### ISSUE THREAD

**Issue by CharlyPoppins** [symfony/symfony#16832]
Hi,

is there a way to display every entities and fields that have a constraint ?

So I can check if there is no misconfiguration betwwen validator.yml and Symfony\Component\Validator\Constraints in entity file.

**Comment by iltar** [comment]
Hello @CharlyPoppins, can you check [the support page](http://symfony.com/support) to see what the best way is to ask your questions? This is not really an issue related to the framework and I'm pretty sure that people on StackOverflow or IRC can help you further.

**Comment by CharlyPoppins** [comment]
Yes, I'm going to check on StackOverflow.
