### ISSUE TITLE
Errors wrong expected argument using Symfony3 with generators

### ISSUE THREAD

**Issue by Krazitchek** [symfony/symfony#16845]
While using Form in Symfony3, using entity (Operation here) and crud generator, Form does not render and "Expected argument of type "string", "Eclp\Bundle\CCBBundle\Form\OperationType" given" appear.

I don't know if it is an issue or my mistake. While i use Symfony generator and write no code, i think it should work !

**Comment by jzawadzki** [comment]
Can you post what command do you run exactly and how your entity looks like?

**Comment by Krazitchek** [comment]
I just download Symfony3 and create, using generators (doctrine:generate:entity and doctrine:generate:crud) an entity (Operation) and crud stuffs.

My test entity (Operation) have only one field (name,string) (and id of course).

The i call in browser the route for creation an operation (Operation entity)... and i got the error.

"Expected argument of type "string", "Eclp\Bundle\CCBBundle\Form\OperationType" given"

**Comment by xabbuh** [comment]
These commands are part of the [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle). Please check the bug tracker over there and report it there if it isn't an already known issue.
