### ISSUE TITLE
Command debug:config ignores environment parameter

### ISSUE THREAD

**Issue by benr77** [symfony/symfony#16867]
When I try `debug:config BundleName` it dumps the config for that bundle. Very useful.

However, it ignores any environment parameter specified, so if I execute `debug:config BundleName -e test` then I still get the configuration from the default `dev` environment.

The environment option is specified when you run `debug:config --help` etc

It would be hugely useful for this command to be able to parse the configs for specified environments.

**Comment by rmed19** [comment]
Hi @benr77, I can see any problem with sf 2.8 : 
~$ php app/console debug:config WebProfilerBundle -e dev

Current configuration for "WebProfilerBundle"
=============================================

web_profiler:
    toolbar: true
    intercept_redirects: false
    position: bottom
    excluded_ajax_paths: '^/(app(_[\w]+)?\.php/)?_wdt'

~$ php app/console debug:config WebProfilerBundle -e test

Current configuration for "WebProfilerBundle"
=============================================

web_profiler:
    toolbar: false
    intercept_redirects: false
    position: bottom
    excluded_ajax_paths: '^/(app(_[\w]+)?\.php/)?_wdt'

**Comment by benr77** [comment]
Looking at this further I agree - testing on 2.7.7 I can see differences between environments... So looks like no bug.

Thanks for checking!
