### ISSUE TITLE
Add hasToken() to AuthorizationChecker

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16878]
I think we should add ``hasToken()`` to ``AuthorizationChecker``.

This code would be needed in ``AuthorizationChecker``:
```php
public function hasToken() {
    return (null === ($token = $this->tokenStorage->getToken()));
}
```

**Reason / Usage:**
I like to redirect an user to route ``x`` if:
1. the user is logged in,
2. and the user is not already on route ``x`` (prevent recursion),
3. and the user has not done ``y`` (any special case).

In my event listener I use this code:
```
if (!$this->authChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
   return;
}
```

If I try to access the Symfony profiler I'll get this error:
```
The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.
```

I think catch the ``AuthenticationCredentialsNotFoundException`` is not the best solution. My code should check if the tokenStorage contains a token. That because I need to inject the TokenStorage.

**It would be less code if the ``AuthorizationChecker`` would have a ``hasToken()`` function to check if calling ``isGranted()`` is allowed.**

**Comment by stof** [comment]
adding this to the AuthorizationCheckerInterface does not make sense IMO. This is not the responsibility of the AuthorizationCheckerInterface.

Thus, adding a method in this interface cannot be done before Symfony 4 (it is a BC break)

**Comment by JHGitty** [comment]
@stof How would you handle it? Would you catch the exception or would you inject the ``tokenStorage``?

**Comment by sstok** [comment]
You can create your own access-voter to handle these special cases.
http://symfony.com/doc/current/cookbook/security/voters.html

**Comment by JHGitty** [comment]
@sstok Could you explain this a little bit?
``isGranted()`` directly throws an ``AuthenticationCredentialsNotFoundException`` if there is no token.

How would you handle my issue with own access voters?

**Comment by WouterJ** [comment]
So inject the token storage and check if token is available in your custom code.

**Comment by umpirsky** [comment]
In 3.4.0 new `security.helper` service that is an instance of `Symfony\Component\Security\Core\Security` is added and provides shortcuts for common security tasks.
