### ISSUE TITLE
Symfony3.0 unable to generate absolute URL within Controller

### ISSUE THREAD

**Issue by rvaliev** [symfony/symfony#16879]
The following code in controller generates Relative URL, however corresponding to documentation it should generate an Absolute:

```
$absolute_url = $this->generateUrl(
            'luckynumber',
            array('count' => 4),
            true
);
```
So the result is: /app_dev.php/lucky/number/4 

Tested the same block of code on Symfony2.7.6 and it worked as it should be:
http://symfony2.app/app_dev.php/lucky/number/4 

BTW. Twig in Symfony3.0 generates absolute URL just fine:
```
{{ url('luckynumber', {'count': 4}) }} 
```

So the result is: http://symfony3.app/app_dev.php/lucky/number/4

**Comment by Tobion** [comment]
You must use the `UrlGeneratorInterface` constants instead of passing a boolean to `generateUrl`. You get a deprecation warning for this in 2.8. If the documentation is wrong at some place, please open a ticket on symfony/symfony-docs.

**Comment by JuliusKoronci** [comment]
Hi, I am using the UrlGeneratorInterface and still the path is relative
