### ISSUE TITLE
YAML PHP object tag property specification is incorrect

### ISSUE THREAD

**Issue by koenpunt** [symfony/symfony#16877]
I came to notice that the tag property for php objects in the YAML parser/dumper is `!!php/object` which, according to the spec, means `tag:yaml.org,2002:php/object`, which in turn is incorrect because `php` isn't a actual type represented by YAML.

So I think it should be a local `!php/object` (single exclamation, local tag), which conveniently enough matches with the [php-yaml extension](https://secure.php.net/manual/en/ref.yaml.php) (LibYAML wrapper).

Excerpt from ref: http://yaml.org/refcard.html
```
Tag property: # Usually unspecified.
    none    : Unspecified tag (automatically resolved by application).
    '!'     : Non-specific tag (by default, "!!map"/"!!seq"/"!!str").
    '!foo'  : Primary (by convention, means a local "!foo" tag).
    '!!foo' : Secondary (by convention, means "tag:yaml.org,2002:foo").
    '!h!foo': Requires "%TAG !h! <prefix>" (and then means "<prefix>foo").
    '!<foo>': Verbatim tag (always means "foo").
```

**Comment by xabbuh** [comment]
Such a change sounds reasonable to me. Parsing and dumping `!php/object` could be done as a bugfix while we would have to deprecate parsing `!!php/object` in 3.1 so that we can drop support for it in 4.0.
