### ISSUE TITLE
Deprecated class on TwigBundle

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#16872]
Hello,

I have been updating my vendors recently, and SensioLabs Insight has reported me that there are 1 deprecated class on `TwigBundle`. Given this is an updated vendor, I presume (from my humble point of vire) it should not be tagged as `@deprecated` or it should not be checked on SensioLabs Insight if that class will be removed on next TwigBundle release.

This is the error reported by SensioLabs Insight:

> `Info` `Architecture`
> 
> The `846826759222eeac8b8b34e803951c07468c406717a71aa7cd45edcdf3463c61_55` service uses the `Symfony\Bundle\TwigBundle\Extension\ActionsExtension` class, which has been deprecated in Symfony 2.2.

Cheers,

**Comment by Tobion** [comment]
It looks like the error report from sensio labs insight is wrong. The `ActionsExtension` is deprecated indeed, but it is only added automatically in the TwigBundle for BC. So the depreaction is only triggered if you actually use the `{% render %}` tag in your templates. So just instantiating the ActionsExtension does not and should not be reported as problem. Please open an issue on SensioLabs Insight.

**Comment by DavidGarciaCat** [comment]
Hi Tobias,

Many thanks for your tip. I'm going to open a ticket, as you have suggested.

Cheers,

**Comment by DavidGarciaCat** [comment]
Hey,

Just to keep you tu to date: this is the SensioLabs Insight answer about this case I posted here:

---

Hello David,

Removing this violation programmatically is not really possible, as we can't determine in an automatic way if this service is a vendor one or yours.

But you can easily just ignore the violation.

Best regards,

**Comment by tvlooy** [comment]
If you really want to get rid of it you could overwrite the service. Eg:

services.yml
```
services:
    twig.extension.actions:
        class: AppBundle\DependencyInjection\NullTwigService
```
AppBundle\DependencyInjection\NullTwigService.php
```
<?php

namespace AppBundle\DependencyInjection;

class NullTwigService implements \Twig_ExtensionInterface
{
    /**
     * {@inheritdoc}
     */
    public function initRuntime(\Twig_Environment $environment)
    {}

    /**
     * {@inheritdoc}
     */
    public function getTokenParsers()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getNodeVisitors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getFilters()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getTests()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getFunctions()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getOperators()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getGlobals()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'deprecated';
    }
}
```

Tested and works with SensioLabs Insights.

**Comment by DavidGarciaCat** [comment]
Hi Tom,

Many thanks for your message.
I'm going to try this update. Hope it helps my SensioLabs Insight checks.

Cheers,
