### ISSUE TITLE
[3.0] [Security] Security component depends on random_bytes function, which was introduced in PHP 7.0

### ISSUE THREAD

**Issue by OJezu** [symfony/symfony#16884]
https://github.com/symfony/security/blob/master/Csrf/TokenGenerator/UriSafeTokenGenerator.php#L48

I have polyfill-php70 installed. It does not help.

![screenshot from 2015-12-07 14 44 37](https://cloud.githubusercontent.com/assets/3941091/11628353/6e9a27a0-9cf1-11e5-8a27-8210c7a4ecea.png)

**Comment by xabbuh** [comment]
As you apparently do not use the Symfony Standard Edition are you sure that you properly set up the autoloading of the installed dependencies?

**Comment by stof** [comment]
the ``random_bytes`` polyfill is not part of ``symfony/polyfill-php70`` itself, but provided by ``paragonie/random_compat`` (which is a dependency of ``symfony/polyfill-php70``).
If you don't use composer, make sure to install it and to load the necessary files.

**Comment by nicolas-grekas** [comment]
In fact, symfony/polyfill-php70 requires paragonie/random_compat so it should be loaded

**Comment by OJezu** [comment]
I have psr4 and psr0 autoloader that serves composer installed classes. (Due to working with legacy code, I cannot use full composer autloader)

It seems that the issue is due to my autloader not including files listed in `autoload_files.php`.

**Comment by stof** [comment]
@OJezu why couldn't you use the Composer ClassLoader for all classes installed by Composer ? This would not forbid to register another autoloader for your legacy code, and would simplify your code by avoiding to duplicate the composer configuration system.

**Comment by OJezu** [comment]
@stof We quickly tried that approach some time ago, but had problem with it. Our legacy code is using `__autoload` function and we had not earlier checked that if we use a function registered with `spl_autoload_register` instead, we can have both autloaders. I've just checked that, and it works, so I've switched to using composer's autoload. Thanks for your advice.

**Comment by nicolas-grekas** [comment]
Could be closed then?

**Comment by OJezu** [comment]
Yeah, I closed it already.
