### ISSUE TITLE
[2.8][WebProfilerBundle] Profiler doesn't render correctly in Microsoft Edge

### ISSUE THREAD

**Issue by zangai** [symfony/symfony#16887]
<img width="745" alt="symfony_profile28" src="https://cloud.githubusercontent.com/assets/1556962/11631041/82b3d1aa-9d00-11e5-95ba-0ceffd135c8b.png">

user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Comment by javiereguiluz** [comment]
I don't have access to the Microsoft Edge browser. Could any Windows user please help us here? My guess is that this will be an easy fix. Thanks!

**Comment by derrabus** [comment]
@javiereguiluz You can try Microsoft's VM for testing with Edge: https://dev.windows.com/en-us/microsoft-edge/tools/vms

**Comment by javiereguiluz** [comment]
@derrabus sadly this is a 5GB download. Too much for me. Sorry.

**Comment by emil-nasso** [comment]
If no one does it before me, i will look into this this weekend. :)
