### ISSUE TITLE
[3.0][WebProfilerBundle] Ajax toolbar block not showing up

### ISSUE THREAD

**Issue by mpiecko** [symfony/symfony#16880]
I installed a fresh Symfony 3 project on a Debian Jessie release (PHP 5.6) with
```
symfony new Symfony3
```
I noticed that the Ajax toolbar block is not showing up. I also noticed, that the twig template with the "sf-toolbar-block-ajax" block is not even injected:

![image](https://cloud.githubusercontent.com/assets/209899/11626311/0c36b010-9ce2-11e5-8060-14df1ccea34b.png)
![image](https://cloud.githubusercontent.com/assets/209899/11626353/6172fe76-9ce2-11e5-8cb3-e879660d7dcb.png)

I'm not sure if this is related, but the DB icon is also missing, although the DB panel is available:

![image](https://cloud.githubusercontent.com/assets/209899/11626390/a01f64a2-9ce2-11e5-9a75-a35bb6e095f2.png)
![image](https://cloud.githubusercontent.com/assets/209899/11626450/41d1b0c0-9ce3-11e5-94d2-a9d6b8b50e86.png)

Michael

**Comment by jelte** [comment]
I think the Ajax toolbar only shows after executing an actual ajax call ( atleast that's what I noticed )

**Comment by javiereguiluz** [comment]
@jelte that's right: if there are no Ajax calls, you won't see that panel.

@mpiecko about the "ghost Doctrine panel", I need to investigate the issue further.

**Comment by mpiecko** [comment]
Thanks @javiereguiluz, but i tested it with Angular, and it worked fine with Symfony 2.8. The problem is: everything works, i see all the requests in the profiler. The only thing that doesn't work is the ajax block inside the debug bar. 

And, more importantly, i see that the JavaScript block for tracking the ajax requests is there - but there is no "sf-toolbar-block-ajax" markup block (see my screenshot). So the call form the ajax handler with
```
var ajaxToolbarPanel = document.querySelector('.sf-toolbar-block-ajax');
```
leads to nowhere. My understanding is that the markup should be there, even if no ajax is performed. But it isn't. So it won't show up if an ajax call is triggered later.

Cheers,
Michael

**Comment by NothingWeAre** [comment]
it seems that there no declaration for Ajax collector in 
/FrameworkBundle/Resources/config/collectors.xml

i have created pull request, but this is my first pull request on github so i may have made some mistakes.
https://github.com/symfony/symfony/pull/16953

**Comment by mpiecko** [comment]
Can confirm, this fixed it. Thanks!
