### ISSUE TITLE
[PropertyInfo] Implement Naming Strategy for Properties

### ISSUE THREAD

**Issue by zanderbaldwin** [symfony/symfony#16889]
The [`ReflectionExtractor`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php) sees a public property as separate from its accessor/mutator methods. For example:

```php
class Website
{
    public $domainName;
    public $author;

    public function getDomainName()
    {
        return $this->domainName;
    }

    public function getAuthor()
    {
        return $this->author;
    }
}

var_dump($reflectionExtractor->getProperties());
/*
array (size=4)
  0 => string 'domainName' (length=10)
  1 => string 'author' (length=6)
  2 => string 'DomainName' (length=10)
  3 => string 'Author' (length=6)
*/
```

The easiest fix would be to lowercase the first letter of the property name determined from a method, though this would cause problems with properties that actually do start with an uppercase letter.

Keeping in mind that it's likely that this component will be used in conjunction with the PropertyAccess component, would it be suitable for a naming strategy to be added (the most obvious being the underscore naming strategy used in both PropertyAccess and Doctrine)?

/cc @dunglas

**Comment by dunglas** [comment]
It's definitely a bug. The first letter must be lower cased.

About the naming strategy, why not adding support for snake_case because as you pointed out it exists in PropertyAccess. But IMO it's better to have be coherent between these 2 components: support only camelCase/snake_case for both or a support for custom strategies for both.

**Comment by zanderbaldwin** [comment]
`snake_case` for PropertyInfo it is. It would be nice to implement naming strategies in both components for edge cases eventually, but I don't see it as a priority.

However, a basic property name transformer might be a good idea to maintain consistency across extractors.

**Comment by iltar** [comment]
Currently doctrine does not fully support snake-case properties: https://github.com/doctrine/collections/pull/29

**Comment by zanderbaldwin** [comment]
Good point.

It's probably best that the component does not take on the role of dictating naming conventions, especially since PSRs actively avoid taking a stance on such issues.

How about implementing a closest-match property name transformer to match identifiers to the correct class properties/methods?

| Identifier | Attempt (in order) |
|---|---|
| `first_name` | `$first_name`, `$firstName`, `{prefix}First_name()`, `{prefix}FirstName()` |
| `firstName` | `$firstName`, `{prefix}FirstName()` |
| `FirstName` | `$FirstName`, `$firstName`, `{prefix}FirstName()` |

To return a property identifier, return class properties as-is and lowercasing the first letter of those determined from class methods. There won't be any issue of which naming convention (`snake_case`, `camelCase`, `StudleyCaps`, etc) is used since the transformer will always choose the property/method closest to the identifier.

Trying to support naming strategies would result in compatibility and support nightmares. There are just too many possible ways for it to go wrong, especially if a mix of naming conventions were used within the same class.

```php
interface PropertyNameTransformerInterface
{
    /**
     * @param string $property
     * @return string
     */
    public function sourceToIdentifier($property);

    /**
     * @param string $name
     * @return string
     */
    public function identifierToSource($name);
}
```

Only issue is how to change the public API of the extractors to ensure each one gets this new property name transformer.

**Comment by zanderbaldwin** [comment]
**Edit;** the more I think about this the more I want to just lowercase the first letter...

The PropertyAccess component already maps identifier strings to the correct property/method, why include it in PropertyInfo which is such a small component in comparison? It's an unnecessary overhead, especially where multiple properties/methods exist with only capitalisation differences.

Compatibility with the PropertyAccess component needs to improve in the future but I don't think a naming strategy is the way to go IMO.

---

- Property names get returned as-is.
- For methods, strip the prefix and (unless a property with exactly the same capitalisation exists) lowercase the first letter.
  - In the reverse, capitalise the first letter and prepend the prefix.

Simple and effective. Thoughts?
