### ISSUE TITLE
Why are these "sigchild"-related things in place in Process?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#16888]
I'd like to ask for some pointers about the special handling of `--enable-sigchild` php in the Process component.
I'm currently trying with such a php, I'm able to reproduce https://bugs.php.net/25727 , but not when using proc_open.
Do we really need these hacks? Can someone give me sample tests / reports?

**Comment by xabbuh** [comment]
@nicolas-grekas The only thing I can tell you that all tests from the dedicated test class where failing for me when I worked on a bug fix on the past and tried to execute it with a PHP environment that was not compiled with the desired flag. Not sure if that is of any help for you, but you can start by compiling PHP that way and try to reproduce this behaviour (if that isn't what you are actually talking about, in that case we might need to compare envs in more detail).

**Comment by romainneutron** [comment]
See the original PR https://github.com/symfony/symfony/pull/5353 

> PHP compiled with --enable-sigchild basically fails to return exit codes, and randomly returns -1 instead most of the time (see https://bugs.php.net/bug.php?id=29123).

> This works around it by having the exit code going through another pipe. It's enabled by default for linux because the new pipe trick won't work on windows I think, but that's unlikely to be an issue because most people don't compile their own php there.
> 
> I could have it enabled only when sigchild is enabled using the code below, but obviously that adds some overhead, so I'm not sure what's worst.

And the second one that enabled the compatibility flag https://github.com/symfony/symfony/pull/5543

**Comment by romainneutron** [comment]
And the actual PHP bug is https://bugs.php.net/bug.php?id=29123
