### ISSUE TITLE
[doctrine-bridge] Missing iconv requirement

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#16883]
On systems without `iconv` installed packages installs but crashes with following error:
![screenshot 2015-12-07 14 15 53](https://cloud.githubusercontent.com/assets/1227834/11627762/56dcd382-9ced-11e5-8072-db65c04235dd.png)

I believe this PR caused that: https://github.com/symfony/doctrine-bridge/commit/ee6ce906e0bfe749e661306bad6696d3968353c7

There're two solutions - require `iconv` in `composer.json` or just provide fallback.
Since PR mentioned above was introduced to simplify the code and remove previous `strlen()` fallback I believe requiring `iconv` is a better solution.

**Comment by nicolas-grekas** [comment]
Yes, requiring iconv is the best option, it should be a loose requirement since almost everyone should have it enabled

**Comment by nicolas-grekas** [comment]
See #16778

**Comment by nicolas-grekas** [comment]
hum, sorry, not requiring it in Symfony, but on your own project

**Comment by nicolas-grekas** [comment]
or require symfony/polyfill-iconv (on your own project again)

**Comment by kiler129** [comment]
Maybe you're right on that actually.
