### ISSUE TITLE
Error in WebProfile

### ISSUE THREAD

**Issue by andrelemos** [symfony/symfony#16895]
An exception has been thrown during the rendering of a template ("Warning: fopen(D:\ZendServer\Andre\hbauth30\var\cache\dev\annotations\9f\5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c657223736561726368426172416374696f6e405b416e6e6f745d5d5b315d.doctrinecache.data): failed to open stream: Invalid argument") in @WebProfiler\Profiler\layout.html.twig at line 67.

from what I could see the error is in FileCache that is generating a lot of big names in windows 10

**Comment by Tobion** [comment]
doctrine/cache#107
