### ISSUE TITLE
[Session] Session storage path does not get set.

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#16898]
Hi!

It seems Symfony dosn't change the session storage path `%kernel.root_dir%/../var/sessions/%kernel.environment%`, when checking `app_dev.php/_profiler/phpinfo` it returns `/var/lib/php/session`.

This lines solves the problem temporarily:
`session_save_path(__DIR__ . "/../var/session");` in  `app.php` and `app_dev.php`

I got the exception when authenticating because Apache dosn't have write access to the default PHP session storage path.

I'm running Symfony 3.0.0 with PHP  7.0.0. 

The project that I noticed the issue on:
https://bitbucket.org/Richardh87/messenger

**Comment by Tobion** [comment]
Did you configure the save_path as in https://github.com/symfony/symfony-standard/blob/master/app/config/config.yml#L31 ?

**Comment by Richard87** [comment]
yup,

`save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"`

https://bitbucket.org/Richardh87/messenger/src/3bb21b49abc243f8e8a1a95e9025e5a9d72b07c2/app/config/config.yml?at=master&fileviewer=file-view-default#config.yml-31

**Comment by Tobion** [comment]
I found the problem. See https://github.com/symfony/symfony-standard/pull/904 for the fix.

**Comment by Richard87** [comment]
Nice! that was really fast :)

**Comment by Richard87** [comment]
that fix solved my problems :)

**Comment by xabbuh** [comment]
Closing here then as there is nothing we can do in the core.
