### ISSUE TITLE
[Form] Custom SearchType renders unwanted search field

### ISSUE THREAD

**Issue by aistis-** [symfony/symfony#16899]
Hello guys. Today I run into the same problem as a guy describes it at [StackOverflow](http://stackoverflow.com/questions/28761789/symfony-2-search-form-renders-an-unwanted-search-field-can-i-disable-this-behav).

Is it a bug or what? If I rename my class to anything different than `SearchType` (e.g. `SearchhType`), it works as I expect.

Just create `SearchType` with your custom fields and try to render with `{{ form(form) }}` in twig template to reproduce the problem.

I have tested it on Symfony 2.8 and 3.0

**Comment by xabbuh** [comment]
I think this is caused by the [search_widget block](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L154-L157) from the form theme. Maybe we should make a check first if the form to be displayed is compound.

**Comment by ogizanagi** [comment]
This issue will happen for any form type provided by Symfony or third-party bundles. I'm not sure we can do something about it, except suggesting to implement `getBlockPrefix` differently if you choose to name one of your form type the same as an existing one:

```php
namespace AppBundle\Form\Type;

// [...]

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // [...]
    }

    public function getBlockPrefix()
    {
        return 'app_search'
    }
}
```

**Comment by webmozart** [comment]
Thanks for reporting this bug @aistis-! :) The solution was already proposed: You should implement `getBlockPrefix()` to return the prefix of the desired template block. A simple solution is to return `'text'` there, then the type is rendered like a normal text widget.
