### ISSUE TITLE
php 7 deprecated functions still present in symfony 3

### ISSUE THREAD

**Issue by gondo** [symfony/symfony#16891]
file `https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/ResourceCaster.php` function `castMysqlLink` still use deprecated functions `mysql_*`

**Comment by xabbuh** [comment]
@gondo Symfony 3 does not require you to use PHP 7 so we cannot drop support for these functions here.

**Comment by gondo** [comment]
what about this http://symfony.com/blog/symfony-achieves-100-php7-compatibility ?
and especially `This means that Symfony no longer accepts changes that break PHP7 compatibility, not even in the master branch where the upcoming Symfony 3 is being developed.` ?

i understand that this is not a change per say, but this code would not work under php7 and therefore symfony3 can not be called 100% compatible with php7
or am i missing something?

**Comment by xabbuh** [comment]
But with PHP 7 you wouldn't have a mysql resource and thus that caster would never be triggered, would it?

**Comment by nicolas-grekas** [comment]
@xabbuh is right, this is dead code on php 7, it is never used

**Comment by jrobeson** [comment]
folks can still use find out how to use the mysql_* functions in php 7 though. This extension does exist, and will likely be in various distribution repositories https://github.com/php/pecl-database-mysql

**Comment by gondo** [comment]
ok, i see now. sorry for the confusion

**Comment by krakjoe** [comment]
The first thing it says in the readme ...

> This extension is deprecated and unmaintained.

The last thing it says in the readme ...

> Although it should be possible to build this extension with PHP 7.0, you are strongly encouraged to port your code to use either MySQLi or PDO_MySQL, as this extension is not maintained and is available for historical reasons only.

I don't think it could be clearer ... this is not an extension you can rely on, it is dangerously unmaintained.

**Comment by jrobeson** [comment]
it can say that all it wants, but people are still going to use it if it ends up in distributions

**Comment by stof** [comment]
But having the caster in Symfony only means it is possible to dump code properly for people using it. I don't see why we should skip registering this caster on PHP 7 just because the extension is deprecated. It would not simplify the codebase (we still need to keep this caster for PHP 5.x anyway) and would only make dumping less useful for people who keep using the deprecated extension.
