### ISSUE TITLE
[Form] getBlockPrefix breaks extended FormType in 2.8

### ISSUE THREAD

**Issue by rvanlaarhoven** [symfony/symfony#16896]
When switching to 2.8, I noticed my custom FormTypes did not render correctly anymore. 

For example, I have the following FormType;

```php
class MediapickerType extends EntityType
{
    public function getName()
    {
         return 'mediapicker';
    }
}
```

With the associated Twig block;

```twig
{% block mediapicker_widget %}
    {# Some custom form rendering #}
{% endblock mediapicker_widget %}
```

In 2.8 I noticed the `FormFactory` checks for the `getBlockPrefix` method. If that does not exist, it falls back to the `getName` method for BC (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/FormFactory.php#L77). 

The problem here is that the `EntityType` already has the `getBlockPrefix` method (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php#L70), so it will never end up in the `else` and it will never render my custom widget block.

I'm not sure what would be the best approach here. For now I simply added the `getBlockPrefix` to all my form types.

**Comment by xabbuh** [comment]
That's one of the reasons you should rather use the Form component's inheritance model by returning `entity` from the `getParent()` method than use PHP inheritance for Form types.

**Comment by Tobion** [comment]
Closing as user error.
