### ISSUE TITLE
[Templating] Custom File Extensions For PPI Framework

### ISSUE THREAD

**Issue by dragoonis** [symfony/symfony#16907]
In PPI we're using core parts of the SF2 templating component.

We've integrated support for Symfony PHPEngine, TwigEngine, SmartyEngine, MustacheEngine, Plates, Latte.

Symfony DelegatingEngine is looking only at file extensions to identify the correct engine.

One of the challenges we're facing is that multiple engines are using `.php` as their extension, like PHPEngine (.php), Plates (.php), Latte (.php). 

As a workaround we've made plates files detected by `.plates` and latte files by `.latte` however this is far from ideal because .php is picked up by IDE's and tooling.

Does anyone have a way to allow engines to be picked up by not just the file extension but a pattern at the end of the file? such as `.plates.php` and `.latte.php` ?

**Comment by jakzal** [comment]
You can implement [`EngineInterface::supports()`](http://api.symfony.com/2.7/Symfony/Component/Templating/EngineInterface.html#method_supports) to do what you'd like it to do, or am I missing something?

**Comment by dragoonis** [comment]
Yea, we're doing:

```
        $template = $this->parser->parse($name);
        return 'latte' === $template->get('engine');
```

**Comment by jakzal** [comment]
Looks like all you need is a custom implementation of the `Symfony\Component\Templating\TemplateNameParserInterface`.

**Comment by jakzal** [comment]
(what I'm trying to say is there's nothing to do in Symfony itself)

**Comment by javiereguiluz** [comment]
Closing it because from @jakzal's comments it seems there is nothing left to do in Symfony. @dragoonis please reopen if you disagree. Thanks!

**Comment by dragoonis** [comment]
@javiereguiluz yep, we're good at our end. We're doing the necessary steps in PPI Framework. Thanks!
