### ISSUE TITLE
Routing schemes https 302

### ISSUE THREAD

**Issue by HarryWiseman** [symfony/symfony#16919]
Hi,

More of a query than an issue, is there any reason then defining https as the scheme for the route the redirect from http > https is a 302 temp redirect?

Having troubles with SEO where it isn't removing the http links as they aren't marked as perm redirects.

Thanks,

Harry

**Comment by xabbuh** [comment]
Isn't this done by the `RetryAuthenticationEntryPoint` which already does what you ask for (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/EntryPoint/RetryAuthenticationEntryPoint.php#L57)?

**Comment by jakzal** [comment]
@HarryWiseman it is a 301 permanent redirect, not a 302. See https://github.com/symfony/symfony/blob/582f4753a343f230fbe18b4e9a0747d48351ddfb/src/Symfony/Bundle/FrameworkBundle/Routing/RedirectableUrlMatcher.php#L35

I have just tested this with the following config:

```yams
foo:
    path: /
    defaults:
        _controller: kernel:indexAction
    schemes: [https]
```

**Comment by xabbuh** [comment]
@HarryWiseman Can you provide some more insight to your issue?

**Comment by HarryWiseman** [comment]
Hi @xabbuh this was an issue to do with a third party where the htaccess was set to do what Symfony routing does automatically.... So this is all fine and not a bug.

Thanks!
