### ISSUE TITLE
Symfony form name.

### ISSUE THREAD

**Issue by gavinkalika** [symfony/symfony#16914]
Symfony3

on symfony form changed form name to  'employeeSearch'
{{ form_start(form,{'attr': {'novalidate': 'novalidate'},'method': 'GET', 'name':'employeeSearch'}) }}.

However, on submission must retrieve data by 'employee_search'
$request->get('employee_search').

What isn't the form class name be overridden?

**Comment by mpiecko** [comment]
Not a solution, but this might be related to https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md

![image](https://cloud.githubusercontent.com/assets/209899/11684812/850a7024-9e74-11e5-9272-d36b91e198aa.png)

Michael

**Comment by gavinkalika** [comment]
thanks!
