### ISSUE TITLE
[2.8][TwigBundle]  Template paths changed

### ISSUE THREAD

**Issue by Baptouuuu** [symfony/symfony#16928]
I suspect the change happened with this [commit](https://github.com/symfony/symfony/commit/ff3c107f14cfc4ff4f4e2186e2ac88de83ea34f9), the path for an error template (for example) went from `@TwigBundle/Resources/views/Exception/error.html.twig` to `@Twig/Exception/error.html.twig`.

I discovered this as I am extending the file locator (to handle a mechanism of themes), and with the upgrade to symfony 2.8 the error pages weren't showing my custom templates as it could no longer find them. 

*Note*: The custom file locator is spliting the template path in order to extract the bundle name, the folder and the file

Can this be qualified as a bc break?

**Comment by WhiteEagle88** [comment]
@Baptouuuu I tried override error.html.twig.
1) I created file error.html.twig in app/Resources/TwigBundle/views/Exception
2) And created exception with 500 error in controller.
3) I get content is my error.html.twig

But need disable debug mode, because if debug mode is enabled you will getting is not overriding error.html.twig(exception.html.twig)

**Comment by Baptouuuu** [comment]
Indeed by default it works as before, what I was trying to say is that as the path string no longer follow the template `{Name}Bundle/Resource/views/{Folder}/{file}.html.twig` it breaks any scripts relying on this pattern to do whatever.

So my question actually is: is this change considered a bc break as it may break people code? I'm not sure as it breaks very specific code that is not a usual use case in symfony (meaning by default nobody needs to alter the way templates are loaded).

**Comment by stof** [comment]
The ``@namespace`` for bundles has *never* included the ``Bundle`` suffix in any released version of Symfony.
the template name went from ``TwigBundle:Exception:error.html.twig`` to ``@Twig/Exception/error.html.twig``, which both refer to the same file in TwigBundle

**Comment by Baptouuuu** [comment]
Oops, sorry about the confusion from my part! (http://symfony.com/doc/current/cookbook/templating/namespaced_paths.html)
