### ISSUE TITLE
bootstrap 3 layout adds "form-control" on hidden inputs / csrf token inputs

### ISSUE THREAD

**Issue by michaelPf85** [symfony/symfony#16925]
Hello,

I've been using Bootlint recently to fix some mistakes on an application we're building. Most errors were on our side and we were able to fix, but one seems to come from symfony : Bootlint complains that our "form__token" hidden inputs use "form-control" class that is only available for text inputs.

I think this is the CSRF token input that SF automatically adds, I might be wrong on some point or term.

I located in *bootstrap_3_layout.html.twig* the block *form_widget_simple* that adds the "form-control" class on everything but "file" inputs. I modified it from `or file != type` to `or ('file' != type and 'hidden' != type)` and it works well. But I'm afraid this could miss some other errors, but other widgets seem to cover about everything (date, datetime, money...), or worse it could not be wanted :)

Would this be alright ? I suppose I might try to write some pull request if it's OK (this would be my first).

We're using Symfony 2.6.12 but I checked the master branch and this part was not changed.

Thanks for your feedback.

**Comment by xabbuh** [comment]
@michaelPf85 It would be great if you could point us to some Bootstrap documentation which explain when to use and when not to use the `form-control` class.

**Comment by michaelPf85** [comment]
That's a challenge... Precise Bootstrap documentation !

Up to now I've found those :
  * Brief explanation of how it behaves : (http://getbootstrap.com/css/#forms-example) "textual <input>"
  * Some listing in the source code that tells when to apply it : (https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/forms.less) line 92 to 112
  * The bootlint check, that should be accurate since it's made by the same team IIRC : issue + commit information (https://github.com/twbs/bootlint/commit/e0783e5de6575ea20086c30fc3202aa5f73431d0)

It never exactly tells in Bootstrap that `form-control`should not be used outside of the cases listed in the code documentation, but the Bootlink rule does say so. As such it's not completely satisfying but IMHO it looks like sufficient doc.

**Comment by javiereguiluz** [comment]
@michaelPf85 thanks for investigating the origin of this recommendation. @xabbuh given these proofs, I'd say that the change is legitimate.

**Comment by xabbuh** [comment]
Seems so. Are there other types we should exclude too?

**Comment by michaelPf85** [comment]
Here is the complete list of input types where the `form-control` class applies (from bootstrap source code).

Date and datetime seem to be covered by oher blocks, but I do not know what `form_widget_simple` covers exactly so I can't filter the list for you unfortunately.

 * input[type="text"]
 * input[type="password"]
 * input[type="datetime"]
 * input[type="datetime-local"]
 * input[type="date"]
 * input[type="month"]
 * input[type="time"]
 * input[type="week"]
 * input[type="number"]
 * input[type="email"]
 * input[type="url"]
 * input[type="search"]
 * input[type="tel"]
 * input[type="color"]

**Comment by satanasdiabolo** [comment]
It looks like `form_widget_simple` covers the following form type:

* TextType
* EmailType
* IntegerType
* MoneyType
* NumberType
* PasswordType
* PercentType
* SearchType
* UrlType
* RangeType
* DateType with option widget set to single_text 
* DateTimeType with option widget set to single_text 
* TimeType with option widget set to single_text 
* BirthdayType with option widget set to single_text 
* FileType

The `form-control` CSS class is also applied to `choice_widget_collapsed`

**Comment by javiereguiluz** [comment]
@michaelPf85 thanks for the information provided to solve this issue and thanks to @satanasdiabolo too.

I've created a new pull request to solve this issue (#17568). @michaelPf85 you mentioned in your first comment that this would be your first pull request. If you want to try to submit a pull request next time, you can read [this guide](http://symfony.com/doc/current/contributing/code/patches.html) and you can ask us for any help that you might need.
