### ISSUE TITLE
Problem with symfony 3.0 instalation/deploy

### ISSUE THREAD

**Issue by vsychov** [symfony/symfony#16939]
I have problem with deploy symfony 3, when I create new project by:
`php symfony new test`

symfony installer create .gitignore file with `/bin/` directory. But if that dirrectory not exists and I try run `composer install`, I got error:
> The symfony-bin-dir (bin) specified in composer.json was not found in /var/www/symfony3/test, can not clear the cache.

**Comment by javiereguiluz** [comment]
@vsychov thanks for reporting this issue. We're tracking it in the github.com/symfony/symfony-installer repository. In fact, we recently merged a pull request to solve it (https://github.com/symfony/symfony-installer/pull/218). The fix will be available in the next Symfony Installer release, which will be published very soon. Thanks!
