### ISSUE TITLE
new debug toolbar - bugs

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#16938]
hello .. I'm using new debug toolbar and I think those hings should be improved:

1. on doctrine tab, there should by total time and total queries
2. on form tab, there should by solved if form names are too long
3. div #content width should 100% ... 

http://i.imgur.com/Ort2iJw.png

**Comment by javiereguiluz** [comment]
About your third point, we've talked several times about that and for now we are not going to make the web profiler 100% wide. The reason is that it makes lines to be extremely long, which completely destroys their readability.

**Comment by javiereguiluz** [comment]
The "empty Doctrine panel" bug is being fixed in https://github.com/doctrine/DoctrineBundle/pull/508

**Comment by javiereguiluz** [comment]
I think we can close this issue as "fixed":

1) The Doctrine bug was fixed: https://github.com/doctrine/DoctrineBundle/pull/503
2) The Form bug is fixed too (but the merge is pending): https://github.com/symfony/symfony/pull/17417
3) The `div#content` width won't be changed for now
