### ISSUE TITLE
Doctrine CRUD, Create action not working

### ISSUE THREAD

**Issue by khalid-s** [symfony/symfony#16931]
Just noticed when doing a CRUD, with sf3, the /new route is generating this error:

```
Expected argument of type "string", "sf\SfBundle\Form\TestType" given
```

Error is comming from here : in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 64

**Comment by xabbuh** [comment]
The `doctrine:generate:crud` command is part of the [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle/). Please report any issues with this bundle in its issue tracker.
