### ISSUE TITLE
Symfony 2.8 not kept up to date on packagist

### ISSUE THREAD

**Issue by liamsorsby** [symfony/symfony#16942]
I've been wating for the bug fix #16796 into version 2.8 which was merged 5 days ago. I've updated symfony using composer and symfony did not update.

I've checked packagist and it seems that version 2.8 was last updated on the 2015-11-30 17:26 UTC.

Are updates pushed to packagist incrementally or should the most recent version of 2.8 be on packagist>

**Comment by stof** [comment]
The 2.8.x-dev version is updated at  2015-12-10 10:37 UTC according to Packagist, which means it is uptodate.

**Comment by xabbuh** [comment]
@liamsorsby If you want to use that fix right now, you will have to depend on the 2.8 development version as there haven't been a new release after the fix has been merged.

**Comment by liamsorsby** [comment]
@stof My mistake, thank you for clarifying this for me.
