### ISSUE TITLE
Symfony3 Profiler | Fatal error on Doctrine explain query

### ISSUE THREAD

**Issue by werdlv** [symfony/symfony#16943]
```
Fatal Error: Class 'Symfony\Component\DependencyInjection\ContainerAware' not found
```
occurs when trying to use "Explain query" option via Symfony Profiler -> Doctrine section.
It is caused because `Symfony\Component\DependencyInjection\ContainerAware` was deprecated and removed in favour of `Symfony\Component\DependencyInjection\ContainerAwareTrait`

Trace:
1) https://github.com/symfony/symfony/blob/v3.0.0/composer.json#L79
2) https://github.com/doctrine/DoctrineBundle/blob/v1.4.0/Controller/ProfilerController.php#L27

Found using:
- Symfony 3.0.0
- PHP 7.0

**Comment by Taluu** [comment]
Should be reported on the DoctrineBundle repository

**Comment by werdlv** [comment]
@Taluu yeah - sorry :) Opened https://github.com/doctrine/DoctrineBundle/issues/500
