### ISSUE TITLE
TranslationUpdateCommand has a code path for an undefined var error

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#16950]
On 2.8, $resultMessage is not always defined here:

https://github.com/symfony/symfony/blob/829c011b4971dec306e39f1aed0fa24c274389bf/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L213

ping @aitboudad

**Comment by aitboudad** [comment]
yep, I'll fix that :)

**Comment by aitboudad** [comment]
see #16954
