### ISSUE TITLE
[Finder] Add type on iterator so that IDE will know what finder iterator returns

### ISSUE THREAD

**Issue by gcds** [symfony/symfony#16965]
Maybe it's possible to add phpdoc to suggest type for iterator? Because I hate every time to write like this when using Symfony Finder

```php
/** @var SplFileInfo $file */
foreach ($finder as $file) {
...
}
```

**Comment by jakzal** [comment]
I don't think there's currently a way to do this other than type hint it in user land code just like you did.

**Comment by stof** [comment]
@jakzal for Iterator, PhpStorm supports it by documenting the return type on ``current``. It is smart enough to figure out that the iterator values are the ones coming from ``current`` and so use this type.

But I'm not aware of a way to specify the type when using IteratorAggregate with a generic iterator (we may solve it by documenting the ``current`` return type on all filtering iterators of the component, as we don't return a generic iterator in the Finder)

**Comment by jakzal** [comment]
@stof `current()` methods are only defined on `RecursiveDirectoryIterator` and `FilePathsIterator` (the later is not present in 3.0 anymore). Both have return types defined.

**Comment by stof** [comment]
@jakzal others could use ``@method SplFileInfo current`` to document it. but I fear PhpStorm does not introspect ``IteratorAggregate::getIterator`` to see what is returned exactly

**Comment by javiereguiluz** [comment]
Reading your comments I'm not sure if this is issue can be fixed or not. Anyone has a better solution for this? Thanks!

**Comment by fabpot** [comment]
@javiereguiluz I guess someone needs to try @stof suggestions first. I'm not a phpstorm user, so someone needs to do that.

**Comment by WouterJ** [comment]
Specifying an iterator return for `getIterator` doesn't work, PHPstorm will show no suggestion.

A dirty way of implementing this is by adding `@return SplFileInfo[]` for `Finder#getIterator()`, but that is only a hack to get PHPstorm autocompletion working (as it's returning an iterator and not an array of objects).

**Comment by ro0NL** [comment]
Our workaround on doctrine associations `@return ArrayCollection|ContainedObject[]`

- Click-throughs in PHPStorm works on both classes :+1: 
- Autocomplete on `ContainedObject` in foreach works as expected :+1: 
- Autocomplete on `ArrayCollection` doesnt work :-1:

**Comment by Haehnchen** [comment]
You can use following syntax to support this in userland for all public iteration methods. i am also able to support it the in symfony plugin. depending on your decision

```php
     * @return Finder|SplFileInfo[] The current Finder instance
     *
     * @api
     */
    public function files()
```

**Comment by Haehnchen** [comment]
pull request created for `Finder|SplFileInfo[]`

**Comment by Haehnchen** [comment]
@ro0NL, @WouterJ `getIterator` now also supported in latest PhpStorm build: https://blog.jetbrains.com/phpstorm/2016/06/phpstorm-2016-2-eap-162-844/
