### ISSUE TITLE
[SecurityBundle] Renaming the firewall context option

### ISSUE THREAD

**Issue by linaori** [symfony/symfony#16960]
On IRC I often tend to help out with Security component/bundle related questions. Recently I had a question regarding the firewall context and sharing it between different firewalls. I thought: "What is a firewall context"? I obviously know the answer, but to someone new, it might not seem so obvious. The answer is simple: 
- _It's the identifier for a given Token and the context option defines which token identifier the firewall should use._

So I thought back of 2.5 and lower, where we still had the `SecurityContext`. It was literally the context with your token in it, referring back to the context option underneath the firewall, which has the firewall name if not defined by the developer.  Now that the `SecurityContext` is gone, the option makes a lot less sense being named "context" as it lost all its references.

**_My proposal is to rename this option to something different to make it easier for (new) developers.**_

Just to throw in a few ideas:
- token-identifier
- token-storage
- storage-key

**Comment by javiereguiluz** [comment]
@iltar although I partially agree with you, I propose to close this as "won't fix". Reasons:

1) Newcomers rarely need to deal with this option. You really need some Symfony experience or must work in a complex application.
2) Changing it would force all experienced developers to relearn the name of this option.
3) As it usually happens with renamings, the proposed alternatives aren't much better than the original.

**Comment by xabbuh** [comment]
Well, if we find a good new name, I am :+1: for renaming this option (we already did that in 2.8/3.0 with some other security related options).

**Comment by WouterJ** [comment]
I'm a big :+1: for this issue. The current naming is too vague and it can really mean anything... Please note that we should not only care for the real newcomers: People may be seasoned Symfony devs, but new to multiple firewalls and the naming of this option won't help anything. Besides that, renaming is already pretty often done to improve APIs (and in almost all cases, the renaming made sense).

A related issue is https://github.com/symfony/symfony/issues/15207 as it's basically the same thing but on the domain level. Are these things not just firewall identifiers? Or firewall scopes? Or firewall namespaces?

**Comment by chalasr** [comment]
👍

**Comment by linaori** [comment]
While this is certainly still an issue, I'd like to see where the security component brings us in the future, perhaps it won't be needed anymore.
