### ISSUE TITLE
Doc + PDF + SF3.0 = 404

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#16962]
Hello

This is a SensioLabs support ticket
(ref https://sensio.zendesk.com/agent/tickets/3945)

> The page http://symfony.com/pdf/Symfony_cookbook_3.0.pdf?v=4 if responding with a HTTP 404.

**Comment by stof** [comment]
should be in the symfony-docs repo, as this is about the doc (or kept in the Sensio tracker as this is something which must be fixed by Sensio anyway given the website is closed source)

**Comment by xabbuh** [comment]
see symfony/symfony-docs#5939 and symfony/symfony-docs#5978

**Comment by lyrixx** [comment]
Oups, sorry I though I were on our private repository for `symfony.com`; That's why I was a bit short with the description.
