### ISSUE TITLE
session_register_shutdown function in NativeSessionStorage.php not compatible with php versions lower than 5.4

### ISSUE THREAD

**Issue by edlington** [symfony/symfony#16979]
Line 104 in \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage,php makes a call to session_register_shutdown(). This will cause a fatal error if Symfony is installed on PHP versions less than 5.4.

A possible fix: 

 if(function_exists('session_register_shutdown')) {
            session_register_shutdown();
        }
        if(!function_exists('session_register_shutdown')){
            if(function_exists('register_shutdown_function')){
                register_shutdown_function('session_write_close');
            }
        }

**Comment by nicolas-grekas** [comment]
This is already provided by the php54 polyfill required in the composer.json file, isn't it ?

**Comment by edlington** [comment]
Nicolas you're absolutely correct. Apologies for flagging a non error. After reading your post I checked the php54 polyfill folder, It's in my install and the code for backwards compatibility is in there. Yet I'm still getting the session_register_shutdown() error if I try to clear the dev or prod cache. I'm wondering what I'm doing wrong. (Symfony newb). Thanks for your patience!

**Comment by nicolas-grekas** [comment]
I doubled checked: closing as there is nothing wrong on our side...
