### ISSUE TITLE
[Process] Failing process timing test using usleep

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#16988]
I'm doing a bit of guess work here based on [this failed unit test](https://ci.appveyor.com/project/fabpot/symfony/build/1.0.4023#L694). Seems that the test [uses `usleep` ](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Process/Tests/ProcessTest.php#L748). Also i noticed (on my own machine) phpunit launches a ton of parallel processes. Take on top of that we don't know for sure what appveyor is running on 1 CPU. So that means a lot of processes are in contention for CPU time. So i guess that could be a cause here. If it is, below are some relevant links

https://github.com/php/php-src/blob/250938e2d35fc54161a18167b7901c5e3b574371/win32/time.c#L101-L113

https://msdn.microsoft.com/en-us/library/windows/desktop/ms687032%28v=vs.85%29.aspx

> Note that a ready thread is not guaranteed to run immediately. Consequently, the thread may not run until some time after the sleep interval elapses. For more information, see Scheduling Priorities.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298%28v=vs.85%29.aspx

**Comment by nicolas-grekas** [comment]
I fully agree here: we should try to make tests less volatile by not relying on usleep/time-ordering as much as possible
