### ISSUE TITLE
MicroKernel: Attach Kernel as Subscriber if implementing interface

### ISSUE THREAD

**Issue by beberlei** [symfony/symfony#16982]
I used MicroKernel for a very small migration project in Doctrine today where we redirect all the old Jira issues to their new Github counterparts. I want to handle all errors and not founds with the MicroKernel as well, but that requires implementing and registering a listener for `kernel.exception`, though it could be possible to just have the Kernel be a listener.

https://github.com/doctrine/doctrine-website-sphinx/commit/ea993376572a71e3844063ca215314ff595e7594

I propose to extend `MicroKernelTrait` to register itself as a subscriber on `event_dispatcher`, if it implements the `EventSubscriberInterface`. Not sure how to do that in a simple way, it probably involves adding a CompilerPass that is added to the ContainerBuilder in `MicroKernelTrait::registerContainerConfiguration`.

**Comment by ogizanagi** [comment]
To me, there are two possibilities to extend the `MicroKernelTrait` in order to propose such a thing.

1) Using a compiler pass (https://github.com/ogizanagi/symfony/commit/b40738c4aa43e64080494041cfc5ef39c5766d9e):

```diff
@@ -12,7 +12,10 @@
 namespace Symfony\Bundle\FrameworkBundle\Kernel;
 
 use Symfony\Component\Config\Loader\LoaderInterface;
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\Reference;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
 use Symfony\Component\Routing\RouteCollectionBuilder;
 
 /**
@@ -71,6 +74,10 @@ trait MicroKernelTrait
             $this->configureContainer($container, $loader);
 
             $container->addObjectResource($this);
+
+            if ($this instanceof EventSubscriberInterface) {
+                $container->addCompilerPass(new EventSubscriberKernelCompilerPass());
+            }
         });
     }
 
@@ -85,3 +92,22 @@ trait MicroKernelTrait
         return $routes->build();
     }
 }
+
+/**
+ * @internal
+ */
+class EventSubscriberKernelCompilerPass implements CompilerPassInterface
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function process(ContainerBuilder $container)
+    {
+        if ($container->has('event_dispatcher')) {
+            $container->findDefinition('event_dispatcher')->addMethodCall(
+                'addSubscriber',
+                array(new Reference('kernel'))
+            );
+        }
+    }
+}
```
If the PHP min requirement for using the trait was PHP 7, we could have used an anonymous class directly instead of this internal compiler pass. We could imagine a base `CallableCompilerPass` class taking a callable to execute as constructor argument in order to do the same.

2) Using the `boot` method (https://github.com/ogizanagi/symfony/commit/cc1979dbee69c000a30712c063994f2fc19649f0):

```diff
@@ -13,6 +13,7 @@ namespace Symfony\Bundle\FrameworkBundle\Kernel;
 
 use Symfony\Component\Config\Loader\LoaderInterface;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
 use Symfony\Component\Routing\RouteCollectionBuilder;
 
 /**
@@ -74,6 +75,15 @@ trait MicroKernelTrait
         });
     }
 
+    public function boot()
+    {
+        parent::boot();
+        $container = $this->getContainer();
+        if ($this instanceof EventSubscriberInterface && $container->has('event_dispatcher')) {
+            $container->get('event_dispatcher')->addSubscriber($this);
+        }
+    }
+
     /**
      * @internal
      */

```

The second option would be acceptable in the `AppKernel` directly, as you did, but I don't like it in the trait.
What do you think ?

**Comment by nicolas-grekas** [comment]
> Another method is to cheat and simply add this

@ogizanagi what about opening a PR doing just that to see how it goes?

**Comment by ogizanagi** [comment]
Sorry for the delay. See #23812.
