### ISSUE TITLE
Change default environment on console

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16993]
Is there any way to change the default environment for the console to ``prod``?
I already know ``export SYMFONY_ENV=prod`` but I would prefer any solution in the deployed code.

**Comment by xabbuh** [comment]
You can change the console front controller in your application: https://github.com/symfony/symfony-standard/blob/master/bin/console#L20

Anyway, please use one the support channels like [StackOverflow](http://stackoverflow.com/questions/tagged/symfony2) or IRC for asking support questions.
