### ISSUE TITLE
generateUrl drops http scheme

### ISSUE THREAD

**Issue by jonathanbull** [symfony/symfony#16991]
The documentation [implies that passing `true` as the third parameter to `generateUrl`](http://symfony.com/doc/current/book/routing.html#generating-absolute-urls) will generate an absolute URL, including the scheme. This works as expected for a https URL, but in the case of a http URL, the scheme gets dropped. As a workaround I'm passing a 0 as the third argument:

    foo_route:
        path:  /foo
        defaults: { _controller: FooBundle:Bar:index }
        schemes: [http] 

    // Returns: //mydomain.com/foo
    $this->generateUrl('foo_route', [], true);

    // Returns: http://mydomain.com/foo
    $this->generateUrl('foo_route', [], 0);

Is this a bug?

**Comment by Tobion** [comment]
See https://github.com/symfony/symfony-docs/pull/6009. You need to use the constant, not `true`.

**Comment by jonathanbull** [comment]
Great, thanks for the prompt commit/reply.

**Comment by xabbuh** [comment]
The documentation PR has been merged and the changes should be visible by tomorrow.
