### ISSUE TITLE
findTaggedServiceIds returns empty array

### ISSUE THREAD

**Issue by 4r1y4n** [symfony/symfony#16997]
I'm trying to create a custom tag for services and get a list of services that has this tag (on `symfony 2.6.4`).  
I created a class to hold found tags:  

    namespace ITW\ReportingBundle;
    
    class ReportForm 
    {
    	private $forms;
    
    	public function __construct()
    	{
    		$this->forms = array();
    	}
    
    	public function addForm($f)
    	{
    		$this->forms[] = $f;
    	}
    	public function getForms() {
    		return $this->forms;
    	}
    	
    }
And the compiler pass class:  

    namespace ITW\ReportingBundle\DependencyInjection\Compiler;
    
    use Symfony\Component\DependencyInjection\ContainerBuilder;
    use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
    use Symfony\Component\DependencyInjection\Reference;
    
    class ReportFormCompilerPass implements CompilerPassInterface
    {
    	public function process(ContainerBuilder $container)
    	{
   
    		$definition = $container->findDefinition(
    				'itw.reporting.formlist'
    		);
    
    		$taggedServices = $container->findTaggedServiceIds(
    				'form.report'
    		);
    		var_dump($taggedServices);
    		foreach ($taggedServices as $id => $tags) {
    			$definition->addMethodCall(
    					'addForm',
    					array(new Reference($id))
    			);
    		}
    	}
    }

And added it to my bundle:  

    namespace ITW\ReportingBundle;
    
    use Symfony\Component\HttpKernel\Bundle\Bundle;
    use Symfony\Component\DependencyInjection\ContainerBuilder;
    use ITW\ReportingBundle\DependencyInjection\Compiler\ReportFormCompilerPass;
    
    class ITWReportingBundle extends Bundle
    {
    	public function build(ContainerBuilder $container)
    	{
    		parent::build($container);
    	
    		$container->addCompilerPass(new ReportFormCompilerPass());
    	}
    }

And used the tag:  

    services:
        itw.contract.form.type.contactReport:
            class: ITW\ContractBundle\Form\ContractReportType
            arguments: 
                - "@security.token_storage"
            tags:
                - { name: form.report }
                - { name: form.type, alias: contractReportForm }
                

But the `findTaggedServiceIds` returns empty array! ( it worked before my last cache clear and after that it returns empty array!)  

What is the problem?

**Comment by stevecohenfr** [comment]
Hi, did you fixed that ?
