### ISSUE TITLE
PropertyAccessor error when edit entity

### ISSUE THREAD

**Issue by nathanmarcos** [symfony/symfony#17003]
Greetings guys!

I got and particular error when editing the entity bellow:

```php
/**
 * Displacement
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Displacement
{
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Vehicle")
     * @ORM\JoinColumn(name="vehicle_id", referencedColumnName="id", nullable=false)
     * @Assert\NotBlank()
     **/
    private $vehicle;

    /**
     * Set vehicle
     *
     * @param \AppBundle\Entity\Vehicle $vehicle
     *
     * @return Displacement
     */
    public function setVehicle(\AppBundle\Entity\Vehicle $vehicle)
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    /**
     * Get vehicle
     *
     * @return \AppBundle\Entity\Vehicle
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    ...
}
```

With form:

```php
class DisplacementType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('vehicle');
    }

    ...
}
```

The point is, when I'm creating a Displacement without choose a Vehicle I got the error from NotBlank Validator as expected but, when editing, I got this:

```
Catchable Fatal Error: Argument 1 passed to AppBundle\Entity\Displacement::setVehicle() must be an instance of AppBundle\Entity\Vehicle, null given, called in /var/www/html/simba/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 502 and defined
```

What makes me worried is the fact that error never occurred before, and I have a lot of same use case in others entities.

In this [stackoverflow's discussion](http://stackoverflow.com/questions/26210873/edit-entity-field-to-null-symfony2), some people told to remove the type hint in set method and some people told to define default as null like bellow:

```php
    //Removed type hint
    /**
     * Set vehicle
     *
     * @param \AppBundle\Entity\Vehicle $vehicle
     *
     * @return Displacement
     */
    public function setVehicle($vehicle)
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    //Defined default as null
    /**
     * Set vehicle
     *
     * @param \AppBundle\Entity\Vehicle $vehicle
     *
     * @return Displacement
     */
    public function setVehicle(\AppBundle\Entity\Vehicle $vehicle = null)
    {
        $this->vehicle = $vehicle;

        return $this;
    }
```
I'm not sure about those two solutions, I think that something went wrong here. What you guys know about that?

Best regards. Thanks a lot!

**Comment by stof** [comment]
Well, this is logical: your setter is called *before* the validator. So if it does not allow to set the invalid values, you won't get the nice user-facing error.

A simple solution is indeed to allow null in your typehint.
In case you prefer having strict typehints in your objects, a solution is to use a separate object as the form target, in which you access invalid data to come in, then run validation rules on it, and then set data in your strict typed object when data are valid only.

**Comment by nathanmarcos** [comment]
@stof Perfect, I got your point. But I have another attributes in this entity with the same case and this error never occurred before.

**Comment by stof** [comment]
well, maybe you never submitted an invalid value in your form...

**Comment by nathanmarcos** [comment]
@stof Definitely you're right! To close the issue, could you explain me why this occurs only on the updateAction and not in the createAction? When I'm creating, I submit null values and I got "This value should not be blank." but, when I'm editing, I got that error 500.

**Comment by ogizanagi** [comment]
@nathanmarcos : Probably because when you are on the new form, you create a new instance of `Displacement`, without any `Vehicle` instance (`null`).

So, as you're submitting the same `null` data for the `vehicle`, the [PropertyPathMapper](`https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php#L92`) will never call `PropertyAccessorInterface::setValue()`

**Comment by nathanmarcos** [comment]
@ogizanagi Of course!! I forgot that point!! Now everything is understood. Thanks a lot.
