### ISSUE TITLE
symfony report error when has '@' in the comment

### ISSUE THREAD

**Issue by ZYWJ** [symfony/symfony#17000]
I am using the [ApiDoc](http://apidocjs.com/) for generating my code document.  
But it occurs error when has '@' in the comment.  
![image](https://cloud.githubusercontent.com/assets/5554211/11775474/118fcc7a-a27a-11e5-88a3-ad088519d93a.png)

This is the error message.  
![image](https://cloud.githubusercontent.com/assets/5554211/11775529/76062a6e-a27a-11e5-8f42-09e0af4b4507.png)

**Comment by Nek-** [comment]
Hello,

Your point is specific on Controller. I'm not sure documenting controllers have a real importance. But indeed it's a problem.

But this problem is not present on a standard installation without using annotation for routing. Did you installed FOSRestBundle ?

If you use annotations for routing, you can use yaml or xml to define your routes. (the issue is still real, it's just a workaround)

**Comment by ZYWJ** [comment]
@Nek
Hi, Thx for you comment.  
I want to auto generate my API document.  
It seems not due to the route of FOSRestBundle.  
The problem is still exists when I put the code comment on the regular controller.

**Comment by Nek-** [comment]
In fact it's an issue from doctrine: https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/AnnotationReader.php#L55

You can also fix it by adding manually ignored annotations. With `AnnotationReader::addGlobalIgnoredName`.

**Comment by ZYWJ** [comment]
I don't know very well.  I am confused.  
 How to use the method `AnnotationReader::addGlobalIgnoredName`

**Comment by ZYWJ** [comment]
The error is still.
The regular controller isn't use annotation for routing. I am use routing.yml for controller routing.

**Comment by ZYWJ** [comment]
@Nek- Thx.
After I tested. I think manually ignored annotations is the quickest way

**Comment by Nek-** [comment]
Notice that if you want to generate a doc from php you should use [phpdoc](http://www.phpdoc.org/) that is natively supported by doctrine annotations.

**Comment by dvc** [comment]
For Symfony4 i have add the CompilePass **with highest priority**

```
// /src/Kernel.php

   ...
    protected function build(ContainerBuilder $container): void
    {
        $container->addCompilerPass(new IgnoreBadAnnotationsPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 1000);
    }
   ...
```

```
// /DependencyInjection/Compiler/IgnoreBadAnnotationsPass.php

<?php

namespace App\DependencyInjection\Compiler;

use Doctrine\Common\Annotations\AnnotationReader;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

final class IgnoreBadAnnotationsPass implements CompilerPassInterface {
    public function process(ContainerBuilder $container) {
        // bug when extending unreal4u\TelegramAPI\Abstracts\KeyboardMethods class 
        // with  "@mentioned" in comment
        AnnotationReader::addGlobalIgnoredName('mentioned');
    }
}
```

**Comment by nicolas-grekas** [comment]
@dvc you likely won't get any more comment on an issue closed more than two years ago. Please open a new one if you think you found a bug - with a reproducer if possible.

**Comment by dvc** [comment]
@nicolas-grekas , i`m sorry. It was an issue, i have found by search. And it`s my workaround here for others, who can find it issue too. I think, this is not a symfony bug.

I have had not too much time to accurate posting. Deadline in project :(

I have create a bug in doctrine/annotations project: https://github.com/doctrine/annotations/issues/169
