### ISSUE TITLE
[2.8][Form] Bug if a userland type use the same class name as a core one

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#17009]
Hello.

I [forked the SE](https://github.com/lyrixx/symfony-standard/tree/sf-form-email-2.8) to reproduce our use case
As you can see, everything is simple there:
* A "custom" `EmailType` that actually do nothing. (In our application, it contains several fields)
* A simple controller
* A simple view.

I would expect to see **nothing** in the view, but instead I can view an empty `input text`.
![screenshot2](https://cloud.githubusercontent.com/assets/408368/11786535/7174604e-a287-11e5-9575-ba2465d7b852.png)

So it looks like there is conflict between Symfony Core Type and **mine** type.

Note: Here I **do not want** to override a type, I just use a name that exist.

More over, the issue it worst than just that. Because it adds a new text-type; the form theme try to cast to string the `$data` to put in there. I added the second commit to show that. And so it results in an exception:
![screenshot3](https://cloud.githubusercontent.com/assets/408368/11786633/e2cf974a-a287-11e5-8c4e-fc8f9143e774.png)

**Comment by lyrixx** [comment]
It's looks like it's a bug in the BC layer with `FormType::getName()`

**Comment by xabbuh** [comment]
Looks like this could also be related to #16899.

**Comment by lyrixx** [comment]
I added another commit in my fork that implement `getBlockPrefix` and it solved the issue.
I try to upgrade to SF3 and the issue is still here. So It looks like it's not related to the BC layer.

So, yes, I think is related. 

Thanks

**Comment by webmozart** [comment]
Thanks for reporting this issue @lyrixx! :) This is not a BC break. If your type was named "search" before, then Symfony already behaved like this. I suppose you named it "app_search" though, so that's also what you probably want to return from `getBlockPrefix()`.

Note: You can also return other existing prefixes - like "text" - if you want to reuse the rendering logic of an existing type.

**Comment by lyrixx** [comment]
@webmozart But it's very hard to debug. Could we do something to ease that?

**Comment by xxorax** [comment]
Still present in 4.4.
Nothing in [the doc](https://symfony.com/doc/4.4/forms.html) about this.
It's a hell to debug due to the switches between services and generated templates.
Declaring `getBlockPrefix()` and returning any string fix the issue.
