### ISSUE TITLE
[Form][Validator] Some errors are skipped

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#17012]
After submitting an invalid form I noticed that I only got some of the errors instead of all of them. I only got the rest of the errors when I fixed the first batch.

The problem occurs when I try to validate a form using multiple validation groups. If the first validation group causes some errors, the other groups are skipped. After some digging I found [this line](https://github.com/symfony/symfony/blob/25b89d4af44fe6eea2102332abe9669ec10ada86/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L836) which causes this unexpected behavior.

I need to be able to show all the errors at once, not just some subset. But I do need more then one validation group for other reasons. Is there a way to fix this?

**Comment by ogizanagi** [comment]
This is the expected behavior when using group sequences actually: Validation by steps.
The question then is: Do you really need to use a group sequence if you didn't expect this ?

**Comment by xabbuh** [comment]
Closing here as this is the expected behaviour.

**Comment by enumag** [comment]
@ogizanagi I need to use multiple validation groups because the form is sometimes more simple and allows some fields to be ommited. It is possible to use multiple validation groups without group sequence?

**Comment by xabbuh** [comment]
@enumag Just pass the list of validation groups with the `validation_groups` option to your form or use pass the array of validation groups to the validator's `validate()` method (depending on how you validate your data).

**Comment by enumag** [comment]
@xabbuh That does seem to work but I lose the benefit of the entity deciding which validation to use. Which is bad because it breaks my automatic pre-flush validation. :-(

**Comment by ogizanagi** [comment]
@enumag : If you really want to have a method deciding which group should be used for validation, I suggest you to create your own `ValidationGroupProviderInterface` & `getValidationGroups()` method, and implement it in each of your entities where it'll be needed.
Then, simply update your pre-flush validation listener to use this method, and pass the returned groups to the `validate()` method.
