### ISSUE TITLE
Process component output with colour

### ISSUE THREAD

**Issue by samsamm777** [symfony/symfony#17010]
When running the `ls -lsa` command in a shell, it will produce output with colour. However when running the same command in a symfony process the output doesn't have colour. Is there any way I can do this?

```php
$process = new Process('ls -lsa');
$process->start();

// ... do other things

$process->wait(function ($type, $buffer) {
    if (Process::ERR === $type) {
        echo 'ERR > '.$buffer;
    } else {
        echo 'OUT > '.$buffer;
    }
});
```

**Comment by ogizanagi** [comment]
AFAIK, you should use Tty (and also specify to use color with `ls`):
```diff
- $process = new Process('ls -lsa');
+ $process = new Process('ls -lsaG'); // OS X
+ $process = new Process('ls -lsa --color="auto"'); // Linux
+ $process->setTty(true);
$process->start();

// ... do other things

+$process->wait();
-$process->wait(function ($type, $buffer) {
-    if (Process::ERR === $type) {
-        echo 'ERR > '.$buffer;
-    } else {
-        echo 'OUT > '.$buffer;
-    }
-});
```

BUT, you'll loose the ability to redirect the output or specify a callable to the `wait`, `run`, `...` methods.

**Comment by javiereguiluz** [comment]
I'm closing it as fixed thanks to @ogizanagi's answer. However, since these tty/pty/etc. features are not very well documented, I've created a new issue to improve that: https://github.com/symfony/symfony-docs/issues/6188
