### ISSUE TITLE
[3.0] Composer install dosn't copy bin/console file

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#17017]
Hi,

when creating a project with `symfony new project_name` we get a .gitignore files which contains the `/bin` directory.

Then when we deploy with git, or clone the projects to other machines for any reason, we don't get the console command because composer dosn't copy it over when running `composer install`...

**Comment by xabbuh** [comment]
Just update your installer to [1.5.0](https://github.com/symfony/symfony-installer/releases/tag/v1.5.0) by running `symfony self-update`.
