### ISSUE TITLE
Control-C on server:run does cause segfault

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony#17018]
while testing the symfony installation i does use server:run to test the site.
but when i close it as it says with CONTROL-C, it does cause a core dump.

```
bin/console server:run
Server running on http://127.0.0.1:8000

Quit the server with CONTROL-C.
^CAborted (core dumped)
```

the apport program once did say something about a `nanosleep_no_cancel` or something similar, but i can't provoke it to show that message again.

yes the program did get closed forcefully but it still should not do core dumps

**Comment by stof** [comment]
A segfault means there is an issue in PHP itself (or in one of the extensions extending the C code). So this should be reported to PHP itself (probably trying it with the ``php -S`` command directly without the ``app/console server:run`` wrapper, to make the bug report more actionable for the PHP team).
There is nothing we can do in Symfony itself to fix crashes of PHP itself
