### ISSUE TITLE
LocaleType and CountryType fields

### ISSUE THREAD

**Issue by redayoub** [symfony/symfony#17028]
Hi,

I'm using the LocaleType in a form to allow the user to select his language, as described in the doc the "value" for each language is the Unicode language identifier. I would like to display to the user in an other page the languages he selected but I have only the language code (e.g. en for english). Is there any way to covert that code to the language label ?

Same case for CountryType field.

Thanks

**Comment by Hanmac** [comment]
its possible to use the Intl module

en to english:
```php
Intl::getLanguageBundle()->getLanguageName("en") //=> "english"
```
DE to Germany:
```php
Intl::getRegionBundle()->getCountryName("DE") //=> "Germany"
```

**Comment by redayoub** [comment]
Thanks a lot. Can I use it in a twig template ?

**Comment by Hanmac** [comment]
as far as I have seen there are no twig templates for that, but it should be easy to add a filter extension for that. (that might be done in a form of feature request)

but i think more easier would be to add a method/function to the Model/Entity that returns the translated name.

**Comment by redayoub** [comment]
Ok, thanks for your help.

**Comment by Hanmac** [comment]
@redayoub i found one which does what you want:
[SonataIntlBundle](https://github.com/sonata-project/SonataIntlBundle)
specially using this functions:
[SonataIntlBundle/LocaleExtension](https://github.com/sonata-project/SonataIntlBundle/blob/master/Twig/Extension/LocaleExtension.php)

**Comment by redayoub** [comment]
Thanks @Hanmac
