### ISSUE TITLE
HttpKernel has a missing dependency on Finder

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#17038]
If you include `symfony/http-kernel` and use the bundle system, it will fail unless you have manually required `symfony/finder` due to this line: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Bundle/Bundle.php#L171

But actually, the only thing that uses this is `Application` from `FrameworkBundle`. So, the dependency should maybe be added to `symfony/framework-bundle`... but really, it's a bit odd that the `Bundle` class in `http-kernel` holds the `registerCommands()` logic.

Options:
A) Add `symfony/finder` to `symfony/http-kernel`: (seems like overkill, but the most technically correct)
B) Add `symfony/finder` to `symfony/framework-bundle` (practical)
C) Something else :)

Thanks!

**Comment by stof** [comment]
Bundles are an optional feature of HttpKernel, so adding the Finder dependency in it is bad. It is an optional dependency.
Adding it to FrameworkBundle looks good to me

**Comment by iltar** [comment]
In my opinion, registering commands is not a task of the bundle. Moving this part outside of a bundle, makes it easier to add (non Command as a Service) commands to an application without bundles.

Couldn't this become a compiler pass in the framework bundle instead? That would totally remove the need of the finder in the component in this case.

**Comment by weaverryan** [comment]
@stof supports the easy way. So we can *at least* do that.

But @iltar your idea is interesting - do you have a specific idea?

**Comment by xabbuh** [comment]
@iltar But that would be a BC break for people using that feature of the component without the FrameworkBundle.

**Comment by iltar** [comment]
@xabbuh we're good at providing BC layers :+1: 

@weaverryan just had some vague ideas how a compiler pass, app kernel or application can do this. I think the application would the most suited due to the nature of calling the original bundle loading process (if I remember correctly).

**Comment by xabbuh** [comment]
@iltar Sure, but that's a new feature then.

**Comment by xabbuh** [comment]
see #17057
