### ISSUE TITLE
No performance tab with PHP7

### ISSUE THREAD

**Issue by WebDevTmas** [symfony/symfony#17030]
I just updated to PHP7 (on ubuntu 14.04) with puphpet.
I ran into some problems, like no php-redis or apc but now all I'm left with is that I don't have the performance tab.

With subrequest I even get an error

    Key "__section__" does not exist as the array is empty in @WebProfiler/Collector/time.html.twig at line 71

It's as if the TimeDataCollector is not working? I can't figure out what's happening.

**Comment by jakzal** [comment]
I have just tested this on latest 2.7, 2.8 and 3.0, and I can see the performance tab just fine.

Please try to reproduce your issue on a vanilla standard edition project.

**Comment by jakzal** [comment]
Here's another report complaining on the performance profiler in PHP 7: #16836.

**Comment by WebDevTmas** [comment]
Confirmed issue on NFS shared folders through vagrant. But not on a normal share.
I'll look for help in another place since the issue is not symfony.
Thanks anyway.

**Comment by WouterJ** [comment]
@jakzal, why did you close this issue, as it's still a valid issue, isn't it?

**Comment by jakzal** [comment]
@WebDevTmas is it? The original reporter said it's not a Symfony issue. We also don't have a reproducible scenario.

**Comment by nightmarepl** [comment]
Same here, but I'm not using vagrant nor NFS folders. It happened right after upgrade to 2.8 and happens only when there are sub-requests.

**Comment by jakzal** [comment]
@nightmarepl if you're able to provide code that would reproduce your issue, we can reopen here.
