### ISSUE TITLE
[DX] - Switch user from WDT

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#17034]
It would be good if the security section in WDT provide a way to switch users in development environments.

**Comment by stof** [comment]
How would this look like to you ?

**Comment by javiereguiluz** [comment]
@tsantos84 I can't find the exact discussion, but I remember discussing about this feature in the past. If I recall it correctly, it was discarded because it was "impossible" to develop that feature in a generic way.

**Comment by tsantos84** [comment]
The new security section has an action to logout the user. I think that one more action could be the impersonation feature. What you think about it?

**Comment by stof** [comment]
@tsantos84 logout is a matter of displaying a link to the logout url, which is known by Symfony.

For the impersonification, we could only build a form asking you to enter a username, and letting you provide a valid one. I'm not sure this would provide much benefit.
Building something more complex letting you choose a user is not possible, as Symfony has no way to know the list of available users (there is no such requirement for user providers, and we won't add it as it would reduce their power)

**Comment by tsantos84** [comment]
Hi @stof, I know that the logout is a single link that Symfony already knows. Maybe a predefined list of users that you can display them in a select box. To make this feature as generic as possible, it could have a config on WebProfilerBundle like this:

web_profiler:
    security:
        switch_user: true
        users: ["admin_user", "guest_user", "super_admin_user"]

**Comment by Sander-Toonen** [comment]
Well, we could just show an input field with a button.
Onclick we could load <current url>?<firewall.switch_user.parameter setting>=<content input field> but the user then needs to know the username, I'm not sure whether this is much an improvement over typing in the url yourself...

**Comment by tsantos84** [comment]
I agree that this is not a big improvement, but it saves our time building the url to switch the user. As I said early, putting a dropdown field with a predefined set of known users (eg. Admin, Super Admin, Editor...) would be better than typing the user name.

**Comment by bitgandtter** [comment]
Maybe the best way is to use the in_memory section of user defined and use it. That way no new sections need to be introduced and its all integrated. For SF will be really easy to read those users and its roles and display it on the toolbar

**Comment by GromNaN** [comment]
This is what I started working on. 

https://github.com/symfony/symfony/pull/14458

**Comment by rvanlaak** [comment]
Also tried this myself in #17037 but as long as the collector can't reach the configuration parameters this isn't possible (yet).

**Comment by stof** [comment]
@bitgandtter your suggestion works only if the memory provider is used. And most projects probably load the users from a database rather than from an hardcoded list in the config

**Comment by tsantos84** [comment]
I agree with @stof. Using only the in_memory provider will not meet all needs. I see two ways to achieve this issue: A list of predefined users that we can choose one of them on WDT or an input field where we only type the user we can switch to as tried by @GromNaN.

**Comment by ihsanudin** [comment]
Better way is switch role not switch user

**Comment by calinpristavu** [comment]
A role switch might have side effects. If, for any reason, the user entity is ever persisted during the role switch, you'll end up changing the persisted roles of that user.

IMHO this is not a generic use case, and should be up to the users to implement it for specific use cases

:-1:

**Comment by stof** [comment]
And this will not be easier to implement either: there is no list of roles anywhere in Symfony either (the role hierarchy knows about some of them, but you might have other roles).
And adding or removing only some roles to the user does not solve the same use case, as you might have custom voters which are not based on roles for their security checks, but on business rules (in my work project, 99% of permission checks don't involve roles but business rules in custom voters)
