### ISSUE TITLE
[WDT] hover overlay problem in google chrome

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#17045]
I'm not entirely sure something can be done about it, it but as of 2.8 I have this problem more than with previous versions.

![Chrome link hover](http://i.imgur.com/xdMMiLB.png)

The problem occurs mainly when you hover over the translation bar and everything to the right of it. When you hover to anything left of it, the hover occurs on the right side thus doesn't go over anything. As I said, I'm not sure anything can be done about this as it's more of a google chrome issue.

**Comment by javiereguiluz** [comment]
I can't reproduce (Chrome 47, Mac): the bottom bar moves downwards when it interferes with the first elements of the toolbar:

![toolbar](https://cloud.githubusercontent.com/assets/73419/11864356/24acba4c-a49c-11e5-993a-7964a852b9bb.gif)

I've looked for and it seems impossible to hide or change the behavior of that bar in a safe way.

**Comment by iltar** [comment]
I should note that I'm on 46, Ubuntu 14.04. I know this feature is in there for quite a while already now that you mention it. I've just tested it with a non-full-screen window and it infact works. However, considering my screen is 1440x900, I already have limited space as is so this won't fix it for me.

If there's no way to manipulate this behavior, I will close this and ask _yet again_ for bigger screens.
