### ISSUE TITLE
[RFC] Convention to load template without override

### ISSUE THREAD

**Issue by xavierleune** [symfony/symfony#17054]
Hi,

Actually in symfony, when you want to override a template from a bundle, you have to override this template into your app/Resources/OverridenBundle. But you actually have to **copy/paste** this template.
If you try to extend it, you will fall into an infinite loop, as the loader will try to load the overriden template, which try to load the overriden template, etc.

Of course if your bundle has some "extension point" (in fact, like sonata, you can have in your bundle a template "myfeature_full.html.twig" and a template "myfeature.html.twig" which just extends the full template, allowing overriden templates to uses blocks and so) you can use it. But it needs more template and the bundle you want to override must allow this.

Actually there is no technical way to bypass this behaviour and a little convention can do the trick.

Let's imagine the convention is to add the "!" mark at the beginning of the name of the template when you want to extends it, you'll be able to do that kind of thing:

src/vendor/ccmbenchmark/mybundle/src/Resources/views/base.html.twig
```twig
    {% block title %}<h1>Hello</h1>{% endblock %}
    {% block content %}
         {# big content with some logic i don't want to copy/paste #}
     {% endblock %}
```

app/Resources/MyBundle/views/base.html.twig
```twig
    {% extends '!MyBundle::base.html.twig' %}
    {% block title %}<h2>Hi !</h2>{% endblock %}
```

The "!" basically say's "Hey, let's drop off all override. I just want **this** template from **this** bundle".

What do you think about this feature? Actually that would be very useful in a lot of cases and will just help to empower bundles !

If this was accepted, I would agree to dev this feature.

/cc @dunglas

**Comment by dunglas** [comment]
:+1: for me. We dived into the code and this feature can be added without introducing too much complexity.

**Comment by jakzal** [comment]
I'm not convinced this should be something we support. I don't like the idea of a new convention (with `!`). Also, if I'm overriding a template of a third party bundle I'd rather override it fully. Otherwise it could mess things up when bundle gets updated.

**Comment by xavierleune** [comment]
@jakzal of course it can be something else than !. About the bundle upgrade, things can already be messing up when you fully override it.
Variables passed to the templating can be changed in the bundle as it's not part of the api. I think that we can reduce that by reducing the amount of code overriden with this feature.

When you override only some blocks you are in fact depending of a smaller amount of code. 

Actually many workarounds are used by the community to allow this very small and simple feature. I really think it should be a part of the framework.

Of course I proposed a convention because it's easy to code / use / understand but if you have any better idea I'm ready to discuss around it!

**Comment by oxman** [comment]
:+1:

**Comment by alfmartinez** [comment]
Nice feature to have.

**Comment by ewgRa** [comment]
:+1: I think nice to have.

As for me more understandable will be:
```
{% extends_exactly 'MyBundle::base.html.twig' %}
{% extends 'MyBundle::base.html.twig' exactly=true %}
```

or something like this

**Comment by Nicofuma** [comment]
Actually couldn't you use the twig native notation to do that? (`@My/base.html.twig`)

**Comment by jverdeyen** [comment]
:+1: I'm currently using this bundle for the same reason:
https://github.com/boekkooi/TwigJackBundle

**Comment by xavierleune** [comment]
@ewgRa for sure your proposition is interesting. But actually adding a new filter / parameter will ask a lot of code. And this will make more code to maintain.

@Nicofuma unfortunately, this doesn't work.

@jverdeyen thks for the link, it's interesting! I'd rather have this into a native standard edition.

**Comment by iltar** [comment]
I've never need the functionality before to be honest. In my opinion you should avoid overriding and extending 3rd party bundle templates and use embedding instead.

**Comment by xavierleune** [comment]
@iltar Actually I surely can understand why you never used this functionality. But there is many cases where you need to override third party bundles (i.e look at sonata).
And to be completely honest, I need it everyday to override my own bundles. I think a lot of companies can have the same use case. For example when you produce an internal bundle but you need to customize a little the templating for some implementations. Copying the template is unefficient or use embedding doesn't make sense, because you use the Controller provided by the bundle so you can't choose the template used.

**Comment by iltar** [comment]
@xavierleune I understand your point of view and my company had the same. We've decided to solve it differently though.
 - Is it a stand-alone template and doesn't require to extend the main template? Can be a self-sufficient template in the bundle with a controller.
 - Is it like a small re-usable part you'd like to include but with logic? Same as above but without extending anything
 - Same as above without logic? include or embed. We use the embed solution to render a navigation bar in every application. 

From my experience, having (internal) vendor bundles with routes and controllers gives more of a headache than worth it. Controllers should in my opinion remain in applications and not bundles to avoid weird constructions such as overrides.

**Comment by xavierleune** [comment]
@iltar thanks for you feedback and sorry for the lag. I understand your point of view, but actually the more I think to this, the more I think I really need this kind of extension.
Actually we are working on major websites across 11 languages. These websites will share some "sections" of sites. So my bundle can provide a lot of actions (so a lot of templates). Without the ability to override the template from my bundle, without copy/pasting, I will have to use a lot of little hacks to reduce maintenance costs.

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. Since this has been asked a lot of times and there are several issues that ask the same, I've created a new issue to centralize the discussion. That's why I'm closing this and I invite you to join #17557 to help us implement this feature. Thanks!

**Comment by xavierleune** [comment]
@javiereguiluz ok thanks for your feedback, I'll join on #17557 !
