### ISSUE TITLE
BC Break regression in ParameterBag

### ISSUE THREAD

**Issue by craigh** [symfony/symfony#17058]
Here: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/ParameterBag.php#L271

The error type is set as `E_USER_ERROR` when it should be `E_USER_DEPRECATED`. using `E_USER_ERROR` throws non-recoverable exception and breaks the site whether `env:prod` or `env:dev`. 

changing it to `E_USER_DEPRECATED` fixes problem for me.

**Comment by xabbuh** [comment]
see #17059
