### ISSUE TITLE
Yaml Parser fails to parse ansible configuration files

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony#17068]
I don't know whether ansible is not YAML standard compliant, but a valid yaml configuration like:

```yaml
---
- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'
```

is not accepted as valid. This makes http://insight.sensiolabs.com complains and declaring many critical violations.

I tested this with www.yamllint.com and there are no issues.

**Comment by xabbuh** [comment]
What exceptions do you get?

**Comment by bburnichon** [comment]
Don't really know. Insight support told me they use symfony yaml parser component.

**Comment by xabbuh** [comment]
This indeed looks like a bug to me. The error message is:

> Unable to parse at line 4 (near "            regexp='date.timezone ='").

**Comment by xabbuh** [comment]
closing as a duplicate of #11109
