### ISSUE TITLE
Problem with security.authentication.provider.dao after upgrade to 2.8

### ISSUE THREAD

**Issue by alxishin** [symfony/symfony#17066]
I'm using IMAGLdapBundle, and have following error after upgrade to 2.8:
> ContextErrorException in DaoAuthenticationProvider.php line 43:
Catchable Fatal Error: Argument 2 passed to Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider::__construct() must implement interface Symfony\Component\Security\Core\User\UserCheckerInterface, string given

This wrong code generated in 2.8:
> protected function getImagLdap_Security_Authentication_Provider_ImagldapService()
>    {
>        $a = $this->get('imag_ldap.security.user.provider');
>
>        return $this->services['imag_ldap.security.authentication.provider.imagldap'] = new \IMAG\LdapBundle\Provider\LdapAuthenticationProvider($a, new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider($a, '', 'imagldap'...

And this worked code from 2.7:
>    protected function getImagLdap_Security_Authentication_Provider_ImagldapService()
>    {
>        $a = $this->get('imag_ldap.security.user.provider');

>        return $this->services['imag_ldap.security.authentication.provider.imagldap'] = new \IMAG\LdapBundle\Provider\LdapAuthenticationProvider($a, new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider($a, $this->get('security.user_checker'), 'imagldap'...

Problem with security.user_checker service.
I found solution: if I change this lines in 
> vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/config/security_listeners.xml

it worked fine for me.
Before:

>        <service id="security.authentication.provider.dao" class="%security.authentication.provider.dao.class%" abstract="true" public="false">
>            <argument /> 
>            <argument /> 

After:
>        <service id="security.authentication.provider.dao" class="%security.authentication.provider.dao.class%" abstract="true" public="false">
>            <argument /> 
>            <argument type="service" id="security.user_checker" />

Can you help me solve this problem?

**Comment by ChadSikorra** [comment]
This seems like a problem in the IMAGLdapBundle. If they are going to use the DAO auth provider in their LoginFactory then they should update it to account for the changes reflected in this commit: https://github.com/symfony/symfony/commit/76bc662463b7138981496e5d46d46f4e1dd6a756. At least that's what it looks like to me.

**Comment by alxishin** [comment]
Thank you, this is bug in IMAGLdapBundle. I think issue must be closed.
