### ISSUE TITLE
IntlDateFormatter leniency

### ISSUE THREAD

**Issue by EmanueleMinotto** [symfony/symfony#17065]
I don't know if this is related to symfony, the intl extension of PHP itself (sorry if I'm opening the issue for nothing).

Currently the `Symfony\Component\Form\Extension\Core\Type\DateType`, if the format is `dd/MM/yyyy` solves it to the same format into the `\IntlDateFormatter`, but that's not always accepted, instead the translated format `d/m/Y` gives me this exception:
```
The "format" option should contain the letters "y", "M" and "d".
Its current value is "d/m/Y".
```

This snippet gives an example: https://3v4l.org/piDJR

Some related issues/PRs I found:
* https://github.com/symfony/symfony/pull/4434
* https://github.com/symfony/symfony/issues/12114

**Comment by jakzal** [comment]
> instead the translated format d/m/Y gives me this exception

How did you configure date type to get this exception? Indeed this is an invalid format as "m" means minutes here.

**Comment by EmanueleMinotto** [comment]
sorry, my mistake
