### ISSUE TITLE
Documentation for symfony/validator is wrong around validateValue

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony#17064]
https://github.com/symfony/validator/blob/master/README.md

I was trying to validate a single value against a constraint, as per documentation above:

```php
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints\Length;

$validator = Validation::createValidator();

$violations = $validator->validateValue('Bernhard', new Length(array('min' => 10)));
```

However, `validateValue` is no longer under s3, and there's no word on how to accomplish what `validateValue` used to do. `validateValue` was super handy when validating single values without having to tie everything up with entities and whatnot.

**Comment by ogizanagi** [comment]
Hi @luispabon. 
You should give a look to the book on symfony.com about ["Validating Values and Arrays"](http://symfony.com/doc/current/book/validation.html#validating-values-and-arrays).

In sf 3, you should simply use the `validate` method:
```php
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints\Length;

$validator = Validation::createValidator();

$violations = $validator->validate('Bernhard', new Length(array('min' => 10)));
```

I guess the README.md file of the `symfony/validator` component should indeed be updated, though.
