### ISSUE TITLE
2.6 impersonate user with special characters

### ISSUE THREAD

**Issue by mrTorb** [symfony/symfony#17062]
if you try to impersonate a user that has special character, like swedish å,ä or ö, in his username I can't get this to work. Have tried twigs filter "url_encode", with no no success.
example
?_switch_user=Göran
?_switch_user=G%C3%B6ran

Is this perhaps fixed in later versions?

**Comment by xabbuh** [comment]
Symfony 2.6 doesn't get bug fixes anymore. Can you reproduce your issue on Symfony 2.7 or higher?

**Comment by paradajozsef** [comment]
@mrTorb can you try it on 2.7 or higher?

Status: Needs Work

**Comment by mrTorb** [comment]
unfortunately, I have no time, at the moment, to upgrade, or to make a test with a higher version. I plan to upgrade to 2.8 later in spring.

**Comment by xabbuh** [comment]
Okay, closing here for now then. Feel free to leave a comment with instructions how to reproduce your issue when you still have it on maintained Symfony versions and we can then reopen.
