### ISSUE TITLE
Issues on toolbar when user is logged in and tries to logout

### ISSUE THREAD

**Issue by paquitodev** [symfony/symfony#17060]
I am working in a Symfony 2.8 and I am using latest FOSUser (`~2.0@dev`). This is how the `security.yml` looks like:

    security:
        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
    
        providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email
    
        firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false
    
            main:
                pattern: ^/
                anonymous: ~
                logout: true
    
                form_login:
                    provider: fos_userbundle
                    csrf_provider: security.csrf.token_manager
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
    
                remember_me:
                    secret:   '%secret%'
                    lifetime: 604800 # 1 week in seconds
                    path:     /
    
        access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    
            - { path: ^/admin/, role: ROLE_ADMIN }

Now take a look to this picture:

![2015-12-17_21-49-03](https://cloud.githubusercontent.com/assets/627886/11888139/834147c8-a508-11e5-8120-e0687c2934bb.png)

As you can see (1) the URI points to `app_dev.php` so I am working on DEV environment (2) user is authenticated (3) although `logout` link points to non DEV env as shown in (4) which cause wrong logout route. Is this a issue or I miss something in configuration?

**Comment by xabbuh** [comment]
Thanks for reporting this bug @paquitodev. However, I close here as it is a duplicate of #17029 which will be fixed by #17048 and #17049.
