### ISSUE TITLE
Symfony/Yaml: objectSupport is ignored.

### ISSUE THREAD

**Issue by IngwiePhoenix** [symfony/symfony#17075]
Testcase:
```php
<?php

# Load Composer
define("AUTOLOADER_FILE", realpath(__DIR__."/../php_modules/autoload.php"));
require_once(AUTOLOADER_FILE);

# Test data
$configString = <<<EOT
Group:
    owner: Ingwie Phoenix
    id: 0
EOT;

echo "--- Data: YAML ---".PHP_EOL;
echo $configString.PHP_EOL;
echo "---".PHP_EOL;

use Symfony\Component\Yaml\Yaml;
$parsedYaml = Yaml::parse($configString, false, true);
$t = gettype($parsedYaml);
if($t == "object") {
    echo "YAML was parsed and returned as object.";
} else {
    echo "YAML was parsed, but not returned as object. Got: $t";
}
echo PHP_EOL;
```

Output:
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/B/test $ php --version
PHP 5.6.14 (cli) (built: Oct  3 2015 14:54:13) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/B/test $ php LoadYamlConfig.php 
--- Data: YAML ---
Group:
    owner: Ingwie Phoenix
    id: 0
---
YAML was parsed, but not returned as object. Got: array
```

It seems that the documented `objectSupport` option is not being taken into consideration.

**Comment by WouterJ** [comment]
What you want is setting `objectForMap` (4th argument of `parse()` to true).

The objectSupport means that values starting with `!!php/object:` are treated as serialized objects.

**Comment by IngwiePhoenix** [comment]
I did a local change to my testcase above and set the fourth option to true - same result.

**Comment by xabbuh** [comment]
I tried your example and this looks indeed like a bug to me.

Status: Reviewed

**Comment by WouterJ** [comment]
See https://github.com/symfony/symfony/pull/17079 for a fix

**Comment by IngwiePhoenix** [comment]
Great! Hoping for a merge soon :)

**Comment by IngwiePhoenix** [comment]
Updated to `2.8.1` (that is what Composer said) and Parser.php line 236 and 237 fail. They both try to access `$data` as array, whilst it may as well be an object. Please re-open and/or re-review.

Lines: https://github.com/symfony/yaml/blob/2.8/Parser.php#L236-L237

**Comment by xabbuh** [comment]
@IngwiePhoenix Can you please provide a failing example?

**Comment by IngwiePhoenix** [comment]
From the top of my head:

```php
<?php
use Symfony\Component\Yaml\Yaml;
$str = "foo: bar\nbaz: derp";
Yaml::parse($str, false, false, true);
```

**Comment by xabbuh** [comment]
@IngwiePhoenix I can confirm this error (see #17190). Thanks for reporting this. I am working on a patch.
