### ISSUE TITLE
Router generator - pass param to generate URL with https protocol

### ISSUE THREAD

**Issue by mimol91** [symfony/symfony#17072]
Hello.
Symfony is missing an simple way to generate URL with https protocol.
There is a nice trick described http://symfony.com/doc/current/cookbook/routing/scheme.html, but its not what I need. (I dont want redirects http->https.)

My use case is with LoadBalancer:
Client (https) -> Loadbalancer -> symfony (http) 

I think that ```referenceType``` param for ```generate``` method could accept  ```self::SECURE_PATH``` 
To generate Secure URL it can look like ```$router->generate('route_name', [], Router::ABSOLUTE_URL|Router::SECURE_PATH)```

**Comment by Tobion** [comment]
You should use http://symfony.com/doc/current/cookbook/request/load_balancer_reverse_proxy.html so that symfony sees the requests as https. Then you do not have this problem.
