### ISSUE TITLE
How to update form integration tests in 2.8

### ISSUE THREAD

**Issue by pschultz** [symfony/symfony#17088]
During our update to 2.8 we noticed that the [cookbook article on form tests][1] is outdated.

It still says

```php
$type = new TestedType();
$form = $this->factory->create($type);
```

however, passing type instances to `FormFactoryInterface::create` is deprecated in favor of FQCNs. 

The simple example in the article is trivial to update, but we can't figure out how to do it for form types that have dependencies. Following the article back in the days, we have written tests that look something like this:

```php
// setup collaborators

$type = new MyFormType($mock1, $mock2, $moreMocksHere);
$form = $this->factory->create($type);

// submit, assert, etc.
```

Is there any documentation available on how to update these tests for Symfony 2.8?

[1]: http://symfony.com/doc/current/cookbook/form/unit_testing.html

**Comment by Tobion** [comment]
Create a form extension (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Test/FormIntegrationTestCase.php#L34) that returns your form type with the mocked dependencies.

**Comment by WouterJ** [comment]
See https://github.com/symfony/symfony-docs/issues/6053

The documentation will be updated very soon: https://github.com/symfony/symfony-docs/pull/6059
