### ISSUE TITLE
Form tests are failing because of missing options

### ISSUE THREAD

**Issue by EVODelavega** [symfony/symfony#17089]
Currently, the unit tests for the forms are failing because none of the `configureOptions` methods are setting the legacy options _"type"_ and _"options"_ correctly. These keys are being passed (eg in `CollectionTypeTest::testLegacyPrototypeData`), causing the OptionsResolver to throw an `UndefinedOptionsException`.

Proposed fix: add both keys to the defaults in `FormType` (options defaults to an empty array, type to null), and perhaps set allowedTypes for both legacy options.

**Comment by nicolas-grekas** [comment]
This has been already fixed isn't it?

**Comment by XWB** [comment]
I believe it was fixed in https://github.com/symfony/symfony/commit/bd686cd1eecad01e38794bf4ee65566e24f844b9

@fabpot When can you release Symfony 2.8.2, the `CollectionType` is broken in 2.8.1.
