### ISSUE TITLE
Symfony/filesystem Cant access to an AS400 (iSeries) repository (path)

### ISSUE THREAD

**Issue by urtziu** [symfony/symfony#17107]
Hi everyone!

I’m trying to get some .pdf from an AS400 (not a database, only a repository (windows) from the server) using filesystem from the controller, but I can’t get them. I’m guessing since the server has a login, do I need to pass the user and the password when creating the path?

The path actually is a simple one \\\ip\foldername\year\filename.pdf (I had try with this same path with a non as400 server and it works). The exact code example is this: 
>  $file=$codenum.".pdf";
$path = "\\\\192.168.X.XXX\\folder1\\20".$year."\\".$file;
$fs = new FileSystem();
 if (!$fs->exists($path)) {
    //Do something
 }else{
     //Do something
}
</code>

It’s not like I need to create a ODBC connection with the AS400 right?

Any idea or help would be great! :) 
Thanks a lot!

Urtzi.

**Comment by Tobion** [comment]
Please ask support questions on stackoverflow.
Btw, if you need to access non-local filesystems, I would look at http://flysystem.thephpleague.com/ which might be better suited.

**Comment by urtziu** [comment]
Oh, sorry about that. 
But thanks for the hint! I will check it right now.
Thank you.
