### ISSUE TITLE
VarDumper - Settings on php.ini cause no info with children array

### ISSUE THREAD

**Issue by vschoener** [symfony/symfony#17103]
Hi,

I didn't find any post about it, but is it possible to set extra settings on this component directly in the php.ini ?

My real problem, I got an array but I can't see more than the first entry lvl.. 

Array [
...
  "attributesListSelected" => array:1 []
  "attributePrice" => array:14 []
]

This was working properly when project is set under symfony but not globally.

I use it that way (globally to all my projects) : 
auto_prepend_file = C:/Users/Vincent/AppData/Roaming/Composer/vendor/autoload.php

Thanks !

Regards

**Comment by nicolas-grekas** [comment]
By default, we dump [max 2500 items](https://github.com/symfony/symfony/blob/7491c2550b8e64506c84d12371164f8033f4c6b1/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php#L118), could this be the reason in your case?
There is no ENV/php.ini way to configure this for now.

**Comment by vschoener** [comment]
Event with an array with on element having childrens this problem persist.. I have to dump my array that way when I want ti see more : dump($attributePrice[0]); for example.

**Comment by vschoener** [comment]
Here is a part of the screenshot for the problem : 
http://imgur.com/qTliqZJ

**Comment by nicolas-grekas** [comment]
Can you give us your global .composer.lock file please?
Can you share a simple reproducer?

**Comment by vschoener** [comment]
Hi,

Where is located the global one ? I didn't see him in my home directory but I can provide you one among my projects I have.

I got this problem in every project I use and I tried to move out my composer initialization code from my php.ini to a project, the problem persist

I found out a way to display my sub array info using CTRL + click on the root arrow, this allow me to expand / collapse everything but when the array is huge.. I let you imagine :)

About a simple reproducer ? How can I share you this ?

Thanks

**Comment by nicolas-grekas** [comment]
wait, the data is here, it's just hidden but you see it. Then if you CTRL+click on that arrow, it opens up and you see the content?
Then the bug is a missing arrow next to each array, nothing more.
Can you share a simple html page with a dump inside?

**Comment by vschoener** [comment]
Yes ! I found out this when I was inspecting element and find the shorcut on click reading the documentation.

The arrow is displaying at the very begining of the rendering and is hidden right after.

Did you have access to this URL (my first pen :)) 

http://codepen.io/vschoener/pen/JGNWNp

**Comment by vschoener** [comment]
Ok I just tried using 'incognito' mode and the code is working great, I'm suspecting one of my chrome plugin...

**Comment by vschoener** [comment]
And the winner is "Emoji Input by EmojiStuff.com"... Something I tried out a couple days before I report this bug..

Thanks for your time and replies. And sorry I didn't find out this before.

**Comment by nicolas-grekas** [comment]
Great, the fix was easy :)

**Comment by vschoener** [comment]
Yes ahah :)
