### ISSUE TITLE
[2.8][Debug] Error open swiftmailer debug panel when send E-mail with Attachment

### ISSUE THREAD

**Issue by am-kzl** [symfony/symfony#17100]
I can't open swiftmailer debug panel cause showed some errors.
When I send e-mail use \Swift_Message and set attachment (\Swift_Attachment).

My symfony version : 2.8.0

[ error ]
```
Method "charset" for object "Swift_Attachment" does not exist in @Swiftmailer\Collector\swiftmailer.html.twig at line 170 
```

Is this a bug ??

**Comment by stof** [comment]
This should be reported to SwiftmailerBundle (and giving the bundle version too)

**Comment by am-kzl** [comment]
thank you to reply!
I did reported to SwiftmailerBundle.
