### ISSUE TITLE
Translation:Update should throw warning if directory is missing

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#17128]
I've executed the command ``translation:update de --force`` on Windows 7 x64.

Because the ``translations`` directory did not exist the translation file was also not created.

**But I've got no error message.**

Two solutions:
a) There should be an error message.
b) The folder should be automatically created if possible. Otherwise there should be an error message.

```
> C:\xampp\php\php.exe bin/console translation:update de --force

Translation Messages Extractor and Dumper
=========================================

 // Generating "de" translation files for "app folder"
 // Parsing templates...
 // Loading translation files...
 // Writing files...

 [OK] Translation files were successfully updated.  
```

**Comment by aitboudad** [comment]
This has been fixed by  https://github.com/symfony/symfony/pull/17085

**Comment by Ener-Getick** [comment]
Can be closed then?
