### ISSUE TITLE
301 Redirect should be always cached

### ISSUE THREAD

**Issue by AlmogBaku** [symfony/symfony#17139]
Currently 301 sends `no-cache`, although it's permanently redirect, therefore it should be cached.

**Comment by jakzal** [comment]
I don't think this is a good idea. You can get into troubles if you ever change your mind as many browsers cache redirects with no expiry date. I'm not saying you shouldn't use cache headers with redirects. It just shouldn't be the default.

**Comment by Disparity** [comment]
This is the key difference: for 301 status can not be "change your mind" to redirect, as opposed to 302 status.

**Comment by ruFog** [comment]
That behaviour is not defined explicitly in [RFC2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2). And some browsers already [cache 301 redirect](http://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s). Strict implementation of extra Cache header in Symfony might be like reinventing the wheel.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by AlmogBaku** [comment]
@ruFog you right, most of the clients/browsers cache 301, but since we send "no-cache" they doesn't!
We don't need to specify anything on 301 redirects

**Comment by javiereguiluz** [comment]
This is a truly difficult issue to solve. There is a disparity of opinions and the standard doesn't define this behavior explicitly.

What should we do? Leave things as they are? Thanks!

**Comment by AlmogBaku** [comment]
@javiereguiluz I suggest to not specify caching headers on redirect 301. Let the client decide, and remove this burden from us.

The current approach create new issues with some clients, i.e. OkHttp (native client for Java): some time you wish to cache the requests in order to access them offline, the `no-cache` header prevent the client to do so without interception of the response.
The best approach imo is at least not sending `no-cache`

**Comment by xabbuh** [comment]
Not sending the header looks reasonable.
