### ISSUE TITLE
How to Log Notice error in Prod ?

### ISSUE THREAD

**Issue by acrozes** [symfony/symfony#17148]
Is add ```Debug::enable(E_ALL, false); ```the right way to log PHP Notice errors in prod (sf 2.8) ?
I don't find any doc about the customization of logs in prod ...

**Comment by jakzal** [comment]
Have a look at http://symfony.com/doc/current/reference/configuration/monolog.html and please use other [available channels](http://symfony.com/support) for support questions. Github is only used for development.

**Comment by acrozes** [comment]
This config don't log PHP Notice but PHP Notice have a warning level, so it should ?  

```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%serveur%_%kernel.environment%.log"
            level: debug
```
