### ISSUE TITLE
[2.X] Using a translation into another translation

### ISSUE THREAD

**Issue by cyberomulus** [symfony/symfony#17158]
Hello, 

I would use a translation into another translation

Sample (in yml file):
```
sample:
    hello: Bonjour
    gerard: {sample.hello} Gérard
```
Is it possible ?
Thank

**Comment by iltar** [comment]
No that's not possible, not sure if it's desired to have but I personally would like to have it.

**Comment by Ener-Getick** [comment]
:+1:
IMO we should use the same syntax used for the container parameter:
```yaml
gerard: %sample.hello% Gérard
```

**Comment by iltar** [comment]
Isn't that syntax already recommended for parameters? I think this would cause too much overhead for something run-time and should be compile time only. This could probably be done when building the cache by adding a second pass that iterates over translations (recursively).

This would leave out parameterized translations though.

**Comment by fabpot** [comment]
What is the use-case? I mean, translations only make sense for whole sentences; translations of words rarely make sense.

**Comment by iltar** [comment]
A telephone number for example, you could put your companies number in a variable which you can then  sub-translate in a bunch of messages. It could also go for specific domain words such as "Webhosting" vs "Hosting". They can be used to ensure a certain level of consistency through your application. 

I'm not saying this is a "must have" feature as there's a lot of different ways you can achieve the same and in the current state it's far from being complex which makes it easy to manage for non-developers..

**Comment by xabbuh** [comment]
How do you see this process happen? Will the translator pass any translated message that contains some special characters back to the translator? Or do you like to pass some additional "parameters" instead?

**Comment by iltar** [comment]
I'm not quite familiar with those concepts but my best guess is that it will check for a specific character in the message and if so, resolve that value by pre-translating it already. If that message also contains a special character, resolve that etc.

**Comment by aitboudad** [comment]
:+1:  see #17164

**Comment by dosten** [comment]
Given the feedback received in the related PR maybe this can be closed right?
