### ISSUE TITLE
MergeDoctrineCollectionListener breaks use of Entity Listener with many-to-many associations

### ISSUE THREAD

**Issue by Ranmus** [symfony/symfony#17154]
I want to use Doctrine's functionality called Entity Listener for tracking some entity changes. I have two entities named Sensors and Parameters. Each Sensor can have multiple Parameters and same Parameters can be also used with different Sensors, so i use many-to-many association between them. Next, i would like to allow add/remove some/all Parameters from Sensor any time and track history of these associations. Entity Listener is perfect solution in this situation.

For this i've created Entity Listener called SensorsListener and added event preUpdate for catching changes made to Sensor entity. But... many-to-many association is collection type and if it has field property named "multiple" set to true, then Symfony's MergeDoctrineCollectionListener is added as event subcriber (DoctrineType class):

``` php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['multiple']) {
            $builder
                ->addEventSubscriber(new MergeDoctrineCollectionListener())
                ->addViewTransformer(new CollectionToArrayTransformer(), true)
            ;
        }
    }
```

It checks if all items from collections were removed, and if yes, then instead of "raw" deleting of items, calls clear method for optimization purposes:

``` php
class MergeDoctrineCollectionListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        // Higher priority than core MergeCollectionListener so that this one
        // is called before
        return array(FormEvents::SUBMIT => array('onBind', 10));
    }

    public function onBind(FormEvent $event)
    {
        $collection = $event->getForm()->getData();
        $data = $event->getData();

        // If all items were removed, call clear which has a higher
        // performance on persistent collections
        if ($collection instanceof Collection && count($data) === 0) {
            $collection->clear();
        }
    }
}
```

If i have for example some Sensor with associated 5 Parameters and i delete 3 of them, it's all ok, but when i remove all Parameters then preUpdate event isn't triggered. Because of clearing collection, Doctrine doesn't know what changes are truly made and doesn't qualify Sensor entity in unit of work as updated.

Workaround for this issue is to add postLoad event for grabbing actual associations and compare them with associations in preFlush state, but in optimization view, it doesn't make sense, because now in whole application where Sensors are used - all of associated Parameters are loaded also.

If i comment line `$collection->clear();` then preUpdate is triggered properly.

I would like to suggest to add some new boolean option to EntityType field, like raw_update or no_optimizations, that will block static usage of clear collection when deleting all associations. It will make Entity Listeners to work with collection types correctly without any workarounds.

**Comment by friizer** [comment]
Same issus here,

I have tried to use Doctrine Event Listener with onFlush.

Once I comment the $collection->clear() line inside the listener, the removed association appears in unitOfWork, and can be queried by $uow->getScheduledCollectionUpdates(), getDeleteDiff() as an entity, when a form posted with empty association data.

**Comment by HeahDude** [comment]
Have you tried to set the `empty_data` option to add an empty value.

That way the count wouldn't be "0" and the `allow_delete` option should take care of it.

**Comment by Ranmus** [comment]
> Have you tried to set the empty_data option to add an empty value.
Yes, i've tried but it's not working. Tried also to add new empty entity as empty_data, but i dont see any change.

**Comment by HeahDude** [comment]
Would this be acceptable to fix your use case and keep performance:
```php
public function onBind(FormEvent $event)
{
    $collection = $event->getForm()->getData();
    $data = $event->getData();

    // If all items were removed, call clear which has a higher
    // performance on persistent collections
    if ($collection instanceof Collection && count($data) === 0) {
        $collection->map(function ($v) { return null; });
    }
}
```

??

**Comment by friizer** [comment]
Yes, it's working with the $collection->map(....

**Comment by HeahDude** [comment]
@friizer Thank you for the feedback :)

**Comment by HeahDude** [comment]
@webmozart Any lead here ?

Is there a problem of configuration ?
This should be handled by `allow_delete` option, right ?

Maybe we could pass this option to the constructor as for `MergeCollectionListener` and apply my fix dynamically ?

**Comment by webmozart** [comment]
As far as I understand, this is nothing we can (should?) fix. Calling `clear()` seems like the proper thing to do if all items of a collection were removed. I think you are looking for a solution to catch `clear()` events, but that seems more of a Doctrine issue.

/cc @beberlei

**Comment by xabbuh** [comment]
@HeahDude Would you like to open a PR with the fix you suggested?

**Comment by HeahDude** [comment]
Ok, I've got some time until next patch release.

**Comment by fabpot** [comment]
@HeahDude Time is up :)

**Comment by Ranmus** [comment]
@fabpot: I almost forgot about this, because i'm using patch in every project that uses Symfony. :) Patch just comments lines 63-65

@webmozart I think that is not a Doctrine issue, because simple clearing Collection with "clear" method should work exactly like it works now - without checking state of Collection, if it was empty or not.

**Comment by Ocramius** [comment]
I'd need feedback on https://github.com/doctrine/doctrine2/pull/7120 too - to me, the change looks correct, but possibly massive BC break due to change in behavior. Anyone having a better overview of the problem here is welcome to provide their opinion there.

**Comment by xabbuh** [comment]
I am closing here as this seems to be addressed in Doctrine itself (see doctrine/doctrine2#7120).
