### ISSUE TITLE
[DependencyInjection] Create a new trait or class to resolve values with the container

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#17160]
Actually, to resolve a value we can use [`ParameterBag::resolveValue()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php#L170) which is accessible [in the `Container`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Container.php#L113).
This works fine but the problem is when we want to resolve a value at runtime and we have a custom `ContainerInterface` instance.

So I would like to have a trait or a class which would allow to resolve values without an access to a `ParameterBag` instance.

You can find [an example of use case in `FOSRestBundle`](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Request/ParamFetcher.php#L139) where we need to resolve values at runtime.
We actually use [a trait](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Util/ResolverTrait.php#L21) but I'd prefer to use something from the core.

**Comment by xabbuh** [comment]
Generally, this would be possible. We would need something like a `ParameterResolver` service. The only issue I see is that the `ContainerInterface` and the `ParameterBag` class have different ways to access a value. So we would need to create the resolver with a callback which knows how to retrieve the underlying value. We can then reuse this class in the `ParameterBag` itself.

**Comment by Ener-Getick** [comment]
I created a new ``ParameterResolver`` in #17192 if you could review it @xabbuh :smile:

**Comment by javiereguiluz** [comment]
Closing as fixed by #25288.
