### ISSUE TITLE
Translator's setConfigCacheFactory isn't part of interface breaking default FrameworkBundle DIC config on override

### ISSUE THREAD

**Issue by FabriZZio** [symfony/symfony#17165]
In the FrameworkBundle's translation.xml DIC configuration, the `setConfigCacheFactory` is being called using `callMethod` here:

https://github.com/symfony/symfony/blob/586c58a354932711bb71fcedca17f86ae5119d2a/src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.xml#L17

This method isn't part of the `Symfony\Component\Translation\TranslatorInterface`, so when using another instance as default translator implementing this interface, the default DIC configuration breaks. (for example by override the `translator.class` parameter in DIC)

Override of Translator class:
````
# app/config/config_test.yml
parameters:
    translator.class: Project\Component\Test\Translator\NullTranslator
````

```
namespace Project\Component\Test\Translator;

use Symfony\Component\Translation\TranslatorInterface;

class NullTranslator implements TranslatorInterface
{
    public function trans($id, array $parameters = array(), $domain = null, $locale = null)
    {
        return $id;
    }

    public function transChoice($id, $number, array $parameters = array(), $domain = null, $locale = null)
    {
        return $id;
    }

    public function setLocale($locale)
    {
    }

    public function getLocale()
    {
        return '--';
    }
}
```
When running cache:clear (for instance during composer install)
```
# export SYMFONY_ENV=test && composer install
...
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined method Project\Component\Test\Translator\NullTranslator::setConfigCacheFactory() in /project/app/cache/test/appTestDebugProjectContainer.php:6183
```

Adding `setConfigCacheFactory` doesn't seem the way to go here. Overruling the `translator.default` service in the DIC configuration fixes this issue, but maybe there are more elegant ways to solve this...

**Comment by iltar** [comment]
@FabriZZio overriding `translator.class` is deprecated and in the future those parameters will be removed. If you want to implement your own translator, you will either have to replace the definition (or alias it), or use service decoration.

**Comment by derrabus** [comment]
The `*.class` parameters are a bad extension point and this is why they have been removed in Symfony 3. There is no guarantee that a service definition only calls methods defined in a generic interface. In fact, service definitions are always implementation-specific, since usually the interface does not define the dependencies of a class.

**Comment by FabriZZio** [comment]
Ok, thank you!
