### ISSUE TITLE
[Form] Binding null on object property

### ISSUE THREAD

**Issue by jvahldick** [symfony/symfony#17167]
I´m trying to use label as a field, but always bind a null value on object.

*FormType*

```php
$builder
	->add('name', 'text', array(
		'label'                 => 'xxx.form.name',
		'translation_domain'    => $this->translationDomain,
		'constraints'           => array(
			new NotBlank()
		)
	))

	->add('label', 'text', array(
		'required'              => false,
		'label'                 => 'xxx.form.label',
		'translation_domain'    => $this->translationDomain
	))
;
```

*Model*

```php
public function setLabel($label)
{
	$this->label = $label;
	
	return $this;
}

public function getLabel()
{
	return $this->label ?: $this->name;
}
```

When I change getLabel method to _"return $this->label"_, no problem happens.
The forms expect this "null" result or there's something wrong?

**EDITED**
I forgot a detail, the null is returned when the previous field "name" has the same value.

**Comment by xabbuh** [comment]
To be honest, I do not understand your question. Do you think you found a bug? And if so, what did you expect but what happened instead?

**Comment by assoum891** [comment]
@jvahldick which is null precisely? 
*the null is returned when the previous field "name" has the same value*
same value as what?

**Comment by jvahldick** [comment]
@xabbuh Yes, I think it´s a bug.

@assoum891 
I have 2 form fields: "name" and "label".
I fill the fields with the same value, like "foo".

![img-01](https://cloud.githubusercontent.com/assets/1113015/12049914/ea0fff1e-aed4-11e5-9f2f-d4aa770a6408.png)

The Request object it´s exactly I am expecting.
![img-02](https://cloud.githubusercontent.com/assets/1113015/12049920/02e549fe-aed5-11e5-89f0-f7b45826769d.png)

After execute handleRequest, my $form->getData() don´t bind _label_ field
![img-03](https://cloud.githubusercontent.com/assets/1113015/12049978/a7cd1eba-aed5-11e5-8145-68222968a328.png)

When I change the method getLabel() **from**:
```php
public function getLabel()
{
    return $this->label ?: $this->name;
}
```

**To:**
```php
public function getLabel()
{
    return $this->label;
}
```

Then the label *field* is binded correctly.

**Comment by xabbuh** [comment]
@jvahldick Could you please fork the Symfony Standard Edition and make the minimum set of required changes to reproduce your problem?

**Comment by jvahldick** [comment]
@xabbuh ty for help.

done at: https://github.com/jvahldick/symfony-standard
branch issue/17167

https://github.com/jvahldick/symfony-standard/commit/17db8b17cb0ec3ef164f27a9dd9043a129aafb64

**Comment by xabbuh** [comment]
Ah, now I understand your issue. The thing is that your `name` property is handled first and due to how your getter method is implemented the `label` property is considered to be not changed in the data mapper: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php#L92-L94

I do not think that we should consider this to be a bug.

**Comment by assoum891** [comment]
@jvahldick  thx for the explanation :)
@xabbuh thx for the anwser, yes apparently if the data in the form is not different from the data returned by the propertyAccessor, the update is not proceeded...

**Comment by assoum891** [comment]
@jvahldick thx for the explanation :)
@xabbuh thx for the anwser, yes apparently if the data in the form is not different from the data returned by the propertyAccessor, the update is not proceeded if the $data is not an object

**Comment by assoum891** [comment]
@jvahldick thx for the explanation :)
@xabbuh thx for the anwser, yes apparently if the data in the form is not different from the data returned by the propertyAccessor, the update is not proceeded...

**Comment by jvahldick** [comment]
Thanks for explanation guys..
Interesting class.

http://symfony.com/doc/current/reference/forms/types/form.html#by-reference solves my problem, but I really don´t know why.

It is it?
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L169-L179
