### ISSUE TITLE
[WebProfiler] request object passed to url generator

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#17178]
in [this commit](https://github.com/symfony/symfony/commit/4bffacc942a071ace5e7e6f2e04eaba9590b6a02#diff-8865c310993bd11e65b844f7439a34c8R356) @rvanlaak has added the request object as argument for the route generator. This is a BC break for a package I wrote which accepts objects as arguments. Can I remove this argument as objects are not being handled by the symfony url generator anyway? Currently this breaks my last X request page with a fatal error which means I have to go back to 2.7.

**Comment by stof** [comment]
this indeed looks like a mistake

**Comment by rvanlaak** [comment]
The router needs all query parameters for the filtering to work. Based on [the](https://github.com/symfony/symfony/blob/4bffacc942a071ace5e7e6f2e04eaba9590b6a02/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L112) [other](https://github.com/symfony/symfony/blob/4bffacc942a071ace5e7e6f2e04eaba9590b6a02/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L160) [`$request`](https://github.com/symfony/symfony/blob/4bffacc942a071ace5e7e6f2e04eaba9590b6a02/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L210) entries in that controller I did assume that that specific action could also use it. Should these also be removed?

Did remember the request object not being available in the view, so :+1: for #17179 if that was a mistake.

**Comment by iltar** [comment]
@rvanlaak it's only an issue when generating urls. In your case you are rendering templates which is all fine as far as I can tell
