### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by cn007b** [symfony/symfony#17172]
Sorry i added this issue, and then found solution for my issue...

Sorry...

**Comment by jvahldick** [comment]
Look at:
https://github.com/symfony/symfony-standard/commit/2bee277feb6c6a02e4828f772cd0945d841f6c51

You can install it like a component:
https://github.com/symfony/assetic-bundle

**Comment by cn007b** [comment]
Yeah, i found it, thank you!)

**Comment by dosten** [comment]
Can you close this?
