### ISSUE TITLE
[3.0.1][CRUD] CamelCase error inside newAction

### ISSUE THREAD

**Issue by mboron83** [symfony/symfony#17182]
During crud generation with generate:doctrine:crud command there is a CamelCase bug inside newAction of generated controller. For instance, when my entity name is "DefinitionCategory" during crud generation inside newAction my object variable has name $definitionCategory. But couple lines below there is try to use undefined object variable $definitioncategory. After submiting form an error "Notice: Undefined variable: definitioncategory" occurs.

```php
    /**
     * Creates a new DefinitionCategory entity.
     *
     * @Route("/new", name="definitioncategory_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $definitionCategory = new DefinitionCategory();
        $form = $this->createForm('EducationBundle\Form\DefinitionCategoryType', $definitionCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($definitionCategory);
            $em->flush();

            return $this->redirectToRoute('definitioncategory_show', array('id' => $definitioncategory->getId()));
        }

        return $this->render('definitioncategory/new.html.twig', array(
            'definitionCategory' => $definitionCategory,
            'form' => $form->createView(),
        ));
    }
```

**Comment by xabbuh** [comment]
The `generate:doctrine:crud` command is part of the [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle/). Please report any issue with it their.
