### ISSUE TITLE
I see the error in two places /var/log/nginx/site.error.log and  app/logs/dev.log

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#17185]
I set breakpoint to 1 string of function \Symfony\Component\Debug\ErrorHandler::handleFatalError and when breakpoint stoping process I see error in /var/log/nginx/site.error.log

Don't understand because in above the function handleFatalError declared as a shutdown handler:
```
register_shutdown_function(__CLASS__.'::handleFatalError');
```
According to this, no errors should not put into php://stderr

**Comment by xabbuh** [comment]
@yapro Which PHP version do you use?

**Comment by yapro** [comment]
```
$ php -v
PHP 5.6.11-1ubuntu3.1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by yapro** [comment]
I think it error of php.
