### ISSUE TITLE
[Form Collections] NotBlank constraint on collection edit

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony#17180]
We are facing a strange "issue" (don't know if really is) about form collections. Let's take into account the following entities

    class Foo
    {
      /**
       * @ORM\OneToMany(targetEntity="Bar", mappedBy="foo", cascade={"persist"}, orphanRemoval=true)
       * @Assert\Valid
       */
      protected $bars;
    }

    class Bar
    {
      /**
       * @ORM\ManyToOne(targetEntity="Foo", inversedBy="bars")
       * @Assert\NotBlank(message="Foo mandatory")
       */
      protected $foo;
       
      /**
       * @ORM\ManyToOne(targetEntity="FooBar")
       * @ORM\JoinColumn(...)
       * @Assert\NotBlank(message="FooBar mandatory!")
       */
      protected $foobar; //here comes the issue!
    }

and the following form types

    // FooType
    class FooType extends AbstractType
    {
      public function buildForm(FormBuilderInterface $builder, array $options)
      {
        $builder
          ->add('bars', CollectionType::class, array(
              'entry_type' => new BarType(),
              'error_bubbling' => false,
              'allow_add' => true,
              'allow_delete' => true,
              'required' => false,
              'by_reference' => false,
          ));
      }
    }

    // BarType
    class BarType extends AbstractType
    {
      $builder
        ->add('foobar', EntityType::class, array(
            'required' => true, // ** PAY ATTENTION! IN DEV ENV. CLIENT SIDE VALIDATION IS TURNED OFF 
            'class' => 'VendorBundle:FooBar',
        ));
    }

So, as I highlighted above, client side validation is turned off in dev. env; that means that `required` attribute of `foobar` seems to be useless and would never be considered unless we switch to other environment.

Ok, now, if we edit  a `Foo` entity that has (just for the sake of this example) one `Bar` inside the collection, through `FooType`, and we set `foobar` to null (by de-selecting entity into form, for example) we end in a situation of

> Catchable Fatal Error: Argument 1 passed to  Vendor\Bundle\Entity\BarType::setFooBar() must be an instance of Vendor\Bundle\Entity\FooBar, null given

This is due to type hinting on `setFooBar()` (and it does make sense. Of course we would prefer not to "hack" by letting it accept a `null` value aswell) but left us perplexed. In fact we would have expected that `NotBlank` validation comes _before_ letting the setter do this.

I've also find were Symfony's form component seems to act that way
 
    // If the data is identical to the value in $data, we are
    // dealing with a reference
    if (!is_object($data) || !$config->getByReference() || $form->getData() !== $this->propertyAccessor->getValue($data, $propertyPath)) {
        $this->propertyAccessor->setValue($data, $propertyPath, $form->getData());
    }

last part of "or" condition is what seems to cause this

    $form->getData(); // = to null
    $this->propertyAccessor->getValue($data, $propertyPath); // = to FooBar as previously a FooBar was correctly setted

So, is this an issue? Is this based on the assumption that client side validation has always to be on and `required` attributes needs always to be setted "the right way"?

**Comment by xabbuh** [comment]
This is how the `required` option is intended to work (also take a look at [the related documentation](http://symfony.com/doc/current/reference/forms/types/form.html#required)):

> If true, an HTML5 required attribute will be rendered. The corresponding `label` will also render with a `required` class.

> This is superficial and independent from validation. At best, if you let Symfony guess your field type, then the value of this option will be guessed from your validation information.

**Comment by DonCallisto** [comment]
@xabbuh it seems to me or this is a very weak approach?

I mean, what if I expose that route with a RESTful approach? Do I need to validate manually posted data?

**Comment by CruzyCruz** [comment]
@DonCallisto 

I have the same problem (or question) than you. I have explained my problem [here](http://stackoverflow.com/questions/37444420/symfony2-embedded-form-validation-is-not-triggered-when-editing).

Did you find any acceptable solution ?

**Comment by DonCallisto** [comment]
@CruzyCruz There's no safe solutions: if you want your code to work, you need can do the following:

- Enable server-side validation
- If you are developing a REST API, taking advantage of form component, you should "parse" and "validate" yourself the input before passing it to the form
- Make your setter accept `null` values (this is the solution I would never choose)

The issue is very difficult to tackle as symfony will perform validation **after** data bind but of course, if your binding (e.g.: your setter) does not accept a `null` value, **even** if you have setted that constraint, well, you know yourself the consequences.

**Comment by CruzyCruz** [comment]
@DonCallisto 

Thanks. 

About making setter accept `null` values, it can be correct if the related attribute is defined with `nullable=true` (I have some ManyToOne relation nullable). I have to verify (later at home) but I remember to have done this before and the problem was still remaining.

Do you think that Data Mappers could do the job ? [Here](https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/) is a very good article.

[Here](http://blog.iltar.nl/posts/733915-avoiding-entities-in-forms) an other good article about DTO that could be used as a workaround for this problem.

**Comment by CruzyCruz** [comment]
@DonCallisto 

[#17003](https://github.com/symfony/symfony/issues/17003) is about the same problem. As you can read in stof's answer, he proposes to allow null in the typehint or to use a separate object (so a DTO).

**Comment by DonCallisto** [comment]
@CruzyCruz yes, DTO is definitely a good choice and is pretty much what I've suggested above on the point 2 of my list. You have to perform a sort of "pre validation".

DTO is absolutely the right choice here to me.

**Comment by CruzyCruz** [comment]
@DonCallisto 

Yes, I didn't realize that you were talking about DTO in your second point. Thanks for all.

**Comment by DonCallisto** [comment]
@CruzyCruz no worry; it was unclear indeed. I've edited it
