### ISSUE TITLE
Cache files should be group writable

### ISSUE THREAD

**Issue by dfredriksen** [symfony/symfony#17188]
I believe the cache/log files should be group writable when written by the browser/console by default so that one can configure group permissions on a user and avoid the annoying cache permissions errors when attempting to clear cache from the console.

**Comment by stof** [comment]
Well, there are many different way to handle the shared cache. The doc explains them all: http://symfony.com/doc/current/book/installation.html#checking-symfony-application-configuration-and-setup

Forcing to write a group-writable cache would be a bad idea:
- we don't know for sure that the browser and the console are in the same group (so following your idea, it should be done world-writable instead)
- not respecting the umask is actually removing flexibility for deployments (it forbids the first cases in the doc). And world-writable cache can even be a security issue.
