### ISSUE TITLE
[Yaml] Regression in object support parser fix

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#17190]
The fix for #17075 done in #17079 introduced a regression.

The following example:

```php
use Symfony\Component\Yaml\Yaml;

print_r(Yaml::parse("foo: bar\nbaz: derp", false, false, true));
```

Is failing with the following exception:

```
PHP Fatal error:  Cannot use object of type stdClass as array in /path/to/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php on line 236
```

**Comment by xabbuh** [comment]
@IngwiePhoenix Can you please check if #17197 completely fixes the issue for you?

**Comment by IngwiePhoenix** [comment]
@xabbuh It seems to work. I had to learn how to pull in PRs, but I found ways to get there. I used this as a test:

```php
<?php
require "vendor/autload.php";

use Symfony\Component\Yaml\Yaml;

print_r(Yaml::parse("foo: bar\nbaz: derp", false, false, true));
```

and it does print an `stdClass` object now. I will run this against a much bigger config file and tell you how that went.

**Comment by IngwiePhoenix** [comment]
Success. Works like a charm now. :)

**Comment by xabbuh** [comment]
@IngwiePhoenix Great, thanks for confirming. Next time I would just make the changes locally in your `vendor` directory (at least when the changeset is just so small). :)

ping @symfony/deciders
