### ISSUE TITLE
Reconsider the CS rule for returning null in functions

### ISSUE THREAD

**Issue by stof** [symfony/symfony#17201]
currently, our CS mandate to use `return;` to return `null` from a function.

But there is 2 different cases actually:
- a function without any return value (returning void), for which `return;` makes sense
- a function returning something or `null`, for which `return null;` would be more meaningful

The original discussion said that PHP had no concept of `void` and so that our CS should not distinguish these 2 cases (and so should have a single rule). But PHP 7.1 now has such concept: https://wiki.php.net/rfc/void_return_type

I think we should revisit this rule in our coding standards, to distinguish functions returning void and functions returning something or null.

what do you think ?

**Comment by stof** [comment]
Note that if this is accepted, the existing return fixer in PHP-CS-Fixer will need to be disabled (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1638 for a discussion about it), and a new fixer might be created to automate the new rule (allowing to update our whole codebase in an automated way).

**Comment by phansys** [comment]
IIUC, `return;` is only used when the function must return an early void, but if the function doesn't return anything, `return` must be omitted: https://symfony.com/doc/current/contributing/code/standards.html#structure
>Use just return; instead of return null; when a function must return void early;

**Comment by phansys** [comment]
So, just as a recap for your 2 points, this should be the current CS:
>* a function without any return value (returning void)

`return` statements are fully absent.

>* a function returning something or null

`return;` statement only present if the return is required before the end of function's flow (early return inside a condition by instance).

As far as I can see, both cases are taken into account with the current spec.

**Comment by stof** [comment]
> IIUC, return; is only used when the function must return an early void, but if the function doesn't return anything, return must be omitted

anything or void is the same. It is just that PHP calls this void (because other languages call it void too)

> As far as I can see, both cases are taken into account with the current spec.

you are confusing the case of returning ``null`` early and returning ``void`` early. Your comment assumes they are the same. They are not (and this is precisely my point).

**Comment by phansys** [comment]
You're right @stof, I misunderstood your point. Thank you for the clarification.

**Comment by derrabus** [comment]
I never liked this specialty of Symfony's coding standard, so if you want to change it: :+1: 

There's no direct need to change it, though. Code with the current CS will run fine under php 7.1 as long as a function is not declared as `void`. And it will take some time untill Symfony can set php 7.1 as a minimum requirement in order to make use of the `void` return type – we're probably talking about Symfony 5 here.

But you're probably right. If php introduces the concept of void type functions, Symfony should probably embrace this concept even before making use of the actual feature.

**Comment by GrahamCampbell** [comment]
> But you're probably right. If php introduces the concept of void type functions, Symfony should probably embrace this concept even before making use of the actual feature.

PHP 7.1 has already done this.

**Comment by dunglas** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: Sounds reasonable to me.

**Comment by Tobion** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
For what it's worth, :-1: from me because of the fact that any assignment of the result of the function will still be `null`.

**Comment by thewilkybarkid** [comment]
:+1: for clarity.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by romainneutron** [comment]
:+1:

**Comment by leofeyer** [comment]
+1

**Comment by huebs** [comment]
+1

**Comment by keradus** [comment]
We should also reconsider `phpdoc_no_empty_return`, which will remove from phpdocs `@return void` and `@return null` annotations.

**Comment by GrahamCampbell** [comment]
Indeed. I've always not liked that fixer.

**Comment by DavidBadura** [comment]
:+1: i like it

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because the community has accepted it and there is nothing else to do:

1. The docs have been updated: https://github.com/symfony/symfony-docs/pull/6614
2. We (probably) won't update the existing code to avoid merging conflicts.
3. We'll use this new rule for the new code added from now on.

**Comment by stof** [comment]
> We (probably) won't update the existing code to avoid merging conflicts.

Technically, we could totally update the existing code in an automated way once we update PHP-CS-Fixer to cover the new standard. And I would even say we should do it, otherwise people will receive warnings from fabbot.io all the time once the automated tool is aware of the new rule

**Comment by keradus** [comment]
Please extend needed actions if needed:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1638#issuecomment-221832315

**Comment by stof** [comment]
@symfony/deciders I'm reopening the issue for this discussion, now that `return;` and `return null;` are considered different in PHP 7.1+

**Comment by robfrawley** [comment]
Not a Symfony decider, but I have always hated how Symfony blurred `null` returns and `void` returns, even if separating such was only a "convention for clarity" prior to PHP 7.1. :+1: To the change. Wasn't this already accepted, though?

**Comment by nicolas-grekas** [comment]
since php 7.1 will force us to do so in master, this should help merges into master. So :+1:, even if it's a boring task (it's not only having a command to help, but also doing to job from 2.7 up to master, potentially handle cross version test failures and dealing with conflicts, and forcing everyone to rebase their PRs meanwhile...)

**Comment by derrabus** [comment]
Inconsistent return points in functions are going to bite us if we want to add return types to them in Symfony 5.0:
* As soon as we add a return type, we cannot mix `return;` and `return $someValue;` within the same function anymore. https://3v4l.org/RBoMM
* If we add a a return type other than `void`, php will not implicitly return `null` when reaching the end of a function, but emit a `TypeError`. https://3v4l.org/5GrdN
* If we add `void` as return type, returning with a value will result in a fatal error, even if we use the result of another void method. https://3v4l.org/B5jgp

I have seen all three cases in Symfony's codebase. I don't know if we can fix all inconsistent return points automatically. The third case needs a different strategy than the other two and an automated tool would have a hard time detecting that case.

But at least PhpStorm is pretty good at finding them. On the current 3.4 branch, PhpStorm detects 353 issues. I've browsed them and I've only found a handful of false positives (mostly fixtures and, let's say, interesting usages of `for` loops).

![Bildschirmfoto 2019-08-07 um 12 14 06](https://user-images.githubusercontent.com/1506493/62615234-310a9000-b90d-11e9-85fd-aee2cfc9b4b8.png)

I'd say, it's worth fixing those issues in 3.4 and 4.3 now to make adding return types to Symfony 5 easier.

**Comment by nicolas-grekas** [comment]
Or, we can decide it's not worth adding `void`. I think it provides nothing personally.

**Comment by derrabus** [comment]
> Or, we can decide it's not worth adding `void`. I think it provides nothing personally.

Fair enough, in that case we could ignore item 3 on my list and would treat PhpStorm warnings on lines like this one like a false positive.

https://github.com/symfony/symfony/blob/41234653d5f67fb512be1d19029b78eb21f526f1/src/Symfony/Component/Console/EventListener/ErrorListener.php#L43

That wouldn't make fixing the other two cases easier, though.

**Comment by teohhanhui** [comment]
https://github.com/symfony/symfony/blob/41234653d5f67fb512be1d19029b78eb21f526f1/src/Symfony/Component/Console/EventListener/ErrorListener.php#L43

is really bad style anyway...

It should be rewritten as:

```php
             $this->logger->error('An error occurred while using the console. Message: "{message}"', ['exception' => $error, 'message' => $error->getMessage()]);

             return;
```
