### ISSUE TITLE
[WebProfilerBundle] Add support to display different info for @media >768px and >1024px

### ISSUE THREAD

**Issue by layanto** [symfony/symfony#17245]
Profiler toolbar css currently supports "sf-toolbar-info-piece-additional-detail" class to only be displayed for >1024px and hidden otherwise. But what if I want to display different info for <1024px and >1024px instead of just displaying the same info plus additional info?
For example for StashBundle (https://github.com/tedious/TedivmStashBundle/pull/90), would like to show hit ratio as percentage (eg 80%) for <1024px view and for >1024px view to display "8 hits /10 requests". Is this currently possible with the new toolbar style (2.8/3.0)? If not, can support for this be added?

**Comment by javiereguiluz** [comment]
In the old toolbar this was achieved with the `sf-toolbar-info-piece-additional` class, which is also maintained in the new toolbar. Please test it and report back if it doesn't work as expected. Thanks!

**Comment by layanto** [comment]
@javiereguiluz I know of ```sf-toolbar-info-piece-additional``` where anything enclosed with this tag will only be displayed for >1024px and hidden for <1024px. I am actually looking for something opposite, a tag which is displayed for <1024px and is hidden for >1024px. Does it exists?
For example with web debug toolbar of doctrine, it shows number of queries for <1024px and for >1024px number of queries is still shown with the addition of query time. What if I don't want to show no of queries and want to show something different for >1024px? To do that I need to hide the no of queries from being shown >1024px (hence needing a class doing the opposite of ```sf-toolbar-info-piece-additional```).

**Comment by layanto** [comment]
Actually I was using ```sf-toolbar-info-piece-additional-detail```, will try with ```sf-toolbar-info-piece-additional```.

**Comment by layanto** [comment]
Tried ```sf-toolbar-info-piece-additional``` and basically does the same as ```sf-toolbar-info-piece-additional-detail```.
Maybe easier to describe the issue with examples:

Use Case 1
Would like to display the following on debug toolbar
<1024px ```icon XX```
>1024px ```icon XX YY ZZ```
Use Case 1 above is easily satisfied with ```sf-toolbar-info-piece-additional-detail``` around ```YY ZZ``` such that ```YY ZZ``` will only be displayed for >1024px and hidden otherwise but ```icon XX``` always displayed.

Use Case 2
Would like to display the following on debug toolbar
<1024px ```icon AA```
>1024px ```icon XX YY ZZ```
Don't think Use Case 2 above can be satisfied with ```sf-toolbar-info-piece-additional-detail```. Not the requirement of showing ```AA``` for <1024px and hidden for >1024px.

Specifically for StashBundle, for example Use Case 2 is as follows:
<1024px ```icon 80%``` or ```icon 4/5```
>1024px ```icon 4 hits/5 calls```

**Comment by layanto** [comment]
Worked around this for StashBundle:
For \<1024px icon A/B
For >1024px icon A XX/B YY
This can be done with ```sf-toolbar-info-piece-additional-detail``` around XX and YY

Issue still exists if someone wants to display completely different information for \<1024px and >1024px.
