### ISSUE TITLE
[Validator] Email Validator does not work properly

### ISSUE THREAD

**Issue by zender** [symfony/symfony#17254]
I am trying to validate email: some,name@gmail.com which is invalid email but it is validated as valid one.

I set these options: strict: true, checkMX: true, checkHost: true.

SF version: 2.7.4

**Comment by xabbuh** [comment]
When the strict mode is enabled, the `Email` validator uses the [egulias/email-validator](https://github.com/egulias/EmailValidator) library to validate e-mail addresses. Please report any issue with their validation in their bug tracker.
