### ISSUE TITLE
Symfony\Component\Console\Application::renderException() should accept \Throwable

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/symfony#17257]
Because of PHP 7, `Symfony\Component\Console\Application::renderException()` should also accept `\Throwable` type.

**Comment by Tobion** [comment]
The same problem applies to HTTP request/response cycle with events (`GetResponseForExceptionEvent`). Ref #16980

**Comment by chalasr** [comment]
I believe this issue has a duplicate https://github.com/symfony/symfony/issues/20110 and a PR https://github.com/symfony/symfony/pull/20111 (which would be nice to finish btw)

**Comment by xificurk** [comment]
Please reopen this issue. It's not a duplicate of #20110 and also it's not yet fixed. PR #20111 added catching of `Throwable`, but the call to `Application::renderException()` still fails.

**Comment by chalasr** [comment]
This should be closed again (see edit on previous comment).
