### ISSUE TITLE
[Crawler] Default charset should be UTF-8

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/symfony#17258]
When "charset" is not provided in $type argument of Crawler::addContent, it should default to UTF-8, which is already pretty widespread.

**Comment by JHGitty** [comment]
As I understand in the Symfony documentation currently the default charset is ISO-8859-1. Right?
Source: http://symfony.com/doc/current/components/dom_crawler.html#adding-the-content

**Comment by ondrejmirtes** [comment]
Yep.

**Comment by xabbuh** [comment]
The character set is tried to be read from the meta tag and falls back to ISO-8859-1 because that's the default in the HTTP 1.1 specification:

> If the charset is not set via the content type, it is assumed
> to be ISO-8859-1, which is the default charset defined by the
> HTTP 1.1 specification.

**Comment by ondrejmirtes** [comment]
I think it would be more practical to use UTF-8 as the default since this is year 2016 and not 1999. Consider it as part of the [Symfony DX initiative](http://symfony.com/blog/making-the-symfony-experience-exceptional).

**Comment by JHGitty** [comment]
So should we follow RFC2616 or should we do a DX initiative here to change the default to UTF-8?

**Comment by ondrejmirtes** [comment]
I would vote for that although that's not up to me but to maintainers.

**Comment by nicolas-grekas** [comment]
changing the default would be a bc break, isn't it?

**Comment by JHGitty** [comment]
As I understand RFC 7230 (which replaces RFC2616) does not contain ``ISO-8859-1`` as default anymore.

>  A recipient MUST parse an HTTP message as a sequence of octets in an
   encoding that is a superset of US-ASCII [USASCII].

.. and ..

> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

**Comment by xabbuh** [comment]
This is only about the header values and not about the contents of the HTTP messages.

Anyway, as @nicolas-grekas said changing the default value would be a BC break and could only be done with Symfony 4.0 (and we would still need to find a proper upgrade path).

**Comment by javiereguiluz** [comment]
I've added this issue to the new `4.0` milestone.

**Comment by jakzal** [comment]
The default encoding for XML documents is actually either UTF-8 or UTF-16. So this would be a bug fix for XML documents with no encoding attribute. Since the default for [html5 is UTF-8](http://www.w3schools.com/html/html_charset.asp) we set the default wrong here as well. We could potentially recognise the document type and apply the right default.

**Comment by ondrejmirtes** [comment]
I'd vote for less autodetection magic and more deterministic behaviour.

On Thursday, 10 March 2016, Jakub Zalas <notifications@github.com> wrote:

> The default encoding for XML documents is actually either UTF-8 or UTF-16.
> So this would be a bug fix for XML documents with no encoding attribute.
> Since the default for html5 is UTF-8
> <http://www.w3schools.com/html/html_charset.asp> we set the default wrong
> here as well. We could potentially recognise the document type and apply
> the right default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony/issues/17258#issuecomment-194801607>.
>


-- 

Ondřej Mirtes

**Comment by nicolas-grekas** [comment]
Closing this one. If someone wants to provide a PR that is BC friendly, please do.

**Comment by nicolas-grekas** [comment]
Reopening as requested on #22462
Note that our policy for bc breaks is to always trigger a deprecation before doing it.
We should never accept bc breaks that have no continuous upgrade path.
Changing a default value is not possible without first doing something in 3.x.

**Comment by PayteR** [comment]
What's the state of this issue? 

I experienced troubles, when i wanted to crawl just some chunk of HTML code (whole page with <head> and charset in it works well). I can work it around with 2 line solution
```
$domCrawler = new Crawler($html);
$domCrawler->addHtmlContent($html);
```
but it's not that convenient and clear solution. 

I'm for UTF-8 default solution, that will BC break, because i think just minority of developers are dependent on this default charset.

**Comment by nicolas-grekas** [comment]
#24372 should do it, please confirm.

**Comment by ondrejmirtes** [comment]
Thanks to all participants! 🎉 👍
