### ISSUE TITLE
Issue: findTaggedServiceIds() searches only in $definitions

### ISSUE THREAD

**Issue by devckonem** [symfony/symfony#17256]
Hi,

I've coded 2 services:
1) The concrete service
```
<service id="just.simple.service" parent="parent.abstract" public="false" class="%parameter.just.simple.service.class%">
    <argument type="service" id="blabla" />
</service>
```
2) The exposed service
```
<service id="just.service" alias="just.simple.service">
    <tag name="find.by.this.tag" />
</service>
```

When I try to get the services with the tag "find.by.this.tag" in a CompilerPass it returns a empty array.
```php
$services = $container->findTaggedServiceIds('find.by.this.tag');
```

And the reason is because it iterates over ContainerBuilder::getDefinitions() and it ignores the $aliasDefinitions.

**Comment by xabbuh** [comment]
In my opinion you shouldn't be able to add tags to aliases at all. Being able to do so means that the alias would work in a different way than the aliased service which completely defeats the purpose of an alias. I think we should rather catch this when aliases are parsed.

**Comment by stof** [comment]
Well, you can't add tags to them (look at the Alias class). But the loader seems to ignore them silently instead of warning the user.

**Comment by devckonem** [comment]
So what would be the next steps? Allow the user to add tags to an alias? IMHO I think you should can add tags to alias services (but I dont know the effects).

**Comment by xabbuh** [comment]
The next step is to improve the loaders to issue warnings when tags are used on aliases.

**Comment by iltar** [comment]
You could always decorate the service and add tags to your decoration.

**Comment by stof** [comment]
@devckonem IMO, tagging aliases does not make sense. The next step would indeed be to warn the user in loaders when doing it.

**Comment by devckonem** [comment]
@stof Yeah your right. Thanks for the reply.
