### ISSUE TITLE
Circular Reference When Using @service_container on autowiring mode

### ISSUE THREAD

**Issue by ihsanudin** [symfony/symfony#17252]
```lang=yaml
services:
    app.menu:
        class: AppBundle\Menu\Builder
        autowire: true
#        arguments:
#            - '@router'
#            - '@service_container'
```

Before i comment the arguments, the service is work. After that i try to use auto wiring mode and got error

```lang=php
[Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                          
  Unable to autowire argument of type "Symfony\Component\DependencyInjection\ContainerInterface" for the service "app.menu".
```
And then i try to add auto wire type

```lang=php
services:
    app.menu:
        class: AppBundle\Menu\Builder
        autowire: true
        autowiring_types: Symfony\Component\DependencyInjection\ContainerInterface
#        arguments:
#            - '@router'
#            - '@service_container'
```
 and i got another error

```lang=php
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]  
  Circular reference detected for service "app.menu", path: "app.menu -> app.menu". 
```

**Comment by stof** [comment]
Well, the second case is expected: you are telling the container that ``app.menu`` should be injected inside autowired services needing a ContainerInterface.

It looks like the autowiring does not handle the case of injecting the container itself (but you should avoid doing that though)

**Comment by ihsanudin** [comment]
@stof : :+1: great

**Comment by dunglas** [comment]
I'm opening a PR to support autowiring of the `service_container` (even if it's a bad practice IMO, and the autowiring is here to avoid doing that when possible).

**Comment by ihsanudin** [comment]
@dunglas : :+1: thank you very much
