### ISSUE TITLE
UserPasswordEncoder instance for use in service, controller or DataFixture code

### ISSUE THREAD

**Issue by CrackHD** [symfony/symfony#17251]
Implemented working custom user provider (user entity and authentication provider), configured in `security.yml`. That `User` entity implements basic fields like `username`, `salt` and `password`.

When i push new `User` entity to my database, i need to set password, encoded with random salt and global encoder options. I have specified `bcrypt` with 18 iterations inside `security.yml`. Symfony uses this option to check passwords on login.

For now i manually generate password with `salt` and `cost` (iterations) and save it with `User::setPassword()`, i can successfully login on my site. **But i want to do this without explicitly specifying "bcrypt"/"iterations" in PHP source**. It should look something like:

    $user->setSalt(md5(uniqid(null, true)));

    // uses encoder to hash salted password:
    $encoder = ???
    $user->setPlainPassword('raw password', $encoder); 

    $em->persist($user);

I need to do this in service, controller and `DataFixtures/ORM/AdminUser.php` on my site. Am i only one cannot understand this, or i did not get something -

It's unclear where to get **UserPasswordEncoder** instance, used on login in my site. The only option i see is to read YML file manually but this is kinda workaround.

**Comment by CrackHD** [comment]
Answer to this question was found accidentally, in [docs page](symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#using-the-container-in-the-fixtures). I think this must be linked or explained in "How to Create a custom User Provider" manual.

To let fixtures access symfony container, we only add `ContainerAwareInterface` to the fixture class and implement its `setContainer()` function. Controllers implement `ContainerInterface` directly, so we can just use `$this`. 

`$container->get("security.password_encoder")` will return an **[UserPasswordEncoder](https://github.com/symfony/security-core/blob/master/Encoder/UserPasswordEncoder.php)** instance i was looking for, with **encodePassword** method available.

Speaking of services, i think like i have to add an argument to constructor of my service:
```php
function __construct(ContainerInterface $container)
```
And let symfony pass the actual container instance via `services.yml` section:
```yaml
my_service:
    class: ...
    arguments: ['@service_container']
```

**Comment by xabbuh** [comment]
@CrackHD Please open an issue in [the documentation repository](https://github.com/symfony/symfony-docs) if you think the documentation for this could be improved.

**Comment by sstok** [comment]
@CrackHD Please note that the salt option is deprecated for the bCrypt encoder.

And I seriously hope that `md5(uniqid(null, true))` is only because you are generating fixtures!
Because I can't even describe how horribly insecure this is :scream:

**Comment by stof** [comment]
@CrackHD Injecting the whole container is a bad idea, because it means your dependency is the whole container. It is better to inject only the service you need

**Comment by CrackHD** [comment]
@stof Could you provide an example? Very need this to be done in best conditions. If so.

**Comment by Naskalin** [comment]
@Crackd I think this is no longer relevant, but somethink like this for symfony 4:

**services.yaml**
```
    App\Utils\Foo:
        calls:
            - method: 'setPasswordEncoder'
              arguments:
                  - "@security.user_password_encoder.generic"
```

Your _service or manager or any class_ **Foo.php**
```
namespace App\Utils;

class Foo
{
    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    public function setPasswordEncoder(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    public function updateUserPassword(User $user, string $plainPassword)
    {
        $user->setPassword(
            $this->passwordEncoder->encodePassword($user, $user->getPlainPassword())
        );

         //...
        $em->persist($user);

    }
}
```
