### ISSUE TITLE
Log file not closed causing "failed to open stream: Too many open files" using phpunit-bridge

### ISSUE THREAD

**Issue by Congelli501** [symfony/symfony#17268]
When running a large phpunit test with phpunit-bridge installed, the log files (`app/logs/test.log`) is not closed and the php process ends up failing with the `failed to open stream: Too many open files` error.

`lsof | grep '^php' | grep 'test.log$' | wc -l` returns 700+ results.

This bug only appear when `symfony/phpunit-bridge` is installed.
Removing it from my composer.json and running the tests again makes the tests run well, with ~20 logs files open.

Could it be caused by "It disables PHP's garbage collector for tests to avoid segmentation faults;" (source: http://symfony.com/blog/new-in-symfony-2-7-phpunit-bridge) ?

Symfony version: 2.7.8
PHP version: 5.6.11 (from Ubuntu 15.10)
phpunit version: 5.1.3 (installed via composer)

This seems to be related to this bug: https://github.com/symfony/symfony/issues/11566

**Comment by nicolas-grekas** [comment]
Thanks for the detailed report and the analyze. Did you try to re-enable the gc?

**Comment by stof** [comment]
This might totally be related, as the GC is needed to clean circular object graphs.

@nicolas-grekas I don't think that the bridge should force disabling the gc. This should be done only in the Symfony testsuite (or even not at all if we don't have segfaults because of it anymore, as this might have been fixed in PHP)

**Comment by Congelli501** [comment]
@nicolas-grekas I re-enabled gc, and this is definitely the source of the unclosed files.

I added these lines at the beginning of the first run test:

```php
var_dump(gc_enabled());
gc_enable();
var_dump(gc_enabled());
```

With symfony/phpunit-bridge enabled:
```
bool(false) # gc is disabled at start
bool(true)
< Tests run as expected, even if symfony/phpunit-bridge is installed > 
```

Without symfony/phpunit-bridge:
```
bool(true) # gc is enabled at start
bool(true)
< Tests run as expected > 
```

@stof I agree that gc should be enabled for unit tests. I expect the tests to be run in an environment as close as possible to production. If the code makes PHP crash, the tests should show it rather than hide it.

I have never experienced any segmentation fault during unit tests, with recent Ubuntu & Debian releases (14.04+ / 7+). This seems to be related to this PHP issue, closed in 2012: https://bugs.php.net/bug.php?id=60825
