### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Notice: unserialize(): Error at offset 86 of 137 bytes")

### ISSUE THREAD

**Issue by javierugalde** [symfony/symfony#17266]
Hi guys, 

## **First of all, Happy New Year 2016 !!!**

Ok, i'm having some problems with my project in symfony 2.7.7, the output error is:

>**An exception has been thrown during the rendering of a template ("Notice: unserialize(): Error at**
>**offset 86 of 137 bytes") in SonataUserBundle:Security:base_login.html.twig at line 25.** 
>> [2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Notice: unserialize(): Error at offset 86 of 137 bytes") in SonataUserBundle:Security:base_login.html.twig at line 25.

This error occurs on every route I try to enter. 

I searched this error in google but without any solution to my problem. What could be happening?

I really appreciate any help that you can provide me to solve this error as soon as possible.

Thank you very much!

Javier Ugalde

**Comment by iltar** [comment]
This seems more of an issue in Sonata than symfony.
