### ISSUE TITLE
Bug when updating 2.7.6 in 2.7.7 with choice fields

### ISSUE THREAD

**Issue by dbuton** [symfony/symfony#17265]
I have an API with the stack : NelmioApiDoc, FosRestBundle and JmsSerializer.
We have a route to display a form configuration (I know, it's bad), like that :

### Route: 
/forms/payments

### Response:
```
{
  "name": "",
  "action": "/payments",
  "method": "GET",
  "attr": [],
  "fields": {
    "itemPerPage": {
      "name": "itemPerPage",
      "required": false,
      "read_only": false,
      "disabled": false,
      "attr": [],
      "type": "integer",
      "data": null,
      "min": null,
      "max": null
    },
    "orderBy": {
      "name": "orderBy",
      "required": false,
      "read_only": false,
      "disabled": false,
      "attr": [],
      "type": "text",
      "data": null,
      "trim": true,
      "min_length": null,
      "max_length": null
    },
    "page": {
      "name": "page",
      "required": false,
      "read_only": false,
      "disabled": false,
      "attr": [],
      "type": "integer",
      "data": null,
      "min": null,
      "max": null
    },
    "direction": {
      "name": "direction",
      "required": false,
      "read_only": false,
      "disabled": false,
      "attr": [],
      "type": "choice",
      "data": null,
      "choices": {
        "asc": "asc",
        "desc": "desc"
      },
...
```

But when we update Symfony in 2.7.7, we have an Error.
```
Resources are not supported in serialized data. Path: Monolog\Handler\StreamHandler -> Symfony\Bridge\Monolog\Logger -> Symfony\Component\Security\Core\Util\SecureRandom -> Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator -> Symfony\Component\Security\Csrf\CsrfTokenManager -> Symfony\Component\OptionsResolver\OptionsResolver -> Exception 
```

And after investigation to fix it, I must add an empty_value equals to '' for each choice type fields because without that I think symfony set an object and the serializer crash an error.

Is it normal? Somebody had the same case? Is it the only way to fix that?

Thank you.

**Comment by HeahDude** [comment]
Hi @dbuton could you please precise which data involves serialisation in your form, is it the `direction` field of your example ?

**Comment by dbuton** [comment]
It's all data wich are of type : choice 
Because if we don't put an empty_value, symfony set it with an object that the serializer can't serialize.
It appears with the 2.7.7 symfony version.

**Comment by HeahDude** [comment]
@dbuton could you please try to update to 2.7.9 and confirm your issue ?

**Comment by HeahDude** [comment]
In your example many fields mention a type `text` or `integer`, that's why I asked you some precision about your data type been serialized.

**Comment by dbuton** [comment]
Yes sorry, it was just an exemple of the response I would like to have.
Yes I tried and had the issue in 2.7.8 and 2.8 so, I think 2.7.9 too.

**Comment by HeahDude** [comment]
I would be nice to be sure, minor versions are all about bug fixing ;)

**Comment by dbuton** [comment]
It's sure we tested in 2.8 and it crashed.

**Comment by HeahDude** [comment]
As you said in the title of this issue, bug appeared between two releases of 2.7.

It can as well have been fixed with the last 2.7.9 or 2.8.2 releases and this is the only thing for sure :)

**Comment by dbuton** [comment]
Ok thanks, so I will test with these versions.

**Comment by xabbuh** [comment]
@dbuton Any news here?

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback. Please reopen it if the error persists. Thanks!
