### ISSUE TITLE
2.8.1 not BC with 2.8.0 - missing 'class' for collections using 'entry_type' of EntityType

### ISSUE THREAD

**Issue by sgilberg** [symfony/symfony#17269]
I had diligently updated all my deprecated methods and options after upgrading to 2.8.0, and then when I ran composer and it moved to 2.8.1, all my forms that used collections of related entities broke. I had updated 'options' to 'entry_options' in all my form builders. Now I see the error "The required option "class" is missing." I have 'class' defined in my entry_options. It appears 'entry_options' is no longer being used in 2.8.1?

I have reverted to 2.8.0 temporarily pending further guidance.

**Comment by xabbuh** [comment]
We had a regression in 2.8.1 which was fixed by #17162 (this isn't released yet but will be part of 2.8.2). Can you confirm that that patch works for you too?

**Comment by sgilberg** [comment]
Ah, thanks @xabbuh ! Sorry I missed that one. That works for me.

**Comment by gondo** [comment]
just the note for everyone else looking for a fix:
#17162 was merged 7days ago, latest release was S2.8.1 released 10days ago, so this will be fixed in the next releass S2.8.2
