### ISSUE TITLE
$requests in RequestStack is empty for first request.

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#17273]
I have created an example of this issue here: https://github.com/trsteel88/symfony-standard/tree/feat-request-bug

The example integrates a Twig loader that uses the RequestStack object. When making the first request (after editing the config), the $requests var inside RequestStack is always empty. A reload fixes the issue. However, editing the config causes the issue once again.

To replicate the issue:

* clone repository
* open app/config.yml and add a blank line to the end of the file
* launch app_dev.php in your browser
* you should now see a dump of the RequestStack and it is empty (screenshot attached)
* refresh, you should now see a working page
* removing the blank line from app/config.yml and a single refresh will cause the problem again.

![screen shot 2016-01-06 at 3 42 29 pm](https://cloud.githubusercontent.com/assets/869933/12135799/1e0298c4-b48c-11e5-9e0b-e6801695d5b3.png)

**Comment by xabbuh** [comment]
Simply do nothing with the injected request stack in the constructor of you loaded class. When the object is created before the event listener for the request stack has run, you will see the described effect.

**Comment by trsteel88** [comment]
@xabbuh, the above example was just 1 example.

I have another example where with the following services.

1. SiteFactory with a get() method.
2. Site (retrieved depending on the hostname, dir etc).
3. Another Service which depends on Site context.

The 3rd service is being initialised and injecting a Site (which is created by the Factory from the RequestStack). Since the $requests are empty, it can't create the Site object on the first load.

This seems like a bug to me.

**Comment by xabbuh** [comment]
Please create a fork of the Standard Edition that reproduces your other issue then.

**Comment by trsteel88** [comment]
Done @xabbuh.

You will notice that the Exception (https://github.com/trsteel88/symfony-standard/blob/feat-request-bug/src/AppBundle/Factory/SiteFactory.php#L21) will now be thrown for the first request. All subsequent requests work. Changing the config.yml will revert it to throwing an Exception again because the RequestStack::$requests is empty.

**Comment by xabbuh** [comment]
Well, this use case isn't better either. Your `app.context.site` service now depends on when it is retrieved and depends on the request. You rather should not register that service, but add something like a `getCurrentSite()` method to your `SiteFactory` class and the use that method at runtime to retrieve a `SiteInterface` instance.

**Comment by trsteel88** [comment]
Yes I know. However, this problem has only come up since upgrading to 2.8 from 2.7. 

The context site is already used across multiple bundles on different applications so it's going to be a bit of a BC break to change it.

**Comment by xabbuh** [comment]
In my opinion you just have been lucky that the code worked before and this is no BC break.

**Comment by trsteel88** [comment]
That really doesn't help me. Don't you think it's strange that it works in 2.7 and not 2.8?

See https://github.com/trsteel88/symfony-standard/tree/feat-request-bug-27

Exact same code. Works in 2.7, doesn't work in 2.8. Is that not a BC break?

**Comment by xabbuh** [comment]
As said the code you have was never expected to work and you simply were lucky that it was not breaking before (it completely depends on when the service is actually created which makes it fragile as you now noticed).

**Comment by trsteel88** [comment]
Why would this be happening though? The Kernel has the Request object. Why isn't it available?

**Comment by stof** [comment]
@trsteel88 the fact that it worked before is just luck: it only means that none of the object depending on your own service was instantiated before the request was available. It was already possible to break it in 2.7 (it depends on any service defined in the container).
and the kernel does things before it starts handling the service (anything happening during boot does not have the Request yet as it is not handling it yet).

Btw, note that your own code is also broken as soon as you use subrequests, as you create a container-scoped service based on the request, which has a shorter lifetime. This is what was prevented by the container previously with the request scope (as it could detect that the configuration of your service depends on such shorter-term service).
The RequestStack does not let the DIC figure out that your code is misbehaving (but it was also possible previously to write such misbehaving code to be honest, by injecting the full container and getting the request from it).

**Comment by trsteel88** [comment]
Hmm, that's a bit disappointing. Guess I'll add a deprecation trigger to get() and create a new getCurrentSite() method.

Thanks guys.

**Comment by stof** [comment]
> Hmm, that's a bit disappointing

Well, this was a broken design from the start. It just happened to work by luck (and your own code might have triggered the same issues than the one triggered by some code change in 2.8 btw)

**Comment by trsteel88** [comment]
It's just weird that it hasn't happened in 2.7 before. I've tested it in quite a few different places and can't replicate.

**Comment by er1z** [comment]
I came across this issue too. How it was possible it worked correctly in 2.7 *everytime* and since 2.8 is a pain in...?

**Comment by er1z** [comment]
Solution: remember to inject ``request_stack`` and **do not** "resolve" the request immediately. Just upon your request. And you save your life. :3

**Comment by COil** [comment]
I am facing the same issue, in a twig extension I inject the request stack, but at the 1st call, the `getGlobals()` function tries to get the current request of the request stack property and it's null. (Symfony 3.1.3) , how to do in this case ? (I want to access the server parameter bag)

**Comment by xabbuh** [comment]
@COil Do not use the request stack when registering your custom stuff, but only refer to it when some of your functions/variables are actually being called.

**Comment by COil** [comment]
@xabbuh Well I switched from a twig global to a twig function and it is now ok.

**Comment by jaydlawrence** [comment]
I am having a similar issue, trying to generate an absolute URL in one of my services.

From what I understand, using the RequestStack is the replacement for using the request scope.

And I need the request context to be able to generate the absolute URL properly.

But as was mentioned above, the first time it is loaded, there is no current request in the requestStack, so my service generates a crappy incorrect URL.

What are the suggestions for working around this?

I could do something dirty like force a page reload if it is not ready, but that seems a bit drastic.

The details of what I am trying to do are [here on Stackoverflow](http://stackoverflow.com/questions/43630670/how-to-generate-absolute-url-from-early-auto-loaded-symfony-3-router/43634938).

**Comment by stof** [comment]
Well, don't try to access the request before the time a request is handling by the kernel. Service constructors are very likely to be called early. Don't put the business logic in the constructor

**Comment by jaydlawrence** [comment]
Thanks @stof.
I changed it only access the RequestStack when it needed the url and it seems to do the trick.
Thanks for your help.

**Comment by samijnih** [comment]
> Solution: remember to inject `request_stack` and **do not** "resolve" the request immediately. Just upon your request. And you save your life. :3

That one worked for me and saves me some ulgy code.

I have a bridge for symfony request/response to psr request/response where I did this ugly thing in the service definition:

`arguments: [ '@=service("request_stack").getCurrentRequest()' ]`

now with autowiring and RequestStack class, I can delete some code :+1: :D
