### ISSUE TITLE
[2.8][3.0] Missing purge button in new Profiler

### ISSUE THREAD

**Issue by Haehnchen** [symfony/symfony#17274]
The new profiler does not provide a "Purge Button" inside "Profile Search" for calling `/_profiler/purge`. 

Suggest adding directly right to result count:
![profiler](https://cloud.githubusercontent.com/assets/1011712/12136527/11cd4c90-b449-11e5-8f31-1a8e4d6a5719.png)

**Comment by fabpot** [comment]
That was done on purpose, the profiler should not modify server side data directly. That's also why we don't have the import/export feature anymore.
