### ISSUE TITLE
[Form] ChoiceType undefined index issue when using $resolver->setNormalizer('choices',

### ISSUE THREAD

**Issue by Rattler3** [symfony/symfony#17270]
In 2.7.8 using setNormalizer to update 'choices' in a Form causes the below error:

```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: 
"Notice: Undefined index: Attribute 1" at 
.../vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php line 288 
```
A new fork has been created to show this issue. This can be found [here](https://github.com/Rattler3/symfony-standard/tree/example).

**Comment by xabbuh** [comment]
Did this work for you with any patch version of the 2.7 release?

**Comment by gseidel** [comment]
I have the same issue with Symfony version 2.8.1

**Comment by gseidel** [comment]
It only occurs if you also have a choice field define before your custom type which use the ```setNormalizer``` function.

https://github.com/Rattler3/symfony-standard/blob/example/src/AppBundle/Controller/DefaultController.php

If you changed the order ```choice``` and ```choiceTwo```it works for me. Maybe this helps for now if the order of the builder doesn't matter.

I guess it has something to do with this comment a few lines before in ChoiceType, because the fields have some dependencies on each other.

```php
// Don't pass the labels by reference. We do want to create a
// copy here so that every form has an own version of that
// variable (contrary to the $choiceLabels object shared by all
// forms)

**Comment by xabbuh** [comment]
> It only occurs if you also have a choice field define before your custom type which use the `setNormalizer` function.

What do you mean with that?

**Comment by gseidel** [comment]
> What do you mean with that?

Look at the DefaultController in the example. If you remove

```php
        $builder->add('choice', 'choice', array(
            'choices' => array(
                '1' => '1',
                '2' => '2',
                '3' => '3',
                '4' => '4',
                '5' => '5'
            )
        ));
```

It works also if you change the order like that.

```php
        $builder->add('choiceTwo', new ExampleChoiceType(), array(
            'show_all' => false
        ));

        $builder->add('choice', 'choice', array(
            'choices' => array(
                '1' => '1',
                '2' => '2',
                '3' => '3',
                '4' => '4',
                '5' => '5'
            )
        ));
```

Please remind that i didn't try that with Rattler3 example, but on my issue that works before. I only transfer that behaviour i found to this example.

**Comment by gseidel** [comment]
Maybe @Rattler3 can confirm that behaviour.

**Comment by Rattler3** [comment]
@xabbuh This worked in the previous version (2.7.7) also not working when I tested in 2.8.0.

I can also confirm what @gseidel is saying. This only happens if both choice fields are present and the choice field with the setNormalizer is the second item. This can be seen in the example [controller](https://github.com/Rattler3/symfony-standard/blob/example/src/AppBundle/Controller/DefaultController.php)

**Comment by paradajozsef** [comment]
I can confirm this behaviour. It occurs in 2.7.9 and 2.8.0. I proposed a PR: #17406. @gseidel has been right with this statement:

> I guess it has something to do with this comment a few lines before in ChoiceType, because the fields have some dependencies on each other.
