### ISSUE TITLE
FatalErrorException in ProxyGenerator.php line 62

### ISSUE THREAD

**Issue by SarramegnaG** [symfony/symfony#17288]
Greetings,

I'm using Centos 7 with PHP 5.4.16 (provided by Centos).

It seems like a change in Symfony 2.8.1 removes the compatibility with old PHP versions (at least for the dev version using app_dev.php). 

Newly integrated Doctrine Common 2.6.1 implements ::class in ProxyGenerator.php line 62 and then throw an error for php version older than 5.5 :
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)

So the app/check.php and web/config.php are not representative anymore.

Regards,

Guillaume

**Comment by stloyd** [comment]
No, it's not. Seems like you try to run composer install on lock that was created at PHP 5.5, it's not possible to get this otherwise as Doctrine 2.6 already forces the requirement of PHP 5.5 & composer would block you from installing it.

**Comment by javiereguiluz** [comment]
@SarramegnaG you are right. The Symfony 2.8 version delivered via the Symfony Installer includes a Doctrine version which requires PHP 5.5. We'll fix it for the next version. For now, the solution is to run `composer update` just after creating the new Symfony project.

**Comment by SarramegnaG** [comment]
@stloyd I used the Symfony Installer, not composer.
@javiereguiluz For your information, I ran "symfony new my-project 2.8" command. I will just fall back on "symfony new my-project 2.8.0" for now.

Thanks for the replies.

**Comment by Tobion** [comment]
https://github.com/symfony/symfony-standard/issues/858

**Comment by ameur-frikha** [comment]
Symfony installer or composer are the same,  just install composer and run composer update

**Comment by alicecaporali** [comment]
Hello,

`composer update` don't work for me.

I found a solution if you are in OVH : create a file nammed .ovhconfig . 

More infmration here : https://docs.ovh.com/fr/fr/web/hosting/configurer-le-php-sur-son-hebergement-web-mutu-2014/
