### ISSUE TITLE
PdoSessionHandler with SQLSRV PDO driver and SQL server 2008 not work

### ISSUE THREAD

**Issue by macintoshplus** [symfony/symfony#17284]
The PdoSessionHandler not work with SQL Server 2008 or greater.

The query [MERGE](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L674) use twice every param.

The error returned by the driver is
```
SQLSTATE[07002]: [Microsoft][ODBC Driver 11 for SQL Server] COUNT field incorrect or syntax error
```

How to use the PDO session handler ?

**Comment by Tobion** [comment]
http://stackoverflow.com/questions/25208804/pdo-count-field-incorrect-or-syntax-error
http://stackoverflow.com/questions/10113562/pdo-mysql-use-pdoattr-emulate-prepares-or-not

**Comment by javiereguiluz** [comment]
@Tobion do you consider this a Symfony bug (and the provided links are workarounds) or do you consider it a "misuse" which can be fixed with the provided links?

**Comment by Tobion** [comment]
I would considere this a bug which should be fixed so it works with both emulation enabled and disabled.

**Comment by javiereguiluz** [comment]
@Tobion thanks! Labeled as "bug" then.
