### ISSUE TITLE
asset function Twig not working in 3.0.1?

### ISSUE THREAD

**Issue by BartDuch** [symfony/symfony#17291]
Hallo,

I switched a project from symfony 2.8 to 3.0.1, I got everything working except that for some reason the twig function asset is not working any more, every where I use it I get an error:
```Twig_Error_Syntax in ExpressionParser.php line 573:
Unknown "asset" function in "base.html.twig" at line 14.```

All the other functions even my own ones are working just fine, I did
- ```composer update```
- ```php bin/console cache:clear```

But then I found this post: https://github.com/csarrazi/CsaGuzzleBundle/issues/85#issuecomment-157531952

This fixed the problem but no idea why?

I added the log file to the project
[log.txt](https://github.com/symfony/symfony/files/81031/log.txt)

**Comment by stof** [comment]
You need to enable the asset system in the configuration of FrameworkBundle to have it in 3.0 (the symfony-standard edition does it: https://github.com/symfony/symfony-standard/blob/34abc7efb5035f1e92c6c9fca59aa8daeeab9082/app/config/config.yml#L34 )

**Comment by BartDuch** [comment]
Thank you, this solved the problem :+1:
