### ISSUE TITLE
[Form][Bug][2.7.8+] Bug when using `false` as a value in an optional choice field

### ISSUE THREAD

**Issue by ivoaz** [symfony/symfony#17292]
After upgrading from 2.7.7 to 2.7.8 I noticed that some choice fields didn't display the empty value.

Example code:
```php
->add('buyback', 'choice', [
    'choices' => [
        'Yes'  => true,
        'No'   => false,
    ],
    'choices_as_values' => true,
    'required'          => false,
]);
```

Before:
![image](https://cloud.githubusercontent.com/assets/407855/12170811/144496ea-b54d-11e5-9a28-a44c9f48ddd5.png)
After:
![image](https://cloud.githubusercontent.com/assets/407855/12170840/3e399e5a-b54d-11e5-9032-4e0d49fe2a37.png)

So far I've found out that the `false` value is converted to empty string in this line https://github.com/symfony/symfony/compare/v2.7.7...v2.7.8#diff-780e59a429c485d2d3b8a37fdf62ac59R79.

I think that the `false` value is displayed instead of empty value because of that.

This bug was introduced in #16705.

**Comment by EAnushan** [comment]
Confirming bug is present in Symfony 3.0.1. Using `false` as a value sets value to empty. 

If the ChoiceType in question has a constraint such as `NotBlank()`, it is impossible to submit the form with the `false` option selected.

Removing the constraint allows form submission, and correctly maps to `false`, but the placeholder logic is still broken since `false` is being treated as empty, and placeholders do not appear if the choices list already contains an empty option.

**Comment by HeahDude** [comment]
see #17760 for a proposal of a fix.

Workaround using `choice_value` :
->add('buyback', 'choice', [
    'choices' => [
        'Yes'  => true,
        'No'   => false,
    ],
    'choice_value' => function ($choice) {
        return false === $choice ? '0' : (string) $choice;
    },
    'choices_as_values' => true,
    'required'          => false,
]);

**Comment by HeahDude** [comment]
Bug confirmed on 2.7 as well as in #17677.

Status: reviewed

**Comment by gharlan** [comment]
> If the ChoiceType in question has a constraint such as NotBlank(), it is impossible to submit the form with the false option selected.

This issue still exists. When selection the `false` value, I get:

> This value should not be blank.

**Comment by HeahDude** [comment]
@gharlan, This is not a `ChoiceType` issue.

When you want to accept a false value you should not use the `NotBlank` constraint.

see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/NotBlankValidator.php#L32

This is expected.

You should use `choice_value` option to map false to another string value, example :
```php
$builder->add('opinion', ChoiceType::class, array(
    'choices' => array(
        'yes' => true,
        'no' => false,
    ),
    'choice_value' => function ($choice, $key) {
        return $key; // will return 'yes' or 'no'
    },
    ...
```
