### ISSUE TITLE
[MicroKernel][2.8.0]

### ISSUE THREAD

**Issue by danieledangeli** [symfony/symfony#17297]
Hi,
I was trying to enable one medium project with a MicroKernel.
I've encountered this problematic.
My goal was (at least for now) starting to remove the routing files and keep only:
- config_{env}
- services.yml
- security.yml

The error is this one:

"[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "security.authentication.retry_entry_point" has a dependency on a non-existent parameter "request_listener.http_port"

which is a clear evidence that the security components has a strict dependency to a parameter that can be not defined (if the router component it's not loaded)!!

By looking the code, the parameter "request_listener.http_port" it's defined in the FrameworkExtension under the function: "registerRouterConfiguration" which is called only if the router component is defined
(obviously I've removed the router configuration from the config.yml)

I was trying to register this parameter:

```php
$container->setParameter('request_listener.http_port', $config['http_port']);
$container->setParameter('request_listener.https_port', $config['https_port']);
```

but it doesn't work.

Question: should the application http_port and https_port be an option under router???

**Comment by jakzal** [comment]
It would be better understand if this is a bug if you provided more code, so we could reproduce your issue.

Did you load the framework configuration? For example:

```php
    protected function configureContainer(ContainerBuilder $c, LoaderInterface $loader)
    {
        $c->loadFromExtension('framework', [
            'secret' => 'my$ecret',
            'test' => null,
            'profiler' => [
                'collect' => false,
            ],
        ]);
    }
```

**Comment by danieledangeli** [comment]
Thanks @jakzal for the quick response.

I've solved it.
The problem was related on my confusion on using the MicroKernelTrait.
Basically the funcitons: "configureRoutes" has never been called because I was overwriting "registerContainerConfiguration" from the previous normal "AppKernel". 

I'm sorry to have raised a ticket. But probably can help someone with the same problem!

**Comment by Steveb-p** [comment]
This proved useful to me. Thanks @danieledangeli
