### ISSUE TITLE
Assets fail to load after a Composer update

### ISSUE THREAD

**Issue by rtarnaud** [symfony/symfony#17309]
Hello,

I doubt my issue is purely related to Symfony but I post here nonetheless as I feel it is the most appropriate place to do so.

I recently performed a Composer update on my Symfony project to get a rid of a package I stopped using. Here is my composer.json:

```json
{
    "name": "XXX/xxx",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-0": {
            "": "src/",
            "SymfonyStandard": "app/"
        }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
		"doctrine/doctrine-fixtures-bundle": "~2.2",
		"friendsofsymfony/user-bundle": "dev-master",
		"knplabs/knp-paginator-bundle": "dev-master",
		"knplabs/knp-menu-bundle": "2.0.0",
		"blockcypher/php-client": "dev-master",
		"friendsofsymfony/rest-bundle": "dev-master",
		"friendsofsymfony/jsrouting-bundle": "dev-master",
		"jms/serializer-bundle": "dev-master",
		"matmar10/bitcoin-address-validator-bundle": "dev-master",
		"stof/doctrine-extensions-bundle": "~1.1@dev",
        "ass/xmlsecurity": "dev-master",
		"coresphere/console-bundle": "dev-master",
		"doctrine/doctrine-migrations-bundle": "^1.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```
In the same time, several packages including Symfony have been updated by the Composer update command:
- Twig
- Symfony
- Assetic
- Sensio (distribution, framework-extra, generator)
- Doctrine (orm, dbal, migrations, common, cache)
- ircmaxell (password-compat)
- paragonie (random_compat)
- fos (rest bundle)
- willdurand (negotiation)
- gedmo (doctrine-extensions)

Now, when i open my application (on /web/app_dev.php), the pages are loading but all assets that are managed by Assetic fail to load: every assetic route called by the browser web/app_dev.php/css/xxx.css  returns a 500 error (Note that requesting thoses routes individually works fine).

Checking the logs, I see that I have got the following Exception:

PHP Fatal error:  Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required 'C:\Users\XXX\Desktop\PROJECT\vendor/.../some_file.php' (include_path='.;C:\php\pear') in C:\Users\XXX\Desktop\PROJECT\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php on line ...

The file that fails to open ('C:\Users\XXX\Desktop\PROJECT\vendor/.../some_file.php') changes every time I request the page on my browser or after I delete the symfony cache, so I don't think it is responsible for the error.

Also, the application loads normally in the prod. environment.

I tried to revert to older versions of Assetic but without success.

Could you please give me some hints about this problem as I really don't have any lead work on at the moment?

Thanks a lot!

**Comment by rtarnaud** [comment]
Forgot to mention that the fatal error is preceded in the logs by the following warning:
PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(C:\Users\XXX\Desktop\PROJECT\vendor\...\some_file.php): failed to open stream: Too many open files' in C:\Users\XXX\Desktop\PROJECT\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php:...

**Comment by jakzal** [comment]
This has more to do with your system configuration, rather then Symfony. Disable xdebug if you have it enabled as I've seen it causing such problems. I'd advice you to check your ulimits if you were on linux, but since you're on windows I don't know if there's even such a setting there ;)

If you think there's a bug with assetic, report it either to [AsseticBundle](https://github.com/symfony/assetic-bundle) or [Assetic](https://github.com/kriswallsmith/assetic).

**Comment by stof** [comment]
If you be great to debug which package update is causing the issue though, to know which package is leaking file descriptors

**Comment by rtarnaud** [comment]
It appears that Symfony (symfony/symfony) is the package causing this issue starting from version 2.7.8 (works fine with 2.7.7). The error also occurs with 2.8.*.
I also tested assetic on a blank project with this composer.json but could not reproduce the error though.
Do you have any clue about what changes in 2.7.8 could have brought this kind of issue (or just maybe revealed a mistake in my own code)?

**Comment by rtarnaud** [comment]
@jakzal 
Thanks for your answer but I had already come across the leads you mentioned while googling:
- xdebug is not responsible although the php errors in the log are more detailed when it's activated
- I do not either about the file limits in Windows but even that was the direct cause of the error, it would still be unsatisfactory (to say the least) to increase those limits as this overflow is certainly caused by some kind of memory leak

**Comment by jakzal** [comment]
@rtarnaud as stof said it would be nice to debug which package causes the error. I can't help myself, unless you can provide a project that would be also failing on OS X or Linux (I don't have access to Windows). 

Without steps to reproduce we can't help much. It might not be assetic at all. Perhaps updating packages one by one (or enabling bundles one by one) would help you identify which dependency is causing troubles.

**Comment by rtarnaud** [comment]
@jakzal
Well as I said, Symfony is the package causing the error and not Assetic. With the same (old version) of Assetic and a newer version of Symfony, the error shows up.
When I talked about leads to investigate, I thought that maybe you had in mind some changes in 2.7.8 and above that might be causing this issue but I understand it's hard to give any tips with so little material.
I will eventually do what you suggested to locate the error more precisely if future versions of Symfony still cause that bug.

**Comment by jakzal** [comment]
> Symfony is the package causing the error and not Assetic

It's a far fetched statement, as the problem doesn't reveal itself in most Symfony installations. So far you're the only one reporting this bug, so your code might as well be at fault. I still count you're get into bottom of this :)
