### ISSUE TITLE
Strange behaviour of \Symfony\Component\Process\Process::start on MacOS

### ISSUE THREAD

**Issue by jakulov** [symfony/symfony#17300]
Hi, i'm trying to run custom command in background from controller.
Here's my simple code
    
    $cwd  = '/path/to/project';
    $command = new Process(
         'bin/console admin:settings_test',  $cwd, null, null, 3600
    );
    $command->start();

When I run this, process isn't starting. I've tried to pass callback function to start – no effect.
So i've changed start method like this:
    
    $this->process = proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $this->env, $this->options);
     var_dump($this->process); die(); // this line was added

It's interesting, that i've got no response from var_dump function and my process finally started!
The most strange thing, is if I'll move var_dump and die calls to few lines down, I will see var_dump output and my command will not be started.

Am I doing something wrong?

So for now I should use my own custom Process class, extending vendor one to avoid this issue, with overriding almost the whole class.

**Comment by jakulov** [comment]
Forgot to notice, that when I'm using run method, it works fine, but I need non blocking fork of my process.

**Comment by jakzal** [comment]
What happens is [the destructor stops your process](https://github.com/symfony/symfony/blob/f20f2f06cc4510bdcfc0794edd45580a0b96e244/src/Symfony/Component/Process/Process.php#L173). You need to `wait()` for the process to finish.

**Comment by jakulov** [comment]
jakzal, so there's no way to run non blocking background process? 
Now i've found a way of using fastcgi_finish_request() before wait() call to send response to the client and close connection. So in next request i can check if process is running and show it's progress to the client. And this is what I want, because process execution can take several minutes and I won't keep opened connection for so long.

**Comment by stof** [comment]
@jakulov you cannot have a child process living longer than its parent process. So no, you cannot launch a background process intended to keep running after your main process exits.

**Comment by stof** [comment]
If you look at how ``server:start`` works, it forks the PHP process (with ``pcntl_fork``), sets the fork as session leader (so that it does not depend on the main process anymore) and runs the subprocess in the fork only.

**Comment by jakulov** [comment]
Thank you for help.
