### ISSUE TITLE
[Suggestion] Link to the Symfony support page from the exception page and the profiler

### ISSUE THREAD

**Issue by stof** [symfony/symfony#17311]
Many people are opening issues on github to ask for support. I suspect that at least some of them don't know what our actual support channels are.

What do you think about linking to http://symfony.com/support on the exception page (the one displayed in debug mode) and in the profiler UI, so that people can know more easily how to ask for support ?

**Comment by jakzal** [comment]
:+1: excellent suggestion

**Comment by TomasVotruba** [comment]
:+1:

**Comment by iltar** [comment]
:+1:

**Comment by fabpot** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1: I like this suggestion

**Comment by peterrehm** [comment]
I just submitted a proposal here #17327.
