### ISSUE TITLE
Deploy a Symfony2 application causes fatal error with SensioGeneratorBundle at AppKernel.php

### ISSUE THREAD

**Issue by reypm** [symfony/symfony#17324]
I have created a new Symfony 2.8 app using Symfony installer by running: `symfony_installer new test 2.8`. After that I ran: `composer update`. And everything is fine until there. Now I want to deploy this app for production environment so I am following the steps as in docs [here][1] so the first command I am running is the following: `composer install --no-dev --optimize-autoloader` but I am getting this error:

    composer install --no-dev --optimize-autoloader
    Loading composer repositories with package information
    Installing dependencies from lock file
    Nothing to install or update
    Generating optimized autoload files
    > Incenteev\ParameterHandler\ScriptHandler::buildParameters
    Updating the "app/config/parameters.yml" file
    > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
    > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

    Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /var/www/html/test/app/AppKernel.php:25
    Stack trace:
    #0 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(430): AppKernel->registerBundles()
    #1 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
    #2 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(70): Symfony\Component\HttpKernel\Kernel->boot()
    #3 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #4 /var/www/html/test/app/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput in /var/www/html/test/app/AppKernel.php on line 25
    Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

      [RuntimeException]
      An error occurred when executing the "'cache:clear --no-warmup'" command:
      Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /var/www/html/test/app/AppKernel.php:25
      Stack trace:
      #0 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(430): AppKernel->registerBundles()
      #1 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
      #2 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(70): Symfony\Component\HttpKernel\Kernel->boot()
      #3 /var/www/html/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
      ponent\Console\Output\ConsoleOutput))
      #4 /var/www/html/test/app/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput in /var/www/html/test/app/AppKernel.php on line 25

I am not sure if this is an issue, an outdated docs or an error from my side, anyway I have reported here and I would like to know what is the right way and/or steps to deploy a Symfony2 app to production environment. Any advice?

I have made the first test in a app ready for production and I got the same issue, I think was my mistake in somewhere so I decide to try a clean app without any changes others than `composer update`

 [1]: http://symfony.com/doc/current/cookbook/deployment/tools.html

**Comment by Tobion** [comment]
> If you get a "class not found" error during this step, you may need to run export SYMFONY_ENV=prod before running this command so that the post-install-cmd scripts run in the prod environment.

The solution is actually desribed just in the docs you followed: http://symfony.com/doc/current/cookbook/deployment/tools.html

**Comment by Tobion** [comment]
Also please use the channels for support questions as described in http://symfony.com/support
