### ISSUE TITLE
Missing argument 1 when injecting parameter in FormType

### ISSUE THREAD

**Issue by imulot** [symfony/symfony#17336]
Hello,

Here my service definition :
services:
    petapp.form.type.species:
        class: PetAppCoreBundle\Form\Type\SpeciesType
        arguments: ['%locale%']
        tags:
            - { name: form.type }

In config.yml
parameters:
    locale: en

In my Species Type : 
    /**
     * Default locale
     *
     * @var sting
     *
     */
    private $default_locale;

    /**
     * Constructor
     *
     * @param string $locale
     */
    public function __construct($locale)
    {
        $this->default_locale = $locale;
    }

I don't undertstand why the DIC does not call my FormType with %locale% parameter.
I have the following error : 
Warning: Missing argument 1 for PetApp\CoreBundle\Form\Type\SpeciesType::__construct(), called in /home/dev/petapp/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php on line 90 and defined 

I call createForm with new 2.8 syntax  (<php 5.5)
$form = $this->createForm('PetApp\CoreBundle\Form\Type\SpeciesType',$species);

Do you have any idea about this issue ?
Thanks.

**Comment by xabbuh** [comment]
I am sorry that your code doesn't work as expected but I will close here anyway as we use GitHub to track the development of Symfony. Please use one of the [support channels](http://symfony.com/support) to get help with your problem. Thank you!

**Comment by imulot** [comment]
Hello,

I tried  documentation example but It does not work either.
http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-your-field-type-as-a-service

It seems a bug related to new 2.8 form feature where we do not need to change controller to access field as a service. 

Error come from :
in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php at line 90
// Support fully-qualified class names
 if (class_exists($name) && in_array('Symfony\Component\Form\FormTypeInterface', class_implements($name))) 
{
    $type = new $name(); ==> classical instanciation without any parameter
} 
Could you reopen this issue ?
Thanks.

**Comment by imulot** [comment]
May be an issue due to my php version. I am in 5.4.45-0+deb7u2.
Syntax ::class in formbuilder not working since this is possible only with php 5.5
I will try to upgrade my php version to fix this issue.

**Comment by imulot** [comment]
FYI : After upgrading php to 5.5 and changing syntax to ::class, error still present.

**Comment by xabbuh** [comment]
Please create a fork of the Symfony Standard Edition with the needed changes to reproduce your issue if you think you found a bug.

**Comment by imulot** [comment]
I have reproduced bug on 2.8 branch of this fork  https://github.com/imulot/symfony-standard.git
  URI /

Warning: Missing argument 1 for Test\TestBundle\Form\Type\BarType::__construct()
I try to inject %locale% parameter in BarType Form service.

Thank you for your help.

**Comment by xabbuh** [comment]
The FQCN of your form type is `Test\TestBundle\Form\Type\BarType` but your registered service's class name is `TestBundle\Test\Form\Type\BarType`.

**Comment by imulot** [comment]
You are right !
Thank you. Mistake was so obvious that I didn't see it.
I will update stackoverflow case.

Thanks again.
