### ISSUE TITLE
[HttpFoundation] "Symfony/2.X" HTTP_USER_AGENT on Symfony 3

### ISSUE THREAD

**Issue by davelima** [symfony/symfony#17335]
So, i think this is not a problem, but while dumping a request made with Symfony\Component\HttpFoundation\Request on Symfony 3.0.1, the user agent used on request was Symfony/2.X.

I've searched for any issues about this but didn't found nothing. There is a reason for it to remains 2.X on 3.X releases, or can we update it to Symfony/3.X on this version? What do you guys think?

**Comment by fabpot** [comment]
Indeed, can you create a PR to change the value to 3.X?
