### ISSUE TITLE
[Security] Voter with AccessDecisionManager & isGranted calls

### ISSUE THREAD

**Issue by Ninir** [symfony/symfony#17331]
Hello,

I created a voter following the [documentation](http://symfony.com/doc/2.8/cookbook/security/voters.html), injecting the AccessDecisionManager to check the current token roles as in the "[checking for roles inside a voter](http://symfony.com/doc/2.8/cookbook/security/voters.html#checking-for-roles-inside-a-voter)" section.
However, when calling `is_granted` from a Twig Template (or isGranted from a controller), I get a circular dependency issue on `security.access.decision_manager`.

This seems logical as the process is in the form of: twig -> security.authorization_checker (is_granted) -> security.access.decision_manager (decide) -> Voter -> security.access.decision_manager (decide).

I thought about:
* creating a service (MyEntityEvaluator) using function compilers (tagging with `security.expressions.function_evaluator`) as expressions
* creating Twig Functions in a Twig_Extension mapping to a service (MyEntityEvaluator).
* passing the container in the service, getting the decision_manager, and call the isGranted method

Am I missing something?

Thanks for your time

Symfony version: 2.8

**Comment by Ninir** [comment]
Guess it is related to:

> The ability to inject the AccessDecisionManager is new in 2.8: it caused a CircularReferenceException before. In earlier versions, you must inject the service_container itself and fetch out the security.authorization_checker to use isGranted().

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the needed changes to reproduce your issue?

**Comment by Ninir** [comment]
@xabbuh Ok just dit it. A minimal setup on the standard edition could not lead to the problem.

For those looking into the same issue: I investigated further, and it is totally related to the SecurityExtraBundle from JMS. Disabling (for testing purposes) the bundle fixed the circular dependency issue.
I Guess it needs more stuff to be matching SF 2.8 at least. Will investigate more to fix it on the bundle side.

Thank you for your time.

**Comment by Ninir** [comment]
More insight on my case:

I wanted to check that the current user was an administrator, thus having the `ROLE_ADMIN`.

Instead of using the `->decide(...)` method of `AccessDecisionManager`, I used the `Symfony\Component\Security\Core\Authorization\Voter\RoleVoter` class to check for the given role inside the current token, i.e:

```php
protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
{
    // ...

    $isAdmin = $this->roleVoter->vote($token, $subject, array('ROLE_ADMIN'));
    
    // ...
}
```

Using the RoleVoter is as easy as instanciating the class, or checking the initial definition of `security.access.simple_role_voter` in the SecurityBundle.
