### ISSUE TITLE
date_format year should use uppercase Y

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#17349]
```php
 ->add('begin', DateTimeType::class, [
  'date_widget' => 'single_text',
  'time_widget' => 'single_text',
  'date_format' => 'd/M/y',
  'html5' => false,
])
```
```
 The "format" option should contain the letters "y", "M" and "d". Its current value is "d/M/Y". 
```

The letter "y" should be uppercase "Y". A lowercase "y" is used for double-digit years (16 instead of 2016, see http://php.net/manual/de/function.date.php). But the current output has 4 digits (2016).

This would result into a BC break. That because I suggest to allow "Y" and deprecate "y".

**Comment by Tobion** [comment]
`date_format` must be one of the `IntlDateFormatter` constants or a IntlDateFormatter pattern. This is not related to the `date` format. See http://php.net/manual/de/intldateformatter.create.php and http://userguide.icu-project.org/formatparse/datetime
