### ISSUE TITLE
PHP7 compatibility issue with symfony 2.7

### ISSUE THREAD

**Issue by kshitizlondon** [symfony/symfony#17341]
Hi, I have a basic symfony 2.7 installation on server with php7 installed.

I see this error:
Compile Error: Cannot use 'String' as class name as it is reserved

Can you please tell me, is sysmfony 2.7 version compatible with PHP7.

If not, please tell me which version should I use?

**Comment by stof** [comment]
Which class is it (which namespace, or which file) ? Are you sure it comes from Symfony ? AFAIK, we have deprecated classes named True and False (but they are optional and should not be used anymore, especially if you plan to use PHP 7 as they cannot work there), but not String class.

**Comment by kshitizlondon** [comment]
@stof ,

You are right I guess:

check this, i think it is twig and mongodb-odm issue:

```sh
$ find . -type f -name "String.php"
./vendor/phpunit/phpunit/src/Util/String.php
./vendor/twig/twig/lib/Twig/Loader/String.php
./vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Annotations/String.php
```
What should I do? Any advice on this issue will be appropriated!!!

**Comment by stof** [comment]
There is not issue in Twig, as the class name is ``Twig_Loader_String`` (same in PHPUnit btw).

For the MongoDB ODM, the ``String`` annotation is deprecated in favor of ``Field(type="string")``. So simply avoid using the deprecated API and it will work on PHP 7.
