### ISSUE TITLE
[Form][2.8.1] Feature "Allowed to return null for query_builder" not available

### ISSUE THREAD

**Issue by aguidis** [symfony/symfony#17352]
Hi,

This post [Symfony blog post](http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder) announced the feature **Allowed to return null for query_builder** has been introduced by commit [#13990](https://github.com/symfony/symfony/commit/e0a1294a44ca4ba902af6af4b4ddfc0dabf8a30d), but this commit [Fix "[Form] Add flexibility for EntityType"](https://github.com/symfony/symfony/commit/eb08baa9fcb6db3863c795ea54e324ced68d56ea) reverted it later.

What do you think ?

**Comment by Tobion** [comment]
The test (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php#L225) is still there and seems to pass. So what is the problem you are experiencing?

**Comment by Tobion** [comment]
Based on https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L168 maybe it's then querying everything that exists (instead of having an empty list)?

**Comment by aguidis** [comment]
Hello @Tobion, thanks for your answers,

My current project use Symfony 2.8.1 and tried to use this new feature but I noticed that I didn't have an empty list but the complete list of my entities in my select box (if I check the database queries in the profiler I have a SELECT * query on my entity table which is the default behavior of the EntityType).

After digging into the PR and the commits of the official repository I found that the code of this feature has been overridden.

In fact, the option `query_builder` is not null because it contains a `Closure` so the second condition is true :
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L166 

About the test you are right it's green :

![image](https://cloud.githubusercontent.com/assets/1856652/12320363/91a6b2b6-baa8-11e5-972a-02dbbd111609.png)

But maybe it's not enough efficient. I added these lines for reproducing my case, at the beginning of the test :

```php
$entity1 = new SingleIntIdEntity(1, 'Foo');
$entity2 = new SingleIntIdEntity(2, 'Bar');
$entity3 = new SingleIntIdEntity(3, 'Baz');
$this->persist(array($entity1, $entity2, $entity3));
```

![image](https://cloud.githubusercontent.com/assets/1856652/12320385/b805d13a-baa8-11e5-9d2b-bc81141d50f7.png)

**Comment by xabbuh** [comment]
@nicolas-grekas Do you remember the reason for eb08baa9fcb6db3863c795ea54e324ced68d56ea?

**Comment by michaelperrin** [comment]
Hello,

I can confirm the issue @aguidis reported.

The test @raziel057 introduced in 317d30b didn't fail when @nicolas-grekas commited eb08baa (I can't see the reason of this commit too) as the test has always passed, @nicolas-grekas therefore didn't see the regression.
The reason is that no fixtures are loaded during the test, so an empty array is always compared to an empty array, whether the feature is implemented or not.

Adding the fixtures like @aguidis proposes make the test fail, which is the expected result as the feature has disappeared from Symfony's code.

**Comment by nicolas-grekas** [comment]
The reason for eb08baa is that by looking [at the code](https://github.com/symfony/symfony/commit/eb08baa9fcb6db3863c795ea54e324ced68d56ea#diff-888009597299c21d535422fd4368bed3R55), `null` isn't a possible value for `$queryBuilder`.
But maybe the fix should have been to allow null. I don't remember :)

**Comment by HeahDude** [comment]
This one can be closed, see https://github.com/symfony/symfony/pull/18830.

**Comment by raziel057** [comment]
@nicolas-grekas The goal of my commit was indeed to allow to return ``null`` from a Closure to have an empty list. When you look at my sample and the code in 317d30b, ``$queryBuilder`` is not null but a Closure on first check.

Then we get the result of Closure by doing:
```
    $queryBuilder = $queryBuilder($manager->getRepository($class));

    if (null !== $queryBuilder && !$queryBuilder instanceof QueryBuilder) {
        throw new UnexpectedTypeException($queryBuilder, 'Doctrine\ORM\QueryBuilder');
    }
```

It's in this other check that queryBuilder needs to be nullable.

**Comment by raziel057** [comment]
@HeahDude #18830 is not the expected feature. The expected one is to get an empty list.

**Comment by HeahDude** [comment]
@raziel057 You can achieve that by passing an empty array to the `choices` option. If needed you can use a normaliser either on `choices` or `query_builder` option. Returning `null` from the closure just fallback on the default behaviour: loading all entities.

**Comment by raziel057** [comment]
@HeahDude I know I can pass an empty array to the ``choices`` option as shown in my sample https://github.com/symfony/symfony/commit/317d30b6efd4e906e9c84fbe558934448379285c

I'had created the PR exactly to change the default behaviour that can already be achieve when the Closure return the queryBuilder. In my mind passing ``null`` must not give the same result that passing the queryBuilder. It must give an empty result, and it permits to avoid to use a more verbose workarround.

**Comment by nicolas-grekas** [comment]
@raziel057 this code calling the closure is in a deprecated code path that does not exist anymore in 3.0.

**Comment by raziel057** [comment]
Please check the post entry here: http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder

**Comment by nicolas-grekas** [comment]
@raziel057 PR welcomed of course if something needs a change!

**Comment by raziel057** [comment]
@nicolas-grekas Ok thanks, I will try to look at this.

**Comment by HeahDude** [comment]
@raziel057 Concerning your sample on the blog post, consider:
```php
$event->getForm()->add('events', 'Symfony\Component\Form\Extension\Core\Type\EntityType', [
    'class' => 'AppBundle:Event',
    'property' => 'title',
    'query_builder' => function(EntityRepository $er) {
        return $er->getEventQueryBuilder();
    }
]));

// ...

public function configureOptions(OptionsResolver $resolver)
{
    if ( ... some condition ... ) {
        $resolver->setDefault('choices', array());

        return;
    }

    $resolver->setDefault(
        'query_builder', 
        $this->getEntityManager()->createQueryBuilder()->select(...)->...
    );
}
```

**Comment by HeahDude** [comment]
@raziel057 I've corrected my sample, you could also have a custom entity type for the "event" field and handle the options in that type to avoid setting default `null` values.

**Comment by raziel057** [comment]
@HeahDude Ok thanks, I didn't thought about this way to do it.
It's just a bit more complex, and unknown from the Symfony Community. I think it's a common feature and needs to be as simple as possible. That's the reason why I introduced the possibility to return null from the Closure. Before my commit, ``null`` was not accepted, so there were no BC.

**Comment by HeahDude** [comment]
@raziel057 
>It's just a bit more complex

It's just using the options resolver for what it's meant do, resolve the config :)

>That's the reason why I introduced the possibility to return null from the Closure

Yes this is still a feature, but the result is not the same and I think it should stay this way.

**Comment by raziel057** [comment]
@HeahDude Yes this is still a feature, but the result is not the same and I think it should stay this way. <- Is not the same as the current behaviour, but that behaviour have been introduced after my PR that have been approved and merged.

To resume here is explained the behavior when returning ``null`` from Closure.
- before Symfony 2.8: UnexpectedTypeException
- after commit 317d30b (20 Mar 2015) : choices = empty array();
- after commit eb08baa (2 Aug 2015) : choices = array() with all results

Do you understand what I mean? The default behaviour that have been agreed and communicated in http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder is the one covered by the commit 317d30b.

I just wants to explain why I said the initial behaviour was introduced without any BC. For my commit eb08baa introduced a bug that was not detected by the unit test I created because there were no data :(.

Now, if you think the current behaviour is more logical, no problem.

**Comment by HeahDude** [comment]
@raziel057 Agreed ;)

**Comment by raziel057** [comment]
@nicolas-grekas @HeahDude I looked at the code in 3.0 and the Normalizer applied on 'query_builder' in configureOptions of EntityType evaluates the closure first and modify the option. So currently it gives gives  ``'query_builder' => null`` when the closure itself returns null. In that case I need to return a ``false`` value.

It seems a bit weird for me to have to return a ``false`` but we need to be able to differentiate ``query_builder => null`` and ``query_builder => function(EntityRepository $er) { return; }`` to process a different behaviour in the choiceLoader closure of DoctrineType.

What do you think about it https://github.com/symfony/symfony/pull/19897 ?
