### ISSUE TITLE
[2.7+][WebTestCase] HTTP_USER_AGENT for client is ignored

### ISSUE THREAD

**Issue by pculka** [symfony/symfony#17351]
Imagine a scenario, where you need to follow redirects based on user_agent, having the default user_agent set in phpunit.xml. But for the sake of this, let's just remove the phpunit.xml UA definition

now following:
```php
        $client = static::createClient(array(), array(
            'PHP_AUTH_USER' => 'superadmin',
            'PHP_AUTH_PW'   => 'changeme',
            'HTTP_USER_AGENT' => 'iPhone'
        ));

        $crawler = $client->request(
            'GET',
            '/',
            array(),
            array(),
            array(
                'HTTP_USER_AGENT' => 'iPhone',
            )
        );

        $this->assertEquals(
            301, // or Symfony\Component\HttpFoundation\Response::HTTP_OK
            $client->getResponse()->getStatusCode()
        );
```

ends up with `$_SERVER['HTTP_USER_AGENT']` being not set, resulting in an exception in the MainController and killing the testing process with a Fail.

I tried to trace down the problem and found that in
BrowserKit\Client, around the line 302 the `$this->request` is still being populated with correct user agent, but SOMEHOW this gets removed for whatever reason while performing `$this->response = $this->doRequest($this->request);`

Can anybody explain WHY is this happening? and HOW can I properly assert getting 301 Code if hitting MainController with a predefined useragent?

Thanks

**Comment by stof** [comment]
``$_SERVER['HTTP_USER_AGENT']`` will not be set. You need to use the Request object to access request info, not superglobals. The browserkit client does not overwrite global variables.

**Comment by pculka** [comment]
oh god, thanks for the info. Now it works

**Comment by stof** [comment]
The WebTestCase does not perform actual requests, but only calls the kernel directly thanks to the request encapsulation. This works only when your code does not break this encapsulation. Any usage of the request superglobals (``$_GET``, ``$_POST``, ``$_COOKIES``, ``$_FILES``, ``$_SERVER`` or ``$_REQUEST``) is making your code incompatible with such testing (and also with the usage of subrequests)

**Comment by pculka** [comment]
yup, that sounds logical now, would be cool to make a note on this in the Testing cookbook?

**Comment by jakzal** [comment]
@pculka feel free to submit a PR to https://github.com/symfony/symfony-docs if you think an improvement would be cool :)
