### ISSUE TITLE
Enforce console color output

### ISSUE THREAD

**Issue by mbrodala** [symfony/symfony#17360]
Currently support for console [color output support is verified](https://github.com/symfony/console/blob/82acbe7244a2f628875fa2c5b1e05199f3098bc4/Output/StreamOutput.php#L93) by checking a few environment variables on Windows systems or the `posix_isatty()` function on other systems.

However, there may be cases where a console application is executed in a *nix environment which doesn't expose the current terminal as TTY.

This is the case in the Shippable CI build environment, thus no PHP application using Symfony console has color output over there even though [it actually works](https://github.com/Shippable/support/issues/774#issuecomment-171277473).

Thus I'd suggest introducing an environment variable to enforce color output for Symfony console apps  which should be evaluated before the other checks.

**Comment by mnapoli** [comment]
FYI the is the `--ansi` option to force colorized output.

**Comment by mbrodala** [comment]
@mnapoli I guess this must be passed through explicitly? E.g.

```
$ bin/phpunit --ansi
PHPUnit 4.8.3 by Sebastian Bergmann and contributors.

unrecognized option --ansi
```

**Comment by mnapoli** [comment]
For PHPUnit they use a different option (probably for historical reason): `--colors=always`.

**Comment by mbrodala** [comment]
Thanks, that actually did the trick. :-)
