### ISSUE TITLE
Form has errors of non mapped fields

### ISSUE THREAD

**Issue by webdevilopers** [symfony/symfony#17363]
My original issue started here:
https://github.com/craue/CraueFormFlowBundle/issues/186

I have a camel cased property `mountingType` in my entity:
```php
    /**
     * @var mounting type
     *
     * @ORM\ManyToOne(targetEntity="MountingType", inversedBy="configurations")
     * @ORM\JoinColumn(name="mounting_type_id", referencedColumnName="id")
     * @Assert\NotNull(groups={"flow_calculatorFlow_step1"})
     * @Assert\Type(type="AppBundle\Entity\MountingType", groups={"flow_calculatorFlow_step1"})
     */
    private $mountingType;
```

Accidentally - before I realized it - I used it the underscored property in my form (built with `CraueFormFlowBundle` by @craue ):
```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        switch ($options['flow_step']) {
            case 1:
                $builder
                    ->add('mounting_type', 'entity', array(
                        'required' => true,
                        'expanded' => true,
                        'class' => 'AppBundle:MountingType',
                    ))
```

I didn't realize the naming problem because my form was still correctly rendered AND populated after submission if the field was filled out:
```twig
<div>
    {{ form_label(form.mounting_type) }}
    <div id="calculator_mounting_type">
        {% for mounting_type in form.mounting_type %}
            {{ form_widget(mounting_type) }} {{ form_label(mounting_type, null, { 'label_attr': {
                    'class': 'ventura_radio_label'
                } } ) }}
        {% endfor %}
    </div>
</div>
```

If I submitted the form without filling out the field the profiler correctly counted(!) the error for the whole form - inside the error "bubble".
But the `mounting_type`field of the form itself showed(!) no error. Instead the camel cased property assertion showed up:
![3_1_errors](https://cloud.githubusercontent.com/assets/3479626/8391200/8ead3518-1cb9-11e5-959e-3bd6d50db9af.png)

I think this is neither bug or feature - it is a wrong configuration.
But it took me some time to figure out what was going on here.

Maybe this behaviour could be improved?

- The `Constraint` could check if the field exists.
- The `Form` field should not be rendered by twig instead of "guessing" a different naming convention
- The `Profiler` could add a hint that the errors were thrown on "non-mapped" fields.

I havn't tried but what would have happened if I turned on `error_bubbling` for this field - would the form have been valid or would the profiler simpy not show the error at all?

**Comment by iltar** [comment]
If I understand it right, this is only an issue where the property is not mapped properly in the error path as the rest seems to work, or am I wrong?

**Comment by webdevilopers** [comment]
In the end you are right. Twig will render the form fields anyway since it is based on the fields added to the form builder.
And the constraints check all the fields defined in the Entity.

But it took me some time to actually see the issue I caused by using different naming conventions.

The "Cause" says `...Form.data.mountingType = null`. And that is correct! But it looked to me as if there was a problem with the submitting process inside the form in the first place.

Maybe there is way to improve the profiler here. It could show up which of the fields are not mapped to properties of the bound Entity after the form was submitted?

**Comment by javiereguiluz** [comment]
Closing it because at the end it wasn't a bug. About changing the form profiler, that looks too complex for this use case. We'll do it if we get more error reports about this issue. Thanks!
