### ISSUE TITLE
Let's make Symfony tests faster

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17366]
### Problem

Thanks to the work of @nicolas-grekas and the community, Symfony tests are faster every day. But we can do better.

I've analyzed the Symfony 2.3 test suite and I've found that **some tests are very slow**. I can think of 3 reasons for a slow test:

1. It's slow because the tested Symfony feature is slow. Let's try to fix that feature.
2. It's slow because the test code is not good enough. Let's fix the test.
3. It's slow because the test or the Symfony feature are complicated. Nothing is wrong with the test. Don't change anything.

### Solution

* I propose to work on fixing the slowest Symfony tests. 
* If you are experienced with Symfony, add a comment in this issue saying which tests are you going to working on, so we don't duplicate the work (e.g. *I'm looking into Process component tests*).
* If you are new to Symfony and want to contribute, you can ask me for help or guidance.

When fixing a test/feature to make it faster, keep in mind that we'll reject:

* Meaningless changes (e.g. replace single quotes by double quotes).
* Changes that destroy code readability.

In case of doubt, ask us!

### Details

I took the fastest test as reference (in my machine it was `InputArgumentTest::testGetDefault`) and this is the list of the slowest Symfony tests:

#### Tests which are at least 10,000 times slower than the fastest test

```
 21,107x slower : Symfony\Component\HttpFoundation\Tests\Session\Storage\MetadataBagTest::testInitialize
 20,186x slower : Symfony\Component\Routing\Tests\Generator\Dumper\PhpGeneratorDumperTest::testDumpWithTooManyRoutes
 12,647x slower : Symfony\Component\Process\Tests\ProcessTest::testProcessPipes with data set #9
 [WORKING ON THIS] 10,754x slower : Symfony\Component\Filesystem\Tests\FilesystemTest::testCopyForOriginUrlsAndExistingLocalFileDefaultsToNotCopy
 10,601x slower : Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #2
 10,570x slower : Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #4
 10,569x slower : Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #3
```

#### Tests which are at least 1,000 times slower than the fastest test

```
  9,453x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsExposedWhenNotProtected with data set #0 ('config.yml')
  9,348x slower : Symfony\Component\Finder\Tests\Iterator\RecursiveDirectoryIteratorTest::testRewindOnFtp
  8,898x slower : Symfony\Component\Finder\Tests\Iterator\RecursiveDirectoryIteratorTest::testSeekOnFtp
  8,420x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenLoggedInWithInsufficientRights with data set #1 ('routes_as_path.yml')
  8,154x slower : Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testTwoClients with data set #0 ('config.yml', true)
  7,588x slower : Symfony\Component\Process\Tests\ProcessTest::testProcessPipes with data set #8 ('fwrite(STDOUT, $in = file_get... $in);', 4096)
  7,074x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenLoggedInWithInsufficientRights with data set #0 ('config.yml')
  7,064x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForMultipleIPAddresses with data set #0 ('config.yml')
  6,997x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForMultipleIPAddresses with data set #1 ('routes_as_path.yml')
  6,838x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsExposedWhenNotProtected with data set #1 ('routes_as_path.yml')
  6,774x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens with data set #0 ('config.yml')
  6,014x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\FormLoginTest::testFormLogin with data set #1 ('routes_as_path.yml')
  5,859x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testLoginLogoutProcedure with data set #0 ('en')
  5,800x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testLoginFailureWithLocalizedFailurePath with data set #0 ('en')
  5,646x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SwitchUserTest::testSwitchedUserCannotSwitchToOther
  4,590x slower : Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testWelcome with data set #0 ('config.yml', true)
  4,276x slower : Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testDuration
  4,142x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\FormLoginTest::testFormLogin with data set #0 ('config.yml')
  4,141x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens with data set #1 ('routes_as_path.yml')
  3,977x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testAccessRestrictedResourceWithForward with data set #0 ('en')
  3,941x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenAnonymous with data set #1 ('routes_as_path.yml')
  3,874x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SwitchUserTest::testSwitchUser with data set "authorized_user_cannot_switch_to_non_existent" ('user_can_switch', 'user_does_not_exist', 'user_can_switch', 500)
  3,849x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenAnonymous with data set #0 ('config.yml')
  3,804x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\AuthenticationCommencingTest::testAuthenticationIsCommencingIfAccessDeniedExceptionIsWrapped
  3,690x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForSingleIPAddress with data set #0 ('config.yml')
  3,686x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForSingleIPAddress with data set #1 ('routes_as_path.yml')
  3,332x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\FirewallEntryPointTest::testItUsesTheConfiguredEntryPointWhenUsingUnknownCredentials
  3,278x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\FirewallEntryPointTest::testItUsesTheConfiguredEntryPointFromTheExceptionListenerWithFormLoginAndNoCredentials
  3,116x slower : Symfony\Component\Process\Tests\ProcessTest::testGetExitCodeIsNullOnWhenStartingAgain
  3,006x slower : Symfony\Bundle\FrameworkBundle\Tests\Functional\ProfilerTest::testProfilerIsDisabled with data set #1 (true)
  2,816x slower : Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testFlash with data set #0 ('config.yml', true)
  2,323x slower : Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\CacheClearCommandTest::testCacheIsFreshAfterCacheClearedWithWarmup
  2,278x slower : Symfony\Component\Process\Tests\ProcessTest::testStartAfterATimeout
  2,214x slower : Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testEnsureStopped
  2,176x slower : Symfony\Component\Process\Tests\ProcessTest::testRunProcessWithTimeout
  2,166x slower : Symfony\Component\Stopwatch\Tests\StopwatchTest::testStop
  2,005x slower : Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\YamlCompleteConfigurationTest::testEncoders
  1,991x slower : Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginWithInvalidCsrfToken with data set #1 ('routes_as_path.yml')
  1,938x slower : Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testRest
  1,848x slower : Symfony\Bridge\Twig\Tests\Extension\FormExtensionDivLayoutTest::testThemeBlockInheritanceUsingUse
  [IMPROVED] 1,784x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\XmlFrameworkExtensionTest::testDisabledProfiler
  [IMPROVED] 1,758x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\YamlFrameworkExtensionTest::testValidation
  [IMPROVED] 1,736x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\XmlFrameworkExtensionTest::testValidation
  1,732x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\YamlFrameworkExtensionTest::testEsi
  [IMPROVED] 1,703x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\PhpFrameworkExtensionTest::testValidation
  [IMPROVED] 1,680x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\PhpFrameworkExtensionTest::testEsi
  1,658x slower : Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\XmlCompleteConfigurationTest::testEncoders
  1,617x slower : Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testDoesNotCacheSomeStatusCodeResponses
  1,614x slower : Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\PhpCompleteConfigurationTest::testRolesHierarchy
  1,604x slower : Symfony\Component\Process\Tests\ProcessTest::testGetExitCodeIsNullOnStart
  1,587x slower : Symfony\Component\Process\Tests\ProcessTest::testIsSuccessfulOnlyAfterTerminated
  1,574x slower : Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\SecurityExtensionTest::testFirewallWithoutAuthenticationListener
  1,560x slower : Symfony\Component\Process\Tests\ProcessTest::testStatus
  1,536x slower : Symfony\Component\Process\Tests\ProcessTest::testTTYCommand
  1,462x slower : Symfony\Component\Process\Tests\ProcessTest::testStopWithTimeoutIsActuallyWorking
  1,377x slower : Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testDateTime
  1,358x slower : Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperTableLayoutTest::testSingleChoiceRequiredWithEmptyValueViaView
  1,329x slower : Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperTableLayoutTest::testMoney
  1,285x slower : Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testTimeWithEmptyValueGlobal
  1,260x slower : Symfony\Component\Form\Tests\Extension\Validator\Type\FormTypeValidatorExtensionTest::testValidationGroupsCanBeSetToCallback
  1,253x slower : Symfony\Bridge\ProxyManager\Tests\LazyProxy\PhpDumper\ProxyDumperTest::testGetProxyCode
  1,227x slower : Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\ConfigurationTest::testValidTrustedProxies with data set #3 (null, array())
  1,174x slower : Symfony\Component\Console\Tests\Helper\DialogHelperTest::testAskWithAutocomplete
  1,146x slower : Symfony\Component\Process\Tests\ProcessTest::testCheckTimeoutOnStartedProcess
  1,119x slower : Symfony\Component\BrowserKit\Tests\ClientTest::testInsulatedRequests
  1,117x slower : Symfony\Component\Validator\Tests\Constraints\CardSchemeValidatorTest::testInvalidNumbers with data set #0 ('VISA', '42424242424242424242')
  1,106x slower : Symfony\Component\Finder\Tests\BsdFinderTest::testName
  1,083x slower : Symfony\Component\ClassLoader\Tests\ClassCollectionLoaderTest::testCommentStripping
  1,074x slower : Symfony\Bundle\FrameworkBundle\Tests\Functional\FragmentTest::testFragment with data set #1 (true)
  1,073x slower : Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testStartTime
  1,065x slower : Symfony\Component\Process\Tests\ProcessTest::testRestart
  1,061x slower : Symfony\Component\HttpFoundation\Tests\File\FileTest::testMove
  1,014x slower : Symfony\Component\Intl\Tests\NumberFormatter\Verification\NumberFormatterTest::testFormatRoundingModeHalfEven with data set #0 (1.121, '1.12')
  1,007x slower : Symfony\Component\Form\Tests\CompoundFormTest::testSetDataSupportsDynamicAdditionAndRemovalOfChildren
```

**Comment by sstok** [comment]
`testDumpWithTooManyRoutes` is slow because it generates allot of routes (32770 to be exact), so I doubt that one can be optimized :) (except for unwinding the loop to a separate file, but that will be quit big! approx 2.23 MiB and will still generate a big amount of objects).

**Comment by javiereguiluz** [comment]
@sstok OK, let's forget about that test then and let's focus on the other ones.

**Comment by smatyas** [comment]
@sstok I think that test is about the dumper, so maybe the urlgenerator part could be left out. It could be enough i.e. to check the last line of the dumped file, if that contains the expected data. Or the total lines/size of the dumped file. I think it would speed up the test. What do you think?

**Comment by paradajozsef** [comment]
@javiereguiluz  I could optimize on ```XmlFrameworkExtensionTest```, ```YamlFrameworkExtensionTest``` and ```PhpFrameworkExtensionTest``` under ```Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\```

I'll propose a PR in a moment.

**Comment by WouterJ** [comment]
`Symfony\Component\HttpFoundation\Tests\Session\Storage\MetadataBagTest::testInitialize` can't be optimized, as it's based on time and thus has to use `sleep(1)` a couple times in order to verify the timing features.

Btw, to be honest I don't think fixing this issue will improve any of the speed. When using the parallel PHPunit execution (which everyone can use by just doing `php ./phpunit symfony`), tests are run in 20 seconds. That's already very fast for 12875 tests.

To give you an idea, when not running phpunit in parallel, running all tests takes 55 seconds on my PC. The slowest test (`Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testTwoClients with data set #0`) takes 2 microsecond longer to execute than an average test (which takes 0.004 microseconds). This reduces to 1 microsecond for 4 other tests, afterwards the tests are less than 0.5 microseconds slower than an average test. I don't think making these 81 listed tests a bit faster will improve test speed in any way. Instead, the number of tests has to be reduced, which is probably possible when looking more closely at tests. Especially tests in the older components (like HttpFoundation) can be improved quite a bit (try to read them, it's very hard).

**Comment by javiereguiluz** [comment]
@WouterJ on Travis tests take between 3 and 6 minutes for each Symfony version and around 18 minutes in total. This initiative can help us get faster feedback from Travis, which is always nice.

Besides, you are right ... and that's another way of making tests faster: removing unneeded or redundant tests. For example, yesterday I was looking at `NumberFormatterTest`. Don't you think that in [these lines](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php#L35-L50) there are a lot of redundant tests?

In any case, any help is greatly appreciated to make tests (and the underlying code) faster. Thanks!

**Comment by smatyas** [comment]
I'm working on optimizing `FilesystemTest`, PR will be made soon.

**Comment by javiereguiluz** [comment]
@smatyas cool! I've updated the list to let others know that you are working on this.

**Comment by WouterJ** [comment]
I think all Functional tests (FrameworkBundle and SecurityBundle ones) can be removed from this issue. They are functional tests, which are by definition much slower than the fastest unit test in the code base (booting Symfony and requesting a page takes time).

**Comment by javiereguiluz** [comment]
@WouterJ you are right of course. But we could also investigate why functional tests are so slow (or "not fast enough"). And maybe we could also try to make Symfony boot faster.

**Comment by Jean85** [comment]
It's nice to tidy up the test, good issue!

But since part of the issue seems to be Travis being slow, shouldn't we check why it's like this?
I'm checking the logs, and it appears that there's something wrong with some build envs; here an example with build 28488:

 * PHP: hhvm - no environment variables set
   * 4 min 59 sec
 * PHP: 5.3 - no environment variables set
   * 3 min 51 sec
 * PHP: 5.4 - no environment variables set
   * **54 sec**
 * PHP: 5.5 - no environment variables set
   * 1 min 10 sec
 * PHP: 5.6 - deps=high
   * 4 min 48 sec
 * PHP: 7 - deps=low
   * 4 min 18 sec

As we can see, we have a really fast build under PHP 5.4 and 5.5, but we're having problems under HHVM, 5.3 and the deps cases.

I think I've uncovered a problem under the deps cases; these are the command lines:

    if [[ $deps = high ]]; then echo "$COMPONENTS" | parallel --gnu -j10% 'cd {}; composer update --prefer-dist; $PHPUNIT --exclude-group tty,benchmark,intl-data'$LEGACY; fi;
    if [[ $deps = low ]]; then echo "$COMPONENTS" | parallel --gnu -j10% 'cd {}; composer update --prefer-dist --prefer-lowest --prefer-stable; $PHPUNIT --exclude-group tty,benchmark,intl-data'; fi;

They seems wrong to me! As in the output, they re-run the composer install each time with each group of parallel execution, wasting a lot of time and resources! They took 180-200 secs instead of the normal ~50...

**Comment by xabbuh** [comment]
@Jean85 These jobs are so fast because we skip them for pull request. :)

**Comment by Jean85** [comment]
Oh, ok, sorry that I missed that!

**Comment by WouterJ** [comment]
@javiereguiluz in that case, this issue has a very very big scope, doesn't it? I mean, if we want to make functional tests faster, we have to improve the speed of the Symfony Kernel. I think improving the speed of the kernel is one of the top priorities for all team members all the time (it shouldbe at least, knowing that people still frequently call this framework "the slowest PHP framework").

**Comment by javiereguiluz** [comment]
To make it easier to work with them, I've grouped slow tests by component/bundle/bridge. We only show tests which are 1,000 times slower or worse.

---

### Symfony / Bridge / ProxyManager

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,253 | Symfony\Bridge\ProxyManager\Tests\LazyProxy\PhpDumper\ProxyDumperTest::testGetProxyCode


### Symfony / Bridge / Twig

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,848 | Symfony\Bridge\Twig\Tests\Extension\FormExtensionDivLayoutTest::testThemeBlockInheritanceUsingUse


### Symfony / Bundle / FrameworkBundle

| Status | Slowness | Test
| ------ | -------- | ----
| | 8,154 | Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testTwoClients with data set #0
| | 4,590 | Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testWelcome with data set #0
| | 3,006 | Symfony\Bundle\FrameworkBundle\Tests\Functional\ProfilerTest::testProfilerIsDisabled with data set #1
| | 2,816 | Symfony\Bundle\FrameworkBundle\Tests\Functional\SessionTest::testFlash with data set #0
| | 2,323 | Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\CacheClearCommandTest::testCacheIsFreshAfterCacheClearedWithWarmup
| | 1,938 | Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testRest
| IMPROVED | 1,784 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\XmlFrameworkExtensionTest::testDisabledProfiler
| IMPROVED | 1,758 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\YamlFrameworkExtensionTest::testValidation
| IMPROVED | 1,736 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\XmlFrameworkExtensionTest::testValidation
| | 1,732 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\YamlFrameworkExtensionTest::testEsi
| IMPROVED | 1,703 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\PhpFrameworkExtensionTest::testValidation
| | 1,680 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\PhpFrameworkExtensionTest::testEsi
| | 1,377 | Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testDateTime
| | 1,358 | Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperTableLayoutTest::testSingleChoiceRequiredWithEmptyValueViaView
| | 1,329 | Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperTableLayoutTest::testMoney
| | 1,285 | Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testTimeWithEmptyValueGlobal
| | 1,227 | Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\ConfigurationTest::testValidTrustedProxies with data set #3
| | 1,074 | Symfony\Bundle\FrameworkBundle\Tests\Functional\FragmentTest::testFragment with data set #1


### Symfony / Bundle / SecurityBundle

| Status | Slowness | Test
| ------ | -------- | ----
| | 12,437 | Symfony\Bundle\SecurityBundle\Tests\Functional\SwitchUserTest::testSwitchUser with data set "unauthorized_user_cannot_switch" ('user_cannot_switch_1', 'user_cannot_switch_1', 'user_cannot_switch_1', 403)
| | 9,453 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsExposedWhenNotProtected with data set #0
| | 8,420 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenLoggedInWithInsufficientRights with data set #1
| | 7,074 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenLoggedInWithInsufficientRights with data set #0
| | 7,064 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForMultipleIPAddresses with data set #0
| | 6,997 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForMultipleIPAddresses with data set #1
| | 6,838 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsExposedWhenNotProtected with data set #1
| | 6,774 | Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens with data set #0
| | 6,014 | Symfony\Bundle\SecurityBundle\Tests\Functional\FormLoginTest::testFormLogin with data set #1
| | 5,859 | Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testLoginLogoutProcedure with data set #0
| | 5,800 | Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testLoginFailureWithLocalizedFailurePath with data set #0
| | 5,646 | Symfony\Bundle\SecurityBundle\Tests\Functional\SwitchUserTest::testSwitchedUserCannotSwitchToOther
| | 4,142 | Symfony\Bundle\SecurityBundle\Tests\Functional\FormLoginTest::testFormLogin with data set #0
| | 4,141 | Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens with data set #1
| | 3,977 | Symfony\Bundle\SecurityBundle\Tests\Functional\LocalizedRoutesAsPathTest::testAccessRestrictedResourceWithForward with data set #0
| | 3,941 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenAnonymous with data set #1
| | 3,874 | Symfony\Bundle\SecurityBundle\Tests\Functional\SwitchUserTest::testSwitchUser with data set "authorized_user_cannot_switch_to_non_existent" ('user_can_switch', 'user_does_not_exist', 'user_can_switch', 500)
| | 3,849 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testRoutingErrorIsNotExposedForProtectedResourceWhenAnonymous with data set #0
| | 3,804 | Symfony\Bundle\SecurityBundle\Tests\Functional\AuthenticationCommencingTest::testAuthenticationIsCommencingIfAccessDeniedExceptionIsWrapped
| | 3,690 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForSingleIPAddress with data set #0
| | 3,686 | Symfony\Bundle\SecurityBundle\Tests\Functional\SecurityRoutingIntegrationTest::testSecurityConfigurationForSingleIPAddress with data set #1
| | 3,332 | Symfony\Bundle\SecurityBundle\Tests\Functional\FirewallEntryPointTest::testItUsesTheConfiguredEntryPointWhenUsingUnknownCredentials
| | 3,278 | Symfony\Bundle\SecurityBundle\Tests\Functional\FirewallEntryPointTest::testItUsesTheConfiguredEntryPointFromTheExceptionListenerWithFormLoginAndNoCredentials
| | 2,005 | Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\YamlCompleteConfigurationTest::testEncoders
| | 1,991 | Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginWithInvalidCsrfToken with data set #1
| | 1,658 | Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\XmlCompleteConfigurationTest::testEncoders
| | 1,614 | Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\PhpCompleteConfigurationTest::testRolesHierarchy
| | 1,574 | Symfony\Bundle\SecurityBundle\Tests\DependencyInjection\SecurityExtensionTest::testFirewallWithoutAuthenticationListener


### Symfony / Component / BrowserKit

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,119 | Symfony\Component\BrowserKit\Tests\ClientTest::testInsulatedRequests


### Symfony / Component / ClassLoader

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,083 | Symfony\Component\ClassLoader\Tests\ClassCollectionLoaderTest::testCommentStripping


### Symfony / Component / Console

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,174 | Symfony\Component\Console\Tests\Helper\DialogHelperTest::testAskWithAutocomplete


### Symfony / Component / Filesystem

| Status | Slowness | Test
| ------ | -------- | ----
| PENDING PR | 10,754 | Symfony\Component\Filesystem\Tests\FilesystemTest::testCopyForOriginUrlsAndExistingLocalFileDefaultsToNotCopy


### Symfony / Component / Finder

| Status | Slowness | Test
| ------ | -------- | ----
| | 10,601 | Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #2
| | 10,570 | Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #4
| | 10,569 | Symfony\Component\Finder\Tests\Iterator\SortableIteratorTest::testAccept with data set #3
| | 9,348 | Symfony\Component\Finder\Tests\Iterator\RecursiveDirectoryIteratorTest::testRewindOnFtp
| | 8,898 | Symfony\Component\Finder\Tests\Iterator\RecursiveDirectoryIteratorTest::testSeekOnFtp
| | 1,106 | Symfony\Component\Finder\Tests\BsdFinderTest::testName


### Symfony / Component / Form

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,260 | Symfony\Component\Form\Tests\Extension\Validator\Type\FormTypeValidatorExtensionTest::testValidationGroupsCanBeSetToCallback
| | 1,007 | Symfony\Component\Form\Tests\CompoundFormTest::testSetDataSupportsDynamicAdditionAndRemovalOfChildren


### Symfony / Component / HttpFoundation

| Status | Slowness | Test
| ------ | -------- | ----
| | 21,107 | Symfony\Component\HttpFoundation\Tests\Session\Storage\MetadataBagTest::testInitialize
| | 1,061 | Symfony\Component\HttpFoundation\Tests\File\FileTest::testMove


### Symfony / Component / HttpKernel

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,617 | Symfony\Component\HttpKernel\Tests\HttpCache\HttpCacheTest::testDoesNotCacheSomeStatusCodeResponses


### Symfony / Component / Intl

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,014 | Symfony\Component\Intl\Tests\NumberFormatter\Verification\NumberFormatterTest::testFormatRoundingModeHalfEven with data set #0


### Symfony / Component / Process

| Status | Slowness | Test
| ------ | -------- | ----
| | 12,647 | Symfony\Component\Process\Tests\ProcessTest::testProcessPipes with data set #9
| | 7,588 | Symfony\Component\Process\Tests\ProcessTest::testProcessPipes with data set #8
| | 3,116 | Symfony\Component\Process\Tests\ProcessTest::testGetExitCodeIsNullOnWhenStartingAgain
| | 2,278 | Symfony\Component\Process\Tests\ProcessTest::testStartAfterATimeout
| | 2,176 | Symfony\Component\Process\Tests\ProcessTest::testRunProcessWithTimeout
| | 1,604 | Symfony\Component\Process\Tests\ProcessTest::testGetExitCodeIsNullOnStart
| | 1,587 | Symfony\Component\Process\Tests\ProcessTest::testIsSuccessfulOnlyAfterTerminated
| | 1,560 | Symfony\Component\Process\Tests\ProcessTest::testStatus
| | 1,536 | Symfony\Component\Process\Tests\ProcessTest::testTTYCommand
| | 1,462 | Symfony\Component\Process\Tests\ProcessTest::testStopWithTimeoutIsActuallyWorking
| | 1,146 | Symfony\Component\Process\Tests\ProcessTest::testCheckTimeoutOnStartedProcess
| | 1,065 | Symfony\Component\Process\Tests\ProcessTest::testRestart


### Symfony / Component / Routing

| Status | Slowness | Test
| ------ | -------- | ----
| | 20,186 | Symfony\Component\Routing\Tests\Generator\Dumper\PhpGeneratorDumperTest::testDumpWithTooManyRoutes


### Symfony / Component / Stopwatch

| Status | Slowness | Test
| ------ | -------- | ----
| | 4,276 | Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testDuration
| | 2,214 | Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testEnsureStopped
| | 2,166 | Symfony\Component\Stopwatch\Tests\StopwatchTest::testStop
| | 1,073 | Symfony\Component\Stopwatch\Tests\StopwatchEventTest::testStartTime


### Symfony / Component / Validator

| Status | Slowness | Test
| ------ | -------- | ----
| | 1,117 | Symfony\Component\Validator\Tests\Constraints\CardSchemeValidatorTest::testInvalidNumbers with data set #0

**Comment by paradajozsef** [comment]
I'm looking into ```Smfony\Bundle\SecurityBundle\Tests\DependencyInjection\*``` tests.

**Comment by javiereguiluz** [comment]
@paradajozsef thanks! Updated the list.

**Comment by nicholas-eden** [comment]
For some of the tests involving sleep, would it make sense to use the Carbon library rather than calling time()?

This would allow us to set a mock time for Carbon, then add a second to the mock time where we would otherwise sleep.

**Comment by Jean85** [comment]
I don't think that tests with sleeps are an issue: since we are running them in parallel, while they sleep other tests will have their (CPU) time to do their work...

**Comment by nicholas-eden** [comment]
@Jean85 are you sure the tests are running in parallel?  I don't see paratest or anything to allow parallel testing.

**Comment by jakzal** [comment]
@nicholas-eden we already "mock the clock" in time sensitive tests with the [phpunit-bridge](https://github.com/symfony/symfony/tree/master/src/Symfony/Bridge/PhpUnit). All tests in the [`@group time-sensitive`](https://github.com/symfony/symfony/blob/34a08464ce53748d7944ece47aee1407a0d1f7f2/src/Symfony/Component/Stopwatch/Tests/StopwatchTest.php#L21) have the [time sensitive functions](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/ClockMock.php) replaced.

@Jean85 even though tests are run in parallel, `sleep()` in tests can still slow down the test suite.

**Comment by javiereguiluz** [comment]
I've been discussing with @nicolas-grekas about this issue. I'm closing it because right now its scope is too broad. Generally speaking the test suite is fast enough (Travis/AppVeyor are the real "bottlenecks" here). So let's close this and let's open in the future other pull request about specific tests that may seem too slow.

Thank you all for the discussion and for the submitted PRs which allows us to speed the test suite a bit.
