### ISSUE TITLE
SF3 security-bundle -> missing parameters for listeners

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#17376]
hello ...

I'm trying to update symfony 2.7 -> 3.0.1 and I see that in security listeners/configs there are no parameters for classes

it's bad merge ? bug ? or I really can not update actual listeners/classes/configs ?

**Comment by xabbuh** [comment]
All the class parameters were removed intentionally (see #14070). There are better ways to customise core services (for example, by using [service decoration](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services)).

**Comment by poolerMF** [comment]
thank you for response @xabbuh 

can you give me advice ? in which file, should I decorate services ?
