### ISSUE TITLE
FORMS -> CollectionType bug ?

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#17381]
when using SF3:

GroupFormType:

    $builder
        ->add('code', TextType::class)
        ->add('roles', CollectionType::class, [
            'entry_type' => RoleFormType::class,
            'entry_options' => [
                'data_class' => '...Entity\Role'
            ]
        ]);
    
form.roles shows correctly ...

when I remove entry_options and in form **RoleFormType** in function **configureOptions** set:

    $resolver->setDefaults(['data_class' => '...Entity\Role'])

then form.roles do not show

in Symfony 2.8 this works great

**Comment by xabbuh** [comment]
This will be fixed with 3.0.2 which will include the fix from #17162 (you can observe the same behaviour when using Symfony 2.8.1 instead of 2.8.2).
