### ISSUE TITLE
[Process] missing behavior explained in phpdoc ?

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#17387]
Currently in Process.php we have a behavior detailled:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L243-L245
> If there is no callback passed, the wait() method can be called with true as a second parameter then the callback will get all data occurred in (and since) the start call.

But I don't find anything in the present code that could make this behavior working (and no test). And indeed it is not working for me.

FYI this phpdoc was implemented [a long time ago](
https://github.com/symfony/process/commit/3523cab07ca9a4aea7b23a522230f4c91aded7f7).

This behavior would be useful in fact. Am I missing something or it has been deleted and the doc stills out to date ?

**Comment by jakzal** [comment]
This part was never implemented. See #3681 for the original PR. 

If no one is eager to implement this behaviour we should remove that comment.

**Comment by stof** [comment]
We should simply remove it in all versions. Even if this gets implemented, it would be a new feature and so go in master, not in maintenance branches.

**Comment by jakzal** [comment]
Indeed.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #17448.
