### ISSUE TITLE
[HttpFoundation] Refactor the Request / Response classes to use the standard interfaces from php-fig

### ISSUE THREAD

**Issue by Ener-Getick** [symfony/symfony#17392]
As discussed [here](https://github.com/symfony/symfony/pull/17379#issuecomment-171905787), it may be the time to think about refactoring the ``Request`` and the ``Response`` classes to follow the ``php-fig`` standards.

You can see this interfaces [here](https://github.com/php-fig/http-message).

Message from @iltar:
>
Actually, I've been thinking of converting the current Request/Response objects to builders. Parameter converters etc are all working by setting values and the same goes for response listeners. By converting the ResponseBuilder and RequestBuilder into a "frozen" variant, it can also be compliant with PSR. This means that when modifying the request > builder but your action > PSR request. Same goes for the response, you can return a Response(Builder), which gets converted to a PSR Response if not already.

**Comment by Tobion** [comment]
Duplicate of #15414

**Comment by stof** [comment]
This is impossible without creating a new incompatible framework (even though you keep the name, which only makes things harder).
Just look at closed issues talking about PSR-7 and at the Symfony blog (even though some of the discussion also happened privately in the core team, I think we posted our conclusions publicly).

this is why we have a PSR-7 bridge allowing to convert between PSR-7 and HttpFoundation instead.

**Comment by Ener-Getick** [comment]
@Tobion @stof right sorry I didn't see this issues... 

To be closed then.
