### ISSUE TITLE
Implement PSR-7 for Request and Response objects

### ISSUE THREAD

**Issue by codykrainock** [symfony/symfony#17394]
The PSR-7 standard has been introduced, and it would be beneficial if the framework followed these guidelines for interoperability purposes between libraries.

* Symfony\Component\HttpFoundation\Request
* Symfony\Component\HttpFoundation\Response

We are currently using the Symfony HttpFoundation classes for OAuth2 implementation. Since Slim 3 and others have moved to a PSR-7 standard, we are experiencing interoperability issues since the HttpFoundation\Request and Response objects do not conform to the standard.

**Comment by Tobion** [comment]
Pleaes use the search. Thanks

**Comment by codykrainock** [comment]
@Tobion - can you clarify? I searched existing issues on this repo and didn't find anything.

**Comment by xabbuh** [comment]
@codykrainock You can take a look at #15414 and #17392 for some background information.
