### ISSUE TITLE
Combining template overriding with inheritance

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#17407]
It would be great to have a functionality which allows to remove uncustomised Twig blocks from a template override. All blocks existing in the override template should be used from there, while the remaining ones should be used from the original template in the bundle.

This would further simplify customisation as you could do something like this.

Bundle template:
```
{% block content %}
    {# ... #}
    {{ block('additions') }}
{% endblock %}
{# ... #}
{% block additions %}{% endblock %}
```

Override:
```
{% block additions 'My addition' %}
```
So you do not need to copy whole templates anymore, but can just focus on what you need to change. This reduces maintaining the customised templates, too.

A similar functionality does already exist for translations where only a subset of all messages can be added to an override.

**Comment by jockri** [comment]
This is what I'm using to have this functionality. 
Not sure that this solution covers all edge case, and can be added to the `BaseKernel`
Any thoughts about it?

Create your own `Kernel` class and extend 2 functions from the `BaseKernel`:
```php
namespace Company\YourBundle\HttpKernel;

use Symfony\Component\HttpKernel\Kernel as BaseKernel;

abstract class OwnKernel extends BaseKernel
{
    public function getBundle($name, $first = true)
    {
        $getNext = false;
        if ($name[0] == '!' && $first) {
            $name = substr($name, 1);
            $first = false;
            $getNext = true;
        }

        $bundles = parent::getBundle($name, $first);

        if ($getNext) {
            return isset($bundles[1]) ? $bundles[1] : $bundles[0];
        } else {
            return $bundles;
        }
    }

    public function locateResource($name, $dir = null, $first = true)
    {
        $getNext = false;
        if ($name[0] == '@' && $name[1] == '!' && $first) {
            $name = '@' . substr($name, 2);
            $first = false;
            $getNext = true;
        }

        $files = parent::locateResource($name, $dir, $first);

        if ($getNext) {
            return isset($files[1]) ? $files[1] : $files[0];
        } else {
            return $files;
        }
    }
}
```

Make sure the AppKernel extends your own Kernel class:
```php
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends \Comapny\YourBundle\HttpKernel\OwnKernel
{
    public function registerBundles()
    {
        $bundles = array();

        // Bundles here...

        return $bundles;
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(__DIR__.'/config/config_'.$this->getEnvironment().'.yml');
    }
}
```

Then you can override parts of templates in your `app/Resources/...` by adding an `!` before the template notation 
```twig
{% extends '!CompanyYourBundle:Admin:edit.html.twig' %}

{% block additions %}
    Extra things here
{% endblock %}
```

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. Since this has been asked a lot of times and there are several issues that ask the same, I've created a new issue to centralize the discussion. That's why I'm closing this and I invite you to join #17557 to help us implement this feature. Thanks!
