### ISSUE TITLE
[DX] Improve generation of absolute URLs

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17413]
### Problem

In Symfony 2.x this is how you generate an absolute URL:

```php
$this->get('router')->generate('route_name', $routeParams, true);
```

This is how you do the same in Symfony 3.x:

```php
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

$this->get('router')->generate('route_name', $routeParams, UrlGeneratorInterface::ABSOLUTE_URL);
```

To me, the new version looks infinitely worse than the old one.

### Solution

I guess Symfony Core won't accept bringing back the boolean argument, so we could add a new `generateUrl()` method:

```php
$this->get('router')->generateUrl('route_name', $routeParams);
```

Thoughts? Better ideas? Thanks!

**Comment by sensorario** [comment]
And, ... isn't a route a value object? Could Symfony core introduce VO in route generation?

```php
$this->get('router')->generate([
    'route_name' => 'foo',
    'params' => [
        'bar' => $routeParams,
    ]
);
```

**Comment by Pierstoval** [comment]
@sensorario This is not the subject of the issue, actually...

Using `generateUrl` is a good idea but actually, having aliases like in Twig may be much better: `generatePath` and `generateUrl` are more "verbose" IMO.

**Comment by peterrehm** [comment]
@javiereguiluz To make it more clear `generateAbsoluteUrl` might be more intuitive.

**Comment by sensorario** [comment]
@Pierstoval ok =) thanks.

**Comment by xabbuh** [comment]
@javiereguiluz The "new" way (i.e. passing the constant from the interface instead of hardcoded values) works the same in Symfony 2 and should always be preferred to avoid issues when upgrading (we updated the docs for this recently).

**Comment by xabbuh** [comment]
But yeah, having shortcut methods with meaningful names (like `generateAbsoluteUrl()`) for the different values might be a good idea.

**Comment by Tobion** [comment]
Just make it the same as the twig shortcuts (url, path) but from the base controller/trait.

**Comment by javiereguiluz** [comment]
@Tobion yes, but we also want to improve DX for any code using the URL generator outside a controller.

**Comment by WouterJ** [comment]
I think the new version is infinitely better. Given there are more than 2 reference types (absolute url, absolute path, relative path and network path), using boolean values don't make any sense here.

I fail to see how it can be much worse. Apart from the fact that you need to type/know the FQCN. However, FQCN can be autocompleted (which is why we use the FQCN for form types now as well...). So instead of a meaningless value (true), you know have a very meaningfull argument.

**Comment by Tobion** [comment]
:-1: On adding a helper method on the router/generator itself. First it cannot be added to the interface because thats a bc break. Secondly, it does not make sense to have two methods for the same thing.

```
$this->get('router')->generate('route_name', $routeParams, true);
$this->get('router')->generate('route_name', $routeParams, UrlGeneratorInterface::ABSOLUTE_URL);
```

IMO the second signature is way more self-explanatory than the first and thus better DX.

**Comment by javiereguiluz** [comment]
@Tobion the long version is more expressive. But the problem is that it's too long (`UrlGeneratorInterface::ABSOLUTE_URL` has 35 chars!! and it requires you to add an import).

```php
$this->get('router')->generate('route_name', $routeParams, true);

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
$this->get('router')->generate('route_name', $routeParams, UrlGeneratorInterface::ABSOLUTE_URL);

$this->get('router')->generateUrl('route_name', $routeParams);
```

**Comment by Tobion** [comment]
Clarity is more important that shortness. For shortness there are IDEs you can use. But for clarity you cannot have tools.

**Comment by Tobion** [comment]
Otherwise you could also propose to remove every constant from symfony. The values are usually shorter (like integers) than the constant.

**Comment by javiereguiluz** [comment]
@Tobion I won't propose to remove constants ... but I'd like some of them to be shorter.

**Comment by Tobion** [comment]
Shorter constant names?

**Comment by alexandresalome** [comment]
What about ``->generate('route_name', $routeParams, 'absolute')``?

Would it be acceptable to add a ``if (is_string($referenceType))`` block at the beginning?

**Comment by sensorario** [comment]
@Tobion is new method in an interface a bc? How can new method cause failing in other components?

**Comment by iltar** [comment]
@javiereguiluz one thing you could do, is shorten the class name:
```php
$this->router->generate('route_name', $routeParams, PATH::ABSOLUTE_URL);
```
Additionally you could split them:
```php
$this->router->generate('route_name', $routeParams, Path::AS_URL);
$this->router->generate('route_name', $routeParams, Path::ABSOLUTE);
$this->router->generate('route_name', $routeParams, Path::RELATIVE);
$this->router->generate('route_name', $routeParams, Path::NETWORK);
```
In fact, the URL generator has mainly options to generate paths at the moment.

```php
final class Path
{
    const AS_URL = '...'; // or maybe FULL_URL? 
}

// and for bc reasons
interface UrlGeneratorInterface
{
    const ABSOLUTE_URL = Path::AS_URL;
}
```

This would be a lot shorter and friendlier to write from a DX perspective.

**Comment by WouterJ** [comment]
@javiereguiluz you are free to use `UrlGenerator::ABSOLUTE_PATH`, which saves some characters. Imports don't matter, these are autocompleted (and required imports were not rejected for form types, which are much more commonly used than url generation).

**Comment by javiereguiluz** [comment]
> Shorter constant names?

@Tobion in my opinion constants mostly used by developers (and not by internal code) should be as short as possible. In the past we did [some changes](https://github.com/symfony/symfony/pull/12074) to achieve that. For example:

```php
// we changed this...
use Symfony\Component\Security\Core\SecurityContextInterface;
SecurityContextInterface::AUTHENTICATION_ERROR

// ... by this
use Symfony\Component\Security\Core\Security;
Security::AUTHENTICATION_ERROR
```

**Comment by stof** [comment]
> @Tobion is new method in an interface a bc? How can new method cause failing in other components?

@sensorario The issue is that it forces all implementations of the interface to implement the new methods, otherwise they don't respect the interface anymore.

Btw, this is also why I think shortcut methods should not be in the router itself: they don't play well with composition at all. A class providing shortcuts should wrap the router instead of being the router itself

**Comment by Tobion** [comment]
IMO we can close this issue in favor of #16863. Just create a RouterTrait with those shortcuts like silex does.

**Comment by mnapoli** [comment]
How about a new "enum" kind of class that would only contain the constants?

Before:

```php
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

$router->generate('route_name', $params, UrlGeneratorInterface::ABSOLUTE_URL);
```

After:

```php
use Symfony\Component\Routing\Generator\UrlType;

$router->generate('route_name', $params, UrlType::ABSOLUTE);
```

**Comment by iltar** [comment]
@mnapoli see my suggestion

**Comment by mnapoli** [comment]
@iltar Ah right sorry I thought you had just aliased the `UrlGeneratorInterface` to `Path` ;)

**Comment by Pierstoval** [comment]
I like your idea @iltar !

**Comment by pimolo** [comment]
:+1: @javiereguiluz
- IMO using theses current constants is not instinctive ;
- I don't like long constants because it encourage most of developers to make more hard wraps* to respect team conventions.

And I think we could deepen the @iltar suggestion because it don't brings BC breaks.

*Ok, lots of hard wraps are not bad in itself, but it would be great if we could reduce their using as possible, especially if they are just caused by too long constants...

**Comment by javiereguiluz** [comment]
Closing it because it seems that this proposal won't get approved.
