### ISSUE TITLE
[DX] Add ability to disable AddClassesToCachePass compiler pass

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#17439]
There is no way to disable AddClassesToCachePass compiler pass.
It generates `classes.map` file, and then `ClassCacheCacheWarmer` always generated `classes.php` file.
So, if I do `app/console cache:warmup` for my dev environment I got a `classes.php` file *always*, wihtout exceptions. But I want to disable that, as it described in http://symfony.com/doc/current/cookbook/debugging.html (my IDE is not very happy with `classes.php` file)

The only one way to do that is to override `buildContainer` method in `AppKernel.php` file and remove line
```php
$container->addCompilerPass(new AddClassesToCachePass($this));
```

There should be more convient way to do that.

**Comment by iltar** [comment]
Can't you simply exclude the var (or app/cache) directory from indexation? It shouldn't be a problem to an IDE to have this. I've personally never encountered a problem with this (or the above solutions provided).

**Comment by Strate** [comment]
I do not want to exclude `app/cache` directory from index - I want to have an indexed generated container/router/twig/etc files.
My ide (PhpStorm) can not exclude one file.

And one more thing, in cookbook entry http://symfony.com/doc/current/cookbook/debugging.html there is a section which describes how cache file could be renamed:

> Some IDEs do not like the fact that some classes are stored in different locations. To avoid problems, you can either tell your IDE to ignore the PHP cache files, or you can change the extension used by Symfony for these files:
> $kernel->loadClassCache('classes', '.php.cache');

This is definetely does not work now, because `classes.php` is hardcoded to `ClassCacheCacheWarmer`.

**Comment by iltar** [comment]
I'm using phpstorm and I've never had those issues before. Even if you mark it as excluded, you won't have issues with the symfony plugin.

![](http://i.imgur.com/neXLuIm.png)

**Comment by aivus** [comment]
@iltar what happens when you try to debug code, which in cache?
I think main reason in it.

**Comment by Strate** [comment]
I will try to developing with excluded cache folder, but inconsistent cookbook entry still an issue (and BC for developing)

**Comment by xabbuh** [comment]
We have another inconsistency here. The `loadClassCache()` method from the `Kernel` class makes it possible to customise the cache prefix and extension of the generated cache file but the cache warmer has a hard coded `classes.php` filename. So in the worst case you would end up with two generated cache files.

**Comment by xabbuh** [comment]
We could introduce an option that would make it possible to disable the cache warmer (meaning the service definition wouldn't be loaded when the option was disabled).

By the way I created symfony/symfony-docs#6169 so that we remember to update the docs to reflect the new `ClassCacheCacheWarmer`.

**Comment by unexge** [comment]
@Strate you can also mark the `classes.php` as `Plain Text`(with right clicking filename). and it will be ignored.

**Comment by xabbuh** [comment]
closing here as it this is more a matter of updating the documentation (see symfony/symfony-docs#6263 for the PR)
