### ISSUE TITLE
[WebProfiler] Proxy `fetch` calls

### ISSUE THREAD

**Issue by ooflorent** [symfony/symfony#17444]
More and more JavaScript applications use `fetch` to load remote data. Currently the Web Profiler does not proxy this function and cannot hook into its calls.

I would be pleased to contribute it if such improvement would be accepted. What do you think about adding this functionality?

**Comment by stof** [comment]
this looks like a good idea.

**Comment by xabbuh** [comment]
Sounds like that could add valuable information to the WDT.

**Comment by javiereguiluz** [comment]
:+1: I would go as far as considering it a bug (or a important lacking feature) of the current profiler.

**Comment by robfrawley** [comment]
@ooflorent I'd be very interested in such functionality. If/when you have a fork you start hacking away at give me a ping; I could use this in a few projects and I should be able to carve some time out to help get it done.
