### ISSUE TITLE
Storing Symfony2 sessions in memcached but the prefix is wrong

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#17447]
Hi,

Prefix of my session handler in memcached is supposed to be `sess_` but for some reason it appears to be `session_` as you can see below. Do you guys know what the reason could be?

Thanks

Inspired from [Storing Symfony2 sessions in memcached][1]

Testing via: `http://symfony.dev/app_dev.php/`

**Memcached content**

    Server 127.0.0.1:11211
    ITEM mc[session_mifkhmgs62j4h3mp2cfl47oi94][1] [917 b; 1453303649 s]
    END
    
    Server 127.0.0.1:11211
    ITEM mc[session_5mf8qtgree00poeh81p0o2h273][1] [966 b; 1453304304 s]
    END

**parameters.yml**

    parameters:
        memcache_server: localhost
        memcache_port:   11211
        memcache_session_prefix:   sess_
        memcache_session_expire:   86400

**service.yml**

    services:
        memcached:
            class: Memcached
            calls:
                - [ addServer, [%memcache_server%, %memcache_port%] ]
    
        session.handler.memcached:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
            arguments: [ @memcached, { prefix: %memcache_session_prefix%, expiretime: %memcache_session_expire% } ]

**config.yml**

    imports:
        - { resource: parameters.yml }
        - { resource: services.yml }
    
    framework:
        session:
            name:        hello
            handler_id:  session.handler.memcached

To debug, I placed a `var_dump` in MemcachedSessionHandler.php file but it doesn't get triggered so the `test.txt` file is always empty.

    # Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php
    
    class MemcachedSessionHandler implements \SessionHandlerInterface
    {
        public function __construct(\Memcached $memcached, array $options = array())
        {
            // ....
            file_put_contents('/var/www/html/local/myproject/test.txt', var_export($options, true));
            // ....
        }
    }

  [1]: https://gist.github.com/K-Phoen/4327229

**Comment by xabbuh** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/symfony2) for support questions.

**Comment by BentCoder** [comment]
@xabbuh [I already did](http://stackoverflow.com/questions/34881174/storing-symfony2-sessions-in-memcached-but-the-prefix-is-wrong)
