### ISSUE TITLE
[Cache] ArrayAdapter in current form not safe for anything but unit tests

### ISSUE THREAD

**Issue by andrerom** [symfony/symfony#17445]
Same issue in php-cache: https://github.com/php-cache/array-adapter/issues/3
Discussion started on: https://github.com/symfony/symfony/pull/17408#discussion_r50109119

## Stale cache
In current form ArrayAdapter is not really safe for applications where cache can not be stale, where stale is defined as the data placed in cache has been updated in the backend, before cache expiry time is reached.

Scenario calls for using cache invalidation instead of relying on expiry, for more on cache invalidation:
- http://foshttpcache.readthedocs.org/en/stable/invalidation-introduction.html
 - *Note: In the case of HTTP cache, stale data to users might not be considered a critical issue, however inside an application where entities from a database is cached, stale data can have unexpected consequences on how the application behaves* 
- https://en.wikipedia.org/wiki/Cache_invalidation

By it's nature, unlike a shared cache pool like memcached, in-memory cache like ArrayAdapter with PHP is not aware of changes going on in other php process on other web requests, another php sapi, or another web server in a cluster setup. Meaning ArrayAdapter is unsafe for use with cache invalidation.

## Memory use

Current implementation also does not have any limits on cache items, meaning long running processes doing batch operations will run out of php memory.

<hr>

For possible fixes see: https://github.com/php-cache/array-adapter/issues/3

**Comment by xabbuh** [comment]
I am not sure if the issue really is a thing with the `ArrayAdapter`. I don't see why you would want to use an in-memory cache when you need to be able to invalidate cache data. But that's a thing we should keep in mind for the documentation where we can add a warning for this limitation.

For the second issue we may introduce a way to define the maximum size of the cache through the constructor (however we may want to define that limit, number of items, consumed memory, whatever).

**Comment by andrerom** [comment]
Yes, as I said in the original comment, it should imho either be documented to be only for testing, or we will need to find ways to solve those issues.

**Comment by nicolas-grekas** [comment]
This is a doc issue (to be written), nothing to change on the code side
