### ISSUE TITLE
[WebProfilerBundle] Form panel doesn't show form types anymore

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#17453]
The old form panel in the web profiler displayed the type of a form and each contained field. This information is missing from the redesigned panel.

This information is very helpful especially when types are guessed, so I think this should be added again.

**Comment by javiereguiluz** [comment]
I don't understand this bug report. Could someone please post a screenshot showing the old panel information which is now missing? Thanks!

**Comment by kucharovic** [comment]
I suppose @webmozart is missing this:
![formtypes](https://cloud.githubusercontent.com/assets/1418898/12445269/a35785e8-bf63-11e5-968a-4295aa84c94f.png)

**Comment by javiereguiluz** [comment]
But the new profiler shows the same information, right?

![form_profiler](https://cloud.githubusercontent.com/assets/73419/12445532/fba71fa0-bf64-11e5-80fd-a71aed767d3b.png)

When you put the mouse hover the type, you see the full namespace:

![ns1](https://cloud.githubusercontent.com/assets/73419/12445541/09a26d58-bf65-11e5-9592-a9779c68b393.png)

![ns2](https://cloud.githubusercontent.com/assets/73419/12445546/0dfd1c04-bf65-11e5-92b7-309e9eae66ab.png)

![ns3](https://cloud.githubusercontent.com/assets/73419/12445554/262779aa-bf65-11e5-8ae0-beaf027582c7.png)

**Comment by kucharovic** [comment]
@javiereguiluz in 3.0.2-dev I can’t see that.
![formtype](https://cloud.githubusercontent.com/assets/1418898/12447147/9670a8ae-bf6e-11e5-9de2-4578b7ad7894.png)

**Comment by javiereguiluz** [comment]
@kucharovic thanks for helping me discover the origin of this issue. I can confirm that the problem occurs only to Symfony 3.0 and higher. Hopefully it's fixed by https://github.com/symfony/symfony/pull/17455
