### ISSUE TITLE
AppVeyor build is still green after a unit test fails

### ISSUE THREAD

**Issue by paradajozsef** [symfony/symfony#17464]
[This build has a failing unit test](https://ci.appveyor.com/project/fabpot/symfony/build/1.0.5119#L702) but the result is: [Build Success](https://ci.appveyor.com/project/fabpot/symfony/build/1.0.5119#L1429)

Someone could look after why it not fails?

**Comment by javiereguiluz** [comment]
Closing it as fixed because AppVeyor is showing again a fail status when there are failed tests. Example: https://ci.appveyor.com/project/fabpot/symfony/build/1.0.5787
