### ISSUE TITLE
[Console] Render markdown valid using the Table class

### ISSUE THREAD

**Issue by tomzx** [symfony/symfony#17466]
Hi,

The `Table` helper class is very useful. It would be even better if it was possible to use it to render markdown compatible tables.

Here's the changes I think would be required to make this work.

- [ ] Add a `markdown` style
- [ ] Specify in some way that we want/do not want to render the top/bottom rows
- [ ] Do not render the row separators if those options are set to false

**Comment by javiereguiluz** [comment]
@tomzx I don't know if you are aware of them because they are not documented, but Symfony Console includes DescriptorHelpers (https://github.com/symfony/console/blob/master/Helper/DescriptorHelper.php) to tweak the output of a command for different formats (XML, Json, etc.)

Markdown is one of the descriptors available. You can see these descriptors in action for example in the commands of the FrameworkBundle (https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor).

Having said that, my guess is that we don't have to modify the current TableHelper ... but we could make those descriptors more useful (documenting them, adding utility methods, etc.)

**Comment by tomzx** [comment]
@javiereguiluz, I was aware of the `DescriptorHelpers`, but I think it is not exactly what I would want to use.  In other words, I do not really want the whole output to be formatted as markdown, only the table for example.

I would think it makes sense to make the `Table` class a little bit more powerful than to have to write some custom `DescriptorHelpers` where only the table output are tweaked.

Let me know if I'm understanding how `DescriptorHelpers` work.

Thanks!

**Comment by javiereguiluz** [comment]
@tomzx yes, you understood it well. The alternative solution would be to create your own console style inheriting from the default SymfonyStyle. There you can override the method that renders the table.

**Comment by xabbuh** [comment]
I can understand why one wants to render the console output as Markdown. Though I do not understand why one would only want to change this for tables. Imho that's a very special use case and should indeed be handled with a custom `SymfonyStyle` implementation. Thus I close here. But please feel free to provide some more information about your use case if you do not agree.

**Comment by tomzx** [comment]
@xabbuh So if I understand what you guys are suggesting, is that we created a class that inherits from `SymfonyStyle` where we replace the `table` method so that we either implement our own `Table` class which doesn't print a top/bottom row or we take the output and strip the first/last line of output? Considering we use a `StreamOutput`, that doesn't seem to be feasible (other than by using a `BufferedOutput` for instance).

By looking at the `SymfonyStyle` and the documentation (http://symfony.com/doc/current/cookbook/console/style.html), we're not making use of this wrapper (we're basically using the default `StreamOutput`). We print tables using this very simple code (simplified here):

```php
$table = new Table($output);
$table->setHeaders(['Name', 'Value']);
foreach ($i = 0; $i < 5; ++$i) {
	$table->addRow(['Title', $i]);
}
$table->render();
```

If it's not too much to ask, could you provide an example of what we'd like to do using a `SymfonyStyle`?

**Comment by inri13666** [comment]
```

**Comment by grasmash** [comment]
Bit messy, but here's a solution if you're just going for a string:
```
      $output = new BufferedOutput();
      $style = new TableStyle();
      $style->setDefaultCrossingChar('|');
      $style->setCellHeaderFormat('<info>%s</info>');

      $table = new Table($output);
      $table->setHeaders($table_contents['headers']);
      $table->setRows($table_contents['rows']);
      $table->setStyle($style);

      $table->render();
      // Remove first and last lines of the table
      // to make it valid markdown.
      $output_lines = explode("\n", $output->fetch());
      array_shift($output_lines);
      array_pop($output_lines);
      array_pop($output_lines);
      $markdown_table = implode("\n", $output_lines);
```

**Comment by amenk** [comment]
I still think it would be nice to have this built-in into Symfony console. It's useful in certain CI scenarios and would not require every one to reinvent the wheel. Can this eventually be reopened?

**Comment by fabpot** [comment]
See #59657
