### ISSUE TITLE
XSD Validation error for Dependency Injection

### ISSUE THREAD

**Issue by chippyash** [symfony/symfony#17460]
http://symfony.com/schema/dic/services/services-1.0.xsd fails validation in both PhpStorm and OxygenXml

error is (output from OxygenXml when validating the XSD file)

System ID: http://symfony.com/schema/dic/services/services-1.0.xsd
Main validation file: http://symfony.com/schema/dic/services/services-1.0.xsd
Engine name: Saxon-EE 9.5.1.7
Severity: fatal
Description: Error in complex type container: Ambiguous content model, there are two <xs:any> wildcards that match overlapping sets of namespaces
Start location: 20:0

and appears to be caused by a duplicate definition of 

```xml
<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
```
at L 27 & 31

net result is that DI container utilising an XML definition won't compile.

[edit]
Container definition will compile under most circumstances but if there is a slight error in the xml  that is not caught by the XSD, (XSD is not a perfect tool in and of itself,) then it appears that most of these parsers lose their way.  However, the invalid syntax of the XSD itself is a problem.

**Comment by xabbuh** [comment]
Looks like other online validators report the same issue too (see, for example, http://www.utilities-online.info/xsdvalidation/#.VqAFvvH1GRs). Can we replace `xsd:sequence` with something else that doesn't require a certain order of the elements being used so that we remove one of the two lines?

**Comment by xabbuh** [comment]
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns="http://symfony.com/schema/dic/services"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     targetNamespace="http://symfony.com/schema/dic/services"
     elementFormDefault="qualified">

  <!-- ... -->

  <xsd:element name="container" type="container" />

  <xsd:complexType name="container">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        The root element of a service file.
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="imports" type="imports" minOccurs="0" maxOccurs="1" />
      <xsd:element name="parameters" type="parameters" minOccurs="0" maxOccurs="1" />
      <xsd:element name="services" type="services" minOccurs="0" maxOccurs="1" />
      <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </xsd:choice>
  </xsd:complexType>

  <!-- ... -->
</xsd:schema>
```

What about something like this?

**Comment by chippyash** [comment]
@xabbuh That would probably do it. It does lose the order in which the child elements can appear and that may be important in some edge cases that I'm not aware of.

I'm seriously wondering if this is some sort of merge bug introduced when the definition was updated for a recent release.  I never had it before in quite a few years of using Symfony DIC as a standalone component.  Just a thought.

**Comment by Tobion** [comment]
This part didn't change in years indeed. So I guess it has always been invalid but working.

This SO question resembles ours pretty well: http://stackoverflow.com/questions/25178259/xsd-allow-elements-from-different-namespace-anywhere-in-a-sequence
If PHP supports XSD 1.1 we could use the open content model.

And with XSD 1.1 we could also use "conditional type assignment" to do some conditional attributes, e.g. as with #17323

**Comment by chippyash** [comment]
I can't see PHP utilising latest XML based technologies any time soon.  Been waiting for years for it to catch up - any time I need to do some serious XML stuff I off load it to something that can handle it.

So, can we just fix the existing XSD.  I'd be happy to do it if someone could point me at the right place to get code and test cases.

**Comment by javiereguiluz** [comment]
@chippyash do you think that this could be solved with the new XSD showed by @xabbuh? In case it is, this issue will be easy to solve. Thanks!

**Comment by backbone87** [comment]
@xabbuh's XSD wont work as one could provide multiple imports (because he can repeat the choice to add one or zero imports)

what would work is this:
```xml
  <xsd:complexType name="container">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        The root element of a service file.
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:group ref="foreign" />
        <xsd:element name="imports" type="imports" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:group ref="foreign" />
        <xsd:element name="parameters" type="parameters" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:group ref="foreign" />
        <xsd:element name="services" type="services" />
      </xsd:sequence>
      <xsd:group ref="foreign" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="foreign">
    <xsd:sequence>
      <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:group>
```
(i use the group just as a little macro)

**Comment by chippyash** [comment]
Chaps, as I say - happy to help but I need to know where to put code, etc.  It appears that this is a problem.  Need guidance from Symfony Central I guess ;-)

**Comment by backbone87** [comment]
i just noticed that my provided schema isnt valid in this form. the schema processor says ambiguous, but accepts the following form, which i originally had, but i liked the other ordering more.
i still dont see the ambiguity in the other form.
```xml
  <xsd:complexType name="container">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        The root element of a service file.
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:group ref="foreign" />
      <xsd:sequence minOccurs="0">
        <xsd:element name="imports" type="imports" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:element name="parameters" type="parameters" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:element name="services" type="services" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="foreign">
    <xsd:sequence>
      <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:group>
```

**Comment by backbone87** [comment]
a PR to change https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd is needed.

according to https://github.com/symfony/symfony/issues/11266 the file at http://symfony.com/schema/dic/services/services-1.0.xsd gets updated then ;)

**Comment by javiereguiluz** [comment]
@backbone87 you are right. We just need someone to make a pull request changing this file: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd  As always, create the PR for the oldest maintained branch where this error should be fixed. This is probably the 2.3 branch, but I'm not sure.

Then, we'll merge the PR and symfony.com will publish the new version in a few minutes. Thanks!

**Comment by backbone87** [comment]
ref https://github.com/symfony/symfony/issues/2122
