### ISSUE TITLE
Why is the $container argument in ContainerAwareInterface::setContainer optional?

### ISSUE THREAD

**Issue by WillBBP** [symfony/symfony#17479]
This just came up in a code review where we've overridden `setContainer`.

Why is it optional?

Why would you want to pass `null` to `setContainer`?

Perhaps it is to maintain some backwards compatibility, but if it can't be made required, perhaps the reason for allowing it to be `null` could be documented in the interface?

E.g. 
```php
/**
* Sets the Container.
*
* @param ContainerInterface|null $container A ContainerInterface instance or null
*
* @api
*/
public function setContainer(ContainerInterface $container = null);
```

**Comment by javiereguiluz** [comment]
For example, when shutting down the kernel, Symfony sets the container to `null` for bundles. See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L154

**Comment by WillBBP** [comment]
Ah, thanks.

I know this probably isn't going to change (any time soon anyway), but would it not be better to have a `clearContainer` or similarly named method to do that so that `setContainer` is only called with an actual Container?

This all came about because we overrode `setContainer` and populate some properties from the container once we've got it. Maybe there is a better more "Symfony" way for us to achieve the same result?

**Comment by javiereguiluz** [comment]
From what you said, you may use "Compiler Passes". Some info:

* [How to Work with Compiler Passes in Bundles](http://symfony.com/doc/current/cookbook/service_container/compiler_passes.html)
* [Understanding the compilation of the container](http://symfony.com/doc/current/components/dependency_injection/compilation.html)
* [Controlling when you hook into the container compiling process](http://symfony.com/doc/current/components/dependency_injection/compilation.html#controlling-the-pass-ordering)

**Comment by WillBBP** [comment]
I'm not sure about that. We're just doing this in a `Base` class for our Doctrine migrations...

```php
    public function setContainer(ContainerInterface $container = null)
    {
        $this->dm = $container->get('doctrine_phpcr.odm.document_manager');
        $this->phpcrSession = $container->get('doctrine_phpcr.default_session');
        $this->em = $container->get('doctrine.orm.entity_manager');
    }
```

Maybe we could set the container on the class, then get these services into the class properties in another method called in our `preUp` and `preDown` methods, but it would still fall over if `$container` was null so not much to be gained there.

I think it would be cool if `ContainerAwareInterface` at least had a line in the DocBlock explaining why `$container` is optional. It would have saved us asking questions during Code Review anyway.

**Comment by jameshalsall** [comment]
I don't think you should be implementing `ContainerAwareInterface` in the migration classes?

The only benefit to doing so would be if you are injecting the migrations anywhere, so you can depend on the abstraction (`ContainerAwareInterface`) rather than the concrete implementation, but in your case I doubt that would be the case.

**Comment by jakzal** [comment]
@WillBBP to me, looking at the method signature, it's clear that container parameter might be null, and any implementation should handle this case in its own way. 

There's no specific reason for this from the DependencyInjection component's perspective. Other components, like the HttpKernel, simply use this possibility. I feel no need to document why it's needed on the interface itself. If you have any specific comment in mind, please open a PR.
