### ISSUE TITLE
[DX] Simplify command testing

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17470]
### Problem

Testing commands is unnecessarily complicated. [This article](http://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input) explains how to do it:

```php
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Helper\HelperSet;
use Symfony\Component\Console\Tester\CommandTester;

// ...
public function testExecute()
{
    // ...
    $commandTester = new CommandTester($command);

    $helper = $command->getHelper('question');
    $helper->setInputStream($this->getInputStream('Test\\n'));

    $commandTester->execute(array('command' => $command->getName()));

    $this->assertEquals('/.../', $commandTester->getDisplay());
}

protected function getInputStream($input)
{
    $stream = fopen('php://memory', 'r+', false);
    fputs($stream, $input);
    rewind($stream);

    return $stream;
}
```

### Solution

Testing a command should be simple: tell me the command's name, give me the input that the user would type in and test the output. Could we translate this idea to code?

```php
use Symfony\Component\Console\Tester\CommandTester;

// ...
public function testExecute()
{
    // ...
    $command = new CommandTester('app:my-command');
    $command->setInputs(array('yes', 'Acme', 'yes'));
    $command->execute();

    $this->assertEquals('...', $command->getDisplay());
}
```

The `->setInputs()` method defines what the user would type in. Symfony adds a trailing `\n` to each input.

Thoughts, comments, better ideas? Thanks!

**Comment by sstok** [comment]
Gush I added these assertions, it makes the output less error-prone for spaces and line-wrapping, and styling (like ` ! Something something `).
https://github.com/gushphp/gush/blob/master/tests/Command/CommandTestCase.php#L29-L76

Command with message output: https://github.com/gushphp/gush/blob/master/tests/Command/PullRequest/PullRequestMergeCommandTest.php

And a table https://github.com/gushphp/gush/blob/master/tests/Command/PullRequest/PullRequestListCommandTest.php

**Comment by WouterJ** [comment]
I like the idea of improving the usage for the command tester. We might even add some build-in asserts in the command tester, like this: (I never like the idea of creating TestCase classes for special asserts)

```php
$tester = new CommandTester($app);

$tester->execute('app:my-command')
    ->assertRawOutput(['Command ran succesfully!'])
    ->assertExitCode(0);

$tester->execute('app:my-command')
    ->interact(['yes', 'Acme', 'yes'])
    ->assertRawOutput(['Command ran succesfully for "Acme"!'])
    ->assertExitCode(0);
```

**Comment by chalasr** [comment]
@WouterJ How that the `CommandTester::assertSomething()` implementation would interact with the phpunit test execution? Shouldn't we create these custom assertions by [extending phpunit] separately?

I started to work on this (make the CommandTester usage more easy).

**Comment by javiereguiluz** [comment]
@chalasr a minor comment: it's better to discuss in this issue the details instead of working on a PR. Otherwise, the PR may be rejected and your work wasted 😢

**Comment by WouterJ** [comment]
Fyi, I've made a command tester here: https://github.com/WouterJ/WouterJEloquentBundle/blob/master/tests/Command/TestCommand.php I'm happy to sent a PR for it.

**Comment by javiereguiluz** [comment]
@WouterJ could you please show how would the example displayed in the description of this issue look using your code? Thanks!

**Comment by WouterJ** [comment]
```php
public function testExecute()
{
    // ...
    TestCommand::create(new MyCommand)
        ->answering('yes')
        ->answering('Acme')
        ->answering('yes')
        ->duringExecute()
        ->outputs('...')
    ;
}
```

When passing an input option: `TestCommand::create(new MyCommand)->passing('--foo')->duringExecute()`
Asserting exit code: `TestCommand::create(new MyCommand)->execute()->exitsWith(2)`

**Comment by chalasr** [comment]
@javiereguiluz Thank's for the advice! 

I like the idea of having one ´setInputs()´ that takes an array of ordered answers (maybe ´setAnswers()´?).

@WouterJ Nice job! I would change some method names to more common names for assertions such as ´shouldOutput´ instead of ´outputs´ and ´withArgument´

**Comment by javiereguiluz** [comment]
@WouterJ thanks for providing the example. To be honest, I don't like the proposed fluent API. It looks too different from other Symfony APIs.

@chalasr I don't like the idea of `setAnswers()` either because they are not always "answers" strictly speaking. A command deals with inputs and outputs, that's why I proposed `setInputs()`. In fact, I'd like to replace the `getDisplay()` method by `getOutput()`, because again, commands just deal with inputs and outputs.

**Comment by chalasr** [comment]
@javiereguiluz The problem is that variables/methods names would create confusions between the `Output`/`Input` objects and "displayed output"/"user input".
I think that we can remove the current `getInput`/`getOutput` methods to provide higher-level methods such as done by the `getDisplay` (would become `getOutput` as you proposed).

I have a WIP: https://github.com/chalasr/symfony/blob/27887a5f9afc4c7ec150f6c588592fa0dcaed9df/src/Symfony/Component/Console/Tester/CommandTester.php

It gives:

        // ...
        $command = new CommandTester($command);
        $command->setInputs(['First input', 'Second input']);
        $command->execute([]);

        $this->assertEquals(0, $tester->getStatusCode());
        $this->assertContains('Success', $tester->getOutput(true));

What do you think?

**Comment by chalasr** [comment]
@javiereguiluz 
I'd like to have your opinion: https://github.com/chalasr/symfony/commit/2dfdefd41e6f42c28b26e03709f26c3f603ee7ab

> In fact, I'd like to replace the getDisplay() method by getOutput(), because again, commands just deal with inputs and outputs.

I think that the `getOutput()` and `getInput()` should stay to keep the Input/Output objects accessible. 
Maybe we could rename these two methods, then rename getDisplay() in getOutput()?
