### ISSUE TITLE
[Form] Using form theme in Twig with "_self" throws deprecation

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#17474]
Hey,

we've got a template which uses `_self` as the form theme in Twig as show in the cookbook:

```
{% extends 'base.html.twig' %}

{% form_theme form _self %}

{% block integer_widget %}
    <div class="integer_widget">
        {% set type = type|default('number') %}
        {{ block('form_widget_simple') }}
    </div>
{% endblock %}

{% block content %}
    {# ... render the form #}

    {{ form_row(form.age) }}
{% endblock %}
```

See: http://symfony.com/doc/current/cookbook/form/form_customization.html

At the same time the profiler shows the deprecation note

`DEPRECATED - Global variable "_self" is deprecated since version 1.21 in ? at line 3`

and I cannot find any hint on how to solve this issue. There's no upgrade guide in the UPGRADE.md or on the Twig page. :(

Cheers
Matthias

**Comment by jvasseur** [comment]
`_self` have been undeprecated (https://github.com/twigphp/Twig/issues/1932)

**Comment by althaus** [comment]
@jvasseur Oh thanks for the hint. I'll await a Twig update then. :+1:
