### ISSUE TITLE
IsNull but NotNull instead of IsNotNull

### ISSUE THREAD

**Issue by conradkleinespel** [symfony/symfony#17477]
Hello,

I am migrating a project from Symfony 2.8 to 3.0

In the process, I saw I had to change the `Null` constraint to `IsNull` for forward compatibility with PHP 7. So I thought it would be obvious to also rename `NotNull` to `IsNotNull`. But I see that `NotNull` was kept intact.

Would it make sense to change `NotNull` to `IsNotNull` for consistency ? Is there a specific reason why maybe this hasn't been done as part of #14228 ?

Thanks for your help,
Best regards

**Comment by Tobion** [comment]
Because `NotNull` is not a reserved word and we try to minimize the BC breaks. If you think it's worth to introduce `IsNotNull` as alias, feel free to make a PR. Thanks.

**Comment by conradkleinespel** [comment]
Alright @Tobion. Thanks a lot for the explanation.
