### ISSUE TITLE
Is Symfony Debug Extension compatible with PHP7?

### ISSUE THREAD

**Issue by nacc** [symfony/symfony#17515]
Hi,

I'm working on packaging up Symfony for Ubuntu and testing against PHP7, but the Debian/Ubuntu system has a special package (previously called php5-symfony-debug) built from src/Symfony/Component/Debug/Resources/ext, which does not compile against PHP7, as per the attached log.
[Symfony-build-failure.txt](https://github.com/symfony/symfony/files/102821/Symfony-build-failure.txt)

**Comment by fabpot** [comment]
No, it's not compatible with PHP 7.

**Comment by nacc** [comment]
Are there any plans to change that? I'll, for now, disable it in the Ubuntu builds I am doing.

**Comment by fabpot** [comment]
Actually, @nicolas-grekas just told me that this extension is not needed in PHP 7 as everything defined in the extension is available natively in PHP 7.

**Comment by nacc** [comment]
Great, thanks!
