### ISSUE TITLE
[DX][WebProfilerBundle] Add HTTP return code in the Ajax request list table

### ISSUE THREAD

**Issue by PeterFour** [symfony/symfony#17518]
Hi,

It would be nice to have a new column to get the HTTP return code of the AJAX request.

Sometime the request list contain one failed request and instead of having to go into the profiler it would be easier to directly have the failing one and go to the profiler entry straight away.

**Comment by mickaelandrieu** [comment]
Hi,
agree, or at least make the row red when the return code is not valid (4xx, 5xx).

This make debugging ajax calls hard because you have to open each profiler links until you find the one you are looking for.

Regards,

**Comment by PeterFour** [comment]
@mickaelandrieu Yes that would be a nice touch too (or an alternative to adding a new column), it could be done also for 3xx even if I don't really encounter those quite often in AJAX

**Comment by mickaelandrieu** [comment]
@javiereguiluz do you agree ? I can make a pull request to add a new column 'HTTP Status code'.

**Comment by Jean85** [comment]
@PeterFour 3xx in AJAX are treated transparently (as from W3C specification), so you NEVER see them: you directly see the destination page, with its HTTP response code.

**Comment by PeterFour** [comment]
@Jean85 My bad then :) That would explain why I never saw any in the profiler table
