### ISSUE TITLE
doctrine:generate:form - Could not load type "date"

### ISSUE THREAD

**Issue by dialogik** [symfony/symfony#17510]
# Issue

When creating a form type via `doctrine:generate:form` it creates a line

    ->add('birthday', 'date')

which invokes the error

    Could not load type "date"

# Fix proposal

It should create a line

    ->add('birthday', DateType::class)

while importing the `DateType`

    use Symfony\Component\Form\Extension\Core\Type\DateType;

**Comment by WouterJ** [comment]
This command does not live in the Symfony package, but in the [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle) instead. Please report this issue in that repository and close this one.

**Comment by ChubV** [comment]
Yes, and there is already PR to fix it https://github.com/sensiolabs/SensioGeneratorBundle/pull/464

**Comment by dialogik** [comment]
@WouterJ Yes sure, please excuse.
