### ISSUE TITLE
Twig render no variables on production environment [Symfony2 2.8]

### ISSUE THREAD

**Issue by hernandof** [symfony/symfony#17512]
Production environment shows all variables emtpy on twig template engine.
Dev environment works fine.

=============> Controller <==================

<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use GuzzleHttp;
class EstablishmentController extends Controller
{

    /**
     * @Route("/restaurantes/{slug}", name="restaurant")
     * @Route("/bares/{slug}",  name="bar")
     * @Route("/restaurantes-bares/{slug}",  name="restobares")
     */
    public function indexAction(Request $request)
    {
        $slug = $request->get('slug');
        $establishment = $this->getEstablishment($slug);
        
        // establishment
        if( isset($establishment)){
            $response = ['establishment' => $establishment['restaurant']];
        }else{
            // redirect
        }

        // sponsors
        if(!is_null($establishment)){
            $sponsors = $this->getSponsors($establishment);
            if(!is_null($sponsors)){
                $response['sponsors'] = $sponsors;
            }
        }

        // comments
        if(!is_null($establishment) && $establishment['restaurant']['numberOfComments'] > 0){
            $comments = $this->getComments($establishment['restaurant']['id'], 1);
            $response['comments'] = $comments;
        }
        return $this->render('AppBundle:Establishment:establishment.html.twig',$response);
    }

    /**
     * @Route("/establishments/{id}/comments/{page}", name="establishment_comments")
     */
    public function getCommentsAction(Request $request, $id, $page)
    {
        $slug = $request->get('id');
        $comments = $this->getComments($id, $page);
        return new JsonResponse($comments);
    }

    /**
     * @Route("/establishment/comment/{id}", name="establishment_comment")
     */
    public function commentAction(Request $request)
    {

    }

    private function getSponsors($establishment)
    {
        $form_params = [];
        if(isset($establishment->restaurant->idPlace)){
            $form_params['idPlace'] = $establishment->restaurant->idPlace;
        }
        if(isset($establishment->restaurant->idCuisines[0])){
            $form_params['cuisine_id'] = $establishment->restaurant->idCuisines[0];
        }
        if(isset($establishment->restaurant->priceRange)){
            $form_params['priceRange'] = $establishment->restaurant->priceRange;
        }
        $response = $this->apiCall('POST', 'api/1.0/sponsor/get' , [ 'form_params' => $form_params ]);
        return $response['sponsor'];

    }

    private function getEstablishment($slug)
    {
        $response = $this->apiCall('POST', 'api/2.0/restaurant/getBySlug' , [
                'form_params' => [
                    'slug' => $slug
                ]
            ]
        );
        return $response;
    }

    private function getComments($id, $page)
    {
        $response = $this->apiCall('POST', 'api/1.0/comments/get', [
                'form_params' => [
                    'id' => $id,
                    'page' => $page
                ]
            ]
        );
        return $response;
    }

    private function apiCall($method, $endpoint, $payload)
    {
        $apiUrl = $this->container->getParameter('api_url');
        $client = new GuzzleHttp\Client();

        try {
            $res = $client->request($method, $apiUrl.$endpoint, $payload);
            $response = json_decode($res->getBody(),1);
        } catch (Exception $e) {
            $response = $e->getMessage();
        }
        return $response;        
    }
}

==============> template <=================

			<div class="display-extended-body">
				<div><i class="icon cutlery"></i> {{ establishment.cuisines|join(', ') }} </div>
				<div><i class="glyphicon glyphicon-map-marker"></i> {{establishment.address}}, {{establishment.locality}}</div>
				<div><i class="glyphicon glyphicon-earphone"></i> {{establishment.phone_number}}</div>
			</div>

**Comment by jakzal** [comment]
Please use one of [our support channels](http://symfony.com/support) for support questions. Thanks!
