### ISSUE TITLE
Upgrade Symfony 2.0 to 2.1

### ISSUE THREAD

**Issue by Siempie93** [symfony/symfony#17546]
Good day everybody

Why does it have to be so difficult to migrate a Symfony 2.0 project to Symfony 2.1? I've left every single stone turned over looking for basic guides to help me step by step to migrate to 2.1.

The Symfony cookbook isn't of much help, as [this](https://symfony.com/doc/master/cookbook/upgrade/major_version.html) is basically the only thing for upgrading I can find on Symfony's website.

I tried to follow [this](https://github.com/lanthaler/sfHydraDemoApp/blob/master/UPGRADE.md) document but I still don't know if this is all or whatever more I have to do to complete the migration.

I just need to get to 2.1 because then things will get easier with composer.

I've started working (doing my internship) at a company and one of their projects run on Symfony 2.0 and they want me to upgrade it to 2.8 LTS, but before jumping to 2.8, I want to go through 2.1 and use the composer afterwards.

Please, I need help with clear instructions.

**Comment by javiereguiluz** [comment]
@Siempie93 the short answer is: Symfony 2.0 was the first version of the new branch and a lot of things were subject to change. 2.1 and 2.2 did a lot of changes too. Things changed in Symfony 2.3, where everything became stable and backwards incompatible changes were reduced to the minimum.

The best resource to upgrade your app is to read the `UPGRADE -2-x.md` guides published [in the Symfony repo](https://github.com/symfony/symfony/tree/2.8). For example, read [UPGRADE-2.1.md](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.1.md) to upgrade from 2.0 and 2.1.

If you have any question during the upgrade process, please use the support channels provided in http://symfony.com/support

**Comment by Siempie93** [comment]
@javiereguiluz I forgot to mention, I were at those links you have sent me as well. Are those links really the best information to follow to upgrade the project? It feels really unclear, were do I have to start?

**Comment by Tobion** [comment]
Symfony is a framework for building things yourself. There cannot be step-by-step instructions or auto-update functionality as it depends on the application that is built with it.
