### ISSUE TITLE
[Request] Avoid external XML entities

### ISSUE THREAD

**Issue by itsadok** [symfony/symfony#17562]
There's a known issue (#15124) with Symfony and hhvm, where the option `hhvm.libxml.ext_entity_whitelist` has to be set in php.ini in order for any XML processing to work.

To reproduce this issue, you can for example do:

```
composer create-project symfony/framework-standard-edition test
cd test
composer require symfony/dependency-injection
hhvm bin/console
```

While settings this option resolves the issue, it opens up a security vulnerability on the server (which is why this option is disabled by default). I have tried looking into it myself, but couldn't figure out where external entities are being used and why it's a requirement.

Is it possible to just remove this requirement, thereby allowing hhvm to work with the default parameters?

**Comment by stof** [comment]
Well, AFAICT, the only way to load an XML file on HHVM without changing this whitelist setting is to stop validating the XSD of the file (which means accepting invalid files).

**Comment by itsadok** [comment]
It looks like you can solve the problem by injecting the content of XSDs instead of linking them in the schema you create at https://github.com/symfony/symfony/blob/caae21c52ffea6ba3377c7d07b15a3c2f0a0f702/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php#L458-L491

**Comment by backbone87** [comment]
import != include in XSD, i dont think its easy, maybe even impossible, to inline the imported schemas.

**Comment by aminemat** [comment]
Any update on this folks? Issue is still present with hhvm `3.15.0`

**Comment by xabbuh** [comment]
@aminemat Would you like to give a try to the approach described in https://github.com/symfony/symfony/issues/17562#issuecomment-176054449?

**Comment by nicolas-grekas** [comment]
Closing as HHVM support has been removed from 4.0, and we're not likely to invest more time into it...
