### ISSUE TITLE
Can not read the choices from the choice list - bug

### ISSUE THREAD

**Issue by IMM0rtalis** [symfony/symfony#17575]
Hi@all

Symfony: 2.8.1

I have a form type:
```php
class MatchingFilterFormType extends AbstractType
{
    protected $languages = null;

    public function __construct($languages) {
        $this->languages = $languages;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
           [...]
            ->add('languages', 'entity', array(
                'class'=> 'EotoBundle\Model\System\Language',
                'choices' => $this->languages,
                'multiple'=> true,
                'required' => false,
                'expanded' => true,
                'choice_translation_domain' => true,
            ))
            [...]
    }
```

In the controller I create the form with:
```php
$languages = $systemService->getLanguages();
        $form = $this->createForm(new MatchingFilterFormType($languages), null, array(
            'action' => $url,
            'method' => 'POST',
        ));
```

And then I want to set the value I stored with the previous call to the form after the form creation, but before the handleRequest:
```php
$form['languages']->setData($filterArray['language']);
```
The $filterArray['language'] contains an ArrayCollection. The data I retrieved from (in the call before and stored into session)
```php
$filterArray['language'] = $form['languages']->getData();
```

At the last snipped I get the exception TransformationFailedException "Can not read the choices from the choice list.".

(Symfony\Component\Form\Extension\Core\DataMapper\CheckboxListMapper)
The problem here is the line 53:
```php
$valueMap = array_flip($this->choiceList->getValuesForChoices($choices));
```

Each choice is an object so it cant be used as key. What should I do to set all the languages from the session? Is this really a bug or do I just use it the wrong way?

Best regards,
Florian

**Comment by IMM0rtalis** [comment]
I found a workaround (or solution?): The problem is, that the entities are not persisted anymore after the loading from the session. And now the form cant handle it.

But the exception-message is confusing.

```php
  $selLanguageIds = array();
        foreach($filterArray['language'] as $selLanguage) {
            $selLanguageIds[$selLanguage->getId()] = $selLanguage->getId();
        }
        if(!empty($selLanguageIds)) {
            /* @var $systemService \EotoBundle\Service\SystemService */
            $systemService = $this->get('eoto.system_service');

            $filterArray['language'] = $systemService->getLanguageRepository()->findById($selLanguageIds);
        }
```

**Comment by xabbuh** [comment]
@IMM0rtalis Why are your entities being loaded from the session? Symfony doesn't use the session to store form values in it. And yes, when you load entites from the session (I would not recommend that), you need to do some extra work as the entity manager wouldn't treat them as managed at this stage (the `merge()` method is needed to make the entity manager aware of them again).
