### ISSUE TITLE
AccessDeniedException remains uncaught

### ISSUE THREAD

**Issue by chinmayshah24** [symfony/symfony#17573]
If i throw a new AccessDeniedException (or in normal flow if a user doesn't have access to a page), it isn't getting resolved by Twig. In fact, I get an apache 500 with "uncaught exception":

```
Uncaught exception 'Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException'
with message 'Access Denied.'
```

Symfony/Component/Security/Http/Firewall/AccessListener.php:70

```php
throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException()
```

The below resolves correctly:

```php
throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException()
```

**Comment by chinmayshah24** [comment]
Before anyone spends any time on this, this is not an issue. I was doing something incorrectly. Apologies

**Comment by mark-casey** [comment]
@chinmayshah24 Could you elaborate on what you were doing wrong so that if anyone else runs into this they may have an idea where to look? I am also currently getting a 500 when trying to throw AccessDeniedException.

Thanks!
