### ISSUE TITLE
[Form] Views of compound forms without children are not considered rendered

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#17580]
Well the title says it all.

```twig
{{ form_start(form) }}
  {{ form_errors(form) }}
  {% for subForm in form.components %}
    {{ form_row(subForm) }}
  {% else %}
    no components
  {% endif %}
{{ form_end(form) }}
```

If `form.components` is empty, it is not considered as rendered at the time `form_end` is called, causing its "container" markup to be rendered. This is especially annoying when you have expanded choices with an empty array of choices.

This is partly related to: https://github.com/symfony/symfony/issues/17579

**Comment by backbone87** [comment]
@webmozart can you review this? if my proposed behavior gets accepted, i can provide a PR for it

**Comment by webmozart** [comment]
Thank you for reporting this issue @backbone87! :)

> if my proposed behavior gets accepted

I don't find any information related to that in your description? What behavior do you propose?

**Comment by backbone87** [comment]
always consider compound forms that have no children as rendered

**Comment by webmozart** [comment]
@backbone87 This is already the case (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormView.php#L70). Your problem is that your form *contains* a child, namely "components". That child is never rendered though.

Your problem can be fixed by passing the `render_rest` option to `form_end()`:

~~~twig
{{ form_end(form, {'render_rest': false}) }}
~~~

I don't think there's anything we can fix on our side.

**Comment by backbone87** [comment]
@webmozart Its about inconsistency: using the tpl code from the OP, we observe 2 cases:

- form.components has children (the for loop gets called for each of them and output them with form_row): form_end will just close the form tag, because it considers form.components to be rendered, because form.components is compound and all children are rendered.
- form.components has no children (the for loop get not called and the else branch is executed): form_end will just close the form tag, because it considers form.components **not** to be rendered, but the condition form.components is compound and all children are rendered, still applies.

ok that description wasnt as good as i expected. ok, lets try this with another one:
the current check of `isRendered`: rendered flag is set **OR** (form has at least one child **AND** each child is rendered)
my proposed check: rendered flag is set **OR** (form is compound **AND** each child is rendered)

if form is not empty, both checks always return the same bool. but if the form is an empty compound form the my check will consider it rendered, while the current one doesnt.

**Comment by backbone87** [comment]
a similar reasoning for checking compound vs. checking number of children is given here:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L549

**Comment by backbone87** [comment]
compare this to: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormView.php#L68

my proposed change:
```php
    public function isRendered()
    {
        if ($this->rendered) {
            return true;
        }

        if (!$this->vars->compound) {
            return false;
        }

        foreach ($this->children as $child) {
            if (!$child->isRendered()) {
                return false;
            }
        }

        return $this->rendered = true;
    }
```

**Comment by webmozart** [comment]
@backbone87 Sounds reasonable. The change should only affect `form_rest()` (or `form_end()`) statements, which aren't commonly used to render rows in the first place, so the implication on existing applications should be minimal.

**Comment by backbone87** [comment]
and update on this?

**Comment by HeahDude** [comment]
>the current check of isRendered: rendered flag is set OR (form has at least one child AND each child is rendered)
>my proposed check: rendered flag is set OR (form is compound AND each child is rendered)

@backbone87 It seems that @webmozart said that it "sounds reasonable" so please open a PR :)
