### ISSUE TITLE
[HttpKernel] [DataCollector] Avoid Catchable Fatal Error: Object of class __PHP_Incomplete_Class could not be converted to string

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#17586]
While the user doesn't delete the session data or clear cache of the browser, this exception occurrs when I access to panel profile > "Request/Response" > tab "Session" > "Session Attributes" and exists a serialized object (in session) whose class doesn't exist. [Here has threw the exception](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php#L76): 
```php
//Symfony\Component\HttpKernel\DataCollector\Util\ValueExporter.php line #76
return (string) $value; //instance of __PHP_Incomplete_Class
``` 

Since in these cases [`is_object`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php#L30) will return `false`, I propose to add the following code to avoid the exception and display a readable value to the user:
```php
// Special case of object
if ($value instanceof \__PHP_Incomplete_Class) {
    $array = new \ArrayObject($value);

    return sprintf('__PHP_Incomplete_Class(%s)', $array['__PHP_Incomplete_Class_Name']);
}
```
**Result**:
## Session Attributes
|Attribute |Value 
| ---------- | ------
| name | __PHP_Incomplete_Class(AppBundle\Model\DeletedClass)

If they agree, I can create a PR to fix it.

**Comment by javiereguiluz** [comment]
I've never experienced this issue myself, but the proposal looks very reasonable. But let's wait for other's opinions before creating the pull request.

**Comment by iltar** [comment]
I've neither experienced this before but that's mainly because I don't add objects to my session whenever possible. For developing purposes, this might happen more often as classes get renamed for example. Considering this is in a data collector and shouldn't affect production envs at all, I'd say this is a nice case to catch :+1:
