### ISSUE TITLE
[HttpKernel] [PHP7] Catch \Error and handle the same way as exceptions?

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#17587]
We run Symfony2 in PHP7 and sometimes an \Error occurs that's catchable but ends up in our PHP error log:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: 
Type error: Argument 1 passed to CartBundle\Entity\Cart::setPaymentMethod() must be
of the type string, null given, called in /../Controller.php on line 310 in /../Cart.php:405
```

We use Sentry to process all our exceptions and the beauty is that it gives us stacktraces. The PHP error log does not. 

Would it be possible to support catching `\Error` and passing it to a subscriber?

**Comment by nicolas-grekas** [comment]
The issue is not catching but logging, see & vote for
https://github.com/symfony/monolog-bundle/pull/153

**Comment by ruudk** [comment]
I use Sentry to `catch` those `\Exception`s with stacktraces to be fixed later. I want the same for `\Error`s

**Comment by robfrawley** [comment]
@ruudk Your response to @nicolas-grekas leaves me to believe you have your own implementation for reporting to Sentry? Otherwise, assuming you are using the monolog sentry driver, the above linked pull request against Monolog would provide the functionality as you described.

**Comment by ruudk** [comment]
It's already fixed. Some exceptions were ignored.
