### ISSUE TITLE
[DX] [Console] `InputInterface::hasOption` is confusingly named

### ISSUE THREAD

**Issue by mcfedr** [symfony/symfony#17597]
Now you probably just want to close this, because in many ways there isn't much that can be done at this stage. 

But I find the `hasOption` method to be misleading, people often use it to check if the option has been passed on the command line, not realising that it actually checks if such an option exists.

I would like to suggest a better name, and another method that actually does what you think this one will do. But given that it would be a breaking change...

**Comment by backbone87** [comment]
Well, `hasOption` can be deprecated in favor of something like `isOptionDefined`

**Comment by mcfedr** [comment]
@backbone87 That sounds great, but I don't see it https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Input/InputInterface.php#L139

**Comment by backbone87** [comment]
Yes, ofc, my comment was about how it could be changed. But changes to interfaces are BC breaks, so i dont know, if the change is viable

**Comment by WouterJ** [comment]
So the point is `hasOption` makes much sense for the `InputDefinition`, as it checks if the definition has such an option.

For some reason, the `Input` and `InputDefinition` have got very similair public APIs, while they are doing other things. I agree that using the same names lead to problems.

**Comment by javiereguiluz** [comment]
@mcfedr I'm afraid that we can't change the behavior of this method (too many PHP projects depend on the Console component, so we can't break backwards compatibility). But I agree that this method is confusing, so I've opened #20159 to at least improve its PHPdoc.
