### ISSUE TITLE
FormType dependency injection

### ISSUE THREAD

**Issue by tamasnyulas** [symfony/symfony#17592]
In Symfony 3 there's no other way to add dependencies to form types, then defining them as services. Those who want to use the form bundle stand alone, have no chance to have some dependency injected to the type, since Symfony itself handles the instantiation inside the form factory.

I'd like to suggest to let the clients use an instance of a `FormTypeInterface` as the first parameter in the `FormFactory::create()` method (or an FQCN string as it's now) and internally don't create other instance of the type. This way whenever you need the FQCN you can have it with `get_class($formType)`, but client's still able to provide their own dependencies without registering services.

**Comment by tburschka** [comment]
Additionally i face exactly this problem testing such a form type with TypeTestCase. It is impossible, since TypeTestCase can't access the services:

http://stackoverflow.com/questions/35048898/how-to-test-a-symfony-form-type-with-constructor

A possibility to inject to the form type constructor would be great.

**Comment by Tobion** [comment]
> I'd like to suggest to let the clients use an instance of a FormTypeInterface as the first parameter in the FormFactory::create() method

This is exactly what has been removed in 3.0.

If you don't use the symfony DI container, you can just implement your own FormExtension that returns a given type for a name similar to https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php

**Comment by stof** [comment]
> If you don't use the symfony DI container, you can just implement your own FormExtension that returns a given type for a name

Or just use the existing PreloadedExtension (which is not lazy-loading the types, but might be enough for your use cases)

**Comment by tburschka** [comment]
@Tobion what's with the typeTestCase?

**Comment by tamasnyulas** [comment]
@Tobion As I know correctly the reason to remove that was to get rid of the `getName()` method: https://github.com/symfony/symfony/pull/15079
Could you explain why is it not allowed to use our own form type instance for the factory? Was it a performance problem that is caused by the misusage by it's clients? If that's the case is there a chance to have another FormFactory method similar to `create()` with FormTypeInterface as first parameter to allow the uncached form creation with the benefits of owning the instance of the type?

**Comment by Tobion** [comment]
The reasons are explained in #5321. And I don't think this will be reverted as there is no need. Again, the correct solution is already explained and just a few lines more than before.

**Comment by tburschka** [comment]
@stof @Tobion any suggestion (or solution) for the TypeTestCase not resolving for forms registered as service?

**Comment by stof** [comment]
@tamasnyulas passing a form instance directly was already discouraged in 2.x as it has a performance impact, as it replaces the type in the registry each time (and it is potentially broken in case of passing instances with different dependencies, depending of what the form type does and how the form looks like).

**Comment by tamasnyulas** [comment]
Thanks @stof, I think I got the idea now. Probably I'll need to implement and register my own `FormExtensionInterface` to solve the problem.

**Comment by stof** [comment]
@tamasnyulas when using the fullstack framework, there is no need to defined your own FormExtensionInterface. Just define these form types as services with the ``form.type`` tag, and the form extension available in the core will handle them.

**Comment by sunshinedaniel** [comment]
You could overwrite the function `getType()` of `FormIntegrationTestCase` and put you initiated Type in there:
```
protected function getTypes()
    {
        $transformer = $this->getMockBuilder(Transformer::class)->getMock();
        return [new AddressRequestType($transformer)];
    }
```
