### ISSUE TITLE
[DomCrawler] BC Break in Fix for #15398

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#17601]
From this commit my functional tests are failing: https://github.com/symfony/symfony/commit/7365bc0e848d53bd78daa2be40c66d6dcff0e98e

This is a BC break because behaviour have been changed (check the modifications in tests). 
I used to make this kind of request:

```php
$crawler = $this->client->request('GET', ''/secured/login', array(), array(), array(
    'HTTP_HOST' => $this->container->getParameter('my.host'),
));
```

So now we need to provide the full URI (with path for environment) or there is a best way to do the same as before?

**Comment by raziel057** [comment]
In fact we just need to set HTTP_HOST in server parameter before calling request:

```php
public function setUp()
{
    $this->client = static::createClient();
    $this->container = static::$kernel->getContainer();
    $this->client->setServerParameter('HTTP_HOST', $this->container->getParameter('my.host'));
}
```

But I think the BC break needs to be documented even if it was a bad behaviour before.

**Comment by jakzal** [comment]
@raziel057 have you looked at #16265?

**Comment by raziel057** [comment]
@jakzal yes I know it's a bug fix but maybe the change can be documented. I close this issue.

**Comment by jakzal** [comment]
@raziel057 please propose a PR if you think think this is something worth documenting. I might be missing something in this particular case, because bug-fixes are usually not treated as BC breaks.
