### ISSUE TITLE
Testing forms registered as service with TypeTestCase

### ISSUE THREAD

**Issue by tburschka** [symfony/symfony#17607]
Hello,

i'm currently struggle with the TypeTestCase from Symfony testing a form type with an constructor. While the offical solution registring a form as a service **works well in the application**, the same form type **don't work with TypeTestCase**. Since TypeTestCase extends from FormIntegrationTestCase and extends from \PHPUnit_Framework_TestCase instead from KernelTestCase. The FormFactory in TypeTestCase doesn't/can't look for forms registered as services and throw an error calling phpunit:

    Tests\DemoBundle\Form\Type\DemoTypeTest::testSubmitValidData
    Missing argument 1 for DemoBundle\Form\Type\DemoType::__construct(), called in /var/www/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php on line 90 and defined

In this special case i have to inject the entity manager, but i have other cases too. My only workaround is to inject the dependencies via options, but i think it's not the way it should work.

DemoType.php

```php
	[...]
	class DemoType extends AbstractType
	{
	    /**
	     * @var EntityManager
	     */
	    protected $entityManager;

	    public function __construct($entityManager)
	    {
		$this->entityManager = $entityManager;
	    }
	[...]
```

services.yml

```yaml
	app.form.type.demo:
	    class: DemoBundle\Form\Type\DemoType
	    arguments: ["@doctrine.orm.entity_manager"]
	    tags:
		- { name: form.type }
```

DemoTypeTest.php

```php
	[...]
	class DemoTypeTest extends TypeTestCase
	{

	    protected function getExtensions()
	    {
		$classMetadata = $this->getMock(ClassMetadata::class, [], [], '', false);
		/* @var ValidatorInterface|\PHPUnit_Framework_MockObject_MockObject $validator */
		$validator = $this->getMock(ValidatorInterface::class);
		$validator->method('validate')->will($this->returnValue(new ConstraintViolationList()));
		$validator->method('getMetadataFor')->will($this->returnValue($classMetadata));
		return [
		    new ValidatorExtension($validator),
		];
	    }

	    public function testSubmitValidData()
	    {
		$formData = [
		    'some' => 'data',
		];

		$form = $this->factory->create(DemoType::class);

	[..
```

**Comment by sstok** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php

You need register your type with an extension, for example use the https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/PreloadedExtension.php to register your type.

Then you can simple use the FormType class-name. The Form component first tries to load your type from the registry (pre-registered form-types) when that fails it will construct the FormType by it's class-name.

In the past you always needed to register the form-type before you could use it.
So using the old way of register a type still applies here. But instead you use the class-name now.

**Comment by WouterJ** [comment]
See also https://github.com/symfony/symfony-docs/issues/6053#issuecomment-166312124 , the docs will be udpated soon.

**Comment by javiereguiluz** [comment]
Closing it because this doesn't look like a bug and the related docs will be improved soon.
