### ISSUE TITLE
[sf3] Data collectors created too late

### ISSUE THREAD

**Issue by sanpii** [symfony/symfony#17612]
Hello,

We experiment a strange comportement with the web debug toolbar and data collectors.

Chanching sf 2.8 to 3.0 makes data collectors instanciate after the request

sf 2.8:
![sf2](https://cloud.githubusercontent.com/assets/113045/12696683/00735db4-c771-11e5-9af4-291e0da96862.png)

sf 3.0:
![sf3](https://cloud.githubusercontent.com/assets/113045/12696684/00750862-c771-11e5-901c-c186865d24f8.png)

This is a simple application for testing purpose: 
https://github.com/pomm-project/pomm-bundle/tree/sf3/tests

Do you have an idea what do we do wrong?

**Comment by chanmix51** [comment]
We do not experience the problem with the micro kernel 3.0 installing the WDT manually.

Are you using the full stack edition in the « simple application for testing purposes » ?

**Comment by sanpii** [comment]
> Are you using the full stack edition

Yes.

**Comment by stof** [comment]
IMO, this is an architecture mistake in PommBundle (making some assumption about the instantiation order of services, which is totally undefined as it can change for any new service added in the container depending on its dependencies), as I commented in https://github.com/pomm-project/pomm-bundle/issues/47#issuecomment-177897738

**Comment by sanpii** [comment]
@stof According to [the documentation](http://symfony.com/doc/current/cookbook/profiler/data_collector.html) I just tagged the data collector service.

With sf2, the `profiler` service is created during a `kernel.request` event but during a `kernel.response` with sf3.

**Comment by sanpii** [comment]
The commit [c19f91](https://github.com/symfony/symfony/commit/c19f91892ba5b8e5da8e68cf2fd5f13bbe6d4f23#diff-bdd2593c9123e09266d82fcc955ba1c8L159) remove the `onKernelRequest` listener.

**Comment by stof** [comment]
yeah, because we don't need it anymore on kernel.request. This is exactly what I mentionned earlier. PommBundle was making an assumption about when the profiler service was instantiated, because the instantiation of their data-collector was changing the configuration of the connection service. This means that until the collector service is instantiated, the connection service is not ready for profiling. This was assuming that the profiler was instantiated before any request was made with Pomm.

**Comment by javiereguiluz** [comment]
After reading @stof's comments, I don't know if there is something left to do by Symfony here.

**Comment by sanpii** [comment]
> I don't know if there is something left to do by Symfony here.

Probably, no. I tried with the doctrine bundle and I don’t have the problem.
