### ISSUE TITLE
[Translator][Idea] Using expressions in the translator

### ISSUE THREAD

**Issue by sstok** [symfony/symfony#17610]
This is a rather crazy idea I got a while back. It's somewhat related to #17158
The original issue was to allow translation strings in other translations, but this has some issues with compatibility.

So I came-up with something much more advanced and less likely to cause conflicts.

I was already planning on building this in time as a component and Bundle, but having it in the Symfony core would be a better fit (if possible).

The idea is to allow Expressions in a translator string.

Example:

```
Hello {$ user.gender == 'male' ? 'Sir' : 'Madam' $},

{$ trans('something') $}

Today date is {$ 'now'|date('d-m-Y') $}.
```

I think it's very unlikely for anyone to have this in the translator keys :smile: but it will open a whole new level of possibilities. The only main challenge is performance, caching is almost mandatory here.

We can store the translation-expression as compiled down PHP for fast execution or convert the whole translation to an expression like:

```
'Hello ' ~ (user.gender == 'male' ? 'Sir' : 'Madam') ~ ',

Today date is ' ~ (date_format('now', 'd-m-Y')) ~'.'
```

Which can be stored using the expression engines caching system.

Suggestions and comments are more then welcome :+1:

**Comment by Deltachaos** [comment]
In my opinion this is some kind of design flaw to have so much logic in a translation steing. Multiple cases can already be archived by using transchoice.

**Comment by iltar** [comment]
Transchoice is designed for a number, it also requires a different function to be called in order to render. I actually have several cases where this would solve some problems for me. I'm not sure if this is desired but I'd be happy to see something like this. Maybe it could even be incorporated into transchoice? `user.gender {male} Sir | {female} Madam | Sir/Madam`

**Comment by sstok** [comment]
@iltar that was already proposed once (#4797) and got replaced by #6009 but was never completed.
I actually looked at the IntlMessage formatter but the complexity of the syntax is not very user-friendly.

My original idea was to use Twig as translation messages (storing them as blocks), but that would be to complex for a little use-case :smile: so that's why I decided to use Expressions instead.

Yes you can pre-filter the values before passing them to translator but that will require more parameters, and if you want to allow customization (like theming) you need to change the code.

Like a said it's a crazy idea :) but in the end it will make possible to embed other translations using `{$ trans('other-string') $}` :yum: making it possible to reuse translations for other translations.

**Comment by sstok** [comment]
Closing in favor of #18314 (fingers crossed 😋 )
