### ISSUE TITLE
Composer update fails

### ISSUE THREAD

**Issue by IchHabRecht** [symfony/symfony#17623]
Currently I'm not able to install/update symfony via composer. Tried with different PHP version. Using latest composer.phar.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/security-acl 2.8.x-dev requires symfony/security-core ~2.4|~3.0.0 -> satisfiable by symfony/security[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2], symfony/security-core[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, 3.0.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v3.0.0, v3.0.0-BETA1, v3.0.1].
    - symfony/security-acl v2.8.0 requires symfony/security-core ~2.4|~3.0.0 -> satisfiable by symfony/security[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2], symfony/security-core[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev,
2.8.x-dev, 3.0.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v3.0.0, v3.0.0-BETA1, v3.0.1].
    - symfony/security-acl 3.0.x-dev requires symfony/security-core ~2.8|~3.0 -> satisfiable by symfony/security[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2], symfony/security-core[2.8.x-dev, 3.0.x-dev, 3.1.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v3.0.0, v3.0.0-BETA1, v3.0.1].
    - symfony/security-acl v3.0.0 requires symfony/security-core ~2.8|~3.0 -> satisfiable by symfony/security[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2], symfony/security-core[2.8.x-dev, 3.0.x-dev, 3.1.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v3.0.0, v3.0.0-BETA1, v3.0.1].
    - don't install symfony/security 2.4.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security 2.5.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security 2.6.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security 2.7.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security 2.8.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.0-RC1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.4.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.0-RC1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.11|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.12|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.5.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.11|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.12|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.13|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.6.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.7.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.8.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.8.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.8.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security v2.8.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 2.4.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 2.5.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 2.6.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 2.7.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 2.8.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.0-RC1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.4.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.0-RC1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.11|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.12|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.5.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.10|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.11|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.12|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.13|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.6.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.0-BETA2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.3|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.4|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.5|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.6|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.7|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.8|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.7.9|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.8.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.8.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.8.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v2.8.2|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 3.0.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v3.0.0|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v3.0.0-BETA1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core v3.0.1|remove symfony/symfony No version set (parsed as 1.0.0)
    - don't install symfony/security-core 3.1.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)
    - Installation request for symfony/symfony No version set (parsed as 1.0.0) -> satisfiable by symfony/symfony[No version set (parsed as 1.0.0)].
    - Installation request for symfony/security-acl ~2.8|~3.0 -> satisfiable by symfony/security-acl[2.8.x-dev, 3.0.x-dev, v2.8.0, v3.0.0].

Anything you can advise to do here?

**Comment by IchHabRecht** [comment]
I'm on a Windows system. Composer version

**Comment by sstok** [comment]
Can you provide the composer.json used to install? The 'parsed as' part makes me think you have an `symfony/symfony: 2.0 as 1.0` in your file.

**Comment by IchHabRecht** [comment]
I've checkout git master and rum composer update to be able to run unit tests. So you have the composer.json on your own ;-)

**Comment by sstok** [comment]
` - don't install symfony/security 2.4.x-dev|remove symfony/symfony No version set (parsed as 1.0.0)`

Strange, as you are using Windows try disabling the antivirus and run `composer clean` to remove the caches. It's possible the local catch got corrupted because of the antivirus (there are many reports about Composer doing strange things do to timeouts caused by the antivirus).

**Comment by sstok** [comment]
Nope :) here it's working fine (also before clear and after clear).

**Comment by IchHabRecht** [comment]
I did `composer clearcache` and `composer install` with still the same result.

**Comment by Ener-Getick** [comment]
Try maybe to remove your vendor folder and ``composer.lock`` and run composer again?

**Comment by IchHabRecht** [comment]
Fresh new clone. Running composer with update  --prefer-dist --prefer-lowest --prefer-stable

Still the same strange error. Not able to install/update symfony

**Comment by Tobion** [comment]
> I've checkout git master and run composer update to be able to run unit tests. So you have the composer.json on your own ;-)

Master branch of which repo?

**Comment by IchHabRecht** [comment]
This one?! Or what do you mean?

**Comment by Tobion** [comment]
You must have messed up something. In the above output it says it tries to install symfony/symfony which makes no sense as this project is symfony/symfony. It does not have itself as dependency.
Also please ask for support on the appropriate channels: http://symfony.com/support

**Comment by adrienlucas** [comment]
Hey there ! I'm commenting here because this issue is one of the few references that my search engine got about the message `Installation request for symfony/symfony No version set (parsed as 1.0.0)` occurring within a `symfony/symfony` install.
For me, the issue came from the fact that I was using a `git worktree` concurrently with a container. AFAIS, composer is trying to find the main `.git` folder, but as the path given in the `gitdir` file was absolute on my host, when using composer _in the container_, the path was not pointing to an existing directory.
**The solution has been to make the `gitdir` path relative !** Something like that :
`sed -i "s:$(pwd):..:" [your-bare-repo-path]/worktrees/[your-worktree]/gitdir` (for me, the bare repo and all the worktrees are at the same in the same directory).
then `sed -i "s:$(pwd):..:" [your-worktree-path]/.git`

I hope this helps.
