### ISSUE TITLE
How to create a second form_login to authenticate users

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#17637]
HI,

i would like to create a second form_login to authenticate my users but with the same pattern.
here is a part of my security.yml

`
firewalls:  
                   
        frontend:
            context: frontend
            pattern: ^/
            form_login:
                provider: fos_clientbundle
                csrf_provider: form.csrf_provider
                login_path : client_login
                check_path : client_check
                failure_path : null
                default_target_path : client_userprofile   
            form_login:
                provider: fos_clientbundle
                csrf_provider: form.csrf_provider
                login_path : ecommerce_front_checkout
                check_path : ecommerce_check
                failure_path : null
                default_target_path : ecommerce_front_checkout                     
            logout:       
              path : client_logout
              target : client_login
            anonymous:    true``

but it don't work!!
I searched on the web but I have not found solutions.

it would require that users can connect through the main login page and also that it may be on another page like an e-commerce page!!

I hope you can help me.
thank you very much

**Comment by xabbuh** [comment]
We do use GitHub only to track bugs and feature requests. Please use one of the [support channels](http://symfony.com/support) for your question. Thank you for understanding.
