### ISSUE TITLE
[HttpFoundation] cache Request::getClientIp and Request::isSecure

### ISSUE THREAD

**Issue by kudlatyamroth** [symfony/symfony#17643]
i think this 2 methods should cache response in self instance. so if we ask for them few times in one request, we not check trusted proxies every time

**Comment by javiereguiluz** [comment]
I have two questions about this proposal:

  * Is a common scenario to ask for the IP and `isSecure` repeatedly in the same request?
  * Is checking trusted proxies a noticeable slow process?

I ask these questions to know if we are talking about a common use case or an edge case. Thanks.

**Comment by kudlatyamroth** [comment]
in our application we ask few times about ip and few times for check if its ssl request.
about trusted proxies, i will benchmark it, tomorrow.
we have 5 addresses with 24 mask, and 10 static addresses

**Comment by kudlatyamroth** [comment]
ok, it looks like this:
without cache 100 times ask:
- client ip (0.00539s [0.065%])
- is secure (0.0045s [0.054%])

without cache 10 times:
- client ip (0.00049s)
- is secure (0.00045s)

with cache 100 times:
- client ip (0.00114s [0.013%])
- is secure (0.00032s)

with cache 10 times:
- client ip (0.00017s)
- is secure (0s)

percent in brackets is time of whole request.
so if we think about it, its not big difference, but in my opinion its worth to cache it on class base.

if you want, i can make pull request for it :)

**Comment by javiereguiluz** [comment]
@kudlatyamroth thanks for the detailed benchmarks.

Assuming that 10 checks per request is the common use case, the current code takes `0.49` milliseconds and the cached version would take `0.17` milliseconds.

Although it would be a 50% performance increase, we'd only save `0.32` milliseconds. That's why I'd say the proposed changes are not worthy.

**Comment by fabpot** [comment]
I agree with @javiereguiluz
