### ISSUE TITLE
[WebProfilerBundle] empty database icon

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#17645]
Using master branch of full stack framework when DoctrineBundle is registered, if no query is executed during the request, there is an empty block rendered without icon in the web debug toolbar.

Shouldn't it be either not displayed or displayed with icon ? What's the expected behaviour ?

![empty_db](https://cloud.githubusercontent.com/assets/10107633/12734039/63dbeaaa-c93e-11e5-9cee-069493e8e071.jpg)

**Comment by dosten** [comment]
Already fixed in https://github.com/doctrine/DoctrineBundle/pull/503 but there isn't a new release yet.

**Comment by HeahDude** [comment]
@dosten ok thanks !
