### ISSUE TITLE
[4.0][HttpFoundation] Future of the Request class

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#17640]
Just as a reminder for 4.0 to not forget https://github.com/symfony/symfony/pull/17379.

> This PR makes `Request::getMimeType()`,  `Request::getFormat()` and `Request::setFormat()` static.

@Tobion can you add to this issue the `4.0` milestone please?

**Comment by dunglas** [comment]
In 4.0 the best would be to extract all the logic from `Request` (and `Response`) to make it a true value object.

**Comment by Ener-Getick** [comment]
I agree and step by step we can even imagine one day to use the psr implementation.

**Comment by Ener-Getick** [comment]
I think we can use this issue to talk about the future of the ``Request`` in general (maybe rename this issue?).

So I see several functions to move or change:
- move ``createFromGlobals`` to a ``RequestFactory`` class (with ``setFactory`` and ``createRequestFromFactory``)
- move ``create`` to ``RequestFactory``
- change the visibility of ``initialize`` to ``private``
- see if we can replace ``duplicate`` by the functions ``with*`` of the [psr implementation](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php)
- move ``normalizeQueryString`` to something like ``QueryStringNormalizer``.
- move ``getClientIps`` and ``getClientIp`` to an ``IpResolver``
- move ``getMimeType``, ``getMimeTypes``, ``getFormat``, ``setFormat`` to a ``MimeTypeResolver`` or ``MimeTypeBag``

If I forgot something or if you don't agree with one of this point, please just tell it :-)

**Comment by stof** [comment]
@Ener-Getick the issue with using PSR is the immutability, which requires to change the whole architecture of HttpKernel (and of other parts using the Request in Symfony). Renaming some methods to ``with*`` will not make HttpFoundation implement PSR-7 (it would only create confusion by making people *think* it works the same).
So please stop bringing this argument each time a change in the Request is mentionned. It only creates confusion for people following a discussion.

**Comment by Ener-Getick** [comment]
@stof I'm not talking about making the ``Request`` immutable but I agree this change would be confusing... 
I'll remove it, let's just talk about the other propositions.

**Comment by Ener-Getick** [comment]
BTW https://github.com/symfony/symfony/issues/6406 also talks about refactoring in part the ``Request`` but that's more about the methods related to uri management.

**Comment by JHGitty** [comment]
We should think about to remove the ``get()`` function. Related discussion: https://github.com/symfony/symfony/issues/17657

**Comment by klinki** [comment]
I have another proposal.

I noticed you mentioned creating RequestFactory class. I agree, it would be great. And it would be great to have method which reads request input from php://input stream. Because right now, PHP doesn't read any data for application/json MIME type (and probably for any other, different then application/x-www-form-urlencoded).

**Comment by Ener-Getick** [comment]
@klinki I love this idea, would be amazing to have such thing in the core (we can even imagine parsing the content asynchronously).

**Comment by WouterJ** [comment]
@klinki afaik, `Request#getContent()` reads from `php://input`, right? https://github.com/symfony/http-foundation/blob/6edfe4a63b1f5c0a3d0c6190998c9089784ea883/Request.php#L1494-L1533

**Comment by acasademont** [comment]
Is this still a thing? Maybe for SF5?

**Comment by fabpot** [comment]
Closing this meta issue.
