### ISSUE TITLE
[HttpFoundation] [DX] Add has() function to Request

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#17657]
Currently you can do this:
```php
$example = $request->get('example');
```

But you are not able to do this:
```php
if($request->has('example')) {
  // ...
}
```

I think this should be added to the ``Request`` class:
```php
public function has($key)
{
   return $this->attributes->has($key) || $this->query->has($key) || $this->request->has($key);
}
```

**Comment by xabbuh** [comment]
I am :-1: on this. Using the `get()` method usually isn't a good idea as it checks one bag after another. You should rather use one of the concrete parameter bags which already offer the `has()` method.

**Comment by JHGitty** [comment]
@xabbuh In this case we should deprecate ``get()``. But if we do not deprecate it I think we should add ``has()``.

**Comment by xabbuh** [comment]
I would be fine with deprecating `get()`.

**Comment by xabbuh** [comment]
However, please note that we already discourage from using this method in its docblock:

> This method is mainly useful for libraries that want to provide some flexibility. If you don't need the flexibility in controllers, it is better to explicitly get request parameters from the appropriate public property instead (attributes, query, request).

**Comment by fabpot** [comment]
Closing as adding `has` won't be done and using `get` is already discouraged in the phpdocs.

**Comment by JHGitty** [comment]
@fabpot Shouldn't we fully deprecate it?
