### ISSUE TITLE
How to handle custom sql functions on schema update?

### ISSUE THREAD

**Issue by nathanmarcos** [symfony/symfony#17651]
Sometimes when you're looking for performance, you need to delegate some responsibilities to the database with some kind of complexity functions and triggers. I'd like to know what is the best practice to handle those custom sql functions to create/update when doctrine:schema:update command is called.

**Comment by javiereguiluz** [comment]
@nathanmarcos your question looks interesting ... but in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by nathanmarcos** [comment]
Sorry and thanks for notice @javiereguiluz.

I created the same question in [StackOverflow](http://stackoverflow.com/questions/6328535/on-delete-cascade-with-doctrine2).
