### ISSUE TITLE
[3.0][Bug][Process] Fatal error: String size overflow

### ISSUE THREAD

**Issue by havvg** [symfony/symfony#17667]
```
Fatal error: String size overflow in .../vendor/symfony/symfony/src/Symfony/Component/Process/Pipes/UnixPipes.php on line 151

Symfony\Component\Process\Process->start()
Symfony\Component\Process\Process->updateStatus()
Symfony\Component\Process\Process->readPipes()
Symfony\Component\Process\Pipes\UnixPipes->readAndWrite()
```

I set the `Process` Input to a `resource` (returned by `fopen`) which exceeds the maximum string size. I tried the same without `Process` (`fread`) which did not result in the fatal error. It seems, the whole content of the resource is getting stored somewhere.

**Comment by havvg** [comment]
I removed all additional code to get down to the bare minimum code to reproduce (happens on `2.8`, too):

```php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Process\Process;

// A file with content greater than string maximum size (example run with file >4GB).
$file = new \SplFileInfo('file_greater_string_size');

$process = new Process('cat', null, null, fopen($file->getRealPath(), 'r'), null);

// The callback can be omitted. 
// It's only present to verify something is actually happening.
$process->start(function($type, $data) use ($process) {
    echo $data;
});

while ($process->isRunning());
```

**Comment by Jean85** [comment]
I think I've encountered the same issue with the output... I launched a PHPUnit test with the Process component, and obtained a very long output (I was trying to assertEquals two entities with too much relations)

**Comment by havvg** [comment]
That's something I encountered, too; but that was easy to circumvent:

```php
$output = new FileOutput($file);
$process->start(function ($type, $data) use ($output, $process) {
    if (Process::OUT === $type) {
        $output->write($data);
    }

    $process->clearOutput();
});
while ($process->isRunning());
```

**Comment by stof** [comment]
@havvg are you using the latest version of the component ? the output is stored in a stream now, not in a string (you would still get an issue if you try to use ``getOutput`` and the full output is too big though)

**Comment by Jean85** [comment]
@stof since which version the stream is used?

**Comment by stof** [comment]
3.0.2 for the 3.0 branch (released yesterday) and dev versions for other branches (as @fabpot has not released other branches at the same time)

**Comment by havvg** [comment]
I updated to `v3.0.2` and still got the error.

**Comment by havvg** [comment]
As far as I can see, the issue are those lines: https://github.com/symfony/symfony/blob/v3.0.2/src/Symfony/Component/Process/Pipes/UnixPipes.php#L149-L152

The `while` loop reads from a large input stream, all of it and writes **all** data of the input stream into the `$data` variable, which will ultimately run into string max size, if the input stream already contains enough data (e.g. an existing file).

**Comment by romainneutron** [comment]
Hello @havvg 

With latest symfony/process@master you can execute a callback whenever the output is disabled, so you just could do (without clearing output):

```
$output = new FileOutput($file);

$process->disableOutput();
$process->start(function ($type, $data) use ($output, $process) {
    if (Process::OUT === $type) {
        $output->write($data);
    }
});

while ($process->isRunning());
```

**Comment by havvg** [comment]
@romainneutron This helps me in no way, when the **input** is too big.

**Comment by romainneutron** [comment]
Oh, I read a bit fast your report. I now get it, it's about input. I'm gonna check this

**Comment by romainneutron** [comment]
Hello @havvg 

I've submitted a patch in #18015. Could you try it and confirm me it solves your issue?

**Comment by havvg** [comment]
Just wanted to let you know @romainneutron, it's working. Thank you very much!

**Comment by nicolas-grekas** [comment]
@havvg can you please check #18066 and confirm it still works for you?

**Comment by havvg** [comment]
@nicolas-grekas works for me, too!
