### ISSUE TITLE
Varchar in Formbuilder Symfony

### ISSUE THREAD

**Issue by eses89** [symfony/symfony#17670]
Hello together,

I have enitiy class  user:
`?php
 class User {
          /**
          * @var integer
          *
          * @ORM\Column(name="id", type="integer")
          * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
          private $id;
/**
* @var string
* @ORM\Column(type="string", nullable=false)
*/
private $firstName;

/**
* @var string
* @ORM\Column(type="string", nullable=false)
*/
private $lasttName;
  /**
  * @ORM\ManyToOne(targetEntity="\Test\TravelBundle\Entity\Flight",     inversedBy="flight")
  * @ORM\JoinColumn(name="flight", referencedColumnName="flightnumber",        nullable=true)
  * @var \Test\TravelBundle\Entity\Flight
  **/
   private $flight;
......
/**
 * Set flight
 *
 * @param \Test\TravelBundle\Entity\Flight $flight
 * @return User
 */
public function setFlight(\Test\TravelBundle\Entity\Flight $flight = null)
{
    $this->flight = $flight;
    return $this;
}
/**
 * Get flight
 *
 * @return \Test\TravelBundle\Entity\Flight
 */
public function getId()
{
    return $this->flight;
}`

And the formbuilder for that is:
`public function newUser(){
            // ID
            ->add('id', 'text', array(
                'label' => 'form.labels.id',
                'translation_domain' => 'User'))

            // Firstname
            ->add('firstname', 'text', array(
                'label' => 'form.labels.firstname',
                'translation_domain' => 'User'))

          // lastName
            ->add('lastname', 'text', array(
                'label' => 'form.labels.lastname',
                'translation_domain' => 'User'))

            // Flight number
            ->add('flightNumber', 'integer', array(
                'label' => 'form.labels.flightNumber',
                'translation_domain' => 'User'))

                ))
            // Submit button
            ->add('save', 'submit', array(
                'label' => 'form.buttons.submitUser',
                'translation_domain' => 'submit'))`

The flightnumber is a column from the entity flight
`class Flight {
/**
 * @ORM\Id
 * @ORM\Column(type="string", length=8, name="flightnumber")
 */
protected $id;

/**
 *
 * @var string @ORM\Column(type="string", length=32)
 */
protected $name;

/**
 * Set id
 *
 * @param integer $id           
 * @return Flight
 */
public function setId($id) {
    $this->id = $id;
     return $this;
}
/**
 * Get id
 *
 * @return integer
 */
public function getId() {
    return $this->id;
}`

The problem is that the flightnumber is in the database varchar and on the formbuilder i have integer when i change to text it doesnt accept numbers, is it possible tp put the type as varchar

**Comment by javiereguiluz** [comment]
@eses89 in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
