### ISSUE TITLE
add Container::getByType()

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#17674]
Since AutowirePass is now part of Symfony I think the possibility to get a service by type could be provided. I think it's a pitty that the information about the service IDs is deleted after resolving. Looks like it's "just" an array of scalars.
https://github.com/symfony/dependency-injection/blob/master/Compiler/AutowirePass.php#L47

It could be stored somewhere so it can be used in Bundles for some extended autowiring capabilities or even in ContainerAware instances. As a container parameter or for example as a an argument for constructor of an implementation of a new interface (which would define something like `getByType(string $type)`) which could decorate the current container.

something like

```php
class ContainerAbleToResolveByType implements ContainerAbleToResolveByTypeInterface
{
    public function __construct(ContainerInterface $container, array $resolvedTypesFromAutowirePass)
    {
        // ...
    }

    public function getByType(string $type)
    {
        // ...
    }

    // decorated methods
}
```
What do you think?

**Comment by jakzal** [comment]
Do you have any specific use case in mind? Using a reference to a service that was autowired seems risky to me. It doesn't seem to be necessary either, as you can easily autowire the same service in multiple places.

**Comment by xabbuh** [comment]
Autowiring happens when the container is built. I do not think that it is a good idea to retain these information after the container has been compiled and dumped.

**Comment by stof** [comment]
Thus, you can have many services defined for the same type, which would then make this getter ambiguous

**Comment by maryo** [comment]
@jakzal I realy don't get how it's more risky than using autowiring at all?
I want to create a bundle for `Inject` annotation I'd like to use inside Controllers (and maybe other ContainerAwares like Fixtures) to decrease a number of service locators used in client code `$this->get() and $this->getContainer()->get()`. This feature would decrease a number of hacks used in the Bundle since I'd have to extend it without this feature and replace the original AutoWirePass.
Something very simmilar is a part of Nette Framework
https://doc.nette.org/en/2.3/di-usage#toc-passing-by-an-inject-method
OFC - constructor injection is always number one.

@xabbuh This is just the easiest solution. The information is still valid. The service IDs and types are still the same unless the container is recompiled.

@stof OFC. Symfony throws and exception in that case. That's not a problem.
https://github.com/symfony/dependency-injection/blob/b59e074952a32eac7267d74a4548d7fa24b04382/Compiler/AutowirePass.php#L231

**Comment by nicolas-grekas** [comment]
@maryo the container is not a service locator. It looks like that's how you use it here isn't it? You'd better do real dependency injection...

**Comment by maryo** [comment]
@nicolas-grekas It is not a service locator but can be used like one. Even Controller base class (I know i don't have to use it) uses service location and ContainerAware is part of Symfony... I prefer constructor injection done by Symfony container 97.123456% of the time. But there are cases where it's not possible or it's not always handy - classes extending Controller from FrameworkBundle, Console Commands, Doctrine ORM Fixtures, ...

**Comment by maryo** [comment]
I made a bundle if someone was interested
https://github.com/vaniocz/vanio-di-extra-bundle

It adds the mentioned `getByType` method and a posibility to inject services (and parameters) using Inject annotation into public properties of ContainerAwares (Controllers, ContainerAwareFixtures, ...).

**Comment by TomasVotruba** [comment]
@maryo Thank you for this feature. I really miss this simple method in Container.

It can be used for Commands, EventListeners, EventDistpachers or any actually <Some>Provider.

I use it for most of my packages when I need to have extensibility without need to change the core package.

Here in Symplify/ModularDoctrineFilters [to collect all filter services](https://github.com/Symplify/ModularDoctrineFilters/blob/d71101c4700f7a77387c8c2d24650ae451f9196e/src/DependencyInjection/Compiler/LoadFiltersCompilerPass.php#L78-L91) - those that implement `FilterInterface`.
