### ISSUE TITLE
[Validator] All validation groups are not used on embedded constraints in a collection constraint

### ISSUE THREAD

**Issue by blazarecki** [symfony/symfony#17675]
Hi,

I don't know if it's a bug but it seem that all embedded constraints of a collection constraint are not applied when using validation groups.

I think that **only the first validation group** passed to the validator is used and the other are omitted.

With the following example if `$config` is equal to `['foo' => 'a']` then with validation groups:
- `['foo', 'bar', 'baz']` we have **0** violation (`NotBlank`)
- `['baz', 'bar', 'foo']` we have **1** violation (`Lenght(min="4")`)
- `['bar', 'baz', 'foo']` we have **1** violation (`Lenght(min="2")`)

``` php
    /**
     * @Collection(
     *     fields={
     *          "foo" = {
     *              @NotBlank(groups={"foo"}),
     *              @Length(min="2", groups={"bar"}),
     *              @Length(min="4", groups={"baz"})
     *          }
     *     }
     * )
     */
    public $config;
```

Here the complete gist with the tests : https://gist.github.com/blazarecki/5dcb754be22dae4f0e53 

Any idea ?
Thanks.

**Comment by backbone87** [comment]
I think the problem is the caching of already validated contraints. So the `@Collection` gets only validated in the first group given.
Can you try:
```
    /**
     * @Collection(
     *     fields={
     *          "foo" = {
     *              @NotBlank(groups={"foo"})
     *          }
     *     }
     * )
     * @Collection(
     *     fields={
     *          "foo" = {
     *              @Length(min="2", groups={"bar"})
     *          }
     *     }
     * )
     * @Collection(
     *     fields={
     *          "foo" = {
     *              @Length(min="4", groups={"baz"})
     *          }
     *     }
     * )
     */
```

**Comment by blazarecki** [comment]
Thanks you @backbone87 it's work. :+1: 
_For information I have update the gist._

I let this issue open because it seem to be a optimisation issue.

What do you think @dunglas ?

**Comment by webmozart** [comment]
Thanks for reporting this issue! This looks like a bug to me.

Status: reviewed

**Comment by blazarecki** [comment]
I create a PR that fix the issue for collection constraint.
I'll check other composite constraints.

It seem that the bug was create in Symfony 2.6

**Comment by blazarecki** [comment]
@webmozart I fix the issue in this PR https://github.com/symfony/symfony/pull/17696

Can you look at it ?

Thank you.
