### ISSUE TITLE
[2.7] [Doctrine Bridge] Tests are failing because of not autoloaded annotations

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#17688]
Those failing tests are making really difficult to review the form component and especially entity type.

Does someone knows what's going on with this issue ?

Does this come from Doctrine ? Is there a workaround ?

**Comment by nicolas-grekas** [comment]
You need to use the local `phpunit` wrapper when running tests: `./phpunit` in the root dir,
See http://symfony.com/doc/current/contributing/code/tests.html

**Comment by HeahDude** [comment]
Ok thanks for the quick reply @nicolas-grekas :)
