### ISSUE TITLE
[3.0.2][BUG][Templating] Regression introduced in TemplateNameParser

### ISSUE THREAD

**Issue by francoispluchino** [symfony/symfony#17683]
With the commit 40035327b2a0fc8a567427308726e0ec62f22f9d, The new regex pattern at the [line 59](https://github.com/symfony/symfony/commit/40035327b2a0fc8a567427308726e0ec62f22f9d#diff-b696dd35180a8539992b7a209a0c9defL59) in `Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser::parse` confuses the letter of the Windows drive `C:\` with a name of bundle.

This bug is only on Windows Platform with Symfony version:
- `3.0.2`,
- `3.0.x-dev`,
- `2.8.x-dev, >2.8.2`

**Comment by jakzal** [comment]
@francoispluchino what kind of a template path are you talking about exactly? 

`'C:\\path\\to\\section\\name.php'` would be converted to `C:path/to/section/name.php` even with the old regex.

**Comment by francoispluchino** [comment]
Yes the path is correctly converted by
```php
$name = str_replace(':/', ':', preg_replace('#/{2,}#', '/', str_replace('\\', '/', $name)));
```

But with the new regex
```php
if (!preg_match('/^(?:([^:]*):)?(?:([^:]*):)?(.+)\.([^\.]+)\.([^\.]+)$/', $name, $matches)) {
```
the result of match is true.

This gives a TemplateReference with a bundle name `C`.

It is not the case with the old pattern.

**Comment by jakzal** [comment]
What I was saying earlier is that both regular expressions work the same with the example path I gave (both don't match). See https://3v4l.org/DlsP3

**Comment by francoispluchino** [comment]
It's not the case with:
```
$name = 'C:\\path\\to\\section\\name.html.twig';
```

**Comment by jakzal** [comment]
That's what I was after (an example). What's the outcome you expect?

**Comment by francoispluchino** [comment]
**preg_match** result: 
`0` not `1`

**matches** result:
```json
[]
```
not:

```json
[
 "C:path/to/section/name.html.twig",
 "C",
 "",
 "path/to/section/name",
 "html",
 "twig"
]
```

The problem is with the file names with many dot.

**Comment by xabbuh** [comment]
see also #17777 which contains some more information how to reproduce this issue

**Comment by jakzal** [comment]
@francoispluchino any idea why the name is normalised to `C:path/to/section/name.php`? I'm not a windows user but this seems wrong as it misses the `/` after `C:`.

**Comment by francoispluchino** [comment]
No I haven't idea, but the bug is caused by the name with more dot, not by the drive (ex. `name.html.twig`).
With the old version, the normalization already used the format with only `c:`, and it was not a problem..

**Comment by jakzal** [comment]
@francoispluchino I know that, just trying to understand why it's normalised to this form :) Thanks anyway!

**Comment by francoispluchino** [comment]
@fabpot Why the `TemplateNameParser` normalize the path without slash after the letter of Windows drive? Is it expected, or it's a bug?

`C:path/to/section/name.html.twig` and not `C/:path/to/section/name.html.twig`.

@jakzal I think it is better to focus on the end of the regex pattern, which blocks the use of file names with more dots.

**Comment by hcomnetworkers** [comment]
Template names starting with "@" are also broken (see ticket #17958). Are they also considered absolute paths, or should I reopen the other ticket?

**Comment by jakzal** [comment]
@hcomnetworkers they're not considered absolute paths, but I'm fixing them as part of #17894 (that's why it's not merged yet).
