### ISSUE TITLE
[Serializer] can't catch serialization errors

### ISSUE THREAD

**Issue by descl** [symfony/symfony#17698]
Hi, sometimes i send bad JSON to the deserialize method and I would like to be able to catch these errors.

i used this code:

```php
try {
            return $this['serializer']->deserialize($json, 'Entity\MyEntity', 'json');
        }catch(\Exception $e){
            echo 'Exception reçue : ',  $e->getMessage(), "\n";
            return null;
        }
```

but using this trycatch method does not work and always give me a **Catchable fatal error**

what's the best solution to catch this errors?

Thanks, Chris

**Comment by jakzal** [comment]
What's the invalid json you're trying to deserialize? What's the Symfony version you use?

The following code works fine for me just fine in 2.7-3.0 (the exception is caught):

```php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

$encoders = array(new XmlEncoder(), new JsonEncoder());
$normalizers = array(new ObjectNormalizer());

$serializer = new Serializer($normalizers, $encoders);

try {
    $result = $serializer->deserialize('{', 'stdClass', 'json');

    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage();
}
```

**Comment by javiereguiluz** [comment]
@descl did the example provided by @jakzal help you solve your issue? If not, could you please provide more details? Thanks!

**Comment by xabbuh** [comment]
I am closing here due to the lack of feedback.

@descl Feel free to provide more information and we can reopen the issue if it turns out to be a bug.
