### ISSUE TITLE
[Form] Deprecate Traversable support in ResizeFormListener::preSubmit()

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#17701]
Right now, `ResizeFormListener::preSubmit()` accepts both arrays and Traversables as data. This does not make much sense since data sent by the browser always comes as arrays.

Support for Traversables should be deprecated and removed in 4.0 in order to facilitate fixes like https://github.com/symfony/symfony/pull/13116.

**Comment by ybensacq** [comment]
Ok PR is done.
