### ISSUE TITLE
[Form] Time type always considered updated

### ISSUE THREAD

**Issue by teadawg** [symfony/symfony#17704]
Related to https://github.com/symfony/symfony/pull/10151

The date part of the field of the form is 1970-01-01 and the date part of the field of the data is the current date, therefore the field is considered changed and updated. The date part should be the same in both.

Temporary fix: Set date of time fields to 1970-01-01 after entity is loaded.

**Comment by jakzal** [comment]
@teadawg would you mind showing us an example, or preferably some code, with explanation what happens and what should happen instead please?

**Comment by jakzal** [comment]
Or is it precisely the same problem as #10151, but with the time type?

**Comment by teadawg** [comment]
Yes, it is precisely the same problem as #10151, but with the time type. With time type only the time is stored in the db, but in php it is handled as DateTime and the date is not always consistent.

**Comment by peterrehm** [comment]
@teadawg I would have to look into the implementation, but based on the fix in #10151 

````php
                // If the field is of type DateTime and the data is the same skip the update to
                // keep the original object hash
                if ($form->getData() instanceof \DateTime && $form->getData() == $this->propertyAccessor->getValue($data, $propertyPath)) {
                    continue;
                }
````

It should catch that as well if the TimeType is handled as php DateTime as long as the value is the same.

**Comment by peterrehm** [comment]
Okay, based in your comment in #10151 

> This fix does not work if the field type is time. The date part of the field of the form is 1970-01-01 and > the date part of the field of the data is the current date, therefore the comparison fails although the 
> time is the same. The date part should be the same in both. I'm not sure on which side this should be > changed.

This looks like it is an issue in the TimeType if it creates objects with different dates. When do the different dates occur?

**Comment by teadawg** [comment]
I'm not 100% sure when they occur. In my opinion the date of TimeType should always be the unix epoch, because no date was specified. Therefore I expect the error to occur when the data is loaded from the db.

**Comment by peterrehm** [comment]
The question is how it can be reproduced. If you would be able to fork symfony-standard and reproduce the issue, I can look into it. Looking quickly at the TimeType in Symfony and Doctrine both seem to have the approach of converting it using either `|` or `!` in `DateTime::createFromString()`.

**Comment by teadawg** [comment]
I just realized the error does not occur since doctrine dbal v2.5

**Comment by peterrehm** [comment]
Can confirm that, just checked that Doctrine DBAL added that here https://github.com/doctrine/dbal/issues/2241. So the issue can be closed here as it solely relates to doctrine.

**Comment by jakzal** [comment]
Thanks guys!
