### ISSUE TITLE
[WebProfiler] Status filter

### ISSUE THREAD

**Issue by juaruipi** [symfony/symfony#17713]
In the WebProfiler, it would be nice to have a filter by response status.

**Comment by javiereguiluz** [comment]
@juaruipi thanks for proposing an idea to improve Symfony.

The good news is that there is already a pull request about this pending to be merged: #17125  Maybe you can help us reviewing it. Thanks!

**Comment by juaruipi** [comment]
Sorry! Did check on issues but not PR. Will have a look, thanks.
