### ISSUE TITLE
Symfony3 PHP7 strange session error

### ISSUE THREAD

**Issue by csiewert** [symfony/symfony#17715]
Hi,

I'm using the new symfony3 distribution with PHP7 on Vagrant.

If I run the app, I get a strange error message:

Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/api/app/../var/sessions/dev)

What could this be?

Greetings

**Comment by Tobion** [comment]
Maybe the `/var/www/api/app/../var/sessions/dev` folder does not exist? Esp the last folder which does not seem to be part of the SE. Is the problem fixed when you create this folder with write permission?

**Comment by csiewert** [comment]
Hey Tobion. The folder is created and there is also an session file in it, but it's empty.

**Comment by Tobion** [comment]
I'm closing this because it does not seem related to symfony. I'd recommend to get help on one of the support channels that symfony or php provides. See http://symfony.com/support

**Comment by csiewert** [comment]
I switched back to PHP 5.6 and the warning is gone now.

**Comment by andrerom** [comment]
@ascbascascasmnc Are you using memcached as session handler? Seen similar issues with PHP7 and memcached. See #20807.

**Comment by hemmat** [comment]
We had the same problem, and the reason for that was that the data in Redis was more than the  "maxmemory" so redis was unable to write any more data. I could login with redis-cli but couldn't set a value, if you are habving this issue, you could login to redis using redis-cli and try to set somthing, if the redis memory is full you'll get an error.

I just can't figure out how to make redis log it when it hits the maxmemory limit.
