### ISSUE TITLE
Bug when using a date earlier to 1970 on form

### ISSUE THREAD

**Issue by ThomasMoquet** [symfony/symfony#17722]
Hi, 

I have a form with a date input : 

```php
        $builder->add('birthDate', 'date', array(
            'widget' => 'single_text',
            'attr' => array('min' => '1900-01-01',
                'max' => date('Y-m-d'))
        ));
```

When you enter a date earlier to 1970, you'll get a warning : 

> Warning: IntlDateFormatter::format(): datefmt_format: invalid PHP type for date
> Stack Trace
> in vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer.php at line 91 
> 
> ```
>             throw new TransformationFailedException('Expected a \DateTime or \DateTimeInterface.');
>         }
>         $value = $this->getIntlDateFormatter()->format($dateTime->getTimestamp());
>         if (intl_get_error_code() != 0) {
>             throw new TransformationFailedException(intl_get_error_message());
> ```

$dateTime->getTimestamp() return false on date earlier to 1970 ([see php documentation](http://php.net/manual/fr/datetime.gettimestamp.php#98374))

You must use $dateTime->format("U") rather than $dateTime->getTimestamp().

Thanks

**Comment by peterrehm** [comment]
Hrm, I can see the point and it might make sense to update the `DateTimeToLocalizedStringTransformer` but I can't reproduce the error/notice you are mentioning. If I enter a date before 1970 everything works as expected for me.

**Comment by ThomasMoquet** [comment]
Hi Peter, 
Maybe timezone can afflect the problem, I will try tomorrow. 

```
object(DateTime)[1088]
  public 'date' => string '1900-12-12 00:00:00' (length=19)
  public 'timezone_type' => int 3
  public 'timezone' => string 'Europe/Paris' (length=12)
```

**Comment by xabbuh** [comment]
@ThomasMoquet Any news here? :)

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.

@ThomasMoquet Feel free to add more information and we can consider to reopen.
