### ISSUE TITLE
Auto-generated labels are not translated while rising translation issue

### ISSUE THREAD

**Issue by Dragnucs** [symfony/symfony#17737]
Auto-generated label names, using the `humanize` filter or not, rises a missing translation warning. Yet, they can neither be detected by translation tools `translation:update` and `debug:translation`. Writing translation file manually and correctly placing it, does not solve the issue and labels are still untranslated and rising issues.

I am having this issue using Symfony 3.0.2, Twig and `bootstrap_3_layout.html.twig`.

**Current results:**
1. Auto generated labels are not detected by translation tools
2. Auto generated labels rise unsolvable translation issues

**Expected Results:**
1. Auto-generated labels should be automatically added to translation files by `translation:update` or;
2. Auto-generated labels should not rise missing translation warning

**How to reproduce:**
1. Create a simple form
2. Do not write any label attribute
3. Do not add any translation setting
4. Render the form using using `{{ form_widget(form) }}`
5. Look at the profiler and you will see a number of missing translations
6. Write your own messages.en.yml and place it correctly
7. Make sure `translation:update en AppBundle --dump-messages` detects the translations
8. Refresh and look at the profiler again to see the same missing translations

**Impractical workarounds:**
1. Add translation settings to all of your form widgets even if you don't need translation
2. Edit the form theme files and remove the `humanize` filter

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by Dragnucs** [comment]
I am already using the Symfony Standard Edition with no changes, except some additional usual bundles.

The project was created using:
```shell
$ symfony new project && cd project
$ sudo composer self-update
$ composer update --prefer-dist
```

Here is a relevant part of my config files:
```json
// composer.json
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/assetic-bundle": "^2.7",
        "symfony/ldap": "^3.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "gedmo/doctrine-extensions": "^2.4",
        "twig/extensions": "^1.3"
    }
```

```yaml
# config.yml
parameters:
    locale: en

framework:
    translator:      { fallbacks: ["%locale%"] }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"

twig:
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
```

**Comment by xabbuh** [comment]
Well, but you must have added some translation files somewhere and being able to see how they look like and where you placed them would make it easier for us to understand your issue.

**Comment by stof** [comment]
``translation:update`` only extracts part of the translations. Even when you use explicit translation keys in your form types labels, they won't be extracted as they are still used through variables in the templates.
The command is not giving you an exhaustive list of the translations.

**Comment by Dragnucs** [comment]
@xabbuh If I set up my fields like
```php
$builder
    ->add('targeted')
    ->add('mgActiveSales')
```

And use this translation file
```yaml
# either src/AppBundle/Resources/translations/messages.en.yml
# or     app/Resources/translations/messages.en.yml

targeted: Targetexcxwcwxd
mgActiveSales: 'Middle Game Active Sales'
```

The generated labels look like **Targeted** and **Mg Active Sales**.

Then if I set up my fields like
```php
$builder
    ->add('targeted')
    ->add('mgActiveSales', null, array(
        // the translator is correctly instanciated in the constructor
        'label' => $this->translator->trans('mgActiveSales')
    ))
```
Then the `mgActiveSales` gets translated to **Middle Game Active Sales** and the number of missing translations gets reduced by one.

What is bugging me is that I didn't set any translation settings in my projects, except in the `config.yml` for `FOSUserBundle` to work. I thought to my self that since Symfony is trying to get a translation for all my form fields why not use this opportunity to give them fancy names but it didn't work. I need to go in the traditional way, and explicitly tell Symfony to translate fields that it already tries to translate. Am I doing something wrong missing a point or what?

**Comment by stof** [comment]
@Dragnucs you should not use the translator in the form field. This will result in double-translating labels. Set the translation key itself as label (or disable translations for this field by setting ``translation_domain`` to false)

**Comment by Dragnucs** [comment]
@stof, of course I should not use the translator in the form field. I also should not have to disable translations in there if I didn't activate them in the first place. I've got hundreds of fields, (72 on a page), setting `translation_domain` just to remove warning somewhere it shouldn't be is not practical.

Please notice that I am not interested in translating my project, just in removing unnecessary warring for quality reasons. And setting the label doesn't help either. Shall I go an extra mile and burden my forms and project with translations?

**Comment by xabbuh** [comment]
@Dragnucs You can still use a form type component to globally set the `translation_domain` option to false.

**Comment by Dragnucs** [comment]
Ok.

**Comment by Tobion** [comment]
Or you can disable the `LoggingTranslator` in dev environment (where it is only active anyway) if you do not want those irrelevant warnings.

**Comment by Dragnucs** [comment]
I don't want symfony to think bad of me or my code, not just to shut up
about it. 

Le 10.02.2016 15:15, Tobias Schultze a écrit : 

> Or you can disable the LoggingTranslator in dev environment (where it is only active anyway) if you do not want those irrelevant warnings. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/symfony/symfony/issues/17737#issuecomment-182418992
