### ISSUE TITLE
translation:update command can only extract from the Resources/views directory

### ISSUE THREAD

**Issue by DrososTasos** [symfony/symfony#17739]
The `translation:update` command is a great way to extract translation messages and keep them up to date. It's possible to write your own extractors and add them to the chain (by tagging them with `translation.extractor`).

It would be great if the command did not restrict to the view folder (see https://github.com/symfony/framework-bundle/blob/master/Command/TranslationUpdateCommand.php#L124) so that we can make other extractions possible.

At the moment we have to hack this by creating our own extractor that replaces the '/Resources/views' in the given `$resource` variable with the desired target directory/file.

Is there any reason for this restriction? Can it be lifted? If so, perhaps we can help with the implementation?

**Comment by jakzal** [comment]
If you read the command's help it says "[the] command extracts translation strings from templates of a given bundle or the app folder". It was design for extracting messages from templates. It's hard to say what will break if we change this now. Perhaps if you sent a PR that would be simple and covered with tests, we could consider it. What's the use case anyway?

**Comment by yakobe** [comment]
A possible use case would be to update translation messages from forms (and whatever else you could build an extractor for) using the same command. This would open up a lot of possibilities. Yes, there is the JMS translation bundle, but it doesn't fit every use case.

Since this command has a generic name `translation:update` it would be nice if it was configurable to update whatever the extractors find. If the extractors should only look in the `Resources/views` folder, maybe it would be better to define that in the extractors themselves? This would preserve BC.

What do you think? If this is something that is worth considering we will investigate further. Otherwise we will stick with the hack :)

**Comment by stof** [comment]
The current API of extractors is not well suited for such use case though. this is precisely why I chose a different interface in https://github.com/Incenteev/IncenteevTranslationCheckerBundle

**Comment by andrewtch** [comment]
Huh, I've stumbled upon this issue while trying to extract messages from controllers, so I will continue here.

My offer would be to add keys like ```--php```, ```--twig``` (with --twig defaults). This will support BC with minor problems with those who use PHP templates.

These would traverse all PHP and TWIG files in app (app/Resources) or bundle scope if bundle is defined. Currently my own override in TranslationUpdateCommand contains the following lines:

```php
        if (null !== $input->getArgument('bundle')) {
            // load any messages php files
            $extractedCatalogue = new MessageCatalogue($input->getArgument('locale'));
            $io->comment('Parsing controllers and php files...');
            $extractor = $this->getContainer()->get('translation.extractor');
            $extractor->setPrefix($input->getOption('prefix'));
            $finder = new Finder();
            $finder->in($foundBundle->getPath())
                ->name('*.php');

            foreach ($finder as $path) {
                $extractor->extract($path, $extractedCatalogue);
```

which perfectly extracts controller messages from a pretty huge project.

**Comment by yakobe** [comment]
@andrewtch That's along the lines that i am thinking too. I would prefer the extractors themselves to know what file types etc they are trying to extract from. Then you dont have to add any extra arguments and you can extract (or "update" as the command suggests) from twig files and php files at the same time. What do you think?

@stof That bundle is ok, but it gives less info than the symfony built in commands. Also, it seems nicer to make the symfony command more generic and extensible than to just use a 3rd party. By the name of the command, there should be no reason why it is restricted to templates (only the description makes this apparent... and there doesn't seem to be a reason why)

**Comment by andrewtch** [comment]
@yakobe , I ended up with the thought that current approacs is fine, and if you need custom approach, you must implement your own translation infrastracture (processing javascripts, twig and php files).

**Comment by netdudes-automatic** [comment]
The current approach would be ok, if the names of the commands are improved. Otherwise it is misleading. I dont think it makes sense to reimplement the complete tranlation infrastructure when a small change would allow us to extend this.

**Comment by ebuildy** [comment]
What about accepting a list of view paths as command options? 

Or make possible to override the class easily in order to specify extra ``viewPaths``.

**Comment by yceruto** [comment]
This issue is related to https://github.com/symfony/symfony/pull/29121 too, where you'll be able to add custom view paths.
