### ISSUE TITLE
Custom Event Listener on KernelException getCode

### ISSUE THREAD

**Issue by liamsorsby** [symfony/symfony#17735]
I've been working with the GetResponseForExceptionEvent but I'm stuggling to get the http StatusCode.

Using the snippet from the docs:

```php
class ExceptionListener
{
    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        // You get the exception object from the received event
        $exception = $event->getException();
        $message = sprintf(
            'My Error says: %s with code: %s',
            $exception->getMessage(),
            $exception->getCode()
        );

        // Customize your response object to display the exception details
        $response = new Response();
        $response->setContent($message);

        // HttpExceptionInterface is a special type of exception that
        // holds status code and header details
        if ($exception instanceof HttpExceptionInterface) {
            $response->setStatusCode($exception->getStatusCode());
            $response->headers->replace($exception->getHeaders());
        } else {
            $response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        // Send the modified response object to the event
        $event->setResponse($response);
    }
}
```

$exception->getCode() always returns 0 regardless of if it is a 500 error or a 404 if the error occurs in one of the symfony bridge components.

The issue seems to be that standard symfony components all use the Debug Exceptions. However, things such as the Twig bridge use the standard php exceptions. i.e. \InvalidArgumentException().

Is there a standard way to get the error code in the eventListener as it seems that alot of the bridges don't use the standard symfony error handling.

**Comment by Jean85** [comment]
Are you assuming that the Exception code should equals the HTTP response code, right?

**Comment by liamsorsby** [comment]
@Jean85 Yes. I've looked through the Exception docs here: http://php.net/manual/en/class.exception.php which symfony exceptions extend. If the HTTP response code isn't set then it will by default return 0. Looking at Symfony component exceptions it looks as if the code has been set to the HTTP response code. However, if you take a look at the symfony bridge i.e for twig and have a look at the exceptions thrown. the status code is never passed through so it will always return 0.

**Comment by jakzal** [comment]
The exception code is not the same as the http status code. It will be set to whatever was set while creating an exception (most of the time the default - 0):

    // status code is 403
    // exception code is 1
    throw new HttpException(403, null, null, [], 1);

I just made a quick test and everything works as expected. 

> Looking at Symfony component exceptions it looks as if the code has been set to the HTTP response code. However, if you take a look at the symfony bridge i.e for twig and have a look at the exceptions thrown. the status code is never passed through so it will always return 0.

Which code exactly do you mean?

**Comment by liamsorsby** [comment]
If you use the EventListener as above and check the $exception->getCode() on a generic Page not found exception you will get 404 returned. However if you do the same thing for a route with an invalid twig path (one that doesn't exist) it will return 0 instead

**Comment by jakzal** [comment]
Please provide a more specific example of how to throw such an exception. Unless you set the exception code explicitly, it will always be set to the default value - 0. Status code is a separate thing.

**Comment by liamsorsby** [comment]
Below is a simple example to dump out the error code returned:

```php
namespace ErrorBundle\EventListener;

use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;

class ExceptionListener
{
    /**
     * @param GetResponseForExceptionEvent $event
     */
    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        $exception = $event->getException();
        print_r($exception->getCode());
    }

}
```

I registered the Listener in my services using the below:

```yaml
services:
    error.exception_listener:
        class: ErrorBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
```

If I write two seperate controllers one for a Page not found exception and one with an invalid twig exception (where the path to the twig file is incorrect):

```php
namespace TestBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class TestController extends Controller
{
    /**
     * @Route("/twig")
     */
    public function twigAction()
    {
        return $this->render("LocationDoesNotExist:Folder:test.html.twig");
    }

    /**
     * @Route("/notfound")
     */
    public function notFoundAction()
    {
        return $this->createNotFoundException();
    }
}
```

You should see that the /notfound route will dump out 404 as the code but the twigAction will return a 0. If you look into the bridge you can see that the code is never set for the error code.

If I have misunderstood this then please correct me. I'm just a little unsure as to why it's inconsistent. Especially when the page here: http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html shows that the way to get the Status Code is to use $exception->getCode(); See snippet below:

```php
// src/AppBundle/EventListener/ExceptionListener.php
namespace AppBundle\EventListener;

use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

class ExceptionListener
{
    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        // You get the exception object from the received event
        $exception = $event->getException();
        $message = sprintf(
            'My Error says: %s with code: %s',
            $exception->getMessage(),
            $exception->getCode()
        );

        // Customize your response object to display the exception details
        $response = new Response();
        $response->setContent($message);

        // HttpExceptionInterface is a special type of exception that
        // holds status code and header details
        if ($exception instanceof HttpExceptionInterface) {
            $response->setStatusCode($exception->getStatusCode());
            $response->headers->replace($exception->getHeaders());
        } else {
            $response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        // Send the modified response object to the event
        $event->setResponse($response);
    }
}
```

If you need me to elaborate please let me know.

**Comment by liamsorsby** [comment]
I have just noticed the bottom section of the snippet that I've posted below. Still a little unsure as to why the code is different with symfony errors though. However, this should resolve my issue.

```php
if ($exception instanceof HttpExceptionInterface) {
    $response->setStatusCode($exception->getStatusCode());
    $response->headers->replace($exception->getHeaders());
} else {
    $response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR);
}
```

**Comment by jakzal** [comment]
Your first example would dump `0`, not `404`. Status code is available for exceptions implementing the HttpExceptionInterface and is set on the response in your last example. If there's no status code, 500 is used. Again, exception code has nothing to do with the status code. 

 I don't think there's a bug here.

**Comment by liamsorsby** [comment]
@jakzal No I realised that after my last comment. I apologise for waisting your time with an oversight. Thank you any way.
