### ISSUE TITLE
http cache fragment optimization

### ISSUE THREAD

**Issue by jayS-de** [symfony/symfony#17752]
With commit 195c57e the http_cache fragments have been escaped to prevent code injection, when restoring the cached content. But it seems that the map is a little bit too restrictive and could be optimized by reducing scope of the escaping map

`Symfony\Component\HttpKernel\HttpCache\Esi`

```php
    private $phpEscapeMap = array(
        array('<?', '<%', '<s', '<S'),
        array('<?php echo "<?"; ?>', '<?php echo "<%"; ?>', '<?php echo "<s"; ?>', '<?php echo "<S"; ?>'),
    );
```

The ```<s``` for example also applies to ```<span>``` and it's much unlikely that an eval() could do something bad. Maybe change to ```<sc``` so it would capture script tags but other html tags would be left intact.

As the possible performance impact is really small, this is a very minor issue.

**Comment by javiereguiluz** [comment]
@nicolas-grekas do you think this proposal by @jayS-de could me merged ... or do you prefer to keep the `<s` value in the escape map? Thanks!

**Comment by nicolas-grekas** [comment]
I think it won"t provide any real value, and could only weaken security. Let's not play with this limit.

**Comment by javiereguiluz** [comment]
OK. I'm closing then as "won't fix".

@jayS-de your proposal didn't make it this time ... but there will be more chances to contribute to Symfony in the future. Thanks!
