### ISSUE TITLE
TwigBridge - Import macros in form_theme not working

### ISSUE THREAD

**Issue by IceShack** [symfony/symfony#17762]
I'm trying to import some macros into my form_theme and I always get following exception:

```
An exception has been thrown during the rendering of a template ("Notice: Undefined index: forms")
```

If I add the macros directly into the template and use "_self" it works.

Example Template

``` twig
{% import 'AppBundle:Form:macros.html.twig' as forms -%}

{% block form_widget_simple %}
    {{ forms.some_macro(form) }} {# throws exception #}
    {{ _self.some_macro(form) }} {# works as it should #}
{% endblock %}

{% macro some_macro(form) %}
    {{ form.id }}
{% endmacro %}
```

I think the problem is somewhere in the TwigBridge, but I don't really understand how it works.

Im Using following versions:
symfony/symfony                     v2.7.9 
twig/twig                           v1.24.0

**Comment by stof** [comment]
This is because the form theme does not render the whole template. It calls only a single block. So the import living outside the block is not executed. Put the import inside the block instead

**Comment by IceShack** [comment]
@stof thank you for your fast answer. Unfortunately I use quite a lot of blocks, so it would result in a very messy code.

**Comment by HeahDude** [comment]
Hi @IceShack I created a gist to solve this kind of use case. Macros can be autoloaded, see https://gist.github.com/HeahDude/f9aeb128fcac309dddc8

**Comment by IceShack** [comment]
@HeahDude Thanks for your gist

Based on that I got following solution, which for me seems more elegant.
https://gist.github.com/IceShack/cdee4c02753455e9a3c9

**Comment by HeahDude** [comment]
@IceShack definitly more clean, thanks for your feedback  :)

**Comment by HeahDude** [comment]
May you can close this issue then as @stof gave the answer and you have a workaround that suits you ;)

**Comment by IceShack** [comment]
Well, I still think this should work "out-of-the-box".

**Comment by mickaelandrieu** [comment]
Sorry to re-up this old thread, but do we have an "out-of-the-box" solution right now ?

I do not consider this issue closed  :)

**Comment by stof** [comment]
> @stof thank you for your fast answer. Unfortunately I use quite a lot of blocks, so it would result in a very messy code.

But are you using macros in all your blocks ?

**Comment by IceShack** [comment]
Well, in that project we had a generic form template with widget blocks for all simple form types and one form template extending that for form types which where basically groups of simple form types. In that second template every widget block used macros for row layouts (multiple fields in one row, etc.). Using just blocks and no macros would have made the code quite messy (for example: more "set" tags)

**Comment by xabbuh** [comment]
I am closing this old issue as it seems nobody is interested in making it happen.
