### ISSUE TITLE
[2.8|3.0][bug][filesystem] IOException from JMSDiExtraBundle::FastDirectoriesResource

### ISSUE THREAD

**Issue by matthbull** [symfony/symfony#17779]
-PHP-7.0.2
-Symfony-2.8.2
-jms/di-extra-bundle v1.6.0
> 
CRITICAL
15:47:26
request	Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/data/www/mysite.dev/app/Resources/bin/backup_data/": The class "JMS\DiExtraBundle\Config\FastDirectoriesResource" is performing resource checking through ResourceInterface::isFresh(), which is deprecated since 2.8 and will be removed in 3.0." at /data/www/mysite.dev/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 100
Context: { "exception": "Object(Symfony\\Component\\Filesystem\\Exception\\IOException)" }

triggered from this code:

```php
 /** @var Filesystem $this->fs */
if ( !$this->fs->exists( $this->bk_path ) ) {
        $this->fs->mkdir( $this->bk_path );
    }
```

I'm not really sure whether this needs reporting on the DiExtraBundle repo or here as FileSystem is mentioned in the error.  Also, it seems odd that the framework should critically fail on a deprecation warning on 2.8.

**Comment by javiereguiluz** [comment]
@matthbull the first part of the error message seems related to a permission issue that prevents to create a directory. The other part is about a deprecated usage made by JMSDiExtraBundle.

For the first error, check permissions and if it doesn't work, please ask for help using these alternatives: https://symfony.com/support. For the second error, please create an issue in the bundle repository. Thanks!
