### ISSUE TITLE
Allow to define Enum nodes with one element

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17774]
In #15433 we partially solved this limitation. But, [as reported](https://github.com/symfony/symfony/pull/15433#issuecomment-183228331) by @ogizanagi, we also need to change EnumNodeDefinition: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Builder/EnumNodeDefinition.php#L34-L36

**Comment by odisleysi** [comment]
Can anyone tell me, from which version was the problem solved?

**Comment by javiereguiluz** [comment]
This issue was fixed with this merge: https://github.com/symfony/symfony/commit/4688f99ea10d6c383c2eeca5b80f838e8ab89e87 so it's available since 2.8.

**Comment by odisleysi** [comment]
I have a project in version 2.8.22 and the query returns a single object, it seems that the object whit a dump() in the controller is in there, but in the twig does not appear.

**Comment by stof** [comment]
@odisleysi there is nothing related to Twig in this PR, so either we miss a lot of context about your project, or your issue has nothing to do with this one (and so it is the wrong place to discuss it).

**Comment by odisleysi** [comment]
ok, thanks for the help.
