### ISSUE TITLE
improve KernelTestCase for MicroKernels

### ISSUE THREAD

**Issue by wodka** [symfony/symfony#17778]
right now KernelTestCase will always use the first "*Kernel.php" file.

With the addition of MicroKernels there might be multiple:

- AdminKernel.php
- ApiKernel.php
- AppKernel.php

it would be great to be able to override the search to a different Logic https://github.com/symfony/symfony/blob/582f4753a343f230fbe18b4e9a0747d48351ddfb/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L118

```php
class KernelTestCase
{
    protected static function getKernelName()
    {
        return '*Kernel.php';
    }
    
    protected static function getKernelClass()
    {
       /* ... */
       $finder->name(self::getKernelName())->depth(0)->in($dir);
       /* ... */
    }
```

this way the kernel can be overwritten inside of a WebTestCase:

```php
class ApiTestCase extends WebTestCase
{
    protected static function getKernelName()
    {
        return 'ApiKernel.php';
    }
    /* ... */
}

**Comment by stof** [comment]
``getKernelClass`` is precisely the extension for that. Overwrite for your need. You just need to return the class name (and as of the Symfony 2.8 standard-edition, the kernel is autoloadable with Composer, making it very easy to return a class name only as you don't need to require the file)

**Comment by wodka** [comment]
I tried to return the classname but it always failed.

```php
protected static function getKernelClass()
{
    return "ApiKernel";
}
```

does not work for app/ApiKernel.php

**Comment by javiereguiluz** [comment]
@wodka have you tried returning the fully qualified class name?

**Comment by wodka** [comment]
this is the fully qualified name :(

ApiKernel File:
```php
<?php

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel;

class ApiKernel extends Kernel
{
    use MicroKernelTrait;
// ...
```

composer.json has the following autoload config:
```json
	"autoload":{
		"psr-0":{
			"":												"src/"
		}
	},
```

I just checked the composer json of symfony-standard: 
```json
"classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
```
<< shouldn't this include app/*Kernel.php to autoload all kernels?

**Comment by xabbuh** [comment]
The Symfony Standard Edition only comes with one application kernel. Thus there is no need to add such a generic rule for all Symfony applications. But of course you can easily make that change in your application if you have more than one kernel.

**Comment by wodka** [comment]
the problem is that getKernelClass() also does a require on the kernel itself. But it is only using the first *Kernel.php file in app/

If an app has multiple microkernels (as far as I understand they have been created for exactly this reason) it tricky to create a WebTestCase.

to be able to use your own kernel you have to override getKernelClass()

```php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Finder\Finder;

abstract class MicrokernelWebTestCase extends WebTestCase
{
    /**
     * @return mixed
     */
    protected static function getKernelName()
    {
        return 'AppKernel.php';
    }

    /**
     * Attempts to guess the kernel location.
     *
     * When the Kernel is located, the file is required.
     *
     * @return string The Kernel class name
     *
     * @throws \RuntimeException
     */
    protected static function getKernelClass()
    {
        if (isset($_SERVER['KERNEL_DIR'])) {
            $dir = $_SERVER['KERNEL_DIR'];

            if (!is_dir($dir)) {
                $phpUnitDir = static::getPhpUnitXmlDir();
                if (is_dir("$phpUnitDir/$dir")) {
                    $dir = "$phpUnitDir/$dir";
                }
            }
        } else {
            $dir = static::getPhpUnitXmlDir();
        }

        $finder = new Finder();
        $finder->name(static::getKernelName())->depth(0)->in($dir);
        $results = iterator_to_array($finder);
        if (!count($results)) {
            throw new \RuntimeException('Either set KERNEL_DIR in your phpunit.xml according to https://symfony.com/doc/current/book/testing.html#your-first-functional-test or override the WebTestCase::createKernel() method.');
        }

        $file = current($results);
        $class = $file->getBasename('.php');

        require_once $file;

        return $class;
    }
}
```

with this modification it is possible to use different kernels - else it is not possible.

**Comment by stof** [comment]
> the problem is that getKernelClass() also does a require on the kernel itself. But it is only using the first *Kernel.php file in app/

The main reason it does such require_once is because the kernel was not autoloadable in the projects created before Symfony 2.8. As we use autoloading for the kernel now, we will probably simplify this logic a lot in the future.

When you have multiple kernels, the right way is to make them autoloadable, as done for AppKernel and AppCache as of 2.8

**Comment by jakzal** [comment]
@wodka this is what stof's talking about: https://github.com/symfony/symfony-standard/blob/c54fcb038ec23515d408aaf6f605aff61f0d41e5/composer.json#L8

**Comment by stof** [comment]
@jakzal he mentionned this line himself previously in the discussion :smile:

**Comment by jakzal** [comment]
Nevermind me than! :)

**Comment by wodka** [comment]
oki, adding it there works just as described!

for reference if someone else needs it - add all Kernels to the ClassMap:
```json
"autoload":{
    "psr-0":{
        "": "src/"
    },
    "classmap": ["app/ApiKernel.php","app/AppKernel.php","app/AppCache.php"]
}
```

now simply override getKernelClass
```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MyTestCase extends WebTestCase
{
    /**
     * @return mixed
     */
    protected static function getKernelClass()
    {
        return 'ApiKernel';
    }
}
```

it would be nice to note that somewhere in the documentation

**Comment by xabbuh** [comment]
Can you open an issue on the docs repo? I am closing here as there does not seem to be anything to do in the code.
