### ISSUE TITLE
Symfony 3.0.2 - Kernel locateResource method

### ISSUE THREAD

**Issue by shadz3rg** [symfony/symfony#17788]
Symfony\Component\HttpKernel\Kernel::locateResource method with given string  "@AppBundle/Resources/changelog.xml" is searching file in /src/AppBundle which is misleading since Resources folder now in /app/Resources
Is it a bug or feature? What should i use instead?

**Comment by javiereguiluz** [comment]
@shadz3rg in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

---

In any case, the answer to your question is probably: use the `kernel.root_dir` container parameter, which in most cases corresponds to `app/` directory: `$this->getParameter('kernel.root_dir').'/Resources/changelog.xml`'
