### ISSUE TITLE
A possibility to set autowiring types of thirdparty services.

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#17783]
I'm missing a possibility to set autowiring types of thirdparty (or framework) services.
I could imagine if one could set it using a service alias but not sure it's a good idea. Maybe there are better ways. It is probably already possible to set the autowiring type in a custom CompilerPass so maybe it's not a good idea at all. This would allow to do it in a configuration file.

Something like
```xml
<service id="app.annotation_reader" alias="annotation_reader">
    <autowiring-type>Doctrine\Common\Annotations\Reader</autowiring-type>
</service>
```

Use case is probably obvious. One could use it in case PRs like https://github.com/symfony/symfony/pull/17782/files were rejected

**Comment by weaverryan** [comment]
I've envisioned a configuration like this for end-users:

```yml
# app/config/services.yml
autowiring:
    'Doctrine\Common\Annotations\Reader': 'annotation_reader'
```

It seems to me that *not* being able to "take control" of exactly which service an interface/class should autowire to is a big missing feature. There are several services that I still can't autowire. wdyt @dunglas?

**Comment by weaverryan** [comment]
Actually, there's a much easier solution to implement. Just use a special parameter:

```yml
# app/config/services.yml
parameters:
    autowiring.types:
        'Doctrine\Common\Annotations\Reader': 'annotation_reader'
```

This could work because *only* the end-user should be specifying autowiring types in this way. So, it's ok that this must be specified all in one place. My other proposal would require a lot of work.

**Comment by dunglas** [comment]
@weaverryan in your last proposal, you think about a "special" parameter parsed by the `AutowirePass`?

Your first proposal looks better but, indeed, it requires a some work in all parsers.

**Comment by weaverryan** [comment]
@dunglas exactly right - a "special" parameter. There is no precedent for using parameters like this in Symfony, but Drupal uses this extensively. The big question is whether or not using a magic parameter like this could cause problem later if we need to break BC. But in this case... I don't think so: we'll be reading this parameter in AutowirePass, so if we deprecate it or change its format, we can throw the deprecation warning there.

**Comment by weaverryan** [comment]
For now, we'll allow users to use this workaround: https://github.com/symfony/symfony/pull/18040#issuecomment-199573489, which works immediately.

Thanks!

**Comment by TomasVotruba** [comment]
I needed this feature to be simple, so I created this bundle: https://github.com/Symplify/DefaultAutowire#multiple-service-of-one-type-set-preferred-one
