### ISSUE TITLE
[Form] NotBlank constraint on edit

### ISSUE THREAD

**Issue by matteomoretti** [symfony/symfony#17796]
I noticed that issue https://github.com/symfony/symfony/issues/17180 and I'm in a comparable situation.
I'm trying to setting a `null` value instead of an entity (this time is not a collection as shown in the issue I've linked) and I would like validation to be triggered.
I don't want to rely on client-side validation with HTML5 onto my forms, so, in development env. I use to turn off this kind of validation.
Now I have the following entity

``` php
class Foo
 {
      /**
       * @Assert\NotBlank
       */
      private $bar;

      // other properties, setters, getters
 }
```

and its form type

``` php
    class FooType extends AbstractType
    {
      $builder
        ->add('bar', EntityType::class, [
          'required' => true, // Turned off in dev. env.
          'class' => 'VendorBundle:Bar',
        ]);
    }
```

If I'm in a brand new object situation (i.e.: `newAction`) the validation is triggered as the following if statement will never be true

``` php
    // If the data is identical to the value in $data, we are
    // dealing with a reference
    if (!is_object($data) || !$config->getByReference() || $form->getData() !== $this->propertyAccessor->getValue($data, $propertyPath)) {
        $this->propertyAccessor->setValue($data, $propertyPath, $form->getData());
    }
```

while when I'm in update situation, the last "branch" of if statement 

``` php
$form->getData() !== $this->propertyAccessor->getValue($data, $propertyPath)
```

is true as I'm setting a different data (`null`) where before was an entity.
I know this issue involves two different concepts (one about validation provided by symfony and the other that is related to PHP type hinting) but, to me, that situation should be taken into account.

What are your thoughts?

**Comment by CruzyCruz** [comment]
@matteomoretti 

I have the same problem (or question) than you. I have explained my problem [here](http://stackoverflow.com/questions/37444420/symfony2-embedded-form-validation-is-not-triggered-when-editing).

Did you find any acceptable solution ?

**Comment by xabbuh** [comment]
see #28485 for an explanation of this behaviour which is expected
