### ISSUE TITLE
PHP complains about Symfony\Component\HttpKernel\Event\callable

### ISSUE THREAD

**Issue by paul-m** [symfony/symfony#17794]
In circumstances I can't recreate locally, I get the following error with symfony 3.0.2 plus silex 1.3.5 (as a RESTful front-end for Drupal 7).

Works fine locally, dies a firey death on Pantheon hosting. The same code works with symfony 2.8.* and silex 1.2.*.

```
Argument 2 passed to Symfony\Component\HttpKernel\Event\FilterControllerEvent::__construct() must be an instance of Symfony\Component\HttpKernel\Event\callable, array given, called in [..]/vendor/symfony/http-kernel/HttpKernel.php on line 131 and defined', '[..]/vendor/symfony/http-kernel/Event/FilterControllerEvent.php', '35', array('kernel' => object(HttpKernel)
```

The method signature in question looks like this:

```
namespace Symfony\Component\HttpKernel\Event;
[..]
class FilterControllerEvent extends KernelEvent
[..]
    public function __construct(HttpKernelInterface $kernel, callable $controller, Request $request, $requestType)
```

So. Should this say `\callable`?

**Comment by Taluu** [comment]
What is your version of php ? `callable` is a php 5.4 feature...

**Comment by Tobion** [comment]
Looks like a php version error.

**Comment by paul-m** [comment]
Ugh. Yes, it is a version problem. Build phase lied to me.

Thanks, folks.
