### ISSUE TITLE
[3.0.2]problem with buildForm (formtype)

### ISSUE THREAD

**Issue by alex1442** [symfony/symfony#17791]
in ChoiceType::class
if expanded set to `true` then
parameter 'empty_data'  ignored ,

validator return error not null for this value

a similar problem https://github.com/symfony/symfony/issues/17789
sf 3.0.2

**Comment by xabbuh** [comment]
Can you explain your issues a bit more and how it is even different from the referenced issue? The best would be to form the Symfony Standard Edition and make the changes needed to reproduce it.

**Comment by alex1442** [comment]
in _ChoiceType::class_, if  _expanded_ ===true ,validator return error : 
   This value should not be blank.
  This value should not be null., 
but _empty_value_ is defined.
```

`class SearchMediaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $data = [ 'size' => 'thumbnail'];/ /defalt values
        $builder->setMethod('GET')
            ->add('tagName',  SearchType::class)
            ->add('size', ChoiceType::class, [
                'choices' => array('thumbnail' => 'thumbnail',
                'low_resolution' => 'low_resolution',
                'standard_resolution' => 'standard_resolution',
                ),
                'choices_as_values' => true,
                'multiple' => false,
                'expanded'=> TRUE,
                'empty_data' => $data['size']
                ]
            );
```
Size valus asserts:
  ```
//searchmediaentity.php
  /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Choice({"thumbnail", "low_resolution", "standard_resolution"})
     */
    protected $size;
```
if expanded ===false then all right

**Comment by HeahDude** [comment]
Bug confirmed in 2.7, anytime `expanded` is `true`, either `multiple` is `true` or not.

I've found a fix in `ChoiceType` add this line 95 :

```php
if (FormUtil::isEmpty($data)) {
    $data = $form->getConfig()->getEmptyData();
}
```

Status: reviewed

**Comment by HeahDude** [comment]
This issue comes from `RadioListMapper` and `CheckboxListMapper` IMHO, as they reset submitted data after `Form::submit()` has used `empty_data`.

I don't if we can fix them without the "hack" above in the `Forms::PRE_SUBMIT` event when `expanded` is true.

**Comment by HeahDude** [comment]
Beware if you set `empty_data` as a callable you should use this code instead from [line 93 of `ChoiceType`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L92) :
```php
$builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $form = $event->getForm();
    $data = $event->getData();

    if (FormUtil::isEmpty($data)) {
        $emptyData = $form->getConfig()->getEmptyData();
        if (is_callable($emptyData)) {
            $emptyData = call_user_func($emptyData, $form, $data);
        }
        $data = (string) $emptyData;
}
```

**Comment by HeahDude** [comment]
See #17822 for a cleaner fix.
