### ISSUE TITLE
[HttpFoundation] [Session] Unnecessary PHP version check

### ISSUE THREAD

**Issue by calinpristavu** [symfony/symfony#17805]
As the minimum required PHP version has been bumped to 5.5.9, there is a redundant check in the `NativeSessionStorage::regenerate` method for version 5.4.0:
[NativeSessionStorage::regenerate#L185-L192](https://github.com/calinpristavu/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L185-L192)

I started working on a deprecation PR for `2.8` and a fix pr for `master` but I don't really know if we still add deprecations to `2.8`.

Please let me know if it's worth proposing PRs for this.

**Comment by nicolas-grekas** [comment]
please open a PR on 3.0 to remove the dead code,
we don't add any deprecation to 2.8

**Comment by calinpristavu** [comment]
Submitted PR + changed description to comply with fabbot

**Comment by stof** [comment]
Thus, there is nothing to deprecate in 2.8 in this case. The fact that we don't need the version check in 3.x thanks to our version requirement does not imply this is deprecated in 2.8
