### ISSUE TITLE
Upgrade-2.8.md and sensio/distribution-bundle

### ISSUE THREAD

**Issue by spdionis** [symfony/symfony#17803]
Currently there is no mention in the upgrade path about changes made to `app/console` file. Apparently there were changes in `bootstrap.php.cache` generation too.

While upgrading to symfony 2.8 I also upgraded `sensio/distribution-bundle` to version `~5.0` because I noticed that was the version generated when a fresh symfony 2.8 project was created. Apparently though  the autoloader doesn't loaded properly in `app/console` and `composer update` fails on post update scripts because it couldn't load `ArgvInput`.

I tried to change:

```php
require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';
```

to 

```php
/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require __DIR__.'/autoload.php';
```

as per the default file in symfony 2.8 but now it wouldn't find `AppKernel`. It's fixed by requiring the AppKernel file too.

The whole issue is weird tho and there's no mention of this in any documentation as far as i can see.

EDIT: I was updating from symfony 2.7

EDIT2: similiar issues for `app_dev.php` and `app.php`

EDIT3: also needed to change the bootstrap file in phpunit.xml

**Comment by eXtreme** [comment]
Well, this is not a correct repository to report this. It is also reported there: https://github.com/sensiolabs/SensioDistributionBundle/pull/255
Also, take look at upgrade notes for symfony standard:
https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md

**Comment by javiereguiluz** [comment]
@spdionis thanks for reporting this issue. However, as @eXtreme said, we probably need to fix it in another repository (to be exact, in https://github.com/sensiolabs/SensioDistributionBundle/pull/255). That's why I'm closing this issue.

**Comment by spdionis** [comment]
Thank you for the directions
