### ISSUE TITLE
Validating email problem with SwiftMailer

### ISSUE THREAD

**Issue by bordeux** [symfony/symfony#17802]
Hi guys! I have a problem with email validator. So here is example:
![example](http://i.imgur.com/KsTt7zB.png)

Result in var_dump is 0 = 0 errors. Wtf?!

So ok, meybe this email is correct. But when im creating swift email object o got a exception:

![example](http://i.imgur.com/0fIIUlX.png)

So: strict flag on email object is invalid. :)

**Comment by xabbuh** [comment]
Using UTF-8 characters in the local part is totally valid. To avoid issues when using Swiftmailer, you can use the development version of the upcoming 6th version of Swiftmailer (see swiftmailer/swiftmailer#403, swiftmailer/swiftmailer#409, egulias/EmailValidator#42).
