### ISSUE TITLE
[Session] question + information/documentation

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#17806]
Hi,

I just want to know, as I did not find any doc, why the `session_fixation_strategy` is by default `migrate`? (symfony 2.8)
Is it due to security issues? Or anything else?

As well, it could be cool if we can find a little doc on the block

```
# strategy can be: none, migrate, invalidate
session_fixation_strategy:  migrate
```

in http://symfony.com/doc/current/reference/configuration/security.html

Many thanks :)

**Comment by jakzal** [comment]
It's hard to tell why the person who implemented this chose it as a default as it was quite a while ago ;) (see https://github.com/symfony/symfony/commit/57ae50e8942f1a3ee9431c320b404fc1b016b87c where the session strategy was introduced). 

It's up to you to choose the right fixation strategy for your application. I think "migrate" is a good default for the framework as the session id is regenerated (so it's more secure than "none" strategy), but session attributes are kept. Clearing the session with "invalidate" might lead to WTF moments if it was the default. It's probably better to let the end users choose it themselves if that's the behaviour they need.

Feel free to submit am issues or a pull request to symfony/symfony-docs if you have ideas on how to improve the documentation.

Thank you!

**Comment by noniagriconomie** [comment]
@jakzal thanks for your answer and your time

Maybe i will yes :)
