### ISSUE TITLE
Prevent service names from including characters not supported by the dumper

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17801]
The reasons are explained in this other discussion: https://github.com/symfony/symfony/pull/17687

The idea is:

  * Deprecate and trigger deprecation warnings since 3.1
  * Throw exceptions since 4.0

**Comment by stof** [comment]
Given that the dumper now supports any characters since #18167, is this still necessary ?

**Comment by xabbuh** [comment]
@javiereguiluz What do you think? I think @stof is right here and we can close this one (we did the same with #18028).

**Comment by javiereguiluz** [comment]
@xabbuh yes! I agree with you and with @stof. This is no longer needed. Closing it. Thanks!
