### ISSUE TITLE
PHP Parse error in Symfony3 using installer

### ISSUE THREAD

**Issue by sameg14** [symfony/symfony#17815]
Steps to reproduce

1. Download symfony installer following these instructions
```
sudo curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony
sudo chmod a+x /usr/local/bin/symfony
symfony --version # Symfony Installer version 1.5.0
```

2. Next attempt to install a new project
```
symfony new otto
cd otto
./bin/console server:run
```
```
PHP Parse error:  parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/djcodesa/vagrant/otto/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 386
```

**Comment by sameg14** [comment]
I am on a mac OSX 10.9.5 and here is my PHP version
```
PHP 5.4.45 (cli) (built: Sep  6 2015 20:56:23)
```

**Comment by xabbuh** [comment]
Well, for Symfony 3 you need PHO 5.5 or higher.

**Comment by javiereguiluz** [comment]
@sameg14 the right answer is the one given to you by @xabbuh. But if you have other issues with the Symfony Installer, please open an issue in https://github.com/symfony/symfony-installer Thanks!
