### ISSUE TITLE
Service as a decorator by default for some configurable framework services.

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#17821]
I have an idea. When setting a service id inside a bundle configuration section like for example
security.yml

``` yaml
security:
    firewalls:
        main:
            entry_point: app.security.authentication_entry_point
```

the service `app.security.authentication_entry_point` (and some other replaceable services) could be automatically set as a decorator (or maybe when it is explicitly set as a decorator but it is missing the decorated service id) so the alias `app.security.authentication_entry_point`**`.inner`** could be used.

In this particular case the original framework default entry point id is usually `security.authentication.form_entry_point.main`. But not every time since it depends on the configured firewall etc. And this service id is actually an internal implementation detail.

I think it's actualy quite easy to implement. Just something like
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L358

``` php

if ($configuredEntryPoint) {
    $definition = $container->getDefinition($configuredEntryPoint);

    if (!$definition->getDecoratedService()) {
        $definition->setDecoratedService($defaultEntryPoint);
    }
}
```

Can try to test it and send a PR.

**Comment by iltar** [comment]
I've read your previous issue but I don't really understand the problem you're trying to solve. Can you provide some nice use-case perhaps?

**Comment by maryo** [comment]
I was thinking about other places where this feature would be useful so I checked other Symfony bundle configuration files and atually I couldn't come up with any other examples from other Bundles. That's simply because SecurityBundle configuration has very deep structure
http://symfony.com/doc/current/reference/configuration/security.html

So other examples from my applications are again from SecurityBundle:
BTW this is just a simple login form :)

When user logs in, he is redirected to a page he came from.
I don't use HTTP referer header because for example when you refresh the login page, the previous page is lost. I don't use sessions for storing the referer because that could cause problems with caching like when using Varnish. So I just simply pass the referring URL in a query parameter and then using `_target_path` hidden field. Cool. But suddenly a bug arrives! When the user tries to log in using bad credentials then the referring url query parameter is lost.
So I decided to specify custom `failure_handler`. I wanted it to decorate the default one because i try to prefer composition over inheritance but Symfony suggest to extend `DefaultAuthenticationFailureHandler`. 
There is a docblock saying "`Can be optionally be extended from by the developer to alter the behaviour while keeping the default behaviour..`" (notice the triple `be` :))

That's actually not a problem. Just an example where decoration could be preferred.

------------- 

Another related example: Since the referring url is passed in the query parameter I decided to prevent the application from redirecting to other sites than those from my application (URLs matched by router is a solution good enough). Again, I decided to extend `DefaultAuthenticationSuccessHandler` but composition would taste better.

-------------

Another example is the one mentioned in the linked issue - decorating the entry point.

If the decoration of this default behaviour would be as simple as it is when implementing other decorators (the `decorates` feature of service definition) then these issues would be simpler to solve and classes like CustomAuthenticationSuccessHandler and CustomAuthenticationFailureHandler could be deprecated favor this approach.

**Comment by iltar** [comment]
So if I understand the issue correctly, the problem lies with the DefinitionDecorator?
```
# just an example, this one actually uses an alias instead in the SecurityExtension
security.user_checker
# when configured for a firewall
security.user_checker.secured_area
```

And if I understand this correctly, you want to have the new `security.user_checker.<context>` take over the service decorating the original `security.user_checker` instead of having the `.inner` variant?

**Comment by maryo** [comment]
I am actually not sure. Maybe.

Let's say you've configured `user_checker: app.user_checker`

so there are three IDs now

`security.user_checker` - the default behavior
`app.user_checker` - your custom service
`security.user_checker.secured_area` - the alias symfony creates and uses which points to 
```

But there is no `.inner` variant for any of these 3 services. And that's it. I want to be able to inject using the `.inner` variant the default behavior to the new service `app.user_checker`.
Ofc I could set the service `app.user_checker` to decorate the default behavior explicitly using `decorates: security.user_checker` but I had to know the name of the default behavior service `app.user_checker`. But OFC it's lesser problem in this case since `security.user_checker` is quote a logical name.

**Comment by javiereguiluz** [comment]
@maryo in short you are asking this:

```
The service `app.security.authentication_entry_point` could be automatically set as a
decorator (or when it's explicitly set as a decorator but it's missing the decorated service id)
so the alias `app.security.authentication_entry_point.inner` could be used.
```

I'm afraid that this kind of features are usually rejected by the Symfony community because they are considered a bit "magical". They always doing things explicitly, even if it's a bit verbose.

**Comment by stof** [comment]
@maryo the ``*.inner`` service is created when using the decoration feature (and it won't appear at runtime as it is a private alias and so gets removed during the optimizations).
and if you make ``app.user_checker`` decorates ``security.user_checker``, the ``security.user_checker`` service will be your custom service at runtime (the same than ``app.user_checker``)

**Comment by javiereguiluz** [comment]
Closing because of the lack of activity and because of the above comments. @maryo I'm sorry this time your feature proposal didn't make it, but please keep sending more ideas to improve Symfony. Thanks!
