### ISSUE TITLE
[Config] Missing mandatory dependency on symfony/yaml?

### ISSUE THREAD

**Issue by calinpristavu** [symfony/symfony#17826]
If you require only the `symfony/config` component you depend on the `symfony/yaml` `Inline` class, which does not show up in the composer `require` section.

Here is a [gist](https://gist.github.com/calinpristavu/d397d64a41c8f2860707) with the proof of error. Steps to reproduce: 
1. require only the config component
2. run the code in the gist

In order to solve this, we need to tightly couple the `symfony/config` component to `symfony/yaml` or duplicate the `Inline::dump()` functionality used [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Dumper/YamlReferenceDumper.php#L96) and [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Dumper/YamlReferenceDumper.php#L110) (which is definetly not a good idea IMO).

I wanted to make a PR only on the [Config component](http://www.github.com/symfony/config) but that one is marked as read-only and add `symfony/yaml` to the config components `config.json` require section.

Should I make a PR here and add the dependency to the configs `composer.json` or in the dedicated repo?

**Comment by WouterJ** [comment]
Well, you are using the `YamlReferenceDumper`. You can use te component perfectly without using this class. That's why it isn't in the main require section.

It should however be added to the "suggest" section of `composer.json`:

```json
{
    "suggest": {
        "symfony/yaml": "To use the yaml reference dumper"
    }
}
```

**Comment by dosten** [comment]
This isn't entirely true because you are not required to use the `YamlReferenceDumper` but agree that we should add a statement that throws an exception if the Yaml component isn't installed.

**Comment by calinpristavu** [comment]
@WouterJ Indeed you are not "supposed" to use it without the yaml component, however it's public and available. the `suggest` section makes perfect sense.

@dosten IMO adding a suggest message is a better solution, because the config component is not supposed to know internally about the yaml one.

**Comment by dosten** [comment]
So, if the Config component is not supposed to know about the Yaml component the `YamlReferenceDumper` makes no sense right? IMO if the Config component provides a Yaml dumper is better to add a check in the constructor to have a nice error message and not a random PHP error.

IMO you should add a suggest section in the composer file and a check in the constructor like here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Dumper/YamlDumper.php#L41-L43

**Comment by calinpristavu** [comment]
:+1: indeed

**Comment by WouterJ** [comment]
@calinpristavu there is no dependency in 2.3 and the next still maintained version is 2.7. So please make a PR against 2.7.

@dosten throwing exceptions isn't done for any other optional deps either

**Comment by dosten** [comment]
@WouterJ If you check my example below you will see that the Yaml dumper in the DependencyInjection component have this check and Yaml is a optional dep https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/composer.json#L27

**Comment by calinpristavu** [comment]
@dosten True, but in our case the yaml component is only needed in one method for two specific cases:
[1](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Dumper/YamlReferenceDumper.php#L94) and [2](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Dumper/YamlReferenceDumper.php#L109), so it's not correct to assume that the entire `YamlReferenceDumper` class is unusable without the optional dep.

I think the suggestion message should be enough.
