### ISSUE TITLE
Use immediate redirects

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17824]
I was replying to [this StackOverflow question](http://stackoverflow.com/questions/35341084/symfony2-redirectresponse-message/35451398) about a user which complains because redirections display the message *Redirecting to ...*

The reason seems to be that Symfony hardcodes a 1 second delay in the HTML used to perform the redirections ([see code](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L86-L96)):

```php
$this->setContent(
sprintf('<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=%1$s" />  <-- here it's the 1 second delay
        <title>Redirecting to %1$s</title>
    </head>
    <body>
        Redirecting to <a href="%1$s">%1$s</a>.
    </body>
</html>', htmlspecialchars($url, ENT_QUOTES, 'UTF-8')));
```

The question is: could we replace `<meta http-equiv="refresh" content="1;..." />` by `<meta http-equiv="refresh" content="0;..." />` to perform immediate redirects?

**Comment by iltar** [comment]
Isn't this simply a fallback because of the header failing? I agree that "0" seconds might be a better choice but afaik this case shouldn't be triggered (often).

**Comment by stof** [comment]
Yeah, this code is only triggered if the headers cannot be sent properly, which probably indicate a bug in their own code which would output something before sending the response.

**Comment by fabpot** [comment]
As @stof said, nobody should see this notice. As we never had any complaints before, I would say that this is not relevant.

**Comment by javiereguiluz** [comment]
I agree with @fabien. Not having previous complaints is a good indicator of not being relevant. Closing it.
