### ISSUE TITLE
Constraints payload option not available in view

### ISSUE THREAD

**Issue by linxlad** [symfony/symfony#17830]
No matter what variation:

```php
         ->add(
                'password',
                PasswordType::class,
                [
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Your password cannot be blank.',
                            'payload' => 'SomePayLoadOption'
                           // or 'payload' => ['type' => 'SomePayLoadType']
                        ])
                    ],
                    'label' => 'Create your password',
                    'attr' => [
                        'class' => 'form-control input-lg',
                        'required' => 'required',
                        'autocomplete' => 'off'
                    ]
                ]
            )
```
![Null cause](https://s3.amazonaws.com/f.cl.ly/items/0I0l392K2Q1Y2X1K1o0B/Image%202016-02-17%20at%206.04.20%20PM.png?v=4429c5d7)

The cause is null which contradicts the documentation:

[Constraint Docs](http://symfony.com/doc/current/reference/constraints/NotBlank.html#payload)
and
[Docs paylod in cause property example](http://symfony.com/doc/current/cookbook/validation/severity.html)

Is this a known issue or misconfiguration on my part?

**Comment by calinpristavu** [comment]
Weird because I just copy-pasted your form type, created a view, submitted an empty value and my `form.vars.errors.errors.cause` field has the constraint in it, and also the payload... maybe provide more code to find out what's happening?

**Comment by linxlad** [comment]
Thanks for testing for me. Strange, I am using Symfony 3.0.2. How are you creating the form in your controller and passing it to the view?

**Comment by calinpristavu** [comment]
@linxlad 
Just like the documentation suggests:
`$this->createForm(TestType::class);`
`{{ dump(form.password) }}`
using a fresh install of sf 3.0

Please provide the steps to reproduce YOUR issue, otherwise this can be considered a misconfiguration.

**Comment by xabbuh** [comment]
@linxlad The best were if you could fork the Symfony Framework Edition and just make the changes that are necessary to reproduce your issue.

**Comment by linxlad** [comment]
Ok, it turns out it was a caching issue and cause was not being cached with the error message. Thanks a lot for you help guys.
