### ISSUE TITLE
Issue and Pull Request templates

### ISSUE THREAD

**Issue by seferov** [symfony/symfony#17841]
Yesterday GitHub [announced](https://github.com/blog/2111-issue-and-pull-request-templates) supporting issue and PR templates.

I think it would be nice to add `.github` to add templates automatically instead of adding them manually from the documentation.
https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by nicolas-grekas** [comment]
Already done :)

**Comment by javiereguiluz** [comment]
@seferov to give you some more info: this is the merged pull request which added this feature: #17831

**Comment by seferov** [comment]
@javiereguiluz @nicolas-grekas thanks, good job. Sorry, I was missed that one.
