### ISSUE TITLE
[DX] Profiler: Improve timeline page view: add an hierarchical view with extra info.

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#17843]
Hi everyone!

Firstly, let me describe my issue. This is typical profiler line view:
![image](https://cloud.githubusercontent.com/assets/392644/13142192/8b3a907c-d64c-11e5-8a81-71fa9ba5a580.png)

There is a lot of repeated sql queries, but there is no any extra helpful information to detect the place to optimization. I want to see which queries are executed there. But there is no such info, I should go to "Database" profiler page and should lookup through plain list of queries.

It would be cool, if popup with extra information (sql query in my case) opens on hover on timeline item.

**Comment by ogizanagi** [comment]
Note this can relate to https://github.com/symfony/symfony/issues/27262 which suggests to add more info & interactivity in this panel. 
This kind of extra information could be added through a new `Stopwatch` component feature allowing to attach arbitrary data to a `StopwatchEvent` instance (but we should be cautious about what we'll put inside).

**Comment by fabpot** [comment]
Closing as nobody worked on this. I also think that adding this kind of feature would slow things down quite a bit and increase the profile payload size significantly.
