### ISSUE TITLE
Warning: session_write_close(): Failed to write session data....

### ISSUE THREAD

**Issue by rvaliev** [symfony/symfony#17845]
I'm using Symfony 3.0.2 with: 
nginx version: nginx/1.4.6 (Ubuntu)
php version: 7.0.3-4+deb.sury.org~trusty+1

Everything works fine except when I try to enter the Symfony profiler where I get the following message:

> 
Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/Symfony/app/../var/sessions/dev)
> 

After that I get this error on every page. To be able to see regular pages again I just need to delete session cookie from my browser. But again, it works fine till I try to enter the Symfony profiler.

This error occurs only when I add to nginx config file this line:

> 
fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
> 

However, when using php5 by adding the following line everything works fine:
> 
fastcgi_pass unix:/var/run/php5-fpm.sock;
> 

BTW. I have another project which is build on Symfony 3.0.1, and there is no such a problem.

**Comment by Tobion** [comment]
Duplicate of #17715

As you are the second one reporting this, can you please debug this problem?

**Comment by rvaliev** [comment]
Tobion, I'm new to Symfony, what do you mean by "debug this problem"? :) 
I've just installed another 2 projects: first one is Symfony 3.0.1 and the second one is 3.0.2. And again I've got the same problem on 3.0.2. 
3.0.1 version works flawless.

**Comment by Tobion** [comment]
What I mean with this is to try to figure out why the error occurs. So we know the reason and then can work an a fix if it is caused by symfony.

**Comment by rvaliev** [comment]
Ok, here it is:

In: 

> 
vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
> 

On line 216 delete session_write_close(); and it works fine again.

**Comment by stof** [comment]
Well, this also removes the associated feature. So it is not a fix.

**Comment by javiereguiluz** [comment]
@rvaliev to recap the causes of the problem, please confirm me that it only occurs when using the Symfony Profiler in Symfony 3.0.2 (and PHP 7 with nginx). The same setup with Symfony 3.0.1 works perfectly. Thanks.

**Comment by rvaliev** [comment]
@javiereguiluz yes. Problems on Symfony Profiler in Symfony 3.0.2 with 
nginx version: 1.4.6 (Ubuntu)
php version: 7.0.3

**Comment by rvaliev** [comment]
Just got the same error using Symfony 3.0.2 on a regular page when building a simple form accordingly to Symfony book. 
My controller looks like this:

> 
 $task = new Task();
        $task->setTask("Write a new blog");
        $task->setDueDate(new \DateTime('tomorrow'));

        $form = $this->createFormBuilder($task)
            ->add('task', TextType::class)
            ->add('dueDate', DateType::class)
            ->add('save', SubmitType::class, array('label' => 'Create Task'))
            ->getForm();
>

**Comment by patrick-mcdougle** [comment]
Does the php package run as a different user perhaps? Could this be a permissions problem?

**Comment by rvaliev** [comment]
@patrick-mcdougle  "ps -ef | grep php5" and "ps -ef | grep php7" commands show the same user viz. "vagrant".

**Comment by mirandaguillaume** [comment]
I currently have the same issue ... 
But it's only from 2 or 3 days as I've had to destroy and recreate my VM with vagrant

**Comment by kainjow** [comment]
From what I've seen, this isn't a Symfony issue, it's an nginx/PHP-FPM issue. PHP-FPM runs its pools as a certain user, so you need to figure out what that use is and either change it to be the "vagrant" user for development with vagrant, or figure something else out. NFS synced folders can't have permissions changed, so an rsync synced folder was what I had to use to get this to work while maintaining a matching server config to production

**Comment by rvaliev** [comment]
@kainjow if it was a nginx/php fpm issue only, then Symfony 3.0.1 should have the same problem.

**Comment by kainjow** [comment]
@rvaliev not unless it was a (security) bug with how permissions were handled with that version.

**Comment by berdyshev** [comment]
confirm. this bug has been reproduced with php7-fpm + nginx and symfony 3.0.3

**Comment by antkowiakit** [comment]
Same problem. Comment
session_write_close(); 
in
Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage
Sloving problem..

**Comment by patrick-mcdougle** [comment]
Commenting out or deleting `session_write_close()` is not a solution. Please stop suggesting this. This will break all session data in your app, flashes, csrf, etc.

**Comment by antkowiakit** [comment]
You can move session to memcached. It sloving problem.

Terminal:
`sudo apt-get install php-memcached`
config.yml:
```
framework:
    session:
      handler_id:     session.handler.memcached
```
parameters.yml:
```
    session_memcached_host:     localhost
    session_memcached_port:     11211
    session_memcached_prefix:   sess
    session_memcached_expire:   3600
```
services.yml:
```
    session.memcached:
        class: Memcached
        arguments:
            persistent_id: "%session_memcached_prefix%"
        calls:
            - [ addServer, [ "%session_memcached_host%", "%session_memcached_port%" ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ["@session.memcached", { prefix: "%session_memcached_prefix%", expiretime: "%session_memcached_expire%" }]
```

**Comment by berdyshev** [comment]
yes, I've made this already, but this doesn't fix the bug with native sessions :smile:

**Comment by jdelaune** [comment]
Getting the same issue, Symfony 3.0.3, using apache and not nginx however.

**Comment by stof** [comment]
If the issue is related to the sync folders of vagrant, another solution (rather than changing the php-fpm user or the way folders are synchronized) is to change the path where sessions are stored, to be outside the synced folders (you don't really need stored session data to be synced anyway)

**Comment by jdelaune** [comment]
Thanks @stof changing the save_path to /tmp worked great.

**Comment by floriansemm** [comment]
same issue here with PHP 5.6.17 on Debian with Symfony 3.0.3

**Comment by mtrenker** [comment]
i just stumbled over the same issue, having the session folder in a docker volume. it seems to be a problem with extending the [SessionHandler](http://php.net/manual/en/class.sessionhandler.php), [SessionHandler::write](http://php.net/manual/en/sessionhandler.write.php) returning false and a [missleading error message](https://bugs.php.net/bug.php?id=71070) 

A quickfix would be to use the session handler without extending it by setting the [handler_id](http://symfony.com/doc/current/reference/configuration/framework.html#handler-id) to null (``handler_id``: ~)

**Comment by Briones** [comment]
Same issue here. PHP 7.0.4 on Ubuntu Xenial and Symfony 3.0.4

Any updates?

**Comment by mtrenker** [comment]
i stumbled upon this using a docker volume and php7-fpm, i really don't know what exactly causes this (it appears to be a problem with synced folders) but [this bug report](https://bugs.php.net/bug.php?id=71070) seems relevant, the error message is misleading.

Background: The [NativeSessionHandler](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeSessionHandler.php) is extending the [SessionHandler](http://php.net/manual/en/class.sessionhandler.php) and apparently, the [write](http://php.net/manual/en/sessionhandler.write.php) function returns false for some reason. from what i've read, newer php versions are more strict with that response, throwing said, error if it does not return true. 

2 quick fixes for the problem:

* use the default SessionHandeler defined in the php.ini (which will basically store the files in the tmp folder of the OS by default so this is almost the same solution as stof's) by setting the [handler_id](http://symfony.com/doc/current/reference/configuration/framework.html#handler-id) to null (``handler_id: ~``) 
* write your own Session handler that extends the [NativeFileSessionHandler](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php) and overwrite the write() method, within the new method call parent::write() within a try/catch statement and return true if no Exception was thrown. As a disclaimer, i don't really know what is going on in the native write() method but looking into the other Handlers such as the [PdoSessionHandler](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php) which also always returns true i think it is worth a shot.

**Comment by Briones** [comment]
@mtrenker Your first solutions works for me. I'm also using Docker.

**Comment by cAstraea** [comment]
Had the same exact same problem symfony 3.0.6 and php 7 , it's a matter of permissions for the shared folder. 
Fixed it by adding the vagrant user and group to the synced folder. 
for example
        config.vm.synced_folder folder["map"], folder["to"], owner:"vagrant",group:"www-data" type: folder["type"] ||= nil

**Comment by HellC0der** [comment]
@mtrenker Also encountered this issue (Ubuntu 14.04 LTS, PHP7, apache2, Symfony 3.0.5) and first solution worked fine for me. But isn't it worse in some way than keeping session file in application directory.

Also I would like to ask... if I make this change

`handler_id: ~`

and keep:

`save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"`

Will Symfony ignore save_path value?

**Comment by ghostal** [comment]
I had this problem under vagrant, with the `ubuntu/trusty64` vagrant box, nginx, PHP 7 and Symfony 3.0.6. As suggested by @kainjow, changing the PHP-FPM pool configuration to switch the user it was running as solved the problem.

For those unsure how to do this:
```
$ sudo nano /etc/php/7.0/fpm/pool.d/www.conf
```
These lines...
```
user = www-data
group = www-data
```
... become...
```
user = vagrant
group = vagrant
```
Save, and then restart the PHP-FPM service:
```
$ sudo service php7.0-fpm restart
```

It seems odd to me though that it should matter which user the pool runs at though, as everything under `/vagrant` is owned by the `vagrant` user and `vagrant` group, but the permissions are all `777`. So my guess would be that the bug is something to do with something misinterpreting permissions.

**Comment by jmleroy** [comment]
Same issue here with Symfony 3.0.6 and PHP7 using Vagrant (puphpet, ubuntu 14.04)
With @antkowiakit 's solution, I got an exception coming from the debugger saying that it doesn't know the class Memcached. I don't have the exact error, because before writing this sentence, I noticed ghostal's response which I thought could help me, since we have more or less the same configuration. 
I suspected before that it was a problem with ownerships since ./var/sessions had 0775 for permission. Alas, whenever I try to sudo change ownership or permissions on /var/www/myproject/whatever, all files remain with www-data:www-data for owner:group and 0664/0775 for permissions. Worse, when I refreshed my page, the old warning on session_write_close reappeared (maybe from the cache?)
I'm out of ideas for the moment :-/

**Comment by jmleroy** [comment]
Aaaand still happening in Symfony 3.1.0.

**Comment by javiereguiluz** [comment]
Is there a consensus here whether this is a Symfony bug or a Vagrant/OS bug/feature/issue? Thanks.

**Comment by mvrhov** [comment]
it seems that the owner of directories inside a vagrant deploy is a vagrant user.so fo php-fpm to be able to write into the folders it also has to be run under vagrant user.. IMO something is wrong with vagrant deployment script. as it seems to create the directories under a wrong user. or vagrant is the only user supported.

**Comment by jmleroy** [comment]
The problem appears even when www-data is set as the owner (default setting in puphpet), and as @ghostal mentioned, the var/ and var/sessions directories have both permissions set to 0777. 
I tried to mount my shared directory as a NFS partition instead of the default setting but it did not solve the problem: the permissions are still set to 0777 but to "502:dialout" user:group and the session files created are empty and have permissions set to 0600.

**Comment by xabbuh** [comment]
@jmleroy Who is owner and group of the created session files?

**Comment by J-Sanchez** [comment]
Im running Vagrant, Ubuntu 14.04.3 LTS, PHP7, Apache.
@ghostal bring me the solution but with a single modification.

In /etc/php/7.0/fpm/pool.d/www.conf user and group must be www-data.

**Comment by mvrhov** [comment]
@J-Sanchez AFAIK, the user and group are set to www-data insode of www.config in default ubuntu/debian build.

**Comment by tstrijdhorst** [comment]
I have the same issue with CentOS 6, PHP7 php-fpm, apache and symfony 3.1. Everything in /var/www/ is owned by www-data. Like others said it does make the session file but it's empty. When I su as www-data I can actually write files in the session path...

Checked www.conf and it runs as www-user, so I thought changing that to www-data would help but it didn't, shouldn't matter anyway since it's in the www-data group and everything is 664.

**Comment by emil-nasso** [comment]
This might not be relevant for everyone but i ran into this issue when running symfony in a docker container and using docker-compose.

I shared the source folder between the host and the container but created volumes for the cache- and sessions-folders so they aren't shared. I don't think it makes sense to share them really. The are unique to the instance running inside the container.

This is how my docker-compose file looks:

```
dev:
  build: .
  command: "php bin/console server:run 0.0.0.0:8000"
  working_dir: "/var/www"
  volumes:
    - .:/var/www
    - /var/www/var/cache/
    - /var/www/var/sessions
  ports:
    - 8000:8000
```

**Comment by csiewert** [comment]
I had the same problem with symfony 2.7 and php 7. Changing user/group to www-data in /etc/php/7.0/pool.d/www.conf resolved it for me.

**Comment by eduardor2k** [comment]
Hi to all,
Deleting all the files inside var/sessions/dev/* worked for me. **PHP 7.0.8, Symfony 3.1.2, Ubuntu 14.04**

**Comment by mcocaro** [comment]
I have the same setup, a vagrant machine with a docker env using php 7 and symfony 3+ - setting the session handler id to null, fixed the issue to me.

**Comment by rvaliev** [comment]
I've figured out the issue. It seems that storing the session files in shared folders is not a good idea. So if you're using a vagrant box like me try to do the following:

`sudo mkdir /var/lib/php/project_folder -p`

then cd to '/var/lib/php' and change project_folder's ownership:

`sudo chown www-data:www-data knp_sessions/ -R`

Verify whether ownership is set to www-data:www-data. 
Open config.yml within symfony project and replace this line (within session config parameters):

`save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"`

to this line:

`save_path:   /var/lib/php/project_folder`

Now everything should be working fine.

**Comment by jakzal** [comment]
Closing as most of us seem to agree it's not a Symfony problem. If anyones feels it's needed,  please submit a PR to documentation to warn the end users about this potential pitfall.

**Comment by digilist** [comment]
I ran into the same error, but for a different reason. I use the memcached session handler and configured the wrong host which resulted in the exact some error message. The error indicates there is an error with the file system write, but that is actually not the case, because the memcached connection fails. Maybe this helps someone who made the same mistake :smile: (I opend an issue to improve the error message #20807)

**Comment by Lusitaniae** [comment]
Should we improve error messages for this scenarios: https://github.com/symfony/symfony/issues/17845#issuecomment-265408195

**Comment by ChrisBPB** [comment]
I got this issue on Symfony 5.1.3, it was caused by too many concurrent ajax calls, ofcourse php sessions have inherent issues due to session lock, esp on file system based caches, but I had never experienced this on Symfony 2, 3, or 4.

I have switched to memcached, but I don't see why this should be necessary just to make 2 ajax calls without destroying my session.
