### ISSUE TITLE
[Process] Make $starttime publicly accessible

### ISSUE THREAD

**Issue by tehplague** [symfony/symfony#17842]
Symfony Process keeps a private `$starttime` property which is used to check whether the configured process timeout has expired. It would be useful if this property could be exposed via a public getter, say `getStartTime()` returning a `\DateTime` with its value.

This can e.g. be used to calculate the total time a process has been running for. Currently storing the start time involves additional bookkeeping of a DateTime value along with the Process object.

**Comment by tehplague** [comment]
It should be possible to implement this without breaking BC ;-)

**Comment by Tobion** [comment]
:-1: The starttime is an implementation detail of the timeout and idle timeout logic. We try not to create unecessary extension points. Otherwise we would also need to expose the last output time. Also keeping track of the start time is one line of code. So closing.
