### ISSUE TITLE
Api Token Authentication just does not work

### ISSUE THREAD

**Issue by J7mbo** [symfony/symfony#17853]
I have followed the docs on two fresh Symfony 3.0 installs to set up the ability to authenticate via API key but the user is `null` when requesting it in the controller. I have documented my code here:

http://stackoverflow.com/questions/35480550/symfony-authentication-with-an-api-token-request-token-user-is-null

Visiting: `http://127.0.0.1:8000/app_dev.php?apiKey=123456789` with the following code in the default controller shows `null`:

```php
class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        var_dump($request->getUser()); die; // null
    }
}
```

Calling `$token->getUser()` in the `ApiKeyAuthenticator` returns `anon.`.

**Comment by J7mbo** [comment]
Turns out that I'm asking for the `$request->getUser()`, which *doesn't* correspond to the currently authenticated user - instead that's for HTTP Basic Auth. This is confusing to be honest, I would expect that the user of the current request would be the currently authenticated user.

**Comment by stof** [comment]
The Request object does not know about the Symfony authentication system. I strongly suggest you to read the Symfony documentation about the Security system.

**Comment by J7mbo** [comment]
Already read it. It's not made explicitly clear in the authentication by API token documentation and I think it may be helpful to clear up confusion there. Will submit a docs PR.
