### ISSUE TITLE
[RFC] Show voter information in the security profiler panel

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17856]
### Problem

The security panel is not very useful because it provides little information:

![security_before](https://cloud.githubusercontent.com/assets/73419/13179546/ae3166ae-d724-11e5-901c-c5af6df7dc77.png)

### Solution

Could we show at least the information about the voters that granted/rejected access? A quick-and-dirty mockup of the idea:

![security_after](https://cloud.githubusercontent.com/assets/73419/13179587/d788f10c-d724-11e5-82cc-91acba09662c.png)

Questions:

  * Can this information be obtained in a reliable manner for any Symfony application?
  * Could we get inspiration from this bundle for implementing this feature? https://github.com/egulias/SecurityDebugCommandBundle
  * Do you miss any other important information in this panel?

Thanks!

**Comment by stof** [comment]
About what would you display the votes ? There can be many decisions being taken during a page load.

**Comment by javiereguiluz** [comment]
@stof all of them then.

**Comment by javiereguiluz** [comment]
Sorry for the short answer. i just wonder if there is a reliable way to show what's going on regarding the security voters during a page load? (even for cases like the one you commented). Security is the most critical thing in an app and I feel that the profiler doesn't help users as much as it could.

**Comment by stof** [comment]
@javiereguiluz displaying votes being done would require building a custom AccessDecisionManager to log decisions being made. This is quite easy to do (build a decorating implementation and wrap the service in debug mode)
Registering the vote of each voter for each decision is harder to implement (especially to correlate them with the decision)

**Comment by iltar** [comment]
What about a voter handling N attributes? Something else that could be interesting, would be to display which attributes have been voted on and what the result was:

| Result | Attribute | Source
|----|----|----
| Granted | CAN_SEE_FOO | some/template/file.html.twig:50
| Denied | CAN_SEE_BAR | SomeController:SomeAction:23
| Granted | IS_AUTHENTICATED_ANONYMOUSLY | access_control
| Denied | IS_AUTHENTICATED_FULLY | SomeController:SomeAction Annotation

Can easily be achieved via a backtrace in a decorator around the `AuthorizationChecker` using the `AuthorizationCheckerInterface` which will have no performance loss in prod.

In theory you can also automatically decorate voters and map their result and class. I think this feature would be more useful as the presented doesn't give me any useful information. Sure, I know which voter gave me a certain result, but that doesn't tell me where it happened and for what it happened.

**Comment by javiereguiluz** [comment]
@iltar :+1: very nice! I like your idea.

**Comment by javiereguiluz** [comment]
@iltar @stof in #17887 I'm trying to implement your ideas. @iltar I have no idea about how to get the **Source** information of your table. Any clue? Thanks!

**Comment by iltar** [comment]
@javiereguiluz this is a bit more complicated. In case of `@Security` annotations, you'd want to hook in on the [`SecurityListener` in the SFWEB](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/SecurityListener.php), for the [`access_control` in the AccessListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/AccessListener.php) and for the template I'm not entirely sure. However, for the template you should be able to somehow get the template source line numbers as this is also available when debugging.

Sadly my experience ends here. A generic solution could be to decorate the `AccessDecisionManager`, but then a lot of stack traces would be meaningless :(

**Comment by anacona16** [comment]
+1. I do not know how much is complicated, but it would be very useful.

**Comment by TomasVotruba** [comment]
:+1: Very nice

**Comment by robfrawley** [comment]
Related, and touching on a few ideas that would be helpful for the purpose of this issue: #17892.

**Comment by tristanbes** [comment]
Very useful when debugging voters, was wondering myself why it wasn't already here last week.
