### ISSUE TITLE
"Encoder" is a Misnomer which Leads to Confusion

### ISSUE THREAD

**Issue by paragonie-scott** [symfony/symfony#17857]
Referring to: https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Security/Core/Encoder

I saw [this thread on StackOverflow](https://stackoverflow.com/questions/35505488/password-en-decryption-fails-with-symfony-3-0), wherein the author is confused about actual cryptography terminology. It seems their confusion is stemming from the naming convention that Symfony uses.

I'd like to refer to my blog post about [cryptography terms and concepts](https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded) (which has been informally peer-reviewed by crypto experts for both semantic and colloquial accuracy and even-more-informally peer-reviewed by neophytes for digestibility).

* Cryptography
    * Keyless
        * Cryptographic hash functions
    * Secret-Key
        * Secret-Key Encryption (e.g. block ciphers, stream ciphers)
        * Secret-Key Authentication (e.g. HMAC)
        * **Password Hashing**
    * Public-Key
        * Key Agreement
        * Public-Key Encryption
        * Public-Key Authentication - Digital Signatures (e.g. RSA, DSA, ECDSA, EdDSA)
* Not Cryptography
    * Compression
    * **Encoding**

This might be something that has to be punted to Symfony 4 (assuming Symfony follows semver), but the average Symfony developer's understanding of the correct cryptography terminology would greatly improve if Symfony changed its vocabulary.

This is just something to consider.

**Comment by javiereguiluz** [comment]
In the Symfony docs there is another issue related to this: https://github.com/symfony/symfony-docs/issues/5688

**Comment by javiereguiluz** [comment]
@paragonie-scott you are right about this. Symfony should replace "encode" by "hash" everywhere. Sadly we cannot do this now because it will be a nightmare to do that change without breaking anything. I know it's not the same, but the docs now explain this misnaming: http://symfony.com/doc/current/book/security.html#dynamically-encoding-a-password

That's why I'm closing this issue as "won't fix". Thank you!
