### ISSUE TITLE
Issue with @Template annotations

### ISSUE THREAD

**Issue by andrewtch** [symfony/symfony#17869]
Symfony 3.0.2, clear installation. @Template annotation renders the following error:

```
Attempted to call an undefined method named "getTemplate" of class 
"Symfony\Bundle\FrameworkBundle\Templating\TemplateReference".
```

Possibly connected with this commit, but not sure: https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/82b8ad65409c99f693088ecbc09c857f01e3b3fa#diff-95cd70265579b17c2c8bf5b9a3037ee6

**Comment by andrewtch** [comment]
dev-master of FrameworkExtraBundle does not work either.

**Comment by iltar** [comment]
@AndrewCarterUK can you show the code that triggers this?

**Comment by andrewtch** [comment]
Just adding any controller / action with @Template annotation. Any bundle, yml configs.

**Comment by iltar** [comment]
Do you have a stack-trace for me?

**Comment by andrewtch** [comment]
Strangely, in PROD i have:

```
[1] Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getTemplate" of class "Symfony\Bundle\FrameworkBundle\Templating\TemplateReference".
    at n/a
        in /PATH/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php line 62
```
and in DEV:

```
[1] Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getTemplate" of class "Symfony\Bundle\FrameworkBundle\Templating\TemplateReference".
    at n/a
        in /PATH/var/cache/dev/classes.php line 7092
```

which is, basically, the same lien in the same file.

Logs basically show KenelRequest -> TemplateListener -> Kaboom.

**Comment by iltar** [comment]
The class cache is a prod thing (which you can turn off if desired). I will
check tomorrow what goes wrong as all tests succeeded when this PR was
merged. I especially added functionality tests for this so maybe something
changed after the last test ran.

**Comment by iltar** [comment]
@andrewtch When I take [`/EventListener/TemplateListener.php line 62` from the commit before mine](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/991aba281bc34a9f306e8f6955bae78871ea82c0/EventListener/TemplateListener.php#L62), I get the line you mentioned. [In the most recent master, this line is empty](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/TemplateListener.php#L62).

Can you make sure you're using the most recent version and re-open the issue on [sensiolabs/SensioFrameworkExtraBundle](https://github.com/sensiolabs/SensioFrameworkExtraBundle) if it's still broken?

**Comment by andrewtch** [comment]
Ok, dev-master fixes it. Seems like I pulled old version.

Closing this, but can you bake a tag for FrameworkExtraBundle so it can be used without dev-master? Thank you!

**Comment by iltar** [comment]
You could open an issue on that repository and ask for it as I'm not sure what the release schedule is for the extra bundle.
