### ISSUE TITLE
translation_domain not used for invalid_message translation

### ISSUE THREAD

**Issue by cleentfaar** [symfony/symfony#17880]
I am not sure this is an issue or by design;

From the [documentation](http://symfony.com/doc/current/cookbook/form/data_transformers.html#creating-the-transformer) I understand that when a `DataTransformer` triggers a `TransformationFailedException` in one of my forms, the `invalid_message` option is used to create a form error for the user. 

To my surprise, I found that the violation created by `FormValidator` does not make use of the `translation_domain`option I configured in my form.

Current code:
```php
$this->context->buildViolation($config->getOption('invalid_message'))
  ->setParameters(array_replace(array('{{ value }}' => $clientDataAsString), $config->getOption('invalid_message_parameters')))
  ->setInvalidValue($form->getViewData())
  ->setCode(Form::NOT_SYNCHRONIZED_ERROR)
  ->setCause($form->getTransformationFailure())
  ->addViolation();
```

Expected code:
```php
$this->context->buildViolation($config->getOption('invalid_message'))
  ...
  ->setTranslationDomain($config->getOption('translation_domain'))
  ...
  ->addViolation();
```

Currently the message ends up being translated for the `validators` domain, but I don't see why I shouldn't be able to override that behaviour and use my own domain for this; especially since my forms can have very specific contexts (i.e. not suited for global error messages).

Can someone confirm this? I'd be happy to write a patch for this if it really is a bug.

**Comment by HeahDude** [comment]
Hi @cleentfaar, this is not a bug.

All messages processed during the validation use the "validators" domain by default for their translation.

The Form component defines all of its base error messages in this domain too so you can override them.

You should open an issue in the doc so it may be said expliciltly in the option reference http://symfony.com/doc/current/reference/forms/types/form.html#invalid-message

But they is already a link to the validation references which precise it http://symfony.com/doc/current/book/translation.html#translating-constraint-messages

**Comment by cleentfaar** [comment]
Perhaps I wasn't clear; I know that form messages are translated with the `validators` domain by default. I also know that you can override the domain by using the `translation_domain` option in your form.

However, the override is not working for errors caused by a `TransformationFailedException`, which can happen when you use a custom `DataTransformer`.

The problematic code (inside `FormValidator`) is described above.

**Comment by HeahDude** [comment]
May be I wasn't clear either, `translation_domain` option does not override `validators` domain and that is an expected behaviour.

Then you should use `validators` domain for `TransformationFailedException` because changing this behavior would be a BC break.

**Comment by cleentfaar** [comment]
I see, thanks for clarifying!
