### ISSUE TITLE
[Security, Profiler] Incomplete implementation of role hierarchies

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#17892]
Hi,

I am trying to build a bundle implementing custom role definitions including role hierarchies.
That works very well with registering a custom `security.voter`. 
As the logic for this role hierarchy is provided by a **custom** security voter, it means the parameter in the security config is empty, i.e.

```
security:
    role_hierarchy: []
```

in `app/config/security.yml`.

So far, so good.

But there are two integration points into the rest of the framework that make issues with a custom role hierarchy.
To explain these two issues, let's use the following hierarchy:

```
ROLE_ADMIN
└── ROLE_USER
```
### 1. Profiler

On the security tab, the profiler displays the directly assigned roles, next to the inherited roles. The inherited roles are always empty.
### 2. Security Annotation / ExpressionVoter

The ExpressionVoter provides an array of `roles` for easy checking. This array of roles only uses the default RoleHierarchy as defined by Security Core.

This way you can have rather strange results:

``` php
/**
 * @Security("is_granted('ROLE_USER')")
 */
// works
```

whereas

``` php
/**
 * @Securty("'ROLE_USER' in roles")
 */
// Does not work
```
### Cause

The cause is that the security bundle assumes that there is only one role hierarchy (which is fed directly from the `security.role_hierarchy` configuration value). This assumption is not correct, as each `SecurityVoter` (probably subclassing `RoleHierarchyVoter`) might have its own hierarchy.

Each of these "role hierarchy extension points" (like `SecurityListener`, `SecurityDataCollector` and maybe `ExpressionVoter`) currently use a direct `RoleHierarchyInterface` to call `getReachableRoles`.

This global role hierarchy (stored in `security.role_hierarchy`) needs to be mutable, so that custom role loaders can benefit from it, too (and we would get the integration with the annotation / expression voter and with the profiler for free).

Custom bundles that integration role hierarchies could then just append roles to the global role hierarchy. This would add a new public method in RoleHierarchy.

Another implementation would be to just add another tag which collects all role hierarchy providers, which are then queried for complete role hierarchies, instead of just the global one. This would mean an API change in some of the core classes.

Thoughts?

**Comment by apfelbox** [comment]
I know that the `@Security`-Annotation is located in the SensioFrameworkExtraBundle, but as both libraries are affected, I want to have one discussion here for both.

**Comment by backbone87** [comment]
you can replace the security.role_hierarchy service definition in your own bundle:
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Resources/config/security.xml#L66
with your own service you can use another implementation of `RoleHierarchyInterface` supporting mutators.

**Comment by cH40z-Lord** [comment]
@backbone87 sure, though what do you do in the case where you have multiple bundles providing specific security features that don't know of each other and therefore can't be made compatible to extend/call each other?

IMO this is a major design flaw considered implementations in other components allow composition in a very easy way.

**Comment by apfelbox** [comment]
@backbone87 you can't, as you need to statically know all used RoleHierarchies in the system. Which currently isn't even possible, as the role hierarchies can be completely hidden inside a security voter.

Which would be fine… if it weren't for the issues described above.

**Comment by backbone87** [comment]
well role hierarchies are not a "first level" concept in the security component. from the userland view, you deal just with an authChecker. everything else is, like you said, subject to more or less sophisticated voters.

@cH40z-Lord the correct way is to decorate the service: moving the original service def, to a private service and replace the "original" service def, with a custom one, gettin the private service def injected. with this approach, every bundle can decorate the hierarchy as wanted und interact with their own "slice" to manipulate the hierarchy, but the voter just sees a "merged" top lvl impl of the interface.

**Comment by apfelbox** [comment]
@backbone87 I am well aware of this fact, that's why I don't suggest a bugfix, but rather a discussion, whether this is something to streamline.

Decorating the service is a way to go, although it seems like an not complicated, but neither very straight forward implementation. I will try to implement it that way, maybe I find more bumps along the road.

Doesn't void the discussion about maybe making the role system (including role hierarchies) a first level concept in the security bundle.

**Comment by robfrawley** [comment]
I don't consider decoration a great solution: it adds complexity and requires additional knowledge and burden to newcomers looking to implement their own voter implementation. As (arguably) the most important component of any application, as well as (often) the last/least well-understood by users, avoiding complexity in the Security component should be priority #2 (directly following #1: actual "security") --- even if decoration may be an "elegant" pattern from the perspective of a software engineer, dead-simple implementations are often more important, and you can't get any more simple than the current handling: a voter interface with a single method signature allowing for voters to be written with absolutely no knowledge of any other object).

I very much like the simplicity of compiler passes, a feature which newcomers would not need to understand to use (through service tags, obviously). It would be relatively painless to implement two value-store objects, say, `VoterRegistrar` and `RoleProviders`, that are registered with the container (obviously, a service tag for role providers would need to be introduced).

This sort of implementation would allow for augmenting the `AccessDecisionManager` and any other code without BC breaks by adding support for consumption of these collection objects while retaining the current behavior by resolving both down to a simple raw-array internally.

**Comment by robfrawley** [comment]
An additional thought to my previous comments:

The `RoleProviders` value object may be overkill as it is the responsibility of the voter cast a determination, based on whatever criteria it deems fit. Though very often this is a collection of roles, such is an implementation detail of the voter itself.

As such, I'm not sure exposing a collection of `RoleProviders` in a value object is helpful. Just spit-balling here, but voters themselves would need to be iterated over and offer a new method that returns a listing of their criteria for an accurate representation. I don't have any workable solution for achieving this, though.

**Comment by chalasr** [comment]
> On the security tab, the profiler displays the directly assigned roles, next to the inherited roles. The inherited roles are always empty.

This does not seem to be the case right now, maybe was it fixed meanwhile?
About the ExpressionVoter part, I don't know. 

Is this issue still relevant? Thanks

**Comment by xabbuh** [comment]
Let's close then. We can still reopen if it turns out to still be an issue.
