### ISSUE TITLE
validators.no.xlf error on clear cache after composer update

### ISSUE THREAD

**Issue by ibasaw** [symfony/symfony#17893]
[Symfony\Component\Translation\Exception\InvalidResourceException]
      Unable to load         "/var/www/sources/xxx/vendor/symfony/symfony/src/Symfony/Component/Validator/Resources/translations/validators.no.xlf": [ERROR 522] Validation failed: no DTD found ! (in n/a - line 2, column 21)
      [ERROR 76] Opening and ending tag mismatch: target line 207 and trans-unit (in n/a - line 208, column 27)
      [ERROR 76] Opening and ending tag mismatch: trans-unit line 205 and body (in n/a - line 317, column 16)
      [ERROR 76] Opening and ending tag mismatch: body line 4 and file (in n/a - line 318, column 12)
      [ERROR 76] Opening and ending tag mismatch: file line 3 and xliff (in n/a - line 319, column 9)
      [ERROR 77] Premature end of data in tag xliff line 2 (in n/a - line 320, column 1)

sf 2.8.3

**Comment by peterrehm** [comment]
Are you on the dev 2.8 branch as 2.8.3 is not yet released?

**Comment by ibasaw** [comment]
in my composer.json, got : "symfony/symfony": "2.8.*@dev",

**Comment by burci** [comment]
2.7 affected as well. There is a closing tg missing:

https://github.com/symfony/symfony/blame/ba35f3d7bb78e8dec2e73d2be4af6b070443e799/src/Symfony/Component/Validator/Resources/translations/validators.no.xlf#L207

**Comment by javiereguiluz** [comment]
@burci nice catch! I'm going to create right now a pull request to fix this.

**Comment by ibasaw** [comment]
didin't see it, and the line number are false, don't got 300 lines in this files.
