### ISSUE TITLE
Cache: AbstractAdapter.php file try set private vars

### ISSUE THREAD

**Issue by sergiors** [symfony/symfony#17895]
Hi everyone

I'm read the file: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L38

apparently the vars are private:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/CacheItem.php#L28

that's dont work, right?

ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
of course it works, tests pass :)
See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L36

**Comment by nicolas-grekas** [comment]
and http://php.net/manual/en/closure.bind.php

**Comment by sergiors** [comment]
Got it
