### ISSUE TITLE
Error: Maximum execution time of 30 seconds exceeded 

### ISSUE THREAD

**Issue by antondachauer** [symfony/symfony#17906]
Hi guys. I just got the message above. Can't understand it, it's the first time I got this error on a previously working system...

**Debugg-Messages**

    INFO - The class "JMS\DiExtraBundle\Config\FastDirectoriesResource" is performing resource checking through ResourceInterface::isFresh(), which is deprecated since 2.8 and will be removed in 3.0
    INFO - Matched route "pp_payment_upgrade_order".
    INFO - The "form.csrf_provider" service is deprecated since Symfony 2.4 and will be removed in 3.0. Use the "security.csrf.token_manager" service instead.
    INFO - The Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderAdapter class is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.
    DEBUG - Read existing security token from the session.
    DEBUG - User was reloaded from a user provider.
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\PaginatorBundle\Subscriber\SlidingPaginationSubscriber::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
    INFO - The pp\lib\BaseDoctrineService class extends Symfony\Component\DependencyInjection\ContainerAware that is deprecated since version 2.8, to be removed in 3.0. Use the ContainerAwareTrait instead.
    INFO - The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0.
    INFO - The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.
    INFO - The Symfony\Bundle\FrameworkBundle\Controller\Controller::getRequest method is deprecated since version 2.4 and will be removed in 3.0. The only reliable way to get the "Request" object is to inject it in the action method.
    INFO - The Symfony\Bundle\FrameworkBundle\Controller\Controller::getRequest method is deprecated since version 2.4 and will be removed in 3.0. The only reliable way to get the "Request" object is to inject it in the action method.
    WARNING - Translation not found.
    CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /var/www/viasenso/muttersystem/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 461
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\PaginatorBundle\Subscriber\SlidingPaginationSubscriber::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".

**Stacktrace** 

    [1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Maximum execution time of 30 seconds exceeded
        at n/a
            in /var/www/viasenso/muttersystem/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 461

**Installed packages (composer info)**

    bmatzner/leaflet-bundle              0.7.0              Leaflet Bundle for Symfony2
    doctrine/annotations                 v1.2.7             Docblock Annotations Parser
    doctrine/cache                       v1.6.0             Caching library offering an object-oriented API for many cache backends
    doctrine/collections                 v1.3.0             Collections Abstraction library
    doctrine/common                      v2.6.1             Common Library for Doctrine projects
    doctrine/data-fixtures               v1.1.1             Data Fixtures for all Doctrine Object Managers
    doctrine/dbal                        v2.5.4             Database Abstraction Layer
    doctrine/doctrine-bundle             1.6.2              Symfony DoctrineBundle
    doctrine/doctrine-cache-bundle       1.3.0              Symfony Bundle for Doctrine Cache
    doctrine/doctrine-fixtures-bundle    v2.2.1             Symfony DoctrineFixturesBundle
    doctrine/doctrine-migrations-bundle  1.0.1              Symfony DoctrineMigrationsBundle
    doctrine/inflector                   v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
    doctrine/instantiator                1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
    doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
    doctrine/migrations                  dev-master 0074c94 Database Schema migrations using Doctrine DBAL
    doctrine/orm                         v2.5.4             Object-Relational-Mapper for PHP
    friendsofsymfony/user-bundle         v1.3.6             Symfony FOSUserBundle
    gregwar/captcha                      v1.1.1             Captcha generator
    gregwar/captcha-bundle               v1.1               Captcha bundle
    imagine/imagine                      v0.6.3             Image processing for PHP 5.3
    incenteev/composer-parameter-handler v2.1.2             Composer script handling your ignored parameter file
    ircmaxell/password-compat            v1.0.4             A compatibility library for the proposed simplified password hashing algorithm: https://wiki.php.net/rfc/password_hash
    jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
    knplabs/knp-components               1.3.2              Knplabs component library
    knplabs/knp-menu                     v2.1.1             An object oriented menu library
    knplabs/knp-menu-bundle              v2.1.1             This bundle provides an integration of the KnpMenu library
    knplabs/knp-paginator-bundle         2.5.1              Paginator bundle for Symfony2 to automate pagination and simplify sorting and other features
    kriswallsmith/assetic                v1.3.2             Asset Management for PHP
    liip/imagine-bundle                  1.5.2              This Bundle assists in imagine manipulation using the imagine library
    monolog/monolog                      1.17.2             Sends your logs to files, sockets, inboxes, databases and various web services
    ocramius/proxy-manager               1.0.2              A library providing utilities to generate, instantiate and generally operate with Object Proxies
    paragonie/random_compat              v1.2.0             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
    psr/log                              1.0.0              Common interface for logging libraries
    sensio/distribution-bundle           v4.0.5             Base bundle for Symfony Distributions
    sensio/framework-extra-bundle        v3.0.13            This bundle provides a way to configure your controllers with annotations
    sensio/generator-bundle              v2.5.3             This bundle generates code for you
    sensiolabs/security-checker          v3.0.2             A security checker for your composer.lock
    stfalcon/tinymce-bundle              dev-master 22afe28 This Bundle integrates TinyMCE WYSIWYG editor into a Symfony2 project.
    swiftmailer/swiftmailer              v5.4.1             Swiftmailer, free feature-rich PHP mailer
    symfony/assetic-bundle               v2.7.1             Integrates Assetic into Symfony2
    symfony/monolog-bundle               v2.8.2             Symfony MonologBundle
    symfony/polyfill-intl-icu            v1.1.0             Symfony polyfill for intl's ICU-related data and classes
    symfony/polyfill-mbstring            v1.1.0             Symfony polyfill for the Mbstring extension
    symfony/polyfill-php54               v1.1.0             Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
    symfony/polyfill-php55               v1.1.0             Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
    symfony/polyfill-php56               v1.1.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
    symfony/polyfill-php70               v1.1.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
    symfony/polyfill-util                v1.1.0             Symfony utilities for portability of PHP codes
    symfony/security-acl                 v2.8.0             Symfony Security Component - ACL (Access Control List)
    symfony/swiftmailer-bundle           v2.3.11            Symfony SwiftmailerBundle
    symfony/symfony                      v2.8.2             The Symfony PHP framework
    twig/twig                            v1.24.0            Twig, the flexible, fast, and secure template language for PHP
    zendframework/zend-code              2.6.2              provides facilities to generate arbitrary code using an object oriented interface
    zendframework/zend-eventmanager      3.0.1              Trigger and listen to events within a PHP application

**Comment by jakzal** [comment]
@antondachauer did it start happening after you upgraded Symfony or just out of nowhere? 

We won't be able to assess if this is a Symfony bug with no steps to reproduce it. Could you provide a fork of Symfony standard edition with this issue reproduced with minimal amount of code please?

**Comment by backbone87** [comment]
just because the timeout occured while the propertyaccessor was used, doesnt mean this component is the cause. from what i see you are handling some paypal related work, which could induce that you use their API, which can be very slow or "hanging" form time to time. This could cause the php timeout.

**Comment by Tobion** [comment]
Closing as this too generic without steps to reproduce.
