### ISSUE TITLE
[3.0.2] Problem with authentification

### ISSUE THREAD

**Issue by falexis77** [symfony/symfony#17901]
I'm use data fixtures to register a user on database.
For the password, i use the service "security.password_encoder" to encode the password. I use pbkdf2 algorythm.
On action, i use the service security.authentication_utils.
But, i have the same error message "bad credentials".

**Comment by javiereguiluz** [comment]
Closing it as a a duplicate of your previous issue #17896.

I added a reply to your previous issue here: https://github.com/symfony/symfony/issues/17896#issuecomment-187626539
