### ISSUE TITLE
[DependencyInjection] Request for non existing service

### ISSUE THREAD

**Issue by michaoj** [symfony/symfony#17915]
Hi,

Since my project update to version 2.3.38-DEV, I have an error while trying to access my site 

```
PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException' with message 'You have requested a non-existent service "liip_imagine.gd".' in /home/joachim/Web/sit/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:307
Stack trace:
#0 /home/joachim/Web/sit/app/cache/dev/appDevDebugProjectContainer.php(4165): Symfony\\Component\\DependencyInjection\\Container->get('liip_imagine.gd')
#1 /home/joachim/Web/sit/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevDebugProjectContainer->getAssetic_AssetFactoryService()
#2 /home/joachim/Web/sit/app/cache/dev/appDevDebugProjectContainer.php(346): Symfony\\Component\\DependencyInjection\\Container->get('assetic.asset_f...')
#3 /home/joachim/Web/sit/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevDebugProjectContainer->getAssetic_AssetManagerService()
#4 /home/joachim/Web/sit/app/cache/dev/appDevDebugProjectContainer.php(2886): Symfony\\C in /home/joachim/Web/sit/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php on line 307
```

After searching, it looks like the problem occurs for all services with a public=false attribute

This issue seems to be related to this pull request
https://github.com/symfony/symfony/pull/17867

And the pending commit
https://github.com/symfony/symfony/commit/4b33fd3d453dd1846089e9a3d53e96dba8caffa5

If if comment the line 99 in 
` src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php `

or revert to version 2.3.37 everything works.

Thanks

**Comment by pborreli** [comment]
looks related to #17910, happens with `public="false"` services only

**Comment by xabbuh** [comment]
@michaoj Can you describe the steps that are necessary to reproduce your issue (best would be if you could fork the Symfony Standard Edition and make the needed changes)?

**Comment by michaoj** [comment]
@xabbuh Well, I could indeed fork Symfony Standard Edition but all I did was commenting a line which doesn't seem to be the best solution ;)

By the way, to reproduce this error, I just did a checkout on my project which includes bundles like liip/imagine-bundle or jms/serializer-bundle and then perform a composer install.

Hope this helps

**Comment by xabbuh** [comment]
@michaoj Well, we needed this line to fix another bug.

Maybe that change was not enough to fix the issue entirely, but as long as we cannot reproduce your issue, we are unable to fix it the right way.

**Comment by michaoj** [comment]
@xabbuh Ok, I will try to go down the root of the problem then. Thanks

**Comment by WouterJ** [comment]
See https://github.com/WouterJ/symfony/commit/be61610674492b71a30080f1a60ccb396b2be5f0 for a failing test case proofing this bug. It involves having a private aliased service that is created by a factory service. Please note that the bug exists for both the old and new factory API.

**Comment by WouterJ** [comment]
Status: Reviewed

**Comment by WouterJ** [comment]
I'm sorry, that test case was proofing something completely irrelevant. In order to reproduce this issue:

 * On a fresh Symfony install (dev-2.8)
 * Add a service config like this:
   ```yaml
   services:
     app.demo:
       class: Doctrine\ORM\EntityManager
       factory_service: doctrine
       factory_method: getManager
   ```

Now, somewhere in a controller use `$this->get('app.demo')`.
