### ISSUE TITLE
[Routing] No route found for an optional parameter

### ISSUE THREAD

**Issue by mheki** [symfony/symfony#17917]
According to http://symfony.com/doc/current/book/routing.html#required-and-optional-placeholders I should be able to have an optional parameter by setting it's default value in `defaults`. 
This seems not working for me anymore.
I was playing with the symfony standard edition as well as vanilla symfony in version 3.0.2

Tested on annotation as well as a yaml routing:
```
blog:
   path: /blog/{page}
   defaults:  { _controller: AppBundle:Default:blog, page: 1 }
```
Running:  `bin/console router:match /blog/2` I get:
![screen shot 2016-02-24 at 15 28 58](https://cloud.githubusercontent.com/assets/2435655/13290416/64e1f6d6-db0b-11e5-9fa0-11e92a195b7a.png)
But ` bin/console router:match /blog/`
gives:
```
[ERROR] None of the routes match the path "/blog/"   
```

**Comment by jakzal** [comment]
see the explanation here https://github.com/symfony/symfony/issues/5869#issuecomment-9911133

**Comment by mheki** [comment]
yeah... makes sense. Thanks @jakzal
