### ISSUE TITLE
JsonResponse setCallback throws InvalidArgumentException on valid callback

### ISSUE THREAD

**Issue by Donool** [symfony/symfony#17923]
Using Symfony 3.0, trying to set a callback on a JsonResponse fails for the following callback: **Utils.callbacks[1]**. 

The pattern in setCallback `^[$_\p{L}] $_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]*+$/u` fails on anything containing brackets while this could be a valid callback.

This works for me `^[$_\p{L}][$_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\.]*+(\x{5b}\S+\x{5d})*$`. This allows callbacks like foo.bar[1] but not foo.bar[].

**Comment by xabbuh** [comment]
Can you provide an example that fails for you?

**Comment by stof** [comment]
See https://github.com/willdurand/JsonpCallbackValidator for the implementation of the proper validation to accept valid callbacks

**Comment by Donool** [comment]
I'm requesting mywebsite.com/function?callback=L.OWM.Utils.callbacks[9].

My functions 
`$callback = $request->get('callback');
......
        $response = new JsonResponse($result);
        $response->setCallback($callback);
return $response;`

But it's giving me an InvalidArgumentException on the part **callbacks[9]** in the setCallback().

Is this example enough?
