### ISSUE TITLE
[FileSystem] tempnam doesn't work on Google App Engine

### ISSUE THREAD

**Issue by swordbeta** [symfony/symfony#17922]
Hi,

In the FileSystem component the `x+` mode is used to create a temporary file. This is sadly not supported by Google App Engine. GAE only supports these modes: r, rb, rt, w, wb, wt. (https://cloud.google.com/appengine/docs/php/googlestorage/advanced#php_filesystem_functions_support_on_google_cloud_storage)

The line in question: https://github.com/symfony/symfony/blob/1b857996029b1aecfa393b7b6a92653cc3873363/src/Symfony/Component/Filesystem/Filesystem.php#L511

Could this perhaps be changed in the component? I understand the use of the `x+` mode here is to prevent a TOCTOU vulnerability, but I need to change this to get symfony working in GAE.

I have a 'fix' (Adding `gs` to this line https://github.com/symfony/symfony/blob/1b857996029b1aecfa393b7b6a92653cc3873363/src/Symfony/Component/Filesystem/Filesystem.php#L489) but it is certainly not a fix that we need merged in the Symfony component. I'm new to Symfony and I don't see how I would extend the component without forking the repository.

**Comment by javiereguiluz** [comment]
@swordbeta do you know if there is a way to detect reliably and unequivocally if the application is running in Google's PHP instead of standard PHP? We make some changes to adapt our code to HHVM (thanks to `if (defined('HHVM_VERSION')) { ... }`) so maybe we could do the same here.

**Comment by swordbeta** [comment]
@javiereguiluz Perhaps the `GOOGLE_APPENGINE_CLASSLOADER` constant, I'm just not too sure how reliable it is.

**Comment by Tobion** [comment]
> but I need to change this to get symfony working in GAE.

Which part of symfony requires the Filesystem::tempnam internally that makes symfony not work on GAE?

**Comment by pvaass** [comment]
@Tobion The exact error when running a default symfony-standard install (without the fix) is
```
Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'A temporary file could not be created.' in /www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:524 
Stack trace: 
#0 /www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(547): Symfony\Component\Filesystem\Filesystem->tempnam('gs://david/symf...', 'appProdProjectC...') 
#1 /www/app/bootstrap.php.cache(3088): Symfony\Component\Filesystem\Filesystem->dumpFile('gs://david/symf...', '<?php?use Symfo...', NULL) 
#2 /www/app/bootstrap.php.cache(2784): Symfony\Component\Config\ResourceCheckerConfigCache->write('<?php?use Symfo...', Array) 
#3 /www/app/bootstrap.php.cache(2696): Symfony\Component\HttpKernel\Kernel->dumpContainer(Object(Symfony\Component\Config\ConfigCache), Object(Symfony\Component\DependencyInjection\ContainerBuilder), 'appProdProjectC...', 'Container') 
#4 /www/app/bootstrap.php.cache(2473): Symfony\Component\HttpKernel\Kernel->initializeContainer() # in /www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 524
```

**Comment by swordbeta** [comment]
@javiereguiluz `$_SERVER['SERVER_SOFTWARE']` is always `Google App Engine`, so something along the line of `if (0 === strpos($_SERVER['SERVER_SOFTWARE'], 'Google App Engine')...` might be the way to go.

**Comment by xabbuh** [comment]
What is the alternative to `tempnam()` with GAE then?

**Comment by swordbeta** [comment]
@xabbuh `tempnam()` works on GAE, `FileSystem::tempnam` does not because of the `x+` flag in `fopen`.
