### ISSUE TITLE
Yaml::parse() incorrectly guesses some strings as floats

### ISSUE THREAD

**Issue by lividgreen** [symfony/symfony#17924]
We faced the problem that values like `23e2345` are parsed by Yaml::parse() as floats instead of string. Looks like the parser recognizes them as "float" despite the value doesn't pass the scientific notation: http://www.yaml.org/spec/1.2/spec.html#id2804092

Example:
```php
$source = <<<EOT
str: 23e2345
EOT;

$yml = Symfony\Component\Yaml\Yaml::parse($source);

echo $yml['str']; // prints "INF" instead of "23e2345"
```
This bug is very annoying when you are trying to store some hashes in yaml (like git short revision) that can appear sometimes in form of `[0-9]+e[0-9]+`.

BTW, ruby parses it as string.

**Comment by stof** [comment]
The spec gives a different regex a few lines below though: http://www.yaml.org/spec/1.2/spec.html#id2805071

**Comment by lyrixx** [comment]
Related to https://github.com/symfony/symfony/issues/10396 ?

**Comment by xabbuh** [comment]
Indeed, returning this as a string look like a bug in the Ruby YAML parser.
