### ISSUE TITLE
2.7 -> 2.8 | delete all depreciations

### ISSUE THREAD

**Issue by Kraguesh** [symfony/symfony#17934]
Hi everyone,

I update my project 2.7 to 2.8. I wanted to correct all depreciations but I don't understand thos on Form.

My form:
```php

namespace Eolas\AdvizBundle\Domain\Dashboard;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class DashboardType extends AbstractType
{
    public function __construct($aOrder = array(), $type, $deleteAllowed)
    {
        $this->aOrder = $aOrder;
        $this->type = $type;
        $this->deleteAllowed = $deleteAllowed;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $deleteAllowed = $this->deleteAllowed;
        $builder
            ->add('label', TextType::class,
                    array(
                    'required' => true,
                    'attr' => array('class' => ' form-control'),
                    'label' => 'attribut.general.label',
                    'pattern' => '^[^\s].*',
              ))
            ->add('order', ChoiceType::class,
                    array(
                    'choices'   => $this->aOrder,
                    'required' => true,
                    'attr' => array('class' => ' form-control select-trim'),
                    'label' => 'attribut.general.order2'
            ))
            ->add('save', SubmitType::class, array(
                    'label' => 'action.save',
                    'attr' => array('class' => 'btn btn-success fieldButtonClass')
                ));
        if ($builder->getData()->getId() && $deleteAllowed) {
            $builder->add('deleteConfirm', 'submit', array ('label' => 'action.delete','attr' => array('class' => 'btn btn-danger fieldButtonClass deleteConfirmBlock')));
        }
    }

    public function getBlockPrefix()
    {
        return 'eolas_advizbundle_dashboard';
    }
}
```

I don't know what to do with : 

- 'Passing type instances to FormBuilder::add(), Form::add() or the FormFactory is deprecated since version 2.8 and will not be supported in 3.0. Use the fully-qualified type class name instead (Eolas\AdvizBundle\Domain\Dashboard\DashboardType)' How to pass my params without new Type(...) like : `$form = $this->createForm(new DashboardType($data, $type, false), $oDashboard, array(...`

- 'The value "false" for the "choices_as_values" option of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.8 and will not be supported anymore in 3.0. Set this option to "true" and flip the contents of the "choices" option instead'

- 'The Symfony\Component\Form\ChoiceList\ArrayKeyChoiceList class is deprecated since version 2.8 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead'

Thanks for help

**Comment by javiereguiluz** [comment]
@Kraguesh in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

In addition, you may read the [UPGRADE to Symfony 3.0 guide](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) which explains how to solve most of this deprecations.
