### ISSUE TITLE
[travis] No memcache extension loaded for PHP7

### ISSUE THREAD

**Issue by ymc-dabe** [symfony/symfony#17945]
> Follow-up on #16215, related to #17873 and websupport-sk/pecl-memcache#7

It looks like travis does not load a memcache extension for PHP7. A memcache extension for PHP7 can be found at [websupport-sk/pecl-memcache](https://github.com/websupport-sk/pecl-memcache/tree/php7), but using this one makes a test in the HttpFoundation component fail (see #17873).

FWIW: Debian currently has packaged https://github.com/websupport-sk/pecl-memcache/commit/fdbd46bbc6f53ed6e024521895e142cbfc9b3340 for [sid](https://packages.debian.org/sid/php-memcache) and [stretch](https://packages.debian.org/stretch/php-memcache).

Thanks for (re-)considering enabling the memcache extension in travis for php7.

**Comment by robfrawley** [comment]
It is worth noting that the above referenced Memcached repository contains code that doesn't pass its own tests via `make test` on PHP 7.

Same goes for https://github.com/memcached/memcached and https://github.com/php/pecl-caching-memcache (the lack of standardized PECL development practices in combination with the friction many received on the internals mailing list when requesting a repo within the github/php namespace has caused quite a frustrating mess for many extensions).

It is likely to be both a frustrating and fruitless effort to try regularly patching Symfony against multiple copies of the extension, all with (mostly) intersecting, but often forked states of readiness, until a stable release is posted (or, at the very least, it passes its post-build `make` tests). This is coming from someone who *really wants solid support* for Memcached in PHP 7 --- but we should not work to implement fixes in Symfony for incomplete and untested extensions, IMHO.

**Comment by nicolas-grekas** [comment]
Travis now uses memcached.so on PHP7, and adds memcache.so on PHP5.
If something is missing, please submit a PR :)
