### ISSUE TITLE
.gitignore updates for 3.0

### ISSUE THREAD

**Issue by moorea5551** [symfony/symfony#17948]
I created a test application today using 3.0 and noticed that the default .gitignore file hasn't been updated to support  the new directory structure in Symfony3.  I will open a pull request to address the issue.

**Comment by moorea5551** [comment]
I opened PR #17949 to address this.

**Comment by robfrawley** [comment]
I think you have confused the symfony source (this repo) with the symfony standard edition distribution (at symfony/symfony-standard). You'r looking for this https://github.com/symfony/symfony-standard/blob/master/.gitignore which is current.

**Comment by moorea5551** [comment]
@robfrawley you're right thanks.
