### ISSUE TITLE
[Translation] Unable to replace Translator class

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#17957]
Hey,

as we're using Gettext for a project I tried to replace the default Translator class to solve our issues with constraint localization. With Gettext we don't need all the good stuff from the default service. So I wrote a class implementing the `Symfony\Component\Translation\TranslatorInterface` and configured the app to use it instead of the default:

``` yaml
parameters:
    translator.class: Acme\HelloBundle\Translation\GettextTranslator
```

Now PHP dies with a missing method error:

> Fatal error: Call to undefined method Acme\HelloBundle\Translation\GettextTranslator::setFallbackLocales() 

This probably happens due to the app config:

``` yaml
framework:
    translator: { fallback: "en" }
```

... but removing the fallback setting doesn't fix the issue. For me this is somehow inconsistent. Isn't the interface definition incorrect that way? Do I miss something? The method is called in the dumped cache files at `getTranslator_DefaultService`.

**Edit:** Working around that issue leads to a missing `TranslatorBagInterface` as a complaint from the `DataCollector`. :(

Cheers
Matthias

**Comment by Ener-Getick** [comment]
This error comes from [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L665).
I don't know if this should be considered as a bug or if you should extend the base ``Translator`` class.

**Comment by backbone87** [comment]
you shouldnt use the parameter to just swap out the service implementation. creating your own service and properly configuring and injecting it (overriding the translator service alias to point to your translator service, insteadof the "translator.default" service), is "cleaner".

**Comment by xabbuh** [comment]
@backbone87 is right about the fact that you shouldn't replace a service just by changing its class parameter (we removed them in 3.0 by the way).

@althaus You wrote that you worked around it and ran into other problems. Can you confirm that just replacing the `translator` alias to point to your own implementation doesn't work neither?

**Comment by althaus** [comment]
@backbone87 @xabbuh Overriding the `translator.class` parameter is the example in the cookbook and the first hit on Google:

http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration

So if I shouldn't do it, it shouldn't be documented? ;-)


I've now changed my config to

```yaml
services:
    translator:
        class: Acme\HelloBundle\Translation\GettextTranslator
```
In the dev env the translator is now a `DataCollectorTranslator` decorating my `GettextTranslator`. So far so good.

I can now remove the `setFallbackLocales` method, but it still requires explicit support for the data collector:

>Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The Translator "Acme\HelloBundle\Translation\GettextTranslator" must implement TranslatorInterface and TranslatorBagInterface.' in /acme/vendor/symfony/symfony/src/Symfony/Component/Translation/DataCollectorTranslator.php:39

**Comment by stof** [comment]
@althaus please open an issue to the doc repo asking to change this doc, as it is indeed the wrong way to override services (which is why we removed all these parameters in 3.0).

> I can now remove the setFallbackLocales method, but it still requires explicit support for the data collector:

The DataCollectorTranslator indeed requires both interfaces to be able to work. Otherwise, it is not possible to build the translator panel. And FrameworkBundle does not have a way to ask it not to configure the translator panel of the profiler while activating others, so the best way is indeed to support it.

**Comment by backbone87** [comment]
well at least the error description is now better. i guess the implementation of `TranslatorBagInterface` is missing in his gettext translator. i would suggest to just implement this interface, if it is nott too complex.

**Comment by althaus** [comment]
@backbone87 Yes, I removed the additional interface for testing this issue. It's working with a dummy implementation although it doesn't offer any usefull information in the profiler for us.

**Comment by backbone87** [comment]
The only thing left from this issue is the fact that the FrameworkBundle expects the `translator` service to be decorateable by the DataCollectorTranslator. IMO the FrameworkBundle should only try to decorate the `translator` service, if it implements both interfaces and issue a notice, if it cant.

**Comment by javiereguiluz** [comment]
Should we close this issue as "fixed" ?

1) The mentioned doc has already been updated since this report: http://symfony.com/doc/current/bundles/override.html#services-configuration

2) The constructor of `DataCollectorTranslator` already makes a check about the translator class:

```php
if (!$translator instanceof TranslatorBagInterface) {
    throw new InvalidArgumentException(sprintf('The Translator "%s" must implement TranslatorInterface and TranslatorBagInterface.', get_class($translator)));
}
```

**Comment by backbone87** [comment]
Yes the `DataCollectorTranslator` does his argcheck, but the FrameworkBundle shouldnt attempt to decorate an arbitrary `TranslatorInterface` with a `DataCollectorTranslator`.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L370
This shouldnt be done without checking if the `translator` service implements `TranslatorBagInterface`

**Comment by xabbuh** [comment]
@althaus @backbone87 Can you try out #21637?
