### ISSUE TITLE
a "+" appears in all responses on 2.7.10

### ISSUE THREAD

**Issue by compains** [symfony/symfony#17955]
Just upgraded on Production environment and it started to fail. This "+" appears even on api calls making json responses useless. Downgraded to 2.7.9 and everything worked again.

**Comment by jakzal** [comment]
I don't see this happening in a fresh installation of Symfony 2.7.10. Unless you can provide steps to reproduce your issue, I'll have to assume the issue's in your application.

**Comment by compains** [comment]
The steps where:

- Update on production machine with capifony (composer update, clear cache and so on)
- Noticed that the application upgraded from 2.7.9 to 2.7.10 and installed new dependency, I don't remember the exact name but started with apc)
- A "+" started to appear in all pages just after opening <body>
- A "+" started to apear in all json calls to a backend also working on Symfony 2.7.9. These calls are done from the app using Guzzle. (The browser ask for a resource to the app, the app request from the back end with Guzzle, and forwards the data json encoded to the browser)
- Checked and confirmed that the backend is not producing the "+" making direct calls to the api.
- Downgraded to 2.7.9 and everything worked again.

So it seems that somewhere during the build process of the response a "+" symbol is injected in the response (independently of it's html or json)

No changes on the application done.

**Comment by jakzal** [comment]
@compains we don't have access to your application. You'll need to provide steps how to reproduce this issue in a standard symfony edition project.

**Comment by javiereguiluz** [comment]
@compains it's been two days and we have received no other complaints about this. And our test suite passes without errors. So it's very unlikely that this is a Symfony issue.

Maybe some patch/diff went wrong and a leading `+` was left somewhere by mistake? Can you try to find with your IDE or editor all the `+` characters in the source code of your application to see if you find something wrong? Thanks!

**Comment by jakzal** [comment]
In the meantime I'll close this issue.  @compains feel free to provide more information and we'll reopen if this is proved to be a problem with Symfony. To be honest this is highly unlikely as we'd have far more bug reports like this.

**Comment by compains** [comment]
We have rolled back to 2.7.9 (and forced Symfony to stay there) and continued with our roadmap. No plans to upgrade again to 2.7.10. If we do, well test it on pre-production and inform about any issue.

@javiereguiluz no missing `+` were found in the app. Neither in php classes or twig files. As this symbol appeared in html pages and json responses seems to be related with the response management.

Thanks for your answers.
