### ISSUE TITLE
TemplateNameParser breaks compatibility in 2.7.10

### ISSUE THREAD

**Issue by hcomnetworkers** [symfony/symfony#17958]
Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser received a new regular expression in 2.7.10, breaking the use of template names that are not in Resources/views.

E.g. a template in "src/My/SuperBundle/Whatever/Template.html.twig" could be found with "@MySuperBundle/Whatever/Template.html.twig" as template name until 2.7.9.

As of 2.7.10 the new regex in the TemplateNameParser matches said template name and thus does not use the parent's parse method of Symfony\Component\Templating\TemplateNameParser effectively not finding the template anymore.

This should not have happened in a minor release.

**Comment by robfrawley** [comment]
Duplicate. See pull request #17894 and issue #17683.

**Comment by hcomnetworkers** [comment]
Thanks
