### ISSUE TITLE
symfony 2.8 form entity type can not dynamic add choice?

### ISSUE THREAD

**Issue by Dam-Deng** [symfony/symfony#17967]
Recently I try to upgrade the symfony from 2.6 to 2.8 ,then I met a problem .
That Country that I have a large data, so I have to get the all data use a API .

Example:
```php
$builder->add('Country', 'entity', array(
                'class' => 'AdminBundle:Country',
                'required' => true,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('q')
                        ->setMaxResults(1);
                }
            ))
```

```javascript
$.get(path, {slug: 'Country'}, function (json) {
    if (typeof json.length == 'undefined') {
    } else if (typeof json != 'undefined') {
        var $countrySelect = $('#app_form_Country');
        $countrySelect.html("<option value=''>---</option>");
        $countrySelect.select2({
            data: json
        });
    }
}, 'json');
```

so that I can loading data asynchronously.
But , when I select a country and submit the form , the form is not valid, and show up this error: This value is not valid!

**But It is work in symfony 2.6!
And It is not work in symfony 2.8!**

Hope your known my mean.Thx

**Comment by HeahDude** [comment]
Hi, @Dam-Deng, if you think t's a bug, could you explain how in the process of the form you add the choice ?

**Comment by Dam-Deng** [comment]
Hi @HeahDude ,  sorry  ,It's the first time use the github issues, so I do some mistake ,HAHA.
Whatever, I update my problem description. Hole your can help me. Thx.

**Comment by HeahDude** [comment]
Are you using symfony 2.8.3 released yesterday ?

**Comment by Dam-Deng** [comment]
Yes , I am using PHP 7.0.1 and Symfony 2.8.3 now

**Comment by HeahDude** [comment]
Could you please try the code below ?

```php
$builder->add('Country', 'entity', array(
    'class' => 'AdminBundle:Country',
    'required' => true,
    'choice_value' => function ($entity) {
        return $entity;
    },
    'query_builder' => function (EntityRepository $er) {
        return $er->createQueryBuilder('q')
            ->setMaxResults(1);
    }
))
```

**Comment by Dam-Deng** [comment]
I try your code and still not work.

In addition, If I not set the `query_builder ` and not use API ,It will be work

**Comment by HeahDude** [comment]
Ok then please now try :

```php
$builder->add('Country', 'entity', array(
    'class' => 'AdminBundle:Country',
    'required' => true,
    'choice_value' => function ($entity) {
        if (null !== $entity) {
            return $entity->getTheSameHtmlValueYouGotIn2_6();
        }
    },
    'query_builder' => function (EntityRepository $er) {
        return $er->createQueryBuilder('q')
            ->setMaxResults(1);
    }
))
```

If the values you got in 2.6 are numeric indexes do the following :

```php
$i = 0;
$builder->add('Country', 'entity', array(
    'class' => 'AdminBundle:Country',
    'required' => true,
    'choice_value' => function () use ($i) {
        if (null !== $entity) {
            return $i++;
        }
    },
    'query_builder' => function (EntityRepository $er) {
        return $er->createQueryBuilder('q')
            ->setMaxResults(1);
    }
))
```

**Comment by Dam-Deng** [comment]
It still not work...

But I have to say something,
If my `query_builder ` get the result is return `UK`, and then I select the `UK` ,It's work.
But If I select other value ,such as `US` or 'CN' ( It get form the API ),  Its not work, and 

Submitted Data in symfony 2.8 toolbar
> Property	                 Value
> View Format                  CN
> Normalized Format       **null**
> Model Format	          same as normalized format

But  in symfony 2.6 toolbar is follow
Submitted Data
> Property	                 Value
> View Format                  CN
> Normalized Format       **Object(AdminBundle\Entity\Country)**
> Model Format	          same as normalized format

**Comment by webmozart** [comment]
Hi @Dam-Deng, thank you for reporting this issue! :) Unfortunately this is not a bug. Limiting the query builder to 1 means that your choice field allows to select precisely one choice. I understand that you worked around this somehow in 2.6, but this is not some functionality that is officially supported by the component, so we cannot guarantee BC either.

I would recommend to add an empty choice field by default and override it with a populated one (no limit) in a PRE_SUBMIT event listener.
