### ISSUE TITLE
Use protected vs private variables in Profiler.php and EnvParametersResource.php

### ISSUE THREAD

**Issue by mmucklo** [symfony/symfony#17966]
Recently I've had the need to override Profiler (in order to export the hash used), and EnvParametersResource (in order to do a clever dotenv integration).

I'm finding that overriding these classes requires me to copy quite a few private variables.

e.g.

``` php
class EnvParametersResource implements SelfCheckingResourceInterface, \Serializable
{
    /**
     * @var string
     */
    private $prefix;

    /**
     * @var string
     */
    private $variables;
```

Could I request that these private member variables be made protected to allow people to easily extend these classes without a lot of copy/paste or code duplication?

**Comment by stof** [comment]
Well, we use private by default everywhere, because anything protected must then be covered by our BC policy, and BC layer for inheritance are the worse to implement, making it a maintenance nightmare.
So we won't be increasing visibility without a clear explanation of the use case (allowing us to decide whether there is a better way to handle this use case rather than switching to protected). Without such use case, you can still request such change, but it will be rejected.

**Comment by mmucklo** [comment]
So for EnvParametersResource -

   It would be nice to able to customize the isFresh() function to look at the timestamp of a **.env** file in root of the source tree.

For Profiler.php -

   I'd like to get access to the hash produced so that it could possibly be used to generate a profiler URL out of band (such as in an API request that returns json where you don't have the luxury of styles and javascript to popup the profiler bar).

**Comment by stof** [comment]
@mmucklo to check a file timestamp, use a FileResource instead.

For the case of an API, Symfony already adds the link to the profiler in a header.

**Comment by javiereguiluz** [comment]
I'm closing this as fixed by the solutions provided by @stof in this last comment. @mmucklo if you don't agree, please reopen. Thanks!

**Comment by mmucklo** [comment]
@javiereguiluz - I actually don't have permission to reopen, nevertheless in reply to @stof - 

For the EnvParametersResource - I'd have to check to see if a FileResource would work in its stead.
For the Profiler - I'd actually like to return the URL link to the profiler in the json of the response.

There are times when I've tried to troubleshoot an API request, and typically this might be done by doing a browser request of the API endpoint.  There are browser plugins that will format the returned json (such as [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en)).

It's convenient to then be able to click on the profiler link right in the browser, rather than having to open the network tab and search the header if it's returned there.
