### ISSUE TITLE
UniqueEntityValidator in SingleTableInheritance

### ISSUE THREAD

**Issue by Nemo64** [symfony/symfony#17962]
I have multiple kinds of entities within a single table inheritance. The UniqueEntityValidator fails in that scenario as it uses `get_class($entity)`. It instead should use the class on which it is defined.

Example:
```PHP
/**
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string", length=15)
 * @UniqueEntity(fields={"email"})
 */
class User {
    /** @ORM\Column(type="string") */
    private $email;
}
```

```PHP
class Collaborator extends User {}
```

Validating the `Collaborator` will now only check for other `Collaborator`s with the same email.

I'm using symfony `2.7.10`.

**Comment by iltar** [comment]
I think you're correct, the validator uses the following checks: 
 - `$class = $em->getClassMetadata(get_class($entity));`
 - `$repository = $em->getRepository(get_class($entity));`

Do you happen to have a different repository defined? You could try to see if the `repositoryMethod` in the constraint will fix this for you.

**Comment by Nemo64** [comment]
@iltar Why should it? It would then call the repository method on the `CollaboratorRepository`. I could probably create a method there which would also return normal `User`s but that wouldn't be really nice would it? ;)

**Comment by iltar** [comment]
@Nemo64 I'm just proposing possible solutions to get your code running. If your entities share the same repository, it shouldn't matter. If they have a different repository, you might want to define the one of the parent entity/class to be the correct one.

**Comment by Nemo64** [comment]
@iltar I know and thanks for that. I hope I don't sound harsh, that wasn't my intention.

But I have the feeling i'm missing something. The `UniqueEntityValidator` uses `->getRepository(get_class($entity))`. Therefor doctrine will create an instance of `EntityRepository`  which is configured to give me instances of that class. I can overwrite that class to so doctrine creates a  `UserRepository` but that won't change the configuration done by doctrines repository factory. The validator will use `->getRepository("Collaborator")` and get a Repository that will only return `Collaborator`s unless i create a method that'll ignore the configuration of that repository.

**Comment by craue** [comment]
Is this considered to be a bug and will be fixed or do I have to add a custom validator instead?

@Nemo64, in your code example, `@UniqueEntityValidator` should be `@UniqueEntity` instead.

**Comment by Nemo64** [comment]
@craue you are right, didn't notice. I updated the example. thanks.

**Comment by ogizanagi** [comment]
Related to #15002 (+issues) and #16969 (+PRs: #16978 & #16981)

**Comment by ogizanagi** [comment]
#15002 is merged and allow to select and fix the repository to use. See https://github.com/symfony/symfony-docs/pull/7057 for the documentation (maybe it can be improved thanks to you)
