### ISSUE TITLE
assets:install => resolve symlink

### ISSUE THREAD

**Issue by Preovaleo** [symfony/symfony#17975]
hi,
I want to add a feature to resolve symlink in the Ressources/public directory
for example :

I want to add the components/jquery package in my project
i can add a package which have a symlink for example

> /vendor/xxx/jqueryBundle/Ressources/public/jquery.min.js 
> => ../../../../components/jquery/jquery.min.js

and when i do assets:install (Hard copies mode) it will copy

> /vendor/components/jquery/jquery.min.js
> => /web/bundles/xxx/jquery/jquery.min.js

What do you think about that?
Have a nice day !

**Comment by maryo** [comment]
I've made this as a composer script (requires php7)
https://github.com/vaniocz/symlink-handler

But your idea is not bad, not sure where it fits better.

**Comment by jakzal** [comment]
@Preovaleo it's not clear what you're asking for. Please provide an expanded explanation :)

**Comment by Preovaleo** [comment]
The final goal of my project is make a bundle that depend on for example jquery.
This new bundle have a `/ressources/public/` dir. It contains a symlink to the jquery file in the jquery package.
The advantage of this technique is that we don't need to maintain a bundle with jquery in it, because i can use the` components/jquery` package

The thing that maryo use work great but i think it can be a native command

Théo

**Comment by fabpot** [comment]
Closing this old issue as I don't need something like this in Symfony core.
