### ISSUE TITLE
[Form] required false default option overrides children specific required option

### ISSUE THREAD

**Issue by gadelat** [symfony/symfony#17970]
```php
class SimpleForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('testField', TextType::class, [
            'required' => true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('required', false);
    }
}
```
When called createView, symfony will create 'testField' with required false, even though we specified it's true. "Default" required option in this case overrides field specific option.

This doesn't happen in reverse (default true, field option false).

Tested on Symfony 2.7 and Symfony 3.0.3

**Comment by iltar** [comment]
One possible option could be that the parent is not required thus the child cannot be required, but I'm not sure if that's the case.

**Comment by gadelat** [comment]
@iltar seems to be correct assumption

**Comment by webmozart** [comment]
@iltar Yes, that's correct.

It's a matter of perspective: If you add an embedded form to an outer form and set `required` to `false` for the embedded form, then *none* of the fields in the embedded form should be required, no matter what their actual configuration is.

I understand that you could see this from the perspective that you are describing here too, but we decided to take another route. Unfortunately we can't support both.
