### ISSUE TITLE
onKernelException response replacement

### ISSUE THREAD

**Issue by aferrandini** [symfony/symfony#17983]
When an `onKernelException` event is fired, if you set a new `Response` the response content is replaced but the status code is not replaced.

```yaml
# services.yml
services:
    ...
    exceptions_listener:
        class: Ferrandini\TestExceptionsBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
```

```php
// ExceptionListener.php
<?php

namespace Ferrandini\TestExceptionsBundle\Listener;

use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
use Symfony\Component\HttpFoundation\Response;

class ExceptionListener 
{
    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        $event->setResponse(new Response('Replace exception with 200 response', 200));
    }
}
```

When you request a route that generates `404` status code, the response should be replaced  with a `200` status code response, but this is what happens:

```bash
$ curl -v "http://localhost:8000/this/route/doesnt/exists/"
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /this/route/doesnt/exists/ HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Host: localhost:8000
< Connection: close
< X-Powered-By: PHP/5.6.6
< Cache-Control: no-cache
< Content-Type: text/html; charset=UTF-8
< X-Debug-Token: 1328ad
< X-Debug-Token-Link: /_profiler/1328ad
< Date: Wed, 02 Mar 2016 08:15:04 GMT
<
* Closing connection 0
Replace exception with 200 response
```

As you can see, the response content is replaced but the response status code is still `404`.

**Comment by javiereguiluz** [comment]
Apparently you can solve this issue with a magic feature provided by Symfony via the `X-Status-Code` HTTP header (see https://github.com/symfony/symfony/issues/12343) Maybe we should work to finally remove this magic feature as proposed by @Tobion.

**Comment by aferrandini** [comment]
Thank you @javiereguiluz maybe we should argue if this is how it should work or if this is an issue and how can we solve it.

**Comment by aferrandini** [comment]
Sorry, the documentation shows how to solve the issue.

http://symfony.com/doc/current/reference/events.html#kernel-exception

**Comment by jakzal** [comment]
Closing as this is currently an expected behaviour and we already have a ticket to discuss chaning it (#12343).
