### ISSUE TITLE
[Serializer] Allow to pass flags to XmlEncoder

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#17987]
Ever since we upgraded our server, libxml was upgraded to `2.9`, which introduced a protection on [the max text length](http://www.xmlsoft.org/html/libxml-parserInternals.html#XML_MAX_TEXT_LENGTH). 

We have one single route for which we want to add `LIBXML_PARSEHUGE` to the `XmlEncoder`, because an external party delivers us huge text nodes. Our problem is that the decoding happens (and makes the application crash) pre-controller in the `FOS\RestBundle\EventListener\BodyListener:114`. See #17956 and #16873 for more background information. What should be done to solve this:

* Make `XmlEncoder` flags configurable, as @dunglas proposes in https://github.com/symfony/symfony/pull/17956#issuecomment-190377991
* Allow `FrameworkBundle` to configure these flags on a specific route, maybe @nicolas-grekas can elaborate on what he meant in https://github.com/symfony/symfony/pull/17956#issuecomment-191322867.  
* That configuration should be applied before the `BodyListener` is executed. [It has priority 10 on `kernel.request`](http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#priorities).

**Comment by dunglas** [comment]
I've opened a pr to make the encoder configurable: #18036

However I'm not sure that exposing this configuration trough the framework bundle is a good idea: changing options globally through this configuration option will impact all usages of this encoder. For instance if someone enable non-safe options to fit its own need with a custom development, it will also impact API Platform that uses encoders registered by the bundle.
IMO it's better to encourage option to register a new instance of the encoder with custom options than changing globally options of all encoders.
If there are use cases where options should be changed globally, the service definition of the default encoder can be easily overridden in the `app/config/services.yml` file.

**Comment by rvanlaak** [comment]
@dunglas agree with you, my usecase just concerns a single route. If your PR and overriding or decorating the `BodyListener` via `services.yml` will be able to solve this I'm fine with that. :+1:

**Comment by rvanlaak** [comment]
We can override the setting once this PR is fixed?
