### ISSUE TITLE
Case mismatch between class and real file names on mac os x

### ISSUE THREAD

**Issue by macintoshplus** [symfony/symfony#17989]
Hi,

I just update to SF 2.8.3 and my project does not work anymore.
This exception is throws on some file.
```
Case mismatch between class and real file names: 
Symfony/Component/Security/Core/User/UserProviderInterface.php vs 
Symfony/Component/Security/Core/user/UserProviderInterface.php in /my/folder/
```

System : `Darwin server.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64`
Os X : `10.10.5`
Symfony version : 2.8.3
PHP Version :
```
PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:22)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
Installed from homebrew.

trace : 
```
in DebugClassLoader.php line 319
at DebugClassLoader->loadClass('Symfony\Component\Security\Core\User\UserProviderInterface')
at spl_autoload_call('Symfony\Component\Security\Core\User\UserProviderInterface')
at ReflectionClass->__construct('Symfony\Component\Security\Core\User\UserProviderInterface') in ClassCollectionLoader.php line 266
```

**Comment by nicolas-grekas** [comment]
Somewhere in your code you should be using Symfony/Component/Security/Core/**u**ser/UserProviderInterface instead of Symfony/Component/Security/Core/**U**ser/UserProviderInterface (note the lowercase vs uppercase "U")

**Comment by jakzal** [comment]
Indeed, PHP doesn't care about case sensitivity but Symfony's autoloader does. You can find the problem with grep: `grep -R 'Core\\\\user' src/`.

**Comment by macintoshplus** [comment]
Thank's. Search return no result.
I reboot my Mac and error disappear... Magic reboot like on Windows !
