### ISSUE TITLE
Built-In server verbose output

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#17994]
Hello there,

Is there any reason to get ` ERR ` always then we run the `server:run -vvv` command (even when we get the `200` status code? Maybe it needs to be fixed?

Regards,

![screen shot 2016-03-03 at 09 04 40](https://cloud.githubusercontent.com/assets/7809429/13489457/0fcf449a-e11f-11e5-86c4-c9c0845d4d6e.png)

**Comment by javiereguiluz** [comment]
Apparently, PHP built-in server outputs its logs to `stderr`. There is [an open issue](https://bugs.php.net/bug.php?id=68334) in PHP repository and [lines like this one](https://github.com/php/php-src/blob/2e874114a235e3ecabe044d2b8768e693f3cec5a/sapi/cli/php_cli_server.c#L699) in the PHP source code seems to confirm this.

**Comment by WouterJ** [comment]
There is nothing wrong with logging to `stderr` though. It's not important information and it surely doesn't need to be piped to the next command.

I think the process helper should not make stderr message so error-like. stderr isn't about errors, it's about information that shouldn't be piped.

**Comment by stof** [comment]
I totally agree with @WouterJ here. The name ``stderr`` is misleading about its actual purpose (btw, I have not found any bash doc naming it ``stderr``). Errors are denoted by the exit code, not by the place where it writes some messages.

**Comment by javiereguiluz** [comment]
[According to Wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_.28stderr.29), "stderr" is *"to output error messages or diagnostics"*. But it's true that developers no longer respect the original purpose of stderr.

**Comment by stof** [comment]
@javiereguiluz log messages are diagnostics

**Comment by javiereguiluz** [comment]
I'm closing this issue because, according to previous comments, the current behavior is not wrong. Moreover, Symfony recently made all Console helpers use `stderr` for their output ([see details](https://github.com/symfony/symfony/commit/ce60be5729755df392dff709a211e15c71d313f6)).

**Comment by WouterJ** [comment]
@javiereguiluz then we still need an issue to make stderr output less error-ish in the process helper.

**Comment by javiereguiluz** [comment]
We could replace `ERR` by `LOG`
