### ISSUE TITLE
PropertyAccessDecorator should not accept callable strings

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#17993]
Right now, PropertyAccessDecorator [treats callable strings as callables, not as strings](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Factory/PropertyAccessDecorator.php#L87). Consequently the following code does not behave as expected:

~~~php
$builder->add('deadline', ChoiceType::class, [
    'choices' => $dateRanges, // DateRange objects
    'choice_label' => 'end',
]);
~~~

This code results in a fatal error. The `end()` function exists (is callable), hence the string is not treated as property path. Instead, `end()` is called with invalid arguments. IMO there are very few cases where this would be the expected behavior, and even if, it could be solved by passing a closure:

~~~php
$builder->add('deadline', ChoiceType::class, [
    'choices' => $dateRanges, // arrays of dates
    'choice_label' => function (array $dateRange) {
        return end($dateRange);
    },
]);
~~~

Treating callable strings as callables should be deprecated. I.e., all methods of PropertyAccessDecorator should trigger deprecation errors `if (is_string($value) && is_callable($value))`.

**Comment by Tobion** [comment]
Exactly this was changed in #15561. To me, the behavior could be unexpected in both ways. But since people can just pass a `PropertyPath` instance directly if there is a conflict in name and the `callable` is the original contract, I thought it's better to change it to the current behavior.

If you think we should revert that, we could just do it as a hotfix as well I assume.

**Comment by rodnaph** [comment]
I just ran into this as a regression when upgrading my Symfony version. In my case I was accessing a property called `range` on an `EntityType` field (which ended up calling the core `range` function as pointed out in the original description).

I'd agree this is confusing behaviour.
