### ISSUE TITLE
[3.0][Form] Entity construct linked to a form "prototype" does not work

### ISSUE THREAD

**Issue by merorafael** [symfony/symfony#17992]
Hello guys,

I'm a question that is probably a bug of the framework.

I have two forms: "ReservaType" and "HospedeType". 

The form "ReservaType" has a collection(CollectionType field) of "HospedeType", "HospedeType" is a form linked a entity "Hospede" and entity "Hospede" has the __construct method, which inserts the default values for each field.

The problem I found is related to calling this method. The "prototype" of "HospedeType"(in "ReservaType") does not call "__construct" method, which in turn does not load default values, including other entities linked to "Hospede".

**Example field with prototype:**
```php
// ...
            ->add('hospedes', CollectionType::class, [
                'label' => 'admin.label.hospedes',
                'entry_type' => HospedeType::class,
                'entry_options' => [
                    'required' => true,
                ],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ])
// ...
```

**Example "Hospede" entity construct:**
```php
// ...
    public function __construct()
    {
        parent::__construct();
        $this->pessoaFisica = new Fisica();
        $this->chegadaPrevista = new \DateTime();
        $this->partidaPrevista = (new \DateTime())->add(new \DateInterval('P1D'));
        $this->principal = false;
        $this->vip = false;
        $this->fichaNacional = new FichaNacional($this);
        $this->disparouEmailBoasVindas = false;
        $this->disparouEmailCheckIn = false;
        $this->status = 1;
    }
// ...
```

HospedeType configureOptions
```php
    // ...
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'CoreBundle\Entity\Hospede',
            'cascade_validation' => true
        ]);
    }
   // ...
```

This is a bug?

Tks

**Comment by webmozart** [comment]
Hi @merorafael, thank you for reporting this issue :) Can you try setting the `prototype_data` option to `new Hospede()`?

**Comment by merorafael** [comment]
@webmozart It's works with the form before is submitted. However, after its submitted, the framework seems to try execute __construct method separately for each entity in the hierarchy.

**Example:**
I own an entity "Hospede" with a Many-To-One relationship with the entity "Pessoa". The entity "Hospede" has a method __construct with the initial charge which defines the  attributes needed of the method __construct of "Pessoa". 

Before the form is submitted, the parameter "prototype_data" calls the method __construct of "Hospede" entity. After, on "handleRequest" method, calls the method __construct of "Pessoa" first and throws "ContextErrorException" because it was not passed any attribute.

> Warning: Missing argument 1 for CoreBundle\Entity\Pessoa::__construct(), called in /var/www/symfony_app/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php on line 136 and defined

**Comment by webmozart** [comment]
@merorafael I see, thank you for the explanation! I *guess* this can be fixed by setting the `empty_data` key in `entry_options` to `prototype_data` by default, unless an `empty_data` key was set explicitly.

**Comment by webmozart** [comment]
Status: Reviewed

**Comment by merorafael** [comment]
@webmozart I tried to fix the problem by adding `empty_data` in `entry_options` and it did not work. I tried adding `empty_data` in `HospedeType` form class and it did not work. If `HospedeType` and `entry_options` does not have `empty_data`, also does not work. 

The problem only happens after submit.

Analyzing the error trace below, the component receives submitted data and does not use the object defined in `prototype_data`, creatings new objects, starting the children and then the parents.

**Error trace**

> - in src/CoreBundle/Entity/Pessoa.php at line 45
> ```php
>         private $telefones;
> 
>         public function __construct($tipo)
>         {
>             parent::__construct();
>             $this->tipo = $tipo;
> ```
> - at ErrorHandler ->handleError ('2', 'Missing argument 1 for CoreBundle\Entity\Pessoa::__construct(), called in /var/www/symfony_app/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php on line 136 and defined', '/var/www/symfony_app/src/CoreBundle/Entity/Pessoa.php', '45', array())
> in src/CoreBundle/Entity/Pessoa.php at line 45
> ```php
>         private $telefones;
> 
>         public function __construct($tipo)
>         {
>             parent::__construct();
>             $this->tipo = $tipo;
> ```
> - at Pessoa ->__construct ()
> in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php at line 136
> ```php
>             if (null !== $class) {
>                 return function (FormInterface $form) use ($class) {
>                     return $form->isEmpty() && !$form->isRequired() ? null : new $class();
>                 };
>             }
> ```
> - at FormType ->Symfony\Component\Form\Extension\Core\Type\{closure} (object(Form), null)
> in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 602
> ```php
>                     if ($emptyData instanceof \Closure) {
>                         /* @var \Closure $emptyData */
>                         $emptyData = $emptyData($this, $viewData);
>                     }
>                     $viewData = $emptyData;
> ```
> - at Form ->submit (array(), true)
> in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 562
> ```php
>                         $isSubmitted = array_key_exists($name, $submittedData);
> 
>                         if ($isSubmitted || $clearMissing) {
>                             $child->submit($isSubmitted ? $submittedData[$name] : null, $clearMissing);
>                             unset($submittedData[$name]);
> 
>                             if (null !== $this->clickedButton) {
> ```
> 
> - at Form ->submit (array(), true)
> in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 562 
> ```php
>                         $isSubmitted = array_key_exists($name, $submittedData);
> 
>                         if ($isSubmitted || $clearMissing) {
>                             $child->submit($isSubmitted ? $submittedData[$name] : null, $clearMissing);
>                             unset($submittedData[$name]);
> 
>                             if (null !== $this->clickedButton) {
> ```
> 
> - at Form ->submit (array('pessoaFisica' => array('nome' => 'RAFAEL', 'sobrenome' => 'MELLO', 'email' => 'merorafael@gmail.com'), 'chegadaPrevista' => '04/03/2016', 'partidaPrevista' => '05/03/2016', 'principal' => '1'), true)
> in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 562
> ```php
>                         $isSubmitted = array_key_exists($name, $submittedData);
> 
>                         if ($isSubmitted || $clearMissing) {
>                             $child->submit($isSubmitted ? $submittedData[$name] : null, $clearMissing);
>                             unset($submittedData[$name]);
> 
>                             if (null !== $this->clickedButton) {
> ```

**Comment by backbone87** [comment]
Your description leaves missing links in your form type structure and model structure.

Please specify and verify:
- `ReservaType` with data_class `???`
- `HospedeType` with data_class `Hospede` entity
- `???Type` with data_class `Pessoa` entity
- `HospedeType` is used inside a `CollectionType` field inside `ReservaType`
- `Pessoa` entity requires (one? multiple?) `Hospede` entity for its constructor
- how is `???Type` (with data_class `Pessoa` entity) used inside `HospedeType`

**Comment by merorafael** [comment]
@backbone87 @webmozart I created a demonstration project to show the bug occurred. You can access the repository using the link below.

https://github.com/merorafael/SymfonyFormExample/tree/master/src/AppBundle

**Comment by backbone87** [comment]
The form component is not meant to handle such constructs without some "manual" work.
The easiest way is to add the missing setters for pessoaFisica in Hospede and pessoa in Fisica and specify the empty_data option in PessoaType, either directly via $resolver->setDefault() in the PessoaType (if the factory callback is to be used in general) or at the pessoa field in FisicaType. Then you can also remove the aggregate entity instanciations from the constructors of your entities (your entities are then built and plugged together by the form component).
Another way is to add a PRE_SET_DATA listener onto the HospedeType and, if the data is null, set it to a new Hospede instance.

Also this is more of a "how to use" or "what did i do wrong" question and is not appropriate to post on an issue tracker. Please use stackoverflow, irc and the mailinglists for this kind of problems.

Good indicators, if you should post an issue about something is:
- you can identify and describe the problem with reference to the symfony code and/or the symfony documentation and/or target use-cases
and/or
- you can propose and/or reference a solution and/or implementation

**Comment by HeahDude** [comment]
What about `PessoaType` ? There is no fields for it in your repository.
This the one you should set the `empty_data` as its constructor needs a subfield, you can define this with a closure :

```php
class PessoaType extends AbstractType
{
    // ... This form exists on real application.
    public function buildForm(FormBuilderInterface $builder, array $options = array())
    {
        $builder->add('tipo');
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\Pessoa',
            'empty_data' => function ($form, $viewData) {
                $tipo = ...
                // either define it here or get it from submission:
                $tipo = $form->get('tipo')->getData();

                return new Pessoa($tipo);
            },
        ]);
    }
}
```

The options `empty_data` will override the default `new $class()` in `Form` and pass the right argument in your constructor thanks to the closure.

**Comment by merorafael** [comment]
Tks @backbone87 and @HeahDude, the event `PRE_SET_DATA` fix it. But the component should not set initial form data(even after submit) with the value setted in parameter `empty_data`?

**Comment by webmozart** [comment]
@merorafael The fix provided by @HeahDude should work without needing to listen to PRE_SET_DATA. The `empty_data` option is only used during submission of a form *if* that form is empty. If a form is prepopulated (i.e. data was passed before), that option is not used. In that case, you should implement a custom data mapper instead. You can do that in you form type:

~~~php
class PessoaType extends AbstractType implements DataMapperInterface
{
    public function buildForm(...)
    {
        // ...

        $builder->setDataMapper($this);
    }

    public function mapDataToForms($data, $forms)
    {
        $forms = iterator_to_array($forms);

        /** @var FormInterface[] $forms */
        if (isset($forms['tipo'])) {
            $forms['tipo']->setData($data instanceof Pessoa ? $data->getTipo() : null);
        }
    }

    public function mapFormsToData($forms, &$data)
    {
        $forms = iterator_to_array($forms);

        /** @var FormInterface[] $forms */
        $data = new Pessoa($forms['tipo']->getData());
    }
}
~~~

**Comment by backbone87** [comment]
@webmozart the problem he has, is that there are no setters for tipo in Pessoa, pessoa in Fisica and fisica in Hospede, so the default data mapper cant map freshly constructed empty_data back into the parent object. All these fields are populated on construction of each object (outside in / no IoC). but the form components constructs empty_data inside out according to IoC.

**Comment by merorafael** [comment]
@webmozart, I fix the problem using `PRE_SET_DATA` in `HospedeType`. I see no need to have a "set" method when an attribute will receive a single value and will never be changed. Do you agree?

**Code added:**
```php
    // ...
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // ...
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            [$this, 'onPreSetData']
        );
    }

    public function onPreSetData(FormEvent $event)
    {
        if (!$event->getData()) {
            $event->setData(new Hospede());
        }
    }
    // ...
```

Now, you do not think the `empty_data` should not have this behavior after the submit?

**Comment by webmozart** [comment]
@merorafael Yes, you don't need a setter.

I can't say much more than what I already said :( Basically, this thread can be summarized to the following rules:

* If you have a **no-arg constructor** and typical setters/getters, use standard Form functionality
* If you do **not** have a no-arg constructor or non-typical setters/getters, choose one of two:
 * Create the object in `empty_data` if it's sufficient to create the object after submit. This method *cannot* be used to overwrite existing objects with new instances.
 * In all other cases implement a custom data mapper as I showed above.

Yes, you can set data in PRE_SET_DATA, but that's almost the same as directly passing your `Hospede` instance to `createForm()` and doesn't solve the problem with the no-arg constructor in `Pessoa`.

I hope that helps.
