### ISSUE TITLE
[Config] Allow infinity values in IntegerNode

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#17996]
Curently, the `IntegerNode` does not seem to support `INF` value (I guess the float type does though), because `INF` is represented as a float.

Maybe having an option or always allowing to use / detecting `INF` values could be useful in IntegerNodes ?

**Comment by backbone87** [comment]
there is no INF value for php integers. PHP_INT_MAX can be used in most cases as a replacement.

**Comment by Taluu** [comment]
There is one : https://3v4l.org/btDsB

**Comment by stof** [comment]
Look at it again, INF is not an integer. It is a float.. so @backbone87 is right.

**Comment by Taluu** [comment]
On a semantic point of view, it is not really a float either... but it is indeed recognized as a `float` value by php. It should not even be a `float` actually imo

**Comment by Babacooll** [comment]
Well as float allows bigger values than integer infinite is considered as a float in PHP. It's the same behavior for a lot of things in PHP (ceil(), floor(), ...) for good reasons.

**Comment by backbone87** [comment]
There is another reason why this is a bad idea:
In php 7 you can typehint against `integer` that would cause type error when an `IntegerNode` allows INF values.

**Comment by fabpot** [comment]
@Taluu Can you explain why you need this?

**Comment by Taluu** [comment]
On an integer node, I need to represent a "limit".... that can be "removed". I could use `PHP_INT_MAX`, but the thing is, this can change depending on the architecture, and I'm not really seeing myself having a limit that can vary ; semantically speaking, having a `null` or `INF` really shows the "no limit" I'm trying to achieve here.

But with an `INF`, I do not have to bother myself with `$limit !== null && $current > $limit)`, I can directly use `$current > $limit` (which will never be true if the `$limit` is `INF`).

Currently, I have to use a `VariableNode` instead :

```php
//
$root
    ->variableNode('my_limit')
        ->isRequired()
        ->cannotBeEmpty()
        ->treatNullLike(INF)
        ->validate()
            ->ifTrue(function ($v) {
                if (!is_numeric($v)) {
                    return true;
                }
                
                if (is_int($v)) {
                    return false;
                }
                
                if (is_float($v) && is_infinite($v)) {
                    return false;
                }

                return true;
            })
            ->thenInvalid('Expected an int or infinity ; had %s')
        ->end()
    ->end();
```

**Comment by javiereguiluz** [comment]
@Taluu I know that `INF` is not the same as `PHP_INT_MAX`. But in practice, in your real applications, would it make any difference to use `PHP_INT_MAX` instead of `INF`?

**Comment by Taluu** [comment]
Yup, because the thing is, even if I will never reach the `PHP_INT_MAX` value, what should I send from my application if I want to say alter my limit ? Sending a big number such as `PHP_INT_MAX` ? What if this limit is reached "one day" ? I'm not sure I agree on such a behavior... While using `INF` is really meaning "no limit" (such as `null`, but an integer node cannot have a null value too)

But fine, I'll keep using the `VariableNode` then I guess . I should maybe add a `LimitNode` that could do the trick though, but this is really specific though.

**Comment by nicolas-grekas** [comment]
The issue here is that once you reach PHP_INT_MAX, you can't deal with integers anymore, and neither the comparison nor the addition work as expected. E.g. `(PHP_INT_MAX + 1) === (PHP_INT_MAX + 2)` is TRUE. This means that you're going to have much more trouble than just the one you're talking about the day you reach PHP_INT_MAX and this shouldn't be handled by using INF to me.

**Comment by Taluu** [comment]
Maybe `(PHP_INT_MAX + 1) === (PHP_INT_MAX + 2)`, but `(PHP_INT_MAX + 3) < INF` still returns `true` (and returns `false` on `<=`). 

I haven't tested it yet, but since PHP 5.6, there is the operator overloading on the gmp extension (cf https://wiki.php.net/rfc/operator_overloading_gmp), that can then go beyond the `PHP_INT_MAX`. But as I said, I need to test it first.

... But guessing that the probability of having this extension is not really high, I guess we can close this ticket (and the associated pr) as this is really specific.
