### ISSUE TITLE
Deprecate support for absolute path in templating

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#17999]
see #17894 and related.

**Comment by robfrawley** [comment]
Absolute paths seem like an awfully limiting choice. Using the "Symfony syntax" allows for both core and users to change defaults in directory structure in future releases painlessly, as it wouldn't affect the actual callouts within templates. It's also shorter to type. ;-)

I'm not too familiar with the handling of template resolution and loading within the framework, but based on my experience with Symfony elsewhere, I'm confident those who want absolute paths can easily achieve such with a custom Loader implementation.

:+1:
