### ISSUE TITLE
Symfony can't read HTTP headers with dots

### ISSUE THREAD

**Issue by lividgreen** [symfony/symfony#18003]
Symfony is using $_SERVER superglobal for getting headers.
But if we have header like 'my.custom.header', the header is converted (probably by most CGI engines) to `$_SERVER['HTTP_MY_CUSTOM_HEADER']`

`$request->heades->hasHeader('my.custom.header')` will return false in this case because Symfony normalizes headers only with `strtr(strtolower($key), '_', '-')`

Probably, the solution may be: use raw `php://input` instead of $_SERVER superglobal?

**Comment by jvasseur** [comment]
`php://input` contains the request body so it can't be used to get the request headers.

**Comment by lividgreen** [comment]
> php://input contains the request body so it can't be used to get the request headers.
correct, sorry

instead there is `apache_request_headers` function
http://php.net/manual/en/function.apache-request-headers.php

**Comment by patrick-mcdougle** [comment]
in hasHeader and getHeader, can we do the same normalization?

**Comment by Exadra37** [comment]
@lividgreen and what happens when we run in Nginx server, instead of Apache with your suggested alternative?

**Comment by robfrawley** [comment]
@lividgreen Why not simply follow the common convention of using an alphanumeric string with underscores as separators for your custom header name?

I am sure there are valid reasons for the use of only `strtr(strtolower($key), '_', '-')` to normalize these values, and some basic research shows it has worth.

This method correctly normalizers the names of all the official headers, as defined by the IETF and maintained for archival and reference by IANA (http://www.iana.org/assignments/message-headers/message-headers.xml). This includes non-standard headers, which also follow this format.

Quite literally *anything more* would be a needless performance hit. Do you really want Symfony looping through all headers for each requests with `preg_replace('{[a-z_]}i', '-', strtolower($key))` so 1 in 10,000 people can enjoy their own, randomly defined header name formatting?

I don't. ;-)

**Comment by Exadra37** [comment]
@robfrawley It was my intention to arrive to your point, after the reply to my question, but you have been heaven more detailed that i would be...  :+1: for your detailed explanation.

**Comment by Tobion** [comment]
@lividgreen does `apache_request_headers` return the correct headers for you?

This is also used in https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php and dots are not normalized there as well.

**Comment by Exadra37** [comment]
@Tobion as per doc block is present only for simplify mocking, as per https://github.com/zendframework/zend-diactoros/blob/9fff83e9aa7d639863e6128782873b4a8ba96807/src/ServerRequestFactory.php#L29-L34

**Comment by lividgreen** [comment]
@Exadra37, manual tells us that `apache_request_headers ` works well with FastCGI starting from PHP 5.4.0 and even with internal php server starting from php 5.5.7. But the question requires more investigation.

@robfrawley as i know there is no convention that restricts using dots in custom http header names. Please correct me if there is one.

Btw, I would like to use dashes instead of dots, but that is the requirement from third-party. Arguments like "dots in headers bring complications to PHP programs" don't work because they have another argument like "our other consumers don't have any problems usinng dots, why should we change our API and affect all other consumers?"

The problem is not the Symfony's problem. That is whole PHP (CGI?) problem. I'm trying to consider a workaround for Symfony. That is my point.

**Comment by xabbuh** [comment]
Is PHP's behaviour (replacing `.`with `_`) documented somewhere?

**Comment by lividgreen** [comment]
@xabbuh, sorry, but I didn't find any related specification. But here is the small test using PHP internal server:

```php
<?php
var_dump($_SERVER);
var_dump(apache_request_headers());
```

Try sending header like 'test.with.dot: 1'. The result will be something like that (PHP 5.5.14):

```
array(24) {
  ....
  ["HTTP_TEST_WITH_DOT"]=>
  string(1) "1"
  ....
}
array(10) {
  ...
  ["test.with.dot"]=>
  string(1) "1"
  ...
}
```

Sorry, I'm not so good in PHP source code to show you the actual place that converts dots to underscores.

**Comment by jaytaph** [comment]
@xabbuh @lividgreen I'm not sure if it's documented, but it's easily found in the source:

filling of the apache sapi $_SERVER settings:
http://lxr.php.net/xref/PHP_5_6/sapi/apache/mod_php5.c#254
which ultimately calls:
http://lxr.php.net/xref/PHP_5_6/main/php_variables.c#98

here, the key is ltrimmed, and any spaces and dots are replaced with a `_`.

`apache_request_headers()` function:
http://lxr.php.net/xref/PHP_5_6/sapi/apache/php_apache.c#394

Note that function does not convert any headers, but it seems it also uses a different entrypoint to find the variables. I don't know why this is (haven't looked at it in-depth).

@Exadra37 I quick glance through the php source code shows me that the fpm sapi uses the same method for registering these variables as the apache sapi (http://lxr.php.net/xref/PHP_5_6/sapi/fpm/fpm/fpm_main.c#628)

**Comment by teohhanhui** [comment]
It's documented for the request parameters:

http://php.net/variables.external

> Note:
Dots and spaces in variable names are converted to underscores. For example <input name="a.b" /> becomes $_REQUEST["a_b"].

Also see http://stackoverflow.com/questions/68651/get-php-to-stop-replacing-characters-in-get-or-post-arrays

**Comment by lividgreen** [comment]
So, it seems safe workaround can be used in Symfony to deal with it: normalize dots to underscores.

**Comment by teohhanhui** [comment]
That would not work, because there's no way to tell what was the original character before it was replaced by underscore.

**Comment by xabbuh** [comment]
@teohhanhui We can replace dots with underscores when someone tries to access a header whose name contains a dot.

**Comment by teohhanhui** [comment]
Yes, but it might match another header which had other special characters replaced to underscores.

**Comment by lividgreen** [comment]
@teohhanhui, PHP converts dots to underscores of each $_SERVER key. That means "we can never tell the difference" for the whole PHP behavior. Why can't we implement some kind of workaround for Symfony to deal with it?
@xabbuh, probably there is enough information to confirm the bug?

**Comment by teohhanhui** [comment]
@lividgreen See #9009

I don't think it'll happen.

**Comment by HeahDude** [comment]
Reading all the discussion here, I'd say let's remain consistent and don't do things that can mess up applications. Two different headers (one with dots and one with dashes) should not be identical when normalized.

Even implicit, this convention seems to have prevented bugs until then, so why not close this issue as won't fix?

**Comment by xabbuh** [comment]
@symfony/deciders What is your opinion on this one?

**Comment by Tobion** [comment]
I wonder whether http://php.net/manual/en/function.getallheaders.php keeps the original headers intact. Then we could use this method instead of `$_SERVER`

**Comment by nicolas-grekas** [comment]
I think we have no way to fix that. PHP normalize header names, no way around (but in special situations that we can't build on).
Should be closed as won't fix to me.

**Comment by javiereguiluz** [comment]
By the way, the recommended naming for custom HTTP headers is `foo-bar-baz` (previously it was `X-foo-bar-baz`) so it's better to play safe and always use dashes instead of dots or underscores. See https://developer.mozilla.org/en/docs/Setting_HTTP_request_headers

So, let's close as "won't fix" then.
