### ISSUE TITLE
dump() causes "Token not found" in profiler

### ISSUE THREAD

**Issue by Grimbode** [symfony/symfony#18008]
Here is the short version of the code:

```php
        $contents = scandir($directory_location);
        while(count($contents) > 0) {
            $elem = array_shift($contents);
            dump($elem); //<-- this line
        }
```

It would appear the dump line is causing the issue. If I comment the dump() line then there is no problem.

Is there a certain kind of string that would cause this problem? Or is there a max limit on dumps? 

![uzwprfk](https://cloud.githubusercontent.com/assets/243674/13526230/fa86122e-e206-11e5-9434-3ceb3d840691.png)

**Comment by javiereguiluz** [comment]
That error only happens to me when I'm in the profiler, execute a `rm -fr app/cache/*` and try to keep navigating in through the profiler pages.

The "token" in this case refers to the stored profile data. Somehow your profile data has been deleted.

**Comment by Grimbode** [comment]
@javiereguiluz That was my first thought and I tried `php console/bin cache:clear` before posting. I just tested  `rm -fr app/cache/*` and as long as I have the `dump($elem);` it still causes the same "Token not found" in the profiler.

**Comment by nicolas-grekas** [comment]
@Grimbode do you see any error in your php error log, like a fatal error? Is this code executed in an internal or external subrequest? What's the page before you see this error?

**Comment by Grimbode** [comment]
@nicolas-grekas there are no errors. If I comment the dump, everything works perfectly fine. External request. I send a post request to my controller that runs that service. The page is just a view with one button to run the process.

[Screen shot of my view](http://imgur.com/9Oq81j6)

**Comment by xabbuh** [comment]
@Grimbode Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by weaverryan** [comment]
@Grimbode if you temporarily move `$kernel->terminate()` above `$response->send()` in `app_dev.php`, you might be able to see an error that's happening:

```php
$response = $kernel->handle($request);
$kernel->terminate($request, $response);
$response->send();
```

These errors are hard to debug because they happen *after* the response is sent to the user, so you might not see an error that's occurring.

**Comment by javiereguiluz** [comment]
I'm closing this because of the lack of feedback. Hopefully this was fixed. If not, please @Grimbode reopen it. Thanks!

**Comment by vctls** [comment]
I'm having the same issue when trying to dump a SimpleXMLElement in my controller.

**Comment by belackriv** [comment]
Adding to this: another cause I found is that a 'dump()' command was running out of memory and causing the token to not generate, but the actual request was successful.

**Comment by BenMorel** [comment]
Just had a similar issue.

> if you temporarily move `$kernel->terminate()` above `$response->send()` (...) you might be able to see an error that's happening

This helped a lot. In my case, it was `memory_limit` that was hit by the profiler.

I also realized that when `$response->send()` is called, the `X-Debug-Token-Link` is sent in the headers, and the connection to the HTTP client is closed, so you would expect that the request is finished and the profiler link is active at this point; but actually **the profiler has not yet created the page**, and you may receive a Token not found error for a few seconds while the profiler is doing its thing in the background, depending on the workload.

Typical `index.php`:

```php
$response->send(); // sends the response and closes the connection using fastcgi_finish_request()
$kernel->terminate($request, $response); // creates the profiler page in the background
```
