### ISSUE TITLE
[Validator] Failed to validate URL with dashes in path

### ISSUE THREAD

**Issue by smilesrg** [symfony/symfony#18017]
This URL ```https://ru.wikipedia.org/wiki/Римский-Корсаков``` fails validation, but it's a valid URL.
Checked on 2.5 and 2.8

**Comment by jakzal** [comment]
I have just tried it with the following code:

```
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints\Url;

$validator = Validation::createValidator();

// validateValue() in 2.3
$violations = $validator->validate('https://ru.wikipedia.org/wiki/Римский-Корсаков', new Url());
var_dump($violations);
```

2.3-3.0 returns no violations. Could you provide a usage example when this would fail?

**Comment by TomasVotruba** [comment]
@jakzal It looks like versions 2.5 and 2.8 were reported

**Comment by jakzal** [comment]
@TomasVotruba 2.5 is not supported anymore. As I said earlier all supported versions from 2.3 to 3.0 do not return any violations.

**Comment by TomasVotruba** [comment]
@jakzal Oh sorry, my bad. I read 2.3.3

**Comment by jakzal** [comment]
@smilesrg what was the problem in the end?
