### ISSUE TITLE
[Security] getDefaultSuccessRedirectUrl should have access to the token

### ISSUE THREAD

**Issue by billsworld** [symfony/symfony#18027]
Using the new Guard component I am redirecting the user to a page like /user/{username}. The problem is I cannot access the user token in ```getDefaultSuccessRedirectUrl```. I am proposing that the ```$request``` and ```$token``` get passed to ```getDefaultSuccessRedirectUrl```

Without the token I have to adjust my authenticator like this

```php
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        // if the user hit a secure page and start() was called, this was
        // the URL they were on, and probably where you want to redirect to
        $targetPath = $request->getSession()->get('_security.'.$providerKey.'.target_path');

        if (!$targetPath) {
            $targetPath = $this->container->get('router')
            ->generate('app_user_index', ['username' => $token->getUsername()]);
        }

        return new RedirectResponse($targetPath);
    }

    protected function getDefaultSuccessRedirectUrl()
    {
         // nothing
    }
```

This is not so good b/c I have to define getDefaultSuccessRedirectUrl which will never be used. Perhaps it would be better if the definition was more like this ```protected function getDefaultSuccessRedirectUrl(Request $request, TokenInterface $token)``` Or maybe ```getDefaultSuccessRedirectUrl``` should not be defined as an abstract method.

**Comment by weaverryan** [comment]
@billsworld Hmm, yes I see! The whole point of implementing `onAuthenticationSuccess` for you was to alleviate the annoying code for getting the target path from the session. However, we just introduced a new trait (https://github.com/symfony/symfony/pull/17714/files#diff-81156d593cb42fd30da1fc35a7a4d056R43) that makes this very easy. I propose that we deprecate `getDefaultSuccessRedirectUrl()` - and have users implement `onAuthenticationSuccess` themselves. Then you would have:

```php
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        $targetPath = $this->getTargetPath($request->getSession(), $providerKey);

        if (!$targetPath) {
            $targetPath = $this->container->get('router')
            ->generate('app_user_index', ['username' => $token->getUsername()]);
        }

        return new RedirectResponse($targetPath);
    }
```

**Comment by billsworld** [comment]
@weaverryan I actually implemented onAuthenticationSuccess more to have access to the TokenInterface. I agree onAuthenticationSuccess could be deprecated but it definitely should not be required by making it abstract in the base class

**Comment by weaverryan** [comment]
I opened a PR to deprecate the function (would also makes the `getDefaultSuccessRedirectUrl` not abstract anymore): #18135
