### ISSUE TITLE
DomCrawler ArrayAccess interface

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18038]
Would it be acceptable for the DomCrawler to implement the ArrayAccess interface? That way `foreach` can be used instead of `each()`. The closure needs to make explicit which outer variables to use (with `use`) and is more verbose. Also instead of `->eq(0)` just `[0]` can be used. Possibly both interfaces could co-exist

**Comment by xabbuh** [comment]
We would then also have to support unsetting nodes. Not sure how you would implement that.

**Comment by flip111** [comment]
`$href->parentNode->removeChild($href);` i guess ^^

**Comment by jakzal** [comment]
Removing nodes is something we don't support on purpose. DomCrawler's a tool for crawling documents, not modifying them.

**Comment by flip111** [comment]
That will make it even more easier, just return the method immediately or throw an exception.

**Comment by xabbuh** [comment]
Imo that it is not behaviour someone would expect when a class claims to implement the `ArrayAccess` interface. That being said I am :-1: on making this change.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because of the concerns expressed by some Symfony Core members. In addition, this would add a new way to solve a problem, and that's something we usually try to avoid.

@flip111 this time your proposal didn't make it, but please keep sending proposals to improve Symfony. Thanks!

**Comment by stof** [comment]
btw, one of your claim was wrong

> That way ``foreach`` can be used instead of ``each()``.

``ArrayAccess`` has nothing to do with ``foreach``. You are confusing with ``Traversable``, and the crawler is already an iterator.

**Comment by flip111** [comment]
@stof ah yes. Actually i forgot to mention something important ... `foreach` works but returns the raw nodes instead of wrapping it in a crawler. So now foreach comes with it's own boilerplate code having to wrap the nodes again manually ... Why not have a method `getNodes` to get an array of nodes, because when walking through the DOM you are more likely gonna need new domcrawlers to specificy your search further and further. I tent to end up with nested closures if im writing a small (throw away) crawler script.

**Comment by flip111** [comment]
> DomCrawler's a tool for crawling documents, **not modifying them**.

This is incorrect because there [are](http://api.symfony.com/3.0/Symfony/Component/DomCrawler/Crawler.html) a ton of `add*` methods on the crawler. There is also `clear()` to remove all the nodes and `reduce()` to remove specific nodes.

I didn't look at the API before and assumed that the people who commented actually did. o_O

@javiereguiluz could you please reevaluate the position on closing this issue? thanks

**Comment by javiereguiluz** [comment]
@flip111 I closed it because of the `-1` votes ... but you can provide new arguments to make core members change their opinion.

**Comment by flip111** [comment]
javier, the originel idea is still okay to me, the counter-argument was not well founded in my opinion

@jakzal can you reevaluate the idea after getting more familiar with the DomCrawler? So that other core members can also base the discussion on the informed point of view? thanks

**Comment by jakzal** [comment]
@flip111 I'm quite familiar with the component, thanks ;)

As [explained in the docs](http://symfony.com/doc/current/components/dom_crawler.html):

> The DomCrawler component eases DOM navigation for HTML and XML documents.

> While possible, the DomCrawler component is not designed for manipulation of the DOM or re-dumping HTML/XML.

DomCrawler is designed to extract details from DOM documents rather than modifying them. Methods you mention, like `reduce()` do not modify the state of the Crawler, but return a new instance. Again, the purpose is filtering/crawling the document, not modifying it. Add methods are there to initially load the document.

Note that I merely pointed out that removing/changing nodes is not something that the Crawler is designed for. Could you think of a way of implementing ArrayAccess which would forbid changing crawler's internal state?

**Comment by flip111** [comment]
@jakzal thanks for your reply. When you are talking about preventing change of the crawlers internal state, you are talking about it being immutable, no? I mean `reduce` does modify "what you have", but it does this by making a new instance. I don't understand why immutability is important in this case, you can just as well make a copy in the mutable world.

Anyway the discussion seems to be about two things now, so let's separate them.

> Methods you mention, like reduce() do not modify the state of the Crawler, but return a new instance.

There are still methods which change the internal state, `clear` and `add*` methods. I'm not sure what the purpose of `clear` is if you want to make things immutable. Also instead of `add` you can have static methods which act as a constructor function to construct a new object in a different way, this prevents the ability to add nodes after the initial load. The way it's designed now doesn't reflect the intent you are expressing in my opinion, this is what i was pointing out before.

> DomCrawler is designed to extract details from DOM documents rather than modifying them.

Ok if this is so, is there any specific reason for it? As engineer i can not accept the argument on base of "it's the way it is". Let's say i have a bridge for bikes and now there are more cars on the road. I'm just gonna look at that bridge and think "how can we change the bridge so that cars can use it too". Rather then stop and say "well no nothing i can do, the bridge was designed for bikes, so i guess that's the end of it". But ye i can not know that maybe the whole area was designated as bike-only to prevent the pollution and noise, which makes the argument about converting the bridge rather pointless. Maybe this is the case with the DomCrawler too? Maybe there is some principle i'm missing that we don't want to use it to modify documents?

Well thanks again for your explanation, i was hoping i could have this nice ArrayAccess interface for crawling (i don't care about modifying documents myself).

**Comment by stof** [comment]
> This is incorrect because there are a ton of add* methods on the crawler

If you look at what these methods are doing, you will see that they are not adding the elements in the document. the elements must already be part of the document.

**Comment by flip111** [comment]
@stof Ah yes very interesting remark. I got as comment that "the DomCrawler is not for modifying documents". So i guess this isn't a problem then, because changing the crawler state does not change the document. Nice find thanks.
