### ISSUE TITLE
Symfony2 blog article - HTML encoding issues

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/symfony#18041]
This blog article displays special characters incorrectly: [Is Symfony too slow for real world usage](http://symfony.com/blog/is-symfony-too-slow-for-real-world-usage)

There may be others so just wanted to report it here quickly.

<img width="718" alt="screen shot 2016-03-07 at 2 23 10 pm" src="https://cloud.githubusercontent.com/assets/1480617/13560141/2be06368-e470-11e5-8831-7da7951a7ea5.png">

**Comment by javiereguiluz** [comment]
Closing it as fixed ... but I'm afraid that we can't fix all the old blog posts (this one is from 2007!!)  Thanks for understanding it.
