### ISSUE TITLE
Upgrade 2.8/3.0 - missing information about Finding deep items in ParameterBag::get()

### ISSUE THREAD

**Issue by zdenekdrahos** [symfony/symfony#18058]
Information about deep items in `ParameterBag` is mentioned only in [http-foundations's changelog](https://github.com/symfony/http-foundation/blob/master/CHANGELOG.md#280).

> Finding deep items in ParameterBag::get() is deprecated since version 2.8 and will be removed in 3.0.

It's big BC (controller doesn't work is SF3), so I think, that it should be mentioned in upgrade guides [2.8](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md) and [3.0](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md).

**Comment by javiereguiluz** [comment]
Closing it as fixed by #18064.
