### ISSUE TITLE
Help needed for lazy developers

### ISSUE THREAD

**Issue by TheCelavi** [symfony/symfony#18050]
Simple problem -> Entity with 15 properties, 2-3 Assertions per property in average.

Need to validate only 14 in one use case, all 15 in other. 

I know - validation groups, but is there any neat solution to this? Like -> "define new validation group from default group which does not exclude certain rules?" in runtime? Or something similar? That I do not need to code too much? :)

**Comment by xabbuh** [comment]
Sorry, but I am closing here @TheCelavi. We use GitHub only for bug reports and to discuss new features. Please use [one of the support channels](http://symfony.com/support) to seek for help. Thank you for understanding.
