### ISSUE TITLE
Missing auto wiring configuration for TranslatorInterface

### ISSUE THREAD

**Issue by J7mbo** [symfony/symfony#18060]
Referring specifically to [this comment](https://dunglas.fr/2015/10/new-in-symfony-2-83-0-services-autowiring/#comment-98235):

> Unable to auto wire argument of type "Symfony\Component\Translation\TranslatorInterface" for the service X

@dunglas wrote:

> Vendor classes must be fixed in the vendor or their definition must be overrided in your app.

> We updated core classes of Symfony and “officials” bundles but it looks like we missed some components like Translator. Can you open a PR or open a bug in Symfony for this one?

So here's a BUG for that! Can I please type hint for this `TranslatorInterface` and be able to get an instance of `"@translator.default"` injected?

**Comment by aitboudad** [comment]
I think yes since 2.8.3, see https://github.com/symfony/symfony/pull/17703

**Comment by dunglas** [comment]
Closing because it's already fixed as pointed out by @aitboudad. Feel free to reopen if there is another issue.
