### ISSUE TITLE
[Form] FormValidator still contains code for `cascade_validation` option removed in 3.0

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#18063]
Form option `cascade_validation` has been removed in 3.0 (https://github.com/symfony/symfony/commit/17cedd343529efb07bd577385d6006d48569e21f), but `FormValidator` still contains code for handling it: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L141

I think this can now be removed .
And (I guess) `allowDataWalking()` method should return `false` by default.

Should I post a PR?

**Comment by peterrehm** [comment]
I would say the lines can be removed but `true` must remain as default. Is this the last part where cascade_calidation is mentioned?

**Comment by webmozart** [comment]
I *think* this should be save to remove.

**Comment by peterrehm** [comment]
Just submitted the PR with this removal.

**Comment by sustmi** [comment]
I don't think you can just remove the whole `while`, @peterrehm .

In 2.7 the `allowDataWalking()` returned `true` only for forms that were root or had all its ancestors with `cascade_validation` option set to `true`.

Now (in 3.0) the `getOption('cascade_validation')` always returns `null` (because it is not defined), so the `allowDataWalking()` method return `true` only for root forms.

Your PR changes the behaviour so that the `allowDataWalking()` method returns `true` for every form.
(For the simplicity I am omitting the precondition that the form `$data` must be either `object` or `array`.)

**Comment by sustmi** [comment]
Also there are still references to `cascade_validation` option in tests.

**Comment by sustmi** [comment]
@webmozart What is the expected behaviour? Should be the validation cascaded in all forms or in none?

**Comment by peterrehm** [comment]
Thanks for your feedback, mind having a look again and comment in the PR directly?

**Comment by webmozart** [comment]
@sustmi It is sufficient if `allowDataWalking()` returns `true` for root forms only:

1. Nested objects will be discovered by the validator itself by traversing the properties constrained with `@Valid` constraints.
2. Nested forms that contain objects disconnected from the root object (and hence cannot be discovered through 1.) can be validated by setting the `constraints` option to `new Valid()`. This will lead to that data being validated in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L60.

I'm pretty sure now that the code in question can be safely removed. We can probably even inline the `allowDataWalking()` method, if the result is easy enough to read.
