### ISSUE TITLE
[RFC] Create a new ValueExporter component

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18074]
### Context

As @fabpot said in https://github.com/symfony/symfony/issues/18070#issuecomment-194238478, if some code is repeated in several parts, we can extract it to a new component, no matter how big or small it is.

### Problem to solve

In Symfony this need is very common: *"given an arbitrary variable, return its best possible representation as a string"*.

### Current situation

Today we solve this problem at least in 6 different ways across different bundles and components:

* [ValueExporter class](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php) (in `Symfony\Component\HttpKernel\DataCollector\Util`) used mostly in DataCollectors.
* [formatValue()](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php#L207), [formatParameter](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php#L227) and [formatCallable](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php#L419) in FrameworkBundle's Console descriptors.
* [formatValue()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L986) method in OptionsResolver component.
* [getStringRepresentation()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php#L98) method in DebugAccessDecisionManager class.
* [varToString()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Exception/FileLoaderLoadException.php#L68) method in FileLoaderLoadException class (`Symfony/Component/Config/Exception`)
* [sanitizeContext()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php#L163) method in LoggerDataCollector (`Symfony\Component\HttpKernel\DataCollector`)

### Solution

Create a new `ValueExporter` component to merge all this stuff.

**Comment by Koc** [comment]
Have same needs for my library https://github.com/Koc/Sphinxy/blob/38429e049ee8498bb619c33a75af39a33fe978cd/Logging/TraceLogger.php#L30 . ValueExporter component is a good idea!

**Comment by fabpot** [comment]
VarDumper is also probably a good way to solve some use cases.

**Comment by nicolas-grekas** [comment]
I was about to write it: this component exists, it's called VarDumper.

**Comment by Koc** [comment]
@nicolas-grekas how it possible get string representation of the variable using VarDumper in easy way? http://symfony.com/doc/current/components/var_dumper/advanced.html#dumpers looks too verbose

**Comment by Koc** [comment]
Also VarDumper adds html or ansi escape codes to output. It doesn't needed for use cases where ValueExporter used.

**Comment by nicolas-grekas** [comment]
@Koc VarDumper provides interfaces and algorithms to extract the state of any var, then represent it using a "Dumper". Writing one or more suited for the envisioned use cases is what's needed.

**Comment by fabpot** [comment]
Indeed, this is what I had in mind with my first comment. Re-using the VarDumper infrastructure to be able to dump values when we need them without all the fancy decoration added by the current dumpers.

**Comment by HeahDude** [comment]
When I look at the origin of `ValueExporter::exportValue()` it appears to be as close to `var_export` as `dump()` is close to `var_dump`.

What do you think about having something like `value_export($data)` ?

**Comment by WouterJ** [comment]
Fyi, I was already trying to make DataCollectors use the HtmlDumper of VarDumper to dump their values. That will be much nicer for objects than `Object ( Some\Fqcn )`. I planned to work more on this during the hackday saturday.

I think all that's needed is add a new class to the VarDumper component that is able to transform [`Data`](https://github.com/symfony/var-dumper/blob/master/Cloner/Data.php) instances to a plain text string.

**Comment by javiereguiluz** [comment]
Closing it in favor of #18149, which asks to improve VarDumper so we can use it for this. Thanks!
