### ISSUE TITLE
"Did you mean" functionality within Symfony

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#18070]
Working on some internal code, I was having trouble understanding certain error messages. The main reason was because I wrote a "parameter" instead of "parameters". To save others some time, I wanted to show a nice possible alternative value that _is_ allowed instead. I know that Symfony has a lot of those messages and they add value to the Developer Experience.

So I wanted to implement this and it occurred to me how often there was code duplication! I've done a very basic search for ["Did you mean"](https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=Did+you+mean) and got 2 pages of which not all contained the actual implementation. There's some [additional implementations](https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=alternatives&type=Code) to be found all around the code base but all come down to 1 thing, suggesting alternatives.

I think it would be a great addition to have a generic way to not only generate alternative suggestions within Symfony, but also for people who want to implement the DX concept in their own applications or libraries. I would imagine this to be a tiny component compared to others which could (for now) provide the following:

``` php
// just an example, no idea how this would be named or if both cases are needed
use Symfony\Component\Alternative\ManyAlternatives;
use Symfony\Component\Alternative\SingleAlternative;

$possibleOptions = ['foo', 'foobar', 'bar'];

echo implode(', ', ManyAlternatives::match(['fo'], $possibleOptions));
// foo, foobar

echo SingleAlternative::match(['fo'], $possibleOptions);
// foo

// or optionally with a custom value resolving
echo ManyAlternatives::match(
    new Definition('foo'),
    $possibleOptions, 
    function (Definition $d) { return $d->getName(); }
);
```

**Comment by javiereguiluz** [comment]
My first impression is that this is too tiny to be a component.

**Comment by iltar** [comment]
I agree on that point but then I couldn't place it in existing components which could be used in smaller libraries and applications.

**Comment by javiereguiluz** [comment]
Yes. This is the code that would normally go to "Symfony Commons" library used by other components. But we don't have "Symfony Commons".

**Comment by iltar** [comment]
Is there a lot of code that could potentially be in this "common" package?

**Comment by sstok** [comment]
To tiny? :) the https://github.com/symfony/symfony/tree/master/src/Symfony/Component/OptionsResolver is only two actual classes (excluding exceptions).

I would rather have a hundred small packages then one big common package, what is common? What is core? I would love to see the XmlUtils class to have it's package so I don't have to copy it every time I want to use it outside of Symfony.

Behold the php worlds smallest package https://github.com/rollerworks/SfContainerInjector this is tiny :smile:

**Comment by jenkoian** [comment]
+1 small packages (another small package in case more evidence is needed https://github.com/bangpound/callable-compiler-pass)

**Comment by iltar** [comment]
I too favor small packages, but it can be a management/version dependency hell. In symfony every package would be bumped the same versions, even if nothing is changed. This already reflects issues present in things like the ACL component/assetics bundle. If desired it could always be a small package which follows its own versioning which doesn't even have to be in the symfony repository. This would fracture the maintainability though. It would also mean that symfony "core" functionality starts depending on non-symfony vendor code.

**Comment by fabpot** [comment]
We've made a strong decision from day 1: one repository, one predictable schedule, multiple subtree splits. It works very well and the downsides are really small. I'm all in favor of creating more decoupled components where it makes sense. Some components started with just one class and more were added afterwards (I think it was the case for the Debug, and it was definitely the case for HttpFoundation). Filesystem itself is a very small component. So :+1: for extracting code to avoid duplication.

**Comment by TomasVotruba** [comment]
As for "Did you mean feature", there might come some inspiration: https://github.com/nette/utils/commit/298e955ad903c212dc766aa3f9f8ca840b6936eb

I'm also for creating a new component. It makes sense to put it all in one place.

**Comment by javiereguiluz** [comment]
My concern is that the core of this component would be five lines of code:

```
foreach ($collection as $item) {
    $lev = levenshtein($method, $item);
    if ($lev <= strlen($method) / 3 || false !== strpos($item, $method)) {
        $alternatives[] = $item;
    }
}
asort($alternatives);
```

Implementing a "Did you mean" feature is trivial: just call the `levenshtein()` function. The hard part is collecting the list of potential alternatives. And that's totally different for console commands, controllers , templates, etc. I don't know how a component would help us with this.

**Comment by TomasVotruba** [comment]
I wonder, this feature could also help the PropertyAccess component with inflector pluralization.

**Comment by javiereguiluz** [comment]
I'm still 👎  about this. Implementing a *"Did you mean?"* just requires 1 function call to `levenshtein()`  The hard part is finding good candidates ... and no component can help you with that.

**Comment by iltar** [comment]
I'll close this issue, it's not too popular, thanks!
