### ISSUE TITLE
Should we provide a tool to fix YAML deprecations?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18079]
### Problem

[YAML deprecations](http://symfony.com/blog/new-in-symfony-2-8-yaml-deprecations) in Symfony 2.8 are a pain for lots of developers. Some of them are wondering if they can use a tool to automatize these changes:

![rdohms_twitter](https://cloud.githubusercontent.com/assets/73419/13643174/de1daaf8-e61f-11e5-8a1a-360ab7f08521.png)

### Solution

Given that this Saturday [there is a Hack Day](http://symfony.com/blog/virtual-symfony-hack-day-march-12th), should we consider adding "something" to remove YAML deprecations automatically? For example, adding a `--fix` option to the `lint:yaml` command?

**Comment by fabpot** [comment]
Sounds reasonable to me and it should be quite easy to do. A very good feature to develop during a hack day anyway!

**Comment by iltar** [comment]
Sounds nice to have, I have dozens of projects that will need this fix for both 3.0 and 3.1.

**Comment by weaverryan** [comment]
There is a tool - but they're stuck in *this* exact issue - someone might be able to help out: https://github.com/umpirsky/Symfony-Upgrade-Fixer/pull/18

**Comment by javiereguiluz** [comment]
I'm closing this because, as @weaverryan said, there is already an open-source tool for this and they are struggling with this very same feature. So let's focus our efforts towards that tool.
