### ISSUE TITLE
Unable to override EntityType query_builder option

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#18073]
Hello,

I am trying to override the query_builder option, keeping over options values of an EntityType form field:

```php
$builder
    ->add('fieldname', EntityType::class, array(
        'class' => 'MyBundle:MyEntity',
    ))
    ->addEventListener(FormEvents::PRE_SUBMIT, array($this, 'onPreSubmit'));
;
```
This is not working, the new query builder set, seems to not be taken into account:

```php
public function onPreSubmit(FormEvent $event)
{
    $form = $event->getForm();

    // Get options previously setted
    $options = $form->get('fieldname')->getConfig()->getOptions();
    // Add query_builder
    $options['query_builder'] = function (EntityRepository $er) {
        return $er->createQueryBuilder('e')->where('...');
    };
    // Not working,, query_builder is ignored. The old query_builder is still used on submit...
    $form->add('fieldname', EntityType::class, $options);
}
```

It seems that something in the options is the problem because this is working:

```php
public function onPreSubmit(FormEvent $event)
{
    $form = $event->getForm();
    
    // Working
    $form->add('fieldname', EntityType::class, array(
        'class' => 'MyBundle:MyEntity',
        'query_builder' => function (EntityRepository $er) {
            return $er->createQueryBuilder('e')->where('...');
        }
    ))
}
```

Any idea?

**Comment by backbone87** [comment]
iirc, there is another option that is derived from query_builder on option resolution. so the options you get from `$form->get('fieldname')->getConfig()->getOptions()` already contain this derived option, ignoring the new query_builder value on resolution.

**Comment by HeahDude** [comment]
@backbone87 is right.

When a form reach a `PRE_SUBMIT` event, it is already built.

So `EntityType` has already built its `choice_loader` and cached the `choice_list` depending on `query_builder` option.

The only way to set this option is to use the same logic as your working `preSubmit` method but in the `buildForm()` method instead.

**Comment by Seb33300** [comment]
Thanks. I just had to unset them to solve the problem:
`unset($options['choice_list'], $options['choice_loader']);`
