### ISSUE TITLE
[Yaml] Not parsing integers with separation correctly

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#18094]
in the [yaml specification](http://yaml.org/type/int.html), it is shown that `123_456_789` should be a valid number (see part on validation). In Symfony, this is interpreted as a string, but it should be interpreted as a valid integer.

**Comment by Taluu** [comment]
But it looks like the `,` is used as a delimiter, even though the yaml specs says it should be a `_`

**Comment by xabbuh** [comment]
The specification you linked to is for YAML 1.1. Are you sure that the same applies for YAML 1.2 too (see also http://yaml.org/spec/1.2/spec.html#id2803828)?

**Comment by Taluu** [comment]
Good point, it is not mentionned anywhere. But I can see that in the 1.2 spec, some links are made to the 1.1 types : http://yaml.org/spec/1.2/spec.html#id2761292

So I'm guessing these are still valid ?

**Comment by javiereguiluz** [comment]
After reviewing the Yaml spec again I think @Taluu is right:

  * Yaml 1.2 spec [explanation about integers](http://www.yaml.org/spec/1.2/spec.html#id2803828) mentions that their URI is `tag:yaml.org,2002:int`
  * That URI is fully [explained here](http://yaml.org/type/int.html) and it allows using `_` to separate integer numbers.
  * Beware that the spec explaining the tags (such as `int`) is version 1.1 ... but that's independent from the main Yaml version, which is 1.2.
  * The same applies for float numbers.

So, Yaml 1.2 (as well as most programming languages) allows using `_` to make numeric values more readable.
