### ISSUE TITLE
[DX] add a method `addTranslatedFlash` on Controller

### ISSUE THREAD

**Issue by julienfastre** [symfony/symfony#18103]
Hi! 

I love the method ´addFlash` on `Symfony\Bundle\FrameworkBundle\Controller\Controller` and I would love having a method `addTranslatedFlash` which would allow to add translated flash in one method.

Currently, we have to call the translator within the method : 

```php
$this->addFlash('success', $this->get('translator')->trans( "The action succeeded !"));
```

I think this shortcut would be welcome :
```php
$this->addTranslatedFlash('success', "The action succeeded !");
```

The signature of this method would copy the one from `Symfony\Component\Translation\TranslatorInterface` : 

```php

protected function addTranslatedFlash($type, $message, array $parameters = array(), $domain = null, $locale = null)
```

If this is accepted, I would be happy to contribute.

**Comment by backbone87** [comment]
Why dont you translate the flash message on output in the template?

**Comment by javiereguiluz** [comment]
As @backbone87 said, the common practice in Symfony is to translate these flash messages in the template, alongside the rest of the contents of the page. I'm :-1: because we try to minimize the shortcuts added to the base controller.

**Comment by jakzal** [comment]
I'm :-1: as well. Translation is something closer to the presentation layer.

**Comment by julienfastre** [comment]
I do understand the need of delegating the flash message to the template. But how do you communicate the parameters to the template ? The actual method signature is `protected function addFlash($type, $message)`.

**Comment by javiereguiluz** [comment]
@julienfastre you pass the variables as regular template variables and then use them as arguments of the `trans` filter/tag. If you can't do this, the solution is to use the code that you showed in your previous comment:

```php
$this->addFlash('success', $this->get('translator')->trans( "The action succeeded !", $parameters));
```

**Comment by julienfastre** [comment]
@javiereguiluz passing the variable as a regular template variables is not possible : we regularly use flash message before redirecting after a successfull create / update action. In this case the flash message is displayed on the next request. The whole code is : 

```
$this->addFlash('success', $this->get('translator')->trans( "The action succeeded !", $parameters));

return $this->redirectToRoute('route_name', $parameters);
```

That's why having the possibility to give parameters to the flash messages would be useful.

Another possibility would be to add flash message with parameters, on the [`FlashBagInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBagInterface.php) : `public function add($type, $message, array $parameters = array(), $domain = null)`. But I do not know how to keep the `get` method easy in this case (how to return the mesage, the parameters and the domain on a easy way).

**Comment by iltar** [comment]
If you want lazy translations, I've done this the following way:

```php
class TranslatableMessage
{
    public function __construct($message, array $parameters = [], $domain = 'messages');
    public function getMessage();
    public function getParameters();
    public function getDomain();
}

// in TwigExtensions::getTests():
new \Twig_SimpleTest('translatable', function ($o) {
    return $o instanceof TranslatableMessage;
}),
```

```twig
{% for msg in app.session.flashbag.get('my_key') %}
    {% if msg is translatable %}
        {{ msg.message | trans(msg.parameters, msg.domain) }}
    {% else %}
        {{ msg | trans }}
    {% endif %}
{% endfor %}
```

This could be narrowed down to less boiler plate but we haven't had the need to do this yet. This makes it possible to translate lazily based on parameters. The big advantage is that you won't have to inject your translator everywhere and can simply handle it in the template.

**Comment by julienfastre** [comment]
@iltar Thanks. The way you are working sounds good. I am going to suggest this to my colleagues.

**Comment by javiereguiluz** [comment]
Let's close this because most people seem to be against it and there are alternative solutions.

@julienfastre this time your proposal didn't make it, but please keep sending proposals to improve Symfony. Thanks!

**Comment by julienfastre** [comment]
@javiereguiluz No problem for closing this. Thanks for your encouragement. And the idea I gathered here are useful.

**Comment by iltar** [comment]
@javiereguiluz @julienfastre what about the implemention I just posted but hidden inside a FrameworkBundle variant of the flash-bag? It could internally perform this check and translate if desired before returning the value.

This would be a very easy to implement feature (hack-day *hint*).
