### ISSUE TITLE
Validator Documentation

### ISSUE THREAD

**Issue by CoolGoose** [symfony/symfony#18108]
Hi Guys,

This commit https://github.com/symfony/validator/commit/6a03b55076d6af83f326a6ff3220ca2d3ffb81d8 removed the validator readme docs that provided a short and clear way on how to use the validator without a symfony form.

The documentation from https://symfony.com/doc/current/book/validation.html doesn't have anything like that. 

Should I open a pull request on the main doc regarding this, or you just don't want to recommend the other way of doing validation ?

**Comment by javiereguiluz** [comment]
@CoolGoose you are right. I'm sorry about this deleted documentation.

I'm closing this issue because we're already trying to add the docs for the Validator component in https://github.com/symfony/symfony-docs/pull/5661  I'll try to help them finish and merge that soon. Thanks!
