### ISSUE TITLE
[Form][Validator] How to disable one transformer validation error dynamically?

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#18109]
Some time ago I created [this question](http://stackoverflow.com/questions/35507960/how-to-disable-one-transformer-validation-error-dynamically-in-symfony2) in stackoverflow (no answer yet)

Some expert could help me?

**Comment by alexislefebvre** [comment]
As xabbuh said in [this other issue](https://github.com/symfony/symfony/issues/18050#issuecomment-193375272):

> We use GitHub only for bug reports and to discuss new features. Please use one of the support channels to seek for help. Thank you for understanding.

I suggest you to close this issue and follow xabbuh's advice by asking for some help on the recommended support channels.
