### ISSUE TITLE
UrlGenerator has incorrect scheme-validation

### ISSUE THREAD

**Issue by arjenm** [symfony/symfony#18106]
Hi, I was looking at the code from the UrlGenerator::doGenerate and noticed something odd about the code which validates the scheme.

I.e. this piece of code

```php
            if ($requiredSchemes) {
                $schemeMatched = false;
                foreach ($requiredSchemes as $requiredScheme) {
                    if ($scheme === $requiredScheme) {
                        $schemeMatched = true;
                        break;
                    }
                }
                if (!$schemeMatched) {
                    $referenceType = self::ABSOLUTE_URL;
                    $scheme = current($requiredSchemes);
                }
            }

```

When the current scheme doesn't match any of the required schemes, it uses `current($requiredSchemes);`

The foreach moved the pointer of that array _past_ the last element, so current will return false.

See the output of this small test script.

```php
$scheme = 'ftp';
$requiredSchemes = ['http', 'https'];

$schemeMatched = false;
foreach ($requiredSchemes as $requiredScheme) {
  if ($scheme === $requiredScheme) {
    $schemeMatched = true;
    break;
  }
}
if (!$schemeMatched) {
  $scheme = current($requiredSchemes);
}

var_dump($scheme);
```

This outputs `bool(false)` rather than `string(4) "http"`

By the way, the code seems overly complex, this should also work for the intended purpose:

```php
if (!in_array($scheme, $requiredSchemes, true)) {
    $scheme = reset($requiredSchemes); // current would actually work here as well
}
```

**Comment by WouterJ** [comment]
There is a small difference between your small test and the actual situation: `$requiredSchemes` is a function parameter in the actual situation. And this makes all the difference for PHP <7.0: [test script run with function parameter](https://3v4l.org/bRqfa) and [test script run with local variable](https://3v4l.org/jsMNh). This means that there is *no bug* in this script.

However, I agree with you that it can be simplified a lot. It would be great if you can make a PR against the 2.3 branch to improve these lines.

**Comment by WouterJ** [comment]
Status: Works for me
