### ISSUE TITLE
Consider improving the "branch" row in the PR table

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18128]
Today a lot of newcomers are contributing for the first time to Symfony. They are doing it great ... except for one minor thing. Most of them leave the original message of the `Branch` row in the PR table:

![pr_branch](https://cloud.githubusercontent.com/assets/73419/13723816/d9e74996-e870-11e5-8e87-64472604ab71.png)

Maybe someone native, such as @weaverryan, can help us reword this message so users understand that they must do something about that row.

**Comment by HeahDude** [comment]
We could maybe add a "?" => `Branch?` as for the others ? or rename in to the more common `Version?` ?

**Comment by HeahDude** [comment]
Or a choice `Version? master (for features and deprecations) | 2.3 | 2.7 | 2.8 | 3.0`

**Comment by WouterJ** [comment]
Please also note that the current sentence is 1 word too long, making it impossible to remove in one go (using shift + end only moves to the end of the input box, not until the next new line). I think this is a bit annoying
