### ISSUE TITLE
[Security] Class Does Not Exist

### ISSUE THREAD

**Issue by ihsanudin** [symfony/symfony#18159]
`https://github.com/symfony/symfony/blob/master/src%2FSymfony%2FBundle%2FSecurityBundle%2FTemplating%2FHelper%2FSecurityHelper.php#L14`

I check the `FieldVote` class is not exist

**Comment by WouterJ** [comment]
You have to install the `symfony/security-acl` package when you use ACL in Symfony.

**Comment by ihsanudin** [comment]
@WouterJ : thanks you very much :+1:
