### ISSUE TITLE
Translations: no "fuzzy" support for the gettext (.po) reader

### ISSUE THREAD

**Issue by nud** [symfony/symfony#18161]
The traditional `gettext` tools usually try to find similar strings when updating translations.

This results in some strings having a translation but being marked as "fuzzy":

```
#. / Template: ../manager/templates/user/profile/vop.html.twig:8
#, fuzzy
msgid "Please put your username or extension."
msgstr ""
"Veuillez vérifier qu'il n'existe pas d'autre utilisateur avec le même "
"identifiant ou la même extension."
```

The expected result when a string is marked as fuzzy is that it should not be used by the translation system. Using symfony, though, the translations are used, which can result in "funny" messages being displayed in the interface despite being often completely out of context.

As a consequence, I think fuzzy support should be added to the gettext support in symfony, and messages tagged with `#, fuzzy` should be discarded.

Beware that sometimes there might be other tags like this and in any order: 

```
#, php-format, fuzzy
```

**Comment by Koalabaerchen** [comment]
What I learned today: XML (xliff) is better at something.

I can confirm the behaviour. It happens in master.

From http://www.gnu.org/software/gettext/manual/gettext.html#PO-Files
`This flag can be generated by the msgmerge program or it can be inserted by the translator herself. It shows that the msgstr string might not be a correct translation (anymore). Only the translator can judge if the translation requires further modification, or is acceptable as is. Once satisfied with the translation, she then removes this fuzzy attribute. The msgmerge program inserts this when it combined the msgid and msgstr entries after fuzzy search only. See Fuzzy Entries. `

Changing the current behaviour is a bit of work (not huge). The PoFileLoader has to be refactored so it observes each message block on it's own and ignore it if it has the fuzzy flag. (and Tests changed/added). But it would also help to get rid of that TODO in there.


But: I'm not sure if it is the right approach ignoring those messages. There would be no feedback as to why the translation is not loaded (we'd have to log). There would be no config.
I'm missing real life application/experience. Are other programs handeling it like that? Would be no translator be surprised that their text is not loaded?

**Comment by nud** [comment]
Well, anyone used to dealing with gettext expects fuzzy translations not to be displayed, because they are likely incorrect.

People only dealing with gettext through the symfony tools will never encounter "fuzzy" tags, because the symfony tools don't generate them. People using other tools (xgettext and msgmerge, poedit and the like) will expect correct behaviour and will get annoyed by the current behaviour.

In my case here, I had a page with completely funky French strings because they were marked as fuzzy but not yet properly translated.

While you are at it there are a lot of useful things to borrow from gettext, including translator comments and the place(s) where the string was found in the code/templates. This alone makes it worth using xgettext/msgmerge over the symfony tools because it eases the translation work A LOT.
