### ISSUE TITLE
[PropertyInfo] Singularize array mutator in ReflectionExtractor

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#18166]
`ReflectionExtractor` currently supports array mutators (`add`, `remove`) but it's not very useful as the singular method name is not being checked.

If we can use `doctrine/inflector` to singularize the property name, we'll be able to pick up a lot more useful information in many cases. I'll open a PR if this is desirable (looking at the `composer.json` of Symfony components, I understand that it has to be an optional dependency).

**Comment by teohhanhui** [comment]
@dunglas

**Comment by dunglas** [comment]
IIRC, the singularized adders and removers should already be used: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L684-L687

**Comment by dunglas** [comment]
Looks like a bug to me. Maybe can we use our own inflector: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/StringUtil.php#L147

**Comment by teohhanhui** [comment]
`symfony/property-info` does not require `symfony/property-access`. So you mean we should suggest `symfony/property-access` just to use its `StringUtil`?

I suspect `doctrine/inflection` would be superior...

**Comment by teohhanhui** [comment]
Of course, the alternative would be just to copy the `StringUtil` from PropertyAccess component, and add a note to keep them in sync.

**Comment by dunglas** [comment]
PropertyInfo and PropertyAccess components are often used together. They must have exactly the same behavior regarding singulars, so they must rely on the same inflection backend.

I'm not a fond of copy/pasting the class. Maybe can we extract the StringUtil class to its own tiny component? /cc @fabpot @webmozart

**Comment by teohhanhui** [comment]
I've just taken another look at this. Maybe we could just use `PropertyAccessorInterface::isReadable` / `isWritable`? An extractor that uses the `PropertyAccess` component seems only logical.

**Comment by teohhanhui** [comment]
@dunglas I noticed that the return value signature for `Symfony\Component\PropertyInfo\PropertyAccessExtractorInterface::isReadable` / `isWritable` is `bool|null`. When should a null value be returned?

**Comment by teohhanhui** [comment]
To answer my own question:

> Maybe we could just use PropertyAccessorInterface::isReadable / isWritable

No. Because that operates at the instance level.

**Comment by webmozart** [comment]
> PropertyInfo and PropertyAccess components are often used together.

@dunglas Does that indiciate that they should probably be in the same package? What about moving the new code from PropertyInfo to the older PropertyAccess component?

**Comment by dunglas** [comment]
@webmozart I've no strong opinion about that. Both components are often used together but they are also commonly used separately. They doesn't solve the exact same problem.

For instance https://github.com/dunglas/php-to-json-schema uses only PropertyInfo and symfony/form (and many other components) only use PropertyAccess.

I usually prefer a set of small decoupled components able to work together than a big monolith.

What would be the benefit to merge both components?

For this specific issue, having a new component (like proposed in #18260) or relying on a third party library (like Doctrine Inflector) looks like a better solution: pluralizing and singularizing words is something very useful and common (e.g. API Platform use Doctrine Inflector for a lot of things, including routing) and isn't related at all with properties.

**Comment by teohhanhui** [comment]
@fabpot This was accidentally closed from the commit message.

**Comment by teohhanhui** [comment]
@webmozart @dunglas

I think it'd be preferrable to use the PropertyAccess component for checking property access (duh...), but currently it only works with an instance. The same functionality is duplicated in PropertyInfo's `PropertyAccessExtractorInterface`.

But I do not agree that PropertyInfo be merged into PropertyAccess, because its purpose is to provide other types of metadata about the property (e.g. Doctrine, PHPDoc). These features would not be a good fit in PropertyAccess.
