### ISSUE TITLE
[Validator][Bug] Email Validation

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#18162]
Hi,

Just to know why a validation on email let 

```email1@gmail.com ; email2@me.com``` 

pass as a valid email ? 

I am on sf 2.8.2

Many thanks :)

**Comment by Triiistan** [comment]
Are you using the email validation with strict option? See here for more details: http://symfony.com/doc/current/reference/constraints/Email.html#strict

**Comment by noniagriconomie** [comment]
@Triiistan hi ty

I think not, i will check and come back
But why is this false by default? it is an error or a required logic that 2 emails are valid

**Comment by iltar** [comment]
The best (and probably only) way to validate an email, is by sending an email towards it. Otherwise the strict=true will be sufficient. It's false by default as it requires a 3rd party library.

**Comment by jakzal** [comment]
@noniagriconomie any news?

**Comment by noniagriconomie** [comment]
I will check this we and come back

**Comment by noniagriconomie** [comment]
@jakzal can not reproduce (validation does not pass even without strict=true), 
it is a bit weird how i get this value in my DB :/
thanks anyway
