### ISSUE TITLE
[BUG] sharedMaxAge calculation problem a page with one of the s-max-age is null

### ISSUE THREAD

**Issue by jean-pasqualini** [symfony/symfony#18160]
Symfony 2.3.16
PHP 5.4.41-0+deb7u1 (cli) (built: May 28 2015 18:22:26)

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/ResponseCacheStrategy.php#L79.

**In the case of a page /example-1**
- Page (s-max-age: 86400)
    - block A (s-max-age: null)
    - block B (s-max-age: 0)

The s-max-age injected by symfony in the response is not 0 but 86400.

Validation by test : php -r "var_dump(min(array(1,2,3,null, 0)));"

**In the case of a page /example-2**
- Page (s-max-age: 86400)
    - block A (s-max-age: 0)
    - block B (s-max-age: null)

The s-max-age injected by symfony in the response is 0.

Validation by test : php -r "var_dump(min(array(1,2,3, 0, null)));"

**Comment by xabbuh** [comment]
In your example what do "block A" and "block B" refer to? Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue? And please also make sure that the issue persists with the latest path version of Symfony 2.3 (2.3.39 which was released yesterday).

**Comment by jean-pasqualini** [comment]
https://github.com/jean-pasqualini/symfony-standard/pull/1/files

**Comment by xabbuh** [comment]
Thanks for providing this great reproducable example. I can confirm that the behaviour doesn't seem to be correct. Can you please check if the fix I proposed in #18164 actually fixes the problem for you?

Status: Reviewed
