### ISSUE TITLE
[process][question / feature request] destructor stops command line command early

### ISSUE THREAD

**Issue by MartinRosserEB** [symfony/symfony#18165]
I want to run asynchronous word - to - thumbnail processing. I am currently offloading the entire processing to a shell command similar to:
process("libreoffice convert inFile to temporaryPdf && convert pdf to img && rm temporaryPdf")

The destructor of this class stops the running process with SIGTERM followed by SIGKILL after a timeout. To achieve what I want, I currently commented out $this->stop() in the destructor.
I would like to be able to circumvent this behaviour, e.g. by setting property disableStopOnDestruct to true. 

I am aware that this will generate orphan processes which will need to be handled at server level.

Any chance to implement this behaviour in the Process package?

**Comment by nicolas-grekas** [comment]
@MartinRosserEB can't you keep the `$process` object around?
Did you try running the process on the background using `&` and the end of the command line?

**Comment by MartinRosserEB** [comment]
@nicolas-grekas difficult to keep the object in my context. The entire application may be left by the user while it is still processing on the command line. Opted for a scheduler mechanism in the meantime: https://github.com/J-Mose/CommandSchedulerBundle . Solved this issue for me. Did not try running the process in the background. Nothing required for me in this case, feel free to close if the feature is not worth the effort.

**Comment by nicolas-grekas** [comment]
Thanks, closing until someone else wants to take the lead on this.
