### ISSUE TITLE
[Yaml] `,` should not be interpreted as a valid number group separator

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#18178]
According to http://yaml-online-parser.appspot.com/, when a `,` is used in a number, it is interpreted as a string.

I don't think I saw anywhere the it should be used as a number separator (for visibility), while in #18096, we can make assumptions that `_` is valid (and also according to the online parser).

But removing this (as it is used only in floats ?) could be a BC break though...

**Comment by javiereguiluz** [comment]
If we currently support something that is wrong according to the Yaml spec, it's OK to deprecate it (and add a BC break in Symfony 4.0), as we did with lots of Yaml features in Symfony 2.8: http://symfony.com/blog/new-in-symfony-2-8-yaml-deprecations
