### ISSUE TITLE
[RFC] Simplify the Email Validator

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18177]
### Problem

  * Validating email addresses is absurdly complex.
  * We've received [tens of issues](https://github.com/symfony/symfony/issues?utf8=%E2%9C%93&q=email+validation) in the past years about this validation.

### Solution

  * Let's simplify the email validator to just check that email addresses "look valid" using a good regexp.
  * If you need to validate that the email is real, send a confirmation email (by the way, do you know any serious service which doesn't send a confirmation email after signing up?).

HTML5 Standard [proposes](https://html.spec.whatwg.org/multipage/forms.html#e-mail-state-(type=email)) this regexp to validate emails:

```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}
[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

### Proposal

  * Update the regexp of the EmailValidator to use the HTML5 regexp
  * Deprecate `strict` option
  * Deprecate `checkMX` option
  * Deprecate `checkHost` option

**Comment by desarrolla2** [comment]
cc/ @egulias

**Comment by Pierstoval** [comment]
IMO, the `checkMX` and `checkHost` should still be available and set to `false` by default. Some private companies / governments want to use these features so it could be good to keep them even if set to `false` by default.

**Comment by nicolas-grekas** [comment]
:+1: but we should take care of BC breaks, that's the difficult part...

**Comment by egulias** [comment]
Hi there.
There are two things you should not use a RegExp for
* parsing HTML
* validating emails

That being said, of course HTML5 one will be "valid" for more of the cases. But, just as an example, that RegExp is saying that `example.@example.com` is valid, which is not. An of course you are not allowing UTF8 emails.
One of the issues, I guess, with the email validation in Symfony is the fact that Swiftmailer has not seen a release in a year and that the validation it uses conflicts with Symfony's one despite being the default email client. v6 of Swiftmailer was supposed to use the same validation than Symfony (it is integrated) but the project is a bit stale right now, correct?

However I do think that replacing the "non strict" with HTML5 regexp will be more useful than the one currently in use.
On `checkMX` and `checkHost` I agree with @Pierstoval

**Comment by dunglas** [comment]
Just my 2 cents. Use filter_var for the simple case and fix it upstream if applicable.

**Comment by patrick-mcdougle** [comment]
I personally think checkMX and checkHost should be kept as well.

**Comment by stof** [comment]
@dunglas fixing it upstream would take years to have a working validation with widespread adoption though (assuming we manage to make upstream change the validation rules of filter_var). And such changes would probably not even be backported to patch releases of previous PHP versions
And currently, filter_var rejects many valid emails (and accepts invalid ones), which is precisely why we stopped using it.

**Comment by JHGitty** [comment]
Please DO NOT try to filter emails in a standard way over regexp or something else. The only thing that would be good is to provide an interface to let the developer choose how to filter email addresses.

Similar discussion in FOSUserBundle: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1923

**Comment by javiereguiluz** [comment]
Closing it because of the lack of recent activity and because it hasn't attracted enough attention from the community.
