### ISSUE TITLE
[Process][Enhancement] Callback allowing parameters

### ISSUE THREAD

**Issue by MartinRosserEB** [symfony/symfony#18171]
`Process->start()` allows to pass a callback function.

It should be possible to pass variables to the callback function as follows:

```php
$process->start(array($class, $method), $var1, $var2);
```

`Process::buildCallback()` is currently optimized to evaluate stdout and stderr. For this reason, it seems not to allow passing variables to the callback function. This would be a very useful addition.

**Comment by xabbuh** [comment]
I am not sure if we need to add this explicitly as you can already achieve this with an anonymous function like this:

```php
$process->start(function() use ($class, $method, $var1, $var2) {
    call_user_func(array($class, $method), $var1, $var2);
});
```

**Comment by nicolas-grekas** [comment]
I agree with @xabbuh , using a closure is the way to go.
