### ISSUE TITLE
[RFC][DI] Decoupling through type mapping

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#18183]
The feature I will describe is meant to solve complex component coupling by using dynamic (configuration-assisted) delegation and/or decoration.

I dont know if the presented solution will be viable from different points of view, but that is up to discussion here.

The solution reuses and extends concepts that are also applied on service autowiring and the feature itself may have been described before in other (non-php) frameworks, but I dont know of any and I came up with this solution while trying to solve problems similar to the ones described in https://github.com/symfony/symfony/issues/6129

The heart of the feature is the following function: `A deduct(B b[, Z z])`,
which either:
- returns an instance of type `A` wrapping the implementation of `b`
- throws an exception

`z` is an optional implementation specific configuration format `Z` which can be used to construct such an instance of type `A`.

The easiest implementation of the given function is the one already used for autowiring:
`if b instance of A then return b else throw exception`

Without the help of additional configuration provided by `c` another implemention may inspect method signatures, the number of members, method names, type names and other type metadata. How reliable the various metrics are, has to be determined.

What could a type `Z` provide to make an implementation more flexible?
A simple way is to provide factories that do exactly the given transformation: `A wrap(B b)`
Not only can the implementation now provide an instance of A for each instance B, but by building the transitive closure over the factories it can provide an instance of A for each instance C given that there is an additional factory: `B wrap(C c)`

Writing those factories and the delegates/decorators used by them, can be very repetitive, but can also be automated, if we can apply an a priori instruction in the config: `A is detuctable from B`. The developer explicitly states that there is a decoration/delegation so a factory `A wrap(B b)` can be built. Whether or not the algorithm used by the `deduct` implementation can actually achieve this or has to error out, will be know at (container) compile time.

The configuration can be extended to also provide specific mappings for all or single members and/or simple argument list transpositions.

**How does this actually help us with decoupling?**
Lets look at the Validator component: it has a dependency to the Translation component, because it uses its interface `Symfony\Component\Translation\TranslatorInterface` at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/ValidatorBuilderInterface.php#L149
Insteadof relying on another package's interface, making it a direct dependency, the Validator component could define its own interface `Symfony\Component\Validator\TranslatorInterface` (which is basically a copy of `Symfony\Component\Translation\TranslatorInterface`, but can also be reduced to just the methods needed for the Validator component) and on service construction use the `deduct` function to get an instance of its own translator type from an already existing translator of the Translations components translator type.

I hope this makes the basic approach somewhat clear. I wont go much further about possible implementations and evaluation of viable metrics until i have some feedback, whether or not this approach is worth following.

**Comment by iltar** [comment]
*I think* I understand what you mean. Let me expand on that example:
 - The validator component would provide a TranslationInterface
 - This interface would implement only what's needed in the package
 - An object implementing this interface would delegate the calls to the TranslatorInterface implementation
   - https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/ValidatorBuilder.php#L335
   - https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Context/ExecutionContext.php#L188

```php
interface ValidatorTranslatorInterface
{
    public function setLocale($locale);
    public function trans($id, array $parameters = array(), $domain = null, $locale = null);
}
```
```php

use Symfony\Component\Translation\TranslatorInterface;

class ValidatorTranslator implements ValidatorTranslatorInterface
{
    private $translator;
    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function setLocale($locale)
    {
        $this->translator->setLocale($locale);
    }

    public function trans($id, array $parameters = array(), $domain = null, $locale = null)
    {
        return $this->translator->setLocale($id, array $parameters, $domain, $locale);
    }
}
```

Now you can type hint against the `ValidatorTranslatorInterface` and it can use the symfony Translator in the background when available.

----

My opinion: This is not something for Symfony. This looks like something generic to solve an optional dependency "issue" within the package eco system. I would love to see something for this but I'm not sure it should be a symfony restricted thing.

That being said, I think it would still be really nice to have, even if it's just in symfony (I know, slightly contradictive).

**Comment by backbone87** [comment]
@iltar you understand it correctly in terms of decoupling, but the main benefit would be that the container can generate the delegator/decorator and its factory for you. you should only need to assist it via configuration on ambiguous or non-trivial delegation cases. thats also the reason why this pattern is tightly coupled to the use of a DI component and cant be implemented "in a generic" way. For the subtasks like code generation, reflection and graph algorithms there are already existing libraries or well-defined algorithms available.

in an optimal use case, given that Translation and Validation components are completely independent of each other and that there is already a working Translator service, it would be enough to just define the ValidatorBuilder service like:
```xml
<service class="Symfony\Component\Validator\ValidatorBuilder" autowire="true" />
```
The delegator to wrap a TranslatorInterface into a ValidatorTranslatorInterface would be generated by the container.

**Comment by iltar** [comment]
In theory you can reverse engineer a class based on the reflection data, so that should be only an implementation/automation detail.

**Comment by nicolas-grekas** [comment]
on which criteria would an instance of Translator's TranslatorInterface be mapped to a ValidatorTranslatorInterface? For sure, we can generate a proxy that does so, but how would we decide that that ValidatorTranslatorInterface can be mapped from a Translator's TranslatorInterface? Yes, there are some signatures in common, but semantically, they may do something different. Would that mean we'd have to maintain a map of which interfaces can be subsetted to which other ones?

Looks obscure to me for now :)

**Comment by backbone87** [comment]
Thats exactly the question, which is up to discussion: Which strategies are viable and feasible to map a TranslatorInterface to a ValidatorTranslator interface? You can split the problem in 2 sub tasks:
- Can Interface X mapped to Interface Y?
- How is Interface X mapped to Interface Y? 

To keep it in the Symfony pragma of being explicit, the first question should be answered by configuration, while the second can be solved by well defined strategies that take signatures and other available information like method names into account.

Still this is just an idea, and it may not be viable to add this feature.

**Comment by jakzal** [comment]
Firstly, introducing such an indirection in Symfony itself wouldn't be viable at this point as I can't see how this could be implemented in a BC way without obscuring the code with lots of BC layers.

Secondly, in my own code I'd prefer to explicitly write an adapter from one component to another, rather than have it automatically generated for me. It's almost never as simple as proxying to the decorated service. And if it is, I might as well rely on the other interface directly. I'll have an integration test for this anyways.

Perhaps I didn't fully understand the use case, but at this point I'm :-1:

**Comment by chalasr** [comment]
Given the lack of reactions and we are able to solve this problem differently (writing adapters in userland) I don't think it's worth pursuing either.

**Comment by backbone87** [comment]
No problem, this wasnt a fully thought through idea anyway, but i was curious about responses and maybe others picking up on it.

I am closing this, but just some final note: The primary goal of this idea was to fully remove intercomponent dependencies, which the "half-automatic adapter generation" is an important part of, but not the main purpose.

**Comment by jakzal** [comment]
> The primary goal of this idea was to fully remove intercomponent dependencies

I'm afraid dependencies would still be there. Just hidden!

**Comment by backbone87** [comment]
From an architectural standpoint, the dependencies are gone, but instead you require an implementation (of your own interface). In end ofc, someone "has to do the work".

There was a ticket that proposed separating the TranslatorInferface into an own package, because they required the Translator component just for the interface to be used by the Validator component, but have their own translation component.
