### ISSUE TITLE
[DI] Autowiring causes a fatal error for optional services

### ISSUE THREAD

**Issue by hason** [symfony/symfony#18188]
I use Symfony components and bundles without forms. Autowiring causes the fatal error for [``twig.form.engine``](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L124) service from TwigBundle:

```PHP Fatal error:  Class 'Symfony\Component\Form\AbstractRendererEngine' not found in ...```

We should replace [``ReflectionClass``](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L265) with [phpdocumentor/reflection](https://packagist.org/packages/phpdocumentor/reflection) or another library for static reflection.

**Comment by dunglas** [comment]
Instead of using phpdocumentor/reflection (it's slow...), maybe can we just check that the class exist before creating the ReflectionClass, or add a try/catch.

**Comment by dunglas** [comment]
But the question is: why the autowiring system try to parse the class of `Symfony\Bridge\Twig\Form\TwigRendererEngine` as this is not an autowired service?

**Comment by xabbuh** [comment]
@hason Would you be able to create an example project that makes it possible to reproduce your issue?

**Comment by hason** [comment]
@dunglas It is necessary to check existence of all parent classes and interfaces => static reflection :smile:. Try/catch is unable to catch Catchable fatal error.

Autowiring is enabled for my controllers and so it has to analyze all registered services. Unfortunately, even unused services.

**Comment by dunglas** [comment]
It's weird that it analyses arguments of an usused service. Can you provide a failing test to help us debugging?

**Comment by hason** [comment]
No, it analyses arguments of my controllers only. But has to know all types of all services https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L136

**Comment by dunglas** [comment]
Ok got it. I'll open a PR with a fix tomorrow.
