### ISSUE TITLE
Update symfony screenshots

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#18219]
The screenshot(s) at http://symfony.com/logo should be updated with the awesome new profiler look.. right?

**Comment by javiereguiluz** [comment]
@ro0NL you are right. Thanks for the heads up. I'll take care of it.

**Comment by javiereguiluz** [comment]
The screenshots have been updated and they'll be available on symfony.com after the next application deploy. Thanks!

**Comment by stof** [comment]
I'm closing this so this won't stay forgotten, as the change has been done.
