### ISSUE TITLE
[Validator] [docBlock] Is constraint defined on option or property?

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#18218]
Here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraint.php#L22
the docblock says:
> A constraint can be defined on a class, **an option** or a getter method.

What does applying constraint on *an option* mean? Shouldn't it say on *a property*?

**Comment by javiereguiluz** [comment]
@sustmi I think you are right. In this context, "option" makes no sense and it should be "property".

Since you already have experience contributing to Symfony, could you please open a PR to fix this? It should be created for Symfony 2.3. Thanks!
