### ISSUE TITLE
Symfony 2.8 app.security not available in Twig template

### ISSUE THREAD

**Issue by DavidSoussan** [symfony/symfony#18223]
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The "app.security" variable is not available.") in SonataAdminBundle::standard_layout.html.twig at line 183.

Not just in Sonata Admin, in any twig template

 Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The "app.security" variable is not available.") in FCPortalBundle:Default:index.html.twig at line 7

INFO - The "app.security" variable is deprecated since version 2.6 and will be removed in 3.0. 

Apparently you have jumped the gun and removed it in 2.8

**Comment by stof** [comment]
Looks like the container is not injected properly: https://github.com/symfony/symfony/blob/0c019035597e9b5a4cb8c0227d66fa97a235298a/src/Symfony/Bridge/Twig/AppVariable.php#L69

**Comment by stof** [comment]
@fabpot the issue is in https://github.com/symfony/symfony/commit/bf066dace2922cf1ce335f5f683fc63d5a7e23c2 which broke the BC layer as the container is not injected anymore.

**Comment by xabbuh** [comment]
@DavidSoussan I cannot reproduce your issue with the latest 2.7 patch release. Which exact version did you use? Are you able to fork the Symfony Standard Edition and make the changes that are necessary to reproduce this?

**Comment by jakzal** [comment]
I also cannot reproduce this (tried on dev version of 2.8, which was the reported version). 

Feel free to provide a failing example and we'll reopen the issue.
