### ISSUE TITLE
Form DateTimeType is not calling the entity setter

### ISSUE THREAD

**Issue by javitoxhz** [symfony/symfony#18221]
I have an entity like this:

```php
class Project {
    // Property with ORM Annotation
    private $startDate;
  
    // Setter
    public function setStartDate($startDate)
    {
       throw new \Exception("This is not called, and i need to");
    }
}
```

And a form type like this:

```php
class ProjectType extends AbstractType {

     /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('startDate', 'datetime', [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd HH:mm:ss',
            ])
        ;
}
```

But I cannot make the form call the setter. When i do the same thing with another type, like a string property, the setter is called, but not when it's a datetime.

**Comment by HeahDude** [comment]
Hi @javitoxhz, I could not reproduce your issue in symfony 2.7.10. Which version are using ?

Have you set the `data_class` option ? It might help the component using the right property access:
```php
class ProjectType extends AbstractType
{
    // ...

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('data_class', 'AppBundle\Entity\Project');
        // ...
```

**Comment by javitoxhz** [comment]
I found my problem.

**Datetime form type** don't call the setter if the new \DateTime is the same than the old \DateTime. I tried with another value and it worked.

Thanks.
