### ISSUE TITLE
random_compat 2.x not allowed?

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/symfony#18226]

**Comment by nicolas-grekas** [comment]
please submit a PR

**Comment by GrahamCampbell** [comment]
It has breaking changes, which, out of the box will break symfony 2.3 apps I'm afraid. That's why laravel has decided not to upgrade to this.

**Comment by GrahamCampbell** [comment]
Or even to allow `~1.0|~2.0` for example.

**Comment by GrahamCampbell** [comment]
Since that will break existing apps.

**Comment by Tobion** [comment]
Closing as this belongs to https://github.com/symfony/polyfill

**Comment by Tobion** [comment]
Actually it would need to be changed for both symfony and polyfill as both require random_compat.

**Comment by GrahamCampbell** [comment]
> Actually it would need to be changed for both symfony and polyfill as both require random_compat.

Yeh. It's only in symfony/symfony that allowing 2.x would potentially cause issues with existing apps.

**Comment by GrahamCampbell** [comment]
It would be good to have your feedback on whether 2.x there actually is a needed security fix, and is worth breaking apps for. Taylor and I decided to revert the openssl removal patch to earlier laravel versions for now because of insufficient evidence, and stuff breaking.

**Comment by Tobion** [comment]
Why would it break existing apps? All symfony cares about is a polyfill for the random functions. The internals are not important.

**Comment by GrahamCampbell** [comment]
It would break apps "by default" if the server has no secure random source, were as before, they would fallback to openssl.

**Comment by xabbuh** [comment]
If we allowed 2.0, we could still use the Symfony requirements to suggest the user to manually require 1.x if we discovered that the server is not suitable for 2.0 (and emit a warning to better update the server config).

**Comment by GrahamCampbell** [comment]
I guess. People don't always see it that way though. ;(

**Comment by derrabus** [comment]
There's already an open PR: symfony/polyfill#44

Symfony itself is compatible with version 2, so Symfony should imho not prevent the upgrade by pinning version 1. Applications that have to be run in environments incompatible with version 2 can be marked incompatible with version 2 via their own composer.json:

```json
"conflict": {
    "paragonie/random_compat": ">=2"
}
```

**Comment by GrahamCampbell** [comment]
I see that got merged.
