### ISSUE TITLE
[PHPUnitBridge] Provide option to disable DeprecationErrorHandler

### ISSUE THREAD

**Issue by slootjes** [symfony/symfony#18222]
I'm working on a 2.8 project and some bundles are using deprecated functions which causes a lot of "Remaining deprecation notices" after outputting my test results. I would like to see an option to disable the DeprecationErrorHandler in general so no output is done at all regarding deprecation warnings.

I think there are roughly 2 options:
- Add a "SYMFONY_DEPRECATIONS_HELPER_DISABLE" environment variable so the handler is not registered
- Add a "SYMFONY_DEPRECATIONS_HELPER" = "none" option so the handler doesn't do anything

For me option 1 would seem the make the most sense, why load the handler in the first place if you don't want to use it right? :)

Just to be clear: I am aware of the "weak" option but my project will run for a few month tops so I am not interested to migrate to 3.0 standards in this case.

**Comment by theofidry** [comment]
:+1: for option 1; the weak option is no good if you want to use your application custom error handler (even for tests).

**Comment by nicolas-grekas** [comment]
Could you elaborate on the issue with weak mode? Also, why did you enable the bridge in the first place?

**Comment by slootjes** [comment]
The issue with weak mode is that it is still outputting a lot of messages on my screen which make me need to scroll back to see if my tests succeeded or not which is very annoying.

I am not aware that I can disable the bridge, I guess it does a lot more than just enabling this deprecation handler right?

**Comment by nicolas-grekas** [comment]
Can you please share a the report you get in weak mode? (In a gist maybe?)

**Comment by slootjes** [comment]
Sure: https://gist.github.com/slootjes/e1462f3e74eaa50e068d

But imo it's not about the output itself. I know I am using deprecated functions (or bundles that do) but I do not care to upgrade to Symfony 3 for this project anyway so I want to be able to ignore those in general.

**Comment by nicolas-grekas** [comment]
Can you please send me the output of running this?
`SYMFONY_DEPRECATIONS_HELPER=weak phpunit`

**Comment by nicolas-grekas** [comment]
The gist you just sent is not in weak mode (weak mode doesn't display the list of deprecation messages)

**Comment by slootjes** [comment]
When adding the "SYMFONY_DEPRECATIONS_HELPER=weak" to my user environment it doesn't list the messages but only: Remaining deprecation notices (70) which is a lot better.

I had added:

<env name="SYMFONY_DEPRECATIONS_HELPER">weak</env>

to my phpunit.xml.dist which obviously didn't do the trick for me. Is this a bug in PHPunit then perhaps?

**Comment by nicolas-grekas** [comment]
can you share your phpunit.xml config then?

**Comment by slootjes** [comment]
https://gist.github.com/slootjes/eb3747923898394cfaa1

**Comment by nicolas-grekas** [comment]
I guess you're using an older phpunit version that is affected by https://github.com/sebastianbergmann/phpunit/issues/1216

**Comment by slootjes** [comment]
I was convinced that this was causing it but even with latest version I experience this:

> phpunit --version
PHPUnit 5.2.12 by Sebastian Bergmann and contributors.

In PhpUnit Bridge bootstrap.php I added:
var_dump(getenv('SYMFONY_DEPRECATIONS_HELPER'));die;

> phpunit
string(0) ""

Although this seems to be more of a phpunit issue than a Symfony issue I still think an option to disable the output in general would be nice.

**Comment by nicolas-grekas** [comment]
The output should be either `false` or `weak`. The empty string means the env var is set, to the empty string. Looking a second time at your phpunit.xml file, the syntax is wrong. You should use:
`<env name="SYMFONY_DEPRECATIONS_HELPER" value="weak" />`

**Comment by slootjes** [comment]
You are absolutely right, thanks! With that syntax it's detecting the correct value. Stil, like I said it would be nice to be able to disable the helper in general, what's the best way to accomplish that?

**Comment by nicolas-grekas** [comment]
Can you please try commenting the line enabling the helper in bootstrap.php and explain why you think the resulting behavior is better in your case?

**Comment by slootjes** [comment]
The difference, as expected, is the: "Remaining deprecation notices (70)" in highlighted red in my console. For me it does not any value to have that, I just want to see that my tests passed and because of that I think an option to disable it completely would be nice. It could be accomplished very easily and I want to do a PR but I think it's good to know what method is preferred.

**Comment by nicolas-grekas** [comment]
If the issue is only this line, then we could just change its color, or even not display it in weak mode. More importantly, what the bridge also does in weak mode is catch unsilenced deprecations. Your test suite happen to work without the bridge because your code is triggering only symfony style deprecations (ie silenced ones). But not every package is something their deprecations. Without the bridge, you'll get an exception by default.

**Comment by slootjes** [comment]
I assumed it did more than only displaying those messages, that's why I didn't create a PR directly. Maybe a "silenced" option next to "weak" is something which could be added?

**Comment by WouterJ** [comment]
I don't  think we should add any more modes besides the current weak, number, regex stuff. Removing color from "weak" mode seems like a nice idea to me.

**Comment by theofidry** [comment]
When not just enabling to disable it? After all you may be using the bridge for the time mocking and not the deprecation helper right?

**Comment by slootjes** [comment]
I think it's good to have the option to disable something I don't want. It's not only the color but the message itself too thats bothering me. I know it doesn't matter that much but it's just stuff I don't want to see because it's irrelevant to my project.

**Comment by nicolas-grekas** [comment]
I mostly agree with @WouterJ 
Still, see #18232

**Comment by slootjes** [comment]
Looks great to me :)

**Comment by slootjes** [comment]
Thanks for implementing this so fast @nicolas-grekas :)

**Comment by rifzy** [comment]
I have a problem using this feature

The env variable is set to disable and i still get deprecation notices 
i'm using symfony 2.8 and phpunit 5.7.20

does someone have any idea how to fix it ?
