### ISSUE TITLE
Phpunit memory leak

### ISSUE THREAD

**Issue by chandon** [symfony/symfony#18236]
We're using Symfony 2.7.10. We have issues with memory leak when loading Doctrine in our phpunit tests.

Starting from Symfony's documentation : http://symfony.com/doc/2.7/cookbook/testing/doctrine.html we have written this test :

```php
    use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

    class memoryleakTest extends KernelTestCase
    {
        private $em;

        protected function setUp()
        {
            self::bootKernel();

            $this->em = static::$kernel->getContainer()->get('doctrine');                          
        }

        protected function tearDown()
        {
            parent::tearDown();

            $this->em->close();

            gc_collect_cycles();
        }

        function testEEE1()  { 
        }
        function testEEE2()  { 
        }
        function testEEE3()  { 
        }
        function testEEE4()  { 
        }
        function testEEE5()  { 
        }
        function testEEE6()  { 
        }
        function testEEE7()  { 
        }
        function testEEE8()  { 
        }
        function testEEE9()  { 
        }
        function testEEE10()  { 
        }
        function testEEE11()  { 
        }
        function testEEE12()  { 
        }
        function testEEE13()  { 
        }
        function testEEE14()  { 
        }
        function testEEE15()  { 
        }
        function testEEE16()  { 
        }
    }
```

we got this result (php_memory_usage between parenthesis) :

    testEEE1: . (42M)
    testEEE2: . (42.7M)
    testEEE3: . (43.3M)
    testEEE4: . (44M)
    testEEE5: . (44.8M)
    testEEE6: . (45.5M)
    testEEE7: . (46.1M)
    testEEE8: . (46.8M)
    testEEE9: . (47.4M)
    testEEE10: . (48.1M)
    testEEE11: . (48.7M)
    testEEE12: . (49.4M)
    testEEE13: . (50.1M)
    testEEE14: . (50.7M)
    testEEE15: . (51.4M)
    testEEE16: . (52M)

If we comment/remove:

    // $this->em = static::$kernel->getContainer()->get('doctrine');

we got (32,7M) for each test and no memory leak.

Is it a proper way to unload doctrine (or services) and kernel after each test in the teardown function ?

**Comment by nicolas-grekas** [comment]
Is it better if you do $this->em = null; before gc_collect_cycles?

**Comment by theofidry** [comment]
and shouldn't you do this call before the `parent::tearDown()`?

**Comment by chandon** [comment]
@nicolas-grekas You're right, this solves the problem, no memory leak anymore ! thanks

@theofidry it doesn't change anything to my problem, but i think youre right.

Perhaps  http://symfony.com/doc/2.7/cookbook/testing/doctrine.html should be updated ?
