### ISSUE TITLE
Reset Profiler data after each request for PHP-PM

### ISSUE THREAD

**Issue by marcj** [symfony/symfony#18244]
Hi!

I'm currently trying to optimize Symfony usage in https://github.com/php-pm/php-pm.

One of those optimizations is to get the correct debugging information in the profiler. Currently after each request only the execution time is correctly calculated. All other stuff like logs, template render times, query logging etc are not reseted after Kernel::terminate(). What we currently do is along these lines: https://github.com/php-pm/php-pm-httpkernel/blob/master/Bootstraps/Symfony.php#L71-L100
I know it's a hack and don't get any support through semver as we hack into the object, but for the moment the only fast way to get things working. If it's working we could provide a pull requests to get this inside Symfony with well defined interfaces.

First Request:
![screen shot 2016-03-21 at 00 24 13](https://cloud.githubusercontent.com/assets/450980/13908043/493766e2-eefb-11e5-8e94-bb5989db4132.png)

9th Request
![screen shot 2016-03-21 at 00 20 13](https://cloud.githubusercontent.com/assets/450980/13908036/2889ad9c-eefb-11e5-9a0f-be94aab851e7.png)

Any ideas?

//Edit
We get for each new request a new Debug-Token, as expected.

**Comment by iltar** [comment]
I'm unfamiliar with what you're doing but if my assumption is correct, it means that you don't close the request/terminate symfony? Could you explain a bit more about the challenge you're facing?

**Comment by marcj** [comment]
> it means that you don't close the request/terminate symfony

What do you mean with 'close the request' or 'terminate symfony'? We do close the request by calling `Kernel::terminate($request, $response);`, but we do not shutdown the Kernel, which should not be necessary as we need the kernel for further requests.

**Comment by stof** [comment]
@marcj not shutting down the kernel also means that you reuse the same Container instance all the time. This is what could cause issues in several places (and it is exactly what causes issues here). Several collector services are stateful, and so would keep the data and mix them with the next request in the profiler. You will also have issues with the FingersCrossedHandler of Monolog for instance.

Rather than trying to list all places where a cleanup would be necessary at the end of the request (which is quite painful as there is no such listing today, and any bundle could contain such a place), have you tried to look at the performance impact of calling ``$container->reset()`` to perform a complete cleanup (you will still need to reset the start time though) ? It may be much easier for now, if the perf impact is acceptable.
Note that ``ResettableContainerInterface`` is only available as of Symfony 2.8, but you can detect whether the container supports the feature by checking whether it implements the interface.

**Comment by marcj** [comment]
Instead of doing https://github.com/php-pm/php-pm-httpkernel/blob/master/Bootstraps/Symfony.php#L90-L99 I tried `$app->getContainer()->reset()` but this breaks with the exception `You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service.` after the second request.
I also tried `$app->shutdown()`, but this makes it terrible slow again.

**Comment by stof** [comment]
ah right, the kernel sets itself only during the initial creation. Try this then:

```php
$app->getContainer()->reset();
$app->getContainer()->set('kernel', $app);
```

**Comment by marcj** [comment]
> Rather than trying to list all places where a cleanup would be necessary at the end of the request (which is quite painful as there is no such listing today, and any bundle could contain such a place)

It is indeed painful and quite a bit of work, but I think it's the only way to keep this whole approach alive and to keep the good performance. But I believe it's time to make this list now :) Maybe PHP-PM is the starting shot for it.

I just tried the latest comment with `set('kernel', $app)`, this works, but makes it again very slow. I guess it's almost equal to shutdown except the `boot` calls to all bundles (which is important when you reset the container, at least in one of my applications). I guess resetting the container is not the right way to go, although I'd be perfect if it wouldn't hurt the performance so much as it could be more compatible. However, I guess I need to investigate deeper.

Any other hints where I can reset the profiler?

**Comment by marcj** [comment]
Ok, I know now why those stats don't get reseted. The `DataCollectorInterface` has only the method `collect` which most DataCollector implementations have in a way implemented that they don't delete the stuff when `collect` is called. This would be currently the only way to keep the memory clean, but would not be perfect, as a second call would return reseted data. A new method `DataCollectorInterface::clean` would solve that issue, but would obviously take too much time until all implementations have updated, so the only way is currently to reset the services and dependencies in the container.

**Comment by marcj** [comment]
I have done now some really nasty hacks, but works so far.
https://github.com/php-pm/php-pm-httpkernel/commit/d6199a56530eb177fe16db4527d59f0da3420a0d#diff-4e4aadfdc2edbd7dfe3479c6259178eaR86

What do you guys think about making this more pretty by introducing some new API methods to the DataCollector stuff? FrameworkBundle/ProfilerListener could call a method like `clear` on onKernelTerminate which basically cleans all data collectors.

**Comment by iltar** [comment]
You could solve it with something like `DataCollectorResetInterface::reset()`.

**Comment by inso** [comment]
@marcj maybe you can try to reset state of data collectors using reflection?

**Comment by fabpot** [comment]
@marcj Making Symfony work better with solution like php-pm is always a good idea. I spent a lot of time a few years back to make sure that Symfony does not leak memory, and we should continue this work. Adding some clean method in the master branch would not solve your immediate problem but makes Symfony stronger in the long term, which is great.
