### ISSUE TITLE
[Process] Silent behaviour change if folder doesn't exist

### ISSUE THREAD

**Issue by shopblocks** [symfony/symfony#18249]
In Process, the second parameter is the `cwd`. If this folder doesn't exist, it seems to run a getcwd.

This should initiate / throw a warning or exception, since the behaviour change is / can be critical.

For us, we were performing git clone into a folder, but the folder doesn't exist, so it clones into the folder where console is ran from. This is on ~3.0

**Comment by iltar** [comment]
It's a bit weird that you can set the cwd via the constructor *and* via the setter. Both have slightly different behavior.

**Comment by jakzal** [comment]
@shopblocks are you suggesting the behaviour was different in previous Symfony versions?

**Comment by shopblocks** [comment]
Im afraid this is the first version I have tested this with, so do not know whether it is different to previous versions or not.

**Comment by jakzal** [comment]
`proc_open()` won't change the working directory if it doesn't exist. It would be a BC break if we started throwing an exception.

**Comment by xabbuh** [comment]
We could trigger a deprecation in 3.2 when a non-existing directory is to be used as the working directory and throw an exception in 4.0.

**Comment by nicolas-grekas** [comment]
@shopblocks would you like to submit a PR triggering that deprecation?

**Comment by alexbowers** [comment]
I'm not sure what you mean by that. What is deprecated? The unexpected behaviour?

**Comment by nicolas-grekas** [comment]
It's not deprecated yet, but the unexpected behavior could be yes.

**Comment by alexbowers** [comment]
Okay, i'll take a look at this.
