### ISSUE TITLE
[PhpUnitBridge][Question] Set value of the deprecation helper

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18253]
I'm trying to set the deprecation helper value via my PHPUnit config:

```xml
<php>
  <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak"/>
</php>
```

Or a numerical value, but I can't see any difference. If I do a dump in the `DeprecationErrorHandler`, I can see that the `$mode` passed is `false`.

Did I miss something? I'm running a regular Laravel application and little PHPUnit config (bootstrap file, and colors and forceCoversAnnotation set to true).

**Comment by nicolas-grekas** [comment]
with which phpunit version?

**Comment by theofidry** [comment]
My bad: PHPUnit 5.2.12 on PHP 5.6.18.

Also if I run the tests locally, and get the return (via `echo "$?") I get `1` (as expected, the default config does not make the tests fail if a deprecation notice is reported). But on Travis the build is marked as failed and stops after the PHPUnit steps.

**Comment by nicolas-grekas** [comment]
you ist have an issue with your phpunit.xml file
does it work if you configure the env var through the env section of you travis file ?

**Comment by theofidry** [comment]
Here's the whole PHPUnit config file for reference:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.2/phpunit.xsd"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         forceCoversAnnotation="true">

    <testsuites>
        <testsuite name="App tests">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory suffix=".php">legacy/</directory>
            <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>

    <php>
        <env name="APP_ENV" value="test"/>
        <env name="DB_DATABASE" value="test"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>

        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak"/>
    </php>
</phpunit>
```

Testing via the Travis environment variable

**Comment by theofidry** [comment]
The Travis test still fails with `env: SYMFONY_DEPRECATIONS_HELPER="weak"`... but I did not see any deprecation message:

<img width="513" alt="screen shot 2016-03-21 at 15 35 33" src="https://cloud.githubusercontent.com/assets/5175937/13924037/acc79d06-ef7a-11e5-8c39-d11f049885fa.png">

Before setting the `SYMFONY_DEPRECATIONS_HELPER` environment (via Travis `env` key or the PHPUnit config file), I could see the deprecation message.

**Comment by theofidry** [comment]
Retried just in case, if I set `SYMFONY_DEPRECATIONS_HELPER` in the `phpunit.xml` file, I get back a deprecation notice and Travis still fails as well... I'm on IRC if you need more info

**Comment by nicolas-grekas** [comment]
@theofidry can't reproduce.

**Comment by theofidry** [comment]
@nicolas-grekas I'll try to look more into it this week

**Comment by theofidry** [comment]
Ok looks more like an issue on my end, somehow PHPUnit is not setting my environment variables right. For example if I do `dump(getenv('APP_ENV'));die;` in my test `setUp()` method, it gives me `dev` instead of `test`. But if I add a new environment variable, ex `<env name="FOO" value="bar"/>`, `getenv('FOO')` gives `'bar'` as expected.

So I'm lost at **why** this is happening, but it's unlikely the bridge fault.

**Comment by stof** [comment]
@theofidry I think setting an environment variable when calling PHPUnit wins over env variables defined in the phpunit.xml file. Check whether you have ``APP_ENV`` defined in your shell

**Comment by theofidry** [comment]
@stof indeed it is. Damn, now I have to track down *where* this variable is set in my shell (as it doesn't happen to me only) :P Thanks for the help!
