### ISSUE TITLE
[PhpUnitBridge] Display deprecation notices messages only in verbose mode

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18251]
By default in PHPUnit skipped and incorrect tests are marked as skipped and incorrect, but the message is not displayed unless you set it in `verbose`. I would only find logical that it would be the same behaviour of the deprecation report.

That being said that may be a BC break and require to access to PHPUnit configuration for configuring PHPUnitBridge, and I have no idea of its feasibility.

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
IMHO, there would be no benefit in doing so, in terms of added value for anyone. The goal of the bridge is to help move forward with deprecations. It fulfills this goal. The bridge already has options for controlling its behavior and personally I'm not interested into building a perfect integration with phpunit. If anyone thing this is really important then of course we'd all be happy to review PRs.

**Comment by nicolas-grekas** [comment]
I also think that  any better integration with phpunit should land into phpunit itself. If anyone wants to take ideas from this bridge, submit PRs on phpunit, we'd all be happy to deprecate the bridge when phpunit natively provides the required features!
