### ISSUE TITLE
composer update should copy in bin/console bin/symfony_requirements

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony#18258]
Prior to `3.0.*` we had this in `composer.json`

```
"config": {
        "bin-dir": "bin"
    },
```

Many of us who have ongoing projects have been ignoring the whole `bin/` directory in our projects for VCS purposes. 

Now with 3.0.0 you moved `console` and `symfony_requirements` into the `bin/` and we need to check them into our VCS (we happen to use Subversion).. You also removed the `bin-dir` key from the default `composer.json`. 

This is problematic because most of us using the `bin-dir` key have been relying on it for all the phars to end up in the `bin` directory, for example `phpunit`, `phing`, etc. But we definitely do not want to check them all in.

I'm aware I can move the two files into `app/` instead and check them in `bin/`, but I would like to stay true to the new directory structure if that is your vision.

One solution I could see is would it be possible for the files to please be added to `bin/` from the composer dependencies like they do for `phpunit` etc?

I am aware that means adding `bin-dir` back in to `composer.json`, but at least it won't completely break our toolchain if we want to follow the new format.

I tried to search for this issue already but couldn't find it, just another one where they were confused why the programs disappeared as they had assumed they could safely delete `bin`.

**Comment by ofbeaton** [comment]
To give you a better idea why this is a huge usability mess, I went ahead and added my `bin/` to my SVN, then set my ignore inside to `*`. Then I manually added `console` and `symfony_requirements` anyways.

I dev on windows and linux (because phpstorm isn't perfect at using all tools on the server yet) so I do run `composer update` on my windows once in awhile. That meant my `bin/` was full of `phpunit`, `phing` and phar tools I use during development.

I go ahead and upload everything except my vendors, because now I have to upload my `bin/`, and run `composer install` on my linux box. Except `phpunit` doesn't write it's file into `bin/` because it has an apparently name conflict with a the existing file I uploaded, no problem, they should be identical right? Except all the files I uploaded from windows don't get +x file permissions, because windows. So now I have to +x the whole thing. Then it works.

As you can see, this is a lot of stress and hassle over previous versions. I don't believe `bin/` should  be something you have to upload, it should be transient like `vendors/` and now most of `var/`. This was the existing workflow.

Please please please just make Symfony install `console` and `symfony_requirements` into the composer bin during a `composer update/install` like the following composer projects that already install into our `bin/`s:
- `security_checker` (from the symfony composer.json)
- `doctrine` (from the symfony composer.json)
- `phpunit` (from the symfony composer.json)
- `apigen`
- `phing`
- `phpcs`
- `pdepend`
- `phpmd`
- `humbug`

Thank you for your time.

**Comment by iltar** [comment]
Currently in git we ignore the `/bin/` directory except for an already added console file. I agree this is rather counter-intuitive and feels weird. Considering the console file is supposed to be an entry point, what about a file in your app/ or src/ that gets symlinked (or copied) towards bin to act as all the other bins? I would love to have a console.php, even if it was just for the code highlights.

**Comment by ofbeaton** [comment]
Right, it doesn't make sense to me why `console` and `symfony_requirements` don't just symlink into vendor like everything else. Here's my bin.

```
[root@myserver]# ls -lha bin
total 16K
drwxr-xr-x.  2 root root 4.0K Mar 22 14:06 .
drwxr-xr-x. 11 root root 4.0K Mar 22 14:05 ..
-rw-r--r--.  1 root root  877 Feb 28 21:54 console
lrwxrwxrwx.  1 root root   35 Mar 22 14:05 doctrine -> ../vendor/doctrine/orm/bin/doctrine
lrwxrwxrwx.  1 root root   41 Mar 22 14:05 doctrine-dbal -> ../vendor/doctrine/dbal/bin/doctrine-dbal
lrwxrwxrwx.  1 root root   39 Mar 22 14:05 doctrine.php -> ../vendor/doctrine/orm/bin/doctrine.php
lrwxrwxrwx.  1 root root   41 Mar 22 14:05 pdepend -> ../vendor/pdepend/pdepend/src/bin/pdepend
lrwxrwxrwx.  1 root root   31 Mar 22 14:05 phing -> ../vendor/phing/phing/bin/phing
lrwxrwxrwx.  1 root root   49 Mar 22 14:05 phpcs -> ../vendor/squizlabs/php_codesniffer/scripts/phpcs
lrwxrwxrwx.  1 root root   35 Mar 22 14:05 phpmd -> ../vendor/phpmd/phpmd/src/bin/phpmd
lrwxrwxrwx.  1 root root   46 Mar 22 14:05 phpunit -> ../vendor/phpunit/phpunit/composer/bin/phpunit
lrwxrwxrwx.  1 root root   54 Mar 22 14:05 security-checker -> ../vendor/sensiolabs/security-checker/security-checker
-rwxr-xr-x.  1 root root 3.9K Mar 22 14:06 symfony_requirements
```

**Comment by stof** [comment]
The ``console`` script is part of your root project. It cannot be shipped from a dependency (it is something which depends on classes defined in the root project).

Mixing bins of your dependencies (managed by Composer) and bins of the project generally ends up being a nightmare. This is why symfony-standard now keeps the composer default value putting the composer-managed bins in ``vendor/bin``. In the SE, ``bin`` contains only project-based bins (``symfony_requirements`` is managed as a project-based bin, as the goal is to be able to run it before running composer, to start by checking requirements)

If you want to keep using ``bin`` for all composer-managed bins, you are free to do so, but you should then manage your project for that. You could even try to write a composer hook doing the symlink-based approach that you suggested here, but I would vote -1 to include such hook into Symfony itself.

**Comment by ofbeaton** [comment]
Right, mixing the bins IS a nightmare. Previously if I wanted to run phpunit I would do `bin/phpunit` but you are saying that in 3.0 land you want us to run `vendor/bin/phpunit` for phpunit (and all the other phars) but `bin/console` for symfony?

I can see how you might want `symfony_requirements` before running composer. I'm going to move them back into `app/` for my purposes then.

I'll close this ticket since it looks like DONTFIX, but in my opinion your decision to promote going against the common convention of making `bin/` the composer bin (and one you promoted in previous versions, which we used to make all our build scripts and CIs) was perhaps not ideal.

Thank you for your consideration.

**Comment by stof** [comment]
> the common convention of making bin/ the composer bin

I would not call it *the* common convention, as ``vendor/bin`` is the default location when using composer. We actually decided to stop promoting a different convention than the one used by Composer.
