### ISSUE TITLE
Symfony 2.3 branch is *not* fully compatible with PHP 7.

### ISSUE THREAD

**Issue by kalzekdor** [symfony/symfony#18269]
There was a [blog post](http://symfony.com/blog/symfony-achieves-100-php7-compatibility) on August 11th claiming that all maintained Symfony branches were 100% compatible with PHP 7. At the time, (and as of right now), 2.3 is a maintained branch.

However, if you view the code under the [Debug](https://github.com/symfony/symfony/tree/2.3/src/Symfony/Component/Debug) section, you'll see that there is no support for the new Error type. Function typing should be using \Throwable, but instead are still using \Exception.

Which leads to errors like:

> Whoops, looks like something went wrong.
> 1/1FatalErrorException: Error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in ...\vendor\symfony\symfony\src\Symfony\Component\Debug\ExceptionHandler.php:67
> Stack trace:
> #0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error))
> #1 {main}
> thrown in ...\vendor\symfony\symfony\src\Symfony\Component\Debug\ExceptionHandler.php line 67
> in ...\vendor\symfony\symfony\src\Symfony\Component\Debug\ExceptionHandler.php line 67

So... is 2.3 fully compatible with PHP 7 or not?

**Comment by iltar** [comment]
http://php.net/manual/en/language.errors.php7.php

I think it's 100% compatible, it just shouldn't catch the Errors here and delegate them most likely. All cases will work until you trigger something that would be an Error (Throwable) in php 7 but not in 5.*

**Comment by kalzekdor** [comment]
See the stack dump I included. When an Error type is thrown,
ExceptionHandler is called and parameterized with the Error. This causes an
Exception to be thrown there, which completely obiliterates any contextual
information about the original Error (e.g., Stack Trace). Which makes any
Errors thrown in PHP 7 nearly impossible to debug.

Exception handling in 2.3 has no provisions for handling the new Error type
in PHP 7. Therefore, it would not be 100% compatible with PHP 7, as
features  are lost when switching to PHP 7.

The weird part is that, as far as I can tell, explicit handling for this
exact scenario was implemented in the 2.6 branch, but was never back-ported
to 2.3. But 2.3 is still in LTS, so the claim that all supported branches
are fully compatible is false. It looks like someone just overlooked
merging the changes into 2.3.

http://php.net/manual/en/language.errors.php7.php

I think it's 100% compatible, it just shouldn't catch the Errors here and
delegate them most likely. All cases will work until you trigger something
that would be an Error (Throwable) in php 7 but not in 5.*

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/symfony/symfony/issues/18269#issuecomment-200317252>

**Comment by nicolas-grekas** [comment]
@kalzekdor would you mind opening a PR against 2.3?

**Comment by kalzekdor** [comment]
@nicolas-grekas Sorry, I'm not too familiar with GitHub, so I'm not sure what you're asking for. 

[Here](https://github.com/symfony/symfony/commit/13c5d7cd0d92b29da6c92790c42c7ea493714d35) is a commit to the 2.6 branch that appears to address the issue, but as far as I can tell it was never applied to the 2.3 branch.

**Comment by Simperfit** [comment]
@kalzekdor @nicolas-grekas wanted to ask you if wou wanted to correct this issue by forking and working on that issue ;).

**Comment by nicolas-grekas** [comment]
Please check #18336

**Comment by kalzekdor** [comment]
Great! Thanks @nicolas-grekas for the quick turn-around.

**Comment by masterjus** [comment]
Hello. It still doesn't work if I register only ExceptionHandler. Like `ExceptionHandler::register();`

**Comment by stof** [comment]
@masterjus 2.3 is not maintained anymore though

**Comment by nicolas-grekas** [comment]
ExceptionHandler needs to be used in conjunction with ErrorHandler, you should not (and cannot on PHP7) use it standalone on PHP7.

**Comment by mlivan** [comment]
Symfony v2.4.10 also have problem with this bug.

**Comment by xabbuh** [comment]
Symfony 2.4 is not maintained anymore. You need to update to Symfony 2.7, 2.8, 3.2 or higher.

**Comment by mlivan** [comment]
Yes. Thank you.

**Comment by chalasr** [comment]
As of today 3.2 is not maintained anymore as well.

**Comment by sterichards** [comment]
I am having this issue on 2.7 using PHP 7.0.29 (cli)

**Comment by curry684** [comment]
You are aware 2.7 is going out of active support in 3 weeks? You should urgently upgrade to 2.8 and then 3.4.

https://symfony.com/roadmap?version=2.7#checker

**Comment by xabbuh** [comment]
In any case, comments on closed issues are likely to get lost. Please open a new one with some steps on how to reproduce it.
