### ISSUE TITLE
Component\Process\Process reads stream input only once on Process::start/run

### ISSUE THREAD

**Issue by akomm** [symfony/symfony#18262]
I want to implement a Command, which starts a child Process and interacts with it at certain points by writing into its STDIN. I did similar with proc_open a while ago and I know it is possible with the process API, which PHP provides, using the nonblocking option and pseudo terminal. The Process component provides an "async" API to run a process, but no means to write to the STDIN during the execution. Only once at start time. 

The entire testcase only checks the stream feature writing to the stream prior the execution:

https://github.com/romainneutron/symfony/blob/e19ce573bc26f64fec610181cd96425af54389fa/src/Symfony/Component/Process/Tests/AbstractProcessTest.php#L164-L181

Not during.

**Comment by nicolas-grekas** [comment]
This is not supported today but could be with #18262

**Comment by nicolas-grekas** [comment]
See also #18386
