### ISSUE TITLE
[Intl] Missing Country Codes

### ISSUE THREAD

**Issue by karvounis** [symfony/symfony#18263]
I am using the Country validator in my app in order to validate if the country code is a valid one. The problem is when validating two country codes: "BV" and "HM", which stand for "Bouvet Island" and "Heard Island and McDonald Islands" respectively. Official Symfony documentation states that a country code should be a valid ISO 3166-1 alpha-2 country code [wikipedia link](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes) but these two country codes are missing and regarded invalid.

**Comment by jakzal** [comment]
These countries [are excluded](https://github.com/symfony/symfony/blob/e06574110aa4d2e47a872983d646fd5776ac4869/src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php#L56-L59) from the list as they're apparently uninhabited.

**Comment by karvounis** [comment]
Dear @jakzal thank you for the update.
