### ISSUE TITLE
Removing the session from the container

### ISSUE THREAD

**Issue by AndrewCarterUK** [symfony/symfony#18273]
I have a project that allows applications to stay alive between HTTP requests using FastCGI. It provides a [Symfony bundle](http://github.com/PHPFastCGI/SpeedfonyBundle) for easy integration.

For the most part, the Symfony framework is very good at handling multiple request cycles - although some changes are required. That said, some of my users have a problem with Symfony session handling.

I'd like to ask if it's possible that improvements could be made to the way that the [listener in the framework bundle](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/EventListener/SessionListener.php) attaches the session to the request so that it could become compatible with handling multiple requests in a single application instance.

I remember that the request was once an entry in the container that was deprecated and removed in Symfony 3, is it possible to do something similar with the session entry for Symfony 4?

Many Thanks,

Andrew

(Edit) Also any tips on how to approach this in the meantime would be greatly appreciated.

**Comment by 1ed** [comment]
See https://github.com/symfony/symfony/issues/10557

**Comment by xabbuh** [comment]
closing in favour of #10557.
