### ISSUE TITLE
Automatically connect to MySQL master if slave not working

### ISSUE THREAD

**Issue by clytemnestra** [symfony/symfony#18288]
I've set up a master-slave connection that works just fine. It seems to read from the slave and write to the master. For the MySQL part I used [this guide][1]. Any modifications done to the master are immediately applied to the slave as well. Both databases use the 5.6 version.

    doctrine:
        dbal:
            default_connection:   default
            connections:
                default:
                    driver:   pdo_mysql
                    host:     "%database_host%"
                    port:     "%database_port%"
                    dbname:   "%database_name%"
                    user:     "%database_user%"
                    password: "%database_password%"
                    charset:  UTF8
    
                    slaves:
                        slave1:
                            host:     "%sdatabase_host%"
                            port:     "%sdatabase_port%"
                            dbname:   "%sdatabase_name%"
                            user:     "%sdatabase_user%"
                            password: "%sdatabase_password%"

However, if the slave's mysql server is down (or badly configured), wouldn't it make sense for the connection to be made to the master? In this case, the whole app crashes and I find that a bit annoying. Whenever the slave comes back up it will be updated from the master and it can be read from once again, but if it's not available in the meantime, the master can be used for reads just fine.

I'd like to know if there is a way to connect to the master if the slave is not working. Is there a configuration to be done? A class or service to overwrite? Or please tell me if it's a bad practice, maybe I am missing something.

I believe it has to do with [MasterSlaveConnection][2] since that one seems to be used when slaves are configured for a dbal connection, otherwise [Connection][3] is used.

  [1]: https://www.digitalocean.com/community/tutorials/how-to-set-up-master-slave-replication-in-mysql
  [2]: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  [3]: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php

**Comment by Tobion** [comment]
Doctrine configuration is part of the doctrine bundle. Please report it to https://github.com/doctrine/DoctrineBundle

**Comment by clytemnestra** [comment]
Done.

**Comment by alfredbez** [comment]
this issue in other repositories: doctrine/DoctrineBundle/issues/526 and doctrine/dbal/issues/2339

**Comment by wspot** [comment]
@clytemnestra hello , since we have the same problem i would like to ask you if your problem is solved and if so is the master and slave databases are synchronized after the configuration ?
