### ISSUE TITLE
Symfony\Component\Form\Extension\Core\Type\DateType and NumberType ignore empty_data: null

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#18285]
in my form builder I do:

    $builder
			->add('debugDate', DateType::class, array(
				'label' => 'label.debug_date',
				'widget' => 'single_text',
				'required' => false,
				'empty_data' => null,
				'attr' => array('data-datepicker'=>1),
			))
			->add('debugNumber', NumberType::class, array(
				'label'    => 'label.debug_number',
				'required' => false,
				'empty_data' => null,
				'scale' => 2));

Enttiy Code:
 
    /**
     * @var \DateTime
     * @ORM\Column(name="debug_date", type="datetime", nullable=true)
     */
    private $debugDate;
    /**
     * @var \DateTime
     * @ORM\Column(name="debug_number", type="datetime", nullable=true)
     */
    private $debugNumber;

Apparently `'empty_data' => null` does not work as expected, since vars.value outputs an empty strring. Why is that? 

Is there a wworkaround for this issue? My project deadline is in a couple of days:( 
I'm reporting this code in a simplified way, real fields are all in embedded forms, if that is of any matter.
Symfony version 3.0.3

![screenshot_1](https://cloud.githubusercontent.com/assets/1181094/14002350/bb666a40-f14b-11e5-8de8-563b29489259.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/1181094/14002351/bb6d19da-f14b-11e5-94e6-24c7109136c5.png)

**Comment by HeahDude** [comment]
Hi @Shoplifter, do you expect the pre set the template default value for the fields ?

In that case you should use `data` options instead which defines the default data for the field and must match the type provided by `data_class`.

`data_class` is null by default for `NumberType` so you can pass either a string or an integer (which will be casted to string like `null` is in your case) and `\DateTime` or string for `DateTimeType` depending on the type of the default data (set by `data` option or as argument in factory methods).

`empty_data` option is used as replacement when no data is submitted to the form (``null`` when field is missing or empty string) and should be a string for both since you use `widget` option as "single_text".

**Comment by Shoplifter** [comment]
no, I dont want to set default values. I'd like en empty date/number field to be valid, if the form is submitted. in database fields are of type datetime/date resp. int/float/decimal - all of them with `DEFAULT NULL`

**Comment by HeahDude** [comment]
So you don't have to do anything data is always null by default and hence the view value is always an empty string.

Am I missing something here ?

**Comment by Shoplifter** [comment]
Exactly. View data is an empty string, but when the value is validated, I would expect it to be null. It still appears to be an ampty string by then though.

**Comment by HeahDude** [comment]
Ok, sorry I got it now. You need a `DataTransformer` in that case, here's a workaround:
```php
$builder
        ->add('debugDate', DateType::class, array(
            'label' => 'label.debug_date',
            'widget' => 'single_text',
            'required' => false,
            'empty_data' => null,
            'attr' => array('data-datepicker'=>1),
        ))
        ->add('debugNumber', NumberType::class, array(
            'label'    => 'label.debug_number',
            'required' => false,
            'empty_data' => null,
            'scale' => 2));

$nullTransformer = new \Symfony\Component\Form\CallbackTransformer(
    function ($data) { return $data; }, // do nothing
    function ($data) { return '' === $data ? null : $data; }
);

$builder->get('debugDate')->addModelTransformer($nullTransformer);
$builder->get('debugNumber')->addModelTransformer($nullTransformer);
```

**Comment by backbone87** [comment]
Its a known behavior and actually working as intented. There are several tickets and discussions about how to provide solutions for this. The common workaround is the one presented by @HeahDude .

This issue should be closed.
Please use the search next time before you open an issue. Thank you.

**Comment by Shoplifter** [comment]
@HeahDude thank so much! That did the trick. Only ahd to remove `'empty_data' => null` for the transformer to be called. 
@backbone87 Actually I did earch. A lot. Maybe used the wrog terms. Sorry for duplicated issues. Closing this one.
