### ISSUE TITLE
Collection constraint not working when value is null

### ISSUE THREAD

**Issue by beni0888** [symfony/symfony#18281]
Hi everyone, 

I don't know whether this is a bug or a misunderstood from my part. The point is that I'm using the collection constraint to validate an array of key-value pairs. The problem is that when I pass a null value to the validator it doesn't return any violation, but in my opinion it should return a collection of violations, at least one per required value. 

My code is as follows:

```php
$constraints = new Assert\Collection(array(
            'fields' => array(
                'name' => new Assert\Required(array(
                    new Assert\Type(array('type' => 'string')),
                    new Assert\NotBlank(),
                    new Assert\Length(array('max' => self::NAME_MAX_LENGTH))
                )),
                'slug' => new Assert\Required(array(
                    new Assert\Type(array('type' => 'string')),
                    new Assert\NotBlank(),
                    new Assert\Length(array('max' => self::NAME_MAX_LENGTH))
                )),
            )
        ));

$violations = $this->validator->validateValue($data, $constraints);
// $violations->count() === 0 when $data is null
```

Is there something that I'm doing bad or something that I'm not doing?

Thanks beforehand

**Comment by inso** [comment]
https://github.com/symfony/symfony/issues/10221#issuecomment-34769066

**Comment by jakzal** [comment]
@inso this is not the case here, as in the example given by @beni0888 the NotBlank constraint is present.

@beni0888 what Symfony version do you use?

**Comment by inso** [comment]
@jakzal beni0888 is saying "when $data is null"

**Comment by dmaicher** [comment]
Indeed the `Collection` validator ignores `null` values like most other validators do:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/CollectionValidator.php#L33

So I guess you would need to add another constraint to make sure the value is an `array` or a `Collection`.

**Comment by jakzal** [comment]
@inso right, I missed this bit.

@dmaicher's right. Closing as there's no bug here.

**Comment by beni0888** [comment]
@jakzal I'm experiencing this problem in a Silex application, the versions I'm using are the following:
- silex/silex - v1.3.5
- symfony/validator - v2.8.3

**Comment by beni0888** [comment]
@webmozart Is there any way of telling the collection constraint not to ignore null values? I've read the conversation in #10221 and I see your point, but IMHO, for the collection constraint particular case is quite confusing to ignore null value for the collection itself, because you have an "allow_missing_fields" option which is false by default a makes you think that it should fail if those fields are not present.

**Comment by webmozart** [comment]
@beni0888 Accepting `null` in the Collection constraint but not in others seems inconsistent to me. Or is it something else you are suggesting?
