### ISSUE TITLE
[Issue] FatalErrorException in RoleHierarchy.php line 43:

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [symfony/symfony#18309]
I created table role and user_roles in my database and I insert for role table is (1, 'ROLE_USER'), (2,'ROLE_ADMIN') and insert for role_user with role_id and user_id.
I login with user has data in role_user , it has error

FatalErrorException in RoleHierarchy.php line 43:
Error: Call to a member function getRole() on a non-object
Pls help me

**Comment by xabbuh** [comment]
It looks like you do not pass `Role` objects to the `RoleHierarchy`. I doubt that this is an issue in Symfony itself, but comes from a misconfiguration of your application. Though feel free to fork the Symfony Standard Edition and make the minimum set of changes needed to reproduce your issue and we can take a look into it.

**Comment by nguyenphuocnhatthanh** [comment]
But when login with user hasn't data in table user_roles , it's not error.
Can you help me? @xabbuh

**Comment by stof** [comment]
Well, given that we don't have any info about what lives between your database and the call to RoleHierarchy (and there is a bunch of code there), we cannot help you here

**Comment by Shukuyen** [comment]
I get the same error when following the documentation here: http://symfony.com/doc/current/cookbook/security/entity_provider.html

My User entity is returning an array with one role string in the implementation of getRoles() from the UserInterface:
`return array('ROLE_USER');`

>     /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles();

**Comment by xabbuh** [comment]
@Shukuyen Can you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by jakzal** [comment]
@nguyenphuocnhatthanh @Shukuyen any news? We need to be able to reproduce your issue to fix it.

**Comment by javiereguiluz** [comment]
Sadly I must close this issue because of the lack of feedback. @nguyenphuocnhatthanh @Shukuyen if you have more information about this or can provide some code to reproduce the error, please reopen the issue. Thanks!
