### ISSUE TITLE
[Form] FormBuilder::add causes exception when given an object

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#18301]
I'm upgrading one of my bundles to the new version 3 standard and came across this bug.

Within my FormType, I add child types like so:

````php
$builder->add('type', new SelectType(), array(
    'choices' => array_combine($choices, static::$defaultChoices),
    'required' => true,
    'data' => self::INCLUSIVE,
    'options' => array(
        'width' => 'auto',
    ),
));
````

The documentation for `FormBuilder::add` states that the second parameter `$type` accepts `string|FormTypeInterface`. But, stepping through the code, I see the child is added to the `$unresolvedChildren` array. Later when `getForm` is called, each of these children are resolved by passing that type to `FormFactory::createNamedBuilder`, which expects a string.

I don't know if this is a documentation error or in fact a bug in the code. I would prefer to pass in an instance of the child type since I can construct it accordingly. Using strings and services would be a pain.

**Comment by HeahDude** [comment]
Hi @twifty, passing `FormTypeInterface` instance is deprecated in 2.8 and document in the corresponding [changelog](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form):
>Passing type instances to Form::add(), FormBuilder::add() and the FormFactory::create*() methods is deprecated and will not be supported anymore in Symfony 3.0. Pass the fully-qualified class name of the type instead.

**Comment by twifty** [comment]
Ahh, so the docblock hasn't been changed to reflect that?

**Comment by HeahDude** [comment]
Right, do you wan to send a PR ?

**Comment by twifty** [comment]
Wish I had time :/

**Comment by HeahDude** [comment]
Ok I'm on it ;)

**Comment by twifty** [comment]
Cheers :+1:

**Comment by HeahDude** [comment]
Done in #18302.
