### ISSUE TITLE
[Security][CSRF] Add Double Submit Cookies as CSRF prevention strategy

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#18313]
From the discussion in https://github.com/symfony/symfony/issues/18115 :
we should add the Double Submit Cookies CSRF prevention strategy as described by
https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet#Double_Submit_Cookies

If doable, this should be the default CSRF prevention strategy used in symfony SE

**Comment by backbone87** [comment]
here is a sample implementation for the `TokenStorageInterface`: https://gist.github.com/backbone87/a03b426797385a04666d

but this really needs #18115 resolved beforehand, else you would spam the client with cookies

**Comment by Koc** [comment]
duplicates #13464

**Comment by javiereguiluz** [comment]
Closing as a duplicate of #13464.
