### ISSUE TITLE
Have Symfony\Component\BrowserKit\Client create and accept a Crawler from another source

### ISSUE THREAD

**Issue by rudiedirkx** [symfony/symfony#18331]
(Original issue on https://github.com/minkphp/Mink/issues/700)

I'm testing forms and mails with Behat and Mink, and I want to read the e-mail in Behat and then use Behat's steps to assert it's correct. Mink only does HTTP requests, it doesn't read mail, so it can't perfom Behat document steps on the mail's DOM.

The fix is (technically) very easy: read the mail in my Behat Context, create a new `DomCrawler\Crawler` and assign it to the `BrowserKit\Client`. From there Behat will treat it like a webpage's HTML DOM.

That requires 2 things:

* An external to create a Crawler from content (like `protected function createCrawlerFromContent($uri, $content, $type)`)
* An external to inject that Crawler into the Client: a `setCrawler()` to match the `getCrawler()`

I don't know about Symfony's standards, so I've no idea if this would be acceptable. Apparently it doesn't belong in Mink, and I don't know how else to make this possible. And it should be possible, because it's so very useful.

**Comment by stof** [comment]
Well, I don't this this belongs to the BrowserKit component either. BrowserKit is about representing a browser (hence its name), and browsers don't let you put the HTML of a page manually. You have to open a page with them.
Allowing to inject the Crawler in the client means that the client would then be in an inconsistent state (as all other state of the Client would be related to a different page).

**Comment by rudiedirkx** [comment]
Hi Stof! Nice to see you here TOO =(

So where **does** it belong? I know it doesn't fit anywhere perfectly, but it does have to fit somewhere? I don't see any way to ADD this without hacking anything, so I can't do it without your help.

I'm not a big fan of "it shouldn't" and "it's not supposed to". It's very useful, and it's very possible, so I have to be able to make it.

If I can do it in a separate, custom package, I'm all for that. Point me in the right direction?

**Comment by stof** [comment]
@rudiedirkx as I said in the Mink PR, the proper solution would be for you to use the DomCrawler component yourselves for your email content, without trying to inject this crawler into a BrowserKit client (your email is HTML, but it is not a web page).
The broken thing is trying to make an email fit into a component meant to handle web pages.

**Comment by rudiedirkx** [comment]
If I use the DomDrawler separately, I can't use Mink's Behat steps, like "follow X" and "see X". That makes it useless. Do you know a way I can make that happen without hacking anything? Would I have to extend every class from `FeatureContext` to (browserkit) `Client` ? If that's an option, if it's built like that, I'll take it.

**Comment by jakzal** [comment]
Closing for reason's given by stof. I also don't think we should support this hack. Implementing custom behat context steps is the way to go.
