### ISSUE TITLE
[2.8.4] It looks like `Kernel::VERSION` wasn't updated before tagging release

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony#18339]
After upgrading Symfony to version 2.8.4 I see "2.8.4-DEV" instead of "2.8.4" as version in console and debug toolbar. Would you be so kind to fix this issue?

Thank you.

**Comment by fabpot** [comment]
Sorry about that but  nothing I can "fix" as a tag cannot be changed.

**Comment by vkhramtsov** [comment]
Why not just tag new release with this fix? For example 2.8.5 ?

**Comment by fabpot** [comment]
Sure, that's what we will do in about a month. In the meantime, having an extra `dev` in the version does not hurt.
