### ISSUE TITLE
Start A Background Process By HTTP Request From Browser

### ISSUE THREAD

**Issue by subins2000** [symfony/symfony#18338]
I need to execute a PHP file in background to download a file. For that, I do this in `init.php` : 
```php
$builder = new ProcessBuilder();
$builder->setPrefix(getPHPExecutable()); // /usr/bin/php
$command = $builder->setArguments(array(__DIR__ .'/background-download.php', 'http://localhost/receive-status', $extraData))
      ->getProcess()
      ->getCommandLine();
      
$process = new Process($command);
$process->start();
```
What the background script does is, download a file and push the download status to localhost server.

## Problem
I initiate the script by sending a HTTP request to the above mentioned file (`init.php`) from the browser. But when I call `start()`, the command is not executed and the request to `init.php` is completed.

If I use `run()` instead, the process runs, but `init.php` request is not completed until the process finishes.

What I require is, run the process in background without server waiting for the `init.php` file to finish sending the response.

Can the Process component do it ?

**Comment by alexislefebvre** [comment]
Please see [this comment from javiereguiluz](https://github.com/symfony/symfony/issues/16484#issuecomment-154381799):

> for user-support questions it's better to use any of the alternatives offered at http://symfony.com/support Thanks!

**Comment by javiereguiluz** [comment]
@subins2000 as you said, you want *"to run a process without the server having to wait to finish it before sending the response back to the user"*. That's exactly why we introduced the `kernel.terminate` event. You can read more about this [here](http://symfony.com/doc/current/components/http_kernel/introduction.html#component-http-kernel-kernel-terminate) and [here](http://symfony.com/doc/current/reference/events.html#kernel-terminate).

I'm closing this issue because it looks like the feature request is already implemented by Symfony. If you have any other question about how to use this feature, please use these support channels: http://symfony.com/support  Thanks!

**Comment by subins2000** [comment]
@javiereguiluz I'm talking about the [Process component](https://github.com/symfony/process). I only want to use the Process component and not HTTP Kernel.

I wish to know whether I could initiate a background process using Symfony Process without having a script to wait for the process to finish.

**Comment by zemd** [comment]
@subins2000 probably you need to use fastcgi function as described in symfony doc

> Internally, the HttpKernel makes use of the fastcgi_finish_request PHP function. This means that at the moment, only the PHP FPM server API is able to send a response to the client while the server's PHP process still performs some tasks. With all other server APIs, listeners to kernel.terminate are still executed, but the response is not sent to the client until they are all completed.

**Comment by ddegasperi** [comment]
@subins2000 I've solved the problem by adding a final '&' to the cmd and disabling the output of STDOUT and STDERR. In your case the following piece of code should work:

```php
$builder = new ProcessBuilder();
$builder->setPrefix(getPHPExecutable()); // /usr/bin/php
$command = $builder->setArguments(array(__DIR__ .'/background-download.php', 'http://localhost/receive-status', $extraData))
      ->getProcess()
      ->getCommandLine();

// solution 1
$process = new Process($command . ' &');
$process->disableOutput();
$process->run();

// solution 2
$process = new Process($command . '  > /dev/null 2>&1 &');
$process->run();
```

**Comment by antoine-nedelec** [comment]
Hi, the ProcessBuilder isn't here anymore in Symfony4, and I can't figure out a way to achieve what you did. Is there any way to do it with latest Symfony ?

**Comment by alexandru-burca** [comment]
> Hi, the ProcessBuilder isn't here anymore in Symfony4, and I can't figure out a way to achieve what you did. Is there any way to do it with latest Symfony ?

I was able to accomplish this with "**exec**". But I am also interested into a solution using ProcessBuilder in symfony 5.

`exec('php '.$this->getParameter('kernel.project_dir').'/bin/console app:command > /dev/null 2>&1 &')`
