### ISSUE TITLE
[Backward Compatibility][Break] NumberToLocalizedStringTransformer

### ISSUE THREAD

**Issue by BorisMorel** [symfony/symfony#18346]
Hello,

With the new version of symfony 2.7.11, i have a break with the form number transformer.
If i set my validator to `@Assert\Type("float")` and that my submitted value doesn't contain a decimal separator, the transformer use `\NumberFormatter::TYPE_INT64` instead of `\NumberFormatter::TYPE_DOUBLE`.

Any reason to change this feature ?

Bug introduced in this commit:
https://github.com/symfony/symfony/commit/03c008cdbfa7c978fe76fc04b3077f1315b378d4

Regards,
Boris.

**Comment by nicolas-grekas** [comment]
The reason for the linked commit is #18067, fixed in PR #18179.
Basically, big integers (roughly between 2^53 and 2^64) can not be represented as floats since floats have not enough precision for storing them.
We could fix this bc-break using floats for numbers < 2^53.

**Comment by BorisMorel** [comment]
Currently this bug appear with latitude and longitude. So I'am really far as the big integer.

**Comment by nicolas-grekas** [comment]
Please check #18358
