### ISSUE TITLE
[PHP 7] Return type declaration in service container

### ISSUE THREAD

**Issue by tobske** [symfony/symfony#18367]
The service container doesn't consider return type declaration which is possible since PHP 7.
If you have something like the following:
```PHP
class A {
    function B() : C {
        return new C();
    }
}
```
the service container doesn't consider the return type declaration ` : C` and then PHP throws a fatal error like
```PHP
 PHP Fatal error: Declaration of BundleFolderA_0123ABC::B must be compatible with Bundler\Folder\A::B(): C
```

**Comment by stof** [comment]
Is it for proxies generated for lazy services ?

You have to use ProxyManager 2 to support PHP 7 features during proxy generation. support for ProxyManager 2 is part of Symfony 2.3.38, 2.7.10, 2.8.3 and 3.0.3. so if you use at least one of these versions, you can update your composer.json to use the 2.x version of ProxyManager

**Comment by tobske** [comment]
Thanks for you quick response.
I actually had a explicit ">1.0" for ProxyManager in my project's composer.json. 
After updating on version 2.x everything works fine.
Sorry for the work.
