### ISSUE TITLE
Symfony 2.8 book example bug missing "<?php" keyword?

### ISSUE THREAD

**Issue by kingjuliyen** [symfony/symfony#18369]
Found a issue with documentation at http://symfony.com/doc/2.8/book/page_creation.html

lucky/number example has code as follows

// src/AppBundle/Controller/LuckyController.php
namespace AppBundle\Controller;

this should be as follows and works fine. <?php seems to be missing in the example

**<?php**
// src/AppBundle/Controller/LuckyController.php
namespace AppBundle\Controller;

I also referred to the auto generated code for DefaultController.php in the same dir it looks as follows, note in <?php is present in this

<?php

namespace AppBundle\Controller;

**Comment by iltar** [comment]
@kingjuliyen non of the examples have the php open tag. If you think they should be there, you'd do best and open the issue on the docs repo to bring it up: https://github.com/symfony/symfony-docs/

**Comment by xabbuh** [comment]
@iltar is right. This should be discussed in the docs repository (see symfony/symfony-docs#6389). However, we discussed this in the past and rejected to do such changes several times (see, for example, symfony/symfony-docs#5741).
