### ISSUE TITLE
[3.0.4] It looks like `Kernel::VERSION` wasn't updated before tagging release 

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony#18365]
After upgrading Symfony to version 3.0.4 I see "3.0.4-DEV" instead of "3.0.4" as version in console and debug toolbar. Would you be so kind to fix this issue?

Thank you.

**Comment by stof** [comment]
@vkhramtsov a tag cannot be altered (git makes it very painful for any people cloning the repo when mutating a tag). So we cannot fix it for the 3.0.4 release.

@fabpot is there a way to improve the release process to add a safeguard preventing such mistake in the future ?

**Comment by fabpot** [comment]
It was a bug I've introduced for 2 versions. Fixed now, won't happen anymore.

**Comment by stof** [comment]
yeah, I saw that the tag was created for the commit before the merge of the release changes...

**Comment by vkhramtsov** [comment]
Thank you. As option, you can create new versions like 2.8.4.1 and 3.0.4.1.
Waiting for new version to verify fix.

**Comment by stof** [comment]
@vkhramtov I don't think this justifies a new release.

**Comment by gabel** [comment]
Is it still present?

**Comment by xabbuh** [comment]
@gabel Yes, the version will match the actual release number again with the release of Symfony 3.0.5 in about a month.

**Comment by gabel** [comment]
@xabbuh thanks... we'll skip this one and all is fine.

**Comment by Miliooo** [comment]
@stof does the fact that the route profiler component is  broken in 2.8.4 (missing use request class) justifies a new release? Granted I don't use it that much, but I'm stuck with a broken profiler now.
