### ISSUE TITLE
Symfony & Docker

### ISSUE THREAD

**Issue by slashsBin** [symfony/symfony#18377]
Does Symfony Team plan on Officially Supporting Docker via Implementing Container Configurations?
Maybe Templates or Officially Releasing them on Docker Hub?

**Comment by jorge07** [comment]
Each one can create his own environment with docker, I don't this is something necessary.

**Comment by fabpot** [comment]
I don't see how that would work. The goal of Symfony is to provide a framework and all the flexibility to make your own choices. We had the same discussion in the past for Vagrant and came to the conclusion that it cannot and shouldn't be part of Symfony itself.

**Comment by kachkaev** [comment]
@fabpot in my view Docker these days stays not further from the core of Symfony than, let's say, css minification. It is almost as common as that.

I started looking into ways of dockerising my Symfony projects recently and naturally went to a cookbook being almost certain that there will be something on Docker in the middle of 2016. There is a section called [Workflow](https://symfony.com/doc/current/cookbook/workflow/index.html) which contains articles on a few environments, but there is simply no single mentioning of `Docker` on the whole website.

That omission is probably something worth fixing in the near future – it would be really good if  Symfony experts like you could give advice on how best to run an app using Docker both during dev and in production. This won't make Docker a part of the framework, but will definitely improve the experience for may people from the community.

And speaking of the boundaries of the framework... I remember days when composer was not a part of Symfony and we used to pull git sub-modules to manage vendors. Software development ecosystem changes quite fast and some trends are worth picking.
