### ISSUE TITLE
New Symfony v3.0.4 tag points to a bad commit

### ISSUE THREAD

**Issue by tifabien** [symfony/symfony#18380]
I just updated my composer deps regarding the fresh new Symfony 3.0.4. 

I was surprised to see when I loaded my application in the Web debug bar the symfony version to 3.0.4-dev.

I looked at [v3.0.4 tag](https://github.com/symfony/symfony/tree/v3.0.4) and seems that it's not pointing to the good commit.

What happened?

**Comment by jvasseur** [comment]
Duplicate of #18365

**Comment by fabpot** [comment]
Only the version is wrong, everything else is fine.

**Comment by tifabien** [comment]
Sorry for the duplicate created and thanks for your quick answers !
