### ISSUE TITLE
RFC process?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#18383]
Are there any insights on Symfony's RFC process? I guess the RFC issue list (https://github.com/symfony/symfony/issues?q=is%3Aissue+is%3Aopen+label%3ARFC) is a good UI for gathering, commenting/discussing and voting on RFC's.

However from there on it seems to be a vague process to me...
- Who decides if it's a legit RFC yes or no?
- How many votes are needed?
- How do we (officially) vote? Reply with :+1: on the RFC issue?
- Who is allowed to vote (officially)?
- How/when do we transist from various states?
 - I.e. Voting phase, Under discussion, In Draft, Accepted
- How do we express its state in the UI?
 - Perhaps some different labels like `RFC-accepted`, `RFC-draft`, etc.
- ... anything else?

Basicly something like PHP is doing (nicely imho); https://wiki.php.net/rfc

**Comment by javiereguiluz** [comment]
@ro0NL the RFC are ruled by the same principles of the rest of issues. The whole process is explained here: http://symfony.com/doc/current/contributing/code/core_team.html

**Comment by ro0NL** [comment]
OK.. haven't read that one in depth, my bad :)

So basicly we _SHOULD_ go from RFC to PR if:

> At least the component's Merger or two other Core members voted +1 and no Core member voted -1. (Voted for the RFC issue that is)

PR is done by whoever is in the mood...

My point is that http://symfony.com/doc/current/contributing/code/core_team.html describes the process of an existing PR, and *not* necessarily the process from an existing RFC to a new PR.

**Comment by javiereguiluz** [comment]
Yes, maybe we should update the text to clarify some things. But you can assume that PR == issue == RFC.

**Comment by ro0NL** [comment]
I see :)

To describe it a bit more clearly.. I'm really interested in stuff like #6406 and #12325

But currently it's hard to determine if these are/will be accepted at all... i.e. can someone go with a PR for the session stuff (#12325)? or should one count the votes first and check if complies with the rule;

> At least the component's Merger or two other Core members voted +1 and no Core member voted -1. 

Everybody seems to thinks it's a good idea however last activity for #12325 is from December 2014. Will this eventually be done by the core team, not done at all, or are we all waiting for someone to create a PR. Perhaps expressing that an RFC is `accepted` would trigger more activity on creating PR's?

**Comment by ro0NL** [comment]
@fabpot perhaps something to think about.. or at least some explicit documentation on RFC's.

**Comment by Tobion** [comment]
Changing the request class as in #6406 will probably not be worth and introduce bc breaks there. So as said there, symfony will probably adapt PSR-7 in the future (hopefully Symfony 4).

#12325 is basically about writing a new Session component (which will replace HttpFoundation/Session). I think everybody agrees, it's just a matter of doing it and making an architecture plan for it. If you feel like taking the lead there, feel free to start with it.

Closing this issue. If there is still something unclear about the RFC, it's an issue for symfony-docs.
