### ISSUE TITLE
[AppVeyor] ProcessTest fails, timeout on stream_copy_to_stream

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#18409]
ping @nicolas-grekas -our CI hero!- this test keeps failing and only in AppVeyor 

https://ci.appveyor.com/project/fabpot/symfony/build/1.0.7827#L997

```
Symfony\Component\Process\Tests\ProcessTest::testIteratorInput
Symfony\Component\Process\Exception\ProcessTimedOutException: The process 
"c:\php\php.exe -r "stream_copy_to_stream(STDIN, STDOUT);"" exceeded the 
timeout of 60 seconds.
```

**Comment by nicolas-grekas** [comment]
Please vote for https://github.com/symfony/symfony/pull/18386 and you'll
get a fix for free ;)

**Comment by Simperfit** [comment]
#18386 has been merged @iltar  :)

**Comment by iltar** [comment]
@nicolas-grekas confirmed, it's succeeding again, thanks! https://ci.appveyor.com/project/fabpot/symfony/build/1.0.7883
