### ISSUE TITLE
[RFC] [Tests] use assertions anywhere in the code and profile them

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony#18411]
What about collecting assertions in controllers, services, entities ... ?

We can already `dump()` objects but I think this could be useful to have results of assertions directly shown in the profiler and the web debug toolbar.

It could be based on `webmozart/assert` (ping @webmozart :)

We could use an `assert` service:
```php
class SomeRequestService
{
    private $assert;
    private $request;

    public function __construct(Request $request, AssertInterface $assert)
    {
        $this->request = $request;
        $this->assert = $assert;
    }

    public function someMethod()
    {
        $session = $this->request;

        $this->assert->true($session->has('some_attribute'), 'The session should have a "some_attribute"', $session());
        $this->assert->same('test', $session->get('some_attribute'), 'The session attribute "some_attribute" should be "test" but got %s', $this->request);
        // or
        $this->assert->regex('/^test/', $session->get('some_attribute'), 'The session attribute "some_attribute" should start with "test" but got %s', $this->request);
        // or even better
        $this->assert->uuid($session->get('some_uuid'), 'The session attribute "some_uuid" is invalid" got %s', $this->request);
```

A controller could get it by `$this->container->get('assert')` and use a trait to hold it as protected parameter and be able to do `$this->assert->*`.

`$assert->*`would be a wrapper for `\Webmozart\Assert::` taking  the "dumped" context as extra last argument, using `dump` function of the VarDumper component to handsome display in the profiler.

It would be nice if the `assert` service wrapper get passed the Stopwatch to check time performances:
```php
// from anywhere using SomeService instance
$assert->stopwatch('some_service_event', '<', 1000, $someService);
```

The `assert` service could handle different channels like `Logger`, to sort them in the profiler.

What do you think ?

**Comment by HeahDude** [comment]
It would be good is the `AssertDataCollector` get passed the StopWatch to check time performances.

**Comment by HeahDude** [comment]
FYI, I'm working on a micro bundle already. If it does not have its place in core, it may help in community projects willing to make functional tests.

**Comment by Simperfit** [comment]
Thanks @HeahDude  !

**Comment by HeahDude** [comment]
Working on an implementation and the dependencies always makes things clear, I will update the API proposed in the op shortly :)

**Comment by HeahDude** [comment]
I was adding a `strategy` field to my factory with constants:
```php
interface Closer
{
    const LOG_ASSERTION = 0;
    const DUMP_ASSERTION = 1;
    const THROW_ASSERTION = 2;

   // ...
}
```

But thanks to @nicolas-grekas and #18414 I guess I can add:
```
const STREAM_ASSERTION;
```

Beautiful functional assertions from the console :)

**Comment by stof** [comment]
I don't this needs to be in core.

**Comment by HeahDude** [comment]
I agree its not needed as part of the core but that would be cool to bring `webmozart/assert` in a bundle that uses most basic symfony features. what about `FOSAssert` ?

**Comment by javiereguiluz** [comment]
I'm not strongly against this ... but I agree with @stof reasons. So this would be a 👎 for me.
