### ISSUE TITLE
console translator:debug

### ISSUE THREAD

**Issue by RafalEsp** [symfony/symfony#18417]
I have created form class, which uses twig template and translator. 

```
class PostForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('publication_date', DateTimeType::class, ['label' => 'post.publication_date'])
            ->add('title', TextType::class, ['label' => 'post.title'])
            ->add('content', TextareaType::class, ['label' => 'post.content'])
            ->add('save', SubmitType::class, ['label' => 'post.save']);
    }
}
```

My translation file is in other domain (admin) than default (messages).
# admin.en.yml

```
post:
  publication_date: Publication date
  title: Post title
  content: Post Content
  save: Save for publication
```

Translation domain is set while calling form factory

```
$form = $this->formFactory
            ->create(PostForm::class, $post, ['translation_domain' => 'admin'])
            ->handleRequest($this->requestStack->getCurrentRequest());
```

Template is really basic for now:

```
{% extends 'AdminBundle:Default:index.html.twig' %}

{% block main_content %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}
```

Everything works fine. I can see translated messages, but when I call

```
bin/console debug:translation en BlogBundle
```

Messages from form are shown as unused, which is not true:

```
---------- -------- ----------------------- ----------------------
  State      Domain   Id                      Message Preview (en)
 ---------- -------- ----------------------- ----------------------
             menu     blog                    Blog module
             menu     post.new                Write new post
             menu     post.dashboard          Blog dashboard
             menu     post.list               Posts list
   unused    admin    post.publication_date   Publication date
   unused    admin    post.title              Post title
   unused    admin    post.content            Post Content
   unused    admin    post.save               Save for publication
 ---------- -------- ----------------------- ----------------------
```

**Comment by HeahDude** [comment]
Hi @RafalEsp! Why does the domain show "menu", do you have another domain that you don't use or is this part of the bug ?

**Comment by RafalEsp** [comment]
Hi,

Yes I am using menu domain in other part of bundle.
All translations are working fine, only debugger shows that messages from admin domain are not used.
You can take a look on source here:
https://github.com/kiss-plus/blog/tree/master/src/KissPlus/BlogBundle
This is only beginning of the project so it is easy to trace, but when it will grow, it can be problem and misleading information

**Comment by HeahDude** [comment]
Ok, I've misread, I don't know if this is a bug, but I can confirm it, because it seems that only translation keys hard printed in the templates are collected.

Since the keys are used as options in a form type, the debug tool does not know about them, there are passed through functions to be printed.

I would say this is expected, but could be e feature, even if I don't see for now how this could be implemented.

**Comment by HeahDude** [comment]
Could you try:
```twig
{% block main_content %}
    {{ form_start(form) }}
    {{ form_widget(form.title, {'label': 'post.title'}) }}
    {{ form_end(form) }}
{% endblock %}
```

to see if it's caught that way ?

**Comment by RafalEsp** [comment]
nope, result is the same.

I've tried setting default domain in template, but in this case translation didn't work at all.
Actually the way in which it is done now, is the only way, that I was able to make form template form with different domain than default 'messages'

**Comment by HeahDude** [comment]
What about:
```twig
{% block main_content %}
    {{ form_start(form) }}
    {{ form_widget(form.title, {'label': 'post.title'|trans({}, 'admin')}) }}
    {{ form_end(form) }}
{% endblock %}
```
?

**Comment by HeahDude** [comment]
Sorry I've updated my first example too, for the label to be printed you need to use `form_row`...

**Comment by HeahDude** [comment]
Also refresh your cache and open the page in your browser so the template files are generated, that might help.

**Comment by RafalEsp** [comment]
In this second example title translation is marked as used.
I guess it works only when translator's trans method is invoked.

**Comment by HeahDude** [comment]
Yes form type options uses translation domain and keys dynamically.

But I think that once they are used once when generating the templates they are called with `trans` too so they should be in the fallbacks catalogue.

It may depend whether your cached translations are generated.

**Comment by RafalEsp** [comment]
I'll try to investigate this issue little bit more while changing this form and creating new ones.

The initial problem for me was to set translation domain for this form, and the way in which I did, was the only one, when translator has 'catched' this domain.

If I will find something I will create pull request ;)

**Comment by HeahDude** [comment]
You can also define the option in the form type directly and override it when needed:
```php
class PostForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('publication_date', DateTimeType::class, ['label' => 'post.publication_date'])
            ->add('title', TextType::class, ['label' => 'post.title'])
            ->add('content', TextareaType::class, ['label' => 'post.content'])
            ->add('save', SubmitType::class, [
                'label' => 'post.save',
                'translation_domain' => 'form', // will override only this field
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('translation_domain', 'admin');
    }
}
```
Then:
```php
$form = $this->formFactory
            ->create(PostForm::class, $post, ['translation_domain' => 'user'])
            ->handleRequest($this->requestStack->getCurrentRequest());
```
would override it in all the fields.

**Comment by RafalEsp** [comment]
This works nice as well, thanks. But unfortunately, problem with unrecognized translations usage remains

**Comment by HeahDude** [comment]
Even when the catalogue is built after opening it in the browser ?

**Comment by RafalEsp** [comment]
yes, exactly. In browser everything is fine.

I was cleaning cache with console, manually for dev env and after refreshing page in browser, result is the same - in browser everything is OK, in debugger it looks like unused.

**Comment by HeahDude** [comment]
Bug or feature ? I don't know :)

**Comment by RafalEsp** [comment]
Cool, don't worry :)

**Comment by HeahDude** [comment]
We need a translation expert! ping @aitboudad :)

**Comment by HeahDude** [comment]
ping @aitboudad any thought on this?

**Comment by xabbuh** [comment]
THat's expected behaviour (a known limitation). The Translation component provides an [`ExtractorInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/Extractor/ExtractorInterface.php) for which we have implementations to extract used translation keys from [Twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Translation/TwigExtractor.php) and [PHP templates](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php). However, there is no extractor to find out which translation keys are used with forms.
