### ISSUE TITLE
How to Create a Custom Form Password Authenticator

### ISSUE THREAD

**Issue by nkl90** [symfony/symfony#18418]
Hello, i create my custom Authenticator from this sample: http://symfony.com/doc/current/cookbook/security/custom_password_authenticator.html
When my form submit request on login_chek, I see the following order of code execution:
`KernelBundle\Security\TimeAuthenticator::__construct`
`KernelBundle\Security\TimeAuthenticator::authenticateToken`
`KernelBundle\Security\AuthFailureHandler::onAuthenticationFailure`
WHY??? WHY dont called createToken() from my TimeAuthenticator??? In authenticateToken() method comes $token. Where did he come from? In my form 2 login fields phone or email. Phone feild filled by mask "+7 (777) 777 77 77" and in that a request comes in. And stored in the database in such a way username column 77777777777. Naturally the user with a phone "+7 (777) 777 77 77" does not exist. How can i modyfi requested data???

**Comment by nkl90** [comment]
I also created a TokenAuthenticator from this example http://symfony.com/doc/current/cookbook/security/guard-authentication.html. Security authorizes my user as this:

>  Logged in as 77017197535
Authenticated Yes
Token class PostAuthenticationGuardToken
Actions Logout

But, after login, the system again passes the authorization process. What am I doing wrong?

**Comment by javiereguiluz** [comment]
@nkl90 in the GitHub repository we only discuss about Symfony bugs and new features. Your issue looks like you are having some troubles using Symfony. For this kind of questions, please use any of the support alternatives shown in http://symfony.com/support Thanks!

If this is ultimately confirmed as a Symfony bug, we'll reopen your issue. Thanks!
