### ISSUE TITLE
[Form] Raise error when not registering translation messages

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18423]
While using the Form component with the Validator as standalone, I noticed that I did not get any error message when my form was invalid. After a bit of debugging, it was simply because the translation files were not registered to the validator. Is is the intended behaviour? I would have expected at least a warning somewhere to tell my *why* I didn't get any message error.

/cc @webmozart

**Comment by jakzal** [comment]
@theofidry can you provide a simple code snippet that would reproduce this behaviour please?

**Comment by theofidry** [comment]
will try in the week...

**Comment by HeahDude** [comment]
ping @theofidry :)

**Comment by theofidry** [comment]
I'm afraid I really don't have the time and energy to re-check that. To be honest I feel like there's a lot lacking in the documentation regarding the Form component for being used as a standalone (and that may explain the low usage of this component outside of the Symfony framework). But I think it's a work that requires a dedicated time to review things properly step by step. As I'm lacking time and I'm not currently using the Form component outside of Symfony, I can't really commit myself to do it.

If someone is ready to take up this work that would be great, meanwhile let's close this issue and not pollute the list of issues with this :)

NB: keep up the good work @HeahDude!
