### ISSUE TITLE
[Console] formatTime helper returns incorrect time

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#18420]
I've noticed, while using the `ProgressBar` class, the elapsed time correctly counting seconds, switching to "1 min" then a second later jumping up to "2 mins". I've narrowed the problem down to the `Helper::formatTime` method:

````php
return ceil($secs / $format[2]).' '.$format[1];
````

shouldn't it be using `floor`?

On a second thought, no it shouldn't. using `floor` will result in strings like "1 mins".

**Comment by xabbuh** [comment]
Not sure if I understand what you mean. Can you give a more detailed explanation or show some screenshot or something like that demonstrating what you experienced?

**Comment by twifty** [comment]
@xabbuh Run the method in a loop:

```php
for ($i=55; $i<65; ++$i)
{
    echo Helper::formatTime($i) . "\n";
} 
````
You will see the output
````
59 secs
1 min
2 mins
````
`ceil(61/60)` will produce 2. The method should be using `floor` but doing so is still incorrect since the loop iteration has already passed the singular form.

**Comment by camporter** [comment]
I submitted a PR for this that will correctly wait on 1 min for all seconds between 60-119 instead of jumping to 2 min prematurely.
