### ISSUE TITLE
[TwigBridge] FormExtension triggers deprecation warning with Twig 2

### ISSUE THREAD

**Issue by sarcher** [symfony/symfony#18427]
Using Symfony 3.x and the current dev-master of Twig 2, the following is triggered:

`The Symfony\Bridge\Twig\Extension\FormExtension class implements Twig_Extension_InitRuntimeInterface that is deprecated to be removed in 3.0`

Fully realize that Twig 2 is still a work in progress, but didn't see this noted elsewhere here and figure it would be good to address at some point.

**Comment by ShinDarth** [comment]
I also get ```The Symfony\Bridge\Twig\Extension\FormExtension class implements Twig_Extension_InitRuntimeInterface that is deprecated to be removed in 3.0 ```

**Comment by xabbuh** [comment]
This looks weird. The `Twig_Extension_InitRuntimeInterface` is not deprecated. Can you show a full stack trace for this?

**Comment by stof** [comment]
@xabbuh it is deprecated in Twig 2 (as ``initRuntime`` will not be supported at all in Twig 3.0). Good news is that Symfony implements this method only for its own BC layer. So Symfony 4.0 will not need this method anymore

**Comment by fabpot** [comment]
What about removing the deprecation notice in Twig 2.0 and add it back for Twig 2.1 (like what we do in Symfony)?

**Comment by xabbuh** [comment]
@fabpot This sounds like a good idea. Not being able to have forward compatible code that does not trigger a deprecation after upgrading seems weird.

**Comment by ShinDarth** [comment]
My stack trace:

```
DebugClassLoader::loadClass()
spl_autoload_call() (called from appDevDebugProjectContainer.php at line 3342)
appDevDebugProjectContainer::getTwigService() (called from Container.php at line 274)
Container::get() (called from appDevDebugProjectContainer.php at line 2833)
appDevDebugProjectContainer::getTemplatingService() (called from Container.php at line 274)
Container::get() (called from Controller.php at line 212)
Controller::render() (called from DefaultController.php at line 15)
DefaultController::indexAction()
call_user_func_array() (called from HttpKernel.php at line 153)
HttpKernel::handleRaw() (called from HttpKernel.php at line 68)
HttpKernel::handle() (called from Kernel.php at line 169)
Kernel::handle() (called from app_dev.php at line 18)
```

**Comment by xabbuh** [comment]
see twigphp/Twig#2179
