### ISSUE TITLE
[PropertyAccess] setValue (again) replace array when not needed

### ISSUE THREAD

**Issue by MisatoTremor** [symfony/symfony#18437]
This behavior has been mentioned in #13731 by @Tobion and fixed in #13835 by @bananer but was reintroduced later (my guess would be #18224 as it introduced the [code that replaces the array](https://github.com/symfony/symfony/pull/18224/files#diff-3e45cf556c0330623c0167841d303dffR152)).

In the following test case the second assertion fails because after the ``setValue`` call the ``publicAccessor`` property of object has the value ``array('value2' => 'baz')`` instead of ``array('value1' => 'foo', 'value2' => 'baz')``.

```php
    public function testArrayNotBeeingOverwritten()
    {
        $value = array('value1' => 'foo', 'value2' => 'bar');
        $object = new TestClass($value);

        $this->propertyAccessor->setValue($object, 'publicAccessor[value2]', 'baz');
        $this->assertSame('baz', $this->propertyAccessor->getValue($object, 'publicAccessor[value2]'));
        $this->assertSame(array('value1' => 'foo', 'value2' => 'baz'), $object->getPublicAccessor());
    }
```

**Comment by nicolas-grekas** [comment]
That's really likely! The fix should go on 2.3. Anyone willing to work on it?

**Comment by MisatoTremor** [comment]
Update: Fixed the test case.

**Comment by MisatoTremor** [comment]
@nicolas-grekas 
Assigning ``$zval[self::REF]`` with the current value after src/Symfony/Component/PropertyAccess/PropertyAccessor.php, Line 153 like below fixes this, but seems a bit brute for the intention of your PR.
Could you please check if this negatively affects your benchmark results?

Before:
```php
$ref = &$zval[self::REF];
```
After:
```php
$ref = &$zval[self::REF];
$zval[self::REF] = $zval[self::VALUE];
```
