### ISSUE TITLE
 Symfony Profiler - Routing

### ISSUE THREAD

**Issue by Jujuwar** [symfony/symfony#18433]
I get an error when I try to view routing in Symfony Profiler:

`[1] Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Request" from namespace "Symfony\Bundle\WebProfilerBundle\Controller".
Did you forget a "use" statement for e.g. "Symfony\Component\BrowserKit\Request" or "Symfony\Component\HttpFoundation\Request"?
    at n/a
        in /Users/Julien/Sites/tfe/vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php line 86`

Using Symfony 2.8.4

**Comment by javiereguiluz** [comment]
@Jujuwar thanks for reporting this error. Sadly this is something I introduced by mistake when fixing other things. The good news is that it's already fixed as of #18340 and it will be available in the next version. Therefore, I'm closing this issue as "fixed". Thanks!
