### ISSUE TITLE
Problem router panel in LTS version

### ISSUE THREAD

**Issue by Preovaleo** [symfony/symfony#18446]
Hi,

LTS = 2.8.*

there is a problem in the LTS install in the router panel of the profiler:
Attempted to load class "Request" from namespace "Symfony\Bundle\WebProfilerBundle\Controller".
Did you forget a "use" statement for e.g. "Symfony\Component\HttpFoundation\Request" or "Symfony\Component\BrowserKit\Request"? 

# How to :
1. install a new lts version of symfony
`php symfony new hello_world lts`
2. start the server
`php app/console server:start`
3. get "/"
4. go to the Routing panel in the profiler

# resolve :
add
`use Symfony\Component\HttpFoundation\Request;`
in 
`src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php`

regards,

**Comment by Preovaleo** [comment]
Allready solved by 9e14f9f but need to bump to 2.8.5

**Comment by xabbuh** [comment]
closing as fixed by #18340
