### ISSUE TITLE
[LDAP] Allow custom LDAP options (logging)

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony#18448]
I would like to be able to specify custom ldap options that map to `ldap_set_option()`

Of particular interest to me is `ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);` which is set before an LDAP connection is started, that will allow me to troubleshoot problems with my LDAP configuration.

As far as I am aware, troubleshooting LDAP misconfigurations is near impossible without doing this.

Obviously I would want to be able to filter the LDAP log messages as well.

Other useful options would be `LDAP_OPT_TIMELIMIT` for specifying a custom timeout.

**Comment by csarrazi** [comment]
Could do, and that would also be rather trivial to implement.

**Comment by ofbeaton** [comment]
Thank you!

**Comment by csarrazi** [comment]
You're welcome!
