### ISSUE TITLE
[Symfony 2.8] Route Controller Annotation merging with "sub controller route"

### ISSUE THREAD

**Issue by Raffaello** [symfony/symfony#18459]
Hi, 

I have defined 2 controller classes, 1 is extending the others

at the top of that classes there is a route annotation defining the path.

here the short example:

```php
/**
 * @Route("/base")
 */
class BaseController extends Controller
{
    /**
     * @Route( "/first")
     */
    public function firstAction()
    {
// ....
    }
}


/**
 * @Route("/extends")
 */
class ExtendedController extends BaseController
{
    /**
     * @Route( "/second")
     */
    public function secondAction()
    {
// ....
    }
}
```

I was expecting that the `firstAction` was mounted in the `/base/first`
instead is mounted in `/base/extended/first`

is this an expected behaviour or is it a bug?

**Comment by Raffaello** [comment]
forgot to say about `routing.yml` i just load the entire folder:

```
bridgeman_gem_library_manager_api_v1:
    resource: "@TheBundle/Controller/"
    type:     annotation
    prefix:   /
```

**Comment by Tobion** [comment]
You basically expose `firstAction` twice once in BaseController and once in ExtendedController.
So the loader will load the route twice and the second one will overwrite the first one as they have the same name. (In my theory when you rename ExtendedController to AController so it comes before, you might get a different result for the firstAction route).

Maybe you want to make BaseController abstract? The current inheritance doesn't make much sense.

**Comment by Raffaello** [comment]
ah, ok make sense now, It load twice the same action.
Yup the current inheritance doesn't make sense at all in OOP way, 
but I was trying to create a subroute in an already used route with some actions already binded to it and "extends" with a subroute that it will group other actions, anyway short time today tried to find a quick way to do not refactor an entire bundle.

Thanks so much for fastest response.
