### ISSUE TITLE
Unresolved parameters in nested Definition instances

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#18458]
This does not apply to XML/YML loaders, but only to PHP defined containers:

Unless I'm wrong and because ResolveParameterPlaceHoldersPass is not recursive, if one instantiates a `new Definition` and use it as e.g. an argument to some other service, it won't be resolved by ParameterBag. Effectively this means you can't use parameters there, or you need resolve them by yourself for nested definitons (but not for named definitions of course).

Bug or a new feature if this were to be fixed? Ping @stof @fabpot 
(personally I lean towards new feature)

**Comment by xabbuh** [comment]
Do we thoroughly support anonymous definitions? IIRC they only accidentally work in some places and have never been considered as actually supported.

**Comment by nicolas-grekas** [comment]
@xabbuh after investigating, they are supported, but not fully: support has been enhanced from versions to versions.
Which means the answer in now clear: new feature.

**Comment by jakzal** [comment]
> Do we thoroughly support anonymous definitions?

I use it all the time in XML and never had any issues.

**Comment by stof** [comment]
> I use it all the time in XML and never had any issues.

that's because the XML loader actually converts them to named definitions.

> Which means the answer in now clear: new feature.

yeah. new feature. But it would be great to finally fully support it. Behat relies on it for instance (which probably works fine because of the fact it does not dump a container)

**Comment by nicolas-grekas** [comment]
Fixed in 3.3 with AbstractRecursivePass
