### ISSUE TITLE
Installer/Git download v3.0.3 instead of v3.0.4

### ISSUE THREAD

**Issue by gencer** [symfony/symfony#18455]
I am not sure if this is a bug but also `v3.0.4` changelog shows older (`3.0.3`) version info. It says "**Downloading v3.0.4**" on `symfony installer` but when i run my app i get `v3.0.3.`

Does anyone have this issue?

**Comment by javiereguiluz** [comment]
I can't reproduce this:

![symfony_installer](https://cloud.githubusercontent.com/assets/73419/14308565/38e145a4-fbd7-11e5-8044-38941c6d75ee.png)

The only error is that the Symfony version says `3.0.4-DEV` instead of `3.0.4` ... but this is a minor issue we introduced when releasing the stable Symfony version. This is truly the `3.0.4` stable version.

**Comment by gencer** [comment]
![ss-2016-04-06_10_49_40](https://cloud.githubusercontent.com/assets/1711576/14310882/f1d557ac-fbec-11e5-973f-591a1fc22165.png)

Console says 3.0.4-DEV, web interface shows 3.0.3. I cleared all caches, restart php-fpm. Still have this.

**Comment by gencer** [comment]
Composer **insists **that my `vendor` folder is `up-to-date`. I tried both `dev` branch and `v3.0.*`. All is saying is up to date. Since you provided a screenshot, I manually removed whole vendor folder and did a fresh install. Now its working. I never face such this issue before. **Composer makes me think there is something wrong with tags or branches.**

Sorry for this unrelated issue.

I manually close this issue as it is only on my side.

**Comment by WouterJ** [comment]
Please note however that the version constrants in the Kernel class weren't updated during the 3.0.4 release. This means that it still shows `3.0.4-DEV` in the 3.0.4 *stable* release. /cc @fabpot something wrong with your release tool?

https://github.com/symfony/http-kernel/blob/v3.0.4/Kernel.php#L62

**Comment by xabbuh** [comment]
@WouterJ see #18380 and #18390
