### ISSUE TITLE
problem installing symfony 2.8

### ISSUE THREAD

**Issue by henryfitz27** [symfony/symfony#18468]
i have a problem installing symfony 2.8. Please Help me. I am new in Symfony
1.-In most cases you should be fine, but please verify there is no inconsistencies between data provided by Symfony and the intl extension. See https://github.com/symfony/symfony/issues/15007 for an example of inconsistencies you might run into.

**Comment by iltar** [comment]
For support questions, please use one of the listed channels on http://symfony.com/support

You might want to explain the issue you have in case this is a bug or other issue. What's not working or what is the problem you're having?

**Comment by Tobion** [comment]
As the requirements check also says

> intl ICU version installed on your system should match the ICU data bundled with Symfony
