### ISSUE TITLE
symfony after install missing some line in files

### ISSUE THREAD

**Issue by mu4ddi3** [symfony/symfony#18463]
after "**php symfony new test-project lts**"
in fresh project take a look at file:

**vendor\symfony\symfony\src\Symfony\Bundle\WebProfilerBundle\Controller\RouterController.php**

it missing line 14: "**use Symfony\Component\HttpFoundation\Request;**"
And because of this , the profiler dies on routing option.

the line exist in the file from GitHub sources.

**Comment by javiereguiluz** [comment]
@mu4ddi3 thanks for reporting this error. Sadly this is something I introduced by mistake when fixing other things. The good news is that it's already fixed as of #18340 and it will be available in the next version. Therefore, I'm closing this issue as "fixed". Thanks!

**Comment by mehdinajeddine** [comment]
Sorry to reopen this issue.
i used the command "symfony new my_project 2.8" to create my project.
and the line "use Symfony\Component\HttpFoundation\Request;" still missed.
Version of installer > Symfony Installer (1.5.1)
Any idea about that ?

**Comment by dosten** [comment]
You must wait for a new release

**Comment by xabbuh** [comment]
@mehdinajeddine You can also install a specific patch release like this:

```bash
$ symfony new my_project 2.8.3
```
