### ISSUE TITLE
Symfony 2.8.4-DEV

### ISSUE THREAD

**Issue by clytemnestra** [symfony/symfony#18472]
I've created a project using the installer and it shows 'Welcome to Symfony 2.8.4-DEV'.

Am I using a stable version or have I done something wrong?

![sf](http://i.imgur.com/weOh3g6.png)

**Comment by WouterJ** [comment]
@clytemnestra there was a bug with the release tool, causing the version constrants not to be updated. This is fixed now and upcoming releases (e.g. 2.8.5) will have the correct versions again.

For now, yes, you've installed 2.8.4 stable.

**Comment by clytemnestra** [comment]
Too bad you can't quick-fix it. Who knows when 2.8.5 will come (seems there's 1 release per month). It's a bit confusing.

**Comment by ureimers** [comment]
And here I am, crawling through my composer.json, comparing it with the one from the 2.8 Symfony standard edition unable to find any differences that would let Symfony be installed as the DEV version :-)
