### ISSUE TITLE
Problem to the symfony 2.7 upload on heroku

### ISSUE THREAD

**Issue by coleccionista777** [symfony/symfony#18473]
Hello friends, I need your help with a problem to the symfony2.7 upload on heroku, I entered the command “git push heroku master” this is the error : 
https://drive.google.com/file/d/0BztswIqNuWoTQjA4enJzelM0dlU/view
I hope you can help me.
Please excuse my limited English.

**Comment by Tobion** [comment]
See http://symfony.com/support for getting support.
