### ISSUE TITLE
Problem with validation for textarea on smartphone/tablet

### ISSUE THREAD

**Issue by Laurent3170** [symfony/symfony#18477]
I have asked on StackOverflow at http://stackoverflow.com/questions/36456757/symfony-doesnt-validate-on-iphone, but it seems to be not a kind of bug, but maybe a problem... If you can help :smile:

I have set an entity with this code

```
/**
 * @Assert\Length(
 *      min = 20,
 *      max = 2000,
 *      minMessage = "message.min_length",
 *      maxMessage = "message.max_length"
 * )
 */
protected $message;
```
When I'm using a desktop navigator it refuses to send, when the message is less than 20, but when on iphone or tablet (android), the message is sent, even empty. The field is a textarea. Any ideas ?
I am using `if($form->isSubmitted() && $form->isValid())` to validate the form.

**Comment by lewis-spears-flashtalking** [comment]
This is not an issue with symfony, it's an issue with the implementation. I have provided an answer that should get the validation working for you.

**Comment by Laurent3170** [comment]
Thanks I have a look at it

**Comment by xabbuh** [comment]
As said I don't see why this should be an issue with Symfony (but we can always reopen if it turns out be a bug).

**Comment by Laurent3170** [comment]
And in fact (see the discussion on StackOverflow) the problem is with empty. Assert/Length doesn't seems to cover Assert/NotBlank. But here I don't know if it's a "bug" or something attended.

**Comment by Laurent3170** [comment]
So it's not a bug I had the answer on StackOverflow. Thanks!
