### ISSUE TITLE
Event console.command not fired when calling command inside another command

### ISSUE THREAD

**Issue by bertoost** [symfony/symfony#18470]
I have created a bundle to run scheduled commands (didn't search for existing ones). I made a command to run these scheduled commands. My bundle is named "scheduler" and the command that is set to the crontab is;

```
$ php bin/console scheduler:run
```

I run commands from this scheduler command like this;
(this is an example, I'm running it database driven)

```
$runCommand = 'the:command:to_run';
$runProperties = array('argument' => 'value', '--option' => 'value2');
$runProperties['command'] = $runCommand;

$command = $this->getApplication()->find($runCommand);

$cmdInput = new ArrayInput($runProperties);
$cmdOutput = new BufferedOutput();

$command->run($cmdInput, $cmdOutput);
```

The problem;
I have a global custom option added to all console commands and this is unavailable from here, since the "console.command" event not is dispatched here.

When I add the following lines just before the $command->run() command, my custom global option works.

```
$event = new ConsoleCommandEvent($command, $input, $output);
$this->getContainer()->get('event_dispatcher')->dispatch(ConsoleEvents::COMMAND, $event);
```

I hope I explained it well :-)

**Comment by iltar** [comment]
The best way to ask support questions are listed on: http://symfony.com/support

Regarding your issue, you will have to call `doRun()` on the `Application` if I look at the code. This method will call `doRunCommand()` which fires the event.

**Comment by bertoost** [comment]
@iltar
I was not requesting suppport. Didn't know there was a way to call it on the Application. This also fixes my problem. Thanks!
