### ISSUE TITLE
[Console] Exit status is 0 on PHP7 when there is a \Throwable exception

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#18484]
Hi!

Pretty basic example

```
<?php
$a = null;
$a->getId();
```

This in PHP7 will throw an `\Error`, which implements the `\Throwable` interface. However, on https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L118 we are only catching `\Exception` to set the status code to 1. As a result, those especial exceptions in the console end up with an 0 exit status code, when it should be 1 as with all other normal exceptions. Thanks! Can work on a PR if needed :)

**Comment by iltar** [comment]
There's going to be a small problem with this method though: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L606

Maybe you could extract the logic or even extract the exception handling away.

**Comment by acasademont** [comment]
Yeah sure, this not as easy as changing the `\Exception` for a `\Throwable`, we would be breaking all PHP5 installs. Some work needs to be done.

**Comment by GrahamCampbell** [comment]
> Yeah sure, this not as easy as changing the \Exception for a \Throwable, we would be breaking all PHP5 installs. Some work needs to be done.

It is as easy as adding another catch block though.

**Comment by GrahamCampbell** [comment]
> changing the \Exception for a \Throwable, we would be breaking all PHP5 installs

Just do what the rest of symfony has done, and use symfony's exception classes to get around this.

**Comment by GrahamCampbell** [comment]
Check if instanceof throwable and not instanceof exception, then if that's true, create this: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/Exception/FatalThrowableError.php, and pass it trough instad.
