### ISSUE TITLE
Password rehash implementation (Bcrypt)

### ISSUE THREAD

**Issue by xtuc** [symfony/symfony#18494]
Hi,

I noticed that if you change the cost of an already hashed password (with Bcrypt), the hash won't change. It will be still valid (password_verify) but in fact it needs to be rehashed.

For that purpose, PHP has a standart function : [password_needs_rehash](https://secure.php.net/manual/en/function.password-needs-rehash.php)

The following code use that behavior in the actual BCrypt encoder implementation.

Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder :

``` PHP
public function isPasswordValid($encoded, $raw, $salt)
{
    /**
     * Password too long
     */
    if ($this->isPasswordTooLong($raw)) {
        return false;
    }

    /**
     * Wrong password
     */
    if (!password_verify($raw, $encoded)) {
        return false;
    }

    $options = [ "cost" => $this->cost ];

    if (password_needs_rehash($encoded, PASSWORD_BCRYPT, $options)) {
        $newPassword = password_hash($raw, PASSWORD_BCRYPT, $options);

        // Persist the new password
    }

    return true;
}
```

The new password needs to be persisted somehow.  Maybe by returning it, see [UserPasswordValidator.php](https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Security/Core/Validator/Constraints/UserPasswordValidator.php#L50).

Note that if PHP changes its PASSWORD_DEFAULT (BCrypt at the moment), the new encoder could migrate from BCrypt to the new algorithm without the need of rehash the entire database manually.

**Comment by michalv8** [comment]
I think the part "// Persist the new password" is a deal breaker here. PasswordEncoderInterface should only encode and check passwords if they are valid. It should be just read-only. To persist new password we would need some kind of "RehashedPasswordPersistHandler" to be injected and it would complicate whole logic of this part of component.

Maybe change BCryptPasswordEncoder to throw an exception if password needs rehash or something like that. Of course on default settings this behaviour would be switched off.

**Comment by iltar** [comment]
What about implementing a `RehashableInterface` and let another layer do the work for you? Possibly on an authentication success event

**Comment by xtuc** [comment]
Yes, I agree with you. The PasswordEncoderInterface only contains pure fonctions. The "// Persist the new password" meant to handle the $newPassword by maybe just returning it. That why I also mentioned the need to update the caller part.

I think throwing an exception isn't the right solution since it needs to store the new password and It will break the pureness of the PasswordEncoderInterface methods.

**Comment by xtuc** [comment]
@iltar I tried to implement it in the OnLoginSuccess but in that context you don't have access to the raw password. You need it to be able to rehash it.

**Comment by iltar** [comment]
One option would be to fire a "token.authenticated" event with the original (contains pw) + authenticated token. @WouterJ @weaverryan is this something you deem useful?

**Comment by javiereguiluz** [comment]
I think I understand @xtuc's need ... but I'm not sure this should be Symfony's responsibility. If you change the cost of the password hashes, your application should probably need to deal with it with some rehashing script.

**Comment by xtuc** [comment]
@javiereguiluz Yes, it's right.

I think that it should be the encoder's responsibility since it's contract is to generate valid password.

I didn't mentions it, the salt can also be updated this way.

**Comment by mathroc** [comment]
> your application should probably need to deal with it with some rehashing script.
@javiereguiluz how could you do that ? you can only have the password when the user login or update his password

**Comment by xtuc** [comment]
@mathroc He meant with a custom controller.

**Comment by stof** [comment]
@xtuc which controller ? No controller is called when the login form is submitted. The request is handled by the security system.

**Comment by xtuc** [comment]
@stof yes, I meant the controller handling the login form.

**Comment by timwsuqld** [comment]
Having to override the built in FormAuthentication controller just to get rehashing when the cost increases is a little silly. We already handle so much of the security, this is just good practice rehashing when possible.

**Comment by weaverryan** [comment]
It would be great to handle this, but that doesn't mean that implementing it in a decent way is possible :). Symfony has no idea where your password is stored or how to update it. So even if we know the password needs to be rehashed and updated in the store, Symfony can't do that. We could maybe make it easy to re-hash all your records in the db with a console command... but even that has drawbacks: only works for db and will likely have issues if you have a huge database, etc.

Unless someone can think of a viable, theoretical solution, I'm -1 on this. I want to be proactive... but grounded in reality :). We could add some documentation about this.

**Comment by robfrawley** [comment]
@weaverryan You can't "rehash all your records in the db with a console command" because the **raw** password is required to perform this operation.

It can only be handled when the *user has submitted their raw password* and it would be great if we could devise a generic solution to this, while still allowing the developer to worry about *how* it is persisted.

**Comment by weaverryan** [comment]
Of course you're right. So even that idea of mine won't work :).

We could dispatch a new event at this moment. It would be a bit weird because the event would need to contain the plain password, but it would allow for this hook.

**Comment by robfrawley** [comment]
That sounds reasonable to me. I share your discomfort with throwing the raw password around in an event, but I don't think there are too many other ways to propagate the information in a generic manner...

**Comment by timwsuqld** [comment]
While it is weird having to put the plain password into an event, I think that it's worth doing. In reality, malicious code doesn't need an event with the raw password to steal it, so having an event is no less secure than the fact we have events for pre/post login where malicious code could grab it out of the request.

**Comment by IMM0rtalis** [comment]
+1 for having any solution here.

**Comment by robfrawley** [comment]
PR #26050 introduces a new `security.authentication.success_sensitive` event (dispatched immediately prior to the existing `security.authentication.success` event) that includes an unsanitized token (raw password included).

This should make it relatively easy to implement a listener and/or subscriber that handles rehashing without exposing the sensitive data to all `security.authentication.success` events. If anyone wants to try to build the "generic rehashing solution" discussed above on top of this, give it a go, but this new event satisfies my requirements, personally.

**Comment by xtuc** [comment]
i'm closing this, i'm not having this issue anymore. Symfony doesn't seems like concerned by my issue anyway.

**Comment by iltar** [comment]
@xtuc have you hcecked the PR that @robfrawley linked 6 days ago? It aims to solve your issue afaik
