### ISSUE TITLE
Process fails inside apache mod_php

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#18503]
## Environment

symfony/symfony               v2.8.4

PHP `5.5.9-1ubuntu4.14` / `API220121212,NTS`

Apache modules: `core mod_so mod_watchdog http_core mod_log_config mod_logio mod_version mod_unixd mod_access_compat mod_alias mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_groupfile mod_authz_host mod_authz_user mod_autoindex mod_bw mod_cgi mod_deflate mod_dir mod_env mod_expires mod_filter mod_headers mod_mime prefork mod_negotiation mod_php5 mod_rewrite mod_setenvif mod_socache_shmcb mod_ssl mod_status`

PHP Extensions: `bcmath, bz2, calendar, Core, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, intl, json, libxml, mbstring, mcrypt, memcachememcached, mhash, mysql, mysqli, newrelic, openssl, pcntl, pcre, PDO, pdo_mysql, Phar, posix, readline, Reflection, session, shmop, SimpleXML, soap, sockets, SPL, standardsysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, Zend OPcache, zip, zlib`
## Problem

``` php
<?php
include __DIR__.'/../vendor/autoload.php';
$proc = new \Symfony\Component\Process\Process('echo TEST');
var_dump(
   $proc->start(),
   $proc->wait(),
   $proc->getExitCode(),
   $proc->getOutput(),
   $proc->getErrorOutput()
);
/* outputs:
NULL NULL NULL string(0) "" string(0) ""
*/

$proc2 = proc_open('echo TEST2', [1=>['pipe', 'w']], $pipes);
var_dump(is_resource($proc2));
if (is_resource($proc2)) {
    var_dump(stream_get_contents($pipes[1]));
    fclose($pipes[1]);
    var_dump(proc_close($proc2));
}
/* outputs
bool(true) string(6) "TEST2 " NULL
*/
```

As you can see, proc_open _kinda_ works at least the output works, but the exit code is null, which is already pretty bad. But then with the Process component I don't even get the output to work.

Note that if I run the script from CLI, it works fine, I get 0 exit codes and output for both examples. Running via Apache mod_php fails.

**Comment by nicolas-grekas** [comment]
How does it behave on 2.8.0?

**Comment by Seldaek** [comment]
On 2.8.0 the first outputs `NULL NULL NULL NULL NULL` which isn't much better ;)

**Comment by nicolas-grekas** [comment]
I'm unable to reproduce on a fresh 14.04LTS Ubuntu, enabling the same PHP extensions as you, but NewRelic. Can you try disabling it plz?

**Comment by Seldaek** [comment]
Not really as it's a prod machine with a bunch of stuff running on it that I am not responsible for. Any chance you install the new relic ext? If you have a VM that is, it's not so hard to quickly add their repo https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian

**Comment by jeremyzahner** [comment]
@nicolas-grekas @Seldaek I could actually let them disable the extension on the system mentioned, if that would help debugging.

**Comment by Seldaek** [comment]
@jeremyzahner ok if you can then that's cool, then run the test.php again to see if it still returns null and empty strings or not :)

**Comment by jeremyzahner** [comment]
@Seldaek I just put in the request. Don't know if it will go through just today or tomorrow first thing. Usually they are pretty fast. I will get back to you when its done.

**Comment by jeremyzahner** [comment]
@Seldaek The output i get (right now) by the way is:

`NULL NULL NULL string(5) "TEST " string(0) "" bool(true) string(6) "TEST2 " NULL`

**Comment by Seldaek** [comment]
What?! :) I get this:

`NULL NULL NULL string(0) "" string(0) "" bool(true) string(6) "TEST2 " NULL`

Can you email me details as to what and how you call it? (Sorry @nicolas-grekas it's a private server..)

**Comment by nicolas-grekas** [comment]
Sorry, even with NewRelic, I'm unable to reproduce, here is the phpinfo output:
[phpinfo.pdf](https://github.com/symfony/symfony/files/215298/phpinfo.pdf)

**Comment by jeremyzahner** [comment]
@Seldaek Now i get the same output as you do. Ill try to disable newrelic for a moment and check again. Was just calling it in chrome. HOST/test.php

**Comment by jeremyzahner** [comment]
@Seldaek Well it seems to be very very inconsistent. While calling it from the browser directly i mostly get:

`NULL NULL NULL string(0) "" string(0) "" bool(true) string(6) "TEST2 " NULL`

but then again every nth refresh i get 

`NULL NULL NULL string(5) "TEST " string(0) "" bool(true) string(6) "TEST2 " NULL`

Can you reproduce that?

(I disabled newrelic for that specific vhost via php flag for now)

**Comment by jeremyzahner** [comment]
@nicolas-grekas Im happy to provide you with access to the system if that'd help.

**Comment by Seldaek** [comment]
Yeah I also see it.. sometimes it works for the output, really weird. I 
wonder if it depends on which php worker we end up running in or something?

But anyway let's not forget that this is still a fail as the exit code 
is null it will fail any check for `0 === $exitCode`.

**Comment by jeremyzahner** [comment]
@Seldaek The new relic extension is disabled for now. =)

**Comment by Seldaek** [comment]
Nope no visible diff, go ahead and re-enable :/ I'm quite at a loss here.

**Comment by xabbuh** [comment]
What do we do here now?

**Comment by Seldaek** [comment]
No clue, it was @jeremyzahner's machine I don't know what the status is :)

**Comment by xabbuh** [comment]
@jeremyzahner Do you have some news for us? :)

**Comment by jeremyzahner** [comment]
@xabbuh I've put it to rest since it cost us to much time to debug this issue. Also, it didn't occur in our own application but in our instance of [Toran Proxy](https://toranproxy.com/). So feel free to close it.

**Comment by Seldaek** [comment]
OK closing then I guess..
