### ISSUE TITLE
Support for YAML parse where entire document has common leading whitespace?

### ISSUE THREAD

**Issue by dreftymac** [symfony/symfony#18509]
## Example001a
```
// ******************** 
// begin_ init php
  require __DIR__ . "/" . "./app/vendor/autoload.php";
  use Symfony\Component\Yaml\Yaml;
  
// ******************** 
// begin_ init vars
  $mydoc  = ('
myfoo:   bar
myinfo:
  alpha: one
  bravo: two
  charl: three
mytable: &uutable001
  - alpha: one
    bravo: two
  - alpha: three
    bravo: four
othertable: *uutable001
  ');
  $vout     =   Yaml::parse($mydoc);
  print var_export( $vout , true );

// begin_ end php
```

## Example001b
```
// ******************** 
// begin_ init php
  require __DIR__ . "/" . "./app/vendor/autoload.php";
  use Symfony\Component\Yaml\Yaml;
  
// ******************** 
// begin_ init vars
  $mydoc  = ('
    myfoo:   bar
    myinfo:
      alpha: one
      bravo: two
      charl: three
    mytable: &uutable001
      - alpha: one
        bravo: two
      - alpha: three
        bravo: four
    othertable: *uutable001
  ');
  $vout     =   Yaml::parse($mydoc);
  print var_export( $vout , true );

// begin_ end php
```

## Issue
* Example001a works as expected
* Example001b does not parse, presumably because of the superfluous leading whitespace on the yaml document.

## Question
Since the superfluous leading whitespace actually serves a purpose in this instance (code indentation) is it possible to add support for parsing YAML documents that have this kind of uniform leading whitespace throughout the document?

**Comment by javiereguiluz** [comment]
In my opinion this should be fixed by the application before providing the contents to the Yaml component. But let's see what others think.

**Comment by xabbuh** [comment]
I agree with @javiereguiluz. The parser is meant to parse valid YAML. Stripping the leading whitespaces is a task that can be easily done in application code.
