### ISSUE TITLE
Symfony missing parameters in integration tests

### ISSUE THREAD

**Issue by lewis-spears-flashtalking** [symfony/symfony#18517]
Since upgrading my doctrine/doctrine-bundle version to the latest, I keep receiving the following error:

```
exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message
'Warning: array_key_exists() expects parameter 2 to be array, null given' in 
app/cache/test/appTestDebugProjectContainer.php:14663
```

I have described the issue in more details on StackOverflow: http://stackoverflow.com/questions/36569444/symfony-missing-parameters-in-integration-tests-doctrine-doctrine-bundle-1-6-2

**Comment by xabbuh** [comment]
@lewis-spears-flashtalking Can you create a fork of the Symfony Standard Edition with a minimal set of changes that are necessary to reproduce your issue?

**Comment by lewis-spears-flashtalking** [comment]
Yes, I will try to replicate the issue & update with the results.

**Comment by lewis-spears-flashtalking** [comment]
After some investigations, I narrowed it down to some code in my codebase that was reflecting the container properties to be null?! This was legacy code and has since been removed.
