### ISSUE TITLE
debug_backtrace() gives unexpected results for args in php7

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18511]
This is not a direct symfony issue, however i'm notifying symfony users with creating this issue because symfony uses backtraces a lot when showing an error page. Perhaps something in the presentation of the backtrace can be changed or a warning can be given to mitigate the underlying php issue. I will just refer to [this bug report](https://bugs.php.net/bug.php?id=72002)

**Comment by nicolas-grekas** [comment]
Yep, this is known, we can't do anything about it, as stated in the bug report...
