### ISSUE TITLE
[Form] InvalidArgumentException: unlink(/tmp/sf_micro_kernel): Is a directory

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#18512]
ping @nicolas-grekas I've seen this one come by several times; Sadly I don't have the time to dive in this deeper but my guess is that there's something misconfigured in the startup/teardown: https://travis-ci.org/symfony/symfony/jobs/122442688#L2951

```
1) Symfony\Bundle\FrameworkBundle\Tests\Templating\Helper\FormHelperDivLayoutTest::testRestAndRepeatedWithRowPerChild
InvalidArgumentException: unlink(/tmp/sf_micro_kernel): Is a directory
/home/travis/build/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:161
/home/travis/build/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Kernel/ConcreteMicroKernel.php:54
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Util/OrderedHashMap.php:178
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Util/OrderedHashMap.php:178
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Form.php:383
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:59
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Form.php:385
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Form.php:477
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:226
/home/travis/build/symfony/symfony/src/Symfony/Component/Form/Tests/AbstractDivLayoutTest.php:231
```

**Comment by nicolas-grekas** [comment]
I investigated this exception, so did @xabbuh, and we don't know were this exception comes from... The stack trace suggests unlink itself throws it, which look a bit surprizing. Does anyone have an idea?

**Comment by iltar** [comment]
Looking at it again:
```php
if (@(unlink($file) || rmdir($file))) {
```
What if this becomes:
```php
if (@unlink($file) || @rmdir($file)) {
```
Maybe the real issue is that the silencing is broken here?

**Comment by xabbuh** [comment]
@iltar I thought about that too. But why does it only fail on the `master` branch then? The code is the same on older branches.

**Comment by iltar** [comment]
For me this only fails in 5.5 on travis, I assume this is related to not being able to get the latest version of something

**Comment by nicolas-grekas** [comment]
And if we use the proper `rmdir`, this fails with `InvalidArgumentException: rmdir(/tmp/sf_micro_kernel): Directory not empty` !!!

**Comment by kinglozzer** [comment]
If anyone’s interested, I encountered this recently and it appears to be caused by an issue with the error suppression operator when it’s used inside custom iterators: https://bugs.php.net/bug.php?id=72122
