### ISSUE TITLE
[CONSOLE] %command.full_name% assumes you want $_SERVER['PHP_SELF'] prefixed

### ISSUE THREAD

**Issue by kcrawley** [symfony/symfony#18524]
When I import 3rd party commands (such as doctrine migrations) into my application, it assumes (incorrectly) that the command can be executed from the script defined in `$_SERVER['PHP_SELF']`. Developers who bootstrap their application with a bash script or via other means cannot override or modify the behavior of `Command::getProcessedHelp()`

I propose a method called `setFullName($fullName)` be implemented which will override the aforementioned behavior.

**Comment by stof** [comment]
Well, the right extension point would not be to configure the full name, but to add a setting in the Application to customize the script name (replacing only the ``$_SERVER['PHP_SELF']`` part)

**Comment by kcrawley** [comment]
I'm trying to push a branch/PR with a fix.

**Comment by kcrawley** [comment]
@stof would a method named `setFullNamePrefix()` and functionality around it be acceptable?

**Comment by kcrawley** [comment]
#18525

**Comment by kcrawley** [comment]
@stof any feedback on this?

**Comment by fabpot** [comment]
I don't understand the problem. Can you illustrate it with some code?
