### ISSUE TITLE
Unable to find template update 3.0.3 => 3.0.4

### ISSUE THREAD

**Issue by poneymagique** [symfony/symfony#18522]
Since I upgrade from 3.0.3 to 3.0.4 my application is not working anymore.

The template I want to process with twing engine is not found.

here is the code:

    /**
     * Build the HTML from a template and a model.
     *
     * @param $datas
     * @param $template
     * @return string
     */
    public function buildHtml($datas, $template)
    {
        $html = $this->twig->render(
            $template,
            array(
                'datas' => $datas
            )
        );

        return $html;
    }

I pass "WidgetsCoreBundle:weather/five_days.html.twig" in the template variable and i get an error:

Unable to find template "WidgetsCoreBundle:weather/five_days.html.twig" (looked into: /projet/data/httpd/www/widgets/app/Resources/views, /projet/data/httpd/www/widgets/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

it was working in symfony 3.0.3 but not in symfony 3.0.4

**Comment by javiereguiluz** [comment]
@poneymagique thanks for reporting this issue. We have been reported about it in the past days: #18364 and #18497.

The real problem is that the template path that is not working for you in the new Symfony version shouldn't have worked before either.

The right template path in your case should be:

```
WidgetsCoreBundle::weather/five_days.html.twig
```

Or:

```
WidgetsCoreBundle:weather:five_days.html.twig
```

In any case, I recommend you to use the new template path based on Twig namespaces. Then you can forget about the ugly `:` in template paths:

```
@WidgetsCore/weather/five_days.html.twig
```

Considering all this, I'm closing this issue because it's not a present bug but a past bug which has already been fixed. Thanks!

**Comment by poneymagique** [comment]
It was a typo in my issue not in my code (::), I just followed the doc 

http://symfony.com/doc/current/book/templating.html

thank you for support, i works now

**Comment by stof** [comment]
The weird is actually that it worked in 3.0.3. I don't understand how this is possible.

**Comment by poneymagique** [comment]
@stof that works since a long time in symfony

**Comment by poneymagique** [comment]
@stof i have no idea why, i did not investigate but i use it since symfony 2.1 or 2.3 and it was working since my last upgrade. I hope people will not have their application broken (i worked on lots of applications with this syntax)

**Comment by javiereguiluz** [comment]
@stof not only it worked in previous Symfony versions, but it looks like LOTS of people used that wrong syntax. We've received three reports in a few days.

**Comment by poneymagique** [comment]
@javiereguiluz @stof it's not really clear for this point in the docs

**Comment by javiereguiluz** [comment]
@poneymagique thanks for letting us know that. I've opened an issue about this in the Symfony Docs repo to fix it: https://github.com/symfony/symfony-docs/issues/6468

**Comment by poneymagique** [comment]
@javiereguiluz thank you for providing support, i'm happy to provide help on my favorite framework
