### ISSUE TITLE
[ExpressionLanguage] Make use of the PropertyAccess component

### ISSUE THREAD

**Issue by wachterjohannes** [symfony/symfony#18520]
The `ExpressionLanguage` should use the `PropertyAccess` component to get a property from an object. This would be quite easy on the first view by calling the PropertyAccessor on this line https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php#L78 .

Maybe i don't see the big picture but that would make the writing of expressions with object much easier. Instead of writing `object.getTitle()` you could use `object.title` which is much more readable.

**Comment by stof** [comment]
One of the requirements of this component is to be able to compile the expression to a PHP expression (to use it in the dumped container for instance).
This is why it requires having different syntaxes for array access, property access and method call (btw, the PropertyAccess already requires a different syntax for the access to an array key, so ``object.title`` would still not be the same than in Twig templates).

**Comment by wachterjohannes** [comment]
hmm as i said: maybe i dont see the big picture. is there a way to include it into this component (without overriding the parser)?

**Comment by acrobat** [comment]
@stof Maybe it's possible to expose a new method on the PropertyAccess component so we have a representation on how to property is called. So we now if the property can be called directly, or with a getter, etc

So we can get from the property access component has the compile method should return things for access to array, object etc. I don't know if this is possible at all, but this would make us able to use the property-access component in the expression-language

**Comment by apfelbox** [comment]
@acrobat that is not possible, as the actual object in an expression is not known at compile time.

`a.title` <- the compiler can't know, what `a` will be.
(it could even change the type between invocations of the compiled code)

**Comment by acrobat** [comment]
Ah yes that makes sense! Too bad it won't work as it would make the expression language more user friendly (if you want to expose the syntax to users of your site)

**Comment by fabpot** [comment]
Closing as it won’t happen.
