### ISSUE TITLE
[HttpKernel] ExceptionListener::logException() wrong number of arguments

### ISSUE THREAD

**Issue by mweibel** [symfony/symfony#18527]
In commit https://github.com/symfony/symfony/commit/22f480752209e1877b9b47f486edad464ad079a4 the argument `$original` of method `logException` got removed, however there's still [a case in the same class where this third parameter is being used](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L52). 

I assume this is a bug but I'm unsure of the consequences.

**Comment by iltar** [comment]
I think it's just something that's not cleaned up properly, my guess is that you can remove it in a PR.
