### ISSUE TITLE
[DbalLogger] Since 2.8 and the use of iconv_* dev/test env are really slow

### ISSUE THREAD

**Issue by JEDIBC** [symfony/symfony#18539]
Hi,

After migrating a project from 2.7 to 3.0 I noticed that loading fixtures and my test suite became really slow (PHP 5.6.20). A blackfire profiling on `bin/console doctrine:fixtures:load -n --env=test` shows that `iconv_*` is responsible :

![iconv_strlen](https://cloud.githubusercontent.com/assets/292261/14519748/1546a8be-0221-11e6-87f5-4a8036c11c1b.png)

![iconv_substr](https://cloud.githubusercontent.com/assets/292261/14519750/1a7a82b0-0221-11e6-9202-c23e9dd8cc60.png)

The fixtures loaded are only 20 entities but each one stores a 100ko xml in database.

On 2.7, `mb_strlen` wasn't slowed by the size of the data :

![mb_strlen](https://cloud.githubusercontent.com/assets/292261/14519876/b904dd54-0221-11e6-83f9-bbf458fedf69.png)
 
In the mean time I can disable logging & profiling on DBAL for test env via config_test.yml but it is quite penalizing.

**Comment by nicolas-grekas** [comment]
Did you enable the mbstring extension when testing on 3.0?

**Comment by nicolas-grekas** [comment]
Please share a link to the blackfire profile

**Comment by JEDIBC** [comment]
Yes mbstring is enabled ans here's the profile https://blackfire.io/profiles/a80c3b15-7d18-4621-be7a-ff483816c40b/graph

**Comment by JEDIBC** [comment]
That was fast 👍
