### ISSUE TITLE
Doctrine outdated YamlDriver

### ISSUE THREAD

**Issue by miholeus** [symfony/symfony#18535]
Symfony lts version, that is 2.8.4 now, triggers errors when using doctrine yml files.
Error I get is:
`'The ability to pass file names to the '.__METHOD__.' method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.'`
Error is triggered by Yaml.php. 
Doctrine YamlDriver code:
`    protected function loadMappingFile($file)
    {
        return Yaml::parse($file);
    }`
This method is fixed in doctrine 2.5. Please update composer.json file and replace doctrine/orm string with 2.5 version.

**Comment by Tobion** [comment]
This issue would belong to https://github.com/symfony/symfony-standard
But doctrine/orm 2.5 requires PHP 5.4 so it cannot be changed in symfony-standard by default which must stay compatible with PHP 5.3. But you can update the doctrine lib in your project of course.
