### ISSUE TITLE
[Form] datetime with time_widget and empty_value for minutes

### ISSUE THREAD

**Issue by alexoueb** [symfony/symfony#18538]
I have created a FormType with a datetime field which can be set to null. I have defined date_widget as single_text and time_widget as choice, with predefined values. So, in my view I have a field for the date and 2 selectors for the time (hours and minutes). If I send my form with the value 2016-04-14 for the date, 12 for the hours and 00 for the minutes, the value which is saved is good 2016-04-14 12:00:00. But, when I edit the record with the same FormType, the single_text value is 2016-04-14, the hours value which is selected is 12, but the minutes value which is selected is wrong, for the empty value "--" is selected. If I select 15 minutes, all is correct. The problem is that 0 minutes is considered as an empty value.

I use Symfony 2.8.4.

# FormType
```
$builder
    ->add('createdAt', 'datetime', array(
        'date_widget' => 'single_text',
        'time_widget' => 'choice',
        'date_format' => 'yyyy-MM-dd',
        'minutes' => array(
            0  => '00',
            15 => '15',
            30 => '30',
            45 => '45',
        ),
        'label' => 'Created at',
        'empty_value' => '--',
        'required' => false,
    ))
;
```

# View
```
{{ form_label(form.end_date) }}
{{ form_errors(form.end_date) }}
{{ form_widget(form.end_date.date) }}
{{ form_widget(form.end_date.time.hour) }}
{{ form_widget(form.end_date.time.minute) }}

```

I'm sorry, my English is not that good and it's my first issue ^^

**Comment by HeahDude** [comment]
@alexoueb You should reverse your minute choices:
```php
$builder
    ->add('createdAt', 'datetime', array(
        'date_widget' => 'single_text',
        'time_widget' => 'choice',
        'date_format' => 'yyyy-MM-dd',
        'minutes' => array(
            '00' => 0,
            '15' => 15,
            '30' => 30,
            '45' => 45,
        ),
        'label' => 'Created at',
        'empty_value' => '--',
        'required' => false,
    ))
;
```
The choice data `(int) 0` was not mapped after view transformation.

Tested and works well on 2.3.

**Comment by HeahDude** [comment]
Ok I got confused because I saw you still use the alias `datetime` and `empty_value` instead of `DateTimeType::class` and `placeholder`.

Still in 2.8, the issue is the same, the `DateTime` object is transformed in an array in view data wich is passed to the time choices, so using your example:
```php
$timeViewData = array(
    'hours' => '12',
    'minutes' => '0',
    'seconds' => '',
);
$timeChoices = array(
    0 => '00', // is not mapped to string '0'
    15 => '15',
    30 => '30',
    45 => '45',
);
```
To get it works use the string values from `$timeViewData` as choice values:
```php
// ...
'minutes' => array(
    '00' => '0',
    '15' => '15',
    '30' => '30',
    '45' => '45',
);
```

**Comment by alexoueb** [comment]
Thank you very much!
