### ISSUE TITLE
[Console] --verbose with param return an error

### ISSUE THREAD

**Issue by Barno** [symfony/symfony#18545]
Hi, if i use --verbose with param (--verbose=1,2,3)  I  have an error

> [Symfony\Component\Console\Exception\RuntimeException]
>   The "--verbose" option does not accept a value.

I did these steps
Fresh installation
`symfony new barno2 3.0.0`
create Command with 
`php bin/console generate:command` (my command is app:demo)
`php bin/console app:demo --verbose=1`
After this command I have the previous error

without param, return the VERBOSITY_VERBOSE

```
if ($output->getVerbosity() >= OutputInterface::VERBOSITY_VERBOSE) {
      $output->writeln('<fg=black;bg=magenta>VERBOSE</>');
}
``` 

my final workflow
```

php bin/console app:demo --verbose
VERBOSE
Command result.

 php bin/console app:demo --verbose=1
  [Symfony\Component\Console\Exception\RuntimeException]
  The "--verbose" option does not accept a value.

```

PHP 5.6.10

**Comment by javiereguiluz** [comment]
We tried to make the `--verbose` option to accept values ... but it was ultimately rejected: https://github.com/symfony/symfony/pull/17647
