### ISSUE TITLE
SubmitType cannot be the parent of a custom type?

### ISSUE THREAD

**Issue by dlancea** [symfony/symfony#18549]
I have a simple custom form type which uses SubmitType as the parent, however, I'm getting an error. Here is the custom type class:

```
<?php
namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class DeleteType extends AbstractType{

	public function getParent(){
		return SubmitType::class;
	}

}
```

I'm getting the error:

```
Fatal error: Call to undefined method Symfony\Component\Form\Form::isClicked() in /var/www/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/SubmitType.php on line 28
```

I'm thinking that [this line in SubmitType](https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Form/Extension/Core/Type/SubmitType.php#L28) is the problem. When using SubmitType directly, $form is a Symfony\Component\Form\SubmitButton object. But when using SubmitType as a parent, it's a Form type.

My end goal was to customize DeleteType further, but I can't get past this point.

**Comment by dlancea** [comment]
This is in symfony/symfony v2.8.3.

**Comment by xabbuh** [comment]
You may let your form type class implement the `SubmiButtonTypeInterface` so that the Form component uses the `SubmitButtonBuilder` instead of the regular `FormBuilder` when creating the concrete form for your type.

**Comment by dlancea** [comment]
Thanks, @xabbuh, that fixed it.

I feel like that should either be fixed, or be better documented, either in the Custom Form Type docs or the SubmitType reference page.

**Comment by xabbuh** [comment]
You can of course submit an issue in the docs repository if you think we could improve the documentation. However, I fail to see why you would actually have to provide your custom submit type at all.

**Comment by Glideh** [comment]
SF3.
I have many forms with always the same submit button and his customisations (bootstrap classes, label, ...) so I need to make an extension.
I don't have the `isClicked` issue but I have another one which seem to totally prevent me to use this extension:
> Neither the property "save" nor one of the methods "getSave()", ... exist and have public access in class ...

No way to set this field unmapped.

**Comment by stephanvierkant** [comment]
As @Glideh explains, I see a good reason why you should be able to provide a custom submit type.

I had the same problem today (symfony 3.1) and found [this issue on StackOverflow](http://stackoverflow.com/questions/35624785/how-to-create-a-custom-savetype-which-is-child-of-submittype-in-symfony-forms) that explains the problem very well.

**Comment by xabbuh** [comment]
IMO your problem would be much easier have been solved using a form type extension that sets this attribute for all `SubmitType` instances without the need to create a custom type (or you could introduce an option that controls whether or not the attribute should be set).
