### ISSUE TITLE
[Console] Testing commands with mocked dependencies fails since 3.0.3

### ISSUE THREAD

**Issue by ruudvanderweijde** [symfony/symfony#18558]
In symfony 3.0.2 and before you could test a console command with mocks like:

``` php
$application = new Application($kernel);
$application->add(new MyConsoleCommand($myMockedRepository));

// we check it's properly registered :)
$command = $application->find('namespace:my-command');

$commandTester = new CommandTester($command);
// execute command
```

**But since 3.0.3 the mocked object is not set in the console command when it is executed.**
A way to work around it is:

``` php
$myCommand = new MyConsoleCommand($myMockedRepository);
$application = new Application($kernel);
$application->add($myCommand);

$commandTester = new CommandTester($command);
// execute command
```

But then I cannot use the `$application->find()` method.

Was this a desired change? I cannot seem to find it in [the change log](http://symfony.com/blog/symfony-3-0-3-released).

**Comment by xabbuh** [comment]
@ruudvanderweijde Could you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by ruudvanderweijde** [comment]
I did (see https://github.com/symfony/symfony-standard/commit/6ceaf605c3410d2e41154a9f08dc1a476fdc85e1) and found something weird.

The test was all fine, until I require mockery/mockery. Then when I run the test (even without no using mockery) it fails.

**Comment by ruudvanderweijde** [comment]
It seems **not to be related to mockery**, it is related to `composer install` on `v3.0.3`

Steps to reproduce:
```
git checkout v3.0.3
composer install
git checkout 6ceaf605c3410d2e41154a9f08dc1a476fdc85e1
phpunit
```

Result:
```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

E.

Time: 374 ms, Memory: 20.00Mb

There was 1 error:

1) Tests\AppBundle\Command\MyCommandTest::testCommand
Exception: this method should be mocked

/Users/ruud/git/ruudvanderweijde/symfony-standard/src/AppBundle/Service/MyService.php:9
/Users/ruud/git/ruudvanderweijde/symfony-standard/src/AppBundle/Command/MyCommand.php:33
/Users/ruud/git/ruudvanderweijde/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
/Users/ruud/git/ruudvanderweijde/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Tester/CommandTester.php:80
/Users/ruud/git/ruudvanderweijde/symfony-standard/tests/AppBundle/Command/MyCommandTest.php:29
```

**Comment by xabbuh** [comment]
The behaviour you observe is related to the changes done in #17569.

**Comment by xabbuh** [comment]
@ruudvanderweijde Does #20442 fix your issue?

**Comment by ruudvanderweijde** [comment]
@xabbuh No, still the same error.

I noticed that I removed my local repository. Want me to clone symfony-standard again?

**Comment by xabbuh** [comment]
@ruudvanderweijde That would be nice.

**Comment by ruudvanderweijde** [comment]
@xabbuh https://github.com/ruudvanderweijde/symfony-standard/commit/d897fd8a38428a200b5f1bd21c625b3b761f4c98
