### ISSUE TITLE
MimeTypeExtensionGuesser PostScript !== Illustrator

### ISSUE THREAD

**Issue by ctrl-f5** [symfony/symfony#18557]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php#L103

return `ai` as file extension for postscript, this is not the same and postscript has its own extension: `ps`

**Comment by stof** [comment]
Well, as you can see in the comment, this list is taken from the Apache project. And ``ai`` is set as the first postscript extension there as well.

**Comment by ctrl-f5** [comment]
does that mean symfony can't diverge from it?

**Comment by stof** [comment]
well, diverging from it would make maintenance of the list much harder

**Comment by ctrl-f5** [comment]
ok, I will handle this in my userland code then, thx
