### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'appProdProjectContainer' not found

### ISSUE THREAD

**Issue by idchlife** [symfony/symfony#18555]
Suddenly I started getting error from nowhere when accessing website (using app.dev) and trying to clear cache in prod env.

No luck finding source of the problem yet :/

    PHP Fatal error:  Uncaught Error: Class 'appProdProjectContainer' not found in   

    /var/www/.../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:485

**Comment by iltar** [comment]
@idchlife please use one of the support channels listed on https://symfony.com/support as this doesn't look like an issue within Symfony itself as it doesn't randomly break.

**Comment by idchlife** [comment]
@iltar thanks!
