### ISSUE TITLE
[SecurityBundle] Extracting the acl configuration

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#18559]
I need some help in https://github.com/symfony/acl-bundle/pull/2, I'm trying to extract the configuration as described in #14718.

Currently having some issues with `.travis.yml`, would be cool if someone could help out with it.

**Comment by javiereguiluz** [comment]
@iltar I'm closing this issue because it has received no feedback in more than a year.

**Comment by javiereguiluz** [comment]
@iltar sorry! I failed to understand the issue date correctly 😊

**Comment by javiereguiluz** [comment]
Closing because the ACL Bundle has its own repository separated from the Symfony repo ... and because Iltar ultimately fixed all the issues. Thanks!
