### ISSUE TITLE
Email with two and more dots like name@doman...com passes basic validation

### ISSUE THREAD

**Issue by yuriy-yakubskiy** [symfony/symfony#18560]
Email with two and more dots like **name.name@doman...com** passes basic validation

```
        "name": "symfony/validator",
        "version": "v3.0.4",
        "source": { 
            "type": "git",
            "url": "https://github.com/symfony/validator.git",
            "reference": "1adb2c6b321cac70717bb85ce97bbb8d33b3839c"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/symfony/validator/zipball/1adb2c6b321cac70717bb85ce97bbb8d33b3839c",
            "reference": "1adb2c6b321cac70717bb85ce97bbb8d33b3839c",
            "shasum": ""
        },
```

**Comment by javiereguiluz** [comment]
@yuriy-yakubskiy you are right ... but this is not as simple to fix as it could look. There are some ongoing discussions to improve the situation about the email validation. See https://github.com/symfony/symfony/issues/18177

**Comment by xabbuh** [comment]
I am closing here as the simple check is indeed very limited. However, you can use the `egulias/email-validator` package together with the constraint's `strict` option to perform a more elaborated e-mail address check.
