### ISSUE TITLE
SymfonyStyle better aligning multi-line blocks?

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#18564]
Description
---

Currently, a multiline warning block looks like:
```
 [WARNING] Your Symfony Installer version is outdated.
 Execute the command "..." to get the latest version

 Downloading the Symfony Demo Application...
```

It's not very clear that the second line is part of the warning block.

Proposed Solutions
---

I propose to change this to:
```
 [WARNING] Your Symfony Installer version is outdated.
           Execute the command "..." to get the latest version

 Downloading the Symfony Demo Application...
```

Or:
```
 [WARNING] Your Symfony Installer version is outdated.
     Execute the command "..." to get the latest version

 Downloading the Symfony Demo Application...
```

Or indent the complete block:
```
    [WARNING] Your Symfony Installer version is outdated.
    Execute the command "..." to get the latest version

 Downloading the Symfony Demo Application...
```

**Comment by javiereguiluz** [comment]
👍  and not only that: this technique should be applied to everything (that was the original intention). For example, a long comment should not be displayed like this:

```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget libero
venenatis, suscipit lacus eu, volutpat nibh. Integer sit amet lacus nunc. Vestibulum
ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
Pellentesque habitant morbi tristique senectus et netus et malesuada fames
ac turpis egestas. Proin nec mauris sed velit iaculis luctus nec ut nisl.
```

But like this:

```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget libero
// venenatis, suscipit lacus eu, volutpat nibh. Integer sit amet lacus nunc. Vestibulum
// ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
// Pellentesque habitant morbi tristique senectus et netus et malesuada fames
// ac turpis egestas. Proin nec mauris sed velit iaculis luctus nec ut nisl.
```

**Comment by JHGitty** [comment]
:+1: Great idea!

**Comment by chalasr** [comment]
I think that this should be the result for any block:

```
 [WARNING] Your Symfony Installer version is outdated.
           Execute the command "..." to get the latest version

 Downloading the Symfony Demo Application...
```

I have a [WIP](https://github.com/chalasr/symfony/commit/2978ad557bbd3c25b41e8376e295974c4b954b46) that is OK for typed block (warning, success, ...) using this solution. 
Is it correct or is there another one of the proposed solutions that should be used instead?

Comments would also become blocks using `' // '` as prefix.
Really interested for any suggestion.

**Comment by JHGitty** [comment]
@chalasr This is Off-Topic - but may be interesting not just for me. How did you do the awesome color backgrounds for "INSERT" and "dev" branch left from the cursor?

**Comment by chalasr** [comment]
@JHGitty Glad to hear that.

I use the ohmyzsh [budspencer theme](https://github.com/tannhuber/oh-my-zsh-budspencer), nothing more (background colors are the default ones).
Don't forget the powerline font as said in the readme, it's required to make it works.
