### ISSUE TITLE
Serializer and Validator mappings don't use Bundle#getPath()

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#18563]
## Description

The bundle class has a `getPath()` method, allowing you to override the path of the bundle. However, inside the FrameworkExtension, `$reflection->getFileName()` is used to get the path to the bundle. This means that `getPath()` is ignored.
## Use-case

In my case, my bundle directory structure looks like:

``` php
MyBundle/
  src/
    MyBundle.php
    ...
  Resources/
    config/
      serializer.yml
      validator.yml
```

In the `MyBundle` class, I override `getPath()` to return `MyBundle/`. This way, I would expect the serializer and validator configuration to be loaded. However, since they use reflection they're looking for `MyBundle/src/Resources/config/serializer.yml`.
## Possible Solution

The auto-discovery of config files should be moved to a compiler pass. These have access to the bundle class instance (instead of FQCN) and can call `->getPath()` on this instance instead of simulating the default behaviour of this method.

**Comment by chalasr** [comment]
👍  Same here, forced to use the default location.

@WouterJ How would you get the bundle class instance in a compiler pass?
I mean without manually creating the instance from the FQCN (as we could do in the FrameworkExtension).

**Comment by iltar** [comment]
I think one of my colleagues hit this bump when trying to register virtual bundles.

**Comment by chalasr** [comment]
@iltar @WouterJ To get around this I added the following method to the FrameworkExtension:

```php
private function getBundlePath($fqcn)
{
    $reflection = new \ReflectionClass($fqcn);
    $getPathReflection = new \ReflectionMethod($fqcn, 'getPath');
    $path = $getPathReflection->invoke(new $fqcn()) ?: dirname($reflection->getFilename());

    return $path;
}
```

Then I use it like

```php
$dirname = $this->getBundlePath($class);
````

Instead of 

```php
$reflection = new \ReflectionClass($fqcn);
$dirname = dirname($reflection->getFilename());
```

The logic is repeated 3 times in the extension.
What do you think about this?

It would be cleaner in a compiler pass using the instances directly, but I can't access `$container->get('kernel')->getBundles()` because the service is synthetic, same in the extension (tried with the SerializerPass for instance). I would like to have your suggestions.

Otherwise, if my workaround sounds good for you, should I submit a patch on master?
Thank's.

**Comment by iltar** [comment]
If I understand the issue correctly, the problem lies with the Bundle files being meta information and functional at the same time.

**Comment by chalasr** [comment]
Related SO question http://stackoverflow.com/questions/36714520/retrieve-bundle-class-instance-from-a-compiler-pass

**Comment by ro0NL** [comment]
@wouterj what about [this](https://github.com/symfony/symfony/pull/19586#discussion_r74277611) approach?

**Comment by chalasr** [comment]
According to [this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L789), this issue should concern the bundle's `translations` directory too.

Some solutions are actually proposed in #19606 and #19646 (Only tested with #19646 and it indeed fix it as it makes bundle instances available from any extension).

**Comment by ro0NL** [comment]
To clarify; this is also not about moving things from extensions to compilers (it could be legit though) as in both cases there's no context whatsoever available. Extensions are just part of a compiler.

**Comment by chalasr** [comment]
See https://github.com/symfony/symfony/pull/21113
