### ISSUE TITLE
 CliDumper Call to undefined function iconv_strlen()

### ISSUE THREAD

**Issue by ahmedash95** [symfony/symfony#18565]
i don't know why i see this error with laravel project when i write 
```
 dd('Ahmed');
```
i get 
```
FatalThrowableError in CliDumper.php line 172:
Fatal error: Call to undefined function Symfony\Component\VarDumper\Dumper\iconv_strlen()
```

**Comment by nicolas-grekas** [comment]
you need to install the iconv extension. It's surprising that it's not already installed on you PHP.
Alternatively, you can `composer require symfony/polyfill-iconv`

**Comment by ahmedash95** [comment]
oh  i installed php70-iconv and it works fine now. thanks for replay.
