### ISSUE TITLE
BCryptPasswordEncoder causing redirect to login page

### ISSUE THREAD

**Issue by taylankasap** [symfony/symfony#18577]
When I'm trying to change another user's password to something longer than 72 characters (when using Bcrypt), because of [this](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Encoder/BCryptPasswordEncoder.php#L70) it redirects me to the login page. Not logging me out, just redirecting.

```
security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. 
{"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0):
Invalid password. at 
/projectpath/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Encoder/BCryptPasswordEncoder.php:70)"} []
```

Maybe fix by throwing a different exception?

I'm using v2.8.2. But I'm guessing this happens in master too (because same line of code exists), not sure though.

**Comment by taylankasap** [comment]
I just realized this is an issue with all password encoders & not just bcrypt. I'm guessing if I use 4097 character password when using PlaintextPasswordEncoder the outcome will be same.

**Comment by nicolas-grekas** [comment]
This is expected behavior, nothing wrong here. Password must have a limit, otherwise we open the door to DOS.

**Comment by taylankasap** [comment]
The issue here is, it is redirecting _me (the admin user)_ when I'm trying to change _another user_'s password. Or are you still saying this is expected behavior?

I think it would be better if it throws an exception which is not handled by default. At least that way the developer will know to add a length validation.

**Comment by stof** [comment]
@taylankasap this would create issues when checking the password.

IMO, what you really need is to have some form validation forbidding to set a password longer than allowed *before* reaching the encoder.

**Comment by taylankasap** [comment]
@stof Yes, I know that'll do it.

It's not like this is causing any issues to me. I'm just stuck at the part where this is the _expected behavior_. Maybe we can settle with "**it's not worth the hassle**".

**Comment by jakzal** [comment]
@taylankasap have you tried handling the BadCredentialsException? The default exception handler will redirect to the authentication entry point. Catch the exception if you'd like to handle it differently.

**Comment by javiereguiluz** [comment]
Closing this issue because the current behavior is considered "correct" and as @jakzal said, the `BadCredentialsException` can be caught to deal with this error.
