### ISSUE TITLE
Some parameters are missing. Please provide them

### ISSUE THREAD

**Issue by Tshepang-dev** [symfony/symfony#18572]
symfony/console suggests installing symfony/process ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/validator suggests installing symfony/intl ()
symfony/validator suggests installing egulias/email-validator (Strict (RFC compliant) email validation)
symfony/validator suggests installing symfony/property-access (For using the 2.4 Validator API)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/var-dumper ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/security-core suggests installing ircmaxell/password-compat (For using the BCrypt password encoder in PHP <5.5)
symfony/security-http suggests installing symfony/security-csrf (For using tokens to protect authentication/logout attempts)
symfony/security-acl suggests installing symfony/class-loader (For using the ACL generateSql script)
symfony/doctrine-bridge suggests installing symfony/form ()
symfony/doctrine-bridge suggests installing doctrine/data-fixtures ()
backbee/backbee suggests installing symfony/form (Allows you to use Symfony Form Component integration)
Writing lock file
Generating autoload files
Creating the "repository/Config/parameters.yml" file
Some parameters are missing. Please provide them.
debug (false):

**Comment by iltar** [comment]
So what's the problem? If you need help, please visit one of the support channels: http://symfony.com/support

**Comment by xabbuh** [comment]
As Iltar said we use GitHub only for coordinating the development process. So please use one of the support channels. Thank you for understanding.
