### ISSUE TITLE
Example about `empty_data` option related to `ChoiceType` at `IntegerType` documentation

### ISSUE THREAD

**Issue by Ziiweb** [symfony/symfony#18582]
Why is there an example about `empty_data` option related to `ChoiceType` at `IntegerType` documentation?

http://symfony.com/doc/current/reference/forms/types/integer.html#empty-data

**Comment by javiereguiluz** [comment]
@Ziiweb please, for issues related to Symfony documentation open an issue at https://github.com/symfony/symfony-docs repository. We'll gladly help you there. Thank you!

**Comment by moldcraft** [comment]
I work with Symfony 2+ years and still don't know how to set default value for form fields

* `data` is useless - it overwrites the saved value
* `empty_data` doesn't work at all on my side (Symfony 3.2.7)

https://stackoverflow.com/q/7913086/1794248
