### ISSUE TITLE
Session default value not being set

### ISSUE THREAD

**Issue by pedrocasado** [symfony/symfony#18586]
Im trying to retrieve a value from the session and use the default parameter but it's returning NULL instead of the empty array from the following code:

    $session = new Session();
    $cart = $session->get('cart', array());
    var_dump($cart);exit;

Symfony 3.0.4
PHP 5.6.18

**Comment by iltar** [comment]
This is not how you use sessions in the Framework. I you want to access the session, use either `$request->getSession()` or get the service called `session`.

I have also tried the code you have presented and it gives me an empty array.

**Comment by pedrocasado** [comment]
Looks like that was something weird within my environment. I did restart php/nginx and the empty array worked either within the `new Session()`. I replaced then by `$request->getSession()` as you mentioned. Thanks.
