### ISSUE TITLE
Why logger service can't be injected in a Extension or  CompilerPass?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#18595]
please read details in  http://stackoverflow.com/questions/34126000/why-logger-service-cant-be-injected-in-the-compilerpass

**Comment by iltar** [comment]
@videni this issue tracker is not meant for support. You can find the support channels on http://symfony.com/support

If SO doesn't give you the answer,  you can always hop by on IRC.

**Comment by javiereguiluz** [comment]
@videni, as @iltar mentioned, in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support as you already did. Thanks!

**Comment by videni** [comment]
@javiereguiluz, @iltar, got it, thanks for your remind
