### ISSUE TITLE
[DependencyInjection] [DX] Unhelpful error message when being stupid while declaring a service as a factory

### ISSUE THREAD

**Issue by lstrojny** [symfony/symfony#18598]
Wrong:

```
<factory id="foo.factory" class="FooFactory"/>
```

Correct:
```
<factory service="foo.factory" class="FooFactory"/>
```

When doing it incorrectly, the error message says this:
```
RuntimeException in PhpDumper.php line 1437: Cannot dump definition because of invalid class name ('')
```

Maybe instead we can complain that the configuration is broken with a more meaningful error message.

**Comment by iltar** [comment]
@lstrojny like this one? #18547 

It's already merged so it should be there next release.

**Comment by stof** [comment]
Closing as 3.1 will indeed have a better error message

**Comment by lstrojny** [comment]
Yep, thank you!
