### ISSUE TITLE
Polyfills should not be required by symfony components

### ISSUE THREAD

**Issue by tpraxl** [symfony/symfony#18592]
Just noticed that requiring `symfony/http-foundation` in composer installs `symfony/polyfill-mbstring`.
I understand this polyfill as a support for an environment where the php mbstring extension is not installed. So, in order to keep the vendor-directory tight, I would prefer if `symfony/http-foundation` would not `require` `symfony/polyfill-mbstring` but if it would `suggest` its usage:
```
"suggest": {
    "symfony/polyfill-mbstring": "Necessary, if php mbstring extension is not installed in your environment."
}
```
Just a tiny issue. Might have a big impact when looking at symfony as a system and all the projects that use it.. However, I would appreciate the suggested change very much.

**Comment by stof** [comment]
if we don't require it, we would still have to check for availability of mbstring functions and provide a fallback. ``symfony/polyfill-mbstring`` will be a no-op when mbstring is installed.

**Comment by tpraxl** [comment]
Ok. Thanks for your answer. 
I thought it would be OK for the component to fail if mbstring is not installed, because the author can just add the requirement to her project as it would have been suggested by composer. Very well then. Don't mind. Thank you very much for your response.
