### ISSUE TITLE
2.7: Could not load type "Symfony\Component\Form\Extension\Core\Type\ChoiceType" on example

### ISSUE THREAD

**Issue by xDaizu** [symfony/symfony#18605]
In your [2.7 docs](http://symfony.com/doc/2.7/reference/forms/types/choice.html) show examples like:

```
$builder->add('isAttending', ChoiceType::class, array(
    'choices'  => array(
        'Maybe' => null,
        'Yes' => true,
        'No' => false,
    ),
));
```

but that code thows a "Could not load type "Symfony\Component\Form\Extension\Core\Type\ChoiceType" " exception. Writing `$builder->add('isAttending', new ChoiceType(), array(` worked, though.

**Comment by stof** [comment]
Looks like the update of the doc for 2.8+ features has been merged in the wrong branch.

> Writing ``$builder->add('isAttending', new ChoiceType(), array(`` worked, though.

don't do it. Passing a new instance forces Symfony do redo some heavy work, and so has a perf impact. Use ``$builder->add('isAttending', 'choice', array(`` in 2.7

**Comment by aitboudad** [comment]
related to https://github.com/symfony/symfony-docs/issues/6501

**Comment by xDaizu** [comment]
> Use $builder->add('isAttending', 'choice', array( in 2.7

Thanks for the advice! Not remembering how it was supposed to be done I just tried the first thing that came to mind :sweat_smile:
