### ISSUE TITLE
[DomCrawler] closest() and outerHtml()

### ISSUE THREAD

**Issue by rafis** [symfony/symfony#18609]
Can you please add `closest()` to DomCrawler?

http://james.padolsey.com/jquery/#v=2.1.3&fn=jQuery.fn.closest

This is pseudo-code, not tested:

``` php
    public function closest($selector)
    {
        if (!count($this)) {
            throw new \InvalidArgumentException('The current node list is empty.');
        }

        $node = $this->getNode(0);
        while ($node = $node->parentNode) {
            if (XML_ELEMENT_NODE === $node->nodeType) {
               $parent = $this->createSubCrawler($node)->filter($selector);
               if ($parent->count()) {
                  return $parent;
               }
            }
        }

        return null;
    }
```

**Comment by xabbuh** [comment]
I am not sure if we need this as you can already achieve what you need by using the `filterXPath()` method.

**Comment by rafis** [comment]
Another feature request `outerHtml()`:

```php
    public function outerHtml()
    {
        if (!count($this)) {
            throw new \InvalidArgumentException('The current node list is empty.');
        }

        $node = $this->getNode(0);
        $html = $node->ownerDocument->saveHTML($node);

        return $html;
   }
```

**Comment by xabbuh** [comment]
@rafis That's what the `html()` method does, isn't it?

**Comment by rafis** [comment]
`html()` returns `innerHtml()`.

**Comment by javiereguiluz** [comment]
I'm 👎 for adding these new methods. The reason is that we must be cautious when adding new features (they will potentially introduce bugs and they must be maintained forever). When lots of people ask for something, you know that you are missing that feature, but that's not the case for these methods because this is the first time the are asked for.

**Comment by adamhopkinson** [comment]
@javiereguiluz agree with the need to be stringent on what to add, but I found this issue while looking for a way to get `outerHtml`.

I've tried importing the node into a new `DomDocument` and then calling `DomDocument::saveHTML()`, but getting nothing returned.

**Comment by 3zzy** [comment]
+1 for outerHTML. Why? `table` for example:

```
$tables = $crawler->filter('table')->each(function (Crawler $node, $i) {
  return $node->html();
});
```

.. this would just return the tables without the `table` tag itself resulting in an invalid and unusable HTML.

**Comment by stof** [comment]
@adamhopkinson the code in https://github.com/symfony/symfony/issues/18609#issuecomment-212952371 gives you a solution to get the outerHtml. you can do it outside the crawler, as ``getNode()`` is public.

**Comment by adamhopkinson** [comment]
@stof yes thanks I'd seen this - my comment was a reply to @javiereguiluz saying he was against adding this method to the codebase.

Think I confused things by detailing what I'd originally tried to do to get `outerHtml` - I'd added this to explain why I thought it should be core.

**Comment by 3zzy** [comment]
`$doc = $crawler->html();` as well get the `innerHTML` not the full responose body.

**Comment by backbone87** [comment]
@xabbuh how would you do closest with xpath? afaik libxml used by php xml extension doesnt support the subsequence function, so `subsequence(//a/ancestor::b, 1, 1)` wont work

**Comment by AlexeyKosov** [comment]
>  The reason is that we must be cautious when adding new features (they will potentially introduce bugs and they must be maintained forever).

@javiereguiluz That's a good reason to stop programming at all. 
Why don't add the functionality but very cautiously, i.e. write required tests, etc?

**Comment by AlexeyKosov** [comment]
Here's my implementation of `closest` (it's an external function):

https://gist.github.com/AlexeyKosov/6aad332bcfd614f92933146a344c89eb

**Comment by mdecaffmeyer** [comment]
It would be nice indeed to have these two **very** useful functions:)

**Comment by reedzhao** [comment]
+1 for outerHTML.  In my case I need to save the html to work on later.  There are important attributes in the outerHTML.

**Comment by lyrixx** [comment]
I have the same kind of need.

I have a list of `li` and I want to select on specifc li according to its content.
What I have done for now is:

```php
$parents = $crawler->filter('li h3:contains("Lille")')->parents();

$li = $parents->reduce(function(Crawler $a, $i) use ($parents) {
    $node = $parents->getNode($i);

    return $node->tagName === 'li';
});
```

But I don't really like this code. I have to grab the real `DomElement` from the `$parents`.

And I need this hack because I want to work with a Crawler instance. (much easier than Dom*)

**Comment by redemption** [comment]
would love to see a closest() function being made.

**Comment by desmax** [comment]
please outerHtml!

**Comment by songweizong** [comment]
code for outerHtml

```
$crawler = new Crawler("<div><p id='p1'>p1</p><p id='p2'>p2</p></div>");
$crawler->filter("p")->each(function (Crawler $node, $i) {
    $domElement = $node->getNode(0); //important: get DOMDocument object from Crawler object
    $html = $domElement->ownerDocument->saveHTML($domElement);
    dump($html); //in laravel
});
```

reuslt: `<p id="p1">p1</p>  <p id="p2">p2</p>`

**Comment by welcoMattic** [comment]
👍 for `outerHTML` method

**Comment by mikeburton220** [comment]
Would love for the outerHTML method to be included, but this is how I'm doing it with filterXPath.

$domElement = $crawler->filterXPath({xpath expression})->getNode(0);
$html = $domElement->ownerDocument->saveHTML($domElement);

**Comment by fabpot** [comment]
Anyone willing to submit a PR for that popular request?

**Comment by lyrixx** [comment]
I'm on it :tada:
