### ISSUE TITLE
[HTTP Cache] 2.8 Question about ESI cache clearing/updating

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#18607]
Hi,

I am implementing some render_esi with the symfony reverse proxy. It works well and it is very helpfull.

But I would like to know if there is a good way to clean the per fragment twig generated and cached inside http_cache/ in app/cache folder ? 

In fact, is there a best practice to have a kind of service or anything else that can reload/regenerate a new twig cached block?

For the moment, I only rm -rf %kernel.cache_dir%/http_cache/* :s 

Many thanks

**Comment by iltar** [comment]
Isn't this simply cache invalidation?

**Comment by GromNaN** [comment]
Your question mix Twig cache and HTTP cache.
- Twig cache should not be cleared, unless you modify the templates files.
- HTTP cache can be invalidated with HTTP headers (which is a generic solution that would work with other cache proxies) or in code with [`Store::invalidate($request)`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L233)

**Comment by noniagriconomie** [comment]
Hi

@iltar did not understand your word, can you explain?

@GromNaN indeed, what I need is forcing the twig rendered as html into the http_cache to be cleared and rebuild. I will try the store invalidate like you said

Thanks

**Comment by jakzal** [comment]
@noniagriconomie Symfony documentation has a whole section about [cache invalidation](http://symfony.com/doc/current/book/http_cache.html#cache-invalidation) in the caching chapter. It's also worth to check the [FOSHttpCacheBundle](http://foshttpcachebundle.readthedocs.org/en/latest/).

I'm closing as there's nothing to do in Symfony. Please seek support on one of the official [channels](http://symfony.com/support).
