### ISSUE TITLE
APCu caching of validator and serializer metadata on Ubuntu 16.04

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony#18612]
Ubuntu 16.04 does not ship with apcu-bc. It is therefore not possible to use both `validator.mapping.cache.doctrine.apc` and `serializer.mapping.cache.doctrine.apc` on symfony installs on this OS. 

Looks as if `*.*.*.apcu` does not exist either so no alternative.

The ApcClassLoader works fine however.

**Comment by nicolas-grekas** [comment]
???

**Comment by lyrixx** [comment]
:question:

**Comment by tucksaun** [comment]
❔

**Comment by luispabon** [comment]
Sorry, dropped my e-cig on the enter key as I was typing the title! Description updated

**Comment by luispabon** [comment]
I'm going to close this for now as I'm seeing other weirdnessess going on under Ubuntu 16.04's bundled PHP. I'm not entirely sure Symfony is at fault here. Will investigate and reopen if necessary.

**Comment by aistis-** [comment]
I confirm having the same issue. Please reopen the issue :disappointed:
