### ISSUE TITLE
[Process] Extending Process and ProcessBuilder

### ISSUE THREAD

**Issue by boite** [symfony/symfony#18611]
It would be good to be able to extend Process and ProcessBuilder to be able to create custom processes, such as building an SSH process and using it to do an SSH exec.

The properties of both classes are declared with private visibility making them less useful as bases for extending.

Should a PR seek to declare the properties as protected or provide more getters?

**Comment by jakzal** [comment]
@boite to make maintenance easier all the properties are private by default. We usually don't relax their visibility unless there's a good use case. You already gave an example of SSH process. Would you mind should a more detailed example? What's currently private and you'd find useful to open?

**Comment by nicolas-grekas** [comment]
@boite can't you just decorate a Process instance instead of extending it?

**Comment by boite** [comment]
Thanks for the suggestion @nicolas-grekas, I will give it a go.

**Comment by xabbuh** [comment]
@boite Did you make some promising progress?

**Comment by boite** [comment]
@xabbuh As yet I have not had time to dedicate to it, but I hope to soon and will certainly provide an update on progress; please bear with me.

**Comment by nicolas-grekas** [comment]
Closing, please reopen if needed.
