### ISSUE TITLE
[Form] Option for ISO 3166-1 countries only, in CountryType field

### ISSUE THREAD

**Issue by ianmclaughlin** [symfony/symfony#18613]
`CountryType` offers countries based on `Intl::getRegionBundle()->getCountryNames()`  which may not be ISO 3166-1 compliant. The `Country` constraint can check for a ISO 3166-1 complaint country.

As an example, for "en" regions, "Ascension Island" is offered as a country, but is disallowed by the constraint. We can, of course, fix this by compiling and providing our own list.

As a better approach, can `CountryType` have an option to show only countries which match the `Country` constraint?

**Comment by jakzal** [comment]
> "Ascension Island" is offered as a country, but is disallowed by the constraint. 

Not sure why you have arrived at this conclusion. The `Intl::getRegionBundle()->getCountryNames()` is actually used by the `CountryValidator`, and all it does is it checks if country code key is present on the list. `AX` (Ascension Island) validates as a country. 

We already disallow some regions while generating data: https://github.com/symfony/intl/blob/master/Data/Generator/RegionDataGenerator.php#L44-L60 but I don't think this is the case we should exclude as we mainly exclude uninhabited islands or sub-continents.

**Comment by ianmclaughlin** [comment]
Sorry about that confusion.

Let me replace "but is disallowed by the constraint" with "but should be disallowed by the constraint".

The Country Constraint claims to validate to ISO_3166-1, but Ascension Island does not appear on
https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

I have downstream systems which require ISO_3166-1 countries, and Ascension Island (ISO 3166-2 SH-AC) should not be getting through

**Comment by xabbuh** [comment]
So if I understand this correctly, we need to fix the generator command of the Intl component instead?

**Comment by ro0NL** [comment]
see #31365 

> Ascension Island is an isolated volcanic island
> (https://en.wikipedia.org/wiki/Ascension_Island)
