### ISSUE TITLE
3.0.4 Security login form

### ISSUE THREAD

**Issue by james-fruhbauer** [symfony/symfony#18614]
By using same code as is described in documentation to log in (cookbook traditional form + DB user provider) check_path route defined in security .yml doesn't hook login form submission and it does't return any error or redirection.

**Comment by hhamon** [comment]
Hi James,
The Github issue tracker is not supposed to receive support requests. We recommend to use the official Forums or the StackOverflow channel for it. Your problem is probably due to the fact that your `check_path` url pattern is not captured by the firewall url prefix.

**Comment by xabbuh** [comment]
@james-fruhbauer As @hhamon said please use [our support channels](http://symfony.com/support) to seek for help. Thank you for understanding.
