### ISSUE TITLE
Validator constraint on cascade delete?

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#18615]
Hello,

Is is possible to validate a an entity with a cascade delete relation to check if a removed child is referenced by another entity?
So we can set a custom error message like "Unable to remove XXX because it is already attached to a XXX."

I would like something like the @UniqueEntity validator constraint used to check if another entry already exists.

Actually I am getting a SQL error:

> ORA-02292: integrity constraint (xxx.FK_xxx) violated - child record found at...

Thanks

**Comment by jakzal** [comment]
Please use one of our support channels to get support: http://symfony.com/support

Hint: you'd probably need to provide your custom constraint to accomplish what you need.

thanks :)
