### ISSUE TITLE
[Console] Missing required value on options does not trigger the appropriated exception

### ISSUE THREAD

**Issue by aledeg** [symfony/symfony#18617]
When using a command with an option which requires a value, you receive a ```Symfony\Component\Console\Exception\RuntimeException``` when you provide said option without a value.

When you test a command with an option which requires a value, you receive a ```Symfony\Component\Console\Exception\InvalidOptionException``` when you provide said option without a value.

I think we should be able to get the same exception in those 2 cases. I don't know which one is appropriated though.

I made a branch on [symfony-standard](https://github.com/aledeg/symfony-standard/tree/command-option-exception) to show my use case.
If I am missing something to make it works the way it should, let me know.

*Note*: I am using symfony 2.8

**Comment by peterrehm** [comment]
The "issue" is that the Application uses `Input/ArgvInput` while the CommandTester is using `Input\ArrayInput`. I think the InvalidOptionException makes more sense. I will submit a PR.

**Comment by nicolas-grekas** [comment]
It would be more consistent, but unfortunately it would be a BC break and we have no migration path for this kind of things. Closing as won't fix.
