### ISSUE TITLE
[Proposal][Validator] Integrate OptionsResolver for constraints

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#18628]
Here's a wild idea; i think it would be nice if we can define constraint options using the `OptionsResolver` component, similar as form types are doing...

Imho this would improve the API for writing constraints (separating options from real class properties), providing consistent error messages/validation/etc., and less plain PHP code for the developer.

We could even enhance the `OptionsResolver` with some sort of `defaultOption` mechanism...

Any thoughts?

**Comment by backbone87** [comment]
the thing is that the annotation parser used relies on the annotation classes and their properties to parse and validate the annotations.

**Comment by ro0NL** [comment]
Im not really aware of the internals right now, but to clearify my intentions.

The goal would be to have immutable constraint objects. The constructor already takes an array of options or a default option which would be compatible. Options as public properties can be kept BC with use of magic `__get` and `__set`, however options needs to be re-resolved then. Validators rely on `Constraint::getOption(s)`.

About annottations.. im not sure what problem you're describing, but as i see it a constraint annotation like `@Assert\Length(min=3)` should just resolve to `new Length(array('min' => 3));`, right?

**Comment by iltar** [comment]
@ro0NL To add some visualization, could you add some examples of what you mean? I think I understand what you're pointing at, but I'm not 100% sure.

**Comment by ro0NL** [comment]
Add a `OptionsAwareTrait` to the `OptionsResolver` component, to allow for specific and/or generic options classes, i.e.;

```php
class MyClassOptions {
    use OptionsAwareTrait;
    public function __construct(array $options = array()) {
        $this->setOptions($options);
    }
    public function getSomeOption() {
        return $this->getOption('some_option');
   }
}

$options = new MyClassOptions();
$options->getSomeOption();
```

That would be part 1;
- `OptionsAwareTrait` exposes `setOption(s)` and `getOption(s)`, `private/protected` by default.
- Concrete classes can override visibility if needed
- A `MagicOptionsAwareTrait` can be added that implements `__call` for generic purposes
 - Optionally enable `__get` and `__set`

An `OptionsAwareTrait` can perhaps be implemented into symfony at several places.

Part 2 would be integration for validator constraints, after that we can perhaps revise form types and other usecases.

So the constraint part..., I think we first need to decide if constraints _should_ be mutable or immutable. Imho it should be the latter. Writing constraint can be done like this;

```php
class SomeConstraint {
    use OptionsAwareTrait { getOption as public; getOptions as public; }
    private $someProp;
    public function __construct($options. $someProp = null) {
        if (is_array($options)) {
            $this->setOptions($options);
        } else {
            $this->setOption($this->getDefaultOption(), $options);
        }
        $this->someProp = $someProp;
    }
}
```
The tricky part for mutable objects (i.e. implementing a `setOption(s)`) method would require (re-)resolving the options array, and we need some sort of pattern the allow configuring the defaults (like `configureOptions` in form types), perhaps a abstract method on the trait. And how/where the `OptionsResolver` is initiated and passed to `configureOptions`.

Currently my local dev-environment is under construction (new laptop ordered) :'), but i like to work on a `OptionsAwareTrait` as a feature.
