### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by HappyJiJi** [symfony/symfony#18638]
Hi ,
This is an error occurred when executing the command: `php app/console doctrine:schema:update --force`

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
The service "fos_user.security.login_manager" has a dependency on a non-existent service 
"security.token_storage".
```

Please help me ! what should I do ??

**Comment by phansys** [comment]
@HappyJiJi, please use the [support channels](https://symfony.com/support).

**Comment by javiereguiluz** [comment]
@HappyJiJi in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support You'll find a lot of people willing to help you. Thanks!

**Comment by HappyJiJi** [comment]
Thanks !
