### ISSUE TITLE
[Console] TranslationDebugCommand: Problem with `instanceof Translator` Typecheck

### ISSUE THREAD

**Issue by coding-musicman** [symfony/symfony#18637]
I have defined messages for the languages `de` and fallback language `en`.

When I execute `console debug:translation de AppBundle` I only retrieve the informations to `de`, but no comparison to the fallback `en`, as shown in the manual.

A bit digging showed it's the test `if ($translator instanceof Translator)` in `function loadFallbackCatalogues` in [TranslationDebugCommand.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/TranslationDebugCommand.php#L298)

A dump of `$translator` shows it's an instance of `Symfony\Component\Translation\DataCollectorTranslator`.

When I remove the test, I get the desired output, a comparison between used and fallback language.

I'm using Symfony 3.

**Comment by xabbuh** [comment]
@coding-musicman How is that supposed to work? The command would then fail because the `DataCollectorTranslator` does not provide the `getFallbackLocales()` method, wouldn't it?

**Comment by coding-musicman** [comment]
@xabbuh I've looked into it. Here is what I get when I dump the RefelectionClass of `$translator':
```
  ReflectionClass {#684
  +name: "Symfony\Component\Translation\DataCollectorTranslator"
  implements: array:2 [
    0 => "Symfony\Component\Translation\TranslatorInterface"
    1 => "Symfony\Component\Translation\TranslatorBagInterface"
  ]
```
That's what you say. But it's definetely working.

And when I dump the container from `$translator = $this->getContainer()->get('translator');` I also get following inheritance tree:
```
"translation.extractor" => Symfony\Component\Translation\Extractor\ChainExtractor {#458
  -extractors: array:2 [
    "twig" => Symfony\Bridge\Twig\Translation\TwigExtractor {#460
      -twig: Twig_Environment {#464
           #extensions: array:29 [
              "translator" => Symfony\Bridge\Twig\Extension\TranslationExtension {#624
                -translator: Symfony\Component\Translation\DataCollectorTranslator {#641
                  -translator: `Symfony\Component\Translation\LoggingTranslator` {#642
                    -translator: Symfony\Bundle\FrameworkBundle\Translation\Translator {#643
```
My guess would be, the `DataCollectorTranslator` is just type casted!?

**Comment by xabbuh** [comment]
Ah well, the `DataCollectorLogger` implements the magic `__call()` method forwarding all unknown calls to the wrapped instance (the `LoggingTranslator` does the same). See #18690 for a fix.
