### ISSUE TITLE
Symfony adds "pattern" attribute to input even if validation groups prevents it

### ISSUE THREAD

**Issue by ktrzos** [symfony/symfony#18632]
I'm using [EasyAdminBundle](https://github.com/javiereguiluz/EasyAdminBundle) and Symfony 3.

I have this field from entity:

```php
    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\Length(min="10", groups={"xxxx"})
     */
    private $title;
```

and used form which is using only one validation group - `yyyy`. 

The problem is, even if validation group `xxxx` is not used, `pattern=".{10,}"` HTML5 attribute is added to `title` input field.

**Comment by dmaicher** [comment]
Indeed for the guessing there is no check for the validation group:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L222

But also thats not really possible to implement 100% I think as the validation group actually used on the form can be dynamically determined after the form is submitted. So at the moment of creating the view we don't necessarily know the validation group yet that will be used when the form is submitted.

Or am I missing something? :)

Can you manually override/define form fields with that Bundle? Did not check it yet.

**Comment by iltar** [comment]
I often have forms where more than half of the validation groups are determined based on the submitted data, so your point is correct there.

**Comment by ktrzos** [comment]
@dmaicher 

In this particular case I'm creating it with `FormBuilder` because `title` is in a collection:

```php
$builder->add('title', Type\TextType::class, ['required' => TRUE]);
$builder->add('content');
$builder->add('imageFile', VichImageType::class);
```

So the type of field is not guessed. I've set it to "text".
