### ISSUE TITLE
Where to store run time settings/config file

### ISSUE THREAD

**Issue by SDPrio** [symfony/symfony#18649]
Hi,

I am working on a Symfony 2 WebApp. One Bundle inside the app handles Payments using the `PayPal REST API`.

The API need to types of config data:

1. Data that never changes, like the **API Key** and **credentials** to the merchants PayPal account. This data is simply stored in a config file in `/AppPaymentBundle/Resources/config/paypal.yml`. This file is edited at **design time** and will **never change at run time**. 

2. Data that is **not known at design time**, but has to created **once at run time** and can than be re-used.  

An example for this **run time config data** would be the following:
To make a payment the user is redirected from my page to the PayPal page. To show the PayPal page in the users language, one has to submit a `ProfileID` together with the other user data to PayPal. This `ProfileID` points to a `Payment Experience Profile` that (beside other layout and design parameters) determines the frontend language. **These profiles have to be created for any locale at runtime**. Once a Profile for locale XY has been created, in can re-used. So, when a User whants to place an order, the following workflow is used:

- User enters his address data including his country XY on my page
- Check we already have a profile ID for country XY in our run time config data
- If not, query PayPal API (using the fixed credentials stored in the config data) to create a new profile for country XY. Store the key-value pair profileID/countryXY in the run time config file
- Load profileID for countryXY
- Create a new `Payment` object by querying the PayPal API (using the fixed credentials stored in the config data)
- Attach profileID to the `Payment` object 
- Redirect user to PayPal page to approve the payment ==> Locale from the profile is used to determin the frontend language.

**Where should I save this run time config data?**

The DB would be one option of course. However I am not sure if this is the right place. This is config data, no entity or user data. Additionally the Payment Bundle should be re-used in different project and it should be as independent as possible. I think a config file would the better solution here. 

Should be `/AppPaymentBundle/Resources/config/` used for this as well? Is this dir intended to be writeable at run time?

Thank you very much!

**Comment by javiereguiluz** [comment]
@SDPrio in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support You'll find lots of people willing to help you. Thanks!

---

By the way, a database look like the best option here, but maybe you want to also check out this bundle: https://github.com/opensky/OpenSkyRuntimeConfigBundle
