### ISSUE TITLE
ajax calls from different symfony application have wrong profiler url in web dev toolbar

### ISSUE THREAD

**Issue by pjordaan** [symfony/symfony#18641]
I'm in this situation: i have a main application for static content www.hostname.nl and a dynamic application webshop.hostname.nl. Both applications are on separate servers and both are different Symfony applications.

When I'm developing the toolbar is shown from www.hostname.nl. It shows the ajax calls from webshop.hostname.nl, but the profiler url in the overview is linked to www.hostname.nl as the url does not contain the hostname and scheme. This means I have to click the link and have to modify the hostname myself to see the profiler data.

I find it weird the ajax requests do not fill in the full profiler url as the profiler does send a header with the full url.

**Comment by stof** [comment]
Already fixed by https://github.com/symfony/symfony/pull/18562 which will be part of the next 2.7.x, 2.8.x and 3.0.x releases, so I'm closing this issue.
