### ISSUE TITLE
[Form][2.8] Improve upgrade guide for deprecated form type instance usage

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#18662]
Hey,

with 2.8 deprecating parsing `FormType` instances to the form builder, it'd be great to give users a hint how they can replace form types with constructor parameters.

Before:
```
$someVar = new SomeVar('acme');
$form = $this->createForm(new MyType($someVar), $entity);
```

After:
```
$form = $this->createForm(MyType::class. $entity, ['someVar' => $someVar]);
```

And in MyType:

```
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setRequired(['someVar']);
    $resolver->setAllowedType('someVar', '\App\Bundle\SomeVar'); 
}
```

I've used this in a couple of procjects as it always was a neat way to streamline form handling and [I'm not alone](http://stackoverflow.com/questions/34027711/passing-data-to-buildform-in-symfony-2-8-3-0).

Cheers
Matthias

**Comment by kcaporaso** [comment]
@althaus, how are you pulling your 'someVar', back out in 'MyType'?  I would suspect that it's in the $options of ``` buildForm(FormBuilderInterface $builder, array $options) ```, but it seems to be only what's defined in ``` configureOptions(OptionsResolver $resolver) ```.

example:
```
// in a controller
$form = $this->createForm(UserType::class, $user, [
                'loggedInUser' => 'the user',
            ]
        );

// in UserType
public function configureOptions(OptionsResolver $resolver)
{
        $resolver->setDefined('loggedInUser');
        $resolver->setRequired('loggedInUser');
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\User',
            'loggedInUser' => null,
        ]);
}

public function buildForm(FormBuilderInterface $builder, array $options)
{
        $this->loggedInUser = $options['loggedInUser'];
       ...
}    
```
One would expect $this->loggedInUser to be 'the user', right, seeing as how I pass it during the createForm() call in the controller?
Nope, it is null every time.  Any tips on what I might want to look at to see why the $options[] are never getting my 'loggedInUser' variable when I set it from the controller?
Regards,
Kevin
