### ISSUE TITLE
Doctrine & Symfony tight coupling

### ISSUE THREAD

**Issue by devckonem** [symfony/symfony#18665]
If you want to declare another AppKernel a more lightweight version that only uses Doctrine\Bundle\DoctrineBundle\DoctrineBundle(), along with others of my own, you must include Symfony\Bundle\FrameworkBundle\FrameworkBundle() because annotation reader is declared in FrameworkBundle() but the classes for the annotation reader are from Doctrine, and that is strange because the Symfony Framework IMHO should have its own implementation(that implies duplicate code in a way, but its independent). My question is why did you make this decision? I don't see how Symfony will work without Doctrine, and IMHO its a very tight coupling.

**Comment by fabpot** [comment]
Doctrine annotations is separate from Doctrine ORM. And DoctrineBundle is all about the Doctrine ORM. So, there is no coupling here. We are just using a library doing annotations parsing which happens to come from the Doctrine guys.

**Comment by devckonem** [comment]
Ok the hole process come from the fact that i want to write a more lightweight version of AppKernel for the use in a console application along with RabbitMQBundle and to reduce the memory footprint of consumers. So I started to cut piece by piece bundles I don't need and when it comes to FrameworkBundle() I can't seem to remove it because of this issue with the annotation reader. Do you have any suggestions regarding my problem? 

Also I understand what you said earlier and it was my mistake to draw some eager conclusions. But still you have to have Doctrine installed for the symfony app to work right?

**Comment by theofidry** [comment]
@devckonem you might want to check https://github.com/symfony/symfony/issues/15748. Also if you want the minimal version I recommend you to start with the empty edition instead of the standard one, will make your life easier.

**Comment by javiereguiluz** [comment]
@devckonem maybe you can checkout [Symfony Microkernel](http://symfony.com/blog/new-in-symfony-2-8-symfony-as-a-microframework) too.

**Comment by stof** [comment]
> So I started to cut piece by piece bundles I don't need and when it comes to FrameworkBundle() I can't seem to remove it because of this issue with the annotation reader. Do you have any suggestions regarding my problem?

Well, DoctrineBundle depends on FrameworkBundle. So you cannot remove FrameworkBundle if you want to enable DoctrineBundle
