### ISSUE TITLE
[DomCrawler] How to set isHtml to false ?

### ISSUE THREAD

**Issue by Staff-i** [symfony/symfony#18660]
Can you please add a setter for isHtml to DomCrawler ? Or give me the way to change isHtml to false.

**For example :**

``` php
    /**
     * Set isHtml
     *
     * @param boolean $bool
     *
     */
    public function setIsHtml($bool)
    {
        $this->isHtml = (bool) $bool;
    }
```

The filter() method use $converter->toXPath($selector) was referred a lowercase value if isHtml is true

The old solution CssSelector::disableHtmlExtension(); no longer exists, and there is no other way to change context.

Thank you in advance.

**Comment by stof** [comment]
This property is set when you create a Crawler from XML content rather than from HTML content. there is no need for a setter IMO. It would only allow to put the crawler in an inconsistent state

**Comment by Staff-i** [comment]
Okay, I have no choice, I should use the filterXPath() method if a node name contains uppercase string. Thanks

**Comment by stof** [comment]
Well, if it is HTML, node names should not be uppercase (according to the HTML spec). It is is XML, just import the content as XML and things will work

**Comment by Staff-i** [comment]
I think I'm import XML with :
> http://php.net/manual/en/domdocument.load.php
> DOMDocument::load ( string $filename [, int $options = 0 ] )
> "Loads an XML document from a file."

This is my code for import content as XML
``` php
$dom = new \DOMDocument();
$dom->load($xml_filename);
$this->crawler = new Crawler($dom);
```

Where is the problem ??? This approach is not appropriate  for import XML content in Crawler?

**Comment by stof** [comment]
but there, you are passing a DOMDocument to the crawler, so it cannot know whether it is XML or HTML. Just let the Crawler load the content itself into a DOMDocument, through the dedicated methods

**Comment by Staff-i** [comment]
Can you give an example ?

**Comment by Staff-i** [comment]
It's okay, I do like this :
``` php
$xml_content = file_get_contents($xml_filename);
$this->crawler = new Crawler();
$this->crawler->addXmlContent($xml_content);
```

Thank's for your help ;)

**Comment by javiereguiluz** [comment]
@Staff-i I'm glad you solved your issue. I'm closing it ... but if you want to keep discussing about it, feel free to reopen it. Thanks!

**Comment by Staff-i** [comment]
I think we need to update documentation "**The DomCrawler Component**" 
> http://symfony.com/doc/current/components/dom_crawler.html

This example is no longer valid ;)

``` php
use Symfony\Component\CssSelector\CssSelector;

CssSelector::disableHtmlExtension();
$crawler = $crawler->filter('default|entry media|group yt|aspectRatio');
```

**Comment by javiereguiluz** [comment]
I've opened https://github.com/symfony/symfony-docs/issues/6519 to track this issue un the docs repo. Thanks!
