### ISSUE TITLE
Generating Entities from Yml file 

### ISSUE THREAD

**Issue by roji430** [symfony/symfony#18668]
i am new to doctrine... created yml file with name XYZ.Model.User.dcm.yml inside my condig directory
and i run orm:generate-enities command to generate Entities in XYZ\Model\ directory but i got XYZ\Model\XYZ\Model\User.php instead of XYZ\Model\User.php

**Comment by iltar** [comment]
Duplicate of https://github.com/doctrine/doctrine2/issues/5803

Please open doctrine issues in the doctrine repository only
