### ISSUE TITLE
Issues when umask is disabled via disable_funtions

### ISSUE THREAD

**Issue by yannicmahe** [symfony/symfony#18672]
Hi,

I'm managing an internal hosting shared platform based on PHP.

In order to limit issues concerning files perms, we have disabled the following functions for hosted applications :
- chown
- chmod
- umask

Indeed, rights are handled by ACLs and most of the uses of the above functions were breaking rights.

The issue with Symfony is that, in this context, the way the "umask" function is used is triggering a PHP fatal error :
Fatal error: Unsupported operand types

This is because of the syntax "~umask()". Indeed the NOT operator can't be used on NULL.

In order to reproduce the issue, simply set "disable_functions=umask" in your PHP configuration.

This issue seems to affect at least the latest versions of Symfony (I haven't checked older versions).

I have to ask our customers willing to use Symfony to patch it in order to have their application work on our platform.

Maybe you could change the way "umask" is used so that it won't trigger any fatal error if not available.

Some possible ways to implement it :
- use a wrapper method that will return a default value if "umask" isn't available (id est if it's return value is NULL).
- use the syntax "~(umask() ?: <default value>)" to ensure the type for the "not"'s operand is supported.
- check if chmod, chown or umask are available before trying to use them, by reading the value of "disable_functions" (that method has more impact, but would avoid PHP Warnings as well).

You will find bellow the occurrence I found of this issue :
symfony/src/Symfony/Component/HttpFoundation/File/UploadedFile.php at line 230
symfony/src/Symfony/Component/HttpFoundation/File/File.php at line 101
symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php at line 234
symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmer.php at line 25
symfony/src/Symfony/Component/HttpKernel/HttpCache/Store.php at line 363
symfony/src/Symfony/Component/Filesystem/Filesystem.php at line 196

There is also an occurrence in Twig, but I guess this is not the right place for this lib.

Of course, it's up to you to determine whether this request is relevant or not.
I'm not using Symfony myself, so I won't complain !
I'm just filling this issue to help my customers willing to use Symfony (patching a framework is never a good idea if you want to be able to easily upgrade it).

Sincerely

**Comment by iltar** [comment]
Working in the hosting branch myself, I can advise to not use Symfony on shared hosting platforms. You can make it work with the limitations set, but in order to do so, need a lot of expertise of the issues at hand and of Symfony. Afaik symfony won't really function well without those functions mentioned as during container building and cache warm-up a lot of files are created.

*I know every hosting is different*

**Comment by yannicmahe** [comment]
In fact, everything works just fine without this functions.
The patchs I propose to my clients is really simple :
=> comment any "chmod" called by Symfony (they are of course linked to the umask calls), and because of the default file permissions handling on the platform, everything is just fine

**Comment by javiereguiluz** [comment]
This issue may be important for Symfony Flex (and Symfony 4) because we use `umask()` by default. We've opened https://github.com/symfony/recipes/issues/116 to discuss about that. Thanks!

**Comment by fabpot** [comment]
I would say that if such basic functions are disabled, it's the responsibility of the hosting provider to provide stubs that do nothing (can be done as a prepend script or something similar).
