### ISSUE TITLE
Doctrine is not fully available (proxies not generated) during Twig TemplateCacheWarmer run

### ISSUE THREAD

**Issue by dovys** [symfony/symfony#18673]
Hi,

we're experiencing issues with warming up twig caches, which require the csrf token storage, which requires a doctrine proxy.

Real life scenario: implementing a memcached version of the TokenStorageInterface and using an entity to determine if the experimentation for it is enabled or not

Reproduction case:
https://github.com/InterNations/cachewarmupbug
A patch to the standard 2.8.4 edition: https://github.com/InterNations/cachewarmupbug/commit/eac6d0d5a2663b60e68577d6a934388cb28466d6

```
php app/console cache:warmup --no-debug -v
```

```
// Warming up the cache for the dev environment with debug false
PHP Warning:  require(app/cache/dev/doctrine/orm/Proxies/__CG__AppBundleEntityTest.php): failed to open stream: No such file or directory in vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

Warning: require(app/cache/dev/doctrine/orm/Proxies/__CG__AppBundleEntityTest.php): failed to open stream: No such file or directory in vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
PHP Fatal error:  require(): Failed opening required 'app/cache/dev/doctrine/orm/Proxies/__CG__AppBundleEntityTest.php' (include_path='.:') in vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

Fatal error: require(): Failed opening required 'app/cache/dev/doctrine/orm/Proxies/__CG__AppBundleEntityTest.php' (include_path='.:') in vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
```

``` yml
# config.yml
doctrine:
    orm:
        auto_generate_proxy_classes: false
```

``` xml
# services.xml
<service id="security.csrf.token_storage" class="AppBundle\Security\Csrf\TokenStorage\DatabaseTokenStorage">
     <argument type="service" id="doctrine.orm.entity_manager" />
</service>
```

``` php
# DatabaseTokenStorage
class DatabaseTokenStorage implements TokenStorageInterface
{
    public function __construct(EntityManagerInterface $em)
    {
        $proxy = $em->getReference(Test::class, 123);
    }
```

The call chain is:
TemplateCacheWarmer -> getTwigService -> getCsrfTokenManager -> getDatabaseTokenStorage -> getEntityManager -> getEntityRepository -> Proxy of Test::class (which is not generated yet)

```
#0 src/AppBundle/Security/Csrf/TokenStorage/DatabaseTokenStorage.php(12): Doctrine\ORM\EntityManager->getReference('AppBundle\\Entit...', 123)
#1 app/cache/dev/appDevProjectContainer.php(1846): AppBundle\Security\Csrf\TokenStorage\DatabaseTokenStorage->__construct(Object(Doctrine\ORM\EntityManager))
#2 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevProjectContainer->getSecurity_Csrf_TokenStorageService()
#3 app/cache/dev/appDevProjectContainer.php(1833): Symfony\Component\DependencyInjection\Container->get('security.csrf.t...')
#4 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevProjectContainer->getSecurity_Csrf_TokenManagerService()
#5 app/cache/dev/appDevProjectContainer.php(2868): Symfony\Component\DependencyInjection\Container->get('security.csrf.t...', 2)
#6 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevProjectContainer->getTwigService()
#7 app/cache/dev/appDevProjectContainer.php(337): Symfony\Component\DependencyInjection\Container->get('twig')
#8 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevProjectContainer->getCacheWarmerService()
#9 vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheWarmupCommand.php(62): Symfony\Component\DependencyInjection\Container->get('cache_warmer')
#10 vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(259): Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(92): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 app/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#16 {main}
```

The cache warmers in the dumped container:

``` php
protected function getCacheWarmerService()
    {
        $a = $this->get('kernel');
        $b = $this->get('templating.filename_parser');

        $c = new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplateFinder($a, $b, ($this->targetDirs[2].'/Resources'));

        return $this->services['cache_warmer'] = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(array(
0 => new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplatePathsCacheWarmer($c, $this->get('templating.locator')),
1 => $this->get('kernel.class_cache.cache_warmer'),
2 => new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TranslationsCacheWarmer($this->get('translator')),
3 => new \Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer($this->get('router')), 
4 => new \Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer($this, $c, array()), 
5 => new \Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer($this->get('twig'), new \Symfony\Bundle\TwigBundle\TemplateIterator($a, $this->targetDirs[2], array())), 
6 => new \Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer($this->get('doctrine'))));
    }
```

There is a way to circumvent the issue by making the DatabaseTokenStorage service lazy, but my expectation is that Doctrine should be fully available to use once the container is built.

**Comment by iltar** [comment]
Just a wild guess, is the doctrine cache warmer triggered too late? https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php

**Comment by lstrojny** [comment]
That is indeed the root cause but in a slightly different way: the cache warmers are only executed after the container dumping thus leaving doctrine in an unusable state during container dumping and before the cache warmer is executed.

**Comment by iltar** [comment]
At the point of the container building, there are no initiated services yet, thus you cannot instantiate your configured EM because it's not done yet.

**Comment by lstrojny** [comment]
Sure you can do `$container->get(…)` and do something with the service. The thing is just that doctrine is in an unusable state with regards to proxies.

**Comment by stof** [comment]
@lstrojny no you cannot do it. You have strictly no guarantee that the service configuration is complete at that point, and so the service you retrieve could be totally broken (or even trigger a fatal error due to a broken instantiation). You should **never** get a service instance during the container building phase.

@symfony/deciders I suggest triggering a deprecation notice when retrieving an instance from a ContainerBuilder before it is compiled (and switching to an exception in 4.0). What do you think ?

**Comment by xabbuh** [comment]
@stof Good idea. I saw code failing several times because of the usage of `get()` in a compiler pass under certain circumstances only (which is frustrating to solve by the user).

**Comment by stof** [comment]
yeah, I never found a working use case for it, but I often saw broken usages

**Comment by javiereguiluz** [comment]
@stof I agree deprecating the use of `get()` inside compiler passes ... but the original question is about cache warmers and not compiler passes, right?

**Comment by stof** [comment]
note that ``auto_generate_proxy_classes: false`` is not the best value for production usage anymore. Recent versions of Doctrine support generating a proxy when it does not exist yet, but using the existing one otherwise (equivalent of the way Symfony builds its cache in prod, without checking existing cache for freshness). This works much better.

Btw, it wouls also be much better to avoid doing heavy Doctrine usage in the constructor of a class when using DI, as it makes instantiation heavy. ``$em->getReference`` is such heavy work as it requires loading all mapping and generating a proxy (on a side note, ``getReference`` should generally not be used, as it requires to be sure that the provided id exists in the database. Doctrine won't validate its existence when using this method, as it is precisely the purpose of the method)

**Comment by lstrojny** [comment]
@stof we are not actually using `$em->getReference()`, that’s just the reproduction example. Yes, we could use `Doctrine\Common\Proxy\AbstractProxyFactory::AUTOGENERATE_FILE_NOT_EXISTS` but that would add one `file_exists()` per proxy per request which, even with statcache, sounds like a bad idea. I guess what would be perfect is a scenario where the behavior is `AUTOGENERATE_FILE_NOT_EXISTS` while the container is dumping and `AUTOGENERATE_NEVER` after the caches are warmed.

**Comment by lstrojny** [comment]
@stof @symfony/deciders: deprecating `ContainerBuilder::get()` make a `ContainerBuilder` no longer a `ContainerInterface`. Separating the building from the usage could turn out to be a very nice thing but if that’s done a ContainerBuilder should no longer implement ContainerInterface but rather be it’s own thing.

**Comment by stof** [comment]
@lstrojny I'm not deprecating the method entirely. I'm deprecating the ability to call it *before compiling* the container

**Comment by lstrojny** [comment]
@stof are you sure it’s a good idea to make a methods behavior depending on the lifecycle of the SF app?

**Comment by jvasseur** [comment]
@lstrojny It's already the case, depending if the container is compiled or not, you could get a service configured differently (most probably badly configured if called before compiling the container).

**Comment by xabbuh** [comment]
@lstrojny Actually, it is already depending on it (see cases where the container builder crashes under certain circumstances when calling `get()` in a compiler pass).

**Comment by xabbuh** [comment]
I am closing here as this is not something we will be able to fix, but where you need to properly design your application (i.e. do not use `get()` before the container was compiled and also don't do heavy work especially related to Doctrine in the constructor).
