### ISSUE TITLE
Make LDAP component accept custom attributes so we can retrieve operational attributes

### ISSUE THREAD

**Issue by steve-todorov** [symfony/symfony#18678]
I was playing around with the LDAP component and I noticed that there is a problem in the code. 
To retrieve an operational attribute with plain php, one needs to pass the forth argument to `ldap_search`:

```php
$ds = ldap_connect( $ldaphost, $ldapport )
$dn="ou=People,o=companyName";
$filterUID = "(uid=$uid)";
$attributes = array('nsAccountLock', 'pwdAccountLockedTime', 'etc');
$result = ldap_search($ds, $dn, $filterUID, $attributes);
$entries = ldap_get_entries($ds, $result);
$lock= $entries[0]["pwdAccountLockedTime"][0]; // will return the attribute data from LDAP.
```

In the Symfony LDAP component, however, one can only pass a specific set of attributes listed in `Symfony\Component\Ldap\Adapter\AbstractQuery`. This limits the usability of the component. In my case, I had to use a third-party library or manually bind to LDAP and do a `ldap_search` so that I can check in my custom user provider that the user is not locked.

**Comment by iltar** [comment]
@steve-todorov This is in the master right now, I think it's a new feature: https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php

Would this be what you need?

**Comment by steve-todorov** [comment]
@iltar This is exactly what I needed! I'm providing a working example for anybody who might be interested (taken from [LdapUserProvider](https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L63)):

    $attributes = array('filter' => array('*', 'pwdAccountLockedTime'));
    $search = $this->ldap->query($this->baseDn, $query, $attributes);

This will retrieve all attributes as well as the operational attribute `pwdAccountLockedTime`.

By the way, I was quite confused when I looked at the `LdapUserProvider` source for the first time. The variables `searchDn` and `searchPassword` should probably be renamed to `bindDn` and `bindPassword` to follow the convention. At first I thought that `searchDn` is actually the `dn` you'll be searching for.

Anyway, I'm closing this as it's already implemented.
