### ISSUE TITLE
TypeTestCase has unused (and unusable) variables

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#18698]
$this->builder and $this->dispatcher of Symfony\Component\Form\Test\TypeTestCase are unused in symfony (Symfony\Component\Form\Tests). 

Most tests in Symfony\Component\Form\Tests could extend FormIntegrationTestCase instead of TypeTestCase because they only use $this->factory.
There are some tests which use a builder, but they build it themselves: `$builder = $this->factory->createXXXBuilder();` :
 * Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest
 * Symfony/Component/Form/Tests/Extension/Core/Type/BaseTypeTest

$this->builder is unusable because it does not allow to add() children. (calling buildForm() after raises an error.)

When I did not overlook any side effects, we can remove $builder, $dispatcher and setUp() form TypeTestCase without breaking anything. With the exception of assertDateTimeEquals() then TypeTestCase is the same as FormIntegrationTestCase, but does not break the [recommended unit testing for forms](http://symfony.com/doc/current/cookbook/form/unit_testing.html).

**Comment by xabbuh** [comment]
@SimonHeimberg Removing those properties would mean to break BC for users of this class who rely on their presence.

**Comment by javiereguiluz** [comment]
@xabbuh does the BC policy apply to tests too?

**Comment by WouterJ** [comment]
@javiereguiluz this is not the `Tests`, but the `Test` namespace. So it's part of the "public testing API" and I think we should apply the BC policy to this as well.

**Comment by javiereguiluz** [comment]
@WouterJ sorry, you are right!

**Comment by Tobion** [comment]
Doesn't this mean this issue can be closed?
