### ISSUE TITLE
[PropertyAccess][DX] Exception mention that some methods didn't exist although they did

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#18694]
With the simple case of 2 entities with a manyToMany relation. If we use a form field not multiple to set the relation, the PropertyAccess throw an exception : 

```
Neither the property "groupes" nor one of the methods "addGroup()"/"removeGroup()", 
"addGroupe()"/"removeGroupe()", "setGroupes()", "groupes()", "__set()" or "__call()" exist
and have public access in class "AppBundle\Entity\User"
```

But if we look at the Entity, the methods `addGroupe` and `removeGroupe` exists and are public.
The exception is raised because in the method `writeProperty` these too methods are used only if the value is an array or traversable witch is not the case if the form field is not multiple.

It would be more easy to debug this situation if we check the presence of the adder and remover methods. Then if this too methods exists the exception should point the fact that in this situation, the expected value is an array or a traversable instance.

**Comment by xabbuh** [comment]
@nykopol Isn't this simply related to the fact that you used the word groupe instead of group?

**Comment by nykopol** [comment]
@xabbuh no, my initial problem is that i have a manyToMany relation between User and Group, but in certain cases i don't allow users to be in multiple groups, so in this case i do a radio selector. As the radio return a single result instead of an array, the form require a transformer that transform the selected group into an array containing this group. 

My proposition concern the fact that without this transformer, the raised exception point an error about some missing properties although they exists. This is no easy to understand the root cause so i think that in this case the exception should indicate some thing like:

> You try to set the 'group' property on class %s. Although the methods `addGroup()` and `removeGroup()` have been detected, the given value must be an array or a traversable implementation. The input value type is : %s.

**Comment by rvanlaak** [comment]
`PropertyAccess` is looking for `addGroup` as the exception mentions, so what is the problem with renaming your `addGroupe` method to that? Don't think you need the transformer then.

**Comment by stof** [comment]
Well, not using the adders and removers when the field is not a collection makes totally sense, as adding and removing only make sense for a collection.
In your case, you should use a data transformer turning your selected group into an array in your form, before it is set in the model data (writing a model data transformer for that is very easy).

@xabbuh the exception message should avoid mentioning the adder and remover in cases where it does not expect them and so does not check for their existence
