### ISSUE TITLE
[Form][Guesser] Guess 'HTML attr constraints' even if the type is set ?

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#18706]
Having a constraint like this :

```php
    /**
     * @var string
     *
     * @ORM\Column(name="text", type="string", length=511)
     * @Assert\Length(min="12",max="511")
     */
    private $text;
```

And a formtype like this :
```php
        $builder
            ->add('text',TextAreaType::class);
```

My form is rendered so :
```html
<textarea id="text" name="text" required="required"></textarea>
```

Here it would be great to have that :
```html
<textarea id="text" name="text" required="required" maxlength="511" pattern=".{12,}"></textarea>
```

But the constraints are only added to the html form if I let symfony use the guesser for the type, like so :

```php
        $builder
            ->add('text');
```

Sadly, if I do it so, I receive a TextType and not a TextareaType.

**Comment by Alsatian67** [comment]
I just do another test :
```php
        $builder
            ->add('text',TextAreaType::class,array('constraints'=>array(new Regex('#^([a-z0-9_-]+\.)*[a-z0-9_-]+\.[a-z]{2,}$#i'))));
```

And here, the HTML constraints are also not guessed.

**Comment by Kyoushu** [comment]
I've been looking into doing this as well.

I was thinking of having an event subscriber inject attributes derived from constraints when FormTypeInterface::finishView()/buildView() is called, but events are only dispatched for data binding in forms.

The only other alternative I can think of is to pass the form view through a class which iterates over all children, adding attributes from constraint annotations in vars.data as it goes.

**Comment by rvanlaak** [comment]
So basically as I understand correctly you want the constraint to add attributes to the formbuilder? Because you can already do this by just adding these attributes. The `required` html5 attribute right now is the only exception that can be defined via the $options array directly (instead of `attr` which lives one level lower).

```php
$formBuilder->add('text', TextareaType::class, array(
    'attr' => array(
        'maxlength' => "511",
        'pattern' => ".{12,}",
    )
);
```
My guess would be that the scope of the constraint is outside of the scope of the form component, as they can be used separately. Had the same discussion about the `placeholder`, which also is in the `attr` array.

**Comment by stof** [comment]
> I was thinking of having an event subscriber inject attributes derived from constraints when FormTypeInterface::finishView()/buildView() is called, but events are only dispatched for data binding in forms.

what you need is a FormTypeExtension, not an event subscriber.

**Comment by Alsatian67** [comment]
@Kyoushu, @rvanlaak

I know how to do it myself. Thank you.

But since the HTML constraints are added automatically from entity constraints when the type is guessed. I'm wonder why this part of the guessing is not applied when I choose a formtype instead of an other.

And I am nearly sure it was so in an old version of symfony (may be when symfony was not able to guesse the type) ? (I started with SF 2.1).

-> So I don't know if I am requesting a Feature or a Bug correction.

**Comment by stof** [comment]
@Alsatian67 when you specify a form type explicitly, guessers are not applied at all (and this is true since Symfony 2.0)

**Comment by Alsatian67** [comment]
OK. Then I propose as **new feature**, to automatically transpose the constraints attached to a form, to the attr options. Event if the form type isn't set explicitly.

**Comment by stof** [comment]
@Alsatian67 this would be a BC break (applying guessers in places where they are not applied currently would change the options being used) and would have a perf impact (running guessers when not necessary).
So it cannot be applied all the time.

**Comment by Alsatian67** [comment]
OK. Thank you for your response.
