### ISSUE TITLE
BC Break with 2.8.5, some services used to be public and are now private

### ISSUE THREAD

**Issue by DHager** [symfony/symfony#18703]
## Symptom

Upgrading Composer package `symfony/symfony` from 2.8.4 to 2.8.5 broke our application with the message: 

>   [InvalidArgumentException]                                                                                                 
  The service "f0060f87044772964831885297651a58cbc94d84acb0738fee7c76412d631605_2" tagged "console.command" must be public.

## Cause

The underlying issue is that our commands were not tagged public, ex:

```xml
        <service class="My\CompanyBundle\Command\EnumerateSomeAnnotations">
            <argument type="service" id="annotation_reader"/>
            <argument type="service" id="router"/>
            <tag name="console.command" />
        </service>
```

I've tracked the trigger down to the change made in #18491 with commit 0a469a418f070e2f8cff498f7ab40f6633504a14 which changed the logic for making anonymous services private by default. 

Perhaps somebody could confirm that this is just old bug being fixed, rather than a new bug being introduced? 

## Solution (Workaround?)

Adding the attribute `public="true"` for our tagged commands seems to be the way forward. 

## Other potential symptoms

For the sake of people doing web-searches for error-messages, these other ones seem like they could pop up:

* The service "%s" must be public as form type extensions are lazy-loaded.
* The service "%s" must be public as form type guessers are lazy-loaded.
* A synthetic service ("%s") must be public.
* The service "%s" must be public as event listeners are lazy-loaded.
* The service "%s" must be public as event subscribers are lazy-loaded.
* The service "%s" must be public as fragment renderer are lazy-loaded.
* The service "%s" tagged "console.command" must be public.
* The service "%s" must be public as form types are lazy-loaded.

**Comment by stof** [comment]
Anonymous services were actually never intended to be allowed as top-level services AFAIK, but only inside arguments.
I was not even aware they were working as top-level services (and @xabbuh and @nicolas-grekas were probably not knowing it either when doing the change).

@symfony/deciders I suggest reverting this change. And then we can decide whether we want to keep this ability or no in the XML loader.

**Comment by fabpot** [comment]
It has indeed never been intended to work and I'm not sure we want to support them.

**Comment by xabbuh** [comment]
Indeed, I didn't expect it to work this way. However, I can see that people may use this for services that they don't refer to explicitly, but that are tagged to be used by some compiler passes (console commands, event listeners, form types and so on). So I think we should rather revert the changes, and deprecate this feature in 3.1 or 3.2.

**Comment by nicolas-grekas** [comment]
Meanwhile, I've learned that people do use anonymous top-level services to e.g. register event listeners.
I don't see the issue supporting this and in fact I've added a test case for it in https://github.com/symfony/symfony/commit/9802a41b3cdd90bc9a4e625d6043859153ce67de#diff-9a0c6740f8f574d9d270c6e2a7d5945cR21
Yet, I agree these services should be kept private...

**Comment by xabbuh** [comment]
@nicolas-grekas Having them `private` means that they cannot be lazily loaded like it is done by, for example, the `ContainerAwareEventDispatcher` class.

**Comment by stof** [comment]
> Yet, I agree these services should be kept private...

This does not work, as some tagged services are required to be public (event listeners for instance) as they are lazy-loaded rather than being injected directly.

**Comment by nicolas-grekas** [comment]
right, then lets revert and add a test to prevent any regression. I don't see the need for deprecating, do you?

**Comment by DHager** [comment]
@xabbuh @stof That sounds more like an issue with the lazy-loading mechanism, since ideally lazy-or-eager should be orthogonal from public-or-private.

For example, suppose you have a main service that takes a kind of request and dispatches it to one of 100 other little tagged services, and usually only 1 or 2 will be used in a single web-request. Obviously you'd want lazy-loading for those 100 services, right? But you probably don't want them to be public, since AFAIK that means you must: 

* Allow any other code to arbitrarily grab a reference to a sub-service
* Pick 100 unique names (or have ugly ones autogenerated)
* Tolerate 100 more entries into `debug:container` (or any other enumeration of public services)
