### ISSUE TITLE
bundle for business intelligence 

### ISSUE THREAD

**Issue by arijmachfar** [symfony/symfony#18707]
Hi,I want to add business intelligence to my project, is there any bundle or any language to work with ?

**Comment by javiereguiluz** [comment]
@arijmachfar in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

---

By the way, check out http://knpbundles.com
