### ISSUE TITLE
Bug with constraint attach to a field ( using @Assert\True() annotation )

### ISSUE THREAD

**Issue by AdriwanKenoby** [symfony/symfony#18700]
When I try to add a custom constraint for a specific field with a method, the return statement is always false.

The same method use to verify form globaly works nice.

This method was named isUrl() in my case and verify if an url is online ( i check the header code with a curl request ).

I thought it was because i use the specific word "url" which could be use in otherway. But even if I change  "url" in "path". I have the same issue.

**Comment by xabbuh** [comment]
@AdriwanKenoby Can you fork the Symfony Standard Edition and make the changes that are needed to reproduce your issue?

**Comment by AdriwanKenoby** [comment]
I think its a symfony bug but it can be an Oro platform issue.

My code is available on [http://gitlab.sinabs.ovh/orocrm-projects/sinabs-orocrm.git](url)

**Comment by xabbuh** [comment]
@AdriwanKenoby Sorry, but we cannot check your whole project. Stripping it down to a minimal set of changes to reproduce your issue or providing a failing test case is the only way I see to help you with your issue.

**Comment by jakzal** [comment]
@AdriwanKenoby any chance to get what xabbuh's asking for please?

**Comment by AdriwanKenoby** [comment]
@xabbuh 

Sorry for the time, i have found a workaround to my problem, i write a custom validator and declare it as a service, then i use callbak annotation to validate my field. My code is no longer public on gitlab, so I build a minimal project symfony with the bug i had found, i attach it to this message.

Their is an entity named Test with a field named url. The method named isUrl return always false, even if it should return true. If i named this method isTestValid, it works.
[test.tar.gz](https://github.com/symfony/symfony/files/336696/test.tar.gz)

**Comment by jzawadzki** [comment]
I just tried to replicate that issue and I can confirm it, however I'm not sure if it can be easily fixed.

Issue here is when there is an entity validated that have both `getter` and `isser` of same form field - in that situation constraints are taken from both methods, but their are validated againts value of getter.

In @AdriwanKenoby example there was form field `url` based on entity `Test` which had `getUrl()` method and `isUrl()` method with `IsTrue` assert put on it. 
In that situation `IsTrue` constraint is validated against value of `getUrl()` instead against value of `isUrl()`

Here you can find forked symfony-standard showing the issue: https://github.com/jzawadzki/symfony-standard/commit/ec00a7b2938c4ab02a91ab943d37c6af9c768e20

**Comment by xabbuh** [comment]
Thank you @AdriwanKenoby for the bug report and thank you very much @jzawadzki for investing the time into find out what went wrong. I was now able to reproduce the issue and create a patch for it in 21115. Can you please try it out and confirm that that PR fixes your issue?

**Comment by fabpot** [comment]
@AdriwanKenoby Can you confirm that @xabbuh's PR fixes your issue?
