### ISSUE TITLE
symfony2.8 console terminting with PHP Catchable fatal error

### ISSUE THREAD

**Issue by Raffaello** [symfony/symfony#18720]
Hi,
i have this error reported when I am loading a bundle:
`PHP Catchable fatal error:  Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in /ssd/xxx/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 389
`

if i don't load that bundle no error reported.
it seems symfony doesn't recognize some misconfiguration/error in the bundle itself.
could it be the case?

thanks

**Comment by Raffaello** [comment]
```
PHP Catchable fatal error:  Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in /var/www/gqm.vm/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 389
PHP Stack trace:
PHP   1. {main}() /var/www/gqm.vm/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/gqm.vm/bin/console:29
PHP   3. Symfony\Component\Debug\ErrorHandler->handleError() /var/www/gqm.vm/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0

Catchable fatal error: Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in /var/www/gqm.vm/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 389

Call Stack:
    0.0006     229736   1. {main}() /var/www/gqm.vm/bin/console:0
    0.0974    2935080   2. Symfony\Component\Console\Application->run() /var/www/gqm.vm/bin/console:29
    3.6687   36427976   3. Symfony\Component\Debug\ErrorHandler->handleError() /var/www/gqm.vm/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0
```

**Comment by Raffaello** [comment]
Ok find the issue.
it was a __destructor issue
(protected and not public)

thanks.

**Comment by numediaweb** [comment]
@Raffaello Could you please show how did you fix it as I'm also facing this issue when I run a command in the bin/console

**Comment by Raffaello** [comment]
@numediaweb at that time i was working on a custom bundle dealing with some async computation. My issues was that I declared erroneously a destructor in a class protected and symfony Debug\ErrorHandler was not able to access/ destroy the object: that was the error reported.

so for instance in my class, I declared `public function __destructor()`. But I think it is quite a specific case to use __destructors.. 

BTW seems Symfony (dev env /w debug) doesn't support them completely.

**Comment by Wirone** [comment]
I have this error when I register plugin into SwiftMailer and that plugin appends sent message to `Sent Items` folder through IMAP, which results with `[CLOSED] IMAP connection broken (server response) (errflg=2)`.

```
Fatal error: Uncaught TypeError: Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php:391
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Unknown: [CLOSE...', 'Unknown', 0, NULL)
#1 {main}
  thrown in vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php on line 391
Segmentation fault
```

PHP 7.0.12

**Comment by numediaweb** [comment]
In my case the problem was with a `Webeith\ImapBundle` bundle that I used which tries to talk to a windows mail server and results back on the error, so I had to just force imap to use the DISABLE_AUTHENTICATOR - Disable authentication properties:
```
$imapStream = imap_open(
            '{'.$this->container->getParameter('mailer_host').'}INBOX',
            $this->container->getParameter('mailer_user'),
            $this->container->getParameter('mailer_password'),
            0,
            0,
            array('DISABLE_AUTHENTICATOR' => 'GSSAPI')
        );
```

**Comment by Wirone** [comment]
Yeah, I ended up with this and with `/novalidate-cert` modifier in IMAP path. But I'm wondering if it could be catched somehow and not end with segmentation fault :-)
