### ISSUE TITLE
StringUtil::singularify converts screenshot to scroonshot

### ISSUE THREAD

**Issue by TakTaki** [symfony/symfony#18748]
Hello,

I've encountered an interesting error while creating my form.
I have a collection of 'screenshot' in it, and when I submit a valid form, I have an alert saying that there's no function addScroonshot declared.

I've done a little research and I think the problem might come from StringUtil::singularify function which contains at the end: 
```php
// Convert teeth to tooth, feet to foot
if (false !== ($pos = strpos($plural, 'ee')) && strlen($plural) > 3 && 'feedback' !== $plural) {
    return substr_replace($plural, 'oo', $pos, 2);
}
```

Maybe I'm just wrong, and I'll appreciate your help!

Thanks!

**Comment by peterrehm** [comment]
I just added a solution to convert screenshots. Please note that this will only work if you have a collection of `screenshots`
