### ISSUE TITLE
[PhpUnitBridge] Detect legacy test

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18755]
[From the doc](https://symfony.com/doc/current/components/phpunit_bridge.html#mark-tests-as-legacy):

> There are four ways to mark a test as legacy:
> - (Recommended) Add the @group legacy annotation to its class or method;
> - Make its class name start with the Legacy prefix;
> - Make its method name start with testLegacy instead of test;
> - Make its data provider start with provideLegacy or getLegacy.

So for marking a test method as legacy, we add the `Legacy` part which results `testLegacy`. However PHPUnit test methods can also me snake case, i.e. `test_legacy` should also work (that is not the case).

**Comment by stof** [comment]
My recommendation would be to use the group for that rather than adding yet another supporting convention

**Comment by theofidry** [comment]
I would agree if it was a brand new convention, but as it's been supported by PhpUnit for a long time already [having snake case test methods], so it's just a bit weird to not align with it.

**Comment by stof** [comment]
I'm talking about naming conventions supported by the bridge, not by PHPUnit (PHPUnit only cares about beginning by ``test``, which does not care about snake case vs camel case).
And btw, this is also why using the group is the recommended way

**Comment by theofidry** [comment]
>(PHPUnit only cares about beginning by test, which does not care about snake case vs camel case).

Point is, `testSomething()` and `test_something()` both works. So if PhpUnitBridge supports `testLegacySomething()`, looks weird not to support `test_legacy_something()` regardless of what the recommended way is.

That being said, I don't feels strongly about this, it's just something I noticed and wanted to raise.

**Comment by stof** [comment]
@theofidry if the component was written today from scratch, ``testLegacy`` would not be supported at all to mark the test as legacy. It is already a BC layer...

**Comment by theofidry** [comment]
Fair then. Do you want to close the issue or maybe someone else has a word to say?

**Comment by xabbuh** [comment]
I agree with @stof. Using the `@group` annotation is the way to go and we should possibly think about deprecating the other ways.

**Comment by theofidry** [comment]
I'm fine with it. I'm letting this ticket open as a reminder to deprecate the other ways then :)

**Comment by stof** [comment]
@xabbuh triggering deprecations in the deprecation reporter is likely to become funny :smile:

**Comment by xabbuh** [comment]
> Make its data provider start with provideLegacy or getLegacy.

Are we in fact sure that the error handler is working this way? I think naming your data provider this way, the only effect is that deprecations triggered during the data provider call are silenced.

ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
>  deprecations triggered during the data provider call are silenced

true, so maybe we can't remove this convention if annotations can't be read on them?
