### ISSUE TITLE
[DOMCrawler]  ->text() method should return all sub elements text, not just first one.

### ISSUE THREAD

**Issue by motammem** [symfony/symfony#18754]
```php
    public function text()
    {
        if (!$this->nodes) {
            throw new \InvalidArgumentException('The current node list is empty.');
        }

        return $this->getNode(0)->nodeValue;
    }
```

code above should change to match expectations.

**Comment by stof** [comment]
The current code matches exactly what is described in the phpdoc.

Changing this is a BC break and so cannot be done. Thus, it would make it inconsistent with other getter methods (which simply cannot read from multiple elements)

On a side node, for people comparing this to the jquery API, it works the same. Any accessor also reads only from the first node.

**Comment by javiereguiluz** [comment]
I'm closing this because of the reasons mentioned by @stof (it'd be a BC break and it wouldn't respect jQuery API).

@motammem this time your proposal didn't make it ... but please keep sharing your ideas to improve Symfony. Thanks!
