### ISSUE TITLE
Microseconds in Stopwatch Component

### ISSUE THREAD

**Issue by danger89** [symfony/symfony#18756]
Hi,

In the [Stopwatch component](http://symfony.com/doc/current/components/stopwatch.html) I only can get the **duration** in _milliseconds_. So in my case I get 0ms, but in reality SOME time passes. I would like to have _microseconds_ precision.

Thanks!

Kind regards,
Melroy van den Berg

**Comment by nicolas-grekas** [comment]
AFAIK, php doesn't provide any way to get sub-millisecond timing measurements...

**Comment by danger89** [comment]
Ok, in that case.. sub-milliseconds (== microseconds). I will update the title.

**Comment by stof** [comment]
@danger89 multiplying by 1000 is to get a number of milliseconds rather than a number of seconds (where 1ms would be 0.001).

the actual issue is the line https://github.com/symfony/stopwatch/blob/4670f122fa32a4900003a6802f6b8575f3f0b17e/StopwatchEvent.php#L235 which will round the value to 1 decimal, meaning that the shorted time being displayed will be 0.1ms. anything shorter than 0.05ms will be formatted as being 0ms.
We would need to allow keeping more decimals when the value is smaller than 1ms IMO

**Comment by javiereguiluz** [comment]
I agree with increasing decimals to display `0.X ms` ... but not `0.XY ms`

**Comment by stof** [comment]
@javiereguiluz we already display 1 decimal. and note that I'm suggesting to display more decimals only for times < 1ms (i.e times likely to be rounded as 0ms today, and for which 1 decimal means displaying only 1 significant number too).

**Comment by danger89** [comment]
Let's give a real example, I tried to measure the 2nd query (first query showed 12ms in doctrine dbal). The second query time showed 0ms.. I didn't trust the Symfony doctrine profiler.. But 0ms also didn't help me at all...

**Comment by danger89** [comment]
Ps. I also get a integer back from stopwatch interface, and and no double. This is the second bug why I get 0ms..

**Comment by flip111** [comment]
@danger89 there are also a few extensions out there which will give you more precision then php has out-of-the-box

https://pecl.php.net/package/hrtime
https://github.com/metaloha/phpTimer

Perhaps it's possible for you to sub-class `StopwatchEvent` and override some methods.

**Comment by patrick-mcdougle** [comment]
I guess I agree that the stopwatch should use times as granular as possible, and formatting should be up to the presentational level code (debug toolbar). That being said, I think that feature would need to be targeted for 4.0 because changing to microseconds would be a BC break.

**Comment by patrick-mcdougle** [comment]
@danger89 Are you sure that your query result wasn't being cached the second time through, resulting in a 0ms time?

**Comment by robfrawley** [comment]
@patrick-mcdougle How is displaying additional precision (providing a *more* precise result) a BC break? That doesn't make sense.

**Comment by danger89** [comment]
@patrick-mcdougle it could be cashed indeed, but a query will stake some time. Meaning I like to see micro second instead of milli seconds precision.

**Comment by stof** [comment]
> it could be cashed indeed

@danger89 this is a funny sentence when you use the wrong verb :smile:

@patrick-mcdougle there is no reason to change the return value to be microseconds. The return value is already a float, so we could just return a flat with more decimals in some cases.

**Comment by danger89** [comment]
Oops cached

**Comment by javiereguiluz** [comment]
Closing it as fixed by #23223.
