### ISSUE TITLE
NumberFormatter: Page referenced on iso.org no longer exists

### ISSUE THREAD

**Issue by darrylhein** [symfony/symfony#18758]
The link to iso.org in the comments for `Symfony\Component\Intl\NumberFormatter\NumberFormatter::formatCurrency()` no longer works.

The link is currently: http://www.iso.org/iso/support/faqs/faqs_widely_used_standards/widely_used_standards_other/currency_codes/currency_codes_list-1.htm which is not found. It seems that iso.org has moved to a for-pay standard (see https://en.wikipedia.org/wiki/Talk:ISO_4217#External_Link_to_.22Official.22_free_standard_now_a_For-Pay_Standard).

Based on the Wikipedia article (https://en.wikipedia.org/wiki/ISO_4217) it seems that this might be the best place http://www.currency-iso.org/en/home/tables/table-a1.html though I'm not sure.

**Comment by javiereguiluz** [comment]
@darrylhein very nice catch! Thank you.

What if we just link to the Wikipedia article you provided: https://en.wikipedia.org/wiki/ISO_4217 ? It looks like it already contains the list of codes.

**Comment by darrylhein** [comment]
@javiereguiluz That would work too...I just never scrolled down the page.

**Comment by xabbuh** [comment]
@darrylhein The link could point to https://en.wikipedia.org/wiki/ISO_4217#Active_codes.

**Comment by javiereguiluz** [comment]
Fixed in #18770.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #18770.
