### ISSUE TITLE
ConsoleHandler never outputs anything if output->getVerbosity() == VERBOSITY_QUIET

### ISSUE THREAD

**Issue by multi-io** [symfony/symfony#18767]
https://github.com/symfony/symfony/blob/v3.0.6/src/Symfony/Bridge/Monolog/Handler/ConsoleHandler.php#L175

That seems wrong. An Output configured as VERBOSITY_QUIET (which is triggered e.g. by running a console command with -q) doesn't mean that nothing should be printed, just very little. E.g. unhandled console command exceptions get reported under VERBOSITY_QUIET. The ConsoleHandler is apparently hard-coded to never output anything to such an output, even though its behaviour is otherwise supposed to be configurable via the verbosityLevelMap parameter.

**Comment by javiereguiluz** [comment]
@multi-io in my opinion the `quiet` option behavior is the expected one. To me `quiet` means: *"display nothing ... unless there is an error"*. The behavior you describe (*"display some, but not much, information"*) is the default one, when you don't change the verbosity level.

**Comment by multi-io** [comment]
@javiereguiluz my point was that ConsoleHandler will absolutely never output anything, not even errors or emergencies, onto to an Output configured as VERBOSITY_QUIET.
