### ISSUE TITLE
[suggestion] add attr chainable accessor to FormView

### ISSUE THREAD

**Issue by quazardous** [symfony/symfony#18777]
It's an humble suggestion, feel free to discuss.

As it adding class attributes to form inputs is like this:

``` twig

{{ form_widget(form.name, {'attr': {'class': 'foo'}}) }}

```

and if you wanted to keep some PHP coded class it's even harder because as it it's just replaced...

so I've quickly done a bad trick in FormView:

``` php
class FormView
{
...
    public function add($attr, $attrName = 'class')
    {
        if (is_array($attr)) {
            $attr = implode(' ', $attr);
        }
        if (empty($this->vars['attr'][$attrName])) {
            $this->vars['attr'][$attrName] = '';
        };
        $this->vars['attr'][$attrName] = trim($this->vars['attr'][$attrName] . ' ' . $attr);
        return $this;
    }

    public function set($attr, $attrName = 'class')
    {
        unset($this->vars['attr'][$attrName]);
        return $this->add($attr, $attrName);
    }
...
}
```

now you can nicely add class attributes:

``` twig
...
{{ form_widget(form.name.add('foo').set('my-name', 'id')) }}
...
```

The implementation is still ugly and the method name could be better but I hope you get the idea...

So what do you think ?

EDIT:
After a while the current tweaked FormView is:

``` php
class FormView extends BaseFormView
{
    public function setAttr($attrName, $attr, $append = true)
    {
        if (is_array($attr)) {
            $attr = implode(' ', $attr);
        }
        if (empty($this->vars['attr'][$attrName]) || !$append) {
            $this->vars['attr'][$attrName] = '';
        };
        $this->vars['attr'][$attrName] = trim($this->vars['attr'][$attrName] . ' ' . $attr);
        return $this;
    }

   // bad trick for twig
    public function isClass($class)
    {
        return $this->setAttr('class', $class);
    }

    public function addClass($class)
    {
        return $this->setAttr('class', $class);
    }

    public function addAttr($attrName, $attr)
    {
        return $this->setAttr($attrName, $attr);
    }

    // bad trick for twig
    public function isAttr($attrName, $attr)
    {
        return $this->setAttr($attrName, $attr);
    }

}
```

and in templates:

``` twig
...
{{ form_widget(form.name.class('foo').attr('bar', 'baz')) }}
...
```

**Comment by ro0NL** [comment]
I think the `attr` variable _could_ deserve some special value object. i.e. something like `AttributeBag` (like other bags such as `ParameterBag`).

The `AttributeBag` could have some utility methods for common attributes, i.e. `$view->vars['attr']->addClass('foo');`.

**Comment by quazardous** [comment]
yeah but this way it s no more chainable around the form input element...

**Comment by ro0NL** [comment]
Agree.. but i dont think we should pollute the `FormView` class with all sort of methods for all sort of vars and/or attributes.

I  also think you shouldn't play around much with the form view instance from within twig. I.e. prepare the view correctly backend :/

Otherwise.. 
```
{% form.name.vars.attr.addClass('foo') %}
{{ form_widget(form.name) }}
```
is just as good as your one-liner, imho. Maybe even cleaner...

**Comment by quazardous** [comment]
yeah sure ;p
in fact i've spotted this chainable fashion in D8 ;p

if the attribute bag is recursive we could have:
```
{% form.name.vars.attr.class.add('foo') %}
{{ form_widget(form.name) }}
```

**Comment by ro0NL** [comment]
> yeah sure ;p

Sarcasm? :p 

Not sure how you see a _recursive attribute bag_... imho only specific attributes (e.g. `class`) require special utilitiy methods like `add` and stuff. It can be applied to each attribute (as it's just string/value manipulation) but imho that would be over-engineering things.

**Comment by quazardous** [comment]
no I agree with you ;p
and I have no real opinion on the implementation

I just find very complicated the actual way to add a class...
(it's just a copy/paste from my widget_attributes block but it's the same logic)
```twig
        {% set _class = 'has-error' %}
        {% if attr.class is defined %}
           {% set _class = _class ~ ' ' ~ attr.class|trim %}
        {% endif %}
        {% set attr = attr|merge({'class': _class}) %}
```

maybe we just need some twig filter to merge a deep key in an array like deepAdd(path, value) ?

**Comment by ro0NL** [comment]
You could propose a deep-merge thingy at the twig library, but from a Symfony point-of-view i kinda like the `AttributeBag` idea. But im not sure we really, really need it :) Some API methods i can think of (besides from the standard collection methods like `all()`);

- `class` attribute: `addClass()`, `toggleClass()`, `removeClass()`, `hasClass()`
- `id` atttribute: `identify()` (i.e. set auto-generated ID if not set previously)
- `__toString()`
- ...?

**Comment by xabbuh** [comment]
Since this issue is quite old and didn't get much traction I guess we can safely assume that there isn't much interest from other developers. Let's close here.
