### ISSUE TITLE
[UX] frameworkbundle console should not run in debug on prod installs

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony#18778]
This is a usability problem. 

If you try to run a `php bin/console` from any production install symfony distribution or the symfony frameworkbundle, you will get a `Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /yourproject/app/AppKernel.php`.

That is because by default the console runs in debug mode, so you have to `--env=prod` on every single command you write. I shouldn't have to do this if I didn't even install the dev dependencies from composer (where the generator bundle is by default).

At the very least it could intercept this particular error (which will occur with a default composer.json from the distribution) and tell me that I need to run my command with `--env=prod`, then give me the error as normal in case that isn't the case.

But best case would be it should works without `--env`, perhaps warning me that dev commands are not available because they were not installed.

~ imo any error that is not easily understood should be treated as a bug

**Comment by iltar** [comment]
This is not a bug in symfony itself, but I would consider the dev-dependency in composer an issue. If the code has be runnable in --env=dev, it should still be a require and not a require-dev. I think you should open this issue in https://github.com/symfony/symfony-standard/

**Comment by ofbeaton** [comment]
Done. https://github.com/symfony/symfony-standard/issues/975

For some reason I was under the impression that all issues were to be raised in symfony/symfony, but I guess symfony-standard is special (or not like components).

**Comment by Pierstoval** [comment]
@ofbeaton `symfony/symfony` is the framework, with all its components.
The console you are using in your Symfony app comes from the Standard Edition, which is basically a _"Pre-configured working app using the Symfony framework"_
