### ISSUE TITLE
Install with composer in  symfony 2.8

### ISSUE THREAD

**Issue by zhilevan** [symfony/symfony#18782]
I try composer require symfony/console but I faced with :

Using version ^3.0 for symfony/console
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/orm v2.4.8 requires symfony/console ~2.0 -> no matching package found.
    - doctrine/orm v2.4.8 requires symfony/console ~2.0 -> no matching package found.
    - doctrine/orm v2.4.8 requires symfony/console ~2.0 -> no matching package found.
    - Installation request for doctrine/orm == 2.4.8.0 -> satisfiable by doctrine/orm[v2.4.8].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
how can I resolve it?

**Comment by Czarnolecki** [comment]
try with doctrine v2.5, composer for version 2.4 requires sf2.

take a look:
2.5: https://github.com/doctrine/doctrine2/blob/2.5/composer.json#L23
2.4: https://github.com/doctrine/doctrine2/blob/2.4/composer.json#L19

**Comment by zhilevan** [comment]
Thank you for attention and reply, I didn't understand what I should do, please provide more details.
I try to install it in  command line with  : composer require symfony/console

**Comment by Tobion** [comment]
Some where you require doctrine 2.4 (either implicitly or explicitly). You should try to depend on doctrine 2.5 instead.

I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by zhilevan** [comment]
Thank you,I got it.
