### ISSUE TITLE
Extend doctrine ORM definitions (between bundles)

### ISSUE THREAD

**Issue by sourcerer-mike** [symfony/symfony#18789]
Hello. With doctrine you give the option to define the ORM / Entities via XML within every bundle.
The shell `bin/console doctrine:generate:entities` creates those entities and is also capable of creating the DB schema. 

But there is a scenario, that doctrine / symfony does not handle yet. Imagine SecondBundle extending the entities of the MainBundle. The MainBundle could have something like this:

```
<?xml version="1.0" encoding="UTF-8" ?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">

    <entity name="App\MainBundle\Entity\Foo1405" table="foo1405">
        <id name="id" type="integer">
            <generator strategy="AUTO" />
        </id>
        <field name="name" type="string" length="100" />
    </entity>
</doctrine-mapping>
```

And the SecondBundle adds functionality and structure:

```
<?xml version="1.0" encoding="UTF-8" ?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">

    <entity name="Crmp\SecondBundle\Entity\Bar1405" table="bar1405">
        <id name="id" type="integer">
            <generator strategy="AUTO"/>
        </id>
        <field name="name" type="string" length="100"/>
        <field name="customer" type="id" />

        <many-to-one target-entity="Crmp\CrmBundle\Entity\Foo1405" field="foos" />
    </entity>

    <entity name="Crmp\CrmBundle\Entity\Foo1405">
        <one-to-many target-entity="Crmp\AcquisitionBundle\Entity\Bar1405"
                     mapped-by="customer"
                    field="customer">
        </one-to-many>
    </entity>
</doctrine-mapping>
```

It would be useful it symfony merges those two definitions. So that the command

    bin/console doctrine:generate:entities MainBundle

Not only uses the first XML but also takes note of the second bundle or other way round (might be better). The SecondBundle updates the entities in the MainBundle.

Symfony is a great framework to create own apps. It's only and last flaw is, that it does not allow plugins for this app. You always have to create your own plugin architecture. With the solution above Symfony will take that pain away and be a full stack framework, delivering a solution for plugins via just using bundles. KISS!

**Comment by xabbuh** [comment]
Thanks for this proposal @sourcerer-mike. However, I still need to close here as the Doctrine code is not maintained by the Symfony maintainers, but they have [their own organisation on GitHub](https://github.com/doctrine/). Please use their issue trackers to ask for new features in Doctrine. Thank you for understanding.

**Comment by sourcerer-mike** [comment]
Hello @xabbuh . Is the command `bin/console doctrine:generate:entities` maintained by Doctrine?
This is the one that can solve the "problem".

**Comment by xabbuh** [comment]
This command is part of the Doctrine package and is wrapped by the DoctrineBundle.
