### ISSUE TITLE
Symfony 2.7.7 form render issue

### ISSUE THREAD

**Issue by dancostinel** [symfony/symfony#18786]
I have the following controller class:

    <?php

    namespace AppBundle\Controller;

    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Symfony\Component\HttpFoundation\Request;

    class DefaultController extends Controller
    {
        /**
         * @Route("/process", name="appbundle_display_route")
         * @Method("GET")
         */
        public function displayAction()
        {
            $form = $this->createFormAction();
            return $this->render('AppBundle:Default:display.html.twig', ['form'=>$form->createView()]);
        }

        /**
         * @Route("/process", name="appbundle_process_route")
         * @Method("POST")
         */
        public function processAction(Request $request)
        {
            $form = $this->createFormAction();
            $data = $form->handleRequest($request)->getData();
            return $this->render('AppBundle:Default:process.html.twig', ['name'=>$data['name'], 'age'=>$data['age']]);
        }

        private function createFormAction()
        {
            $form = $this->createFormBuilder()
                ->setAction($this->generateUrl('appbundle_process_route'))
                ->setMethod('POST')
                ->add('name', 'text')
                ->add('age', 'integer')
                ->add('Go', 'submit')
                ->getForm();
            return $form;
        }
    }

And the following two simple templates:

    # AppBundle/Resources/views/Default/display.html.twig
    {% extends '::base.html.twig' %}

    {% block body %}
        {{ form_start(form) }}
            {{ form_rest(form) }}
        {{ form_end(form) }}
    {% endblock %}

    # AppBundle/Resources/views/Default/process.html.twig
    {% extends '::base.html.twig' %}

    {% block body %}
        {{ name }}<br>
        {{ age }}<br>
    {% endblock %}

Problem: When I try to access for the first time the `/process` route (on `GET`), the form isn't rendered, only a blank webpage is displayed instead. 

I tried to put `@Method({"GET"})` [with `{}`], still didn't rendered the form. Tried even to remove `@Method` annotation, and instead use `@Route("/process", name="appbundle_display_route", requirements={"_method"="GET"})`, still didn't rendered the form. The third way I knew, was to declare the routes in a .yml file and then import that file in the main `app/config/routing.yml`, as:

    appbundle_display_route:
        path: /process
        defaults: { _controller: AppBundle:Default:display }
        methods: [GET]

Still didn't worked as expected.

OBS: Then, I tested the same code (ok, not the same, instead of `'text'`, I used `TextType::class` and so on, for all Symfony versions 2.8.* and greater), in other Symfony versions: 2.7.6, 2.7.13, 2.8.3, 3.0.4, and all of them rendered, correctly, the form.

QUESTION: Is this a bug?

Thanks for your time!

**Comment by xabbuh** [comment]
If it works with 2.7.13 (which is a patch version that was released after 2.7.7) and it also works with the latest releases of 2.8 and 3.0, I don't see what we can do here other then suggesting you to update to the latest patch version of the minor version you use. Thus I am closing here. Please feel free to comment if you think there's still something we could do.

**Comment by dancostinel** [comment]
This was/is a simple project for learning purposes, and I can easily migrate from 2.7.7 to any other version, but what if someone has a real project in 2.7.7...?

**Comment by xabbuh** [comment]
They would have to update to another 2.7.x version anyway as bug fixes are always part of new patch releases.

**Comment by dancostinel** [comment]
Ok, I got it! Thank you!
