### ISSUE TITLE
[Yaml] Warn of unquoted strings

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18787]
[According to the YAML component doc](http://symfony.com/doc/current/components/yaml/yaml_format.html#strings):

>Strings containing any of the following characters must be quoted. [...]

>`:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, `

However, there is absolutely no warning of any kind when a string starting with most of the mentioned characters, although some like `@` throw an error.

It is also saying `Strings containing`, but AFAIK `h@llo` does not raise any error/warning either.

**Comment by xabbuh** [comment]
Afaik we always trigger warnings when possible in these case. The documentation is a bit vague I agree. Though I doubt that it would be better to explain for each of these characters where they are allowed outside of unquoted strings and what implications that bears. However, we can surely discuss that in the docs repo if you disagree. Anyway, I am closing here as I don't see how we can improve the code. Though of course feel free to comment if you can think of concrete YAML examples that could be handled better in the parser (or even in the dumper).

**Comment by theofidry** [comment]
>Afaik we always trigger warnings when possible in these case.

What are those warnings? If I do:

```yaml
foo: %
bar: <
```

I'm not getting anything (I registered a error handler dumping everything it gets and the error report level at `E_ALL` while testing).

**Comment by xabbuh** [comment]
Which version did you use? We made some improvements for 3.1 too.

**Comment by theofidry** [comment]
`v3.0.6` and `dev-master`.

**Comment by xabbuh** [comment]
Having in example like this:

```php
use Symfony\Component\Yaml\Yaml;

error_reporting(E_ALL);

$yaml = <<<EOT
foo: %
bar: <
EOT;

set_error_handler(function ($type, $msg) {
    echo $msg;
});

Yaml::parse($yaml);
```

Yields the following output:

```
Not quoting a scalar starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0.
```

Using only an opening angle bracket is allowed in YAML and yields the string consisting only of the `>` character (see http://yaml-online-parser.appspot.com/, for example).

**Comment by theofidry** [comment]
My bad for the `%`, looks like I missed it.

So for the others, the policy is to state that they should be escaped but doesn't raise a warning?

**Comment by xabbuh** [comment]
When using a standalone script it's not so easy to spot as our deprecation messages are silenced by default and you need an error handler that is capable to handle them (like what we have in Symfony).

The thing is when using any of the aforementioned characters in a YAML string you need to pay extra attention to make sure that the character is treated as is and doesn't trigger some special behaviour in the YAML parser. Thus, at some point in the past we decided to just tell people to quote strings containing those characters while it's strictly not always necessary (but doesn't bother the reader with all the details of the YAML spec). So the only thing we may want to change is be more precise in the docs of when you need to quote those characters and when not (and honestly I am not convinced that that wouldn't even add more confusion).

**Comment by theofidry** [comment]
I'm not convinced that having the doc more precise would be better either. It's just that I kind of expect a warning in all those cases so I wanted to double check :)
