### ISSUE TITLE
[HttpKernel] HttpKernelInterface and SubRequests

### ISSUE THREAD

**Issue by ragboyjr** [symfony/symfony#18791]
Food for thought,

With things like [StackPHP](http://stackphp.com) and other frameworks based off of the Symfony HttpKernel, the HttpKernelInterface is used a lot. One thing i've noticed and that kind of bugs me is the that the kernel interface signature is 

```php
/** @return Response */
public function handle(Request $request, $type = self::MASTER_REQUEST, $catch = true);
```

Personally, this is kind of a bummer because IMHO, it seems like the signature should be:

```php
/** @return Response */
public function handle(Request $request);
```

It would make composition and decoration for the http kernels a lot easier in my opinion. Every kernel shouldn't have to worry about master and sub requests, or catching errors or not. In some instances, sub requests don't really make much sense (consider API's). 

And in addition, you could easily make http kernels that would catch exceptions for you if you wanted. And for sub requests, you could just make add an attribute to the request made like `$request->attributes->set('is_sub', true);` Then an http kernel could just look for that attribute and handle accordingly.

Anyways, it's just a thought. BC might be a tough issue, but you could probably get around it with [interface composition](https://3v4l.org/F07Nt) or something of the like. I was wondering if anyone (symfony devs) shared this thought or if this is something that will *never* change*

**Comment by ragboyjr** [comment]
I guess another thing to think about would be maybe better Psr7 support with the http kernel interface

**Comment by iltar** [comment]
> Then an http kernel could just look for that attribute and handle accordingly.

Except that the request shouldn't be aware if it's a subrequest or not. I don't really see the problem with the current signature. I do about 5~8 sub-requests each page, but they are all via twig. I haven't encountered a case where I want to do a subrequest elsewhere.

**Comment by ragboyjr** [comment]
@iltar, I guess when you don't use twig, there aren't really any other uses for it. 

The Request already holds a bunch of attributes that act as metadata that let external services perform special operations on them. For example, the `_controller` attribute is stored in the Request when that has no meaning to the actual request but only for code that knows to look at that attribute. So storing another attribute that could let an HttpKernel know to process this request specially doesn't seem inconsistent.

**Comment by ragboyjr** [comment]
The point I'm trying to make, is that with the HttpKernelInterface, every http kernel implementation needs to be able to handle Sub Requests, and catching exceptions. When those are two things that don't seem intrinsic to an HttpKernel. You could have a specific Kernel implementation that allows for catching of exceptions or making sub requests, but not every kernel made should have to care about that.
