### ISSUE TITLE
[Serializer] missing @throws tags

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#18798]
If we check the interfaces [SerializerInterface](https://github.com/symfony/serializer/blob/master/SerializerInterface.php), [NormalizerInterface](https://github.com/symfony/serializer/blob/master/Normalizer/NormalizerInterface.php), [DenormalizerInterface](https://github.com/symfony/serializer/blob/master/Normalizer/DenormalizerInterface.php), none of them have a `@throws` tag. Is it intended? Can do a PR if that's not the case.

**Comment by javiereguiluz** [comment]
@theofidry this is clearly something to fix ... but let's wait to see if Symfony Mergers are willing to do it if a PR is proposed or not. Thanks!
