### ISSUE TITLE
LockHandler()->Lock() Fails on Symfony 3.0.6

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#18805]
Hi!

After updating to Symfony 3.0.6 yesterday the LockHandler stopped working with this error:

```
[2016-05-17 22:06:21] php.DEBUG: unlink(web/bundles/framework): No such file or directory 
{"type":2,"file":"/home/eportal/production/releases/20160517200626/vendor/symfony/symfony/src/
Symfony/Component/Filesystem/Filesystem.php","line":178,"level":28928} []
```

This is my code (in top of a process email's script):

```php
        $output->writeln("Locking file...");
        $lockfile = new LockHandler("email.spool.lock");
        if (!$lockfile->lock())
            exit();
        $output->writeln("File locked.");
```

Any help would be greatly appreciated :)

Richard

**Comment by Richard87** [comment]
Also, this is my output when running the command:

    [eportal@vps production]$ php current/bin/console app:process_messages --verbose
    Locking file...
    [eportal@vps production]$ 

Not very exciting...

**Comment by Richard87** [comment]
Also, it works perfectly fine on my development machine (Win10), but the error happens on the production machine (CentOS 7)

**Comment by xabbuh** [comment]
Can you show the full stack trace? I fail to see why the lock handler should try to delete something in your web directory.

**Comment by csarrazi** [comment]
Could you check whether you have the rights to see, or modify the file, or if the file is actually there?

Regarding the first error, I don't think it's related at all. It mostly seems related to a failed deployment, with a script trying to remove the symlink in web/bundles/framework (maybe an error during assets:install or composer install).

**Comment by Richard87** [comment]
Hi, there is no stacktrace, just a warning and then `lock()` fails, so I exit the command...

I'll take a look into the folders now...

**Comment by Richard87** [comment]
the "file/folder" web/bundles/framework is a symling:

     framework -> ../../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/public/

Hmm, yeah, it makes sense that the unlink is unrelated (couldn't find code for it in LockHandler)

Then, why does the `Lock()` fail :(

**Comment by javiereguiluz** [comment]
@Richard87 the `Symfony\Component\Filesystem\LockHandler` class does some error silencing in this line:

![lock_handler](https://cloud.githubusercontent.com/assets/73419/15359129/32b9a462-1d08-11e6-92f3-485c9f6df13e.png)

Could you please try to comment that line and see if some new error message appears?

**Comment by Richard87** [comment]
Thanks, I commented it out (and replaced exit() with echo "Unable  to get lock... Exiting"), and this is my results: (Spoiler: no warnings!)

	[eportal@vps current]$ php bin/console app:proc -e prod --verbose
	Locking file...
	Unable  to get lock... Exiting
	File locked.
	Starting sending messages...
	Hidden filter disabled.
	Found 3 unsent messages.
	Sending MessageID: 98
	Sending MessageID: 459
	Sending MessageID: 464
	[eportal@vps current]$ 

... :/

**Comment by Richard87** [comment]
After removing the lock-file manually all works as expected, so it's most likly a problem with my system :(  

Thank you guys for helping out and looking into it...
