### ISSUE TITLE
Profiler timeline looks confusing in some cases

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18808]
I was trying to optimize a Symfony 3 application when I saw that `kernel.terminate` was taking 93ms (~33% of total time). This is strange because I don't have any custom listener for that event. To make things worse, the profiler timeline displays this:

![profiler_timeline](https://cloud.githubusercontent.com/assets/73419/15370506/a92437aa-1d37-11e6-8df9-7c8aed28053d.png)

So, the email listener takes 2ms and then "nothing" executes for 91ms 😱 

---

The truth is that the `ProfilerListener` hooks into `KernelEvents::TERMINATE`. So the real problem is that the profiler timeline is wrong. It should look like this:

![profiler_timeline_annotated](https://cloud.githubusercontent.com/assets/73419/15370657/330d49e8-1d38-11e6-85fe-e23f04f5da6c.png)

---

I'll try to fix this, but I'd like to ask if others are experiencing weird issues with the timeline. Thanks!

**Comment by patrick-mcdougle** [comment]
I'll bet this has to do with `LateCollect()`. Happy hunting! https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php#L44

**Comment by javiereguiluz** [comment]
Closing it because it's more complicated than I had anticipated.
