### ISSUE TITLE
AuthenticationFailureEvent not triggered for AccountStatusException

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#18807]
I have a subscriber to `AuthenticationFailureEvent` but it isn't triggered for `AccountStatusException`'s.

Ref: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L85

Is there a reason for this?

**Comment by Padam87** [comment]
I would be interested in this as well.

**Comment by chalasr** [comment]
See #23256
