### ISSUE TITLE
[Console] Limit time to answer in QuestionHelper#ask()

### ISSUE THREAD

**Issue by aminin** [symfony/symfony#18809]
## Problem

I have a quiz with questions which have to be responded quickly:
1) to make sure user is not googling an answer
2) to prevent user from stucking in a single question

## Solution

```php
$question = new \Symfony\Component\Console\Question\Question(
    'What is the airspeed velocity of an unladen swallow?',
    'WASTED'
);
$questionHelper->setTimeLimit(20); // The question have to be answered in 20 seconds
$answer = $questionHelper->ask(
    $input,
    $output,
    $question
);
```

**Comment by javiereguiluz** [comment]
I understand that you need this feature, but it looks like a "niche option" to me. This (probably) won't be used by 99.99% of users, so I'd say 👎 to add it to the core of Symfony.

**Comment by javiereguiluz** [comment]
Closing because of the reasons stated above.

@aminin this time your proposal didn't make it, but please remember that the Symfony repository is always open for new ideas and proposals that you may want to share with us. Thank you!
