### ISSUE TITLE
[DoctrineBridge] auto_mapping for multiple managers

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#18800]
Hi,

I looked into the configuration of the doctrine bundle, and thought that `auto_mapping: true` should be working with multiple managers after version 2.6.

However the implementaion does the exact opposite (https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php#L485), even the tests test for a LogicException (https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Tests/DependencyInjection/DoctrineExtensionTest.php#L51-75)

Is this the desired behavior, or is it a bug?

(Related: https://github.com/doctrine/DoctrineBundle/issues/60#issuecomment-167976931)

**Comment by stof** [comment]
the feature added in 2.6 is not to be able to use ``auto_mapping: true`` in multiple managers at the same time, as this can only produce broken setups (mapping the same entity class with multiple entity managers is opening the door to tons of weird cases, many of them breaking in weird ways).
The new feature was to be able to use ``auto_mapping`` in one of the entity manager even when there are other managers defined (while 2.5 and older don't allow to use auto-mapping at all as soon as there are multiple managers). In this case, the auto_mapping will map any bundle which is not already mapped by another manager.

**Comment by Padam87** [comment]
I see. Thanks!
