### ISSUE TITLE
NativeSessionStorage fatal error when profiling and phpseclib library is utilized

### ISSUE THREAD

**Issue by PabloJoan** [symfony/symfony#18819]
I've been profiling an http get request with blackfire.io where I utilize phpseclib ( https://github.com/phpseclib/phpseclib ) to ssh in to a server and execute a command.

the fatal error is this 

```
request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the
session because headers have already been sent by "/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php"
at line 3255." at /app/cache/prod/classes.php line 114 {"exception":"[object]
(RuntimeException(code: 0): Failed to start the session because headers have
already been sent by \"/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php\"
at line 3255. at /app/cache/prod/classes.php:114)"} []
```

in phpseclib, line 3255 is as follows

```php
user_error('Unable to open channel');
```

and the fatal error comes from the native session storage class symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php

```php
if (ini_get('session.use_cookies') && headers_sent($file, $line)) {
    throw new \RuntimeException(sprintf('Failed to start the session because headers have already been sent by "%s" at line %d.', $file, $line));
}
```

i'm not sure how headers_sent and user_error are related, maybe something else is the issue, but when profiling this with blackfire, it happens all the time

Symfony 2.8
Phpseclib 2.0

Php 5.4
Mac OS X 10.11.4

**Comment by Tobion** [comment]
What error handler do you have which is triggered by user_error? It probably outpus something. Thus the error.

**Comment by PabloJoan** [comment]
The library doesn't use any error handlers, only symfony

**Comment by jakzal** [comment]
@PabloJoan would you be able to provide a small script that reproduces this issue?

**Comment by PabloJoan** [comment]
I opened this issue in phpseclib as well, they mentioned they are working on a better solution on the master branch (unstable) and provided a walk around.

https://github.com/phpseclib/phpseclib/issues/990#issuecomment-220863156

**Comment by fabpot** [comment]
Closing as there is no issue in Symfony.
