### ISSUE TITLE
[Console] server:status doesn't work as expected when custom IP is used

### ISSUE THREAD

**Issue by aledeg** [symfony/symfony#18810]
I have a built-in web-server running on ```0.0.0.0:8000``` which I've launch with the following command:
```bash
bin/console server:start 0.0.0.0
```

--------------------------------

When I try to get it's status with the following command, it doesn't work:
```bash
bin/console server:status 0.0.0.0

# I receive that error message
# [WARNING] No web server is listening on http://0.0.0.0
```
But if I try the following command, it works:
```bash
bin/console server:status 0.0.0.0:8000

# I receive that message
# [OK] Web server listening on http://0.0.0.0:8000
```

--------------------------------

I think, that the command should work like the others and use the default port if none is specified.

**Comment by peterrehm** [comment]
@aledeg I was able to verify that bug. I just provided a fix for that.
