### ISSUE TITLE
[Form] Fields not required when object passed as data?

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#18815]
`required="required"` should be default [according to the docs](https://symfony.com/doc/current/reference/forms/types/text.html#required).

What's strange, when I pass array as data, it works as the docs say. When I pass a simple object with public properties, the fields become not–html5-required.

```php
// inside FooType::buildForm()
$builder->add('title');

// title field is html5-required as expected:
$this->formFactory->create(new FooType(), []);
//<input type="text" id="foo_title" name="foo[title]" required="required" />

// title field is not required any more… o.O
$this->formFactory->create(new FooType(), new FooDTO());
//<input type="text" id="foo_title" name="foo[title]" />
```

Symfony 2.7.13. Is it a bug or expected behaviour?

**Comment by MacDada** [comment]
I've found that when I pass an object as data [`FormFactory` guesses](https://github.com/symfony/form/blob/v2.7.13/FormFactory.php#L107) that the field should not be required (as the guessers expect that the field would have i.e. `Assert\NotBlank` or be required Doctrine field).

But why? It is inconsistent with passing data as array and the docs don't mention it => just say that `required` is `true` by default.

So either something is wrong with the code or with documentation.

**Comment by MacDada** [comment]
The difference is here: https://github.com/symfony/form/blob/v2.7.13/FormBuilder.php#L101

For arrays there is no `DataClass`, so [`$type` is always resolved to `'text'`](https://github.com/symfony/form/blob/v2.7.13/FormBuilder.php#L102). Therefore `$type` is not `null` anymore and [`createNamedBuilder ` is called](https://github.com/symfony/form/blob/v2.7.13/FormBuilder.php#L106).

When I pass my DTO, `DataClass` is `FooDTO`, so `$type` is still `null` and can by guessed inside [`createBuilderForProperty `](https://github.com/symfony/form/blob/v2.7.13/FormBuilder.php#L109).

**Comment by HeahDude** [comment]
The doc also says:
>This is superficial and independent from validation. At best, if you let Symfony guess your field type, then the value of this option will be guessed from your validation information.

So this is consistent to me: using an object as data leads to guessing its fields properties and if there is no constraint as you said then it is not required. Arrays do not carry any metadata to do that but one could use his own guessers.

Maybe you can open an issue or a PR in the doc if you think this need to be better explained, but I can't see what could be changed in the core, specially without breaking anything.

**Comment by xabbuh** [comment]
I agree with @HeahDude. Please open an issue on the docs repository if you feel that we could improve the docs regarding this behaviour.
