### ISSUE TITLE
Empty label for CollectionType entry makes the label "Name"

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18849]
`'entry_options' => ['label' => '']` displays as `"Name"` instead of `""`

**Comment by xabbuh** [comment]
You should be able to set the option to `false` to not render the label.

**Comment by flip111** [comment]
Just saying what if you want to render the `label` element without content .. perhaps you have some JS which needs that label tag. Anyway it's odd ..

**Comment by Tobion** [comment]
This is not specific to CollectionType is it?

**Comment by HeahDude** [comment]
@flip111 Which label are talking about when you say "Name"? The collection field label or each entry label?

**Comment by flip111** [comment]
collection field label

```php
  $form = $app['form.factory']->createBuilder(F\FormType::class, [[]])
    ->add('requests', F\CollectionType::class, [
      'allow_add' => true,
      'allow_delete' => true,
      'entry_type' => Vendor\Form\Type\RequestType::class,
      'entry_options' => ['label' => ""]
    ])
    ->add('Get_xml', F\SubmitType::class)
    ->getForm();
```

Using Form component through Silex

**Comment by HeahDude** [comment]
I think you need to try:
```php
$form = $app['form.factory']->createBuilder(F\FormType::class, [[]])
    ->add('requests', F\CollectionType::class, [
        'allow_add' => true,
        'allow_delete' => true,
        'entry_type' => Vendor\Form\Type\RequestType::class,
        'label' => "", // change this line to affect the field label
        // 'entry_options' with nested label handles as many labels as entries
    ])
    ->add('Get_xml', F\SubmitType::class)
    ->getForm();
```

**Comment by HeahDude** [comment]
Note that to assure the mapping of an empty array to the collection field you'd better do:
```php
$form = $app['form.factory']->createBuilder(F\FormType::class, ['requests' => []])
// ...
```

**Comment by flip111** [comment]
@HeahDude hhmm that label you set is only for 1 field, the CollectionType, no? As i remember i was seeing `Name` on each entry of the collection. I will try it and report back though ^^

**Comment by HeahDude** [comment]
Ok that means that it matches the `name` field of the embed `RequestType` but `$entryOptions['label']` matches the inner type itself.

**Comment by HeahDude** [comment]
I think you can close here, feel free to ask a question on [stack-overflow](http://stackoverflow.com) using the label `symfony-forms` if you have some trouble setting the nested field label. Thanks!

**Comment by flip111** [comment]
@HeahDude your suggestion does not work out. `label` controls the label of the Collection itself and not it's entry (children). Also what seems of similar cause is that your suggestion gives (for me) unexpected results for the Collection Label as well ! See below for a small overview. (I was addressing bottom right cell, you the one above)

| | false | not supplied | string | empty string |
| --- | --- | --- | --- | --- |
| collection | no label | name of collection field | collection label | name of collection field | string |
| entry | no label | `__name__label__` | entry label | `Name` |  | string |

So `Name` seems to come out of nowhere since the entry type was not named. So when you make your entry label `""` you don't expect `Name` but just a label without contents. Btw the entry type class only had the `buildForm` method (and the rest inherited from `AbstractType`)

There is also no __`name` nested field of the embed `RequestType`__. All fields have other names then `name`.

Issue is not resolved.

**Comment by HeahDude** [comment]
@flip111 Could you please fork symfony standard and add the minimum of code to reproduce your issue? Thanks

**Comment by stof** [comment]
@flip111 for the empty string, the behavior is the same actually, when you remember 2 things:

- it is not actually the name of the field, but a humanized version of it (i.e. replacing underscores by spaces, turning camel case into separate words and applying ``ucwords``)
- the prototype is named ``__name__``, which gives ``  Name  `` when humanized, hence what you see (if you look at the HTML source, you probably have the extra spaces around the word)

**Comment by flip111** [comment]
@elangovansundar how does your question relate to this issue ?
