### ISSUE TITLE
Use <ul> for CollectionType

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18848]
It would be nice to have a more specialized widget for CollectionType. Before anyone wants to point me to [the code](https://github.com/symfony/symfony/blob/6782cfa01159afbaa0ab083c262677941f00b388/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L26-L31). This could doesn't really specialize much other than setting the prototype attribute. I mean more something along the lines of

```twig
{%- block collection_entry_widget -%}
    <ul {{ block('widget_container_attributes') }}>
        {%- if form.parent is empty -%}
            {{ form_errors(form) }}
        {%- endif -%}
        {{- block('form_rows') -}}
        {{- form_rest(form) -}}
    </ul>
{%- endblock collection_entry_widget -%}

{%- block collection_widget -%}
    {% if prototype is defined %}
        {%- set attr = attr|merge({'data-prototype': form_row(prototype) }) -%}
    {% endif %}
    {{- block('collection_entry_widget') -}}
{%- endblock collection_widget -%}
```

IMO ul is always the correct choice for a list (collection) in html. And this also matches [the documentation](https://symfony.com/doc/current/cookbook/form/form_collections.html).

**Comment by peterrehm** [comment]
Basically same as #18936. http://symfony.com/doc/current/cookbook/form/form_customization.html

**Comment by flip111** [comment]
@peterrehm this issue discuss the change of the specific CollectionType twig template. Issue 18936 is about the mechanism of determining _how to apply_ all form related templates. For this issue it also refers to specific code that is part of the symfony framework (see link in first post), this is not about the documentation.

**Comment by peterrehm** [comment]
I would say all you want to achieve can be done using the current customization options.

**Comment by flip111** [comment]
@peterrehm yes you are right, i'm proposing to make the html list element the standard element for the collection type so that other people can benefit from these html semantics as well out-of-the-box.

**Comment by xabbuh** [comment]
Even if this were semantically more appropriate (which we would need to discuss imo), we would not be able to do this before 4.0 as changing the HTML so massively would be a BC break.

**Comment by peterrehm** [comment]
@xabbuh So this should be closed as won't fix?

**Comment by xabbuh** [comment]
Imo  @symfony/deciders what do you think?

**Comment by fabpot** [comment]
I think the same. The BC break is probably not worth it.

**Comment by xabbuh** [comment]
Closing here as two core team members voted against this change.

**Comment by flip111** [comment]
maybe next year in development phase of 4.0
is there a list to keep track of possible things for 4.0 ?
