### ISSUE TITLE
[Console] Unexpected unsupported command option shortcut

### ISSUE THREAD

**Issue by nico-incubiq** [symfony/symfony#18856]
Hi,
I am using Symfony 2.8.6, and after creating a new Command, I stumbled upon an unexpected error:

```
An argument with name "command" already exists.
[Symfony\Component\Console\Exception\LogicException]
An argument with name "command" already exists.
```

After trying a lot of different solutions, I found out that the error had to do with the option shortcut I used:

```php
$this->setName('my:super:command')
->setAliases(['my:super:commandalias'])
->setDescription('Performs some irrelevant work.')
->addOption('survey', 's', InputOption::VALUE_REQUIRED, 'My option with a shortcut.')
```

After changing the alias (or setting it to null), the error just stopped popping out.
Is there any obvious reason I am missing here, or is this a bug?
Because to my knowledge "s" is not used anywhere else.

Furthermore, the error is awkwardly cryptic and gave me a hard time debugging this.

Regards,
Nicolas

**Comment by mccullagh** [comment]
It is used from the FrameworkBundle for the shell Option https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L44

The Option is removed in 3.0

**Comment by peterrehm** [comment]
@mccullagh What is the relation between the code sample and your referenced InputOption?

However with Symfony 3.0.6 I cannot reproduce the error.

**Comment by peterrehm** [comment]
Ok, I see the point, the error is just raised when calling the command due to the duplicate alias of the Option. The error message is indeed misleading.

**Comment by peterrehm** [comment]
I traced the issue down and just submitted a fix. https://github.com/symfony/symfony/pull/18864

**Comment by nico-incubiq** [comment]
Wonderful! Thanks for the fix
