### ISSUE TITLE
[YAML] Inconsistent serialization / deserialization of ISO 8601 dates

### ISSUE THREAD

**Issue by jkphl** [symfony/symfony#18859]
There seems to be no way of serializing an ISO 8601 date to YAML format so that it would be re-interpreted as date when parsed again. Consider the following simple tests:

```php
use Symfony\Component\Yaml\Yaml;

print_r(Yaml::parse('date: 2015-12-21T22:30:00'));
// Array
// (
//     [date] => 1450737000
// )

echo Yaml::dump(['date' => 1450737000]);
// date: 1450737000

echo Yaml::dump(['date' => new \DateTime('2015-12-21T22:30:00')]);
// date: null

echo Yaml::dump(['date' => new \DateTime('@1450737000')]);
// date: null

echo Yaml::dump(['date' => '2015-12-21T22:30:00']);
// date: '2015-12-21T22:30:00'

print_r(Yaml::parse('date: \'2015-12-21T22:30:00\''));
// Array
// (
//     [date] => 2015-12-21T22:30:00
// )
```

Parsing an unquoted ISO 8601 date will correctly result in a UNIX timestamp (btw. why not a `DateTime` object at all? At least as an option this should be available IMHO). Now try to do it the other way round:

* Passing in a UNIX timestamp will result in an integer
* Passing in a `DateTime` object will result in `null`
* Passing in an ISO 8601 string will result in a quoted string

But re-parsing the quoted string won't convert it back to a UNIX timestamp (because of the quotes).

**Comment by xabbuh** [comment]
With Symfony 3.1 you will be [able to do that](http://symfony.com/blog/new-in-symfony-3-1-customizable-yaml-parsing-and-dumping#parsing-and-dumping-datetime-objects).

**Comment by jkphl** [comment]
@xabbuh That's good news, thanks! Maybe a stupid question: Will this still / automatically work in case the ISO 8601 date is not explicitly parsed ([as in the example provided](http://symfony.com/blog/new-in-symfony-3-1-customizable-yaml-parsing-and-dumping#parsing-and-dumping-datetime-objects)) but a rather a nested value somewhere in a YAML document? Like:

```yaml
something:
  date: 2015-12-21T22:30:00
  whatever: 123
```

What will you need to pass into `Yaml::parse()` then?

**Comment by xabbuh** [comment]
@jkphl `Yaml::PARSE_DATETIME` still is the solution. It basically tells the parser to treat every datetime string it detects in a way to return a `\DateTime` object for it no matter where it is located in your YAML document.

**Comment by stof** [comment]
and for dumping, Symfony 3.1 will accept DateTime (and DateTimeImmutable) without the need of any flag

**Comment by jkphl** [comment]
@xabbuh @stof Awesome, thanks guys! :+1:
