### ISSUE TITLE
issue for enum type with running reverse engeneering

### ISSUE THREAD

**Issue by RodolVelasco** [symfony/symfony#18851]
I'm trying to run this 

`php app/console doctrine:mapping:import --force PDAppBundle xml`

And I'm getting this error 

```
rodolvelasco:~/workspace/osTicketSymfony $ php app/console doctrine:mapping:import --force PDAppBundle xml
                                                                                           
  [Doctrine\DBAL\DBALException]                                                                    
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.  
                                                                                                   
doctrine:mapping:import [--em [EM]] [--filter FILTER] [--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <bundle> [<mapping-type>]

```
Is there any workaround to handle this?

**Comment by javiereguiluz** [comment]
@RodolVelasco as you may know, Symfony is made with several packages and third-party libraries. One of them is called Doctrine, which is glued into Symfony thanks to the Doctrine bundle.

The `doctrine:mapping:import` is provided by that bundle, so we cannot fix it in the Symfony repository. Please, open an issue in https://github.com/doctrine/DoctrineBundle and copy+paste this issue. Thanks!
