### ISSUE TITLE
Detection of when target url is the same as the login_path is extremely brittle

### ISSUE THREAD

**Issue by unsane1047** [symfony/symfony#18862]
The DefaultAuthenticationSuccessHanlder class attempts to redirect you to the specified default_target_path if the referrer is equal to the specified login_path, however, this detection is extremely brittle. Simply adding a blank query string ( /login? instead of /login) when visiting the login_path directly causes the login to wrap back to the login_path rather than using the default target path.

Specifically, these lines (122 through 124) from Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler.php are the issue:

``` php
if ($this->options['use_referer'] && ($targetUrl = $request->headers->get('Referer')) && $targetUrl !== $this->httpUtils->generateUri($request, $this->options['login_path'])) {
    return $targetUrl;
}
```

The last part of the condition in this if statement checks only if the Referer matches the login_path exactly, not taking into account negligible cases such as an empty query string.

I am new to Symfony, so I'm not sure how to accomplish a less brittle check directly using Symfony components, however, I have patched my custom AuthenticationSuccessHandler to split the url and remove any empty query string before comparing the two paths in order to catch this case.

**Comment by mrzard** [comment]
Hi, I just submitted a PR that makes this a bit better, let me know if this useful :)

**Comment by develth** [comment]
The change breaks the login redirect. See comments here:

https://github.com/symfony/symfony/commit/bafa8e29e05e3dda0bf13fbcd85673a9986f57f7

**Comment by xabbuh** [comment]
Can you open a new issue with a description of your problem and how to reproduce it?
