### ISSUE TITLE
Twig duplicating blocks. Bug or feature?

### ISSUE THREAD

**Issue by xDaizu** [symfony/symfony#18866]
Given the following example:

```twig
--parent.html.twig
<div id="container">
    {% block body %}
    {% endblock body %}
</div>
{% block modals %}
{% endblock modals %}

--child.html.twig

{% extends "parent.html.twig %}

{% block body %}
    {%block modals %}
        <div id="childModal"></div>
    {% endblock modals %}
{% endblock body %}
```

#childModal will appear twice in the rendering of child, once inside #container, and another one after it. Is this expected behaviour? It's a special case of nested blocks not reflected on [the manual](http://twig.sensiolabs.org/doc/tags/extends.html)

**Comment by javiereguiluz** [comment]
I'd say that this behavior is the expected one. The child template first fills in `modals` with some content and then fills in the `body` with the same content. Your templates should probably be like this:

```twig
{# parent.html.twig #}
<div id="container">
{% block body %}
    {% block modals %}{% endblock modals %}
{% endblock body %}
</div>

{# child.html.twig #}
{% extends "parent.html.twig %}

{%block modals %}
    <div id="childModal"></div>
{% endblock modals %}
```

**Comment by xDaizu** [comment]
@javiereguiluz  Thanks for your input, it probably is the expected one, just wanted to check. A note in the documentation about this type of nesting could be nice and useful for future users.

 That being said... I think your "your templates should probably be like this" is out of line. The code snippet is not "real", and even if it were, it's obviously a very simplified example to illustrate the case, from where you are literally unable to infer my desired output, since I didn't state it.

**Comment by javiereguiluz** [comment]
@xDaizu I'm sorry if my previous comment offended you. I tried to explain my point in a non-patronizing way ... but it's clear that I didn't manage to explain myself well. I'm sorry.

**Comment by xDaizu** [comment]
@javiereguiluz Don't be! :open_mouth: 
I didn't pretend to sound offended (you know how it is with text :sweat_smile:), it's just that I felt that the addendum served no purpose and distracted from the matter at hand.
