### ISSUE TITLE
[DX] Controller shortcut for dispatching events

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#18868]
Hi everybody.

I was thinking of having a shortcut in the base controller in order to ease dispatching events. This could encourage people using more events and putting less "logic" in the controller. The method could have this signature:

```php
protected function dispatch($eventName, \Symfony\Component\EventDispatcher\Event $event)
```

It would basicaly do:

```php
return $this->get('event_dispatcher')->dispatch($eventName, $event);
```

I know it's a kind of very little shortcut, so I don't know if it worth it. So, the debate is on now ;)

**Comment by chalasr** [comment]
👍 
Small typo in your description `function dispath` instead of `dispatch`.

**Comment by javiereguiluz** [comment]
I'm not sure about this 😕  The gain is minimal. We have some 1-line shortcuts, but they also save you a `use` import. In this case we barely hide any complexity and we just save some characters.

**Comment by chalasr** [comment]
I understand your point of view about the not necessary hidding of complexity, but it's in the same register of Controller::get() (that doesn't need/avoid any use statement) that just makes begginers able to code without having the knowledge of the container. Is it something good? Not sure too

**Comment by iltar** [comment]
One one hand it makes it easier for people to start decoupling logic from controllers, but on the other, this might make them misuse the event dispatcher as command bus.

From my perspective the controllers should be thin. I personally don't fire events from controllers but the layer used by the controllers does. However, by giving (new) developers easy access to events, I fear that people will start putting crucial logic in event listeners. The thing with events is, your application/business logic should still work without the events being fired.

As tracing back which events are fired when is rather complicated, I think this is a counter-dx solution for new devs as it makes it easier to mess up. For more experienced developers, I rather see them fire events in other places than controllers.

**Comment by fabpot** [comment]
I'm 👎 in helping people firing events from controllers, that's an anti-pattern.  We should not encourage that.

Having less logic in controllers is indeed always a good idea, but that's mostly done by moving the logic in business services.

**Comment by Vinorcola** [comment]
Yep that make sense. I think I may have over used events myself to call my business services when you can simply call them from the controller directly.

At least it highlighted my mistake ;)

Thanks for your point of view.
