### ISSUE TITLE
[Form][Validation] Disabled option ignores backend validation

### ISSUE THREAD

**Issue by senaria** [symfony/symfony#18874]
Relates to [#12799](https://github.com/symfony/symfony/issues/12799)

As per [w3 specification](http://www.w3.org/TR/html5/forms.html#concept-fe-disabled) the html validation must be skipped for disabled types. This is fine, but why is this also done for the backend validation?

Imagine I've got two properties on an entity which are represented by two fields on a form ("a" | " b"). The user is able to fill in field "a" but not "b", since this field is disabled. The business logic defines, that "b" is calculated as "a" multiplied by two, and will be calculated each time "a" is set. The validation constraint for "b" defines that it must be greater than 5. With the current implementation the form component will skip validation for "b" if it is disabled, allowing invalid data to be saved.

From my side this is a problem. If, however, I would use "readonly" the field _would_ be validated, but it could also be altered manually (since "readonly" is only a html/frontend constraint). This could violate business logic. If I disable the field, it can not be altered, but it won't be validated to the required constraint. I understand that disabled option will not validate on client-side but why is the validation also disabled on the server-side?

Another thing I noticed is that validation errors for disabled fields will be shown if _any_ other enabled field has a validation error. Somehow this seems very inconsistent. I.e validation errors are prevented from being shown when the errors are only on disabled fields. However, if any other non-disabled field has a validation error, suddenly the disabled field also shows an error ⚠️ . 

Here is a simple example. I realize this could be solved another way but there are some cases with complex business logic that cannot:

``` php
/**
 * @ORM\Entity()
*/
class TestEntity
{
    /**
     * @var int
     * @Assert\NotBlank()
     */
    private $a;

    /**
     * @var int
     * @Assert\GreaterThan(
     *     value = 5
     * )
     */
    private $b;

    public function setA($a){
       $this->a = $a;
       $this->b = $a*2;
    } 

    [...] ( other getters and setters etc.)
}


class TestEntityFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'a',
                null,
            )->add(
                'b',
                null,
                ['disabled' => true]
            );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => TestEntity::class,
                'error_bubbling' => false,
            ]
        );
    }
}

TestController extends Controller
{
    /**
     * @Route("/{id}/edit", requirements={"id" = "\d+"})
     * @Method("POST")
     *
     * @param int     $id
     * @param Request $request
     *
     * @return RedirectResponse|Response
     */
    public function updateAction($id, Request $request)
    {
        $entity = $this->getEntity($id);
        $form = $this->getForm($entity);
        $form->handleRequest($request);
        if ($form->isValid()) { // This is where the form will be validated
            $this->save($entity);

            return $this->redirect(
                $this->generateUrl(
                    $this->getRoute('edit'),
                    [
                        'id' => $id,
                    ]
                )
            );
        }

      [...] // return to edit page
    }
} 
```

twig:

``` twig
{{ form_start(form) }}
    {{ form_row(form.a) }}
    {{ form_row(form.b) }}
{{ form_end(form) }}
```

**scenario 1**
a = 3
b = 6 (disabled)
Results in no validation error being shown. Record will be saved. 👍 

**scenario 2**
a = null
b = 0 (disabled)
Two validation errors are shown, one for "a" and one for "b". Record will not be saved. Correct but inconsistent. 😕  

**scenario 3**
a = 1
b = 2 (disabled)
Results in no validation error being shown. Record will be saved even though "b" is invalid. 
Big problem 👎  

Could you please let me know what your thoughts are about that? It would be cool if we would have at least a option to allow disabled values to be validated too.

**Comment by stof** [comment]
How are you computing ``c`` ? Is it done in your setters which are not there ?

The submitted value for ``c`` is irrelevant for the case, as a disabled field will never update the underlying object (as submitting something in this field is not allowed).
If your setters for ``a`` and ``b`` are recomputing ``c`` automatically, it may not be blank in your first case

**Comment by senaria** [comment]
@stof sorry maybe my example was a bit confusing. I have tried to update it with a simpler example. Could you take another look please? 
Thank you in advance.

**Comment by yakobe** [comment]
Having followed #12799, I agree that this is inconsistent and peotentially very dangerous as invalid data can be saved to the database. 
Is there any workaround to force the validation to run on the entity/object as normal? It seems to me that we should use validation groups to ignore validation on certain fields, and not just automatically ignore entity validation that is mapped to a disabled form field.

**Comment by xabbuh** [comment]
Your issue is that you modify `$b` in the `setA()` method which is called to update the `$a` attribute. I do not think that this is something we can (or even need) to solve in the Form component.

**Comment by yakobe** [comment]
@xabbuh It's not something we even want the form component to solve. That's the whole point... It has nothing to do with the form component. The problem is that the form component is deciding what should or shouldn't be validated, when it is not the business of the form to do that. That is the job of validation groups. Otherwise you end up with the (very dangerous) inconsistencies above.

**Comment by senaria** [comment]
What is the status of this issue?

**Comment by yakobe** [comment]
Can someone have a look into this issue? It's still causing problems for us and making us do some horrible hacks to get around it 😞 .

**Comment by yakobe** [comment]
We would be happy to take a look at fixing it if we know that the solution will be considered. Even if it is just a way to cleanly override the default functionality.

**Comment by xabbuh** [comment]
@webmozart @HeahDude Would you mind looking into this?

**Comment by senaria** [comment]
How is the status about this?

**Comment by Isinlor** [comment]
I think it's the same issue as mine here: https://github.com/symfony/symfony/issues/20784#issuecomment-265178764

[Disabled form is always valid.](https://github.com/symfony/form/blob/master/Form.php#L745)

**Comment by xabbuh** [comment]
@senaria I tried to reproduce your issue with the code from your issue description, but the form was not marked as valid for me. Do you still experience the issue? If so, could you please create a small example application that allows to reproduce it?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Hafsazn** [comment]
hello, you can use

>  'attr'     =>
>                     [
>                         'readOnly' => true
>                     ]

instead of 

> 'disabled' => true
