### ISSUE TITLE
generate:doctrine:crud could generate a form.html.twig template that would be shared by new.html.twig and edit.html.twig

### ISSUE THREAD

**Issue by Ziiweb** [symfony/symfony#18877]
Hi,

I would like to ask you here about the possibility for `generate:doctrine:crud` to generate a `form.html.twig` template that would be included at `new.html.twig` and `edit.html.twig`.

At this moment the new and edit templates are generated this way below (I paste here just edit template)
```
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Service edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('service_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}
```
but I would find more appropriate to generate (for edit template for example) something this like this below, since the most cases the edit and new templates use the same form:
```
{% extends 'base.html.twig' %}

{% block body %}
    **{% include 'form.html.twig' %}**
    <ul>
        <li>
            <a href="{{ path('service_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}
```

**Comment by xabbuh** [comment]
The `generate:doctrine:crud` command is part of the [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle/). Please report your issue over there.
