### ISSUE TITLE
PropertyAccessor problem: "committee" -> "committoo"

### ISSUE THREAD

**Issue by mtijink** [symfony/symfony#18872]
When using Doctrine in symfony, we have a `committee_member` field and corresponding `setCommitteeMember()` in the entity.

However, this does not work since the PropertyAccessor turns this into `setCommittooMember()`, which does not work, of course.

I traced this problem to line 215-216 in `StringUtil::singularify`, where it assumes the `ee` signifies plurality.

**Comment by peterrehm** [comment]
I just provided a PR to fix this. #18909.
