### ISSUE TITLE
Basic functional test does not work properly

### ISSUE THREAD

**Issue by Saint-Cyr** [symfony/symfony#18870]
When running the default funtional test generated with a bundle automatically, we get some error we do not understand it. `sudo phpunit src/Bundlename` We are using symfony 3.0.6

**Comment by javiereguiluz** [comment]
@Saint-Cyr please add a comment here with the output you get when running the tests to see if this is a Symfony error or if it's related with something else. Thanks!

**Comment by Saint-Cyr** [comment]
I'm sorry I just realize a couple of minute ago that it looks like the framework have nothing to deal with this issue because I've reuse the same vendor to run another app and I wase able de run the test without any issue so I apologize to take your time. But additionally I would like you to tell me: is it a good practice to reuse a old vendor for another project after removing all the unnecessary bundles from src/ ?

**Comment by Saint-Cyr** [comment]
As I said it the error is so unreadable .... but this is some part of it: ` <div id="logs">
            <ol class="traces logs">
            <li>
            INFO - Matched route &quot;user_homepage&quot;.
        </li>
            <li>
            INFO - Populated the TokenStorage with an anonymous Token.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\DumpListener::configure&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Bundle\FrameworkBundle\EventListener\TestSessionListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\Security\Http\Firewall::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest&quot;.
        </li>
            <li class="error">
            CRITICAL - Uncaught PHP Exception InvalidArgumentException: &quot;The _controller value &quot;UserBundle:Default:index&quot; maps to a &quot;UserBundle\Controller\DefaultController&quot; class, but this class was not found. Create this class or check the spelling of the class and its namespace.&quot; at /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php line 89
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\DumpListener::configure&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Bundle\FrameworkBundle\EventListener\TestSessionListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Symfony\Component\Security\Http\Firewall::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.request&quot; to listener &quot;Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController&quot;.
        </li>
            <li>
            DEBUG - Notified event &quot;kernel.controller&quot; to listener &quot;Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController&quot;.
        </li>
    </ol>
        </div>
    </div>


<div class="block">
    <h2>
        Stack Trace (Plain Text)&nbsp;
        <a href="#" onclick="toggle('traces-text'); switchIcons('icon-traces-text-open', 'icon-traces-text-close'); return false;"><img class="toggle" id="icon-traces-text-close" alt="-" src="data:image/gif;base64,R0lGODlhEgASAMQSANft94TG57Hb8GS44ez1+mC24IvK6ePx+Wa44dXs92+942e54o3L6W2844/M6dnu+P/+/l614P///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAABIALAAAAAASABIAQAVCoCQBTBOd6Kk4gJhGBCTPxysJb44K0qD/ER/wlxjmisZkMqBEBW5NHrMZmVKvv9hMVsO+hE0EoNAstEYGxG9heIhCADs=" style="display: none" /><img class="toggle" id="icon-traces-text-open" alt="+" src="data:image/gif;base64,R0lGODlhEgASAMQTANft99/v+Ga44bHb8ITG52S44dXs9+z1+uPx+YvK6WC24G+944/M6W28443L6dnu+Ge54v/+/l614P///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAABMALAAAAAASABIAQAVS4DQBTiOd6LkwgJgeUSzHSDoNaZ4PU6FLgYBA5/vFID/DbylRGiNIZu74I0h1hNsVxbNuUV4d9SsZM2EzWe1qThVzwWFOAFCQFa1RQq6DJB4iIQA7" style="display: inline" /></a>    </h2>

    <div id="traces-text" class="trace" style="display: none;">
<pre>[1] InvalidArgumentException: The _controller value &quot;UserBundle:Default:index&quot; maps to a &quot;UserBundle\Controller\DefaultController&quot; class, but this class was not found. Create this class or check the spelling of the class and its namespace.
    at n/a
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php line 89

    at Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser->parse('UserBundle:Default:index')
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php line 60

    at Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->createController('UserBundle:Default:index')
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php line 76

    at Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(object(Request))
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php line 46

    at Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController(object(Request))
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 127

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php line 79

    at Symfony\Component\HttpKernel\Client->doRequest(object(Request))
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php line 131

    at Symfony\Bundle\FrameworkBundle\Client->doRequest(object(Request))
        in /opt/lampp/htdocs/TUTORIAL3/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php line 315

    at Symfony\Component\BrowserKit\Client->request('GET', '/')
        in /opt/lampp/htdocs/TUTORIAL3/src/KinglocatorBundle/Tests/Controller/DefaultControllerTest.php line 13

    at KinglocatorBundle\Tests\Controller\DefaultControllerTest->testIndex()
        in  line 

    at ReflectionMethod->invokeArgs(object(DefaultControllerTest), array())
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php line 910

    at PHPUnit_Framework_TestCase->runTest()
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php line 770

    at PHPUnit_Framework_TestCase->runBare()
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php line 685

    at PHPUnit_Framework_TestResult->run(object(DefaultControllerTest))
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php line 726

    at PHPUnit_Framework_TestCase->run(object(PHPUnit_Framework_TestResult))
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php line 747

    at PHPUnit_Framework_TestSuite->run(object(PHPUnit_Framework_TestResult))
        in phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php line 747

    at PHPUnit_Framework_TestSuite->run(object(PHPUnit_Framework_TestResult))
        in phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php line 429

    at PHPUnit_TextUI_TestRunner->doRun(object(PHPUnit_Framework_TestSuite), array('listGroups' => false, 'loader' => null, 'useDefaultConfiguration' => true, 'testSuffixes' => array('Test.php', '.phpt'), 'configuration' => '/opt/lampp/htdocs/TUTORIAL3/phpunit.xml.dist'))
        in phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php line 155

    at PHPUnit_TextUI_Command->run(array('/usr/local/bin/phpunit', 'src/KinglocatorBundle/'), true)
        in phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php line 106

    at PHPUnit_TextUI_Command::main()
        in /usr/local/bin/phpunit line 515

</pre>
    </div>
</div>

<script type="text/javascript">//<![CDATA[
    function toggle(id, clazz) {
        var el = document.getElementById(id),
            current = el.style.display,
            i;

        if (clazz) {
            var tags = document.getElementsByTagName('*');
            for (i = tags.length - 1; i >= 0; i--) {
                if (tags[i].className === clazz) {
                    tags[i].style.display = 'none';
                }
            }
        }

        el.style.display = current === 'none' ? 'block' : 'none';
    }

    function switchIcons(id1, id2) {
        var icon1, icon2, display1, display2;

        icon1 = document.getElementById(id1);
        icon2 = document.getElementById(id2);

        display1 = icon1.style.display;
        display2 = icon2.style.display;

        icon1.style.display = display2;
        icon2.style.display = display1;
    }
//]]></script>
            </div>
        </div>
    </body>
</html>
' contains "Hello World".
`

**Comment by javiereguiluz** [comment]
> But additionally I would like you to tell me: is it a good practice to reuse a old vendor for another project after removing all the unnecessary bundles from src/ ?

I'm afraid is not. Sharing the `vendor/` dir between different projects always produces hard-to-debug errors.

**Comment by Saint-Cyr** [comment]
thank you ! fortunately I've not yet been far

**Comment by stof** [comment]
@Saint-Cyr your issue is that the autoloader generated by Composer is also in the vendor folder. So by reusing the one of another project, you are missing the autoloading of your own project code.

**Comment by Saint-Cyr** [comment]
Thank you @stof but as @javiereguiluz said it to me : 

> I'm afraid is not

 then I decided to restart the project as Symfony recmmand it (from scratch).
