### ISSUE TITLE
[Translator] DataCollectorTranslator breaks type hints

### ISSUE THREAD

**Issue by havvg** [symfony/symfony#18886]
The commit c923b2ab885f2fce2059a3dcd2a8a643fcb2456b introduced `Symfony\Component\Translation\DataCollectorTranslator` which does not provide the `Symfony\Component\Translation\Translator::addResource` method. As there is no interface available to reflect to collectability of resources as done by the original translator the decorator breaks correct type hints on the actual implementation, which provides the method in question (see [example](https://github.com/propelorm/PropelBundle/blob/aca832ca2e68554694f7f82e41a01e740c50db5b/Translation/ModelTranslation.php#L89)).

What do you think about a `Symfony\Component\Translation\Translator\ResourceCollectionInterface` which holds `addResource` being implemented by both implementations mentioned?

**Comment by stof** [comment]
``addResource`` is part of the configuration API of the implementation, which is implementation specific. Defining an interface for it does not make sense IMO. It is perfectly possible to define translators not needing resources (we have such implementations in Symfony btw).
