### ISSUE TITLE
symfony notification

### ISSUE THREAD

**Issue by arijmachfar** [symfony/symfony#18884]
I'm new in symfony and I want to integrate notification to my project,I want that the admin user receive a notification from user who want to have some information so the admin user should send an email to this user 
how cant I do it ?help please.

**Comment by javiereguiluz** [comment]
@arijmachfar in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
