### ISSUE TITLE
How access to form.parent when the form has child called parent?

### ISSUE THREAD

**Issue by rafrsr** [symfony/symfony#18882]
How can know if a form has a parent or not, in a view?

The fast answer is:

``` twig
{{ form.parent }}
```

but if the form has a child called `parent` the above statement always return a result, even when they do not have a real parent.

then the only way to know if has a real parent is something like:

``` twig
{% set hasParent = (form.parent is not null and (not form.offsetExists('parent') or form.parent != form.offsetGet('parent'))) %}
```

I'm missing something? 

a method `hasParent()` is needed in the FormView to avoid the \ArrayAccess.

**Comment by ianfp** [comment]
I just ran into the same problem. Example:

In MyFormType.php:

    if ($this->shouldHaveParentInput()) {
        $form->add('parent', EntityType::class, [
            // ...
        ]);
    }

In the Twig template:

    {% if form.parent is defined %}
        {{ form_row(form.parent) }}
    {% endif %}

The condition in the Twig template is always true, which causes Bad Things to happen.

**Comment by HeahDude** [comment]
`FormView::$parent` is a public property, you can access the child in twig using `form['parent']`.

But I'm 👍 for adding `FormView::hasParent()` which should be hardcoded in twig to prevent accessing the property.

**Comment by ianfp** [comment]
@HeahDude Oh... I actually have the _inverse_ of @rafrsr's problem. (I didn't read his original description carefully enough.) Using array access notation will work fine for me. Thanks!

**Comment by iltar** [comment]
Usually a form type isn't supposed to know about a parent, a parent only does about its children, not sure if you should build your types/templates from this PoV

**Comment by apfelbox** [comment]
@iltar it is not uncommon to use the check to properly format nested forms.

Even symfony core templates use it: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L256

**Comment by yceruto** [comment]
Well, what about to reintroduce `hasParent()` and `getParent()` methods to `FormView` to fix all these related bugs?

https://github.com/symfony/symfony/commit/b3081e85a062abb8fc8a22f20a2b3289db2ff501#diff-f60b55ea46e40b9c4475a1bd361f6940L239

Note that it isn't just about parent view existence, but access through its properties too.

**Comment by yceruto** [comment]
A quick search on the use of `form.parent` (`*.twig`) in Github repos:

### 30,993 code results (maybe some aren't instances of `FormView`):
https://github.com/search?utf8=%E2%9C%93&q=%22form.parent%22+extension%3Atwig&type=Code&ref=advsearch&l=&l=

**of which 5 in symfony/symfony:**
https://github.com/search?l=&q=%22form.parent%22+extension%3Atwig+repo%3Asymfony%2Fsymfony&ref=advsearch&type=Code&utf8=%E2%9C%93
