### ISSUE TITLE
[Form] default `title` attribute of select elements in DateType field is wrong

### ISSUE THREAD

**Issue by MrMitch** [symfony/symfony#18891]
In a form, the title attribute that is generated for the day, month and year `<select>` elements of a `DateType` field are somewhat strange.

The field is declared by : 
```php
// ...
$builder->add('acceptationDate', DateType::class, [
    'label' => 'Date d\'acceptation',
    'format' => \IntlDateFormatter::LONG
]);

// ...
```

It is rendered by : 
```twig
<div class="col-sm-6">
    <label class="control-label">{{ form.acceptationDate.vars.label }}</label>
    {{ form_widget(form.acceptationDate, {attr: {class: 'profile-proposal-acceptation-date'}}) }}
</div>
```

And the result is : 

![image](https://cloud.githubusercontent.com/assets/576772/15575744/b99e4eea-2354-11e6-9f5e-20f4f853ffae.png)

Notice the `title` of each `<select>` is of the form : 

```
overall type: UNKNOWN_TYPE
    server type: NO_SERVER_DATA
    heuristic type: UNKNOWN_TYPE
    label: Date d'acceptation
    parseable name: proposals][0][acceptationDate][year]
    field signature: 1774999824
    form signature: 15606418167790132698
```

**Comment by xabbuh** [comment]
This looks weird to me. Are you sure that it is not related to another bundle your are using? Can you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by MrMitch** [comment]
Turns out this has nothing to do with Symfony, this was due to a flag being activated in Chrome to show autofill predictions.

![image](https://cloud.githubusercontent.com/assets/576772/15681345/143bf5ac-2759-11e6-84a2-f38710633352.png)

Apologies for the erroneous report.

**Comment by imbhavin95** [comment]
It's filled out with Chrome. Chrome autofill needs this.
