### ISSUE TITLE
[YAML] DateTime parsing with `PARSE_DATETIME` causes fatal error

### ISSUE THREAD

**Issue by jkphl** [symfony/symfony#18897]
With reference to #18859, using the new `PARSE_DATETIME` flag causes a fatal error when parsing an ISO 8601 date:

```php
var_dump(Yaml::parse("date: 2002-12-14", Yaml::PARSE_DATETIME));
```

results in:

```
PHP Warning:  strpos() expects parameter 1 to be string, object given in [...]\symfony\yaml\Parser.php on line 542
PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'A colon cannot be used in an unquoted mapping value at line 1 (near "date: 2002-12-14").' in [...]\symfony\yaml\Parser.php:543
Stack trace:
```

Quoting the date doesn't yield an error but creates no `DateTime` object either:

```php
print_r(Yaml::parse("date: '2002-12-14'", Yaml::PARSE_DATETIME));

Array
(
    [date] => 2002-12-14
)
```

**Comment by xabbuh** [comment]
Thanks for catching this bug @jkphl. Can you please check if #18899 fixes the issue for you?

**Comment by jkphl** [comment]
@xabbuh Will test as soon as possible (tomorrow). Thanks!

**Comment by jkphl** [comment]
@xabbuh Needed to adapt my tests as well, but yes, #18899 seems to work for me! :)

**Comment by xabbuh** [comment]
@jkphl Thank you for the confirmation and also thank you very much for testing the new features before the stable release. This helps us to provide even better working code when the final release is published.

**Comment by jkphl** [comment]
@xabbuh You're welcome! Happy to contribute. :)
