### ISSUE TITLE
Coding style : use multiline class and method signatures

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#18890]
Not sure if this is a standard or what, but it looks like multiline signatures are absolutely not used in the codebase of Symfony. See for instance this 500 characters wide signatures : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/SimpleFormAuthenticationListener.php#L58

I'm ready to make a PR if you want to set a limit.

**Comment by javiereguiluz** [comment]
As you know Symfony follows the PSR-2. In that standard we can read:

```
Argument lists MAY be split across multiple lines, where each subsequent line is
indented once. When doing so, the first item in the list MUST be on the next line,
and there MUST be only one argument per line.

When the argument list is split across multiple lines, the closing parenthesis and
opening brace MUST be placed together on their own line with one space between them.
```

Example:

```php
<?php
namespace Vendor\Package;

class ClassName
{
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
}
```

So, splitting in several lines is optional.

---

My personal vote is to **not** break arguments in several lines whatever their length.

**Comment by greg0ire** [comment]
Thanks for your answer, I know fully well this is optional (otherwise I guess you guys have tests for PSR2 that would not pass), but 500 chars, really, isn't that a bit too much ? 

before : 

```php
public function __construct(TokenStorageInterface $tokenStorage, AuthenticationManagerInterface $authenticationManager, SessionAuthenticationStrategyInterface $sessionStrategy, HttpUtils $httpUtils, $providerKey, AuthenticationSuccessHandlerInterface $successHandler, AuthenticationFailureHandlerInterface $failureHandler, array $options = array(), LoggerInterface $logger = null, EventDispatcherInterface $dispatcher = null, CsrfTokenManagerInterface $csrfTokenManager = null, SimpleFormAuthenticatorInterface $simpleAuthenticator = null) {
}
```

after

```php
public function __construct(
    TokenStorageInterface $tokenStorage,
    AuthenticationManagerInterface $authenticationManager,
    SessionAuthenticationStrategyInterface $sessionStrategy,
    HttpUtils $httpUtils,
    $providerKey,
    AuthenticationSuccessHandlerInterface $successHandler,
    AuthenticationFailureHandlerInterface $failureHandler,
    array $options = array(),
    LoggerInterface $logger = null,
    EventDispatcherInterface $dispatcher = null,
    CsrfTokenManagerInterface $csrfTokenManager = null,
    SimpleFormAuthenticatorInterface $simpleAuthenticator = null
)
```

IMO, besides liking, habits or "readability", I think the latter is easier to review, especially if you're changing an argument, and also, easier to edit.

Plus, you can rapidly tell when a class probably does to much by seeing it has more than 10 arguments.

**Comment by javiereguiluz** [comment]
> Plus, you can rapidly tell when a class probably does to much by seeing it has more than 10 arguments.

That's why I prefer to keep these long lines. They are a painful indicator that something's wrong with that code (although sometimes that long code is right because it is just a rare edge case).

**Comment by greg0ire** [comment]
> That's why I prefer to keep these long lines. They are a painful indicator that something's wrong with that code (although sometimes that long code is right because it is just a rare edge case).

Well if you see a ten line long constructor, you can also tell can't you ? But with more accuracy : you know how many arguments there are, regardless of how long their name, type hinting are. With the first method, you can't quickly tell.

**Comment by Soullivaneuh** [comment]
> you know how many arguments there are, regardless of how long their name, type hinting are. With the first method, you can't quickly tell.

Or just read the phpdoc.

:+1: to keep single line method/class signature. Keep single line method/class signatures is a question of clarity and consistence.

**Comment by greg0ire** [comment]
Consistency with what ? Existing code ? The point is to change it!

**Comment by Soullivaneuh** [comment]
Please do not extract a word of my sentence. I'm also talking about clarity.

Yes this is a personal opinion, like using spaces instead of tabs. This is how standards are built: from opinions. :wink:

**Comment by fabpot** [comment]
Indeed, we are not using multiline method signature, that's the choice we made and we won't change it as it would make merging branches a nightmare for no benefits.

**Comment by Soullivaneuh** [comment]
@javiereguiluz in any case I agree with @greg0ire for one thing: This should be clarified on the coding standard document.

**Comment by javiereguiluz** [comment]
@Soullivaneuh yes

**Comment by greg0ire** [comment]
> @javiereguiluz in any case I agree with @greg0ire for one thing: This should be clarified on the coding standard document.

And maybe also explained.

**Comment by sagikazarmark** [comment]
> They are a painful indicator that something's wrong with that code (although sometimes that long code is right because it is just a rare edge case).

Indicator for whom: developers or users of the framework? Because it is definitely painful for everyone.

**Comment by Soullivaneuh** [comment]
> Because it is definitely painful for everyone.

That's why this kind of long methods should be refactored in this case. :wink: 

I think this what @javiereguiluz tried to explain.

**Comment by sagikazarmark** [comment]
Well, for me the only logical reasoning is this by @fabpot:

> it would make merging branches a nightmare for no benefits.

Although I don't think it is that dramatic (when there are no such long signatures in the first place) it makes sense and I don't think it requires more discussion. It is quite trivial after all.

**Comment by greg0ire** [comment]
> That's why this kind of long methods should be refactored in this case. :wink: 

I think we get exactly what you mean, but this 500-chars-long character has been here for a while, and no one has done anything about it, so you might as well use a `// FIXME` comment or open an issue if you want to draw attention on that. Also, this alerting method is not accurate : you can get an alert if type hinting and arguments are long, even if you don't have many arguments:

```php
<?php
function (Some\Looooooooooong\Classname $someVeryyyyyyyyyyyyyyyyyyyLongArgument, Some\Looooooooooong\Classname $someOtherVeryLongArgument)
```

I know you're going to say "but now you have another problem maybe, but the very same problem can also be seen with a multiline signatures


```php
<?php
function (
    Some\Looooooooooong\Classname $someVeryyyyyyyyyyyyyyyyyyyLongArgument,
    Some\Looooooooooong\Classname $someOtherVeryLongArgument
)
```

Also, if you have *both* problems, you will see it more easily with a multi line signature : 

```php
<?php
function (
    $okayLengthArg,
    $okayLengthArg2,
    $okayLengthArg3,
    $okayLengthArg4,
    Some\Looooooooooong\Classname $someVeryyyyyyyyyyyyyyyyyyyLongArgument,
    Some\Looooooooooong\Classname $someOtherVeryLongArgument
)
```

But not so easily with a single-line signature


```php
<?php
function ($okayLengthArg, $okayLengthArg2, $okayLengthArg3, $okayLengthArg4, Some\Looooooooooong\Classname $someVeryyyyyyyyyyyyyyyyyyyLongArgument, Some\Looooooooooong\Classname $someOtherVeryLongArgument
)
```

**Comment by greg0ire** [comment]
> when there are no such long signatures in the first place

What do you mean? I gave an example from the symfony code of a 500 characters long method signature…

**Comment by Soullivaneuh** [comment]
If you have something like this:

```php
<?php
function (Some\Looooooooooong\Classname $someVeryyyyyyyyyyyyyyyyyyyLongArgument, Some\Looooooooooong\Classname $someOtherVeryLongArgument)
```

I think you have a problem too. :stuck_out_tongue: 

> > Well, for me the only logical reasoning is this by @fabpot:

> it would make merging branches a nightmare for no benefits.

Not the only IMHO but yes, this is the biggest issue.

**Comment by greg0ire** [comment]
> Although I don't think it is that dramatic

The main problem is that every decision made here makes it to other project that simply base themselves on all symfony standards, which mean maybe the standards should be very very carefully chosen. And if something turns out to be not so great and changing it is too much of a hassle, just say that instead of carving the rule in stone. Something along the lines "Symfony does it like this, but this rule is a legacy rule, not part of the standards, don't follow it".

> I think you have a problem too. :stuck_out_tongue: 
Please read all of my answer before replying.

**Comment by Soullivaneuh** [comment]
> Please read all of my answer before replying

I read it. This change not really nothing. You have two problems? Well, fix the first one and see what is going.

**Comment by greg0ire** [comment]
> I read it. This change not really nothing. You have two problems? Well, fix the first one and see what is going.

That's the point : fixing the second might be way easier (if it is the argument name being to long), but if you can't notice it, too bad.

**Comment by Soullivaneuh** [comment]
That's the point but I think it's pointless regarding the other inconvenients.

Your argument is acceptable, but I don't agree with it. :-)

**Comment by greg0ire** [comment]
> Your argument is acceptable, but I don't agree with it. :-)

Well let's agree to disagree then :)

**Comment by fabpot** [comment]
Everything has been said, locking this conversation now.
