### ISSUE TITLE
Lazy Services don't work with PHP 7.0.7

### ISSUE THREAD

**Issue by Hast** [symfony/symfony#18895]
PHP 7.0.7 was released today, including [bugfix#71737 (Memory leak in closure with parameter named $this)](https://bugs.php.net/bug.php?id=71737).

Now, all compiled lazy services throw this exception:

`FatalErrorException in appDevDebugProjectContainer.php: Compile Error: Cannot use $this as parameter`

This is the line from the debug container causing the problem: http://joxi.ru/XEA4JEfDYaKemb.jpg

Looks like a critical issue, because we have to either downgrade to 7.0.6 or turn off all lazy services in the project.

**Comment by stof** [comment]
This should be reported to the ProxyManager library, which is the one generating this code

**Comment by Hast** [comment]
Thank you, I reported the issue there: https://github.com/Ocramius/ProxyManager/issues/316

**Comment by Ocramius** [comment]
This is being worked on on https://github.com/Ocramius/ProxyManager/pull/308

Still depending on builds to pass though.
