### ISSUE TITLE
[HttpKernel] Normalize "SYMFONY__" environment parameters

### ISSUE THREAD

**Issue by seeeppp** [symfony/symfony#18905]
I'm currently working on a __Symfony 2.8__ based project where i ran into an issue using a .env file and [vlucas/phpdotenv](https://packagist.org/packages/vlucas/phpdotenv) for setting the environment parameters. For now it's not possible to use a boolean or numeric parameter in the .env file because those parameters aren't normalized and always will be a string. 
For my project i added a simple method to the AppKernel that normalizes the .env parameter before setting it to the symfony environment.

I'm not quiet sure if that is a problem that should be fixed in [vlucas/phpdotenv](https://packagist.org/packages/vlucas/phpdotenv) or a feature that should be added to the HttpKernel; especially for a 12-factor app?

I created a [fork](https://github.com/seeeppp/symfony-standard) of the standard edition to recreate the problem. Just remove the call of my `normalizeEnvValue` method in `AppKernel::getEnvParameters`.

I also would be very glad if someone has a better way solving my problem :-)

**Comment by peterrehm** [comment]
There is a discussion around this matter here: https://github.com/vlucas/phpdotenv/issues/104

However such normalization could easily be added to SF itself, I do not know if this is wanted, IMHO it would make sense.

**Comment by vershnik** [comment]
This should be solved in SF, as environment variable not necessary loaded from .env file using vlucas/phpdotenv 

I use ENV instruction in Dockerfile and --env-file option when running container, and I'm getting strings instead of booleans.

**Comment by javiereguiluz** [comment]
To give some context on why this issue was closed ... there is a proposal to deprecate these variables entirely (and remove them in future Symfony versions): #20089
