### ISSUE TITLE
EntityType Field - Possible error with NotBlank

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#18900]
I found an issue with a very simple use case when using an EntityType Field.

Example, I have defined a field like this mapped to a Site entity:

```php
class SiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('siteType', EntityType::class, array(
            'label' => 'type',
            'class' => 'PTCNoventoBundle:SiteType',
            'choice_label' => 'translations['.$this->locale.'].name',
            'query_builder' => function(EntityRepository $er) {
                return $er->findAllSortedByName($this->locale);
            },
            'placeholder' => 'select.option',
            'empty_data' => null,
        ));
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Site::class,
        ));
    }
));
```
And in my entity, I have the corresponding property:

```php

class Site
{
    /**
     * @Assert\NotNull
     * @ORM\ManyToOne(targetEntity="PTC\NoventoBundle\Entity\SiteType")
     * @ORM\JoinColumn(name="site_type_id", referencedColumnName="id", nullable=false)
     */
    private $siteType;

    public function setSiteType(\PTC\NoventoBundle\Entity\SiteType $siteType)
    {
        $this->siteType = $siteType;

        return $this;
    }
    ...
```

Result at Site creation (works as expected):
- Empty selection in siteType list -> Error on field siteType: This value should not be null.
- Selection in siteType list -> Creation of Site

Result at Site modification (don't works as expected):
- Empty selection in siteType list -> (EXPECTED) Error on field siteType: This value should not be null. (CURRENT)  500 Internal Server Error - InvalidArgumentException: Expected argument of type "PTC\NoventoBundle\Entity\SiteType", "NULL" given 
- Selection in siteType list -> Creation of Site

So, as you can see, when I change the selection in the list from an old selected value to empty one, Symfony tries to set NULL in siteType property of Site entity (with the propertyPath accessor) before validation. I understand that the validator need to set NULL to the entity before being able to validate it but it's weird for me to insert data that is not allowed to be in an entity. 

@webmozart Do you have idea about that?

As a workarround I need to set the null default value in setSiteType, but it's seems very weird:
```php
public function setSiteType(\PTC\NoventoBundle\Entity\SiteType $siteType = null)
```

Stack trace:
 at PropertyAccessor ::handleError ('4096', 'Argument 1 passed to PTC\NoventoBundle\Entity\Site::setSiteType() must be an instance of PTC\NoventoBundle\Entity\SiteType, null given, called in /home/lallement/workspace-ic2m/novento/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 605 and defined', '.../novento/src/PTC/NoventoBundle/Entity/Site.php', '88', array('this' => object(Site)))
in src/PTC/NoventoBundle/Entity/Site.php at line 88 
at Site ->setSiteType (null)
in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 605
at PropertyAccessor ->writeProperty (array(object(Site), object(Site)), 'siteType', null)
in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 201
at PropertyAccessor ->setValue (object(Site), object(PropertyPath), null)
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php at line 93
at PropertyPathMapper ->mapFormsToData (object(RecursiveIteratorIterator), object(Site))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 618  +
at Form ->submit (array('name' => 'A', 'siteType' => '', 'save' => '', '_token' => 'FPNl_4fv2i6Eh0lc-ii6CU3wzjt569cY6bB3_YcCSs0'), true)
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php at line 116
at HttpFoundationRequestHandler ->handleRequest (object(Form), object(Request))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 488  +
at Form ->handleRequest (object(Request))
in src/PTC/NoventoBundle/Controller/Transport/SiteController.php at line 54

**Comment by iltar** [comment]
Validation is done _after_ populating the data objects. If your data object is an entity, you will have to allow populating invalid data into your entity in order to validate it. I don't know why it inserts null, but if you want to prevent this from happening, don't use entities as data objects: http://blog.iltar.nl/posts/733915-avoiding-entities-in-forms

**Comment by raziel057** [comment]
Endeed it's also the conclusion I made. When the entity is directly used as data object, we must allow populating with invalid data and it's seems to be dangerous. But maybe another solution could be found without having to write a specific distinct data object. Not sure...

**Comment by peterrehm** [comment]
@raziel057 If you ensure that you validate your objects before persisting them it is not critical at all. One Option would be making the Object nullable.

````php

class Site
{
    /**
     * @Assert\NotNull
     * @ORM\ManyToOne(targetEntity="PTC\NoventoBundle\Entity\SiteType")
     * @ORM\JoinColumn(name="site_type_id", referencedColumnName="id", nullable=false)
     */
    private $siteType;

    public function setSiteType(\PTC\NoventoBundle\Entity\SiteType $siteType = null)
    {
        $this->siteType = $siteType;

        return $this;
    }
    ...
````

I assume when you have tested the modification you created at first a Site with a valid SiteType. Then when changing it the PropertyPathMapper is forced to map the null value to the property as the value is different. However when instantiating an Object the property siteType is null by default. When the mapper gets null as a value it skips to set the new value as there would be no difference. So by the way, when instantiating your Object without a constructor you have invalid data by default and you need to have a validator to ensure data consistency.

You can read further in the PropertyPathMapper here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php#L92

I would say the behaviour is as expected and you should work around as per your need and this ticket can be closed.

**Comment by raziel057** [comment]
@peterrehm "One Option would be making the Object nullab" <- This is what I've done currently, even if it seems to not be the best solution as I know the property (at Entity Level) must never be null. But as the entity is also used for validation (as Data Object) I know it must be nullable. In fact it's the same when data is not initialized (at creation) so no problem with that, I can live with this work around. So I close the ticket.
