### ISSUE TITLE
[Twig][Assetic] Load assets by name

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#18901]
Hey,

it'd be really helpful, if the `asset` function could load named assets directly:

config.yml:

```yaml
assetic:
    assets:
        acme:
            ...
```
Somewhere in Twig:

`<link rel="stylesheet" href="{{ asset('@acme') }}"/>`

instead of the need to use a `stylesheets` tag to recompile the same file.

This way our devs don't have to know any target location of the output and the filesystem wouldn't be filled with useless files.

As Assetic already can load assets by name this shouldn't be too hard to implement?

Cheers
Matthias

**Comment by stof** [comment]
The ``asset`` function is just about adding the right prefix and the right version in the URL. It cannot know about Assetic.

**Comment by althaus** [comment]
So if neither Assetic nor the `asset` function are capable of doing this... what would be the best option to add this feature? Should I write my own `NamedAssetsTwigExtension` which gets the asset manager(?) and then could add a `named_asset` function? It's basically so plain simple to replace `@acme` with the configured output value. :(

**Comment by stof** [comment]
You asked Assetic to support its named assets in the ``asset`` function, which it cannot do as it does not own this function. And symfony cannot support it, as it does not know about Assetic (and this code cannot know it for BC reasons, and should not know it either btw).

Having a separate function asking Assetic for a named asset could work (it would still have nothing to do with the ``asset`` function of Symfony btw)

**Comment by xabbuh** [comment]
Closing here as the requested feature would need to be added in the AsseticBundle.

**Comment by althaus** [comment]
OK... I give up... I won't post the request another time at another place. Just going back to the drawing board rethinking the usage of Assetic at all.
