### ISSUE TITLE
[JavaScript] How to handle Symfony form collection nested in another form collection 

### ISSUE THREAD

**Issue by 4dr3n4l1n3** [symfony/symfony#18910]
Hi, 
I have a multilevel nested collections, and the official tutorial of symfony offers a javascript solution to manage one level of form collection.
any suggestions for javascript ?

**Comment by peterrehm** [comment]
This is not directly an issue with Symfony, however you can find a working sample in the MopaBootstrapBundle here http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/collections/nested.

I hope this helps your needs.

**Comment by javiereguiluz** [comment]
@4dr3n4l1n3 sadly I need to close this issue because in the GitHub repository we only discuss about Symfony bugs and new features. If the solution provided by @peterrehm doesn't work for you, please use any of the official Symfony support alternatives shown in http://symfony.com/support Thanks!
