### ISSUE TITLE
 unexpected 'self' Process Component

### ISSUE THREAD

**Issue by DracotMolver** [symfony/symfony#18926]
I just update silex framework where I'm using the Process component and was working ok but now I've got an error. I used to use v3.0 of this component, but know I'm getting the next error message:  syntax error, unexpected 'self' (T_STRING) in ../vendor/symfony/process/Process.php on line 538. This is in the version v3.1.0.

**Comment by stof** [comment]
This code is perfectly valid.

what is your PHP version ?

**Comment by iltar** [comment]
I think this is ran on an unsupported php version: https://3v4l.org/VoLHU

**Comment by stof** [comment]
Yeah, the error message complaining about ``self`` is weird, when the actual issue is ``yield`` being unsupported in this version.

**Comment by DracotMolver** [comment]
thanks guys, I knew the code was right, but I didn't know about the version - it was in my mind but I dind't give it importation -. @iltar  thanks a lot for that link . and Yes is the version. I'm using PHP v5.4.43. Thanks both :)
