### ISSUE TITLE
3.0.6 doctrine generate:crud fails with datetime

### ISSUE THREAD

**Issue by Haikuch** [symfony/symfony#18920]
when calling doctrine:generate:crud on an entity with a datetime column, the command creates 

> ->add('time', 'datetime')

in the form type, but this throws an exception, it should be 

> ->add('time', DateTimeType::class)

instead

**Comment by stof** [comment]
Closing this because the crud generator is part of SensioGeneratorBundle, not of Symfony. Please report it to this bundle

**Comment by Haikuch** [comment]
ok, its already posted there, fine https://github.com/sensiolabs/SensioGeneratorBundle/issues/463
