### ISSUE TITLE
[Finder] Abysmal performance on FTP

### ISSUE THREAD

**Issue by sandermarechal** [symfony/symfony#18923]
Finder has abysmal performance when used on FTP. Much worse than using standard SPL iterators directly. Depending on the FTP service used, Finder will return files at a rate of one every 10-30 seconds(!) while PHP's internal iterators take mere milliseconds.

Here's a quick benchmark script:

``` php
<?php

require 'vendor/autoload.php';

// Some public FTP servers to use
$ftp = 'ftp://speedtest.tele2.net/'; // Fast server
//$ftp = 'ftp://ftp.hq.nasa.gov/';     // Not so fast server, still fast with RecursiveDirectoryIterator

function benchmark($it)
{
    $start = microtime(true);

    foreach ($it as $file) {
        echo ".";
    }

    echo "\nTime: " . round(microtime(true) - $start, 4) . "s\n";
}

echo "Testing on $ftp\n";

echo "PHP Internal iterator:\n";
benchmark(new NoRewindIterator(new DirectoryIterator($ftp)));

echo "Symfony Finder iterator:\n";
$finder = new \Symfony\Component\Finder\Finder();
$finder->in($ftp)->depth('== 0');

benchmark($finder);
```

I have included some publicly available FTP servers in the script to test with. Some example runs:

```
$ php test.php 
Testing on ftp://speedtest.tele2.net/
PHP Internal iterator:
..................
Time: 0.0006s
Symfony Finder iterator:
.................
Time: 18.04s
```

```
$ php test.php 
Testing on ftp://ftp.hq.nasa.gov/
PHP Internal iterator:
..........
Time: 0.0002s
Symfony Finder iterator:
............................................................................................................................................................................^C
```

I broke off that last test after a good 15 minutes or so. It was giving me about 1 file every 30 seconds.

Tested with Finder 2.8.x, 3.x and dev-master (4a4ef9f) on PHP 5.x and PHP 7

**Comment by sandermarechal** [comment]
I have tried running the script under Wireshark because I suspected that maybe Finder is downloading complete files just to get some SplFileInfo. It doesn't appear to do that, but I do see a large amount of FTP commands going over the wire, inlcuding many new connections/logins.

**Comment by stof** [comment]
your bencmark does not make things comparable. Your internal iterator does not iterate recursely over the RecursiveDirectoryIterator

**Comment by sandermarechal** [comment]
True. I'll see if I can fix that benchmark for better accuracy.

But still, it can take up to 30 seconds or more to retrieve a single file from the listing using Finder. That's not some small performance loss that needs a very accurate benchmark. That's several orders of magnitude difference.

**Comment by sandermarechal** [comment]
I have updated the benchmark script so that both the internal iterator and the Finder return the same list of files (non-recursively):

```
$ php test.php 
Testing on ftp://speedtest.tele2.net/
PHP Internal iterator:
..................
Time: 0.0002s
Symfony Finder iterator:
..................
Time: 11.8024s
```

```
$ php test.php 
Testing on ftp://ftp.hq.nasa.gov/
PHP Internal iterator:
..........
Time: 0.0001s
Symfony Finder iterator:
..........
Time: 36.8364s
```

I noticed that the main difference between the two FTP servers is the speed at which logging in happens. From the wireshark logs I also see a whole lot of FTP connections being established. Could it be that Finder is continually reconnecting with the FTP server for information about files?

**Comment by sandermarechal** [comment]
After some more testing I can reproduce the issue. If I call something like `$file->isDir()` while iterating, the interal iterator is also very slow. It seems that SplFileInfo reconnects to the FTP server for file information of a specific file.

**Comment by stof** [comment]
@sandermarechal the Finder component does not do anything with FTP. It just deals with directory iterators and SplFileInfo, which themselves deal with PHP streams.
To fix your issue, you would probably need to optimize the FTP stream wrapper to reuse existing FTP connections whenever possible. This is not something we can fix in the Finder component.
Note however than you could write a userland implementation of such a stream wrapper and register it over the one shipped in ext-ftp, and it will be used when using the Finder, allowing you to prototype this kind of optimization in PHP rather than doing it in C in ext-ftp directly.

**Comment by xabbuh** [comment]
Closing for the reasons explained by @stof.

**Comment by DerDu** [comment]
FYI: Just in case someone is struggling with this, here is a "drop-in solution"

I used the following library to boost performance from 15-20s to 2s :) .. not as good as plain PHP but better than dropping Finder ;)

https://github.com/emersion/php-wrappers

```
FtpStream::register();

// Finder stuff

FtpStream::unregister();
```

(There are also classes for sFTP and FTPs included)
