### ISSUE TITLE
Is parameter missing in security.user.provider.ldap ?

### ISSUE THREAD

**Issue by idybil** [symfony/symfony#18933]
Hi, I think there is a missing parameter in the security.user.provider.ldap service in the security.xml file (vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/config/security.xml). 

The missing parameter is the password_attribute.

```xml
<service id="security.user.provider.ldap" 
 class="Symfony\Component\Security\Core\User\LdapUserProvider" abstract="true" public="false">
 argument - security.ldap.ldap 
 argument  - base dn
 argument  - search dn
 argument  - search password
 argument  - default_roles
 argument  - uid key
 argument  - filter
 **argument  - SHOULD WE ADD A NEW ARGUMENT HERE FOR THE password_attribute ?**
</service>
```

Because when I try to use the LDAP provider in my security.yml file, Symfony throws me the next exception :

```
OutOfBoundsException in Definition.php line 202: The index "7" is not in the range [0, 6].
```

As a temporary workaround, I override the service in my service.yml to add the password_attribute parameter and it worked.

Thanks

EDIT: The Symfony version I'm using is 3.1

**Comment by iltar** [comment]
@csarrazi probably knows more about this, but my guess is that it slipped through as the functional tests are missing atm

**Comment by csarrazi** [comment]
Ok. It seems that this is simply an issue with the service definition itself. I'll fix this ASAP.

**Comment by idybil** [comment]
Thanks @csarrazi
