### ISSUE TITLE
Cascade form styling

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18936]
It would be nice to be able to cascade the twig template to child forms. For example with the bootstrap3 twig template and some complex forms with collections you can not do things like: change the html of all the fields of the collection entry. You can change the row of the entry itself, but not the fields of the entry type.

**Comment by peterrehm** [comment]
@flip111 There are several ways how to customize the rendering. http://symfony.com/doc/current/cookbook/form/form_customization.html What else would you need?

**Comment by flip111** [comment]
@peterrehm you don't understand this feature request? or are you saying the feature is already available?

**Comment by peterrehm** [comment]
@flip111 I would say it is already possible as you can e.g. define the view for a specifiy collection, see the link above.

**Comment by flip111** [comment]
@peterrehm as far as i know customizing a view for a collection doesn't cascade down, can you give an example how this would work?

**Comment by peterrehm** [comment]
In the view of an form you can do e.g. the following:

````twig
   {% form_theme form 'AppBundle:form:collection.html.twig' %}
    </fieldset>
    <fieldset id="tab-third" class="tab-pane">
        <div class="tab-content">
            {{ form_row(form.myCollection) }}
        </div>
    </fieldset>
````

**Comment by flip111** [comment]
@peterrehm are you sure that code is ok? afaik you should place html in a `block` tag, then you can use `form_theme` tag to set custom view for this form. Anyway it seems that you have part of a form and load a custom template for that `CollectionType`. At least i will assume this because it's missing the content of file `collection.html.twig`. I don't really see how this is answering the question of cascading form templates. Maybe i should describe the issue slightly different...

Suppose you want to change `form_row` of all types, you can just change `form_row` .. simple. But now you want to change all `from_row` for fields that are part of collection `libraries`. There is no cascading here, so you will have to change this manually on each field (as far as i know at least). I can't use a generic `form_row` "applied to collectiontype `libraries`" here ... i just need to customize my fields one by one. I would like them to inherit their template from a `form_row` that is specialized for `libraries`.

I hope this doesn't make it more confusing for you, but let's compare it to CSS. Just to help explain what is "cascading". NOTE: this issue is NOT about css, i'm just using it as example. And also, this html has nothing to do with the form html in symfony form templating.

`form_row` could be `<form_row>` (suppose html supports this tag), now if you want to style that you do:

```css
form_row {
    color: blue;
}
```

now what i would like to do is this:
```css
#libraries form_row {
    color: red;
}
```

but still be able to do something like this:
```css
#libraries #city {
    color: yellow;
}
```

This middle step here (the second css snippet) is not supported as far as i know.

You can keep on cascading as well .. for example if the `libraries` have another collection in them such as `books`

**Comment by peterrehm** [comment]
Args I did not past the second part of the snippet, I just updated the code above. Of course the snippts are just snippets of the relevant parts, you can read up about the customization.

If you want your way of inheritance you could create e.g. custom types inheriting the Collection type.

````
class MyCollection extends CollectionType
{
    //...
}

class MyOtherCollection extends MyCollection
{
    //...
}
````

With this you should be able to create some kind of inheritance. 

In your case I think I would just handle it with custom themes and would have the inheritance if really needed in the themes.

**Comment by flip111** [comment]
@peterrehm i think the issue is orthogonal to what you are proposing. When it comes to how forms are displayed on a website there are actually a bunch of things that have either inheritance or some kind of tree structure

1. html is a tree structure
2. css can be a tree structure
3. types can have a tree structure by php class inheritance
4. forms have a tree structure when they are nested

Right now item 3 is coupled with item 1. Namely ... the html widget is chosen based on the FormType. This is what you are describing. As far as i know there is currently no way to couple item 4 with item 1. This would be very convenient though as it would allow you to customize formtypes PER "location" inside the form. So then you could do:

```
Form
  LibraryName (TextType)
  BooksCollection (Collection)
    BookName (TextType)
```

Change the template of `BookName` because `it's part of BooksCollection`.

Right now you are forced to work in the other system of php formtypes and this would require you to create a custom type. This is now a bit weird because in your presentation (view) is coupled with the data (model) .. a formtype holds data and also uses a particular template. I would like to choose another template for an existing type based on where in the presentation layer it's placed. And the presentation location is based on how forms are nested and not how type inheritance works.

**Comment by peterrehm** [comment]
I just provided possible solutions for your use case. I don't think inheritance is normally needed as in general collections will look the same or you can handle it with the theme itself. With the restriction that you need to define the view properly where you want to render the form.

**Comment by flip111** [comment]
@peterrehm thank you for trying to provide a solution. Actually i already had my case fixed before i opened this issue. If i need support to fix my code i will open up a question on stackoverflow or ask in IRC. I opened this issue to discuss a possible new feature in symfony that changes coupling of formtypes, formtemplating and data.

**Comment by xabbuh** [comment]
I am closing here as I don't think this is going to happen and it also doesn't seem that this is a feature many users are looking for.
