### ISSUE TITLE
[console] Performance issue when rendering a table

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#18957]
I have a table with following configuration:

* 5 columns
* 128 rows
* a header row

This is 645 cells in total that require any kind of formatting. It takes **~0.25sec** to render such table even if all (but header) cells are empty.

Digging it further I've found that **~5000** calls to `OutputFormatter::format` method are made. I think that every decoration element in table (e.g. `----` and `|`) is processed via `OutputFormatter::format` method each time even though they don't change during table rendering process.

Here is list of call traces grouped by call path (arguments might be different):

```

Symfony\Component\Console\Formatter\OutputFormatter::format (line 112) <- Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration (line 601) <- Symfony\Component\Console\Helper\Table::getCellWidth (line 572) <- Symfony\Component\Console\Helper\Table::calculateColumnsWidth (line 259) - 1446 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 122) <- Symfony\Component\Console\Output\Output::writeln (line 302) <- Symfony\Component\Console\Helper\Table::renderRowSeparator (line 261) - 1 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 310) <- Symfony\Component\Console\Helper\Table::renderColumnSeparator (line 327) <- Symfony\Component\Console\Helper\Table::renderRow (line 264) - 1 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 112) <- Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration (line 363) <- Symfony\Component\Console\Helper\Table::renderCell (line 329) <- Symfony\Component\Console\Helper\Table::renderRow (line 264) - 6 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 365) <- Symfony\Component\Console\Helper\Table::renderCell (line 329) <- Symfony\Component\Console\Helper\Table::renderRow (line 264) - 6 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 310) <- Symfony\Component\Console\Helper\Table::renderColumnSeparator (line 330) <- Symfony\Component\Console\Helper\Table::renderRow (line 264) - 6 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 122) <- Symfony\Component\Console\Output\Output::writeln (line 332) <- Symfony\Component\Console\Helper\Table::renderRow (line 264) - 1 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 122) <- Symfony\Component\Console\Output\Output::writeln (line 302) <- Symfony\Component\Console\Helper\Table::renderRowSeparator (line 265) - 1 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 310) <- Symfony\Component\Console\Helper\Table::renderColumnSeparator (line 327) <- Symfony\Component\Console\Helper\Table::renderRow (line 272) - 240 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 112) <- Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration (line 363) <- Symfony\Component\Console\Helper\Table::renderCell (line 329) <- Symfony\Component\Console\Helper\Table::renderRow (line 272) - 1440 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 365) <- Symfony\Component\Console\Helper\Table::renderCell (line 329) <- Symfony\Component\Console\Helper\Table::renderRow (line 272) - 1440 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 310) <- Symfony\Component\Console\Helper\Table::renderColumnSeparator (line 330) <- Symfony\Component\Console\Helper\Table::renderRow (line 272) - 1440 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 122) <- Symfony\Component\Console\Output\Output::writeln (line 332) <- Symfony\Component\Console\Helper\Table::renderRow (line 272) - 240 times

Symfony\Component\Console\Formatter\OutputFormatter::format (line 145) <- Symfony\Component\Console\Output\Output::write (line 122) <- Symfony\Component\Console\Output\Output::writeln (line 302) <- Symfony\Component\Console\Helper\Table::renderRowSeparator (line 276) - 1 times
```

**Comment by aik099** [comment]
The `\Symfony\Component\Console\Helper\Table::renderColumnSeparator` method is sure doing same thing again and again and just commenting it out I've shaved `0.08s` from script run time.

**Comment by aik099** [comment]
Probably if each cell, that know upfront that it doesn't need formatting, can specify OUTPUT_RAW as well, then this could speed up things as well.

**Comment by aik099** [comment]
> Also it's worth consolidating all `$this->output->write` done to build a single table row into single call, because it would make only as much calls as table has rows instead of making `rows x columns` calls as now.

After only doing that locally here is how things have improved (XHProf diff):

![symfonyconsole_tablerendering_performanceimprovement1](https://cloud.githubusercontent.com/assets/1277526/15779809/3978b936-29a7-11e6-9038-854aa497a1d4.png)

**Comment by javiereguiluz** [comment]
@aik099 the results look impressive. Have you tried to run tests after your changes to see if it breaks some edge-case? Thanks!

**Comment by aik099** [comment]
I haven't. So far I've experimented in `vendor/symfony/console` folder in my project. I can try making same code changes in symfony repo clone and see about the tests.

**Comment by javiereguiluz** [comment]
@aik099 you can do a `cd vendor/symfony/console` and `composer install` and `phpunit` those tests only.

**Comment by aik099** [comment]
Nice trick. All tests pass.

**Comment by aik099** [comment]
I've submitted a PR with current changes. I'm sure more aspects in table rendering can be improved, but it's a good start. After that PR applied in my test scenario total application runtime was cut off from **0.39s** to **0.26s**.

**Comment by aik099** [comment]
Here is same report from BlackFire.Io:

<iframe frameborder="0" allowfullscreen src="https://blackfire.io/profiles/compare/faa3c421-ea79-40e3-af39-f0c799df9414/embed"></iframe>

https://blackfire.io/profiles/compare/faa3c421-ea79-40e3-af39-f0c799df9414/graph

P.S.
Not sure how log link would work considering that I'm using Free account with 1 day profile retention.

**Comment by aik099** [comment]
I guess this issue haven't made it into http://symfony.com/blog/symfony-2-8-7-released .

**Comment by stloyd** [comment]
@aik099 It is there, it's just not mentioned in the blog post (somehow missed ;))

Cause if you click on the commit of merge: https://github.com/symfony/symfony/commit/83e24bab6d17456f382ff249fff7bf497a77e1da you can notice at the bottom of message where it was merged & where it exists (and there are tags: `v3.0.7  v2.8.7 v2.7.14`).
