### ISSUE TITLE
Problème de classe manquante sur débogage d'environnement de production (théorique)

### ISSUE THREAD

**Issue by mantissefr** [symfony/symfony#18955]
Bonjour,

Je suis un développeur Symfony en progression et je m'intéresse au débogage d'un environnement de production.

C'est à dire que j'ai indiqué comme paramètre dans le fichier ~/app/AppKernel.php, le paramètre :

`$kernel = new AppKernel('prod', true);`

Afin de corriger des erreurs 500.

Je ne comprends pas le message d'erreur de chargement de classe que je reçois alors :

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Unable to load class "Psr\Cache\CacheItemInterface in in /home/###/www/symfony/prod/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:265 Stack trace: #0 "'

alors que seul le paquetage psr\log est requis par Symfony.

Est-ce que c'est un problème qui vient de moi ?

Sincères salutations,

Mantisse
![github](https://cloud.githubusercontent.com/assets/10047653/15753590/21727074-28f4-11e6-8345-21c1395daea8.png)

**Comment by jakzal** [comment]
Please use English, many of us don't know French ;)

Also, please note that we only use github for development. If you have a problem with Symfony and need help, use one of the official support channels: http://symfony.com/support

**Comment by mantissefr** [comment]
Hello there jakzal,

I am a developper for fun not in my job even if I would like to do both.

I don't understand why I get : 

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Unable to load class "Psr\Cache\CacheItemInterface in in /home/###/www/symfony/prod/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:265 Stack trace: #0 "'`

when only package psr\log is needed.

**Comment by mantissefr** [comment]
I had to add :

`"psr/cache":"1.0.*"`

to composer.json and update with a classic :

php composer.phar update.

Do I have to ask for a pull request directly in composer.json or does someone know more than me about if Symfony on PSR-6.

**Comment by mantissefr** [comment]
Oh sorry, I thought I was using symfony 2.8.* whereas I am using symfony 3.2-dev.

I am going to try to close this now.
