### ISSUE TITLE
Empty session in AbstractFormLoginAuthenticator of Guard

### ISSUE THREAD

**Issue by Shekhovtsovy** [symfony/symfony#18958]
Sometimes $request maybe with empty session: `[session:protected] => `

```
  $targetPath = $this->getTargetPath($request->getSession(), $providerKey);
        if (!$targetPath) {
            $targetPath = $this->getDefaultSuccessRedirectUrl();
        }
```
I had `Catchable fatal error:  Argument 1 passed to Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator::getTargetPath() must be an instance of Symfony\\Component\\HttpFoundation\\Session\\SessionInterface, null given`

Maybe better to do something like below

```
        $session = $request->getSession();       
        if ($session instanceof SessionInterface) {
            $targetPath = $this->getTargetPath($session, $providerKey);
        }
        if (!isset($targetPath) || !$targetPath) {
            $targetPath = $this->getDefaultSuccessRedirectUrl();
        }
```

**Comment by pasdeloup** [comment]
I couldn't reproduce.
What do you mean by "Sometimes"?
Does it happen randomly or when using a special configuration?

Using the Symfony full stack it seems hard to not have session at all (different from having an empty session). 
If I'm not wrong, it would mean the session service doesn't exist, or the firewall listener is called before the session listener.

**Comment by pasdeloup** [comment]
Or maybe you are only using some components?

**Comment by Shekhovtsovy** [comment]
Im use symfony security component (with present http/firewall, http/firewallMap, GuardAuthenticationListener which includes `class FormLoginAuthenticator extends AbstractFormLoginAuthenticator implements GuardAuthenticatorInterface`) separately without whole framework.
Everytime I must put SessionInterface object in request even if I dont use session in module. I think,  it's not a bug, but improvement which will make the classes more independent.

**Comment by pasdeloup** [comment]
Ok, it makes more sense.
I was trying to find a bug using full stack.

You should make a PR for your fix. Or I can work on it if you don't have time.
