### ISSUE TITLE
Need to update packagist 2.8.* 

### ISSUE THREAD

**Issue by mantissefr** [symfony/symfony#18956]
Hello,

On packagist, symfony/framework-standard-edition 2.8.6 gives a dependency on symfony/symfony version 2.8.*.

symfony/symfony version 2.8.6 composer.json has been updated with PSR-6 (symfony 3.2) dependency but packagist does not reflect that for the moment.

Is it a too soon PR as I manually updated my composer vendor tree with symfony version 2.8.6 with git ?

Mantisse

**Comment by xabbuh** [comment]
I am not sure if I understand what you mean. The Cache component was introduced with 3.1 and is not part of Symfony 2.8.

**Comment by WouterJ** [comment]
But please note that the Cache component has no Symfony dependencies and you can require the component by adding `symfony/cache` to your dependencies. You won't get the PSR-6 integration in the FrameworkBundle though.

**Comment by mantissefr** [comment]
@xabbuh look at composer.json in version 2.8.6 which includes psr/cache now in symfony/symfony package.

**Comment by WouterJ** [comment]
I'm sorry, but Ican't find a `psr/cache` dependency in the `composer.json` onf 2.8.6: https://github.com/symfony/symfony/blob/v2.8.6/composer.json

Nor does it exists in 2.8.7-DEV: https://github.com/symfony/symfony/blob/2.8/composer.json

**Comment by mantissefr** [comment]
Found this link from the official package
https://github.com/symfony/symfony/blob/master/composer.json
but got it wrong, I was on version 3.2.

newbie GIT on github : got it wrong.

Closing again now.

**Comment by WouterJ** [comment]
No problem :) You can use the switcher on the top left in the github code view to switch to specific tags (releases) or branches (dev versions).
