### ISSUE TITLE
How to set choice values in twig?

### ISSUE THREAD

**Issue by dialogik** [symfony/symfony#18950]
I am using a `ChoiceType` in a Symfony3 form type

    $builder
        ->add('confirmation', ChoiceType::class, array(
            'choices'  => array(
                'Maybe' => null,
                'Yes' => true,
                'No' => false,
            )
    ))

Now I want to set `choices` dynamically in twig. I would assume to go like this

    {{ form_widget(field.type, {'choices': {'foo': true, 'bar': false}}) }}

but that throws error

> Impossible to access an attribute ("attr") on a boolean variable ("1") in form_div_layout.html.twig at line 82

Is there any way to set choices in twig (while rendering the form field using `form_widget()` or `form_row()`)?

**Comment by stof** [comment]
no you cannot, because choices impact the building of the form. They are not passed as is to the template (they main goal of the Form component is not to handle the rendering, but to handle the form binding)

**Comment by javiereguiluz** [comment]
Closing this issue because, apparently, this "limitation" is instead a "feature".
