### ISSUE TITLE
Disable WebDebugToolbarListener on download

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18965]
I'm offering an html file up for download. And in debug mode the toolbar is injected. Perhaps check for content-disposition and attachment too?

**Comment by iltar** [comment]
Could indeed hook in here and check if there's additional headers present: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L116

**Comment by peterrehm** [comment]
Just provided a fix for that case.
