### ISSUE TITLE
Yaml parser can't parse JSON

### ISSUE THREAD

**Issue by kelunik** [symfony/symfony#18968]
According to http://www.yamllint.com/ the following is a valid `.yml` file.

```yml
storage: /etc/acme
server: letsencrypt
certificates: [
    {
        "paths": {
            "/tmp": ["docs.example.org", "git.example.org"]
        }
    }
]
```

Instead of parsing successfully, the parser throws an exception.

```
Malformed inline YAML string [ at line 3 (near "certificates: [")
```

**Comment by javiereguiluz** [comment]
The official YAML spec states that [ben-kiki.org/ypaste](http://ben-kiki.org/ypaste/) is the reference Yaml parser. If you try it with your document, it shows two "unexpected" errors:

![yaml_spec_error](https://cloud.githubusercontent.com/assets/73419/15801246/a5e0470e-2a8f-11e6-842a-361031a23496.png)

**Comment by iltar** [comment]
This seems to work though:

```yml
storage: /etc/acme
server: letsencrypt
certificates: |
    [
        {
            "paths": {
                "/tmp": ["docs.example.org", "git.example.org"]
            }
        }
    ]
```

**Comment by xabbuh** [comment]
@iltar In your example, the value of the `certificates` key will be a string.

Indeed, spanning maps or sequences over multiple lines currently is not supported by the YAML parser when using `{`/`[` to start a mapping/sequence (we only support them for the inline notation). Right now I don't see how we could add this to the parser without reworking much of it. But if someone can come up with a straightforward fix, I will be happy to merge such a PR.

**Comment by fabpot** [comment]
I'm :-1: to support this feature, as the following is visually the same as the above example, with less chars and already supported:

```yaml
"paths":
     "/tmp": ["docs.example.org", "git.example.org"]       
```

For the record, supporting 100% of the YAML spec this has never been our goal.

**Comment by scaytrase** [comment]
Hi, is this still a case? YAML is the superset of JSON and here in 2018 I still can't pase JSON with symfony 4.2.1 `YAML::parse` call with the same error:

```
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 1 (near "{"). in /local/vendor/symfony/yaml/Parser.php:382
Stack trace:
#0 /local/vendor/symfony/yaml/Parser.php(95): Symfony\Component\Yaml\Parser->doParse(' {', 0)
#1 /local/vendor/symfony/yaml/Yaml.php(79): Symfony\Component\Yaml\Parser->parse('{\n  "consumes":...', 0)
```

My goal is to parse the OpenAPI schema which could be YAML or JSON (which is actually valid YAML too as the definition of YAML stands) without trying to detect which certain language I got.

JSON is fully valid YAML object, while can't it be parsed?
