### ISSUE TITLE
Inherited methods in API docs

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18963]
Would like to see inherited methods in https://symfony.com/doc/current/components/finder.html from https://secure.php.net/manual/en/class.splfileinfo.php now i have to search in two places.

**Comment by Tobion** [comment]
This is a documentation issue https://github.com/symfony/symfony-docs

**Comment by flip111** [comment]
documentation says it's a symfony issue https://github.com/symfony/symfony-docs/issues/6534#issuecomment-220802792

**Comment by Tobion** [comment]
In the docs you linked the API docs, here you link the component docs. So it's not clear what you want. Btw, one sentence to describe the problem and the expected behavior is usually not enough.

**Comment by xabbuh** [comment]
If I understand you correctly, this is coming from Satis which does not render the docblocks of parent classes (at least when they are built-in core classes). Not sure what we can do about that in Symfony itself or in its docs.

**Comment by flip111** [comment]
oh yes sorry i copy paste from the wrong tab, i edit my first post
