### ISSUE TITLE
[PropertyAccess] [Bug] isReadable return true for an array index even if not set.

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#18969]
Description
----------------

Let's take the following empty array:

```php
$array = array();
```

And the following empty class:

```php
$object = new class {};
```

Check if an undefined property is readable from the class:

```php
$accessor = PropertyAccess::createPropertyAccessor();
$accessor->isReadable($object, 'foo'); // false
```

Same check on the array:

```php
$accessor = PropertyAccess::createPropertyAccessor();
$accessor->isReadable($array, '[foo]'); // true
```

As `$array['foo']` doesn't exist, I assume it's a bug, right?

Possible solution
-----------------------

In `PropertyAccessor::readIndex`, in the following condition:

```php
if (isset($zval[self::VALUE][$index])) {
    $result[self::VALUE] = $zval[self::VALUE][$index];

    if (!isset($zval[self::REF])) {
        // Save creating references when doing read-only lookups
    } elseif (is_array($zval[self::VALUE])) {
        $result[self::REF] = &$zval[self::REF][$index];
    } elseif (is_object($result[self::VALUE])) {
        $result[self::REF] = $result[self::VALUE];
    }
}
```
Add an `else` statement like:

```php
if (isset($zval[self::VALUE][$index])) {
    // ...
} else {
    throw new NoSuchIndexException(...);
}
```

Sort as `isReadable` properly returns `false` on unreadable index.

**Comment by chalasr** [comment]
If the bug is confirmed, I have a ready patch.

**Comment by sstok** [comment]
When you call `getValue()` does it give an exception in this case? (non-existing key).

**Comment by chalasr** [comment]
@sstok, for $array it gives NULL, fot $object, it throws an exception saying that no getter/isser/hasser found.

**Comment by sstok** [comment]
OK, so it's directly confirmable. Hmm..

**Comment by chalasr** [comment]
@sstok It seems that tests expect this behavior. That sounds strange to me, looks like for you too.

**Comment by chalasr** [comment]
After investigation, it's the expected behavior. The second argument of `PropertyAccessor::__construct()` determines if exceptions should be thrown or not, if it is set to true, isReadable properly returns false.
I'll close this issue, the attached PR, then open a new PR to allow passing this argument in PropertyAccess::createPropertyAccessor` (e.g. `createPropertyAccessor($throwExceptionOnInvalidIndex = false)`).

**Comment by khusseini** [comment]
May I ask how this was decided? I find it a bit confusing that the exceptions differ from objects and arrays.

**Comment by xabbuh** [comment]
There was nothing to change as this is the expected behaviour (accessing non-existing array keys just returns `null`, see http://symfony.com/doc/current/components/property_access.html#reading-from-arrays).

**Comment by Vorotyagin-Anton** [comment]
`$accessor->isReadable($array, '[foo]'); // true`

**Comment by Vorotyagin-Anton** [comment]
It can be useful with multidimensional array.
```
$array = array();
$accessor->isReadable($array, '[foo]'); // true
$accessor->isReadable($array, '[foo][bar]'); // false
```

Because
```
$array = array();
$accessor->getValue($array, '[foo]'); // null
$accessor->getValue($array, '[foo][bar]'); // Exception\UnexpectedTypeException - "PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "[foo][bar]" at property "bar"."
```
