### ISSUE TITLE
Symfony Assert Choices with 0 value always valid

### ISSUE THREAD

**Issue by gusdecool** [symfony/symfony#18973]
Tested using Symfony 2.3

create an entity with assert choice, example:

```php
class PaymentGateway 
{
    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     *
     * @Assert\NotNull()
     * @Assert\Choice(choices={"stripe"})
     */
    private $type;
}
```

Now test the entity and set the value to 0
Example i test in controller

```php
    /**
	 * @Route("/test/yo")
	 */
	public function testDumpAction()
	{
		$paymentGateway = new PaymentGateway();
		$paymentGateway->setType(0);

		$errors = $this->get('validator')->validate($paymentGateway);
		var_dump($errors); // examine the dump value, there is no violations

		return new Response('ok');
	}
```

**Comment by peterrehm** [comment]
@gusdecool The choice validator is not strict by default. You need to set the strict option to avoid such issue. This is related to the behaviour of the php in_array function.  (Background information http://stackoverflow.com/a/13846839 / http://php.net/manual/en/function.in-array.php)

Once you enable the strict mode everything should work as intended.

/cc @javiereguiluz Does it make sense to enable strict by default? This is actually a nasty pitfall.

**Comment by peterrehm** [comment]
Any feedback whether we should change the general behaviour?

**Comment by xabbuh** [comment]
@peterrehm Enabling strict mode by default changes the default behaviour and thus would be a BC break to me.

**Comment by peterrehm** [comment]
To me if possible it might make sense to break BC as this is a bug from the user perspective. You would never expect it to behave this way.

**Comment by ro0NL** [comment]
I think the `strict` option should be removed here.. (ie force it hardcoded). Like @peterrehm states.. from a  user pov you just expect the value to be one of.

**Comment by peterrehm** [comment]
I would say in all cases it is a nasty bug if 0 is valid if there is not an element with the key 0.

**Comment by gusdecool** [comment]
Thanks @peterrehm , i were adding `@Assert\Type("string")` to resolve my issues. But use case wise, this definitely a bug, if it's the bug `in_array`, probably we should not used `in_array` and change into something else.

**Comment by peterrehm** [comment]
ping @symfony/deciders

**Comment by xabbuh** [comment]
We could think about deprecating other values thank true for the strict option and then entirely deprecate it in 4.1.

**Comment by peterrehm** [comment]
The question is are there use cases where this is wanted?

**Comment by peterrehm** [comment]
Another option might be a special handling for the value `0`.

**Comment by ro0NL** [comment]
Also note the current behaviour, as far as i can see, already differs from the built-in validation for the `ChoiceType` from the form component (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L127) by using `isset`.

**Comment by peterrehm** [comment]
@ro0NL That is the behaviour of the choice type but this issue is about the choice constraint.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L186 is to check if an option is selected in case of multiple.

And https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L127 is just a sanity check if the returned options are matching the configured ones. I assume this is as the validator component is decoupled from the form component. (https://github.com/symfony/form/blob/master/composer.json#L28)

**Comment by ro0NL** [comment]
Just saying the logic for `is choice in choices` differs (constraint vs form) ;-)

**Comment by peterrehm** [comment]
I think we have 3 choices.

1. Introduce as BC break by setting strict by default to true and optionally deprecate the false option with targeting 3.2 as we can provided a proper upgrade path. I think this should be inline with the maintenance guidelines as this can be considered as bug with almost no effect

2. Introduce a special handling for the value 0 when the mode is not strict which could also cause bc breaks.

3. Deprecate the Option in 3.2 and switch the default option only in 4.0

I would lean towards option 2. If you agree I would have a look into it.

/ping @symfony/deciders

**Comment by ro0NL** [comment]
3 sounds nice.. imo we should avoid "special handling". You go strict or loose on this, not loose except for 0 (if i understand correctly). Transforming/normalizing is not its job, again imo.

**Comment by xabbuh** [comment]
The only viable option for me is 3.

**Comment by peterrehm** [comment]
Again I think a special handling might make also sense due to this:

````php
$test = ['option1', 'option2'];
var_dump(in_array(0, $test));
# bool(true)
php > var_dump(in_array(1, $test));
bool(false)
````

This is nothing but expected PHP behaviour, but this can and will lead to nasty bugs. To be honest I had to update a production app after taking care of that issue.

After reconsideration I am more against making it all strict as you might want e.g. even though this can be a special case:

````php
$test = ['1', '2'];
var_dump(in_array(1.00, $test));
# bool(true)
````

So to me option 2 is actually the only really viable solution.

**Comment by ro0NL** [comment]
We fixed production bugs due to loose in_array.. from that day on we went **strict** by default, and loose by exception (with a comment ;-)) and never looked back. It's way more reliable...

**Comment by peterrehm** [comment]
Jep, but I think the real issue is only with 0. I can't think of any data where this behaviour will be right.

**Comment by ro0NL** [comment]
If 0 not being actually option, then yes, the only issue input-wise is 0. If 0 _is_ an option though we have more, eh, issues: https://3v4l.org/Gklbs

**Comment by peterrehm** [comment]
Okay, I am all in for making strict the default behaviour... :) Will open a PR shortly.

**Comment by peterrehm** [comment]
@ro0NL Just provided a PR for further discussion with new options...
