### ISSUE TITLE
[polyfill-iconv] iconv does not work with argument TRANSLIT//IGNORE

### ISSUE THREAD

**Issue by ludekvesely** [symfony/symfony#18984]
Hi, I have a problem with `polyfill-iconv` which does not work correctly. I'm not able to use it with Nette framework - method [Strings::webalize](https://github.com/nette/utils/blob/master/src/Utils/Strings.php#L185) which calls function `iconv` fails:

```php
$s = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $s);
```

Problem is in order `TRANSLIT` and `IGNORE` - if `IGNORE` is before `TRANSLIT`, it works. I've forked polyfill-iconv repo and [fixed this problem](https://github.com/ludekvesely/polyfill-iconv/commit/246a7512cd1d6a69beb7e8953895daaa55bfe499), but not sure if it is good solution - this will not work with `IGNORE//TRANSLIT` parameter. 

I'm using this library because function `iconv` doesn't work on Alipne Linux - [this is original issue](https://github.com/nette/utils/issues/109).

**Comment by Tobion** [comment]
Please open the issue at https://github.com/symfony/polyfill. Thanks

**Comment by nicolas-grekas** [comment]
@ludekvesely please have in mind that several iconv implementation exist. I may be wrong, but the current behavior of the polyfill is in line with the iconv implem that is bundled on Windows.
If that's the case, then maybe patching Nette would be wise.
But as stated by @Tobion , please open your issue on https://github.com/symfony/polyfill. thanks
