### ISSUE TITLE
[Form] Collection FormType with a all fields disabled is deleted at submit

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#18998]
If i have this FormType, for EntityA :
```php
class FormTypeA extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('my_collection', CollectionType::class, [
            'entry_type' => FormTypeB::class
        ]);
    }
}
```

And this one, for EntityB :
```php
class FormTypeB extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('field', TextAreaType::class, [
            'disabled' => true
        ]);
    }
}
```

When i submit my form, "all" EntityB are removed from my database => that's not what i expect, i just want to not save any modification on "field".

If i add another field into FormTypeB, "who is not disabled", nothing is removed, disabled does it's job (don't save any modification into this disabled field), that's fine.

If i add another field into FormTypeB, "who is disabled", same problem : when i submit my form, "all" EntityB are removed from my database => that's not what i expect

**Comment by iltar** [comment]
As far as I know, disabled fields are not send to the server by browsers, can you verify that?

**Comment by raziel057** [comment]
Yes indeed, I also encountered this issue recently. As no data is sent, it's considered that the item of the collection has been removed. As a workaround you can just add an Hidden field (not disabled) in the FormTypeB to make the distinction between item with all fields disabled and item deleted.

**Comment by iltar** [comment]
Or you stop binding your entities directly onto your form and you use data transfer objects: http://blog.iltar.nl/posts/733915-avoiding-entities-in-forms

**Comment by steevanb** [comment]
@iltar : you're right, they are not sent by browser. So, i understand the problem ... But to mee, that's a bug.
I've read your link, but honestly, i don't see how it can help me. And that's too much code, for nothing, in my opinion.

@raziel057 : that's what we do, with ah hidden not mapped field. But that's not a "perfect" solution.

**Comment by iltar** [comment]
@steevanb because right now you're relying on the forms to put your entities in a valid state and as you can see, that doesn't happen. It's not too much code for nothing, it's making sure the code does what you want it to do.

**Comment by HeahDude** [comment]
Have you tried using PATCH method ? It should prevent it by using the `$clearMissing` parameter. You can also try to hardcode `Form::submit($data, $clearMissing)` instead of relying on `Form::handleRequest()` in your controller.

**Comment by xabbuh** [comment]
@steevanb Did @iltar's and @HeahDude's comments help you solve your problem?

**Comment by steevanb** [comment]
@xabbuh : not really. i agree with their methods, but to me, that's not a "solution", that's a bug. i solve it by adding an hidden, not mapped field in each collection. with this field, there is 1 field sent instead of 0, so my collection isn't deleted.

**Comment by HeahDude** [comment]
@steevanb I haven't been able to reproduce your bug neither on 2.7 nor 2.8 with FQCN and `entry_type` option.

Could you please try add the minimum of code to a fork of symfony-standard to reproduce it?
Thanks!

**Comment by HeahDude** [comment]
Hey! Any news here?

**Comment by jakzal** [comment]
Let's close. We'll reopen once anyone's able to reproduce this issue.

**Comment by albawan** [comment]
I had the same issue like this in Symfony 4. Got around it by setting a 'readonly' attribute.

**Comment by charlyox** [comment]
Have same issue on SF 2.6, when orphanRemoval="true" was set on parent's oneToMany attribute. Had to set one of the child collection fields to read_only instead of disabled.
