### ISSUE TITLE
Segmentation Fault with PHPUnit and the bridge

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#18996]
My project is running under PHP7 inside Docker:

```
PHP 7.0.7 (cli) (built: May 28 2016 00:32:37) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

Test suites work great, but if I add `symfony/phpunit-bridge:^3.1`, this goes to this bug:

```bash
root@1dc91cfa2dcc:/code# ./bin/phpunit --debug
Segmentation fault (core dumped)
```

I don't know if it's strongly related to your lib or PHP, so I start opening an issue here.

Note: I tested it with PHP 7 outside Docker, directly on my host. I got more verbosity but this does not explain the segfault IMHO:

```bash
sullivan@sweetnexy:~/projects/project/(master)$ ./bin/phpunit 
PHP Fatal error:  Uncaught Declaration of Tests\AppBundle\Admin\IncidentAdmin::testToString() should be compatible with Tests\AppBundle\Admin\AbstractAdminTest::testToString($objectDescription, $expectedToString)

/home/sullivan/projects/project/tests/AppBundle/Admin/IncidentAdminTest.php:68
/home/sullivan/projects/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:72

  thrown in /home/sullivan/projects/project/tests/AppBundle/Admin/IncidentAdminTest.php on line 68
Segmentation fault (core dumped)
```

Solving the fatal error is resolving the Segmentation fault but I don't think this should end like this.

**Comment by nicolas-grekas** [comment]
Segfault are on PHP side, not symfony's...

**Comment by Soullivaneuh** [comment]
@nicolas-grekas I agree, but I have this segfault only when I require phpunit-bridge.

Any idea? I opened this issue because of this. :-/

**Comment by nicolas-grekas** [comment]
No idea really, I don't debug segfaults :)
Please submit an issue on PHP with a simple reproducer if you can get one.

**Comment by AboElnuoR** [comment]
I had had the same problem.
Then I found this solution
https://stackoverflow.com/a/39258774/6163727
