### ISSUE TITLE
England is missing in CountryType

### ISSUE THREAD

**Issue by bettinz** [symfony/symfony#18993]
Hello, I'm using Symfony 3.1 and in CountryType list I can't find England.
There is The United Kingdom but England is missing. Is it a known issue?

Thanks

**Comment by stof** [comment]
England is not part of the ICU list of countries, which is why it is not here.

**Comment by bettinz** [comment]
Do you have any link about this ICU list? I'm not sure to understand why England is not part of this, since England is a state and United Kingdom is a Union of States

**Comment by stof** [comment]
In ISO standards, England, Wales and Scotland are registered as being nations which are a subdivision of UK. But the country is listed as being UK (England is not a sovereign state anymore since centuries)

**Comment by bettinz** [comment]
Thank you for the explanation
