### ISSUE TITLE
[Forms] Forms no longer submit in 2.8 unless I explicitly set their 'action' on createForm()

### ISSUE THREAD

**Issue by kcaporaso** [symfony/symfony#19000]
Prior to 2.8 my forms would submit fine coded as follows:
In controller:
```
$company = new Company();
$form = $this->createForm(CompanyType::class, $company);
// using @Template()
return [
    'form' => $form->createView()
];
```
Then twig rendering:
```
{{ form_start(form) }}
 // .. render other elements using form_row(form.title), etc...
<input type="submit" name="save" value="Save">
{{ form_rest(form) }}
{{ form_end(form) }}
```
Clicking the Save button would submit the form to the appropriate indexAction() defined with @Route.
However, after upgrading to 2.8 now the form doesn't even POST.
Only if I update my createForm(...) like below and explicitly set the 'action' it will work, but I don't want to update 30-50 forms.
```
$form = $this->createForm(CompanyType::class, $company, [
      'action' => $this->generateUrl('company_create'),
]);
```
Is this a new BC break from 2.7 to 2.8? Did I missing something else in the documentation?
This is not a nesting of forms either, it's a single form.  Appreciate any advice on this one.

For giggles:
```
friendsofsymfony/jsrouting-bundle      1.6.0               A pretty nice way to expose your Symfony2 routing to client app...
friendsofsymfony/user-bundle           dev-master d1fccc6  Symfony FOSUserBundle
symfony/assetic-bundle                 v2.8.0              Integrates Assetic into Symfony2
symfony/monolog-bundle                 2.11.1              Symfony MonologBundle
symfony/polyfill-apcu                  v1.2.0              Symfony polyfill backporting apcu_* functions to lower PHP vers...
symfony/polyfill-intl-icu              v1.2.0              Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring              v1.2.0              Symfony polyfill for the Mbstring extension
symfony/polyfill-php54                 v1.2.0              Symfony polyfill backporting some PHP 5.4+ features to lower PH...
symfony/polyfill-php55                 v1.2.0              Symfony polyfill backporting some PHP 5.5+ features to lower PH...
symfony/polyfill-php56                 v1.2.0              Symfony polyfill backporting some PHP 5.6+ features to lower PH...
symfony/polyfill-php70                 v1.2.0              Symfony polyfill backporting some PHP 7.0+ features to lower PH...
symfony/polyfill-util                  v1.2.0              Symfony utilities for portability of PHP codes
symfony/process                        2.6.x-dev 57f1e88   Symfony Process Component
symfony/security-acl                   v3.0.0              Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle             v2.3.11             Symfony SwiftmailerBundle
symfony/symfony                        v2.8.7              The Symfony PHP framework
symfony/yaml                           2.6.x-dev c044d17   Symfony Yaml Component
```

Regards,
Kevin

**Comment by xabbuh** [comment]
Can you please fork the Symfony Standard Edition and make the minimum set of changes that is required to reproduce your issue?

**Comment by kcaporaso** [comment]
@xabbuh , sorry I'm not following you. Maybe you mean install the Symfony SE and see if a virgin install has the same behavior?  If that's not what you mean please let me know.

**Comment by kcaporaso** [comment]
@xabbuh, so I set up a virgin 2.8 SE and the form behaves properly.  Meaning with these minimal pieces the form submits as it should.
```
     /**
     * @Route("/form")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isValid()) {
            echo ' Is valid after submit ';
        }

        return [
            'form' => $form->createView(),
        ];
    }
```
Twig:
```
 {{ form_start(form) }}
 {{ form_widget(form) }}
 <input type="submit" value="Save" name="save">
 {{ form_end(form) }}
```

Good for Symfony, bad for me as I still have to determine what's breaking it in my massive project. 
Regards,
Kevin

**Comment by xabbuh** [comment]
You could turn off some other bundles you make use of to check if the new behaviour is related to them. Though I don't think that this is related to Symfony itself at all.

**Comment by xabbuh** [comment]
@kcaporaso Any news here? :)

**Comment by jakzal** [comment]
Closing as it's apparently end user's mistake. @kcaporaso if you think this is really a bug, we will reopen this issue once you provide details how to reproduce it on Symfony SE.

**Comment by kcaporaso** [comment]
@jakzal , thanks guys, honestly, I had to just go back to 2.7 until I find the time to debug what bundle was causing this issue.  I'll get there at some point and will update this thread at that time.  Obviously others haven't reported hitting the conflict, so it's clearly something specific to my bundle collection.

**Comment by kcaporaso** [comment]
@jakzal , @xabbuh I finally circled back around on this one.  The issue shows up when using symfony 2.8+ and AngularJS (at least up to AngularJS v1.4.12).  The 2.8 change that seems to be related is this one: https://github.com/symfony/symfony/issues/13852, essentially, an empty 'action' is no longer being rendered in the form.

So, the workaround when using AngularJS and symfony 2.8+ is to add the following to your twig template:
```
// before 2.8
form_start(form)

// after 2.8
form_start(form, { attr: {'action':''}})
```

This is really only going to be required if you're not actually setting the 'action' item on your form, explicitly. I hope this helps someone else moving from symfony 2.7 and beyond.
