### ISSUE TITLE
Improve error when a template extends from itself

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#19018]
As reported here https://github.com/symfony/symfony-installer/issues/258 if one of your templates extends by mistake from itself, you get a brutal "Segmentation fault" error instead of an informative error message. Would be easy to add this check somewhere and avoid this situation? Thanks!

**Comment by nicolas-grekas** [comment]
I'm sorry but segfault are not our duty...

**Comment by fabpot** [comment]
I don't agree. Here, the user made a mistake in the PHP code by using a template that extends itself. That being said, I think we already had some similar reports and we did not find an easy/simple and fast way to do a check.

**Comment by fabpot** [comment]
... which would be a Twig issue anyway.
