### ISSUE TITLE
PR d83e346 breaks YAML parsing

### ISSUE THREAD

**Issue by userfriendly** [symfony/symfony#19023]
lint:yaml complains about a YAML file not being valid under certain circumstances since commit d83e346 by @paradajozsef 

Example file:
https://github.com/liuggio/ExcelBundle/blob/excel-forks/Resources/config/services.yml

In this case the error message mentions line 91. The issue appears to be related to a commented line following an array. When a blank line is inserted after line 89, before the comment in line 90, the error message is gone.

**Comment by paradajozsef** [comment]
@userfriendly The link is broken, could you fix it?

**Comment by userfriendly** [comment]
Fixed. Sorry about that.

**Comment by paradajozsef** [comment]
I can confirm it, thx for reporting!

Status: Reviewed.

**Comment by xabbuh** [comment]
If I am not mistaken, the even didn't work before. Can you confirm that?

**Comment by xabbuh** [comment]
@userfriendly Can you please check if #19028 fixes the issue for you?

**Comment by userfriendly** [comment]
@xabbuh Yes, that does make lint:yaml very happy. :+1:

**Comment by xabbuh** [comment]
@userfriendly Thanks for the confirmation.

**Comment by paradajozsef** [comment]
@xabbuh Thank you very much for fixing this!

**Comment by userfriendly** [comment]
@awolder @DeVelbeck please keep an eye on this while I'm in Germanland. Cheers!
