### ISSUE TITLE
Base YAML config.yml file not parsing correctly?

### ISSUE THREAD

**Issue by thenetimp** [symfony/symfony#19024]
I just used the "symfony new 2.8" command to pull a fresh version of 2.8.  When I go to my browser I get a 500 reset connection error.  I get no errors in any log files, and with display_errors = On I get no feedback from the application.  This is with php 2.5 and Apache 2.4.7

I have also tried by using the composer command to install Symfony 2.8 and I get the exact same issue.  

I traced through the class files and got as far as the YamlFileLoader but wasn't able to sort out the exact issue.  

Thoughts?

**Comment by PavelPetrov-WebBambooLtd** [comment]
Sounds like a permission issue to me. Can you try http://symfony.com/doc/current/book/installation.html#book-installation-permissions

**Comment by PavelPetrov-WebBambooLtd** [comment]
Also keep in mint that the command "symfony new 2.8" will install Symfony 3.1 in a folder named "2.8".

What is the PHP version you're running?

**Comment by javiereguiluz** [comment]
@thenetimp you must execute `symfony new project_name 2.8` instead of `symfony new 2.8`

**Comment by thenetimp** [comment]
sorry that's what I did.  I had the project name there, I spent 2 hours trying to debug it and forgot the exact command.

**Comment by thenetimp** [comment]
Apache runs as vagrant user.  the cache and log directories are owned by the vagrant user.  When I change them to be owned by root I start getting symfony errors that they can't be written too.  I don't think it's a permissions problem

**Comment by PavelPetrov-WebBambooLtd** [comment]
@thenetimp If you make them owned by root Sf will not be able to write there for sure.
Just for testing try:
```
sudo chmod -R 777 var/cache
sudo chmod -R 777 var/logs
```

That will for sure proove if it is permission related

**Comment by thenetimp** [comment]
tried that as well.

**Comment by PavelPetrov-WebBambooLtd** [comment]
@thenetimp What does 
`php bin/symfony_requirements`
say?

**Comment by thenetimp** [comment]
`php app/SymfonyRequirements.php`

returns nothing

**Comment by PavelPetrov-WebBambooLtd** [comment]
@thenetimp The code you're pasting is wrong
`php bin/symfony_requirements`

not

`php app/SymfonyRequirements.php
`

**Comment by PavelPetrov-WebBambooLtd** [comment]
@thenetimp My bad that command is for 3.1

`php app/check.php`

**Comment by thenetimp** [comment]
`[OK] Your system is ready to run Symfony projects`

**Comment by PavelPetrov-WebBambooLtd** [comment]
I just realized that because you're running 2.8 not 3.1 the commands I gave you earlier also do not work. They should be:

```
sudo chmod -R 777 app/cache
sudo chmod -R 777 app/logs
```

When check.php returns no problem, the odds are that it is permissions...

**Comment by thenetimp** [comment]
yes I realized the commands you gave me were wrong and I corrected them as I went along.  It is not a permissions problem.  The directory is writable to Symfony.  When I force the directories to be incorrect for writing Symfony actually gives me an error.

**Comment by PavelPetrov-WebBambooLtd** [comment]
I'm out of ideas :)

**Comment by thenetimp** [comment]
Still not fix to my problem but I wanted to see if I could get older versions to install.

2.3, 2.4, 2.5 all install and display the basic screen you get when you install them. only issue is in 2.5 lots of broken links, but symfony itself response.

2.6, 2.7 and 2.8 all have the same issue.  So it must be something that changed in 2.6, so I'll start reading the change logs there and see if I can figure something out.

**Comment by thenetimp** [comment]
and just like that things magically start working.... wth....  I quit...

**Comment by javiereguiluz** [comment]
@thenetimp reading your last comment it seems that the issue was fixed. I'm glad this is now working even if you don't know the exact reason. Therefore, I'm closing this issue as "fixed". Thanks!
