### ISSUE TITLE
[Form] Customising rendering of a single field not working as documented

### ISSUE THREAD

**Issue by gerryvdm** [symfony/symfony#19021]
I have the following template:

``` twig
{% form_theme form _self %}

{% block _myform_categories_widget %}
    foo
{% endblock %}

{{ form_widget(form.categories) }}
```

The `form_widget()` functions successfully renders `foo`, but the problem is that the block itself is rendered as well on top of the template, so in this example the output is `foo foo`.

**Comment by PavelPetrov-WebBambooLtd** [comment]
@gerryvdm I think maybe also the label gets rendered?
Maybe:
`{% form_theme form _self %}

{% block _myform_categories_widget %}
    <div class="name_row">
        labelfoo
        {{ form_errors(form) }}
        foo
    </div>
{% endblock %}

{{ form_row(form.categories) }}`

**Comment by xabbuh** [comment]
That's how Twig is supposed to work. Blocks only won't be displayed if your template extended another template.

**Comment by javiereguiluz** [comment]
@xabbuh but @gerryvdm is using [the exact same code explained](http://symfony.com/doc/current/cookbook/form/form_customization.html#how-to-customize-an-individual-field) in the Symfony Docs:

![custom_field](https://cloud.githubusercontent.com/assets/73419/15999052/258468aa-3143-11e6-82cb-4bef918fc3ce.png)

Is this a doc issue then?

**Comment by xabbuh** [comment]
@javiereguiluz Yeah, I think we need to make this more clear in the docs.

**Comment by mvrhov** [comment]
No. This did work. Something else has changed.

**Comment by xabbuh** [comment]
@mvrhov Do you know in which version this used to work?

**Comment by mvrhov** [comment]
Can this wait till Tuesday. I have one project on 2.8 and I can check. It this still works there.

**Comment by xabbuh** [comment]
@mvrhov Any news here?

**Comment by mvrhov** [comment]
I did try it 2.8 don't remember the exact version and it didn't work. So This was probably broken a long time ago. 
IMO it would still be nice to fix this and NOT documentation.

**Comment by mvrhov** [comment]
@xabbuh
I'm going to recant my previous message. I don't know how I've run the test previously on my project, but In the past 2 hours I've run the test on standard edition starting with 2.7.0 and the worked it up to 3.2.0

What does in fact happen is that if you **remove all the blocks except the ones for forms**, then twig will render the contents of those blocks.

I can push the demo if somebody else want to verify.

**Comment by HeahDude** [comment]
This bug may have been related to specific Twig version which could be fixed, if it's working now then let's close here until we can actually reproduce it.
