### ISSUE TITLE
[PhpUnitBridge] time() mocking is not triggered depending on how PhpUnit is invoked

### ISSUE THREAD

**Issue by 1ma** [symfony/symfony#19032]
I'm not sure if this is a genuine bug or a misunderstanding from my part on how to use the PHPUnit Brige, but I think it might be.

### Summary & reproduction steps

When this test suite is run, ClockMock fails to override the implementation of the time functions _outside the namespace where the test case lives_, despite having made the appropriate calls to ClockMock::register.

```bash
# initial setup
git clone --branch clockmock-fix https://github.com/1ma/Psr7Hmac
cd Psr7Hmac
composer install
wget https://phar.phpunit.de/phpunit.phar
```

```bash
# running the whole tests suite
php phpunit.phar

PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

...............................................................  63 / 183 ( 34%)
............................FFFFFFF............................ 126 / 183 ( 68%)
.........................................................       183 / 183 (100%)

Time: 1.63 seconds, Memory: 16.00MB

There were 7 failures:

1) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "Asika\Http\Request" (Asika\Http\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

2) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "GuzzleHttp\Psr7\Request" (GuzzleHttp\Psr7\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

3) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "RingCentral\Psr7\Request" (RingCentral\Psr7\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

4) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "Slim\Http\Request" (Slim\Http\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

5) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "Symfony\Component\HttpFoundation\Request" (Zend\Diactoros\ServerRequest Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

6) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "Wandu\Http\Psr\Request" (Wandu\Http\Psr\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

7) UMA\Tests\Psr\Http\Message\HMAC\VerifierTest::testDelayedMessageDetection with data set "Zend\Diactoros\Request" (Zend\Diactoros\Request Object (...))
Failed asserting that true is false.

/home/marcel/Desktop/Psr7Hmac/tests/HMAC/VerifierTest.php:118

FAILURES!
Tests: 183, Assertions: 890, Failures: 7.

Generating code coverage report in Clover XML format ... done
```

```bash
# running the specific test case that contains the tests that failed above
php phpunit.phar tests/HMAC/VerifierTest

PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

...................................                               35 / 35 (100%)

Time: 476 ms, Memory: 14.00MB

OK (35 tests, 112 assertions)

Generating code coverage report in Clover XML format ... done
```

```bash
# running the problematic tests alone
php phpunit.phar tests/HMAC/VerifierTest --filter testDelayedMessageDetection

PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

.......                                                             7 / 7 (100%)

Time: 283 ms, Memory: 14.00MB

OK (7 tests, 14 assertions)

Generating code coverage report in Clover XML format ... done
```

### Analysis
```php
/**
 * @dataProvider simplestRequestProvider
 *
 * @param RequestInterface $request
 */
public function testDelayedMessageDetection(RequestInterface $request)
{
    ClockMock::register(__CLASS__);
    ClockMock::register(TimeProvider::class);
    ClockMock::withClockMock(true);

    $signedRequest = (new Signer(self::SECRET))
        ->sign($request);

    $timeSensitiveVerifier = (new Verifier())
        ->setMaximumDelay(5);

    $this->assertTrue($timeSensitiveVerifier->verify($signedRequest, self::SECRET));

    sleep(10);

    $this->assertFalse($timeSensitiveVerifier->verify($signedRequest, self::SECRET));

    ClockMock::withClockMock(false);
}
```
With the help of XDebug I have seen that in every case the register function passes the expected namespaces down to the eval() call, which are ```UMA\Tests\Psr\Http\Message\HMAC``` and ```UMA\Psr\Http\Message\HMAC``` in the first call, then ```UMA\Psr\Http\Message\Internal``` in the second.

Then I placed breakpoints at the beginning of ClockMock's time() and sleep() methods, which are the only ones that are used in the test.

If everything worked as expected the execution flow should enter ClockMock's time() function two times (first from [UMA\Psr\Http\Message\Internal\TimeProvider#L18](https://github.com/1ma/Psr7Hmac/blob/7dfe0ddf5295b1b3d87df25ea3c98911a0b609db/src/Internal/TimeProvider.php#L18), then from [UMA\Psr\Http\Message\HMAC\Verifier#L119](https://github.com/1ma/Psr7Hmac/blob/7dfe0ddf5295b1b3d87df25ea3c98911a0b609db/src/HMAC/Verifier.php#L119)), then sleep() from the very same test function, then time() for one last time, again from [UMA\Psr\Http\Message\HMAC\Verifier#L119](https://github.com/1ma/Psr7Hmac/blob/7dfe0ddf5295b1b3d87df25ea3c98911a0b609db/src/HMAC/Verifier.php#L119).

What I'm withnessing is that when I run PHPUnit with no further arguments the execution flow only enters the sleep() method called in the unit test, so both the ```UMA\Psr\Http\Message\HMAC``` and  ```UMA\Psr\Http\Message\Internal``` are not properly mocked.

When I run the whole affected test case (VerifierTest) the flow also enters the time() method two times, when it passes by [UMA\Psr\Http\Message\HMAC\Verifier#L119](https://github.com/1ma/Psr7Hmac/blob/7dfe0ddf5295b1b3d87df25ea3c98911a0b609db/src/HMAC/Verifier.php#L119), but *not* at [UMA\Psr\Http\Message\Internal\TimeProvider#L18](https://github.com/1ma/Psr7Hmac/blob/7dfe0ddf5295b1b3d87df25ea3c98911a0b609db/src/Internal/TimeProvider.php#L18), so it seems that in this case the ```UMA\Psr\Http\Message\Internal``` namespace is still not properly mocked (still, the tests pass because the time() call that should have been mocked is the first one in the execution flow so the returned timestamp is the same as if it had really been mocked).

Only when I run the specific test function with PHPUnit's --filter flag I can see three distinct calls to ClockMock's time() and one to sleep().

If that's any help, there's also a Travis build available at https://travis-ci.org/1ma/Psr7Hmac/builds/136911702

**Comment by nicolas-grekas** [comment]
See https://symfony.com/doc/current/components/phpunit_bridge.html#troubleshooting
You need to adjust your phpunit.xml if you need to mock outside the namespace where the test case lives, and use the annotation otherwise.
This is because function declaration can't be made at runtime in every situations but must happen early in the bootstrap process.

**Comment by 1ma** [comment]
Dead on! Thank you Nicolas. And I apologize, if its documented I should have found it out myself.
