### ISSUE TITLE
Incorrect line break in exception message (500 debug page)

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#19041]
I was looking at line 7, but it's actually line 78. I don't think it's correct to cut off a word or number in the middle. 

![image](https://cloud.githubusercontent.com/assets/1754678/16008922/af66b56e-317a-11e6-9a0a-a5195a8b9fb7.png)

**Comment by javiereguiluz** [comment]
@iltar 👍  This is one of the multiple details that we want to improve redesigning the exception template.

**Comment by pedroresende** [comment]
@iltar, @javiereguiluz I've made a possible fix for this issue
