### ISSUE TITLE
It's impossible to disable templating since 3.1

### ISSUE THREAD

**Issue by j0k3r** [symfony/symfony#19052]
In a project, we decided to disable templating (in prod env).

We don't need it in production because we are just generating xml. We send the response at the end of the controller (`return $response->setContent($xml);`).

That's why we defined that in `config.yml`:

```yaml
framework:
    # ....
    templating: false
```

We started the project with Symfony 2.8 and recently jumped to 3.1. And that's when the problem came out: we can't clear the cache anymore in prod env because the templating now require to have at least one engine defined. Which seems to be like that for years.

**But** one commit, in the 3.1 branch, breaks the ability to disable templating: https://github.com/symfony/symfony/commit/39723c512681c178032aabc4cce38da85d461b66

This commit remove `canBeEnabled` and use `canBeUnset` instead.

As far as I understand, it means the templating _can be disabled_ and we don't have to worry about it. But the configuration of FrameworkBundle define the `engines` as required (`->isRequired()`). This means we can't disable templating **because** a child is required.

With Symfony 3.0.x :white_check_mark: :

```
[12:30:55](master *%=){0}jeremy@j0k:~/late$ composer up

  - Updating symfony/symfony (v3.1.0 => v3.0.7)
    Checking out 272ab3327c3d311aaa9f634730162ea00e9d9e93

[12:31:19](master *%=){0}jeremy@j0k:~/late$ php bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                          
```

With Symfony >= 3.1.x :x: :

```
[12:31:22](master *%=){0}jeremy@j0k:~/late$ composer up

  - Updating symfony/symfony (v3.0.7 => v3.1.0)
    Checking out e71d4713c506686e6cf027af44c97ee5d94c7db4

[12:35:04](master *%=){0}jeremy@j0k:~/late$ php bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false  
                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "engines" at path "framework.templating" must be configured.    
```

I know we can define the engine to use php if we don't want to load and enable Twig but we don't want to load classes related to php templating either.

So what can be the solution to disable templating?
 - should we re-use `->canBeUnset()` under templating configuration?
 - should we remove the requirement for `engines` node?

PS: it's the same for router, because it is also `->canBeEnabled()` but got a required child (`resource`).

**Comment by stof** [comment]
for now, you can workaround it this way:

```
framework:
    templating:
        enabled: false
        engines: []
```

I will keep this issue opened, because we indeed have a BC break here

**Comment by j0k3r** [comment]
Thanks for the workaround but I still have to define php as templating engine (since engines _should have at least 1 element(s) defined_).

```yaml
framework:
    templating:
        enabled: false
        engines: ['php']
```

I guess that if I define `enabled: false` the templating is still disabled.

**Comment by xabbuh** [comment]
see #19120
