### ISSUE TITLE
[Form] Form method when handling request

### ISSUE THREAD

**Issue by seferov** [symfony/symfony#19056]
To give a simple example;
```php
$form = $this->createForm(new FormType(), new Entity(), [
   'method' => 'PUT',
]);
$form->handleRequest($request);
```

In this case, passing `Request` to form with `handleRequest`, why do I have to explicitly declare method as an option when handling request methods other than POST?

**Comment by mvrhov** [comment]
The browsers only know how to submit the forms with action set to GET or POST.. When the action is set to anything other.. the hidden field is added to the form to indicate the proper action.

**Comment by javiereguiluz** [comment]
Let's close this issue as "fixed". The question was answered and there's nothing left to do for Symfony. Thanks!
