### ISSUE TITLE
Upgrade 2.8/3.0 - missing information about generating absolute url

### ISSUE THREAD

**Issue by zdenekdrahos** [symfony/symfony#19058]
[Documentation 2.6](http://symfony.com/doc/2.6/book/routing.html#generating-absolute-urls) generates absolute url with `true`. [Newer documentation](http://symfony.com/doc/2.8/book/routing.html#generating-absolute-urls) uses constant. But the change is not mentioned in [upgrade guide](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md), not even in [routing's changelog](https://github.com/symfony/routing/blob/master/CHANGELOG.md):

| symfony | code | url |
| ----------- | ------ | ---- |
| [2.8](https://github.com/symfony/routing/blob/2.7/Generator/UrlGeneratorInterface.php#L37) | `$router->generate('...', [], true)` | http:/www.example.com/page |
| [3.0](https://github.com/symfony/routing/blob/master/Generator/UrlGeneratorInterface.php#L37) | `$router->generate('...', [], true)` | /page |

There was [deprecation](https://github.com/symfony/routing/commit/502cac1e711e708044e23a38ef3a452cedaa0878) but that can be very easily missed when absolute url is generated in AJAX call. We've found this little bug in generated url 3 months after upgrading to SF3. It's nothing critical, but it should be mentioned at least in upgrade guide.

**Comment by iltar** [comment]
It's indeed missing from the upgrade guides (checked all 2.6+ branches). However, calling it with true would've triggered a deprecation notice in 2.8. Not sure if the deprecation tool would've found it but it would've been most definitely logged into your WDT.

**Comment by peterrehm** [comment]
@zdenekdrahos Can you create a PR?
