### ISSUE TITLE
[ClassLoader] Incompatibility with hhvm and gc_mem_caches()

### ISSUE THREAD

**Issue by robations** [symfony/symfony#19050]
hhvm now self-identifies as PHP7 but doesn't support `gc_mem_caches()` which is causing `composer install` to fail, see this line:

https://github.com/symfony/class-loader/blob/master/ClassCollectionLoader.php#L198

**Comment by stof** [comment]
Please report an issue in HHVM, as it is a bug on their side then (btw, HHVM has a config option to choose whether it runs in PHP 5 vs PHP 7 mode)

**Comment by robations** [comment]
Thanks @stof. See https://github.com/facebook/hhvm/issues/7155

**Comment by xabbuh** [comment]
Closing here in favour of facebook/hhvm#7155.
