### ISSUE TITLE
$form->submit not mapping model data 

### ISSUE THREAD

**Issue by yoncy** [symfony/symfony#19071]
Symfony version 2.4.10 

Seems that $form->submit($data) doesn't map with model field types. So having errors that value is not  valid. Even the data is there, it should be mapped. 
Suppose is ModelChoiceList from Propel bridge mapping fault (had problems with it in the past) but it seems **NOT**
http://prntscr.com/bgzxcs

My form looks like 
`public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('eventCompany', 'model', [
            'class'         => 'Capp\CoreBundle\Model\EventCompany\EventCompany',
            'property'      => 'id',
            'query'         => \Capp\CoreBundle\Model\EventCompany\EventCompanyQuery::create()
                                ->filterByActive(-1),
            'by_reference'  => false,
            'required'      => true,
            'attr'          => ['class' => 'chosen-select', 'style' => 'width:200px;'],
            'label'         => 'Company',
            'empty_value'   => 'Select an event first',
        ]);`

in my controller 
 `
        $materialRequest = new MaterialRequest\MaterialRequest();
        $form = $this->createForm(new Type(), $materialRequest);

        $this->unifyRequest($request, 'material_request');

        if ('POST' === $request->getMethod()) {
            // get request data
            $data = $this->prepareFormData($request->get('material_request'));

            $form->submit($data);

            if ($form->isValid()) {`

**Comment by xabbuh** [comment]
@yoncy Symfony 2.4 is no longer supported. Can you reproduce your issue on Symfony 2.7 or newer?

**Comment by yoncy** [comment]
@xabbuh  Not really, not using forms at all, in the newest projects with new symfony versions.
Problem was related with that 'virtual'  query that anyway will not bring results (active = -1, populate later from ajax). Commented that and now seems to be ok. Something with initial mapping was broken there I think.
 `'query' => \Capp\CoreBundle\Model\EventCompany\EventCompanyQuery::create() ->filterByActive(-1), `
PS: Sorry for the post, cannot delete it or something.
