### ISSUE TITLE
Disable faulty translation in documentation

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony#19074]
Hey there. You should add the no translate attribute to your symfony documentation. Otherwise google will translate them which results into false code.

![2016-06-16 11_36_49-wie https erzwingen oder http fur verschiedene urls symfony cookbook](https://cloud.githubusercontent.com/assets/5689499/16112226/b7e71452-33b6-11e6-8ca9-c702d6857740.png)

**Comment by javiereguiluz** [comment]
@CoalaJoe thanks for suggesting this proposal. I think it makes sense to do that. However, we discuss about Symfony Docs in this other repository --> https://github.com/symfony/symfony-docs  Could you please copy+paste this issue in that other repo? Thanks!

**Comment by xabbuh** [comment]
For the records: This will be continued in symfony/symfony-docs#6657.
