### ISSUE TITLE
Support Finder objects in Filesystem component

### ISSUE THREAD

**Issue by djmattyg007** [symfony/symfony#19075]
It would be really nice if it waa possible to pass an instance of \Symfony\Component\Finder\Finder to some of the methods in \Symfony\Component\Filesystem\Filesystem, such as `remove` and `touch`.

**Comment by stof** [comment]
these methods accept filenames (both as an array and an iterator). Supporting the Finder would be a matter of making them able to deal with a SplFileInfo object rather than a filename.
But I'm not sure it is worth it. It is easy to wrap the Finder into an iterator returning filenames:

```php
function extractFileNames(\Traversable $fileIterator)
{
    foreach ($fileIterator as $file) {
        yield $file->getPathname();
    }
}

$filesystem->remove(extractFileNames($finder));
```

**Comment by djmattyg007** [comment]
Thanks for the tip. It would be nice to avoid duplicating the glue code everywhere though.

**Comment by stof** [comment]
Well, you can define the function once and use it several times :smile:

**Comment by javiereguiluz** [comment]
@stof if this need is common enough, the framework should provide it. I don't know if it's common.

**Comment by ro0NL** [comment]
What about `$finder->extractFilenames()`? It seems convenient for this..

**Comment by ro0NL** [comment]
@djmattyg007 can you confirm you're encountering any issues on this? Ie it basicly works out of the box already.. :confused:

**Comment by djmattyg007** [comment]
No, no issues. It was just a nicety, for the reasons listed above.

**Comment by fabpot** [comment]
Closing as @ccording to @ro0NL who did some work on that, it already works out of the box.

**Comment by ro0NL** [comment]
Well at least `remove` and `touch` ;-)
