### ISSUE TITLE
Deprecation notices sometimes ignore PSR-1 paragraph 2.3 

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony#19087]
Deprecation notices sometimes ignore [PSR-1 paragraph 2.3](http://www.php-fig.org/psr/psr-1/#2-3-side-effects). For example [Symfony\Component\Ldap\LdapClient](https://github.com/symfony/symfony/blob/7581f71b34dec4ea6ae167cd3f02403002fa55a0/src/Symfony/Component/Ldap/LdapClient.php#L14).

I think this should be in the constructor and maybe in other cases in public static methods that do not pass the constructor.

Shall I create a PR fixing this cases?

**Comment by nicolas-grekas** [comment]
They are here on purpose, we don't want the notice to be triggered at each instantiation, but only once.

**Comment by gisostallenberg** [comment]
Why would you only want is once? When triggered at each instantiation it would be possible to aggregate the usage of such classes and identify all points where it should be replaced.

**Comment by nicolas-grekas** [comment]
What issue are you trying to solve?

**Comment by gisostallenberg** [comment]
:confused: You're right, not a specific issue. Just that you state to [follow the PSR-1](http://symfony.com/doc/current/contributing/code/standards.html), but maybe your target is more important. Thanks for taking the time to answer my question. Glad I didn't spent time on the PR :wink:

**Comment by nicolas-grekas** [comment]
You gained some time to do any other PR :)
