### ISSUE TITLE
[Process] Orphan temporary files are left on Windows - still an issue

### ISSUE THREAD

**Issue by adamjakab** [symfony/symfony#19089]
Hi,

I have found and read these issues #8629 and #7078 and I experience the same problems still.
It is a Windows issue - I have a synchronization cli application using symfony/console and symfony/process launching around 4-5K processes a day. It was built and tested on linux and deployed on Windows 2008 Server R2 for production. 
The main application is launched by Windows Task Scheduler and using an internal cron-like procedure it launches processes at certain times to sync data between servers.
It worked for a few months then it stopped and was unable to launch even manually.

Looking into the thing and debugging the main process I have found that I was getting this 'A temporary file could not be opened to write the process output to, verify that your TEMP environment variable is writable.' exception.  I looked up the TEMP directory and I have found  around 120,000 temporary files inside (most of them 0 bytes).

Looking for the origin I was thrown off-track because I the `Process::STDOUT => tempnam(sys_get_temp_dir(), 'out_sf_proc'),` [here](https://github.com/symfony/process/blob/master/Pipes/WindowsPipes.php#L51) should produce temporary files with prefix 'out_sf_proc'. Well, it does not. At least not on my server. The files I find that get created by WindowsPipes class are prefixed with: 'out' and 'err' such as 'err4F18.tmp' and 'out4F19.tmp'.

I put in some 'echo's for a quick check to see what gets called and what not. 
The `__destruct` method gets correctly called, and hence, the `removeFiles` method as well.
However, the `@unlink($filename);` [here](https://github.com/symfony/process/blob/master/Pipes/WindowsPipes.php#L170) does not always succeed resulting in the leftover files.

I have also put in a stupid loop to attempt to remove the file once every second until it succeeds (max 60sec) and I can see that some of the files after 5-10 attempts get correctly removed. Some others reach 60 sec and remain forever. During that time if I attempt to remove these file manually with admin account Windows says that files are in use and cannot be removed.

Any ideas?

Php: 5.6

**Comment by nicolas-grekas** [comment]
Can you check which processes are locking the files? (check google to see how...)

**Comment by romainneutron** [comment]
Your issue has been fixed in branch 2.7. Patch will be available to other branches very soon and will be released in all next symfony releases.

Thanks again for reporting this

**Comment by adamjakab** [comment]
[köszönöm](https://en.wiktionary.org/wiki/k%C3%B6sz%C3%B6n%C3%B6m) @nicolas-grekas
