### ISSUE TITLE
[FrameworkBundle] Improve console header line

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#19095]
Hi,

Imho the current header line for the console application is a bit circus-like and misleading.

![image](https://cloud.githubusercontent.com/assets/1047696/16169874/b0add5d4-353e-11e6-83f3-048bc54ecdc6.png)

Circus like as in; Green, white and yellow for the name/version part.
Misleading as in `app/dev/debug` looking like a working directory or at least some sort of path.

Im not proposing a big fat ascii header here, but just some formatting improvements. What about formatting the individual parts (version, kernel name, dev yes/no, debug yes/no) as labels, a bit like the webprofiler toolbar is doing.

**Comment by xabbuh** [comment]
At least for the `app/dev/debug` part I agree with you. Especially for newcomers this part might not be really clear.

**Comment by ro0NL** [comment]
@xabbuh any thoughts?

![image](https://cloud.githubusercontent.com/assets/1047696/16462974/025b3b76-3e34-11e6-9912-9d29666cbe38.png)

Im just playing around with it.. not sure if _this is it_ though. Some things i like (kernel@env format, better signal colors), some things i dont (colors :sweat_smile:, brackets i guess =/)

**Comment by javiereguiluz** [comment]
In my opinion the latest proposal is more confusing than the existing line.

We could go for the explicit way:

```
Symfony 3.2.0-DEV (kernel: app) (env: dev) (debug: true)
```

**Comment by ro0NL** [comment]
Makes sense =/ :+1: for removing "version"

What about colors? separate label wise? key-value wise?

**Comment by jvasseur** [comment]
I think `debug: false` shouldn't be red, red means an error and disabling debug is a totally valid thing.

**Comment by ro0NL** [comment]
I know.. therefore i proposed on/off instead of true/false. Imho reg/green also signals on/off. But maybe keeping it simple is a good thing, ie plain text except for the version.

**Comment by WouterJ** [comment]
> Do we want UTF8 chars? I.e. we could als play with ✓ & ✗

This is not supported by Windows terminals.

**Comment by javiereguiluz** [comment]
What if we don't use color at all?

If not possible, please don't try to convey the information with colors. Color blindness, specially for green/red, is very common for males: ~8% of population, [see reference](https://en.wikipedia.org/wiki/Color_blindness#Epidemiology) (for females is just 0.5%).

**Comment by ro0NL** [comment]
Globally? The whole console is pretty colorful right now and can be controlled by `--[no-]ansi` anyway.

Or do you propose
`Symfony 3.2.0-DEV (kernel: app) (env: dev) (debug: true)` literally?

**Comment by xabbuh** [comment]
I you really want to use colours here, I would use them to distinguish keys and values, but I would not use a colour that is dependent on the actual value.

**Comment by HeahDude** [comment]
Agreed with @xabbuh since using colors this way can make parentheses needless

**Comment by ro0NL** [comment]
![image](https://cloud.githubusercontent.com/assets/1047696/16515449/605f22fc-3f72-11e6-802b-9e6932c55cb0.png)

Imo we need some form of separation..
- separating metadata from the version (e.g. v3 with parentheses)
- separating key/value pairs (e.g. v3 with comma)

**Comment by javiereguiluz** [comment]
My preference would be the third option.

**Comment by ro0NL** [comment]
Mine too :)
