### ISSUE TITLE
Validating or ignoring validation of embedded model property in a request

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#19093]
Hi,

I'm trying validate or ignore validating embedded model property class based on the request payload however I don't quiet know how to do it. The request is considered valid only if no `manufacturer` property is given in payload or both properties of `manufacturer` is given or `manufacturer` is set to `null`.

Note: Is what I want possible without using class level custom validator? I can do this with a custom class validator.

**VALID REQUESTS**
As you can see either all given or none for `manufacturer`.

```
{
  "name": "Ball",
  "manufacturer": {
    "phone": "123",
    "email": "abc@abc.abc"
  }
}

{
  "name": "Ball",
  "manufacturer": null
}

{
  "name": "Ball"
}
```

**INVALID REQUESTS**
As you can see `manufacturer.email` is either missing or set to `null`. It could be `phone` too. 

```
{
  "name": "Ball",
  "manufacturer": {
    "phone": "123",
    "email": null
  }
}

{
  "name": "Ball",
  "manufacturer": {
    "phone": "123"
  }
}
```

**MODELS**

```
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as Serializer;

class Property
{
    /**
     * @Assert\NotBlank(message="The name field is required.")
     *
     * @Serializer\Type("string")
     */
    public $name;

    /**
     * @var Manufacturer
     *
     * @Assert\Valid(traverse="true")
     *
     * @Serializer\Type("Application\BackendBundle\Model\Api\Manufacturer")
     */
    public $manufacturer;
}
```

```
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as Serializer;

class Manufacturer
{
    /**
     * @Serializer\Type("string")
     */
    public $phone;

    /**
     * @Serializer\Type("string")
     */
    public $email;
}
```

**Comment by ro0NL** [comment]
I assume you can jus use symfony's built-in validator, to validate your models as you configured them with annotation constraints. Did you configured it accordingly?

Where exactly are you stuck? Your workflow seems quite basic..
- Deserialize request into model
- Validate model

About `@Assert\Valid(traverse="true")`... this is the default behaviour.. so i would remove that or set it explicitly to `false`, as you never want to traverse the `Manufacturer

**Comment by iltar** [comment]
This issue tracker is for actual issues, not support questions. The recommended support channels can be found here: http://symfony.com/support

**Comment by BentCoder** [comment]
@ro0NL I want to run validation on `Manufacturer ` only if one or both of its properties are in request payload. You have to provide either both of them or none of them to make validation kick in.

If I do this, `manufacturer` becomes compulsory in request. As I say, if you don't provide both `phone` and `email` then `manufacturer` shouldn't be compulsory.

```
class Manufacturer
{
    /**
     * @Assert\NotBlank(...)
     * @Assert\Regex(....)
     * @Serializer\Type("string")
     */
    public $phone;

    /**
     * @Assert\NotBlank(.....)
     * @Assert\Email(.....)
     * @Serializer\Type("string")
     */
    public $email;
}
```

**Comment by ro0NL** [comment]
Sounds like a deserializing problem.. i.e. you always get a `Manufacturer` model, even if there's no `manufacturer` element in the request, ie a model full of null values, right?

Sorry @iltar :')

**Comment by BentCoder** [comment]
@ro0NL Yes.

So these should be perfectly fine as `manufacturer` either exist with all values or none of them. Only partial is invalid.

```
{
  "name": "Ball",
  "manufacturer": {
    "phone": "123",
    "email": "abc@abc.abc"
  }
}

{
  "name": "Ball",
  "manufacturer": null
}

{
  "name": "Ball"
}
```

**Comment by ro0NL** [comment]
Maybe you can get some specific support at the JMS repository..., IRC otherwise. It sure sounds like weird behaviour though, on the other hand how bad is it? I.e. why do you want to;

> [...] run validation on Manufacturer only if one or both of its properties are in request payload.

From a validating pov is not so much a problem, from a serializing pov; you can skip null values when serializing. I guess you would end up with `"manufacturer": {}` instead of `"manufacturer": null` then...

**Comment by javiereguiluz** [comment]
@BentCoder I'm sorry but I'm going to close this issue because so far it doesn't look like a Symfony bug. Hopefully @ro0NL's comments will help you solve this. Otherwise, please check: https://symfony.com/support  Thanks!
