### ISSUE TITLE
[CI] fabbot.io isn't working properly

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#19119]
Fabbot.io seems to not be working properly, since there are some PRs with checks that are passing, but they indeed are offending basic CS rules.
Some examples:
* [#18788 (comment)](https://github.com/symfony/symfony/pull/18788#discussion_r63454258)
* [#18501 (comment)](https://github.com/symfony/symfony/pull/18501#discussion_r67624243)

Moreover, It would be nice to know also which version of `PHP-CS-Fixer` and which of their rules is fabbot.io using in order to help with the debug of these kind of issues and ensuring a consistent codebase according the well defined CS standards.

**Comment by fabpot** [comment]
I've just updated fabbot to add some more checkers. Up until now, only the Symfony level fixers were enabled as I thought that it automatically includes the PSR-X ones, but that's not the case.

So, as of today, fabbot runs all PSR-X, Symfony and php_unit_construct from contrib.

I've run it on one PR and it now catches the issue: http://fabbot.io/report/symfony/symfony/18501/ebf3a2ffc8e778b255bb4786f19dba8ae4100575

**Comment by phansys** [comment]
Thank you @fabpot.

**Comment by xabbuh** [comment]
For the records, #19121 will fix the CS for the `2.7` branch.

**Comment by mvorisek** [comment]
@fabpot Can you please upgrade the PHP version of fabbot.io to PHP 8.0? - needed for CS fixer. If there is a better place to submit issues for fabbot.io, please let me know! Thanks.

**Comment by fabpot** [comment]
fabbot.io has been using PHP 8 for quite some time now.

**Comment by mvorisek** [comment]
@fabpot https://fabbot.io/report/FriendsOfPHP/PHP-CS-Fixer/5469/ac94edbfe3c2a8cc467ccc11191a1c91a180d995 why does fabbot.io fix the already up-to-date CS then?
