### ISSUE TITLE
Symfony, phpunit 5.4 and deprecations

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#19125]
When upgrading to a newer phpunit, you will start getting warnings that amongst some `getMock` is deprecated and `createMock` should be used instead.

According to the contribution page, [4.2 or higher is required][1]. Symfony doesn't have its own dependency on phpunit and thus it's up to the contributors to use the proper versions. Now that phpunit is picking up speed and starts dropping unsupported php versions and features, things change fast. 

In phpunit 5.4 the biggest change is the deprecation of `getMock`. If this method is used with only 1 argument, it has to be replaced by `createMock` and if the other arguments were passed along, `getMockBuilder` should be used instead.

As symfony doesn't really have a constraint on phpunit other than 4.2+, you will run into some small issues:
```
$ f getMock -G "Test/"
src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php
96:        $translator = $this->getMock('Symfony\Component\Translation\TranslatorInterface');
97:        $validator = $this->getMock('Symfony\Component\Validator\Validator\ValidatorInterface');
98:        $contextualValidator = $this->getMock('Symfony\Component\Validator\Validator\ContextualValidatorInterface');

src/Symfony/Component/Form/Test/TypeTestCase.php
33:        $this->dispatcher = $this->getMock('Symfony\Component\EventDispatcher\EventDispatcherInterface');
```

The first one I don't know but the second one is used as a base class for form type tests. Besides of this, the test code might have to change as well as `getMock` is being deprecated. I can create a patch for those cases to check if createMock exists and call it instead or use the mock builder for example.

Besides of this issue, I would like to bring up the discussion of the supported phpunit versions and how to actively keep the tests up-to-date.
 - Should the phpunit-bridge create a BC layer to avoid those issues in the future and expose a custom API?
 - Should the minimal phpunit version be bumped to something that's still maintained? 
 - [Minor versions are not supported for very long and the major for a year][2]. Maybe the minimum phpunit version should always be `<current major>.0.0`?

[1]:https://symfony.com/doc/current/contributing/code/patches.html#install-the-software-stack
[2]:https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#support

**Comment by nicolas-grekas** [comment]
We support only one way to run tests: through the ./phpunit wrapper, which
is 5.1. Because we support php 5.5 but phpunit 5.4 requires php 5.6, we're
can use phpunit 5.4 features without breaking the tests for php 5.5 OR
creating a compat wrapper. I really don't see the point into coding this
wrapper: yet more code to maintain. Tests run fine, the quality of the code
base or the test suite is not affected by using a not-up-to-date phpunit.

**Comment by xabbuh** [comment]
The only way we could "fix" this would be to always use PHPUnit's mock builder which is available in all supported versions. However, as @nicolas-grekas said we can control the used PHPUnit version through our `phpunit` wrapper. Thus I don't think that we need to do anything here than just not use PHPUnit 5.4 right now.

**Comment by yannickl88** [comment]
Do note that since the `TypeTestCase` is a public class provided to allow others to easily write unit tests. So if you are using that in your own project in combination with phpunit 5.4+ you will get a deprecation warning.

So yes, for symfony itself it is not an issue, but you should at least provide a warning free public solution for those not using the wrapper for their own projects.

**Comment by iltar** [comment]
@nicolas-grekas That means that we're currently running an "unsupported" version though. Not a big deal at this time, but it will make upgrading to 6.0 quite a bit harder. 

Would it be an idea to update the contribution page to explain how to run the actual tests? Currently I dumped a `phpunit.phar` in my project dir which I run for tests, but ideally I'd use the same as symfony uses.

As far as I understand it, it's simply running `./phpunit`. So this page could tell us to use `./phpunit` which uses `phpunit` 5.1 or higher instead of 4.2.

**Comment by xabbuh** [comment]
@iltar Imo the way we updated the docs some time earlier this year are pretty clear: http://symfony.com/doc/current/contributing/code/tests.html#running-the-tests Do you see something we can improve?

@yannickl88 Indeed, you are right when it comes to test case classes that are meant to be used by third-party projects.

**Comment by iltar** [comment]
@xabbuh mainly this page: http://symfony.com/doc/current/contributing/code/patches.html as it still indicates phpunit 4.2 minimal. I can make a PR to update this to 5.1 if desired.

**Comment by xabbuh** [comment]
@iltar You're right. I just spotted that too (see symfony/symfony-docs#6668).

**Comment by stof** [comment]
@iltar we cannot use the phar, as it includes some Symfony code (the Yaml component, used for the tap reporter IIRC), which means you would run tests against this version of the component rather than the tested codebase.

**Comment by stof** [comment]
and we cannot require PHPUnit 5.1. Our testsuite needs to stay compatible with 4.8 to be able to run tests on PHP 5.5

**Comment by iltar** [comment]
@stof but the way how php works, it will load the -by phpunit required- library either way and never your version (if I'm not mistaken). I assume there's some form of isolation when running the tests.

Anyway, the actual issues for the extension points are fixed now so that was a nice quick gain

**Comment by stof** [comment]
@iltar our wrapper precisely handles it by removing the requirements for features we don't use

**Comment by iltar** [comment]
@stof But if there's a conflicting component, which is used by both symfony and phpunit for example, it would load the phpunit one and you would be unable to test the symfony one as the php version is always loaded first.

**Comment by stof** [comment]
@iltar which is why symfony/yaml is not the only dependency being removed by our wrapper, keeping only the dependencies needed for the feature we use.

Btw, as we perform a composer-based install of phpunit, your affirmation is wrong. It depends on the order of autoloaders (PHPUnit performs eager-loading of all its dependecies in the phar, but not in source installs)
