### ISSUE TITLE
[TwigBundle] Twig extensions as services

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#19130]
The official [Twig extensions repository](https://github.com/twigphp/Twig-extensions) provides some nice extra stuff for twig.

If we want to integrate some on a Symfony project as a service, we can find [some tricks](http://blog.christian-baer.com/index.php/truncate-text-in-twig-symfony-2/) or maybe an [external bundle](https://packagist.org/packages/dms/twig-extension-bundle) for that.

But AFAIK, no "official" implementation inside Symfony itself.

Why not proposing those extensions as services if the `twig/extensions` package is required by the end user?

This would permit to have an official way and avoid a lot of nearly reliable integrations and mysterious implementation like we recently discovered here: https://github.com/sonata-project/SonataCoreBundle/pull/311

What do you think?

Sorry if I open an already asked question, I found nothing on the issue tracker about that...

Thanks.

**Comment by iltar** [comment]
Well in my opinion this isn't really needed. Truncating text is a different story and should be handled with css imo, especially because if you repeat and M 50 times, you might still have length problems.

If there's already a  bundle that implements the extensions, why not just use that? Shouldn't be a problem if you really need the functionality.

**Comment by WouterJ** [comment]
Registering a service with a custom class and tagging it as Twig is nor a trick nor a nearly-reliable integration, it's just the only officially supported way to register twig extensions. Any Twig extension, whether it's from `your/awesome-twig-extension` package or from `twig/extensions` doesn't matter.

What happends here is that some application uses filters not available in a normal Twig setup. It will then need a dependency and to register this extension. Just as I need to require Eloquent ORM and register an eloquent service if I want to use Eloquent ORM in my application. I honestly can't see the problem here.

**Comment by Soullivaneuh** [comment]
> Truncating text is a different story and should be handled with css imo, especially because if you repeat and M 50 times, you might still have length problems.

Please not that Twig is not **necessary** for html template. You can even use is to generate txt files if you want.

Plus, this is not about truncate function only. :wink: 

> If there's already a bundle that implements the extensions, why not just use that?

This bundle provide a configuration to activate or deactivate some extensions. This is great for end user but not really for other external bundles that need some extension. This might fail if deactivated.

**Comment by Soullivaneuh** [comment]
@WouterJ So what about external bundles which need those extensions? What about this? sonata-project/SonataCoreBundle#311

Should be the role of the bundle to register this twig class as a service without know if this one may be already enable? Looks weird to me.

What is the proper way for you?

cc @greg0ire

**Comment by iltar** [comment]
I would expect composer to tell me to install the extensions library (or do it itself), I don't want to be bothered by dependencies of dependencies.

**Comment by Soullivaneuh** [comment]
> I would expect composer to tell me to install the extensions library (or do it itself), I don't want to be bothered by dependencies of dependencies.

What do you mean? I'm not telling about requiring the composer package inside twig-bundle, but provide the extensions as services **if the packages is installed**.

**Comment by WouterJ** [comment]
> @WouterJ So what about external bundles which need those extensions? What about this? sonata-project/SonataCoreBundle#311

If I understand the issue correctly, we have an *application* requiring the Twig extension, not a bundle.

But if a bundle requires something that's not available in Symfony core, it indeed has to take care of making sure it's loaded. See for instance the installation guide of Sonata, which requires you to register SonataCoreBundle, KnpMenuBundle and a few others when you want to use the SonataAdminBundle.

This is also one of the reaons third party bundles almost never use `@Route` annotations: It relies on SensioFrameworkExtraBundle and not a core feature. Bundles don't want to take care of making sure the framework extra bundle is required and simply use core supported formats (yaml, xml, etc.).

**Comment by iltar** [comment]
If I understand @Soullivaneuh correctly, the desired feature is to have the TwigBundle register the extensions if the package is installed.

**Comment by stof** [comment]
@Soullivaneuh but what if you want to use only some of these extensions ? There is currently 5 extensions in this repo:

- i18n: cannot be used as it conflicts with the Symfony translator integration, so should not be registered
- text
- date
- array (useful only if you need to shuffle arrays in your template, which I never needed)
- intl

If we make things configurable to let the application decide which extensions are registered or no, your point about bundles needing it becomes invalid, as they will still need to check whether the extension is there or no.
If we don't make things configurable and just register everything as soon as the package is installed, people will likely complain about it

**Comment by iltar** [comment]
In that case, if existing bundles don't provide this functionality with configurations, why not make one yourself?

**Comment by Soullivaneuh** [comment]
> If I understand the issue correctly, we have an application requiring the Twig extension, not a bundle.

Currently, this is a big debate: https://github.com/sonata-project/dev-kit/issues/138 :stuck_out_tongue: 

For me it's more a group of bundle than an application, because AFAIK this one can be installed and run as is after a git clone / composer install.

But let's not diverge from the subject of this issue. :wink: 

> But if a bundle requires something that's not available in Symfony core, it indeed has to take care of making sure it's loaded. See for instance the installation guide of Sonata, which requires you to register SonataCoreBundle, KnpMenuBundle and a few others when you want to use the SonataAdminBundle.

> This is also one of the reaons third party bundles almost never use @Route annotations: It relies on SensioFrameworkExtraBundle and not a core feature. Bundles don't want to take care of making sure the framework extra bundle is required and simply use core supported formats (yaml, xml, etc.).

Agree, this is why the first point was to move this service onto ecommerce, not core-bundle.

But I still think this is not the role of ecommerce too (this not really a final application).

> If I understand @Soullivaneuh correctly, the desired feature is to have the TwigBundle register the extensions if the package is installed.

Exactly, nothing more! :wink: 

> @Soullivaneuh but what if you want to use only some of these extensions ? There is currently 5 extensions in this repo:

Interesting. There is no way to "detect" already installed filters or functions to not add not wanted service? Or something like that, dunno...

The issue is a suggestion to add this on twig-bundle but also to have a point of view of the best way to implement them.

**Comment by greg0ire** [comment]
> BTW, what happen if we declare a service for Twig_Extensions_Extension_Text on the bundle and the user do the same on his application? No conflict?

You can have two service with the same class, that is not a problem (and that's why you should not file classes under a `Service` directory IMO).

Also, maybe framework integrations could be directly in the library, in a `Bridge\Symfony\ directory, since these extensions seem controversial enough to avoid the twig bundle referencing them directly.

**Comment by WouterJ** [comment]
> > BTW, what happen if we declare a service for Twig_Extensions_Extension_Text on the bundle and the user do the same on his application? No conflict?
 > You can have two service with the same class, that is not a problem (and that's why you should not file classes under a Service directory IMO).

Problem here is that Twig doesn't allow 2 extensions with the same name anymore: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L793-L795

**Comment by greg0ire** [comment]
> Problem here is that Twig doesn't allow 2 extensions with the same name anymore: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L793-L795

Oh right… I guess it's to avoid a conflict at the twig filter level (didn't realize @Soullivaneuh was probably talking about that as opposed to a conflict at the service level)

**Comment by Soullivaneuh** [comment]
> Problem here is that Twig doesn't allow 2 extensions with the same name anymore: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L793-L795

So not a problem right now, but will be later.

For me this is another reason to discuss about the proposed idea of this issue. :wink: 

> didn't realize @Soullivaneuh was probably talking about that as opposed to a conflict at the service level

Well, I was indeed talking about service, but this will not be our problem apparently...

**Comment by sstok** [comment]
Maybe add a check in the https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/TwigEnvironmentPass.php to ensure the class (not the extension-name) is not already registered?

**Comment by greg0ire** [comment]
Another problem : if the user deliberately defines their own `truncate` filter (which can happen if they don't realize this extension exists), there will be a conflict. So I'd says that enabling this services should be deliberate. Having a configuration key that would lead to loading corresponding service definitions would be a plus though. Something along those lines : 

```
twig:
    extra_filters:
        - truncate
        - wordwrap
```

**Comment by stof** [comment]
@greg0ire your proposal would not work, as we can only have granularity based on extensions, not on individual filters inside them

**Comment by Soullivaneuh** [comment]
> Maybe add a check in the https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/TwigEnvironmentPass.php to ensure the class (not the extension-name) is not already registered?

How would you handle this?

**Comment by greg0ire** [comment]
> @greg0ire your proposal would not work, as we can only have granularity based on extensions, not on individual filters inside them

We can't without modifying the extension itself indeed.

**Comment by stof** [comment]
@greg0ire and providing configuration in each extension to allow to register them partially is a no-go IMO

**Comment by greg0ire** [comment]
> @greg0ire and providing configuration in each extension to allow to register them partially is a no-go IMO

It does seem a bit much. How about something like : 

```
twig:
    enable_extra_filters: true
```

**Comment by sstok** [comment]
@Soullivaneuh Keep a list of all the extension classes (not there service-ids) and ensure each class only exists once. It will not prevent extensions with the same name but will prevent registering the same class twice (which is very common for the Twig-extensions package).

**Comment by Soullivaneuh** [comment]
> Keep a list of all the extension classes (not there service-ids) and ensure each class only exists once.

Looks great but I worry about performance. If we have lot of extensions, parsing the stored class array on each definition check can be quite long, right?

**Comment by javiereguiluz** [comment]
@Soullivaneuh I don't fully understand the issue here. Twig extensions are not built-in in Twig. Any developer (or project) that needs them must register them as services or must enable them directly in the Twig environment.

We're going to integrate soon the Intl extension because it's used very frequently ... but the rest of extensions will be kept separate for now.

**Comment by greg0ire** [comment]
@javiereguiluz I think the issue at hand is the possibility that every bundle that wants to use truncate, for instance, has to declare the service themselves, or have the user do it themselves, by copying the same boilerplate service definition on each project. So either you get a cumbersome installation procedure or you get classes that are used over and over with different service id's.

**Comment by Soullivaneuh** [comment]
@greg0ire @javiereguiluz Exactly.

This is indeed not difficult to declare them on an app, but I don't think this is the role of a vendor bundle.

**Comment by nicolas-grekas** [comment]
Closing, as this is something that should be done as a Flex recipe instead now IMHO.

**Comment by Soullivaneuh** [comment]
@nicolas-grekas Do we have a flex issue for that?

**Comment by nicolas-grekas** [comment]
Not sure, please open one.

**Comment by xabbuh** [comment]
https://github.com/symfony/recipes/tree/master/twig/extensions/1.0 right?

**Comment by nicolas-grekas** [comment]
Right!
