### ISSUE TITLE
When post_max_size is reached, CSRF error is triggered

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#19140]
https://github.com/symfony/symfony/issues/15479#issuecomment-137445433

I'm not sure, but I think this should not be happen.

**Comment by gharlan** [comment]
If `post_max_size` is reached, the `$_POST` superglobal is always empty: http://php.net/manual/en/ini.core.php#ini.post-max-size
So no, the token is not present. ;)

**Comment by xabbuh** [comment]
I am not sure what we can do in Symfony then. Well, maybe skipping the CSRF check? But how would we know that?

**Comment by gharlan** [comment]
The special handling of the `post_max_size` error is located here: https://github.com/symfony/symfony/blob/6e03a4231aac051c6c0ed6fc1341d5e912d81ebe/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L73-L90
