### ISSUE TITLE
GreaterThan Validator for Dates doesn't work

### ISSUE THREAD

**Issue by exchentrix** [symfony/symfony#19152]
Hey,

I've this in my form builder:

```php
        $builder->add('birthdate', DateType::class, array(
            'widget' => 'single_text',
            'html5' => false,
            'format' => $dateFormat,
            'attr' => array(
                'data-mask' => $this->i18n->getDataMaskFromDateFormat($dateFormat)
            ),
            'label' => $dateFormat
        ));
```

This is my validation.yml:

```yaml
	FooBundle\Model\Bar\Baz
		properties:
			birthdate:
				- NotBlank:
					message : messages.null
				- Date:
					message: messages.invalid_date
				- GreaterThan:
					value: -100 years
					messages: messages.invalid_year
```

If I post something like "1987-09-01", the form is not valid and brings me the message "invalid_year".

Is there something broken, or am I doing something wrong?

Best
Christian

**Comment by jakzal** [comment]
@exchentrix would you mind providing a fully working form please? I'm not sure what values you've got as `format` and `data-mask` options.

**Comment by exchentrix** [comment]
@jakzal Sure. I simplified the form and I'm using the default format now (yyyy-MM-dd). I also kicked the data-mask attribute for testing purposes:

### the form type

	<?php

	namespace CalcoBundle\Form\Type;

	use Symfony\Component\Form\AbstractType;
	use Symfony\Component\Form\FormBuilderInterface;
	use Symfony\Component\OptionsResolver\OptionsResolver;
	use Symfony\Component\Form\Extension\Core\Type\DateType;
	use Symfony\Component\Form\Extension\Core\Type\TextType;
	use Symfony\Component\Form\Extension\Core\Type\EmailType;
	use Symfony\Component\Form\Extension\Core\Type\PasswordType;

	use CalcoBundle\Services\I18nService;

	class RegistrationType extends AbstractType
	{
		public function buildForm(FormBuilderInterface $builder, array $options)
		{
			$builder->add('name', TextType::class);
			$builder->add('email', EmailType::class);
			$builder->add('plainPassword', PasswordType::class);

			$builder->add('birthdate', DateType::class, array(
				'widget' => 'single_text',
				'html5' => false,
			));
		}

		public function configureOptions(OptionsResolver $resolver)
		{
			$resolver->setDefaults(array(
				'data_class' => 'CalcoBundle\Model\Acl\Customer\Customer',
				'csrf_token_id' => 'registration'
			));
		}

		public function getBlockPrefix()
		{
			return 'app_user_registration';
		}
	}

The data class is built by propel. The controller for handling comes from FOSUserBundle and is not be overriding by me. I dont know wheather you need the view, anyway I'll give it to you:

### the view template for form rendering

	{% extends 'FOSUserBundle::layout.html.twig' %}
	{% block body %}
	<div class="login" data-lbg="blue">
		<div class="l-block toggled" id="l-register">
			<div class="lb-header palette-Blue bg">
				<i class="zmdi zmdi-account-circle"></i>
				{% trans %}messages.create_account{% endtrans %}
			</div>
			<div class="lb-body">
				{{ form_start(form, {'method': 'post', 'action': path('fos_user_registration_register')}) }}
				{{ form_widget(form._token) }}
				<div class="form-group fg-float{% if form.name.vars.errors|length %} has-error{% endif %}">
					<div class="fg-line">
						{{ form_widget(form.name, { 'attr': {'class': 'input-sm form-control fg-input'} }) }}
						{{ form_label(form.name, 'messages.name', { 'label_attr': {'class': 'fg-label'} }) }}
					</div>
					{% if form.name.vars.errors|length %}
						<small class="help-block">{{ form_errors(form.name) }}</small>
					{% endif %}
				</div>
				<div class="form-group fg-float{% if form.email.vars.errors|length or form.vars.errors|length %} has-error{% endif %}">
					<div class="fg-line">
						{{ form_widget(form.email, { 'attr': {'class': 'input-sm form-control fg-input'} }) }}
						{{ form_label(form.email, 'messages.email', { 'label_attr': {'class': 'fg-label'} }) }}
					</div>
					{% if form.email.vars.errors|length or form.vars.errors|length %}
						<small class="help-block">
							{{ form_errors(form.email) }}
							{{ form_errors(form) }}
						</small>
					{% endif %}
				</div>
				<div class="form-group fg-float{% if form.plainPassword.vars.errors|length %} has-error{% endif %}">
					<div class="fg-line">
						{{ form_widget(form.plainPassword, { 'attr': {'class': 'input-sm form-control fg-input'} }) }}
						{{ form_label(form.plainPassword, 'messages.password', { 'label_attr': {'class': 'fg-label'} }) }}
					</div>
					{% if form.plainPassword.vars.errors|length %}
						<small class="help-block">{{ form_errors(form.plainPassword) }}</small>
					{% endif %}
				</div>
				<div class="form-group fg-float{% if form.birthdate.vars.errors|length %} has-error{% endif %}">
					<div class="fg-line">
						{{ form_widget(form.birthdate, { 'attr': {'class': 'form-control input-mask'} }) }}
						{{ form_label(form.birthdate, 'messages.birthdate', { 'label_attr': {'class': 'fg-label required'} }) }}
					</div>
					{% if form.birthdate.vars.errors|length %}
						<small class="help-block">{{ form_errors(form.birthdate) }}</small>
					{% endif %}
				</div>
				
				<button type="submit" class="btn palette-Blue bg">{{ 'messages.register'|trans }}</button>
				{{ form_end(form) }}
				<div class="m-t-30">
					<a  href="{{ path('fos_user_security_login') }}" class="palette-Blue text d-block m-b-5">{% trans %}messages.already_have_account{% endtrans %}</a>
					<a  href="{{ path('fos_user_resetting_request') }}" class="palette-Blue text">{% trans %}messages.forgot_password{% endtrans %}</a>
				</div>
			</div>
		</div>
	</div>
	{% endblock %}

### the full validation for the model

	CalcoBundle\Model\Acl\Customer\Customer:
		constraints:
			- Propel\PropelBundle\Validator\Constraints\UniqueObject:
				fields:  email
				message: messages.email_exists
		properties:
			name:
				- NotNull:
					message : messages.null
			email:
				- NotNull:
					message : messages.null
				- Email:
					message : messages.invalid_email
			plainPassword:
				- NotBlank:
					message : messages.null
			birthdate:
				- NotBlank:
					message : messages.null
				- Date:
					message: messages.invalid_date
				- GreaterThan:
					value: -100 years
					message: messages.invalid_year

I'm on symfony 2.8.8 right now.

- I post "1987-09-01" --> Form is valid, which is ok
- I post "1655-09-01" --> Form is valid, which is not ok
- I post "2547-09-01" --> Form is valid, which is not ok

When using the LessThan-Validator for the birthdate field, the form becomes invalid (messages.invalid_year) no matter which year I'm posting.

Thanks for your help!


Best
Christian

**Comment by xabbuh** [comment]
Which PHP version do you use?

**Comment by exchentrix** [comment]
I'm using PHP 7.0.8-3.

**Comment by xabbuh** [comment]
@exchentrix Could you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by exchentrix** [comment]
@xabbuh Sure. I've forked the standard edition and made the changes in the 2.8 branch: https://github.com/exchentrix/symfony-standard/tree/2.8 

Some strange stuff is going on there. If I use the normal entity in the FormType

    'data_class' => 'AppBundle\Entity\Foo',

and the corresponding class in the controller for handling the form request,

    $foo = new FooEntity();

the validator is working as expected. "1500-01-01" brings me the correct error message. When I change the _data_class_ to _'AppBundle\Model\Foo'_ and in the controller _$foo = new FooModel()_, then the GreaterThan-Validator is not working. Input of "1500-01-01" brings me, that the form is valid.

Best
Christian

**Comment by jakzal** [comment]
@exchentrix thanks to your great efforts I managed to finally reproduce this issue

**Comment by xabbuh** [comment]
@exchentrix Thank you for providing the example. I took a look at it and I could confirm your issue. However, this is in fact no bug but expected behaviour. Let me explain it: The generated Propel class does not store `\DateTime` objects in the model class' `$bar` property, but only holds a string describing the date. The getter and setter method of the model class then deal with transforming the string from and to `\DateTime` instances.

Though you can still make your validation rules behave as expected by changing the config to not access the property directly, but to use the getter method instead:

```yaml
AppBundle\Model\Foo:
    getters:
        bar:
            - GreaterThan: -100 years
```

Thus, I am closing here as there is nothing to change in the Validator component regarding your issue. But of course please feel free to come back if anything is still not clear to you.

**Comment by exchentrix** [comment]
@xabbuh Ok, thats something, I already had been thinking. The method with validating the getters instead of the properties, works like a charm. Thank you very much for the investigation.
