### ISSUE TITLE
[Form] entry_type with FQCN and empty_data issue within collection

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony#19165]
Running on an application with SF2.8, before migrating it to SF3. What I got here is, at some point in a form

```php
    // BarType.php
    $builder->add('foo', CollectionType::class, [
       'entry_type'     => new FooType(),
       'error_bubbling' => false,
       'allow_add'      => true,
       'allow_delete'   => true,
    ]);
```

Reading [this](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) I found that we need to change `entry_type` of forms from `new FooType()` to `FooType::class`.

But I've noticed something very weird: if I change `entry_type` from instance to FQCN and in embedded form (`FooType`) I use something like

```php
    // FooType.php
    $resolver->setDefaults([
        'data_class' => 'Vendor\Bundle\Entity\Foo',
        'empty_data' => new Foo(),
    ]);
```

Then, every object added to the collection are "collapsed" into the same one (e.g.: I add three elements, after form binding I got three `Foo` elements in my `Bar` object but they're all the same).

Unfortunately, now, I cannot write an example to let give you a better understand of what is going on here but I will do in the next days if anyone need it.

**Comment by HeahDude** [comment]
Hi @DonCallisto, since you define `data_class` option the `empty_data` is set handled by default to return a new entity. Could you try to remove its (what should be useless) definition to see if it solves your issue using the default behavior? Thanks.

**Comment by DonCallisto** [comment]
@HeahDude of course it resolve it (sorry but I forgot to mention that; actually a very important part).
But it's not a good behavior imho.

**Comment by HeahDude** [comment]
If you really want to hardcode a default (working) behavior maybe try:
```php$resolver->setDefaults([
    'data_class' => 'Vendor\Bundle\Entity\Foo',
    'empty_data' => function() {
        return new Foo();
    },
]);
```

**Comment by HeahDude** [comment]
Anyway I don't think this is a bug, but I might be wrong...

**Comment by DonCallisto** [comment]
@HeahDude I'm not arguing here about `new Foo()`, I'm just saying that if you use them in combination (as you could do with `new FooType()` instead of `FooType::class`), this scenario will collapse your collection into a collection where all elements are the same (and no, that's not the *right* or *expected* behavior).

Why shouldn't this be a bug, if collections doesn't act like collections and no one force me to avoid an instantiation in `empty_data` if I'm using a FQCN  as `entry_type`?

**Comment by HeahDude** [comment]
It's not a bug to me since `CollectionType` uses the same nested type for each entry, so by hardcoding empty data (and needlessly overwriting the default behavior) the same instance is used as `empty_data` for every entry.

So I consider this is a bad usage, but again I might be wrong.

**Comment by DonCallisto** [comment]
@HeahDude Umh, so you think that collection objects are the same object for that reason. Right, it could be.

By the way if I `spl_obj_hash` onto embedded form I see that not only the underlying data `Foo` is the same for the collection, but also the forms that keeps them. The same thing is not true if avoid `empty_data`.

This sounds very weird. Hopefully someone more involved than me could help to understand if it's a bug or not.

**Comment by HeahDude** [comment]
Have you tried:
```php
$resolver->setDefaults([
    'data_class' => 'Vendor\Bundle\Entity\Foo',
    'empty_data' => function() {
        return new Foo();
    },
]);
```
?

**Comment by DonCallisto** [comment]
@HeahDude No, I didn't. But the issue is that, from documentation, you can use `new Foo()` and this, as said before, cause the issue. It's not about "how to make it works". Without any `empty_data` it works like a charm: maybe this options should be avoided if you use FQCN and not `new` (so basically it should be avoided from sf3 on, as I've read into changelog) and, so, should be an option that should be removed from form component.Or if this is a bug, should be fixed.

Any other thoughts?

**Comment by HeahDude** [comment]
>No, I didn't. But the issue is that, from documentation, you can use new Foo() and this, as said before, cause the issue. It's not about "how to make it works".

It is about "how to make it works" IMHO, since this issue may be a documentation issue. A better doc prevents misusage.

Also I'm pretty sure that:
```php
'empty_data' => function() {
    return new Foo();
},
```
solves it, could you please confirm?

**Comment by DonCallisto** [comment]
@HeahDude I'll try it in the week and and let you know.

Honestly, what you said has sense: if there is a sort of lack in the documentation, is still worth of effort try and fix the docs.

BTW, in case of your fix works, I suggest to update also [this](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) in order to avoid mistakes

**Comment by DonCallisto** [comment]
@HeahDude Just tried and it works with closure. Thank you for support!

**Comment by HeahDude** [comment]
@DonCallisto Great! Let's close here then, I'll deal with it in https://github.com/symfony/symfony-docs/pull/6265. Thanks!
