### ISSUE TITLE
[RFC] [DependencyInjection] Automatically detect definitions class based on their factory

### ISSUE THREAD

**Issue by Ener-Getick** [symfony/symfony#19161]
Thanks to the features of php 7.0 we can now guess the class of a service created with a factory:
```php
function myFactory(): MyServiceClass
{
}
```

So I propose to create a new pass to automatically update the services definition when possible. This is particularly useful for autowiring (this way you don't have to copy-paste the class name of the service, especially when this is from a third party library).

What do you think ?

An implementation could be [this](https://github.com/Ener-Getick/symfony/blob/c17d12d9bfac320e3522f15dfeefc3a7504486d6/src/Symfony/Component/DependencyInjection/Compiler/FactoryReturnTypePass.php).

**Comment by ro0NL** [comment]
@Ener-Getick what if the factorized object is a subclass of `MyServiceClass`? Or the return-type is set to some interface? Or is this only a cosmetic value?

**Comment by TomasVotruba** [comment]
This is must have. Already know it from other DI frameworks.

**Comment by Ener-Getick** [comment]
I opened #19191, please review it in case you see something to change :)

**Comment by TomasVotruba** [comment]
Thank you @fabpot  and @Ener-Getick

**Comment by Ener-Getick** [comment]
You're welcome :)
