### ISSUE TITLE
DomCrawler: Support for evaluate

### ISSUE THREAD

**Issue by aight8** [symfony/symfony#19162]
The DomCrawler missing a simple evaluate method to use even more complex xpath query strings.

**Comment by xabbuh** [comment]
Can you provide an example of what you actually would like to achieve?

**Comment by aight8** [comment]
Sure! Imagine you want to fetch only a part of an attribute - because the ID is a part of a url. In this case currently you first fetch the attribute with the attr method and then make the extraction with regex or however. But this is not necessary because you can do the full query with XPath:

```
substring-after(/dt/@id, '_')
```

or

```
substring-before(substring-after(/span/@style, ' '), '%')
```

This allows crawlers to be more accurate and work without extra coding. Only with string configurations.

Currently you can only filter and then get the text, html or full attribute of a node.

It's important to query this in the sub crawler when used otherwise it's query from root.

I imagine a method something like ->evaluate(exp : string) (same name like on \DOMXPath class). Then this query is queried on the current context and return's a string or whatever result it contains instead of a Crawler.

**Comment by jakzal** [comment]
@aight8 would you mind having a look at #19430? :)

**Comment by mpyw** [comment]
👍
