### ISSUE TITLE
[Profiler] creates two profiles per request with empty layout

### ISSUE THREAD

**Issue by exchentrix** [symfony/symfony#19179]
Hey,

I'm noticing some strange profiler behaviour. It creates two profiles for each request. This is my layout:

    <body>
        {% block body %}{% endblock %}

When requesting /login the profiler will create and store two profiles.

### token 072206 (normal token in the debug toolbar)

![1](https://cloud.githubusercontent.com/assets/1130714/16355721/8a0c04fa-3ac0-11e6-95ac-9bc5f75e0d1d.png)

![request](https://cloud.githubusercontent.com/assets/1130714/16355723/9ebc8f8c-3ac0-11e6-8479-7a74df038dda.png)

### token 4d060b (strange token)

![2](https://cloud.githubusercontent.com/assets/1130714/16355729/c622424c-3ac0-11e6-8eeb-f50ce11466db.png)

![request2](https://cloud.githubusercontent.com/assets/1130714/16355731/d74f2c74-3ac0-11e6-83c6-2bf83ee0e664.png)

When I subrequest the app (e.g. add twigs render(controller) method), then for each subrequest, there are also two profiles created. Note, that the same controller methods are profiled with different times...

I'm using vagrant with PHP 5.6 and symfony 2.8.7. I'm trying to figure out where this comes from.

Or is this the normal behaviour because of the _wdt? If I disable debug toolbar, there are also two profiles created.

### Update: 

I noticed, that this is not happening every time. The problem is gone now, I did nothing.

I also noticed, that some of my console outputs are appearing twice (so as something is called twice).

Sometimes this output appears:

![console](https://cloud.githubusercontent.com/assets/1130714/16356006/080c7746-3aca-11e6-9235-902e73aa8788.png)

And sometimes this:

![console2](https://cloud.githubusercontent.com/assets/1130714/16356011/0f984b8e-3aca-11e6-90c7-36fd1211e34a.png)

The second output seems to be coming from _wdt, but ChromePHP doesn't show this everytime.

### Question

Anyway, does anyone know, why using MemcachedProfilerStorage is deprecated now? http://symfony.com/doc/current/cookbook/profiler/storage.html 

"In Symfony versions prior to 3.0, profiles could be stored in files, databases, services like Redis and Memcache, etc. Starting from Symfony 3.0, the only storage mechanism with built-in support is the filesystem."

If you are using vagrant with NFS on windows hosts, there can be 404 errors when developing the app, due the poor write performance of NFS: https://github.com/symfony/symfony/issues/15462#issuecomment-228376831 (the debug toolbar tries to grab the profile, which is not yet created, so it retrys) I described it here: https://github.com/winnfsd/vagrant-winnfsd/issues/46#issuecomment-228533482

In my case switching to MemcachedProfilerStorage solved the problem, so it would be nice if we can reimplement the different StorageProfiler types again...

### Update

Thanks to https://github.com/winnfsd/winnfsd/issues/22 and his write performance improving for winnfsd. Profiler things are fine now. So for me there is no need for MemcachedProfilerStorage anymore.

I will close this. I Dont know where the error with the double profile creation came from, but I will have an eye on it.

Best
Christian

**Comment by adamsafr** [comment]
I've got the same problem after adding 3rd render(controller) method to layout.
Updating logs and cache to internal vagrant directory instead of writing to the NFS share helped me.
AppKernel.php code:

```php
class AppKernel extends Kernel
{
    // ...

    public function getCacheDir()
    {
        if ($this->isDevOrTestOnVagrant()) {
            return $this->getVagrantDir().'/var/cache/'.$this->getEnvironment();
        }

        return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        if ($this->isDevOrTestOnVagrant()) {
            return $this->getVagrantDir().'/var/logs';
        }

        return dirname(__DIR__).'/var/logs';
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }

    private function isDevOrTestOnVagrant()
    {
        return file_exists($this->getVagrantDir()) && in_array($this->getEnvironment(), ['dev', 'test']);
    }

    private function getVagrantDir()
    {
        return '/home/vagrant/Code-cache/'.basename(dirname(__DIR__));
    }
}
```
