### ISSUE TITLE
[Profiler] Queries in doctrine should have order or time if more connections.

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#19170]
hello ...

I'm using more doctrine conenctions .. and it will be good to know, time when was query executed or total query order of all connections

It would be good to know time when was query executed even if one connection

**Comment by javiereguiluz** [comment]
@poolerMF thanks for proposing this improvement. I think it makes sense. However, this is something to be implemented in the DoctrineBundle ... so I've opened an issue there to discuss about it: https://github.com/doctrine/DoctrineBundle/issues/588  Thanks!
