### ISSUE TITLE
[Testing] $client->disableReboot() broken

### ISSUE THREAD

**Issue by multi-io** [symfony/symfony#19178]
When doing functional testing using the test client (Symfony\Bundle\FrameworkBundle\Client) and disabling kernel reboots between requests using `$client->disableReboot()`, upon the 2nd request I'm running into this:

https://github.com/symfony/symfony/blob/7617492914bb21672003fc7d30511bc0da9693ad/src/Symfony/Component/HttpFoundation/Session/Storage/MockArraySessionStorage.php#L134

I don't have a test case right now, but you should be able to reproduce this easily.

**Comment by xabbuh** [comment]
Closing this one as a duplicate of #13450.
