### ISSUE TITLE
Doctrine database configuration and the Symfony book

### ISSUE THREAD

**Issue by AscanderS** [symfony/symfony#19196]
This is a discrepancy between the Symfony book and Symfony version 2.8 (at least) which is very disturbing for someone trying Symfony with PostgreSQL for the first time.
   
On page http://symfony.com/doc/2.8/book/doctrine.html It is explained that setting database_driver on app/config/parameters.yml allows to choose a driver. 

```
# app/config/parameters.yml
parameters:
    database_driver:    pdo_mysql

```
However, parameter database_driver is not used (at least in version 2.8) since in app/config/config.yml you find that pdo_mysql is wired:

```
# app/config/config.yml
doctrine:
    dbal:
        driver:   pdo_mysql

```
The solution would be, on new projects, to add database_driver parameter in app/config/parameters.yml and change app/config/config.yml to use database_driver parameter:
```
# app/config/parameters.yml
parameters:
    database_driver:    pdo_mysql
...
# app/config/config.yml
doctrine:
    dbal:
        driver:   "%database_driver%"

```

**Comment by iltar** [comment]
https://github.com/symfony/symfony-standard/blob/master/app/config/config.yml#L43

It's supposed to be a hard config. Parameters are supposed to differ per server environment. You never (should ever) have different drivers per server environment. 

[In this example][1], the parameter is used, but should IMO just be configured without. You could open an issue in the docs repository about that.

[1]:http://symfony.com/doc/2.8/book/doctrine.html#configuring-the-database

**Comment by fabpot** [comment]
This is indeed a docs issue.

**Comment by AscanderS** [comment]
Right. I'll post it there. Thanks.

**Comment by xabbuh** [comment]
Closing in favour of symfony/symfony-docs#6691.
