### ISSUE TITLE
Invalid Exception

### ISSUE THREAD

**Issue by theLordz** [symfony/symfony#19208]
Hello,

After the last commit we get this:

[InvalidArgumentException] Tagged form type extension must have the extended type configured using the extended_type/extended-type attribute, none was configured for the "form.type_extension.upload.validator" service.

Where do we have to configure this?

**Comment by ro0NL** [comment]
@theLordz see #19207

**Comment by fabpot** [comment]
fixed in #19211

**Comment by theLordz** [comment]
@ro0NL @fabpot Thank you for the quick reply. Everything back to normal. 👍
