### ISSUE TITLE
Unvalid service "cache.default_redis_provider" in Symfony 3.1

### ISSUE THREAD

**Issue by arno14** [symfony/symfony#19202]
I have a simple test that iterate over every registered service in the container.
Since I upgraded to 3.1 I have an error on the service "cache.default_redis_provider":
```
Class "Predis\Client" does not exist
```
How can I configure my application to disable this service?

**Comment by stof** [comment]
You can change the configuration for ``framework: cache: default_redis_provider`` to set it to ``null`` rather than ``'redis://localhost'``, so that it does not register a redis pool

**Comment by arno14** [comment]
That works fine
thanks
