### ISSUE TITLE
Date validation refuse valid dates

### ISSUE THREAD

**Issue by trendkill** [symfony/symfony#19206]
In Symfony-2.7.9, I am using a form with type date, 'format' => 'dd-MM-yyyy' and 'widget' => 'single_text'. So, when a user inputs certain date like '12-12-2090', the form will be invalidated with this valid date.

Tested with invalid form result: 12-12-2090
Tested with valid form result: 12-12-2012

Did someone know why happen this erratic behavior?

**Comment by xabbuh** [comment]
Which PHP version on which platform do you use?

**Comment by trendkill** [comment]
PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31) on Debian GNU/Linux 7.9 (wheezy)

**Comment by xabbuh** [comment]
Is your local PHP version built for 32 or 64 bit support?

**Comment by javiereguiluz** [comment]
`12-12-2090` corresponds to the `3816716400` timestamp, which overflows on 32bit systems because `PHP_INT_MAX` is `2147483647`.

Anyone can suggest a solution for this issue? Or is it "impossible" and the only solution is to upgrade to 64bit? Thanks!

**Comment by mvrhov** [comment]
AFAIR it's been upgrade to 64bit since forever.

**Comment by xabbuh** [comment]
Is there anything we can do here? I mean even if PHP is not able to create a valid `Date` instance for the given date what are we supposed to do? Furthermore, using a 64bit version of PHP should mitigate the issue as it supports a broader range of dates.

**Comment by xabbuh** [comment]
I am closing here as there isn't anything we can do in Symfony.
