### ISSUE TITLE
Isn't 201 NOT a REDIRECT

### ISSUE THREAD

**Issue by anoopmd** [symfony/symfony#19228]
Hello All,

In a project that I am working on, we are using Symfony as a middleware between the Java WebService and the browser.

Strangely Symfony converts a 201 response received from the WebService to a 302 Redirect.

I am not sure if this is the reason why this is happening. 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L1129

https://tools.ietf.org/html/rfc7231#section-7.1.2

Any suggestions would be of great help.
Thanks in advance.

**Comment by anoopmd** [comment]
[https://github.com/symfony/symfony/issues/12347](url)

**Comment by ro0NL** [comment]
Well.. browsers dont do it :) At first sight `201` being valid for `isRedirect` seems weird, especially compared to `isRedirection`.

My guess it's related to implementation code that rely on the `Location` being present. Can you specify where the conversion happens?

I think its considerable to deprecate the outcome for 201 with isRedirect and change its behavior.

**Comment by apfelbox** [comment]
See #608

**Comment by Tobion** [comment]
Duplicate of #12347
