### ISSUE TITLE
Symfony serializer Circular __construct

### ISSUE THREAD

**Issue by electromuis** [symfony/symfony#19232]
I had a bug in my code which went as follows:

```php
    public function getAsOptional(){
        return new self([], array_merge($this->optionalFields, $this->requiredFields), $this->flags);
    }
```

This together with the GetSetMethodNormalizer makes an infinite loop of new Objects. It filled all 8 gigs of ram, php just threw the 60 second timeout.

Would it be an idea to update `Symfony\Component\Serializer\Normalizer\AbstractNormalizer->isCircularReference` for this case?

**Comment by xabbuh** [comment]
Can you provide a failing test case?

**Comment by dunglas** [comment]
Your code looks weird. This isn't a circular reference as this always a new instance that is returned. It looks to me like the normal behavior of the serializer too try to serialize those relations. If you want to exclude it, use serialization groups.

**Comment by ro0NL** [comment]
@dunglas i dont think its weird, although the domain log may be weird to allow for an inifinite chain, there are often methods that return `self` with a different spec (i.e. `getParent`). I can imagine you want to include it till a certain depth, ie im not sure the user should fix this in code as the serializer is triggering infinite calls here.

**Comment by dunglas** [comment]
@ro0NL there is the `@MaxDepth` annotation for that: https://github.com/symfony/symfony/pull/17113 (it still needs to be documented...)

**Comment by ro0NL** [comment]
Didn't know that :) But that's awesome.

I guess @electromuis has 3 options then; 1) exclude it, 2) include it with max depth or 3) refactor to return null at some point.

**Comment by electromuis** [comment]
I already fixed if by renaming the function to asOptional(). The point was i am using a bundle which initializes the serializer as a new instance, so the only way to change the serializer config would be to branch and modify that bundle myself.
I tought this would be something nice to implement, especially since there already is a place for it and like @ro0NL said, this is something that might happen. I didn't have the time to do that myself, else i would have.

**Comment by ro0NL** [comment]
@dunglas do you think it makes sense to have a default max depth? Say 500 or so?

**Comment by dunglas** [comment]
I've no strong opinion about that, but I think it's the developper responsibility to handle such edge cases.

**Comment by electromuis** [comment]
The biggest problem wat the 3 hours trying to find the problem, my ram spaced out. I only found it when i temporarily echoed out the classnames in the normalizer. After the php timeout i saw the ever repeating classname.

![img-20160629-wa0009 jpg](https://cloud.githubusercontent.com/assets/1395336/16563443/63258c28-4202-11e6-9a94-a97c29f1c6bc.jpeg)

**Comment by javiereguiluz** [comment]
> do you think it makes sense to have a default max depth? Say 500 or so?

I'd agree with that!  This would be similar to the protection applied by Xdebug via the max function nesting level, which is 256 (was 100 before Xdebug 3.2).

**Comment by ro0NL** [comment]
@javiereguiluz checked it out a bit... currently it's disabled entirely by default, however it could be simplified in some ways;

```
$maxDepth = null; // default, ie 256
$maxDepth = 0; // or -1, \INF, ie unlimited, ie disabled
$maxDepth = 434; // whatever value
```

Do you think it's worth it? ping @dunglas

**Comment by dunglas** [comment]
Why not, but it needs:

1. to be benchmarked (we shouldn't decrease performance for such an edge case)
2. be explicitly documented

**Comment by ro0NL** [comment]
Compared to disabled it's about 4-8ms slower for 1000 nested objects and max depth set to 1001.

**Comment by xabbuh** [comment]
What do we do here?

**Comment by ro0NL** [comment]
If the initial problem is solved one way or another, i would close it for now. Changing the serializer behavior is out of scope anyway. Maybe i can do a PR in the near future..

**Comment by javiereguiluz** [comment]
Let's close this issue as recommended by @ro0NL. The improvements or changes to the Serializer component, if any, should be discussed in a separate issue. Thank you all for helping @electromuis.
