### ISSUE TITLE
CollectionType prototype_data based on initialized object

### ISSUE THREAD

**Issue by Glideh** [symfony/symfony#19231]
I know that we can use `prototype_data` to define the initial data of collection embedded forms.

Is there a way to base these initial data on the related initialized object ?

```php
class Product {
    private $type = 'food';
    private $enabled;

    public function __construct()
    {
        $this->enabled = true;
    }
}
```

Embedding a product collection into a `ShoppingCart` form

```php
class ShoppingCartFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('products', CollectionType::class, array(
                'data_class' => Product::class,
            // ...
            )
    }
}
```

The prototype will not take the default values from the entity whereas a `ProductForm` would.

**Comment by HeahDude** [comment]
A prototype is not "hydrated" by some entity's data but only view data. What do you mean exactly?

**Comment by Glideh** [comment]
I forgot to mention, I mean for a field with a specific `data_class`: here `Product`

**Comment by HeahDude** [comment]
It is but on submission only, not on initialization. I mean a prototype does not initialize empty entity, but a submitted prototype (actually its view data) will hydrate a new entity.

**Comment by Glideh** [comment]
I see, it makes sense for me now.

Specifying this is simple enough
```php
'prototype_data' => new Project()
```
