### ISSUE TITLE
Missing root namespaces for @expectedException

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#19237]
I noticed this at the workflow component and decided to do a quick scan

Im talking about `@expectedException \Exception` vs. `@expectedException Exception`. Without `use` statements the latter works for phpunit but breaks editor click-throughs, at least phpstorm.

Searched with `@expectedException\s+[^\\\s]` with 34 results on master (not checked for `use` statements). Perhaps something to automate?

Not sure about [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerNameParserTest.php#L111) one :-)

**Comment by fabpot** [comment]
This should be added to PHP-CS-Fixer indeed. Can you make the suggestion there?

**Comment by fabpot** [comment]
Closing as there is now an issue on PHP CS Fixer
