### ISSUE TITLE
[DX] Improve the error message when the command is not found

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#19258]
### Problem

Today I spent some minutes trying to figure out why Symfony told me that `Command xxx is not defined` although the command was indeed defined as usual.

The reason was that the command file name didn't end in `Command` (it was `Whatever.php` instead of `WhateverCommand.php`).

[A question about this](http://stackoverflow.com/questions/16060529/symfony2-custom-console-command-appears-as-not-defined-upon-execution) on StackOverflow has 5,387 views and the answer has been upvoted 28 times.

### Solution

When you mess up PHP classes, namespaces and file names, Symfony displays perfect error messages about the problem and the possible solutions.

Could we do the same for commands? Ideally, check if the command class exists but the file name lacks the `Command` suffix. If not possible, at least display a message like:

```
Command xxx is not defined. Did you forget to add the `Command`
suffix to the command's file name?
```

**Comment by stof** [comment]
> Ideally, check if the command class exists

How can we check that the class exists ? We don't know the class name implementing a command with this name.

Btw, if your class was already named WhateverCommand, it would not exist either, because the autoloader would not find it...

**Comment by javiereguiluz** [comment]
> How can we check that the class exists ?

Not possible technically. The alternative solution would be very complex:

* Transform the command name into a class name (foo:bar -> FooBar)
* Look for PHP files with names not suffixed by `Command` in the `Command/` dir of every bundle 
* Let `levenshtein` decide if some of those files is closely related to the missing command.

In any case, a simple message "Did you forget ..." would be enough.

**Comment by stof** [comment]
> Transform the command name into a class name (foo:bar -> FooBar)

Except that this will not work for many cases (for instance due to command namespacing)

**Comment by GromNaN** [comment]
> Look for PHP files with names not suffixed by Command in the Command/ dir of every bundle

This is the only working solution. When the `Command` dir is scanned.

**Comment by javiereguiluz** [comment]
Closing this proposal as "won't fix" because sadly it's very difficult (nearly impossible) to do it right. Thanks for your comments.
