### ISSUE TITLE
Symfony Form Builder twig

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#19263]
on my controller:

```
return $this->render('AppBundle:Site:index.html.twig', array(
'form' => $form->createView()
));
```
on index.html it's show's the form. but on my index.html.twig i have:

```
{% extends 'AppBundle::layout.html.twig' %}
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}
```
any nothing will show. symfony show only on index.html.twig but no also on the twig like load it once. i'm using Symfony 3.1 thanks

**Comment by HeahDude** [comment]
Any code in a twig template extending another should be lying in blocks:
```twig
{% extends 'AppBundle::layout.html.twig' %}

{% block some_block_name %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}
```
See http://twig.sensiolabs.org/doc/tags/extends.html#child-template.

**Comment by ben29** [comment]
i don't understand..
this is my index.html.twig:
```
{% extends 'AppBundle::layout.html.twig' %}
{% block title %}TEST{% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}
```
this is my layout.html.twig:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="he" lang="he" dir="rtl">
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
<body>
    {% block body %}{% endblock %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</body>
</html>
```

**Comment by HeahDude** [comment]
A form view cannot be rendered twice, so once it's rendered in the body block it's not in the parent layout.

**Comment by ben29** [comment]
i need that the form will upper on the top. and the bottom.
any solution for that?

**Comment by HeahDude** [comment]
You can use `set` tag but you should not since it would duplicate html attributes, this is not a good practice and a little hacky:
```twig
{% set form_view %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endset %}

{# then call #}
    {{ form_view }}
{# many times #}
```

**Comment by ben29** [comment]
finally i did 2 forms...
but the "<form name=form">
it's in the same codes.
how can i change this name ?!
```
        $form = $this->createFormBuilder($contact)
            ->add('fullname', TextType::class)
            ->getForm();
....
```

```
        $form2 = $this->createFormBuilder($contact)
            ->add('fullname', TextType::class)
            ->getForm();
```

**Comment by xabbuh** [comment]
You have to use the `createNamedBuilder()` method from the `FormFactory` class (which is  accessible  as the `form.factory` service).

Anyway, I am closing here as we don't use GitHub for support questions. For that please refer to one of the support channels on https://symfony.com/support.
