### ISSUE TITLE
[HttpKernel] Passing arrays as URI attributes to the ESI and SSI renderers

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#19262]
Hello!

> Passing objects as URI attributes to the ESI and SSI renderers has been deprecated and will be removed in Symfony 4.0. The inline fragment renderer should be used with object attributes.

I have an deprecation error when I try to render
``` twig
{{ render_esi(controller('AppBundle:Default:widget', { 'data': { 'foo': 'bar' } })) }}
```

Is this an error in documentation and it's only possible to pass scalars?
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Fragment/AbstractSurrogateFragmentRenderer.php#L100

**Comment by xabbuh** [comment]
@BoShurik Where did you find that example in the documentation?

**Comment by BoShurik** [comment]
@xabbuh https://github.com/symfony/symfony/blob/master/UPGRADE-3.1.md#httpkernel
Or you mean the code? It's not from the documentation

**Comment by xabbuh** [comment]
Well, you asked if there was an error in the documentation. That's why I asked where you found that example code. The part of the upgrade file you linked to clearly states that passing objects to the ESI fragment renderer should be avoided as this is deprecated.

**Comment by BoShurik** [comment]
@xabbuh but in my example I pass an array, not an object

**Comment by xabbuh** [comment]
@BoShurik Ah sorry, I see your point. Yes, I think we have to improve the deprecation message. It's not only object values that are deprecated now, but this applies to all non-scalar values.
