### ISSUE TITLE
Http Firewall ExceptionListener : setTargetPath() should not be called on subrequests

### ISSUE THREAD

**Issue by gggeek** [symfony/symfony#19285]
In cases where a subrequest triggers an auth error, the ExceptionListener stores the url of the subrequest as targetPath.
Once the user logs in, he lands on the url for the subrequest instead of the url he should land on.

This happens with fos_user_content_hash as well as with _fragment urls.

Related issues:
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/302
https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287

**Comment by iltar** [comment]
Sub-requests are not supposed to trigger the security component though

**Comment by gggeek** [comment]
@iltar well, it seems that they do in real life...

**Comment by iltar** [comment]
How do you trigger it?

**Comment by gggeek** [comment]
It happens f.e. when:
- the fos http cache bundle route used to generate a user_hash is protected by a firewall rule, and sf http cache is on ( which then will trigger the subrequest to /_fos_user_context_hash when the user visits /login)
- in an eZPublish application, one of the controllers used for subrequests tries to load a Content from the Repository which the user does not have access to

**Comment by iltar** [comment]
This line explicitly checks for the request type: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall.php#L49

So if it's triggered anyway, it's a master request. If I understand the caching correctly, it will simply do a GET on another URL, which is then a master request. This url should not be protected because it's cached afaik.

The second one sounds like it's simply throwing the wrong exception.

**Comment by gggeek** [comment]
ps: the 2nd is an interesting case: the same 'logical' action (trying to load a content for which you do not have access rights) is actually requested to send the user to the login screen, at least in the case where the user is viewing said content as its main controller...

**Comment by iltar** [comment]
That's probably an http access exception and not a normal access exception

**Comment by gggeek** [comment]
Uhm, sounds reasonable.
I will try to do a few more tests to find out if the fos_http_cache request is actually a subrequest, and the exact type of exception thrown by eZPublish when accessing protected content in a subrequest...

**Comment by dbu** [comment]
the FOSHttpCacheBundle hash lookup request is not a subrequest in symfony. it is done from HttpCache or from Varnish, so from the view of symfony, it is a separate request. sub requests happen when you let twig call another controller to render part of your page.

**Comment by javiereguiluz** [comment]
@gggeek did you manage to make more tests about this? Thanks.

**Comment by jakzal** [comment]
@gggeek since the related issue is fixed (https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287#issuecomment-230026120), can this one be closed as well?

**Comment by xabbuh** [comment]
I am closing here. @gggeek Please leave a comment if you still encounter this issue and we can consider to reopen.
