### ISSUE TITLE
[Cache] AbstractCacheAdapter uses specific CacheItem implementation

### ISSUE THREAD

**Issue by jayS-de** [symfony/symfony#19294]
The AbstractCacheAdapter guards the save methods for a specific CacheItem implementation

```
public function save(CacheItemInterface $item)
    {
        if (!$item instanceof CacheItem) {
            return false;
        }
        if ($this->deferred) {
            $this->commit();
        }
        $this->deferred[$item->getKey()] = $item;
        return $this->commit();
    }
```
[AbstractCacheAdapter::save](https://github.com/symfony/symfony/blob/c53cb57b9ddb0e97c3596772d4b4a66c0db14091/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L288)

It may be useful, to get rid of this guard check so it would be possible to use different cache item implementations

**Comment by nicolas-grekas** [comment]
From [PSR-6](http://www.php-fig.org/psr/psr-6/) (and technically legitimate):
`Calling Libraries SHOULD NOT assume that an Item created by one Implementing Library is compatible with a Pool from another Implementing Library.`
