### ISSUE TITLE
[RFC] Integrating the Cache component in the Symfony Profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#19297]
The community is very excited with the new Cache component, so it's time to integrate it with the Profiler. 

**My questions**:
- Which information about the Cache would you like to see in the Web Debug Toolbar?
- Which information would you like to see in a dedicated Cache profiler panel?

Thanks!

**Comment by HeahDude** [comment]
I guess it would be useful to list the used adapters and a hit/miss count.

**Comment by DZunke** [comment]
A list of the called cache-keys (and -tags?) with hit / miss / wrote status. That would be nice. :smile:

**Comment by javiereguiluz** [comment]
@HeahDude something like this?

| Pool | Type | Hits | Misses
| ---- | ---- | ----: | ------:
| cache.app | APCu | 320 (95%) | 43 (5%)
| cache.system | filesystem | 4,309 (99%) | 67 (1%)
| app.cache.custom | Redis | 120,874 (99%) | 320 (1%)

**Comment by javiereguiluz** [comment]
@DZunke something like this?

#### Cache Operations

| Key | Tags | Action | Status
| --- | ---- | ------ | -------
| `reviews-25` | - | GET | OK
| - | `products` | INVALIDATE | OK
| `review-25` | - | SAVE | OK

**Comment by DZunke** [comment]
@javiereguiluz yeah, something like this. Maybe with the pool that was called for the combination. This would be, in my opinion, very useful.

**Comment by HeahDude** [comment]
Looks like a good start to me :)

**Comment by HeahDude** [comment]
@javiereguiluz One should be able to choose which pool to trace with an entry limit otherwise `Cache Operations` section may be very long!

**Comment by DZunke** [comment]
@HeahDude @javiereguiluz i understand to be carefully with the psr cache interface but maybe there is a way to get a debug setting for the adapters to switch tracing? Or a special tracable proxy adapter to decorate the cache adapter in dev mode like the ```TraceableEventDispatcher```?

**Comment by layanto** [comment]
Maybe some inspiration can be gained from Profiler of StashBundle
https://github.com/tedious/TedivmStashBundle/pull/90

**Comment by javiereguiluz** [comment]
@layanto that's definitely a good idea! I'm pasting here some screenshots for reference:

#### Web Debug Toolbar

![stash_wdt](https://cloud.githubusercontent.com/assets/73419/16614470/bb9a54ae-4371-11e6-9c91-2b3a8789e3d2.png)

#### Profiler

![stash_profiler](https://cloud.githubusercontent.com/assets/73419/16614471/be66131c-4371-11e6-9365-304332ddc3c8.png)

**Comment by stof** [comment]
@javiereguiluz I don't think driver options are really useful here (they don't depend on the request). Seeing which keys were hit or missed would be more useful

**Comment by layanto** [comment]
Php-cache's cache-bundle also has integration with Profiler
https://github.com/php-cache/cache-bundle/tree/master/src

**Comment by javiereguiluz** [comment]
@layanto thanks! Do you have any screenshot of it? I can't find any.

**Comment by layanto** [comment]
I am not familiar with php-cache, only tried it just now to get the screen captures below:
![toolbar](https://cloud.githubusercontent.com/assets/245078/16616234/377cfda4-43bf-11e6-8085-7360076ac583.png)
![profiler](https://cloud.githubusercontent.com/assets/245078/16616238/3a2afbaa-43bf-11e6-9922-1fb28b42a53e.png)

**Comment by iltar** [comment]
Personally I would also like to see which cache keys were called and what their status was, this would be nice in a more detailed view

**Comment by rvanlaak** [comment]
I've also been working with the `cache-bundle` profiler panel that @Nyholm created, which already does quite a decent job. What about using that bundle, it also allows to easily configure caching services via yml directly.

**Comment by ProPheT777** [comment]
Good job! It's a detail but the logo looks like redis which can be confused.

**Comment by Renrhaf** [comment]
Excellent, I was also thinking that such a data collector might be really useful when using the new cache component.

**Comment by Koc** [comment]
Hits/misses in debug toolbar has no sense:
* on dev env usually are null adapter used
* this is dev env and nobody cares about hit ration

Instead of this it would be better store information about misses on production. And maybe also share it across requests for getting complete information.

**Comment by Renrhaf** [comment]
I do not agree, on some projects we are working with redis adapter even on dev, and gathering info about hit/misses might be useful to search for optimizations.

**Comment by Koc** [comment]
yes, but this useful when you do monitoring live environment on real load

**Comment by spreling** [comment]
This would be a created addition for the cache component. Any idea on when it get released? Can't wait to test it

**Comment by Nyholm** [comment]
Has anybody started to work on this issue? @javiereguiluz?

If not, I can create a first version.

**Comment by javiereguiluz** [comment]
Thanks for your help, but I'm afraid we cannot implement this yet. First we need to agree on the contents that we want to include in this panel.

**Comment by Nyholm** [comment]
Reading the tread it looks like most people would like to have statistics about hits and misses. I guess I would start with creating a collector and a simple user interface. 

This issue has been stalled for a while so I guess I started to do some work so people can test and have opinions about concrete stuff. 

But I will not do anything if you feel we should make any decisions first.

**Comment by javiereguiluz** [comment]
You are right. If there is a consensus around some basic features, we can start working on those and iterate it later.

**Comment by Renrhaf** [comment]
+1 for a first, simple collector, showing hit/misses and keys, maybe ttl too.

**Comment by Nyholm** [comment]
PR created =)
Feedback is appreciated on the PR thread. https://github.com/symfony/symfony/issues/21065
