### ISSUE TITLE
The "symfony\translation\Tests\fixtures\resources.ts" will make some mistake when use typescript in project

### ISSUE THREAD

**Issue by oustn** [symfony/symfony#19293]
I use Angular 2 with Laravel. When the webpack check the typescript files, The "symfony\translation\Tests\fixtures\resources.ts" will be treat as a typescript file. Actually it's a xml file I think. So hope you can fix it,thank. (My English is poor, don't mind it). The error information as below:

<details>
<summary>See Error Stack Trace</summary>

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,2): error TS1110: Type expected.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,7): error TS1005: ':' expected.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,21): error TS1005: ';' expected.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS1109: Expression expected.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(4,22): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(6,20): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(7,25): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(8,7): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(9,5): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(10,3): error TS1161: Unterminated regular expression literal.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(11,1): error TS1005: ':' expected.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,3): error TS2304: Cannot find name 'xml'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,7): error TS2304: Cannot find name 'version'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,21): error TS2304: Cannot find name 'encoding'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(1,38): error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(2,2): error TS2304: Cannot find name 'TS'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(3,4): error TS2304: Cannot find name 'context'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(4,6): error TS2304: Cannot find name 'name'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(4,11): error TS2304: Cannot find name 'resources'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(5,6): error TS2304: Cannot find name 'message'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(6,8): error TS2304: Cannot find name 'source'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(6,15): error TS2304: Cannot find name 'foo'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(7,8): error TS2304: Cannot find name 'translation'.

ERROR in /home/vagrant/Code/oustn_web/vendor/symfonybank/translation/Tests/fixtures/resources.ts
(7,20): error TS2304: Cannot find name 'bar'.
</details>

**Comment by stof** [comment]
It is a file in the QT translation format, which is indeed XML-based, but uses the ts extension as well.

I suggest you to configure webpack to ignore the composer vendors when looking for typescript files (it may even speed up things depending on how they implement the file lookup, by avoiding to recurse into all PHP vendors.

**Comment by javiereguiluz** [comment]
@oustn thanks for reporting this issue. However, I'm afraid that we cannot remove that file because Symfony needs it. The easiest solution, as explained by @stof, will be to configure webpack to not look for files in the `vendor/` directory of your project.

Therefore, I'm closing this issue as "can't fix". Thank you!

**Comment by aitboudad** [comment]
@oustn exclude `vendor` in your `tsconfig.json`
```json
{
  "exclude": [
    "node_modules",
    "vendor"
  ],
}
```

**Comment by zhekaus** [comment]
@aitboudad ,
It doesn't solve the problem completely :(

vendor.bundle.js:183 C:\webProj\proj1\web\node_modules\@types\node\index.d.ts
(73,13): error TS2300: Duplicate identifier 'require'.errors @ vendor.bundle.js:183sock.onmessage @ vendor.bundle.js:1732EventTarget.dispatchEvent @ vendor.bundle.js:3452(anonymous function) @ vendor.bundle.js:6552SockJS._transportMessage @ vendor.bundle.js:6550EventEmitter.emit @ vendor.bundle.js:3388WebSocketTransport.ws.onmessage @ vendor.bundle.js:1818wrapFn @ vendor.bundle.js:17178ZoneDelegate.invokeTask @ vendor.bundle.js:16589Zone.runTask @ vendor.bundle.js:16478ZoneTask.invoke @ vendor.bundle.js:16659
vendor.bundle.js:183 C:\webProj\proj1\web\src\typings.d.ts
(5,18): error TS2300: Duplicate identifier 'require'.errors @ vendor.bundle.js:183sock.onmessage @ vendor.bundle.js:1732EventTarget.dispatchEvent @ vendor.bundle.js:3452(anonymous function) @ vendor.bundle.js:6552SockJS._transportMessage @ vendor.bundle.js:6550EventEmitter.emit @ vendor.bundle.js:3388WebSocketTransport.ws.onmessage @ vendor.bundle.js:1818wrapFn @ vendor.bundle.js:17178ZoneDelegate.invokeTask @ vendor.bundle.js:16589Zone.runTask @ vendor.bundle.js:16478ZoneTask.invoke @ vendor.bundle.js:16659

**Comment by AndrewKiri** [comment]
@zhekaus Did you exclude it in `webpack.config.js`? If so - make sure to revert it and write your exclude directive in `tsconfig.json`
