### ISSUE TITLE
[Validator] constraint validators - empty values checking

### ISSUE THREAD

**Issue by qlarin** [symfony/symfony#19308]
I found a little problem with constraints validators. In almost every validator in method validate is checking that value is not null.
`if (null === $value) {
      return;
}`
That way causes some mistakes. If value will be equal to empty string or any other similar scenario, that condition will return false. I propose to change that to:
`if (empty($value)) {
      return;
}`
in reference to http://php.net/manual/en/function.empty.php#refsect1-function.empty-returnvalues

**Comment by ro0NL** [comment]
No..., no empty :) I think `NotEqualTo` is what you're looking for.

**Comment by qlarin** [comment]
I am writing about every validator ;) for example ChoiceValidator, look at validate method inside that validator

**Comment by jakzal** [comment]
Did you actually experience any problems, or your concerns are coming from static analysis of code? Most validators consider both `null` and empty string as empty values. ChoiceValidator expects an array, therefore doesn't make a check for an empty string.

**Comment by qlarin** [comment]
Yes, exactly as you wrote. I have problems when i am trying to pass empty array to this validator. But this is not an exception. I've noticed that some problems occurs with validators that extend `AbstractComparisonValidator`.

**Comment by xabbuh** [comment]
How would the validator actually act differently with the changes you suggest then?

**Comment by qlarin** [comment]
When the validator will get an empty array, or an empty string (or whatever function is considered as an empty value) will not conduct any further validation. At this point, this happens only if the null will be given explicitly.

**Comment by xabbuh** [comment]
But for a constraint that acts on collections there is no difference when the collection is empty. And for all other constraints they should simply not get passed arrays imo (you can use the `Type` constraint if you want to check the type of a property using the Validator component). Using `empty()` for the initial check is too weak due to what is actually considered an empty value.

**Comment by qlarin** [comment]
Let me give you another example, what if the developer uses `GreaterThanOrEqualValidator` (which inherits the `AbstractComparisonValidator`). Set the conditions that he wanted to was `optional`, and values must be greater than 1? If you do not give any value, despite the fact that the validator is `optional`, you will get an error validation. (Because it did not provide explicitly `null`).

**Comment by qlarin** [comment]
Perhaps `empty()` is too general method. I wonder is not it better to give the opportunity to check such a condition in a class that inherits. In abstract would only be a reference to the method for example. `CheckIfEmpty()`. Method would return `Boolean` value. Main method `validate()` does not interested in what would happen inside the method that is responsible for checking empty values. This gives greater flexibility in building validators based on `AbstractComparisonValidator`. You can always override the child `CheckIfEmpty()` method.

**Comment by xabbuh** [comment]
What do you understand as making the validator optional?

**Comment by qlarin** [comment]
Set in `optional` collection validator.

**Comment by xabbuh** [comment]
Can you please show how you configured your constraints, what data you validate and which error you get in that case? I think I still do not properly understand your issue.

**Comment by xabbuh** [comment]
Closing here due to the lack of feedback. We can consider to reopen if the needed information are given.
