### ISSUE TITLE
Clear cache symfony 2.8 not working

### ISSUE THREAD

**Issue by oscarjg** [symfony/symfony#19301]
We have updated our project to Symfony 2.8 and when we execute `cache:clear -e=prod --no-debug` the the process never ends. The cache folders size are incrementing until 50G. The twig folder has the largest size (maybe is a clue). We needed to kill the process.

With 2.6 and 2.7 it works fine

**Comment by javiereguiluz** [comment]
@oscarjg thanks for reporting this issue. We haven't received any similar report before, so my guess is that it's caused by an edge-case not properly covered by Symfony or it's an internal issue caused by the application.

In any case, we'll need more information. For example, does the following command work?

```
cache:clear -e=prod --no-debug --no-warmup
```

**Comment by oscarjg** [comment]
Thanks @javiereguiluz for your fast reply. If I execute the command with --no-warmup options works fine. I updated all the files as is described on https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md. With a new symfony 2.8 project works fine too. 

With my vagrant the command is killed and in production the command finish after a lot of minutes. The results is:

2,7M  app/cache/dev
5,7G	  app/cache/prod
5,7G	 app/cache/prod/twig

Any suggestion?

**Comment by oscarjg** [comment]
I found the problem which cause the error. The paths option inside twig configuration in config.yml file cause the error. The same code on 2.7 works fine so, maybe is a "bug", some incompatibility or some  strange use case with 2.8.  I'll try to get the same error with a clean project and if get the same error again I'll know you to check it, by the moment this issue is done for me.

Muchas grácias @javiereguiluz
