### ISSUE TITLE
[BrowserKit] getAbsoluteUri() not working as expected with values that only contain query string parameters (eg. ?foo=bar)

### ISSUE THREAD

**Issue by georaldc** [symfony/symfony#19303]
Similar to URIs just containing hash values, I believe the result from getAbsoluteUri() should still re-use an existing, previous request when working with only a query string value. This actually gave me problems using a related project (goutte) where a redirect to a location containing only query string parameters was sending goutte to the wrong location.

I can create a PR if this is an actual issue.

**Comment by xabbuh** [comment]
Imo that's an issue of the server's response. Afaik a Location header musst a full URL and not only URL parameters.

**Comment by georaldc** [comment]
I'm not familiar with the rules but browsers handle this just fine. Another library I noticed that seems to handle it fine too is guzzle
