### ISSUE TITLE
Not proper exit codes for console events with default exception handler

### ISSUE THREAD

**Issue by breathbath** [symfony/symfony#19318]
I have problems with proper exit codes handling in Symfony console commands. 

To reproduce you should:
1. Create a new command e.g. migration
2. Put some code to cause a fatal php error.
3. Run the command for any env
4. Analyze the exit code, it will be 0.

Here is an example for a migration:

    class Version30160629145219 extends AbstractMigration
    {
    public function postUp(Schema $schema)
    {
        $a = $this::SOME_CONST;
    }
    ...

Then we execute:

    php app/console doctrine:migrations:migrate -e prod -n && echo $?
    
                                                               
      [Symfony\Component\Debug\Exception\FatalThrowableError]  
      Undefined class constant 'SOME_CONST'                    
                                                              
    0

The problem is in Symfony\Component\HttpKernel\EventListener\DebugHandlersListener which has a hardcoded exceptions handler for console events and does not properly handles the exit codes. 
```
if (!$this->exceptionHandler) {
            if ($event instanceof KernelEvent) {
                if (method_exists($event->getKernel(), 'terminateWithException')) {
                    $this->exceptionHandler = array($event->getKernel(), 'terminateWithException');
                }
            } elseif ($event instanceof ConsoleEvent && $app = $event->getCommand()->getApplication()) {
                $output = $event->getOutput();
                if ($output instanceof ConsoleOutputInterface) {
                    $output = $output->getErrorOutput();
                }
                $this->exceptionHandler = function ($e) use ($app, $output) {
                    $app->renderException($e, $output);
                    //probably here should be throw $e;
                };
            }
        } 
```
Of course I could use a custom exception handler as a dependency which will throw exception and also do the same job of nicely rendering them with the application component. But unfortunately it cannot get the context of Symfony\Component\Console\Application to call this method there, so I am not sure if it's even possible. It would be nice to have this possibility out of the box with the exception handler.
Thanks in advance.

**Comment by SebastienTainon** [comment]
In fact, every time an exception is thrown while a command is being executed, the exit status code is 0.

That does not make great sense, because it means the command resulted in a success, which it didn't.

Instead if an exception in thrown in a command, the exit status code should be greater than 0 so that the programs that read the output of the command can understand that there was a failure.

**Comment by jameshalsall** [comment]
@SebastienTainon this isn't true...

```
$ app/console test; echo $?


  [RuntimeException]
  error


test

1
```

@breathbath your test is wrong, you are using `&&` to combine the console command *and* the echo into a single operation, so the `echo $?` isn't returning the exit code of the console command, try this:

```
$ app/console doctrine:migrations:migrate -e prod -n; echo $?
```

and you will see the exit code is 255
