### ISSUE TITLE
Update to ICU data v. 57

### ISSUE THREAD

**Issue by victor-paumier** [symfony/symfony#19315]
Is it possible to update ICU data to last version ([v. 57](http://source.icu-project.org/repos/icu/icu/tags/release-57-1/source/)) in order to have last fixes please?
And if you do it periodically, when is the next update planned? 
Thank you

**Comment by HeahDude** [comment]
Hi @victor-paumier, you should be able to run any Intl version you want, the generated ICU data in Symfony code base is only used to run tests.

The component will use your installed version by default.

There is no planning AFAIC to generate test fixtures. It mainly depends on compatibility with version of PHP supported by Symfony.

Maybe we can close here. Thanks!

**Comment by stof** [comment]
@HeahDude that's not true. the Intl component also exposes some ICU data not available through the APIs exposed by ext-intl (see the ``Symfony\Component\Intl\Intl`` class)
