### ISSUE TITLE
Missing validation errors when uploading file exceeding upload_max_filesize

### ISSUE THREAD

**Issue by MgFrobozz** [symfony/symfony#19311]
When uploading a file whose size exceeds upload_max_filesize in /etc/php5/*/php.ini, no validation error is displayed. 

`print_r($_SERVER)` (below) shows HTTP_CONTENT_LENGTH as 600 Mb, but CONTENT_LENGTH is not set. `ServerParams.php::getContentLength` checks CONTENT_LENGTH, but not HTTP_CONTENT_LENGTH, and returns `null`

``` php
_SERVER 'Array
(
...
    [HTTP_CONTENT_TYPE] => multipart/form-data; boundary=---------------------------15270606778207862301721628084
    [HTTP_CONTENT_LENGTH] => 600001284
...
)
```

Adding this code before the call to $form->handleRequest() avoids the problem:

``` php
if (!isset($_SERVER['CONTENT_LENGTH']) && 
    isset($_SERVER[ 'HTTP_CONTENT_LENGTH'])) 
{
     $_SERVER['CONTENT_LENGTH'] = $_SERVER['HTTP_CONTENT_LENGTH'];
}
```

**Comment by norbert-n** [comment]
Maybe the upload is greater than post_max_size, so $_POST and $_FILES superglobals are empty and the validator has nothing to complain. If that happens, symfony should add a error with a post_max_size_message to the form (and not to the FileType-element).

**Comment by rparsi** [comment]
@MgFrobozz @norbert-n Not sure if this is normal php behaviour, but in my experience when the size of submitted "data" exceeds various settings in php.ini (ie `post_max_size`) php wipes everything sent in the request.  I'm not sure how symfony can prevent this; you have to upload the file first to accurately determine the size.

**Comment by MgFrobozz** [comment]
As it turned out, there were two problems:

1. If the upload file was under the limits in the /etc/nginx config file, then $form->handleRequest() ignored $_SERVER[ 'HTTP_CONTENT_LENGTH'] when $_SERVER['CONTENT_LENGTH'] was not set, and made it appear that the content length was 0.
2. If the upload file was over the nginx limit, the request never made it to app.php in the symfony app. The nginx limit was the same as the /etc/php5/*/php.ini files, making it appear that the php limit might be the problem.

My ultimate solution was to check the file size in javascript, and prevent the upload there.

**Comment by norbert-n** [comment]
@rparsi sadly this is the normal php behavior: [php.net](http://php.net/manual/en/ini.core.php#ini.post-max-size).
Symfony can't prevent this, but tries to detect it ([here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Util/ServerParams.php#L33)).

**Comment by xabbuh** [comment]
Anything we can do here? Or is this something you have to live with when using PHP?

**Comment by Nek-** [comment]
AFAIK `HTTP_CONTENT_LENGTH` is not standard. So It's normal to me that there is no support in Symfony for this custom header.

**Comment by xabbuh** [comment]
It seems there's nothing we can do here.
