### ISSUE TITLE
 can't access attribute in buildView  the attribute is set by calling setAttribute of FormBuilder in  form event listener  

### ISSUE THREAD

**Issue by videni** [symfony/symfony#19324]
```
public function buildForm(FormBuilderInterface $builder, array $options)

$builder
            ->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) use ($builder){
            //......
                $builder->setAttribute('gateways', $gatewayForms);  // pretty sure gatewayForms  is not empty
}

}
```

```
 public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['gateways'] = [];

     //somehow $form->getConfig()->getAttribute('gateways')  is null
        foreach ($form->getConfig()->getAttribute('gateways') as $type => $prototype) {
            /* @var FormInterface $prototype */
            $view->vars['gateways'][$type] = $prototype->createView($view);
        }
    }
```
Any idea please?

**Comment by HeahDude** [comment]
@videni You're mixing the builder's attributes and the form's config, you should use an option to be able to access it from both methods.

**Comment by videni** [comment]
@HeahDude, options data is passed from  configureOptions to buildForm and buildView,   I have to set the `gateways ` variable in `PRE_SET_DATA` method,  because  the variable is calculated based on  form data in PRE_SET_DATA method.

**Comment by HeahDude** [comment]
But at `PRE_SET_DATA` the form is already built, so your change on the builder does not impact its config has it is already set. Can the data you need be accessible directly in `buildView()`?

**Comment by videni** [comment]
@HeahDude , thanks for you clue, I find another to bypass this problem.
