### ISSUE TITLE
symfony/process unable to write to temp folder on windows since 3.0.8

### ISSUE THREAD

**Issue by Navi2016** [symfony/symfony#19336]
I'm using Laravel 5.2 Queue Listeners and since the update from symfony/process 3.0.7 to 3.0.8 i'm getting this message alot:

'Symfony\Component\Process\Exception\RuntimeException' with message 'A temporary file could not be opened to write the process output to, verify that your TEMP environment variable is writable' in \laravel\vendor\symfony\process\Pipes\WindowsPipes.php:56

And the process closes out, now it doesnt happen all the time, just after a while.
It works fine when using process 3.0.7.

I checked sys_get_temp_dir(); and it returned the regular windows temp directory, should be ok.
To be sure i created a C:\temp folder, opened all permissions and configured it in php.ini, but it did not make a difference. I do see some files appear in this directory:
sf_proc_00.err and sf_proc_00.out, but no sf_proc_00.check file.

I am on Windows 10 x64. Let me know if you need more details.

**Comment by xabbuh** [comment]
@Navi2016 Can you check if this is caused by the changes made in #19118?

**Comment by nicolas-grekas** [comment]
@Navi2016 can you please remove the `@` in front of `fopen` and see if you get any error message? Otherwise, can you `var_dump(error_get_last());` just before the exception is thrown?

**Comment by Navi2016** [comment]
Actually, i tried removing the @, no error appears.

It seems it only happens when i open multiple processes, then one of them closes after a while, in the meantime they do work fine.

So i thought, why don't i just comment out the Exception, so i did and then, everything is fine. So there doesnt really seem to be a problem, i think its just multiple processes trying to do the same thing / access the same thing at the same time?

**Comment by xabbuh** [comment]
@nicolas-grekas In [#19118](https://github.com/symfony/symfony/pull/19118/files#diff-456e315dc6cdf329e053bb23c7597570R55) you said that the `fopen()` call will be handled gracefully even with concurrent processes. I wonder if that might depend on the actual Windows version being used or if the issue vanishes when, for example, the process id was part of the filename.

**Comment by nicolas-grekas** [comment]
Yep, and also AFAIK, when fopen fails, a warning is always triggered...
@Navi2016 can you try mode ab instead of wb? Any better?

**Comment by Navi2016** [comment]
Same problem with ab!

**Comment by fernandobandeira** [comment]
I have a similar issue after updating the symfony/proccess to 3.0.8 i started to get the following error when i composer update my laravel project:

````
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader


  [ErrorException]
  unlink(C:\Users\ferna\AppData\Local\Temp\sf_proc_00.out): Permission denied


Script php artisan optimize handling the post-install-cmd event returned with error code 1
````

Downgraded to 3.0.7 and i don't have the problem anymore, maybe this is a related issue? Also running.
Windows 10 x64,

**Comment by nicolas-grekas** [comment]
Could you please try #19427?

**Comment by Navi2016** [comment]
Hi,

I updated to the latest version of process, same thing occured!

I commented out the exception again and it runs along fine.

Navi.

**Comment by nicolas-grekas** [comment]
The "sf_proc_00*" files should not exist anymore and the error message has been update, so this can not produce *the same* thing. What's your exact error message?

**Comment by Navi2016** [comment]
Left it running for a while, with the exception commented out, these warnings appear in the process:

PHP Warning:  fopen(C:\Webserver\phptemp\sf_proc_01.out): failed to open stream: Permission denied in C:\DATA\vhosts\spl.itypo.nl\typo3conf\ext\spl_launchpad\laravel\vendor\symfony\process\Pipes\WindowsPipes.php on line 63
PHP Warning:  fopen(C:\Webserver\phptemp\sf_proc_01.out): failed to open stream: File exists in C:\DATA\vhosts\spl.itypo.nl\typo3conf\ext\spl_launchpad\laravel\vendor\symfony\process\Pipes\WindowsPipes.php on line 63
PHP Warning:  unlink(C:\Webserver\phptemp\sf_proc_01.out): No such file or directory in C:\DATA\vhosts\spl.itypo.nl\typo3conf\ext\spl_launchpad\laravel\vendor\symfony\process\Pipes\WindowsPipes.php on line 60
PHP Warning:  unlink(C:\Webserver\phptemp\sf_proc_01.out): Permission denied in C:\DATA\vhosts\spl.itypo.nl\typo3conf\ext\spl_launchpad\laravel\vendor\symfony\process\Pipes\WindowsPipes.php on line 60

Directory is fully open and has all permissions.

**Comment by nicolas-grekas** [comment]
@Navi2016 I don't get how the warnings can be triggered: there is a local error handler that should catch them. See https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Process/Pipes/WindowsPipes.php#L56
Any idea?

**Comment by nicolas-grekas** [comment]
@Navi2016 can you please test #19579? Does it work better?

**Comment by nicolas-grekas** [comment]
ping @Navi2016 I'd really appreciate some feedback here, thanks!

**Comment by Navi2016** [comment]
Hi,

I'm working on the project tomorrow again, i will do some testing and let you know!

**Comment by Navi2016** [comment]
Sorry for the delay, have tested it and it seems to stay running OK now!
