### ISSUE TITLE
Phantom untranslated items in Symfony Profiler Translation section

### ISSUE THREAD

**Issue by Rikijs** [symfony/symfony#19332]
I am using Symfony v3.1.1 and found strange behavior while translating form submit button label.

Label is translated correctly, but there is one extra translation showing up in Translation Messages missing section!

 - What is strange is that missing translation is just a translated word, but i am using generally.approximately.precisely notation and in template there is no single words.
 - Also the phantom translation happens to show itself in messages domain, but messages domain is not used in that template...

Full description can be found on StackOverflow [here](http://stackoverflow.com/questions/38030690/symfony-3-1-translation-with-custom-domain-shows-missing-phantom-untranslated-it).

Using:
 - Symfony 3.1.2
 - Windows 10 Pro x64
 - PHP v7.0.8 (XAMPP for Windows)

**Comment by sstok** [comment]
A label is always run trough the translator in the template, even if it's already translated.
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L213

You can prevent this by setting the `translation_domain` to false: `{{ form_row(form.submit, {'label': button_submit_label, translation_domain: false, 'attr': {'class': 'button-choose-date small success'}}) }}`

**Comment by Rikijs** [comment]
Tahnks @sstok, `translation_domain: false` fixed my issue.

**Comment by stof** [comment]
@Rikijs so this was not a phantom. It was a case of double translation (translating the already translated message).
``translation_domain: false`` was implemented precisely because the profiler made us aware of such useless translation calls once we were able to see them.

**Comment by Rikijs** [comment]
Thanks @stof for clarification.
