### ISSUE TITLE
[Profiler] Error caused because of a SwiftMailer attachment

### ISSUE THREAD

**Issue by Adambean** [symfony/symfony#19345]
Hello there,

There appears to be an unhandled error in the Symfony profiler if you try to view the emails section of a request when an email contains an attachment. (The profiler bar does show the email count correctly.)

URL used: **/app_dev.php/_profiler/9c5869?panel=swiftmailer**

Error thrown:
> Neither the property "charset" nor one of the methods "charset()", "getcharset()"/"ischarset()" or "__call()" exist and have public access in class "Swift_Attachment" in @Swiftmailer/Collector/swiftmailer.html.twig at line 170

This currently happens on Symfony 2.8 though it could be due to an outdated SwiftMailer?

Actions I've attempted to resolve this:

- Updating components via Composer
- Clearing the cache (app/console cache:clear)
- Clearing the cache file system (rm -rf app/cache/*)

Some files of use have been attached here. Please let me know if you require any further details.

- [composer.lock.txt](https://github.com/symfony/symfony/files/359153/composer.lock.txt)
- [stacktrace.txt](https://github.com/symfony/symfony/files/359159/stacktrace.txt)

**Comment by xabbuh** [comment]
The Swiftmailer panel is rendered by the [SwiftmailerBundle](https://github.com/symfony/swiftmailer-bundle/). Can you please reopen this issue there?

**Comment by Adambean** [comment]
Thanks for reviewing this, I'll copy this to the SwiftmailerBundle repository.
