### ISSUE TITLE
[Symfony\Component\Debug\Exception\ContextErrorException] when clearing the cache

### ISSUE THREAD

**Issue by totechess** [symfony/symfony#19341]
I have upgraded a project from Symfony 2.3 to 3.1 and since I installed symfony/debug I am receiving this error when I try to clear the cache. Or when that command is called.

<pre><code>
[Symfony\Component\Debug\Exception\ContextErrorException] 
  Warning: mkdir(): Permission denied 
</code></pre>
 
I have run chmod -R 777 var and executed bin/console cache:clear -v and this is what I got
<pre><code>
Exception trace:
 () at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php:41
 Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
 mkdir() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php:41
 Swift_FileSpool->__construct() at /Applications/XAMPP/xamppfiles/htdocs/var/cache/dev/appDevDebugProjectContainer.php:4505
 appDevDebugProjectContainer->getSwiftmailer_Mailer_Default_SpoolService() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Applications/XAMPP/xamppfiles/htdocs/var/cache/dev/appDevDebugProjectContainer.php:4518
 appDevDebugProjectContainer->getSwiftmailer_Mailer_Default_TransportService() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Applications/XAMPP/xamppfiles/htdocs/var/cache/dev/appDevDebugProjectContainer.php:4479
 appDevDebugProjectContainer->getSwiftmailer_Mailer_DefaultService() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275
 Symfony\Component\DependencyInjection\Container->get() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/swiftmailer-bundle/EventListener/EmailSenderListener.php:55
 Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener->onTerminate() at n/a:n/a
 call_user_func() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() at n/a:n/a
 call_user_func() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:174
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:43
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:136
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:839
 Symfony\Component\Console\Application->doRunCommand() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /Applications/XAMPP/xamppfiles/htdocs/beclap.cl/bin/console:27
</code></pre>

These are my dependencies in my composer.json file
<pre><code>
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "3.*",
        "doctrine/orm": "^2.5",
        "sensio/generator-bundle": "3.*",
        "sensio/distribution-bundle": "5.*",
        "symfony/swiftmailer-bundle": "^2.3",
        "sonata-project/block-bundle": "3.0.*@dev",
        "helios-ag/fm-elfinder-bundle": "~6",
        "sensio/framework-extra-bundle": "^3.0",
        "doctrine/doctrine-bundle": "^1.6",
        "sonata-project/admin-bundle": "3.4.*@dev",
        "gedmo/doctrine-extensions": "master-dev",
        "friendsofsymfony/user-bundle": "2.0.*@dev",
        "sonata-project/core-bundle": "3.0@dev",
        "knplabs/knp-menu-bundle":"2.1.x-dev",
        "knplabs/knp-menu": "2.1.x-dev",
        "sonata-project/doctrine-extensions": "^1.0",
        "symfony/monolog-bundle": "2.*",
        "monolog/monolog": "1.*",
        "symfony/debug": "^3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.7",
        "symfony/phpunit-bridge": "^3.0"
    }
</code></pre>

**Comment by iltar** [comment]
Have you tried going to 2.8 first?

**Comment by totechess** [comment]
Yeah, I did an it worked but I was trying to upgrade to that version and I was solving every single error that it was appearing but this one is the hardest so far.

I have already modified the entire directory structure and I hope I can fix this problem too

**Comment by peterrehm** [comment]
@totechess Did you try deleting the cach folders manually?

**Comment by totechess** [comment]
Yeah and nothing

**Comment by xabbuh** [comment]
Can you please show the output of `composer show` when this is happening?

**Comment by totechess** [comment]
This is the <code>composer show</code>. There's something with SwiftMailer. SwiftMailer is trying to create that folder
<pre><code>
behat/transliterator                v1.1.0             String transliterator
cocur/slugify                       v2.2               Converts a string into a slug.
components/elfinder                 2.1.5              ElFinder FileManager
components/jquery                   1.12.4             jQuery JavaScript Library
components/jqueryui                 1.11.4             jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top...
doctrine/annotations                v1.2.7             Docblock Annotations Parser
doctrine/cache                      v1.6.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.3.0             Collections Abstraction library
doctrine/common                     v2.6.1             Common Library for Doctrine projects
doctrine/dbal                       v2.5.4             Database Abstraction Layer
doctrine/doctrine-bundle            1.6.3              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.0              Symfony Bundle for Doctrine Cache
doctrine/inflector                  v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                        v2.5.4             Object-Relational-Mapper for PHP
friendsofsymfony/user-bundle        dev-master 298f27c Symfony FOSUserBundle
gedmo/doctrine-extensions           dev-master 61904db Doctrine2 behavioral extensions
helios-ag/fm-elfinder-bundle        6.1.2              ElFinder bundle, adds ElFinder file manager to your Symfony2/3 project
helios-ag/fm-elfinder-php-connector 2.5.3              ElFinder PHP backend, 5.4 compliant
jdorn/sql-formatter                 v1.2.17            a PHP SQL highlighting library
knplabs/knp-menu                    dev-master e849f84 An object oriented menu library
knplabs/knp-menu-bundle             dev-master 42ff195 This bundle provides an integration of the KnpMenu library
kriswallsmith/assetic               v1.3.2             Asset Management for PHP
monolog/monolog                     1.20.0             Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat             v2.0.2             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common     1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   3.1.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrie...
phpdocumentor/type-resolver         0.2                
phpspec/prophecy                    v1.6.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           2.2.4              Library that provides collection, processing, and rendering functionality for PHP code coverage info...
phpunit/php-file-iterator           1.4.1              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1              Simple template engine.
phpunit/php-timer                   1.0.8              Utility class for timing
phpunit/php-token-stream            1.4.8              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     4.8.26             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        2.3.8              Mock Object library for PHPUnit
psr/cache                           1.0.0              Common interface for caching libraries
psr/log                             1.0.0              Common interface for logging libraries
robloach/component-installer        0.2.3              Allows installation of Components via Composer.
sebastian/comparator                1.2.0              Provides the functionality to compare PHP values for equality
sebastian/diff                      1.4.1              Diff implementation
sebastian/environment               1.3.7              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  1.2.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state              1.1.1              Snapshotting of global state
sebastian/recursion-context         1.0.2              Provides functionality to recursively process PHP variables
sebastian/version                   1.0.6              Library that helps with managing the version number of Git-hosted PHP projects
sensio/distribution-bundle          v5.0.7             Base bundle for Symfony Distributions
sensio/framework-extra-bundle       v3.0.16            This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle             v3.0.7             This bundle generates code for you
sensiolabs/security-checker         v3.0.2             A security checker for your composer.lock
sonata-project/admin-bundle         3.4.0              The missing Symfony Admin Generator
sonata-project/block-bundle         3.0.1              Symfony SonataBlockBundle
sonata-project/cache                1.0.7              Cache library
sonata-project/core-bundle          3.0.0              Symfony SonataCoreBundle
sonata-project/doctrine-extensions  1.0.2              Doctrine2 behavioral extensions
sonata-project/exporter             1.5.0              Lightweight Exporter library
swiftmailer/swiftmailer             v5.4.3             Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle              2.11.1             Symfony MonologBundle
symfony/phpunit-bridge              v3.1.2             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.2.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.2.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56              v1.2.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70              v1.2.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util               v1.2.0             Symfony utilities for portability of PHP codes
symfony/security-acl                v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle          v2.3.11            Symfony SwiftmailerBundle
symfony/symfony                     v3.1.2             The Symfony PHP framework
twig/extensions                     v1.3.0             Common additional features for Twig that do not directly belong in core
twig/twig                           v1.24.1            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.0.2              Assertions to validate method input/output with nice error messages.
</code></pre>

**Comment by jameshalsall** [comment]
What does your swiftmailer configuration look like in `config.yml`?

**Comment by totechess** [comment]
<pre><code>
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
</code></pre>

**Comment by nicolas-grekas** [comment]
I guess this should be reported on the swiftmailer repos, which is the component triggering the error

**Comment by xabbuh** [comment]
@totechess As @nicolas-grekas said please report this over at the Swiftmailer repository.
