### ISSUE TITLE
UploadedFile::move permissions

### ISSUE THREAD

**Issue by taviroquai** [symfony/symfony#19347]
Hi,

This is a request to add a third argument (file permissions) to the move method signature.

From the following line, we can see that there is an attempt to set the file permissions.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L230

Would it be possible to add a third argument with default permissions, ending as:

```
    /**
     * Moves the file to a new location.
     *
     * @param string $directory        The destination folder
     * @param string $name             The new file name
     * @param integer $permissions The desired file permissions 
     *
     * @return File A File object representing the new file
     *
     * @throws FileException if, for any reason, the file could not have been moved
     */
    public function move($directory, $name = null, $permissions = 0666)
```

And then applying it in the line 230:
```
        @chmod($target, $permissions & ~umask());
```

Thanks :)

**Comment by jakzal** [comment]
Adding a new argument would be a BC break. You can update permissions after file has been moved, so what's the use case for this change?

**Comment by javiereguiluz** [comment]
@jakzal you are right ... but this proposal would make it more convenient. We just need to decide if updating permissions is a common enough scenario (and then add this feature in the next Symfony version) or not (and then reject this proposal).

**Comment by taviroquai** [comment]
My 2 cents...

If setting permissions is not on the scope of this function, then, line 230 does not make sense.
If it really needs to set file permissions, then, the third argument makes a lot of sense.

**Comment by jakzal** [comment]
The method already sets permissions, which are appropriate defaults for a file. Umask is also applied, so you can turn on/off some permissions (i.e. `022` will disable write permissions for group & others). In my experience this is sufficient. That's why I asked for your use case, to understand why this change is needed.

**Comment by taviroquai** [comment]
@jakzal 
The use case is simple:

1. Using Laravel
2. Uploading a file
3. Setting file permissions 664

Having the third argument, the third step would not be needed.

**Comment by xabbuh** [comment]
@taviroquai But this should already happen when you set your umask to `022`.

**Comment by taviroquai** [comment]
@xabuuh
Sorry, I don't understand. Where do I set the umask 022?

**Comment by taviroquai** [comment]
@xabbuh 
I suppose you refering setting the umask at system level.

This request is to allow the application to set custom file permissions when moving the uploaded file, giving more flexibility without the need for the developer to repeat the chmod command after moving the file.

Line 230 already has this purpose, set file permissions, in a hard-coded way, which I think is a very bad way. Adding the third argument would, also, allow the application to not repeat this operation.

**Comment by stof** [comment]
@taviroquai but your feature request still respect the system umask. So even if you pass ``0664`` as permission, you will still get ``0644`` as actual permission when applying the ``0022`` umaks (which is the default umask in all Linux distributions I know of)

**Comment by stof** [comment]
and not respecting the system umask would be considered a security issue btw.

**Comment by taviroquai** [comment]
@stof 
That is true.

So, you are giving arguments to not let the application changing the uploaded file permissions using Symfony framework, leaving to the developer to add another operation to change it. Is that right?

**Comment by stof** [comment]
Well, I'm saying that your own proposal will not solve your use case.

**Comment by jakzal** [comment]
Closing as the related PR was rejected.
