### ISSUE TITLE
[Form] CollectionType prototype is missing some parameters

### ISSUE THREAD

**Issue by MichaelMure** [symfony/symfony#19355]
I have a form with a CollectionType with a subform. I'm trying to upgrade my project from Symfony 2.5 to Symfony 3 and face a regression.

This subform has a twig template with, among others, `horizontal_label_class` and `horizontal_input_wrapper_class` parameters for some widget. If there is already some data in the collection, the generated form is fine and respect those parameters. However, the prototype generated is incorrect and does not respect those and the UI is broken when dynamically adding new entries in the web page.

I tracked down the origin of the regression to this PR, introduced in Symfony 2.8.5.
https://github.com/symfony/symfony/pull/18317

If I roll back the three lines change in CollectionType from this PR (https://github.com/symfony/symfony/pull/18317/files#diff-148c9ca81f4d248cb20ab6ae2a3219f4L58), everything is fine again.

Other related issue:
https://github.com/phiamo/MopaBootstrapBundle/issues/1167

**Comment by HeahDude** [comment]
The error seems to come from this line: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Form/Extension/HorizontalFormTypeExtension.php#L48
`null === $form->getParent()` is not true anymore for a prototype in a collection.

**Comment by javiereguiluz** [comment]
@HeahDude so this could be considered a usage error instead of a Form component error? Thanks.

**Comment by HeahDude** [comment]
@javiereguiluz I guess it could, considering this BC break is a bug fix. But I remember I first proposed another way to fix the original issue which may not break that code.

Question is what do we want to do about it? Suggestions __@symfony/deciders__?

**Comment by xabbuh** [comment]
@HeahDude Can you maybe open a PR containing the changes that you would have done to fix the issue?

**Comment by HeahDude** [comment]
@xabbuh see https://github.com/symfony/symfony/pull/19420.

**Comment by HeahDude** [comment]
Let's close here.
