### ISSUE TITLE
[Validator] Email doesn't follow the RFC 2822 (as used by Swiftmailer)

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#19359]
Hi,

Currently when using an Email validation constraint (http://symfony.com/doc/current/reference/constraints/Email.html) there is no possibility to check the value against the RFC 2822. So it's possible to register "bad" emails that can't be used by Swiftmailer, because a check is done based on this RFC (view http://www.bala-krishna.com/how-to-fix-swift-mailer-error-address-in-mailbox-given-does-not-comply-with-rfc/).

What do you think about adding a property as for the current "strict" option to check with the same method that done by Swiftmailer?

To avoid this issue, I just created a new EmailRFC validator which is based on a specific class of Swiftmailer. But I think it would be better to integrate it to the base validator of Symfony.
Maybe the Swift_Mime_Grammar() must be extract from Swiftmailer to be used independently?

```php
class MailRFCValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        $patternProvider = new \Swift_Mime_Grammar();

        if (!is_null($value) && !empty($value) && !preg_match('/^'.$patternProvider->getDefinition('addr-spec').'$/D', $value)) {
            $this->context->addViolation($constraint->message);
        }
    }
}
```

What is your opinion on the topic?

**Comment by xabbuh** [comment]
You can use a development version of Swiftmailer to prevent being affected from this or wait for a new Swiftmailer release (#17802, swiftmailer/swiftmailer#403, swiftmailer/swiftmailer#409, egulias/EmailValidator#42).

**Comment by raziel057** [comment]
@xabbuh Thanks for your reply

**Comment by HKandulla** [comment]
Hi @xabbuh, what is the best way to use the development version of SwiftMailer in Symfony. Even the [dev-master](https://packagist.org/packages/symfony/swiftmailer-bundle#dev-master) of the swiftmailer-bundle references swiftmailer/swiftmailer: >=4.2.0,~5.0?

**Comment by jakzal** [comment]
@HKandulla put custom swiftmailer/swiftmailer requirements in your composer.json

**Comment by HKandulla** [comment]
@jakzal but the [swiftmailer-bundle](https://github.com/symfony/swiftmailer-bundle/blob/master/composer.json) references "swiftmailer/swiftmailer": ">=4.2.0,~5.0", so it will work with the 6.0-dev Version of SwiftMailer?

**Comment by jakzal** [comment]
@HKandulla you can use [an alias to trick composer](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to think it's using a different version. I'm not sure how compatible the bundle is with the library though. You're doing it on your own responsibility ;)

**Comment by HKandulla** [comment]
@jakzal thanks! I give it a try.
