### ISSUE TITLE
HttpFoundation Request getURI alphabetized 

### ISSUE THREAD

**Issue by matzegebbe** [symfony/symfony#19358]
the ```getURI``` function uses the ```getQueryString``` which calls ```normalizeQueryString```

It builds a normalized query string, where keys/value pairs are alphabetized and have consistent escaping.

I use all parameters to hash them in order they appear. I do not use the build-in UriSigner. Should it be possible to disable ```array_multisort($order, SORT_ASC, $parts);``` by switch? I know there is the ```getRequestUri``` function but in some situations you maybe want a normalized query string without alphabetical order

https://github.com/symfony/symfony/blob/0fc2b622e8795a33b01c0a0b5075abd6e2406839/src/Symfony/Component/HttpFoundation/Request.php#L672

**Comment by fabpot** [comment]
The normalization process must include the reordering as we want to be sure that for any key/value pairs, we always end up with the same query string. I think your best bet is to copy/paste the code of the method and adapt it to your needs.

**Comment by Vovchikus** [comment]
> The normalization process must include the reordering as we want to be sure that for any key/value pairs, we always end up with the same query string. I think your best bet is to copy/paste the code of the method and adapt it to your needs.

In this case it is not a good name for this method, I expect from method getQueryString exact same behaviour as $_SERVER['QUERY_STRING'], but it is not. May be more explicit name for such method should be getNormalizedQueryString
