### ISSUE TITLE
Workflow component needs cancellation/reset groups

### ISSUE THREAD

**Issue by Nyorai** [symfony/symfony#19357]
When using the workflow component for a parallel approvement workflow where if any of the transitions result in a rejection, there is no way to reset the marking on the other places and the workflow can end up in an undesired state.

For example: If I need approval by both A & B to publish, A could reject but the workflow would still be waiting for B to approve. A rejection by A needs to cancel the waiting for approval of B, and vice versa.

**Comment by fabpot** [comment]
ping @lyrixx

**Comment by lyrixx** [comment]
Hello  @Nyorai 

In this case, you need to declare explicitly some transitions to be able to "return / reset" to the initial state (or a previous one).

**Comment by Nyorai** [comment]
Thanks for that @lyrixx. Creating an enter event that resets the marking does the trick.
