### ISSUE TITLE
[Translation][Question] Dashes vs. underscore

### ISSUE THREAD

**Issue by leberknecht** [symfony/symfony#19353]
Ahoi!

I'm using crowdin for managing translations, and per default, crowdin uses locales like "en-UK". As the symfony translation component seems to expect underscores instead of dashes, i'm now using generic "en" locale on crowdin as a workaround. But i'm wondering: Some stackoverflow page was saying that dashes should be used, refering to https://tools.ietf.org/html/rfc5646 . The docs only say that language-codes according to ISO 639-1 and ISO_3166-1 are used ... so, before starting a feature request a la "Please support dashes in locales" and get flamed for asking something stupid....would it be stupid to request dashes in locales? :D

**Comment by sstok** [comment]
I did some quick searching but it seems most locales in a filename are with underscores, so Crowdin should update there platform to allow this instead.

**Comment by leberknecht** [comment]
Hm, i was more asking "would it make sense to request for dash-support, or is there a special reason why it should be underscore and only underscore"? The arugment "quick search says its more common to use underscores" doesnt say much in my opinion. So if we introduce something like an option to define the separator-character, maybe everyone would be happy. :)

**Comment by jakzal** [comment]
I don't think it's worth it. It would potentially complicate code (haven't looked into it, perhaps someone could prove me wrong with a simple and elegant PR). I vote for a single way of doing things to avoid confusion.

**Comment by javiereguiluz** [comment]
I agree with @jakzal. The proposed change looks simple (just replace an underscore by a dash) but it could have enormous (and unexpected) consequences in our code. Let's keep it unchanged.

@leberknecht it looks like this time your proposal was not accepted ... but please, keep proposing features and improvements for Symfony. Thank you!

**Comment by ptrm04** [comment]
@leberknecht - old thread I've stumbled upon (and yes, I might be a Necromancer) - you can still use hyphens for the sub-tags as per RFC5646 - just use an early Listener and flip the dashes to underscores, here's a gist: https://gist.github.com/ptrm04/b1ecaca960296479844fd3fc49e51cf2

**Comment by leberknecht** [comment]
Hu! Nice idea! Thank you!
