### ISSUE TITLE
Expression Language grammar

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#19364]
Would be nice to have a specification of the expression language. Possibly as BNF.

**Comment by nicolas-grekas** [comment]
Since 3.1, you can dump the AST to whatever format. I know that's not your request, but still wanted to point at it :)
About your issue, it's not going to happen unless someone interested in having in (and help maintaining that grammar) submits a PR.

**Comment by jakzal** [comment]
@flip111 nice to haves are nice to have. What would be the use case? Are you willing to work on the PR? Otherwise let's close.

**Comment by flip111** [comment]
Yes well, i'm not going to debate the merits of a language specification. Wikipedia has [some information](https://en.wikipedia.org/wiki/Programming_language_specification) on it. Writing up a BNF for such a small DSL shouldn't be a problem. What's much harder is to keep the spec in line with the implementation and the other way around. But what i do want to mention is that when a grammar is available it will be really easy to port it and another benefit is that when using a parser generator you don't need to do the implementation anymore. I might be willing to work on a PR if i know what you have in mind for it.

**Comment by xabbuh** [comment]
It doesn't seem that there is much interest in having this. I suggest to close here.
