### ISSUE TITLE
[PHPSTORM 12.x | PLUGIN] Unable to create projects, SSL error.

### ISSUE THREAD

**Issue by QuantumRevenger** [symfony/symfony#19360]
I've been unable to create a new project for weeks now using Symfony in PHP Storm via the plugin, every time it just throws out with an SSL error saying the certificate isn't valid.

This is affecting two seperate locations, and doesn't seem to be resolvable, even updating the plugin has made no improvement to the issue.

Version: 3.1.2

Error Output:
"cURL error 60: SSL certificate problem: unable to get local issuer certific ate [GuzzleHttp\Ring\Exception\RingException] cURL error 60: SSL certificate problem: unable to get local issuer certific ate new   [ ]"

Can someone please look into this?

**Comment by javiereguiluz** [comment]
Two quick questions:

* I never create Symfony projects with PHPStorm. I create them directly with the Symfony Installer. Do you know if PHPStorm uses the Symfony installer internally?
* Do you happen to use Windows? (We have some SSL related issues in Windows when using the Symfony Installer)

**Comment by QuantumRevenger** [comment]
PHPStorm uses the Symfony installer internally? I believe so, it creates a composer / phar file within a folder called Symfony and then executes these files (ending in error).

Do you happen to use Windows? I do, I am on Windows 10 x64 Pro edition. Both machines at my home / office run the same OS. The Symfony framework used to install without any issues and then one morning it stopped working and never came back.

Do you have any workarounds, or a solution coming soon?

**Comment by javiereguiluz** [comment]
@QuantumRevenger thanks for the info. It's definitely a Symfony Installer + Windows OS error. I'm closing this issue in favor of https://github.com/symfony/symfony-installer/issues/268 where we can discuss about this and fix it. Thank you.

**Comment by sstok** [comment]
Check if your antivirus has SSL scanning enabled, disable this and check again.

**Comment by QuantumRevenger** [comment]
@sstok I have disabled my anti-virus (Webroot: Complete Internet Security) and tried to install again and the same error occurs during installation. I believe that Webroot does do "SSL/HTTPS Scanning" but I disabled all shields under the configuration panel.

**Comment by AmaliDeveloper** [comment]
Hey you can get the solution in this tutorial Good Work [Link](https://youtu.be/gh1T8wS2alM)
