### ISSUE TITLE
miss symfony / http-foundation during themosis Installation

### ISSUE THREAD

**Issue by Bulldog-hub** [symfony/symfony#19376]
I'm just want to install themosis to start new project and i have some problem during installation.
<pre>
composer create-project themosis/themosis myProject
</pre>
and the installation fails because obviously missing a package symfony.

<pre>
Installing themosis/themosis (1.2.3)
  - Installing themosis/themosis (1.2.3)
    Loading from cache

Created project in myProject
Loading composer repositories with package information
Warning: Accessing wpackagist.org over http which is an insecure protocol.
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - themosis/framework 1.2.3 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.2 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.1 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.0 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - Installation request for themosis/framework 1.2.* -> satisfiable by themosis/framework[1.2.0, 1.2.1, 1.2.2, 1.2.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see  for more details.

Read  for further common problems.
</pre>

Do you have a fresh bug of missing stable tags on symfony/http-foundation.

**Comment by Tobion** [comment]
Seems like all tags are missing on packagist: https://packagist.org/packages/symfony/http-foundation but they exist in git https://github.com/symfony/http-foundation/tags

Might be related to #19375

**Comment by iltar** [comment]
It seems fixed again. I've send out a tweet/issue in `#composer` last evening about this. https://packagist.org/packages/symfony/dependency-injection was also having this issue but it's showing again.

**Comment by javiereguiluz** [comment]
Closing it because the related Packagist.org issue seems to have been fixed. @Bulldog-hub thanks for reporting this!
