### ISSUE TITLE
[Form] Validation done on entities removed at FormEvents::SUBMIT

### ISSUE THREAD

**Issue by MichaelMure** [symfony/symfony#19378]
I have a form where I pre-populate a collection to have a series of inputs. After submitting, I want to trim this collection based on the data submitted. With Symfony 2.5, I had an event listener on FormEvents::SUBMIT, where I could trim the ArrayCollection binded to the form's collection.

When migrating to Symfony 3, this stopped working properly. The problem is that even if the entities are correctly removed and the validation is correctly done after this removal, removed entites are still validated and the form submit fail.

Here is a minimal example of what I do:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $myformentity = $options['data'];

    $builder
        ->add('mycollection', CollectionType::class)
        ->add('mycheckbox',CheckboxType::class, array(
            'required'=> false,
            'mapped'  => false,
        ));

    $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) use($myformentity) {
        $form = $event->getForm();

        if($form->get('mycheckbox')->getData()){
            // Remove some entities in $myformentity->mycollection
        }
    });
}
```

Is this a regression ? Is there another way to do that ?

**Comment by HeahDude** [comment]
Hi @MichaelMure. What do you mean by `removed entites are still validated`?
Could you share the logic of your listener or add a minimum of code in a fork of symfony-standard to reproduce your issue? Thanks!

**Comment by MichaelMure** [comment]
@HeahDude Let say $myformentity->mycollection is pre-filled with 10 entities (entity0 to entity9). In the FormEvents::SUBMIT listener, I choose to remove entity5 to entity9 based on another field value in the form. I do this by removing doctrine entities in the $myformentity->mycollection ArrayCollection.

What happen is that the entities validation (for instance Constraint\GreaterThanOrEqual) is triggered for all the entities present originaly in the collection, including entity5 to entity9. The form content is thus considered not valid and is displayed again with validation error.

It works as if now the form hierarchy is walked to trigger the entities validation, instead of doctrine's object graph previously.

I'm doing this because I have a page where I need a different number of inputs depending on a date provided by the user in the same form. A few lines of javascript hide the wrong inputs, so the user cannot see or edit them, based on the date provided.

I'll have a look at creating a fork of symfony-standard.

**Comment by MichaelMure** [comment]
I build a minimal example project from Symfony Standard and it turns out that it is working as expected.

The origin of my problem was the use of `'mapped' => false`  field in some subform, maybe in conjunction with `'constraints' => array(new Valid())`.

So I don't think it's a bug, just a bad code in my side. Sorry for the noise !
