### ISSUE TITLE
Add DoctrineValueResolver 

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#19372]
The function `$this->getUser()` of the Controller class has been moved to Dependency Injection. Why shouldn't this also be done for the `$this->getDoctrine()` function?

http://symfony.com/blog/new-in-symfony-3-2-user-value-resolver-for-controllers

**Comment by iltar** [comment]
The difference with the security user and doctrine, is that doctrine (in this case) is a service where the user is stateful. If you want to inject stateless objects (services), you should do so in the constructor imo.

**Comment by fabpot** [comment]
@iltar is right.
