### ISSUE TITLE
Email aaa@@@@bbb.com is valid

### ISSUE THREAD

**Issue by miroslavhajek** [symfony/symfony#19385]
```php
        $builder = new ValidatorBuilder();
        $validator = $builder->getValidator();

        $inputData = [
            'email' => 'aaa@@@@bbb.com',
        ];

        $val = new Collection([
            'email' => [
                new Email(),
            ],
        ]);
```

Is valid.... Problem is in `Symfony\Component\Validator\Constraints\EmailValidator::validate` on line 81. Expected message is _Array[email]: This value is not a valid email address. (code bd79c0ab-ddba-46cc-a703-a7a4b08de310)_.

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. In the past we've tried several times to improve the email validator. This is the latest attempt: https://github.com/symfony/symfony/issues/18177  But for different reasons, we never implement those changes.

**Comment by xabbuh** [comment]
Are you sure that this address is valid? Even the `egulias/email-validator` library seems to consider it invalid.

**Comment by fabpot** [comment]
Indeed, this is not a valid email address.

**Comment by stof** [comment]
Note that if you don't run the email validation in strict mode, this will indeed not be detected as invalid, but this is expected. When not using the strict validation, lots of invalid emails will go undetected (this is why we use a dedicated library in strict mode)
