### ISSUE TITLE
WebTestCase does not populate $_SERVER['QUERY_STRING']

### ISSUE THREAD

**Issue by solazs** [symfony/symfony#19380]
I'm trying to write integration tests using phpUnit. 

Running the following code 

```php
class DefaultControllerTest extends WebTestCase
{
 public function testFilter()
    {
        $client = static::createClient();

/* Also tried this, but no joy
$client = static::createClient([],['QUERY_STRING' => 'filter=parent.name,eq,testusername']);*/

        $client->request('GET',
            '/users',
            ['filter' => 'parent.name,eq,testusername']
        );

/* No succes this way either
$client->request('GET',
            '/users?filter'=parent.name,eq,testusername'
        );

Nor with
$client->request('GET',
            '/users',
            ['filter' => 'parent.name,eq,testusername'],
            [],
            ['QUERY_STRING' => 'filter=parent.name,eq,testusername']
        );*/

        $response = $client->getResponse();
        echo "Got response: " . $response;

//...
}

```

Upon debugging, I've discovered, that the`QUERY_STRING` key does not exist in $_SERVER.

I think this is a bug, but correct me if I'm missing something.

Versions:
PHPUnit 5.4.6
PHP 7.0.8 (cli) (built: Jun 22 2016 16:45:35) ( NTS )
Zend Engine v3.0.0
    with Zend OPcache v7.0.8
    with Xdebug v2.4.0
Running on Arch linux

Composer package versions:
doctrine/annotations                 v1.2.7             Docblock Annotations Parser
doctrine/cache                       v1.6.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.3.0             Collections Abstraction library
doctrine/common                      v2.6.1             Common Library for Doctrine projects
doctrine/dbal                        v2.5.4             Database Abstraction Layer
doctrine/doctrine-bundle             1.6.3              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0              Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         v2.5.4             Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.2             Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
jms/metadata                         1.5.1              Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0              A library for easily creating recursive-descent parsers.
jms/serializer                       1.1.0              Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                1.1.0              Allows you to easily serialize, and deserialize data of any complexity
monolog/monolog                      1.20.0             Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat              v2.0.2             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpcollection/phpcollection          0.4.0              General-Purpose Collection Library for PHP
phpoption/phpoption                  1.5.0              Option Type for PHP
psr/log                              1.0.0              Common interface for logging libraries
sensio/distribution-bundle           v5.0.7             Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.16            This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.0.7             This bundle generates code for you
sensiolabs/security-checker          v3.0.2             A security checker for your composer.lock
solazs/qurep                         dev-master 61bb8ba 
swiftmailer/swiftmailer              v5.4.3             Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               2.11.1             Symfony MonologBundle
symfony/phpunit-bridge               v2.8.8             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            v1.2.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.2.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.2.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.2.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.2.0             Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.3.11            Symfony SwiftmailerBundle
symfony/symfony                      v3.0.8             The Symfony PHP framework
twig/twig                            v1.24.1            Twig, the flexible, fast, and secure template language for PHP

**Comment by stof** [comment]
This is totally expected. It populates the Request object, but it does not overwrite superglobals.

You should access this info from the Request object, not from ``$_SERVER``

**Comment by solazs** [comment]
Query parameters are accessed from the Request object whenever possible, but PHP does not support having two GET parameters with the same name, which is why the QUERY_STRING is needed. It does get populated when calling a web server, shouldn't the test environment reproduce the exact parameters or at least provide a mode to test them?

**Comment by stof** [comment]
use ``$request->server`` to access this, not ``$_SERVER``. The client will not overwrite the superglobals.

In a Symfony project, you should never need to access superglobals. The Request object encapsulates all info they contains (except for ``$_SESSION`` which is in the Session object). The big advantage of the Request object is that it is *not* global, and so makes the code much more testable (no global state to worry about)

**Comment by solazs** [comment]
Using $request->server works, I did not notice it in the docs. 
Thanks for the help and for the quick reply!
