### ISSUE TITLE
Twig asset() helper ignores router.request_context.base_url parameter

### ISSUE THREAD

**Issue by MrMitch** [symfony/symfony#19396]
Hi !

When the `asset` helper is used in a twig template to generate urls, it does not take into account the `router.request_context.base_url` parameter set in `config.yml` (or `config_*.yml`).

I've created a **[sample project](https://github.com/MrMitch/symfony-assets-base-url)** (based on [symfony/symfony-standard](https://github.com/symfony/symfony-standard)) to illustrate this.

The project defines a [default base-url](http://symfony.com/doc/current/cookbook/console/request_context.html) for all requests in [config.yml](https://github.com/MrMitch/symfony-assets-base-url/blob/assets-base-url/app/config/config.yml#L10).
Inside the project, i added a [demonstration command](https://github.com/MrMitch/symfony-assets-base-url/blob/assets-base-url/src/AppBundle/Command/GenerateAssetsListCommand.php) `mitch:generate-assets-list` that ouputs 3 lists of urls.
1. a list generated with `asset`
2. a list generated using `url`
3. a list generated using `path`

The urls of list 2 & 3 all have the base-url part inside, the urls in list 1 do not.

[The template](https://github.com/MrMitch/symfony-assets-base-url/blob/assets-base-url/src/AppBundle/Resources/views/template.twig) looks like : 

``` twig
## assets urls

- {{ asset('bundles/app/img/logo.png') }}
- {{ asset('bundles/framework/images/logo_symfony.png') }}

## controller urls

- {{ url('homepage') }}
- {{ url('dummy_route') }}

## controller paths

- {{ path('homepage') }}
- {{ path('dummy_route') }}
```

The ouput generated by `php bin/console mitch:generate-assets-list` looks like :

``` md
## assets urls

- /bundles/app/img/logo.png
- /bundles/framework/images/logo_symfony.png

## controller urls

- http://localhost/subfolder/
- http://localhost/subfolder/dummy

## controller paths

- /subfolder/
- /subfolder/dummy
```

Thank you for your time,
Mitch.

**Comment by MrMitch** [comment]
The relevant commit is https://github.com/MrMitch/symfony-assets-base-url/commit/f4de6cae206059794859eec1a6e802657fa5632a

**Comment by xabbuh** [comment]
What happens if you wrap the `asset()` call in [absolute_url()](http://symfony.com/doc/current/book/templating.html#linking-to-assets)?

**Comment by MrMitch** [comment]
This produces a full URL (including scheme and host), which is not really the desired effect. Moreover, the base-url is still missing.

The new list : 
```twig
## assets urls with `absolute_url`

- {{ absolute_url(asset('bundles/framework/images/logo_symfony.png')) }}
- {{ absolute_url(asset('bundles/framework/images/logo_symfony.png')) }}
```

produces : 
```md
## assets urls with `absolute_url`

- http://localhost/bundles/framework/images/logo_symfony.png
- http://localhost/bundles/framework/images/logo_symfony.png
```

commit : https://github.com/MrMitch/symfony-assets-base-url/commit/f8b5ee8ec147ad032b0db49fd17058a1ca911ab9

**Comment by javiereguiluz** [comment]
@MrMitch is the `asset()` used in a template rendered via web or via a console command? The `router.request_context.*` parameters are ignored by the web and used by the CLI.

**Comment by MrMitch** [comment]
Hi @javiereguiluz, as mentionned in the issue description, the template is rendered via a [console command](https://github.com/MrMitch/symfony-assets-base-url/blob/assets-base-url/src/AppBundle/Command/GenerateAssetsListCommand.php).

**Comment by stof** [comment]
This is because the ``Asset`` component has nothing to do with the router, and so it ignores settings configuring the routing RequestContext.

What we are missing is a way to configure the default base path in the Asset component, when we don't have a Request in the RequestStack and we use the request-based context

**Comment by 1ed** [comment]
Why don't you set the assets base URL like this?

```yaml
framework:
    assets:
        base_urls:
            - '%router.request_context.scheme%://%router.request_context.host%'
```

**Comment by MrMitch** [comment]
Hi @stof, thanks for the clarification. Do you recommend something I can fix in my code or does the `Asset` component have to be updated to include a way to configure the base path when we use the request-based context and we don't have a Request in the RequestStack ?

**Comment by MrMitch** [comment]
ping @stof @javiereguiluz : do you have any suggestion as to how I can fix this in my code or if it has to be fixed in the `Asset` component ?

**Comment by ro0NL** [comment]
Had a quick look today and im not sure whats the best way to solve it. Currently there's a `RequestStackContext`, bridging the HttpFoundation component. There's no `RequestContextContext` bridging the Routing component. Havent looked at implementation level yet..

However implementing a `RequestContextContext` is tricky because i have no idea how to go from baseurl to basepath in a generic way.

But if i understand @stof correctly he wants to fix it at `Package::setBasePath` level, basicly providing a default value if not provided by the context.

Im not sure what's the best way to go..  maybe a simple VO (`Context`) will do and constructing it from a request stack or request context where needed...

**Comment by MrMitch** [comment]
Thank you for your further investigation. Is is still considered `unconfirmed` ?

**Comment by ro0NL** [comment]
Personally i think the context interface in the asset component is slightly over-engineered.. i would favor a simple VO and construct that where needed. Havent really investigated where this should happen exactly..

**Comment by MrMitch** [comment]
Hi everyone, do you have any news regarding this issue ? 
Do you still consider it unconfirmed ?
Do you have any idea as to how it could be solved ?

**Comment by jakzal** [comment]
I removed the "Unconfirmed" label. Stof has indicated what's the real problem here:

> This is because the Asset component has nothing to do with the router, and so it ignores settings configuring the routing RequestContext.

> What we are missing is a way to configure the default base path in the Asset component, when we don't have a Request in the RequestStack and we use the request-based context

**Comment by MrMitch** [comment]
@jakzal thank you
@stof let me know if there's anything I can do to help

**Comment by javiereguiluz** [comment]
@MrMitch have you tried adding the following config?

```yaml
# app/config/config.yml
framework:
    assets:
        base_path: /subfolder
```

**Comment by ro0NL** [comment]
@MrMitch does #21027 works out?

**Comment by ro0NL** [comment]
I updated the PR with a simpler approach (same like routing componet works) by introducing;

```yaml
# parameters.yml
asset.context.base_path: '/base/path'
asset.context.secure: false
```

@javiereguiluz setting `assets.base_path` will fix CLI, but duplicates the base path in web (as the request context works properly then). So it doesnt workout.

We need a default _context_ on CLI, hence #21027. I hearby confirm this as an issue / incomplete behavior.

**Comment by javiereguiluz** [comment]
@ro0NL I haven't look into the details ... but I don't understand why do we need two different config options for the same thing. Using `assets.base_path` only should work everywhere (CLI, web, etc.)

**Comment by ro0NL** [comment]
This is not how the Asset component works. It defines contexts + packages. Both can have a base path.

The context base path depends on environment (mine is `/sf`, yours is `/something-else`). In web this path is guessed/provided by `Request::getBasePath`. The package "base path" is relative to it..

See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Asset/PathPackage.php#L69.. it should make things clear.

**Comment by ro0NL** [comment]
And yes, there's no way to overrule the context base path by design. I guess should go with URL packages in that case (even if using the same host).

**Comment by javiereguiluz** [comment]
@ro0NL (again, without having looked into details) couldn't the `asset()` function take the value of `assets.base_path` config when there is no request (in the CLI) ?

**Comment by ro0NL** [comment]
Suppose you would do `assets.base_path: '%base_path%/assets' (a parameter, because mine differs from yours).

Given `asset('foo.jpg')`i get `/sf/assets/foo.jpg` in CLI :+1:

But i get `/sf/sf/assets/foo.jpg` in web :-1:

Meaning if we ignore `asset.base_path` in web we'd get `/sf/foo.jpg`, which is still wrong.

**Comment by ThomasLandauer** [comment]
The configuration setting is now called just `base_path`: https://symfony.com/doc/current/reference/configuration/framework.html#base-path
