### ISSUE TITLE
Can't generate a working crud for an entity named Url

### ISSUE THREAD

**Issue by electrolinux** [symfony/symfony#19394]
How to reproduce:

    symfony new foo 2.8
    cd foo
    vim app/config/parameters.yml app/config/config.yml # config pdo...
    app/console doctrine:generate:entity --entity=AppBundle:Url \
        --format=annotation --fields="name:string(128) href:string(255)"  \
        --no-interaction
    app/console doctrine:generate:entities AppBundle:Url
    app/console doctrine:generate:crud --with-write AppBundle:Url
    app/console doctrine:schema:create
    app/console server:run

So far so good, but going to /url/new throw an exception:

Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class AppBundle\Entity\Url could not be converted to string") in form_div_layout.html.twig at line 13.

_Everything works fine if the entity is named something else, of course._

**Comment by javiereguiluz** [comment]
@electrolinux thanks for reporting this issue. You did it perfectly and the steps to reproduce it are very clear! However, the fix to this error must be done on the SensioGeneratorBundle, which is the tool that generates the CRUD for entities.

Sadly I can't move this issue to the corresponding repository: https://github.com/sensiolabs/SensioGeneratorBundle/issues  So, could you please create a new issue in that repository and copy+paste these contents? Thanks!

**Comment by electrolinux** [comment]
@javiereguiluz that's what I was thinking initially, but after further investigation, it really seems to me that it has nothing to do with the generator, which always produce the same output excepted for the classes names. 
Furthermore, dumping the formView in each template seems to show almost the same structure, again excepted for the names.
So it really seems related to either Twig or the TwigBundle, as for the Url FormView, the form_widget() generate a supplemental edit field for the entity itself, which cause the exception when the entity has no __toString() method (which is the default for generated entities)

I suppose I need to change the title of this issue to something as **[TwigBundle] form_widget() generate a supplemental field when the formView contains an Entity named Url**, unless you have a better suggestion?

### Url formView (crashing):
````php
FormView {#500 ▼
  +vars: array:27 [▼
    "value" => Url {#446 ▼
      -id: null
      -href: null
    }
    "attr" => []
    "form" => FormView {#500}
    "id" => "url"
    "name" => "url"
    "full_name" => "url"
    "disabled" => false
    "label" => null
    "label_format" => null
    "multipart" => false
    "block_prefixes" => array:3 [▶]
    "unique_block_prefix" => "_url"
    "translation_domain" => null
    "cache_key" => "_url_AppBundle\Form\UrlType"
    "read_only" => false
    "errors" => FormErrorIterator {#569 ▶}
    "valid" => true
    "data" => Url {#446 ▶}
    "required" => true
    "max_length" => null
    "pattern" => null
    "size" => null
    "label_attr" => []
    "compound" => true
    "method" => "POST"
    "action" => ""
    "submitted" => false
  ]
  +parent: null
  +children: array:2 [▼
    "href" => FormView {#579 ▶}
    "_token" => FormView {#586 ▶}
  ]
  -rendered: false
}
````
### Web formView (working Ok):
````php
FormView {#326 ▼
  +vars: array:27 [▼
    "value" => Web {#272 ▼
      -id: null
      -href: null
    }
    "attr" => []
    "form" => FormView {#326}
    "id" => "web"
    "name" => "web"
    "full_name" => "web"
    "disabled" => false
    "label" => null
    "label_format" => null
    "multipart" => false
    "block_prefixes" => array:3 [▶]
    "unique_block_prefix" => "_web"
    "translation_domain" => null
    "cache_key" => "_web_AppBundle\Form\WebType"
    "read_only" => false
    "errors" => FormErrorIterator {#395 ▶}
    "valid" => true
    "data" => Web {#272 ▶}
    "required" => true
    "max_length" => null
    "pattern" => null
    "size" => null
    "label_attr" => []
    "compound" => true
    "method" => "POST"
    "action" => ""
    "submitted" => false
  ]
  +parent: null
  +children: array:2 [▼
    "href" => FormView {#405 ▶}
    "_token" => FormView {#412 ▶}
  ]
  -rendered: false
}
````

### The form type:
````bash
diff src/AppBundle/Form/WebType.php src/AppBundle/Form/UrlType.php 
9c9
< class WebType extends AbstractType
---
> class UrlType extends AbstractType
28c28
<             'data_class' => 'AppBundle\Entity\Web'
---
>             'data_class' => 'AppBundle\Entity\Url'
```

### The views:
````bash
diff app/Resources/views/web/new.html.twig app/Resources/views/url/new.html.twig
4c4
<     <h1>Web creation</h1>
---
>     <h1>Url creation</h1>
13c13
<             <a href="{{ path('web_index') }}">Back to the list</a>
---
>             <a href="{{ path('url_index') }}">Back to the list</a>
````
### The entities:
````bash
diff src/AppBundle/Entity/Web.php src/AppBundle/Entity/Url.php
8c8
<  * Web
---
>  * Url
10,11c10,11
<  * @ORM\Table(name="web")
<  * @ORM\Entity(repositoryClass="AppBundle\Repository\WebRepository")
---
>  * @ORM\Table(name="url")
>  * @ORM\Entity(repositoryClass="AppBundle\Repository\UrlRepository")
13c13
< class Web
---
> class Url
47c47
<      * @return Web
---
>      * @return Url

````

### The controllers:
````bash
diff src/AppBundle/Controller/WebController.php src/AppBundle/Controller/UrlController.php
9,10c9,10
< use AppBundle\Entity\Web;
< use AppBundle\Form\WebType;
---
> use AppBundle\Entity\Url;
> use AppBundle\Form\UrlType;
13c13
<  * Web controller.
---
>  * Url controller.
15c15
<  * @Route("/web")
---
>  * @Route("/url")
17c17
< class WebController extends Controller
---
> class UrlController extends Controller

# (... edited for brevity)

37c37
<      * Creates a new Web entity.
---
>      * Creates a new Url entity.
39c39
<      * @Route("/new", name="web_new")
---
>      * @Route("/new", name="url_new")
44,45c44,45
<         $web = new Web();
<         $form = $this->createForm('AppBundle\Form\WebType', $web);
---
>         $url = new Url();
>         $form = $this->createForm('AppBundle\Form\UrlType', $url);
50c50
<             $em->persist($web);
---
>             $em->persist($url);
53c53
<             return $this->redirectToRoute('web_show', array('id' => $web->getId()));
---
>             return $this->redirectToRoute('url_show', array('id' => $url->getId()));
56,57c56,57
<         return $this->render('web/new.html.twig', array(
<             'web' => $web,
---
>         return $this->render('url/new.html.twig', array(
>             'url' => $url,

````

**Comment by electrolinux** [comment]
In fact, it's really a crud generator limit, and I will open an issue there, maybe. One must override the getBlockPrefix for any form type which is named as a built-in type (like Url)
