### ISSUE TITLE
log and WebDebugToolbar show only one event for kernel.request

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#19393]
In symfony 3.1.2 `Symfony\Component\EventDispatcher\Debug\WrappedListener` hides the real events.

The debug toolbar lists only one event for kernel.request, the `...\WrappedListener`.

In the logs, there are several DEBUG entries for the event kernel.request, but each for the '...\WrappedListener`.

### How to reproduce: ###
 * Take any project running with symfony 3.1.2 (or probably any version since march). Make a request in dev mode.
 * Open the profiler on events panel (`.../app_dev.php/_profiler/c87980?panel=events`). There is only one entry in `kernel.request`, the one for WrappedListener.
 * check the Debug entries in the log panel of the profiler (`_profiler/c87980?panel=logger`). Only the WrappedListener is listed for event kernel.request. In case debug logging is enabled, you may also check the log on the filesystem (`./var/logs/dev.log`).

**Comment by jakzal** [comment]
@SimonHeimberg I just tried to reproduce this issue but everything seems to be working just fine.

I Installed Symfony with `symfony new issue19393` and the debug toolbar shows all the events properly in both events and logs tabs.

![image](https://cloud.githubusercontent.com/assets/190447/17095358/f94524da-524b-11e6-8030-339966712fef.png)

![image](https://cloud.githubusercontent.com/assets/190447/17095336/e07b5c76-524b-11e6-8aec-8871dea83684.png)

![image](https://cloud.githubusercontent.com/assets/190447/17095328/d2ef6eda-524b-11e6-97d0-2cd906dce9b9.png)

**Comment by SimonHeimberg** [comment]
@jakzal your images show that this is not a general problem, but only on my installation. I retried today and I'm almost sure the problem showed up on the first try. But when I wanted to dig into it, the problem was gone. Now debug toolbar shows everything as in your images.

Therefore I confirm this bug as closed. And I can not add any details when it could occur.
