### ISSUE TITLE
[ProxyManagerBridge][Bug] Used feature from PHP 7 in fixtures

### ISSUE THREAD

**Issue by zomberg** [symfony/symfony#19407]
Used return type declaration which from PHP 7 in fixtures:

/src/Symfony/Bridge/ProxyManager/Tests/LazyProxy/Fixtures/php/lazy_service_with_hints.php
```php
    /**
     * {@inheritdoc}
     */
    public function initializeProxy() : bool
    .......

    /**
     * {@inheritdoc}
     */
    public function isProxyInitialized() : bool
    ....
```

Can it be a problem or it is just fixture?

**Comment by Tobion** [comment]
Its a test for proxy manager 2 which requires php 7: https://github.com/Ocramius/ProxyManager/blob/2.0.x/composer.json#L22
