### ISSUE TITLE
Symfony3 route 404 with Nginx server

### ISSUE THREAD

**Issue by DarthPestilane** [symfony/symfony#19414]
I followed the book of documentation to create my first page : http://symfony.com/doc/current/book/page_creation.html.

And I configured an Nginx web server for symfony according to : 
http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#web-server-nginx

But all pages turned out to be an 404 error except the homepage.
Please help.

**Comment by Tobion** [comment]
# #
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
