### ISSUE TITLE
[Form][Intl] Money type is always in prepend mode

### ISSUE THREAD

**Issue by Th3Mouk** [symfony/symfony#19424]
Hello everyone.

I've found something that I don't understand in form, intl components, and bootstrap3 bridge.

I try to render a money field on a Bootstrap3 design, but with the currency symbol after the input.
In UK an amont is render like that `£10` but in France `10€`.

First of all, in bootstrap bridge, I think there is a mistake, and before making a PR, I prefer to check with you.
As you can see [here](https://github.com/symfony/symfony/blob/1298ce51cb08b6cf780784056e723fd542db84cc/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L25), when the value prepend is false, the render is prepended.
IMO the test should be
```twig
{% if prepend %}
```

But it doesn't resolve all cases, because doing this, the currency symbol can be anymore prepended.

As you can see [here](https://github.com/symfony/symfony/blob/8356d15dfa2a7bc13ac500079c6e3223f8682e88/src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php#L352), the function that format currency into string, doesn't take argument to prepend or not the symbol.

Something like that can ba add.
```php
if ($prepend) {
  $ret = $symbol.$value;
} else {
  $ret = $value.$symbol;
}
```

So finally,  the symbol is always prepend in the pattern in the `MoneyType` [code here](https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php#L92), because the `preg_match` always return the same result.

Thanks for your help

**Comment by stof** [comment]
@Th3Mouk are you sure it always return the same result for all locales ?

**Comment by Th3Mouk** [comment]
@stof as I see [here](https://github.com/symfony/symfony/blob/8356d15dfa2a7bc13ac500079c6e3223f8682e88/src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php#L352) yes. But I haven't check manually.

**Comment by ogizanagi** [comment]
I'd say it's the `Symfony\Component\Intl\NumberFormatter\NumberFormatter::formatCurrency()` which is wrong, because the php native implementation will properly return the proper result with different locales. 

However, as you mentioned, the bootstrap form theme seems wrong.

**Comment by Th3Mouk** [comment]
@ogizanagi thanks for the help.

I don't want to tweak this form type on a decade of projects, only the position of the currency is wrong with the bootstrap bridge, not a blocking bug. I simply use the `MoneyType` of Symfony, that use `formatCurrency()` method. 
After tweaking the bridge, I looked a little further into the components.

**Comment by ogizanagi** [comment]
@Th3Mouk : AFAIU, there is nothing to do on the component side. The `Intl`component is a replacement layer for the native php intl extension. And the docs state:

> The replacement layer is limited to the locale "en". If you want to use other locales, you should install the intl extension instead.
— http://symfony.com/doc/current/components/intl.html

So if you have the `intl` extension, you shouldn't suffer from the issue mentioned below.

**Comment by Th3Mouk** [comment]
I got the `intl` extension activated, but the € symbol is prepend.

So all `intl` extension users must create their own `MoneyType` ?

**Comment by ogizanagi** [comment]
I think there is a confusion: the currency being prepended or appended only depends of the configured locale, not the currency:

```php
>>> $nf = new \NumberFormatter('fr', \NumberFormatter::CURRENCY)
=> NumberFormatter {#189}
>>> $nf->formatCurrency(20, 'EUR')
=> "20,00 €"
>>> $nf = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY)
=> NumberFormatter {#178}
>>> $nf->formatCurrency(20, 'EUR')
=> "€20.00"
```

Or do you think there is another issue ?

> The only thing that i don't understand is here. The activation of the intl extension will not change anything. As you said the function seems "limited".

The line you linked will not be used if you have the intl extension, because the stub provided by Symfony won't be registered, and your code will use the native `\NumberFormatter`.

**Comment by Th3Mouk** [comment]
@ogizanagi thanks !
> The line you linked will never be executed if you have the intl extension, because the stub provided by Symfony won't be registered, and your code will use the native \NumberFormatter.

It's exactly the information that I missed.
If you had a link of piece of code where I can learn a little more.

This issue can be closed in same time of the PR.

**Comment by ogizanagi** [comment]
@Th3Mouk Everything you need to know about that is explained in the [component documentation installation section](http://symfony.com/doc/current/components/intl.html#installation).

Glad I helped 😉

**Comment by nicolas-grekas** [comment]
@Th3Mouk should be closed? What's remaining? Worth describing in a new issue?
