### ISSUE TITLE
Invalid Yaml accepted

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#19436]
`{1:""}` [is invalid yaml](http://yaml-online-parser.appspot.com/?yaml=%7B1%3A%22%22%7D&type=json), but our parser accepts it.
It should be `{1: ""}` (space after `:`)

**Comment by stof** [comment]
how does it parse it currently ?

**Comment by nicolas-grekas** [comment]
```
Array (
    1 => ''
)
```

**Comment by xabbuh** [comment]
I'll look into it.

**Comment by xabbuh** [comment]
see #19472
