### ISSUE TITLE
[cache] Filesystem adapter sets incorrect timestamps

### ISSUE THREAD

**Issue by pkruithof** [symfony/symfony#19431]
The new Cache component uses the filesystem adapter by default. 

```sh
$ ls -l pools/TP1BESnWfV/y/U/wx+WpNt6nS-+Gb2SEdxQ
-rw-r--r-- 1 www-data www-data 2409 9223372036854775807 pools/TP1BESnWfV/y/U/wx+WpNt6nS-+Gb2SEdxQ
```

The modification date is incorrect here: 9223372036854775807. When I stat it, I also get this date:

```sh
$ stat pools/TP1BESnWfV/y/U/wx+WpNt6nS-+Gb2SEdxQ
  File: 'pools/TP1BESnWfV/y/U/wx+WpNt6nS-+Gb2SEdxQ'
  Size: 2409      	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 9187238     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   33/www-data)   Gid: (10000/www-data)
Access: 2016-07-26 13:17:17.719261683 +0200
Modify: 9223372036854775807
Change: 2016-07-19 15:59:20.179413813 +0200
 Birth: -
```

Test that it's incorrect:

```sh
$ php -r "echo date('r', 9223372036854775807);"
Sun, 04 Dec 219250468 15:30:07 +0000
```

**Comment by patrick-mcdougle** [comment]
This seems to be a issue in linux not in this component. In my opinion, this should be reverted, as PHP_INT_MAX is effectively cache forever whereas the new code defaults to one year.

```
vagrant@RMBP-015-vagrant:/tmp/foo$ php -a
Interactive mode enabled

php > touch('/tmp/foo/foo-test', pow(2, 55));
php > touch('/tmp/foo/foo-test2', pow(2, 56));
php > exit
vagrant@RMBP-015-vagrant:/tmp/foo$ ls -la
total 8
drwxrwxr-x 2 vagrant vagrant 4096 Jul 31 19:44 ./
drwxrwxrwt 6 root    root    4096 Jul 31 19:43 ../
-rw-rw-r-- 1 vagrant vagrant    0 Jun 13  1141709097 foo-test
-rw-rw-r-- 1 vagrant vagrant    0 72057594037927936 foo-test2
```

If I had to make any guesses, I'll bet this happens when the year's representation can no longer fit into a 32 bit integer.

EDIT: according to the article on the [2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). I was close. It's 2^32 + 1900.

> Most operating systems designed to run on 64-bit hardware already use signed 64-bit time_t integers. Using a signed 64-bit value introduces a new wraparound date that is over twenty times greater than the estimated age of the universe: approximately 292 billion years from now, at 15:30:08 on Sunday, 4 December 292,277,026,596. The ability to make computations on dates is limited by the fact that tm_year uses a signed 32 bit int value starting at 1900 for the year. This limits the year to a maximum of 2,147,485,547 (2,147,483,647 + 1900).

**Comment by pkruithof** [comment]
You're right in that it's not a bug in this component (as also demonstrated by the php example in my OP). However using the maximum integer results in dates that are inconsistent with 'normal' dates, and thus can be problematic when computing with them (for instance, if you'd want to compare the year with another date).

Since there is no real way to let file caches not expire by date (unless you use some form of metadata), I'd say you could set the date further in the future to accomplish the same goal of "effectively cache forever", while still maintaining valid dates to work with.
