### ISSUE TITLE
[FrameworkBundle] Move AddConsoleCommandPass to Console component

### ISSUE THREAD

**Issue by Haehnchen** [symfony/symfony#19440]
After i integrated `console.command` tags into Shopware https://github.com/shopware/shopware/pull/559 we hade a discussion about `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass` and its FrameworkBundle dependency.

A project with `symfony/console` and `symfony/dependency-injection` need to copy this CompilerPass. @bcremer and @xabbuh had some ideas to move this class.

Maybe we can optimize command registration over dic somehow.

**Comment by iltar** [comment]
This class can indeed be outside of the `FrameworkBundle`.

If you want to optimize the information of the command, you'll have to somehow make the configuration static or extract it all together. This makes it possible to lazy-load the commands.

**Comment by bcremer** [comment]
I would like to move `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass` to 
`Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass`.

This would be consistent with the existing compiler passes in other components like `Symfony\Component\HttpKernel\DependencyInjection\FragmentRendererPass` or
`Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass`.

I am not sure about the migration process of `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass`. 

Should it extend from `Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass` to prevent duplicate code? Similarly this was already done for the `RegisterListenersPass` in this commit:  https://github.com/symfony/symfony/commit/89b8e0a9498101d352207011b83821574fc71a93.

This however would introduce a new dependency to `symfony/console` in `symfony/framework-bundle`.

**Comment by dunglas** [comment]
It can be a soft dependency: test if the pass class exists with class_exists before registering it. If the console component is not installed, the pass will not be registered.

**Comment by bcremer** [comment]
@dunglas I did something similar in the pull request: https://github.com/symfony/symfony/pull/19443/files#diff-687bdbb38a4dc672ca2a79f23e764892R95

What about `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass`? Should it be removed? 

If it stays and it can be deprecated but we cannot delegate to the new pass since it might not be present.

**Comment by Haehnchen** [comment]
@bcremer thx for this contribution
