### ISSUE TITLE
No $errorNames in UniqueEntity constraint

### ISSUE THREAD

**Issue by TobiasXy** [symfony/symfony#19447]
It seems all (or at least most) of the base validation constraints (Symfony\Component\Validator\Constraints) set an error code when they are building the ConstraintViolation.

But: The UniqueEntity constraint (\Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity) does not.
I currently create an API where I want to provide the users error codes with every constraint violation.
How am I supposed to do that with the UniqueEntity constraint (or more general with Constraints which do not set an error code)?

Wouldn't it be good to make the error code required for ConstraintViolations?

**Comment by jakzal** [comment]
Which error code do you mean? The UniqueConstraintValidator [sets the error code](https://github.com/symfony/symfony/blob/36ec08563e616e6e73f153cca5e77c964dce433f/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L138) just like other validators:

```php
 $this->context->buildViolation($constraint->message)
            ->atPath($errorPath)
            ->setParameter('{{ value }}', $invalidValue)
            ->setInvalidValue($invalidValue)
            ->setCode(UniqueEntity::NOT_UNIQUE_ERROR)
            ->addViolation();
```

**Comment by HeahDude** [comment]
https://github.com/symfony/symfony/pull/19309 will be part of next releases.

**Comment by HeahDude** [comment]
and https://github.com/symfony/symfony/pull/19333 as well.

**Comment by jakzal** [comment]
Cool, closing than :)
