### ISSUE TITLE
[Intl] Minimum stability problem of the component Intl

### ISSUE THREAD

**Issue by jjanvier** [symfony/symfony#19444]
Is there any reason why intl is declared as "mininum-stability: dev" on all its tags?

It seems really weird as now you recommend to replace `symfony/icu` by `symfony/intl`.

**Comment by stof** [comment]
``mininum-stability`` is a root-only setting. It only affects composer when the package installs its own dependencies for testing purposes. And we always run our tests against dev version of our dependencies in Symfony.

The ``mininum-stability`` has strictly no impact on the usage of the component.

**Comment by jjanvier** [comment]
@stof it has an indirect impact for us.

Imagine you have a package A that uses symfony/intl. Package A minimum stability is stable.
The package B requires package A. Package B minimum stability is also stable. 

Now we have to change the package B composer.json to add symfony/intl.

**Comment by stof** [comment]
no, you don't. ``minimum-stability`` is root only. It does not mean that you can only use dev versions of symfony components. The requirement constraints used in the component totally allow to fulfil them with stable release.

I think you are misunderstanding how composer works
