### ISSUE TITLE
Conflict ICU Symfony 2.8

### ISSUE THREAD

**Issue by syrinesa** [symfony/symfony#19453]
Configuration Checker

This script analyzes your system to check whether is ready to run Symfony applications.

RECOMMENDATIONS
To enhance your Symfony experience, it’s recommended that you fix the following:

intl ICU version installed on your system (57.1) should match the ICU data bundled with Symfony (55.1)
In most cases you should be fine, but please verify there is no inconsistencies between data provided by Symfony and the intl extension. See https://github.com/symfony/symfony/issues/15007 for an example of inconsistencies you might run into.

Re-check configuration

**Comment by Tobion** [comment]
Closing as there is no problem description except the copy pasted text from the config checker.
