### ISSUE TITLE
Profiler - DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by Marcpepe** [symfony/symfony#19462]
Hi, 

I am getting an error in the Profiler : 

```
An exception has been thrown during the rendering of a template
("DateTime::__construct(): Failed to parse time string (1469696585) at
position 8 (8): Unexpected character") in "@WebProfiler/Profiler/layout.html.twig" at line 33.
```

It refers to [this line](https://github.com/symfony/symfony/blob/3.0/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/layout.html.twig#L33) (I'm using version 3.0).

Any idea were it might be coming from ?

If it's any help, I am having the problem on both 5.5.28 and 5.6.24 versions..

Any help is appreciated !

**Comment by javiereguiluz** [comment]
The line where the error is originated is the following:

```twig
<dd>{{ profile.time|date('r') }}</dd>
```

It's so simple that I cannot see any error on it ... except when the `profile.time` property is not really a datetime. Could you please show us the value of `{{ dump(profile.time) }}` just before that line? Thanks!

**Comment by jakzal** [comment]
@Marcpepe is this something you experience (or could reproduce) on the Standard Edition?

Does this work on your machine? `php -r 'var_dump(date("r", 1469696585));'`

**Comment by xabbuh** [comment]
@Marcpepe Any updates here? :)

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback and because we haven't received any similar reports.
