### ISSUE TITLE
[FrameworkBundle] AddRequestFormatsListener priority not enough high for RouterListener

### ISSUE THREAD

**Issue by ohaag** [symfony/symfony#19469]
Hello!

I was wondering about priority problems in _FrameworkBundle_ in Symfony 2.8 at least.

Both of them listen on _kernel.request_ but [_RouterListener_](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php) has a 32 priority and [_AddRequestFormatsListener_](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/AddRequestFormatsListener.php) has no priority set (so, it means 0).
Because of this priority, when the _RouterListener_ throw an exception as _NotFoundHttpException_ or _MethodNotAllowedHttpException_ for example, it has no knowledge about custom format specified in _framework_ configuration.

If I add custom mime types as explained in:
http://symfony.com/doc/current/cookbook/request/mime_type.html

Then if I want to implement an _HttpExceptionListener_ that convert exception message in a custom mime type from an _Accept_ Header, I'm stuck. If this Listener need to convert _RouterException_, its priority need to be above 32 but if I want to know my custom mime types to know that 'application/vnd.v1+json' is json format, priority need to be below 0. (p > 32 and p < 0 impossible)

I'll go for the _FosRestBundle_ solution, creating a _MimeTypeListener_ with a high priority but I thought it is redundant.
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.8.0/Resources/config/mime_type_listener.xml

I would know if there was a reason that prevents to rise the _AddRequestFormatsListener_ priority.

**Comment by bwegrzyn** [comment]
I am wondering about this as well.

AddRequestFormatsListener is running after the Firewall listener, which means the authentication process does not have access custom formats that are defined. This is turn means that I cannot decode the username/password in a custom format before it reaches the Firewall listener.

**Comment by xabbuh** [comment]
@symfony/deciders Is there a reason that prevents us from running the `AddRequestFormatsListener` before the `RouterListener`?

**Comment by xabbuh** [comment]
ping @symfony/deciders
