### ISSUE TITLE
hiddeninput.exe not testable with interactive input

### ISSUE THREAD

**Issue by Fuzzyma** [symfony/symfony#19463]
I wrote a console command which makes use of the `setHidden` feature to enter passwords.
When I wanted to test this command I came across a strange issue. My phpunit was stopping and hanging in the `hiddeninput.exe` process. Obviously the console was waiting for input.
`hiddeninput.exe` ignored my input given by

```php
$command->setHelperSet($this->getHelperSet("SomeRandomInputString\n"));
```

I then was able to "unfreeze" my console by just giving the desired input to the console (just pressing enter in this case).

I uploaded an example project which comes with a command and a test to show this issue.
Just clone it, run `composer install` and `phpunit` to reproduce:
https://github.com/Fuzzyma/hidden-input-bug

PS: A pic showing what my console is doing:

![hiddeninput](https://cloud.githubusercontent.com/assets/3540542/17210916/5afabefc-54c6-11e6-8b5d-e75a1a51d122.PNG)

At the bottom you can see the process which runs at the moment

**Comment by stof** [comment]
This is logical, because ``hiddeninput.exe`` does not use stdin to ask for the value (because stdin cannot be hidden on windows)

**Comment by Fuzzyma** [comment]
Is there any way to test this properly?

**Comment by javiereguiluz** [comment]
If someone can think of a trick to test this, please share it. Otherwise, we'll add a note in the docs explaining that this cannot be done. Thanks!

**Comment by sstok** [comment]
Basically you would have to extend the QuestionHelper (set hidden to false) and overwrite it in the HelperSet.

We did this for maxAttempts in Gush https://github.com/gushphp/gush/blob/0ae54b1da803767112dbe509dcb96545539cd964/src/Helper/GushQuestionHelper.php (hmm, return value of `getName()` is wrong)

**Comment by javiereguiluz** [comment]
Closing this as "fixed" thanks to the solution proposed by @sstok. If this doesn't work, @Fuzzyma please tell us so we can update the docs about this. Thanks!

**Comment by delamart** [comment]
I would re-open this issue. As I'm not sure @sstok 's "solution" is one ... (I must admit I don't really understand how it solves anything related to this issue).

At the very least I would put in the documentation that you can't Unit Tests for hidden questions as they trigger `shell_exec` for which you can't provide any pre-defined Input.

Ideally QuestionHelper::doAsk() would ignore hidden questions in the context of a CommanderTester with Inputs. I'm going to try an figure out how to do this now in my tests.

**Comment by delamart** [comment]
OK I found my current solution which is probably close to the one from @sstok. I also created a special QuestionHelper just for Unit testing:

```php
<?php

namespace Tests\Helper;

use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

/**
 * Class TestQuestionHelper
 *
 * Used to override hidden questions so they can be unit tested like all other questions
 * @link https://github.com/symfony/symfony/issues/19463
 *
 * @package Ecolint\BeeClientBundle\Tests\Helper
 */
class TestQuestionHelper extends QuestionHelper
{
    public function ask(InputInterface $input, OutputInterface $output, Question $question)
    {
        if($question->isHidden())
        {
            $question->setHidden(false);
        }
        return parent::ask($input, $output, $question);
    }

}
```
which I then use in my unit test:
```php
<?php

namespace Tests\Command;

use Tests\Helper\TestQuestionHelper;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;
// ... 

class HiddenCommandTest extends TestCase
{
    public function testExecute()
    {
        $command = $application->find('your:command');

        // Override the default QuestionHelper so we can test hidden questions
        $helper = new TestQuestionHelper();
        $helperset = $command->getHelperSet();
        $helperset->set($helper, 'question');

        $commandTester = new CommandTester($command);

        $commandTester->setInputs(array(
            'input for hidden question'
        ));

        $commandTester->execute(array('command'  => $command->getName()));

        // Do your assertions
    }
}
```

I would definitely mention this issue in the docs and maybe `QuestionHelper` could be modified to remove the hidden flag if it detects a Unit Test environment (not sure how).
