### ISSUE TITLE
StreamedResponse creates Duplicate Response Headers with small message body

### ISSUE THREAD

**Issue by ruttencutter** [symfony/symfony#19467]
I'm running into an issue using a StreamedResponse to return a file to the user that can be limited in size by a post parameter.  In some cases, we return 10,000 rows, and in others only 4.

Since upgrading to Symfony 3.x our tests related to small sized files have broken on our front end because of duplication of the Symfony-Derived HTTP headers:

apiVersion (we inject this one time via a kernel.event_listener, kernel.response event)
Cache-Control
Set-Cookie
X-Debug-Token
X-Debug-Token-Link

I've been able to duplicate this issue in 3.0 and 3.1, and it is identical.  Seems to be related to the body size of the response, as I've stripped out all other related code.  Small body, double headers. Larger body, works as expected.

So if you test on app_dev.php you will see the debug tokens duplicated with the iterator set to 10.  Set the iterator to 1000 and the duplicated headers go back to normal.

http://pastebin.com/NQMGrHEJ

**Comment by stickyhands** [comment]
+1 met the same problem few days ago

**Comment by AAstakhov** [comment]
@ruttencutter I've been trying to reproduce with the given example, but I don't see duplicated headers.
Why do you have Set-Cookie header? The code in your example doesn't set any cookie.

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. Please comment if you can provide more details and we can consider to reopen this issue.

**Comment by WARrior-Alex** [comment]
Hi!

Well, after some researches as small workaround for this issue I can suggest to use `flush()` method in your callback.

**Comment by RichTech** [comment]
Hi,

had same problem. Double headers "Cache-Control" and others. If I dont return the response, but call the sendHeaders() and sendContent() on the response object, all is correct. But, if i return the response object, symfony sends the headers I said to send + default headers.

This wasnt the case few weeks ago. In this time I upgraded from v3.3 to v3.4.
