### ISSUE TITLE
VarDumper Parse Error: Expected String when dumping JSON

### ISSUE THREAD

**Issue by Jakobud** [symfony/symfony#19471]
I have a decoded JSON string that I am dumping using VarDumper. Actually I'm using Laravel's `dd()` method (dump & die) but it uses VarDumper in the background. Here is the framework code:

https://github.com/laravel/framework/blob/be353964453ee0f750e6562419a32d387e8909f0/src/Illuminate/Support/helpers.php#L508

Anyways, here is a screenshot of what I'm getting:

![screen shot 2016-07-28 at 11 09 53 am](https://cloud.githubusercontent.com/assets/87356/17222085/d729f8d4-54b3-11e6-9db7-30ebeeb0bed9.png)

It appears that the `#158` that is being printed out is causing some sort of issue here. The only thing I can think of is that I think xdebug is running but I wouldn't expect that to interfere here.

**Comment by stof** [comment]
what is this Error thing displayed here ? Where does it come from ?

**Comment by Jakobud** [comment]
I assumed it was part of VarDumper. Is it not? Here is the DOM:

![screen shot 2016-07-28 at 1 31 48 pm](https://cloud.githubusercontent.com/assets/87356/17226654/bd7e1dde-54c7-11e6-8055-c5d6491ee629.png)

If this is not apart of VarDumper I apologize.

**Comment by Jakobud** [comment]
Ah man this was some stupid chrome extension I had installed. Sorry I thought this was part of VarDumper. Sorry!
