### ISSUE TITLE
Bus error on composer install

### ISSUE THREAD

**Issue by anacicconi** [symfony/symfony#19475]
One of my colleagues is having a problem running composer install on his computer. I'm not sure it's a bug related to Symfony but, as I can't find any information on internet, I would like to know if anybody have already had this issue and know how to solve it. 

    Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
    Bus error
    Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

    [RuntimeException]
    An error occurred when executing the "'cache:clear --no-warmup'" command:
    Bus error
    .

We use a docker environment to run the project. It's a regular docker-compose with php, sql, elastic... The problem only happens on his computer, which is a Mac and it's aleatory. If we delete the cache folder manually, then we can run the command without any problem. However, if we run composer install again the bug reappears.

**Comment by lecneri** [comment]
Try using with -vvv which is more verbose and will give u more details

**Comment by anacicconi** [comment]
Hi @lecneri, thanks for your answer but this is already the output we have when we run the command with verbose mode. The only information is: Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

**Comment by peteraba** [comment]
@anacicconi I'm almost certain that it has to do with the a volume being linked from the host. try the following:

1. tty into the container (docker exec -it containerhash bash)
2. copy `composer.json` into `/tmp` (for example);
3. run composer install 
4. move the `vendor` directory back to the source directory.

**Comment by nicogies** [comment]
Hello, here is the workaround we use:

```sh
composer install --no-scripts
php app/console assets:install --symlink --relative
sudo rm -Rf app/cache/*
```

Best,
Nicolas

**Comment by anacicconi** [comment]
Thanks @peteraba and @nicogies !
