### ISSUE TITLE
HTTP Status header if we prefix route

### ISSUE THREAD

**Issue by lecneri** [symfony/symfony#19483]
Hi,

Imagine you have a controller FooController and you want to prefix all routes from this controller of it with /foo. Eg.: /foo/bar, /foo/foo, etc. 

I don't know if I'm doing wrong but I use @Route annotation at class declaration, and works very well for me. Today when I was creating a test class, happened to isSuccessful() from Response was returning false, and I found out that was because the Status Code was 301 (moved permanently). Now I'm wondering if this HTTP status code is correct, or shouldn't be 200? Here an example of FooController

```php
/**
 * @Route("/foo")
 */
class FooController extends Controller
{
    /**
     * @Route("/bar")
     */
    public function barAction()
    {
        return new Response("bar");
    }
```

**Comment by bhavin-nakrani** [comment]
Can you paste code how you generate url for ```/foo```?

**Comment by jameshalsall** [comment]
A 301 response code is not in the class of status codes that indicates a successful response (2xx): http://www.restapitutorial.com/httpstatuscodes.html

**Comment by lecneri** [comment]
@jameshalsall  but the code I used above returns header 301, and I'm here to discuss if the example above shouldn't be in success class.

@bhavin-nakrani You meant /foo root? If so, all u gotta do is use only / in @Route annotation above the action
`
/**
 * @Route("/")
 */
public function indexAction()
{
   return new Response("index Action");
}
`
Sorry be this short but type code using tablet is a pain hehe. Just add this method to the class example I created in 1st post.

**Comment by xabbuh** [comment]
I do not understand how you are actually accessing your application when you get this error (probably a functional test?). Can you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by lecneri** [comment]
@xabbuh Hi, sorry, I think language may being a barrier here, because english is not my main language. 

I realize that the header only changes with one  route (/). Which makes sense for me, but anyway I made this Foo Project with a simple test that shows what I was talking about. https://github.com/lecneri/Foo.

Another thing I noticed while I was doing this example is when I generate Controller using console, the tests were placed in src/AppBundle/test is this normal or should be placed in tests/AppBundle ?

**Comment by jakzal** [comment]
> Another thing I noticed while I was doing this example is when I generate Controller using console, the tests were placed in src/AppBundle/test is this normal or should be placed in tests/AppBundle ?

see https://github.com/sensiolabs/SensioGeneratorBundle/pull/494

**Comment by jameshalsall** [comment]
@lecneri your problem is that on this line: https://github.com/lecneri/Foo/blob/master/src/AppBundle/Controller/FooController.php#L15 your route definition should be 

`@Route("")`

then you won't see a 301 from your test but a 200

**Comment by lecneri** [comment]
@jameshalsall Yeah, I never thought that an empty route would do the trick. Thanks man! Well, that being clarify I think we can close this issue.

@jakzal thank you for the info!
