### ISSUE TITLE
Symfony\Component\Console\Style\SymfonyStyle::ask fails formatting output correctly if last character of $question or $default is an escaped Backslash

### ISSUE THREAD

**Issue by kalti** [symfony/symfony#19493]
``` php
$io = new SymfonyStyle($input, $output);
$io->ask('question with default value Backslash\\', '\\');
```

This code snippet will print the following in command line:
```
 question with default value Backslash</info> [</comment>]:
 > 
```

- symfony/console v3.1.3
- php v7.0.9
- Mac OSX v10.11.6

**Comment by chalasr** [comment]
I can confirm the bug. However it will not be easy to fix, backslashes are escaped (and they should be) so not sure we should fix the fact that the backslash doesn't exist in the output, but still, the way we are escaping it causes the weird things you're showing (`</comment>` part of the output).

I will try to do something for that.
Status: reviewed

**Comment by sstok** [comment]
Use the `\Symfony\Component\Console\Formatter\OutputFormatter::escape()` in `\Symfony\Component\Console\Helper\SymfonyQuestionHelper`.

And it fixes it 👍 (not sure about side effects, like a default with a custom style. but from what I saw it should work).

With duplicate backslash:
![schermafbeelding 2016-09-18 om 13 45 28](https://cloud.githubusercontent.com/assets/904790/18615394/346bc066-7da6-11e6-868e-801a48d69a40.png)

With single backslash:
![schermafbeelding 2016-09-18 om 13 47 02](https://cloud.githubusercontent.com/assets/904790/18615400/6ab1d9f8-7da6-11e6-82da-78402f670594.png)

**Comment by chalasr** [comment]
As clever as simple, thank you @sstok! I do not see any possible side effect for now.
See #19961
