### ISSUE TITLE
accessing protected member in the class CacheItem without setter

### ISSUE THREAD

**Issue by hackeurtalibe** [symfony/symfony#19509]
in the construct of the ArrayAdapter class in the Cache colmponent the protected member in the CacheItem class are accesssed directly

**Comment by iltar** [comment]
So what's the problem?

**Comment by hackeurtalibe** [comment]
The problem is that a protected property cant be accessed directly in a class that does not extend that class as you know it

Envoyé de mon iPhone

**Comment by hackeurtalibe** [comment]
If you look at the class ArrayAdapter in the constructer you'll see

Envoyé de mon iPhone

**Comment by hackeurtalibe** [comment]
And even phpstorm signals this error

Envoyé de mon iPhone

**Comment by iltar** [comment]
That's because it uses the closer bind method to reach them: https://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

**Comment by xabbuh** [comment]
Closing here as this is not a mistake. Note that you may have to change your PhpStorm settings (the PHP version used for validation) to not display any errors here.
