### ISSUE TITLE
[ASK] Show Profiler in Production When Logged In As Super Admin

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#19505]
I read this article

```
https://symfony.com/doc/current/profiler/matchers.html
```

And try to show profiler even in production but only for Super Admin.

My Step:

1. I move `new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle(),` to global bundle (not only on test or dev)

2. I follow this tutorial `https://symfony.com/doc/current/profiler/matchers.html#creating-a-custom-matcher`

The problem:

My profiler always show, not only for super admin.

I search stackoverflow and also google before asking on it. I don't know, it is bug or i have an error

NB: sorry for my bad english

**Comment by sstok** [comment]
Please use one of the support channels to get support: http://symfony.com/support

Make sure you clear the cache `bin/console cache:clear --env=prod --no-debug` whenever you change the configuration for production.

**Comment by ad3n** [comment]
Sorry, it is my mistake
