### ISSUE TITLE
Allow Workflow code reuse

### ISSUE THREAD

**Issue by RoSk0** [symfony/symfony#19502]
I want to extend Symfony\Component\Workflow class to make my specific workflow.
The only thing that I need to change is doCan() method, but I can not do it because it is **private**. So my question is should I create completely new class copying all the code and modifying small bit(which seems wrong) or I can submit a pull request to change methods visibility? I'm pretty new with Symfony so sorry if something is not right with my question.

**Comment by robfrawley** [comment]
I have no authority with regard to accepting PRs for this project, but I can point out that several PRs of the same character have recently been accepted. I'd just go for it and create one. Unless there is a reasoned issue to obfuscate/limit extensibility (such as sensitive data like you'd find in a security-related component), there shouldn't be an issue.

**Comment by unkind** [comment]
If you really need to replace default behaviour of `doCan`, think about it in this way: it probably means that `Workflow` should have some kind of strategy and you want to replace default strategy with another one:
```php
$workflow = new Workflow(..., new MyCustomAwesomeStrategy());
```
It's way better than solve your issues with inheritance:
```php
class WorkflowWithCustomDoCanStrategy extends Workflow
{
   // ... 
}

class WorflowWithCustomDoCanStrategyAndSomeAdditionalBehaviour
    extends WorkflowWithCustomDoCanStrategy
{
   // ...
}
```

**Comment by RoSk0** [comment]
@unkind Your totally right and it already have - **Definition** and **MarkingStore**. I didn't completely got how it supposed to work from the beginning and bug my code that was creating definition got me to that state. Now when I have fixed that bug and got better understanding of the process it makes more sense why the **Workflow** class is so restricted to extension - there is no need in it.
