### ISSUE TITLE
[DX][WDT] Link to last 10 into navbar

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#19506]
Hi all

It would be great if from the WDT, we could access this url
_profiler/{token}/search/results?ip=&limit=10 direclty (the last 10)

In fact, my use case is, when I want to check my "post" request, which actually redirect to a "get" one, i have to click on the route status 200, then last 10, then find my "post" request. A long process.

Or better if it is possible, have the link as well to the "post" request profiler directly next to the "get" one if we detect we have been redirected previously.

Maybe the option one is faster

EDIT : image addition
<img width="299" alt="img" src="https://cloud.githubusercontent.com/assets/13205768/17409438/97fd2bec-5a6f-11e6-9399-209b0ae746e1.png">

Thanks

**Comment by ogizanagi** [comment]
Should we close this one as 2 different PRs were rejected independently from the implementation?

**Comment by stof** [comment]
Yeah, closing this as we rejected the feature (see PRs for the explanations)
