### ISSUE TITLE
Links for documentation not consecutive (prev/next links)

### ISSUE THREAD

**Issue by dprocaccini** [symfony/symfony#19513]
There are few articles whose "« previous" link do not actually match the article that came before it.
Examples: 

Breadcrumb | Link | Previous | Next | Errors/Notes                                      
|:---|:---|:---|:---|:---|
Home / Documentation / Routing | http://symfony.com/doc/current/routing.html | « The Routing Component | Controller » | Since this is the Routing page under "Getting Started" the _previous_ link should be back to "Creating Pages"
Home / Documentation / Bundles / The Bundle System / Bundles / Best Practices for Reusable Bundles | http://symfony.com/doc/current/bundles/best_practices.html | « How to Install 3rd Party Bundles | How to Use Bundle Inheritance to Override Parts of a Bundle » | This is the first page after "The Bundle System" under Guides > Bundles, so the _previous_ link should be back to "The Bundle System". 

The "Learn More" section appears to be a table of contents for these sub-articles, but the links are often not in order, and clicking through Guides consecutively may skip content listed under "Learn More".  For example, clicking on each next article under "Guides > Bundles" will never show the article for "How to Remove a Bundle".

**Comment by iltar** [comment]
Can you reopen this issue in the docs repository? https://github.com/symfony/symfony-docs/

**Comment by javiereguiluz** [comment]
Moved to https://github.com/symfony/symfony-docs/issues/6836.
