### ISSUE TITLE
Windows 10 does not support console colors any more

### ISSUE THREAD

**Issue by jhdxr** [symfony/symfony#19520]
#18385 introduced CLI color suport under Windows 10, and I confirm that works when I use win 10.0.10586.

However, I upgrade to the redstone version (10.0.14393), it seems the color support has been removed.

**Comment by jameshalsall** [comment]
I imagine this is because Ubuntu bash has been added in this release.

**Comment by ste93cry** [comment]
I have the same problem after upgrading to Windows 10 Anniversary Update. The issue affects Composer as well (https://github.com/composer/composer/issues/5542)

**Comment by jhdxr** [comment]
@jameshalsall if so, microsoft made a very silly desicion. I don't want to setup my development enviroment again...

**Comment by alcohol** [comment]
Does [this](https://github.com/composer/composer/issues/5323#issuecomment-220871883) help?

**Comment by ste93cry** [comment]
No, I'm using the non-legaci console and it doens't work

**Comment by bckp** [comment]
Colors still work on PowerShell, but not in CMD

**Comment by dequeues** [comment]
MS removed ANSI from the native command line, at least in the latest build 14393.10, version 1607.

**Comment by ste93cry** [comment]
while I trust you, do you have any reference where this is confirmed officially?

**Comment by dequeues** [comment]
I don't, I've been looking myself. I'll keep looking and if I get any resources I'll let you know.

**Comment by ste93cry** [comment]
I really hope Microsoft did not remove officially the colors from the cmd, adding support for them was one of the best things they could do for Windows 10. I prey for this being just a regression

**Comment by mlocati** [comment]
Color support is still available in Windows 10 Console.
The problem is that for Windows 10.0.10586 it was enabled by default, but with Windows 10.0.14393 (Anniversary Update) it must be explicitly enabled by the program.

I already asked the PHP core team to enable it for `php.exe`: see https://bugs.php.net/bug.php?id=72768

**Comment by gremo** [comment]
Same problem here. How to switch back to the "uncolored" version without the weird characters?

**Comment by wouterj** [comment]
@gremo for the moment, passing `--no-ansi` with each command should work.

**Comment by mlocati** [comment]
Before updating the Console code I'd wait to see what happens with https://bugs.php.net/bug.php?id=72768: if they implement what I suggest there for the various PHP versions we can keep using colors on Windows

**Comment by gremo** [comment]
@wouterj thanks, I was hoping in a "global" solution (i.e. compatibility mode or other stuff).

**Comment by cirdog** [comment]
If this hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer eliminates the need to flag it for every command.

**Comment by jameshalsall** [comment]
Or you can just alias it, something like...

`doskey composer=composer.bat --no-ansi`

(rough guess)

**Comment by uzairali001** [comment]
Does anyone found any solution?
how git is showing colors in cmd?

**Comment by mlocati** [comment]
> Does anyone found any solution?
> how git is showing colors in cmd?

We can't enable ANSI colors via PHP script:s it has to be done by php.exe itself. https://github.com/php/php-src/pull/2103 implements support to this, but we have to wait for PHP 7.2 to be released

**Comment by stof** [comment]
in the meantime, you should keep using other supported ways: ConEmu or Ansicon

**Comment by Nek-** [comment]
Just for information. I really like [Mintty](https://github.com/mintty/wsltty) as windows terminal.

**Comment by vferko** [comment]
Console colors seem to be an issue of newer Windows 10...
http://stackoverflow.com/q/44047988/985454

![image](https://cloud.githubusercontent.com/assets/2313018/26202882/52010a68-3bd9-11e7-96bd-162c171e3702.png)
