### ISSUE TITLE
Recompile container manually

### ISSUE THREAD

**Issue by sagikazarmark** [symfony/symfony#19525]
I am working on a Docker container setup with symfony (can be found [here](https://github.com/webplates/symfony-standard)). The most common problem is how to inject parameters runtime into a symfony application. So far I simply cleared the cache upon container start, but I realized that in some applications this might be a heavy operation. My idea now is to recompile the DI container only: https://github.com/webplates/symfony-standard/pull/42/files#diff-c23da96dc8986a4cee89980f3aad30e0R78

What do you think? Is this a safe operation? Is it possible that some other cache parts rely on compiled container parameters?

Initially I wanted to boot the kernel and execute compile afterwards, but that gave me the following error, so I decided to "partially" boot the kernel and compile the container without checking it's freshness.

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'The service "security.firewall" has a dependency on a non-existent service "security.request_matcher.5314eeb91110adf24b9b678372bb11bbe00e8858c519c088bfb65f525181ad3bf573fd1d".' in /home/mark/Projects/webplates/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
Stack trace:
#0 /home/mark/Projects/webplates/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
#1 /home/mark/Projects/webplates/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidRefere in /home/mark/Projects/webplates/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 58
```

**Comment by javiereguiluz** [comment]
In my experience, messing with these things is always tricky and leads to fragile solutions. If you want to inject parameters at runtime, you may check out [OpenSkyRuntimeConfigBundle](https://github.com/opensky/OpenSkyRuntimeConfigBundle).

In any case, this issue looks like a question about advanced Symfony usage instead of a bug report or feature request, so I'm closing it for now. Please consider using https://symfony.com/support to continue looking for ways to solve this. Thanks!

**Comment by sagikazarmark** [comment]
@javiereguiluz although you are right about this being a question, since the Dependency injection is a separate component too, I think it would be nice if there was an official recommendation about this. Personally I think that cache warmers should not store any parameters in custom cache files.

Just for reference, we are talking about this part of the code: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L478

**Comment by sagikazarmark** [comment]
http://stackoverflow.com/questions/38777550/recompile-symfony-container-manually
