### ISSUE TITLE
Duplicate keys in Yaml fail silently

### ISSUE THREAD

**Issue by alexpott** [symfony/symfony#19526]
When the yaml parser reads
```
foo: bar
foo: bar2
```

It will return an array with the first key. This is unfortunate for a couple of reasons.

1. It is not to spec. The Yaml spec is clear that duplicate keys should be treated as an error - see http://yaml.org/spec/1.2/spec.html#id2759572
2. The current behaviour of choosing the first key is pretty unique. See:
```
Psy Shell v0.7.0 (PHP 7.0.7 — cli) by Justin Hileman
>>> $a = ['a' => '1', 'a' => '2']
=> [
     "a" => "2",
   ]
```
Also it is the opposite behaviour to the PECL yaml parser (which behaves like PHP) so allowing users to swap between implementations can have interesting affects.

**Comment by alexpott** [comment]
So reading the links from the Symfony Yaml component where there are tests for this behaviour it links to http://yaml.org/spec/1.1/#id932806

> It is an error for two equal keys to appear in the same mapping node. In such a case the YAML processor may continue, ignoring the second key: value pair and issuing an appropriate warning.

So what I think we are missing is _and issuing an appropriate warning_

**Comment by javiereguiluz** [comment]
This is the PR that introduced this behavior: #10902 and in other issues we've been discussin about this behavior too: #14512.

@xabbuh is the main Yaml component maintainer, so let's see what he thinks about introducing changes related to this. Thanks!

**Comment by sstok** [comment]
Would it be possible to use a silenced warning or a flag to throw/warn on a duplicate key?

**Comment by alexpott** [comment]
@sstok I was just coding up a PR to introduce a new parse flag PARSE_EXCEPTION_ON_DUPLICATE

**Comment by xabbuh** [comment]
I guess that the current behaviour was implemented based on the assumption that duplicate keys are allowed (see the quoted part of the spec at https://github.com/symfony/symfony/issues/19526#issuecomment-237524176). However, as you can this part is from the YAML 1.1 spec, but we do follow the YAML 1.2 which does forbid duplicate keys (see the issue description).

With this in mind I suggest to deprecate the current behaviour in Symfony 3.2 and throw a `ParsException` starting with Symfony 4.0.

@symfony/deciders What are your thoughts on this?

**Comment by javiereguiluz** [comment]
@xabbuh I agree: deprecate in 3.2; exception in 4.0.

**Comment by dunglas** [comment]
I agree too. Duplicate keys can be a pain to debug anyway.

**Comment by patrick-mcdougle** [comment]
Does this effect the ability to include other config files? Like how the config_prod.yml file loads the config.yml file? Or is that a different concept that does that?

**Comment by xabbuh** [comment]
@patrick-mcdougle That's a different concept which is specific to how the DependencyInjection and Routing component handle the merging of configuration files that have been parsed by the parser from the Yaml component.
