### ISSUE TITLE
ServiceNotFoundException "debug.security.all.decision_manager"

### ISSUE THREAD

**Issue by ab2llah** [symfony/symfony#19536]
hi.my symfony website was just fine.suddenly i saw this error:

    ServiceNotFoundException in ContainerBuilder.php line 771:
    You have requested a non-existent service "debug.security.all.decision_manager".

env=prod works just fine but when i try to open any page on env=dev i see this error.
 please help i did everything to fix it

**Comment by javiereguiluz** [comment]
@ab2llah thanks for reporting this issue. Please tell us:

1) Your current Symfony version
2) If this error happened after updating your Composer dependencies

**Comment by ab2llah** [comment]
i use version 3.1.2
i updated my composer dependencies just now.
the update fixed my problem! thanks!
