### ISSUE TITLE
[Form] DateType fails parsing when midnight is not a valid time

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#19531]
In some timezones, **midnight may not be a valid date**; this happens when the DST change was done on midnight. It's a poor choice, and it was done only in the past. If you enter those dates in a `DateType`, it gets rejected as invalid. 

Under the hood, the issue is with the `\IntlDateFormatter` that is initialized with the current timezone, when with a simple date it can be avoided... Here: https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L119

Maybe decoupling between DateType and DateTimeType could be a solution?

In my case, TZ is `Europe/Rome` and one of the infamous date is `1978-05-28`; I can reproduce the issue in this 3val: https://3v4l.org/NDnbm
DateTime doesn't suffer this bug: https://3v4l.org/ZmQ1q

Mainly, the Form uses the intl extension, that uses ICU, and that assumes midnight as the hour if not specified, which is what happens when  you use a `DateType` field.

I tried to open a bug on https://bugs.php.net/bug.php?id=72649 but it got closed... What can we do about it?

PS: this issue surfaced already multiple times: #18267 #16518 #16368

**Comment by mbeccati** [comment]
For reference, I've closed the php.net bug as ICU returns an error and there's little we can do in the intl extension. Sure, ICU could be smarter, but its behaviour can't be altered.

In any case, think that the error lies in the way the date is parsed though. Since we're not talking about date+time, the date-only should be parsed using UTC, then eventually converted to a \DateTime in the local timezone, e.g.: https://3v4l.org/WivPk

**Comment by Jean85** [comment]
Thanks for the PR!! 
It includes a test that reproduces the bug, we're good to go!

Status: reviewed

**Comment by mbeccati** [comment]
Thanks @fabpot

**Comment by dkorsak** [comment]
After merge, there is bug on the DateTimeType::class form type - DateTimeToLocalizedStringTransformer class on branch master.

My timezone is Europe/Warsaw, +2h from UTC timezone.

Part of form:
```
$builder->add(
                'publishDateEnd',
                DateTimeType::class,
                [
                    'required' => false,
                    'widget' => 'single_text',
                    'format' => 'dd.MM.yyyy HH:mm',
                    'attr' => [
                        'placeholder' => 'dd.mm.yyyy HH:mm',
                    ],
                ]
```
When for example publishDateEnd is set as 2016-08-01 10:00:00 and I set in the web form date as 2016-08-01 12:00:00, after save form date back to 2016-08-01 10:00:00. Should be saved as 2016-08-01 12:00:00.

When I add 'view_timezone' => 'UTC' into widget option, date is set ac correct date.

**Comment by jakzal** [comment]
@dkorsak can you please open a new issue?
