### ISSUE TITLE
YamlFileLoader - Undefined class constant 'PARSE_CONSTANT'

### ISSUE THREAD

**Issue by Tabetha** [symfony/symfony#19532]
Hi, I found this behavior on Symfony dev version for **3.2**.

Problem is in file **Symfony/Component/DependencyInjection/Loader/YamlFileLoader** on line **396**. There is PHP no able to get constant **PARSE_CONSTANT** (see in error log).

```php 
try {
     $configuration = $this->yamlParser->parse(file_get_contents($file), Yaml::PARSE_CONSTANT);
} catch (ParseException $e) {
      throw new InvalidArgumentException(sprintf('The file "%s" does not contain valid YAML.', $file), 0, $e);
}
```

```
Error: Undefined class constant 'PARSE_CONSTANT'
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:396
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:69
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php:45
/home/travis/build/Tabetha/JMSTranslationBundle/Tests/Functional/AppKernel.php:61
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:571
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:484
/home/travis/build/Tabetha/JMSTranslationBundle/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:117
/home/travis/build/Tabetha/JMSTranslationBundle/Tests/Functional/Command/BaseCommandTestCase.php:29
/home/travis/build/Tabetha/JMSTranslationBundle/Tests/Functional/Command/ExtractCommandTest.php:55
```

**Comment by javiereguiluz** [comment]
It's strange because Yaml master version has `PARSE_CONSTANT` defined [in this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Yaml.php#L31):

![yaml_master_constant](https://cloud.githubusercontent.com/assets/73419/17416725/cfc6817a-5a8f-11e6-93b2-468ca5fca3ff.png)

**Comment by Tabetha** [comment]
I know this, and I agree, its strange. However I was not able to find proper solution or source of bad behavior, so I wrote it here. Weird is, only this constant is not working, so maybe problem with name. I try some more tests tomorrow.

**Comment by nicolas-grekas** [comment]
Phpunit embeds its own version of the yaml component. Are you using it when you get this exception? Then that's the cause...

**Comment by Tabetha** [comment]
Yes, I think this happened only running tests. But not 100% sure.

**Comment by iltar** [comment]
I've seen this issue come by before on `#symfony` and this developer was on dev-master as well. I can try to run the dev-master in a project next week to see if I can reproduce it to confirm this.

**Comment by jakzal** [comment]
To reproduce this install phpunit 4.8, and run the following test:

```
<?php

use Symfony\Component\Yaml\Yaml;

class FooTest extends \PHPUnit_Framework_TestCase
{
    public function testIt()
    {
        $value = Yaml::parse("foo: bar");

        $this->assertSame(['foo' => 'bar'], $value);
        $this->assertSame(256, Yaml::PARSE_CONSTANT);
    }
}
```

As nicolas-grekas said, this is because phpunit comes with its own version of the Yaml component, which is loaded before the version you use in the project. 

There's not much we can do about it.

**Comment by nicolas-grekas** [comment]
See some more discussions about this at https://github.com/sebastianbergmann/phpunit/pull/2264

**Comment by sebastianlp** [comment]
So... there is any solution to this?

**Comment by javiereguiluz** [comment]
Indeed this is an incredible annoying issue. I wish we could do something ... but I'm not sure is technically possible form our side :(

**Comment by sebastianlp** [comment]
Such a pity :( How can I run my tests without this?

**Comment by javiereguiluz** [comment]
@sebastianlp the solution is to not use the PHPUnit PHAR and instead, do a Composer + require-dev + phpunit/phpunit and execute your tests via `./vendor/bin/phpunit` (or `./bin/phpunit` depending on your Symfony config).

**Comment by nicolas-grekas** [comment]
The even better solution is to require Symfony's php unit bridge and use the simple-phpunit wrapper instead.

**Comment by sebastianlp** [comment]
Thank you @javiereguiluz & @nicolas-grekas!!! Using the bridge it's all OK!

**Comment by pboethig** [comment]
I could solve the problem the following way:
- delete app/bootstrap.php.cache and regenerate it with:

php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php

Thats all. After all you can call phpunit like before....

**Comment by rafa0809** [comment]
Adding more info about this problem. Look at this code:

`
// File tests.bootstrap.php launched before PHPUnit tests
<?php

if ( isset($_ENV[ 'BOOTSTRAP_CLEAR_CACHE_ENV' ]) ) {
    echo '    >Running clear cache & load fixtures: DOING' . PHP_EOL;
    passthru( sprintf(
        'php "bin/console" cache:clear --env=%s --no-warmup --quiet',
        $_ENV[ 'BOOTSTRAP_CLEAR_CACHE_ENV' ]
    ) );
    if ( !$_ENV[ 'SKIP_FIXTURES' ] ) {
        passthru( sprintf(
            'php "bin/console" doctrine:fixtures:load --env=%s --no-interaction --quiet',
            $_ENV[ 'BOOTSTRAP_CLEAR_CACHE_ENV' ]
        ) );
    }
    echo '    >Running clear cache & load fixtures: DONE' . PHP_EOL;
}

require __DIR__ . '/autoload.php';`

When I set SKIP_FIXTURES=false to skip the fixtures, the exception is threw.

**Comment by craigh** [comment]
Any ideas on how to setup PhpStorm to do this with the bridge or some other solution?

**Comment by sstok** [comment]
@craigh Run the simple-phpunit wrapper script once, then configure PHPStorm to use the custom autoloader of the modified phpunit script: something like ./vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/vendor/autoload.php

Notice, whenever you run Composer update/install you will need run the wrapper script again. PHPUnit 6 removed the usage of Yaml completely 👍
