### ISSUE TITLE
[WebProfilerBundle] fetch calls are not shown in ajax toolbar

### ISSUE THREAD

**Issue by ivoba** [symfony/symfony#19547]
When using window.fetch the ajax calls do not appear in the toolbar.

Information about window.fetch:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
https://developers.google.com/web/updates/2015/03/introduction-to-fetch

We encountered this when using https://github.com/github/fetch which will use window.fetch if the browser supports it, which latest FireFox and Chrome do.

If you confirm this a PR could be provided.

**Comment by javiereguiluz** [comment]
@ivoba thanks for reporting this issue. You are right ... but we already had an earlier issue reporting this (#17444), so I'm going to close this as duplicated.

> If you confirm this a PR could be provided.

Yes, please! We confirmed the issue but sadly nobody volunteered to solve it. If you are willing to do it, we'll appreciate it a lot! Thank you.
