### ISSUE TITLE
[WDT] 404 on postLoad Doctrine event with File

### ISSUE THREAD

**Issue by acoquoin** [symfony/symfony#19548]
Hello :)

I have a very simple code which generates a 404 for the WTD (symfony 3.1.1).
I have a postLoad Event from Doctrine, here the code :

```php
class BrochureListener ...
use Symfony\Component\HttpFoundation\File\File;

    public function postLoad(LifecycleEventArgs $args)
    {
        // ....
        $translation->setPdf(new File(sprintf('%s/%s', $this->uploadDirectory, $pdf)));
        // ...
    }
```

My problem is, when i call File, the WDT seems fail and boom : 404 on the WDT.
I dunno if the problem is symfony, my code or Doctrine :/
Any idea ?

**Comment by javiereguiluz** [comment]
@acoquoin in the GitHub repository we only discuss about Symfony bugs and new features. For now, this looks like a Symfony usage question and not a confirmed bug. Please use any of the support alternatives shown in http://symfony.com/support to ask the community about this. If the Symfony bug is confirmed, we'll reopen your issue. Thanks!
