### ISSUE TITLE
[VarDumper] Parse error when dumping stdClass object

### ISSUE THREAD

**Issue by podarcis** [symfony/symfony#19546]
When dumping an object of stdClass, VarDumper shows a parse error.

Minimal example code:
```
<?php
require_once('vendor/autoload.php');

$data = new \stdClass;
$data->foo = 'bar';

dump($data);
```

Error displayed in box:
```
Error: Parse error on line 1:
{#3 ▼  +"foo": "bar"
-^
Expecting 'STRING', '}'
```

PHP-Version: PHP 7.0.4-7ubuntu2.1
VarDumper-Version: 3.1.3 and dev-master

**Comment by nicolas-grekas** [comment]
This error is displayed by one of your browser extension (already reported and confirmed as such).

**Comment by nicolas-grekas** [comment]
See #19471

**Comment by nicolas-grekas** [comment]
Please fill a bug report to the author of the extension...

**Comment by podarcis** [comment]
Oh dear, sry for the noise. The extension seems to be "JSONView". Thanks!
