### ISSUE TITLE
Can't get json() method working

### ISSUE THREAD

**Issue by xurshid29** [symfony/symfony#19553]
Hi,
I'm trying to use a new method `json` from `Contorller` class, and JmsSerialiser bundle also has been installed, but it is giving me the error :  
`Type error: Argument 3 passed to JMS\Serializer\Serializer::serialize() must be an instance of JMS\Serializer\SerializationContext, array given, called in /home/xurshid29/Projects/sl-classic/source/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php on line 117`

Here is a `json` method definition:

```
protected function json($data, $status = 200, $headers = array(), $context = array())
    {
        if ($this->container->has('serializer')) {
            $json = $this->container->get('serializer')->serialize($data, 'json', array_merge(array(
                'json_encode_options' => JsonResponse::DEFAULT_ENCODING_OPTIONS,
            ), $context));

            return new JsonResponse($json, $status, $headers, true);
        }

        return new JsonResponse($data, $status, $headers);
    }
```

And here is a `serialize` method definition from JmsSerializer bundle:

```
public function serialize($data, $format, SerializationContext $context = null)
    {
        if (null === $context) {
            $context = new SerializationContext();
        }

        return $this->serializationVisitors->get($format)
            ->map(function(VisitorInterface $visitor) use ($context, $data, $format) {
                $this->visit($visitor, $context, $visitor->prepare($data), $format);

                return $visitor->getResult();
            })
            ->getOrThrow(new UnsupportedFormatException(sprintf('The format "%s" is not supported for serialization.', $format)))
        ;
    }
```
And as we see, method parameters are different. 

I'm using Symfony v3.1.3

**Comment by sstok** [comment]
The JmsSerializer and the Symfony serializer are not the same.
And the JmsSerializer actually has it's own service name: http://jmsyst.com/bundles/JMSSerializerBundle

**Comment by xurshid29** [comment]
@sstok https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/config/services.xml#L178

**Comment by wouterj** [comment]
Both do not use the same API, so you can't use it like this.

As stated in the line you referenced, the `serializer` alias in the JMSSerializerBundle is here only for backwards compatibility reasons and you should disable the alias in the config and use `jms_serializer` instead.

**Comment by wouterj** [comment]
Anyway, this issue can be closed as it's not related to Symfony core, but to a third party bundle.

**Comment by xurshid29** [comment]
ok
