### ISSUE TITLE
event "kernel.request" not stopped after SF upgrade (2.8.8 to 2.8.9) and (3.1.2 to 3.1.3)

### ISSUE THREAD

**Issue by stephadz** [symfony/symfony#19577]
Hello, 

We use NelmioCorsBundle, and we have a problem with event propagation after sf upgrade.
The issue is also posted on the NelmioCorsBundle Repos with more informations. 
https://github.com/nelmio/NelmioCorsBundle/issues/64

Any ideas?

Thanks in advance.

**Comment by xabbuh** [comment]
The referenced issue was closed as being fixed by #19651. Thus I am closing here too.

@stephadz Please leave a comment if the PR didn't fix your issue and also give some instructions on how to reproduce your issue.
