### ISSUE TITLE
[Form] Translator gives a missing message error for empty string when required option is set to false

### ISSUE THREAD

**Issue by guzzlefry** [symfony/symfony#19571]
Version: 3.1.3

To reproduce:
Create a form with a ChoiceType field with option 'required' set to false. Render in template.

![8hrsnqd](https://cloud.githubusercontent.com/assets/3201334/17498779/67023f0c-5d97-11e6-8d23-26dfe8f95886.png)

**Comment by aitboudad** [comment]
Can you please fork the Symfony Standard Edition and make the changes to reproduce the issue?

**Comment by guzzlefry** [comment]
Well, I can't seem to reproduce this on either the master branch or the v3.1.3 tag. It's likely something odd with my current application.  Closing unless I find a way to reproduce this on a fresh checkout.
