### ISSUE TITLE
[2.7] HTTP Foundation: MongoDB Session Expiration Logic

### ISSUE THREAD

**Issue by chrisgittings** [symfony/symfony#19581]
We are using MongoDB for session management. We explicitly disable PHP garbage collection (as described in the file reference below) via:

```
session.gc_probability: 0
```

We have our own session listener, which is expiring sessions (for non-Admin users) after 30 mins. However, after upgrading to symfony 2.7, the logic in `MongoDbSessionHandler` is invalidating sessions after 24 mins (1440 secs), for any user.

I think this is due to the logic in: https://github.com/symfony/http-foundation/blob/2.7/Session/Storage/Handler/MongoDbSessionHandler.php#L139

which is using `gc_maxlifetime` to set "expires_at". Due to the way sessions are found in `read()` in this class, sessions older than 24 mins are not found, effectively expired, before our own SessionListener logic can run.

My question is, why is a GC-related value being used to define when a session expires? Shouldn't session expiry and session GC be unrelated?

We are able to work around this by setting `session. gc_maxlifetime` to a higher value, but this doesn't feel right, given that GC is disabled.

Would it make sense to provide other ways for finding Mongo sessions, so that either:
- The session expiration logic can optionally ignore `gc_maxlifetime/expires_at` altogether, leaving it to code to handle session expiration, or
- There's an alternative way to specify the max session length, e.g., via a different optional parameter that could still default to `gc_maxlifetime` if not explicitly provided?

**Comment by fabpot** [comment]
Closing as nobody seems to care enough to provide a fix (as I'm not a MongoDB user myself, I have no clue o incentive to work on a fix).
