### ISSUE TITLE
Validation YAML files not loaded from Resources/config/validation folder

### ISSUE THREAD

**Issue by SvetlinStaev** [symfony/symfony#19592]
I upgraded a project from Symfony 2.8 to 3.1 and the validation constraints stopped loading for all bundles when they are defined in the `Resources/config/validation` folder of the bundle.

I checked the `FrameworkExtension` which loads the files and it seems that the `getRealPath` method of the `$file` in the `getValidatorMappingFiles` method is returning empty string rather than the path itself. Is this a problem with the Symfony 3.1 or it might be related to some PHP setting?

I am using `PHP 7.0.9`.

**Comment by xabbuh** [comment]
@SvetlinStaev Does this even happen on a fresh installation of the Symfony Standard Edition?

**Comment by SvetlinStaev** [comment]
@xabbuh I haven't tried it on a fresh installation. Yesterday I reinstalled PHP 7 on my machine and it started working. I assume it must be related to the environment rather than the framework.

**Comment by xabbuh** [comment]
I am closing here for now.

@SvetlinStaev Please comment if you happen to find more details about how to reproduce your issue. Thanks!
