### ISSUE TITLE
[Finder] ExcludeDirectoryFilterIterator does not like trailing slashes

### ISSUE THREAD

**Issue by kassner** [symfony/symfony#19599]
Hi!

With PHPCPD (https://github.com/sebastianbergmann/phpcpd/issues/135) I found out that `ExcludeDirectoryFilterIterator` does not exclude a directory if it is informed with a trailing slash (very common to happen if you're using bash autocomplete).

Looks like just `rtrim($directory, '/')` [here](https://github.com/symfony/symfony/blob/904279e1420e8b31c7b1cde71bf352b9fff70f31/src/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php#L37-L43) will do the trick, but I was not able to assemble a unit test yet.

Any other approach to fix this?

Thanks!

**Comment by ro0NL** [comment]
Can you show whats `$directories` looks like in your case? I think this makes sense :-)

**Comment by kassner** [comment]
@ro0NL 

```
array(10) {
  [0]=>
  string(6) "tests/"
  [1]=>
  string(4) ".svn"
  [2]=>
  string(4) "_svn"
  [3]=>
  string(3) "CVS"
  [4]=>
  string(6) "_darcs"
  [5]=>
  string(12) ".arch-params"
  [6]=>
  string(9) ".monotone"
  [7]=>
  string(4) ".bzr"
  [8]=>
  string(4) ".git"
  [9]=>
  string(3) ".hg"
}
```

**Comment by ro0NL** [comment]
Here's the test https://github.com/symfony/symfony/compare/master...ro0NL:finder/rtrim-excluded-dirs

I can PR this if you want.. but maybe you have something going on already. The class is complex though.. i cant really visualize it how it works in recursive state (ie `::$isRecursive`) as this is untested :-) (ie maybe it's only needed for the `if` part.

**Comment by kassner** [comment]
@ro0NL you can PR it, I'm not that far with my test.
