### ISSUE TITLE
[MonologBridge] Check header size before logging to firephp

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#19590]
Firephp makes debugging harder, in a way that when it crashes you'll need to to investigate that first as in my case i only got `502 Bad Gateway`. Eventually the problem was an undefined variable. Not cool :)

Maybe i can work on a fix later, but for now i'll leave this here for future reference.

```yml
firephp:
    type:   firephp
    level:  info
```

```
172.18.0.1 - - [10/Aug/2016:11:57:22 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
2016/08/10 12:01:35 [error] 6#6: *13 upstream sent too big header while reading response header from upstream, client: 172.18.0.1, server: ~^(?<domain>.+)\.dev$, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "symfony.dev"
```

While actually the problem was
```
 Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: form" at /var/www/html/symfony/src/AppBundle/Controller/DefaultController.php line 19 
```

edit: maybe this should be fixed over at [Seldaek/monolog](https://github.com/Seldaek/monolog)

**Comment by jakzal** [comment]
This is really an issue with your [web server config](https://gist.github.com/magnetikonline/11312172#determine-fastcgi-response-sizes).

**Comment by ro0NL** [comment]
Thx. This is actually [documented](https://github.com/symfony/symfony-standard/blob/master/app/config/config_dev.yml#L25). Crazy.
