### ISSUE TITLE
Cannot add a violation to the correct path if a constraint is applied to the form itself

### ISSUE THREAD

**Issue by AssortedParrot** [symfony/symfony#19598]
I'm using Symfony 2.8.9 with PHP 5.6.10.

The following code will cause the violation to be added at path `data.type` instead of `children[type].data` (like it would happen if the constraint was applied to an individual field). This causes the error message to show up in the wrong place. I need to apply the constraint to the whole form because I have to validate a field depending on the value of another field.

**Form type**
```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type as FormType;
use Symfony\Component\Form\FormBuilderInterface;

use AppBundle\Validator\Constraints as CustomConstraint;

class SettingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('type', FormType\ChoiceType::class, [
            'label'         => 'Type',
            'required'      => true,
            'choices'       => [
                'type1'     => 'Type 1',
                'type2'     => 'Type 2',
                'type3'     => 'Type 3',
            ],
        ]);
        $builder->add('value', FormType\TextType::class, [
            'label'         => 'Value',
            'required'      => true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'constraints' => [
                new CustomConstraint\ValidSetting(),
            ],
        ]);
    }
}
```

**ValidSettingValidator**
```php
<?php

namespace AppBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class ValidSettingValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        $type = $value['type']);
        $value = $value['value']);

        if ($type === 'type1')
        {
            $errorOccurred = true; // Add validation logic here
            if ($errorOccurred)
            {
                $this->context->buildViolation($constraint->message)->atPath('type')->addViolation();
            }
        }
    }
}
```

This bug can be worked around using `error_mapping` in the `SettingType`. For some reason, mapping `type` to itself seems to work.

```php
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'constraints' => [
                new CustomConstraint\ValidSetting(),
            ],
            'error_mapping' => ['type' => 'type'],
        ]);
    }
```

Am I using this wrong or is this a bug?

**Comment by HeahDude** [comment]
You should try `$this->context->buildViolation($constraint->message)->atPath('[type]')->addViolation();`

**Comment by javiereguiluz** [comment]
@AssortedParrot did @HeahDude's comment solve your issue?

**Comment by jakzal** [comment]
Closing due to lack of feedback. We'll reopen if there's any more information provided.

**Comment by AssortedParrot** [comment]
Sorry for the late response. Yes, @HeahDude's solution worked for me. However, [the docs on creating a custom validation constraint](http://symfony.com/doc/current/validation/custom_constraint.html) don't mention this at all. If I understand this correctly, this is because the example in the docs validates an object, while it's an array in my example. It's clear after you find out that internally the PropertyAccess component is used, so perhaps this should be mentioned in the docs?

**Comment by xabbuh** [comment]
@AssortedParrot Can you please open an issue in the docs repository if you feel that we can improve them at some point?

**Comment by cataragak90** [comment]
hello!
what if I want to add a violation to a field of subform, something like: form.subform.field ?

**Comment by julestruong** [comment]
anyone found a solution @cataragak90  ?

**Comment by videni** [comment]
I am also interested in @cataragak90 ' s question

**Comment by cataragak90** [comment]
> I am also interested in @cataragak90 ' s question

I don't really remember, I think I did it like that:
```
                $this->context
                    ->buildViolation($message)
                    ->atPath('')
                    ->atPath($propretyName)
                    ->addViolation();
```
and the $propretyName = the name of the field in the html form, it's created by default: "formName_subform_field"

**Comment by videni** [comment]
@cataragak90 , thank for you share, however it most likely won't work. this approach may be not correct, I ask a question [here](https://stackoverflow.com/questions/56334452/how-to-map-violation-to-symfony-form-manually/56338976#56338976). that answer is more reasonable.

**Comment by isopen** [comment]
https://symfony.com/doc/current/reference/forms/types/form.html#error-bubbling = false

**Comment by muhiddingithub** [comment]
If field type is HiddenType error_bubbling will be default true, that why error_bubbling should set manually false
