### ISSUE TITLE
MicroKernelTrait is having old directory structure

### ISSUE THREAD

**Issue by cadavre** [symfony/symfony#19593]
For Symfony >3.0 we have default directory structure as declared in:
https://symfony.com/doc/current/configuration/override_dir_structure.html

But when using `MicroKernelTrait` the directory structure is as in old Symfony <3.0 and also as described in documentation:
https://symfony.com/doc/current/configuration/micro_kernel_trait.html

My suggestion is to unify directory structure for framework and `MicroKernelTrait` for Symfony >3.0.

EDIT: To whom doesn't want to look closely: directories `logs/` and `cache/` are not placed in `var/` as they should, they're placed in `app/` instead.

PS I know I can workaround this with overriding `getCacheDir()` and `getLogDir()` but it's not a solution.

**Comment by wouterj** [comment]
> PS I know I can workaround this with overriding getCacheDir() and getLogDir() but it's not a solution.

Are you aware that this is exactly what is done in the Standard Edition in Symfony 3? https://github.com/symfony/symfony-standard/blob/master/app/AppKernel.php#L36-L44

One of the big things in Symfony is that it doesn't enforce any directory structure. Use whatever structure you're comfortable with, especially when using the micro kernel trait.

**Comment by jakzal** [comment]
> I know I can workaround this with overriding getCacheDir() and getLogDir() but it's not a solution.

This is not a workaround, but precisely the thing you should do. We cannot change implementations of these methods in Symfony as it would be a BC break.

**Comment by ro0NL** [comment]
Eventually it's a documentation issue. Ie. we could add the `get*Dir` methods to the example code, or explain it's left out (probably) for readability (hence the different directory structure).

**Comment by fabpot** [comment]
I agree with @ro0NL that this is a doc issue. @cadavre Can you open an issue on symfony/symfony-docs and close this one? Thanks.

**Comment by cadavre** [comment]
Thanks for answers! All make sense, I'll issue docs repo.
