### ISSUE TITLE
[VarDumper] HtmlDumper+WDT broken in master?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#19609]
@nicolas-grekas, https://github.com/symfony/symfony/commit/998ff33e8931a0ed10ffc54a5135f9ba91093a29 breaks the WDT toolbar in master on chrome 52.0.2743.116 (the request is never finished, calling it directly works ok though), but it's a client issue i guess.

It's a bit weird, these [2 lines](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L292,L293) make the loop explode, making it run forever when requested with xhr.

I just did a simple `dump(array(1))` in the default controller.

**Comment by nicolas-grekas** [comment]
Please report the error on chrome, there is nothing wrong on our side...

**Comment by ro0NL** [comment]
No error... tab just freezes and needs to be force quit. However here some specs;

- https://github.com/ro0NL/symfony-standard/commits/issue/19609
- Add `console.log('entering for');` right [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L278) (above `for (i = 0; i < len; ++i) {`)
- Visit `/app_dev.php/` (for me private mode in chrome 52.0.2743.116 (64-bit) on ubunutu 14.04)

![image](https://cloud.githubusercontent.com/assets/1047696/17647771/50d496d6-6200-11e6-95b8-bf1490771188.png)
and counting.

HTTP traffic seems ok now, (symfony-standard 3.2), when i test with symfony-standard 3.1.* with symfony/symfony 3.2 i get
![image](https://cloud.githubusercontent.com/assets/1047696/17647817/befc22d6-6201-11e6-8202-e7468b5203c7.png)

**Comment by jameshalsall** [comment]
@nicolas-grekas I am seeing the same issue on `dev-master` too.

**Comment by nicolas-grekas** [comment]
On Firefox also?

**Comment by jameshalsall** [comment]
Yes, Firefox (41) and Safari (9.1) also have the same issue.

The `Sfdump` function defined in `HtmlDumper` is being called continuously, which ends up killing the tab in the browser.

**Comment by ro0NL** [comment]
Firefox 48

![image](https://cloud.githubusercontent.com/assets/1047696/17657057/93657a72-62c0-11e6-9695-5c3c9a588a2f.png)

**Comment by nicolas-grekas** [comment]
@ro0NL could you please check if #19803 fixed the issue?

**Comment by jakzal** [comment]
ping @ro0NL

**Comment by ro0NL** [comment]
Sorry, i was away due holiday and stuff. Ill test it out this week(end).

**Comment by ro0NL** [comment]
@nicolas-grekas fixed!

16c5c76 broken, 03a824a ok!
