### ISSUE TITLE
Sample JS code for collections may submit two entries with the same name

### ISSUE THREAD

**Issue by AssortedParrot** [symfony/symfony#19603]
The documentation chapter [How to Embed a Collection of Forms](http://symfony.com/doc/current/form/form_collections.html) contains [sample code](http://symfony.com/doc/current/form/form_collections.html#allowing-new-tags-with-the-prototype) to demonstrate how to add the possibility for users to create additional entries in the collection.

The problem is with this piece of code:

```javascript
    // count the current form inputs we have (e.g. 2), use that as the new
    // index when inserting a new item (e.g. 2)
    $collectionHolder.data('index', $collectionHolder.find(':input').length);
```

This assumes that the entries are numbered continuously, starting with 0. However, this may not be the case if the form was already submitted, but contained errors. Consider this scenario:

1. Click the "add" button twice to add two entries, with indices `0` and `1`.
2. Click the "remove" button on the first entry, leaving only entry `1`.
3. Add some error to the form to cause validation to fail, then submit the form.
4. The existing entry still has index `1`. However, (assuming each entry contains exactly one `<input>` field), `$collectionHolder.find(':input').length` will be `1` (because there's exactly one entry).
5. If you click the "add" button again, it will thus add a new entry with index `1`. This will override the first entry, which is certainly not what the user would expect.

This can be worked around by [customizing the prototype](http://symfony.com/doc/current/form/form_customization.html#form-custom-prototype) to add a `data-index` attribute to each entry's widget, set to `form.vars.name`. The code would then have to loop through all entries to determine the maximum index, and set the current index to the maximum index plus 1.

```javascript
    var index = 0;
    $('.collection_entry').each(function () {
        if ($(this).data('index') >= index) {
            index = $(this).data('index') + 1;
        }
    });
    $collectionHolder.data('index', index);
```

If you can ensure that all new entries are added at the end of the collection (i.e. the indices are strictly increasing), you can avoid the loop by using the `index` of the last entry:

```javascript
    var index = 0;
    var $entries = $('.collection_entry');
    if ($entries.length > 0) {
        index = $entries.last().data('index') + 1;
    }
```

**Comment by webjobs** [comment]
I spotted same problem long time ago. To solve it, I had to figure how S2 works internally with keys; in short, newly added collection elements can have **any** key, they don't have to be in order.

For example, you could have keys like **0, 1, 10, my_key_15000** and so on. 

When form is generated for the first time, your collection will have ordered keys like 0, 1, 2... On submission, if any of the keys are missing (i.e. you remove element from collection), Symfony will check differences in key names and call add/remove  methods correctly.

To avoid counting, I used different approach. Check this code I used for AngularJS collections:

```javascript
    this.createKey = function () {
        if ( !$scope.nextKey ) {
            var now = performance.now();
            $scope.nextKey = Math.floor(now);
        }

        $scope.nextKey ++;

        return $scope.nextKey;
    };
```

Everytime I need to add element to collection, I call this method. On first invocation key would be f.e. 500 and it will **always** increase by one on each call. So if you delete first element, a submission to server would have keys like **1, 2, 500, 501**.

This solution works for SPA. For full-page refresh, you can use Date object in similar way.

Hope this helps as an idea.

**Comment by javiereguiluz** [comment]
@AssortedParrot thanks for reporting this issue and thanks @ftl-sw for explaining a possible solution. This looks like a docs issue, so I've moved this to https://github.com/symfony/symfony-docs/issues/6924 and we can close this issue then.

**Comment by Mondane** [comment]
I've just looked at wat `performance.now()` returns:

> The performance.now() method returns a DOMHighResTimeStamp, measured in milliseconds, accurate to five thousandths of a millisecond (5 microseconds).
>
> The returned value represents the time elapsed since the time origin (the PerformanceTiming.navigationStart property). In a web worker, the time origin is the time that its execution context (e.g. thread or process) is created. In a window, it is the time that the user navigated (or confirmed navigation, if confirmation was needed) to the current document. Bear in mind the following points:

Taken from https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

In my opinion this means the same index can still occur because the time is measured from page load.

I've resolved the index problem with a new approach by adding a bit to the collection holder in my twig template:

For the documentation on http://symfony.com/doc/current/form/form_collections.html , one could add this tag attribute:

```twig
data-index="{{ form.tags|length > 0 ? form.tags|keys|sort|last + 1 : 0 }}"
```

If there are tags, the tag with the highest index is found and that index + 1 is added as value for data-index, otherwise, 0 is used.
