### ISSUE TITLE
[Routing] build query string with PHP_QUERY_RFC3986

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#19625]
[UrlGenerator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L269) doesn't use [`http_build_query`](http://php.net/manual/en/function.http-build-query.php) fourth parameter, thus encoding spaces as `+` because of the *application/x-www-form-urlencoded* media type.

As route extra parameters aren't used in a form context I think `PHP_QUERY_RFC3986` should be used.

[Twig does that already](http://twig.sensiolabs.org/doc/filters/url_encode.html).

**Comment by Tobion** [comment]
:+1:
