### ISSUE TITLE
Introduce Symfony\Component\Workflow\TransitionInterface ?

### ISSUE THREAD

**Issue by RoSk0** [symfony/symfony#19621]
I have integrated Workflow component into Drupal 7 website and because of custom config storage it will be really useful for me to have an ability to use my own class as Transition class to have some custom properties and methods.
I think that it wouldn't be too complicated to introduce Symfony\Component\Workflow\TransitionInterface but I see one thing that I have no idea how to handle. In Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:393 registerWorkflowConfiguration() method is directly referencing Workflow\Transition::class to add transition to workflow definition. Should it be made configurable somehow? Does it make sense to introduce this interface at all ?

**Comment by ro0NL** [comment]
Cant you couple custom logic by transition name, and hook in using events? Ie. why do you need a custom class? From the workflow pov it's just a simple VO.

**Comment by lyrixx** [comment]
Hello @RoSk0 

I usually don't like to add interface on simple POP / value object.

Then If you store your "workflow schema" outside the config.yml (or something similar in drupal), you have to create everything by hand. It's really easy. So IMHO, there is no need for the TransitionInterface

**Comment by RoSk0** [comment]
Thanks for replies @lyrixx and @ro0NL .
What about such essential properties like 'label' that should be shown to the user? Where how those should be stored? Having label as part of immutable value object looks perfectly legit to me.

**Comment by lyrixx** [comment]
@RoSk0 you can simply extend the Transition class ?! or Store more information anywhere in a map.

**Comment by lyrixx** [comment]
I'm closing this issue as there is not activity anymore. More over I gave some solutions.
Feel free to reopen the issue if it was not clear enough.
