### ISSUE TITLE
EntityType should have option to have setter / add method called

### ISSUE THREAD

**Issue by novoss** [symfony/symfony#19622]
Here's my situation: A `Parent` entity has a `OneToMany` relationship with some `Child` entities. The form for `Parent` has an `EntityType` field, with options `['class'=>Child::class, 'multiple'=>true, 'expanded'=>true]`.

When calling `$form->handleRequest($request)`, I expected `Parent->addChild()` to be called, like it is with `CollectionType` if the `by_reference` option is set to `false`.

It seems `EntityType` doesn't have this option, meaning there's no way to have `Parent->addChild()` called when Children are added.

Is this correct?

I think it would be handy to add an option for this. I'd be happy to have a crack at adding it if people agree with me.

I'm using `Symfony 3.1.3`.

**Comment by jxmallett** [comment]
I've gotten around this for the moment by adding a `POST_SUBMIT` form `EventListener`.

^ @novoss and I are the same person. Work account...

**Comment by rparsi** [comment]
@novoss It's as you think, `EntityType` does not have the `by_reference` option

**Comment by HeahDude** [comment]
`EntityType` __do have__ `by_reference` option.

**Comment by rparsi** [comment]
Doesn't say so in the docs, under inherited options

**Comment by HeahDude** [comment]
There are many things the doc does not say :)

But `EntityType` extends `DoctrineType` which inherits `ChoiceType` which extends `AbstractType` which inherits `FormType` which has the option...

("extends" => php, "inherits" => `$formType->getParent()`)

**Comment by stof** [comment]
@rparsi then open an issue on the doc repository to ask them to fix the doc.

**Comment by jxmallett** [comment]
Thanks for the info @HeahDude. I'll have to check if setting `by_reference=false` actually has the desired result (it certainly should).

On a semi-related note, the docs could be phrased better. They say `by_reference` defaults to `true` (which it does) but they also say:

> Setting `by_reference` ensures that the setter is called in all cases

They should probably say:

> Setting `by_reference=false` ensures that the setter is called in all cases

**Comment by jxmallett** [comment]
I created a pull request for the `by_reference=false` thing.

https://github.com/symfony/symfony-docs/pull/6923

**Comment by HeahDude** [comment]
Let's close then :)

**Comment by javiereguiluz** [comment]
Closing this as *"it will be fixed in the docs"*.
