### ISSUE TITLE
How to find a Github project (website) made with Symfony (I want to look at good example as a pattern to refactoring my project)

### ISSUE THREAD

**Issue by sruj** [symfony/symfony#19626]
I just want to look at ONE, well done, website made with Symfony as a pattern to refactoring my project.

(other than https://github.com/symfony/symfony-demo - it's just too small)

If this is not a proper place to ask about that please suggest me better place before you remove this question.

**Comment by ro0NL** [comment]
> website made with Symfony as a pattern to refactoring my project

Well, basically in its core, that is the demo/standard edition. As it shows you all/most common symfony patterns on a lowest level. Or see http://symfony.com/doc/current/best_practices/index.html if you want.

So unless you're not specific about what you want to refactor.. this is really hard to answer, but maybe you can look up one of these guys on github; https://symfony.com/showcase/

I always tend to google "X best practices" vs. "X bad practices", that kind of stuff.

**Comment by sruj** [comment]
ok, thanks, 

(I will remove this post tomorrow.)

**Comment by fabpot** [comment]
Closing as you should use the proper support channels as mentioned by @ro0NL
