### ISSUE TITLE
[Cache][BUG][PHP 7.1]Always set default lifetime

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#19641]
Looking at cache.xml, there is a parameter/argument named `default lifetime`.
It seems that this is not set as the container contains `''` as a value for a parameter that's clearly supposed to be an integer.
This is a problem in php 7.1 as `''` is not a valid integer and thus php emits a warning `Warning: A non-numeric value encountered`

This can be clearly seen when running app/console cache:clear on php 7.1

**Comment by jameshalsall** [comment]
I'm not seeing this on a default symfony standard install. Can you provide your config?

**Comment by mvrhov** [comment]
Just checkout the master of symfony standard run composer update and then `bin/console cache:clear`

**Comment by nicolas-grekas** [comment]
See #19650
