### ISSUE TITLE
Profiler storage lifetime

### ISSUE THREAD

**Issue by arodiss** [symfony/symfony#19658]
According to [3.0 documentation](http://symfony.com/doc/3.0/reference/configuration/framework.html#lifetime), `profiler` configuration can specify `lifetime`
However, in [code for 3.0.9](https://github.com/symfony/framework-bundle/blob/v3.0.9/DependencyInjection/Configuration.php#L194) I see no such node.

Thus, attempt to use it in my application triggers `Unrecognized option "lifetime" under "framework.profiler"`

Either documnetation or ode should be updated.

PS. Did not check this, but seems like `3.1.x` should be affected as well

**Comment by stof** [comment]
This should be reported to the documentation issue tracker. This config setting was removed in 3.0, but it looks like it was not removed from the doc.

**Comment by arodiss** [comment]
@stof 
Thank you for clarification.
Created https://github.com/symfony/symfony-docs/issues/6889

**Comment by arirangz** [comment]
Is there a way to limit the profiler storage?
Setting a lifetime or a profile limit? I can't find anything in the documentation or in the code itself.

My var/cache/profiler/ folder is getting huge not clearing previous profiles.

Thanks!

**Comment by fabpot** [comment]
As this is a dev tool, there is nothing like that, just clear the cache.

**Comment by arirangz** [comment]
Hi Fabpot,

Thanks for your answer.

I understand that as a dev tool options are limited but still it's annoying to have the profiler folder taking 40go after few days without clearing the cache.

Is there a way to use the dev bar but without storing previous profiles, only the current one?

**Comment by NothingWeAre** [comment]
As I have limited storage in my dev VM, and constantly cleariong cache is bothersome, I have been searching for automated solution.
After some experiments I managed to create cron job that works for me.
Dont know if someone will find it, but I will leave it here anyway.

`* * * * * root cd /var/www/trol/src/var/cache/dev/profiler && sed -i ':a;$q;N;101,$D;ba' ./index.csv && ls -1t | tail -n +102 | xargs rm -rf`
where: 
`sed -i ':a;$q;N;101,$D;ba' ./index.csv` removes all lines in `index.csv`, except last 100. (new dumps are stored last)
`ls -1t | tail -n +102 | xargs rm -rf` removes all folders and files except newest 100. 

Hope this helps someone.
