### ISSUE TITLE
[HttpKernel] Support querystring in action arguments

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#19655]
One feature I'm often missing, is the ability to fetch query parameters directly from the method arguments. With the refactoring I've made it easier to add functionality, I was thinking to use this if the feature would be decided.

**Current scenario**

``` php
class FooController
{
    /**
      * Calling "/foo?bar=baz"
      * @Route("/foo")
      */
    public function fooAction(Request $request)
    {
        return new Response(sprintf('Your query was %s.', $request->query->get('bar')));
    }
}
```

**Proposed scenario**

``` php
class FooController
{
    /**
      * Calling "/foo?bar=baz"
      * @Route("/foo")
      */
    public function fooAction(Request $request, $bar)
    {
        return new Response(sprintf('Your query was %s.', $bar'));
    }
}
```

This should also support arrays and optional values for example:

``` php
class FooController
{
    /**
      * Calling "/foo?bar[]=baz&bar[]=hello-world"
      * @Route("/foo")
      */
    public function fooAction(Request $request, array $bar = [])
    {
        // ...
    }
}
```

Would this be something I can add to the core? If not I can add it to my own bundle for people that do need it.

**Comment by HeahDude** [comment]
There is already http://symfony.com/doc/master/bundles/FOSRestBundle/annotations-reference.html, wouldn't an argument value resolver mess with it?

**Comment by iltar** [comment]
The other solution would be to add the parameters in Symfony elsewhere, meaning they end up in the attributes. This would make it possible to create a parameter converter for `?post=1` where the 1 gets converted into a Post object.

**Comment by fabpot** [comment]
It has been rejected in the past. Being able to get the value of routing parameters is ok (`/:foo`), but being able to get anything passed by the user is a no-go in terms of security.

**Comment by iltar** [comment]
But wouldn't it be the exact same thing as reading the request query manually? It would merely be a shortcut. I could also add bogus info there or in the route Paramus, wouldn't make a difference as far as I can tell. I could even make a parameter converter that already does this so I fail to see which security issues this would raise.

**Comment by ro0NL** [comment]
@iltar you're right, it's the same when reading _manually_. However, that's the risk in terms of security, we just should not advertise with "add a method argument, and it's automagically populated by the user" (whereas route arguments are controlled by the developer). Eventually we create a backdoor entrance, the risk of writing "bad" code that is.

**Comment by iltar** [comment]
In that case, would it be an idea to white-list query string parameters in the route config?

**Comment by ro0NL** [comment]
Could work. Not sure how intuitive that is, not everybody uses annotations/comments to clarify.

Personally i was thinking more along the lines of;
`public function someAction(Request $request, Param $bar)`

Think `$bar->isQuery()`, `$bar->isGiven()`, etc.

If we go this way, we need a whitelist. Period :)

**Comment by Koc** [comment]
Ref #3254

**Comment by iltar** [comment]
Closed at it will most likely not be fixed

**Comment by bohdanyurov-gl** [comment]
@fabpot I am still curious about whitelisting GET query parameters. Shouldn't it resolve your security concerns?
