### ISSUE TITLE
Descriptive config error message don't show up

### ISSUE THREAD

**Issue by bjcullinan** [symfony/symfony#19652]
Please explain to me the purpose of MainConfiguration.php.  A perfect example of my issue is right here: https://github.com/symfony/symfony/commit/04508658b52274dfd7a6d7502d565c764e569e5d#diff-b17a1d8367613749bf70e5c1fa67235e

When a configuration setting changes names for no apparent reason, there are specific parts of that code that indicate the change such as the lines: The "intention" option for the '.__CLASS__.' is deprecated since version 2.8 and will be removed in 3.0. Use the "csrf_token_id" option instead.

That sounds EXTREMELY helpful to know, too bad the code never hits that point.  This message is in MainConfiguration.php:  "You should define a value for only one of 'intention' and 'csrf_token_id' on a security firewall. Use 'csrf_token_id' as this replaces 'intention'."

Again the code NEVER executes that either, because that message would have been SO so helpful after a long day of upgrade other people's public libraries.

Please explain to me why when I run this command:
php app/console cache:clear --env=dev;

                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "intention" under "security.firewalls.main.form_login"      
                                                                                 
Why don't those helpful message show up, instead of this generic message?  What am I missing.  You must have put the check in the wrong place.  Is there an "--ignore-errors" option that I am missing and if I had used that it would show the other more descriptive messages?  The form_login section doesn't even exist in MainConfiguration.

Everyone who has ever used that setting already knows the name "intention", so why change it?  Don't get me wrong, I make unnecessary changes to code all the time and it usually comes around to bite me, but I am the only one reading my code.  There are at least 1,000 people using your code so changes should stay at a minimum.  More importantly, why don't the descriptive messages show up when the configurator runs?

**Comment by iltar** [comment]
The error you've described is triggered in the listener, that means that the wrong options have been configured. However the configuration is validated and throws the exception because something is wrong. Configuration is compiled and the compiler passes/extensions configure the listener. So this error is not triggered because the configured already catches it.

The option "identity" is not mentioned anywhere in that PR though so I don't see how this is related. If I check the config in 3.1 (I don't remember this option existing in 2.8) I get the following output:

```bash
$ bin/console config:dump SecurityBundle | grep identity
            object_identity:      acl_object_identities
            object_identity_ancestors:  acl_object_identity_ancestors
            security_identity:    acl_security_identities
            allow_if_object_identity_unavailable:  true**
```

So what I think is the problem is this:

```yml
security:
    firewalls:
        main:
            form_login:
                identity: ~ # this is invalid and is the one causing your exception
```

**Comment by bjcullinan** [comment]
Thank you, sorry I typed the word identity, but I meant intention.  I figured that out eventually, but what I am really wondering is how do we get those messages to describe the error instead?  I don't understand why MainConfiguration 2.8 has a bunch of helpful error message, but they are under the 'logout' section, is that in the wrong place?  Is MainConfiguration incomplete in the 2.8 branch?  Check out this page because this is the version I am working with and find **intention**: https://github.com/symfony/symfony/commit/743e670f4acbcb5863fd0248c97bd25050f3f44f

If I was still using the 'intention' setting, why didn't I get the message from MainConfiguration: "Setting the 'intention' configuration key on a security firewall is deprecated since version 2.8 and will be removed in 3.0. Use the 'csrf_token_id' key instead."?
What is the point of having all these warnings about the Deprecation if they never showed up on the console?
There is a basic misunderstanding of principal here.  Configuration files are declarative, that means like a George Forman, SET IT AND FORGET IT!  POINT RELEASE, upgrading from 2.7 to 2.8 labeled as LONG TERM SUPPORT, should not break someone's configuration.
I am not asking for justification, I am just asking if there is a bug in that version of MainConfiguration that could have saved me some time and if those messages in the future can be put in the most helpful place because it reads like it is meant to prevent this from being confusing.

**Comment by iltar** [comment]
So what's the actual issue then? I don't quite get it.. Was the feature removed in 2.8 (while it shouldn't have been) after you upgraded from 2.7 to 2.8?

**Comment by bjcullinan** [comment]
NEWS FLASH!  AddOptions needs to include old and new configuration names in order to fall through to more descriptive error messages.
https://github.com/symfony/symfony/pull/19662

**Comment by jameshalsall** [comment]
Looks like you have upgraded from 2.x to 3.x, read the upgrade guide (https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) and it clearly states that the `intention` configuration option was changed to `csrf_token_id`
