### ISSUE TITLE
Is it possible to show a relationship in options?

### ISSUE THREAD

**Issue by rquadling** [symfony/symfony#19654]
Hi.

I'm wondering if it is possible to use the Symfony/Console component to build a set of options that satisfy this command line help.

script command [--limit=n] [[--target=n [--reverse-order]] | [--date = ccyyddmm ]]

So only a `--target` can be in `--reverse-order`, but both `--target` and `--date` can have `--limit`.

I know I can implement the internal validation logic, but it would be nice to be able to show this to the user in a consistent way - by that I mean I just describe the relationship of the options, the component correctly displays that information and validates the options to see if they obey the rules I've defined.

**Comment by jakzal** [comment]
@rquadling Marking this as a feature request as this is currently not possible. Not sure if anyone's willing to work on this (and if the solution would be simple enough, with no BC breaks, to be accepted)

**Comment by a-ast** [comment]
@jakzal , @rquadling , what do you think about an approach with option groups like this
```php
class TestOptionRelatedCommand extends OptionRelatedCommand
{
    protected function configure()
    {
        $this
            ->setName('test:command:option-related')
            ->addOption('limit', null, InputOption::VALUE_REQUIRED)
            ->addOptionGroup()
                ->addOptionGroup()
                    ->addOption('target', null, InputOption::VALUE_REQUIRED)
                    ->addOption('reverse-order', null, InputOption::VALUE_REQUIRED)
                ->addOption('date', null, InputOption::VALUE_REQUIRED)
        ;
    }
}
```

The idea is to introduce new class (`OptionRelatedCommand`) inherited from `Command`. Besides this, it will require to override `Input` class to implement more sophisticated validation and also `InputDefinition`.

Does it make sense?

**Comment by rquadling** [comment]
Structurally, that looks right. I can easily understand the syntax.

OOI, the `reverse-order` option is `InputOption:VALUE_NONE` (in my example).

Would it be necessary to have a new command class? That suggests input processing is done in the command class. Maybe a better option would be to have an `InputProcessor` that returns an object obeying `InputInterface`.

**Comment by chalasr** [comment]
I don't think a dedicated Command class is a good solution neither.
Closing as this is 2 years old and nobody proposed a concrete implementation. 
Please feel free to reopen if you have one in mind.
