### ISSUE TITLE
Allegedly transparent changes are being made to MainConfiguration that are not transparent

### ISSUE THREAD

**Issue by bjcullinan** [symfony/symfony#19661]
Steps to reproduce error:
1) Setup symfony 2.8
2) Use the configuration setting security: firewals: main: form_login: intention:
3) Observe that **none** of the error messages intended to help correct the deprecated setting show up, only the generic error is reported, negating the utility of the 20 lines committed to fix this setting.

```
if (isset($options['intention'])) {
            if (isset($options['csrf_token_id'])) {
                throw new \InvalidArgumentException(sprintf('You should only define an option for one of "intention" or "csrf_token_id" for the "%s". Use the "csrf_token_id" as it replaces "intention".', __CLASS__));
            }
            @trigger_error('The "intention" option for the '.__CLASS__.' is deprecated since version 2.8 and will be removed in 3.0. Use the "csrf_token_id" option instead.', E_USER_DEPRECATED);
            $options['csrf_token_id'] = $options['intention'];
        }
```

Lines 51 through 60 in UsernamePasswordFormAuthenticationListener.php are intended to notify the change of config property names but the code never reaches this point of execution because the property fails during the configuration build process:
https://github.com/symfony/symfony/blob/04508658b52274dfd7a6d7502d565c764e569e5d/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php#L51

Additionally, MainConfiguration is intended to report configuration errors related to the csrf_token_id property, but it does not:
https://github.com/symfony/symfony/commit/743e670f4acbcb5863fd0248c97bd25050f3f44f

When clearing the cache, only the generic error message is reported, probably because the configuration checks are in the wrong place in the hierarchy under the function addFirewallsSection():
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]

Unrecognized option "identity" under "security.firewalls.main.form_login"

```

To make matters worse, contributors believe that changes are "transparent" when they are not.  And the utility of MainConfiguration error checking is diminished by not reporting the intended correction on the command line.  This is a systemic issue because there are 20 extra committed lines of unnecessary code that do not support their own purpose, either the lines in UsernamePasswordFormAuthenticationListener should be reached because MainConfiguration does not care about the superfluous setting, or MainConfiguration should work as designed and report errors with config, including using the console interface.

**Comment by iltar** [comment]
Regardless of whether or not you agree with this change, these lines of code are necessary for the component. People can use the component without the framework so those "unnecessary" lines of code are most certainly necessary. 

Which symfony version are you using? Because you shouldn't be getting this error in 2.8 afaik.

**Comment by sstok** [comment]
Related to #19652 (I would even consider this a duplicate as the same issue discussed).

**Comment by stof** [comment]
your error message talks about an unrecognized ``identity`` setting, which has nothing to do with the renaming of ``intention`` to ``csrf_token_id``

**Comment by bjcullinan** [comment]
As I already discussed I mistakenly used the word identity because on
CSRFToken($id, $value) is designated even though it use to be called
intention.  So MainConfiguration is not used when using the component as a
standalone? Then why doesn't MainConfiguration call some
ConfigurableInterface within each module so you only have to check the
$options variable once?  Your literally avoiding abstracting error checking
by forcing a developer to include error check within the module and then
those same error checks withing MainConfiguration.  Both of those
activities should point to the same list of options.  Superfluous code is
just as detrimental to software as real bugs are because it burdens me and
Mr Jakzal to locate two separate places where options are being checked for
errors.

**Comment by bjcullinan** [comment]
And it is a burden because Mr iltar and Mr nicolas had to come along and
make the commit to MainConfiguration. If this was all I one place Mr Jakzal
would have been able to fix it himself originally.

**Comment by bjcullinan** [comment]
Fuck you stof, Open Code of Conduct is deprecated.  "Update: We will not be continuing work on the open code of conduct. See our followup post for more information."

**Comment by iltar** [comment]
It seems like you just came here to rage. Nobody is forcing you to use Symfony so stop acting like a 10 year old.

**Comment by bjcullinan** [comment]
Agreed, 100%.  Fix it, or don't.  I don't care anymore because no one here has the ability to look past "tone of voice" and actually spend 5 minutes acknowledging the problem.  Open source sucks because people make commits without writing tests and checking other people's work.  Case in point.  I tried to check someone's work and got zero helpful feedback.  There's no place in this community for me and I hope the rest of you wise up because it turns to shit like Drupal.

@stof 

```
php app/console cache:clear --env=dev;

                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "intention" under "security.firewalls.main.form_login"     
                                                                                 

```

**Comment by iltar** [comment]
I actually tried to help you despite your tone. You should understand a few points here:
 - Shouting at people and saying things like "fuck you" will not get you anywhere
 - You still haven't told me which symfony version you are using and how this issue suddenly arises
 - If this was really a problem, I would've seen more issues about it and I didn't
 - Feel free to add a test-case to cover your "bug" and see if it can be fixed
 - You think bugs only occur in open-source software?
 - Btw, there's a ton of tests and a ton of reviews. Before blaming things, do some research.

All deprecations in 2.7 and 2.8 are following the backwards compatibility promise: https://symfony.com/doc/current/contributing/code/bc.html and those BC layers have been removed in 3.0. Again, do some research before blaming and getting angry about something you don't understand.

Please, grab some tea, sit back and take a deep breath before trying again.

**Comment by ro0NL** [comment]
As i understand correctly, we have a pretty big BC issue right now..we get an exception instead of a (expected) deprecation notice...

**Comment by ro0NL** [comment]
Problem found i guess;

`form_login.intention` is not deprecated from 2.7 to 2.8 (perhaps other factories are affected as well), compare;

- 2.7: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php#L32
- 2.8: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php#L32

**Comment by bjcullinan** [comment]
https://github.com/symfony/symfony/pull/19662
