### ISSUE TITLE
Fix the calendar exception to handle null

### ISSUE THREAD

**Issue by wakqasahmed** [symfony/symfony#19688]
Fix the calendar exception to handle null, error was raised while exporting from akeneo

The Symfony\Component\Intl\DateFormatter\IntlDateFormatter::__construct() method's argument $calendar value NULL behavior is not implemented. Only the GREGORIAN calendar is supported. Please install the "intl" extension for full localization capabilities.

<img width="1279" alt="81f951cc-57e0-11e6-9f6f-e231bbf00bf4" src="https://cloud.githubusercontent.com/assets/4486133/17835155/fe1c16a2-676e-11e6-94d0-2fc408ab53c9.png">

**Comment by sstok** [comment]
You only mention a problem, but not how to solve it 😄 

Are you suggesting to default to the `GREGORIAN` calender when NULL is passed?

**Comment by ro0NL** [comment]
[This](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php#L154) conflicts with https://secure.php.net/manual/en/intldateformatter.setcalendar.php

> default is IntlDateFormatter::GREGORIAN, which is also used if NULL is specified

So normalizing here makes sense.. (lets dont rely on PHP constructors and nulls). Not sure why we limit to GREGORIAN only (let PHP try to decide it?).. could be there for a reason :)

**Comment by wakqasahmed** [comment]
I have submitted a pull request for the fix. The fix is as simple as locale (e.g. default: "en")

https://github.com/symfony/symfony/pull/19691
