### ISSUE TITLE
[HttpFoundation] Authorization header not available via headers()

### ISSUE THREAD

**Issue by andig** [symfony/symfony#19693]
I'm using Apache 2.4 and php 7.0 configured as module and HttpFoundation 3.0.9. I've read https://github.com/symfony/symfony-docs/pull/2529/files#r3886789 and added the RewriteRule although not running PHP through CGI.

When calling app with a `Authorization: Bearer ....` header, it's not available via `headers()`. It is however visible via `apache_request_headers()`. 

Why isn't Symfony picking up the apache header?

**Comment by ro0NL** [comment]
Symfony uses `$_SERVER['HTTP_*']` to get the headers.. have a look at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L28

Perhaps you can debug from here, as there are some [edge cases](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L78).

**Comment by andig** [comment]
@ro0NL I can confirm that no corresponding `HTTP_AUTHORIZATION`variable or similar is set in the `$_SERVER` array.

**Comment by andig** [comment]
See https://github.com/symfony/symfony/pull/7649 for a PR that didn't get merge and was apparently covered by a documentation update. Unfortunately that seems valid for CGI use only.

Even if this is a PHP defect- it would make sense to patch it in Symfony?

**Comment by ro0NL** [comment]
There is an [`ApacheRequest`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ApacheRequest.php).. perhaps we could merge in headers from `apache_request_headers` here.

**Comment by andig** [comment]
I've also opened https://bugs.php.net/bug.php?id=72915 to get some further insights.

**Comment by andig** [comment]
ping @fabpot regaring the discussion from #7649

**Comment by dunglas** [comment]
From the doc of LexikJwtAuthenticationBundle 
> Important note for Apache users
> 
> As stated in this link and this one, Apache server will strip any Authorization header not in a valid HTTP BASIC AUTH format.
>
>If you intend to use the authorization header mode of this bundle (and you should), please add those rules to your VirtualHost configuration :
 
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md

**Comment by andig** [comment]
@dunglas 

> As stated in this link and this one, Apache server will strip any Authorization header not in a valid HTTP BASIC AUTH format.

From what I've read thats the case for Apache/CGI. I'm running PHP as Apache module. I've tested the rewrite rule without success. Also, the headers _are_ available using `apache_request_headers()`.

IMHO this is a PHP deficiency that Symfony might/should work around.

**Comment by nicolas-grekas** [comment]
@andig how would you fix that on Symfony side?

**Comment by andig** [comment]
In the current state perfectly legal headers sent by client are silently ignored (by PHP). This is wrong (in PHP).

As written a few comments above I'd suggest checking the relevant headers from apache (and potentially other web servers). I agree that would be lessening the pain of a PHP shortcoming but being limited to BASIC AUTH is a bit old-fashioned. If that shouldn't be OOTB, maybe it might make sense to have a "parseHeaders" extension point that an apache plugin could snap in to do just that?

**Comment by nicolas-grekas** [comment]
So, this is Apache-module only? You're suggestion is to use `apache_request_headers()`, which is only available on that SAPI, would match. I think we might try using that in [Request::createFromGlobals()](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L266)
Would you mind doing the PR?

**Comment by andig** [comment]
Shouldn't this rather go somewhere here https://github.com/symfony/symfony/blob/9a90cde4ed72bb9226354ceeecc869ee9ebee493/src/Symfony/Component/HttpFoundation/ServerBag.php#L99? 

adapted from https://stackoverflow.com/questions/40582161/how-to-properly-use-bearer-tokens

    if (!isset($headers['AUTHORIZATION'])) {
        if (function_exists('apache_request_headers')) {
            $requestHeaders = apache_request_headers();
            $requestHeaders = array_combine(array_map('ucwords', array_keys($requestHeaders)), array_values($requestHeaders));
            if (isset($requestHeaders['Authorization'])) {
                $headers['AUTHORIZATION'] = trim($requestHeaders['Authorization']);
            }
        }
    }

**Comment by nicolas-grekas** [comment]
createFromGlobals is the only place that reads from globals, and apache_request_headers also reads from globals, so yes, I'm pretty confident createFromGlobals is the right place :)

**Comment by andig** [comment]
> createFromGlobals is the only place that reads from globals

Got it. `ServerBag` ist responsible for undoing the PHP madness, `createFromGlobals` is responsible for obtaining global data.

**Comment by chalasr** [comment]
Making use of `apache_get_headers()` in `createFromGlobals()` has been rejected for performance reasons in https://github.com/symfony/symfony/pull/7649. Should we give still give it a try? Or close? I can submit the PR if desired.

**Comment by andig** [comment]
ping @nicolas-grekas what's your take on the performance impact of adding `apache_get_headers()`?

**Comment by nicolas-grekas** [comment]
Does this issue exist with FPM, or is it specific to Apache?
If Apache only, then the check should start with `if ('apache2handler' === \PHP_SAPI)`.
then I see no perf issue, but the implementation must be more optimized than what was proposed in #7649 (I think there is no need for any array_merge, let's directly access THE key that we miss.)

**Comment by andig** [comment]
> Does this issue exist with FPM, or is it specific to Apache?

The issue- no access to bearer token header- exists in general due to https://github.com/php/php-src/blob/9fc0a5e049ade8082b2b9a45687ac8cbd694f731/main/main.c#L2615

For apache it can be worked around since the native headers are accessible. 

> but the implementation must be more optimized than what was proposed

This could be done for both bearer authentication as far as I see the need. Are there other cases that should be considered?

**Comment by nicolas-grekas** [comment]
After digging and spending some time thinking about this, we should not implement the workaround in Symfony.
The reason is that this would IMHO create more WTF that help. I already found a blog post from someone who had an app work locally, but failing in prod, because of apache vs php-fpm diff here.
By not providing a **partial** workaround, we force ppl to care about the issue, which is the only real "fix" to me.

**Comment by andig** [comment]
> By not providing a partial workaround, we force ppl to care about the issue, which is the only real "fix" to me.

Makes perfect sense to me. However, getting to this point I was chasing up and down various rabbit holes (cgi workaround, various PRs, docs update etc).

Would it make sense- even if a PHP topic rather than a Symfony topic- to point out that only `Basic` and `Digest` authorisation headers are available but not the more and more popular `Bearer` headers?

In any case, can be closed, thank you!

**Comment by nicolas-grekas** [comment]
@andig in the Symfony doc for sure, please open an issue or better, a PR, on https://github.com/symfony/symfony-docs/!
Closing as discussed, thanks for it.

**Comment by JSkalskiSBG** [comment]
In my case I had to add to virtual machine config in Apache:
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by BenoitDuffez** [comment]
In my case I followed @JSkalskiSBG's instructions, but I had to recover the value in `server`:

    $request->server->get('HTTP_AUTHORIZATION')
