### ISSUE TITLE
Class level violations not added to path without some code contortionism.

### ISSUE THREAD

**Issue by keyboardSmasher** [symfony/symfony#19695]
Before the validator change, I used to be able to do this:
```
$notBlank = new Constraints\NotBlank();
$this->context->validate($transaction->getCity(), $notBlank, 'city');
```

With the new `Symfony\Component\Validator\Context\ExecutionContextInterface` I try this:

```
$this->context->getValidator()->inContext($this->context)
    ->atPath('city')->validate($transaction->getCity(), $notBlank);
// No joy. Violation is not added.
```

I must do this:
```
$violations = $this->context->getValidator()->startContext()
    ->atPath('data.city')->validate($transaction->getCity(), $notBlank)
    ->getViolations();
$this->context->getViolations()->addAll($violations);
// JOY! Violation is added.
```

Notice I have to use `data.city`, not just `city` in order for it to work. (thank goodness for xdebug)

**Comment by keyboardSmasher** [comment]
I guess this is just normal behavior, so I'll just go with it. 👍

**Comment by HeahDude** [comment]
Can we close here?

**Comment by keyboardSmasher** [comment]
I think at the very least that it should be documented that when you are using a custom "class level" validation constraint that the validator doesn't work as advertised. Where is `data.` documented? I don't believe this is the intended behavior.

But since I have found a workaround, and if no one has any objections, go ahead and close. :D

**Comment by HeahDude** [comment]
What about
```php
$this->context->getValidator()->inContext($this->context)
    ->validate($transaction->getCity(), $notBlank);
```
?

You should check the [upgrade file](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#validator), there is some examples close to your final solution in there.

If you fixed your issue, thank you for reporting this in the docs repository so we can close here.

**Comment by keyboardSmasher** [comment]
Nope. The problem is that the context is the class data. So, it needs to know which path to add the violation to.

They've taken a simple one-line solution and turned it into a convoluted mess. But, I'll close this issue regardless.

:)
