### ISSUE TITLE
[EventDispatcher] Possibility to add pointer at which the propagation has stopped

### ISSUE THREAD

**Issue by yellowmamba** [symfony/symfony#19709]
Hi,

This is more of a feature request than an actual bug. At the moment, event dispatcher does not track at which listener does event propagation stop. For instance, I would like the ability to see out of my 10 listeners, which listener stops the propagation, and why. I have looked into `TraceableEventDispatcher`, but it only holds the called and uncalled listeners, and can't be grouped by the event name.

The way I work around it is to have a listener interface from which all listeners extend, that returns the name of the listener, and then I override `stopPropagation` of my event to record the name of the listener where it stops.

My listener interface looks like this:

```php
interface EventListenerInterface
{
    public function getName();

    public function getStopMessage();
}
```

I am not sure how helpful it would be for the rest of community. I have had to do something like this every time I needed to send a batch of events, and then generate a summary of how they got handled.

Would be interested to listen to what everyone has to say.

Cheers

**Comment by stof** [comment]
An event listener is just a callable, so your proposal won't work.

**Comment by ro0NL** [comment]
First thought is to use an object in the middle to cover your case... ie. solve it in userland;

```php
// listener A
$obj->mark();

// listener B
$obj->isMarked();
```

**Comment by yellowmamba** [comment]
Yeah ok, agree with @stof the listener could be an anonymous function as well, in which case it wouldn't be of much help.
