### ISSUE TITLE
[Console] Running an Application in a Process without TTY can't keep Terminal size

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#19719]
_All branches are concerned._

_On OS X, in an iTerm window opened with < 120 columns._

The following script:

```php
<?php
# output_something.php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Console\Terminal;
use Symfony\Component\Process\Process;

require __DIR__.'/vendor/autoload.php';

(new Application('output_something'))
    ->register($commandName = 'ヽ(⌐■_■)ノ')
        ->addOption('no-more')
        ->setCode(function (InputInterface $input, OutputInterface $output) {
            $terminal = new Terminal();
            $io = new SymfonyStyle($input, $output);
            $io->note('Terminal width: '.$terminal->getWidth());
            $io->success('Success');

            if (!$input->getOption('no-more')) {
                (new Process('php output_something.php --no-more --ansi'))
//                    ->setTty(true)
                    ->run(function ($type, $buffer) use ($io) {
                        $io->write($buffer);
                    })
                ;
            }
        })
    ->getApplication()
    ->setDefaultCommand($commandName, true)
    ->run()
;
```

will output:

<img width="756" alt="screenshot 2016-08-23 a 23 35 13" src="https://cloud.githubusercontent.com/assets/2211145/17911221/bae2b4de-698c-11e6-8c58-a61c14d95a23.PNG">

instead of:

<img width="759" alt="screenshot 2016-08-23 a 23 35 29" src="https://cloud.githubusercontent.com/assets/2211145/17911528/3e91efe2-698e-11e6-8864-161710213850.PNG">

Uncommenting the `$process->setTty(true);` line will resolve the issue.

However, [it's not always convenient to enabled TTY mode](https://github.com/symfony/symfony-docs/issues/6188#issuecomment-175479684) and is not often used by third-party scripts.

For instance, with classical Composer post-install scripts, in which commands are executed in a process without TTY mode, it causes some issues on a small terminal width:

<img width="755" alt="screenshot 2016-08-24 a 00 02 24" src="https://cloud.githubusercontent.com/assets/2211145/17911513/2f785ab4-698e-11e6-8d89-257681f7baf8.PNG">

A quick solution to this (at least in 3.2) would be to set the `COLUMNS` & `LINES` env variables in order to reuse them in the process as soon as we run the `Application`. But I doubt this would be the best way to go.

<details>
<summary>Show quick fix sample for >= 3.2</summary>
```diff
diff --git a/src/Symfony/Component/Console/Application.php b/src/Symfony/Component/Console/Application.php
index f0129d5..fa5e8d4 100644
--- a/src/Symfony/Component/Console/Application.php
+++ b/src/Symfony/Component/Console/Application.php
@@ -104,6 +104,8 @@ class Application
      */
     public function run(InputInterface $input = null, OutputInterface $output = null)
     {
+        $this->terminal->setEnv();
+
         if (null === $input) {
             $input = new ArgvInput();
         }
@@ -361,7 +363,7 @@ class Application
      * Adds an array of command objects.
      *
      * If a Command is not enabled it will not be added.
-     * 
+     *
      * @param Command[] $commands An array of commands
      */
     public function addCommands(array $commands)
diff --git a/src/Symfony/Component/Console/Terminal.php b/src/Symfony/Component/Console/Terminal.php
index 9189f2d..d36e333 100644
--- a/src/Symfony/Component/Console/Terminal.php
+++ b/src/Symfony/Component/Console/Terminal.php
@@ -52,6 +52,17 @@ class Terminal
         return self::$height;
     }

+    public function setEnv()
+    {
+        if (!trim(getenv('LINES'))) {
+            putenv('LINES=' . $this->getHeight());
+        }
+
+        if (!trim(getenv('COLUMNS'))) {
+            putenv('COLUMNS=' . $this->getWidth());
+        }
+    }
+
     private static function initDimensions()
     {
         if ('\\' === DIRECTORY_SEPARATOR) {
```
</details>

**Comment by chalasr** [comment]
👍  Confirmed, the output width/height of processes aren't the ones of the terminal from which the script is ran (if no explicit `setTty(true)`).

The proposed approach fixes the bug on 3.1+, we'll need to find an equivalent for older branches.

**Comment by nicolas-grekas** [comment]
Why not? Please open a PR...

**Comment by ogizanagi** [comment]
@nicolas-grekas : Because I don't know how to fix and test it for real. The suggested fix is kind of both a feature and a fix, unless we decide to backport the env variable handling introduced in the `Terminal` class in 3.2...
Thus I decided to expose the issue first.

Anyway, here's the PR.
