### ISSUE TITLE
Error installing dependency injector

### ISSUE THREAD

**Issue by alvibd** [symfony/symfony#19723]
I get this following error while installing symfony dependency injection through composer

Call to undefined method Symfony\Component\DependencyInjection\ContainerBuilder::addScope()

Been trying to figure out but could not find such resoource. How can I solve this?

**Comment by iltar** [comment]
Which version are  you trying to install and do you already have something installed?

**Comment by alvibd** [comment]
sorry, I found out it is only needed for symfony version 3.1
