### ISSUE TITLE
CollectionType: about "entry_type" option when collection has different types

### ISSUE THREAD

**Issue by Ziiweb** [symfony/symfony#19737]
Hi,

I'm using `CollectionType` to upload files related to a `Trip` entity, in a variable called `$paths` (type array). So they will be this saved this way:

`["a3d7662c73254e57ab60e47f96f999077754725a.jpeg","6f6c6ed62397add9a5047a67df344ad1d9183225.jpeg"]`

When editing a `Trip` entity I need to **show** and **add** files (pictures). So..

1. to **show** the pictures I cannot give a default value to an input file type ([read this](http://stackoverflow.com/questions/1696877/how-to-set-a-value-to-a-file-input-in-html)) so I have to transform the `$paths` array to text type inputs.

2. and to **add** new pictures I have to generate new file type inputs using JS.

So I have **file type inputs** and **text type inputs** in the same collection

The problem: I get errors if I set `entry_type: FileType::class` because of the **text type inputs** inside the collection, and I have to transform the text type inputs to file type inputs.

So Im wondering if you have consider to support collections with different form field types.

**Comment by dmaicher** [comment]
Idea: create a new form type `PathType` that will either add a text field or a file field with `inherit_data` set to `true` (http://symfony.com/doc/current/reference/forms/types/form.html#inherit-data). You can use a form event listener on `PRE_SET_DATA` to decide which field type to add. Client side you can use the prototype then and add it to the DOM via JS as described here http://symfony.com/doc/current/form/dynamic_form_modification.html.

Anyway is not an issue with the symfony form component imho but rather a question for stackoverflow :wink:

**Comment by HeahDude** [comment]
@dmaicher's suggestion is the way to go in your case: using a custom type as entry for the collection.

For polymorphic collection there is already https://github.com/symfony/symfony/issues/9835.

I think we can close this one.
