### ISSUE TITLE
BinaryFileResponse sends wrong Content-Length header for files modified by stream wrappers/filters

### ISSUE THREAD

**Issue by TravisCarden** [symfony/symfony#19738]
`\Symfony\Component\HttpFoundation\BinaryFileResponse::prepare()` sets the `Content-Length` header based on a simple `getSize()` for the file on disk. However, if the file passes through a stream filter that changes its file size, the result is that the file is delivered with the wrong header value, causing it to fail to display properly in most browsers. I discovered this while implementing an encryption layer, because it stores my files encrypted on disk and decrypts them on-the-fly for delivery. I'm able to fix the problem in `BinaryFileResponse`, like so:

``` diff
--- a/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php
+++ b/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php
@@ -186,7 +186,11 @@ class BinaryFileResponse extends Response
      */
     public function prepare(Request $request)
     {
-        $this->headers->set('Content-Length', $this->file->getSize());
+        ob_start();
+        $size = readfile($this->getPathname());
+        ob_end_clean();
+
+        $this->headers->set('Content-Length', $size);

         if (!$this->headers->has('Accept-Ranges')) {
             // Only accept ranges on safe HTTP methods
```

The problem could probably be solved in other places, too--like `\Symfony\Component\HttpFoundation\File\File::getSize()`--depending on the domain model. (e.g., if `File` should be thought of as truly representing the file on disk, it may be a pollution of the concept to modify it to compensate for streaming behavior.)

**Comment by EclipseGc** [comment]
Maybe something like this? (completely untested code)

```diff
diff --git a/File/File.php b/File/File.php
index 4736b45..dac1a3e 100644
--- a/File/File.php
+++ b/File/File.php
@@ -133,4 +133,14 @@ class File extends \SplFileInfo
 
         return $originalName;
     }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function getSize()
+    {
+        $file = fopen($this->getPathname(), 'rb');
+        return fstat($file)['size'];
+    }
+
 }

**Comment by patrick-mcdougle** [comment]
If you're passing it through as a stream, shouldn't you just set the Transfer-Encoding to chunked and leave the content-length header off?

**Comment by TravisCarden** [comment]
It's not being streamed over HTTP. The file contents are being modified as read via a PHP stream filter.

**Comment by d-ph** [comment]
In case someone used the same google keywords as me, read the OPs problem, concluded that it somewhat matches your problem:

Use `clearstatcache(true, $fileNameYouModifiedUsingFilePointerFunctions)`.

More info: https://stackoverflow.com/a/5167585/2282328 and https://www.php.net/manual/en/function.clearstatcache.php.

You're welcome and I wish you a productive day.
