### ISSUE TITLE
Some warnings spout out.

### ISSUE THREAD

**Issue by makoru-hikage** [symfony/symfony#19730]
The error_reporting spout out this messages upon usage:

```
Warning: Illegal offset type in D:\xampp\htdocs\project\vendor\symfony\security-csrf\TokenStorage\NativeSessionTokenStorage.php on line 88

Warning: Illegal offset type in D:\xampp\htdocs\project\vendor\symfony\security-csrf\TokenStorage\NativeSessionTokenStorage.php on line 76
```

As I check upon the aforementioned lines, they use the same practice of use object property as an array key which is considered a bad practice for some. Fortunately, the usage is not detrimental to the efficiency of the class, yet it is quite annoying.

```
76 .. $_SESSION[$this->namespace][$tokenId] = (string) $token;
88 .. return isset($_SESSION[$this->namespace][$tokenId]);
```

Shall you suppress such warnings by appending `@` or rework this one?

**Comment by jakzal** [comment]
Did you pass anything as a namespace to the constructor? It should be a string (or nothing to use the default).

**Comment by stof** [comment]
We have no reason to silence these warnings IMO. they indicate that you are already breaking the contract of the class, as they cannot happen in a supported usage.

**Comment by makoru-hikage** [comment]
Thank you very much for the responses.

What I did was...

```
use \Symfony\Component\HttpFoundation\Session\Session;
use \Symfony\Component\Form\Extension\Csrf\CsrfExtension;
use \Symfony\Component\Security\Csrf\TokenStorage\NativeSessionTokenStorage;
use \Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator;
use \Symfony\Component\Security\Csrf\CsrfTokenManager;
...

/* CSRF protector */
    // create a Session object from the HttpFoundation component
    $session = new Session();

    $csrfGenerator = new UriSafeTokenGenerator();
    $csrfStorage = new NativeSessionTokenStorage($session);
    $csrfManager = new CsrfTokenManager($csrfGenerator, $csrfStorage);

    $container['form_factory'] = Forms::createFormFactoryBuilder()
        ->addExtension(new HttpFoundationExtension())
        ->addExtension(new CsrfExtension($csrfManager))
        ->getFormFactory();
...
```

I just copied and edited some snippet from the [Symfony Form Component documentation](http://symfony.com/doc/current/components/form.html).

I use the complete Symfony Form Component for this [project](https://github.com/makoru-hikage/SlimStarterDelta-prototype/blob/master/app/container/container.php) I've been working on.

The responses are sincerely appreciated; thank you very much.

**Comment by xabbuh** [comment]
Well, you are passing `$session` to the `NativeSessionTokenStorage` constructor which expects a string while `$session` is an instance of `Session` in your example. The example in the docs doesn't pass an argument at all which lets the token storage use a default namespace. Thus I am closing here as this is not an issue in Symfony. But thank you anyway for opening the issue. :)

**Comment by makoru-hikage** [comment]
Thank you very much!
