### ISSUE TITLE
Error 500 every time it is made the deployment of a new code in system Symfony 2.8 in production, someone has been through this?

### ISSUE THREAD

**Issue by faelp22** [symfony/symfony#19739]
What happens, I have a SYMFONY 2.8 production system, it receives updates from my packages "BUNDLES" through to "pull" automatic. and for some reason the server to error 500, complaining of cached code.

I do not cache on apache and not use another caching system, PHP 6.5.24 use this linux server.

This is an example of the error that occurs when the server receives an update.

[Wed Aug 24 17:05:11.638885 2016] [:error] [pid 11055] [client 64.16.214.100:30866] PHP Fatal error:  
Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ServiceCircularReferenceException' with message 'Circular reference detected for service "service_name", path: 
"service_name".' in /home/my_system/app/bootstrap.php.cache:2191\nStack trace:\n#0 /tmp/my_system/prod/cache/classes.php(2460): 
Symfony\\Component\\DependencyInjection\\Container->get('service_name')\n#1 /tmp/my_system/prod/cache/classes.php(2428): 
Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->lazyLoad('kernel.exceptio...')\n#2 /tmp/my_system/prod/cache/classes.php(2275): 
Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners('kernel.exceptio...')\n#3 /home/my_system/app/bootstrap.php.cache(3265): 
Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#4 /home/my_system/app/bootstrap.php.cache(3213): 
Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Symfony\\Component\\Debug\\Exc in /home/my_system/app/bootstrap.php.cache on line 2191

How to solve the problem? I restart the Apache service. Now I would like to understand and solve it with the help of you as I can be doing something wrong in this process.

Thank you all

**Comment by faelp22** [comment]
Run the following command every time I send an update:

composer install --no-dev --optimize-autoloader
php app/console cache:clear --env=prod --no-debug
php app/console assets:install --symlink --env=prod --no-debug

But still does not solve the problem, as I said before I can only solve if I restartar the apache service.

**Comment by peterrehm** [comment]
Do you use opcache? That caused some issues in our deployment process and therefore we are clearing the cache on each deployment. But this caused only issues on specific changes.

**Comment by jakzal** [comment]
Please use one of our [support channels](http://symfony.com/support) to get support. We only use github for development. Thank you for understanding.

**Comment by faelp22** [comment]
Thank @jakzal, I'm sorry I did not, I asked the question in there [stackoverflow](http://stackoverflow.com/questions/39166476/error-500-every-time-it-is-made-the-deployment-of-a-new-code-in-system-symfony-2) ok
