### ISSUE TITLE
[DI] Extract string manipulation static methods from Container to StringUtil

### ISSUE THREAD

**Issue by a-ast** [symfony/symfony#19746]
The `Container` class has two public static methods for string manipulations: `camelize` and `underscore`.
Converting strings is not a responsibility of a container. Some classes even use `Container` namespace only to call these static methods.   

Other components have a dedicated class for string utils:
* Symfony\Component\PropertyAccess\StringUtil
* Symfony\Component\Form\Util\StringUtil

My suggestion is to extract string functions to a new class Symfony\Component\DependencyInjection\StringUtil and deprecate `Container::camelize` and `Container::underscore`.

**Comment by stof** [comment]
-1 for that. Providing reusable inflection utilities is not the goal of this component (use ``doctrine/inflector`` or another dedicated package for that).

IMO, we should mark these 2 methods as ``@internal``.

**Comment by a-ast** [comment]
@stof It is mainly about a single responsibility. I still think it is better to have these 2 methods apart from `Container` and mark `StringUtil` as `@internal`.

**Comment by a-ast** [comment]
BTW, these methods are used in SensioGeneratorBundle so they are not internal.

**Comment by fabpot** [comment]
Closing this one as I don't see how moving them to another class would fix anything. As @stof said, having a new class would make them more prominently available for people to reuse. These methods are public because (as you noticed), we need them from time to time internally and in some bundles.
