### ISSUE TITLE
[Console][3.0][3.1] How to test SymfonyStyle::askQuestion interaction?

### ISSUE THREAD

**Issue by aedart** [symfony/symfony#19753]
In version 3.0.x of the Symfony Console component, I'm relying on the `SymfonyStyle` to output certain elements, such as questions. However, now that I need to test my commands, I'm running into trouble, because I have no idea how to test the interactive part, while using `SymfonyStyle`.

I have the following base command, from which all of my application's commands inherit from;

``` php
abstract class BaseCommand extends Command
{

    /**
     * The input
     *
     * @var InputInterface
     */
    protected $input;

    /**
     * The output
     *
     * @var StyleInterface
     */
    protected $output;

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $ioc = IoC::getInstance();

        $this->input = $input;
        $this->output = $ioc->make(StyleInterface::class, [
            'input'     => $input,
            'output'    => $output,
        ]);

        return $this->runCommand();
    }

    /**
     * Execute the command
     *
     * @return int|null
     */
    abstract public function runCommand();
}
```

Inspired by [How to test commands that expect input](http://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input), I wrote the following helper methods in my tests;

```php
    /**
     * Returns a input stream
     *
     * Utility method for helping to test commands that
     * require interaction.
     *
     * @see http://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input
     *
     * @param $input
     *
     * @return resource
     */
    public function getInputStream($input)
    {
        $stream = fopen('php://memory', 'r+', false);
        fputs($stream, $input);
        rewind($stream);

        return $stream;
    }

    /**
     * Write input stream
     *
     * @param array $input
     *
     * @return resource
     */
    public function writeInput(array $input)
    {
        $input = implode('\n', $input);

        return $this->getInputStream($input);
    }
```

### The problem

I'm not able to (don't see how) set the input stream onto the question helper inside the `SymfonyStyle`. 
This is largely due to that the question helper is not able to be specified in the default implementation.

``` php

    public function askQuestion(Question $question)
    {
        if ($this->input->isInteractive()) {
            $this->autoPrependBlock();
        }

        // PROBLEM HERE: !$this->questionHelper is private, new instance always created.
        if (!$this->questionHelper) {
            $this->questionHelper = new SymfonyQuestionHelper();
        }

        $answer = $this->questionHelper->ask($this->input, $this, $question);

        if ($this->input->isInteractive()) {
            $this->newLine();
            $this->bufferedOutput->write("\n");
        }

        return $answer;
    }

```

Even if I create a custom implementation, I'm still not sure how to allow a stream's data to be specified.

Thus, I have no idea how I can write a few tests in which interaction is proven via some input. It appears that this issues is being kind of resolved in you `dev-master`, but I really need a good way of solving this for version 3.0 or 3.1.

**Comment by chalasr** [comment]
As you spotted, command testing has been improved in 3.2, especially on `SymfonyStyle` for which it was quite hard (maybe impossible).
You can now set your inputs on the CommandTester directly, working with and without SymfonyStyle (see [the doc on 3.2](http://symfony.com/doc/master/components/console/helpers/questionhelper.html)).

I may be wrong, but I would say you to require `symfony/console:~3.2@dev` in dev (only), so you can profit of these changes for testing, without going with dev dependencies in production. 
This solution feels safe to me because the behavior is the same as in 3.0/3.1, changes only concern testing.

**Comment by aedart** [comment]
Thanks, I think that might just work.
