### ISSUE TITLE
SVG version of our exception ghost anyone?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#19756]
Would anyone with some vectorial drawing skills like to prepare an SVG version of our cute exception ghost?

![332033](https://cloud.githubusercontent.com/assets/243674/18025963/6f42c140-6c39-11e6-8f99-96f6d07e9adf.gif)

**Comment by patrick-mcdougle** [comment]
@nicolas-grekas I could probably start doing that tomorrow. Anyone know what font that is? If not, I can try and trace the shapes into paths or just pick a font that looks similar.

**Comment by patrick-mcdougle** [comment]
it looks like the ghost part is already done... symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Icon/exception.svg

**Comment by patrick-mcdougle** [comment]
This one is the ghost and the bubble where the text is actual text (user would need the Alba font for it to look right). I'll make one that's less international-friendly where the text is just the outlines. The style should probably be brought out of the svg. Let me know how you'd like to proceed (internationalizable or not) and I'll open the PR moving to use svg instead.

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112 126"><defs><style>#ghost{fill:#3f3f3f;}#bubble{fill:#aacd4e;}text{font-size:14px;fill:#fff;font-family:Alba, sans-serif;}</style></defs><g id="ghost"><path d="M106.17,97a1.92,1.92,0,0,1-2,0,2.05,2.05,0,0,1,0-1.87c3.92-5.25-4.58-5.46-1.89-.6.36.66.48,2.66-.11,2.48-5.17-1.58-5,1.94,0,2,.63,0-1,5.1-5.17,4.91V97c0-26.67-39.19-26.67-39.19,0,0,3.17,0,5.35,0,6.88C53,104.62,51.36,99.06,52,99c5-.1,5.16-3.62,0-2-.59.18-.48-1.82-.12-2.48,2.7-4.86-5.8-4.65-1.89.6A2.05,2.05,0,0,1,50,97a1.92,1.92,0,0,1-2,0c-5.5-6.83-7.25,2.67,0,2,.5,0,1.64-.07,1.51.42-1.85,6.9,3.34,7,8.28,7.64,0,1.54,0-1.06,0,8.94,0,10.33,12.72,10.33,12.72,0,0,10.33,13,10.33,13,0,0,10.33,13.51,10.33,13.51,0v-9c4.95-.63,9.48-.85,7.67-7.59-.13-.48,1-.46,1.5-.42C113.42,99.67,111.67,90.17,106.17,97Zm-44-6c0-4.23,3.08-7.65,6.87-7.65s6.87,3.42,6.87,7.65a7.48,7.48,0,0,1-5.51,7.5,3.23,3.23,0,0,0,1.9-2.94,3.26,3.26,0,1,0-4.62,2.94A7.48,7.48,0,0,1,62.18,91ZM77.5,112.5c-4.72,0-9.5-2.92-9.5-8.5a1,1,0,0,1,2,0c0,4.47,3.89,6.5,7.5,6.5s7.5-2,7.5-6.5a1,1,0,0,1,2,0C87,109.58,82.22,112.5,77.5,112.5Zm9.71-14a3.26,3.26,0,1,0-2.73,0A7.49,7.49,0,0,1,79,91c0-4.23,3.08-7.65,6.88-7.65s6.87,3.42,6.87,7.65A7.49,7.49,0,0,1,87.21,98.48Z"/></g><g id="bubble"><path d="M56.65,70.4C75,66.1,88.42,52.52,88.42,36.42,88.42,16.86,68.63,1,44.21,1S0,16.86,0,36.42C0,55.68,19.21,71.34,43.12,71.81H43C43,77.21,50.88,84,57,84,52.71,78.67,54.08,71,56.65,70.4Z"/><text transform="matrix(1.05, -0.12, 0.12, 0.99, 12.76, 36.15)">Exception<tspan x="-0.45" y="16.8">detected!</tspan></text></g></svg>

**Comment by patrick-mcdougle** [comment]
And here's the one with the paths:

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112 126"><defs><style>#ghost{fill:#3f3f3f;}#bubble{fill:#aacd4e;}</style></defs><g id="ghost"><path d="M106.17,97a1.92,1.92,0,0,1-2,0,2.05,2.05,0,0,1,0-1.87c3.92-5.25-4.58-5.46-1.89-.6.36.66.48,2.66-.11,2.48-5.17-1.58-5,1.94,0,2,.63,0-1,5.1-5.17,4.91V97c0-26.67-39.19-26.67-39.19,0,0,3.17,0,5.35,0,6.88C53,104.62,51.36,99.06,52,99c5-.1,5.16-3.62,0-2-.59.18-.48-1.82-.12-2.48,2.7-4.86-5.8-4.65-1.89.6A2.05,2.05,0,0,1,50,97a1.92,1.92,0,0,1-2,0c-5.5-6.83-7.25,2.67,0,2,.5,0,1.64-.07,1.51.42-1.85,6.9,3.34,7,8.28,7.64,0,1.54,0-1.06,0,8.94,0,10.33,12.72,10.33,12.72,0,0,10.33,13,10.33,13,0,0,10.33,13.51,10.33,13.51,0v-9c4.95-.63,9.48-.85,7.67-7.59-.13-.48,1-.46,1.5-.42C113.42,99.67,111.67,90.17,106.17,97Zm-44-6c0-4.23,3.08-7.65,6.87-7.65s6.87,3.42,6.87,7.65a7.48,7.48,0,0,1-5.51,7.5,3.23,3.23,0,0,0,1.9-2.94,3.26,3.26,0,1,0-4.62,2.94A7.48,7.48,0,0,1,62.18,91ZM77.5,112.5c-4.72,0-9.5-2.92-9.5-8.5a1,1,0,0,1,2,0c0,4.47,3.89,6.5,7.5,6.5s7.5-2,7.5-6.5a1,1,0,0,1,2,0C87,109.58,82.22,112.5,77.5,112.5Zm9.71-14a3.26,3.26,0,1,0-2.73,0A7.49,7.49,0,0,1,79,91c0-4.23,3.08-7.65,6.88-7.65s6.87,3.42,6.87,7.65A7.49,7.49,0,0,1,87.21,98.48Z"/></g><g id="bubble"><path d="M61.33,28.16a1.75,1.75,0,0,0,1.31.35,1.77,1.77,0,0,0,1.2-.64,1.6,1.6,0,0,0,.38-1.25,1.58,1.58,0,0,0-.66-1.12,1.79,1.79,0,0,0-1.32-.34,1.76,1.76,0,0,0-1.19.64A1.58,1.58,0,0,0,60.68,27,1.61,1.61,0,0,0,61.33,28.16Z"/><path d="M56.65,70.4C75,66.1,88.42,52.52,88.42,36.42,88.42,16.86,68.63,1,44.21,1S0,16.86,0,36.42C0,55.68,19.21,71.34,43.12,71.81H43C43,77.21,50.88,84,57,84,52.71,78.67,54.08,71,56.65,70.4Zm4.84-28.25a1.76,1.76,0,0,0-1.19.64A1.59,1.59,0,0,0,59.92,44a1.61,1.61,0,0,0,.66,1.13,1.75,1.75,0,0,0,1.31.35l1.31-.15a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.91.91,0,0,1-.19.71,1,1,0,0,1-.68.35l-1.31.15a3.75,3.75,0,0,1-2.79-.72,3.53,3.53,0,0,1-.6-5.06,4,4,0,0,1,5.4-.57.9.9,0,0,1,.37.61.92.92,0,0,1-.34.82l-1.68,2a1.05,1.05,0,0,1-.66.36,1,1,0,0,1-.75-.2.91.91,0,0,1-.38-.64.89.89,0,0,1,.25-.69l.94-1.12A1.89,1.89,0,0,0,61.49,42.15Zm11.66-5.23a.89.89,0,0,1,.2-.7,1,1,0,0,1,.67-.35,1,1,0,0,1,.75.17.88.88,0,0,1,.36.64l.59,5a.91.91,0,0,1-.2.72,1,1,0,0,1-.69.35,1,1,0,0,1-.75-.18.92.92,0,0,1-.35-.65ZM76,45.25a1.3,1.3,0,0,1-1.74.21,1.09,1.09,0,0,1-.45-.78,1.06,1.06,0,0,1,.27-.85,1.29,1.29,0,0,1,1.72-.2,1.06,1.06,0,0,1,.46.76A1.09,1.09,0,0,1,76,45.25ZM67.62,23.48a3.41,3.41,0,0,1,4.52-.53,2.83,2.83,0,0,1,1.17,2l.49,4.15a1.07,1.07,0,0,0,.44.76,1.19,1.19,0,0,0,.88.23h.06a1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34h-.06a3.19,3.19,0,0,1-2.37-.6,2.86,2.86,0,0,1-1.17-2l-.08-.66-.41-3.5a1,1,0,0,0-.44-.75,1.18,1.18,0,0,0-.88-.23,1.21,1.21,0,0,0-.81.42,1,1,0,0,0-.25.84l.37,3.17a.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1,1,0,0,1-.74-.17.89.89,0,0,1-.35-.64L67,25.72A2.83,2.83,0,0,1,67.62,23.48Zm1.21,15.9a1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.37,1.24,1.56,1.56,0,0,0,.65,1.12,1.77,1.77,0,0,0,1.31.34,1.79,1.79,0,0,0,1.2-.64A1.57,1.57,0,0,0,71,42.71l-.64-5.46a.88.88,0,0,1,.2-.7,1,1,0,0,1,.67-.35,1,1,0,0,1,.75.17.88.88,0,0,1,.36.64L73,42.47a3.35,3.35,0,0,1-.8,2.65,4,4,0,0,1-5.33.63,3.49,3.49,0,0,1-.6-5A3.76,3.76,0,0,1,68.83,39.38ZM59.47,24.6A4,4,0,0,1,64.82,24a3.51,3.51,0,0,1,.6,5.06,4,4,0,0,1-5.35.63,3.53,3.53,0,0,1-.6-5.06ZM58.19,30a.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1,1,0,0,1-.74-.17.89.89,0,0,1-.35-.64L55.58,25a.89.89,0,0,1,.19-.71,1,1,0,0,1,.68-.34q1-.12,1.11.82Zm-2.9-8.56A1.27,1.27,0,0,1,57,21.2a1.11,1.11,0,0,1,.19,1.63,1.27,1.27,0,0,1-1.72.2,1.11,1.11,0,0,1-.19-1.63Zm-6.86,2.07a1,1,0,0,1,.68-.35,1,1,0,0,1,.75.18.9.9,0,0,1,.36.65l.09.74,3.37-.4a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.86.86,0,0,1-.87,1.06l-3.37.4.26,2.17a1.07,1.07,0,0,0,.44.76,1.2,1.2,0,0,0,.88.23,1.17,1.17,0,0,0,.8-.43,1.08,1.08,0,0,0,.24-.84l0-.12a.87.87,0,0,1,.21-.7,1,1,0,0,1,.68-.35,1,1,0,0,1,.74.18.89.89,0,0,1,.36.63v.13a2.85,2.85,0,0,1-.66,2.24,3.16,3.16,0,0,1-2.15,1.14A3.19,3.19,0,0,1,50,31a2.84,2.84,0,0,1-1.17-2l-.57-4.78A.92.92,0,0,1,48.43,23.47ZM28.1,28.31A3.76,3.76,0,0,1,30.65,27a1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.38,1.24A1.57,1.57,0,0,0,30,31.85a1.77,1.77,0,0,0,1.31.34,1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,3.76,3.76,0,0,1-2.78-.71,3.49,3.49,0,0,1-.6-5ZM13,31.22a4.71,4.71,0,0,1,1.11-3.72,5.27,5.27,0,0,1,3.57-1.89,1,1,0,0,1,.75.17.88.88,0,0,1,.36.64.9.9,0,0,1-.2.71,1,1,0,0,1-.69.35A3.35,3.35,0,0,0,16,28.3,3.07,3.07,0,0,0,15,30l3.1-.37a1,1,0,0,1,.75.17.89.89,0,0,1,.36.64.9.9,0,0,1-.2.71,1,1,0,0,1-.69.35l-3.15.37a3.06,3.06,0,0,0,1.37,1.47,3.34,3.34,0,0,0,2,.39,1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,5.27,5.27,0,0,1-3.91-1A4.71,4.71,0,0,1,13,31.22Zm8.39,19.91a4,4,0,0,1-5.33.63,3.49,3.49,0,0,1-.6-5A3.76,3.76,0,0,1,18,45.39a1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34A1.76,1.76,0,0,0,17,47.9a1.59,1.59,0,0,0-.37,1.24,1.57,1.57,0,0,0,.65,1.12,1.77,1.77,0,0,0,1.31.34A1.79,1.79,0,0,0,19.8,50a1.57,1.57,0,0,0,.38-1.25l-.65-5.46a.89.89,0,0,1,.2-.7,1,1,0,0,1,.67-.35,1,1,0,0,1,.75.17.88.88,0,0,1,.36.64l.65,5.46A3.35,3.35,0,0,1,21.37,51.13Zm1.08-16.94a.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1,1,0,0,1-.74-.17.89.89,0,0,1-.35-.64l0-.36a2.86,2.86,0,0,1,.81-2.38,2.81,2.81,0,0,1-1.34-2.12l0-.36a.89.89,0,0,1,.19-.71,1,1,0,0,1,.68-.34q1-.12,1.11.82l0,.36a1.05,1.05,0,0,0,.44.76,1.2,1.2,0,0,0,.88.22,1.17,1.17,0,0,0,.79-.43,1.06,1.06,0,0,0,.25-.83l0-.36a.89.89,0,0,1,.2-.71,1,1,0,0,1,.69-.34,1,1,0,0,1,.74.17.89.89,0,0,1,.35.64l0,.36a2.81,2.81,0,0,1-.81,2.37,2.86,2.86,0,0,1,1.34,2.13l0,.36a.89.89,0,0,1-.19.71,1,1,0,0,1-.68.34,1,1,0,0,1-.74-.18.87.87,0,0,1-.37-.63l0-.36a1.07,1.07,0,0,0-.44-.75,1.16,1.16,0,0,0-.87-.24,1.2,1.2,0,0,0-.81.43,1.07,1.07,0,0,0-.25.84Zm4.07,12.09a1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.37,1.25,1.61,1.61,0,0,0,.66,1.13,1.75,1.75,0,0,0,1.31.35l1.31-.15a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.91.91,0,0,1-.19.71,1,1,0,0,1-.68.35l-1.31.15a3.75,3.75,0,0,1-2.79-.72,3.53,3.53,0,0,1-.6-5.06,4,4,0,0,1,5.4-.57.9.9,0,0,1,.37.61.92.92,0,0,1-.34.82l-1.68,2a1,1,0,0,1-.66.36,1,1,0,0,1-.75-.21.91.91,0,0,1-.38-.64.89.89,0,0,1,.25-.69l.94-1.12A1.9,1.9,0,0,0,26.51,46.28Zm9.76,3.25a3.4,3.4,0,0,1-4.52.54,2.84,2.84,0,0,1-1.17-2L30,43.26a.92.92,0,0,1,.19-.71,1,1,0,0,1,.68-.35,1,1,0,0,1,.75.18A.91.91,0,0,1,32,43l.09.74,3.37-.4a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.86.86,0,0,1-.87,1.06l-3.37.4.26,2.17a1.07,1.07,0,0,0,.44.76,1.2,1.2,0,0,0,.88.23,1.17,1.17,0,0,0,.8-.43,1.08,1.08,0,0,0,.24-.84V47.4a.87.87,0,0,1,.21-.7,1,1,0,0,1,.68-.35,1,1,0,0,1,.74.18.89.89,0,0,1,.36.63v.13A2.85,2.85,0,0,1,36.27,49.53Zm-2-16.81a3.53,3.53,0,0,1-.6-5.06,4,4,0,0,1,5.4-.57.9.9,0,0,1,.37.61.92.92,0,0,1-.34.82l-1.68,2a1.05,1.05,0,0,1-.66.36,1,1,0,0,1-.75-.2.91.91,0,0,1-.38-.64.89.89,0,0,1,.25-.69l.94-1.12a1.89,1.89,0,0,0-.39,0,1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.37,1.25,1.61,1.61,0,0,0,.66,1.13,1.75,1.75,0,0,0,1.31.35l1.31-.15a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.91.91,0,0,1-.19.71,1,1,0,0,1-.68.35L37,33.44A3.75,3.75,0,0,1,34.25,32.72Zm7,11.82a1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.37,1.25,1.61,1.61,0,0,0,.66,1.13,1.75,1.75,0,0,0,1.31.35l1.31-.15a1,1,0,0,1,.74.17.89.89,0,0,1,.35.64.91.91,0,0,1-.19.71,1,1,0,0,1-.68.35l-1.31.15a3.75,3.75,0,0,1-2.79-.72,3.53,3.53,0,0,1-.6-5.06,4,4,0,0,1,5.4-.57.9.9,0,0,1,.37.61.92.92,0,0,1-.34.82l-1.68,2a1.05,1.05,0,0,1-.66.36,1,1,0,0,1-.75-.2.91.91,0,0,1-.38-.64.89.89,0,0,1,.25-.69l.94-1.12A1.89,1.89,0,0,0,41.23,44.54Zm2.63-12.18a.91.91,0,0,1-.35-.65A.89.89,0,0,1,43.7,31a1,1,0,0,1,.68-.34,1.78,1.78,0,0,0,1.2-.64A1.6,1.6,0,0,0,46,28.76a1.57,1.57,0,0,0-.66-1.12A1.79,1.79,0,0,0,44,27.3a1.77,1.77,0,0,0-1.19.64,1.58,1.58,0,0,0-.38,1.24l.64,5.45a.91.91,0,0,1-.2.72,1,1,0,0,1-.69.35,1,1,0,0,1-.75-.18.92.92,0,0,1-.35-.65l-.64-5.44a3.36,3.36,0,0,1,.78-2.65,4,4,0,0,1,5.35-.63,3.51,3.51,0,0,1,.6,5.06,3.77,3.77,0,0,1-2.56,1.35A1,1,0,0,1,43.86,32.36ZM50.1,48.52a1,1,0,0,1-.69.34,3.76,3.76,0,0,1-2.79-.71,3.49,3.49,0,0,1-.6-5,3.76,3.76,0,0,1,2.55-1.34,1,1,0,0,1,.75.18.9.9,0,0,1,.36.65.88.88,0,0,1-.2.71,1,1,0,0,1-.69.34,1.76,1.76,0,0,0-1.19.64,1.59,1.59,0,0,0-.37,1.24,1.57,1.57,0,0,0,.65,1.12,1.77,1.77,0,0,0,1.31.34,1,1,0,0,1,.75.18.91.91,0,0,1,.36.65A.88.88,0,0,1,50.1,48.52ZM52,47.68a2.84,2.84,0,0,1-1.17-2l-.56-4.78a.92.92,0,0,1,.19-.71,1,1,0,0,1,.68-.35,1,1,0,0,1,.75.18.91.91,0,0,1,.36.65l.09.74,3.37-.4a1,1,0,0,1,.74.17.9.9,0,0,1,.35.64A.86.86,0,0,1,56,42.84l-3.37.4.26,2.17a1.07,1.07,0,0,0,.44.76,1.2,1.2,0,0,0,.88.23A1.17,1.17,0,0,0,55,46a1.08,1.08,0,0,0,.24-.84V45a.87.87,0,0,1,.21-.7,1,1,0,0,1,.68-.35,1,1,0,0,1,.74.18.89.89,0,0,1,.36.63v.13a2.86,2.86,0,0,1-.66,2.24,3.4,3.4,0,0,1-4.52.54Z"/></g></svg>
Again, the css should be extracted from here and into the proper style attribute on the page.

Let me know how you want to proceed. My vote is for the text one. It's got way fewer bytes and it can be i18n friendly.

**Comment by wouterj** [comment]
For the reference, a comparisation of the proposals:
![sf-exception-ghost](https://cloud.githubusercontent.com/assets/749025/18037035/e7dec3b4-6d7a-11e6-8d6b-d2737b36924e.png)

**Comment by nicolas-grekas** [comment]
Thank you @patrick-mcdougle ! I'll take the "paths" version, english is fine here (all exception messages are in english)

**Comment by Tobion** [comment]
I'd prefer Proposal 1 without font. The other text is really hard to read and seem blurry.

**Comment by apfelbox** [comment]
The fingers of the ghost got a bit thin. Would it be possible to make them a little bit thicker again?

**Comment by wouterj** [comment]
@Tobion that's mostly because of GitHub's upload restrictions. Do you have the same blurry experience when viewing [the vector](http://jsbin.com/qivotegiyi/3/edit?output)?

**Comment by Tobion** [comment]
Maybe not as bad. But still worse than the normal text. I don't see the point of using a custom font for that. The webprofiler doesn't use this font in any other place, does it?

**Comment by wouterj** [comment]
> I don't see the point of using a custom font for that. The webprofiler doesn't use this font in any other place, does it?

Please note that proposal 2 doesn't use a custom font. The font has been transformed into vector paths and are now rendered as just paths filled with white color.

The reason behind the custom font is because the original used this custom, Alba, font as well. For a design perspective, using a plain font doesn't look as nice. (the font is part of the cuteness imo).

For the reference, I'm +1 on proposal 2 as well.

**Comment by pborreli** [comment]
In proposal 2, you should add the double quotes to `style=width:112px` 
You should compress the svgs with svgo (web ui is available here https://jakearchibald.github.io/svgomg/)

**Comment by wouterj** [comment]
> In proposal 2, you should add the double quotes to style=width:112px 

It's just so people can see the actual image instead of just the svg code. I'm aware that it can be done a lot nicer (and should be done, by the one that's going to implement the svg).

Btw, it doesn't have to be quoted here: https://mathiasbynens.be/notes/unquoted-attribute-values :)

**Comment by nicolas-grekas** [comment]
SVGOMG applied in #19774, thanks for the link @pborreli

**Comment by fabpot** [comment]
Proposal 2 looks the best option to me.
