### ISSUE TITLE
Create Symfony version with type hint and strict types

### ISSUE THREAD

**Issue by Lisennk** [symfony/symfony#19762]
I think it's time to use PHP 7 features like strict types in new Laravel versions. Also you can transmit code via some compiler, that will produce PHP 5.6 compatible code as alternative.

**Comment by keyboardSmasher** [comment]
Yikes. People will be using 5.6 (forced via web hosts) until at least 2019.

It seems like a reasonable thing to do though. Clearing cache in production is already doing lots of "compiling".

**Comment by Lisennk** [comment]
Yes, if Symony will support 5.6 until, they will. But maybe you right, anyway, it's a good task  for the future.

**Comment by Ener-Getick** [comment]
@Lisennk it is not that easy, at first i don't see the benefits of using php7 features if we remove them with a transpiler. The biggest issue here is that symfony has a strict bc policy and it is not possible to change methods signature without a bc layer that we can't provide anyway as long as we support php5.
And even when symfony will only support php7 it will be hard to upgrade the current codebase, maybe only new features will benefit of strict typing.

**Comment by javiereguiluz** [comment]
@Lisennk thanks for proposing this! We know that PHP 7 is great and that PHP 5.X will be soon unsupported. However, as pointed by @Ener-Getick, this would be a brutal backwards compatibility break that goes against our [strict backwards compatibility promise](http://symfony.com/doc/current/contributing/code/bc.html). Si I must close this as "won't fix".

However, for Symfony 4.0, released in November 2017, we'll probably update the minimum PHP version required by Symfony ... probably to PHP 7. But we won't change the existing code, we'll just use that new PHP version for the new Symfony features.

**Comment by robfrawley** [comment]
@javiereguiluz: why would you make a point of staying you "won't change the code" for a release like 4.0? It would be wonderful for the framework to have the ability to enable strict signature definitions at some point.

**Comment by javiereguiluz** [comment]
@robfrawley it's just a personal opinion. During the 2.x to 3.x transition, we went from PHP 5.3 to 5.5. The result? We didn't change a single line of code: `array()` was still used instead of `[]`, we didn't replace FQCN by `::class`, etc. PHP 5.5 features are only used in the new code, not in the existing code. I'd expect the same to happen when we transition from PHP 5.x to 7.x.

**Comment by Lisennk** [comment]
@javiereguiluz, but what if `array()`, for example, will be deprecated some day in future?

**Comment by avierr** [comment]
> Yikes. People will be using 5.6 (forced via web hosts) until at least 2019.
> 
> It seems like a reasonable thing to do though. Clearing cache in production is already doing lots of "compiling".

it is 2019 now!

**Comment by fabpot** [comment]
Work on this has been started and will land partially in 4.4 and 5.0.
