### ISSUE TITLE
symfony/polyfill-mbstring You have requested a synthetic service ("request").

### ISSUE THREAD

**Issue by vortexgin** [symfony/symfony#19770]
I was update my dependency user composer and everything running well until i'm open the website. 

The only one dependency that i used just symfony/polyfill-mbstring doing download update.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Analyzed 9467 packages to resolve dependencies
Analyzed 606436 rules to resolve dependencies
  - Installing symfony/polyfill-mbstring (dev-master 988cbed)
    Downloading
    Extracting archive

  - Installing twig/twig (1.x-dev ffa2b81)
    Loading from cache
    Extracting archive
```

After I open the website, show error like this : 

```
2016/08/29 11:12:25 [error] 718#0: *467111 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'You have requested a synthetic service ("request"). The DIC does not know how to construct this service.' in /path_to/app/cache/prod/appProdProjectContainer.php:1961
Stack trace:
#0 /path_to/app/bootstrap.php.cache(2221): appProdProjectContainer->getRequestService()
#1 /path_to/app/cache/prod/appProdProjectContainer.php(3506): Symfony\Component\DependencyInjection\Container->get('request', 2)
#2 /path_to/app/bootstrap.php.cache(2157): appProdProjectContainer->synchronizeRequestService()
#3 /path_to/app/bootstrap.php.cache(3360): Symfony\Component\DependencyInjection\Container->set('request', NULL, 'request')
#4 /path_to/app/bootstrap.php.cache(2535): Symfony\Component\Ht...
PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'You have requested a synthetic service ("request"). The DIC does not know how to construct this service.' in /path_to/app/cache/prod/appProdProjectContainer.php:1961
```

**Comment by HeahDude** [comment]
What is the symfony version? Have you tried clear the cache manually? Does it work in dev environment?

Maybe one of your dependency package is using the deprecated `request` service instead of the `request_stack` and should be updated too.

**Comment by vortexgin** [comment]
I'm using Symfony 2.8. I have tried clear cache manually also remove eveything under app/cache folder. I have tried on dev environment too and it doesn't work.

If i check my composer log, only symfony/polyfill-mbstring (dev-master 988cbed) that doing download update.

**Comment by javiereguiluz** [comment]
@vortexgin at firt sight this error should be unrelated to `polyfill-mbstring`. Can you please double check that your application services don't use `request` as their arguments. Thanks!

**Comment by vortexgin** [comment]
I'm already found dependency that makes bug. thanks for the clue

**Comment by scragg0x** [comment]
@vortexgin which dependency was it?

**Comment by dmeziere** [comment]
+1 Just trying to run the deploy script on an active app broke everything. Needed to roll-back. The developers won't like it :) If anyone have a patch it would save them time.

**Comment by vortexgin** [comment]
@scragg0x : suncat mobile detect bundle was the problem, i have contact the admin & he has update the repository.

**Comment by dmeziere** [comment]
I can deliver again. The problem (wherever it comes from) seems closed.
