### ISSUE TITLE
A render_esi call it's marked as main request with varnish ahead

### ISSUE THREAD

**Issue by giovannialbero1992** [symfony/symfony#19775]
I've noticed a strange behaviour with my symfony's project on render_esi call.
I've a listener on kernel request that on `$event->isMasterRequest()` associated to render_esi returns true.

So I've done 3 projects clean (`2.7.11`, `2.8.9`, `3.1.3`) and I've the same problem.
In the listener I've used `dump` to see the order of requests.
```
dump($request->getUri());
dump($event->isMasterRequest());
```
I expected
```
https://local.test.com
```
```
true
``` 
```
https://local.test.com/_fragment?_hash=MBduZlawyGueqXZnsfQeSh0INVclSs2AV5luErGe3Qk%3D&_path=_format%3Dhtml%26_locale%3Den%26_controller%3DAppBundle%253ADefault%253ArenderEsi
```
```
false
```

 But I have only

```
https://local.test.com/_fragment?_hash=MBduZlawyGueqXZnsfQeSh0INVclSs2AV5luErGe3Qk%3D&_path=_format%3Dhtml%26_locale%3Den%26_controller%3DAppBundle%253ADefault%253ArenderEsi
```
```
true
```

thanks in advance

**Comment by stof** [comment]
This is expected, as it is a request reaching the Symfony app from the outside.

not getting the ``https://local.test.com`` URI indicates that Varnish already had it in the cache

**Comment by giovannialbero1992** [comment]
Thanks a lot @stof ! I've overridden `Symfony\Component\HttpKernel\EventListener\FragmentListener` and marked a request as `esi` into attributes to resolve my problem. Thanks again

**Comment by HeahDude** [comment]
Can we close here?
