### ISSUE TITLE
Support for PHP 7.1 nullables

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#19771]
This is an excerpt from the #19677.

The upcoming PHP 7.1 will add support for nullable types. So the function declarations in php 7.1 won't need a default null parameter e.g `\StdClass $foo = null` but could be written as   `?\StdClass $fool`.

I'm assuming that there are a lot of argument resolvers  e.g controller argument resolver, DI, .. inside a Symfony which would complain or throw an exception on new declaration. The new version will be released around the symfony 3.2 release so this would fit nicely together.

**Comment by iltar** [comment]
Right now the builds are being tested on 7.1 so it's at least backwards compatible for now. I'll see if I can add a test-case for 7.1.

**Comment by dunglas** [comment]
There is probably some work to do in the PropertyInfo component to support this new feature.

**Comment by iltar** [comment]
I could have a look at it but that's a bit beyond my expertise ^^

**Comment by dunglas** [comment]
IIUC, it doesn't change the reflection API and `ReflectionParameter::allowsNull()` will return true if `null` is allowed using the new notation. So we don't have to change anything.

**Comment by iltar** [comment]
Previously it would return true if the signature had `= null` as default value so it might have some behavioral changes when called manually: [`(?string $value)`][1], [`(?string $value= 'value')`][2]

[1]: https://3v4l.org/FiLKN
[2]: https://3v4l.org/dsPU0
