### ISSUE TITLE
keep throwing an exception when impersonating with username having '+' included

### ISSUE THREAD

**Issue by jerryladoo** [symfony/symfony#19791]
when I impersonated with username `jerry+123@gmail.com`, it kept saying 'You are already switched to "jerry+123@gmail.com" user', which caused by the `if` statement at line 121 in SwitchUserListener.php

```
...
if ($token->getUsername() === $request->get($this->usernameParameter)) {
    return $token;
}
throw new \LogicException(sprintf('You are already switched to "%s" user.', $token->getUsername()));
...
```

the $token->getUsername() returned correct value, `jerry+123@gmail.com`, but $request->get($this->usernameParameter) returned something like this `jerry 123@gmail.com`

The version currently used is 2.7, but I have checked the latest versoin, there is same code in same place, any ideas guys?

**Comment by iltar** [comment]
This is probably because the email is passed as get argument, which converts the + to a space.

**Comment by weaverryan** [comment]
Yea, try %2B in the URL instead of the plus sign - it's exactly as @iltar said: the + is understood to be a space in the URL.

We actually switch users that have a + in them in our knpu vids and it *does* work - once you use %2B.

Closing unless some other info comes up!

Cheers!
