### ISSUE TITLE
Too much right margin on toolbar without route

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#19805]
When there is no route, e.g. a 404 page, the route item is not shown in the toolbar. This results in too much right margin in the status item:

![sf-toolbar-wrong-margin](https://cloud.githubusercontent.com/assets/749025/18132645/ecf80e86-6f97-11e6-9d5d-45465ed3a899.png)

**Comment by javiereguiluz** [comment]
I can confirm this issue. Wouter, thanks for reporting it.
