### ISSUE TITLE
[Yaml] Excessive quoting when dumping string values

### ISSUE THREAD

**Issue by stefk** [symfony/symfony#19800]
The [regex](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Escaper.php#L85) used to decide whether a dumped string must be single-quoted has several issues:

```
/[ \s \' " \: \{ \} \[ \] , & \* \# \?] | \A[ \- ? | < > = ! % @ ` ]/x
```
- the `x` modifier doesn't ignore spaces inside a character class ([doc](http://php.net/manual/en/reference.pcre.pattern.modifiers.php))
- the `\s` makes any string containing a space a match for single-quoting
- `'` and `"` aren't in the list of characters requiring quoting ([doc](http://symfony.com/doc/current/components/yaml/yaml_format.html#strings))

The result is that after a dump, almost _every_ translation is single-quoted, which is undesirable.

Changing the regex to:

```
/["\:\{\}\[\],&\*\#\?]|\A[\-?|<>=!%@`]/
```

seems to fix most issues, but this requires further investigation and testing. I'm open to sending a PR if there's an interest.

**Comment by Ener-Getick** [comment]
see https://github.com/symfony/symfony/pull/19782 :)

**Comment by stefk** [comment]
Thanks for the link.

> We do need to quote any scalar containing spaces as those spaces wouldn't be saved in some cases by the parser 

I don't see how the parser could be involved at this stage. Shouldn't taking care of leading/trailing spaces (and special characters/expressions) be enough for the dumper?

> For your last point, it's more a documentation problem than a real problem in the code.

I don't think so. It seems those characters are perfectly valid in unquoted strings:

http://yaml.org/spec/1.2/spec.html#id2788859
http://yaml-online-parser.appspot.com/?yaml=foo%3A+ba%22r%0Abaz%3A+q%27u%27x%27%0A&type=canonical_yaml

**Comment by Ener-Getick** [comment]
> I don't see how the parser could be involved at this stage. Shouldn't taking care of leading/trailing spaces (and special characters/expressions) be enough for the dumper?

Because of bc, [spaces are not supported in unquoted keys](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Inline.php#L460).
And if we really want to be precise, we should only quote scalars when they begin or end with spaces.

> I don't think so. It seems those characters are perfectly valid in unquoted strings:

Alright, then quotes should be moved to indicators.

**Comment by stefk** [comment]
> Because of bc, spaces are not supported in unquoted keys.

Ok, my bad, I only thought of values, not keys. The fact that the same methods are used for escaping both complicates the issue.

**Comment by Ener-Getick** [comment]
You're not totally wrong, it should work but it's a current limitation of the Parser.

**Comment by Ener-Getick** [comment]
After all [that was easier to fix than I thought](https://github.com/symfony/symfony/pull/19750/commits/51b87f7a3a103ee8e8e0be3d767394c20ef476ff) but I don't think we should rely on that to generate Yaml as it has to work on older versions as well imo.

**Comment by HipsterJazzbo** [comment]
I'm just going to throw a +1 in here for fixing this in relation to keys. Keys do not need to be quoted if there are spaces, and it's actually a fairly big deal if you're using YAML as a format for use by non-technical people.

**Comment by xabbuh** [comment]
I am going to close here as I don't see this happening anytime soon in the future. Of course, if someone wants to give it a try, I am open to review a PR doing such a change in a simple way.
