### ISSUE TITLE
[LDAP] Warning: Illegal string offset 'count' 

### ISSUE THREAD

**Issue by elementaire** [symfony/symfony#19804]
Hey,

First of all, I am using Symfony version 3.1.3 and the LDAP Component.

When i use the native PHP `var_dump(ldap_get_entries(...))`, I get this kind of data :

```
array (size=29)
  'count' => int 28
  0 => 
    array (size=114)
      'objectclass' => 
        array (size=5)
          'count' => int 4
          0 => string 'top' (length=3)
          1 => string 'person' (length=6)
          2 => string 'organizationalPerson' (length=20)
          3 => string 'user' (length=4)
      0 => string 'objectclass' (length=11)
      'cn' => 
        array (size=2)
          'count' => int 1
          0 => string 'John DOE' (length=13)
      1 => string 'cn' (length=2)
      [...]
```

With using LDAP Component, i got a `Warning: Illegal string offset 'count' ` in `vendor/symfony/symfony/src/Symfony/Component/Ldap/LdapClient.php` at line `75`. It throws it as an exception.

The component seems to expect `$resultAttribute` (`$values`) to be an array. But in my example, it is not always the case (`0 => string 'objectclass' (length=11)`, etc.).

Is a flaw/bug of the component itself or the data returned by my LDAP server are invalid ?

ping @csarrazi

**Comment by csarrazi** [comment]
Hi @elementaire, could you provide a small snippet (anonymised, of course), with the actual code that you are running?

Could you also specify which version of PHP you are using?

Thanks!

**Comment by elementaire** [comment]
Hi @csarrazi,

I am using `PHP 5.6.11-1ubuntu3.4`.

In a controller, i have this method :

```php
/**
 * @Route("/test", name="test")
 */
public function testAction()
{
	$config = $this->getParameter('ldap');
	
	$client = new \Symfony\Component\Ldap\LdapClient($config['host']);
	$client->bind($config['dn'], $config['password']);

	$data = $client->find($config['baseDn'], '(&(objectClass=person)(sAMAccountName=johndoe))');

	dump($data);

	return $this->render('@App/Default/index.html.twig');
}
```

If the user `johndoe` exists : `Warning: Illegal string offset 'count'` in `vendor/symfony/symfony/src/Symfony/Component/Ldap/LdapClient.php` at line `75`

Otherwise : `Could not rewind entries array: Success` in `vendor/symfony/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/ResultIterator.php` at line `78`

Thanks!

**Comment by csarrazi** [comment]
Indeed, this seems like a bug in the component. This means that we need to check whether each key is actually an array or not, and choose a different strategy depending on the type of value we receive from the native php function.

The rewind issue is another thing. I'll investigate into this.

**Comment by elementaire** [comment]
Do you need additional information to fix it ?

For the second warning, i get this data from the `print_r(ldap_get_entries(...))` :
```
Array
(
    [count] => 0
)
```
Do you want I open a new issue for the second warning ?

I guess, we can update the status of this one.

Status: Reviewed

**Comment by csarrazi** [comment]
@elementaire Ok, the 2nd issue is linked to an edge case with receiving no result from the query.

Regarding the first issue, it seems that there's either a problem with https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Adapter/ExtLdap/Collection.php#L110 or with https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/LdapClient.php#L61

Could you check the results of $query->execute() at line 66 of LdapClient? https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/LdapClient.php#L66

Thanks.

**Comment by elementaire** [comment]
Thanks @csarrazi, i checked and tested a lot based on your idea in order to understand the issue.

I came to this inconstancy in the way to cleanup attributes between https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Adapter/ExtLdap/Collection.php#L110 and https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Adapter/ExtLdap/ResultIterator.php#L40

**So, the first code removes all the numeric keys sent by some LDAP (good idea i guess) whereas the second does not.**

I compared this following code with what `foreach` using in the `find()` method of `LdapClient` class.
```php
$query->execute()->toArray();
```

**Comment by csarrazi** [comment]
Indeed, the issue seems to come from the ResultIterator, which does not filter the fields. This actually makes me wonder why I made `CollectionInterface` implement ArrayAccess...
I guess this logic should be moved in the ResultIterator class instead.

**Comment by bjoernHeneka** [comment]
I've got the exact same problem. The response I got from:
```
dump($entry->getAttributes());
```

Looks like: 
```
array:23 [▼
  "userPassword" => array:2 [▼
    "count" => 1
    0 => "{SSHA}uOm82L2kmsQu19zAJShefpa8p3JhSzY1NTdkODNlYWE3MDdlMg=="
  ]
  0 => "userPassword"
  "cn" => array:2 [▼
    "count" => 1
    0 => "user"
  ]
  1 => "cn"
  "email" => array:2 [▶]
  2 => "email"
  "member" => array:7 [▶]
  3 => "member"
  "objectClass" => array:3 [▶]
  4 => "objectClass"
  "uid" => array:2 [▶]
  5 => "uid"
  "uidNumber" => array:2 [▶]
  6 => "uidNumber"
  "isAdmin" => array:2 [▶]
  7 => "isAdmin"
  "isSuperadmin" => array:2 [▶]
  8 => "isSuperadmin"
  "isEnabled" => array:2 [▶]
  9 => "isEnabled"
  "creationDate" => array:2 [▶]
  10 => "creationDate"
  "count" => 11
]
```

Maybe it can help a bit.

**Comment by csarrazi** [comment]
Thanks @bjoernHeneka. This confirms that the issue is the filtering, which is not done when using the ResultIterator. This can be fixed pretty easily.

**Comment by bjoernHeneka** [comment]
Sound great @csarrazi 
Can i do sth. that it will work until the fix is available?
I'm using symfony 2.8.11

**Comment by csarrazi** [comment]
Instead of using the result collection's `getIterator()` function when doing a `foreach ($result as $entry)`, try using the `toArray()` function.

E.g. 

```php
foreach ($result->toArray() as $entry) {
    // ...
}
```

**Comment by bjoernHeneka** [comment]
Ok. Maybe it's a stupid question and i don't get sth. But I'm using the LdapClient from LdapComponent.
The way described here: http://symfony.com/doc/current/security/ldap.html

I'm not iterating through the results at all. It is done by the LdapClient,.

**Comment by csarrazi** [comment]
Don't worry, there are no stupid questions, especially since the doc for the component is currently outdated (most of the security doc is okay, just not the Ldap-specific part of the documentation as the component has received a major refactoring in Symfony 3.1).

Actually, you should use the `Ldap` class instead of the `LdapClient` class, which is there for backward-compatibility with Symfony 2.8 and 3.0.

You should do something like

```php
$options = [
    'host' => $config['host'],
];
$ldap = Ldap::create('ext_ldap', $options);
$ldap->bind($config['dn'], $config['password']);
$query = $ldap->query($config['baseDn'], '(&(objectClass=person)(sAMAccountName=johndoe))');

$results = $query->execute();
dump($results->toArray());
```

**Comment by csarrazi** [comment]
@bjoernHeneka @elementaire Could you check whether my fork works correctly with your code? Normally, I should have fixed all potential issues with the `LdapClient::find()` method.

**Comment by elementaire** [comment]
Hey @csarrazi,

It is ok for me for the main issue.

About the edge case, I still get the error.

In https://github.com/csarrazi/symfony/blob/fix/ldap-wrong-attribute-format/src/Symfony/Component/Ldap/Adapter/ExtLdap/Collection.php#L51 and https://github.com/csarrazi/symfony/blob/fix/ldap-wrong-attribute-format/src/Symfony/Component/Ldap/Adapter/ExtLdap/Collection.php#L94, the strategy to iterate the data are not the same.

With using ldap_first_entry() function, you can't distinguish the difference between no data and an error, so the exception is always sent when the query returns no data.

**Comment by csarrazi** [comment]
Hi @elementaire I just pushed a new version. Everything should work as intended, now.

**Comment by csarrazi** [comment]
Thanks for your help with this issue, by the way!

**Comment by elementaire** [comment]
@csarrazi No more error but the data are not identical between API, is this normal?

**Old way:**

````php
<?php
/**
 * @Route("/test", name="test")
 */
public function testAction()
{
	$config = $this->getParameter('ldap')['auth'];
	$client = new \Symfony\Component\Ldap\LdapClient($config['host']);

	$client->bind($config['dn'], $config['password']);
	$data = $client->find($config['baseDn'], '(&(objectClass=person)(sAMAccountName=johndoe))');
	
	dump($data);
	
	return new \Symfony\Component\HttpFoundation\Response;
}
````

Prints if the user exists: 

```
DefaultController.php on line 36:
array:2 [▼
  "count" => 1
  0 => array:94 [▼
    "objectclass" => array:5 [▶]
    0 => "objectclass"
    "cn" => array:2 [▶]
    1 => "cn"
    "sn" => array:2 [▶]
    2 => "sn"
```

Otherwise:

```
DefaultController.php on line 36:
array:1 [▼
  "count" => 0
]
```

**New way:**

````php
/**
 * @Route("/test2", name="test2")
 */
public function test2Action()
{
	$config = $this->getParameter('ldap')['auth'];

	$options = [
		'host' => $config['host'],
	];

	$ldap = \Symfony\Component\Ldap\Ldap::create('ext_ldap', $options);
	$ldap->bind($config['dn'], $config['password']);

	$query = $ldap->query($config['baseDn'], '(&(objectClass=person)(sAMAccountName=johndoe))');

	$results = $query->execute();
	dump($results->toArray());
	
	return new \Symfony\Component\HttpFoundation\Response;
}
```

Prints if the user exists (note the `Entry` class and the missing of numeric keys):

```
array:1 [▼
  0 => Entry {#3777 ▼
    -dn: "CN=John DOE,OU=DIJ,OU=Users,OU=AOG,DC=aog,DC=priv"
    -attributes: array:46 [▼
      "objectClass" => array:4 [▶]
      "cn" => array:1 [▶]
      "sn" => array:1 [▶]
```

Otherwise: 

```
[]
```

Thanks for fixing the issue, by the way! ;)

**Comment by csarrazi** [comment]
@elementaire The old / new APIs not returning the same thing is normal. One thing to note is that the `LdapClient` class also exposes the `query()` method, and implements both the legacy and the new Ldap interfaces, so you can use the same API with both the `Ldap` class and the `LdapClient` class, only the `Ldap` class won't expose a `find()` method.

The new way is much cleaner, and actually abstracts the actual implementation. The goal of the new version was to be able to be independent from the library used in the background. This means that you can potentially write your own adapter for another LDAP implementation (a pure userland implementation, for example, instead of relying on PHP's `ldap` extension, or even wrap another library (like ZendLdap)).

Currently, the reference implementation is `ext_ldap`, which is based on PHP's `ldap` extension.

**Comment by csarrazi** [comment]
To be clearer regardless of the class that you use (`Ldap` or `LdapClient`), you can do:

```php
// $client = ...

$client->bind($config['dn'], $config['password']);
$query = $ldap->query($config['baseDn'], '(&(objectClass=person)(sAMAccountName=johndoe))');

$results = $query->execute();
dump($results->toArray());
```

The `LdapClient` is here for backward compatibility with Symfony 2.8 and 3.0.

**Comment by csarrazi** [comment]
Another thing, in earlier versions, the `find()` method simply returned the output of PHP's `ldap_search()` function, which is pretty dirty (`count` elements for each array level, as well as numeric keys, which only contain the field names and, for some completely unknown reason, are lowercase unlike the output of `ldap_get_attributes()`...

**Comment by elementaire** [comment]
Ok. So this is normal ; i guess the fix is perfect.

**Comment by bjoernHeneka** [comment]
@csarrazi I was in vacation. Just updated the new symfony version and it works fine. Thanks a lot for your help.

**Comment by csarrazi** [comment]
You're welcome! :)
