### ISSUE TITLE
Symfony Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [symfony/symfony#19808]
Dear **Symfony** contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, [truck factor](https://en.wikipedia.org/wiki/Bus_factor) (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”. By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of **Symfony**?

2) Who are the developers responsible for this truck factor estimation?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by HeahDude** [comment]
Hi @2mferreira that's a funny way to approach a problem, I'd say at least [1556](http://symfony.com/contributors) :)

**Comment by iltar** [comment]
Actually, if the whole core team gets hit by a truck, we can only work with forks, which causes serious troubles in the framework as nothing gets officially fixed anymore ;)

**Comment by alexbridge** [comment]
1. **Symfony** is a framework. Building a **Project** is how team members are using it. According to [Wiki](https://en.wikipedia.org/wiki/Bus_factor) "Bus Factor" is " a measurement of the concentration of information in individual team members". That means its nothing about Software at all. Its only about members, being long with this Project.

2. As is mentioned **Symfony** is a framework. Estimation of **Bus factor** can be done in **Project context**.

Best

**Comment by javiereguiluz** [comment]
@2mferreira we have:

* 1 admin/leader
* ~15 members of the Core Team
* Tens of regular contributors, triagers, etc.
* Hundreds of ocasional contributors.

I'd say the "truck factor" would be between 16 and 40.

Resources:

* Symfony Core Team: http://symfony.com/doc/current/contributing/code/core_team.html
* Symfony GitHub Teams: https://github.com/orgs/symfony/teams

**Comment by nicolas-grekas** [comment]
Since there are much more people out of the core team that could take over, I'd say TF>15.

**Comment by nicolas-grekas** [comment]
It also depends on what you mean by "serious troubles". If fab were hit by a truck, we could consider Symfony in serious trouble. But the project could still recover.

**Comment by HeahDude** [comment]
I truly think the point of open-source and forking on Github, is that a project never really dies unless everyone stops using it.

**Comment by COil** [comment]
Therefore, I would suggest to forbid the core team to take the bus or plane together ! :smile:

**Comment by fabpot** [comment]
Closing now.
