### ISSUE TITLE
Uncaught exception 'ErrorException' under HHVM in PHP7 mode

### ISSUE THREAD

**Issue by photodude** [symfony/symfony#19810]
Doing some testing with [Travis CI with HHVM in PHP7 compatibility mode](https://travis-ci.org/photodude/joomla-cms/jobs/156689060). I get the following error that seems to be coming from the [symfony console](https://github.com/symfony/console)

```php
Fatal error: Uncaught exception 'ErrorException' with message 'proc_open() expects parameter 4 to be string, null given' in phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:954
Stack trace:
#0 (): Composer\Util\ErrorHandler::handle()
#1 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(954): proc_open()
#2 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException()
#6 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run()
#7 phar://composer.phar/bin/composer(43): Composer\Console\Application->run()
#8 /home/travis/.phpenv/versions/hhvm-stable/bin/composer(24): include()
#9 {main}
```

**Comment by jameshalsall** [comment]
This seems like a bug in HHVM rather than Symfony, it's passing `null` which is a valid value..

From the [PHP docs](http://php.net/proc_open)
> The initial working dir for the command. This must be an absolute directory path, or NULL if you want to use the default value (the working dir of the current PHP process)

**Comment by photodude** [comment]
Thanks I overlooked that the error was coming from a PHP function. I have opened an [issue with HHVM](https://github.com/facebook/hhvm/issues/7306) for this since it should work with null (irregardless of whether the compatibility mode is set for php5 or php7. 

Closing this issue as HHVM specific

**Comment by photodude** [comment]
I will note that this issue is new, [checking past tests](https://travis-ci.org/photodude/joomla-cms/jobs/155839085) this error did not exist. We are still testing on the same version of HHVM 3.12.8 or 3.14.5 

same version of composer and same version of symfony console.
