### ISSUE TITLE
Little PHPDocs correction

### ISSUE THREAD

**Issue by EarthDweller** [symfony/symfony#19821]
[https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L454](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L454)

`Response->setStatusCode()` is also used in:
1. RedirectResponse
2. JsonResponse
3. StreamedResponse
4. BinaryFileResponse

But in PHPDocs written `@return Response` >> appears some warnings in IDE
Must be:
`@return static`
or
`@return Response|RedirectResponse|JsonResponse|StreamedResponse|BinaryFileResponse`

**Comment by iltar** [comment]
In this case I would say `@return $this`

**Comment by EarthDweller** [comment]
> In this case I would say @return $this
Right, RedirectResponse->setStatusCode() can't return BinaryFileResponse

**Comment by iltar** [comment]
When using `return $this` in your code, you can add `@return $this` in your docblock, which is done in other locations as well.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #21054.
