### ISSUE TITLE
(Cache) Redis Adapter should retrieve the expiration time

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony#19823]
Hello,

I'm experiencing issues when using the Redis PSR-6 adapter for a specific use case.
When storing a key-value pair into the redis server, we can specify the TTL, in other words, how long will the key will live in the cache.

My use case is to create a buffer to connect to external APIs which limit the amount of requests for a defined  period. For example, I have to send 100+ requests to an API that restrict to 35 requests per minute (yes... some partners I work with do that).

With Redis I can do the following:
```php
$redis             = new Redis();
$bufferKey         = 'api.current.requests';
$bufferExpiresIn   = 60;
$bufferMaxRequests = 35;

$redis->connect('127.0.0.1');

for ($i=1; $i <= 100; $i++) {

    if (!$redis->exists($bufferKey)) {
        $redis->set($bufferKey, 1, $bufferExpiresIn);
    }
    else {

        CheckBufferOverLoad:
        $value = $redis->get($bufferKey);
        if ($value >= $bufferMaxRequests) {
            sleep(1);
            goto CheckBufferOverLoad; // Yeah, I know you love gotos :-)
        }

        else {
            $redis->incr($bufferKey);
        }
    }
    
    // Call API

}
```
This works pretty well, but I love abstractions.

So here's the same code, translated with Symfony's Redis PSR-6 Adapter:
```php
use Symfony\Component\Cache\Adapter\RedisAdapter;
use Symfony\Component\Cache\CacheItem;

$redis             = new Redis();
$adapter           = new RedisAdapter($redis);
$bufferKey         = 'api.current.requests';
$bufferExpiresIn   = 60;
$bufferMaxRequests = 35;

$redis->connect('127.0.0.1');

function initItem(RedisAdapter $adapter, CacheItem $item, $bufferExpiresIn) {
    $item->set(1);
    $item->expiresAfter($bufferExpiresIn);
    $adapter->save($item);
}

function incrementItem(RedisAdapter $adapter, CacheItem $item) {
    $value = (int) $item->get();
    $item->set($value + 1);
    $adapter->save($item);
}

for ($i = 1; $i <= 100; $i++) {

    $item = $adapter->getItem($bufferKey);

    if (!$item->isHit()) {
        initItem($adapter, $item, $bufferExpiresIn);
    }
    else {

        CheckBufferOverLoad:
        $item  = $adapter->getItem($bufferKey);
        $value = (int) $item->get();

        if ($item->isHit()) { // Buffer still exists
            if ($value >= $bufferMaxRequests) {
                sleep(1);
                goto CheckBufferOverLoad; // Don't panic, gotos are just for this example
            }

            else {
                incrementItem($adapter, $item);
            }
        }

        else { // Buffer has been reinitialized
            initItem($adapter, $item, $bufferExpiresIn);
        }

    }

    // Call API

}

```

This doesn't work the same way, because when the adapter hits the cache, the retrieved item knows nothing about the original expiration time. When calling `$cache->save($item)`, the expiration time is reset, resulting in an infinite loop when reaching the `sleep(1);` statement (the value is always incremented, never reset to 1).

**Comment by nicolas-grekas** [comment]
The behavior you're asking for can't be added to the Cache component, because it is not PSR-6 compliant. If we were to add it anyway, it'd mean you'd bind your implementation to the specific behavior of this redis adapter. Defeats the purpose of interop again.

Can't you instead add the TTL/timespamp in the cached value and manage it from there?

**Comment by bpolaszek** [comment]
Hello Nicolas,

I'm not sure this is not PSR-6 compliant, since the PSR-6 provides the ability, for a cached item, to specify its expiration time.

Actually I've created another adapter that does the job, have a look at it:
https://github.com/bpolaszek/redis-psr6-ttl-aware-adapter

It's just a simple override of `Symfony\Component\Cache\Adapter\RedisAdapter`, hydrating the CacheItem `$expiry` property on `getItem($key)`:
https://github.com/bpolaszek/redis-psr6-ttl-aware-adapter/blob/master/src/RedisTTLAwareAdapter.php#L37

With this simple addition, this adapter does the job as expected.

**Comment by nicolas-grekas** [comment]
> this adapter does the job as expected

As *you* expect :)
Psr6 cache items are actual objects the are destroyed after use, not the abstract concept that survives through the persistence layer.

**Comment by bpolaszek** [comment]
> As *you* expect :)

Ofc, that's what I meant :) 
But at first glance, I don't see a BC break on this.

> Psr6 cache items are actual objects the are destroyed after use, not the abstract concept that survives through the persistence layer.

Does that mean a `isHit() === true` CacheItem object is doomed to never be saved again?
I'm not sure of this. 

IMO if this object is saved again, it shouldn't set a default expiry time to 0, but the original one.

When I just call 
```php
$item->set($myNewValue);
// I don't want to change expiry
$cache->save($item);
```

I don't understand the really expected behaviour is 
```php
$item->set($myNewValue); 
$item->expiresAfter(0); // this is implicitely done behind the scenes
$cache->save($item);
```

Maybe the PSR-6 rules are ambiguous at that point, or is there something I didn't read correctly?

**Comment by nicolas-grekas** [comment]
> IMO if this object is saved again, it shouldn't set a default expiry time to 0, but the original one (when available).

That's what you'd like yes, but PSR-6 doesn't specify it, which means you can't rely on this behavior when having interpo in mind.

> I don't want to change expiry

then store it as a value and deal with it in your code, that would work fine I guess.

> Maybe the PSR-6 rules are ambiguous at that point, or is there something I didn't read correctly?

They are not: they don't tell, which means you should not rely on some behavior that is not enforced by the spec.

**Comment by bpolaszek** [comment]
All right, I understand your point.

> then store it as a value and deal with it in your code, that would work fine I guess.

Actually it doesn't, since the value may have been set up by another PHP process - that's the purpose of a shared cache handler like Redis :)

Besides, dealing with the expiration time as another key-value pair in another Cache pool adds a layer of complexity and dependency, where, *to my eyes*, the PSR-6 `expiresAfter` already provide a solution out-of-the box, without needing to rely on a specific adapter or implementation. 

Considering the ambiguity of *should we reset the expiration time* or *should we fetch the original expiration time* in the PSR-6, I know understand this is not an omission in the code but rather a position.

I respect this and thus won't interfere any longer :)

Thanks for your explanations.

Have a nice day,
Ben
