### ISSUE TITLE
[2.7.17] You have requested a synthetic service ("request")

### ISSUE THREAD

**Issue by chandon** [symfony/symfony#19825]
I just have updated from 2.7.16 ot 2.7.17

My project doesn't work anymore (DEV or PROD environment)

    RuntimeException in appDevDebugProjectContainer.php line 5493

    in appDevDebugProjectContainer.php line 5493
    at appDevDebugProjectContainer->getRequestService() in bootstrap.php.cache line 2189
    at Container->get('request', '2') in appDevDebugProjectContainer.php line 8559
    at appDevDebugProjectContainer->synchronizeRequestService() in bootstrap.php.cache line 2125
    at Container->set('request', null, 'request') in bootstrap.php.cache line 3270
    at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2479
    at Kernel->handle(object(Request)) in app_dev.php line 30

Downgrading to 2.7.16 solves the problem

**Comment by chandon** [comment]
Seems that the problem was linked to an external package. Updating the package solves the problem, but this BC seems quite strange (even if the package was faulty)

**Comment by scragg0x** [comment]
@chandon which package did you have to upgrade?

**Comment by chandon** [comment]
@scragg0x It was "suncat/mobile-detect-bundle": "dev-master#d800c7590aac32d72cf05a88334d1f3f312888a6"

I updated it to  "suncat/mobile-detect-bundle": "1.*"

**Comment by opichon** [comment]
It seems tied to an external package, but how can we find out which one? The error message is cryptic to say the least.

**Comment by nicolas-grekas** [comment]
See #19847

**Comment by manuelDistefano** [comment]
Downgrade to 2.7.16 solve the problem for me.

**Comment by omarboussarsar** [comment]
I solve the problem by downgrading to 2.7.16 also.

**Comment by scragg0x** [comment]
In my case, downgrading to 2.7.16 did not help me.  To find out what is causing the issue, look at the `bootstrap.php.cache` and look where `synchronizeRequestService` is being called per the exception.  It should have the offending services / 3rd party libs.  For me it was monolog with a particular configuration, there is an open issue on their repo on it.
