### ISSUE TITLE
Abandon the propel1 bridge on packagist

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#19833]
I think because of #13656, [symfony/propel1-bridge](https://packagist.org/packages/symfony/propel1-bridge) should be abandoned on packagist in favor of [propel/propel-bundle](https://packagist.org/packages/propel/propel-bundle).

**Comment by jakzal** [comment]
:+1:

**Comment by xabbuh** [comment]
👍 

ping @fabpot

**Comment by fabpot** [comment]
Done
