### ISSUE TITLE
[QUESTION] AsseticBundle

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#19835]
Sorry if my question is not related with Symfony because after 2.7 AsseticBundle is dropped from Symfony dependencies.

I just want to ask who are maintaining AsseticBundle? Because i saw nothing activity in github repository.

The issue is not replied any more but the documentation is exist in official symfony.

Thank you for the reply and sorry for my bad english

**Comment by fabpot** [comment]
Thanks for your feedback. As you noticed, AsseticBundle is in a different repository. It's not maintained by the Symfony core team, so I don't really know what's going on there. You should open an issue on the AsseticBundle instead. Thanks.
