### ISSUE TITLE
[ClassLoader] ClassCollectionLoader cache file not compatible with declare directives

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#19845]
Adding a file containing a `declare` directive to the classes cache, the directive is printed as-is, making the directive valid for all classes declared after that.
Also when using `declare(strict_types=1)` in PHP 7, the generated `classes.php` throws a `FatalErrorException` when loaded as the "strict_types declaration must be the very first statement in the script".

**Comment by nicolas-grekas** [comment]
AFAIK, there is no way in PHP 7 to make a `declare(strict_types=1)` apply to a single class in a file where several ones are declared.
Thus, this is a limitation we can't fix.
Or has someone an idea how to do so?

**Comment by Nicofuma** [comment]
At least we could not dump the `declare(strict_types=1)` line in order to generate a valid PHP file

**Comment by alekitto** [comment]
Or we can generate a file for strict declared classes only, that should be required at the bottom of the `classes.php` file...

However the issue refers to `declare(ticks=n)` directive also, as writing it as a block is not the same as the non-block directive (http://php.net/manual/en/control-structures.declare.php#88929).

Maybe we can just skip those files containing a `declare`? Or throw an exception?

**Comment by nicolas-grekas** [comment]
Why adding complexity/wtf in ClassCollectionLoader (why the hell isn't this class inlined while I asked for it to be??), can't you just *not* list the class for inlining?

**Comment by nicolas-grekas** [comment]
> we can generate a file for strict declared classes only

unfortunately that won't work wen inheritance will come into play (parent classes must be declared first)...

**Comment by alekitto** [comment]
If the only solution is to not inline those files, I think it should be documented somewhere at least...

**Comment by nicolas-grekas** [comment]
I forgot about block notation.
This is possible:
```
namespace {
    declare(ticks = 1) {
        class foo
        {
        }
    }
}
```

So, it's just a fix away, if someone wants to give it a try.

**Comment by nicolas-grekas** [comment]
Hell, no: `strict_types declaration must be the very first statement`

**Comment by nicolas-grekas** [comment]
I found a way to fix this properly :)
#19859
