### ISSUE TITLE
Issue for Swiftmailer and PHP 7 with declare(strict_types=1);

### ISSUE THREAD

**Issue by ChrisWesterfield** [symfony/symfony#19846]
Hi,

every time that I want to send emails through swiftmailer I get the following notice:

 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: unserialize() expects parameter 1 to be string, boolean given

it happens if there are emails inside of the mail queue (currently I'm using Snc Redis Bundle with Symfony 3.1 for swiftmailer spooling.

I'm using in all my own classes `declare(strict_types=1);` in the header.
Before I switched this it worked without the notification.

PHP: 7.0.10 (dotDeb)
Symfony newest 3.1 stable version.
\Redis as Redis Driver
Linux: Debian 8 latest Updates
I'm not using the bundled redis from dotdeb as these include igbinary which is broken in combination with doctrine cache inside of redis.

If more details needed, please let me know.
I will provide them asap.

**Comment by jameshalsall** [comment]
What is the stack trace? Can you show your code?

**Comment by jameshalsall** [comment]
This looks related to #19845

**Comment by ChrisWesterfield** [comment]
Ticket can be closed.
After a closer look at the stacktrace with looking into the SNC Redis Bundle it appears that the bundle isn't ready for declare strict.
Issue can be closed.
