### ISSUE TITLE
[ClassLoader] Undefined variable inside of `findFile` method

### ISSUE THREAD

**Issue by BR0kEN-** [symfony/symfony#19855]
The second argument for `apcu_fetch()` function must be passed by reference. See http://php.net/manual/en/function.apcu-fetch.php.

Affected line: https://github.com/symfony/class-loader/blob/master/ApcClassLoader.php#L125

**Comment by jameshalsall** [comment]
Call-time pass by reference was removed in PHP 5.4. I don't see anything wrong with the `ApcClassLoader`

**Comment by xabbuh** [comment]
@BR0kEN- Did you experience any issues with the current code?

**Comment by jakzal** [comment]
Indeed, there's [nothing wrong](https://3v4l.org/bVuN8) with the `ApcClassLoader`.  @BR0kEN- we'll reopen if you come up with a scenario which would break the code.
