### ISSUE TITLE
Symfony2&3 Web Debug Toolbar 500 Internal Server Error 

### ISSUE THREAD

**Issue by rizagunes** [symfony/symfony#19850]
hi, i'm getting this error on default project after "php app/console server:run"
im using php7
https://s15.postimg.io/54yaz6ty3/Se_im_001.png-
`
Neither the property "ip" nor one of the methods "ip()", "getip()"/"isip()" or "__call()" exist and have public access in class "Symfony\Component\HttpKernel\Profiler\Profile" in @WebProfiler/Profiler/layout.html.twig at line 30`

Thanks

**Comment by jameshalsall** [comment]
What version?

**Comment by rizagunes** [comment]
I get this error in both versions, i don't get the error when i close toolbar (config_dev.yml)

my system:
linux mint
apache2 + php 7.0.10

**Comment by Tobion** [comment]
Duplicate of #19560

**Comment by xabbuh** [comment]
Please continue in #19560.
