### ISSUE TITLE
entity is error

### ISSUE THREAD

**Issue by gitgaojun** [symfony/symfony#19863]
On my project . the error is
Property Yilinker\Bundle\CoreBundle\Entity\WechatPosters::$WechatPostersId does not exist 

but I was change $WechatPostersId  to $wechatPostersId. 
I don't know why I was flushall the redis is ok? 
when I flushall the redis ,something is error because nothing isset in the redis.

**Comment by javiereguiluz** [comment]
@gitgaojun I'm closing this issue because of the reasons mentioned earlier, but I'm sure that the Symfony community can help you via the support channels explained in http://symfony.com/support
