### ISSUE TITLE
Sub process output not being returned 'real-time'

### ISSUE THREAD

**Issue by lukesnowden** [symfony/symfony#19873]
I'm just testing out the Process class and it doesn't seem to do what it says on the tin.

Docs state 

> When executing a long running command (like rsync-ing files to a remote server), you can give feedback to the end user in real-time by passing an anonymous function to the run() method:

I have 1 file with the following

```php
$process = new Process('php terminal.php');
$process->setTimeout(null);
$process->run( function ( $type, $buffer ) {
	if (Process::ERR === $type) {
		echo 'ERR > '.$buffer;
    } else {
 		echo 'OUT > '.$buffer;
 	}
});
```

and another with the following

```php
$x = 10;
while( $x ) {
	echo "{$x}\n";
	sleep(1);
	$x--;
}
```

While running this via terminal after a **10 second wait** the output is

```cli
OUT > 10
OUT > 9
OUT > 8
OUT > 7
OUT > 6
OUT > 5
OUT > 4
OUT > 3
OUT > 2
OUT > 1
```

which shows there are 10 iterations of closure above but there is no output until the process is finished.

Am I missing something here?

Regards, Luke

**Comment by jakzal** [comment]
I just tried your example and it works as expected, outputting a number every second.

**Comment by lukesnowden** [comment]
I've had someone else tell me the above works. Could there be any output PHP setting that could be messing this up?

**Comment by elementaire** [comment]
Hi @lukesnowden,

You should read these : http://php.net/manual/en/function.ob-flush.php and http://php.net/manual/en/function.flush.php

It could help you to understand the bias to your demonstration. PHP could buffer your ouputs before sending them to your console. You should not check your theory with `echo` because it is often the case. 

Regards

**Comment by xabbuh** [comment]
@lukesnowden Any news here? :)

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. Feel free to provide more input and we can consider to reopen.
