### ISSUE TITLE
[DomCrawler] crawler differences between page get and HEREDOC

### ISSUE THREAD

**Issue by frian** [symfony/symfony#19880]
Hi,

I have a problem in my tests where the crawler does not see the complete html of the page.

I asked on [stackoverflow](http://stackoverflow.com/questions/39352486/symfony-crawler-access-nested-div) with no luck.

Upon further investigation, if I paste the html as HEREDOC in the test everything works as expected

I wrote 2 tests to show the case, as the html is long I made a [gist](https://gist.github.com/frian/fdbd866995355939e92e761fa0b89d9f).

Everything inside

`<div class="monthEventWrapper">`

is not seen by the crawler on 

`$crawler = $this->client->request('GET', '/month');`

but with a HEREDOC and

`$crawler = new Crawler($html);`

it works !?

Thanks

**Comment by jakzal** [comment]
I just tried your example, and it works perfectly fine (tests are passing, see [my branch](https://github.com/jakzal/symfony-standard/compare/master...jakzal:issues/19880?expand=0)). I'm going to close it as this doesn't look like a bug, but a mistake in somewhere in your app. Feel free to provide a failing example to prove otherwise, and we'll re-open.

**Comment by frian** [comment]
Hi,

ok, as the app works ant the html validates I will try to make a working example.

Thanks !

**Comment by jakzal** [comment]
@frian feel free to use [my branch](https://github.com/jakzal/symfony-standard/tree/issues/19880) as a starting point.

**Comment by frian** [comment]
will do this !

Am I right : the crawler just see the outputed html ?

Looking for a hint as where to start searching what happens ?

Thanks :)

**Comment by jakzal** [comment]
> Am I right : the crawler just see the outputed html ?

Yes.

> Looking for a hint as where to start searching what happens ?

* logs
* html output of the client `$this->client->getResponse()->getContent()`
* html output in the crawler `$crawler->html()`

**Comment by frian** [comment]
Hi again,

so here's a demo [branch](https://github.com/frian/symfony/tree/issues/19880-demo).

Not sure if I done this right !

there's a fixture.sql file to load data.

The page loads strangely (reloads), but this is not the case in the full app, so the bug should not be related to this.

If I can do anything else ...

Thanks !

**Comment by jakzal** [comment]
In the test you're using basic auth, while your application is configured to use a form login. The test fails as you're not being logged in. Since this is not a Symfony bug, please use our [support channels](http://symfony.com/support) to get help. Good luck! :)

**Comment by frian** [comment]
well I'm following the [docs](http://symfony.com/doc/current/testing/http_authentication.html) !?

as I have 

`- { path: ^/, role: ROLE_USER }`

and all others tests passes I think I'm logged in !

Thanks !

**Comment by frian** [comment]
A comment on : well I'm following the [docs](http://symfony.com/doc/current/testing/http_authentication.html) !?

Thanks !

**Comment by frian** [comment]
Hi @jakzal,

I finally noticed that I forgot to add
    
    security:
        firewalls:
            main:
                http_basic: ~

to config_test.yml in the demo :( which made the demo work :)

As I had it in my app's config_test.yml, I was, well, at least surprised !
 
Then a light went on, I forgot to add a session var in the test :(

Sorry for the inconvenience and thanks a lot for your time !

Have a nice week end :)
