### ISSUE TITLE
test fails after upgrade 3.1.3 - 3.1.4 due to wrong date

### ISSUE THREAD

**Issue by frian** [symfony/symfony#19881]
Hi,

after upgrading 3.1.3 to 3.1.4, the following test fails : 

```php
        $crawler = $this->client->request('GET', '/event/new');

        $this->assertTrue($crawler->filter('html:contains("new event")')->count() == 1);

        $form = $crawler->selectButton('create')->form();

        $startDate = date('d/m/Y') . " 09:00";
        $endDate = date('d/m/Y') . " 10:00";

        $form['timetm_eventbundle_event[title]'] = 'test title';
        $form['timetm_eventbundle_event[place]'] = 'test place';
        $form['timetm_eventbundle_event[agenda]'] = '1';
        $form['timetm_eventbundle_event[startdate]'] = $startDate;
        $form['timetm_eventbundle_event[enddate]'] = $endDate;

        $crawler = $this->client->submit($form);

        $this->assertTrue($this->client->getResponse()->isRedirect());
        $this->client->followRedirect();
        $this->assertContains(
            '09:00',
            $this->client->getResponse()->getContent()
        );
        $this->assertContains(
            'test title',
            $this->client->getResponse()->getContent()
        );
```

with

        Failed asserting that "document" contains "09:00"

which is true. Somewhere my

```php
        $startDate = date('d/m/Y') . " 09:00";
        $endDate = date('d/m/Y') . " 10:00";
```

where changed to

```php
        $startDate = date('d/m/Y') . " 07:00";
        $endDate = date('d/m/Y') . " 08:00";
```

v3.1.3 output after tests

![v3 1 3](https://cloud.githubusercontent.com/assets/6443649/18311595/6d023bb6-7505-11e6-8974-1c322d756047.png)

v3.1.4 output after tests

![v3 1 4](https://cloud.githubusercontent.com/assets/6443649/18311600/72daf974-7505-11e6-8155-4b1292502887.png)

Any changes in date manipulation I missed ?

Thanks

**Comment by javiereguiluz** [comment]
I don't know what can be happening here, but in case it gives you a clue: the 2 hour difference matches the difference between the "default" GMT timezone and the current summer time in Europe (CEST). So it could be a timezone issue somewhere.

**Comment by frian** [comment]
Hi Javier,

I checked my php timezone settings, they are set to "Europe/Zurich".

Thing is if I upgrade - downgrade the bug appears / disapears !

Is there some timezone setting in symfony ?

Thanks

**Comment by javiereguiluz** [comment]
The only date related change that I can find between 3.1.3 and 3.1.4 is this one: #19541

**Comment by frian** [comment]
Only one I found too !

I saw nothing special when I checked it, but now I'm wondering if it's not related to me not having the latest intl !?

I think I read somewhere in the docs that this could lead to strange behaviour !

will try to check this !

Thanks !

**Comment by pedroresende** [comment]
@frian have you tried to revert #19541 on 3.1.4 to verify if it is the origin of your problem ?

**Comment by mvrhov** [comment]
Try applying #19879

**Comment by frian** [comment]
Hi @mvrhov, @pedroresende,

I'm now installing ubuntu 16 ( was on 14 ) to see if anything changes !

Will try your solutions and come back.

Thanks !

**Comment by frian** [comment]
Hi,

so after installing ubuntu 16.04, the problem is gone !

not sure if this needs further investigations ?

Thanks !
