### ISSUE TITLE
User account disabled. Opcache issue.

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#19886]
Hi everyone!

I don't find any information about this issue. I expose my case:

Symfony 2.8.7, FOSUserBundle "dev-master", Nginx, php7 with php-fpm and opcache actived with no validation tiemstamps.

Most of the times when I deploy my app (around 8/10 times), I get kicked out from the session and then when I try to login I receive a User account disabled message. Then I restart php-fpm in the server and I can login successfully.

It's strange cause when I deploy (ansible) I have a task that execute php-fpm restart. And as I said before sometimes everything goes well, and other times I need to restart php even 3 times.

Error occurs in:

Symfony\Component\Security\Core\Exception\DisabledException occurred in User/UserChecker.php:42

If I dump $user, i see user is loaded but no enabled or locked data:

![image](https://cloud.githubusercontent.com/assets/1706470/18344033/06066b24-75b6-11e6-93ad-da152dd13660.png)

And i See in debug toolbar that's doing a redis query to find session:

0.18 ms	session	GET pb_sessiond1iatpii501suehogk8mr6ek85

And the info in my session is:

_sf2_attributes|a:3:{s:26:"_security.main.target_path";s:28:"https://app.xxxxx.com/";s:18:"_csrf/authenticate";s:43:"mw6yhqr8jsUIazza3qFRPk_bxCXtG-NKGrjNj26EdJ8";s:23:"_security.last_username";s:20:"marcos@xxxxx";}_sf2_flashes|a:0:{}_sf2_meta|a:3:{s:1:"u";i:1473326443;s:1:"c";i:1473326059;s:1:"l";s:1:"0";}

If I configure opcache with validation timestamps to 1 (default config) works ok, but not always.

Has someone the same issue?

PS. My session is stored in a external redis database.

**Comment by jakzal** [comment]
I'm going to close this issue as there's no bug in Symfony. We don't use github for support questions (see http://symfony.com/support).

P.S. Issues with clearing opcache are quite common and you shouldn't have issues sorting it out with the help of google.
