### ISSUE TITLE
Symfony 2.8.11 - Form `choice`'s options are inheriting id and name of parent select

### ISSUE THREAD

**Issue by alanhartless** [symfony/symfony#19898]
I had an override for `choice_widget_options.html.php` as a work around for https://github.com/symfony/symfony/issues/19016. I noticed that has since been fixed so wanted to give it a try. When I removed the override to use stock, I noticed that each option of the select inherited it's `id` and `name` attributes as well. This caused issues for me with JS `getElementById()`. Should a check be in place to not set the parent's id and name?

**Comment by alanhartless** [comment]
Issue seems to be this https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Resources/views/Form/choice_attributes.html.php#L1 since it's the parent's form object passed here https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Resources/views/Form/choice_widget_options.html.php#L11. I don't see a need for https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Resources/views/Form/choice_attributes.html.php#L1 so maybe that can just be removed?

**Comment by alanhartless** [comment]
Actually both lines 1 and 2 - if the select is disabled, it adds disabled to all options making it impossible to get the fixed value via JS. https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Resources/views/Form/choice_attributes.html.php#L1-L2

**Comment by HeahDude** [comment]
Thanks @alanhartless for reporting this, indeed this line should be removed. See #19904.

Status: reviewed
