### ISSUE TITLE
TwigEngine->exists() returns true for any string

### ISSUE THREAD

**Issue by tchapi** [symfony/symfony#19903]
Hi

I have an issue after updating to 2.8.11 from 2.8.9.
In a controller :

    $this->get('templating')->exists($templateName)

returns `true` for any `$templateName`, i.e. for any string, like "blablabla" or whatever. Doesn't work if I encapsulate the string in a `TemplateReference` either. It worked perfectly before updating.

Am I missing something ?

Symfony version: **2.8.11**

**Comment by muspelheim** [comment]
it work ok for me (bool(false) for blabla) on symfony 2.8.11

**Comment by tchapi** [comment]
Ah ? Ok that's strange then. What could I do wrong for it to break ? I don't see how I could have modified the `templating` service myself in my application, but maybe I'm overlooking something. Any hints ? Maybe a dependency that could add a layer above the service ?

**Comment by jakzal** [comment]
Just tried it myself and it works as expected. Closing as there's no bug.
