### ISSUE TITLE
Cache component problem

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#19912]
Symfony 3.1

1. Run from console `cache:clear`
2. Run command, which saves an item in the symfony cache
3. Open the page in browser, where this item is fetched, get `$cacheItem->isHit = false`

Working scenario:
1. Run `cache:clear`
2. Open some other page in browser (which doesn't request the item from the cache)
3. Run command, which warms-up the cache item
4. Open the page in browser, where this cache item is fetched, get `$cacheItem->isHit = true` and everything works fine

So, it looks like running the cache warm-up command right after the cache:clear command doesn't make sense. Is this the expected behaviour?

**Comment by jakzal** [comment]
Do you run your command in the same environment (prod/dev) as you use in the browser?

**Comment by vudaltsov** [comment]
@jakzal , in the same dev environment. I doublechecked that.
And my working scenario proves that.

**Comment by jakzal** [comment]
@vudaltsov would you mind forking Symfony Standard edition and reproducing your problem on a new branch please? We need to isolate this problem with simplest possible code.

**Comment by vudaltsov** [comment]
I reproduced the problem in the clean fork of the project, but everything worked.
I will look attentively at the business logic in my project.

Sorry for this incorrect issue.

**Comment by vudaltsov** [comment]
I am digging into the problem in my actual project.

I noticed that when I run warmup command right after the cache clear command, it creates cache in a different place than if I run my command after I once go to the browser.

What finally solved the issue was commenting the `'name'` element in `Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\CachePoolPass` at 33, because right after clearing the cache the `'%kernel.name%' = '_ap'` and only later it becomes `app`

**Comment by vudaltsov** [comment]
@nicolas-grekas, could you, please, help with this?

**Comment by Simperfit** [comment]
What are you using as your system environment (docker / no container / vagrant) ?

**Comment by vudaltsov** [comment]
@Simperfit, no container. Just directly on Ubuntu I am working on.

**Comment by nicolas-grekas** [comment]
Should be fixed by #20147
