### ISSUE TITLE
ExecutableFinder generates wrong Path

### ISSUE THREAD

**Issue by tschechniker** [symfony/symfony#19913]
Hi,

the executableFinder is generating a wrong path if you have open_basedir in action.

For example you have installed java in /usr/bin/java and your open_basedir is set to /usr/bin/ the ExecutableFinder will return /usr/bin//java. The problem is that the open_basedir restrictions now say your are not allowed to access /usr/bin//java because of the two slashes.

See: https://github.com/symfony/process/blob/master/ExecutableFinder.php#L82

```php
/**
* $dir = /usr/bin/
* $name = java
* $suffix = '' (empty)
*/
if (is_file($file = $dir.DIRECTORY_SEPARATOR.$name.$suffix) && ('\\' === DIRECTORY_SEPARATOR || is_executable($file))) {
```

Best regards

Tobi

**Comment by xabbuh** [comment]
I can confirm the issue.

Status: Reviewed

**Comment by xabbuh** [comment]
@tschechniker Can you please check if `/usr/bin/java` in your case is a symlink to a file outside of your `open_basedir`? That's actually the only case where I was really able to reproduce your issue. Though I am not sure if we can actually avoid that then.

**Comment by xabbuh** [comment]
see #20077

**Comment by tschechniker** [comment]
@xabbuh Yes /usr/bin/java is a symlink. This is standard on many Linux distros. But i don't see how the symlink will cause this issue. From my oppinion this is a logical issue.

So my open_basedir has the following content:

open_basedir=/var/www/;/usr/bin/

Now you are itterating over the open_basedir

$dirs[0] = "/var/www/"
$dirs[1] = "/usr/bin/"

Now you are searching for the executeable:
foreach($dirs a $dir) ...
$dir.DIRECTORY_SEPARATOR.$name.$suffix

==> "/usr/bin/".DIRECTORY_SEPARATOR."java".""

So from my side this is not a fault of the symlink

**Comment by xabbuh** [comment]
@tschechniker It is as the symlink is pointing to a location outside of your open basedir config.

Please note that PHP evaluates the symlink before trying to figure out if the path is allowed:

> All symbolic links are resolved, so it's not possible to avoid this restriction with a symlink. If the file doesn't exist then the symlink couldn't be resolved and the filename is compared to (a resolved) open_basedir .

see http://php.net/manual/en/ini.core.php#ini.open-basedir
