### ISSUE TITLE
[RFC] [4.0] The EventSubscriberInterface should be an abstract class

### ISSUE THREAD

**Issue by jameshalsall** [symfony/symfony#19914]
The [`EventSubscriberInterface`](https://github.com/symfony/event-dispatcher/blob/master/EventSubscriberInterface.php) currently defines a single static function, but this makes no sense on an interface.

Imho it should be an abstract class that defines an abstract function instead.

This obviously breaks BC but could be introduced now whilst marking the interface as deprecated.

**Comment by mvrhov** [comment]
No. This is wrong. PHP doesn't support multiple class inheritance. So Having interface is correct way of doing that.

**Comment by jameshalsall** [comment]
Good point, but I don't think an interface is correct either. A trait possibly?

**Comment by jameshalsall** [comment]
I guess this is related: https://github.com/symfony/symfony/issues/2110 and given the usage in `EventDispatcher` (calling it as an instance method) I can see why it's been implemented this way.
