### ISSUE TITLE
[Form] support textarea placeholder attribute

### ISSUE THREAD

**Issue by foaly-nr1** [symfony/symfony#19925]
Is there any particular reason why `TextareaType` doesn't support the `placeholder` attribute?

```html
<textarea placeholder="Describe yourself here..."></textarea>
```

**Comment by digilist** [comment]
Why did you close this issue? Is there any reason?

**Comment by foaly-nr1** [comment]
Yes, because it is support, I just stupidly didn't think before opening this.

http://symfony.com/doc/current/reference/forms/types/textarea.html#attr

**Comment by digilist** [comment]
Ah yes, you can add it as an attr. But why do the other types have a placeholder option? It just confused me and it might be confusing for other devs too.

**Comment by stof** [comment]
@digilist the test type does not have a dedicated option for it either. And types using a ``placeholder`` option are *not* using such option to configure the HTML placeholder attribute.

**Comment by digilist** [comment]
Okay, nevermind, only the ChoiceType has a placeholder, not the TextType.
