### ISSUE TITLE
TranslationUpdateCommand test failure on master

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#19921]
If someone wants to have a look, it'd be great!
https://travis-ci.org/symfony/symfony/builds/159397742

**Comment by jakzal** [comment]
@nicolas-grekas I can no longer run tests locally. Am I missing something? Running the phpunit wrapper just outputs the first line:

![image](https://cloud.githubusercontent.com/assets/190447/18467610/89e14938-7998-11e6-8d64-e5496acc42b5.png)

**Comment by nicolas-grekas** [comment]
composer update first, then try again? maybe remove the .phpunit folder before?

**Comment by jakzal** [comment]
Ok, I figured it out.

This works:

```
./phpunit src/Symfony/Bundle/FrameworkBundle/
```

and this doesn't:

```
./phpunit src/Symfony/Bundle/FrameworkBundle/Tests
```

**Comment by nicolas-grekas** [comment]
Did it work previously?

**Comment by jakzal** [comment]
re #19325 #19878

**Comment by jakzal** [comment]
> Did it work previously?

Not sure to be honest, but it definitely works with phpunit directly.
