### ISSUE TITLE
Validator cache and closure

### ISSUE THREAD

**Issue by hlecorche** [symfony/symfony#19937]
In validator component, a metadata object can have a closure.

But when `framework.validation.cache` is used with `validator.mapping.cache.doctrine.apc`, the cache throws an exception because cache can't seraliaze a closure.

> Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at /path/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php line 57 {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed

**Comment by hlecorche** [comment]
The exception is thrown when `Callback` validator is used with `loadValidatorMetadata` method :

```php
    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        //It's OK !

        $fakeNames = array('fake-name');

        if (in_array($this->getFirstName(), $fakeNames)) {
            $context->buildViolation('This name sounds totally fake!')
                ->atPath('firstName')
                ->addViolation();
        }
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        //Exception is thrown !!!!

        /*
         * Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at
         * /path/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php line 57 {"exception":"[object]
         * (Exception(code: 0): Serialization of 'Closure' is not allowed
         */

        $callback = function ($object, ExecutionContextInterface $context, $payload) {
            // ...
        };

        $metadata->addConstraint(new Assert\Callback($callback));
    }
```


You can test here : https://github.com/hlecorche/bug-closure (homepage route in prod environment)

**Comment by Koc** [comment]
looks like relates to #12302, #10083

**Comment by stof** [comment]
if you want your metadata to be cacheable, don't use a closure for the callback.

**Comment by xabbuh** [comment]
Closing here as #20793 has been merged. Please comment with some more details if you still experience any issues.
