### ISSUE TITLE
Allow GetSetMethodNormalizer in Serializer to be aware of type hinted parameters

### ISSUE THREAD

**Issue by miguelsimoes** [symfony/symfony#19935]
When using the Serializer with the GetSetMethodNormalizer, it could be important that, on deserialize/denormalize, if the setters have type hint of the argument that the value could be converted to it.

A simple approach (do not mind the naming convention) would be to replace 

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php#L64-L66, which reads:

``` php
if (in_array($setter, $classMethods) && !$reflectionClass->getMethod($setter)->isStatic()) {
    $object->$setter($value);
}
```

With something like:

``` php
if (in_array($setter, $classMethods) && !$reflectionClass->getMethod($setter)->isStatic()) {
    $parameters = $reflectionClass->getMethod($setter)->getParameters();
    $typeHint = $parameters[0]->getClass();

    if ($typeHint && class_exists($typeHint->name) && !$value instanceof $typeHint->name) {
        $typeHintedClassName = $typeHinted->name;
        $value = new $typeHintedClassName($value);
    }
    $object->$setter($value);
}
```

**Comment by dunglas** [comment]
Can you take a look at this https://github.com/symfony/symfony/pull/17660? It:

1. checks if the type of the deserialized data is the same than the one of the corresponding property
2. adds support for complex deserialization of relations relations / complex types (e.g., nested objects)

I think that it's another way to fix the same problem.

**Comment by dunglas** [comment]
Does it fix your problem?

**Comment by jakzal** [comment]
ping @miguelsimoes

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.
