### ISSUE TITLE
[Workflow] Request for getDefinition()

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#19938]
I'd like access to the definition property for creating workflow documentation.  Can you add

    public function getDefinition()
    {
        return $this->definition;
    }

to Workflow.php?

Thanks.  I'll add this as a PR.

**Comment by tacman** [comment]
This would avoid the contortions like

    private function getProperty($object, $property)
    {
        $reflectionProperty = new \ReflectionProperty(get_class($object), $property);
        $reflectionProperty->setAccessible(true);
        return $reflectionProperty->getValue($object);
    }

https://github.com/symfony/framework-bundle/blob/master/Command/WorkflowDumpCommand.php#L71-L77

**Comment by javiereguiluz** [comment]
Let's ask to our fellow Workflow expert @lyrixx: do you think this would be a good idea ... or do you prefer to not add this method? Thanks!

**Comment by lyrixx** [comment]
Hello. 

What is your use case?

Right now I don't want to add `Workflow::getDefinition`, as the workflow definition is mutable.

**Comment by tacman** [comment]
We are generating documentation from from the workflow, e.g. 

http://survos-documentation.readthedocs.io/en/latest/workflows/Member/participant.html#member-states

And don't want to read the workflow.yml file directly.

**Comment by lyrixx** [comment]
Ok got it. 

I'm still against for opening a breach in the code. Because I can not predict what could happen if people get the definition and modify it on the fly...

You can still use the reflection at your own risk to do that.

**Comment by javiereguiluz** [comment]
Given that @lyrixx is against this proposal, let's close it for now as "won't fix".

@tacman this component is brand new, so that's why we prefer to be very cautious about exposing its internal features. In the near future, when more people use the component and we get more feedback, we can reconsider this decision. Thanks!

**Comment by lyrixx** [comment]
For you information, This feature has been added to Symfony.
