### ISSUE TITLE
[serializer] Extra attributes may throw exception when denormalize

### ISSUE THREAD

**Issue by juliendidier** [symfony/symfony#19948]
During the denormalization of an object, the [AbstractObjectNormalizer](https://github.com/symfony/serializer/blob/master/Normalizer/AbstractObjectNormalizer.php#L186) do not throw exception when an attribute is not in allowed. As a result I can denormalize an array to an object with not mapped attributes.

I'm currently designing an API.
Users are not allowed to send extra attributes that are not mapped to my class.
I want to throw an exception on this case.

Is it possible to implement this feature inside the Serializer component ?

**Comment by dunglas** [comment]
It is not currently implemented but it should be trivial to add to the current normalizer.
It would be a nice improvement but it should he optional and disabled by default.

**Comment by Simperfit** [comment]
@dunglas this can be closed ?
