### ISSUE TITLE
[Translation] Add a new lint:translation command

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony#19942]
Hi, guys!

I'd like to open a PR for implementing a new console command for translations:

``` bash
# shows the errors in the console
$ ./bin/console lint:translation <file | dir | @BundleName>

# reorders translation messages according to the message order for default locale
$ ./bin/console lint:translation --reorder <file | dir | @BundleName>

# fixes the errors modifying the translation files
$ ./bin/console lint:translation --fix <file | dir | @BundleName>

# fixes the errors modifying the translation files and
# adds empty missing translations from the original file
$ ./bin/console lint:translation --fix --add-missing <file | dir | @BundleName>
```

First of all, I'd like to say that maintain translations is a difficult process, especially if we want to keep them consistent with each other. I mean: fix syntax, keep message order in sync in different files, add missing translation messages, etc.).

Actually, we can see it in the example of [Symfony Demo](https://github.com/symfony/symfony-demo) project though this is a small project. This problem is even more relevant for big projects. Symfony Web Debug Toolbar helps with missed translations, but its tips relate to the opened page only (the page that developer's viewing right now). That's why I want to suggest this new console command.

What do you think about it?

**Comment by javiereguiluz** [comment]
I like this idea. But I'd think a bit more about the options of the command. It's common for this kind of commands to have two modes: 1) "show the changes to do but don't make them", 2) "make those changes".

In this example, `--fix` seems the option that makes changes ... but there is a `--reorder` option that makes changes too.

The other issue to think about is if we want to allow to select the fixers: reorder, add missing, etc. or we want to run all of them at once.

Finally, I'd like to have a list of proposed fixers. For example:

* reorder: changes translation files to have their contents in the same order as the original translation file.
* add missing: changes translation files to add all the translations defined in the original translation files and missing in this particular translation files.
* ...

**Comment by bocharsky-bw** [comment]
@javiereguiluz I agree with you, it makes sense to make changes for `--reorder` option only with specified `--fix` option.

I suppose, we'd like to have some format-specific fixers, for example, for YAML translations:
```yaml
# inline
post.no_comments: No comments
post.no_posts: No posts
# or expanded
post:
    no_comments: No comments
    no_posts: No posts
```

I'm also wondering in the best way of original translation determination. I think we should provide `--default-locale` (or just `--locale`) option for it which helps to determine original translation file i.e. the file, which will be used as the basis for `--reorder`, `--add-missing`, etc. options.

**Comment by ro0NL** [comment]
@bocharsky-bw did you considered `translation:update` on this? Maybe we should avoid having 2 commands doing write operations..

Ie. maybe extending the update command with `--from-file` and`--from-source` could work?

`--add-missing` can be used like `--extract` which plays nice with both `--from-file/source`.

**Comment by bocharsky-bw** [comment]
Hey @ro0NL , I think single `lint:translation` command with a few options will be enough for these purposes. We already have `lint:twig` and `lint:yaml` similar commands. BTW, the `yaml:lint` command is deprecated and doesn't work in Symfony 3, so `lint:translation` looks like a better name here.

What about formatting YAML translation files: I think doing the same operation with different commands is a bad idea. The command should determine translation file format by itself and process it properly.

**Comment by ro0NL** [comment]
Maybe you're right, and 2 commands could work

- `translation:update` updates files based on source
 - functional related -> we need all strings in a file
- `lint:translations` updates files based on a template file
 - cosmetic related -> we need to organize our files in a sane way

About (re)formatting; this only affects inline vs. expanded (ie. dot notation yes/no) and is definitely translation related, but only for YAML+PHP. Im more or less leaning to something like `LoaderInterface::supportsDotNotation` to avoid tracking a list of extensions somewhere.

**Comment by rvanlaak** [comment]
There are quite some bundles that do a nice job on this, or am I mistaking on the scope of your issue here? ;)

https://github.com/schmittjoh/JMSTranslationBundle
https://github.com/lexik/LexikTranslationBundle

**Comment by stof** [comment]
A command changing the file should not be named ``lint:*`` IMO. As soon as it fixes things, it is not a linter anymore.

**Comment by javiereguiluz** [comment]
Even if this idea is changed to only provide a linter command and not a fixer, I'd love to see it happen.

(Context -> this morning, a minor error in a XLIFF translation file completely broke a bundle release: https://github.com/javiereguiluz/EasyAdminBundle/pull/1490)

**Comment by rvanlaak** [comment]
@javiereguiluz we right now have the `yml` linter in our test suite, which saved us from releasing broken bundles several times already. So 👍 from me on that specific context too.
