### ISSUE TITLE
[Forms] handleRequest() blanks the fields in my form

### ISSUE THREAD

**Issue by htollefsen** [symfony/symfony#19947]
Symfony version: 2.8.6

I'm attempting to update the form fields based on a selection in a parent fieldtype. But when I do `$form->handleRequest($request)`, all the data in my form is empty.

I've mainly attempted to follow this guide: [Dynamic Generation for Submitted Forms](http://symfony.com/doc/current/form/dynamic_form_modification.html#form-events-submitted-data).

ArticleType.php

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $updateRoute = $this->router->generate('appbundle_article_update_form');
    
        $builder
            ->add('name', 'text', [
                'required' => false,
            ])
            ->add('description', 'textarea', [
                'required' => false,
            ])
            ->add('ajax_update_action', 'hidden', [
                'data' => $updateRoute,
                'mapped' => false,
            ])
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'text' => 'Text',
                    'textarea' => 'Multiline',
                    'choice' => 'Choice',
                ],
            ])
            ->add('parameters', OptionsType::class)
        ;
    }

OptionsType.php

If `type` in ArticleType is set to 'choice', 3 extra fields should be added (which they do).

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', 'text', [
                'required' => false,
            ])
            ->add('required', 'checkbox', [
                'required' => false,
            ]);
        ;
    
        $builder->addEventListener(
            FormEvents::POST_SET_DATA,
            function (FormEvent $event) {
    
                $form = $event->getForm();
                $parentData = $event->getForm()->getParent()->getData();
    
                if ($parentData->getType() == "choice") {
    
                    if(!$form->has('multiple')) {
                        $form->add('multiple', 'checkbox', [
                            'required' => false,
                        ]);
                    }
                    if(!$form->has('extended')) {
                        $form->add('extended', 'checkbox', [
                            'required' => false,
                        ]);
                    }
                    if(!$form->has('choices')) {
                        $form->add('choices', 'text', [
                            'required' => false,
                            'attr' => [
                                'help_block' => 'Provide a comma separerated list',
                            ],
                        ]);
                    }
    
                }else {
                    foreach(['multiple', 'extended', 'choices'] as $field_name) {
                        if($form->has($field_name)) {
                            $form->remove($field_name);
                        }
                    }
                }
            }
        );
    }

Article/edit.html.twig:
Pretty straight forward, where we have a custom form to update the form (without persisting!)

    {{ form(form) }}

    <script>
    
    $( document ).ready(function () {
        $('select#article_type').on(
            'change',
            this,
            function() {
                var $form = $(document).find('form[name=article]'),
                    $url = $form.find('#article_refresh_action').val(),
                    $data = $form.serialize();
    
                $.ajax({
                    url: $url,
                    type: 'POST',
                    data: $data,
                    success: function (html) {
                    $form.find('#article_parameters').replaceWith($(html).find('#article_parameters'));
                }
                });
            }
        );
    });
    
    </script>

ArticleController.php:
Note that I do not want to persist the data to the database, just update the form, and return it.

    /**
     * @param Request $request
     *
     * @Route("/article/updateForm", name="appbundle_article_update_form")
     * @Method({"PUT", "POST"})
     *
     * @return Response
     */
    public function updateFormAction(Request $request)
    {
        $form = $this->createForm(
            $this->get('appbundle.form.type.article'),
            new Article()
        );
    
        // When i do a `dump($request->request->all())` here, I'm given all the correct data in an array
    
        $form->handleRequest($request);
    
        // When i do `dump($form->getData());` here, all the fields are null, which makes the form return blank.
    
        return $this->render(
            'AppBundle:Article:edit.html.twig', [
                'form' => $form->createView(),
            ]
        );
    }

Article.php
the entity:

    /**
     * Storing it as json.
     *
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $parameters;
    
    /**
     * Set parameters.
     *
     * @param array $parameters
     *
     * @return Article
     */
    public function setParameters($parameters)
    {
        $this->parameters = json_encode($parameters);
    
        return $this;
    }
    
    /**
     * Get parameters.
     *
     * @return array
     */
    public function getParameters()
    {
        return json_decode($this->parameters, true);
    }

So after the handleRequest, all my fields are blanked, without any exception or notices in the log. Is this a bug, or am I just doing this the wrong way?

**Comment by jakzal** [comment]
@htollefsen would you mind putting your code in a fresh standard edition project? Would be easier to reproduce.

**Comment by patrick-mcdougle** [comment]
If I had to make a guess, it has to do with the line:
```
if($form->has($field_name)) {
    $form->remove($field_name);
}
```

If you remove form fields, they're going to not be there.

**Comment by htollefsen** [comment]
@jakzal I've uploaded a demo here https://github.com/htollefsen/handleRequest

@patrick-mcdougle The fields are supposed to be removed whenever `choice` is not set.

**Comment by HeahDude** [comment]
Hi @htollefsen, I've tried your demo, and it seems the form is actually submitted, it's just not valid because your try to submit some fields that are not present yet. To make it work you have to put another listener on `PRE_SUBMIT` which change the fields considering submitted data and to do that the listener should be in the `ArticleType`.

So I suggest you put both listeners in it:
```php
$builder->addEventListener(
    FormEvents::POST_SET_DATA,
    function (FormEvent $event) {

        $form = $event->getForm()->get('options'); // changed this line
        $parentData = $event->getData(); // and this one

        if ($parentData->getType() == "choice") {

            if(!$form->has('multiple')) {
                $form->add('multiple', 'checkbox', [
                    'required' => false,
                ]);
            }
            if(!$form->has('extended')) {
                $form->add('extended', 'checkbox', [
                    'required' => false,
                ]);
            }
            if(!$form->has('choices')) {
                $form->add('choices', 'text', [
                    'required' => false,
                    'attr' => [
                        'help_block' => 'Provide a comma separerated list',
                    ],
                ]);
            }
        }else {
            foreach(['multiple', 'extended', 'choices'] as $field_name) {
                if($form->has($field_name)) {
                    $form->remove($field_name);
                }
            }
        }
    }
);

$builder->addEventListener(
    FormEvents::PRE_SUBMIT,
    function (FormEvent $event) {

        $form = $event->getForm()->get('options');
        $parentData = $event->getData();

        if ($parentData['type'] == "choice") { // changed this line too
        // because data here is the submitted array

            if(!$form->has('multiple')) {
                $form->add('multiple', 'checkbox', [
                    'required' => false,
                ]);
            }
            if(!$form->has('extended')) {
                $form->add('extended', 'checkbox', [
                    'required' => false,
                ]);
            }
            if (!$form->has('choices')) {
                $form->add('choices', 'text', [
                    'required' => false,
                    'attr' => [
                        'help_block' => 'Provide a comma separerated list',
                    ],
                ]);
            }
        } else {
            foreach(['multiple', 'extended', 'choices'] as $field_name) {
                if($form->has($field_name)) {
                    $form->remove($field_name);
                }
            }
        }
    }
);
```

Can be closed since it is not a bug.

**Comment by htollefsen** [comment]
@HeahDude Thank you very very much!
