### ISSUE TITLE
[Asset] Versionize assets according to a Manifest

### ISSUE THREAD

**Issue by regularjack** [symfony/symfony#19945]
I would like the Asset component to be able to version assets according to a *Manifest*. A manifest is simply a map of paths to their versioned selves, for example:

```
/images/foo.png => /images/foo-123abc.png
/css/bar.css    => /css/bar-789xyz.css
```

To optimize client-side caching, an asset's URL should only change when its contents change. A simple way to achieve this is to append a hash of the file's content to the name of the file, as part of the build process.

Many frontend build tools do this and at the same time generate a manifest that maps the file's original name to its versioned name.

Supporting this use case would make it easy to "hook" frontend build tools with the Asset component.

This can be achieved by a `ManifestVersionStrategy` class whose constructor takes an array representing the manifest:

```php
$manifest = array(
    '/images/foo.png' => '/images/foo-123abc.png',
    '/css/bar.css'    => '/css/bar-789xyz.css',
);

$versionStrategy = new ManifestVersionStrategy($manifest);

// Returns '/images/foo-123abc.png'
$versionStrategy->applyVersion('/images/foo.png');

// Returns '/css/bar-789xyz.css'
$versionStrategy->applyVersion('/css/bar.css');

// Returns '789xyz'
$versionStrategy->getVersion('/images/foo.png');
```

This is a followup to PR #19418

**Comment by javiereguiluz** [comment]
@regularjack thanks for proposing this feature.

In my experience, this asset strategy is not common enough to include it by default. But let's wait for more opinions about this idea.

Besides, you can already build your own asset strategy. See [this PR](https://github.com/symfony/symfony/pull/17532) for details, because this feature is not documented yet (well do that [here](https://github.com/symfony/symfony-docs/issues/6205)).

**Comment by ro0NL** [comment]
I think version strategies should be exchangeable, this is limited to a specific number of known assets, ie. it will throw if not found? We shouldn't do that by design imo.

A manifest is usually output, not input.

**Comment by regularjack** [comment]
Thank you for the feedback. Thinking further about this and since we're able to specify a custom strategy (I wasn't aware this was possible), I agree this feature probably does not belong in the Asset component. Closing.
