### ISSUE TITLE
Codecov (or similar) integration

### ISSUE THREAD

**Issue by uuf6429** [symfony/symfony#19957]
Hey,

I was wondering, is there any particular reason why the symfony repo isn't connected with a code coverage tool like [codecov.io](https://codecov.io/)?

I think it would be quite useful, especially to contributors.

**Comment by iltar** [comment]
Actually the longer I've been writing tests, the less code coverage means to me. Code coverage is nice for unit-tests to see which cases you've missed, but imo that's about it. If this is something you want to know, phpunit already ships with working coverage support.

**Comment by uuf6429** [comment]
@iltar I know, and codecov simply prints out phpunit clover coverage... but I'm not even talking about the coverage rate at this point.

It's simply the fact that tools like codecov may help answer things like "why did coverage drop so much between commits" which may lead to discovering many unexpected scenarios.

Enabling this tool costs absolutely nothing (financial, risk or effort).

**Comment by fabpot** [comment]
I totally agree with @iltar. I don't want to go down this road as all of a sudden, we will get many PRs just to increase "code coverage", which by itself is a vanity metric.

**Comment by uuf6429** [comment]
I have to politely disagree, especially considering we're mixing project contribution policy with tools that may decrease bugs (especially ones that are hard to detect).

**Comment by iltar** [comment]
I can write tests that will test nothing but still cover a full class. I think the quality of tests is important and if it's a test simply to increase coverage, it will have no meaning and bugs will be hidden in "tested"code instead of found and dealt with.

**Comment by uuf6429** [comment]
I do not disagree with that. This tool can definitely be misused.

I think it is up to contribution policy and good code review to disallow/correct such misuse.

But anyway, I think this argument went past it's point, so I won't persist.
