### ISSUE TITLE
Book feature on symfony.com

### ISSUE THREAD

**Issue by packtpartner** [symfony/symfony#19968]
Hi,

Packt is proud to publish a new book on Symfony.
[Mastering Symfony](https://www.packtpub.com/web-development/mastering-symfony)

We would appreciate if you could create a Resources or Books page to feature this book on symfony.com. I think it will help many developers in their learning. 

Let me know if something like this can be done.

Thanks in advance.

**Comment by jakzal** [comment]
This repository is used for Symfony development. Perhaps a more appropriate one for your request would be https://github.com/symfony/symfony-marketing (although I'm not sure if it will be accepted).
