### ISSUE TITLE
[Forms] inject options to DoctrineType Loader in Symfony 3.x

### ISSUE THREAD

**Issue by Smart-Core** [symfony/symfony#19962]
How to inject options to DoctrineType Loader in Symfony 3.x? In Symfony 2.x branch it used to be in that way:

```
$loader = function (Options $options) {
	$loader = $this->getLoader($options['em'], $options['query_builder'], $options['class']);
	$loader->setMyOption($options['my_option']);

	return $loader;
};
```

Code form was that:

```
$form->add('tags', 'entity', array(
   'class' => 'Acme\Entity\MyTag',
   'loader' => $loader,
   'my_option' => 'some_value',
))
```
Now it need to discribe that method:

```
public function getLoader(ObjectManager $manager, $queryBuilder, $class)
{
	return new FolderLoader($manager, $queryBuilder, $class);
}
```
How to inject custom options to Loader from form?

**Comment by HeahDude** [comment]
You can either implement the [`ChoiceLoaderInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Loader/ChoiceLoaderInterface.php) and pass the instance using the `choice_loader` option, or use the [`query_builder` option](http://symfony.com/doc/current/reference/forms/types/entity.html#query-builder) to customize the behaviour of the default loader.

**Comment by Smart-Core** [comment]
Please. can you help me to understand how to rewrite this code https://gist.github.com/Smart-Core/7e423ac9a3ff1907176d23e1734818a7 with choice_loader option to working in Symfony 3.x? Whith example, please :)

**Comment by xabbuh** [comment]
I am sorry, but we use GitHub only to discuss about the development of the framework. Please use one of the [support channels](http://symfony.com/support) if you need help with your code.

**Comment by Smart-Core** [comment]
Maybe some thing is broken? because I can't found the way to inject custom options to the choice loader...

In Symfony2.x all works correctly.

**Comment by HeahDude** [comment]
The `loader` option has been deprecated in 2.7 in favour of `choice_loader` option, but you should not need to change something else as you extends `DoctrineType` overriding `getLoader()` is the way to go. Maybe you could use a normalizer instead of defining `loader` option lazily.
