### ISSUE TITLE
[Bug]  Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection"

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#19976]
I use latest stable version of Symfony (3.1.X) and get it error

```                                                                                                                         
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                    
  Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection".  
                                                                                                                         

Exception trace:
 () at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:503
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceInlinedDefinitionsSetup() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:665
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:691
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServices() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:152
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:632
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:478
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:117
 Symfony\Component\HttpKernel\Kernel->boot() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:68
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /bin/console:29
```
i checked at @https://github.com/symfony/symfony/issues/8425 this issue is closed but i got it

**Comment by blaues0cke** [comment]
@ad3n What have you done to get rid of this issue?

**Comment by ad3n** [comment]
@backbone87 : :+1: yes the issue gone :+1:

**Comment by blaues0cke** [comment]
@ad3n Yes. I am facing the same issue when I update all the dependencies in my project, so it would be nice to know what you did to fix it in your project! :-)

**Comment by ad3n** [comment]
@backbone87 : Just make sure your service dependencies is not depend the entity manager service or related it. You can use other approach such as, use call to pass dependency to your service instead of passing directly on constructor.

**Comment by sstok** [comment]
It seems you referenced the service to itself?

**Comment by blaues0cke** [comment]
I understand the error, but I got the same error message as @ad3n and since this error only occurs after a `composer update` its very hard to figure out the service or listener that causes this problem since I get this in a pretty big project. This is why I am asking! :-)

**Comment by robfrawley** [comment]
As noted in @8425:

> This is a circular reference. This object graph requires to instantiate the entity manager before instantiating Foo, and to instantiate Foo before the TestListener. But the TestListener needs to be instantiating when building the doctrine EventManager required by the EntityManager. And here, you see the issue: where can we start instantiating ? nowhere.

Your code needs to be refactored to remove such circular reference issues; there is no other feasible path forward.
