### ISSUE TITLE
Slow performance in dev mode since "Use VarDumper in the profiler"

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#19978]
Since https://github.com/symfony/symfony/commit/41a76494ec8416965e2444a7fe2ffce2dbb9a3e8 forms are very slow in dev mode.

Example: Symfony-Demo, `PostType` (`/de/admin/post/1/edit`), added these two fields:

```php
        $builder
        // ...
            ->add('country', CountryType::class, [
                'mapped' => false,
            ])
            ->add('choice', ChoiceType::class, [
                'mapped' => false,
                'choices' => range(1, 10),
                'expanded' => true,
                'multiple' => true,
            ])
```

Blackfire comparison (from commit before 41a76494ec8416965e2444a7fe2ffce2dbb9a3e8 to current master): [+645%, 227 ms → 1.69 s](https://blackfire.io/profiles/compare/03ec2035-852c-4e49-b2b1-229cbb9ae287/graph)

In a real-world form in a project it is: 180 ms → 4.2 s

ping @wouterj

**Comment by gharlan** [comment]
The memory usage difference is also remarkable: +501% (see blackfire comparison)

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
@gharlan can you please try #19986?

**Comment by gharlan** [comment]
Thanks a lot, much better, but still slower than before 41a76494ec8416965e2444a7fe2ffce2dbb9a3e8

My real world form (measured with symfony profiler):
commit before 41a76494ec8416965e2444a7fe2ffce2dbb9a3e8: ~ 180 ms
41a76494ec8416965e2444a7fe2ffce2dbb9a3e8: ~ 4.2 s
your pr: ~ 500 ms

**Comment by gharlan** [comment]
Symfony Demo with two additional fields (blackfire)
commit before 41a7649: 227ms
current master: ~ 1.69 s
your pr: ~ 363 ms

**Comment by nicolas-grekas** [comment]
Can you try changing the two `setMaxItems(50)` to `setMaxItems(1)` in FormDataCollector to if it gets acceptable? We'll then have to decide which number between 1 & 50 is best for the use case.

**Comment by gharlan** [comment]
my real world form with.. 
`setMaxItems(1)`: ~ 340 ms
`setMaxItems(10)`: ~ 400 ms
`setMaxItems(20)`: ~ 425 ms
`setMaxItems(30)`: ~ 445 ms
`setMaxItems(40)`: ~ 460 ms
`setMaxItems(50)`: ~ 470 ms (500 ms was too high in previous comment)

**Comment by nicolas-grekas** [comment]
So, should we stop here? Is 50 OK or should be lower it? To me it's OK if we're slower than before: this time is added only to `kernel.terminate`. And the benefit is worth it (look at the profiler how beautiful it is :) )
WDYT?

**Comment by gharlan** [comment]
Let us go with 50. :+1: Imo it is not worth to decrease the number.

Also: I think my real world form has an unusual amount of checkboxes etc.
4.2 s wouldn't be acceptable, but I think 470 ms is ok for this case. ;)

> look at the profiler how beautiful it is :)

Didn't pay attention to it until now, only had a look to the permorfance difference. ;)
Loving it! ❤️ Thanks all of you.

**Comment by nicolas-grekas** [comment]
PR updated, not to 50, but to limit to the 2nd depth level.

**Comment by gharlan** [comment]
@nicolas-grekas updated to current master. It is much slower than your pr 2 days ago.

commit before 41a7649: ~ 180 ms
41a7649: ~ 4.2 s
your pr 2 days ago: ~ 470 ms
current master: ~  3.7 s

**Comment by nicolas-grekas** [comment]
See #20022, `setMaxItems(25)`
