### ISSUE TITLE
minimum language level of PHP7 for Symfony 2.7 dependency ocramius/proxy-manager

### ISSUE THREAD

**Issue by chrisdlangton** [symfony/symfony#19984]
```Warning: Unsupported declare 'strict_types' in /vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19```

My runtime: PHP 5.6.25 with Xdebug 2.4.1

PHP7 introduced `strict_types` and Symfony 2.7 is meant to to support PHP 5.6 right?

After install i can see the culprit is here;

requires of `"ocramius/proxy-manager": "~0.4|~1.0|~2.0"` found in th composer.json file;
vendor/symfony/symfony/composer.json

This dependency brings Symfony 2.7 up to minimum language level of PHP7.

Perhaps lock the dependency to a version that works with the target PHP language levels for Symfony 2.7

EDIT:
checking my composer.lock i can see that the last known working version of `ocramius/proxy-manager` is `1.0.2`. This language level compatibility issue can be resolved by locking to that version in the symfony composer.json

**Comment by xabbuh** [comment]
It looks like you are building the lock file in an environment that uses PHP 7 and thus pulls in this dependency. You should rather avoid that or explicitly configure the PHP version of your production server using Composer's platform option.

**Comment by chrisdlangton** [comment]
@xabbuh thank you for the reply

We do have `"php": ">=5.3.3"` defined already however this doesn't account for Symfony not locking compatible versions of it's own dependancies. 

Regarding the environment, as mentioned the runtime was 5.6.25. Entertaining that composer might somehow locate another PHP binary I searched and now certain there is no other PHP version installed on the machine nor is there any alternative PHP versions in the file system or available in the PATH.

I'd like to understand if Symfony is in agreeance that incompatible dependency versions should be addressed and locked to ensure stability of the framework?

**Comment by xabbuh** [comment]
This won't solve your issue. The lock files of your dependencies are not taken into account when Composer install the packages your application needs. This is something you have to take care of. On the framework level, we can only ensure that Symfony works with either version.

**Comment by chrisdlangton** [comment]
@xabbuh by "lock" i mean set the version constraints on your deps, not to be confused with a `composer.lock` file.

**Comment by xabbuh** [comment]
I don't see what we need to change here. We do not forbid any version. So you are free to use whatever version you want (we need to support 2.0 for PHP 7 users). What are the exact steps you did to end up with an incompatible version locally?

**Comment by chrisdlangton** [comment]
@xabbuh you're response isn't clear to me, perhaps i could explain with less room for misunderstandings;

1) vendor/symfony/symfony/composer.json
This file tell the users composer how to install the symfony package.

2) Symfony states that the dependancy package of `"ocramius/proxy-manager"` is known to work at versions `"~0.4|~1.0|~2.0"`

3) I am a user and my composer on my local machine runs php 5.6.25 and i invoke composer on my project that requires symfony as a dependancy
3a) composer follows my project composer.json dependacy of `"symfony/symfony": "2.7.*"` and i get version `2.7..18`
3b) composer follows symfony's vendor/symfony/symfony/composer.json and installs `"ocramius/proxy-manager": "~0.4|~1.0|~2.0"` and i get version `2.0.3`
4) I get PHP7 level code excpetions when i run with XDebug
4a) my investigation leads me to identify https://packagist.org/packages/ocramius/proxy-manager with a minimum php language level of 7.0.0
4b) I didn't define `"ocramius/proxy-manager": "~0.4|~1.0|~2.0"` and i can see `"symfony/symfony": "2.7.*"`brought it in as a dependancy
4c) I understand `"symfony/symfony": "2.7.18"` should be compatible with php 5.6
5) I revert my `composer.lock` file and return to `"symfony/symfony": "2.7.18"` which also locked at the tim i install  "ocramius/proxy-manager": "1.0.2"
6) Raise this bug report

**Comment by xabbuh** [comment]
Are you sure that the PHP version you use to run Composer actually is 5.6? Can you please show your complete `composer.json` file?

**Comment by chrisdlangton** [comment]
@xabbuh not an issue, this is it (notice we do not define the package in question);

```
{
  "name": "ladoo/brolly-cms",
  "license": "proprietary",
  "type": "project",
  "autoload": {
    "psr-0": {
      "": "src/",
      "SymfonyStandard": "app/"
    }
  },
  "repositories": [
    {
      "type": "vcs",
      "url": ""
    }
  ],
  "require": {
     "php": ">=5.3.3",
    "symfony/symfony": "2.7.*",
    "doctrine/orm": "2.5.*",
    "doctrine/dbal": "2.5.*",
    "doctrine/doctrine-bundle": "1.5.*",
    "symfony/assetic-bundle": "2.7.*",
    "symfony/monolog-bundle": "~2.7",
    "sensio/distribution-bundle": "4.0.*",
    "sensio/framework-extra-bundle": "3.0.*",
    "incenteev/composer-parameter-handler": "2.0.*",
    "jms/serializer-bundle": "0.*",
    "friendsofsymfony/rest-bundle": "1.*",
    "friendsofsymfony/user-bundle": "1.*",
    "symfony/swiftmailer-bundle": "^2.3",
    "ladoo/brolly-utils": "dev-master",
    "aws/aws-sdk-php-symfony": "~1.0",
    "doctrine/doctrine-migrations-bundle": "^1.0",
    "fennb/phirehose": "dev-master"
  },
  "require-dev": {
    "sensio/generator-bundle": "2.5.*",
    "escapestudios/symfony2-coding-standard": "~2.0",
    "hot/phpunit-runner": "dev-master",
    "squizlabs/php_codesniffer": "^2.7",
    "phpunit/phpunit": "5.4.*"
  },
  "scripts": {
    "post-root-package-install": [
      "SymfonyStandard\\Composer::hookRootPackageInstall"
    ],
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
    ]
  },
  "config": {
    "bin-dir": "bin"
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-web-dir": "web",
    "symfony-assets-install": "relative",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    }
  }
}
```

Again, not sure how this helps as the package in question is part of symfony **not** any single project that uses symfony...

Note: changing to `"php": "5.6.*"` does not help, symfony still brings in 2.0 version of the package in question and nothing any single project can do will change that only symfony can define it "working" versions of its dependancies.

**Comment by jakzal** [comment]
> composer follows symfony's vendor/symfony/symfony/composer.json and installs "ocramius/proxy-manager": "~0.4|~1.0|~2.0" and i get version 2.0.3

You can only get 2.0.3 if you run PHP 7, or set platform to PHP 7.  Perhaps there's a platform requirement locked in your composer.lock (look for `"platform": {}`)? 

> symfony still brings in 2.0 version of the package 

Symfony allows you to use any version of this package. 2.0 is chosen based on the platform, not because of Symfony definitions.

**Comment by chrisdlangton** [comment]
@jakzal excellent! You've explained it perfectly AND found the root cause. Thank you.

Our composer.lock had `7.0.10` for the php version.

I guess this has shown that the magic mapping of `"~0.4|~1.0|~2.0"` to the php engine version is what makes it difficult to diagnose an issue like this (unless you've seen it before).

Cheers
