### ISSUE TITLE
php app/console server:run

### ISSUE THREAD

**Issue by sam2908** [symfony/symfony#20005]
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: date_default_timezone_get(): It is not safe to rely on the system'  
  s timezone settings. You are *required* to use the date.timezone setting or  
   the date_default_timezone_set() function. In case you used any of those me  
  thods and you are still getting this warning, you most likely misspelled th  
  e timezone identifier. We selected the timezone 'UTC' for now, but please s  
  et date.timezone to select your timezone.

**Comment by xabbuh** [comment]
I am sorry, but we use GitHub only to track the development of the framework. Please use one of [the support channels](http://symfony.com/support) to seek for help. Thank you for understanding.
