### ISSUE TITLE
[DependencyInjection] - AddSecurityVotersPass - setVoters

### ISSUE THREAD

**Issue by andersonscr** [symfony/symfony#20004]
There are legacy bundles that have dependence definition "security.access.decision_manager " even using the debug mode. Example: JMSSecurityExtraBundle.

Affected class : Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\AddSecurityVotersPass

Solution: conditionally call 'setVoters' of class 'debug.security.access.decision_manager', but always call 'setVoters' of class 'security.access.decision_manager'

**Comment by iltar** [comment]
I'm not sure if legacy bundles should be supported by symfony, it should be bundles supporting specific (or a wide range of) symfony versions.

**Comment by xabbuh** [comment]
I am not sure if I really understand your issue. The `DebugAccessDecisionManager` actually calls `setVoter()` on the wrapped manager: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php#L64-L66

So can please explain a bit more what issue you are experiencing?

**Comment by andersonscr** [comment]
I'm migrating my project from symfony2 to last symfony revision. 

When I was using annotation 'JMS\SecurityExtraBundle\Annotation\Secure', then my project broke because SecurityExtraBundle uses 'security.access.decision_manager' to access Decision Manager in the development environment.

Maybe the bundle SecurityExtraBundle need fix it.

**Comment by andersonscr** [comment]
The proposed solution was change **function process** of class **Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\AddSecurityVotersPass** to:

`if($container->hasDefinition('debug.security.access.decision_manager')){`
`    $adm = $container->getDefinition('debug.security.access.decision_manager');`
`    $adm->addMethodCall('setVoters', array(array_values($voters)));`
`}`
`$adm = $container->getDefinition('security.access.decision_manager');`
`$adm->addMethodCall('setVoters', array(array_values($voters)));`

**Comment by xabbuh** [comment]
As said, the `DebugAccessDecisionManager` forwards the call to `setVoter()` to the wrapped manager. Please rather describe your actual issue and how to reproduce it.
