### ISSUE TITLE
[FORM] isSubmitted() returns false when in fact, the form was actually submitted.

### ISSUE THREAD

**Issue by eggmatters** [symfony/symfony#20013]
Form create from Controller:
```
/**
* @Route("/site/options/{optionId}/entities/{entId}/update", name="ent_update")
* @Method({"GET"})
*/
public function updateAction(Request $request, $entId,  $optionId) {
        $ent = new Entity();
        $form = $this->createForm(EntityCreateType::class, $ent, array(
            'custom_options' => $this->getCustomOptions($optionId), // returns array of select options
            'action' => $this->generateUrl('ent_update_save'),
            'method' => 'put'
        ));
       . . .
}
```
EntityCreateType.php:
```
public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add( 'name', Type\TextType::class, [
                'label' => 'Name'
            ]
        )
        ->add('custom_options', Type\ChoiceType::class, [
                'label' => 'Custom Options',
                'choices' => $options['custom_options'],
                'mapped' => false
        ])->add('submit', Type\SubmitType::class, [
                'attr' => ['class' => 'btn-success btn-outline'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Entity::class,
            'custom_options' => []
        ]);
    }
```
Form submit route (controller method):
```
/**
 * @Route("/site/entities/{entId}/update/", name="ent_update_save")
 * @Method({"PUT"})
 */
public function updateEntityAction(Request $request, $entId) {
        $ent = new Entity();
        $form = $this->createForm(EntityCreateType::class, $ent);
        $form->handleRequest($request)
        $form->isSubmitted(); // RETURNS FALSE!!!
        $form->getData(); // EMPTY!
 }
```

The `$form->isSubmitted()` in updateEntity action returns false. 
`$form->getData()` is empty.

The updateEntityAction() method in the controller is reached via the 'ent_update_save' route, by the action set on the form which is triggered by the Submit Event In the DOM. Which by all accounts indicates that the form has indeed been submitted. 

The $request->request->parameters->{form_id} array is populated:
```
Array(
   'name' => "The name actually entered on the form and SUBMITTED",
   'custom_options' => 'The value of the custom option that was actually selected on the form.'
   'submit' => ""
)
```
The submit event occurred, making an http request to the server to the path indicated in the "action" attribute on the form.

The http method is set to "PUT" which most servers alias as a 'POST'.

The 'POST' data is populated in the Request object.

The FormConfigBuilder's RequestHandler has set the Form instances submitted property to false in the handleRequest() call.

**Comment by xabbuh** [comment]
It looks like you never configure your form to act on PUT requests. This means that the request handler will not submit the form at all. If this is not the cause of your issue, please fork the Symfony Standard Edition and make the changes that are needed to reproduce your problem.

**Comment by eggmatters** [comment]
yeah, the put method was configured. Forgot to add it to my code sample. Updating now.

**Comment by xabbuh** [comment]
@eggmatters That's only true for your `updateAction()` which renders the form, but not for the `updateEntityAction()` which handles the form after it is submitted.

**Comment by eggmatters** [comment]
@xabbuh Not sure I'm following. The form which is rendered is as shown. The route for updateAction is specified with "PUT" as the method:
```
 * @Route("/site/entities/{entId}/update/", name="ent_update_save")
 * @Method({"PUT"})
public function updateEntityAction( . . .
```

BTW, changing the method on the form and the accepted method on the route to "POST" still has no effect. I have other forms which don't have this problem. The only departure is that one of the fields in the EntityCreateType class is "unmapped" I'm not sure if that has any effect though.

**Comment by eggmatters** [comment]
Changing the method in the Routing specification to:
`@Method({"PUT","POST"})` does in fact change the 'submitted' property of the form object to true, but `$form->getData()` is empty.

**Comment by eggmatters** [comment]
And, I should point out that, I have another createAction in the controller which creates the same form, just with the action pointing to a different route (i.e. controller method), and That submit works just fine.

**Comment by xabbuh** [comment]
@eggmatters Your route is allowing PUT requests, but in that method you do not configure your form to handle them.

You should change:

```php
$form = $this->createForm(EntityCreateType::class, $ent);
```

to

```php
$form = $this->createForm(EntityCreateType::class, $ent, array(
    'method' => 'put'
));
```

**Comment by eggmatters** [comment]
Thanks! that appears to have worked.

**Comment by aliemre** [comment]
Make sure that `$form->handleRequest($request)` is placed before condition. For example:

```
$ent = new Entity();
$form = $this->createForm(EntityType::class, $ent);
$form->handleRequest($request);

if ($form->isSubmitted() && $form->isValid()) {
    // ...
}
```

**Comment by d-yuri** [comment]
Have same issue. In my case, it was a mistake from my side I forgot to extend my custom type where I off csrf_protection. 
So I got invalid data with no one error and `$form->isSubmitted()` return `false`
Maby its help someone.

**Comment by PHPTCloud** [comment]
I solved my problem when overwrite parent method `getBlockPrefix`, e.g.

Input data
```json
{
    "date_field_id": 1273633
}
```

FormType
```php
<?php

namespace App\Form;


class CreateOrdersListType extends AbstractType
{
    ...
    public function getBlockPrefix(): string
    {
        return '';
    }
    ...
}

```

**Comment by sovetski** [comment]
Same issue here, all suggestions do not work

EDIT: I found the problem. I was using "PATCH" method, but my "http_method_override" was set to "false" (config\packages\framework.yaml)

https://symfony.com/doc/current/forms.html#changing-the-action-and-http-method
