### ISSUE TITLE
Session always started by Security Firewall component

### ISSUE THREAD

**Issue by albenik** [symfony/symfony#20023]
I can not avoid session start for anonymous users as described in http://symfony.com/doc/current/session/avoid_session_start.html 

because session always started by 
https://github.com/symfony/symfony/blob/v3.1.4/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L83

**Comment by iltar** [comment]
> This means that if you need to avoid creating a session cookie for some users, it can be difficult: you must completely avoid accessing the session.

If you use a firewall, it will most likely check the session to see if someone is authenticated.

**Comment by backbone87** [comment]
The problem is that checking the session will start it. So maybe the security component can early return, if there isnt even a session started yet?

**Comment by iltar** [comment]
Then how is it supposed to check if you're logged in? Best to do is simply shut off security for that route.

**Comment by albenik** [comment]
At leas security component could check $request->hasPreviousSession() as proposed in article.
Especially the Request instance was already got a few lines below.

**Comment by iltar** [comment]
And what if I need an anonymous authentication on that URL and there was no session before?

**Comment by nicolas-grekas** [comment]
Closing as this should have been fixed in 3.4 with session-related improvements.
