### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by mario6097** [symfony/symfony#20021]
hi

at http://symfony.com/doc/master/cmf/bundles/content/index.html
link/button 'Download as pdf' opens a  "Not found page" http://symfony.com/pdf/Symfony_cmf_2.0.pdf?v=4

cheers
mario

**Comment by iltar** [comment]
As this is about the documentation, can you open a ticket in [symfony/symfony-docs](https://github.com/symfony/symfony-docs) instead?

**Comment by javiereguiluz** [comment]
I'm closing this in favor of this doc issue: https://github.com/symfony/symfony-docs/issues/7002
