### ISSUE TITLE
strange behaviour of format in DateTimeType::Class with widget single text

### ISSUE THREAD

**Issue by frian** [symfony/symfony#20031]
Hi,

I recently had a [strange bug](https://github.com/symfony/symfony/issues/19881) on a project, which disappeared after an ubuntu upgrade.

Yesterday it was back, no change in this part of the code, no sf update (3.1.4), ubuntu updates.

Same thing 2 hours difference. As @javiereguiluz mentionned it's the GMT offset.

I finally found it's the format option which causes this : 

            ->add('startdate', DateTimeType::class, array(
            		'widget' => 'single_text',
            		'format' => 'dd/MM/yyyy HH:mm',
            		'label'  => 'event.date.label',
            		'attr'   => array('class'=>'date')
            ))

I also tried other formats like

        'format' => 'yyyy-MM-dd HH:mm'

with no change.

If I comment the format it works well.

I created some demo code [here](https://github.com/frian/symfony/tree/time-bug) with 3.2 dev.

It reproduces the bug, but with one hour error instead of two in 3.1.4.

I also tried stuff like set timezone in AppKernel with no change.

Thanks !

**Comment by mvrhov** [comment]
My comment from #19881 still applies.  It seems that the fixes from 2.7 were still not merged into the master (and probably other 3.x branches). So the bug still exists there.

**Comment by frian** [comment]
hi @mvrhov,

you are right and also my new hero :)

Applied to 3.1.4 and works.

Thanks a lot !
