### ISSUE TITLE
[HttpFoundation] "Deleting" a cookie sets "deleted" as cookie value

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#20049]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Cookie.php#L97

An empty string should be used to avoid collision when someone actually uses the value "deleted" in their cookie value space.

But wait, you may say, the cookie will never be submitted in following requests, because it gets set as already expired. However HTTP clients are not forced to dismiss expired cookies and could submit them in requests. https://tools.ietf.org/html/rfc6265 for reference.

**Comment by unkind** [comment]
> However HTTP clients are not forced to dismiss expired cookies and could submit them in requests. https://tools.ietf.org/html/rfc6265 for reference.

Quote from the RFC:
> Finally, to remove a cookie, the server returns a Set-Cookie header
   with an expiration date in the past.

**Comment by backbone87** [comment]
Nowhere in the RFC it is mentioned that cookies with an expiration date in the past MUST NOT be stored by the client. Also in section 5.4. about constructing the cookie header from a set of stored cookies it is not mentioned to filter out expired cookies.

**Comment by unkind** [comment]
> A cookie is "expired" if the cookie has an expiry date in the past.

> The user agent MUST evict all expired cookies from the cookie store
> if, at any time, an expired cookie exists in the cookie store.

**Comment by backbone87** [comment]
you are correct. though this RFC is from 2011 which is fairly new, idk how the requirements of older obsoleted RFCs were set. but when i dont find the stackoverflow answer i am pretty much lost on this argument.

still using the empty string is more elegant i think, its also used in the "delete cookie" example on php.net

**Comment by unkind** [comment]
> still using the empty string is more elegant i think, its also used in the "delete cookie" example on php.net

It uses "deleted" string as well: https://github.com/php/php-src/blob/1c295d4a9ac78fcc2f77d6695987598bb7abcb83/ext/standard/head.c#L130

**Comment by sh4ka** [comment]
I guess this is not an issue with any modern (~5 years) http client. This is not an issue atm.

**Comment by backbone87** [comment]
If this is the case, it will never become an issue, because i dont think http clients will evolve backwards.
