### ISSUE TITLE
No way to override the Content-Type header in Browserkit Request

### ISSUE THREAD

**Issue by Pherserk** [symfony/symfony#20042]
Making a request with the method request() will always override the content-type header, with application/x-www-form-urlencoded.

Example to reproduce the problem

``` php
 $client = static::createClient();
 $headers['content-type'] = 'some.other valid IANA';
 $client->request('POST', '/api/test', [], [], $headers, 'HELO');
```

the request sent to the controller will contain application/x--www-form-urlencoded

Also trying with:

``` php
$headers['HTTP_content-type'] = 'some.other valid IANA' same result
```

**Comment by ro0NL** [comment]
@Pherserk can you try `CONTENT_TYPE` or `HTTP_CONTENT_TYPE`... FYI you're passing in server parameters, not headers. Maybe https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/HttpFoundation/ServerBag.php#L31 kicks in some how..

However at first sight your version should work too based on https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/HttpFoundation/HeaderBag.php#L114

Can you debug where stuff gets lost?

**Comment by Pherserk** [comment]
@ro0NL 

Just added a failing test on this fork at line 167
https://github.com/Pherserk/browser-kit/blob/master/Tests/ClientTest.php

But due to the nature of the mock TestClient, I think it is not reliable.

**Comment by Pherserk** [comment]
@ro0NL 
Probably I'm messing up things, some headers passed in the ServerBag are translated to headers.
I should use the headers bag, so what should be the correct way to call the client method I'm using to send the request?
Many thanks.

**Comment by ro0NL** [comment]
From your issue i kinda assumed you were using [`WebTestCase::createClient`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L31) So perphaps compare to what `Symfony\Component\HttpKernel\Client` does, ie filtering the request [correctly](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Client.php#L145), here's where the magic happens.

Next your `TestClient::doRequest` is foobar.. it doesnt use `$request` at all..  so yes it's not reliable.

Im lost.. what exactly is the issue? `WebTestCase`, `TestClient`?

**Comment by Pherserk** [comment]
Looking at the Client class in Browserkit component:

 $this->internalRequest = new Request($uri, $method, $parameters, $files, $this->cookieJar->allValues($uri), $server, $content);

$this->request = $this->filterRequest($this->internalRequest);

if I dump the internalRequest, it preserves the content-type header, while request, does override it with the x-form one value.
But I can't understand how this happens.

**Comment by ro0NL** [comment]
This is guessing.. i can have a look tonight maybe. But by default the request is not filtered.. ie `$this->internalRequest === $this->request`. So something else's happening down the chain.. cant you search for `application/x--www-form-urlencoded` and go from there?

**Comment by Pherserk** [comment]
@xabbuh i think we can close this issue,
I have opened this pull request, that is related to this, that is not a bug, but a sometimes difficult to spot behaviour.

https://github.com/symfony/http-foundation/pull/32

**Comment by petertanath** [comment]
@xabbuh @javiereguiluz @ro0NL 
according to this line https://github.com/symfony/http-foundation/blob/master/Request.php#L369
If you set 
$client->setServerParameter('CONTENT_TYPE' ,'ANY OTHER FORMAT');
OR
$client->request(
            'POST',
            'URL',
            [],
            [],
            ['CONTENT_TYPE' => 'ANY OTHER FORMAT'],
            ''
        );
this should works

**Comment by javiereguiluz** [comment]
Closing because this should work as explained by @petertanath. @ro0NL thanks for your help here too.

**Comment by yapro** [comment]
Maybe this will help us https://github.com/symfony/browser-kit/pull/10
