### ISSUE TITLE
Symfony CollectionType

### ISSUE THREAD

**Issue by bogdaniel** [symfony/symfony#20059]
Not really sure if this is a bug or something but here it goes.
If you want to use a CollectionType to do a self reference on the same field it won't work
Given two entities ( in my example Survey and Headquarter):

https://gist.github.com/bogdaniel/a0bcc848e2bd282382f45a2bd15cc0e2

**Comment by HeahDude** [comment]
Hi @bogdaniel Can you please at your gist to a fork of symfony standard to see if we can reproduce your issue. Thanks!

**Comment by bogdaniel** [comment]
Here is a git repo from my localhost https://github.com/bogdaniel/symfony-collection

**Comment by dmaicher** [comment]
Seems a bit weird to me how your form types are built :wink: 

Isn't this what you want to have? A list with all existing `Headquarter` entities when you create a new `Survey`?

```php
class SurveyType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('headquarter', EntityType::class, [
                'class' => Headquarter::class,
                'label' => false,
                'multiple' => true
            ])
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Survey::class
        ));
    }
}

**Comment by dmaicher** [comment]
@bogdaniel does this solve your issue?

**Comment by xabbuh** [comment]
Closing here for now due to the lack of feedback.

@bogdaniel Please let us know if @dmaicher's example doesn't help you and if you still think that there is an issue we need to solve in Symfony.
