### ISSUE TITLE
[Debug] TypeError in ErrorHandler

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#20068]
In a command class I'm using something like this:

```php
        $imap = @imap_open('foo', 'bar', 'baz');

        if (!$imap) {
            throw new \RuntimeException(imap_last_error());
        }
```

When an imap error occurs, I get an uncaught TypeError:
> Uncaught TypeError: Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in /Users/gharlan/workspace/symfony_demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:368

Symfony: current master
PHP: 7.0.11

It is reproducibly with symfony demo by adding the code above to `ListUsersCommand::execute`:

![screenshot 2016-09-28 12 00 12](https://cloud.githubusercontent.com/assets/330436/18909251/2d56a7b2-8573-11e6-82c9-63f3fd4fda82.png)

**Comment by nicolas-grekas** [comment]
I guess this should be reported on the imap extension also, because having `Unknown` as file, `0` for line, and `null` for context is plain broken.

**Comment by fabpot** [comment]
If the imap extension does not behave correctly, we can indeed close this one as won't fix.

**Comment by nicolas-grekas** [comment]
@gharlan please open a bug report on bugs.php.net, here is a plain php reproducer:
```php
<?php

set_error_handler(function ($type, $message, $file, $line, $context) {
    if ($context) {
        $context = array_keys($context);
    }
    var_dump(compact('type', 'message', 'file', 'line', 'context'));
});

@imap_open('foo', 'bar', 'baz');
```

which displays:
```
array(5) {
  ["type"]=>
  int(2)
  ["message"]=>
  string(37) "imap_open(): Couldn't open stream foo"
  ["file"]=>
  string(35) "/home/nicolas/Code/symfony/test.php"
  ["line"]=>
  int(10)
  ["context"]=>
  array(7) {
    [0]=>
    string(4) "_GET"
    [1]=>
    string(5) "_POST"
    [2]=>
    string(7) "_COOKIE"
    [3]=>
    string(6) "_FILES"
    [4]=>
    string(4) "argv"
    [5]=>
    string(4) "argc"
    [6]=>
    string(7) "_SERVER"
  }
}
array(5) {
  ["type"]=>
  int(8)
  ["message"]=>
  string(59) "Unknown: Can't open mailbox foo: no such mailbox (errflg=2)"
  ["file"]=>
  string(7) "Unknown"
  ["line"]=>
  int(0)
  ["context"]=>
  NULL
}
```

which looks wrong

**Comment by wujku** [comment]
Problem still exists.

**Comment by nicolas-grekas** [comment]
See #21401

**Comment by stof** [comment]
has the issue been reported to PHP ?
