### ISSUE TITLE
allow_if in access_control for the login page.

### ISSUE THREAD

**Issue by albout** [symfony/symfony#20060]
Hello, 

I have a problem with the allow_if option in access_control for the login page. If i put an expression which return false, it does nothing, route works. If i put the same expression in @Route annotation like: @Route('/my-route', condition:"condition") condition worked and user's blocked. 

For information, my login page is from http://symfony.com/doc/current/security/form_login_setup.html.

Examples:

**not working:** 

access_control:
- { path: '/login', roles: IS_AUTHENTICATED_ANONYMOUSLY, allow_if: "request.getMethod() != 'GET'" } 

**working:**

@Route("/login", condition="request.getMethod() != 'GET'") works.

I checked and the route in access_control is the good one used. 
I also asked on irc before posting here.

Is this behavior normal? 

Thank you

Infos:

- Symfony 3.1.4
- PHP 5.6.24

**Comment by albout** [comment]
Yes, posted @ 5:39 on the chan officer iltar 👮  😄 

Yes lol, no reason to do this, it's just a quick example to show the issue. 
I want to do others things with the allow_if...

**Comment by iltar** [comment]
Come back to the channel and we can discuss it, this issue tracker is not for support questions 😄

**Comment by albout** [comment]
Ok i come thank you 👍
