### ISSUE TITLE
@Route value being injected into Request->$request by the provided in the @Route key

### ISSUE THREAD

**Issue by idchlife** [symfony/symfony#20062]
* @Route("/current/upload-{type}", requirements={"type": "avatar|background|gallery"})

Then I have Request $request argument and have 'type' key with provided value in $request->request->all()

If I'm not mistaken, $request->request is supposed to be POST only parameters?

**Comment by stof** [comment]
this looks really weird. I never saw this behavior. Have you checked the actual request being made does not also submit this value through POST ?

Please provide a reproducing case (you can for instance start a new projct based on Symfony standard edition and add the minimal code needed to reproduce it)

**Comment by idchlife** [comment]
Yes on clean Symfony install I cannot reproduce. Checking what else is used at my application that causes this.

**Comment by idchlife** [comment]
Problem solved. It's Swagger in NelmioApiDocBundle. It was sending also type because of requirements.

![image](https://cloud.githubusercontent.com/assets/4563032/18884375/d4a8d88e-84ef-11e6-806d-3c82b41d9de7.png)
