### ISSUE TITLE
[RFC][OptionsResolver] Pass a closure to *AllowedTypes method

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#20074]
For options with more complicated validation schemes, pass a closure which returns `true` for acceptable types and `false` for invalid types:

Question/Answer in [Stackoverflow](http://stackoverflow.com/questions/39751569/advanced-type-validation-with-optionsresolver-component).

**Before:**
```php
//...
function is_foobar($value) {
    return $value instanceof Foo && $value instanceof Bar;
}

$resolver = new OptionsResolver();
$resolver->setRequired('data');
$resolver->setAllowedTypes('data', 'foobar');
```

Confusing error message when invalid type:

```
InvalidOptionsException: The option "data" with value Baz is expected to be
of type "foobar", but is of type "Baz".
```

**After:**

```php
// ...
$resolver->setAllowedTypes('foo', function ($value) {
    return $value instanceof Foo && $value instanceof Bar;
});

$resolver->setAllowedTypes('bar', function ($value) {
    return is_subclass_of($value, 'Foo');
});
```

Ignore closure in error message.

If approved I can send a PR for that as well as works `setAllowedValues` method.

**Comment by HeahDude** [comment]
👎 on this, we have normalizers to do that. I've answered on stackoverflow:

```php
use Symfony\Component\Form\Exception\InvalidConfigurationException;

$resolver->setNormalizer('data', function(Options $options, $data) {
    if (!$data instanceof Foo && !$data instanceof Bar) {
        throw new InvalidConfigurationException('"data" option must implement "Foo" and "Bar" interfaces.');
    }

    return $data;
});
```

**Comment by backbone87** [comment]
even without closures it is possible just with allowed types config:
```php
$resolver->setAllowedTypes('data', [ Foo::class, Bar::class ]);
```

**Comment by HeahDude** [comment]
Nope, it will return `true` for one of them, not both.

**Comment by backbone87** [comment]
you are correct, didnt read his example correctly

**Comment by HeahDude** [comment]
Another thing is that there is no default message for a boolean returned by a closure. The normalizer gives you full control of what to test (even with dependencies) and throw the exception(s) you need.

**Comment by backbone87** [comment]
But then again the API design is discussable.
imagine someone explaining the options resolver:
"you have allowed types and normalizers, use normalizers for any transformation/cleaning you want to do and allowed types to do a type checking of passed values." - "how do i check, if the passed value is of a certain type and implements a specific interface?" - "if you want to do **this** kind of type checking you should screw the allowed types feature and use a normalizer"

**Comment by HeahDude** [comment]
@backbone87 each have their design, which is fine:
```php
$resolver->setAllowedValues('letter', array('A', 'B', 'C'));
$resolver->setAllowedTypes('number', array('int', 'float', 'SomeNumberClass'));
```
For the rest there is the normalizer. In fact whenever the exception message is not "wrong, use one of those ***", a normalizer should be used.

**Comment by yceruto** [comment]
Well, after I sleep on, I think my approach is wrong, because it's already done by using `setAllowedValues` or `addAllowedValues` methods:

```
$resolver->setAllowedValues('foo', function ($value) {
    return $value instanceof Foo && $value instanceof Bar;
});
```

So it's not necessary to use `setAllowedTypes` for this purpose. Sorry for the nose :(

**Comment by backbone87** [comment]
did know you can already pass a closure to setAllowedValues, yeah that pretty much ends all discussion on this
