### ISSUE TITLE
typescript error in symfony/translation

### ISSUE THREAD

**Issue by achmadk** [symfony/symfony#20084]
i got errors when type "tsc --watch" in command prompt (the image are attached). i use typescript version 2.0.2
![error symfony translation](https://cloud.githubusercontent.com/assets/8057028/18946777/9a78ba64-865a-11e6-89b5-73966b0e049e.PNG)

**Comment by iltar** [comment]
How is a fixture file in your vendor related to typescript? This file contains XML which seems to be related to a specific loader (QT?).

**Comment by fabpot** [comment]
Closing as there is no issue here, you should not watch the vendors.

**Comment by stof** [comment]
And you should not assume that any ``.ts`` file anywhere will be a typescript file. The ts extension was used by other tools before typescript was ever created.
