### ISSUE TITLE
Bc break between 2.8 and 3.0 for  ConstraintValidatorInterface (prevents Drupal 8 update to 3.1)

### ISSUE THREAD

**Issue by catch56** [symfony/symfony#20088]
ConstraintValidatorInterface is in both 2.8 and 3.0.

While the methods are identical, the use statement was added to change from the deprecated ExecutionContextInterface to the new version.

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Validator/ConstraintValidatorInterface.php

https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Validator/ConstraintValidatorInterface.php

What this means is that if you have 2.8 code implementing both interfaces, you can't update implementations of ExecutionContextInterface - because when they're passed into ConstraintValidatorInterface they're implementing the wrong interface.

Drupal.org issue is here: https://www.drupal.org/node/2721179

The only fix I can think of would be to add a new version of ConstraintValidatorInterface (and ConstraintValidatorFactoryInterface) to 2.8, which just point to the new interfaces, otherwise identical.

**Comment by stof** [comment]
you should make your custom validators extend the base class shipped in Symfony. This way, the difference in signature would be handled in Symfony itself, solving the issue. The fact that we have such a base class (and that all Symfony documentation always shows to use it) is what allowed the Symfony community to support both 2.7 and 2.8 even though there is a BC break in the interface itself

**Comment by catch56** [comment]
OK we weren't using that. Although neither ConstraintValidatorInterface nor ExecutionContextInterface mentions it, where in the docs is that mentioned?

**Comment by catch56** [comment]
That helps a bit, but not for one case:

We have two classes that both extend Constraint and implement ConstraintValidatorInterface.

In that case, they can't be updated to inherit from ConstraintValidator, because they already inherit from Constraint.

Additionally they can't be updated to not inherit from Constraint, because constraint validators type hint on Constraint rather than an interface.

I found a workaround though which was create a new base class, which extends Constraint, implements ConstraintValidatorInterface and provides the initialize method. Those two classes can then extend that to be compatible with 2.8, and only that class would need to be updated for 3.x to change the use statement.

Question is then, would Symfony accept a PR for 2.8 to add another base class doing the above, that would then a allow a Drupal 8 patch which only updates the dependency, otherwise it's still a bc break for us (albeit one I could personally live with).

**Comment by stof** [comment]
having the constraint being the validator itself looks really weird. Constraints are meant to be part of the mapping, which means you have lots of instance of them, and they get serialized in the cache. Constraint validators on the other hand are service-like instances. The validator only instantiate them once.
What is your use case for mixing the 2 responsibilities in the same class ?

And no, I would probably not accept a base class in core which would make it easy to mix these 2 different responsibilities in the same class, as this does not make sense to do it IMO.

**Comment by catch56** [comment]
That's a good point, I can't see a good reason for it either.

So the ConstraintValidator class does indeed provide everything. I think this could use docs in ConstraintValidatorInterface pointing to the base class, but thanks for the pointer. That should be the last blocker for Symfony 3 usage in Drupal 8 gone soon.
