### ISSUE TITLE
Deprecate SYMFONY__ environment variables

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20089]
Now that #19681 is merged, Symfony config has proper support for environment variables. So maybe it's time to deprecate the special [SYMFONY__ environment variables](http://symfony.com/doc/current/configuration/external_parameters.html) and remove them in Symfony 4.0.

**Comment by iltar** [comment]
I was already wondering if they were still serving a purpose, sounds good to me!

**Comment by fabpot** [comment]
Yes, we just need someone to submit a PR.
