### ISSUE TITLE
[Validator] Creating constraint with options in array after using array_walk

### ISSUE THREAD

**Issue by weckonet** [symfony/symfony#20106]
Hello! I found out about a rather unexpected interaction. This code doesn't work, throwing an _ConstraintDefinitionException (No default option is configured for constraint)_:

```php
$options = ['message'=>'Hello'];
array_walk($options, function(&$item) { $item = $item . ' world!'; });
$constraint = new Email($options); // Not working
```

In order to make it work, I have to use `reset($options)` after `array_walk()` so that I get a valid array pointer. I propose to either output a meaningful error message (that Constraint cannot be initialized without valid internal pointer) or to replace `is_string(key($options))` in `Symfony\Component\Validator\Constraint` to something like `is_string(array_keys($options)[0])`.

**Comment by backbone87** [comment]
can you please check your example? because i dont see for what that second line is good for, it has no relation to the first and third.

**Comment by weckonet** [comment]
Oh, sorry, `$a` was supposed to be `$options`, I rewrote variable names from my example for clarity but messed that up. 

Exactly. I actually just went through a similar scenario and almost went mad while debugging, because the reliance on array pointer is quite unexpectable.
