### ISSUE TITLE
Application exit code not properly handled, when having fatal exceptions, Symfony 2.8, PHP7

### ISSUE THREAD

**Issue by bozerkins** [symfony/symfony#20110]
when a command throws a fatal error in PHP7, the exception produced is handled by global error handler, not application error handler.

thus the error message is properly handled, but the exit code is not.

such code for example (for tests or more) could lead to such behavior, under Symfony 2.8 / PHP 7
`
$a = null;
$a->getSmth();
`
under PHP 5.3 the above command execution would exit with non zero exit code.
under PHP7.\* this would end up with exit code being zero, which is not good.

the problem is in the - Symfony/Component/Console/Application.php:124, 
where only \Exception class is catched
#20111

**Comment by bozerkins** [comment]
#20111

**Comment by sh4ka** [comment]
Can this be related to https://github.com/symfony/symfony/issues/19078 ??
OP: Can you verify is the same problem? Thanks a lot.

**Comment by bozerkins** [comment]
No. The problem is different.
#20110 - is about catching console application **fatal** exceptions in PHP7 (which are generated by PHP, not triggered by user)
#19078 - is about catching user exceptions, triggered in "kernel terminate" event dispatcher

**Comment by sh4ka** [comment]
Brilliant. Just ringed a bell for me and I wanted to make sure.
