### ISSUE TITLE
Doctrine collector breaks on master with twig 1.26@dev

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#20125]
After updating to twig 1.26@dev on symfony 3.2@dev things tend to crash;

```
An exception has been thrown during the compilation of a template 
("Method Symfony\Bridge\Twig\Extension\HttpKernelRuntime::controller() does not exist")
in "@Doctrine/Collector/db.html.twig".
```

see https://github.com/doctrine/DoctrineBundle/blob/1.6.4/Resources/views/Collector/db.html.twig#L113
and https://github.com/symfony/symfony/pull/20079#issuecomment-250965873

**Comment by fabpot** [comment]
1.26 is out now.

**Comment by ro0NL** [comment]
@fabpot the doctrine issue persists.. it happens when loading the toolbar.

![image](https://cloud.githubusercontent.com/assets/1047696/19022003/2d1c0356-88ce-11e6-8c62-713e1c86b2fe.png)


Exception is shown at `/_profiler/<token>`
