### ISSUE TITLE
[Response Class] No effect when calling setCharset() when Content-Type is set to "application/json".

### ISSUE THREAD

**Issue by bs-thomas** [symfony/symfony#20123]
I noticed that in the prepare() method in Http Foundation's Response Class, it ignores the character set in a case if the content type does not start with "text/".  I was using "application/json" for my type.

As I thought application/json is also a type of text, I was wondering if for this special case it should be allowed?

Code here:

```php
            // Fix Content-Type

            $charset = $this->charset ?: 'UTF-8';

            if (!$headers->has('Content-Type')) {

                $headers->set('Content-Type', 'text/html; charset='.$charset);

            } elseif (0 === stripos($headers->get('Content-Type'), 'text/') && false === stripos($headers->get('Content-Type'), 'charset')) {

                // add the charset

                $headers->set('Content-Type', $headers->get('Content-Type').'; charset='.$charset);

            }
```

I would like to have some feedback on this.  I'd be happy to do a pull request if that makes it easier for you, and if the above makes sense to everyone.

Thank you very much!!

**Comment by patrick-mcdougle** [comment]
Not exactly sure what your use case is, but according to [RFC 4627 §3](https://tools.ietf.org/html/rfc4627#section-3) application/json SHALL be encoded in unicode.

**Comment by xabbuh** [comment]
See #13410 for the reasons why it is implemented this way.

**Comment by bs-thomas** [comment]
Fair enough.  Thank you!
