### ISSUE TITLE
Unable to Decoder XML

### ISSUE THREAD

**Issue by dannyec** [symfony/symfony#20139]
I am kinda frustrating trying to decode/encode from a XML request (listen) and i got this error.

`PHP Fatal error:  Class 'Symfony\Component\Serializer\Encoder\XmlEncoder' not found in /home/www/wechat/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/Decoder/XmlDecoder.php on line 30" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: localhost, request: "POST /wechat/proxy?signature=79e576daeff6b91114fd0d48e7d80ab2e90sq235&timestamp=1475511219&nonce=269932691&openid=xxxxxxxx`

Aditional information, I am using namespaces:
```
 use Symfony\Component\Serializer\Serializer;
 use Symfony\Component\Serializer\Encoder\XmlEncoder;
```

Using Symfony 2.8

**Comment by iltar** [comment]
Doesn't look like a bug in Symfony, have you verified that the class is actually there? Do you have the dependency on the serializer component installed? Seems like you've forgot an installation step as it's an optional dependency: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json#L39

**Comment by dannyec** [comment]
Thanks bro, save my life, I was spending a lot of time looking for this error. Actually I am building a plugin, I didn't expect about this dependency. Thanks a lot.

**Comment by javiereguiluz** [comment]
@dannyec I'm glad it was fixed thanks to @iltar's help. Next time you have a question like this one, where you are not sure if it's a Symfony bug or not, it's better to ask it first in any of the support channels provided by Symfony (https://symfony.com/support) because a lot of Symfony users can help you fix it. Thanks!
