### ISSUE TITLE
DateTime constraint doesn't allow to pass format parameter

### ISSUE THREAD

**Issue by Arkemlar** [symfony/symfony#20134]
I am trying to do this in my controller annotations:

```php
@FOSRest\QueryParam(name="start_date", requirements=@Assert\DateTime(format = "Y-m-d\TH:i:sO")
```

And getting error:

```
The options \"format\" do not exist in constraint Symfony\\Component\\Validator\\Constraints\\DateTime <...>
```

But [documentation](http://symfony.com/doc/current/reference/constraints/DateTime.html#format) says that I can pass format as an option. Also tried to pass format as:

```php
@FOSRest\QueryParam(name="start_date", requirements=@Assert\DateTime("Y-m-d\TH:i:sO")
```

and got error:

```
The options \"\" do not exist in constraint Symfony\\Component\\Validator\\Constraints\\DateTime
```

Finally, even this way it is not working (investigated later):

```php
$validationResult = $this->get('validator')->validate($start_date,[new Assert\DateTime(['format'=>"Y-m-d\\TH:i:sO"])]);
```

Error:

```
The options \"format\" do not exist in constraint Symfony\\Component\\Validator\\Constraints\\DateTime
```

Assert defined as:

```php
use Symfony\Component\Validator\Constraints as Assert;
```

Symfony standard edition version 3.0.9.

**Comment by jonag** [comment]
From the documentation :

> The format option was introduced in Symfony 3.1.

Since you are using Symfony 3.0.9 the error seems normal to me. Maybe you should consider upgrading your Symfony version if you need to pass a specific format to the validator?

**Comment by Arkemlar** [comment]
Well, yeah. I not even looked at version limitation because the need of `format` option is so obvious that I can't imagine how is it possible to have DateTime validator without format option. Assumed it existed right from the very beginning.
