### ISSUE TITLE
Twig extensions use deprecated features

### ISSUE THREAD

**Issue by garak** [symfony/symfony#20133]
I just updated my vendors on a Symfony 2.8 project, getting Twig 1.26.0
I'm getting the following deprecation notice:
```
Referencing the "Twig_Extension_Core" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead.
```
I tried to remove `getName()` method from my extension, everything is working like before, but the deprecation is still there. I guess is something inside Symfony itself

**Comment by sh4ka** [comment]
Is it possible that the template is still cached?

**Comment by garak** [comment]
Removed all the cache, no luck

**Comment by stof** [comment]
Already fixed in https://github.com/symfony/symfony/pull/20079 but not yet part of a stable Symfony release
