### ISSUE TITLE
[TwigBridge] Form theme for Materialize

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#20145]
As we have form layouts for [Bootstrap](http://getbootstrap.com/) and [Foundation](http://foundation.zurb.com/), it could be great to move forward to most used CSS frameworks!

[Materialize](http://materializecss.com) is becoming more and more popular, since "Material Design is the new black" thanks Google.

Is it planned to create a specific form theme for Materialize?

**Comment by javiereguiluz** [comment]
In the past, the criteria we used was the popularity of the framework measured by GitHub stars.

My personal opinion is that we should only support Bootstrap (101,880 stars) but the community pushed to get support for Foundation (24,180). At the moment, Materialize has 21,735 so it's very close to Foundation.

**Comment by fabpot** [comment]
And the past tells us that those are not really maintained the way they should. So without a few people willing to contribute the code AND maintain it, it won't happen from the core team.
