### ISSUE TITLE
Twig deprecation notices when running phpunit tests

### ISSUE THREAD

**Issue by NeilJ247** [symfony/symfony#20149]
Hi,

Pulling in the latest twig and running our projects phpunit tests is giving me the following error after the tests have run:

`Referencing the "Twig_Extension_Core" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead: 594x`

This appears to relate to a recent change in https://github.com/twigphp/Twig/issues/2147.  Is the error something related to Symfony core needing updated or is there something I need to do on my end to resolve this?

Thanks.

**Comment by stof** [comment]
Symfony core has already been updated. update Symfony to 2.7.19, 2.8.12 or 3.1.5

**Comment by NeilJ247** [comment]
Thanks.  Updating to 3.1.5 did the trick :)
