### ISSUE TITLE
isPublic check in ConstraintValidatorsPass on decorators .inner argument

### ISSUE THREAD

**Issue by mariuszpass** [symfony/symfony#20150]
Hi.
I have a decorator for doctrine.orm.validator.unique which is tagged with validator.constraint_validator. With symfony 3.1.5 new checks were introduced in [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddConstraintValidatorsPass.php)

My decorator:
```
    app.decorating.doctrine_unique:
        class:     CapiBundle\Model\Validator\Constraints\UniqueEntityDecorator
        decorates: doctrine.orm.validator.unique
        arguments: ['@app.decorating.doctrine_unique.inner', '@doctrine']
        public:    false
```
results with exception `The service "app.decorating.doctrine_unique.inner" must be public as it can be lazy-loaded.`
Additionaly, `InvalidArgumentException` is not imported.

**Comment by smertius** [comment]
+1 
I have same problem.

**Comment by sstok** [comment]
The `app.decorating.doctrine_unique` service needs to be public, the fact you are getting this means the service was already incorrectly defined (and wouldn't have worked).

Are you decorating your own service elsewhere?

**Comment by mariuszpass** [comment]
I think, that private `app.decorating.doctrine_unique` is not a problem, because it's not tagged as `validator.constraint_validator` and it's not used directly (by it's @id). I've tried to make it public, but it doesn't changed anything.
The problem is, that decorated service is passed as argument to my service, but it's private - `.inner` is always made private. But it's still tagged as `validator.constraint_validator` which triggers check and then an exception.

**Comment by xabbuh** [comment]
The issue is that even after the decoration took place the tag is still (only) associated with the decorated service. Don't we always need to move the tags from the decorated service to the decorator?

**Comment by xabbuh** [comment]
Can you please check if #20207 fixes your issue?

**Comment by mariuszpass** [comment]
@xabbuh It fixes my problem only when I set `app.decorating.doctrine_unique` as public. 
However `DecoratorServicePass` creates an public alias for it, so I end up with two public services `doctrine.orm.validator.unique` and `app.decorating.doctrine_unique` which are same.
It's not a big deal but I think it's worth noticing.
Thanks for your work.

**Comment by xabbuh** [comment]
@mariuszpass I do not see how we can avoid that. The fact that it worked for you before was just pure luck as the compiler would have been allowed to inline your service if you did not reference it anywhere (which might cause hard to debug bugs). Though we could maybe think about supporting private constraint validators service like we already do for console commands.
