### ISSUE TITLE
TraceableEventDispatcherInterface doesn't implement ContainerAwareInterface

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#20151]
Symfony 2.8.

It seems that the `TraceableEventDispatcherInterface` doesn't implement the `ContainerAwareInterface` but it anyway gives access to the `getDispatcher` method.

I'm using PHPStorm, and, if cast to `ContainerAwareEventDispatcher` an exception is thrown:

> Catchable Fatal Error: Argument 3 passed to SerendipityHQ\Bundle\StripeBundle\EventListener\StripeCustomerSubscriber::onCustomerCreate() must be an instance of Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher, instance of Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher given

but if I cast to `TraceableEventDispatcherInterface` the autocompletion doesn't work as it doesn't give me "access" to `getContainer()` method (while it is possible to call as it is implemented).

I think there is something wrong but, as I don't know which is the correct/expected behavior, I cannot fix it as I don't know if it is correct or not that a `TraceableEventDispatcher` gives anyway access to the `getContainer` method. Maybe someone more involved in the development of Symfony can better understand what to do.

As you can see from the image, this is how currently I'm setting the method

<img width="741" alt="schermata 2016-10-04 alle 12 04 50" src="https://cloud.githubusercontent.com/assets/1968622/19070301/dae21f54-8a2a-11e6-8057-401689386806.png">

**Comment by stof** [comment]
TraceableEventDispatcher should not implement this interface.

currently, you get access to ``getContainer`` when the inner dispatcher has this method (which is not always the case), because the TraceableEventDispatcher forwards all method calls (done this way to simplify the code registering listeners, as such calls can be forwarded).

And IMO, there is no reason to use the event dispatcher to get access to the container, so it is not an issue if PhpStorm does not show you this method (it is even a good idea)

**Comment by iltar** [comment]
> I currently access the container to get some services I need in listeners/subscribers.

You should just inject them. But to be honest, 8 dependencies is way too much for as listener.

**Comment by Aerendir** [comment]
@iltar yes, are too much. But they are needed as each listener dispatch other events in a chain that is four level deep in deepest point. I need to pass a dependency from the first listener to the fourth in the chain, so is more handy to directly access the container and keep the events smaller in arguments to pass to constructors.

**Comment by stof** [comment]
@Aerendir no, you don't pass dependencies from a listener to another one. You inject dependencies in the listener, not in the event

**Comment by stof** [comment]
and btw, if you really insist on using the container (even if it is a bad idea), you can also inject the container into your listener instead of trying to get it from the event dispatcher. The event dispatcher is not there to give you access to the container, even when it is itself container aware.

**Comment by Aerendir** [comment]
@stof Your reply opened me a new World: I'm following the wrong path. I have to pass the dependencies when I register the listener. Is right! when I first used the the event system this was not clear to me: I'm going to rewrite my code. Thank you very much for the clarification!
