### ISSUE TITLE
Limiting web-profiler-toolbar AJAX request count

### ISSUE THREAD

**Issue by promarcel** [symfony/symfony#20155]
I having some trouble with the web-profiler-toolbar. We have a lot of AJAX requests in our application, any time the request count is going higher than 500 past requests the web page is going very slow and laggy.

So is there any method to limiting the counted request, for example: Are 500 requests done, delete one of the latest and add the current (new) request. So the AJAX request count is limited to an special number.

When there is no function for this, see this issue as an very helpful feature request.

**Comment by patrick-mcdougle** [comment]
I think that JS could be optimized a little. I think it should append new rows to the table as opposed to re-creating the whole thing.

**Comment by patrick-mcdougle** [comment]
@marceldeglau I haven't had a chance to test this yet, but here's [my attempt at fixing this up](https://gist.github.com/patrick-mcdougle/dcd5435aecd096fdc7c367641c7b08d1). The gist wouldn't let me save with slashes in the file name, so if you convert the tildes to directory separators, that should be the file you need to create to overwrite this. I'm hoping to test the changes tomorrow and if it's good I'll open a PR, but if you have a chance to test it, I would love to have another set of eyes on it.

**Comment by marceldeglau** [comment]
@patrick-mcdougle Thank you for your gist. I've not tested it long time, only for any minutes. The layout is a little bit "buggy" also the requests are added to the wrong direction. Also I think this will produce the same issue: After long times of requests 3.000+ requests the page will get very slow and buggy.

I think the best way will be to add a configuration to limit the displayed requests, for example the 501. request is done, the first entry (1. request) should be remove from the HTML.

Additional node: I've tested my idea, by removing the request using a own jQuery script, after removing the whole page is going speed up well!

**Comment by fabpot** [comment]
Limiting the max number of requests shown makes sense. I would not make it configurable though. 500 requests is already a lot and nobody is going to browse just a long list anyway. So, let's find a number that works well performance wise and that still gives enough information to the developer.

**Comment by marceldeglau** [comment]
@fabpot Thanks for your comment. I'll think this is the best way! **+1**

Sure 500 requests are very much. I mean 200 up to 150 requests are complete enough for debugging.

Node: Perhaps also we can add a button or link for stop to count requests in the profiler?

**Comment by patrick-mcdougle** [comment]
@marceldeglau The layout is "buggy" because of #19576 where they added a new column. I'll bet you're not on master and don't have the column yet. I truly believe that the performance problem has nothing to do with the number of requests, but rather the inefficient way we're re-constructing that section of the DOM on each request. Working on taking another stab at it now. If I can't get it to perform well, I'll limit it to 200 requests (seems like a meaningful number for ajax requests). Yes that's a HTTP joke.

**Comment by patrick-mcdougle** [comment]
@marceldeglau [Gist updated](https://gist.github.com/patrick-mcdougle/dcd5435aecd096fdc7c367641c7b08d1). I basically re-wrote all the rendering code to be more smart. I personally think the resulting code is more clear, but I'm biased. I also removed the type column so it would work with your version of symfony.

**Comment by marceldeglau** [comment]
@patrick-mcdougle Thanks for your work, but it isn't working for me: http://i.imgur.com/lDyenWn.png
I'm currently under 3.1.5, is there a problem?

**Comment by patrick-mcdougle** [comment]
@marceldeglau doh. Back porting this to 3.1 from master is giving me trouble. I'll come back to this in an hour or so.

**Comment by marceldeglau** [comment]
@patrick-mcdougle @fabpot I think the best way is to add it to 3.2 version. It's currently not a "immediately" issue.

**Comment by patrick-mcdougle** [comment]
@marceldeglau Try one more time. I was so close. Same [gist](https://gist.github.com/patrick-mcdougle/dcd5435aecd096fdc7c367641c7b08d1) as before.

**Comment by patrick-mcdougle** [comment]
I'll be targeting the PR to master, but I wanted to make sure it solves your performance issue before I bother opening the PR.

**Comment by marceldeglau** [comment]
@patrick-mcdougle Thanks! I#ve testes over 2.000 calls, and it seems to be stable. No lags or other issues. 
But I think also to add a limit of counted requests (see @fabpot's comment) to 200 requests. For example, add a new request and the delete the oldest one. 

Thank you very much for your awesome work dude!

**Comment by patrick-mcdougle** [comment]
I think having an arbitrary limit is confusing and unneeded if the performance problem can be fixed. People might assume the bottom request is the first one when it's the 200-ago one.

**Comment by fabpot** [comment]
I agree

**Comment by marceldeglau** [comment]
@patrick-mcdougle I've tested it again with ober 5.500 calls. The page is going fine, but when I mouse-over the requests, the complete browser will lag and freeze for any seconds. I think there are to many requests they've stored in HTML. It will be the best, we add a limit for the requests they are shown in the hover card. (Referencing to @fabpot comment)...
