### ISSUE TITLE
[security] Proposal: a way to know what voter refused the access

### ISSUE THREAD

**Issue by johndodev** [symfony/symfony#20168]
Hi,

I have an API with unanimous voters strategy and when a voter refuse a api call, I would like to throw an exception depending to what voter refused the call. All voter vote on the same attribute of course (eg : Attributes::API_CALL).

I think it's a real use case, but there is no way to know what voter(s) refused the call.

There is several way to do that, and I can make a PR, but before I woul'd like to discuss about it to know if it worth or if the SF team do not want it.

For example, we coul'd add a function "getDecision" or "getAuthorization" on the AthorizationChecker class, which would return an object, with some properties like "granted" (bool), and "denyingVoters" (array).

Another simplier way coul'd be adding a "getException" on the VoterInterface which can return null or an exception to throw if the voter deny the access, but it is not really a good design here imo (only relevant on unanimous strategy)..

Anyway, this woul'd result to a refactoring of the AccessDecisionManager and a BC break.. maybe for SF4 ?

I know I coul'd avoid that with one attribute per voter, but it loose the interest to have voters.

**Comment by iltar** [comment]
You can decorate all voters and keep track of them in debug mode. The WDT already shows which attributes is being voted on so it shouldn't be too hard to combine; see #17887

**Comment by edhgoose** [comment]
Earlier this week we had an AccessDenied exception on our production environments that we could not trace the origin of, nor reproduce on test environments. We generally don't want to turn the WDT on on these environments, and so the ability to add some logging to record which voter it was via one of the mechanisms above would be beneficial for us (unless there is a better way of solving that specific problem?).

(In the end, it was the FOSUserBundle and a two factor auth library getting confused with each other if you're curious)

**Comment by iltar** [comment]
You don't have to turn on the WDT, you merely have to visit app_dev.php, which you can easily shield with the right webserver config.

**Comment by johndodev** [comment]
It seems it's not really a big deal, I close ! 

Thanks
