### ISSUE TITLE
Request should not trust any header names by default

### ISSUE THREAD

**Issue by dzuelke** [symfony/symfony#20178]
(also see symfony/symfony-docs#7045)

http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html and http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html talk about trusting proxies, and http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly in particular mentions AWS as an example.

AWS ELBs do not set a `Forwarded` header, making it necessary to follow the instructions at http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html#my-reverse-proxy-sends-x-forwarded-for-but-does-not-filter-the-forwarded-header, but they also **do not set an `X-Forwarded-Host`** (only `…-For`, `…-Port` and `…-Proto`), which means, that for a very popular use case (running on AWS, or products that build on it, e.g. Heroku), applications would be vulnerable to spoofing of those headers.

My hunch is that a lot of developers don't realize that they need to explicitly distrust these headers, especially as the special case documentation and handling logic for `Forwarded`, unlike the other headers, has been introduced relatively recently.

I propose that out of the box, when a developer calls `Request::setTrustedProxies()`, no header names are trusted by default, and they must always be explicitly opted into using `Request::setTrustedHeaderName()`. That's only slightly more work, but means that the default is safe with an empty whitelist, and developers, having to investigate what headers really are being set in their environment, are much more likely to end up with valid settings that do not compromise application security.

/cc @fabpot, who asked me to open this issue (I may have time for a PR soon-ish)

**Comment by dzuelke** [comment]
@nicolas-grekas quick ping to see if this may be extra relevant/timely, as it's related to #21830

**Comment by nicolas-grekas** [comment]
Nice, then we cal close this one ! Here is why:
#21830 makes providing the trusted headers a requirement (a non enforced one for now to not break BC, but will be mandatory in 4.0).
So, `setTrustedProxies` take the set of trusted headers as 2nd args.
Typically:
`Request::setTrustedProxies(array(127.0.0.1), Request::HEADER_FORWARDED);`
or
`Request::setTrustedProxies(array(127.0.0.1), Request::HEADER_X_FORWARDED_ALL);`

but really, this 2nd arg is a bit field, so that in tha AWS ELBs, you just need to do eg:
`Request::setTrustedProxies(array(127.0.0.1), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);`

Done!
Would you mind doing the doc PR solving  https://github.com/symfony/symfony-docs/issues/7045?

**Comment by dzuelke** [comment]
Okay, but in 3.3, just `Request::setTrustedProxies(array(127.0.0.1))` will continue to trust all the headers, correct?

It might be worth considering changing that default even in 3.3, to "immediate breakage", in the interest of security, as 99.975% of code out there does that call in `app.php` or similar, and would need touching only once during upgrading (which could be documented).

Or at least change it in 3.4, as that will be the LTS version, and I really really really really really think the defaults are harmful.

But I'll let you decide that :)

**Comment by fabpot** [comment]
I agree with @dzuelke here that we should make the second new arg mandatory as of 3.3. But I would not make the default "optimized" for AWS, that's a doc issue instead IMHO.

**Comment by nicolas-grekas** [comment]
Done in https://github.com/symfony/symfony/pull/22238
@dzuelke would you mind doing the doc PR?

**Comment by robfrawley** [comment]
Very must support this "BC-break" in the immediately next minor version, as well.

**Comment by dzuelke** [comment]
Can do @nicolas-grekas, want to give me a deadline?

**Comment by nicolas-grekas** [comment]
May 15th if possible, that should match the first betas of 3.3
