### ISSUE TITLE
[DX] Inconsistency in the arguments for twig form functions

### ISSUE THREAD

**Issue by mik-laj** [symfony/symfony#20188]
## Problem

I would like to submit one attention, which may cause a problem for beginners.
Look at function declarations:

```
form(view, variables)
form_start(view, variables)
form_end(view, variables)
form_label(view, label, variables)
form_errors(view)
form_widget(view, variables)
form_row(view, variables)
form_rest(view, variables)
```

Two statements stand out: `form_label`, `form_errors`. 
The first declaration may cause a problem for beginners, as it often is given an array of options as the second argument.The error message is not clear. 
## Solution

I think that should give the check type, if the argument is definitely a string and provide the solution (pass null as second argument).

Thanks in advance.

**Comment by apfelbox** [comment]
How about making the label just an entry in the variables array of `{{ form_label() }}`? This would make it consistent und could probably be implemented in a BC safe way.

**Comment by mik-laj** [comment]
@apfelbox. Currently, you are ready to give a label in this way.
````twig
{{ form_label(edit_form, null, {"label": "cat"}) }}
````
This code works correctly.

I will try to create a patch that creates two virtual function definitions.
````
form_label(view, label, variables)
form_label(view, variables)
````

**Comment by jakzal** [comment]
@mik-laj You can also look at it from another perspective - `variables` is always the last argument.

Changing the order of arguments would break lots of existing applications which would go against our [BC promise](http://symfony.com/doc/current/contributing/code/bc.html). Potentially, we could swap `form_label()` arguments and support both variations for some time so people had time to upgrade (as the label is a string and variables are an array we could recognise what was passed). However, is it really worth it?

**Comment by mtrojanowski** [comment]
I proposed a change how the consistency can be met without breaking BC.
