### ISSUE TITLE
is it necessary to integrate an angularJs-like javascript framework into Symfony?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#20187]
nowadays , single page web app is very popular and wildly used than ever before, it says every day a javascript  framework  comes into the world,   Laravel announced vue.js as their main javascript framework, there are lots of works to do integrate a javascript framework into a  php framework like Symfony , as you can see [laravue roadmap](https://github.com/laravue/laravue#roadmap)  , I heard that Symfony is trying to be neutral to javascript frameworks, but indeed  the problem exists, since Symfony has to choose twig as its default template engine, I think it might be possible that Symfony would choose a javascript framework.

these days I searched a lot to find a javascript framework to build a single page web together with my Symfony project, but apparently  there is no existed solution ,  before I dive into this topic, I am wondering is our community is doing this job ?

**Comment by iltar** [comment]
Symfony is a php framework, so I don't see why it should support a specific javascript framework. I think that's something more for CMS systems.

**Comment by javiereguiluz** [comment]
@videni Symfony only makes this kind of decisions for back-end technologies. For example, there are millions of mailers, loggers, template engines and database libraries for PHP ... but Symfony only provides built-in support for SwiftMailer, Monolog, Twig and Doctrine.

For front-end technologies, a lot of members of the Symfony community think that we shouldn't make any decision and leave the framework 100% agnostic to those technologies.

In my opinion this is a mistake and Symfony should provide seamless integration (which is not the same as "coupling") with some front-end technologies, as we do for back-end technologies.

In the past, the front-end landscape changed too quickly, but lately things seem to have stabilized. For example, webpack now looks like a safe bet, so maybe we could do something to integrate webpack more easily with Symfony apps.

**Comment by iltar** [comment]
@javiereguiluz That's already possible: https://github.com/hostnet/webpack-bundle

But we've noticed (just like with assetics), that it's just not working as nicely as you'd want. The best idea is to just keep it separated as javascript has already (way too many) specialized tools. Integration would be nice, but would always be subpar with a php/framework integration.

Our approach was to have automatic splitpoint generation for webpack, but this means that every single twig compilation, webpack recompiles as well. Ideally you'd want webpack to compile when a file changes, but webpack already has a very nice watch mode for this. The native tooling is already present and good so I think that a php framework/tool would only mean restrictions.

What I would like, is good tutorials and best-practices how to integrate different systems on symfony.com (advanced usages includes, not just the basics).

Javascript frameworks are still coming and going, just like the supported javascript, transpilers, es6 es 2016 etc. It will just give a headache to provide default implementations.
http://www.commitstrip.com/en/2015/09/16/how-to-choose-the-right-javascript-framework/

**Comment by videni** [comment]
@iltar , @javiereguiluz , thanks for sharing your idea,  maybe we should change the idea we have in mind that `Symfony only makes decisions for back-end technologies`,  because front-end technologies are more difficult than before, right now , a front-end developer needs to know AugularJs like framework, jquery , javascript ，nodejs,  a semantic-ui like css framework in-depth,    and  template engine maybe, etc, they also need to know RESTfull API, JWT, lots of things. It is difficult to find  such sophisticated front-end developer here where I am working, why we choose a javascript framework , just simply  it can make life easier, as Laravel  community does.

 @iltar , I totally agree with you , maybe we should not do it at framework level, but we do need good tutorials about this topic, Symfony evolves a lot from version 1 to version 2 , every jump is a labour pain, need lots of work, but that is what makes Symfony perfect today.

**Comment by ChadSikorra** [comment]
Pretty much every time I create a new application I end up using [FOSJsRoutingBundle](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle) and [BazingaJsTranslationBundle](https://github.com/willdurand/BazingaJsTranslationBundle). Having tight JS support for both Translations and Routing like that is extremely helpful in most modern web apps where a lot of things are being done in JS. Just my 2cents anyways. I'm not sure to what degree, if any, Symfony should be focusing on integration with JS stuff.

**Comment by javiereguiluz** [comment]
@videni now that you have changed the title of this issue, the answer to your question is clear: "No; Symfony won't integrate any JS framework".

What we can discuss is whether Symfony could provide seamless integration for "common JS stuff" and "popular JS tools". But installing/integrating "these JS things" in your Symfony app will always be the developer's responsibility.

**Comment by sstok** [comment]
FYI, if you need to provide a good server-side implementation for communicating with Angular.
https://github.com/api-platform (works with Symfony).

**Comment by mvrhov** [comment]
@iltar @javiereguiluz I like this one better [wp bundle](https://github.com/mariusbalcytis/webpack-bundle)

**Comment by iltar** [comment]
Provides a different integration feature set, but it comes down to the same problems as what assetics has, you run it with php instead of native. 

@sstok looks interesting!

I think the main issue is not that there's no proper integration, it's just (like javascript frameworks) scattered over the internet and no real collection of what to use when.

**Comment by sh4ka** [comment]
In my humble opinion, some expectations about what the framework should and should not do are the reason of having bundles. There are many ways of working that way (my personal fav is api-platform). Agnosticism is better in this case.

**Comment by javiereguiluz** [comment]
Let's close this issue because the consensus seems clear about not integrating a JS framework into Symfony. @videni thanks for proposing this discussion and thanks everyone for your opinions.
