### ISSUE TITLE
Can Symfony do this? - Render only existing relations in a Collection form and allow adding new relations for already existing items

### ISSUE THREAD

**Issue by clytemnestra** [symfony/symfony#20200]
So I've been struggling for the past 4 days with this and I am not sure if it is possible with Symfony or if I need to intervene with a custom fix. I feel like this is a common widget used through applications and it could be pretty simple to do but I am missing the point on how to do it.

The idea is to add already existing Products to a new Order in a form. The Products are already in the database, they just need to be brought in the frontend. To do this, a text field that searches them by name, returns a clickable drop-down list and on clicking one item from the list, the Product is added to the Order. With this, no new Products should be created.

The problem is that I want only the existing relations to be initially displayed, and not all of the Products from the database.

Now, what I've tried so far:

```php
class Order
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Product", inversedBy="orders")
     * @ORM\JoinTable()
     */
    protected $products;

}
```
```php
class Product
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Order", mappedBy="products")
     */
    protected $orders;

}
```
And now OrderType form:

This will show a multi-select with all products and the selected ones are the products of the order. The problem is that the select contains all of the products.

```php
->add('products')
```

The default one is actually an EntityType with multiple=true, expanded = false. I can expand it for checkboxes:

![img](http://i.imgur.com/QGwThbO.png)

This will show only the Order's products in the select, but when I try to add a new one (I'll copy/paste one of the inputs and change its id to an existing product's ) I will get "The choices "8" do not exist in the choice list.".

```php
->add('products',EntityType::class,array('class'=>Product::class,'choices'=>$order->getProducts(),'multiple'=>true,'expanded'=>true))
```

This makes me think that I need to either allow EntityType to allow choices to be added that are not in the choices passed to the form, but I don't know how to do that, can't seem to find a way, OR use CollectionType which allows me to add/remove associations.

```php
->add('products', CollectionType::class, array('by_reference' => false, 'entry_type' => EntityType::class, 'allow_add' => true, 'allow_delete' => true, 'entry_options' => array('class'=>Product::class,'expanded'=>true)))
```
![image](http://i.imgur.com/SVaPgtq.png)
This will render radio containing ALL products for each relation. I can add new products to the order thanks to the CollectionType, but the initial relations show all products as radio list for each relation. If only I could somehow tell EntityType to only render the current relation.

Is there a way to do this?

**Comment by sh4ka** [comment]
Yes, there is a way. Take a good read to: https://symfony.com/doc/current/doctrine/associations.html and keep in mind that you can change the way Doctrine works by extending it.
I cannot give you the precise solution but there is more than one way to accomplish that.

**Comment by clytemnestra** [comment]
The problem is from Symfony's forms, not from Doctrine. I think..

**Comment by xabbuh** [comment]
@clytemnestra I am sorry, but I am closing your issue as we useGitHub only for the Symfony development. To gather support please refer to one of our [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by peyman-mohamadpour** [comment]
Dear @clytemnestra, have you found the solution? as I am exactly at the same thing
