### ISSUE TITLE
Cache cannot distinguish between OPTIONS and GET

### ISSUE THREAD

**Issue by nico-incubiq** [symfony/symfony#20202]
Hello,

I just ran into an issue with Symfony 3.1.5 concerning the HttpCache mechanism, which sends back the content of a GET method while executing an OPTIONS call.
I have a JS application which calls an API. This app uses CORS preflight OPTIONS calls to determine if he can call the API. Cache is configured on some public APIs.

On a basic example here is what happens:
- OPTIONS call from the JS app returns the right Response with headers such as "access-control-allow-methods: GET" and "cache-control: no-cache" (if I do it multiple times using Postman it always generates a new Response with the expected content, so that I am sure it is not cached)
- GET call issued just after returns a Response with headers such as "cache-control: max-age=86400, public, s-maxage=86400" (this one is being cached by HttpCache, which stores it in a file on the server)
- But when another computer accesses the page, the OPTIONS call returns a **cached Response**, with "cache-control: max-age=86400, public, s-maxage=86400"

I found that because the **Store::generateCacheKey()** method only uses the **Uri** to compute the cache the key, then HttpCache thinks it has found a cached version of the OPTIONS call and **sends back the headers and body** of the GET call instead.

I think the generateCacheKey should at least use the **method** when computing the key, and maybe headers like *Accept-**.

**Comment by stof** [comment]
``Accept-*`` should not be part of the cache key by default (but then, we should still be able to vary on it)

**Comment by nico-incubiq** [comment]
Just a follow up on this one, I confirm the issue is not present on Symfony 3.1.2, so that I think this also comes from the same commit which caused #19582 (OPTIONS method is now considered as safe).

**Comment by dmaicher** [comment]
I think its not as easy as just putting the request method into the cache key generation :wink: As far as I can see the HttpCache will try to return a cached reponse for a previous `GET` request when performing a `HEAD` request. So we might need some extra logic for `OPTIONS` requests then.

Added a test case to confirm the issue here: https://github.com/symfony/symfony/commit/78c4a0c22093b25a2181105c3dfc1c53cb2871a5

Headers should not be part of the cache key like @stof said. That's what the Vary headers are meant to be used for :wink:

**Comment by xabbuh** [comment]
But OPTIONS requests [are not cacheable](https://tools.ietf.org/html/rfc2616#section-9.2). So the only thing we have to solve is to bypass the cache entirely in this case (thus no cache key building involved), right?

**Comment by dmaicher** [comment]
@xabbuh ah good point :blush: :+1: Will simply adjust my branch and create a PR then :wink:

**Comment by dunglas** [comment]
Instead of hardcoding this behavior in the `HttpCache` class,  we can add a new `isMethodCacheable` to the `Request` class. Such helper methods are very useful (for instance when API building APIs).

**Comment by dmaicher** [comment]
@dunglas agreed :blush: Makes sense. Updated my PR.

**Comment by teohhanhui** [comment]
@xabbuh:

> But OPTIONS requests are not cacheable.

That should not apply so cleanly to a reverse caching proxy. CORS preflight requests hitting the app can take much longer than necessary, when they can actually be cached in the reverse proxy.

**Comment by xabbuh** [comment]
@teohhanhui I don't see where you can take that from the RFC. IMO it's very clear about the possibility to cache OPTIONS requests.

**Comment by teohhanhui** [comment]
@xabbuh The RFC sets out the rule for HTTP caching. The AppCache, like Varnish, is not a HTTP cache. A reverse caching proxy is properly part of the web server because out-of-band information can be used to allow caching where it's not usually possible.
