### ISSUE TITLE
ConflictingHeadersException for google data compression proxy

### ISSUE THREAD

**Issue by piszczek** [symfony/symfony#20215]
Hello.
I'm using Symfony 2.8.12

Error message:

> PHP Fatal error:  Uncaught exception 'Symfony\Component\HttpFoundation\Exception\ConflictingHeadersException' with message 'The request has both a trusted Forwarded header and a trusted Client IP header, conflicting with each other with regards to the originating IP addresses of the request. This is the result of a misconfiguration. You should either configure your proxy only to send one of these headers, or configure Symfony to distrust one of them.' in /[...]/app/bootstrap.php.cache:783\nStack trace:
> # 0 /[...]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ValidateRequestListener.php(40): Symfony\Component\HttpFoundation\Request->getClientIps()
> # 1 [internal function]: Symfony\Component\HttpKernel\EventListener\ValidateRequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
> # 2 /[...]/app/cach in /[...]/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 67, referer: [...]

This error happens only when we use Google Data Compression Proxy. This is option in Chrome Mobile browser "Saving data" (or maybe "Data compression" in Polish it's "Oszczędzanie danych"). While it's turned on, we get this message when we tried enter on any site.

This error doesn't happen in earlier versions of Symfony. Some of projects using version 2.8.5 and it working fine.
Probably [this change](https://github.com/symfony/http-foundation/commit/e8fa5fede69ff2bc38cacf4768a679eb77123c5a) make a trouble.

Only this change working for me and prevent from errors
`unset($_SERVER["HTTP_FORWARDED"]);`

Probably it's connected with [this error](https://github.com/contao/standard-edition/issues/45)

Regards and thanks for any help.

**Comment by xabbuh** [comment]
Is it really the Google Data Compression Proxy that is setting both headers?

**Comment by sh4ka** [comment]
How you connect to the internet? Directly or proxied?

**Comment by piszczek** [comment]
It's weird I can't repeat this error again.
It's happend when in google chrome browsor data compression was turned onor if I use [this plugin](https://chrome.google.com/webstore/detail/data-compression-proxy/ajfiodhbiellfpcjjedhmmmpeeaebmep/related) in desktom chrome browser. I didn't use no addition proxy of smth.

Could it be temporary?

Error happens many times on server. I had no idea how i can reproduce them before I check IP from it happens. 
IP was random but always from google-proxy-xxx-xxx-x-xxx.google.com
Eg. IP from it happens:
66.102.9.131:39629
66.102.9.136:43656
66.102.9.136:45329
66.102.9.131:51509
66.102.9.136:57489
...

Errors was always the same.

**Comment by yellow1912** [comment]
We have this exact issue with chrome browser on android phone

**Comment by yellow1912** [comment]
Further investigation leads us to the AppCache in app.php. If we comment out that (and thus turn off the symfony proxy cache) then the issue is gone.

**Comment by QuentinLeBonArtisan** [comment]
Same issue for me. With the ConflictingHeadersException

```
public function getClientIps()
    {
       [...]
        if ($hasTrustedForwardedHeader && $hasTrustedClientIpHeader && $forwardedClientIps !== $xForwardedForClientIps) {
            throw new ConflictingHeadersException('The request has both a trusted ....');
        }
       [...]
    }
```

$forwardedClientIps = array ('xx.xxx.98.137');
$xForwardedForClientIps = array('66.249.93.74', 'xx.xxx.98.137');

66.249.93.74 seems to be the data compressor Google proxy.

**Comment by scaytrase** [comment]
Same issue here. Toggling the data compression for mobile chrome toggles the facing the issue.

**Comment by ruicampos** [comment]
We had the same issue and solved by adding to web/app.php:

```
Request::setTrustedHeaderName(Request::HEADER_FORWARDED, null);
```

This makes Symfony distrust the Forwarded header - http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html

**Comment by gnat42** [comment]
I can confirm that the google data saver mode proxy sends both headers. I dumped them via apache_get_headers() in the exception message they were:

The headers being sent were:
Array
(
[Host] => www.example.com
[Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8
[Accept-Encoding] => gzip, deflate, sdch
[Accept-Language] => en-US,en;q=0.8,fr-CA;q=0.6,fr;q=0.4,es;q=0.2
[Cache-Control] => max-age=0
[Forwarded] => for=70.72.63.221
[Save-Data] => on
[Scheme] => http
[Upgrade-Insecure-Requests] => 1
[Via] => 1.1 Chrome-Compression-Proxy
[X-Forwarded-For] => 70.72.63.221
[Connection] => Keep-alive
)

**Comment by nicolas-grekas** [comment]
@ruicampos is right, doing this call is required in this situation.

**Comment by gnat42** [comment]
So @nicolas-grekas there is a problem with simply closing this issue. If I deploy a site to some infrastructure I control where we've got a proxy server in there I as the owner of the product know I need to set the proxy header setup appropriately.

In this case you have a very large influencial party IE Google that has a setting somewhere where a normal user isn't likely to set themselves. The default symfony installation breaks with this. It's a non trivial amount of users that can be affected. 

If every symfony developer now needs to set that setting so that their site works on a mobile Android device why isn't this the default setting? Additionally, what happens if I need to support both types of proxies? Like we have a proxy that sends one header and google sending both. Can't symfony's code cascade  somehow? Such as preferring one over the other when both are present?

**Comment by scaytrase** [comment]
The problem is not with headers themselves, but with problem is that we cannot know if (or when) large vendors will deploy unsupported ones. We should have a way to make the application robust

**Comment by nicolas-grekas** [comment]
Yep, agreed, that's what is done, enhanced in 3.3.
See #22238 and #20178 for some background on the topic.
