### ISSUE TITLE
DataUriNormalizer does not recognize valid mime types

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#20225]
DataUriNormalizer `denormalize` method uses a regex to validate a data uri, but fails to recognize some valid mime types, such as:

```
application/shf+xml
application/resource-lists+xml
application/java-archive
application/vnd.ms-word.document.macroenabled.12
x-conference/x-cooltalk
```

**Comment by Nek-** [comment]
@alekitto could you provide a case (with a file) so we can reproduce ?

**Comment by alekitto** [comment]
I've uploaded two test files in this gist: https://gist.github.com/alekitto/364d727f31ebb179f96a3215fe3703cd

The test files are:
test.docm with type `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
hello.jar with type `application/java-archive`
