### ISSUE TITLE
setOptions in symfony process is not available.

### ISSUE THREAD

**Issue by Modelizer** [symfony/symfony#20222]
Hi,
  In [symfony/process](https://github.com/symfony/process) if I want to set multiple options then I'm not able to set it, for example, I can use `setOption(key, value)` to set option but what if I want to set multiple options then I should do is `setOptions([key1 => value1, key2 => value2...])` I have gone trough the [API](http://api.symfony.com/2.7/Symfony/Component/Process/ProcessBuilder.html) but I'm not able to find alternative.

Thanks.

**Comment by backbone87** [comment]
if its not there then its not implemented? do you purpose to implement a multi set for options?

**Comment by Modelizer** [comment]
Yes. If it's approved by core symfony team then I can do it.

**Comment by ro0NL** [comment]
@Modelizer you should add PR on the symfony/symfony repo...  as symfony/process is readonly ;-)

**Comment by Modelizer** [comment]
@ro0NL Thanks.

New PR https://github.com/symfony/symfony/pull/20358
