### ISSUE TITLE
Parse error on types

### ISSUE THREAD

**Issue by vasilvestre** [symfony/symfony#20220]
FatalErrorException in appDevDebugProjectContainer.php line 5084:
Parse Error: syntax error, unexpected ':', expecting ';' or '{'

public function initializeProxy() : bool

If i deleted or modify, the next function with " : bool" is the new problem..
Thanks

**Comment by jakzal** [comment]
Can you please upload the result of `composer show`?

**Comment by xabbuh** [comment]
@vasilvestre Looks like you are using ocramius/proxy-manager 2.0 while not using PHP 7.

**Comment by jakzal** [comment]
Looks like you installed your dependencies and generated the cache on php 7, but try to run your project on php 5.x.

**Comment by vasilvestre** [comment]
My bad. Don't know what and why proxy manager is there but.. thanks
