### ISSUE TITLE
[DX][Form] Ability to disable the checkMX of email validator for dev environment

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#20226]
The check mx is a great feature of the email validator but doesn't allow you to test your form type without an internet connection. Which is a problem for example for people who work in a train or in the middle of nowhere just behind an awesome lake.

There were a PR that would fix this problem: https://github.com/symfony/symfony/pull/18142

But the spotted use case was only "test env". And considering that fact, the solution was not optimal. But if you consider also the dev environment... I think the PR should be re-considered.

What do you think ? Do you want me to take care of that ?

**Comment by iltar** [comment]
You can't ever trust DNS records a full 100%, think about changes and TTL for example. The only way to verify if an email address is valid, is by sending mail. While the check itself can be nice, I don't think it's too relevant for email validation. Mx records can give false negatives (if that's what you call it).

**Comment by fabpot** [comment]
I agree with @iltar that this option should IMO never be used as it's more or useless. If it were just me, I would just remove this option altogether.

**Comment by Nek-** [comment]
@iltar @fabpot 

TTL problem is like "not working properly for your super custom email for some hours", most part of the time (and for most users) it's ok.

Btw you dislike this (pretty cool) option enough to close an issue about for it ? :) So why not deprecate it and remove it definitely from Symfony ?

**Comment by iltar** [comment]
Actually, Most people don't know that mx (or dns checks in General) are not
reliable. When using this check, it gave false negatives all the time for
me (partially cause I'm in the hosting business)

**Comment by fabpot** [comment]
I do think that deprecating this option and removing it in 4.0 is the way to go.
