### ISSUE TITLE
Command helpers as separate components

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#20227]
I wanted to make a small script that picks a random file, ask some questions about it and then go to the next file. I don't really need a full-fledged Command, would it be possible to move helpers like Question helper to their own component? (1) Right now i would have to use the Command component and set a default command (because i don't really need a "command"). It would be nice if the question helper just uses the default stdin stdout if those arguments are not supplied. (2). And secondly it would help if the Question helper has some convenient methods to create the questions. (3). I imagine a usage like this:

```php
$helper = new QuestionHelper(); // pass optional other InputInterface / OutputInterface
$colors = $helper->choice(
        'Please select your favorite color (defaults to red)',
        array('red', 'blue', 'yellow'),
        0);

// .. $helper -> another question
```

Same for being able to send color output to the console.

**Comment by javiereguiluz** [comment]
@flip111 this question looks strange to me: you want to run a PHP script in the console to ask questions ... but you don't want to create a (Symfony) command console that asks questions.

At first sight, instead of an optimization, this looks like putting much more effort to achieve the same goal.

**Comment by flip111** [comment]
Hi @javiereguiluz i see the 4 lines i posted as an optimization of https://symfony.com/doc/current/components/console/changing_default_command.html which has 19 lines + https://symfony.com/doc/current/components/console/helpers/questionhelper.html which should also be about 4 lines. Plus that i don't need/want the out-of-the box stuff that Command gives me (which is overhead when you don't need it). Which sight are you talking about?

**Comment by xabbuh** [comment]
Imo there is no big deal to create the input and output instances yourself if you want to use the helpers outside a command. Adding fallbacks in the helpers would add to much complexity to them for not much gain.

**Comment by flip111** [comment]
@xabbuh your proposal pretty much covers (1), leaving (2) not implemented and (3) unanswered. If in your opinion it's better for people to start writing their own wrappers around all the questions then it's no to 1 2 and 3. Possibly such a wrapper could be included as a a class?

**Comment by stof** [comment]
@flip111 the issue with adding helper methods to create questions is that it would require adding lots of optional arguments, which become barely usable. This is how our DialogHelper was looking in the past, and it was becoming very hard to use when adding more features. This is why we switched to a Question object with setters.

and making the helper work without the Input and Output abstractions seems a bad idea to me. It would force them to duplicate code of the output and input objects in a place not responsible for that.

Note that you can totally use the helper without creating a command, if you pass it the Output properly.

And splitting this in a different component would make things harder to maintain as these are things closely related. It is fine to instal symfony/console even when you use only part of it IMO.

**Comment by flip111** [comment]
Ok seems clear, i might do a PR for a wrapper class later.
