### ISSUE TITLE
Create A SecurityTokenValueArgument

### ISSUE THREAD

**Issue by manuelj555** [symfony/symfony#20231]
Hi, I see that the feature https://github.com/symfony/symfony/pull/19452 was deprecated. 

So, What do you think in favor of create a SecurityTokenValueArgument?

The use case for this is:

```php
public function anyAction(Request $request, TokenInterface $token) {
    $user = $token->getUser();
}
```

This is useful when the controller does not extends the default base Controller class.

_Sorry for my bad english :(_

**Comment by iltar** [comment]
The feature was actually not deprecated at all and still works, only the deprecation of the `getUser()` function in the controller was removed.

**Comment by manuelj555** [comment]
Ah ok, sorry for the confusion!
