### ISSUE TITLE
[Console] Wrong handling of multi-line argument descriptions

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#20237]
This is a follow-up on #13220 created by @wouterj. The problem is in [line 47](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Descriptor/TextDescriptor.php#L46-L47):

``` php
// + 17 = 2 spaces + <info> + </info> + 2 spaces
preg_replace('/\s*[\r\n]\s*/', "\n".str_repeat(' ', $totalWidth + 17), $argument->getDescription()),
```

While the whitespace calculation might be correct for the unit test, where the `<info>` tags are simply output, it is certainly wrong for a decorated console, where the `<info>` tags are converted.

<img width="882" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19472746/cee73640-9528-11e6-9b08-bc41890734bf.png">

The calculation should be `// + 4 = 2 spaces + 2 spaces` so it is `$totalWidth + 4`, then the spacing will be correct.

<img width="882" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19472797/00f5b5ee-9529-11e6-965d-1c05669dafd7.png">

**Comment by rquadling** [comment]
Several +17's need to become +4's.

**Comment by ogizanagi** [comment]
Confirmed and patch applied in https://github.com/symfony/symfony/pull/20704.

Status: Reviewed
