### ISSUE TITLE
symfony v. 2.8.12 and file AddConstraintValidatorsPass

### ISSUE THREAD

**Issue by bartek1234321** [symfony/symfony#20238]
symfony\symfony\src\Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConstraintValidatorsPass.php

InvalidArgumentException: Have you missed namespace?

**Comment by xabbuh** [comment]
Fixed by #20163 (which will be released with 2.8.13). Please give more information if this isn't the issue you are experiencing.
