### ISSUE TITLE
[TwigBundle] Invalid escaping strategy "name"

### ISSUE THREAD

**Issue by JMLamodiere** [symfony/symfony#20244]
Since #20224 , I have this error, for instance when displaying the profiler : 

```
Invalid escaping strategy "name" (valid ones: html, js, url, css, html_attr) in "@WebProfiler/Profiler/results.html.twig" at line 1.
```

Seems to be related to the configuration key `autoescape` [in Configuration.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/Configuration.php#L123) which default has switched from `filename` to `name` .

A workaround is to manually set it back to `filename` in the project config : 

```yaml
twig:
    autoescape: 'filename'
```

**Comment by xabbuh** [comment]
That commit requires Twig 1.27 which isn't released yet. It looks like you are already using a development version of 1.27 which is not at the latest commit (that provides the needed changes, you need twigphp/Twig@b646e503e9889af552fb6f1ffb0a703902456feb).

**Comment by JMLamodiere** [comment]
Thanks, sorry !
