### ISSUE TITLE
Symfony 2.8 file upload error

### ISSUE THREAD

**Issue by pawelprzychodzien** [symfony/symfony#20246]
Hi, can someone help me with this problem: http://stackoverflow.com/questions/40106506/symfony-2-files-upload ? Complete issue description and my code is posted there. Thanks in advance for your help.

**Comment by iltar** [comment]
This issue tracker is not to ask for help on solving problems. As you've already asked on SO, I think this can be closed.

**Comment by pawelprzychodzien** [comment]
Sorry, my bad, but maybe you know where else can I ask those kind of issues?

**Comment by iltar** [comment]
You can try IRC: `freenode.net` channel: `#symfony`
 - http://symfony.com/support

**Comment by pawelprzychodzien** [comment]
ok, thx!
