### ISSUE TITLE
[Workflow] Ability to generate diagram with current state highlighted

### ISSUE THREAD

**Issue by fracz** [symfony/symfony#20249]
According to the [docs](https://github.com/symfony/symfony-docs/pull/6871/files#diff-fd1227343e613ad7b14c5aac75691a0eR12) you can dump workflow diagram to png file.

It would be perfect if one could generate such diagram in contenxt of particular instance with current state marked somehow. [The demo of the workflow](http://symfony-workflow-demo.herokuapp.com/) does this with SVG and looks amazing. But it is scripted manually.

**Comment by javiereguiluz** [comment]
@lyrixx do you think this is a reasonable feature request? Could it be implemented without complicating the code much? Thanks!

**Comment by lyrixx** [comment]
IIUC the use case, it's [already implemented in the command](https://github.com/symfony/symfony/blob/4eeb1f018b9b5b7a5dd4635b7006ee5b4ad7e0e9/src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php#L39) and so in the [Dumper](https://github.com/symfony/symfony/blob/4eeb1f018b9b5b7a5dd4635b7006ee5b4ad7e0e9/src/Symfony/Component/Workflow/Dumper/GraphvizDumper.php#L46)
