### ISSUE TITLE
GroupSequenceProvider doesn't work with doctrine proxies

### ISSUE THREAD

**Issue by syastrebov** [symfony/symfony#20251]
Unable to use `GroupSequenceProvider` if entity was loaded as doctrine proxy. See `LazyLoadingMetadataFactory::getMetadataFor($value)`. It's just getting `$value` class as is:

`$class = ltrim(is_object($value) ? get_class($value) : $value, '\\');`

so it won't work for doctrine proxies where we will get classname with `Proxies\__CG__\` prefix instead of real entity class. So original class annotations will be skipped and `getGroupSequence` won't be called.

I guess need to add doctrine get real class check to ensure we are not loading metadata for proxy.

Found related issue https://github.com/symfony/symfony/issues/14944.

**Comment by jakzal** [comment]
Since there were problems reproducing the original issue, would you mind reproducing it on a fork of Symfony Standard Edition? It would help to debug the issue and would prove this is not something specific to your project.

**Comment by syastrebov** [comment]
@jakzal yeah, no problem

**Comment by iltar** [comment]
Probably should use the `ClassUtils::getClass($object);`

**Comment by syastrebov** [comment]
@jakzal prepared the demo

commit:
https://github.com/syastrebov/symfony-standard/commit/449245d9252ddd9917ffa7aee7f107e5a0780507

repo:
https://github.com/syastrebov/symfony-standard/tree/group-sequence-proxy-sample

**Comment by artursvonda** [comment]
Would iterating over all parents additionally to self and fetching metadata be a valid strategy? Wouldn't tie solution to specific case and would benefit all proxy classes.

**Comment by syastrebov** [comment]
Was fixed here https://github.com/symfony/symfony/commit/9dd6b0cf643380f3ffb67fcc85eef1255ecfb910, closing the issue.
