### ISSUE TITLE
[Process] Stopping of processes inconsistent between platforms

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#20259]
On Linux, the primary implementation of `Process::stop()` is [calling `proc_terminate()`](https://github.com/symfony/process/blob/cdb8db3590748b544e673f8879269afa3c65460a/Process.php#L1532) with `TERM` signal.
This effectively kills the process but usually not its child processes.

On Windows, however, [`taskkill` command with `/T` switch is used](https://github.com/symfony/process/blob/cdb8db3590748b544e673f8879269afa3c65460a/Process.php#L1522) so whole process sub-tree is killed.

I found that the `taskkill` command for Windows platforms was added here: https://github.com/symfony/process/commit/1eb5593edd48ceea1834c6d0b48ee33edf23aeed#diff-9a01fc0e340da4c3f1e4a16029a63977R626 .
But the commit message says nothing about any need to kill the whole process tree:

> [Process] Make Process::start non-blocking on Windows platform

Is there any reason for this inconsistency?

**Comment by sustmi** [comment]
I would expect `Process::stop()` to kill the whole process tree on all platforms (even when POSIX `kill()` does not do it I would expect the `Process` component to clean-up everything).
This is a common behaviour in Linux terminal (eg. `bash`) that when you press CTRL+C to stop the process all the child processes are stopped too.

**Comment by nicolas-grekas** [comment]
Linux and Windows are two different OSes and we can't completely abstract them out.
PHP wraps all process in a shell by default. On Linux, you can replace this shell by your actual command by prefixing it with `exec` (eg. `exec command --arg` instead of `command --arg`).
This is not something we can fix in Symfony actually and unfortunately.

**Comment by javiereguiluz** [comment]
@sustmi I'm sorry but I must close this as *"we can't fix it"* because of the reasons mentioned by Nicolas.

**Comment by nicolas-grekas** [comment]
Not that this has beedn "fixed" in 3.3, when you use the Process class with an array as first attribute.

**Comment by sustmi** [comment]
If I remember it correctly I wanted the `Process::stop()` call to kill the child processes to solve this issue in Composer: https://github.com/composer/composer/issues/5800 .
In brief, when Composer thinks that `git clone` takes too much time it calls `Process::stop()` but this stops only the parent process and not the child ones. Composer then downloads the files by some fallback method. But in the meantime Git's child process finishes the download however as it detects that the target folder was changed (by Composer doing the fallback download method) it "panics" and deletes all the files.

I do not think that this issue can be resolved by passing an array as an argument to `Process` constructor.
Luckily I did not encounter the problem again since 2016 so lets hope it does not appear again.

**Comment by nicolas-grekas** [comment]
> I do not think that this issue can be resolved by passing an array as an argument to Process constructor.

That's a strange statement... How do you know?
Personally, I know that I worked on a PR that's been merged into 3.3, that when you pass an array as first argument to Process, is able to remove the intermediary shell, so that git is not a child process anymore, and as such receives itself the kill signal...

**Comment by sustmi** [comment]
If I understand it correctly the new "array as an first argument" interface (https://github.com/symfony/symfony/pull/21474) can be used only for single executable.
The problem is that in Composer they do not use a simple command with a single executable but they want to chain commands using `&&`. See: https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L65.
Or do I miss some point?

**Comment by nicolas-grekas** [comment]
On Symfony side, there is a new primitive that allows fixing the issue. The composer would need to take advantage of it. The line you linked can certainly be split into several consecutive process calls if needed.
