### ISSUE TITLE
[RFC][Security] Define access control rule for route

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#20257]
Hi,

Currently the `access_control` setting only allows regex paths, wouldn't it be nice to allow a route name as well. This would avoid duplicating paths between routing and security.

```yml
access_control:
  - { path: '^/admin' }
  - { route: 'some_route_id' }
```

Any thoughts?

**Comment by fabpot** [comment]
Won't work. Security is executed before routing.

**Comment by ro0NL** [comment]
Can we do a different approach then? currently we chose for `@Security` annotations.. which requires extra dependencies. I find this in scope of symfony framework..

In theory we should be able to get the compiled regex for a route right?

**Comment by stof** [comment]
@fabpot this is not true. The routing comes first

**Comment by ro0NL** [comment]
@fabpot shall we reopen? Im curious if someone has comments on this.

@stof imo. it's a must have for the framework, even if that means we need to boot routing first to get the path regex.

To clarify; we went with annotations to explicitly target a controller/action (ie. route), having 2 route definitions was not acceptable in our case (error prone) as this is security related.

**Comment by stof** [comment]
A solution for this could be to allow configuring an id of a RequestMatcherInterface service for the access control rule, which would be used instead of the one configured based on ``path``, ``ips``, ``host`` and ``methods``. This would give full flexibility to match requests in more complex ways (and looking at the route name might be a possibility then, by implementing RequestMatcherInterface in this way)

**Comment by ro0NL** [comment]
Makes sense, however we could do some built in logic right? Ie. i noticed there is a `Symfony\Component\HttpFoundation\ExpressionRequestMatcher` matcher, i kinda assemed i was able to trigger it using:

```yml
access_control:
  - { path: '^/admin' }
  - { expression: 'some expression' }
```

But we do have `allow_if` for the built-in request matcher right now. Because of that i thought a `RouteRequestMatcher` could be done and allowing it all;

```yml
access_control:
  - { path: '^/admin', allow_if: 'some (sub) expression' }
  - { expression: 'some expression' }
  - { roure: 'some_route_id' }
```

**Comment by ro0NL** [comment]
For reference, this can be achieved using: https://github.com/yarhon/YarhonRouteGuardBundle which looks pretty cool :) Thx @yarhon
