### ISSUE TITLE
[Forms] exceeding php max_input_vars leads to a misleading CSRF token error

### ISSUE THREAD

**Issue by Perni1984** [symfony/symfony#20262]
For a standard php installations max_input_vars is set to 1000. 

I recently ran into this php "behaviour", when I had to POST submit a form with more than 1000 variables and thus the CSRF token was the very last variable of the form. Naturally the input variables > max_input_vars where truncated, and so was the CSRF token. 

As I received an invalid CSRF token error, this took me quite some time to track it down - as I clearly saw in the POST Request body that the valid token was submitted. Eventually a max_input_vars "Warning" or another error message would be more helpful.

**Comment by iltar** [comment]
Recently encountered this as well, except that it was without CSRF token thus we never noticed until someone started digging why specific items were always missing.

Maybe it would be nice in general if Symfony logs an error or warning that this value is reached (not to crash).

**Comment by javiereguiluz** [comment]
Could someone with experience in the Form component propose a fix for this? In theory it looks easy. We "just" need to do this somewhere:

```php
if (count(...) > (int) ini_get('max_input_vars')) {
    throw ...
}
```

**Comment by stof** [comment]
@javiereguiluz you can't do this, as the number of POST variables will never be bigger than the ``max_input_vars``.

and this becomes even harder: the max is not about the number of elements in ``$_POST``, but about the number of parameters in the request, i.e. when flattening ``$_POST`` (because PHP parses ``foo[bar]=1&foo[baz]=2`` into an array, but we still have 2 input vars).

I don't know whether PHP exposes a way to know that the max was reached.

If it does not, we could do a poor-man implementation by flattening ``$_POST`` (meh for performance), and then comparing its count to ``ini_get('max_input_vars') - 1`` (it will reject the case where you send *exactly* the max number of vars, but we cannot do better then)

**Comment by javiereguiluz** [comment]
So, for me this is a "won't fix" then. PHP says that:

> If there are more input variables than specified by this directive, an E_WARNING is issued, and further input variables are truncated from the request.

So you should see the `E_WARNING` somehow.

**Comment by iltar** [comment]
We didn't get any warnings as far as I know (perhaps we only logged errors?)

**Comment by stof** [comment]
@javiereguiluz but this warning probably happens before the Symfony error handler is registered (it probably happens at the very beginning of the process, as I don't think the processing of ``$_POST`` is delayed)

**Comment by xabbuh** [comment]
Do we have any chance to detect this issue when handling the form in the component? The way I understand the issue there is no way to achieve this.

**Comment by ro0NL** [comment]
Agree. IMHO the user is responsible for creating forms not exceeding the server limits.

**Comment by xabbuh** [comment]
Let's close here then.

**Comment by wadjeroudi** [comment]
@xabbuh @stof @ro0NL are you sure that with php 7 changes on error exception / throwable we can't catch the E_WARNING ?

**Comment by xabbuh** [comment]
@wadjeroudi Would you like to give it a try?

**Comment by wadjeroudi** [comment]
@xabbuh just tried, php 7 didn't improve anything on errors before script execution, but there's a solution that symfony already uses register_shutdown_function 

but symfony doesn't log e_warning errors : 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ErrorHandler.php#L637
