### ISSUE TITLE
[Client] Can't access the profiler in functional tests

### ISSUE THREAD

**Issue by nplhse** [symfony/symfony#20282]
I'm currently setting up some functional tests with symfony 3.1.5 and keep on running into an  issue when trying to evaluate if an email has been submitted successfully. 

I've enabled the profiler in my config_test.yml like this:

``` yaml
framework:
    profiler:
        enabled: true
        collect: false
```

Within my test I request the Swiftmailer via the Profiler like this:

``` php
$this->client->enableProfiler();

// Note: The following function is my abstraction of the submission of the recover email form
$this->requestRecoveryMail($email); 

$mailCollector = $this->client->getProfile()->getCollector('swiftmailer');
```

But I keep on getting the `Error: Call to a member function getCollector() on boolean` error. I think that I've located the problem and found out that `$this->client->getProfile()` always returns false. 

As far as I know this comes from line 85 in the [Symfony Profiler](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Profiler/Profiler.php#L85) where the value of the `X-Debug-Token` is always `null`.

I'm really not sure if this is an actual bug, or just my stupidity but during my research on this topic i found this [Post on a very similar issue on stackoverflow](http://stackoverflow.com/questions/35231270/symfony2-phpunit-functional-test-has-x-debug-token-header-instead-of-x-debug-tok). But in my case I wasn't even able to find the X-Debug-token header within the request.

(Note: The actual code of this test can be found [here in this repository](https://github.com/nplhse/arcella/blob/dev-users/tests/Arcella/UserBundle/Controller/PasswordRecoveryTest.php).)

**Comment by patrick-mcdougle** [comment]
Your profiler is getting disabled because you're not collecting. See https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L383-L385. I think removing the `collect: false` line from your config might help.

**Comment by nplhse** [comment]
Actually that helped, but I'm still having some trouble with this issue. Because as far as I understood the [manual says](http://symfony.com/doc/current/reference/configuration/framework.html#collect) that `collect: false`just implies that I need to trigger the execution of the Profiler manually via `$client->enableProfiler()`. Which is what I need, because I don`t want to profile every single request during the tests.

Also I've tried to figure out where this error actually came from and found out that the Profiler was actually executed the whole time and that the results always appear in the `var/cache/test/profiler` folder - including a correct `X-Debug-Token` header. But when the Profiler tries to load the Request via the `loadProfileFromResponse()` function it can't find the `X-Debug-Token`header no more.

**Comment by nplhse** [comment]
Finally I've figured out the source of error (and of cause it was my own fault):

In all the examples of sending emails in functional tests they always submit the email via a request and I'm doing this by submitting a form. And in this case I've just forgotten to set `$client->followRedirects(false)` prior to submitting to be able to access the correct Profiler data. 

Therefore I'm closing this issue because it's not a bug - but a feature I misunderstood.

**Comment by javiereguiluz** [comment]
@nplhse thanks to your comment I could fix a test that suffered the same problems. I've proposed to add some help in the Symfony Docs to prevent this error from happening to other developers: https://github.com/symfony/symfony-docs/pull/7115  Thanks!
