### ISSUE TITLE
no documented way of clearing a route's default/option/requirements

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony#20296]
I have a route object that a base class defines, and I want to remove an attribute from it, either a default, an option, or a requirement.

What seems to work is setDefault('propertyname', NULL), but that doesn't seem to be documented.

**Comment by Tobion** [comment]
What do you expect as solution of this issue?

**Comment by joachim-n** [comment]
Well I suppose either:

a) there is a way to clear a requirement (either NULL, or something else I'm not aware of). The docs should be fixed to mention this.
b) there is no correct way to clear a requirement, but using NULL works to clear a requirement, but it's an unintended effect. This should be adopted and documented.
c) there is no correct way to clear a requirement; using NULL works but should not be relied upon. This is a missing feature.

**Comment by javiereguiluz** [comment]
@joachim-n I've tested your code and it doesn't work for me:

```php
$route->getOption('foo');       // 'bar'
$route->hasOption('foo'));      // true
$route->setOption('foo', null);
$route->hasOption('foo'));      // true
$route->getOption('foo');       // null
```

It's a bit cumbersome, but you could do this to remove some options:

```php
->setOptions(array_diff($route->getOptions, ['foo']));
```

My only question would be: is this feature something needed that should be implemented ... or is it an edge-case and we can ignore it? Thanks!

**Comment by fabpot** [comment]
Closing as there is no more feedback here.

**Comment by joachim-n** [comment]
> My only question would be: is this feature something needed that should be implemented ... or is it an edge-case and we can ignore it? Thanks!

Surely that question was address to maintainers, rather than to myself?
