### ISSUE TITLE
Add support for detached processes

### ISSUE THREAD

**Issue by ricardofandrade** [symfony/symfony#20300]
Hi all,

I accidentally found out that:
`$process = new Process('sleep 60 >/dev/null');`
`$process->start();`
Will make the process run completely detached from the PHP.
That happens because two processes (PIDs) are created by the command and `Process` is tracking the wrong one for termination purposes (`stop()`).
This is exactly the behavior I wanted, but I'd prefer to have it without a hack.
Questions:
- Is this behavior intentional?
- Is this behavior expected?
- Is there any alternatives to run a detached process (I'm running version 2.8)?
- If not, is there interest to add support to it?

My apologies if there's already an issue on the same theme but I couldn't find one.

**Comment by nicolas-grekas** [comment]
Yep, this is expected, as it's the default behavior of php's native proc_open.
If you want to attach, run ` $process = new Process('exec sleep 60 >/dev/null');`

**Comment by theofidry** [comment]
You can found the doc related to that behaviour [here](http://symfony.com/doc/current/components/process.html#process-pid).

**Comment by javiereguiluz** [comment]
The first questions of @ricardofandrade have been addressed: this is the normal and expected behavior.

Now we need to answer his other questions:

* Is there any alternatives to run a detached process (I'm running version 2.8)?
* If not, is there interest to add support to it?

**Comment by nicolas-grekas** [comment]
We don't want to support detached processes. These are called zombie processes in fact.
Note that we do support background processes, which is something different.
