### ISSUE TITLE
Not correct email validation

### ISSUE THREAD

**Issue by Nidhognit** [symfony/symfony#20309]
Error:
In fom, user write email "test.@gmail.com", and form validation say 'valid', but i cant send message for this email, they is does not comply with RFC 2822, 3.6.2.

Form example:

``` php
            ->add('email', 'email', [
                    'required' => true,
                    'constraints' => [new NotBlank(), new Email()]
                ]
            )
```

System information:
Ubuntu 14, php 7.0.12, Symfony 2.8.12.

**Comment by ro0NL** [comment]
Ref #18177, #18428

I suggest to disable strict validation,  or create an issue at https://github.com/egulias/EmailValidator if you think its behavior is incorrect.

**Comment by xabbuh** [comment]
@Nidhognit Do you mean you experience what is described in #19359?

**Comment by jeremyFreeAgent** [comment]
Have you required `egulias/email-validator`?

**Comment by iltar** [comment]
The default validation of the Email validator does not do an extensive regex, it merely checks if the @ is present.

**Comment by dosten** [comment]
Since there are a lot of issues about this topic, why not open again the discussion to have a hard dependency on `egulias/email-validator`?

**Comment by sfarkas1988** [comment]
The email validator is useless from my point of view without strict mode.
The following email patterns are valid when using the email validator with default option:


```
        $validator = $this->getContainer()->get('validator');
        $emails = array(
            'xx@xx@virgilio.it',
            'xxx.mari@gmal..com',
            'xx.xx @alice.i',
            'xx.xx@gmal..com',
            'xx@hotmail.com;xxx.tgn.xxx@gencat.cat',
            'XXXX08@GMAIL.COM; XXXX@HUBU.ES'
        );

        foreach ($emails as $email) {
            var_dump($validator->validate($email, new Email()));
        }
```

**Comment by xabbuh** [comment]
Is there anything left to do here?
