### ISSUE TITLE
How do you integrate ReactJs  into Symfony?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#20318]
> I ask the question here to collect the ideas to integrate ReactJs into Symfony, any idea would be appreciated, hopefully, we can find some good practices to use them together. 

These days I am trying to integrate a javascript framework to my Symfony project,  I asked a [question](#20187)  here collect ideas,  after  lots of digging , I decide to use ReactJs,  there are lots of articles to show how to use reactJs with Symfony,  but most of them are elementary.  I don't plan to  use [ReactBundle](https://github.com/Limenius/ReactBundle)  to render service-side react code,  I decide to render all react component at client side , this is not a big performance issue at the moment. 

the biggest problem I met is  `building ReactJs form`, making each form component manually is quite tedious, there might be a better way. I found a fancy  ReactJs library that can build form automatically based on json schema, 
[react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form#form-data-changes)
it will be  wonderful that  if we can generate this kind of schema based on Symfony form type definition,  in theory, it possible to do this. I don't find any existing solution for this,  how do you solve this problem?  any question or solution can be here , so we can share our knowledge.

**Comment by javiereguiluz** [comment]
@videni sadly I need to close this issue because it's considered a support question instead of a real Symfony issue. It seems that you are new to the Symfony community, so let me explain this a bit more:

* In GitHub we only create issues to ask/discuss about new Symfony features and to report bugs/errors.
* The questions about using Symfony or solving problems in your applications are solved in the different Symfony support channels shown here: https://symfony.com/support

Now you may wonder: but how can I know that Symfony issues are not for asking questions about Symfony usage? You are right, you cannot know that. That's why in #20295 we are trying to improve the GitHub issues to display a message explaining the same that I told you in this comment.

I hope you understand it. Thanks!

**Comment by javiereguiluz** [comment]
@videni in the Symfony Documentation we opened an issue a few months ago to discuss about creating tutorials to integrate modern JavaScript tools into Symfony: https://github.com/symfony/symfony-docs/issues/6285  Sadly nobody has helped us with it so far 😭

**Comment by videni** [comment]
@javiereguiluz , thanks for your remind , this repo has bigger influence than symfony-docs, a few people would know the issues you opened there, I suggest we open this issue at least for a while,  this integration decision can't be made by a front-end developer, if we want to find a full solution, I think our backend develop needs to do some work, it is highly possible that one of us has done this job, I think finding a way to resolve this problem is more important than the rules.

**Comment by SpiGAndromeda** [comment]
ReactJS would also be perfect for my needs. I would linke to use ist für a collection type with complex mechanisms of selfs modifiying ... would be much easier by manipulate data from inside a react component. 

I tried to use the data option of the form components and set them to {this.state.*} but this only works for some form element types which accept strings. The render funtion should use the html code from the prototype attribute generated by the collection type. The whole thing doesn't seem to be applicable.

As far as I know React has some server support for using the rendered DOM (that's what I tried). But It doen't really work with Symfony and twig. So I guess integrating react would require at least a new option for the form classes and not so small adaptations in form rendering and templates ... I dont think that this could be done with a seperate bundle?

**Comment by videni** [comment]
@SpiGAndromeda , do you notice [LiformBundle](https://github.com/Limenius/LiformBundle)? it seems it is a great start point. I haven't found any big open source project that proves the true fact that using ReatJs and Symfony, I think our community should do something that fill this gap.

**Comment by SpiGAndromeda** [comment]
Thx @videni. Perhaps I'll try that with another project my current one is nearly finished.
