### ISSUE TITLE
How to use setAttribute on a Form field

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#20311]
I'm trying to use `setAttribute` or `setAttributes` on a form field but it doesn't work.

I've tried:

Test 1

    // Set data-stripe
    $form->get('company_data')
        ->get('legalName')->setAttributes(['data-stripe', 'name']);

Test 2

    // Set data-stripe
    $form->get('company_data')
        ->get('legalName')->setAttribute('data-stripe', 'name');

Test 3

    // Set data-stripe
    $form->get('company_data')
        ->get('legalName')->setAttributes(['attr' => ['data-stripe', 'name']]);

But no ones of those work.

I've written with more details a [question also on StackOverflow](http://stackoverflow.com/questions/40267844/how-to-use-setattribute-on-symfony-form-field) where I provide more code too.

Is this a correct behavior? Am I doing something wrong? Maybe I misunderstood the use of the methods?

**Comment by ro0NL** [comment]
`setAttributes(['attr' => ['data-stripe', 'name']])` should be `setAttributes(['data-stripe', 'name'])` right?

**Comment by Aerendir** [comment]
@ro0NL the first solution you proposed doesn't work.

The second is really "long": they are about 7 fields to which I have to add the attribute and doing all the procedure makes useless to embed the formtype I already have: I simply re-create the fields on the form. The advantage is completely lost if I have to write three lines for each editing (more I have to respect the form type, so if I change it in one place, I have to change it also here and most likely I'll forget to do and I'll break something.

Just a multiplication: 7 fields (the fields I have to add the attribute to) * 3 lines: 21 lines of (PROCEDURAL) code just to add a `data-stripe` attribute!

This is really useless as a simple `addOption()` method will solve the problem in a really smart way. Possible there isn't a method like this?

**Comment by ro0NL** [comment]
You're right, `setAttributes` has a different purpose. Modifying options after you defined the field (`add`) requires a different approach (dont ask me why, but take a look at https://stackoverflow.com/questions/11616789/symfony2-change-field-options-of-an-embedded-form).

**Comment by HeahDude** [comment]
You can only pass options to a `FormBuilderInterface`, the form has its config lot and you cannot modify your options once `$form = $builder->getForm()` is called.

I think we have to close here since there is no problem with Symfony in this case.

Please continue using the support channel, thanks :)

**Comment by Aerendir** [comment]
@HeahDude , there is no bug, for sure... But there is something like a feaature request as navigating StackOverflow too there are many users that needs to modify the options, also after the `$form->getForm()` method is called... We are speaking of simple editing, mostly to the `attr` field of the `$options` array. Maybe this may be taken into account, doesn't it?

**Comment by HeahDude** [comment]
The config being locked is part of the design, but allowing to modify it after building would be too risky and put in an unsafe state since options have to be resolved and that's only possible at the building step.
