### ISSUE TITLE
[Intl][Form] Support ISO 3166-1 Alpha-3 country codes

### ISSUE THREAD

**Issue by TerjeBr** [symfony/symfony#20313]
Could we please extend the form type `CountryType` via an option to make it support ISO_3166-1 Alpha-3 country codes?

Sources for the country codes:
- https://www.iso.org/obp/ui/
- http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
- https://github.com/thephpleague/iso3166
- https://gist.github.com/brianherbert/1687655

I'm currently working on a project where I need country codes as 3 characters instead of just 2.

Would it be possible to include a new alpha3 option or something to support 3 characters country codes? 

(This was first raised in #8492 but that issue was closed without being resolved properly)

**Comment by ldt** [comment]
In our app, we have reset the list of nationalities to handle it:

```php
        $nationalities = array_flip(Intl::getRegionBundle()->getCountryNames());
        $nationalities = array_map([$this, 'getISO3Code'], $nationalities);

        $builder
            ->add(
                'nationality',
                CountryType::class,
                [
                    'required' => $required,
                    'label'    => 'nationality',
                    'attr'     => [
                        'data-field'    => 'nationality',
                    ],
                    'choices' => $nationalities,
                    'preferred_choices' => array('FRA'),
                ]
            )
```

And it works fine in 3.1.x.
I recently tried to upgrade to 3.2.3 and I got 2 letters country codes so I had to downgrade back to 3.1.10. Any clues what could be involved?

**Comment by HeahDude** [comment]
Hi @Idt this is related to https://github.com/symfony/symfony/issues/20771.

**Comment by xabbuh** [comment]
@ro0NL Would we be able to provide access to the three-letter codes through the Intl API?

**Comment by surelygroup** [comment]
Have a look at https://github.com/symfony/symfony/issues/8492#issuecomment-221382428

**Comment by ro0NL** [comment]
Seems ICU has the same dataset available (from https://github.com/symfony/symfony/issues/8492#issuecomment-221382428)

https://github.com/unicode-org/icu/blob/13889bece13f51b0e9b3eef16cd34490c96da291/icu4c/source/data/misc/metadata.txt#L3840-L3843

So we could investigate this :)

Moreover, for languages we maintain the mapping ourselves:https://github.com/symfony/symfony/blob/7dfc97be9f3c997f243f33759cbe2ee990e2cb31/src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php#L32

But AFAIK it's also available in ICU, e.g. https://github.com/unicode-org/icu/blob/13889bece13f51b0e9b3eef16cd34490c96da291/icu4c/source/data/misc/metadata.txt#L14-L17

To be able to extra the "alpha3" lists we first need to understand the format. I think we need all codes only with reason=overlong.

**Comment by xabbuh** [comment]
Okay, so once the API from the Intl component allows us to access these data we should be able to extend the `CountryType` accordingly.

**Comment by surelygroup** [comment]
Be aware of the difference between language codes and region codes. They are not the same.

Region is about geographic country names.

Language codes is about codes for the different spoken languages.

The tables @ro0NL linked to seemed to all be about language codes and not region codes.

**Comment by ro0NL** [comment]
The icu metadata holds both languaes and regions/territories ;)

https://github.com/unicode-org/icu/blob/13889bece13f51b0e9b3eef16cd34490c96da291/icu4c/source/data/misc/metadata.txt#L5-L9


https://github.com/unicode-org/icu/blob/13889bece13f51b0e9b3eef16cd34490c96da291/icu4c/source/data/misc/metadata.txt#L2251-L2254

**Comment by TerjeBr** [comment]
Please have a look at https://github.com/symfony/intl/pull/10

I hope that can bring this issue closer to an implementation.

**Comment by TerjeBr** [comment]
Make that PR https://github.com/symfony/symfony/pull/32663 instead.

**Comment by TerjeBr** [comment]
Make that PR https://github.com/symfony/symfony/pull/32676 instead.

**Comment by TerjeBr** [comment]
The necessarry support in the Intl library has now been merged in #32988

**Comment by ro0NL** [comment]
Next step `alpha3 => true` for form types? Or what's the proposal :)

**Comment by TerjeBr** [comment]
Yes, but I might not have time for it until next week, or even later. Sorry.

But it should be a simple task now for anyone to pick up. If someone feels like it, feel free to submit a PR.
