### ISSUE TITLE
Improve the way stack traces are displayed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20320]
We've just [updated Symfony Demo to Symfony 3.2 beta1](https://github.com/symfony/symfony-demo/pull/393) and I saw the new log messages with the VarDumper component integration. It looks great! Thanks @wouterj and @nicolas-grekas for your work here.

---

The only thing that looks strange to me is that "stack traces" are not fully expanded. It's a bit weird to see that long empty list of arrows instead of the actual messages:

![deprecation_trace](https://cloud.githubusercontent.com/assets/73419/19758386/18b65d72-9c28-11e6-99c1-7eb7e65db534.png)

I know that you can Command+Click on an arrow to expand all its children ... but this behavior is not intuitive and it's not well-known. So my fear is that most people will do the following:

![deprecation](https://cloud.githubusercontent.com/assets/73419/19758443/57978138-9c28-11e6-85bf-04620a34dc5b.gif)

If you agree with this, could we please increase the level where the dump is expanded? Thanks!

**Comment by nicolas-grekas** [comment]
In fact, this view is buggy, you shouldn't see this (keepArgs, etc). I'm going to have a look at it.
