### ISSUE TITLE
Invalid default path for assets when customizing web directory

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#20329]
When the `web` directory is changed via Symfony extra config in `composer.json`:

``` json
{
    "extra": {
        "symfony-web-dir": "public"
    }
}
```

Then `php bin/console assets:install` fails because the default directory configured is still `web`.

version: Symfony SE 3.1.

**Comment by miisieq** [comment]
The` composer.json` property `symfony-web-dir` is used only for post-install and post-update script handling.

If you want to install assets in a specific target directory, the only option is to run the command with `target` parameter `php bin/console assets:install --target=public`.

**Comment by nicolas-grekas** [comment]
Closing as this is old, and Flex have changed things in this area. Please resubmit if still a blocker for you (or better: submit a fix :) )
