### ISSUE TITLE
After changing the locale on the translator the catalogue is not refreshed

### ISSUE THREAD

**Issue by stivenllupa** [symfony/symfony#20338]
Coming from the [documentation tip](http://symfony.com/doc/2.7/translation/locale.html) 

> Setting the locale using $request->setLocale() in the controller is too late to affect the translator. Either set the locale via a listener (like above), the URL (see next) or call setLocale() directly on the translator service.

I have a mailer service which needs to send emails in 2 languages (as of recently). Normally I tried to use the tip as mentioned above `$translator->setLocale('it_IT');` after generating the default mail texts in the default locale. Changing the locale would throw warnings that the same keys were not found for italian in this example. 

After some digging now I do : 

```
$translator->setLocale('it_IT');
$translator->getCatalogue('it_IT');
```

The second line is a "phantom" line in my code just so I force the translator to load the correct catalogue. This took me some time to figure out so it would be nice if there some more clarification on the `setLocale` method or best case, changing the method so that when you set the locale it loads the catalogue automatically.

**Comment by patrick-mcdougle** [comment]
You can just pass the `it_IT` string into `trans()` on the existing translator without changing the locale on the Translator class.

**Comment by stivenllupa** [comment]
@patrick-mcdougle I know, but in my case I had an already existing email templates architecture. To add the locale as a variable in the template would require a lot of files to be updated, contrary to the mailer service that I had wich requires 3 ~ 4 lines of code. So I see my solution as valid. This is why I am asking either write more explanation how the `setLocale` works / is intended for or make it so it does what looks natural.

**Comment by aitboudad** [comment]
Hi @stivenllupa using setLocale in your service should work, can you fork the Symfony Standard Edition and make the changes that are needed to reproduce the issue ?

**Comment by aitboudad** [comment]
The documentation tip you mentioned is about using the user locale stored in the request which is bit different to your use case

**Comment by stivenllupa** [comment]
@aitboudad I am going to look this weekend if I can make a fork of some form. Need to cut down a lot from my current project and see in the process if this is only for this project or universal.

**Comment by PaperCoder** [comment]
@stivenllupa I tried to confirm your issue with a reduced test case by forking the symonfy-standard but I'm not having your described issue. Could you plz give us more information or extend the fork to get your described problem?

https://github.com/pixelart/symfony-standard/commit/f685151d82faa0d9b4f5b4f0b2145aa60c58f51c

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. 

@stivenllupa Please leave a comment when you are able to give some steps to reproduce your issue.

**Comment by stivenllupa** [comment]
@xabbuh Sadly I am not able to create a fork due to project privacy. What I can do are some code snippets I have in the mailer service. Hope this can help: 

```
class NotificationMailer
{
    // ...
    /** @var \Swift_Mailer */
    private $mailer;
    /** @var EngineInterface */
    private $templating;
    /** @var TranslatorInterface */
    private $translator;
    // ...

   public function __construct( /* All the Dependencies */) { //... } 

   public function sendNotificationEmail(User $sourceUser, User $targetUser, $type, $values)
   {
        /* Prepare User related data */        
        $this->setEnglishLanguage();
        $subject = $this->translator->trans('prefix_headline_mail'); // Subject is only in English

        $bodyEnglish = $this->templating->render($template, $values);
        
        $this->setItalianLanguage();
        $bodyItalian  = $this->templating->render($template, $values);
        /* Put bodies in one */

       $mailMessage = \Swift_Message::newInstance()
            ->setSubject($subject)
            ->setFrom($from)
            ->setTo($to)
            ->setCc($cc)
            ->setBody($body, 'text/html');

        try {
            $this->mailer->send($mailMessage);
            $this->logger->info("A Mail was sent", array('to' => $to, 'subject' => $subject));
        } catch (Exception $e) {
            $this->logger->log("error", $e->getMessage());
        }
   }
   /* Other small data setting functions */
   protected function setEnglishLanguage()
   {
       $this->translator->setLocale('en_EN');
       $this->translator->getCatalogue('en_EN');
   }

   protected function setItalianLanguage()
   {
       $this->translator->setLocale('it_IT');
       $this->translator->getCatalogue('it_IT');
   }

    /* Other set language like functions */
}
```
At it's core this is it. What I have noticed though, is that at random this will not work. And the Italian keys are not found and displayed as keys. The English keys are translated. 

There is no apparent pattern for this, I do not have access to prod feedback so I usually see this behaviour only on dev environment, so I am not sure if 1) Am I doing something wrong? (It really feels like no) or 2) is there some misconfiguration or  another service doing something else? (Templating?)
