### ISSUE TITLE
[WebProfilerBundle] body end tag isn't mandatory

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#20339]
> A body element's end tag may be omitted if the body element is not immediately followed by a comment.

https://www.w3.org/TR/html5/sections.html#the-body-element

Following [Google HTML Style Guide](https://google.github.io/styleguide/htmlcssguide.xml) I noticed the toolbar isn't injected when the response doesn't contain `</body>` even if it is valid HTML. Could this be replaced with `<title>` which is the only mandatory tag?

This would require some minor changes in [toolbar_js.html.twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig):
- waiting for the DOM to be ready as `document.body` won't exist before
- creating the toolbar using JavaScript to append it where it won't break the DOM

**Comment by romainneutron** [comment]
Be careful, using JS to inject the toolbar might break Content Security Policy, keep our eyes open when reviewing a change on this part

**Comment by MatTheCat** [comment]
@romainneutron this wouldn't change anything, Content Security Policy doesn't care what scripts do.
