### ISSUE TITLE
[Config] ArrayNode cannotBeEmpty() problem

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#20356]
On the one hand, `->cannotBeEmpty()` method is accessible since it exists in the base NodeDefinition. On the other hand, arrays are not checked for being empty and don't have an `$allowEmptyValue` property.

So I can have:

```php
$treeBuilder
    ->root('acme')
        ->children()
            ->arrayNode('locales')
                ->isRequired()
                ->cannotBeEmpty()
                ->prototype('scalar')->cannotBeEmpty()->end()
            ->end()
        ->end()
    ->end();
```

and

```yml
acme:
    locales: []
```

and no exception will be thrown.

**Comment by ro0NL** [comment]
You should use `requiresAtLeastOneElement` instead. Problem is `ArrayNode` doesnt extend `VariableNode` as it implements `BaseNode` different.

It could be convenient to use the same naming..
