### ISSUE TITLE
Deprecation logs are no longer displayed in the "Deprecations" panel

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20370]
I'm upgrading a Symfony app to Symfony 3.2-beta1 and the deprecation messages are now displayed in the "Info. & Errors" panel whereas the "Deprecations" panel remains empty. This looks very wrong to me. Am I missing something?

![symfony_deprecations](https://cloud.githubusercontent.com/assets/73419/19847896/2f7f9b66-9f4a-11e6-9531-39e94726f0ab.png)

**Comment by stof** [comment]
can you show the context provided for these log messages ? Detection of deprecation log messages is based on the context. Your screenshot has the context collapsed

**Comment by javiereguiluz** [comment]
This is the context for a Sonata deprecation:

![log_context_1](https://cloud.githubusercontent.com/assets/73419/19860645/c05c88d0-9f89-11e6-8692-5702237253e5.png)

And this is the context for an Assetic deprecation:

![log_context_2](https://cloud.githubusercontent.com/assets/73419/19860651/c364c4f2-9f89-11e6-84c6-0f8ba0587cb2.png)

**Comment by stof** [comment]
hmm, too bad that dumping an ErrorException does not dump the severity 😞

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
@javiereguiluz can you please give me the output of `composer show`?

**Comment by nicolas-grekas** [comment]
Do you have a globally installed VarDumper maybe?

**Comment by nicolas-grekas** [comment]
The issue is that you have a log processor that transforms the original exception shipped in the context by an array that represents the exception, but is not the exception.
The core issue is that Symfony's logger data collector should not get through Monolog processing.
We need to see if we can rewire things in a cleaner way.
