### ISSUE TITLE
Display long strings in log contexts without trimming them

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20371]
After upgrading to Symfony 3.2-beta1, I realized that some strings in log contexts are being trimmed:

![long_message](https://cloud.githubusercontent.com/assets/73419/19848439/bdb40586-9f4d-11e6-982d-ce9e19acc363.gif)

I find this behavior annoying and unnecessary. If I click on the "Show context" log, there is no need to save space trimming long strings because I want to get all the information to solve the problem as quickly as possible. Maybe it's a good idea to trim absurdly long strings (10,000 characters?) but the rest of strings should be displayed unmodified.

**Comment by ogizanagi** [comment]
@javiereguiluz : You've tagged this issue with `VarDumper`. But a quick solution would be to increase the maximum number of chars before the `HtmlDumper` trims string, in `WebProfilerExtension` from the `WebProfilerBundle`.
AFAIK, you can do so by simply changing the value of `maxStringLength` by calling `HtmlDumper::setDisplayOptions`, or rather by adding it to the method call in `WebProfilerBundle/Resources/config/profiler.xml`.

Or do you think it requires a different feature from the `HtmlDumper` ?

**Comment by javiereguiluz** [comment]
@ogizanagi thanks for your comment. I like your proposal a lot. I'm trying to fix this in #20380.
