### ISSUE TITLE
[Cache] apcu_bc needed when upgrading to PHP7

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#20373]
We recently upgraded to PHP7, and are working on migrating to Redis, but in the meanwhile we still need APCu. Although I remember that APC support would be dropped with Symfony 3.0 this still left some traces. This required us to install [`apcu_bc`](https://pecl.php.net/package/apcu_bc), because we still are in the process of migrating from 2.8 to 3.1 due to Sylius.

- There still are docs about enabling framework / [annotation](http://symfony.com/doc/current/reference/configuration/framework.html#reference-annotations-cache) / [validation](http://symfony.com/doc/current/reference/configuration/framework.html#reference-validation-cache) / [templating](http://symfony.com/doc/current/reference/configuration/framework.html#reference-templating-cache) caching. The 3.1 branch for instance mentions APC, but does not mention APCu.
- Core only has an `ApcAdapter` that implements the `CacheInterface`, there is no `ApcuAdapter`.
- A `apcu` caching service for Doctrine also is missing with [the options](http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers).

Right now I'm working on implementing my own apcu adapter service, but can this be considered something that should be added to 2.8+ too? If so, we thereafter can get rid of the `apcu_bc` package.

**Comment by dunglas** [comment]
There is an `ApcuAdapter`: https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Cache/Adapter/ApcuAdapter.php and the Doctrine bundle also supports the APCu since 1.6.4: https://github.com/doctrine/DoctrineBundle/commit/641654a243967eb03946b005085f6f697f0d9935

It's mostly a doc issue.

**Comment by rvanlaak** [comment]
Thanks @dunglas, still on `2.8` here though ;) for the `doctrine` configuration section using `apcu` worked, but on `framework.validation.cache: apcu` we still get an exception:

> The service "validator.builder" has a dependency on a non-existent service "apcu".

**Comment by nicolas-grekas** [comment]
2.8 is bug fix only, so we're not going to add any new behavior there. `apcu_bc` is the way to go (ie the solution is in your infra, not in SF). Closing for this reason.

**Comment by rvanlaak** [comment]
I'm okay with that, recently completed upgrading to `3.2`, as Sylius `beta.1` was released. 

I do think that there are Symfony users that aren't allowed to install `apcu_bc` themselves (read: shared hosting, CI envs) so if they still are on `2.8` they can't work around this.
