### ISSUE TITLE
Neither the property "redirect" nor one of the methods "redirect()", "getredirect()"/"isredirect()" or "__call()" exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector" in @WebProfiler/Profiler/layout.html.twig at line 23.

### ISSUE THREAD

**Issue by EmyJ** [symfony/symfony#20387]
Hi,

I just update to Symfony 2.8 and i have a bug with the WebProfiler.
I can access to my web page but the profiler wont load and throw this error:

_Neither the property "redirect" nor one of the methods "redirect()", "getredirect()"/"isredirect()" or "_call()" exist and have public access in class "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector" in @WebProfiler/Profiler/layout.html.twig at line 23.

Here is my composer.json

"name": "symfony/framework-standard-edition",
"license": "MIT",
"type": "project",
"description": "The "Symfony Standard Edition" distribution",
"autoload": {
"psr-0": { "": "src/" }
},
"require": {
"php": ">=5.5.9",
"symfony/symfony": "2.8.",
"doctrine/orm": "~2.4",
"doctrine/doctrine-bundle": "~1.4",
"doctrine/doctrine-fixtures-bundle": "~2.2",
"twig/extensions": "~1.0",
"symfony/assetic-bundle": "~2.8",
"symfony/swiftmailer-bundle": "~2.3",
"symfony/monolog-bundle": "~2.4",
"sensio/distribution-bundle": "~4.0",
"sensio/framework-extra-bundle": "~3.0",
"sensio/generator-bundle": "~2.3",
"incenteev/composer-parameter-handler": "~2.0",
"symfony/icu": "1.0.@dev",
"gedmo/doctrine-extensions": "dev-master",
"white-october/pagerfanta-bundle": "dev-master",
"friendsofsymfony/user-bundle": "~2.0@dev",
"fp/openid-bundle": "dev-master",
"sonata-project/admin-bundle": "~3.9",
"sonata-project/doctrine-orm-admin-bundle": "~3.1",
"widop/google-analytics-bundle": "",
"excelwebzone/recaptcha-bundle": "dev-master",
"hwi/oauth-bundle": "0.5.-dev",
"lightopenid/lightopenid": "dev-master"

The subject who is already talking does not help me.
#94

Do you have any idea ?

**Comment by xabbuh** [comment]
Can you please show the output of `composer show`?

**Comment by EmyJ** [comment]
Here is the output of _composer show_

atoum/atoum                              2.8.2
atoum/atoum-bundle                       1.4.1
behat/transliterator                     v1.1.0
cocur/slugify                            v2.3
doctrine/annotations                     v1.3.0
doctrine/cache                           v1.6.1
doctrine/collections                     v1.3.0
doctrine/common                          v2.6.1
doctrine/data-fixtures                   v1.2.1
doctrine/dbal                            v2.5.5
doctrine/doctrine-bundle                 1.6.4
doctrine/doctrine-cache-bundle           1.3.0
doctrine/doctrine-fixtures-bundle        2.3.0
doctrine/inflector                       v1.1.0
doctrine/instantiator                    1.0.5
doctrine/lexer                           v1.0.1
doctrine/orm                             v2.5.5
excelwebzone/recaptcha-bundle            dev-master fff64c4
fp/openid-bundle                         dev-master 09dfd53
friendsofsymfony/user-bundle             dev-master 7271c17
fzaninotto/faker                         v1.6.0
gedmo/doctrine-extensions                dev-master 95b915a
hwi/oauth-bundle                         dev-master 429ae3f
incenteev/composer-parameter-handler     v2.1.2
ircmaxell/password-compat                v1.0.4
jdorn/sql-formatter                      v1.2.17
knplabs/knp-menu                         2.2.0
knplabs/knp-menu-bundle                  2.1.3
kriswallsmith/assetic                    v1.3.2
kriswallsmith/buzz                       v0.15
lightopenid/lightopenid                  dev-master 9d42dc2
monolog/monolog                          1.21.0
pagerfanta/pagerfanta                    v1.0.3
paragonie/random_compat                  v2.0.3
psr/cache                                1.0.1
psr/log                                  1.0.2
sensio/distribution-bundle               v4.0.12
sensio/framework-extra-bundle            v3.0.16
sensio/generator-bundle                  v2.5.3
sensiolabs/security-checker              v3.0.2
sonata-project/admin-bundle              3.9.0
sonata-project/block-bundle              3.2.0
sonata-project/cache                     1.0.7
sonata-project/core-bundle               3.1.1
sonata-project/doctrine-orm-admin-bundle 3.1.1
sonata-project/exporter                  1.7.0
swiftmailer/swiftmailer                  v5.4.3
symfony/asset                            v2.8.13
symfony/assetic-bundle                   v2.8.0
symfony/class-loader                     v2.8.13
symfony/config                           v2.8.13
symfony/console                          v2.8.13
symfony/debug                            v2.8.13
symfony/dependency-injection             v2.8.13
symfony/doctrine-bridge                  v2.8.13
symfony/event-dispatcher                 v2.8.13
symfony/expression-language              v2.8.13
symfony/filesystem                       v2.8.13
symfony/finder                           v2.8.13
symfony/form                             v2.8.13
symfony/framework-bundle                 v2.8.13
symfony/http-foundation                  v2.8.13
symfony/http-kernel                      v2.8.13
symfony/icu                              1.0.x-dev fdba214
symfony/intl                             v2.8.13
symfony/monolog-bundle                   2.11.1
symfony/options-resolver                 v2.8.13
symfony/phpunit-bridge                   v3.1.6
symfony/polyfill-apcu                    v1.2.0
symfony/polyfill-intl-icu                v1.2.0
symfony/polyfill-mbstring                v1.2.0
symfony/polyfill-php54                   v1.2.0
symfony/polyfill-php55                   v1.2.0
symfony/polyfill-php56                   v1.2.0
symfony/polyfill-php70                   v1.2.0
symfony/polyfill-util                    v1.2.0
symfony/process                          v2.8.13
symfony/property-access                  v2.8.13
symfony/routing                          v2.8.13
symfony/security                         v2.8.13
symfony/security-acl                     v3.0.0
symfony/security-bundle                  v2.8.13
symfony/stopwatch                        v2.8.13
symfony/swiftmailer-bundle               v2.4.0
symfony/symfony                          v3.1.5
symfony/templating                       v2.8.13
symfony/translation                      v2.8.13
symfony/twig-bridge                      v2.8.13
symfony/twig-bundle                      v2.8.13
symfony/validator                        v2.8.13
twig/extensions                          v1.4.1
twig/twig                                v1.27.0
white-october/pagerfanta-bundle          dev-master 394c0a2
widop/google-analytics                   1.0.0
widop/google-analytics-bundle            1.1.0
widop/http-adapter                       1.0.2
widop/http-adapter-bundle                1.1.1

**Comment by dosten** [comment]
Hmmm.. Actually you are using Symfony v3.1.5 but seems like for some reason you have also installed the standalone components at version 2.8.13 this is causing your problem.
As I can see, there is not problem with Symfony itself but with Composer.
In your `composer.json` you have `"symfony/symfony": "2.8.",` with a missing `*`. It should be `"symfony/symfony": "2.8.*",`

**Comment by EmyJ** [comment]
oh, thank you for your help.
