### ISSUE TITLE
Proposal: new Lock component

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#20382]
The new 3.2 release of Symfony improve the integration of the framework in containers (cache, dynamic env vars, etc...).
With such containers, it's easier to scale our services no matter the physical machine where the service ends up. But this bring a new issue: sometimes services need to lock some things, and actually, the framework only expose a "local" filesystem lock (which is good and efficient for a local usage).

At first I just wanted to create a PR to add a new RedisLockHandler (which implement the [redlock strategy](http://redis.io/topics/distlock)). But I wonder where to put the code. IMO, it doesn't make sens to add such feature in the filesystem component.

That's the subject of this issue:

* [ ] Do we need such feature in Symfony.
* [ ] Where should it be located (new component?)

If a new component is created, then,  other lock could be implemented:
 - filesystem
 - semaphore
 - memcached
 - redis
 - pdo

Such cross-network locks could solve issues like #4976

**Comment by javiereguiluz** [comment]
@jderusse thanks for this proposal. It theory it looks nice; in practice I don't know if they are so common to justify a new component.

Besides, I'd like to know if other frameworks (PHP or not) provide this component/plugin/package/library too. Thanks!

**Comment by stof** [comment]
IIRC, the discussion when adding the filesystem lock explicitly decided that a full distributed lock system was left to external libraries rather than being provided by Symfony.
And there are many libraries about this: https://packagist.org/search/?q=lock

**Comment by jderusse** [comment]
@javiereguiluz I did not find any implementation integrated in a framework except JBoss.

@stof Fully agreed with the point. This issue is just to ask if this two years old decision is still relevant? Especially when the world is slicing to serverless architecture...

If this feature does not worst it, we can close this issue. 
Globally, I wonder how to know when a feature should stay in separate package and when it may be integrated in the framework.
For instance, packagist list ~ 1500 *cache related* libraries and, IMHO, it was a good thing to provide this feature directly in the framework.

**Comment by fabpot** [comment]
I agree with @jderusse that we should at least consider re-discussing the need to have something in Symfony. @jderusse I think the first step would be to do some research on existing libraries and see if some of them are "good enough". The discussion will then be much easier as we would know what to do based on the strengths and the weaknesses of the existing libraries.

**Comment by jderusse** [comment]
After some research in php (and other languages) libraries:
[https://github.com/remi-san/lock](remi-san/lock) is a pretty good base with several interface to manage the usual cases but contains only a redis implementation
other packages like [https://github.com/malkusch/lock](malkusch/lock) and [https://github.com/arvenil/ninja-mutex](arvenil/ninja-mutex) expose several backend but are less extensible.
(more detail below)
On distributed backends, most of packages implement the [http://redis.io/topics/distlock](redlock stragegy). 

## Here is my detail notes:

### php libraries

#### [https://github.com/remi-san/lock](remi-san/lock)
- well splited (several interfaces: token generators, quorum, store, etc..)
- redis focused +> may be extended to other providers thanks to interfaces
- some bug (ie: isLocked => don't take quorum strategy into account)
- backend returns the expiration date

#### [https://github.com/malkusch/lock](malkusch/lock)
- several backends (CAS, flock, memcached, redis, semaphore, transaction)
- some backend are weird : the transaction lock does not use a lock at db level, but, replay the operation till there isn't any sql exception

#### [https://github.com/cheprasov/php-memcached-lock](cheprasov/php-memcached-lock)
- only memcached, but interessant
- implement a refresh method to extends an expiration date
- handle many case in a memcache implementation but complex implementation

#### [https://github.com/cheprasov/php-redis-lock](cheprasov/php-redis-lock)
- have a optimized implementaiton of redis->exec (first call to execSha1 fallback to execLua)

#### [https://github.com/arvenil/ninja-mutex](arvenil/ninja-mutex)
- several backends (memcached, mysql, redis, flock, directory(???))
- big factory to create lock (key and LockerImpl as parameter)
- oriented lock service and key as argument
- missing a quorum feature

#### [https://github.com/ronnylt/redlock-php](ronnylt/redlock-php)
- take drift factor into account
- everything in one class (unlock sensible to failure)

#### [https://github.com/sensiolabs/consul-php-sdk](sensiolabs/consul-php-sdk)
- not a lock package, but contains a consul implementation
- https://github.com/sensiolabs/consul-php-sdk/blob/master/Consul/Helper/LockHandler.php
- what if the session is lost during a job ?


## redlock implemented in other languages

#### [https://github.com/SPSCommerce/redlock-py](SPSCommerce/redlock-py)
- implement a TTL drift
- retry / retryCount

#### [https://github.com/hjr265/redsync.go](hjr265/redsync.go)
- implement a refresh method (https://github.com/hjr265/redsync.go/blob/master/redsync/mutex.go#L252)

#### [https://github.com/mike-marcacci/node-redlock](mike-marcacci/node-redlock)
- implement a TTL drift
- retry / retryCount


## regardins issues in these libraries, we have to beware of:

- When using lock bases on connection (DB get_lock or consul) the lock may be release lock when connexion is lost => did not mean, the process is dead.
- interesant lecture on clock jump [https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html](https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html)
- Do we need to try to lock every nodes (optimization)
    => If quorum is met => STOP locking other resources
    => If quorum can't be met (too much failure) => ABORT locking

## backend Strategies / Features

### handle by kernel

Lock is handle by something who know when the process is terminated (ie: flock) and can unlock the resource when the process died unexpectly

pro: Don't worry about unlock
con: Work only on localhost

### timeoutable

The backend is in charge to unlock the resource. If it don't, the resource will automatically be unlocked after a given TTL.

pro: can be implemented every where
con: hard to define the TTL. When to small, the lock may not finish it job in time. When to big, the backends have to wait a lot after a previous failure
    a lock can be released (due to timeout) whereas the initial worker is still working

evolution: Somme package implement a "refresh" feature in charge of pushing the TTL
```
$lock = new Lock('foo');

// Aquire a 10 seconds lock
$lock->lock();
foreach ($jobs as $job) {
    // Assert a <10 seconds job
    $job->run();

    // refresh the lock for 10 more seconds
    $lock->refresh();
}

$lock->release();
```

### multi store nodes

The state of locks could be stored in multiple unsynchronized stores. (ie redis)
The backend have to try to aquire lock in a majority of nodes

pro: Lock storage more scalable
con: slow (multiple call to aquire lock)
    every backend must use the same list of nodes
    hard to define the same TTL for every nodes
    sensible to clock jump

### Compare and swap (CAS)

Does not realy lock a resource, but provide a way to perform atomic instruction by retrying the operation until a shared memory is not modified between the beginig and the end of the operation.

pro: can be implemented every where
con: backend must be aware that the operation may have to be repeated several times

### auto release

Some loks may throw warning when not released (ie: sem_aquire). Could be usefull to implement __destruct and/or register a shutdown function to automaticaly release these locks

### blocking (or non blocking)
- Loker wait (or not) for a previous lock to release the lock

### LockInfo
- provide informations about a lock (backend, lock acquire time, lock expiration)

### One lock per key vs One lock to manage all locked resources

```
$lock = new Lock('key')
$lock->lock();
```

vs

```
$lock = new Lock()
$lock->lock('key');
```


pro/con: same process can manage concurency at it own level. Usefull for app like reactphp ie: $lock1=new Lock('foo') will be locked by $lock2=new Lock('foo'))
con/pro: need factory for complexe locks (ie: redislock need a connection to the servers)


## possible backends

- null
- array/memory
- flock
- filesystem
- redis
- memcache
- [https://en.wikipedia.org/wiki/Compare-and-swap](cas)
- semaphore
- consule
- pdo (SELECT GET_LOCK(...))
- consul
- etcd
- zookeeper

**Comment by jderusse** [comment]
Thank you all for your help in reviewing these PR
