### ISSUE TITLE
[Serializer] XmlEncoder : Add a way to remove empty tags

### ISSUE THREAD

**Issue by amoiraud** [symfony/symfony#20398]
Hi I have to generate an XML without any empty tags.

Right now I use the XmlEncoder to generate it and I have some thing like : 

```xml
    <node>
         <subnode>Value</subnode>
          <emptysubnode/>
    </node>
```

And what I need in output is : 

```xml
    <node>
         <subnode>Value</subnode>
    </node>
```
I can acheive this by changing XmlEncoder buildXml method L396 : 

changing this : 

```php
    } elseif (is_numeric($key) || !$this->isElementNameValid($key)) {
        $append = $this->appendNode($parentNode, $data, 'item', $key);
    } else {
        $append = $this->appendNode($parentNode, $data, $key);
    }
```
to this

```php
    } elseif (is_numeric($key) || !$this->isElementNameValid($key)) {
        $append = $this->appendNode($parentNode, $data, 'item', $key);
    } else {
        if ($data !== null) {
            $append = $this->appendNode($parentNode, $data, $key);
        }
    }
```

Is there a way to do that ? or we can add this feature but I don't really see how to do it ?

**Comment by dunglas** [comment]
Some people may want this behavior, but most people probably prefer having empty tags. The are 2 solutions here:

* Open a Pull Request with your patch but make it configurable using the `$context` parameter (with a key like `remove_empty_tags`)
* Decorate the XmlEncoder in your own project (using service decoration) and remove empty tags

**Comment by ogizanagi** [comment]
This one can be closed as the related PR has been merged.

**Comment by magarzon** [comment]
Why don't have the same for the JsonEncoder (or any encoder)?

**Comment by dunglas** [comment]
Not yet.

**Comment by sdykae** [comment]
Any thoughts on JsonEncoder?

**Comment by nantkowiak** [comment]
@sdykae just follow this instructions: https://symfony.com/doc/current/components/serializer.html#skipping-null-values

**Comment by nebkam** [comment]
Seems to me this setting is being ignored while `decoding` - empty tags are being decoded as empty strings, not `null`
