### ISSUE TITLE
[Yaml] Failing DateTime tests for Symfony\Component\Yaml\Tests\InlineTest

### ISSUE THREAD

**Issue by Einenlum** [symfony/symfony#20399]
PHPUnit tests are broken on master for `Symfony\Component\Yaml\Tests\InlineTest`.

```diff
There were 3 failures:

1) Symfony\Component\Yaml\Tests\InlineTest::testParseTimestampAsDateTimeObject with data set "date" ('2001-12-15', 2001, 12, 15, 0, 0, 0)
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
-2001-12-15T23:00:00+0000
+2001-12-14T23:00:00+0000

2) Symfony\Component\Yaml\Tests\InlineTest::testParseNestedTimestampListAsDateTimeObject with data set "date" ('2001-12-15', 2001, 12, 15, 0, 0, 0)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'nested' => Array (
-        0 => 2001-12-15T23:00:00+0000
+        0 => 2001-12-14T23:00:00+0000
     )
 )

3) Symfony\Component\Yaml\Tests\ParserTest::testParseDateAsMappingValue
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'date' => 2002-12-14T00:00:00+0000
+    'date' => 2002-12-13T23:00:00+0000
 )

FAILURES!
Tests: 559, Assertions: 787, Failures: 3.
```

Could it be linked to Daylight Saving Time?
(thanks @iltar for your help on this)

**Comment by iltar** [comment]
Additionally I also have this error that I think that could be related:

```
1) Symfony\Component\Serializer\Tests\Normalizer\DateTimeNormalizerTest::testDenormalizeUsingFormatPassedInContext
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
-2016-01-01T00:00:00+0000
+2016-01-01T00:00:00+0100

```

**Comment by Einenlum** [comment]
@iltar In my case there is 1 hour + 1 day of difference. It seems in your case it's only 1 hour.
Linked to datetime php config?

**Comment by Einenlum** [comment]
@iltar Indeed, same result for `DateTimeNormalizerTest`

**Comment by stof** [comment]
@iltar what is your configured timezone ?

**Comment by iltar** [comment]
@stof 
```
$ php -r "echo date_default_timezone_get();"
Europe/Amsterdam
```

**Comment by stof** [comment]
I think these tests should force the timezone to be in UTC, as they expect the date to be dumped in UTC

**Comment by iltar** [comment]
Probably went right because of summer time :(

**Comment by Einenlum** [comment]
@iltar what is strange is I don't only have a diff of 1hour between what is get and what is expected. I have 1 day + 1 hour.

**Comment by nicolas-grekas** [comment]
PHP 7.1 changed a bit here, I already patched master on similar issues in #20291

**Comment by stof** [comment]
@nicolas-grekas has it been reported as a BC break to PHP ?

**Comment by nicolas-grekas** [comment]
Nope, I didn't want to get there on internals ;)
And the change is borderline between bug fix and BC break. But I may be wrong so if someone wants to open the topic, please do!
