### ISSUE TITLE
[Validator] Groups and `inContext` validation

### ISSUE THREAD

**Issue by hvt** [symfony/symfony#20394]
Considering this class `A`:

```php
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Mapping\ClassMetadata;

class A {

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new Assert\Callback(['callback' => 'isGeneralValid']));
        $metadata->addConstraint(new Assert\Callback(['callback' => 'isGroupValid', 'groups' => ['bar']]));
    }

    public function isGeneralValid(ExecutionContextInterface $context)
    {
        $validator = $context->getValidator();
        $validator
            ->inContext($context)
            ->atPath('foo.general')->validate('', new Assert\NotBlank)
        ;
        $this->isGroupValid($context);
    }

    public function isGroupValid(ExecutionContextInterface $context)
    {
        $context
            ->buildViolation('manual violation')
            ->atPath('foo.group')
            ->addViolation()
        ;
        $validator = $context->getValidator();
        $validator
            ->inContext($context)
            ->atPath('foo.group')->validate('', new Assert\NotBlank)
        ;
    }

}
```
It might be that I'm using the `inContext` validation wrong...

I'm validating this class as follows (using the 2.8.13 validator):
```php
$a = new A;

$violations_general = $validator->validate($a);
if (0 !== count($violations_general)) {
    echo "GENERAL VIOLATIONS:\n";
    foreach ($violations_general as $violation) {
        echo "\t".$violation->getPropertyPath().": ".$violation->getMessage()."\n";
    }
}
```

Validating the entire class results in the expected result:
```
GENERAL VIOLATIONS:
	foo.general: This value should not be blank.
	foo.group: manual violation
	foo.group: This value should not be blank.
```

However, now let's only validate the `bar` group:
```php
$violations_group = $validator->validate($a, null, 'bar');
if (0 !== count($violations_group)) {
    echo "GROUP VIOLATIONS:\n";
    foreach ($violations_group as $violation) {
        echo "\t".$violation->getPropertyPath().": ".$violation->getMessage()."\n";
    }
}
```
This is the (unexpected) output:
```
GROUP VIOLATIONS:
	foo.group: manual violation
```

Where I would have expected this:
```
GROUP VIOLATIONS:
	foo.group: manual violation
	foo.group: This value should not be blank.
```

So in-context validation of a particular group, does not go well. Not really sure what the problem is though...

**Comment by stof** [comment]
Well, your NotBlank constraint is in the default group, and your ``validate()`` calls does not define the validated groups, which means you ask Symfony to keep using the same group than currently. So the constraint does not match the validated groups

**Comment by hvt** [comment]
So if I understand it well, the group definition of the `Callback` constraint on the `isGroupValid` method, is not 'inherited' when validating anything by using the `ContextualValidatorInterface`? (It is when manually building violations.)

What should I do to achieve what I want :]? Should I really include the group constraint for each and every constraint I'm testing in the `isGroupValid` method? This was not needed when I used `validateValue` calls from inside the `isGroupValid` method.

**Comment by xabbuh** [comment]
@hvt Well, you need to make sure that the `NotBlank` constraint is added to the `bar` group.

**Comment by courtney-miles** [comment]
Right or wrong, it is worth noting the inconsistency here, and that the PHPDoc is misleading.

The `$groups` argument on `\Symfony\Component\Validator\Validator\ContextualValidatorInterface::validate` is documented as:

> The validation groups to validate. If none is given, "Default" is assumed

This is incorrect.  The `ContextualValidatorInterface::validate()` will default to group of the context, and not "Default".

Take the following example, where the MyConstrainValidator would be used with group validation.

```php
class MyConstraintValidator extends ConstraintValidator
{
    public function validate ($value, $constrain) {
        // This validate call will trigger regardless of `$this->context->getGroup()`.
        $validator = $context->getValidator()->validate('', new Assert\NotBlank());

        // This validate call will only work if `$this->context->getGroup() == "Default"`.
        $context->getValidator()->validate('', new NotBlank());
    }
}
```

So your custom constraints must be group sensitive.  Which I dont' think is ideal, since you would not want to hardcode any groups names in your constraints.  So these are your options.

```php
class MyConstraintValidator extends ConstraintValidator
{
    public function validate ($value, $constrain) {
        $context->getValidator()->validate('', new NotBlank(), 'Default');
        // or ...
        $context->getValidator()->validate('', new NotBlank(['groups] => $this->getGroup()));
    }
}
```
