### ISSUE TITLE
[ProxyManager] Support final classes

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#20392]
A service may be declared as final. In that situation, when the service is registered as lazy to Symfony DIC, it will throw an exception:

    [ProxyManager\Exception\InvalidProxiedClassException] Provided class "Foo" is final and cannot be proxied

Where actually it *can* be proxied: you just need to proxy the parent class or the implemented interface instead like done in Zend\ServiceManager. I'm not sure how you are supposed to do however when your class extend another one and/or implements one or several interfaces. But the alternatives are:

- Create a non-final decorator and use it instead
- Remove the `final` keyword (not always doable)

TBH I think those two alternative solutions kind of sucks as I don't think the usage of a DIC should influence how you design you services.

Thoughts?

**Comment by xabbuh** [comment]
Not sure what we should do in Symfony here. This issue is simply related to how the proxy manager library works, isn't it?

**Comment by theofidry** [comment]
I though so as well but the proxy manager just creates a proxy for what you
ask. Handling a final class and proxying the interface or parent class
instead of the final class would be something to do at the integration
level instead

**Comment by Ocramius** [comment]
When proxying a final class, assuming that class implement an interface (completely), that interface can be proxied instead.
This is currently unsupported in the symfony DIC, and it would probably force too much detail into the service definition.
AFAIK, auto-wiring requires that (if constructor types point at interfaces) a preferable interface is mapped for the various services. Maybe we can use that?

**Comment by theofidry** [comment]
@Ocramius very naive and (overly?) demanding comment on my part: I don't feel right that I have to be wary of using the final keyword just because of the way my class is registered to a DIC.

**Comment by Ocramius** [comment]
Can't do much about it. Roave/BetterReflection just got to a decent shape after a full year of work, and it still needs to be integrated in order for me to allow monkey-patching of classes (removing `final` modifier at runtime).

Even then, the correct solution is proxying the interface, as I described above. Look up zendframework/zend-servicemanager's docs about lazy services to see how it is done there.

**Comment by theofidry** [comment]
@Ocramius I can accept proxying the implemented interface, but as of now I got no option of what I'm proxying in Symfony DIC :/ An alternative is to 1. remove the final keyword, 2. have a non final decorator for my service which I will declare as a proxy instead but both really sucks

**Comment by Ocramius** [comment]
Welcome to software engineering: the art of trade-offs.

**Comment by theofidry** [comment]
Come one don't make me cry 😭

**Comment by Ocramius** [comment]
You can either work with what you have now, or you can work with perfect
technology, given lim t → ∞

**Comment by javiereguiluz** [comment]
Closing it because it seems there's nothing left to do here for Symfony. Thank you all for the discussion and the solutions provided.

**Comment by stof** [comment]
@javiereguiluz wre could have a feature in Symfony allowing to request proxying based on an interface rather than based on the class itself, to solve this issue.
We cannot decide to do it automatically though, as some other class may have the final class itself as typehint (which is why we use the class itself for the proxy).

This would not be hard to implement. We could just add another attribute alongside ``lazy`` (or allow passing ``lazy: className``), and validating that the actual service class indeed is a child of the provided proxied class.
I suggest looking at it for 3.3

**Comment by javiereguiluz** [comment]
@stof thanks for the insights. Reopening it then!

**Comment by nicolas-grekas** [comment]
I think planning for this feature is really doing over-engineering for non-general-but-narrow cases.
IMHO, if such cases of `final` are found that prevent some classes to be turned into lazy proxies, the `final` key word should just be removed. Adding an `@final` annotation instead should be the way to go.
The better way would be for PHP core to allow creating lazy-proxies natively. Let's dream a bit and get back to reality:
> Welcome to software engineering: the art of trade-offs.

;)

**Comment by theofidry** [comment]
@nicolas-grekas I'm fine with that if you add a 👍 to https://youtrack.jetbrains.com/issue/WI-31225 ;)

**Comment by nicolas-grekas** [comment]
Looks like you first need to open a PR on PHPDocumentator 2 (or PSR-5.)

**Comment by theofidry** [comment]
See https://github.com/phpDocumentor/fig-standards/issues/139

**Comment by nicolas-grekas** [comment]
Closing in favor of #20656
