### ISSUE TITLE
Entity Type "choice value" Callback function

### ISSUE THREAD

**Issue by epixilog** [symfony/symfony#20402]
`Hi` everyone, 

According to the documentation (http://symfony.com/doc/current/reference/forms/types/entity.html#choice-value), choice value should work exaclty like choice label. But it seems like callback function is not working correctly. 

So if I call for exmaple : 

`
$builder->add('category', EntityType::class, array(
    'class' => 'AppBundle:Category',
    'choice_value' => function ($category) {
        return $category->getDisplayName();
    }
));
` 

This will give me something like : 

> Call to a member function getDisplayName() on null

What's driving me crazy is when I'm "vardumping" the $category->getDisplayName() it shows the value correctly.

Thanks for your help in advance

**Comment by HeahDude** [comment]
Hi @epixilog, the documentation needs an update for choice related types ;)

You just need to handle the case where the placeholder is checked as an existing choice:
```php
$builder->add('category', EntityType::class, array( 
    'class' => 'AppBundle:Category', 
    'choice_value' => function (Category $category = null) {
        return null === $category ? '': $category->getDisplayName();
    },
));
```

**Comment by xabbuh** [comment]
Closing here as this is a documentation issue as @HeahDude explained.
