### ISSUE TITLE
[DX] More details about events fired in web profiler

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#20403]
Currently we can see which events were fired and its listeners ordered by its priority. These informations is very helpful to debug the dispatcher component. In addition, it would be very nice if we can see the dump of the Event object near to the listeners in the same order as they were fired. I'm currently building an application based on events so the more information about the events is better to debug them. Does this improvement make sense?

**Comment by derrabus** [comment]
Dumping all events could potentially bloat the profiles taken. For instance, all kernel events have the fully booted kernel (including the service container) attached to them. If you dump that event object, you'll probably get more information than you've ever asked for.

While an exception could be made for the kernel events to not include the kernel in those dumps, we could run into similar problems with custom events where we cannot make general assumptions on what information is safe to include.

What you could do is attaching a logging event handler with maximum priority to the events that you want to look into.

**Comment by javiereguiluz** [comment]
@tsantos84 although I like your proposal ... the implementation would be impractical for the reason explained by @derrabus. That's why I must vote :-1: to this proposal.

**Comment by tsantos84** [comment]
Hi @javiereguiluz and @derrabus, I agree with you both although I thought about make it configurable in framework bundle, so we can enable/disable this feature on demand.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" for now ... but we can revisit the idea in the future! @tsantos84 although this time your proposal didn't make it, please keep proposing new features or improvements for Symfony. Thank you!
