### ISSUE TITLE
PREG_BACKTRACK_LIMIT_ERROR in Yaml parser

### ISSUE THREAD

**Issue by RichardBradley** [symfony/symfony#20411]
A YAML string with too many backslash escapes can trigger a `PREG_BACKTRACK_LIMIT_ERROR ` error in the Yaml parser.

## Steps to reproduce:

Run the following unit test:

```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Yaml\Yaml;

class YamlParserBacktrackLimitTest extends WebTestCase
{
    public function testYamlQuotedString() {

        $foo = str_repeat("x\r\n\\\"x\"x", 1000);
        $yamlString = Yaml::dump(["foo" => $foo]);

        $arrayFromYaml = Yaml::parse($yamlString);

        $this->assertEquals($foo, $arrayFromYaml['foo']);
    }
}
```

## Observed behaviour

This test will pass if you reduce the "1000" constant to "100", and fail as-is.

The reported exception is:
```
Malformed inline YAML string ("x\r\n\\\ ...
at n/a
        in ...\vendor\symfony\symfony\src\Symfony\Component\Yaml\Inline.php line 344
```

The relevant source [is here](https://github.com/symfony/symfony/blob/172d0a4c08f11e1f1e1f9ad28302d3a8bda51492/src/Symfony/Component/Yaml/Inline.php#L344): 

```
       const REGEX_QUOTED_STRING = '(?:"([^"\\\\]*(?:\\\\.[^"\\\\]*)*)"|\'([^\']*(?:\'\'[^\']*)*)\')';
...
        if (!preg_match('/'.self::REGEX_QUOTED_STRING.'/Au', substr($scalar, $i), $match)) {
            throw new ParseException(sprintf('Malformed inline YAML string: %s.', substr($scalar, $i)));
        }

```

## Expected behaviour

1. The test should pass, i.e. the YAML should be parseable, since it fits in memory and is well formed.

2. The exception thrown by Symfony if the `preg_match` fails due to `PREG_BACKTRACK_LIMIT_ERROR` should indicate that the op failed due to resource exhaustion and not incorrectly blame invalid YAML.

## Suggested fix

I suspect that changing the `REGEX_QUOTED_STRING` regex to use [possessive qualifiers](http://www.regular-expressions.info/possessive.html) will probably fix bug 1 above without otherwise changing the YAML parser's behaviour.

Fixing bug 2 above needs a call to `preg_last_error()` after each "`preg_match`" call in Symfony code, which will be tedious.

**Comment by stof** [comment]
using possessive quantifiers should indeed be done.

Regarding your point 2, this would involve distinguishing ``0`` and ``false`` as return value for ``preg_match`` (``false`` would indicate a regex error, which should trigger a different exception saying that something was broken in the parser).
But this is quite tedious indeed, so it would be better to fix the root error (avoid needless backtracking)

**Comment by mahagr** [comment]
:+1:  Thanks for fixing this one, its a big one. It should also improve yaml parsing performance (on affected input) by a great deal.

**Comment by RichardBradley** [comment]
You're welcome.

Do you know when I can expect a 3.2 based release which will include this fix?

**Comment by mahagr** [comment]
I'm waiting for the release as much as you do :)

**Comment by xabbuh** [comment]
Since the last patch releases have just been released two days ago you will have to wait for about four weeks for the next releases.
