### ISSUE TITLE
Best way to override ServerRunCommand and ServerStartCommand?

### ISSUE THREAD

**Issue by pocky** [symfony/symfony#20429]
Hello,

I am using a non-standard folder structure and I just discovered a "problem" with `server:run` and `server:start` (for me it's a DX) :

```
        $documentRoot = $input->getOption('docroot');

        if (null === $documentRoot) {
            $documentRoot = $this->getContainer()->getParameter('kernel.root_dir').'/../web';
        }
```
For my distribution, the `$documentRoot` should be : `$this->getContainer()->getParameter('kernel.root_dir').'/../../web'`

I don't want to tell to each dev wich using my distribution to add the --docroot option (or using an alias via composer scripts/make) so I'm looking to the best way to change this.

Solutions :

1- ServerRunCommand and ServerStartCommand should be used as services to allow overriding
2- Add a getDocumentRoot option in Kernel and use the parameter instead of relative path (simpler)
3- Create a symfony/server-bundle with all related server commands as dependency of framework-bundle

What's your opinion?

**Comment by chalasr** [comment]
@pocky Hello,

If you don't want to pass this option each time, here is a quick way to do it:

```php
<?php

namespace AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ServerRunCommand as BaseServerRunCommand;

class ServerRunCommand extends BaseServerRunCommand
{
    protected function configure()
    {
        parent::configure();

        $this->getDefinition()->getOption('docroot')->setDefault('your/custom/docroot');
    }
}
```

Like this, calling `bin/console server:run` use your custom docroot by default.

I may miss something but in my opinion having the `docroot` option should be enough for most use cases, I don't think it is worth making it configurable, AFAIK we never did such for any command in the past.

**Comment by pocky** [comment]
@chalasr Correct! ;)

But if I want to share my AppBundle with you (and your symfony-standard), this change will broke your `server:run`.

**Comment by chalasr** [comment]
> But if I want to share my AppBundle with you (and your symfony-standard), this change will broke your server:run.

Since the need is quite specific to your structure, you could register the command [as a service](https://symfony.com/doc/current/console/commands_as_services.html) and have the command in a place that cannot be published/reused (e.g. in `app/Command` if your structure allows it), outside of any bundle.

**Comment by chalasr** [comment]
@pocky See #21190, it should help here
