### ISSUE TITLE
[Console] Impossible to extend ProgressBar

### ISSUE THREAD

**Issue by a-ast** [symfony/symfony#20427]
Helpers are not final classes, so it is assumed we can extend them.
If, for any chance, you needed to extend `ProgressBar`, it would fail.

This test
```php
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Tests\Fixtures\DummyOutput;

class ProgressBarExtensibilityTest extends PHPUnit_Framework_TestCase
{
    public function testStart()
    {
        $progressBar = new ExtendedProgressBar(new DummyOutput());
        $progressBar->start(10);
    }
}

class ExtendedProgressBar extends ProgressBar
{

}
```
fails with the message

> PHP Fatal error:  Call to private method Symfony\Component\Console\Helper\ProgressBar::getStepWidth() from context 'ProgressBar' 
> in vendor/symfony/symfony/src/Symfony/Component/Console/Helper/ProgressBar.php on line 573

It happens because the private method `getStepWidth` is called in a closure:

```php
'current' => function (ProgressBar $bar) {
      return str_pad($bar->getProgress(), $bar->getStepWidth(), ' ', STR_PAD_LEFT);
},
```
It works only inside `ProgressBar` but `ExtendedProgressBar` has no access to private methods of the parent class.

My proposal is to change a visibility of `ProgressBar::getStepWidth` to `protected`.
All other `ProgressBar` methods that are used in the same context (in `initPlaceholderFormatters`) are public.

(I'd work on PR if there are no objections or other ideas.)

**Comment by a-ast** [comment]
I found a workaround for this issue:

```php
public function testStart()
 {
    $progressBar = new ExtendedProgressBar(new DummyOutput());
    ProgressBar::getPlaceholderFormatterDefinition('current');
    $progressBar->start(10);
}
```

The call of `ProgressBar::getPlaceholderFormatterDefinition` binds `self` to the context of `ProgressBar` class, therefore all methods of `ProgressBar` will be called in the context of this class and calls to private methods will not cause fatal errors.

**Comment by stof** [comment]
hmm, PHP binding closures to the calling class rather than the class in which the closure is defined is a weird behavior. It effectively means that the default closure binding is useless for non-final classes.

**Comment by a-ast** [comment]
> binding closures to the calling class rather than the class in which the closure is defined is a weird behavior
> right fix would be to re-bind the closure explicitly to the right class instead

@stof what do you mean by 're-bind'? `static::$formatters = static::initPlaceholderFormatters();` ?
