### ISSUE TITLE
[Filesystem] LockHandler fallback directory should be configurable

### ISSUE THREAD

**Issue by nkirstein** [symfony/symfony#20423]
Currently, there is no way (in Symfony) to configure the fallback directory for the LockHandler when deploying a third-party Symfony-based app. Unless the developer has hard-coded a specific directory in the constructor calls, the LockHandler will fall back on the system's temporary directory as provided by `sys_get_temp_dir()`.

This can lead to problems in some shared hosting configurations when `sys_get_temp_dir()` doesn't provide a useful value and the corresponding php.ini directive `sys_temp_dir` cannot be configured by the user. That may sound like a fringe scenario but I know of one fairly big European provider that uses the following setup on their shared servers:

- `sys_get_temp_dir()` defaults to `/tmp` because `sys_temp_dir` has no value assigned to it, AND
- PHP is blocked from writing to `/tmp` for security reasons.

Currently, the only way to adapt a third-party Symfony-based app to such a setup is to "hack" the source code, e.g. by replacing `sys_get_temp_dir()` with some absolute path or by setting the TMP, TEMP and TMPDIR environment variables at runtime. It would be much easier if a fallback directory for the LockHandler could be specified centrally in a Symfony configuration file. The LockHandler could then use the following fallback sequence:
1. Use any directory passed in the constructor call.
2. Otherwise, use any directory specified in the configuration file.
3. Otherwise, use `sys_get_temp_dir()` to get the system's default temporary directory.

To be clear: I'm not expecting Symfony to anticipate every weird server setup. What I'm saying is that, since the usability of `sys_get_temp_dir()` depends on the server setup, and precisely because Symfony cannot anticipate all possible server setups, it should provide a way of configuring a fallback directory in case `sys_get_temp_dir()` fails.

**Comment by xabbuh** [comment]
How would that be different from passing a path to the constructor as you are already able to do?

**Comment by nkirstein** [comment]
@xabbuh Well, for a developer it may not make a difference. But here I'm speaking from the perspective of someone who is **deploying a third-party app** on a webserver. In this situation, I cannot pass a path to the constructor because I'm not the developer of the app and I don't want to hack the source code. If the developer didn't specify an **app-specific** directory in the constructor call, then I have no way of telling the LockHandler to use a certain **server-specific** directory if `sys_get_temp_dir()` fails to deliver a useable path. So it would be great to have a place in the configuration files where I could specify a **server-specific** path. Does that answer your question?

**Comment by javiereguiluz** [comment]
What about checking if sys_get_temp_dir() is writable and otherwise, falling back to the cache dir?

```php
// pseudo-code; it won't work!
$lockPath = $lockPath ?: is_writable(sys_get_temp_dir()) ? sys_get_temp_dir() : $this->getParameter('kernel.cache_dir');
```

**Comment by nicolas-grekas** [comment]
ping @lyrixx

**Comment by lyrixx** [comment]
Hello.

I see at lease two solution here:

1. Patch (with a PR) the third party code to use the the `%kernel.cache_dir%` folder
2. Add a static method / property to configure the fallback.

**Comment by nicolas-grekas** [comment]
Should we do something in LockableTrait?

**Comment by lyrixx** [comment]
Actually, there is a much more simpler solution. `sys_get_temp_dir()` already read the `TMPDIR` environment value. So you can simple add the following line `putenv('TMPDIR=/foobar');` in your front controller.

**Comment by javiereguiluz** [comment]
Let's close this as "fixed" thanks to the tip provided by @lyrixx (which by the way, it's being added to the Symfony Docs too. See https://github.com/symfony/symfony-docs/pull/7150)

**Comment by nkirstein** [comment]
@javiereguiluz @nicolas-grekas @lyrixx Sorry for being a pain in the a.. but I don't see how this solves the issue that I was raising. I was suggesting that in a situation where you're deploying a third-party Symfony-based app on a shared webserver, it would be useful to have a way of configuring a temp directory without having to modify the source code of the third-party app. The solution offered by lyrix is to add `putenv('TMPDIR=/foobar');` in the front controller, which effectively amounts to modifying the source code. Or am I missing something?

**Comment by javiereguiluz** [comment]
@nkirstein you are right ... but @lyrixx proposal to `putenv()` in the front controller was just an example. You can define the `TMPDIR` environment variable using the deployment script, the web server, etc.

**Comment by nkirstein** [comment]
@javiereguiluz True, but my point is that none of these options may be available or feasible. Please remember: I'm not speaking from a developer's perspective. I'm taking the perspective of someone who is running a website with, say, Contao 4 on a shared hosting webserver. (I'm using Contao 4 as an example because it actually uses the LockHandler). Let's say the webserver is running Apache and PHP is running as a module, and the only thing I can do in terms of server configuration is use .htaccess files. I'm not using a deployment script, maybe I don't even have SSH access. That's a realistic scenario on some basic shared webhosting platforms. 

So what can I do? I can add `putenv('TMPDIR=/path');` as @lyrixx suggested, but that would mean modifying the Contao code. I can put `SetEnv TMPDIR /path` in my .htaccess file, but for some weird reason this only works if I _also_ add `putenv('TMPDIR='.getenv('TMPDIR'));` in the PHP code, so again I need to modify the source code. 

Let me argue once more for my original suggestion that the temporary directory should be configurable. I think this case is similar to that of, say, the database host name. When writing a database library such as Doctrine, you want to make the database host name user-configurable because there is no reliable way of determining the host name from within PHP unless you've already set up a database connection. In particular, you would't want to use something like `ini_get('mysqli.default_host')` to determine the database host name because that may not deliver a useful value or any value at all. Now, in the case of the temporary directory, you are using `sys_get_temp_dir();` which is supposed to give you the default temporary directory. The problem is that this function is unreliable because the usefulness of its return value depends on the server configuration. So I think that, just as the database host name should be configurable, so should the temporary directory.

If this still doesn't convice you I promise I'll shut up ;-)

**Comment by javiereguiluz** [comment]
The solution I was thinking for your case was putting this in your `.htaccess` file:

```apache
SetEnv TMPDIR /path
```

You say that it doesn't work ... maybe that's an Apache config error?

**Comment by nkirstein** [comment]
Yes, that's really strange. It only works with that extra bit of PHP code. There is a discussion about this here: http://stackoverflow.com/questions/13186069/ but no clear evidence as to whether it's an Apache or a PHP issue. 

Another solution would be to set `sys_temp_dir=/path` in the php.ini or `php_admin_value sys_temp_dir "/path"` in the Apache configuration. But that's not available in my scenario, either. 

Anyways, I know how to work around my particular problem but I was trying to argue on a more general level.
