### ISSUE TITLE
[DI] ENV parameters at runtime with PHP 7 strict types not working properly

### ISSUE THREAD

**Issue by sandrokeil** [symfony/symfony#20434]
I'm just playing around with the Symfony 3.2 Beta and [Runtime Environment Variables](https://github.com/symfony/symfony/pull/19681).

There are two problems:

1. It's not data type aware
1. It's not working if environment parameter is a service name
1. No `null` value support

## 1. It's not data type aware
All environment variables are strings e.g. if you use nginx + php-fpm. So we need a type cast on reading the environment variable. For example `%env('MY_INTEGER', 'integer')%` or `%env('MY_BOOLEAN', 'bool')%` etc. Otherwise it makes no sense, because you get errors like `Invalid type for path "swiftmailer.mailers.default.disable_delivery". Expected boolean, but got string`.

How can we solve this?

##  2. It's not working if environment parameter is a service name
If I put the `mailer_transport` parameter to an environment variable I get the error `You have requested a non-existent service "%env(MAILER_TRANSPORT)%"`. This env variable has the value `smtp`. I guess @fabpot mentioned this [here](https://github.com/symfony/symfony/pull/19681#pullrequestreview-64679).

Would be great if we can resolve this too. Any ideas?

## 3. No `null` value support
It should be possible to allow default `null` values or to allow not defined environment variables which have then as default value `null`. The `mailer_transport` parameter [can be null](https://symfony.com/doc/2.7/reference/configuration/swiftmailer.html#transport).

With `$container->setParameter('env(MY_DEFAULT_NULL)', null);` I get the error `The default value of an env() parameter must be scalar, but "NULL" given`. And if this environment variable is not defined, I get the error `Environment variable not found: "MY_DEFAULT_NULL"`.

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Flagging as feature request, because the current behavior has its validity scope, and this description is about extending this validity scope.

Note that I'm not sure there is anything to do in Symfony core: the "fix" might very well be in DI extensions, when they do too much things at compile time, vs runtime. See https://github.com/symfony/symfony/issues/19843 for an example of enhanced DI extension.

**Comment by sandrokeil** [comment]
Alright, I added another problem `No `null` value support` in the description.

**Comment by nicolas-grekas** [comment]
> null values

already supported as default value:
```
parameters:
    env(FOO): ~
```

**Comment by fabpot** [comment]
That's a problem. There is a discrepancy between what you can do with a real env value (only strings) and what you can do here with a parameter.

**Comment by fabpot** [comment]
So, at least for 3.2, let's throw an exception with the env var value is defined as a parameter and the value is not null or a string.

This can be then revisited in 3.3 if we start supporting conversions from strings to other types.

**Comment by sandrokeil** [comment]
Thanks for clarification.

> No null value support
already supported as default value:

I use a PHP configuration file and this doesn't work. I got an `~` instead of a `null` value for this parameter. @nicolas-grekas 

```php
$container->setParameter('MY_NOT_DEFINED', '%env(MY_NOT_DEFINED)%');
$container->setParameter('env(MY_NOT_DEFINED)', '~');
```

**Comment by nicolas-grekas** [comment]
Did you try `$container->setParameter('env(MY_NOT_DEFINED)', null);`? The previous notation is yaml only.

**Comment by sandrokeil** [comment]
@nicolas-grekas Yes, see 3. in the description.

> With `$container->setParameter('env(MY_DEFAULT_NULL)', null);` I get the error `The default value of an env() parameter must be scalar, but "NULL" given`. And if this environment variable is not defined, I get the error `Environment variable not found: "MY_DEFAULT_NULL"`.

**Comment by nicolas-grekas** [comment]
Fixed
