### ISSUE TITLE
[Translation] Different caching mechanism for translations

### ISSUE THREAD

**Issue by koemeet** [symfony/symfony#20430]
From what I can tell the translation component is kind of hard coupled to store its cache in the filesystem. It would be nice if it would be possible to use for example Redis to store the cached translation catalogues. 

My use case for this is that I am storing my translations inside a database so cache invalidation becomes an issue when I have the application running on multiple servers. I would have to clear the specific folders on every server when a change is made in the database.

**Comment by aitboudad** [comment]
Hi, 
I did many attempts to solve this issue, the last ones is https://github.com/symfony/symfony/pull/17563
but I think it need to be simplified.
well I'll try again to do some clean up in the next few days I hope it will be accepted soon :)
Thanks

**Comment by steffenbrem** [comment]
@aitboudad Looks good, much better separation. With your changes it would be easy to implement a Redis cache, thanks for your work on this! 👍

**Comment by LouTerrailloune** [comment]
I also store my translations in database. I'm using a request listener that replace the translations in the translator catalog with the ones from the database. On cache hit: just replace translations, on cache miss: load from database ans then save into cache,  on database update: clear the cache. (using synfony/cache in my case).

**Comment by lunetics** [comment]
@LouTerrailloune mind sharing that in a gist?

**Comment by LouTerrailloune** [comment]
Here is the gist for the listener : https://gist.github.com/LouTerrailloune/c283857bcb2f53985e75c3738432f1ae

**Comment by Warxcell** [comment]
@LouTerrailloune Is that working when you access translations from commands?

**Comment by LouTerrailloune** [comment]
@Warxcell I think it's not working as-is but you should be able to load the translation and inject them in the translator with a console event (or manualy at the start of your command). dont(forget to set the locale.

**Comment by nicolas-grekas** [comment]
I'm :-1: for adding a generic caching layer: the performance is critical here and having to load potentially huge catalogs from a remote backend is going to be a perf killer. This is especially true when considering the current way: dumping catalogs to the filesystem means leveraging opcache. There is no faster "backend" in PHP.

BUT, I agree there is an issue with invalidating this cache. This is what we should work on instead IMHO. #27600 is basically about that.

If we agree, let's close here.

**Comment by deguif** [comment]
This can probably be closed, following @nicolas-grekas last comment as https://github.com/symfony/symfony/pull/28937 was merged.
