### ISSUE TITLE
FormConfigBuilder changing \Form\Extension\Core\Type\Password Type to \Form\Extension\Core\Type\PasswordTypeArray and throwing Exception on 'PasswordTypeArray'

### ISSUE THREAD

**Issue by eggmatters** [symfony/symfony#20438]
While Creating an Abstract type, I am attempting to create a Password field input box on a form:

```
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CBMSUserType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add( 'email', Type\EmailType::class, [
                'label' => 'email / username',
                'attr'  => ['class' => 'org_form_50']
            ])
            ->add('password', Type\PasswordType::class. [
                'label' => 'password',
                 'attr' => ['class' => 'org_form_50']
                ])

    }
. . .
}
```
This corresponds with an 'User' entity defined supporting the 'email'  and 'pasword' properties defined as strings.

The controller sets the form accordingly:
```
$user = new User();
$form = $this->createForm(UserType::class, $user, array());
return $this->render(':MyApp/users:user_create.html.twig', array(
            'title' => 'Create System User',
            'form' => $form->createView()
));
```
The defined view to rendered the form is a twig template:
```
{% block body %}

    {{ form_start(form) }}
    {{ form_row(form.email) }}
    {{ form_row(form.password) }}
    {{ form_end(form) }}
{% endblock %} 
```
EXPECTED:

The form renders two text input fields, the password field is HTML input type 'password'.

ACTUAL:

The following exception is thrown:

```
Could not load type "Symfony\Component\Form\Extension\Core\Type\PasswordTypeArray" 
CRITICAL - Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "Symfony\Component\Form\Extension\Core\Type\PasswordTypeArray"" at /tmp/admin/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php line 87 
```
The FQCN passed into FormRegistry is "PasswordTypeArray". But there is no 'PasswordTypeArray' defined by the application. The change occurs somewhere deep within the library code and I have not yet been able to isolate it. 

Conclusion: 
I am requesting html to be generated including an input element with a 'password' type which will associate with the corresponding property of my User entity. Somewhere along the line, the type specification to do this is being transformed into a non-existent type.

**Comment by HeahDude** [comment]
You should follow the trace to see where the word `Array` is suffixed to the fqcn of the form type. As far as I can see you're use case is fine, and the issue does not look related to symfony.

**Comment by eggmatters** [comment]
Yeah, I traced it as far as I could. I am not seeing where Array is appended to anything. (it just appears in the signatures in SymfonyComponent FormRegistry. Still trying to pinpoint it. The entity is declaring a string. I'm still running a few tests to isolate the behavior and will post my findings ASAP.

**Comment by eggmatters** [comment]
UPDATE: Changing the PasswordType field to TextType field throws a similar error: "Could not load type "Symfony\Component\Form\Extension\Core\Type\TextTypeArray" 

Other forms (with TextType) are rendering. This is leading me to believe that this is not a bug

**Comment by eggmatters** [comment]
CONCLUSION:
We can now close this issue. Looking _carefully_ at the code I supplied, we easily see the culprit: 
```->add('password', Type\PasswordType::class. [
```
As much as it pains me to point it out, Please notice the "." operator separating the arguments between the expected type and the options parameters. The  argument passed in for the type hit was:
```
'Form\Extension\Core\TypeType\PasswordType' . Array()
```
which explains the issue and why I couldn't see it being "assigned" anywhere in the stack trace. 

Apologies for the fire drill.
