### ISSUE TITLE
[TwigBundle] Non-existing method call

### ISSUE THREAD

**Issue by ShinDarth** [symfony/symfony#20435]
In:  https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php#L137

there is this line:

``$loader->getSource($template);``

both my IDE and phpunit complain that the method ``getSource()`` does not exist, which is causing me troubles when writing unit tests.

Also I don't understand the purpose of that call, it is a `get` method so it is supposed to return something, but we are never using the returned value.

I guess lines 136-141 can just be removed, in that case I can open a PR.

**Comment by stof** [comment]
Are you using the dev version of Twig 2.x ? This could be the issue. Twig 2.x is a fast moving target these days, with lots of APIs being deprecated in 1.x and removed in the dev version of 2.x (Fabien dedicated time to Twig to move towards a 2.0 release). Symfony code may not be fully updated yet for all these changes (especially if you use a stable release of Symfony rather than the dev version as well).
I suggest you to stick to Twig 1.x for now.

**Comment by ShinDarth** [comment]
I'm using Symfony dev version

**Comment by javiereguiluz** [comment]
@ShinDarth can you please show the output of this command? Thanks!

```
$ composer show twig/twig
```

**Comment by ShinDarth** [comment]
@javiereguiluz sure:

```
name     : twig/twig
descrip. : Twig, the flexible, fast, and secure template language for PHP
keywords : templating
versions : * 2.x-dev
type     : library
license  : BSD 3-clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/twigphp/Twig.git 50c8024766a97c39d7c28a6ab3a34be43f2a7493
dist     : [zip] https://api.github.com/repos/twigphp/Twig/zipball/50c8024766a97c39d7c28a6ab3a34be43f2a7493 50c8024766a97c39d7c28a6ab3a34be43f2a7493
names    : twig/twig

autoload
psr-0
Twig_ => lib/

requires
php >=5.5
symfony/polyfill-mbstring ~1.0

requires (dev)
symfony/debug ~2.7
symfony/phpunit-bridge ~2.7
```

**Comment by xabbuh** [comment]
@ShinDarth Can you please check if #20440 solves the issue for you?

**Comment by ShinDarth** [comment]
@xabbuh at the moment I can't, I can check tomorrow. Anyway thanks for that PR, I left a comment btw.

**Comment by ShinDarth** [comment]
@xabbuh I've just tested and it works, thanks again.

**Comment by xabbuh** [comment]
@ShinDarth Thank you for reporting the issue initially and for providing quick feedback!
