### ISSUE TITLE
ChoiceType: 0.0 floats as choice does not get initial selected

### ISSUE THREAD

**Issue by hvanoch** [symfony/symfony#20443]
I have a form with a ChoiceType like this:
```php
       $builder
            ->add('vatRate', ChoiceType::class, [
                'expanded' => true,
                'choices' => [
                    '0%' => 0.0,
                    '6%' => 0.06,
                    '21%' => 0.21,
                ],
                'choices_as_values' => true
            ]);
```

My object passed to the form has 0.0 (float) as initial value, but the first item of the radio buttons does not get selected/checked. I tried several configurations but nothing seems to work.
Is this a bug with the formbuilder not being able to handle floats correctly?

I am on symfony 2.8.13

**Comment by HeahDude** [comment]
Hi @hvanoch could try 2.8-@dev to see if https://github.com/symfony/symfony/pull/20378 solve your issue?

**Comment by hvanoch** [comment]
I looks like it was my own fault.
I mapped the property "vatRate" as decimal in doctrine ORM. But type  "decimal" always returns a string or null, not a float. Thence my confusion.

I did take a look at #20378 but I noticed something weird with certain floats.
0.000001 for instance show "1.0E-6" as value in the html. Is that the intention?

**Comment by xabbuh** [comment]
Closing here as it turns out that the described behaviour was no bug but a misconfiguration.
