### ISSUE TITLE
Serializer Dependency issue with Symfony 2.8

### ISSUE THREAD

**Issue by jayesbe** [symfony/symfony#20457]
Referencing a pull request at https://github.com/symfony/serializer/pull/9

The symfony/serializer defines the symfony/property-access and symfony/http-foundation dependencies to allow 2.8 or 3.0 however the symfony/property-info dependency only allows 3.1.

Setting the property-info dependency to allow 2.8 like the others.

**Comment by stof** [comment]
this is wrong. The 3.1 version of the serializer needs features added in property-info 3.1. It is **not** compatible with 2.8 or 3.0 anymore

**Comment by jayesbe** [comment]
Doesn't that mean that allowing the other dependencies to have 2.8 as an option needs to be updated ?

**Comment by jayesbe** [comment]
Closing this. The v3.1 of property-info installs just fine on sf 2.8 and it was another issue altogether.
