### ISSUE TITLE
.vtt format validation & storage error

### ISSUE THREAD

**Issue by khaninejad** [symfony/symfony#20454]
> I want to upload .vtt format using Laravel Storage facade.
> with validation, I can't do this because Laravel couldn't recognize .vtt format.
> without validation, it is uploaded but extension changed to .txt
> https://www.w3.org/TR/webvtt1/
Laravel users mentioned its functionality came from Symfony
http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/File/UploadedFile.html
https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php
So, I think you need to add VTT to your Mime Guesser.

**Comment by javiereguiluz** [comment]
@khaninejad could you please provide more information about the `.vtt` extension?  I can't find it in [the official list of MIME types and extensions](http://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by khaninejad** [comment]
Sure.
*WebVTT* is a format for displaying timed text tracks (such as subtitles or
captions) using the <track>
<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track> element.
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

**Comment by javiereguiluz** [comment]
We're trying to fix this in #21329. Let's wait and see if they accept it!
