### ISSUE TITLE
[DX][DependencyInjection] Unable to trace a circular reference if the service is private

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#20456]
If you introduce a circular reference in your container and that one service in the chain is private, then the exception don't give you the full path of the loop.

e.g. if all service are public you have this path:
```
Circular reference detected for service "security.access.decision_manager", path: "cache_warmer -> twig -> security.authorization_checker -> security.access.decision_manager -> the.bad.service".
```

But if the service `the.bad.service` is private, the exception is:
```
Circular reference detected for service "security.access.decision_manager", path: "security.access.decision_manager".
```

And it's a real pain to find where is the problem.

**Comment by iltar** [comment]
@nykopol can you check this again but now by injecting the private service twice? My guess is that it cannot determine the service id because it's optimized away (e.g. inlined).

**Comment by nykopol** [comment]
@iltar it's confirmed. If the private service is injected twice, the exception contain the full path.

**Comment by xabbuh** [comment]
@nykopol Can you provide an example project where this is happening? Circular references should be detected by the `CheckCircularReferencesPass` which is run before the `InlineServiceDefinitionsPass`.

**Comment by nykopol** [comment]
@xabbuh Sorry but I'm not able to reproduce this anymore... For what I see the only things that may have interact was that my offending service was altered from a compiler pass.

As I'm not able to reproduce this you, i think that you can close the issue.
