### ISSUE TITLE
[Framework] Console shows commands for disabled parts

### ISSUE THREAD

**Issue by mvar** [symfony/symfony#20463]
I'm planning to use Symfony for command line only application. Because I don't need any of WEB related stuff, I keep `framework` configuration as simple as possible:

```yml
framework:
    secret:          "%secret%"
    default_locale:  "%locale%"
```

I have noticed that this does not affect commands listed in command list:

```bash
$ bin/console 
Symfony version 3.1.6 - app/dev/debug
...
Available commands:
  help                                    Displays help for a command
  list                                    Lists commands
 assets
  assets:install                          Installs bundles web assets under a public web directory
 ...
 server
  server:run                              Runs PHP built-in web server
  server:start                            Starts PHP built-in web server in the background
  server:status                           Outputs the status of the built-in web server for the given address
  server:stop                             Stops PHP's built-in web server that was started with the server:start command
 translation
  translation:update                      Updates the translation file
```

As you can see, `assets` and `translation` commands are listed even thought they are not enabled in configuration. None of these are working because of missing dependencies. In my case `server` commands are not working too because I don't have `web/` directory.

I know this is not a bug, but one loose end which could be solved in the future :)

Waiting for comments.

**Comment by fabpot** [comment]
A great cleanup has been made in 3.2 (current master). So, 3.2 should be more "accurate" in terms of commands you can indeed run without adding more dependencies (no more translation commands is the translation component is not installed). Note that the assets:install command is not related to the assets configuration though.
