### ISSUE TITLE
Show used repository method for each doctrine web profiler query

### ISSUE THREAD

**Issue by marfillaster** [symfony/symfony#20468]
This is more of a DX especially in a large codebase to quickly locate a query used in a particular page.

**Comment by iltar** [comment]
This is going to be hard to track though. You'd have to decorate the repositories by allowing the EntityManager to do this and even this only catches only the cases where you use the EM to get a repository.

**Comment by javiereguiluz** [comment]
I agree with @iltar: at first sight this looks extremely difficult to implement. If in your application it's important to track some specific queries, you could use the StopWatch component, the Log service, etc.

**Comment by kix** [comment]
A hacky solution, but looks like it should work: you can wrap the `\Doctrine\DBAL\Connection` with a decorator that would get the `debug_backtrace()`, process it somehow and find the topmost caller that implements `\Doctrine\Common\Persistence\ObjectRepository`.

**Comment by stof** [comment]
Note that adding usage of ``debug_backtrace()`` in the DBAL DebugStack SQLLogger (which is  used by the profiler) has been suggested in the past, and rejected.

thus, it could be harder than that, because the execution might not happen inside the code of a repository

**Comment by javiereguiluz** [comment]
@marfillaster I'm closing this as "won't fix" because the implementation looks too complex, but I hope you keep suggesting ideas to improve Symfony in the future. Thanks!
