### ISSUE TITLE
form in a controller with a service

### ISSUE THREAD

**Issue by EmyJ** [symfony/symfony#20461]
hi, 

I updated a Symfony Project version 2.4 to version 2.8 and try to resolve all deprecations by following this guide : https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md

I have this deprecation:

Passing type instances to FormBuilder::add(), Form::add() or the FormFactory is deprecated since version 2.8 and will not be supported in 3.0. Use the fully-qualified type class name instead.

Due to the following code :

`public function newAction(Request $request)
    {
        $contact    = $this->get('MyBundle.manager.contact')->createOne($this->getUser());
 
        $forms = [4 => "", 3 => "_integration", 2 => "_problem", 1 => "_partnership"];
        $form_views = [];
 
        foreach($forms as $i => $key)
        {
            $form       = $this->createForm($this->get('MyBundle.form.type.contact' . $key), $contact, array(
                'action' => $this->generateUrl('main_contact_submit' . $key),
                'method' => 'POST'
            ));
            $form->handleRequest($request);
 
            $form_views['form_' . $i] = $form->createView();
        }
         
        return $form_views;
    }`

the service used : 
 
    '<services>
        <service id="MyBundle.form.type.contact" class="MyBundle\MainBundle\Form\Type\ContactType">
            <tag name="form.type" />
        </service>
        <service id="MyBundle.form.type.contact_integration" class="MyBundle\MainBundle\Form\Type\ContactIntegrationType">
            <tag name="form.type" />
        </service>
        <service id="MyBundle.form.type.contact_partnership" class="MyBundle\MainBundle\Form\Type\ContactPartnershipType">
            <tag name="form.type" />
        </service>
        <service id="MyBundle.form.type.contact_problem" class="MyBundle\MainBundle\Form\Type\ContactProblemType">
            <tag name="form.type" />
        </service>
    </services>'

a part of the view : 
`<div class="form-container form-1">
        {{ form_start(form_1) }}
            <span class="mandatory">{{ "Fields marked with * are mandatory" | trans }}</span>
 
            <div class="row">
                <div class="large-4 columns">
                    {{ form_row(form_1.lastname) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_1.firstname) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_1.nickname) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_1.email) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_1.subject) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-6 columns">
                    {{ form_row(form_1.complementary.facebook) }}
                </div>
                <div class="large-6 columns">
                    {{ form_row(form_1.complementary.website) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-4 columns">
                    {{ form_row(form_1.complementary.twitter) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_1.complementary.twitch) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_1.complementary.youtube) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_1.message) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-6 columns">
                    {{ form_row(form_1.recaptcha) }}
                </div>
                <div class="large-6 columns">
                    <button class="button small right">{{ "Validate" | trans }}</button>
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns"><br /></div>
            </div>
        {{ form_end(form_1) }}
    </div>
 
    <div class="panel classic-block form-displayer" id="form-2">
        {{ "You used MyBundle to buy a product and are currently encountering a problem" | trans }}
    </div>
 
    <div class="form-container form-2">
        {{ form_start(form_2) }}
            <span class="mandatory">{{ "Fields marked with * are mandatory" | trans }}</span>
 
            <div class="row">
                <div class="large-4 columns">
                    {{ form_row(form_2.lastname) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_2.firstname) }}
                </div>
                <div class="large-4 columns">
                    {{ form_row(form_2.nickname) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_2.email) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_2.subject) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-6 columns">
                    {{ form_row(form_2.complementary.shop) }}
                </div>
                <div class="large-6 columns">
                    {{ form_row(form_2.complementary.date_of_purchase) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-6 columns">
                    {{ form_row(form_2.complementary.order_number) }}
                </div>
                <div class="large-6 columns">
                    {{ form_row(form_2.complementary.invoice_number) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns">
                    {{ form_row(form_2.message) }}
                </div>
            </div>
 
            <div class="row">
                <div class="large-6 columns">
                    {{ form_row(form_2.recaptcha) }}
                </div>
                <div class="large-6 columns">
                    <button class="button small right">{{ "Validate" | trans }}</button>
                </div>
            </div>
 
            <div class="row">
                <div class="large-12 columns"><br /></div>
            </div>
        {{ form_end(form_2) }}
    </div>`

I know it takes the form write like this: $form = $this->createForm(MyType::class);

but there I do not know how.

ps: If there is need to code, I can give in.

thank you in advance

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
