### ISSUE TITLE
[Twig] Make Exception templates easier to customize

### ISSUE THREAD

**Issue by Einenlum** [symfony/symfony#20473]
For now Exception pages contain no blocks. Cf. https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/Resources/views/Exception/exception.html.twig

To override just the image or to change a sentence in the template, you need to copy paste *all* the template, which is unfortunate.

We should add blocks in all these templates.

**Comment by stof** [comment]
The exception.html.twig is used only in debug mode, to display the exception to developer. What is the use case for extending it ?

Btw, blocks would be useful only when define specific templates by status code (or if you replace the ExceptionController itself to use different templates). You cannot overwrite the template while making it extend the original version of this template (as you would actually make it extend your overwriting version too, creating an infinite loop). So I don't see how you would use it.

**Comment by javiereguiluz** [comment]
@Einenlum even if you are right ... the `exception.html.twig` should *never* be extended/modified because it's only used for debug purposes, as explained by @stof. Could you give some more details about the reasons to extend it? Thanks!

**Comment by Einenlum** [comment]
I don't see the link between being not being able to extend a template and debug purposes.
So if it's for debug we should never extend? Where does this idea come from?
The reason could be simple. You want to change the wording, the style of the exception page or the exception image (which was my problem).

Even if it's for debug and so for developers only, does it mean we should never be able to change something in this page? I don't understand the philosophy.

**Comment by xabbuh** [comment]
@Einenlum Of course, you are free to customise the template as you like. But you will have to override the full template if that's something that is so important for you. As this is something that will never be displayed to the user I am clearly 👎 on making this change in core.

**Comment by stof** [comment]
@Einenlum see my previous comment. Even if we add blocks in the core template, this will not help you, as you will be overwriting the template, and so the core template will not be accessible anymore.

**Comment by fabpot** [comment]
Not everything is meant to be extensible (that's true for code and templates). Here, error templates displayed in the debug mode should be considered "private".

The philosophy is that we don't want to make everything extensible (time consuming, complexity added, maintenance is more difficult) also because we have a strong BC policy.

Closing this issue as again those templates are not meant to be an extension point.
