### ISSUE TITLE
form.factory::create Does not bind to data_class

### ISSUE THREAD

**Issue by adetwiler** [symfony/symfony#20485]
I created a form type that includes a default data_class for Contact::class and am not able to get this data class to be bound using the form.factory::create method, but am able to get it working using form.factory::createNamed.

If I do this:

```
$contact = new Contact();
$contactForm = $this->createForm(ContactFormType::class, $contact);
$contactForm->handle($request);
```
^ this causes the form to become invalid with no visible errors.

However, if I do this, it works:
```
$contact = new Contact();
$contactForm = $this->container->get('form.factory')->createNamed(null, ContactFormType::class, $contact);
$contactForm->handleRequest($request);
```

**Comment by HeahDude** [comment]
Hi @adetwiler, what you report is very strange! Can you tell us which version of Symfony you are using?

**Comment by adetwiler** [comment]
Hello @HeahDude, thank you for your reply. I am using version 3.1.6.

**Comment by xabbuh** [comment]
Can you please fork the Symfony Standard Edition and make changes that are necessary to reproduce your issue?

**Comment by adetwiler** [comment]
With Symfony Standard Edition, I was not able to reproduce the issue.

**Comment by HeahDude** [comment]
Are you naming the form in your view? If so the request matcher is not able to map the request data.

**Comment by adetwiler** [comment]
I realized I tested it on dev-master, so I'll get back to you with results from 3.1.6.

@HeahDude I use the fos rest bundle and don't use twig.

**Comment by HeahDude** [comment]
You may need to add `FOSUserBundle` in your demo to be able to reproduce your issue. What you can do in your code is `dump($request->request->all())` and see in your html code if the form is named.

**Comment by adetwiler** [comment]
@HeahDude When I output dump($request->request->all()), the form is not named. I will try adding `FOSUserBundle` in the demo.

**Comment by HeahDude** [comment]
No I meant `FOSRestBundle` sorry I've edited my post ;)

**Comment by adetwiler** [comment]
No worries! I will try out FOSRestBundle in the demo.

**Comment by HeahDude** [comment]
@adetwiler Any news?

**Comment by adetwiler** [comment]
@HeahDude been super busy this weekend. I'll try to get it to it in the next few days.

**Comment by HeahDude** [comment]
ping @adetwiler :)

**Comment by xabbuh** [comment]
I am closing here due to the lack of feedback. If you manage to provide some more details, we can consider to reopen.
