### ISSUE TITLE
[Serializer] Custom SerializerLoader (for custom yaml serialization groups format)

### ISSUE THREAD

**Issue by ZeBigDuck** [symfony/symfony#20488]
Hi all!

Regarding to `FrameworkExtension.php`, all serializerLoaders seems to be hard-defined (see [FrameworkExtesion part concerning serializerLoaders](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1092-L1184))

I'd like to register a custom serializer, which would be a yaml serializer loader handling serialization groups differently than current yaml serializer loader. How may I register it without modifying vendor class FrameworkExtension ?

Thank you

**Comment by theofidry** [comment]
This part just conditionally serializer services. Otherwise, it's like for any other service:

- You can add a new serializer/encoder by registering it as a service tagged with `serializer.normalizer` or `serializer.encoder`. The order may matter so you may have to assign a priority number
- You can completely override one of the service by registering your service with the same service ID

**Comment by ZeBigDuck** [comment]
Thank @theofidry you for your answer,

Anyway here I don't want to override the serializer, but I want to override the way that groups are handled. So this is not about serializer service, and sadly, there is no such service for group handling.

But as you said, maybe I should make a custom serializer that will itself process my custom serialization file and bypass original serialization group handling by symfony. This solution seems to be less clean to me, but I'm not sure I can do otherwise.

FYI, what I'd like to do is to handle serialization groups with an `Entity > Group > Field` tree, like this : https://gist.github.com/anonymous/018a15e74be499d76d4e42024033726c

Which is, regarding to my usage, less messy than the current group system, to make an easy to manage API fields access by profile.

**Comment by theofidry** [comment]
Yes I think the way to go is using your own normalizer, that's how we do it https://github.com/api-platform/core. I'm not very happy of the extension points of the serializer, hence #19330

**Comment by ZeBigDuck** [comment]
Okay thank you for confirming this.

I'll do it this way (btw this is to be used with ApiPlatform too).
I didn't tried to understand in depth how Symfony core works, but it's weird that some classes are hard-coded as strings in FrameworkExtension, maybe container isn't accessible here, but this remains non very flexible...

Thank you @theofidry

**Comment by theofidry** [comment]
>I didn't tried to understand in depth how Symfony core works, but it's weird that some classes are hard-coded as strings in FrameworkExtension, maybe container isn't accessible here, but this remains non very flexible...

There is almost no hard-coded values actually. The hard-coded strings are 1. service ID, 2. tag strings (and for both you want them fix), and then it's some classes because some normalizer are optional, so they can't be registered all the time but only if they are installed.
