### ISSUE TITLE
Random Container class name generation fail

### ISSUE THREAD

**Issue by alexglue** [symfony/symfony#20489]
Kernel class method getName(){} has a schroedinger-bug:
when working directory starts with number, generated class has invalied php name:

pwd (root dir is): 112bgf3892d (like name, generated in teamcity etc)

fix:

```php
        public function getName()
        {
            if (null === $this->name)
            {
                //[-] $this->name = preg_replace('/[^a-zA-Z0-9_]+/', '', basename($this->rootDir));
                //[+] $this->name = 'app' . preg_replace('/[^a-zA-Z0-9_]+/', '', basename($this->rootDir));
            }

            return $this->name;
        }
```

**Comment by dunglas** [comment]
Thank you for reporting this issue @alexglue. As you already created a fix, can you open a Pull Request and add a non-regression test please?
