### ISSUE TITLE
[LDAP] Issue with case-sensitive usernames

### ISSUE THREAD

**Issue by quentinus95** [symfony/symfony#20486]
When authenticating a user using the LDAP security component, username entered by the user is used to build the `User` instance.

In case of a case-insensitive authentication (which is the default behavior : https://stackoverflow.com/questions/29897684/is-ldap-dn-case-insensitive), the final `User` username can be wrong (for instance, `USERNAME` instead of `UserName`).

To avoid this issue, I'm using the `cn` attribute of the `Ldap\Entry` instead, so I'm getting the well-spelled username. To apply a more generic solution, I think we should store the `$uidKey` as an attribute in the `LdapUserProvider` and use it to retrieve the username using the `Entry` (`$entry->getAttribute($this->uidKey)`).

I can create a pull request if you want.

Thx !

**Comment by quentinus95** [comment]
ping @csarrazi ping @lyrixx

**Comment by csarrazi** [comment]
Hi @quentinus95. Actually, this does not work for all cases. Indeed, LDAP structures do not only store users, but may actually contain one or multiple trees representing an organization and its sub-entities, as well as user groups.

The UID key is actually very specific to the security component, and entries should not be aware of that.

**Comment by quentinus95** [comment]
Hi, thanks for your answer.

I'm not sure to really understand your explanation. Do you have an example where the `$uidKey` given to the `LdapUserProvider` is not describing an attribute of the searched user ?

Maybe I'm wrong but I guess that the uidKey will be the field describing the user's username (and you've set the default value for the filter to `({uid_key}={username})`).

My idea is only to change code in the `loadUserByUsername` to return something like `return $this->loadUser($entry[0]->getAttribute($this->uidKey), $entries[0]);` (the `uidKey` would be added as an attribute of the `LdapUserProvider`). Of course, entries should not be aware of the UID key (but my first message was maybe a bit confusing).

**Comment by csarrazi** [comment]
Sorry if that was not clear on my side. What I mean is that everything in LDAP is represented as the same type of object: an `Entry`. Basically, you can compare an `Entry` to a vertex in a graph, or a node in a tree.

When reading your answer, I actually thought you were suggesting to add a $uidKey in the `Entry`, and not the `LdapUserProvider`, which surprised me.

There's nothing wrong about changing the code in the user provider. We need to check whether this has an impact on other things, though.

**Comment by quentinus95** [comment]
Yes, it would not make any sense to add it to the `Entry` :smile: 

I will open a PR soon.

Thanks !

**Comment by quentinus95** [comment]
I've just created the PR.
