### ISSUE TITLE
strange behavior using is_granted possible bug

### ISSUE THREAD

**Issue by lazaro3487** [symfony/symfony#20494]
I have a strange behavior using the is_granted twig utility. 

In the is_granted function I pass some roles for showing a meu in the app, the problem is:

If the user has the role ROLE_MANAGE_COMPANY_CONFIG the block is rendered but when the user does not has the first role passed to the function the block is never rendered. This only occurs when the user does not have the first role defined in the funtion.
If the user has the first ROLE asigned, but does not has any other it works as expected, for this reason i think this is a bug. Any help is apreciated.

{% block menu_configuration %}

    {% if is_granted('ROLE_MANAGE_COMPANY_CONFIG', 'ROLE_MANAGE_ENV_VARS', 'ROLE_SMTP_MAILER_CONFIG') %}
        {{ parent() }}
        {# ADD MORE ELEMENTS HERE #}

    {% endif %}
{% endblock %}

**Comment by HeahDude** [comment]
Hi @lazaro3487, you should pass an array with all the roles as first argument, otherwise you're messing with the signature of the function (ref https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php#L32).

Try:
```twig
{% if id_granted(['ROLE_MANAGE_COMPANY_CONFIG', 'ROLE_MANAGE_ENV_VARS', 'ROLE_SMTP_MAILER_CONFIG']) %}
```

**Comment by lazaro3487** [comment]
Thank you very much for the answer, sorry my mistake.
