### ISSUE TITLE
Generating CRUD from Entities outside Bundles

### ISSUE THREAD

**Issue by ShinDarth** [symfony/symfony#20515]
I know that keeping entities outside bundles is not considered a good practice, but still there are few rare cases when we might face such a situation.

It would be nice to have the possibility of manually specifying the path of the entity and the target bundle for the generated CRUD.

This should give an idea about the possible solution to this:

http://stackoverflow.com/questions/31689469/doctrinegeneratecrud-for-entites-outside-a-bundle

**Comment by javiereguiluz** [comment]
@ShinDarth you are right. This is in fact an issue of the SensioGeneratorBundle, which is the one in charge of generating those CRUD entities. We already have a reported issue about this in that bundle's repository: https://github.com/sensiolabs/SensioGeneratorBundle/issues/335  Therefore, I'm closing this issue as a duplicate.
