### ISSUE TITLE
Process component start method doesn't wait for the process to be actually spawned

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#20513]
Hello,

We just spent days trying to solve this issue, it might be a bug, or a lack of context inside the documentation: 

We're trying to launch a command using the `Process` component taking benefit of the asyncronuousity of the `start()` method.

**Problem was, the command was not started**. Turns out to be that the **`Process` didn't had enough time to spawn** and the controller returned a response so the Process component never had the change to spawn the process to run the command.

Example

```php
public function myAction() 
{
    $process = new Process('../bin/console my:super-heavy-command');
    $process->start();

    // Returning a response too soon, the process isn't started yet :(
    return new JsonResponse(['status' => 'launched']);
}
```

Out of despair, we added a `sleep(2);` right after the `$process->start()` method. And it fixed it. The command now was correctly launched.

Either this is a bug and `$process->start()` **needs** to wait that the process is correctly spawned before returning anything **OR** you might need, inside the doc, to specify that when using async `Process` to make sure that the process is running before doing anything else (like returning a `Response`).

```php
public function myAction() 
{
    $process = new Process('../bin/console my:super-heavy-command');
    $process->start();

    while (!$process->isRunning()) {
        // we actually wait for the `Process` component to spawn the process
        sleep(1);
    }

    return new JsonResponse(['status' => 'launched']);
}
```

Environment: 
Debian 8
PHP 7.0.13 (php-fpm)
Symfony v3.1.6

**Comment by tristanbes** [comment]
PS: If i'm using the async process, inside my controller I **don't want** to wait for the command to finish using `isRunning()` method. It kills the benefit of the asynchronous feature.

**Comment by tristanbes** [comment]
Actually,

this comment basically explains that this behaviour is not a bug : https://github.com/symfony/symfony/issues/20445#issuecomment-259894126

IMO it should be added in the doc.

For now, i'll use a sh script, so the wrapper only (and not the command) gets killed like @stof said there: https://github.com/symfony/symfony/issues/20445#issuecomment-259927285

**Comment by stof** [comment]
@tristanbes on some OS (OSX and Windows at least), killing a process does kill the child processes. So your case would still kill the command.

What you should do is run it in sync mode, but on kernel.terminate (and ensure that you deploy using PHP-FPM so that kernel.terminate can run after sending the response).

**Comment by nicolas-grekas** [comment]
I don't know how we could wait for the process to be actually spawned. Yet, as stof said, zombie processes (ie processes without parent) are not supported because they are not portable and thus unreliable. Instead, you should do background processes, which means managing them from the parent, and be sure that children process have finished before exiting the parent. This is the only stable way.

**Comment by tristanbes** [comment]
Ok I understand. @nicolas-grekas imo this should be added in the documentation because this will lead to other misunderstanding

Something like
"Running an asynchronous process is not the same than running a processing surviving yourselves."
"You process **will** be killed as soon as the cycle of request/response is finished"

And maybe add a hint like @stof said that only works with php-fpm.

Would you accept such PR in the documentation if I add this ?

**Comment by nicolas-grekas** [comment]
Sure we would accept such a PR!

**Comment by javiereguiluz** [comment]
I've created https://github.com/symfony/symfony-docs/issues/7151 to not forget about improving this doc. Therefore, I'm closing this issue as "fixed". Thanks!

**Comment by EnchanterIO** [comment]
In theory u can do something like this, not sure if it actually works in production but could be:

```
    /**
     * @inheritdoc
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $jobs = $this->legacyJobs->getAllPending(DoctrinePublishJobs::TYPE_ACCOUNT_PUBLISH);

        /** @var Process[] $processes */
        $processes = [];

        foreach ($jobs as $job) {
            $this->legacyJobs->markAsInProgress($job);

            $process = new Process(
                sprintf(
                    '%s bin/console.php %s --%s=%d',
                    (new PhpExecutableFinder())->find(),
                    StartChunkingCommand::COMMAND_NAME,
                    StartChunkingCommand::PARAM_JOB,
                    $job->getId()
                )
            );
            $process->start();

            $processes[] = $process;
        }

        foreach ($processes as $process) {
            while ($process->isRunning()) {
                // waiting for process to finish
            }

            $output->writeln($process->getOutput());
        }
    } 
```
