### ISSUE TITLE
[Security] The TokenBasedRememberMeServices does not call eraseCredentials, so the cookie will always mismatch

### ISSUE THREAD

**Issue by lunetics** [symfony/symfony#20510]
Tested with Symfony 3.2-BETA1

Since the RememberMeTokenService doesn't call the AuthenticatenManager, the User gets loaded without a call to eraseCredentials(). Since the remember me token was set with erased credentials, the cookie hash always mismatches:

Reproduce:
Use a User with an eraseCredentials method.

1: Authenticate as user with rememberme settings
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L95

2: close browser and reopen url
In https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/RememberMe/TokenBasedRememberMeServices.php#L56 the hash from the code (without password) is checked against a new generated hash (with password), this fails now. 
Adding a ```$user->eraseCredentials()``` above seems to fix the bug.

Not sure if the actual eraseCredentials should go into https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php since it's called after the "mismatch"

Maybe the https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php is also affected, there's also no eraseCredentials() call

**Comment by rahulsharma20** [comment]
I am having the same issue. The remember me cookie is always mismatching. Have you found a solution for this?

**Comment by xabbuh** [comment]
@rahulsharma20 Are you able to provide a small example project that makes it possible to reproduce your issue?

**Comment by rahulsharma20** [comment]
Okay. Give me some time. I'll send you the same.

**Comment by rahulsharma20** [comment]
Okay, I have been able to regenerate the behaviour in a simple project.
I have implemented the remember me functionality but if I remove the PHPSESSID cookie from my browser, the user is logged out.

Here are the logs -
`[2017-08-23 11:47:03] security.DEBUG: Remember-me cookie detected. [] []
[2017-08-23 11:47:03] security.DEBUG: Remember-Me authentication failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException(code: 0): The cookie's hash is invalid. at /Users/rahulsharma/Public/login_project/vendor/symfony/symfony/src/Symfony/Component/Security/Http/RememberMe/TokenBasedRememberMeServices.php:58)"} []
[2017-08-23 11:47:03] security.DEBUG: Clearing remember-me cookie. {"name":"REMEMBERME"} []
[2017-08-23 11:47:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []`

Here's the project - https://github.com/rahulsharma20/SymfonyRememberMe
Please take a look and let me know.

**Comment by xabbuh** [comment]
Thanks for the reproducer. I took a look at the code and now understand what's going wrong. Please take a look at the API docs of the `getPassword()` and `clearCredentials()` methods:

```php
interface UserInterface
{
    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword();

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials();

    // ...
}
```

Now, there is something going wrong in your code. Either, `getPassword()` can return the plaintext password which would violate the contract of the `getPassword()` method which requires us to return the hashed password or `eraseCredentials()` does erase a non-plaintext password. Either way, this is something that needs to be fixed in your code.

Thus I am closing here as this is not a bug in Symfony.
