### ISSUE TITLE
Deprecation of UserProviderInterface in favor of UserLoaderInterface

### ISSUE THREAD

**Issue by KatharinaSt** [symfony/symfony#20514]
While removing all the deprecations of Symfony 2.8 and lower I get the following notice:

> Implementing loadUserByUsername from Symfony\Component\Security\Core\User\UserProviderInterface is deprecated since version 2.8 and will be removed in 3.0. Implement the Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface instead.

This should be mentioned in the upgrade guide.

**Comment by stof** [comment]
Btw, we should improve the message, because what is deprecated is implementing UserProviderInterface *on the Doctrine entity repository* when using the entity user provider. Implementing UserProviderInterface itself is not deprecated for other usages.

**Comment by chalasr** [comment]
See #20540
