### ISSUE TITLE
Can't create a child form type of the SubmitType

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony#20528]
In my HTML I want to create a button which has HTML as a label (button text) because I want to use the `material-icons`. The problem is, that the `SubmitType` doesn't transform the HTML to HTML but just prints it onto the button, so I wanted to create a custom form type which inherits from the `SubmitType` and renders the HTML. So I created a new `FormType`

```
<?php
namespace Acme\FrontendBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * Class HtmlSubmitType
 *
 * This form type is used for submit buttons which need HTML for the data (e.g. label). The html rendering is defined
 * in the fields.html.twig file
 *
 * @category Form Type
 * @package  Acme\FrontendBundle\Form\Type
 * @link     http://www.example.com
 * @author   Theo Tzaferis <email@example.com>
 */
class HtmlSubmitType extends AbstractType
{
    /**
     * @inheritdoc
     */
    public function getParent()
    {
        return SubmitType::class;
    }
}
```

However, when using this form field in a `FormType` which has this as the default data_class ` 'data_class' => ResolvedVendor::class` and adding it

`->add(sprintf('quote_%s', $vendor->getToken()), HtmlSubmitType::class)`

I'm always getting the error 

> Neither the property "quote_25v9nt1puvms" nor one of the methods "getQuote25v9nt1puvms()", "quote25v9nt1puvms()", "isQuote25v9nt1puvms()", "hasQuote25v9nt1puvms()", "__get()" exist and have public access in class "Acme\FrontendBundle\Model\Cart\ResolvedVendor".

I don't really understand it, since the documentation says 

>Here, the return value of the getParent function indicates that you're extending the ChoiceType field. This means that, by default, you inherit all of the logic and rendering of that field type

and also it's a submit button, why does it need to be mapped? Why does this error not get thrown when using the `SubmitType` but when extending from it? I also can't set the option `mapped` to false, since it's not a valid option for the `SubmitType` which makes sense, but then why am I getting the error?

**Comment by stof** [comment]
does it work fine if you use a SubmitType directly ?

**Comment by tzfrs** [comment]
The `SubmitType` works without problem. I fixed my problem also by writing this into my `fields.html.twig`

```
{%- block submit_widget -%}
    {% set label = label|raw %}
    <button type="submit" {{ block('button_attributes') }}>{{ label|raw }}</button>
{% endblock %}
```

But I just thought that the behavior I encountered is not the desired one, so I opened an issue.

**Comment by stof** [comment]
OK, found it. Buttons have a special handling in the Form tree. To tell the type resolver that your type creates a submit button rather than standard form element, you need to implement the ``Symfony\Component\Form\SubmitButtonTypeInterface`` marker interface on your form type, as far as I can tell. Can you try this ?

**Comment by tzfrs** [comment]
I can confirm that this works!

**Comment by stof** [comment]
I don't think this is documented. I'm not even sure the doc team is aware of this specific case (I was not until a few minutes ago) when I looked for it).
Please open an issue on the doc repo about it. We should have a cookbook article about creating custom form button types (even though it is not common). 

FYI, there are 2 available interfaces: ``Symfony\Component\Form\SubmitButtonTypeInterface`` for form types creating a submit button and ``Symfony\Component\Form\ButtonTypeInterface`` for types creating another kind of buttons.
And the type hierarchy does not apply when handling these markers currently. Child types must implement the interface too (which is what needs to be documented)

**Comment by HeahDude** [comment]
Another solution is to extend the `SubmitType` using the PHP inheritance instead of the component's one.

**Comment by tzfrs** [comment]
Thank you! I'll open an issue there later.

**Comment by tzfrs** [comment]
@HeahDude - Yes, but then I can't use a custom form field template in twig. When I do it like you said and and write a custom twig template, the template doesn't get rendered. I still need to use the `submit_widget` then which would destroy - in this case - the purpose of a custom form type.

**Comment by HeahDude** [comment]
You can customize `getBlockPrefix`

**Comment by tzfrs** [comment]
I can confirm that your solution also works. However I'll stick to the Interface for now

**Comment by HeahDude** [comment]
It happens to use PHP inheritance also in the core take `AbstractType` or `DoctrineType` for examples ;)

**Comment by xabbuh** [comment]
@stof I discussed a similar topic before with another user in #18549. At that time I did not think that it could be a common use case to provide your own submit button type implementations and I am still not convinced that this is a good idea. But since apparently people at least to do that we should probably add something to the docs about this topic.

**Comment by stof** [comment]
@HeahDude the DoctrineType class is not a form type by itself. It is an abstract class to share the implementation between several types. Same for AbstractType (being there to implement all methods as empty ones to make the code more readable)

Using PHP inheritance would mean that Symfony would not consider your type as a child type of the SubmitType, and so any customization of the SubmitType done using the form extension points would get lost.
Using PHP inheritance between an existing form type and your own form type is always a bad idea.

**Comment by tzfrs** [comment]
@xabbuh What would be your recommended way then to have a button which takes HTML as label without overriding the `submit_widget`?

**Comment by HeahDude** [comment]
@tzfrs You can just use a `ButtonType` and play with the key `type` in `attr` option if needed, can't you?

@xabbuh Right, one just needs to know what he does when choosing one of them (or both).

**Comment by tzfrs** [comment]
@HeahDude  I think there are many possibilities how to solve this problem, I just was curious as why it didn't work when using `getParent`. Thank you all.
