### ISSUE TITLE
Process and encapsulated quotes in parameters

### ISSUE THREAD

**Issue by h0gar** [symfony/symfony#20527]
I'm trying to run a mysql command using the process package, but I'm having troubles with the double quotes.

My process builder looks like this:

```
$query = "LOAD DATA INFILE 'file.csv' IGNORE INTO TABLE `table` FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n' (col1, col2, col3)";
$builder = new ProcessBuilder([
	'mysql',
	'-u',
	$user,
	$pass ? '-p'.$pass:null,
	$db,
	'-e',
	$query
]);
```

Process generates the following command line:

`cmd /V:ON /E:ON /D /C "("mysql" "-u" "root"  "database" "-e" "LOAD DATA INFILE 'file.csv' IGNORE INTO TABLE `table` FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n' (col1, col2, col3)") 1>"...\AppData\Local\Temp\sf_proc_00.out" 2>"...\AppData\Local\Temp\sf_proc_00.err""`

And it fails, due to the quote between "ENLOSED BY'" and "'LINES TERMINATED BY". Without this quote, it works except that MySQL can't parse the file properly. How am I supposed to pass the SQL query parameter?

**Comment by nicolas-grekas** [comment]
Does the issue still exist with Process v3.3, using `new Process(...)` instead of `new ProcessBuilder()`?

**Comment by javiereguiluz** [comment]
Closing because of the lack of feedback and because, as mentioned by Nicolas, `ProcessBuilder` has been deprecated by something better and this issue is probably fixed. Thanks!
