### ISSUE TITLE
[BUG] ArgumentValueResolver

### ISSUE THREAD

**Issue by teerawutdir** [symfony/symfony#20546]
i partice follow this http://symfony.com/blog/new-in-symfony-3-2-user-value-resolver-for-controllers

when logged $user still null
public function barAction(UserInterface $user = null) { ... }

**Comment by xabbuh** [comment]
@teerawutdir I am sorry, but with this description we will not be able to help you. Please describe the steps we need to perform to reproduce your issue. The best would be if you could fork the Symfony Standard Edition and make the changes that are necessary to reproduce it.

**Comment by teerawutdir** [comment]
Sorry For Bad English 

I've Test Code From http://symfony.com/doc/master/controller/argument_value_resolver.html
From example priority is 50 
that make $user to null but i resolved 
problem with set priority to 100

Thankyou for your help
