### ISSUE TITLE
Validator/LoaderInterface has the ClassMetadata implementation as typehint

### ISSUE THREAD

**Issue by appeltaert** [symfony/symfony#20542]
Instead of ClassMetadataInterface

**Comment by xabbuh** [comment]
The `ClassMetadataInterface` was introduced long after the `LoaderInterface`. Changing the argument type hint would have been a BC break then. Though I wonder if it is really necessary to have an interface for this. Is there an actual use case where you want to exchange the metadata class implementation?

**Comment by appeltaert** [comment]
I can imagine.. Well i got stuck in a situation where i needed to validate an array holding data, and another array holding the constraints for keys in the data array. Couldn't rebuild this, its part of a larger subsystem that dynamically builds everything based on definitions that are linked to other relations of users, yadayada.. 

For complex situations with no Class or file holding the constraints you can always loop over data and validator yourself ofcourse, but thats a problem when you need a Context instance to hold the root data so constraints can access the root data.

Something like this:

```php 
$arr = [
'config1' => 'val1',
'config2' => 'val2,
];

$constraints = [
  'config1' => [
    new NotBlank  ,
    ..
  ],
  'config2' => [
    new Callback..., // <-- reads config1
    ...
  ]
];
```

I couldve fixed it using the validator if i could write another Loader and a ClassMetdata class that can read __call's from an ArrayObject or something, but it was this simple fact that blocked me. So i thought i'd report it.

I solved it right now simply looping over the data, then looping over the constraints, and creating the *Validator classes myself, passing a Context class that holds the root data.

**Comment by xabbuh** [comment]
closing here as we cannot solve it without a BC break as explained
