### ISSUE TITLE
[FrameworkBundle][Process] 3.2.0 RC1: Webserver as run configuration in PhpStorm/IntelliJ

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#20565]
It has always been handy for me to configure the `server:run` command as a run configuration in PhpStorm. This way, I can launch the webserver with a single click and relaunch or stop it from within the IDE.

<img width="594" alt="bildschirmfoto 2016-11-19 um 00 35 16" src="https://cloud.githubusercontent.com/assets/1506493/20450376/5867abb8-adf0-11e6-8077-0af74e04e43b.png">

After upgrading to Symfony 3.2, this run configuration has stopped working. When launching it, it stops immediately the following error message:

```
  [Symfony\Component\Debug\Exception\ContextErrorException]                   
  Warning: proc_open(/dev/tty): failed to open stream: Device not configured 
```

Running the command in a normal shell still works, though.

System: macOS 10.12.1, php 7.1.0 RC6.

**Comment by nicolas-grekas** [comment]
This must be related to #19174.
Can you try two different things please?
1. replace setTty by setPty in src/Symfony/Bundle/FrameworkBundle/Command/ServerRunCommand.php => works? if yes, can you see colored output?
2. apply #20576 => removes the notice?

**Comment by derrabus** [comment]
Replacing `setTty` by `setPty` works first. This is the output I get:

<img width="701" alt="bildschirmfoto 2016-11-21 um 10 17 44" src="https://cloud.githubusercontent.com/assets/1506493/20476973/e243249a-afd3-11e6-81db-910950eca2e7.png">

So, no colored output if I use the run configuration. But the output is colored, if I use `server:run` inside a normal console. But note that after this change, the web server access is not logged to the console anymore.

Additionally, after reloading the page a couple of times, the command exits with the following error:
```
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11".
```

Patch #20576 fixes everything for me:

<img width="704" alt="bildschirmfoto 2016-11-21 um 10 28 13" src="https://cloud.githubusercontent.com/assets/1506493/20477315/560fb022-afd5-11e6-9d91-b7bc96d6264f.png">

**Comment by nicolas-grekas** [comment]
Then #20576 is the way to go. Thanks!

**Comment by nicolas-grekas** [comment]
PR updated to fix tests, can you please check again?

**Comment by derrabus** [comment]
Yes, the PR still works for me.

I still have that problem with the command exiting suddenly after some reloads, though. But it seems to be independent from how I run it and whether I apply your patch or not, so I'll file a separate bug report about it. Right now, the PR makes things better for me. 👍

**Comment by nicolas-grekas** [comment]
>   The process has been signaled with signal "11".

that's a segfault, we can't do anything about it on Symfony side, this is a php engine issue...

**Comment by fabpot** [comment]
@derrabus If you are using PHP 7.1RCx, the segfaults are indeed a bug in PHP.

**Comment by derrabus** [comment]
I've opened #20580 for this issue. I can try to reproduce it with php 7.0 later, if that helps.
