### ISSUE TITLE
3.2.0-RC1: Problem with redis provider service

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#20563]
I am trying to update the Zikula core to Symfony 3.2.0-RC1. When running composer I receive the following error:

```
[RuntimeException]                                                                                                                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                          
  PHP Fatal error:  Uncaught Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException: Service definition validation errors (1):                      
  - cache.default_redis_provider: Class "Redis" does not exist in /.../src/vendor/matthiasnoback/symfony-service-definition-validator/Compiler/ValidateServiceDefinitionsPass.php:44

Stack trace:
  #0 /.../src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(120): Matthias\SymfonyServiceDefinitionValidator\Compiler\ValidateServiceDefinitionsPass->process(Object(Zikula\Bridge\DependencyInjection\ContainerBuilder))
  #1 /.../src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(565): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Zikula\Bridge\DependencyInjection\ContainerBuilder))
  #2 /.../src/lib/Zikula/Bridge/DependencyInjection/ContainerBuilder.php(110): S in /.../src/vendor/matthiasnoback/symfony-service-definition-validator/Compiler/ValidateServiceDefinitionsPass.php on line 44
```

The `appDevDebugProjectContainer.xml` file contains the following service definition:

```xml
    <service id="cache.default_redis_provider" class="Redis">
      <argument>redis://localhost</argument>
      <factory class="Symfony\Component\Cache\Adapter\RedisAdapter" method="createConnection"/>
    </service>
```

Is this a problem which must be fixed in our config file? If yes, how to do that (couldn't find anything about it in the cache component docs)?

**Comment by HeahDude** [comment]
This is about a dependency which tries to get a not yet defined service in a compiler pass `Matthias\SymfonyServiceDefinitionValidator\Compiler\ValidateServiceDefinitionsPass` from your trace.

Maybe related to https://github.com/symfony/symfony/pull/20533, but what's weird is that it's already part of RC1.

@nicolas-grekas any thought?

**Comment by nicolas-grekas** [comment]
@Guite can you try #20537 see if it fixes your issue?

**Comment by Guite** [comment]
@nicolas-grekas doesn't seem to change anything. Not sure though whether I did it correctly: I ran `composer update`, manually merged your changes and ran `composer update` again.

**Comment by nicolas-grekas** [comment]
This is a false positive in https://github.com/matthiasnoback/symfony-service-definition-validator
Yet, we maybe able to do something about it in #20577

**Comment by Guite** [comment]
@nicolas-grekas I confirm that #20577 fixes this issue :tada:
