### ISSUE TITLE
Profiler directory is absent from the cache after running cache:clear

### ISSUE THREAD

**Issue by arnucci** [symfony/symfony#20572]
Hello
In upgrading from version 2.7.19 to 2.7.20, I noticed that logs are absent from the logger pannel in the web debugger interface.
After running a few tests, I realized that logs are present when I simply run the bash command rm -rf * in the cache/dev directory and absent when I run php app/console cache:clear.

I observed that in the second case, the profiler directory is absent from the cache.

My environment : OS : linux, php version 5.5.9

**Comment by PeterFour** [comment]
I'm having sor of the same issue. The profiler directory always stays empty, and cause the WDT to crash with the alert. Everything is set in term of permissions, but it only affect one of my symfony project.

**Comment by pixeltreiber** [comment]
@arnucci For me the profiler folder is deleted both in 2.7.19 and 2.7.20 when you do a cache clear. You say that logs are still there even if you run "rm -rf *" in the cache/dev directory. If you then still have the profiler data I think your app does not run in the dev environment. Another possibility would be that your rm command fails without returning an error. I had that problem with virtualbox shared folders.
I think it's normal that the profiler data is lost if you do a cache clear. This data can not be created on cache warmup. If you want to keep profiler data also when you do a cache clear, you should set a different folder to store that data. See [http://symfony.com/doc/2.7/profiler/storage.html](http://symfony.com/doc/2.7/profiler/storage.html)

**Comment by arnucci** [comment]
Hello pixeltreiber

Regarding you're answer and my first post, it seems that i was not very explicit. So I try again with more details.

In both version, (v2.7.19 and 2.7.20) when I run the cache:clear command, the profiler dir is remove from the cache.

But when I browse my app again, with v2.7.19, the profiler dir is "rebuilt" and I see new log in the web profiler.
On the other hand with v2.7.20, when I navigate again, the profiler dir is still absent and the logger panel of the web profiler is empty.

Last case : with v2.7.20
I remove the entire cache/dev directory with the rm command.
When I browse my app again, the cache is rebuilt whit a profiler dir in it and the log that match with my navigation. And I can see these logs in the logger panel.

So I don't think the problem is the location of the profiler dir. I don't want  to keep old logs, I just want the new one :-)

**Comment by javiereguiluz** [comment]
@arnucci can you reproduce the error with the latest version of the 2.7 branch, which is 2.7.24: http://symfony.com/blog/symfony-2-7-24-released

**Comment by arnucci** [comment]
@javiereguiluz : I do the tests describe above with the new version (2.7.24) and it works as expected.
Both version 2.7.19, 2.7.24 have the same behaviour.
When I clear the cache with cache:clear command , the profiler dir is deleted.
But It is automatically "recreated" as I navigate into my app.
The logs tab is not empty anymore and I can search a specific token (from token created after I clear the cache)

So to me, the problem is solve.
Thanks
