### ISSUE TITLE
Symfony2 swiftmailer dependent problem with smtp transport and CLI

### ISSUE THREAD

**Issue by tsifra** [symfony/symfony#20570]
This problem is related to swiftmailer, monolog and symfony2. I believe roots of the problem are somewhere in symfony2. I've faced exactly the same problem as [follows](http://stackoverflow.com/questions/36730347/cant-send-e-mail-through-command-line-php-script-swiftmailer). But this guy had it 7 months ago. And i found it only after recent update.

So sending mail works fine from controllers but doesn't work from command. Have no idea what to look for. If i call getUsername and getHost on transport from command it returns correct data. But if i check mailserver logs after sending it looks like swfitmailer tries to send mail without username and password. If i switch to transport: mail Mail sending works absolutely fine.

First problem that i've got after upgrade is described [here](https://github.com/symfony/monolog-bundle/issues/182). It's also related with mail sending but with Monolog.

**Comment by xabbuh** [comment]
Without some more detailed information it will unfortunately be hard to help you. Best would be if you could come up with a fork of the Symfony Standard Edition where you made the needed changes to reproduce your issue.

**Comment by tsifra** [comment]
You're right. I've forgot to put detailed info on this.
symfony/symfony v2.8.14
symfony/swiftmailer-bundle v2.4.0
symfony/monolog-bundle 2.12.0
swiftmailer/swiftmailer v5.4.4
symfony/swiftmailer-bundle v2.4.0

One detail i also forgot to mention that i have to use dirty hack in swiftmailer code to allow usage of self signed certificate on server. Like described [here](http://stackoverflow.com/questions/26896265/php-swiftmailer-using-starttls-and-self-signed-certificates/27106677#27106677). It didn't cause any problems till recent symfony and swiftmailer changes. I have to use this because monolog also uses default params from YML files. As i know there is no option in symfony's config to allow this. Anyway this code modification shouldn't cause such strange behaviour difference in controller and in command line. Here is code of command. If i use transport: mail (postfix is configured to forward mail through another host relayhost = [mail.mail.me]:587) everything work fine. But if i change transport to smtp mail in controller is working and mail in CLI not.

```
class CronCommand extends ContainerAwareCommand
{
	...

	protected function execute(InputInterface $input, OutputInterface $output)
	{
		$mailer = $this->getContainer()->get('mailer');
		$message = \Swift_Message::newInstance();
		
		$message
			->setSubject('test')
			->setFrom(array('mail@mail.me' => "name"))
			->setTo('mail@mail.me')
			->setBody(
				"test",
				'text/html'
			);

		$numSent = $mailer->send($message);
	}

	...
}
```

**Comment by javiereguiluz** [comment]
@tsifra although it's not a solution we'd recommend ... could you please try the code shown here?
https://github.com/swiftmailer/swiftmailer/issues/544#issuecomment-220103233

**Comment by mvrhov** [comment]
Do you have to use self signed certificate in the days that Let's Encrypt offers free certificates?

**Comment by tsifra** [comment]
@javiereguiluz this solution is working as i remember. But i have to use transport: mail option not because of SSL, I have to use it because transport: smtp works fine in controllers, but doesn't work in command line calls.
@mvrhov you're right. let's encrypt is great. I use it for web. Hopefully i'll do setup for mail server also. This issue not about this.

**Comment by xabbuh** [comment]
@tsifra Can you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your problem? I was not able to do so (see also https://github.com/symfony/symfony/issues/20570#issuecomment-270839320).

**Comment by xabbuh** [comment]
Closing here due to the lack of feedback. @tsifra Please let us know when you can provide more information and we can consider to reopen.
