### ISSUE TITLE
[Serializer] Fatal error: Class 'Symfony\Component\PropertyAccess\PropertyAccess' not found

### ISSUE THREAD

**Issue by johnpancoast** [symfony/symfony#20588]
Using `symfony/serializer: "~3.1"` in my project and got that error when using the ObjectNormalizer. Seems that serializer component is [dependent on PropertyAccess](https://github.com/symfony/serializer/blob/3.1/Normalizer/ObjectNormalizer.php#L15) but there's [no requirement](https://github.com/symfony/serializer/blob/3.1/composer.json#L18) in composer.

**Comment by johnpancoast** [comment]
Hmm I guess the docs say that you need to add the dependency on property access yourself if you want to use the resolver.

**Comment by hefekranz** [comment]
super bad.

**Comment by weaverryan** [comment]
Hmm, seems we could probably add a check for the class a better exception if it's not found. @dunglas there are quite a few optional deps inside `symfony/serializer` - what do you think about adding some more explicit checks when optional deps are used in the code?

**Comment by dunglas** [comment]
Why not, but it's already explicitly stated in the suggest section of `composer.json`: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/composer.json#L45

**Comment by fabpot** [comment]
We are throwing specific exception for such cases in other places in the framework, I think it's better than having a PHP error. By the way, the `suggest` section of `composer.json` is not really useful here.

**Comment by dunglas** [comment]
Ok I'll open a PR to add exceptions.

**Comment by hefekranz** [comment]
Thanks guys!

**Comment by nicolas-grekas** [comment]
friendly reminder @dunglas

**Comment by dunglas** [comment]
@nicolas-grekas the related PR has already been merged https://github.com/symfony/symfony/pull/24563. Closing.
