### ISSUE TITLE
[YamlFileLoader] Error: Undefined class constant 'PARSE_CONSTANT'

### ISSUE THREAD

**Issue by emirb** [symfony/symfony#20581]
## Overview
I tried to test my code readiness for Symfony 3.2-RC1. I've set my `minimum-stability` to `dev` and ran `composer update symfony/symfony --with-dependencies`. The update itself went well, however I found out that my functional tests are failing. 

It seems that the problem is not specific to my code, but happens in 3.2.0-RC1 in general.

Versions:
```
$ php -v
PHP 7.0.13 (cli) (built: Nov 21 2016 14:25:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies

$ symfony --version
Symfony Installer version 1.5.9
```

## Steps to reproduce
1. Install a 3.2.0-RC1 version of Symfony using Symfony installer:

```

$ symfony new demo 3.2.0-RC1

  WARNING  You are downloading an unstable Symfony version.

 Downloading Symfony...

    5.2 MiB/5.2 MiB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%
....
$ cd demo
```
2. Run PHPunit:
```
$ phpunit
PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 183 ms, Memory: 6.00MB

There was 1 error:

1) Tests\AppBundle\Controller\DefaultControllerTest::testIndex
Error: Undefined class constant 'PARSE_CONSTANT'

/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:396
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:69
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php:45
/private/tmp/demo/app/AppKernel.php:48
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:570
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:483
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:116
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:146
/private/tmp/demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php:33
/private/tmp/demo/tests/AppBundle/Controller/DefaultControllerTest.php:11

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

The issue seems to be on line [396](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L396) of `Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php`
However, I see that the constant is properly defined in [\Symfony\Component\Yaml\Yaml](https://github.com/symfony/yaml/blob/3.2/Yaml.php#L31).

**Comment by ogizanagi** [comment]
I wasn't able to reproduce the issue following your steps 😕

**Comment by derrabus** [comment]
PHPUnit bundles its own version of the YAML Component. My best guess is, that somehow PHPUnit's version of the YAML Component is loaded instead of the one from your vendors.

**Comment by fabpot** [comment]
@derrabus You are right, that's exactly what happens here.

**Comment by emirb** [comment]
@derrabus Thanks for clarifying! Requiring `phpunit/phpunit` and running it from `vendor/bin/phpunit` works correctly.
