### ISSUE TITLE
[Process] timeout not triggered when using process as iterator

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#20594]
As the title says, When using `Process::getIterator` execution hangs regardless of the timeout value. This doesn't happen when using a callback supplied to `Process::wait`.

Shouldn't the `getIterator` method internally call `checkTimeout`?

A workaround is to call `getIterator` with the `ITER_NON_BLOCKING` flag, and manually call `checkTimeout`.

````php
foreach ($process->getIterator(Process::ITER_NON_BLOCKING) as $type => $data) {
    try {
        $process->checkTimeout();
    } catch (\Exception $err) {
        break;
    }
    if (empty($data)) {
        usleep(100);
        continue;
    }
    // Handle data as usual
}
````

**Comment by chalasr** [comment]
Status: reviewed 👍 

See #20600

**Comment by twifty** [comment]
Wow, That was a quick fix 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
