### ISSUE TITLE
[HttpFoundation] Google Data Saver Issue with X-Forwarded-For and Forwarded Header

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#20597]
Hello,

  So recently we discovered an issue with one site we built when using android chrome with the data saver mode turned on. Basically data saver mode uses a google proxy. The main page would load, but all 'sub' pages returned a 404. Digging around we found an exception in the prod.log.

[2016-11-22 09:16:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 
The request headers contain conflicting information regarding the origin of this request. at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:67 Symfony\\Component\\HttpFoundation\\Exception\\ConflictingHeadersException(code: 0): The request has both a trusted Forwarded header and a trusted Client IP header, conflicting with each other with regards to the originating IP addresses of the request. This is the result of a misconfiguration. You should either configure your proxy only to send one of these headers, or configure Symfony to distrust one of them. 

The headers being sent were:
Array
(
    [Host] => www.oursite.com
    [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [Accept-Encoding] => gzip, deflate, sdch
    [Accept-Language] => en-US,en;q=0.8,fr-CA;q=0.6,fr;q=0.4,es;q=0.2
    [Cache-Control] => max-age=0
    [Forwarded] => for=70.72.63.221
    [Save-Data] => on
    [Scheme] => http
    [Upgrade-Insecure-Requests] => 1
    [Via] => 1.1 Chrome-Compression-Proxy
    [X-Forwarded-For] => 70.72.63.221
    [Connection] => Keep-alive
)

Which shows it has both headers, but they match (other than for=X in the Forwarded header).

What I'm wondering is if this should have caused the error it did? Looking at the bootstrap.php.cache relevant code it checks it the addresses match, but I'm not 100% sure if it should have been an error.

This is also somewhat problematic since we didn't configure any proxy settings. This is a user proxy that they can enable/disable and since there are so many android devices out there with Chrome, this could affect any site using symfony. Oddly enough another site using a similar set of bundles doesn't have these issues so I'm quite confused.

**Comment by xabbuh** [comment]
@gnat42  Can you check if this is the same as #20215?

**Comment by gnat42** [comment]
It sure is. Closing as duplicate of #20215
