### ISSUE TITLE
[DI] Custom service definition classes are not supported

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#20608]
Commit https://github.com/symfony/dependency-injection/commit/ec7e70fb2b1a8c6263528b5ffa1f065e510e4f88 by @nicolas-grekas introduced additional check, which from my understanding should prevent adding `DefinitionDecorator` services definitions. However the way this bug was fixed also breaks all implementations where `Definition` is extended by custom class. The example use case in my code is adding some strict checks for parameters of service. 

In my opinion it should specifically check for `DefinitionDecorator`.

**Comment by stof** [comment]
What is your use case for using a custom class ?

**Comment by nicolas-grekas** [comment]
Would you mind opening a PR so that we can have the discussion alongside
with the code?

**Comment by stof** [comment]
and btw, this does not prevent their usage when you compile the container. It prevents their usage only when you use the ContainerBuilder to instantiate the service

**Comment by kiler129** [comment]
@nicolas-grekas: See https://github.com/symfony/symfony/pull/20609
@stof: I'm implanting DIC into very very very old system so custom service definition contains additional check for class passed to implement old logic used before refactoring code to use Symfony DIC. The additional thing which we do is assigning custom parameters to service which are later processed by custom compiler pass and rewritten to container parameters - this is actually a workaround for lack of per-service parameters.
