### ISSUE TITLE
[security] Class __PHP_Incomplete_Class has no unserializer

### ISSUE THREAD

**Issue by johndodev** [symfony/symfony#20606]
Hello, 

It is a pretty weird bug as always for this one.

I use silex, not symfony, but the problem is on the securityComponent, so not especially related to silex.

- The message is : 

    Warning: Class __PHP_Incomplete_Class has no unserializer in /var/www/project/vendor/symfony/security/Core/Authentication/Token/AbstractToken.php on line 164

- The class it is talking about is *DoctrineProxies\__CG__\App\Entity\User* (unserialize_callback_func is telling me).

- My user implement Serializable with id, username, password.

- On the application, I use subdomain to identify a company (I have a Company entity with a slug property). I also have some special subdomain, as "manager" for example.

- My session domain is the TLD, so when I'm logged on a company, I'm logged on every company, on the manager etc... (There is a /login on every subdomain, but for each it is the same function called).

- And there is the problem. Everything work fine until I add a ManyToOne relationship  on the company to an User : 

```
class Company
{

    /**
     * @ORM\ManyToOne(targetEntity="User")
     */
    private $creator;
```

Now, let's say I log in on the "manager" subdomain. It's working. I switch on a company URL, still working, I'm logged. I switch again to manager, bug append (see the warning).

Another try : I log in directly on a company subdomain ("anonymous" pages are okay, not logged, working). Bug append directly.

Bug vanish as soon I remove the relation (I still have to clear my session cookie).

Soo, I tried some changes in my code, in listeners, in "company management", but still. So before break the app more deeply, I wanted to ask security pro players. 

Also, bug is the same on production environment (well, the project is not really in production yet, internal beta).

**Comment by johndodev** [comment]
News:

I have a listener on KernelEvents::REQUEST which had a priority of 255 to load the currentCompany on the request attributes from the subdomain.

The bug disappear if I change the priority to 8 max. Since 8 is the priority of the firewall, I guess I shouldn't load a Company entity before firewall job (but I don't know why).

You can close the issue, I think I can handle the sides effects of this change in my app, if any, but I can provide more information if you really want to investigate.

**Comment by iltar** [comment]
The problem is that you're storing entities in your session: https://stovepipe.systems/post/decoupling-your-security-user
