### ISSUE TITLE
Redesign the Symfony exception pages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20620]
The design of the Symfony exception pages hasn't been updated in years. After the [Symfony Profiler redesign](http://symfony.com/blog/new-in-symfony-2-8-redesigned-profiler) introduced in Symfony 2.8, updating their design is more needed than ever.

I've created this issue to tell you that we've already started working on this and that we'll show the result in a few days, after the [SymfonyCon Berlin](http://berlincon2016.symfony.com) so the community can provide feedback about it. Meanwhile, please try to not change anything related to those pages. Thanks!

**Comment by lyrixx** [comment]
Please, re-introduce this [PR](https://github.com/symfony/symfony/pull/10729) ;)

**Comment by iltar** [comment]
Big plus from my side, their design is a bit off now.

_Sneaky advert for the last few tickets for SymfonyCon?_ 😄
