### ISSUE TITLE
Wrong property path for validation when using view transformer

### ISSUE THREAD

**Issue by YaoOcelotl** [symfony/symfony#20624]
When you use a view transforme in an embedded form, child leaf forms have a property path '[name]' and the ViolationMapper can not mach the path.

**Comment by xabbuh** [comment]
@YaoOcelotl Can you please fork the Symfony Standard Edition and make the needed changes to reproduce your issue?

**Comment by YaoOcelotl** [comment]
Hello @xabbuh,

I have submitted a patch with the required test needed to check for this bug.

**Comment by YaoOcelotl** [comment]
The example is ready see:
https://github.com/YaoOcelotl/symfony-standard/tree/example/compound-form-and-data-transformer

The root form does not use the data transformer and sets the data_class to class name ,and the child forms use the data transformer and sets the data_class to null.

Submit an empty form and the error at root level are as expected but for the childs the error bubbles.

**Comment by xabbuh** [comment]
I am going to close here. As @HeahDude said in the linked PR using the transformer for your use case doesn't look right.
