### ISSUE TITLE
[RFC] Consider versioning the XSD files

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20635]
For those developers using XML config in their Symfony apps, don't you think we should start versioning the XSD files?

For example, in [this recent PR](https://github.com/symfony/symfony/pull/11394/files#diff-bf0f08e3953ad533af3316e3674f7a35) we changed a lot the contents of `routing-1.0.xsd`  ... but the file continued being the `1.0` version instead of bumping it to `1.1`.

Should we care about versioning? Does BC policy apply to these XML files? Thanks!

**Comment by sstok** [comment]
It should yes, whenever the schema changes (removal of old options, like pattern/path in routing).
For the actual functioning of Symfony this is not really important as schema's are loaded locally (and never remote), but PHPStorm allows to fetch the XSD for code suggestions and validation.

**Comment by javiereguiluz** [comment]
Versioning these files would be complex both for Symfony and for the applications using them ... so another solution could be to remove the versioning entirely and name these files `routing.xsd` instead of `routing-1.0.xsd`, etc.

**Comment by javiereguiluz** [comment]
Let's make a decision about this:

1. Keep the current behavior (make changes but don't change the file version)
2. Remove the version numbers from files
3. Add full versioning to files: any change bumps the file version number

My vote goes for 1.  Ping @symfony/deciders

**Comment by GromNaN** [comment]
The versioning is already provided by Symfony version.
* [v2.8.17/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd](https://raw.githubusercontent.com/symfony/symfony/v2.8.17/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd)
* [v3.2.3/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd](https://raw.githubusercontent.com/symfony/symfony/v3.2.3/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd)

**Comment by lsmith77** [comment]
The purpose of these files is mainly to ease people using XML config to create configuration files. As such I guess our config structure that they define is covered by the BC promise and as such this constraints the contents of the XML files.

So I guess your above question regarding the BC promise was only about the file name itself?

**Comment by Taluu** [comment]
AFAIC, I think option 1 or 2 are nice.

**Comment by stof** [comment]
I opened https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/879 to see whether PhpStorm could be taught to find the bundled XSD schema files (as done by Symfony), which would make the behavior nicer.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" ... because the current situation works well and there's not enough consensus to change this. Thanks!
