### ISSUE TITLE
Rename framework.ide = symfony to framework.ide = browser

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20633]
In #19973 @jeremyFreeAgent introduced a cool option to open files in the browser itself instead of your IDE/editor. This is activated when `framework.ide` is no configured or when you set `framework.ide` to `symfony`.

Given that this option opens a file in a browser and given that this is used outside of Symfony (for example [in this Silex code](https://github.com/silexphp/Silex-WebProfiler/commit/db11b65f98939440d985042d8f76a7148af9155d)), what do you think about renaming `framework.ide = symfony` to `framework.ide = browser` ?

**Comment by nicolas-grekas** [comment]
open a PR, we'd better have the discussion on the actual code

**Comment by javiereguiluz** [comment]
@nicolas-grekas but the usual workflow is to propose an idea/change via an issue and if it's accepted, then create the PR.

Moreover, I looked into #19973 and I couldn't see where the `symfony` string is hardcoded. I don't know if it's a bug or I'm missing something.

**Comment by nicolas-grekas** [comment]
> I couldn't see where the symfony string is hardcoded

you're right! in fact, the description is outdated: the default is to open in the browser, see https://github.com/symfony/symfony-demo/pull/392/files

**Comment by jeremyFreeAgent** [comment]
Yes that right @nicolas-grekas

**Comment by javiereguiluz** [comment]
I'm closing this issue then because the `symfony` option does not exist.
