### ISSUE TITLE
[Debug] Warning: Class __PHP_Incomplete_Class has no unserializer

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20654]
I'm not sure if this is a Symfony issue or something on my side ... but when upgrading to/from 3.2-RC2 and 3.1, I'm getting a lot of these errors:

```
[...]

Writing lock file
Generating autoload files
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Class __PHP_Incomplete_Class has no unserializer

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling
the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Warning: Class __PHP_Incomplete_Class has no unserializer
```

**Comment by wouterj** [comment]
I think this happens quite often when upgrading versions. The cache files are not always backwards compatible.

The problem with `cache:clear` is that before clearing the cache, the cache is first used to boot the Symfony CLI. As cache is not BC, this will error. The only solution afaik is to clear the cache yourself using `rm -rf var/cache/`.

**Comment by fabpot** [comment]
@wouterj is right, nothing we can do on our side.
