### ISSUE TITLE
file not found ApcClassLoader.php in bootstrap.php.cache in hosting server

### ISSUE THREAD

**Issue by adityarai** [symfony/symfony#20655]
[27-Nov-2016 19:29:05 Asia/Kolkata] PHP Warning:  require(/home/nadiarafl/public_html/var\..\vendor\symfony\symfony\src\Symfony\Component\ClassLoader\ApcClassLoader.php): failed to open stream: No such file or directory in /home/nadiarafl/public_html/var/bootstrap.php.cache on line 1780
[27-Nov-2016 19:29:05 Asia/Kolkata] PHP Warning:  require(/home/nadiarafl/public_html/var\..\vendor\symfony\symfony\src\Symfony\Component\ClassLoader\ApcClassLoader.php): failed to open stream: No such file or directory in /home/nadiarafl/public_html/var/bootstrap.php.cache on line 1780
[27-Nov-2016 19:29:05 Asia/Kolkata] PHP Fatal error:  require(): Failed opening required '/home/nadiarafl/public_html/var\..\vendor\symfony\symfony\src\Symfony\Component\ClassLoader\ApcClassLoader.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/nadiarafl/public_html/var/bootstrap.php.cache on line 1780

the above error log is generated by server...
I updated my symfony to 3.1.7.  If i remove this line 1780 in bootstrap.php.cache, it works fine in prod hosting server: 
namespace {require __DIR__.'\\..\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\ClassLoader\\ApcClassLoader.php';}

**Comment by xabbuh** [comment]
It looks strange that your path contains backslashes while your filesystem seems to be UNIX-based. Did you warm up the cache on a Windows system?

**Comment by adityarai** [comment]
I'm using windows in my local system and its working fine there. But in hosting server (LINUX) it shows error.

**Comment by xabbuh** [comment]
Where did you warm up the cache? On your local system or on the server?

**Comment by adityarai** [comment]
In my local system actually,. i have no option to clear cache in my shared hosting..

**Comment by xabbuh** [comment]
Does it work if you just remove the cache and let Symfony spin it up on the first request?

**Comment by adityarai** [comment]
you mean the cache  folder inside var?

**Comment by xabbuh** [comment]
@nicolas-grekas It looks like we are using `DIRECTORY_SEPARATOR` somewhere when storing class file paths in the bootstrap cache. Do you remember if that was done on purpose and we didn't normalise them using `/` intentionally?

**Comment by nicolas-grekas** [comment]
@adityarai can you please try #20676?

**Comment by adityarai** [comment]
Yes, Its working fine now,... thank you,..

**Comment by athos99** [comment]
J'ai le même probleme, je travail sous Windows et génère tou mon projet pour produire un livrable, mais le livrable est prévu pour tourner sous linux et j'ai un problèeme depuis la version 3.1.7
Le fichier bootstrap.php.cache qui est généré sous windows contient à la dernière ligne.

namespace {require __DIR__.'\\..\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\ClassLoader\\ApcClassLoader.php';}

Les \\ ne sont pas comprix par linux

L'erreur provient du fichier  \vendor\symfony\symfony\src\Symfony\Component\ClassLoader\ClassCollectionLoader.php
ligne 122 à 135. 
On utilise DIRECTORY_SEPARTOR il faudrait soit utiliser '/' qui marche pour les deux environements ou alors utiliser la constante DIRECTORY_SEPARTOR et non sa valeur.
ce qui donerrait
namespace {require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'symfony'.DIRECTORY_SEPARATOR.'symfony'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Symfony'.DIRECTORY_SEPARATOR.'Component'.DIRECTORY_SEPARATOR.'ClassLoader'.DIRECTORY_SEPARATOR.'ApcClassLoader.php';}

**Comment by xabbuh** [comment]
Please use English to describe your problem so that everybody is able to understand your issue.
