### ISSUE TITLE
Profiler router panel errors when no route params present

### ISSUE THREAD

**Issue by ged15** [symfony/symfony#20650]
Steps to reproduce:

```shell
symfony new symfony-app 3.2.0-RC2
cd symfony-app
bin/console s:start
open http://127.0.0.1:8000
open http://127.0.0.1:8000/_profiler/{token}?panel=router
```

The exception:
```
An exception has been thrown during the rendering of a template ("Notice: Undefined offset: 1") in @WebProfiler/Router/panel.html.twig at line 20.
```

And the `ContextErrorException` points to `vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php:280`.

**Comment by wouterj** [comment]
Thanks for the detailed reproduce steps! I can confirm this bug and submitted a fix in https://github.com/symfony/symfony/pull/20652

status: reviewed

**Comment by ged15** [comment]
@wouterj wow, fantastic! Thanks for the amazing work!
