### ISSUE TITLE
[YAML] Parser does not handle empty lines before comment and document separator

### ISSUE THREAD

**Issue by BR0kEN-** [symfony/symfony#20659]
### Story

I was wanting get the information about using colors for languages from GitHub.

![BR0kEN-/cibox continuous integration toolbox](https://cloud.githubusercontent.com/assets/2760616/20651097/0491a824-b4e7-11e6-9b54-27ec510911a6.png)

Have found [public repository](https://github.com/github/linguist) where this information conveniently stores in single [YAML file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). Okay, let's parse it using Symfony YAML component.

```php
\Symfony\Component\Yaml\Yaml::parse(file_get_contents('https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml'));
```

And I've got: `Multiple documents are not supported at line 2 (near "---").`. This happened due to [empty line before the document separator](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L34).

Also, after digging deeper, I determined that the same behavior will be in case of empty line(s) will be placed before the comment.

#### Example failing cases:

- Empty line before the document separator.
- Empty line before the comment.
- Empty line before the comment and before the document separator.
- Multiple empty lines before the comment and before the document separator.
- Whitespaces before the document separator.
- Whitespaces before the comment.
- Whitespaces before the comment and before the document separator.

I cannot provide examples here since GitHub removes empty lines, but in PR I've made [these cases are presented](https://github.com/symfony/symfony/pull/20660/files#diff-b9782e0a87ac5b704d48e33117161c37).

**Comment by javiereguiluz** [comment]
Instead of the empty line, I think the problem is what the error message says. In `Symfony\Component\Yaml\Parser.php` you can see the following:

```php
if ('---' === $this->currentLine) {
    throw new ParseException('Multiple documents are not supported.', $this->currentLineNb + 1, $this->currentLine);
}
```

So YAML files that define multiple documents are not supported. In this case the solution is simple because the file that you mentioned doesn't really have multiple documents. So you can safely do a `str_replace('---', '')` before processing the document.

**Comment by BR0kEN-** [comment]
Make sense, @javiereguiluz, I've thought about this. I've made a PR, take a look at changes there, please - they are allow to handle such cases.

**Comment by BR0kEN-** [comment]
@javiereguiluz, should there labels be changed for this issue, since PR has a `Reviewed` status?

**Comment by javiereguiluz** [comment]
@BR0kEN- you are right! Changed.

**Comment by stof** [comment]
Well, the parser is not wrong here. The file indeed has 2 YAML documents here, except that the first document contains only comments

**Comment by BR0kEN-** [comment]
@stof, but parser should not produce fatal errors in this case.

**Comment by stof** [comment]
Well, the Symfony parser does not support multi-document files, and this is indeed a multi-document file (even though the first document is useless for you). Detecting whether one of the documents contains only meaningless content (comments and whitespaces) would make the logic harder).

For this particular case, the advice from @javiereguiluz about removing the ``---`` before parsing seems much easier.

**Comment by BR0kEN-** [comment]
That's what I'm doing now. But changes are not so complex, from my point of view, and would be nice to have them available out of the box.
