### ISSUE TITLE
Don't trim strings in the VarDumper dumps of the profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20669]
Although I **love** the use of VarDumper in the 3.2 RC2 profiler, we should tweak it a bit to hurt its DX. Specifically, we should never trim strings:

![trimmed-strings-1](https://cloud.githubusercontent.com/assets/73419/20666755/1a549890-b566-11e6-89e5-d7cd60c30813.png)

![trimmed-strings-2](https://cloud.githubusercontent.com/assets/73419/20666757/1c584a06-b566-11e6-800b-076d72a5fa1e.png)

After #20380 I though this was fixed. Should we make this change in other places? Is something wrong on my side?

**Comment by chalasr** [comment]
Indeed. Commenting out [this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/ClassStub.php#L32) fixes it, but not sure about how it could be for the profiler only :/

**Comment by nicolas-grekas** [comment]
These are CSS ellipses indeed, and personally I find it more convenient to have them than having long lines that spans on several lines and make it hard to read the important info, which is the class name, not its namespace...

**Comment by wouterj** [comment]
Can we maybe readd the previous behaviour of class names in the profiler? (showing only the class name, with the FQCN as title)

**Comment by nicolas-grekas** [comment]
Note that the fqcn is still the title, and that it is also copy-pasteable.

**Comment by nicolas-grekas** [comment]
What about changing the color of the namespace instead?
E.g. using the "default" color on dumps:

![capture du 2016-11-29 10-16-29](https://cloud.githubusercontent.com/assets/243674/20703737/1ea37bf2-b61d-11e6-96b8-9767d9589ef9.png)

**Comment by javiereguiluz** [comment]
When redesigning the profiler for Symfony 2.8 I also thought about displaying some information in a compact way (e.g. the logger panel). However, I think this is wrong.

The profiler is where you go when something is wrong, so you need all information at once. We don't need to make information compact and it doesn't matter if a log line spans 4 or 5 rows. Of course we can apply "intelligent design" to make important parts stand out, like the class/method names, and to fade others, like the namespace.

**Comment by ogizanagi** [comment]
Does https://github.com/symfony/symfony/issues/20679 closes this one or is there anything else to do?

**Comment by nicolas-grekas** [comment]
Done
