### ISSUE TITLE
Consider deprecating ClassCollectionLoader & co.

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20668]
Calling for feedback + experiment from the community on this topic:

on a Symfony standard edition, prod env, no-debug, PHP 7, composer -o (ie normal setup for prod),
if I comment the line requiring `bootstrap.php.cache` and the call to `$kernel->loadClassCache();` in `web/app.php`, it looks like my setup is *not* slowed down, if not a bit faster.
I used `ab` for benching.

That could mean we don't need these optims in PHP 7 era.

If this is confirmed, it means we could consider deprecating `ClassCollectionLoader` and `$kernel->loadClassCache()`.
Could any of you try the same and report some resulting numbers?
Thanks in advance!

**Comment by stof** [comment]
Yeah, the composer optimized autoloader kinds of defeat this, as it does not need any stat call to identify the file to be loaded.
And then, OPCache takes care of the loading of the file itself.

I'm all 👍 for deprecating this.

The question then is whether we should really ship the new ``addAnnotatedClassesToCompile`` in 3.2 if we want to deprecate the whole system in 3.3

**Comment by javiereguiluz** [comment]
Even if we don't use it much, I'd say it's too late to remove `addAnnotatedClassesToCompile()` for 3.2 (which is due in just a few days).

**Comment by dmaicher** [comment]
I just tested it on one of my bigger projects (so not on a Symfony Standard Edition).

I used `composer install --optimize-autoloader --classmap-authoritative --no-dev` and `ab -n 5000 -c 1` on `PHP 7.0.13` with the following (dev) opcache settings:

```
opcache.enable = 1
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 3
```

First 3 runs without any changes:

1. Time per request:       36.808 [ms] (mean)
2. Time per request:       36.782 [ms] (mean)
3. Time per request:       36.809 [ms] (mean)

Then 3 runs with the changes:

1. Time per request:       35.805 [ms] (mean)
2. Time per request:       35.782 [ms] (mean)
3. Time per request:       35.742 [ms] (mean)

So it seems in my tests its around 1ms faster :tada:

**Comment by iltar** [comment]
If it will be deprecated, I will remove the class load features for the kernel in #20107

**Comment by fbourigault** [comment]
Same results here. `Time per request:       10.540 [ms] (mean)` => `Time per request:       9.437 [ms] (mean)` on a Symfony/API Platform/Sonata application.

**Comment by stof** [comment]
Then deprecating looks sensible to me.

**Comment by Ocramius** [comment]
O say kill it with :fire:. This particular cache has only caused a huge load of bugs on my end, so far...

**Comment by lisachenko** [comment]
It's end of epoch of pre-compiled class cache files! Burn them all! :fire:
