### ISSUE TITLE
[Serializer] Wrong deserialization with object as constructor parameter

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#20670]
Hello,

I start with a bug before a PR because I have no time for now and it looks very weird.

In the latest RC this line looks very weird : https://github.com/symfony/symfony/blob/v3.2.0-RC2/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L340

I don't get how it could work (and it definitively do not work in my app). 

We should run a `denormalize` operation instead of  `deserialize` operation. All data should be at least decoded from json, no ?

I get also ` Warning: json_decode() expects parameter 1 to be string, array given in /var/app/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/JsonDecode.php on line 88` that which make me say I'm right.

Thanks

edit: Replacing the deserialize by denormalize make my app working

Here is a gist to reproduce : https://gist.github.com/tyx/ed50f6e525494909249b571c76360c36

**Comment by tyx** [comment]
I get it in tests : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Tests/Fixtures/DenormalizerDecoratorSerializer.php#L39

Yes we replace deserialization by denormalization so I get why test are green. Do we do the same kind of "hack" in our serializer construction ?

Here is mine for now 
```
        <service id="my.serializer" class="Symfony\Component\Serializer\Serializer" public="false">
            <argument type="collection">
                <argument type="service">
                    <service class="Symfony\Component\Serializer\Normalizer\PropertyNormalizer">
                        <argument>null</argument>
                        <argument type="service">
                            <service class="Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter" />
                        </argument>
                    </service>
                </argument>
                <argument type="service">
                    <service class="Symfony\Component\Serializer\Normalizer\ObjectNormalizer">
                        <argument>null</argument>
                        <argument type="service">
                            <service class="Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter" />
                        </argument>
                    </service>
                </argument>
            </argument>
            <argument type="collection">
                <argument type="service">
                    <service class="Symfony\Component\Serializer\Encoder\JsonEncoder" />
                </argument>
            </argument>
        </service>
```

**Comment by tyx** [comment]
Here is a gist to reproduce the problem https://gist.github.com/tyx/ed50f6e525494909249b571c76360c36

**Comment by ogizanagi** [comment]
Hi @tyx. Thanks for reporting the issue and providing the code to reproduce it. See https://github.com/symfony/symfony/pull/20690 for a possible fix.

Anyway, the bug is confirmed to me.

Status: Reviewed

**Comment by tyx** [comment]
Thanks @ogizanagi it works !

**Comment by vasilvestre** [comment]
This affect me with sf 2.8, what's the workaround for this ? I can't upgrade my dependencies :/
