### ISSUE TITLE
[Twig] form_theme _self removes global variables

### ISSUE THREAD

**Issue by martixy** [symfony/symfony#20678]
It is basically issue #5284 to the letter.

On two seperate projects, these last couple of months, I've encountered this problem.

It's still alive and well.
The workaround is to put the template in a separate file. But this prevents the use of `{{ parent() }}` forcing me to copy-paste code.

Symfony version is 3.0.something up to the current 3.1.7.

**Comment by xabbuh** [comment]
@martixy Would you be able to create a reproducable example (best by forking the Symfony Standard Edition and making the needed changes there)?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. 

@martixy Please reply if you can provide more information and we can consider to reopen.
