### ISSUE TITLE
Annotation + Group use declarations - PHP7

### ISSUE THREAD

**Issue by GeoffreyHervet** [symfony/symfony#20683]
Hello,

got the following bug in symfony 3.1.5:
```<?php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\{
    ParamConverter, Route, Method
};

/**
 * @ParamConverter("website")
 *
 * @Route("{websiteCode}", requirements={"website": "\w+"})
 */
class CategoryController extends Controller
{
}
```

The error is: `[Semantical Error] The annotation "@ParamConverter" in class CategoryController was never imported.`

When I dont use the use group feature of PHP, it works.

Best,
Geoffrey

**Comment by stof** [comment]
This must be reported to https://github.com/doctrine/annotations which is the library implementing support for annotations
