### ISSUE TITLE
Router does not handle env var parameters.

### ISSUE THREAD

**Issue by magnusnordlander** [symfony/symfony#20682]
Since #19681 was merged there is a kind of regression in routing configuration. In the routing config files, parameters on the form `%env(FOO)%` are interpreted like regular old parameters, rather than environment parameters (i.e. they always use the value set in e.g. parameters.yml). This is confusing for users.

Ideally we'd want to fix this so that env var parameters work here too, but seeing as how late we are in the release schedule, I suggest we simply disallow using parameters on the form `%env(FOO)%` by throwing an exception in `Symfony\Bundle\FrameworkBundle\Routing\Router::resolve` when one is encountered, and we can fix the issue fully in a later patch release. Sounds good?

## Reproduction

```yaml
# routing.yml
foo:
    path: /bar
    schemes: ["%env(PROTOCOL)%"]
```
```yaml
# parameters.yml
parameters:
    env(PROTOCOL): https
```

### Expected behavior
```
magnus@Turing ~/D/T/envtest> env PROTOCOL=http bin/console debug:router
 ------ -------- -------- ------ ------ 
  Name   Method   Scheme   Host   Path  
 ------ -------- -------- ------ ------ 
  foo    ANY      http     ANY    /bar  
 ------ -------- -------- ------ ------ 
```

### Actual behavior
```
magnus@Turing ~/D/T/envtest> env PROTOCOL=http bin/console debug:router
 ------ -------- -------- ------ ------ 
  Name   Method   Scheme   Host   Path  
 ------ -------- -------- ------ ------ 
  foo    ANY      https    ANY    /bar  
 ------ -------- -------- ------ ------ 
```

**Comment by stof** [comment]
We should forbid it.

Adding support for env vars there would be very hard, because most of these places are used at time of dumping the matcher (embedding them into bigger regexes), and cannot be changed at runtime (the scheme is probably the only case where it could be possible).

**Comment by nicolas-grekas** [comment]
See #20687
