### ISSUE TITLE
[YAML] Cannot parse ::class constant

### ISSUE THREAD

**Issue by sc0rp10** [symfony/symfony#20709]
Following YML produced error `The constant "DateTime::class" is not defined`
```yml
foo:
    datetime_class: !php/const:DateTime::class
```

**Comment by ogizanagi** [comment]
This is explained by the fact `::class` is not a real constant, but a php keyword triggering a compilation time transformation: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

We could surely add the `::class` support in the parser, but I wonder how relevant it'll be, considering you'll have to type the entire FQCN in the yaml file anyway?

i.e:

```yml
foo:
    bar: !php/const:Symfony\Component\HttpKernel\Kernel::class
```

vs 


```yml
foo:
    bar: Symfony\Component\HttpKernel\Kernel
```

**Comment by sc0rp10** [comment]
@ogizanagi I think variant with '::class' better: unknown class will not pass and threw compilation error.

**Comment by ogizanagi** [comment]
> unknown class will not pass and threw compilation error.

That's [a wrong assumption](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) unfortunately 😅  (unless we add a check ourself):

> Note:
The class name resolution using ::class is a compile time transformation. That means at the time the class name string is created no autoloading has happened yet. As a consequence, class names are expanded even if the class does not exist. No error is issued in that case.

**Comment by xabbuh** [comment]
I am :-1: on changing anything here. As @ogizanagi explained you need to specify the FQCN anyway. So using the `class` constant simply is more inconvenient than just typing the class name.

**Comment by javiereguiluz** [comment]
@sc0rp10 thanks for reporting this issue. Sadly I need to close it as "won't fix" because, as explained by @ogizanagi and @xabbuh, in this particular case, the use of `!php/const:` is very inconvenient and actually worse that not using it. Thanks for understanding it.

**Comment by sc0rp10** [comment]
@javiereguiluz yes, I agree - you're right! thanks!
