### ISSUE TITLE
YAML DUMP_MULTI_LINE_LITERAL_BLOCK question, possible bug

### ISSUE THREAD

**Issue by lauradean** [symfony/symfony#20706]
In outputting an array to YAML, my multi-line strings were not being output as literals, but I found that if I changed the line in Dumper.php from

```php
if ($inline > 1 && Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK
    & $flags && is_string($value) && false !== strpos($value, "\n")) {
```

to

```php
if ($inline >= 1 && Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK
    & $flags && is_string($value) && false !== strpos($value, "\n")) {
```

then it works perfectly.

Is there a reason for checking for `$inline > 1`?

**Comment by xabbuh** [comment]
@lauradean Thank you for reporting this issue. Can you please also show us the code you used to dump as well as the array to be dumped?

**Comment by lauradean** [comment]
Here is the line of code to create the Yaml:

`$yaml = Yaml::dump($result, 3, 4, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);`

The real array is too long and contains sensitive information and html that will not display properly, but here is something similar, as would be output by print_r:

```
Array
(
    [test] => Array
        (
            [0] => Array
                (
                    [key_1] => This is a single-line value.
                    [key_2] => This is a multi-line value.
It has two lines.
                )
        )
)

```
Here is the desired YAML output, which worked after I put in the above code change:

```
test:
    -
        key_1: 'This is a single-line value.'
        key_2: |
            This is a multi-line value.
            It has two lines.

```


(I did not test this specific array.)

**Comment by xabbuh** [comment]
I think you are right. See #20732 which will resolve your issue.
