### ISSUE TITLE
[WebProfilerBundle] JS error using Request as window.fetch param

### ISSUE THREAD

**Issue by OnekO** [symfony/symfony#20723]
If you try to use a Request object as window.fetch param, js will crash because:
```javascript
if (!arguments[0].match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

One easy solution is something like this before that line  (line ~246, /symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig)
```javascript
    var paramType = Object.prototype.toString.call(arguments[0]);
    if (paramType === '[object Request]') {
        arguments[0] = arguments[0].url;
        arguments[1] = {
            method: arguments[0].method,
            credentials: arguments[0].credentials,
            headers: arguments[0].headers,
            mode: arguments[0].mode,
            redirect: arguments[0].redirect
        };
    }
```

At least that's working for me, but it needs more testing.

**Comment by stof** [comment]
Can you open a pull request with the fix (targeting the 3.2 branch) ?

**Comment by OnekO** [comment]
Sure!

**Comment by OnekO** [comment]
https://github.com/symfony/symfony/pull/20724
