### ISSUE TITLE
[RFC] Rename the "config:dump-reference" command

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#20721]
I've never liked the `config:dump-reference` command name. It looks unnecessarily hard to understand and it forces you to use two different commands for very similar operations:

```
$ ./bin/console debug:config
$ ./bin/console debug:config doctrine
$ ./bin/console config:dump-reference
$ ./bin/console config:dump-reference doctrine
```

Given that this command just displays the default values for the config options, could we for example merge it with the `debug:config` command?

Something like this:

```
$ ./bin/console debug:config
$ ./bin/console debug:config doctrine
$ ./bin/console debug:config --defaults
$ ./bin/console debug:config doctrine --defaults
```

or this:

```
$ ./bin/console debug:config
$ ./bin/console debug:config doctrine
$ ./bin/console debug:config --show-defaults
$ ./bin/console debug:config doctrine --show-defaults
```

Or something else proposed by the community. Thanks!

**Comment by ogizanagi** [comment]
One of the first drawbacks I see with this, is that the `config:dump-reference` allows to dump the reference using different formats (xml or yaml), which is not proposed by the `debug:config` command, which simply choose yaml as a way to represent the processed config array in the console (it does not reflect exactly the format used for writing the configuration).

**Comment by chalasr** [comment]
@ogizanagi Wouldn't it be doable to propose `xml` as output format? Actually it's either json or yaml.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because of the reasons explained by Maxime and because there's no response from the community. Thanks!
