### ISSUE TITLE
[3.2][Validation] BC break in ValidatorCacheWarmer when class should not be used

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#20739]
For the complete context: https://github.com/symfony-cmf/routing-bundle/issues/370

In short, there are classes that should not be used in some cases (for instance, the PHPCR document referenced in the issue if PHPCR is not installed and disabled). This class definition relies on some PHPCR interfaces, which do not exists.

As the cache warmer tries to load all metadata, this results in errors. This can be fixed by dynamically registering the validation metadata in a compiler pass based on the configuration.

However, it still is a BC break in the code. I just wanted to notify you about this, not sure what can be done to avoid this (checking all interfaces first seems lots of overhead). At least, the `UPGRADE-3.2.md` file should mention this.

**Comment by nicolas-grekas** [comment]
Does #20725 fix this issue?

**Comment by wouterj** [comment]
I didn't try, but I don't think it does. It only modifies the `AnnotationCacheWarmer`, while the bug reported in this issue is about the `ValidatorCacheWarmer` (warming up the cache for XML and Yaml mappings). But maybe they can be fixed in sort of the same way?

**Comment by nicolas-grekas** [comment]
Indeed :) so if someone would like to give it a try, please do!

**Comment by wouterj** [comment]
I tried to fix this, but it's a lot more complicated and I don't know how to fix it. As the class implements a non-existing interface, a `Fatal error: Interface 'xxx' not found` error. I can't think of a way to hide this error?
