### ISSUE TITLE
[RFC] Default Custom Date and DateTime pattern 

### ISSUE THREAD

**Issue by KonstantinCodes** [symfony/symfony#20733]
In the Form Component, `\IntlDateFormatter` is used to parse Date(Time) strings and to format `\DateTime` Objects into strings based on the Date formats _FULL_, _LONG_, _MEDIUM_ and _SHORT_ as well as the Time format counterparts.

Custom Date Patterns can be explicitly set in the Options of Form Components. This however leads to Applications having to set the Pattern for all Components.

Much easier would be to have a simple configuration value to set the custom date and date_time format as a default for all Form Components.

**Example**

Current:
```
$builder
    ->add('date', DateTimeType::class, array(
        'format' => 'y-M-d H:mm:ss'
    ));
```

New Configuration:
```
form:
    default_date_pattern: 'y-M-d H:mm:ss'
```

Ultimately, this needs not be constrained to only the Form Component and could be a general configuration for the entire Application.

**Comment by xabbuh** [comment]
As far as I understand the feature request this can easily be solved in a custom form type extension and doesn't require special options. Thus I think we shouldn't implement this in core.
