### ISSUE TITLE
Behavior Change: Incorrect controller arguments no longer throw exception

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#20746]
Hi guys!

The commit sha: 9c48756a19a930ce4dc13eb47a50b89de9e3b921 (cc @iltar) changed some behavior in all versions of Symfony, I think on accident.

Consider the following:

```php
/**
 * @Route("/product/{id}")
 */
public function showAction($id2)
{
}
```

Previously, this would have thrown the following error: 

> Controller "SomeController::showAction" requires that you provide a value for the "$id2" argument (because there is no default value or because there is a non optional argument after this one).

But after this commit, it does not throw the error, and instead `$id2` is set to null in all cases. The specific problem is this block: https://github.com/symfony/symfony/commit/9c48756a19a930ce4dc13eb47a50b89de9e3b921#diff-8518ab757bc9acd6d5a874a2e2737502R135

Was this expected? It's a step back in DX, as you can now silently mess up your route param without being notified.

Cheers!

**Comment by iltar** [comment]
@weaverryan I think this is an unintended side-effect. As the method name implies, it does allow null, but this only for cases where no type-hint is given. Is this only on php7 or also on php5?

**Comment by AlkisStamos** [comment]
Hello
i've noticed this behavior on 3.1 and 3.2 but not on 3.0. It seems to be coming from the Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver::resolve method since it yields a value in any case (even null).
Changing the
`yield $argument->hasDefaultValue() ? $argument->getDefaultValue() : null;`
to
`if(!$argument->hasDefaultValue())
{
    return null;
}
yield $argument->getDefaultValue();`
Seems that it fixes this behavior cause the Symfony\Component\HttpKernel\Controller\ArgumentResolver checks for non \Generator instances.

**Comment by iltar** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/DefaultValueResolver.php#L30

This line should probably check whether a type is set, as: `fooAction($something);` allows to call: `$controller->fooAction(null);`

**Comment by weaverryan** [comment]
@iltar Yep, I'm using 5.6, so it definitely is an issue there. 

It's tricky because now that there's been a release with the behavior change, we've sorta already accidentally broken BC. If we're going to unbreak it back, we should probably do it quickly - it's already been included in 2.7.19, 2.7.20 and 2.7.21, for example, for the 2.7 releases.

@iltar are you able to make a patch that does the check you're talking about?

Thanks :)

**Comment by iltar** [comment]
First thing I'll do when I arrive at work

**Comment by fabpot** [comment]
👍 for fixing this as a bug.

**Comment by weaverryan** [comment]
Wow! That was crazy fast fix and merge - thank you @iltar!

**Comment by iltar** [comment]
@weaverryan I feel responsible for changes that I contribute to and thus find it important to provide some after-care when I can
