### ISSUE TITLE
Hardcoded dependency to glyph icons

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#20742]
In Zikula we use FontAwesome instead of GlyphIcons. Thus our bootstrap version does not include the glyph icons in order to avoid unneeded stuff wasting bandwidth.
We just discovered (https://github.com/zikula/core/issues/3243) that the Twig bridge uses a glyph icon for error messages in `Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig`:
```
{% block form_errors -%}
    {% if errors|length > 0 -%}
    {% if form.parent %}<span class="help-block">{% else %}<div class="alert alert-danger">{% endif %}
    <ul class="list-unstyled">
        {%- for error in errors -%}
            <li><span class="glyphicon glyphicon-exclamation-sign"></span> {{ error.message }}</li>
        {%- endfor -%}
    </ul>
    {% if form.parent %}</span>{% else %}</div>{% endif %}
    {%- endif %}
{%- endblock form_errors %}
```

As this is a hardcoded dependency we thought it may be interesting to report it.

**Comment by Guite** [comment]
For the moment we can use this workaround: https://github.com/zikula/core/pull/3244

**Comment by javiereguiluz** [comment]
@Guite thanks for reporting this issue and for explain it nicely.

You are right about the "hard dependency" with GlyphIcons. However, I consider this a "feature" and not a "bug". Bootstrap 3 has this dependency and it uses Glyphicons everywhere ... and this form theme is for Bootstrap 3 only.

Bootstrap 4 dropped this dependency entirely and you are now free to use anything you want. Therefore, sadly I must recommend to close this issue as "won't fix".

**Comment by Vinorcola** [comment]
I agry with @javiereguiluz : the Bootstrap 3 theme is linked to Bootstrap 3 and therefore GlyphIcons. If you removed GlyphIcons from Bootstrap, you should create your own form theme.

This theme is just a helper for Bootstrap integration ;)
