### ISSUE TITLE
Cannot close debug bar after update to 3.2

### ISSUE THREAD

**Issue by helfd** [symfony/symfony#20754]
After the update from Symfony 3.1 to 3.2 i cannot close the Symfony debug bar with the [X] button anymore.
The problem occurs in Firefox 50.0.2 on Xubuntu 14.04 64 Bit. 
The Firefox console shows a javascript error on click "ReferenceError: event is not defined".
When i use Chromium 53 the close button works as expected, i tested this behavior with an existing and a fresh 3.2 project.

**Comment by alsar** [comment]
This was already fixed: https://github.com/symfony/symfony/pull/20717
