### ISSUE TITLE
ChoiceValidator trigger error

### ISSUE THREAD

**Issue by pengend** [symfony/symfony#20779]
In ChoiceValidator.php, an error is triggered when the options strict is false
`
        if (false === $constraint->strict) {
            @trigger_error('Setting the strict option of the Choice constraint to false is deprecated since version 3.2 and will be removed in 4.0.', E_USER_DEPRECATED);
        }
`

But the option is set to false by default in Choice.php
`
    public $strict = false;
`

**Comment by Simperfit** [comment]
As settled in the [UPGRADE-3.2.md](https://github.com/symfony/symfony/blob/master/UPGRADE-3.2.md#validator), I think this is intended because it will change in 4.0.

@nicolas-grekas, did I understand that wrongly ?

**Comment by pengend** [comment]
@Simperfit  If this is indended, `strict` option becomes necessary for every choice annotation, not  very convenient if bridge is enabled...

**Comment by Simperfit** [comment]
@pengend I found the PR, you can check it to understand the goal of this deprecation : #19257

**Comment by peterrehm** [comment]
@pengend This was the only way to properly switch over to a strict handling which is what you want in general.
