### ISSUE TITLE
Feature request: Show service definition location in debug output

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#20776]
Hey folks. I want to add the suggestion to show an more detailed `debug:container` output. It would be great to see WHERE a service was defined.

# How it currently works
`php bin/console debug:container validator`

Output:

```
------------------ ----------------------------------------------------------
  Option             Value
 ------------------ ----------------------------------------------------------
  Service ID         validator
  Class              Symfony\Component\Validator\Validator\ValidatorInterface
  Tags               -
  Public             yes
  Synthetic          no
  Lazy               no
  Shared             yes
  Abstract           no
  Autowired          no
  Autowiring Types   -
  Factory Service    validator.builder
  Factory Method     getValidator
 ------------------ ----------------------------------------------------------
```

# Proposed Change
`php bin/console debug:container validator`

Output:

```
------------------ ----------------------------------------------------------
  Option             Value
 ------------------ ----------------------------------------------------------
  Service ID         validator
  Class              Symfony\Component\Validator\Validator\ValidatorInterface
  Tags               -
  Public             yes
  Synthetic          no
  Lazy               no
  Shared             yes
  Abstract           no
  Autowired          no
  Autowiring Types   -
  Factory Service    validator.builder
  Factory Method     getValidator
  Location           path\to\symfony\src\Symfony\Bundle\FrameworkBundle\Resources\config\validator.xml
 ------------------ ----------------------------------------------------------
```

It would be easier to inspect and override existing definitions.

**Comment by stof** [comment]
there is no way to display this:
- loaders don't store this info in the Definition
- definitions can be altered in many places (for instance by compiler passes) and so are not defined in a single place.

**Comment by javiereguiluz** [comment]
@dsentker although your proposal is legit, I'm afraid that we must close it as "won't fix" because, as explained by @stof, it's not technically possible to implement it. In any case, thanks for proposing improvements for Symfony and please, keep doing that. Thanks!

**Comment by ogizanagi** [comment]
Adding this information to the Definition from the file loaders would not be hard, though.

But it's probably not worth it. Using the PhpStorm Symfony plugin, you're already able to jump to a service definition from a class, and I don't think it has much usefulness to add this information in the debug output.
