### ISSUE TITLE
[FrameworkBundle] Don't seed cache pool namespaces with kernel debug

### ISSUE THREAD

**Issue by Sander-Toonen** [symfony/symfony#20780]
I was wondering whether there was a specific reason to include ``kernel.debug`` in the cache pool namespace seed. Imho setting/unsetting the debug flag should not have an effect on the workings of a program. 

https://github.com/symfony/symfony/pull/18544 added the ``kernel.name``, ``kernel.root_dir``, ``kernel.environment`` and ``kernel.debug`` to the cache pool namespace. 

Consider this scenario:
A user has a website that displays values from a database which are cached. A worker (console command) updates values in the database and busts the corresponding cache keys. In order to find a problem in the worker, the user wants to log some more details and restarts the workers without the ``--no-debug`` flag. Now suddenly, the cache isn't busted anymore and no information gets updated on the UI.

I would therefore suggest removing ``kernel.debug`` from the cache pool seed.

**Comment by nicolas-grekas** [comment]
> I would therefore suggest removing kernel.name from the cache pool seed.

I guess you mean kernel.debug. Please open PR (against on 3.1?) so that we can discuss that there. Looks fine to me. Please also open one against DoctrineCacheBundle since it has the same issue since https://github.com/doctrine/DoctrineCacheBundle/pull/105

**Comment by Sander-Toonen** [comment]
@nicolas-grekas Oops, yes. I changed it.

Ok. I will.
