### ISSUE TITLE
[Form] How to know with certaintity if $form->getData() returns valid data?

### ISSUE THREAD

**Issue by Isinlor** [symfony/symfony#20784]
[Submitted and disabled form is always valid.](https://github.com/symfony/form/blob/master/Form.php#L724) So in the situation:
```
    if ($form->isSubmitted() && $form->isValid()) {
        $data = $from->getData();
        // handle data ...
    }
```

Is it expected that code depending on `$form->getData()` is able to handle [complete lack of data](https://github.com/symfony/form/blob/master/Form.php#L506) even if the from is valid? Or should I always check that form is not disabled? So instead recommended `if ($form->isSubmitted() && $form->isValid()) {` default to `if ($form->isSubmitted() && $form->isValid() && !$from->isDisabled()) {`?

@edit I'm asking the question because I saw deprecation of calling `$form->isValid()` when the form is not submitted, but the issue mentioned above bothers me much more. I'm curious if I'm missing something or the part  `if ($this->isDisabled()) { return true; }` should be removed from there (or at least better documented).

**Comment by HeahDude** [comment]
@Isinlor Why a disabled form should be invalid?

A disabled form is always (virtually) submitted so it is validated. I don't really get your point here.

**Comment by Isinlor** [comment]
The code here https://github.com/symfony/form/blob/master/Form.php#L506 is ignoring submitted data and isValid method will consider the data valid even if it does not contain required values etc. therefore code depending on `$from->getData();` to be without errors can fail if form is disabled and still submitted for some reason. It did happen to me when user submitted the same form twice from the same page. The form was supposed to be disabled and not submitable after the first time, but because the submits were consecutive without the page refresh it did not stop the user.

**Comment by stof** [comment]
@Isinlor a disabled form does not let the user submit a new value for the field (a browser is not even required to post the value for a ``<input disabled>``).
If the data is invalid when the form is disabled, it means that your data was invalid before creating the form (and so you already have corrupted data)

**Comment by Isinlor** [comment]
@stof The submitted data is valid on the first time then becomes invalid and the form is disabled. But if user have open the form in the other tab or someone else did open the not disabled form at the same time before the first submit then the data submitted second time are invalid.

**Comment by HeahDude** [comment]
>The submitted data is valid on the first time then becomes invalid and the form is disabled

This doesn't make any sense.

It looks like you have a race condition, so I can't see how the framework could fix your issue.

**Comment by Isinlor** [comment]
Yes, it is a sort of race condition and the fix is simple check `if ($form->isSubmitted() && $form->isValid() && **!$from->isDisabled()**) {` before handling the data, but it is not nice gotcha, since `$form->isValid()` is effectively laying to me. That's what I'm trying to point out.

**Comment by HeahDude** [comment]
Solving this race condition by checking it this way looks very fragile. But I don't think the component should support this case.

The form should not be responsible for validating the model pre set data, one can use the validator directly.

Anyway even in that case, if the view send some outdated data in a disabled field it will hydrate the model data. So maybe you could just unmap that field using the option `'mapped' => false` on it.

**Comment by Isinlor** [comment]
I'm not sure if we are on the same page. The problem is not lack of validation of pre set data, but submitted data.

The documentation of `isDisabled` method is saying that `The validation of modified disabled forms should fail.`:

```
    /**
     * Returns whether this form is disabled.
     *
     * The content of a disabled form is displayed, but not allowed to be
     * modified. The validation of modified disabled forms should fail.
     *
     * Forms whose parents are disabled are considered disabled regardless of
     * their own state.
     *
     * @return bool
     */
    public function isDisabled();
```

but implementation of `isValid()` method will never fail:
```
    public function isValid()
    {
        if (!$this->submitted) {
            return false;
        }

        if ($this->isDisabled()) {
            return true;
        }

        if (count($this->getErrors(true)) > 0) {
            return false;
        }

        return true;
    }
```

**Comment by HeahDude** [comment]
I understand the confusion, but the component considers the field as submitted without actually submitting it (ref https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L508), thus it considers it validated without considering the actual validation.

I'm not sure how we should handle this, and without breaking BC.

**Comment by Isinlor** [comment]
I was thinking that this BC could be introduced [alongside of the deprecation of calling `isValid` without submitting the form for Symfony 4.0](https://github.com/symfony/form/blob/master/Form.php#L727). Seems like there will be no better moment for that. In the old version it could just be better documented.

**Comment by HeahDude** [comment]
Such deprecation would be triggered internally, https://github.com/symfony/form/blob/master/Form.php#L767.

**Comment by MetalArend** [comment]
Maybe we should also deprecate a call to isValid in the case of a disabled form field?

I would also think that a disabled form field can never be submitted anyway, and if would have been submitted nonetheless, that would be a breach of contract that should trigger an error.

**Comment by xabbuh** [comment]
closing in favour of #27217
