### ISSUE TITLE
[FrameworkBundle][Translation] Don't add Translation into DI when it is disabled in Config

### ISSUE THREAD

**Issue by BPScott** [symfony/symfony#20791]
More of request for comments rater than a "hey this is certainly a bug"...

Using Symfony 3.2 I have disabled translation, validation and form in my [FrameworkBundle config](http://symfony.com/doc/current/reference/configuration/framework.html) as I do not require these items in my application (it's a JSON API). I have confirmed this by running `app/console debug:config FrameworkBundle` and noting that those three items all state `enabled: false`.

When I run `app/console debug:container` I note that the form and validator services are now absent, however translation services are still registered. This is particularly annoying as there are 28 of them.

Is it possible for the translate service config to not be loaded if it (and everything that depends upon it) has been disabled in the config?

Looking at [the extension config](https://github.com/symfony/symfony/blob/e7658492152b8f097c5bfaa9ed0facc93633a9ed/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L87-L96) I note that forms require translation. Perhaps this could be reworked in a similar manner to [the validation registration](https://github.com/symfony/symfony/blob/e7658492152b8f097c5bfaa9ed0facc93633a9ed/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L136-L144) so that it is only forced to load if the form component is also enabled.

**Comment by javiereguiluz** [comment]
👍 

This goes along changes like the one we introduced recently in FrameExtraBundle to not enable unnecessary things: https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/427

**Comment by xabbuh** [comment]
see #20928 for a first attempt to clean this up a bit
