### ISSUE TITLE
[ClassLoader] Link to Composer documentation (when that part is finished there)

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#20804]
Instead of mentioning the `composer install --apcu-autoloader` command in the deprecations introduced in #20777 we should link to the (to be written) documentation about this (see composer/composer#5947 for the related Composer issue).

**Comment by javiereguiluz** [comment]
I'm closing this because ClassLoader is deprecated entirely. I've opened https://github.com/symfony/symfony-docs/issues/7533 in case we want to link to that article in the docs.
