### ISSUE TITLE
[HttpKernel] Irritating behaviour when automatic cache warmup fails

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony#20803]
When running with an empty cache (after deleting the cache, after creation, while? running "[ab]??/console cache:clear"), warmUp of cache_warmer service is called automatically in [Symfony\Component\HttpKernel\Kernel::initializeContainer](../blob/a4edafbd7d82ccea983f04ade3dc220e72f340e2/src/Symfony/Component/HttpKernel/Kernel.php#L496) (for dev environment). When the warmup fails, the cache is seen as initialized anyway. This results in console commands failing 1x after clearing the cache and passing thereafter (example in [1]). (Also loading the first page fails in a different way than a thereafter [if no console command is run before].)

Should this commands pass in the 1st run (and warn about a failing cache warmup), or should they keep failing? The answer depends on whether the cache needs  to be warmed up.

Tested with 2.8.12, 2.8.14, Symfony 3.2.0

[1] search for "Interesting thing" in #19589

**Comment by SimonHeimberg** [comment]
There is a note about warmup failing here: http://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer

**Comment by nicolas-grekas** [comment]
warming up when clearing the cache is deprecated as of 3.3, I think we can close this one.
