### ISSUE TITLE
D.I. is ignoring parent service definition if in yml file

### ISSUE THREAD

**Issue by Pherserk** [symfony/symfony#20819]
I have this issue, but I'm following documentation guidelines.
http://stackoverflow.com/questions/41020396/invalid-argument-key-nameoftheargument-found-symfony3-extending-an-abstract-s

what am I wrong?

**Comment by javiereguiluz** [comment]
@Pherserk in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, it's better to keep using any of the support alternatives shown in http://symfony.com/support By the way, your question on StackOverflow already got answered. Thanks!
