### ISSUE TITLE
ControllerResolver::getArguments is no longer called

### ISSUE THREAD

**Issue by fxOne** [symfony/symfony#20822]
I'm currently upgrading my Symfony 3.0 Project to 3.2 and wondering why my implementation of [`ControllerResolver::getArguments`](https://github.com/symfony/http-kernel/blob/master/Controller/ControllerResolver.php#L101) is no longer get called. 

As far as i can see the issue is the change from [`$arguments = $this->resolver->getArguments($request, $controller);`](https://github.com/symfony/http-kernel/blob/v3.0.9/HttpKernel.php#L141) to [`$arguments = $this->argumentResolver->getArguments($request, $controller);`](https://github.com/symfony/http-kernel/blob/v3.2.0/HttpKernel.php#L145) in the `HttpKernel::handleRaw()` method.

In the [UPGRADE-3.1 documentation](https://github.com/symfony/symfony/blob/master/UPGRADE-3.1.md#httpkernel) i can only find the notice that `ControllerResolver::getArguments()` is deprecate, not that the call is removed.

**Comment by ogizanagi** [comment]
As states the UPGRADE-3.1 file:

> The `ControllerResolver::getArguments()` method has been deprecated and will
    be removed in 4.0. If you have your own `ControllerResolverInterface`
    implementation, you should inject either an `ArgumentResolverInterface`
    instance or the new `ArgumentResolver` in the `HttpKernel`.

You should inject an instance of `ArgumentResolverInterface` in the `HttpKernel`. 
But simply setting this argument to `null` will use your controller resolver as before.
However, it still looks like a BC break, because using the framework bundle, the `HttpKernel::__construct()` `$argumentResolver` argument is always wired.

**Comment by fxOne** [comment]
In the case that I overwrite the `http_kernel` service definition to set the last parameter to null you should remark that i also must overwrite the `debug.controller_resolver` service definition to set the `$argumentResolver` to `null` if i want to use the Symfony debug environment.

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. 

@fxOne Please leave a reply when you can provide some steps to reproduce your issue and we can consider to reopen.
