### ISSUE TITLE
phpunit file assumed as infected malware on shared server hosting

### ISSUE THREAD

**Issue by adityarai** [symfony/symfony#20821]
Reason for the port block

During our regular scans, we have found malicious files in your account which may be infected with malware. 
Here is the list of files our scanning has identified :

/home/nadiarafl/public_html/osandbox/ledgerbook/vendor/symfony/symfony/phpunit
Please clean up files listed above using virus/malware scanners. DO NOT delete the files directly as they may be important for your website to function. Kindly consult your/plugin developer before deleting and ensure that you have a backup on your local computer.

Note: In most cases, deleting these files may not be sufficient. You may have to delete the infected theme/plugin and reinstall to the latest version of CMS to fix the issue permanently after the port is unblocked.

Unblocking the port

Once all the files are cleaned, please press 'Unblock Port' button given below. Our scanners will scan the account 
in the next few hours and unblock the port if all files have been cleaned.

**Comment by fabpot** [comment]
Not sure what this is about, but this has nothing to do with Symfony. Your scanner gives you a false positive apparently.
