### ISSUE TITLE
Key "type_class" for array with keys "id, name, view_vars, children" does not exist in @WebProfiler/Collector/form.html.twig at line 460.

### ISSUE THREAD

**Issue by dsmink** [symfony/symfony#20823]
Is this issue related to: [Exception after 3.2 upgrade #20698](https://github.com/symfony/symfony/issues/20698) ?

The issue occurs opening the Form panel in the Profiler.

**Comment by nicolas-grekas** [comment]
If you're on 3.2.0, the fix should be already merged in the 3.2 branch and 3.2.1 will be OK.
If you're on the latest commit on the 3.2 branch, the please provide a reproducer.
