### ISSUE TITLE
how to run symfony in my share host

### ISSUE THREAD

**Issue by golpesareirooni** [symfony/symfony#20848]
hi
i copied all symfony's folders and files in my host.
then import my database in phpmyadmin's host.
but nothing show, just my favicon!
how can i resolve this problem?
and how can check requirement of my symfony?

**Comment by javiereguiluz** [comment]
@golpesareirooni in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

By the way, this article should answer all your questions --> http://symfony.com/doc/current/setup.html
