### ISSUE TITLE
[CI] [PHP7.1] fabbot.io wants space after nullable parameter type

### ISSUE THREAD

**Issue by kubawerlos** [symfony/symfony#20846]
```
diff -ru Tests/EventListener/Fixture/FooControllerNullableParameter.php Tests/EventListener/Fixture/FooControllerNullableParameter.php
--- Tests/EventListener/Fixture/FooControllerNullableParameter.php	2016-12-09 11:06:50.340035350 +0000
+++ Tests/EventListener/Fixture/FooControllerNullableParameter.php	2016-12-09 11:06:51.615996047 +0000
@@ -12,7 +12,7 @@
     {
     }
 
-    public function nullableParamAction(?\DateTime $param)
+    public function nullableParamAction(? \DateTime $param)
     {
     }
 }
```
http://fabbot.io/patch/sensiolabs/SensioFrameworkExtraBundle/445/e4c023dda3c6a5966b18256f97ae12e5979b5006/cs.diff

**Comment by stof** [comment]
should be reported to PHP-CS-Fixer.

this repository is not about developing fabbot.io

**Comment by kubawerlos** [comment]
@stof PHP-CS-Fixer doesn't seem to have problem with this.

**Comment by stof** [comment]
well, then maybe fabbot.io needs to update its PHP-CS-Fixer version. But anyway, this repo is not where it is maintained.

**Comment by kubawerlos** [comment]
Any place to report it?

**Comment by tucksaun** [comment]
Hello @kubawerlos.
This should be fixed when fabbot will use PHP-CS-Fixer 2.
I'm working on it so it should be there soon :)
