### ISSUE TITLE
[RFC][DependencyInjection] Deprecate Definition::get/setFile() to be removed in 4.0

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#20864]
The DependencyInjection component allows to require a file before instantiating a service. This feature is documented on the `Definition` page: https://symfony.com/doc/current/service_container/definitions.html#requiring-files.

```yml
services:
    foo:
        file: '%kernel.root_dir%/../file_to_include.php'
        class: Foo
```

or 

```php
$definition->setFile('%kernel.root_dir%/../file_to_include.php');
```

Will generate using the PhpDumper:

```php
    protected function getFooService()
    {
        require_once ($this->targetDirs[3].'/app/../file_to_include.php');

        return $this->services['foo'] = new \Foo();
    }
```

This feature exists since the very beginning (https://github.com/symfony/symfony/commit/65d075016888e202cc20c9710800512caec77811) and is part of an API that has hardly ever changed.

I never used it myself and I think I've never seen anyone using it neither (_**not saying it's a reason enough to remove it**_).

I wonder which were the use-cases (_probably for compatibility with old non-autoloadable libraries_), if they are still relevant and if advocating better solutions (if it exists for the use-cases) by removing this entirely isn't better?

---

Some resources:

- https://symfony.com/doc/current/service_container/definitions.html#requiring-files
- http://stackoverflow.com/questions/10816930/how-to-include-a-file-class-in-symfony2
- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Definition.php#L411-L433

**Comment by iltar** [comment]
So I learned something new today! I think this comes from a pre-PSR autoloading era. Personally I have no problems with this being removed.

**Comment by chalasr** [comment]
Same here, I never seen this anywhere and I would be curious to see a use case where the need is not solvable through autoloading. 

👍  burninate it!

**Comment by Simperfit** [comment]
Never seen that either ;). 

Remove it ! :p

**Comment by jvasseur** [comment]
I'm a bit :-1: for removing it, I never used it but i see a valid use case for it : requiring a generated php file (a service could be generated from some configuration and dumped as a php class). Such a case could not be easily handled by the composer autoloader.

**Comment by fabpot** [comment]
👎 for removing this. I agree that this is probably the most useful feature of the DI component, but I don't understand why we should remove it.
