### ISSUE TITLE
[Cache] Zend OPcache seems to be disabled, can't compile file

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#20878]
I'm running Symfony 3.2 on a PHP 7.1 server with Opcache enabled for FPM but not for CLI.

Every time we deploy, this errors gets logged to Sentry:

```
Symfony\Component\Debug\Exception\FatalErrorException: Zend OPcache seems to be disabled, can't compile file
#1 /vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/PhpFilesAdapter.php(118): null
#0 Hautelook\SentryClient\ErrorHandler(null): Hautelook\SentryClient\ErrorHandler::handleFatalError
```

I think this is due the fact that I have `opcache.enable_cli => Off`. Since the warmup command runs on CLI, it will never work.

Maybe it would be good if the PHPFilesAdapter checks this configuration first, before trying to save it?

**Comment by nicolas-grekas** [comment]
Do you have xdebug.scream enabled?

**Comment by nicolas-grekas** [comment]
would you like to submit a PR?

**Comment by ruudk** [comment]
I'll debug further and try a PR :)

**Comment by ruudk** [comment]
I don't have xdebug installed. So its not related to `xdebug.scream`.

**Comment by ruudk** [comment]
Added PR https://github.com/symfony/symfony/pull/20883
