### ISSUE TITLE
[Var-Dumper] improve search-ability of data

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#20873]
Using the var-dumper component in a debugging tool that outputs multiple (deserialized) JSON documents via the var-dumper. Generally as long as the data structures are not expanded they are not searchable via the browser search. Using ctrl+click, I can expand one dump at a time.

It would be nice if there would be some way to output input fields to easily search across individual dumps as well as all dumps. Ideally without having to expand the content fully. When searching like this, ideally the tree should expand to show and highlight the matched items.

**Comment by lyrixx** [comment]
I usually, use the following syntax: `dump([$obj1, $obj2, $obj3])` and then I click on the root node and finally use the ctrl+click feature on the root node to expend everything.

**Comment by lsmith77** [comment]
FYI

I created my own twig function (which basically just removed the ``isDebug()`` check as I am using this not for debugging during development but instead I am using it to create a tool for debugging product data and the state of a product in different systems.

as such I put the data into a table to be able to see the state side by side.

so my use case goes beyond what is currently covered via the ``dump()`` twig function.

**Comment by nicolas-grekas** [comment]
Do achieve this experience, someone needs to write more JS in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L123

**Comment by lsmith77** [comment]
yeah .. I mostly opened the ticket to see if there is interest in adding such functionality .. maybe I can entice someone with javascript skills then to implement it.

**Comment by ogizanagi** [comment]
I started something yesterday about searching nodes in the HtmlDumper output, but there is nothing more than UI for now: https://github.com/ogizanagi/symfony/commit/b811a1670870161b57cd26efa80364ec229972de

I don't know at all if this is easily achievable, nor if my JS skills are good enough. 😅

**Comment by lsmith77** [comment]
@ogizanagi maybe create a WIP PR and reference this ticket?

**Comment by ogizanagi** [comment]
@lsmith77: I wanted to make it functional before. See #21109 :)
