### ISSUE TITLE
[DependencyInjection] Use current class as default class for factory declarations

### ISSUE THREAD

**Issue by lstrojny** [symfony/symfony#20888]
Assume this config:
```xml
<service class="SomeClass">
    <factory method="create"/>
</service>
```

I would expect this to call `SomeClass::create()`. Instead it dies with this error:

```
Cannot dump definition because of invalid class name ('')
```

Any reason to not use the current class as the default class for a factory declaration.

**Comment by ogizanagi** [comment]
It actually makes sense to me 👍 

See #20943
