### ISSUE TITLE
HEAD request becomes GET when using AppCache in prod environment

### ISSUE THREAD

**Issue by mangelsnc** [symfony/symfony#20893]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.14

I have an API endpoint in my project which uses the HEAD method. When I'm in `dev` mode, everything works as expected, but when I switch to `prod` environment, all the requests are transformed to `GET`.

The main difference between this environments is that `prod` has cache enabled, and as far as I know, the class `HttpCache` is the [responsable of this change](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L420).

I'm not sure if it's a bug or my mistake in some configuration, I'm pretty sure that I'm not the first who make a `HEAD` request with the cache enabled.

**Comment by dmaicher** [comment]
Yes that is the current behaviour. Varnish for example also has this behaviour by default as far as I know.

So your API Endpoint needs to be aware if the request is a HEAD or GET request?

**Comment by xabbuh** [comment]
@mangelsnc Can you elaborate why it matters to your API endpoint whether the request method is HEAD or GET?

**Comment by mangelsnc** [comment]
Hi to everyone,

It's a really common pattern use the HEAD method for example to check the existence of a resource without return itself in the body of the response, to avoid heavy load responses in many cases.

For example:

```
[GET] /api/users/17b9cd455468ead91af14de08de0914c
```

In case the UUID exists, it will return an status code 200 with an entire user resource in the body, and a status code 404 in the other case. But these response can be a really heavy one to only check the existence of the user and here is where it's useful to take advantage of the HEAD method.

If you use:

```
[HEAD] /api/users/17b9cd455468ead91af14de08de0914c
```

You only has as response the headers, including the status code which is the only you need to check the existence of the resource.

**Comment by dmaicher** [comment]
I understand. In this case I would propose to have a new config option for the HttpCache `head_method_passthrough` (or whatever name :smile: ) so you can change this default behaviour if you want? Not sure we should change the behaviour completely as it sometimes makes more sense to just pass in a GET to have one cached version to serve for GET & HEAD requests to increase the hit-rate.

@xabbuh what do you think? I could look into it and create a PR for it.

**Comment by dmaicher** [comment]
I added the option here: https://github.com/symfony/symfony/compare/master...dmaicher:http_cache_method_head_passthrough?expand=1

@xabbuh would this be considered a bugfix? Wondering which target branch I should choose for a PR :yum:

**Comment by xabbuh** [comment]
@dmaicher IMO that clearly would be a new feature (i.e. it would have to target the `master` branch).

**Comment by dmaicher** [comment]
@xabbuh ok I thought so too :wink:

**Comment by dmaicher** [comment]
So the PR was closed :wink: I guess this means we won't be able to provide a fix for this issue.

**Comment by fabpot** [comment]
Actually, in the related PR, some way to change the default behavior is described.
