### ISSUE TITLE
[Console] improving input with validation & transformation

### ISSUE THREAD

**Issue by ReDnAxE** [symfony/symfony#20899]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

While learning the console component workflow, I noticed that (afaik) there is no validation, neither transformation in console input system.

- Transformation : Could we improve console input with adding possibility to add transformers for each argument/option definition ?
Ex: adding a custom `ClosureTransformer`
Ex 2: adding a pre-developed `DoctrineTransformer`, which will e.g. translate "43" value in User instance (like paramConverter in controllers).

- Validation (less important imo) : Could we improve console input with adding possibility to add validation constraints for each argument/option definition (using validator component) ?
Ex: adding new `Email()` constraint (like in forms)
Ex: adding new `Type('\DateTime')` constraint (need transformations implementation)

What do you think about those 2 propositions ? Can I propose 1 or 2 PR ?

Imo there is no reason to let developers to code this logic in `Command::execute` method, right ?

**Comment by ogizanagi** [comment]
This feature request make me think about this package: https://github.com/matthiasnoback/symfony-console-form

I don't know if something similar should be in the core.
Regarding validation, you're already able to validate anything with the validator component. The transformation part could be interesting, but for common commands looks too edgy to me. You usually don't require that much work inside your command.

**Comment by xabbuh** [comment]
The Doctrine transformer could be interesting for many users. However, would your code really be more readable/shorter/whatever compared to manually getting the repository and calling one of its methods? So not sure it's really worth adding something like this to the core.

**Comment by ReDnAxE** [comment]
@ogizanagi I didn't know the [symfony-console-form](https://github.com/matthiasnoback/symfony-console-form) package, interesting.
@xabbuh I think it depends of the implementation.. But Perhaps it is utopist to propose annotation system in commands like with paramConverters in controllers ^^.

In fact I was inspired while using the small Node.JS library [posix-argv-parser](https://github.com/busterjs/posix-argv-parser), which propose both validators and transformers.
Even in a small project, I rapidly took advantages of transformers.

**Comment by chalasr** [comment]
Resolving command argument/options has been rejected in #23902, let's close here.
