### ISSUE TITLE
[Process] Implement Expects

### ISSUE THREAD

**Issue by alexbowers** [symfony/symfony#20898]
| Q                | A
| ---------------- | -----
| Feature request? | yes

In linux, there is an `expect` command, which can be setup to deal with interactive programs.

Currently, in symfony there is no way to handle this.

Having the ability to setup `expects` and have them resolve using symfony would be very useful.

I'm willing to implement this, if it is something that would be considered by the community for merging.

**Comment by jakzal** [comment]
@alexbowers thanks for taking your time to make this suggestion! I'm not familiar with the `expect` command. Would you mind explaining a use case for this kind of functionality in the Process component?

**Comment by alexbowers** [comment]
Expect is used to "listen" to a commends output and upon a match, perform
some action.

A common use case is to automate inputs in bash, for example, filling in a
password, a path etc.

This exists in python as pexpects, ansible as expects, bash as expects.

**Comment by alexbowers** [comment]
Here are some examples of it in python

https://github.com/pexpect/pexpect/tree/master/examples

**Comment by nicolas-grekas** [comment]
Not sure what that would mean. What's missing? What's expected?
@alexbowers would you be able to work on this one?

**Comment by alexbowers** [comment]
I had a quick look into it, but wasn't able to figure it out.

I may be able to spend a little more time on it.

What is desired is how the `expect` command works.

What this allows is for you to effectively use Symfony to type input into another command that is running within Symfony.

This is useful for typing in passwords, choosing configuration options where flags aren't available, etc.

You basically would tell it to wait for an output, and respond with some input.

**Comment by alexbowers** [comment]
The basic syntax I was thinking was:

```php
<?php

$cmd = new Process("...");
$cmd->expect("Enter your password:", env("password"));
$cmd->run();
```

This would cause the command to read the output per line, and when it see's "Enter your password:" then it will put the value from the second argument and "press enter".

I can't figure out how to do this unfortunately.

How do we read output, and how can we pass input in?

**Comment by alexbowers** [comment]
I can see that in some way I need to be able to call `pipes->write` but, I can't figure out how to best structure that.

**Comment by nicolas-grekas** [comment]
Closing as this is not something we should do in core IMHO.
