### ISSUE TITLE
FormExtension 

### ISSUE THREAD

**Issue by roji430** [symfony/symfony#20908]
Fatal error: Uncaught InvalidArgumentException: Passing any arguments the constructor of Symfony\Bridge\Twig\Extension\FormExtension is reserved for internal use.
`$renderer=new TwigRenderer($formEngine,$csrfManager);
// add the FormExtension to Twig
$twig->addExtension(
    new FormExtension($renderer)
`);````

**Comment by xabbuh** [comment]
The exception was fixed fix in 3.2.1 which was released today. However, we didn't update the documentation yet (see symfony/symfony-docs#7242). Though I still need to close here as this is no issue in the code, but just a missing documentation update.
