### ISSUE TITLE
[Security][Ldap] how to authenticate via LDAP bind with DNs differentiated by more than username

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#20905]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

I am implementing LDAP authentication using ``form_ldap_bind`` which supports the ``search_dn`` configuration option to dynamically generate the DN to use for the ``ldap_bind()`` check.

However in my case the DN's differentiate on more than the username for different users:
``uid=foo,ou=External,ou=Employees,dc=example,dc=com`` vs. ``uid=bar,ou=Internal,ou=Employees,dc=example,dc=com``

The ``LdapUserProvider`` in turn supports searching for users but then requires a password attribute to validate the authentication which isn't available in my case. ``LdapBindAuthenticationProvider`` also does not support a filter parameter (which might be useful here, but I am not an LDAP expert).

I wonder if we need another auth provider which is more flexible to find the relevant DN from the LDAP server before attempting to validate the password via ``ldap_bind()`` along the lines of:
```
ldapsearch -d 1 -w 'XXX' -H ldaps://example.com:636 -D "uid=sys,ou=Accounts,dc=example,dc=com" -b 'dc=example,dc=com' '(uid=foo)' dn
```

**Comment by lsmith77** [comment]
@csarrazi do you have some advice here?

**Comment by csarrazi** [comment]
Duplicate of #16823.

@lsmith77 The user provider can be used along with the form_ldap_bind mechanism, in which case the password attribute should not be set. The password attribute should *only* be used if you are using LDAP to fetch users, but perform password comparison within the application.

To solve your problem, you should create your own authentication provider, based on SimpleFormAuthenticator, and perform an LDAP search here to retrieve the user's DN, and use it to bind to the LDAP server.

Keep in mind that you should not rely on the `isBound()` getter to check whether the user is bound or not, but instead rely on the exception thrown by the `bind()` statement.
`isBound()` will only tell you that the connection was bound at least once, but you won't know who is the currently bound user. You may actually be bound to the server anonymously or with a search user.

Basically, just make sure that you explicitly bind with the search user first (or perform the anonymous bind), and then only perform the bind as the user with the found DN.

```php
try {
    $ldap->bind(); // or $ldap->bind($searchDn, $searchPassword);
} catch (ConnectionException $e) {
    throw new BadCredentialsException('Could not connect to server');
}
try {
    res = $ldap->query($dn, $query, $options)->execute();
    
    if (1 !== count($res)) {
        throw BadCredentialsException('Could not find user or query matched more than 1 user');
    }

    $entry = $res[0];

    $ldap->bind($entry->getDn(), $password);
} catch (ConnectionException $e) {
    throw new BadCredentialsException('Bad password');
} catch (LdapException $e) {
    throw new BadCredentialsException('Bad query');
}
```

Then you can use the user provider to search after trying to bind to the server. If you want to be able to use the user fetched by the user provider, then you would need to make sure that your username is set to be the full DN, and thus, you would need to override the user provider also.

**Comment by lsmith77** [comment]
thx

**Comment by lsmith77** [comment]
see https://github.com/symfony/symfony/pull/21402
