### ISSUE TITLE
[Cache] PhpArrayAdapter logs error on initialize of non-existent file

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#20901]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.2.1

Just installed 3.2.1 on PHP 7.1 in production and got the following error logged to Sentry:

```
Symfony\Component\Debug\Exception\FatalErrorException: include(): Failed opening '/home/ticketswap/app/releases/20161213142627/app/cache/prod/annotations.php' for inclusion (include_path='.:/usr/share/php')
#1 /vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php(331): null
#0 Hautelook\SentryClient\ErrorHandler(null): Hautelook\SentryClient\ErrorHandler::handleFatalError
```

I had a similar issue in the PR I submitted yesterday https://github.com/symfony/symfony/pull/20883. That issue is now gone, but the next issue arises. 

The issue is with this code:
https://github.com/symfony/symfony/blob/d27d4459597f52c437cea4688b623cc0b190bc5e/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php#L331

```php
    /**
     * Load the cache file.
     */
    private function initialize()
    {
        $this->values = @(include $this->file) ?: array();
    }
```

The error suppression still triggers an error (in PHP 7.1 with `error_reporting = E_ALL`). 

Isn't it better to first check if the file exists?

**Comment by nicolas-grekas** [comment]
I'd first like to understand why error suppression doesn't work as expected... Can you please inspect it?

**Comment by ruudk** [comment]
I spend some time trying to debug the issue:

* I cannot reproduce this locally when running `--env=prod cache:warmup --no-debug`
* Checked error_reporting related settings with production server, they are the same
* Disabled xdebug on my development machine, without any result.
* I check the documentation about error suppression and found that Sentry does handle this scenario correctly. It checks `error_reporting()` before it proceeds.

The only difference I can imagine is NewRelic that is active on the production server. I will try to install that on my development machine to see if that makes any difference.

**Comment by ruudk** [comment]
Ok, I found the root cause for this issue. It's definitely related to Hautelook's SentryClient. 

It registers a [shutdown procedure](https://github.com/hautelook/sentry-client/blob/4807c277e802d00cec263e13e34256c2a376efc8/src/Hautelook/SentryClient/ErrorHandler.php#L45) and then retrieves [error_get_last()](https://github.com/hautelook/sentry-client/blob/4807c277e802d00cec263e13e34256c2a376efc8/src/Hautelook/SentryClient/ErrorHandler.php#L88) and submits it to Sentry.

Since `error_get_last` always returns the last error, no matter the error was suppressed or not, this caused my issue.
