### ISSUE TITLE
Disable DataCollectionTranslator when kernel.debug == false

### ISSUE THREAD

**Issue by maximium** [symfony/symfony#20918]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.14

Hello, I believe the translator shouldn't be wrapped with DataCollectorTranslator in prod env here 
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L349
suppose this will work
$this->translationConfigEnabled = $container->getParameter('kernel.debug');
at
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L815

I have an out of memory issue when make thousands of translations in command.

**Comment by stof** [comment]
@maximium the line 349 is called only when the profiler is enabled. In prod, you should not enable the profiler at all. and if you enable it in non-debug mode, we do need to register the collector, otherwise we still cannot profile things.

**Comment by maximium** [comment]
It's really so I missed it. My apologizes and thanks for the help
