### ISSUE TITLE
Feature #11993 is poorly documented and exposed

### ISSUE THREAD

**Issue by ABM-Dan** [symfony/symfony#20912]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3..1.8

I was trying to implement a custom authentication success handler, and it took me quite a bit to identify how to inject the options, the fact that it's based on the existence of a setOptions method is rather opaque.

Can we have an interface that is implemented by official handlers exposing setOptions?

**Comment by ABM-Dan** [comment]
This might be a duplicate of #4258 .

**Comment by xabbuh** [comment]
Thank you for reporting this @ABM-Dan. As this is about the documentation of the introduced feature I moved your issue to the documentation repository (see symfony/symfony-docs#7989).
