### ISSUE TITLE
Avoid phpunit 5.6 warnings on getMock in AbstractConstraintValidatorTest

### ISSUE THREAD

**Issue by ste93cry** [symfony/symfony#20913]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7+

Trying to use PHPUnit 5.6 on Symfony 2.7+ results in a lot of deprecation warnings if the base class of the test is `AbstractConstraintValidatorTest`. The PR #19129 was merged to fix the same issue, however the change has been applied against the class `ConstraintValidatorTestCase` which is available since Symfony 3.2. I could provide a PR for the 2.7+ branches, if needed.

**Comment by xabbuh** [comment]
The `AbstractConstraintValidatorTest` class is part of the Symfony testsuite and is not meant to be reusable. The `ConstraintValidatorTestCase` serves this purpose and as you said was already updated in #19129. Thus, there's nothing to do here. That's why I am closing this issue.

**Comment by ste93cry** [comment]
As fair as I understand from the [UPGRADE](https://github.com/symfony/symfony/blob/e938361cf71f78ae5affd454debfca24c31a3cd7/UPGRADE-3.2.md) file that class was indeed meant to be reusable, but it was in a "wrong namespace" and got refactored into the new `ConstraintValidatorTestCase`.

**Comment by sstok** [comment]
You can fix this, but it is a hack.
https://github.com/rollerworks/PasswordStrengthBundle/pull/69

Symfony 2.7's API is stable so it shouldn't break 👍

**Comment by ste93cry** [comment]
Sure, thanks for the hint. However as explained below I still think that that class was meant to be reusable, so it should be definitely be fixed

**Comment by xabbuh** [comment]
@ste93cry The good news is that #20984 will update all tests.

**Comment by ste93cry** [comment]
Nice, thank you!
