### ISSUE TITLE
Return Host in AppKernel ?

### ISSUE THREAD

**Issue by yuioppooh** [symfony/symfony#20919]
Hello,

I do not understand why insight sensiolabs returns a "Method Request :: createFromGlobals should not be used" error on using the code below in the AppKernel file.

```php
<?php
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\HttpFoundation\Request;

class AppKernel extends Kernel
{
    private $host;

    /**
     * Constructor.
     *
     * @param string $environment The environment
     * @param bool   $debug       Whether to enable debugging or not
     */
    public function __construct($environment, $debug)
    {
        parent::__construct($environment, $debug);

        $request = Request::createFromGlobals();
        $this->host = $request->server->get('HTTP_HOST');
    }

   // ...
}
```

How to recover the host in the kernel file properly in this case knowing that $ _SERVER ['HTTP_HOST'], is not allowed either?

Thank you !

**Comment by stof** [comment]
Why do you need the host in the AppKernel constructor ? This breaks several things:

- a kernel might be used to process several request (which might have different hosts if your webserver allows several ones). Even though a PHP-FPM usage will generally process a single request in the process, this won't be the case in tests when using WebTestCase
- the kernel is also instantiated in non-HTTP contexts (the CLI uses it too for instance)

**Comment by yuioppooh** [comment]
Thanks for your quick response!

I use the host to define the proper parameter file and to separate log files.
The goal is to have several sites (domain) but with the same core.

Here is an example always in the AppKernel file:
```
public function getCacheDir()
    {
        if (!empty($this->host))
            return $this->getRootDir().'/../var/cache/'.$this->host.'/'.$this->environment;
        else
            return parent::getCacheDir();
    }

    public function getLogDir()
    {
        if (!empty($this->host))
            return $this->getRootDir().'/../var/logs/'.$this->host;
        else
            return parent::getLogDir();
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        if(!empty($this->host))
            $loader->load($this->getRootDir().'/config/'.$this->host.'/parameters.yml');
        else
            $loader->load($this->getRootDir().'/config/parameters_default.yml');

        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }
```

**Comment by arnaspet** [comment]
what about environments ? would it fix your problems ?

**Comment by yuioppooh** [comment]
Sorry I did not understand what you meant?

**Comment by lyrixx** [comment]
@yuioppooh you should inject your dependencies:

```
// web/app.php

use Symfony\Component\HttpFoundation\Request;

require __DIR__.'/../app/autoload.php';

$request = Request::createFromGlobals();
$kernel = new AppKernel('prod', false, $request->server->get('HTTP_HOST'));
```

and 

```php
// app/AppKernel.php
<?php

use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    private $host;

    public function __construct($environment, $debug, $host = null)
    {
        parent::__construct($environment, $debug);
        
        $this->host = $host;
    }
```

**Comment by yuioppooh** [comment]
Thanks for your reply, I had thought about this method but I saw that some command in files in the vendor directory uses the call to the current kernel. So it will not work anymore for the console commands ...

**Comment by mvrhov** [comment]
For the cli you should pick up the host from the cli.. env
and then you run the app/console like this `HOST=example.com app/console`

**Comment by lyrixx** [comment]
> Thanks for your reply, I had thought about this method but I saw that some command in files in the vendor directory uses the call to the current kernel. So it will not work anymore for the console commands

I don't see the issue, it *is* the current kernel. Can you show me an example?

**Comment by jakzal** [comment]
Closing since lyrixx have already given a solution to this problem and there's no further feedback from the reporter.

**Comment by martin-programming** [comment]
> Thanks for your reply, I had thought about this method but I saw that some command in files in the vendor directory uses the call to the current kernel. So it will not work anymore for the console commands ...

Just run this in the shell:  export SERVER_NAME=<your_domain> and then you can use the bin/console commands with no problems.
