### ISSUE TITLE
Bug when attempting to edit the current logged user

### ISSUE THREAD

**Issue by ShinDarth** [symfony/symfony#20920]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.0

Assuming that there is a page to edit users. If we try to edit the current logged user **AND** the form submission will fail (e.g. when a field validation fails, like wrong password/repeat password combination) **THEN** the current logged user token will be modified according to the submitted data of the form.

See also: http://stackoverflow.com/questions/27024424/editing-user-with-error-wrongly-changes-the-app-user-username-temporarily-how-t

**Comment by stof** [comment]
Well, if your User object used in the auth system is the same than the one being edited, there is nothing we can do here, as you mutate the object you gave to Symfony.
Btw, this is the reason why the EntityUserProvider reloads the user by primary key, not by username.

**Comment by ShinDarth** [comment]
isn't there a way to prevent the passed object to be mutated in case that the form validation fails?

**Comment by xabbuh** [comment]
@ShinDarth Validation happens after the form data has been bound to the underlying object. So there's no way to handle that. But you can use a DTO for the form instead of mapping it directly to your entity.

**Comment by jakzal** [comment]
Closing since, as explained by others, there's nothing we can do about this.
