### ISSUE TITLE
[Validation] GroupSequence and validation groups should work together

### ISSUE THREAD

**Issue by shinab** [symfony/symfony#20929]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

Mixing GroupSequence and validation_groups should be working as it say in PR #10287

For now, GroupSequence alone is working as expected, but when validation_groups is added, validation does not fail on first error.

Forked version here : https://github.com/shinab/symfony-standard

**Test scenario**
Put a dot in the field and valid

With current implementation, validation should fail directly after **group3**, but it passed thougt **group2** and **group1** too.

If you comment validation_groups in _MyEntityType_, validation fail after **group1** as expected.

**Comment by xabbuh** [comment]
@shinab Can you confirm that #20975 fixes your issue?

**Comment by shinab** [comment]
Yeap, it's all good to me 👍

**Comment by mindaugasvcs** [comment]
How to use GroupSequence and validation groups together when I have mapped and not mapped form fields? I have to validate non mapped fields only when mapped fields pass validation.
