### ISSUE TITLE
[Config] Provide shorthand methods for ArrayNodeDefinition::prototype()

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#20921]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

[ArrayNodeDefinition::prototype()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php#L77) returns a `NodeDefinition`. However in reality it returns an `IntegerNodeDefinition`, `ArrayNodeDefinition` and so on.

This makes the last line of the following code `->max(10)` not recognizable by IDEs and with a bit TreeBuilder is can become annoying
````
$node = new ArrayNodeDefinition('name');
$node
    ->prototype('integer')
    ->max(10);
````

I propose to provide shorthand methods for the standard node types (variable, scalar, boolean, integer, float, array, enum)

So the previous snippet could be written as
````
$node = new ArrayNodeDefinition('name');
$node
    ->prototypeInteger()
    ->max(10);
````
As a result, your IDE will recognize that it returns `NumericNodeDefinition` and can *follow* the call.

**Comment by arnaspet** [comment]
I think it's too much verbosity. 100 lines of code only for ide support is too much.
also i guess if you really want ide supportm you could do phpDoc like this
```php
    /**
     * Sets a prototype for child nodes.
     *
     * @param string $type the type of node
     *
     * @return IntergerDefinition|ArrayDefinition| ScalarNodeDefinition // you get the point
     */
    public function prototype($type)
    {
...

```
but again, you would need to support those comments, if any `NodeDefinition` class would be created, you would forget to update this comment
