### ISSUE TITLE
Error: Call to undefined method createMock()

### ISSUE THREAD

**Issue by GCalmels** [symfony/symfony#20948]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 2.8.15

I tried to test a FormType with invalid_message and I followed the [doc](http://symfony.com/doc/2.8/form/unit_testing.html#adding-custom-extensions) for adding extensions.

I got this error :
```
Error: Call to undefined method AppBundle\Test\Form\Type\AlertTypeTest::createMock()

...AppBundle/Tests/Form/Type/AlertTypeTest.php:18
...vendor/symfony/symfony/src/Symfony/Component/Form/Test/FormIntegrationTestCase.php:30
...vendor/symfony/symfony/src/Symfony/Component/Form/Test/TypeTestCase.php:31
```  

And if I change createMock by getMock, I had an other error :
`Call to a member function addConstraint() on null`

**Comment by xabbuh** [comment]
How did you run the tests? Did you use the `simple-phpunit` script from the PhpUnitBridge? Or did you use a standalone installation of PHPUnit? If so, which version of PHPUnit do you have installed?

**Comment by GCalmels** [comment]
I use PHPUnitBridge v2.8.15 but I don't use `simple-phpunit` just `phpunit -c` and the version of PHPUnit is 5.3.4

**Comment by iltar** [comment]
When you're in the root of the project, execute `./phpunit` and it will run the tests with the right version. `createMock` is added in a more recent version of phpunit.

**Comment by GCalmels** [comment]
Well, in the root of my project, I don't have any `./phpunit`
Can I change the version of phpunit from PHPUnitBridge?

**Comment by iltar** [comment]
My bad, I was under the impression you were testing the Symfony project. You need this command: `./bin/simple-phpunit`

**Comment by GCalmels** [comment]
Sorry but I don't have any `simple-phpunit`...

**Comment by iltar** [comment]
Then you don't have the phpunit-bridge installed and thus you should probably update your local phpunit in order to use this feature of the tests, or install the phpunit bridge of course.

To do so, require the `symfony/phpunit-bridge` and configure your `bin-dir` in composer.json (under extra)

**Comment by stof** [comment]
Well, the Symfony doc uses the API added in PHPUnit 5.4+ rather than the deprecated ``getMock`` one. If you use an older PHPunit version (note that the current version is 5.7), you should adapt things to use the older API.

**Comment by stof** [comment]
@iltar using the bridge would not help here, because it does not use PHPUnit 5.4+ yet (due to the Symfony testsuite not being upgraded yet)

**Comment by iltar** [comment]
Wait, so Symfony is providing code to test with `createMock`, but can't test this itself?

**Comment by GCalmels** [comment]
Ok! I only have to upgrade `phpunit` to use createMock! Sorry, but now I have the second error : `Call to a member function addConstraint() on null`

**Comment by xabbuh** [comment]
@iltar Symfony itself doesn't make use of `createMock()` yet. It's just the documentation where we at some point made changes that are incompatible with PHPUnit < 5.4.

**Comment by rifzy** [comment]
so you mean that for example, symfony 2.8 and phpunit 5.4 are incompatible ?
what is the highest version of phpunit i can use with symfony 2.8 ? @xabbuh

**Comment by stof** [comment]
@rifzy no, he said that the example shown **in the doc** requires PHPUnit 5.4+ (which btw means that 5.4 itself is supported).
The recommended version of PHPUnit is 5.7 though (5.4 is quite old).

Symfony 2.8 should even be compatible with PHPUnit 6 (except the PHPUnit bridge. You need to install 3.3+ for PHPUnit 6 support. but it is meant to be installed separately anyway)

**Comment by xabbuh** [comment]
By the way, I opened symfony/symfony-docs#7869 to explain this in the documentation.
