### ISSUE TITLE
[3.2] The service "validator.builder" has a dependency on a non-existent service "translator"

### ISSUE THREAD

**Issue by yannickl88** [symfony/symfony#20949]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

I'm trying to create an as minimal project using the symfony components as possible. However, the  framework bundle seems to require the translation bundle without explicitly stating this in the composer.json.

My requires:
```json
{
    "require": {
        "guzzlehttp/guzzle":             "^6.2",
        "sensio/framework-extra-bundle": "^3.0",
        "symfony/framework-bundle":      "^3.2",
        "symfony/monolog-bundle":        "^3.0",
        "symfony/security-bundle":       "^3.2"
    },
}
```
Issue code: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.xml#L23

**Comment by iltar** [comment]
Relates to #15714

**Comment by xabbuh** [comment]
@yannickl88 Can you please check if #20928 improves your situation?

**Comment by yannickl88** [comment]
@xabbuh not really, I get a better error though. "Validator support cannot be enabled as the Translation component is not installed." Which seems to say a lot more then before.

However, this does not solve my problem that I want to use the validation without the translator component.

**Comment by stof** [comment]
@yannickl88 but you cannot, this is the whole point. The validator component needs to translate messages.
Btw, this makes me think that the Validator component should probably require the Translation component.

**Comment by xabbuh** [comment]
@stof In theory, you could build the validator without using the `ValidatorBuilder` and use your own implementation of the `ExecutionContextFactoryInterface`. Though that's probably not a common use case.

**Comment by yannickl88** [comment]
@stof I find that a bit of an odd dependency. Why should I need a translator to validate stuff?

**Comment by iltar** [comment]
As I've suggested once before, would be nice if the validator component contains its own translator interface. You can then simply create a non-translating-adapter and a symfony translator adapter. This makes it easier to use in non-symfony applications as well where you already have a translator. Yay for setter injection though...

**Comment by xabbuh** [comment]
Okay, the issue is not the missing dependency on the Translation component for the Validator component (in fact it is present: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/composer.json#L21). However, you just can enable the `framework.validation` without actually checking that the Validator component is installed (see #20957 for the fix).

**Comment by yannickl88** [comment]
that is odd, I was searching my lock for `symfony/translation` and could not find it... yet it's very plainly a dependency of the `symfony/validator`.

**Comment by xabbuh** [comment]
@yannickl88 Are you sure that the `symfony/validator` package is installed then?

**Comment by yannickl88** [comment]
With the above require list I do not get `symfony/translation` nor do I get 'symfony/validator`. Which might explain why the translator is missing.

But that makes the error even more confusing. How can I enable something which is missing and not get an Error telling me to install the validation component?

**Comment by xabbuh** [comment]
@yannickl88 I agree that this is indeed confusing. That's why I proposed #20957 which should provide a more meaningful error message. Could you please test that patch?
