### ISSUE TITLE
Error FormTypeTest : Call to a member function addConstraint() on null

### ISSUE THREAD

**Issue by GCalmels** [symfony/symfony#20952]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 2.8.15

I followed the [doc](http://symfony.com/doc/current/form/unit_testing.html#adding-custom-extensions) for adding custom extensions and I had an error at `new ValidatorExtension($this->validator),` 

The cause of this error is on the `_construct` of ValidatorExtension.php : 
`$metadata = $validator->getMetadataFor('Symfony\Component\Form\Form');`
and after :
`$metadata->addConstraint(new Form());` but $metadata is null

**Comment by xabbuh** [comment]
@GCalmels I think that's an issue with the example provided in the documentation, but not related to the Symfony code. Can open a new issue on the [docs repository](https://github.com/symfony/symfony-docs)?

**Comment by GCalmels** [comment]
Well, do you know the valid example? Yes, I will open a new issue!

**Comment by xabbuh** [comment]
The mocked `ValidatorInterface` would have to return a valid constraint (and you will probably have to mock some more stuff). Though not completely sure if that's really the best way to go or if we shouldn't rewrite the whole example.

**Comment by GCalmels** [comment]
I post the solution I found :
```php
protected function getExtensions()
    {
        $this->validator = $this->createMock(ValidatorInterface::class);
        $this->validator
            ->method('validate')
            ->will($this->returnValue(new ConstraintViolationList()));
        $this->validator
            ->method('getMetadataFor')
            ->will($this->returnValue(new ClassMetadata('Symfony\Component\Form\Form')));

        return array(
            new ValidatorExtension($this->validator)
        );
    }
```

**Comment by xabbuh** [comment]
@GCalmels Thank you! Can you please also add this as a comment to symfony/symfony-docs#7270.
