### ISSUE TITLE
AbstractAdapter of symfony/cache uses a colon which is against PSR-6

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#20950]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | Not sure
| Symfony version  | 3.2

Hello,

We recently made an update and we noticed inside our Redis Cache the following record

    mynamespace.:key

The expected one one should be ``mynamespace.key``

We recently switched from colon to dot in order to be compatible with PSR-6. [Check here](http://www.php-fig.org/psr/psr-6/#definitions) check the key section.

It seems that the line affecting us is [this one](https://github.com/symfony/cache/blob/master/Adapter/AbstractAdapter.php#L43)

**Comment by nicolas-grekas** [comment]
There is no bug here: PSR-6 only tells about the key as provided through the interface. Have internally a colon is perfectly fine and desired in fact.

**Comment by gmponos** [comment]
First I believe that you shouldn't close the issue without some feedback.

Secondly if that's the case why to validate the namespace? 

https://github.com/symfony/cache/blob/master/Adapter/AbstractAdapter.php#L43
https://github.com/symfony/cache/blob/master/Adapter/AbstractAdapter.php#L411

**Comment by wouterj** [comment]
Please be aware that issues can always be reopened by maintainers.

Anyway, as @nicolas-grekas tried to explain: The rules for the id apply to the *key* of the public api. So the argument you pass to `getItem()`.

The rules do not apply for the *id* used internally to store the cache item. In this id, the colon is used to seperate namespace from key, in order to use it later on.

It is perfectly valid to store an item called `something_completely_different` internally in the adapter when storing an item with key `hello` using the public api.

**Comment by nicolas-grekas** [comment]
Sorry if I closed to fast...
As you see on the linked line, the validation happens on the outside boundary of the namespace (the part that is provider as argument).
The colon is pure internal details.

**Comment by gmponos** [comment]
I am trying to follow your points. Can you explain to me one more thing.

Shouldn't PSR  be interfaces/guidelines that help us move from one library to another without having to refactor any of your code?

So let's just mention some examples:

1. I have two applications first application uses the PSR-6 of symfony and the other application uses any other PSR-6. These two applications can't share the cache because the not-symfony application doesn't use the colon separator.
2. If I switch library I am obliged to delete my cache (generally that would be the correct thing to do when you deploy but it shouldn't be obligatory).

Generally the two examples above might not break the functionality but I believe that there is a logical break here.

Thank you by the way for your time here.

**Comment by stof** [comment]
@gmponos PSR-6 does not standardize anything about the internal storage of the implementation. It is not its goal. It is about standardizing how you use the cache in PHP.

Implementations are free to store things as they want internally (which is the goal of having an interface btw)
