### ISSUE TITLE
[Debug] service aliases

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#20955]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | dunno

I would find it would be great to have a debug command to look for all the aliases of a given service, e.g.:

```
$ bin/console debug:container:alias acme.doctrine.foo

 This service has the following aliases:
  [0 ] acme.foo.default
    [0 ] acme.foo
  [1 ] acme.foo_alias
```

WDYT?

**Comment by chalasr** [comment]
I think that being aware of all the aliases of a given service would be useful indeed, but not sure it's worth introducing a dedicated command. Instead, what about using the existing `debug:container`, maybe just adding a `Aliases` column or a `--aliases` option?

**Comment by theofidry** [comment]
I personally find a dedicated command more clear than an option. Ideally this would be something displayed in the service info, but as aliases are not a bidirectional relationship, you have to scan for all the services so I fear a performance issue there, hence a dedicated command which makes it clear that it's not trivial (as opposed to showing the service info which is "just" reading the service definition).

**Comment by nicolas-grekas** [comment]
@theofidry let's close, or implement?

**Comment by theofidry** [comment]
Before even going for an implementation this has yet to receive an approval from the core team

**Comment by nicolas-grekas** [comment]
I'm -0 for a dedicated command, as the list is already huge, and this doesn't deserve a dedicated item IMHO.

**Comment by theofidry** [comment]
IIRC now when requesting an alias service it automatically displays the service details of the aliased service. I'm perfectly fine with that I think it's pretty nice. I would just check how it works when there is a chain of aliases, I think it wouldn't be too complicated to have the chain displayed in that situation

**Comment by theofidry** [comment]
Well, for now it displays the information of the original service with a mention that the service requested is an alias for it. Maybe this could be improved by listing all the aliases there with the message but I don't have time for it atm so let's close this :)
