### ISSUE TITLE
[Console] SymfonyQuestionHelper escapes formatting in question prompts

### ISSUE THREAD

**Issue by mrmark** [symfony/symfony#20964]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes (I think?)
| RFC?             | no
| Symfony version  | 3.2.1

I'm very late to the Symfony 3 upgrade game, but in comparison to Symfony 2.8, this code behaves differently:

```php
$io = new SymfonyStyle($input, $output);
$io->confirm('Are you sure you want to <comment>something</comment>');
```

Expected output is that the word "something" has a different color, instead the output is as follows:
```
Are you sure you want to <comment>something</comment> (yes/no) [yes]:
 >
```

This is due to this [commit](https://github.com/symfony/console/commit/afaa27c2769d257f016d70c71d17d65fb8531fa3).  From the tests, it seems like the escape was added just for backslashes and not really intended to also escape formatting.

Maybe this is too late into Symfony 3 to change this behavior, but it is handy to be able to emphasize words in questions.

**Comment by chalasr** [comment]
Thank you for reporting this bug. See #20970

**Comment by chalasr** [comment]
Status: Reviewed

**Comment by mrmark** [comment]
Thanks very much for looking at this so quickly, cheers!
