### ISSUE TITLE
[WebProfilerBundle] CSP still blocks style

### ISSUE THREAD

**Issue by cs278** [symfony/symfony#20963]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

Unless I'm missing something #18568 doesn't fully fix the compatibility of the toolbar with content security policy, JS works fine but the toolbar CSS is blocked.

The reason is the CSS is injected from an XHR request and so has a different nonce than the one set in the CSP header.

A solution that works is to move the CSS into the `toolbar_js.html.twig` view.

I've prepared a branch with a few test actions to illustrate the problem:

https://github.com/symfony/symfony-standard/compare/master...cs278:broken-csp

**Comment by tgabi333** [comment]
+1

**Comment by romainneutron** [comment]
Could you please provide the violation? 
In which page?

**Comment by cs278** [comment]
@romainneutron I don't have this to hand and probably won't get chance to look at it for a few weeks.

The CSP violation appears on pages rendering the toolbar (not the profiler pages themselves) that have a `style-src: hash-/nonce-` rule, the message is nonce mismatch or something to that effect.

**Comment by romainneutron** [comment]
I just submitted a patch that solves your issue. Thanks for reporting

**Comment by cs278** [comment]
> I just submitted a patch that solves your issue. Thanks for reporting

That looks like what I did locally when testing, so should solve the problem for me.
