### ISSUE TITLE
HeaderBag::get() is not case insensitive for some locales

### ISSUE THREAD

**Issue by ausi** [symfony/symfony#20979]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

`HeaderBag::get()` doesn’t work correctly if the locale for `LC_CTYPE` is set to `tr_TR` and the header key has the letter `i` in it. The issue can be reproduced with the following unit test in [HttpFoundation/Tests/HeaderBagTest.php](https://github.com/symfony/symfony/blob/0ab662843132a4ede35a2fa7fce4e3d59c27fa15/src/Symfony/Component/HttpFoundation/Tests/HeaderBagTest.php):

```php
public function testGetWithLocale()
{
    $locale = setlocale(LC_CTYPE, 0);
    if (false === $locale) {
        $this->markTestSkipped('Your platform does not support locales.');
    }
    try {
        $requiredLocales = array('tr_TR.UTF-8', 'tr_TR.UTF8', 'tr_TR.utf-8', 'tr_TR.utf8', 'Turkish_Turkey.1254');
        if (false === setlocale(LC_CTYPE, $requiredLocales)) {
            $this->markTestSkipped('Could not set any of required locales: '.implode(', ', $requiredLocales));
        }
        $bag = new HeaderBag(array('fio' => 'bar', 'BIO' => 'bizz'));
        $this->assertEquals('bar', $bag->get('FIO'), '->get key in case insensitive uppercase');
        $this->assertEquals('bizz', $bag->get('bio'), '->get key in case insensitive lowercase');
    } finally {
        setlocale(LC_CTYPE, $locale);
    }
}
```

This test fails on PHP 7.0.14 on Debian 8.6. I tested it on the [Docker image php:7.0-cli](https://hub.docker.com/_/php/) with the `tr_TR.UTF-8` locale installed.

The cause for this bug is that `strtolower('I')` can have three different results for `tr_TR` depending on the specific locale and the operating system. It can return the `I` unchanged as uppercase, the special character `ı` or the expected lowercase `i`.

Looking through the Symfony code I found that setting the locale for `LC_NUMERIC` is supported because there is a test in the Yaml component [Yaml/Tests/InlineTest.php:96-114](https://github.com/symfony/symfony/blob/0ab662843132a4ede35a2fa7fce4e3d59c27fa15/src/Symfony/Component/Yaml/Tests/InlineTest.php#L96-L114), see #2557. But I’m not sure if setting the locale for `LC_CTYPE` is a supported configuration.

If setting the locale for `LC_CTYPE` (or `LC_ALL`) is not supported, it should be documented as a requirement I think.

**Comment by javiereguiluz** [comment]
Sadly, handling the tricky Turkish `i` letter (https://en.wikipedia.org/wiki/Dotted_and_dotless_I) is one of the hardest problem to solve in computing. You can see thousands of issues reported for any kind of application. So, I guess we could leave this as "won't fix" and recommend to not use the `i` character in headers instead of having to deal with LC_TYPE, etc.

**Comment by ausi** [comment]
`HeaderBag::get()` is probably not the only method that has issues like this. I think most usages of `strtolower()`, `strtoupper()` and `ctype_*()` are affected.

Leaving this as “won’t fix” makes sense IMO, because using `setlocale()` before every usage of these functions might be way too cumbersome.

But I would not recommend avoiding the character `i`, but instead documenting a system requirement that `LC_CTYPE` has to be set to `C`. This could also be easily added to the `bin/symfony_requirements` check I think. Do you think this system requirement would be suitable, or are there supported use cases where a different locale for `LC_CTYPE` is needed?

**Comment by fabpot** [comment]
That's indeed a very well-known issue (I made a whole talk on this in the past). Closing it as won't fix.

**Comment by ausi** [comment]
@fabpot Thanks for taking a look!

Is the official way to avoid this bug now to leave `LC_CTYPE` set to `C`? Or as @javiereguiluz said not use the `i` character?

I’d like to make a PR to the documentation to make this issue more well-known.

I couldn’t find your talk about this in the internet, do you have a link for me?

**Comment by halk** [comment]
I wished I could avoid it by not using `I`. Unfortunately this also affects HTTP headers such as Accept-Encoding. Nginx server passes them on as ACCEPT_ENCODING

**Comment by ausi** [comment]
Avoiding the `I` character in HTTP headers is not really possible as several standard headers are relying on it (e.g. `Last-Modified`, `Location`,…)

@halk I think you should instead make sure that `LC_CTYPE` set to `C` in your application (e.g. with `setlocale(LC_CTYPE, 'C');`).
