### ISSUE TITLE
[Form] Collection entry fields' required parameter is ignored

### ISSUE THREAD

**Issue by bacart** [symfony/symfony#20987]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.8

Hello.

Here is very simple `Article` form type:

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('tags', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', [
        'entry_type' => 'TagBundle\Form\Type\TagType',
        'allow_add' => true,
        'required' => true,
    ]);
}
```

The `Tag` form type is also pretty simple:

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('name', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
        'required' => true,
    ]);
}
```

Everything is ok, new tags have a `name` field which is required. But when I change the `Article` form as follows, Tag's `name` field becomes not required.

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('tags', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', [
        'entry_type' => 'TagBundle\Form\Type\TagType',
        'allow_add' => true,
        'required' => false, // The only change is here
    ]);
}
```

All the underlying fields ignore it's `required` parameter and take a parent collection's `required` setting.

**Comment by HeahDude** [comment]
Hello @bacart, this is expected, it does not make sense to have required fields nested in a compound non required field, the `required` option is always inherited by the children, overriding their own setup.

**Comment by bacart** [comment]
@HeahDude, thanks for clarification!
