### ISSUE TITLE
Nelmio CORS does not work anymore with 3.2 onwards

### ISSUE THREAD

**Issue by nico-incubiq** [symfony/symfony#20990]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

Hi,
I use Nelmio CORS bundle to add CORS to my API responses. All was good with Symfony 3.1.7, but when I updated to 3.2.0 I starter to get CORS errors everywhere.
Debugging a little I found out that the CORS bundle listens to "kernel.response" event to add its headers. But with Symfony 3.2.0, this listener is not called anymore.
Changelogs do not say anything about any related change, so I guess it really is a Symfony Bug.
Regards,
Nicolas

**Comment by xabbuh** [comment]
@nico-incubiq Thank you for the bug report. Could you please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by nico-incubiq** [comment]
Nice idea. I could not reproduce simply with the standard edition and nelmio CORS.
This issue is related to FOS HttpCache calling isMethodSafe() without any parameters, which is apparently deprecated. It seems weird though that isMethodSafe() does not return 'OPTIONS' and 'TRACE' if options are omitted. This is a BC.
Maybe you should include that change in the UPGRADE-3.2 documentation.
