### ISSUE TITLE
[YAML] Yaml::parse() does not handle empty lines in mulitline sequence elements

### ISSUE THREAD

**Issue by W0rma** [symfony/symfony#21005]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.8.15

The `Yaml::parse()` seems to have problems if an element of a sequence contains a multiline string containg an empty line:

```php
$raw = <<<YAML
---
foo:
  bar:
  - field1: value
    field2: |
      bla

      bla
      bla
YAML;

try {
    \Symfony\Component\Yaml\Yaml::parse($raw);
} catch (\Symfony\Component\Yaml\Exception\ParseException $e) {
    // Exception is thrown
    $e->getMessage();
}
```

This example results in a `ParseException` with the message `Unable to parse at line 8 (near "    bla").`.

If empty lines are used outside the sequence, `Yaml::parse()` does not throw the `Exception`. F.e. this example works fine:

```php
    $raw = <<<YAML
---
foo:
  bar:
  - field1: value
    field2: |
      bla
      bla
      bla
  bar2: |
      bla

      bla
      bla
YAML;

\Symfony\Component\Yaml\Yaml::parse($raw);

try {
    \Symfony\Component\Yaml\Yaml::parse($raw);
} catch (\Symfony\Component\Yaml\Exception\ParseException $e) {
    // Exception is thrown
    $e->getMessage();
}
```

**Comment by stof** [comment]
there is a difference between your 2 cases: in the second case, the line is not empty, but contains the indentation whitespaces like the ``bla`` lines. This may be why it works.

**Comment by W0rma** [comment]
I've updated my post. Case 2 works even if the line is empty

**Comment by xabbuh** [comment]
@W0rma Can you confirm that #21084 fixes your issue?

**Comment by W0rma** [comment]
@xabbuh Yes, issue is fixed. Thank you!
