### ISSUE TITLE
Error with Symfony\Bridge\Twig\Form\TwigRenderer

### ISSUE THREAD

**Issue by topwebstudio** [symfony/symfony#21008]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |  no
| RFC?             | yes 
| Symfony version  | 3.2, 3.3

I've made pretty minimalistic standalone example to display this error:

https://github.com/topwebstudio/symfonyform

The error which is thrown with this example:

> Fatal error: Uncaught exception 'Twig_Error_Runtime' with message 'Unable to load the "Symfony\Bridge\Twig\Form\TwigRenderer" runtime.'

**Comment by chalasr** [comment]
It looks like a BC break which has been introduced in (at least is related to) #20093.

What is needed to make it work is to create a `Twig_RuntimeLoaderInterface` implementation able to load the `TwigRenderer`, then call `Twig_Environment::addRuntimeLoader()`.  
The patch: https://github.com/topwebstudio/symfonyform/compare/master...chalasr:renderer-runtime-loader.patch

Maybe the form component (or twig bridge?) should provide and register this runtime loader?

I can submit a PR if needed.
/cc @fabpot

**Comment by nicolas-grekas** [comment]
3.2-dev or 3.2.1?
may also be a merge mistake
ping @xabbuh

**Comment by chalasr** [comment]
@nicolas-grekas Same error on 3.2.0, 3.2-dev and 3.2.1 from my side

**Comment by xabbuh** [comment]
This is indeed something that broke in #20093. The error is related to the way `csrf_token()` Twig function is registered now (see https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bridge/Twig/Extension/FormExtension.php#L81). It now requires a runtime loader to be registered that is able to load the `TwigRenderer`. 

This is only an issue when you are not using the full-stack framework as when using the TwigBundle the loading is handled by the [ContainerAwareRuntimeLoader](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/TwigBundle/ContainerAwareRuntimeLoader.php) and the [RuntimeLoaderPass](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/RuntimeLoaderPass.php).

**Comment by fabpot** [comment]
The Twig PR has been merged now and will be part of Twig 1.30.

**Comment by chalasr** [comment]
I opened https://github.com/topwebstudio/symfonyform/pull/1 on the example repository to make it uses the new runtime loader.

I think it would be good to document the upgrade path somewhere in order to close this issue.

**Comment by xabbuh** [comment]
I think we should also update the changelog file of the TwigBridge. I'll handle that after Twig 1.30 has been released (I also have a related doc issue for this in my backlog).

**Comment by chalasr** [comment]
@xabbuh  I opened #21022 before your comment, feel free to replace it. Btw, Twig 1.30 has been released

**Comment by chalasr** [comment]
I think this issue can be closed
