### ISSUE TITLE
Datepicker instead of exististent DateTime choices

### ISSUE THREAD

**Issue by koukouille** [symfony/symfony#21006]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

How can we use a DatePicker instead of the original dateTime choices? In the request, the dateTime is in array (day, month, year / hour, minute) but in single_text, we have only date and time in the request and then at the submiting of the form, i have an error : invalid value.

To override the existent DateTime i create a new type in services.

**Comment by stof** [comment]
Well, ensure that your date picker uses the right date format when filling the input field in single_text mode. By default, the format used to represent today will be ``2016-12-21``, as it is the HTML5 date format.

**Comment by koukouille** [comment]
Ok nice, thx for the response. It's works for the date. 

But for datetime, i already have the problem.
In fact i have 2 inputs text to save a date time and i think maybe he waiting one input ?

**Comment by koukouille** [comment]
Ok thank you it's work i close

**Comment by stof** [comment]
depends whether you use ``widget => single_text`` (one ``<input type=datetime>``) or ``date_widget => single_text, time_widget => single_text`` (one ``<input type=date>`` and one ``<input type=time>``)

**Comment by stof** [comment]
@koukouille why have you removed all your comments ?

**Comment by koukouille** [comment]
Yes my bad i missed click --" 
I have date_widget => single_text, time_widget => single_text.

**Comment by koukouille** [comment]
Ok it's done, just add html5 and don't use the meridian in the date thx for your help.

Have a nice day. goodbye
