### ISSUE TITLE
Memory leak in FormDataCollector

### ISSUE THREAD

**Issue by vermi0ffh** [symfony/symfony#21009]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

When using a very large number of temporary forms, the FormDataCollector goes bigger and bigger, never releasing used ram. There is no way to clean it on purpose, eventually leading to an out of memory error.

# How to reproduce

```
for($i=0; $i<10000; $i++) {
  $data = [ 'rand' => rand() ];
  $object = new RandEntity();
  $form = $this->createForm(RandFormType::class, $object);
  $form->submit($data);
}
```

There should be a way to disable quickly the FormDataCollector service (via an option in the form maybe ?)

# How I by-passed the problem

I added a compiler-pass replacing the service with an empty

```
class ChangeFormDataCollectorPass implements CompilerPassInterface
{

    /**
     * You can modify the container here before it is dumped to PHP code.
     *
     * @param ContainerBuilder $container
     */
    public function process(ContainerBuilder $container)
    {
        if ($container->hasDefinition('data_collector.form')) {
            $definition = $container->findDefinition('data_collector.form');
            $definition->setClass(EmptyFormDataCollector::class);
            $container->setDefinition('data_collector', $definition);
        }
    }
}
```

```
class EmptyFormDataCollector implements FormDataCollectorInterface
{
    /**
     * Returns the name of the collector.
     *
     * @return string The collector name
     */
    public function getName()
    {
        return 'empty_form_data_collector';
    }
    
    /**
     * Returns all collected data.
     *
     * @return array
     */
    public function getData()
    {
        return [];
    }
[...]
}
```

# Consequences
RAM usaged dropped very significantly, from > 600 Mb to 50 Mb.
No performance drop witnessed.
Form validation is working correctly.

# Not tested
I did not render the form nor created a formView. My app is console only.

**Comment by nicolas-grekas** [comment]
We could to `$this->clonerCache = array();` somewhere in `FormDataCollector`.
Could you try in e.g. `serialize` just before the return, or in `collect`?

**Comment by vermi0ffh** [comment]
I tried adding it in both functions :

```
$this->clonerCache = array();
return serialize($this->data);
```

```
public function collect(Request $request, Response $response, \Exception $exception = null)
{
    $this->clonerCache = array();
}
```

Still > 600 Mb ram, with a performance drop after 1500 forms processed.

**Comment by stof** [comment]
if your app is console-only, I suggest you to disable the profiler in FrameworkBundle, as the profiler is HTTP-only anyway. This will avoid all overhead of the data collection done for nothing.

**Comment by vermi0ffh** [comment]
It's very effective !
Memory usaged dropped to about ~30 Mb !

 Maybe the profiler should be automaticaly disabled in cli mode ? (I can try to provide a patch)

**Comment by stof** [comment]
@vermi0ffh the issue is that we cannot change the container configuration between the different SAPI automatically, because the cached container is shared between all SAPIs for a given environment (and not sharing it would forbid to have a ``cache:warmup`` command as you would have to warmup the cache using the php-fpm/mod_php SAPI)

**Comment by vermi0ffh** [comment]
I will try to think about something and come back when I'll have a solution. Thank you very much everyone for your help !
