### ISSUE TITLE
[Twig] ternary operator fails when function not defined in non executed code path

### ISSUE THREAD

**Issue by ttk** [symfony/symfony#21012]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 1.29.0

Consider this case where `value` and the `somefunction()` are undefined:
```
{% if value %}
  {{ somefunction(value) }}
{% else %}
  {{ 'hello' }}
{% endif %}
```

It will print "hello" without error.  However, if we try to rewrite the above using the ternary operator:

`{{ value ? somefunction(value) : 'hello' }}`

it fails.   After some debugging it turns out that the ternary operator doesn't like that `somefunction()` is undefined, even if it doesn't get executed in the logic.  I feel that this is a bug as it should behave the same way as the previous case using if/else.

**Comment by stof** [comment]
well, the function being undefined should always complain AFAIK, as functions are resolved at compile time (and so cannot depend on conditions)

**Comment by stof** [comment]
See https://twigfiddle.com/hoonf1 where the undefined function fail for the first case too: https://twigfiddle.com/hoonf1

**Comment by ttk** [comment]
I looked into this further to see what's going on here...and it turns out that I'm using the [js port of twig](https://github.com/twigjs/twig.js).  Apparently that version allows you to use undefined functions in the twig template and it will just skip over any line of code that are using any undefined function.  Sorry for the confusion.
