### ISSUE TITLE
http_cache directory feature

### ISSUE THREAD

**Issue by nrctkno** [symfony/symfony#21015]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.9

In production environments with high traffic could be a great feature customize the http_cache folder, maybe outside the /var/cache dir, keeping this one for framework cache files.

(sorry for my bad english)

**Comment by ro0NL** [comment]
Why do you want to keep the kernel's http cache files outside the kernel's cache directory?

In production you can just move the entire cache dir to some better location.. right?

**Comment by fabpot** [comment]
If you have a high traffic website, you should use a proper HTTP reverse proxy like Varnish.

**Comment by nrctkno** [comment]
@fabpot **I'd love to use Varnish,** but it's not possible in my current production server.

@ro0NL The goal would be to separate the content cache and the framework cached files, so if any administrator deletes an an environment's cache folder (negligently), the HTTP cached content wouldn't be affected.

I understand that conceptually this is not necessary, but perhaps it would contribute to the flexibility of the framework.

Thanks for your answers.

**Comment by ro0NL** [comment]
I think you should go with a user-land solution and hook in on [`createStore`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php#L80)

**Comment by ro0NL** [comment]
Besides' how trusty is your HTTP cache... if framework cache is actually invalidated?

**Comment by fabpot** [comment]
Or even easier, pass the cache directory explicitly when creating the CacheKernel instance.

**Comment by nrctkno** [comment]
@ro0NL @fabpot thanks a lot

**Comment by zacharyzh** [comment]
@ro0NL @fabpot 

Put http cache files in the kernel cache dir is a bad idea. It makes cache:clear command so slowly 

Strictly, HTTP caching is not a part of the framework cache. It would be better to give an option in the configuration file.

**Comment by xabbuh** [comment]
@zacharyzh You are able to pass the cache directory to the constructor of the `HttpCache` class.

**Comment by zacharyzh** [comment]
Reverse proxy should be a standard system like Varnish. It just returns the cache data to client whether the framework cache is valid or not.

In fact, the cache:clear command can not clear the Varnish data. Why not separate the reverse proxy from framework?

**Comment by zacharyzh** [comment]
I would like to document it to cookbook. But I am not good at English.

And cache:clear command will clean up the HTTP cache should be warning, execute this command in prod env should be very carefully.

**Comment by nrctkno** [comment]
Finally and as @ro0NL said, I could achieve this overriding the _AppCache_ class in _/app/AppCache.php_:

```
class AppCache extends HttpCache {

  ...

  protected function createStore() {
    return new Store($this->cacheDir ?: $this->kernel->getCacheDir() . '/../../../env/http_cache');
  }

}
```

Thank you!
