### ISSUE TITLE
UrlValidator fails on urls containing an umlaut

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#21013]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.15

The `preg_match` pattern used by the UrlValidator does not match (returns `false`) if the url contains a German umlaut, for example `http://example.org/files/viel-glück.pdf`.

Refs #10467

**Comment by ro0NL** [comment]
Not sure but given the regex from [2.8.15](https://github.com/symfony/symfony/blob/v2.8.15/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L24) your subject value seems to pass...

https://regex101.com/r/VgFNYL/1

**Comment by Guite** [comment]
Indeed, I must have done something wrong while testing this. Sorry for the trouble.
