### ISSUE TITLE
MoneyType with divisor: integer conversion leads to wrong database values

### ISSUE THREAD

**Issue by elmariachi111** [symfony/symfony#21026]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 2.8.14

http://stackoverflow.com/questions/41286474/symfony2-moneytype-with-divisor-integer-conversion-leads-to-wrong-database-valu

We're storing all our money related values as cents in our database (ODM but ORM will likely behave the same). We're using `MoneyType` to convert user facing values (12,34€) into their cents representation (1234c). The typical [float precision problem](https://www.leaseweb.com/labs/2013/06/the-php-floating-point-precision-is-wrong-by-default/) arises here: due to insufficient precision there are many cases that create rounding errors that are merely visible when debugging. `MoneyType` will convert incoming strings to floats that may be not precise ("1765" => 1764.9999999998). Things get bad as soon as you persist these values. The (integer) cast in IntType (ODM/ORM) will strip off the value's mantissa instead of rounding the value, effectively leading to writing wrong values into the database (1764 instead of 1765 when "1765" is internally 1764.9999999998).

Here's a unit test that should work from within any Symfony/container application:

```
//for better debugging: set ini_set('precision', 17); 

class PrecisionTest extends WebTestCase
{
    private function buildForm() {
        $builder = $this->getContainer()->get('form.factory')->createBuilder(FormType::class, null, []);
        $form = $builder->add('money', MoneyType::class, [
            'divisor' => 100
        ])->getForm();
        return $form;
    }

    // high-level symptom
    public function testMoneyType() {
        $form = $this->buildForm();
        $form->submit(['money' => '12,34']);

        $data = $form->getData();

        $this->assertEquals(1234, $data['money']);
        $this->assertEquals(1234, (int)$data['money']);

        $form = $this->buildForm();
        $form->submit(['money' => '17,65']);

        $data = $form->getData();

        $this->assertEquals(1765, $data['money']);
        $this->assertEquals(1765, (int)$data['money']); //fails: data[money] === 1764 
    }

    //root cause
    public function testParsedIntegerPrecision() {

        $string = "17,65";
        $transformer = new MoneyToLocalizedStringTransformer(2, false,null, 100);
        $value = $transformer->reverseTransform($string);

        $int = (integer) $value;
        $float = (float) $value;

        $this->assertEquals(1765, (float)$float);
        $this->assertEquals(1765, $int); //fails: $int === 1764
    }
}
```

might relate to https://github.com/symfony/symfony/issues/10240 and https://github.com/symfony/symfony/issues/8473

**Comment by sstok** [comment]
I would vote to remove the devisor and rounding stuff for money as this doesn't work properly and use a proper library like https://github.com/moneyphp/money.

That's what I did for RollerworksSearch after almost killing myself with this logic...
https://github.com/rollerworks/search/pull/125

**Comment by elmariachi111** [comment]
That would be a hard option and definitely raises a fat BC issue ;)

**Comment by mvrhov** [comment]
Yeah it would be a BC break, but it would solve this issue properly and probably once and for all.

**Comment by elmariachi111** [comment]
This one's fixed by https://github.com/symfony/symfony/pull/24036 ! FINALLY! Thank you so much 😘

**Comment by chalasr** [comment]
Closing then
