### ISSUE TITLE
Should we use fully qualified function calls?

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#21020]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.7.0 -> master

According [to Ocramius](https://twitter.com/Ocramius/status/811521045932949504) and [to this blog post](http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/), we can have a small performance gain (-2% according to the blog post) by simply prepending the PHP function calls with `\`.
This allows PHP to simplify the opcode by removing a check.

Do you think it's worth doing it in symfony ?

**Comment by fabpot** [comment]
We discussed that in the past and the conclusion bask then as that it was not worth it (performance wise). @jpauli What's you point of view on this?

**Comment by iltar** [comment]
To be fair, I think this is something that PHP should solve, but would imply that we most likely won't get it.

**Comment by GuilhemN** [comment]
@iltar I don't think it's doable directly in php as it would be a huge BC break (this behavior is used in  `ClockMock` for example).
PHP could propose [an alternative using declare](https://twitter.com/giveupalready/status/811557375677239296), it would be the best solution imo but it won't be available to symfony for years.

@fabpot the gain varies on every app unfortunately so it's hard to say... [Someone gained 4%](https://twitter.com/ZannaBaldwin/status/811576036097925120) (which is significant imo). I'll try to benchmark those changes on symfony to have more meaningful stats.

**Comment by nicolas-grekas** [comment]
Note that the bench should be done with opcache enabled. I don't see it on the listed pages, and the dumped opcodes are not going to be the same with opcache. We can't draw any conclusion without this info.

**Comment by GuilhemN** [comment]
@nicolas-grekas I ran it with opcache enabled and the results are similar (except for `benchNamespacedFunction`):
```console
$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```
```console
$ ~/.composer/vendor/bin/phpbench run test.php --report=aggregate
PhpBench 0.13.0. Running benchmarks.

\foo\MixedBench

    benchFqGlobalFunction         I99 P0 	[μ Mo]/r: 0.234 0.215 (μs) 	[μSD μRSD]/r: 0.028μs 11.80%
    benchGlobalFunction           I99 P0 	[μ Mo]/r: 0.240 0.218 (μs) 	[μSD μRSD]/r: 0.037μs 15.50%
    benchOverriddenFunction       I99 P0 	[μ Mo]/r: 0.244 0.222 (μs) 	[μSD μRSD]/r: 0.038μs 15.43%
    benchNamespacedFunction       I99 P0 	[μ Mo]/r: 0.235 0.222 (μs) 	[μSD μRSD]/r: 0.022μs 9.22%

4 subjects, 400 iterations, 40,000 revs, 0 rejects
(best [mean mode] worst) = 0.203 [0.238 0.219] 0.298 (μs)
⅀T: 95.292μs μSD/r 0.031μs μRSD/r: 12.989%
suite: 133a2c691ad87f05376c5855803f0ed511a79a4a, date: 2016-12-22, stime: 13:08:10
+-------------------------+---------+--------+
| subject                 | mean    | diff   |
+-------------------------+---------+--------+
| benchFqGlobalFunction   | 0.234μs | 0.00%  |
| benchGlobalFunction     | 0.240μs | +2.64% |
| benchOverriddenFunction | 0.244μs | +4.49% |
| benchNamespacedFunction | 0.235μs | +0.70% |
+-------------------------+---------+--------+
```

**Comment by jpauli** [comment]
The lookup is cached, but still needed.
On a big application performing many different function calls from namespaces, the perf could be felt.

We could add a declare() to take hand over the PHP compiler yes.

Also, I find it more logical, if one wants to call for a PHP function into a namespace, to prefix it by \.
This is how things should be done "cleanly".  The fallback has been added for BC , but you pay the price of one lookup for it.

Please note that OPCache has nothing to do in there. OPCache doesn't resolve anything further than the PHP compiler does in such cases.

**Comment by GuilhemN** [comment]
The article received [comments on reddit](https://www.reddit.com/r/PHP/comments/5jpqb3/optimizing_php_performance_by_using/), most think that this change is not worth it. I wasn't able to quantify the gain on symfony as the error margin is bigger than it (maybe one of you can try?).
So I guess we'll have to trust these comments and consider it is not significant. Waiting for an alternative such as a `declare` statement would be the best imo considering the current benchmarks we have.

**Comment by jpauli** [comment]
Agreed

**Comment by dpagini** [comment]
Hi @fabpot & @jpauli - Apologies to comment on a closed thread, and maybe the consequence of that is this comment is never seen... But if it is seen...

I am seeing the conversation above seemingly dismiss the idea/task of changing all of symfony over to to use the FQ function calls. Yet, when I look at the files in Symfony 2/3/4/etc, I find plenty of instances of PHP calls prefixed with `\`. Is there any standard around this at this point? Will you accept code in either form? Is one preferred over the other? Is that documented somewhere I might be missing... or maybe is there room to establish and document a standard?

**Comment by chalasr** [comment]
@dpagini The PHP compiler performs optimizations on some functions when they are referenced in the root namespace, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048 for the full list

**Comment by dpagini** [comment]
Thanks for the post, that helps me understand a little further. From a symfony standpoint, is there any direction that those functions MUST be prefixed? I see some PRs where it's requested they be added that way. I guess maybe my last question still stands for this... is there somewhere in Symfony this is documented, or should be documented?

**Comment by chalasr** [comment]
I would say it is not documented. 
The php-cs-fixer configuration of the Symfony codebase enables the rule enforcing the prefix for these special functions, so as a contributor the CI will fail and suggest you a patch to aumatically add the prefix where it is needed (that's fabbot). 
The place where coding standards are documented is https://symfony.com/doc/current/contributing/code/standards.html, I think an issue/PR adding a mention for this rule would be welcome.
