### ISSUE TITLE
[Cache] FilesystemAdapter checks whether the cache directory is writable

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#21024]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1

Symfony cache component is not compatible with a read-only filesystem:
https://github.com/symfony/symfony/commit/e5d6db5c6911f9884cb79bb513053b8f12c98fda#diff-fe14fffdd6799f339b2daf1045d09360R33

**Comment by 4rthem** [comment]
Still present in the 3.2 branch. I'll push the same fix next week.

**Comment by nicolas-grekas** [comment]
No need, just wait for a merger to merge 3.1 into 3.2

**Comment by 4rthem** [comment]
OK great, but the relevant code has been moved into a trait since 3.2 so please let this issue open to ensure the merge fixes my problem. Thank you!
