### ISSUE TITLE
[Console] Global "format" option for commands

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#21042]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (proposal)
| BC Break report? | no
| RFC?             | maybe
| Symfony version  | 3.3

As pointed out in http://symfony.com/blog/new-in-symfony-3-3-improved-command-descriptors:

> One of the most unknown features of the Symfony Console commands is that they can provide alternative output formats, such as XML, JSON, Markdown, etc

Actually,  there are a lot of commands providing this `format` option. All of them have a `$this->addOption()` with pretty much the same argument, and a part of the command help presenting this option (i.e. `use the --format option for getting a json output`), which is pretty much the same too (and should be).

What I propose here is to make the `format` option a generic/global one, like `ansi|no-ansi`, `quiet`... which are part of the application default options.

If a command doesn't support several formats, the default `txt` would be used and displayed in the help.
If it does, it would just have to call something like `setSupportedFormats()` e.g:

```php
protected function configure()
{
    $this->setSupportedFormats(['json', 'xml']);
   // ...
}
```

So this part of the help wouldn't have to be repeated, same for the option itself. Descriptors would make use of `$command->getSupportedFormats()` to describe the option properly.

WDYT?

**Comment by ro0NL** [comment]
Good idea :+1:

**Comment by iltar** [comment]
What about custom commands that use this option already?

**Comment by chalasr** [comment]
@iltar Good point, AFAIK it would fail actually. I'll look if we can do something for that

**Comment by fabpot** [comment]
Another remark: The way we deal with `--format` is non-generic, so it's not a generic option. We've just moved the logic in one place for convenience, but there is nothing generic on this feature.

**Comment by chalasr** [comment]
> We've just moved the logic in one place for convenience

Sure, and some commands proposing this option do not make use of this place (if we are talking about descriptors). I'm not proposing to make the behavior of this option generic but only the way we set it and describe it. What I would like to propose is to change from:

```php
protected function configure()
{
       $this
           // ...
           ->addOption('format', null, InputOption::VALUE_REQUIRED, 'The output format', 'txt');
           // ...
          setHelp(<<<EOF
...
You can also output the information in other formats by using the <comment>--format</comment> option:

  <info>php %command.full_name% --format=xml</info>
EOF
          )
    ;
}
```

to one method call:

```php
$this->setPossibleFormats(array('json', 'xml'));
```

So we could avoid repeating the first code in each command supporting this option and be consistent in its help/description.
Providing a different output depending on the value of this option would stay up to the command, not something handled globally (not realistic I think).

**Comment by ro0NL** [comment]
If it's only a `addOption` wrapper imo. it's not worth it. It should do _something_.. at least providing a descriptor for  a given, supported, format.

**Comment by xabbuh** [comment]
Wouldn't it make sense to rather use specialised `SymfonyStyle` implementations instead of descriptors. At least, that should be easier to adapt your commands then, right?

**Comment by ro0NL** [comment]
It could work.. especially for markdown-like languages. However im not sure it overrules descriptors fully.. XML is not a style but a description in that sense.

Imo. it makes no sense to procuce something generic like `<title>Foo</title>` for `$style->title('Foo')` in XML, opposed to producing `# Foo` in markdown which looks convenient.

Some thoughts, given `command --format=xml`

```php
// something should handle the format option to provide the correct style/descriptor instance
$this->style()->title('Foo'); 
$this->descriptor()->describe($domainObject);

// things should be controllable
$this->style('markdown')->title();
$this->descriptor('xml')->describe();
```

So the first issue i see.. is how do we know if we want XML/JSON with plaintext or markdown tiles? And which combinations can be made?

**Comment by chalasr** [comment]
I'm closing this issue thanks to the discussion, I think things are good as they are and that this is not worth it. The `format` option is imho definitely not a generic one and I can't imagine that it'll become.

Thanks!

**Comment by mmarton** [comment]
I see it's an old thread, but this is something I really need right now for messenger:failed:show. Combining with jq it would be really powerful tool to handle / filter / search through failed messages

**Comment by chalasr** [comment]
PR welcome to add a format option to that command.

**Comment by mmarton** [comment]
I'm too busy handling messages manually :D  

Jokes aside, I will give it a try when my time allows it.
