### ISSUE TITLE
Incompatible with php-pthreads?

### ISSUE THREAD

**Issue by xorinzor** [symfony/symfony#21048]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.0

I am writing an extension for the Pagekit CMS which utilizes several Symfony components (including the Debug component).

Recently I've been writing php-pthreads code for multithreading and whenever one of the threads ran into an error I would get this error in the "main" thread:

```
Fatal error: Uncaught Error: Cannot access private property Symfony\Component\Debug\ErrorHandler::$reservedMemory in <snip>/public/app/vendor/symfony/debug/ErrorHandler.php on line 559

Error: Cannot access private property Symfony\Component\Debug\ErrorHandler::$reservedMemory in <snip>/public/app/vendor/symfony/debug/ErrorHandler.php on line 559

Call Stack:
    0.2689    7668344   1. Symfony\Component\Debug\ErrorHandler::handleFatalError() <snip>/public/app/vendor/symfony/debug/ErrorHandler.php:0

Segmentation fault
```

Is the Symfony ErrorHandler just not compatible with php-pthreads? or should I be doing something else? (register my own errorhandler for each thread?).

All threads have full inheritance from the main thread enabled by default (ie: classes, functions, constants, etc)

Worth to note: this script is executed from CLI

**Comment by xabbuh** [comment]
The code of the Debug component doesn't look wrong to me. Maybe a full stack trace would help to isolate the issue. Though I have no experience with the pthreads extension.

**Comment by xorinzor** [comment]
@xabbuh this is the full output that PHP returns, I have xdebug installed, is there another command with additional parameters that I could run to provide more debug information for this issue?

**Comment by stof** [comment]
I suspect that this is a bug in pthreads instead. The Symfony code is valid PHP code. Can you report this to pthread as well ?

**Comment by javiereguiluz** [comment]
Let's close in favor of https://github.com/krakjoe/pthreads/issues/649 and we'll reopen if the issue is confirmed/suspected of being caused by Symfony. Thanks!
