### ISSUE TITLE
[DX] Smarter web server commands

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21040]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

### Problem

When using the `server:start` command in several apps, you must provide a free port number to avoid errors like this one:

```bash
$ ./bin/console server:start
  [OK] Web server listening on http://127.0.0.1:8000

(change to other app in other directory)

$ ./bin/console server:start
  [ERROR] A process is already listening on http://127.0.0.1:8000

$ ./bin/console server:start 127.0.0.1:8001
  [ERROR] A process is already listening on http://127.0.0.1:8001

$ ./bin/console server:start 127.0.0.1:8002
  [ERROR] A process is already listening on http://127.0.0.1:8002

  fffffuuuuuuuuuuuu !!!!
```

### Solution

If it's technically possible, I'd like the `server:start` command to look for a free port automatically. Starting from `8000`, check the following `N` ports and pick the first one available.

Same example as before:

```bash
$ ./bin/console server:start
  [OK] Web server listening on http://127.0.0.1:8000

(change to other app in other directory)

$ ./bin/console server:start
  [OK] Web server listening on http://127.0.0.1:8024
```

Depending on how fast/slow is this process, we could check 10, 100 or 1,000 ports before showing the error message.

**Comment by fabpot** [comment]
The "problem" I can see is that currently, we don't have the information about which server is running on a given port. So, when a web server is running on 8000, we don't know if this is a server for the current project or from another project. I will investigate if we can "fix" that as part of my PR decoupling the web server from framework bundle.

**Comment by javiereguiluz** [comment]
OK. I was thinking about the `isOtherServerProcessRunning()` method that calls the `fsockopen()` function. We could call that repeatedly increasing the port number until we don't get an error. (I haven't tested and I don't know if it makes sense).

**Comment by fabpot** [comment]
But then, and that's just one example, we need to store the port somewhere so that the `server:stop` command works.

**Comment by fabpot** [comment]
Working on it :)

**Comment by nicolas-grekas** [comment]
What about deprecating server:start&stop and keep only server:run? Allows having some logs right into the console.

**Comment by xabbuh** [comment]
I can imagine that auto-discovery of the next free port can cause confusion if users do not read the output carefully enough and then visit their project in the browser and do not see the expected output. What about making the new behaviour opt-in with an option like `--discover-port`?

**Comment by javiereguiluz** [comment]
@xabbuh do you really think that would be a problem? The output message is super short:

```
[OK] Web server listening on http://127.0.0.1:8024
```

Besides, don't people just click on that link to open the page in the browser?

**Comment by nicolas-grekas** [comment]
Is it that common to have a port conflict btw?
About an option to enable the auto selection, it could be eg `--port auto`. But it would look inverted to me, to have to type more to enable some auto mechanism. Typing more to disable the auto logic is what looks the normal way to me.
Another idea: add a config option so that each app can have a different default port ?

**Comment by javiereguiluz** [comment]
It happens to me all the time. Maybe it's because I work with lots of small apps simultaneously.

In my opinion, if we add an option to enable this behavior, then it's better to not implement this behavior. Remembering the name of the option and typing it would be almost the same amount of work.

**Comment by xabbuh** [comment]
Being able to configure the default port also sounds like a good idea to me. The default value could either be `8000` or `auto`.

**Comment by fabpot** [comment]
What about replacing the current `address` and `--port` options to a single argument:

```
server:run 127.0.0.1:8000
server:run 8000 # same as above
server:run 127.0.0.1 # port is 80
server:run auto # port is auto-determined starting at 8000
```

**Comment by xabbuh** [comment]
@fabpot You can already pass the port as part of the address. Though I think it indeed makes sense to unify the unit and deprecate the `--port` option.

**Comment by fabpot** [comment]
See #21039 (auto not implemented yet but easier now)
