### ISSUE TITLE
Configure DI by definition

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#21056]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

TLDR; `DI\YamlFileLoader` is practically `DI\ArrayLoader + Yaml::parse`. Lets separate those for better reuseability allowing a `PhpArrayFileLoader` just as easy.

___

Not sure it's really worth it, but would it be nice to write a configuration definition for the DI (loader) component? Integrating the config component.

Right now only XML has a real definition with XSD. But if we add a base `Loader` and `Configuration` class, i see several benefits;

- Having 1 base class that can map a normalized array to the `ContainerBuilder`. This would clean up YAML, XML loaders drastically. As they only need to supply the array in de-normalized form from file.

- All the benefits from the config component in terms of maintaining the (true) definition, normalizing and validating.

- Allow more specific/custom loaders to be added easily, for example. i really miss a `PhpFileLoader` that handles configuration from arrays, allowing serialization etc.

```php
// config.php
return [
  'parameters' => [
    'key' => 'value',
  ],
  'services' => [
    // ...
  ],
];
```

This would work for bundle configuration as well.

Any thoughts?

**Comment by stof** [comment]
A big goal of the Config component is dealing with merging of multiple configuration files together. This is not something necessary for we need for DI loaders.

And our XML and Yaml format have differences, to make them feel more native. The XML component relies on attributes in many cases where YAML cannot and so relies on "magic" conventions (references, reference behavior on error, expression arguments, etc...).
Trying to normalize to a single format before validation would actually not simplify the code at all (especially as we need to preserve BC for the existing syntax in all formats).

Thus, adding a level of abstraction would also make it harder to give meaningful error messages (as we would not have the info about the filename anymore at the time doing the validation except by wrapping it again).
So IMO it is not worth it.

For bundle configuration, PHP files are already supported, but they need to look like this (to specify the bundle):

```php
$container->loadFromExtension('twig', array('strict_variables' => true));
```

**Comment by ro0NL** [comment]
> A big goal of the Config component is dealing with merging of multiple configuration files together

Could be.. but for me the config component is mostly about definitions (and why those are important). Only merging arrays is basically as simple as `array_merge`

> This is not something necessary for we need for DI loaders.

Using config loaders means practically using a `LoaderResolver`; meaning DI loaders already benefit from multiple files support.

> And our XML and YAML format have differences
> Trying to normalize to a single format before validation would actually not simplify the code at all

The config component would exactly fix that, right? Introducing a normalized form by definition. You say providing the de-normalized form is too big a deal? With `fixXmlConfig` in mind, i only can think of some explicit attribute remapping.. and only that, not the _entire_ job.

Besides XML is the special one here. PHP arrays, YAML, and probably others mimic the true definition way simpler.

> we need to preserve BC for the existing syntax in all formats

File syntax wouldnt change? It's only normalized and validated against a certain definition. That, of course should be compatible with all implementing file formats. It should not contain language specific features, i guess.

> Thus, adding a level of abstraction would also make it harder to give meaningful error messages (as we would not have the info about the filename anymore at the time doing the validation except by wrapping it again).

> For bundle configuration, PHP files are already supported, but they need to look like this

I know and it depends on runtime. I propose support for writing "true" configuration files in PHP, something that can be serialized/parsed, ie. `return ['strict_variables' => true];`.

**Comment by ro0NL** [comment]
>  It should not contain language specific features, i guess.

That is; for sure actually. Anything not part of the (true) de-normalized form should be pre normalized in concrete loaders first.

**Comment by fabpot** [comment]
I don't get it. Which problem are you trying to solve?

**Comment by ro0NL** [comment]
I've though of this where it should go (imo.)

Basically i want to introduce a new loader in the config, a plain simple `ArrayLoader` that can validate against some definition.

```
- Config\Loader
  - Config\ArrayLoader (could utilize against a given ConfigurationInterface)
    - DI\ArrayLoader
  - Config\FileLoader
    - DI\FileLoader
      - DI\YamLoader <  DI\ArrayLoader
```

Meaning basically all loaders can cleanup, as they only need to parse the file (get the de-normalized array) and go with an `ArrayLoader` from there.

The (true) definition / handling the de-normalized array happens in a single place.

Better reuseability. I dont understand it why we _do_ have YAML, but not PHP arrays? While it's practically the same format. If we started with PHP arrays, YAML was easy :)

Implementing a `ConfigurationInterface` for the DI config is optional. But i think it eases handling the de-normalized array a lot :) again; cleaning up.

Eventually this could apply to `Router\Loader` as well.

**Comment by ro0NL** [comment]
The true issue is

> Thus, adding a level of abstraction would also make it harder to give meaningful error messages (as we would not have the info about the filename anymore at the time doing the validation except by wrapping it again).

Hence i chose for

```
- DI\FileLoader
  - DI\YamLoader <  DI\ArrayLoader
```

We maintain the inheritance tree that way, and YAML could provide the current resource as a context to the array loader, so it can provide (cosmetic) meaningful error messages.

I think it's totally doable.

**Comment by stof** [comment]
> Could be.. but for me the config component is mostly about definitions (and why those are important). Only merging arrays is basically as simple as array_merge

Only for flat arrays. Look at http://friendsofsymfony.github.io/slides/config_definition.html#1 for examples about what goes wrong with PHP deep merging (we were trying to use it before using the component, and this is what made us create the component: removing 3000 LOC used to merge and validate the SecurityBundle configuration properly, half of them being about merging)

**Comment by ro0NL** [comment]
Fine, `Config\Definition` + `Config\Loader` both are important. It's not what this is about.

See https://github.com/ro0NL/symfony/commit/f68981a9174bf634bb9e6575a14d3493d6026d6c what im thinking of. It seems to work out so far? This are baby steps to this PR;

- Standardizes `Config\Loader::import()`, aiming for a `ImportingLoaderInterface` now.
- Favoring `Config\FileLoader::setCurrentResource` over `setCurrentDir`
- `DI\FileLoader::setCurrentResource` actually handles container resource tracking, cleaning up the first things already

**Comment by ro0NL** [comment]
Imo. this is as simple as `XML > array > ContainerBuilder`. Respectively `DI\XmlFileLoader > DI\ArrayLoader`.

It really doesnt change too much... we only populate `ContainerBuilder` from a dedicated `DI\ArrayLoader`, where a concrete loader simply provides its resource.

PHP
```php
return [
   // ..
   'some_service' => new Reference('ref'), // normalized format
   'other' => '@ref', // de-normalized format
];
```
 YAML
```yml
# ...
   'other': '@ref' # only supports de-normalized format
```

XML
```xml
<!-- ... -->
  <other>
    <argument type="service">ref</argument> <!-- de-de-normalized format? -->
  </other>
```
```php
// XmlFileLoader
if ('service' === $attr['type']) {
  $denormalized['other'] = '@'.$nodeContent; // provide de-normalized format
   $denormalized['other'] = new Reference($nodeContent); // provide normalized format
}
```

Now all concrete loaders can be as simple as `$arrayLoader->load($denormalized);`.

I know it creates extra logic for XML file loader, but it currently already contains it as well. So practically i dont see the real issue (it may even be simpler to provide the de-normalized format).

**Comment by unkind** [comment]
> We specifically rejected the fact of using the YAML array syntax for a PHP array, because there is no reason to use a '@=...' magic syntax for expressions. It is much less readable than doing new Expression('...') (and avoids the need to escape @ at the beginning of strings)

Offtopic here: I'm not sure about using existing classes like `Definition` (mutable, with many getters, and factory method contains reference as plain string), if the following syntax could be accepted, I can try to reincarnate my #11953:

```php
// Since 5.6 you can "import" functions
use Symfony\Component\DependencyInjection\definition;
use Symfony\Component\DependencyInjection\reference;

return [
    'services' => [
        'connection_foo' => definition(MySqlConnection::class)
            ->factory([reference('connection_factory'), 'createConnection'])
            ->arguments([
                reference('bar'),
                '%mysql_host%' // parameter('mysql_host') ?
            ])
    ],
];
```

**Comment by ro0NL** [comment]
Practically it's still a PHP file, so you can do anything. But first things first; this is truly about bringing the de-normalized data to it lowest level, which is configuration data; so all stringish at least.

Whenever we have a clear structure handling, and loaders following responsibilities we can finetune/utilize normalization API much easier and more logical.

**Comment by ro0NL** [comment]
Having a `DI\ConfigurationInterface` is totally optional, and not the true goal. Although i think it comes with benefits.

Basically im requesting a simple `DI\ArrayLoader` here... so either i or SF can create a PHPArray loader rather easily.

I dont want to built the container in PHP, i want to configure it in PHP.

I understand @stof point here about losing file file context. But im proposing a `DI\ArrayLoader::setCurrentResource()` that forwards to `setCurrentDir` on the resolved loader, something like that. With #21062  this should work rather clear.

This could easily migrate the YAML loader, and perhaps leave XML alone :)

**Comment by nicolas-grekas** [comment]
I still don't get the problem this is going to solve.
Adding a new way to load the config needs to fit a use case.
DX wise, the current ways are really good enough.
:-1: (again, in the hope of helping everyone focus their time)

**Comment by ro0NL** [comment]
For SF it reduces complexity, for me it gives flexibility. That is better DX on both sides (how i see it at least).

But I understand YAML+FrameworkBundle+RAD is the _standard_ here. But to clarify, i use DI for practically any bootstrapping thingy and i really dont need the YAML dep all the time. 

Ill guess ill stick with current PHP loader; although (for me) doing it as PHP array would actually improve DX.

**Comment by unkind** [comment]
> Ill guess ill stick with current PHP loader; although (for me) doing it as PHP array would actually improve DX.

What stops you having a such loader? We have it in our internal project.

I see 2 issues with our custom loader though:
* we have to evolve it on our own with upgrades (but it happens rarely);
* we can't use closures as it requires some changes in `PhpDumper` to be done (and they were rejected last time I tried to push it to upstream).

**Comment by nicolas-grekas** [comment]
il

2016-12-28 13:26 GMT+01:00 unkind <notifications@github.com>:

**Comment by ro0NL** [comment]
Closing, as for now it's too far away; implementing config builders on this.

**Comment by ro0NL** [comment]
@unkind check out https://github.com/mnapoli/fluent-symfony (not sure you're involved some way.. but this is more or less what you described in https://github.com/symfony/symfony/issues/21056#issuecomment-269370499)

**Comment by unkind** [comment]
@ro0NL thanks, I saw that project. The thing is we already use something like that, I just want to see built-in support. Also it may open doors for closure factories in the core.
