### ISSUE TITLE
[PhpUnitBridge] missing ext-zip dependency

### ISSUE THREAD

**Issue by tgabi333** [symfony/symfony#21060]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.1

Running  ./bin/simple-phpunit needs the `ext-zip`extension. It [instantiates ZipArchive class](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L46]) 

But this is not documented neither checked in the code.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #21303.
