### ISSUE TITLE
Unacessible routes in prod because HEAD request becomes GET

### ISSUE THREAD

**Issue by mangelsnc** [symfony/symfony#21074]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.14

Related to #20893 issue, theres a problem when you change to `prod` environment, all the routes annotated with `@Method("HEAD")` are not accessible, because before to send it to backend, is sent a `GET` instead of a `HEAD` and that route is not configured for this method.

The only solution is to annotate it as `@Method({"HEAD", "GET"})`.

**Comment by xabbuh** [comment]
Can you explain a use case where you want routes to be accessible only by HEAD requests, but not by GET requests?

**Comment by mangelsnc** [comment]
Take for example a User resource which, among other fields, has one called `phone`.

Now think in an endpoint to check if a given phone exists in the database, something like:

`HEAD /api/users/phones/xxxxxxxxxxxxxx`.

- I don't need the entire user
- Phone is not a complex resource and the only logic response is a true or a false (Status code 200 or 404)
- I don't want identify or search users via phone
- Just wanna check if that phone exists or not.

I think is reasonable for a web framework allow these kind of behaviour, and the conversion made by the cache system it's something unexpected for a lot of clients.

I know Varnish do this the same way, but Varnish is just a reverse proxy, not an entire framework.

**Comment by javiereguiluz** [comment]
This one is tricky. The current behavior looks wrong ... but it's what Varnish does too. @mangelsnc you say that Varnish is a reverse proxy and Symfony a framework ... but we're talking about the HttpCache here ... so Symfony is just a reverse proxy in this case too.

On the other hand, even if this is what Varnish has done forever ... it's still a confusing behavior and they receive a lot of issues and PRs about that. For example, this recent one: https://github.com/varnishcache/varnish-cache/issues/2107

So, to keep providing 100% compatibility with Varnish, we should probably not change this behavior.

**Comment by nicolas-grekas** [comment]
Current behavior is also good to me, inline with HTTP semantics also.
