### ISSUE TITLE
[Config] Add ReflectionClassResource

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#21079]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| RFC?             | yes
| Symfony version  | 3.3

When one uses autowiring, the dumped container watches many source files through `FileResource` objects, thus watching the mtime of referenced files.
When one is working on a class and this class is autowired, one sufferes from a big DX penalty: the container is rebuild almost everytime the user refreshed its page.
We should enhance this.
The solution seems to be to create a `ReflectionClassResource` that not only tracks mtimes, but also all signature related reflection info of a given class (+parents), and compares a hash of this to return `isFresh` only when a change is detected there also.

Would someone like to give this a try?

**Comment by ro0NL** [comment]
Doesnt one actually expect things to invalidate, when working on a class?

I understand technically we _must_ given a changed signature, but DX-wise effectively we _should_ only when a comment changes or so... (maybe whitespace). Maybe a hash based on stripped code?

Or am i missing something?

**Comment by nicolas-grekas** [comment]
> Maybe a hash based on stripped code?

that's exactly what I mean, except that I'd not base that on stripped code, but on reflection info only.

**Comment by ro0NL** [comment]
I missed something. The updated code will of course run as usual in runtime. Pheww.

I like it :+1:

**Comment by ro0NL** [comment]
The only "problem" i see i classes that are accessed before compilation and actually used in building. Changing those wont invalidate.. but that's a bad feature anyway ;-)

**Comment by dunglas** [comment]
@weaverryan already added a similar solution some months ago: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Config/AutowireServiceResource.php

**Comment by nicolas-grekas** [comment]
Indeed, I missed that!

**Comment by ro0NL** [comment]
We should add property/return value support right?

**Comment by nicolas-grekas** [comment]
Reopening: autowiring has AutowireServiceResource, but with closure proxies, and getter injection, we're going to need a more generic mechanism.
