### ISSUE TITLE
Rename DebugAccessDecisionManager to TraceableAccessDecisionManager

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21085]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

A while ago we introduced `DebugAccessDecisionManager` to collect this information and display it in the Security panel of the Symfony Profiler. I though that `Debug + ...` was a better name than `Traceable + ...`. However, every comparable class in Symfony is called `Traceable + ...`, so we should rename `DebugAccessDecisionManager` to `TraceableAccessDecisionManager`.

This issue is an "easy pick", so it can be solved by any developer wanting to make their first contribution to Symfony. But first, let's wait and see if the Symfony Core members agree with this proposal.

**Comment by Jean85** [comment]
I would like to work on this!
Since the class is marked as `@internal`, this means that it's not a BC break, right? Or should we leave a class with that name as a deprecated alias ?

**Comment by Jean85** [comment]
The PR seems OK, and also 2 core member commented and approved there.

Should we wait for further discussion?
