### ISSUE TITLE
[Console] Required arguments not detected as such

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#21099]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.11

I've added the required argument to my command by adding this in the `configure` method of command class:

```php
$this
			->setName('search')
			->addArgument(
				'path',
				InputArgument::REQUIRED,
				'File path'
			)
			->addArgument(
				'keywords',
				InputArgument::REQUIRED,
				'Search keyword'
			)
			->addOption(
				'match-type',
				't',
				InputOption::VALUE_REQUIRED,
				'',
				'first'
			);
```

Then I invoke command like this:

```
app search path/to/file ""
```

and `keywords` argument is considered as passed, but having empty value. As a result no validation error happens and `execute` method of command is executed.

**Comment by ogizanagi** [comment]
Looks expected to me. AFAIK `InputArgument::REQUIRED` only means the argument should be present when invoking the command. Not that the value should not be empty.

Do you think supporting something like `InputArgument::REQUIRED|InputArgument::NOT_BLANK` as a new feature would make sense, though?

**Comment by wouterj** [comment]
This is indeed expected behaviour.

I would not add NOT_BLANK, we're not talking about validation constraints here, just existence of arguments. If you want to validate the arguments, use the validator component in the command or some simple constraints.

**Comment by xabbuh** [comment]
Closing here as this is indeed the expected behaviour.

**Comment by aik099** [comment]
> Closing here as this is indeed the expected behaviour.

OK. Maybe it would be best to specify `""` passing case as valid on http://symfony.com/doc/current/components/console/console_arguments.html page. Right now just from reading the docs I can't tell that required argument means argument presence is required, but value can be empty.

> If you want to validate the arguments, use the validator component in the command or some simple constraints.

@wouterj , I haven't found any examples of validation on command level. Extending `ArgvInput` just to override `validate` method doesn't seem like a good idea. Other ways to introduce application-wide validation logic change?
