### ISSUE TITLE
Form RequestHandler

### ISSUE THREAD

**Issue by roji430** [symfony/symfony#21095]
Expected argument of type "null", "Symfony\Component\HttpFoundation\Request" given in NativeRequestHandler line 56

**Comment by xabbuh** [comment]
Thank you for your bug report @roji430. However, please provide more context about when and how you experienced this issue so that we can reproduce it. Otherwise, we won't be able to help you.

**Comment by roji430** [comment]
In my controller method i created  form like this and pass request object to the handle request
`public function doActionLogin(Request $request)
    {

        $form = $this->createFormBuilder()
            ->add('task', TextType::class)
            ->add('dueDate', DateType::class)
            ->add('save', SubmitType::class, array('label' => 'Create Post'))
            ->getForm();
       
           $form->handleRequest($request);

       }
And this throw UnexpectedTypeExcpetion. Expected argument of type "null", "Symfony\Component\HttpFoundation\Request" given in NativeRequestHandler line 56

**Comment by xabbuh** [comment]
This must be related to your project setup as a default Symfony application won't use the `NativeRequestHandler`, but will use the `HttpFoundationRequestHandler`. Please fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue.

**Comment by roji430** [comment]
ok @xabbuh  let me try

**Comment by roji430** [comment]
how can i configure Symfony form to use HttpFoundationRequestHandler can u help me?

**Comment by xabbuh** [comment]
@roji430 That's the default as long as you didn't modify the `form.type_extension.form.request_handler` service (or the `form.type_extension.form.request_handler.class` parameter on Symfony versions before 3.0).

**Comment by roji430** [comment]
@xabbuh yes but from Form config i get the request handler NativeRequestHandler  i don't modify it

**Comment by xabbuh** [comment]
Well, without being able to reproduce your issue it's unfortunately impossible to help you with your problem.

**Comment by HeahDude** [comment]
@roji430 You need to register the [HttpFoundationExtension](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/HttpFoundation/Type/FormTypeHttpFoundationExtension.php) or the [FormTypeHttpFoundationExtension](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/HttpFoundation/Type/FormTypeHttpFoundationExtension.php), you can also do it by defining it as a service like done in the framework bundle, see https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/form.xml#L161.

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. 

@roji430 Please comment when you can provide some steps to reproduce your issue and we can consider to reopen.
