### ISSUE TITLE
Write an object in Session

### ISSUE THREAD

**Issue by quentincurtet** [symfony/symfony#21097]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

Hi,
In my controller i need to put an object in session (in order to use it in other action) but when i do : 
```
$session = $this->get('session');
$session->set('toto', $grids['selectLabel']);
```
I got the following error :  Serialization of 'Closure' is not allowed.

Can someone help me ?

Thanks.

**Comment by ro0NL** [comment]
You cant really put closures in the session :) it's basically runtime code.. whereas the session may try to write on disk, or a database. We need a serialized version.

You really need to get rid of the closure before writing, and re-add it or so after reading.

**Comment by quentincurtet** [comment]
Ok thank you, i process differently, i don't know if it's a good practice, i put in session every element of my object that i need.
