### ISSUE TITLE
ParameterBag::filter "convenience" check

### ISSUE THREAD

**Issue by lt** [symfony/symfony#21105]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.1 - master

`ParameterBag::filter` contains the following snippet

```php
        // Add a convenience check for arrays.
        if (is_array($value) && !isset($options['flags'])) {
            $options['flags'] = FILTER_REQUIRE_ARRAY;
        }
```

The problem here is when you request **sanitisation** of any type, but pass an array, the sanitisation succeeds returning an array rather than what you requested.

I would say that data validating as types that have not specifically been requested is actually inconvenient, contributes to bugs, and possibly even security issues.

Example:
http://whatever?q[]=shouldntReallyBeAnArray

```
// This is fine
$query = $pb->filter('q', '', FILTER_SANITIZE_STRING);

// This is not fine
funcThatWantsAStringButGoesNutsWithAnArray($query);
```

Luckily there seems to be a workaround because of that gnarly flags check.

```
$pb->filter('q', '', FILTER_SANITIZE_STRING, ['flags' => ['leading_source_of_facepalms' => 'frameworks']]);
```

Not sure what I expect to be done about this, just wanted to make a point about hidden magic being bad.

**Comment by xabbuh** [comment]
Are there really use cases where you use the `filter()` method, but do not pass any flags at all?

**Comment by lt** [comment]
@xabbuh Sure, why not, it's optional after all.

**Comment by Simperfit** [comment]
What can we do in here to fix the bug and close the issue ? @xabbuh

**Comment by fabpot** [comment]
Closing as this issue has no traction.
