### ISSUE TITLE
[DebugToolBar] Manually added FormError are not detected

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#21107]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

The Debug Tool Bar doesn't seems to catch the FormError added manually to the form after validation:

```php
if ($form->isValid()) {
    try {
        $model->doStuf();
    } catch (AnyKindOfException $e) {
        $form->get('field')->addError(new FormError('You can\'t do that!'));
    }
}
```

**Comment by patrick-mcdougle** [comment]
This is because the data is collected during the form events lifecycle which would have happened already. See the DataCollectorListener in (Symfony/Component/Form/Extension/DataCollector/EventListener/DataCollectorListener.php) Is there a reason that you can't use the validation component within the framework to do your validation for you? Then isValid will appropriately return false.

**Comment by tkleinhakisa** [comment]
When the validation requires a database select, for exemple to check if an email adress is available, there can be concurency issues if the given data has been inserted between the validation select and the insert.

**Comment by Jean85** [comment]
@tkleinhakisa you have to use the UniqueEntity validator. https://symfony.com/doc/current/reference/constraints/UniqueEntity.html

**Comment by Vinorcola** [comment]
@Jean85 Some may not use entities into their forms!

**Comment by Jean85** [comment]
Then the only secure solution is an unique index on the DB level.

**Comment by tkleinhakisa** [comment]
@Jean85 The UniqueEntity validator have exactly the problem i describe: it can return true but the insert fails due to unique index at the db level. In that case you need to catch the exception and add the error manually as @Vinorcola exemple in the first message

**Comment by Vinorcola** [comment]
To make things clear, I'm not looking for an alternative way. It's just a debugging matter, so not a big deal. I just noticed that de DebugToolBar do not detect some form error (edded manually). @patrick-mcdougle explained us why.

But this is an edge case, and furthermore, concerning debugging only. So we just have to decide if this bug worth being corrected knowing the amount of work it will need.

I don't know at all how the WebDebugToolBar work, so I can't really help on this. :(

**Comment by tkleinhakisa** [comment]
I agree with @Vinorcola 

I guess it would require to decorate the Form class to add a specific behavior to the addError method in dev mod when the toolbar is activated. It might not worth all that work for a debugging issue.

**Comment by javiereguiluz** [comment]
I agree with the last comments. The estimated complexity to fix this edge case doesn't seem like it'd be worth it. So, let's close this as "won't fix". Thanks for understanding it and for the insightful discussion!
