### ISSUE TITLE
Demo app doctrine:fixtures:load

### ISSUE THREAD

**Issue by ttnnkkrr** [symfony/symfony#21120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 1.5.9

the logins dont work on PHP 7.0.14-2+deb.sury.org~xenial+1 so i try 
```
bin/console doctrine:fixtures:load
```
I get 
>  [Doctrine\DBAL\Exception\DriverException]              
>  An exception occured in driver: could not find driver  
                                                         

                                       
>  [Doctrine\DBAL\Driver\PDOException]  
>   could not find driver                
                                       

                         
>  [PDOException]   
>  could not find driver  
                         
I am on a fresh system and just updated everything to be sure. I cant find any usefull or meaningful articles with google

**Comment by theofidry** [comment]
@ttnnkkrr did you check if you had the proper extension installed? (I guess `pdo_mysql` here)

**Comment by ttnnkkrr** [comment]
Yes actually i did.
I decided to debug oldschool and just found that what i was missing was in fact sqlite

**Comment by ttnnkkrr** [comment]
please add some detection and error handling for this

**Comment by javiereguiluz** [comment]
@ttnnkkrr thanks for reporting this issue. However, as it's related to the Symfony Demo app, I've created an issue in that other repository to fix it. See https://github.com/symfony/symfony-demo/issues/418
