### ISSUE TITLE
[TwigBundle] Twig cache warm up is not idempotent

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#21130]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Since Twig uses template path in its cache key, the latter differs when performing cache:warmup for the first or the second time. So I have to run `cache:warmup` twice in order to get all the templates generated.

At the first run, the service `templating.cache_warmer.template_paths` fills `var/cache/prod/templates.php` which contains relative paths like `__DIR__.'/../../../vendor/foo/bar/Resources/views/blabla.html.twig'`. But at this time the DI container provides a `TemplateLocator` which has no `/templates.php` cache file ([see constructor](https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php#L35)) so the `var/cache/prod/../../../` part is omitted.

It's only at the second run, when `/templates.php` exists, that we get a `TemplateLocator` using these cached paths. In this case, the final cache key is used and templates are properly generated in their final path.

**Comment by 4rthem** [comment]
Here is an ugly fix (to help understand) that refreshes the `TemplateLocator` cache:

```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php b/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php
index bf6e795..823d3db 100644
--- a/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php
+++ b/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/TemplateLocator.php
@@ -23,6 +23,7 @@ class TemplateLocator implements FileLocatorInterface
 {
     protected $locator;
     protected $cache;
+    protected $cacheDir;
 
     /**
      * Constructor.
@@ -32,6 +33,7 @@ class TemplateLocator implements FileLocatorInterface
      */
     public function __construct(FileLocatorInterface $locator, $cacheDir = null)
     {
+        $this->cacheDir = $cacheDir;
         if (null !== $cacheDir && file_exists($cache = $cacheDir.'/templates.php')) {
             $this->cache = require $cache;
         }
@@ -39,6 +41,15 @@ class TemplateLocator implements FileLocatorInterface
         $this->locator = $locator;
     }
 
+    public function forceUseCacheFile()
+    {
+        if (!file_exists($cache = $this->cacheDir.'/templates.php')) {
+            throw new \RuntimeException(sprintf('The "%s" cache file does not exists', $cache));
+        }
+
+        $this->cache = require $cache;
+    }
+
     /**
      * Returns a full path for a given file.
      *
diff --git a/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php b/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php
index 9eea901..15a14cd 100644
--- a/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php
+++ b/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php
@@ -62,6 +62,8 @@ class TemplateCacheCacheWarmer implements CacheWarmerInterface
         }
 
         $twig = $this->container->get('twig');
+        $locator = $this->container->get('templating.locator');
+        $locator->forceUseCacheFile();
 
         $templates = $this->finder->findAllTemplates();
```

**Comment by xabbuh** [comment]
Does #21237 fix your issue?

**Comment by 4rthem** [comment]
Yes, great! Thank you @nicolas-grekas, @xabbuh!
