### ISSUE TITLE
[RFC] ArgumentValueResolver for the Session (or Flashbag)

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#21159]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

### The `getFlashBag()` Issue

One constantly recurring issue, is the missing method of `getFlashBag()` in the `SessionInterface`. This leads to being unable to get the flash bag in a clean way.
 - Injection the `SessionInterface` is better than `Session`, but no `getFlashBag()` available.
 - You can get the `Session` from the `Request`, but officially this is a `SessionInterface`, so no `getFlashBag()`.
 - You can inject the `FlashBagInterface`, but this service is private and in theory shouldn't be used like this afaik.

Just to name a few issues and pull requests:
 - #20258 adding getFlashBag to SessionInterface in later 3.1.x, or 3.2.x ?
 - #11957 [Session] Changed session.flash_bag service to publicly available
 - #11279 [Session] "getFlashBag" interfacing issue
 - #11035 Update SessionInterface.php
 - #11032 Update Request.php
 - #10036 getFlashBag missing in SessionInterface
 - #5568 [HttpFoundation] [Session] SessionInterface is missing "getFlashBag" method: correct?

### Possible Solution
There are 2 solutions that might be worth looking into now that we have `ArgumentValueResolvers`. Either the `FlashBag` or `Session` could be requested via the action.

```php
class fooController
{
    public function barAction(Session $session)
    {
        $flashBag = $session->getFlashBag(); // this is now valid
    }

    public function bazAction(FlashBag $session)
    {
        // still need to do $request->getSession(); sadly
    }
}
```

Personally I'm leaning towards the `Session` type-hint. I think this would be a nice addition as the session has no real business in the Request object, but interface wise still is stateful (hence the no-constructor injection).

**Comment by fabpot** [comment]
I like the first solution the most. Injecting the Session instance makes a lot of sense to me.

**Comment by rvanlaak** [comment]
I'm a bit late with this party (as PR #21164 already is there), but injecting the `Session` makes way more sense, as you also would not inject `request->cookies`.
