### ISSUE TITLE
Incorrect variable dumps raw profiler content into web

### ISSUE THREAD

**Issue by samayo** [symfony/symfony#21170]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.2.9

Well, this could be some sort of a feature, look at this simple code I have: 

```php
    namespace AppBundle\Controller;

    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Symfony\Component\HttpFoundation\JsonResponse;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\HttpFoundation\Response;

    /**
     * @Route(
     *  "/bug/{slug}.{_format}",
     *  defaults={"_format":"html"}
     * )
     */
    public function isBug($format){
        return new Response($format);
    }
```

I am passing 'mistakenly' the undefined variable `$format` to a method, instead of `$_format`.

Now, when I go to `http://localhost/bug/anything.rss` I get to see a 724 lines of codes raw html, css, php code. It seems like the profiler just gets outputted directly into the browser. 

For those who would like to see the image result [here is one](http://4.1m.yt/ip6BquN.png)

I don't know what is causing this.

**Comment by stof** [comment]
This is not the profiler. This is the exception page (in HTML format) being returned while the browser does not treat it as HTML (and so displays the source).
This still looks weird though

**Comment by xabbuh** [comment]
@samayo Can you fork the Symfony Standard Edition and make the changes that are needed to reproduce your issue?

**Comment by samayo** [comment]
@xabbuh [Here is my fork with the changes](https://github.com/symfony/symfony-standard/compare/master...samayo:master) I tested in local and pushed it as is.

**Comment by wouterj** [comment]
I can confirm this issue with Symfony 3.2.1.

status: reviewed

**Comment by wouterj** [comment]
Ah, I got the error. I would not say this is a bug, this is completely expected behaviour:

As the `_format` route parameter is set to `rss` in this case, the response will be set to be RSS. As the exception controller doesn't support RSS, it'll simply render the default HTML response. However, it's still sent as being RSS, so the browser doesn't render it as HTML.

If you access `http://localhost/bug/anything.atom` or `http://localhost/bug/anything.html`, you'll get expected results.

I think 2 things can be done to make this more user friendly:

 1. Default to `txt` instead of `html`
 2. Or keep the default of `html`, but also sent the response as being HTML to the browser

**Comment by samayo** [comment]
I would support the second option. Whatever it is, full application path should not be displayed to visitors.

**Comment by wouterj** [comment]
> Whatever it is, full application path should not be displayed to visitors.

Please note that we're now talking about the dev environment. On the production environment (The thing your visitors will visit), another template is rendered (the `error` one instead of the `exception` one). This will hide all sensitive information.

**Comment by samayo** [comment]
Ah, I assumed it would be the same for prod as well, since it would throw an exception as well. My bad

**Comment by nicolas-grekas** [comment]
I'd be -1 for magic format conversion on the header side.
For rendering exceptions as text, there is #18722 (needs to be reviewed thought).

**Comment by javiereguiluz** [comment]
I agree with @nicolas-grekas ... let's close here to support the PR that proposes to display exceptions as plain text: #18722.
