### ISSUE TITLE
[VarDumper] Switch between occurrences using keyboard in HtmlDumper's search utility

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#21174]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

A search functionality has been added to the HtmlDumper in #21109, which is quite nice.
The current implementation make us able to switch between results through clicks on the up/down arrows (buttons):

<img src="https://cloud.githubusercontent.com/assets/2211145/21567181/4eb8013c-ceaa-11e6-8ed9-f9cb40090d55.gif" width="300" height="300" />

I think it would be even better if we could do the same by pressing <kbd>ENTER</kbd> (go to next occurrence) and <kbd>SHIFT</kbd>+<kbd>ENTER</kbd> (go to previous occurrence), like for browser's find-and-replace.

WDYT?
ping @ogizanagi

**Comment by nicolas-grekas** [comment]
arrow up/down instead?

**Comment by chalasr** [comment]
Maybe but IMHO the more it replicates the browser's behavior, better it is. Enter/shift+enter is the one I tried naturally

**Comment by ogizanagi** [comment]
I planned to add this feature and rely on the same keyboard shortcuts as when performing a search in browsers. AFAIK: <kbd>CTRL/CMD</kbd> + <kbd>shift</kbd> + <kbd>G</kbd> and add a help box somewhere.

See http://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/

**Comment by ogizanagi** [comment]
Done in #21238 with main browser shortcuts.
