### ISSUE TITLE
[TwigBundle] Attempted to call an undefined method named "getTemplateName" of class "Twig_Error_Runtime".

### ISSUE THREAD

**Issue by attila901** [symfony/symfony#21176]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  |  3.2.1, 3.1.8, 2.8.15, 2.7.22

```Twig_Error::getTemplateName``` was removed with https://github.com/twigphp/Twig/commit/b8dabf67341a0d1d5262b2dfcd99841f15f5eccc#diff-e7bace45505091def27fd3bcf8592eafL102 commit.

In ```TwigEngine::render``` function trying to call this missing function:
https://github.com/symfony/symfony/commit/9218cacf317c0df071b4c338dd4173c63922328d#diff-27458b03974dca07a87d506fcce0a522R77

Output:
```
Attempted to call an undefined method named "getTemplateName" of class "Twig_Error_Runtime".
Did you mean to call e.g. "getTemplateLine" or "setTemplateLine"?
```

/cc @nicolas-grekas

**Comment by yalg** [comment]
I've got the same error with Symfo 2.8.15 since twig 2.0 update.

This message occurs only when we use Template annotation without template name, and when there is an error in twig template. So we don't show the twig_error report.

If we give template name, it desapear, and it display the twig_error correctly.

I think that commit #9218cac for TwigEngine.php solve the problem but not merge.

**Comment by burci** [comment]
@yalg 9218cacf317c0df071b4c338dd4173c63922328d is merged into master and v3.2.1  v3.1.8 v2.8.15 v2.7.22 but not fixing the issu.

**Comment by yalg** [comment]
@burci Strange, because when I show my vendor files, I dosen't see any commit #9218cac update.

**Comment by burci** [comment]
@yalg if you open 9218cacf317c0df071b4c338dd4173c63922328d you can see the tags / branches that includes that commit, it was merged with #20831.

**Comment by yalg** [comment]
@burci thanks, and sorry, I don't know what appens, but after another composer update, it seems to be the same code (maybe forgot to refresh my remote files in IDE), but I'm ok that it's not fixing the issue

**Comment by mdzzohrabi** [comment]
I have the same issue , after composer update , in version 2.8.15

**Comment by ydomenjoud** [comment]
Dirty work-around : Replace getTemplateName by getFile on line 55 
( SF3.2.1 )

**Comment by Rezequiel** [comment]
Apparently you fixed for Symfony 2.7 only. So, why you close this issue if Symfony 3.2 still with this error?

**Comment by xabbuh** [comment]
@Rezequiel Branches are merged up to the `master` branch on a regular basis. Thus, eventually this PR will land in 3.2 before the next patch release (which will be `3.2.2`).

**Comment by Rezequiel** [comment]
@xabbuh excellent, thanks for the explanation!

**Comment by sdudziak** [comment]
Got this error for:
(composer.json):
`  "require": {
    "php": ">=5.5.9",
    "components/jquery": "^3.2",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-cache-bundle": "^1.3",
    "doctrine/orm": "^2.5",
    "fortawesome/font-awesome": "^4.7",
    "incenteev/composer-parameter-handler": "^2.1",
    "sensio/distribution-bundle": "^5.0",
    "sensio/framework-extra-bundle": "^3.0",
    "swiftmailer/swiftmailer": "^6.0",
    "symfony/assetic-bundle": "^2.8",
    "symfony/monolog-bundle": "^3.1",
    "symfony/polyfill-apcu": "^1.3",
    "symfony/swiftmailer-bundle": "^3.0",
    "symfony/symfony": "^3.3",
    "twig/twig": "^2.4",
    "zurb/foundation": "^6.3"
  },`

And as a result for `bin/phpunit` I've received:
`1) Tests\AppBundle\Controller\DefaultControllerTest::index
Error: Call to undefined method Twig_TokenStream::getFilename()

/var/www/good-kitty/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/AsseticTokenParser.php:116
/var/www/good-kitty/vendor/symfony/assetic-bundle/Twig/AsseticTokenParser.php:63
/var/www/good-kitty/vendor/twig/twig/lib/Twig/Parser.php:169
/var/www/good-kitty/vendor/twig/twig/lib/Twig/TokenParser/Block.php:38
/var/www/good-kitty/vendor/twig/twig/lib/Twig/Parser.php:169
/var/www/good-kitty/vendor/twig/twig/lib/Twig/Parser.php:82
/var/www/good-kitty/vendor/twig/twig/lib/Twig/Environment.php:512
/var/www/good-kitty/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php:38
/var/www/good-kitty/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php:59
/var/www/good-kitty/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:160
/var/www/good-kitty/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:195
/var/www/good-kitty/vendor/symfony/assetic-bundle/Routing/AsseticLoader.php:70
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:164
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:101
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:146
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:84
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php:45
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php:72
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:58
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:371
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:293
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:46
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:306
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:260
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:101
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:106
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:146
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:129
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php:61
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:131
/var/www/good-kitty/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:315
/var/www/good-kitty/tests/Functional/AppBundle/Controller/DefaultControllerTest.php:21
`

And the indexAction is almost the same as original example one (replaced for dirname function):
`
public function indexAction(Request $request) : Response
    {
        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', [
            'base_dir' => dirname($this->getParameter('kernel.root_dir') . '/..') . DIRECTORY_SEPARATOR,
        ]);
    }
`

**Comment by sdudziak** [comment]
Doh... When I reverted Twig to `^1` it becames to work fine.
