### ISSUE TITLE
Workflow component only supports twig 1.x

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#21172]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

**Comment by stof** [comment]
What is the issue with Twig 2 ?

**Comment by mvrhov** [comment]
As per require-dev it's only tested against 1.x branch

**Comment by stof** [comment]
Well, it is tested against Twig 2 when running the fullstack testsuite on Travis, so it is working already. We should just update the constraint in the component

**Comment by lyrixx** [comment]
I just opened a PR

**Comment by Codenator81** [comment]
@stof Have issues with twig 2. It not works with debug panel

**Comment by Codenator81** [comment]
Twig_Error_Syntax in exception.html.twig line 12:
Unknown "format_file_from_text" filter.

**Comment by lyrixx** [comment]
Hello @Codenator81 

It has nothing to do with the workflow component. Could you open a new issue? 

Thanks.

**Comment by Codenator81** [comment]
OK @lyrixx . Thanks
