### ISSUE TITLE
[Serializer] Can't use config files without bundle

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#21187]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

Similar to https://github.com/symfony/symfony/issues/15655 for the serializer.
Actually, the serializer configuration files must reside in a bundle to be detected e.g. `AppBundle/Resources/config/serialization`. 
On the other hand, translations files are loaded from bundles _and_ from the global `app/Resources/translations` directory. For doctrine, the path of mapping files can be configured.

Shouldn't we try to detect those configuration files in `%kernel.root_dir%/Resources/config/serialization` as well?

**Comment by ogizanagi** [comment]
There is a pending PR regarding the validator: https://github.com/symfony/symfony/pull/19086 :)

**Comment by chalasr** [comment]
@ogizanagi I totally missed them, thanks. 
Updated this to talk about the serializer only

**Comment by dunglas** [comment]
I agree it must be done for 3.3 as bundle-less app will become fist-class citizens. I can work on this.

**Comment by fabpot** [comment]
That would be great

**Comment by chalasr** [comment]
> I can work on this.

Thanks. Note that #19086 does it for the validator by adding a config option instead of only detecting some given places in `app/`, I think it makes sense as it's consistent with the doctrine configuration.

**Comment by dunglas** [comment]
I'll wait the merge of this one because most code can be factorized.

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/pull/19086 has been merged now

**Comment by chalasr** [comment]
see #21924
