### ISSUE TITLE
Too much exceptions

### ISSUE THREAD

**Issue by n-for-all** [symfony/symfony#21199]
if i pass an array of options that include any other key, this shows an exception, what for?, if the option is unknown, simply ignore or issue a warning in the logs.

![image](https://cloud.githubusercontent.com/assets/171367/21749355/a7962d2a-d5b6-11e6-971e-66ae7213cd1b.png)

slow down a little on exceptions, there is no global exception handler for symfony and neither we can control the exceptions thrown, and i don't think you will provide or rewrite half of symfony code to support error handling correctly, and currently you are over using exceptions everywhere. 
there are some cases where it is better to return false than breaking executing, like the below case for example, where i think the unknown options should be ignored and continue execution with a warning in the logger if needed, you are currently not giving us the choice, it is either that or nothing.

Currently we can't write a simple silex/symfony app without facing 20-30 exceptions, half of them should be warnings.

**Comment by xabbuh** [comment]
We throw exceptions when something goes wrong that shouldn't be ignored because ignoring it would either break your application or lead to issue that are hard to debug. Of course, if you think that there are places where we throw exceptions of which you think they shouldn't be thrown, we can discuss that from case to case. But that's not something we will change generally.

**Comment by n-for-all** [comment]
ok thanks, right now i am trying to fix this issue, either by removing the additional options before i pass them, which means i get the form registry, resolve the type, get the default options and remove the additional ones before passing the type to the builder, and i can't seem to find a way to override the options resolver, neither i can get the "form registry" from the "form factory" because it is declared as private, unless i go and override the forms, the factory and the registry just to get the options resolver.

can you add a method to return the registry or the options resolver somehow from the form factory, or if there is anyway to do that without overriding the provider, the forms and the factory?

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormFactory.php

**Comment by xabbuh** [comment]
I am not sure if I understand your use case. Why do you actually pass options that are invalid in the first place?

**Comment by n-for-all** [comment]
because there are some options that doesn't exist on some fields, like placeholder or pattern, or data-* options, which breaks the form builder, unless i override each field with these options.

**Comment by xabbuh** [comment]
So why do you pass these options to form types then that don't support them?

**Comment by n-for-all** [comment]
it is very simple, the user saves what he wants, i check the required fields, pass them to the form handler, and additional fields, i pass them to another handler to add them to the fields.

currently the forms are limited and can't be overriden easily, if i am able to override and pass my options resolver, i would be able to pass the extra fields and print the in the template.

so instead of overriding each field type, i will just pass common attributes, ignore these additional attribute from the options resolver and then print them in the field.

**Comment by xabbuh** [comment]
I don't see how this is related to how Symfony works. If you are already able to dynamically add form types to your form tree based on the user's input, you already have to decide which kind of concrete form type to add. At this step you then also have control over which options you pass to the form type.

**Comment by n-for-all** [comment]
The form must support all fields by symfony, approx 30 fields, there should be a way i get the default options from the form builder to be able to compare.

so how can i know the default fields required for each field type from the form factory or the builder?, i can't see to find a way for that, unless i go to the docs and copy each option for each field type to know the options required.

**Comment by xabbuh** [comment]
Even if you were able to retrieve all the available options, how would you proceed then? How would you determine sensible values for all the options?

**Comment by n-for-all** [comment]
i don't,  just exclude the additional options

if you go to any field:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/BirthdayType.php

you will see that the defaults is passed to the resolver, with the resolver method "getRequiredOptions" and "getDefinedOptions" you can get the options i need and required for the field to parse correctly.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/OptionsResolver/OptionsResolver.php

so once i add any field from the UI, i will check against the required fields and return an error if any is missing, if there is none missing and there is additional, i ignore the additional and use another method to parse them. (i know the additional from subtracting the defined from the submitted options), the resolver must somehow ignore the unknown fields so i can parse with another handler or i should be able to get back the options resolver and get the required options.

**Comment by wouterj** [comment]
```php
$type = $formRegistry->getType(BirthdayType::class);
$optionsResolver = new OptionsResolver();

do {
    $type->configureOptions($options);
} while (
    $type->getParent()
    && ($type = $formRegistry->getType($type->getParent()))
);

$availableOptionsForBirthdayType = $optionsResolver->getDefinedOptions();
```

**Comment by HeahDude** [comment]
Almost there ;)
```php
$inputOptions = ... // user's input
$guessedTypeClass = ... // based on user's input

$type = $formRegistry->getType($guessedTypeClass);

$availableOptions = array_flip($type->getOptionsResolver()->getDefinedOptions());

$correctOptions = array_intersect_keys($inputOptions, $availableOptions);

$invalidOptions = array_diff_key($inputOptions, $availableOptions);
```

**Comment by n-for-all** [comment]
i understand, however i don't have the form registry, i have $app['form.factory'] which is registered through silex provider, i have:

Symfony\Component\Form\FormFactory
Symfony\Component\Form\FormBuilder

which of both and how i can retrieve the form registry?

**Comment by HeahDude** [comment]
@n-for-all I've opened https://github.com/silexphp/Silex/pull/1473 to fix your issue.
