### ISSUE TITLE
Hyperlink (anchor tag) inside terminal - Symfony/Process

### ISSUE THREAD

**Issue by Modelizer** [symfony/symfony#21207]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | no valid

Can we create a hyperlink inside the terminal? I'm working on a project to automate most of the task which user needs to do it manually while installation. I'm using Symfony process to do it. When search for a package and clicks on title inside terminal he should be redirected to GitHub repo. But unfortunately no luck :/

Here is the repo which I'm working on https://github.com/Qafeen/Manager

**Comment by GromNaN** [comment]
I don't know if you can display interactive links in the terminal (like <a>). Displaying the URL should be enough to be clicked: http://stackoverflow.com/questions/2338765/is-there-a-way-to-make-a-link-clickable-in-the-osx-terminal

**Comment by fabpot** [comment]
A terminal only displays text. But indeed, some of them detects URLs and allows you to click on them.
