### ISSUE TITLE
[ExpressionLanguage] Validate access to public properties of object

### ISSUE THREAD

**Issue by deanc** [symfony/symfony#21216]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.* 3.*

When using the `ExpressionLanguage` component to access the public property of an object, no validation is provided to ensure that this property exists. This (I think) could potentially result in expressions evaluating incorrectly. I propose that a SyntaxError is thrown if trying to access a property which does not exist.

```php
class Object {}

$language = new ExpressionLanguage();

try {
    $result = $language->evaluate(
        'obj.prop' == 2,
           array(
               'obj' => new Object()
            )
     );
}
catch(SyntaxError $e) {
  // catch here
}
```

**Comment by stof** [comment]
Well, this is not a syntax error (the syntax is fine). This is a runtime error (values of variables are runtime-only). And adding stricter validation at runtime is possible only in interpreted mode, not in compiled mode (as we cannot add this to the compiled code without making things insane and requiring some functions to be available at runtime).
And so we already rejected this in the past (we don't want to have a stricter validation in 1 case and the other.

**Comment by deanc** [comment]
Hi @stof and thanks for the quickly reply. You are correct, of course about it being a runtime error. What would you suggest for a user who wishes to solve this problem?

**Comment by xabbuh** [comment]
I am against adding such checks. Doing so would potentially degrade performance without much added value IMO.

@symfony/deciders What do you think?

**Comment by fabpot** [comment]
Same for me, closing then.
