### ISSUE TITLE
[Console] Support empty values for options

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21215]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Fabien added [this comment](https://github.com/symfony/symfony/pull/21210#issuecomment-271297002) about this bug:

> #20044 this is a bug on Console that should be fixed, when passing --prefix="", the prefix should be empty.

**Comment by chalasr** [comment]
@fabpot Ok that passing `--prefix=""` or `--prefix ""` should give an empty prefix, but when passing `--prefix` without explicit value, how should it behave (take the default value or be empty)?

**Comment by chalasr** [comment]
See #21228

**Comment by javiereguiluz** [comment]
Closing it as "impossible to fix" ... documenting this behavior in https://github.com/symfony/symfony-docs/pull/7363

**Comment by chalasr** [comment]
Hmm, solving the issue of having empty strings when quotes are specified involves to loose `null` values when it make sense thus cannot be solved without refactoring. 
However #21228 fixes a real issue about the impossibility to know if an option was set without/with an empty value, which is I think what Fabien meant at first.

Think about our first issue with the `--prefix` option, the first fix made that was reverted (https://github.com/symfony/symfony/pull/20184) would have been correct and IMHO pretty straightforward: `$prefix = $input->getOption('prefix') ?: ""`, don't you think?

**Comment by chalasr** [comment]
This should be reopened :)

**Comment by dakess** [comment]
I have the same problem. I tried a lot of workarounds from https://github.com/symfony/symfony/issues/11572 but nothing works as expected. however I found this and tried the patch in https://github.com/symfony/symfony/pull/21228, I can say it fixes the bug for me. 
is it possible to apply https://github.com/symfony/symfony/pull/21228 on the symfony/console composer package? can I help somehow? thanks

**Comment by chalasr** [comment]
@dakess Thanks for confirming that the fix is valid, it's the best help you could give.

> I tried a lot of workarounds from #11572 but nothing works as expected

I was not aware of this issue, it seems to be a duplicate. Added it to #21228 fixed tickets.

> is it possible to apply #21228 on the symfony/console composer package

It'll be once merged, then automatically available in next releases. 
I'm waiting for a decision to be made but I don't see any blocker since it is a really annoying bug that should be fixed, as stated by the symfony lead.
