### ISSUE TITLE
[Form] DateType does not convert timezone 

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony#21217]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

The `DateTimeToLocalizedStringTransformer` when used with a pattern that have only date (in `DateType` for instance) does not convert the result in the desired output

Reproduction steps:
- Use `DateType` in a form
- Set the `model_timezone` to `Pacific/Tahiti`, having default timezone to `Europe/Berlin`.
- Enter the date `2017-01-10`
- Submit the form
- Notice that the received data is `2017-01-10 00:00 Europe/Berlin`, whereas it should be `2017-01-10 11:00 Europe/Berlin`

Incoming pull request with tests and proposed resolution.

(ping @tsurenas for finding it)

**Comment by tkleinhakisa** [comment]
It looks good to me. When the time is not considered it doesn't make much sense to talk about timezones.

2017-01-10 is tuesday january the 10th of year 2017 whereever you are on earth, it can't be monday the 9th nor wednesday the 11th. 
If you consider it as a time interval then it is more than 24 hours. 
If you want to specify a 24 hours interval it should be 2017-01-10 00:00:00 Europe/Berlin to 2017-01-10 23:59:59 Europe/Berlin

**Comment by magnetik** [comment]
I see your point but it still feels weird to me.

I'm using the DateType to select the 24h interval of the user's selected day. Most of the use case I can think of using a DateType in a timezone changing application imply this, but maybe it's only my confirmation bias. Maybe it would be a little less surprising if the output were "2017-01-10 00:00:00 Pacific/Tahiti". 
Maybe it's a DX issue of the `DateType` that exposes a `model_timezone` and `view_timezone` options when it will be in fact not used.

Another problem is that the `DateTimeToArrayTransformer` doesn't behave the same way: it always convert the timezone. 
You can test it by using a `DateType` with the data of the example with:
* widget `single_text`: the result is `2017-01-10 00:00:00 Europe/Berlin`
* widget `choice`: the result is `2017-01-10 11:00 Europe/Berlin`

**Comment by tkleinhakisa** [comment]
> Maybe it would be a little less surprising if the output were "2017-01-10 00:00:00 Pacific/Tahiti".

Think of it in the other way (model_timezone to Berlin, default to Tahiti) then you would get 2017-01-09 which would be event more surprising

> Maybe it's a DX issue of the DateType that exposes a model_timezone and view_timezone options when it will be in fact not used.

I agree with that

> Another problem is that the DateTimeToArrayTransformer doesn't behave the same way: it always convert the timezone.
> You can test it by using a DateType with the data of the example with:
>
> widget single_text: the result is 2017-01-10 00:00:00 Europe/Berlin
> widget choice: the result is 2017-01-10 11:00 Europe/Berlin

That seems like the real bug here.

I think one of the pb is that there is no object in PHP to represent only a date, but always a datetime so you end up with "2017-01-10 00:00:00 Pacific/Tahiti" when it should only be "2017-01-10"

If you think about dates using \DateTime then "2017-01-10 00:00:00 Pacific/Tahiti" is the same as "2017-01-10 00:00:00 Europe/Berlin"
If you think about real dates and times then it's not the same anymore

**Comment by mvrhov** [comment]
Like @tkleinhakisa said. Timezone is irrelevant when operation in date only mode. IMO, the time part when in Date only mode should return default timezone and 00:00:00 as a time portion. So it seems that the choice widget is behaving wrong.

**Comment by tkleinhakisa** [comment]
I agree with 00:00:00 default timezone. Should the tz options be removed/deprecated ?
This looks like a bc break for people relying on the bad behavior of the choice widget

> I'm using the DateType to select the 24h interval of the user's selected day. Most of the use case I can think of using a DateType in a timezone changing application imply this, but maybe it's only my confirmation bias.

@magnetik I do it the opposite in my app: select a date and the event is active for that date no matter what the end users tz are (the event lasts more than 24h). In that case it would create failure in some case where the conversion change the date. I don't think one is better than the other so we need to find consensus about the what the field behavior should be

do you agree with @mvrhov and I suggestions ? would you update the pr accordingly ? maybe we should get some "official" feedback about the deprecation and potential bc

**Comment by mvrhov** [comment]
tz on date only component was deprecated. datetime component needs it.

**Comment by tkleinhakisa** [comment]
I could not find any deprecation in the DateType: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/DateType.php

Am i looking at the wrong place ?

**Comment by mvrhov** [comment]
No it's a fu*kup #12404 They are supposed to be marked as deprecated, but were directly removed. And then added back and not marked as deprecated.
