### ISSUE TITLE
[DI] Autowiring debug tools

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#21222]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | dunno

A lot of new features related to the auto-wiring have been added recently:

- Autowiring
- Setter auto-wiring
- Getter auto-wiring

IMO, especially with the last two, it starts to become necessary to have more tooling to debug auto-wiring. For example, I am a developer coming onto an existing Symfony project which make moderate or heavy use of the auto-wiring feature. Regardless of if the usage of this feature has been done wisely or not, in that situation, I should be able to easily tell what services is auto-wired and its surrounding effects (e.g. if #21031: what other services are auto-wired?).

I have in mind a command to list all the auto-wired services with eventually details on which level of auto-wiring is used. But maybe someone has a better or other suggestions in mind?

/cc @nicolas-grekas @dunglas

**Comment by dunglas** [comment]
The `debug:container` command already tell if a service is autowired or not (in detailed mode).

**Comment by theofidry** [comment]
That's a start but quite limited. For example I may want to know which service is auto-wired, but if I have 200 services I won't check them one by one... It is great to get the details of a service, not to analyze the list of services.

Maybe we could add an option to `debug:container`, e.g. `debug:container --auto-wired`.

**Comment by nicolas-grekas** [comment]
Or you could use grep :)

**Comment by theofidry** [comment]
How? you don't know if the service is auto-wired from the name do you?

**Comment by nicolas-grekas** [comment]
grep autowire -Cxx?

**Comment by iltar** [comment]
grep sadly doesn't work in windows unless you use WSL. Sadly this requires you to have your environment re-setup in Linux.

**Comment by theofidry** [comment]
@nicolas-grekas I still don't see how it would work, `debug:container` just displays:

```
swiftmailer.mailer.default.plugin.messagelogger        Swift_Plugins_MessageLogger
swiftmailer.mailer.default.spool                       Swift_MemorySpool
```

so you can't get the auto-wire information from it, the only way AFAIK is to get the service details to check the autowire section.

**Comment by nicolas-grekas** [comment]
> use grep

or submit a PR :)

**Comment by sstok** [comment]
👍 for `--auto-wired` option.

OT. 

git-bash works, I actually used that all the time when doing development. Cmd is not as powerful and ConEmu with Bash, and PowerShell was to new to me.

Only problem is the paths, oh Windows when will adapt to the POSIX filesystem naming.

And else pass the output to a file and and use an editor to search :trollface:

**Comment by theofidry** [comment]
Rethinking about this one after reading https://github.com/symfony/symfony/pull/21859: maybe we could add a `autowired` tag to the auto-wired services, and then allow `debug:container` to be filtered by tags one way or another?

**Comment by nicolas-grekas** [comment]
@theofidry this tag is proposed in #21859, it's just called `autoregistered`

**Comment by theofidry** [comment]
@nicolas-grekas isn't there a difference between the two? An auto-wired service is not necessarily auto-registered.

**Comment by nicolas-grekas** [comment]
yes, there is one - for autowired ones, there is already the "autowired" attribute on defintion objects, a tag would just duplicate that semantic for nothing

**Comment by theofidry** [comment]
Fair, then maybe instead of a dedicated option for autowiring, maybe we could add the ability to filter the container services by attributes and/or tags?

**Comment by nicolas-grekas** [comment]
@theofidry unless you want to work on it, I suggest to close here.

**Comment by Simperfit** [comment]
@theofidry If you don't have the time I could be working on it anytime soon ;)

**Comment by theofidry** [comment]
Any help is welcomed @Simperfit ;)
