### ISSUE TITLE
Revamp the main Symfony README file

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21235]
In the [Symfony Slack channel](https://slackinvite.me/to/symfony-devs) someone suggested to make the README file of this repo "more sexy". I agree, but let's see what the community thinks about this.

## Problems of the current README

* The title is README instead of Symfony
* It doesn't mention that Symfony uses the MIT license
* It references old projects using Symfony: Dailymotion, Yahoo! Answers ... instead of the amazing and new projects using Symfony, such as Spotify and BlaBlaCar.
* It still describes Symfony as a framework ... instead of components + framework
* It recommends to start reading the docs with the "Quick Tour" ... but that's probably not a good idea, because that doc is no longer maintained/updated and it's pretty bad unfortunately.
* Contributing and Community Reviews should be merged.
* etc.

## Proposal for a new README

I looked into two sources for inspiration: 

* [GitHub repos with > 30K stars](https://github.com/search?utf8=✓&q=stars%3A%3E30000&type=Repositories)
* [Awesome READMEs curated list](https://github.com/matiassingers/awesome-readme)

Changes we could introduce:

* Remove the README title
* Add the Symfony logo, like [TensorFlow](https://github.com/tensorflow/tensorflow), [Vue](https://github.com/vuejs/vue) or [Docker](https://github.com/docker/docker) ... or display only the small logo ("sf" letters inside a black circle) and put the project description side-by-side, like [D3](https://github.com/d3/d3)
* Mention some modern websites (Spotify, BlaBlaCar) and projects (Drupal, Magento) using Symfony and link to the [Projects using Smyfony page](http://symfony.com/projects).
* Add a very short list of "key Symfony features", similar to [React](https://github.com/facebook/react), [docker](https://github.com/docker/docker#better-than-vms) and [Vue](https://github.com/vuejs/vue#intro)
* Expand the community section to display resources like our official Twitter, Blog, IRC, Slack, StackOverflow, etc. like [Bootstrap](https://github.com/twbs/bootstrap#community), [React Native](https://github.com/facebook/react-native#getting-help) and [docker](https://github.com/docker/docker#talking-to-other-docker-users-and-contributors). Mention that issues are only for asking new features and reporting bugs, not for support.
* Add a brief mention to "security disclosure", like [docker](https://github.com/docker/docker#security-disclosure) and [Node.js](https://github.com/nodejs/node#security).
* Show the recommended "doc flow" for newcomers: Start with the "Getting Started" guides, continue with the specific guides or component docs that you may need and when you have experience, read the "best practices" guide.
* Link to the Symfony API reference from the doc section?
* Add a mention to our time-based releases, LTS and roadmap inside the Download/Installation section? [Node.js](https://github.com/nodejs/node#download) does it.
* Mention that we follow Semver? [Bootstrap](https://github.com/twbs/bootstrap#versioning) and [FontAwesome](https://github.com/FortAwesome/Font-Awesome#versioning) do it.
* Is the "Running Symfony Tests" still relevant? [Angular.js](https://github.com/angular/angular.js#running-tests) is the only popular GitHub repo that still includes it.
* I wouldn't add the typical "badge row". Why? The "Downloads" badge is irrelevant because we have https://symfony.com/stats/downloads, the "MIT License" badge is irrelevant because we mention the license in the README contents, the "Test Pass" badge is unnecessary because we already show for each PR if they pass or not, etc.
* etc.

## Final comments

* The README of the components would remain the same to ease maintenance. Only the main symfony/symfony README would be updated.
* It looks like we would add a lot of contents ... but don't worry because the goal would be to make a very slick and concise README file.

**Comment by Jean85** [comment]
Great suggestions!
Along with the Semver notice, I would add a link to the BC promise, and point the user to the UPGRADE-*.md files.

**Comment by iltar** [comment]
Great suggestion, I'm all for!

**Comment by stof** [comment]
> Is the "Running Symfony Tests" still relevant?

not in the readme. Only contributors are interested in it, so this should go in the contributing file

> Expand the community section to display resources like our official Twitter, Blog, IRC, Slack, StackOverflow, etc.

And explain explicitly that the github issue tracker is not our support channel (with a link to https://symfony.com/support)

**Comment by elonmir** [comment]
You might consider adding the slack channel link as well.

**Comment by javiereguiluz** [comment]
@Jean85 you are right. License is already highlighted by GitHub.
@stof good point; issues !== support
@elonmir yes, it's proposed to add it to the new community section

**Comment by javiereguiluz** [comment]
The community seems to agree with this. So before starting to work on this PR, we need the approval of Symfony deciders. Thanks!

**Comment by pyrech** [comment]
Has this issue been forgotten by deciders ? ^^
