### ISSUE TITLE
[Yaml] Linter does not understand multi-line plain-style strings

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#21240]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.0

Yaml linter does not understand multi-line (lines containing `\n`) [plain-style](http://www.yaml.org/spec/1.2/spec.html#id2788859) strings.

```yaml
- foo
  bar
```

Should parse as: `['foo bar']`. Instead gives parse error on line 2.

**Comment by xabbuh** [comment]
Thank you for the report. Support for this feature was added in #21114 and will be available in the upcoming 3.3 release. Thus, I am closing here.
