### ISSUE TITLE
form filed naming isssue

### ISSUE THREAD

**Issue by roji430** [symfony/symfony#21245]
Hi,
I am new to symfony form so i am posting this question .
basically i have form with lot of field in and what i need is the form data should be in single array
for Eg:
lets suppose the form fields names  are name,username,password, etc...
and i need to get these all filed inside a array named user
likes this
`user=>{name=>'shajsdahsd,
password'=>'asdjasdh,
etc...`
so i give form filed names as `user['name]` but but it show show message like The name contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").
Can any one help me to figure it out....

**Comment by iltar** [comment]
For support questions, please join IRC (freenode.net #symfony) or join slack: symfony-devs.

**Comment by roji430** [comment]
Thank u @iltar
