### ISSUE TITLE
[Asset] Use http base_urls for non secure requests

### ISSUE THREAD

**Issue by killerwolf** [symfony/symfony#21249]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.0

# RequestContextAware assets serving

The documentation [(Asset Component documentation)](http://symfony.com/doc/master/components/asset.html) states:
_HTTPs or protocol-relative URLs for HTTPs requests, any base URL for HTTP requests_

Is there a way to keep consistency with main request ? if request are http then use only HTTP base_urls.

Thanks

**Comment by stof** [comment]
Register your base URL as protocol-relative.

**Comment by killerwolf** [comment]
I am using 2 different (sub)domains (one for https and one for http), so protocol relative URLs is not an option.

Is there a way to decorate these service (or package), in order to unset HTTPS endpoints from base_urls after creating sslPackage

Note: seems like this was already discussed here without any response https://github.com/symfony/symfony/issues/15244

**Comment by javiereguiluz** [comment]
We should make a decision: do we change the current behavior of the Asset component ... or do we consider this a "won't fix" edge case? Thanks!

**Comment by killerwolf** [comment]
Fist thing first: 
I think we should Reactore the Packages class as it is not easy decorable/swapable , this will allow easier decoration.

we can propose a solution with backward compatibilty in mind :) (something like `strict_context: false` by default default)

**Comment by Simperfit** [comment]
It this needed ?

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" (or more precisely, "not longer needed" because everything uses SSL/TLS today) because of the comments given in the related ted pull request: #22510.
