### ISSUE TITLE
Prevent test extending

### ISSUE THREAD

**Issue by keradus** [symfony/symfony#21266]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | n/a

Somehow related to #20493 (cc @nicolas-grekas).

Symfony project treats (which is good) it tests as internal code that should serve only this repo purposes.
It's not common, but I do saw very edge case when someone actually extend concrete `Foo...TestCase` of Symfony unittests. **I would like to propose marking all utests as `@internal` and `@final` (or maybe even `final class` on class-syntax level, not docs) - to prevent that kind of situations.**
In the case I describe the exotic project tests crashed after updating Symfony becouse of BC breaks on `Foo...TestCase` class.

If agreed, I could prepare a PR.

**Comment by theofidry** [comment]
Aren't tests already excluded from the classmap by default? Having to manually register them is already a sign that this should not done.

Instead of final, we could also use `@private`, although not official, in most IDEs this prevent auto-completion to work for those classes (outside of your package).

**Comment by nicolas-grekas** [comment]
If it's not written on the BC promise page, we should mention it there. It's too much pain on the code side.

**Comment by nicolas-grekas** [comment]
"Tests" (with an "s") folders are excluded from the BC promise, that's the policy.

**Comment by keradus** [comment]
@theofidry
`@internal` instead of `@private` and all good with the annotation
excluded from classmap, but not all are using classmaps on dev envs. if one would load standard psr loader instead of classmap loader test classes will be registered.

@nicolas-grekas 
I totally agree with the policy, but then one is still able to technically abuse it if he is not aware of policy in the first place. `@internal` annotation will shout at him in IDE, with final will crash on code execiution.

**Comment by iltar** [comment]
Related: #17749

**Comment by stof** [comment]
> Aren't tests already excluded from the classmap by default? Having to manually register them is already a sign that this should not done.

they are out of the classmap, but the PSR-4 autoloader can find them

**Comment by nicolas-grekas** [comment]
To help move on, I'm :-1: here. The amount of work + maintenance burden this is going to put on use is not worth it IMHO.

**Comment by keradus** [comment]
I do not find this argument valid. Could be done automatically and only for newest line (to not cause merging issues)

**Comment by fabpot** [comment]
I'm also against this change.

Tests are internal by definition. If people want to reuse some `*TestCase` classes not under the `Test/` directory (not that no `s` at the end), they are on their own.

Mentioning this in our BC promise is indeed a good idea. Marking all tests as internal and final is not IMHO.

**Comment by keradus** [comment]
so, it is a matter of kindly asking vs forbidding on code level ;)
