### ISSUE TITLE
[RFC] Improve tracking of environment variables in the case of private services

### ISSUE THREAD

**Issue by tgalopin** [symfony/symfony#21273]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (kind of)
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2

Recently, I stumbled upon an issue with environment variables that I had troubles to understand. Here it is:

I have two environment variables, defined in my `parameters.yml` with a default value of empty:

``` yaml
parameters:
    env(MAILJET_PUBLIC_KEY): ''
    env(MAILJET_PRIVATE_KEY): ''
```

I use these variables only in a private service:

``` xml
<service id="app.mailjet.transport" class="AppBundle\Mailjet\MailjetApiTransport" public="false">
    <argument type="service" id="csa_guzzle.client.mailjet_api"/>
    <argument>%env(MAILJET_PUBLIC_KEY)%</argument>
    <argument>%env(MAILJET_PRIVATE_KEY)%</argument>
</service>
```

This private service is not used by any other service for the moment.

As the service is private and not used by any other service, the `RemoveUnusedDefinitionsPass` removes it from the container. However, when the container dumper dumps the container, it checks if the environment variable was dumped. As the service is now gone, an expection is thrown (`EnvParameterException, Incompatible use of dynamic environment variables "MAILJET_PUBLIC_KEY", "MAILJET_PRIVATE_KEY" found in parameters.`).

I suggest to add a tracking of environment variables in the `RemoveUnusedDefinitionsPass` in order to avoid this issue as it is difficult to understand for newcomers and may lead to troubles.

**Comment by HeahDude** [comment]
Related https://github.com/symfony/symfony/issues/20850.

**Comment by nicolas-grekas** [comment]
@tgalopin would you mind trying this patch, and if it works, open a PR with a test case?
```diff
--- a/src/Symfony/Component/DependencyInjection/Compiler/RemoveUnusedDefinitionsPass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/RemoveUnusedDefinitionsPass.php
@@ -72,6 +72,7 @@ class RemoveUnusedDefinitionsPass implements RepeatablePassInterface
                 $compiler->addLogMessage($formatter->formatRemoveService($this, $id, 'replaces alias '.reset($referencingAliases)));
             } elseif (0 === count($referencingAliases) && false === $isReferenced) {
                 $container->removeDefinition($id);
+                $container->resolveEnvPlaceholders(serialize($definition));
                 $compiler->addLogMessage($formatter->formatRemoveService($this, $id, 'unused'));
                 $hasChanged = true;
             }
```

**Comment by tgalopin** [comment]
I will do this week-end.

**Comment by jakzal** [comment]
@tgalopin any news? :)

**Comment by tgalopin** [comment]
Kind of busy, I forgot about this. I'll try asap :) .

**Comment by tgalopin** [comment]
It does fix the issue, I create a PR.
