### ISSUE TITLE
Translation strange behavior with .yaml in 3.2.1

### ISSUE THREAD

**Issue by vlahanas** [symfony/symfony#21278]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.1

Hello,
I am facing an issue with translations. I am using both .yaml and .xml files. Although when i run the 
php bin/console debug:translation {locale} 
command i can see all my translations, those included in .yaml files are not accessible from within controller. 
Ex. 
$this->get('translator')->trans('message.new_password_confirmation')
will return a string 'message.new_password_confirmation'

**Comment by aitboudad** [comment]
Can you please fork the Symfony Standard Edition and make the changes to reproduce your issue?

**Comment by vlahanas** [comment]
@aitboudad  Closing the issue, since i could not reproduce it in a clean installation of Symfony Standard Edition. Most probably i have messed-up with something in my configuration. Sorry about that...
