### ISSUE TITLE
2.8 http-kernel fixture test gives linter error, php < 7.1

### ISSUE THREAD

**Issue by GDmac** [symfony/symfony#21286]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.8

introducing php 7.1 syntax in 2.8 (php 5.3+ compatible) makes php lint go red.
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/Tests/Fixtures/Controller/NullableController.php#L16

php 7.0 gives: syntax error, unexpected ``?``
``public function action(?string $foo, ?\stdClass $bar, ?string $baz = 'value', $mandatory)``

Am using the 2.8.* http-kernel component on a project that uses older php (5.4 - 7.0). Netbeans seems to do a lint on ALL files in a project, and puts an annoying red dot on the ``vendor`` directory.

**Comment by javiereguiluz** [comment]
It's true that the class uses PHP 7.1 syntax, but if you look into the three tests that use it:

* src/Symfony/Component/HttpKernel/Tests/ControllerMetadata/ArgumentMetadataFactoryTest.php
* src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolverTest.php 
* src/Symfony/Component/HttpKernel/Tests/Controller/ControllerResolverTest.php 

You'll see that all of them includes the `@requires PHP 7.1` annotation, so PHPUnit only executes it when you have PHP 7.1 or higher. I don't know if we can do anything else to prevent the errors that you mention.

**Comment by fabpot** [comment]
You probably need to exclude the `vendor` directory from being inspected by Netbeans. In any case, there is nothing we can do in Symfony itself.

**Comment by GDmac** [comment]
@javiereguiluz phpunit is not the issue, that runs fine. It is the linter in de editor / IDE that is problematic. 

@fabpot ignoring vendor is not a good option, it would ruin any navigation and code hints by the IDE. 

Can the NullableController be set to a more compatible syntax ?
```
public function action(string $foo=null, \stdClass $bar=null, string $baz = 'value', $mandatory)
```

Not every studio / project is on bleeding edge PHP 7.1.
This is for Symfony 2.8, which still supports PHP 5, 
Adding the PHP 7.1 requirement is maybe pushing it a bit to fast forward.

**Comment by xabbuh** [comment]
@GDmac There is a difference between scanning the code to be able to provide auto-completion information and complaining about potential incompatibilities beefier of features not available because of older PHP versions. And this fixture was precisely added to ensure that the SUT does not break support for PHP 7.1 features.
