### ISSUE TITLE
symfony form label attribute 'for' not changing according to form_widget 'id' change while passing through template

### ISSUE THREAD

**Issue by roji430** [symfony/symfony#21297]
i am rendering a form containing form fields in symfony in my template i am doing rendering the form part by part like this ` {{- form_label(form.category,'Categoryname',{ 'label_attr' : {'class': 'control-label','for':'Cname'}}) -}}
 {{- form_widget(form.category,{ 'attr': {'class': 'form-control col-md-10','max-length':55},'label': 'Category name','required':true,'id':'Cname' }) -}}`

but 'id' of the form field change as 'Cname' but the for attribute in the label not change it show what is default by symfony How can i change the "id" of the form field and "for" attribute of the corresponding label ?

**Comment by ro0NL** [comment]
You should not set the ID attribute yourself, it's under debate though :) https://github.com/symfony/symfony/issues/20965#issuecomment-267764478

I believe you can access the generated id via `form.category.vars.id`.

You should really checkout the support channels at https://symfony.com/support as this is not really the place to do so.

**Comment by roji430** [comment]
@ro0NL so you are telling that i should not set the id attribute via 'attr' ,but what  if i need custom id so that my java script can work with out any problem

**Comment by ro0NL** [comment]
You can pass it right? `document.getElementById('{{ form.field.vars.id }}')`

Or select elements by class name or so..

**Comment by HeahDude** [comment]
@roji430 You can customize the form view using `buildView()` or `finishView` in your form type:
```php
public function buildView(FormView $view, FormInterface $form, array $options = [])
{
    $view->vars['id'] = 'your_custom_id';
}
```
or override the form theme of your field to define the needed html with the proper id and html attributes.

Anyway we should close here IMHO, since this is expected and unlikely to change as said in #20965 (to avoid weird side effects).
