### ISSUE TITLE
[Routing] Why pathname decodes before matching?

### ISSUE THREAD

**Issue by sc0rp10** [symfony/symfony#21307]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

I'm using Silex 2.0 have route `/{uri1}/{uri2}` and uri ```/http%3A%2F%2Fhttpbin.org%2Frobots.txt/http%3A%2F%2Fhttpbin.org%2Frobots.txt```
I expect next parameters in route:
```
Array
(
    [uri1] => http://httpbin.org/robots.txt
    [uri2] => http://httpbin.org/robots.txt
)
```
But I got false. If I add regex advice `.+` to both placeholders, I see

```
Array
(
    [uri1] => http://httpbin.org/robots.txt/http://httpbin.org
    [uri2] => robots.txt
)
```
In the `UrlMatcher::match` I see `$this->matchCollection(rawurldecode($pathinfo), $this->routes)`
Why not match raw uri and after matching do rawurlencode for each parameter?

**Comment by Tobion** [comment]
You cannot just match the raw URI as it could also have encoded versions of unreserved chars like `a`. This wouldn't match anymore but should be considered equal. So what would be needed is decoding depending on if its a reserved or unreserved char.
But the routing component does not distinguish between slash and encoded slash for historical and security reasons. There are already multiple issues about this.

**Comment by jakzal** [comment]
Can this be closed?
