### ISSUE TITLE
DOMCrawler: removing extra break lines and spaces?

### ISSUE THREAD

**Issue by jpetitcolas** [symfony/symfony#21302]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.1.7

We are currently implementing a functional test, testing content of the following code:

``` xml
<p class="availability">
    <span class="available-from">
        {{ 'video.available.from'|trans }}
        {{ video.rights.begin|localizeddate('long', 'none') }}
    </span>

    <span class="available-to">
        {{ 'video.available.to'|trans }}
        {{ video.rights.end|localizeddate('long', 'none') }}
    </span>
</p>
```

We need to test content of the `.availability` element. Hence, we use something like:

``` php
$this->assertEquals($expectedAvailability, $crawler->filter('.availability')->text());
```

However, as there are some line breaks, this test fails as following:

```
-'Available from January 6, 2017 to June 14, 2017'
+'
+    
+        Available from
+        January 6, 2017
+    
+        to
+        June 14, 2017
+    
+'
```

We are used to fix this output using a code like:

``` php
$text = $element->text();
$text = preg_replace("/(\n|\t)/", '', $text);
$text = preg_replace("/ {2,}/", ' ', $text);
$this->assertEquals($expectedOutput, trim($text));
```

Yet, it may be a good idea to add a new `$cleanedOutput = false` parameter to the `text()` method?

**Comment by javiereguiluz** [comment]
This was proposed, and rejected, a few years ago in #11470. Two methods were proposed: `trim()` and `flatten()` (the last one is what you are asking for in this issue).

I still think it'd be a good idea. Let's ping @symfony/deciders to see if they've changed their opinion about this. Thanks!

**Comment by vlakoff** [comment]
Adding these `trim()` and `flatten()` methods would require changing the `text()` return type from a plain string to a stringable object. I wouldn't bend towards this change.

Personally I'm extending the Crawler, I couldn't anymore clutter my code all over with this:
```php
$ref = preg_replace('/\s+/', ' ', trim($node
    ->filter('div.numero_ref')
    ->text()));
```

Now I just have to do:
```php				
$ref = $node
    ->filter('div.numero_ref')
    ->cleanText();
```

**Comment by HeahDude** [comment]
It's very common to trim strings in tests, so 👍 for me but this should be opt-in with a new method or a defaulted argument in `text($trim = false)`.

**Comment by Simperfit** [comment]
Can we move forward on this ?
