### ISSUE TITLE
[Console] Options are not recognized if command name is not specified

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#21317]
Q                | A
 ---------------- | -----
 Bug report?      | yes
 BC Break report? | no
 Symfony version  | 3.2.0

It happens when default command is configured. So that  `php app.php app:foo --bar example` works fine but `php app.php --bar example` returns _CommandNotFoundException_ exception "Command "example" is not defined. ".

**Comment by stof** [comment]
this is known (and documented IIRC). There is nothing we can do here in a BC way.

**Comment by javiereguiluz** [comment]
@stof do you consider this a bug to be fixed in 3.3 ... or "a broken feature" that won't be fixed? Thanks!

**Comment by xabbuh** [comment]
@javiereguiluz IIRC there were bug reports in the past and we came to the conclusion that this isn't something that could be fixed without breaking backwards compatibility.

**Comment by xabbuh** [comment]
And @stof is right that we talk about this limitation [in the documentation](http://symfony.com/doc/current/components/console/changing_default_command.html):

> This feature has a limitation: you cannot use it with any Command arguments.

**Comment by javiereguiluz** [comment]
@xabbuh thanks for the info. But I still don't know if this is a known bug that won't be fixed until 4.0 ... or a known limitation that will never be fixed.

**Comment by ogizanagi** [comment]
I think it'll never be fixed. But it can be solved in userland, using a foolish workaround like the following (with some limitations too...):

```php
/**
 * This application aware ArgvInput implementation tries to detect if an existing command name has been provided.
 * If not, it'll add the provided default command name to the tokens.
 */
class DefaultCommandArgvInput extends ArgvInput
{
    public function __construct(Application $application, string $defaultCommand)
    {
        $argv = $_SERVER['argv'];
        $commandName = $argv[1] ?? null;
        if (empty($commandName) || !$application->has($commandName)) {
            array_splice($argv, 1, 0, [$defaultCommand]);
        }
        parent::__construct($argv);
    }
}
```

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" for the reasons given above ... but I've opened https://github.com/symfony/symfony-docs/pull/7545 to improve the docs about this.
