### ISSUE TITLE
make it easier to control the order in which auth sources are accessed

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#2131]
we have an application that uses http basic and cas for authentication in a single firewall. since the bulk of the requests are handled via the in_memory auth source set in the http basic provider its important that its checked first in order to not overload the cas and to reduce the network overhead.

**Comment by jakzal** [comment]
Am I missing something, or is this already possible with the [chain user provider](http://symfony.com/doc/current/cookbook/security/multiple_user_providers.html)?

**Comment by iltar** [comment]
@jakzal Guard allows you to do this now afaik
