### ISSUE TITLE
[Security] LdapUserProvider should not be aware of user password

### ISSUE THREAD

**Issue by stoccc** [symfony/symfony#21319]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

Steps to reproduce the bug.
1. Configure auth with form_login_ldap in security.yml (see http://symfony.com/doc/2.8/security/ldap.html#configuration-example-for-form-login)
2. Configure the default LDAP user provider (see http://symfony.com/doc/2.8/security/ldap.html#fetching-users-using-the-ldap-user-provider)
3. Try to login with a valid user and password

If your ldap server return something not null in the userPassword field, you will not be authenticated.
This is due to these lines of code that handle password in inconsistent ways:
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L82
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L98

I think LdapUserProvider should not take care of the user's password as in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L98, thus this line
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L82
should be changed in
```
        $password = null;
```
to have the provided LdapUserProvider.php working properly.

Best regards.

**Comment by ChadSikorra** [comment]
Yeah, that would be a problem. Each time the user is refreshed from the LdapUserProvider, if it pulled the password attribute initially (and it contained something), it would invalidate the user in the authentication provider as the old and new user object passwords will not match. That's my understanding of this issue anyway. Maybe I'm overlooking something?

**Comment by stoccc** [comment]
@ChadSikorra 
I think you got exactly the problem.

**Comment by xabbuh** [comment]
@csarrazi Can you have a look here? :)

**Comment by csarrazi** [comment]
Actually, the user provider *should* be aware of the password returned for the user class.

This is actually the case when some users actually do not use the LDAP Bind mechanism, but actually use client-side password validation, using the password hash (yes, it is a valid use case).

What we can do, though, is make the password field configurable (and this is actually the case in the master branch), and make sure that when the password field is set to a null value, we do not try to retrieve the password and set it in the user object.

**Comment by fabpot** [comment]
Looks like we can close this one, right? /cc @csarrazi

**Comment by csarrazi** [comment]
Yes indeed
