### ISSUE TITLE
Remove feature auto_alias because it is not fully implemented

### ISSUE THREAD

**Issue by jean-pasqualini** [symfony/symfony#21321]
Original pull request : https://github.com/symfony/symfony/pull/12526

@wouterj @xabbuh @nicolas-grekas @fabpot

The feature implement the CompilerPass AutoAliasServicePass see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutoAliasServicePass.php

Unfortunately it has never been wired. So it is not available in symfony.

Why do we keep this feature if it is not wired?

**Comment by stof** [comment]
We cannot remove it, because the compiler pass may be wired by other projects using the component (I'm quite sure Drupal 8 wires it, as they were the one requesting it)

**Comment by fabpot** [comment]
Indeed, we added it for Drupal even if we are not using it directly.
