### ISSUE TITLE
[Console]  v. 2.8.16 - undefined Outputformatter::escapeTrailingBackslash()

### ISSUE THREAD

**Issue by PatrickBauer** [symfony/symfony#21337]
After updating from symfony/console 2.8.15 to 2.8.16 the following error message appears while using the Drupal console:

`Error: Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() in Symfony\Component\Console\Helper\SymfonyQuestionHelper->writePrompt() (line 57 of /Users/patrickbauer/Sites/vs_root/vendor/symfony/console/Helper/SymfonyQuestionHelper.php).
`

I don't know if this is the right place to report this error and I'd be glad if someone redirected me to the right place.

**Comment by xabbuh** [comment]
The method is there: https://github.com/symfony/symfony/blame/2.8/src/Symfony/Component/Console/Formatter/OutputFormatter.php#L50

Do you maybe have to clear your Opcache?

**Comment by PatrickBauer** [comment]
As far as I know, Opcache is disabled for CLI scripts, isn't it?
I wouldn't know how to empty it right now, but I saw the following error in PhpStorm at the given line:

![symfony-trailingbackslash](https://cloud.githubusercontent.com/assets/1428943/22071198/b8519b1e-dd9e-11e6-96c8-f209d9a2a4a2.jpg)

**Comment by stof** [comment]
> As far as I know, Opcache is disabled for CLI scripts, isn't it?

depends on your config in php.ini

> I wouldn't know how to empty it right now, but I saw the following error in PhpStorm at the given line:

yeah, PhpStorm complains about any usage of internal code. It is not smart enough to detect that the usage is in the same package than the definition (and if symfony/console was not allowed to use its own internal code, there would be no point having it)

**Comment by stof** [comment]
Can you show the output of ``composer show 'symfony/*'`` ?

**Comment by PatrickBauer** [comment]
Sure. The system we're using is Drupal 8 with the Drupal Console.

```
symfony/browser-kit             v3.2.2  Symfony BrowserKit Component
symfony/cache                   v3.1.9  Symfony implementation of PSR-6
symfony/class-loader            v2.8.16 Symfony ClassLoader Component
symfony/config                  v3.1.9  Symfony Config Component
symfony/console                 v2.8.16 Symfony Console Component
symfony/css-selector            v2.8.16 Symfony CssSelector Component
symfony/debug                   v2.8.16 Symfony Debug Component
symfony/dependency-injection    v2.8.16 Symfony DependencyInjection Component
symfony/dom-crawler             v3.1.9  Symfony DomCrawler Component
symfony/event-dispatcher        v2.8.16 Symfony EventDispatcher Component
symfony/expression-language     v3.1.9  Symfony ExpressionLanguage Component
symfony/filesystem              v3.1.9  Symfony Filesystem Component
symfony/finder                  v2.8.16 Symfony Finder Component
symfony/http-foundation         v2.8.16 Symfony HttpFoundation Component
symfony/http-kernel             v2.8.16 Symfony HttpKernel Component
symfony/polyfill-apcu           v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-iconv          v1.3.0  Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring       v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54          v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55          v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/process                 v2.8.16 Symfony Process Component
symfony/psr-http-message-bridge v0.2    PSR HTTP message bridge
symfony/routing                 v2.8.16 Symfony Routing Component
symfony/serializer              v2.8.16 Symfony Serializer Component
symfony/translation             v2.8.16 Symfony Translation Component
symfony/validator               v2.8.16 Symfony Validator Component
symfony/var-dumper              v2.8.16 Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                    v2.8.16 Symfony Yaml Component
```

**Comment by stof** [comment]
hmm, does Drupal embed its own version of the symfony/console component somewhere, or is everything managed by composer ?
I'm wondering whether it is possible that a second version of the component code may live in your project (and having OutputFormatter being loaded from this other version which would not have the internal method)

**Comment by PatrickBauer** [comment]
As far as I know everything is managed through composer (as long as one uses https://github.com/drupal-composer/drupal-project). 

There is no other OutputFormatter in the project files, see:

![outputformatter](https://cloud.githubusercontent.com/assets/1428943/22074320/4376f226-dda8-11e6-8dea-977f128488e1.jpg)

**Comment by joelrotelli** [comment]
@PatrickBauer Same problem here with drupal-composer

**Comment by xabbuh** [comment]
Could one of you push an example project to GitHub that would allow us to reproduce your issue?

**Comment by PatrickBauer** [comment]
You could use https://github.com/drupal-composer/drupal-project, install Drupal Console and use the "drupal site:install" command.

In the meantime there was another issue to be found here, with a possible fix (didn't try it yet):
https://github.com/hechoendrupal/drupal-console/issues/3100

**Comment by xabbuh** [comment]
@PatrickBauer Thanks for the feedback and linking the related issue. I am closing here as this should indeed be fixed the linked PR. Please leave feedback here if the fix in Drupal does not solve your issue.
