### ISSUE TITLE
[FrameworkBundle] CachePoolClearerPass fails if "cache.annotations" service is created

### ISSUE THREAD

**Issue by antanas-arvasevicius** [symfony/symfony#21339]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-dev

Using Symfony 3.3.0-dev + "jms/di-extra-bundle": "dev-master" got an error:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "cache.annotations".              

Problem is that DiExtraBundle AnnotationConfigurationPass is using annotation reader service which uses "cache.annotations" and they are instantiated in AnnotationConfigurationPass.
After that  "cache.annotations" definition no longer available as it's already instantiated. 
Now CachePoolClearerPass uses has('cache.annotations') and then getDefinition('cache.annotations') (see: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolClearerPass.php#L55 )
has('cache.annotations')  returns true, because it has that service, but getDefinition() now throws exception because no definition exists.

DiExtraBundle is registering AnnotationConfigurationPass in before optimization pass  and FrameworkBundle's CachePoolClearerPass is registered in after removing pass.
Maybe we could rearrange these Passes, or it would be safe to patch CachePoolClearerPass to use not has() but hasDefinition() instead? In this case, users who uses DiExtra bundle won't get 'monolog.logger.cache' inserted into 'cache.annotations' so don't know is this also good option. 

What's your thoughts?

**Comment by stof** [comment]
The issue is that ``has()`` does not guarantee that there is a definition (it may be an alias too).

Btw, instantiating a service does *not* remove the Definition object

**Comment by antanas-arvasevicius** [comment]
Hi,
it does! Look at https://github.com/symfony/dependency-injection/blob/master/ContainerBuilder.php#L377  it removes definitions when they are instantiated and assigned to container.

Changing `has()` to `hasDefinition()` maybe fix the problem, but still, "cache.annotations" service configuration will be different when some previous compiler pass instantiates that before CachePoolClearerPass rewires it. Don't know, maybe its not a big deal, but could trigger subtle issues somehow :) Should I submit PR fixing this? And which way do you prefer more?

**Comment by antanas-arvasevicius** [comment]
Related: https://github.com/symfony/symfony/commit/24c40e0d22120bfd63b4a1fa868a756438a55c12

**Comment by antanas-arvasevicius** [comment]
@stof looks you've been right, don't know how "cache.annotations" disappears from container definitions? Can be found in AnnotationConfigurationPass but on in CachePoolClearerPass

**Comment by antanas-arvasevicius** [comment]
"cache.annotations" definitions is removed when `DependencyInjection/Compiler/DecoratorServicePass.php:64`  calls `$container->setAlias('cache.annotations', new Alias('cache.annotations.recorder', false));`
Here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L643

And then `RemovePrivateAliasesPass` removes an alias to "cache.annotations" too :)
So definitions and aliases has been gone after these steps.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/RemovePrivateAliasesPass.php#L40

Shouldn't that `CachePoolClearerPass` be called not after removal step, but before `RemovePrivateAliasesPass`? I can see that there is complicated interdependencies between everything, but hope my debug info will help to mangle this out.

**Comment by nicolas-grekas** [comment]
> Shouldn't that CachePoolClearerPass be called not after removal step, but before RemovePrivateAliasesPass?

For reference, that's on purpose: the goal is to *not* block the removal of private pools when they are just injected in the clearer.

**Comment by antanas-arvasevicius** [comment]
I don't get it, why CachePoolClearerPass trying to get definition of "cache.annotations" if it is actually an alias which get removed in RemovePrivateAliasesPasss and this is called first.
And actually real definition is "cache.annotations.recorder" which I think should be modified in CachePoolClearerPass then it make sense
Now passes call sequence is: `RemovePrivateAliasesPass  -> CachePoolClearerPass`

**Comment by nicolas-grekas** [comment]
I mean: changing the order of compiler passes is going to affect all pools. The fix needs to affect only the cache.annotation related issue.

**Comment by antanas-arvasevicius** [comment]
@nicolas-grekas @stof please review PR https://github.com/symfony/symfony/pull/21362

**Comment by nicolas-grekas** [comment]
@antanas-arvasevicius can you please confirm that #21381 fixes your issue?

**Comment by antanas-arvasevicius** [comment]
Hi, I can confirm that your PR fixes my issue. So my PR gets deprecated :)
