### ISSUE TITLE
[SecurityBundle] Tests segfaults with php 7.1.0 on OS X 10.12.2

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#21349]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3 (master)

For some reasons, since 7497f1c, using php 7.1.0 (built: Dec  2 2016, Liip PHP OS X 10.12.2), I get segmentation faults when executing tests on the `SecurityBundle`:

```sh
./phpunit src/Symfony/Bundle/SecurityBundle/

#!/usr/bin/env php
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

Testing src/Symfony/Bundle/SecurityBundle/
...............................................................  63 / 139 ( 45%)
...................Segmentation fault: 11
```

There are actually many tests triggering a segfault, but executing a test case alone might pass for some of them whereas it fails when starting the whole SecurityBundle test suite.

(I know segfaults are issues with the php engine, but it might be useful to identify the issue)

**Comment by nicolas-grekas** [comment]
Ping @jpauli
General note: segfaults are PHP bugs, not Symfony's

**Comment by chalasr** [comment]
Same on my side (OSX 10.11.6, PHP 7.1.0)

**Comment by jpauli** [comment]
We released 7.1.1 recently. Could you try with that version ?

**Comment by ogizanagi** [comment]
Sure. Same issue using PHP 7.1.1 freshly compiled.

**Comment by jpauli** [comment]
Could you fill in a bug on https://bugs.php.net/ with the stack trace and the version of Symfony you are testing please ?

**Comment by ogizanagi** [comment]
Done: https://bugs.php.net/bug.php?id=73989

**Comment by ogizanagi** [comment]
Closing, as it has been confirmed on the php bug tracker and that there is nothing to do on Symfony's side to workaround it temporarily.
