### ISSUE TITLE
Happy guy on exception pages

### ISSUE THREAD

**Issue by severak** [symfony/symfony#21343]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             |  no
| Symfony version  | 2.x + 3.x

Hi, this little guy at Symfony error page seems to be happy that Exception occured:

![screenshot379](https://cloud.githubusercontent.com/assets/615685/22104451/7bf9eef4-de3f-11e6-8396-7806bda2a856.png)

**This is completely ridiculous**.

Exception is no reason to be happy, please, provide sad alternative for 

`symfony/src/Symfony/Bundle/TwigBundle/Resources/views/Exception/exception.svg`

**Comment by jenkoian** [comment]
How about a confused John Travolta? (https://github.com/jolicode/GifExceptionBundle)

![](https://raw.githubusercontent.com/jolicode/GifExceptionBundle/master/Resources/public/images/404/confused-travolta.gif)

**Comment by javiereguiluz** [comment]
@severak thanks for your proposal. However, I must close this as duplicated because we are already redesigning the exception pages in #20951. Thanks!
