### ISSUE TITLE
[DI][Autowiring] Resolve ambiguous dependency when it is decorated

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#21351]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

If a service is decorated and the decorator doesn't set the `autowiring-type` explicitly, then it is judged as ambiguous by the AutowirePass, for example:

```php
class Foo 
{
    public function __construct(AccessDecisionManagerInterface $accessDecisionManager) 
    {
    }
}
```
```yaml
AppBundle\Foo:
    autowire: true
```
Gives:

>   [Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Unable to autowire argument of type "Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface" for the service "AppBundle\Foo". 
Multiple services exist for this interface (debug.security.access.decision_manager, debug.se
  curity.access.decision_manager.inner).

I think that a nice improvement could be to check that the only 2 alternatives are the decorator and the decorated, and inject the decorator instead of throwing.

I given it a try but calling `$this->container->getDefinition('debug.security.access.decision_manager')->getDecoratedService()` from the AutowirePass returns `null` since the DecoratorServicePass calls `$decorator->setDecoratedService(null);` before that the AutowirePass is called.

Is there something doable in order to make this possible (e.g. changing the AutowirePass priority or avoid calling `setDecoratedService(null)` on decorators when processing them)?

If nothing can be done, I'll just propose to fix it for this specific service by adding an `autowiring-type` onto.

**Comment by fabpot** [comment]
I think it should be fixed globally or not at all.

**Comment by fabpot** [comment]
And of course, I would prefer to fix it globally :)

**Comment by xabbuh** [comment]
I agree. Not sure yet how to fix it though.

**Comment by chalasr** [comment]
You're both talking about fixing it, I'm not sure it can be without introducing something like a `Definition::$decorator` to be populated from the `DecoratorServicePass` and consumed by the `AutowirePass` (or remove this line https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php#L41, not aware of the drawbacks).

I'll look at it.

**Comment by chalasr** [comment]
See #21397

**Comment by Hanmac** [comment]
sorry that you didnt managed yet to fix that problem.
but in your example with:
```
Service
Decorator(Service)
Auto(Service)
```

and Auto does see Decorator and Decorator.inner, i didnt run a test yet, but isnt Decorator.inner an Alias in that place or did i get that wrong?

**Comment by nicolas-grekas** [comment]
Could this issue by solved by injecting DecoratorServicePass into AutowirePass, add a method on DecoratorServicePass that returns the missing info about decorated services, and use it inside AutowirePass when needed?

**Comment by chalasr** [comment]
@nicolas-grekas I'm afraid that having the info is not enough. 
See my failed attempt in #21397 where the info was here and which worked for one level of decoration, but several edge cases wasn't properly managed due to both the AutowirePass implementation and the patch itself. At the moment I didn't find a robust way to handle this fully.

**Comment by nicolas-grekas** [comment]
could service definitions opt-out from autowiring types, saying the AutowirePass: I'm not a candidate for this kind of interface? Could that help?

**Comment by chalasr** [comment]
I think it's the right approach. Do you want to give it a try or shall I do?

**Comment by nicolas-grekas** [comment]
Please do :)
