### ISSUE TITLE
StreamedResponses send response to stdout before $response->send() is called in app.php

### ISSUE THREAD

**Issue by Loupax** [symfony/symfony#21355]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

Steps to reproduce:

1. Create a controller that returns a StreamedResponse and create a route to it.
For example

```
class DefaultController extends Controller
{
    /**
     * @Route('/example')
     */
    public function downloadSomewhatHugeFileAction()
    {
        $response = new StreamedResponse(function () {
            $response = $this->get('webservice.thingy')->fetch()->getBody();
            while (!$response->eof()) {
                echo $response->read(1);
            }
        });

        $disposition = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, 'file.csv');
        $response->headers->set('Content-Disposition', $disposition);
        return $response;
    }
}

```
2. Change your webapp entry point file to look something like this.

```
...
$kernel = new AppKernel('dev', true);
$kernel->loadClassCache();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
die('Handled but not sent yet');
$response->send();
$kernel->terminate($request, $response);
```

3. Visit your new URL and see the response that you don't get if you returned a `Response` object instead

**Comment by dmaicher** [comment]
Is it a problem for you that the response is streamed to the client before the `$respone->send()` call? 

I also find it a bit confusing but probably there is a reason for it being done here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/StreamedResponseListener.php#L41

ping @fabpot

**Comment by jvasseur** [comment]
I think this is done so that the StreamedResponse is executed in the context on the Kernel::handle method. This has two advantages : any error raised by the callback can still be handled by the kernel and the RequestStack still contains the current request instead of being empty.

**Comment by Loupax** [comment]
I discovered this while I was trying to test the performance of my application by putting timers between `$kernel->handle()` and `$response->send()` but other than that my applications work properly. 

If it is not possible to handle this  when `$response->send()` it would be better to at least document this case.

**Comment by jakzal** [comment]
The explanation why it was done in the event listener is given in the pull request that introduced the streamed response feature: https://github.com/symfony/symfony/pull/2935#r310919

> The event listener is needed because we need to be in the request scope to be able to generate the response. If you send the response in the front controller, the request is not available anymore.

**Comment by nicolas-grekas** [comment]
@jakzal shall we close then?

**Comment by jakzal** [comment]
I suggest we add the comment I pasted above to the StreamedResponseListener.

**Comment by Tobion** [comment]
I still don't see why we need the listener. Can someone give an example? Also "scopes" concept doesn't exist anymore. So the explanation doesn't fit anymore.

**Comment by ogizanagi** [comment]
@Tobion : As said @jvasseur  is https://github.com/symfony/symfony/issues/21355#issuecomment-275850254, calling `$response->send()` in the front controller would mean calling it after `KernelEvents::FINISH_REQUEST` and the current request being popped out of the request stack. So what if the stream response callback uses services needing the request?
I guess that's what meant @fabpot by "in the request scope" in his comment and is still applicable.
