### ISSUE TITLE
Display a map of services dependencies

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#21365]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.11

I know about command:

```
app/console debug:container
```

but it list of services.

How to display a map of services dependencies?

**Comment by ogizanagi** [comment]
Don't know if that's what you expect, but Symfony ships with a `GraphvizDumper` you can use to generate something like:

<img width="1127" alt="screenshot 2017-01-20 a 21 29 12" src="https://cloud.githubusercontent.com/assets/2211145/22164471/9f25e9c8-df57-11e6-8341-17dd5d692f7e.PNG">

However there is no command allowing to dump the container right now, though it can be an idea.

**Comment by GromNaN** [comment]
The Graphviz of a symfony standard container is huge, thus useless.
I've hacked a command to build the `.dot` file from the dumped `.xml`in the cache: https://gist.github.com/GromNaN/af7e53de4b9e0167f1f294a9a0db0ab2

**Comment by javiereguiluz** [comment]
@yapro as you can see in the previous comments, it's already possible with the existing GraphVizDumper. However ... it's not that simple to use it, so borrowing @ogizanagi's idea, in #21724 I'm proposing to create new commands to dump the container more easily. Thanks!
