### ISSUE TITLE
[Console]Add option to hide the choices

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#21364]
| Q                | A
| ---------------- | -----
| Feature request? | yes

When the using `SymfonyStyle::choice` with a very long choice list, one can't see the question unless they scroll backwards. If the choices are well known (like language codes or country codes), it might be enough to ask the question without showing any choices and let the auto-completer do its job. I can work on it if you think it is worth it.
For now I think I'll just write a custom style.

**Comment by ogizanagi** [comment]
Somehow related to https://github.com/symfony/symfony/pull/15553, but I guess your suggestion is to add a new SymfonyStyle method making use of the autocompletion & validation rather than a `ChoiceQuestion` ? :)

**Comment by greg0ire** [comment]
Un uh yes it's very related indeed! Would be nice to have it available through the SymfonyStyle as you suggest though

**Comment by HeahDude** [comment]
👍 I've used an custom style with a method like this for the next release of GeneratorBundle, and thought about proposing it to the core. Don't have time for this, would love to see a PR though.

Here's what I used (not pushed yet) https://github.com/HeahDude/SensioGeneratorBundle/blob/generate-bundle/Command/Style/SensioGeneratorStyle.php#L68.

**Comment by greg0ire** [comment]
Thanks @HeahDude , I'll probably make a PR with this soon.

**Comment by greg0ire** [comment]
@HeahDude : I made [a PR on your PR branch](https://github.com/HeahDude/SensioGeneratorBundle/pull/1), and then closed it because if we go that way (not using the choice question), we lose [the default validator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Question/ChoiceQuestion.php#L127), which is a no-go for me since I need to use this with an associative array. A solution might be to move the validator to its own class.

**Comment by ogizanagi** [comment]
> not using the choice question [...] A solution might be to move the validator to its own class.

Or considering back something like https://github.com/symfony/symfony/pull/15553.

**Comment by javiereguiluz** [comment]
I propose to close this as "won't fix". You can always use a `Question` with `setAutocompleterValues()`, which guarantees that the question is seen by the users and the available values are not displayed. Do you agree with this? Thanks!

**Comment by chalasr** [comment]
I agree given nobody proposed a better alternative. Still, PR extracting the choice validator welcomed if you think it's worth it.
Closing
