### ISSUE TITLE
[DI] Cannot declare class ...\DefinitionDecorator, because the name is already in use

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#21369]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3-dev

When using `DefinitionDecorator` in a unit test, the error above will be triggered. Seems like the renaming is not done properly.

**Test output**
```
There was 1 error:

1) Symfony\Cmf\SeoBundle\Tests\Unit\DependencyInjection\CmfSeoExtensionTest::testErrorHandlingPHPCR
Cannot declare class Symfony\Component\DependencyInjection\DefinitionDecorator, because the name is already in use

/home/travis/build/symfony-cmf/seo-bundle/.phpunit/phpunit-5.3/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:73
/home/travis/build/symfony-cmf/seo-bundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ChildDefinition.php:226
/home/travis/build/symfony-cmf/seo-bundle/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/DefinitionDecorator.php:16
/home/travis/build/symfony-cmf/seo-bundle/src/DependencyInjection/CmfSeoExtension.php:254
/home/travis/build/symfony-cmf/seo-bundle/src/DependencyInjection/CmfSeoExtension.php:240
/home/travis/build/symfony-cmf/seo-bundle/src/DependencyInjection/CmfSeoExtension.php:83
/home/travis/build/symfony-cmf/seo-bundle/vendor/matthiasnoback/symfony-dependency-injection-test/PhpUnit/AbstractExtensionTestCase.php:54
/home/travis/build/symfony-cmf/seo-bundle/tests/Unit/DependencyInjection/CmfSeoExtensionTest.php:192
```

**Comment by Simperfit** [comment]
Isn't it because of the `class_alias` on line 226 in ChildDefinition ?

**Comment by xabbuh** [comment]
@wouterj How can I reproduce this issue?

**Comment by chalasr** [comment]
@wouterj Is this issue still relevant? I checked out the bundle and the test suite runs fine on my side.

**Comment by scaytrase** [comment]
I've faced this issue today with `3.3@dev`. Also I see a little problem with `DefinitionDecorator is now just a clone of `Definition`, and all the decorating logic is missed. Is it a BC?

**Comment by scaytrase** [comment]
The problem occures when doing like `new DefinitionDecorator('some.service.id')`. Does the mocking logic works properly? maybe the `DefinitionDecorator` should just extend `ChildDefinition` instead?

**Comment by ogizanagi** [comment]
@scaytrase: Could you provide a reproducer?

**Comment by scaytrase** [comment]
@ogizanagi I'll try to make one

**Comment by scaytrase** [comment]
@ogizanagi https://github.com/scaytrase/symfony-21369

Here it is. I cannot make a travis build for you (they have some issues ATM), but you can manually switch to `symfony/symfony:3.3@dev` or `minimum-stability:dev` ( the easiest way) to make this repo failing

**Comment by scaytrase** [comment]
Stacktrace is following

```
Cannot declare class Symfony\Component\DependencyInjection\DefinitionDecorator, because the name is already in use
 C:\Work\Projects\scaytrase\symfony-21369\vendor\symfony\http-kernel\Kernel.php:546
 C:\Work\Projects\scaytrase\symfony-21369\vendor\symfony\dependency-injection\ChildDefinition.php:131
 C:\Work\Projects\scaytrase\symfony-21369\vendor\symfony\dependency-injection\DefinitionDecorator.php:16
 C:\Work\Projects\scaytrase\symfony-21369\DependencyInjection\Issue21369Extension.php:19
```

**Comment by scaytrase** [comment]
https://travis-ci.org/scaytrase/symfony-21369/builds/229627906 Here is the travis. 3.1 build are failed for another reason (looks like phpunit 6 uncompatibility)

3.3@dev failed for reason above

**Comment by ogizanagi** [comment]
@scaytrase : Thanks a lot for your help and the reproducer. It seems the `return` trick isn't good enough when the `DefinitionDecorator` class is used first. Instead, I suggested another trick in #22657 which seems to work. Could you confirm it please?

**Comment by ogizanagi** [comment]
Status: reviewed

**Comment by scaytrase** [comment]
Locally applying your patch to vendor makes test pass. You have a travis build, so I think there is nothing more I can confirm. Thank you
