### ISSUE TITLE
ParameterBag issues with type return

### ISSUE THREAD

**Issue by tolbon** [symfony/symfony#21386]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Hi All,

I have got an issue with ParameterBag of HttpFoundation

I use this method
```php
    /**
     * Returns the alphabetic characters and digits of the parameter value.
     *
     * @param string $key     The parameter key
     * @param string $default The default value if the parameter key does not exist
     *
     * @return string The filtered value
     */
    public function getAlnum($key, $default = '')
    {
        return preg_replace('/[^[:alnum:]]/', '', $this->get($key, $default));
    }
```
and other methods like ``getInt()``, ``getAlpha()``

If my URL is http://my/url?param=stuff
it works great
but for testing purpose I tried to pass an array like this http://my/url?param[]=stuff&param[]=stuff2
getAlnum return an array
and getInt return (int) 1 cause convert an array to int (array = true = 1)

Maybe the doc is wrong and must return mixed or string|array ?

**Comment by xabbuh** [comment]
Should this method really return an array then? This looks like an unexpected result to me and I would rather return the empty string instead then.

**Comment by ro0NL** [comment]
I think technically we should map each array element (if it's an array) and return the filtered array.

Eventually request validation belongs to your controller, nevertheless this method should work as expected in both scenarios (imo.).

**Comment by fabpot** [comment]
Closing as won't fix for reasons explained in #24667

**Comment by JanTvrdik** [comment]
Wrong documentation of sanitization / validation functions should be treated as a security issue. The current documentation makes it easy for people to rely on `ParameterBag::getAlnum()` returning `string`, which is not actually true.

**Comment by ryanhobrock** [comment]
I believe this issue is worthy of reopening. If the return string type isn't enforced the docblocks should at least be updated.
