### ISSUE TITLE
[DI][DX] Optional class for named services DX issue

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#21380]
| Q                | A
| ---------------- | -----
| Bug report?      | yesish
| Feature request? | no
| BC Break report? | not really
| RFC?             | no
| Symfony version  | 3.3

Since https://github.com/symfony/symfony/pull/21133, the `class` attribute isn't required anymore when using a classname as service id:

```yml
services:
    Vendor\Namespace\Class: ~
```

However, due to the current implementation, the following is considered valid too:

```yml
services:
    bar:
      arguments: ['foo']
```

The `bar` key is considered valid, and will be used as the `Definition` class, despite there is no `bar` class in the project.
Which means **no compile-time exception**. You'll only get:

> Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "bar" from the global namespace.
Did you forget a "use" statement? 

at runtime, when trying to use the service.
Previously, you got an error **at compilation time**:

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: The definition for "bar" has no class.

I think it's a DX regression, especially for someone not being aware of this behavior.

But the fact is that, looking at the tests, it seems expected.
In https://github.com/symfony/symfony/pull/20943#issuecomment-272922010, I suggested to enforce a leading backslash for global namespace classes, ie:

```yml
services:
    \bar: ~
```

but that's not something to consider, given one of the main benefits of declaring a service this way, is to call it using `$container->get(\bar::class)`. Which doesn't resolves to a FQCN with a leading backslash. 
So, unless we move the service id as definition class logic inside each loaders, it's probably a no-go...

First question: Should we care?

Then, what are the possible solutions ?

1. Enforce a leading backslash from file loaders but keeping the ability to do 
    ```php
    $container->register(\ExistingClassFromTheGlobalNamespace::class)
    ```
     which means moving the logic to yaml and xml file loaders. Which creates an inconsistent behavior between formats and probably gives wrong responsibilities to the loaders compared to the compiler pass.
1. Do not accept classes from the global namespace, or at least only accept classes from the global namespace starting with an uppercase char. 
    In my experience, most services ids are lowercased (despite the fact case doesn't matter until https://github.com/symfony/symfony/issues/21193), whereas classnames are mainly capitalized (despite there is no recommendation about it in PSR-0/PSR-4 AFAIK), so it'll prevent WTF moments for a majority and looks sensible to me.
1. Anything else?

**Comment by nicolas-grekas** [comment]
IMHO, there are two no-gos:
- using a convention to "sniff" what "looks enough like" a class or not;
- using `class_exists`, because that would slow down the creation of the compiler, and more importantly make it context-sensitive.

Which means I'm leaning towards answering "no, we can't" to your "Should we care?" question.

That being said, what about catching the `Error` that comes up when a class is missing, and turn it into some friendlier error message when we find that the missing class has exactly the same name than the service id that we were asking for?

**Comment by ogizanagi** [comment]
> what about catching the Error that comes up when a class is missing, and turn it into some friendlier error message when we find that the missing class has exactly the same name than the service id that we were asking for?

It'll indeed be a step forward, but how would you proceed in order to achieve that? 😕 

The two possibilities I see are:

1. Catch the `\Error` from `Container::get()` and parse the message to see if it's a class not found. This also requires updating the `PhpDumper` to wrap any method instantiating a service in the same try/catch block (can be done through a proxy method though to avoid cluttering the generated class).
2. Analyze the backtrace from `ClassNotFoundFatalErrorHandler` to find out if we were trying to call a service with this id when the class not found error occurred.

Both solutions looks complex for this very specific DX regression, and moreover are still runtime exceptions, while it used to throw at compil time before :/

**Comment by theofidry** [comment]
@ogizanagi what about adding a leading backslash and removing it when registering the service? i.e. forcing:

```yaml
services:
    \bar: ~
```

but behind the scene remove the leading backslash so that `$container->get(\bar::class)` still works.

Alternatively we could make the class mandatory if no backslash if found at all in the service name:

```yaml
services:
    bar: ~ # throw an error as not no `class` property has been found an `bar` is ambigus`
```

**Comment by ogizanagi** [comment]
Thanks @theofidry for these suggestions.

> what about adding a leading backslash and removing it when registering the service

Could be a solution. However, as mentioned earlier, I think we should keep the ability to do:

```php
$container->register(\ExistingClassFromTheGlobalNamespace::class)
```

using the PHP format. So either we don't support the above, either that'll require moving the logic from passes to file loaders :/
Also, I don't really like transforming the service name behind the scene.

> Alternatively we could make the class mandatory if no backslash if found at all in the service name

Yes, I think it's better to consider that registering a class from the global namespace this way is a limitation and throw. But I'm afraid everyone will disagree. 😄

**Comment by theofidry** [comment]
I also prefer the second option, less magics and I think it's an reasonable limitation.

**Comment by nicolas-grekas** [comment]
I fact, why not, with one more step: let's not map id to class when no namespace is found.
@ogizanagi I think you can try a PR doing that - enforcing the "class" attribute for global classes.
WDYT?

**Comment by ogizanagi** [comment]
Sure, I'll do it.

**Comment by theofidry** [comment]
Keep me in the loop when you open the PR if I miss it please. I don't think
I'll be of a big help, but i would love to see the follow up still ;)

**Comment by ogizanagi** [comment]
@theofidry : It's already opened 😄 See #21453. 
Thanks for your involvement. :)
