### ISSUE TITLE
No form tokens after update to Symfony 3.2.2

### ISSUE THREAD

**Issue by secit-pl** [symfony/symfony#21393]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

After update from Symfony 3.2.1 to 3.2.2 all my forms have lost the _token input field. I'm using the default form configuration.

    use Symfony\Component\Form\AbstractType;
    
    class Type extends AbstractType
    {
      
      ...
      
      public function configureOptions(OptionsResolver $resolver)
      {
          $resolver->setDefaults([
              'data_class' => Type::class,
         ]);
      }

When I force the form to use the token by setting the csrf_protection to true the form token will appear. 

Below is the part of the console log of the last composer update. Before it all worked fine, after I don't have tokens in all form.

	#> composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	  - Updating symfony/symfony (v3.2.1 => v3.2.2)
		Checking out 358c59fd21f9db7fdb465d1e07fba822d9e18e9e

	  - Removing doctrine/collections (v1.3.0)
	  - Installing doctrine/collections (v1.4.0)
		Downloading: 100%

	  - Removing doctrine/common (v2.6.2)
	  - Installing doctrine/common (v2.7.2)
		Loading from cache

	  - Removing doctrine/dbal (v2.5.5)
	  - Installing doctrine/dbal (v2.5.10)
		Downloading: 100%

	  - Removing doctrine/doctrine-bundle (1.6.6)
	  - Installing doctrine/doctrine-bundle (1.6.7)
		Downloading: 100%

	  - Removing liip/imagine-bundle (1.7.0)
	  - Installing liip/imagine-bundle (1.7.1)
		Loading from cache

	  - Removing symfony/phpunit-bridge (v3.2.1)
	  - Installing symfony/phpunit-bridge (v3.2.2)
		Downloading: 100%

	  - Updating friendsofsymfony/user-bundle dev-master (58757f0 => 41a5d37)
		Checking out 41a5d3796710df903c3fa3e1735b206e4858d56f

	  - Updating vich/uploader-bundle dev-master (2f19166 => a642f3e)
		Checking out a642f3e221bea2b277a53ea92072ed5f7e740b13

**Comment by iltar** [comment]
It sounds like the CRSF configuration is either in your application off (framework config.yml) or a bug triggered this to be off.

**Comment by secit-pl** [comment]
Before the composer update all worked fine, and the CSRF was enabled globally. The only thing I've done was the update of vendors.

**Comment by secit-pl** [comment]
@iltar after your comment I've tried to test it with the:

framework:
    csrf_protection: true

before I had:

framework:
    csrf_protection: ~

and the token is still is not displayed if I don't force the csrf_protection => true in each form.

**Comment by xabbuh** [comment]
@secit-pl Is there any chance for you to reproduce your issue with the Symfony Standard Edition? Unfortunately, without further information and without being able to reproduce it we will very likely not be able to help you.

**Comment by xabbuh** [comment]
Closing here due to the lack of feedback.

@secit-pl Please leave a comment if you can provide us a reproducable example and we can reopen here.
