### ISSUE TITLE
Mismanagement of the data in formtype with collections fields

### ISSUE THREAD

**Issue by gbourgeat** [symfony/symfony#21392]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Hi all, 

I am embarrassed by the behavior of the form handler in the management of the forms of type collection.

**My case:**
I have a tree which possesses branches
FormType Tree contains a field branches which is of type collection of formtype BranchType.

My Tree is created with 2 branches 
```
[

    'tree' => [
        'id' => 1,
        'branches' => [
             [
                  'id' => 1,
                  'name' => 'br1',
             ],
             [
                  'id' => 2,
                  'name' => 'br2',
             ]
       ]
 ]
```

If I send
```
[

    'tree' => [
        'id' => 1,
        'branches' => [
             [
                  'id' => 2,
                  'name' => 'br2',
             ]
       ]
 ]
```
I will see
```
[

    'tree' => [
        'id' => 1,
        'branches' => [
             [
                  'id' => 1,
                  'name' => 'br2',
             ]
       ]
 ]

```
In my application which I use in API I have many relations a little as this one and at several levels.

I would like to know if it is a bug, if it is known and if in a future version will have cured or if the use of forms is not simply adapted to a use in API.

Thanks

**Comment by xabbuh** [comment]
@gbourgeat Please use English on GitHub so that everyone is able to help you with your issue. Thank you for understanding.

**Comment by gbourgeat** [comment]
@xabbuh Sorry

**Comment by xabbuh** [comment]
That's a know limitation of the `CollectionType`. It uses the position of the mapped data in the collection to determine how they have changed. You can use event listeners to  work around this (see #4492 for more information). Therefore I am closing here. Thank you for understanding.
