### ISSUE TITLE
Attempted to load class "CacheException" from namespace "Symfony\Component\Cache\Adapter"

### ISSUE THREAD

**Issue by Avtonom** [symfony/symfony#21394]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 2.8

Did you forget a "use" statement for
https://github.com/symfony/cache/blob/v3.2.2/Adapter/FilesystemAdapter.php#L81

**Comment by nicolas-grekas** [comment]
Thanks for reporting, this has already been fixed in https://github.com/symfony/symfony/pull/21276
