### ISSUE TITLE
[Serializer] CamelCaseToSnakeCaseNameConverter upper camel case not working

### ISSUE THREAD

**Issue by markusu49** [symfony/symfony#21399]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all supported

The CamelCaseToSnakeCaseNameConverter provides a constructor argument to specify whether to use lower camel case or not. Denormalizing upper camel case works fine, but normalizing `ThisIsATest` returns `_this_is_a_test` (should be `this_is_a_test`).

**Comment by theofidry** [comment]
@markusu49 this is happening because `ThisIsATest` is not camelCase but PascalCase.

**Comment by markusu49** [comment]
Isn't this naming Microsoft-specific (see [Wikipedia](https://en.wikipedia.org/wiki/Camel_case))? What is the `lowerCamelCase` attribute for then?

**Comment by theofidry** [comment]
>Some people and organizations, notably Microsoft,[4] use the term camel case only for lower camel case.

It's not limited to Microsoft but more generally in programming languages.

**Comment by markusu49** [comment]
PascalCase is just another name for upper camel case - people often call things differently. However, the denormalize function supports it:

`return $this->lowerCamelCase ? lcfirst($camelCasedName) : $camelCasedName;`

Why shouldn't the normalize function, too?

**Comment by chalasr** [comment]
@theofidry as your last quote points it out, there is indeed two kind of camel case: lower and upper, PascalCase being a synonym of upper camelCase (also known as StudlyCaps). 
The `$lowerCamelCase` constructor argument let me understand the same as @markusu49 i.e. you can chose between both syntaxes using this normalizer so the result it expects looks legit to me.

**Comment by theofidry** [comment]
@chalasr IMO it's up to discussion, and tbh I don't feel strongly about it, but if the denormalize method supports it, the normalize one should as well indeed.

**Comment by chalasr** [comment]
Also I would intuitively prefer a CamelCaseToSnakeCaseNameConverter and a PascalCaseToSnakeCaseNameConverter than only the former handling both

**Comment by robfrawley** [comment]
Isn't "lower camel case" simply "camel case", whereas "upper camel case" is "pascal case"? The function arguments are confusing as-is. Two separate converter classes would be more appropriate.

**Comment by markusu49** [comment]
How should we handle edge cases then, like passing `ThisIsATest` to the (lower) camel case converter? It currently converts to `_this_is_a_test`, but it isn't reversible, as the unit tests make sure that `_kevin_dunglas` converts to `_kevinDunglas`.

**Comment by chalasr** [comment]
@markusu49 Your fix is legit on 2.7. If we want to separate, we have to deprecate this argument and introduce the new converter, that must be done on master, in another PR.
