### ISSUE TITLE
[VarDumper][RFC] Ability to hide properties from being dumped

### ISSUE THREAD

**Issue by cH40z-Lord** [symfony/symfony#21390]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | not sure
| RFC?             | yes
| Symfony version  | 2.x/3.x

Imagine the following situation: You've got a class like this

```php
class Foo
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $contents;

    /**
     * @var \DateTime
     */
    private $timeCreated;
}
```

Now if you put a very large string into the `$contents` property, such as a dump from an XML file that you've fetched from the web, dumping that instance using `dump()` might pollute the output. I often find myself in a situation where some properties are more important than others. So having to scroll through the entire output can become cumbersome, especially when working on the console where you can't collapse or hide them.

That is the reason why I would like to propose a possibility to let developers decide what properties are dumped. For this I'd like to have a new annotations and an optional parameter for `dump()`.

```php
class Foo
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     * @Debug(output="hidden")
     */
    private $contents;

    /**
     * @var \DateTime
     */
    private $timeCreated;
}
```

Using `dump()` now on an instance flagged with a `@Debug` property would result in only printing `$id` and `$timeCreated`.
If you still want to get the complete debug output, you can then pass in a flag to `dump()` that ignores the `@Debug` annotation like so: `dump($fooInstance, VarDumper::DEBUG_SHOW_ALL);`. Passing multiple objects to dump them would still work: `dump($foo, $bar, $baz, VarDumper::DEBUG_SHOW_ALL);`.

Most of the time I'm not interested in inspecting inner service classes that have been injected via the constructor but more in the dedicated fields that the class exposes:

```php
class Bar
{
    /**
     * @var FirstService
     * @Debug(output="hidden")
     */
    private $firstService;

    /**
     * @var SecondService
     * @Debug(output="hidden")
     */
    private $secondService;

    /**
     * @var ThirdService
     * @Debug(output="hidden")
     */
    private $thirdService;

    /**
     * @var string
     */
    private $propertyA;

    /**
     * @var string
     */
    private $propertyB;

    /**
     * @var string
     */
    private $propertyC;


    public __construct (FirstService $firstService, SecondService $secondService, ThirdService $thirdService)
    {
        $this->firstService = $firstService;
        $this->secondService = $secondService;
        $this->thirdService = $thirdService;
    }
}
```

Making the annotation's `output` property explicit like this would allow one to add even more modes, such as `collapsed` and is forward compatible with any potential feature that might be added to it.

Looking at other frameworks such as .NET, they have a similar concept using the `[DebuggerBrowsable(DebuggerBrowsableState.Never)]` attribute for exactly the very same reasons.

So, any opinions? :)

**Comment by stof** [comment]
> ``dump($fooInstance, VarDumper::DEBUG_SHOW_ALL);``

Such API is impossible, because ``dump()`` is a variadic function. We have no way to use extra arguments to pass options

**Comment by cH40z-Lord** [comment]
> Such API is impossible, because dump() is a variadic function. We have no way to use extra arguments to pass options

Variadic parameters are passed in as array. Shouldn't be too hard to check the last entry for a matching flag.

Right now the current implementation of `dump()` is as follows:

```php
if (!function_exists('dump')) {
    /**
     * @author Nicolas Grekas <p@tchwork.com>
     */
    function dump($var)
    {
        foreach (func_get_args() as $var) {
            VarDumper::dump($var);
        }
    }
}
```

I can't see why it shouldn't be possible to check the last argument element, especially since it doesn't even use the variadic operator of the language itself.

As an alternative we could introduce `dump_all()` which passes the correct flag into `VarDumper::dump()`.

**Comment by stof** [comment]
> Variadic parameters are passed in as array. Shouldn't be too hard to check the last entry for a matching flag.

But dumped values can be **any** PHP values, even the values corresponding to flags (btw, if the flag is an integer, it is *very* easy to end up with a dumped value being considered as a flag instead).
We cannot enforce the last argument to always be a flag. This would be a BC break, and it would make it painful to use the API.
Thus, having custom arguments *after* a variadic argument is not something supported by the PHP variadic argument feature. So we should not design an API looking like that, because it will always feel weird.

**Comment by cH40z-Lord** [comment]
Yes I agree. However, it's easy to use something other than an integer like a string GUID or a hash value. One could even pass an instance of a flag class to prevent any issues.

Either way, I'm open to introduce the aforementioned `dump_all()` (or any other) method if the API really feels too weird.

**Comment by nicolas-grekas** [comment]
I fact, this is possible by using a custom cloner, maybe with a custom caster also.
Then, you'll need to rewire the dump function which is only the tip of the iceberg (ie don't focus on it).
See http://symfony.com/doc/current/components/var_dumper/advanced.html

**Comment by stof** [comment]
> Yes I agree. However, it's easy to use something other than an integer like a string GUID or a hash value.

A string GUID would have the same issue (even though collisions would be less likely)

**Comment by nicolas-grekas** [comment]
Closing as explained
