### ISSUE TITLE
New profiler panel for build time info

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#21405]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Symfony version  | 3.3

When the container is compiled, special logs are generated in a file called usually `var/cache/dev/appDevDebugProjectContainerCompiler.log`.

Some deprecations can also be triggered at that build time.

Yet, these deprecations are too often forgotten - because they only appear once.
And the mentioned log file is never looked at (did you know it existed at all?)

It would be great if we could have a new profiler panel for these info.

Anyone willing to give it a try?

**Comment by javiereguiluz** [comment]
Do we need a new panel?

* The initialization time is displayed in the Performance panel.
* The special logs can be displayed in a new tab in the Log panel.

Anything else is missing?

**Comment by nicolas-grekas** [comment]
Just to be clear, as I see it, this info should be persistent: it should not be filled only for the very request that generated them - but be available for inspection in any request.
Make it fit into an existing panel is good also.

**Comment by xabbuh** [comment]
That's indeed a good idea. One use case where this is useful: When using invalid keywords in YAML DI config files, the `YamlFileLoader` will trigger deprecations. But you either need to run `cache:clear` in verbose mode or take a look into the log panel during the very first request that triggers warming up the cache. Being able to easily introspect the build log will ease catching these mistakes a lot.

**Comment by ScullWM** [comment]
I've started working on it, should we distinct "regular" deprecated from "container" ones with a new counter in the profiler bar ?

**Comment by ScullWM** [comment]
Here's what I get (including the container compilation):
![capture d ecran 2017-01-31 a 16 32 46](https://cloud.githubusercontent.com/assets/1017746/22471623/34458c1a-e7d3-11e6-85d4-d2020ba342c1.png)

And with no new container compilation:
![capture d ecran 2017-01-31 a 16 33 26](https://cloud.githubusercontent.com/assets/1017746/22471668/513876ac-e7d3-11e6-87e3-526dada4f24f.png)

Is it possible to have something else than deprecated notifications logs during this compilation ?

The next step is it to have a filter on the "container compilation logs" only in the profiler.

**Comment by stof** [comment]
@ScullWM there are a bunch of debug logs in the container compilation
