### ISSUE TITLE
[HttpFoundation] HTTP/2 support

### ISSUE THREAD

**Issue by thewilkybarkid** [symfony/symfony#21415]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

We're looking to start serving different assets to HTTP/1.x and HTTP/2 (single CSS files and multiple-files respectively). Cloudfront (for example) will serve HTTP/2 to the client, and downgrade the server request to HTTP/1.1 (adding a `Via` header declaring the client connection as 2.0). The server sees `SERVER_PROTOCOL` of `HTTP/1.1`, ignoring the `Via` header. It should really parse the `Via` header if it's trusted and use that, or, probably more correctly, have a new `Request` method to find this value.

On a related note, it looks like the HttpFoundation `Response` will only reply in HTTP 1.x unless the protocol version is manually set (after `prepare()` is called).

**Comment by nicolas-grekas** [comment]
@thewilkybarkid would you like to submit a PR?
