### ISSUE TITLE
Route requirements - POST body

### ISSUE THREAD

**Issue by marekkobida** [symfony/symfony#21411]
| Q                | A
| ---------------- | -----
| Bug report?      | probably no
| Feature request? | true
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

If I send request to /approve without id in POST body request still successfully continues.
Take route requirements care just with GET params? 
PS: I'm just using routing component.

```php
$routes->add('/approve', new Route(
    '/approve',
    [
        '_controller' => function () { }
    ],
    [
        'id' => '[0-9]'
    ],
    [],
    '',
    [],
    [
        'POST'
    ]
));
```

**Comment by jakzal** [comment]
The requirements section is neither for GET nor POST parameters. It's for path placeholders. Your path doesn't have a placeholder called "id" (or any other for that matter).

Relevant documentation: http://symfony.com/doc/current/components/routing.html#defining-routes

> An array of requirements. These define constraints for the values of the placeholders as regular expressions.


Closing as there's no bug.
