### ISSUE TITLE
"OutOfBoundsException" with within-bounds index

### ISSUE THREAD

**Issue by robfrawley** [symfony/symfony#21412]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x-dev
| Related Issues | liip/LiipImagineBundle#858

While working to get `liip/imagine-bundle` updated to properly support Symfony 3.3.x, I ran into the following error message, which I found horribly confusing:

> Symfony\Component\DependencyInjection\Exception\OutOfBoundsException:
The index "0" is not in the range [0, -1]

Obviously, the confusing part being that `0` is absolutely within the range `[0, -1]`. I know constraints, requirements, and conventions of the DI component have been highly volatile as of late (in terms of contributed code), so I'm hoping this report will result in a more expressive, useful exception message moving forward.

https://travis-ci.org/liip/LiipImagineBundle/jobs/195385425#L311

I'll update this issue shortly when I figure out what actually causes this confusing exception message.

**Comment by apfelbox** [comment]
I found this issue, if I want to replace an argument of a service in a compiler pass, of a service that has no arguments:

```yml
some_service:
    class: A\B\TestClass
```

And in your compiler pass:

```php
$container->getDefinition('some_service')
    ->replaceArgument(0, "some_value"); // <-- this value doesn't exist
```

Please note, that apparently you have to define placeholder arguments in your service definition, if you want it to work. It doesn't suffice, that the class has constructor arguments, but you also need to defined placeholder arguments in yml (if you use that as configuration language):

```yml
some_service:
    class: A\B\TestClass
    arguments:
        - ~ # <- this is important
```

**Comment by stof** [comment]
Well, if there is no argument before, you cannot replace them. you would need to use ``addArgument`` in this case

**Comment by xabbuh** [comment]
#21416 should make the exception message more clear

**Comment by robfrawley** [comment]
@apfelbox @stof @xabbuh Oh, how I love the Symfony community: go to sleep, wake up, PR pending! Thanks.
