### ISSUE TITLE
Request in AuthenticationFailureEvent

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#21427]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

AuthenticationFailureEvent should contain current request, similar to InteractiveLoginEvent. Feature to log invalid logins is often requested.

**Comment by ogizanagi** [comment]
The difference with the `Symfony\Component\Security\Http\Event\InteractiveLoginEvent` is that `AuthenticationFailureEvent` lives in the `Symfony\Component\Security\Core\Event` namespace.
So it should not be tied to the request, as it's also meant to be used in non-http contexts.

But you should be able to retrieve the current request from a listener, by injecting the `request_stack` service, right?

**Comment by gadelat** [comment]
Of course. But it's weird when I make a listener which listens to both correct logins and failed logins and I need to use requestStack for one of them, while not for the other. If InteractiveLoginEvent is meant for http logins while AuthenticationFailureEvent not, I think there is missing something like InteractiveLoginFailureEvent

**Comment by ogizanagi** [comment]
Why not indeed. Maybe you could provide a PR?
