### ISSUE TITLE
Add support for "immutable" cache control

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21425]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Mozilla and Facebook recently published [this blog post](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/) and [this other blog post](https://code.facebook.com/posts/557147474482256/this-browser-tweak-saved-60-of-requests-to-facebook) explaining the new `Cache-control: immutable` feature that allows applications to forget about the revalidation requests and HTTP 304 code, greatly increasing the performance of "page reloads".

**Comment by dmaicher** [comment]
Where are changes required? `Symfony\Component\HttpFoundation\Response` and the `HttpCache` component? Anything else?
