### ISSUE TITLE
[Console] TableCell Helper throws error if value is numeric

### ISSUE THREAD

**Issue by jaydiablo** [symfony/symfony#21429]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7+

When using the TableCell helper in the Console Component, if I pass a numeric value as the first parameter of the constructor, then render the table, PHP throws an error:

>Method Symfony\Component\Console\Helper\TableCell::__toString() must return a string value

Sample code:

```php
$table = new Table($output);
$table->setRows([[new TableCell(12345)]]);
$table->render();
```

Casting to a string (either in the TableCell helper, or before the value is passed to the constructor) fixes it.

**Comment by chalasr** [comment]
But the `TableCell` constructor expects a string as stated in the phpdoc: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/TableCell.php

**Comment by javiereguiluz** [comment]
@chalasr you are right ... but don't you think it's super common to use tables to display numeric values?

**Comment by chalasr** [comment]
I agree and don't see any technical drawback for changing this on 2.7. I just think that, theoretically, this should be considered as an enhancement since it involves to change `string` to `string|int` in the doc block (if it was a concrete typehint, we would be stuck until 4.0). Up to deciders :)

**Comment by stof** [comment]
If there was a string typehint, there would be no bug, as PHP would cast it for us (unless you use strict_types in your own code, but then it would be your responsibility to pass a string strictly, and your choice to use strict mode).

I suggest casting in the constructor though (behaving the same than the string typehint) and keeping it documented as ``@var string`` only.
