### ISSUE TITLE
[Console] Using TableCell with colspan and certain styles doesn't render properly

### ISSUE THREAD

**Issue by jaydiablo** [symfony/symfony#21434]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7+

I'm not sure how to write a test for this, as I don't know the best way to test for colors in the console component, but here's an example that shows the behavior that I'm talking about:

```php
'Header with comment style' => array(
                array(
                    new TableCell('<comment>Long Title</comment>', array('colspan' => 3)),
                ),
                array(
                    array(
                        new TableCell('9971-5-0210-0', array('colspan' => 3)),
                    ),
                    new TableSeparator(),
                    array(
                        'Dante Alighieri',
                        'J. R. R. Tolkien',
                        'J. R. R'
                    ),
                ),
                'default',
<<<'TABLE'
+------------------+---------+------------------+
| Long Title                                    |
+------------------+---------+------------------+
| 9971-5-0210-0                                 |
+------------------+---------+------------------+
| Dante Alighieri  | J. R. R. Tolkien | J. R. R |
+------------------+---------+------------------+

TABLE
            ),
```
(in order to make this fail in the symfony test suite I have to enable the `$decorator` parameter in the method `getOutputStream()`)

Here's how that table renders:

<img width="388" alt="screen shot 2017-01-27 at 9 25 55 am" src="https://cloud.githubusercontent.com/assets/136907/22378386/ae2e15d8-e472-11e6-9a8a-9dbb00aec6bb.png">

If I don't use `<comment>` as the style, and use the `<fg>` type of style, it works as expected:

```php
),
            'Header with comment style' => array(
                array(
                    new TableCell('<fg=yellow>Long Title</>', array('colspan' => 3)),
                ),
                array(
                    array(
                        new TableCell('9971-5-0210-0', array('colspan' => 3)),
                    ),
                    new TableSeparator(),
                    array(
                        'Dante Alighieri',
                        'J. R. R. Tolkien',
                        'J. R. R'
                    ),
                ),
                'default',
<<<'TABLE'
+------------------+---------+------------------+
| Long Title                                    |
+------------------+---------+------------------+
| 9971-5-0210-0                                 |
+------------------+---------+------------------+
| Dante Alighieri  | J. R. R. Tolkien | J. R. R |
+------------------+---------+------------------+

TABLE
            ),
```

Output:

<img width="385" alt="screen shot 2017-01-27 at 9 28 22 am" src="https://cloud.githubusercontent.com/assets/136907/22378494/04c3be2a-e473-11e6-8d79-7d47e9346a87.png">

The `<error>` style also fails:

<img width="383" alt="screen shot 2017-01-27 at 9 29 45 am" src="https://cloud.githubusercontent.com/assets/136907/22378567/4e87490a-e473-11e6-8003-9439ece6f89f.png">

So does the `<question>` style:

<img width="389" alt="screen shot 2017-01-27 at 9 32 40 am" src="https://cloud.githubusercontent.com/assets/136907/22378664/9ed8476a-e473-11e6-89d7-645be4fbc69a.png">

But the `<info>` style is fine (I assume this is the default for the header rows):

<img width="387" alt="screen shot 2017-01-27 at 9 30 24 am" src="https://cloud.githubusercontent.com/assets/136907/22378592/61e78866-e473-11e6-8624-ef2c5ce81573.png">

This doesn't happen if there is no colspan:

```php
'Header with comment style' => array(
                array(
                    new TableCell('<comment>Long Title</comment>'),
                    'Test',
                    'Test'
                ),
                array(
                    array(
                        new TableCell('9971-5-0210-0', array('colspan' => 3)),
                    ),
                    new TableSeparator(),
                    array(
                        'Dante Alighieri',
                        'J. R. R. Tolkien',
                        'J. R. R'
                    ),
                ),
                'default',
<<<'TABLE'
+------------------+---------+------------------+
| Long Title       | Test             | Test    |
+------------------+---------+------------------+
| 9971-5-0210-0                                 |
+------------------+---------+------------------+
| Dante Alighieri  | J. R. R. Tolkien | J. R. R |
+------------------+---------+------------------+

TABLE
            ),
```

Output:

<img width="389" alt="screen shot 2017-01-27 at 9 35 46 am" src="https://cloud.githubusercontent.com/assets/136907/22378812/0a5e830a-e474-11e6-847d-d442f4ef7c00.png">

Position of the Cell with the style doesn't seem to matter, so I think it's just setting a colspan that causes it to color the whole table:

```php
'Header with comment style' => array(
                array(
                    'Test',
                    'Test',
                    new TableCell('<comment>Long Title</comment>'),
                ),
                array(
                    array(
                        new TableCell('9971-5-0210-0', array('colspan' => 3)),
                    ),
                    new TableSeparator(),
                    array(
                        'Dante Alighieri',
                        'J. R. R. Tolkien',
                        'J. R. R'
                    ),
                ),
                'default',
<<<'TABLE'
+------------------+---------+---------------------+
| Test             | Test             | Long Title |
+------------------+---------+---------------------+
| 9971-5-0210-0                                    |
+------------------+---------+---------------------+
| Dante Alighieri  | J. R. R. Tolkien | J. R. R    |
+------------------+---------+---------------------+

TABLE
            ),
```

Output:

<img width="391" alt="screen shot 2017-01-27 at 9 37 48 am" src="https://cloud.githubusercontent.com/assets/136907/22378876/65b9f9a0-e474-11e6-97fe-b8f35b142d28.png">

**Comment by jaydiablo** [comment]
FWIW, this is what gets passed to the formatter:

>|&lt;info&gt; &lt;comment&gt;Long Title&lt;/comment&gt;                                     &lt;/info&gt;|

Which renders like so in the Formatter (notice that the pipes are also yellow):

<img width="467" alt="screen shot 2017-01-27 at 10 10 21 am" src="https://cloud.githubusercontent.com/assets/136907/22379975/e3a51436-e478-11e6-897f-0fbe5d272b4d.png">

When I remove the colspan (and add a couple of rows) this is the content passed to the formatter:

>|&lt;info&gt; &lt;comment&gt;Long Title&lt;/comment&gt;      &lt;/info&gt;|&lt;info&gt; Test             &lt;/info&gt;|&lt;info&gt; Test    &lt;/info&gt;|

Which renders like so:

<img width="350" alt="screen shot 2017-01-27 at 10 09 45 am" src="https://cloud.githubusercontent.com/assets/136907/22379983/ea1233e4-e478-11e6-802b-e248056116fb.png">

So it doesn't seem to be a nested tag issue, I'm not yet clear why these two different string are rendered differently.

**Comment by ogizanagi** [comment]
Thanks for all the inputs you've provided to help reproducing and debugging this issue. I was able to reproduce the issue, and noticed it worked for 
```php
new TableCell('<comment>Long Title</>')
```

while it doesn't for 
```php
new TableCell('<comment>Long Title</comment>')
```

Nothing is wrong with the short or long ending tag, but the main difference is the length.
It appears using a `TableCell` didn't properly inspect the content length, as it may contains some styles. Then `Helper::strlenWithoutDecoration` should be used.

See https://github.com/symfony/symfony/pull/21438
