### ISSUE TITLE
[Routing] Support passing parameters as objects to Router::generate()

### ISSUE THREAD

**Issue by Zzortell** [symfony/symfony#21435]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0

Hello,

Following #21409, I think it would be very more user-friendly to enable passing parameters as objects to Router::generate().
Indeed, the user is used to get objects from parameters in the controller using explicit or implicit param converters, so it would be nice to be able to pass these very same objects to generate routes.
It should be possible insofar the task of the Router is exactly managing controller arguments for making routes.

**Comment by robfrawley** [comment]
Hm... what exactly do you mean by "passing parameters as objects to `Router::generate()`. Can you provide an example of how you'd expect that to function?

**Comment by iltar** [comment]
@Zzortell like this? https://github.com/iltar/http-bundle

**Comment by javiereguiluz** [comment]
@Zzortell thanks for your proposal.

However, I must close it as duplicated of #10395, #5999, #11177 and #2288.
