### ISSUE TITLE
[Workflow] Enter events

### ISSUE THREAD

**Issue by samusenkoiv** [symfony/symfony#21433]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.0

I found a strange behaviour of Workflow Class. Particularly this part https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Workflow.php#L139-L141 . Turns out, if a listener is subscribed on "workflow.entity.enter.place" it will receive the entity when it is not in the "place" yet.
So technically there is no an event like "right-after-a-transition".
Shouldn't we trigger ""workflow.entity.enter" events after changing the place for entity?

```
$this->transition($subject, $transition, $marking);
$this->markingStore->setMarking($subject, $marking);
$this->enter($subject, $transition, $marking);
```

**Comment by samusenkoiv** [comment]
@lyrixx ping

**Comment by lyrixx** [comment]
Actually, this event is named `enter` and not `entered`.

Anyway, I have no objection to invert theses two lines But I would like to know your use case before it.

**Comment by stof** [comment]
there is already another event after marking the place: ``announce``. So I don't see any reason to change the place where ``enter`` is triggered. This would make both events equivalent (and would be a BC break).

**Comment by samusenkoiv** [comment]
Well, lets imagine there is a Feature which has many Tasks. When the last task is closed the feature needs to be approved. In that case it would be convenient to have something like:

```
if ($workflow->can($task, 'close')) {
    $workflow->apply($task, 'close');
} 
```
And have a listener which listens to "workflow.task.entered.closed" which do the job.
Even the name "entered" tells us that an entity _**entered**_ the place, while this is just _about to enter_ it

**Comment by stof** [comment]
hmm, announce is about newly enabled transitions, not about the place. So it is not the same event actually.

But we should rather add another event if there is a use case for it IMO. changing the behavior of the existing event would break BC, which could do weird things

**Comment by stof** [comment]
@samusenkoiv the event name is **not** ``entered``. It is ``enter``. there is no ``workflow.task.entered.closed`` event

**Comment by samusenkoiv** [comment]
@stof "announce" event will be triggered only in case there are some other further possible places for an entity.

**Comment by samusenkoiv** [comment]
It would be reasonable to have "before_enter" and "after_enter", but that'd lead to BC breaks too.

**Comment by stof** [comment]
Well, we could add a ``entered`` event after updating the marking

**Comment by samusenkoiv** [comment]
@stof yes we could. Do we agree on that, should I prepare a PR?

**Comment by Padam87** [comment]
@samuelvogel https://github.com/symfony/symfony/pull/20787

I wanted to do the same thing last month :)

**Comment by samusenkoiv** [comment]
@lyrixx any thoughts?

**Comment by meDavid** [comment]
My use case is the following: automatic transitions. For automatic transitions I would now have listeners on the `entered` event that would (optionally) apply a secondary transition. It would make the following test succeed, which is not possible with the `enter` event:

```
	public function testCanContinue()
	{
		// The graph looks like:
		// +---+     +----+     +---+     +----+     +---+
		// | a | --> | t1 | --> | b | --> | t2 | --> | c |
		// +---+     +----+     +---+     +----+     +---+
		$definition = $this->createSimpleWorkflowDefinition();
		$subject = new \stdClass();
		$subject->marking = null;
		$eventDispatcher = new EventDispatcher();
		$workflow = new Workflow($definition, new SingleStateMarkingStore(), $eventDispatcher, 'workflow_name');
		$eventDispatcher->addListener('workflow.workflow_name.entered.b', function (Event $event) use ($workflow) {
			$workflow->apply($event->getSubject(), 't2');
		});

		$workflow->apply($subject, 't1');
		$this->assertEquals('c', $subject->marking);
	}

```

**Comment by Padam87** [comment]
@meDavid Seconded. I needed this too, settled for the announce event.

**Comment by lyrixx** [comment]
@meDavid Indeed, it's better to listen the `announce` event in your use case.

@samusenkoiv Could you explain why you could not use the `announce` event?

**Comment by samusenkoiv** [comment]
@lyrixx I do not understand how I can do it with `announce`. 
As far as figured out of the code:
Announce checks all possible further transitions, finds if some of them are eligible to perform and dispatches that those transitions can be performed right now ("workflow.%name%.announce.%eligible_transition").
Or am I missing something?

What I would like to have is being notified when an entity has changed its place. Just like `enter`, but `enter` is  trigged before the entity gets to the place.

https://github.com/symfony/symfony/pull/20787/files solves this in a nice way, why don't like it?

**Comment by lyrixx** [comment]
If you want to auto apply transition, you can have a look at: https://github.com/lyrixx/SFLive-Paris2016-Workflow/commit/9fda92a70572a48a347c69b5eae975fac264d928

> https://github.com/symfony/symfony/pull/20787/files solves this in a nice way, why don't like it?

The implementations is good. But we already have many events, and If we can avoid to add new events it's better. If there is too many options, it's harder to understand each one. But if there is no solution for this use case, we will add it to the core ;)

**Comment by meDavid** [comment]
@lyrixx My usecase is indeed resolved using the announce event.

**Comment by samusenkoiv** [comment]
@lyrixx I do not want to auto apply transition.

Yes, I do not see a solution. To be honest, I believe the `enter` event is useless, while `entered` is essential one. What needs to happen to include it in core?

>  But we already have many events
We could add an option which would indicate which of the events we'd like to be dispatched. What do you think? I could work on it in case it has chances to be merged.

**Comment by lyrixx** [comment]
No, adding an option is even worst ;)

I still don't get your use case. because [here](https://github.com/symfony/symfony/issues/21433#issuecomment-275696965) it's about auto transition.

Could you explain again you use case please?

**Comment by samusenkoiv** [comment]
@lyrixx well, from some perspective it is indeed about auto transition, but it is about auto transition of **another** entity.

So I we have Feature entity which has many Task. When a task is in place "finished" we need to check all the others feature's tasks. If every task is in place "finished" then we can try to mark the feature as "completed". 
With current events there is no way to do that. 

I'll explain:
Feature f1 has two tasks t1 and t2. The t1 task has been "finished" for a while. The t2 task is about to go to "finished" place. So I have "leave", "transition", "enter" events. All of them are dispatched **_before_** the t2 task gets into "finished" place. Provided I listen to one of them, I would have such a code:
```
public function onTaskFinished(Event $event)
{
        // the t2 task
        $task = $event->getSubject();
        foreach ($task->getFeature()->getTasks() as $task) {
            // if at least one task is not finished
            if ($task->isFinished() === false) {
                return;
            }
        }
        
        // here I know that all tasks are finished, but they are not, because of the t2 task
}
```

And with **entered** event being dispatched after setting marking this would be possible.

**Comment by lyrixx** [comment]
Ok, Nice I understand your use case.

What about:
```php

public function onTaskFinished(Event $event)
{
    // the t2 task
    $currentTask = $event->getSubject();
    foreach ($task->getFeature()->getTasks() as $task) {
        // The current task is finished
        if ($task === $currentTask) {
            continue;
        }
        
        // if at least one task is not finished
        if ($task->isFinished() === false) {
            return;
        }
    }
    
    // here I know that all tasks are finished, but they are not, because of the t2 task
}
```

But anyway, even if it is possible to do that I don't like it so much. Because it will mean the Feature is finished before the last Task.

Now I'm :+1: for a new event.

I will re-open #20787 and review it, and merge it ;)

**Comment by samusenkoiv** [comment]
Indeed, such a condition is a solution here (although it seems hacky), but it is not possible if we go outside `onTaskFinished`.
I'm glad I was able to explain the objectives.

**Comment by lyrixx** [comment]
Yeah, every sensible decision is really easier with a clear use case. Thanks.

**Comment by fduch** [comment]
> @meDavid Indeed, it's better to listen the announce event in your use case.
> @lyrixx My usecase is indeed resolved using the announce event.

@lyrixx @meDavid please note that `announce` event can redundantly waste the time computing enabled transitions (since it [involves guards processing](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Workflow.php#L168)) in case when you simply need to perform cascade processing.
