### ISSUE TITLE
Twig_Error_Syntax

### ISSUE THREAD

**Issue by RimBouda** [symfony/symfony#21446]
Bonjour, j'espere avoir de l'aide.
Je suis débutante avec Symfony 3 et j'ai cette erreur que jen'arrive pas a résoudre. j'espere trouver une solution en votre aide. Merci. 
Et voici l'erreur : 

Twig_Error_Syntax in classes.php line 5280: An exception has been thrown during the compilation of a template ("Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in /opt/lampp/htdocs/Symfony/var/cache/dev/classes.php on line 5573 and defined") in "@Twig/Exception/exception_full.html.twig".

**Comment by FabienPapet** [comment]
Bonjour, ce repository n'est pas fait pour du support, utilisez plutôt stackoverflow pour cela. De plus, l’utilisation de l'anglais est obligatoire ici.
