### ISSUE TITLE
[OptionsResolver] Normalizer is not called when no default is set for option and no value is provided for it

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony#21448]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.7.23

I found this issue through working with symfony forms. The normalizer for the `data` option does not get called if 1. `setDefault()` is not called first for the option **AND** 2. no value is provided for it. The same goes for all other options.   
Strictly speaking this complies IMO with the semantics of "normalizing" an option, i.e: there is no normalization of the value when there is no value.   
But I'm using the normalizer to basically populate the option based on the other options if no value is provided for it. So this could be a useful feature.  
My use case in forms goes as follows:   
I have a field where a user should be selected and I want this to default to the current user when no data is provided for it **AND** a `default_current_user` option is set to **true**.

**Comment by HeahDude** [comment]
Hi @thedamnedrhino, your use case is already handle by the resolver, just use a lazy option:
```php
$resolver->setDefault('data', function (Options $options, $previousDefault) {
    // access other options with $options['other_option']
    return 'new default';
})
```

**Comment by thedamnedrhino** [comment]
@HeahDude, thank you I wasn't aware of that.

**Comment by javiereguiluz** [comment]
Closing it as "already fixed" then.
