### ISSUE TITLE
[Debug] PHP 7 Throwable not handled with ExceptionHandler

### ISSUE THREAD

**Issue by CarsonF** [symfony/symfony#21464]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

[ExceptionHandler::handle](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Debug/ExceptionHandler.php#L117) typehints `Exception` and fails when `Error` is given. `ErrorHandler` accounts for `Throwable` but `ExceptionHandler` does not.

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by CarsonF** [comment]
It only happens when `ErrorHandler` is not registered as that converts the `Error / Throwable` to an `Exception`.

**Comment by xabbuh** [comment]
@nicolas-grekas Can you have a look here? :)

**Comment by nicolas-grekas** [comment]
No bug here: the exception handler should be used in conjuctin with `ErrorHandler`, which is in charge of many things, among them converting `Error` to `FatalErrorException`, then calling this method.
