### ISSUE TITLE
[WebProfiler] Profiler broken using a base url in RequestContext

### ISSUE THREAD

**Issue by eliecharra** [symfony/symfony#21480]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.19

I have a symfony 2.7 application running behind a nginx reverse proxy using a base path :

```nginx
server {
        listen   80;
        server_name xxxxxxx.fr;
        location /foo/bar/ {
            proxy_pass http://backend/;
        }
}
```

In my Symfony application I have the following listener which update the request context host and base url :

```php
<?php

namespace OrangeBundle\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Routing\RequestContext;

class RouterListener implements EventSubscriberInterface
{

    protected $host;
    protected $baseUrl;
    /**
     * @var RequestContext
     */
    protected $context;


    public function __construct(
        $host,
        $baseUrl,
        RequestContext $context
    )
    {
        $this->host = $host;
        $this->baseUrl = $baseUrl;
        $this->context = $context;
    }

    public function onKernelRequest(GetResponseEvent $event)
    {
        if ($event->isMasterRequest()) {
            $this->context->setHost($this->host);
            $this->context->setBaseUrl($this->baseUrl);
        }
    }

    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::REQUEST => array(array('onKernelRequest', 31)),
        );
    }
}
```

Everything works fine, except when using `render` with a path in twig.
The WebProfiler is using render to display the web debug toolbar, but using the base url the kernel throw a not found exception.

![selection_085](https://cloud.githubusercontent.com/assets/6154987/22477800/c640a9ce-e7e7-11e6-81f7-268973a75bb4.jpg)

Is there a known workaround for these kind of scenario ?

Thanks !

**Comment by javiereguiluz** [comment]
If you remove the `if ($event->isMasterRequest()) {` check in the `RouterListener`, does the issue persist?

**Comment by eliecharra** [comment]
Yeah actually the request which generate the `{{ render(path()) }}` is not a sub request, so removing the check on isMasterRequest does not impact this behaviour.

Following lines are breaking the profiler :

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/layout.html.twig#L5
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/layout.html.twig#L62

I've forked **symfony/symfony-demo** [here](https://github.com/eliecharra/symfony-demo) to demonstrate the bug :

**Ensure that no other service is listening on port 80**

```
$ git clone git@github.com:eliecharra/symfony-demo.git && cd symfony-demo
$ docker-compose up -d
$ docker-compose exec web composer install
$ docker-compose exec web chmod 777 -R var/cache var/logs var/sessions
```

Then try to access http://localhost/foo/bar/_profiler/empty/search/results?limit=10 using a web browser.

App is working under well http://localhost/foo/bar/

It's not just the profiler, every `{{ render(path(...)) }}` is broken.

**Comment by stof** [comment]
Well, IMO, this is because your own overriding of the context is incomplete (you may not override all places referencing these).
A better way would be to configure the system to recognize the right base path from the start rather than hacking into Symfony to replace the configuration done by symfony (the Request object is not reconfigured by your code for instance)

**Comment by eliecharra** [comment]
> A better way would be to configure the system to recognize the right base path from the start rather than hacking into Symfony to replace the configuration done by symfony

Any hint on proper way for doing that ?

I tried to override following params according [this page](https://symfony.com/doc/current/console/request_context.html) in documentation

```yaml
    router.request_context.host: localhost
    router.request_context.base_url: foo/bar
```

Symfony still redirect me without base url.
![selection_014](https://cloud.githubusercontent.com/assets/6154987/22513814/a263914a-e89d-11e6-8824-8c41d558eaca.png)

**Comment by stof** [comment]
this is about webserver configuration though, not about configuration in the project, as we need the logic of Request to determine the right path.

But I don't know exactly how to do it. I haven't done crazy webserver configurations

**Comment by eliecharra** [comment]
Hum maybe we should close this issue as the problem is not related to the WebProfiler itself.

I'm still experiencing issues trying to run Symfony under a reverse proxy with a base path, maybe I'll open another issue more relevant for this behaviour.

**Comment by sod** [comment]
@eliecharra could you workaround this issue?
