### ISSUE TITLE
[SymfonyStyle] Add simple styled lines

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#21489]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | x.y.z

I've found myself using a syntax like this:

    $this->ioWriter->block('Starting the Daemon...', 'INFO', 'fg=blue');

So, maybe useful to add some methods like:

    $this->ioWriter->writelnInfo('Starting the Daemon...', 'INFO', 'fg=blue');
    $this->ioWriter->writelnError('Starting the Daemon...', 'ERROR', 'fg=red');
    ...

Those methods simply print a line, without background colors and without occupy a lot of space like the methods `warning()`, ecc.

What do you think about?

**Comment by Aerendir** [comment]
@xabbuh The fact you've added the labels means that if I implement the requested features they will be merged? Because before putting efforts in them, I'd like to understand if they will be or not merged! Thank you!

**Comment by iltar** [comment]
Are you using the `SymfonyStyle`? Because that's exactly what this provides: http://symfony.com/doc/current/console/style.html#result-methods

**Comment by Aerendir** [comment]
@iltar , yes, I'm using it. But those methods render a block this way:

    //// background //// background //// background //// background//// background //// background                                                                                                                        
     [OK] Waiting for new ScheduledJobs to process...                                                                       
    //// background //// background //// background //// background//// background //// background                       

While I want a simple line like this:

    [INFO] Starting the Daemon... 

![schermata 2017-02-03 alle 13 27 50](https://cloud.githubusercontent.com/assets/1968622/22591397/9a7dd706-ea14-11e6-8c86-c636c126b8d4.png)
                                                                                                                    
As you can see, the current methods provided by `SymfonyStyle` renders a line with a background (`[OK] Waiting for new ScheduledJobs to process...`) while I want a simple colored line like `[INFO] Starting the Daemon...`.

**Comment by iltar** [comment]
That's why you can implement your own style that does this

**Comment by Aerendir** [comment]
@iltar , yes, for sure I can implement my own styles... But I think those can be useful also for other people o.O Don't they?

**Comment by Aerendir** [comment]
However, is exactly this the reason for which I'm first asking if it can be of any interest: because if it isn't I'll don't put effort in it and I'll go the "dirty" way :)

**Comment by ogizanagi** [comment]
I think using the `SymfonyStyle::block()` method is enough for this on userland, along with creating your own derived style.
So IMHO, it's not worth it :)

**Comment by Aerendir** [comment]
Excuse me if I'm insisting, but I'm speaking of standard colors for standard kinds of messages. Also Bootstrap has [helper classes](http://getbootstrap.com/css/#helper-classes). Why should Symfony not have them? Only because each one can recreate them by him/herself? Is as saying that a framework is not required as each one can write by himself a DomCrawler, a Process component or a StopWatch component. The meaning of a framework is exactly this: provide some common functionalities, doesn't it?

I don't understand why you don't agree. Say "is enough" doesn't seem to me a sufficient reply. "Sufficient enough" for who? Untile some days ago I didn't care if the `SymfonyStyle` class had or not those methods. But now I'm writing a lot of commands in many different applications and the only alternative I have at the moment is to create a dedicated composer package that only contains those standard styles. And for sure someone else in my own situation will find useful to have a convenient method to write them.

I'll go anyway to write them, as I thinnk they might be useful... Then who decides if they are worth the work or not will decide...

I'm sorry for this discussion...

**Comment by stof** [comment]
> I don't understand why you don't agree. Say "is enough" doesn't seem to me a sufficient reply. "Sufficient enough" for who? Untile some days ago I didn't care if the SymfonyStyle class had or not those methods. But now I'm writing a lot of commands in many different applications and the only alternative I have at the moment is to create a dedicated composer package that only contains those standard styles. And for sure someone else in my own situation will find useful to have a convenient method to write them.

Well, you case means that you want to have your own style of output, not matching the Symfony one. So creating your own style class makes sense.

Adding fully flexible methods allowing to pass styles as argument is not a good idea IMO:
- it defeats the purpose of the Style class of providing a consistent styling of output (as the styles are coming from the outside)
- it does not provide anything compared to direct styling of the message (with the API supported since Symfony 2.0) AFAICT, while being less powerful (as the existing system supports styling parts of the string only when wanted)

**Comment by Aerendir** [comment]
But I don't want to create an error style yellow colored... Only an error line red colored... o.O A kind of message a lot of people would use if present (without the needs to write a dedicated class)...
