### ISSUE TITLE
Wrong query generated by query builder

### ISSUE THREAD

**Issue by bettinz** [symfony/symfony#21483]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

Hello, I've a problem with forms, and I can't understand if it's related to doctrine or symfony.
I have 2 entities: user and stable. I've a table called user_for_stable with user_id and stable_id

So I've created this simple form called "CowType":

```php
->add('stable', EntityType::class, array(
                'class'=>'AppBundle\Entity\Stable',
                'multiple'=>false,
                'expanded'=>false,
                'choice_label'=>'stableName',
                'query_builder'=> function (EntityRepository $er) use ($options) {
                    return $er->createQueryBuilder('u')
                        ->where(':userobj MEMBER OF u.users')
                        ->setParameter("userobj", $options['userObj'] );
                },
            ))
```
In the controller I've:
```php
$form = $this->createForm(CowType::class, $cow, array('userObj'=>$this->getUser()));
```

But the generated query is wrong:

```sql
SELECT s0_.id AS id_0, s0_.address AS address_1, s0_.city AS city_2, s0_.zip AS zip_3, s0_.state AS state_4, s0_.stable_name AS stable_name_5 FROM stable s0_ WHERE EXISTS (SELECT 1 FROM user_for_stable u1_ WHERE s0_.id = u1_.stable_id AND u1_.id = ?)
```
it should be

```sql
SELECT s0_.id AS id_0, s0_.address AS address_1, s0_.city AS city_2, s0_.zip AS zip_3, s0_.state AS state_4, s0_.stable_name AS stable_name_5 FROM stable s0_ WHERE EXISTS (SELECT 1 FROM user_for_stable u1_ WHERE s0_.id = u1_.stable_id AND u1_.user_id = ?)
```

in stable entity I've:

```php
     /**
     * @var
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\UserForStable", mappedBy="stable")
     */

    private $users;
```

This code is working as expected:

```php
$q= $er->createQueryBuilder('u');
                    $q->select('s')
                        ->from('AppBundle:Stable', 's')
                        ->leftJoin('s.users', 'usersInStable', 'WHERE', 'usersInStable.user = :userObj' )
                        ->setParameter('userObj', $options['userObj']);
```
the generated sql is

```sql
SELECT s0_.id AS id_0, s0_.address AS address_1, s0_.city AS city_2, s0_.zip AS zip_3, s0_.state AS state_4, s0_.stable_name AS stable_name_5, s0_.tav AS tav_6, s0_.kg_for_notch AS kg_for_notch_7, s0_.number_of_meal AS number_of_meal_8 FROM stable s1_, stable s0_ LEFT JOIN user_for_stable u2_ ON s0_.id = u2_.stable_id WHERE u2_.user_id = ?
```

Can you help me? Thanks

**Comment by HeahDude** [comment]
Hi @bettinz, I think the problem is that the `EntityRepository` passed to the callable is the one handling the `Stable` class instead of the relationship.

I don't how to exactly how solve this (if this is it), but without looking into it right now, maybe you could try to handle the logic in the repository method:
```php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\StableRepository")
 */
class Stable
{
    // ...`
```
```php
namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class StableRepository extends EntityRepository
{
    public function getQueryForUser(User $user): QueryBuilder
    {
        // ...
```
```php
use AppBundle\Entity\Stable;
use AppBundle\Repository\StableRepository;

$builder->add('stable', EntityType::class, [
    'class' => Stable::class,
    'multiple' => false,
    'expanded' => false,
    'choice_label' => 'stableName',
    'query_builder'=> function (StableRepository $r) use ($options) {
        return $r-> getQueryForUser($options['user']);
    },
]);
```

**Comment by bettinz** [comment]
Hello, I've created a simple project here:
https://github.com/bettinz/doctrineTest

**Comment by stof** [comment]
If the generated SQL for your DQL is wrong, this should be reported to the Doctrine ORM, not to Symfony. Symfony will *not* generate any SQL there

**Comment by bettinz** [comment]
Hello @stof , I know, but I can't understand if it's a problem with symfony and forms (and query builder) or a problem with Doctrine. 😃

**Comment by HeahDude** [comment]
I don't think the query is wrong the problem is that the repository passed to the callable is defined by the `class` option, here another entity is really target as a joined relationship.

We cannot solve this out if the box in the core or in Doctrine. You need to use either a custom a loader or to use the proper repository.

**Comment by stof** [comment]
Well, the repository being used is the repository for the selected class. And this works fine. your query really select in the ``stable`` table. So all is fine here.
The wrong SQL is only the one generated for the ``:userobj MEMBER OF u.users`` part of the DQL. And this has nothing to do with Symfony. Symfony is *never* involved in the conversion from DQL to SQL. this is purely a Doctrine ORM layer

**Comment by bettinz** [comment]
The doctrine guys are asking me for a case test: can anyone help me to build that and prove this specific situation? Thanks 😃

**Comment by HeahDude** [comment]
I think we can close here, since this is definitely Doctrine related, see https://github.com/doctrine/doctrine2/issues/6270.

**Comment by bettinz** [comment]
Sure, I close right now. Thanks ;)
