### ISSUE TITLE
[Workflow] Block or Revert event?

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#21490]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | maybe
| BC Break report? | no
| RFC?             | no
| Symfony version  | >3.2

Hi,

I have the following scenario.

I have a `bill` transition, which moves the state from `not_billed` to `billed`. We use a 3rd party billing system though an API. 

I wanted to integrate the API call with the listener, but ran into a problem. The API we use is pretty unstable (I know... the client wanted to use that specific provider), and when it fails, I would somehow need to block the event, but there is no way to do that once it has passed the guard phase.

My current code looks like this:

```$workflow->apply($order, 'bill')```
```php
/**
 * Automatically creates the invoice.
 *
 * @DI\Observe("workflow.order_status.enter.billed")
 */
public function onBill(Event $event)
{
    $order = $event->getSubject();
    $result = $this->invoiceHandler->createInvoice($order);

    if ($result === false) {
        return false; // I would need to do something here to prevent state change.
    }

    $order->setInvoiceId($result['id']);
}
```
I cannot really move this logic to a guard, because that would result in a new invoice every time `can` method is called.

The one thing that comes to mind is to flip it around... only apply when the invoice has been created, but that would make the whole thing useless.

Any advice?

Thanks,
Adam

**Comment by unkind** [comment]
> that would make the whole thing useless

You can dump graph with GraphvizDumper. That's awesome. But probably useless, that's true.

**Comment by Padam87** [comment]
@unkind I'm sure the client would be happy to hear that. "It breaks on every 10th order, but hey, look at that cool graph" :)

**Comment by lyrixx** [comment]
Hello.

IIUC your issue, you can simply throw an exception (not related to the workflow component) to abort the transition?

**Comment by Padam87** [comment]
That is what I ended up doing. I was looking for a way to reject the event, but a simple exception will do
