### ISSUE TITLE
[Doctrine][CacheWarmer] Check the generated proxies

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#21509]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.0+

When using Doctrine with Symfony, sometimes the generated entity proxies are invalid (e.g. if the entity is `final`, which cause an issue as proxies are generated by extending the original class). 

The `ProxyCacheWarmer` class which is called during `bin/console cache:warmup` generates the proxies but do not check them. This means that you figure out that a generated proxy is invalid only at runtime (during tests if you cover that case or at any other time where a proxy is being used otherwise).

As the proxy factory returns the generated proxies, WDYT of doing an `include_once` on all the generated proxies during the cache warmup phase to ensure they are all valid?

**Comment by iltar** [comment]
Missing a title in the issue (besides of the tags)

**Comment by xabbuh** [comment]
Couldn't this be caught in the Doctrine proxy factory and throw an exception their?

**Comment by theofidry** [comment]
This may be done in Doctrine proxy factory, but throwing an exception is not doable in <PHP7 at least, as it may throw a FatalError

**Comment by Ocramius** [comment]
Handled in https://github.com/doctrine/common/pull/771

**Comment by theofidry** [comment]
Thanks for that quick fix!
