### ISSUE TITLE
[Debug] BufferingLogger is not used when not displaying errors

### ISSUE THREAD

**Issue by CarsonF** [symfony/symfony#21500]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.8+

In [`Debug::enable`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Debug/Debug.php#L55-L59) the buffering logger is only given to the `ErrorHandler` when display errors is true. Wouldn't that mean that errors before a proper logger is given will be swallowed in production? It seems like the buffering logger should be independent of the display errors flag.

**Comment by nicolas-grekas** [comment]
Debug::enable is just a helper. Changing it's behavior is not possible for BC. If it doesn't fit your need, just wire things by yourself :)
