### ISSUE TITLE
[DI component] Autowiring should ignore anonymous classes

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony#21506]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^2.8\|^3.0

Hi,
I've found a little bug into the autowiring component.
Suppose you have set up `/src/AppBundle/Services` to be autowired.
And you have an `AppBundle\Services\MyService` requiring something into the constructor (let's say, `Psr\Log\LoggerInterface`).
And everything works well.

Then, somewhere in `AppBundle\Services\MyService`, let's say, `AppBundle\Services\MyService::process()`, you add the following code:
```php
$fn = function (\SplSubject $splSubject) {
    $this->logger->log('Something has changed, somewhere');
};

$splSubject->attach(new class($fn) implements \SplObserver {
    
    /**
     * @var callable
     */
    private $fn;

    /**
     * __anonymous$object$\SplObserver@852 constructor.
     * @param callable $fn
     */
    public function __construct(callable $fn) {
        $this->fn = $fn;
    }

    /**
     * @inheritDoc
     */
    public function update(\SplSubject $subject) {
        $fn = $this->fn;
        $fn($subject);
    }
});
```

You'll get the following exception:
```
RuntimeException in AutowirePass.php line 95:
Unable to autowire argument index 0 ($fn) for the service "class@anonymous/var/www/myappp/src/appbundle/services/myservice.php0x7f5571837bff". If this is an object, give it a type-hint. Otherwise, specify this argument's value explicitly.
```

I think the Autowiring component doesn't check if the class is anonymous or not, and I don't think anonymous classes should be autowired. 
This is PHP7+ specific, so calling `$reflectionClass->isAnonymous()` into the `AutowirePass` would require a php version check first.

**Comment by stof** [comment]
Where are you putting such code ? I don't see any code related to the DI component in your snippet.

Btw, the Symfony DI container is meant to be dumped (unless you don't care about performance), and anonymous classes are not an option in this case.

**Comment by bpolaszek** [comment]
Hi @stof,

I'm really sorry, though the exception was raised from the `AutowirePass`, after further investigations the issue is not related to the DI component itself but by its use with `dunglas/action-bundle`.

When not using DunglasActionBundle autowiring, but creating the service into `services.yml` with `autowire: true`, the anonymous class used in the code is simply ignored, as expected.

I will report the issue in the proper github repo.

Sorry for the inconvenience.
Ben
