### ISSUE TITLE
[DI] Invalid syntax in proxy class generated by overridden getter

### ISSUE THREAD

**Issue by jean-pasqualini** [symfony/symfony#21507]
@nicolas-grekas 

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | master

When use overriden getter on class has already one constructor, the syntax of proxy class generated is invalid.

The constructor generated not contains '__constructor'.

TODO : 
- [X] Make pull request
- [X] Write test fail
- [X] Fix
- [X] Run test pass

**Comment by nicolas-grekas** [comment]
do you want to work on a PR?

**Comment by jean-pasqualini** [comment]
@nicolas-grekas yes

**Comment by jean-pasqualini** [comment]
https://github.com/symfony/symfony/pull/21508
