### ISSUE TITLE
[WDT] Translation messages are too tight, causing word-breaks

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#21519]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2 (possibly others)

The screenshot should be self explanatory. My guess is that the CSS is simply allowing words to break. This would be an excellent case to use the full screen width as I still have a lot of white space left on the right. 

![image](https://cloud.githubusercontent.com/assets/1754678/22583763/e617cbb6-e9ee-11e6-899a-1b8303055014.png)

_Sorry for the above whitespace, but this is the real element size in the WDT it seems, using an extension to capture it._

**Comment by javiereguiluz** [comment]
This was on my TODO list. I want to make these changes:

* Prevent word breaks in domain and message ID
* Allow word breaks in the message preview

(... and about the full screen, it's something that we've explained lots of times: readability increases as you increase the line length ... until a point where the readability plunges ... text lines in books, newspapers, websites, etc. are not immensely long for this reason)

**Comment by iltar** [comment]
In case of bigger texts, could we use an ellipsis with an "expand" button? 9/10 times I'm not interested in reading big texts here anyway.

**Comment by javiereguiluz** [comment]
Closing as "fixed". I can't find the PR, but we fixed this a while ago adding `nowrap` classes to message IDs and domains:

![translation-panel](https://user-images.githubusercontent.com/73419/30265276-feee8f0e-96db-11e7-89b9-c0c58f0ff05d.png)
