### ISSUE TITLE
symfony/yaml versioning policy

### ISSUE THREAD

**Issue by urbantom** [symfony/symfony#21510]
| Q                           | A
| ------------------------ | -----
| Bug report?           | no
| Feature request?  | no
| BC Break report?  | no
| RFC?                    | no
| Symfony version   | N/A

Why do you maintain so many versions as well as so many active branches assigned to versions?

Context: current phing/phing (2.16) package requires symfony/yaml ^3.1, but drupal/core 8.2.5 (complying the criteria ~8.0 defined in composer.json distributed with drupal-composer/drupal-project project) requires symfony/yaml ~2.8. So how to build (but not crack) environment that provides drupal/core as well as phing/phing?

(Sorry, if it is lame question. Thanks for patience, in advance.)

**Comment by javiereguiluz** [comment]
You should check this article, that explains our release process in detail: https://symfony.com/doc/current/contributing/community/releases.html

**Comment by fabpot** [comment]
Phing should probably depend on `2.8|3.1` instead. Closing as there is nothing we can do.

**Comment by urbantom** [comment]
Thx4help
