### ISSUE TITLE
[Console] Cron processes wrap error messages at 80 characters

### ISSUE THREAD

**Issue by duncan3dc** [symfony/symfony#21513]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.0

I recently upgraded from 3.1.2 and noticed that my Exception messages in the log files have started wrapping at 80 characters, eg:
```
  [DomainException]                                                            
  Transactions for financial year 2017/18 are held until year end has complet  
  ed
```

It looks like #20328 changed the behavior of terminals with undefined widths from unlimited to `80` characters, was this intentional? Is there another way to fix the original problem @nicolas-grekas reported? (caused by #19724)

**Comment by nicolas-grekas** [comment]
Was intentional yes (no breaking your script, but making the behavior predictable)
You should create the `COLUMNS` env var in the context of your cron script if you want precise control here.

**Comment by duncan3dc** [comment]
@nikita2206 I want it to be unbounded again though, how do I achieve that with `COLUMNS`?

**Comment by duncan3dc** [comment]
Symfony changes the environment variables meaning there's then no way to tell that a terminal is unbounded, is there? Shouldn't Symfony use "namespaced" environment variables? eg use `SYMFONY_COLUMNS` if it exists, otherwise fallback to `COLUMNS`?

**Comment by nicolas-grekas** [comment]
Did you try with `COLUMNS=0`?
About the namespace, why? `COLUMNS` is used by eg some Python programs to configure exactly the same setting. There is nothing Symfony specific in this need to control the width of the output.

**Comment by stof** [comment]
COLUMNS is the environment variables that some terminals are setting automatically based on their width. So in them, it means things work out of the box instead of having you to run ``export SYMFONY_COLUMNS="$COLUMNS"`` each time you open or resize your terminal

**Comment by duncan3dc** [comment]
@nicolas-grekas Setting `COLUMNS=0` doesn't do anything, because #20328 no longer permits zero width, it will always override it with `80` since that change.

@stof Requiring everybody export `SYMFONY_COLUMNS` would be silly, I said fallback to `COLUMNS` if `SYMFONY_COLUMNS` doesn't exist.

I thought the issue was that `Process` wasn't picking up the width determined by `Console`. So I offered `SYMFONY_COLUMNS` as a potential solution to that problem, instead of manipulating `COLUMNS` (which was correctly set as zero)

**Comment by nicolas-grekas** [comment]
Did you actually try it ?
See https://github.com/symfony/symfony/pull/20328/files#diff-ff02f73646f2e1cbcfeb955ca8fda12aL26 which is the code path that should be applicable when 0 is used.

**Comment by duncan3dc** [comment]
@nicolas-grekas Of course I tried it, that code path won't be applicable for `0` at all, `if ("0")` is false in PHP: https://3v4l.org/8ZEK5

**Comment by stof** [comment]
if we want to allow setting the env variable to 0, we should use ``if (false !== $width = getenv('COLUMNS'))``

**Comment by nicolas-grekas** [comment]
Indeed, then what about allowing zero here? (and making sure that the code base can deal with it)

**Comment by nicolas-grekas** [comment]
@duncan3dc would you like to submit a PR about that?

**Comment by duncan3dc** [comment]
@nicolas-grekas Sure thing, thanks
