### ISSUE TITLE
[Form] The index 0 is not within the property path

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#21511]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | x.y.z

The tests of my bundle https://github.com/Aerendir/stripe-bundle fails with PHP 7.2.

The reported error is:

> 1) SerendipityHQ\Bundle\StripeBundle\Tests\Model\CreditCardStripeTokenTypeTest::testSubmitValidData
> Symfony\Component\PropertyAccess\Exception\OutOfBoundsException: **The index 0 is not within the property path**
> /home/travis/build/Aerendir/stripe-bundle/vendor/symfony/property-access/PropertyPath.php:188
> /home/travis/build/Aerendir/stripe-bundle/vendor/symfony/property-access/PropertyAccessor.php:218
> /home/travis/build/Aerendir/stripe-bundle/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:93
> /home/travis/build/Aerendir/stripe-bundle/vendor/symfony/form/Form.php:618
> /home/travis/build/Aerendir/stripe-bundle/Tests/Form/Type/CreditCardStripeTokenTypeTest.php:23

The code is [here](https://github.com/Aerendir/stripe-bundle/blob/master/Tests/Form/Type/CreditCardStripeTokenTypeTest.php).
The build is [here](https://travis-ci.org/Aerendir/stripe-bundle/jobs/197705088).

Unfortunately I have no idea of how to fix the problem.

**Comment by mvrhov** [comment]
I think something like that was reported a few days ago and it might also be fixed in latest 3.2/master
I can't seem to find the issue.

**Comment by xabbuh** [comment]
@Aerendir Is this still an issue or was it solved in the meantime as suggested by @mvrhov?

**Comment by Aerendir** [comment]
@xabbuh , Unfortunately I cannot test it with the version 3.2 at the moment...

**Comment by xabbuh** [comment]
Thanks for the feedback. I am closing here for now then. Please let us know if you still experience the issue with the latest patch releases and best provide an example to reproduce your issue and we can reopen then.

**Comment by Aerendir** [comment]
@xabbuh Ok, thank you! 👍

**Comment by garak** [comment]
Just found this issue via google search. I'm facing the same problem with php 7.2 and latest Symfony (currently `3.2.8`

**Comment by xabbuh** [comment]
@garak Please provide some steps that allow to reproduce your issue.

**Comment by Aerendir** [comment]
I've just get again this error in the continuous integration server run by Travis.

Here the log: https://travis-ci.org/Aerendir/stripe-bundle/jobs/233196004

Here the unit test: https://github.com/Aerendir/stripe-bundle/blob/master/Tests/Form/Type/CreditCardStripeTokenTypeTest.php#L23

Here the form type that causes the error: https://github.com/Aerendir/stripe-bundle/blob/master/Form/Type/CreditCardStripeTokenType.php

Hope this may help you.

**Comment by xabbuh** [comment]
@Aerendir Can you check if this is related to the BC break in PHP's `preg_match()` behaviour that was discussed in #22707?? If so, we can simply wait until this is fixed in PHP itself.

**Comment by Aerendir** [comment]
No, unfortunately not: the error happens in the nightly build and I don't have ways to install it.
Anyway yes, maybe it will be fixed by the PHP's team itself...

**Comment by xabbuh** [comment]
What I mean is: Do you still experience the issue if made the change that was proposed in #22707?
