### ISSUE TITLE
[Console] Invert black and white colors for fg and bg

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#21525]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

Currently the value that define the colors white and black seems to be inverted.

This is the current output produced:

```
$ioWriter->block('Black white', null, 'fg=white;bg=black');
$ioWriter->block('White black', null, 'fg=black;bg=white');
```

![schermata 2017-02-03 alle 17 52 46](https://cloud.githubusercontent.com/assets/1968622/22600163/9fdd45ea-ea39-11e6-8f12-c5b39052cdef.png)

The right output should be this instead:

This bug affects also the legibility of other messages as shown below:

![schermata 2017-02-03 alle 17 53 55](https://cloud.githubusercontent.com/assets/1968622/22600194/c2607f9c-ea39-11e6-927f-686a979796ab.png)

![schermata 2017-02-03 alle 17 52 23](https://cloud.githubusercontent.com/assets/1968622/22600145/8a9c6080-ea39-11e6-95d7-7fe51cbe1fd9.png)

**Comment by iltar** [comment]
I think this might be related to the color definitions of your terminal, it's working fine for me

**Comment by Aerendir** [comment]
Mmm... Can you better explain what are you meaning? How can I check them and change?

**Comment by Aerendir** [comment]
Ok, @fabpot reply me here https://github.com/symfony/symfony/pull/21526#issuecomment-277303006

**Comment by Aerendir** [comment]
@iltar , when you start the web server, does you see this?
![schermata 2017-02-04 alle 10 10 00](https://cloud.githubusercontent.com/assets/1968622/22617324/3bdfd0ce-eac2-11e6-8c92-78c655792e1e.png)
(white text "[OK] Web server listening on http://127.0.0.1:8000" in a yellow box)

**Comment by iltar** [comment]
This is what it looks like for me, but I don't have linux at home. I can check again on Monday, but I have modified my colors slightly.

![image](https://cloud.githubusercontent.com/assets/1754678/22617511/57484db4-eac7-11e6-9d84-a4ec6b59d870.png)

**Comment by Aerendir** [comment]
@iltar I found the problem: is PHPStorm!

This is how the colors appear on the Mac's Terminal:

<img width="433" alt="schermata 2017-02-04 alle 11 38 04" src="https://cloud.githubusercontent.com/assets/1968622/22617842/b767568e-eace-11e6-9098-487aec80d460.png">

So the problem is the way PHPStrm configures the ANSI colors (I searched for this and on StackOverflow there a lot of question about this: I've only to find the solution to correctly set the colors).
