### ISSUE TITLE
phpunit test with container calls takes ~20x more time

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#21549]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

Created simple gist to show this https://gist.github.com/tarlepp/be57391ceead9099d66e3500001ae58b also tested with phpunit 5.7.11 and the results are the same.

I tracked this to commit https://github.com/symfony/symfony/commit/e59f0e0fd7323902fa025e2eae96ce9eb91b24c5#diff-0e793081ceb720201745c982a568903fL1046

Maybe that `$container->setAlias('annotation_reader', 'annotations.cached_reader');` was removed by mistake ?

**Comment by nicolas-grekas** [comment]
Can you please try #21556 and report if it fixes the issue?

**Comment by nicolas-grekas** [comment]
ping @tarlepp

**Comment by tarlepp** [comment]
@nicolas-grekas I'll try that tonight, currently at work so cannot test that now...

**Comment by tarlepp** [comment]
@nicolas-grekas Just tested that (made those changes manually to my project) and results are the same :(

**Comment by nicolas-grekas** [comment]
are you sure you rebuilt the container/cleared the cache - including the bootstrap.cache.php file?
can you share a blackfire profile then?

**Comment by tarlepp** [comment]
removed whole `var` directory contents after those modifications - [https://blackfire.io/profiles/8f265ea9-299e-4cfb-867a-43e6d67bd4f6/graph](blackfire profile)

**Comment by nicolas-grekas** [comment]
CachedReader is not called but AnnotationReader is - it looks like the patch is not applied or that the annotation cache is not enabled...

**Comment by tarlepp** [comment]
Hmm, I'm using SensioFrameworkExtraBundle with default configuration, that annotation cache should be enabled by default - right ?

**Comment by tarlepp** [comment]
@nicolas-grekas It seems that I messed something up on that manual update, just fetched your PR directly and it seems that all is ok! 

Blackfire profile: https://blackfire.io/profiles/12c9f174-a059-4525-ba34-5e2bdb070f8d/graph

Thanks for your help really!

**Comment by teohhanhui** [comment]
There is still a very noticeable slowdown when upgrading from 3.2.2 to 3.2.4. I don't have access to Blackfire (because there is no Alpine support yet), so here's hoping somebody else could fill in with similar reports.
