### ISSUE TITLE
UniqueEntityValidator with multiple constraints fails if the first constraint is null

### ISSUE THREAD

**Issue by gigib82** [symfony/symfony#21554]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

Scenario: I'm validating an entity like this
```php
$validator->validate($device, [
    new UniqueEntity([
        'fields' => ['accountId', 'tenantUuid'],
        'em' => $provisioningEm
    ])
]);
```

If `accountId` happens to be null, [UniqueEntityValidator](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L90-L94) will now exclude it from the constraint list (since commit 1e3421d ), failing [later on](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L136-L137) because `$criteria[$fields[0]]` is an invalid array access: `fields[0]` is the string "accountId", which is not in `$criteria`. 
Reverting lines 88-94 to the version before the commit linked above fixes the issue.

**Comment by xabbuh** [comment]
@gigib82 Sorry for breaking this. Can you confirm that #21562 fixes the issue for you?

**Comment by gigib82** [comment]
Tested #21562: there is now a behavioural difference with respect to the previous released version.
Using my own example, a null `accountId` and a non-null `tenantUuid` used to always pass validation, even if in the DB there was already a record with null `accountId` and the same `tenantUuid`. The same scenario now fails validation.
I'm not sure which is the most correct behaviour, but merging this will cause a small BC break.

**Comment by xabbuh** [comment]
@gigib82 Did you enable or disable the `ignoreNull` option?

**Comment by gigib82** [comment]
No, never explicitly set that option.

**Comment by xabbuh** [comment]
@gigib82 You are right. It's not related to the changes from #21562, but was introduced in #21431. You were just not able to see the wrong behaviour due to the initial issue here. I'll work on fixing it completely.

**Comment by xabbuh** [comment]
@gigib82 I updated #21562. Would you mind checking it again?

**Comment by gigib82** [comment]
The same test suite that spotted the errors is now ok, so I would say #21562 fixes the error

**Comment by xabbuh** [comment]
Thanks for the confirmation.
