### ISSUE TITLE
-2000% performance with Symfony 3.2.3 (server CPU overload)

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#21559]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | -
| RFC?             | -
| Symfony version  | v3.2.3

Hello, 

We run a multi-tenant application on Symfony `v3.2.1`. When we upgraded the vendors (only minor version) the application didn't respond anymore, and all our server pool reached 100% of usage (when it's <5% usually).

I tracked down, and upgraded *vendor by vendor*, until I upgraded from Symfony `v3.2.1` to `v3.2.3`, as soon as the update landed the production, the same behaviour happened again.
All servers went to 100% CPU usage, and we couldn't get a single page loaded.

Even after 5 minutes after turning webserver off, all PHP threads didn't seem to be killed. Had to manually restart PHP to free all the CPU's.

Only Symfony were upgraded to reproduce the "bug" (I did it twice on production to be sure it was really a Symfony problem)

Here are some charts showing the symptoms:
* [CPU load](https://www.evernote.com/l/ARGZCS64TPBNHphmdtTjAEp1tekGef8rp4g) 
* [Application Response time and traffic during the time where Symfony 3.2.3 was on production](https://www.evernote.com/l/ARFAF8LBb4NLIr1EM2XKKLpu_UMHdhxgegE)
* [Application response time 6 hours before the upgrade (running v3.2.1 for reference)](https://www.evernote.com/l/ARFwhCXjaLhME4i1BzeeXWYqpOq3esZgCyI
)

_System specs; 2 servers running (database on other servers):_  
- PHP FPM 7.0.15-1~dotdeb+8.1
- OPcache enabled
- Nginx 1.11.9
- Xeon CPU E5-1620 v2 @ 3.70GHz
- 32Go RAM

---

Same server, same settings, only Symfony version changes:

Symfony v3.2.1: **6,734ms**
![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier_](https://cloud.githubusercontent.com/assets/346010/22732257/d1794b82-eded-11e6-9a96-1923655e1c26.png)

Symfony v3.2.2:  **6,574ms**
![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier__et_composer_json_-_yprox-v2_-____workspace_yprox-v2_](https://cloud.githubusercontent.com/assets/346010/22732302/fb595b22-eded-11e6-9daa-4b90fe4dd4b0.png)

Symfony v3.2.3: **19,613ms**
![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier_](https://cloud.githubusercontent.com/assets/346010/22732329/0d5668e2-edee-11e6-90fb-0c1af475376d.png)

[Normal performance main request screenshot](https://www.evernote.com/l/AREwWWoVe1BAra_UIHygk-DjulOzdvgug3c) 
![symfony_profiler](https://cloud.githubusercontent.com/assets/346010/22733097/dd86ef8a-edf0-11e6-9eed-eafb33d8db5e.png)

VS [Degraded performance main request screenshot](https://www.evernote.com/l/ARGXk1g6i69OGIySk-B3zAbeZVJU5ncxaew)
![symfony_profiler](https://cloud.githubusercontent.com/assets/346010/22733086/d40a8d0e-edf0-11e6-83f9-b267f1c6e352.png)

## Blackfire comparaison
Here's the [blackfire comparaison](https://blackfire.io/profiles/compare/4632ae34-a20c-48a9-ae3f-a0492196ea79/graph)

**Comment by Simperfit** [comment]
@tristanbes Do you know where it takes that much time ? could it be related to #21556 ?

**Comment by gadelat** [comment]
I don't think it's related to that, since issue it fixes was introduced in Symfony 3.2.0, but OP says they did not have this problem on 3.2.1

**Comment by tristanbes** [comment]
Here's a [profiler trace captured by newrelic](https://www.evernote.com/l/AREeB1KonHtIVZ6iDa-lrpNL9irZ1hZ_ffw), but it's a partial one. Don't know if it's going to help you

**Comment by iltar** [comment]
You said you went from `v3.2.1` to `v3.2.3`, can you verify if `v3.2.2` is working?

**Comment by tristanbes** [comment]
@iltar I can't really risk another downtime especially after almost 4hours downtime yesterday. This application serves ~2k websites

**Comment by Simperfit** [comment]
@tristanbes Could you do test that locally ?

**Comment by tristanbes** [comment]
yes, onto that right now.

**Comment by tristanbes** [comment]
Same server, same settings, only Symfony version changes:

Symfony 3.2.1: *6734ms*

![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier_](https://cloud.githubusercontent.com/assets/346010/22732257/d1794b82-eded-11e6-9a96-1923655e1c26.png)

Symfony 3.2.2 *6574ms*
![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier__et_composer_json_-_yprox-v2_-____workspace_yprox-v2_](https://cloud.githubusercontent.com/assets/346010/22732302/fb595b22-eded-11e6-9daa-4b90fe4dd4b0.png)

Symfony 3.2.3 *19613ms*
![accueil_-_bc2e___reseau_national_de_diagnostic_immobilier__franchise_diagnostiqueur_immobilier_](https://cloud.githubusercontent.com/assets/346010/22732329/0d5668e2-edee-11e6-90fb-0c1af475376d.png)

[Normal performance main request screenshot](https://www.evernote.com/l/AREwWWoVe1BAra_UIHygk-DjulOzdvgug3c) VS [Degraded performance main request screenshot](https://www.evernote.com/l/ARGXk1g6i69OGIySk-B3zAbeZVJU5ncxaew)

**Comment by romainneutron** [comment]
A Blackfire comparison would help a lot

**Comment by tristanbes** [comment]
Here's the blackfire comparaison: https://blackfire.io/profiles/compare/1be7516b-7446-4ac6-a956-86ffe3ba7d35...56b6b517-9bff-44e1-b949-5a5d701c4e1b/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

**Comment by pamil** [comment]
@tristanbes it shows "404 not found" for me

**Comment by tristanbes** [comment]
Thanks @pamil I've updated the link
