### ISSUE TITLE
Form error enhancement for extra fields

### ISSUE THREAD

**Issue by bitgandtter** [symfony/symfony#21560]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

It will be nice to enhance the form error for extra fields, when working with any other than HTML render pages, like REST apis or any other kind, sending extra fields to the form can be really easy, like name mistakes or intended extra fields. The form error message right now is "This form should not contain extra fields." this give the root of the issue but requires debugging to see the actual issue. It will be nice to have an extended message like "This form should not contain extra fields. (field1, field2, ..., fieldN)".

It can be activated on debug=true if for some reason it may saw a security risk.

**Comment by ogizanagi** [comment]
Actually you can already do this by using the [`extra_fields_message`](http://symfony.com/doc/current/reference/forms/types/form.html#extra-fields-message) option on your forms:

```php
'extra_fields_message' => "This form should not contain extra fields: {{ extra_fields }}",
```

where `{{ extra_fields }}` will be replaced by a comma separated list of the submitted extra field names.

**Comment by bitgandtter** [comment]
My bad, wasnt aware of that option, but even thought will not be great to have it enabled by default on dev or debug=true?

**Comment by ogizanagi** [comment]
I'm not sure we should do that, as it would also affect html forms too. IMHO the form error messages are supposed to be the same, whatever the env is, and the form field name is quite internal.
If it only deserves a debug purpose or api calls, you can consult the error in the profiler, or create a form type extension changing this option, according to the request format for instance.
