### ISSUE TITLE
Twig translate function with parameters generates an error

### ISSUE THREAD

**Issue by Romain** [symfony/symfony#21570]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 2.8.16

I'm translating an app. The default locale is french.
My strings are in .xlf files.
Everything works fine. But if I try to use trans with parameters, I get an error.

Here is the twig function which generates the error: 

`{{ 'front.index.stay_connected.accept_tos'|trans( {'%link_start%': '<a href="' ~ path('tos') ~ '" title="TOS">', '%link_end%': '</a>'} )|raw }}`

Without it, everything works fine. With it, I get:

> UndefinedMethodException in TranslationDataCollector.php line 104:
> Attempted to call an undefined method named "cloneVar" of class "Symfony\Component\Translation\DataCollector\TranslationDataCollector".

I've spent a lot of time trying to figure out what the problem was, with no success.

Thanks for your help.

**Comment by aitboudad** [comment]
Can you please fork the Symfony Standard Edition and make the changes to reproduce your issue?

**Comment by xabbuh** [comment]
I don't see where this should come from. The line from your error message doesn't contain anything like that: https://github.com/symfony/symfony/blob/v2.8.16/src/Symfony/Component/Translation/DataCollector/TranslationDataCollector.php#L104 Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by Romain** [comment]
Yep, I'll try to reproduce.
R

**Comment by Romain** [comment]
Since the current version of Symfony is 3.2.3, I've decided to not clone this one, but rather install it from the command line to have a version coherent with mine:

`composer create-project symfony/framework-standard-edition my_project_name "2.8.16"`

I could not reproduce the bug, it works fine. This is weird...

**Comment by stof** [comment]
can you show the output of ``composer show 'symfony/*'`` in your affected project ?

**Comment by Romain** [comment]
Here it is:

> symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
> symfony/config             v3.2.3  Symfony Config Component
> symfony/intl               v3.2.3  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
> symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
> symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
> symfony/polyfill-iconv     v1.3.0  Symfony polyfill for the Iconv extension
> symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
> symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
> symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
> symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
> symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
> symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
> symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
> symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
> symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
> symfony/symfony            v2.8.17 The Symfony PHP framework
> symfony/translation        v3.2.3  Symfony Translation Component

**Comment by stof** [comment]
hmm, you have the 3.2 translation component installed alongside the 2.8 fullstack framework. This is what might cause the issue, due to mismatches in versions. 

too bad that Composer still has not fixed its bug where one of the optimization it applies can lead to a package being installed alongside a different version of a package it installs (which goes against the behavior of ``replaces``).

**Comment by Romain** [comment]
Oh gosh...
I changed my composer.json this way: `"symfony/translation": "^2.8"`, and now it works like a charm.
Thanks a lot @stof, you saved me hours of useless googling...
Too bad that composer can't detect incompatibilities between modules and the framework.
