### ISSUE TITLE
Throwing exception in event listener for controller gives 500 error

### ISSUE THREAD

**Issue by tdbui22** [symfony/symfony#21575]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.3

I'm using the information found on this page http://symfony.com/doc/current/event_dispatcher/before_after_filters.html to implement the before filter. I did exactly as described to throw an AccessDeniedHttpException and it works fine on dev but on prod it gives a 500 erorr instead of a 403.

**Comment by dmaicher** [comment]
Do you have a stack trace of the exception causing the 500 in production?

**Comment by tdbui22** [comment]
I ran basically the same code in the documentation (minus the token stuff and just immediately throw the exception in the onKernelController method. Here is the stack trace thrown in the terminal when I run server:run

[Thu Feb  9 14:25:49 2017] PHP Fatal error:  Uncaught exception 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException' with message 'This action needs a valid token!' in /Users/tien/Documents/dev/demo/src/AppBundle/EventListener/TokenListener.php:13
Stack trace:
#0 [internal function]: AppBundle\EventListener\TokenListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /Users/tien/Documents/dev/demo/var/cache/prod/classes.php(3707): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /Users/tien/Documents/dev/demo/var/cache/prod/classes.php(3622): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#3 /Users/tien/Documents/dev/demo/var/cache/prod/classes.php(4644): Symfony in /Users/tien/Documents/dev/demo/src/AppBundle/EventListener/TokenListener.php on line 13

**Comment by dmaicher** [comment]
Seems like you are not checking the controller on the event (`$event->getController()`)?

Your listener will also be called when symfony tries to render the exception page for your 403 `AccessDeniedHttpException` :wink: So in that case you are most likely throwing the exception again which prevents Symfony from handling the exception so it gives up and lets it bubble up.

**Comment by tdbui22** [comment]
I literally copied the code from the example and which does not work in production.

You are right it was a bubbling issue. The document should be updated to something like this instead.
use Symfony\Bundle\TwigBundle\Controller\ExceptionController;
$controller = $event->getController();
if (!is_array($controller) || $controller[0] instanceof ExceptionController) {
    return;
}

**Comment by dmaicher** [comment]
But the example contains this check with a custom interface:

```php
if ($controller[0] instanceof TokenAuthenticatedController) {
```

anyway this is not a symfony bug. Can you close the issue? Thanks :wink:

**Comment by tdbui22** [comment]
You are right the example only runs under one condition.

**Comment by pierreboissinot** [comment]
> Seems like you are not checking the controller on the event (`$event->getController()`)?
> 
> Your listener will also be called (using a subrequest) when Symfony tries to render the exception page for your 403 `AccessDeniedHttpException` wink So in that case you are most likely throwing the exception again which prevents Symfony from handling the exception so it gives up and lets it bubble up.

Thank you for the explanation
