### ISSUE TITLE
[Debug] Server Timing integration

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#21585]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I'm currently working on integrating the time collected to the response with [Server Timing](https://www.w3.org/TR/server-timing/).
Do you think it's valuable?

Main issue is: somme times are overlaping others and the result could be confusing (sum of section != overall).

![screenshot from 2017-02-11 12-09-24](https://cloud.githubusercontent.com/assets/578547/22853295/fc743b78-f052-11e6-8d97-eea2ff40a534.png)

**Comment by javiereguiluz** [comment]
There are no comments in this issue ... but in the Symfony Slack some people said that it wasn't that useful ... except for Ajax requests.

**Comment by dkarlovi** [comment]
@javiereguiluz that's a big "except" if you're building PWAs on top of Symfony API. :)

**Comment by apfelbox** [comment]
The nice thing of server timings is that they are unobtrusive – and therefore also useful for production code.
So maybe the code doesn't have to live in the debug bundle?

**Comment by jderusse** [comment]
@apfelbox collecting such timing add an overhead on every monitored services (see tracableEventDispatcher for instance)... I don't think it's a good idea to go in production with it.

**Comment by stof** [comment]
The Server Timing specification is still a proposal subject to changes without notices. So I think it is too early to provide support for it in the core. I suggest starting the experiment as an external bundle instead.

**Comment by stof** [comment]
btw, the target version cannot be 3.3: we reached feature freeze so new features cannot be added in 3.3 anymore.

**Comment by apfelbox** [comment]
@jderusse that is obvious. Although I actually see two use cases for this integration:

1. provide a framework for just sending timing data to the browser. Throwing `microtime(true)` through my application and sending approximate timings to the browser is not expensive – neither in debug, nor in prod.
2. automatically integrate with the debug bundle to fetch timing information automatically from the profiler.

2. is obviously expensive and only for debug, but 1. is perfectly viable for prod.

**Comment by lyrixx** [comment]
It looks like laravel got an integration: https://underground.works/clockwork/

**Comment by ostrolucky** [comment]
@lyrixx that's not just Laravel tool, anybody can contribute with Symfony bridge there

**Comment by King2500** [comment]
Chrome 65 supports the Server Timing API:
https://blog.chromium.org/2018/02/chrome-65-beta-css-paint-api-and.html

**Comment by theofidry** [comment]
I think Clockwork is open to different frameworks integrations: https://github.com/itsgoingd/clockwork/issues/196 so we could look for adding a Symfony bridge there instead of going for a Symfony only solution. Especially since this package looks already quite popular

**Comment by jderusse** [comment]
Closed by https://github.com/symfony/symfony/pull/27985 
See last @fabpot comment

**Comment by Bilge** [comment]
I don't particularly care for the _intended_ use of `server-timing`, but it's currently the _only_ way to pass arbitrary data from server to client via headers, which is a very interesting [hack](https://stackoverflow.com/a/66211531/1041515). As such, it would be useful to have a feature to convert an array to the appropriately encoded header, if nothing else.
