### ISSUE TITLE
BrowserKit : set choices in choiceType of a test

### ISSUE THREAD

**Issue by koukouille** [symfony/symfony#21596]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

Hi, i have a problem with the BrowserKit. My form contain 2 choiceTypes and when i load the form in my fonctionnal test (which use the BrowserKit), they are empty because they need the object passed in parameter (which is in $options['data'] in the formType).
I try to set values or pass the object in my test but nothing. 

Can you tell me how to pass the object in parameter of $client->request(...) to be in $options['data'] in the form or just set staticly choices in choiceTypes directly in the crawler or form in my fonctionnal test pls ?

**Comment by xabbuh** [comment]
I am sorry, but I need to close this issue as we do not use GitHub for support. Please refer to one of the [support channels](http://symfony.com/support). Thank you for understanding.
