### ISSUE TITLE
[Console] Progressbar should output new line when finished

### ISSUE THREAD

**Issue by tomasfejfar** [symfony/symfony#21590]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

Progressbar should output newline when finished. It could be configurable behaviour, although I don't know of any use cases that require it NOT to output new line. 

```
$progressbar = new ProgressBar($output);
$progressbar->start(100);
$progressbar->advance(100);
$progressbar->finish();
echo 'X';
```
Expected:
```
 100/100 [============================] 100%
X
```
Actual:
```
 100/100 [============================] 100%X
```

**Comment by robfrawley** [comment]
IMHO, I think it *would* be useful to __not__ output a newline, allowing something like this on completion.

```
 100/100 [============================] 100% Completed! 
```

That said, it might be nice if it were configurable.

**Comment by fabpot** [comment]
Closing as it is useful to be able to write something at the end of the line, and adding a newline when needed is not that difficult.

**Comment by tomasfejfar** [comment]
@robfrawley optional parameter to the `finish('Completed!')` method? 🙂 And default value of that parameter could be `PHP_EOL` :) I'd by happy to prepare a PR if @fabpot were to change his mind 😉

**Comment by fabpot** [comment]
I don't see how adding a parameter makes things easier. I'd rather not add a parameter for this.

**Comment by delmicio** [comment]
`echo PHP_EOL.'X';`

**Comment by ro0NL** [comment]
Note `SymfonyStyle` does this already for you :)

https://github.com/symfony/symfony/blob/55def786822b19cb04de57d3d7b32c33df22739c/src/Symfony/Component/Console/Style/SymfonyStyle.php#L258-L263

**Comment by robfrawley** [comment]
@ro0NL Not everyone uses the `SymfonyStyle` components: many have much more specific console cases and use the `ProgressBar` directly. Regardless, I still don't think it is too much to ask for people to simply call `newLine` manually after using `ProgressBar`.

**Comment by fomvasss** [comment]
I in Laravel i use after `$bar->finish()` this method `$this->output->newLine();`

```bash
vagrant@homestead ~/www/laravel/hipertin.test (dev) $ php artisan shop:product-rating-calculate

 Calculate rating for 500 products ?:
 > y

 500/500 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
vagrant@homestead ~/www/laravel/hipertin.test (dev) $
```

**Comment by bilogic** [comment]
@fabpot 
How about `->finishWithNewLine($default = 1)`? This is easy and will make everyone happy. I will gladly PR.

I think the issue here is readability, readers unfamiliar with Progressbar will not understand why there is an echo/newline after `finish()` until after they examine the output. It makes the code look cleaner even though it is just 1 line of extra code.

**Comment by nora-sch** [comment]
This is my example - the bar is displayed automatically in the middle of iteration and it's impossible to have a line break after it
![image](https://user-images.githubusercontent.com/62623658/183046854-8f86363f-951a-4977-8522-b82c9c7cbb5a.png)
I'm using here : 
`foreach ($io->progressIterate($allImages) as $image) { ...`

**Comment by michabbb** [comment]
does someone has a suggestion on how to use multiple progress bars in one artisan command to make it look "okay" ? 🤔

**Comment by serious-angel** [comment]
I've seen in codes workarounds as the following:

```php
$progressBar->setFormat("\n[%current%/%max%] [%bar%] %percent:3s%%\n");
```

This works, from the first glance, and makes the bar more convenient and clean.
Yet, it does not seem safe. Hence, to clarify, is that approach safe, considering `->advance()` and `->display();`?
