### ISSUE TITLE
Browserkit generate two HTTP_Referer

### ISSUE THREAD

**Issue by TonyGao** [symfony/symfony#21598]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.16

Hi, there

I found when I make client request with custom Referer header, there are always generate another one. Code below, 

```
$this->client->request(
            'POST',
            $postUrl,
            array(),
            array(),
            [
                'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
                'HTTP_USER_AGENT' => ApiURL::$USER_AGENT,
                'HTTP_Referer' => ApiURL::$url('referer'),
                'HTTP_Origin'  => ApiURL::getOrigin()
            ],
            'r='. urlencode(json_encode($jsonObject))
        );
```

dump the request like below (I change the content with dummy url)

```
#server: array:7 [
    "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
    "HTTP_Referer" => "http://url.com/right"
    "CONTENT_TYPE" => "application/x-www-form-urlencoded"
    "HTTP_REFERER" => "http://url.com/wrong"
    "HTTP_Origin" => "http://w.url.com"
    "HTTP_HOST" => "url.com"
    "HTTPS" => false
  ]
```

Even I tried to change the "HTTP_REFERER", but it looks change nothing, as below

```
$this->client->request(
            'POST',
            $postUrl,
            array(),
            array(),
            [
                'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
                'HTTP_USER_AGENT' => ApiURL::$USER_AGENT,
                'HTTP_Referer' => ApiURL::$url('referer'),
                'HTTP_RERERER' => ApiURL::$url('referer'),
                'HTTP_Origin'  => ApiURL::getOrigin()
            ],
            'r='. urlencode(json_encode($jsonObject))
        );

```

Is there any method change or delete the generated HTTP_REFERER? Thank you.

**Comment by stof** [comment]
well, in the second case, *you* are adding 2 of them.

BrowserKit currently expects giving it keys for ``$_SERVER``, not directly HTTP header names. And in PHP's ``$_SERVER``, HTTP headers have uppercase names. I suggest you to keep using the uppercase name. It will work best.

But anyway, if you do several requests with the client, it will always set the referer to the previous one (unless you reset the client between them of course, as it resets the history). This is because BrowserKit handles the browsing history.

**Comment by TonyGao** [comment]
@stof thank you, I found the mechanism by reading code, that's it

```
if (!$this->history->isEmpty()) {
            $server['HTTP_REFERER'] = $this->history->current()->getUri();
        }
```

And I comment it, then everything work as I want, but is there possible to provide an options in the request process to make it dumb manually. If this can be achieved, then it is really better and flexible.

**Comment by ro0NL** [comment]
What about calling `$client->getHistory()->clear()` between calls? However.. from the client perspective updating the referer makes really sense.

Ie. how come your history is not empty?

See also https://github.com/symfony/symfony/blob/master/src/Symfony/Component/BrowserKit/Client.php#L274

**Comment by TonyGao** [comment]
@ro0NL Well, that's maybe a special request, I must keep everything else except the automatically generated referer header.

**Comment by ro0NL** [comment]
A special request.. there's your problem ;-) perhaps use a special client for that?

Why do you want to override the default browser behavior? The client could only set the referer if not set already.. but im not sure it should care about that in any way.

**Comment by TonyGao** [comment]
@ro0NL Yes, you're right for browser behavior simulation, but not for a api tester. Some special rest api use custom header, status code of json content and anything what they could used to implement the request validation. So  in that way make it optional should be a great choice.

**Comment by javiereguiluz** [comment]
Let's close this because it's not a Symfony bug and the use case looks too edgy to add a new feature to it. Thanks!
