### ISSUE TITLE
Support for new 7.1 session options

### ISSUE THREAD

**Issue by Erseni** [symfony/symfony#21606]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

The NativeSessionStorage is not supporting the new php 7.1 session:
[php.net](http://php.net/manual/en/session.configuration.php)
sid_bits_per_character
sid_length
trans_sid_hosts
trans_sid_tags

```
$validOptions = array_flip(array(
            'cache_limiter', 'cookie_domain', 'cookie_httponly',
            'cookie_lifetime', 'cookie_path', 'cookie_secure',
            'entropy_file', 'entropy_length', 'gc_divisor',
            'gc_maxlifetime', 'gc_probability', 'hash_bits_per_character',
            'hash_function', 'name', 'referer_check',
            'serialize_handler', 'use_cookies',
            'use_only_cookies', 'use_trans_sid', 'upload_progress.enabled',
            'upload_progress.cleanup', 'upload_progress.prefix', 'upload_progress.name',
            'upload_progress.freq', 'upload_progress.min-freq', 'url_rewriter.tags',
        ));

        foreach ($options as $key => $value) {
            if (isset($validOptions[$key])) {
                ini_set('session.'.$key, $value);
            }
        }
```

**Comment by chapterjason** [comment]
> **Session ID generation without hashing**
> Session IDs will no longer be hashed upon generation. With this change brings about the removal of the
> following four ini settings:
>  
>     session.entropy_file
>     session.entropy_length
>     session.hash_function
>     session.hash_bits_per_character
>  
> And the addition of the following two ini settings:
> 
>     session.sid_length - defines the length of the session ID, defaulting to 32 characters for backwards compatibility)
>     session.sid_bits_per_character - defines the number of bits to be stored per character (i.e. increases the range of characters that can be used in the session ID), defaulting to 4 for backwards compatibility


Source: [Migrating from PHP 7.0.x to PHP 7.1.x - Other changes - Session ID generation without hashing](http://php.net/manual/de/migration71.other-changes.php#migration71.other-changes.session-id-generation-without-hashing)

**Comment by nicolas-grekas** [comment]
please submit a PR against branch 2.7
