### ISSUE TITLE
[DI] Unable to use env() on params passed to ReplaceAliasByActualDefinitionPass

### ISSUE THREAD

**Issue by andrerom** [symfony/symfony#21609]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.x

It's stated in #20434 that env variables currently does not support being used in place for service names, which limits it's usefulness.

Is there plans to provide a best practice around this?

Possible alternatives:
A. ~~Change how configuration of handlers are done to allow switching service on runtime~~ _Does not make sense as pointed out by @stof below, often you **need** to compile config depending on a handler, this is something to do at compile time and not run time_
B. Introduce a compile time env variable support as well so we can also be allowed to inject variables at compile time without having to resolve to custom [env.php](https://github.com/ezsystems/ezplatform/blob/v1.7.0/app/config/env/docker.php) kind of solutions.
C. If there are no plans to tackle this with additional features, improvment potential here is to improve doc and more clearly throw on use like this as done in #20687.

Example:
```                                                  
  [Symfony\Component\DependencyInjection\Exception\EnvParameterException]                    
  Incompatible use of dynamic environment variables "MAILER_TRANSPORT" found in parameters.  
                                                                                             

Exception trace:
 () at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:137
(...)

                                                                                                                         
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                             
  Unable to replace alias "swiftmailer.mailer.default.transport.real" with actual definition "%env(MAILER_TRANSPORT)%".  
                                                                                                                         

Exception trace:
 () at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ReplaceAliasByActualDefinitionPass.php:63
(...)
                                                                              
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "%env(MAILER_TRANSPORT)%".        
                                                                              

Exception trace:
 () at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:795
(...)
```

**Comment by stof** [comment]
Aliases cannot use parameters at all (since Symfony 2.0.0), be there env variables or no.

And btw, supporting env variables there is a no-go IMO. The whole point of env variables is that they are resolved at runtime. And aliases are validated and resolved at compile time. Adding a dynamic target for an alias would require rewriting all code dealing with aliases (and adding overhead for all aliases in the container, to check at runtime whether they need to be resolved dynamically...)

**Comment by nicolas-grekas** [comment]
I suggest to open an issue on swiftmailer bundle instead, this is where the issue exists - too many logic done at compile time

**Comment by stof** [comment]
@nicolas-grekas this issue comes from MonologBundle. And processing the whole bundle config at runtime to decide which handlers to create and how looks insane to me. I don't think the overhead it will add is justified, compared to being able to switch the logger handlers at runtime without a deployment (thus, most of them expect different configuration settings, and potentially different dependencies, so it would simply not work).

**Comment by nicolas-grekas** [comment]
indeed :)

**Comment by stof** [comment]
btw, the same is true for the swiftmailer transport: each transport expect different config settings

**Comment by andrerom** [comment]
Well there is still option B and C available :)

**Comment by nicolas-grekas** [comment]
> B. Introduce a compile time env variable support as well so we can also be allowed to inject variables at compile time without having to resolve to custom env.php kind of solutions.

Why not use `SYMFONY__*`  env vars instead of env.php? see also #20100 (thus if you think this should not be deprecated, please comment there)

**Comment by andrerom** [comment]
> Why not use SYMFONY__* env vars

They are rather pointless, they are overridden by defined parameters.

>  instead of env.php

I did get rid of env.php approach, but what I ended up with for now is to use `comoser.json incenteev-parameter.env-map` for compile time params, and env() for run time options. But with all the recent env improvements I was hoping to avoid having to use `incenteev/composer-parameter-handler`, I was kind of expecting some standard convention could solve this now ;)

**Comment by nicolas-grekas** [comment]
OK. You can also do that in your bundle extension: resolve env vars and inject them in params. That'd be 100% compile time.

**Comment by andrerom** [comment]
true, but if symfony came with something like `%compile_env()%` then I would not have to hard code that in the bundle, it can be user defined in the yml files we provide to end user.

**Comment by nicolas-grekas** [comment]
I'd be in favor of closing this one, and replacing it with a doc issue. IMHO, we should not provide helpers to make people use env vars at compile time. Doing so means making the container not runtime-configurable for the corresponding envs. While there are legitimate use cases to do so, there are already ways to do that (the simplest one being to `getenv()` in a compiler pass).

**Comment by andrerom** [comment]
ok

**Comment by cordoval** [comment]
is there a way to shut down the %env()% trick? honestly i ran into so many issues with it that i just use a parameters.php to do set my parameters, wasted a lot of time because of this.

**Comment by javiereguiluz** [comment]
@cordoval it's not really a trick but a feature :)  And there's no direct way to disable it ... but there's an indirect way: not using it in any config file.

**Comment by cordoval** [comment]
thanks @javiereguiluz i know the features are with good intentions, just so frustrating 👴 uff uff
