### ISSUE TITLE
[Intl] update to ICU data v58.2

### ISSUE THREAD

**Issue by tuxayo** [symfony/symfony#21601]
| Q                | A
| ---------------- | -----
| Bug report?      | kinda
| Feature request? | kinda
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

OS: Arch Linux
ICU library package: icu 58.2-1

When I run `php bin/symfony_requirements` I get

```
 * intl ICU version installed on your system (58.2) does not match the
   ICU data bundled with Symfony (57.1)
   > To avoid internationalization data inconsistencies upgrade the
   > symfony/intl component.
```

As I have the latest Symfony version, ICU data should be updated in Symfony right?

**Comment by ogizanagi** [comment]
@jakzal is working on this. See https://github.com/symfony/symfony/pull/20564 :)

**Comment by bsimon94** [comment]
Hello, I have this recommendations when I run the symfony configuration checker file config.php

This script analyzes your system to check whether is ready to run Symfony applications.
RECOMMENDATIONS
To enhance your Symfony experience, it’s recommended that you fix the following:
intl ICU version installed on your system is outdated (52.1) and does not match the ICU data bundled with Symfony (58.2)
To get the latest internationalization data upgrade the ICU system package and the intl PHP extension.
a PHP accelerator should be installed
Install and/or enable a PHP accelerator (highly recommended).
short_open_tag should be disabled in php.ini
Set short_open_tag to off in php.ini*.
* Changes to the php.ini file must be done in "/Library/Application Support/appsolute/MAMP PRO/conf/php7.0.8.ini".

Can someone tell me what can I do ?

**Comment by tuxayo** [comment]
See the comment above yours: https://github.com/symfony/symfony/issues/21601#issuecomment-279514634

#20564 is part of the upcoming [v2.7](https://github.com/symfony/symfony/milestone/13)

So I guess you can try to help with the remaining 2.7 tasks
