### ISSUE TITLE
[Serializer] Xml encoder throws exception for valid data

### ISSUE THREAD

**Issue by gr1ev0us** [symfony/symfony#21617]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.x

The problem is in a xml serialization array/object contained DateTime object. To normalize this i am using DateTimeNormalizer (it appeared in sf 3.2, but in my project I use my custom implementation). As a result I get an UnexpectedValueException.

How to reproduce a bug:
```php
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;

$serializer = (new Serializer([new DateTimeNormalizer, new XmlEncoder]));

$result = $serializer->serialize(['node'=> new DateTime('2017-02-13T17:54:23+0300')]);
```

expects:
```xml
<response><node>2017-02-13T17:54:23+0300</node></response>
```

actual: An unexpected value could not be serialized: '2017-02-13T17:54:23+0300'

I suppose, there is no need to normalize value before buildXml invocation:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L480

**Comment by xelan** [comment]
Status: Reviewed

Seems like the `XmlEncoder` doesn't work correctly if a Normalizer returns something other than an object.

Restarting the node type selection if the normalizer returns a non-object seems to work:
```php
private function selectNodeType(\DOMNode $node, $val)
    {
        if (is_array($val)) {
            return $this->buildXml($node, $val);
        } elseif ($val instanceof \SimpleXMLElement) {
            $child = $this->dom->importNode(dom_import_simplexml($val), true);
            $node->appendChild($child);
        } elseif ($val instanceof \Traversable) {
            $this->buildXml($node, $val);
        } elseif (is_object($val)) {
            $normalized = $this->serializer->normalize($val, $this->format, $this->context);

            if (is_object($normalized)) {
                return $this->buildXml($node, $normalized);
            }

            return $this->selectNodeType($node, $normalized);
        } elseif (is_numeric($val)) {
            return $this->appendText($node, (string) $val);
        } elseif (is_string($val) && $this->needsCdataWrapping($val)) {
            return $this->appendCData($node, $val);
        } elseif (is_string($val)) {
            return $this->appendText($node, $val);
        } elseif (is_bool($val)) {
            return $this->appendText($node, (int) $val);
        } elseif ($val instanceof \DOMNode) {
            $child = $this->dom->importNode($val, true);
            $node->appendChild($child);
        }

        return true;
    }
```
I cloned `master` and applied this change, all tests for the Serializer component pass afterwards.

Should I open a PR?

**Comment by xelan** [comment]
Test code for reproducing the bug:
```php
require_once('vendor/autoload.php');

use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;

$normalizers = [new DateTimeNormalizer()];
$encoders = [new XmlEncoder()];

$serializer = new Serializer($normalizers, $encoders);
$result = $serializer->serialize(['node' => new DateTime()], 'xml');

var_dump($result);
```

**Comment by xelan** [comment]
The question whether the serialization of objects without a class definition makes sense, as they can't be deserialized afterwards. `Serializer::deserialize()` needs a class name, `stdClass` is not supported without a custom `Normalizer`.

**Comment by gr1ev0us** [comment]
In my case, I'm using a serializer for creating xml response for remote clients. So It is no need deserializer here (I defined DateTime format in my api-doc). 
Besides, XmlEncoder is using implementation of NormalizerInterface, that defines return value (in phpDoc) array or scalar, not object. I think XmlEncoder has logical error trying to call selectNodeType with serialized scalar value.

Probably the solution will be in a recursive call:
```php
private function selectNodeType(\DOMNode $node, $val)
{
// ...
     } elseif (is_object($val)) {
         return $this->selectNodeType($node, $this->serializer->normalize($val, $this->format, $this->context));
// ...   
}
```
