### ISSUE TITLE
[Serializer] CSV Encoder returns inconsistent result

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#21616]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.x

I am trying to understand what's the use of returning inconsistent data depending if the csv has multiple rows or not  at [this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Encoder/CsvEncoder.php#L153).

Furthermore:

- This is really not documented
- When I used the CsvEncoder I was passing the decoded result into a Collection object which was expecting an associative array. When the user uploaded a single line everything broke.
- I will just have to put a really bad code part that will need to check if it's a numeric key or not. Can't really think of any other way.
- Checked the other encoders and I don't think they do that.

**Comment by xabbuh** [comment]
@dunglas Can you have a look here? :)

**Comment by dunglas** [comment]
The original intent was to allow easily to implement write methods for APIs where you usually deal with a single document. For instance it's the only way to make this encoder working out of the box with API Platform (`POST` and `PUT` expect a single document as input, not a collection).

After a second though it can be counter-intuitive when sending collections (not usual when creating APIs but I'm aware there are tons of user use-cases for this encoder) when the "collection" contain only 1 document.

The sure thing is it must be documented. A "fix" can be to enable or disable this behavior using a context flag (for BC concerns, it should be a new flag to disable this behavior). If it can help you, I'll try to open a PR for that this week.

**Comment by gmponos** [comment]
> I'll try to open a PR for that this week

No problem :+1:

**Comment by gmponos** [comment]
ping.

**Comment by gander** [comment]
ping

**Comment by Simperfit** [comment]
@gmponos Could you test #25218 and tell me if it's ok for you ?

**Comment by dunglas** [comment]
Fixed by #25218.
