### ISSUE TITLE
phpunit-bridge's ClockMock not recognizing @group time-sensitive annotation

### ISSUE THREAD

**Issue by ComaVN** [symfony/symfony#21612]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

I cannot get clock mocking to work using the `@group time-sensitive` annotation in Symfony 2.8.17

According to [the documentation](https://symfony.com/doc/2.8/components/phpunit_bridge.html#clock-mocking), this annotation is the recommended way to mock `time()` and `sleep()` calls.

However, only by explicitly registering my class can I get it to work.

See https://github.com/ComaVN/symfony-phpunit-bridge-clockmock for a test case

**Comment by stof** [comment]
using the group works only when the ``Symfony\Bridge\PhpUnit\SymfonyTestsListener`` listener is registered in your testsuite.
This can be achieved in 2 ways:
- by registering it in your phpunit.xml config file
- by using the ``simple-phpunit`` executable shipped in the bridge, which will handle installing PHPunit under the hood, and will force the registration of the listener when calling PHPUnit.

**Comment by stof** [comment]
Please open an issue on the doc repo about this though.

**Comment by ComaVN** [comment]
Thanks for the reply. I created an issue for symfony-doc. I guess this issue can be closed then?
