### ISSUE TITLE
Is the "alias" attribute of validators mandatory or optional?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21610]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 2.7+

In the PHPdoc of https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Validator/ConstraintValidatorFactory.php we can read:

```
 * A constraint validator should be tagged as "validator.constraint_validator"
 * in the service container and include an "alias" attribute:
 *
 *     <service id="some_doctrine_validator">
 *         <argument type="service" id="doctrine.orm.some_entity_manager" />
 *         <tag name="validator.constraint_validator" alias="some_alias" />
 *     </service>
 *
 * A constraint may then return this alias in its validatedBy() method:
 *
 *     public function validatedBy()
 *     {
 *         return 'some_alias';
 *     }
```

But in the code of https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraint.php we can see that the `validatedBy()` has a default value:

```php
public function validatedBy()
{
    return get_class($this).'Validator';
}
```

---

So, there's some confusion about `alias` being optional or not. See https://github.com/symfony/symfony-docs/pull/6610 and https://github.com/symfony/symfony-docs/pull/7489

---

My question: is `ConstraintValidatorFactory.php` doc wrong or am I missing something?

**Comment by stof** [comment]
the *constraint* has a default value. when using a validator as a service, you can either use this default value or change it to something else. But then, the validator service must reference this alias (be it the default one or a custom one). Nothing forbids you to rely on the default implementation of ``validatedBy`` even when using a service.

If you omit the alias in the DI tag, the compiler pass uses the service id by default, for historical reasons, which may suit your needs or no

**Comment by javiereguiluz** [comment]
Thanks for the explanation! I'm going to close this issue then as *"nothing to do here"* and we'll continue in the docs.

**Comment by darius-v** [comment]
I had made a bug when copying service description xml  and left alias unchanged from another validator. Is that a feature or bug that it calls wrong validator if alias wrong?
