### ISSUE TITLE
UniqueEntityValidator fails when the unique value is a custom doctrine type field

### ISSUE THREAD

**Issue by magarzon** [symfony/symfony#21619]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.10

When the unique field selected is a field with a Doctrine Custom Type, and there is a violation in the validation (i.e., the value already exists in the database), the method validate in UniqueEntityValidator throws a Doctrine/Common/Persistence/Mapping/MappingException: The class 'Whatever' was not found in the chain configured namespaces AppBundle\\Entity

This is due to the modifications introduced in this commit: [https://github.com/symfony/symfony/commit/b3ced8608b8229c1ec54181819d869d47ca92a7d](https://github.com/symfony/symfony/commit/b3ced8608b8229c1ec54181819d869d47ca92a7d)

And is due to this method that is called to build the violation error in the validate method:
[https://github.com/symfony/symfony/blob/b3ced8608b8229c1ec54181819d869d47ca92a7d/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L140](https://github.com/symfony/symfony/blob/b3ced8608b8229c1ec54181819d869d47ca92a7d/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L140)

If the field value is an object (as in the case of a Doctrine custom type), it assumes that it's a Doctrine entity and try to get its identifiers, and there is when the exception is thrown, because the object is not an entity and it's not mapped

**Comment by dmaicher** [comment]
Thanks for the bug report. I could reproduce the issue and this case was indeed not considered :cry: 

I proposed a fix in https://github.com/symfony/symfony/pull/21656.

**Comment by iBasit** [comment]
How do we use this?

**Comment by xabbuh** [comment]
@iBasit What do you mean?
