### ISSUE TITLE
Allow user to attach callback in Symfony process that gets fired when status changes

### ISSUE THREAD

**Issue by nicholasnet** [symfony/symfony#21624]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

Currently Symfony process allows user to attach callbacks to listen for output but it does not allow user to attach callback that gets fired during status change like completion, success, abort, error etc for async one. Right now only way to monitor the status is to check constantly in a loop which is bit inconvenient in my opinion.

**Comment by sstok** [comment]
This is only possible when you monitor the activity as PHP as no native promise/async functionality. So unless this comes available (yes there are libraries, but these are still very young) it's not really possible at the moment.

**Comment by fabpot** [comment]
Closing as that's not something we can easily support in Symfony.
