### ISSUE TITLE
[PropertyAccess] Common syntax for arrays and objects

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#21626]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

I think it would be really helpful if common (dot-based) syntax could be used in PropertyAccess component.

Consider this:

```
use Symfony\Component\PropertyAccess\PropertyAccess;

class DummyExample {
    public function getA() { return new static(); }
    public function getB() { return new static(); }
    public function getC() { return 'I want to get this'; }
}
$array = ['a'=>['b'=>['c'=>'I want to get this']]];
$object = new DummyExample();

$propertyAccessor = PropertyAccess::createPropertyAccessor();
dump(
    $propertyAccessor->getValue($array, '[a][b][c]'), // UGLY!!
    $propertyAccessor->getValue($object, 'a.b.c'),
);
```

For now, accessing array properties are not possible with `a.b.c` syntax. Why? I know it makes sense for integer keys to use brackets, but for associative arrays syntax could be the same as for objects.

It will allow to use common syntax regardless of what data is being processed. Sometimes objects can be serialized to array, but path may remain "the same". With this feature accessing this path could still work without additional changes.

What do you think?

**Comment by chalasr** [comment]
I already thought about proposing this but gave up for a reason that I don't remember. We have places in the core where dot syntax is handled manually instead of using a PropertyAccessor for this reason (e.g. ConfigDebugCommand,

**Comment by fabpot** [comment]
In the past, we used to have a common notation. We switched to an explicit on a long time ago because of issues with the Validator/Form components.
