### ISSUE TITLE
[Security] _target_path is not persisted between login attempts

### ISSUE THREAD

**Issue by aistis-** [symfony/symfony#21628]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | v3.0

When in `security.yml` defining `target_path_parameter: _target_path` for a form, it works only on first form login attempt. `_target_path` is not persisted between the attempts, so you will not be redirected to `_target_path` after first failed attempt to login.

Some more info https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2450

A workaround: http://stackoverflow.com/questions/12329855/symfony-2-keep-target-path-even-on-wrong-password

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by laskos** [comment]
I cant reproduce it. Security ignores URL parameters. `target_path_parameter` is about the form hidden field, not the url one according to the [docs](http://symfony.com/doc/current/security/form_login.html#control-the-redirect-url-from-inside-the-form).

**Comment by aistis-** [comment]
Thanks for taking look into that. I will try checking on the issue when I find some time.

**Comment by jakzal** [comment]
@aistis- any news?

**Comment by Koc** [comment]
relates to #10049

**Comment by xabbuh** [comment]
Closing here for now due to the lack of feedback.

@aistis- Please feel free to provide more information on how to reproduce your issue and we can consider to reopen.
