### ISSUE TITLE
[browserkit] slow ?

### ISSUE THREAD

**Issue by johndodev** [symfony/symfony#21621]
Hello,

I just write a functional test on silex with the browserkit and phpunit, and I was surprised it was so slow. As I saw some mentions of hundred of tests run on few seconds, I don't know if my slow run is normal..

So on my test, _setUp_ create the app (the pimple container) and a sqlite database with very  few fixtures on RAM, and tearDown drop the schema (all that with doctrine tools). It take 1.38 sec to do that (launch with an empty test).

But with a test, for example : 

```
public function testLogin()
{
	$client = $this->createClient();
	$client->followRedirects();

	$crawler = $client->request('GET', 'http://posao.test.luminjo.com');
	$this->assertTrue($client->getResponse()->isOk());

	$form = $crawler->selectButton('login.submit')->form();

	$crawler = $client->submit($form, [
		'_username' => 'login@login.com',
		'_password' => 'password',
	]);

	$this->assertEquals('http://posao.test.luminjo.com/tickets', $client->getRequest()->getUri());
	$this->assertTrue($client->getResponse()->isOk());

	foreach ([
		'http://posao.test.luminjo.com/account',
		'http://posao.test.luminjo.com/tickets/create',
		'http://posao.test.luminjo.com/settings',
		'http://posao.test.luminjo.com/folders',
		'http://posao.test.luminjo.com/agents',
		'http://posao.test.luminjo.com/typical_responses',
		'http://posao.test.luminjo.com/tags',
		'http://posao.test.luminjo.com/embed',
		'http://posao.test.luminjo.com/stats',
		'http://posao.test.luminjo.com/account/role',
		'http://posao.test.luminjo.com/pricing',
			 ] as $url) {
		$client->request('GET', $url);
		$this->assertTrue($client->getResponse()->isOk());
	}
}
```
It take 19.13 secondes. I can literally be faster manually on my browser.
Form submit is especially slow (so I removed a test to check a failure login message).

I have to give full URL because the host is a part of logic (here posao is the slug of an entity).

I don't see anything special on the design of the app, no reason to be slow. It is ph5.6, I can't test on php7 yet, but in a few weeks..

So, is it standard execution time or is something wrong here ?

**Comment by stof** [comment]
Can you provide a blackfire profile of this execution, allowing to see which part is slow ?

and which Symfony BrowserKit version are you using ?

**Comment by johndodev** [comment]
Okay I just did it and indeed I found something fancy with my listeners (wich leads to a lot of password_hash call, which is slow).

 Omg this tool is super usefull. Thanks !
