### ISSUE TITLE
Symfony\Component\Form\Extension\Core\Type\DateType behave differently between OS

### ISSUE THREAD

**Issue by xanxiver** [symfony/symfony#21630]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

When I am testing to submit a date value using ISO 8601 format to a form that contains Symfony\Component\Form\Extension\Core\Type\DateType in its field, it behaves differently between OSX El Capitan and Ubuntu 14.04, the former OS gives me error and the latter doesnt give me error (Using $form->isValid() gives me false on OSX El Capitan and true on Ubuntu 14.04).

**Comment by xabbuh** [comment]
Does it depend on the submitted value? Are the PHP versions identical? Both are 32 or 64 bit versions?

**Comment by xanxiver** [comment]
@xabbuh both submitted in ISO 8601 format (eg. 2017-02-17T00:00:00+0700) as I said before it gives error on OSX El Capitan (I have tested on my friend macbook too so it is tested in 2 OSX) and it doesn't give error on Ubuntu 14.04. Both using PHP 7.0.15 and both are 64 bit version. But when I change the DateType to DateTimeType, the error doesnt occur anymore.

**Comment by stof** [comment]
``2017-02-17T00:00:00+0700`` is *not* the valid ISO 8601 format (even though it is what is outputted when using ``DateTime::ISO_8601`` in PHP). The ISO format is ``2017-02-17T00:00:00+07:00``

Regarding both systems, do you have ext-intl on both of them ? Or are you relying on the polyfill on one of them ?

**Comment by xanxiver** [comment]
@stof The Ubuntu has intl but the OSX doesn't have it, I will try to install it on the OSX

**Comment by javiereguiluz** [comment]
@xanxiver did you manage to install ext-intl on macOS? Does the error persist?

(by the way, sometimes installing the Intl extension is not that easy on macOS. If you have any problem, you can consider using https://php-osx.liip.ch which installs PHP with everything that is needed)

**Comment by xanxiver** [comment]
@javiereguiluz sorry for my slow response, i have already managed to install ext-intl. The error doesn't occur anymore after I install ext-intl.

**Comment by javiereguiluz** [comment]
@xanxiver thanks for reviewing this 👍  So, now that the error is gone with the installed intl PHP extension, we can close this as "fixed". Thanks!
