### ISSUE TITLE
[PropertyAccess] All exceptions should implement Symfony\Component\PropertyAccess\Exception\ExceptionInterface

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#21644]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (in my opinion)
| Feature request? | no
| BC Break report? | ? (hard to tell)
| RFC?             | no
| Symfony version  | 3.2.1

I am writing unit tests in our app and when using `PropertyAccessor` I would like to make expectation for `Symfony\Component\PropertyAccess\Exception\ExceptionInterface`, but `Symfony\Component\PropertyAccess\Exception\AccessException` (and its children) does not implement it.

Of course I can make expectation for `NoSuchPropertyException` but I think every PropertyAccess component's exception should be catchable with common interface.

**Comment by Wirone** [comment]
As a sidenote: is it normal behaviour that when accessing non-existing array index there is not any exception, but `null` is returned?

**Comment by xabbuh** [comment]
> As a sidenote: is it normal behaviour that when accessing non-existing array index there is not any exception, but `null` is returned?

Yes, it's even documented: http://symfony.com/doc/current/components/property_access.html#reading-from-arrays

**Comment by Wirone** [comment]
@xabbuh thanks, I read that documentation and somehow I've missed that.

I got one doubt while we're talking about exceptions. There is `NoSuchIndexException`, phpDoc states it is thrown in `PropertyAccessor::readPropertiesUntil()`, but - as far as I understand code and `PropertyAccessorArrayAccessTest::testGetValueFailsIfNoSuchIndex()` - it requires to build `PropertyAccessor` instance with enabling exceptions on invalid index. Maybe it should be included in docs?

**Comment by Wirone** [comment]
@webmozart you're the author of `ExceptionInterface` is there any reason that not every PropertyAccess exception implements it?

I could work on this (take care of implementations and add some tests), but I would like to know:
- if it's required or not, obviously
- where PR should go (2.3 and then up to every branch?)

**Comment by ogizanagi** [comment]
@Wirone: [`AccessException`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/Exception/AccessException.php) is extending [`RuntimeException`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/Exception/RuntimeException.php) from the `PropertyAccess` component, which does implement `Symfony\Component\PropertyAccess\Exception\ExceptionInterface`.

**Comment by Wirone** [comment]
@ogizanagi :scream: I am 100% that my unit test's expectation was failed but now when I think of it, it may be related to invalid path within array I was asking about above. Since it returns `null` instead of throwing exception, expectation could fail... I checked that classes and maybe I thought it was `\RuntimeException`.

Anyway... my bad.
