### ISSUE TITLE
Namespace for PHPUnit outdated

### ISSUE THREAD

**Issue by maddy2101** [symfony/symfony#21652]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

You still use the outdated Namespace of PHPUnit (\PHPUnit_Framework_TestCase) as Parent in vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php. Meanwhile, no dependecy declaring an upper limit for phpunit prevents the installation of phpunit 6.x. And this, in sequence, leads to tests failing from the beginning. Please consider updating this dependency.

**Comment by fabpot** [comment]
Thanks for the report. I'm closing this issue as we already have many other reports and even some pull requests trying to solve this issue.
