### ISSUE TITLE
Zero-Config: Resolve class by service name

### ISSUE THREAD

**Issue by sourcerer-mike** [symfony/symfony#21667]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.0

Just have heard about the Zero-Config activities so I like to give in some idea. I tried to implement it but it seems a bit bigger so I like to ask before.

## Service configuration without passing class

Imagine this services.yml defining a custom service:

```
services:
  foo.bar.baz_qux:
    arguments: [ 1, 2, 3 ]
``` 

What's clearly missing is the `class:` argument.
With the correct service name the class could be resolved.
As I experienced this occurs quite often for ...

- Repositories
- CommandHandler
- Controller / or Action-Classes

Because they got that singleton touch.

### Resolving class name

The `class` for  `foo.bar.baz_qux` should be looked up like this:

- Check for `\FooBundle\Bar\BazQux` class
  - Every dot became a backslash
  - Underscore separates words (`ucwords()`)
  - The other rules are (hopefully) obvious.
- Check for `\FooBundle\Bar\Baz_Qux` class
- Check for `\Foo\Bar\BazQux` class
- Check for `\Foo\Bar\Baz_Qux` class
- Throw exception about missing or unresolvable class

**Comment by dosten** [comment]
:-1: 

You can use:

```
services:
  FooBundle\Bar\BazQux:
    arguments: [ 1, 2, 3 ]
```

**Comment by xabbuh** [comment]
:-1: for me as well. If you want to omit the `class` attribute, you can use the service id for it. That should be enough and less confusing than adding another convention to achieve this.

**Comment by javiereguiluz** [comment]
@sourcerer-mike thanks for making a proposal to improve Symfony. However, as you can see the feedback from the community is not very positive, so I must close this as "won't fix".

Although this time your proposal didn't make it, please keep making proposals and asking for new features in the future. That's what makes us advance! Thanks.

**Comment by nicolas-grekas** [comment]
@sourcerer-mike just in case you missed it: http://symfony.com/blog/new-in-symfony-3-3-optional-class-for-named-services
