### ISSUE TITLE
Route annotation not found when using an absolute class namespace

### ISSUE THREAD

**Issue by e7o-de** [symfony/symfony#21685]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

```
<?php

namespace FancyBundle\Controller;

use \Symfony\Bundle\FrameworkBundle\Controller\Controller;
use \Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class FancyController extends Controller
{
    /**
     * @Route("/fancy")
     */
    public function fancyAction()
```

When executing php app/console cache:warmup or trying to request a page (using PHP 5.4 in my case, not sure if that matters), I get the following error:

```
// Warming up the cache for the prod environment with debug false                                                      

  [Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                     
  [Semantical Error] The annotation "@\Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" in method FancyBundle\Controller\FancyController::fancyAction() does not exist, or could not be auto-loaded in /app/fancyProject/current/src/FancyBundle/Controller/ (which is being imported from "/app/fancyProject/current/app/config/routing.yml").
                                                                     
  [Doctrine\Common\Annotations\AnnotationException]               
  [Semantical Error] The annotation "@\Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" in method FancyBundle\Controller\FancyController::fancyAction() does not exist, or could not be auto-loaded.
```

Took me a while, but looks like it only works when the use statement in the controller doesn't contain the leading backslash (fully allowed in PHP), so ... some of that magic happening in Symfony (and Doctrine I assume) is somehow wrong there.

I can fix it for my use case (just by removing the first slash and hope this will be visible in Google as I couldn't find that error message with this solution), but this should get fixed at some point imho ... maybe by doing less magic? :) It's pretty annoying, last time somebody asked me about that kind of error I had no idea, but now, as it struck myself as well ...

**Comment by xabbuh** [comment]
You need to report this to the doctrine/annotations project as this is dealing with the parsing of annotations. There is nothing we can do in Symfony. Thank you for understanding.
