### ISSUE TITLE
Invalid auto-loading doctrine object in controller action

### ISSUE THREAD

**Issue by mtijink** [symfony/symfony#21693]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

When I have a controller action like this:

```php
public function showAction(int $id, SomeObject $other = null)
```

and a route like this:

```yaml
some_route:
    path: /{id}
    defaults: { _controller: ...:show, other: ~ }
```

the result is that symfony calls the controller with both the `$id` set, and `$other` loaded with the same id (which may even be invalid for that object!), even tough I specifically provided a value for `$other`.

Even leaving `other` away in the route specification, I would expect this to work fine (since a parameter with name `$id` is available), and auto-loading the object is a mistake, in my opinion. Especially because the issue does not occur without type hinting.

**Comment by xabbuh** [comment]
Symfony doesn't do any converting to arbitrary objects by default. Do you make use of param converters as they are provided by the SensioFrameworkExtraBundle? Do you have other bundles installed that influence the way requests are handled?

**Comment by mtijink** [comment]
Yes, we use the SensioFrameworkExtraBundle, sorry for the confusion. No other bundles affect requests, as far as I know, we do not use much more than the symfony standard edition.

Should I create an issue there instead?

**Comment by xabbuh** [comment]
Without seeing more of the code that's hard to guess. If you are using param converters it could be related to misuse of them or an issue with them and then indeed should be reported to the bundle's repository.

**Comment by stof** [comment]
This is related to the way the DoctrineParamConverter works in SensioFrameworkExtraBundle. By default, it looks for both an attribute with the same name than the argument and the ``id`` attribute. It is possible to configure the ParamConverter explicitly to disable this behavior, by telling it which attribute should be used for the id: ``@ParamConverter("other", options={"id": "other"})``

Anyway, I'm closing this issue asit is not an issue in Symfony.
