### ISSUE TITLE
Choice assert with callback fails inside the All assert

### ISSUE THREAD

**Issue by murilolobato** [symfony/symfony#21706]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.14

If I try to use the `Assert\Choice` inside the `Assert\All`, like following I receive a `The choice constraint expects a valid callback` error message.

```php
// src/AppBundle/Entity/User.php
namespace AppBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class User
{
    /**
     * @Assert\Count(min="1")
     * @Assert\All({
     *     @Assert\Choice(callback={"getValidColors"})
     * })
     */
     protected $favoriteColors = array();

     public static function getValidColors()
     {
          return array('red', 'green', 'blue');
     }
}
```
The error message: 
![image](https://cloud.githubusercontent.com/assets/1851400/23180958/ead2a63c-f851-11e6-8f00-eec351845cc7.png)

To walkaround this problem, I've added the full-qualified-class-name to the first paramater of the callback option of the `Assert\Choice`, as follow:

```php
// src/AppBundle/Entity/User.php
namespace AppBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class User
{
    /**
     * @Assert\Count(min="1")
     * @Assert\All({
     *     @Assert\Choice(callback={"AppBundle\Entity\User", "getValidColors"})
     * })
     */
     protected $favoriteColors = array();

     public static function getValidColors()
     {
          return array('red', 'green', 'blue');
     }
}
```

And this way it has worked, but this method is not covered at any documentation. I'm willing to help if I know what needs to be done.

**Comment by xabbuh** [comment]
The cause of this behaviour probably basically is the same as in #20477.
