### ISSUE TITLE
Symfony Process real-time output not working in production

### ISSUE THREAD

**Issue by lukesnowden** [symfony/symfony#21702]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | Process v3.0.9

Can someone please inform me of why Symfony Process real-time output never works on any production server I use but always works locally (Mac).

I know (kind of) that there is not really an issue with the code base (there could be checks in place to stop this being a regular occurrence).

http://stackoverflow.com/questions/42362014/symfony-process-real-time-output-not-working-on-nginx

```php
protected function runComposerSelfUpdate( $path )
{
    $process = new Process( 'php composer.phar update', $path, [ 'PATH' => env( 'PATH' ), 'HOME' => env( 'HOME' ) ] );
    $process->setTimeout(600);
    $process->run( function ( $type, $buffer ) {
            echo nl2br( $buffer );
    });
}
```

This is not the first time I've posted this but seems to be being swept under carpet. 

**So my question being**, is there any reason why real-time output **wouldn't work**, weather it be incorrectly implemented or server configuration/settings?

NGINX 
1 GB  
30 GB Disk 
Ubuntu 16.04.1 x64
Linux 4.4.0-62-generic x64
PHP 7.1

Greatly appreciate any help here.

**Comment by ProPheT777** [comment]
What is your intent ? Display it on browser right ? hint : `symfony-process-real-time-output-not-working-on-nginx` 

You have to disable the output buffering, because nginx is waiting that php process echo through the socket. Php is buffering the echoed response, to ensure that he send the whole response. In your case you won't that. 

```
       header('Content-Encoding: none;');

        set_time_limit(0);

        $handle = popen("<<< Your Shell Command >>>", "r");

        if (ob_get_level() == 0) 
            ob_start();

        while(!feof($handle)) {

            $buffer = fgets($handle);
            $buffer = trim(htmlspecialchars($buffer));

            echo $buffer . "<br />";
            echo str_pad('', 4096);    

            ob_flush();
            flush();
            sleep(1);
        }

        pclose($handle);
        ob_end_flush();
```
Example with crappy code above. 

May be you can try with a streamedResponse and put the `process->run()` as callback ?

**Comment by lukesnowden** [comment]
aha! Getting somewhere now @ProPheT777, added;

```cli
gzip off;
proxy_buffering off;
```

to the nginx config and im getting some output! But only in around 20 second intervals, would you know why this is?

Thank you very much

**Comment by ProPheT777** [comment]
Maybe a proxy timeout in nginx rules, have you try to increase proxy_timeout ? 

like `proxy_timeout 10m;` for example

**Comment by fabpot** [comment]
Closing as this is apparently a configuration issue and not related to Symfony.
