### ISSUE TITLE
SetEnv in Vhost don't work in mode production

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#21703]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.9

my website work with many subdomaines.for each domain, i configured a variable environnement with the instruction SetEnv ...

        DocumentRoot /var/www/acme/web
        ServerName test.acme.com
        SetEnv  SYMFONY__BOUTIQUE__CONFIG test

when i am in dev mode, i can to get my var with : %boutique.config%

but in prod mode, i don't work, the website don't recove the var.

For it to work I am forcing to change the second parameter of this line : 
$kernel = new AppKernel('prod', false) instead of $kernel = new AppKernel('prod', true).

the problem is that I no longer have my page errors in this case!!

What should I do to recover the environment variable in production mode?
Thanks

**Comment by stof** [comment]
This is because changing the ``SYMFONY__`` env variables does not trigger rebuilding the container in non-debug mode (checking the cache for freshness has a big impact on performance). The ``SYMFONY__`` env variables are read at compile time.

Symfony 3.2 added a new feature to be able to read env variables at runtime instead.

**Comment by strauss69400** [comment]
I am therefore forced to go to symfony 3.2 to be able to get this variable in production?

**Comment by stof** [comment]
if you want to read them at runtime, yes.

Btw, Symfony 3.0 is unmaintained since months, and stopped receiving *security* patches a few weeks ago. So you should definitely update: http://symfony.com/roadmap?version=3.0#checker

**Comment by jakzal** [comment]
@strauss69400 just to clarify. To re-read SYMFONY__ env vars you need to clear the cache.
