### ISSUE TITLE
[Form] ChoiceType "order_group_by" Option

### ISSUE THREAD

**Issue by JProffitt71** [symfony/symfony#21717]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2

Right now groups are ordered by their first occurrence in the group_by callable. I've run into a use-case where I cannot guarantee the order of that first occurrence, and need to be able to sort the groups after they are defined. It would be nice if there was an additional option to define a comparator for sorting groups.

In my specific case, I have a group_by function that looks like this:

```php
'group_by' => function ($entity) use ($soonThreshold) {
    switch (true) {
        case $entity->isComplete():
            return 'Complete';
        case $entity->willBeComplete():
            return 'Will Be Complete';
        case $entity->isOverDue():
            return 'Not Complete - Overdue';
        case $entity->isDueBy($soonThreshold):
            return 'Not Complete - Due Soon';
        default:
            return 'Not Complete - Due Later';
    }
}
```

My application requires these groups to be presented in this order, but I have no way to guarantee that the entities will be ordered in a way that produces that order (even with a query builder).

**Comment by HeahDude** [comment]
Hi @JProffitt71 I don't know why you closed here, but actually you can handle it in custom template.

Making a custom block will let you access the `choices` variable which can be an array of either `ChoiceView` or `ChoiceGroupView` indexed by group name.

So you can do:
```twig
{% block _form_name_choice_field_name_row %}

{% if choices['Complete'] is defined %}
    {% for choice in choices['Complete'] %}
        <input type="checkbox"
               name="{{ full_name }}[]"
               class="complete"
               value="{{ choice.value }}"
               {% set attr = choice.attr %}
               {{ block('attributes') }}
               {% if choice is selectedchoice(value) %}checked="checked"{% endif %}
         >
         <label>{{ choice.label }}</label>
    {% endfor %}
    {% for choice in choices['Will Be Complete'] %}
...
```

**Comment by JProffitt71** [comment]
Hi @HeahDude, I actually do not remember closing this. I thought perhaps it was rejected.

I found a solution for my case that's similar to yours - I made an extension to the ChoiceType that sorts the choices in buildView(). 

In implementing that algorithm I saw why maybe it isn't a built-in feature. Choice groups and choices can be mixed together at any particular level, and there's no good general way to handle that (sort groups in place; put ungrouped choices at the end / beginning; let the comparator function handle it?)

Since it's easy enough to extend the ChoiceType and implement this behavior however you expect it to work, I think it makes sense to leave it up to developers and not make it a core feature.

**Comment by HeahDude** [comment]
Thank you for your feedback. That's funny, I actually encountered a bug this week on a project that made me thought about deprecating using grouped choices as array of arrays in favor of the `group_by` option which gives no control over the order of the group. Creating a template is a solution but it's a bit cumbersome IMHO to do it just for this.

I would reopen here though, besides when @stof adds a "feature" label on an issue I would definitely not consider it as rejected ;).

**Comment by jordscream** [comment]
Hi @JProffitt71 @HeahDude, @stof  this feature interrests me ^^
How do you see the feature definition ? a new option for ChoiceType ? a new expected return of the method group_by ['value' => priority] ? other ideas ?

**Comment by webmozart** [comment]
I'm :-1: on this feature. The problem solved here can easily be solved by sorting the choices before passing them to the `choices` option (either with `usort()` or - better - in the database).

**Comment by xabbuh** [comment]
I agree with @webmozart. Closing here, thank you for understanding.

**Comment by althaus** [comment]
I understand the decision, but this makes a flaw in the form component for me. Groupable lists in combination with l10n of the items is quite a hazzle and the unreliable behaviour of the  `group_by` option doesn't help on it.
