### ISSUE TITLE
Swiftmailer still sends email if exception is thrown

### ISSUE THREAD

**Issue by graundas** [symfony/symfony#21719]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.1

When Exception is thrown in the Controller, I get a Response in the browser, which states, that Exception has occurred. The emails that are sent (using the built-in Swiftmailer) before throwing Exception, are **really sent** and shown in the Symfony Profiler.

As stated in the Docs, "the email only gets sent if the whole request got executed without any unhandled exception or any errors." (https://symfony.com/doc/current/email/spool.html).

I have spooling enabled in my config (spool: { type: memory }). Why emails are still being sent even if Exception occurs?

**Comment by pimolo** [comment]
Can you provide something to reproduce your bug ?

**Comment by stof** [comment]
that's a documentation issue. the terminate event is also called for cases where you have an exception caught by Symfony (it would not be triggered in case of fatal errors, as the code stops immediately)

**Comment by graundas** [comment]
So that's why I couldn't find anything in Swiftmailer bundle, that would protect emails from being really sent. I wonder how that (stopping emails sending) would be possible to implement. That would be a nice feature, because, for example, in my project, if Exception is thrown, then I rollback changes in the database, but emails are still being sent (i.e. about successful order, etc.).

Is there any way to detect, that an Exception has occurred, in the kernel.terminate event listener (argument passed to the listener is PostResponseEvent)?

**Comment by laskos** [comment]
@graundas maybe try send emails after flush the database?

**Comment by graundas** [comment]
If you have in mind sending emails in the controller/service, that will not be a solution if a fast response to the user is a priority. Sending emails consumes time depending on the service, which is chosen for sending them (i.e. amazon).

Emails should be sent in the kernel.terminate event listener.

> The final event of the HttpKernel process is kernel.terminate and is unique because it occurs after the HttpKernel::handle() method, and after the response is sent to the user.
> <..>trigger the kernel.terminate event where you can perform certain actions that you may have delayed in order to return the response as quickly as possible to the client (e.g. sending emails).
[http://symfony.com/doc/current/components/http_kernel.html#the-kernel-terminate-event](http://symfony.com/doc/current/components/http_kernel.html#the-kernel-terminate-event)

The problem is to detect in kernel.terminate event listener whether an exception was thrown anywhere in the application.

**Comment by HeahDude** [comment]
Then the mailer listener should listen to `kernel.exception` to turn on a flag that could condition the code of terminate handling.

**Comment by SimonHeimberg** [comment]
IMHO fixing this (in 1a7156621fb9) broke BC. Before I could simply send emails containing error information with enabled memory spool. Now I must disable memory spool, or do anything fancy I do not yet know. Any hints?

**Comment by graundas** [comment]
Maybe your application is badly implemented? If Exception is not caught, then there is something wrong with the application. I suggest you catching Exceptions.

**Comment by jvasseur** [comment]
@graundas sometimes letting the Symfony error handle handle the Exception (to log it and show an error page) is the right thing to do.

I agree with @SimonHeimberg here, the spool should be a transparent system and not change the application behavior.

**Comment by graundas** [comment]
I agree that sometimes there are things that need to be done unusually. I think that the most common scenario is an Email (i. e. info about successful order) sent during a Database transaction, which fails and is rolled back, but the user receives Email that his order is placed successfully, which actually is not. There are a lot of use cases similar to that (Notifications, Comments, Posts, etc) where Emails are sent during database transactions, which can fail. Of course, you can say that application logic could be rewritten, so that Email should be sent only if a transaction is successful, but in a system, which has a lot of event listeners and services, each of which is responsible for sending a specific emails, that would be difficult to implement.

I think that without this fix there would be more problems than benefits. Could you provide more details about your scenario, where you want to show an error (Exception) to the user and send all the emails after displaying that error?

**Comment by SimonHeimberg** [comment]
Exactly @jvasseur, we [overwrite the ExceptionContoller](https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-exceptioncontroller) to show a custom page and send an email to the system developers.

**Comment by SimonHeimberg** [comment]
@graundas, this works as you describe when **memory spool** is enabled. (Then no mail is sent on exception, since the fix.) BUT the mail **is** sent on exception when there is *no spool* as well as when there is *file spool*.

When we want to write a bundle that works same with every mail configuration, we have to check the spooling type to get fully consistent behaviour. Unhandy! (Best is to only call mail sending when the mail should really be sent. Then spooling does not matter except in some rare cases. Rarely means that the mail is sent or not when an exception happens after sending, depending on the spool type.)

**Comment by graundas** [comment]
I agree with that. It should be more transparent about sending emails in case of Exception. Maybe there could be additional option in the swiftmailer configuration like **send_on_exception**.

**Comment by robfrawley** [comment]
> the spool should be a transparent system and not change the application behavior.

Yes.

**Comment by Richard87** [comment]
Is there any temporary fix?
I use this to send me an email if there are any unhandled exceptions occuring on production :/

Richard

**Comment by graundas** [comment]
Have you tried [http://symfony.com/doc/current/logging/monolog_email.html](http://symfony.com/doc/current/logging/monolog_email.html) ?

**Comment by Richard87** [comment]
Yeah, that's what I am using, but I stopped receiving emails after updating last thursday...

        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'eportal@skilnet.no'
            to_email:   'richard.hagen@gmail.com'
            subject:    An Error Occurred!
            level:      debug

**Comment by graundas** [comment]
Try disabling memory spooling in the swiftmailer configuration.

**Comment by Richard87** [comment]
Hi, when using Deduplicated or buffered there are a new error message in Monolog

SwiftMailer changed the signature of a `setDate()` :(

![image](https://user-images.githubusercontent.com/5749715/27033377-53f5c8b4-4f79-11e7-9864-d1ff586e1b77.png)

**Comment by sstok** [comment]
Can't you can configure a secondary spooler that sends directly, and use that for the exception mailer??

**Comment by Richard87** [comment]
Hi, I fixed it with downgrading swiftmailer and swiftmailer bundle... :(
