### ISSUE TITLE
Define a controller using a closure

### ISSUE THREAD

**Issue by psampaz** [symfony/symfony#21728]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

I am trying to define a controller using a closure (like in Silex) in order to create a Route.

routing_test.php

```php
<?php
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Routing\Route;

$collection = new RouteCollection();
$collection->addCollection(
    $loader->import("routing_dev.yml")
);

$route = new Route('/api/testToken', [], [], [], '', [], ['GET']);
$route->setDefault('_controller', function () { return new Response(); });
$collection->add('api_test_token', $route);

return $collection;
```

While I see that the Route component supports this (https://github.com/symfony/symfony/blob/826639cf368075be9381166316d43cf123622e52/src/Symfony/Component/Routing/Tests/RouteTest.php#L90)

when I try to add a Route in SF full stack framework I get an error on 

Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php:49

because the DelegatingLoader tries to parse a string and convert it to class::method format.

Is this considered a bug or it is just not supported by Symfony Framework?

thank you

**Comment by stof** [comment]
the fullstack framework does not support closures, because it dumps an optimized router in the cache, and closures are not supported in this process

**Comment by javiereguiluz** [comment]
@stof can you estimate the complexity of adding support for this feature? Or maybe there's some PHP/technical limitation?

Partially related to this. The other day I was playing with the Symfony microkernel and when I saw this:

```php
$routes->add('/random/{limit}', 'kernel:randomAction');
```

I thought: `kernel:...` is ugly. I want to use this:

```php
$routes->add('/random/{limit}', [$this, 'randomAction']);
```

Or even a closure:

```php
$routes->add('/random/{limit}', function (Request $request, $limit) {
    // ...
});
```

**Comment by psampaz** [comment]
thank you @stof for your fast answer.

I actually wanted to ask you the same thing. Is there a limitation or this is something that could be added in the future if someone works on this on a PR?

It seems helpful in cases of prototyping and testing or in the microkernel.

**Comment by fabpot** [comment]
The limitation is due to a PHP limit. There is no way in PHP to dump a closure. There are some libraries trying to do that, but there are fragile. So, that's why we don't have this feature in Symfony.

**Comment by javiereguiluz** [comment]
👍 closing it then, because there's a compelling reason for the "won't fix". Thanks!

**Comment by sstok** [comment]
Would it make sense to at least give an exception when this is detected rather then then trying to parse the controller?

**Comment by psampaz** [comment]
@sstok +1 for the exception.
