### ISSUE TITLE
Strategy for SCA

### ISSUE THREAD

**Issue by kalessil** [symfony/symfony#21725]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

First I want to clarify: we are not talking about CS, but about dead code, probable bugs and other things I was contributing.

It would be very helpful to understand how I could contribute into newer branches (so far it was the oldest one, e.g. 2.7). Main concern is merge ability of course.

One idea I have is coordinated planning based on a component, e.g. filesystem and then iterations over supported branches. This would allow to efficiently interact with one maintainer and reduce amount of merge issues.

Any thoughts on this?

**Comment by javiereguiluz** [comment]
@kalessil I love your contributions ... but I can also understand the "pain" that some changes may introduce to mergers.

Anyway, this is only that can only be answered by our main mergers: @fabpot and @nicolas-grekas. Thanks!

**Comment by fabpot** [comment]
I think it depends on the number of changes, but more importantly the need for those changes. If they fix bugs, or if this is to remove dead code, that might make sense indeed. Having a lot of PR is probably not a good idea. For changes with a lots of impact on other branches, what we do is one PR in 2.7, and then we "freeze" merging anything else until we have merge all branches. It needs coordination, but that's doable and we do that from time to time.

**Comment by javiereguiluz** [comment]
Closing it as "answered". @kalessil as you can see, there's no clear answer because it depends on the proposed changes.

Hopefully, your PRs are created automatically ... so if they are eventually rejected, you probably haven't wasted a lot of your time. Thanks!

**Comment by kalessil** [comment]
Thank you @fabpot for the answer, let's stick to small PRs and reasonable changes then.

@javiereguiluz: yep, the topic is clarified.
