### ISSUE TITLE
Generated code is not complient withe php-cs-fixer @Symfony rule

### ISSUE THREAD

**Issue by Dragnucs** [symfony/symfony#21721]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^2.7

Code generated by commande line tools like Command or entity generators do not fully respect the rule `Symfony` set by php-cs-fixer.

Most obvious example are phpdoc_summary and trailing_comma_in_multiline_array.

**Comment by javiereguiluz** [comment]
@Dragnucs you are right! However, this code belongs to the SensioGeneratorBundle, so the fix must be proposed in that other repository. I've moved your issue to https://github.com/sensiolabs/SensioGeneratorBundle/issues/538  so I'm closing this one. Thanks!
