### ISSUE TITLE
Enable the twig.controller.preview_error service only when needed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21738]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.x

Although I don't load the Twig error preview URLs in production, in the dumped container I can see the following service:

```php
'twig.controller.preview_error' => 'getTwig_Controller_PreviewErrorService',

// ...

protected function getTwig_Controller_PreviewErrorService()
{
    return $this->services['twig.controller.preview_error'] = new \Symfony\Bundle\TwigBundle\Controller\PreviewErrorController(${($_ = isset($this->services['http_kernel']) ? $this->services['http_kernel'] : $this->get('http_kernel')) && false ?: '_'}, 'twig.controller.exception:showAction');
}
```

Should TwigBundle load this service conditionally?

```xml
<service id="twig.controller.preview_error" class="Symfony\Bundle\TwigBundle\Controller\PreviewErrorController">
    <argument type="service" id="http_kernel" />
    <argument>%twig.exception_listener.controller%</argument>
</service>
```

**Comment by stof** [comment]
We cannot load the service only when routes are imported (routing config is not yet processed when building the container, and is independent). so this would require adding a new configuration setting in TwigBundle. Is it worth it ?

**Comment by javiereguiluz** [comment]
If we define a new option (and that's a big "if") we could simplify a lot of things:

1) Add a new option:

```yaml
# config_dev.yml
framework:
    preview_errors:
        enabled: true
```

2) Remove the ENTIRE `routing_dev.yml` file and instead:

* Load `@WebProfilerBundle/Resources/config/routing/wdt.xml` automatically when`web_profiler.toolbar` is `true`
* Load `@WebProfilerBundle/Resources/config/routing/profiler.xml` automatically when `framework.profiler` is enabled

3) Simplify the `config_dev.yml`:

```diff
framework:
-    router:
-        resource: "%kernel.root_dir%/config/routing_dev.yml"
-        strict_requirements: true
```

Removing `routing_dev.yml` would be great to reduce the perceived complexity of Symfony.

**Comment by sstok** [comment]
The exception page is only used when debugging is enabled, so adding an extra option seems unnecessary 🤔

**Comment by javiereguiluz** [comment]
I'm closing this because with Symfony Flex, everything will be even simpler and without the need of doing anything special. Thanks!
