### ISSUE TITLE
Remove some class parameters related to Routing

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21735]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.x

In the `@FrameworkBundle/Resources/config/routing.xml` we define some parameters related to Routing classes. They don't follow the exact `[...].class` naming syntax used by Symfony in the past, but they look the same:

```xml
<parameter key="router.options.generator_class">Symfony\Component\Routing\Generator\UrlGenerator</parameter>
<parameter key="router.options.generator_base_class">Symfony\Component\Routing\Generator\UrlGenerator</parameter>
<parameter key="router.options.generator_dumper_class">Symfony\Component\Routing\Generator\Dumper\PhpGeneratorDumper</parameter>
<parameter key="router.options.matcher_class">Symfony\Bundle\FrameworkBundle\Routing\RedirectableUrlMatcher</parameter>
<parameter key="router.options.matcher_base_class">Symfony\Bundle\FrameworkBundle\Routing\RedirectableUrlMatcher</parameter>
<parameter key="router.options.matcher_dumper_class">Symfony\Component\Routing\Matcher\Dumper\PhpMatcherDumper</parameter>
<parameter key="router.options.matcher.cache_class">%router.cache_class_prefix%UrlMatcher</parameter>
<parameter key="router.options.generator.cache_class">%router.cache_class_prefix%UrlGenerator</parameter>
```

Shouldn't we remove these parameters as we did with every other `.class` param?

**Comment by fabpot** [comment]
+1 for removing those parameters.

**Comment by lstrojny** [comment]
What’s the alternative if one wants to register a custom generator base class ?

**Comment by jakzal** [comment]
@lstrojny the alternative is to [decorate](https://symfony.com/doc/current/service_container/service_decoration.html) or replace the service.
