### ISSUE TITLE
[Forms] NumberType value not updating

### ISSUE THREAD

**Issue by foaly-nr1** [symfony/symfony#21734]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

I noticed that when trying to change a NumberType's value from 37.36 to 37.37, it wouldn't update. I've created unit tests that reproduce the issue. The issue doesn't occur when setting an empty field's value to 37.37.

Assertion fails at: https://github.com/foaly-nr1/symfony/blob/153041ab7604b36ac33e2ef13d490edda739e994/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php#L80

```bash
$ phpunit --filter=NumberTypeTest -v
Clock-mocked namespaces for SymfonyTestsListener need to be nested in a "time-sensitive" key. This will be enforced in Symfony 4.0.
PHPUnit 5.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.15 with Xdebug 2.5.0
Configuration: /Users/jonnyschmid/Sites/symfony/phpunit.xml.dist

Testing Symfony Test Suite
.....F                                                              6 / 6 (100%)

Time: 7.91 seconds, Memory: 130.00MB

There was 1 failure:

1) Symfony\Component\Form\Tests\Extension\Core\Type\NumberTypeTest::test3736to3737
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-37,37
+37,36

/Users/jonnyschmid/Sites/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php:80

FAILURES!
Tests: 6, Assertions: 6, Failures: 1.
```

**Comment by dmaicher** [comment]
Your `->setData('36.37')` call is ignored here because initial data is passed so the form data is "locked":

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L323

**Comment by HeahDude** [comment]
@foaly-nr1 Thank you for providing a test for your issue, sadly @dmaicher is right, passing initial data on form creation is the same as setting the `data` option, so it cannot further be changed.

This issue can be closed.

**Comment by HeahDude** [comment]
Btw, If you really need to override it, you can use a listener on `PRE_SET_DATA` event and use `$event->setData()` instead.

**Comment by foaly-nr1** [comment]
I don't seem to have created tests that adequately illustrate the behaviour I'm struggling with. Please see my screencast below. Surely both fields should show the updated value upon submission, not just one of them.

The demo application can be found here: https://github.com/foaly-nr1/symfony-standard/tree/number-type-issue-demo

![37-37](https://cloud.githubusercontent.com/assets/282458/23317499/95cc0508-fac6-11e6-803c-4af98c53fcf1.gif)

**Comment by foaly-nr1** [comment]
@dmaicher @HeahDude would love if you could have another look!

**Comment by dmaicher** [comment]
@HeahDude @xabbuh maybe there is a problem indeed.

If we change this line https://github.com/foaly-nr1/symfony/blob/153041ab7604b36ac33e2ef13d490edda739e994/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php#L77

into `$form->submit('37.37');` then the test still fails - but it shouldn't? Did not have time to investigate further yet...

**Comment by dmaicher** [comment]
Ok after checking a bit it seems to be something weird happening with php floating point numbers...

Inside `NumberToLocalizedStringTransformer` this is happening:

```php
$number = '37.37';
$number *= 100; //float(3737)
$number = floor($number); //float(3736) ???
$number /= 100; //float(37.36);

**Comment by foaly-nr1** [comment]
Right, we are testing `submit()` not `setData()`. As per https://github.com/foaly-nr1/symfony/blob/e1cd408d7af7a70f2d25026f3dd6fef3a44affd3/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php#L77.

They both fail now. So it will be a rounding problem.

```bash
phpunit --filter=NumberTypeTest -v
Clock-mocked namespaces for SymfonyTestsListener need to be nested in a "time-sensitive" key. This will be enforced in Symfony 4.0.
PHPUnit 5.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.15 with Xdebug 2.5.0
Configuration: /Users/jonnyschmid/Sites/symfony/phpunit.xml.dist

Testing Symfony Test Suite
....FF                                                              6 / 6 (100%)

Time: 8.2 seconds, Memory: 130.00MB

There were 2 failures:

1) Symfony\Component\Form\Tests\Extension\Core\Type\NumberTypeTest::test3737
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-37,37
+37,36

/Users/jonnyschmid/Sites/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php:71

2) Symfony\Component\Form\Tests\Extension\Core\Type\NumberTypeTest::test3736to3737
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-37,37
+37,36

/Users/jonnyschmid/Sites/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/NumberTypeTest.php:80

FAILURES!
Tests: 6, Assertions: 6, Failures: 2.
```

**Comment by foaly-nr1** [comment]
In fact

```php
floor(3737); // double(3737)
floor(37.37*100); // double(3736)
```

**Comment by xabbuh** [comment]
see also https://3v4l.org/ldkKI

reopening here as we IMO need to look into how to solve this

**Comment by foaly-nr1** [comment]
I've added a data set to an existing test of `NumberToLocalizedStringTransformerTest`: https://github.com/foaly-nr1/symfony/blob/2c4004d92932ac42ef44a4e4229d56d47ad14a58/src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php#L308

Now failing with:

```bash
$ phpunit --filter=NumberToLocalizedStringTransformerTest -v
Clock-mocked namespaces for SymfonyTestsListener need to be nested in a "time-sensitive" key. This will be enforced in Symfony 4.0.
PHPUnit 5.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.15 with Xdebug 2.5.0
Configuration: /Users/jonnyschmid/Sites/symfony/phpunit.xml.dist

Testing Symfony Test Suite
...............................................................  63 / 206 ( 30%)
............................................................... 126 / 206 ( 61%)
..........F.................................................... 189 / 206 ( 91%)
.................                                               206 / 206 (100%)

Time: 7.48 seconds, Memory: 130.00MB

There was 1 failure:

1) Symfony\Component\Form\Tests\Extension\Core\DataTransformer\NumberToLocalizedStringTransformerTest::testReverseTransformWithRounding with data set #32 (2, '37.37', 37.369999999999997, 2)
Failed asserting that 37.359999999999999 matches expected 37.369999999999997.

/Users/jonnyschmid/Sites/symfony/src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php:366

FAILURES!
Tests: 206, Assertions: 221, Failures: 1.
```

**Comment by foaly-nr1** [comment]
Possible solution:

```php
$number = floor(37.37*100); // double(3736)
var_dump($number);
$number = floor(bcmul(37.37, 100)); // double(3737)
var_dump($number);
```

From http://php.net/manual/en/language.types.float.php#language.types.float:

> Additionally, rational numbers that are exactly representable as floating point numbers in base 10, like 0.1 or 0.7, do not have an exact representation as floating point numbers in base 2, which is used internally, no matter the size of the mantissa. Hence, they cannot be converted into their internal binary counterparts without a small loss of precision. This can lead to confusing results: for example, floor((0.1+0.7)*10) will usually return 7 instead of the expected 8, since the internal representation will be something like 7.9999999999999991118....
> 
> So never trust floating number results to the last digit, and do not compare floating point numbers directly for equality. If higher precision is necessary, the arbitrary precision math functions and gmp functions are available.
