### ISSUE TITLE
RedisTrait::createConnection() does not support password with ":"

### ISSUE THREAD

**Issue by Nicofuma** [symfony/symfony#21745]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

The regex used to extract the password from the DSN in RedisTrait::createConnection() (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Traits/RedisTrait.php#L75) does not match correctly the password containing the character `:`.

Ex:
dsn: `redis://foo:bar@127.0.0.1`
extracted $auth: `bar`
expected $auth: `foo:bar`

Note: Redis does not support login/password but only a single password.

**Comment by nicolas-grekas** [comment]
That's on purpose, for compatibility with SncBundle DSNs and with
parse_str, from `http://user: password@...`

You need to use eg `redis://ignored:my:pass@...`

**Comment by javiereguiluz** [comment]
@Nicofuma this was a nice catch! @nicolas-grekas thanks for the explanation. I've opened https://github.com/symfony/symfony-docs/issues/7531 to fix this in the docs. Thanks!
