### ISSUE TITLE
Minus sign(-) is replaced with a dash(−) after rendering NumberType.

### ISSUE THREAD

**Issue by vbaur** [symfony/symfony#21746]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.7

After setting the default locale to lithuanian I've noticed the following unexpected behaviour: after rendering the NumberType widget with a negative value inside, minus sign(-) is replaced with a dash(−) , which in turn makes JS unable to parse the given string to a number.

I am not sure if it affects any other languages or if this error is locale specific.

**Comment by javiereguiluz** [comment]
Are we sure this is caused by Symfony? I've looked into the form templates and the NumberType widget and I don't see anything. Moreover, I've looked for the dash `−` in my entire `vendor/` directory and there were 0 matches.

**Comment by xabbuh** [comment]
Closing due to the lack of feedback.

@vbaur I will happily reopen here if you can provide an example to reproduce your issue.
