### ISSUE TITLE
FatalThrowableError should call the parent __construct

### ISSUE THREAD

**Issue by fifsky** [symfony/symfony#21743]
The class extend FatalErrorException, but not call parent __construct

https://github.com/fifsky/symfony/commit/7500a8eb8c4d4f7a0d615737d3fadb96d4b6a4c8

**Comment by jakzal** [comment]
ping @nicolas-grekas

I'm sure [it was done](https://github.com/symfony/symfony/commit/e94b31f3a03edabf6aeee5317aa51475dbcdc90e#diff-472eb74b4f0fd7983dae3cfd67d6bfbcR34) for a reason, but I have no idea why. PHP7 compatibility? #14469

**Comment by stof** [comment]
The FatalErrorException constructor does special handling of the stack trace (and calls its parent constructor for everything else). And we don't want to perform the special for FatalThrowableError. this is why we call the grand-parent constructor directly instead.

**Comment by nicolas-grekas** [comment]
@stof is right, no bug here
