### ISSUE TITLE
Don't create Twig's translation extractor service if not needed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21757]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.x

In a Symfony app I have disabled the entire `translation` service. In 3.2, the production container still contained lots of translation related things, but in 3.3 everything has gone ... except for 1 service:

```php
'twig.translation.extractor' => 'getTwig_Translation_ExtractorService',

// ...

protected function getTwig_Translation_ExtractorService()
{
    return $this->services['twig.translation.extractor'] = new \Symfony\Bridge\Twig\Translation\TwigExtractor(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->get('twig')) && false ?: '_'});
}
```

Should we enable this service conditionally too? Thanks!

**Comment by xabbuh** [comment]
Since #20799 we remove this service when the Translation component is not present. Shouldn't that be enough as having the component installed without using it doesn't make much sense, does it?

**Comment by javiereguiluz** [comment]
@xabbuh I'll check again ... but my issue was created after upgrading a Symfony app to `dev-master`, so the #20799 PR should be there.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" ... I've just created an app with Flex, installed Twig and I can no longer see this translation related service. Thanks!
