### ISSUE TITLE
symfony/var-dumper Tests/Fixtures/GeneratorDemo.php linting error (not valid till PHP 7)

### ISSUE THREAD

**Issue by reedy** [symfony/symfony#21750]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 3.0

From 3.0, the required PHP version is specified in composer.json as >= 5.5.9 https://github.com/symfony/var-dumper/blob/3.0/composer.json

https://github.com/symfony/var-dumper/blob/3.0/Tests/Fixtures/GeneratorDemo.php#L14 is not valid syntax till >= 7.0

2.8 has this file too https://github.com/symfony/var-dumper/blob/2.8/Tests/Fixtures/GeneratorDemo.php but only requires php >= 5.3.9

https://3v4l.org/RYlVX

```
Output for 5.5.0 - 5.6.30
Parse error: syntax error, unexpected 'bar' (T_STRING) in /in/RYlVX on line 14

Process exited with code 255.

Output for 5.4.0 - 5.4.45
Parse error: syntax error, unexpected '1' (T_LNUMBER) in /in/RYlVX on line 9

Process exited with code 255.

Output for 5.3.0 - 5.3.29
Parse error: syntax error, unexpected T_LNUMBER in /in/RYlVX on line 9

Process exited with code 255.
```
only  hhvm-3.11.1 - 3.13.2, hhvm-3.15.4 - 3.17.1, 7.0.0 - 7.1.2 report no error

I do note that in https://github.com/symfony/var-dumper/blob/3.0/Tests/Caster/ReflectionCasterTest.php#L146 it does annotate that it requires PHP 7

Which is then going to come back to the argument that "you shouldn't be linting your vendor directory", which may be true, but as been pointed out numerous times, people do for various reasons....

Does this make this a WONTFIX?

**Comment by fabpot** [comment]
The PHP version in composer.json is just the minimum version we support, not the max. I don't see any issue here on Symfony's side.

**Comment by stof** [comment]
Well, some fixtures files indeed use newer syntaxes, but they are used in tests which are skipped on older version.
You should not be linting test fixtures of the vendor library.

Removing tests ensuring compatibility with PHP 7 features is indeed a total no-go. So this is a won't fix.

**Comment by iltar** [comment]
This is the only way to test things like anonymous classes, nullable hints, scalar types etc.

**Comment by xabbuh** [comment]
closing as there is nothing to fix

**Comment by kenorb** [comment]
Related: #11921
