### ISSUE TITLE
Symfony memory leak on windows

### ISSUE THREAD

**Issue by cirovargas** [symfony/symfony#21753]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.9

I am facing problems with symfony on Windows (Windows Server 2012 R2 Datacenter Edition)

Every day (sometimes more than once a day) the system stop to work because of memory problems:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 54 bytes)

Symfony is not reading the cache data but reloading the src to each request (the cache folder growing up to 10GB)

The PHP version is 7.0.6 x86, Apache 2.4 MPM WinNT

Restarting the service solves my problem but i believe this solution is not appropriate

**Comment by stof** [comment]
which folder is growing that large inside the cache ? Are you able to determine it ?

**Comment by javiereguiluz** [comment]
I don't know if this is the case, but the directory used by the HTTP cache is usually the one that grows indefinitely. See #4871 for related issues and PR attempts.

**Comment by cirovargas** [comment]
@stof i cleared the cache now, can reply you later. @javiereguiluz  is not my case, dont use http cache (use render_esi to render blocks but not cache http properly)

**Comment by javiereguiluz** [comment]
@cirovargas did you manage to investigate more details about this issue? (such as the folder/s that grow the most)

**Comment by cirovargas** [comment]
twig and annotation. if ia modify a template or configuration the symfony ever reload.

This happens on any windows/apache machine.

Permissions on this folders is granted for 'All' read/write and full control

**Comment by cirovargas** [comment]
Some logs:

> [2016-10-08 15:29:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Out of memory (allocated 2097152) (tried to allocate 32768 bytes)" at C:\app\apache_php\apache2\htdocs\ouvidoria\var\cache\prod\twig\e6\e60d73545b68ff8dd395d7b0f7ba16aa49cb4ac30765667898e7aa0f0027347d.php line 60 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Out of memory (allocated 2097152) (tried to allocate 32768 bytes) at C:\\app\\apache_php\\apache2\\htdocs\\ouvidoria\\var\\cache\\prod\\twig\\e6\\e60d73545b68ff8dd395d7b0f7ba16aa49cb4ac30765667898e7aa0f0027347d.php:60)"} []

> [2016-10-08 15:29:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Out of memory (allocated 2097152) (tried to allocate 397312 bytes)" at C:\app\apache_php\apache2\htdocs\ouvidoria\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php line 91 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Out of memory (allocated 2097152) (tried to allocate 397312 bytes) at C:\\app\\apache_php\\apache2\\htdocs\\ouvidoria\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []

> [2016-10-08 16:50:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Out of memory (allocated 2097152) (tried to allocate 16384 bytes)" at C:\app\apache_php\apache2\htdocs\ouvidoria\vendor\symfony\symfony\src\Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator.php line 65 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Out of memory (allocated 2097152) (tried to allocate 16384 bytes) at C:\\app\\apache_php\\apache2\\htdocs\\ouvidoria\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\ChoiceList\\Factory\\CachingFactoryDecorator.php:65)"} []

**Comment by jakzal** [comment]
@cirovargas can you try to upgrade to Symfony 3.2? [Symfony 3.1 doesn't receive bug fixes](http://symfony.com/roadmap?version=3.1#checker) anymore.

Also, are you able to answer stof's questions?

> which folder is growing that large inside the cache ? Are you able to determine it ?


One more test you could do is to try a fresh installation of standard edition. This will rule out (or confirm) the possibility there's something in your code causing the leaks.

**Comment by nicolas-grekas** [comment]
Could be fixed by #21973, please confirm.

**Comment by nicolas-grekas** [comment]
Rereading, maybe not in fact :) Please upgrade to 3.2 then report again as suggested.

**Comment by HeahDude** [comment]
ping :)

**Comment by javiereguiluz** [comment]
Closing it due to lack of feedback. Please upgrade to Symfony 3.3 (to be released next week) and reopen this issue if the issue persists. Thanks!

**Comment by cirovargas** [comment]
Using Symfony 3.4 now, my cache folder grew up 246GB
![scachelolulo](https://user-images.githubusercontent.com/1972562/35818499-64f7dd72-0a87-11e8-86c9-95f0ad204598.png)

**Comment by jakzal** [comment]
Which folder inside `cache/dev` or `cache/prod` grows so much?

**Comment by javiereguiluz** [comment]
Maybe it's `cache/test/` (that's the one which grows the most in my apps ... and it's because the profiling data: `var/cache/test/profiler/`).
