### ISSUE TITLE
[DependencyInjection] Ignore tags of abstract services

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#21761]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

[As pointed by @nicolas-grekas](https://github.com/symfony/symfony/pull/21730#discussion_r103076676), tags of abstract services can now be inherited so we should probably stop throwing exceptions when having the case and just ignore them.
I suggest to do this by adding an argument to `ContainerBuilder::findTaggedServiceIds`:
```php
public function findTaggedServiceIds(string $name, bool $ignoreAbstractServices = false);
```

**Comment by chalasr** [comment]
Sadly adding an argument to a public method is forbidden by the BC promise, even with a default value.

**Comment by GuilhemN** [comment]
@chalasr this tip should be mentionned on http://symfony.com/doc/current/contributing/code/bc.html imo, most people do not know it.

**Comment by nicolas-grekas** [comment]
Let's just *not* add any argument ad deal with that inline in each Pass.
