### ISSUE TITLE
Security documentation: The Big Picture is missing

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#21760]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (documentation)
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

Hello,
I'm digging through Symfony's Security components trying to implement a custom security bundle, and I really miss one thing: The Big Picture. There is a lot written about individual components and even source code is quite understandable, but there is nothing about how these components work together.

The workflow diagrams in [HttpKernel documentation](http://symfony.com/doc/current/components/http_kernel.html) are extremely helpful. There should be similar diagrams included in [Security component documentation](https://symfony.com/doc/current/components/security.html). How all these components interact with each other? What happens during ordinary HTTP request? What happens during login? What happens during subsequent HTTP requests? …? …?

The documentation says there are some components (Guards missing, btw) and that's it. No relation between them is provided. No context. Nothing about basic principles nor ideas.

Security is important and must be well understood to make it right. A cookbook without context is not enough — it helps when one understands, but does not make him understand. Symfony Security component is powerful and complex, so it is hard to get into it.

Someone who has deep understanding of the Security component, please, draw few diagrams how it works. It will help many other developers.

**Comment by javiereguiluz** [comment]
@jkufner you are right ... but for docs-related issues, we use the symfony-docs repository. That's why I'm closing this.

Moreover, we have some issues related/duplicated of this: https://github.com/symfony/symfony-docs/issues/7496

In any case, I think it's a mistake to document/explain the complexity of the Security component. In my opinion, we should first reduce that complexity (as proposed in #21029) and then document it.

**Comment by jkufner** [comment]
Ok, created a new issue there.

> In any case, I think it's a mistake to document/explain the complexity of the Security component. In my opinion, we should first reduce that complexity (as proposed in #21029) and then document it.

That would be perfect. However, perfect is enemy of good. Moreover, mapping of current situation is the first step to getting it better.
