### ISSUE TITLE
FQCN is Service Complexe expression, bad generated

### ISSUE THREAD

**Issue by alborq** [symfony/symfony#21777]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version   |2.8.9

Hi
 I try to Inject Values Based on Complex Expressions
Escaping seems to be not correct : 

Code snippet is a couple of déclaration, cache generated : 

OK:  backslash is not escaped 
```php 
@=service('doctrine.orm.geolid_em_entity_manager').getReference('Components\Notification\Entity\Notification', 'activity_report_monthly')
$this->get("doctrine.orm.geolid_em_entity_manager")->getReference("ComponentsNotificationEntityNotification", "activity_report_monthly")
```

NOK : backslash escaped, not generated in cache
```php 
@=service('doctrine.orm.geolid_em_entity_manager').getReference('Components\\Notification\\Entity\\Notification', 'activity_report_monthly')
$this->get("doctrine.orm.geolid_em_entity_manager")->getReference("ComponentsNotificationEntityNotification", "activity_report_monthly")
```

Become magic : 1 escaped twice, other escaped 0 and spécial char is generated
```php 
@=service('doctrine.orm.geolid_em_entity_manager').getReference('Components\\\Notification\\\Entity\\\Notification', 'activity_report_monthly')
$this->get("doctrine.orm.geolid_em_entity_manager")->getReference("Componentsotification\\Entityotification", "activity_report_monthly")
```

**Comment by dmaicher** [comment]
Does this work for you?

```yaml
"@=service('doctrine.orm.default_entity_manager').getReference('Components\\\\Notification\\\\Entity\\\\Notification', 'activity_report_monthly')"

**Comment by alborq** [comment]
@dmaicher, I test, and yes, it working. Can you explain why ? it's really normal ? 
Components\\Notifi... is not a good syntax ?

**Comment by xabbuh** [comment]
@alborq You need to escape a backslash with four backslashes (see http://symfony.com/doc/current/components/expression_language/syntax.html#supported-literals).

**Comment by alborq** [comment]
Thanks for your reply.
