### ISSUE TITLE
[console] Ambiguous keys get wrongly autocompleted

### ISSUE THREAD

**Issue by dritter** [symfony/symfony#21789]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.4

My situation is as follows:
I have a console application that uses a ChoiceQuestion with version numbers as values. Rendered the question looks like this:
```
  [0]: 3.0.0
  [1]: 2.2.0
  [2]: 2.1.3
```
If I select option "2" I'll get "2.2.0", because the value gets autocompleted.

It even fails with associative arrays:
```
  [a]: berlin
  [b]: copenhagen
  [c]: amsterdam
```
If I select "b", I get "a", the key of the first option, as its value is found by the autocompleter.

Here is a testcase to demonstrate the behaviour:
```php

    public function testAmbiguousKeyFromChoicelist()
    {
        $possibleChoices = array(
            'a' => 'berlin',
            'b' => 'copenhagen',
            'c' => 'amsterdam',
        );

        $dialog = new QuestionHelper();
        $helperSet = new HelperSet(array(new FormatterHelper()));
        $dialog->setHelperSet($helperSet);

        $question = new ChoiceQuestion('Please select the environment to load', $possibleChoices);
        $question->setMaxAttempts(1);

        $answer = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream("b\n")), $this->createOutputInterface(), $question);

        $this->assertSame("b", $answer);
    }
```

A possible solutions could be:
  - Do not consider keys as autocomplete values (so keys must match exactly)
  - Do consider keys as autocomplete values, but the take precedence over values

My preference would be the first option.

**Comment by timonf** [comment]
My first review. I hope I doing it right! I already started bugfixing, I will create a PR when bug is confirmed.

Thank you @dritter for creating this bug report! This indeed looks like a bug. I reproduced the bug in the "ticket_21789_input_test" branch of https://github.com/timonf/symfony-standard. See this [test command](https://github.com/timonf/symfony-standard/blob/ticket_21789_input_test/src/AppBundle/Command/QuestionHelperTestCommand.php).

![21789_wrongautocompletion_versions](https://cloud.githubusercontent.com/assets/546813/24370955/8696cb92-1329-11e7-892c-fa00826bf958.png)
![21789_wrongautocompletion_towns](https://cloud.githubusercontent.com/assets/546813/24370954/8685bf1e-1329-11e7-971f-375b2edaece4.png)

Status: Reviewed

**Comment by dritter** [comment]
@timonf Awesome! This problem is even worse on Windows, as there you don't see the autocompletion. So in the second example of your screenshot, you'll type "b" and see only "b", press enter and the value gets autocompleted..

Btw. your testcommand looks good to me. 👍

**Comment by Nek-** [comment]
IMO it's not a bug, it's a feature! It suggests something, which is cool!

In another hand not seeing anything in windows while there is an actual completion running is a bug.

**Comment by timonf** [comment]
I am using [Certificationy CLI](https://github.com/certificationy/certificationy-cli). I ran into the same problem. I enter the number of the right answer (in this case "4"), but Symfony Console component will autocomplete the second answer. I think keys should have a higher priority like in my [fix](https://github.com/timonf/symfony/commit/370348748b678ab0b35b97f8929626d0e8195a00#diff-312c2e9ca43f41955ae78e8adf50fe49R318).

![certificationycliautocompletenumbered](https://cloud.githubusercontent.com/assets/546813/24395381/c328eea2-139f-11e7-9fe6-beb1c7a7ad8f.png)

**Comment by timonf** [comment]
I did some more tests... it's still a very strange behavior.

I extended the test above:

```php
    public function testAmbiguousKeyFromChoiceList()
    {
        $numericChoices = array(
            '0' => '20',
            '1' => '100',
            '2' => '200',
        );

        $numericChoicesWithoutKeys = array(
            '20',
            '100',
            '200',
        );

        $versionChoices = array(
            '0' => '1.0',
            '1' => '2.2',
            '2' => '2.3',
        );

        $versionChoicesWithAlphaKeys = array(
            'a' => '1.0',
            'b' => '2.2',
            'c' => '2.3',
        );

        $alphabeticalChoices = array(
            'a' => 'berlin',
            'b' => 'copenhagen',
            'c' => 'amsterdam',
        );

        $dialog = new QuestionHelper();
        $helperSet = new HelperSet(array(new FormatterHelper()));
        $dialog->setHelperSet($helperSet);

        $question = new ChoiceQuestion('Q1', $numericChoices);
        $answer1 = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream('2' . PHP_EOL)), $this->createOutputInterface(), $question);

        $question = new ChoiceQuestion('Q2', $numericChoicesWithoutKeys);
        $answer2 = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream('2' . PHP_EOL)), $this->createOutputInterface(), $question);

        $question = new ChoiceQuestion('Q3', $versionChoices);
        $answer3 = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream('2' . PHP_EOL)), $this->createOutputInterface(), $question);

        $question = new ChoiceQuestion('Q4', $versionChoicesWithAlphaKeys);
        $answer4 = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream('b' . PHP_EOL)), $this->createOutputInterface(), $question);

        $question = new ChoiceQuestion('Q5', $alphabeticalChoices);
        $answer5 = $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream('b' . PHP_EOL)), $this->createOutputInterface(), $question);

        echo PHP_EOL;
        echo $answer1 . PHP_EOL;
        echo $answer2 . PHP_EOL;
        echo $answer3 . PHP_EOL;
        echo $answer4 . PHP_EOL;
        echo $answer5 . PHP_EOL;
    }
```

And now... the question: What is the output? :D 

Here is the answer:

```
20
20
2.2
b
a
```

It also looks strange with my current [fix](https://github.com/timonf/symfony/commit/370348748b678ab0b35b97f8929626d0e8195a00#diff-312c2e9ca43f41955ae78e8adf50fe49R318) (WIP):

```
20
20
2.2
b
b
```

The problem is the default validator of `ChoiceQuestion` class. It is acting different with associative arrays. Here is the code:

```php
# src/Symfony/Component/Console/Question/ChoiceQuestion.php
                if (!$isAssoc) {
                    if (false !== $result) {
                        $result = $choices[$result];
                    } elseif (isset($choices[$value])) {
                        $result = $choices[$value];
                    }
                } elseif (false === $result && isset($choices[$value])) {
                    $result = $value;
                }
```

My fix would only cover the issues with strings as keys.

**Comment by RonanSauvage** [comment]
Hello,

I'm not sure this developement is compliant with SF's best practices but it has the merit of making ChoiceQuestion available with "choices" argument on Windows' CLI.

I've not found similar function to that Console\Helper->getOSTerminal(). 

I've tried with two differents OS (WIN & LINUX) and results have all been within the expected function questionHelper->ask(). 

You can see it in : https://github.com/RonanSauvage/symfony/commit/22ddb90552c84bbc33fc7c496c8133cea90d68d4

Now to try to PR this is another question because without update after initial clone, i've some unit tests failures.

**Comment by xabbuh** [comment]
@RonanSauvage It's better to open a pull request with your changes as that eases reviewing the code and you will also see the full result of our test suite on Travis CI and AppVeyor.

**Comment by nicolas-grekas** [comment]
See #26875
