### ISSUE TITLE
[SecurityBundle] something is broken after recent commits

### ISSUE THREAD

**Issue by antanas-arvasevicius** [symfony/symfony#21809]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-dev

Today we've got build error in our system: 
Restored to last worked version on 'd69bb304001e57e00678b86e8e499067889db538'
Hope this info will help to spot a problem.
```
[04:39:32][Ant output]      [exec]      [exec] > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
[04:39:32][Ant output]      [exec]      [exec] 
[04:39:32][Ant output]      [exec]      [exec] 
[04:39:32][Ant output]      [exec]      [exec]   [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
[04:39:32][Ant output]      [exec]      [exec]   The service "security.authentication.provider.simple_form.default" has a de
[04:39:32][Ant output]      [exec]      [exec]   pendency on a non-existent service "security.user.provider.concrete.carrier
[04:39:32][Ant output]      [exec]      [exec]   User".
```

Our security.yml:
```yml
security:
    providers:
        carrierUser:
            entity:
                class: System\Entity\CarrierUser
                property: email

    erase_credentials: false
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: carrierUser
            simple-form:
                check_path: /login_check
                require_previous_session: false
                authenticator: tms.security.authentication.provider
                failure_handler: auth.failure_handler
                failure_forward: true
                failure_path: false

    encoders:
        System\Entity\CarrierUser: bcrypt
```

**Comment by antanas-arvasevicius** [comment]
Little findings: on working version there line in container build logs:
```Symfony\Component\DependencyInjection\Compiler\InlineServiceDefinitionsPass: Inlined service "security.user.provider.concrete.carrieruser" to "security.firewall.map.context.default".```


but in not working version there is line

``Symfony\Component\DependencyInjection\Compiler\InlineServiceDefinitionsPass: Inlined service "security.user.provider.concrete.carrierUser" to "security.firewall.map.context.default".```

Previous version automatically lowercased every provider name, but new version looks like not converting to lower cases. Maybe this is a case.

**Comment by xabbuh** [comment]
Which commit exactly did you use when experiencing this issue?

**Comment by antanas-arvasevicius** [comment]
today latest i think, just checked out from teamcity work dir:
here is: 28a00dac0c396f2880b84bc33d7abae698d4d94a

**Comment by antanas-arvasevicius** [comment]
But I don't know exactly which commit fails.

**Comment by xabbuh** [comment]
Can you check if the issue still persists when you only use lowercase letters for the user provider name?

**Comment by mvrhov** [comment]
If only the case sensitivity is the problem AFAIR this was done on purpose. And it should be in Changelog/Upgrade document.

**Comment by antanas-arvasevicius** [comment]
Yes, works then lowercasered. If it's by purpose then should throw exception about saying what is wrong exactly during configuration validation I think.
I'll probably tracked which commit broken this and will write details soon

**Comment by antanas-arvasevicius** [comment]
found a problem, it was during inconsistent getUserProviderId() usage, sometimes it was called like:
 getUserProviderId(strtolower($name)); sometimes like  getUserProviderId($name);

Fixed by putting strtolower() inside getUserProviderId

https://github.com/symfony/symfony/commit/fbd9f88e312d03614b7e96ed3a1c8c993eb8c0b5#diff-2be909961a57bf75fbb600c1f5fc46e3R320

**Comment by xabbuh** [comment]
@antanas-arvasevicius That commit was reverted later on. That's why I wonder if you still experience the issue when using the latest `master` branch.

**Comment by xabbuh** [comment]
Never mind, I see that f6637dd9008deb786823aba02102870e4bd26e25 wasn't merged up to master yet.
