### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#21816]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | probably
| RFC?             | no
| Symfony version  | 3.2.4

Hello symfony's team,

I'm experiencing an issue with Symfony 3.2.4. I want to implement functionnal tests by following this documentation: http://symfony.com/doc/current/best_practices/tests.html

When I run the test with the following command:
phpunit tests/AppBundle

I got an error:
Class 'PHPUnit_Framework_TestCase' not found

I'm using the latest stable PHPUnit version, installed as PHAR.

Is it a bug or did I missed something? I can't find further information about this issue.

Thank you a lot for your help.

Kind regards,
Fabien

**Comment by theofidry** [comment]
Hi, this is happening because you are probably using PHPUnit 6 which no longer supports `PHPUnit_Framework_TestCase` and has been replace by `PHPUnit\Framework\TestCase`. See https://thephp.cc/news/2017/02/migrating-to-phpunit-6 for more information.

**Comment by fabienlem** [comment]
Hi @theofidry,

That was it! Now everything works as expected.

Thank you a lot :+1: I'm closing this issue.

Regards,
Fabien

**Comment by xabbuh** [comment]
@fabienlem Thanks for reporting your issue anyway. We will update the documentation in symfony/symfony-docs#7556 to reflect these changes in PHPUnit.

**Comment by stof** [comment]
@xabbuh don't spend too much time on this. Next releases (in all branches) will be compatible with PHPUnit 6

**Comment by xabbuh** [comment]
@stof I know. The docs PR just updates the examples to not use the old classes anymore (but use the namespaced classes instead).

**Comment by Yigaue** [comment]
This was helpful

**Comment by rejuancse** [comment]
// use the following namespace
use PHPUnit\Framework\TestCase;

// extend using TestCase instead PHPUnit_Framework_TestCase
class SampleTest extends TestCase {

}
