### ISSUE TITLE
Workflow GuardEvent Name of Workflow

### ISSUE THREAD

**Issue by timglabisch** [symfony/symfony#21818]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Hello,

the GuardEvent should contain the name of the workflow.

I wrote a Bundle that allows to check role based permissions in workflow transitions,
it was a mess to get the name of the current workflow :)

Tim

**Comment by lyrixx** [comment]
Hello @timglabisch ;

I just opened a PR. But unfortunately, as it's a new feature it will be merged into master (3.3) and not 3.2 as you asked for.
