### ISSUE TITLE
[Config] Transform a value into an array

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21817]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 3.x

In config trees is common to see code like the following to turn a value into an array:

```php
->beforeNormalization()
   ->ifTrue(function ($v) { return !is_array($v); })
    ->then(function ($v) { return array($v); })
->end()

// ...

->beforeNormalization()->ifString()->then(function ($v) { return array($v); })->end()
```

You can see it tens of times in Symfony, popular bundles and elsewhere. Could we add a helper method to remove this boilerplate code? Thanks!

**Comment by ro0NL** [comment]
See also #20223

Some generic if/then's for casting purposes would be really nice.

**Comment by javiereguiluz** [comment]
@ro0NL I partially agree with you. It's OK to add more if/then helpers ... but only if they are used enough. In the case of the string/number -> array conversion, it's a very common need (even in the Symfony code itself).

**Comment by ro0NL** [comment]
I'd vote for a generic solution, covering all types;

```
if()->is('string')->then()->castTo('array')
if()->is('numeric')->then()->castTo('int')
```

Something like that.

**Comment by fabpot** [comment]
I don't like the generic solution you suggest @ro0NL as it has many drawbacks. The main one being discoverability and autocompletion (think IDEs).

As @javiereguiluz suggested, we only need some of them, the most used ones. Let's do that.

**Comment by ro0NL** [comment]
Agree. My proposed syntax may not be suitable; i actually meant https://github.com/symfony/symfony/pull/20223#issuecomment-258602528 and indeed for common types only.

**Comment by ro0NL** [comment]
Rethinking the numeric to int conversion from #20223, it looks convenient but im not sure it's good practice. Ie. TTL values and such are probably best defined as an integer node anyway (being strict).. @chalasr  wdyt?

Not saying a generic conversion api doesnt workout, but it's most likely overkill.

What about tackling both usecases pointed out by @javiereguiluz  with a nice one-liner..

```php
->beforeNormalization()
   ->castToArray()
   ->ifNotInArray($arr)
   ->then($profit)
->end()
```

`castToArray` wraps the `ifPart` closure.

Any thoughts?
