### ISSUE TITLE
HttpCache does not alter the "Forwarded" header

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#21838]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 2.7 up to master

the `HttpCache::forward()` method deals with `X-Forwarded-For`, but not with the "newly" standardized `Forwarded` one.

**Comment by dmaicher** [comment]
Should it only alter an existing `Forwarded` header? Or also add a new one? Then we would add two headers though (`Forwarded` and `X-Forwarded-For`) :yum: But I guess that could be fine for maximum compatibility?

**Comment by jordscream** [comment]
@nicolas-grekas , @dmaicher , WDYT ? ^^ try to help :-P

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/symfony/symfony/commit/725dee4cd8b4ccd52e335ae4b4522242cea9bd4a
