### ISSUE TITLE
nvalidArgumentException' with message 'The class finder must implement a "findFile" method

### ISSUE THREAD

**Issue by ingmjg** [symfony/symfony#21836]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 1.4.20

**Comment by ingmjg** [comment]
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The class finder must implement a "findFile" method.' in 
/var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php:84\n
Stack trace:\n
#0 /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/liClassLoader.class.php(36): Symfony\\Component\\ClassLoader\\ApcClassLoader->__construct('S2A')\n#1 /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/liClassLoader.class.php(41): liClassLoader->__construct()\n
#2 /var/www/html/e-venement/plugins/sfDomPDFPlugin/config/sfDomPDFPluginConfiguration.class.php(31): liClassLoader::create()\n
#3 /var/www/html/e-venement/lib/vendor/externals/symfony1/lib/config/sfApplicationConfiguration.class.php(169): sfDomPDFPluginConfiguration->initialize()\n
#4 /var/www/html/e-venement/lib/vendor/externals/symfony1/lib/config/sfApplicationConfiguration.class.php(150): sfApplicationConfiguration->initializePlugins()\n
#5 /var/www/html/e-venement/lib/vendor/exter in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php on line 84, referer: http://localhost/e-venement/web/event.php/event.html

**Comment by fabpot** [comment]
Closing this issues as symfony1 is not maintained anymore.
