### ISSUE TITLE
constraints is not an option

### ISSUE THREAD

**Issue by Cathmor** [symfony/symfony#21839]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

I made a classless form for credit cards and want to put super basic validation on it. Added the constraints option like the documentation shows ([http://symfony.com/doc/current/form/without_class.html](url)) and used the correct use statements for Length and am getting the "options 'constraint' does not exist" error. 

I'm not sure if this is a bug or not, it could very well be a user error on my part and I'm just reading the documentation badly. 

My code looks something like this

`->add('SecurityCode', TextType::class, array(
    'required' => true,
    'constraints' => array(
        new Length( array('min' => 3, 'max' => 3) ),
    'empty_data' => null
))`

**Comment by HeahDude** [comment]
Hi @Cathmor, the `constraints` option is defined by the validator extension of the Form component, please ensure that the [`FormTypeValidatorExtension`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/Type/FormTypeValidatorExtension.php) is registered as a service if you don't use the `FrameworkBundle`, or directly passed to the form factory or the form registry depending on the version of symfony you're using.

**Comment by xabbuh** [comment]
Closing here as you indeed need to register the extension manually when not using the full framework as @HeahDude said.

**Comment by Cathmor** [comment]
Thank you! I am using the form outside the framework bundle so this is my issue.
