### ISSUE TITLE
UniqueEntityValidator throw a PHP Notice: Undefined index

### ISSUE THREAD

**Issue by apimobi** [symfony/symfony#21847]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.1.*

The issue has been solved in others version
Hi can you merged the fix applied on 2.8 and 3.2 in 3.1 on Validator?

> [https://github.com/symfony/symfony/blame/2.8/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L112]

**Comment by xabbuh** [comment]
Symfony 3.1 had reached end of maintenance by the end of January. So you will only receive security fixes. You need to update to 3.2 to get bugfixes too (see https://symfony.com/roadmap).
