### ISSUE TITLE
[ParamConverter] optional route parameter gets set always

### ISSUE THREAD

**Issue by mktcode** [symfony/symfony#21848]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.4

I have the following controller action which can be accessed through two different routes:

```php
/**
 * Creates a new event entity (or copies an existing one).
 *
 * @Route("/new/{type}", name="event_new")
 * @Route("/new/copy/{baseEvent}", name="event_new_copy")
 * @Method({"GET", "POST"})
 */
public function newAction(Request $request, $type = Event::TYPE_DEFAULT, Event $baseEvent = null)
{
    dump($baseEvent);
    if ($baseEvent) {
        $event = clone $baseEvent;
    } else {
        $event = new Event();
        $event->setType($type);
    }

    // process form ...

}
```

When I call /new/copy/1 I get my event form prefilled with the data of baseEvent BUT this is also the case when I just call /new.

The dump($baseEvent); tells me that $baseEvent is always the first event entity from my database.

The debug toolbar says the current route name is event_new and not event_new_copy.

When I call /new/sometype then $baseEvent is null, as expected.

Can anyone explain this behaviour to me?

For now I use

```php
if ($baseEvent && $request->attributes->get('_route') == 'event_new_copy') {
    $event = clone $baseEvent;
} else { ...
```

as a workaround.

http://stackoverflow.com/questions/42578006/optional-route-parameter-gets-set-always

**Comment by javiereguiluz** [comment]
Can you try moving the more specific `event_new_copy` route on top of the less specific `event_new` route?

If this doesn't work, could you add a requirement to the `event_new` to prevent the word `copy` as the value of `type`? Using regular expressions is tricky to negate an entire word; you must use something like this:

```
@Route("/new/{type}", requirements={ type: "^(?!.*copy).*$"}, name="event_new")
```

**Comment by jakzal** [comment]
@mktcode is type a property of your `Event`? If yes, than what you're probably experiencing is the `DoctrineParamConverter` selects the first event of the given type. If this is the case, then there's no bug here. You might try to [tweak the DoctrineParamConverter options](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#doctrine-converter) to prevent this behaviour (i.e. only allow querying by the id), but I think it's the best if you simply split your method into two. This way it will also be easier to understand what's going on and where the parameters are coming from.

**Comment by javiereguiluz** [comment]
Closing it because there's no more feedback, so this was probably fixed by @jakzal suggestions. Thanks!
