### ISSUE TITLE
[DomCrawler] Strange Bug that removes closing Style Tag

### ISSUE THREAD

**Issue by thaasch** [symfony/symfony#21852]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.2.4

The Symfony Dom Crawler has a strange Issue. When you do a `document.write` inside a Script tag and you put a opening and a closing tag inside the write the closing tag gets removed. 

Here is the Code Demo:

```
<?php
use Symfony\Component\DomCrawler\Crawler;


$html = <<<'HTML'
<!DOCTYPE html>
<html>
    <head>
		<script type="text/javascript">
			document.write('<style type="text/css">.jserror {display:none}</style>')
		</script>	
    </head>
</html>
HTML;

$crawler = new Crawler($html);
echo($crawler->html());
```

**Comment by stof** [comment]
Parsing the HTML itself is done by PHP (and libxml in the underlying code), not by Symfony DOMCrawler (we rely on PHP's DOM API).

Btw, browsers used to do the same in the past, which is why it was common to use string concatenation between the ``<`` and the tag name.

**Comment by thaasch** [comment]
Thanks for the quick response. My problem is that i have no influence on the html i download it via Guzzle and cache it inside a template. Can you suggest a workaround @stof ?

**Comment by jakzal** [comment]
Closing, since there's nothing we can do in Symfony. The same happens if you use the DOM API directly:

```
$dom = new \DOMDocument('1.0', 'UTF-8');
@$dom->loadHTML($html);
echo $dom->saveHTML($dom);
```

I know it's not perfect, but you could do sth like the following to mitigate the issue:

```$html = str_replace('</style>\'', '<\'+\'/style>\'', $html);```

**Comment by thaasch** [comment]
I fixed it by using a simple regular expression:

 `preg_replace('/(([\'"]).*)(<\/([^>]*)>).*\2/', "$1</$2.$2$4>$2", $html);` 

now everything works fine :)
