### ISSUE TITLE
HttpFoundationRequestHandler::handleRequest() doesn't handle empty form data

### ISSUE THREAD

**Issue by LordWeedlle** [symfony/symfony#21895]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | ?
| Symfony version  | 2.8.15

Hi,
I'm upgrading from Symfony 2.3 to 2.8 and ran into an issue.
I'm using an entity which get some properties let's see it as follow
```php
class MyEntity
{
    private $myProperty;
}
```
I'm missing annotations as this code it is only for demonstration purpose, but it is a symfony entity.
I got a controller action which list MyEntity's entites and I got a filter system to show all my entites or only those with `$myProperty` corresponding to what I want.
We can imagine the controller action as follow:
```php
function listAction(Request $request)
{
    $form = $this
        ->createForm(MyEntityFormType::class, [], ['method' => $request->getMethod()])
        ->handleRequest($request)
    ;
}
```

In `symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler::handleRequest()` function there is in line 109 this verification:
```php
// Don't auto-submit the form unless at least one field is present.
if ('' === $name && count(array_intersect_key($data, $form->all())) <= 0) {
    return;
}
```

I never have form name in sent data on my whole project. When I try to call my controller action `listAction` without filtering on `MyEntity::myProperty` form is not submitted because no field are present in form while I could before as I was using `submit()` function.

I found a workaround checking if I'm in this particular case and then resubmitting manually the form but it's kind of ugly and definitly not a good practice.
```php
$form = $this
    ->createForm(MyEntityFormType::class, [], ['method' => $request->getMethod()])
    ->handleRequest($request)
;

// $form->handleRequest() doesn't submit request with no data
// If the form doesn't get errors and the request doesn't get
// data we manually call $form->submit() w/ computed data
if (!$form->isSubmitted() && (0 === count($form->getErrors(true))) && $form->isEmpty()) {
    $requestData = $request->request->all();
    $queryData = $request->query->all();
    $form->submit(array_merge($defaultValue, $queryData, $requestData));
}
```

Is there a best practice to handle this case ?
Is this a case which is not supposed to be ?

**Comment by xabbuh** [comment]
Even with Symfony 2.8 you could still use `submit()` if you want to submit the form regardless the form of the current request. Is this an API or why do you need your form to don't have a name?

**Comment by LordWeedlle** [comment]
Yes, this is an API.
I'm trying to use `handleRequest` as when I send data they are part of `$request` object and `handleRequest` is designed to parse this.
If I go using only submit I'll need to duplicate code which is already present in `handleRequest` function and most of the time `handleRequest` do the work.

**Comment by iltar** [comment]
Note: don't use forms in an API, simply use a (de)serializer and the validator and you're done.

**Comment by HeahDude** [comment]
Hello @LordWeedlle, the solution here is quite simple: just use a custom handler if you need a special processing of the request post data and query and in your type class do:
```php
class MyEntityFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setRequestHandler(new MyRequestHandler());
        // ...
    }
}
```
You can of course inject it with your form type as a service.

Actually the HttpFoundationHandler is doing his job and parses the query for GET and post data for POST request, it also checks that fields or form name are present as parameters, never had any issues until now when using it with API, also FosRestBundle is using forms quite well.

If you need such logic in many types, you can create a base type and make other types extend it:
```php
class ApiFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setRequestHandler(new MyRequestHandler());
        // Maybe you would also need to add specific token field to all children
    }
}

class MyEntityFormType extends AbstractType
{
    public function getParent()
    {
        return ApiFormType::class;
    }
}
```

**Comment by xabbuh** [comment]
@HeahDude Wouldn't such a case even better be solved with a form type extension that offers an option like `api` which turns the behaviour on or off? That way you wouldn't have to work with the inheritance chain and could also use this feature for form types you don't own.

**Comment by HeahDude** [comment]
Yes there are many way to solve this, I chose to demonstrate what I guess the simplest in this case, not the most flexible :).

**Comment by HeahDude** [comment]
Btw, it's better to avoid extension when possible as it adds overhead on every types, in most cases one needs to extends `FormType` and all types inherit this one except buttons.

**Comment by javiereguiluz** [comment]
Reading the comments it looks like this one is solved, so I'm closing it. Reopen if you disagree. Thanks!
