### ISSUE TITLE
Add a way to find "best match" for content-type based on Accept header

### ISSUE THREAD

**Issue by anlutro** [symfony/symfony#21909]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.x

In Python, the framework Flask has a method on its `AcceptHeaders` equivalent called `best_match` which basically compares the `Accept` header with your list of available content-types and returns the best match.

I found myself implementing this manually in an abstract controller class:

```php
foreach ($request->getAcceptableContentTypes() as $type) {
	if ($type == 'application/json') { return $type; }
	if ($type == 'text/plain') { return $type; }
	if ($type == 'text/html') { return $type; }
}
return 'text/plain';
```

Is this something that could be added to the `AcceptHeaders` class?

PS: I wasn't able to find any info on what RFC yes/no entails so I might have put the wrong thing there.

*(edit by @lyrixx: Yes, it's a RFC, I fixed the PR description. Thanks)*

**Comment by julienfalque** [comment]
I think what your are looking for is https://github.com/willdurand/negotiation.

**Comment by anlutro** [comment]
That looks solid, but for my fairly simple needs a ~10 line method of code is really all that's needed. I'm wondering if a simpler implementation of said negotiation could belong in Symfony itself.

**Comment by javiereguiluz** [comment]
@anlutro could you please share the link to the source code of that method? I only find references to it in this old article: http://flask.pocoo.org/snippets/45/  Thanks!

**Comment by anlutro** [comment]
It's implemented in werkzeug, which is like flask's version of http-foundation, if you will.

https://github.com/pallets/werkzeug/blob/36a1444686ba4e4736400d6d94b8d637559fea7b/werkzeug/datastructures.py#L1723

**Comment by anlutro** [comment]
I'd be happy to make a pull request with a sample implementation, by the way.

**Comment by javiereguiluz** [comment]
@anlutro that's why I didn't find it in the Flash repo 😅  Thanks!

**Comment by javiereguiluz** [comment]
We already define a `getPreferredLanguage()` method ... so adding a `getPreferredContentType()` could make sense ... but let's wait for more comments. Thanks!
