### ISSUE TITLE
Custom operator on ExpressionLanguage

### ISSUE THREAD

**Issue by hanprat** [symfony/symfony#21907]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | dunno

Is there a way to add or extend a custom operator in symfony expression language? For example, I want to use this expression:

`cart.items intersect ['123', 'xyz', 'ab3'] and cart.total_items >= 20`

where `intersect` is a custom binary operator between `array` and `array` and check their intersection.

**Comment by fabpot** [comment]
You can create a function, which is the main extension point.

**Comment by sroze** [comment]
@fabpot does this mean you are not keen in seeing an new extension point for operators?

**Comment by matthewfedak** [comment]
@fabpot @sroze @hanprat I also need an intersect operator or something which achieves the same result. Is it possible to create such a feature using just a function or do I need to fork the library?

**Comment by sroze** [comment]
@matthewfedak yes you can create your own `intersect` function that you'll use like that (from your example): `intersect(cart.items, ['123', 'xyz', 'ab3'])`

**Comment by sstok** [comment]
@matthewfedak everything can be done with a function as in practice an operator is nothing more then syntactic sugar for a binary expression. 

In fact, when using a custom operator in SQL it actually uses a function to perform the operation 😄

**Comment by matthewfedak** [comment]
@sstok @sroze Thank you very much both of you. I have a working solution now:

    // expression i want to evaluate
    $expression = "intersect(choices, ['jan', 'gregor', 'hans'])";

    // arguments passed to the expression (in my case sanitized checkbox form fields i.e. choices[])
    $aData = ['choices' => ['jan', 'chris', 'andre']];

    // create new expression language object
    $language = new ExpressionLanguage();
   
    // register new intersect function
    $language->register('intersect', function () {
        // not used
    }, function ($args, $firstParam, $secondParam) {
        // returns true if some common names found
        return (!empty(array_intersect($firstParam, $secondParam)));
    });

    // evaluate expression and return bool (true in this example as 'jan' was a common name )
    $result = $language->evaluate($expression, $aData);
