### ISSUE TITLE
Errors on HHVM LTS 3.18

### ISSUE THREAD

**Issue by photodude** [symfony/symfony#21900]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | master branch

the following errors occurred on the current HHVM LTS 3.18

```php
syntax error, unexpected '{', expecting $end or TC_SECTION or TC_LABEL or END_OF_LINE in /home/travis/build/symfony/symfony/src/Symfony/Component/DependencyInjection/Tests/Fixtures/ini/nonvalid.ini on line 1

syntax error, unexpected JUNK in /home/travis/build/symfony/symfony/src/Symfony/Component/DependencyInjection/Tests/Fixtures/ini/almostvalid.ini on line 1

Fatal error: Class already declared: appFrameworkbundletestsessionDebugProjectContainer in /tmp/3.3.0-DEV/Session/cache/frameworkbundletestsession/appFrameworkbundletestsessionDebugProjectContainer.php on line 20
```

see build 
https://travis-ci.org/symfony/symfony/jobs/208295490

note: test does not complete more than 96% and thus does not report the additional errors

**Comment by fabpot** [comment]
Do you want to work on fixes for those errors? HHVM is not actively maintained by the core team, but we are more than happy to merge PRs to fix problems.

**Comment by photodude** [comment]
I will if I can figure out the issues. Not sure my skills are up to that, or when I will have some time to attempt to dig into the details.

**Comment by fabpot** [comment]
@photodude Thank you.

**Comment by nicolas-grekas** [comment]
Fixes done in https://github.com/symfony/symfony/pull/21917/files?w=1 :)
