### ISSUE TITLE
Cannot convert VarDumper\Cloner\Data to string while using sub-requests - profiler bug

### ISSUE THREAD

**Issue by ivanbarlog** [symfony/symfony#21911]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

When using sub-requests and trying to checkout profiler timeline of sub-request I am getting following error:

> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Symfony\Component\VarDumper\Cloner\Data could not be converted to string").

I have found the issue at following line https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.html.twig#L111

When you dump `profile.getcollector('request').requestattributes.get('_controller')` you can see that it contains array, not just string.

```
Data {#3521 ▼
  -data: array:1 [▼
    0 => array:1 [▼
      0 => "Path:ToYour:action"
    ]
  ]
  -position: 0
  -key: 0
  -maxDepth: 20
  -maxItemsPerDepth: -1
  -useRefHandles: -1
}
```

I would fix it but I am not sure if it should be fixed within the `time.html.twig` template or the problem is with VarDumper data cloner hence I am reporting this bug.

**Comment by nicolas-grekas** [comment]
Can you please chec wrapping that call into a `profiler_dump()`? 
`{{ profiler_dump(profile.getcollector('request').requestattributes.get('_controller')) }}`

**Comment by ivanbarlog** [comment]
I tried to replicate the issue and it seems that you have found the solution eg. wrapping call into `profiler_dump()` helped.

Output for `{{ profile.getcollector('request').requestattributes.get('_controller') }}` is

```
Data {#6191 ▼
  -data: array:1 [▼
    0 => array:1 [▼
      0 => "SomeBundle:Some:action"
    ]
  ]
  -position: 0
  -key: 0
  -maxDepth: 20
  -maxItemsPerDepth: -1
  -useRefHandles: -1
}
```

whilst output for `{{ dump(profile.getcollector('request').requestattributes.get('_controller')) }}` is:

```
"SomeBundle:Some:action"
```

Would you like to fix it or should I fix it and create pull request?

**Comment by ivanbarlog** [comment]
Oh, but that's not the solution, right? Because this dumps the value not "prints" it out...

**Comment by nicolas-grekas** [comment]
Pleas submit a PR adding profiler_dumpa round. The correct output is "SomeBundle:Some:action" indeed.

**Comment by ivanbarlog** [comment]
This is probably not the correct solution since the `profiler_dump` adds some styling to the output (see the picture below)

![image](https://cloud.githubusercontent.com/assets/2583610/25125212/47b4f474-242e-11e7-8865-c60cdfb0939e.png)

**Comment by nicolas-grekas** [comment]
See #22874
