### ISSUE TITLE
TextType empty_data = null if string is empty

### ISSUE THREAD

**Issue by markoffk** [symfony/symfony#21928]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.2.4

Hello. 

I am getting null value after passing empty string to symfony form field. 
After defining empty_data in form builder, the problem has gone:
```
        $builder
            ->add('name', TextType::class, [
                'empty_data'  => '',
            ])
```

But documentation claims that empty_data is empty string ('') by default. So either the documentation should be changed or behavior of form field type.

Link to docs: http://symfony.com/doc/current/reference/forms/types/text.html#empty-data

Thanks.

**Comment by stof** [comment]
Please open an issue in the doc repo. This is a documentation issue (changing the behavior of the code is a no-go as it would be a BC break and the text type behaves this way since Symfony 2.0.0)

**Comment by markoffk** [comment]
Thanks. 
You can close existing issue.
The new link to issue is here: https://github.com/symfony/symfony-docs/issues/7596
