### ISSUE TITLE
[Cache] PhpArrayAdapter chmod its cache file to 0666

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#21929]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

Is there a reason why the `chmod($tmpFile, 0666)` is forced?
https://github.com/symfony/symfony/blob/c60009eae8506cfd31786fdcd867b4e76478345a/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php#L153

**Comment by stof** [comment]
@nicolas-grekas shouldn't it be ``0666 ~ umask()`` instead ?

**Comment by nicolas-grekas** [comment]
PR welcomed :)
