### ISSUE TITLE
How to include CMS features?

### ISSUE THREAD

**Issue by SDPrio** [symfony/symfony#21921]
Hi,

This is not a bug report or a feature request but a question about how to use Symfony in general. I am sorry, that I have to use to use the issue tracker, but I found no other sources to answer my question. I have learned, that there are nor dump question, and I hope that this is not an exception :-)

**The question is: How to include CMS features in a Symfony based web app?**

I am working on a "classic" web app, that is separated into a public front end that promotes and describes the features on the one hand, and a private back end that offers the web app features to logged in users. 

While Symfony is really great to create the web app itself and all the features for the users, it seems to be quite limited when it comes to create the plain content of the public front end like feature, help, support, price, etc. pages. 

Adding a new pages requires creating a new route, new controller, new template, etc. All these steps are only possible when having direct access to the source code. While this is not a big issue for a developer, it is out of question, that a "simple author" (= content creator) could perform these steps. 

Of course I know about the **Symfony CMF** project, but my goal is not to create a new CMS and to re-invent the wheel. I just want to add some CMS features to my Symfony web app.

I also know about bundles like **EkinoWordpressBundle**, which allow to connect Symfony with an existing CMS (Wordpress in this case). However these solution seems to focus on integrating Symfony into Wordpress and not (as much) on integrating Wordpress in Symfony. 

**I am looking for a simple solution to let authors add, edit and manage pages without access to the source code.** 

Currently I have simply separated the CMS from Symfony: While the Symfony web app is running under `ourWebApp.xy`, the content is manged by Wordpress under `help.ourWebApp.xy` and `blog.ourWebApp.xy`. While this obviously workes fine, this solution has some major disadvantages. From a SEO point of view, these are three different webpages and content on one of the subdomains does not count for the main domain. Additionally the subdomains cannot use "common" pages parts created by Symfony (e.g. header and footer). 

**So, what is the correct solution to reach this goal with Symfony?** 
 
Thank you very much!

**Comment by javiereguiluz** [comment]
@SDPrio thanks for bringing up this interesting discussion. Sadly, we use the Symfony repository only to report bugs or ask for new features, so questions like these should be asked on our official support channels (I recommend you to use Slack): https://symfony.com/support

---

Now I'll add some comments about your question:

* If you want a truly simple CMS, take a look at the Symfony Demo app: https://github.com/symfony/symfony-demo  Just replace "Blog" by "CMS" and "Blog Post" by "Page" and that's it.
* If you want a full-featured CMS, use Drupal, which uses Symfony components.
* If you want something in between, there are a ton of CMS built with Symfony:
  * Simple CMS: http://symfony.com/projects/bolt, http://symfony.com/projects/grav, http://symfony.com/projects/forkcms
  * More advanced CMS: http://symfony.com/projects/sulu, http://symfony.com/projects/pagekit, http://symfony.com/projects/victoire
  * Static site generators: http://symfony.com/projects/sculpin, http://symfony.com/projects/spress, http://symfony.com/projects/carew
