### ISSUE TITLE
The index "castañuelas" created by the choice list is invalid. It should be a valid, non-empty Form name.

### ISSUE THREAD

**Issue by dramentol** [symfony/symfony#21934]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

In class Symfony\Component\Form\FormConfigBuilder:

```
    /**
     * Returns whether the given variable contains a valid form name.
     *
     * A name is accepted if it
     *
     *   * is empty
     *   * starts with a letter, digit or underscore
     *   * contains only letters, digits, numbers, underscores ("_"),
     *     hyphens ("-") and colons (":")
     *
     * @param string $name The tested form name
     *
     * @return bool Whether the name is valid
     */
    public static function isValidName($name)
    {
        return '' === $name || null === $name || preg_match('/^[a-zA-Z0-9_][a-zA-Z0-9_\-:]*$/D', $name);
    }
```

As far as I know 'ñ' is a letter but a $name including 'ñ' will not pass validation, so either wrong implementation or wrong docblock comment.

**Comment by stof** [comment]
Well, it is an accentuated letter, not a basic letter

**Comment by dramentol** [comment]
@stof I have to disagree with you. 'ñ' is not an accentuated letter, it's a letter as any other, at least in spanish. But still if that was the case the docblock says nothing about basic or accentuated letters.

Is there any reason for only a-z A-Z letters being accepted?

**Comment by Nek-** [comment]
I guess you want it as value and not index. That's why you get an error. Can you give the code that generates this error ?

**Comment by dramentol** [comment]
@Nek- You are completely right. I'm trying to use a field other than the id on an entity choice list. I thought index was used for the value.

Thanks.
