### ISSUE TITLE
[Form]/[Doctrine][Bridge] EntityType broken for "multiple" under Symfony 3.2.5

### ISSUE THREAD

**Issue by superhaggis** [symfony/symfony#21947]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.5

Assuming either https://github.com/symfony/symfony/pull/21656, https://github.com/symfony/symfony/pull/21267 or https://github.com/symfony/symfony/pull/21880 broke the expected behaviour of Doctrine Bridge's EntityType.

Assumptions:
- You have an entity called AppBundle\Entity\Foo with correct annotations - fields: id, name
- The database schema has been updated to reflect the entity
- There is one row in the database table with ID 1
- CSRF disabled for brevity

Use case:
- Create a form called "bar", add an EntityType widget with the name "foo"; set "class" to "AppBundle:Foo"; set "choice_label" to "name"; set "multiple" to "true", set "invalid_message" to "Invalid value: {{ value }}".
- Post the following data to the form: bar[foo][]=1
- Evalulate $form->isValid()

Expected:
- Evaluates to boolean true.

Actual:
- Evalulates to boolean false - form errors state that for field "foo", the error is "Invalid value: array".

I rolled back to Symfony 3.2.4 and received the expected outcome of $form->isValid() evaluating to boolean true.

**Comment by xabbuh** [comment]
Support for Symfony 2.4 ended over two years ago (see http://symfony.com/roadmap?version=2.4#checker). None of the PRs that you are talking about was ever merged into the `2.4` branch. Are you sure that you are using that Symfony version?

**Comment by superhaggis** [comment]
D'oh, I meant 3.4.5.  Sorry, wrote that in a hurry. 👅

**Comment by wouterj** [comment]
Hmm, 3.4 isn't released yet. We're at 3.2 and 3.3-dev now.

**Comment by xabbuh** [comment]
@superhaggis Could you please fork the Symfony Standard Edition and make changes that allow to reproduce your issue?

**Comment by superhaggis** [comment]
Doing too many things at once. 😢 

Issue with 3.2.5 - sorry, I don't have time at the moment to fork to reproduce.  Deadlines etc..

**Comment by yceruto** [comment]
https://github.com/symfony/symfony/pull/21880 is about intl form types (not related to Doctrine Bridge's EntityType)

**Comment by yceruto** [comment]
https://github.com/symfony/symfony/pull/21656 is about tests only (not related too)

**Comment by mcfedr** [comment]
Seems to be the same as https://github.com/symfony/symfony/issues/21952

**Comment by yceruto** [comment]
Confirmed! same as #21952 and fixed in https://github.com/symfony/symfony/pull/21957
