### ISSUE TITLE
Wrong ConsoleCommand exit code on some exceptions

### ISSUE THREAD

**Issue by sourcerer-mike** [symfony/symfony#21940]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

I got this:

```
int(22519) // error_reporting
string(1) "1"  // display_errors

                                                                                                           
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                             
  Attempted to call an undefined method named "first" of class "Doctrine\ORM\Tools\Pagination\Paginator".  
                                                                                                           

worker:run [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

root@live:/var/www# echo $?
0
```

Yes Paginator has no ::first method.
But I expected Symfony to have an exit code different than zero.

Reproducable:

```
protected function execute(InputInterface $input, OutputInterface $output)
{
        $nope->getCarter();
}
```

Exit code is still zero.

**Comment by xabbuh** [comment]
Thank you for reporting this issue @sourcerer-mike. However, I still have to close here as a duplicate as we already have #20775 to track this.

**Comment by sourcerer-mike** [comment]
What the hell? Sorry for that. Didn't found those while searching for the problem. :/

**Comment by xabbuh** [comment]
no problem :)
