### ISSUE TITLE
ChoiceType with int values broken

### ISSUE THREAD

**Issue by mcfedr** [symfony/symfony#21952]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.5

I am using Forms to validate incoming data, and have `ChoiceType`s that receive int.

#21267 introduces a change that requires all values to strings. Clearly this breaks stuff.

Example: 

```php
->add('days', ChoiceType::class, [
    'choices' => [
        'Mon' => 1,
        'Tue' => 2,
        'Wed' => 3,
        'Thu' => 4,
        'Fri' => 5,
        'Sat' => 6,
        'Sun' => 7,
    ],
    'preferred_choices' => [(int) date('w')],
    'multiple' => true,
    'by_reference' => false,
])
```

And the submitted data is:

```php
'days' => [1, 2, 3, 4, 5, 6, 0],
```

I am using forms to handle data coming in as json, using [mcfedr/json-form](https://github.com/mcfedr/json-form/blob/master/src/Mcfedr/JsonFormBundle/Controller/JsonController.php#L25)

**Comment by mcfedr** [comment]
Created a test for this: https://github.com/symfony/symfony/commit/fadb5ae05dfcfed74f3c3b4e2994ad681f21a210

**Comment by craigh** [comment]
thanks for fixing this 👍
