### ISSUE TITLE
A not so-obvious error message when messing up with controllers

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#21969]
Given

```php
class Actions
{
    /**
     * @Cfg\Route("/", name="home")
     */
    protected function home(): Response
    {
        return $this->render('index.html');
    }
}
```

I get `The controller for URI "/" is not callable. Method "home" on class "SymfonyProxy_f6aad6c251e61ad4ae1fc5a561578cae" should be public and non-abstract.`.

That's normal as my method should be public, not protected. But the error message is not so obvious. Developers don't care about the intermediate proxy.

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
the error message should check for the InheritanceProxyInterface and use the parent class when applicable
