### ISSUE TITLE
Missing priority for events in doctrine bridge

### ISSUE THREAD

**Issue by chapterjason** [symfony/symfony#21977]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

I just have two listeners and they have to be in the correct order. My first approach was to set the priority in the `tags` for the listeners, I noticed that nothing changed the order. After I checked the code in [Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L101](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L101) and compared it to [Symfony/Component/Form/FormConfigBuilderInterface.php#L33](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormConfigBuilderInterface.php#L33) I just realized that the priority is missing.

Yeah I know that Component/Form and the Bridge/Doctrine are two different parts.

**Comment by javiereguiluz** [comment]
You are right: we allow to define priorities everywhere ... so I guess it should be OK to add priorities here too. 👍  from me!

**Comment by wouterj** [comment]
Doctrine is using it's own EventManager: https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/EventManager.php This one doesn't have the priority feature, so it's not something we can add in Symfony. It should first be added in the Doctrine EventManager.

**Comment by javiereguiluz** [comment]
@chapterjason after @wouterj's comment, I'm afraid we need to close this as "can't fix" because it depends on Doctrine project. If you still want this feature, please open an issue in https://github.com/doctrine/common/issues

Thanks!

**Comment by dmaicher** [comment]
Aren't the listeners and subscribers already registered in the correct order when specifying priorities on the tag?

https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L67

**Comment by chapterjason** [comment]
Thank you @dmaicher I found out that [https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L91](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L91) does not take care of priorities what makes no sense cause the priorities will sorted later in [https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L95](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L95) 

My prove:
I changed the lines to following
```
            var_dump(json_encode($taggedListeners));
            $listenersPerCon = $this->groupByConnection($taggedListeners, true);
            var_dump(json_encode($listenersPerCon));
```

My result:
```
Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterEventListenersAndSubscribersPass.php:92:
{
   "my.listener1":[
      {
         "event":"prePersist"
      },
      {
         "event":"preUpdate",
         "priority":50
      }
   ],
   "my.listener2":[
      {
         "event":"postPersist"
      },
      {
         "event":"preUpdate",
         "priority":100
      },
      {
         "event":"preRemove"
      },
      {
         "event":"postFlush"
      }
   ]
}

Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterEventListenersAndSubscribersPass.php:94:
{
   "default":{
      "my.listener1":{
         "event":[
            "prePersist",
            "preUpdate"
         ]
      },
      "my.listener2":{
         "event":[
            "postPersist",
            "preUpdate",
            "preRemove",
            "postFlush"
         ]
      }
   }
}
```

**Comment by dmaicher** [comment]
@javiereguiluz we have to re-open this unfortunately :cry: I double checked and there is indeed something broken with handling the priorities.

This only ever worked correctly if there is exactly one tag per service as otherwise the priorities are lost.

**Comment by dmaicher** [comment]
@chapterjason I proposed a fix here: https://github.com/symfony/symfony/pull/22001
Maybe you can try it with my changes?
