### ISSUE TITLE
[PhpUnitBridge] vendor weak mode fails

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#21980]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0 (master — 40d133c)

https://github.com/symfony/symfony/pull/21539 results in an error on my end after upgrading `symfony/symfony` to `^3.3.@dev`.

```
PHP Fatal error:  Uncaught uasort() expects parameter 1 to be array, null given

/path/to/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:109
/path/to/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:219

  thrown in /path/to/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php on line 219

Fatal error: Uncaught uasort() expects parameter 1 to be array, null given
```

From what I see the error seems to come from https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L88 where it should be:

```php
$deprecations = array(
            'unsilencedCount' => 0,
            'remainingCount' => 0,
            'remaining vendorCount' => 0,  // this one is missing although doesn't cause an error
            'legacyCount' => 0,
            'otherCount' => 0,
            'unsilenced' => array(),
            'remaining' => array(),
            'remaining vendor' => array(), // this is the missing bit causing an error
            'legacy' => array(),
            'other' => array(),
        );
```

PhpUnit config:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.6/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="app/autoload.php"
         stopOnFailure="true"
         verbose="true"
>
    <php>
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak_vendors" />
    </php>

   <!-- ... -->
</phpunit>
```

/cc @greg0ire

**Comment by greg0ire** [comment]
Both entries are supposed to be added just below : https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L100 Can you please debug that part ?

**Comment by theofidry** [comment]
Indeed I didn't see it.

There is two things:

- the mode is not resolved yet when you are doing that check. The mode is resolved by `$getMode` which will be used [there](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L104)
- `DeprecationErrorHandler::register()` is called, `SYMFONY_DEPRECATIONS_HELPER` is not set yet (but `$getEnv` returns `'weak_vendors'` later when a deprecation is fired)

**Comment by greg0ire** [comment]
Not sure why, but I don't reproduce this bug… what do you reckon should be done ?

1. add the 2 entries unconditionally?
2. add them conditionally, but somewhere else?
3. resolve the mode earlier?

**Comment by greg0ire** [comment]
To be honest, I don't even understand what you mean by resolved… when I try the function, it does add the two entries in my case. `$mode` is set as expected.

**Comment by greg0ire** [comment]
You said you are upgrading `symfony/symfony`, but the error is thrown in `symfony/phpunit-bridge`… could it be that you have both package, and some twisted autoloading problem is happening here? If yes, how is it even possible to install both packages together?

EDIT: I see that [the symfony package on packagist](https://packagist.org/packages/symfony/symfony) does not replace `symfony/phpunit-bridge`. Is that normal?

**Comment by theofidry** [comment]
>Not sure why, but I don't reproduce this bug… what do you reckon should be done ?
>
>add the 2 entries unconditionally?
>add them conditionally, but somewhere else?
>resolve the mode earlier?

Add the 2 entries unconditionally, we don't really care.

>To be honest, I don't even understand what you mean by resolved

I mean that the `$mode` passed during `DeprecationErrorHandler::register()` is `false` in my case, but the mode returned by `$getMode` is `weak_vendors`.

**Comment by theofidry** [comment]
demo [here](https://github.com/theofidry/phpunitbridge-demo1)

**Comment by greg0ire** [comment]
You have both `symfony/symfony` and `symfony/phpunit-bridge`… does it make sense?

**Comment by greg0ire** [comment]
The issue goes away when using an environment variable : `SYMFONY_DEPRECATIONS_HELPER=weak_vendors vendor/bin/simple-phpunit`.

**Comment by theofidry** [comment]
Well, I just installed the app with the Symfony installer :)

I don't think it's a problem, but in your case I think you get the right
mode because you declare the environment variable. In mine its objected by
PhpUnit which happens later (after the error handler registration).

**Comment by greg0ire** [comment]
So… you found a bug in simple-phpunit?
