### ISSUE TITLE
Authentication with a second manager

### ISSUE THREAD

**Issue by strauss69400** [symfony/symfony#21987]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4

I created a second manager for my second database. In this base, i create a table which it contains my players. The problem is the symfony don't load users from this database.
Fosuserbundle allows me to connect on the administration and my custom bundle with the second base allows players to connect on the frontend

here is an extract of my config.yml :

    `doctrine:
    dbal:
    default_connection: default
    connections:
        default:
            driver:   pdo_mysql
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
        seconddb:
            driver:   pdo_mysql
            host:     "xx.xx.xx.xx"
            port:     "3306"
            dbname:   "acme_test"
            user:     "acmegamestest"
            password: "mypassword"
            charset:  UTF8

    orm:
    default_entity_manager: default
    auto_generate_proxy_classes: "%kernel.debug%"
    #naming_strategy: doctrine.orm.naming_strategy.underscore
    entity_managers:
        default:      
           connection: default 
           mappings:
                acmeAdminBundle: ~
                acmeBlogBundle: ~
                gedmo_translatable:
                   type: annotation
                   alias: GedmoTranslatable
                   prefix: Gedmo\Translatable\Entity
                   is_bundle: false
                   # make sure vendor library location is correct
                   dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
        seconddb:
           connection: seconddb
           mappings:
               acmeJoueurBundle: ~ `

and here is an extract of my security.yml :

    `encoders:
    FOS\UserBundle\Model\UserInterface: sha512
    Acme\JoueurBundle\Entity\Players:
        algorithm: sha512
        encode_as_base64: false

    providers:
        seconddb:
            entity:
                class: Acme\JoueurBundle\Entity\Players
                property: username    
                manager_name: seconddb
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        administration:
            pattern: ^/admin
            provider: fos_userbundle
            context: administration
            form_login:
                #csrf_provider: security.csrf.token_manager
                login_path : fos_user_security_login
                check_path : fos_user_security_check
                failure_path : null
                default_target_path : /admin                
            logout:       
              path : fos_user_security_logout
              target : /connexion
            anonymous: true    
        frontend:
            pattern: ^/
            provider: acme_joueurbundle
            context: frontend
            form_login:
                #csrf_provider: form.csrf_provider
                login_path : acme_players_login
                check_path : acme_players_check
               failure_path : null
                default_target_path : acme_players_userprofile                      
            logout:       
              path : acme_players_logout
              target : acme_players_login
            anonymous:    true`

and my entity implements "AdvancedUserInterface, \Serializable" with this function :
    
    `public function getRoles()
    {
        return array('ROLE_PLAYERS');
     }

    public function getSalt(){

       return $this->salt;
    }

    public function eraseCredentials(){

    }

    public function isAccountNonExpired()
    {
         return true;
    }

    public function isCredentialsNonExpired()
    {
         return true;
    }

    public function isAccountNonLocked()
    {

        return !$this->banned;
    }

    public function isEnabled()
    {
        return $this->active;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->active

        ));
     }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
     {
        list (
           $this->id,
           $this->username,
           $this->password,
           $this->active
        ) = unserialize($serialized);
     }`

However when i trying to connect, i get this errors in dump function :

![lclho](https://cloud.githubusercontent.com/assets/8798254/23852281/47adc20c-07e7-11e7-94f5-fe3ac6342bbc.png)

and in the section Doctrine i get this :
![1epbo](https://cloud.githubusercontent.com/assets/8798254/23852290/4fc3fd30-07e7-11e7-8d2c-64d67ac355f7.png)

Is what you know the solution? Hope you can help me. Thanks

**Comment by xabbuh** [comment]
Looks like you forgot the contents of your `security.yml` file.

**Comment by strauss69400** [comment]
yes :) i updating my issue.thanks

**Comment by xabbuh** [comment]
What steps did you perform to end up with this dump? As which user did you authenticate? What does your `PlayersController` do around line 44?

**Comment by strauss69400** [comment]
the line 44 is the inside of  the loginAction which i launched the dump!!

    `    public function LoginAction(Request $request){
    	
        /** @var $session \Symfony\Component\HttpFoundation\Session\Session */
        $session = $request->getSession();

        $authErrorKey = Security::AUTHENTICATION_ERROR;
        $lastUsernameKey = Security::LAST_USERNAME;

        // get the error if any (works with forward and redirect -- see below)
        if ($request->attributes->has($authErrorKey)) {
            $error = $request->attributes->get($authErrorKey);
        } elseif (null !== $session && $session->has($authErrorKey)) {
            $error = $session->get($authErrorKey);
            $session->remove($authErrorKey);
        } else {
            $error = null;
        }

        if (!$error instanceof AuthenticationException) {
            $error = null; // The value does not come from the security component.
        }

        dump($error);

        // last username entered by the user
        $lastUsername = (null === $session) ? '' : $session->get($lastUsernameKey);

        $csrfToken = $this->has('security.csrf.token_manager')
            ? $this->get('security.csrf.token_manager')->getToken('authenticate')->getValue()
            : null;
    	
		 return $this->render('AcmeJoueurBundle:Players:login.html.twig',array(
		 		'last_username' => $lastUsername,
            	'error'         => $error,
		 		'csrf_token' => $csrfToken,
		 ));
	}`

**Comment by xabbuh** [comment]
How do your configurations for the `acme_players_*` routes look like? Can you please show the log excerpt for the failing request?

**Comment by strauss69400** [comment]
yes, here is my routes for players connection.

    `kiyoi_players_logout:
         path : /{_locale}/logout
        defaults: { _controller : KiyoiJoueurBundle:Players:logout,_locale:%locale% }
     
    acme_players_login:
       path:     /{_locale}/loginplayers/
       defaults: { _controller: acmeJoueurBundle:Players:login,_locale: %locale% }
       requirements:
          _locale: %langSiteRequirement%
       
    acme_players_check:
        path:     /loginplayers-check/
        defaults: { _controller: acmeJoueurBundle:Players:logincheck,_locale: %locale% }` 

and here log exception from the toolbar symfony 

![image](https://cloud.githubusercontent.com/assets/8798254/23859527/25641da0-0804-11e7-841c-4da33205d064.png)

**Comment by xabbuh** [comment]
Please show the full debug log, not only infos and errors.

**Comment by strauss69400** [comment]
the list is too long, there is 68 line.There is nothing special !! only the events that are launched and sql requests!!

**Comment by xabbuh** [comment]
Alternatively, you can fork the Symfony Standard Edition and make changes that are necessary to reproduce your issue. One can then checkout your fork locally and try to investigate the cause for your issue.

**Comment by strauss69400** [comment]
i found the problem!!!in Methods serialize and unseralize of my entity Players, i add $this->salt!!
thanks for your help
