### ISSUE TITLE
[Session] MockArraySessionStorage: clear(): error when no bags

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#21990]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7+

https://github.com/symfony/http-foundation/blob/2.7/Session/Storage/MockArraySessionStorage.php#L175

`clear()` iterates over list of bags, but… sometimes there are no bags and it results in PHP error:

> Invalid argument supplied for foreach()

How to get that error?

```
$storage = new MockArraySessionStorage();
$storage->clear();
```

I stumbled upon this then I was writing a test to reproduce #7104:

```php
public function testLogout(Client $client)
{
    $client->getKernel()->boot();
    $client->getContainer()->get('session.storage.filesystem')->clear();
    $client->request('GET', '/logout');
```

---

Possible solutions:

* a.) Throw exception instead of having PHP error (message could say what's wrong).
* b.) Return early when `$this->bags` is `null`.
* c.) Always keep `$this->bags` as array (instead of possible `null`).

`b` and `c` could be considered BC if someone relied upon this "not working" (but I'd say the chances are low).

---

After it is decided what to do with this issue, I can create PR with test and implementation.

**Comment by dmaicher** [comment]
Seems bad to me as well the current behaviour. How should I know that I need to add bags first to be able to call clear? :yum: 

I would suggest to just initialize the bag member with an empty array here https://github.com/symfony/http-foundation/blob/2.7/Session/Storage/MockArraySessionStorage.php#L63 ?

**Comment by MacDada** [comment]
> I would suggest to just initialize the bag member with an empty array here https://github.com/symfony/http-foundation/blob/2.7/Session/Storage/MockArraySessionStorage.php#L63 ?

@dmaicher Yep, it is one of solutions I proposed:

> c.) Always keep $this->bags as array (instead of possible null). […] could be considered BC if someone relied upon this "not working" (but I'd say the chances are low).

**Comment by Tobion** [comment]
This seems like a bug indeed and I agree with solution c),
Can you create a PR to initialize the bags property? Thanks

**Comment by MacDada** [comment]
BTW, what is this `tearDown` method for? https://github.com/symfony/http-foundation/blob/2.7/Tests/Session/Storage/MockArraySessionStorageTest.php#L59

AFAIK, all fields all overwritten by PhpUnit on next `setUp` call.

**Comment by MacDada** [comment]
BTW2, do u know how to marry symfony source code + phpunit + phpstorm?

In phpunit settings, if I point to Symfony's vendor autoloader (to autoload Symfony classes), I get "Class 'PHPUnit_TextUI_ResultPrinter' not found" error.

If I point to my global composer vendor autoloader (to autoload phpunit; ~/composer/vendor/autoload.php) I get "Class 'PHPUnit\Framework\TestCase' not found" error.
