### ISSUE TITLE
Security: User provider is mandatory, even if I don't need it.

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#21998]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | maybe
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.5

I use custom authentication which stands on tokens without users. Therefore, I don't use UserProvider. But configuration loader requires me to provide at least one user provider.

Please make user provider optional. When some component asks for user from user provider, it should crash, so I know there is something wrong.

**Comment by Nek-** [comment]
@jkufner 

As I understand it's not a bug but something mandatory that may not be. Right ?

Also it's present in any version of Symfony as it's a "missing feature". Right ?

**Comment by jkufner** [comment]
Well… it's hard to tell. I updated the Q/A table.

It is a bug in a sense that I cannot use authenticator which don't use users, but there is nothing really broken. It is just an unnecessary constraint.

**Comment by robfrawley** [comment]
"There is nothing really broken. It is just an unnecessary constraint." LMFTFY:

| __Q__ | __A__ |
| --- | --- |
| Bug report? | no |
| Feature request? | yes |

**Comment by curry684** [comment]
If this part is being refactored I'd suggest taking it larger, as a lot of Symfony's configuration in this area is pretty outdated in practice. When implementing APIs or external authentication mechanisms I commonly have implementations of UserInterface around that are not about users at all, and have a ton of empty methods around that are not relevant.

The UserProvider/UserInterface subsystem is geared far too much towards the classical user/password website login, and hence also stem 'weirdish' things like the one mentioned here with a UserProvider being mandatory.

**Comment by jkufner** [comment]
Exactly. As far as I understand, there is no need for UserProvider unless AuthenticationListener requires one. When a different paradigm is used for authentication, this entire UserProvider infrastructure is not used at all.

Firewall and AuthenticationListeners are fine and generic enough. Tokens are a bit confusing and there is an unnecessary bound to sessions, but thats for another story. Questionable is the rest of the infrastructure above the AuthenticationListeners. So, let's make UserProviders optional. It would allow us to build a new lighter and simpler infrastructure while keeping the old one in place until the new is ready.
