### ISSUE TITLE
[Form] [DX] Collection of form with delete empty is not clear

### ISSUE THREAD

**Issue by murilolobato** [symfony/symfony#22003]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

[Instructions about delete_empty](http://symfony.com/doc/current/reference/forms/types/collection.html#delete-empty) are partially ok. It instructs only that allow_delete must be enabled.

If you have a collection of another form type, and you want that empty items are deleted, you have to dig around the web (old issues and wrong workarounds), to discover that you just have to set `entry_options => array('required' => false)` at the collection definition.

I've discovered this searching in the issues. And found https://github.com/symfony/symfony/issues/13940 which points to https://github.com/symfony/Form/blob/master/Tests/Extension/Core/Type/CollectionTypeTest.php#L145-166 

I think, we could update the collection doc, in the section of delete_empty, to warn the developers about this behavior. And, why this `entry_options => array('required' => false)` makes sense? In my opinion, i think it is not legible. I'm available to help!

**Comment by murilolobato** [comment]
I have just found, why `required => false` makes sense. http://symfony.com/doc/2.8/reference/forms/types/form.html#empty-data

**Comment by xabbuh** [comment]
@murilolobato Unfortunately, I have to close your issue as this repository is only about the Symfony code. If you feel that the documentation for a feature could be improved, please the dedicated [documentation repository](https://github.com/symfony/symfony-docs) instead. Thank you for understanding.
