### ISSUE TITLE
Prefill form hidden fields with FormEvents 

### ISSUE THREAD

**Issue by raphydev** [symfony/symfony#22009]
How to prefill the value of a cache field with the values of some other fields of the current form before submission of the form, with FormEvents (PRE_SUBMIT and POST_SUBMIT). I read the doc, but I see the fire always? Someone to a solution for me please

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by raphydev** [comment]
Ok, thanks
