### ISSUE TITLE
Translator: WDT collector use last locale page 

### ISSUE THREAD

**Issue by alborq** [symfony/symfony#22004]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.9

Hi. 

When you use translator in dev; WDT calculate Fallback, Defined Message 
BUT 
It do this, with the lastest locale used in page and not a locale use during translation 

Exemple : 
Locale FR : 
{{ 'hi'|trans }} => Say 'Bonjour'
Change locale with `$this->translator->setLocale('en');`
{{ 'hi'|trans }} => Say 'Hi'
Change locale with `$this->translator->setLocale('An Unknow language');`
{{ 'hi'|trans }} => Say 'Hi' //Fallback
Change locale with `$this->translator->setLocale('en');`

WDT Render : You havent fallback message. because it's post analyse. 

Usecase : mass mailing with different language

**Comment by fancyweb** [comment]
@xabbuh This issue was fixed by https://github.com/symfony/symfony/pull/32925,  I tested it, you can close.

**Comment by xabbuh** [comment]
cool :+1: thank you for checking @fancyweb
