### ISSUE TITLE
[Form] delete_empty don't work for embedded forms without data_class

### ISSUE THREAD

**Issue by murilolobato** [symfony/symfony#22008]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.18

I'm creating a form, that has a collection of another form. OrderType has a collection of ItemType. Assuming that both have the option `data_class = null`, empty items are not being removed during form submit. Empty Items are being validated. The expected behavior was that empty items would be removed, as it happens when I create entities for this two types and set them in type's `data_class` options.

Looking at the source code and other issues, people already have had problem with delete_empty, but this is a new case. I've also found the tests to `delete_empty` and the scenario I've listed above is not being tested.

Here is the test with data_class defined: https://github.com/symfony/Form/blob/master/Tests/Extension/Core/Type/CollectionTypeTest.php#L145

I'll try to create a test, and attach to this issue, but I can't promise anything.

**Comment by murilolobato** [comment]
Maybe @peterrehm or @cordoval could help, as they're involved at the creation of delete_empty.

**Comment by yceruto** [comment]
@murilolobato if `allow_delete` is `false` then `delete_empty` does not work ( see test https://github.com/murilolobato/symfony/blob/ede90e8957195a15223fd5d689b4198801852a56/src/Symfony/Component/Form/Tests/Extension/Core/Type/CollectionTypeTest.php#L142)

Cound you try with `'allow_delete' => true` also?

**Comment by murilolobato** [comment]
@yceruto I've updated the pull request, now with the allow_delete to my test. It still fails, I already knew that it would fail too, beacuse in my real app I've made a bunch of tests and tentatives.

And you touched a nice poin, because the test I wrote is a copy from the test above, and in that test there is no allow_delete, but works...

**Comment by yceruto** [comment]
Well, I see that, still with `'allow_delete' => false` if it's a new element, then, it should be removed 👍

**Comment by HeahDude** [comment]
Maybe related to https://github.com/symfony/symfony/issues/13601? @murilolobato could the approach of https://github.com/symfony/symfony/pull/20496 solve your problem?

**Comment by murilolobato** [comment]
In #13601, I think that the functionality proposed by @Koc is not needed in that usecase. But maybe, this functionality could help me, because I would teach to the form how to determine if a item is empty, and if it is empty it would be removed from the collection and everything would work, in theory.

The question that @yceruto made in the pull request is very convenient too, it is worth to take a look.

**Comment by murilolobato** [comment]
Closing in favor of #13601
