### ISSUE TITLE
[DI] YamlFileLoader unclear exception message when file can not be found

### ISSUE THREAD

**Issue by slootjes** [symfony/symfony#22007]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.0

https://github.com/symfony/symfony/blob/v2.8.0/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L347

When a file does not exist in the file system the exception message "The service file "%s" is not valid." implies that the file contains invalid yml while I think changing it to "The service file "%s" does not exist." would be a lot more clear for the user.

If others agree I would be happy to create a PR for this minor change.

**Comment by javiereguiluz** [comment]
@slootjes I agree. Something like `The file "%s" does not exist.` would be much better 👍
