### ISSUE TITLE
Consider removing allowCustomResponseCode()

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22019]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 3.3

While writing the [New in Symfony 3.3: Deprecated X-Status-Code](http://symfony.com/blog/new-in-symfony-3-3-deprecated-x-status-code) blog post, I wondered why we need `allowCustomResponseCode()`. Let me show some code:

**This is what we have in Symfony 3.2**

```php
$exception = $event->getException();
$response = new Response('...', 500, ['X-Status-Code' => 404]);
$event->setResponse($response);
```

**This is the solution proposed by Symfony 3.3**

```php
$exception = $event->getException();
$response = new Response('...', 404);
$event->allowCustomResponseCode();
$event->setResponse($response);
```

**This is what I want**

```php
$exception = $event->getException();
$response = new Response('...', 404);
$event->setResponse($response);
```

---

Removing `X-Status-Code` is great and help us reduce the "cognitive load" required to use Symfony ... but all those gains are lost when introducing `allowCustomResponseCode()`.

**Comment by fabpot** [comment]
It's there for a reason. Have a look at Silex for a good example of its usage. Basically, Symfony overrides the status code when there is an exception, but sometimes, we need another one. It's very rare. And by the way, I would not even talk about that on the blog post as end users should never use that.

**Comment by javiereguiluz** [comment]
Do you mean that users don't have to use `allowCustomResponseCode()` or the entire status code overriding feature?

**Comment by fabpot** [comment]
The entire status code overriding feature (that's useful in very specific cases, we only have one example in Silex).

**Comment by javiereguiluz** [comment]
OK. Let's close this then as "won't fix". I've opened https://github.com/symfony/symfony-docs/pull/7640 to remove any reference to `X-Status-Code` in the docs. Thanks!
