### ISSUE TITLE
[Dotenv] Component Documentation Link Broken

### ISSUE THREAD

**Issue by bitdagger** [symfony/symfony#22025]
The documentation link for the [DotEnv component](https://github.com/symfony/dotenv) currently 404s

The current link given is: https://symfony.com/doc/current/components/dotenv/index.html

**Comment by Nek-** [comment]
Hello @bitdagger 

Thank you very much for reporting this issue but it's related to https://github.com/symfony/symfony-docs . Can you report the issue on the related repository and close this issue ?

Thank you :) .

**Comment by bitdagger** [comment]
Found the relevant issue there: https://github.com/symfony/symfony-docs/issues/7526

Thanks!
