### ISSUE TITLE
Symfony console breaks on certain terminal width when displaying an exception

### ISSUE THREAD

**Issue by mjrider** [symfony/symfony#22021]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Symfony version  | v3.2.6

When displaying an exception, symfony console produces the following error
The example breaks on my machine when my terminal is between 72 and 134 columns
Repository with a minimal reproduction is available on: https://github.com/mjrider/break-symfony-console
```
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: Incorrectly nested style tag found. in /tmp/example-minimum/vendor/symfony/symfony/src/Symfony/Component/Console/Formatter/OutputFormatterStyleStack.php:87
Stack trace:
#0 /tmp/example-minimum/vendor/symfony/symfony/src/Symfony/Component/Console/Formatter/OutputFormatter.php(185): Symfony\Component\Console\Formatter\OutputFormatterStyleStack->pop(Object(Symfony\Component\Console\Formatter\OutputFormatterStyle))
#1 /tmp/example-minimum/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(653): Symfony\Component\Console\Formatter\OutputFormatter->format('<error>   => '1...')
#2 /tmp/example-minimum/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(Exception), Object(Symfony\Component\Console\Output\StreamOutput))
#3 /tmp/example-minimum/test.php(17): Symfony\Component\Console\Application->run()
#4 {main}
  thrown in /tmp/example-minimum/vendor/symfony/symfony/src/Symfony/Component/Console/Formatter/OutputFormatterStyleStack.php on line 87
```

OS information: Linux Mint 18.1
```
$ php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

```

**Comment by mjrider** [comment]
some more input:
3 runs, with different coll sizes, please note the
- failure on cols 130
- the broken `</info>` tag on 140 and 135 cols

![screenshot at 2017-03-16 14-38-48](https://cloud.githubusercontent.com/assets/213105/23998851/bc115d22-0a56-11e7-8794-4a73126586ba.png)

**Comment by jordscream** [comment]
@mjrider . I confirm a problem with the OutpoutFormatter. Try to push a PR as soon

**Comment by chalasr** [comment]
It's the first time I see style added on an exception message, that feels wrong to me. I might be wrong but to me exception messages should be raw text.
I would use a `block()` (e.g. `SymfonyStyle::warning()`, `::error()`) and return an error code instead of throwing. But if you really want an exception, I think you should look at overriding `Application::renderException()` rather than tweaking the message.

**Comment by mjrider** [comment]
@chalasr it doesn't matter why there is styling in the exception message, Symfony breaks internally when trying to render an exception with formatting, so the options are:

- `renderException` ignores styling, and outputs styling tags as text
- `renderException` detects styling, and doesn't split lines in a way that the formatter breaks

both options have in common that Symfony should never break regardless what the user gives as input

Unrelated: because Symfony generates an exception while handling the exception the original message gets lost, which is also very bad

**Comment by mjrider** [comment]
@jordscream any progress on the PR? Can i help in ?

**Comment by stof** [comment]
Are you putting CLI formatting inside the exception message itself ?

**Comment by jordscream** [comment]
@stof , he tries to do 
`
$str = "<comment>Please configure New Relic:</comment> <info>set('newrelic', array('api_key' => 'xad3...', 'application_id' => '12873'));</info>";
	      throw new \Exception($str);
`
With a certain terminal width , the output formatter styleStack breaks.

It cuts like this with a certain width:

`
first line: <error><comment>Please configure New Relic:</comment> <info>set('newrelic'</error>
second line: <error>', array('api_key' => 'xad3...', 'application_id' => '12873'));</info></error>
`
the '<info> </info>' is splitted on each line. So for the first line treatment, when he interprets the last node </error>, it flushes <info> in the styleStack cause it finishes the line

Is it a bug, or should we prevent not to put CLI formatting inside the exception ?

**Comment by stof** [comment]
We should IMO prevent putting formatting there (considering it as plain text) IMO. Allowing formatting in them would be a nightmare, given that Symfony itself applies some formatting when rendering the exception.

**Comment by jordscream** [comment]
@stof , Can we propose a cleaning message development to prevent the disfonctionment ? (When a user does it, it displays nothing and in the code it crashes the parser...) or let we it like this ?

**Comment by mjrider** [comment]
@jordscream like said in https://github.com/symfony/symfony/issues/22021#issuecomment-287313312 
Symfony should not throw an exception, and 'forget' the original exception.

We are here in an critical path, being an exception it could contain any message, what would happen if it was an exception from a dom parser which html5 tags  like <comment> or <info> inside. breaking on that kind of output defeats the whole purpose of adding an Exception handler.

i would vote for handling the message as if it was plain text, and not formatted text

**Comment by santilin** [comment]
I have another use case to avoid splitting lines at the console width, and is when there is a path in the otuput and I want to be able to click on in on my favourite IDE so I want it to be kept in one line

    In Parser.php line 128:
                                                                               
      Couldn't parse test '/home/santilin/devel/yii2base/apps/biosegura.api/tests  
      /unit/models/ModelPedidoSemanasTest.php' on line 14                          
      syntax error, unexpected 'class' (T_CLASS)                                   

With the current behaviour, the path of the failing file is split and I can not click on it to open it.
