### ISSUE TITLE
HEAD method implementations are ignored

### ISSUE THREAD

**Issue by alinn** [symfony/symfony#22028]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | >2.3

Is there any reason this (snippet below) exists? the rfc does not require implementations to be identical, but that the responses be equivalent.

```php
            // check HTTP method requirement
            if ($requiredMethods = $route->getMethods()) {
                // HEAD and GET are equivalent as per RFC
                if ('HEAD' === $method = $this->context->getMethod()) {
                    $method = 'GET';
                }
                if (!in_array($method, $requiredMethods)) {
                    $this->allow = array_merge($this->allow, $requiredMethods);
                    continue;
                }
            }
```

Worse, in 2.3, what i am currently using (could be it's the same in higher versions), the router debug will actually not take this into consideration and report that the routing works as per the user routing definition

There could be valid reasons to not want to execute the same code for GET and HEAD - f.e. avoid expensive hydration in exploratory HEAD calls. 

If the Content-Length defined in 14.13 is a factor here, that is expressed with SHOULD, not MUST, so no reason to impose this on the user.

**Comment by xabbuh** [comment]
see #20893 and #21074

**Comment by javiereguiluz** [comment]
Closing it as duplicated of #21074.

@alinn although what you said is true, there are other strong reasons to not change this behavior ... and popular apps such as Varnish do the same.

**Comment by alinn** [comment]
@javiereguiluz @xabbuh thank you for finding the duplicates (i was only searching open tickets) Even though i don't agree with having this in a framework, i understand there are reasons to keep it. What about the router debug? is that showing the right stuff in > 2.3 ?

**Comment by drastik** [comment]
This is causing an issue with a TUS implementation.

TUS uses a `HEAD` request when resuming an upload to get the current status.
Through Drupal 8 (and thereby Symfony 2), I am routing to a Controller that calls the TUS server.
On the `HEAD` request, it is rewriting to a `GET` and causing a completely different response, and breaking the integration entirely.

https://tus.io/protocols/resumable-upload.html#head

**Comment by eli-sta** [comment]
I think the only problem here is when we want to provide hot-link via email and some bots can fetch that link using 'HEAD' method.
It's often in Microsoft outlook.com system.

As an Example:
@Route({"en": "/{code}/verify/{transaction}/{token}"},
     *     requirements={"code": "^[a-zA-Z0-9\-_]{1,32}$", "transaction": "^[0-9]{1,12}$", "token": "^[a-f0-9]{6}$"},
     *     name="_transaction_verification",
     *     methods={"GET", "POST"})

this route bypassing 'HEAD' method and activates the link.

My workaround is to check method type and ignore if it's 'HEAD'.

**Comment by UBERPHP** [comment]
I think the only problem here is when we want to provide hot-link via email and some bots can fetch that link using 'HEAD' method.
It's often in Microsoft outlook.com system.

As an Example:
@Route({"en": "/{code}/verify/{transaction}/{token}"},
     *     requirements={"code": "^[a-zA-Z0-9\-_]{1,32}$", "transaction": "^[0-9]{1,12}$", "token": "^[a-f0-9]{6}$"},
     *     name="_transaction_verification",
     *     methods={"GET", "POST"})

this route bypasses request 'HEAD' method to the controller method (and in my case activates subscription, which is not what my customer wants).

My workaround is to check the request method type and ignore if it's 'HEAD'.
