### ISSUE TITLE
Workflow Component: support Value Objects to be used as Marking Store

### ISSUE THREAD

**Issue by validaide-mark-bijl** [symfony/symfony#22031]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.6

Hi everyone,
First of all, let me say that I am a big fan of Symfony and enjoy the new functionality introduced in Symfony 3.x, such as the Workflow Component, a great help!

I wanted to request a feature on the Workflow Component to support the use of ValueObjects for the marking store. I am a big fan of using ValueObjects to restrict the usage of otherwise potentially 'generic' properties. For example, I have the following YML:

```yml
framework:
  workflows:
    my_workflow:
      type: 'state_machine'
      supports:
        - AppBundle\Entity\MyEntity
      marking_store:
        type: 'single_state'
        arguments:
          - 'status'
```

The usage of the 'status' elsewhere in the application is guarded by the ValueObject MyStatus:

```php
class MyStatus
{
 const STATUS_NEW = 'new';
 const STATUS_OTHER = 'other';

 /** @var string **/
 protected $status;

 public function __construct(string $status) {
  if(!in_array($status,self::getStatuses()) {
   throw new InvalidArgumentException();
  }
  $this->status = $status;
 }

 public function __toString()
 {
  return $this->status;
 }

 public function getStatuses()
 {
  return [
   self::STATUS_NEW,
   self::STATUS_OTHER
  ];
 }
}
```
This is then used in the MyEntity class:

```php
...
/**
 * @var MyStatus
 */
protected $status;
...
public function __construct()
{
 $this->status = new MyStatus(MyStatus::NEW);
}
...
```

Currently, I get the following error when I try using a ValueObject:
```
ContextErrorException: Warning: Illegal offset type
```
Thrown in the SingleStateMarkingStore at line 52:
```php
return new Marking(array($placeName => 1));
```
Could support for ValueObjects be realized by potentially doing a string cast?
```php
return new Marking(array((string)$placeName => 1));
```

I hope I made my case clear and I'm not overlooking anything here that might indicate my feature request to be a non-issue or already available.

Thanks in advance,
Kind regards,
Mark

**Comment by lyrixx** [comment]
Hello Mark.

We could think it's safe to add this but we would add to fix also the `MultipleStateMarkingStore`. And in this case it would be a bit harder and not very natural.

In place, I suggest you to implement your own `StatusMarkingStore`. It will be much simpler than the `SingleStateMarkingStore` because you already know the property name so you can directly use the accessor.

```php
use Symfony\Component\Workflow\Marking;
use Symfony\Component\Workflow\MarkingStore\MarkingStoreInterface;

class SingleStateMarkingStore implements MarkingStoreInterface
{
    public function getMarking($subject)
    {
        $placeName = $subject->getStatus();

        if (!$placeName) {
            return new Marking();
        }

        return new Marking(array((string) $placeName => 1));
    }

    public function setMarking($subject, Marking $marking)
    {
        $subject->setStatus(new Status(key($marking->getPlaces())));
    }
}
```

Then, you will have to register this marking store as a service, and use the id in the workflow. configuration

---

If you are not agree with that, don't hesitate to reopen the issue.

**Comment by danaki** [comment]
Having the same issue but using popular PhpEnum.

**Comment by danaki** [comment]
@lyrixx excuse me, I searched thru the sources and can't find how do I "use the id in the workflow. configuration". Can you give an example?

**Comment by danaki** [comment]
Guys, should I create a new issue or the owner can reopen this?

**Comment by stof** [comment]
```yaml
framework:
    workflows:
        my_workflow:
            # ...
            marking_store:
                service: my_custom_marking_store
```

**Comment by danaki** [comment]
@stof thank you, custom service did the trick
