### ISSUE TITLE
[FrameworkBundle] Clear cache pools

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#22047]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0 (master)

~~Here is what you get when you try to clear the cache pools without any argument:~~

```
$ bin/console cache:pool:clear

[OK] Cache was successfully cleared.
```

~~Which is completely false: you didn't clear anything. An example of output when it works:~~

```
$ bin/console cache:pool:clear cache.app

 // Clearing cache pool: cache.app

 [OK] Cache was successfully cleared.
```

~~I think a more intuitive behaviour, to be consistent with other commands, is that when no argument is passed all the pools are cleared.~~

EDIT: the part above has been dealt with #22159.

 [Actually I can see that I wasn't the only one thinking about this](https://github.com/symfony/symfony/pull/19891#r78667780), but has been dismissed as dimmed too dangerous. I would like to argue for this still:

- First it's plain annoying without it if you really want to clear everything: you have to check the config to list the existing pools, and add the complete list manually, then synchronize it later. Alternatively, you can find a smarter way to retrieve the list, but in any case, it requires a bit of tickling on the user end.
- It is dangerous yes, but not more than a regular `cache:clear`...
- If we really want to avoid mistakes, we should have a prompt command, like for migrations or schema update. As I believe `cache:clear` and `cache:pool:clear` calls can be fairly common in dev, maybe we could not prompt that when the environment is `prod`

Regardless of this discussion, I think the current message is misleading and should be change to something along the lines:

```
$ bin/console cache:pool:clear

[WARNING]: no pool to clear found.

[OK] Cache was successfully cleared.
```

**Comment by ro0NL** [comment]
@theofidry bugfix is merged. Output in 3.2 is currently 

```
[Symfony\Component\Console\Exception\RuntimeException]  
Not enough arguments (missing: "pools").  
```

I think it's good as is; we dont really have a list of all pool id's AFAIK, and im not sure it's worth tracking those for this need.

Note that `cache:clear` by default only clears `cache.default_clearer`.

**Comment by theofidry** [comment]
Thanks for #22159 :)

> we dont really have a list of all pool id's AFAIK, and im not sure it's worth tracking those for this need.

I'm still a bit bothered by not being able to easily clear _all_ the cache pools. Would a `--all` option or something be really too much?

But well if I'm the only one, I'll go with a workaround on my side... I'm letting this issue for a bit longer but if there is no more interest in this then I'll close it :)

**Comment by nicolas-grekas** [comment]
Or submit a PR?

**Comment by theofidry** [comment]
>Or submit a PR?

If there is an interest there (i.e. we want that in the core), then yes I will do a PR rather than my in-house solution :)

**Comment by ro0NL** [comment]
> I'm still a bit bothered by not being able to easily clear all the cache pools.

For now `cache:clear` kinda does that.. but im not sure why `default_clearer` is tagged as `kernel.cache_clearer`, tagging `global_clearer` seems to make more sense.

We should also define what includes _all_ pools/clearers. As the `cache:pool:clear` command lets you clear any `CacheItemPoolInterface|Psr6CacheClearer` service :)

**Comment by nicolas-grekas** [comment]
I would have to issue with a `--all` option btw

**Comment by nicolas-grekas** [comment]
Implementer needed, or let's close...

**Comment by theofidry** [comment]
It's in my Todo list, I just didn't find much time for OSS lately :)

**Comment by Tobion** [comment]
Closing. Feel free to still create a PR.
