### ISSUE TITLE
Segmentation fault after FatalErrorException

### ISSUE THREAD

**Issue by hcomnetworkers** [symfony/symfony#22069]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x-dev
| PHP version | 5.5.9 and 7.1.3
| Apache2 version | 2.4.7 and 2.4.25
| Xdebug version | 2.4.0
| OS | Ubuntu 14.04 LTS

Reproducable using the symfony-standard-master by calling a method on a null object, like in e.g. a controller action:
```
$null = null;
$foo = $null->get();
```

This results in a segmentation fault and not the expected rendering of the error page. While debugging with xdebug the segmentation fault appears in the [ArgumentResolver::getArguments](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php#L46) method after the FatalErrorException was correctly created and the [ExceptionController:showAction](https://github.com/symfony/twig-bundle/blob/master/Controller/ExceptionController.php#L56) is to be called.
The segmentation fault causes Apache to return an ERR_EMPTY_RESPONSE instead of any call stack.

**Comment by xabbuh** [comment]
Not sure if we can do anything about this in Symfony as a segmentation fault usually is an issue of the PHP interpreter.

ping @nicolas-grekas @jpauli

**Comment by jpauli** [comment]
Could you detail and try to provide a small reproducer please ?
The code you link doesn't crash to me.
Also, do not activate Xdebug (do not load it at all) while reproducing.

**Comment by hcomnetworkers** [comment]
We have tried and reproduce the problem also on other servers, not having xdebug installed at all.

However, the problem does not occur on a Ubuntu 16 machine. So for now we will upgrade our dev environments to Ubuntu 16.
