### ISSUE TITLE
[RFC] Command to remove non-production files

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#22064]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | latest

I would like to propose a new feature that can be bundled with Symfony: A command that can remove files that you don't need in production. There have been several suggestions in the past to not include things like tests when developing:
 - #5674
 - #11810
 - #16174
 - #20057
 - There are probably more..

I envision this as a command that people can add to their composer.json to remove:
 - Test files/directories
- Docs (including images)
 - md files (readme, upgrade, etc), might have to be optional

> This should definitely not be removing source files like Tree Shaking! You can narrow your dependencies for that to specific components/bundles.

Several use-cases could be satisfied by this:
 - Reducing the effective size of the application when using a buildserver or bundling Symfony in a desktop app /cc @jrobeson 
 - A clean environment when developing, no mocks or test files in auto-completion
 - No readme files, examples or upgrade logs/contribution logs showing up in search results (hence this step might have to be optional).

**Comment by javiereguiluz** [comment]
I like this idea ... but I don't like how specific the proposed command is. Instead of `production:remove-files` command, I'd create a `production:prepare` command. The tasks that this command could do are:

* "Compile" the application: warm-up and generate everything that has to be generated to run the Symfony app. And do that in a directory-independent manner, so we can prepare the app in one dir and then make the switch to another dir and start serving requests right away.
* "Optimize" the application: the most obvious thing would be to remove all the useless files as suggested by @iltar. In the future, it could be more "intelligent" and do other safe optimizations.
* etc.

All these tasks could be enabled/disabled via console options.

**Comment by iltar** [comment]
Regardless of details, this would open up other possibilities:
 - a way of building your application (possibly with custom scripts)
 - a way of adding sanity checks (like are _all_ my paths relative, including in vendor)
 - a way of possibly even deploying your application to a server (possibly with custom scripts)

I know that this most likely won't be an advisable way of deployment for bigger companies or companies that have multiple people working on applications. Though, this could be fixed with custom build scripts. However, this could make deployments conceptually a lot easier for people that have no fancy deployment tools or server. Think of:
 - Deployment scripts for shared hosting, which a hosting provider could provide to customers (my situation)
 - Deployment scripts that could be shared via github for example
 - Integration with existing deployment tools

**Comment by javiereguiluz** [comment]
I'd say that anything related to deployment is a no-go for being too complex and too hard to do it right for a large enough number of use cases.

**Comment by craigh** [comment]
I like this idea.

**Comment by rvanlaak** [comment]
Would be great if Composer could handle removing all these files when `--prefer-dist` is passed.

**Comment by steevanb** [comment]
To me, that's not Symfony purpose, it's deploy script purpose.

**Comment by iltar** [comment]
Just encountered this DX issue:

![image](https://user-images.githubusercontent.com/1754678/29556747-1a92ba9c-8727-11e7-9b4c-f711847d53ee.png)

It's still extremely annoying that all Symfony test files are available when develop. Not only does it add a significant amount of classes to auto completion, it also creates confusion as to which class you actually need.

**Comment by Taluu** [comment]
IMO this is related to PHPStorm which is aggressively checking all files...

Or maybe when composer installs stuff, we should exclude non-dev directories. But that would be a job for composer.

**Comment by nicolas-grekas** [comment]
Can't this be handled by the phpstorm plugin?

**Comment by theofidry** [comment]
@iltar if I have to look at the vendor (source & test) code, I need them to be indexed by PHPStorm so excluding them is not a solution. It's more the auto-complete of PHPStorm that needs to be smarter, it's like when I'm starting to type a `$a` for an argument and it suggests me `$argc` first which is obviously wrong. But in any case that is more a PHPStorm issue than Symfony, either in PHPStorm itself or the plugin

**Comment by iltar** [comment]
The issue is _not_ the IDE. This issue is _not_ that the plugin doesn't exclude this. The problem is that Symfony as dependency comes with test files which are 100% irrelevant to development when using Symfony as framework. I don't see how test files are relevant to using the framework.

Was playing around with the `WebTestCase` just now and I already picked the wrong class by accident.

![image](https://user-images.githubusercontent.com/1754678/29560319-f08a9d0e-8731-11e7-8691-082576601d78.png)
 
If you have to look at the tests, look at github or make a clone/checkout of the symfony repository. As developer, you're _only_ interested in the source code, not the tests. The current Developer Experience is that _all_ the test classes show up in my auto complete, simply because they exist in the dist version.

**Comment by theofidry** [comment]
>The problem is that Symfony as dependency comes with test files which are 100% irrelevant to development when using Symfony as framework [...] If you have to look at the tests, look at github or make a clone/checkout of the symfony repository. As developer, you're only interested in the source code, not the tests

I disagree. I often consider tests are part of the documentation: they are helpful to understand how the code works and what is the current behaviour when the source code is not clear enough

**Comment by iltar** [comment]
I highly disagree with that. There's literally 0 cases where I've ever found the tests of a package useful as they have mocked out everything. If you want documentation, the code should usually be sufficient. If you need documentation on how to use something, it should be documented in the docs. If this is not the case, it should be added, rather than cluttering everyone with files they will most likely never need.

Worst case scenario, you can still look it up in the Symfony repository on either github or in your local clone. Could hold a poll to see who think it's not needed to have the files vs those who actually use the files to view how it's used. 

I don't think that the majority of developers should be bothered by a shortcut for the few.

**Comment by nicolas-grekas** [comment]
removing non production files - and removing entries from autocompletion are two totally different issues.
the fact that one implies the other is not an argument that justifies removing production files.
disagreeing is fine, but moving forward is better :)

here, the target of not having tests be proposed while autocompleting is a nice one.
I would even like it when working on Symfony itself. Which is a use case that is not covered by this RFC btw.

On the autocompletion topic, I'm sticking to my pov expressed in #17749: : editorconfig/editorconfig#228 is the correct solution.
Meanwhile, the Symfony phpStorm plugin can help.

**Comment by nicolas-grekas** [comment]
I just submitted as a sugestion to phpStorm:
> When a PHP class or method is tagged `@internal` and `@deprecated`, it is still suggested when using autocompletion.
> If one validate the suggestion, one gets the selected method/class, with a line through (strike), hinting this should not be used.
>
> But why suggest a non-recommended method/class in the first place?
This is rather annoying as many of us make wrong selection by mistake.
>
> It would be great if phpStorm could at least suggest these entries last in the list.
>Even having them removed would be OK for me - or maybe have them suggested only if no other choice exists?
>
>That's definitely something people a struggling with, I hope you might do something to enhance the UX.

**Comment by iltar** [comment]
I believe there's already an issue open (if not multiple) about the internal

**Comment by theofidry** [comment]
editorconfig/editorconfig#228 looks by far the most promising one to me. You could always PHPStorm to try to not put priority in the files found in the `tests` folder for auto-completion but then they will have trouble for when tests are in fancy locations and it's not just `src` & `tests`

**Comment by Haehnchen** [comment]
about autocompletion: just open an issue at [JetBrains](https://youtrack.jetbrains.com/issues/WI). i am also struggling in completion window but not only in Symfony projects.

there are ways to help with the Symfony plugin but a generic solution would be more helpful

**Comment by nicolas-grekas** [comment]
Here is the phpStorm issue if you want to chime in:
https://youtrack.jetbrains.com/issue/WI-37750

**Comment by iltar** [comment]
Closing this issue as it's not a good idea
