### ISSUE TITLE
Uncommitted changes

### ISSUE THREAD

**Issue by talorlik** [symfony/symfony#22068]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

My environment is as follows:
Ubuntu 16.04
PHP 7.1.1

When running composer install in Laravel5.4 I get an error symfony/yaml has uncommitted changes.

Please help.

Regards,
Tal.

**Comment by xabbuh** [comment]
It looks like you (or some Composer plugin) made changes to some files of the Yaml component inside your `vendor` directory. There's nothing we can do here about that. However, you can use `d` during the prompt to see what exactly was changed inside your `vendor` directory. Closing here as this has nothing to do with Symfony. Thank you for understanding.
