### ISSUE TITLE
DateTimeType HTML5 Chrome

### ISSUE THREAD

**Issue by ricardosaracino** [symfony/symfony#22063]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

**Comment by RicardoSaracino** [comment]
Well i had to do a bit of work to get it working on chrome, not sure what the current html spec says but the my date time would not use the supplied value unless i used my HTML5_FORMAT 

`{% block date_time_widget %}
	{{ form_widget(form, { 'type' : 'datetime-local'}) }}
{% endblock %}
`

`/**
 * Class UserDateTimeType
 * @package AppBundle\Form\Type
 * 
 * Symfony DateTimeType would not render correctly
 */
class UserDateTimeType extends TextType {

	/**
	 * Works in Chrome
	 */
	const HTML5_FORMAT = 'Y-m-d\Th:i';

	/**
	 * @var \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
	 */
	private $tokenStorage;

	/**
	 * @param TokenStorage $tokenStorage
	 */
	public function __construct(TokenStorage $tokenStorage)
	{
		$this->tokenStorage = $tokenStorage;
	}

	/**
	 * {@inheritdoc}
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder->addModelTransformer(new \AppBundle\Form\Transformer\UserDateTimeTransformer($options['model_timezone'], $options['view_timezone'], $options['format']));
	}

	/**
	 * {@inheritdoc}
	 */
	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(
			[
				'widget' => 'single_text',
				'compound' => false,
				'input' => 'sting',
				## UserDateTimeTransformer
				'format' => self::HTML5_FORMAT,
				'model_timezone' => 'UTC',
				'view_timezone' => $this->tokenStorage->getToken()->getUser()->getTimeZone(),
			]
		);
	}

	/**
	 * @return null|string
	 */
	public function getBlockPrefix()
	{
		return 'date_time';
	}
}`

**Comment by xabbuh** [comment]
This looks like the same as #27233 for me which has a pending pull request. So I am going to close here.

@ricardosaracino Can you confirm that #28372 fixes your issue too?
