### ISSUE TITLE
Create traits for common tasks in controller

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#22061]
| Q                | A
| ---------------- | -----
| Bug report?          | no
| Feature request? | yes
| BC Break report? | no
| RFC?                     | no
| Symfony version  | 3.1

Symfony [don't officially recommends](http://symfony.com/doc/current/controller/service.html) that controllers should be defined as a service. Therefore, some devs (like me) like to define the controllers as a service to keep them thin and not depending on container. This issue is to suggest some traits that make the same tasks of `Symfony\Bundle\FrameworkBundle\Controller\Controller`, example:

```php

trait FormTrait
{
    private $formFactory;
   
    /**
     * Creates and returns a Form instance from the type of the form.
     *
     * @param string $type    The fully qualified class name of the form type
     * @param mixed  $data    The initial data for the form
     * @param array  $options Options for the form
     *
     * @return Form
     */
    protected function createForm($type, $data = null, array $options = array())
    {
        return $this->formFactory->create($type, $data, $options);
    }

    /**
     * Creates and returns a form builder instance.
     *
     * @param mixed $data    The initial data for the form
     * @param array $options Options for the form
     *
     * @return FormBuilder
     */
    protected function createFormBuilder($data = null, array $options = array())
    {
        return $this->formFactory->createBuilder(FormType::class, $data, $options);
    }
}
```

In that way I need only to inject the `FormFactoryInterface` in the controller and I have the same shortcuts of `Symfony\Bundle\FrameworkBundle\Controller\Controller`. The above example shows the trait for `FormFactoryInterface` but it would be for the must used services like `EngineInterface`, `UrlGenerator`, `Doctrine`, `Security` and etc.

**Comment by iltar** [comment]
Regarding the `EngineInterface`, I've proposed an idea with lazy rendering (replacing `@Template`), which someone turned into a PR #21765. This should effectively replace 1 dependency.

Your forms can have a lot of dependencies:
 - Form Factory
 - Usually a repository to fetch current data
 - The Entity Manager (or repository) to persist the new data
 - A url generator to redirect
 - A flash bag/session to store a message that it went fine
 - Any other dependency like an API or what ever to handle forms

To reduce the controller size, you can also use this package: https://github.com/hostnet/form-handler-bundle

Effectively this reduces the amount of dependencies in your controller quite some and aims for slim controllers.

> Note that there's an open PR that will improve quite some, reducing dependencies of your action. This PR should be merged soon.

Regarding the other dependencies:
 - Security: use the `@Security` annotation
 - Doctrine: use (and inject) repositories if you need them

**Comment by GeoffreyHervet** [comment]
You're maybe looking for a `FormHelper` instead of a `trait` ?

**Comment by nicolas-grekas** [comment]
Instead of a new trait, this should be proposed as new methods on ControllerTrait, see #18193
