### ISSUE TITLE
Allow easy and disruption-free secret rotation

### ISSUE THREAD

**Issue by BabakMN** [symfony/symfony#22078]
Just wanted to open a discussion about the ability to rotate the application secret.

What do you think about something roughly like the following:

* Make the `secret` parameter an array instead of a single value

* Whenever a secret is needed to produce a value use the very first item from the secret array

* Whenever a value is being validated against the secret iterate through the secret array and test the operation against all secrets.

* Where possible, "upgrade" the value using the newest secret.

If the application secret needs to be rotated just push a new secret at the beginning of the array. Over time you can delete old items and keep the most recent `N` items.

So values based on old secrets will be honoured until their expiry and the secret can be rotated easily without any disruption.

If you want immediate invalidation of all values, push a new secret, get rid of all other secrets.

I can imagine some potential command line commands as well,

* `bin/console security:secrets:rotate` (add new secret, keep all)

* `bin/console security:secrets:rotate --keep=5` (rotate and keep up to 4 older secrets)

* `bin/console security:secrets:rotate --keep=1` (rotate and invalidate all others)

For example you could have `bin/console security:secrets:rotate --keep=5` set in a nightly cron for automatic daily rotation.

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

**Comment by javiereguiluz** [comment]
@BabakMN I still don't have an opinion about this proposal ... but keep in mind that the "secret" parameter:

* Must be the same on every server that runs the same application
* If you change it, you log out all your users automatically

So it's a very special parameter.

**Comment by BabakMN** [comment]
Thanks for your input Javier.

With regards to the first point, it's a good point worth considering however I think it naturally falls outside the scope of Symfony.

Anyone running a multi-server setup will understand the consequences of having out-of-sync values on different servers and will be expected to manage them in the same way they manage other values such as API keys.

Thinking about that, I think that can be a good case for _not_ having the `rotate` command that I mentioned earlier in Symfony.

However, the other part could still be done (make secrets an array).

In other words that would mean that Symfony will support secret rotation, however it will not manage them for you in any way (beyond an initial generation if needed).

So people can continue to manage their own parameters like they do now, including the secrets.

With regards to your second point,

I was hoping that making the secrets an array could avoid this problem. In other words when you add the new secret a value that was based on the old secret will still be considered valid because the old secret is still in service so users will not notice anything and you can rotate secrets frequently.

**Comment by sstok** [comment]
The secret is used for CSRF, and remember-me? It's not an encryption or password, it needs to remain a secret and should be truly random! Rotating the secret is a bit overkill and unnecessary.

Secondly testing against old keys could potentially cause a downgrade attack were an old compromised key can still be considered valid.

**Comment by BabakMN** [comment]
Of course changing the secret is always easily possible. I think it would be nice if changing it was "optionally disruption free" so you are not forced to invalidate everything.

You can still invalidate everything if you wish, but you will not be forced to (by leaving only one item in the secrets array).

I'd argue that whenever a "secret" mechanism is provided it is equally important to make an effort to facilitate the invalidation and rotation of it.

Right now the single secret value actively discourages people from changing the secret because of the immediate forced invalidation.

I wouldn't say it's overkill. Rotating secrets is a part of any good security policy.

With regards to the downgrade attack,

The management of the values are left entirely to the user.

If someone leaves a old compromised secret in there it doesn't matter if they can have 1 or 10 of them.

The "secrets array" would be defined as "the set of current valid secret(s)". So old compromised keys should be removed from such an array. Having a single value is the same as having an array of size 1.

Ultimately this means all you are doing is allowing the system to recognise more than one secret as valid at a time.

So when you rotate you can keep the previous value in there for a few days or hours and no user faces an unexpected error/logout.

Logically from a security standpoint provided that each secret is long and truly random and not compromised it makes no difference if the system honours only 1 secret or 5 (negligible difference to be precise).

An attacker is equally unlikely to guess any of them.

**Comment by nicolas-grekas** [comment]
Shouldn't this be dealt with and env var instead? There is already everything in place to do so if I'm not wrong.

**Comment by BabakMN** [comment]
@nicolas-grekas Yes environment variable is also good but that's not the issue.

What I'm suggesting here is to allow for more than one secret to be valid at any point in time.

So the validation logic in relation to secret values becomes iterative. It starts with the "freshest" secret and goes through all available secrets until it finds a good one. Otherwise it's invalid.

Where possible it can re-compute the "old" values using the freshest secret as a bonus. Or just leave them to expire naturally.

As I highlighted above earlier this isn't really anything exotic or complicated because it's almost the same as the existing logic (single secret value => array of secrets with size 1) which will remain possible for anyone who wants it.

For reference [Keygrip](https://github.com/crypto-utils/keygrip) is an example of a software that does this.

**Comment by fabpot** [comment]
The secret is now an env var. For everything else, I don't think it belongs to Symfony core. So, let's close here. Thanks for the discussion.
