### ISSUE TITLE
Per Firewall Guard Configuration Options

### ISSUE THREAD

**Issue by ChadSikorra** [symfony/symfony#22071]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | maybe?
| BC Break report? | no
| RFC?             | no

What is the recommended way to do per-firewall guard configuration options? Just add logic based on the request in the Guard? My current use case is redirection settings. Based on what firewall you are using a Guard from you might want different redirection to occur. It would be nice to define some configuration options like this per firewall like you can with the form_login approach.

Currently it seems like the only way would be to add logic to the `onAuthenticationSuccess()` and `onAuthenticationFailure()` methods and inspect the Request object. Maybe it should stay that way due to the generic nature of the Guard in general? Thoughts?

**Comment by weaverryan** [comment]
Hey @ChadSikorra!

I think you have 2 different options:

1) Yep, you could definitely just look at the request URI. Nice and simple.

2) The more "proper" way would be to create 2 separate guard authenticator services, passing each some different configuration argument. Then, each firewall will have its own guard service id (but both will still be using the same class, so no code repeat!)

And yea, the goal is to keep Guard pretty generic - I want to avoid adding more configuration to `security.yml`, and instead have the end user write their own logic :).

Cheers!
