### ISSUE TITLE
[FileSystem] makePathRelative incorrect output when $startPath has ".." in it

### ISSUE THREAD

**Issue by motammem** [symfony/symfony#22083]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0

```php
$endPath = 'C:\web\js\app.js';
$startPath = 'C:\web\css\..\\';
$filesystem->makePathRelative($endPath, $startPath);
```
Expected output is `js\app.js` but this snippet outputs `../../js/app.js/`.

**Comment by xabbuh** [comment]
Can you try #22085?

**Comment by xabbuh** [comment]
I just had another look at the documentation of the `makePathRelative()` method. It clearly states that both arguments must be absolute paths. In this case, passing a path that contains the `..` segment is not expected, is it?

**Comment by jakzal** [comment]
Isn't `C:\web\css\..\` still an absolute path? It's not relative to the current directory.

**Comment by Tobion** [comment]
It's absolute but contains dot segments. It's not stated whether that is supported. But if it was supported there should be a `removeDotSegments` method on the filessystem I guess.

**Comment by xabbuh** [comment]
I have reworked #22085 and opened it as #22133.
