### ISSUE TITLE
AuthenticationProviderManager can contain duplicate authentication providers

### ISSUE THREAD

**Issue by scoolen** [symfony/symfony#22093]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.11

If my application has multiple firewalls with some of them using the same user provider; they will be added to the AuthenticationProviderManager as unique authentication providers.

Is this intended behavior c.q. is there a use case I'm overlooking?

I would expect them to be deduplicated somewhere during the configuration compilation.

**Comment by chalasr** [comment]
In fact, an _authentication_ provider service is created per authentication listener and per firewall. Most of the time each created service takes the configured _user_  provider as constructor argument (see e.g. [DaoAuthenticationProvider](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php) for form-login.
 
For instance, configuring 2 firewalls with e.g. 1 `form-login` per firewall would create 2 authentication provider services. Given uniqueness is based on the created _authentication_ provider service id (not the user provider name), both would added to the auth provider manager service. I might miss something but I think this is right.

**Comment by scoolen** [comment]
@chalasr I'm not sure I follow you. You mean to say "in fac"

**Comment by javiereguiluz** [comment]
Closing it because @chalasr said that this is indeed the expected behavior and not a bug. Please reopen if you disagree. Thanks!
