### ISSUE TITLE
Fix for CSS attribute at Profiler Translation Page

### ISSUE THREAD

**Issue by you-ser** [symfony/symfony#22107]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

File: [symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/translation.html.twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/translation.html.twig)

Problem: If you have 2+ spaces between words at message for translation e.g. `Post__Header` ('_' is space) browser show it with one space `Post Header` (in browser console you can see all spaces but browser render it with `white-space:normal;` default rule) and if you copy message from Profiler page it will be with one space too.

Solution: At macro **render_table** last 2 columns "Message ID" and "Message Preview" should have css rule
```css
white-space: pre;
```
which can be added with some class at file 
[symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/profiler.css.twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/profiler.css.twig)

**Comment by e-moe** [comment]
Looks like this issue can be closed since PR was merged

**Comment by javiereguiluz** [comment]
Yes! Closing it as fixed by #22123. @e-moe thanks for your contribution!
