### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by strikeflo** [symfony/symfony#22106]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

File : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/EmailValidator.php

There's a problem when using checkMX option with email with a @ at the end leading to error "Warning: checkdnsrr(): Host cannot be empty"

The regex '/^.+\@\S+\.\S+$/'  line 81 allow email pattern like 'name@email.com@' but the code substr($value, strrpos($value, '@') + 1) line 90 doesn't work then and return empty string for $host...

**Comment by jordscream** [comment]
@strikeflo , IMO we have to enforce the regexp.
Do you have the problem when you put strict option to TRUE ? ([link](http://symfony.com/doc/current/reference/constraints/Email.html#strict))

**Comment by jordscream** [comment]
@strikeflo , or verify not empty string in checkMX function

@xabbuh , WDYT?

**Comment by strikeflo** [comment]
@jordscream the strict option work, but it just bypass the initial problem
I'll just use the strict option for my project, so that issue don't really matter to me anymore, but it would be nice to enforce the regex indeed. (at least prevent a situation where an unexpected error can occur)

**Comment by jordscream** [comment]
Waiting for @xabbuh opinion

**Comment by xabbuh** [comment]
A solution could be to let `checkMX()` return `false` when the `$host` is empty.
