### ISSUE TITLE
Allow setting custom PHP executable with parameters for server:run command

### ISSUE THREAD

**Issue by tomasfejfar** [symfony/symfony#22101]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.4

* I'm using https://github.com/tomasfejfar/xdebug-wrappers if I need xdebug in any CLI app - practically a shortcut for `php -dzend_extension=xdebug.dll`
* I'm using symfony console command server:run to start dev server
* other usecase would be running the server with custom php.ini (`php -c /path/to/ini`)

**Expectation:**
If I run `xdebug bin\console server:run` CLI PHP is launched with xdebug extension enabled. So will the server. 

**Actual:**
If I run `xdebug bin\console server:run` CLI PHP is launched with xdebug extension enabled. But not the server, because it reverse parses the php executable from runtime (i.e. runs `php` without the -d parameter). 

**Proposed solution:**
Ideally I'd want the server to run using the very same command used to run the command. But that seems impossible from what I researched. 
So the next best solution seems to be to allow passing the executable from outside in `ServerRunCommand::createPhpProcessBuilder` skipping  `\Symfony\Component\Process\PhpExecutableFinder::find()` if it's defined. 
I'll be happy to send PR if this makes sense to you.

**Comment by jordscream** [comment]
@tomasfejfar 👍

**Comment by nicolas-grekas** [comment]
@tomasfejfar would you like submitting a PR? That'd be for 3.4 on WebServerBundle

**Comment by tomasfejfar** [comment]
I'll try to work on that and submit PR ASAP.

**Comment by tomasfejfar** [comment]
The PR is ready, I hope ;)
