### ISSUE TITLE
DOMCrawler break each loop

### ISSUE THREAD

**Issue by kironet** [symfony/symfony#22110]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2

Hello,
I don't know here to ask, on stackoverflow noone can help me.

I'm using DOMCrawler.
Is it possible somehow break each loop? 

What I want, is simple. 
I have a table, I want to get a column, and if column contains some string, I want to break each loop. 

```
<table id="ctl00_MainContent_objSearchGrid_dgCorpSearchResults" cellspacing="0" cellpadding="0" align="Center" rules="all" border="1">
    <tbody>
    <tr>
        <td>Entity Name</td>
        <td>NV Business ID</td>
        <td>Status</td>
        <td>Type</td>
    </tr>
    <tr>
        <td><a href="">GOOGLE</a></td>
        <td><a href=""></a></td>
        <td><a href="">Expired</a></td>
        <td><a href="">Reserved Name</a></td>
    </tr>
    <tr>
        <td><a href="">GOOGLE INC.</a></td>
        <td><a href="">NV20161275322</a></td>
        <td><a href="">Active</a></td>
        <td><a href="">Foreign Corporation</a>
        </td>
    </tr>
    </tbody>
</table>
```

```
        $crawler->filter('#ctl00_MainContent_objSearchGrid_dgCorpSearchResults tr')->each(function (\Symfony\Component\DomCrawler\Crawler $element) {
            $status =  $element->filter('td')->eq(2)->text();
            echo $status;
            if ($status == 'Active') {
                break;
            }
        });
```

**Comment by jakzal** [comment]
No, it's not possible and it wouldn't make any sense as the `each()` method's suppose to invoke a callback on **each** node. You can use a foreach to loop over the result of your `filter()` call though.

Closing as we don't use github for support questions ;)

**Comment by draaslan** [comment]
I have the same issue.

**Comment by DougThwaites** [comment]
Pretty sure you can use return; or return true; to continue the loop and return false; to break to loop :)

Hope this helps :)
