### ISSUE TITLE
EntityType form field not adding empty option for dropdowns

### ISSUE THREAD

**Issue by Mike-Expedient** [symfony/symfony#22111]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no?
| Symfony version  | 3.2.3

In using an EntityType field in a form, there's no way to get a blank option in a drop down (select tag). `'required' => false`  does not work and neither does adding a placeholder. Making the menu a set of radio buttons via the `'expanded' => true` option does yield a radio button with a "None" label, but no way to yet get it as part of a dropdown or a multiselect field.

**Comment by dmaicher** [comment]
So setting `'required' => false` and `'placeholder' => 'bla'` together is not working? Sure it's not related to any custom form theme when rendering it?

Currently I don't not have any Symfony 3.2 app to try and reproduce the problem :yum: On Symfony 2.8 and 3.0 its working for me definitely.

**Comment by Mike-Expedient** [comment]
Looks like it was a form theme that was pulled from a symfony 2.6 project that was blocking the rendering of the dropdown. Thanks for your help!

**Comment by dmaicher** [comment]
:+1:

**Comment by rustx5** [comment]
👍🏻
