### ISSUE TITLE
Leverage new "cron jobs" from Travis

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#22118]
| Q                | A
| ---------------- | -----
| RFC?             | yes
| Symfony version  | all

I just noticed https://docs.travis-ci.com/user/cron-jobs/

This means we could have more extensive tests run on a periodic basis.
E.g. runs some functional tests of symfony standard with symfony master, silex, code coverage, etc.
If someone would like to give it a try (on its fork first?), please do :)

**Comment by iltar** [comment]
What about installing the https://github.com/symfony/symfony-demo there with the latest master and run the tests?
