### ISSUE TITLE
Support for constructing parent service definition in build time

### ISSUE THREAD

**Issue by chapterjason** [symfony/symfony#22125]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.6

In my Project I use [https://github.com/doctrine/DoctrineMongoDBBundle](https://github.com/doctrine/DoctrineMongoDBBundle) to work with `MongoDB`. It works very well.

To have one website with pages in different languages I use an optionally `_locale` param in `@Route`, what also works very well. But now to inject an array with all languages to twig from the database I need to create a `CompilerPass` that do something like that:

```php
public function process(ContainerBuilder $container)
{
    // $manager = $container->get('doctrine_mongodb')->getManager(); // here it breaks
    // $repository = $manager->getRepository('Bundle:Languages');
    // $languages = $repository->findAll();
    // [...] // do some random stuff to convert languages in an simple list like in the next line

    $languages = ['en', 'de', ...]; // this data should come from the database like in the outcommented lines before
    $definition->addMethodCall('addGlobal',
        ['languages', $languages]
    );
}
```

I can't get access to the Database here cause it throws `Constructing service "monolog.logger.doctrine" from a parent definition is not supported at build time.` ([https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1009](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1009)) that means it is possible to support creating services from a parent definition?

No? why?
Yes? how?

**Comment by jakzal** [comment]
Compiler passes are executed while container is being built. It's not ready to work with yet and you shouldn't be accessing services in the compilation phase. 

See https://github.com/symfony/symfony/issues/18673#issuecomment-216183042

You'll need to fetch your languages with no services (i.e. plain sql or move them to configuration), or fetch them at run time.

**Comment by xabbuh** [comment]
If its class implements the [`Twig_Extension_GlobalsInterface`](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/GlobalsInterface.php), your Twig extension can even provide global variables.

**Comment by chapterjason** [comment]
@xabbuh I solved this now with a kernel EventListener `onGetResponse` It works, but its a bit wired to do something like inject languages on every request cause of the database costs (Note to myself: cache o.O). Its not the first time I had the issue to do something with services in build time.

Thank you for this hint!

**Comment by xabbuh** [comment]
Depending on how expensive it is to fetch these information you may indeed want to cache them somehow.
