### ISSUE TITLE
[HttpKernel] Support for Throwable

### ISSUE THREAD

**Issue by lstrojny** [symfony/symfony#22128]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

The exception handling subsystem in Symfony’s HttpKernel does not support PHP 7 Throwables yet.

## Changes
 - Let `Symfony\Component\HttpKernel\HttpKernel::handle()` catch `Throwable`
 - Invoke `Symfony\Component\HttpKernel\HttpKernel::handleException()` and pass `Throwable`
 - Change `Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent` to allow `Throwable` or `Exception`
   - This is a BC break  ⚠️
 - Change `Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent` to hint `Exception|Throwable`
   - This is a BC break ⚠️
 - Change `Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException()` to catch `Throwable` as well
 - Change `Symfony\Component\HttpKernel\EventListener\ExceptionListener::logException()` to accept `Exception` or `Throwable`
   - This is a BC break ⚠️
 - Change `Symfony\Component\HttpKernel\EventListener\ExceptionListener::duplicateRequest()` to accept `Exception` or `Throwable`
   - This is a BC break ⚠️
 - Change `Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer::render()` to handle `Throwable`

Anybody thinks that a bad idea? Anything I forgot? Feedback is more than welcome!

**Comment by Taluu** [comment]
Accepting `Exception` or `Throwable` are not BC Breaks... as it is opening the scopes for each mentionned methods.

But 👍

**Comment by nicolas-grekas** [comment]
PHP 7 errors are dealt with in a special way: any "Error" are turned into regular "FatalThrowableError" by the Debug component, then reinjected into regular exception handling via the terminateWithException method. Nothing to do here IMHO.

**Comment by lstrojny** [comment]
@Taluu they are B/C breaks since people could be overloading the and would need to adjust the type hints to not violate LSP in their overloading classes.

@nicolas-grekas indeed, that sounds good to me. Maybe with 4.0 some simplification is due in the Debug component but that's certainly nothing this PR does.

**Comment by derrabus** [comment]
Is this still the way to go? Now that PHP 5 is not supported anymore, the whole `Error` wrapping code seems unnecessary to me.

Also, if an error is caught, I currently see `FatalThrowableError` instead of the actual error class which is not intuitive, imho.

**Comment by nicolas-grekas** [comment]
Yes it is, Error and Exception do not have the same base type for a reason - the same here.

**Comment by derrabus** [comment]
A big reason was probably BC. If errors would be thrown as exceptions, you'll break a lot of legacy code. Or is there one I'm missing here?

I'll open another ticket for the side effect I've mentioned. I think, we can fix that without refactoring the whole error handling. ;-)

**Comment by derrabus** [comment]
I'm mean, technically, #18140 could have been rejected for the seam reasons.

**Comment by nicolas-grekas** [comment]
@derrabus that's true :) I'm mostly saying the current way of handling Error makes sense, so there is no hurry into create a deprecation + BC break, and I prefer resiting it personally. It's not trivial that they are different - yet they are. Almost nobody should catch "Error" - so neither "listen" (which means canceling potentially), except post-low-level handling - which is what the current design achieves. Changing this gives more important responsibilities to devs - but fail safe is a really complex topic.

**Comment by Erikvv** [comment]
If you are running Symfony not standalone but instead calling from another framework, the Error escapes Symfony and it will use the error handlers of the other framework. 

This is not intuitive.

Also the Debug Component does not work in that case.

**Comment by derrabus** [comment]
@Erikvv That is correct. This regularly strikes me when boostrapping Symfony inside a legacy application that already has custom errors handlers in place that I cannot replace right away. See also #26514 for a lengthy discussion on that topic.
