### ISSUE TITLE
[varDumper] question about __debugInfo() method

### ISSUE THREAD

**Issue by s-chizhik** [symfony/symfony#22141]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | possible
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

Hi. I have a little question about `VarDumper` component. Is there any ability (at least potential) to change method name, [which is used to get debug info](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/Caster.php#L53)? I'd like to use custom-named method instead of `__debugInfo()`. Why? Because `xDebug` or `PhpStorm` can call this method when I'm debugging and it will break app trace. To prevent this, I'd like to rename `__debugInfo()` to ex: `__myAwesomeDebugInfo()`. It allows to save `VarDumper` functionality and prevent breaking debug trace by `xDebug`.

**Comment by stof** [comment]
``__debugInfo`` is a PHP feature. So the VarDumper component uses this builtin feature when it is implemented.

If you want to add extra info in the dump only when using VarDumper, implement a dedicated Caster for your class and register it in the dumper.

**Comment by s-chizhik** [comment]
@stof, thx for the answer. I guess your suggestion will help!
