### ISSUE TITLE
Conflict restrictions are not feasable for symfony/form

### ISSUE THREAD

**Issue by dereuromark** [symfony/symfony#22145]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.8.18

Please see
https://github.com/symfony/form/commit/fdee9a5231da88aa770b661738116fee90365aeb

This breaks existing applications that have constraints on this range of codeception/phpunit.
They cannot that easily upgrade those other dependencies, but now can't also get any patches for symfony/form without breaking everything as it would force-downgrade those mentioned dependencies or go into a dead lock.

The issue is that even though phpunit is a require-dev dependency "conflict" additions to the composer.json bubble up into productive systems (they are not constrainted to require-dev and first level dependency pulling). This is not acceptable. You must be more careful with setting those constraints, as they have no relevance for applications running with symfony forms, but now make those incompatible with the new ( and potential security) patches.
I recommend a less brutal constraining inside of your tests at runtime instead. By either throwing an exception or skipping those. "Conflict" due to the mentioned issues for production projects is wrong IMO.

**Comment by stof** [comment]
Well, Symfony provide base testscases to test your own form types. And they have been migrated to use the namespaced classes in PHPUnit to be compatible with PHPUnit 6.
This requires using PHPUnit 4.8.35 or using PHPUnit 5.4.3+ (because the namespaced class is not available otherwise).

I don't think this is a big issue. This prevents you to use early PHPUnit 5 releases, but these are unmaintained. This still allows lots of PHPUnit 5 releases.

**Comment by stof** [comment]
And we cannot make the ``extends`` clause condition to switch the parent class (at least not without weird ugly hacks)

**Comment by xabbuh** [comment]
I agree with @stof here. There is no maintained PHPUnit version you cannot use with this conflict rule.

**Comment by dereuromark** [comment]
That's a bummer. OK, we will have to see how we can navigate out of this mess. Thanks for the clarification.

**Comment by xabbuh** [comment]
@dereuromark Which PHPUnit version are you using and why is it that you cannot update it?

**Comment by dereuromark** [comment]
"version": "5.3.5", due to codeception "version": "2.1.11" and other requirements that prevent an upgrade for those at this time. But now no symfony bugfixes can be pulled anymore because of the IMO too harsh constraints.
But we will figure it out on our end then.

**Comment by sstok** [comment]
To bad Composer doesn't support a conflict-dev option 🤔
