### ISSUE TITLE
RequestDataCollector exception when forwarding requests

### ISSUE THREAD

**Issue by ovrflo** [symfony/symfony#22166]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x / dev-master / 1b63474

Hello,

I just installed a brand-new symfony/framework-standard-edition:dev-master a few hours ago and now I got an exception when I used Controller::forward().

`Symfony\Component\VarDumper\Cloner\Data objects are immutable`

Relevant trace:
```
BadMethodCallException: Symfony\Component\VarDumper\Cloner\Data objects are immutable.
    at n/a
        in vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/Data.php line 149

    at Symfony\Component\VarDumper\Cloner\Data->offsetSet('forward', array('token' => 'cbc1b8', 'controller' => array('class' => 'FOS\\UserBundle\\Controller\\SecurityController', 'method' => 'loginAction', 'file' => 'vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php', 'line' => 27)))
        in vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DataCollector/RequestDataCollector.php line 41

    at Symfony\Bundle\FrameworkBundle\DataCollector\RequestDataCollector->collect(object(Request), object(Response), null)
        in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php line 184

    at Symfony\Component\HttpKernel\Profiler\Profiler->collect(object(Request), object(Response), null)
        in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php line 97

    at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse(object(FilterResponseEvent))
        in var/cache/dev/appDevDebugProjectContainer.php line 1060
```

I followed the trace and I got to `Symfony\Bundle\FrameworkBundle\DataCollector\RequestDataCollector` which tries to set `$this->data['forward']` after calling it's `parent::collect()`. The problem is that `parent::collect()` "freezes" `$this->data` by cloning it (with VarCloner).

The easiest fix is probably to call `parent::collect()` _after_ updating `$this->data`, but I don't know if it's the best fix (I hope not). In the mean time I'll avoid the forward.

Any input ? Should I submit a PR with my proposed fix ?

**Comment by ro0NL** [comment]
Nice catch. What about using an additional property `$this->forward`?

Status: reviewed

**Comment by ovrflo** [comment]
So, I did a little digging. This is what I found out:
- This bug was introduced in ab716c6
- My initial suggestion to call `parent::collect()` after manipulating `$this->data` would not work since that array gets initialized in the `parent`
- @ro0NL's solution might work with minimal work (need to override `parent::serialize()`)
- I propose another solution: split the logic in 2 methods: one that performs the collection (building the array) and another that calls the first and then freezes (clones) `$this->data`.

Finally, looking at the commit that introduced the bug, I'm wondering what other collectors are affected.

**Comment by ro0NL** [comment]
Another solution could be

```
parent::collect();
$data  = $this->data->getValue(true);
$data['forward'] = ..;
$this->data = $this->cloneVar($data);
```

But is perhaps a bit overkill.

I think for now your last suggestion (splitting the base method) is the most sane thing to do :+1: 

> I'm wondering what other collectors are affected.

I believe not in core. Reading is unaffected, writing could create issues in user land collectors. Not sure we should care... :thinking: 

cc @nicolas-grekas this one is pretty critical for 3.3 :)
