### ISSUE TITLE
[Serializer] Using constructor with variadic argument and name converter could lead to bug?

### ISSUE THREAD

**Issue by Arkemlar** [symfony/symfony#22169]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | from `master` to `3.1.7` or earlier

Today when I read sources of serialiser component I found weird thing.
Look at [this](https://github.com/symfony/serializer/blob/master/Normalizer/AbstractNormalizer.php#L343) line. I copy-paste this fragment there:

```php
                    if ($allowed && !$ignored && (isset($data[$key]) || array_key_exists($key, $data))) {
                        if (!is_array($data[$paramName])) {
                            throw new RuntimeException(sprintf('Cannot create an instance of %s from serialized data because the variadic parameter %s can only accept an array.', $class, $constructorParameter->name));
                        }
                        $params = array_merge($params, $data[$paramName]);
                    }

```

Previous line checks `$data` array for existence of `$key`, but then `$paramName` used insted in `is_array call` and in `array_merge` too. I think its a bug. It could be not found yet because this code should be executed when class has constructor with variadic argumant AND when name converter is used at the same time.

**Comment by jakzal** [comment]
@Arkemlar could you please provide small snippet of code, or a test case, that would reproduce the alleged bug?

**Comment by xabbuh** [comment]
Closing for now due to the lack of feedback. @Arkemlar Please provide more information to reproduce the issue you described and we can consider to reopen.
