### ISSUE TITLE
Routing: Working with entities

### ISSUE THREAD

**Issue by sourcerer-mike** [symfony/symfony#22161]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no/dunno
| Symfony version  | 3.2

Routing works like:

```
wallet_read:
  path: /wallet/{id}.{_format}
```

Would be nice to have that a bit more intelligent like

```
wallet_read:
  path: /wallet/{wallet.id}/{wallet.title}.{_format}
```

So that URL generator like in Twig receive the entity and does the rest of the magic:

```
path('wallet_show', {wallet: wallet})
```

How about that?

**Comment by iltar** [comment]
While this doesn't work exactly the way you want it, it does allow objects as route arguments: https://github.com/iltar/http-bundle

**Comment by javiereguiluz** [comment]
@sourcerer-mike thanks for your proposal. Sadly, I must close it as "duplicated" because we have received the same proposal in #21435 #10395, #5999, #11177 and #2288.

**Comment by zmitic** [comment]
@ScreamingDev Take a look at this bundle, works very similar to what you want with just one extra annotation:

https://github.com/zmitic/rewire-bundle

**Comment by iltar** [comment]
@zmitic interestingly enough, your objects when creating routes does almost the same as my bundle. Seems like it could be enhanced using my bundle for that part
