### ISSUE TITLE
[FrameworkBundle] Disabling --env and --no-debug 

### ISSUE THREAD

**Issue by bamarni** [symfony/symfony#22199]
I'm trying to create a Symfony application with the MicroKernelTrait helper, only containing the framework bundle. Kernel environment and debug mode would solely be passed through environment variables so I wouldn't use the `--env` and `--no-debug` flags for my CLI console, which is defined like this : 

``` php
#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Debug\Debug;

set_time_limit(0);

$loader = require __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/kernel.php';

if ($debug = getenv('DEBUG') !== false) {
    Debug::enable();
}

$kernel = new MicroKernel(getenv('ENV') ?: 'prod', $debug);
$application = new Application($kernel);
$application->run();
```

However those options are automatically defined here : https://github.com/symfony/symfony/blob/811a6bf5eb45fe0fedfa657f14a055ef10e1ddf9/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L44-L45

This registers them even though they don't have any effect and are not required by the framework bundle AFAICT, it seems like a convention from the standard edition. Would it be possible to move those lines to the standard edition's `bin/console` file? As it's a BC break for Symfony 4.0 maybe?

**Comment by GromNaN** [comment]
You can reset options like this:
```php
$options = $application->getOptions();
unset($options['env'], $options['no-debug']);
$application->setOptions($options);
```

**Comment by bamarni** [comment]
Thanks for the tip, even though there are workarounds imo it should still be moved on the long run.

**Comment by javiereguiluz** [comment]
@bamarni instead of removing these options, the solution should be:

* If you have full control of the command execution, don't use them and rely only on the env vars.
* If the command execution is beyond your control (because users can execute them) then you can apply the technique proposed by @GromNaN.

In any case, I'm closing this proposal as "won't fix" because this feature looks too niche to me. The `--env` option is definitely needed in most apps either to set the env or to override in a single command the global env set using env vars.

**Comment by bamarni** [comment]
@javiereguiluz : thanks for the follow-up. Lately I've seen this blog post though (http://fabien.potencier.org/symfony4-best-practices.html), my understanding of it was that those options were planned for removal?

> Currently, the Symfony console tool can take the environment and the debug flag via the --env and --no-debug flags. Or alternatively via the SYMFONY_ENV and SYMFONY_DEBUG environment variables.
With Symfony 4, this is no longer needed. APP_ENV and APP_DEBUG can be used for both the web front controller and the console tool.
No more ./bin/console foo:bar --env=prod --no-debug or SYMFONY_ENV=prod SYMFONY_DEBUG=0 ./bin/console foo:bar. Just use ./bin/console foo:bar.

**Comment by javiereguiluz** [comment]
@bamarni indeed you are right! I completely forgot about that. Another reason to not allow to disable --env and --no-debug is that they will disappear soon!
