### ISSUE TITLE
[YAML] Parser doesn't understand properly lines with trailing spaces 

### ISSUE THREAD

**Issue by lcobucci** [symfony/symfony#22193]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3-dev

As mentioned on https://github.com/symfony/symfony/pull/22067#issuecomment-289603202 the last commit on the yaml component breaks the parser for that scenario.

**Comment by fabpot** [comment]
ping @nicolas-grekas

**Comment by jordscream** [comment]
@fabpot @nicolas-grekas , I create a PR, it missed rtrim method.
I did the PR based on master
