### ISSUE TITLE
[DI] Default parameter values are only enabled with autowiring

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22209]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Symfony version  | 3.x

initializing `public function __construct($a, $b = 'b', $c = null)` while providing `$a` and `$c` is only possible with `autowire:true`

that should not really be needed right?

**Comment by nicolas-grekas** [comment]
Yes it should: dong reflection on service definition is done as sparingly as possible. autowiring is a case where obviously we need to do it, so the coupling happens there.
We do not want to be forced to inspect all services when no such introspecting passes are used.
