### ISSUE TITLE
Add IIS config files (security and rewrite support)

### ISSUE THREAD

**Issue by strulens** [symfony/symfony#22214]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Is it possible to add "web.config" files for IIS in addition with ".htaccess" files?

app/web.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.web>
        <authorization>
            <deny users="*" /> 
        </authorization>
    </system.web>
</configuration>
```

src/web.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.web>
        <authorization>
            <deny users="?" /> 
        </authorization>
    </system.web>
</configuration>
```

web/web.config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.webServer>
        <defaultDocument enabled="true">
            <files>
                <add value="app.php" />
            </files>
        </defaultDocument>
        <rewrite>
            <rules>
                <rule name="RewriteAll" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="app.php" appendQueryString="true" />
                </rule>
                <rule name="AvoidDuplicate" stopProcessing="true">
                    <match url="^app\.php(?:/(.*)|$)" ignoreCase="false" />
                    <action type="Redirect" redirectType="Permanent" url="{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by javiereguiluz** [comment]
I don't know if this proposal will make it, but I think we should add the `web/web.config` file to this doc article: http://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by curry684** [comment]
This is not a Symfony feature request, but a Symfony Standard Edition feature request. The framework does not care about deployment details like this.

Having said that I would make a stronger case for removing `.htaccess` files over adding support for every webserver out there, for example to NGINX all of them are noise. And potentially dangerous noise as every one of them has to properly forbid access to all other ones to prevent easy attack vector detection.

Perhaps SensioDistributionBundle could add some sort of "prepare for webserver X" command generating a bunch of web.configs or .htaccess files. It's a distribution/deployment thing after all.

**Comment by javiereguiluz** [comment]
@strulens thanks for this proposal. Right now Symfony is in a transition phase. The Symfony Standard edition (and the .htaccess files) is a thing of the past, because we are moving to [Symfony Flex](https://github.com/symfony/flex).

In the future, Symfony won't include the .htaccess files, so we can't add these files for IIS either. However, thanks to the new [Symfony Recipes](https://github.com/symfony/recipes) mechanism, we could implement this idea easily. I've moved your proposal there to discuss about it: https://github.com/symfony/recipes/issues/78

Thanks!
