### ISSUE TITLE
Documentation: TextType option 'empty_data' defaults to null

### ISSUE THREAD

**Issue by canaaerus** [symfony/symfony#22215]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

According to the [documentation](http://symfony.com/doc/master/reference/forms/types/text.html#empty-data) the default value of the `empty_data` option to `\Symfony\Component\Form\Extension\Core\Type\TextType` is the empty string `''`:

> empty_data¶
> 
> type: mixed
> 
> The default value is '' (the empty string).

But I found when using 3.2.6, that the default of `empty_data` is actually `null`.
I’m not sure if or where in the code this is actually defined, so I could not check against it.

**Comment by HeahDude** [comment]
Hello @canaaerus, this is a duplicate of #22192, we can close here, this is a known issue, thanks for the report anyway.

**Comment by canaaerus** [comment]
Ah I see now. A better duplicate is #7596. Sorry, I should have searched more thoroughly.
