### ISSUE TITLE
Update Twig dependency for 3.3.x-dev

### ISSUE THREAD

**Issue by Growiel** [symfony/symfony#22212]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             | no
| Symfony version  |3.3.x

I wanted to upgrade my 3.1.x version of Symfony to 3.3.x-dev to test the Session typehint feature.

I changed my `composer.json` to be `"symfony/symfony": "3.3.x-dev",`.

Ran `composer update symfony/symfony` without any issues... until the cache clear. The cache clear couldn't complete with the following error:

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Twig_ContainerRuntimeLoader' not found`

I looked at the Twig dependency in `symfony/symfony`, it's `"twig/twig": "~1.28|~2.0",`. I looked at my installed version, it's `1.31`.

For good measure, I ran `composer update` to update it all. Twig was updated from `1.31` to `2.3.0`:

    Removing twig/twig (v1.31.0)
    Installing twig/twig (v2.3.0)

The installation completed sucessfully and running `php bin/console c:c` works fine now.

Note that Twig was NOT the only module updated by the `composer update` command.

I'm not quite sure what the minimum version for Twig needs to be, but `1.31` doesn't to be working.

**Comment by stof** [comment]
the requirement should be updated to be ``~1.32|~2.2`` due to the new feature being used.

**Comment by xabbuh** [comment]
see #22220
