### ISSUE TITLE
[Cache] Why doesn't the FileSystemAdapter use the Symfony cache directory?

### ISSUE THREAD

**Issue by WickedSilver** [symfony/symfony#22233]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2.6 (from 3.1 and up AFAIK)

The `FileSystemAdapter` (and some other file caches) uses the `sys_get_temp_dir()` function to determine where to save the cache.
Is there any reason not to save it to the `var/cache` or `var/tmp` directory by default instead of using the `sys_get_temp_dir()` function?
The main reason i'm asking is that you might need to give the web server user permissions to write to the temp folder as well.
If there is a good reason tot `sys_get_temp_dir()` instead of the symfony cache directory please let me know.

EDIT: added `var/tmp` as another option

**Comment by xabbuh** [comment]
The `FilesystemAdapter` class is part of the Cache component which can be used outside the full-stack framework meaning that the neither the `var/cache` nor the `var/tmp` directory may exist.

**Comment by WickedSilver** [comment]
That seems about right 👍 
While i was trying to invalidate my cache using RabbitMQ i got some strange behaviour on Windows though.
Using the default directory (`sys_get_temp_dir()`) resulted in using `C:/Windows/Temp` from my controller for me 2 days ago. 
While implementing a consumer for RabbitMQ (whose job was to clear the file cache) my cache didn't seem to get cleared.
This could be because of file/write permissions, but testing this morning i saw the default directory was now `C:\Users\<username>\AppData\Local\Temp`
Seems this could be either a Windows issue or a mistake at my end since i can't really reproduce it anymore.

Unless someone else has/had problems with this i suggest closing this issue.

**Comment by theofidry** [comment]
Wouldn't it be better to default to `/var/tmp` in the context of Symfony full-stack? I realise I had a a similar issue :/
