### ISSUE TITLE
[PropertyInfo] Array or collection can be nullable 

### ISSUE THREAD

**Issue by 4rthem** [symfony/symfony#22248]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

PHP allows null value when using an array type hint but the [PhpDocExtractor](https://github.com/symfony/property-info/blob/2.8/Extractor/PhpDocExtractor.php#L343) does not consider array and collections as nullable since the [ReflectionExtractor](https://github.com/symfony/property-info/blob/2.8/Extractor/ReflectionExtractor.php#L214) does.

```php
function setProperty(array $prop = null)
```

**Comment by stof** [comment]
@dunglas any reason why ``$nullable`` is not taken into account there ?

**Comment by dunglas** [comment]
This is not the case:

```
php > function f(array $h) {}
php > f(null);
PHP Warning:  Uncaught TypeError: Argument 1 passed to f() must be of the type array, null given, called in php shell code on line 1 and defined in php shell code:1
```

IIUC, the behavior is correct here.

**Comment by dunglas** [comment]
If you explictly allow null values, you should document it accordingly:

```php
/** @param $prop array|null */
function setProperty(array $prop = null);
```

**Comment by 4rthem** [comment]
I gave you a bad example, yes it's about the PhpDocExtrator so I use the `@param $prop array|null` notation.

Please have a look at my PR: https://github.com/symfony/symfony/pull/22251/files
The issue is in the [createType](https://github.com/symfony/symfony/pull/22251/files#diff-72b9199530f645acef692f3d77d4de4dR318) method where `$nullable` is ignored when type is an array or a collection.
