### ISSUE TITLE
Twig global runs before proxies are generated on cache warmup

### ISSUE THREAD

**Issue by VersatilityWerks** [symfony/symfony#22246]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

Background: 
I have a white-label system with a SiteProvider class which looks at the HTTP_HOST and grabs the current site. That class is set as a Twig global so that it can be displayed on pages and such. It also acts as a site validator by throwing an exception if the site does not exist, or if there is a problem with the database.

Problem:
This works fine in dev, but in production it complains about a missing proxy which appears to be used when I grab the Site entity. From what I can tell, the Twig globals run before Doctrine gets a chance to generate proxies.

Solution:
Generate Doctrine proxies before Twig globals run, or offer up a workaround/solution for me please.

**Comment by xabbuh** [comment]
In the `prod` environment, the `kernel.debug` parameter is disabled. In this case, Doctrine proxy classes are not generated on demand, but you can do that by running the `cache:warmup` command which triggers the cache warmer from the Doctrine bridge that shows the work.

**Comment by VersatilityWerks** [comment]
I get the error while running cache warmup. I guess the twig globals are called prior to proxies being generated.

**Comment by xabbuh** [comment]
Can you please show the full error you get including its stack trace?

**Comment by VersatilityWerks** [comment]
For right now, this is the best i can do. I can run more later.

PHP Warning:  require(/var/www/FFB-CRM/var/cache/pro_/doctrine/orm/Proxies/__CG__AppBundleEntitySites.php): failed to open stream: No such file or directory in /var/www/FFB-CRM/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
PHP Fatal error:  require(): Failed opening required '/var/www/FFB-CRM/var/cache/pro_/doctrine/orm/Proxies/__CG__AppBundleEntitySites.php' (include_path='.:/usr/share/php') in /var/www/FFB-CRM/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

                                                                                          
  [Symfony\Component\Debug\Exception\FatalErrorException]                                 
  Compile Error: require(): Failed opening required '/var/www/FFB-CRM/var/cache/pro_/doc  
  trine/orm/Proxies/__CG__AppBundleEntitySites.php' (include_path='.:/usr/share/php')

**Comment by VersatilityWerks** [comment]
Also, this is my deploy script and it's dying on the warmup portion.

```
git pull origin master;
composer install;
php bin/console cache:clear --env=prod --no-debug;
php bin/console cache:warmup --env=prod --no-debug;
chmod 0777 -R ./var;
```

**Comment by xabbuh** [comment]
Can you also show the code of your Twig extension?

**Comment by VersatilityWerks** [comment]
I'm not at home to grab it but the part that causes the problems is a getRepository findOneBy.

**Comment by stof** [comment]
are you using findOneBy inside your class constructor or in a method ?

**Comment by VersatilityWerks** [comment]
Constructor. So as soon as it's instantiated it checks for the whitelabel site based on http_host.

**Comment by VersatilityWerks** [comment]
I need it to occur before the controller and be available to twig globally. If I set it up similar to the UserProvider, is there a way I could still set it as a twig global?

**Comment by stof** [comment]
this is the issue. the constructor can happen very early (as instantiation is needed to build other objects depending on it). Delay the DB query until necessary.

I cannot help you converting it without seeing some code.

**Comment by VersatilityWerks** [comment]
services.yml
```
    app.site:
        class: AppBundle\Security\SiteProvider
        arguments: ["@doctrine.orm.entity_manager", "%kernel.environment%"]
```

config.yml
```
twig:
  globals:
        siteprovider: '@app.site'
```

SiteProvider.php __construct method
```php
/**
     * SiteProvider constructor.
     * @param EntityManager $entityManager
     * @throws \Exception
     */
    public function __construct(EntityManager $entityManager, $environment)
    {
        $this->em = $entityManager;

        $domain = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : false;
        //only run if HTTP_HOST is set for now. This fixes cache-warmup error, but is NOT optimal.
        if( $domain )
        {
            /** @var SiteDomains site_domain */
            $this->site_domain = $this->em->getRepository(SiteDomains::class)->findOneBy(['domain' => $domain]);

            //if the site_domain does not exist
            if (!$this->site_domain)
            {
                throw new \Exception("This domain has not been setup correctly");
            }

            //if the environment does not exist
            if (!$this->site_domain->getEnvironment())
            {
                throw new \Exception("Found domain, missing environment");
            }

            //if the site does not exist
            if (!$this->site_domain->getSite())
            {
                throw new \Exception("Found domain, missing site");
            }
        }
    }
```

**Comment by VersatilityWerks** [comment]
So...I could keep it as-is, but move the domain query logic to another method called setSiteDomain() and call it from somewhere globally prior to the controller being called, but I'm not sure where would be best to do that.

**Comment by VersatilityWerks** [comment]
It needs to happen on every request, and I don't want to call it within my controller.

**Comment by stof** [comment]
Well, you should delay the retrieval of ``site_domain`` until the first time you need to read it.

If something needs to happen on each request, you can use a kernel.request listener (which will be called before the controller)

**Comment by stof** [comment]
btw, using a listener would allow you to use the Request object instead of reading from ``$_SERVER``, keeping the encapsulation (and making your code compatible with WebTestCase again)

**Comment by VersatilityWerks** [comment]
Good advice, much appreciated. I am curious if anyone finds this to be a limitation/bug or if it's my bad and I shouldn't have put that there?

**Comment by stof** [comment]
@VersatilityWerks when using dependency injection, you should never put business logic in the constructor, as it might be called much earlier than you think (or even when you think it should not be called at all, depending on the object graph).
The issue in your case is that instantiating the object is necessary before calling cache warmers, because the Twig cache warmer depends on Twig which depends on your service.

and the different cache warmers are not lazy-loaded at the time they are called. They are all instantiated at the same time when getting the main cache warmer.

**Comment by VersatilityWerks** [comment]
Makes sense, but my code aside...I still feel like Doctrine should be one of the first things generated because it's a lower level service. Like.. Config > Doctrine > Services > Twig > Controller.

**Comment by VersatilityWerks** [comment]
Hmmm...of course then you might run into services that need twig or twig that needs services. I guess it needs to figure that order out dynamically as-needed?

**Comment by stof** [comment]
@VersatilityWerks I don't know in which order they are running. But even if Doctrine is the first one, this would **not** solve your issue, as they constructor is called before **all** cache warmers.

**Comment by VersatilityWerks** [comment]
Ah Gotcha. Thanks a ton for your help. I've only been working with Symfony for 6 months and it's been a beast to wrap my head around.
