### ISSUE TITLE
[Form] ChoiceType not valid when expanded

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#22247]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

```
$builder->add('type', ChoiceType::class, [
    'label' => false,
    'choices' => [
        '1' => '1',
        '2' => '2'
    ],
    'expanded' => true,
    'mapped' => false
]);
```

after submit I'm getting:
**This value is not valid.**
Caused by:
- ConstraintViolation
- TransformationFailedException

if I remove expanded, then everything is OK

**Comment by xabbuh** [comment]
How do you submit the data? Do you build them manually? Can you create a failing test case or an example project that allows us to reproduce your issue?

**Comment by poolerMF** [comment]
I tried .. and after many attemps I figure out, I had one change in ChoiceType.php
my mistake, sorry
