### ISSUE TITLE
choices_as_values default value

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#22250]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.8.18

Why the default value of option `choices_as_values` is false for 2.8.*?
https://github.com/symfony/symfony/blame/2.8/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L411

My forms did not use this option at all, but however the deprecated warnings triggers.
https://github.com/symfony/symfony/blame/2.8/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L361

**Comment by stof** [comment]
@Aliance because of backward compatibility. We cannot change the default, as choices were passed as key in 2.x and so the default behavior of 2.8 must be the same for all projects upgrading from 2.7 to 2.8.

This option is precisely about being able to migrate the content of choices progressively (passing the option to true for places which have been migrated to the new API).

**Comment by Aliance** [comment]
As I understand, in 2.6- there was:
```php
'choices' => [
    'value' => 'label',
],
```

2.6-2.8 is the transition version, so this option was added:
```php
'choices' => [
    'label' => 'value',
],
'choices_as_values' => true,
```

In 3.0+ there will be:
```php
'choices' => [
    'label' => 'value',
],
//'choices_as_values' => true, – No need in this, this is the default behavior
```

Where am I wrong?

**Comment by stof** [comment]
there is nothing wrong here.

And this is precisely why the option default to false, so that updating your codebase from 2.6- keeps the same behavior (as you would not have migrated the choices yet)

**Comment by Aliance** [comment]
So after updating to 3.* these deprecations will gone away?

**Comment by stof** [comment]
Well, you must get rid of the deprecations *before* migrating to 3.x, as you cannot migrate to 3.x without updating the structure of choices. This is precisely what these deprecations are about.

**Comment by Aliance** [comment]
Thanks for explanations!
