### ISSUE TITLE
[Lock] Make FlockStore $fileName formula a callback function

### ISSUE THREAD

**Issue by temple** [symfony/symfony#22257]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | ¿?
| Symfony version  | 3.3

On this [version](https://github.com/symfony/lock/commit/1a795b6dd733c888f90e91660cd0abaa51068a92#diff-1e62348f8eaa842484a4d4667ad2578dR71) of `Symfony\Component\Lock\Store\FlockStore`
the function called `lock` calculates a name for the filesystem lock file, by a concrete string formula.

```php
        $fileName = sprintf('%s/sf.%s.%s.lock',
            $this->lockPath,
            preg_replace('/[^a-z0-9\._-]+/i', '-', $key),
            hash('sha256', $key)
        );
```

This doesn't help as much as letting the user provide an optional hash callback function via configuration and construct params or via class setter, don't ya think?

I'll would be graceful if you appreciate coding this suggestion.

Cheers

**Comment by jderusse** [comment]
Why would you control the filename used by the lock?
To you have a concrete use case?

**Comment by temple** [comment]
Multithread/Multi-process permissions stuff, Full-OS LOCALE compatibility, File Monitoring... any colour you like
