### ISSUE TITLE
[Config] Support dots in node names

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony#22268]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

I don't see any reason why developers would not use a config name with dots in it.

I am currently refactoring a legacy application using this kind of configuration nodes. I want to use the power of the `Config` component to improve validation.

I currently cannot do this and I could not find any reason why this is prevented.

**Comment by sstok** [comment]
The dot notation is used to inform at which position the configuration is set. I even believe in YAML you can use `framework.secret: 'thisissecret'` and it will be transformed to an array structure.

So changing this would be a big BC break.

**Comment by bburnichon** [comment]
I don't want to change anything about how symfony framework is using configuration. In my case, its the standalone `Config` component that changes (only to enlarge authorized values in keys)

**Comment by bburnichon** [comment]
@sstok Actually via introducing the ability to change path separator in #22253 it can be seen that prototyped array can already have dots in configuration path... We should be consistent, always prevent it, or never, but not sometimes allowing it, sometimes not.

**Comment by bburnichon** [comment]
What is the prefered way of targetting my issue?

1. Remove limitation of node names (which I consider as a bug and could be solved in all currently active branches and was my first intention)
2. Add path separator selector proposed in #22253 (and would land in 3.4 as a new feature. Maybe use `/` as default path separator in 4.0)
3. Another way

ping @sstok @fabpot @nicolas-grekas @stof

**Comment by bburnichon** [comment]
Is something missing on this issue? How can I help? @fabpot @nicolas-grekas @stof

**Comment by bburnichon** [comment]
I don't have any feedback on this since April! feature freeze is coming. Can you please review? @ogizanagi @fabpot
