### ISSUE TITLE
[humanizer] Using button label e.g. "Save BUG" creates unwanted result

### ISSUE THREAD

**Issue by tholanger** [symfony/symfony#22269]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

Using button label e.g. "Save BUG" creates unwanted result caused by humanize-method. If using Standard template "form_div_layout.html.twig" for example I was wondering why all my upper-case labels are strange whitespaced. For example I use a button label: "Save BUG". It is rendered as "Save b u g".  Is this a wanted result?

For me I just took the humazine-filter out of my "form_div_layout.html.twig"-copy.

If this is a wanted result I am sorry for creating this report. But I am not sure if should be so.

Kind regards,
Thomas

![2017-04-04_11h20_15](https://cloud.githubusercontent.com/assets/8501714/24650150/9d1439da-1929-11e7-9571-7ecfb7a841f8.png)

**Comment by curry684** [comment]
Please refer to the [`label`](http://symfony.com/doc/current/reference/forms/types/form.html#label) and [`label_format`](http://symfony.com/doc/current/reference/forms/types/form.html#label-format) properties of FormType fields.

The humanize filter is just the "most meaningful default" if you didn't provide either of those 2 properties explicitly. Taking it out of the templates is the wrong place to fix it, if the default isn't working you should just set the label or its format in the form type.

**Comment by sstok** [comment]
FYI, this is happening because the humanize filter assumes each upper case letter is a new word.

**Comment by curry684** [comment]
Status: works for me

**Comment by curry684** [comment]
> If using Standard template "form_div_layout.html.twig" for example I was wondering why all my upper-case labels are strange whitespaced.

Completely offtopic by the way on this subject: your code should not be enforcing the rendering of labels anyway. Use CSS rule `text-transform: uppercase` if you want to render something in all-caps.

**Comment by tholanger** [comment]
Autsch. You are right. Thanks for hinting. 
Not an "issue" anymore ;)
