### ISSUE TITLE
[Bug] Validator: Specify custom atPath to target children in a collection

### ISSUE THREAD

**Issue by jbdelhommeau** [symfony/symfony#22298]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.x

I raised a bug in validator component.
I try to build violation for a children in my collection and affect a custom path to target my specific child.

However, in this context the propertyPath inherit of basePath sufixed with '.data'. And this breaks the message of validation.

Exemple:

BasePath of violation path is :  ``` children[customers].data ```

AtPath: ```children[1].children[followupMailingList].data```

Final Violation path is: ``` children[customers].data.children[1].children[followupMailingList].data ```

The right final violation path sould be (without the .data of basePath):  ``` children[customers].children[1].children[followupMailingList].data ```

I fix it in a pull request: https://github.com/symfony/symfony/pull/22609

**Comment by xabbuh** [comment]
@jbdelhommeau Would you mean to create a small example project that makes it possible to reproduce your issue? As said in #22609 we cannot merge a form specific patch into the Validator component. But being able to reproduce your issue might allow someone to work on a proper fix.

**Comment by xabbuh** [comment]
Closing here due to the lack of feedback. We can consider to reopen if someone can provide a failing example project.
