### ISSUE TITLE
[WebProfiler] Race condition in Ajax requests

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22297]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

Following commit https://github.com/symfony/symfony/commit/2c053ee83dd54bbfff8edbc2fc2ce3d1bd35f664 there is now a race condition in the debug toolbar if an Ajax request is finished before the toolbar itself is loaded, as the new `finishAjaxRequest` function always assumes the DOM of the Ajax panel to be available:

> Uncaught TypeError: Cannot read property 'children' of undefined
    at finishAjaxRequest (new:140)
    at XMLHttpRequest.<anonymous> (new:140)

I only started running into this after optimizing my application with require.js, so it's a tight window to reproduce it, and it's in my specific case about 50% depending on network conditions and server load.

**Comment by curry684** [comment]
The culprit of the error is at https://github.com/symfony/symfony/blob/2c053ee83dd54bbfff8edbc2fc2ce3d1bd35f664/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L138, where the start of the request just bugs out if the web toolbar is not loaded. It's right after the `request.DOMNode` property has been set to the empty `tr` which has no children causing the error.

The trivial quick fix would be to test for the row being initialized in `finishAjaxRequests`, but it would leave the panel empty despite also showing a correct count of processed requests. The harder fix would include buffering the 'early' requests.

**Comment by apfelbox** [comment]
An implementation idea would be like Google Analytics implements their `ga` variable.

Start out with an array `window.ga = []` and later swap the global variable with an object implementiung a `push()` method.

**Comment by curry684** [comment]
Profiler already does that in `requestStack` local variable. I'm preparing a PR that processes any 'backlog' during the onSuccess of the toolbar load.
