### ISSUE TITLE
Parameters in URL are ignored

### ISSUE THREAD

**Issue by collierscott** [symfony/symfony#22301]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

Parameters being passed in the url seem to be ignored. 

This is prevents viewing different panels in the profiler so that only the "Request/Response" panel is ever shown regardless of the panel values.

Example Urls:

- http://example.local/app_dev.php/_profiler/8a1189?panel=logger
- http://example.local/app_dev.php/_profiler/8a1189?panel=router

It also prevents impersonating users.
- http://example.local/app_dev.php/admin/blog?_switch_user=thomas

I have checked ``php bin/symfony_requirements`` and there are no issues there.

System Info:
- Docker 17.03.1 running on mac

Docker Container Info:
- PHP-FPM Container
    - Base image from Dockerhub:  php:7.1-fpm
    - Debian:jessie
    - PHP 7.1.2
    - Zend Engine v3.1.0
    - Xdebug v2.5.1
    - Zend OPcache v7.1.2

- NGINX Container
    - NGINX 1.10.2
    - Using configuration found here:  http://symfony.com/doc/current/setup/web_server_configuration.html

Have also ran composer update and same problem using Symfony version 3.2.7.

Attached is a dump of the request object:

[request_dump.txt](https://github.com/symfony/symfony/files/896367/request_dump.txt)

**Comment by apfelbox** [comment]
Just to be sure:

You have the `$is_args$args` here?

```conf
try_files $uri /app.php$is_args$args;
```

**Comment by collierscott** [comment]
Just built Docker containers on Windows machine and everything is working as expected. I am going to rebuild on Mac tomorrow and close if everything is working.

**Comment by collierscott** [comment]
Just rebuild containers on Mac. Same issues. 

But, code is working in Docker containers on a Windows machine and on a Mac using MAMP. So, this is not  a Symfony issue. Closing.
