### ISSUE TITLE
Breaking Change introduced in Symonfy Filesystem

### ISSUE THREAD

**Issue by Loilo** [symfony/symfony#22328]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.7

Commit d50ffa1de7e0474024147b68b69db9b036d5b70d introduced a breaking change to Filesystem's `makePathRelative` method.

Previously, running
```php
$fs->makePathRelative('a', 'b');
```
correctly resulted in `../a/`.

After the mentioned commit, running the same code now results in `./`, which is clearly not correct.

This case is not covered by the Filesystem tests since they seem to only test absolute paths.

Imho there should either be tests for relative paths or it should be mentioned in the documentation that the `makePathRelative` method is only for absolute paths (which I don't assume).

**Comment by ausi** [comment]
I already created a pull request for this issue: #22321

**Comment by ausi** [comment]
> Previously, running `$fs->makePathRelative('a', 'b');` correctly resulted in `../foo/`.

I think it resulted in `../a/` not `../foo/`.

**Comment by Loilo** [comment]
I'm sorry. My local test code for this was `$fs->makePathRelative('foo', 'bar')`. Fixed that.

**Comment by Loilo** [comment]
I guess I can close this then in favor of #22321.
