### ISSUE TITLE
[Form] Checkbox default value (checked) is not included in prototype when using CollectionType.

### ISSUE THREAD

**Issue by idybil** [symfony/symfony#22320]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

I have a form which use a CollectionType like this:

``
         ...
            ->add(
                'x',
                CollectionType::class,
                array(
                    'entry_type' => XType::class,
                    'label' => false,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'by_reference' => false,
                    'error_bubbling' => false,
                )
            );
``

The entity that reference the XType has a Boolean field which is initialized to true:

``
/**
 * @var Boolean
 * @ORM\Column(name="is_active", type="boolean", nullable=false)
 */
 protected isActive = true;

``

When the data-prototype is generated in my Twig template, it does include the value="1" but it does not include the "checked=checked" attribute for the isActive field like it normally does for form field not in a collection.

``
data-prototype="&lt;div class=&quot;collection-item&quot;&gt;&lt;div&gt;&lt;label for=&quot;x___name___isActive&quot;&gt;Is active&lt;/label&gt;&lt;input type=&quot;checkbox&quot; id=&quot;x___name___isActive&quot; name=&quot;x[__name__][isActive]&quot; value=&quot;1&quot; /&gt;&lt;/div
``

I'm I missing something or is it a bug ?

Thanks

**Comment by GustavoDalPont** [comment]
I'm assuming you have and entity A, that has a collection of X and in both of these, data_class is set correctly.

When you're using a collection, the default prototype_data always will be null, as stated here: http://symfony.com/doc/current/reference/forms/types/collection.html#prototype-data. If you want to use an instance of a object as prototype data you have to pass it like this:

```
$builder->add('x', CollectionType::class, array(
    'entry_type' => XType::class,
    'label' => false,
    'allow_add' => true,
    'allow_delete' => true,
    'by_reference' => false,
    'error_bubbling' => false,

    'prototype_data' => new X(),
));
```

**Comment by idybil** [comment]
@GustavoDalPont Thanks for your time, it is working perfectly. I'm closing this since no more issue.
