### ISSUE TITLE
Strange error message with Symfony-2.8

### ISSUE THREAD

**Issue by pblr** [symfony/symfony#22327]
Hi,

I am using Symfony 2.8.18. I was always able to debug the previous error messages I had. Everything worked perfectly before. I restarted my local apache server and get the following error message:

> Warning: class_implements(): Class �]� does not exist and could not be loaded

Here is a link to the screenshot of the message: https://i.stack.imgur.com/W4AEc.png

I deleted the cache by removing the corresponding folders and by using the following command:

`php app\console doctrine:cache:clear-metadata && php app\console doctrine:cache:clear-query && php app\console doctrine:cache:clear-result`

But it did not solve my problem. I do not know how to understand this error message.
Do you have any ideas on how to debug the code?

**Comment by sstok** [comment]
It seems one of your files is corrupted, please remove the vendor folder and run composer install again.

Which PHP versions are you using?

**Comment by pblr** [comment]
I am using PHP 7.1.1. I made what you said and it works. Thank you very much. I close the issue.

**Comment by Lajdak** [comment]
I had the same problem on 2 different PC's. First with win 7, second with win 10. Here is link to stack https://stackoverflow.com/questions/43867959/symfony-randomly-crash-debugclassloader-php. I can't resolve it so i working an 2-4x of day i must just restart apache, press f5 and it working again.

**Comment by nicolas-grekas** [comment]
The SO page invites to increase the `realpath_cache_size`, strange. Might be a PHP bug.
ping @jpauli

**Comment by jpauli** [comment]
That's a PHP bug.  Please, upgrade PHP to the latest version, and check if the bug is always triggerable. It may have been fixed in between (PHP 7.1.1 is very old)
