### ISSUE TITLE
[TwigBundle] Logs tab broken in new exception view

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22335]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

If i look at the logs in the profiler, it performs rich expansion of the message parameters, including fancy popups to dig deeper.

In the exception view I get a long list of *'Notified event "{event}" to listener "{listener}"'*. Far from interesting or useful hehe.

It should act the same as the profiler view methinks, or at least replace the parameters to make it readable.

**Comment by javiereguiluz** [comment]
Please paste a screenshot to better understand the problems. Thanks!

**Comment by curry684** [comment]
![errorlog](https://cloud.githubusercontent.com/assets/1455673/24796963/9d2d2194-1b8f-11e7-8717-f3c59c62c7e1.png)

**Comment by chalasr** [comment]
Status: reviewed
See #22393
