### ISSUE TITLE
[FrameworkBundle][DX] ControllerNameParser does not handle invokable controllers

### ISSUE THREAD

**Issue by BPScott** [symfony/symfony#22338]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-dev

Invokable controllers are coming! In routing config they're already addressable using a FQCN e.g. in a routing YAML:
```yaml
home:
    path: /home
    defaults: { _controller: AppBundle\Controller\HomeController::__invoke }
```

And when #22330 is merged we can drop the __invoke:

```yaml
defaults: { _controller: AppBundle\Controller\HomeController }
```

---

When defining routes it would be good to to also support invokable controllers using the shorter colon-based syntax. Currently the ControllerResolver / ControllerNameParser can't handle these two cases:

```yaml
defaults: { _controller: AppBundle:Home:__invoke }
```

fails as it resolves to `AppBundle\Controller\HomeController::__invokeAction` which doesn't work for obvious reasons.  Fixing this would be a case of not transforming __invoke into __invokeAction in the [ControllerNameParser](https://github.com/symfony/symfony/blob/549af739af1639b3bb1bb52314226565d5612a46/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php#L78-L80).

```yaml
defaults: { _controller: AppBundle:Home }
```

Fails as this format doesn't get passed into the ControllerNameParser to be parsed in the [ControllerResolver](https://github.com/symfony/symfony/blob/549af739af1639b3bb1bb52314226565d5612a46/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L47-L50) so thus results in a `ServiceNotFoundException`. 

### Expected Behaviour

Both `AppBundle:Home` and `AppBundle:Home:__invoke` should resolve to invoking `AppBundle\Controller\HomeController`.

(This ticket was spun out from comments on #22202).

**Comment by iltar** [comment]
When using `AppBundle:Home:__invoke` as notation, it will try to match  `HomeController::__invokeAction`, which is obviously not possible. This is simply how the controller name parser works for that particular notation. [ControllerNameParser.php#L79](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php#L79)

With the `AppBundle:Home` notation, it will try to fetch the `AppBundle` service and call the `Home` method, and will therefore not work.

I don't think this is something easily fixable.

**Comment by mvrhov** [comment]
However if you register the controller as a service then it works out of the box.

**Comment by chalasr** [comment]
The parser has never advocated to support a short `a:b` notation for invokable controllers. Actually, this is a new feature, not a bug.

**Comment by mvrhov** [comment]
All I'm saying is that register the controller as service if you want to use `AppBundle\Controller\HomeController` as this works

**Comment by chalasr** [comment]
As long as it has no mandatory constructor arg, `_controller: AppBundle\Controller\HomeController` actually works without registering the controller as a service (see https://github.com/symfony/symfony-docs/pull/6951)

**Comment by BPScott** [comment]
> About fixing support for `AppBundle:Home:__invoke()`, not sure it's relevant. The `c` of the `a:b:c` is known to represent an action that must be suffixed by Action for being parsed.

Agreed, thinking since I originally raised this, supporting `AppBundle:Home:__invoke()` isn't a good idea for the reason you raised - `c` always maps to `cAction` and there is no need to special case this.

My original thought was it might have been worth having symmetry with defining routes as `FQCN` and `FQCN:__invoke` but tbh there's no point using `FQCN:__invoke` as `FQCN` is shorter, more readable and more inline with what I'd expect anyway given that you're referencing a callable and `FQCN:__invoke` is a magic method rather than a thing you actually call.

I still think aliasing `AppBundle:Home` to `AppBundle\Controller\HomeController` would be a good idea as that's 20 chars of boilerplate that could be removed, even though these days I'm leaning towards controllers as services and using the FQCN as an explicit mapping.

**Comment by BPScott** [comment]
Closing this, as in retrospect it's not needed given that 4.0 and Flex shall be moving away from having an AppBundle so most common use-case for this shall die, along with FQCNs as controller names being pushed as best practice over over the colon notation anyway.
