### ISSUE TITLE
[DX] [TwigBundle] Call stack does not expand intuitively

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#22334]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

The new error templates are really cool and pretty, but do introduce some new features that expose shortcomings that were already in the old one, but less noticeable.

Consider calling `$this->denyAccessUnlessGranted('bullcrap');` in a controller. This throws an `AccessDeniedException`, which is translated into an `AccessDeniedHttpException` by the framework. The exception template then flattens the exception stack, expands the first one and looks for non-`/vendor/` code there to expand. Not finding any, as it's an internal rethrow.

So this leaves the developer staring at a screen full of completely irrelevant call stack, just a plain "Access Denied" message on top, and 1000+ pixels down a collapsed block for the inner exception, where the interesting line of code is actually already expanded, its parent just isn't.

The screen would, for cases like this, be much more developer friendly if it just left the first exception collapsed, as it contains no userland code, and just expanded all exceptions that do. It would probably be a fine rule to just expand all exceptions that *have* userland code. Only if none of the exceptions have userland code should the first one be expanded by default (as that implies a framework bug or config error).

@javiereguiluz thoughts?

**Comment by javiereguiluz** [comment]
I agree ... but keep in mind that this is not because of the redesign. We simply changed the style of the exception pages, so the contains remain the same as before. I don't know if it's possible, but we should do a better job displaying first the real exception: the one that you can fix with your own code.

Meanwhile, I'll try to do what you say ... if a trace contains only vendor code, don't collapse it by default. But this won't be easy because Twig is not designed to do this business logic in a simple way.

**Comment by curry684** [comment]
I tried the scenario on 3.2, and it's less of a nuisance there because it actually keeps both call stacks collapsed initially. Both are not really useful in this situation though.

I had a look at implementing the change, and it's indeed not trivial in Twig but certainly doable. I would maybe prefer to introduce some extra functionality on `FlattenException` to ease the implementation. I'll be happy to have a go if we agree the suggested solution is the way to go.

**Comment by stof** [comment]
@javiereguiluz I think what we could do is that if we don't find any non-vendor code in the trace of the first exception, we would expand the next one and look for non-vendor code in it.

We cannot just reverse the order of exception to display the inner one first, as this would hurt DX in most cases (as wrapping exceptions is often adding more details. For instance, in the case of Twig, it points to the template location of the code triggering the exception).

**Comment by curry684** [comment]
An added complexity is that rethrows always share a large portion of the base call stack between the exceptions. It could be hard, for example when exceptions occur in callbacks from external libraries, to highlight the correct root cause. Hence my proposal to just expand every exception that *has* userland code, to the first hit of userland code. 100% DX is likely impossible here, but we should shoot for 99%.

**Comment by curry684** [comment]
See attached commit, I still need to review it later this weekend but it should solve all issues. Also incidentally fixes a discrepancy in the old code that would consider anonymous functions user code even though they can't be expanded.
