### ISSUE TITLE
Browserkit back should not go back to URLs that redirect 

### ISSUE THREAD

**Issue by willemstuursma** [symfony/symfony#22336]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

When using `BrowserKit`, the back function behaves differently from a real browser such as Chrome.

In a real browser, redirects are ignored when going back. In this driver, redirect are not ignored and instead followed again.

Imagine the following requests made with a browser or this driver:

1. http://www.example.org/1 [http 200]
2. http://www.example.org/2 [http 302 => http://www.example.org/3]

A browser and this driver will now be at http://www.example.org/3. 

Clicking back in the browser would take me back to http://www.example.org/1. Using `back()` in BrowserKit will take me back to http://www.example.org/2, and then again to http://www.example.org/3. 

I'm a bit new to this browser stuff, so I hope this is the right place to report this issue. Let me know if it is unclear.

**Comment by sstok** [comment]
See #22341

**Comment by curry684** [comment]
See https://github.com/symfony/symfony/pull/22341#issuecomment-292773809, it's a bug with BC break.
