### ISSUE TITLE
[DI] Cannot instantiate abstract class

### ISSUE THREAD

**Issue by pierredup** [symfony/symfony#22345]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-dev

When defining a service without the `class` config, and that has an abstract parent, I'm getting the error `Cannot instantiate abstract class ...`

Class definitions:

```php
abstract class AbstractTestService {}

class TestService extends AbstractTestService { }
```

This is the service definition:

```yaml
AppBundle\AbstractTestService:
    abstract: true

AppBundle\TestService:
    parent: AppBundle\AbstractTestService
```

Whenever I try to use the `AppBundle\TestService` service, I'm getting the above mentioned error.

This config however works, when I add the `class` option to the `TestService` definition

```yaml
AppBundle\AbstractTestService:
    abstract: true

AppBundle\TestService:
    class: AppBundle\TestService
    parent: AppBundle\AbstractTestService
```

**Comment by pierredup** [comment]
I see the comment on the original PR #21133:

> deals with ChildDefinition (which should not have this rule applied on them)

which makes me curious, why should this rule not be applied to child definitions?

**Comment by Nek-** [comment]
I confirm this issue. But the class is usually loaded by the FileLoader... So to me, it's more a FileLoader issue. Here is a test that confirms it:

```patch
From a6eaca5c459b69396ad4b186bfbd529d08bbb9e8 Mon Sep 17 00:00:00 2001
From: "Nek (Maxime Veber)" <nek.dev@gmail.com>
Date: Sun, 9 Apr 2017 15:44:40 +0200
Subject: [PATCH] Add test for abstract service with FQCN as id

---
 .../Tests/Fixtures/AbstractTestService.php             | 18 ++++++++++++++++++
 .../Tests/Fixtures/ExtendsAbstractTestService.php      | 18 ++++++++++++++++++
 .../Tests/Fixtures/yaml/class_id_child.yml             |  5 +++++
 .../Tests/Loader/YamlFileLoaderTest.php                | 10 ++++++++++
 4 files changed, 51 insertions(+)
 create mode 100644 src/Symfony/Component/DependencyInjection/Tests/Fixtures/AbstractTestService.php
 create mode 100644 src/Symfony/Component/DependencyInjection/Tests/Fixtures/ExtendsAbstractTestService.php
 create mode 100644 src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/class_id_child.yml

diff --git a/src/Symfony/Component/DependencyInjection/Tests/Fixtures/AbstractTestService.php b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/AbstractTestService.php
new file mode 100644
index 0000000..2f8ba89
--- /dev/null
+++ b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/AbstractTestService.php
@@ -0,0 +1,18 @@
+<?php
+
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
+
+
+abstract class AbstractTestService
+{
+
+}
diff --git a/src/Symfony/Component/DependencyInjection/Tests/Fixtures/ExtendsAbstractTestService.php b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/ExtendsAbstractTestService.php
new file mode 100644
index 0000000..f7275ec
--- /dev/null
+++ b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/ExtendsAbstractTestService.php
@@ -0,0 +1,18 @@
+<?php
+
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
+
+
+class ExtendsAbstractTestService extends AbstractTestService
+{
+
+}
diff --git a/src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/class_id_child.yml b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/class_id_child.yml
new file mode 100644
index 0000000..a52e85a
--- /dev/null
+++ b/src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/class_id_child.yml
@@ -0,0 +1,5 @@
+services:
+    Symfony\Component\DependencyInjection\Tests\Fixtures\AbstractTestService:
+        abstract: true
+    Symfony\Component\DependencyInjection\Tests\Fixtures\ExtendsAbstractTestService:
+        parent: Symfony\Component\DependencyInjection\Tests\Fixtures\AbstractTestService
diff --git a/src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php b/src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php
index 8e4732f..e9bd328 100644
--- a/src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php
+++ b/src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php
@@ -25,6 +25,7 @@ use Symfony\Component\Config\Resource\DirectoryResource;
 use Symfony\Component\Config\Resource\FileResource;
 use Symfony\Component\DependencyInjection\Tests\Fixtures\CaseSensitiveClass;
 use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\DependencyInjection\Tests\Fixtures\ExtendsAbstractTestService;
 use Symfony\Component\DependencyInjection\Tests\Fixtures\Prototype;
 use Symfony\Component\DependencyInjection\Tests\Fixtures\NamedArgumentsDummy;
 use Symfony\Component\ExpressionLanguage\Expression;
@@ -566,6 +567,15 @@ class YamlFileLoaderTest extends TestCase
         $loader = new YamlFileLoader($container, new FileLocator(self::$fixturesPath.'/yaml'));
         $loader->load('anonymous_services_in_parameters.yml');
     }
+
+    public function testChildWithClassAsIdServices()
+    {
+        $container = new Containerbuilder();
+        $loader = new YamlFileLoader($container, new FileLocator(self::$fixturesPath.'/yaml'));
+        $loader->load('class_id_child.yml');
+
+        $this->assertSame($container->getDefinition(ExtendsAbstractTestService::class)->getClass(), ExtendsAbstractTestService::class);
+    }
 }
 
 interface FooInterface
-- 
2.7.4
```

Status: Reviewed

**Comment by pierredup** [comment]
It's not an issue with loading the class, the issue is with [Symfony\Component\DependencyInjection\Compiler\ResolveClassPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php) which sets the class on the definition if you don't provide the `class` config and the service id matches a class name, but it skips any `ChildDefinition`. Then in [Symfony\Component\DependencyInjection\Compiler\ResolveDefinitionInheritancePass#L58-L60](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionInheritancePass.php#L58-L60) if the definition doesn't have a class, it maps the class name to the parent class which is what then gets dumped in the compiled container.

To fix the issue, the `ChildDefinition` should not be skipped when resolving class names, but in the original PR it looks like it is done intentionally. I'll create a PR to fix this, but first want to understand what the intention behind it was and if it indeed needs fixing.

/cc @nicolas-grekas

**Comment by Nek-** [comment]
The problem is that filling classes of any `ChildDefinition` in the `ResolveClassPass` is a serious BC break. A quick (and ugly?) fix may be to simply check if the id is a FQCN.

**Comment by pierredup** [comment]
It's not really a BC break, since that class was only introduced for version 3.3 which hasn't been released yet.

> A quick (and ugly?) fix may be to simply check if the id is a FQCN.

That is exactly what the `ResolveClassPass` does, just not for any `ChildDefinition` classes

**Comment by Nek-** [comment]
I was meaning something like that:

```php
<?php

if ($definition instanceof ChildDefinition && !class_exists($id)) {
    continue;
}
```

**Comment by nicolas-grekas** [comment]
I don't know what would be the best here.
In 3.2, when the class is missing from a child definition, it means the class should be inherited from the parent.
This current logic is aligned to that preexisting behavior.
Let take the following:
```yaml
AppBundle\TestService:
    abstract: true

AppBundle\TestService_child1
    parent: AppBundle\TestService
```

There, your requirement does not apply and it would be wrong to fill the class of the child with "AppBundle\TestService_child1".

The only technical thing we can rely on to decide between both situations would be a `class_exists` check. But that would make the configuration context-sensitive (ie config means something else depending on some info that is not in the config itself), which is a no-go to me in this case.

So, DX wise, we have to decide which behavior is the most friendly:
- always set this "class" when an id looks like a class (as you were expecting is to do)
- always skip "class" population for ChildDefinition (as history would tell and currently implemented)

Both approaches have unexpected behaviors: the description of this PR on one side, and the above example otherwise.

If we go your way, we should recommend to use "dots" in all non-class ids, so that the ambiguity shown in my example is resolved.

Any opinion here?

**Comment by pierredup** [comment]
> In 3.2, when the class is missing from a child definition, it means the class should be inherited from the parent.

I didn't know that, as I haven't used child definitions until recently.

Probably a bit ugly solution, but what if we handle it in the compiled container? We keep a reference of the parent class and the service id if it matches a class name. Then in the compiled container we can do the `class_exists` call and fall back to the parent class if it fails?

**Comment by pierredup** [comment]
Alternatively I think the functionality can stay as-is currently, and just documented that this won't work for child services.

**Comment by nicolas-grekas** [comment]
I think I've found an acceptable middleground, see #22362.

**Comment by backbone87** [comment]
Couldnt this be solved at least in XML? I think this was discussed before, when decision was made whether class should be derived from id (like now) or vice versa.
