### ISSUE TITLE
bug: Form: prototype doesnt support relations

### ISSUE THREAD

**Issue by mark-netants** [symfony/symfony#22349]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.2.6 & 3.2.7

After upgrading an (old) sf 2.3 project to 3.2 the form do not render correctly.
All fields are now rendered as a text field box. Even the relations which were displayed as a select in 2.3.

Example:

entity1: hasMany: entity2
entity2: hasMany: entity3

Displaying the forms separately works fine, but when using the data-prototype the fields of these relations are shown as a text field. This was working fine in 2.3.

**Comment by iltar** [comment]
Have you upgraded to 2.8 before going to 3.x?

**Comment by mark-netants** [comment]
This procedure 2.3 -> 2.6 -> 2.8 -> 3.x

**Comment by iltar** [comment]
Can you share your form type?

**Comment by mark-netants** [comment]
// OrderType
`public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class, array(
                'entry_type' => OrderItemType::class,
                'label' => 'items',
                'allow_add'    => true,
                'allow_delete' => true,
                'prototype' => true,
                'by_reference' => false
            ))
        ;
    }`

// OrderItemType
` public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity')
            ->add('unit_price')
            ->add('tax_percentage')
            ->add('isRecurring')
            ->add('recurringFrom', DateType::class, [
                'widget' => 'single_text',
                'format' => 'dd-MM-yyyy',
                'attr' => [
                    'class' => 'form-control input-inline datepicker',
                    'data-provide' => 'datepicker',
                    'data-date-format' => 'dd-mm-yyyy'
                ]])
            ->add('product')   // <<== this is the join which "breaks" on sf3+
        ;
    }
`
When displaying this form on sf2.3 the product line is shown as a dropdown/select.
When displaying this form on sf3.2 the product line is shown as a text box.

When directly showing OrderItemType the product line is shown as a select even on sf3.2

**Comment by iltar** [comment]
Can you put your code between 3 backticks on a new line?

**Comment by mark-netants** [comment]
I've edited the post above. If still unclear i could create a public repo which demo's the problem ?

**Comment by iltar** [comment]
If I understand it correctly, it's about the `product`, but this one does not declare a form type? Maybe in 2.3 it tried guessing, but that doesn't happen here. I think you'll have to explicitly define it. Can you check if this works for you? http://symfony.com/doc/current/reference/forms/types/choice.html#example-usage

**Comment by mark-netants** [comment]
Will do!
Strange that it does work on OrderItemType (viewed separately)

**Comment by mark-netants** [comment]
I feel like a noob right now, but indeed defining the type and mapped entity fixed this issue.
Overlooked that product.
Thank you for your time, please close this issue as it is not an issue, just an error on my side...
