### ISSUE TITLE
[Process] Get stuck when run `ssh` with multiplexing

### ISSUE THREAD

**Issue by leo108** [symfony/symfony#22346]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

It works well with code:

```
$cmd='ssh root@xxx.com echo 1;';
$p = new Symfony\Component\Process\Process($cmd);
var_dump($p->run()); // returns 0 almost immediately
var_dump($p->getOutput());
```

But it gets stuck with code:

```
$cmd='ssh -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux root@xxx.com echo 1;';
$p = new Symfony\Component\Process\Process($cmd);
var_dump($p->run()); // doesn't return anything
```

and it throws an error after 1min:

```
Symfony\Component\Process\Exception\ProcessTimedOutException with message 'The process "ssh -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux root@xxx.com echo 1;" exceeded the timeout of 60 seconds.'
```

**Comment by pierredup** [comment]
I'm unable to reproduce this error. Did you try the command with different hosts? Could it be a SSH config error on your host or remote machine?

**Comment by leo108** [comment]
@pierredup I found it works on my Mac, but not on my vagrant boxes neither my aws server, php in my Mac is 5.6.30, I have two vagrant virtual machines, one is php-5.6.21@centos6.7, the other is php7.1.0@ubuntu16.04.1, my aws server is php7.1.3@ubuntu16.04.2

**Comment by leo108** [comment]
I have tested some other servers, they both not working.

| System | PHP | Works? 
| --------|------|-------
| Centos 6.8 | 5.6.21 | no 
| Centos 6.7 | 5.6.21 | no 
| Centos 6.8 | 7.1.0 | no 
| Ubuntu 16.04.2 | 7.1.3 | no 
| Ubuntu 16.04.1 | 7.1.0 | no 
| macOS 10.12.4 | 5.6.30 | yes

**Comment by pierredup** [comment]
Is that connecting from or to? I connected from a mac to a CentOS server, which worked fine. I'll be able to test from an ubuntu server tomorrow

**Comment by leo108** [comment]
@pierredup they all connect to the same one remote server

**Comment by leo108** [comment]
@pierredup any update?

**Comment by leo108** [comment]
https://github.com/deployphp/deployer/issues/1155#issuecomment-294709056
It's a [bug](https://bugzilla.mindrot.org/show_bug.cgi?id=1988) of openssh, it works after upgrade openssh to ^7.3p1.
