### ISSUE TITLE
ChoiceType cyclic dependency problem

### ISSUE THREAD

**Issue by andreyserdjuk** [symfony/symfony#22354]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.19

After [this](https://github.com/symfony/symfony/commit/fb4d8de5e4c99d074d6b8f67f9251671014a931b) commit the $options['options'] (i.e Options::offsetGet('options')) call cannot be used inside 'choices_loader' closure: it causes [cyclic dependency](http://stackoverflow.com/questions/43291951/sonatapagebundle-circular-dependancy-on-edit-create-page) problem in projects when 'choice_loader' closure makes internal call of Options::offsetGet('choices') like [sonata-project does](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Type/ModelType.php#L109).

**Comment by ersah123** [comment]
I can confirm for version 2.8.19. I'm using sonata project. In particular SonataPageBundle , when i click page to edit, i gives me this error.

Downgrading version to 2.8.18 fixes the problem for me.

**Comment by HeahDude** [comment]
The only way I see is to revert @stof commit.

**Comment by stof** [comment]
choice_loader making use of choices ? Why would you use both the choice_loader and the choices at the same time ? They are mutually exclusive in the ChoiceType. Is Sonata changing the meaning of the `choices` option ?

**Comment by Neodork** [comment]
Maybe wait till https://github.com/sonata-project/SonataAdminBundle/issues/4443 has been resolved.

**Comment by Cyrilovich** [comment]
Same for me !
Downgrading version to 2.8.18 fixes the problem...

**Comment by HeahDude** [comment]
The related issue has been fixed in Sonata, see https://github.com/sonata-project/SonataAdminBundle/pull/4445.

**Comment by Neodork** [comment]
Waiting for 3.17.0 release to confirm in production

**Comment by Neodork** [comment]
Can confirm, no cyclic dependency error getting thrown with:

![symfony](https://gyazo.com/dda0371b05756beb8e092cc7a0fe6cb1.png)
![sonata-admin](https://gyazo.com/730eb1180f222af39805e079369f4e34.png)

I think this can be closed.

**Comment by mrahmouni** [comment]
i confirm this resolve the problem

thanks
