### ISSUE TITLE
Certain text content changes the mime type of txt files.

### ISSUE THREAD

**Issue by MarkVaughn** [symfony/symfony#22363]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ~3.2

Some file uploads are failing due to .txt files not being recognized as text
*test.txt* `hello`
```
>>> Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser::getInstance()->guess('pathto/test.txt');
=> "text/plain"
```
test2.txt `HKF9-JX9RXE-U43A4X`
```
>>> Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser::getInstance()->guess('pathto/test2.txt');
=> "application/zlib"
```
Double checking with bash (osx)
```
$ file --mime-type pathto/test2.txt 
 pathto/test2.txt: text/plain
```

a few more tests:
- `HK` -> "application/zlib"
- `H` -> "application/octet-stream"

Expecting `text/plain`

**Comment by jordscream** [comment]
@MarkVaughn . I tried and I have no pb. Can you send me your exact file to jordan.samouh(at)gmail.com

**Comment by MarkVaughn** [comment]
Thanks @jordscream, sent you the files & a test file.

**Comment by Nek-** [comment]
You could attach it as zip to one of your messages !

**Comment by MarkVaughn** [comment]
Oh nice!
[test2.zip](https://github.com/symfony/symfony/files/913893/test2.zip)

**Comment by MarkVaughn** [comment]
@Nek- this is what I see
```
$ php test.php
FileBinaryMimeTypeGuesser supported 
FileinfoMimeTypeGuesser supported 
test.txt: application/octet-stream
test2.txt: application/zlib
test3.txt: application/zlib
```

**Comment by MarkVaughn** [comment]
After further digging I got this result for test 2 & 3 txt
- FileinfoMimeTypeGuesser guessed application/zlib
- FileBinaryMimeTypeGuesser guessed text/plain

**Comment by Nek-** [comment]
A point that may good to notice is that this is not an isolated case. For instance, MS Office document detection is a serious problem.

I think this issue may be related to this PR: https://github.com/symfony/symfony/pull/21985

**Comment by Simperfit** [comment]
What needs to be done here ?

**Comment by MarkVaughn** [comment]
Well I just reviewed my test file, now I'm on php 7.3 and the results have improved
```
echo FileBinaryMimeTypeGuesser::isSupported() ? "FileBinaryMimeTypeGuesser supported \n": "FileBinaryMimeTypeGuesser not supported \n";
echo FileinfoMimeTypeGuesser::isSupported() ? "FileinfoMimeTypeGuesser supported \n": "FileinfoMimeTypeGuesser not supported \n";
echo 'test.txt: '. MimeTypeGuesser::getInstance()->guess('test.txt') . "\n"; 
echo 'test2.txt: '. MimeTypeGuesser::getInstance()->guess('test2.txt') . "\n";
echo 'test3.txt: '. MimeTypeGuesser::getInstance()->guess('test3.txt') . "\n";
```
➜  test2 php test.php
```
FileBinaryMimeTypeGuesser supported
FileinfoMimeTypeGuesser supported
test.txt: application/octet-stream
test2.txt: text/plain
test3.txt: text/plain
```

So test.txt is just the capital letter H and nothing else, but the other longer ones are now recognized as text/plain. I'll check on an upgraded of Symfony early this week, and if it changed due to whatever development I'll close the issue (if it's solved)

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" in recent Symfony versions.

Running your script I got the same results:

```
FileBinaryMimeTypeGuesser supported
FileinfoMimeTypeGuesser supported
test.txt: application/octet-stream
test2.txt: text/plain
test3.txt: text/plain
```

Then I tried with the latest version of the new Mime component:

```php
require __DIR__.'/vendor/autoload.php';
use Symfony\Component\Mime\MimeTypes;

$mimeTypes = new MimeTypes();
echo 'test.txt: '. $mimeTypes->guessMimeType('test.txt') . "\n";
echo 'test2.txt: '. $mimeTypes->guessMimeType('test2.txt') . "\n";
echo 'test3.txt: '. $mimeTypes->guessMimeType('test3.txt') . "\n";
```

The result was the same:

```
test.txt: application/octet-stream
test2.txt: text/plain
test3.txt: text/plain
```

If I use the tools from the operating system:

```
$ file -b --mime test.txt
application/octet-stream; charset=binary
```

So, I'd say the results are now the expected ones ... and that's why we close this as "fixed". Thanks.
