### ISSUE TITLE
Serializer error 500

### ISSUE THREAD

**Issue by koukouille** [symfony/symfony#22360]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Hi, I actually use the Serializer. I try to serialize a complexe object including different objects and there is a circular reference. I try to catch it and then return only the Id of the object but it appear an error 500 this page doesn't work.
I tried to use the max_depth option but nothing work.

Can you help me ?

**Comment by fabpot** [comment]
You should use StackOverflow for support. We are using Github issues only for bugs and features. Thanks.
