### ISSUE TITLE
Wrong content of Form::getViewData() on forms whith children

### ISSUE THREAD

**Issue by sryabov** [symfony/symfony#22371]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7 (exists from 2.8 and may be early)

Code example (in controller):
```php
$form =  $this->createFormBuilder(null, [
        'csrf_protection' => false,
    ])
    ->add('e', \Symfony\Bridge\Doctrine\Form\Type\EntityType::class, [
        'class'     => 'AppBundle:Entity',
        'multiple'  => true,
    ])
    ->getForm()
    ->submit(['e' => [3, 180]])
;
```

as result $form->getViewData() is not plain array eq to sumbitted data but:
```
array:1 [▼
  "e" => ArrayCollection {#6289 ▼
    -elements: array:2 [▶]
  }
]
```

bug in Form::submit()
`
$viewData = $this->config->getCompound() ? $this->viewData : $submittedData;
`
[line 607](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Form.php#L607) initially takes viewData, but in processig children elements used PropertyPathMapper (for nested forms)
`
$this->config->getDataMapper()->mapFormsToData($childrenIterator, $viewData);
` 
[line 630](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Form.php#L630)
, which fill `$viewData` with Model Data
`
$this->propertyAccessor->setValue($data, $propertyPath, $form->getData());
`
[line 93](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php#L93) and as result in `$viewData` we have mixed content of View and Model Data

**Comment by HeahDude** [comment]
Hello @sryabov, thank you for opening this issue. I don't really get what's the issue here, it is expected that the view data keep the submitted data when it's invalid to it remains in the view while displaying errors.

**Comment by sryabov** [comment]
@HeahDude, sorry but [documentation](http://symfony.com/doc/current/form/data_transformers.html#about-model-and-view-transformers) is of a different opinion and me too =)
For example view data may be used for generate urls: `{{ path('abc', form.viewData)|merge({page: formviewData.page|default(0) + 1}) }}`

**Comment by HeahDude** [comment]
I've never seen that article about transforming an issue before 😱, I lacked the time to review everything among the lot of new stuff added in a recent update of the docs, thank you very much for this heads-up, I'm gonna deeply review it!

**Comment by HeahDude** [comment]
For your information, the view data has the request/view format only for simple forms, meaning they have options `compound` set to `false` and no child.

Any compound form has a view data in the format of the `data_class` option or an array, anything else would require a model transformer.

All the code you linked works as expected, this is a documentation issue.

**Comment by sryabov** [comment]
Hmm, but
```php
$normData = $this->viewToNorm($viewData);
```
[line 634](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Form/Form.php#L634) send to ViewTransformer mix of view data (from main form) and model data (from childern forms). Is it really expected?

**Comment by HeahDude** [comment]
>line 634 send to ViewTransformer mix of view data (from main form) and model data (from children forms). Is it really expected?

Yes it is :) for the reasons I've explained above.

To resume:
Simple form => view data == request data
Compound form => view data == (data_class | array) mapping children model data, using DataMapper.

**Comment by Isinlor** [comment]
@sryabov See my discussion with @HeahDude here: https://github.com/symfony/symfony/issues/20880#issuecomment-267129575

IMHO this is a bug, a big one, so big that I'm not sure if it can be changed. Maybe with release of Symfony Forms 2.0 :) .

**Comment by xabbuh** [comment]
@sryabov Can you explain which issue you try to solve (e.g. why do you nee to call `getViewData()` on your form?

**Comment by sryabov** [comment]
@xabbuh as simple example for generating query string to next page with all form data
```php
$data = $form->getViewData();
$data['page'] += 1;
$query = http_build_query($data);
```

**Comment by xabbuh** [comment]
If you want to do that, you will have to walk the form tree and only fetch the view data of its leafs as that's the data that will be sent when the user submits the form.

**Comment by sryabov** [comment]
@xabbuh and that's the problem.
In any case when I use method getViewData I expect receive View Data but receive mixed content. And this behavior is not described.

**Comment by HeahDude** [comment]
@sryabov Still this is expected as long as you don't use transformers the view data is the same as the model data, which is the more common case for compound forms:

when they use an object as underlining data, instead of transforming it to an array, the option `data_class` should be set, both to validate the format and create an instance if children needs to be mapped and there is no initial data (null).

I'll update the docs soon to better reflect that.

**Comment by calumbrodie** [comment]
This is a behaviour that has caused us issues too. We have the same use case as described above in that we have a form which drives a paginated set of data and the form data needs to be represented in a form suitable for paginating (within a URL), therefore we need the form view data fully transformed to viewData.

In our case, to work around this issue we had to choose between (a) refactoring nested forms into flat forms without nesting OR (b) manually walking the form building viewdata for each subform. I chose the former, but appreciate for others this won't be possible.

**Comment by HeahDude** [comment]
See https://github.com/symfony/symfony/issues/14514 for the same use case.

We should close here as this is unlikely to be changed, instead we should better document the view data handling.

**Comment by javiereguiluz** [comment]
@HeahDude closing, as you said. By the way, is this improvement in your TODO list or any open issue in Symfony Docs, or should we open a new issue to nor forget about it? Thanks!

**Comment by HeahDude** [comment]
TODO list ;). Trust me I can't forget about that one :D.
