### ISSUE TITLE
[Validator][GroupSequences] GroupSequences execute next group if first fail

### ISSUE THREAD

**Issue by chaos-drone** [symfony/symfony#22373]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.19

This issue appears when form is used without entity/data_class. Both groups "Basic' and 'Strict' are validated even if there are violations in 'Basic'. 

I also get the error: `The Symfony\Component\Validator\Constraints\GroupSequence::getIterator method is deprecated since version 2.5 and will be removed in 3.0. in Symfony\Component\Validator\Constraints\GroupSequence.php on line 107` which is caused in by Symfony\Component\Form\Extension\Validator\Constraints\FormValidator.php:(84)

The `Form` and `Validator` components are working standalone outside of symfony distribution, with all the dependencies also available.

Here is how the form is configured:

```
class MyType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add("name", null, [
                    "constraints" => new NotBlank(["groups" => ["Basic"]])
                ])
                ->add("phone", MyPhoneType::class, [
                    "constraints" => [
                        new NotBlank(["groups" => ["Basic"]]),
                        new PhoneNumber(["groups" => ["Strict"])
                    ]
                ])
                ->add("email", EmailType::class, [
                    "constraints" => [
                        new NotBlank(["groups" => ["Basic"]]),
                        new Email(["groups" => ["Strict"]]),
                    ],
                ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "validation_groups" => new GroupSequence(["Basic", "Strict"])
        ]);
    }
}
```

**Comment by gustavodpont** [comment]
Looking through the code
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L813

When mapping the constraints on the form, _$context->getViolations()_ is always an empty array, even when there's a violation. And mapping on the entity it come with one position.

**Comment by xabbuh** [comment]
It would be nice if one of you could upload an example project that one could just checkout and execute to try to reproduce your issue.

**Comment by gustavodpont** [comment]
Sure, https://github.com/gustavodpont/issue22373
URL: /my/new

On this example there's 2 constraints for property name, Length (min => 10, groups => Basic) and one Email (groups => Strict) and then the validation group is a GroupSequence (["Basic", "Strict"]), mapped on the Form.
When you put something like "abcd" on name, expected is "This value is too short. It should have 10 characters or more." without the "This value is not a valid email address.", but the 2 messages appears.

**Comment by chaos-drone** [comment]
@gustavodpont thanks! :)

**Comment by pedrocasado** [comment]
same with Symfony 3.3.2.

**Comment by HeahDude** [comment]
@gustavodpont Thanks a lot for this reproducer! I think I found a way to fix this.

Could you please give #23722 a look?
