### ISSUE TITLE
Impersonate Disabled User

### ISSUE THREAD

**Issue by bradbyu** [symfony/symfony#22381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.1

While testing disabling a user, I decided to try to impersonate the disabled user and found that you are able to impersonate the user as normal (as if they were never disabled). I expected the user should be disabled. Is this expected behavior?

When I log out, then try to log in as the disabled user, I am properly alerted that the account is disabled and am not logged in.

**Comment by dmaicher** [comment]
Currently indeed `$userChecker->checkPreAuth($user)` is not called to check if the user is disabled.

I added it in this branch: https://github.com/symfony/symfony/compare/2.7...dmaicher:fix-switch-user-if-disabled?expand=1

I'm not 100% sure though that the behavior was really not indented to be like this? I mean as a user that has the permission to switch to other users maybe its ok if he can also switch to disabled users?

So this should be discussed/clarified first then I can happily open the PR for it :blush:

**Comment by xabbuh** [comment]
I am not sure either. There may be good reasons why you need to switch to a disabled user.

**Comment by javiereguiluz** [comment]
This issue reports this "feature" as a bug ... but in #6306 they are asking us to add this "feature" to Symfony because it's missing. Which PR is wrong?

**Comment by stof** [comment]
@javiereguiluz #6306 was forgotten to be closed when we implemented the feature through another issue requesting it (we missed the fact that there were duplicate feature requests).
This issue is now asking to remove the feature

**Comment by craue** [comment]
@stof, could you point me to when/where this was implemented?

**Comment by Vinorcola** [comment]
:-1: for this. Being abble to impersonnate should be a feature reserved for top admin to check if there is no issue on the application for a specific user. The fact that the user is being disabled or not is not important here. Maybe an admin would like to check something on a disabled user before enable it back.

**Comment by noniagriconomie** [comment]
Not a bug here, we should be able to switch to any user
You have the event if needed to avoid switching in your app
Also we could add disabled: true/false in the user panel when switching to an other user

**Comment by jakzal** [comment]
👎 

I agree this is a feature, not a bug. Not being able to switch to a disabled account is more of an edge case and could always be implemented in user land. Doing it the other way around would be harder.

Voting to close.

**Comment by chalasr** [comment]
Agree.
