### ISSUE TITLE
Allow HttpFoundation v3.2 dependency on HttpKernel v2.8?

### ISSUE THREAD

**Issue by niels-nijens** [symfony/symfony#22391]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes?
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.19

We are currently using the HttpKernel component version 2.8 within a project. I would like to use HttpFoundation component version 3.2 to use the 'SameSite' cookie functionality.

Is it possible to extend the dependency requirement for the HttpKernel component version 2.8 to HttpFoundation component version 3.2?

**Comment by iltar** [comment]
What dependencies do you have that won't allow you to install 3.2? If so, maybe you could solve those?

**Comment by niels-nijens** [comment]
I had a problem installing HttpFoundation v3.2 alongside HttpKernel v2.8. It looks like I'm able to upgrade the HttpKernel component to 3.x after all. 😃

**Comment by stof** [comment]
Not allowing the full 3.x releases in 2.8 components was actually done on purpose. If you want to use new 3.2 features, the right solution is to upgrade to HttpKernel 3.2 too.

**Comment by xabbuh** [comment]
I agree with @stof. Therefore, I am closing here.

**Comment by niels-nijens** [comment]
I've been looking for some reference on why v3.1 is included and v3.2 is not, but could not find anything related to this. Thanks for clearing this up, @stof.

We've successfully upgraded to HttpKernel v3.x. Problem solved.
