### ISSUE TITLE
Upgrade note not clear about EventDispatcher

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#22402]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | -
| Symfony version  | 3.3.x-DEV

Upgrade 3.3 readme specify

```
EventDispatcher

The ContainerAwareEventDispatcher class has been deprecated. Use EventDispatcher with closure-proxy injection instead.
```

That is exactly the same message than on the class itself (`ContainerAwareEventDispatcher`) 
> @deprecated since 3.3, to be removed in 4.0. Use EventDispatcher with closure-proxy injection instead.

Maybe can you add an example on how to inject the `event_dispatcher` service in 3.3 that doesn't trigger this warning ?

Before: 
```xml
<service class="AppBundle\Manager\FooManager" id="app.manager.foo">
    <argument id="event_dispatcher" type="service"/>
</service>
 ```

After: ?

**Comment by chalasr** [comment]
Injecting the `event_dispatcher` as before is just fine. 
This note is relevant for people actually relying on the `ContainerAwareEventDispatcher` class, not the `event_dispatcher` service.

What has been changed is how event subscribers/listeners are injected into the `event_dispatcher` service, that is done through `closure-proxy` arguments for lazyness, removing the need for the `ContainerAwareEventDispatcher` class (the `EventDispatcher` one is now used directly). 

This change should not involve anything regarding the use of events, subscribers/listeners are still registered as before using the corresponding tags.

**Comment by stof** [comment]
except if your constructor has a typehint on ContainerAwareEventDispatcher, of course. But this should not happen. you should always use EventDispatcherInterface as typehint

**Comment by tristanbes** [comment]
Ok thanks guys for explanation. I guess I got alarmed by Phpstorm inspection that highlighted in red the event_dispatcher service on my service definition with the deprecation message.

**Comment by hcomnetworkers** [comment]
Could you please use an alias service or something to prevent the event_dispatcher from being identified as deprecated?

![symfony_3 3_event_dispatcher_deprecated](https://cloud.githubusercontent.com/assets/15338688/26671787/138a3b40-46b7-11e7-9347-3898144f3d52.png)

This also confused me, leading me here.

**Comment by ricohumme** [comment]
Hi,

I am actually depending on the container in the eventdispatcher, but I can't seem to find an example on how to use the event dispatcher with the container. Can an example be provided on how to use correctly?

**Comment by asentner** [comment]
Bump. The notes were not clear. Will the ContainerAwareEventDispatcher class just be replaced? I typically wouldn't need it to be container aware as I inject it into a service anyways to use the addListener() method.

**Comment by stof** [comment]
Well, Symfony will change the class used for the service in 4.0 (using the normal EventDispatcher rather than its ContainerAwareEventDispatcher child).
We cannot make the change in 3.4, as it would be a BC break (people relying on methods of the child class when getting the `event_dispatcher` service would get a fatal error instead of a deprecation warning in a working method)

**Comment by stof** [comment]
I think the issue is related to the Symfony plugin here. Using deprecated classes should add a warning on the service definition only, not on the service retrieval. Service deprecation and class deprecation are independant
