### ISSUE TITLE
[Form] Expression validation constraint on form without a Data Class 

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#22403]
Hello,

When using form without a data class (see: http://symfony.com/doc/current/form/without_class.html), we are not able to use expression to access other fields data.

Only the `value` var seems to be filled.

If I try something like `this.firstName`, I am not able to access others fields values.

Is it normal?

**Comment by yceruto** [comment]
Yes, it's the normal behavior, without `data_class` there is no object instance in context (hence it's `null`).

However, in this case, you can to add the `Expression` constraint to root form and `value` will contain an array of your fields values:

For example:
```php
$form = $this
    ->createFormBuilder(null, [
        'constraints' => [
            new Expression([
                'expression' => 'value["firstName"] == "foo"'
            ])
        ]
    ])
    ->add('firstName')
    ->add('lastName')
    ->getForm();
```

**Comment by Seb33300** [comment]
This is what I am doing but I hoped there was another solution.

Maybe something like a `data` var which give an access to unmapped data (when `data_class` is not specified or for fields with `mapped` options is set to `false`).

**Comment by yceruto** [comment]
Maybe we talking about to pass a new value to expression context like the current `root` value from validator context, thus we have complete access to form instance (in this case), then, this would be possible (with or without `data_class`, accessing to unmapped fields too):
```php
$form = $this
    ->createFormBuilder()
    ->add('firstName', null, [
        'constraints' => [
            new Expression([
                'expression' => 'root["firstName"].getData() != root["lastName"].getData()',
            ])
        ]
    ])
    ->add('lastName')
    ->getForm();
```

**Comment by xabbuh** [comment]
It doesn't seem that there is much concern about adding something like the root form to the context of the ExpressionLanguage being used when validating a form. Thus, I am going to close here.
