### ISSUE TITLE
Session: set different lifetimes per user for PdoSessionHandler

### ISSUE THREAD

**Issue by pavarnos** [symfony/symfony#22413]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi. In my app, different types of users have different session timeouts. PdoSessionHandler::write() and ::getMergeStatement() get the session.gc_maxlifetime ini value and overwrites the lifetime in the database with the default value every time the session data is saved. Is there any way around this behaviour (other than creating my own version of the PdoSessionHandler?)

**Comment by Tobion** [comment]
Just call `ini_set('session.gc_maxlifetime')` with the user-dependent lifetime before calling session_save.

**Comment by pavarnos** [comment]
Thanks for the quick reply. Yes, i tried that. But the value gets overwritten on each request so i cannot set it once at login and forget it.

**Comment by Tobion** [comment]
If you don't want to set it on each session, then you need a custom session handler indeed.

**Comment by pavarnos** [comment]
Thanks. I wondered about changing
```php
$mergeSql = "INSERT INTO $this->table ($this->idCol, $this->dataCol, $this->lifetimeCol, $this->timeCol) VALUES (:id, :data, :lifetime, :time) ".
 "ON DUPLICATE KEY UPDATE $this->dataCol = VALUES($this->dataCol), $this->lifetimeCol = VALUES($this->lifetimeCol), $this->timeCol = VALUES($this->timeCol)";
```
to
```php
$mergeSql  = "INSERT INTO $this->table ($this->idCol, $this->dataCol, $this->lifetimeCol, $this->timeCol) VALUES (:id, :data, :lifetime, :time) " .
  "ON DUPLICATE KEY UPDATE $this->dataCol = VALUES($this->dataCol), $this->timeCol = VALUES($this->timeCol)";
```
in PdoSessionHandler::getMergeSql() to prevent subsequent session writes changing the lifetime value. (note that lifetime col is not updated in the second snippet above).

But I'm OK for now: have created my own handler for this. Thanks for the quick responses!
