### ISSUE TITLE
Request::getClientIp returns null when running in cli mode

### ISSUE THREAD

**Issue by miklcct** [symfony/symfony#22415]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Running 

    (new Symfony\Component\HttpFoundation\Request)->getClientIp();

from cli gets null which violates the PHPDoc saying it return string.

**Comment by xabbuh** [comment]
While this is true what is the point in asking for the client IP on the CLI where there is no HTTP request at all?

**Comment by miklcct** [comment]
I discovered the bug when a middleware calling this was added into the application stack and called in unit tests, and failed unexpectedly by throwing TypeError because I passed the result directly into a string argument.

**Comment by xabbuh** [comment]
The only thing we can do is to relax the return type in the docblock as there is no IP address we could return. So that would not really solve your issue.

**Comment by miklcct** [comment]
If the return type is correct I would have already handled the null case accordingly, so please modify the doc to reflect the reality.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
