### ISSUE TITLE
[Security] json_login tries to handle every request

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#22423]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3-dev

https://github.com/symfony/symfony/pull/18952

`UsernamePasswordJsonAuthenticationListener` seems to "high-jack" every request. While the documentation http://symfony.com/doc/master/security/json_login_setup.html seems to imply it supports things like `check_path` I do not see this in the code at all. It might make sense to extend from `AbstractAuthenticationListener`. At the very least the listener should check the `Content-Type` header if its a json request.

**Comment by chalasr** [comment]
duplicate of https://github.com/symfony/symfony/issues/21948.
I'm on it.

**Comment by chalasr** [comment]
See #22425
