### ISSUE TITLE
[Dependency Injection] Broken autowiring in 3.2.7

### ISSUE THREAD

**Issue by drscre** [symfony/symfony#22429]
The following code works in 3.2.6 but fails in 3.2.7

```php
class Class1 {
    function __construct() {}
}
class Class2 {
    function __construct(Class1 $class1) {}
}
class Class3 {
    function __construct(Class1 $class1) {}
}

$cls2 = new \Symfony\Component\DependencyInjection\Definition(Class2::class);
$cls2->setAutowired(true);

$cls3 = new \Symfony\Component\DependencyInjection\Definition(Class3::class);
$cls3->setAutowired(true);

$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();

$container->setDefinition('srv2', $cls2);
$container->setDefinition('srv3', $cls3);
$container->compile();

$container->get('srv3'); // :-(
```

This line is to blame
https://github.com/symfony/symfony/blob/v3.2.7/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L136

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

**Comment by nicolas-grekas** [comment]
Yep, it's fixed in the repos and will be part of the next release.
