### ISSUE TITLE
[Var-dumper] Expand all / collapse all

### ISSUE THREAD

**Issue by bilougit** [symfony/symfony#22437]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.*

Hi, I'm using `dump` every day and I'm very happy with it. However, every now and then, I want to display an array of objects for instance. Currently, all objects are collapsed til I click on the arrow of the object I want to check.
Is there anyway to expand all objects all at once? If not, it'd be great if there was a button `exand all` for instance to do that.

**Comment by nicolas-grekas** [comment]
CTRL+click on the arrow => done

**Comment by bilougit** [comment]
@nicolas-grekas It doesn't work for the version `2.6`, I upgrated to `3.7` and it works now.
 thanks!

**Comment by stof** [comment]
@bilougit 2.6 is unmaintained anyway.

**Comment by bilougit** [comment]
Oops, sorry I didn't realize it, @nicolas-grekas what you suggested (`CTRL+click`) expands only the object/array and all objects/arrays inside it, **not its siblings**...

**Comment by stof** [comment]
@bilougit do it one level higher

**Comment by bilougit** [comment]
@stof yes I'm aware of that :D,  however it'd be better if I didn't have to do it
```php
dump(array($myObj));
```

**Comment by stof** [comment]
well, you should not need. Object nodes are also collapsible

**Comment by bilougit** [comment]
@stof my previous comment does not make any sense .. sorry about that... What I wanted to say is to make it possible to collapse/"uncollapse" something like this (all at once of course):
```php
// file1.php line 200
dump($myObj1);
// file1.php line 250
dump($obj);
// file2.php line 150;
dump($array);
// etc ....
```

I agree that it's not too important but IMO it'd be nice to have.

**Comment by SeanCarrington** [comment]
Thanks @nicolas-grekas
