### ISSUE TITLE
[EventDispatcher] Before and after dispatch event

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#22438]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

This is a proposal to add two events to be dispatched by eventDispatcher

- event_dispatcher.before_dispatch
- event_dispatcher.after_dispatch

If it sounds like a good idea, I can develop my implementation proposals.

**Comment by fabpot** [comment]
What would be the use case of such generic events? In any case, that would add a lot of overhead. I'm 👎 on such an addition.

**Comment by sstok** [comment]
I can imagine live cycle events for some listener related systems (like a Domain Command handler), and that's actually useful and acceptable.

But dispatching events while listen to events? This is so weird I could not resist myself making a meme 😐

![76614294](https://cloud.githubusercontent.com/assets/904790/25046887/2352840e-2134-11e7-9ced-62e38756ab66.jpg)

**Comment by curry684** [comment]
I'm just left wondering how the main event were ever going to happen after dispatching before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events before the before_dispatch events etc.

**Comment by theofidry** [comment]
Hey, ok this is a bad idea but let's not bash/troll people for that :)

**Comment by fabpot** [comment]
@theofridy is right. I'm closing and locking this conversation.

**Comment by javiereguiluz** [comment]
@skafandri if you got upset by the above comments, we apologize. We're sure that they weren't ill-intentioned to mock your proposal, so please, keep contributing your ideas to the Symfony project. Thanks!

**Comment by xabbuh** [comment]
By the way, if you really need something like that, you can decorate the event dispatcher and do what you need there before and after delegating the event to the decorated dispatcher.
