### ISSUE TITLE
[DX] implement a fake dump for prod environment

### ISSUE THREAD

**Issue by m47730** [symfony/symfony#22433]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

I'm very addicted to dump() to debug my code and i find it a invaluable tool, so thank you very much!
Unfortunately some time i forget to rid off of a dump or two in the code and if the code bump into production i got an exception because dump() does not exists.

I understand this should not happen and i should get more controls in place, but it happens; so my proposal: why not create a fake dump() function for production environment that does absolutely nothing?

Regards,
Matteo

**Comment by curry684** [comment]
Whilst TwigBundle does this it is in a better position to do so as its calls to `dump` are compiled away to nothingness. For the global `dump` function it means incurring CPU and IO load to all Symfony users on every project. I don't think that's a good idea for something that should, realistically, not be happening.

I suggest if you have issues with this you simply define the function in your own front controller:
```
if (!function_exists('dump')) {
  function dump($var) {
    @trigger_error('We left a dump call in the code that should have been removed before release', E_USER_WARNING);
  }
}
```

**Comment by theofidry** [comment]
Another way is to lint your code in the CI or something

**Comment by m47730** [comment]
@curry684 Sorry i don't get the "CPU and IO load" aspect, but probably for my lack of knowledge of symfony internals.
The global dump needs to be precompiled, of course, but the overhead of resulting file would be neglectable for basically a oneliner function. On the execution phase, instead, i don't get the downside because the function is never called if someone did his homework.

As i said, i understand that leave a dump is not a best practise, but it's similar to app_dev.php file where a basic authorization mechanism is in place. Why? app_dev.php should never be in production. Yes. But bad things happen and sometimes an additional safety belt it's better.

Also i think this improves the developer life. Basically now you have to choose to group all of your dumps into various "if env == dev" or you have to delete all dumps before committing (and maybe put them in place again if another bug pops out).
With a blank dump i can leave all my debug info in the code without hurting anyone (in my opinion the speed change will be near zero), it's a bit inelegant but improves the workflow.

Regards,
Matteo

**Comment by curry684** [comment]
> Sorry i don't get the "CPU and IO load" aspect

Loading a file with a function that is only being used by you costs CPU cycles and IO load.

**Comment by iltar** [comment]
You should probably start doing code reviews, this would've been discovered. This is not a problem with the production environment of Symfony in my opinion.

**Comment by nicolas-grekas** [comment]
As explained, this is done on purpose. You need a code linter or a better review process instead :)

**Comment by m47730** [comment]
Of course i think is a review process error (or CI, or procedural in general) what i don't agree is leave the possibility of this could happen; but i don't want to insist more because is clear that is my opinion that you don't share.
Instead i'd like to leave a tiny contribution to poor soul that lack of proper revision method; based on suggestions of @curry684, I ended up with those two addition to code:

**src/AppBundle/Twig/TwigExtension.php**
```
class TwigExtension extends \Twig_Extension
{
    public function getFunctions()
    {
        return array(
            new \Twig_SimpleFunction('dump', array($this, 'dump')),
        );
    }

    public static function dump()
    {
        @trigger_error('you leave dump() in your views!', E_USER_WARNING);
    }
}
```

**web/app.php**
```
<?php

use Symfony\Component\HttpFoundation\Request;

function dump($var) { @trigger_error('you leave dump() in your code!', E_USER_WARNING); }
[...]
```
I tested that code: in dev environment twig default function wins over extension and app_dev.php is unchanged than no need to encapsulate in "function_exists". In prod env it works as expected.
Thanks everyone for patience and tips.

Regards,
Matteo
