### ISSUE TITLE
[Translation] translation founded but considered as missing

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#22432]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 2.8.19

Hi

I have this translation in my project
```xml
<trans-unit id="front.cart.payment_step.payment_step.discount_code_form_placeholder">
    <source>front.cart.payment_step.payment_step.discount_code_form_placeholder</source>
    <target>Saisissez votre code promo</target>
</trans-unit>
```

And i use it only in twig like this

```twig
{{ form_widget(discount_code_form.code, {
    attr: {
        placeholder: 'front.cart.payment_step.payment_step.discount_code_form_placeholder'|trans
    }
}) }}
```

the profiler tells me that the translation is missing, is this normal (twig side, not controller side) ?

Many thanks

**Comment by curry684** [comment]
Placeholders are translated by default so your code:
1. Translates the placeholder to "Saisissez votre code promo" explicitly in your code.
2. Tries to translate "Saisissez votre code promo" **again** in the form type. Which isn't found, triggering the error, and being displayed as the default, which is usually the same string.

Remove the `|trans` filter to fix this.

**Comment by noniagriconomie** [comment]
@curry684 removing indeed |trans in the twig does the job (no more missing)

@stof i understand your comment, the translation is done internaly by the form as well

many thanks both of you
