### ISSUE TITLE
Exception page in Symfony Profiler is broken after redesign

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#22442]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

After the recent redesign of the exception page in PR https://github.com/symfony/symfony/pull/20951 the exception page in saved profile in Symfony Profiler (URL `/_profiler/{token}?panel=exception`) is broken.

See the screenshot:
![broken-exception-page](https://cloud.githubusercontent.com/assets/885946/25054661/bb1c7720-215e-11e7-89fb-8edbacde54a5.png)

It looks like rendering a saved profile uses only `@Twig/Exception/exception.twig.html` template without the `@Twig/layout.html.twig` that contains CSS for the page.
See https://github.com/symfony/symfony/blob/bbe269f666d315439b3ca014d311bbc71f63af41/src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php#L66 called from https://github.com/symfony/symfony/blob/bbe269f666d315439b3ca014d311bbc71f63af41/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/exception.html.twig#L33 .

Therefore SVG "+" and "-" icons are displayed in default dimensions that are 1792x1792.

**Comment by sustmi** [comment]
The problem could be solved by changing `exception` to `exception_full` in https://github.com/symfony/symfony/blob/bbe269f666d315439b3ca014d311bbc71f63af41/src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php#L108 but it just does not feel right because that would include whole HTML page (including `<html>`, `<body>` and `<head>` tags) into the page.

The other solution that comes into my mind is moving the in-line `<style>` from layout into `exception.html.twig` but this is also not a clean solution as `<style>` tags should be inside `<head>` tag.
But most of the browsers support `<style>` tag inside `<body>` and it was very close from being tolerated by the standard: https://github.com/whatwg/html/issues/1605#issuecomment-282438836 so I guess is not that bad after all.
What do you think?

**Comment by sustmi** [comment]
I have just found that `@Twig/Exception/error.html` that is rendered when `debug` is `false` (see https://github.com/symfony/symfony/blob/bbe269f666d315439b3ca014d311bbc71f63af41/src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php#L108) contains whole HTML page too. So I guess we do not have to worry about rendering `@Twig/Exception/exception_full.html` inside another page.

**Comment by curry684** [comment]
Noticed this as well.

Status: reviewed
