### ISSUE TITLE
Collection element adder/remover naming in an entity

### ISSUE THREAD

**Issue by rgutknec** [symfony/symfony#22454]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3

What about collection element adder/remover in an entity, that do not follow simple singular/plural forms (author => authors, category => categories) ?
I should have : getMedia, addMedium and removeMedium (instead of addMedia, removeMedia)

**Comment by ro0NL** [comment]
Probably related to #21569, #9336, #22190, #5013 and others :)

**Comment by rgutknec** [comment]
Thanks @ro0NL for your help. As @lrlopez says :
> I think this feature can be rather useful to many people

This would be very useful for example for Latin words like medium/media, datum/data, ...
I close this issue and follow the mentioned ones.
