### ISSUE TITLE
[DependencyInjection] Environment variables don't work unless container is dumped

### ISSUE THREAD

**Issue by araines** [symfony/symfony#22464]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

In attempting to use the Dependency Injection component in its standalone form with the new `env()` style parameters, I've found that I must dump the container for it to work.

**services.yml**
```yaml
parameters:
  foo: '%env(BAR)%'
```

**test.php**
```php
$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/config'));
$loader->load('services.yml');

// Print the unresolved parameter (correct)
echo $container->getParameter('foo'); // %env(BAR)%

$container->compile();

// Print the resolved parameter (incorrect!)
echo getenv('BAR'); // baz
echo $container->getParameter('foo'); // env_BAR_9555682ffeb2c0d4b0c85ff622058910

$dumper = new PhpDumper($container);
file_put_contents('/tmp/container.php', $dumper->dump());
require '/tmp/container.php';
$container = new ProjectServiceContainer();

// Print the dumped and resolved parameter (now correct)
echo $container->getParameter('foo'); // baz
```

It is entirely possible I've misunderstood something here, but I've looked high and low in the documentation and I can't see anything which says you must dump the container - it appears to be an optional step so far as I can tell for performance reasons.  As such, I'd expect a compiled container to work the same as a dumped one.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/issues/21420
Doc PR/issue welcomed of you want to work on it!
