### ISSUE TITLE
access_control, optional locale regex breaks

### ISSUE THREAD

**Issue by peyman-mohamadpour** [symfony/symfony#22463]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

I have Symfony paths like:

    /en/login
    /login
and want to set `access_control`, adding **optional** locale section in path:

    security
        access_control:
            - { path: ^/([a-z]{2}/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
The regex is [working fine](https://regex101.com/r/JSmGgL/1), but Symfony gives me parse error:
>Unexpected characters near "/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }" at line 71 (near "- { path: ^/([a-z]{2}/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }").

I can not understand why?!
I think there is a problem with escape character.

**Comment by xabbuh** [comment]
The closing curly brace will be interpreted as the end of the YAML mapping. You need to quote the string like this:

```yaml
security
    access_control:
        - { path: '^/([a-z]{2}/)?login$', role: IS_AUTHENTICATED_ANONYMOUSLY }
```

I am closing here as this behaviour is no bug.
