### ISSUE TITLE
Non-BC changes in Symfony 4.0

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22462]
This meta issue lists all the non-BC changes that were proposed for Symfony 4.0:

* [ ] Use `UTF-8` as the default encoding in the DomCrawler (instead of the current `ISO-8859-1` (#17258)
* [ ] ...

**Comment by nicolas-grekas** [comment]
Our policy for bc breaks is to always trigger a deprecation before doing it. 
We should never accept bc breaks that have no continuous upgrade path.
Changing a default value is not possible without first doing something in 3.x.

**Comment by javiereguiluz** [comment]
Yes. But #17258 was closed, so I needed to create this to not forget about that change. It's been asked for multiple times and not using UTF-8 nowadays feels wrong.

**Comment by nicolas-grekas** [comment]
Then reopen it :)
The only continuous upgrade path is to make the charset a required argument.

**Comment by nicolas-grekas** [comment]
Reopened #17258
