### ISSUE TITLE
Missing alias of security.user_checker

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#22466]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

Alias of `security.user_checker` to `Symfony\Component\Security\Core\User\UserCheckerInterface` seems missing.
Defining an autowired service that depends on the interface raises a deprecation error (`Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "security.user_checker" service to "Symfony\Component\Security\Core\User\UserCheckerInterface"`)

**Comment by xabbuh** [comment]
I am not sure that it is a good idea to create a global alias for the `UserCheckInterface`. The thing is that you can configure different user checkers per firewall. So which one would you want to alias then? Having the need to be explicit when inject the user check at least should make one think about what they want to have injected I guess.

**Comment by stof** [comment]
@xabbuh AFAIK, we have a main `security.user_checker` service (firewalls can decide to inject a different one, but we have a main checker)

**Comment by xabbuh** [comment]
@stof Yes, we have the `security.user_checker` service and it's the default value when your firewall config does not require another one explicitly.

**Comment by xabbuh** [comment]
To be more clear: My point isn't that there is no service we could not alias. I just think that adding the alias ourselves will hide the fact that the aliased one must not necessary be the user checker service the user wants to use. And by the way, if you know that your applications does only use one user checker, you are can add the alias yourself anyway.

**Comment by xabbuh** [comment]
Though we can check during compile time if the user registered a custom user checker and otherwise add the alias (see #22470).
