### ISSUE TITLE
Inconsistency in security factories

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#22473]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

I've implemented my own security authentication using a custom factory as e.g. described in the [docs here](http://symfony.com/doc/current/security/custom_authentication_provider.html).
I read the source code in `SecurityExtension` carefully and as far as I could see, thanks to the support for factories and the `AbstractFactory` I was able to quickly have my own listener, provider etc. registered. Configuring it in my `security.yml` was as easy as this:

```yml
firewall_name:
    pattern: ~
    anonymous: true
    my_factory_key: { my_factory_settings: foobar }
```

However, this does not work for `logout`. As you can see [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L351), `logout` has to be explicitly defined on the firewall so I cannot just use my factory to provide my own logout listeners. I would like to replace the logout listener because I don't want it to check for a path but for request parameters to be present.
I just wonder if this is on purpose or if this is actually an inconsistency? Maybe anyone can tell me :-)

**Comment by sh4ka** [comment]
I think you should enable the logout option in the firewall like this: http://symfony.com/doc/current/security.html#logging-out

**Comment by Toflar** [comment]
This is not what I need. My firewall does not support logging out on a specific route but on certain request attributes which is why I need to adjust the default logout listener.

**Comment by ro0NL** [comment]
I think your stuck :) The bundle config only supports the default logout handler, which is path based :(

Can you move forward when decorating `security.logout_listener`?

Would be nice if we could do something like `logout: { id: some-service }` on each firewall :+1:

**Comment by Toflar** [comment]
> Would be nice if we could do something like logout: { id: some-service } on each firewall 👍

Yeah, I just wonder why nobody else had this problem before which is why I'm kinda feeling I'm missing something 😄

**Comment by ro0NL** [comment]
We all use path-based logout :P
