### ISSUE TITLE
[DI] master: Can't use 'factory' in '_instanceof' in service Yaml

### ISSUE THREAD

**Issue by mattjanssen** [symfony/symfony#22489]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x-dev

A few weeks ago on master I was able to use `factory` in my `_instanceof` Yaml service declarations. This was useful because all instances of DoctrineRepository need the same factory call. Without it, all DoctrineRepositories have to duplicate the same factory line. The purpose of `_instanceof` to reduce duplication would be better served if we could use factory.

@nicolas-grekas I edited `DependencyInjection/Loader/YamlFileLoader` and added `'factory' => 'factory'` to the `$instanceofKeywords` array and it seemed to work. Any drawbacks? Better solutions?

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/22356#discussion_r110704007
And #22189

Any comment about these?

**Comment by mattjanssen** [comment]
Closing as this is mostly a duplicate of #22189. Thanks Nicolas.
