### ISSUE TITLE
[Security] UsernamePasswordJsonAuthenticationListener requires custom failure handler to prevent redirect to login

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#22483]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3-dev

Right now `UsernamePasswordJsonAuthenticationListener` defaults to using `DefaultAuthenticationFailureHandler` which means that a redirect is made rather than returning a `4xx` error. I guess it makes sense to have the ability to define a custom failure handler but there should be a way to not have a redirect.

I looked into `DefaultAuthenticationFailureHandler` and I do not see a clean way to get this behavior, maybe we should add a `throw_exception` option to make it possible to simply re-throw the `AuthenticationException` so that it can be handled appropriately elsewhere or if there should be an option `return_error_reponse` which accepts an HTTP status code as a value that would then be used in the response.

**Comment by lsmith77** [comment]
ping @chalasr @dunglas

**Comment by chalasr** [comment]
Indeed, a redirection as default response in case of failure doesn't make sense for this listener.

I think having both `throw_exception|return_error_response` and `failure_handler` would be confusing, what should we do if a custom failure handler is set and `throw_exception|return_error_response` is set?

Couldn't we replace the current default failure handler to one returning a simple 401 (json?) response, maybe inlined in the `UsernamePasswordJsonAuthenticationListener::onFailure()` method directly?

**Comment by lsmith77** [comment]
sure we could of course also introduce another failure handler

**Comment by chalasr** [comment]
In fact this applies to the success handler as well: if used on a stateless firewall, a success would redirect to a route which requires to be authenticated, leading to a redirect loop.

Either this listener should ease stateless authentication and the default success/failure handlers should provide some basic json responses (no redirect at all) or it should ease stateful one (as currently) and we should keep using the default (redirect based) success/failure handlers as for `form_login`, requiring to define some custom success/failure handlers for having it stateless.

Is there use cases for having it stateful/redirect-based? Hitting a JSON API with credentials should not lead to redirections, right?

I would say default stateless, removing redirect-related options from the listener factory (`default_target_path`...). Looking for @dunglas thoughts before acting.

**Comment by chalasr** [comment]
well, see #22494
