### ISSUE TITLE
dump not working if created new Application

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#22488]
if I run this example:
http://symfony.com/doc/current/console/command_in_controller.html
then dump is not working

I think, it is becouse of creating new Application

**Comment by xabbuh** [comment]
I am not sure if I understand your problem. The code example you linked to does not make use of `dump()`.

**Comment by poolerMF** [comment]
before returning Response try dump and you will see

**Comment by xabbuh** [comment]
What happens then? Do you get an error message? Did you install the VarDumper component?

**Comment by sh4ka** [comment]
If you are expecting to see the dump in console when used from the controller, I don't think that's going to happen...

**Comment by poolerMF** [comment]
VarDumper  installed properly
![example](https://cloud.githubusercontent.com/assets/4276289/25245002/2e6e21bc-2603-11e7-884f-88faeae082b7.PNG)

**Comment by sh4ka** [comment]
VarDumper docs: On the command line (CLI SAPI), the output is written on STDOUT, but you are changing the output.

**Comment by javiereguiluz** [comment]
@poolerMF you are right that this doesn't work ... but I tend to agree with @sh4ka: this is a documented limitation of dump(). Besides, the code shown in your example doesn't look taken from a real application. Did you experienced this when using dump() in your app? Thanks!

**Comment by poolerMF** [comment]
I just want to debug it ..

you can close issue

**Comment by javiereguiluz** [comment]
Closing it then. @poolerMF this time it was considered OK to not fix this edge case, but please keep reporting any other issues or edge cases you may find in the future. Thanks!
