### ISSUE TITLE
[FrameworkBundle] cache:clear instantiates the kernel regardless of its constructor signature

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#22499]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7 up to 4.0

Nothing seems to indicate that the application kernel (most often `AppKernel`) should not have a custom constructor. However doing so breaks the `cache:clear` command as it [blindly creates a new instance of the kernel class](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L243) for warming up the cache, assuming that the constructor is the same as the `Kernel` one.
Fortunately, `cache:clear` with warmup is deprecated as of 3.3, and running it with `--no-warmup` followed by `cache:warmup` is fine.

To reproduce, checkout the SE in 2.7+, add a constructor to the `AppKernel` class with a third required argument, update the `console` file to instantiate it properly (common for e.g. [multi-kernel app](http://symfony.com/doc/current/configuration/multiple_kernels.html)) and run `cache:clear`:

> Type error: Argument 1 passed to AppKernel::__construct() must be of the type integer, string given, called in [...]/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 243

Could the warmup part of the command make use of `@cache_warmer::warmup()` instead?

**Comment by iltar** [comment]
Related issues: #8500 and #12232

**Comment by chalasr** [comment]
Closing as won't fix
