### ISSUE TITLE
[DotEnv] Potential issue with `$_SERVER`

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#22493]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x-dev

In the `DotEnv.php` file we have this:

```php
    /**
     * Sets values as environment variables (via putenv, $_ENV, and $_SERVER).
     *
     * Note that existing environment variables are never overridden.
     *
     * @param array $values An array of env variables
     */
    public function populate($values)
    {
        foreach ($values as $name => $value) {
            if (isset($_ENV[$name]) || false !== getenv($name)) {
                continue;
            }
            putenv("$name=$value");
            $_ENV[$name] = $value;
            $_SERVER[$name] = $value;
        }
    }
```

Isn't it a bit dangerous to replace `$_SERVER` variables? There are env vars that do not exist but keys might exist in the `$_SERVER` array, so it shouldn't replace keys that are handled by PHP internally.

Is it really important to avoid replacing sensitive data from the `$_SERVER` var?

WDYT?

**Comment by sh4ka** [comment]
This:
`if (isset($_ENV[$name]) || false !== getenv($name)) {`
Could be changed to:
`if (isset($_ENV[$name]) || isset($_SERVER[$name]) || false !== getenv($name)) {`
And we will be safe.

**Comment by Pierstoval** [comment]
Indeed, but that's why I created an issue: is it worth it to do so?

**Comment by sh4ka** [comment]
In my humble opinion, not doing it is an error.

**Comment by Pierstoval** [comment]
See #22500 then 🙂

**Comment by fabpot** [comment]
Why would it be "dangerous"? Names and values are defined by the developer.

**Comment by curry684** [comment]
In shared hosting environments you're often sharing PHP and NGINX/Apache processes with untrusted external parties. Not securing this means a sandboxing issue on their end might allow privilege escalations through pushing `X_FORWARDED_FOR` or related headers into your application. Far fetched, but possible.

As a more severe example though I actually have a Dockerized application in production where the docker environment actually uses the `HTTP_HOST` env variable to define the primary deployment domain, and pushes it down in the app where it is used for example to match routes based on `host: "api.${HTTP_HOST}"`.

And given the code in this issue, that will no longer work as `$_SERVER['HTTP_HOST']` is being overwritten....

**Comment by sstok** [comment]
But .env is not meant to be used in production 😛 you should be using actual ENV's set using the web server configuration.

**Comment by Pierstoval** [comment]
If someone wants to define a `TMP` or `TEMP` env var, it shouldn't be set this way, because TMP is also a special var.

Actually, anything in [`$_SERVER` php doc](http://php.net/manual/en/reserved.variables.server.php) shouldn't be overriden because it's managed by PHP internally.

At least, even if it's for dev environment, I think it's nice to enforce users not to override `$_SERVER` vars because it encourages documentation about `$_SERVER`

**Comment by fabpot** [comment]
Then, perhaps we should just remove `$_SERVER` overriding altogether.

**Comment by Pierstoval** [comment]
Internally, PHP get env vars and puts them into the `$_SERVER` var as well as `$_ENV`, even if it's not the best IMO, it's still a behavior from PHP itself.

But by doing this, PHP still makes sure that _internal_ vars are not replaced with env vars that have the same name as the `$_SERVER` keys, so to be consistent with internal PHP behavior I would recommend to still override `$_SERVER`, but do it exactly like PHP does it: by not replacing existing keys 😄

**Comment by sstok** [comment]
It seems the PHP engine (from I was able to understand from the C code) simple registers special `$_SERVER` variables afterwards, so they are not fully protected. But simple overwritten.

But 👍  to not overwrite existing SERVER values. Using SERVER for ENV values seem a bit like using `$_REQUEST` instead of POST/GET.

**Comment by curry684** [comment]
> Then, perhaps we should just remove $_SERVER overriding altogether.

👍 from me on that one. As mentioned above, it's like `$_REQUEST` and `register_globals` all over again. No need to mimic 20 year old legacy behaviors in PHP, if you need an env var just query the env vars.

**Comment by nicolas-grekas** [comment]
@curry684 I agree with you that merging several sources is a bad idea, but we're no going to reinvent PHP and fix that by ourselves. Not adding the values in `$_SERVER` would make this component useless for the existing code base that just checks this variables for env values. Since this is a quite common practice, we have no choice but support it. Not overriding existing values fixes the reported issue. Thus I'm +1 on the linked PR and consider this fixed.
