### ISSUE TITLE
[Form] is_edit => false, erases data_class constructor values

### ISSUE THREAD

**Issue by wickedOne** [symfony/symfony#22504]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.6

not entirely sure whether this is a bug or expected behaviour.

when using a form for a class which sets (default) values in it's constructor method while the is_edit option is set to false, the constructor values are erased if not submitted.

e.g.
```php
class Foo 
{
    private $foo;
    private $bar;

    public function __construct()
    {
        $this->bar = 'baz';
    }

    // ...
}

class FooType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'foo',
                TextType::class
            )->add(
                'bar',
                TextType::class
            );
            
        public function configureOptions(OptionsResolver $resolver)
        {
            $resolver->setDefaults([
                'data_class' => 'AppBundle\Entity\Foo',
                'is_edit' => false,
            ]);
        }

    }
```
and you'll post: 
```json
{"foo" : "bar"}
```

will result in:
```sql
+-------+------+
|  foo  |  bar |
+-------+------+
|  bar  | NULL |
+-------+------+
```

while one might expect:
```sql
+-------+------+
|  foo  |  bar |
+-------+------+
|  bar  |  baz |
+-------+------+
```

**Comment by dmaicher** [comment]
Thanks for your report :wink: 

This is expected behavior if you submit the form using a `POST` request. Since you are not submitting any value for `bar` its set to null on the model.

If you would use a `PATCH` request then the form component would only update fields that are actually submitted.

Btw I don't understand what your custom `is_edit` option should have to do with it?

**Comment by wickedOne** [comment]
thanks for the clarification!
i was unaware that a ``PATCH`` method actually [is allowed](https://tools.ietf.org/html/rfc5789#section-2) to create a new resource...  :confused:

> Btw I don't understand what your custom is_edit option should have to do with it?

my bad, nothing actually...
