### ISSUE TITLE
Forms, DataTransformer: Allow multiple invalid_messages when using data transformers

### ISSUE THREAD

**Issue by twharmon** [symfony/symfony#22501]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | ?
| RFC?             | ?
| Symfony version  | 3.2.7

In the [documentation for data transformers](http://symfony.com/doc/current/form/data_transformers.html#creating-the-transformer), the input is validated in the IssueToNumberTransformer class, and the error message is set in the TaskType class. What if there are multiple types of invalid input, can there be a way to have multiple error messages?

I know this can be done with Symfony\Component\Validator\Constraints in the Entity class, but since validation must also take place in the data transformer, I think there should be a way to have more control over the error messages.

**Comment by ogizanagi** [comment]
See https://github.com/symfony/symfony/pull/20978 for a suggested implementation.

**Comment by xabbuh** [comment]
I just stumbled upon #9891 which basically requests the same feature. So I am going to close here as a duplicate.
