### ISSUE TITLE
Confusion regarding framework.trusted_proxies in Symfony 3.3

### ISSUE THREAD

**Issue by alcaeus** [symfony/symfony#22506]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3-dev

According to the current [Symfony 3.3 upgrading document](https://github.com/symfony/symfony/blob/a90e46188f8502d473a9e339f3da2c653df8bbde/UPGRADE-3.3.md#frameworkbundle), the `framework.trusted_proxies` parameter config option has been deprecated and will be removed in Symfony 4.0. However, according to the [commit in question](https://github.com/symfony/symfony/commit/72e28957e2804517e36c6a74fe7fbffae54f5184#diff-5e7347edce37c5886ec67b7ba02f3a9c), the option has been removed in 3.3 already (unless you trust that comment a few lines above where it still says the parameter is deprecated).

What's the state of this? Is the configuration option deprecated in 3.3 or is it already removed? If so, what's the reason for this BC break?

**Comment by sstok** [comment]
The option itself is no longer supported. Setting it gives a helpful message about this change.
But in 4.0 this will be completely removed, and no upgrade message is shown anymore.

`@deprecated in version 3.3, to be removed in 4.0` is to help developers find old code when working on the next major version.

**Comment by alcaeus** [comment]
Thanks for the explanation. Should the UPGRADE document for 3.3 be updated to mention the option being removed, not deprecated? If so, I can create a PR.

**Comment by sstok** [comment]
Oh wait, the UPGRADE in the root is not up-to-date with the one of the FrameworkBundle.

**Comment by sstok** [comment]
See #22507

**Comment by alcaeus** [comment]
Thank you, closing since it's being fixed by the pull request.
