### ISSUE TITLE
Debug property has multiple behaviours

### ISSUE THREAD

**Issue by htesligte** [symfony/symfony#22508]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.3

The debug property (used in WebTestCase::createClient) that is used to create a client has multiple behaviors. It shows production error pages, but it also decides whether or not cache is fresh and needs to warm up. 
This gives an issue when we try to mock a security voter, depending on whether a test has run before this, the test fails or succeeds. I would like to see the debug flag split in two, a flag to display production error pages, and a flag to control cache behavior. 

I am talking about these pieces of code:

Kernel.php:
```
    protected function initializeContainer()
    {
        $class = $this->getContainerClass();
        $cache = new ConfigCache($this->getCacheDir().'/'.$class.'.php', $this->debug);
        $fresh = true;
        if (!$cache->isFresh()) {
            $container = $this->buildContainer();
            $container->compile();
            $this->dumpContainer($cache, $container, $class, $this->getContainerBaseClass());

            $fresh = false;
        }

        require_once $cache->getPath();

        $this->container = new $class();
        $this->container->set('kernel', $this);

        if (!$fresh && $this->container->has('cache_warmer')) {
            $this->container->get('cache_warmer')->warmUp($this->container->getParameter('kernel.cache_dir'));
        }
    }
```

and TwigBundle/Controller/ExceptionController:
```
    public function showAction(Request $request, FlattenException $exception, DebugLoggerInterface $logger = null)
    {
        $currentContent = $this->getAndCleanOutputBuffering($request->headers->get('X-Php-Ob-Level', -1));
        $showException = $request->attributes->get('showException', $this->debug); // As opposed to an additional parameter, this maintains BC

        $code = $exception->getStatusCode();

        return new Response($this->twig->render(
            (string) $this->findTemplate($request, $request->getRequestFormat(), $code, $showException),
            array(
                'status_code' => $code,
                'status_text' => isset(Response::$statusTexts[$code]) ? Response::$statusTexts[$code] : '',
                'exception' => $exception,
                'logger' => $logger,
                'currentContent' => $currentContent,
            )
        ));
    }
```

**Comment by sh4ka** [comment]
Do you mind writing a quick test proving the failing point?

**Comment by htesligte** [comment]
Sure, I will write something to demonstrate this issue. It might take a few days until I have time.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
