### ISSUE TITLE
[Form] Fixing FormTypeInterface::getName() deprecations leads to illegal characters error

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#22502]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

While working on removing deprecations from 2.8.17 app, and prepare it for 3.0 upgrade and fixing:
```
Foo\BarType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0.
```
by updating:

```diff
-    public function getName()
+    public function getBlockPrefix()
     {
```
I immediately get:

```
The name "Foo\BarType" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").
```

I see [getName()](https://github.com/symfony/symfony/blob/v2.8.17/src/Symfony/Component/Form/AbstractType.php#L68-L72) returns `get_class($this)`, which must contain `\` if type does not live in root namespace, which is almost never the case. And [FormConfigBuilder::isValidName()](https://github.com/symfony/symfony/blob/v2.8.17/src/Symfony/Component/Form/FormConfigBuilder.php#L918) does not allow `\`.

To reproduce the issue:

```
git clone git@github.com:umpirsky/symfony-issue-22502.git
cd symfony-issue-22502
composer install
php reproducer.php             
PHP Fatal error:  Uncaught Symfony\Component\Form\Exception\InvalidArgumentException: The name "Foo\ReproducerType" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":"). in /home/umpirsky/Projects/symfony-issue-22502/vendor/symfony/symfony/src/Symfony/Component/Form/FormConfigBuilder.php:895
Stack trace:
#0 /home/umpirsky/Projects/symfony-issue-22502/reproducer.php(25): Symfony\Component\Form\FormConfigBuilder::validateName('Foo\\ReproducerT...')
#1 {main}
  thrown in /home/umpirsky/Projects/symfony-issue-22502/vendor/symfony/symfony/src/Symfony/Component/Form/FormConfigBuilder.php on line 895
```

**Comment by iltar** [comment]
Do you actually need the `getName()`? Because you could just remove both.

**Comment by sstok** [comment]
`getName()` can still exist for compatibility, but it can't return the class name. You only use the class for referencing (add/create/getParent).

**Comment by umpirsky** [comment]
@iltar No, but I do need `getBlockPrefix()`, that's why I change:

```diff
-    public function getName()
+    public function getBlockPrefix()
     {
```

@sstok Yes, but I want to remove that deprecation before upgrade, and this name validation is blocking me, That's what this issue is about. :)

Thanks for the feedback!

**Comment by sstok** [comment]
Can you provide a reproducer? https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by umpirsky** [comment]
@sstok Yes, will do soon. ;)

**Comment by umpirsky** [comment]
Looks like the workaround is to define both:

```php
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function getBlockPrefix()
    {
        return 'bar';
    }
```

Like in [EntityType.php#L60-L74](https://github.com/symfony/symfony/blob/v2.8.17/src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php#L60-L74)

**Comment by sstok** [comment]
Actually `getName()` is only for compatibility, it shouldn't have changed in 2.7 🤔 I guess this is a bug. But I don't know enough about these internals to say for sure.

Friendly ping to @webmozart

**Comment by HeahDude** [comment]
Hello @umpirsky, thanks for this reproducer, but I think it's not enough because the error should not happen in a full stack context, see https://github.com/HeahDude/sf_issue_22502.

**Comment by umpirsky** [comment]
@HeahDude Yes, you are right, I found some things in my code that caused this. Closing..

Thanks!

**Comment by HeahDude** [comment]
Ok thanks, for the record you need indeed to keep implementing `getName()` for BC but in your app just remove the service definition (if no injection is needed) or the alias parameter in the tag and use FQCN only with factory methods (`create*()`,` add()` including Form and its builder), otherwise your solution above is the way to go.

**Comment by umpirsky** [comment]
Yes, exactly. Thanks.
