### ISSUE TITLE
Config Component - children() method not found on prototype() when using TreeBuilder

### ISSUE THREAD

**Issue by J7mbo** [symfony/symfony#22505]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

According to [Array Node Options](http://symfony.com/doc/current/components/config/definition.html#array-node-options) in the documentation, we can use the following code when utilising the TreeBuilder.

    ->prototype('array')
        ->children()

However, because `prototype()` returns an object of type [NodeDefinition](https://github.com/symfony/symfony/blob/3e7ff2194e6750c2f92544c4f4559bef8ef713ff/src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php), which does *not* contain the method `children()`, this throws up errors in IDEs and removes IDE autocompletion from the rest of the TreeBuilder usage.

Concrete example that works:

<img width="697" alt="screen shot 2017-04-23 at 13 56 55" src="https://cloud.githubusercontent.com/assets/2657310/25317393/c21779a6-282c-11e7-8f09-f6668e4a0d17.png">

**Comment by ro0NL** [comment]
In 3.3/master there are shortcut methods available, such as `arrayPrototype()` ;)

**Comment by xabbuh** [comment]
Closing here as I don't think we can do much about it and using the `arrayPrototype()` method doesn't suffer this limitation.
