### ISSUE TITLE
[EventDispatcher] quo vadis listener priorities

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#22514]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3

I am wondering about Symfony 4 (which in turn might require some deprecations for 3.3) and how to deal with priorities. The current number system creates very implicit dependencies between listeners that are quite fragile to deal with. See for example this PR on FOSRestBundle that is the continuation of various previous attempts to "extend" Symfony core behavior:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1692

The fundamental question to me is:
1) keep the priority system (ie. implicit dependencies)
2) replace it with a system allowing definition of explicit dependencies
3) remove priorities without a replacement

About 1)
I find the current approach to lead to hard to debug code, especially when Bundles are trying to extend core behavior. It gets worse when multiple Bundles attempt to extend the same core listener.

About 2)
I think we have debated explicit dependencies between listeners at various points already and dropped it due to concerns over the complexity in building the dependency graphs etc. I guess in theory maybe composer code could be used here but maybe that is overkill. I guess performance could be handled via caching similar to what we do with the DI Container. But either way it would be a lot of code to write

About 3)
This would be the most radical step. Essentially this would mean that listeners that depend on each other would need to be chained together explicitly. That is we might want to then offer some sort of chain listener. If I would want to create a dependency between two listeners I would therefore have to de-register the existing listener and replace it with a chain listener that is then configured to execute the given listeners in the required order. This approach would basically make dependencies explicit but would rely on the user to handle this explicitly. The advantage being that it would be less code to write and maintain on our side but it would make it harder to solve situations of multiple re-useable bundles wanting to extend the same core listener.

**Comment by lsmith77** [comment]
BTW here is a search to give a rough idea about the current core use of priorities:
https://github.com/symfony/symfony/search?l=XML&q=priority&type=&utf8=✓

**Comment by ro0NL** [comment]
> de-register the existing listener and replace it with a chain listener

I always decorate such a service (e.g.  tagged event listener), doing my logic from there + calling the inner listener.

I guess the problem with priorities is you shouldnt rely on it to create dependencies with external libs. In case it's dependent.. then decorate it?

**Comment by javiereguiluz** [comment]
My vote is for 1). I don't think we should change anything about the listener priorities.

Besides, Symfony built-in priorities never change, so if your code must be executed before or after something, you can check those priorities (e.g. using the dedicated profiler panel) and adjust your own priority accordingly.

**Comment by jakzal** [comment]
I agree with @javiereguiluz

**Comment by lsmith77** [comment]
Just so that I can understand better, you think that its not worth the change or you think that priorities are still the best pattern to model such dependencies?

**Comment by jakzal** [comment]
I think it's good enough and changing to another system is simply not worth the effort and disruption it will bring. Priorities work for most of use cases. I think we should avoid dependencies between listeners in the first place (decoration is one way to avoid it).

**Comment by javiereguiluz** [comment]
👍  now I fully agree with Jakub.

**Comment by stof** [comment]
Having explicit dependencies also make it much harder to have soft-coupling. and removing the control of the sorting entirely would make it much less powerful than today.
And caching is not always an option. The Form component also rely on EventDispatcher, but cannot pre-compute the dependency graph.

So I think priority is still a better option than explicit dependencies (yes it has drawbacks, but explicit dependencies have other drawbacks). And so I don't think changing is worth it

**Comment by Pierstoval** [comment]
I also think current priority system is the best option. Having an event that depends on another event introduces a lot of coupling, especially if an event depends on an external lib event, so in this case, both projects contributors have to work together to make sure the priority is set and never changes (like Symfony events, with their priority that won't change)

**Comment by lsmith77** [comment]
so in this sense our recommended pattern is "soft coupling" and clearly documented priorities that are part of the BC promise?

**Comment by stof** [comment]
@lsmith77 yes

**Comment by dunglas** [comment]
In API Platform I've added a bunch of constants corresponding to popular priorities (https://api-platform.com/docs/core/events). It makes the registering of subscribers easier and more user friendly. We may do something similar for priorities of builtin listeners.

**Comment by lsmith77** [comment]
for the record, where are the priorities documented?

I guess here:
* http://symfony.com/doc/current/reference/events.html
* http://symfony.com/doc/current/reference/dic_tags.html

**Comment by lsmith77** [comment]
@dunglas I like this idea a lot!

**Comment by dunglas** [comment]
So expect a PR soon!

**Comment by lsmith77** [comment]
thanks for the feedback!
