### ISSUE TITLE
Hidden Console Commands & Namespaces

### ISSUE THREAD

**Issue by CupOfTea696** [symfony/symfony#22512]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

When all Console Commands are hidden, the List Command still shows the namespace, even though there isn't a single visible command within that namespace. The namespace should be hidden here.

In the example below, I run `MyApp/bin/app list`. The command `ms:init` is set to hidden.

Result:
```
Available commands:
  help         Displays help for a command
  list         Lists commands
 ats
  ats:clean    Delete any exported ATS archives in a given set of paths
  ats:export   Optionally build an ATS Frontend, and export the required files to an archive
 ms

```

Expected result
```
Available commands:
  help         Displays help for a command
  list         Lists commands
 ats
  ats:clean    Delete any exported ATS archives in a given set of paths
  ats:export   Optionally build an ATS Frontend, and export the required files to an archive
```

**Comment by ro0NL** [comment]
Related to #19954 

Note it doesnt happen in 3.3 currently, probably because above PR. Perhaps something can be backported here... not sure :) i can have a look soonish.
