### ISSUE TITLE
[HttpFoundation] Invalid redirect Location

### ISSUE THREAD

**Issue by funivan** [symfony/symfony#22517]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | all

For example we have URL represented as object
```php
class IndexUrl {
    public $hash = 'menu';
    public function __toString()
    {
      return 'http://test.com/index#' . $this->hash;
    }
  }
```
I try to use this object with `RedirectResponse`
```php
$response = RedirectResponse::create(new IndexUrl());
```
`RedirectResponse` produce invalid `location` header:
```php
$response->headers->get('Location') // Location will be "menu"
```

BUT valid content.
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://test.com/index#menu" />

        <title>Redirecting to http://test.com/index#menu</title>
    </head>
    <body>
        Redirecting to <a href="http://test.com/index#menu">http://test.com/index#menu</a>.
    </body>
</html>
```

**Comment by sh4ka** [comment]
I think this is a documentation problem. The first parameter accepted for RedirectResponse::create() whould be a $body, in the same way Response::create() is. http://api.symfony.com/3.2/Symfony/Component/HttpFoundation/Response.html#method_create
Or maybe I'm missing something.

**Comment by iltar** [comment]
`public static function create($url = '', $status = 302, $headers = array())` So that's not the problem.

Somewhere internally it does `$values = array_values((array) $values);`, which causes something weird I suppose. I recommend to simply add a getter instead of using `__toString()`. This is not a valid use-case for that anyway imo.

**Comment by sh4ka** [comment]
Look at the example for that method @iltar:
`return Response::create($body, 200)
    ->setSharedMaxAge(300);`
What do you think?

**Comment by funivan** [comment]
@iltar you are correct `array_values` breaks our object.

> I recommend to simply add a getter 

Yep. But what to do if someone forget to write this __toString ? 
It is hard to detect this buggy code:
1. IDEA does now show any warnings because of the phpdoc 
`@param string $url     The URL to redirect to.`
2. Can be detected only with unit tests

**Comment by iltar** [comment]
@funivan `@param string $url`, that means that you cannot use an object. An object with `__toString()` does not work with strictmode and `(string $url)` either. If Symfony were to add the typehint and you would use  `declare(strict_types=1);`, your code would break anyway.

**Comment by funivan** [comment]
@iltar agree. So we need validation of parameter. Something like https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L408:L410

**Comment by nicolas-grekas** [comment]
Closing as "bogus", as discussed in #22518.
