### ISSUE TITLE
[phpunit-bridge] Class 'PHPUnit_Util_Test' not found

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [symfony/symfony#22515]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Running tests throws me the error `PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Util_Test' not found in ........../vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:94`

phpunit version is 6.1.1

**Comment by e-moe** [comment]
Symfony 3.2 doesn't support phpunit 6.x. Use 5.x instead

**Comment by xabbuh** [comment]
This is indeed expected. Support for PHPUnit 6 was added to the  `master` branch. Requiring `^3.3@dev` of the bridge will allow you to use PHPUnit 6 too.

**Comment by KonstantinKolodnitsky** [comment]
Thanks
