### ISSUE TITLE
[DI] Xml definitions: support setting the injected id as node value

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#22525]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

So that one could use `<argument type="service">logger</argument>`, when only `<argument type="service" id="logger" />` is supported right now. I made the mistake so many times.

**Comment by javiereguiluz** [comment]
I'm 👎  for these reasons:

* "Autocompletion" is usually mentioned as the best feature of the XML format, so developers using an IDE "can't" make this mistake.
* Providing multiple alternatives to define the same config is something that we usually avoid because it complicates our code and the learning curve.

**Comment by nicolas-grekas** [comment]
When the existing alternative is not the instinctive one (as was the case for me when learning that syntax), I challenge these reasons. Note that I don't use any fancy IDE nor autocompletion and that we shouldn't no design thing to be easy only for advanced IDEs users. So still calling for this :)

**Comment by iltar** [comment]
I would love to see this "fixed" actually. I don't often work with XML but the `id="service_id"` feels counter intuitive. I always end up doing `<argument type="service">logger</argument>` as well and then wondering why it's not working 😢

**Comment by ogizanagi** [comment]
I also found this confusing when I learned it, even if now I'm used to it. So I'd like to get this fixed too. 👍

**Comment by fabpot** [comment]
👎 for the same reasons as @javiereguiluz. I would add also consistency with other argument types.

**Comment by nicolas-grekas** [comment]
I don't get that consistency argument: the allowed argument types are "collection", "service", "expression", "string", "constant", "iterator", "closure-proxy".

Among them, only "service" and "closure-proxy" take an additional attribute to define their values.
In fact, this request would make things more consistent to me. (maybe why my intuition made me think that was the correct syntax when I write xml definitions)...
