### ISSUE TITLE
[WebProfilerBundle] Some listeners don't display their priority

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22520]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | all

In the profiler, the listeners related to the `kernel.terminate` event don't display the priority:

![undefined-priority](https://cloud.githubusercontent.com/assets/73419/25387104/f25ba972-29c9-11e7-9fa8-8cf24710ded7.png)

However, those services define their priority:

![defined-priority](https://cloud.githubusercontent.com/assets/73419/25387113/fa340ea0-29c9-11e7-8af8-2b9b0a876ce5.png)

But this is somehow lost and the priority is `null` in the profiler:

![null-priority](https://cloud.githubusercontent.com/assets/73419/25387127/067611fe-29ca-11e7-9faa-468415c64b80.png)

**Comment by stof** [comment]
I suspect this is because the collection of data about listeners is done during the `kernel.terminate` event. And so, during this event, the dispatcher does not contain the actual listeners but wrapped versions of them.

The TraceableEventDispatcher probably need to unwrap the listener before forwarding the call, as done for `removeListener` (except that it should not remove the wrapper of course)

**Comment by dmaicher** [comment]
On my Symfony 2.8 app I can see the priority for the `kernel.terminate` listener (there is only one listed):

![listener_prio](https://cloud.githubusercontent.com/assets/921145/25424865/30d5b4cc-2a6a-11e7-8427-ecd407627d19.png)

**Comment by javiereguiluz** [comment]
I used the Symfony Demo app, so 3.2.5 for me.

**Comment by stof** [comment]
@dmaicher the implementation in 2.8 is totally different.

**Comment by dmaicher** [comment]
@stof ok thats what I thought but above it says `Symfony version: all` :yum:

**Comment by stof** [comment]
Well, I think it is a mistake.

The 2.8 version has actually a different issue. It has the right priority, but not the right callable

**Comment by dmaicher** [comment]
I fixed the problem for 2.8 in this PR https://github.com/symfony/symfony/pull/22541.

I will also try to have a look on 3.2.

**Comment by dmaicher** [comment]
@javiereguiluz can you try this diff for 3.2? I currently don't have an app running with it :yum: 

```diff
diff --git a/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php b/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php
index 45208a19b2..59afdc0f71 100644
--- a/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php
+++ b/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php
@@ -89,9 +89,18 @@ class WrappedListener
             $this->data = false !== self::$cloner ? self::$cloner->cloneVar(array(new ClassStub($this->pretty.'()', $this->listener)))->seek(0) : $this->pretty;
         }
 
+        $priority = null;
+        if (null !== $this->dispatcher) {
+            $priority = $this->dispatcher->getListenerPriority($eventName, $this->listener);
+            // if we try to get the priority while an event is dispatched the wrapper is registered so fallback here
+            if (null === $priority) {
+                $priority = $this->dispatcher->getListenerPriority($eventName, $this);
+            }
+        }
+
         return array(
             'event' => $eventName,
-            'priority' => null !== $this->dispatcher ? $this->dispatcher->getListenerPriority($eventName, $this->listener) : null,
+            'priority' => $priority,
             'pretty' => $this->pretty,
             'data' => $this->data,
         );
```

I think the problem is indeed that during dispatching the wrapped versions are registered and so getting the priority for the original listener fails as @stof also suspected.

**Comment by javiereguiluz** [comment]
@dmaicher I've just tested your solution and I can confirm that it fixes the problem to me. Thanks!

By the way, if you need a Symfony 3.2 app to do quick tests you can use the [Symfony Demo app](https://github.com/symfony/symfony-demo) which can be installed in just a few seconds.

**Comment by dmaicher** [comment]
@javiereguiluz ok cool :blush: Then I will prepare a PR later today.

True next time I will just use the demo app indeed :+1: Thanks for the tip.

**Comment by dmaicher** [comment]
Here is the fix: https://github.com/symfony/symfony/pull/22568
