### ISSUE TITLE
[cache component] Get all keys method

### ISSUE THREAD

**Issue by Francesco-Rizzi** [symfony/symfony#22524]
**Get all keys method**

http://symfony.com/blog/new-in-symfony-3-1-cache-component

It would be a very useful method, with the standard component I have not way to retrieve all keys store on redis (or whatever..) (I can only with a third-part library)...

maybe something like:
`$cache->getKeysByPattern('*')`;

I thinks it should be a base func. and I'm surprised that there is not.

**Comment by stof** [comment]
Getting the list of keys available in the cache store may not be possible for all implementations. And when it is possible, it may be very slow for some backends.
I think this is one of the reason why PSR-6 rejected having such method.

The Cache component is about implementing PSR-6 and PSR-16, not about inventing our own cache API

**Comment by nicolas-grekas** [comment]
Yep, same pov as Stof's, I doubt we should do anything. Keys discoverability doesn't scale, and has little to no business-related use cases.

**Comment by fabpot** [comment]
Closing then.
