### ISSUE TITLE
[Validator] Double validation in an unusual case

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#22538]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Hello everyone, as the title says, I have found another case of double validation.

My classes : 
```php
interface PriceInterface {}
interface VariantPriceInterface extends PriceInterface {}
abstract class AbstractPrice implements PriceInterface {}
class VariantSamplePrice extends AbstractPrice implements VariantPriceInterface {}
```

The validation constraints : 
```yaml
PriceInterface:
    getters:
        value:
            - NotBlank: ~
```

If you validate a `VariantSamplePrice`, the constraint is checked twice.

This case is taken from a real project. I reproduced the issue on my symfony-standard fork https://github.com/fancyweb/symfony-standard/tree/new-double-validation-issue. Just launch the local server and go on the homepage route.

Related issue https://github.com/symfony/symfony/issues/19943

**Comment by stof** [comment]
yeah, this could happen for constraints added on interfaces, because `AbstractPrice` receives the constraint, and `VariantSamplePrice` receives it a second time through its implementation of `VariantPriceInterface`

**Comment by fancyweb** [comment]
I'm working on a PR for this today.

**Comment by Simperfit** [comment]
@fancyweb did you find anything ?

**Comment by fancyweb** [comment]
From what I remember it's hard / kind of impossible to fix it nicely with no BC break. I tried two times to do so but I did not succeed. The explanation in the closed related PR is still valid.

A new savior for this bug is more than welcome 😄
