### ISSUE TITLE
[OptionsResolver] Is it possible to allow/ignore extra options?

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#22536]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

I have an array of options that has a subset that needs resolving, the rest of it is not important. Is it possible to ignore the rest of the array? 
A similar behavior to [Form allow_extra_fields](http://symfony.com/doc/current/reference/forms/types/form.html#allow-extra-fields)

Example: **email** and **phone** are required, everything else just doesn't matter.

````php
$options = [
    'email' => 'email',
    'phone' => 'phone',
    //many other keys
];

$resolver = new \Symfony\Component\OptionsResolver\OptionsResolver();
$resolver->setRequired(['email', 'phone']);
$resolver->resolve($options);
````
This obviously yields `UndefinedOptionsException`

**Comment by ro0NL** [comment]
Yes :) `$resolver->setDefined(array_keys($options))`

https://github.com/symfony/symfony/pull/12156

**Comment by skafandri** [comment]
so simple it made me laugh :))

very PHPish :)

**Comment by rvanlaak** [comment]
Came here via Google. Adding them to `setDefined` actually results in the the values being returned.

Our use case instead is to allow extra options without the `UndefinedOptionsException` gets thrown, but the options should not get resolved / outputted.

**Comment by kshtompel** [comment]
Agree with @rvanlaak
there should possibility to define options you are interested in to be resolved and to skip other

With this answer I define all options in all places where set of options are used or prepare them each time before I use them but it makes no sense to use OptionsResolver after I'd already prepared them

**Comment by ephrin** [comment]
For those who googled this page. `\Symfony\Component\OptionsResolver\OptionsResolver::setIgnoreUndefined()` can be used.
