### ISSUE TITLE
console process sometimes not executed

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#22545]
SYMFONY 3.2.2
APACHE 2.4.18
PHP 7.0.15
rights for writting into /tmp/ setted properly

for example:

console2:
```
#!/usr/bin/env php
<?php

$file = explode('=', $_SERVER['argv'][1]);
$file = $file[1];
file_put_contents('/tmp/file_'.$file.'.txt', "FILE = ".$file." ".date("d.m.Y H:i:s")."\n", FILE_APPEND);
```

RunAllTasksCommand.php
```
class RunAllTasksCommand extends ContainerAwareCommand {

    protected function configure() {
        $this->setName('run-all-tasks');
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        $projectRootDir = $this->getContainer()->getParameter("kernel.root_dir") . '/../';
        $basicString = 'cd '.$projectRootDir . ' && php bin/console2';

        // CODE ... ONLY ONE OF CASE 1-5
    }
}
```

try to add one of these cases

// CASE 1, result =everything working, but sync
$process = new Process($basicString.' --file=1');
$process->run();
$process = new Process($basicString.' --file=2');
$process->run();

// CASE 2, result =everything working, async
system($basicString.' --file=1 > /dev/null');
system($basicString.' --file=2 > /dev/null');

// CASE 3, result =sometimes not working, async
$process = new Process($basicString.' --file=1');
$process->start();
$process = new Process($basicString.' --file=2');
$process->start();

// CASE 4, result = same as CASE3
$basicString = 'PWD='.$projectRootDir . ' && php bin/console2';
$process = new Process($basicString.' --file=1');
$process->start();
$process = new Process($basicString.' --file=2');
$process->start();

// CASE 5, result = same as CASE3
$process = new Process('php ' . $projectRootDir.'bin/console2 --file=1');
$process->start();
$process = new Process('php ' . $projectRootDir.'bin/console2 --file=2');
$process->start();

I just want to execute Processes in Command without waiting for response (async)
If I run case 3 or 4 or 5 **more times really quick** (17 times in 10 seconds)  ... some processes or all processes are not executed

![result](https://cloud.githubusercontent.com/assets/4276289/25478247/b1096aea-2b40-11e7-8828-fd648ee812bf.png)
I can execute it every 5 second ... I can even execute ONLY one process ...  result will be same ... sometimes some processes will be not execute ... so **it doesn't matter how many processes or how often**
there are no error logs in symfony or apache
I also tried removing symfony cache ... restart apache ... result will be same

**Comment by viviengaetan** [comment]
Hey @poolerMF,

There is no issue here, your main process die right after the start of your sub-processes.
Sometimes the sub-process is faster to finish than its parent and sometimes not - leading to its end before it finished its work.

It's a PHP limitation - not a Symfony Process one.

You can read @jakzal [answer](http://stackoverflow.com/a/27609014) which give you advice on what to do if you really want background processes (Message Queue)

**Comment by jakzal** [comment]
Indeed, thanks for looking into this issue @viviengaetan 

Closing as this is an expected behaviour. See #20513 #20445 #12195 for more details.

To run the process asynchronously use message queues or the `kernel.terminate` event. For the later see: http://symfony.com/doc/current/components/process.html#running-processes-asynchronously

**Comment by YosraHamza** [comment]
@poolerMF did you find a solution for this issue ? it happens with me also randomly on nginx server

**Comment by poolerMF** [comment]
> @poolerMF did you find a solution for this issue ? it happens with me also randomly on nginx server

I used command "exec" instead of symfony process

**Comment by YosraHamza** [comment]
@poolerMF Thanks a lot.
