### ISSUE TITLE
[Process] A command containing slashes instead of backslashes should be quoted on Windows

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#22549]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3

On Windows it is possible to use `/` directory separator instead of `\` to run a command inside CLI. But to be able to run such a command the path needs to be quoted.

I am using SF 3.3 now but I guess this commit caused the BC break which is merged to many versions.
https://github.com/symfony/symfony/commit/3779f3fbb98db5fd1647fa8e2af84a05adb1c7a0#diff-bfb5d7f8e7485d053a135b3692e8a0ca

Thus also the example in this test is not correct. It would not work on Windows.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Tests/ProcessBuilderTest.php#L94

```
D:\Program Files>php\php -r "echo 'hello';"
hello
D:\Program Files>php/php -r "echo 'hello';"
Could not open input file: /php

D:\Program Files>"php/php" -r "echo 'hello';"
hello
D:\Program Files>
```

**Comment by nicolas-grekas** [comment]
Can you provide a reproducer test that we could add to the test suite?
The linked commit is applicable to non-Windiws OSes so that's really strange that you found it do have introduced the issue...

**Comment by maryo** [comment]
@nicolas-grekas You're right. I missed the last return inside the Windows condition and the `ProcessUtils::escapeArgument` is actually not used anymore since SF 3.3. That's the problem. OK, I'll send a PR in few minutes.
