### ISSUE TITLE
[Workflow] State machine can have multiple transitions with the same name

### ISSUE THREAD

**Issue by tomaszhanc** [symfony/symfony#22558]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

IMO state machine can have multiple transitions with the same name. For workflow (petri net) transitions must be unique, but it's not the case for state machine. Are you agree with me? If yes we can remove the uniqueness check from validator: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Validator/StateMachineValidator.php#L39

Of course it might be not the only change - I would like to check it and create a PR just first let me know if you would even consider to accept it?

**Comment by stof** [comment]
it does not require global uniqueness. It requires uniqueness of the name for a given start place for the transition.
You cannot have multiple transition with the same name and the same start place in a state machine (you can reuse the same name from another place, but this is already supported)

**Comment by stof** [comment]
@tomaszhanc Symfony 3.3 already supports this syntax 😄
