### ISSUE TITLE
DebugClassLoader can't load class AppKernel - wrong path

### ISSUE THREAD

**Issue by mikaelit** [symfony/symfony#22575]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

Hi,
this issus look like this:
```
Warning: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require_once([my_paht]\vendor\composer/../../pp/AppKernel.php): failed to open stream: No such file or directory in [my_paht]\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php:169
Stack trace:
#0 [my_paht]\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php(169): Symfony\Component\Debug\ErrorHandler->handleError(2, 'require_once(C:...', '[my_paht]...', 169, Array)
#1 [my_paht]\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php(169): require_once()
#2 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('AppKernel')
#3 [my_paht]\app\console(26): spl_autoload_call('AppKernel')
#4 {main}
  thrown in [my_paht]\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php on line 169
```

I think the bug is in the wrong path. From the path to AppKernel.php is stripped off 'a' in 'app':
`Equire_once ([my_paht] \ vendor \ composer /../../ pp / AppKernel.php)`

I have this problem in diffrent projects. In symfony 2.8.17 and 3.2.6

**Comment by stof** [comment]
can you show us the `autoload` section of your composer.json ?

**Comment by mikaelit** [comment]
In bouth verson of symfony::
```
"autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
```

**Comment by ro0NL** [comment]
Just to be sure.. you are using composer for autoloading right?

**Comment by mikaelit** [comment]
yes :)

**Comment by ro0NL** [comment]
What does spl_autoload_functions() look like before Debug::enable()? Or put differently; can you debug where the path gets messed up?

**Comment by mikaelit** [comment]
I looked in vendor where spl_autoload_functions() is with Debug::enabled(), but I did't find such function.
Could you tell me in which file I can find this?

I found only that the composer change path in autoload_classmap.php and autoload_static.php.

autoload_classmap.php
`    'AppCache' => $baseDir . '/pp/AppCache.php',
    'AppKernel' => $baseDir . '/pp/AppKernel.php',
`

autoload_static.php
`        'AppCache' => __DIR__ . '/../..' . '/pp/AppCache.php',
        'AppKernel' => __DIR__ . '/../..' . '/pp/AppKernel.php',
 `

But why?... where? I don't know.

**Comment by stof** [comment]
then, the bug is in composer, not in the Symfony DebugClassLoader. Please report it to Composer.

**Comment by mikaelit** [comment]
I figured out after research. ;)
