### ISSUE TITLE
Lock Component: keep it for 3.3?

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#22580]
Before I publish the first beta of Symfony 3.3, I have a question about the Lock component.

There are still some fundamental questions about some issues, and I'm not comfortable to publish it as is without good answers for some of them. Two possibilities: mark it as experimental or move it to 3.4. My personal preference would be to move it to 3.4 as there is no rush to have it in core IMHO.

Current PRs on the Lock component (not all are critical of course): https://github.com/symfony/symfony/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20lock

WDTY?

**Comment by nicolas-grekas** [comment]
I'm OK to postpone it for 3.4. We don't need to be in a hurry, and locking is complex. Better not introduce something that has open pending and not-trivial questions.

**Comment by jderusse** [comment]
Postponing it to 3.4 will give us time to polishing it (integration to framework bundle) and providing more reliable store for distributed lock.

**Comment by stof** [comment]
I'm also OK for postponing it to 3.4.

**Comment by nicolas-grekas** [comment]
@jderusse would you mind doing the removing PR please, then the reopening one once it's merged?

**Comment by jderusse** [comment]
I'm AFK this week end. Can't​ do it before Monday

**Comment by xabbuh** [comment]
:+1: for postponing it too

**Comment by bkielbasa** [comment]
I will use the component for sure, So it would be cool have it as experimental

**Comment by fabpot** [comment]
PR created. See #22590

**Comment by robfrawley** [comment]
Solid decision :+1:
