### ISSUE TITLE
How replace ExceptionCaster::filterTrace to ExceptionCaster::castTraceStub?

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#22583]
| Q                | A
| ---------------- | -----
| Bug report?      | –
| Feature request? | –
| BC Break report? | –
| RFC?             | –
| Symfony version  | 2.8

> The filterTrace method is deprecated since version 2.8 and will be removed in 3.0. Use the castTraceStub method instead.

Can not understand how should I change them. I have this code:
```php
$trace = $exception->getTrace();
ExceptionCaster::filterTrace($trace, false);
```
This code transforms `$trace` variable from
```
[
    [
        'function' => '%methodName%',
        'class' => '%FQCN%',
        'type' => '->',
        'args' => [/* ... */],
    ],
    // ...
]
```
to this format:
```
[
    [
        'call' => '%FQCN%->%methodName%',
        'file' => '',
    ],
    // ...
]
```

How can I do the same by using `ExceptionCaster::castTraceStub`? I'm tried to use It like this:
```php
        $trace = $exception->getTrace();
        $trace = ExceptionCaster::castTraceStub(
            new TraceStub($trace),
            $trace,
            new Stub(),
            true
        );
```

**Comment by nicolas-grekas** [comment]
@Aliance sorry for the delay. I'm not sure about what you want to do, but maybe the best is to copy/paste the implementation in you own code if you really need that transformation that way?

**Comment by Aliance** [comment]
@nicolas-grekas I preferred to use build-in functions (this is for logging purposes). The deprecated message tells me that I should change `filterTrace` to `castTraceStub`, can you help me with the example?

**Comment by nicolas-grekas** [comment]
I'd need more precise description of your input+output, but basically, you should just wrap the trace in a TraceStub, and let the cloner call castTraceStub for you.

**Comment by Aliance** [comment]
> basically, you should just wrap the trace in a TraceStub, and let the cloner call castTraceStub for you.

I read [this article](https://symfony.com/doc/2.8/components/var_dumper/advanced.html), but could not find any example.

As I described in the first post, I've tried this:
```php
        $trace = $exception->getTrace();
        $trace = ExceptionCaster::castTraceStub(
            new TraceStub($trace),
            $trace,
            new Stub(),
            true
        );
```

But it seems to be wrong code. The original code is: https://gist.github.com/Aliance/3e9b12090eb8f75d18ca7366fd75224c

**Comment by nicolas-grekas** [comment]
@Aliance do you still need this or did you find a way around?

**Comment by Aliance** [comment]
@nicolas-grekas nope, I find this code redundant and remove it from repo. But may be someone else needs this.

For me, this issue can be closed. Thanks!
