### ISSUE TITLE
PhpDumper cannot dump DefinitionDecorator

### ISSUE THREAD

**Issue by AlexeyKosov** [symfony/symfony#22595]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Currently, DefinitionDecorator calls the parent constructor with no arguments, and thus the `class` property is not defined. As a result, the container fails to compile and throws an exception: 

```
 1/1 RuntimeException in PhpDumper.php line 1446: Cannot dump definition because of invalid class name (NULL) 

 in PhpDumper.php line 1446
at PhpDumper->dumpLiteralClass('NULL') in PhpDumper.php line 760
at PhpDumper->addNewInstance(object(DefinitionDecorator), 'return ', '$this->services[\'foo\'] = ', 'foo') in PhpDumper.php line 421
at PhpDumper->addServiceInstance('foo', object(DefinitionDecorator)) in PhpDumper.php line 679
at PhpDumper->addService('foo', object(DefinitionDecorator)) in PhpDumper.php line 706
at PhpDumper->addServices() in PhpDumper.php line 155
```

It turns out using DefinitionDecorator in my case requires setting the `class` property explicitly all the time.

**Comment by chalasr** [comment]
Could you provide the failing code so that we can reproduce?

**Comment by chalasr** [comment]
Nevermind, I thought this was about 3.3. The following can be used to reproduce:

```php
$container = new ContainerBuilder();
$container->register('parent', Foo::class);
$container->setDefinition('child', new DefinitionDecorator('parent'));
(new PhpDumper($container))->dump();
```

Definition decorators are converted to definitions (merged with the parent one) at compile time. 
You have to either compile the container using `$container->compile()` or process it using the good pass `(new ResolveDefinitionTemplatesPass)->process($container);` before dumping it.

**Comment by AlexeyKosov** [comment]
I have to run the compiler pass with the `DefinitionDecorator` at the `PassConfig::TYPE_OPTIMIZE` stage so that it has access to the Doctrine's entity manager, is there any way I can make it work in this case?

**Comment by xabbuh** [comment]
@AlexeyKosov What do you mean with "that it has access to the Doctrine's entity manager"? Do you get an error? What does it look like?

**Comment by AlexeyKosov** [comment]
@xabbuh Sorry if I wasn't clear.
I mean that I add the compiler pass with the `optimize` type and it actually runs after all the definition decorators are compiled so it throws the above-mentioned exception.
Why I need to run the compiler pass at the `optimize` stage rather than at the default one (`beforeOptimization`) is because I need to have access to some services from the container (for instance, entity manager) in the compiler pass.

`
class FooBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container);
        $container->addCompilerPass(new BarCompilerPass(), PassConfig::TYPE_OPTIMIZE);
    }
}
`

**Comment by xabbuh** [comment]
Using services during the compilation of the container is not something one should do. And registering services dynamically based on the results of a query looks weird to me.

**Comment by AlexeyKosov** [comment]
@xabbuh, you're right, it wasn't a good idea, I've already refactored it and registered a factory for those services in the container.
Just to sum up: in v.3.2 `DefinitionDecorator`s don't work if the compiler pass runs at the stage different from `beforeOptimization`.
