### ISSUE TITLE
Add HTML5 input type color in Form Component  

### ISSUE THREAD

**Issue by sblondeau** [symfony/symfony#22596]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi
The HTML5 input type "color" does not exist on Symfony Form component. https://symfony.com/doc/current/forms.html#text-fields

However, this form type works well is most of modern browsers like Firefox or Chrome. http://caniuse.com/#feat=input-color

It would be very interesting to add it with an automatic validation of hexadecimal color format.
Thanks !

**Comment by xabbuh** [comment]
Is this something that is commonly wanted (I never had such a need)? I am not sure if this is something that really should be part of the core.

**Comment by sblondeau** [comment]
Yes, it could be very useful; i.e add a custom color to a new product category.
There are almost all HTML5 input types in Symfony (UrlType, EmailType, ...), why color type would be missing ?

**Comment by javiereguiluz** [comment]
@xabbuh regardless of the popularity of this input (which I don't know) in my opinion the Form component should at least include all the form field types defined in the HTML 5 standard: https://www.w3.org/TR/html5/forms.html

**Comment by maidmaid** [comment]
By opening your link @javiereguiluz, I notice than we could add for example a [telephone input](https://www.w3.org/TR/html5/forms.html#telephone-state-(type=tel)) type.

**Comment by Nek-** [comment]
Hello. I'm 👍 with this feature. I had to implement the color type in many projects. With validator as well. That could (should) be handled by Symfony once for all. :)

And I'm also 👍 with Javiere of course.

But about the telephone it's... Complicated. I think it should be handled just like the email type with a recommended package for more checks.

**Comment by Hanmac** [comment]
yeah telephone is a bit complicated, specialy if we want non-american telephone numbers too.
that means that Validator might not be that simple to add.
or we connect it with Country Type and do country specific telephone format.

**Comment by ro0NL** [comment]
lets keep telephone simple; no validation :)

> Note: Unlike the URL and E-mail types, the Telephone type does not enforce a particular syntax.

https://www.w3.org/TR/html5/forms.html#telephone-state-(type=tel)

**Comment by garak** [comment]
Sadly, I just tried to do the same proposal 4 years ago (about type tel), it was rejected. See #8026
