### ISSUE TITLE
Add option of entity or bundle when doing doctrine:schema:create

### ISSUE THREAD

**Issue by MicWit** [symfony/symfony#22606]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | N/A

I wanted to look at what sql was being run in a bundle I was installing, and so used
` php bin/console doctrine:schema:create --dump-sql
`
This came up with a lot of SQL, and in some cases, it would be nice to be able to just create or update one entity or entities under 1 bundle. When I looked into it, there is the option of using one entity manager, but that generally isn't going to help with vendor bundles etc.

So it would be nice to get an option on the  console command for schema create or schema update to select just one entity or any entity within a bundle (I understand that the bundle option may be hard to do, but if we could just do it by one, or maybe a number of entities, we could just look in the bundle at the entity names).

So then we could do something like
` php bin/console doctrine:schema:create --dump-sql --entities=[entity1,entity2]
`
and narrow down which entities are affected.

Not sure if this would be a Symfony feature or if it would need to be added in Doctrine first?

**Comment by xabbuh** [comment]
This command is part of the DoctrineBundle which extends a command that is part of the Doctrine 2 library. You will have to ask for this feature in the Doctrine project.

**Comment by javiereguiluz** [comment]
@MicWit I've moved your issue to the repository mentioned by @xabbuh: https://github.com/doctrine/DoctrineBundle/issues/656

Thanks!
