### ISSUE TITLE
[DI] Fully support PHP constants

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#22600]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (well yes and no actually)
| BC Break report? | no
| RFC?             | no (well yes and no actually)
| Symfony version  | 3.4

Actually, the DI component has a limited support of PHP constants. e.g, in xml you can use `<argument type="constant">FOO</argument>`. So far, so good. But then, it is resolved, and thus when dumped, if my constant has a `bar` value, will not appear as `FOO` as expected, but as `"bar"` (note the `"`s).

Thus, if you compile the container on a say "build" machine, deploy the generated code to several other machines, and want to tweak the constant (e.g, a `DEBUG_STATUS` constant) on a signle machine, as it is already resolved on the build machine, you will never be able the tweak said value without having to rebuild the container (which you may not be able to on said machine ; think as if it is somebody else wanting to do the task, not having a clue that you have to do something other than "tweaking the constant").

A solution could be to either support in the `Definition` (Or maybe like the closure proxy arguments, through `ClosureProxyArgument` class) the constants, and thus when dumped just dumps the constant name, or use a placeholder like in the env behavior. If it were up to me. I think the first solution would be more elegant (and could pass the config too, see #22594).

**Comment by fabpot** [comment]
Not sure I understand the use case. If you "built" the code/container, any change to the PHP code must triggers a recompile. I suppose you're not changing a PHP constant value in production anyway. It looks like what you want is to use an env var instead.

**Comment by Taluu** [comment]
Actually these constants are used as configuration values (like parameters), even though we are thinking of migrating to current standards (parameters + env vars you described it in https://github.com/symfony/symfony/issues/22151#issuecomment-289128970). Values like `DEBUG_[feature name]` and things like that.

So yes, we are sometimes changing constants on production env (disabling things, re-enabling other things, ... etc), and expect the changes to be reflected on the production code without having to do anything else. And most of the time, we may not know the constant values on build time, as the constants file is built through another task. Hence the fact that we need that constants are not resolved on the compile step, but on the runtime. 

This is indeed like env vars, but we chose not to burn steps while migrating our legacy (constants driven configuration) to current standards.

I could make a sort of pass on the generated code to replace things like `"CONSTANT_[constant name]"` to `[constant_name]` but it feels hackish. With the same problem as reported in #22594. as the config component would not really like this. But as I said, it is a legacy, so it should be fine... Even though I still think that constants should be fully supported by the config and di components.

**Comment by fabpot** [comment]
Closing as this is an edge case we don't want to support in Symfony.
