### ISSUE TITLE
[FrameworkBundle] Translation component should be required

### ISSUE THREAD

**Issue by regularjack** [symfony/symfony#22617]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.8

The `TranslatorHelper` in the FrameworkBundle [uses](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/Templating/Helper/TranslatorHelper.php#L15) `Symfony\Component\Translation\TranslatorInterface`.

However, the translation component [is not](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/composer.json#L18) in the `require` section of `composer.json` but in the `require-dev`.

The translation component should be in the `require` section of `composer.json`.

**Comment by javiereguiluz** [comment]
I think the solution should be the opposite: enable the translation helper only if the translation component is installed. I don't know if that's already done or not (lately we changed a lot of things to enable them conditionally depending on the installed components).

**Comment by Hanmac** [comment]
the DependencyInjection does handle that:
https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L861-L863

means if Translator is not loaded, it does remove the translation helper

**Comment by javiereguiluz** [comment]
@regularjack as @Hanmac showed, this is already done in Symfony 3.3 beta1, so I'm closing it as fixed. Thanks!
