### ISSUE TITLE
[Console] Issues when rendering nested exceptions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22618]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | all

When upgrading an app to Symfony 3.3 beta, an exception is triggered when using the `framework.trusted_proxies` option. I guess this BC break is OK because security, etc. But as you can see, the Console component has some issues when rendering nested exceptions:

![nested_exceptions](https://cloud.githubusercontent.com/assets/73419/25651937/f35c9a8a-2fe5-11e7-9e7e-42d833ded0a5.png)

**Comment by ro0NL** [comment]
It happens from the sensio distribution script handler, making it hard to fix; see https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L293

We need to remove decoration here, i guess, from the previous (erorr) output. However we're in a compsoser script handler, without a dependency on symfony/console. I.e. we cannot call `Helper::removeDecoration` or so...

Maybe just remove the duplicated output here;

![image](https://cloud.githubusercontent.com/assets/1047696/25664488/0b5ed9f6-301b-11e7-8de5-d32edac96326.png)

The original exceptions are already shown, the CLI signature as well. Question is what would be the exception message then.. simply `An error occured`?

Status: reviewed

**Comment by stof** [comment]
@ro0NL the composer script handler runs inside the composer process itself, and so it has access to the symfony/console component shipped by composer itself.

**Comment by ro0NL** [comment]
Also sort of duplicated #22618 :P

**Comment by ro0NL** [comment]
@stof are you sure?

```
PHP Fatal error:  Call to undefined method Symfony\Component\Console\Helper\Helper::removeDecoration() in /projects/sf/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php on line 294
```

**Comment by ro0NL** [comment]
Never mind; it's a new method which is not available yet :) Also we need a formatter from the output+error output. Not sure we can get both.

**Comment by chalasr** [comment]
@ro0NL the called method is 3.3+, I guess composer ships a stable version.
Also, I think this is due to the terminal width not being set through composer scripts (see https://github.com/symfony/symfony-standard/issues/1026, probably the same issue).

**Comment by stof** [comment]
@chalasr it ships 2.8, due to the min PHP requirement (composer still supports PHP 5.3 currently)

**Comment by chalasr** [comment]
Backporting https://github.com/symfony/symfony/pull/19724 to 2.8 should fix this.

**Comment by ro0NL** [comment]
`removeDecoration` is backported as wel :tada: we needed it to fix lower branches. 

Available since 2.8.19, composer runs 2.8.18. So we're close :) but im not sure we can get a right formatter instance from composer's IO :thinking:

**Comment by ro0NL** [comment]
Are you sure? We still need to remove decorations from it right?

![image](https://cloud.githubusercontent.com/assets/1047696/25666565/2b664134-3021-11e7-8f21-3d1b9cceee60.png)

However.. by now i think we dont really need `removeDecoration` actually, a simple `preg_replace("/\033\[[^m]*m/", '', $string);` would do.

**Comment by chalasr** [comment]
Not tried out yet but the ticket fixed by #19724 being quite similar I think it would be the proper fix (the command is run in a symfony Process ran by the script handler which is itself ran in a composer process, it needs the `COLUMNS`+`WIDTH` env vars to be set).

**Comment by ogizanagi** [comment]
Not sure #19724 and backporting the `Terminal` class would help actually. I tried to manually compile composer with `symfony/console` 3.3, and the result is even worth.

<img width="1474" alt="screenshot 2017-05-03 a 17 03 59" src="https://cloud.githubusercontent.com/assets/2211145/25667047/9b92ea42-3022-11e7-9bb2-20807ffcea4f.PNG">

But I confirm the `preg_replace` solution mentionned by @ro0NL should work actually.

**Comment by ro0NL** [comment]
Removing the decoration seems to fix both issues...

https://github.com/sensiolabs/SensioDistributionBundle/pull/317
