### ISSUE TITLE
New exception pages don't work when WebProfilerBundle is not installed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22631]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3

I was playing with Symfony Flex when I noticed this:

---

Create a project with Symfony Flex:

```bash
$ composer create-project symfony/skeleton:3.3.x-dev my_project/
$ cd my_project/
$ make serve
```

Browse http://localhost:8000/

**Problem 1**: I still see the old exception page design ... because TwigBundle is not installed. I'll propose a solution for this in a separate issue.

---

Install TwigBundle:

```bash
$ composer req twig-bundle
```

Browse http://localhost:8000/

**Problem 2**: I can see the new design ... but everything is broken because the JavaScript features are not enabled because we link to `src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig` and that file does not exist (because WebProfilerBundle is not installed).

---

Install WebProfilerBundle:

```bash
$ composer req profiler
```

Browse http://localhost:8000/

**Now everything works as expected**.

---

TwigBundle is not "a real bundle" because is not standalone. If WebProfilerBundle is not installed too, it doesn't work.

**Which solution do you propose?** The obvious one would be duplicating the WebProfilerBundle's `base_js.html.twig` file in TwigBundle too. What do you think?

**Comment by iltar** [comment]
Can't we make the profiler bundle a dependency of the twig bundle? Seems like the profiler is required.

**Comment by javiereguiluz** [comment]
The opposite behavior also happens and it's frustrating:

```bash
composer create-project symfony/skeleton:3.3.x-dev my_project/
$ cd my_project/
$ composer req profiler
$ make serve
```

But you don't see the debug toolbar or the profiler interface ... because TwigBundle is not available. So you must run this too:

```bas
$ composer req TwigBundle
```

**Comment by fabpot** [comment]
Duplicate the file.
