### ISSUE TITLE
[Console] Add a way to remove commands

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#22645]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

symfony/console is awesome, and could be more powerfull with a simple feature : **remove commands**.

For example, in `dev` env, all `doctrine:*` commands are usefull, but not in `prod` env.
Today, i can call `doctrine:schema:update` in `prod`, i can't block it.

I think this feature could be added easily, by adding a new configuration like `framework.console.removeCommands: []` and read it in `Symfony\Bundle\FrameworkBundle\Console\Application::registerCommands()`.

We can add `Symfony\Component\Console::remove($name)` too, in case we use symfony/console outside Symfony.

If you want, i can do it, cause i need it :)

**Comment by iltar** [comment]
This would be a lot easier if all the information about a command, wouldn't require its initialization. Because even here, by removing a command, you have to exclude it based on the name, which isn't known until you  instantiate the command.

**Comment by steevanb** [comment]
Not really : you know commands you don't want to appear, or be used. No need to instantiate anything, just list names :)

**Comment by iltar** [comment]
@steevanb but that's how commands work. The command has to be initiated as the name is the constructor argument: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Command/Command.php#L66

**Comment by steevanb** [comment]
I see... for now, we can't have it's name before instantiate it, true.

So we can call $application->add() only when needed :
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Bundle/Bundle.php#L193

**Comment by iltar** [comment]
This feature would be a lot easier to implement if we could have all the information available without initiating the command class, name, options, arguments, help text etc.

**Comment by steevanb** [comment]
But we can't, and i don't think it will change soon :)

**Comment by chalasr** [comment]
yeah, that would be really hard regarding BC and separating definitions from command themselves has been rejected already.

Having them already initialized is too bad yes, but this is asking for the ability to remove a command which _can_ be supported since commands are _given_ initialized to the application via `add(Command $command)`  then mapped by name (any command included in the application is initialized currently), adding `remove($name)` should be trivial (we have `has()` already).

About support for laziness in the console, I think it's a must have for 4.0. I'm working on a proposal.

**Comment by steevanb** [comment]
I've done it here : https://github.com/huttopia/console-bundle

Easy as hell, just need it in Symfony ;)

**Comment by robfrawley** [comment]
@steevanb It's not that we don't think you can do it, but that @iltar it unhappy commands need to be initialized regardless (which, if I'm not mistaken, *everyone* is unhappy about), but the secondary issue isn't related here. Cary on with a pull request pertaining to your original idea if you'd like.

**Comment by iltar** [comment]
What if you block commands based on FQCN instead?

**Comment by steevanb** [comment]
I can't, cause different FQCN can have same command name ;)

**Comment by iltar** [comment]
Different classes shouldn't have the same command name afaik. In theory this should even be 1:1, though not enforced.

**Comment by steevanb** [comment]
Not sure about it. You could override command name, to me, that's ok, i need it :)

**Comment by COil** [comment]
I dropped a production database recently by launching a doctrine loadf-fixtures script on the wrong server... so sure it will be usefull. :rofl:

**Comment by ro0NL** [comment]
For what it's worth i'd like to remove the assets:install command; so :+1: if we can do something here.

> About support for laziness in the console, I think it's a must have for 4.0. I'm working on a proposal.

@chalasr any news? :P i was thinking to move command definitions to a static method (that would ease things right?)

**Comment by stof** [comment]
@ro0NL that would be a huge BC break, as it would forbid relying on state of the object during the definition (so forget about configuring some settings in the command constructor, which is currently possible)

**Comment by chalasr** [comment]
@ro0NL Having the command name and aliases are enough to make `get()/find()` lazily loading commands. Making `getName()` and `getAliases()` static would help, but that would be hard to do regarding BC.

**Comment by chalasr** [comment]
> @chalasr any news?

Almost there, based on tags (`<tag name="console.command" command="server:run" />`)

**Comment by steevanb** [comment]
You can close this issue.
I've done it on my side, and im' not sure they way this issue is taking is the right one :)

**Comment by COil** [comment]
@steevanb what did you do?

**Comment by steevanb** [comment]
https://github.com/huttopia/console-bundle

Just override Symfony\Bundle\FrameworkBundle\Console\Application, to add console.excluded configuration :)

**Comment by javiereguiluz** [comment]
It's not as easy as using a config option, but you can use the `ConsoleEvents::COMMAND` event to check if the command about to be executed is in a blacklist defined by you and then, stop the execution of the command. See https://symfony.com/doc/current/components/console/events.html

**Comment by steevanb** [comment]
Nice way to do it, but i prefer mine, cause with event command appears in list, and i don't want :)

**Comment by nicolas-grekas** [comment]
This feature request is a side effect of commands autodiscovery, isn't it?
Instead of adding this feature, I think we can just implement #23488.
Then, commands will be easily removable with a compiler pass.

**Comment by chalasr** [comment]
Agree with @nicolas-grekas. Registering commands as services is the new way to go, writing such pass should be trivial (we could give an example in the docs?). Let's close

**Comment by TomasVotruba** [comment]
This would be great feature, just need it :)

**Comment by stof** [comment]
for commands defined as services, the solution is to skip registering the services. If you use automatic class discovery for a folder, the `#[When]` attribute solves the conditional registration of services (if you register services explicitly, the condition has to go around that explicit definition)

**Comment by TomasVotruba** [comment]
I need to remove one of default ones to make `list` output more readable for 1-2 command apps.

**Comment by stof** [comment]
Please open a dedicated issue to discuss that need then instead of doing that on an issue closed 6 years ago.

**Comment by TomasVotruba** [comment]
I don't think there is enough interest, based on previous chat. 
I found a better way using private accessor :+1:
