### ISSUE TITLE
[DI] Tag subscribers for collecting tagged services?

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#22649]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Service subscribers can be used by services knowing exactly what services they need (requires a static list of identifiers), creating service locators from a compiler pass remain the only way to collect and map services corresponding to a given tag, injecting the locator by hand into the requesting service.

Would it be interesting to give the ability to service subscribers to request all registered services for a tag (tagged services subscribers)? This could be done by introducing a variant of ServiceSubscriberInterface like:

```php
interface TagSubscriberInterface
{
    public function getSubscribedTag()
    {
        return [
            'console.command', // request access to services tagged "console.command"
            'console.command' => Command::class // skips non Command subclasses
        ];
    }
}
```

It would remove the need for creating compiler passes that are dedicated to collect services without performing any special treatment on those.

**Comment by ro0NL** [comment]
Does it conflict with #22200?

> It would remove the need for creating compiler passes that are dedicated to collect services without performing any special treatment on those.

We're more or less solving the same issue.. right? Not sure.. but tend to favor a config-only approach...

**Comment by nicolas-grekas** [comment]
I also prefere config based approach. ServiceSubscriberInterface is generic and has nothing specific to Symfony: it just gives more info about the way some code works. This TagSubscriberInterface would require something really specific for Symfony internals.
We'd better make writing some compiler passes easier - or not required thanks to generic config, as #22200 tries to do, IMHO.

**Comment by chalasr** [comment]
I missed #22200, I agree. 
Btw, it makes me think that we should not have fully replaced `!service_locator { foo: @foo1}` (that I would rename as `!map: { foo: '@foo1'l }` today), it is nice for people which do not want DIC-specific stuff into IMHO.
Closing then, thanks for your thoughts.

**Comment by ro0NL** [comment]
@chalasr :+1: for `!map { }`

That way #22200 can leverage !map + !iterator, and introduce !tagged_map + !tagged_iterator.. i like that :)

wdyt?

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/issues/12269#issuecomment-279000328 :) 
that would be nice I think

**Comment by ro0NL** [comment]
Agree.. then again it adds complexity by creating nested structures (ie. what does `!tagged  'foo'` do by itself?) It becomes very DSL-ish :) not sure we should go that way.

**Comment by chalasr** [comment]
Agreed

**Comment by GuilhemN** [comment]
The yaml spec [defines the `!!map` tag](http://yaml.org/type/map.html), also having a `!map` tag would be confusing imo.
