### ISSUE TITLE
[DX][WebProfiler] Translation panel locale information

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#22643]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | 
| Symfony version  | >=2.7

Hi

Currently on the web profiler (2.8), in the translation panel, i did not see info about the locale as a reminder information
I think it could be very usefull to remind the developer about the locale(s)

- session locale (if its override the default)
- request locale (if its override the default)
- default locale (parameter)

What do you think?

(If it is already done on 3.X branch, just close the PR)

Thanks!

**Comment by stof** [comment]
the locale is already displayed in the profiler in Symfony 3.3 in the configuration panel, together with the default timezone: http://symfony.com/blog/new-in-symfony-3-3-improved-the-profiler-configuration-panel

**Comment by javiereguiluz** [comment]
@stof even if you are right ... I think @noniagriconomie asks to display more information about the locales from Symfony, PHP, your app, etc. I might send a PR for this.

**Comment by noniagriconomie** [comment]
@stof @javiereguiluz exactly, i think in the translation panel it will be good to remind the dev that for the current request he is profilingg the session was defined as followed

**Comment by stof** [comment]
why are you talking about the session now ?

**Comment by noniagriconomie** [comment]
-session+locale
My bad
