### ISSUE TITLE
[Proposal] Use explicit global namespace for PHP version constants

### ISSUE THREAD

**Issue by stof** [symfony/symfony#22650]
I just checked how PHP compiles the access to constants, to see what OPCache can eliminate.

As such, I suggest using explicit namespacing of constants rather than relying on the fallback when doing PHP version checks with `PHP_VERSION_ID`. When relying on the fallback, it does not allow to compute the PHP version check at compile time: https://3v4l.org/UrXY7/vld#output

The VLD output still shows the else branch in the output, but it is dead code (as the jump over it is not conditional anymore). Note sure if it is because OPCache does not delete dead code, or because VLD stores the opcodes before the end of optimizations. I haven't tried to dump the opcodes from OPCache directly (which is possible with phpdbg on 7.1+)

**Comment by javiereguiluz** [comment]
Maybe @jpauli can share his expertise about this topic and validate/reject this proposal. Thanks!

**Comment by ro0NL** [comment]
:+1:  it makes the code side effect free - https://3v4l.org/p2JU0

**Comment by flip111** [comment]
@stof did you only check with the 3v4l.org website? afaik the opcache is only effective with sapi interface, in case 3v4l starts your code snippet under a cli instance of php opcache is not enabled (this is likely to happen).

**Comment by jpauli** [comment]
:+1:

This is true for every internal constant.
You should use \PHP_VERSION_ID to make comparisons.
This way, OPCache will be able to optimize the code at compile time.
If you run in CLI (like 3v4l), don't forget the opcache.enable_cli=1  , you'll then see that OPCache evaluates.

**Comment by javiereguiluz** [comment]
Now that this proposal has been validated ... could we implement it before 3.3 release ... or is it too late now?

**Comment by stof** [comment]
@fabpot @nicolas-grekas what do you think about doing this for other internal constants too, to allow compile-time resolution of constants (even though they are less likely to trigger dead code trashing than `PHP_VERSION_ID`) ?

**Comment by jpauli** [comment]
It can only be good for PHP runtime. I think it doesnt alter the code visibility too much, so I myself would be :+1: for that
