### ISSUE TITLE
BrowserKit: Cannot use object of type GuzzleHttp\Psr7\Uri as array

### ISSUE THREAD

**Issue by dstuecken** [symfony/symfony#22654]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3-dev

I am using the browser kit to crawl some websites and I am getting this error:
Uncaught Error: Cannot use object of type GuzzleHttp\Psr7\Uri as array in vendor/symfony/browser-kit/Client.php:546

Seems like the URI instance has to be explicitly converted to string so that it makes use of the __toString implementation.

**Comment by Federkun** [comment]
I'm not sure we can define that as a bug. After all, the `request` method require a string as a Uri. Since the component don't complain to psr7, I think you should cast the Uri obj to string beford your `request`.

**Comment by dstuecken** [comment]
Oh true, you're right. I'll better do that!
