### ISSUE TITLE
How to fix this permission error?

### ISSUE THREAD

**Issue by hemrajpal** [symfony/symfony#22651]
Sometimes get this warning.

ContextErrorException in FileProfilerStorage.php line 158: Warning: file_put_contents(/var/www/html/var/cache/dev/profiler/c9/73/fb73c9): failed to open stream: Permission denied

How to solve this problem?

**Comment by Federkun** [comment]
You already opened a question here: http://stackoverflow.com/questions/43817267/how-to-fixed-this-symfony-permission-error

**Comment by hemrajpal** [comment]
How to solve this problem?

**Comment by xabbuh** [comment]
I am closing here as we do not use GitHub for support questions. Thank you for understanding. :)
