### ISSUE TITLE
[PropertyAccess] Incompatibility with PHP 7.2 PCRE

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#22667]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

https://github.com/php/php-src/pull/1303
https://github.com/php/php-src/commit/c832ab4de68485df67d09ebb8d2bf55b658c5e30

According to these changes in PHP 7.2 non-matched groups are never represented as `''` for PHP 7.2, now they are represented as `null`. This causes `Form` component fail to set the property as `PropertyPath` internally matches the paths and checks for empty string here:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyPath.php#L101-L102

I think the easies way to fix this is to cast `matches[2]` to string

**Comment by nicolas-grekas** [comment]
CLosing as this should be resolved soon in php-src master.
