### ISSUE TITLE
Symfony Flex + phpunit

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#22661]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | 
| BC Break report? |
| RFC?             | 
| Symfony version  | 3.3.dev

I'm using Symfony Flex and now I'm trying to make some functional tests to that project and it seems like `KernelTestCase.php` file method `protected static function getKernelClass()` doesn't work with flex Kernel.php which have namespace defined:

```php
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Component\Routing\RouteCollectionBuilder;

/**
 * @author Fabien Potencier <fabien@symfony.com>
 */
final class Kernel extends BaseKernel
...
```

And then if we take a closer look about that method:

```php
protected static function getKernelClass()
{
    if (isset($_SERVER['KERNEL_DIR'])) {
        $dir = $_SERVER['KERNEL_DIR'];

        if (!is_dir($dir)) {
            $phpUnitDir = static::getPhpUnitXmlDir();
            if (is_dir("$phpUnitDir/$dir")) {
                $dir = "$phpUnitDir/$dir";
            }
        }
    } else {
        $dir = static::getPhpUnitXmlDir();
    }

    $finder = new Finder();
    $finder->name('*Kernel.php')->depth(0)->in($dir);
    $results = iterator_to_array($finder);
    if (!count($results)) {
        throw new \RuntimeException('Either set KERNEL_DIR in your phpunit.xml according to https://symfony.com/doc/current/book/testing.html#your-first-functional-test or override the WebTestCase::createKernel() method.');
    }

    $file = current($results);
    $class = $file->getBasename('.php');

    require_once $file;

    return $class;
}
```

We see that there is nothing to handle namespace of that Kernel class.

And below `phpunit` stacktrace:

```bash
1) App\Tests\Functional\Controller\DefaultControllerTest::testThatDefaultRouteReturns200
Error: Class 'Kernel' not found

/home/wunder/PhpstormProjects/symfony-flex-backend/vendor/symfony/framework-bundle/Test/KernelTestCase.php:172
/home/wunder/PhpstormProjects/symfony-flex-backend/vendor/symfony/framework-bundle/Test/KernelTestCase.php:148
/home/wunder/PhpstormProjects/symfony-flex-backend/vendor/symfony/framework-bundle/Test/WebTestCase.php:33
/home/wunder/PhpstormProjects/symfony-flex-backend/tests/Functional/Controller/DefaultControllerTest.php:22
```

**Comment by ogizanagi** [comment]
As suggested on Slack, I'd propose to add a new `KERNEL_CLASS` env var we'll set by default in the `phpunit.xml.dist` provided by flex through recipes, rather than using `KERNEL_DIR`, so that `KernelTestCase::getKernelClass()` could use it, with highest priority.

**Comment by tarlepp** [comment]
Yep that is one option to solve this, want to know if someone figures different ways to complish this.

**Comment by fabpot** [comment]
@ogizanagi Sounds like a good idea. Would you like to submit a PR?

**Comment by sstok** [comment]
Now that the Kernel is namespaced and autoloadable I would rather recommend to use something like:

```php
protected static function getKernelClass()
{
    return \App\Kernel::class;
}
```

As it's less error prone when refactoring (with PHPStorm). Rather here or in phpunit.xml.dist you need to define it somewhere :)

**Comment by ogizanagi** [comment]
See #22668.

Overriding the `KernelTestCase::getKernelClass()` is a great solution currently, but it requires to override it (or create new base classes just for that in userland) for each KernelTestCase/WebTestCase child.
When using flex, we need a ready-to-go solution.
But you're truly right about refactoring. I added a `class_exists` check and threw a proper exception to help. Also, when refactoring, there is only one place to update (in addition to the kernel itself).

**Comment by dtfafard** [comment]
@ogizanagi Do you have a code sample of this?

**Comment by tarlepp** [comment]
@dtfafard in your `phpunit.xml.dist` file inside the `<php>` tag just add `<env name="KERNEL_CLASS" value="App\Kernel" />` and that should do the trick.

[Full  example](https://github.com/tarlepp/symfony-flex-backend/blob/master/phpunit.xml.dist#L16)

**Comment by dtfafard** [comment]
Thank you @tarlepp for the example. I managed to add the App\Kernel class with its own path. The goal for flex is to avoid doing additional work so I would suggest to add this in the Flex Script.
