### ISSUE TITLE
[Console] Apps can no longer expect their fatal error handlers to be triggered

### ISSUE THREAD

**Issue by ciaranmcnulty** [symfony/symfony#22678]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.8

There is a behaviour change in this version; previously a `Throwable` that occurred during a console command's `run` would be thrown upwards. It's now caught and turned into an `Exception`.

The change in question is here:
https://github.com/symfony/symfony/pull/22435/files#r115471431

For an example of how this causes an issue, in PhpSpec we maintain a `2.5` bugfix branch that does not know how to handle Throwables, instead relying on a mechanism that uses `register_shutdown_function` to format a nice error message when a fatal error occurs. As of Symfony 3.2.8 this message is no longer shown, because the shutdown function never executes.

This is something we could of course code around, but it's not a change I'd expect to be introduced in a patch.

**Comment by chalasr** [comment]
I confirm the bug, up to master. console.exception|error listeners should be able to handle throwables, but if they don't, the exception should reach the error handler, which is not the case anymore (neither the Debug one nor custom error handlers are reached).

**Comment by chalasr** [comment]
@ciaranmcnulty Could you try #22690?
