### ISSUE TITLE
Symfony Profiler Broken in 2.8+

### ISSUE THREAD

**Issue by alexgurrola** [symfony/symfony#22671]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.8+

We have a system of Load Balancers and Web Servers, so we use Database Storage for the Profiler, which has somehow become deprecated and removed in 2.8+, which will keep us from ever upgrading in the future.  Is there any alternatives for retrieving this logic or will we be forced to create our own extensions for future use?

Location:

https://github.com/symfony/symfony/tree/2.8/src/Symfony/Component/HttpKernel/Profiler

**Comment by javiereguiluz** [comment]
You are right. We deprecated all profiler storages in #15944. I don't think they will be introduced in the future, so the solution is the one you suggested: create your own profiler storage. In this case, it could be as simple as copying the original Symfony database storage that you used before.

**Comment by alexgurrola** [comment]
@javiereguiluz Thanks for your help.  We decided to maintain a copy of the ProfilerStorage Handlers for the foreseeable future.  If there's any other advice going forward, we're all ears.  😄

**Comment by alexgurrola** [comment]
Update: We created a composer package with the necessary code to keep these ProfilerStorage Handlers easily installed, configured, and maintained.  The package is located here: [ProfilerStorageBundle](https://packagist.org/packages/sitetheory/profiler-storage-bundle)

**Comment by weaverryan** [comment]
Thanks @alexgurrola!
