### ISSUE TITLE
[Yaml][DependencyInjection] references across files are broken

### ISSUE THREAD

**Issue by ivoba** [symfony/symfony#22698]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

Since release 3.2.8 Yaml references across imports do not work anymore and fail with:

> Reference "my.reference.from.file1" does not exist at line 1 (nea  
>   r "test.in.file2: *my.reference.from.file1").

This probably was introduced with https://github.com/symfony/symfony/pull/22351 by @xabbuh 

Test Scenario

file1.yml
```
vars:
    foo: &my.reference.from.file1
      baz: foobar
```
file2.yml
```
othervars:
  zigzag: *my.reference.from.file1
```
config.yml
```
imports:
  - { resource: "./file1.yml" }
  - { resource: "./file2.yml" }
```
I suppose the YamlFileLoader calls the Parser->parse() on every import and since the $this->refs array is resetted in parse() the references are missing on 2nd parse run.

Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:396

Imports are not part of the YAML spec afaik, so the bug might rather be a part of the YamlFileLoader.

**Comment by xabbuh** [comment]
To me this is something that used to work accidentally. References are not meant to be used across documents and only the fact that the parser did not clean up its internal state made this work somehow.

**Comment by fabpot** [comment]
I agree with @xabbuh, that's not a supported feature. Closing as a won't fix.

**Comment by BowlingX** [comment]
mh, even though it worked accidentially, it worked before, and this is a breaking change. Maybe it should be included in a minor release instead of a patch release. Would it not make sense to import references to share common configuration? At least for the current import scope.

**Comment by stof** [comment]
@BowlingX I would actually argue that this fixes could even be considered as a security fix. This was equivalent to reading memory you don't own.

And sharing references between files won't happen. References are part of the YAML spec. Imports are not. The importing is a feature of the DI component, which parses some data, then reads a specific part of it to decide it should also load extra data (which may not even be in the same format).
