### ISSUE TITLE
[Process] wait() - proposal to softcode sleeping time

### ISSUE THREAD

**Issue by and800** [symfony/symfony#22697]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

The current implementation of `wait()` sleeps for 1 ms between process state checks. My Htop reports that routines which are in a wait loop consume about 2% of CPU time. Although that is ok for most tasks, I think that 2% is too much sometimes (when I got a lot of such waiting routines).
So I think that adding the option to change timeout time would be a nice idea. Looking forward to hear your thoughts about it.

**Comment by stof** [comment]
I think the issue is that the actual loop is *not* sleeping while waiting (the loop doing the sleep is just the one waiting for the actual process termination once the pipes get closed, but most of the time is spent earlier)

**Comment by and800** [comment]
Yes, I was wrong, that `usleep(1000)` loop is running only when the pipes are closed

But in general, the problem is the same.

If I understand the code correctly, prior to this, there is a loop of pipe status checking (are they already closed?). It uses `stream_select()` call with timeout set to `Process::TIMEOUT_PRECISION`, and during that timeout the waiting process is actually sleeping. By default it's 0.2s. Quite a long time, but it still eats too much on my machine.

Therefore, one of these statements has to be true:
+ I am reading Htop stats incorrectly
+ Sometimes, even 0.2s is too little and the users need an option to setup timeout time manually

**Comment by flip111** [comment]
@and800 can you do some profiling to further substantiate the issue? For example would be nice to see a graph which displays what time the process is sleeping and what time it's active.

**Comment by and800** [comment]
@flip111 I'm currently doing benchmarks, gonna post results in a few minutes

**Comment by flip111** [comment]
@and800 i mean tracing information, not benchmarks .. but ok benchmarks can be useful too.

**Comment by and800** [comment]
At first, sorry for not having time for working on this issue.

I made some tests today and it seems that I was wrong. Timeout time does not have any impact on performance. I'm closing this.
