### ISSUE TITLE
HttpKernel::handleRaw() used a depricated method 

### ISSUE THREAD

**Issue by shude** [symfony/symfony#22704]
| Q                | A
| ---------------- | -----
| Symfony version  | 3.2.2

HttpKernel::handleRaw() used a deprecated method ArgumentResolverInterface::getArguments()

**Comment by xabbuh** [comment]
The `ArgumentResolverInterface::getArguments()` method is not deprecated. The deprecated method is `ControllerResolverInterface::getArguments()`. Internally, the `HttpKernel` class already uses the `getArguments()` method from the arguments resolver if one is passed through the constructor and only falls back to the controller resolver if none is passed.
