### ISSUE TITLE
`getInput` cannot get the input I have set.

### ISSUE THREAD

**Issue by shtse8** [symfony/symfony#22705]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 

`getInput` cannot get the input I have set. It returns a `IteratorIterator` instead.

Code:
```php
$process = new Process('myProgram');
$inputStream = new InputStream();
$process->setInput($inputStream);
$inputStream2 = $process->getInput();
var_dump($inputStream === $inputStream2);
var_dump($inputStream2);
```

Result:
```php
bool(false)
IteratorIterator Object
(
)
```

**Comment by ro0NL** [comment]
This is by design :) so not a bug really @xabbuh 

I see the confusion, but technically you still get one of these `resource|string|\Iterator|null`, cant you rely on that?

**Comment by shtse8** [comment]
@ro0NL I have tried my best to get back my input from the return, but with no luck. Could you suggest me an example to get back my input from the `getInput`'s return.

**Comment by ro0NL** [comment]
looked to quick; it's intended to return the original input actually. See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/ProcessUtils.php#L106 however `InputStream` is a aggregate, not an `\Iterator`.. so we need to patch that :+1:

**Comment by ro0NL** [comment]
looking at it again, and it actually handles `\Traversable` and so `\IteratorAggregate` as well :sweat: 

So it's truly works by design :) meaning you need to work with the original ref variable, or rely on a contract, i.e. `instanceof \Iterator`.

Not sure what needs to be done here as inner workings rely on the current `getInput` variant. But we could add a `getOriginInput`, sure; or refactor the API =/

**Comment by shtse8** [comment]
I want to get the input from the process variable, so that we don't need to store the original ref variable separately. Please kindly add a method to return the original input and I suggest to refactor the API as it makes much sense for `getInput`/`setInput` pair.

**Comment by javiereguiluz** [comment]
I agree with @shtse8. This looks confusing.

**Comment by Simperfit** [comment]
@shtse8 Do you want to work on this ?

**Comment by nicolas-grekas** [comment]
To me that's by design. Do it prevent doing useful things?

**Comment by Simperfit** [comment]
@fabpot this needs to be closed too.
