### ISSUE TITLE
[Console] Different behaviour for key and value inputs in case of "." character

### ISSUE THREAD

**Issue by borNfreee** [symfony/symfony#22706]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | ^3.2

I would like to know if it is a real bug or intended behaviour:

I'm using `ChoiceQuestion` with choices of folders, where I can have `.` and `..` among other results, e.g.:

```
    [1] .
    [2] app
    [3] src
```

When I type "." I get an error: `Value "." is invalid` because of regular expression: `'/^[a-zA-Z0-9_-]+(?:,[a-zA-Z0-9_-]+)*$/'`.

But when I type "1", the value correctly passes validation and `ChoiceQuestion` returns `array(1) {  [0] =>  string(1) "."}`.

I think both variant ("." and "1") should be allowed in this case.

________

If you think this is a bug, what would you like to see as a solution: 

* allowing some range of special characters in the regular expression
* allow providing custom regular expression
* something else

(I want to contribute for the first time to Symfony so directions/advices are much appreciated)

Thank you.

**Comment by flip111** [comment]
@borNfreee you can make a pull request to change the regular expression to allow for anything that is not whitespace or a comma. The current regex is making too many assumptions on the use case. Better to allow as much as possible for a generic class like ChoiceQuestion and when people want to limit the characters in the choices they are better of writing their own class that is specific for their problem.
