### ISSUE TITLE
Autoloading of Routes From Bundles

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#22700]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Dependency Injection Extensions are great way to let the bundle autoload their services and other configuration details. However routes needs to be included manually in main app routing file.

Is there any reason why extension or bundle cannot register routes? I know about [advanced loaders](https://symfony.com/doc/current/routing/custom_route_loader.html#more-advanced-loaders), but isn't dynamically loading routes slow on production?

**Comment by xabbuh** [comment]
That's true for projects that are currently built on top of the Symfony Standard Edition. However, with Symfony Flex this will change and routes can be provided through recipes. That's why I am going to close here.

**Comment by kiler129** [comment]
@xabbuh: Perfect, thank you.

**Comment by lucascdsilva** [comment]
@xabbuh @kiler129   Hi, does this work in symfony 4? I'm starting to use symfony and I ended up with the same question about how to dynamically load routes.

**Comment by sstok** [comment]
@lucascdsilva Have a look at https://github.com/rollerworks/RouteAutowiringBundle 👍

**Comment by lucascdsilva** [comment]
@sstok  tanks, I will look

**Comment by chiqui3d** [comment]
I find it incredible that this does not exist, and the bundle cannot be completely isolated and does not depend on the global configuration, and also having to create a recipe to write within the global configuration of the system 🔥

thanks @sstok

**Comment by chiqui3d** [comment]
Finally I have used the solution the @kiler129, thanks
