### ISSUE TITLE
[Form] TransformationFailedException: Unable to transform value for property path

### ISSUE THREAD

**Issue by yurii-github** [symfony/symfony#22717]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.2.8
| PHP | 7.1.1 
| MySQL | 5.7.11

In short:
this approach fails http://symfony.com/doc/master/reference/constraints/DateTime.html

> CRITICAL - Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "dateCreated": Expected a string." at ROOT\vendor\symfony\symfony\src\Symfony\Component\Form\Form.php line 1046 

> TransformationFailedException: Unable to transform value for property path "dateCreated": Expected a string. 

Probably similar issues
#8690 (marked as closed BUT the issue is still there)
#12114 also may be related.

-------
I did setup as 
> C:> symfony new PRJ

If you have entity with field like below you will get error

```
    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime()
     */
    private $dateCreated;
```
> Unable to transform value for property path "dateCreated": Expected a string.

But with this one all is fine

```
    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\Type(type="\DateTime")
     */
    private $dateCreated;
```

NOTE:  Setup as
 > C:> symfony demo

works fine and contains assert in format that is failing in default setup

I'm not sure where is the bug with it or what component is missing

regards

**Comment by dmaicher** [comment]
Thanks for the report.

Is the exception coming from here? https://github.com/symfony/symfony/blob/v3.2.8/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php#L130

If so what is the `$value`?

**Comment by yurii-github** [comment]
hello. thanks for answer

no, I've pointed the source. Here's more of it
https://github.com/symfony/symfony/blob/v3.2.8/src/Symfony/Component/Form/Form.php#L1047

error:  **"Unable to transform value for property path "dateCreated": Expected a string."**

```
    private function modelToNorm($value)
    {
        try {
            foreach ($this->config->getModelTransformers() as $transformer) {
                $value = $transformer->transform($value);
            }
        } catch (TransformationFailedException $exception) {
            throw new TransformationFailedException(
                'Unable to transform value for property path "'.$this->getPropertyPath().'": '.$exception->getMessage(),
                $exception->getCode(),
                $exception
            );
        }
        return $value;
    }
```

Unfortunately I've just started with SF recently so I cannot help you with more info yet.

regards

p.s.
I have generated code from console and moved all templates to bundle, but I guess it is not related to it.

**Comment by xabbuh** [comment]
Can you show how you configured your form?

**Comment by yurii-github** [comment]
# step-by-step from zero

1. download from symfony.com/installer
2. do setup
> php symfony.phar new asd
> cd asd
> composer update
3.  manually configure db at **\asd\app\config\parameters.yml**
4. do rapid install
> php bin\console doctrine:database:create
> php bin\console doctrine:generate:entity
> AppBundle:Test
> new field: createdDate (datetime)
> php bin\console doctrine:generate:entities AppBundle:Test
> php bin\console generate:doctrine:crud  -n --overwrite --with-write --entity=AppBundle:Test
> php bin\console doctrine:schema:update --force
5. add manually to Test.php
```
use Symfony\Component\Validator\Constraints as Assert;
...  
      /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdDate", type="datetime")
	 * @Assert\DateTime()
     */
    private $createdDate;
		
```
6. try  http://localhost/asd/web/app_dev.php/test/1/edit
7. see error

something like that

p.s.
http://localhost/asd/web/config.php shows only one notification

> intl ICU version installed on your system is outdated (57.1) and does not match the ICU data bundled with Symfony (58.2)
> To get the latest internationalization data upgrade the ICU system package and the intl PHP extension.

**Comment by xabbuh** [comment]
Can you please show the code of the generated form type?

**Comment by yurii-github** [comment]
sure
```
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TestType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('createdDate');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Test'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_test';
    }


}
```

**Comment by xabbuh** [comment]
Your issue is that the Form component needs to guess the form type and its options if you do not configure them explicitly. This is done based on your ORM mapping configuration as well as your validation constraint definitions. Adding the `DateTime` constraint makes the `ValidatorTypeGuesser` assume that the form type should be a `DateTimeType` with the `input` option set to `string` (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L120). You can solve this by either being more explicit in your form type definition (i.e. configure the form type) or by removing the DateTime constraint (which IMO is a good idea as adding a proper type hint to your `setCreatedAt()` and optionally allowing `null` values will do the same without relying on the Validator component).

**Comment by yurii-github** [comment]
thanks for heads up, it leads me to interesting thing

On real project I can fix it by adding **DateTimePickerType** (from sonata project)

```
use Sonata\CoreBundle\Form\Type\DateTimePickerType;

...

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('dateCreated', DateTimePickerType::class)
...
```

On demo project it has its own form type DateTimePickerType.php, reason why it is working there.
When I create new project (standard version?) it has no such form type.

In my view, it is broken because docs recommend initially false assert checks as there's no statement I have to make custom form type for date. But anyway, I guess I got the idea

can you please explain difference between
@Assert\DateTime()
and
@Assert\Type(type="\DateTime")

I'm a bit confused.

regards

**Comment by xabbuh** [comment]
> On demo project it has its own form type DateTimePickerType.php, reason why it is working there.
When I create new project (standard version?) it has no such form type.

There is a built-in [DateTimeType](http://symfony.com/doc/current/reference/forms/types/datetime.html) that supports an HTML 5 widget.

> In my view, it is broken because docs recommend initially false assert checks as there's no statement I have to make custom form type for date.

I am not sure I understand that part. Can you explain a bit more?

> can you please explain difference between
@Assert\DateTime()
and
@Assert\Type(type="\DateTime")

The first constraint will accept everything that looks like a date (e.g. it will accept strings that are valid date representations, see http://symfony.com/doc/current/reference/constraints/DateTime.html). The latter one actually checks for the value being a `\DateTime` instance (see http://symfony.com/doc/current/reference/constraints/Type.html).

**Comment by yurii-github** [comment]
by broken I mean that console generates code that fails initially. So to get it working I have to tweak form type.

thanks for pointing about constraints, but it is hard to get why split them into 2 things. Maybe this is only me.

anyway, I guess this is feature of SF so I'm closing this issue,

thanks for your time.

**Comment by rubmic** [comment]
I had
`
    /**
     * @Assert\DateTime()
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createdAt;
`
which create error message
> Unable to transform value for property path "createdAt": Expected a string.

changed
>      * @Assert\DateTime()
to
>      * @Assert\Type(type="\DateTime")

And works ! Thanks !
