### ISSUE TITLE
[SecurityBundle] Fragment Path Redirects on Login

### ISSUE THREAD

**Issue by ChadSikorra** [symfony/symfony#22710]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

It's pretty common when developing a Single Page Application to use a fragment hash for routing on the javascript side. It's also common that a user may bookmark a specific page that contains a hash that describes how to get back to wherever they were. If you have your site behind a Symfony login page then the hash of the URL is lost when they have to log back in.

To fix this I think the following new security bundle options are needed for the form_login:
* `fragment_path_parameter`: defaults to `_fragment_path`. This user is responsible for storing the hash in this parameter during the login process.
* `use_fragment_path`: Default to false. This controls whether or not the redirect would attempt to use the contents of the fragment path on the redirect. 

I don't mind working on something like this. Just curious if this seems like an OK approach before I start.

**Comment by javiereguiluz** [comment]
@ChadSikorra thanks for reporting this. I don't know if others agree, but instead of adding new config options to control this, I think this could be considered a bug and we should always include the fragment part in the login redirect.

**Comment by ogizanagi** [comment]
I agree with @javiereguiluz 👍

**Comment by dmaicher** [comment]
Maybe I'm missing something but the hash fragment of the URL will not be available server side? So not sure how we should redirect back to the URL with the hash :yum:

**Comment by javiereguiluz** [comment]
@dmaicher that's true 😱   I got confused because we recently added a feature to generate the URL hash from the server side ... but the opposite doesn't work: you can't get the URL hash from the server side!!

**Comment by ChadSikorra** [comment]
@javiereguiluz That is indeed the issue here ;) I should have explained it a little better. The reason the new fragment path parameter would be needed is because there has to be some way for the server side login process to know the fragment to append for the redirect (as the fragment is not visible as far as PHP server side is concerned).

The parameter value would need to be updated manually by the developer (a simple sync to the value from `window.location.hash`) on the login form.

**Comment by dmaicher** [comment]
Isn't this technically possible already?

We have the `_target_path` option: http://symfony.com/doc/current/security/form_login.html#control-the-redirect-url-from-inside-the-form

So if you set that accordingly as a hidden field on the login form (so including the hash fragment) it should work?

**Comment by ChadSikorra** [comment]
@dmaicher That possibility crossed my mind too. Technically you could set the value of `_target_path` using javascript to something like:

`window.location.pathname + window.location.search + window.location.hash`

Though something about that feels wrong. But I guess so does needing a separate parameter just for the fragment (though it is more explicit having it in its own value).

**Comment by fabpot** [comment]
Closing as setting `_target_path` explicitly is the way to go.
