### ISSUE TITLE
[Form] Callback validator on a sub form with EntityType

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#22716]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

Hello,

I have a sub form collection with a "Product" `EntityType` field where I added a `Callback` validator in the `configureOptions` method of the form to make custom check (no entity is mapped to the form).

On the parent form, I have set the validation group to `Default`.

The result is that all of the Product entity `Default` annotations constraints are checked.
My entity contains a Boolean field with a `NotBlank` constraint on it, and the constraint fails because the `false` value is considered as blank.

But the Entity should not be validated since it is an `EntityType` field.

If I remove the Callback constraint, everything is OK, the Product entity is not validated.

Subform class:
```php
class HardwareAccessoryType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('product', EntityType::class, [
                'class'        => Product::class,
                'choice_label' => 'name',
            ])

            ->add('productModel', EntityType::class, [
                'class'        => ProductModel::class,
                'choice_label' => 'name',
            ])

        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'constraints' => [
                new Assert\Callback(function ($data, ExecutionContextInterface $context, $payload) {
                     // The issue only happens if I add a callback validator (even if the callback function is empty)
                }),
            ],
        ]);
    }
}
```

**Comment by HeahDude** [comment]
>My entity contains a Boolean field with a NotBlank constraint on it, and the constraint fails because the false value is considered as blank.

Sounds weird, you should use `NotNull` contraint on a boolean field instead and maybe also `Type("boolean")`.

>The result is that all of the Product entity Default annotations constraints are checked.

>But the Entity should not be validated since it is an EntityType field.

The has nothing to do with the type, but with the validation configuration. Adding a constraint on that nested form for what I guess to handle a kind of `HardwareAccessory` entity is also validated by the default group if `Valid` contraint is set on the root data for that property and on the "product" property of the `HardwareAccessory` class.

Could you please fork symfony standard and add the minimum of code to reproduce your issue? Thanks!

**Comment by Seb33300** [comment]
I can't explain why, but I am not able to reproduce this bug anymore.
Maybe something about this has been fixed in newest Symfony versions.

**Comment by xabbuh** [comment]
> My entity contains a Boolean field with a NotBlank constraint on it, and the constraint fails because the false value is considered as blank.

That's expected. The `NotBlankValidator` explicitly checks for `false` when adding the violation (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/NotBlankValidator.php#L32).

**Comment by Seb33300** [comment]
Thanks.

Using `NotNull` instead of `NotBlank` is the solution.
