### ISSUE TITLE
_instanceof rules should be globally definable

### ISSUE THREAD

**Issue by rakelley** [symfony/symfony#22723]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

The service `_instanceof` feature added in 3.3 is a welcome addition, however currently it is only applied within the scope of the configuration file it is located in.  For large projects with service definitions split up into multiple files, there is no way to apply `_instanceof` rules to all services in the application.

I understand why loading files in isolation by default is desirable, however this seems like a significant general-use feature. For example, most applications have certain basic interfaces (e.g. `ContainerAware` or `LoggerAware`) that could have `_instanceof` mutator-wiring rules which apply to the entire application.

**Comment by fabpot** [comment]
I'm :-1: for having this configured globally as it would apply to all third-party bundles as well. Side effects might occur.

**Comment by rakelley** [comment]
Sorry, "globally" was a poor choice of words to describe something that absolutely should not have side-effects outside of the application, you're right.  I was thinking of an inheritance-based implementation.

Example: A config file imports three others and has `_instanceof` rules marked as inherited. All services in those three files (and any files they import) receive the inherited rules, but nothing above this level is affected.

Currently the parse tree is stateless, and this would introduce parent state that would need to be passed, but I don't think it would be overly complicated.

**Comment by theofidry** [comment]
This is far from being the first time this feature is being requested. Maybe a mention in the doc explaining why this feature has not been implemented would be appropriate

**Comment by kiler129** [comment]
I fully agree with @rakelley - inheritance should definitely work for `_instanceof`. Imagine you have main application `services.yml` file importing 10 different bundles. Multiple classes in multiple bundles are implementing `LoggerAwareInterface` - you cannot autowire setter injection AFAIK.

Using `_instanceof` will be very easy in such case - logger will be defined in the main `services.yml` along with `_instanceof` containing `calls` directive. I'm afraid if it's not too magical thou...

**Comment by GuilhemN** [comment]
Note that you can just autoconfigure your services and add an autoconfigured instanceof using `ContainerBuilder::registerForAutoconfiguration()`. You can look the framework bundle extension for examples.

**Comment by rakelley** [comment]
@GuilhemN That's actually a perfect solution to our needs, thank you.

**Comment by rakelley** [comment]
Unfortunately, this doesn't quite work as hoped.

`ResolveInstanceofConditionalsPass::process()` explicitly disallows using auto-configured `ChildDefinitions` which have method calls, for reasons described in the [responsible pr](https://github.com/symfony/symfony/commit/a943b96d4291ba60d49dedb92ba6f224fb6d752d).

Hopefully this will be supported in future, in the mean time we're likely just going to do it with our own compiler pass.

**Comment by stof** [comment]
@rakelley `_instanceof` does not apply to ChildDefinition either.
Resolving inheritance of settings from both the parent definition and the `_instanceof` rules is a nightmare. We tried it, it added lots of complexity with lots of weird cases, and so we reverted it by forbidding to use both features at the same time.

**Comment by pejkosz94** [comment]
I'm using Symfony 4.4 and problem still occurs.

Is there option that `_instanceof` and `_defaults: bind` could be configurable in multiple services files and does not override definitions?
Right now I have structure:
```
--services/
----services_module_A.yaml
--services.yaml
--services_test.yaml
```

When I'm adding `_instanceof` to `services/services_module_A.yaml` and `services.yaml`. Only those from `services.yaml` are taken.

I'm registering all services from `service` directory in `Kernel.php` with code `$loader->load($confDir . '/services/*' . self::CONFIG_EXTS, 'glob');`

**Comment by stof** [comment]
I guess the issue is the order in which you load your files, if 2 of them could define the same service

**Comment by pejkosz94** [comment]
@stof but I want to add `_instanceof:` in 2 files, example:

services_A.yaml:
```
services:
    _instanceof:
        SomeService:
            tags: ['some.tag']
```

services.yaml: (main one)
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            int $tokenTtl: '%env(int:tokenTtl)%'
    _instanceof:
        SomeOtherService:
            tags: ['some.other_tag']
```

Right now only services from `services.yaml::_instanceof` (main file) are taken. Services from `services_A.yaml::_instanceof` are overrode (in this case totally deleted, because only last values are taken).

It there any option to merge those 2 arrays of services pointed in `_instanceof:` section?
