### ISSUE TITLE
Where should PR's for the validator component be sent?

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#22720]
I submitted a PR to the validator component (https://github.com/symfony/validator/pull/22).

However, I've noticed there are PR's from August 2016 without any responses. See https://github.com/symfony/validator/pulls

Should my PR be pushed somewhere in particular?

**Comment by ro0NL** [comment]
Yes - the main repo :) (the one you're at now)

https://github.com/symfony/symfony

**Comment by chalasr** [comment]
> Report issues and send Pull Requests in the main Symfony repository

https://github.com/symfony/validator#resources

**Comment by ro0NL** [comment]
That could be made more clear though :)

**Comment by stof** [comment]
@fabpot could you make @symfony-bot commenting on PRs on the read-only subtree split repos ? I think most of the core team has not subscribed to notifications on them and so does not receive notifications when a PR is opened there.

**Comment by javiereguiluz** [comment]
Let's close this as fixed and let's wait and see if Fabien can make a bot that warns users submitting PRs to the individual component repos. Thanks!
