### ISSUE TITLE
[Routing] Will it be a good idea to write differential tests of PhpMatcherDumper output?

### ISSUE THREAD

**Issue by origaminal** [symfony/symfony#22753]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | ~2.7|~3.0|~4.0

I found out that ```PhpMatcherDumper``` is tested by file line matching against set precompiled matchers. While it is totally fine to ensure that we get what we do want there are differences in the logic flows of, for example, ```UrlMatcher``` and dumped ```UrlMatcher```. This is why  I'm curious whether it will be a good idea to write differential tests of a matcher and a dumped matcher?

**Comment by nicolas-grekas** [comment]
Closing as this is not really an issue, so tracking it is not needed. If the test suite is not good enough, let's (im)prove it :)
