### ISSUE TITLE
Tag symfony/lock 0.1?

### ISSUE THREAD

**Issue by bshaffer** [symfony/symfony#22766]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | n/a

Can we tag a version for `symfony/lock`? Even if it's `0.1`? 

We are using this in some of the subpackages of [`google/cloud`](https://github.com/GoogleCloudPlatform/google-cloud-php-core/blob/v1.4.0/composer.json#L14), and there are conflicts regarding minimum stability. Perhaps this is by design, but if the library is ready, a tag would be fantastic!

Thank you.

**Comment by GrahamCampbell** [comment]
the error there is they should be using a proper version constraint, so composer can resolve it

**Comment by stof** [comment]
We decided that symfony/lock was not yet ready to be released in 3.3. It will be part of the 3.4 release. so no, we won't create tags yet (if it was ready, we would have it as part of Symfony 3.3 RC-1)

**Comment by xabbuh** [comment]
I think we can close here as there will be no tag before the first RC of Symfony 3.4.
