### ISSUE TITLE
[HttpFoundation] Request: Object oriented way to set and remove cookies?

### ISSUE THREAD

**Issue by k00ni** [symfony/symfony#22775]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | *

The Request class already provides cookies as an array (resp. a Bag) using $cookies property. But each entry is a key-value pair (cookie name => value). If i understand it right, to get more details for a given cookie (e.g. domain), you need to get the name from `Request->cookies` and use `$_COOKIE['that cookie name']` to get the rest.

Because of that hassle, I'd like to have an additional function, which returns these cookies, but as an array (or Bag) of [Cookie](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Cookie.php) instances. This allows an object-oriented access to cookie data without the need of $_COOKIE.

If others like this idea, i could make a pull request with an example implementation.

**Comment by k00ni** [comment]
I currently play around with my custom implementation and got problems, using a simple array of Cookie instances. Furthermore, using a ParameterBag is also problematic, because the Cookie class doesn't allow changes of the cookie data.

Imagine the following use case:
```
Request => set a cookie value => Response => set cookies => send Response
```
That is not possible, because you a function or something, to change a cookie instance so that the response send all new cookies, if available, but also changes existing ones. Last one is important, because removing a cookie is usually done by set its `expires` to 0.

**Comment by xabbuh** [comment]
I don't see what this would improve. The client only sends key (name)/value pairs (the values in the `$_COOKIE` array are just the same strings). The additional attributes of the `Cookie` class are only taken into account when the application sends cookies to the client (but that's the responsibility of the `Response` class which already does it).

**Comment by apfelbox** [comment]
From a request side, there is no additional info.
The client only sends the `Cookie: test=abc` data to the server.

All other related information (domain, expiration, etc…) is only stored in the client and with this data the client decides whether to send the cookie data at all. But the client only ever sents a `cookie name => value` map, nothing more.

**Comment by k00ni** [comment]
@xabbuh wrote:
> The client only sends key (name)/value pairs (the values in the $_COOKIE array are just the same strings). The additional attributes of the Cookie class are only taken into account when the application sends cookies to the client (but that's the responsibility of the Response class which already does it).

@apfelbox wrote:
> All other related information (domain, expiration, etc…) is only stored in the client and with this data the client decides whether to send the cookie data at all. 

I would like to have an object-oriented approach to handle cookies all the way from a Request to the Response. Please correct me if i am wrong, if the following is somehow already possible.

Some pseudo code to illustrate my thoughts:
```php
$request = Request::createByGlobals();
$request->cookies = array('foo' => 'bar');

function invalidateUserSession($request) {
     // instead of doing something like
     setcookie('login_cookie', null, 1, '/');

    // i would like something like
    $request->cookies->invalidateCookie('foo');
    // or
    $request->cookies->get('foo')->invalidate();

    // do other stuff ...

    // make and return response
    $response = new Response(...);
    $response->headers->setCookie($request->cookies->get('foo'));
    return $response;
}

$response = handleRequest($request);
$response->send();
```

Otherwise i would have no idea how to avoid using setcookie. Especially if your are in a test environment, where you otherwise run into errors like `Cannot modify header information - headers already sent by`.

**Comment by apfelbox** [comment]
It would not be wise to reuse the response cookies in the request, as the two are two entirely different concepts - see the MDN link. Also from a SoC perspective, the received cookies in the request are in no way related to the sent cookies in the response. And they should'nt be.

Not sure whether this ... 
```php
function invalidateUserSession(Request $request) 
{
    $request->cookies->invalidateCookie('login_cookie');

    // make and return response
    $response = new Response(...);
    $response->headers->setCookie($request->cookies->get('login_cookie'));
    return $response;
}
```

... is preferable to ...

```php
function invalidateUserSession() 
{
    // make and return response
    $response = new Response(...);
    $response->headers->setCookie(new Cookie('login_cookie', null));
    return $response;
}
```

... though.

What could be improved in the current cookie system however is that the knowledge that you can reset a cookie by sending it empty to the client is not abstracted away from the user.

`$response->headers->setCookie(new ResetCookie('login_cookie'));` or something like that.

However, I would refrain from mixing request and response cookies.

**Comment by k00ni** [comment]
Hi @apfelbox, i agree with you, that would be a good solution. It could be optimized by using just:

```php
$response->headers->setCookie(new Cookie('login_cookie', ''));
```
An empty string let the [__toString](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Cookie.php#L96) method of Cookie mark cookie as deleted:

```php
    if ('' === (string) $this->getValue()) {
        $str .= 'deleted; expires='.gmdate('D, d-M-Y H:i:s T', time() - 31536001);
    }
```

That would only solve my cookie deletion problem. (not fully tested)

**Comment by derrabus** [comment]
Isn't this what `ResponseHeaderBag::clearCookie()` is supposed to do?

**Comment by jakzal** [comment]
Closing this issue since removing cookies is already possible with `$response->headers->clearCookie('login_cookie')` as derrabus pointed out.
