### ISSUE TITLE
[FrameworkBundle] No way to specify validation config outside of the bundle

### ISSUE THREAD

**Issue by sonu27** [symfony/symfony#22772]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0-RC1

After speaking with @weaverryan and looking at https://github.com/symfony/symfony/blob/8514e22399fce5e27943ed832d5bdd1f52542dff/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1112-L1140 we believe the only way to add configuration is within the bundle.

It should be possible to read the validation config from the `etc` or newly proposed `config` directory, searching for a file named `validation.yaml` or similar.

I'd really like this as part of 3.3 if possible.

Are we correct in thinking this? Could it be done for 3.3?

**Comment by ogizanagi** [comment]
It's already part of 3.3! See https://github.com/symfony/symfony/pull/19086 😉

**Comment by weaverryan** [comment]
Ah, I missed it indeed! Should have looked in the `Configuration` class :). 

Thanks @ogizanagi!

**Comment by sonu27** [comment]
Thanks! Done here https://github.com/sonu27/local-infrastructure-concept/commit/2da14ec1b05a43cd3d26a66cc524225b9e733780

BTW, the validation.yaml file had to be placed outside etc/packages dir, otherwise I was getting an error
