### ISSUE TITLE
[DependencyInjection] Prepend method arguments

### ISSUE THREAD

**Issue by torinaki** [symfony/symfony#22788]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | *
| Symfony version  | *

I'm proposing to create possibility to prepend arguments for child services that extend some parent declaration specially in scope of providing constructor arguments.

# Current behavior
When you add arguments in child service declaration it will be append to the end of constructor list of arguments.
```php
class ParentClass {
    public $a;
    public function __construct($a) {
        $this->a = $a;
    }
}

class ChildClass extends ParentClass {
    public $c;
    public function __construct($a, $c) {
        parent::__construct($a);
        $this->c = $c;
    }
}
```
```xml
<services>
    <service id="parent_service" class="ParentClass" abstract="true">
        <argument>a</argument>
    </service>
    <service id="child_service" class="ChildClass" parent="parent_service">
        <argument>c</argument>
    </service>
</services>
```

# Problem
In case when you need to add new argument into `ParentClass` you have to modify `ChildClass` constructor arguments.
```php
class ParentClass {
    public $a;
    public $b;
    public function __construct($a, $b) {
        $this->a = $a;
        $this->b = $b;
    }
}

class ChildClass extends ParentClass {
    public $c;
    public function __construct($a, $b, $c) {
        parent::__construct($a, $b);
        $this->c = $c;
    }
}
```
```xml
<services>
    <service id="parent_service" class="ParentClass" abstract="true">
        <argument>a</argument>
        <argument>b</argument>
    </service>
    <service id="child_service" class="ChildClass" parent="parent_service">
        <argument>c</argument>
    </service>
</services>
```

# Solution
We can avoid to modify `ChildClass` constructor by using [argument unpacking](https://wiki.php.net/rfc/argument_unpacking).
```php
class ParentClass {
    public $a;
    public $b;
    public function __construct($a, $b) {
        $this->a = $a;
        $this->b = $b;
    }
}

class ChildClass extends ParentClass {
    public $c;
    public function __construct($c, ...$parentArgs) {
        parent::__construct(...$parentArgs);
        $this->c = $c;
    }
}
```
But to make it possible we must somehow prepend arguments in service declaration: 
```xml
<services>
    <service id="parent_service" class="ParentClass" abstract="true">
        <argument>a</argument>
        <argument>b</argument>
    </service>
    
    <!-- Option 1: DI automatically recognize argument unpacking and prepend arguments by default -->
    <service id="child_service" class="ChildClass" parent="parent_service">
        <argument>c</argument>
    </service>
    
    <!-- Option 2: we provide special option to ask DI to prepend arguments -->
    <service id="child_service" class="ChildClass" parent="parent_service">
        <argument prepend="true">c</argument>
    </service>
    
    <!-- Option 3: we specify index in revers order -->
    <service id="child_service" class="ChildClass" parent="parent_service">
        <argument index="-1">c</argument>
    </service>
</services>
```

Variadic functions can be recognized using existing reflection method [ReflectionParameter::isVariadic](http://php.net/manual/en/reflectionparameter.isvariadic.php).

**Comment by derrabus** [comment]
I don't see a big deal with adjusting the constructors of child classes if the parent's constructor was changed. No offense, but your solution seems hacky and opinionated to me and I can't find any real benefit in it.

**Comment by torinaki** [comment]
@derrabus it is not a problem to adjust constructor of child class when it sits in same repository where parent class. It became an issue when you trying to extend bundle's service definition from other repository. In this case you will need create two PRs into different repositories and it add an overhead into developement flow like additional testing, PR review and deployment.

**Comment by jakzal** [comment]
:-1: I don't really see what kind of a problem this would solve. I suggest that decorating a 3rd party service works better than extending it. I'd also prefer to be notified that a 3rd party service has changed by a failing unit test so I could inspect the changes and decide what to do, rather than expecting a framework to handle this situation automagically.
