### ISSUE TITLE
[DependencyInjection] RewindableGenerator returns an invalid traversable when IteratorArgument is empty 

### ISSUE THREAD

**Issue by meyerbaptiste** [symfony/symfony#22780]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | >= 3.3.0-BETA1

I have an `IteratorArgument` instance with an empty array as values (`new IteratorArgument([])`).
The [`PhpDumper` instance transform it to a `RewindableGenerator` class](https://github.com/symfony/symfony/blob/428b9bfa4fea0c9427d216ebcd293a9b2bf4d885/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1436-L1451) like this:
```php
new RewindableGenerator(function() {}, 0);
```

So, when I iterate on my `RewindableGenerator` instance, I get an error because `function() {}` is not a valid traversable:
```
Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator
```

Currently the `property_info` service (`PropertyInfoExtractor` class) is impacted with `getShortDescription` and `getLongDescription` methods when [the `phpdocumentor/reflection-docblock` package is not installed](https://github.com/symfony/symfony/blob/428b9bfa4fea0c9427d216ebcd293a9b2bf4d885/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1389-L1393). See api-platform/core#1127.

I don't know what is the best way to fix this, but a solution is to generate an "empty" generator/iterator with the `PhpDumper`:
```php
// PHP 7+
new RewindableGenerator(function () { yield from []; }, 0);

// PHP 5.1+
new RewindableGenerator(function () { return new \EmptyIterator(); }, 0);
```

WDYT?

**Comment by stof** [comment]
Or just replacing the whole `new RewindableGenerator(function() {}, 0)` thing by `new \EmptyIterator()`, which is already rewindable.

**Comment by jvasseur** [comment]
@stof you need the `RewindableGenerator` class to provide the `count` method.

**Comment by stof** [comment]
hmm indeed. EmptyGenerator is not countable

**Comment by nicolas-grekas** [comment]
@meyerbaptiste would you mind opening a PR to fix this?
I think we should just allow `null` as `$generator` and adjust things to leverage it.

**Comment by nicolas-grekas** [comment]
Hum, better: use an empty generator:
https://3v4l.org/uXBEq

**Comment by nicolas-grekas** [comment]
2nd hum :)
`new \EmptyIterator()` is fine: the promise is to generate an iterator - not specifically countable, right?

**Comment by stof** [comment]
I think https://github.com/symfony/symfony/pull/21455 was meant to promise you can count without breaking lazyness

**Comment by nicolas-grekas** [comment]
Indeed, so `new RewindableGenerator(function () { return new \EmptyIterator(); }, 0);` should be the way to go to me

**Comment by meyerbaptiste** [comment]
I'll open a PR with this solution! Thx.
