### ISSUE TITLE
Symfony Validator Component missing dependency

### ISSUE THREAD

**Issue by walterdolce** [symfony/symfony#22807]
| Q                | A
| ---------------- | -----
| Bug report?      | yes & no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | none (but the component's is 3.2.7)

When using the `Email` constraint in strict mode the following error occurs if the dependency is missing:
```
RuntimeException in EmailValidator.php line 61:
Strict email validation requires egulias/email-validator ~1.2|~2.0
```
Given the strict email validation requires the above-mentioned dependency, and the strict email validation is a feature supported by the component out of the box, this means the egulias/email-validator package is a dependency of the validator component, but the validator component does not ship with this dependency by default.

I think the opposite should be. 

The validator component offers this functionality (strict email checking) which is executed by the `egulias/email-validator` code logic. This makes the `egulias/email-validator` package an explicit dependency of the validator component. If the validator component would still function without it (the `egulias/email-validator` package), it would then offer a "default" email strict checking mechanism, which is not the case.

What do you think?

Thank you.

**Comment by ogizanagi** [comment]
Using the strict email feature is totally optional and won't prevent you from using the other component's features. Hence `egulias/email-validator` is only a soft dependency. Install it if you're using the strict email feature, but if you don't, making it a hard dependency will only install a package you'll never use.
The `Strict email validation requires egulias/email-validator ~1.2|~2.0` already is the best we could offer in terms of DX.

**Comment by robfrawley** [comment]
I disagree: suggested dependencies should only enhance functionality. In this case, it renders one of the classes within the validator unusable. That is the definition of a hard dependency, IMHO.

That said, I *do* understand why it's marked as a suggested dependency, to ensure we don't pull in extra packages that are unused, but such a "problem" is more psychological than practical. Adding another namespace to the autoloader array isn't going to realistically affect performance, nor is adding 50.

**Comment by fabpot** [comment]
Closing as we already had this discussion in the past about other optional deps. We only add hard requirements on packages that must be installed for the component to work. That's not the case here.

**Comment by ogizanagi** [comment]
> I disagree: suggested dependencies should only enhance functionality. In this case, it renders one of the classes within the validator unusable. That is the definition of a hard dependency, IMHO.

That's not how it works, at least not for most packages I use. A hard dependency is something required for the package itself to work intrinsically, not for one feature only.

> but such a "problem" is more psychological than practical. Adding another namespace to the autoloader array isn't going to realistically affect performance, nor is adding 50.

That's not the main issue to me. A package ships with its own dependencies and it's own versions constraints (which may conflict/restrict with yours).
