### ISSUE TITLE
Avoid repeated information when creating a form type extension

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22833]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | -

If you follow this article https://symfony.com/doc/current/form/create_form_type_extension.html you'll see that:

1. In the `ImageTypeExtension` class, you must define which type are you extending with the `getExtendedType()` method.
2. When defining a service, you must repeat that information in the `extended_type` attribute of the `form.type_extension` tag.

---

I have two proposals:

1. Why repeat the information in the tag? Please remove this requirement. Thanks!
2. I guess there will be some reasons for this but, why must I define the extended type in the `getExtendedType()` method instead of just extending the class of that type?

**Comment by xabbuh** [comment]
> I guess there will be some reasons for this but, why must I define the extended type in the `getExtendedType()` method instead of just extending the class of that type?

We are talking about form type extensions here. Making those classes extend some concrete form type class means that they would be implementors of the `FormTypeInterface`. Thus, an extension would be usable as a form type. That does not make much sense as the goal of a form type extension is not to create new types, but to add functionality to an already existing type.

**Comment by javiereguiluz** [comment]
In PHP we use class extension to add new functionality or change the parent functionality. Since these form things are PHP classes and since this is about adding new functionality, I assumed we could use the natural way here (extending PHP classes) 😢

**Comment by jvasseur** [comment]
@javiereguiluz you can have more than one extension for one form type, that's not possible by extending classes.

**Comment by vudaltsov** [comment]
What if the `getExtendedType()` method is ignored and deprecated, but multiple `form.type_extension` tags are supported to add the same extension to multiple form types?

**Comment by sstok** [comment]
@vudaltsov That's not possible as tags are only for type (extensions) registered as services (which is only required when there is a constructor with required parameters).

**Comment by sstok** [comment]
You could make the `getExtendedType` static, but this will limit use-cases were a type is registered with a configurable parent.

FYI, PHPStorm 2017.2 EAP allows class type completion in string literals (not tried this yet).

**Comment by vudaltsov** [comment]
@sstok , I meant this:

```yml
services:
    my_form_extension:
        class: AppBundle\Form\TypeExtension\MyFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: ...\TextType }
            - { name: form.type_extension, extended_type: ...\TextareaType }
```

**Comment by wouterj** [comment]
`getExtendedType` cannot be removed. It would mean that the form component would be unusable without the DI component. Components should work standalone.

Extending a class to add functionality is not really good OO...

The only thing that can be changed is making `getExtendedType()` static, so the compiler can call it without initializing the service.

**Comment by javiereguiluz** [comment]
It seems "impossible" to change this. So let's close it as "won't fix". Thanks!

**Comment by wouterj** [comment]
This solution seems possible? (except that we have to rename the method, so we can make it static without any PHP warning)

 > The only thing that can be changed is making getExtendedType() static, so the compiler can call it without initializing the service.

**Comment by xabbuh** [comment]
let's see if we can achieve this with #24530
