### ISSUE TITLE
Add min-width for debug toolbar dump section

### ISSUE THREAD

**Issue by Arkemlar** [symfony/symfony#22839]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | may be
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8 & browser Chrome or FF (on debian based linux, last update in 2017)

Since very old symfony2 versions this issue still relevant, at least for me, I show it in two pictures:
1) What I currently see very often:
![image](https://cloud.githubusercontent.com/assets/19671202/26286779/c760a7fc-3e75-11e7-860e-b30de878282c.png)
2) How it should look like:
![image](https://cloud.githubusercontent.com/assets/19671202/26286790/f48db792-3e75-11e7-9d59-1119a4424253.png)
The only change required is adding width (for example `min-width: 500px;`) for CSS selector `pre.sf-dump`. Or make it configurable and use configurated option in dynamic styles part (`<style>` tag) at the end of the page, which is already starts with `pre.sf-dump`:
![image](https://cloud.githubusercontent.com/assets/19671202/26286826/e1ceb254-3e76-11e7-8b2f-46a78453cc26.png)

**Comment by ogizanagi** [comment]
Doesn't https://github.com/symfony/symfony/pull/20716 already solved this? The fix is available since sf 2.8.15, 3.1.8 & 3.2.1.

**Comment by Arkemlar** [comment]
@ogizanagi since my sf version is 3.2.8 - looks like no :/

**Comment by mkurzeja** [comment]
I've managed to recreate this issue on 3.2.9. I will create PR later today
