### ISSUE TITLE
[Console] ChoiceQuestion - invalid error handling if a choice array is empty.

### ISSUE THREAD

**Issue by victorKochkarev** [symfony/symfony#22842]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

ChoiceQuestion - invalid error handling if a choice array is empty.

```php
protected function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = $this->getHelper('question');
        $question = new ChoiceQuestion(
            'Please select your favorite color (defaults to red)',
            [],
            0
        );
        
        $question->setErrorMessage('Color %s is invalid.');

        $color = $helper->ask($input, $output, $question);
        $output->writeln('You have just selected: '.$color);

    }
```

Results into infinite not descriptive warning/error message loop:
![screenshot from 2017-05-22 00-18-02](https://cloud.githubusercontent.com/assets/1124015/26288182/33ffadbe-3e84-11e7-957f-97d5ebe4bb55.png)

**Comment by ro0NL** [comment]
![image](https://cloud.githubusercontent.com/assets/1047696/26298641/58910138-3ed8-11e7-9432-b72510e52db1.png)

affects 2.7.26

Status: reviewed
