### ISSUE TITLE
Deprecation in UserPasswordEncoderCommand::__construct is always throw when you test another command

### ISSUE THREAD

**Issue by xkobal** [symfony/symfony#22855]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3RC1

When you're using the Symfony way to test command (https://symfony.com/doc/current/console.html#testing-commands), you 'always got a deprecation when the command list is build, because the deprecation is in the __construct(), even if I never used this command in my tests.

`Passing null as the first argument of "Symfony\Bundle\SecurityBundle\Command\UserPasswordEncoderCommand::__construct" is deprecated since version 3.3 and will be removed in 4.0. If the command was registered by convention, make it a service instead`

**Comment by ogizanagi** [comment]
Could you provide a reproducer? I tried [the test in `symfony-demo`](https://github.com/symfony/symfony-demo/blob/master/tests/AppBundle/Command/AddUserCommandTest.php#L102-L112) but cannot reproduce (even by using the exact same code as in the mentioned documentation).

Anyway, it looks very weird to me, as this command is now registered as a service by the `SecurityBundle` and the dependency is always provided.
Did you extend the command in your project or tried to register it manually?

**Comment by xkobal** [comment]
I will try to provide a reproducer tomorrow. You have to run tests with an empty cache.

The UserPasswordEncoderCommand is neither extended or registered in y projet.

**Comment by chalasr** [comment]
See #22858

**Comment by xkobal** [comment]
Thanks @chalasr , same problem I think.

**Comment by chalasr** [comment]
@xkobal Would you mind to apply #22858 on your project and confirm it fixes the issue?

**Comment by xkobal** [comment]
@chalasr it works ! thanks
