### ISSUE TITLE
why symfony.com block access from China? 

### ISSUE THREAD

**Issue by videni** [symfony/symfony#22864]
Access  symfony.com will redirect to https://wego.here.com/  ,shows 

```
ERROR

The request could not be satisfied.

The Amazon CloudFront distribution is configured to block access from your country. 
Generated by cloudfront (CloudFront)
Request ID: EPiRoI8_2g_yOVzQJZOHO9IeKKj2tLMF9cIpSe8_5neZWXxIw0E0vQ==
```

**Comment by issei-m** [comment]
China side (i.e. GFW) seems to be blocking the some CDN.

Same issue here: https://github.com/CacheBrowser/cachebrowser/issues/2

**Comment by fabpot** [comment]
That's weird. We do not block access to China anyway.

**Comment by videni** [comment]
@fabpot, @issei-m , Seems GTW is upgraded again, I can't access symfony.com even with ExpressVPN.

**Comment by fabpot** [comment]
@videni Is there anything we can do to help?

**Comment by videni** [comment]
@fabpot， thank you so much , I am afraid not,  I usually check document from symfony.com site, now I will build the doc locally.
