### ISSUE TITLE
Symfony LockHandler throws wrong error

### ISSUE THREAD

**Issue by Xendiadyon** [symfony/symfony#22882]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | ?
| Symfony version  | 2.6.6 - 2.6.8
(Edit: I meant 3.2.6-3.2.8)

In https://github.com/symfony/filesystem/blob/master/LockHandler.php the error_handler is deactivated from lines 70-82. Thus, if an error is thrown in line 85-86, the error-message is wrong.

Found in contao/core-bundle upon symlink generation: https://github.com/contao/core-bundle/issues/845
The system tries to open a specific file in /tmp but has no read/write access due to malconfiguration (?). A Critical Exception is thrown, but the error-message does not fit to the error.

**Comment by iltar** [comment]
Note that you're reporting this bug for symfony 2.6.* versions, which are not supported anymore (for a long time). Can you verify if this is the same with 2.7?

The file you linked is in the master, but in 2.6, the behavior is different: https://github.com/symfony/filesystem/blob/2.6/LockHandler.php#L69
https://github.com/symfony/filesystem/blob/2.7/LockHandler.php#L72

**Comment by Xendiadyon** [comment]
Sorry, I totally confused the versions.
I was working with version 3.2.8 and downgraded to version 3.2.6. Both showed this problem.

![image](https://cloud.githubusercontent.com/assets/2657385/26419875/5703d274-40c1-11e7-80b1-85da1aa0a5b9.png)
I have some files in the /tmp directory which are not readable, the rights are crashed (this probably will be fixed as soon as the hoster cleans the /tmp directory).

So I expect a "fopen() Permission denied" error. When I uncomment the "silencing" of the error-reporting on line 72, I get a few of these error notifications since I cannot open/read/chmod this file (although it exists).
But when in this section the error-reporting is silenced but the handler !$this->handle does not exist on line 84, it throws an error (which is good) but the message is crap (a critical notice):

```
[2017-05-23 18:38:57] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://***.de/contao/install","method":"GET"} []
[2017-05-23 18:38:57] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Using the Contao\\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead. at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/LockHandler.php:86)"} []
```

This notice "Using the Contao\\RequestToken class has been deprecated and will no longer work in Contao 5.0." has nothing to do with the error which is triggered.
This is since the `$error = error_get_last();` on line 85 fetches the last notice and not the correct error (which was "silenced" due to shutting down the error handling in the few lines before)

**Comment by xabbuh** [comment]
@Xendiadyon Can you check if #22910 improves the error message for you?
