### ISSUE TITLE
FatalErrorException in VerifyCsrfToken.php line 156: Call to undefined method Symfony\Component\HttpFoundation\HeaderBag::setCookie()

### ISSUE THREAD

**Issue by JosephSKh** [symfony/symfony#22898]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | x.y.z

FatalErrorException in VerifyCsrfToken.php line 156:
Call to undefined method Symfony\Component\HttpFoundation\HeaderBag::setCookie()

**Comment by xabbuh** [comment]
This looks like an issue in your code. There is no `VerifyCsrfToken` class in the Symfony code.

**Comment by JosephSKh** [comment]
@xabbuh i found this
````
        protected function addCookieToResponse($request, $response)
            {
            $config = config('session');

        $response->headers->setCookie(
            new Cookie(
                'XSRF-TOKEN', $request->session()->token(), Carbon::now()->getTimestamp() + 60 * $config['lifetime'],
                $config['path'], $config['domain'], $config['secure'], false
            )
        );

        return $response;
    }`

**Comment by JosephSKh** [comment]
it's in `vendor/laravel/framework/src/illuminate/foundation/http/middleware/verifycsrftoken.php/

**Comment by xabbuh** [comment]
Maybe in your case `$response` is not a `Response` object or you exchanged its `$headers` property after initialisation. But anyway, this is not a Symfony bug. Since we do not use GitHub for support questions I am going to close your issue. Thank you for understanding.
