### ISSUE TITLE
Composer reading parameters.yml.dist

### ISSUE THREAD

**Issue by lecneri** [symfony/symfony#22899]
| Q                     | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

Hello, I noticed that when we try to add new bundle to symfony and parameters.yml.dist has an error, a parser error is thrown, even though the parameters.yml.dist is correct.

For instance:
* Create a new symfony project
* add a simple space before  mailer_transport entry in app/config/parameters.yml.dist
* go to console and execute
* > composer require jms/serializer-bundle
* An error will be thrown

> Updating the "app/config/parameters.yml" file
> Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the symfony-scripts event terminated with an exception
> 
> Installation failed, reverting ./composer.json to its original content.
> 
> 
>   [Symfony\Component\Yaml\Exception\ParseException]
>   Unable to parse at line 13 (near " mailer_transport: smtp").

from error I noticed the following message:
> Updating the "app/config/parameters.yml" file
And acctually it checks parameters.yml.dist, which in my opinion it shouldn't be an issue if this file is wrong since as name says is a distribution file. 

If this file must be parsed, the error message could be more clear and says that parameters.yml.dist has a problem, not the parameters.yml

**Comment by chalasr** [comment]
This should be reported on https://github.com/Incenteev/ParameterHandler

**Comment by javiereguiluz** [comment]
@lecneri thanks for reporting this issue. I'm closing this because you have also reported it in the original library handling this feature (https://github.com/Incenteev/ParameterHandler/issues/113).
