### ISSUE TITLE
twig render controller - controllerName vs controllerNameAction

### ISSUE THREAD

**Issue by Herod** [symfony/symfony#22915]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | not sure/all

I am not sure if this is a real issue but it is confusing (at least for me).

In symfony we can render controllers inside the twig files by using the standard syntax `bundle:controller:action`

I find it confusing when we have a controller name suffixed by `Action` but the declaration of render controller inside twig is without the `Action` word.

example taken from the documentation: 

```
// src/AppBundle/Controller/ArticleController.php
namespace AppBundle\Controller;

// ...

class ArticleController extends Controller
{
    public function recentArticlesAction($max = 3)
    {
        // make a database call or other logic
        // to get the "$max" most recent articles
        $articles = ...;

        return $this->render(
            'article/recent_list.html.twig',
            array('articles' => $articles)
        );
    }
}
```

```
{# app/Resources/views/base.html.twig #}

{# ... #}
<div id="sidebar">
    {{ render(controller(
        'AppBundle:Article:recentArticles',
        { 'max': 3 }
    )) }}
</div>
```

Why not using strict names like `render(controller(AppBundle:Article:recentArticlesAction`))?

As an extra comment would it be nice to add a link to the API resource documentation in the symfony documentation website?

**Comment by Tobion** [comment]
Following your own arguments, you would also need to add the controller suffix to be consistent: `AppBundle:ArticleController:recentArticlesAction`

**Comment by Herod** [comment]
What i am saying is that you can use it without the suffix 'action'. Which is confusing.

**Comment by Tobion** [comment]
Yes and I'm giving another example where the suffix is omitted. So what do you want to have changed?

**Comment by stof** [comment]
The syntax used in Twig is the same than in your routing file (as they are both sending the value to the same code). So do you complain about it also in routing (or are you using annotations and so don't see this string for routes) ?

**Comment by Herod** [comment]
guys, what is not clear to me is that now I have this `public function **recentArticlesAction()**` and in the render controller i call it as `AppBundle:Article:**recentArticles**`.
How would this be called inside the controler render if I will have a method name called `public function **recentArticles()**`

There is no routing involved here.

**Comment by predakanga** [comment]
@Herod, what they're saying is that this isn't a Twig issue.

The mapping of Apple:Banana:Carrot -> AppleBundle\BananaController::CarrotAction is a convention of the FrameworkBundle - that convention is implemented in [FrameworkBundle\Controller\ControllerNameParser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php).

All Twig (and Routing and all the other layers that deal in controllers) deal with is a simple string; ControllerNameParser (via ControllerResolver) does all the work of turning that into a controller.

**Comment by Herod** [comment]
@predakanga ah right, now i see it... Is that 'Action' string needed to be hardcoded there anyway?

**Comment by predakanga** [comment]
@Herod, I doubt that would be changed, given that it's quite an ingrained convention throughout Symfony.

Fortunately, it's simple enough to change - the logic is implemented as a service (`controller_name_converter`), so all you need to do is [decorate that service](http://symfony.com/doc/current/service_container/service_decoration.html) and alter the return value of `parse($controller)` as you see fit.

You'll see this pattern in a bunch of places around Symfony and it's related libs, for instance in Doctrine's (naming strategy)[http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/namingstrategy.html] - it's quite easy to write a bundle that enables your preferred settings and just include that in any new projects.

**Comment by stof** [comment]
If you go this way, be careful of not breaking the existing convention of adding `Action` at the end when needed, otherwise you will make your project incompatible with third-party bundles though

**Comment by javiereguiluz** [comment]
I'd recommend to close this as "won't fix". @Herod you are right that this notation is confusing at first, but most Symfony developers have learnt it easily (we haven't received other issue reports about this).

Besides, when using the structure proposed by Symfony Flex (in Symfony 3.3 today or in Symfony 3.4 or 4.0 starting from November 2017) this confusing notation is no longer used. Instead, you must use this explicit notation, which includes the `Controller` and `Action` suffixes:

```twig
{# before: Symfony 3.2 #}
{{ render(controller('App:Blog:commentForm', {'id': post.id})) }}

{# after: Symfony 3.3 or 3.4 with Flex or Symfony 4.0 #}
{{ render(controller('App\\Controller\\BlogController:commentFormAction', {'id': post.id})) }}
```

**Comment by Tobion** [comment]
@javiereguiluz will `App:Blog:commentForm` be deprecated then?

**Comment by fabpot** [comment]
The `App:Blog:commentForm` is not deprecated, not sure if that's needed. In any case, I'm closing as "won't fix" indeed as we have another more explicit notation since a long time.
