### ISSUE TITLE
 Increasing xdebug.max_nesting_level to 101

### ISSUE THREAD

**Issue by saadux** [symfony/symfony#22918]
Hi Guys,

I have this message error on my project 

![yooooooooooo](https://cloud.githubusercontent.com/assets/28957566/26458838/02619334-4164-11e7-8b00-b28363123757.PNG)

so i increase xdebug.max_nesting_level to 101 and it works. I would like to know if this operation will have a negatif effect on my project, or can generate some issues after (like : slow loading at the execution).

thanks

**Comment by javiereguiluz** [comment]
@saadux this looks like a Symfony support question, so it's better to use any of these options to ask it: https://symfony.com/support

In any case, on the Symfony Slack, @stof said that 100 is very low and he usually increases it to 1,000. So, it's safe to increase this value. Let's close this as fixed then. Thanks!
