### ISSUE TITLE
[Form] Issue with CountryType choices in Symfony 3.3

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22920]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes?
| Symfony version  | 3.3

I use this form type in a Symfony 3.2 app and it works as expected:

```php
->add('country', 'Symfony\Component\Form\Extension\Core\Type\CountryType', [
    'preferred_choices' => [
        'FR', 'DE', 'US', 'ES', 'GB', 'IT', 'JP',
    ]
])
```

When upgrading to 3.3.0 RC1 I see this:

```
Using the "choices" option in
Symfony\Component\Form\Extension\Core\Type\CountryType has been deprecated since
version 3.3 and will be ignored in 4.0. Override the "choice_loader" option
instead or set it to null: 8x
```

This deprecation is explained here: https://github.com/symfony/symfony/blob/3.3/UPGRADE-3.3.md#form  but I think it may be wrong for the CountryType. If I use one of the solutions proposed in that UPGRADE guide, the list of countries is now empty:

```php
->add('country', 'Symfony\Component\Form\Extension\Core\Type\CountryType', [
    'preferred_choices' => [
        'FR', 'DE', 'US', 'ES', 'GB', 'IT', 'JP',
    ],
    'choice_loader' => null,
])
```

**Comment by ogizanagi** [comment]
I tried reproducing it in the symfony-demo by adding:

```php
            ->add('country', CountryType::class, [
                'mapped' => false,
                'required' => false,
                'preferred_choices' => [
                    'FR', 'DE', 'US', 'ES', 'GB', 'IT', 'JP',
                ],
            ])
```

to the `PostType`, but I don't get the deprecation (using 3.3-dev).
Do you have some form type extensions that may alter the value of the ChoiceType (or any of its child) `choices` option?

**Comment by javiereguiluz** [comment]
@ogizanagi I had two CountryTypes. I only showed the first one ... the second one didn't use `preferred_choices` but `choices`. That was the problem! I ended up replacing the CountryType by a ChoiceType and there are no deprecations now.

Thanks for reviewing this and I'm sorry for my bay issue report!
