### ISSUE TITLE
[Cache] Redis PSR-6 getItem should not use transactions by default

### ISSUE THREAD

**Issue by Tasiobg** [symfony/symfony#22922]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 3.2

File affected https://github.com/symfony/cache/blob/3e22d4ac7a60f7421f1c9e8dd15140f072834480/Traits/RedisTrait.php#L278

Function: 
private function pipeline(\Closure $generator)

Redis PSR-6 getItem() operations are run inside the pipeline as a Redis transaction instead of a normal "get" operation, for instance check line 307 ($this->redis->multi). Redis transactions should be slower and they have side effect, in my case I'm running RedisCluster and I set it to distribute the load between the master and slaves but using transactions is running all operation only on the master server.

For instance it could be reproduced by using phpredis module and setting the RedisCluster connection to something like this:
```
// Create a cluster setting two nodes as seeds
$obj_cluster = new RedisCluster(NULL, Array("host:7000", "host:7001","host:7003"));

// Always distribute readonly commands between masters and slaves, at random
$obj_cluster->setOption(
    RedisCluster::OPT_FAILOVER, RedsiCluster::FAILOVER_DISTRIBUTE
);
```

I have done a quick fix, I have change the last else condition to no use transactions and in this case works fine, load get distributed. 
this is the change I did for the test
```
else {
    $results[];
    $i = 0;
    foreach ($generator() as $command => $args) {
        $ids[$i] = $args[0];
        $results[$i++] = call_user_func_array(array($this->redis, $command), $args);
    }
}
```

If for any reason this is not a bug and PSR-6 Redis adapter is mean to wrap single operations into a transaction, would be nice to have an option to disable this behaviour.

**Comment by nicolas-grekas** [comment]
AFAIK, pipeline is not transactional. But since it uses one single connection to fetch several items at once, it gets them from the same server. Still, each read should be independent, I don't know why the master is always selected. Could it be a phpredis issue?
To me, the code is correct: if you ask several items at once, fetching them in batch is expected. If you don't, you can call getItem() several times.

**Comment by Tasiobg** [comment]
Looks like phpredis implementation of "multi" may set the server into transaction mode
https://github.com/phpredis/phpredis#transactions
Maybe i should try to report this on the phpredis github.

**Comment by Tasiobg** [comment]
I have open an issue on phpredis https://github.com/phpredis/phpredis/issues/1186

**Comment by nicolas-grekas** [comment]
Thanks. How does a predis client behave?

**Comment by nicolas-grekas** [comment]
I got it: since a pipeline can have read and write ops, the master has to be selected...

**Comment by nicolas-grekas** [comment]
See #22924

**Comment by Tasiobg** [comment]
Nice one @nicolas-grekas, this should work.
