### ISSUE TITLE
[Intl] Inconsistency of language list

### ISSUE THREAD

**Issue by merorafael** [symfony/symfony#22935]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.20

Hello everbody,

I'm testing the LanguageBundle in Intl extension, and I found inconsistency in the language listing.

**Examples:**
In the file **Intl/Resources/data/language/pt.json** don't have any key called "pt_BR", but in the file **Intl/Resources/data/language/en.json** the key exists.

In addition to the above problem, we have a lack of standard language keys, where in some cases they are defined in ISO 639-1 and other ISO 639-2.

I know Symfony uses data from the [International Components for Unicode](http://site.icu-project.org/) library, but these inconsistencies are creating a uselessness in this feature. Would not it be better to create our own data source?

Thanks!

**Comment by Nek-** [comment]
Hello,

This is to fix. It would be awesome if you do it (I don't speak Portuguese).

Thanks for your contribution!

**Comment by stof** [comment]
I'm against creating our own data source duplicating the work of ICU. We don't want to have to maintain such thing. The core team has better things to focus on.

**Comment by merorafael** [comment]
@stof I know it sounds like a term "reinventing the wheel", but the ICU files are inconsistent and this affect us, because the symfony-intl uses this files and language list is inconsistent and insufficient trust to be used.

**Comment by stof** [comment]
@merorafael then contribute to ICU to improve this list for everyone using it, instead of asking us to create a second list, for which we won't have resources to maintain it, and so it will suffer from similar issues (except that we will then have 2 different lists which could even lead to inconsistencies between 2 parts of your project if they use different lists)

**Comment by fabpot** [comment]
I agree with @stof, this should be fixed upstream instead.
