### ISSUE TITLE
[Form] Allow MoneyType to be rendered as input with type=number

### ISSUE THREAD

**Issue by MrNicodemuz** [symfony/symfony#22937]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | possibly
| RFC?             | yes
| Symfony version  | 3.2.1

A MoneyType field rendered as type=number gives a much better usability on mobile phones, where the keyboard will be rendered as a numeric keyboard. This allows more easier input of a currency value.

Related stackoverflow question:
https://stackoverflow.com/questions/38190891/how-to-override-symfony-form-moneytype-input-as-type-number

**Comment by Hanmac** [comment]
i think the problem with that is that money/currency has different formats in different countries.
(the same currency could have different thousand and number separators)

and i don't think that type=number can work with that. Probably type=text is problematic for that too. some client validation would be helpful for that.

**Comment by MrNicodemuz** [comment]
@Hanmac Is there a way to override this feature for my use case?

I'm using the MoneyType with full dollar amounts for a specific few target markets. No separators, etc.

**Comment by Hanmac** [comment]
@MrNicodemuz i think that is your "short" way to solve that:
http://symfony.com/doc/current/form/form_customization.html#method-2-inside-a-separate-template
you want to overwrite the "money_widget" block.

i think something like that might solve it:
```twig

{% extends 'form_div_layout.html.twig' %}

{% block money_widget %}
    {%- set type = type|default('money') -%}
    {{ parent() }}
{% endblock %}

```

PS: not tested

**Comment by MrNicodemuz** [comment]
@Hanmac Thanks this worked perfectly!

**Comment by marino-andriamialy** [comment]
the solution 
{{ form_row(form.price, {'type': 'number'}) }}
