### ISSUE TITLE
Unhelpful deprecation trace in 3.3

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22958]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| Symfony version  | 3.3.0

![image](https://cloud.githubusercontent.com/assets/1047696/26582954/5d03147e-4543-11e7-8c90-a9b31ae67a3b.png)

Not sure this is intended some way, but i have no idea whats causing the deprecation :)

**Comment by stof** [comment]
@nicolas-grekas why is there a single element in the trace here ?

**Comment by Xymanek** [comment]
I've got exactly same thing. 3.2.8 -> 3.3.0

**Comment by mvrhov** [comment]
AFAIR I've seen a couple more on other places.

**Comment by Hanmac** [comment]
@ro0NL i could remove that problem in my 3.3.0 build when i did search my project and its vendor for all uses of addClassesToCompile.
some bundles doesn't do the check for PHP < 7.0. this bundles need to be updated.
in my cases it was Sonata Bundles

**Comment by Xymanek** [comment]
@Hanmac Following your advice, I checked my `vendors` directory. For me it turned out to be `MonologBundle` which was locked at `^2.8` for some reason...

**Comment by ro0NL** [comment]
> but i have no idea whats causing the deprecation

i lied.. i knew it was asseticbundle for us. But that's not the point here ;-)

**Comment by ogizanagi** [comment]
See #23007 for displaying the full trace.
