### ISSUE TITLE
[Cache] FatalThrowableError on dev env when injecting a TagAwareAdapter object in a service

### ISSUE THREAD

**Issue by tifabien** [symfony/symfony#22956]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

I updated my application this morning with the brand new 3.3 version but I'm facing an issue only when I call the app_dev.php front controller. 

My service has the following declaration 
```
<service id="app.manager.establishment" class="AppBundle\Manager\EstablishmentManager">
    <argument type="service" id="app.repository.establishment_repository"/>
    <argument type="service" id="cache.app"/>
</service>
```

In order to use the TagAwareAdapter in my application I decorated the default cache.app service like this
```
<service id="app.decorating_cache" class="Symfony\Component\Cache\Adapter\TagAwareAdapter" decorates="cache.app" public="false">
            <argument type="service" id="app.decorating_cache.inner" />
        </service>
```

My EstablishmentManager constructor looks like this 
```
public function __construct(EstablishmentRepository $establishmentRepository, TagAwareAdapterInterface $cache) {.
..
}
```

When I call my dev front controller I got this FatalThrowableError

![fatalthrowableerror](https://cloud.githubusercontent.com/assets/705356/26580444/80666b06-4538-11e7-9971-23969289e65c.PNG)

As the TagAwareAdapterInterface extends the AdapterInterface I thought it was OK but it seems not.

Did I miss something?

**Comment by chalasr** [comment]
See #22960

**Comment by tifabien** [comment]
Great thanks!
