### ISSUE TITLE
Row count wraps in profiler (routing)

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22959]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.3.0

![image](https://cloud.githubusercontent.com/assets/1047696/26583884/3c45bba2-4547-11e7-8717-dd92c1e500ed.png)

confusing :)

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. I'm going to send a PR to fix this bug in 2.7+ because it also happens in other panels (e.g. translation).

**Comment by ro0NL** [comment]
CSS counters look promising for this :) https://jsfiddle.net/davidThomas/7RyGX/

**Comment by javiereguiluz** [comment]
Closing it as fixed by #23229.
