### ISSUE TITLE
Cannot select message in new exception page

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22957]
| Q                | A
| ---------------- | -----
| Bug report?      | no, annoying though
| Feature request? | yes
| Symfony version  | 3.3.0

![image](https://cloud.githubusercontent.com/assets/1047696/26582062/db8e1248-453f-11e7-9fde-32a460456595.png)

Copy-pasing the exception message is a common thing, at least for specific keywords. I think CSS or so blocks it :confused:

**Comment by tkuijer** [comment]
Seems to be caused by https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ExceptionHandler.php#L319

**Comment by ogizanagi** [comment]
See https://github.com/symfony/symfony/pull/22968
