### ISSUE TITLE
[DependencyInjection] Autowiring deprecations after upgrading to 3.3.0

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#22951]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

After upgrading the Symfony Demo app to 3.3.0 final, I see these deprecations (that weren't shown in 3.3.0 RC1):

```
Autowiring services based on the types they implement is deprecated since
Symfony 3.3 and won’t be supported in version 4.0. You should rename (or alias)
the “security.user_password_encoder.generic” service to
“Symfony\Component\Security\Core\Encoder\UserPasswordEncoder” instead.

Autowiring services based on the types they implement is deprecated since
Symfony 3.3 and won’t be supported in version 4.0. You should rename (or alias)
the “doctrine.orm.default_entity_manager” service to
“Doctrine\ORM\EntityManager” instead.
```

**Comment by ogizanagi** [comment]
I think you simply missed it using the 3.3.0-RC1 release actually. ^^ (I double-checked and it happens in both RC and stable release).

You should probably typehint over `Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface` in `AddUserCommand`.
The same goes for the entity manager: `CheckRequirementsSubscriber` typehints on the implementation rather than the `EntityManagerInterface` for which is already declared an alias.

But the question is: should we declare explicit aliases for those implementations?

**Comment by stof** [comment]
Defining the alias for the interface rather than the implementation was done on purpose, to encourage people to typehint interfaces.

@weaverryan shouldn't the exception message also mention the existing supported interface autowiring to suggest changing the typehint ? I thought you added something about it.

**Comment by javiereguiluz** [comment]
Now I'm seeing another deprecation (that was reported on Symfony Slack by other users too):

```
User Deprecated: The "Twig_TokenParser_Include" class is considered final.
It may change without further notice as of its next major version. You should
not extend it from "Twig_TokenParser_Embed".
```

**Comment by mkalisz77** [comment]
Autowiring-types are deprecated since Symfony 3.3 and will be removed in 4.0. Use aliases instead for "Psr\Log\LoggerInterface".

This is from my appDevDebugProjectContainer.xml (only one single  place where I found autowiring-type entry)

    <service id="monolog.logger" class="Symfony\Bridge\Monolog\Logger" public="false">
      <argument>app</argument>
      <call method="pushProcessor">
        <argument type="service" id="debug.log_processor"/>
      </call>
      <call method="useMicrosecondTimestamps">
        <argument>true</argument>
      </call>
      <call method="pushHandler">
        <argument type="service" id="monolog.handler.console"/>
      </call>
      <call method="pushHandler">
        <argument type="service" id="monolog.handler.main"/>
      </call>
      <autowiring-type>Psr\Log\LoggerInterface</autowiring-type>
    </service>

**Comment by xabbuh** [comment]
@mkalisz77 Your issue is probably solved by updating MonologBundle to 3.1 (which contains the fix from symfony/monolog-bundle#203).

**Comment by xabbuh** [comment]
@javiereguiluz The `@final` error in Twig should go away once there is a tag in Twig containing twigphp/Twig@a083db55c242ed30451467c802633cddbad198ed.

**Comment by scaytrase** [comment]
> Defining the alias for the interface rather than the implementation was done on purpose, to encourage people to typehint interfaces.

@stof The problem is that I'm receiving this even for services, which do not implement any interface and are autowired by-type. Do we have to alias each service now to make it autowireable?

**Comment by scaytrase** [comment]
I've created a gist for you with a sample

https://gist.github.com/scaytrase/cb4eda510a68f48ec5c7e978616c6cb3

Which gives me the following output

```
> C:\Work\Tools\PHP7.1\php.exe vendor/phpunit/phpunit/phpunit -c pusample.xml AutowireTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 499 ms, Memory: 6.00MB

OK (1 test, 0 assertions)

Remaining deprecation notices (1)

Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "svc_c" service to "Test\C" instead: 1x
    1x in AutowireTest::testAutowiring from Test

```

**Comment by weaverryan** [comment]
> @weaverryan shouldn't the exception message also mention the existing supported interface autowiring to suggest changing the typehint ? I thought you added something about it.

I did have a PR with this change... but it was ultimately reverted: https://github.com/symfony/symfony/pull/22648#discussion_r114982686

The proper fix *is* really to change the type-hint - e.g. `UserPasswordEncoder` to `UserPasswordEncoderInterface`. But creating an alias is not a bad solution, and will be more "global" - i.e. I would have to do just one thing versus fixing 10 type-hints.

But, this did confuse me, and is now confusing other people. My proposed message looked like this:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. Try changing the type-hint to "Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface" instead.

I believe that - at least now - we don't have a lot of context as to exactly *where* the type-hint is (i.e. which argument of which method).

**Comment by weaverryan** [comment]
See #22999

**Comment by scaytrase** [comment]
I've made a reproducing repo for (from my POV) these weird deprecations:

https://github.com/scaytrase/sf22951-reproducer/blob/master/AutoWiringTest.php

Tests are passing but deprecations emitted:

https://travis-ci.org/scaytrase/sf22951-reproducer/builds/238025170

It looks like that we have problems autowiring services which were transitive autowired
