### ISSUE TITLE
Web Toolbar not loading due to an error in LoggerDataCollector

### ISSUE THREAD

**Issue by SvetlinStaev** [symfony/symfony#22952]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

This morning I have upgraded one of my projects from 3.2.8 to 3.3.0. Everything is working fine except that the web toolbar is not loading. There is a strange error logged which is causing it. In the logs it is:

```
[2017-05-30 07:51:42] php.CRITICAL: Uncaught Notice: Undefined offset: 1 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined offset: 1 at /Users/SvetlinStaev/Projects/test/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php:142)"} []
```
When I comment this `$log[1]`, it works fine and no errors are logged.

```
$logs[$log[0]][] = array('message' => ''); //$log[1]);
```
I tried to change the permissions of my cache and log folders, cleared the cache, warmed up, enabled and disabled the toolbar but without commenting `$log[1]` it fails.

On a fresh Symfony 3.3.0 project it works fine. Would it be possible to have a check for the count of the `$log` variable before this line?

**Comment by chosroes** [comment]
I have this error too. It's because the Compiler addLogMessage method is deprecated but doesn't offer backward compatibility when doing explode ': ' in  LoggerDataCollector.php
So I can't use 3.3.

**Comment by SvetlinStaev** [comment]
You are right. I debugged this and the only bundle which uses that deprecated method is JMS DI Extra bundle, removed it and it works fine. The question is shouldn't this explode be checked for the count of the array elements anyway, just to ensure it has them until 4.0 removes that compiler method.

**Comment by Wirone** [comment]
@SvetlinStaev thanks for this information. I lost about 2 hours freaking out what's going on. Too bad we can't get rid of JMSDiExtra because we use JMSQueueBundle.

I think `Compiler::addLogMessage()` should detect calling class and add log message in the same format as `Compiler::log()` does (`class: message`).
