### ISSUE TITLE
Malformed profiler data causing infinite loop in FileProfilerStorage

### ISSUE THREAD

**Issue by Kyoushu** [symfony/symfony#22963]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

I had some code which was attempting to call a method on NULL inside a sub-request. The way the error was handled resulted in profiler data referencing its own token in the `parent` property

**Excerpt from beginning of profiler data file**
```
a:9:{s:5:"token";s:6:"e4d0be";s:6:"parent";s:6:"e4d0be";s:8:"children...
```

This resulted in [\Symfony\Component\HttpKernel\Profiler\FileProfilerStorage::createProfileFromData()](https://github.com/symfony/symfony/blob/7d3700a4/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php#L266) being sent into an infinite loop, as the `$this->read()` call on line 267 opens the same file, returning it back to createProfileFromData to be processed.

I believe this is similar to the issue reported in #3620

**Comment by Kyoushu** [comment]
I'm not sure how to reproduce this issue with a unit test, so I've created a project which triggers is when you visit the homepage.

https://github.com/Kyoushu/symfony-fileprofilerstorage-bug

**Comment by raphaelvigee** [comment]
Same issue, I end up having a serialized profile being an array of 65000 entries !!!

**Comment by nicolas-grekas** [comment]
Anyone willing to give this one a try? With the reproducer it should be doable?
