### ISSUE TITLE
[YAML] Invalid YAML did not throw exception anymore

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#22967]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

---
```php
<?php

require __DIR__.'/vendor/autoload.php';


$yaml = <<<EOYAML
hello
    foo: bar
EOYAML;

dump(Symfony\Component\Yaml\Yaml::parse($yaml));
```

--- 

output:

```
"hello foo: bar"
```

**Comment by magnetik** [comment]
I think it's ec593b923bc7fff7d21268f636551fa012911053 fault

**Comment by weaverryan** [comment]
@xabbuh what do you think? Is that actually valid YAML? If so... it seems the multi-line parsing could cause some WTF's (as it's much more likely that this is a mistake)

**Comment by xabbuh** [comment]
Yes, this is broken by the multi-line parsing. But I did not find a way to fix it easily yet.

**Comment by nicolas-grekas** [comment]
maybe @GuilhemN has an idea here?

**Comment by GuilhemN** [comment]
That's indeed invalid yaml, keys must be inlined (see http://www.yaml.org/spec/1.2/spec.html#ns-plain(n,c))

**Comment by xabbuh** [comment]
Oh indeed, @GuilhemN is right here. I didn't intend to change this behaviour when introducing the parsing of multi-line scalars. But as it seems that the YAML we were parsing before was not valid, we can close here now.

**Comment by lyrixx** [comment]
@xabbuh I don't understand you here. It IS invalid. So symfony should throw an exception. It's not the case anymore.

**Comment by xabbuh** [comment]
@lyrixx Oh sorry, I read too quickly. Thanks for reopening.

**Comment by walterdolce** [comment]
Just stumbled upon this issue as I was about to open the same. 

By using the YAML parser `3.3.0` with the following:
```
try {
    $yaml = Yaml::parse(' &  *  !  |  >  \'  "  %  @  ` #, { asd a;sdasd }-@^qw3');
} catch (\Exception $e) {
   echo $e->getMessage();
}
```

No exception is thrown. No exception is thrown when the `Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE` flag is used either.
