### ISSUE TITLE
Add a more helpful hint with the "autowiring services based on the types" deprecation message

### ISSUE THREAD

**Issue by MetalArend** [symfony/symfony#22969]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

While first trying to use the new autowiring functionality in 3.3, the following message started popping up:
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "X" service to "X"

It tells me:
- to rename (or alias) the "security.token_storage" service to "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage" instead
- to rename (or alias) the "form.factory" service to "Symfony\Component\Form\FormFactory" instead

But the actual solution was to replace the TokenStorage and FormFactory typehints in my controller class constructor with TokenStorageInterface and FormFactoryInterface typehints. Would it be helpful to somehow reflect this in the log message in such cases?

**Comment by weaverryan** [comment]
See #22951

**Comment by MetalArend** [comment]
Nice, thanks for this!
