### ISSUE TITLE
Moving classes causes fatal error in ApcClassLoader

### ISSUE THREAD

**Issue by danepowell** [symfony/symfony#22975]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 2.8.20

ApcClassLoader seems really sensitive to moved/deleted class files, and I'm wondering if there's a way that it could more gracefully handle these situations, or if this is indicative of a problem with the class implementations.

Specifically, I have a Drupal 8 install that uses the Config Filter module, which used to provide a ConfigFilterServiceProvider class. In a more recent version of this Config Filter module, this class was removed ([in this commit](http://cgit.drupalcode.org/config_filter/commit/?h=8.x-1.x&id=1149cfcb37d3b51311521b1451cc74dc212b0167)).

The problem is that after upgrading to the newer version of that module, I now get this error from the symfony class loader:

> Fatal error: require(): Failed opening required 'docroot/modules/contrib/config_filter/src/ConfigFilterServiceProvider.php' (include_path='vendor/phing/phing/classes:.:/usr/share/php') in vendor/symfony/class-loader/ApcClassLoader.php on line 110

You might think "eh, easy fix, just clear the APCu cache". Well, that's a lot easier said than done in some environments. In multi-server architectures, that requires manually restarting PHP-FPM / Apache on every single server. Just to move one class file. I'd like to think that there's a better solution than that.

**Comment by javiereguiluz** [comment]
Yes, I was going to propose to clear the cache because this "bug" is really a "feature" of this APC loader.

What you may use is [apc_delete_file()](http://php.net/manual/en/function.apc-delete-file.php), which lets you clear only the APC cache for some PHP file (and thus, for some class).

**Comment by danepowell** [comment]
Thanks @javiereguiluz , but I think there are two problems with that approach, related to the fact that we are using APCu:

1. APCu doesn't have the apc_delete_file() function, I suppose the rough equivalent would be apcu_delete().
2. APCu maintains separate caches for CLI and web (Apache / FPM) requests, so I'm not sure that any call you make from the command line (including apcu_delete) will affect the web cache.

**Comment by nicolas-grekas** [comment]
Just don't use ApcClassLoader and use a dumped composer class map instead?

**Comment by nicolas-grekas** [comment]
There is nothing we can do on our side, that's why I'm suggesting this. Just don't use ApcClassLoader on servers that don't allow resetting the cache...

**Comment by danepowell** [comment]
Using the ApcClassLoader is Drupal core behavior and not something I want to change on a whim to address an issue that occurs very rarely (moving class files).

I found an upstream workaround, which is to use Drupal's deployment_identifier setting to vary the prefix passed to the autoloader so it doesn't pull stale cache entries.

**Comment by nicolas-grekas** [comment]
that should be the way to go, closing then.

**Comment by joelpittet** [comment]
Thanks @danepowell that worked for me as well.
`$settings['deployment_identifier'] = 'some different string to invalidate the APC cache'`

**Comment by damontgomery** [comment]
This also resolved an issue we were having with enabling a module in Drupal 8. The `$settings['deployment_identifier']` addressed the issue.

@danepowell This might be a good thing for Acquia to include in their loaded settings.php so that memcached deployments are easier. ;).

**Comment by chx** [comment]
So Symfony screws up again and the Drupal developers suffer? Par for the course, I presume.

**Comment by JDDoesDev** [comment]
@damontgomery or @joelpittet I hate to threadjack this issue, but is there a d.o issue that addresses this?

**Comment by weitzman** [comment]
deployment_identifier fixed another problem for us. was discussed a lot at https://www.drupal.org/project/drupal/issues/2752961.

**Comment by JDDoesDev** [comment]
Thanks @weitzman!
