### ISSUE TITLE
Click to open file in IDE on exception page don't work anymore after upgrading to 3.3.0

### ISSUE THREAD

**Issue by fsevestre** [symfony/symfony#22978]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | :thinking: 
| RFC?             | no
| Symfony version  | 3.3.0

After upgrading to Symfony 3.3 from 3.2 it seems that the new exception style broke the links to files.
When I click on the file path the block hide (before, we had to click on the icon).
The solution atm is to open the file in a new browser tab.

![capture du 2017-05-30 23-40-02](https://cloud.githubusercontent.com/assets/4130750/26606520/8cba2384-4592-11e7-9c9b-6ee593dc2c83.png)

![capture du 2017-05-30 23-40-20](https://cloud.githubusercontent.com/assets/4130750/26606523/913d3478-4592-11e7-8510-5a7b0a5c5e0b.png)

**Comment by fabpot** [comment]
Indeed, I noticed the same.

**Comment by ogizanagi** [comment]
I've added a commit to https://github.com/symfony/symfony/pull/22968 to fix this. 
But let's see if @javiereguiluz got something else in mind :)
