### ISSUE TITLE
[EventDispatcher] After upgrading to 3.3.0 removeSubscriber() does not work any more.

### ISSUE THREAD

**Issue by Gemineye** [symfony/symfony#22970]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.0

In some commands I use this kind of functionality to disable the sending of Emails: 
`$this->getContainer()->get('event_dispatcher')->removeSubscriber($this->getContainer()->get('my_email_subscriber'));`

And then I put it back:

`$this->getContainer()->get('event_dispatcher')->addSubscriber($this->getContainer()->get('my_email_subscriber'));`

After some debugging I found out that the EventDispatcher now holds closures to enhance LazyLoading in the `$this->listeners` array. 
So the `array_search` check does not work anymore in function `removeListener`.

I'm not sure if this really is a bug or if there is a new way now to achieve this.

**Comment by chalasr** [comment]
BC break confirmed, dunno how to fix that.

Status: reviewed

**Comment by dmaicher** [comment]
Indeed seems impossible to remove subscribers by instance now with the closure proxies :cry: 

@nicolas-grekas as you introduced it in https://github.com/symfony/symfony/pull/20953 do you have an idea?

**Comment by dmaicher** [comment]
@nicolas-grekas yeah was about to ask how exactly to iterate over the service subscribers internally as we don't really have access to them anymore with the closures now?

I guess to make this work we have to inject extra information about the subscribers somehow into the EventListener within the compiler pass?

**Comment by nicolas-grekas** [comment]
Another idea would be to replace those proxy closures by an invokable, that would implement some interface to retrieve the wrapped service itself, that EventDispatcher could then use internally.
I've no better idea for now but this one may work. WDYT?

**Comment by dmaicher** [comment]
yep that also crossed my mind :blush: 

Something like this?

```php
class LazyListenerCallable
{
    public function __invoke(...) {
        // this would be used for dispatching events
    }

    public function getInstance() {
        // this would return the instance
    }
}

**Comment by chalasr** [comment]
Looking at it

**Comment by mvrhov** [comment]
@nicolas-grekas: There was a suggestion on similar event dispatcher from drupal community but was turned down because the interface would not be compatible. I can't seem to find it now. AFAIR it was also faster than the symfony implementation.

**Comment by nicolas-grekas** [comment]
@mvrhov yep I remember that one, and it's been closed because we reclaimed the perf issue with the closure proxies (the culprit was the logic in addSubscriber, which is costly.)

**Comment by stof** [comment]
@nicolas-grekas we cannot deprecate addSubscriber in favor of compiler passes. The Form component cannot use the compiler pass for instance (but we want to be able to use subscribers there).

**Comment by nicolas-grekas** [comment]
Can you please report if #23008 solves the issue?

**Comment by ostrolucky** [comment]
I've just came to this issue from 3.4 beta changelog. I'm greatly in favor of deprecating add/remove subscriber methods.

@stof How about just extracting functionality of getting list of listeners out of EventSubscriber? Something like new static method `EventDispatcher::getListenersFromSubscriber(EventSubscriberInterface $subscriber)` which will return normalized array of listeners, mostly what's currently done in EventDispatcher::addSubscriber? Then all that Form component will need to do is replace
```php
$this->dispatcher->addSubscriber($subscriber);
```
with
```php
foreach (EventDispatcher::getListenersFromSubscriber($subscriber) as list($eventName, $listener, $priority) {
    $this->dispatcher->addListener($eventName, $listener, $priority);
}
```

Same approach will be utilized by compiler pass, deprecated method in dispatcher itself and recommended as upgrade path for libraries/code which don't use/cannot use FrameworkBundle.

What do you think @nicolas-grekas? Are you still in favour of deprecating those methods?

**Comment by nicolas-grekas** [comment]
I'm not in favor of it if there is no technical purpose: we already reverted changes that we thought were favoring better design, when we later on realized that they also broke legitimate use cases. It's really hard to foresee that.

**Comment by ostrolucky** [comment]
Are you referring to closure proxy feature which broke use case presented in this issue? That change was done in minor version and nature of that feature indeed made it difficult to foresee this breakage. 

I believe Removal of those dispatcher methods is more transparent in what will they do and we can prepare for that better. Additionally, I think I do have legitimate technical reason for doing that. I've contacted you on slack where I would like to present it to you.

**Comment by nicolas-grekas** [comment]
Not specifically this one :)
I suggest you open an RFC if you want to present your point: it's better to discuss in the open, and on an open issue/PR :)
