### ISSUE TITLE
Autowiring tries to wire unused/non-service classes

### ISSUE THREAD

**Issue by samsch** [symfony/symfony#22977]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | Not sure
| RFC?             | no
| Symfony version  | 3.3.0

It seems autowiring tries to auto create the dependencies for a service before checking that the service is actually used.

It seems like it should not attempt to retrieve a dependency for a service which isn't used. If this error is actually expected or a limitation of the system, then I think there should be at least a note in the documentation, both in the [autowiring doc](http://symfony.com/doc/current/service_container/autowiring.html) and in the [upgrade guide](http://symfony.com/doc/current/service_container/3.3-di-changes.html#upgrading-to-the-new-symfony-3-3-configuration).

For my actual use case, I have a data class which is used as a form data object. The constructor for this class takes a service which I directly pass to it where I instantiate the object. Autowiring tries to find this service during container compile and fails.

## Steps to reproduce
1. Create new 3.3 app `symfony new test-app 3.3`
1. Add new `src/AppBundle/Class1` and `src/AppBundle/Class2` with source as below.
1. Run app (`php bin/console server:start`)
1. Open webpage to error

### Error
```
AutowiringFailedException
Cannot autowire service "AppBundle\Services\DataThings\OtherData": argument "$data" of method "__construct()" must have a type-hint or be given a value explicitly.
```
### Class1 source
```php
<?php

namespace AppBundle;

class Class1
{
    public function __construct(Class2 $c2)
    {}
}
```
### Class2 source
```php
<?php

namespace AppBundle;

class Class2
{
    public function __construct($something)
    {}
}
```

**Comment by xabbuh** [comment]
When using the new configuration services will be automatically registered, but you can explicitly exclude some classes (take a look at section http://symfony.com/doc/current/service_container/3.3-di-changes.html#step-4-auto-registering-services from your second link).

**Comment by samsch** [comment]
If you always use a organized-by-type folder structure where all your data classes are in a single folder, that might be a reasonable solution. However, for projects organized [by](https://marmelab.com/blog/2015/12/17/react-directory-structure.html) [domain](http://verraes.net/2011/10/code-folder-structure/), where data classes will not necessarily be under any specific folder, you would likely need to add an exception for each individual data class, or use a naming convention to exclude the files. Either solution is fragile.

In my opinion, file exclusions don't properly address the issue.

If there wasn't this note: "...if any of the services are not used in your code, they're automatically removed from the compiled container." ([ref](http://symfony.com/doc/current/service_container/3.3-di-changes.html#services-are-loaded-automatically)) then I might assume another solution isn't possible. However, at some level unused services can be dropped. It seems reasonable to ignore errors thrown while trying to load a unused "service".

I'm not familiar with the autowiring implementation, but perhaps if dropping a unused service and it's errors isn't possible (or breaks things), is there maybe a way we could mark non-service classes at the class level? Perhaps an annotation: `@NoAutowire`?

**Comment by xabbuh** [comment]
> However, at some level unused services can be dropped. It seems reasonable to ignore errors thrown while trying to load a unused "service".

Before being able to drop services the container first needs to build the entire dependency graph. This is not possible if some of the service definitions are incomplete.

**Comment by weaverryan** [comment]
This is legit. There's an error here: https://github.com/symfony/symfony/blob/c2d729a212e35c909bee9c0fddb70184469d28c5/src/Symfony/Component/DependencyInjection/Compiler/AutowireExceptionPass.php#L47

Class2 *is* removed from the container (because neither Class1 nor Class2 are referenced). But, Class2 is first inlined into Class1, so the if statement thinks the service was not actually removed, but just inlined. So, the exception is thrown when it should not be.

I'll see if I can find a fix :)

**Comment by weaverryan** [comment]
PR #22993

**Comment by smcjones** [comment]
Would be nice to be able to exclude folders by wildcard.

Example:

    exclude: '../../src/AppBundle/Utils/{*/Exception}'

**Comment by nicolas-grekas** [comment]
Isn't it working already if you remove the curly brackets? (glob makes them special only if they contain a comma to define an alternative)

**Comment by smcjones** [comment]
Hmm... I did not try it without curly brackets. I can try tomorrow. I did update my example to include more than one comma separated value as that was my use case.

**Comment by sinner** [comment]
I'm still having this trouble.

**Comment by xabbuh** [comment]
@sinner Please open a new issue with an example that allows to reproduce your issue.
