### ISSUE TITLE
cache:clear shows many invalid characters, unicode characters in webpage, ANSI cached files, etc

### ISSUE THREAD

**Issue by patrickvane** [symfony/symfony#22972]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.2.0+

Cache:clear as well as cache:warmup have a weird output (see screenshot). 

In several projects the webpages (in prod or dev environment) show many unicode characters, followed by an error stating that the headers have already been send (see screenshot). 

Every file is UTF8 without BOM, except for var/cache/prod/annotations.php, which is ANSI, and which sends the headers. The file is also not executed (throw Exception('test') in it doesn't do anything). web/app.php is executed (echo's in it are visible, above the unicode mess), and the controller action is also executed (echo's are displayed after the unicode mess). 

These errors don't happen in 3.1.*, but do happen in 3.2.0 and beyond. 

The way to quickly test it is this:

php composer create-project symfony/framework-standard-edition TestProject "3.2.0"
cd TestProject
SET SYMFONY_ENV=prod
php composer install --no-dev --optimize-autoloader
php bin/console cache:clear --env=prod --no-debug

If the cache:clear produces many random characters, as in the screenshot, then it has bugged. 

The screenshots:

![error_01](https://cloud.githubusercontent.com/assets/1434108/26596023/a4a46a42-456d-11e7-96f3-5f6d0ccd97df.png)
The webpage in 3.2.* in production (production, debian 8 server)

![error_02](https://cloud.githubusercontent.com/assets/1434108/26596026/a7488b3e-456d-11e7-95d5-a6b775683025.png)
The error in sentry (production, debian 8 server)

![error_03](https://cloud.githubusercontent.com/assets/1434108/26596031/a9380532-456d-11e7-8b4b-52cce1de10db.png)
Grep to see which php file starts with something else than <?php
(caused by ANSI encoding of annotaitons.php file)
(production, debian 8 server)

![error_04](https://cloud.githubusercontent.com/assets/1434108/26596034/ab15db90-456d-11e7-9d83-b9520d6a3ff4.png)
Content of var/cache/prod/annotations.php
(production, debian 8 server)

![error_05](https://cloud.githubusercontent.com/assets/1434108/26596035/acbcec72-456d-11e7-947e-b33624c2af13.png)
Output of cache:clear with 3.2.0, 
(development, win 7 pc)

**Comment by sstok** [comment]
When running this locally is it working? Does it only happen on the server? Are you using FTP to upload files (binary vs ASCII)?

is PHP properly configured for encoding, and are you using mb.function-overload (this is know to cause problems). Tip: use  `<details>your code here</details>` to hide big blocks of code (when pasting your configuration 😛 ).

<details>
Hi there
</details>

The most likely is an encoding issue somewhere.

**Comment by patrickvane** [comment]
It's happening both locally (the development PC is local) as well as on a server. The server pulls the code in through git. 

The phpinfo of the server can be seen here: https://backend-phpinfo.lowentry.com/
My local phpinfo is similar. 
mbstring.func_overload is 0

"PHP encodes the namespace with a backslash, it's possible somewhere this escaping is removed causing the string to be seen as unicode sequences."
This happens with a new symfony project (3.2.0 and later, including 3.3.*), if this is a namespace error, does this mean it's in the symfony code itself? Or is it in a configuration file somewhere that is wrong?

**Comment by nicolas-grekas** [comment]
annotations.php has a BOM? Why?

**Comment by patrickvane** [comment]
The var/cache/prod/annotations.php file is generated incorrectly?

**Comment by nicolas-grekas** [comment]
If it has a BOM, yes. There is no BOM in the code base...

**Comment by sstok** [comment]
Are you using an specific editor (or having one open at the time of executing this command, I know some IDE's are eager to update every within a project).

I forgot to ask, do you run the cache:clear also on the server, or prior to pulling?

**Comment by patrickvane** [comment]
I use PHPStorm on the dev PC, but I didn't work on this project, it bugs without doing anything. 
It also happens on the debian server as well. 

All I do is:
```
php composer create-project symfony/framework-standard-edition TestProject "3.2.0"
cd TestProject
SET SYMFONY_ENV=prod
php composer install --no-dev --optimize-autoloader
php bin/console cache:clear --env=prod --no-debug
```

On linux, you should of course use `export SYMFONY_ENV=prod` instead of `SET SYMFONY_ENV=prod`. 

Again, this doesn't happen in 3.1 (which is what I'm using because of that), but it does happen in 3.2 and 3.3.

**Comment by nicolas-grekas** [comment]
I just ran these exact commands and I have no issues... Ubuntu box.

**Comment by patrickvane** [comment]
Weird. I'm thinking, both my dev windows pc and the DigitalOcean debian 8 server use PHP 7.0, could this be the cause of it?

My server uses "7.0.22-1~dotdeb+8.1 (cli) ( NTS )"

My dev pc uses "7.0.10 (cli) (built: Aug 18 2016 09:48:53) ( ZTS )"

What PHP version did you use?

**Comment by nicolas-grekas** [comment]
7.1 - but more people would have reported the issue if if were just related to this I suppose...

**Comment by patrickvane** [comment]
Ok, did some testing. I made a new server (debian 9, completely clean state), ant this is what I ran:

```
apt-get update

apt-get install -y git unzip php php-xml

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

php composer.phar create-project symfony/framework-standard-edition TestProject "3.2.0"
cd TestProject
export SYMFONY_ENV=prod
php ../composer.phar install --no-dev --optimize-autoloader
php bin/console cache:clear --env=prod --no-debug
```

Now, everything went fine. 

Then I changed the php.ini settings to match my dev pc / actual server, so:

```
nano /etc/php/7.0/cli/php.ini
:: change [display_errors] to On
:: change [display_startup_errors] to On
:: change [cgi.fix_pathinfo] to 0
:: change [max_execution_time] to 3600
:: change [max_input_time] to 3600
:: change [memory_limit] to 5120M
:: change [post_max_size] to 2048M
:: change [date.timezone] to Europe/Amsterdam
:: change [zend.multibyte] to On
:: change [mysqli.reconnect] to On
:: change [opcache.enable] to 1
:: change [opcache.enable_cli] to 1
:: change [opcache.memory_consumption] to 128
:: change [opcache.interned_strings_buffer] to 8
:: change [opcache.max_accelerated_files] to 20000
:: change [opcache.use_cwd] to 1
:: change [opcache.validate_timestamps] to 1
:: change [opcache.revalidate_freq] to 10
:: change [opcache.save_comments] to 1
:: change [opcache.fast_shutdown] to 0
:: change [opcache.enable_file_override] to 1
:: change [realpath_cache_size] to 4096K
:: change [ignore_user_abort] to On
:: change [log_errors] to Off
:: change [track_errors] to Off
```

And then I got an error during cache:clear (when I normally would get unicode spewing out), the error is:

```
Fatal error: Could not convert the script from the detected encoding "UTF-32LE" to a compatible encoding in /root/TestProject/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php on line 158

Fatal error: Could not convert the script from the detected encoding "UTF-32LE" to a compatible encoding in /root/TestProject/vendor/composer/ClassLoader.php on line 444
```

Now, I'm trying to figure out which config change exactly that has caused. I didn't set the opcache settings, so those can be ignored. My guess is cgi.fix_pathinfo, but I'll test this out to be certain and post the results. 

Again, this doesn't happen with Symfony 3.1.0 (I tested that one out as well), this only happens in Symfony 3.2.0+. 

-to be continued-

**Comment by patrickvane** [comment]
Well that was fast. It was `zend.multibyte = On` that caused it. 

Could you try setting zend.multibyte to On to see if that would also cause cache:clear to throw errors?

**Comment by nicolas-grekas** [comment]
Can you please share a VM that reproduce this?

**Comment by patrickvane** [comment]
Well I already deleted them, but I recreated a new one, same as before except that I just changed the zend.multibyte option and nothing else (tested it, cache:clear throws errors). 

SSH:
 Host: root@128.199.51.239
 Port: 22
 Password: symfony-demo

"~/TestProject" is currently a new Symfony 3.2.0 project. 

To get the error, do:

```
cd TestProject
export SYMFONY_ENV=prod
php ../composer.phar install --no-dev --optimize-autoloader
php bin/console cache:clear --env=prod --no-debug
```

**Comment by nicolas-grekas** [comment]
So, this looks like https://bugs.php.net/64912
It happens when both "zend.detect_unicode" and "zend.multibyte" are "on".

**Comment by patrickvane** [comment]
Great find! Seems like your fix would solve it. 

Now this might sound dumb, because I don't know how Symfony works internally, but I got to wonder, in your fix, what happens when zend.multibyte is set to 1 after the `$this->zendMultiByte = ini_get('zend.multibyte');` statement was run? What if it was 0 at that time, but then during 

```
if ($this->zendMultiByte) {
   $zmb = ini_set('zend.multibyte', 0);
}
```

it is 1. Wouldn't that cause your fix to be skipped, causing the bug to still happen? 

Although this only happens during cache:warmup, and I don't know if that executes any user code or just Symfony code. If it won't execute any user code then it won't matter much, the fix will work fine then.

**Comment by nicolas-grekas** [comment]
Then it will break again. But nobody does that, and we shouldn't make everyone pay extra function call for such silly situations. That's why I made the code like that at least.

**Comment by patrickvane** [comment]
Ehm, wait, I just tested it out and it still errors, even when I did it like this:

```
    private function initialize()
    {
//        if ($this->zendMultiByte) {
            $zmb = ini_set('zend.multibyte', 0);
//        }
        try {
            $this->values = file_exists($this->file) ? (include $this->file ?: array()) : array();
        } finally {
//            if ($this->zendMultiByte) {
                ini_set('zend.multibyte', $zmb);
//            }
        }
    }
```

Didn't you test out the fix on the shared server?

It seems like ini_set doesn't work with zend.multibyte.

**Comment by nicolas-grekas** [comment]
Hum, I tested but with zend.detect_unicode, then read on PHP docs that send.multibyte was also possible, and moved on to implement the fix. My bad for not testing then.
Can you replace and submit a PR on 3.3 if it works? (it should!)

**Comment by nicolas-grekas** [comment]
OK, confirmed to work with zend.detect_unicode, PR here: #24003

**Comment by patrickvane** [comment]
Nice, tested it as well, fix works correctly. Good job.
