### ISSUE TITLE
Exception thrown right after updating to 3.3.0: Invalid key "X" found in arguments of method "__construct()", only integer or $named arguments are allowed

### ISSUE THREAD

**Issue by yukoff** [symfony/symfony#22979]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.3.0

Right after updating to v3.3.0 my app started to crash with an exception (tried on PHP 7.0.12 and 7.1.3)
```
An error occurred when executing the ""cache:clear --no-warmup"" command: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid key "event_dispatcher" found in arguments of method "__construct()" for service "tmdb.configuration": only integer or $named arguments are allowed. in /sandbox/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php:47
Stack trace:
#0 /sandbox/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /sandbox/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /sandbox/project/vendor/symfony/symfony/s in /sandbox/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php on line 47
```

After reverting back to 3.2 (3.2.9) works perfectly. If I exclude corresponding bundle from loading it will creash for the next one with the same message. I'm not sure what are exact steps to reproduce - in my case it was a simple update from 3.2.8 to 3.3.0, I'll try to narrow this down.

**Comment by xabbuh** [comment]
Related to #22981?

**Comment by weaverryan** [comment]
@yukoff Can you post your `services.yml` file? Specifically, show how the `tmdb.configuration` service configuration looks?

**Comment by yukoff** [comment]
@xabbuh It seems related at the first sight, but with patch applied from the #22981 app crashes with
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "redis_host". Did you mean this: "doctrine.orm.cache.redis_host"? in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php:100
Stack trace:
#0 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('redis_host')
#1 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(217): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('redis_host')
#2 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(187): Symfony\Component\DependencyInjection\Par in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php on line 100
```

However `redis_host` is indeed defined (and worked with 3.2.9) via `parameters.php`:
```php
if ($redisUrl = getenv('REDIS_URL')) {
    $parts = parse_url($redisUrl);
    $container->setParameter('redis_host', $parts['host']);
    $container->setParameter('redis_port', $parts['port']);
    $container->setParameter('redis_user', $parts['user']);
    $container->setParameter('redis_pass', $parts['pass']);
}
```

**Comment by weaverryan** [comment]
@yukoff Can you post your full configuration setup? It seems like there may be multiple things going on, and I want to be able to untangle all of them :)

**Comment by yukoff** [comment]
@weaverryan with pleasure ;) - [here it is](https://github.com/php-tmdb/symfony/blob/2.0/Resources/config/services.xml#L28)

**Comment by weaverryan** [comment]
Thank you!

Ok, first thing:

```xml
<argument key="event_dispatcher" type="service" id="event_dispatcher" />
```

Iirc, ising the `key` like this was meaningless before 3.3 -  it just added this as the first argument. We made this explicitly illegal in 3.3 - so you should just remove this. But, it is a minor BC break.

Next:

> You have requested a non-existent parameter "redis_host"

Afaik, nothing changed significantly in this area... if you put a `die()` inside the `if` statement in `parameters.php` and rebuild your cache, is it being hit? What is making sure the `REDIS_URL` environment variable is being set?

Cheers!

**Comment by yukoff** [comment]
@weaverryan Rechecking right now - I same have a filing I might missed something, however all used vars should be in .env

**Comment by yukoff** [comment]
Yep, just like you said @weaverryan - now it's on
```
Invalid key "event_dispatcher" found in arguments of method "__construct()" for service "tmdb.configuration": only integer or $named arguments are allowed.
```

**Comment by yukoff** [comment]
Ok, got rid of `key=` attribute, now the error is
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid key "collaboration" found in arguments of method "__construct()" for service "sulu_admin.js_config_pool": only integer or $named arguments are allowed. in ...\Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass.php:47
```

**Comment by yukoff** [comment]
The service
```
        <parameter key="sulu_admin.js_config_pool.class">Sulu\Bundle\AdminBundle\Admin\JsConfigPool</parameter>
...
        <service id="sulu_admin.js_config_pool" class="%sulu_admin.js_config_pool.class%"/>
```

The `Sulu\Bundle\AdminBundle\Admin\JsConfigPool` is a non-derived class without defined constructor.

**Comment by dunglas** [comment]
Can we have to your repo? I cannot find the string `"collaboration"` in the Sulu's repository. It looks relate to your config.

**Comment by yukoff** [comment]
@dunglas I'm just as confused as you o_O Trying to figure out, but this is all I have in it
```
$ git grep collaboration
app/config/admin/sulu.yml:        sulu_collaboration_entity:
app/config/admin/sulu.yml:                directory: "%sulu.cache_dir%/collaboration/entity"
app/config/admin/sulu.yml:        sulu_collaboration_connection:
app/config/admin/sulu.yml:                directory: "%sulu.cache_dir%/collaboration/connection"
app/config/admin/sulu.yml:sulu_collaboration:
app/config/admin/sulu.yml:    entity_cache: doctrine_cache.providers.sulu_collaboration_entity
app/config/admin/sulu.yml:    connection_cache: doctrine_cache.providers.sulu_collaboration_connection
```

Unfortunately I can't provide you with an url as it is a WIP project I'm currently working unavailable to public (and I think it is barely related - everything works if change just one line to be ~3.2.8 ;)

On the other hand I might misunderstood you on regard
> Can we have to your repo? ...
I guess you already came across [sulu/sulu](https://github.com/sulu/sulu)?

**Comment by weaverryan** [comment]
It looks like Sulu was updated for 3.3 support: https://github.com/sulu/sulu/pull/3379

Does upgrading to that fix all of the issues?

**Comment by danrot** [comment]
Yeah, ran into the same issue, and I've already fixed it in Sulu 😄

**Comment by yukoff** [comment]
@weaverryan @danrot Yep, things ok after update. Thanks for the update!

**Comment by weaverryan** [comment]
Thanks guys!
