### ISSUE TITLE
Redis Cache Adapter always uses tcp scheme even if unix socket connection string used

### ISSUE THREAD

**Issue by kopeckyales** [symfony/symfony#22974]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Cache/Traits/RedisTrait.php

line 123

```php
$params['scheme'] = isset($params['host']) ? 'tcp' : 'unix';
```

line 93

```php
$params += array(
            'host' => isset($params['host']) ? $params['host'] : $params['path'],
```

so $params['host'] is never empty => scheme is always tcp even if path is unix socket, which leads to exception in Predis Client.

**Comment by nicolas-grekas** [comment]
@kopeckyales would you like to submit a PR to fix this? I guess the bug also exists in 3.2 where it should be fixed?
