### ISSUE TITLE
.trace-head should not have `use-select: none` style

### ISSUE THREAD

**Issue by tom10271** [symfony/symfony#22982]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

`vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/views/exception.css.twig`
```css
.trace-head { -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; }
```

It blocks developer from highlighting and copying message for further googling.

Thanks

**Comment by xabbuh** [comment]
Thanks for reporting this @tom10271. However, we already have a similar report in #22957. Thus I am closing here as a duplicate.
