### ISSUE TITLE
User Deprecated: The "Twig_TokenParser_Include"

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#22998]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.0

> User Deprecated: The "Twig_TokenParser_Include" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Twig_TokenParser_Embed".

i didn't find usage of this function..
after refresh it's gone.

**Comment by stof** [comment]
this does not happen in Symfony. *Both* classes are in Twig. So I'm closing this issue (this is already reported on the Twig repo)

**Comment by ben29** [comment]
can you share with me the link to track this error?

**Comment by xabbuh** [comment]
see twigphp/Twig#2459
