### ISSUE TITLE
Can't find WebServerBundle commands anymore in 3.3.0

### ISSUE THREAD

**Issue by Id4v** [symfony/symfony#23006]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

When migrating from Sf 3.2.x to 3.3.x I encountered an issue with the WebServerBundle.

Since 3.3.x WebServerBundle is a standalone bundle but Symfony's `composer.json` says that `symfony/symfony` replaces `symfony/web-server-bundle` 

```json
 "replace": {
    ...
    "symfony/web-server-bundle": "self.version",
    ...
}
```
I think, this results in `symfony/web-server-bundle` being never installed, therefore `server:*` commands not being available.
Is it correct, or am I missing something here ?

**Comment by chalasr** [comment]
The code you pasted only means that _if installed_, the package version should be `self.version` (the current `symfony/symfony` version).
Follow [the corresponding upgrade note](https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md#frameworkbundle) to get `server:*` commands working again

> The server:run, server:start, server:stop and server:status console commands have been moved to a dedicated bundle. Require symfony/web-server-bundle in your composer.json and register Symfony\Bundle\WebServerBundle\WebServerBundle in your AppKernel to use them.

**Comment by stof** [comment]
symfony/symfony actually replaces the bundle, this is true. the bundle is part of the main repo, like FrameworkBundle and TwigBundle

**Comment by chalasr** [comment]
So we should get the bundle installed when using `symfony/symfony`?

**Comment by stof** [comment]
@chalasr you already have the code of the bundle. But you need to register it in your kernel

**Comment by Id4v** [comment]
@stof indeed, registering WebServerBundle in AppKernel fixes it. 
My bad.

I'll close this issue as it's stated in the upgrade note (I read it, but somehow missed it)

Thanks.
