### ISSUE TITLE
PhpUnit-Bridge can't deal with @runTestsInSeparateProcesses

### ISSUE THREAD

**Issue by paul-m** [symfony/symfony#23003]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | maybe
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.2.8

I'm working on Drupal 8 core. Drupal has adopted symfony/phpunit-bridge as a way to catch deprecations. The codebase has a lot of `@trigger_error('', E_USER_DEPRECATED)` type code in it.

The problem is that a lot of our PHPUnit-based tests are functional and need to run in isolated processes.

There are two problems:

1) We can't test `@expectedException` in isolated tests. They always fail.

2) Errors triggered by `@trigger_error()` never surface in isolated tests.

There are two reasons for this:

For 1 above, `SymfonyTestsListener` sets the expectation for the test run before the isolation occurs. Whatever deprecation error is emitted, it happens in another process. When it's done, the 'host' listener then finds no deprecation message so it fails the test.

For 2 above, the problem is that a) `Symfony\Bridge\PhpUnit\DeprecationErrorHandler` is never registered in isolation, due to the way the isolation occurs. Also, once you solve the problem of registering the error handler, it fails the test by calling `exit(1)`. As it turns out, PHPUnit ignores the return value of the child process, so we never get the fail.

I've written a patch for Drupal that basically overcomes these limitations, but it's effectively a fork of symfony/phpunit-bridge, and it'd be much better not to do that.

You can see the patch here: https://www.drupal.org/node/2870194#comment-12111028

Is there a reason symfony/phpunit-bridge doesn't support isolated tests? I couldn't find a testing policy document to see if the limitation was arbitrary or intentional.

**Comment by nicolas-grekas** [comment]
Please submit a PR. The limitation should be removed!

**Comment by paul-m** [comment]
Splitting this up because it's complex and might require an upstream change for phpunit.

First, I'm working on marking isolated tests with @expectedDeprecation as risky. Progress here: https://github.com/symfony/symfony/compare/master...paul-m:mark-isolated-tests-risky

Not ready for a PR because I don't know enough about the symfony phpunit script to understand how to make it pass without hanging.

**Comment by nicolas-grekas** [comment]
@paul-m the hanging might have been solved in #24498, so that submitting your PR might be unlocked now, looking forward to it :)

**Comment by paul-m** [comment]
Thanks. I'm a bit of a newbie to the Symfony way of doing things, so I wasn't sure if it was me missing a step or something.

I'm coming at this from the Drupal 8 world, where we're stuck at phpunit-bridge 3.2.*. See https://www.drupal.org/node/2882826

**Comment by nicolas-grekas** [comment]
@paul-m about https://www.drupal.org/node/2882826, the bridge should work with a recent enough version of PHPunit 4.8.*
