### ISSUE TITLE
Cannot redeclare ContainerAwareInterface in classes.php

### ISSUE THREAD

**Issue by MassiveHiggsField** [symfony/symfony#23016]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

After upgrading from Symfony 3.0.6 to 3.3.0 something with the cache seems to be broken in production mode. There are some other tickets basically mentioning the same issue, but the solution was always to remove the offending class from src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php

Similar issues/pull requests:

https://github.com/symfony/symfony/pull/22657
https://github.com/symfony/symfony/issues/20753
https://github.com/symfony/symfony/issues/21520

and some more, just search for redeclare in the issues.

My problem specifically concerns the ContainerAwareInterface, the error message is:

 PHP message: PHP Fatal error:  Cannot redeclare class Symfony\\Component\\DependencyInjection\\ContainerAwareInterface in var/cache/dhs/prod/classes.php on line 3364

At first i tried the usual, cache clearing (via rm and app/console), vendor reinstalls (even removing the complete vendor directory). 

I just removed the class from the list in FrameworkExtension.php, cleared the cache and everything works fine so far. Is there a bigger problem with this new caching mechanism or is it my environment?

**Comment by sstok** [comment]
Are you using opcache? try clearing this.

For now you can remove this line https://github.com/symfony/symfony-standard/blob/3.3/web/app_dev.php#L27 (it may negatively effect performance if your not using PHP 7).

**Comment by MassiveHiggsField** [comment]
OpCode Cache clearing didn't solve it unfortunately, removing the line of course does. For now, this is okay, since we're in the process of finally moving to php7, so this may not be an issue then.

**Comment by nicolas-grekas** [comment]
This caching mechanism is fragile. Not using it is the proper fix. (And moving to php7 :))
Closing as this is already deprecated.
