### ISSUE TITLE
[Security] Make Role::$role protected

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#23025]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Since `Symfony\Component\Security\Core\Role\RoleInterface` is deprecated, there is no possibility to create a Role entity anymore. `Symfony\Component\Security\Core\Role\Role::$role` is private and extending the `Role` class doesn't allow to add mapping to that property.

I suggest making `$role` protected. If I am not mistaken this won't break existing child classes.

**Comment by iltar** [comment]
You can still create a role entity, you just can't store it in your session anymore.

**Comment by xabbuh** [comment]
By the way, there is a proposal to also deprecate the entire `Role` class in Symfony 3.4 (see #22048). So you will probably be better off by using strings as roles instead.

**Comment by vudaltsov** [comment]
Got it, thank you 👍
