### ISSUE TITLE
[DX] Exception Message is not Selectable

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#23020]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

Symfony 3.3.0 introduced new exception page which makes debugging so much easier and presents all the information in a cleaner form. However I immediately discovered one design decision/bug which makes communication with a team harder: you cannot select and copy&paste exception message nor its class.

To better illustrate the problem see the following animation:
![selection](https://cloud.githubusercontent.com/assets/1227834/26693148/c2272fe4-46c8-11e7-95e3-800f1cfefd9d.gif)

I marked this as bug rather than a FR, since older version of that page allowed to select everything.

**Comment by fabpot** [comment]
Already fixed :)

**Comment by kiler129** [comment]
@fabpot: Thank you!
