### ISSUE TITLE
[DX][WebProfiler] Logger panel, filter log channel

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#23038]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=2.7

Hi!

I would like to know if there is a way to have a feature that filters the channel(s) and so logs in the logger pannel? maybe a multiple select could do the job
story: when the dev selects one or many channel(s), only the mapped logs will be displayed

(PS: i am using sf2.8, so maybe this kind of feature exists already on 3.X)

cf my screenshot

![a](https://cloud.githubusercontent.com/assets/13205768/26732614/7093a540-47b8-11e7-8078-0d74ecbdc437.png)

What do you think?

Many thanks!

**Comment by ogizanagi** [comment]
This feature does not exist yet, but I do think it is useful and could be achieved easily (perfect for a first contribution).
Would you open a PR targeting the 3.4 branch?

**Comment by javiereguiluz** [comment]
I'm not that sure that it will be easy ... and looking at the "debug" tab should be exceptional. The normal use case is to look into "Info & Errors" and occasionally, look at "Deprecations". In my opinion, the rest (debug, silenced errors and containers) are rare and you "never" look at them unless a weird error happens.

**Comment by ogizanagi** [comment]
You're right. I honestly can't say I'm looking much at this panel usually and most of the logs in there aren't useful to me (doctrine, events, security, ...). But it clearly depends on your application. If you have some complex actions or tough code paths, debug logs become really useful...but those are drowned inside this panel amongst all the other non-useful ones. And you can't even filter to get the "app" channel (or any other relevant one for you), beyond doing a CTRL + F search.

**Comment by noniagriconomie** [comment]
Hi

Thanks for your time and comments

Actually i was thinking of this feature when i was working on my project and debuging my app with my log

We have some specific monolog channels, cart, where we log the cart add item or cart validation during the checkout process

And finding the actual cart channel was hard, indeed i do cmd+f for that

Hope my explanations are more precises

**Comment by noniagriconomie** [comment]
Any chance to get a feature like that? 
If not, or not now, you can close the issue :)
Thanks

**Comment by noniagriconomie** [comment]
@ogizanagi @javiereguiluz ping ?

cf my previous comment

If there is no chance to get this feature for 3.4, you can close the issue

Thank you,

**Comment by javiereguiluz** [comment]
I'm afraid I'm going to close this as "won't fix" because I guess this won't be simple to implement (we're trying to simplify lots of things in Symfony; for example: some config options of the debug toolbar: #23728).

My advice would be to log the `cart` channel logs with a `INFO` priority. That way they'll appear in the first logger tab. You'll have the important information at once and without having to do anything or click on any tab or filter anything.

**Comment by noniagriconomie** [comment]
@javiereguiluz understood

more goiing to do cmd + f searches :)

thank you anyway for your time

**Comment by javiereguiluz** [comment]
I'm not sure I understand your comment. If you use [the info() method of the logger](https://symfony.com/doc/current/logging.html), your `cart` channel messages will appear in the first tab of the logger panel. Not only you can forget about `cmd + f` forever, but you don't have to click anywhere or do anything else.

**Comment by noniagriconomie** [comment]
@javiereguiluz i took the "cart" channel example, but we have maybe 10+ specific channels to separate our business logs :) (and remove them from the sf log stack)

sometimes we log in a request debug, info, critical and in case of critical we flush
the aim of this issue was to get those all log no matter their level in the profiler to check fastly the log context flow :)
