### ISSUE TITLE
[Command] exit codes

### ISSUE THREAD

**Issue by wickedOne** [symfony/symfony#23030]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

##### Use case:
We have several multi langual repositories and a ci server doing all kinds of basic build tests for each proposed pull request. One of those checks is to see whether there are any missing translations. A command like
```
php bin/console debug:translation --only-missing en --all
```
perfectly lists all missing translations, but always returns an exit code ``0``.
Hooking into the ``command.terminate`` event gives you the ``OutputInterface`` but gives you no clue to what has been the result of the command. So now i stream the command result into a file which i have to scan for a ``missing`` string.

##### Feature request:
Would it be of added value to have a more flexible way to manipulate the exit code of any given command by, for example, firing error- and / or warning events?

**Comment by chalasr** [comment]
Since you are running this command for being aware of your missing translations, and it gives you them all, then the command did its job successfully, thus the exit code should be 0. There's no error so no error code to set, isn't it?

>  So now i stream the command result into a file which i have to scan for a missing string.

That seems to be the right way for what you're trying to achieve. To return an error code in some conditions, I would look at extending the command to redefine it, failing in case nothing has been written in your case.

**Comment by wickedOne** [comment]
yes, you're right, the command works fine and outputs all the information i need and in most cases that's sufficient.

nevertheless i think the exit code should depend on the result rather than whether or not the command ran successfully.

I could extend the command from this example, but as it returns nothing  a ``parent::execute(...`` wouldn't be sufficient so i have to copy all the code from the execute function from this command and define an exit code based on whether or not the ``SymfonyStyle`` table has any rows or not. personally i don't think that's a good strategy.

**Comment by chalasr** [comment]
I agree, maybe this specific command needs an additional option to throw on missing translation or something like? Adding a generic way to change the exit code sounds hard to implement.

**Comment by wickedOne** [comment]
the ``SymfonyStyle`` already provides a [variety of functions](https://github.com/symfony/console/blob/master/Style/SymfonyStyle.php#L143-L178) for several result levels. As the console component is [already aware of the dispatcher](https://github.com/symfony/console/blob/60d0efcb8470bf5cfbea84bff99cf1af0ccfdf00/Application.php#L802) it might be a thought to somehow hook into this.

this way it won't break any current implementations while providing a more flexible way to manipulate the result of a command

**Comment by stof** [comment]
@wickedOne you might be interested in https://github.com/Incenteev/IncenteevTranslationCheckerBundle which provides commands suited for CI needs (it builds on top of the Symfony extraction system, it does not rebuild one from scratch)

**Comment by wickedOne** [comment]
@stof thanks for that! looks like that bundle does exactly what i'm looking for in this use case (will have a go at it next tuesday).

nevertheless i'd like to continue the discussion whether or not it would be of added value if we provide a more flexible system to hook into the command results. by accident i ran into this specific use case last week, but can imagine there are plenty of use cases where a developer / ci server wants to hook into the results of a (3rd party) command.

**Comment by nicolas-grekas** [comment]
> flexible way to manipulate the exit code of any given command 

this has been improved in 3.3, and you should be able to register to both `ConsoleEvents::TERMINATE` and `ConsoleEvents::ERROR,` events and change the exit code from a listener, isn't it?

**Comment by wickedOne** [comment]
if i remember correctly those events _do_ give you access to the ``OutputInterface`` nevertheless, at that point you don't have a clue what has been sent to the output before the event was fired, so manipulating the access code based on previous output seems impossible.

a thought might be register warnings, errors, infos, etc. (something like ``$ouput->warning('tanslation x.y.z missing')``) within a command (similar to whet is done in the ``LoggerInterface``) and provide a way in the application's configuration to configure the severity / exit code for that

**Comment by chalasr** [comment]
You should throw a domain exception from your command, one that you can rely on for setting the exit code. Setting the exit code will make the exception caught and only your warning will be displayed.
Closing here because the existing solution should be enough to not implement such generic mechanism. Please comment if you disagree. Thanks.

**Comment by wickedOne** [comment]
i'm not sure whether i understand your comment.

the command component indeed is flexible enough to have control over exit codes when you're dealing with commands you write yourself. 

this discussion however is about having a bit more influence on exit codes from commands provided by third parties (which is symfony from this specific example) so that you don't have to copy an entire command in order to set an exit code which your ci understands

**Comment by chalasr** [comment]
Alteing command exit codes based on the output is probanly not something we want to support. 
If your command outputs a warning message and a success (in this order), what code should it use? Also the different outputs are not all promising a style API and the command exit code is handled at the Application level, I don't see how could this be implemented in a generic way.
