### ISSUE TITLE
Parent, child category not working 

### ISSUE THREAD

**Issue by shahzadthathal** [symfony/symfony#23055]
Hi,

I'm trying to save parentId(parent category id) against child category id but it is not working.
I have followed this [article](http://symfony.com/doc/current/reference/forms/types/entity.html#choice-attr)

I have used ```tempCatId``` filed but it always shows me null, how I can  ```tempCatId``` when I select a category from the dropdown and submit the form?

```Symfony version 3.3```

ProductCategory.php
```
    /**
     * @var integer
     * @ORM\Column(name="parent_id", type="integer", nullable=true)
     */
     private $parentId;
    
    private $tempCatId;
   
    public function setTempCatId($param){
        $this->tempCatId = $param;
        return $this;
    }
    public function getTempCatId(){
        return $this->tempCatId;
    }
```

ProductCategoryType.php
```
 public function buildForm(FormBuilderInterface $builder, array $options){
        $builder->add('tempCatId', EntityType::class, array(
            'class' => 'AdminBundle:ProductCategory',
            'choice_label' => function ($tempCatId) {
                return $tempCatId->getTitle();
            },
            'placeholder' => 'Choose parent category',
            'required' => false,
        ));
        $builder->add('title', TextType::class);
        $builder->add('sortOrder', TextType::class);
        $builder->add('status', ChoiceType::class, array(
        'choices' => array('Active' => true, 'In Active' => false),
        ));
    }
```
Form:

```
      <div class="form-group">
	        {{ form_label(form.tempCatId, 'Parent Category') }}
	        {{ form_errors(form.tempCatId) }}
	        {{ form_widget(form.tempCatId, {'attr': {'class': 'form-control'}}) }}
    	</div>
   //I can see this html in console
  <select id="product_category_tempCatId" name="product_category[tempCatId]" class="form-control">
 <option value="">Choose parent category</option>
<option value="1">First Category</option>
</select>

```
ProductCategoryController.php

```
    public function createAction(Request $request, Slugger $slugger){
            $item = new ProductCategory();
            $form = $this->createForm(ProductCategoryType::class, $item)
            ....
          if ($form->isSubmitted() && $form->isValid()) {
                echo "<pre>";
                print_r($item);
                exit;
```
Print 

> results:AdminBundle\Entity\ProductCategory Object
(
    [parentId:AdminBundle\Entity\ProductCategory:private] => 
    [slug:AdminBundle\Entity\ProductCategory:private] => 
    [title:AdminBundle\Entity\ProductCategory:private] => Chil Category of First cat
    [status:AdminBundle\Entity\ProductCategory:private] => 1
    [sortOrder:AdminBundle\Entity\ProductCategory:private] => 0
    [id:AdminBundle\Entity\ProductCategory:private] => 
    [tempCatId:AdminBundle\Entity\ProductCategory:private] => AdminBundle\Entity\ProductCategory Object
        (
            [parentId:AdminBundle\Entity\ProductCategory:private] => 
            [slug:AdminBundle\Entity\ProductCategory:private] => first-category
            [title:AdminBundle\Entity\ProductCategory:private] => First Category
            [status:AdminBundle\Entity\ProductCategory:private] => 1
            [sortOrder:AdminBundle\Entity\ProductCategory:private] => 1
            [id:AdminBundle\Entity\ProductCategory:private] => 1
            [tempCatId:AdminBundle\Entity\ProductCategory:private] => 
        )

)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by shahzadthathal** [comment]
I think this is a bug, please read my issue ;)

**Comment by xabbuh** [comment]
No sorry, this is just how the entity type works. It's dealing with objects not IDs. Doctrine ORM is about mapping associations between objects to a relational database. However, you are moving things there by not writing objects but IDs.
