### ISSUE TITLE
[Form] DateType widget choice - always render months as numbers

### ISSUE THREAD

**Issue by krafas** [symfony/symfony#23064]
Now Symfony DateType has 3 widget types: `choice`, `text`, `single_text`. 

When using widget type `choice` the format is `y-M-d` and can't be changed, see: https://github.com/symfony/symfony/blob/v3.3.0/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L73

We have business requirement, that months always must be rendered as numbers (from 01 to 12). What is the best way to achieve this?

**Comment by yceruto** [comment]
> We have business requirement, that months always must be rendered as numbers (from 01 to 12). What is the best way to achieve this?

```php
$form = $this->createFormBuilder()
    ->add('birthday', DateType::class, [
        'widget' => 'choice',
        'format' => 'MM-d-y',
    ])
    ->getForm();
```

![date_type](https://cloud.githubusercontent.com/assets/2028198/26787809/4592aeea-49d9-11e7-867a-48449115d4ad.png)

**Comment by yceruto** [comment]
However I think https://github.com/symfony/symfony/pull/21063 introduces one BC break not allowing these month formats: `LLL-d-y` or `LLLL-d-y` for widget `choice` ?

**Comment by krafas** [comment]
Thank you, @yceruto!
