### ISSUE TITLE
Accidental Twig Namespace break in 3.3.1

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#23072]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.1

In #22962, we accidentally broke some things. I don't know how extensive it is, but for example: https://github.com/symfony/symfony/commit/c3d1262208783fa103e7bb9fe5b3cddb1096dcfd#diff-8c3f0dfe6717f0f670f95e3d4a88873b - `Node_Block` on line 51 and `Node_Set` on line 56 are not defined. This breaks things pretty hard on 3.3.1.

I'm about to leave work for today... so I don't have time to fix. Hopefully someone else will see this!

**Comment by ogizanagi** [comment]
I think #23073 should solve this.
