### ISSUE TITLE
[Form] Ability to define form theme file in type class

### ISSUE THREAD

**Issue by bOmBeLq** [symfony/symfony#23070]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

So I've been wondering what if we added a **theme** option to form type options. By default this field value would be null for BC but if value set then it would result in kind of automated call to 
`{% form_theme form_view theme_from_the_type_options %}`

This would allow for simpler creation of bundles with form types which already have templates. Currently you would have to use compiler pass to  **automaticly** add your theme to twig themes when bundle is registered or user has to manually register your form theme (I've seen both cases being used by bundle creators). 

Having the **theme** option on form type would also allow for much simpler templating of forms.
For example you could have form type named `JqueryUploadType`
Now if you define separate template named `jquery_upload_theme.html.twig`
then you have to define there blocks named `jquery_upload_widget`, `jquery_upload_row` etc. and also register your theme in global themes list or manually call form_theme.

With the **theme** option on form having `form_widget` and `form_row` blocks would be enough because the template is applied only to this field. I know you can achive this by calling
`{% form_theme form.yourField 'path_to_template.html.twig' %}` but this requires some extra code if you use your field in many places. Also if you use it as CollectionType entry then you would have to iterate over all fields.

Is there any particular reason such option has not been introduced on form types yet?
Would this be an performance issue? Or maybe it's about separation of backend and frontend logic?

**Comment by iltar** [comment]
> Or maybe it's about separation of backend and frontend logic?

I think this is the primary reason. Things related to your view, should not be in a blueprint that maps html elements to data objects and validation.

**Comment by bOmBeLq** [comment]
@iltar Yes, though there are still some parts of form type that strongly affect frontend:
- type name itself
- label option
- attr option
- getBlockPrefix method
- finishView 

I think that adding template path in options for convinience wouldn't be bad idea.
I'm going to do it anyway. The question is should I do a PR or a separate bundle which would add this functionality (though separate bundle may be hard to achieve).

**Comment by iltar** [comment]
This might be of assistance: http://symfony.com/doc/current/form/create_form_type_extension.html

**Comment by bOmBeLq** [comment]
Thank you very much for advice. This will be probably way to go for the "option" part. The complicated part will be to internally addding the template as theme to the form type.

**Comment by bOmBeLq** [comment]
Closing in favor of pull request https://github.com/symfony/symfony/pull/23990.
