### ISSUE TITLE
Cache warming requiring database connections

### ISSUE THREAD

**Issue by thanosp** [symfony/symfony#23079]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.9, 3.3.0, 3.3.1, 3.3.2

After updating to 3.2.9 or 3.3.[0-2] it seems even running plain `bin/console` tries to warm up the whole system requiring database connections, redis and whatnot to be available.
That blocks for example asset generation happening on a CI server for prepackaging or even running composer install on CI which will trigger the `ScriptHandler` scripts ending up in symfony's dev mode (requiring again a database).

**Comment by xabbuh** [comment]
Are you able to provide a small project that allows to reproduce your issue and/or a stack trace?

**Comment by thanosp** [comment]
For me to reproduce it I just need to remove the cache dir fully and run plain `bin/console`. 
Which leads to this breakpoint trying to connect to mysql.
This is with Symfony 3.3.2.

![screen shot 2017-06-06 at 10 58 49](https://cloud.githubusercontent.com/assets/1217690/26821612/44e37ff0-4aa7-11e7-9325-3f88eb02e0f1.png)

**Comment by xabbuh** [comment]
You should be able to stop Doctrine from trying to detect the database platform version by explicitly configuring the server version as explained in https://github.com/doctrine/DoctrineBundle/issues/351#issuecomment-65771528.

If you don't want to trigger the `ScriptHandler` you can also run `composer install` with the `--no-scripts` option.

**Comment by thanosp** [comment]
@xabbuh thanks that solves my issue indeed
