### ISSUE TITLE
About the twig namespace path question or bug

### ISSUE THREAD

**Issue by TonyGao** [symfony/symfony#23077]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

Hi, there

I have two question and maybe one of them is a bug. 

First, I have a template namespaced path which is in a controller like below.

```
$twigShortName = "@SunshineUIBundle/Resources/views/base.html.twig";
$path  = $this->getContainer()->get('kernel')->locateResource($twigShortName);
```

It works fine, but maybe the classic three layer namespaced path below is better choice, my question is how can I transform it to the the real path?

```
$twigShortName = "@SunshineUIBundle::base.html.twig";
$path  = WhatMethod?? ($twigShortName);
```

Second, I want to use another way to get the template name

```
$twig = $this->getContainer()->get('twig');
$template = $twig->loadTemplate($twigFile);
dump('Template name: '.$template->getTemplateName());
```

But I got three different result in this way as below

```
"Template name: SunshineAdminBundle:Default:index.html.twig"
"Template name: @SunshineOrganization/title/title.html.twig"
"Template name: /Users/tony/Sites/Sunshine/Sunshine/src/Sunshine/OrganizationBundle/Resources/views/title/new.html.twig"
```

I don't know what's going on there, is that a regular result? or may be it should be use one style or type result by the same method ?

**Comment by mvrhov** [comment]
Using twig namespaces  aka the first one is the recommended one, the 2nd one is/should be deprecated.

**Comment by stof** [comment]
Can you show the code corresponding to each dump, to make it easier to understand your case ?

**Comment by TonyGao** [comment]
@stof  Here's the code

https://github.com/TonyGao/Sunshine/blob/master/src/Sunshine/AdminBundle/Command/ListBundlesCommand.php#L58

It's about list all my bundles and all twig in the bundles and all blocks in the twigs.

**Comment by TonyGao** [comment]
@mvrhov thanks, I find a solution here

```
$this->twig = $this->get('twig');
$path = $this->twig->getLoader()->getCacheKey(str_replace('@', '', $template));
```

**Comment by stof** [comment]
Well, if you want the file path rather than then template name, use `$template->getSource()->getPath()`

**Comment by TonyGao** [comment]
@stof Actually I already got it's absolute path by finder, and I want the template name by SunshineAdminBundle:Default:index.html.twig or @SunshineOrganization/title/title.html.twig, but I found $template->getTemplateName() alway give me different format.

**Comment by stof** [comment]
Well, the name given by `getTemplateName` depends on the name you gave when loading the template. The template name is the input of the Twig API

**Comment by TonyGao** [comment]
@stof Thank you for the explanation, I close this issue if it's not a bug.
