### ISSUE TITLE
The CSRF token is invalid. Please try to resubmit the form

### ISSUE THREAD

**Issue by shahzadthathal** [symfony/symfony#23071]
Hi, 
I have followed this article but I'm getting this error when submitting the form through ajax.
http://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms

I have already added this in my form but the error is still there:

```
        {{ form_start(form) }}
        {{ form_row(form._token) }}
```
I can see csrf token in inspect element:
```
<form name="product" method="post">
        <input type="hidden" id="product__token" name="product[_token]" value="oc-sS1-N_VreWGa5_IsbYS6RLwy4F7EEv-Ua1_w6CJg" />```

**Comment by yceruto** [comment]
https://stackoverflow.com/a/9004896/4224384

**Comment by shahzadthathal** [comment]
But the issue is this, please read my question here
https://stackoverflow.com/questions/44375317/symfony-populate-sub-category-dropdown-on-change-parent-category

**Comment by latheva** [comment]
Make sure the sessions dir is existe in the root directory and its writable.

cheers
