### ISSUE TITLE
[Console] Passing extra option/argument to console command silently ignored and following arguments/options ignored too

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#23089]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Symfony version  | 3.2.x

I've noticed that passing an extra argument/option to my command is an error, and this error break following options to be parsed.
But this error is silently ignored (swallow-all exceptions code added in https://github.com/symfony/symfony/commit/0af16762932e96500e2e8a143c058dcbfaac8bb9), and my command just run without any passed option/arguments. I would consider this as a bug.

**Comment by chalasr** [comment]
Could you provide a simple reproducer?

**Comment by Strate** [comment]
Oh, sorry, this is not actual, i have been on broken version, which was introduced and fixed there https://github.com/symfony/symfony/pull/21841. So, I just updated and everything goes ok
