### ISSUE TITLE
User Deprecated: Setting the "esi" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0.

### ISSUE THREAD

**Issue by Korikulum** [symfony/symfony#23080]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0, 3.3.1, 3.3.2

The `HttpCache` throws a deprecation notice when esi is enabled:
```
# config.yml
esi: { enabled: true }
# app_dev.php
$kernel = new AppCache($kernel);
```

`User Deprecated: Setting the "esi" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0.`

**Comment by ro0NL** [comment]
Tracked it down to https://github.com/symfony/symfony/blob/v3.3.2/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php#L58

Not sure how to fix it yet :) fix is welcome.

Status: reviewed
