### ISSUE TITLE
[DX][WebProfiler] Exit impersonnation link

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#23094]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x.x

It would be great to have a link to exit impersonnation in the debug toolbar the same way we have a logout link:

![debug](https://user-images.githubusercontent.com/2178680/26884255-9e580224-4b9f-11e7-8227-7e79bc1e3cad.png)

This would be especially usefull when ending up on an exception page where there is no way to customize the template to display an exit link.

**Comment by yceruto** [comment]
There is a PR in progress for that, see https://github.com/symfony/symfony/pull/23026

**Comment by Vinorcola** [comment]
@yceruto Oh! Great!
Issue can be close then I guess!

**Comment by stof** [comment]
issue will be closed when merging the PR then 😄
