### ISSUE TITLE
[Routing] Ability to exclude a route from matcher

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#23093]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | N/A

In an application I must build URL to another host. The host is environment-dependent and the path contains a parameter so I thought of using the router. It works great but my only concern is that the route will be in the UrlMatcher whereas it will never match. Would it be possible to add an option specifying whether a route can be matched or not?

**Comment by sstok** [comment]
Unless you have route patterns that overlap (`news/{title}` with `title=".+"`, which also matches `news/1/edit`) this shouldn't be a problem as `/news/{id}/edit` doesn't match `/news/100`, all routes are matched in full and unless you your requirement is "greedy" (matches beyond the `/` delimiter) you wont have this problem.

But do note that you control the requirement (a regex) and you can use a [negative look-ahead](http://www.regular-expressions.info/lookaround.html) to prevent matching, it's only a bit tricky to get this right as you only want to prevent conflicts while still allowing other matches.

You can have a look at https://github.com/rollerworks/app-sectioning-bundle which helps with separating the application into back-end/frontend sections. It's in alpha state but maybe some of it's logic can help you :)

**Comment by MatTheCat** [comment]
I think you misunderstood: host is different so the route will *never* match. But the matcher will check for it anyway, which is pointless. So I ask for a way to define a route which will not be checked by the matcher.

**Comment by iltar** [comment]
I was thinking about this as well recently. We have a few URLs that are generated to link towards other hosts, but will _never_ get matched. However, there are still rules created to match those routes, which simply can _never_ be matched.

**Comment by MatTheCat** [comment]
Could we just filter `$this->getRoutes()` on a route option [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php#L101)?

**Comment by fabpot** [comment]
What would be the benefit of being able to exclude those routes. It they cannot match, it's just extra information that does not hurt.

**Comment by iltar** [comment]
@fabpot they actually _can_ match, but aren't ever matched as long as the application routing is matched first. Example:

```php
// somewhere above
if (...) {
    // ...
    // app.authentication.login
    if ('/login' === $trimmedPathinfo) {
        $ret = array (  '_controller' => 'Hostnet\\App\\Controller\\Authentication\\LoginController::loginAction',  '_route' => 'app.authentication.login',);
        if (substr($pathinfo, -1) !== '/') {
            return array_replace($ret, $this->redirect($rawPathinfo.'/', 'app.authentication.login'));
        }

        return $ret;
    }
    // ...
}

// some more routes

if (preg_match('#^cp\\.(?P<environment_url>([a-z]+\\.)?domain.nl)$#si', $host, $hostMatches)) {
    // ...
    // frontend_routing.cp.login_page
    if ('/login' === $trimmedPathinfo) {
        $ret = $this->mergeDefaults(array_replace($hostMatches, array('_route' => 'frontend_routing.cp.login_page')), array ());
        if (substr($pathinfo, -1) !== '/') {
            return array_replace($ret, $this->redirect($rawPathinfo.'/', 'frontend_routing.cp.login_page'));
        }

        return $ret;
    }
    // ...
}
```

This has some side effects that I rather see impossible:
 - If the order changes for whatever reason, things break, because in this application the host regex will match (shared bundle defining all cross-linking routes between apps).
 - As it can never be matched, it's only extra overhead in the matching for this host + unmatched routes, especially if you have fallback routes

**Comment by fabpot** [comment]
Is it reasonable to say that the "overhead" is not something we need to worry about? If yes, I would close this issue.

**Comment by nicolas-grekas** [comment]
The overhead is negligible IMHO, the router handles any size of route collections in constant time. I wouldn't care for this aspect.

**Comment by iltar** [comment]
Fair enough, especially after your recent additions!

What about the matching order though? Right now it's more of a "I found out we had this and luckily it didn't break", but it could be causing issues in the future. A test case that prevents this from happening would be enough to satisfy me to be honest.

**Comment by Tobion** [comment]
If the host has a requirement that cannot match, then the route will never match. It does not matter if it's first or last in that regard.

**Comment by iltar** [comment]
@Tobion except that it _will_ match in my scenario as the host requirement is matching

**Comment by Tobion** [comment]
I don't get what you are asking for. Routes are matched in order and we have lots of tests for this.

**Comment by nicolas-grekas** [comment]
Since the generator doesn't care about the verb and the condition, we could easily add a special verb or condition that the matcher-dumper could use to skip generating code for those.
Could be e.g. `methods: generate` or `condition: false`
PR welcome  suppose is any of you want to make it happen.
