### ISSUE TITLE
[Routing] 

### ISSUE THREAD

**Issue by Gribnif** [symfony/symfony#23109]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=3.3

[#1c5a24](https://github.com/symfony/routing/commit/1c5a2444ae0cd2cdd1a60829c428dbfa948ddb4d) introduced a strict check on unserialize() within Route.php, which is good for security. However, it causes a failure if the compiled route's class is anything other than CompiledRoute. This is the case in Drupal, where the serialized object of a route requires \Drupal\Core\Routing\CompiledRoute.

Might I suggest adding the ability to set the list of allowed classes somehow?

**Comment by Tobion** [comment]
#21090 should be reverted for the Route class as it breaks BC. Being able to change the compilation by overwriting the compiler class is a supported use-case. But the new check prevents that.

**Comment by fabpot** [comment]
@Gribnif Can you submit a pull request?

**Comment by stof** [comment]
There is a second place where it was added but should not. I commented on the PR

**Comment by Gribnif** [comment]
I have created a PR for the Routing portion of the issue. I feel that the FormError.php portion should be done by someone else in a separate PR, since reverting it can have different effects.

**Comment by stof** [comment]
which different effect ? Removing the allowed_class will give us back the 3.2 behavior: allowing any object there, which is something we need
