### ISSUE TITLE
EmailValidator not checking blank character

### ISSUE THREAD

**Issue by guidoheckmann** [symfony/symfony#23104]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.20

File
 symfony/src/Symfony/Component/Validator/Constraints/EmailValidator.php
does not check the incoming value for blank characters in its local part.

**Comment by stof** [comment]
Are you using it in strict mode or no ? In non-strict mode, it only performs a very basic validation (which will indeed not reject this kind of invalid emails, as well as many others).

**Comment by guidoheckmann** [comment]
No, I am not using it in strict mode. Thanks for your fast reply.
In my eyes blank character should be basic ;-)

**Comment by stof** [comment]
@guidoheckmann when I mean basic, I mean "very basic": a string with a `@` and something before and after. that's all.
Proper email validation is very complex, and this is what strict mode does, but it requires an extra dependency (we rely on a library dedicated to it)
