### ISSUE TITLE
[Profiler] MasterRequest not saved in profile list

### ISSUE THREAD

**Issue by mar1be** [symfony/symfony#23115]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.2

The profile of a master request is not saved when it has sub requests. I have to set the only_master_requests parameters to true to resvole this issue.

**Comment by trearcul** [comment]
I've encountered this bug too, but it has been already in v3.3.1.

Master requests imho are not saved because iterator index of `ProfilerListener.profiles` property is changed to point to the last item during it's first iteration in `ProfilerListener.onKernelTerminate()`, when calling `Profiler.saveProfile()`. So, when you have more requests in the `profiles` property, only the first request is saved.

I've also found out that calling `VarCloner.cloneVar()` in `SecurityDataCollector.lateCollect()` is somehow responsible for the index change.

I hope it will helps with fixing the bug.

**Comment by Majkl578** [comment]
While debugging this, we bisected this bug to commit c17a009d666007150b9fdeba61521d0760cf4ab6 (`[EventDispatcher] Handle laziness internally instead of relying on Cl… `).

**Comment by nicolas-grekas** [comment]
Could any of you provide a reproducer please? eg a patched standard edition to reproduce the issue?
Also, which version og PHP are you using?

**Comment by timdierolf** [comment]
I can confirm @trearcul 's description. It has to do with the method ```SecurityDataCollector::lateCollect()```. Somehow the ```cloneVar()``` call is responsible for the ```ProfilerListener::$profiles``` not to be looped completely and thus not all profiles are saved.

Unfortunately, I can't provide a reproducer (yet). I can only describe the circumstances it occurs in my project:

- I use a simple controller action rendering a twig template.
- In this template I call another controller action. e.g. ```{{ render(controller('my_controller:subAction')) ```.
- For authentication I use a ```PostAuthenticationGuardToken```.
- For authorization I use ```- { path: ^/, roles: ROLE_USER }``` in the ```access_control``` config.

Now, if I remove this line from ```access_control``` everything works just fine! 

So I could trace it down to ```SecurityDataCollector::lateCollect()``` where I debugged the ```SecurityDataCollector::$data``` array. The only difference between the ```access_control``` entry present and not present (not working and working) is the array item ```access_decision_log```. 

In the working version without authorization it's empty: 
```
'access_decision_log' => 
    array (size=0)
      empty
```

And that's the item in the broken version with the authorization enabled:
```
'access_decision_log' => 
    array (size=1)
      0 => 
        array (size=3)
          'attributes' => 
            array (size=1)
              ...
          'object' => 
            object(Symfony\Component\HttpFoundation\Request)[36]
              ...
          'result' => boolean true
```

I use PHP 7.0.18-0ubuntu0.17.04.1.

Hope this helps.

**Comment by nicolas-grekas** [comment]
Would you mind trying this patch?
```diff
--- a/src/Symfony/Component/VarDumper/Caster/SplCaster.php
+++ b/src/Symfony/Component/VarDumper/Caster/SplCaster.php
@@ -184,7 +184,7 @@ class SplCaster
         $storage = array();
         unset($a[Caster::PREFIX_DYNAMIC."\0gcdata"]); // Don't hit https://bugs.php.net/65967
 
-        foreach ($c as $obj) {
+        foreach (clone $c as $obj) {
             $storage[spl_object_hash($obj)] = array(
                 'object' => $obj,
                 'info' => $c->getInfo(),
```

**Comment by timdierolf** [comment]
@nicolas-grekas Yes, the patch fixed it. :+1:

**Comment by mar1be** [comment]
Hello,

I upgrade my project to Symfony 3.3.4 and I still have the issue.

**Comment by samdjstevens** [comment]
I too am experiencing this issue - weirdly it only happens when the sub request controller has a property on it that references a "large-ish" (a few dependencies) object - if I change this reference to be a much smaller/simpler object, the master profile saves fine.

**Comment by martijnhartlief** [comment]
In 3.3.1 and higher, on one of our pages, it takes about 3 seconds to render including 3 sub-request. Afterwards the javascript does 5 attempts to access the webtoolbar, it concludes there is no profiler.

If I manually refresh the _profiler/_wdt url. it will give another 404 **but** the second reload will show the profiler, after about 25 seconds. According to the profiler the request took 24 seconds, where the profiler took around 21 seconds.

So for some reason it looks like the original request just exits before generating the profiler, thus resulting in a 3 second load time and no profiler data is generated. But if you keep refreshing the url that should have been created, it seems to do another request that includes the 3 second original load and the profiler load time.
