### ISSUE TITLE
Bug: Problem with same resource ID's for array of entities

### ISSUE THREAD

**Issue by MicWit** [symfony/symfony#23113]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

I am trying to create an array of timeslots as entities that use DateTime for the start and end. I have a while loop to increase at a half hour interval. The issue I am having is that it seems the same resource is allocated for every start and end time in every entity in the array, so they are all showing the same time! Note: this does NOT happen when I import data from JMS serializer (http://jmsyst.com/libs/serializer), only when I get PHP to do a while loop.

To replicate, do the following:
Set up a symfony app and set all permissions so you can see the app_dev.php page.
Copy the following code into the following code into src/AppBundle/Controller/DefaultController.php:
```
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Entity\Timeslot;
use AppBundle\Entity\Timeslots;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        // create entity to hold timeslots
        $timeslots = new Timeslots();

        // create start and end times as now 
        $curr_time = new \DateTime("NOW");
        $end_time = new \DateTime("NOW");

        // update start and end times to be correct, 8am - 10am
        $curr_time->setTime(8,00);
        $end_time->setTime(10,00);

        // loop through and add a timeslot for each half hour
        while ($curr_time < $end_time) {
            $timeslot = new Timeslot(); //new timeslot with no start or end
            $timeslot->start = $curr_time; //add the start time (same as last end time)
            $curr_time->add(new \DateInterval('PT30M')); //add half an hr
            $timeslot->end = $curr_time; //add the end time, half an hour later
            array_push($timeslots->timeslots, $timeslot); //add this newly created timeslot to the array
        }

        dump($timeslots); //this should show half hour timeslots, but it all has the one time

        // return blank page to test using dump()
        return new Response('<body><head></head><body></body></html>');
    }
}
```
Create the following files in src/AppBundle/Entity/:
Timeslot.php (A single timeslot):
```
<?php

namespace AppBundle\Entity;

class Timeslot
{

    /**
     * Start time
     */
    public $start;

    /**
     * End time
     */
    public $end;

}
```
Timeslots.php (To hold an array of timeslots):
```
<?php

namespace AppBundle\Entity;

class Timeslots
{

    /**
     * Array to store the timeslots
     */
    public $timeslots;

    /**
     * Set up the timeslots as an empty array so we can add to it when required
     */
    public function __construct() {
        $this->timeslots = array();
    }

}
```
Now when you go to app_dev.php, notice that the list of timeslots that have been dumped all have the same time for both start and end and all have the same resource ID?
The PHP is working fine, try dump $curr_time in different spots in the while statement and you will see it is changing as expected.
The final outcome is that they all have the same time as what should be in the "end" in the last timeslot entity to be created. I believe that the same instance is used and is being overwritten every time so effectively the last time one is modified they are all modified.

**Comment by fancyweb** [comment]
`$curr_time` is a `\DateTime` object which means all your `TimeSlot` objects share the same reference to this object in their `start` and `end` properties. This is unrelated to Symfony.

**Comment by MicWit** [comment]
Ok, I figured it would put the value of the object (or another instance of the object) as the new value for start. If I was to create $object->property = "value" abd then do $object2->property2 = $object->property,  I could then say $object->property = "new value" and $object2->property2 would still be "value".

So by what your saying is Im passing something more like $object in rather than the value of the object?

So, would doing something more like $timeslot->start = new \DateTime($curr_time) to pass the value in as a new object? 

Ive left work and am replying from my phone, but next week when im back will experiment. I'm guessing the new DateTime will want a string as well.

**Comment by fancyweb** [comment]
In your first example it would effectively work because "value" and "new value" are strings and strings are passed by copy in PHP.

But `\DateTime` are objects, so they are passed by reference which kinda means you don't pass the value of the object but its instance. So you need to create a new \DateTime instance for every property  as you suggested.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
