### ISSUE TITLE
"Unable to find template ..." error message when using bundle-specific templates

### ISSUE THREAD

**Issue by DeValk** [symfony/symfony#23137]
Hello,

In Symfony 3.3, when trying to use a template developed for my custom bundle, receiving the error:
'Unable to find template "MyUsrBundle:Registration:register.html.twig" (looked into: /srv/www/vhosts/s1/app/Resources/views, /srv/www/vhosts/s1/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).'

The full path to the template was 'app/Resources/Views/MyUsrBundle/Registration/register.html.twig'.
In the controller it was referred to as following.

`return $this->render(
            'MyUsrBundle:Registration:register.html.twig',
            array('form' => $form->createView())
        );`

I also tried putting it to 'app/My/UsrBundle/Resources/Views/Registration/register.html.twig', got the same error.

There were a few issues reported in this regard earlier (the most recent #18522) , and I tried all options suggested in replies, but nothing really worked. Was I missing something?

Thank you,

Val

**Comment by xabbuh** [comment]
Do you have TwigBundle installed and enabled?

**Comment by yceruto** [comment]
> The full path to the template was 'app/Resources/Views/MyUsrBundle/Registration/register.html.twig'.
In the controller it was referred to as following.

> I also tried putting it to 'app/My/UsrBundle/Resources/Views/Registration/register.html.twig', got the same error.

This should be a typo, look at the `Views` directory, this one should be `views` instead (lowercase), please check out.

**Comment by DeValk** [comment]
Thank you @xabbuh, @yceruto,
Yes, TwigBundle was installed and enabled. 
And yes, the path was with the 'views' beginning with a lowercase.
When I moved the template file to 'app/Resources/views/register.html.twig', it worked well. So it seemed as if the system didn't want to look in other directories, like 'app/Resources/Views/MyUsrBundle/Registration/register.html.twig'.

Was there any way to tell the system to check that directory?

Thank you,

**Comment by stof** [comment]
@DeValk the global directory to overwrite bundle-specific templates (accessible through the `MyUsrBundle:Registration:register.html.twig` syntax) is `app/Resources/MyUsrBundle/views`, not `app/Resources/views/MyUsrBundle` (which will just reference bundle-less templates in a folder named `MyUsrBundle`)

**Comment by stof** [comment]
Btw, using the `Bundle:folder:file` notation requires enabling the templating component in the project.

**Comment by Hanmac** [comment]
if its your own bundle, shouldnt the template be in:
`src/MyUsrBundle/Resources/views/Registration/register.html.twig`
?

**Comment by DeValk** [comment]
Thank you @stof and everyone, 
It worked when I moved my bundle-specific template to 
`app/Resources/MyUsrBundle/views/Registration/register.html.twig` and in my controller referred to it as 
`MyUsrBundle:Registration:register.html.twig`.

In case this may be helpful for someone else.

Val

**Comment by stephane-wis** [comment]
in "app/config/config.yml" be sure to have this:
framework:
    # ...
    templating:
        engines: ['twig']

**Comment by realthk** [comment]
@stephane-wis thanks, that was missing from my freshly installed Symfony 3.4.9

**Comment by Arouna31** [comment]
thanks @stephane-wis

**Comment by skandertrifa** [comment]
> in "app/config/config.yml" be sure to have this:
> framework:
> # ...
> templating:
> engines: ['twig']

love you men ♥
