### ISSUE TITLE
[Debug] Separate visually errors from vendor and from application

### ISSUE THREAD

**Issue by rentalhost** [symfony/symfony#23144]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2 (last)

Should be great if on debug a stacktrace (like on the "whoops" page) we have a visual difference between the "vendor code" and the "application code". It can help find out "where my problem starts".

The `ReflectionClass()` should help to tell where file is located, then just check if it is from "vendor" folder to mark as "white background" else "yellow background" to indicate an "user-zone file".

**Example:**

![image](https://user-images.githubusercontent.com/421851/27035678-946365ee-4f58-11e7-8464-a0d2963a93d7.png)

**Comment by fabpot** [comment]
That's a great idea!

**Comment by rentalhost** [comment]
Fixed on PR #23152.

**Comment by xabbuh** [comment]
reopening here (will be when the PR is merged, but this way we don't lose track in case the PR gets closed for some reason)
