### ISSUE TITLE
[Routing] Dumper use compile time values for runtime defined parameters ('%env(VAL)%')

### ISSUE THREAD

**Issue by VolCh** [symfony/symfony#23140]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.0+

With config
```yaml
parameters:
    domain: '%env(DOMAIN)%'
    env(DOMAIN): localhost
```
and route 
```php
    /**
     * @Route(
     *     "/",
     *     name="mobile_homepage",
     *     host="m.{domain}",
     *     defaults={"domain"="%domain%"},
     *     requirements={"domain"="%domain%"}
     * )
     */
    public function mobileHomepageAction()
    {
        // ...
    }
```
Router dump the  value of DOMAIN environment variable ( ('localhost' if undefined) of dump process (console cache:warmup) instead of use container getParameter (which use getenv('DOMAIN')) in runtime.

I think this is unexpected behavior according http://symfony.com/doc/current/configuration/external_parameters.html :
> You can reference environment variables by using special parameters named after the variables you want to use enclosed between env(). Their actual values will be resolved at runtime (once per request), so that dumped containers can be reconfigured dynamically even after being compiled.

I'll try to create fix PR if this bug report is confirmed.

**Comment by stof** [comment]
Well, the router cannot use the container at runtime anyway (the router is dumped into static code which does not have access to the container).
So we should forbid using parameters relying on runtime env variables in route requirements.
/cc @nicolas-grekas

**Comment by VolCh** [comment]
@stof can we inject container in dumped urlGenerator/Matcher? If we can't we can hardcode this case and generate something like 
```
$defaults['domain'] = getenv('DOMAIN') ?: 'localhost';
```
during dump pass in case defaults={"domain"="%env(DOMAIN)%"}

**Comment by stof** [comment]
@VolCh the routing component has no knowledge of DI parameters are all. Requirements and defaults are just string there.
The support of DI parameters in FrameworkBundle is actually quite hacky already, as it hooks into the route loading process to resolve parameter it finds. But it cannot impact the dumped router.
Btw, your proposed dumped code is *not* equivalent to the resolution of `%env(DOMAIN)%` in the container (well, it would require making the dumper aware of the compiler pass fallback instead).

**Comment by javiereguiluz** [comment]
I think we should detect if an env var is used in any route requirement and then throw an exception.

**Comment by nicolas-grekas** [comment]
There is no (simple) way to do this, routes and DI are decoupled, and coupling them is complexity we'd better not add. Throwing is also not (easily) possible, and would prevent legit use cases btw / break BC.
I'd recommend to close as won't fix.
You should deal with this in your controller instead
