### ISSUE TITLE
[Console] Provide setter methods for Question text and default value

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#23147]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 3.x

So far constructor is the only way to set these properties. It is a bit [tricky](https://github.com/Chi-teck/drupal-code-generator/blob/66de5db0e6177171c5e3791e7f4a0a43bd047145/src/Helper/InputHandler.php#L101) to set them even in extended class because they have private scope. All other class members has both setter and getter methods.

**Comment by chalasr** [comment]
What is the use case for changing these values after construction?

**Comment by Chi-teck** [comment]
I have a few dozens commands and a single Input handler that is responsible for preprocessing questions before passing them to Question helper. For instance, default value can be callable that takes answers of previously asked questions as a parameter. I need to [invoke](https://github.com/Chi-teck/drupal-code-generator/blob/66de5db0e6177171c5e3791e7f4a0a43bd047145/src/Helper/InputHandler.php#L92) the callable and put the result back to question object. Another case it [formatting](https://github.com/Chi-teck/drupal-code-generator/blob/66de5db0e6177171c5e3791e7f4a0a43bd047145/src/Helper/InputHandler.php#L125) question text.

**Comment by chalasr** [comment]
Wouldn't it be possible to create a new Question instance instead of altering the existing one?

**Comment by Chi-teck** [comment]
It would be too verbose. The questions can have configured some other properties that should be preserved (validator, normalizer, autocompleter values).

**Comment by chalasr** [comment]
Closing as it does not seem worth it as mentioned in the proposed PR.
