### ISSUE TITLE
Groups option missing in the UniqueEntity constraint documentation

### ISSUE THREAD

**Issue by rtarnaud** [symfony/symfony#23158]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no ????
| Symfony version  | 3.4.0

I noticed that the UniqueEntity constraint (form validation) accepts the "groups" option like other common validation constraints. However, this option does not appear in the documentation: https://symfony.com/doc/3.4/reference/constraints/UniqueEntity.html
Very minor thing but I just wanted to let the community know.

**Comment by xabbuh** [comment]
Thank you for reporting this @rtarnaud. However, since we have its own repository for the documentation I have moved the issue there (see symfony/symfony-docs#8036).
