### ISSUE TITLE
[WebProfiler] Profiler bar broken in IE 11

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#23159]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

The profiler bar looks a bit broken on Internet Explorer 11. This is a screenshot with a fresh symfony-standard application. As you can see, some of the widgets are placed on top of each other.

![sf-profiler-bar-ie11](https://user-images.githubusercontent.com/1506493/27076958-e5b28796-502e-11e7-942c-bfa3beba4a7a.PNG)

As a reference, the same view with Symfony 3.2. Here, everything's fine.

![sf-3 2-profiler-bar-ie11](https://user-images.githubusercontent.com/1506493/27077340-05668d8e-5030-11e7-98bc-8e24f8ebdae0.PNG)

**Comment by javiereguiluz** [comment]
@derrabus thanks for reporting this. However, I'm afraid that I must close this as won't fix. We're using more and more advanced CSS/JS features on Symfony pages (profiler, the new exception pages, etc.). We know that some browsers don't render those pages nicely but our reasoning is:

* End-users can use any browser they want ...
* ... but developers must use modern browsers to use Symfony's debugging tools

There shouldn't be any reason to use our debug tools in IE11 (except, maybe, the Ajax panel, which may be different depending on what the browser does) ... but the rest of panels should be the same on any browser.

**Comment by stof** [comment]
@javiereguiluz this is just the cache.svg icon missing the width and height attributes, that we added in other icons to display them properly in IE. I suggest we fix this icon

**Comment by javiereguiluz** [comment]
OK ... let's fix that icon ... but the rest of features won't work (we use flex for example and its support is very buggy on IE11).

**Comment by stof** [comment]
@javiereguiluz we don't use flex in the toolbar. We use it in the profiler page, but the profiler already requires modern browsers since ages. The toolbar is a bit different as it is injected inside your own page (and having a broken display there could make it harder for the dev to debug other rendering issues in their page)

**Comment by derrabus** [comment]
Right. I'm totally fine with using a real browser when viewing profiles collected with IE.

**Comment by javiereguiluz** [comment]
@derrabus about your last comment, I consider IE a real browser too (and Symfony project does too). It's true that it's not as modern as others (Edge, for example) but we respect it as we do with any other project. Thanks!

**Comment by derrabus** [comment]
@javiereguiluz I'm sorry if my comment sounded disrespectful. I didn't mean it that way. I've changed my comment.

**Comment by LeonidasJP** [comment]
I spotted this issue in v2.8.41 as well; adding
```css
.sf-toolbar-block .sf-toolbar-icon img, .sf-toolbar-block .sf-toolbar-icon svg {
    width:24px;
}
```
to my CSS fixed the problem for me. It seems IE11 is not handling the `width` and `height`-attributes set on the `<svg>` node...
