### ISSUE TITLE
error while updating to a new version of symfony

### ISSUE THREAD

**Issue by karimennassiri** [symfony/symfony#23150]
I'm trying to update my Symfony version from 2.8 to 3.2 via composer. composer instal all the libraries and when we arrive to clear cache I'm getting this error :

`Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception                                                                                                                                    
[RuntimeException]                                                                                                                   
An error occurred when executing the "'cache:clear --no-warmup'" command:                                                            
PHP Fatal error:  Class 'Symfony\Component\HttpKernel\Kernel' not found in /home/web/project/path/app/AppKernel.php on line 11  
PHP Stack trace:                                                                                                                     
PHP   1. {main}() /home/web/gestionnaire/path/app/console:0                                                                          
PHP   2. require_once() /home/web/gestionnaire/path/app/console:11`

I've tried to delete cache manually, but it not working and the class it's present in the project.

**Comment by stof** [comment]
I think you changed the major version of SensioDistributionBundle too, not only the Symfony version. And so, you need to update your project based on changes we made in the bundle (the bootstrap.php.cache does not require the composer autoloader for you anymore): https://github.com/sensiolabs/SensioDistributionBundle/blob/master/UPGRADE.md

**Comment by karimennassiri** [comment]
I've tried to follow this upgrade instructions that reveal some new errors like this one. `with message 'The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "arguments: [@service_container]").'`

**Comment by shahroznawaz** [comment]
Hi you first need to upgrade symfony to 3.0. the directory structure will also be changes. I have written a guide on it : https://www.cloudways.com/blog/upgrade-symfony-2-to-3/ 

After upgrading to symfony 3.0 you can easily upgrade tw 3.2 by replacing version in composer.json file. Also there are some deprications you need to see for symfony 3.2.Let me know if it works.

**Comment by xabbuh** [comment]
@karimennassiri Are you still experiencing any issues? Did it help to follow the upgrade guide of the SensioDistributionBundle?

**Comment by karimennassiri** [comment]
@xabbuh I still work on it. I've started the @stof solution, there's some good evolution but i still need to do some refactoring of the old code

**Comment by javiereguiluz** [comment]
Let's close this because it's probably fixed and it doesn't look like a Symfony bug but an upgrade issue. Thanks!
