### ISSUE TITLE
[Config] ClassExistenceResource::isFresh states that some cached resources are stale

### ISSUE THREAD

**Issue by nelsonkopliku** [symfony/symfony#23165]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | maybe
| RFC?             | no
| Symfony version  | 3.3.2

When updating from symfony 3.2.9 to symfony 3.3.2 we noticed that all our functional tests had incredibly slowed down due to a regeneration of cache on every test.

What we noticed is that the method ClassExistenceResource::isFresh returns false for Proxied EntityManager (e.g. EntityManager593ff38a09f85_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager)

Is this a bug? or are we misconfiguring something?

Note that we simply upgraded symfony and if we rollback to 3.2.9 the problem disappears.

**Comment by nicolas-grekas** [comment]
Change tracking has changed in 3.3 so this might be a bug.
Would you be able to provide us a reproducer, eg a patched standard edition?

**Comment by stof** [comment]
@nicolas-grekas I think this is related to the fact that this class is a generated proxy class. The question there is how would a proxy class gets registered in a ClassExistenceResource

**Comment by stof** [comment]
@nelsonkopliku are you using JMSDIExtraBundle ? AFAIK, Symfony's lazy services don't trigger this kind of resource check, but JMSDIExtraBundle also performs some proxy-based magic, and this may be happen early enough in the container building process to trigger some later check on the existence of the class (and if the proxy class is generated on demand, the existence resource could go wunky as the proxy class may not be autoloadable)

**Comment by nicolas-grekas** [comment]
@nelsonkopliku I agree with @stof, the question is why is a ClassExistenceResource used at all to track proxies?

**Comment by xabbuh** [comment]
@nelsonkopliku Do you have some news for us? :)

**Comment by nicolas-grekas** [comment]
Closing, please reopen if you manage to reproduce the issue.

**Comment by nelsonkopliku** [comment]
@nicolas-grekas @stof I removed JMSDIExtraBundle and the issue disappeared with the bundle

**Comment by FabienPapet** [comment]
We have migrated from 2.8 to 3.4 and faced the same problem. As we couldn't remove JMSDiExtra of our application, our solution was to run tests with debug `false`.

**Comment by nazar256** [comment]
> @nelsonkopliku are you using JMSDIExtraBundle ? AFAIK, Symfony's lazy services don't trigger this kind of resource check, but JMSDIExtraBundle also performs some proxy-based magic, and this may be happen early enough in the container building process to trigger some later check on the existence of the class (and if the proxy class is generated on demand, the existence resource could go wunky as the proxy class may not be autoloadable)

This really helped. This made me to find several solutions:
- as proposed earlier - do not use jms/di-extra-bundle or any bundle depending on it (like jms/security-extra-bundle in our case)
- do not use autowire (actually I would encourage to use autowire and choose another way)
- do not run tests (and probably symfony under PPM/RoadRunner) with enabled "debug" flag, like in a production environment build cache manually and then run tests
- disable di-extra-bundle [integration with doctrine](https://www.jmsyst.com/bundles/JMSDiExtraBundle/master/doctrine)

The last one may appear the easiest option if you didn't use di-extra-bundle for doctrine explicitly. Or even if you did - try using autowire instead for all doctrine-relevant services.

I hope this saves time for you.
