### ISSUE TITLE
[FrameworkBundle] assets:install does not clean unnecessary bundle folders

### ISSUE THREAD

**Issue by stof** [symfony/symfony#23177]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

If you installed assets previously, and then a bundle removed its `Resources/public` (or you removed the bundle entirely), the corresponding bundle folder in `web/bundles` is not cleaned when running `assets:install` again.
Getting a clean `web/bundles` folder requires deleting the folder and running the install again.

Note that you even end up with broken symlinks in `web/bundles` in case assets were symlinked rather than copied.

Originally reported as https://github.com/symfony/flex/issues/22 for a case impacting the removal of a bundle.
See https://github.com/symfony/symfony-demo/pull/588 for such a case about removing public assets from existing bundles too (we missed at least 2 removals in the history, as the `sensiodistribution` folder was unused since before the demo switched to symlinks, while `framework` was after).

**Comment by GaryPEGEOT** [comment]
I take it

**Comment by NicolasPion** [comment]
> If you installed assets previously, and then a bundle removed its Resources/public (or you removed the bundle entirely), the corresponding bundle folder in web/bundles is not cleaned when running assets:install again.

@GaryPEGEOT I think we need to check for each existing folder If the Bundle still exists

Something like : https://github.com/symfony/symfony/pull/23190
