### ISSUE TITLE
[Security] Symfony does not redirect xhr to target path after login.

### ISSUE THREAD

**Issue by langj** [symfony/symfony#23182]
| Q                | A
| ---------------- | -----
| Bug report?         | yes
| Feature request? | no
| BC Break report? | no
| RFC?                    | no
| Symfony version  | 2.8

The Firewall/ExceptionListener does not set the target path for xhr. This was introduced in 9ee74ea (long ago).

I would like to do authentication via xhr. Is there any reason against reverting this?
I dont see any reason for the current behavior, especially because symfony still intercepts and redirects xhr. Only the target path is ommited, and the redirect after login falls back to the default path.

Or may be it could be made configurable.

**Comment by dmaicher** [comment]
Seems it fixed some issues where users were redirected to xhr urls? https://github.com/symfony/symfony/pull/14593

**Comment by fabpot** [comment]
It was done that way to avoid being redirected to a XHR URL, which would look weird in a browser. You can always be explicit about your target URL, so I'm closing this one.
