### ISSUE TITLE
[PHPUnitBridge] Issue with @runInSeparateProcess

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#23189]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.2

I noticed there is an issue when running tests with the bridge (vendor/bin/simple-phpunit). When a test is annotate with @runInSeparateProcess the whole test suite is run.

For example if I run, the whole test suite is executed:
```
php /usr/local/bin/phpunit.phar src/.../Tests/Controller/MyTest.php --filter="testFoo"
```
```php
/**
 * @runInSeparateProcess
 */
public function testFoo() {}
```

It's not the case when I remove @runInSeparateProcess or if I run phpunit without the bridge (but it's not supported with Symfony 3.3.2).

**Comment by xabbuh** [comment]
Related to #23003?

**Comment by nicolas-grekas** [comment]
Closing as duplicate yep.
