### ISSUE TITLE
Using ArrayCollection with ChoiceType: fails and expects array instead

### ISSUE THREAD

**Issue by BenoitDuffez** [symfony/symfony#23192]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.2

I don't know what FC and RFC mean so I did not answer.

I followed the [guide here](http://symfony.com/doc/current/form/dynamic_form_modification.html#form-events-submitted-data). I have an entity like this:

```php
/**
 * Invoice
 *
 * @ORM\Table(name="invoice")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\InvoiceRepository")
 */
class Invoice
{

...

    /**
     * @var ArrayCollection
     * 
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Section", inversedBy="invoices", cascade={"persist"})
     * @ORM\JoinTable(name="invoice_section", joinColumns={@ORM\JoinColumn(name="invoice_id", referencedColumnName="id")},
     *   inverseJoinColumns={@ORM\JoinColumn(name="section_id", referencedColumnName="id")})     */
    private $sections;
                                                                                
    public function __construct() {
        $this->sections = new ArrayCollection();
    }

...
                                                                                                            
    /**
     * Get sections                                    
     *
     * @return \Doctrine\Common\Collections\Collection 
     */                                                
    public function getSections()                      
    {
        return $this->sections;
    }                                                  
```

In `InvoiceType` (form builder for this entity), the following works well:

```php
$builder->add('sections', ChoiceType::class);
```
But this is not the intended behavior. What I want is that the user selects another field first (of type `Quote` below), which will return a list of sections. I have hence followed the guide linked earlier and here's what I have implemented:

```php
$formModifier = function (FormInterface $form, Quote $quote = null) {
	$sections = null === $quote ? array() : $quote->getSections();
	$form->add('sections', ChoiceType::class, array(
		'multiple'    => true,
		'expanded' 	  => true,
		'choices'     => $sections,
        'choice_attr' => function($section, $key, $index) {
            /* @var Section $section */
            return [
                'disabled' => $section->isOption() ? false : 'disabled',
                'checked' => $section->isOption() ? false : 'checked',
            ];
        },
        'choice_label' => function($section, $key, $index) {
            /* @var Section $section */
            return $section->getTitle();
        },
	));
};

$builder->addEventListener(
	FormEvents::PRE_SET_DATA,
	function (FormEvent $event) use ($formModifier) {
		$data = $event->getData();
		$formModifier($event->getForm(), $data->getQuote());
	}
);

$builder->get('quote')->addEventListener(
	FormEvents::POST_SUBMIT,
	function (FormEvent $event) use ($formModifier) {
		$quote = $event->getForm()->getData();
		$formModifier($event->getForm()->getParent(), $quote);
	}
);
```

This yields the following (before even submitting):

> Unable to transform value for property path "sections": Expected an array.

If I change the accessor in the entity (`Invoice`, not `Quote`!), e.g. add `->toArray()` it works like a charm:

```php
/**
 * Get sections
 *
 * @return \Doctrine\Common\Collections\Collection
 */
public function getSections()
{
    return $this->sections->toArray();
}
```

I was hoping for Symfony to support `ArrayCollection` out of the box without converting them to `array`.

**Comment by stof** [comment]
`RFC` means `Request For Comments`. It describes issues which are about describing details of a new feature (generally for complex features). See https://en.wikipedia.org/wiki/Request_for_Comments

`BC` means `Backward Compatibility`. See https://symfony.com/bc

For a Doctrine ArrayCollection, you should use the EntityType rather than the ChoiceType (EntityType is a child type of ChoiceType, so all ChoiceType features are available in it too), or you need to add the `CollectionToArrayTransformer` yourselves, as done by the EntityType already.

**Comment by stof** [comment]
Btw, the guide is using EntityType, so you haven't followed it exactly.

**Comment by BenoitDuffez** [comment]
I have adapted it believing that EntityType didn't inherit from ChoiceType.
Sorry about that.

I will update my code and get back to you. Thanks a lot for your kind support.

**Comment by BenoitDuffez** [comment]
Works like a charm. Should've followed the doc to the letter.

Sorry about that, and thanks for your time. Cheers!
