### ISSUE TITLE
[ContainerAwareCommand] Problem while creating new Command in Symfony 3.3

### ISSUE THREAD

**Issue by engharb** [symfony/symfony#23191]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.3

Dears,
  I have a problem when I create an console Command in symfony 3.3. When I am calling the following lines:

```
$doctrine = $this->getContainer();//->get('doctrine');
$em = $doctrine->getEntityManager();
```
I get exception as
```
Call to undefined method Symfony\Component\Console\Application::getKernel() in /home/vagrant/MyWebsite/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php:43
```

Is there another way to call a doctrine entity/instance, or how to work around this problem.?

Best regards

**Comment by xabbuh** [comment]
Could it be that you use the `Application` class from the Console component instead of the one from FrameworkBundle?

**Comment by engharb** [comment]
Yes i am using:
```
//application.php
use Symfony\Component\Console\Application;
````
because when I am using
```
use Symfony\Bundle\FrameworkBundle\Console\Application;
```
it asks me to pass KernelInterface as application argument
```
new Application();
```
and I was not be able to pass KernelInterface.

Could write me a clear example, that will be very helpful and kind of you.

regards,

**Comment by chalasr** [comment]
The symfony/symfony-standard repo provides such [console application](https://github.com/symfony/symfony-standard/blob/3.3/bin/console).

**Comment by engharb** [comment]
thank you chalasr,

But I still have problem when I 
```
//application.php
.
.
$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);

$application->add(new AppBundle\Command\CreateCategoryCommand());

$application->run($input);
```

I got another exception: 
```
The autoloader expected class "AppBundle\Command\app" to be defined in file "/home/vagrant/GeheimnessWebsite/vendor/composer/../../src/AppBundle/Command/app.php"
```

**Comment by Hanmac** [comment]
@engharb i think your problem is where you did call your code piece inside your code.

that is an example of one of my commands
```php
class TerminalClientCommand extends ContainerAwareCommand
{
    public function __construct() {
        $name = "your:name";
        parent::__construct($name);
        //your code doesn't work in __construct yet
    }
    
    protected function execute(InputInterface $input, OutputInterface $output) {
        //your code should work there
    }
}
```

without writing own Application code, i can call the command by:
`php bin/console your:name`
does work even without any service definition

how is your code different from that?

**Comment by engharb** [comment]
@Hanmac thank you for responding. my problem is : how to call instance of the doctrine entity manager.
These two lines throwing exception
```
$doctrine = $this->getContainer();//->get('doctrine');
$em = $doctrine->getEntityManager();
```

and I don't know exactly how to solve that in symfony 3.3. In symfony 3.2 works but not in Symfony 3.3

I am looking to hear from you soon.

regards,

**Comment by Hanmac** [comment]
@engharb i think i need more of your code to see what is going on.

because something like that does work in my execute function
$this->getContainer()->get('doctrine');

can you try to make a fork of symfony where you can make a testcase where it does fail?

**Comment by chalasr** [comment]
This is not about a bug in symfony, should be discussed on [support platforms](http://symfony.com/support) instead.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
