### ISSUE TITLE
[Console] QuestionHelper does not run validation in non-interactive mode

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#23211]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all since 2.6 (https://github.com/symfony/symfony/commit/336bba2fd816184c2adf9721659b3c6fe36e708d)

When shell runs in non-interactive mode `QuestionHelper` returns the default answer but it is not validated using passed validator (see https://github.com/symfony/symfony/blob/4cde3b9fcb00602eeafb119defb4a65841a93cfc/src/Symfony/Component/Console/Helper/QuestionHelper.php#L52).
I implemented a password question as it is described in documentation: http://symfony.com/doc/current/components/console/helpers/questionhelper.html#validating-a-hidden-response
but in non-interactive console the question returns null which is default answer instead of failing on error that password cannot be empty.

It is confusing because from the outside I got a feeling that the validation will prevent from having an empty answer.

Does it make sense change `QuestionHelper` to run the validation even on default values?

**Comment by sustmi** [comment]
Note: I can make a pull-request if it is desirable.

**Comment by fabpot** [comment]
I don't think this is worth it. It's up to you as a developer to pass a valid default value. It also helps figuring out if the user actually answered the question or if the default value was selected (by allowing `null` for instance when a string is expected). Last, but not least, it would be a BC break.
