### ISSUE TITLE
[Cache][FrameworkBundle] Doesn't possible to use ArrayAdapter in cache.app

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#23214]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

https://github.com/BoShurik/symfony-standard/commit/ab139bc4fb1e0417a894c4627bcbf91667e653e2

`cache.app` service builds as
```php
protected function getCache_App_RecorderInnerService($lazyLoad = true)
{
        return $this->services['cache.app.recorder_inner'] = new \Symfony\Component\Cache\Adapter\ArrayAdapter('09wk9DB47N', false);
}
```
If `0 <'09wk9DB47N'` then we got an exception
```
Notice: A non well formed numeric value encountered
```
here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php#L130

**Comment by iltar** [comment]
This would fix it, but not sure if this is the right approach:
```diff
-$expiry = time() + $item["\0*\0defaultLifetime"];
+$expiry = time() + (int) $item["\0*\0defaultLifetime"];
```

**Comment by BoShurik** [comment]
The problem is in FrameworkBundle
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php#L76

ArrayAdapter constructor signature dose not contains $namespace parameter

**Comment by BoShurik** [comment]
Currently I've used this workaround
```php
use Symfony\Component\Cache\Adapter\ArrayAdapter as BaseArrayAdapter;

class ArrayAdapter extends BaseArrayAdapter
{
    /**
     * @inheritDoc
     */
    public function __construct($namespace = null, $defaultLifetime = 0, $storeSerialized = true)
    {
        parent::__construct($defaultLifetime, $storeSerialized);
    }
}
```

**Comment by chalasr** [comment]
We are blindly replacing arguments of cache adapters, that looks fragile. Dunno how to fix this yet. 
Status: reviewed

**Comment by nicolas-grekas** [comment]
Maybe just add a special case for ArrayAdapter in the compiler pass?

**Comment by xabbuh** [comment]
please try the changes from #23469
