### ISSUE TITLE
[Console] QuestionHelper: add possibility to ask for a value starting or ending with whitespace

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony#23210]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all since v2.6 (https://github.com/symfony/symfony/commit/336bba2fd816184c2adf9721659b3c6fe36e708d)

Currently, `QuestionHelper` trims all answers (see eg. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php#L108 ). Can we add a possibility to ask for a value that starts or ends with whitespace?

The actual usecase is for example asking for a password. We do not want to restrict users to use only passwords that do not start or end with whitespace.
`PasswordType` has this feature by default - see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/PasswordType.php#L38 .

The `QuestionHelper::doAsk()` method is already quite complex but I guess we could add some logic there to check whether `Question` has flag `trimAnswer` set or not.

What do you think?

**Comment by sustmi** [comment]
Note: I can make a pull-request if it is desirable.

**Comment by javiereguiluz** [comment]
This feature request is really tricky. I'm not sure if I'm 👍  or 👎 .

However, for the mentioned use case, I'm strongly 👎 . Using passwords with leading or trailing white spaces is so fragile, that it will "never" work. If that's your use case, keep using the current QuestionHelper *and* remember to trim white spaces if those passwords are set via web too.

**Comment by Nek-** [comment]
@javiereguiluz I disagree with your point on the use case. Just let people do what they want with password and the world will be better :D. (especially when it's "weird")

I don't see the problem with having a configurable option on the `Symfony\Component\Console\Question` class.

**Comment by javiereguiluz** [comment]
@Nek- I disagree with you. Look around and you'll see that no serious web site let users do what they want with their passwords. They require you to use a min/max length, they require you to use certain characters, the password cannot include the login, etc. Yes, some of those rules are stupid ... but most of them are great.

In my opinion, not allowing (or silently ignoring) the leading and trailing white spaces is a good thing to avoid issues.

**Comment by sustmi** [comment]
Ok, I crawled the internet a little bit and I found there already are many discussions on similar topic:
- https://www.drupal.org/node/1921576
- https://stackoverflow.com/questions/7240869/should-i-trim-spaces-in-a-password-field
- https://stackoverflow.com/questions/9937996/trimming-whitespace-from-usernames-and-passwords
- https://ux.stackexchange.com/questions/75686/why-do-some-websites-including-google-trim-whitespaces-in-passwords

I came to a conclusion that we should at least be transparent about the trimming. So I propose mentioning it in the `ask()` comment: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php#L45
For example: `@return mixed The user answer trimmed of whitespace characters`.

What do you think?

**Comment by chalasr** [comment]
We know that spaces in passwords can lead to weird behaviors, but as said the Form PasswordType itself is flexible on that point. 
Pushing to a good practice and mentioning the risks when not following is good thing, even make it default, but forcing to follow is not in my opinion. Nobody forbids you to store passwords in clear for instance, but we strongly recommend to not do so.
Making this opt-in as a feature looks sensible to me, it should be up to the users to trim user inputs or not, providing good defaults of course (required for BC anyway).

**Comment by Simperfit** [comment]
I think we should not implement this too.

**Comment by chalasr** [comment]
PR welcome to add a flag on Question that indicates if the answer should be trimmed or no with default to `true`. Closing due to the lack of activity here.
