### ISSUE TITLE
Symfony 3.3 services autoconfiguration problem

### ISSUE THREAD

**Issue by aLkRicha** [symfony/symfony#23221]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

I'm trying migrate to symfony 3.3 and use new feature `autowire`/`autoconfigure` services:

So in services.yml i have:

    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: false
    
        # makes classes in src/AppBundle available to be used as services
        AppBundle\:
            resource: '../../src/AppBundle/*'
            # you can exclude directories or files
            # but if a service is unused, it's removed anyway
            exclude: '../../src/AppBundle/{Entity,Controller,DQL,Form/DataTransformer,Repository}'

i declare my twig extension as:

    AppBundle\Twig\ImageExtension:
          arguments:
              $env: "%kernel.environment%"

and constructor for this service:

    public function __construct(TokenStorage $token, UserRepository $userRepository, RedisCacheService $cache, string $env)
        {
            $this->env = $env;
            $this->user = $token->getToken() ? $token->getToken()->getUser() : false;
            $this->userRepository = $userRepository;
            $this->cache = $cache;
        }

seems that all is ok, but i'm getting this error:

    (1/1) AutowiringFailedException
    Cannot autowire service "AppBundle\Twig\ImageExtension": argument "$env" of method "__construct()" must have a type-hint or be given a value explicitly.

and have no idea how to fix it.

**Comment by memsb** [comment]
`AppBundle\Twig\ImageExtension:
      public: true
      arguments:
          $env: "%kernel.environment%"`

**Comment by aLkRicha** [comment]
@memsb it doesn't help. 😞

**Comment by GuilhemN** [comment]
Is your service configured in the same config file than the rest of your services? Is it declared after the prototype? 
It looks like the prototype takes precedence over your manual service config.

**Comment by git4me2** [comment]
I think it should work via Extension for each bundle separately.  Right now autowire working only from main service.yml. When I am trying to use service.yml in bundle directory is not working like @aLkRicha  wrote.

**Comment by stof** [comment]
@memsb your comment is wrong. Twig extensions don't need to be public at all (and never needed it).

@git4me2 I do'nt understand your comment. you will need to provide more details.

**Comment by git4me2** [comment]
@stof I used DependencyInjection folder with  Symfony\Component\HttpKernel\DependencyInjection\Extension class. So I configured services.yml for each of my bundles. More is here http://symfony.com/doc/current/bundles/extension.html   And problem is when I tried to use such configuration on bundles with autowire. In short words it is not working when I put code there. It is working only in main service.yml file.

**Comment by xabbuh** [comment]
@git4me2 I am sorry but I do not fully understand your problem. Can you please show a small example project that makes it possible to reproduce your issue?

**Comment by git4me2** [comment]
I will try explain it. I have AppBundle and in this bundle I add folder DependencyIncjection in this folder I put two files:

**AppExtension**

`class AppExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $this->processConfiguration($configuration, $configs);

        $loader = new YamlFileLoader(
            $container,
            new FileLocator([__DIR__.'/../'])
        );

        $loader->load('Resources/config/services.yml');
    }
}`

**and Configuration** 

`class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritdoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('app');

        return $treeBuilder;
    }`

So now the services.yml places in bundle directory/Resources/config/ is working when I write in:

>   cms_bundle.file_cmd_srv:
    class: CmsBundle\Service\FileCmdSrv
    arguments:
      - '@cms_bundle.file_cmd_rep'

but it is not working if I tied to use in this file autowire like this:

> services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

Same code is working when I move content of this service.yml to main app/config/ direcoty

**Comment by xabbuh** [comment]
What is the exact content of your bundle's `services.yml` file? Did you only place your `_defaults` section there order did you also add config code to tell Symfony which services to configure or where to find them (i.e. using the new PSR-4 based mechanism)?

**Comment by git4me2** [comment]
I added:

    AppBundle\:
        resource: '../../src/AppBundle/*'

**Comment by xabbuh** [comment]
In your example given above, the `FileCmdSrv` was located in the `CmsBundle\Service` namespace. That would of course not be autowired when your config matches the `AppBundle` namespace.

**Comment by git4me2** [comment]
sorry I use of course I just paste not this part :)
`CmsBundle\:
    resource: '../../src/CmsBundle/*'`

**Comment by git4me2** [comment]
I have some observation.  Maybe I don't understand how it works :) When I add this part:

>services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: public

to app/config/services.yml and this part:

  CmsBundle\:
    resource: '../../src/CmsBundle/*'
    exclude: '../../src/CmsBundle/{Entity,Repository}'

then it is not working but if I put both part to one of this files it is working.

So my question is do I need to add first part to each services.yml in each bundle?

**Comment by xabbuh** [comment]
Service defaults are indeed only applied to services whose loading is triggered from the same file. I am going to close here as the observed behaviour is not a big but a misconfiguration.
