### ISSUE TITLE
[Validator] AddConstraintValidatorsPass hardcoded value for 'validatorFactoryServiceId'

### ISSUE THREAD

**Issue by ivanpepelko** [symfony/symfony#23224]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^3.3

File `Component/Validator/DependencyInjection/AddConstraintValidatorsPass.php` contains hardcoded value (`validator.validator_factory`) for validator factory service (last statement of method `process()`, call to `ContainerBuilder::replaceArgument()`) --> should use value provided in constructor (`$validatorFactoryServiceId`).

**Comment by xabbuh** [comment]
Do you want to submit a pull request?

**Comment by ivanpepelko** [comment]
Wanted to, but I started reading 'contributing guidelines' and decided to open issue ticket instead.

**Comment by xabbuh** [comment]
see #23226
