### ISSUE TITLE
symfony crawler can not get current node

### ISSUE THREAD

**Issue by saberkahalian** [symfony/symfony#23230]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | /no
| BC Break report? | no
| RFC?             | yes/no

**my html that I want crowl is this :**
```
<div id='dp' >
-- some html
<script>
        kcpAppDialogObj_.find('.kcpAppDeliveryInProgress').html('<div style="text-align:center"><img src="https://images-na.ssl-images-amazon.com/images/G/01/kindle/www/myk/icon_spinner._CB192549371_.gif" /> Processing your request... </div>');
i =1+1
</script>
-- some html
</div>
```
when I use :
`$product = $crawler->filter('#dp');`

it is return just 
```
-- some html
<script>
        kcpAppDialogObj_.find('.kcpAppDeliveryInProgress').html('<div style="text-align:center"><img src="https://images-na.ssl-images-amazon.com/images/G/01/kindle/www/myk/icon_spinner._CB192549371_.gif" /> Processing your request...
</script>
```

it is not return full content of my div

**Comment by stof** [comment]
This is because the parser used by PHP for the DOM extension suffers from the same limitation than older browers: putting HTML tags inside a JS string in a script tag messes with the closing of the tag (it finds the `</div>` inside the script tag).
I don't see anything we can do about this here (we won't reimplement the whole dom extension of PHP in userland to use a different parser).
If you control the HTML, the solution is to split the JS string with concatenation just after the `<`

**Comment by saberkahalian** [comment]
Thanks for your response but I did'n get what you mean ! 
I am crawling a webpage that the content of html  it is not under my  controller, I just parse html and I supposed that the parser investigated that tag of </div> is inside the script and it is not end of main parsed div!

**Comment by stof** [comment]
Well, if the HTML is not under your control, fixing this will be very hard

**Comment by jakzal** [comment]
Indeed, this is [a problem with the DOM extension](https://3v4l.org/fET2j):

```
<?php

$content = <<<DOC
<div id='dp' >
-- some html
<script>
        kcpAppDialogObj_.find('.kcpAppDeliveryInProgress').html('<div style="text-align:center"><img src="https://images-na.ssl-images-amazon.com/images/G/01/kindle/www/myk/icon_spinner._CB192549371_.gif" /> Processing your request... </div>');
i =1+1
</script>
-- some html
</div>
DOC;

$doc = new DOMDocument();
$doc->loadHTML($content);
$query = new DOMXPath($doc);
$divs = $query->query('//div[@id="dp"]');

foreach ($divs as $div) {
    var_dump($div->nodeValue);    
}
```

will print:

```
-- some html

        kcpAppDialogObj_.find('.kcpAppDeliveryInProgress').html('<div style="text-align:center"><img src="https://images-na.ssl-images-amazon.com/images/G/01/kindle/www/myk/icon_spinner._CB192549371_.gif" /> Processing your request... "
```

As stof said the bug is in the dom extension and there's nothing to do in Symfony.

**Comment by chan17** [comment]
infoWin.setContent('<div style="width:280px;height:100px;">' + pois[n].name + ':'
                                + pois[n].address + '<br/> <span class="label label-success">已选择当前位置<\/span><\/div>');

delete End of tag or add \ . all It works. became The browser fixes the broken tag

**Comment by chan17** [comment]
infoWin.setContent('

' + pois[n].name + ':'
+ pois[n].address + '
已选择当前位置<\/span><\/div>');
delete End of tag or add \ . all It works. became The browser fixes the broken tag

**Comment by chan17** [comment]
infoWin.setContent('

' + pois[n].name + ':'
+ pois[n].address + '
已选择当前位置‘);
delete End of tag or add \  （<\/span ><\/div >）. all It works. became The browser fixes the broken tag

**Comment by chan17** [comment]
```
infoWin.setContent('<div style="width:280px;height:100px;">' + pois[n].name + ':'
                                + pois[n].address + '<br/> <span class="label label-success">已选择当前位置<\/span><\/div>');
```

delete End of tag or add \ . all It works. became The browser fixes the broken tag
