### ISSUE TITLE
Performance regression in DEV mode since "Use VarDumper in the profiler"

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony#23233]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

I know that VarDumper in the profiler brings lot of improvements especially when displaying objects but it's a bit weird to loose so much performance on some pages when upgrading to Symfony 3.3. 

In fact the more important impact is linked to pages that are composed with render controller. Exceution time and memory usage increases a lot. Please check the benchmark file in attachment.

[Benchmark-20170620.pdf](https://github.com/symfony/symfony/files/1088227/Benchmark-20170620.pdf)

To resume (each widget is integrated to a dashboard as render controller):
In PHP 5.6.30:
- Dashboard with 12 widgets: SF 3.1.5: 978ms - SF 3.3.2: 2499ms -> +255%
- Dashboard Global with 14 widgets: SF 3.1.5: 1430ms - SF 3.3.2: 3307ms -> +231%

In PHP 5.6.30:
- Dashboard with 12 widgets: SF 3.1.5: 406ms - SF 3.3.2: 861ms -> +212%
- Dashboard Global with 14 widgets: SF 3.1.5: 748ms - SF 3.3.2: 1338ms -> +179%

I know some work have been done to improve the performance here: https://github.com/symfony/symfony/pull/19986

I'm not sure if something can be done, especially for render controller use case, because the profiling is done for all sub requests even if a lot of data comes from the Master Request (Doctrine, Security, Twig, etc). I just don't understand why the memory usage increase as much. Please also note that the Dashboard page doesn't contains any form. It seems the Routing page of sub requests make the memory increase a lot.

I let you close the ticket if you think that nothing can be done.

**Comment by javiereguiluz** [comment]
I noticed a similar slowdown. See the profile of the same page of a complex Symfony app using 3.2 and 3.3 versions:

## 3.2.9

![before-profiler](https://user-images.githubusercontent.com/73419/27336585-51190bb2-55d0-11e7-9c51-9fac64f4dd49.png)

## 3.3.2

![after-profiler](https://user-images.githubusercontent.com/73419/27336587-52dc7448-55d0-11e7-8c30-6541a2b74dff.png)

## Main differences

![comparison-profiler](https://user-images.githubusercontent.com/73419/27336359-97113c6c-55cf-11e7-8cbe-37dd9d68af8f.png)

**Comment by nicolas-grekas** [comment]
This means too much data is being cloned. Can you think of any object that could be collected but should be skipped because it's not displayed? There should be some to explain the difference.

**Comment by graemechapman** [comment]
I am also seeing a massive difference in memory usage. My php memory limit was previously set to 64mb, since upgrading from 3.2.9 to 3.3.2 I've had to increase this to 160mb to avoid getting out of memory errors. I have tested on a few different Symfony versions, and this change occurs between 3.3.0 and 3.3.1. 

I also noticed that the performance tab shows about 50% increased peak memory usage, all consumed by the ProfilerListener. 

With a lower memory limit, an out of memory exception always occurs at https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php#L44

The memory usage in production environment is unaffected.

I am currently running PHP 5.5.38.

**Comment by raziel057** [comment]
Performance Page - Master request

![master_request](https://user-images.githubusercontent.com/652505/27382152-ef87d5de-5685-11e7-9973-777b98eae32d.png)

If I check the Performance page of a Sub Request (widgetGenderAction), I can see that Total execution time doesn't correspond to the processing of the sub request (11ms). Is it normal? It does not match either the total execution time of Master Request (825ms or the total of Sub Request time 179 ms).

![sub_request_perf](https://user-images.githubusercontent.com/652505/27381811-88969834-5684-11e7-8535-fb79b5ddf7d9.png)

If I click on the Routing page of Sub Request, I got an OutOfMemory exception (on php 7.1.6 with memory_limit=128mb) 

![routing_error](https://user-images.githubusercontent.com/652505/27382343-cfe5328e-5686-11e7-8529-c275800430f5.png)

When I increase the memory limit, I got:

![routing_sub_request](https://user-images.githubusercontent.com/652505/27382356-e3adabd4-5686-11e7-9877-509a4f38ce34.png)

None route match for Sub Requests so maybe the Routing data collecting could be avoid here?

**Comment by stof** [comment]
Well, the timing of a request does not include the time spent in ProfilerListener (this is a chicken and egg issue: how do you measure the time until after you are done saving the result of the measure ?).

And the issue here seems to be that the `Symfony initialization time` is add in subrequests too, while it is actually paid by the master request only (you pay it once per process only).
The collector would need to skip collecting this part of the timing when collecting info for a subrequest.

**Comment by stof** [comment]
And this matches numbers: 293ms is 282ms (SF initialization, copied from the master request by mistake) + 11ms (time collected for the subrequest)

**Comment by raziel057** [comment]
@stof Ok understood but in that case the figure in master request is not accurate (5ms). Check my screenshot of Master Request. 

What is your opinion about the routing part?

**Comment by javiereguiluz** [comment]
Not sure if related to this, but the files generated by the profiler (var/cache/dev/profiler/*) are HUGE. It takes more than 2 MB per request in some of my applications. Other users have complained about this too.

**Comment by markitosgv** [comment]
Hi!

We have same issue, when upgrading to Symfony 3.3.x.

For example I've got a page with a form field EntityType, which loads about 500 entities to a select dropdown, now profiler generates a >50Mb file and 404 debug toolbar error appears.

If I downgrade to Symfony 3.2.x, same page, generates a 1.8Mb profiler file.

**Comment by XWB** [comment]
Profiler is pretty slow after upgrading to Symfony 3.3. Furthermore, disk size is gigantic. At some pointed it reached over 100 GB of space.

![image](https://user-images.githubusercontent.com/1032281/27579961-90519476-5b29-11e7-993d-cd1ec038b723.png)

**Comment by javiereguiluz** [comment]
I don't know if this is a bug or a feature that must be reverted, but I've added the "Critical" label because fixing this should be our top priority. Thanks!

**Comment by nicolas-grekas** [comment]
Please post one of these big files.

**Comment by XWB** [comment]
Profiler directory reached 110 GB today:

![image](https://user-images.githubusercontent.com/1032281/27626921-2e101f46-5bea-11e7-83b4-a47d779be7e4.png)

**Comment by mvrhov** [comment]
@XWB: You are pressing F5 too much :P

**Comment by XWB** [comment]
Well it never was an issue prior to Symfony 3.3 ;)

**Comment by XWB** [comment]
@nicolas-grekas What file would you like to see? Each directory within `/cache/dev/profiler/` contains a lot of subdirectories, each being 454 MB in size:

![image](https://user-images.githubusercontent.com/1032281/27681027-16233218-5cbe-11e7-9cc8-73dfa2a513cf.png)

**Comment by markitosgv** [comment]
Please, any update? I can't upgrade to Symfony 3.3 :(

**Comment by theofidry** [comment]
@markitosgv it's not progressing much because we don't have any reproducible code. If you can publish such of those files or publish a repo where this error occurs I'm sure it would be solved in no time :)

**Comment by szymach** [comment]
Maybe it is linked to the Symfony's web server? I know that sometimes you can get extremely slow performance out of it (like when rendering PDFs with `KNPSnappyBundle`). Also, this drop is new, since I was able to run a project on my PC on 3.3.0 without any issues initially.

**Comment by graemechapman** [comment]
> Maybe it is linked to the Symfony's web server? I know that sometimes you can get extremely slow performance out of it (like when rendering PDFs with KNPSnappyBundle).

I'm seeing similar issues when using Apache.

**Comment by IwfY** [comment]
For us the problem is most noticeable on Sonata admin pages (3.20.1).
Using Twig 2.3 instead of 2.4 makes it better, it's still a noticeable performance drop.

Using Symfony 3.3.2, Apache.

**Comment by markitosgv** [comment]
We are using MongoDB, Nginx and PHP 7. You can try with a EntityType in a form (in our case DocumentType) with ~400 results for example to notice that.

**Comment by szymach** [comment]
Oh yeah, I forgot to mention I do have a lot (~280) of depreciations messages out of Twig, since the libraries I use still use it in version 1.20-ish and I can not switch to 2.x. Could be another lead? PHP 7.1 btw.

**Comment by nicolas-grekas** [comment]
Please share one of the big files generated by the profiler.

**Comment by szymach** [comment]
@nicolas-grekas I have a ~400MB profiler file I could share, but I the question is where do I send it? Is there any sensitive data in those files I should be worried about, or can I just upload it to some file sharing service without worry?

**Comment by ctaverne** [comment]
Hi, Same issue here. Memory usage is increasing massively.

**Comment by nicolas-grekas** [comment]
See #23415, Backfire profiles welcomed.

**Comment by markitosgv** [comment]
Hi guys, for me problem with Symfony 3.3.4 still persists.

![image](https://user-images.githubusercontent.com/1706470/27900348-4c4ed53e-622e-11e7-8b6a-8c03f513f654.png)

Same page, with symfony 3.2.9 works :/

**Comment by nicolas-grekas** [comment]
In fact, this maybe related to a high number of deprecations, not only to the way the collected data is collected in 3.3. Is that plausible? Can you post a screenshot of the profiler deprecation panel?

**Comment by markitosgv** [comment]
This is another page deprecations info:

![image](https://user-images.githubusercontent.com/1706470/27900647-84a84cc0-622f-11e7-9e4c-e1c190edf487.png)

But, I think it's not about deprecations, look:

```php
...
            ->add(
                'activeOrganization',
                DocumentType::class,
                [
                    'label'       => 'Active Organization',
                    'class'       => Organization::class,
                    'attr' => [
                        'placeholder' => 'userContact.activeOrganization.placeholder',
                    ],
                    'query_builder' => function ($qb) {
                        return $qb->createQueryBuilder()->select('contact.name')->select('owner')->field('owner')->prime(true);
                    },
                ]
            )
...
```

If I put a limit in the query, like 100, It works ok. I know this is not the best way to show a select with a huge collection of entities, but it's ok for this purpose.

**Comment by szymach** [comment]
I have this issues on a page where there's a query returning a single record, so I do not think it is related to a lot amount of data being fetched from the database.

**Comment by nicolas-grekas** [comment]
Please open specific issue, related to the Form panel it looks like?

**Comment by XWB** [comment]
> In fact, this maybe related to a high number of deprecations, not only to the way the data is collected in 3.3. Is that plausible? Can you post a screenshot of the profiler deprecation panel?

I have only 1 deprecation notice in my application.
