### ISSUE TITLE
[Bug] Strange UrlGenerator since Apache 2.4.26

### ISSUE THREAD

**Issue by neoteknic** [symfony/symfony#23236]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.22

Strange bug started with Apache 2.4.26 :

Example in Prestashop 1.7 (link to module list) :

Link is (apache 2.4.26) :
/module/catalog (think link don't work)

instead of (apache 2.4.25) :
/adminXXXX/index.php/module/catalog

I have also a strange bug in phpmyadmin after upgrading Apache, after login it redirect to the parent folder ( example : mydom.com/ instead of mydom.com/phpmyadmin), fixed by setting an url in the config, it can be related.

PHP version : php-fpm 7.1.6
Symfony 2.8.* latest from composer

With same php version and Apache 2.4.25 it's ok.
Absolutly nothing was modified in php files or in php config (php-fpm was not restarted too, only Apache). And no config files was modified in apache.

It's something related to:
   Symfony\Component\Routing\Generator\UrlGenerator method doGenerate

**Comment by xabbuh** [comment]
I am sorry, but I do not think that this is related to Symfony (at least you are talking about phpMyAdmin which is in no way related to Symfony). Thus I am going to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by neoteknic** [comment]
phpmyadmin include symfony in dependencies.
Sorry, it was related to wrong SCRIPT_FILENAME in symfony url generator.
Added ProxyFCGIBackendType GENERIC in apache config to fix it.

**Comment by PABourdin** [comment]
Sorrry, I do have the same issue, unrelated to phpmyadmin, in another Silex2 application (gitlist).

@neoteknic could you please describe much more in detail how you fixed the problem?
Thanks a lot!

**Comment by PABourdin** [comment]
This is my current Apache config:

```
Alias /app/ /path/to/app/
<Directory /path/to/app>
Options -MultiViews +SymLinksIfOwnerMatch
FallbackResource /app/index.php
<Files config.ini>
Require all denied
</Files>
</Directory>
```
