### ISSUE TITLE
Impersonate an user with remote_user and form_login firewalls

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#23249]
Hi,

I have an application with a `remote_user` authentication firewall on which I need to set the impersonate system to make admin users able to login as another user.

I know that the impersonating mechanism is [not compatible with pre authenticated](http://symfony.com/doc/current/security/pre_authenticated.html) firewalls like `remote_user` so I decided to add a second firewall with `form_login`.

But the `remote_user` firewall seem to take the priority on the  `form_login` so I cannot switch user. I still be logged with the `remote_user` credentials.

Is it possible to use `User impersonation` when multiple firewalls are configured and a `remote_user` is one of them?

Thanks

**Comment by jakzal** [comment]
I think this is not possible as it would require making `remote_user` stateful to share the authentication context (see #8614 #18406).  Perhaps you could [leverage guard](https://symfony.com/doc/current/security/multiple_guard_authenticators.html#multiple-authenticators-with-shared-entry-point) in some way to accomplish what you need.

What order are your firewalls registered in?

**Comment by chalasr** [comment]
Closing due to the lack of feedback.
