### ISSUE TITLE
DataCollectorTranslator::getFallbackLocales() return empty array

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#23248]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

Hi !

When i call `$container->get('translator')->getFallbackLocales()`, in dev environment, i get an empty array.
I have to call `$container->get('translator.default')->getFallbackLocales()` to really get fallback.

Problem is here : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/DataCollectorTranslator.php#L100
I have a `LoggingTranslator` instance, not `Translator`.
We can't change `instanceof Translator` by `instanceof TranslatorInterface`, cause `TranslatorInterface` do not define `getFallbackLocales()`.

I don't know how to fix it ...

**Comment by xabbuh** [comment]
see #23250

**Comment by Hanmac** [comment]
hm i still don't see why it does look for specially Translator and why TranslatorInterface can't be extended to use getFallbackLocales :/

**Comment by chalasr** [comment]
> why TranslatorInterface can't be extended to use getFallbackLocales

@Hanmac Adding a new method to an interface would break any implementation that is not already implementing this method, adding a new interface extending the TranslatorInterface one is possible, but that needs to be discussed beforehand (in a dedicated issue) .

**Comment by xabbuh** [comment]
Adding a new method to an interface is a BC as all implementations would need to be adapted. That's why we cannot do so.

**Comment by steevanb** [comment]
Thanks !

**Comment by steevanb** [comment]
Just a question : `This PR was merged into the 2.7 branch.`, what about 2.8 et 3.x ?

**Comment by javiereguiluz** [comment]
@steevanb from time to time we merge from lower branches to higher branches. So your PR will be merged "soon" to the upper branches too.

**Comment by steevanb** [comment]
Ok, thanks !
