### ISSUE TITLE
Throwing AccessDeniedException when getCredentials() in GuardAuthenticator are null

### ISSUE THREAD

**Issue by nospor** [symfony/symfony#23253]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi, I upgraded to Symfony3.3 from 3.2. I am using GuardAuthenticator to authenticate my users. I also have ExceptionListener to provide my own responses to different exceptions depending on is it AJAX or not.

In class below there are two methods

```
class SsoAuthenticator extends AbstractGuardAuthenticator {
.....

    public function getCredentials(Request $request)
    {
        //it returns credentials or NULL
    }
.....
    public function start(Request $request, AuthenticationException $authException = null)
    {
        $url = $this->container->getParameter('sso.server_url');
        $url .= '/login?redirect=' . urlencode(
                $request->getScheme() . '://' .
                $request->getHttpHost() .
                $request->getRequestUri()
            );

        return new RedirectResponse($url);
    }
}
```

According to documentation methos `start()` is called when method `getCredentials()` returns null;
It was working fine with symfony3.2. But when I upgraded to symfony3.3 it stopped working. Method `start()` was not called anymore. After long investigating it appeard, that in symfony3.3 you throw AccessDeniedException which you didn't in Symfony3.2. And now, when I have my ExceptionListener yours AccessDeniedException goes first to my ExceptionListener and then I return some Response and method `start()` is not called anylonger. I had to add some conditions in my ExceptionListener that when is raised AccessDeniedException i must do `return; ` and then method `start()` is finally called.

Well, IMHO it is not a good solution. I think you shouldn't throw exception when `getCredentials()` returns NULL. I think you should do what you said you will do which is call `start()` method directly. Now I, and maybe others need to play with this strange situation.

Robert

**Comment by chalasr** [comment]
> After long investigating it appeard, that in symfony3.3 you throw AccessDeniedException which you didn't in Symfony3.2.

Would you be able to point out this change or when it has been introduced?

**Comment by nospor** [comment]
Well, maybe it was throw in Symfony3.2 as well but it was catched by something in the middle? All I know is now (Symfony 3.3) this exception goes directly to my ExceptionListener which didn't happen in Symfony3.2. 
Below is the exception trace which I can see when it goes to my ExceptionListener. Maybe it will tell you something more.

> #0 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php(69): Symfony\Component\Security\Http\Firewall\AccessListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#1 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/EventListener/FirewallListener.php(48): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#2 [internal function]: Symfony\Bundle\SecurityBundle\EventListener\FirewallListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#3 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(106): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#4 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#5 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#7 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(146): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#8 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#9 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/html/brad/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(171): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/brad/web/app_dev.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}

**Comment by ussuritiger** [comment]
This is from the documentation (version 3.3):

> **start(Request $request, AuthenticationException $authException = null)**
    This is called if the client accesses a URI/resource that requires authentication, but no authentication details were sent (i.e. you returned null from getCredentials()). Your job is to return a Response object that helps the user authenticate (e.g. a 401 response that says "token is missing!").

My **getCredentials** method returns _null_ but the **start** method is never called. An exception is thrown instead.

**Comment by nospor** [comment]
@ussuritiger  exactly. It is not a problem if you do not have your own ExceptionListener - then symfony catch that exception and call `start()` method. If you have your own ExceptionListener, then you have a problem as I have described.

**Comment by wimpog** [comment]
Same issues here! **AccessDeniedException** instead of **AuthenticationException** in **start()**, and the **start()** method can't be type-hinted with **AccessDeniedException**

**Comment by chalasr** [comment]
Status: reviewed

I'm on it.

**Comment by chalasr** [comment]
Can someone try #23291 and confirm it fixes the issue?
This is a BC break in the event dispatcher component.

**Comment by nospor** [comment]
@chalasr  thank you, I've just checked your fix and seems to be working fine now :)

**Comment by chalasr** [comment]
thanks for the quick confirmation @nospor

**Comment by nospor** [comment]
You are welcome. But it is you who did the most job, so well done and thx once more for your fix :)
I am not familiar with Symfony acceptance process but when we can expect this in official Symfony3.x version?

**Comment by chalasr** [comment]
The next maintenance releases should occur in ~10 days (once a month). 
Given I think we can expect it to be reviewed quickly (your confirm helps a lot) as this behaviour change may impact more than only the security component, I hope the patch will be part of the next release set.
