### ISSUE TITLE
[RFC] [DX] Re-usable Controller layout

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#23259]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
Symfony version  | 3.4 and\or 4.0

Hi, I'm currently working on some kind of RPC server bundle stack on top of symfony and I have a simple internal method routing, which generally repeats the symfony one's. I say repeats but not re-uses (which I hope to do initially), since the current routing have several limitations:

* [Controller Resolver](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php) signature requires the whole `Request` object, but really it uses only `_controller` attribute value, can we pass it instead? The `Request` object is used only to build Exception message with `getPathInfo` call, but I think we can overcome it with rethrow on higher level or just refactor it out. Most of the exceptions, thrown by `ControllerResolver` do not use the `PathInfo` to construct the message.

* [Controller Name Parser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php) signature hardcodes the `Controller\*Controller::*Action` controler layout and it is even not configurable. Replacing this layout to another (or making this configurable) leads to full class override with copy&paste despite of the fact it is open for inheritance. we can make action guessing and action parsing to be protected methods, which define the layout

I also have some thoughts on decoupling `Route` from HTTP since most of the routing loading process could be fully reused for creating internal routing, but the current `Route` class is all about HTTP routing (i.e it [modifies path to match URI format](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Route.php#L159)), but I haven't fully formalized this thoughts yet

I hope we can make the components a bit more decoupled with this ideas.

WDYT?

**Comment by iltar** [comment]
Being able to resolve a controller based on a name, will have a big :+1: from me. It would be even possible to cache the result. I've been playing with this a while back, but never got finish it as the change was too big.

**Comment by scaytrase** [comment]
The same happens with `SensioFrameworkExtraBundle`, most of the annotations and their listeners could be re-used since they use just request attributes (and update the attributes) and the request instance (as an expression variable, whatever the type it is), but re-using them requires to fully copy&paste them to change the listener signatures (in general use another event, replace `->attributes` to `->getAttributes()` only)

The same happens with new `ArgumentResolver` system, the only default value resolver that really uses the request as the instance of `Request` is the `SessionValueResolver`, others are using attributes and push new attributes back.

I think that the real issue it that we trying to bind to the implementation of `Request`, not to the specific interfaces like some kind of `AttributedRequestInterafce` or `SessionRequestInterface`

Inventing some interfaces for the `Request` class could help us to decouple from it in some places

**Comment by derrabus** [comment]
Resolving a request to a controller is the router's job. It parses the request and adds a `_controller` attribute to it.

Since for an RPC implementation the information you need to determine the controller usually has to be extracted from the request body, Symfony's default router (which is designed to use URL and method for routing) won't work here.

Implement your own router by implementing `RequestMatcherInterface` and either
* attach it to an event listener that runs before/after the default router or
* use the `ChainRouter` from Symfony CMF to register your custom router along with the default one.

**Comment by scaytrase** [comment]
@derrabus good idea indeed, but won't work since `jsonrpc` determines the **batch** request which requires special processing, so I really cannot implement `RequestMatcherInterface` here since there is several RPC requests within single HTTP one.

But I'm not sure how can I attach it to the default router without exposing controllers as a generic HTTP controller, since the HTTP `path` rules and the JSON-RPC `method` is the different thing with different rules

**Comment by derrabus** [comment]
@scaytrase You would need a controller for batch requests then. You could even reuse your RPC router there and process each individual call within the batch request as sub-request.

Regarding the default router: as I said, you can't use it. I've already implemented an RPC router because I had to migrate an RPC backend of an ExtJS application to Symfony and I did not want to rewrite all existing remotely callable classes.

Please have a look at slide 22 and 23 of this deck. Does that help you?

https://slidr.io/derrabus/modernizing-with-symfony#22

**Comment by scaytrase** [comment]
> You would need a controller for batch requests then.

I already have one, yes

> You could even reuse your RPC router there and process each individual call within the batch request as sub-request.

If I re-use `RequestMatcherInterface` router here, then I should construct a new (`::duplicate`) `HttpKernel\Request` for each RPC subrequest and process each one as generic HTTP request. 

The general idea looks interesting, I'll take a deeper look into it. Some questions

* Would it have any performance impact (calling full HTTP stack for every RPC subrequest)? 
* What about routing cache, like HTTP have done?

**Comment by derrabus** [comment]
Yes, there will be a slight overhead, but you'd have the advantage that you don't have two different ways of invoking RPC calls.

Anyway, back to this RFC: I don't think that any generic controller matching magic would be helpful in your case. What would be helpful imho is a way to add custom request matchers to Symfony's routing as your case requires deep inspection of the request body.

**Comment by scaytrase** [comment]
@derrabus I'm already have single way for both batch and single request, I'm just splitting things up, process each one and combines responses back. The problem is that if I'll use `HttpKernel` for processing - then I'll receive the `Http\Response` back, not the RPC one. Of course I can make a special `RpcResponse extends Response` with RPC response payload as separate field, but this will be a real overhead, since I do not need the whole `Response` part of this class.

Matching logic is not about my case, but about binding to ~unused interfaces~ implementation instead of interface, which leads to impossibility to re-use the component. There is no need for deep inspection, there need is to have the `ParameterBag` with `_controller` value specified, and all the magic starts working.

**Comment by derrabus** [comment]
@scaytrase If I understood the batch format of JSON-RPC correctly, you should be able to simply concatenate the rendered JSON response bodies to get a valid batch response. So having `Response` objects should not be a big deal, imho.

```php
<?php

$responses = [ /* the Response objects from the sub requests */];
$responseBodies = array_map(
    function (Response $response) {
        return $response->getContent();
    },
    $responses
);

return new Response(
    '['.join(',', $responseBodies).']',
    Response::HTTP_OK,
    ['Content-Type' => 'application/json']
);
```

**Comment by scaytrase** [comment]
@derrabus in simple case, yes, but passing the RPC response as plaintext content would end in difficulties building infrastructure around this, like handling and converting RPC exceptions to proper response, filtering reponses, etc. 

* I.e controller may produce `void` as the action result, and this should end in NO response representation (200 OK with no content).
* Or I wan't to filter out `data` field from `error` JSON-RPC property if I have `debug` disabled, in your case I should parse the body back, filter it and replace the body.

So having a structured response representation is useful.

Your arguments are totally correct from the POV of refactoring or modernizing legacy app with symfony, with this thoughts we. For us the JSON-RPC is internal standard and I'm trying to build a toolchain for fast and comfortable service development from scratch ontop of symfony, so I'm searching a way to make it extensible and reusable

**Comment by derrabus** [comment]
@scaytrase If you really need to parse responses, subrequests are bad. But I really don't think you would need to. All the examples you provided contain problems that you need to solve for individual calls anyway. So if your batch controller shouldn't really care about converting exceptions etc. 

Don't get me wrong: I don't say, you *have to* use subrequests for your batch requests. It's just that you might need to duplicate framework functionality if you don't.

Anyway, we've left the topic of this RFC, I think.

So if request matching is not an issue for you, what exactly is the problem you're facing?
* You can match a request to a call to any public method of any class or public service.
* And you can convert whatever the controller returns to a valid HTTP response (using the `VIEW` and `EXCEPTION` events).
So, it is in my opinion possible to implement a generic RPC framework on top of Symfony. What needs to be changed to make implementing such a framework easier for you?

**Comment by scaytrase** [comment]
> So if your batch controller shouldn't really care about converting exceptions etc.
Batch controller really does not, but other cases are still valid. My favourite case is handling 500 exception of subrequest as it will produce you an html (or raw json, if we set the `_format` correctly`, not a valid json-rpc response

> So, it is in my opinion possible to implement a generic RPC framework on top of Symfony

Sure it's possible, I already did one. But it's so terrible :D It has grown eventually under pressure of limited time, so copy&pasting was a suitible dirty decision. Now I have some time to deal this, so I posting my suggestions, which could be made with Sf 4.0 (as some of them tends to be BC breaks)

To implement it I've copy&pasted almost all components mentioned above:
* Routing (`Loader`, `Matcher`, route cache) as soon as use simplified `Route` (`Method` actually) with only `path` and `defaults` (these are essentials). Current `Route` is heavy bounded to HTTP protocol, one can be abstracted to inherit generic functionality
* `ControllerNameParser` since the `@BundleName\Controller\ClassController::actionAction` layout is hard-coded and not changeable. This could be abstracted to represent layouts with protected methods or constructor arguments
* `ControllerResolver` since it is bound to the `Request` instead of `ParameterBag`. We can pass the `ParameterBag` there in some way - via the interface `::getAttributes()` or directly pass `ParameterBag` for resolution.

ATM im thinking of `ArgumentResolver` since the idea is very simple, but everything is bound to `Request` again

**Comment by derrabus** [comment]
> My favourite case is handling 500 exception of subrequest as it will produce you an html (or raw json, if we set the _format correctly`),but not a valid json-rpc response

As I said earlier: You have to deal with this issues for individual calls anyway. If you send a single RPC call (no batch) and the endpoint talks back in HTML, it's violating the standard. This is not related to subrequests at all.

Register a listener in the `KernelEvents::EXCEPTION` event and convert the exception to the error format defined in the JSON-RPC standard.

> To implement it I've copy&pasted almost all components mentioned above:
> * Routing

Yes, routing is the part that requires the most effort. You have to do the request matching on your own because neither controller nor attributes are matched through the URL, but through the request body instead.

Just make sure that, after the `KernelEvents::REQUEST` event has been processed, the `_controller` attribute is set properly on the request and that all arguments that need to be passed to the controller action are registered as attributes as well. This way, the framework should be able to take over again.

What you need is a way to configure which actual class or service is responsible for which RPC method. Symfony's concept of routes does not help here, since it's designed for URL-based matching, which is okay for about 98% of the use cases of Symfony, I guess. I doubt that we find a one-size-fits-all approach here that makes our lives easier, so imho it's okay that you have to come up with your own way of configuring your request matcher.

> the `@BundleName\Controller\ClassController::actionAction` layout is hard-coded and not changeable

This is not true. If your request matcher writes fully qualified method reference like `Acme\MyApplication\SomeRpcObject::someMethod` or a service reference like `some_service_id:someMethod` into the `_controller` attribute, the controller resolver should be able to handle it.

> `ControllerResolver` since it is bound to the Request instead of `ParameterBag`

Why would you care?

> ATM im thinking of `ArgumentResolver` since the idea is very simple

I don't think you need argument resolvers here. You need a custom request matcher anyway and it should be able to retrieve all arguments from the request already.

**Comment by scaytrase** [comment]
okay, we've started the cycle here

> This is not true. If your request matcher writes fully qualified method reference like 

Actually no, that's job done by `ControllerResolver`, not `ControllerNameParser`. Controller Name Parser [requires `a:b:c` notation strictly](https://github.com/symfony/framework-bundle/blob/master/Controller/ControllerNameParser.php#L49-L52), and maps it to the `MyBundle\Controller\MyController::myAction` string and vice versa.

If my matcher writer the fully qualified notation - yes this would work. But that means that I should apply the my own `ControllerNameParser` by myself, If my routing allows `a:b:c` notation and I want just another folder to place non-http controllers (see below about easy mistake consequence)

>  doubt that we find a one-size-fits-all approach here that makes our lives easier, so imho it's okay that you have to come up with your own way of configuring your request matcher.

I'm not asking anybody of making things to match everyone needs, but do you really think, that [this logic,](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php#L41-L64) for example, really belongs to HTTP routing? It's kind of recursive loader logic, but the only thing belonging here to HTTP routing is the `RouteCollection` class reference

> Why would you care?

I can start a long talk about design, LoD, but not. I just ask, why we not passing the whole `RequestStack` or entire `Kernel` just because no one cares?

> As I said earlier: You have to deal with this issues for individual calls anyway.

Yes and processing them is a problem (as a plaintext part of a `Response`. I remember, that we are speaking about DX and a library (or toolchain), not about a final project, which is under my full control.

* `FilterResponse` event happens after `View` event, and if someone wants to modify the RPC response, he should ensure that it was RPC request and than parse, modify and replace body
* We are still dealing HTTP stack here, which means any `Response` object passed from the controller (as a mistake or misunderstanding) will pass the `View` event entirely resulting in garbade among the subrequests. You will not receive the fancy error that your response has invalid format, you'll just get garbage in final response

> I don't think you need argument resolvers here. You need a custom request matcher anyway and it should be able to retrieve all arguments from the request already.

Yes, but argument resolution mostly happens from the `Request->attributes` and I cannot blindly fill the attributes with RPC parameters since this is a security issue.

**Comment by nicolas-grekas** [comment]
Why should this be in core? Can't it be in a bundle?

**Comment by scaytrase** [comment]
@nicolas-grekas not sure I've understood a question. 

I'm not suggesting here to introduce new logic but to split and lower signature requirements (Request with proper named attribute -> attribute string value ), since the logic does not requires `Request` instance itself.

The RPC logic example is just example and it is already the bundle with copy-pasted modified classes (just because we can not reuse the current `Request`-based implementation), I'm not suggesting to push this into core.

We can decompose current implementation into simply string-based signature and `Request` based facade for BC (since we missed 3.4 and 4.0 here)

**Comment by nicolas-grekas** [comment]
OK, sorry, got it. So I guess this could be done, would you try a PR? (piece by piece if possible, so that it's easier to review/accept and less "risky" on your side)

**Comment by scaytrase** [comment]
If this is an acceptable plan, I can start some work on it, sure

**Comment by iltar** [comment]
Sounds like a good idea to me, I can help out with reviews and concept

**Comment by Tobion** [comment]
Closing see https://github.com/symfony/symfony/pull/25422#issuecomment-368241404
