### ISSUE TITLE
JsonResponse should not produce HTML "safe" JSON by default

### ISSUE THREAD

**Issue by ryancastle** [symfony/symfony#23258]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.7

By default, `JsonResponse` currently encodes JSON to be "safe" to embed into HTML, by over-encoding output.

`// Encode <, >, ', &, and " characters in the JSON, making it also safe to be embedded into HTML.`

In practice, this seems to encourage developers (and consumers of this JSON output) to not bother escaping JSON content in HTML documents. Which is not something that should happen with JSON, because it can come from anywhere. We should not depend on the default configuration of a library like this to ensure safe HTML output. It seems like a perfect parallel to the old `magic_quotes` setting in PHP. By trying to idiot-proof security, you create less of it. We can see that because I believe the default encoding options should be removed, but it is going to be difficult to do now without creating security problems for developers who have unwittingly depended on this setting.

In addition to that, you get bulkier & and harder to read JSON output, for what seems to be (at best) no benefit. If it was purely about convenience, I think it would be a different issue altogether, and I believe there would be a benefit to the current options.

I'd prefer to remove those encoding options, and perhaps even turn on `JSON_UNESCAPED_SLASHES` because it seems to be used for the same `magic_quotes` reasons (but at the `json_encode()` defaults layer in PHP).

**Comment by xabbuh** [comment]
Given that you can already change the encoding options in `JsonResponse` what would you still wanna change?

**Comment by javiereguiluz** [comment]
@xabbuh I think I agree partly with @ryancastle's comment. I don't think it's as bad as magic_quotes ... but it's probably not 100% correct either.

At least in Symfony 3.2 we added a named constructor `::fromJsonString()` which should help a bit with this. See https://symfony.com/blog/new-in-symfony-3-2-dx-improvements#added-a-named-constructor-to-jsonresponse

**Comment by ryancastle** [comment]
@xabbuh Yes. I still think it's worth changing. Symfony shouldn't be encouraging/facilitating anybody to dump unencoded JSON into HTML. I believe there's also a benefit in eliminating as much "implementation specific" JSON configuration as we can, to produce JSON that works the way most JSON works. PHP is already a bit guilty of that, by escaping slashes even though most JSON real world examples don't do that. 

The `fromJsonString()` method is a good addition, but I don't think it really changes the issue here. Every developer who benefits in any way from this feature, is leaving themselves exposed to a JSON implementation change or tweak.

1. Do we agree that this encourages poor development practice?
2. If so, do we think a security-hole producing BC break is justifiable to to fix it?

I don't think we resolve the issue cleanly without a BC break, but that might be worth thinking about too?

**Comment by nicolas-grekas** [comment]
We cannot do this change as it would potentially open security issues in existing apps.
Being "unencoded" by default so that devs are put face to face with their mistake is a bad argument to me also...

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because of the mentioned security concerns. Symfony always tries to be "safe by default", so 'm afraid we cannot change this.

**Comment by choult** [comment]
Just in the interest of posterity, as one of our engineers was looking into escaping the HTML content of JSON responses for XSS-safe use over AJAX by a client JS application and found the discussion on this Github issue confusing:

It's our understanding that the escaping of JSON content from `JSONResponse` is intended only to combat [MIME/content-sniffing](https://en.wikipedia.org/wiki/Content_sniffing) by web browsers that are keen to render everything as HTML; imagine being pointed at a JSON response by an attacker that the browser interprets as HTML.

This escaping is not suitable for preventing XSS triggered when a JS application adds data from a JSON object to the DOM; good practice is to never trust the source of data and to escape when placing it on the page, so please ensure you're escaping data prior to display to a viewer when rendering it in Javascript.

Some background:

https://www.drupal.org/project/drupal/issues/479368
https://github.com/expressjs/express/issues/3268
