### ISSUE TITLE
[Validator] RecursiveContextualValidator and metadata cache edge case

### ISSUE THREAD

**Issue by gonzalovilaseca** [symfony/symfony#23263]
| Q                | A
| ---------------- | -----
| Bug report?      | not sure
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2

We came across an edge case when using metadata cache:
A form has this field: 
(`'constraints' => new Valid(),` shouldn't be there, but still, it can happen)
```
       $builder->add('email', EmailType::class, [
            'constraints' => new Valid(),
            'label'       => 'sylius.form.customer.email',
        ]);
```
When submitting the form, you get a misleading exception:
`Cache key "me@hotmail.co.uk" contains reserved characters {}()/\@:" at /vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php line 149`

That's because `validateObject` line 349 is making this call:
`$classMetadata = $this->metadataFactory->getMetadataFor('whatever@hotmail.co.uk');`
Therefore `CacheItem:InvalidArgumentException` is being thrown before `UnsupportedMetadataException`.

Fix was easy, but finding the issue was quite painful, would this be considered a bug? 

If yes I could work on a patch for it.

**Comment by gonzalovilaseca** [comment]
Ping

**Comment by xabbuh** [comment]
@gonzalovilaseca Please apologise that we did not look earlier into your issue. Are you able to provide a small project that allows to reproduce your issue?

**Comment by gonzalovilaseca** [comment]
Sure, give me a few days and I'll provide it.

**Comment by HeahDude** [comment]
Hello @gonzalovilaseca.

Seems expected to me. `Valid` constraint should be used on traversable data like arrays or objects, not be used for a scalar such an email string in your case.

**Comment by xabbuh** [comment]
I think @HeahDude is right here. So I am going to close here.

**Comment by gonzalovilaseca** [comment]
Of course he is right, I mentioned it in my initial description, but the error message is misleading and the code doesn't cope with exceptions on the cache engine.
