### ISSUE TITLE
CsvEncoder does not consider context

### ISSUE THREAD

**Issue by SmokeyBrandie** [symfony/symfony#23278]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.4 

CsvEncoder class seems to not consider context.
This leads to "circular reference" error on encoding since Groups Annotaton are not processed.

Example:

```
$serializer = new Serializer([new ObjectNormalizer()], [new CsvEncoder()]);
$data = $serializer->encode($items, 'csv', array('groups' => array('export')));
```

The entitiy has only one field with the annotation "groups":

```
/**
 * @var string
 *
 * @ORM\Column(name="title", type="string", length=255)
 * @Groups({"export"})
 * @Assert\NotNull()  
 */
private $title;
```

As far as I can see, the `CsvEncoder `Class `Symfony\Component\Serializer\Encoder\CsvEncoder` does not consider the `$context` at all.

Even though the method  `public function encode($data, $format, array $context = array())` defines it, `$context` is nowhere used in the method.

**Comment by ogizanagi** [comment]
Context options acting on object properties are used by normalizers (here the [AbstractNormalizer](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L35)), not encoders. Encoders and their options only are about the output format.

Did you enabled annotations in the [`framework.serializer`](https://symfony.com/doc/current/serializer.html#using-serialization-groups-annotations) config ?

**Comment by SmokeyBrandie** [comment]
Thank you!
I misunderstood the process of serializing. Although its perfectly described in doc: https://symfony.com/doc/current/components/serializer.html

Here is how it works for me:
```
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$normalizer = new ObjectNormalizer($classMetadataFactory);
$serializer = new Serializer([$normalizer], [new CsvEncoder($this->getParameter('csv_delimiter'))]);
$csv = $serializer->serialize($items, 'csv', array('groups' => array('export')));
//send to client and add BOM to let excel recognize it as utf8
return new JsonResponse("\xEF\xBB\xBF" . $csv);
```
But there are still two unanswered questions for me:

1. Why does the `normalize `method take `$format`  parameter? According to the doc mentioned above the normalizer always results in array as "man in the middle" format
2. Is there a way to order the encoded fields? I'd like to generate an export as csv and to be able to define the fields ordering would be cool.

Thank you!

**Comment by backbone87** [comment]
> Why does the normalizemethod take $format parameter? According to the doc mentioned above the normalizer always results in array as "man in the middle" format

some normalizers like api-platforms normalizer for json-ld need it, because json-ld needs to be normalized differently

> Is there a way to order the encoded fields? I'd like to generate an export as csv and to be able to define the fields ordering would be cool.

that would be a new ticket


i think this can be closed
