### ISSUE TITLE
Custom Validators with aliases ClassNotFoundException

### ISSUE THREAD

**Issue by cmsanche** [symfony/symfony#23270]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

I'm getting a ClassNotFoundException when using a custom Validator.

`
Attempted to load class "entity_validator" from the global namespace.
Did you forget a "use" statement?
`

I tracked the error down to the getInstance function of the ConstraintValidatorFactory class.
It's assuming that $constraint->validatedBy() will return a classname, but this is not the case if validatedBy has been overwritten to return an alias.

    $this->validator = Validation::createValidator();
    $violations = $this->validator->validate($entity, array(new ValidEntity());

vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorFactory.php

    /**
     * {@inheritdoc}
     */
    public function getInstance(Constraint $constraint)
    {
        $className = $constraint->validatedBy();

        if (!isset($this->validators[$className])) {
            $this->validators[$className] = 'validator.expression' === $className
                ? new ExpressionValidator()
                : new $className();
        }

        return $this->validators[$className];
    }

**Comment by xabbuh** [comment]
In this case you have to use the `ConstraintValidatorFactory` from the FrameworkBundle (or the [`ContainerConstraintValidatorFactory`](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Validator/ContainerConstraintValidatorFactory.php) from the Validator component if you use Symfony 3.3) which is able to [fetch the constraint validator from the service container](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/Validator/ConstraintValidatorFactory.php#L79).

Closing here as this is no bug. Thank you for understanding.
