### ISSUE TITLE
[Workflow] Announcing doesn't work as advertised

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#23275]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

[Documentation](http://symfony.com/doc/current/workflow/usage.html#using-events) lists these events:
- workflow.announce
- workflow.[workflow name].announce
- workflow.[workflow name].announce.[transition name]

But in reality, [only last one is dispatched](https://github.com/symfony/symfony/blob/0a084ddd208d43436e1430e7a4e7243ee196be11/src/Symfony/Component/Workflow/Workflow.php#L304). 

I don't know if this is a bug in code or documentation.

**Comment by stof** [comment]
I would consider it a bug in the code, as this is inconsistent with all other events we dispatch /cc @lyrixx

**Comment by ostrolucky** [comment]
If it's confirmed that it's bug in code, please let me fix it myself

**Comment by xabbuh** [comment]
Looks like a bug to me too.

**Comment by Nyholm** [comment]
I will look into this today.
