### ISSUE TITLE
[Stopwatch] Add a reset method

### ISSUE THREAD

**Issue by jmgq** [symfony/symfony#23284]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Allow the Stopwatch to be reset to its original state, deleting all the data measured so far, just as an actual stopwatch.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #23285.
