### ISSUE TITLE
DateFormatter wrongly named file bug

### ISSUE THREAD

**Issue by finkbg** [symfony/symfony#23304]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

Typo in filename:

>  (1/1) ClassNotFoundException
> 
> Attempted to load class "TimezoneTransformer" from namespace "Symfony\Component\Intl\DateFormatter\DateFormat".
> Did you forget a "use" statement for another namespace?

The .php file is named Time**Z**oneTransformer.php, although the class inside is "TimezoneTransformer"

**Comment by e-moe** [comment]
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Intl/DateFormatter/DateFormat/TimezoneTransformer.php

File name and class name inside is equals. @finkbg could you pls explain your point?

**Comment by finkbg** [comment]
They are not in a few of  our systems - 1 production and 2 dev. Might be an issue with us.

**Comment by finkbg** [comment]
I created a new project and indeed the file is correctly named. Definitely an issue with us.
