### ISSUE TITLE
Support has/was/need method as getters.

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#23314]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | probably
| RFC?             | ?
| Symfony version  | ?

What about adding support for `has`/`was`/`need` and etc getters in serializer?
[GetSetMethodNormalizer:: isGetMethod](https://github.com/symfony/symfony/blob/0896b02be073b8fa60fe6e8b3cf5d4f81b748bf8/src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php#L75-L94)

FYI, JMS serializer had already [supported](https://github.com/schmittjoh/serializer/blob/d4a7ae2647b136a6512959c693108c5da6ca6fcc/src/Metadata/PropertyMetadata.php#L67-L68) `has`.

**Comment by stof** [comment]
-1 for `was` and `need`, which are not supported anywhere in Symfony or Twig for accessors.

However, `has` would make sense.

Note that `has` is already supported by the ObjectNormalizer, as it uses the PropertyAccess component.

**Comment by Aliance** [comment]
I agree, `has` is my favorite, others were proposed for discussion.

---

Is it BC break? What branch should be used?

**Comment by ro0NL** [comment]
Should be a new feature for 3.4, i guess.
