### ISSUE TITLE
[Filesystem] fileperms(): stat failed

### ISSUE THREAD

**Issue by axzx** [symfony/symfony#23312]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

My code:
```
$fs = new \Symfony\Component\Filesystem\Filesystem();
$fs->copy('http://lorempixel.com/900/900/', 'var/cache/image.jpg');
```

I got a warning message:

09:40:03 DEBUG     [php] Warning: fileperms(): stat failed for http://lorempixel.com/900/900/
[
  "exception" => Symfony\Component\Debug\Exception\SilencedErrorContext {
    -severity: E_WARNING,
    trace: {
      /home/project/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:72: {
        : // Like `cp`, preserve executable permission bits,
        : @chmod($targetFile, fileperms($targetFile) | (fileperms($originFile) & 0111));,
        : 
      }
    }
  }
]

**Comment by xabbuh** [comment]
Can you please give #23340 a try?

**Comment by axzx** [comment]
I copied your code and paste it into Symfony 3.3.2.
Works well, no longer displays a warning.

**Comment by nicolas-grekas** [comment]
there is no issue: that line is at DEBUG level, reporting a SilencedErrorContext - which means everything is fine, that's just a log line!

**Comment by axzx** [comment]
@nicolas-grekas But annoys when loading DataFixtures

**Comment by nicolas-grekas** [comment]
OK, see #23398
