### ISSUE TITLE
Do not validate null values in UserPassword\UniqueEntity validators

### ISSUE THREAD

**Issue by szymach** [symfony/symfony#23319]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | Checked on 3.2, I assume it is for 3.* in general

Hello, 
I have ran into an issue when using the `Symfony\Component\Security\Core\Validator\Constraints\UserPassword` validator and PHP 7.1 - if the field value is empty (a null), the validator breaks on [this](https://github.com/symfony/security-core/blob/3.2/Encoder/BasePasswordEncoder.php#L84) line with a warning `hash_equals(): Expected user_string to be a string, null given`. 

Usually validators simply check the value for a null and return if found, but here it just passes it on further and allows it to break. Same goes for `Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator` and it requires me to overwrite these classes and manually add a check for null. I can make a PR fixing this, assuming everyone is fine with this change.

**Comment by xabbuh** [comment]
This looks indeed like an issue to me.

**Comment by Hanmac** [comment]
i think the validators should ignore null, and because that can be validated later with the NotNull one.

**Comment by xabbuh** [comment]
This should be fixed when #23341 gets merged.
