### ISSUE TITLE
Bug when using pdo driver in Symfony/cache

### ISSUE THREAD

**Issue by zhouyl** [symfony/symfony#23313]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all version

A error encountered when managing cache with pdo:：

    [2017-06-28 15:29:27][cache][WARNING]: Failed to fetch key "{key}" {"key":"xfoo","exception":"[object] (PDOException(code: HY093): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens at ~/vendor/symfony/cache/Traits/PdoTrait.php:173)"} []

It needs to be modified in Traits/PdoTrait.php(This bug could be found in ALL versions of symfony/cache):

https://github.com/symfony/cache/blob/master/Traits/PdoTrait.php#L173
https://github.com/symfony/cache/blob/3.2/Adapter/PdoAdapter.php#L198 

```
diff --git a/Traits/PdoTrait.php b/Traits/PdoTrait.php
--- a/Traits/PdoTrait.php
+++ b/Traits/PdoTrait.php
@@ -170,7 +170,7 @@ trait PdoTrait
             foreach ($expired as $id) {
                 $stmt->bindValue(++$i, $id);
             }
-            $stmt->execute($expired);
+            $stmt->execute();
         }
     }
```

**Comment by dmaicher** [comment]
Which database are you using? PostgreSQL? Seems mysql and sqlite are not complaining about it because tests are passing with both :yum: 

But anyway I can confirm that the argument to `->execute` should be omitted as the parameters are bound in the loop above.

@zhouyl maybe you want to create a PR to fix it? :blush:

**Comment by zhouyl** [comment]
@dmaicher

I'm using mysql, you need to set a logger to catch the exception

```
LoggerAwareTrait::setLogger(Psr\Log\LoggerInterface $logger)
```

**Comment by dmaicher** [comment]
@zhouyl yeah thx I edited my comment as I also figured that out :wink:

**Comment by stof** [comment]
@nicolas-grekas looks like some test is missing (or broken) in the shared cache testsuite

**Comment by dmaicher** [comment]
@stof @nicolas-grekas actually makes sense that this internal detail of the `PdoAdapter` is not covered by the general cache testsuite.

Basically there was no test for the cleanup being done when fetching an expired item. So the cache functionality itself was not broken.

I fixed the issue and added a separate test case here: https://github.com/symfony/symfony/pull/23326
