### ISSUE TITLE
json_login is ignored

### ISSUE THREAD

**Issue by JuliusKoronci** [symfony/symfony#23331]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.3

Hi, I am not sure if this belongs here..but I and some of my friends tried to test the new json_login options with a clean Symfony project following the documentation but none of us managed to get it working. 

security.yml

security:
providers:
    db_provider:
        entity:
            class: IgsemAuthBundle:User
            property: email
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_USER:        IS_AUTHENTICATED_ANONYMOUSLY
encoders:
    Igsem\AuthBundle\Entity\User:
        algorithm: bcrypt
firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
    main:
        anonymous: ~
        provider: db_provider
        json_login:
            check_path: check
access_control:
    - { path: ^/secure, roles: ROLE_ADMIN }

SecurityController.php

 /**
 * @Route("/check", name="check")
 */
public function checkAction(Request $request, AuthenticationUtils $authUtils)
{
}

I tried multiple variations of the configuration and it always fails with an error saying the controller must return a response and the firewall just ignores the json_login.

I am not sure if I missed something in the documentation or the documentation is missing some steps or if it is a bug..so sorry for spamming if my mistake :)

Thanks a lot

This is my first ticket so if it is not filled in correctly I do apologise

**Comment by chalasr** [comment]
`json_login` isn't ignored, if you look at your logs you should see
> [2017-07-01 12:09:19] security.INFO: User has been authenticated successfully. {"username":"user"} []

The default behavior being to let the request continue if no authentication success handler has been defined, hence your controller is reached. Currently, If you add a `UserInterface $user` argument to the check action, you'll get the user.

What you need is to add an authentication success handler which sets the response (define it as a service, make it implement `AuthenticationSuccessHandlerInterface`, and set `the json_login.success_handler` option with the service id) or just return the response you want from your `check` action.

**Comment by JuliusKoronci** [comment]
Thanks I though I had missed something..this although is really not evident from the docs..which also suggest to use an empty controller as a dummy placeholder for the route without any success_handler..so if you just really follow the docs this is very hard to figure out. I am closing the ticket as I moved to LexikJWTAuthBundle but I believe it would be nice to mention this in the tutorial :)

thanks

**Comment by chalasr** [comment]
You're right, this wasn't the original behavior and we forgot to update the docs accordingly
