### ISSUE TITLE
[Cache] TagAwareAdapter does not invalidate and misbehave with same item/tag key

### ISSUE THREAD

**Issue by robertodormepoco** [symfony/symfony#23335]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.9

Using the [TagAwareAdapter](https://github.com/symfony/symfony/blob/v3.2.9/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php) with the Redis adapter (but i think it applies to any adapter), i was unable to invalidate my chached items, the issue is at [this line](https://github.com/symfony/symfony/blob/v3.2.9/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L308) the composed key is wrongly ordered, causing the code to return everytime the version value 0, though after fixing the issue i saw that while using the same key for the CacheItem and for one of the former tags the stored infos used by the adapter to understand what's the current version of the item are malformed due to the premises.

```
$item = $cache->getItem('cached_data_1234_suffix');
$item->tag(['cached_data_1234', 'cached_data_1234_suffix']);
```

i.e. 
```
GET "project_prefix:\x00tags\x00cached_data_1234_suffix"
"a:2:{s:24:\"x00cached_data_1234\";i:0;s:27:\"x00cached_data_1234_suffix\";a:2:{s:24:\"x00cached_data_1234\";i:0;s:27:\"x00cached_data_1234_suffix\";i:0;}}"
```

instead of

```
GET "project_prefix:\x00tags\x00cached_data_1234_suffix"
"a:1:{s:24:\"cached_data_1234\";i:3;}"
```

**Comment by nicolas-grekas** [comment]
I don't understand your bug description. The ordering you're talking about is right:
`self::TAGS_PREFIX.$key` is the cache key where all tags related to item `$key` are stored
and `$tag.self::TAGS_PREFIX` is the cache key where the version of tag `$tag` is stored.

Can you please share a small script that misbehaves?

**Comment by robertodormepoco** [comment]
Sorry for bothering you, i've done new tests and there was something else that was not working; the mentioned code works just fine.
