### ISSUE TITLE
Contact form - no translation found warning

### ISSUE THREAD

**Issue by devkbsc** [symfony/symfony#23359]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.x

Hello,
I am novice in symfony. The swift mailer is not working in my contact form.

This is my mail configuration

```yaml
#Mail setting
    mailer_transport: smtp
    mailer_host: mail.smtp2go.com
    mailer_user: myemail@gmail.com
    mailer_password: abscd
```

And test my mail through cmd, it send a mail by using 

```
php bin/console swiftmailer:email:send 
```

The mail was successfully received. And then i used swiftmailer in my form. But it's not working. It displayed the "No translation found" for all the fieldtype in the form. 

**My controller** 

```php
public function indexAction(Request $request)
    {
        $contact_form = $this->createFormBuilder()
            ->add('lastname', TextType::class, array('label'=> 'nom', 'attr' => array('class' => 'form-control', 'style' => 'margin-bottom:15px')))
            ->add('firstname', TextType::class, array('label'=> 'prenom', 'attr' => array('class' => 'form-control', 'style' => 'margin-bottom:15px')))
            ->add('email', EmailType::class, array('label'=> 'email','attr' => array('class' => 'form-control', 'style' => 'margin-bottom:15px')))
            ->add('subject', TextType::class, array('label'=> 'subjet','attr' => array('class' => 'form-control', 'style' => 'margin-bottom:15px')))
            ->add('message', TextareaType::class, array('label'=> 'message','attr' => array('class' => 'form-control')))
            ->add('send', SubmitType::class, array('label'=> 'submit', 'attr' => array('class' => 'btn btn-primary', 'style' => 'margin-top:15px')))
            ->getForm();

        $contact_form->handleRequest($request);
        if($contact_form->isSubmitted() && $contact_form->isValid()){

            $data = $contact_form->getData();
            dump($data);

            $message = \Swift_Message::newInstance()
                ->setSubject("Contact Form Submission")
                ->setFrom($data['subject'])
                ->setTo('localtestmain@gmail.com')
                ->setBody(
                    $contact_form->getData()['message'],'text/plain'
                );
            $this->get('mailer')->send($message);
        }

        return $this->render('BlogBundle:Contact:index.html.twig',[ 'contact_form'=> $contact_form->createView()]);
    }
```

```twig
{% extends '::base.html.twig' %}
{% block title %}Contact{% endblock %}

{% block body %}
    Contact us!
    {{ form(contact_form) }}
{% endblock %}
```

My translation setting in the config.yml is here

```yaml
parameters:
    locale: fr
framework:
    translator:      { fallbacks: ["%locale%"] }
```

The warning message in the dashboard looks like this 

```
WARNING
15:13:50
translation	Translation not found.
Hide context
[▼
  "id" => "nom"
  "domain" => "messages"
  "locale" => "fr"
]
WARNING
15:13:50
translation	Translation not found.
Hide context
[▼
  "id" => "prenom"
  "domain" => "messages"
  "locale" => "fr"
]
WARNING
15:13:50
translation	Translation not found.
Hide context
[▼
  "id" => "email"
  "domain" => "messages"
  "locale" => "fr"
]
```

**Comment by javiereguiluz** [comment]
The most common reason why this happens is this one ([explained here](https://symfony.com/doc/current/translation.html#translation-resource-locations)):

> Each time you create a new translation resource (or install a bundle that includes a translation resource), be sure to clear your cache so that Symfony can discover the new translation resources:
>
> php bin/console cache:clear

The second reason why this may happen is that the translation file doesn't contain the translation of those missing strings. Check that this file contains at least this translation:

```yaml
# app/Resources/translations/messages.fr.yml
prenom: First Name
nom: Last Name
email: Email
```

---

If none of those solutions work for you, please use any of the support channels showed here: https://symfony.com/support to ask this question. The reason is that we only use the GitHub repo to discuss about bugs and features of Symfony, but not to provide support. Thanks!

**Comment by devkbsc** [comment]
I tried this file creation app/Resources/translations/messages.fr.yml which was not existed in my symfony directory. I created one. But i couldn't fix the problem.

**Comment by javiereguiluz** [comment]
After you create that file, please remember to execute this command to clear the cache:

> php bin/console cache:clear

If you find any problem after following all the steps explained here: https://symfony.com/doc/current/translation.html  please ask for support in any of these channels: https://symfony.com/support Thanks!

**Comment by japodhidev** [comment]
After following the installation and setup instructions over at [Symfony Translation] (https://symfony.com/doc/current/translation.html). This snippet did the trick for me.
```sh
php bin/console translation:update --dump-messages fr --force
```
You could also try running
```sh
php bin/console debug:translation fr 
```
to display the messages you already defined and haven't used yet. Happy hacking
