### ISSUE TITLE
[DI] Deprecate/remove autowiring "auto-create" Definition functionality

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#23350]
| Q                | A
| ---------------- | -----
| Bug report?      | No
| Feature request? | No
| BC Break report? | no
| RFC?             | No
| Symfony version  | 3.4.0

The current autowiring behavior is:

> If there is not a service whose id exactly matches the type AND there are **0** services in the container that have the type, a new, private, autowired service is auto-registered in the container and used for that argument.

In #22295, @nicolas-grekas proposed removing this. But, we decided not to, because it meant that all services would need to be explicitly wired. But with the PSR-4 service loader, that's not true anymore.

We should deprecate this "auto-registration" functionality from `AutowirePass` (https://github.com/symfony/symfony/blob/d7992dc1b77f098152476e69addef3c303acc638/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L422-L461) and throw an exception in 4.0.

This "auto-registration" in AutowirePass is problematic because we can't apply instanceof to those definitions... which is a bit unexpected. Removing it also simplifies the autowiring logic: there's one less case to explain. I chatted with @dunglas about this already (https://twitter.com/dunglas/status/881557361042894849).

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by dunglas** [comment]
:+1:

**Comment by xabbuh** [comment]
👍

**Comment by stof** [comment]
Yeah, it also creates WTF debugging moments, when you get error messages related to an autocreated services sometimes while you expected your own service: https://github.com/symfony/symfony/issues/23325

👍 from me.

**Comment by fabpot** [comment]
@weaverryan I think you can safely work on a PR :)

**Comment by weaverryan** [comment]
Haha, indeed... except I was hoping someone else would beat me to it ;). But if not, I'll get to it!

**Comment by TomasVotruba** [comment]
This gave me some WTF, so :+1: PSR-4 is just fine
