### ISSUE TITLE
Info of property defined in trait

### ISSUE THREAD

**Issue by max-voloshin** [symfony/symfony#23365]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.9

There is a problem in such case:

```
<?php

use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;

require_once __DIR__ . '/vendor/autoload.php';

trait Foo
{
    /**
     * @var int
     */
    protected $variable = 0;
}

class Bar
{
    use Foo;
}

$extractor = new PhpDocExtractor();
$types = $extractor->getTypes(Bar::class, 'variable');

var_dump($types);
```

Expected: something like:
```
array(1) {
  [0] =>
  class Symfony\Component\PropertyInfo\Type#2 (6) {
    private $builtinType =>
    string(3) "int"
    private $nullable =>
    bool(false)
    private $class =>
    NULL
    private $collection =>
    bool(false)
    private $collectionKeyType =>
    NULL
    private $collectionValueType =>
    NULL
  }
}
```

Actual:
```
NULL
```

As I undestand it is a consequence of `\phpDocumentor\Reflection\ClassReflector::getProperties`  which doesn't resolve property from trait. But I am not sure it should be reported in phpDocumentor project as a bug.

**Comment by nicolas-grekas** [comment]
Please try with a recent version, 3.0.9 is unsupported and the bug may have been fixed already?

**Comment by max-voloshin** [comment]
I've just tested my script with `"symfony/property-info": "dev-master"` and `"phpdocumentor/reflection": "*"` and can confirm that this problem is already resolved.

@nicolas-grekas, thank you for the tip!
