### ISSUE TITLE
Symfony 3.3.3 asset:install file copy broken

### ISSUE THREAD

**Issue by Koalabaerchen** [symfony/symfony#23373]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

Upgrading Symfony to 3.3.3 (from 3.3.2) breaks the asset install at the post-install/post-update of composer.
This only happens if it copies the files (e.g. on Windows). Symlink creation works fine.

Edit: To clarify it's totally fine on systems that actually support symlinks like Linux.

[error.txt](https://github.com/symfony/symfony/files/1121474/error.txt)

**Comment by R-Develop** [comment]
Same problem on the 2.8 branch, verified on multiple projects.

**Comment by for-creator** [comment]
Symfony 3.3.3 on Windows 7 x64, php 7. bin/sonsole assets:install don't work: no symlink, no hard-copy with no errors.

**Comment by Zeichen32** [comment]
Same problem after upgrading to 3.3.3

**Comment by 1ed** [comment]
Could you please check if https://github.com/symfony/symfony/pull/23378 fixes your issue?

**Comment by Gemorroj** [comment]
need hotfix 😞

**Comment by Oopas** [comment]
Same, broken with Symfony 3.3.3 on windows...

**Comment by xabbuh** [comment]
Did someone of you check if #23378 fixes the issue?

**Comment by Oopas** [comment]
I get this error with the fix.

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined variable: filesystem`

**Comment by 1ed** [comment]
@Oopas write `$this->filesystem` instead

**Comment by Oopas** [comment]
@1ed Oh yeah... i'm dumb haha... It works ! Thank you very much.

**Comment by magician7** [comment]
Windows 10, PHP 7.0.19, no symlink, no copyfile, no errors.

**Comment by decebaldecebal** [comment]
I also have the same problem, I thought it was something to do with my PC.
Windows 10 x64, PHP 7.1 (XAMPP), no symlink and no errors, it worked fine before.

**Comment by fabpot** [comment]
Can anyone test the fix in #23378? That would really help us.

**Comment by fabpot** [comment]
I've just merged 2.7 onto 2.8, 3.2, and 3.3, so testing is much easier. You "just" need to use the dev version of `symfony/framework-bundle` in your `composer.json`.

**Comment by koddistortion** [comment]
The fix from #23378 works in my 3.3.3 installation on Windows with absolute symlinks. They are created fine and no longer removed.

**Comment by nea** [comment]
Hi @fabpot 

Just changed the $dirsToRemove and $validAssetDirs based on #23378 and it works on Windows with Symlinks.


Cheers

**Comment by fabpot** [comment]
Thank you @nea @koddistortion

**Comment by 1ed** [comment]
Just to clarify this issue is nothing to do with symlinks. The problem was that the Filesystem iterator works differently on windows (https://bugs.php.net/bug.php?id=48547) as it uses `\` by default as a directory separator so the condition never met and everything was deleted in the `web/bundles` directory.

**Comment by fritzmg** [comment]
Fixed in `symfony/symfony` `3.3.4`

**Comment by R-Develop** [comment]
LTS branches too, thanks very much!
