### ISSUE TITLE
Defining service with id "Foo" and using it as "Foo" triggers deprecation warning

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony#23379]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi,

When I define a service with the service id `Foo` and then use it by getting the service `Foo` I get the warning:
> Service identifiers will be made case sensitive in Symfony 4.0. Using "foo" instead of "Foo" is deprecated since version 3.3

This is strange because I never used `foo`. 

It feels like the service IDs should be entirely in lowercase. I do not see this in the PSR11. Is this something that will be in Symfony 4?

Thanks

**Comment by xabbuh** [comment]
Can you provide a minimal project making it possible to reproduce your issue?

**Comment by magnetik** [comment]
Nevermind, I was not using the correct ID. It works fine.

Sorry about that.
