### ISSUE TITLE
Error when scaffolding new Symfony release (3.3.3)

### ISSUE THREAD

**Issue by nioperas06** [symfony/symfony#23382]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

I have this error when scaffolding new symfony project (3.3.3): 

![screenshot from 2017-07-04 12-58-45](https://user-images.githubusercontent.com/11293401/27829243-8dcc680e-60b8-11e7-82d3-4a31e684120c.png)

Thank you for help !

**Comment by nioperas06** [comment]
Another error when generating new bundle with CLI. 
![screenshot from 2017-07-04 13-16-54](https://user-images.githubusercontent.com/11293401/27829800-4e39b89c-60bb-11e7-84b2-e008c4a39717.png)

**Comment by SaidMarar** [comment]
+1 after fresh install i had same problem

**Comment by 1ed** [comment]
Fixed in https://github.com/symfony/symfony-standard/commit/c4c2ef5d383fd0a39adbb1eb5c8840a412fd4335
