### ISSUE TITLE
security.role_hierarchy -> getMap

### ISSUE THREAD

**Issue by hounded** [symfony/symfony#23396]
You use to be able to get a list of roles security.role_hierarchy.roles
As far as I can tell that no longer exists 

would it be possible to have 

```php
public function getMap() {
       return $this->map;
}
```

in Symfony\Component\Security\Core\Role\RoleHierarchy.php;

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

**Comment by nicolas-grekas** [comment]
How did you use to get that list?

**Comment by hounded** [comment]
I believe it was along the lines of 
```php
$this->get('security.role_hierarchy.roles')
```
based of the answer provided below
https://stackoverflow.com/questions/8928085/how-to-retrieve-full-role-hierarchy-in-symfony

**Comment by xabbuh** [comment]
`security.role_hierarchy.roles` is a parameter (take another look at the answer, it uses `getParameter()` and not `get()`) and that did not change.
