### ISSUE TITLE
assets:install deleting all web/bundles folders at end of process on Windows

### ISSUE THREAD

**Issue by picks44** [symfony/symfony#23399]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.23

Since my upgrade to 2.8.23 yesterday, the assets:install command works fine (copying all the bundles assets in `web/bundles`) but at the end of the process, all the folders of the `web/bundles` folder are deleted.
I'm on Windows 7.

Any clue? I never faced this issue before.

**Comment by xabbuh** [comment]
This should be fixed by #23378.

**Comment by picks44** [comment]
Alright, thanks @xabbuh
