### ISSUE TITLE
After upgrade to 3.3 error: Undefined class constant 'HEADER_X_FORWARDED_FOR'

### ISSUE THREAD

**Issue by Snodvod** [symfony/symfony#23400]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.3

After updating to symfony 3.3 I get this error: 

```Fatal error: Undefined class constant 'HEADER_X_FORWARDED_FOR' in /var/www/***/***/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php on line 122```

This only happens when I visit the site in production environment. When using app_dev.php this error is not thrown...

Any ideas on this?

**Comment by szymach** [comment]
Remove `bootstrap.cache.php` and regenerate it.

**Comment by Snodvod** [comment]
Oh great, thanks a lot!!
