### ISSUE TITLE
Doctrine bigint from int to string

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#23406]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.10

Hi :)

This PR is a huge BC : https://github.com/symfony/symfony/pull/22988/files

Every PHP 7 return type are broken :
```php
public function getId(): int {}
```

Every test with *===* are broken :
```php
if ($id === 1) {}
```

I understand bigint is a problem in PHP, but i don't think this BC is the solution ... All my application is down, and i think i'm not alone ;)

**Comment by dunglas** [comment]
It was a bug since the very beginning. Doctrine explicitly documents bigint as being converted to string.
The mentionned PR does'nt change the behavior. It just fixes the type mismatch (Doctrine will return a string anyway).

**Comment by steevanb** [comment]
Ok, thanks !
