### ISSUE TITLE
assets:install removing bundle directories

### ISSUE THREAD

**Issue by bmadzar** [symfony/symfony#23416]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.11

The change introduced in 3.2.10 (#23195) broke our applications.

We have several Symfony applications that share a `web/bundles` dir. Previously they could coexist happily but now running `assets:install` on one deletes the assets from the others. #23378 does not fix the problem, we basically need `assets:install` to ignore bundles it doesn't know about.

This sort of breaking change should not be introduced in a patch version.

**Comment by 1ed** [comment]
Already fixed in https://github.com/symfony/symfony/pull/23378 and released 3.2.11.

**Comment by bmadzar** [comment]
@1ed I have tried 3.2.11 and the problem exists there as well. My understanding of #23378 is that it only fixes the problem for files, not directories.

**Comment by stof** [comment]
@1ed I don't think the PR you mentionned fixes the case reported here.

@bmadzar the previous behavior was considered as bug, as it would leave broken files around (symlinks pointing to a removed folder for instance). This is why it happened in a patch release.
What is your use case for several applications sharing the same web/bundles folder ? And is it for applications sharing the same vendor folder or no ?

**Comment by 1ed** [comment]
Oh, yes. Sorry I didn't read it through carefully.

**Comment by bmadzar** [comment]
@stof Yes, the applications share the same vendor folder as well. We only have a single public directory on the server.

**Comment by tristanbes** [comment]
It's a **major bc break** for us.
We also have 2 kernels. All assets were published in the same folder.

So we run 
`./sitecon assets:install --smylink web/` for kernel A
`./admincon assets:install --symlink web/` for kernel B

Now, if we run command for `A` then `B` only assets from `Kernel B` are present breaking the application using the kernel `A`

**Comment by mvrhov** [comment]
This is probably also broken for one of our sites if we decide to migrate. As we also have the same setup as @tristanbes

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/24216#issuecomment-336179635
Someone needs to take over if anything should be done.
