### ISSUE TITLE
Symfony Profiler performance bogged down by deprecation notices

### ISSUE THREAD

**Issue by szymach** [symfony/symfony#23415]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.x

Hello,
The recent fix to Profiler has indeed reduced the size of generated files, but in my case the performance is still very slow. From what I gather, it has to do with the fact that I have around 600-700 depreciation notices on list pages in my CMS (vendor library dependent on Twig, can not upgrade unfortunately). Now I am not sure this is something that can or should be fixed on your side, but gathering the depreciation notices does have a big hit on app performance. Thanks in advance for feedback.

**Comment by nicolas-grekas** [comment]
can you try this patch, does it make things better?
```php
--- a/src/Symfony/Component/Debug/ErrorHandler.php
+++ b/src/Symfony/Component/Debug/ErrorHandler.php
@@ -414,7 +414,7 @@ class ErrorHandler
                 $errorAsException = self::$silencedErrorCache[$message];
                 ++$errorAsException->count;
             } else {
-                $lightTrace = $this->tracedErrors & $type ? $this->cleanTrace(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3), $type, $file, $line, false) : array();
+                $lightTrace = array();
                 $errorAsException = new SilencedErrorContext($type, $file, $line, $lightTrace);
             }
 
```

**Comment by szymach** [comment]
I am sorry, but it does not. I forcefully removed cached and dumped Composer autoload, but it is still as slow as before.

**Comment by nicolas-grekas** [comment]
can you share a blackfire profile please? just send me the URL by email if it contains anything private. thanks

**Comment by szymach** [comment]
I will, but not right now, since I do not event have Blackfire installed on this PC and I will be finishing work soon. I will generate a report once I get home this evening.

**Comment by szymach** [comment]
[Here's](https://blackfire.io/profiles/27ecae64-e6c8-42a0-837c-3736c9cb0007/graph) my report.

**Comment by szymach** [comment]
Hey, was the report any help? Do you need more?

**Comment by nicolas-grekas** [comment]
@szymach can you please try this path, any better?
```diff
--- a/src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php
+++ b/src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php
@@ -102,7 +102,7 @@ class ExceptionCaster
         }
 
         unset($a[$sPrefix.'file'], $a[$sPrefix.'line'], $a[$sPrefix.'trace']);
-        $a[Caster::PREFIX_VIRTUAL.'trace'] = new TraceStub($trace);
+        $a[Caster::PREFIX_VIRTUAL.'trace'] = new TraceStub($trace, false);
 
         return $a;
     }
```

**Comment by szymach** [comment]
Hey, I am sorry but no. New [report](https://blackfire.io/profiles/849f2182-4d6e-40d1-9128-81c57813447a/graph).

**Comment by nicolas-grekas** [comment]
Can you please try #23465?

**Comment by szymach** [comment]
Hello,
Just reporting that after upgrading to 3.3.5 everything works fine. Thanks again :)
