### ISSUE TITLE
Calling AbstractAdapter::isSupported on array in Finder.

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#23418]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | ?
| Symfony version  | 2.8.*

When I look at [Finder::searchInDirectory](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Finder/Finder.php#L769-L769) method, I saw calling `AbstractAdapter::isSupported` method on array element (`$this->adapters`), not object. Can you explain for me: is it a bug or I do not understand something?

**Comment by 1ed** [comment]
Nothing is wrong with that. `$this->adapter` is an array of arrays like `['adapter' => $adapter, 'priority' => $priority, 'selected' => false]` and `$adapter` is an instance of ` Symfony\Component\Finder\Adapter\AdapterInterface`. See [Finder.php#L98-L111](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Finder/Finder.php#L98-L111).

**Comment by Aliance** [comment]
Ok, I understand. Thanks.
