### ISSUE TITLE
FileBag set method - mistake on if statement

### ISSUE THREAD

**Issue by alexapetrei** [symfony/symfony#23425]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

In vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\FileBag.php

**Comment by Seb33300** [comment]
I think he is talking about this line:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/FileBag.php#L50

**Comment by iltar** [comment]
So what's the mistake? Please clarify this in your issue, otherwise there's nothing that can be done with it.

**Comment by alexapetrei** [comment]
the mistake is that you are checking if the parameter is array and instance in the same time. instead of && should be || . "or" instead of "and"

**Comment by xabbuh** [comment]
No, the value can be either an array or an instance of `UploadedFile`. And only if it's neither of them the exception has to be thrown. Using "or" would mean that the exception were thrown for every call of this method.
