### ISSUE TITLE
[WebProfiler] Exceptions panel have an empty exception summary

### ISSUE THREAD

**Issue by romain-pierre** [symfony/symfony#23433]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

Hi all, the exception summary seem to be hidden by a wrong css rule.

![screen shot 2017-07-06 at 14 09 34](https://user-images.githubusercontent.com/20155356/27910338-062654f2-6255-11e7-8c3d-40274bd74212.png)

This is the HTML part that is not showed. I will fix that if nobody want to do :-)

```html
<div class="exception-summary">
    <div class="exception-metadata">
        <div class="container">
            <h2 class="exception-hierarchy">
                                <abbr title="Exception">Exception</abbr>
            </h2>
            <h2 class="exception-http">
                HTTP 500 <small>Internal Server Error</small>
            </h2>
        </div>
    </div>
    </div>
```

**Comment by javiereguiluz** [comment]
I can't reproduce this. I've just tested it in Symfony 3.3.5 and I can see the exception message:

![exception-message](https://user-images.githubusercontent.com/73419/28354526-89d5296c-6c60-11e7-9d8b-121617d5d0f6.png)

**Comment by romain-pierre** [comment]
The issue appear when there is no message in the exception. And it may be the same on the error page (the gosht icon disappear):

![screen shot 2017-07-19 at 10 17 56](https://user-images.githubusercontent.com/20155356/28357449-c28aa93e-6c6b-11e7-84ab-ec62e521b661.png)

![screen shot 2017-07-19 at 10 18 52](https://user-images.githubusercontent.com/20155356/28357458-c707d1e4-6c6b-11e7-9ac8-181cc3a6439f.png)

Why not using the exception class name when there is no message to display?

**Comment by javiereguiluz** [comment]
> Why not using the exception class name when there is no message to display?

We already display that in two places of the page:

![exception-1](https://user-images.githubusercontent.com/73419/28359346-260c8a76-6c72-11e7-832a-25408b8f241e.png)

If we also display it as the exception message, it would be too repetitive:

![exception-2](https://user-images.githubusercontent.com/73419/28359361-2ec70358-6c72-11e7-91c5-487834e6b9a9.png)

That's why in #23584 we're proposing another solution for this. Thanks!

**Comment by romain-pierre** [comment]
Ok, so it's perfect. Simply hide completely the message box as in your PR should be great!
