### ISSUE TITLE
Generated bundle are not autoloaded

### ISSUE THREAD

**Issue by Nicosonic** [symfony/symfony#23439]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | >= 3.3.3

When generating a bundle with `bin/console generate:bundle`  the bundle is not autoloaded automatically anymore. It gives the following error when trying to load a page :

> Attempted to load class "NameBundle" from namespace "NameBundle".
Did you forget a "use" statement for another namespace?

This used to worked in previous versions. At least for the 3.2.*

To get it works on 3.3*, I used this workaround in the composer.json : 
```
"psr-4": {
        "AppBundle\\": "src/AppBundle",
        "OC\\": "src/OC"
},
```

And played this command on the server : 
```composer dump-autoload```

**Comment by stof** [comment]
this should be reported to SensioGeneratorBundle, as the bundle generator is not part of Symfony itself but of a third-party bundle.

**Comment by guilliamxavier** [comment]
For the record: re-submitted there as https://github.com/sensiolabs/SensioGeneratorBundle/issues/555
