### ISSUE TITLE
Cannot load Workflow configured with config.yml

### ISSUE THREAD

**Issue by OskHa** [symfony/symfony#23436]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

After following the docs from http://symfony.com/doc/current/workflow/state-machines.html, workflows are not working for me with the config usage.

Code
```
$stateMachine = $this->get('state_machine.pull_request');
```

Exception:
```
You have requested a non-existent service "state_machine.pull_request".
```

if i do it programmatically everything is working.

```
$definition = new Definition(
    ['draft', 'review', 'rejected', 'published'],
    [
        new Transition('to_review', 'draft', 'review'),
        new Transition('publish', 'review', 'published'),
        new Transition('reject', 'review', 'rejected'),
    ],
    'draft'
);

$marking = new SingleStateMarkingStore('state');
$workflow = new Workflow($definition, $marking);
```

**Comment by OskHa** [comment]
Just checked the same setup under fresh symfony install. same behaviour.
Maybe i just miss something? From checking the component theres no need to register any bundle under AppKernel.

**Comment by xabbuh** [comment]
Can you create a small example project that makes it possible to easily reproduce your issue?

**Comment by ostrolucky** [comment]
It seems you use code for retrieving service from this doc http://symfony.com/doc/current/workflow/state-machines.html, but use workflow definition from this doc http://symfony.com/doc/current/workflow/usage.html

Name of the service depends on how did you configured your worklow in config

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. Please leave a comment with more information and we can consider to reopen.
