### ISSUE TITLE
Error: Undefined class constant 'HEADER_X_FORWARDED_FOR'

### ISSUE THREAD

**Issue by yannicka** [symfony/symfony#23430]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

Since upgrade from 3.2 to 3.3, I've the following error on my homepage:

```
Error: Undefined class constant 'HEADER_X_FORWARDED_FOR'
```

Exception: `Symfony\Component\Debug\Exception\FatalErrorException`
From: `in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php (line 122)` : 

```php
// Sub-request object will point to localhost as client ip and real client ip
// will be included into trusted header for client ip
try {
  if (Request::HEADER_X_FORWARDED_FOR & Request::getTrustedHeaderSet()) { // ** THIS LINE (122) **
    $currentXForwardedFor = $request->headers->get('X_FORWARDED_FOR', '');
    $server['HTTP_X_FORWARDED_FOR'] = ($currentXForwardedFor ? $currentXForwardedFor.', ' : '').$request->getClientIp();
```

The problem only occur in `prod` and not in `dev`.

The line that that throws the exception:

```twig
{{ render(controller('NewsBundle:Default:last')) }}
```

The method from the controller:

```php
public function lastAction()
{
    $news = $this->getDoctrine()
        ->getRepository(News::class)
        ->createQueryBuilder('news')
        ->getQuery()
        ->getResult();

    return $this->render('NewsBundle:Default/Partials:last.html.twig', [
        'news_list' => $news,
    ]);
}
```

The problem is not in the query (I've simplified it here), it works on `dev` and I didn't have any problem before.

The problem seems occur in the render of a fragment, but I've no idea why.

[A screenshot](https://framapic.org/erb53FOuQO1P/93p2jIc6Mhbz.png)

**Comment by xabbuh** [comment]
You need to remove your `bootstrap.php.cache` file (see #23400).

**Comment by yannicka** [comment]
Thanks, problem solved.
