### ISSUE TITLE
[RFC] Async event dispatcher support 

### ISSUE THREAD

**Issue by makasim** [symfony/symfony#23441]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | any

I've been working on an [async event dispatcher](https://github.com/php-enqueue/enqueue-dev/tree/master/pkg/async-event-dispatcher) lately and I like to share my results. It works on top of MQ and I believe it could be a great addition to Symfony. I personally think that such a feature should be in the Symfony, besides Laravel [already has this feature in core too](https://laravel.com/docs/5.4/events#queued-event-listeners).

## How it works 

There is [a listener](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncListener.php) which sends events as messages. [A transformer](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/PhpSerializerEventTransformer.php) helps to convert events back and forth. The [consumer processor](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncProcessor.php) calls [async event dispatcher](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncEventDispatcher.php) `dispatch` method with the event it has got from the queue. The dispatcher dispatches only async events and their sub-events. 

To make a listener async in the full stack Symfony application [you have to add](https://github.com/php-enqueue/enqueue-sandbox/blob/master/symfony/app/config/config.yml#L187) `async: true` tag attribute like this: 

```yaml
tags: 
  - { name: 'kernel.event_subscriber', async: true }
```

and you need a consumer command to be run in the background.

## The advantages of my solution

* It works transparently for the client. It can work with any existing event object. No need to implement any special interfaces. Nothing of that kind.
* It can dispatch sync and async events at the same time
* If the code is disabled the `async` tag attribute is ignored and those events are dispatched in the same process.
* It is bound to any MQ implementation or library and based on [queue interfaces](https://github.com/php-enqueue/psr-queue). It was battle tested on eight different types of transport. The queue interfaces could be moved to Symfony or [queue-interop](https://github.com/queue-interop) repo. 

## Outside full stack Symfony app.

It is easy to use outside full stack Symfony application. We have to register a special listener (it sends a message ) to default `dispatcher`:

```php
<?php
use Enqueue\AsyncEventDispatcher\AsyncListener;
use Symfony\Component\EventDispatcher\EventDispatcher;

$asyncListener = new AsyncListener($context, $registry, $eventQueue);

$dispatcher = new EventDispatcher();
$dispatcher->addListener('foo', $asyncListener);
```

and all async listeners to the async dispatcher:

```php
<?php
use Enqueue\AsyncEventDispatcher\AsyncEventDispatcher;
use Symfony\Component\EventDispatcher\GenericEvent;

$asyncDispatcher->addListener('foo', function(GenericEvent $event) {
    echo 'Async: '.$event->getSubject().PHP_EOL;

    $dispatcher->dispatch('bar', new GenericEvent('theBarSubject'));
});
```

The simplest consume script might look like this:

```php
<?php

<?php
while (true) {
    if ($message = $consumer->receive(5000)) {
           $asyncProcessor->process($message, $context);
           $consumer->acknowledge($message);
    }
}
```

The complete working code could be found [here](https://github.com/php-enqueue/enqueue-dev/tree/master/pkg/async-event-dispatcher) and [usage example](https://github.com/php-enqueue/enqueue-sandbox/tree/master/async-event-dispatcher).

What do you think about it? 
Do you think it worth it?

**Comment by unkind** [comment]
> What do you think about it?

Symfony EventDispatcher was designed like hook dispatcher, not "true" event dispatcher. Async processing doesn't make sense for hooks, so it leads to confusion.

**Comment by havvg** [comment]
Imho, this is totally off the business of the event dispatcher. For example, when I got an Event, which is bound to a domain model. When I'm now exchanging the event dispatcher with the async one, it's not transparent. It requires dependencies to make it actually work, e.g. the consumer command, the information transport ("transformers") etc.

We implemented the same stuff with a few 100 lines of code (including tests) & less overhead.

Imho this RFC should be published as an infrastructural bundle with clear dependencies, documentation, rather than putting it into core. Not everything needs to be "core". Imho the Symfony core should focus on stability, performance, security and features for 80%+ projects, not 2% enterprise.

Besides that, I don't think "Async Event Dispatcher" is the right name. It's basically a message queue and should be named as it. An "Async Event Dispatcher" which would be really transparent with the behaviour of the current event dispatcher, would be something like https://gist.github.com/havvg/3852361, with direct control which event is dispatched async. This could be implemented transparently as in-memory queue by moving `addAsyncEvent` logic into `dispatch` making any event async, or by configuration etc. However this is truly transparent.

**Comment by unkind** [comment]
> For example, when I got an Event, which is bound to a domain model. When I'm now exchanging the event dispatcher with the async one, it's not transparent.

I'm not sure I understand this example. When you fire event, you don't care how exactly this thing (event dispatcher, event bus, etc.) will notify event handlers about this event. However, as I said above, Symfony EventDispatcher is not "pure" event dispatcher, it is hook manager that **requires** to have sync event dispatching, because it allows to modify event object and send it back.

On other hand, "pure" event dispatcher/bus is "one way" bus, so it's perfectly fine to have async event handlers, because there is no difference for initiator (the one who executes `$this->eventBus->handle(...)`). Initiator doesn't care what, when and in which order will be notified, because he won't receive any feedback directly anyway.

> Besides that, I don't think "Async Event Dispatcher" is the right name.

It turns out that "Event Dispatcher" is not right name for the Symfony component. :)
https://twitter.com/mathiasverraes/status/665237482326355968, https://twitter.com/mathiasverraes/status/665238383699091456

**Comment by havvg** [comment]
I agree with the naming differences, although in my experience "hook" is not used widely in the PHP world, but it's more like "event" and "messages", respectively. The latter one will be implemented as a message bus, and then you are the point you made: you have decoupled situation.  At least that's my experience in the PHP world on this topic, and be revisiting some implementations around "events" and "messages" it's common sense to some degree. I have also seen many of those implementations to be named "event bus" to make it clear, it's kinda "message bus/queue".

Let the "wrong" name be; it would be even more important to not coin something with a similar name working completely different, and putting something like "it's transparent" into its description - that's my whole point.

**Comment by makasim** [comment]
> Symfony EventDispatcher was designed like hook dispatcher, not "true" event dispatcher. Async processing doesn't make sense for hooks, so it leads to confusion.

IMO it was designed as event dispatcher though in some cases it is used as hook indeed. The async events feature could be enabled per event and you choose what events you want to process asynchronously. For example, you have a real event listener which sends a mail and doesn't communicate with the caller in any way. It is a good candidate for async events.

> Imho, this is totally off the business of the event dispatcher. For example, when I got an Event, which is bound to a domain model. When I'm now exchanging the event dispatcher with the async one, it's not transparent

You do not exchange anything, you still work with the oldie dispatcher. The async events are enabled by adding an async listener (which sends a message).  On per listener basis. 

>  It requires dependencies to make it actually work, e.g. the consumer command, the information transport ("transformers") etc.

My idea is next. Symfony provides a foundation so other 3rd bundles\libraries could build their solutions on top of it. Then developers decides whether they need this feature or not. Everyone could use event dispatcher in sync mode as before.

Of course if you need this feature you'll have to do some extra work. IMO it is not hard to setup a supervisard and put a command to its config. A few hours of work could given you a good performance gain.  

I see it the same way as [lazy services](http://symfony.com/doc/current/service_container/lazy_services.html). Symfony gives us a foundation (contract) and maybe some basic implementation (a filesystem based transport) and we free to use it or not, and we are free to choose from any available MQ transports. 

> Besides that, I don't think "Async Event Dispatcher" is the right name. It's basically a message queue and should be named as it. 

The code I am proposing is about async events and nothing else. It is based on some queue interfaces (contract) which abstracts MQ part. The code does not deal with the queue directly but through the contract.

> However this would be truly transparent.

I might not agree with you here. Your solution requires an explicit change in the client's code (to make sync event async). The client has to call a completly different method which is not part of the disptacher interface by the way. 

My solution does not require anything like that. It uses same interfaces. If the async events feature is not enabled it works as before (sync mode). Only those event listeners which have `async: true` attribute set will be served as async. You can have sync and async listners working toghether at the same time (the feature is enabled per listener). 

> and putting something like "it's transparent" into its description - that's my whole point.

It is transparent to the client. It means you dont have to modify its code every time you want make something async or another way around. That's what I meant by saying "transparent".

**Comment by havvg** [comment]
Just to clarify on the "transparent"; I actually meant, what you mean by transparent:

> This could be implemented transparently as in-memory queue by moving addAsyncEvent logic into dispatch making any event async, or by configuration etc. However this would be truly transparent.

I think `lazy` services are a good example for what I mean. It's configured only (composer.json + attribute) and that's it. It just works™, no cohered implementation required. As you said, your setup require steps to do, and more important: maintain (e.g. supervisord).

I agree with you on the client - the callee of `dispatch`- transparency. But it's not transparent within the system as opposed to e.g. `lazy` services.

Don't get me wrong on this, I like the idea as it. I'm just concerned about making it part of the core.

**Comment by makasim** [comment]
I moved the interfaces out of the enqueue project to a separate repo [queue-interop](https://github.com/queue-interop/queue-interop). Everybody is welcome to participate in its development.

**Comment by unkind** [comment]
> The async events feature could be enabled per event listener and you (as a developer) choose what events you want to be processed asynchronously.

I understand your point, but I'm trying to say, that it is not clear, for example, when async event handler with higher priority executes later than sync event handler with lower priority. The same question goes to the `stopPropogation` method: what should happen when you call it from sync event handler? Does it mean that async handlers should be interrupted as well? Also, some developers might be confused when they mutate event object (and this is acceptable in the Symfony EventDispatcher), but `->dispatch()` method won't return these changes. All these confusions come from the fact that the Symfony component wasn't designed for async behavior in the first place.

We have async event handlers in Symfony EventDispatcher as well, but we don't use this tool directly. We use our own `EventBus` contract with our own `Event` interface without mutators (`stopPropogation`, `setName`, etc.) to make it clear that you can't affect initial procedure and other event handlers. You can find some implementation details here: #18873. Internally, we have 2 instances of the `EventDispatcher` (for sync and async event handlers) and `EventBus` triggers `dispatch` in both of them. In config developer has to specify behavior by choosing right DI-tag. So it's possible to solve this issue without changes in the Symfony core and in more explicit way for developers.
