### ISSUE TITLE
Make the var dumper configurable

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#23442]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Hi.

When working on an API and dumping something, the dump is HTML formatted. I does not play nicely with curl and my terminal.

I open https://github.com/symfony/symfony/pull/13915 2 years ago but it has been rejected. I think we need something to debug API.

**Comment by sawmurai** [comment]
Have you had a look at http://symfony.com/doc/current/components/var_dumper/advanced.html?

Maybe you can use the CliDumper without coloring to dump data nicely.

**Comment by lyrixx** [comment]
I use it in a symfony fullstack.

**Comment by sawmurai** [comment]
Than that should be possible. How are you dumping data right now?

**Comment by lyrixx** [comment]
With the dump function.

**Comment by lyrixx** [comment]
@nicolas-grekas Do you have something in mind someone could work on?

**Comment by ogizanagi** [comment]
@lyrixx : Is https://github.com/symfony/symfony/pull/23831 enough to close this issue?

**Comment by lyrixx** [comment]
Your pull request is very nice. But unfortunatly it's a new way to get dumps and does not really fix this issue. 

But we may close this issue anyway and see how it's going
