### ISSUE TITLE
FormBuilderInterface - CountryType's  PlaceHolder

### ISSUE THREAD

**Issue by devkbsc** [symfony/symfony#23449]
Hello,
I have a CountryType class in my form which displays all the country list in ASC by default. I would like to show an Default false type_option as "Placeholder" 

Is there any possibilites to do that?

```
$builder->add('id_pays', CountryType::class, array('label'=>false, 'attr'=>array('choices'=> array('Choisir' => false)
            'class'=>'form-control',
            'style'=>"margin-bottom:5px;"
        )));
```
Already i have tried this. It doesn't work

**Comment by javiereguiluz** [comment]
Yes, you can do that using the `placeholder` option. See https://symfony.com/doc/current/reference/forms/types/choice.html#placeholder

In any case, in the Symfony repository we only discuss about Symfony bugs and new features. Questions about using Symfony can be asked here: https://symfony.com/support
