### ISSUE TITLE
ClassNotFoundException after using generate:bundle

### ISSUE THREAD

**Issue by Veleous** [symfony/symfony#23450]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

When attempting to run `./bin/console server:run` after having generated a bundle using `./bin/console generate:bundle --namespace=Acme/MyBundle --bundle-name=AcmeMyBundle --format=annotation` I get a `ClassNotFoundException`.

If I update the `autoload psr-4` section of `composer.json` to include my bundle it all works fine.  I didn't have to do this in `3.3.2`.

**Comment by yceruto** [comment]
See symfony/symfony-standard#1098

**Comment by javiereguiluz** [comment]
@Veleous thanks for reporting this! As @yceruto said, this was reported before in https://github.com/symfony/symfony-standard/issues/1098, so I'm closing this as a duplicate. Hopefully this will be fixed soon.
