### ISSUE TITLE
First three characters from route removed

### ISSUE THREAD

**Issue by marvoh** [symfony/symfony#23463]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.4

Something weird is happening in my application since moving from version 3.2 to 3.3.4. The first three characters from routes are being removed hence majority of the application is failing.

For example, a route like /portal ends up /tal, /register becomes /ister.

**Comment by xabbuh** [comment]
Are you able to provide an example project that makes it possible to reproduce your issue?

**Comment by javiereguiluz** [comment]
Here is a similar issue: #1911  Probably this is a web server misconfiguration which is removing 3 letters from all URLs to strip the `web/` part of the URL, which is 3 letters.

**Comment by marvoh** [comment]
This is driving me crazy. I cannot explain how it happens but it does so in the middle of rush hour like now so I'm not even in a position to think straight and what information to provide. It worked fine after posting above but it's just occurred again. I'm using the default .htaccess and haven't changed any server config that didn't work earlier before upgrading to symfony 3.3.4

**Comment by Tobion** [comment]
Is this still relevant? Without further information there doesn't seem anything we can do.

**Comment by xabbuh** [comment]
Closing here due to the lack of feedback. Please leave more information about how to reproduce your issue and we can consider to reopen.
