### ISSUE TITLE
final CacheItem not mockable in tests

### ISSUE THREAD

**Issue by cjost1988** [symfony/symfony#23464]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.11

Good morning,
I am using the tagging of CacheItems in my project and have a small issue with the class definition of the `CacheItem`.

Since the `tag` method is not defined in the `PSR\CacheItemInterface` and the `CacheItem` is final it's impossible to mock `CacheItems` in tests in a proper way. 
My suggestion would be to add an interface that extends the CacheItemInterface and will be implemented by the `CacheItem`.

```php
interface TagAwareCacheItemInterface extends CacheItemInterface
{
    // ...
    public function tag(array $tags);
}

class CacheItem extends TagAwareCacheItemInterface
{
}
```

I think this should not break BC, correct me if I am wrong.

Cheers,
Christian

**Comment by GuilhemN** [comment]
Another option is to use the `@final` annotation which allows mocking.

**Comment by stof** [comment]
As all properties are protected currently, this would open the door to extension point. So this is not the simpliest. We would first need to know why properties are protected rather than private (as long as the class is final, this is equivalent for our BC policy, but it is not the case anymore if the class is not final anymore), to know whether we break things when making them private.

**Comment by cjost1988** [comment]
I like the approach trying to keep things closed and only open things if it's necessarily needed. That's why I suggested the interface approach. It keeps the BC security and adds the opportunity to mock the CacheItem in terms of tagging.

It's the first time I bring up sth like that to the community but I want to do this more often from now on. I could open a PR with the interface approach, if you want me to.

For my project I currently added an interface which extends the `CacheItermInterface` and is only used for the tests. The `TagAwareAdapter` could also profit from it.

**Comment by nicolas-grekas** [comment]
The interface has more drawbacks than the `@final` annotation IMHO (which has none in fact.)
The CacheItem is a data object - we do not want to open other implementations. The interface would open for that, and by doing so, it will also encourage people to get out of PSR-6.
`@final` has no drawback: it just give the intent, which is only what's needed here.

**Comment by stof** [comment]
@nicolas-grekas do you remember why properties are protected rather than private ? If we go with `@final` to allow mocking, I would still switch properties to private. Otherwise, people will start extending the class to access these properties, and potentially break the component

**Comment by nicolas-grekas** [comment]
To ease accessing them from array cast. But I think we shouldn't care. The annotation says we don't support any use of inheritance with this class. That's enough to me.

**Comment by cjost1988** [comment]
> The interface would open for that, and by doing so, it will also encourage people to get out of PSR-6

It was opened by adding methods to `CacheItem` which are not present in the `PSR\CacheItemInterface`. Adding an interface that describes the `CacheItem` just legitimates the tagging feature in the `CacheItem`.

If you don't want to make people extend the `CacheItem` it's possible to make the properties private according to @stof . If it's needed to get the data of the data holder `CacheItem` as array representation there are a lot of technical possibilities to provide this.

As well there are code occurrences where the protected properties of `CacheItem` are accessed directly from outside of the class (e.g. `\Symfony\Component\Cache\Adapter\TagAwareAdapter`:39) in addition to the property visibility.

**Comment by nicolas-grekas** [comment]
`@final` just provides exactly what we need, there is nothing more to enforce to me.
The direct access is via closure rebinding, for a "friend" class (C++-like). Nothing related here :)
A "tagged cache item" interface does not belong to Symfony to me: we don't want to provide any generic semantic on this topic, we just want to provide a data object implementation. The interface would belong to a PSR.

PR adding`@final` is welcomed :)

**Comment by advancingu** [comment]
@nicolas-grekas I wasn't aware that the PHP versions that Symfony supports had support for C++ style friend classes. Would you care to point out the PHP language specification where this is defined? As is, the code in `TagAwareAdapter` is clearly performing a visibility violation which means this is broken code that only works because PHP is so lenient towards structural errors.

As for the suggestion to resolve this via addition of an annotation, I strongly disagree for the same reasons as given by @cjost1988

**Comment by cjost1988** [comment]
I didn't know that PHP has friend class mechanism like in other languages, otherwise this is plain visibility break of the class properties.

For the other topic, If we don't want to legitimate `CacheItem->tag` I don't see any reason to use the tag mechanism since it's not part of the PSR and therefor nothing needs to be changed for me.

> A "tagged cache item" interface does not belong to Symfony to me

Symfony introduced tagging of `CacheItems` under the symfony namespace and therefor it's 
responsible for the interface definition.

**Comment by nicolas-grekas** [comment]
This is going out of topic. There is no violation at all anywhere. "Visibility" is a concept that opens for "contractual" reuse. Internal use of things are not bound by "re"use rules, that's why other languages have private classes, class friendship, etc. From a OOP PoV, this is just the way to achieve this in PHP. But again, this is purely internal, so you shouldn't care.

**Comment by nicolas-grekas** [comment]
See #19515

**Comment by nicolas-grekas** [comment]
Your use case is legitimate, and the annotation is exactly the way to allow it, while not adding more semantics to the type system via an interface, which would be an unwanted side effect.

**Comment by nicolas-grekas** [comment]
> C++ style friend classes

this is possible with closures rebinding, available since 5.4: http://php.net/manual/fr/closure.bindto.php

**Comment by advancingu** [comment]
> this is possible with closures rebinding, available since 5.4: http://php.net/manual/fr/closure.bindto.php

Interesting, thanks for the link. PHP never ceases to amaze :D

**Comment by theofidry** [comment]
@nicolas-grekas any reason not to make those properties `private` instead of `protected`? Removing `final` for `@final` is enough for the mocking use case. But removing it like that also opens the door to abuse whilst making everything private and the methods finals would guarantee that it won't happen.

**Comment by nicolas-grekas** [comment]
I've no specific objection, that's doable, it will just make the PR a bit more complex, for a benefit that I don't personally see (if one doesn't care about `@final`, it's on its own and we won't care if a change breaks its code.) As you want.

**Comment by unkind** [comment]
May I ask why do you need to mock this class?

I see that class contains `time()` call aka singleton, and it can be fixed by passing value through constructor (could be added). Then, you can pass simple `new CacheItem(42)` instead of mocking it.

**Comment by nicolas-grekas** [comment]
Back to this one week later, I think the same as @unkind: the core issue might just be that this call should not be mocked - it's a data object in fact, one that has (almost) no behavior.

Instead, you should be able to create a real CacheItem, e.g. via using an ArrayAdapter to construct them.

**Comment by cjost1988** [comment]
Yes, I would agree if `CacheItem` would be only a data holder. But there is no clean way to set the `key` or manipulate the `isHit` properties. So I've to mock these `CacheItems` to provide the data in a way I want them. Yes, I could use a `\Closure::bind()` because by magic the visibility constraints of the class are ignored, but it's not clean for me too.

Using another real business logic class to generate a `CacheItem` in tests is not an option for me.

For me this issue can be closed since I've added a new interface in the test environment that solves the testing problems for me.

**Comment by nicolas-grekas** [comment]
Ok, closing then.

**Comment by unkind** [comment]
> But there is no clean way to set the key or manipulate the isHit properties.

After close examination of the class I wonder how [this class](https://github.com/symfony/symfony/blob/c633f912d8dde08f9278c691e6347438f901987d/src/Symfony/Component/Cache/CacheItem.php) works. `isHit` property is only accessible via `isHit()` method and there is no way to set/change its value. Values are meant to be set via reflection?

**Comment by robfrawley** [comment]
If I'm not mistaken they are set via closure binding.

**Comment by cjost1988** [comment]
@robfrawley yes, you're right. Only closure binding makes it possible by a visibility break to set the properties.
