### ISSUE TITLE
[Yaml] Escaper::requiresSingleQuoting() returns wrong result

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#23474]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3.2

The [documentation](https://symfony.com/doc/current/components/yaml/yaml_format.html#strings) says:

> Strings **containing** any of the following characters must be quoted. Although you can use double quotes, for these characters it is more convenient to use single quotes, which avoids having to escape any backslash ``\``:
>
> * ``:``, ``{``, ``}``, ``[``, ``]``, ``,``, ``&``, ``*``, ``#``, ``?``, ``|``, ``-``, ``<``, ``>``, ``=``, ``!``, ``%``, ``@``, `

However, the [`Escaper::requiresSingleQuoting()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Escaper.php#L87) method uses the following regex:

```php
preg_match('/[ \s \' " \: \{ \} \[ \] , & \* \# \?] | \A[ \- ? | < > = ! % @ ` ]/x', $value)
```

The `\A[ \- ? | < > = ! % @ ` ]` part only checks whether the value **begins** with one of the characters instead of whether it **contains** one of the characters, so either the docs or the regex is wrong IMHO.

**Comment by stof** [comment]
The doc is wrong. Some chars are special only at the beginning of a value, and so the YAML component avoids escapoing when unnecessary

**Comment by leofeyer** [comment]
Ok, so a value such as `foo%bar` does not need to be escaped?

**Comment by stof** [comment]
not for the YAML format.

I commented on the issue referenced above. The cause of this issue is not related to the YAML format at all, but to the fact that DI configuration may require some escaping too (as some chars are special to represent usage of parameters)

**Comment by leofeyer** [comment]
Yes, https://github.com/contao/installation-bundle/issues/61 has nothing to do with this issue. However, this issue is still valid insofar as the documentation needs to be fixed, doesn't it?

**Comment by stof** [comment]
Btw, the documentation may correspond to an older version of the escaper implementation. I think we used to over-escape values (we would escape `foo%bar` too)
