### ISSUE TITLE
Let's use Flysystem instead of FileSystem Component

### ISSUE THREAD

**Issue by kcassam** [symfony/symfony#23481]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

Flysystem https://github.com/thephpleague/flysystem is a perfect remplacement for Filesystem component, I don't see the point on maintening the Filesystem component when we have Flysystem around

**Comment by robfrawley** [comment]
In my opinion, Symfony's Filesystem component and Flysystem ultimately serve different needs. The Filesystem component is limited to what its name implies, the filesystem, and as such is only ~148K. On the other hand, Flysystem allows you to access files in a medium-agnostic manner but is much bulkier, coming in at 2.6M (or about 95% larger).

**Comment by kcassam** [comment]
yes true, not the same scope
