### ISSUE TITLE
Deprecate auto-discovery of commands in their directories

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23488]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Now that commands can be lazy services very easily, we should deprecate their convention-based auto-discovery (the special "Command" folder in each bundles).

**Comment by javiereguiluz** [comment]
What would be the implications of this change? Before, if I  define commands in the `Command/` folder of my bundle, everything works. What should I do now if I still have the same commands in the same folder? Thanks!

**Comment by chalasr** [comment]
@javiereguiluz Actually if you are using the 3.3 default container configuration, your commands would still be registered naturally and behave the same as before (thanks to the PSR-4 based discovery).

👍

**Comment by lyrixx** [comment]
I'm :-1: for this. It's really convenient for people that don't like PSR-4 base discovery.
More over it will break so many vendored bundles that relies on this feature.

**Comment by chalasr** [comment]
@lyrixx that would not break until 4.0, just trigger deprecations as usual so that distributed/final bundles can register their commands as services beforehand (using PSR-4 discovery or full definitions).

**Comment by lyrixx** [comment]
Yes, I know that ;)

**Comment by javiereguiluz** [comment]
@chalasr thanks for the info. So, if you use the default 3.3 config, everything keeps working. What about applications that upgrade to 3.3, 3.4, etc. but don't want to use autowiring and the default Symfony config? Will commands break for those apps?

**Comment by chalasr** [comment]
@javiereguiluz I think the plan should be to trigger a deprecation notice when a command is registered via this convention, we are able to detect that so no, it won't break in 3.x, only in 4.0, the upgrade path being to register the commands as a service (container aware commands are still ok). The PSR-11 loader should be the easiest way to upgrade for non-distributed bundles as it replicates the convention-based behaviour.

**Comment by nicolas-grekas** [comment]
There is no need for autowiring nor the default config to reason about this.
You can think of this as a proposal to turn a hard coded convention into an equivalent explicit config rule.
Let's say one wants to opt out completely from our default config, then there would be just one rule needed:
```yaml
App\Command\:
  resource: ../src/Command
```
Which would be the explicit equivalent of the current behavior.
Symfony always prefers explicit and configuration over implicit and conventions. This is an opportunity to remove one of the last places where we are not aligned to our philosophy, and enhance flexibility and discoverability, since that's the benefit.

**Comment by javiereguiluz** [comment]
@nicolas-grekas I agree with you about removing hardcoded things 👍 

-----

Unrelated to this, but related to hardcoding, maybe you can propose a solution on this issue: https://github.com/symfony/recipes/issues/104  Apparently, the Kernel used in Flex apps has the `config/` string hardcoded as the config dir location, so there's no simple way to override that. Thanks!

**Comment by iltar** [comment]
Configuration over convention! 🎉

**Comment by nicolas-grekas** [comment]
Doing this would also fix a long standing issue with commands: right now, if a single command fails to instantiate, all commands are unusable. By making commands lazy, we would fix that, see eg. #22243

**Comment by nicolas-grekas** [comment]
Unlocked now that #23624 is merged

**Comment by chalasr** [comment]
Deprecated in #23805 🎉
