### ISSUE TITLE
[DependencyInjection] Compiler pass before merge

### ISSUE THREAD

**Issue by Padam87** [symfony/symfony#23491]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=3.4

Hi,

We have recently started to develop a new system, and one of the requirements is to be able to change some parameters from the admin section. (These parameters would normally belong to parameters.yml, or config.yml:parameters)

Unfortunately some of these parameters are needed compile time.
The [OpenSkyRuntimeConfigBundle](https://github.com/opensky/OpenSkyRuntimeConfigBundle) is very good for some use cases, but it uses expressions, so it can only be used for service arguments directly. This would be fine if you write everything on your own, but that is almost never the case.

For example, in our case, the following extensions depend on the `locale` parameter: framework, stof_doctrine_extensions, jms_translation, jms_i18n_routing.

I will solve this by creating a `parameters.php` file, which reads the config, but I think this would be a nice use case for a compiler pass that runs before the `MergeExtensionConfigurationPass`.

`PassConfig::TYPE_BEFORE_MERGE`

Any chance of accepting a PR like this?

(It would be even better if somehow we could pass expressions/callbacks as parameters, but thats a tall order :))

**Comment by javiereguiluz** [comment]
@Padam87 in one project I use the `parameters.php` file that you mention for some highly dynamic params that can't be defined as env vars or in any other way.

Adding a new compiler pass type is a very serious change, so I'd say that it's better to keep using the `parameters.php` file (unless you find a use case that you can't solve with that). Thanks!

**Comment by Padam87** [comment]
Hi @javiereguiluz,

We wanted this as a private, but reusable bundle.

I've ended up creating a `parameters.php` file and loading it via prepend in the bundle's extension.

```php
    /**
     * {@inheritdoc}
     */
    public function prepend(ContainerBuilder $container)
    {
        $loader = new Loader\PhpFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('parameters.php');
    }
```

It works well, so if the new pass is too much, than this can be closed.
