### ISSUE TITLE
[Cache] FilesystemCommonTrait - Cannot use integers as namespace

### ISSUE THREAD

**Issue by keyball** [symfony/symfony#23503]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

Hi, 
I found that the method `Symfony\Component\Cache\Trait\FilesystemCommonTrait::init($namespace, $directory)`
has some constructs which prevent the namespacing.

The line 33: if (isset($namespace[0])) { ...

will work only if the given namespace is a string. If it'll be an integer - the isset will return false - and no sub-directory in cache root will be created!

Example:

```
$x = 892;
echo 'First element: ' . $x[ 0 ] . PHP_EOL;
var_dump( isset( $x[ 0 ] ) );
```

results in:
_First element: 
bool(false)_

but this notation:
```
$x = (string)892;
echo 'First element: ' . $x[ 0 ] . PHP_EOL;
var_dump( isset( $x[ 0 ] ) );
```
returns the correct values:
_First element: 8
bool(true)_

I would recommend to change the isset directly to a preg_match called one line letter, declare the $match array and check for matching entry in it to throw the exception - or explicitly cast the incoming parameters to string ( it will be obsolete in PHP7 if the method would get typed parameters) .

```
private function init($namespace, $directory)
    {
        $namespace = (string)$namespace;
        $directory = (string)$directory;
```

A similar notation can be found also in the line 28, but there is a lower probability to get an integer instead of string. I know that the "isset" is the fastest method to check if a string exists - but in this case it is not the best solution.

Best regards,
Lukas

**Comment by ro0NL** [comment]
> will work only if the given namespace is a string.

Although not explicitly documented, i think it actually needs to be a string by design. So passing an integer violates the contract.. making this a non-issue :)

We may add contstructor docblocks to clarify.

**Comment by keyball** [comment]
Ok, that should be at least a test with is_string in the constructor to be sure, if the given parameter is a string or not. That will protect from passing all other types to the method. And as a developer uses an external library, he must not even know, how it works to use the given methods. And the only return values should be a value or an exception. In the current case, if someone will use a value that can come from database, url, xml, json, etc. and pass it directly - he won't be sure if the cache will be stored correctly - and now it is possible to overwrite the cache keys from another users - if the namespace will be an user id - as no sub-directory with the correct name will be created. This is not an expected behaviour - so for me - a bug :)

Or do you follow the sentence: Our software never has bugs it just develops random features? :D

**Comment by ro0NL** [comment]
You need to be sure it's a string (if that's the contract). If the constructor arg defines `@param string $some` and you violate it... you're on your own :)

Asserting with `is_string` is just a safeguard for the contract, which is uncommon thing to do in SF.

> Or do you follow the sentence: Our software never has bugs it just develops random features? :D

Software has bugs.. for sure; i wouldnt qualify this as such though :)

**Comment by keyball** [comment]
I got your point - but this isn't the case ;) There is no parameter description in the constructor of the FilesystemAdapter class yet :) But I'll be then more cautious to use the other methods now :) 

Thanks for info :)

**Comment by ro0NL** [comment]
That's why i suggested 

> We may add constructor docblocks to clarify.

;-)

**Comment by iltar** [comment]
The interface (at least in 3.4):
```php
public function __construct($namespace = '', $defaultLifetime = 0, $directory = null);
```
So I would say the type is most certainly defined as string here.
