### ISSUE TITLE
Console Command error on line 665 preg_match() expects parameter 2 to be string object given

### ISSUE THREAD

**Issue by rizalio** [symfony/symfony#23501]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | yes
| RFC?             | no 
| Symfony version  | 4.0.x-dev

I try create a new test command with symfony console components.

testCommand.php

```
<?php

namespace Rizal\Commands;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    protected function configure()
    {
      $this
         // the name of the command (the part after "bin/console")
         ->setName('app:test')

         // the short description shown while running "php bin/console list"
         ->setDescription('Test Command');

    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
       $output->writeln('Congratulations! Command setup successfully!');
    }
}
```

app.php

```
#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
$app = new Application();


$app->register(new Rizal\Commands\TestCommand);


$app->run();
```

The error says: 

```
PHP Warning:  preg_match() expects parameter 2 to be string, object given in C:\Users\Rizal Fakhri\Desktop\project-youtube\vendor\symfony\console\Command\Command.php on line 665
```

**Comment by xabbuh** [comment]
I cannot reproduce your issue. Can you upload a small example project that makes it possible to do so?

**Comment by rizalio** [comment]
I just following official docs here [http://symfony.com/doc/current/components/console.html](http://symfony.com/doc/current/components/console.html). 

And add new command like docs here: [http://symfony.com/doc/current/console.html](http://symfony.com/doc/current/console.html)

I ain't change anything, just following the docs, here my file 

[project-youtube.zip](https://github.com/symfony/symfony/files/1148410/project-youtube.zip)


and here some screenshoots:
![ss1](https://user-images.githubusercontent.com/22221916/28212890-d0c2c3b6-68cd-11e7-8657-f0f6f6356165.png)
![ss2](https://user-images.githubusercontent.com/22221916/28212891-d0c7697a-68cd-11e7-9b53-edec675db65e.png)

**Comment by inso** [comment]
@rizalio you should use:

    $app->add(new Rizal\Commands\TestCommand);

instead of:

    $app->register(new Rizal\Commands\TestCommand);

**Comment by xabbuh** [comment]
@inso is right. You need to use `add()` instead of `register()`.

**Comment by rizalio** [comment]
Well I just following the docs, ok let me try :) thanks for you all help :)
