### ISSUE TITLE
FreeTDS - SQLSERVER

### ISSUE THREAD

**Issue by rmfwebmaster** [symfony/symfony#23500]
SYMFONY 3 erros connect sqlserve user freeTDS

$ bin/console  doctrine:query:sql  "select * from [pm01estoque].[dbo].[cadcop00]" --connection=sqlserver
                                                        
  [Doctrine\DBAL\Driver\PDOException]                             
  SQLSTATE[01002] Adaptive Server connection failed (severity 9)

-------------------------------------------------------------------------------------------------------------
$isql -v sqlserver sa '123456'
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL>

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

Furthermore, this error does not look related to Symfony but to Doctrine/DoctrineBundle.
