### ISSUE TITLE
Call to a member function addResource() on array

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23518]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

I'm updating a Symfony application to use Symfony 3.3.4 and Flex 1.0.11. In my app I had this config file which maps old URLs to new URLs:

```php
// app/config/legacy_url_map.php
<?php

return array(
    '/old-url' => '/new-url',
    // ...
);
```

I tried to move that file to `config/routing/legacy_url_map.php` but the following confusing error happened:

![fatal-error](https://user-images.githubusercontent.com/73419/28238742-b4173980-695a-11e7-8aa7-fd5bcd29732f.png)

-----

I guess you can't put arbitrary files inside the new `config/routing/` dir ... but the error message should be improved in those cases. Thanks!

**Comment by fabpot** [comment]
Closing as this is a doc issue
