### ISSUE TITLE
Can we set RedirectResponse meta refresh to 0?

### ISSUE THREAD

**Issue by jnvsor** [symfony/symfony#23524]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | *

In `HttpFoundation\RedirectResponse` there's a fallback html body with a meta refresh set to 1 second. Can we change this to 0? As far as I'm aware all browsers support a meta refresh of 0.

**Comment by ro0NL** [comment]
What's the goal? AFAIK this has never been an issue to anyone, also note `Refresh` is a non-standard thingy in HTTP (this is probably here for historic reasons).

Reading http://www.otsukare.info/2015/03/26/refresh-http-header the `Competition Of Techniques` is quite interesting actually ;-)

**Comment by jnvsor** [comment]
Refresh is pretty much universally supported and doesn't rely on javascript, so it's a good way to push a redirect through if your headers are already sent. This wouldn't affect symfony per-se (since any modern framework isn't going to echo in the controller), but I know legacy projects that could benefit from the fallback.

**Comment by ro0NL** [comment]
well.. it doesnt hurt probably :)

**Comment by jnvsor** [comment]
Well if no-one knows a reason to leave it at 1 I'll submit a PR to change it to 0

**Comment by javiereguiluz** [comment]
👍  for changing to `0`
