### ISSUE TITLE
[RFC] Deprecate $invalidBehavior in Container::get

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#23525]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Now that PSR containers are real; SF's container is one and service locators show its usefulness, i think we can/should drop `get($id, $invalidBehavior)` (which is not PSR api) in favor of `has($id) ? get($id) : null`

Service locators have optimized hassers, and dumpers optimize to a cheap isset already. So it shouldnt have to much impact. 

Note invalid behavior for `Reference` remains in YAML etc., but we can probably move the constants, as `IGNORE_ON_INVALID_REFERENCE` has no use in `get()` anyway.

Thoughts?

**Comment by nicolas-grekas** [comment]
What would be the benefit of doing so? PSR11 is not Symfony's ContainerInterface, and we don't have any plan to replace it completely.

**Comment by ro0NL** [comment]
Little i guess.. as we're already PSR compliant. it's just, because of that, i see no real reason to sell additional API with `get()`. Having 1 way of doing things is nice :)

So yeah, im not sure it's worth the effort.. hence RFC :)

**Comment by chalasr** [comment]
I would keep it :) `on-invalid=` is especially useful for having soft dependencies across core components.

**Comment by ro0NL** [comment]
That wouldnt change :) wherever we use $invalidBehavior we would invoke a has call instead.

**Comment by xabbuh** [comment]
But that would mean one additional method call. I am not convinced that's worth it.

**Comment by ro0NL** [comment]
@xabbuh note from PSR perspective you can spare out the extra has call

```
try {
  return $container->get('x');
} catch (ServiceNotFoundException $e) {
  return null;
}
```

**Comment by nicolas-grekas** [comment]
:-1:

**Comment by fabpot** [comment]
I'm 👎 as well. Closing.
