### ISSUE TITLE
[RFC] Deprecate the web_profiler.position option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23528]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

This config option allows to display the debug toolbar at the top of the browser window instead of the default bottom position.

In the past we required this option because the old profiler displayed the toolbar at the top ... but the new profiler no longer needs it because it doesn't display the toolbar.

Although this may look as a small option, it requires some code to manage it:

* The config code to define and validate the `position` option in `web_profiler`
* The toolbarPosition argument is passed around in some profiler controllers
* The CSS styles must define special styles when the toolbar is at the top
* We even create a container parameter for this! `web_profiler.debug_toolbar.position`

Now that we don't need this option for ourselves, I propose to deprecate it in 3.4 and remove it in 4.0.

**Comment by hhamon** [comment]
I'm +1 too for deprecating it if we're sure it doesn't provide added value. If I remember well I had to move the toolbar at the top once because I was working on a page with an infinite scroll and the toolbar at the bottom was annoying in this case.

**Comment by xabbuh** [comment]
IIRC the use case @hhamon mentions was the reason why we rejected this idea in the past. However, how hard would it be to write custom CSS that does the same without the need for this option?

**Comment by javiereguiluz** [comment]
I can't understand why you can't use the web profiler in a page with "infinite scroll". This "feature" makes impossible to achieve the footer of the page, because the page always adds more contents ... but the debug toolbar is fixed at the bottom of the page. You can click on it without having to do any scroll. Moving the cursor over the debug toolbar won't make the page add more contents.

**Comment by nicolas-grekas** [comment]
:+1: if it removes code and help maintenance

**Comment by fabpot** [comment]
IIRC, it was introduced to help display the toolbar on mobile, where having it on top is "better"/easier/worked (don't remember exactly).
