### ISSUE TITLE
[RFC] Move ContainerAwareCommand from FrameworkBundle to Console

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23529]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

A few days ago, in the Symfony Slack someone (I think it was @gnugat) proposed to make this change, so I copy it here to discuss about this:

> We could move ContainerAwareCommand from FrameworkBundle to Console.

**Comment by chalasr** [comment]
Given the steps done toward registering commands as services and dependency lazy loading, I don't think we should go in this direction.
The only benefit for commands to be `ContainerAware` is to have very lazy dependencies (loaded only when called) but as of 3.3 we have better alternatives, the best being to make the command a service subscriber.
Actually, as of 3.4 I would consider extending `ContainerAwareCommand` a bad practice.

**Comment by ro0NL** [comment]
It depends on `Application` from the framework bundle anyway.. so that needs to be stripped; leaving you with `implements ContainerAwareInterface + user ContainerAwareTrait` bridging class.

You can do that in user land easily. I.e. we might as well deprecate `ContainerAwareCommands` once core doesnt use it anymore.

**Comment by gnugat** [comment]
@chalasr so should we deprecate it?

@ro0NL FrameworkBundle's `Application` could also be moved to Console

**Comment by chalasr** [comment]
@gnugat https://github.com/symfony/symfony/issues/21623 :) I may reopen, I think we need time for the community to be familiar with 3.3 features and best practices

**Comment by nicolas-grekas** [comment]
:-1: as is, ContainerAwareInterface is not the future, as explained by @chalasr

**Comment by javiereguiluz** [comment]
Closing it because of the downvotes ... and because @chalasr may reopen a related (but better) proposal in the future. Thanks!
