### ISSUE TITLE
Documentation for AuditTrailListener, Logging in Workflow Component

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#23521]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.3+

**Comment by iltar** [comment]
So what's the actual issue? If you want more documentation, please check https://github.com/symfony/symfony-docs and see if there are PRs/issues open already.

**Comment by javiereguiluz** [comment]
@tacman the documentation for Symfony project is managed in a different repository: https://github.com/symfony/symfony-docs

Please review the open issues (https://github.com/symfony/symfony-docs/issues) and pull requests (https://github.com/symfony/symfony-docs/pulls) to check if we're already working on this. If we are not, please open an issue asking for new docs. Thanks!
