### ISSUE TITLE
[RFC] Simplify the creation of validation constraints

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23530]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Another proposal made a few days ago in the [Symfony Slack](https://symfony.com/support). I'm sorry I can't remember the person behind this proposal.

> I'd like to change constraint classes. I don't understand why I need to create a Constraint with only a name and a ConstraintValidator with logic. Only one class could be good even if it's don't respect SRP.

An example of what we are talking about: to validate countries, you need to create these two classes:

* [Constraints\Country.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/Country.php) is almost empty.
* [Constraints\CountryValidator.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/CountryValidator.php) contains the validation logic.

Maybe we can define a new interface, so we can do things in a single `CountryConstraint.php` class instead of having to define two classes for each constraint?

**Comment by ro0NL** [comment]
Perhaps we can trick the pattern and add a `abstract SelfValidatingConstraint extends Constraint implements ConstraintValidatorInterface`

could work out

**Comment by hhamon** [comment]
The actual implementation has a lot of sense and I don't see how we could easily simplify it. Separating constraints (aka rules or configurations) from validators (behaviors) enables to reuse the validator logic with multiple instances of constraints are configured differently. If both were mixed in the same class, we wouldn't be able to reuse the same constraint (think `@Length` for instance) multiple times with different configurations during the same validation run.

Thus, constraint classes enable to register Annotations in the annotation registry.

**Comment by ro0NL** [comment]
> The actual implementation has a lot of sense and I don't see how we could easily simplify it.

Well..

> abstract SelfValidatingConstraint extends Constraint implements ConstraintValidatorInterface

seems viable to me. I think we only need to patch validator factores to allow for something like `validatedBy() { return $this; }` perhaps.

> If both were mixed in the same class, we wouldn't be able to reuse the same constraint (think `@Length` for instance) multiple times with different configurations during the same validation run.

If it's self validating.. i dont see a real issue here?

**Comment by hhamon** [comment]
Your idea could work I guess. But Idon't see if it provides real added value in the end. Let's see what others think.

**Comment by ro0NL** [comment]
I would allow to merge `CountryValidator` into `Country` :) not sure core needs it.. but TBH i would love write custom constraints like that actually :)

**Comment by xabbuh** [comment]
Supporting this out of the box could be nice in terms of DX. We should then just make sure that one cannot pass any options to the constraint's constructor as doing so would lead to weird behaviour.

**Comment by ro0NL** [comment]
Constructing constraints wouldnt change? Once constructed, we'd have the validator as well (considering it implements `ConstraintValidatorInterface` and it's picked up in the factory somewhere, e.g. by `return $this` in validatedBy()).

It should still allow for other instances of the same type..

`$countryContraintA->validate($val, $countryConstraintB)` not sure that's a big deal.

**Comment by javiereguiluz** [comment]
Closing as won't fix because of the downvotes and comments agains it. Thanks!
