### ISSUE TITLE
[RFC] Deprecate the router.strict_requirements option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23532]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

This option lets you ignore the requirements of routes when generating links. This is useful to not throw exceptions when using `path()` or `url()` in Twig templates.

I've never cared about this option or changed its default value. I wonder if it's the same for other people. My reasoning for deprecating it:

* Sometimes it's great to not throw exceptions in Twig templates (e.g. the changes we made to `logout_url()` function) but this case it's different. It's like telling Symfony: *"I'm giving you the wrong arguments, but I don't care: generate a (wrong) link anyway!"*
* Even if you avoid exceptions in the template, when clicking on the link and executing the controller, you'll probably throw exceptions anyway because the arguments are wrong.
* It complicates a bit the applications using Flex. Let me explain why:

When using Flex, you have 3 different routing configurations:

* `config/routing.yaml` is where you define the routes of the app.
* `config/routing/*.yaml` is where packages add their routes to the app.
* `config/packages/routing.yaml` and `config/packages/dev/routing.yaml` configure the routing component.

I can imagine a lot of problems for newcomers when we tell them *"configure the routing file"* ... but which one !?!?!

If you open the `config/packages/routing.yaml` file, you see that it's only used for this `strict_requirements` option:

```yaml
# config/packages/routing.yaml
framework:
    router:
        strict_requirements: null
```

So, if we remove the `strict_requirements` option, this file disappears and everything would be easier.

**Comment by fabpot** [comment]
Please, have a look at why we introduced this option in the past. We won't remove anything if the use case that made us introduce it in the first place still exists. Why on earth would you think we introduced non-sense options in the past?

**Comment by fabpot** [comment]
I'm all for simplifying things, but not blindly.

**Comment by javiereguiluz** [comment]
I'm sorry if I explain myself bad. In the first phrase of the description I said *"This is useful to [...]"* so I don't think is a non-sense. I just wonder if this option is still needed/useful. Thanks!

**Comment by fabpot** [comment]
Which is exactly my point. If you are wondering if this option is still needed, just have a look at the PR that introduced it. No need to create an issue. If when re-reading the PR that introduced this option, you find that the use case does not exist anymore, then create an issue.

**Comment by javiereguiluz** [comment]
For reference purposes, this is the PR that introduced this: #4534.

I agree with [this comment](https://github.com/symfony/symfony/pull/4534#r974742) from @Tobion:

>  I fully understand your use case [...] but IMO it should be implemented differently [...] it belongs to the view layer, that is Twig.

This could be an argument of `path()/url()`:

```twig
<a href="{{ path('route', { param: 'wrong' }, ignore_errors = true) }}"> ... </a>
```

Or, if Twig defined a `@` operator to silence exceptions by returning `null`:

```twig
<a href="{{ @path('route', { param: 'wrong' }) }}"> ... </a>
```

**Comment by ro0NL** [comment]
> I've never cared about this option or changed its default value

That's because SF standard has sensible defaults. AFAIK this settings allows for `fail in dev, dont fail in prod` strategy.. which is nice? Not sure we need a per case choice in templates :S

Descriptions are clear;

```
'true' is the preferred configuration in development mode, while 'false' or 'null' might be preferred in production
```

However i'd prefer a simple `true|false` though :) I wouldnt use the current `false` mode, i'd expect that that to work how `null` actually works :)

**Comment by nicolas-grekas** [comment]
@javiereguiluz please note that this behavior (strict in dev, not in prod) is quite common in the code base:
twig variables are strict in dev, weak in prod
php errors throw exception in dev, log in prod

I think this is just the correct strategy, and that this parameter is the equivalent for routing.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because of the reasons given in the above comments. Thanks!
