### ISSUE TITLE
[HttpKernel] HttpCache works with cloned request object

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#23546]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.4

In the [`HttpCache::fetch()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L421
) method does a `$subRequest = clone $request;` and passes the `$subRequest` variable to the `forward()` method, so all the request attributes end up on the `$subRequest` object instead of the `$request` object.

```php
    protected function fetch(Request $request, $catch = false)
    {
        $subRequest = clone $request;

        // send no head requests because we want content
        if ('HEAD' === $request->getMethod()) {
            $subRequest->setMethod('GET');
        }

        // avoid that the backend sends no content
        $subRequest->headers->remove('if_modified_since');
        $subRequest->headers->remove('if_none_match');

        $response = $this->forward($subRequest, $catch);  // <-- $subRequest instead of $request

        if ($response->isCacheable()) {
            $this->store($request, $response);
        }

        return $response;
    }
```

This causes the request object to be empty when passed to `$kernel->terminate($request, $response)`.

<img width="728" alt="" src="https://user-images.githubusercontent.com/1192057/28267664-56b2be34-6afb-11e7-9618-0b9523c5cf25.png">

Here is the request object without using the HTTP cache:

<img width="805" alt="" src="https://user-images.githubusercontent.com/1192057/28267673-6378d842-6afb-11e7-98c0-30f12c322b4e.png">

Is this the expected behavior when using the HTTP cache? Because some of our `kernel.terminate` event listeners need to read the request attributes. Also, it seems kind of inconsistent to me.

**Comment by nicolas-grekas** [comment]
I think it's the expected behavior: the cache middleware shouldn't have access to the parameters set by the app. That's the behavior of using eg Varnish as another middleware caching layer, we should not diverge from this reference.

**Comment by fabpot** [comment]
Being as close as possible as a reverse proxy that would be in front of an app is indeed the goal here.

**Comment by tkfm-yamaguchi** [comment]
@nicolas-grekas 
> I think it's the expected behavior: the cache middleware shouldn't have access to the parameters set by the app. 

Then, is it impossible to use terminate event for the process like below which depends on the request's attributes (i.e. _controller) ?
https://stackoverflow.com/a/35219628/11076740

If so, it would be nice that some notes about that limitation of terminate event are in the references/documents.
