### ISSUE TITLE
Validation cache duplicates constraints

### ISSUE THREAD

**Issue by ossinkine** [symfony/symfony#23544]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=3.2.2 >=3.3.0-beta1

Validation caching merges constraints for class and all of its parents. It's wrong behaviour, because the class already contains constraints from parent classes. As a result we have duplicated constraint.

### The way to reproduce

Create two models, the second one extends the first one:
```php
namespace AppBundle\Model;

class Foo
{
    public $foo;
}
```
```php
namespace AppBundle\Model;

class Bar extends Foo
{
}
```
Create validation config, add constraint to the first class, the second class should be defined (empty or with some constraints)
```yaml
AppBundle\Model\Foo:
    constraints:
        - Expression: "this.foo !== null"

AppBundle\Model\Bar:
```
And validation of new `Bar` object will generates two duplicated violations:
```php
$container->get('validator')->validate(new Bar()));
```
Note: this code should be executed in prod environment, because test environment doesn't use validation cache by default.

**Comment by dmaicher** [comment]
I cannot reproduce your problem using Symfony `v2.8.24`. I made sure the validator uses a cache and for me the merging of the constraints ends up with exactly one class constraint for `Bar`. So the validation results in one violation.

**Comment by ossinkine** [comment]
@dmaicher I'll to reproduce with your version shortly

**Comment by ossinkine** [comment]
@dmaicher I was wrong. Affected versions start on 3.2.2. I've updated the top message.
Maybe validator cache warmer breaks this. See https://github.com/ossinkine/symfony-standard/tree/issue-23544, run `./bin/console cache:warmup --env=prod` and `./bin/console foo --env=prod`

**Comment by dmaicher** [comment]
Ok indeed bug confirmed using `3.2.2+`.

**Comment by dmaicher** [comment]
Ok after some debugging I found the problem.

It only happens when using the cache warmup because in that case the `Psr6Cache` uses an `ArrayAdapter` with `$storeSerialized=false` which means we are mutating the cache item after it has been written into the cache by calling `$this->mergeConstraints($metadata);`.

Working on a fix :wink:

**Comment by dmaicher** [comment]
@ossinkine I proposed a fix here: https://github.com/symfony/symfony/pull/23558

Can you try it to confirm it works for you?

**Comment by ossinkine** [comment]
@dmaicher Yes, it works for me! Great work! 👍
