### ISSUE TITLE
dom-crawler ignores submit buttons when parse form elements

### ISSUE THREAD

**Issue by VoDmAl** [symfony/symfony#23557]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | *.*.*

dom-cralwer does not handle correct request that depends on form submit button value.

According to HTML spec you could put more than one submit button and server side will take into account value of the html element. Some discussions are here: https://stackoverflow.com/questions/547821/two-submit-buttons-in-one-form

All you need is just to remove submit and button from !in_array here: https://github.com/symfony/dom-crawler/blob/master/Form.php#L477

Or give an option to customize it. 

Thank you!

**Comment by xabbuh** [comment]
Can you please be a bit more specific and give a small example of what you are trying to do and what exactly is failing in your project (e.g. what did you expect to happen and what happened instead)?

**Comment by VoDmAl** [comment]
Yep. I use \Goutte\Client. I requested a page with form.  I found form on page with Symfony\Component\DomCrawler\Crawler and used submit(). 

This form looks like: 
```html
<form action="index.php">
<input type=text name=login />
<input type=text name=password />
<input type=submit name=action value=login />
```

On server side i guess it looks like: 
```php
switch ($_POST['action']) {
    case 'login':
        // do login stuff
        break;
    case 'logout':
        // do logout stuff
        break;
    default:
        throw new Exception('Unknown action');
        break;
}
```

I can't pass field named "action". Will be Exception as the code filtered such type of form elements.

So the easiest solution is to do not filter "submit" buttons and allow us to pass default values or to change to own values.

**Comment by jakzal** [comment]
You shouldn't pass the action manually, but rather select the button you want to submit:

```
$form = $crawler->selectButton('foo')->form();
$crawler = $client->submit($form, array('field1' => 'test', 'field2' => 'aaa'));
```

Full example. Given a page with two buttons:

```
<!DOCTYPE html>
<html>
    <body>
        <div class="debug"><?php var_dump($_POST); ?></div>
        <form action="index.php" method="POST">
                <input type=text name=login />
                <input type=text name=password />
                <input type=submit name=action value=bar />
                <input type=submit name=action value=foo />
        </form>
    </body>
</html>
```

and a script

```
<?php

use Goutte\Client;

require_once __DIR__.'/vendor/autoload.php';

$client = new Client();
$crawler = $client->request('GET', 'http://localhost:8000/page.php');

$form = $crawler->selectButton('foo')->form();
$crawler = $client->submit($form, array('login' => 'test'));
var_dump(html_entity_decode($crawler->filterXPath('//div[@class="debug"]')->html()));

$form = $crawler->selectButton('bar')->form();
$crawler = $client->submit($form, array('login' => 'test'));
var_dump(html_entity_decode($crawler->filterXPath('//div[@class="debug"]')->html()));
```


it will dump:

```
string(111) "array(3) {
  ["action"]=>
  string(3) "foo"
  ["login"]=>
  string(4) "test"
  ["password"]=>
  string(0) ""
}
"
string(111) "array(3) {
  ["action"]=>
  string(3) "bar"
  ["login"]=>
  string(4) "test"
  ["password"]=>
  string(0) ""
}
"
```
