### ISSUE TITLE
Web server does not stop on server:stop

### ISSUE THREAD

**Issue by szymach** [symfony/symfony#23568]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

Hello,
Despite my initial assumption, the `server:stop` does not actually stop the web server. It displays all-is-good message, but I can still access the app under `127.0.0.1:8000`. What is more, there is no way for my to shut down the process aside from running `kill PROCESS_PID`.

This has changed since upgrading to 3.3.5 from 3.2.11 (PHP 7.1.7).

**Comment by javiereguiluz** [comment]
I can't reproduce with Symfony 3.3.5. I run `server:start`, check that the process exists, run `server:top` and the process no longer exists. We'd need ore information to reproduce this.

**Comment by szymach** [comment]
I can email you my php.ini (I would rather not post it here). Also running Ubuntu 16.04 with all current updates installed.

**Comment by szymach** [comment]
@javiereguiluz please check your email, I have sent you my PHP configuration data. I can also confirm I have this problem on two separate projects, both running sf3.3.5.

**Comment by javiereguiluz** [comment]
I've checked the php.ini and phpinfo sent by @szymach. I can't see anything different from expected:

* OPCache is disabled in CLI
* There are no disabled functions or classes
* pcntl extension is installed and enabled

Can you see any error message in the system log or the main PHP log file when trying to stop the web server?

**Comment by szymach** [comment]
Sorry, but no PHP related error messages are present in either file. Maybe it will help that in both cases I ran it on Ubuntu 16.04, though separate workstations.

**Comment by stof** [comment]
can you check in your phpinfo if sigchild is enabled on each of these servers ?

**Comment by javiereguiluz** [comment]
@stof how can you check "sigchild" support? I can't see it in my own phpinfo. Maybe is displayed as "Zend Signal Handling"? If it is, then it's enabled in the phpinfo that he sent me.

**Comment by szymach** [comment]
Also as a side not, I can use `server:run` and simply cancel the process, which works fine (hardly useful, but hey, maybe it will help somehow).

**Comment by stof** [comment]
@javiereguiluz PHP normally displays the `Configure command` in the phpinfo, allowing to see whether `--enable-sigchild` was part of it.
However, I just discovered that Debian packaging (and so Ubuntu one as well) removes this info: https://bugs.launchpad.net/ubuntu/+source/php5/+bug/516061

@nicolas-grekas this means that our detection of sigchild in the Process component is broken for people using Debian/Ubuntu packages, as it is based on checking the phpinfo.

**Comment by nicolas-grekas** [comment]
@stof sad... can't we assume that debian/ubuntu do not do sigchild-enabled build?
@szymach can you try `php-config --configure-options` and report the output please?

**Comment by stof** [comment]
@nicolas-grekas this assumption is what happens in practice in the code (if the second is removed entirely, ``--enabled-sigchild`` won't be there). but I'm not sure it is the case.

**Comment by szymach** [comment]
@nicolas-grekas  This is the output from my home PC, but I have the same issue here anyway:

```
--includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --disable-silent-rules --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-cli --disable-cgi --disable-phpdbg --with-config-file-path=/etc/php/7.1/cli --with-config-file-scan-dir=/etc/php/7.1/cli/conf.d --build=x86_64-linux-gnu --host=x86_64-linux-gnu --config-cache --cache-file=/build/php7.1-DIXfRi/php7.1-7.1.7.retag/config.cache --libdir=${prefix}/lib/php --libexecdir=${prefix}/lib/php --datadir=${prefix}/share/php/7.1 --program-suffix=7.1 --sysconfdir=/etc --localstatedir=/var --mandir=/usr/share/man --disable-all --disable-debug --disable-rpath --disable-static --with-pic --with-layout=GNU --without-pear --enable-filter --with-openssl=yes --with-pcre-regex=/usr --enable-hash --with-mhash=/usr --enable-libxml --enable-session --with-system-tzdata --with-zlib=/usr --with-zlib-dir=/usr --enable-dtrace --enable-pcntl --with-libedit=shared,/usr build_alias=x86_64-linux-gnu host_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -O2 -Wall -pedantic -fsigned-char -fno-strict-aliasing -g
```

**Comment by robfrawley** [comment]
@nicolas-grekas Your assumption is accurate at this time; both the [Ubuntu default packages](https://packages.ubuntu.com/xenial/php7.0) and [ondrej/php ppa](https://launchpad.net/~ondrej/+archive/ubuntu/php/) do not build with `--enabled-sigchild` as of today, confirmed using:

```
apt-get source php${version}
grep enable-sigchild ../php${version}/debian/rules &>/dev/null ; echo $?
# outputs 1

php-config --configure-options | grep -o enable-sigchild &>/dev/null ; echo $?
# outputs 1
```

**Comment by nicolas-grekas** [comment]
ok thanks, so all is good on the sigchild topic.

Looking at the code, could it be because of https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebServerBundle/WebServer.php#L162 ?
In 3.2, instead of getcwd(), we used [sys_get_temp_dir()](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php#L46)

**Comment by nicolas-grekas** [comment]
Instead of pid tracking, can't we add a kill switch to the webserver, coded in the front controller, that we could trigger via a simple HTTP call?

**Comment by pedrobrost** [comment]
I have the same problem and I found this:

```
// Symfony\Component\Process\ProcessBuilder
// public function getProcess()
$arguments = array_merge($this->prefix, $this->arguments);
        $process = new Process($arguments, $this->cwd, $this->env, $this->input, $this->timeout, $this->options);
        // to preserve the BC with symfony <3.3, we convert the array structure
        // to a string structure to avoid the prefixing with the exec command
        $process->setCommandLine($process->getCommandLine());
```

So, here in getProcess the final value of the instance variable "commandline" is in my case: 

`"'/usr/bin/php7.0' '-S' '127.0.0.1:8000' '/home/pedro/Projects/{project_name}/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php'"`

And before 3.3 version, the final value was:

`"exec '/usr/bin/php7.0' '-S' '127.0.0.1:8000' '/home/pedro/Projects/{project_name}/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php'"`

As you can see the first one doesn't have the "exec ". So I don't really know why this happens but without that "exec " the server doesn't stop when the "stop()" message is sent to the Process object. If I add that "exec", everything goes well.

**Comment by nicolas-grekas** [comment]
@pedrobrost good catch, that should do it: #23568

**Comment by robfrawley** [comment]
@nicolas-grekas #23686 not #23568 :-)
