### ISSUE TITLE
Browser crashes when loading annotated routes and annotations are disabled

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23566]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

When using Symfony 3.3 and Flex, annotations support is not enabled by default. If you uncomment this config of `config/routing.yaml` file:

```yaml
controllers:
    resource: ../src/Controller/
    type: annotation
```

The browser displays a *"Make sure annotations are enabled"* message, but the application continues working, eats all CPU and finally crashes the browser:

![annotations-crash](https://user-images.githubusercontent.com/73419/28306671-81b1b98c-6ba0-11e7-909d-e646046fa637.png)

I expected the application to finish once the error message is displayed.

**Comment by ogizanagi** [comment]
https://github.com/symfony/symfony/pull/23577 should fix this 😅
