### ISSUE TITLE
[VarDumper] Dumper probably shouldn't localize decimal points.

### ISSUE THREAD

**Issue by bobthecow** [symfony/symfony#23572]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 3.2.0

This…

```php
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;

// Ensure locale uses `.` for decimal separator
setlocale(LC_NUMERIC, 'en_US');

$cloner = new VarCloner();
$dumper = new CliDumper(null, null, CliDumper::DUMP_LIGHT_ARRAY | CliDumper::DUMP_COMMA_SEPARATOR);
$dumper->dump($cloner->cloneVar([1, 2.3, 4]));
```

Works as you'd expect:

```
[
  1,
  2.3,
  4
]
```

But this…

```php
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;

// Switch to a locale with `,` as a decimal separator
setlocale(LC_NUMERIC, 'fr_FR');

$cloner = new VarCloner();
$dumper = new CliDumper(null, null, CliDumper::DUMP_LIGHT_ARRAY | CliDumper::DUMP_COMMA_SEPARATOR);
$dumper->dump($cloner->cloneVar([1, 2.3, 4]));
```

Gets a little weird:

```
[
  1,
  2,3,
  4
]
```

And if you change locales after creating a dumper…

```php
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;

// Ensure locale uses `.` for decimal separator
setlocale(LC_NUMERIC, 'en_US');

$cloner = new VarCloner();
$dumper = new CliDumper(null, null, CliDumper::DUMP_LIGHT_ARRAY | CliDumper::DUMP_COMMA_SEPARATOR);

// Switch to a locale with `,` as a decimal separator
setlocale(LC_NUMERIC, 'fr_FR');

$dumper->dump($cloner->cloneVar([1, 2.3, 4]));
```

It gets weirdest of all:

```
[
  1,
  2,3.0,
  4
]
```

**Comment by nicolas-grekas** [comment]
the bug when changing the locale after creating the dumper should be fixed by #23574

**Comment by nicolas-grekas** [comment]
and see #23575 for the locale dependent part
(I think being locale sensitive is a feature, but when using "comma" flags, a C locale is implicit.)

**Comment by bobthecow** [comment]
Thanks for the quick turnaround!

Maybe there should be a dumper flag to disable localized floats? In my case, I want the return values in PsySH to always look as close to code as reasonably possible.

**Comment by nicolas-grekas** [comment]
But you always use a comma flag, don't you? Which means with #23575 that you're going to be locale insensitive :)

**Comment by bobthecow** [comment]
True, but that feels kind of like relying on a side effect or an implementation detail :)

**Comment by nicolas-grekas** [comment]
It's a behavior, which means a feature of the comma flags :)

**Comment by bobthecow** [comment]
Fair enough. :)
