### ISSUE TITLE
[PropertyInfo] Error with phpdocumentor/reflection in test mode

### ISSUE THREAD

**Issue by aumel** [symfony/symfony#23576]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.25

I am not sure if the problem is related directly to Symfony.

I encounter an error with PropertyInfo component on a new install of symfony 2.8.25 and phpunit tests. The problem does not seem to appear in production mode.

This is a simple test to reproduce:
```
<?php

namespace AppBundle\Tests;

use AppBundle\Entity\MyClass;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;

class PropertyInfoTest extends \PHPUnit_Framework_TestCase
{
    public function testPropertyInfo()
    {
        $phpDocExtractor = new PhpDocExtractor();
        $reflectionExtractor = new ReflectionExtractor();

        $listExtractors = array($reflectionExtractor);

        $typeExtractors = array($phpDocExtractor, $reflectionExtractor);

        $descriptionExtractors = array($phpDocExtractor);

        $accessExtractors = array($reflectionExtractor);

        $propertyInfo = new PropertyInfoExtractor(
            $listExtractors,
            $typeExtractors,
            $descriptionExtractors,
            $accessExtractors
        );

        $object = new MyClass();
        // this part throws an error
        $types = $propertyInfo->getTypes(get_class($object), 'property');
    }
}
```

When I execute the test with phpunit, I get this error:

```
Fatal error:  Cannot use phpDocumentor\Reflection\DocBlock\Location as Location because the name is already in use in test_property_info/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/FileReflector.php on line 19
```

Is there a problem with autoload PSR-4 ?

**Comment by Simperfit** [comment]
@aumel Could you please do the following, so we could get a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

**Comment by aumel** [comment]
@Simperfit I forked the Symfony Standard Edition and I made modification to reproduce the bug on branch `issue-23576`

Link of the forked repo: https://github.com/aumel/symfony-standard

To reproduce bug, you must execute the test `phpunit -c app src/AppBundle/Tests/Entity/`

You will get this error:

```
Fatal error:  Cannot use phpDocumentor\Reflection\DocBlock\Location as Location because the name is already in use in /vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/FileReflector.php on line 19
```

For info, I tested with PHP 5.6.x and phpunit 5.7.21.

**Comment by jakzal** [comment]
@aumel thanks for taking time to reproduce this issue. Seems that the original problem is replaced by a new one. This is what I'm getting now (on PHP 7.1.10 with PHPUnit 5.7.23):

```
There was 1 error:

1) AppBundle\Tests\Entity\PropertyInfoTest::testPropertyInfo
TypeError: Argument 2 passed to phpDocumentor\Reflection\DocBlock::__construct() must be an instance of phpDocumentor\Reflection\DocBlock\Description or null, instance of phpDocumentor\Reflection\DocBlock\Context given, called in /project/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php on line 131

/project/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php:131
/project/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/ClassReflector/PropertyReflector.php:105
/project/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php:231
/project/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php:179
/project/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php:86
/project/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php:115
/project/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php:84
/project/src/AppBundle/Tests/Entity/PropertyInfoTest.php:39
```

The problem is caused by PHPUnit coming with `phpdocumentor/reflection-dockblock`. If you run it as a phar the version might be different to the one installed in your project.

Symfony 2.8 branch relies on `phpdocumentor/reflection-dockblock:^1.0.7`, while PHPUnit >= 5 comes with version 3.*.  Your test won't fail with phpunit 4.8.

You either have to use the legacy phpunit version, or upgrade Symfony I'm afraid.

**Comment by aumel** [comment]
@jakzal Thanks! I didn't notice the difference between PHPUnit and Symfony 2.8 for `phpdocumentor/reflection-dockblock`.
