### ISSUE TITLE
[RFC] Display the context on the exception pages

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#23589]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

On the exception page (see screenshot) we don't display the context. It can be useful.
What about adding it?

<details>
<summary>screenshot</summary>

![screenshot at 2017-07-19 13-57-34](https://user-images.githubusercontent.com/408368/28365862-85b3f582-6c8a-11e7-9891-361fcd958d16.png)
</details>

**Comment by nicolas-grekas** [comment]
What kind of context do you mean?

**Comment by lyrixx** [comment]
the context associated with a **log** message

**Comment by fabpot** [comment]
Any news on this one? @lyrixx Are you interested in working on it?

**Comment by lyrixx** [comment]
Sure ;)
