### ISSUE TITLE
Show current and default locales in web debug toolbar

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony#23583]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

I think this information could be useful for debugging multi-lang apps. For now I need manually dump `$request->getLocale()`/`$request->getDefaultLocale()` in code to see it. We can show it in the Request tab:
<img width="317" alt="screen shot 2017-07-19 at 11 28 19" src="https://user-images.githubusercontent.com/3317635/28357867-6b4aef26-6c75-11e7-948e-b761b7d3a6e5.png">

UPD: Noticed `_locale` in "Request Attributes" section of profiler's Request panel though.

**Comment by xabbuh** [comment]
This could indeed be useful as part of the translation panel. The `_locale` request attribute does not necessarily have to be the same as the locale used by the translator.

**Comment by bocharsky-bw** [comment]
As I see it in translation tab & panel:
<img width="179" alt="screen shot 2017-07-19 at 23 29 32" src="https://user-images.githubusercontent.com/3317635/28388122-46303754-6cda-11e7-838e-88124c10921d.png">
<img width="406" alt="screen shot 2017-07-19 at 23 29 47" src="https://user-images.githubusercontent.com/3317635/28388126-4a087f6c-6cda-11e7-942f-cd0a6b2925f5.png">
