### ISSUE TITLE
Cookie SameSite in lowercase

### ISSUE THREAD

**Issue by mikefrancis** [symfony/symfony#23585]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe
| RFC?             | no
| Symfony version  | latest

I am creating a Laravel wrapper around @aidantwoods [SecureHeaders package](https://github.com/aidantwoods/SecureHeaders) and am experiencing an issue with using `Symfony\Component\HttpFoundation\ResponseHeaderBag::set()` with a cookie.

The cookie I am trying to set has the attribute `SameSite=Lax` which comes from Aidan's package, which I then attempt to set but get the following `InvalidArgumentException`:

```The "sameSite" parameter value is not valid.```

This is because the check (https://github.com/symfony/symfony/blob/22f6091bc7bc3a22d60b802693ccbfa37a5fb3a3/src/Symfony/Component/HttpFoundation/Cookie.php#L129) references the `Cookie::SAMESITE_LAX` and `Cookie::SAMESITE_STRICT` constants which are both lowercase.

My suggestion would be to change this check to match case insensitively, but not sure how much of a breaking change this would be.

Would gladly submit a pull request for this!

**Comment by mikefrancis** [comment]
Just an FYI that in the spec for Same-site Cookies, both `Lax` and `Strict` have uppercase first letters.

This spec is still a draft though, but I would imagine this is what browsers would be looking at adopting?

**Comment by javiereguiluz** [comment]
In [RFC 6265](https://tools.ietf.org/html/rfc6265) they always talk about *"If the attribute-name case-insensitively matches the string ..."* and in https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00 they say:

```
If the "attribute-name" case-insensitively matches the string
   "SameSite", the user agent MUST process the "cookie-av" as follows:

   1.  If "cookie-av"'s "attribute-value" is not a case-insensitive
       match for "Strict" or "Lax", ignore the "cookie-av".
  2. ...
```

So, the comparison **must** be case-insensitive in this case.

**Comment by mikefrancis** [comment]
Might be jumping the gun but have submitted a PR for this ☝️
