### ISSUE TITLE
Compile Error: Declaration of Proxies\__CG__\Student::getYear() must be compatible with StudentModel::getYear(): Busybee\InstituteBundle\Entity\Year

### ISSUE THREAD

**Issue by crayner** [symfony/symfony#23597]
I may be in the wrong spot, as this may be a Doctrine issue.

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | yes/no
| Symfony version  | 3.3.5

I have stated to add return type declarations, but it appears that the Proxy copy does not copy PHP v7+ Return Type Declarations and therefore a Compile Error is generated.  

The getYear method in the StudentModel is defined as:

```
<?php
namespace Busybee\StudentBundle\Model;

use Busybee\InstituteBundle\Entity\Year;

abstract class StudentModel
{
    /**
     * @return Year
     */
    public function getYear(): Year
    {
        return $this->year;
    }
```
and
```
<?php
namespace Busybee\StudentBundle\Entity;

use Busybee\PersonBundle\Model\PersonInterface;
use Busybee\StudentBundle\Model\StudentModel;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Student
 */
class Student extends StudentModel implements PersonInterface
{
```
and 
```
<?php

namespace Busybee\PersonBundle\Model;

use Busybee\PersonBundle\Entity\Person;

interface PersonInterface
{

    /**
     * Get Person
     *
     * @return Person
     */
    public function getPerson();

    /**
     * Format Name
     *
     * @param array $options
     * @return string
     */
    public function formatName($options = []);
}
```

Year is defined in the use statements.  StudentModel is an extension of Student Entity class. I have had the same fault using int.

The Proxy in the doctrine/orm folder of the cache of Student does not contain the return type declaration.

```
<?php

namespace Proxies\__CG__\Busybee\StudentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \Busybee\StudentBundle\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());
        return parent::getYear();
    }
```

**Comment by iltar** [comment]
I think you have to update some dependencies, the proxy generation works fine with a newer version of the library

**Comment by Hanmac** [comment]
hm i also don't think that is a Symfony Problem but more a Doctrine Problem

**Comment by xabbuh** [comment]
make sure to use version 2 of the [proxy manager](https://github.com/Ocramius/ProxyManager)

Anyway, I'm closing here as this is not related to Symfony.

**Comment by crayner** [comment]
So, Doctrine.Common Version 2.5.3 seems to be the last stable version, but 2.7.0-DEV does work correctly.

**Comment by vivekaviva** [comment]
Error:
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Proxies\__CG__\App\Entity\Category could not be converted to string").

**Comment by DiegoJohan** [comment]
I had the same problem, i resolve it cleaning cache
