### ISSUE TITLE
[PHPUnit Bridge] Call to undefined method PHPUnit_Framework_TestResult::warnings()

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony#23598]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

I got the next error in tests:
> PHP Fatal error:  Call to undefined method PHPUnit_Framework_TestResult::warnings() in /home/travis/build/symfony/symfony-demo/vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/src/TextUI/ResultPrinter.php on line 293

This happens because simple PHPUnit load `PHPUnit_Framework_TestResult` from `vendor/phpunit/phpunit/src/Framework/TestResult.php` instead of `vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/src/Framework/TestResult.php` in the project. And it's a problem to remove PHPUnit from the project completely because some other dependencies still depend on it.

Actually, you can see this failure in latest Symfony Demo builds, for example: https://travis-ci.org/symfony/symfony-demo/jobs/255414154

**Comment by nicolas-grekas** [comment]
phpunit cannot be a dependency of other dependencies.
It must always be a root dependency (ie in "require-dev" only).
Both (the bridge and a -require-dev phpunit) are mutually exclusive.

**Comment by NicoHaase** [comment]
@nicolas-grekas if the demo project provided by Symfony itself is not able to run on Travis, how can this be an unsupported use case?

**Comment by nicolas-grekas** [comment]
what's the relationship with symfony-demo?

**Comment by javiereguiluz** [comment]
Symfony Demo tests on Travis CI are broken because of this issue. See https://travis-ci.org/symfony/symfony-demo/jobs/255414154

**Comment by xabbuh** [comment]
That's an issue of `dama/doctrine-test-bundle` which requires PHPUnit not in `require-dev` but in `require`: https://github.com/dmaicher/doctrine-test-bundle/blob/1.x/composer.json#L18

**Comment by bocharsky-bw** [comment]
I mean a lot of dependencies depends on PHPUnit like Doctrine, Monolog, etc. Yes, it's dev dependency, but it means even if we do not require it obviously in my `composer.json` when I do `composer install --dev` Composer will install PHPUnit in my project as a dev dependency anyway due to those relations. So as I understand PHPUnit and PHPUnit Bridge just can't be mutually exclusive because it's impossible do not install PHPUnit when installing composer dependencies with --dev.

**Comment by xabbuh** [comment]
Composer will only install dev dependencies of your own `composer.json` file. `require-dev` sections of your dependencies are not taken into account when you install your dependencies.

**Comment by bocharsky-bw** [comment]
Ah, I totally forgot about that. Then `dama/doctrine-test-bundle` is the only problem for Symfony Demo. I think this issue could be closed now, thanks!

**Comment by bocharsky-bw** [comment]
However, is there a way to fix the problem with `dama/doctrine-test-bundle` except to stop using it at all?

**Comment by nicolas-grekas** [comment]
Report/submit a PR on the bundle?
Closing meanwhile :)

**Comment by dmaicher** [comment]
@javiereguiluz I will look into the problem with my bundle + open a PR with a fix then on `symfony-demo` :wink:
