### ISSUE TITLE
DateTimeToLocalizedStringTransformer wrong timestamp when DateTime::ATOM used

### ISSUE THREAD

**Issue by zajca** [symfony/symfony#23602]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

I found out weird datetime transformation when using DateTime::ATOM format. Time after form handle is set to `00:01:00` 

form type:
```
class ItemPublishType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('publishSince', DateTimeType::class, [
                'format' => \DateTime::ATOM,
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ItemPublishDTO::class,
            'csrf_protection' => false,
        ]);
    }
}
```
DTO used:
```
class ItemPublishDTO
{
    /**
     * @Assert\GreaterThanOrEqual("now")
     */
    public $publishSince;
}
```
I made some debugging and find out that when `IntlDateFormatter` is resolved parse will return wrong timestamp
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L123

Timezone is set to UTC

this is a string I'm sending to server: "2019-01-08T10:00:00+00:00"

**Comment by mvrhov** [comment]
You are specifying the wrong format. The date implementation used under the hood is the intl one, so you should specify the format according to that.
You probably missed this in the docs.

**Comment by zajca** [comment]
Now I'm confused. How can I use format string? Intl does not provide RFC3339/ATOM which I want.

**Comment by zajca** [comment]
OK, when I use `DateTimeType::HTML5_FORMAT` it work's just fine. Actually docs didn't make this clear for me, but docsblock in https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php#L36-L57 
made this clear.

**Comment by nicolas-grekas** [comment]
Doc PR welcomed :)

**Comment by mvrhov** [comment]
@zajca: Yeah I agree, this info is only written at the `date_format` and not at the `format` attribute. Whereas the DateType includes the full and proper doc text.
