### ISSUE TITLE
[DI] Bad autowiring failure message with later named args

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#23606]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

From a training today :). Suppose this class:

```php
class MyCoolClass
{
    public function __construct(Logger $logger, $isDebug)
    {

    }
}
```

Because `Logger` is the wrong type-hint, I should receive this error:

> Cannot autowire service "AppBundle\EventListener\MyCoolClass": argument "$logger" of method "__construct()" references class "Monolog\Logger" but no such service exists...

And at first, I do! But suppose I specify the `$isDebug` argument:

```yml
services:
    AppBundle\Service\MyCoolClass:
        arguments:
            $isDebug: true
```

As *soon* as this arg is specified the error changes:

> Invalid constructor argument 2 for service "AppBundle\EventListener\MyCoolClass": argument 1 must be defined before.

The problem is:

A) AutowirePass correctly throws an `AutowiringFailedException` due to the bad `Logger` type-hint. But, exceptions are not thrown in this class, but stored for later
B) Because argument 1 appears to be missing, `CheckArgumentsValidityPass` throws the above exception
C) The `AutowireExceptionPass` - which would normally throw the exception from (A), is never called - because (B) already threw its exception.

The correct behavior is to always throw the first exception about the `Logger` class. But, I'm not sure how to do this. `AutowirePass` purposefully does not throw exceptions... because it waits to make sure the service wasn't removed from the container. But in this case, `CheckArgumentsValidityPass` steps in early and throws this other, less clear exception. It has no idea that the *true* exception is just waiting for the "ok" that the service wasn't removed.

I'm open to ideas... :). In general, the passes are becoming a bit more dependent on each other, and that's complicating things.

Cheers!

**Comment by nicolas-grekas** [comment]
That'd be a new 3.4 feature of course. Let 3.3 as is, this is not a bug,
just an less than ideal behavior.

**Comment by nicolas-grekas** [comment]
We should reduce coupling asap.

To do so, I think we can create some special placeholder for missing args:
each pass that detects a missing args put that special placeholder in place
of the arg. This placeholder could hold a message saying why some pass does
so. This message would be almost like the message of current exceptions
that are thrown instead.
Then, at the very late, a new compiler pass could turn these into
exceptions.
That would be a generalization of the current logic that applies only to
autowiring for now.
It would just need passes to agree on that placeholder thing and provide
decoupling on top, for that concern.

**Comment by nicolas-grekas** [comment]
Anyone willing to try this one? Not trivial, thus interesting :) @GuilhemN?

**Comment by GuilhemN** [comment]
@nicolas-grekas sorry I won't have the time to handle this one... I have to do a "break" for ~2 years for my studies.
This seems to be a nice proposal though.

**Comment by unckleg** [comment]
I'll go for it if someone does not overdo me. :) 

Keep up Baby junior is coming :dagger:

**Comment by backbone87** [comment]
just confirming this bug. it happened to me when i tried to autowire an argument with an interface from a 3rd party bundle, that wasnt setup for autowiring. the error message rly gave me a headache and pointed me into the **wrong** direction while searching for errors.

i would definitely classify this as a bug.
