### ISSUE TITLE
[WebProfiler] SF toolbar buggy after calling Sfjs.load

### ISSUE THREAD

**Issue by dpobel** [symfony/symfony#23609]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | 
| Symfony version  | 3.3.5

For the admin interface of eZ Platform 2.0, we are developing an application where the navigation happens with AJAX request. After an AJAX request corresponding to the navigation, the following is code is run:

```js
Sfjs.load(
    document.querySelector('.sf-toolbar').id,
    `/_wdt/${debugTokenFromHttpHeader}`
);
```

so that the toolbar is updated as if the full page was generated (implementation of this feature request https://github.com/symfony/symfony/issues/15456)

Somehow, this is working (the toolbar is updated for instance the Route name, the timing or the memory usage are updated) but after calling `load` the toolbar is buggy in the following ways:

1. if it's was minimized, it becomes maximized
1. it's impossible to minimized it again, clicking on *Close Toolbar* link has no effect
1. if the page does others AJAX requests, the AJAX requests counter is correctly updated, but it keeps on blinking even after the end of those requests

**Comment by ro0NL** [comment]
Kinda duplicates #15456

I believe this will be a core feature you can optin to :) see #22509

**Comment by javiereguiluz** [comment]
Closing as probably fixed by https://symfony.com/doc/current/profiler.html#updating-the-web-debug-toolbar-after-ajax-requests as @ro0NL said. If there are some issues after applying that feature, please create a new issue with the new error details. Thanks.
