### ISSUE TITLE
Add support for !!str in Symfony 2.7 too

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23607]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

In Symfony 3.4, we finally deprecated `!str` and used `!!str` for the YAML tag that casts values to strings. However, given that `!str` is wrong according to YAML spec, should we make this change too in Symfony 2.7 as a bug fix?

**Comment by fabpot** [comment]
We decided to deprecate and give an upgrade path, so fixing this as a bug fix in 2.7 is not possible.

**Comment by xabbuh** [comment]
I thought about just properly handle the `!!str` tag in 2.7 as a bugfix too as that's invalid YAML. The deprecation would still only happen in 3.4.

**Comment by nicolas-grekas** [comment]
@xabbuh OK on my side if the patch is small enough :)

**Comment by fabpot** [comment]
`!str`/`!!str` are really advance usages of the YAML component. I'm against adding support in 2.7.

**Comment by nicolas-grekas** [comment]
Closing then :)
