### ISSUE TITLE
Segfault during functional tests

### ISSUE THREAD

**Issue by JEDIBC** [symfony/symfony#23600]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

Since the upgrade to symfony 3.3, the functional tests generates a segfault. The only way to avoid it is to run the tests with `--process-isolation`.

I am not the only one having this problem as a bug report has been filled on PHP website : https://bugs.php.net/bug.php?id=74877

**Comment by nicolas-grekas** [comment]
Nothing we can do in Symfony, you did right reporting the bug to php...
