### ISSUE TITLE
Form labels force translation language

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#23611]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

I have a situation where I have set a locale for my application but there is a form in a different language where I want to have the labels available in that language.

inside the `vendor\symfony\Symfony\src\Symfony\Bridge\Twig\Resources\views\Form\form_div_layout.html.twig` we have `block form_label`. This block accepts translation key and the domain but no language 

```twig
`label : label|trans({}, translation_domain)`.
```

In a normal situation I would use something like this in order to force the language:
```twig
{{ translation.key | trans({}, 'messages', 'de') }}
```

In the form builder now we can do something like:

```php
$builder
    ->add('field', TextType::class, [
        'label' => 'translation.key',
        'translation_domain' => 'messages',
```

Would be of any use to add something like:

```php
$builder
    ->add('field', TextType::class, [
        'label' => 'translation.key',
        'translation_domain' => 'messages',
        'translation_domain_language' => 'de' //as language iso or whatever that can be passed from controller or other places
```

and to end up using inside the `block form_label` something like:

```twig
`label : label|trans({}, translation_domain, translation_domain_language)`.
```

**Comment by ogizanagi** [comment]
For reference, we're debating of a similar option for Intl form types in https://github.com/symfony/symfony/pull/23629.

**Comment by Herod** [comment]
In case this will help someone:

The way I do it now is actually overwriting the blocks, which I think it's a bit tricky:

Inside the form:
```php
$builder
    ->add('firstName', TextType::class, [
        'label'      => 'first.name',
        'label_attr' => ['translation_domain_language' => $this->language->getIso()],
])
```
Overwriting the twig file:
```twig
{% block form_label %}
...

{% set translation_domain_language = '' %}
    {% if label_attr.translation_domain_language is defined %}
        {% set translation_domain_language = label_attr.translation_domain_language %}
    {% endif %}

    <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
    <span></span>{{ label|trans({}, translation_domain, translation_domain_language)|raw }}</label>

....
{% endblock form_label %}
```

And for buttons I modify their specific block.

**Comment by mvrhov** [comment]
What about implementing a tag like trans_default_domain. But only for language

**Comment by xabbuh** [comment]
Is this really a common use case? I am not convinced we need to support in the core.

**Comment by xabbuh** [comment]
I am closing here as I do not think this is a very common use case and it should be easily solvable with a custom form theme overriding the `form_label` block.

**Comment by ghost** [comment]
In form class we have `configureOptions` method where we can `setDefaults` so we can easly set e.g. `'translation_domain'` which is nice. Why can't we have another option e.g. `'translation_locale'`? to force that locale on translated labels... My app has multiple languages but admin module is only in one language which is not the default app's locale so I want to easly force that locale on that form labels having only one translation file (for now) and I can't? I need to create custom form theme? In Twig there is easy way to do it but in forms this is obviously missing feature?
