### ISSUE TITLE
Symfony 3.3.5 - Can't generate new bundle

### ISSUE THREAD

**Issue by kironet** [symfony/symfony#23623]
| Q                | A
| ---------------- | -----
| Bug report?      | mb
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.5

I've just installed new Symfony 3.3.5 project.
Now I'm trying to generate new bundle

`    php bin/console generate:bundle`

But getting this:

>     > Generating a sample bundle skeleton into app/../src/Web/BaseBundle
>       created ./app/../src/Web/BaseBundle/
>       created ./app/../src/Web/BaseBundle/WebBaseBundle.php
>       created ./app/../src/Web/BaseBundle/Controller/
>       created ./app/../src/Web/BaseBundle/Controller/DefaultController.php
>       updated ./app/../tests/WebBaseBundle/Controller/DefaultControllerTest.php
>       created ./app/../src/Web/BaseBundle/Resources/views/Default/
>       created ./app/../src/Web/BaseBundle/Resources/views/Default/index.html.twig
>       created ./app/../src/Web/BaseBundle/Resources/config/
>       created ./app/../src/Web/BaseBundle/Resources/config/services.yml
>       created ./app/../src/Web/BaseBundle/Resources/config/routing.yml
>     > Checking that the bundle is autoloaded
>     FAILED
>     > Enabling the bundle inside app/AppKernel.php
>       updated ./app/AppKernel.php
>     OK

So fixed it in composer.json like this:

```
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
```

also tried like this:

```
    "autoload": {
        "psr-4": { "WebBaseBundle": "src/Web/BaseBundle" },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
```

But if I try to launch my project, I'm getting this error:

> Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to
> load class "WebBaseBundle" from namespace "Web\BaseBundle". Did you
> forget a "use" statement for another namespace? in
> /Volumes/U/Projects/e-shop/app/AppKernel.php on line 18

Here is my AppKernel

```
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Web\BaseBundle\WebBaseBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();

            if ('dev' === $this->getEnvironment()) {
                $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
                $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            }
        }

        return $bundles;
    }
```

What can be possibly wrong in totally new project? 
Thanks for help.

**Comment by javiereguiluz** [comment]
@kironet thanks for reporting this issue and I'm sorry about this.

However, the bundle generator tools are managed in a different repository than Symfony. So I've copied your issue to https://github.com/sensiolabs/SensioGeneratorBundle/issues/567 and that's why I'm closing this one.

**Comment by luv-vik** [comment]
Just run this command
`composer install` or `composer update`
