### ISSUE TITLE
Custom user authentication loading/refreshing user twice - workflow issue?

### ISSUE THREAD

**Issue by hcomnetworkers** [symfony/symfony#23622]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

We have a custom user provider created based on [this documentation](https://symfony.com/doc/current/security/custom_provider.html) and a custom authenticator based on [this documentation](http://symfony.com/doc/current/security/custom_password_authenticator.html). Furthermore we trigger the firewall ourselves during our routing, because we have dynamic firewalls depending on dynamic page paths and settings.

Now with cookie based session authentication, the [ContextListener](https://github.com/symfony/symfony/blob/6db73d3f4e47fad0be4973b83fb3402bd2321b35/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L168) calls ```refreshUser()``` on the provider.

The token is still not authenticated here. Only a first **authorization** request such as configured access directives on the route or a call to ```isGranted()``` will cause the token to be **authenticated**, which is fine, we can still manually authenticate the token if need be.

However, upon authentication the authenticator will call ```loadUserByUsername()```, loading the user again, despite the ```refreshUser()``` before.

What is the intended workflow here? Is the documentation faulty? Should the authenticator not load the user again? Or should the ContextListener not refresh the user? Because right now the only thing the refresh does is finding out if the user was deleted, but all the other checks, like the user's isActive-flag, are only checked during authentication. Maybe the ContextListener should immediately authenticate the user?

**Comment by iltar** [comment]
I don't think the firewall is designed to be dynamic. If anything, make your firewall simply protect everything and use access_control with `@Security` to regulate access. This way you can leverage all the default behavior without adding quirks or hacks. I recommend this, because the Security component is quite complex and it's hard to get a grasp of everything if you want to have a different behavior.

**Comment by hcomnetworkers** [comment]
If it was not designed to be dynamic, why can you configure multiple firewalls in the first place? We simply have the need for multiple firewalls. How they are activated, through a yaml-configuration or dynamically does not matter and that is not the problem here. Even with a single static firewall, the questions above don't go away.

**Comment by iltar** [comment]
You can have multiple firewalls, that's no problem. I just wouldn't bother dynamically doing this. There's no real loss in doing so. Make sure your `access_control` is configured as well, this is what would trigger the authentication.

**Comment by hcomnetworkers** [comment]
Thank you for your responses, but please read my questions.

When authentication triggers the custom authenticator is calling ```loadUserByUsername()```, but the ContextListener has already called ```refreshUser()``` before. This is a duplicate action with the latter not having any obvious reason for being there at all.

Every [UserAuthenticationProvider](https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php#L70) loads the user again upon authentication.

So again: What sense is there in having the refreshUser during the firewall listening?

**Comment by iltar** [comment]
The issue sounds vaguely similar to https://github.com/symfony/symfony/pull/19033#issuecomment-316377562
