### ISSUE TITLE
Standalone console application doesn't handle php7 \Error exceptions

### ISSUE THREAD

**Issue by FloatingMaster** [symfony/symfony#23640]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

Console application does not hangle php7 \Error fatal exceptions.

**example:**
```
public function execute(InputInterface $input, OutputInterface $output) {
    $foo = null;
    $foo->bar();
}
```
```
$ ./bin/console command
$ echo $?
0
```

**Comment by chalasr** [comment]
Unable to reproduce using the fullstack framework nor the console standalone (v3.3.5), exit code is 255 for both. Can you check that you are on the latest 3.3? If it persists, please provide a reproducer (fork of the standard edition or simple console application with enough code to reproduce).

**Comment by FloatingMaster** [comment]
Yes, my fault. Custom exception handler was registered.
