### ISSUE TITLE
crash when running ScriptHandler: The process has been signaled with signal 11

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#23641]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | -
| RFC?             | - 
| Symfony version  | 3.3.5

When running `composer install` when it comes to ScriptHandler, the installation fails 

```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception
                                              
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11".
``` 

When running `bin/console assets:install --symlink web/` the command succeed.

PHP version: `PHP 7.1.7-1+0~20170711133214.5+stretch~1.gbp5284f4`
Debian 9.x
Composer version 1.4.2

The complete log of `composer install -vvvv` is there: https://gist.github.com/tristanbes/8df5a9d534e37550f9b0e526a1bd1031

In the log, you have the error, but if you read the output, you can see that **all assets has been installed as if no error really happened.**
`[OK] All assets were successfully installed.`

**Comment by nicolas-grekas** [comment]
signal 11 is a segfault, meaning a bug in the php engine itself.
you should fill a bug report to bugs.php.net, nothing we can do in Symfony.
while doing so, please provide a minimal reproducer.
