### ISSUE TITLE
Improve bundle configuration documentation for `config:dump-reference`.

### ISSUE THREAD

**Issue by kherrera-ebsco** [symfony/symfony#23647]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

The information dumped by the `config:dump-reference` command would be far more valuable to me if each setting has additional information associated to it that described its purpose. The problem I am having is that even the official documentation does not document all of the settings that are available for a bundle. I sometimes have to analyze how the DIC extension uses the defined settings, digging into the source for the classes that actually use them.

I recommend that the configuration tree for each first-party bundle be visited (i.e. `FrameworkBundle`, `SecurityBundle`, etc.), `->info()` be used to add documentation for all available settings, and possibly include simple examples with the documentation.

**Comment by jakzal** [comment]
> The problem I am having is that even the official documentation does not document all of the settings that are available for a bundle.

This should be fixed in documentation whether we implement this feature or not.

I personally don't use config:dump-ref much but this request sounds reasonable to me. However, I think that flex might make this command even less used since we'll have configuration with basic examples done for us. For more advanced configuration we'll still need documentation.

**Comment by Simperfit** [comment]
Is there something to do here ?

**Comment by kherrera-ebsco** [comment]
The `DependencyInjection/Configuration.php` files would need to be updated for all bundles. I have moved on, so I'll close this.
