### ISSUE TITLE
WebProfiler + StreamedResponse = No toolbar

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#23651]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

When using `Symfony\Component\HttpFoundation\Response` to produce some output, the toolbar from WebProfilerBundle is correctly injected before `</body>` tag. But when using `Symfony\Component\HttpFoundation\StreamedResponse` the toolbar is not injected.

Would it be possible to inject toolbar into `StreamedResponse` too ?

Also, this "detail" should be noted in the documentation, so users of the `StreamedResponse` class won't get surprised.

**Comment by stof** [comment]
currently, it is not possible, as the event listener has no way to hook into the streamed rendering. and implementing such hook would be very hard, as streaming itself is not performed by Symfony but by your own code (so *you* would have to provide a hook to Symfony)

**Comment by javiereguiluz** [comment]
@jkufner thanks for reporting this. You are right about this, but sadly we won't fix it because it's too complicated and not worth it (that's why I'm closing this as "won't fix").

However, as you said, we can mention this limitation somewhere in the docs. We're trying to do that in https://github.com/symfony/symfony-docs/pull/8221

**Comment by fabpot** [comment]
I don't think it's "too complicated". It's more like that it does not necessarily makes sense. Streaming a response means that there is never a good time to inject the toolbar (besides the technical complexity that we don't have access to the stream).

**Comment by jkufner** [comment]
Output is available via the `$output_callback` parameter of [`ob_start()`](http://php.net/manual/en/function.ob-start.php). So technically it is possible to intercept `</body>` in the stream just before it is sent to a client.
