### ISSUE TITLE
[Form] Choice loader is not validated against unknown choice(s)

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#23679]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | a bit?
| RFC?             | no
| Symfony version  | 3.2

While having this form wtih a language type and custom choice type, i noticed submitting an unknown value triggers a transformation value (thus form error) on the choice field but not for the language field.

This worked OK in 2.7

```php
$form = $this->createFormBuilder(null, array('csrf_protection' => false)))
    ->add('a', LanguageType::class)
    ->add('b', ChoiceType::class, array('choices' => array(1,2,3)))
    ->getForm();
$form->handleRequest($request);
```

```
POST /
form[a]=x&form[b]=x
```

3.2
![image](https://user-images.githubusercontent.com/1047696/28618857-3832d720-7206-11e7-8904-46061409ff62.png)

2.7
![image](https://user-images.githubusercontent.com/1047696/28618638-6a264010-7205-11e7-8137-a545f2200d23.png)

**Comment by HeahDude** [comment]
This is the drawback of lazy loading choices, we cannot validate a submitted value without loading all choices.

I agree this is a kind of BC break though, we should fine a way to deprecate this path, to enforce usage of proper constraints.

**Comment by ro0NL** [comment]
Hm.. defining a constraint kinda defeats laziness as well no? Cant we use `loadChoicesForValues` as an optimized check?

**Comment by HeahDude** [comment]
>Hm.. defining a constraint kinda defeats laziness as well no?

Indeed, but without violating SRP.

**Comment by ro0NL** [comment]
I always liked choice type validating out-of-the-box for unknown choices. It's a nice safety net.

But you're right i never defined constraints for choice fields :)) i rely on the behavior of forms for this. Basically i choose between forms and the standalone validator per use-case, and mostly it's forms TBH.

It's at least weird to have different behavior between "choices" and "choice_loader".

**Comment by HeahDude** [comment]
>But you're right i never defined constraints for choice fields

And this is why I think a deprecation is necessary to make it clear.

**Comment by ro0NL** [comment]
Okay.. as forms already integrates constraint validation. Why not auto register a choice constraint... isnt that plain convenient?

**Comment by HeahDude** [comment]
IMO This is a good idea to consider when revamping type guessing.
