### ISSUE TITLE
Make tests pass on PHP 7.2

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23671]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7 & up

We have a policy of not adding anything to allowed failures, because that consumes a Travis job, and nobody cares checking what's there. In the past, I usually opened a PR adding that kind of line and fixing the code to make it green, and maintained that PR until it was ready for merge as a non-allowed-failure line.

If someone would like to help us doing that, that'd be awesome.

**Comment by Simperfit** [comment]
I could be helping on this, did you already opened a PR about that @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
please do!
