### ISSUE TITLE
cache:clear clears all kind of cache (even the application one)

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#23685]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no (not sure)
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >3.1

Hello,

After some weird problem in production, we just realized that using that running `bin/console cache:clear` **removes all kind of cache, even custom one defined by developper like using the `RedisAdapter`**.

In my team we are splitted between "it's normal" and confusion. This command has been around since `Symfony 2.0` and I would have never excepted to have an undocumented impact on a cache component introduced in `Symfony 3.1`

**My point is** : 
Symfony has his **internal cache** (metadata cache + `var/cache`) which is totally fine to clear when running `cache:clear` command 

Symfony provides cache component in order to use it for **our app** needs, so why, when we need to clear internal Symfony cache (`var/cache`) this command also earase all keys for our application cache ?

I think it's a dangerous behaviour because:
- By default, in standard edition `cache:clear` is called from `post-script` in `composer.json`. So each time we deploy and run composer install. It'll remove all cache, even if you don't want to.
- This feature (or bug :p) is not documented

We deliver 5-20 times per day, so we resolved this issue by no longer `cache:clear` the application removing it from the `composer script section` (that will lead all developpers to weird behaviour after adding some libraries, because it won't be done automatically).

Maybe I don't have the correct argument **but** can you  please provide your point of view to what led you to this decision, and how to keep our application cache while still have the possibility  to delete internal symfony cache ? (please don't tell me that we have to use another cache bundle to be able to achieve that.... it would be so much waste)

imho, we should have a way to clear all internal symfony cache in a separate way from the cache we use for our application.

Thank you :-)

**Comment by nicolas-grekas** [comment]
We fixed this issue in Blackfire by redefining the "clearer" of the "cache.app" root service to a specific one, not tagged as `kernel.cache_clearer`.
Then, clearing of app cache is done via `cache:pool:clear`.
I don't know if the current default behavior is a good default. Why not, provided it's documented and easy to turn into a dedicated command. Not sure that's the case right now.
WDYT?

**Comment by tristanbes** [comment]
I mean the case when you want to clear all cache (including your app) is very rare (almost impossible in fact for large applications).

to me the better solution would be to separate by default in 2 commands. 

An alternative to 2 separate commands would be more options to the existing one like
`cache:clear --pool=internal`
`cache:clear --pool=app`
`cache:clear --pool=app.memcache_custom`
or something like this.

Having to refine the cache.app service by removing a tag is pretty advanced, and is bad for DX. I mean if the situation was inversed, I would be ok, but it's quite the opposite: the current situation covers the 1% need and breaks the 99% others.

What do you think ?

**Comment by nicolas-grekas** [comment]
About the command, there is already one: `cache:pool:clear`.
About changing the current default behavior of `cache:clear` clearing `cache.app` derivatives, we have to decide if that a BC break or not.
The wiring I gave is advanced for sure, I didn't post it saying there is no issue. Quite the contrary. Just hinting an immediate solution (a few lines of yaml), and helping the one implementing the change in FrameworkBundle if we decide to do it :)

**Comment by nicolas-grekas** [comment]
Here is the required config, in `services.yml`:
```
services:
    cache.app_clearer:
        class: Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
```

this overwrites the `cache.app_clearer` alias (which defaults to `cache.default_clearer`, which itself has the `kernel.cache_clearer` tag.).

Then, clearing will only happen if you do `./bin/console cache:pool:clear cache.app_clearer` (or any specific pool.)

**Comment by tristanbes** [comment]
Thank you for the quick solution indeed :)

Well, to me it's not BC break if we change the current behaviour of `cache:clear` for 2 reasons:
 * it's undocumented feature. developper doens't know that their cache pools are going to be removed when real world cases are very rare if you want to clear pool cache on `cache:clear`
 * it's never going to be released for 3.x branches if it's treated as BC break 👎 

But it's only my opinion. Would love to see what other developpers or core team thinks on this.

**Comment by javiereguiluz** [comment]
This has also bugged me in the past. I agree that it's unexpected that the "clear:cache" deletes everything. The "data cache" (related to Cache component) is very different from the "cached application" (the result of "compiling" the services, routes, annotations, etc.)

**Comment by nicolas-grekas** [comment]
@javiereguiluz to be accurate, the Cache component relates and already handles both "data cache" and "cached application". The vocabulary in place is "cache.app" and "cache.system", which are the services from whom all pools derivate, with the exact same semantic you describe (in more abstract terms: `cache.app` derived pools are for "model-sourced items", and `cache.system` ones for "code-sourced items".)

**Comment by robfrawley** [comment]
Developers are already relying on the behavior of `cache:clear`, whether it is in their deploy scripts or elsewhere, and changing that before 4.x seems like a BC break to me.

That said, I also understand how this behavior would confuse some. Why not simply add an array argument to the command that allows passing context(s). That addition should allow those who want to remove specific cache contexts to do so without changing the default behavior. I'd be happy to contribute a PR if this is desirable and no one else is interested or has the time to do so.

**Comment by nicolas-grekas** [comment]
anyone willing to give this a try?

**Comment by stof** [comment]
if we want to change the behavior in 4.x, we have to give a way to opt-in the new behavior for 3.4 already, and display a deprecation warning when using the old behavior (and this will solve @tristanbes's concern about this change never reaching 3.x, as it would be opt-in in 3.4)

**Comment by tristanbes** [comment]
@nicolas-grekas I'm not sure I can perform this, but i'm willing to give a try. Can you tell me what do you want for an approach ? 

- Change the default attribute  `clearer="cache.app_clearer"` from services created when you create new cache pools, and create a new clearer name that will be grabbed by the `cache:pool:clear` command  ?
- something else ? 

Thanks

**Comment by tristanbes** [comment]
note : I no longer have the time to take care of this.

**Comment by nicolas-grekas** [comment]
I'm on it

**Comment by nicolas-grekas** [comment]
I'll submit a PR on 3.4 to change the behavior there. I think it's the best thing do to, with an UPGRADE note.

**Comment by nicolas-grekas** [comment]
See #24383
