### ISSUE TITLE
[RFC][DX] New command to debug form types

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#23688]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

These are some questions and issues that we could make us when we are building/using a form type or type extension:
* Why is not my extension being applied to the form type?
* Why is not available my new option in the child type?
* What are the defined options for my form?
* What options are required?
* I want to modify the default value of an option but I don't know if this value is allowed, where was this option defined to know that?
* etc.

Generally, I use the documentation to know what options are available, required, etc. I guess that keeping this options list updated is quite cumbersome and still there are options missing, e.g those defined by type extensions.

What about add a new command `debug:form` to get information from form types?

![debug-form](https://user-images.githubusercontent.com/2028198/29007125-c3508cd6-7aca-11e7-91e2-c2b509847db5.png)

Can this help us?

**Comment by robfrawley** [comment]
I would absolutely find value in such a debug command.

**Comment by theyoux** [comment]
Great feature!

**Comment by flip111** [comment]
One of the things i always have to look up ...

**Comment by pribeirojtm** [comment]
Hi there,

I'm using this command, but I think is something that could be also useful to add to it.

I don't see any possibility to check the fields of the given form to this command. How can I check form fields types? I thought this command would provide such functionality, but I don't know how.

Thanks.

**Comment by xabbuh** [comment]
@pribeirojtm Can you open a new issue if you would like to propose enhancements for an existing feature? Comments on closed issues/PRs are likely to get lost.
