### ISSUE TITLE
Please add getter methods for private workflow properties

### ISSUE THREAD

**Issue by Guite** [symfony/symfony#23695]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x

Please add getter methods for the following properties:

* Symfony\Component\Workflow\Workflow#markingStore
* Symfony\Component\Workflow\MarkingStore\MultipleStateMarkingStore#property
* Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore#property
* Symfony\Component\Workflow\SupportStrategy\ClassInstanceSupportStrategy#className

Currently the only (dirty) way to access this information seems using Reflection.

**Comment by lyrixx** [comment]
Could you tell us why you need theses properties?

**Comment by Guite** [comment]
A graphical workflow editor which receives a workflow name and fetches all required properties. The user can then change stuff and copy the updated workflow definition in either YAML or XML.

![editor](https://user-images.githubusercontent.com/277531/28956134-5a493606-78eb-11e7-914e-abcafbe7b65b.jpg)

**Comment by lyrixx** [comment]
It's a bit weird to me to use an already configured workflow at runtime. Why don't you build your tool on top of the configuration schema ? More over, it looks like you almost already did it :) 

Finally, The `MarkingStore` is an interface so it can be something different than `MultipleStateMarkingStore` or `SingleStateMarkingStore`.
And it's the same for `SupportStrategy`.

So your implement will be broken if someone use something different thant the default configuration. And I occurs quite often. For exemple, some people store the state as a bit mask field.

**Comment by Guite** [comment]
> weird to me to use an already configured workflow at runtime

Consider that the workflow is provided from another party than a potential user of it. The developer (provider) can not know in advance whether it will fit the need of all users. Thus, the user could add another state and save it using another name for example.

> Why don't you build your tool on top of the configuration schema ?

Because I do not want to go away from the Symfony defaults, but simply provide a simple UI for that.

> More over, it looks like you almost already did it :)

The editor is fully working. The only current drawback is that the properties mentioned above need to be read using reflection which looks a bit unstable and short-living.

> Finally, The `MarkingStore` is an interface... and it's the same for SupportStrategy.

Actually these properties are only read to provide a reasonable value in the corresponding form fields (see the top right of the screenshot above) so a default value is read from the workflow being loaded.

Would it be possible to add something like `getName()` to the `MarkingStore` interface? For example `MultipleStateMarkingStore` would return `multiple_state` here. At some point the logic for mapping this string to the class probably exists already. Similarly a support strategy could return the "subjects" it supports.

If you think that this extension is dumb just close this issue.

**Comment by lyrixx** [comment]
> Would it be possible to add something like getName() to the MarkingStore interface? For example MultipleStateMarkingStore would return multiple_state here. At some point the logic for mapping this string to the class probably exists already. Similarly a support strategy could return the "subjects" it supports.

I will be a BC break and you don't need it. You can simply use `instanceof`.

> If you think that this extension is dumb just close this issue.

No no ;) I just want to be sure you really need all theses getter and if you are aware of the lack of your implementation. 

All the getters you are asking are not harmful for the component so I'm quite open to accept the corresponding PR.

**Comment by Guite** [comment]
> You can simply use instanceof.

Which requires that I know all existing implementations of the interface...

**Comment by lyrixx** [comment]
I will be the same with getName. If **my** custom implementation return `yolo`, what are you going to do ?

**Comment by Guite** [comment]
Use `yolo` because this is the identifier used in workflow definitions to utilise this implementation?

**Comment by Guite** [comment]
Currently:
```
if ($markingStore instanceof \Symfony\Component\Workflow\MarkingStore\MultipleStateMarkingStore) {
    $markingStoreType = 'multiple_state';
} elseif ($markingStore instanceof \Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore) {
    $markingStoreType = 'single_state';
} elseif ($markingStore instanceof \Your\CustomMarkingStore) {
    $markingStoreType = 'yolo';
}
```

Proposed:
```
$markStoreType = $markingStore->getName();
```
or
```
$markStoreType = $markingStore->getIdentifier();
```

**Comment by lyrixx** [comment]
According to your screenshot and with an hypothetical `MarkingStore::getIdentfier` :
For the "MarkingStore" form type: `yolo` could fit. But not for the "State field" form type.
For exemple, the state field could be store in N column (many flags) or even outside the entity (in another table for instance)

So basically, for the "Marking Store" form type, the best way (IMHO) is to use the class name.
And if the class name is in [MultipleStateMarkingStore, SingleStateMarkingStore] then you can use the getName. If it's not the case, you **can not guess** how not where the state is stored.

So I'm :-1: for adding `MarkingStore::getIdentfier` or `MarkingStore::getName`

**Comment by lyrixx** [comment]
Why did you close this issue? the associated PR is not merged yet.

**Comment by Guite** [comment]
Oops sorry.
