### ISSUE TITLE
[Cache] DoctrineAdapter should filter bool false values

### ISSUE THREAD

**Issue by lstrojny** [symfony/symfony#23696]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

Doctrine returns `false` for cache key misses but the DoctrineAdapter does not filter those values, therefore leading to cache items that are a hit but are of value false.

Something like this should fix it:

```
--- src/Symfony/Component/Cache/Traits/DoctrineTrait.php
+++ src/Symfony/Component/Cache/Traits/DoctrineTrait.php
@@ -27,7 +27,7 @@ trait DoctrineTrait
     {
         $unserializeCallbackHandler = ini_set('unserialize_callback_func', parent::class.'::handleUnserializeCallback');
         try {
-            return $this->provider->fetchMultiple($ids);
+            return array_filter($this->provider->fetchMultiple($ids), function ($value) { return $value !== false; });
         } catch (\Error $e) {
             $trace = $e->getTrace();
```

**Comment by nicolas-grekas** [comment]
That's not what the MultiGetCache interface of Doctrine says:
https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/MultiGetCache.php

so, if there is a bug, it's in the implementation that returns false for misses, not on Symfony's side.
Did I miss something?

**Comment by lstrojny** [comment]
@nicolas-grekas Interesting hint!

Managed to reproduce it

```php
<?php
include 'vendor/autoload.php';

$memcached = new Memcached();
$memcached->addServer('localhost', 11211);
$memcachedCache = new \Doctrine\Common\Cache\MemcachedCache();
$memcachedCache->setMemcached($memcached);

$adapter = new \Symfony\Component\Cache\Adapter\DoctrineAdapter(
    new \Doctrine\Common\Cache\ChainCache([new \Doctrine\Common\Cache\ApcuCache(), $memcachedCache])
);

$k = str_repeat('b', 246);

$item = $adapter->getItem($k);
var_dump($item->isHit(), $item->get());
```

Output:
```
bool(true)
bool(false)
```

Reason is: `\Doctrine\Common\Cache\MemcachedCache::doContains()`

This is the implementation:

```
return false !== $this->memcached->get($id)
            || $this->memcached->getResultCode() !== Memcached::RES_NOTFOUND;
```

The result code is `int(33)` which is `RES_BAD_KEY_PROVIDED`. So yes, the bug is in doctrine cache.

**Comment by lstrojny** [comment]
Also it’s fixed in the latest version 👍
