### ISSUE TITLE
[Security][LDAP] add support for group mapping

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#23699]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.0

I think mapping of LDAP group information is a common enough use case that it should be considered to be added to core:
https://medium.com/@xobb/map-ldap-groups-to-symfony-3-security-roles-eb3ff09934a9

That being said, I would also like to see the addition of a query command line tool to help debug and test LDAP configurations. As such I am wondering if such more "advanced" features should not live in a separate Bundle? Obviously the logic would still be in the component, so I guess there would not be a lot left to put into said Bundle, so maybe its fine to add this stuff into the SecurityBundle.

**Comment by nicolas-grekas** [comment]
ping @csarrazi

**Comment by csarrazi** [comment]
Group information is specific to the LDAP implementation (Active Directory, Apache Directory, OpenLdap, Oracle Directory Server, etc.), and should not sit in the LDAP component. However, I don't have anything against having this in the security component.

**Comment by iltar** [comment]
I think this would be a nice addition. Currently we use the LDAP groups as roles and while this might be different per LDAP setup, it could probably be abstracted away so that it doesn't require a custom implementation in the security.

**Comment by lsmith77** [comment]
Yeah, I guess many people will just map ldap groups to roles so imho it would make sense to support this out of the box. But as you can see in the above linked code, there is also some need for extension points, like a getter for the default role.

**Comment by csarrazi** [comment]
By the way, this topic is actually already being discussed in #18803. I'd be glad if you could contribute to the discussion, so we can make this topic move forward. And at least decide on the way we want to expose this feature.

**Comment by lsmith77** [comment]
closing in favor of #18803
