### ISSUE TITLE
[RFC] Proposal to simplify the autowiring of container parameters

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23718]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

### The Problem

These days I'm updating some legacy Symfony applications to use Flex and modern Symfony practices. The first step was autowiring services. I loved the change. Everything is much better now and the automation (not magic) added by autowiring is fantastic to improve your productivity and code quality.

However, there's a minor thing about autowiring that bugged me: autowiring scalars.

```php
public function __construct(SomeClass $service1, $argument1, $argument2, $argument3)
{
    $this->service1 = $service1;
    $this->argument1 = $argument1;
    $this->argument2 = $argument2;
    $this->argument3 = $argument3;
}
```

I understand that this cannot be solved without adding magic. But in my case, **100% of scalar values are container parameters**. And I have literally hundreds of lines of service config like this:

```yaml
Acme\Blah\Blah\MyClass:
    arguments:
        $argument1: '%kernel.project_dir%'
        $argument2: '%app.container_param%'
        $argument3: '%app.another_param%'
```

It's so boring to do this. And so useless! I'd like to propose another way to solve this.

-----

### The Proposal

What if we allow to inject `ParameterBag` to inject all container parameters?

The above example would now look like this:

```php
public function __construct(SomeClass $service1, ParameterBag $params)
{
    $this->service1 = $service1;
    $this->argument1 = $params->get('kernel.project_dir');
    $this->argument2 = $params->get('app.container_param');
    $this->argument3 = $params->get('app.another_param');
}
```

And **no YAML/XML config would be needed** for services like this.

-----

### Comments

* *What about performance?* The number of container params has been reduced drastically in modern Symofny versions (by removing the `*.class` params) and params is an array which is easily cacheable by PHP 7. Impact in memory consumption should be minimal or null? To be confirmed...
* *What if you have thousands of container params?* Don't use this and keep using the existing solution to inject params individually.

**Comment by GuilhemN** [comment]
Another solution is merging https://github.com/symfony/symfony/pull/22187 which allows to inject named arguments in all services of a file :)

**Comment by javiereguiluz** [comment]
@GuilhemN yes, your proposal could work too ... although I don't like that it introduces yet another configuration option that users must learn.

**Comment by GuilhemN** [comment]
There's not much to learn, the syntax is the same as arguments. The difference is that it can be used for arguments **and** method calls arguments and that its content doesn't need to be used in **all** services for resources/defaults.

This could replace `arguments` in most cases in fact so if you're worried there is too much to learn, we could reduce the explanations about `arguments` and method calls arguments to focus on it.

**Comment by javiereguiluz** [comment]
I was referring to `bind`, which would be the new keyword/option to learn.

**Comment by theofidry** [comment]
@javiereguiluz why can't you already inject the parameter bag?

**Comment by GuilhemN** [comment]
For sure but that's not much to learn, there are options that are far less useful imo that we still introduced and documented (configurators, shared).

**Comment by javiereguiluz** [comment]
@theofidry have you tested it? Because I can't make that work at all 😞

**Comment by GuilhemN** [comment]
I guess you first have to register the `ParameterBag` as a service:
```
services:
    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface:
        factory: ["@service_container", getParameterBag]
```

**Comment by javiereguiluz** [comment]
@GuilhemN 

```
Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException:
Unable to resolve service "Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface":
method "Symfony\Component\DependencyInjection\ContainerInterface::getParameterBag()" does not exist.
```

**Comment by GuilhemN** [comment]
What if you explicitly don't autowire it?

**Comment by franzose** [comment]
@javiereguiluz, by injecting ParameterBag or the whole container you make dependencies of your class unclear. If you feel that you repeat the same tasks of declaring some classes' arguments again and again, shouldn't you consider refactoring?

**Comment by NicoHaase** [comment]
What about introducing a ConfigurationClass? It takes all scalars you need, delivers them through getters, and should be autowirable

**Comment by theofidry** [comment]
@javiereguiluz to be honest that's one thing I don't like about auto-wiring: bending designs to make it work better. IMO auto-wiring is a tool to help, not something you base your application on. So in your case I would say that yes: you inject scalar values, you need to manually wire them. And Symfony is not alone: even in frameworks with full auto-wiring like Laravel you need to do that.

Now if you really want to go that way:

- Inject the ParameterBag: dunno why that doesn't work but this doesn't sound right. Or maybe this has something to do with the compiled container... In any case it sounds like something that should be supported
- Have configuration classes as suggested as @NicoHaase 
- Have a parameter alias to take advantage of https://github.com/symfony/symfony/pull/21383

There may be other solutions like refactoring some pieces, using abstract service definitions, but hard to tell without your code.

**Comment by nicolas-grekas** [comment]
#22187 is exactly the solution we created to solve this issue, I think we just need everyone to focus on it so that it get some support and is merged.

**Comment by nicolas-grekas** [comment]
#22187 is just the explicit way to code your own conventions in *configuration*. Contrary to a propsal like this, or the annotation based ones, that force you to design/write your *code* in some way for the need of auto-configuration, which is doing things reverse side to me.

**Comment by javiereguiluz** [comment]
Let's close this in favor of #22187. Thanks!

**Comment by MGDSoft** [comment]
I think this approach to improve development speed is important. Because to add a argument in a service I need to move to other file, search service (or create his definition), and add argument, when I back to my service I lost my focus for this repetitive tasks....

This kind of things is not magic is to be efficient...

I know all symfony programmers must know how services system works but in 90% of time we need to save our time.

This problem is the same to add a "TAG", "priorities" ... in a service. What do you think about the use of Annotations?

**Comment by nicolas-grekas** [comment]
See #25288, which could be used instead.
