### ISSUE TITLE
[Form] EntityType - group by - multiple DB selects

### ISSUE THREAD

**Issue by mimol91** [symfony/symfony#23710]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

**UPDATE**
After some digging it seems that I was missing
``` ->select('country', 'continent')```

Hello. I've noticed that there is no easy way to optimize number of DB selects while using `group_by` attribute on EntityType.

Lets assume that we have `Continent` entity with relation to `Country`.
In select I would like to choose Country grouped by Continent. Its seems that this approach generate additional SQL query (for each of country). I've tried inner join, but it didnt work:
```
$form = $this->createFormBuilder()
            ->add('country', EntityType::class, [
                'class' => Country::class,
                'query_builder' => function (CountryRepository $er) {
                    $qb = $er->createQueryBuilder('country')
                    ->innerJoin('country.continent', 'continent');

                    return $qb;
                },
                'group_by' => function (Country $country) {
                    return $country->getContinent()->getName();
                },
            ])
            ->getForm();
```

In my case I've got a lot of parent entities witch two or three children and it generate a lot selects.
It would be great, that group_by could use join from query_builder, or solved in some other way.

Demo:
![demo-select](https://user-images.githubusercontent.com/2659069/28743397-e90e8d50-7459-11e7-8bd6-e4a4f64e6533.gif)

I've created symfony demo:
https://github.com/mimol91/symfony-select-demo
Example SQL:
```
DROP TABLE IF EXISTS `continent`;
CREATE TABLE `continent` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_6CC70C7C5E237E06` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `continent` (`id`, `name`) VALUES
(2,	'Africa'),
(1,	'Asia'),
(3,	'Europe');

DROP TABLE IF EXISTS `country`;
CREATE TABLE `country` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `continent_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_5373C9665E237E06` (`name`),
  KEY `IDX_5373C966921F4C77` (`continent_id`),
  CONSTRAINT `FK_5373C966921F4C77` FOREIGN KEY (`continent_id`) REFERENCES `continent` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `country` (`id`, `name`, `continent_id`) VALUES
(1,	'China',	1),
(2,	'India',	1),
(3,	'Japan',	1),
(4,	'Nigeria',	2),
(5,	'South Africa',	2),
(6,	'Egypt',	2),
(7,	'Russia',	3),
(8,	'Germany',	3),
(9,	'Turkey',	3);
```

**Comment by spalacios** [comment]
Thanks!!!
Add my solutions
![image](https://user-images.githubusercontent.com/7970320/43864221-81a84b48-9b35-11e8-9bb1-3d0a6e23578f.png)
![image](https://user-images.githubusercontent.com/7970320/43864265-9bd7f644-9b35-11e8-9913-7c27481d696d.png)
