### ISSUE TITLE
Genrerating a new bundle

### ISSUE THREAD

**Issue by stefanfr** [symfony/symfony#23715]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

I've just started a new Symfony project when I noticed that it isn't posible to add an new bundle.
I followed the steps show in te docs that didn't work. Next I tried to generate the Bundle with the same error et the end:

```
Attempted to load class "APIBundle" from namespace "APIBundle".
Did you forget a "use" statement for another namespace?
```
I tried downgrading symfony to 3.3.0 and everything is fine on this version.

**Comment by curry684** [comment]
Creating bundles is not an issue. The error you show indicates you did not follow PSR-4 autoloading conventions. Did you by any chance mix up casing on `Api` or not put the bundle in the `src` folder where it should be?

**Comment by stefanfr** [comment]
That's why I used the generate function mentioned in the docs. So the casing and placement wasn't the issue. I created a project with 3.3.0 and did the same steps without any problems.

**Comment by curry684** [comment]
Can you provide a link to the exact documentation page that you followed so we can be sure everyone's looking at the same docs?

**Comment by chalasr** [comment]
Closing as duplicate, see https://github.com/symfony/symfony-standard/issues/1098.
