### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#23725]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.5

After register type as
types:
UserRoleType: AF\Bundle\UserBundle\DBAL\Types\UserRoleType

I get exception:
Could not load type "UserRoleType"

**Comment by sstok** [comment]
This is part of the https://github.com/doctrine/DoctrineBundle, and make sure you clear the cache.
Secondly it will help if you provide more details, like the code of your type and the full configuration of doctrine.

**Comment by allfreelancers** [comment]
Please see https://github.com/fre5h/DoctrineEnumBundle/issues/102
