### ISSUE TITLE
`preload` twig function does not append "Link" header in response headers

### ISSUE THREAD

**Issue by thomas-dotworx** [symfony/symfony#23737]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.5

I wanted to use the `preload` function for twig but I do not get the "Link" headers appended to the server response. The problem is that `$event->isMasterRequest()` in `AddHeaderLinkListener` class returns `false` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/WebLink/EventListener/AddLinkHeaderListener.php#L38)

Can you help me @dunglas ?

**Comment by javiereguiluz** [comment]
Friendly ping to @dunglas to see if he has returned from his holidays. Thanks!

**Comment by jvasseur** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/WebLink/EventListener/AddLinkHeaderListener.php#L38 is not the problem, links sould only be added to the master request since headers from sub-requests are ignored. And since the `preload` function is always adding links to the master request (https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/WebLinkExtension.php#L60) it should work without problems for sub-requests.

**Comment by Simperfit** [comment]
@thomas-dotworx What's the issue since @jvasseur is right ?

**Comment by thomas-dotworx** [comment]
The `AddLinkHeaderListener` does not append the link header for me.
When I copy the exact piece of code to my custom response listener the headers get appended though. 

Here's my code:
```php
class ResponseListener
{
    private $_enabled;
    private $_serviceContainer;
    private $_authChecker;

    public function __construct(Container $serviceContainer, $enabled, AuthorizationCheckerInterface $authChecker)
    {
        $this->_enabled = $enabled;
        $this->_serviceContainer = $serviceContainer;
        $this->_authChecker = $authChecker;
    }

    public function onKernelResponse(FilterResponseEvent $event)
    {
        $response = $event->getResponse();

        if ($event->isMasterRequest()) {
            // Set headers
            $responseHeaders = $response->headers;
            $responseHeaders->set('strict-transport-security', 'max-age=31536000; includeSubDomains');
            $responseHeaders->set('X-XSS-Protection', '1; mode=block');
            $responseHeaders->set('X-Content-Type-Options', 'nosniff');

            $linkProvider = $event->getRequest()->attributes->get('_links');
            if (!$linkProvider instanceof \Psr\Link\LinkProviderInterface || !$links = $linkProvider->getLinks()) {
                return;
            }
            $serializer = new \Symfony\Component\WebLink\HttpHeaderSerializer();
            $responseHeaders->set('Link', $serializer->serialize($links), false);

        }
    }
}
```

**Comment by thomas-dotworx** [comment]
My config file:
```yml
acme.response_listener:
       class: AcmeBundle\Listener\ResponseListener
       arguments: ["@service_container", '%trim_response_enabled%', '@security.authorization_checker']
       tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
```

**Comment by Simperfit** [comment]
@thomas-dotworx Do you want to try povided a PR with the fix ?

**Comment by Simperfit** [comment]
Status: Reviewed

**Comment by thomas-dotworx** [comment]
Just figured out that I did not enable `web_link` in my config file. That's missing in the docs or did I just oversee that? Thanks!

**Comment by thomas-dotworx** [comment]
So I guess this will be done here symfony/symfony-docs#7515

**Comment by votemike** [comment]
For anyone finding this issue because they think `preload` isn't working in a 3.3 application (or one not using Flex), as @thomas-dotworx said, you need to enable web_link in your config file.
```
framework:
    web_link:
        enabled: true
```
In applications using flex instead of the symfony bundle as a whole, it seems to be enabled by default.
