### ISSUE TITLE
[SecurityBundle] Class name parameter is not yet resolved in AddSecurityVotersPass

### ISSUE THREAD

**Issue by pjarmalavicius** [symfony/symfony#23733]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

When voter service class is parameter, it is not yet resolved while checking if it implements VoterInterface.
Maybe type of AddSecurityVotersPass should be "optimization"?

**Comment by iltar** [comment]
The compiler pass itself isn't an optimization pass though. I'm more curious as of why your service definition's class is a parameter and not a class name...

**Comment by pjarmalavicius** [comment]
Actually I got this error in in third party bundle. But still if it's possible to define class name as parameter then Compiler pass should handle that.

**Comment by iltar** [comment]
If this feature is supported, it should probably be done as one of the first things, before all the other compiler passes run.

**Comment by chalasr** [comment]
The right way to solve this would be to resolve the parameter in the pass as we do in https://github.com/symfony/symfony/blob/2fed6f31c9410ee6acf002f5693c0e9b17725b0c/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php#L47 right?

Same concern as @iltar, not sure if we should add support for this, deprecate it in the passes supporting it already or do nothing at all.

**Comment by pjarmalavicius** [comment]
@iltar I think we can leave AddSecurityVotersPass as it was before and add new compiler pass of type "optimization" for voters validity check. I did PR for that

**Comment by iltar** [comment]
Just found a case where the class name is resolved inside the pass: https://github.com/symfony/symfony/blob/d024d795593bfa0773e312c5d5aa1cec4159d3d9/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php#L47

**Comment by pjarmalavicius** [comment]
Yes, it's the same as chalasr suggests, but if follow symfony best practices, then I would say that we also should write core to follow it. I mean class name parameters are not recommended and maybe one day it will be deprecated. Having check validity compiler pass doesn't depend on class parameter parsing and it also doesn't change what worked before
