### ISSUE TITLE
Is order of loaded bundles important?

### ISSUE THREAD

**Issue by kubawerlos** [symfony/symfony#23746]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

When I install fresh Symfony project with Symfony Installer and in `AppKernel.php` move `DoctrineBundle` to the top I'm getting deprecation error:

> The Symfony\Component\DependencyInjection\DefinitionDecorator class is deprecated since version 3.3 and will be removed in 4.0. Use the Symfony\Component\DependencyInjection\ChildDefinition class instead.

Before the moving there was no error. Is order of loaded bundles important? If so, is there any information about it?

**Comment by stof** [comment]
@nicolas-grekas do you have an idea why the reporting of the deprecation could be missing in one case ?

**Comment by kubawerlos** [comment]
@stof I've found out - if `FrameworkBundle` is loaded first it loads `ChildDefinition` which create and alias:

```php
class_alias(ChildDefinition::class, DefinitionDecorator::class);
```

and `DoctrineBundle` uses the new class when trying to use deprecated one.

However, when `DoctrineBundle` is loaded first it tries to load deprecated one which results with mentioned warning.
