### ISSUE TITLE
How to Override Templates from Third-Party Bundles for symfony4

### ISSUE THREAD

**Issue by Jackson8Zhang** [symfony/symfony#23740]
How to Override Templates from Third-Party Bundles for symfony4
![qq 20170801203749](https://user-images.githubusercontent.com/25034767/28825557-4e0f8b4a-76f9-11e7-86ff-d597f8fa2e0f.png)

**Comment by yceruto** [comment]
The new convention is still in progress (https://github.com/symfony/symfony/pull/23339) and if it's accepted you might be able to override this third-party template in `templates/bundles/FOSUser/layout.html.twig`.

Meanwhile, see this answer https://stackoverflow.com/a/45239524/4224384 for a workaround.

**Comment by Jackson8Zhang** [comment]
@yceruto ok.
