### ISSUE TITLE
Unique constraint violation on add after remove of a row in Symfony Persistent Collection form with Oracle

### ISSUE THREAD

**Issue by nkitsul-cyframe** [symfony/symfony#23768]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

$em->flush() right after handleRequest() produces unique constraint violation, in Symfony Persistent Collection, after a row violating the constraint is added and the other row violating same constraint is removed (thus there is no more constraint violation in theory).

See picture:
![image](https://user-images.githubusercontent.com/25300654/28885569-5872c7d8-7784-11e7-9dc2-efd1266131a3.png)

Dump around handleRequest():
`    dump($request->get('timesheet_detail')['payTransTime']);
    dump($payTransHeader->getPayTransTime());

    $form->handleRequest($request);
    die;
    $this->getDoctrine()->getManager()->flush();
    // flush() produces unique constraint violation exception.`

shows (in form): 

`    array:1 [▼
  1 => array:4 [▼
    "timesheetCodes" => "440C112D54425DCCE0531D0C510A219F"
    "timesheetQty" => "4.00"
    "payDate" => "2017-07-04"
    "dayNum" => "2"
  ]
]
TimesheetController.php on line 419:
PersistentCollection {#1213 ▼
  -snapshot: array:1 [ …1]
  -owner: PayTransHeader {#1225 ▶}
  -association: array:15 [ …15]
  -em: EntityManager {#1751 …11}
  -backRefFieldName: "payTransHeader"
  -typeClass: ClassMetadata {#1221 …}
  -isDirty: false
  #collection: ArrayCollection {#1214 ▼
    -elements: array:1 [▼
      0 => PayTransTime {#3283 ▼
        -id: "26536DDDC72F49C0B7DA4C6599174336"
        -timesheetQty: "2"
        -payDate: DateTime {#3286 ▶}
        -dayNum: 2
        -payTransHeader: PayTransHeader {#1225 ▶}
        -timesheetCodes: TimesheetCodes {#3268 ▶}
      }
    ]
  }
  #initialized: true
}
`
Or see the dump output above as a picture:
![image](https://user-images.githubusercontent.com/25300654/28885715-da934c4c-7784-11e7-9f9c-2dcb229c14cf.png)

The collection is declared as "cascade: persist" in entity yml definition.

It looks like in handleRequest() either:
- Inserts are done after deletes.
- Or flush() is not fires after deletes.

Wrapping entire code in beginTransaction() ... commit(), in the hope that it would verify constraints violations all at once at the very end, did not help.

It looks likea symfony/doctrine bug?

The only workaround, we were able to come up with was to turn off "cascade: persist" and do removal of collection elements by hand above "handleRequest()", do flush() and persist collection elements by hand after "handleRequest()". It does not look like a clean solution.

**Comment by nkitsul-cyframe** [comment]
It is Symfony/Doctrine integration with Oracle problem.

**WORKAROUND:** We found out that it is problem specific to Oracle. By default, oracle creates INDEXES and CONSTRAINTS as IMMEDIATE. Doctrine's UnitOfWork::commit() assumes that constraints are DEFERRABLE.

So, the workaround, is to use DEFERRABLE unique constraints.

Since indexes can not be deferrable in Oracle, you should set them as non-unique, and use constraints instead.

So, give Oracle SQL commands similar to:

```
DROP INDEX "INDEX_NAME_IDX";
CREATE INDEX "INDEX_NAME_IDX" ON "TABLE_NAME" ("COL_1", "COL_2", "COL_3");
ALTER TABLE "TABLE_NAME" ADD CONSTRAINT "CONSTRAINT_NAME_CSTR" UNIQUE ("COL_1", "COL_2", "COL_3") DEFERRABLE INITIALLY DEFERRED;
```

**Comment by dmaicher** [comment]
@nkitsul-cyframe so its a Doctrine related issue and should be reported there?
