### ISSUE TITLE
[Process] Special symbols are quoted

### ISSUE THREAD

**Issue by twifty** [symfony/symfony#23769]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

In order to escape command line args with the Process module, it is recommended to pass the args as an array:

```php
$url = 'git@github.com:foo/bar';
new Process(['git', 'clone', $url, 'cloned']);
```
A problem occurs when piping and/or chaining commands
```php
$url = 'git@github.com:foo/bar';
new Process(['git', 'clone', $url, 'cloned', '&&', 'cd', 'cloned']);
```
The above will generate `"'git' 'clone' 'git@github.com:foo/bar' 'cloned' '&&' 'cd' 'cloned'"`

Note the quoted '&&'.

Is it now necessary to build the command line string ourselves before using the module?

**Comment by nicolas-grekas** [comment]
Using an array as first argument is a new feature of 3.3 and yes, it escapes all argsw that's the feature in fact.
If you need &&, you need a shell, which you get if you pass a string instead of an array.
You may wonder how to escape then. There is no need if you use environment vars to inject values, eg via the $env arg of the constructor, or the new $env arg of eg start/run.

**Comment by nicolas-grekas** [comment]
You'll likely also want to inherit environment vars, see corresponding method to do so.

**Comment by twifty** [comment]
OK, just refactored my code to make use of the new env parameter, and I must say 'easy'. As a future addition, perhaps we could give command strings in the form "cd {dir} && cat {file}" then have the component `strtr` the env variable names for us. Prefixing each with '$', which is already in the php syntax for double quoted strings, is a little misleading.

Regarding the documentation though, it doesn't exist. The word 'env' doesn't even exist on http://symfony.com/doc/master/components/process.html for either the 3.3 or 4.0 version.

**Comment by nicolas-grekas** [comment]
@twifty would you like to contribute a doc PR on https://github.com/symfony/symfony-docs/?

> cd {dir} && cat {file}

that's a good, it would also provide portability of simple shell expressions

**Comment by nicolas-grekas** [comment]
See #23778
