### ISSUE TITLE
Customizing Symfony console exceptions

### ISSUE THREAD

**Issue by mohamadx** [symfony/symfony#23762]
Hello  

I want customize error exception or override with my exception handler in symfony console (see attached file). I was search in documents and google it already but I can't found the answer!  
Is it possible?  

![screen shot 2017-08-02 at 17 17 18](https://user-images.githubusercontent.com/15182195/28874338-b02b202a-77a6-11e7-870e-52e5dc3ebb0d.png)

**Comment by chalasr** [comment]
What kind of customization are you looking for? Is it styling e.g. changing background/foreground color?

**Comment by mohamadx** [comment]
I think it's better if I can register my Exception handler. Actually I want customize color, styling and message

**Comment by chalasr** [comment]
Right, are you using the fullstack framework (`symfony/symfony`) or the console solely?

**Comment by mohamadx** [comment]
No. I just use only symfony console for one of my CLI applications

**Comment by chalasr** [comment]
Then I think the best is to create your own `Application` extending the base one and overwrite `renderException()` into.

**Comment by mohamadx** [comment]
@chalasr Thank you so much  
My issue has been resolved
