### ISSUE TITLE
symfony/cache requires PHP 7.1.3

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#23775]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.6

symfony/cache requires "php": "^7.1.3", but 7.0 is still widely used and supported. Such big dependency change in a patch version (3.3.5 → 3.3.6) is really ugly and surprising (especially when one runs `composer update` on a machine with PHP 7.1 and deploys to a server with PHP 7.0).

Please change required PHP version back to PHP 7.0 and leave dependency change to PHP 7.1 for Symfony 3.4.

**Comment by mvrhov** [comment]
This will probably get fixed. However to prevent this from happening you should actually tell the composer that it should pick the packages for a specific php version... e.g.

```js
    "config": {
        "platform": {
            "php": "5.5.9"
        },
        "sort-packages": true
```

**Comment by javiereguiluz** [comment]
But the `composer.json` of symfony/cache 3.3 branch says:

```json
"require": {
        "php": "^5.5.9|>=7.0.8",
        "...": "..."
}
```

See https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Cache/composer.json#L23

**Comment by nicolas-grekas** [comment]
and the composer.json on 3.3.6 allows 7.1:
https://github.com/symfony/cache/blob/v3.3.6/composer.json

**Comment by xabbuh** [comment]
closing here as there is no such requirement

@jkufner maybe some of your other dependencies required PHP 7.1.3

**Comment by jkufner** [comment]
Sorry, my bad. Somehow I mixed up doctrine/cache with symfony/cache and new version got into lock file :)

@mvrhov Thank you. That helps a lot.
