### ISSUE TITLE
[Process] Allow writing portable "prepared" command lines

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23778]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

With 3.3, we already support "prepared" command lines.
```php
$process = new Process('echo $abc && echo $def');
$process->inheritEnvironmentVariables(); // unrelated, just for FC

$process->run(null, array('abc' => 'ABC', 'def' => 'DEF'); // echoes ABCDEF
```

It works quite simply: it just creates the corresponding env vars and leverages the underlying shell to parse the command line and use the values. The `$abc` syntax comes from `sh` of course, nothing we have to deal with fortunately.

BUT this comes with a drawback, namely: portability. Why? Because we rely on the shell to parse the command line :)
On Windows, the same command has to be written as `echo !abc! && echo !def!`, using the `!foo!` syntax from Windows' shell (`cmd.com`) to use env vars.

While creating a portable command line language is out of scope, we could at least provide some portable syntax for env vars injection.

One proposal as already been made, using curly brackets: `echo {abc} && echo {def}`.
WDYT?

**Comment by ScullWM** [comment]
I like the idea, could be great for test. 
But not sure about using it as a second argument of the run method.

**Comment by nicolas-grekas** [comment]
> not sure about using it as a second argument of the run method

that's not the topic, because that's already released as 2nd arg, for BC reasons :)

**Comment by twifty** [comment]
It could also be used to validate if all required env vars have been passed into the start/run methods.

**Comment by nicolas-grekas** [comment]
Maybe prefer SQL-like placeholders?
`echo :abc && echo :def`.

Anyone willing to give it a try?

**Comment by twifty** [comment]
> Maybe prefer SQL-like placeholders?
No, I often find those type of statements hard to read and easy to miss. A before and after token, such as the braces are much clearer.

**Comment by ro0NL** [comment]
> While creating a portable command line language is out of scope, we could at least provide some portable syntax for env vars injection.

Isnt that contradictory =/ can we really parse a command line?

What about defining a command line per OS, and let run() figure out which to use... could that work?

**Comment by Simperfit** [comment]
@ro0NL Yes I guess that could work, but the goal here is to provide something easy to use and working on all platform the same way.
