### ISSUE TITLE
Performance issues after upgrade to 3.2.13

### ISSUE THREAD

**Issue by pinkeen** [symfony/symfony#23770]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.13

I am not sure if this is a regression in symfony, it very well may be related to my environment. 
After recent composer update and upgrade to 3.2.13 the total execution time went up from ~90ms to ~1600ms (Symfony initialization time 30ms -> 800ms). Tested that on a page that does nothing more than just renders a static page using twig.

I have specifically tried downgrading only `symfony/symfony` to 3.2.12 to isolate the issue and indeed the performance goes back to normal.

Are you aware of any changes that would affect performance so severely?

BTW Haven't tested in prod mode.

**Comment by nicolas-grekas** [comment]
3.2 is not maintained anymore, you need to move to 3.3, where this should have been fixed.

**Comment by javiereguiluz** [comment]
@pinkeen sadly we stopped maintaining Symfony 3.2 just two days ago! Luckily, the transition from 3.2 to 3.3 should be smooth. Here you have the UPGRADE guide: https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md

**Comment by fabpot** [comment]
Is the slowdown from 3.2.12 top 3.2.13? If yes, then it should be reopened and fixed. We cannot have a last release with such a regression.

**Comment by nicolas-grekas** [comment]
Then, a Blackfire comparison would be really helpful.

**Comment by pinkeen** [comment]
Upgrade to 2.3 completely slipped my mind, too focused on the project itself (seems to be good that I can do that with symfony!).

Anyhow I created a blackfire comparison and it was evident that the DIC is recompiled on every request. I have no idea why it manifested itself after the upgrade but it seems to be the common issue of borked filemtimes (first thing that came to my mind after seeing the profile). Fixing date issues brought the performance back to normal. Still something must've changed with the cache invalidation mechanism because switching back and forth between 3.2.12 and 3.2.13 "turned the issue on and off".

Sorry for the false alarm, keep up the good work!
