### ISSUE TITLE
[Doctrine Bridge] Do not register form types if no form component

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#23788]
| Q                | A
| ---------------- | -----
| Bug report?      | "yes and no"
| Feature request? | "yes and no"
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x, probably ever since there is this bridge though (so 2.7 minimum ?)

I am currently using the Doctrine bridge on a Flex install. For some reasons, if I add a typehint to an action in a controller (`public function myAction(Request $request)` for example), it tries to load the `form.type_guesser.doctrine` service, which in turn implements an interface that is present in the Form Component.

I think that if the form component is not available, this service shouldn't be registered, as @sstok suggested it on Slack.

**Comment by Koc** [comment]
Possible duplicate of #23818

//cc @nicolas-grekas

**Comment by jakzal** [comment]
Is this still the case @Taluu ?

**Comment by xabbuh** [comment]
ping @Taluu :)

**Comment by Taluu** [comment]
Nope seems to do just fine. Closing. :}
