### ISSUE TITLE
[SecurityBundle] LogoutUrlHelper not found

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#23787]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

After updating my symfony/flex installation, the securityBundle throw this exception for the LogoutUrlHelper class who's not found in the vendor

![LogoutUrlHelpException](https://img15.hostingpics.net/pics/373122Capturedecran20170804a145138.png)
All the configuration is functional.
Any idea ?

**Comment by chalasr** [comment]
Fixed in https://github.com/symfony/symfony/pull/23755, the patch will be part of the next maintenance release (3.3.7).
