### ISSUE TITLE
Entity form type fails when submiting an empty value for non-string identifier type on Postgres

### ISSUE THREAD

**Issue by maryo** [symfony/symfony#23808]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

This is almost the same issue as https://github.com/symfony/symfony/issues/14583 but I am afraid nobody would notice this old closed issue.

I am using entity type with required set to `false` and the entity's id is set to uuid type using `ramsey/uuid-doctrine` package with Postgres. It uses a different doctrine type than native `guid` - https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidType.php named `uuid`. Doctrine maps it to `guid` Postgres type OFC but `$metadata->getTypeOfField($identifier)` returns `uuid`. So this condition is not satisfied
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php#L75

A solution would be to check native types instead.

```php
$databasePlatform = $qb->getEntityManager()->getConnection()->getDatabasePlatform();
$identifierMapping = $metadata->getFieldMapping($identifier);

if (Type::getType($metadata->getTypeOfField($identifier))->getSQLDeclaration($identifierMapping, $databasePlatform) === $databasePlatform->getGuidTypeDeclarationSQL($identifierMapping)) {
    // all types mapped to GUID
}
```

I can send a PR... but it's actually not very nice as well as filtering out those non-integer values in the condition above.

Why can't we filter out empty strings in all cases? Or at least skip `array('')` which covers entity type when both `multiple` and `required` is set to `false` (the values is an empty array in case when `multiple` is set `true`)? Or can we? Is there a case where empty string is not an empty choice?

**Comment by Tobion** [comment]
The problem is that empty strings could be a valid choice in other columns. For example varchar primary keys allow empty strings (in mysql and postgres for sure). See http://sqlfiddle.com/#!17/14518/1
But trying to select an empty string for a  GUID column will fail as the above example also shows. So it really depends on the column type what is allowed and what not.

Maybe the safer solution is to just also add an explicit case for `uuid`, i.e. `'guid' === $metadata->getTypeOfField($identifier) || 'uuid' === $metadata->getTypeOfField($identifier)`

**Comment by Tobion** [comment]
@maryo can you create a PR?

**Comment by maryo** [comment]
I know it can be valid in SQL, I'm just not sure if empty string is always treated as an empty choice or not because the Form component is quite complex (there is `FormUtil::isEmpty`, `empty_data` option and so on).

Your proposal covers only this exact issue (custom DBAL type named `uuid`) but that's good enough for me.

**Comment by Tobion** [comment]
I guess `\Doctrine\ORM\Mapping\ClassMetadataInfo::$fieldMappings['columnDefinition']` is not set at this point which would reference the real column type. If that is not available, I don't see another solution.

**Comment by maryo** [comment]
@Tobion I think `columnDefinition` is even optional and rarely used at all. That's why I posted that snippet in the initial comment of this issue
```
Type::getType($metadata->getTypeOfField($identifier))->getSQLDeclaration($identifierMapping, $databasePlatform) === $databasePlatform->getGuidTypeDeclarationSQL($identifierMapping))
```
This one works. But... There are still soo many Postgres types that would fail
https://www.postgresql.org/docs/9.2/static/datatype.html
