### ISSUE TITLE
[Debug] Trigger a deprecation when an `@internal` class/interface/trait is used

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23800]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

We use `@internal` quite extensively, yet, the DebugClassLoader class doesn't warn when one uses such a tagged class/interface/trait.

We should trigger the same kind of deprecation as we already do for `@final`, with the added condition that the root namespace needs to be different (don't trigger within the same root namespace.)

**Comment by GuilhemN** [comment]
Do you have an idea of such implementation? A class is loaded only once so I don't see how we could always trigger the deprecation when necessary.

**Comment by nicolas-grekas** [comment]
In the case where one extends/uses/implements, it should be similar to what we do for final. Not sure we should do more (we maybe could, using the stack trace, but that might have to high of an impact.)

**Comment by GuilhemN** [comment]
Ok, I thought you talked about detecting the use of an internal class in the code which is indeed complicated.
:+1: for detecting extends/implements. Uses might be harder but why not if we find a clean solution :)
