### ISSUE TITLE
[DI] Allow using a class factory

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#23819]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Here's a proposal coming mostly from @nicolas-grekas (I helped a bit making the example :)).
Would you like to be able use a class factory to define your services?

Main benefits:
- service names based on the methods return type (or `@Alias`)
- arguments injection based on autowiring
- access to php functions at runtime (no need anymore of the expression language), that also means access to `getenv()`
- possibility to manually inline simple services

An example of how it could be used:
```yml
// services.yaml
imports:
    - type: service_factory
      resource: App\MyServicesFactory
```
```php
// src/MyServicesFactory.php
<?php

namespace App;

use App\Entity\Product;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Psr\Logger\LoggerInterface;

class MyServicesFactory
{
    private static $apiKey = 'foo';
    private $database;

    public function __construct()
    {
        // Constructor called with *no* argument
    }

    /**
     * @Tag(name="monolog.logger", channel="my_channel")
     * @Alias(id="my_service")
     * @Alias // when used with no id, the return type is used
     * @Param("strategies", tag="app.strategies")
     * 
     * @param StrategyInterface[] $strategies // it's the responsibility of a DI extension to populate this
     */
    public function myService(LoggerInterface $logger, iterable $strategies): MyServiceInterface
    {
      	$myService = new MyService($logger);
      	$myService->setSecret(self::$apiKey); // the service can be easily configured
      	$myService->setSecret(getenv('API_KEY')); // even dynamically
      	foreach ($strategies as $strategy) {
            $myService->addStrategy();
     	}

    	// Less flexible than an injected dep, but still a nice shortcut for private apps
        // benefits from type hinting (return type vs argument type can be verified by IDEs)
      	$myService->setDatabase($this->myDatabase()); 
  
      	return $myService;
    }

    /**
     * ExpressionLanguage not needed anymore.
     */
    public function myController(MyService $myService, Repository $doctrine): MyController
    {
      	return new MyController($myService, $doctrine->getRepository(Product::class));
    }

    protected function myDatabase(): DatabaseInterface
    {
      	return $this->database ?? $this->database = new Database('dns://...');
    }
}
```

Wdyt? This could be an alternative to https://github.com/symfony/symfony/issues/22407.

**Comment by nicolas-grekas** [comment]
Disclaimer: this borrows some ideas from Disco :)
And I think it has more potential than #22407 because it allows writting code that that is actually used at runtime (vs a DSL-like - which is nice BTW!)

**Comment by sstok** [comment]
Interesting, wondering would this also make https://github.com/container-interop/service-provider also easier to realize?

**Comment by shochdoerfer** [comment]
Almost as good as [Disco](https://github.com/bitExpert/disco) :) I like the idea of passing dependencies via method parameter, that solves quite a bit of the magic within Disco that I do not really like.

Are you able to register multiple factories? If so, how would you solve naming collisions?

**Comment by GuilhemN** [comment]
@sstok I don't think so, the implementation is different.

> Are you able to register multiple factories? If so, how would you solve naming collisions?

@shochdoerfer yes, that's just a resource. About conflicts, I'd say like right now, the latest service defined wins.

**Comment by Tobion** [comment]
I really like this proposal.

- It uses normal PHP code and does not require another format/language you need to learn, e.g. compared to #22407 
- Sometimes initializing services isn't that straightforward, e.g. Guzzle clients with complicated middlewares. So at first you think how to do it in PHP. And then you still have to transcode that to yaml or xml which doesn't make it easier. With this proposal you just have to do it once in PHP with a factory and you're set.

**Comment by shochdoerfer** [comment]
@nicolas-grekas  Any chance to join forces with [Disco](https://github.com/bitExpert/disco)? Like extending Disco to be able to use it as a common basis? Ping me if you are interested...

**Comment by fabpot** [comment]
For the record, #23834 looks much better to me.

**Comment by ro0NL** [comment]
@GuilhemN what about favoring #23834 for annotating. So the factory would implement i.e. `ServiceFactoryInterface` and have a static method that receives a id + definition configurator for each class method.

The factory itself is also a service.

**Comment by chalasr** [comment]
Is this still relevant?

**Comment by nicolas-grekas** [comment]
Closing as I think we drafted the idea, so can be referenced in the future when needed.
