### ISSUE TITLE
[WebProfilerBundle] Cache panel contains only data from the last render controller request

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#23820]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Empty symfony-standard project contains 5 cache calls in profile, but if I add simple render controller - the cache panel becomes empty (No cache calls were made.)

https://github.com/BoShurik/symfony-standard/commit/2b2a8c4935c1f751e9745ed7f9f24990e1826596

**Comment by tristanbes** [comment]
So, 7 august 2017 huh ? 
Isn't this issue reviewed @xabbuh since its the same as mine ?

To reproduce: https://github.com/tristanbes/symfony-cache-profiler-bug

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/26080
