### ISSUE TITLE
Overriding the TranslationExtension with the TransNode 

### ISSUE THREAD

**Issue by LoicChancerel** [symfony/symfony#23830]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I'm currently working on an app with several themes, not only graphic but concerning the content as well. Because of that, the translations might be different, depending on what theme is set.

To do this, we overrided the Symfony\Bridge\Twig\Extension\TranslationExtension and declared it as a service : 
``` 
<service id="twig.extension.trans" class="ThemeBundle\Twig\Extension\TranslationExtension">
            <argument type="service" id="translator"/>
            <argument type="service" id="liip_theme.active_theme"/>
</service>
```

In our custom TranslationExtension, we overrided the function trans and transchoice, and in our Twigs we're used to use the `|trans` method, which works like a charm.
But I'm currently working on implementing the [Sonata-Project](https://github.com/sonata-project), and it seems that it's using a different way of translation

We looked into the files and saw that the tag `{%- trans from 'domain' %}some_text{% endtrans -%}`  triggered this error : 

> The "Symfony\Bridge\Twig\Extension\TranslationExtension" extension is not enabled.

Which seemed logical as we overrided it, but wasn't really expected. In fact, we found out that this class, the original TranslationExtension, was called directly in the Symfony\Bridge\Twig\Node\TransNode.php file, at the line 63 : 
```
$compiler
    ->write('echo $this->env->getExtension(\'Symfony\Bridge\Twig\Extension\TranslationExtension\')->getTranslator()->'.$method.'(')
    ->subcompile($msg)
;
```
Actually it's called through the class TransTokenParser, which seemed triggered by the tag above.
I tried (just to be sure) to change it manually, and it's working now, but as it's not a good workaround at all, I'm here to ask about it.

Have we done something wrong or is it possible to correct it and maybe make it more dynamic ?

**Comment by dmaicher** [comment]
Maybe it would make more sense for you to overwrite/decorate the original symfony translator to have your custom logic? Then at least wherever you translate stuff (maybe one day you want to translate something not in a twig template?) your translator would be used consistently.

Seems it goes a bit too deep into symfony internals your approach.

**Comment by LoicChancerel** [comment]
I'll try to decorate the translator, it seems to be cleaner and as you said more consistent.

Thanks for your quick answer !

**Comment by xabbuh** [comment]
So we can close here?

**Comment by LoicChancerel** [comment]
Thanks again, it's all good
