### ISSUE TITLE
how to import services declared in different yml files in Flex-Enabled Symfony app?

### ISSUE THREAD

**Issue by mappedinn** [symfony/symfony#23849]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

In symfony application, services can be declared in different yml file and then imported in the `app/config/config.yml` as follows:

```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: config_extensions.yml }
```

So what about Flex-enabled Symfony application? I tried that in `config/services.yaml` but without success!!!

**Comment by fabpot** [comment]
There is no difference here. Flex does not change anything to Symfony, it is just a nice way to auto-configure Composer packages. So, importing from services.yaml should work.
