### ISSUE TITLE
Sub-Request 769 ms

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#23840]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Sub-Request execute:

769 ms
Total execution time
270 ms
Symfony initialization
35.25 MB
Peak memory usage

``` php
namespace AF\Bundle\WebBundle\Controller\Frontend;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class FooterController extends Controller
{
    public function viewAction(Request $request)
    {
        $homepageUrl = $this->generateUrl('homepage');

        return $this->render('AFWebBundle:Frontend/Footer:view.html.twig', array(
            'homepageUrl' => $homepageUrl
        ));
    }
}
```

**Comment by curry684** [comment]
What exactly is the problem?

**Comment by allfreelancers** [comment]
yes, too long time in empty controller, why?

**Comment by NicoHaase** [comment]
Run a profiler and have a look :) Stuff like XHProf or Blackfire is not that complicated to set up and will help you not only for this question.

And I don't see any empty controller there. It generates a URL and renders a view.

**Comment by allfreelancers** [comment]
@NicoHaase generation an Url сould take 769 ms?

**Comment by curry684** [comment]
For all we know you're fetching the URL parameters in real time from a webserver in someone's basement in Peru, or running this on a webserver that is running at a system load of 50.

Symfony itself is blindingly fast. You are apparently surprised by something it does slow. We can't debug it without all of your code, nor are we inclined to personally debug every issue someone has anywhere in the world. So help us help you and do the initial research of what is actually causing the delay. If you find something far more detailed than "rendering an empty controller" than you're now giving us that actually points towards an issue in Symfony we're happy to help.

**Comment by fabpot** [comment]
I'm closing this issue. Without numbers coming from a profiler, there is nothing we can do, and it's impossible to know if there is a problem and if the problem comes from Symfony.
