### ISSUE TITLE
[Console] Private attributes and methods in ArgvInput class should be protected

### ISSUE THREAD

**Issue by Th3Mouk** [symfony/symfony#23851]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

## Source 
[ArgvInput Class](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Console/Input/ArgvInput.php)

[The Interface](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Console/Input/InputInterface.php)

## Problem

I have actually a php console file that implementing a custom kernel and fetching the --env option by ArgvInput declaration.
After this I have a custom Silly Application that automatically registers some commands but all without the --env option. Not necessary because it's the responsibility of the Kernel to determinate the environnement.
So this option must be ignored after the kernel instantiation in all commands.

The problem is, I need to implement my own ArgvInput class extending the previous one, to override parse method or parseLongOption method. Because actually each command throw `The "--env" option does not exist.`

Is it impossible because the class have some private attributes and methods, while the class is not final.

## Solution

Change the scope of all private methods and attributes to protected.

**Comment by stof** [comment]
you should add the `--env` option at the Application level, to make it an allowed option. This is how Symfony does it: https://github.com/symfony/symfony/blob/9295a4f1eba9ed9050c7aba634bf1b15ef649b65/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L49

Changing everything to protected is not a solution, as it means that everything becomes an extension point we have to maintain forever. This has a huge cost for us (inheritance-based extension points are the worst ones when it comes to writing a BC layer during a refactoring).

**Comment by Th3Mouk** [comment]
@stof thanks for the tip, it's very good solution 🍻
