### ISSUE TITLE
[WebProfilerBundle][RFC] TemplateManager requires implementing Twig 1.x compatibility interfaces

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony#23868]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

Additional context: https://github.com/Sylius/Sylius/issues/8392

In Sylius a PR of mine moved the app from using Twig 1.x to Twig 2.x, in that PR I removed all uses of deprecated/compatibility methods and interfaces from the [ThemeFilesystemLoader](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php) that they have.  Apparently doing so causes the undefined method error in the linked Sylius issue report.

Would it be possible (or practical) to make the TemplateManager be able to work without requiring the compatibility interfaces?

**Comment by javiereguiluz** [comment]
@mbabker I've looked into the TemplateManager code but I still don't understand the issue. We check for Twig 2.x getSourceContext() first and then Twig 1.x getSource(). Could you please tell me the exact lines of code that create issues for Sylius? Thanks!

**Comment by mbabker** [comment]
The exact order in the TemplateManager's `templateExists` is:

- If the loader implements `Twig\Loader\ExistsLoaderInterface`, then the `exists()` method is called
- If the loader implements `Twig\Loader\SourceContextLoaderInterface`, then the `getSourceContext()` method is called
- If neither condition above is met, the `getSource()` method is called; this is only present in Twig 1.x

It was in that last condition that the linked Sylius issue was filed from.

**Comment by mbabker** [comment]
Works for me, thanks!
