### ISSUE TITLE
Could not determine access type for property "price"

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#23871]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.306

http://www.magmadigital.co.uk/2014/symfony-association-names/

![image](https://user-images.githubusercontent.com/10435075/29238619-0aedc13a-7f6c-11e7-8251-2de602b82bc3.png)

![image](https://user-images.githubusercontent.com/10435075/29238625-17f32e92-7f6c-11e7-9058-97dfd19676fc.png)

**Comment by sstok** [comment]
Can you provide an exception stack trace (as text) and small example to reproduce this result. And please don't images for scripts or exceptions 👍

**Comment by xabbuh** [comment]
When you are using the `CollectionType` your mapped property should have a plularized name. So it should probably be `prices` and not `price`.

**Comment by Simperfit** [comment]
@xabbuh maybe we can close this?
@imsheng is this still an issue? it's quite old without any feedback. if it's the case feel free to re-open it.
