### ISSUE TITLE
Form component, get passed options

### ISSUE THREAD

**Issue by stoccc** [symfony/symfony#23883]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.8

It would be nice to have the chance to get passed options to a FormType, the same way they are displayed in the Profiler (section Form -> Passed options, in each field).

That would be useful when replacing a field inside a form event, so that could be created a replaced field with all (and just) the previously passed option with some edits, without the other "resolved options".

Now this informations, to what I know, are available only in the dev environment in the Profiler, and are collected in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php#L83

see this question on stackoverflow https://stackoverflow.com/questions/42900331/how-to-get-the-passed-options-to-a-symfony-form

**Comment by xabbuh** [comment]
This looks like an edge case to me. And since nobody else seems to have such an issue I am going to close here. Thank you for proposing this feature anyway.
