### ISSUE TITLE
Email not sent when using a Command and development bypass "delivery_addresses"

### ISSUE THREAD

**Issue by reypm** [symfony/symfony#23880]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

While trying to send and email from `dev` and using [delivery_addresses](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-addresses) with [Gmail transport](https://symfony.com/doc/current/email/gmail.html) I got no emails in my Gmail account:

- not in SPAM
- not in Inbox
- not in any other places, there is no rules on my account.

Basically this is how my configuration looks like:

```
# app/config/config.yml
swiftmailer:
    transport:      "%mailer_transport%"
    host:           "%mailer_host%"
    username:       "%mailer_user%"
    password:       "%mailer_password%"
    encryption:     "%mailer_encryption%"
    port:           "%mailer_port%"
    sender_address: "%mailer_sender_address%"
    spool:          { type: memory }
    logging:        '%kernel.debug%'

# app/config/config_dev.yml
swiftmailer:
    delivery_addresses: ['<email_adress>@gmail.com']
    transport: gmail
    username:  <email_adress>@gmail.com
    password:  *******************

# app/config/parameters.yml
parameters:
    mailer_transport: smtp
    mailer_port: 25
    mailer_host: email-smtp.us-west-2.amazonaws.com
    mailer_user: <mailer_user>
    mailer_password: *********************
    mailer_encryption: tls
    mailer_sender_address: no-reply@<domain>.com
    mailer_sender_name:     Some Sender Name
```

The code I am using for send the email is which is defined as a service and is being called from the command where I need to send the email:

```php
<?php

namespace QuoteBundle\Services;

use Doctrine\ORM\EntityManager;
use Psr\Log\LoggerInterface;

class SendNotification
{
    /** @var EntityManager */
    private $entityManager;

    /** @var \Swift_Mailer */
    private $swiftMailer;

    /** @var  LoggerInterface */
    private $logger;

    public function __construct(
        EntityManager $entityManager,
        \Swift_Mailer $swiftMailer,
        LoggerInterface $logger
    ) {
        $this->entityManager = $entityManager;
        $this->swiftMailer   = $swiftMailer;
        $this->logger        = $logger;
    }

    public function sendNotification(int $user_id, array $email_data): array
    {
        // ....
        $message = \Swift_Message::newInstance()
                                 ->setSubject($email_data['subject'])
                                 ->setFrom($email_data['from'])
                                 ->setTo($email_data['email'])
                                 ->setBody($email_data['body'], 'text/html');

        try {
            $this->swiftMailer->send($message);
            $this->logger->info(sprintf('The message was sent to: %s', $email_data['email']));
        } catch (\Exception $e) {
            $this->logger->info(sprintf('The message could not be sent to: %s', $email_data['email']));
            $this->logger->debug(sprintf('Error: %s', $e->getMessage()));
        }

        return ['success' => true];
    }
}
```

I have a channel for this email stuff and I can see the email is logged:

```
monolog:
    handlers:
        email:
            level: debug
            type: rotating_file
            path:  '%kernel.logs_dir%/email_%kernel.environment%.log'
            max_files: 10
            channels: [email]

----

[2017-08-13 13:31:16] email.INFO: The message was sent to: <email>@gmail.com [] []
[2017-08-13 14:49:07] email.INFO: The message was sent to: <email>@gmail.com [] []
[2017-08-13 14:49:59] email.INFO: The message was sent to: <email>@gmail.com [] []
[2017-08-13 14:52:54] email.INFO: The message was sent to: <email>@gmail.com [] []
...
```

Sadly I haven't a way to get more information because [logging](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#logging) only sent useful information to the profiler.

In addition: I am using Docker 17.07.0-ce-rc2-win22 (12979) (edge channel) (the image is [here](https://github.com/reypm/docker-lamp)) in Windows 10. 

Why the emails are not going out? I am missing something?

PS: if you need any other debug information I can provide it, just let me know

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by reypm** [comment]
@xabbuh this look like support to you?

**Comment by chalasr** [comment]
@reypm It does for me. The issue is very broad, probably coming from your environment. To confirm that this is indeed a bug, we would need a generic reproducer. If you can provide that, this should be opened on https://github.com/symfony/swiftmailer-bundle, but better try our support platforms first.
