### ISSUE TITLE
Use dump() without die; - hidding debug panel.

### ISSUE THREAD

**Issue by nickicool** [symfony/symfony#23891]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Very simple bug for checking. If use `dump()` function in any controller without `die;` - Debug tool bar is hide. All work, but debug panel hide with add class `.sf-display-none`. If this class remove using Firebug - all works.
Link for example - default Symfony demo app.

**Comment by xabbuh** [comment]
Can you please provide a [small example project](http://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs) that allows to reproduce your issue?

**Comment by nickicool** [comment]
I found what the problem is - Adguard did something that was added or removed the class sf-display-none. Now all is well. I apologize for your time and thank you very much for your work.
