### ISSUE TITLE
[Token Storage] Calling setToken() with `null` throws an AuthenticationException

### ISSUE THREAD

**Issue by AdamReece-WebBox** [symfony/symfony#23908]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | ?
| Symfony version  | 2.8.21

I noticed an issue with the `setToken()` function in `\Symfony\Component\Security\Core\Authentication\Token\Storage`. As described in the [API](http://api.symfony.com/2.8/Symfony/Component/Security/Core/Authentication/Token/Storage/TokenStorage.html) the `$token` parameter of this function is allowed to be null, however when passing `null` to it I get the following exception:

```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Argument 1 passed to Symfony\Component\Security\Core\Exception\AuthenticationException::setToken() must implement interface Symfony\Component\Security\Core\Authentication\Token\TokenInterface, null given, called in ~/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php
on line 129" at ~/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php line 41
{"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException::setToken() must implement interface Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface, null given, called in ~/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php on line 129 at ~/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php:41)"} []
```

What I am attempting to pass `null` to this to force a sign out if a user doesn't have access to administrate a particular site in a multi-site environment with the following snippet.

* `User` is our own entity class implementing the advanced user interface.
* `redirectWithMessage()` is just a wrapper for `redirectToRoute()` and adding a flash message in 1 call.

```
public function setContainer(ContainerInterface $container = null)
{
    parent::setContainer($container);

    $user = $this->getUser();
    if (!($user instanceof User) || !$this->isUserAdminOfSite($user, $this->getSiteId())) {
        $this->get("security.token_storage")->setToken(null); // Exception thrown here
        $this->get("request")->getSession()->invalidate();
        $this->redirectWithMessage("user_admin_logout", [], "You are not permitted to administrate this site.", "danger");
    }
}
```

I've checked the source through my vendor folder, and the parameter is definitely defined as `TokenInterface $token = null`, so it's not this.

What seems to be happening is that `\Symfony\Component\Security\Http\Firewall\ExceptionListener::handleAccessDeniedException()` is reading the token and checking if it's "full fledged". If not a `\Symfony\Component\Security\Core\Exception\AuthenticationException` is thrown, however `setToken()` in this exception class does not allow `null` to be passed in.

I think that either the token should allowed to be `null` in `\Symfony\Component\Security\Core\Exception\AuthenticationException`, or `\Symfony\Component\Security\Http\Firewall\ExceptionListener::handleAccessDeniedException()` should not attempt to set a null token in the `AuthenticationException`. _I'm not sure what implications a `null` token would have in the exception elsewhere._

If however you don't think that I should be forcing a sign out in this way let me know. 👍

**Comment by iltar** [comment]
If you want to de-authenticate the user, either try setting it to an anonymous token, or do it via a voter by denying access until proper authentication is done. The other option would be to do it via a user-checker and the refresh user method. 

The current solutions seems really ugly and bad for multiple reasons and it doesn't surprise me it fails.

**Comment by AdamReece-WebBox** [comment]
Passing an anonymous token might be suitable, we'll try that.

The reason this is being done at this level is because users can be assigned administrative status for none/many sites using a many to many relationship, and this relationship needs to be manageable by a "top administrator" in the web interface.
(The main distinction between different sites is the HTTP host name)

Because of this we can't feasibly use the firewall rules to throw this access exception without re-writing the firewall YML any time a site is added/removed or user-admin relationship is added/removed. It needs to be done at controller level, and the `setContainer()` seemed like the best global place to do it.

**Comment by iltar** [comment]
This still sounds like something you can do either as voter or during the refresh user though, it saves you a lot of trouble by hooking in either one of the 2 security extension points
