### ISSUE TITLE
[Console] Automatic creation of \DateTime objects from arguments

### ISSUE THREAD

**Issue by tdashton** [symfony/symfony#23902]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x

_*Note*: this is a general question whether y'all would accept a merge request with the following logic added to the `\Symfony\Component\Console\Input\InputOption` and `\Symfony\Component\Console\Input\InputInterface` class._

Basically I want to know if it is worth my time to open a pull request :)

*Motivation*: Frequent use of date time strings in commands.

*Feature Request*: Add logic to the `/Symfony/Component/Console/Input/InputOption` for `const VALUE_IS_DATETIME = 16;`

This would simplify passing and getting `\DateTime` within the context of a command:

Usage:
`console/app command --zee-date-time "12 months ago"`

```php
new InputOption('zee-date-time', null, InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_DATETIME, '... (in a format recognized by \DateTime).', '23 days ago'),
```

and then 

```php
/** @var \DateTime  $dateTimeObject */
// date time or InvalidArgumentException if the string cannot be parsed into a DateTime
$dateTimeObject = $input->getOption('zee-date-time');
```

**Comment by iltar** [comment]
This sounds like something that could use a similar system to argument value resolvers

**Comment by chalasr** [comment]
Indeed

**Comment by kiler129** [comment]
Maybe we can go even further and instead of adding constant we can give an option to specify a factory/transformer in `InputOption`?

**Comment by chalasr** [comment]
Resolving command options/arguments as `\DateTime` through the proposed flag is not flexible enough I think, this could apply to any type like doctrine entities.

Wiring some method arguments through value resolvers as suggested by @iltar would be great, but I fail to see how it could be implemented given how commands are designed (thinking to `execute()` which is inherited and thus has locked signature).

I did propose something similar to what @kiler129 suggests but aborted for some reasons: https://github.com/symfony/symfony/pull/21041. 
Would that be a solution? Note that I would change naming from `validator` to `resolver`, and we could provide some built-in resolvers like the `\DateTime` one.

Related issue: https://github.com/symfony/symfony/issues/20899

**Comment by iltar** [comment]
There's no reason to not treat commands as (cli) controllers, imo. Can easily decouple a command from its base class and wire input/output arguments via a resolver. Downside, the AVR is tightly coupled to the Request as back then, it wasn't a requirement to make it generic (I did propose this).

**Comment by fabpot** [comment]
I'm :-1: for such an addition which seems very specific to me. For the record, I'm also :-1: for "converting" commands to controllers.

**Comment by tdashton** [comment]
Cool, thanks for your feedback @chalasr @kiler129, I appreciate !! I shall look into it.
