### ISSUE TITLE
[Debug] SecurityBundle tries to load classes from Templating

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#23913]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I do not have symfony/templating installed. 

<img width="767" alt="screen shot 2017-08-17 at 11 35 58" src="https://user-images.githubusercontent.com/1275206/29406077-424c3d96-8340-11e7-976c-565a946d3524.png">

The first request is fine, but the second request causes an issue: 

<img width="1103" alt="screen shot 2017-08-17 at 11 37 13" src="https://user-images.githubusercontent.com/1275206/29406144-79a25c94-8340-11e7-9202-75558a8b21b0.png">

Possible solution: Make sure the

**Comment by chalasr** [comment]
This is a bug in Config which has been fixed and will be part of 3.3.7. 
Could you check 3.3-dev out and confirm that the problem doesn't occur?

**Comment by Nyholm** [comment]
Sorry for not searching enough. I will check

**Comment by Nyholm** [comment]
Thank you. `"symfony/config": "3.3.x-dev"` works

**Comment by Koc** [comment]
Ref #23818 #23753
