### ISSUE TITLE
Provide blog URL in deprecation messages

### ISSUE THREAD

**Issue by aalwash** [symfony/symfony#23919]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | maybe?
| Symfony version  | 3.3.6

Today I upgraded from Symfony 3.2.6 to 3.3.6 and started fixing some deprecations, to make our code Symfony 4 ready (or in some cases even 3.1+)

Most of the time the warnings are clear, like:

> Not quoting the scalar "%fos_user.registration.confirmation.template%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0.

So I started Googling and landed on http://symfony.com/blog/new-in-symfony-3-1-yaml-deprecations

Wouldn't it be awesome to maybe add a 'How to fix' link next to 'Show context' and 'Show trace' to the blog?
Of course, some of these blog pages are added way later after the code has been pushed. So yes, whenever a blog is written about a deprecation, change the deprecation message and add a link to the blog.

I think it's rather easy to build something like that and could save a lot of time when you try to fix a deprecation.

PS.: Sorry, this is my first feature request in the Symfony project, if more information is required, please let me know!
Maybe I can try to make a patch with a code change proposal.

**Comment by kiler129** [comment]
I will go a step further and add links to all old messages. The question is whatever we consider changing an exception message a BC break?

**Comment by aalwash** [comment]
@kiler129 that was exactly my point, all deprecations should get a link, IF there is a blog about how to fix them.

I just had time to dig into the code and noticed that the messages are trigger_errors, with E_USER_DEPRECATED.
A "dirty fix" would be, mentioning the blog URL in the message itself and parse it through the frontend and make it a link.

Other then that, I don't have an idea how to fix this differently without changing too much code.

**Comment by ro0NL** [comment]
That requires to know the link before pushing right :S How would this work? For every blog post an additional PR to update the deprecation? 

Perhaps a google link with the normalized deprecation message will do; and then whenever the blog post is written include that somehow. Yet we only save a copy/paste/google then.

**Comment by aalwash** [comment]
> Of course, some of these blog pages are added way later after the code has been pushed. So yes, whenever a blog is written about a deprecation, change the deprecation message and add a link to the blog.

I don't think the original PR should be hold until the blog is written, that will cause unnecessary delay.
So yes, additional PR to update the deprecation message whenever the blog post is live.

> Perhaps a google link with the normalised deprecation message will do; and then whenever the blog post is written include that somehow. Yet we only save a copy/paste/google (or select/drag) then.

That's possible, but like you mentioned, you will only save a copy/paste and some extra clicks.
And, there is a chance you're not going to end up on the blog link, because Google didn't index it yet, or Google thinks the blog is less important for your search.


I prefer a clear link to the blog, even if it's added later on in a different PR (or any other solution someone can come up with).
It's clear, with just one click you be redirected to the blog explaining the reason of deprecation and how to fix it.

**Comment by ro0NL** [comment]
@aalwash sorry missed that sentence. Addiotional PR is probably the best approach yes; and can be done by anyone.

**Comment by nicolas-grekas** [comment]
:-1:
We always avoid adding links in the source, that'd be a nightmare to maintain.

**Comment by nicolas-grekas** [comment]
Note if one wants to maintain such a list, this can be done in a bundle. But that should not be in core to me.

**Comment by aalwash** [comment]
I agree, links in the core code is a nightmare and should be avoided if possible.

What if the deprecation message contain an unique error number/hash?
So the WebProfiler (separate bundle) will maintain the list of the error numbers/hashes + blog URL's

Does that sound like a interesting idea?

**Comment by kiler129** [comment]
After thinking about this more @nicolas-grekas is right... codes are neat idea, but we'll end up with 0xAF87373AFF, this will also be bad. Maybe instead of hashes or numbers we can use something like `Scalar keys are deprecated ...... See reference "deprecation.scalars"`.

**Comment by chalasr** [comment]
Googling `symfony upgrade` gives the following link as first result http://symfony.com/doc/current/setup/upgrade_major.html#update-your-code-to-work-with-the-new-version. Reading `UPGRADE-[relevant version]` file is the right way for getting hints about upgrading. Some blog posts may be better (more code examples) but these are "news", we don't write a blog post for every single deprecation so we can't build on that. As said, even if we were, doing this would be a nightmare regarding maintenance, whatever links or unique numbers are used to identify a deprecation.

**Comment by aalwash** [comment]
I closed the RFC since the majority is against it. 
For now, I think we will keep it on Googling the errors ;)
