### ISSUE TITLE
[Symfony 2.7+][Form] Issue with Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer::reverseTransform

### ISSUE THREAD

**Issue by vulkodava** [symfony/symfony#23918]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7+

Kind of related to "[Form] Empty data fails on OneToOne / OneToMany by converting null to empty string #21890"

Hi, quick question. I think in Symfony 2.7 Upgrade Symfony has removed a piece of code from the `Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer::reverseTransform` method. The piece code in question is listed bellow. But I was wondering why, what's the reasoning behind that, because now forms treat empty value of a drop-down as empty string, rather than `null`. I guess it is so you can actually sand an empty string as a real value. but I was wondering if this is the reason and if this would stay like that, because lots of the code I work with revolves around the `null` value and now when I upgrade I will have to do a lot of changes, and if they change it back I will have to do all those changes again, so is it a desired behavior?

        ***
        // These are now valid ChoiceList values, so we can return null
        // right away
        if ('' === $value || null === $value) {
            return;
        }
        ***

**Comment by xabbuh** [comment]
I am closing here. The case you mention should be handled below: https://github.com/symfony/symfony/blob/8ab7077225eadee444ba76c83c667688763c56fb/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php#L43-L49

If you still experience any issues, please comment with some steps on how to reproduce it.

**Comment by vulkodava** [comment]
Thank you you :)
