### ISSUE TITLE
ProxyManager\Proxy\VirtualProxyInterface not found

### ISSUE THREAD

**Issue by DevMayo** [symfony/symfony#23911]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Hello,

My Symfony project is working fine in dev env, but in prod env i get this message :

> Fatal error: Interface 'ProxyManager\Proxy\VirtualProxyInterface' not found in C:\xampp\htdocs\test_site\var\cache\prod\appProdProjectContainer.php on line 4747

The faulty line in the appProdProjectContainer.php is : 

`class DoctrineORMEntityManager_000000003ac18a72000000007b10f3563023a147a8b7be3a85e9cd63cfe8e6bf extends \Doctrine\ORM\EntityManager implements \ProxyManager\Proxy\VirtualProxyInterface`

I get the same message when i try to clear the prod cache. I don't understand why the VirtualProxyInterface is missing. How can i get it back ? 

This issue is for both 3.3.6 and 3.2.13 Symfony versions of my project, it was previously working on 2.8

**Comment by NicoHaase** [comment]
This class is coming from the proxy manager. Have you used it recently, or probably deleted that package? Try to run composer update to see whether the cache of your autoloader is okay

**Comment by sstok** [comment]
Like @NicoHaase says "Have you used it recently, or probably deleted that package?". when you have an old cache that was generated with this package still present the old Container is has become stale cannot be used for booting the cache:clear process.

Delete the var/cache/prod manually and see it that solves it.

_This is a known problem and is finally solved in the upcoming Symfony 3.4 release!_

**Comment by DevMayo** [comment]
I didn't delete the proxy manager package. Following your advices i performed composer update and delete the var/cache/prod directory manualy.

It solved the problem. Many thanks !

**Comment by chalasr** [comment]
Closing as solved.
