### ISSUE TITLE
[Workflow] Introduce a Workflow interface, type-hint against it in Registry

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#23910]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | latest

`Workflow\Registry` accepts only instances of `Worflow\Workflow` which makes decorating workflows awkward. It would allow for more flexibility if an interface was introduced here.

**Comment by lyrixx** [comment]
The decoration argument make sens ; I'm :+1: 

Do you want to create the PR?

**Comment by dkarlovi** [comment]
> Do you want to create the PR?

Sure, not a problem. Would this count as a BC?

**Comment by lyrixx** [comment]
Sorry, I forgot this was a PR. And not it's not a BC break.

**Comment by xabbuh** [comment]
In fact, changing some of the type hints to accept `WorkflowInterface` instance instead of `Workflow` would be a BC break for child classes.

**Comment by chalasr** [comment]
We would have to first deprecate passing a Workflow that doesn't implement WorkflowInterface everywhere the typehint should change.

**Comment by dkarlovi** [comment]
OK, what's the proper action here? I'll create the PR.

**Comment by chalasr** [comment]
Ah... nevermind, we are talking about a method, I thought a constructor. Then a possible path would be to deprecate the whole `add()` method in favor of a constructor. Question is: is `add()` useful?

**Comment by Simperfit** [comment]
@chalasr, can't we accept both in the add method and add a deprecation when we pass a Workflow that does not implement the interface ?

**Comment by chalasr** [comment]
@Simperfit nope, because removing the current typehint to allow both would break any subclass of Registry (fatal)

**Comment by dkarlovi** [comment]
So, how do we tackle this?

**Comment by chalasr** [comment]
@dkarlovi We can't remove/change the `Workflow` typehint in public/protected methods, that would break existing implementations and subclasses. 
The only possible path is to let the method unchanged and deprecate it for removing it in 4.0, but actually there are 2 such methods: `SupportsStrategyInterface::supports()` and `Registry::add()`. I think `add()` could be deprecated, but `supports()` cannot since it is part of an interface and is useful.
About your use case, the decorating Workflow could extend `Workflow` and override its methods. An interface would give more flexibility, but that's not worth breaking BC.

**Comment by chalasr** [comment]
Unless we want to break BC for this, I think we can close.

**Comment by Simperfit** [comment]
IMO it could be worth the little BC.

**Comment by dkarlovi** [comment]
Agree with @Simperfit, otherwise you're locked-in to current state "forever" without a clear way forward in the future, and we're talking about only two usage occurrences here AFAIK. If decided to do it in the future, it'll only be as complex or more so, not less.

**Comment by lyrixx** [comment]
Another approach is to rename the method. What do you think ?

**Comment by chalasr** [comment]
@lyrixx 👍  The most annoying is `SupportsStrategyInterface` though, as we would need to deprecate it entirely (renamed) for changing the typehint in `supports()`. 
Imho it's worth changing doing it for both `Registry` and `SupportsStrategyInterface`, doing that in 3.4 would be best.

**Comment by lyrixx** [comment]
Wahoo, that so much work :/ 
Do someone want to do it ?

**Comment by dkarlovi** [comment]
I can do it, what's the scope exactly?

**Comment by chalasr** [comment]
- Deprecate `Registry::add(Workflow $workflow)`
- Add `Registry::addWorkflow(WorklowInterface $workflow)` (or so)
- Duplicate `Registry::add()` tests and use `Registry::addWorkflow()` into
- Mark `Registry::add()` tests as legacy, asserting the deprecation
- Deprecate `SupportsStrategyInterface`
- Add a replacement interface, changing `supports(Workflow $workflow)` to `supports(WorkflowInterface $workflow)`
- Duplicate tests relying on this interface to have new ones using the new interface
- Mark the tests relying on this interface as legacy
- Document the changes in Workflow/CHANGELOG and UPGRADE files

I think it's too late for 3.4. If I'm right, PR should be submitted against master.

**Comment by dkarlovi** [comment]
Thanks for the list @chalasr, I'll start on it this week.
