### ISSUE TITLE
[Silex/WebProfiler] Unknown argument "max_depth" for function "profiler_dump(value)".

### ISSUE THREAD

**Issue by quazardous** [symfony/symfony#23922]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.6

symfony/web-profiler-bundle 3.3.6
symfony/security 3.3.6
Silex 2

the web profiler crash with

```
 (1/1) Twig_Error_Syntax
Unknown argument "max_depth" for function "profiler_dump(value)".
```

seams `symfony/web-profiler-bundle/Twig/WebProfilerExtension.php` has a deprecated (?) function.

```php
// line 31
    public function getFunctions()
    {
        return array(
            new \Twig_SimpleFunction('profiler_dump', array($this, 'dumpValue')),
        );
    }

    public function dumpValue($value) // <-- just adding a parameter $maxDepth here fix the crash (but does nothing of course)
    {
        if (null === $this->valueExporter) {
            $this->valueExporter = new ValueExporter();
        }

        return $this->valueExporter->exportValue($value);
    }
```

I'm duplicating this issue https://github.com/silexphp/Silex-WebProfiler/issues/124

**Comment by ogizanagi** [comment]
Are you sure this is the `symfony/web-profiler-bundle` 3.3.6 version which is installed?
In your excerpt, the code is different than the actual one in 3.3.6:

https://github.com/symfony/symfony/blob/6f80cbd2dd89c5308b14e03d806356fac72c263e/src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php#L70-L80

I'd say you rather have the 3.1 version installed:

https://github.com/symfony/symfony/blob/96e7dede3ddc9e3b3392f5cc93e26eca77545a89/src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php#L31-L36

**Comment by stof** [comment]
Please give the stack trace of the exception you are getting too, to see where it happens

**Comment by bckr75** [comment]
In `composer.json` replace `"silex/web-profiler": "2.0"` with `"silex/web-profiler": "^2.0"`, then run `composer update`, it should help.
As @ogizanagi said:  
> I'd say you rather have the 3.1 version installed

Yes, you have 3.0.9 installed.

**Comment by xabbuh** [comment]
closing here as this doesn't seem to be an issue in Symfony
