### ISSUE TITLE
Form with an EntityType field with multiple=true giving back array and ArrayCollection

### ISSUE THREAD

**Issue by stoccc** [symfony/symfony#23927]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.22

I have a strange behaviour with a form (mapped to an `array`, not to a Entity) containing a field of type `EntityType` with `multiple=true`.

If I set that field with initial data an empty `array`, e.g. `array()`, after successful submit when I call `$form->getData()` I get an `ArrayCollection` for that field.

Instead, if I set that field with initial data a non empty `array`, after a successful submit when I call `$form->getData()` I get a simple `array` for that field.

Shouldn't I obtain always the same type?

**Comment by iltar** [comment]
I don't understand it completely, but it seems like you're using an EntityType while you should be using a collection type of sorts?

**Comment by yceruto** [comment]
AFAIK the expected default data for `EntityType` with `multiple = true` should be an `ArrayCollection`. 

Even though, an `array` is allowed, it shouldn't be recommended, because the core `MergeCollectionListener` doesn't care about the data type of the normalized data:

https://github.com/symfony/symfony/blob/1732cc8489d592f0f54c0383ae9fb3457e616b12/src/Symfony/Component/Form/Extension/Core/EventListener/MergeCollectionListener.php#L61-L62

Hence `$event->getForm()->getNormData()` and `$event->getData()` won't have the same data type and `ArrayCollection` is lose if non "empty" data is provided by default.

**Comment by yceruto** [comment]
However, I think passing an `array` should work too and the expected data type results should be coherent with the default data.

This is where that is not true:

https://github.com/symfony/symfony/blob/1732cc8489d592f0f54c0383ae9fb3457e616b12/src/Symfony/Component/Form/Extension/Core/EventListener/MergeCollectionListener.php#L83-L87

Status: Comfirmed

**Comment by yceruto** [comment]
The solution to be consistent with default data type provider:
https://github.com/symfony/symfony/blob/1732cc8489d592f0f54c0383ae9fb3457e616b12/src/Symfony/Component/Form/Extension/Core/EventListener/MergeCollectionListener.php#L83
```diff
- if (!$dataToMergeInto) {
+ if (null === $dataToMergeInto) {
```
and the resulting data type should be consistent:
 * If an `array` is given => an `array` is retrieved. 
 * If an `ArrayCollection` is given => an `ArrayCollection` is retrieved. 

@stoccc could you try it?

**Comment by stoccc** [comment]
@yceruto OK, it works. If I give an `array`, I always get an `array`; if I give an `ArrayCollection`, I always get an `ArrayCollection`

**Comment by yceruto** [comment]
@stoccc If you prefer, you can provide the fix and update your PR, or let me know to submit a new one :)

**Comment by stoccc** [comment]
@yceruto ok, I committed your changes #

**Comment by stoccc** [comment]
@yceruto I created new PR #23980 against 2.7. It seems that in php 5.3 tests pass, while in php 7 and 7.1 they don't pass. I can't figure out why. In my installation with 2.8 on php 7.0.10 I don't have problems. :(

**Comment by pejaycz** [comment]
I have same problem with Symfony 3.3.6 (PHP 5.6)
