### ISSUE TITLE
[Security] LogicException: %scheb_two_factor.security_voter.class% should implement the VoterInterface interface when used as voter

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#23924]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.x-dev (8c4a1e75bee9e8110937fb6ec1ccf94aa1556a52)

Error:

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\LogicException: %scheb_two_factor.security_voter.class% should implement the Symfony\Component\Security\Core\Authorization\Voter\VoterInterface interface when used as voter. in vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php:54
```

This service is defined in https://github.com/scheb/two-factor-bundle/blob/master/Resources/config/security.xml#L52. Looks like class is not resolved in https://github.com/symfony/security-bundle/blob/master/DependencyInjection/Compiler/AddSecurityVotersPass.php#L45.
It returns parameter instead.
Error is going away when I hardcode FQCN instead of `%scheb_two_factor.security_voter.class%` parameter.

I've read https://github.com/symfony/symfony/blob/master/UPGRADE-3.4.md#securitybundle and this class does implement `VoterInterface`, the problem lies in fact that `AddSecurityVotersPass` is operating with `"%scheb_two_factor.security_voter.class%"` string instead with FQCN.

/cc @nicolas-grekas

**Comment by xabbuh** [comment]
Thanks for reporting, but I close here as a duplicate of #23733.
