### ISSUE TITLE
Add a way to set constraint in ContraintValidatorTestCase

### ISSUE THREAD

**Issue by toommz** [symfony/symfony#23939]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

To set the constraint on a validator unit test, we need to almost entirely rewrite the setUp() method, while it will only be a little method away to permit more configurability, as in :

```php
// In ConstraintValidatorTestCase

protected function setUp()
{
    // […]
    $this->contraint = $this->createConstraint();
    // […]
}

protected function createConstraint()
{
    return new NotNull();
}

// In my own validator test case, overriding the added method

protected function createConstraint()
{
    return new MyBeautifulConstraint();
}
```

Maybe, as I'm new to Symfony, I totally missed the point of the abstract class or something else ?!

**Comment by dmaicher** [comment]
Did you check how the abstract class is used by other test cases?

For example: https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/Validator/Tests/Constraints/IsTrueValidatorTest.php

**Comment by toommz** [comment]
Yes, and this is actually the way I do constraint tests when using assertNoViolation().

I don't know why but this is now working after retrying it. My apologies. I close the issue.
