### ISSUE TITLE
CacheDataCollector and CacheCollectorPass not compatible with TraceableCache

### ISSUE THREAD

**Issue by hcomnetworkers** [symfony/symfony#23937]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes, PSR-16
| Symfony version  | >=3.3

[CacheDataCollector](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/DataCollector/CacheDataCollector.php) and respective [CacheCollectorPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CacheCollectorPass.php) do not work with the [TraceableCache](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Simple/TraceableCache.php).

Both TraceableCache and [TraceableAdapter](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/TraceableAdapter.php) should implement a common interface for the getCalls-method and the events TraceableCacheEvent and TraceableAdapterEvent could be the same class and put in a new file.

**Comment by nicolas-grekas** [comment]
ping @Nyholm if you want to look at it

**Comment by Nyholm** [comment]
Sure, I will have a look tonight or over the weekend

**Comment by Simperfit** [comment]
@Nyholm do you have some time to take this, or do you want me to do it ?

**Comment by Nyholm** [comment]
Oh, as you can see. I've totally forgotten about this. Please Hamza, feel free to have a look.

**Comment by jeroennoten** [comment]
@nicolas-grekas is this issue still relevant? It seems that the class TraceableCache was deprecated in Symfony 4.3:

```
The "TraceableCache" class is deprecated since Symfony 4.3, use "TraceableAdapter" and type-hint for "CacheInterface" instead.
```

And in the 5.x branch, the TraceableCache class is gone.

**Comment by nicolas-grekas** [comment]
Correct, thanks, let's close. If someone has the issue on 4.4 and wants to fix it, PR welcome.
