### ISSUE TITLE
[Serializer][RFC] Add normalizer property options

### ISSUE THREAD

**Issue by akeeman** [symfony/symfony#23932]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | eventually
| RFC?             | yes
| Symfony version  | 3.4 (keeping bc) / 4.0

Hi, I was experimenting with the serializer component as I maybe want to use api-platform.com. I missed a feature where I can mark an integer field as [hashid](http://hashids.org/). So I modified the serializer component. Before putting in the effort to write a pr, I first want to check if you guys are in for such an addition.

It boils down to the following. I added another annotation, `Options`, that holds an arbitrary value. In my case
```php
/**
 * @var int
 * @Options({"hashids"=true})
 */
$myprop;
```

Then this is added to the property metadata, just like `@Groups` and `@MaxDepth`. Then it will be added as argument to a bunch of normalizer and denormalizer methods, analogous to the `$context` parameter. Also a few modifications are made to allow scalars to pass through (de)normalizers whenever they have options. This way, the (de)normalizer can decide if it wants to (de)normalize this value, like it already does, like so

```php
public function supportsNormalization($data, $format = null, array $context = [], array $options = [])
{
    return isset($options['hashids']) && true === $options['hashids'];
}
```

So given this, the ability is added to let a (de)normalizer modify any attribute if it's flagged with some data.

Is it worth it to create a PR, or don't you guys like the idea?

**Comment by ogizanagi** [comment]
Instead of a new `$options` argument (which is not really easy to introduce regarding BC), why not introducing a new `@Context` annotation allowing to configure the context per field? This would allow to configure the format to use per field for the `\DateTimeNormalizer` for instance (or any similar normalizer exposing relevant options).

> Also a few modifications are made to allow scalars to pass through (de)normalizers whenever they have options.

Not sure we should do that. Why not using a virtual property (i.e a method) for your specific need? (Or using a DTO to serialize instead of directly mapping your entities, but that might not be the best solution for you using `api-platform`).

**Comment by akeeman** [comment]
@ogizanagi Thanks for your reply. Below I'm sharing my thoughts and give some answers.

> Instead of a new `$options` argument (which is not really easy to introduce regarding BC), why not introducing a new `@Context` annotation allowing to configure the context per field?

I tried that at first, but then chose to go with the `@Options`. There were two main reasons. One being that these `options` represent some options that configure only the attribute (internal object configuration), while the `$context` provides data on the broader scope and configure many attributes (external context configuration). The second was that I found it harder to implement, as the context propagates to nested objects, while the options are explicitly applicable to the attribute only. So my thought was that it would be better to keep them separate. Please let me know if you (still) think it should be part of the context.

> [...] (which is not really easy to introduce regarding BC) [...]

I saw the way it was done with `$context` and was thinking to take a similar approach. It's not the most beautiful one, but it works great.

> This would allow to configure the format to use per field for the `\DateTimeNormalizer` for instance (or any similar normalizer exposing relevant options).

Given that options are passed to all normalizers (I suggest it's not only passed to the "supports(De)Normlization" but to the (de)normalization method itself too, it can indeed be used  to configure the dateTime format too, on a individual attribute basis.

> > Also a few modifications are made to allow scalars to pass through (de)normalizers whenever they have options.
>
> Not sure we should do that.

Not sure too, but I don't know a better way and it is required if I want to reach my goal. Maybe this helps to get a better view. The first piece of code is [copied from here](https://github.com/symfony/symfony/blob/v3.3.6/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L263-L272). This decides wheter a normalizer should be called in the denormalization process. The second snippet is an altered version that also throws in scalars whenever it has `$options`.

Original
```php
            if (Type::BUILTIN_TYPE_OBJECT === $builtinType) {
                if (!$this->serializer instanceof DenormalizerInterface) {
                    throw new LogicException(sprintf('Cannot denormalize attribute "%s" for class "%s" because injected serializer is not a denormalizer', $attribute, $class));
                }
                $childContext = $this->createChildContext($context, $attribute);
                if ($this->serializer->supportsDenormalization($data, $class, $format, $childContext)) {
                    return $this->serializer->denormalize($data, $class, $format, $childContext);
                }
            }
```

Adapted
```php
/*modified*/if (Type::BUILTIN_TYPE_OBJECT === $builtinType || !empty($options)) {
/*added*/       $type = Type::BUILTIN_TYPE_OBJECT === $builtinType ? $class : $builtinType;
                if (!$this->serializer instanceof DenormalizerInterface) {
/*modified*/        throw new LogicException(sprintf('Cannot denormalize attribute "%s" for type "%s" because injected serializer is not a denormalizer', $attribute, $type));
                }
                $childContext = $this->createChildContext($context, $attribute);
/*modified*/    if ($this->serializer->supportsDenormalization($data, $type, $format, $childContext, $options)) {
/*modified*/        return $this->serializer->denormalize($data, $type, $format, $childContext, $options);
                }
            }
```

> Why not using a virtual property (i.e a method) for your specific need? (Or using a DTO to serialize instead of directly mapping your entities, but that might not be the best solution for you using `api-platform`).

This would require me to set services that would provide the converted value (in my case to create the hashid from an integer) on an entity. I don't think that's good practice. Also, as it's about the id, I should do that on every entity I expose through the api. And indeed, a DTO doesn't work well with `api-platform`.

**Comment by akeeman** [comment]
@ogizanagi So what do you think? Is it worth it to create a PR, or don't you guys like the idea?
