### ISSUE TITLE
Forms Collection

### ISSUE THREAD

**Issue by lecneri** [symfony/symfony#23931]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi all,

I've an entity Measurement with following data
Client - Entity 
Date   - date (duh:P)
Value  - float

I'm trying to create a form to insert a client's measurement in a month
So I've create one form to inform the client/month to be inserted
Now I trying (in vain) to create another form with Measurement collection as root element and I'm really having a hard time to figure this out.

As pointed in docs (http://symfony.com/doc/current/form/form_collections.html) they used a root entity to hold the collection (task has collection of tags) but in my case I don't have the root entity I have the collection as root. What's the best way to do this?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
