### ISSUE TITLE
[Form] DateIntervalType does not respect ISO 8601

### ISSUE THREAD

**Issue by havvg** [symfony/symfony#23948]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.1

The `Symfony\Component\Form\Extension\Core\Type\DateIntervalType` does not recognise short versions of valid ISO 8601 interval representations such as `P6M` when using `single_text` `widget`.

Currently the `with_*` options such as `with_years` are named confusingly. They actually mean "mandatory element including designator" within the provided (string) data. Imho, those options should only alter the form view rendering & respective transformation, not how the input is validated.

**Comment by xabbuh** [comment]
This does not seem to be an issue anymore. With a form type like this:

```php
$builder
    ->add('duration', DateIntervalType::class, [
    'widget' => 'single_text',
    'with_days' => false,
    'with_years' => false,
    'mapped' => false,
])
```

Submitting the string `P6M` reveals the expected `DateInterval` object. Thus, I am closing here.
