### ISSUE TITLE
Using Workflow & FrameworkBundle leads to error when triggering by type autowiring

### ISSUE THREAD

**Issue by RobertMe** [symfony/symfony#23946]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I'm using some standalone parts of Symfony without using the full symfony/symfony dependency. This currently means that I'm using the FrameworkBundle and Workflow component. But this leads to some "complicated" problem where compiling the container works fine, but when checking if the container is still fresh it leads to an error, being:
> Uncaught exception 'ReflectionException' with message 'Class Symfony\Component\Security\Core\Authorization\ExpressionLanguage not found' in /var/www/symfony-error/vendor/symfony/workflow/EventListener/ExpressionLanguage.php on line 22

After a lot of debugging I found out there are two (possible) issues which lead to this problem.

The first issue is the fact that the class is added as `ClassExistsResource` due to the now deprecated _by type auto wiring_. This due to `AutoWirePass::populateAvailableType` calling `$this->container->getReflectionClass` which will add this class as resource, because it didn't exist (or in this case couldn't be loaded). But IMHO it is strange to add such class as resource because of the auto wiring. As it means that classes which aren't used in the compiled container (which is the case for this `ExpressionLanguage` class, the service for it doesn't exist as it is unused) are still checked when checking if the container is still "fresh". While it is completely unsure whether such service would actually suffice to be used as auto wire argument (which even most likely is the case in all of these scenarios, that such missing class can't suffice as argument of a completely different service). And I think this also means that _all_ services which are defined will be checked whether the container is still fresh, so either as `ClassExistenceResource`, or as `ReflectionClassResource`, even when they aren't available in the compiled container. Which will thus lead to a performance impact in those cases where every call checks if the container is still fresh (so at least dev environment).

The second issue is in `ClassExistenceResource`, where `throwOnRequiredClass` seems to fail. For the `$i = 1 + array_search($autoloadFrame, $trace, true);` line the `array_search` is false in my case (on PHP 5.6), so `$i` will become `1` which in my case means that the actual `spl_autoload_call` is tested. Furthermore if the check did work, it would end up testing on the `include` call from Composer which would still mean that it would throw in this case.

To demonstrate the issue I've created a test project: https://github.com/RobertMe/symfony-error The first time the page will load fine (and display "loaded"), but when refreshing the page it gives a fatal error due to aboves exception. As can be observed the `ExpressionLanguage` class isn't present as service in the dumped container, but it is present in the compiled containers meta file, as `ClassExistenceResource`.  When changing the configuration of the `Foo` service by disabling auto wiring, or creating a new Bar service (matching the type of the argument), it does work. This because in that case the by type auto wiring isn't triggered, and thus the `ExpressionLanguage` class isn't monitored for existence.

**Comment by chalasr** [comment]
Hey, thanks for the report and the deep analyse. I think this has been fixed already, could you retry on `3.3.8` (released yesterday)? Please tell us if the issue still happens or just close if it's ok. Thanks.

**Comment by RobertMe** [comment]
The error is indeed fixed in `3.3.8` _but_ the first point is still valid.

When _by type auto wiring_ is triggered (because it can't autowire an argument based on the new service id = classname logic) every class which is registered in the container (either public or private) is checked and either the `ReflectionClassResource` or `ClassExistenceResource` is created for it (and thus checked during every `isFresh` check). While there is a low chance that such class would actually match the type being searched by the autowiring. This is visible by unserializing the `.meta` file, which shows that the (updated) test project has 16 resources, while, when adding a `Bar` service, there are only 14 resources being checked. This difference isn't that much, but in my actual project the difference of course is bigger. So personally I find this a bit odd and I think it would be better if these classes/files weren't checked on every call.

**Comment by chalasr** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
That's normal behavior. The missing classes have to be tracked as such. Imagine you create them after the container is dumped: then the container needs to be recompiled.

**Comment by chalasr** [comment]
Can we close?

**Comment by jakzal** [comment]
Closing for reasons given by Nicolas.

**Comment by stof** [comment]
Well, checking if the container is still fresh should not trigger a ReflectionException though. Invalidating the cached container is not the same than breaking things when checking whether it should be invalidated.

**Comment by nicolas-grekas** [comment]
@stof my answer applied to https://github.com/symfony/symfony/issues/23946#issuecomment-325909635
the exception is gone in 3.3.8 :)
