### ISSUE TITLE
The annotation color is difficult to see.

### ISSUE THREAD

**Issue by MarwenBenTalebAli** [symfony/symfony#23957]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

Hello,
Im working on a Symfony project on eclipse IDE.
Im using Windows7-64bit and Eclipse Java EE IDE for Web Developers
Version eclipse: Oxygen Release (4.7.0).
Version PHP: 7.1.7 

I download eclipse from official site and after I install the plugin Darkest dark theme all works normally. And when I install the Symfony plugin the bug appears.

I opened the perspective php.
- The file is opened with a php editor.
- The Editor Colors is set to ‘Darkest Dark’ theme.

The problem: **The annotation color is difficult to see.**
 the problem is with this code:
```
/**
 * @Assert\NotBlank(message="Champ obligatoire!")
 * @Assert\Length(min=10, minMessage="Le login doit faire au moins {{ limit }} caracteres.")
 */ 
protected $login;
```
no problem:
```
 /*message comment*/
//message comment
```

See details in the attach file.

![annotation-color](https://user-images.githubusercontent.com/29453089/29606906-80b9a77a-87e7-11e7-973a-436d4773679d.png)

in General > Appearance, i tryed all themes
-Windows classic theme, not working fine
-Light theme, working fine
-Windows XP Blue theme, working fine
-Windows XP Olive, working fine
-Classic , working fine
-Dark, not working fine
-Darkest Dark – It’s a Total Eclipse, not working fine

Im using these annotations @Assert and @ORM.
whene importing these annotations

```
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
```
it says:
```
The import Symfony\Component\Validator\Constraints is never used
The import Doctrine\ORM\Mapping is never used
```

**Comment by mvrhov** [comment]
This is not a problem of symfony but of an IDE you are using.

**Comment by MarwenBenTalebAli** [comment]
I post this bug on the Darkest Dark Theme forum and eclipse's bugzilla.

The Genuitec suggest me the issue to Symfony plugin creators.
And im still watting the answer from eclipse's bugzilla.

**Comment by nicolas-grekas** [comment]
This should be reported on https://github.com/Haehnchen/idea-php-symfony2-plugin

**Comment by Simperfit** [comment]
@MarwenBenTalebAli @nicolas-grekas since this is eclipse should be reported here ;)

**Comment by Seb33300** [comment]
The eclipse plugin repository seems to be this one: https://github.com/pulse00/Symfony-2-Eclipse-Plugin

**Comment by MarwenBenTalebAli** [comment]
ok, ty
