### ISSUE TITLE
kernel.project_dir (getProjectDir()) silently returns incorrect path without composer.json

### ISSUE THREAD

**Issue by spaivaras** [symfony/symfony#23950]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| Symfony version  | 3.3.x

Currently in symfony 3.3.x parameter kernel.project_dir silently returns kernel_dir if composer.json is not found at all. IMHO it shouldn't be related with composer.json as in prod environment, composer is typically not needed at all, so files could be discarded from build artifacts. So even an error or a warning would be better here compared to option that you can get 2 different paths depending on that you have or not have a 3rd party file.

even cache:clear fails with missing files errors, if project_dir is used without composer.json file
```
PHP Fatal error:  Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "/var/www/releases/20170822132058/app/vendor/willdurand/geocoder/Dumper" does not exist. in /var/www/releases/20170822132058/vendor/symfony/config/FileLocator.php:46
111

**Comment by stof** [comment]
Well, if you don't want it to depend on the presence of the composer.json, you can overwrite the method in your own kernel.
Harcoding the nesting level of your own kernel class inside your project structure in Symfony itself cannot work (the kernel can be in different places). Finding the composer.json file made it easy to build a generic implementation working for all people not removing the composer.json.
However, inside your own AppKernel, implementing a project-specific retrieval not bound to the composer.json is dead simple (it will be `return dirname(__DIR__);` if you use the structure of the standard edition)

**Comment by nicolas-grekas** [comment]
I agree with @stof (btw, you're not the only one cleaning composer.json, and this solution was provided before and was OK.)

**Comment by xabbuh** [comment]
I agree with @stof and @nicolas-grekas. Thus, closing here as there is an easy way to override the project dir config if needed.

**Comment by mvrhov** [comment]
So why is the projectDir variable private then? Why do I have to re-declare it in my kernel?

**Comment by chalasr** [comment]
@mvrhov the `kernel.project_dir` parameter uses the return value of `Kernel::getProjectDir()`, override this method to set a custom path.

**Comment by mvrhov** [comment]
rootDir variable is protected.. so I can set it once and next time just return the cached value.
For projectDir I have to redeclare the variable in a child to do the same. That's why I'm asking.

**Comment by stof** [comment]
@mvrhov rootDir being protected is a legacy reason. We cannot make it private due to the change being a BC break. but the new property can be private without issue.
The support way to customize this has always be to overwrite the method (even for rootDir, the doc talked about overriding the getter)

**Comment by chs2** [comment]
Hi, 

I just hit the same problem on production and I wondered, now that ".env" is required by public/index.php, if it couldn't be added to the test in Kernel::getProjectDir() with "composer.json" ?

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L347
```php
while (!file_exists($dir.'/composer.json') && !file_exists($dir.'/.env')) {
/* … */
}
```
