### ISSUE TITLE
[PHPUnitBridge] not removing packages should be supported

### ISSUE THREAD

**Issue by stof** [symfony/symfony#23955]
Currently, if the `SYMFONY_PHPUNIT_REMOVE` env var is set to an empty string, the behavior is the same than when it is not set at all: remove `symfony/yaml phpspec/prophecy`. So there is no easy way to remove nothing.
The current workaround is to ask it to remove an unrelated package (composer will tell you there is nothing to remove, but won't fail).

**Comment by Simperfit** [comment]
What could be done here is to test that `SYMFONY_PHPUNIT_REMOVE` is empty string  or null and in this case remove nothing ? and in the case that it is not set, remove `symfony/yaml phpspec/prophecy` WDYT?

**Comment by xabbuh** [comment]
Well, the issue is that this would be a BC break regarding the current behaviour when `SYMFONY_PHPUNIT_REMOVE` is set to the empty string.

**Comment by Simperfit** [comment]
What do you think of deprecating the behaviour and changing it in next major ?

**Comment by stof** [comment]
@xabbuh I would say that setting it to an empty string and then still getting things removed is quite unexpected behavior. I would consider it a bug, as we are not doing what the user intention is (removing nothing)

**Comment by Simperfit** [comment]
If this ok, I can make a PR to fix the behaviour.

**Comment by chalasr** [comment]
👍  as a bug
