### ISSUE TITLE
Upgrading Symfony project breaks web/config.php and bin/symfony_requirements files

### ISSUE THREAD

**Issue by petk** [symfony/symfony#23963]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

When downloading Symfony 3.3.6 (latest stable version) the `bin/symfony_requirements` and `web/config.php` files work as they should. Once you do `composer update` it breaks them with replacing the require paths from:

```php
require_once dirname(__FILE__).'/../var/SymfonyRequirements.php';
```

to:

```php
require_once dirname(__FILE__).'/./SymfonyRequirements.php';
```

**Comment by fabpot** [comment]
Have you updated SensioDistributionBundle as well?

**Comment by petk** [comment]
The SensioDistributionBundle is at v5.0.20 as it comes with Symfony 3.3.6. I've discovered this is already pointed out here:
https://github.com/sensiolabs/SensioDistributionBundle/issues/324
so this can be probably closed as duplicate then.
