### ISSUE TITLE
"Cache key length must be greater than zero"

### ISSUE THREAD

**Issue by tlorens** [symfony/symfony#23966]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.3.5

Just looking for some ideas on how to debug this and figure out what is causing this exception.  I have the @Cache annotation in a handful of associations. This error doesn't happen often.  Months at a time it'll be fine.  

I don't think this is a bug as I haven't found anyone else having this problem.

**Comment by xabbuh** [comment]
Can you please provide some more context? Do you have a stack trace that makes it possible to see where this issue happens? Can you also show your usage of the `@Cache` annotation?

**Comment by tlorens** [comment]
It's unfortunate I don't have a stack trace since I don't have access to production nor do I have the exactly details of what the user was attempting to do when this happened.   So I'm just trying to figure out where to look on my own and hunt this down.  Maybe there's some sort of handler I can put in place to catch this and gather more info??   From what I know the entity the user attempted to updated.       * @Cache("READ_WRITE") on a few relationships that might change.   * @Cache("READ_ONLY") on a relationship that doesn't change ever since it's creation.  Now that I'm looking, I'm not even sure these are being used as the entity itself doesn't have the @Cache annotation.

**Comment by tlorens** [comment]
In my entity I have a association annotated like so. 
```

* @UniqueEntity(
 *     fields={"workpaperReference", "audit"},
 *     repositoryMethod="uniqueWorkpaperRef",
 *     message="A piece of evidence already leverages that reference number. No changes were made."
 * )
 
```

The Property is annotated like this
```

     * @ORM\Column(name="workpaper_reference", type="string", length=255, nullable=true)
     * @Assert\Valid()
     * @Gedmo\Versioned
```

The error appears to happen when a user blanks the field.  So it may be an issue with the validator and the error message isn't correct?

**Comment by xabbuh** [comment]
@tlorens Do you think you can provide a full example that allows to reproduce the issue? Otherwise I am afraid that we cannot do much here.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
