### ISSUE TITLE
Impossible to use container in controllers injected in another services

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#23973]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.3

Example: https://github.com/BoShurik/symfony-standard/commit/af755c3d696153da2921dd555f853d3e26970c2f

`Call to a member function get() on null`

for `MenuController.php`

```php
public function widgetAction()
{
    return new Response($this->generateUrl('homepage'));
}
```

**Comment by mvrhov** [comment]
I'd say you are doing it wrong, but that's me.

**Comment by BoShurik** [comment]
Yes, its simplified example. In this case better to use `render(controller())`.

**Comment by xabbuh** [comment]
There's no bug. You simply do not call `setController()` on your `MenuController`.

**Comment by BoShurik** [comment]
Yes, but its strange that I do not need to call it for controllers called from router. Maybe set container automatically for `ContainerAwareInterface` via `autoconfigure`?

**Comment by NicoHaase** [comment]
You did not call the MenuController from the router, as far as I can see

**Comment by BoShurik** [comment]
Yes, but if I do there would be no exception

**Comment by nicolas-grekas** [comment]
> do not need to call it for controllers called from router

see https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L74

I guess we can close then.

**Comment by xabbuh** [comment]
Closing here as calling `setContainer()` automatically is a feature of the controller resolver but not of the DI component.
