### ISSUE TITLE
[Security][Guard] method ::start never called

### ISSUE THREAD

**Issue by kuboslav** [symfony/symfony#23981]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I'm playing with Symfony Flex. Following [this tutorial](https://symfony.com/doc/current/security/guard_authentication.html) I've set up token authentication system.

Everything works fine, except *“no token”* situation. `GuardAuthenticator` calls `::onAuthenticationFailure` instead of calling `::start` method. I've tried both to throw `AuthenticationException` from `::getUser` or return `null`.

My Authenticator class is properly registered as service. I've tried configure it as `guard.entry_point`, but no success.

**Comment by kuboslav** [comment]
Now I've tried it with Symfony version 2.8.26 and result is the same.

**Comment by Nek-** [comment]
Hello, thanks for you're report. Can you provide a reproducer please?

http://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by kuboslav** [comment]
**Bug Reproducer**

https://github.com/kuboslav/symfony-standard/tree/issue_23981

Run app: `php app/console server:run`
Make request: `curl http://localhost:8000/`

Expected:
```
HTTP/1.1 401 Unauthorized
…
{
    "message": "Authentication Required"
}
```

Actual:
```
HTTP/1.1 403 Forbidden
…
{
    "message": "Username could not be found."
}
```

**Comment by derrabus** [comment]
The framework will only call the entry point of a firewall, if all authenticators have failed to find credentials. So if you want your guard authenticator to act as the entry point (which is basically the purpose of the `start()` method), you need to make sure that no authenticator claims that credentials (valid or not) have been found inside the request.

In your case, you've enabled the anonymous authenticator on your firewall which will always be able to authenticate the request. This is probably not what you want.

Secondly, `getCredentials` needs to return `null` to indicate that no credentials have been provided.

```php
public function getCredentials(Request $request)
{
    if (!$token = $request->headers->get('X-AUTH-TOKEN')) {
        // No token?
        return null;
    }

    // What you return here will be passed to getUser() as $credentials
    return array(
        'token' => $token,
    );
}
```

I see that this is documented differently in that cook book article. So the documentation should be changed, imho.

**Comment by kuboslav** [comment]
@derrabus Thanks! It works like a charm :)
