### ISSUE TITLE
Form rendering throws notice if the form is submitted with array instead of string

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#23995]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

When the user uses Chrome Inspect feature and changes the `<input type="text"` name to include an extra array (e.g. from `article_form[title]` to `article_form[title][foobar]`, the form fails to render. The reason is that the template is trying to render the "invalid" array as an `<input>` value.

```
Twig_Error_Runtime:
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").

  at vendor\symfony\symfony\src\Symfony\Bridge\Twig\Resources\views\Form\form_div_layout.html.twig:13
  at Twig_Template->displayBlock('form_widget_simple', array('value' => array('foo' => 'aa'), 'attr' => array(), 'form' => object(FormView), 'id' => 'article_form_title', 'name' => 'title', 'full_name' => 'article_form[title]', 'disabled' => false, 'label' => 'Article title', 'label_format' => null, 'multipart' => false, 'block_prefixes' => array('form', 'text', '_article_form_title'), 'unique_block_prefix' => '_article_form_title', 'translation_domain' => null, 'cache_key' => '_article_form_title_text', 'errors' => object(FormErrorIterator), 'valid' => false, 'data' => array('foo' => 'aa'), 'required' => true, 'size' => null, 'label_attr' => array(), 'compound' => false, 'method' => 'POST', 'action' => '', 'submitted' => true, 'app' => object(AppVariable)), array('form_widget' => array(object(__TwigTemplate_74fc98e978cb4218b308d1fa4d08196af014f2b1069a5f65da3ed6ecc38bdf83), 'block_form_widget'),
...
```

The problematic line in the template is this: https://github.com/symfony/symfony/blob/3a9653df72fd268aa9f0f968ec32eafbd886dd0d/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L13

The simplest repro-case I managed to create is this one:

```php
    public function createAction()
    {

        $form = $this->createFormBuilder(
            [
                'title' => [
                    'foo' => 'bar',
                ],
            ])
            ->add('title', TextType::class)
            ->getForm();

        return $this->render('article/add-article.html.twig', [
            'form' => $form->createView(),
        ]);
    }
```

```twig
# article/add-article.html.twig
{% block body %}
	{{ form(form) }}
{% endblock %}
```

**Comment by iltar** [comment]
So that means the page would result in a 500 error because the user is messing with the HTML?

**Comment by mhujer** [comment]
No, I jumped to conclusion too fast. It only reports a notice. Which is converted to exception in `dev` mode.

In `prod` mode it converts the data to string `Array`:
![image](https://user-images.githubusercontent.com/353372/29741358-323ee732-8a6b-11e7-9440-6af76f4cc5c5.png)

It happens also on the Symfony.com: http://symfony.com/search?q[foo]=form.

But if the developer forgets to add `@Assert\Type(type="string")`, the form may validate just fine and pass the array further in the app. Which may actually be happening - the Symfony web searches for term `Array`.

(I checked several webapps and most of them are prone to this issue)

**Comment by sstok** [comment]
I'm not entirely sure how we can fix this this properly, we could add a safe guard in the themes (which will not fix this issue for custom themes). 

Or we can add a transformer to ensure if a none scalar value is provided it's transformed to an empty string. But this could be considered a BC break as some may have added additional transformer(s) that expect this kind of behavior 🤔

**Comment by mhujer** [comment]
@iltar I'm afraid I found a case when it fails with 500.

_Can someone please check that I haven't overlooked something?_

When there is another assert - such as `@Assert\Email()` or `@Assert\Length(min="10", max="100")` which expects string-ish value, they do this check:

```php
        if (!is_scalar($value) && !(is_object($value) && method_exists($value, '__toString'))) {
            throw new UnexpectedTypeException($value, 'string');
        }
```

So if the `$value` is of type `array`, exception is throw and the error page is rendered.

The `Type` validator is called (if it is before other validators - such as in the example bellow), but it does not prevent the other validators from being called.

```
Symfony\Component\Validator\Exception\UnexpectedTypeException:
Expected argument of type "string", "array" given

  at vendor\symfony\symfony\src\Symfony\Component\Validator\Constraints\LengthValidator.php:37
  at Symfony\Component\Validator\Constraints\LengthValidator->validate(array('foo' => 'aaaa'), object(Length))
     (vendor\symfony\symfony\src\Symfony\Component\Validator\Validator\RecursiveContextualValidator.php:850)
  at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateInGroup(array('foo' => 'aaaa'), null, object(GenericMetadata), 'Default', object(ExecutionContext))
     (vendor\symfony\symfony\src\Symfony\Component\Validator\Validator\RecursiveContextualValidator.php:696)
  at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateGenericNode(array('foo' => 
...
```


Case for reproduction (you need to change input name from `form[title]` to `form[title][foo]`:
```php
    public function createyAction(Request $request)
    {
        $form = $this->createFormBuilder()
            ->add('title', TextType::class, [
                'constraints' => [
                    new Type('string'),
                    new Length(['min' => 10]),
                ],
            ])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //foo
        }

        return $this->render('article/add-article.html.twig', [
            'form' => $form->createView(),
        ]);
    }
```

```twig
# article/add-article.html.twig
{% block body %}
	{{ form(form) }}
{% endblock %}
```

**Comment by mhujer** [comment]
Related: #14943 and #20935

**Comment by iltar** [comment]
Honestly, if a user messes with the input fields, a 500 is justified. Won't have to expect valid responses if you send invalid requests

**Comment by mhujer** [comment]
For me it seems unexpected from the DX point-of-view: If the proper `@Assert\Type()` annotations are added, it should work like any other validation.

And I think it may be possible to flood the server logs with this error.

**Comment by techi602** [comment]
@iltar you can not justify error 500 for unhandled user input validation (error 400 bad request would be more suitable in this case - yet still embarrassing for simple form validation)
Imagine hackbots which will spam your application error logs with random input field names.

**Comment by ianmclaughlin** [comment]
HTTP 400 (Bad Request) is for client errors, so it's inappropriate to return 500

Our logs are being filled with exceptions which don't need to be thrown

**Comment by xabbuh** [comment]
closing in favour of #4102
