### ISSUE TITLE
[Lock] unit test error on macOS, Call to undefined function pcntl_sigwaitinfo()

### ISSUE THREAD

**Issue by l1l31** [symfony/symfony#23993]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-dev

when i run unit test, it's report:

```
4) Symfony\Component\Lock\Tests\Store\SemaphoreStoreTest::testBlockingLocks
Error: Call to undefined function pcntl_sigwaitinfo()

/private/var/www/symfony-lock/Tests/Store/BlockingStoreTestTrait.php:79
Error: Call to undefined function pcntl_sigwaitinfo()
```

because `pcntl_sigwaitinfo` function is not avaliable on macOS, see https://bugs.php.net/bug.php?id=70708

**Comment by javiereguiluz** [comment]
@l1l31 thanks for reporting this issue. We're trying to fix it in #24004.
