### ISSUE TITLE
AbstractDumper::dumpLine() and echoLine() don't properly document the $depth parameter

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony#23992]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

The docs for AbstractDumper::dumpLine() and echoLine() say:

>      * @param int $depth The recursive depth in the dumped structure for the line being dumped

and 

>      * @param int    $depth     The recursive depth in the dumped structure

Yet this is called with a depth of -1:

```
            $this->dumpLine(-1);
```

That doesn't make sense if the depth is as described in the documentation.

**Comment by nicolas-grekas** [comment]
There need to be this special case, to signal the last line and allow closing the dump.

**Comment by nicolas-grekas** [comment]
see #23999
