### ISSUE TITLE
Bad error message when controller argument cannot be injected

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#23997]
I've the following code:

```php
class ConnectController extends AbstractController
{
    public function loginAction(Request $request, ConnectEntryPoint $entryPoint)
    {
    }
```

I get this error message:

```
Controller "App\Controller\ConnectController::loginAction()" requires that you provide a value for the "$entryPoint" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.
```

Which tells me that there is probably no `ConnectEntryPoint` service but it's not very explicit about why... knowing that I do have such a service... at least almost :)

But if I move the injection to the constructor like this:

```php
class ConnectController extends AbstractController
{
    public function __construct(ConnectEntryPoint $entryPoint)
    {
    }
```

Then, I get the right error message with a nice hint about how to fix it:

```
Cannot autowire service "App\Controller\ConnectController": argument "$entryPoint" of method "__construct()" references class "SensioLabs\Connect\Security\EntryPoint\ConnectEntryPoint" but no such service exists. You should maybe alias this class to one of these existing services: "security.authentication.entry_point.sensiolabs_connect", "security.authentication.entry_point.sensiolabs_connect.website".
```

Can we try to get this message in the first case as well?

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Fixing this would require making individual argument resolver to supersede this generic exception message - ie the controller resolver mechanism currently have no context to know that this message should be triggered.
For now, the message can still be found in the compiler logs (I'm not saying this is enough :) )

**Comment by chalasr** [comment]
Problem is that another value resolver could be able to resolve it, so just returning a specific error when this one fails would be wrong. We could use the ServiceValueResolver error as last resort in case no one _supports_ the arg, but that would still mean we assume that you want a service at first, while you could be looking for something else that could not be resolved (e.g. a doctrine entity).

**Comment by nicolas-grekas** [comment]
I'll try something by the end of the week

**Comment by sroze** [comment]
Happy to take this one. @nicolas-grekas did you have any specific way of solving it in mind?

**Comment by nicolas-grekas** [comment]
I think we can solve quite easily this by adding a new behavior for references, we could name e.g. `ContainerInterface::RUNTIME_EXCEPTION_ON_INVALID`.
We would also need to add `getError()/adderror()` methods on `Reference`, as we already did on `Definition`, to define the exception message. Then, `PhpDumper` and `ContainerBuilder` would throw these when appropriate. Should be doable for 4.1 I suppose, if someone wants to give it a try.

**Comment by weaverryan** [comment]
In the case of a service locator (like the one used in the arg resolver), when would the error be triggered exactly? When we actually try to access the service from the locator? In that case, wouldn't the error happen as soon as the service arg resolve tried to resolve the argument (therefore not allowing other resolvers a chance)? I'm very interested in this, and now I can see most of the picture... but not quite all yet :)

**Comment by nicolas-grekas** [comment]
It would throw when accessing the service yes.
Yes, it would prevent any lower priority resolver to act.
But I don't think there is any use case for a lower priority resolver, so should be acceptable IMHO.
