### ISSUE TITLE
Limit the console application exit code to 254 because 255 is reserved by PHP

### ISSUE THREAD

**Issue by vertexvaar** [symfony/symfony#24037]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

[Console/Application](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L157) limits the exit code to 255 which is reserved by PHP according to the [documentation of exit](http://php.net/manual/en/function.exit.php)
The exit code should be limited to 254 instead.

**Comment by fabpot** [comment]
We don't limit which code you can use. That's not the responsibility of the component. The code you mention is just there to avoid invalid exit code.
