### ISSUE TITLE
[Console][DI][DependencyInjection][RFC][Feature] Placeholder method for getting services directly from container into the ContainerAwareCommand

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony#24032]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | any

How about to add into the [ContainerAwareCommand](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php) a placeholder method for getting service from container like it has done into the abstract Controller:
https://github.com/symfony/symfony/blob/v2.8.19/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php#L378-L392

**Comment by iltar** [comment]
Ideally you would just inject your dependencies, especially now that auto-wiring is maturing. I see no need to make service locators easily accessible.

**Comment by chalasr** [comment]
We are currently moving from container aware stuff to proper dependency injection. Can you give us your use case for extending ContainerAwareCommand? We believe it is not needed anymore thanks to the recent changes in DI, we may deprecate it on the long run since even the core doesn't need it anymore.

**Comment by Aliance** [comment]
So every command should be registered as a service?

Currently, I use `ContainerAwareCommand` only for two usecases:

1. Getting the container parameter, such as current ENV or whatever from `parameters.yml`
2. Getting some services from `services.yml`

So yes, registering a command as a service will solve every of this usecases.

I'm using 2.8, does it supports this behavior?

**Comment by iltar** [comment]
2.8 supports registering commands as a service afaik, but for newer features such as (proper) autowiring, you'll need 3.3 minimal.

**Comment by Aliance** [comment]
Thank you for the advice, I suppose that I can close this issue.
