### ISSUE TITLE
parse error with asset:install AnnotationRegistry.php on line 50

### ISSUE THREAD

**Issue by viejalospelos** [symfony/symfony#24035]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.27

I just update symfony this morning and now, when I use the command asset:install, I obtain this message:
Parse error: syntax error, unexpected ':', expecting ';' or '{' in ...\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationRegistry.php on line 50

**Comment by iltar** [comment]
Seems like you've installed the annotation registry for a php 7.1 version rather than what you're running it on, this is not related to Symfony though.

**Comment by xabbuh** [comment]
As @iltar said you need to use a version of `doctrine/annotations` that is compatible with your PHP versions (i.e. don't use 1.5.x as it requires PHP 7.1 or higher.

**Comment by viejalospelos** [comment]
Thanks for your response, as you said me, it goes back to work fine with doctrine/annotations 1.4 but it's strange because I'm using php 7.1.1 and I hadn't problems with installation

**Comment by iltar** [comment]
Make sure you run `composer update` on the same php version/settings as where you run `composer install` and your application

**Comment by xabbuh** [comment]
Most likely you are using a different PHP version during development than what you have on your production server.

**Comment by andresrex** [comment]
This solved this issues: https://bolt.cm/item/fixing-issues-after-the-recent-doctrine-2-6-update, just need to add to composer.json the following:

```
	"config": {
		"platform": {
			"php": "5.6"
		}
	}
```

**Comment by charlieartist** [comment]
What is odd is that I'm getting this issue on some builds, even though my server is running PHP 7.1.x, and I do have the PHP version set in my composer.json file. To confirm, I'm running v.1.5.

**Comment by mamallana** [comment]
When you install the composer if you pointed to php 7 then make sure current server(wamp) pointing to the  same php version.
