### ISSUE TITLE
Can't define the id attribute of a widget in a form from the controller

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony#24044]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I tried to define the id attribute of a widget in a form using a [form class](https://symfony.com/doc/current/forms.html#creating-form-classes).

Is it normal that we can't customize the id of a widget while we can for a label?
For more details[ see my question on SO](https://stackoverflow.com/questions/45962997/how-can-i-define-the-id-attribute-of-a-widget-in-a-form-from-a-symfony-controlle).

I created [a sandbox project that reproduces the issue](https://github.com/Kwadz/sf-widget-custom-id).

**Comment by jakzal** [comment]
Thank you for taking time to submit this bug report with the sandbox. Very helpful!

However, as you probably expected Symfony relies on this behaviour, see https://github.com/symfony/symfony/issues/20965#issuecomment-339342545
