### ISSUE TITLE
[Workflow] Initialize without any pre-configured workflows

### ISSUE THREAD

**Issue by nea** [symfony/symfony#24051]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3

Hi everyone

I am looking into the workflow component as it would pose a very interesting solution for many use cases we are facing.
We are especially looking into dynamically working with the workflows and initializing them. 

But there is one thing, I want to ask if reasonable to change in line https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L476

Does it make sense, to not load the services if no global workflows are configured? Right now, I have defined a dummy workflow to be able to access the registry to add additional, dynamic workflows.

If at least everything is initialized from the beginning, the registry could be used later on to configure workflows more dynamically.

Does that make sense what I am babbling about ^^? Or is there a specific reason for the current design decision I do not see?

Thanks a lot in advance

**Comment by ro0NL** [comment]
I think the trick is to support `framework.workflows: false` which explicitly disables. And perhaps `framework.workflows: ~` to enable without any workflows configured.

**Comment by nea** [comment]
Hi @ro0NL 

I tried ~ (same idea ^^) but didn't work out. Also tried with an empty array but then the validation kicks in as it iterates the content and fails the validation (unfortunately).


Thanks

**Comment by ro0NL** [comment]
Yeah we need to patch that first :)

**Comment by xabbuh** [comment]
see #24093
