### ISSUE TITLE
HttpFoundation Parsing XML (Escape and Filter Issue with character 'e')

### ISSUE THREAD

**Issue by impixel** [symfony/symfony#24054]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.8.0

 I have created an endpoint to accept POST request and in payload I have a XML file, when dumping the request I get an array with elements of the XML payload; However, if value of one of the key contains escaping character 'e', it will add plus and makes the character capital case, please look at example below:

`<member guid="349ff4Aa" status="Active" number="59e611" >`

will become:

`["guid" => "349ff4Aa", "status" => "Active", "number" => 59E+611]`

So in any case that, there is a character 'e', it will filter and sanitise incorrectly, for example: value of `199e001` will become `19900` in Request ParameterBag.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
