### ISSUE TITLE
[Serializer] Add ignored attributes option

### ISSUE THREAD

**Issue by mdeboer** [symfony/symfony#24071]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I know the serializer is due for a redesign (#19330) but I'm daring to make a feature request for the time being. Currently (afaik) the mapping (yaml/xml/annotations) lack a way of ignoring attributes and you end up writing a normalizer to do just that.

With a bit of digging I figured it won't be too difficult to add an attribute metadata option to ignore the attribute (as is done for `groups` and `maxDepth` options). This can then be read by the (to be written) `getIgnoredAttributes` getter to get the ignored attributes, instead of accessing the `ignoredAttributes` array directly.

The ignored attribute is useful for classes that have no groups but want to exclude a property, say the `id` property. It's cumbersome to add a group specifically to do that.

The YAML could look like this:

```yaml
My\Fancy\Namespace\Entity\Alien:
  attributes:
    id:
      ignore: true
```
Or to keep things clean:
```yaml
My\Fancy\Namespace\Entity\Alien:
  ignoredAttributes:
    - id
```

Please share your thoughts as I'm willing to implement this 👍

**Comment by raresserban** [comment]
This would be especially useful when also using the ApiPlatform project with entities with a lot of fields.

**Comment by vsilvestre-accenture** [comment]
This actually exist through [ignored_attributes](https://symfony.com/doc/current/components/serializer.html#ignoring-attributes) isn't it ?

**Comment by javiereguiluz** [comment]
Closing as fixed because of what @vsilvestre-accenture said. Thanks!

**Comment by theoaks** [comment]
That approach is not a neat way to do it... I would have preferred using an annotation. That way, we can abstract certain implementations and not worry about case to case basis. You guys can take a cue from NewtonSoft.Json. Everything they did is using C# attributes (which is the idea behind PHP Annotations)

**Comment by raresserban** [comment]
@theoaks There is a pull request for this:
https://github.com/symfony/symfony/pull/28744

**Comment by mdeboer** [comment]
@theoaks in hindsight I agree on this (mind you, this is openened more than two years ago). But yes there is a PR open for this as mentioned.
