### ISSUE TITLE
Wrong entity name with crud generator

### ISSUE THREAD

**Issue by aref-lazrek** [symfony/symfony#24070]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

The crud generator creates wrong entity name in newAction()
the use is right `use AppBundle\Entity\Transactions;`
but here it's 
`    public function newAction(Request $request)
    {
        $transaction = new Transaction();
     ...
    }`

**Comment by chalasr** [comment]
Closing as `generate:crud` is part of https://github.com/sensiolabs/SensioGeneratorBundle, not symfony. Please consider reporting it there.
