### ISSUE TITLE
[RFC] Deprecate the "matcher" option of the profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24077]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

As [commented by Fabien](https://github.com/symfony/symfony/pull/22484#issuecomment-326814184), we could deprecate the `profiler.matcher` option:

> The matcher configuration was added at a time where we thought that having the profiler in production could make sense (and so being able to enable it conditionally made sense). That's not the case anymore. Nobody should ever enable it in production.
>
> With that in mind, I would go in the other direction and remove the matcher config altogether for Symfony 4.0 (deprecating it in 3.4 first of course).

**Comment by stof** [comment]
This makes sense to me. I never used this option

**Comment by hhamon** [comment]
I've never used it either.
