### ISSUE TITLE
[Dotenv][WebServerBundle] Possible BC break when overriding previously loaded variables

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24078]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3

As reported by @tiger-seo in https://github.com/symfony/symfony/pull/23799:

-----

1) i am grateful for all your hard work, but this change is a breaking change and it is not mentioned :(

2) to give you more info why it is a BC, please see our `env_autoload.php`, which is used instead of `autoload.php`:
```php
<?php

/** @var \Composer\Autoload\ClassLoader $loader */

use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Dotenv\Exception\PathException;

$loader = require __DIR__ . '/autoload.php';

$dotenv = new Dotenv;

try {
    // existing environment variables are never overridden
    $dotenv->load(__DIR__ . '/config/.env');
} catch (PathException $e) {
}

// existing environment variables are never overridden
$dotenv->load(__DIR__ . '/config/.env.dist');

return $loader;
```

3) @tiger-seo, I think you could try to load the `.env.dist` earlier than the `.env`:
```php
// existing environment variables are never overridden
$dotenv->load(__DIR__ . '/config/.env.dist');

try {
    // existing environment variables are never overridden
    $dotenv->load(__DIR__ . '/config/.env');
} catch (PathException $e) {
}

return $loader;
```

4) yes, this is exactly how we've fixed it

**Comment by nicolas-grekas** [comment]
I'm not sure we should do anything here. Fixing this is a BC break. Since the component is new, it's easier for ppl to update their code. I know this is not the policy and if we've notice this change earlier, we would have think twice about it.

Yet, looking at the broken code, it is already very strange to me to rely on an exception to "fallback". I'd expect ppl to do a file_exists check instead.

**Comment by voronkovich** [comment]
@nicolas-grekas, we could fix it by adding a BC break note.

**Comment by nicolas-grekas** [comment]
Would you mind opening a PR doing so?

**Comment by voronkovich** [comment]
@nicolas-grekas, I've created a PR: https://github.com/symfony/symfony/pull/24081
