### ISSUE TITLE
autocomplete only works on the first item of a multiselect question

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony#24072]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I have a multiselect question, created using the sample code at https://symfony.com/doc/current/components/console/helpers/questionhelper.html#multiple-choices

When I run the command, the first option autocompletes. Subsequent options do not.

So for example:

```
Please select your favorite colors (defaults to red and blue)
  [0] red
  [1] blue
  [2] yellow
```

With this input:

> r

the rest of the word 'red' appears and a press of TAB takes me to the end of the word.

With this input:

> red, b

nothing happens.

**Comment by chalasr** [comment]
Autocompleting multi-choice questions may not be supported currently and would probably be nice to have. Not totally sure this qualifies as a bug though
