### ISSUE TITLE
symfony/console: ArrayInput->__toString() val can be an array

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#24087]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Input/ArrayInput.php#L113

Value can be an array for example while testing with ArrayInput and multiple values. Everything else work as expected, but the escape failed, cause its written for strings.

```
new ArrayInput([
    '--option' => ['value1', 'value2']
]);
```

**Comment by chalasr** [comment]
See #24096
