### ISSUE TITLE
Environment var + routing schemes is broken with 3.3.7+

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#24086]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.7

Hello.

### Issue

We used to control the scheme of the URL with an environment variable (`HTTP_SCHEME`).
It used to work fine until Symfony 3.3.7

### Reproducer

We noticed a regression in the processing of environment variables and routing schemes.

I have created a [producer here](https://github.com/lyrixx/symfony-standard/commit/7c4a730dc8f41309b3aa94804824984a3b1a10f4).
It's an extra commit on top of the standard edition with Symfony 3.3.*

I order to reproduce the issue you **need** a real web server (does not work
with PHP -S, nor bin/console server:run).

In the web server you have to add the following line in the PHP location:

    fastcgi_param HTTP_SCHEME https;

**edit:** read the next comment

### Results

(I removed useless headers )

#### With Symfony 3.3.6:

    >[{..}/dev/debug/sf-routing-schema-param](master *) curl http://sf-routing-schema-param.localhost:8888/app_dev.php -I
    HTTP/1.1 301 Moved Permanently
    Location: https://sf-routing-schema-param.localhost/app_dev.php/

#### With Symfony 3.3.7, 3.3.8, and 3.3.*@dev:

    >[{..}/dev/debug/sf-routing-schema-param](master *) curl http://sf-routing-schema-param.localhost:8888/app_dev.php -I
    HTTP/1.1 200 OK
    Server: nginx/1.12.1

**Comment by lyrixx** [comment]
Oh, I found an easier reproducer: Just clone the reproducer, install the vendor and run ` HTTP_SCHEME=https bin/console debug:router` with different version of symfony.

**Comment by nicolas-grekas** [comment]
I think the issue might be related to the name of your env var:
when accessing `$_SERVER['HTTP_SCHEME']`: does the value come from an http header? or from an actual env var?
there can be high security risk related t this ambiguity, and 3.3.7 is more strict on that topic.

**Comment by nicolas-grekas** [comment]
Should be related to #23899 and #23949

**Comment by lyrixx** [comment]
Indeed, If I rename my env var name, the issue is gone.

But I don't know what to do with this issue though

**Comment by nicolas-grekas** [comment]
We should close IMHO, security is at risk here.

**Comment by lyrixx** [comment]
What about adding a sage guard in the DotEnv component: If a var starts with `HTTP_` we could throw an error or a least a notice. WDYT?

**Comment by nicolas-grekas** [comment]
Could be worth at least a note in some docblock/doc yes.
`HTTP_*` env vars do not populate the `$_SERVER` superglobal for security reasons (possible confusion with HTTP headers.)
And env vars that start with `HTTP_*` are also not read from `$_SERVER` for the same reason.
Bot for Dotenv and for the container.

**Comment by lyrixx** [comment]
:+1: I let you do the PR ;)

**Comment by nicolas-grekas** [comment]
@lyrixx I'm closing as there is nothing to do on SYmfony side. Doc PR/issue welcomed.
