### ISSUE TITLE
choice_attr doesn't work for ChoiceType expanded multiple

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#24088]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

i just cloned [symfony-standard](https://github.com/symfony/symfony-standard/tree/34100145781df01182dd9dc7420248ec7b50acd9) and changed these two files

* app/Resources/views/default/index.html.twig
* src/AppBundle/Controller/DefaultController.php

in the template i just added `{{form(form)}}` the controller looks like this

```php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type as F;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        $form = $this->get('form.factory')->createBuilder()
          ->add('field', F\ChoiceType::class,
            [ 'choices' => ['a' => 'a', 'b' => 'b']
            , 'expanded' => true
            , 'multiple' => true
            , 'attr' => ['class' => 'AAA']
            , 'choice_attr' => ['class' => 'BBB', 'required' => true]
            , 'required' => true
            ])
          ->getForm();

        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
            'form' => $form->createView()
        ]);
    }
}
```

In the html that is rendered i don't see the class `BBB` or the `required` on my checkboxes. My goal is to put required on all the checkboxes and then use javascript (something like https://stackoverflow.com/a/24862015) to validate that at least 1 is checked in a group.

HTML is rendered by FireFox 55.0.3

**Comment by HeahDude** [comment]
Nested checkboxes list should never be required otherwise it's not possible to submit them unchecked, https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L399. They all have the same name, and should remain uncheckable.

**Comment by flip111** [comment]
@HeahDude it's possible if you remove the `required` with javascript. And the other part of the issue ... where is the `BBB` class?

**Comment by stof** [comment]
The issue is that you have the wrong structure for the content of your `choice_attr` options. It should either be a callable returning the attributes, or an array of attributes for each choice (with indexes matching the indexes used in `choices`)

**Comment by flip111** [comment]
@stof you're right it works when i change it to

```php
, 'choice_attr' => ['a' => ['class' => 'BBB', 'required' => true], 'b' => ['class' => 'BBB', 'required' => true]]
```
turns into
```html
<input id="form_field_0" name="form[field][]" class="BBB" required="required" value="a" type="checkbox">
```

however the documentation says:

> This can be an array of attributes (if they are the same for each choice)

https://symfony.com/doc/current/reference/forms/types/choice.html#choice-attr

so what's going on?

**Comment by HeahDude** [comment]
>however the documentation says:

>This can be an array of attributes (if they are the same for each choice)

This is a doc issue, and what I'm implementing in https://github.com/symfony/symfony/pull/16834.

**Comment by flip111** [comment]
When was the behavior changed so that the code and documentation is not in sync?

**Comment by xabbuh** [comment]
I am going to close here as this is an issue of the documentation as @HeahDude said.
