### ISSUE TITLE
unable find bundle template

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#24085]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.12

```
Unable to find template "KitWebBundle:Default:index.html.twig" (looked into: D:\xampp\htdocs\kitlabs\lovetosee\app/Resources/views, D:\xampp\htdocs\kitlabs\lovetosee\vendor\symfony\symfony\src\Symfony\Bridge\Twig/Resources/views/Form, D:\xampp\htdocs\kitlabs\lovetosee\vendor\knplabs\knp-menu\src\Knp\Menu/Resources/views).
````

src/KitWebBundle/Resources/view/default/index.html.twig is exist.

**Comment by stloyd** [comment]
```
# Wrong:
src/KitWebBundle/Resources/view/default/index.html.twig
# Correct:
src/KitWebBundle/Resources/views/Default/index.html.twig

**Comment by stof** [comment]
on case sensitive file systems (which is the case by default on Linux), it is important to respect the casing between the template name and the file.

**Comment by lcp0578** [comment]
@stloyd @stof view is wrong, views is correct
