### ISSUE TITLE
Let mkdir exception indicate if a nondir blocks dir creation

### ISSUE THREAD

**Issue by axel-rutz** [symfony/symfony#24097]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3-dev

How to reproduce:

* create a directory
* create a symlink to this directory
* want to create a file via Filesystem::dumpFile('symlink/filename', $someContent)

Expected: File is created.
Result: IOException mkdir(): File exists.

Reason:
```
    public function dumpFile($filename, $content)
    {
        $dir = dirname($filename);

        if (!is_dir($dir)) {
            $this->mkdir($dir);
        }
```

is_dir() does not account for symlinks.

**Comment by xabbuh** [comment]
`is_dir()` should take symlinked directories into account. However, this can fail if the parent directory is missing the executable bit which is necessary to enter this directory. Can you confirm that #24105 gives you these information?

**Comment by axel-rutz** [comment]
Oh in fact this happened when a symlink is there but the target does not exist. The same should happen when any nondir file is in the path where Filesystem::mkdir is to create a dir.

We might consider checking this in mkdir and throw a more illuminating exception for better DX. (At least /me/ is a live example that the current exception can mislead.)

So title may be: Let mkdir exception indicate if a nondir blocks dir creation.

**Comment by axel-rutz** [comment]
I have to correct myself: The exception thwown "IOException mkdir(): File exists." should really be good enuff.
Just in this special case i did not get it. But caring for such special cases would feel like nannying. So closing.

**Comment by axel-rutz** [comment]
For the records: Here's the code to create the symlink target dir. 
```
    if (
      is_link($dir) 
      && ($linkTarget = $fs->readlink($dir, TRUE)) 
      && !file_exists($linkTarget)
    ) {
      $fs->mkdir($linkTarget);
    }
```

My gut feeling is this is more a special use case than a magick we should generally implement so leaving closed as WONTFIX.

**Comment by xabbuh** [comment]
@axel-rutz Thank you for your additional feedback. Though I think we should indeed improve the error message in these cases (see #24134 doing that).

**Comment by axel-rutz** [comment]
@xabbuh Looks fine to me!
