### ISSUE TITLE
Kernel::getProjectDir() - Using $this when not in object context

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#24099]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

I read 
https://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory
and try to use,

Using $this when not in object context

**Comment by iltar** [comment]
That's probably because you're trying to call the method statically while it's not static. Note that this is merely a way of writing down a specific method within a specific class, this is not necessarily executable code.

**Comment by allfreelancers** [comment]
@itar 
I understand, but the article points to a static method of use:

However, given that most of the times getRootDir () is used to get the project root directory, in Symfony 3.3 we've decided to introduce a new method called Kernel :: getProjectDir () which will give you exactly that.

**Comment by sstok** [comment]
You can't call `getProjectDir` as a static as it's not static. See the implementation pull request for details, `Kernel :: getProjectDir ()` is just a way to point a method reference.

**Comment by javiereguiluz** [comment]
@allfreelancers I'm sorry for the confusion. I've updated the blog post to remove the `Kernel::` part, so it no longer looks like a static method. So, I'm closing this issue as "fixed" then.

By the way, most of the times you don't call this method directly but make use of the `kernel.project_dir` container parameter in your services and controllers.

**Comment by chalasr** [comment]
> I understand, but the article points to a static method of use

That's the way we use to describe a method `Class::method()`, PHP itself uses the same.
