### ISSUE TITLE
Make symfony components available as phar files

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#24094]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

When making little scripts it would be useful to have symfony components available as phar files. For example the FileSystem component. Using composer slows things down (also if the vendor folder needs to be copied) and leaves more files around.

**Comment by fabpot** [comment]
Probably something the community can provide, but not something the core team is likely to do and maintain.

**Comment by GromNaN** [comment]
The phar should be the final executable : use composer for development and distribute a phar. Examples: php-cs-fixer, phpunit, cachetool, composer itself...

**Comment by robfrawley** [comment]
The tools you mentioned (`php-cs-fixer`, `phpunit`, `composer` - I'm not familiar with `cachetool`) are meant to be used as stand-alone executables. Things like the file system component (as well as the cache, config, security, etc components), are meant to be used to ease the development of an application through capable, well written, and maintained libraries. I don't see why shipping them as a phar would be particularly beneficial for any of these. In fact, it brings us back to the behavior we had before composer existed, where dependencies had to be fetched one-by-one and unzipped into place, or downloaded using pear.

**Comment by chalasr** [comment]
I agree with @robfrawley. All these packages are (or provide) final applications. For symfony there would be no executable entry point, thus phars would just be archives. Not for the core to me.
