### ISSUE TITLE
Profiler and Dinamics Entity Managers

### ISSUE THREAD

**Issue by Banegasn** [symfony/symfony#24116]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.13

Hello i'm using dynamics Entity Managers because my application uses different databases all the time
and i want to debug some of the queries i do in this connections but profiler doesn't show the queries

Code Example that i use to create entity managers in a service

```php
return \Doctrine\ORM\EntityManager::create(
            $connectionParams,
            $this->configuration,
            $this->eventManager
);
```
How could i log the queries made with this entity manager in the profiler?

**Comment by stof** [comment]
Well, make sure that the DBAL configuration contains a logger hooked into the collector.

**Comment by Banegasn** [comment]
i managed to do this but i get a warning saying that `container->get('doctrine.dbal.logger.profiling.common')` is deprecated

I want to log the queries to be able to see them in the web debugger / profiler

What is the right way to do this without the deprecation warning

```php
        $NewEM = \Doctrine\ORM\EntityManager::create(
            $connectionParams,
            $this->configuration,
            $this->eventManager
        );

        $NewEM->getConnection()->getConfiguration()->setSQLLogger( $this->container->get('doctrine.dbal.logger.profiling.common')  );

        return $NewEM;

```

**Comment by stof** [comment]
well, getting a private service dynamically is indeed deprecated (and may break if the service is inlined). But you could define a public alias for it.

Btw, if you want to see queries logged separately from the ones from the `common` connection, you should create a separate logger and hook it in the collector.

**Comment by Banegasn** [comment]
Thanks for your answer @stof 
Could you provide me a sample code to achieve this?
I'm struggling to do this since days

**Comment by javiereguiluz** [comment]
I'm closing this old issue because if it's a problem of public/private services, you can do what @stof said: create an alias of the private service and make the alias public. See https://symfony.com/doc/current/service_container/alias_private.html

If the problem is about the Doctrine DBAL logger, it's better to ask about that in the repository of Doctrine DBAL. Thanks!
