### ISSUE TITLE
var-dumper mobile responsive

### ISSUE THREAD

**Issue by eb22fbb4** [symfony/symfony#24117]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

By default, the dump function print text is very small in mobile mode.

![1](https://user-images.githubusercontent.com/20163117/30143897-a4be02ae-93ba-11e7-88fc-ed3323fccc48.png)

I try to do modify the source code，add meta for mobile responsive in HtmlDumper::getDumpHeader :

```html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```

![2](https://user-images.githubusercontent.com/20163117/30144011-4075f9b8-93bb-11e7-848d-ca7be195a03d.png)

I know it is not a good practice

**Comment by nicolas-grekas** [comment]
The dump output can be inlined into any HTML page. No sure we should alter the rules set (or not) by the page.
