### ISSUE TITLE
Bad Exception - Call a command with array options from a controller that throws an exception 

### ISSUE THREAD

**Issue by mgiraud** [symfony/symfony#24128]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I've recently needed to call a command from a controller. The doc is : https://symfony.com/doc/current/console/command_in_controller.html

My command has an option named locales which can be an array : `InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY` so i've configured the ArrayInput that way
```php
$input = new ArrayInput(
            [
                'command' => 'test',
                'arg' => 'arg',
                '--locales' => ['en_GB'],
            ]);
```

If the execution of this commands, for some reason, throws an exception then the exception displayed on the debug page is : 
```
Error: Method Symfony\Component\Console\Input\ArrayInput::__toString() must not throw an exception, caught Symfony\Component\Debug\Exception\ContextErrorException: Warning: preg_match() expects parameter 2 to be string, array given
```
which doesn't give any details about the exception.

Here is a project to demonstrate the bug : [https://github.com/mgiraud/sf3-issue](https://github.com/mgiraud/sf3-issue)
Start a server and navigate to the root the page.

For information if the command does not throw an exception then everything works.

**Comment by chalasr** [comment]
This has been recently fixed, not released yet. 
Could you checkout https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Console/Input/ArrayInput.php and confirm the error doesn't occur anymore? Please close if it's ok, the patch will be part of the next maintenance releases.

**Comment by mgiraud** [comment]
Yep this patch fixes the issue

**Comment by papnoisanjeev** [comment]
@chalasr

facing same problem in symfony version 4.3.4
// Use Statements:

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$kernel = $this->get('kernel');
$application = new Application($kernel);
$application->setAutoExit(false);
$messages = 10;

$input = new ArrayInput(array(
                    'command' => 'oauth-server:client:create',
                    '--redirect-uri' => ['/'],
                    '--grant-type' => ["authorization_code", "password", "refresh_token"],
                    '--user-id' => $user,
    ));

$output = new BufferedOutput();
$application->run($input, $output);

Error: Method Symfony\Component\Console\Input\ArrayInput::__toString() must not throw an exception, caught Symfony\Component\Debug\Exception\ContextErrorException: Warning: preg_match() expects parameter 2 to be string, array given

**Comment by chalasr** [comment]
@papnoisanjeev I can't manage to reproduce with symfony/console 4.3.4.
If you can provide a reproducer that we can run (a small console application that includes the failing command), please open a new issue so that we can confirm the bug.
