### ISSUE TITLE
ide setting on path replace fails

### ISSUE THREAD

**Issue by AntonioCS** [symfony/symfony#24129]
| Q                | A
| ---------------- | -----
| RFC?             | yes
| Symfony version  | 3.3.8

Hey,

I am trying to use the [ide ](https://symfony.com/doc/current/reference/configuration/framework.html#ide)setting with paths replaced but I just can't get it to accept the paths and the documentation is not very clear.

So initially I had this:

`ide: "netbeans://open?file=%%f&line=%%l"`

But since this is giving me an incorrect path (running it on docker) I tried to do what the documentation tells me to do (guest_path>host_path) like so:

`ide: "netbeans://%f:%l&/application/>/host-path/&open?file=%%f&line=%%l"`

But this just leads to an error:

> 
>  (1/1) ParameterNotFoundException
> 
> You have requested a non-existent parameter "f:".

I tried a few variations of that string but I just can't get it to work. 
Can someone please point me in the right direction and also update the documentation to make this a bit clearer?

Thanks!

**Comment by ro0NL** [comment]
The value used in docs `'myide://%f:%l&/path/to/guest/>/path/to/host/&/foo/>/bar/&...'` needs to be escaped if used as a config value, as then `%...%` has special meaning. It doesnt mention that :)

So should be `ide: "netbeans://%%f:%%l&/application/>/host-path/&open?file=%%f&line=%%l"`

But you need to apply path mappings as last to preserve a valid URL, as it basically uses special query params for this.

So `ide: "netbeans://open?file=%%f&line=%%l&/application/>/host-path/"` works as expected.

**Comment by aik099** [comment]
@AntonioCS, just stumbled upon same issue. Turned out the value of `xdebug.file_link_format` in my `php.ini` file was always used instead of `framework.ide` config option. The documentation said it works the opposite. I've sent PR (see https://github.com/symfony/symfony-docs/pull/8405) to update the documentation.

**Comment by aik099** [comment]
@ro0NL , the documentation attempts to display, that several path prefixes can be specified, but it indeed confuses people. In reality it's ways one path prefix pair (guest to host).

**Comment by aik099** [comment]
@AntonioCS , I have this for `framework.ide` value and it works:

```
phpstorm://open?file=%%f&line=%%l&/home/alex/web/>/Volumes/web/
```

**Comment by AntonioCS** [comment]
@aik099 Yes that is what @ro0NL suggested and it's working great and yes that documentation is a bit tricky.
Thanks @ro0NL

**Comment by aik099** [comment]
@AntonioCS , @ro0NL , maybe you can send a PR to documentation to have 2 examples:

* one for common use, when there is only one path prefix
* advanced one if several path prefixes are used

?

**Comment by Apologiz** [comment]
**This works for PhpStorm in linux :)**
```
echo "APP_HOME=$(pwd)" >> .env
echo "ide: 'phpstorm://open?file=%%f&line=%%l&/var/www/myProject>%env(APP_HOME)%'" >> $(pwd)/config/packages/framework.yaml
```
