### ISSUE TITLE
[FrameworkBundle][DependencyInjection] Container debug command misses arguments

### ISSUE THREAD

**Issue by FabienSalles** [symfony/symfony#24138]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

I'm trying to use autowring in a project and I have an issue a little similar to this one #23998. My first problem was the part in "update 2" in [this same issue on stackoverflow](https://stackoverflow.com/a/45888416). I use a form type and my class isn't really abstract but It's just an example to show the problem : 

See below my old service declaration :

```php
class MyFormType extends AbstractType
{
    protected $mandatoryDay;
    protected $translator;
    
    public function __construct(TranslatorInterface $translator, $mandatoryDay)
    {
        $this->translator = $translator;
        $this->mandatoryDay = $mandatoryDay;
    }
}
```
Old service declaration : 

```xml
<service id="abstract_form_type"
    class="AppBundle\Form\MyFormType"
    abstract="true">
    <argument type="service" id="translator" />
    <argument>%my_parameter%</argument>
</service>
```

Result with debug:container abstract_form_type --show-arguments : 

```
Information for Service "abstract_form_type"
===========================================================

 ---------------- ------------------------------------------------ 
  Option           Value                                           
 ---------------- ------------------------------------------------ 
  Service ID       abstract_form_type               
  Class            AppBundle\Form\MyFormType  
  Tags             -                                               
  Public           yes                                             
  Synthetic        no                                              
  Lazy             no                                              
  Shared           yes                                             
  Abstract         yes                                             
  Autowired        no                                              
  Autoconfigured   no                                              
  Arguments        Service(translator)                             
                   2                                               
 ---------------- ------------------------------------------------ 
```

With the autowiring feature : 

```xml
<service id="abstract_form_type"
    class="AppBundle\Form\MyFormType"
    abstract="true"
    autowire="true">
    <argument key="$mandatoryDay">%my_parameter%</argument>
</service>
```

And the same symfony command I have this error : 

```
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                               
  Invalid constructor argument 2 for service "abstract_form_type": argument 1 must be defined before. Check your service definition. 
```

I removed the parameter and I found that the autowring does not work with a service define as abstract.

The new class : 

```php
class MyFormType extends AbstractType
{
    protected $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }
}
```

Declaration without abstract : 

```xml
<service id="abstract_form_type"
    class="AppBundle\Form\MyFormType"
    autowire="true">
</service>
```

Result with debug:container abstract_form_type --show-arguments : 

```
Information for Service "abstract_form_type"
===========================================================

 ---------------- ------------------------------------------------ 
  Option           Value                                           
 ---------------- ------------------------------------------------ 
  Service ID       abstract_form_type               
  Class            AppBundle\Form\MyFormType  
  Tags             -                                               
  Public           yes                                             
  Synthetic        no                                              
  Lazy             no                                              
  Shared           yes                                             
  Abstract         no                                              
  Autowired        yes                                             
  Autoconfigured   no                                              
  Arguments        Service(translator.data_collector)              
 ---------------- ------------------------------------------------
```

Declaration with abstract : 

```xml
<service id="abstract_form_type"
    class="AppBundle\Form\MyFormType"
    abstract="true"
    autowire="true">
</service>
```

Result : 

```
Information for Service "abstract_form_type"
===========================================================

 ---------------- ------------------------------------------------ 
  Option           Value                                           
 ---------------- ------------------------------------------------ 
  Service ID       abstract_form_type               
  Class            AppBundle\Form\MyFormType  
  Tags             -                                               
  Public           yes                                             
  Synthetic        no                                              
  Lazy             no                                              
  Shared           yes                                             
  Abstract         yes                                             
  Autowired        yes                                             
  Autoconfigured   no                                              
 ---------------- ------------------------------------------------
```

No parameter is found !

**Comment by chalasr** [comment]
I think this can be solved using bindings as of 3.4, dunno about 3.3. ping @nicolas-grekas

**Comment by FabienSalles** [comment]
Thanks for your reply @chalasr  :). 

Binding feature can actually avoid to use abstract services and inheritance of services (cf my other bug #24183) and solve my problems but there are still "conflicts" between them in my project. 

I found these bugs by converting all my services and migrate to Sf 3.3. Now that practically all my services use autowiring, I have less utility to create abstract services and use the inheritance but it would still be useful in some cases.

**Comment by nicolas-grekas** [comment]
Can't we make autowiring pass to wire abstract services?

**Comment by xabbuh** [comment]
@nicolas-grekas Would be a new feature then?

**Comment by nicolas-grekas** [comment]
Or bug fix really.

**Comment by stof** [comment]
The hard part about autowiring them is that the child service might have a different constructor signature, and so inherited arguments might end up being wrong.

**Comment by mschop** [comment]
@stof Why should this be any different to when autowiring interfaces or normal classes (wich seems to work in Symfony 4). For interfaces and classes (abstract or not) the constructor of the parent does not matter for autowiring.

It's strange that autowiring for normal classes work, but not for abstract classes. That does not make any sense to me and should be a bug.

So the bug seems to be still there in 4.5.1.

**Comment by stof** [comment]
@mschop service inheritance has nothing to do with PHP class inheritance. you could totally use a ChildDefinition with an unrelated class (but this is likely to be useless). and an abstract service could be a concrete class.

**Comment by stof** [comment]
the tricky stuff regarding autowiring there is the fact that anything you define in the parent service gets inherited by the child (that's the whole point of service inheritance). But if you let the autowiring define the arguments of the parent service, it means you don't know what gets inherited when writing the child service (and it might change over time). This might cause issues when defining your own extra arguments in the child.

**Comment by TomasVotruba** [comment]
Today this took me 30 minutes of life. Nasty bug :/

How do you overcome it?

**Comment by FabienSalles** [comment]
Hi,

I tried to create a reproducer for my issue reported 3 years ago => https://github.com/FabienSalles/symfony-reproducer/tree/reproducer-%2324138

There is : 
* a service `App\Service\TestWithoutParameter` without parent that is autowire by the [`resource` key](https://symfony.com/doc/current/service_container.html#importing-many-services-at-once-with-resource)
* an abstract service `App\Service\AbstractWithParameter` which is parent of a child service `App\Service\TestWithParameter` that are not autowire by the `resource` key (I don't know why)
* a command `./bin/console app:test` that show if `TestWithParameter` is autowire or not

My Observations :
* The command `./bin/console app:test` show that `AbstractWithParameter` is autowire only if we set manually `autowire: true` on the parent **or** the child service
* the command `debug:container App\Service\AbstractWithParameter --show-arguments` never display the autowire service (only the parameter set manually)

So : 
* I have no longer the error reported on the abstract service but I can have it on the child service if we don't specify manually `autowire: true`
* like @nicolas-grekas said before, we have a bug on the command `debug:container` (I think)
* we always have to specify `autowire: true` on the child and/or the parent `service` in order to use autowiring feature if we set a `parent` or have `abstract` set to true

**Comment by dompie** [comment]
If someone might hope this will work in Symfony5: It does not.
Also setter injection does not work on abstract services, Although docs suggests it should work: https://symfony.com/doc/current/service_container/parent_services.html

Autowire has no effect on abstract classes. See example project https://github.com/dompie/abstract-setters

**Comment by michaelKaefer** [comment]
I will try this.

**Comment by michaelKaefer** [comment]
@dompie For me it seems that your problems come from a misconfiguration which is not related to this issue. If you change `config/services.yaml` from:

```yaml
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
```
to:
```yaml
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/AbstractTest.php'
            - '../src/RealTest.php'
```
then your example works.

**Comment by michaelKaefer** [comment]
@FabienSalles As far as I can see there is no bug and the issue should be closed. Please correct me if I'm wrong.

#### 1. The original issue
This maybe is was a bug in earlier versions, I didn't check. But can this be reproduced in 4.4? It seems that abstract services can be autowired in 4.4 without any problem, or?

#### 2. The reproducer (https://github.com/FabienSalles/symfony-reproducer/tree/reproducer-%2324138)

In `config/services.yaml` there is:
```
services:
    App\Service\AbstractWithParameter:
        abstract: true
        arguments: ['retrieve the parameter']
    App\Service\TestWithParameter:
        parent: App\Service\AbstractWithParameter
```
Which results `autowired: false` for the abstract service and the concrete service.

The rest of your configuration does not change the fact above and is irrelevant (the `autowired: true` is not inherited which is correct I think):
```
services:
    App\:
        autowire: true
        autoconfigure: true
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

**Comment by FabienSalles** [comment]
I still can't see autowired parameters on the abstract service with the command `./bin/console debug:container "App\Service\AbstractWithParameter" --show-arguments` whereas I can see them on the parent service with `./bin/console debug:container "App\Service\TestWithParameter" --show-arguments` If `autowire` attribute is set to true on the abstract service.

Everything else seems to be normal for me now.
So the issue could stay opened or could be replaced by a new one focus on the command `debug:container` (if this is relevant and a bug for you).

I let you decide.

Anyway, the original issue was based on an old project on which I started to autowire my services. 
The problem appeared during the transition between my old services and my new ones. 
During this refactoring, I wasn't using all the potential of the autowiring feature. 
Now I no longer use abstract/parent service. I think this feature has lost a lot of its benefits and could be avoid.

**Comment by michaelKaefer** [comment]
Sorry, I misunderstood. So yes, the only remaining bug is that instead of:

```bash
./bin/console debug:container "App\Service\AbstractWithParameter" --show-arguments
  [...]
  Arguments        retrieve the parameter    
  [...]
```

it should rather be:

```bash
./bin/console debug:container "App\Service\AbstractWithParameter" --show-arguments
  [...]
  Arguments        retrieve the parameter        
                   Service(monolog.logger)  
  [...]
```
Thanks for clarifying.

**Comment by michaelKaefer** [comment]
I don't have the rights but the labels should be changed to: `Bug`, `FrameworkBundle`, `Help wanted` and the title to something like `[FrameworkBundle] Container debug command misses arguments`.

**Comment by michaelKaefer** [comment]
Sorry, I cannot solve this, maybe somebody else. Maybe it is enough to provide a note on the `bin/console debug:container` command if 1) a service name argument is given and 2) `--show-arguments` is set. Something like `NOTE If the service is abstract note that its autowired arguments are not listed`. This I could do but I got no other idea.

**Comment by jderusse** [comment]
please have a look to #39692
