### ISSUE TITLE
Remove anything related to security ACL

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24147]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

As Fabien said [in this comment](https://github.com/symfony/symfony/pull/23811#issuecomment-320520323) it's time to remove anything related to security ACLs from Symfony and move it to https://github.com/symfony/acl-bundle. Symfony 4.0 is our last chance to do this in several years.

**Comment by chalasr** [comment]
There is already a PR for that https://github.com/symfony/acl-bundle/pull/2

**Comment by chalasr** [comment]
See #24341
