### ISSUE TITLE
Remove @inheritdoc to decrease visual debt

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#24143]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | any

I want to propose the removal of `@inheritdoc` if used as _a docblock_.

Before

```php
/**
 * {@inheritdoc}
 */
public function some() { }
```

After

```php
public function some() { }
```

I think we can do it easily at once including lower branches, hence the RFC. But let me know if we dont do this anymore, but left the codebase as is. Then it can be closed i guess :)

Some background;
- https://dasprids.de/blog/2013/10/28/about-inheritdoc-and-other-useless-documentation/
- https://stackoverflow.com/questions/26550745/correct-syntax-for-inheritdoc-in-phpdocumentor

But more important;
> Currently some applications have DocBlocks containing just the {@inheritDoc} inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
>
> However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard @inheritDoc that will serve that purpose.

At https://github.com/phpDocumentor/phpDocumentor2/blob/master/docs/guides/inheritance.rst

**Comment by ro0NL** [comment]
> it does make clear that an element has been explicitly documented

Tend to not care.. docblocks are inherited by default (if not specified by the sub class). Tested in phpstorm and works perfect.

**Comment by iltar** [comment]
Honestly, I'd love to keep them in. It might not be the right way of doing so, but they imply that they are inheriting something.

**Comment by ricknox** [comment]
My vote is to keep the standard {@inheritdoc} tag. That tag is supported by phpDocumentor and widely used by within the core code of Symfony.

Methods whose docblock is expected to be identical to a parent class or interface may use `{@inheritdoc}` (note the wrapping **{}**) as the sole line of their docblock to indicate "use whatever the parent is". That is, this:

```php
/**
 * Implements \SomeClass::getValue().
 */
public function getValue() {
    return $this->value;
}
```

That will become:

```php
/**
  * {@inheritdoc}
  */
public function getValue() {
    return $this->value;
}
```

It is a huge pain when you change a namespace in an interface, then you have to go through and find every implementation and edit each method's docblock to reflect the change. Note that overridden methods are not always part of an interface.

**Comment by ro0NL** [comment]
Not sure i follow... 

> may use {@inheritdoc}

That's the point :) it's incorrect, yet works today. IIUC in this case it should be

```php
/**
 * @inheritdoc
 */
```

to serve `it does make clear that an element has been explicitly documented` purpose.

To me all visual debt really :)

**Comment by ro0NL** [comment]
In fact, i think the current approach is what you describe a "huge pain". If you make change in a namespace/interface/etc. a `@inheritdoc` may no longer apply; thus should be removed :)

**Comment by nicolas-grekas** [comment]
I think we added them for a purpose. If we remove them, ppl and reviewers will wonder why this method is undocumented - or will be forced to open another file to figure out they are in fact.

>  If you make change in a namespace/interface/etc

this doesn't apply, as we have a BC policy that makes this kind of changes extremely rare.

**Comment by ro0NL** [comment]
> this kind of changes extremely rare

Probably yes :) it's a conceptual problem.

>  If we remove them, ppl and reviewers will wonder why this method is undocumented - or will be forced to open another file to figure out they are in fact.

Keeping them is legit (IMHO poinless, but legit :)). Changing `{@inheritdoc}` to `@inheritdoc` is not worth i guess, not the goal of this PR at least :).

Feel free to reject & close.

**Comment by sstok** [comment]
> To me all visual debt really :)

![visual-dept-mf](https://user-images.githubusercontent.com/904790/30313003-26f56b4c-979c-11e7-918d-ab9ed80e01df.jpg)
:trollface: 

Personally I stopped using inheritdoc for classes that are considered internal or to obvious that they don't require documenting. But it does serve a purpose. And FYI PSR-5 is not final yet, the php-cs-fixer actually changes this in-line which could be considered wrong for this specific purpose.
