### ISSUE TITLE
[RFC] Type parser/guesser/checker

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#24140]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.x

[Demo repository](https://github.com/iluuu1994/symfony-type-component)

I've written a type parser, guesser and checker for a private project. It allows you to easily verify that user input has a certain type. It works for all basic all types:

- Primitive types
- Mixed types
- Null
- Arrays
- Classes
- Interfaces
- Union types
- Intersection types

Things that I might implement in the future:

- [Shapes](https://docs.hhvm.com/hack/shapes/introduction)

One use case for this could be Symfony's [OptionsResolver::setAllowedTypes](https://symfony.com/doc/current/components/options_resolver.html#type-validation) functionality. Currently a lot of validation has to be done using closures. It might also be interesting for testing libraries (more expressive type checking) or static analysis tools.

I'm just checking to see if this is something you guys would be interested in. If so I'm down to making it "Symfony ready".

Here's how it works:

# Setup

```php
$parser = new TypeParser();
$checker = new TypeChecker();
$guesser = new TypeGuesser($checker);
```

# Type parser

The type parser parses a string representation of a type into an AST. The syntax will feel familiar to everybody who has used PHPDoc types or type hints.

```php
$type = $parser->parse('int | ?float');
```

```php
UnionType {
  +lhs: IntType {
  +rhs: UnionType {
    +lhs: FloatType
    +rhs: NullType
  }
}
```

# Type checker

The method `isSubtypeOf` checks if type `a` is a subtype of type `b`. There is also a method for checking super types or type equality.

```php
$result = $checker->isSubtypeOf(
    $parser->parse('(?int)[]'),
    $parser->parse('(int | string)[]')
);
```

```php
false
```

# Type guesser

The type guesser will infer the type of any instance. This means you can pass it to the type comparators provided by the type checker.

```php
$result = $checker->isSubtypeOf(
    $guesser->guess([1, 2.5, 3, 4, 5.5, ['foo', 'bar']]),
    $parser->parse('(int | float | string[])[]')
);
```

```php
true
```

**Comment by ro0NL** [comment]
Looks good from a component pov :+1: is there a repo to star? If i have a usecase id use it.

Unless i use `PhpDocExtractor` from SF... does it fit that? I.e. could this replace the `phpDocumentor\` deps?

**Comment by iluuu1994** [comment]
@ro0NL No, right now it's in a private repository. I'm not too familiar with `PhpDocExtractor` but I'd assume it only parses the PHPDoc blocks and not the type itself? I'm not sure if I understand your question 😅

**Comment by ro0NL** [comment]
@iluuu1994  also not too familiar with it :) just thought conceptually PhpDocExtractor could use your type parser, but now looking at it i think this needs to stay tied to `phpDocumentor` lib.

>  Is it phpdoc compliant?

see https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md

**Comment by iluuu1994** [comment]
@ro0NL More or less, at least:

```
type-expression  = type *("|" type)
type             = class-name / keyword / array
array            = (type / array-expression) "[]" / generic
array-expression = "(" type-expression ")"
generic          = collection-type "<" [type-expression "," *SP] type-expression ">"
collection-type  = class-name / "array"
class-name       = ["\"] label *("\" label)
label            = (ALPHA / %x7F-FF) *(ALPHA / DIGIT / %x7F-FF)
keyword          = "array" / "bool" / "callable" / "false" / "float" / "int" / "mixed" / "null" / "object" /
keyword          = "resource" / "self" / "static" / "string" / "true" / "void" / "$this"
```

I do not yet support generics (I'm not sure anyone supports those, never seen them in a PHPDoc block). Some of the keywords are also missing, especially dynamic ones as `self`, `static` or `$this` as those depend on the context of the code. Other than that yeah, the definition is pretty much the same.

**Comment by iluuu1994** [comment]
I finally got around creating a [demo repository](https://github.com/iluuu1994/symfony-type-component).  
After thinking about it I see two potential use cases for this in the Symfony repository:

1. Guess the types of non-doctrine entities via annotations
2. Improve the `OptionsResolver::setAllowedTypes` method

**Comment by sroze** [comment]
The "parser" and "guesser" aspects are already covered by the PropertyInfo component isn't it?

**Comment by iluuu1994** [comment]
@sroze You're right. The parser is already provided by the [phpDocumentor/TypeResolver](https://github.com/phpDocumentor/TypeResolver) library. I wasn't aware of that. 🤦‍♂️ It even supports contexts to support pseudo types and non-fqn types which I was planning on doing. Oh well 😂

The guesser takes an actual PHP value and determines it's type, including array nesting:

```php
$guesser->guess([1, null, 3, 4, 5, 'foo']);

// > ArrayType {
// >   +inner: UnionType {
// >     +lhs: IntType {
// >     +rhs: UnionType {
// >       +lhs: NullType
// >       +rhs: StringType
// >     }
// >   }
// > }
```

The problem now is that it generates types using my own AST. Now I'd have to reimplement the guesser and the checker on top of the [phpDocumentor/TypeResolver](https://github.com/phpDocumentor/TypeResolver) library.

I'll think about that. Until then I'll close this issue.
