### ISSUE TITLE
[UniqueEntityValidator] use __toString method to feed {{value}} in constraint message

### ISSUE THREAD

**Issue by CKESSLER** [symfony/symfony#24150]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

In Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator.php, according to documentation (https://symfony.com/doc/current/reference/constraints/UniqueEntity.html#message) it is possible to use the __toString method when used field is an object.

However the formatWithIdentifiers method never return the __toString method result.

Is it possible to add this feature?

**Comment by iltar** [comment]
Usage of `__toString()` should be heavily discouraged imo.

**Comment by xabbuh** [comment]
This was fixed in #20287 and #28252.
