### ISSUE TITLE
[Intl] Locale::getFallback does not split on dash

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#24154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.8 (but all others I guess, did not check yet)

---

Hello.

I just hit an issue with the country type and the Intl component.

According to PHP, the first parameter of [Locale::setDefault](http://php.net/manual/en/locale.setdefault.php)
should be a BCP 47 compliant tag.

So according to the [RFC](https://tools.ietf.org/html/bcp47), it should be something like `fr` or `fr-FR`.
In my case it's `fr-FR`.

Now the CountryType use the `Locale::getDefault`. Refs:

* https://github.com/symfony/symfony/blob/v3.3.8/src/Symfony/Component/Form/Extension/Core/Type/CountryType.php#L78
* ...
* https://github.com/symfony/symfony/blob/v3.3.8/src/Symfony/Component/Intl/Data/Provider/RegionDataProvider.php#L67

Then symfony will use will default locale to find the best locale by ["fallbacking"](https://github.com/symfony/symfony/blob/v3.3.8/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php#L148-L149) on "wider" locale (`fr_FR` -> `fr`)

And [here](https://github.com/symfony/symfony/blob/v3.3.8/src/Symfony/Component/Intl/Locale.php#L70)
there is something wrong IMHO. Symfony only try to split the local with an underscore (`_`) and not
with a dash (`-`). But the RFC states the locale should use an underscore and not a dash.

---

Some facts to take in consideration:

* The [Translator component](https://symfony.com/doc/current/components/translation/usage.html#content_wrapper) use another RFC for the format of the locale. (`fr_FR`);
* The [Validator component](https://symfony.com/doc/current/reference/constraints/Locale.html) use another RFC for the format of the locale. (`fr_FR`);
* It's really weird I'm the first one to hit this issue => Did I miss something ?

---

What I suggest: We could update the `Locale::getFallback` method to support splitting on `-`.

WDYT? I can make the PR if this RFC is accepted.

---

I [pushed a reproducer](https://github.com/lyrixx/symfony-standard/tree/sf-local-lowdash)

**Comment by fabpot** [comment]
For reference, see discussion on #2468 as well

**Comment by lyrixx** [comment]
We could use `locale_parse` instead of our local implementation. We will cover more cases. More over I don't see pitfall here.
`

**Comment by fabpot** [comment]
PR more than welcome :)

**Comment by thejahweh** [comment]
Is it possible to get this change into Symfony 4?
It would require 2 more lines at `\Symfony\Component\Translation\Translator::computeFallbackLocales`.

**Comment by xabbuh** [comment]
@thejahweh I can see the change in Symfony 4: https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Intl/Locale.php#L70
