### ISSUE TITLE
[HttpFundation] Add an XmlResponse

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#24187]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| BC Break report? | yno

What about an `XmlResponse` like the `JsonResponse`?

I'm writing a controller to render a sitemap and having such object is really helpful.

What do you think about?

**Example of use**

        $queryBuilder = $this->getDoctrine()->getManager()->getRepository('AppBundle:Store')->getSitemapQueryBuilder();

        $pager = new Pagerfanta(new DoctrineORMAdapter($queryBuilder, false));
        $pager->setCurrentPage($request->query->get('page', 1));
        $pager->setMaxPerPage($request->query->get('per_page', 10));

        $stores = [];
        /** @var Store $store */
        foreach ($pager as $store) {
            $stores[] = [
                'loc'        => $router->generate('store_view', ['domain_host' => $store->getDomain()->getHost()], RouterInterface::ABSOLUTE_URL),
                'lastmod'    => (new \DateTime())->format('Y-m-d'),
                'changefreq' => 'daily',
                'priority'   => '0.1',
            ];
        }

        $sitemap = [
            '@xmlns' => 'http://www.sitemaps.org/schemas/sitemap/0.9',
            'url'    => $stores,
        ];

        return new XmlResponse($sitemap, 'urlset', false, ['xml_format_output' => 'formatOutput', 'xml_encoding' => 'UTF-8']);

**Comment by VolCh** [comment]
There is no one standard way to convert "2D" PHP objects/arrays to "3D" (at least) XML document. Or may be I am so old-fashioned and nobody (except me) use xml attributes, namespaces and so on?

**Comment by Aerendir** [comment]
No, you are not the only one for sure.

I created this object for a really simple use case: serve an XML site map.

I'm going to update the opening comment to illustrate deeper how I'm using this `XmlResponse` object in my use case.

For all other use case, it's obvious we should speak of them here... Maybe at the end we will decide to use the `XmlResponse` object for simpler scenarios leaving the more complex ones to a more tailored solution based on the specific use case.

**Comment by javiereguiluz** [comment]
@Aerendir when you created this issue I wondered what would be the use cases for this XmlResponse (because I've never need anything like this and we've never received this petition before).

Now you've added your use case: site maps. However, if you refer to Google/Schema.org XML sitemaps, I find it strange to define a controller for that. It's common to create a console command that generates the XML files in the background (e.g. when the server load is low) and let the web server serve them.

**Comment by Aerendir** [comment]
@javiereguiluz Yes, maybe, but I'm using Heroku that doesn't allow write operations.

For sure I can generate the sitemap and then upload it to AWS, but this was the fastest way I had and given it is not so big the overhead of generating it on the fly is really small.

In the future for sure I will generate it asynchronously, but for the moment I want to generate it on the fly as this is the fastest way to accomplish the task.

**Comment by chapterjason** [comment]
Are you already thought about that the [PHP XML Dom Manipulation](http://php.net/manual/en/domdocument.savexml.php)? For a simple use case like a sitemap generator it would be a simple class who could handle this. You could simply load the router from the container (dont know if public?) If not create a service and inject it, after that you can get all routes, check permission of publicity and generate the sitemap.

```
return new Response($sitemap->saveXML());
```

**Comment by ro0NL** [comment]
:+1: for `return new XmlResponse($domDocOrSimpleXmlMaybe)` and be done.

**Comment by MacDada** [comment]
Just use Response and some kind of (XML) serializer (Symfony/JMS) – they are ready, proven, specialized tool, just for the task.

**Comment by javiereguiluz** [comment]
Closing because the related pull request (#24188) was ultimately rejected.
