### ISSUE TITLE
Form fields do not contain 'data_collector/passed_options' attribute in dev env but do in prod env.

### ISSUE THREAD

**Issue by MyDigitalLife** [symfony/symfony#24181]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

I have a form where I want to update some attributes of a few fields. I do this with the following code:
```
$fieldConfig = $builder->get($fieldName)->getFormConfig();
$attributes = $fieldConfig->getAttribute('data_collector/passed_options');
var_dump($attributes);
```
The problem i am having here is that the $attributes array is `null` when running this code with env prod but works fine when running it in env dev. It should have a field `data_collector/passed_options`. So it looks like there is a difference in the values added to the attributes field in the dev and prod envs. I can reproduce this on our production servers and my personal development server. I can also reproduce it in a new project with the following code in a form type:
```
$builder->add('test', null, ['disabled' => false]);
$fieldConfig = $builder->get('test')->getFormConfig();
var_dump($fieldConfig->getAttributes());
```

This looks like a bug to me. Or am i doing something wrong?

**Comment by xabbuh** [comment]
The data collectors mainly useful when the profiler is enabled (which by default only is the case in the `dev` and `test` environments). That's why the related data collector classes from the Form component are only registered when the profiler is enabled.

So no there's no bug here.
