### ISSUE TITLE
Autoconfigure in default configuration isn't possible when we have an inheritance of services

### ISSUE THREAD

**Issue by FabienSalles** [symfony/symfony#24183]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3.8

I didn't find any issue for this so I create this one. After I converted all my services with the autowiring feature I tried to use autoconfigure by default and I blocked when I had a service that inherite an other one.

Initially I had this : 

```xml
<services>
        <defaults autowire="true" />

        <service id="parent_form_type"
             class="AppBundle\Form\MyParentFormType">
            <argument key="$parameter">%my_parameter%</argument>
       </service>

        <service id="child_form_type"
            class="AppBundle\Form\MyChildFormType"
            parent="parent_form_type"
            autowire="true">
            <tag name="form.type" />
        </service>
</services>
``` 

I removed the `abstract` attribute in my parent service in order to avoid [this issue](https://github.com/symfony/symfony/issues/24138) and I had to add the `autowire="true"` in my child service to avoid this one : 

```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                
  Attribute "autowire" on service "child_form_type" cannot be inherited from "defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in app/config/services/form.xml (which is being imported from "app/config/services").
```

So I changed my `default` tag  : 
```xml
<defaults autowire="true" autoconfigure="true"/>
```

And I had this error (same that before for autowiring) :

```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                    
  Attribute "autoconfigure" on service "child_form_type" cannot be inherited from "defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in app/config/services/form.xml (which is being imported from "app/config/services"). 
``` 

So I did the same thing for autowiring and set it directly in my child service : 

```xml
<service id="child_form_type"
    class="AppBundle\Form\MyChildFormType"
    parent="parent_form_type"
    autowire="true"
    autoconfigure="true">
</service>
```

And I had this error : 

```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                     
  The service "child_form_type" cannot have a "parent" and also have "autoconfigure". Try setting autoconfigure="false" for the service in app/config/services/form.xml (which is being imported from "app/config/services").
```

I tried to set autoconfigure to false like the error said but I got the initial error again : 

```xml
<service id="child_form_type"
    class="AppBundle\Form\MyChildFormType"
    parent="parent_form_type"
    autowire="true"
    autoconfigure="false">
</service>
```

```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                    
  Attribute "autoconfigure" on service "child_form_type" cannot be inherited from "defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in app/config/services/form.xml (which is being imported from "app/config/services"). 
```

I think, this inheritance problem shouldn't occurs when we directly set the option in the service.

**Comment by xabbuh** [comment]
@nicolas-grekas Can you have a look here?

**Comment by stof** [comment]
The last error indeed looks wrong.

**Comment by nicolas-grekas** [comment]
I just tried reproducing the last error using your examples, but I didn't manage to make it fail.
Can you please provide a reproducer that I could run locally?

**Comment by FabienSalles** [comment]
I also tried to reproduce it again with the symfony-standard repository and after with my old project but it works fine now. May be it was a caching issue.

Sorry for the noise and for taking your time. I close the issue.
