### ISSUE TITLE
[Validator] Wrong error handling when type differs

### ISSUE THREAD

**Issue by ninsuo** [symfony/symfony#24196]
Q | A
-- | --
Bug report? | yes
Feature request? | no
BC Break report? | no

Hello the community,

A hunter from our Bug Bounty Program reported that when an input is manually changed from text to an array on the form payload, he receives a 500 instead of a proper violation.

For example, if `email=bob@lamouche.com` is changed to `email[]=bob@lamouche.com` on an email field having an EmailValidator, we end up with [this exception thrown](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L50 ):

https://github.com/symfony/symfony/blob/3e4f97852ddb17b740daaefa6b6df33d462ade59/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L49-L51

This is obvious, and not really an issue as field was manually changed, but this might create false positives on error logs / monitoring if abused. Wouldn't it be cleaner to add a violation to the field, simply telling that the value is not an email?

**Comment by xabbuh** [comment]
You are right about this. However, we already have some tickets (see for example #14943, #23995) that cover this. So I am closing here as a duplicate.

**Comment by ninsuo** [comment]
👍 thanks

**Comment by ninsuo** [comment]
For those who look for a quick solution, you can create a Kernel Exception Listener like this one:

```php
<?php

namespace AppBundle\EventListener;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
use Symfony\Component\Security\Core\Authentication\Token\AnonymousToken;
use Symfony\Component\Validator\Exception\UnexpectedTypeException;

class KernelExceptionListener implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        // When sending invalid data types to form fields, validation throws
        // exceptions, leading to 500s which is a small security issue because
        // someone could repeat to send invalid data to create noise on our
        // dashboards, and potentially do something worse during the storm.
        if ($event->getException() instanceof UnexpectedTypeException) {
            $response = new Response();
            $response->setStatusCode(400);
            $event->setResponse($response);
        }
}
```

And the DI configuration:

```xml
        <service id="app.listener.kernel_exception" class="AppBundle\EventListener\KernelExceptionListener">
            <tag name="kernel.event_listener" event="kernel.exception" method="onKernelException" />
            <call method="setContainer">
                <argument type="service" id="service_container" />
            </call>
        </service>
```
