### ISSUE TITLE
Null character breaks DomCrawler

### ISSUE THREAD

**Issue by JohnBakery** [symfony/symfony#24194]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3?

I'm not exactly sure if this is a bug or an encoding issue on my end, but someone on IRC suggested I post this here. I'm running DomCrawler component, so not exactly sure what version of Symfony it uses.

The issue arises when I try to parse the following page `https://play.google.com/store/apps/details?id=com.balintinfotech.sinhalesekeyboardfree&hl=en`.

That page has a comment in Sinhalese, that has a NULL character in it. When I parse that site through DomCrawler, it doesn't see some of the tags

You can test it with the following code

    $autoloader = require __DIR__.'\vendor\autoload.php';
    use Symfony\Component\DomCrawler\Crawler;

    $app_id = 'com.balintinfotech.sinhalesekeyboardfree';

    $response = file_get_contents('https://play.google.com/store/apps/details?hl=en&id='.$app_id);
    $crawler = new Crawler($response);
    echo $crawler->filter('div[itemprop="datePublished"]')->text();

**Comment by xabbuh** [comment]
Can you confirm that this is the same as described in #20323?

**Comment by JohnBakery** [comment]
Yup, the same issue. Closing.
