### ISSUE TITLE
[Validator] UUID Validator only validates variant 2 UUIDs

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24209]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | any

The `UuidValidator` only validates Variant 2 UUIDs, but this isnt mentioned anywhere. When you want to use it to validate UUIDs from an ActiveDirectory for example, one must use non-strict mode.

the RFC does not disallow non variant 2 UUIDs. see also https://stackoverflow.com/a/6953207

What can be done?
- Rename the validator to indicate only Variant 2 UUIDs are validated
- Explicitly document that only variant 2 UUIDs are supported
- Include all variants in strict mode validation

**Comment by ro0NL** [comment]
Do you have an non variant 2 example that fails with strict=false? I.e. whats the bug?

```php
/**
* Strict mode only allows UUIDs that meet the formal definition and formatting per RFC 4122.
*
* Set this to `false` to allow legacy formats with different dash positioning or wrapping characters
*
* @var bool
*/
public $strict = true;
```

To me that looks compliant with the stackoverflow answer =/ I.e. i think `Include all variants in strict mode validation` is the current behavior (or it should be).

**Comment by backbone87** [comment]
Non-strict mode accepts every 128 bit sequence.

The point is, that non variant 2 (not to be confused with version 2) uuids are strictly valid according to the RFC, because it does not prohibit non variant 2 UUIDs, but only declares a specific format for variant 2.

Dash positioning and wrapping characters are only about the string representation, but not about the spec of the bit sequence.

basically every microsoft guid does not pass strict mode validation, even when its in standard string representation. Here is one: `d7bb0bc1-0b24-944c-bea2-ef7da43e5c5c`

**Comment by ro0NL** [comment]
You're right. I misread it.

**Comment by ro0NL** [comment]
@backbone87 think i got this :) could you try #24230
