### ISSUE TITLE
Symfony 3.3 CLI Database Update Error

### ISSUE THREAD

**Issue by MKhalidJunaid** [symfony/symfony#24213]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.10-DEV

When i try to generate entity from database using following commands it breaks
Reference https://symfony.com/doc/current/doctrine/reverse_engineering.html

> /php70 bin/console doctrine:mapping:import --force AppBundle
> /php70 bin/console doctrine:mapping:import --force AppBundle annotation
> /php70 bin/console doctrine:mapping:import --force AppBundle xml
## Error Details ##

                                                                                   
>  [Doctrine\DBAL\Exception\ConnectionException]                                     
>  An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory  
>  [Doctrine\DBAL\Driver\PDOException]               
>  SQLSTATE[HY000] [2002] No such file or directory  
>  [PDOException]                                    
>  SQLSTATE[HY000] [2002] No such file or directory  
> doctrine:mapping:import [--em [EM]] [--shard SHARD] [--filter FILTER] [--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <bundle> [<mapping-type>]

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

By the way, the code that deals with the mapping import is not part of Symfony, but is provided by the Doctrine project.
