### ISSUE TITLE
[Console] Multiple line breaks "\n\n" are ignored on exception message.

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#24212]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7 (tested in 3.4)

![newline-bug](https://user-images.githubusercontent.com/2028198/30466097-67e234c8-99a9-11e7-9170-50fed5f658ce.png)

The raw message clearly shows two line breaks between sentences, however the final message ignore it. No matter how many line breaks you put, only one is taken into account.

This should be the expected result based on the raw message:
![newlines-bug-ok](https://user-images.githubusercontent.com/2028198/30466186-01338438-99aa-11e7-9266-b282f7eaded5.png)

The related code is too old ([`a52f41d`](https://github.com/symfony/symfony/commit/a52f41d4142e882ba628832d9a2666b3e62d6e65#diff-38eebdda7d6ebfcb7405b91167f05c9cR1157), [`4a4fea7`](https://github.com/symfony/symfony/commit/4a4fea742bbde8b99233ee990e159a1a529cbf65#diff-38eebdda7d6ebfcb7405b91167f05c9cR1164)):
https://github.com/symfony/symfony/blob/5bf241aa8e7bf8646e54b1c19461d8ae20671631/src/Symfony/Component/Console/Application.php#L1136-L1138

So I'm not sure (implications? real cause?) if removing the `if` statement (https://3v4l.org/XcI6Q) is the right solution even though it worked for me. Someone could validate this?

**Comment by ro0NL** [comment]
Removing it creates a different result compared to `str_split` (first case), and even loses a part of the origin string. So im not sure removing here is OK. https://3v4l.org/QV2t8 (2.7 based).

**Comment by yceruto** [comment]
@ro0NL I meant, keeping `$lines[] = count($lines) ? str_pad($line, $width) : $line;` :)

**Comment by yceruto** [comment]
https://3v4l.org/XcI6Q
