### ISSUE TITLE
String validators (email, regex etc) throw exceptions when validating an array

### ISSUE THREAD

**Issue by ianmclaughlin** [symfony/symfony#24214]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

I am getting traffic from a web scanner who is sending crafted payloads to my form handlers. In particular, I'm getting arrays being sent to fields with email and regex validators, and my logs are being filled up with 
`UnexpectedTypeException: “Expected argument of type “string”, “array” given”`

Instead of throwing a type exception, the validators should gracefully return a violation

**Comment by ro0NL** [comment]
Probably related to #14943 & #23995

**Comment by ianmclaughlin** [comment]
closing as duplicate of #14943
