### ISSUE TITLE
[Phpstorm Plugin Support] Remote Call

### ISSUE THREAD

**Issue by pquerner** [symfony/symfony#24218]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

There is a PHPStorm plugin called "Remote call" [1] which can be used to open files in your IDE if you click on a special hyperlink. This could be used for example in the Symfony Profiler section, where you can check your templates used on your current page.
A hyperlink on that twig template can be used to open the file automatically in your IDE.

A popular Magento1 module [2] uses this plugin to help you to open the templates in your IDE faster.

There is also a bundle for this [3], but its outdated according to their composer.json. 

[1] https://plugins.jetbrains.com/plugin/6027-remote-call
[2] https://github.com/AOEpeople/Aoe_TemplateHints
[3] https://github.com/darles/RemoteCallBundle

**Comment by ro0NL** [comment]
Just wondering.. cant you already do achieve this with the `framework.ide` setting? Assuming the plugin is enabled on phpstorm side.

**Comment by pquerner** [comment]
I dont know what you mean. The Hyperlink must be specially crafted (see docs on the Remote Call plugin for more information) so the IDE (with enabled plugin) can intercept it.

**Comment by ro0NL** [comment]
https://symfony.com/doc/current/reference/configuration/framework.html#ide :)

**Comment by pquerner** [comment]
"Symfony turns file paths seen in variable dumps and exception messages"

No words about the profiler.

**Comment by ro0NL** [comment]
Dumps in profiler benefit the same feature. Twig bridge provides `file_link` for specialized links, i.e. the dispatched controller in WDT is linked that way.

> This could be used for example in the Symfony Profiler section, where you can check your templates used on your current page.

IIUC you propose a new feature where for each twig template rendered, we'd somewhere render a link _to_ it. Right? That's souds nice and can be done in the twig panel perhaps :+1:

**Comment by pquerner** [comment]
I mean, in the Profiler Template section you can see what templates were parsed (and the name of the template). I propose that these templates names also get a special crafted hyperlink onto them, so I can be lazy and click on that hyperlink to have my IDE open the file for me.

I guess that can be easily forged with your ```file_link``` function, *if* twig knows more than the file name (ie its path on the file system).

**Comment by ro0NL** [comment]
See https://github.com/symfony/symfony/pull/24236

**Comment by pquerner** [comment]
I have found a bug with the proposed change from @ro0NL . It has been reported here https://github.com/symfony/symfony/pull/24236#issuecomment-332780218

@fabpot

**Comment by nicolas-grekas** [comment]
@pquerner please open a new issue: comments on closed PR/issues can easily get lost.

**Comment by pquerner** [comment]
@nicolas-grekas I have created a new issue here https://github.com/symfony/symfony/issues/24355
I hope its fine how I created it, since I wasnt sure how to report stuff which is still in a ```-dev``` branch.
