### ISSUE TITLE
[Ldap][Security] LdapBindAuthenticationProvider does not bind before search query

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24210]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | any

When using the `LdapBindAuthenticationProvider` without the `LdapUserProvider` while using a `queryString` to search for the users DN, the auth provider executes an LDAP search without binding first.
see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Provider/LdapBindAuthenticationProvider.php#L96

this error does not occur when used in combination with the `LdapUserProvider`, because this one is binding to a search user before.

**Comment by backbone87** [comment]
the only good solution that comes to my mind, is requiring a search user and password for the `LdapBindAuthenticationProvider` when a `queryString` is to be used and bind to that user before querying.

**Comment by acasademont** [comment]
Yes, a search user and search password should be provided when using the queryString option, and perform a first bind for the search. Then, if the query if successful, bind again with the provided form credentials.

**Comment by diabl0** [comment]
This bug screwed me whole day as I was using LDAP for auth, and custom user provider with roles from database.
Currently implementing own auth provider, but this need be fixed, or at least documented to save time for others.
