### ISSUE TITLE
Lock component documentation missing

### ISSUE THREAD

**Issue by FallDi** [symfony/symfony#24221]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Documentation of component https://github.com/symfony/lock is missing.
File `https://github.com/symfony/lock/edit/master/README.md` file contains bad link https://symfony.com/doc/master/components/lock.html

**Comment by ro0NL** [comment]
Work in progress? https://github.com/symfony/symfony-docs/pull/7866
