### ISSUE TITLE
[RFC] Deprecate 'views' directory in favor of 'templates' everywhere

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#24227]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4, 4.0

The proposal, according to the new directory structure for `3.4/4.0` applications, deprecate:
 * `AcmeBundle/Resources/views` in favor of `AcmeBundle/Resources/templates`. 
 * `%kernel.root_dir%/Resources/views` in favor of `twig.default_path`.
 * `%kernel.root_dir%/Resources/<BundleName>/views` in favor of `templates/bundles/<BundleName>`.

the last two are ready, but we have not done the deprecation notice in `3.4` if the old path exists and it is not added manually to the `twig.paths` list.

It would eliminate future confusion about two different names with the same concept within the Symfony world. Same modus operadi, deprecate in `3.4` and remove in `4.0`.

What do you think?

**Comment by fabpot** [comment]
I would not change that. New projects will use `templates/` at the project's root. So, the paths you mentioned are somewhat "legacy" for end users. Now, for bundles, I don't think this is worth it as there is not really an easy upgrade path (one can create a symlink but that's not worth it if you ask me).

**Comment by yceruto** [comment]
> I would not change that. New projects will use templates/ at the project's root. So, the paths you mentioned are somewhat "legacy" for end users.

:+1: 

> Now, for bundles, ...

Same as new projects, new bundle will use `Bundle/Resources/templates`.

> ... I don't think this is worth it as there is not really an easy upgrade path (one can create a symlink but that's not worth it if you ask me).

For existing ones, the migration path should be quite easy IMHHO just need to move all the templates from `views/` to `templates/` directory and since the Twig's namespace remains the same it wouldn't affect the template load, but I'm probably missing something when you say `there is not really an easy upgrade path`.

**Comment by yceruto** [comment]
Thus would be for bundles:
![bundles-templates](https://user-images.githubusercontent.com/2028198/30507127-741b2e74-9a4f-11e7-941a-82ecb329ae99.png)
I tried it for `TwigBundle` and it worked fine (without do anything more that rename the `views` directory) just adding:
```php
            if (file_exists($dir = $bundle['path'].'/Resources/templates')) {
                $bundleHierarchy[$name]['paths'][] = $dir;
            }
            $container->addResource(new FileExistenceResource($dir));
```
to `TwigExtension`.

**Comment by fabpot** [comment]
You forget that a bundle must be able to support several versions of Symfony. So, it must work with `views` AND `templates`, not one or the other.

**Comment by yceruto** [comment]
Sure, I forgot about that, nevermind.
