### ISSUE TITLE
How to access the parameters in sapui5  which are passed in request body of URL 

### ISSUE THREAD

**Issue by sajjanhubale** [symfony/symfony#24233]
I am setting up duo two-factor authentication in a sapui5 web application and node.js . I am new to sapui5 so this may be a simple answer.

I have everything set up except I need to verify the response by doing the following: "After the user authenticates (e.g. via phone call, SMS passcode, etc.) the IFRAME will generate a signed response called sig_response and POST it back to the post_action URL. Your server-side code should then call verify_response() to verify that the signed response is legitimate."

sig_response value will be posted to below post_action url

 **Duo.init({ 
'host':'api-shfjsdfhs.duosecurity.com',
 'sig_request':sig_request, 
'post_action':'http://localhost:8080/DuoNext/index.html#/Final', });**

How can i access the sig_response parameter value in Final page. Below is highlighted in example using PHP $resp = Duo\Web::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);

Duo Web: https://duo.com/docs/duoweb

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
