### ISSUE TITLE
[RFC] Rename twig.default_path to twig.templates_dir

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24235]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

I was looking at the nice feature contributed by @yceruto in 76ccce7464b6421e2b4dbc10c5f9c941a76bf5b7 and I wondered if `twig.default_path` is the best name for this new option.

If you ask someone what could `twig.default_path` mean ... they will probably say: the path to the default Twig executable. If this option defines the directory where the Twig templates are stored, could we rename it to `twig.templates_dir`?

**Comment by Tobion** [comment]
I agree it's not that clear. But at least it's consistent with `twig.paths` config. `twig.paths` would probably be better named `twig.template_namespaces` btw.

**Comment by nicolas-grekas** [comment]
We don't have easy migration paths for renaming parameters. For this reason, I'm "-0" here.

**Comment by javiereguiluz** [comment]
Let's close because this was intended to be fixed before 3.4/4.0 release and that cannot happen now. Cheers!
