### ISSUE TITLE
[Form] Choice value get trimmed and throw Invalid value error

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#24247]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 2.8 (think newer versions also affected)

When you have a choice which has whitespaces in its values:

```php
$options['choices'] = [
    'test with whitespace ' => 'test with whitespace ',
]
```

The `TrimListener` will trim the whitespace but the Validator will throw Invalid value `test with whitespace ` submitted.

**Possible Solutions**

When the option `trim` is true the values of the choice should also been trimmed.

**Comment by ro0NL** [comment]
In your case id say `trim=false`. For using leading/trailing spaces in choice value, you dont expect a trimmed value.

**Comment by alexander-schranz** [comment]
@ro0NL trim is true by default so the value get trimmed by the TrimListener but as the choices values are not trimmed it throws an error. My expected behaviour is when trim is true the values should also been trimmed so it don't throw an error. Not sure where the values are validated for the choices form type.

**Comment by ro0NL** [comment]
> when trim is true the values should also been trimmed

I tend to disagree, this is just an open door for side effects. IMHO form should not make assumptions here.

**Comment by alexander-schranz** [comment]
@ro0NL but else you will never be able to submit that form. For me the ChoiceType should default set `trim` to `false` so this could not happen. This would be a BC Break as none trimmed values could currently not been submitted also trimming the value is no BC Break as this didnt work before because of the TrimListener.

**Comment by ro0NL** [comment]
> but else you will never be able to submit that form

Correct, because the submitted value is not a valid choice.

How would `['a', 'a    ']` work? Choices are passed by the user, and likely are domain values. What's your usecase? Why cant you set trimmed choices (the expected ones)? Why not trim=false if you actually have choices with leading/trailing spaces?

Technically we can detect choice values with spaces and imply a default trim value. But i prefer explicitness here.
