### ISSUE TITLE
[Cache] TagAwareAdapter + Redis does not invalidate properly all the time

### ISSUE THREAD

**Issue by mbek** [symfony/symfony#24240]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.4

### Problem description 
We are experiencing an issue with Redis + TagAwareAdapter where in _some_ cases the cache does not invalidate. In regular situations the cache is cleared properly as far as we can tell, but it seems in some edge cases it is not.

In these cases, we need to clean out the whole cache using ```clear()``` on the pool.

### Troubleshooting steps
We use the same pool-adapter for the tag-item as the cache-item itself. When the issue appears, i ask the items in the pool using ```redis-cli```:

```
127.0.0.1:6379> keys *nl*GpSchedule* 1) "sitecache.1.nl:U_1_S_2699916618_module_GpSchedule_" 
2) "sitecache.1.nl:A_1_S_2699916618_module_GpSchedule_" 
3) "sitecache.1.nl:U_1_S_1564297934_module_GpSchedule_" 
4) "sitecache.1.nl:\x00tags\x00U_1_S_1564297934_module_GpSchedule_"
```

As you can see there is _no_ \x00tags\x00 item at all. Then i run ```clear()``` on the pool:

```
127.0.0.1:6379> keys *nl*GpSchedule*
1) "sitecache.1.nl:U_1_S_2699916618_module_GpSchedule_"
2) "sitecache.1.nl:\x00tags\x00U_1_S_2699916618_module_GpSchedule_"
3) "sitecache.1.nl:A_1_S_2699916618_module_GpSchedule_"
4) "sitecache.1.nl:\x00tags\x00A_1_S_2699916618_module_GpSchedule_"
```

I get both the \x00tags\x00 pool-item as the main item.

### My idea
As far as I understand the code.. In the ```createCacheItem``` closure in ```TagAwareAdapter``` the expiry/defaultLifetime of the tag-item is the same as that of the cache-item. This means that if Redis starts expiring keys (which apparently it does randomly) it might select the 'tags' item as a victim, leaving the main item.

As the code assumes the item is not expired at all whenever the tags item does not exist, we are never able to expire it anymore.

### Request
I chatted about this with @nicolas-grekas on Slack and I now doubt I understand the tag code properly.

1. Am i correct to think that whenever we create a cache item with tags, it also creates the cache-item with the ```\x00tags\x00``` prefix of the id?
2. Is there any troubleshooting i can do to see which tags are linked to an item if the issue occurs again?

**Comment by dmaicher** [comment]
We had some similar issues a while ago in production using the `TagAwareAdapter` and Memcached. 

In our case we had to increase the memory for Memcached to make sure we never hit the limit so that it would start evicting our tag keys...

I think similar to Memcached also Redis will evict LRU keys when out of space for example: https://redis.io/topics/lru-cache

**Comment by mbek** [comment]
Yes I checked that, but the eviction statistics is zero on our adapter:

```
expired_keys:1239241
evicted_keys:0
```

**Comment by dmaicher** [comment]
Hmm that's strange :disappointed: Then it seems the disappearance of your tag keys is not caused by Redis itself?

**Comment by mbek** [comment]
Well, my guess is that the TTL of the 'tags' key is expired (not evicted) before the regular key, but I am not sure this is how it works.

**Comment by matigda** [comment]
But if TTL would be the case wouldn't cache-items be deleted in the same moment as tag-items ?

**Comment by mbek** [comment]
Not per se if i understand the documentation correctly:

https://redis.io/commands/expire:
```
Redis keys are expired in two ways: a passive way, and an active way.

A key is passively expired simply when some client tries to access it, and the key is found to be timed out.

Of course this is not enough as there are expired keys that will never be accessed again. These keys should be expired anyway, so periodically Redis tests a few keys at random among keys with an expire set. All the keys that are already expired are deleted from the keyspace.

Specifically this is what Redis does 10 times per second:

    Test 20 random keys from the set of keys with an associated expire.
    Delete all the keys found expired.
    If more than 25% of keys were expired, start again from step 1.
```

**Comment by 92161898515** [comment]
Pessoal estou me esforçando para ler todos os e-mails 
--
Enviado da aplicação Mail.Ru para Android quarta-feira, 20 setembro 2017, 05:15da manhã -03:00 de mbek  notifications@github.com :

**Comment by nicolas-grekas** [comment]
@mbek can you put this patch in place and report any new behavior?
```diff
--- a/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php
+++ b/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php
@@ -255,11 +255,7 @@ class TagAwareAdapter implements TagAwareAdapterInterface
             $f = $this->createCacheItem;
 
             foreach ($tagsByKey as $key => $tags) {
-                if ($tags) {
-                    $this->itemsAdapter->saveDeferred($f(static::TAGS_PREFIX.$key, array_intersect_key($tagVersions, $tags), $items[$key]));
-                } else {
-                    $deletedTags[] = static::TAGS_PREFIX.$key;
-                }
+                $this->itemsAdapter->saveDeferred($f(static::TAGS_PREFIX.$key, array_intersect_key($tagVersions, $tags), $items[$key]));
             }
             if ($deletedTags) {
                 $this->itemsAdapter->deleteItems($deletedTags);
```

**Comment by mbek** [comment]
I have added the changes to our file. Because the issue only occurs under highload, we will evaluate it the coming days.

**Comment by 92161898515** [comment]
👍

**Comment by nicolas-grekas** [comment]
See #24419

**Comment by Simperfit** [comment]
@mbek Do you still have an issue ?

**Comment by mbek** [comment]
@Simperfit I think the issue is resolved. Because it only happened under high load and even then seldomly, we cannot be sure for now. We did not hit the issue though 👍
