### ISSUE TITLE
Symfony 3.2 Form field collection errors mapping

### ISSUE THREAD

**Issue by mklimm** [symfony/symfony#24268]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.13

I have implemented form field for collection with allow_delete = true, allow_add = true and by_reference = false options.

I added needed js code to delete elements and append forms for new objects of this collection from prototype.

This works as I expected, but when I submit a few subforms for this collection with indexes not in order (for example 0, 1, 3 instead of 0, 1, 2), then errors from subform with index 3 are assigned to index 2 (which not exists), but subforms are rendered with indexes 0, 1, 3 (same as before submit) after invalid form submit...

I'm sure that it worked correctly in Symfony (errors from subform with index 3 are assigned to subform with same index).

**Comment by mklimm** [comment]
any progress?

**Comment by jakzal** [comment]
This has manifested itself in various forms. Re #7468 #15526 #21595

**Comment by xabbuh** [comment]
This use case is currently not supported. I am closing here as it duplicates #7828.
