### ISSUE TITLE
Empty data in Symfony Request object when Controller is called by Authorize.net webhook

### ISSUE THREAD

**Issue by silentiumtempus** [symfony/symfony#24262]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

Using Authorize.net sandbox Web UI, set up an webhook to call Symfony controller by URL. By default Auth.net sends POST request with data in JSON format. Verified at Requestb.in that the data is sent:

RAW BODY:

{"notificationId":"f803dsa2c9-32fa-4f44-8dsd-b9b2324lf9a7","eventType":"net.authorize.payment.authcapture.created","eventDate":"2017-09-19T09:29:46.9455538Z","webhookId":"f2a105zd-drf4-491v-ab31-9cdd4a8ad04a","payload":{"responseCode":21,"authCode":"111","avsResponse":"M","authAmount":12.5,"entityName":"transaction","id":"45"}}

Then trying to retrieve POST data in Symfony Controller and write it in a sample file, return actually does nothing:

Controller code:

```php
/**
 * @Route("/callback")
 * Class DonateController
 * @package AppBundle\Controller
 */
class WebHookController extends FOSRestController
{
/**

 * @Route("/test", name="webhooktest")
 * @param Request $request
 * @return \Symfony\Component\HttpFoundation\Response
 */

public function WebHookAction(Request $request){

    set_include_path('/var/www/project/web/');
    $file = 'webhook_test.txt';
    $content = $request->getContent();
    $json = json_decode($content, true);

    $wr = "Request object test 0: " .  $request->request->all() . "\n\n";
    $wr = $wr . "Object : " . $request->__toString() . "\n\n";
    file_put_contents($file, $wr);

    return $this->render('test/webhook.html.twig',
        [
            'wr' => $wr
        ]);
}
}
```

Unlucky, the $request contains only header, $request->request->all() returns only **empty** Array

Tried to extend from **FOSRestController** with body_listener instead of classic Symfony Controller without any difference.

config.xml part (**for FOSRest**):

fos_rest:
    param_fetcher_listener: true
    body_listener:
      decoders:
        json: fos_rest.decoder.json

Also tried to handle requests with **symfony-json-request-transformer** and **SymfonyBundlesJsonRequestBundle**, no result.

What's wrong here?

**Comment by silentiumtempus** [comment]
$request->getContent() also returns nothing

**Comment by chalasr** [comment]
Doesn't `$json` contain the (json decoded) request content?

**Comment by silentiumtempus** [comment]
Attempt to write output of $json to a file returns nothing, $json->get('notificationId') throws an exception "call to a member function get() on null"

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by silentiumtempus** [comment]
Do you need a standalone app or just a controller?
It also requires a authorize.net sandbox account set up to trigger webhook request.

**Comment by xabbuh** [comment]
If this only happens with your Sandbox account this is likely an issue with that service and not a Symfony bug.

By the way, did you try to dump the return value of `getContent()` before passing it to `json_decode()`?

**Comment by silentiumtempus** [comment]
Requestb.in service shows valid content of Authorize.net webhook request, but when I try to getContent() from the $request using same POST request from Authorize.net (just URL replaced pointing to my application) I get only null in request content. 

That's what I do:

1. Log in into auth.net sandobx.
2. Use auth.net webhook test service to send a POST request to requestb.in.
3. Verify at requestb.in that it's received, with both **header** and **raw body**
4. Use the same auth.net webhook test service to send a POST to my app.
5. Get the POST, write the $request to a file - > got **only** request header.
6. Try to get any data using getContent() or json_encode or any other way I know -> got null or empty Array.

**Comment by xabbuh** [comment]
Well, I still don't see that this is related to Symfony. This code works very well in many projects and I guess that would have been spotted earlier. But if it is, you should be able to create a small project without Authorize.net which just simulates the real requests that are happening in your application.

**Comment by silentiumtempus** [comment]
Resolved switching from HTTP to HTTPS

**Comment by jjenly** [comment]
I have the same issue.
At first it was strange behavior when im try to set cookies, its was autocomplited with: 'Set-Cookies'+NAME
update http-foundation (v4.0.1 => v4.0.2): help solve this, but then request start be empty on get cookies and post request, get method works
`<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Cookie;

class GameController extends Controller
{
    const localStorageSecret = 'setMyStats';

    /**
     * @Route("/start", name="start")
     */
    public function startAction(Request $request)
    {
        dump($request->request);
        $start = $request->request->get('start');
        if ($start === 'go!') {
            //never run
            return $this->redirectToRoute('login');
        }
        return $this->render('start.html.twig');
    }

}
?>`
