### ISSUE TITLE
Variable "index" does not exist in traces_text.html.twig (line 4)

### ISSUE THREAD

**Issue by tlorens** [symfony/symfony#24265]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.0

Twig Runtime error... Upgraded from 3.2.13 to 3.3.9 and started noticing that when I encountered an error the variable `_display_code_snippet` wasn't found in traces.html.twig.   So I rolled back a couple versions and it still happened.   Rolled back to 3.2.13 and the problem went away-- I then figured I'd step through each version until it happened again.  I get pretty much the same issue with 3.3.0 but it's `index` this time.  I have custom 400 and 500 twig files.   

I haven't looked into the code much-- tried hacking in the variable but it led to more issues.

**Comment by xabbuh** [comment]
Did you override some of the templates from TwigBundle?

**Comment by tlorens** [comment]
Yes.  I have a `Resources/TwigBundle/views/Exceptions/error404.html.twig` and `Resources/TwigBundle/views/Exceptions/exception_full.html.twig` I could move those out and see if that's the cause of the issue.  The problem only occurs when displaying the exception and stack-trace.  Let me toss these files out and see what happens, though I don' t think it will make a difference.   Anything else I can try to help debug what's going on here?  I'm more than willing to try and help out.

**Comment by tlorens** [comment]
Appears to be something with overriding `exception_full.html.twig`  With 3.3.x it seems that I don't need to do this anymore as the exception/stack-trace display has been greatly improved.
