### ISSUE TITLE
requirements-checker verbose mode?

### ISSUE THREAD

**Issue by garak** [symfony/symfony#24271]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

I need to communicate to an hosting provider the requirements for a Symfony application.
Unfortunately, it looks like there's no way to get such list from requirements-checker, unless you run it on a place where no requirement is met.
It would be nice if we could activate a verbose mode, where requirements-checker is not just displaying green dots, but instead is displaying full informations, so we can copy/paste them.
Of course, the same can apply to check.php web output.

**Comment by chalasr** [comment]
This should be submitted on https://github.com/symfony/requirements-checker, the package development and release process are independent from this repository.

**Comment by javiereguiluz** [comment]
I've moved this issue to https://github.com/symfony/requirements-checker/issues/13. Thanks!
