### ISSUE TITLE
Events profiler and logs get confused when an exception is thrown in one of listeners 

### ISSUE THREAD

**Issue by Xymanek** [symfony/symfony#24275]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

## Events panel

No exception behaviour:
![screenshot_1](https://user-images.githubusercontent.com/2865341/30692218-33cd922a-9ed3-11e7-928e-ae1460050ce8.png)

Exception in marked listener:
![screenshot_2](https://user-images.githubusercontent.com/2865341/30692147-f4c8eef8-9ed2-11e7-9546-96cda97214ec.png)

Note that in case of exception the previous listeners successfully run and then all `kernel.controller` listeners were called again (without any exceptions). Sub-request profiler shows exactly the same events and logs view.

## Logs panel

The thrown exception was `NotFoundHttpException` and this is the log view (very long): https://user-images.githubusercontent.com/2865341/30692725-73b966be-9ed5-11e7-8e7d-9a17de034981.png

Notice how it says

>Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke"

Order of events is weird too:

> request -> controller -> response -> finish_request -> exception -> response -> finish_request

While in reality (using xDebug):

> request -> security.authentication.success -> controller -> exception -> request -> controller -> controller_arguments -> response -> finish_request -> response -> finish_request -> terminate

**Comment by nicolas-grekas** [comment]
@ro0NL would you like to give this one a try, taking inspiration from #23659?
