### ISSUE TITLE
 [Form][CollectionType] Builder data in entry type is NULL

### ISSUE THREAD

**Issue by arnKo** [symfony/symfony#24274]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.8

Calling `$builder->getData()` inside the build function of a form type embedded into a CollectionType returns `NULL`.

```php
class ExampleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       $builder->add('collection', CollectionType::class, [
           'entry_type' => EmbeddedType::class,
       ]);
    }
}

class EmbeddedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Returns NULL
        var_dump($builder->getData());
    }
}
```

A simple fix would be to adapt the ResizeFormListener and forward the data to the builder:

From
```php
25 class ResizeFormListener implements EventSubscriberInterface
[...]
75     public function preSetData(FormEvent $event)
[...]
 93         // Then add all rows again in the correct order
 94         foreach ($data as $name => $value) {
 95             $form->add($name, $this->type, array_replace(array(
 96                 'property_path' => '['.$name.']',
 97             ), $this->options));
 98         }
 99     }
```
To
```php
25 class ResizeFormListener implements EventSubscriberInterface
[...]
75     public function preSetData(FormEvent $event)
[...]
 93         // Then add all rows again in the correct order
 94         foreach ($data as $name => $value) {
 95             $form->add($name, $this->type, array_merge(array_replace(array(
 96                 'property_path' => '['.$name.']',
 97             ), $this->options), array('data' => $value)));
 98         }
 99     }
```

**Comment by bartholdbos** [comment]
I reproduced this problem in the exact same manner

**Comment by bartholdbos** [comment]
Status: Reviewed

**Comment by Simperfit** [comment]
@arnKo Do you want to provide the according fix by creating a PR ?

**Comment by xabbuh** [comment]
IMO using the `getData()` method of the form builder is a mistake and you should use an event listener for the `PRE_SET_DATA` event instead. Do you then still experience the same behaviour?

**Comment by stof** [comment]
Building the form indeed happens before the data is set in a general case. In some cases, the data might be available already, but there is no guarantee (it depends how the form is created). Using the listener is indeed the right solution.
