### ISSUE TITLE
Compiler pass is ignored when registered inside an extension

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#24282]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

When registering a compiler pass inside an extension it is just ignored:

```php
class FooExtension extends Extension
{
     public function load(array $configs, ContainerBuilder $container)
    {
         // It will never be called
         $container->addCompilerPass(new CustomPass());
    }
}

**Comment by NicoHaase** [comment]
That sounds strange. Is the Method load itself never called? Or is your CustomPass never used? This might be the case, as processing the extensions itself is a compiler pass

**Comment by iltar** [comment]
Compiler passes should be registered in the bundle. The container builder in the extension load method, is a new builder that simply has the parameters/resources/definitions/aliases etc merged back into the original container. The [MergeExtensionConfigurationPass](https://github.com/symfony/symfony/blob/7a9eb2c654efc6db6a3922563d868a8e3e2461b8/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L66) loads the actual extensions, which means that the compiler passes are already running, which means you shouldn't be able to add new ones.

**Comment by NicoHaase** [comment]
@iltar: probably, there should be an exception thrown if addCompilerPass is called too late to be processed

**Comment by iltar** [comment]
Honestly, I believe the extension load should not receive a `ContainerBuilder` but a different class. Perhaps a subset of the methods, but something that clearly indicates that it's an isolated container that gets merged into the main one. It's not the first, second, or third time this is causing confusion, nor will it be the last time.

/cc @nicolas-grekas

**Comment by marcospassos** [comment]
The load method is being called. Yeah, it should throw an exception and better documented (I could not find any reference saying it is not supported). Btw, I'm using the DIC as a standalone component, so there is no bundle to put this logic into.

**Comment by stof** [comment]
@marcospassos you still have a place registering extensions. This is the place where you should register compiler passes too

**Comment by marcospassos** [comment]
The best option would be passing a another object that encapsulates the container builder exposing only the available methos at this stage, but it is a huge BC break.

**Comment by stof** [comment]
@iltar not receiving a ContainerBuilder but a class sharing 99% of the ContainerBundle would be kind of weird. And it is a huge BC break anyway (it requires replacing the ExtensionInterface with a different interface changing the typehint)

**Comment by iltar** [comment]
@stof you are correct. However, for now it could be subclassed by something that's more restrictive to at least give errors when trying to add a compiler pass for example.

**Comment by ogizanagi** [comment]
I agree with @iltar and I think we could improve the situation without BC break by simply creating a subclassed instance of the ContainerBuilder when calling the extension `load` method.
See #24295 for this solution.
