### ISSUE TITLE
[Console] You have requested a non-existent service (broken test after symfony update)

### ISSUE THREAD

**Issue by kylekatarnls** [symfony/symfony#24284]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4/dev-master

Hi, the following unit test was successfull last week, the cron job ran into an error now: https://github.com/pug-php/pug-symfony/blob/master/tests/Pug/PugSymfonyBundle/Command/AssetsPublishCommandTest.php

It seems Symfony is the only changed dependency.

All other tests are still goods, only the command test fails to get the service.

Does the API change or is it a bug?

Thanks,

**Comment by NicoHaase** [comment]
Can you share the error message?

**Comment by kylekatarnls** [comment]
Of course, first, this is the compelte Travis status:
https://travis-ci.org/pug-php/pug-symfony/builds/278150523

And this is the failure on PHP 7.1:
https://travis-ci.org/pug-php/pug-symfony/jobs/278150563#L565

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "templating.engine.pug".
/home/travis/build/pug-php/pug-symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:255
/home/travis/build/pug-php/pug-symfony/src/Jade/JadeSymfonyBundle/Command/AssetsPublishCommand.php:39
/home/travis/build/pug-php/pug-symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:276
/home/travis/build/pug-php/pug-symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Tester/CommandTester.php:84
/home/travis/build/pug-php/pug-symfony/tests/Pug/PugSymfonyBundle/Command/AssetsPublishCommandTest.php:26
```

**Comment by stof** [comment]
Well, the failing job is the one using Symfony 4. In Symfony 4, services are private by default. You should mark your service as public explicitly to keep it public.

And btw, you should make your CI run on 3.4 too (with the Symfony PHPunit bridge to report deprecations). You would have seen a deprecation warning in your testsuite for that change.

**Comment by kylekatarnls** [comment]
Thanks, a lot! Tests passed locally, I'll close the issue if all is good in TravisCI.
