### ISSUE TITLE
Autowiring fails with normalizers in no debug mode

### ISSUE THREAD

**Issue by rpg600** [symfony/symfony#24296]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

I'm using the autowiring for my services and i have some normalizers extending the ObjectNormalizer/AbstractNormalizer of the Serializer component.
Everything works fine in the dev env with debug mode, but in the prod env and no debug the serialization groups that were defined in annotations are simply ignored.
The cause is that the [FrameworkExtension](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1370) decorates the [ClassMetadataFactory](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactory.php) service with the [CacheClassMetadataFactory](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Serializer/Mapping/Factory/CacheClassMetadataFactory.php) service when debug mode is disabled. Therefore the ClassMetadataFactoryInterface type becomes ambiguous in the [AbstractNormalizer](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L76) because of these two services implementing the same interface and because no alias is defined.
I think it could be tricky to figure out, for most of developers, that an alias should be defined to resolve this problem.
IMO this should be done in the FrameworkExtension, it would be an easy pick.

ping @nicolas-grekas

**Comment by stof** [comment]
as normalizers expect the ClassMetadataFactoryInterface as argument, we should indeed make it autowirable.
@rpg600 do you want to open a PR adding the private alias ?
