### ISSUE TITLE
[RFC] Deprecate Kernel::getRootDir?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#24293]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.x

Should we deprecate `Kernel::getRootDir()`? With the new structure and `Kernel` living in `src/` this will basically point to some arbitrary namespace path. Im not even sure core still uses/needs it, having `getProjectDir()` also.

I think also any `dirname(__DIR__)` call in https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php should be replaced by that (getProjectDir).

**Comment by stof** [comment]
The hard part of the deprecation will be deprecating the `kernel.root_dir` parameter in the container.
We don't have a way to deprecate DIC parameters currently. And it will be hard to build such feature before the 3.4 feature freeze (which is planned for the end of the week according to the roadmap)

**Comment by ro0NL** [comment]
Milestone updated to 3.x :) perhaps be pragmatic on parameters? As 4.0 `kernel.root_dir` is just gone. Code wise there's no BC break, so perhaps we can do this with a CHANGELOG entry.

Deprecating public calls `getRootDir()` only.

**Comment by stof** [comment]
Removing a parameter **is** a BC break, as it breaks all bundles relying on it (and there are a lot.

**Comment by chalasr** [comment]
Removing `kernel.root_dir` would be a huge breaking change. I think it's worth having a mechanism for deprecating parameters, at least for core.

**Comment by ro0NL** [comment]
It's a useless path IMHO; superseded by `project_dir`. But deprecation path might not be worth it, as indeed the params are kinda problematic. (Perhaps nice feature anyway :))

But yeah, the path would be to use `project_dir` probably.

Related to #24292 now, if we want to get rid of `kernel.name`.

**Comment by ro0NL** [comment]
From @wouterj on slack

> Does anyone know the status of the `kernel.root_dir` parameter? It's marked deprecated in 3.3, but it seems to still be available in 4.0.0-BETA3. Can I keep using it in my bundle in Symfony 4?

Then i remembered https://github.com/symfony/symfony/pull/22315#discussion_r110220731

Basically `%kernel.root_dir%` is already deprecated.. :sweat: not sure how that reflects this PR, or `getRootDir()` at all :confused:

**Comment by nicolas-grekas** [comment]
I think we actually failed to remove the parameter even in 4.0...

**Comment by mariusbalcytis** [comment]
Actually, I think UPGRADE.md should be fixed to remove the statement that is not true. It's misleading and complicates the work taken in migration to 4.0 compatibility.

Furthermore, other Symfony bundles (in 4.x branch) also still use this parameter.

https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#httpkernel
```
Removed the kernel.root_dir parameter. Use the kernel.project_dir parameter instead.
Removed the Kernel::getRootDir() method. Use the Kernel::getProjectDir() method instead.
```

But both are there on 4.0:
https://github.com/symfony/http-kernel/blob/master/Kernel.php#L545

**Comment by ro0NL** [comment]
> remove the statement that is not true

Technically you're right, however i think its intention is to not start using `%kernel.root_dir%` as of 3.3. Then again.. SF itself is still using it :)

Perhaps do what we always do; revert the "virtual" deprecation now, and bring in a feature to deprecate di params first. Or dont deprecate the param.

**Comment by nicolas-grekas** [comment]
Let's drop that line from UPGRADE/CHANGELOG files yes.
