### ISSUE TITLE
Expected argument of type "array or (\Traversable and \ArrayAccess)", "string" given

### ISSUE THREAD

**Issue by MarwenBenTalebAli** [symfony/symfony#24302]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.8

Hello,

I'm trying to make a nested Form, embed a collection of forms inside a form. 
i have problem with the buildForm.

i am trying to add educations to my CurriculumVitae form.

- One CurriculumVitae has Many Educations.

- Many Education have One CurriculumVitae.

im getting this error message:

> Expected argument of type "array or (\Traversable and \ArrayAccess)",
> "string" given

CurriculumVitae Entity:

    /**
     * CurriculumVitae
     *
     * @ORM\Table(name="curriculum_vitae")
     * @ORM\Entity(repositoryClass="GE\CandidatBundle\Repository\CurriculumVitaeRepository")
     */
    class CurriculumVitae
    {
    	/**
         * @ORM\OneToMany(targetEntity="GE\CandidatBundle\Entity\Education", mappedBy="curriculumVitae", cascade={"persist", "remove"})
         * @ORM\Column(name="id_education")
         */
        protected $educations;
    /**
     * Add education
     *
     * @param \GE\CandidatBundle\Entity\Education $education
     *
     * @return CurriculumVitae
     */
    public function addEducation(\GE\CandidatBundle\Entity\Education $education)
    {
        $this->educations[] = $education;
        $education->setCurriculumVitae($this);
        return $this;
    }

    /**
     * Remove education
     *
     * @param \GE\CandidatBundle\Entity\Education $education
     */
    public function removeEducation(\GE\CandidatBundle\Entity\Education $education)
    {
        $this->educations->removeElement($education);
    }
    }
Education Entity:

    /**
     * Education
     *
     * @ORM\Table(name="education")
     * @ORM\Entity(repositoryClass="GE\CandidatBundle\Repository\EducationRepository")
     */
    class Education
    {
    	...
    	/**
         * Many Education have One CurriculumVitae.
         * @ORM\ManyToOne(targetEntity="GE\CandidatBundle\Entity\CurriculumVitae", inversedBy="educations")
         * @ORM\JoinColumn(name="curriculumVitae_id", referencedColumnName="id")
         */
        private $curriculumVitae;
    }

CurriculumVitaeType:

    public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('educations',
                    CollectionType::class, [
                        'entry_type' => EducationType::class,
                        'allow_add' => true,
                        'allow_delete' => true,
                        'prototype' => true,
                        'by_reference' => false,
                        'label' => 'Educations:'
                    ]
                )
            ;
        }

CurriculumVitaeController:

    class CurriculumVitaeController extends Controller
    {
    	...
        public function editAction(Request $request, CurriculumVitae $curriculumVitae)
        {
            $deleteForm = $this->createDeleteForm($curriculumVitae);
            $editForm = $this->createForm('GE\CandidatBundle\Form\CurriculumVitaeType', $curriculumVitae);
            $editForm->handleRequest($request);
    
            if ($editForm->isSubmitted() && $editForm->isValid()) {
                $this->getDoctrine()->getManager()->flush();
    
                return $this->redirectToRoute('cv_edit', array('id' => $curriculumVitae->getId()));
            }
    
            return $this->render('curriculumvitae/edit.html.twig', array(
                'curriculumVitae' => $curriculumVitae,
                'edit_form' => $editForm->createView(),
                'delete_form' => $deleteForm->createView(),
            ));
        }
    }

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by MarwenBenTalebAli** [comment]
Im sorry

> Expected argument of type "array or (\Traversable and \ArrayAccess)", "string" given

it is not a bug? I can't found any solution.

**Comment by dbrumann** [comment]
It's a bug in your code, not in Symfony. Feel free to [open a question on stackoverflow](https://stackoverflow.com/questions/ask). I will gladly help you there. You can also find help in the [symfony-devs slack](https://symfony.com/slack-invite) `#support`-channel.
