### ISSUE TITLE
[§ecurity, Guard] RememberMe, IS_FULLY_AUTHENTICATED and Symfony Guard doesn't work together

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#24319]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.8

Hi!

I'm using Symfony Guard, and trying to use the Remember Me function (currently for 4 minutes), but it has no effect.

I stay fully logged in until I specifically click the logg out button.

I have this firewall config:

        main:
            anonymous: ~
            switch_user: true

            remember_me:
                secret:   '%secret%'
                lifetime: 240 # 2 week in seconds
                path:     '/'
                always_remember_me: true
            logout:
                path:   '/logout'
                invalidate_session: false

            guard:
                provider: database_users
                authenticators: ['AppBundle\Security\FormAuthenticator']
                entry_point:  'AppBundle\Security\FormAuthenticator'

My FormAuthenticator:

    public function supportsRememberMe() { return true; }

Please advice... I want a "secure" are, where the user have to be fully authenticated to view...

**Comment by NicoHaase** [comment]
You should read http://symfony.com/doc/current/security/remember_me.html again - "remember_me" is supposed to keep your users logged in longer than the current session lasts. Iff your session lasts longer than four minutes, remember_me has no effect as this should only create a new session when there is no current session available.

**Comment by Richard87** [comment]
Aha, that makes a lot of sense now! Thank you for answering so quick!

**Comment by stof** [comment]
On a side note, you should avoid having a comment saying `2 week in seconds` near a number configuring 240s. Your future self will thank you when reading the code again 😄
