### ISSUE TITLE
[TwigBundle] Template override path isn't Symfony Flex-friendly

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#24310]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.9

Before Symfony Flex:

* template path: `/app/Resources/views/{PATH/TO/TEMPLATE.html.twig}`
* override template path: `app/Resources/{BUNDLE_NAME}/views/{PATH/TO/TEMPLATE.html.twig}`

After Symfony Flex:

* template path: `/templates/{PATH/TO/TEMPLATE.html.twig}`
* override template path: `/Resources/{BUNDLE_NAME}/views/{PATH/TO/TEMPLATE.html.twig}`

As you can see the override template path doesn't match overall path change logic made in Symfony Flex.

Proposing to look for override templates in `/templates/override/{BUNDLE_NAME}/views/{PATH/TO/TEMPLATE.html.twig}`.

Right now the override folder is hardcoded in https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L128-L130

P.S.
Might be a bug, but `.../_error/404.html` url is looking for override templates in `/src/Resources/{BUNDLE_NAME}/views/{PATH/TO/TEMPLATE.html.twig}` folder.

**Comment by jvasseur** [comment]
This is already fixed by #24179

**Comment by aik099** [comment]
I was just 11 days late about reporting it 😉 . Thanks for pointing me out in right directly. Will try using 3.4 branch (because release is only in november) to see how it working right now.
