### ISSUE TITLE
Symfony 3 - IIS web.config

### ISSUE THREAD

**Issue by kironet** [symfony/symfony#24324]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3

Hello,

How to run symfony on IIS web hosting? .httaccess doesn't work there and I can't find web.config in documentation.

Thanks

**Comment by javiereguiluz** [comment]
@kironet sadly I must close this issue because we use the GitHub repository only to report bugs and ask for new features. This kind of support questions should be asked in any of these channels: https://symfony.com/support  Thanks!
