### ISSUE TITLE
Log orphan events on the profiler

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#24347]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

We currently have the list of event with called and not called listeners:

![image](https://user-images.githubusercontent.com/1698357/30930469-16e61cba-a3c2-11e7-9f1e-75cfa314b588.png)

This is great, but if I do something like this:

```
$this->get('event_dispatcher')->dispatch('unknow.event');
```

This one does not appear anywhere on the profiler.

It would be great to have an "Orphan events" section to list event that was dispatched but not managed by any listener. This would allow an easier debugging IMHO.

Additionally, we might add a warning section on the profiler toolbar when orphan event are dispatched.

**Comment by vudaltsov** [comment]
I don't think that orphan events should generate a warning. F.e. workflow dispatches many events but you are not supposed to listen to all of them and there is nothing bad about it.

**Comment by Simperfit** [comment]
We could filter events, keep thoses triggered by the user and show them in the profiler with a warning

**Comment by lyrixx** [comment]
IMHO it's a good thing to display orphan events. But the warning is a bad idea. If an event is not listened, it's not an issue...

**Comment by xabbuh** [comment]
I agree with @lyrixx. @vudaltsov gave a very good example where it's totally valid to not listen to certain events without that being an issue.

**Comment by Simperfit** [comment]
@Soullivaneuh Do you want to work on this new feature ? it seems that we agreed on this (without adding the warning).

**Comment by xabbuh** [comment]
@Simperfit see #24392
