### ISSUE TITLE
[Debug] Support showing exceptions as plain text

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#24354]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

As requested in PR #18722 (the PR's specific implementation didn't make it, but the goal should be retained.)
Should be done using VarDumper IMHO (see comments on linked PR).

**Comment by yceruto** [comment]
@nicolas-grekas do you think there's anything else to do here? I think the TxtErrorRenderer provided by the new ErrorRenderer component is covering it, isn't it?

**Comment by nicolas-grekas** [comment]
Sure
