### ISSUE TITLE
[Phpstorm Plugin Support] Remote Call (Additional bugreport)

### ISSUE THREAD

**Issue by pquerner** [symfony/symfony#24355]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| Symfony version  | 3.4-dev (https://github.com/symfony/symfony/commit/bd3bc69036d4dc34e029681f059f4ba301f1ba38)

Ticket #24218 was fixed via #24236 , but it introduced an error on Windows machines.

The following error is logged to the users Browser

```
Uncaught SyntaxError: Invalid Unicode escape sequence
```

The generated link from the profiler looks like this on a Windows 10 machine:

```
javascript:var rq = new XMLHttpRequest(); rq.open('GET', 'http://localhost:8091?message=G:\_projects\xxxx\app\Resources\views\user\edit.html.twig:1', true); rq.send(null);
```

(My browser is Google Chrome Version 61.0.3163.100)

If the URL is opened by hand it correctly opens the file in my PHPStorm IDE (with enabled Remote Call Plugin).

If we manually escape the Windows directory dividers (backslash) with additional backslashes, the URL should look like this:

```
javascript:var rq = new XMLHttpRequest(); rq.open('GET', 'http://localhost:8091?message=G:\\_projects\\xxxx\\app\\Resources\\views\\user\\edit.html.twig:1', true); rq.send(null);
```

and is working fine.

This has been reported before here https://github.com/symfony/symfony/pull/24236#issuecomment-332780218 but I was asked to create a new issue here https://github.com/symfony/symfony/issues/24218#issuecomment-332782582

I guessed here https://github.com/symfony/symfony/pull/24236#issuecomment-332784532 that the generated ```link``` variable should again be looked at from a Windows machine. Although its currently unclear where the XHR link is coming from (like guessed here https://github.com/symfony/symfony/pull/24236#issuecomment-332786033)

**Comment by ro0NL** [comment]
Can you explain where this JS comes from, im kinda clueless. And seems not really SF related, but maybe the plugin/browser is messing, and we might do something to overcome.

**Comment by ro0NL** [comment]
If this truly requires to be called as XHR request, maybe a new setting could work;

```
framework.ide: { link: '...', xhr: true }
```

**Comment by nicolas-grekas** [comment]
for sure not, config options shouldn't be used as workarounds for badly encoded strings :)

**Comment by pquerner** [comment]
If I ```dump``` the variable ```link``` here https://github.com/symfony/symfony/commit/9ebe2185bd7785a119bd4ebc057c89b30f8cd3b0#diff-d586a5424c06b09812bbfd9e8c266456R90 

I get the ```javascript:var rq = new XMLHttpRequest(); rq.open('GET', 'http://localhost....``` string. So I guess its SF related? But if I search my whole app folder (with vendors folder) for this code it doesnt show up.

**Comment by stof** [comment]
@pquerner search for the beginning of the string (without the URL itself, as it depends on the path being opened), it may allow you to find the location.

**Comment by pquerner** [comment]
Turns out https://github.com/symfony/symfony/pull/24356#issuecomment-333059560 nothing needs to be changed after all. Sorry for the big mess, guys.
