### ISSUE TITLE
`%env(VAR)%` does not work with `symfony/monolog-bridge`

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#24368]
The latest stable `symfony/monolog-bridge` `v3.3.9` does not work with `%env(...)%` properly:

It throws
````
Warning: constant(): Couldn't find constant Monolog\Logger::ENV_FOO_E6B45FD60EEE44A71EEAF8C53561891E
````

for the following config:

```php
    'main' => [
        'type' => 'stream',
        'path' => '%kernel.logs_dir%/%kernel.environment%.log',
        'level' => '%env(FOO)%',
        'channels' => ['!event'],
    ],
```

**Comment by nicolas-grekas** [comment]
Did it ever worked? It looks like the same as #24270: the error message is buggy and will be fixed by #25163
But the exception will remain: env vars are not (and should not) be supported everywhere.

**Comment by zerkms** [comment]
> env vars are not (and should not) be supported everywhere.

The "should not" part is confusing.

It looks like the framework developers know better how people should configure their apps. That surely is not true 🤷‍♂️

**Comment by nicolas-grekas** [comment]
For sure, and you as a dev have everything at hand to make it work if you really want to. But then, you need to code a DI extension, because the framework provides best practices :)
I invite you to look at the link I provided to learn about the current reasoning.
Pleas also answer my question if possible.

**Comment by zerkms** [comment]
> Did it ever work?
It totally worked with old (now deprecated) `SYMFONY_` way of specifying environment variables. With `SYMFONY_` it worked everywhere unconditionally, now it's a mine field - you cannot tell until you try.
From that perspective I see the changes as a huge usability/flexibility regression.

**Comment by nicolas-grekas** [comment]
This is going a bit of topic. The deprecated way of using env vars just didn't work. There are plenty of discussion about why the current way was desired before it existed, and why it is how it is now.
The main idea being that env var should be a way to configure an app *at run time*, which means without container re-compilation for Symfony apps.

**Comment by zerkms** [comment]
I did not mean the current solution is not "better", my point is that the new solution does not cover all the use cases old solution was capable of handling.
I was configuring the `symfony/monolog-bridge` through environment variables before. Indeed, it was not in runtime, but at least it was possible to do with container regeneration. Now it's broken. Hence - it's a regression.

**Comment by nicolas-grekas** [comment]
I'm closing here as technically the issue has been fixed. Using env vars at compile time is another topic that would need another discussion to be resolved. Thanks for the hints.

**Comment by nicolas-grekas** [comment]
See #25173
