### ISSUE TITLE
[Security] @Security annotation User parameter is overridden by authenticated user

### ISSUE THREAD

**Issue by masterkaos** [symfony/symfony#24360]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

If I have the following controller action setup
```
/**
* @Securty("is_granted('USER_MANAGE', user)")
*/
public function indexAction(User $user)
{

}
```

The authenticated user will be passed into the voter instead of the user parameter.
This can easily be resolved by renaming the parameter. This may be expected behaviour, but at the minimum, should the documentation be updated to better reflect that would be the intended outcome?

**Comment by xabbuh** [comment]
The `@Security` annotation is part of the [SensioFrameworkExtraBundle](https://github.com/sensiolabs/SensioFrameworkExtraBundle). This should be reported over there.
