### ISSUE TITLE
[WebProfiler] Exception, when attempting to view EXPLAIN of a Doctrine query

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#24394]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Using `Product` entity from https://symfony.com/doc/current/doctrine.html documentation and modified `DefaultController::editAction` to:

1. accept `Product $product` parameter
2. have `@Route("/edit-product/{product}")` annotation

Then I'm accessing `/edit-product/2` url and viewing performed DB queries in Web Profiler.

When I click on `Explain query` link I'm getting `An error occurred while loading the query explanation.` message instead of actual EXPLAIN and Developer Console of Browser shows that underlying AJAX request failed with HTTP 500 response.

Looking deeper shows that error was:

```
An exception has been thrown during the rendering of a template ("You have requested a non-existent service "templating". Did you mean one of these: "templating.helper.logout_url", "templating.helper.security"?"). (500 Internal Server Error)
```

![2017-10-02_1114](https://user-images.githubusercontent.com/1277526/31068958-f7073cb8-a762-11e7-8f9f-480164651b76.png)

P.S.
I've used Symfony Flex to create a project and templates are rendered correctly with Twig.

**Comment by stof** [comment]
hmm, DoctrineBundle still uses the templating component instead of direct Twig usage in 1 place.

the workaround until we fix it is to install the `symfony/templating` component.

**Comment by aik099** [comment]
Yes, I've also found https://github.com/doctrine/DoctrineBundle/blob/master/Controller/ProfilerController.php#L82. I'll send a PR in there with a fix to resemble `ControllerTrailt::render` method (see https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L231-L247).

**Comment by aik099** [comment]
I've reported issue into correct place: https://github.com/doctrine/DoctrineBundle/issues/707 . Sorry for posting issue to wrong repo.

**Comment by MikSDigital** [comment]
@stof hello!
Installing `symfony/templating` did not help.
`{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.0",
        "symfony/orm-pack": "^1.0",
        "symfony/profiler-pack": "^1.0",
        "symfony/templating": "^4.0",
        "symfony/yaml": "^4.0"
    },
    "require-dev": {
        "symfony/dotenv": "^4.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "01C1DPEAE05ENYCC4D2R6HJW26",
            "allow-contrib": false
        }
    }
}
`

**Comment by PaddyLock** [comment]
I'm also experiencing this issue. I have Symfony 4.1.4 with Flex. symfony/templating is install as a require-dev by symfony/framework-bundle

**Comment by xabbuh** [comment]
@PaddyLock Dependencies listed in `require-dev` are only installed if they are in the `require-dev` section of the project's `composer.json` file. The dev dependencies of your project's dependencies are not taken into account. So if you are not requiring the Templating component yourself and neither does any of your dependencies, the package will not be installed. You can run `composer show` to see what's actually installed.

**Comment by PaddyLock** [comment]
@xabbuh thanks, I don't know how then (maybe the way flex works?) but it is installed though as I can see it in the vendor/symfony/templating folder

**Comment by xabbuh** [comment]
I am afraid we won't be able to help without being able to reproduce. So if you could create a small application that allows to reproduce, that will be really helpful.
