### ISSUE TITLE
Symfony yaml pattern with double quotes

### ISSUE THREAD

**Issue by faheemhameed** [symfony/symfony#24408]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

```yaml
            pattern: 
                "^/api/(apiName1|\
                apiName2|\
                apiName3)"
```

The above pattern supposed to be translated as 

```
{ pattern: '^/api/(apiName1|apiName2|apiName3)' }
```

http://nodeca.github.io/js-yaml/

But it's translated with a space for line break as below:

```
{ pattern: '^/api/(apiName1| apiName2| apiName3)' }
```

It seems to me like a bug. 

Thanks.

**Comment by xabbuh** [comment]
I don't understand. Why should spaces inside a quoted string be ignored?

**Comment by xabbuh** [comment]
I am going to close here as the observed behaviour is correct. In (double) quoted strings newlines are folded which means that the become a space (see http://www.yaml.org/spec/1.2/spec.html#id2760844).

**Comment by faheemhameed** [comment]
Sorry, I missed to add the backslash at the end of the line in the pattern. 

I understand that the each new line is converted to a single space but when you add a backslash at the end of the line then it strips that white space.

`yaml
            pattern: 
                "^/api/(apiName1|\
                apiName2|\
                apiName3)"
``

Please try to see this here:

http://nodeca.github.io/js-yaml/#yaml=ICAgICAgICAgICAgcGF0dGVybjogCiAgICAgICAgICAgICAgICAiXi9hcGkvKGFwaU5hbWUxfFwKICAgICAgICAgICAgICAgIGFwaU5hbWUyfFwKICAgICAgICAgICAgICAgIGFwaU5hbWUzKSI=

But if I am wrong you may please help let me know how to achieve the above (spaceless translation of new line characters)

**Comment by xabbuh** [comment]
@faheemhameed I have updated your description to reflect the backslashes. And you are right, for that example you would indeed expect the outcome that you describe.

**Comment by xabbuh** [comment]
see #24416
