### ISSUE TITLE
Bug determining isFromTrustedProxy as secure broadcasted proxies

### ISSUE THREAD

**Issue by webmake** [symfony/symfony#24424]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3.9

First all all bug recovered debugging https://github.com/fideloper/TrustedProxy, why all trafic is still under http, not https. So let's take a look.

```
    public function isSecure()
    {
        if ($this->isFromTrustedProxy() && $proto = $this->getTrustedValues(self::HEADER_CLIENT_PROTO)) {
            return in_array(strtolower($proto[0]), array('https', 'on', 'ssl', '1'), true);
        }

        $https = $this->server->get('HTTPS');

        return !empty($https) && 'off' !== strtolower($https);
    }
```
gives always as **not secure** (isSecure is `false` - **that's not expected**)

Okay Let's take then deeper. Called method `isFromTrustedProxy` gives false:
```
    public function isFromTrustedProxy()
    {
        return self::$trustedProxies && IpUtils::checkIp($this->server->get('REMOTE_ADDR'), self::$trustedProxies);
    }
```
Let's take some data that we set via `setTrustedProxies`, `$proxies = ['*']`. Now what's happening:
```
['*'] && IpUtils::checkIp($this->server->get('REMOTE_ADDR'), ['*'])
```
first part is true (**good**), but `checkIp` returns false (**not expected**).
```
    public static function checkIp($requestIp, $ips)
    {
        if (!is_array($ips)) {
            $ips = array($ips);
        }

        $method = substr_count($requestIp, ':') > 1 ? 'checkIp6' : 'checkIp4';

        foreach ($ips as $ip) {
            if (self::$method($requestIp, $ip)) {
                return true;
            }
        }

        return false;
    }
```
So any ip, against all others `'*'` is not valid, strange. Now let's take real data:
$requestIp = 192.168.20.13, and $ip = `'*'`
```
    public static function checkIp4($requestIp, $ip)
    {
        $cacheKey = $requestIp.'-'.$ip;
        if (isset(self::$checkedIps[$cacheKey])) {
            return self::$checkedIps[$cacheKey];
        }

        if (!filter_var($requestIp, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
            return self::$checkedIps[$cacheKey] = false;
        }

        if (false !== strpos($ip, '/')) {
            list($address, $netmask) = explode('/', $ip, 2);

            if ($netmask === '0') {
                return self::$checkedIps[$cacheKey] = filter_var($address, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4);
            }

            if ($netmask < 0 || $netmask > 32) {
                return self::$checkedIps[$cacheKey] = false;
            }
        } else {
            $address = $ip;
            $netmask = 32;
        }

        return self::$checkedIps[$cacheKey] = 0 === substr_compare(sprintf('%032b', ip2long($requestIp)), sprintf('%032b', ip2long($address)), 0, $netmask);
    }
```
Description tells:
```
@return bool Whether the request IP matches the IP, or whether the request IP is within the CIDR subnet
```

Where am I wrong, giving all trafic as 0.0.0.0 or `'*'` (just to be clear 
```
sprintf('%032b', ip2long('0.0.0.0')) and
sprintf('%032b', ip2long('*'))
```
are the same), but turns out that trusted all network (broadcast), not matches against given ip (192.168.20.13)?

**Comment by webmake** [comment]
IMHO, last line `return self::$checkedIps[$cacheKey] = 0 === substr_compare....` is wrongly interpreted, because substr_compare returns 1, but `0 === 1` is false

**Comment by webmake** [comment]
I found, that if I pass `'*/0'` then also wrongly works `filter_var($address, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4);` part within `checkIp4` method. Only one solution, `'0.0.0.0/0'` gives proper result. 

Should be considered then what is a valid form to give into `setTrustedProxies`

**Comment by xabbuh** [comment]
Did we ever say or document anywhere that you *could* pass `*` instead of an IP address/netmask?

**Comment by webmake** [comment]
Is there any code validating from dummy mistakes?

**Comment by webmake** [comment]
Two code places working differently, first validates with FILTER_VALIDATE_IP, second place converts using ip2long without any validation. See point? Should be code working the same, either bot uses validation, either remove that filtering at all

**Comment by xabbuh** [comment]
Would there be any difference? The result would still be `false`, right?

**Comment by webmake** [comment]
Actually not, as you can see `sprintf('%032b', ip2long('0.0.0.0')) == sprintf('%032b', ip2long('*'))` that's the difference, so in one place you consider `'*'` as not valid, in other place as valid.

**Comment by xabbuh** [comment]
I guess noone thought about someone passing `*` there and then PHP's type juggling takes action and leads to the observed result. Maybe we should add a check to just return `false` if anything that is neither an IP address nor a netmask is passed.

**Comment by xabbuh** [comment]
@webmake Can you check if #24502 improves your situation?
