### ISSUE TITLE
[DX] Allow listeners to be autoconfigured

### ISSUE THREAD

**Issue by wjbLabs** [symfony/symfony#24422]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Autoconfiguring services is amazing feature but it allows me to configure event subscribers and not event listeners (they still must use ``services.yml``).

My suggestion is a set of interfaces that will allow autoconfig of them as well:
```php
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;

interface OnKernelViewListenerInterface
{
    public function onKernelView(GetResponseForControllerResultEvent $event);
}
```
and extension class:
```php
$container
    ->registerForAutoconfiguration(OnKernelViewListenerInterface::class)
    ->addTag('kernel.event_listener', ['event' => KernelEvents::VIEW]);
```
Example code I am using:

```php
class ResponseSerializer implements OnKernelViewListenerInterface
{
    private $serializer;

    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    public function onKernelView(GetResponseForControllerResultEvent $event): void
    {
        $request = $event->getRequest();
        $controllerResult = $event->getControllerResult();
        // do serialization and make response
        $event->setResponse($response);
    }
}
```

**Comment by iltar** [comment]
Sounds interesting. Your target branch should be 3.4 though

**Comment by wjbLabs** [comment]
@iltar Thanks, I fixed it.

**Comment by Koc** [comment]
How to deal with priority?

**Comment by nicolas-grekas** [comment]
Why not just implement EventSubscriberInterface instead of adding yet more interfaces?

**Comment by wjbLabs** [comment]
@nicolas-grekas Because honestly, I don't like writting ``getSubscribedEvents()`` when I am listening only to one event.

I prefer to do one event per class.

**Comment by nicolas-grekas** [comment]
Then you can create some per-event generic base class in your app that implement it, and done.
I don't think we should support this in Symfony: that's less flexible (see priority issue + one event per interface), and increases overall complexity, by adding yet another way to do something.

**Comment by wjbLabs** [comment]
Well I already built this, along with ``DoctrineEventSubscriber``:

![screenshot 2017-10-04 14 13 00](https://user-images.githubusercontent.com/1964158/31175106-5d8941be-a90e-11e7-9ae7-33bcbc03f157.png)

and I will put annotation reader to resolve priority. 

But I was thinking this could be a good helper if it was in core so users who prefer listeners, don't have to write in ``services.yml``.

**Comment by chalasr** [comment]
Does not look interesting enough to me either.

**Comment by Tobion** [comment]
Closing as core members including me don't think this is a good idea.
