### ISSUE TITLE
[HttpFoundation] Request should not use php://input if content is NULL

### ISSUE THREAD

**Issue by andig** [symfony/symfony#24437]
| Q                | A
| ---------------- | -----
| Bug report?      | not sure
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | ^2.6

I have a problem when sending HTTP request with using HttpFoundation, Http Messagebridge together with GuzzleHttp.

What happens is that a simple Symfony GET request:

    GET /entity.json HTTP/1.1
    Host: 127.0.0.1:8080

becomes when converted to Psr7 and sent via Guzzle:

    GET /entity.json HTTP/1.1
    Host: 127.0.0.1:8080
    Transfer-Encoding: chunked
    Expect: 100-Continue
    user-agent: Symfony/3.X
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-language: en-us,en;q=0.5
    accept-charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7

The problem:

Getting request as ressource via `Request->getContent(true)` returns `php://input` as ressource for GET request body since `content` is `NULL` (default). The `HttpMessageBridge` creates a Psr7 request with `php://input` as body stream. Due to this stream being present `Guzzle` is not able to determine body size (NULL instead of 0) and creates a complex request.

Impact:

Request is slow (`Expect: 100-continue`) and some server libraries like `reactphp/http` are not able to handle it.

While I could fix that for my own HTTP client by setting `content` to `(string)""` instead of `NULL` this won't fix it for other clients.

Does it really make sense that Symfony Request returns `php://input` when `content` is not set?

**Comment by andig** [comment]
Note: the original body `asRessource` functionality has been introduced in https://github.com/symfony/http-foundation/commit/1b2736dc9bec4dc031b069211b2f1bd8afe15b18 by @Seldaek

**Comment by Simperfit** [comment]
@andig Do you want to provide a PR ? I think this has to be fixed.

**Comment by andig** [comment]
> Do you want to provide a PR ? I think this has to be fixed.

Would need at least some insight if this makes sense.

**Comment by nicolas-grekas** [comment]
@andig if the patch is not huge, I think you could gather more feedback by providing a PR. I don't see anything that would allow me to tell you to not try it...

**Comment by fabpot** [comment]
Closing as it seems to related to the PSR-7 bridge as mentioned in the linked issue.
