### ISSUE TITLE
[HttpFoundation] RedisSessionHandler

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#24433]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

Add a `RedisSessionHandler`, same as existing ones for Memcache(d). It would allow to use Redis as a session storage without modifying php.ini and with better integration with Symfony (using env vars for configuring the `save_path`, for example).

**Comment by Tobion** [comment]
please use the search. #14539

**Comment by dkarlovi** [comment]
I did, must have missed it because it's closed which makes no sense to me.

Having a user handler means you can define the save path from config, using env vars, as I said. There's zero reason to have TWO Memcached-related handlers and zero Redis handlers.

**Comment by Tobion** [comment]
There are not two memcached handlers.

**Comment by Tobion** [comment]
There are 4 memcache(d) handlers:

- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcacheSessionHandler.php
- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php
- http://php.net/manual/de/memcached.sessions.php
- http://us3.php.net/manual/en/memcache.examples-overview.php

And two for Redis:

- https://github.com/phpredis/phpredis#php-session-handler
- https://github.com/nrk/predis/blob/v1.1/src/Session/Handler.php

Isn't that enough?

**Comment by dkarlovi** [comment]
> There are not two memcached handlers.

I think you know what I mean: HttpFoundation currently provides support for:

1. [`MemcacheSessionHandler`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcacheSessionHandler.php)
2. [`MemcachedSessionHandler`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php)

Reason given for rejecting previous PRs: there's a native support already. Obviously, this goes for Memcache one too, why did that get special treatment and end up in the framework?

> Isn't that enough?

Obviously it's technically enough, this issue is about providing it by the framework, with all the benefits coming from the integration (like the twice-mentioned env config support out of the box). Monolog can output to STDERR, but [having a minimal implementation built right into the framework is still desirable](https://github.com/symfony/symfony/pull/24300).

IMO having multiple PRs and issues on the matter should be a signal people use Redis in this way, are keen to use it in Symfony apps and having support for it shouldn't be a problem, especially since the implementation is so minimal. Please reconsider this (several times rejected) idea.

**Comment by dkarlovi** [comment]
Two side notes I've just remembered:

1. Redis native session support is tricky and can be buggy: we had issues with it on a (non-Symfony, though) large news portal (many users, many sessions) and it can cause problems which were worked around by a user Redis handler which did the same thing in the same setup.
2. As Symfony now offers the Cache component, maybe an acceptable idea might be to offer something like `CacheSessionHandler`? This would amount to the same thing, but might make it more palpable?

**Comment by xabbuh** [comment]
Just for the records: Having a generic PSR-6 session handler was already rejected (see #19193 and #23321).

**Comment by dkarlovi** [comment]
@xabbuh thanks for the links, I actually fully agree with @nicolas-grekas arguments there about different volatility constraints for both use cases, haven't completely considered it.

**Comment by Tobion** [comment]
> with all the benefits coming from the integration (like the twice-mentioned env config support out of the box)

You can just call `ini_set('session.save_path', $env)` with the env config. Or just use the framework session config for this which does the same thing. I don't see the relation to whether the handler is in symfony or somewhere else.

**Comment by dkarlovi** [comment]
> I don't see the relation to whether the handler is in symfony or somewhere else.

I'm not claiming it's impossible to do it otherwise because of course it is. The proposal is to bring Redis support inline with Memcache support for this use case, as I've said. If I can

> just `ini_set`

for Redis, I can do that for Memcache as well, what's the reason to support Memcached twice, but Redis not at all? Also, as I've said, from my experience Redis native session support can be buggy.

What's exactly your reason NOT to do it, which doesn't also apply to Memcached?

**Comment by Tobion** [comment]
Maintainance costs? Not reinventing the wheel? There are alot of reasons. Feel free to provide a PR that has definite advantages like more features or better performance than the existing redis session handlers. Then we can talk more concrete.
Btw, we deprecated one of the memcache session handlers. #24443

**Comment by dkarlovi** [comment]
> definite advantages like more features or better performance than the existing redis session handlers

Does the existing Memcached handler satisfy those requirements, seeing it's just a wrapper around the native module? Memcached native session handler can basically be used exactly like the Redis one.

Or are you planning on deprecating `MemcachedSessionHandler` too?

**Comment by nicolas-grekas** [comment]
@dkarlovi would you have time to submit a PR as @Tobion suggested? Maybe the argument of not having to install another package to use it would convince ppl?

**Comment by dkarlovi** [comment]
@nicolas-grekas sure, but I don't see what my PR could do differently than those two rejected before.

The way I see, the argument here for not including the Redis adapter is "no, thank you" as I literally cannot understand why would you not do it if you have done the Memcached one:

1) has native support directly in the module: (Memcached: yes, Redis: yes)
2) has custom user handler available (Memcached: yes, Redis: yes)
3) has Symfony user handler available (Memcached: yes, Redis: no)

That's my whole point, can't see why Redis is second-class citizen for Symfony sessions. :)

**Comment by nicolas-grekas** [comment]
When #24523 will be merged, I think it'll make sense to add a Redis session handler.

**Comment by dkarlovi** [comment]
@nicolas-grekas would we go for a new PR or resume previous ones?

**Comment by nicolas-grekas** [comment]
New PR (that could borrow code from previous ones)

**Comment by Simperfit** [comment]
@dkarlovi since #24523 has been merged, do you want to implement that feature ?

**Comment by dkarlovi** [comment]
@Simperfit seeing you're doing #23910, I'll do this, yes.

**Comment by dkarlovi** [comment]
There we go, hope it's OK. :)
