### ISSUE TITLE
[RFC][DI] Get rid of tags

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#24432]
| Q                | A
| ---------------- | -----
| Bug report?      |  no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | ?

I was wondering, seing autoconfiguration system and the following pull requests:
* #12269 
* #22649 
* #23916 

if we could consider a futur without tags, tags simply being replaced by "instanceof".

Indeed, autoconfigure tends to add tags to classes implementing a certain type in order to inject them into another service. But rather than tagging according to implementations and then fetching tagged services, why do we not simply fetch services according to their implementation directly?

This would also bring more security has tagged services will have to implement a certain type (which you probably often want). And for those special cases where you want to tag different classes, you can just create an empty interface and make your services implement that empty interface.

WDYT?

**Comment by nicolas-grekas** [comment]
Let's say some bundle has several `EventSubscriberInterface`, and a configuration in place to conditionally enable some of them for some reason, how would you do that? That's the purpose of tags: decouple interfaces and wiring. This is desired.

**Comment by stof** [comment]
thus, we have many cases where tags need to provide additional metadata for the wiring (only half of the core tags are compatible with autoconfiguration due to that I would say).

So I don't see any benefit about removing tags entirely.

**Comment by nicolas-grekas** [comment]
Closing as tags serve a unique and legitimate purpose. The nice thing as you spotted, is that you can save yourself from using them for simple (yet common) use cases.
