### ISSUE TITLE
[DI] Throw useful error msg when trying to access not-found but private service

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#24444]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Right now, when a service is not found, we throw a `ServiceNotFoundException` with some suggestions.
But when the lookup is for a private service that ended up being removed or inlined, that message is not accurate: we should instead hint about the service being private + suggest to either turn it public or not use the container at all (similar to the deprecation in `Container::get()`).

On 4.0, where services will be private by default, this looks like a DX requirement to me, so we should do it during the feat. freeze.

**Comment by stof** [comment]
However, this would force us to keep a list of private ids in the dumped container (including removed/inlined services, that we don't even have today at all). What about the memory usage here (although it should be possible to keep this array in shared memory if being careful)

**Comment by nicolas-grekas** [comment]
Correct. I think that it wouldn't matter if we put that list in a separate file (at least when using the multi-files dumped container.)

**Comment by sroze** [comment]
> On 4.0, where services will be private by default

So is this the final decision of the core team? Either way, I also think it's a DX requirement. 

@nicolas-grekas What do you mean by a separate file? We already have the `privates` within the container, can't we use this?

**Comment by nicolas-grekas** [comment]
That's the current state yes, so it should stay: this is just the final logical step of the work put by the community in this area

About the list of private services, yes we can put it in the class for sure. The discussion was about finding a way to *not* put it there, in order to not bloat the container.

**Comment by sroze** [comment]
That's fair enough, let's go this way. We need to write some great documentation/articles about how this is important then I guess.

Sure, I get that it would be nice to move it somewhere else for performance reasons but for now I guess we can just re-use these `privates` for this specific issue :)

**Comment by sroze** [comment]
Also, don't get what you mean by "we put that list in a separate file (at least when using the multi-files dumped container.)".

**Comment by chalasr** [comment]
@sroze You probably missed https://github.com/symfony/symfony/pull/23741
