### ISSUE TITLE
[DI] UTF-8 characters not supported as parameter key

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony#24445]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

I get a fatal error when I set UTF-8 characters as parameter key in config files.

Failing change on symfony demo : https://github.com/GromNaN/symfony-demo/commit/63376b923addc33314359670fd024402c61f83ac

```yaml
parameters:
    mécanique: "%orangé%"
    orangé: "ok"
```

```
✗ php bin/console server:run -vvv


  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: DOMElement::setAttribute(): string is not in UTF-8


Exception trace:
 () at vendor/symfony/dependency-injection/Dumper/XmlDumper.php:292
 Symfony\Component\DependencyInjection\Dumper\XmlDumper->convertParameters() at vendor/symfony/dependency-injection/Dumper/XmlDumper.php:81
 Symfony\Component\DependencyInjection\Dumper\XmlDumper->addParameters() at vendor/symfony/dependency-injection/Dumper/XmlDumper.php:53
 Symfony\Component\DependencyInjection\Dumper\XmlDumper->dump() at vendor/symfony/framework-bundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php:32
 Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->process() at vendor/symfony/dependency-injection/Compiler/Compiler.php:143
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at vendor/symfony/dependency-injection/ContainerBuilder.php:746
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at vendor/symfony/http-kernel/Kernel.php:577
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor/symfony/http-kernel/Kernel.php:119
 Symfony\Component\HttpKernel\Kernel->boot() at vendor/symfony/framework-bundle/Console/Application.php:69
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at bin/console:33
```

PHP Version installed on Mac with Homebrew.
```
✗ php -v
PHP 7.1.8 (cli) (built: Aug 17 2017 17:06:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.17.3~mac-x64-non_zts71, https://blackfire.io, by SensioLabs
```

**Comment by GromNaN** [comment]
The issue only appends with debug enabled (when ContainerBuilderDebugDumpPass runs) and seems to be related to the usage of `strtolower` in `ParameterBag`: https://github.com/symfony/symfony/blob/a9d2f68ae9946000e2bcc3403d218ec0124f992a/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php#L114

**Comment by sroze** [comment]
@GromNaN the `ParameterBag` has changed in 3.4 and I can't reproduce with this version. I've [used your symfony-demo branch](https://github.com/sroze/symfony-demo/tree/utf-8-parameter-key) and [update to `3.4.x-dev`](https://github.com/sroze/symfony-demo/commit/ed7d05e9171586f19cac1f842480167ca8afabc8). Can you double check with your project it's all good in the 3.4 branch?

**Comment by eXtreme** [comment]
I haven't reported that yet but I have a similar problem with 3.3.x in  debug mode when doctrine/dbal exception is thrown with sql error and I use binary data as Uuid in the query. I mean, the exception that is shown tells me that "string is not in UTF-8" but of course the real exception is in the stacktrace so was not a big deal; but it shouldn't obviously work that way. I will reproduce that dbal exception tomorrow at work and provide more details here.

**Comment by nicolas-grekas** [comment]
@sroze is right, and there is nothing we can do before 3.4 sorry. But you'll be able to do it with 3.4 :)

**Comment by nicolas-grekas** [comment]
Oh, I just realized this might be locale sensitive, so with eg the C locale, it would work :)
