### ISSUE TITLE
PDO session timestamps out of range for postgres

### ISSUE THREAD

**Issue by mxp100** [symfony/symfony#24456]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.6+

With using PDO session handler with Postgres: PDO SQL error in PdoSessionHandler->close() - integer out of range, if gc_maxlifetime in php.ini with default value.

**Comment by Tobion** [comment]
What does you schema look like?

**Comment by Tobion** [comment]
It works on sqlfiddle. http://sqlfiddle.com/#!17/52d8c/2
So how to reproduce the problem?

**Comment by mxp100** [comment]
insert into sessions values ('abc', 2147483647, 2147483647);
DELETE FROM sessions WHERE ses_lifetime + ses_time < 1509428343;
select * from sessions;

**Comment by mxp100** [comment]
ses_lifetime = 2147483647 and you reproduce problem

**Comment by Tobion** [comment]
That's just the standard https://en.wikipedia.org/wiki/Year_2038_problem hit now if you use big lifetimes. So the proper fix might to use bigger integer column. As your solution will give you another 20 years to hit the problem again, it's better than nothing. ;)

**Comment by mxp100** [comment]
it's standard practice for unlimited sessions
