### ISSUE TITLE
ViolationMapper problem with acceptsErrors for not submitted values

### ISSUE THREAD

**Issue by kalinick** [symfony/symfony#24453]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.9

I have the problem with ViolationMapper. It skip values that was not submitted.  The problem appear in validation groups. If field is not submitted, but mentioned in validation group. Validator found constraint, but form not map it.

It can be solved by object direct validation. But here appear problem how combine form errors and object. Also i should validate object twice.

Can in method acceptsErrors, $form->isSubmitted() check be optional? Or ViolationMapper added to FormTypeValidatorExtension as service

**Comment by xabbuh** [comment]
Can you create a small example project that illustrates your problem? I am not sure if I really understood it.

**Comment by kalinick** [comment]
https://github.com/kalinick/violation-mapper-problem

test should not fail

https://github.com/kalinick/violation-mapper-problem/blob/master/tests/AppBundle/Controller/DefaultControllerTest.php

**Comment by kalinick** [comment]
It looks like responsibility of form is to test only form values. But it validate entity anyway. So it will be cool to have mechanizm to get from form full entity validation (not only form)

**Comment by hbouhadji-vp** [comment]
Did you found a solution to this issue since ? Thx @kalinick

**Comment by xabbuh** [comment]
Can you confirm that the changes proposed in #30265 will fix this issue?
