### ISSUE TITLE
[DI] YamlFileLoader throws ArgumentCountError

### ISSUE THREAD

**Issue by jakubkulhan** [symfony/symfony#24469]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 3.3.10
| PHP version | 7.1.8

`YamlFileLoader` catches deprecation error from from YAML parser [to add info about filename and then calls `$prevErrorHandler`](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L608-L612). The call misses PHP error handler's [5th argument - `errcontext`](http://php.net/set_error_handler), so `ArgumentCountError` is thrown.

E.g. Tracy uses `errcontext` argument - https://github.com/nette/tracy/blob/master/src/Tracy/Debugger.php#L364

**Comment by xabbuh** [comment]
see #24459 (in short: regards context argument is optional and will also be deprecated in PHP 7.2)

**Comment by xabbuh** [comment]
see nette/tracy#264 for the fix
