### ISSUE TITLE
Lost commits during merge?

### ISSUE THREAD

**Issue by webmake** [symfony/symfony#24487]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.2.8-3.3.0

I've just updated `symfony/http-foundation` dependency from 3.2.8 to 3.3.10, and tests at random place just broke, previously was working with expectation of `'http://localhost/test'`, now it became `'http://localhosttest'`. I'm using getUri method.

I made some research, so I updated to 3.2.13 (seems working version). then I updated to 3.3.0 version (broke), and tried to find in history who deleted `'/'`, but nothing interested found, just addition, but not removal, at commit https://github.com/symfony/http-foundation/commit/9077baf78efa2e78f596e9321e3c2db626fe92c7#diff-7edb274bc39ed8c493badba7dd278826
```diff
+        if ($requestUri !== '' && $requestUri[0] !== '/') {
+            $requestUri = '/'.$requestUri;
+        }
```
I'm using `getUri` method, which uses that discussed `preparePathInfo` method. More over I found another missing slashes commits:
https://github.com/symfony/http-foundation/commit/9077baf78efa2e78f596e9321e3c2db626fe92c7#diff-7edb274bc39ed8c493badba7dd278826
https://github.com/symfony/http-foundation/commit/4665cb98b5e11fb3b20692637bc9cb32a0992a1a#diff-7edb274bc39ed8c493badba7dd278826
https://github.com/symfony/http-foundation/commit/742db411c556b5e974812f6e414afa4b70aacd9a#diff-7edb274bc39ed8c493badba7dd278826L1849

Please clearify is it missing or deleted for real but no reference to it?

**Comment by webmake** [comment]
![image](https://user-images.githubusercontent.com/5016464/31317393-d744745a-ac48-11e7-8071-e0cad129cbf0.png)

According to my diff tool f594c12bc67603be7b0074defc2fdce5eaef76fe missing, 9077baf78efa2e78f596e9321e3c2db626fe92c7 contains, 4665cb98b5e11fb3b20692637bc9cb32a0992a1a contains,
742db411c556b5e974812f6e414afa4b70aacd9a contains,
8aaa59fd5ad8b878f8d0bf88f1b0a7004c333258 contains (initial commit)

**Comment by nicolas-grekas** [comment]
Might be a bad merge conflict resolution. Would you mind sending a fix with a test case please?

**Comment by webmake** [comment]
Test case for request:
```
public function testRequestMatches()
    {
        $inputArray = [
            'input1' => 'value1',
            'input2' => 'value2',
        ];

        $request = Request::create('test', 'POST', $inputArray);
        $expect = [
            'request_uri' => 'http://localhost/test',
            'request_method' => 'POST',
            'request_input' => $inputArray,
            'request_headers' => $request->headers,
        ];
        $actual = [
            'request_uri' => $request->getUri(),
            'request_method' => $request->getMethod(),
            'request_input' => $request->request->all(),
            'request_headers' => $request->headers,
        ];

        $this->assertEquals($expect, $actual);
    }
```
```
    protected function preparePathInfo()
    {
        $baseUrl = $this->getBaseUrl();

        if (null === ($requestUri = $this->getRequestUri())) {
            return '/';
        }

        // Remove the query string from REQUEST_URI
        if (false !== $pos = strpos($requestUri, '?')) {
            $requestUri = substr($requestUri, 0, $pos);
        }
        if ($requestUri !== '' && $requestUri[0] !== '/') {
            $requestUri = '/'.$requestUri;
        }

        $pathInfo = substr($requestUri, strlen($baseUrl));
        if (null !== $baseUrl && (false === $pathInfo || '' === $pathInfo)) {
            // If substr() returns false then PATH_INFO is set to an empty string
            return '/';
        } elseif (null === $baseUrl) {
            return $requestUri;
        }

        return (string) $pathInfo;
    }
```
Not sure only due `prepareBaseUrl`, because according commit it is necessary to add 
```
        if ($requestUri !== '' && $requestUri[0] !== '/') {
            $requestUri = '/'.$requestUri;
        }
```
but seems that works without it also

**Comment by Simperfit** [comment]
Could you please send a pull request with the following changes ?
