### ISSUE TITLE
Anonymous services for the fluent PHP format

### ISSUE THREAD

**Issue by unkind** [symfony/symfony#24493]
Sometimes I don't care about service name at all, e.g. when I decorate service or when I make service which is meant to be injected by CompilerPass (listeners, command handlers, ....). If I have multiple services for the same class, I'm not able to simply use class name as a service name.

Does it make sense to introduce something like anonymous services (`ServicesConfigurator`):
```php
    final public function anonymous(string $class)
    {
        return $this->set(uniqid(), $class)->private();
    }
```
? (service name should be determined for tests, but I want to show the idea).

Also current configuration of decorated services is not well-compatible with anonymous services above. I want to see something like

```php
return function (ContainerConfigurator $c) {
    $c->anonymous(CacheFooDecorator::class)
        ->decorate(Foo::class)
        ->args(
            decorated(), // injects Foo service
            ref('memcache'),
            // ...
        );
};
```

**Comment by nicolas-grekas** [comment]
What about allowing null as I'd for this?
Would be better IMHO.
PR should be submitted asap to make it into 3.4.

**Comment by unkind** [comment]
I'm afraid I don't see decent solution in the current design.

If I generate name for the anonymous service in the `ContainerBuilder`, it's not possible to create valid `Definition` structure because it depends on current service id in the `setDecoratedService`:

```php
    $s->anonymous('\Symfony\Component\DependencyInjection\Tests\Fixtures\StdClassDecorator')
        ->decorate('configured_service')
        ->args([
            decorated(), // <- here I have to replace this placeholder by `anon0.inner`
                         // but generated part ("anon0") doesn't exist yet
                         // or I have to overwrite $renamedId
            42
        ]);
```

The problem here is that API allows to make alias (`$renamedId`) for decorated service; however, I need to overwrite this alias in order to define decorator, I don't see other way to refer decorated service.

P.S. These traits are driving me nuts: no autocompletion, no current context. Probably, it's better to simply copy-paste (inline) these methods as they are very trivial.
P.P.S. `AbstractRecursivePass::processValue` probably should receive a `Definition` itself, because it makes impossible to process arguments if this logic depends on `Definition`, e.g. I need to know id of decorated service in order to process placeholder for decorated service (`DecoratedServiceArgument`).
