### ISSUE TITLE
[Twig] Sandbox integration undocumented

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#24497]
This is about how to properly integrate twig sandbox with the twig-bundles configuration.

The major problem with this is, that there is very limited documentation available about the sandbox itself and none regarding the integration with symfony. I think the sandbox is a very nice feature and should get some more love (at least an article in the symfony docs).

When i was evaluating the sandbox extension and how to integrate it, there are a few questions that came up, that would be best answered by the "designers intent":
- Should there be a new twig env for each sandbox "profile"?
  -> If yes, how to duplicate the default twig environment with all its integrated features (profiler, loaders, forms etc) without too much pain?
  -> If no, how to enable different sandbox "profiles"? Could this be a feature request against twig itself?
- A way to setup the policy (or multiple policies) by configuration (similar to https://github.com/intaro/twig-sandbox-bundle which is a good start, but isnt up to date and has its design flaws)
- If using the sandbox, the feature to be implemented is dealing with user supplied templates most of the time. There is a twig lint command and an article in the twig docs on how to validate the twig syntax. there are also some blog entries on how to create a validator for this. imho this should be included in the twig bundle just as the lint command is.

**Comment by stof** [comment]
Regarding the sandbox, I think the way to use it would depend on what you intend to do. You probably don't want to sandbox the main `twig` service (at least not globally), as this will likely break third-party bundles (unless your sandbox allows almost everything, but then it is kind of useless). Sandboxing the WebProfilerBundle template may cause issues for instance.
Personally, I never used the sandbox (as I don't have the need for user-supplied templates in my project), so I never investigated this in details.

I don't think including a validator for user-supplied templates in TwigBundle makes sense, as TwigBundle does not provide any management of user-supplied templates.

**Comment by backbone87** [comment]
> I don't think including a validator for user-supplied templates in TwigBundle makes sense, as TwigBundle does not provide any management of user-supplied templates.

Well this is sounds like "It isnt in it, because it isnt in it", but i get what you mean and thats exactly the purpose of this ticket: is it worth to improve builtin handling of user-supplied templating (but with more focus on the sandbox integration, since the validator is trivial).

And yes, i agree that the sandbox shouldnt be enabled by default in the default twig env. But copying the twig env into an own service is a lot of repeated work and not that easy because you cant just reuse the extension instances (they are stateful). Also i think that most use-cases for user-supplied templates definitely need different policies ("profiles") depending on usage context and authorization.

**Comment by stof** [comment]
> is it worth to improve builtin handling of user-supplied templating (but with more focus on the sandbox integration, since the validator is trivial).

Builtin support of user-supplied template would have to cover the persistence (otherwise there is not much builtin), and it may be hard to generalize it.

> Also i think that most use-cases for user-supplied templates definitely need different policies ("profiles") depending on usage context and authorization.

this makes it even harder to build this feature in Symfony itself (as it has no idea what your requirements for different profiles could be)

**Comment by backbone87** [comment]
> Builtin support of user-supplied template would have to cover the persistence (otherwise there is not much builtin), and it may be hard to generalize it.

This is basically providing a loader that is able to load from an entity property, no?

> this makes it even harder to build this feature in Symfony itself (as it has no idea what your requirements for different profiles could be)

From my PoV profiles are similar to validation groups in purpose. Lets say you have 3 policies, 1 for email templating, 1 for Document templating and 1 "admin" policy. So i could do something like this:
```twig
{% sandbox [ 'email', app.user.admin ? 'admin' : null ] %}
  {% include 'user_supplied_email_template_from_content_property_of_email_template_entity_with_id_1' %} 
{% endsandbox %}
```
The policies themselves still need to be configured by the dev (though helpful tools like the bundle from the OP has, would be nice)

**Comment by fabpot** [comment]
Closing as this is not something that should be supported in core.
