### ISSUE TITLE
Can't install symfony later version(3.3.10) on xampp later version(v3.2.2) becouse of ICU version.

### ISSUE THREAD

**Issue by laksithakumara** [symfony/symfony#24513]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

i using xampp v3.2.2 and PHP 7.1.9 on windows 10 x64, that xampp version comes with ICU 57

I need to upgrade it to 59 (request from symfony 3.3.10), so i downloaded ICU59 and copied all ICU*59*.dll to php directory and Apache bin directory, but it's not recognized. i know without recompiling 
php_intl.dll this will not work. is there are way to solve with issue ? 

Does the "php_intl.dll" have to be upgraded ?

Thanks

**Comment by NicoHaase** [comment]
Why do you need ICU 59? We're running v55.1 on our servers and are using sf 3.3.10 too, without any problems.

And, as a sidenote: if you have any problem using XAMPP, you should use their bugtracker :)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
