### ISSUE TITLE
[Security] logout remember_me user that has changed

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#24525]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | yes?
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.0

With #23882, a session token is logged out when the user has changed but not if you have a remember me token. When visiting a page when logged in after your account has changed, you lose the session token but fallback to an authenticated `RememberMeToken`.

Thoughts on how we can fix this?

**Comment by iltar** [comment]
How exactly is the user changed?

**Comment by kbond** [comment]
The is disabled. I am using the `EqualtableInterface`

**Comment by kbond** [comment]
I attempted a fix in PR #24536. I think it might be a BC break so I could use some help to eliminate that.

**Comment by kbond** [comment]
I ended up going a different direction with #24536. The user in `RememberMeToken` cannot be compared as there is no user to compare with. I ended up adding a missing `UserCheckerInterface::checkPostAuth()` call in `RememberMeAuthenticationProvider::authenticate()`

**Comment by egonolieux** [comment]
Maybe I am doing something wrong as this should be fixed, but I still have this problem using the `EqualtableInterface` in version 3.4.4 having the `logout_on_user_change` option set to `true`.

In my `isEqualTo` method I compare the user's email address, password and roles. If I change any of these values in the database, the session gets invalidated but the user remains logged in because of the remember me token:

```
[2018-03-01 01:43:10] request.INFO: Matched route "account". {"route":"account","route_parameters":{"_controller":"AppBundle\\Controller\\AccountController::accountAction","_route":"account"},"request_uri":"https://example.com/account","method":"GET"} []
[2018-03-01 01:43:10] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\RememberMeToken"} []
[2018-03-01 01:43:10] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"user@email.com","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-03-01 01:43:10] security.DEBUG: Remember-me cookie detected. [] []
[2018-03-01 01:43:10] security.INFO: Remember-me cookie accepted. [] []
[2018-03-01 01:43:10] security.DEBUG: Populated the token storage with a remember-me token. [] []
[2018-03-01 01:43:10] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
```

My security config is pretty basic:

```
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            anonymous: ~
            http_basic:
                provider: user_entity_provider
                realm: API
        content:
            pattern: ^/content
            security: false
        dev:
            pattern: ^/_profiler
            security: false
        main:
            provider: user_entity_provider
            stateless: false
            anonymous: ~
            logout_on_user_change: true
            form_login:
                login_path: /account/sign-in
                check_path: /account/sign-in
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager
            logout: 
                path: /account/sign-out
                target: /
            remember_me:
                name: REMEMBERME
                secret: '%secret%'
                lifetime: 31536000 # 1 year.

    providers:
        user_entity_provider:
            entity:
                class: AppBundle:User
                property: emailAddress
```

**Comment by chalasr** [comment]
@egonolieux please open a new issue if you think that you found a bug, comments on closed tickets aren't tracked.

**Comment by egonolieux** [comment]
@chalasr sorry for that, I was not sure to post it here or to open a new issue ;). https://github.com/symfony/symfony/issues/26379
