### ISSUE TITLE
Null class reserved in php7

### ISSUE THREAD

**Issue by elabayoub** [symfony/symfony#24538]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Hey,
I'am trying to use this repo (2.7) with php7, but unfortunately 'Null' can't be used as a name because it's reserved for php7. I have changed the name and it's usages manually its works, but i need a stable version for my composer without upgrading to symfony 3.
Best Ragards.

**Comment by xabbuh** [comment]
You need to use the `IsNull` constraint instead (see http://symfony.com/doc/2.7/reference/constraints/IsNull.html).

**Comment by elabayoub** [comment]
Thanks for your reply, you're right, but i'am talking about the class "\vendor\symfony\symfony\src\Symfony\Component\Validator\Constraints\Null.php"
When the projects builds it gives that error. Just if there is a way that composer ignore it or don't install it...
Regards.

**Comment by xabbuh** [comment]
Can you give the full error that you get including its stack trace?

**Comment by stof** [comment]
If you don't use this deprecated constraint, PHP has no reason to load the field (and so to break due to the reserved class name)

**Comment by NicoHaase** [comment]
@elabayoub , have you seen the big deprecation notice in the Null constraint? ;)

**Comment by elabayoub** [comment]
@xabbuh, @stof, thanks for your help you were right it isn't used so it doesn't cause any problem, the problem was another bundle.
@NicoHaase, yes i saw it and i didn't say that i'm using it ;). thanks
