### ISSUE TITLE
Create web-server component

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#24534]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 3.4

https://github.com/symfony/web-server-bundle

Currently web-server is implemented as a bundle, however its code is mostly generic and not related to Symfony Framework.

Is it possible to turn it into standalone Symfony component?

I managed to [run it without Symfony ](https://github.com/Chi-teck/web-server
)but my approach is a bit tricky and some redundant dependencies are still loaded (http-kernel).

Thanks.

**Comment by chalasr** [comment]
The bundle does need to register some services, so turning it into a component would involve to couple it to the framework via a `framework.web_server` config node, that has been rejected already (see e.g. https://github.com/symfony/symfony/pull/21190).

Perhaps we could consider extracting classes from the bundle to a component though. A 3rd party bundle should just be the glue integrating a library in the framework, and this is not the first asking for it.

**Comment by jakzal** [comment]
re #23771

**Comment by fabpot** [comment]
Closing as a duplicate
