### ISSUE TITLE
TwigDataCollector chokes on dynamic 'string' based templates

### ISSUE THREAD

**Issue by gnat42** [symfony/symfony#24540]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.4.x-dev

We have a situation where we deal with some user-editable templates. Think, templates that are merged with needed content, in this case legal documents. The user can then edit the automatically produced content and we create a pdf from that content.

Here's some of the code
```php
public function render($data, array $params)
{
        $templateConfig = $this->getPracticeTemplateConfig();
        $fullParams = array_merge($params,['template' => $templateConfig]);
        $submittedData = $this->splitIntoPages($data);

        $processedData = [];
        foreach ($submittedData as $content) {
            $endContent = (next($submittedData) == true) ? '<div style="page-break-after: always;"></div>' : '';
            $data = sprintf("{%% extends 'NSPracticeBundle:DocumentTemplate:content.html.twig' %%} {%% block content %%}%s%s{%% endblock %%}", $content, $endContent);
            $template = $this->twig->createTemplate($data);
            $processedData[] = $template->render($fullParams);
        }

        $data = sprintf('{%% extends \'NSPracticeBundle:DocumentTemplate:%s.html.twig\' %%} {%% block body %%}%s{%% endblock %%}',
            $templateConfig->getTwigTemplate(),
            implode('', $processedData)
        );

        $template = $this->twig->createTemplate($data);
        return $template->render($fullParams);
}
```
This all works perfectly. The issue is that in a dev environment the TwigDataCollector dies as its unable to locate template as returned by $this->twig->createTemplate($data) since its a 'string' instead of an actual path. 

It seems to me that I'm either solving my problem incorrectly or the lateCollect() function should be changed to (catching and ignoring the error):

```php
public function lateCollect()
    {
        $this->data['profile'] = serialize($this->profile);
        $this->data['template_paths'] = array();

        $templateFinder = function (Profile $profile) use (&$templateFinder) {
            try {
                if ($profile->isTemplate() && $template = $this->twig->load($profile->getName())->getSourceContext()->getPath()) {
                    $this->data['template_paths'][$profile->getName()] = $template;
                }
                foreach ($profile as $p) {
                    $templateFinder($p);
                }
            } catch (\Twig_Error_Loader $exception) {
            }
        };
        $templateFinder($this->profile);
    }
```

**Comment by gerryvdm** [comment]
Can confirm, just rendering a template from source seems to crash the profiler.


(1/1) Twig_Error_LoaderUnable to find template "__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" (looked into: /users/vandermaeseng/export/project/skynet/zend/applications/cms-newsletter/app/Resources/views, /users/vandermaeseng/export/project/skynet/zend/applications/cms-newsletter/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).
--
in Filesystem.php (line 226)
at Twig_Loader_Filesystem->findTemplate('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in FilesystemLoader.php (line 78)
at FilesystemLoader->findTemplate('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in Filesystem.php (line 143)
at Twig_Loader_Filesystem->getCacheKey('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in Environment.php (line 270)
at Twig_Environment->getTemplateClass('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in Environment.php (line 350)
at Twig_Environment->loadTemplate('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in Environment.php (line 328)
at Twig_Environment->load('__string_template__9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')in TwigDataCollector.php (line 66)
at TwigDataCollector->Symfony\Bridge\Twig\DataCollector\{closure}(object(Twig_Profiler_Profile))in TwigDataCollector.php (line 70)
at TwigDataCollector->Symfony\Bridge\Twig\DataCollector\{closure}(object(Twig_Profiler_Profile))in TwigDataCollector.php (line 73)
at TwigDataCollector->lateCollect()in Profiler.php (line 121)
at Profiler->saveProfile(object(Profile))in ProfilerListener.php (line 117)
at ProfilerListener->onKernelTerminate(object(PostResponseEvent), 'kernel.terminate', object(TraceableEventDispatcher))
at call_user_func(array(object(ProfilerListener), 'onKernelTerminate'), object(PostResponseEvent), 'kernel.terminate',object(TraceableEventDispatcher))in WrappedListener.php (line 104)
at WrappedListener->__invoke(object(PostResponseEvent), 'kernel.terminate', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(PostResponseEvent), 'kernel.terminate', object(ContainerAwareEventDispatcher))in EventDispatcher.php (line 212)
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener)), 'kernel.terminate', object(PostResponseEvent))in EventDispatcher.php (line 44)
at EventDispatcher->dispatch('kernel.terminate', object(PostResponseEvent))in TraceableEventDispatcher.php (line 144)
at TraceableEventDispatcher->dispatch('kernel.terminate', object(PostResponseEvent))in HttpKernel.php (line 88)
at HttpKernel->terminate(object(Request), object(Response))in Kernel.php (line 151)
at Kernel->terminate(object(Request), object(Response))in app_dev.php (line 32)

**Comment by ro0NL** [comment]
Thanks for reporting, will look into that :+1: 

ref https://github.com/symfony/symfony/pull/24236 / 3.4
