### ISSUE TITLE
Failed to start the session because headers have already been sent by "" at line 0.

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#24544]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Level | Channel | Message
-- | -- | --
INFO                12:11:19 | php | User Deprecated: The JavierEguiluz\Bundle\EasyAdminBundle\EasyAdminBundle class is deprecated since version 1.16 and will be removed in 2.0. Use the EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle class instead.
INFO                12:11:19 | request | Matched route "project_submit_draft".
CRITICAL                12:11:19 | request | Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "" at line 0." at W:\OpenServer\domains\af\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 138
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "EasyCorp\Bundle\EasyAdminBundle\EventListener\ControllerListener::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RequestDataCollector::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
DEBUG                12:11:19 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".

**Comment by fabpot** [comment]
For support questions, check https://symfony.com/support

This does not look like a framework issue.
