### ISSUE TITLE
Update from 2.8.27 to 2.8.28 includes BC break in MergeCollectionListener

### ISSUE THREAD

**Issue by rcwsr** [symfony/symfony#24550]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.8.28

Just updated from 2.8.27 to 2.8.28 and some of our tests have started failing, I'm not sure exactly why yet, but I've narrowed it down to this change https://github.com/symfony/symfony/commit/aaba6b4c2bdbe2d4a92754ea4f9a43570af2ff16#diff-eda3319cba753bdf0b2d298b76a64531R83. For our tests that fail `$dataToMergeInto` is an empty array.

**Comment by yceruto** [comment]
Could you show us the test case, please?

**Comment by jakzal** [comment]
@rcwsr are you able to provide more details please? A small, failing test case would be nice.

**Comment by rcwsr** [comment]
Sorry, I'll try and put something together tomorrow

**Comment by nicolas-grekas** [comment]
Closing because of lack of feedback. Please resubmit with more details if you can.
