### ISSUE TITLE
[FrameworkBundle] Serializer not work without PropertyAccess component

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#24553]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

FrameworkBundle assumes that `PropertyAccess` component is present
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L139

We need to add it as a dependency or optionally register `serializer.normalizer.object` service

**Comment by weaverryan** [comment]
Related to #20588, but slightly different

**Comment by BoShurik** [comment]
I still can't use it.

`bin/console` throws an exception 
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "PropertyAccessor" from namespace "Symfony\Component\PropertyAccess".
Did you forget a "use" statement for another namespace? in /Users/boshurik/Projects/symfony-property-access-issue/var/cache/dev/srcDevDebugProjectContainer.php:435
```

I tried to remove `ObjectNormalizer` from container. Add to `Kernel` `CompilerPassInterface`
```
/**
 * @inheritDoc
 */
public function process(ContainerBuilder $container)
{
    $container->removeDefinition('serializer.normalizer.object');
    $container->removeDefinition(ObjectNormalizer::class);
}
```
but no results

**Comment by BoShurik** [comment]
Got it. I should move compiler pass from kernel to separate class and set priority to maximum (execute before object.normalizer tag pass)
```
/**
 * @inheritDoc
 */
protected function build(ContainerBuilder $container)
{
    $container->addCompilerPass(new CompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 1000);
}
```
