### ISSUE TITLE
[Form] FormInterface::getPropertyPath() return type incosistency

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#24560]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3

In [FormInterface::getPropertyPath()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormInterface.php#L176) the return type is not nullable.

But its implementation in [Form::getPropertyPath()](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L215) actually returns null. This costed me a `Call to a member function getElements() on null` since I was relying on IDE autocomplete.

**Comment by Simperfit** [comment]
Should we update the interface, or maybe change the behaviour when retuning null WDYT ?

**Comment by vudaltsov** [comment]
`null` is returned when the form has an empty name. It allows for unprefixed children.

```php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class IndexController extends AbstractController
{
    /**
     * @Route(name="index")
     * @Template()
     */
    public function indexAction()
    {
        $form = $this->get('form.factory')
            ->createNamedBuilder('')
            ->add('text', TextType::class)
            ->getForm();

        return [
            'form' => $form->createView(),
        ];
    }
}
```

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <form name="" method="post">
            <label for="text">Text</label>
            <input type="text" id="text" name="text">
        </form>
    </body>
</html>
```
We cannot change this behaviour, obviously.
