### ISSUE TITLE
[Forms] Type options are shared amount instances

### ISSUE THREAD

**Issue by olvlvl** [symfony/symfony#24561]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8 - dev-master

Hi,

After 2 hours tinkering around `symfony/forms` code to investigate a strange behavior I discovered that a type configuration is _shared_ between all form instances, which might be ok until you use `data` to provide a default instance. Actually, it's very problematic when said type is used in a collection. I couldn't figure out why all the items in my collection were ending have the same values…

This is also an issue when you want to provide an entity with a generated identifier as default value. Please consider the following code, subsequent submits in a same session would override the previous one…

```php
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data' => new Recipe(new ObjectID)
            'data_class' => Recipe::class,
        ]);
    }
```

I would expect this behavior if `AbstractType::configureOptions()` was a static method, but it is not.

Also the documentation doesn't make mention of this: https://symfony.com/doc/current/reference/forms/types/form.html#data

Now I'm not sure how to provide initialized instances, maybe I'm using `data` is very terrible ways :) 

What do you think?

**Comment by iltar** [comment]
You should probably just bind the data when creating the form and pass that to the form factory. I think this is something that should be be documented as something to not due to to the issue you described.

**Comment by dmaicher** [comment]
This is expected behavior imho.

I usually achieve this using form events. If you bind a listener to `FormEvents::PRE_SET_DATA` you can set the data you want on the event.

**Comment by iltar** [comment]
Or just pass the data argument when building the form in those methods: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormFactory.php#L16

Using a form event is quite overkill.
