### ISSUE TITLE
The debug:container command is confusing

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#24562]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Would have been great for 3.4 but I guess it's too late now :)

When one runs the `debug:container` command, the list of *public* services is displayed.
If the `--show-private` flag is passed, private services are displayed also.

This logic is build on / suggests a false assumption: that public services are more for "userland", while private services are more "internal". This is completely wrong. Of course, the confusion comes from the word "private", that convey this semantic when applied on classes.

I think we need a new semantic that would allow devs to discover more easilly which services/aliases they can reference or type-hint for (when using autowiring), vs which services are more internal and are not meant to be referenced.

**Comment by weaverryan** [comment]
Also, `debug:container --types` is a pretty long command... for what is probably (currently) the most useful way to run the command. I'd like to make that `debug:types` (even if that's just a shortcut).

**Comment by javiereguiluz** [comment]
I find `debug:services` easier to understand than `debug:types` ("types" is too generic ... and problematic in Symfony because Symfony Forms use "types" instead of "fields").

**Comment by weaverryan** [comment]
Yea.. so maybe debug:services would need to behave different in the future and show “types” by default only, as the types are what you want most of the time. Anyways, we need to give it some thought.

**Comment by ro0NL** [comment]
about the "new semantic"; i was thinking of `autowireable = true|false` (per definition or with _defaults). Allowing to exclude a class named service from autowiring discovery. Exposed with `debug:container/services --autowireable`, but keeping `debug:autowiring` is worth it IMHO.

for public/private services.. we cant really deny the semantic right? but i do think inversing might make more sense (`--show-public|public|exposed`).
