### ISSUE TITLE
How to handle “complex” dynamic forms with multiple possible actions per field?

### ISSUE THREAD

**Issue by SDPrio** [symfony/symfony#24572]
| Feature request? | yes
| RFC?                     | yes
| Symfony version  | 2.8

I am working on a Symfony 2.8 based web app project and trying to create a form, which allows to return multiple different results/fields/formats depending on previous selections within the form.

To keep it simple let us assume the web app is a simple address book which allows to manage any number of Contacts. Each Contacts is assigned to a Category, e.g. "Business", "Family", "Friends", "School", etc.

It should be possible to import new Contacts in CSV format. In the first step the uploaded CSV file is parsed and the app checks if all used categories are valid == exist within the app.

For non existing categories, the user should have three options:

- Remove all entries which use this category form the import
- Re-assign an existing category that should be used instead, e.g. "Private" ==> "Family"
- Add the missing category to the web app. Beside the name additional details like icon and color need to be selected

**How can this be done?**

Let us assume, that there are invalid categories "Private", "Company" and "Club" in the import data. Now I would like to present a form, where the user could pick for each category on the choices described above:

```
Private    Remove|Assign|Create
Company    Remove|Assign|Create
Club       Remove|Assign|Create
```

Depending on the selection, additional form fields will become visible:

```
Private    REMOVE|Assign|Create    Do not import these entries (text hint)
Company    Remove|ASSIGN|Create    ==> Business (selected from DropDown box)
Club       Remove|Assign|CREATE    Textfield: Name, Dropdown: Icon, Dropdown: Color
```

Of course it is no problem to build this list and so switch between the options using some JavaScript.

**BUT: What is the correct way to pass the result back to Symfony? Can this be done by using (custom) FormTypes?**

I found different tutorials on how to create dynamic forms depending on existing data or on data that was previously submitted by the user (e.g. [here](http://symfony.com/doc/2.8/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms))

The problem is, that the data that is returned/posted for each category has no unique structure but depends on the selected action.

How can i handle that for one category a BOOL value is returned (delete = yes) while other receive a string (assign "Business") or complex data (name, icon, color)...

**Can this be done with Symfony or do i have to build my own data structure (e.g. some JSON) from the user selection and post this back to the WebApp?**

In general I would need something like the `form.groups.vars.prototype` which is available when working with collections. Only difference is, that I do not need prototypes for collection items but for different return types (BOOL = delete, STRING = assign, Name+Icon+Color = create, etc.). 

Depending on the delete/assign/create selection for each item I could then replace the corresponding action with the content from action-prototype.

**Is it possible to solve this kind of scenario with Symfony forms or do I have to work on a completely custom solution?**

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by SDPrio** [comment]
Well, I think this more like a feature request, since I do not think that this possible yet, is it?

**Comment by ostrolucky** [comment]
Seems solvable to me. Declare those submit buttons in FormType, then you can find out which one has been pressed inside submit listener and decide which custom model transformer to use. For further discussion use support channels as already advised. 

For feature request, your post is too abstract anyway. You are not suggesting any concrete idea. I would close this.

**Comment by SDPrio** [comment]
This is not about having different submit buttons per entry/item but to have different possible return types per entry/item and only one global submit button. 

The question is, how to create such a form and how to handle it. Of course I could a custom FormType which includes a choice field (Remove/Assign/Create), a selection box to choose the assigned category and all form fields to create a new category.

When submitted I would then check the value of the choice field and use the other fields accordingly (ignore all other field is Remove was selected, assign the selected category, etc.) 

Question is, how to efficiently create and organize this form? Creating all form fields for any possible return type for all items is a lot of work. It would be far better to just create prototypes for the possible return types and toggle them dynamically using JS, wouldn't it?

Problem is, that prototypes can only created for CollectionTypes which allow adding items. But this is not about adding items but to toggle between different return types. Is this possible? I assume not. Would that not be a useful feature?

**Comment by xabbuh** [comment]
@SDPrio Can you describe how the API should look like to support your use case? I mean how would you like to build your form? So far I don't really understand what are the missing parts here. A more concrete example might help.

**Comment by xabbuh** [comment]
I am closing here for now as it is not really clear what the requested feature is. But we can of course reopen when there is more information.
