### ISSUE TITLE
[VarDumper] Code excerpts and trailing commas

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#24581]
| Q                | A
| ---------------- | -----
| Bug report?      | yesish
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

When using the `DUMP_COMMA_SEPARATOR` or `DUMP_COMMA_SEPARATOR` flags, a trailing comma is added to each line. But when dumping an exception, adding a comma at the end of each line of the code excerpt looks a bit unexpected to me:

<img width="580" alt="screenshot 2017-10-16 a 22 40 59" src="https://user-images.githubusercontent.com/2211145/31634697-ac88a326-b2c4-11e7-9e19-68813c82318c.PNG">

```php
RuntimeException {
  #message: "foo",
  #code: 0,
  #file: "./src/Symfony/Component/VarDumper/Tests/Dumper/CliDumperTest.php",
  #line: 181,
  trace: {
    ./src/Symfony/Component/VarDumper/Tests/Dumper/CliDumperTest.php:181 {
      › ,
      › $ex = new \RuntimeException('foo');,
      › ,
    },
    Symfony\Component\VarDumper\Tests\Dumper\CliDumperTest->testDumpWithCommaFlagsAndExceptionCodeExcerpt() {},
    ./.phpunit/phpunit-6.0/src/Framework/TestCase.php:1042 { …},
    ./.phpunit/phpunit-6.0/src/Framework/TestCase.php:901 { …},
  },
}
```

See https://github.com/ogizanagi/symfony/commit/1f624ae410671cad3623a59996af1633b55eb624 for a simple test case reproducing this.

Does it worth an improvement?

**Comment by javiereguiluz** [comment]
I didn't know that `DUMP_COMMA_SEPARATOR` exist! What's the reason behind it? If it's to make the dumped contents a valid JSON object, it doesn't look like a valid JSON object yet. If it's pure aesthetics, it's complicating things for no good reason.

I'd propose either to remove this flag ... or improve as `DUMP_AS_JSON_OBJECT`.

**Comment by ogizanagi** [comment]
It's actually merely aesthetics in my case; I do prefer:
```php
[
  1,
  2,
  3,
]
```

over:

```php
[
  1
  2
  3
]
```

but @lyrixx mentioned in the original PR introducing it (#21653) the use case of displaying a dump on one line, hence the comma separator becomes more than an aesthetics thing. But I actually don't know the way he proceeded to display it in one line.

**Comment by lyrixx** [comment]
Hello.

For the record, I added this feature to be able to write a dump on one line.
It's used in the [ConsoleFormatter.php](https://github.com/symfony/symfony/blob/b935b93c7ae6fc9360765756632472a85f7bda7a/src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php#L78) ; [related PR](https://github.com/symfony/symfony/pull/21705)

**Comment by Simperfit** [comment]
I can try to make the PR if you want @ogizanagi.
