### ISSUE TITLE
Call to a member function has() on null

### ISSUE THREAD

**Issue by bettinz** [symfony/symfony#24580]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hello, I'm trying to call an action from a controller to another controller.
So I've UserController and "getRegistrationNumberAction(WorkEvent $event)" and from EventController I call

$number= $this->get(UserController::class)->getRegistrationNumberAction($workEvent);
The error appear here:
$em= $this->getDoctrine()->getManager();
and the error is: Call to a member function has() on null

I've modified services.yml with new symfony configurations (autowire, _defaults, etc) so I can't understand what is wrong. Can you help me?
PS: If I try to dump $this->get(UserController::class) it dump null.
Maybe this will help to understand that page of documentation: http://symfony.com/doc/current/service_container/3.3-di-changes.html (the error message doesn't help really much).
Thanks

Stack:
```
Symfony\Component\Debug\Exception\FatalThrowableError:
Call to a member function has() on null

  at vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:356
  at Symfony\Bundle\FrameworkBundle\Controller\Controller->getDoctrine()
     (src/AppBundle/Controller/UserController.php:294)
  at AppBundle\Controller\UserController->getRegistrationNumberAction(object(WorkEvent))
     (src/AppBundle/Controller/WorkEventController.php:81)
  at AppBundle\Controller\WorkEventController->addResultAction(object(WorkEvent), object(Request))
  at call_user_func_array(array(object(WorkEventController), 'addResultAction'), array(object(WorkEvent), object(Request)))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:30)
  at require('/Users/bettinz/PhpstormProjects/teamdog/web/app_dev.php')
     (vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:42)
```

**Comment by bettinz** [comment]
Solved with this at start of UserController:
```php
private $em;

    public function __construct(EntityManager $entityManager)
    {
        $this->em= $entityManager;
    }
```
and in getRegistrationNumber:
```
$this->em->getRepository
```
Is that the correct way to proceed? Thanks

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
