### ISSUE TITLE
Problem with share authentification cookies

### ISSUE THREAD

**Issue by Tommy10802** [symfony/symfony#24601]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2

Hello I have a little problem with authentification cookie value which is created and stored in browser after success login.
I have 2 symfony web aplication hosted on same domains at different subdomain.
When i authentificate on site A and copy value of cookie and replace this value on site B i am authentificated. Where is a problem? Is there not any unique key or something like that which is hashed into cookie value on every symfony application?

Thanks

**Comment by NicoHaase** [comment]
If this is running on the same server, both applications share common sessions. Maybe you should override the session file directory as documented on http://symfony.com/doc/current/session/sessions_directory.html

**Comment by Tommy10802** [comment]
Thanks for fast reply :)

yes, both applications is running on same server.
I dont think this is a problem.
Because of when i logged on server A  with user admin cookie name is
`d06aeb67c2f9e2ce44239977dc1480ad` and its value `362obuc28nl1efev1795d7a7n3`.
On server B cookie name (`438172e6697377a2637835d949dd97bf`) is different, what is good becasue this sessionName is generated base on unique application secret key.
The problem is when i copy cookie value `362obuc28nl1efev1795d7a7n3` from site A and set it manually into browser with cookie name from server B and try to access on server B, i am logged as admin user because user with "admin" login name exist on server B too. And this is not desirable i think

**Comment by Tommy10802** [comment]
Thanks a lot, it helps :)
