### ISSUE TITLE
Deprecations causing big performance hit in dev ProfilerListener

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#24625]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x

When you trigger a lot of deprecations, they will be stored in the profiler. However, this causes a massive performance hit on all dev pages triggering those. from 5 to 89 deprecations, causes the profiler listener to go from roughly 300 to 900ms. 

For 3.4, this deprecation is causing most issues: https://github.com/symfony/symfony/blob/1f92e459db0efd2576eaa63a4fa0fe39e68b32dd/src/Symfony/Component/DependencyInjection/Container.php#L277

**Pre deprecation**
![image](https://user-images.githubusercontent.com/1754678/31773443-1124bb60-b4e3-11e7-818e-3f887013faee.png)

**Post deprecation**
![image](https://user-images.githubusercontent.com/1754678/31773456-1ea4c5aa-b4e3-11e7-85ed-b7e70cd255b0.png)

The cause seems to be the amount of unserialize function calls in the Stub. `Stub::unserialize()` goes from `4870` to `23570`.

**Pre deprecation**
![image](https://user-images.githubusercontent.com/1754678/31773689-c768d348-b4e3-11e7-8183-1c00a511d06f.png)

**Post deprecation**
![image](https://user-images.githubusercontent.com/1754678/31773651-b01bc236-b4e3-11e7-8ff3-830e97264d26.png)

**Comment by nicolas-grekas** [comment]
You should look into *what* is doing "unserialize". I'm not sure it's legitimate to unserialize at all at this stage. Without a real (Blackfire) profile, you're on your own :)

**Comment by iltar** [comment]
Hmm you were right about unserialize, this was the result of the second app_dev call, which is from the toolbar. I'm diving into the actual result now and seeing a different result. Sadly I'm still not able to install blackfire io, so I will have to do with webgrind to analyze it. If you want, I can supply the cachegrind files of the screenshots below privately. I believe this issue should be 100% reproducible by triggering a load of deprecations.

**Total pre-deprecation**
![image](https://user-images.githubusercontent.com/1754678/31810618-bc3dacac-b57c-11e7-82e3-96c450dd9e50.png)

**Total post-deprecation**
![image](https://user-images.githubusercontent.com/1754678/31810628-c5091d6c-b57c-11e7-9186-8c314ee93b72.png)

**Function calls pre-deprecation**
![image](https://user-images.githubusercontent.com/1754678/31811725-dd6590da-b580-11e7-83df-6023345d2fdb.png)

**Function calls post-deprecation**
![image](https://user-images.githubusercontent.com/1754678/31811707-d197a8ec-b580-11e7-8006-64529867b8df.png)

**Function Graph pre-deprecation**
![index 1](https://user-images.githubusercontent.com/1754678/31811788-2893182a-b581-11e7-9fb2-1697b6b0fd02.png)

**Function Graph post-deprecation**
![index](https://user-images.githubusercontent.com/1754678/31811087-8622d820-b57e-11e7-8b71-e0714f9b18e8.png)

**Callstack of the LoggerDataCollector**
![image](https://user-images.githubusercontent.com/1754678/31812190-7c4f1d0a-b582-11e7-9bca-e66f2853c913.png)

**Comment by nicolas-grekas** [comment]
How's the log panel like? Can you fully expand one deprecation listed there to see what's nested in the collected stack trace?

**Comment by iltar** [comment]
I can provide you the exact data on Tuesday earliest. It's basically the exception message with some additional information and a context stored in it (line numbers etc). From what I can tell, all the data needed for exception messages. Each item in this array had 6~8, maybe more rows per array item, containing at least the context array with multiple rows.

**Comment by javiereguiluz** [comment]
Same here. With just 63 deprecations, the profiler listener more than triples its execution time:

![profiler-listener](https://user-images.githubusercontent.com/73419/31876646-b76e0d12-b7d3-11e7-875a-10bf51cd9d6e.png)

And here is the stack trace of one of those deprecations:

![trace](https://user-images.githubusercontent.com/73419/31876661-c478148a-b7d3-11e7-9efa-09b7c8755a01.png)

**Comment by iltar** [comment]
@nicolas-grekas, here's what's actually in there (quite a lot).

![image](https://user-images.githubusercontent.com/1754678/31927214-56c6b476-b893-11e7-8c61-10fb395b2b7c.png)

**Comment by nicolas-grekas** [comment]
Please report behavior with #24895

**Comment by javiereguiluz** [comment]
I've noticed a significant improvement after testing #24895 changes. Thanks!

**Comment by iltar** [comment]
@fabpot the provided patch did not fix anything for this ticket, it's still an issue

**Comment by nicolas-grekas** [comment]
@iltar can you try this patch?

```diff
--- a/src/Symfony/Component/Debug/ErrorHandler.php
+++ b/src/Symfony/Component/Debug/ErrorHandler.php
@@ -715,7 +715,7 @@ class ErrorHandler
         }
         if (!($throw || $this->scopedErrors & $type)) {
             for ($i = 0; isset($lightTrace[$i]); ++$i) {
-                unset($lightTrace[$i]['args']);
+                unset($lightTrace[$i]['args'], $lightTrace[$i]['object']);
             }
         }
```

**Comment by nicolas-grekas** [comment]
@iltar this one:

```diff
--- a/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php
+++ b/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php
@@ -86,7 +86,7 @@ class DebugHandlersListener implements EventSubscriberInterface
                         $handler->screamAt($levels);
                     }
                     if ($this->scope) {
-                        $handler->scopeAt($this->levels);
+                        $handler->scopeAt($this->levels & ~E_USER_DEPRECATED & ~E_DEPRECATED);
                     } else {
                         $handler->scopeAt(0, true);
                     }
```

**Comment by iltar** [comment]
Applying just the second patch reduced it by 100~150ms, not optimal, but better.

Old (for reference):
![](https://user-images.githubusercontent.com/1754678/32655139-b0fd1792-c60c-11e7-8b0d-d60ff1b17e04.png)

New:
![image](https://user-images.githubusercontent.com/1754678/32668336-8ff3162e-c63d-11e7-911d-45fdf8b02495.png)

**Comment by nicolas-grekas** [comment]
OK, fixed in #24910 then.
With no better profiles, I'd consider this issue as fixed now, as the deprecation-related part has been optimized twice, and nothing in the posted screenshot is actionable.

**Comment by iltar** [comment]
Yes, it's already a good improvement as it reduced the time in the profile listener by 20~30%, so that's awesome, thanks!

I hope that I can use blackfireio in the near future instead

**Comment by nicolas-grekas** [comment]
An additional yet important note:
IN DEV ALSO
further perf can be achieved by enabling the `container.dumper.inline_class_loader` parameter.
The reason for this is that the DebugClassLoader will be skipped for services on the hot path, which has a significant impact.

**Comment by nicolas-grekas** [comment]
@iltar would love to ear how the param improves your setup

**Comment by iltar** [comment]
I'll give that one a shot on Monday, I've seen it come by and it looks really promising!

**Comment by iltar** [comment]
@nicolas-grekas I can confirm that performance is increased by that setting. My local env (7.1, opcache, xdebug), the average request time is down by 100\~300ms on the same page. The profiler listener is about 30\~60ms faster. What I mainly noticed, is that the page loads are very similar: 850ms\~950ms rather than 950\~1250.

Having a big project with a lot of files, this will certainly improve performance for at least dev. 

Sadly we're only running new relic on 1 production server, so I won't know the actual performance gain of 3.4 in prod with properly configured opcache. In my local environment I don't notice a real change with that setting, but I have no proper profiling available here.

**Comment by iltar** [comment]
Forgot to add my cachegrind result:

![image](https://user-images.githubusercontent.com/1754678/32714579-dcfa0be0-c84e-11e7-80eb-c106ef7b87c5.png)

**Comment by zavgarr** [comment]
For All looking for Out of memory exception after deploy - check permissions on var/cache and var/log directories
