### ISSUE TITLE
Twig_Extension::getName() is deprecated

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24627]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

After upgrading to Symfony 3.4 beta1, I'm seeing a ton of deprecations like this one:

```
The "Twig_Extension::getName()" method is deprecated since 1.26 (to be removed
in 2.0), not used anymore internally. You should not extend it from
"Symfony\Bridge\Twig\Extension\LogoutUrlExtension"
```

@sstok suggested on the Symfony Slack chat to require Twig 1.26 as the minimum version, because that's the one which deprecated `getName()` and the first version where we can remove it without making the applications fail.

**Comment by chalasr** [comment]
Duplicate of #24522 :)

**Comment by javiereguiluz** [comment]
Closing then. I'm sorry!
