### ISSUE TITLE
[Validator] MetaDataFactory cache is always null, resulting in no cache

### ISSUE THREAD

**Issue by MichaelHindley** [symfony/symfony#24643]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.BETA1

I have a class annotated with Constraints like so:

```php
class Recipe
{
    /**
     * @Serializer\Type("string")
     * @Assert\Length(min="10", max="20")
     *
     * @var string
     */
    private $title;
}
```

When validating the class, the Constraints work as expected.

However, when I want to use the MetaData for the Class, I notice it is not in the Cache.

Breakpointing gives this result:

![image](https://user-images.githubusercontent.com/1016639/31824572-b49bd28e-b5af-11e7-8c45-455cd8b57b6f.png)

Stack trace:

![image](https://user-images.githubusercontent.com/1016639/31824595-c7d5a0a0-b5af-11e7-8b5f-63a6af427732.png)

I have tried with APCu and without. 
From what I could gather, if $this->cache is null in the MetaDataFactory, the cache logic is never triggered.

Trying to get the Validator service in a Controller, and getting the Classes MetaData from cache, results in null, but the Class gets Validated each request.

My use Case is using the MetaData for API Documentation, the same way I am using JMSSerializer MetaData. The Serializer MetaData is in the cache, but the Validator is not, and from what I can see, will never enter the write statement since the "driver" is always null, at least from all the Validator classes I've breakpointed through.

**Comment by stof** [comment]
The Validator cache is disabled in debug mode currently (because the cache itself does not have a debug mode to auto-refresh it on metadata change):

https://github.com/symfony/symfony/blob/4c414d8136f0684aebd1e92d3f75eab65a6092f9/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1096-L1098

**Comment by MichaelHindley** [comment]
Ah great, thanks for your input!

**Comment by xabbuh** [comment]
closing here as there is no bug
