### ISSUE TITLE
Symfony crashes after login

### ISSUE THREAD

**Issue by Ananaskirsche** [symfony/symfony#24647]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

When following the guide to write a login page in [the Symfony documentation](http://symfony.com/doc/current/security/form_login_setup.html) and loading the users from my database, Symfony returns a HTTP 500 error. After that the webserver freezes.
I am using a ArchLinux 4.13.7-1 x86_64 with PHP 7.1.10. My database is a MariaDB 10.1.28.
<br />
When the crash happens there are no real information in the debug log except the following line:
`[Thu Sep 21 15:32:23 2017] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0`
<br />
I found out, that the issue does not occure when writing the users login credentials in the security.yml. This issue does also occure when using a Apache 2.4.28 webserver. Increasing the memory limit in the php.ini does not resolve the issue. Instead Symfony fills the maximum amount of memory with data.  For me, I have downgraded to Symfony version 3.3.2, where this issue does not occure, using the same code from the documentation.

**Comment by xabbuh** [comment]
Are you able to provide a small example project that allows to reproduce your issue?

**Comment by Ananaskirsche** [comment]
Since I am new to Symfony I don't know how to do that. But I opened a repository [here](https://github.com/Ananaskirsche/SymfonyCrash). I hope this is ok too....

**Comment by xabbuh** [comment]
Your `User` class looks suspicious to me:

```php
public function serialize()
{
    return $this->serialize(array(
        $this->id,
        $this->username,
        $this->password,
    ));
}

public function unserialize($serialized)
{
    list(
        $this->id,
        $this->username,
        $this->password,
    ) = $this->unserialize($serialized);
}
```

Your `serialize()` and `unserialize()` methods will call themselves recursively over and over again.

You will probably just want to call PHP's `serialize()` and `unserialize()` functions instead:


```php
public function serialize()
{
    return serialize(array(
        $this->id,
        $this->username,
        $this->password,
    ));
}

public function unserialize($serialized)
{
    list(
        $this->id,
        $this->username,
        $this->password,
    ) = unserialize($serialized);
}
```

I am going to close here for now. But we can of course reopen if that's not the only issue.

**Comment by Abdelmonem-BEN-NACEUR** [comment]
@xabbuh thank you :D, you saved my time.

**Comment by RUmanchik** [comment]
@xabbuh thank you. I ve had the same problem with $this->unserialize looping.

**Comment by heardofdezz** [comment]
#37684
