### ISSUE TITLE
The required option resets the FormView

### ISSUE THREAD

**Issue by pengend** [symfony/symfony#24646]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

My method `buildForm` :
```
        $builder
            ->add('radioProperty', EntityType::class, [
                'required' => false,
...
```
My method `finishView` :
```
...
        $propertyView = $view->children['radioProperty'];
        foreach ($propertyView->children as $key => $child) {
            $child->vars['residenceName'] = $property->getResidence()->getName();
...
```
I have a strange issue with the option `required`, when I set it to `false`, it seems to reset all view vars on the child, and I have an error like this : `Key "residenceName" for array with keys "value, attr, form, id, name, full_name, disabled, label, label_format, multipart, block_prefixes, unique_block_prefix, translation_domain, cache_key, errors, valid, data, required, size, label_attr, compound, method, action, submitted, grid, checked" does not exist.`

Btw, if I set it to `true`, it works perfectly.

**Comment by xabbuh** [comment]
Are you able to provide a small project allowing it to reproduce your issue? Since you seem to deal with parent/child relationships of your form types it could be related to how you set the data.

**Comment by Simperfit** [comment]
@pengend Could you please respond to @xabbuh's comment ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
