### ISSUE TITLE
Requiring LazyLoadingValueHolderFactoryV1 causes fatal error due to method signature incompatibility

### ISSUE THREAD

**Issue by TysonAndre** [symfony/symfony#24648]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

Remediation: Fix the file or remove it (or document that it's broken). Since I don't see any pull requests or issues mentioning V1, I assume it's unused.

Noticed via static analysis. This crashes in php 7.0-7.2

```
php > require_once 'vendor/autoload.php';
php > require_once 'src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/LazyLoadingValueHolderFactoryV1.php';

Fatal error: Declaration of Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\LazyLoadingValueHolderFactoryV1::getGenerator() must be compatible with ProxyManager\Factory\LazyLoadingValueHolderFactory::getGenerator(): ProxyManager\ProxyGenerator\ProxyGeneratorInterface in /path/to/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/LazyLoadingValueHolderFactoryV1.php on line 20
```

**Comment by xabbuh** [comment]
What did you do to end up with the error? Whether to use `LazyLoadingValueHolderFactoryV1` or `LazyLoadingValueHolderFactoryV2` is decided based on the used version of the `ocramius/proxy-manager` package: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php#L39-L43

**Comment by TysonAndre** [comment]
This is a false positive, then... I didn't notice that the folders were different
