### ISSUE TITLE
[RFC] Remove addSubscriber/removeSubscriber methods

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#24662]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

Subscriber concept is pretty simple. It's to get list of listeners and attach them to EventDispatcher. This is useful concept, but having this functionality in EventDispatcher itself breaks SRP, makes code harder to maintain, makes user space code less flexible and provides technical obstacles as I will demonstrate later.

There is no reason for having this inside EventDispatcher. On application level, we can replace most of the EventSubscriber usage without breakages via compiiler pass, as I have done in my [RegisterListenerPass](https://github.com/ostrolucky/app-event-dispatcher/blob/master/src/Symfony/DependencyInjection/RegisterListenersPass.php). For rest, we can expose this functionality in different way.

I propose to remove
```
\Symfony\Component\EventDispatcher\EventDispatcherInterface::addSubscriber
\Symfony\Component\EventDispatcher\EventDispatcherInterface::removeSubscriber
\Symfony\Component\Form\FormConfigBuilder::addEventSubscriber
```
Next, I propose to shift responsibility of getting list of listeners from subscriber and attaching them to EventDispatcher to separate, new classes, such as:
```
\Symfony\Component\EventDispatcher\ListenerExtractorInterface::extract($subscriber)
\Symfony\Component\EventDispatcher\EventSubsciberAttacher::{attach, detach}
```

Default implementation of `ListenerExtractorInterface` will do same thing `EventDispatcher::addSubscriber` currently does.

`EventSubscriberAttacher` is simple utility class which will just iterate over the values supplied by `ListenerExtractor` and call `EventDispatcherInterface::addListener`. 

Current RegisterListenerPass will utilize this mechanism, with optional argument for ListenerExtractor. Current direct consumers of API I'm proposing to remove will also be encouraged to use it, although they are not forced to, they can easily write their own attaching logic from scratch. They will no longer be forced to [override methods](https://github.com/symfony/symfony/issues/12863) to affect extraction process of EventDispatcher used in container.

___
AddSubscriber method caused [some](https://github.com/symfony/symfony/issues/12863) [issues](https://github.com/symfony/symfony/issues/22970) in the past. What triggered me to write this RFC though is peculiar issue I'm working on currently. I'm going to present it to you.

Let's say we have a

```php
class Foo {
    private $dispatcher;
    
    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }
    
    public function addEventListener($eventName, $listener, $priority = 0)
    {
        $this->dispatcher->addListener($eventName, $listener, $priority);
    }
    public function addEventSubscriber(EventSubscriberInterface $subscriber)
    {
        $this->dispatcher->addSubscriber($subscriber);
    }
}
```

This kind of code is used in current FormConfigBuilder. But let's not focus on that.

What I need to do now is to **wrap listener callables into different, wrapper callable**. If I'm in charge of adding listeners, this is easy
```php
public function addEventListener($eventName, $listener, $priority = 0)
{
    $listenerMiddleWare = function(Event $event) use ($listener) {
        $this->doSomeStuff();

        return $listener($event);
    };

    $this->dispatcher->addListener($eventName, $listenerMiddleWare, $priority);
}
```

But in addEventSubscriber method, EventDispatcher is in charge of adding listeners instead and I can't hook into this process. On the first sight, there are two solutions to this problem, but none of them is correct:
1. Don't call `$this->dispatcher->addSubscriber()`, instead extract logic from this method and call `$this->addEventListener`for each listener, instead of `$this->dispatcher->addListener`.
1. Use decorator pattern and in constructor wrap the supplied dispatcher into proxy event dispatcher, where we provide custom implementation of addListener, or addSubscriber methods.

Why are they not correct:
1. This assumes dispatcher which has been injected uses default implementation of addSubscriber method. User could instead inject EventDispatcher with overridden addSubscriber method with his own logic. No way to know.
1.
    1. If I don't make an addSubscriber call to wrapped dispatcher, this is same problem as I had in 1.
    2. If I extract wraping logic I have in `Foo::addEventListener` into addListener method of this wrapper, and let `addSubscriber` call pass to wrapped dispatcher, wrapped dispatcher will trigger his own addListener method, not mine.

**Comment by nicolas-grekas** [comment]
SRP itself doesn't seem like a good enough reason to do this, esp. now that this is how things are.
Yes, we could move the logic to DI wiring. But that would also mean the component would be suddenly harder to use for ppl that don't use our DI component.
Apart from "better design", what's the benefit of doing so?

**Comment by ostrolucky** [comment]
SRP wasn't reason alone for this RFC. I have demonstrated example which shows technical limitation of this design.

For people who don't use DI component, it would be only slightly harder. Instead of doing `$eventListener->addEventSubscriber($subscriber)`, they would do `EventSubscriberAttacher::attach($eventListener, $subscriber);`

**Comment by nicolas-grekas** [comment]
Hum, OK. The BC layer is going to be the main difficulty... Would you have the will and time to make it happen?

**Comment by ostrolucky** [comment]
I might. I would like to reach approval of the idea first though.

**Comment by stof** [comment]
I tend to agree that this could be moved outside the EventDispatcher.

BC layer would not be hard actually:

```php
class EventDispatcher
{
    public function addEventSubscriber($subscriber)
    {
        @trigger_error('...', E_USER_DEPRECATED);

        EventSubscriberAttacher::attach($this, $subscriber);
    }
}

**Comment by nicolas-grekas** [comment]
> BC layer would not be hard actually

don't miss the interface change :)

**Comment by stof** [comment]
@nicolas-grekas deprecating the method in the interface would not require lots of work (people would still have to implement the method for now, as the interface has to keep it for BC, but they would also trigger a warning when people use it)

**Comment by fabpot** [comment]
I'm mostly 👎 on this proposal. I think the benefits are too thin compare to the huge migration path. Also because this component is used a lot, so we need to be very careful when doing refactoring.

**Comment by nicolas-grekas** [comment]
Let's close, it staled :)

**Comment by SulivanDotEu** [comment]
Removing a subscriber is very difficult and I wish this RFC will be reopen one day.
