### ISSUE TITLE
[Security] ChainPasswordEncoder

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#24669]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

I want to change users encoder so I thought of using the workflow described here: https://pehapkari.cz/blog/2017/02/06/how-to-rehash-legacy-passwords-in-symfony/#comment-3153608090 but for this I need to be able to chain the legacy and new encoder. A `ChainPasswordEncoder` would just take a `PasswordEncoderInterface` array in its constructor and loop over it to implement `encodePassword` and `isPasswordValid`.

The way `EncoderFactory` works makes me think it's not feasible in userland.

WDYT?

**Comment by xabbuh** [comment]
@MatTheCat You can create a custom service based on the `ChainPasswordEncoder` command into which you inject the other encoders. You may want to take a look at http://blog.michaelperrin.fr/2017/01/17/migrating-users-to-a-secure-hashing-algorithm-in-symfony/ for some inspiration. I am going to close here as this is already possible.

**Comment by MatTheCat** [comment]
> You can create a custom service based on the `ChainPasswordEncoder` command into which you inject the other encoders.

What is this command?

The solution you mentionned doesn't allow to hash the old hash with the new algorithm though. I don't know myself if it's an issue but the comment I linked make me think so.
