### ISSUE TITLE
Autowire CacheItemPoolInterface with default_lifetime

### ISSUE THREAD

**Issue by thomas-hiron** [symfony/symfony#24678]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

The **default_lifetime** configuration doesn't seem to be working with an autowired **CacheItemPoolInterface** (using Filesystem).
Here is the code:
```php
namespace AppBundle\Api;

use Psr\Cache\CacheItemPoolInterface;

class MyApi
{
    /**
     * @var CacheItemPoolInterface
     */
    private $cache;

    public function __construct(CacheItemPoolInterface $cache)
    {
        $this->cache = $cache;
    }
}
```

The configuration:

    framework
        cache:
            app: cache.adapter.filesystem
            pools:
                name:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 10 # doesn't work
I have to declare it explicitly in order to make it work:
```php
namespace AppBundle\Api;

use Psr\Cache\CacheItemPoolInterface;

class MyApi
{
    /**
     * @var CacheItemPoolInterface
     */
    private $cache;

    public function __construct(CacheItemPoolInterface $cache)
    {
        $this->cache = $cache;
    }

    public function getData()
    {
        if (false === $this->cache->hasItem('item_name')) {
            // API request...

            $item->set($data);
            $item->expiresAfter(10); // Works after this

            $this->cache->save($item);
        }

        // ...
    }
}
```

**Comment by nicolas-grekas** [comment]
type hinting will provide you the "cache.app" service, but you're setting the default lifetime on service "name" (bad service name btw).

**Comment by thomas-hiron** [comment]
Thanks for your help, but I think I am missing something. I changed the configuration to this:
    
    cache:
        pools:
            app.cache.api:
                adapter: cache.adapter.filesystem
                default_lifetime: 10
Is the same as?

    cache:
        app: cache.adapter.filesystem
        pools:
            app.cache.api:
                adapter: cache.app
                default_lifetime: 10

Do I need to create an alias to *CacheItemPoolInterface*? It seems there is a link missing somewhere.

**Comment by nicolas-grekas** [comment]
cache.adapter.filesystem is already the default so you can use:
```
cache:
    pools:
        app.cache.api:
            default_lifetime: 10
```
then, there is a missing link yes :)
if you want this app.cache.api pool to be the default when typehinting the interface, you need to alias it yes. Or alternatively you can use regular D configuration and explicitly inject app.cache.api as the first argument of your "AppBundle\Api\MyApi" class/service.

**Comment by thomas-hiron** [comment]
Thank you very much, I used the alias solution:

    Psr\Cache\CacheItemPoolInterface:
        alias: 'app.cache.api'
