### ISSUE TITLE
redirect user to a login form python

### ISSUE THREAD

**Issue by hadeelm24** [symfony/symfony#24672]
Good Morning 
actually I don’t know where is the Error 
I want to enter the username and phone number and check this data  to access  
I use pymongo inside python code 
and HTML 

**## Python Code :**
from flask import Flask, redirect, url_for, request
from pymongo import MongoClient     
app = Flask(__name__)

@app.route('/success/<name>')
def success(name,Phone):
    return 'welcome %s' %name

@app.route('/login',methods = ['POST', 'GET'])
def views():

    client = MongoClient('localhost', 27017)
    db = client['mongoDatabaseDemo']
    collection_user = db['login']
    new_login = collection_user.insert_many(
        [
             {
                  'name':'jhon',
                   "Phone No": '0111873725'
             },
             {
                  "name":"Mike",
                   "Phone No": '0137500979'
             },
             {
                  'name':'Ray',
                   "Phone No": '018354735'
             },
             {
                  "name":"Michelle",
                   "Phone No": '0110293347'
             }
       ]
    )
if request.method == 'POST':
  name = request.form['name']
  Phone = request.form['Phone']
    return redirect(url_for('success',name = name, Phone = Phone)) 
else:
  name = request.args.get('name')
  Phone = request.args.get('Phone')
    return redirect(url_for('success',name = name, Phone = Phone))
if __name__ == '__main__': 
   app.run(debug = True)

## **HTML** 
<html>
  <body>
     <form action = "http://localhost:27017/login"method = "POST">
        <p>Name:</p>
        <p><input type = "text" name = "username" placeholder="Username"/></p>
        <p>Phone No.:</p>
        <p><input type="tel" Phone= "Phone" placeholder="Phone"/></p>
        <p><input type = "submit" value = "submit"/></p>
     </form>  

    </body>
  
</html>

could anyone help me pleas and told me what is wrong ....

**Comment by iltar** [comment]
![](https://img.memecdn.com/wat-wat-wat-oh-wait-why-im-doing-this_o_2044883.jpg)

Are you looking for https://stackoverflow.com/ ?

**Comment by javiereguiluz** [comment]
Closing because this issue doesn't have anything to do with Symfony.
