### ISSUE TITLE
[TwigBridge] Create impersonation_exit_path() and *_url() functions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24676]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

Creating the URL to exit a user impersonation is much harder than expected because even the HTTP query parameter name is configurable (see https://github.com/symfony/symfony/commit/a3253f6db686adbaca39e0e034af49e7ab293ab2). Given that we already have `logout_path()` and `logout_url()` Twig functions, could we create `impersonation_exit_path()` and `impersonation_exit_url()` too?

**Comment by fabpot** [comment]
Sounds good to me.

**Comment by Simperfit** [comment]
I'm working on it
