### ISSUE TITLE
Symfony\Component\Console\Exception\RuntimeException Not enough arguments (missing: "package")

### ISSUE THREAD

**Issue by dameer** [symfony/symfony#24679]
Hi!
I'm trying to install Carbon Fields library via composer. One of dependencies is Symfony. Whenever I run composer installation is interrupted by error message reading:

[Symfony\Component\Console\Exception\RuntimeException]  
Not enough arguments (missing: "package"). 

Is that anything relating to Symfony or badly composed JSON?

**Comment by chalasr** [comment]
Please paste the exact command you are executing (`composer ...`).

**Comment by dameer** [comment]
`composer require htmlburger/carbon-fields`

...according to [Quickstart manuals](https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-1-0) of Carbon Fields.

**Comment by NicoHaase** [comment]
According to https://packagist.org/packages/htmlburger/carbon-fields, there is no dependency upon Symfony components

**Comment by dameer** [comment]
How about this one:

![31951532-ad0665b6-b8de-11e7-82ef-2d0b637b4c10](https://user-images.githubusercontent.com/1826261/31988671-2bd02aa8-b970-11e7-80f3-e09172624d2c.png)

**Comment by NicoHaase** [comment]
I don't see any connection to Symfony there either.... and without inspecting your composer.json, nobody can give hints

**Comment by BoShurik** [comment]
`composer why-not` accepts argument `package` (https://getcomposer.org/doc/03-cli.md#prohibits-why-not-) (The exception points to this)
Should be:
`composer why-not vendor/package-name`

**Comment by chalasr** [comment]
And this argument is required, thus this is just a misuse of a composer command which relies on the symfony console. Closing

**Comment by zenng** [comment]
Go to project root -> composer show -> for package access u need to write like twig/twig -> composer why-not twig/twig
