### ISSUE TITLE
[DependencyInjection] Accessing value of resolved env parameters

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#24674]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-BETA1

Hello!

I have following file with secrets:
```
{
    "secret": "Secret value",
    "db_password": "Password value"
}
``` 
In my services.yaml I've got this:
```
parameters:
    env(SECRETS_FILE): '%kernel.project_dir%/secrets.json'
    app.secrets: '%env(json:file:SECRETS_FILE)%'
```
I don`t want to pass entire secrets to services. I tried following:
```
bind:
    $secret: '@=parameter("app.secrets")["secret"]'
```
and this work fine, but only in service definition. I can't do this for 
```
parameters:
    app.secrets.secret: '@=parameter("app.secrets")["secret"]'
```
or
```
framework:
    secret: '@=parameter("app.secrets")["secret"]'
```

So I want that this values will be accessible through separate parameters, e.g. `app.secrets.secret` and `app.secrets.db_password`. But when I got value of `app.secret` in `Kernel:configureContainer` I've got `'%env(json:file:SECRETS_FILE)%'` not a content of the file.

Is it possible to realize this approach using `%env(json:file:SECRETS_FILE)%` or I should manually use `file_get_contents` and `json_decode` in `Kernel`?

**Comment by nicolas-grekas** [comment]
Using expressions in parameters is not supported, so this cannot work indeed.

**Comment by BoShurik** [comment]
@nicolas-grekas maybe I understand this feature incorrectly and accessing env arrays is not supported. Is it possible to access specific keys from secrets file in compile time?

**Comment by nicolas-grekas** [comment]
You've got everything right, except that accessing a specific key is not supported...

**Comment by BoShurik** [comment]
@nicolas-grekas If I want to set secrets, I should use separate file for any service, e.g. database, redis and so on. I can't store it in one file. Am I correct?
```
parameters:
    env(DATABASE_SECRET): '%kernel.project_dir%/secrets/database'
    app.secrets.database: '%env(file:DATABASE_SECRET)%'

    env(API_SECRET): '%kernel.project_dir%/secrets/api'
    app.secrets.api: '%env(file:API_SECRET)%'
```

**Comment by nicolas-grekas** [comment]
Correct

**Comment by xabbuh** [comment]
I have relabelled the issue as a feature request. However, I am not sure if we can (or want to) really implement this in a save way.

**Comment by BoShurik** [comment]
Yes. Now I think that I can use old `parameters.yaml` instead

**Comment by nicolas-grekas** [comment]
Technically, we could add a property-path processor to access a specific key.
Closing as exposing several secrets as several files is the way to go for now (as done typically by vaults.)
We can always reconsider if the issue comes back often and with legitimate use cases.
