### ISSUE TITLE
[VarDumper] New Version of Chrome(62.0.3202.66) cannot render dd function in network preview window

### ISSUE THREAD

**Issue by friparia** [symfony/symfony#24688]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

### Description:
When updated to chrome version 62.0.3202.66, dd function cannot be rendered by chrome network preview window. 

![fzr n2qqt 1c4hpj wu6a](https://user-images.githubusercontent.com/3226127/31978542-868ff794-b974-11e7-8993-feb2064334d8.png)

And I have found the [changelog of chrome](https://chromium.googlesource.com/chromium/src/+log/61.0.3163.98..62.0.3202.66?pretty=fuller&n=10000). [This commit]( https://chromium.googlesource.com/chromium/src/+/f674b40baf2d44d1b27f33b3ed39e60b2b9169da%5E%21/#F0) says it will not render as HTML agressively if requested via XHR.  It will use base64 to encode the response body first, and then render the html, so it may cause javascript not be rendered ?

### Steps To Reproduce:

1. Update to chrome version 62.0.3202.66
2. Execute a dd function
3. Check the chrome network preview window

This bug is found in [laravel framework](https://github.com/laravel/framework/issues/21808) when using the symfony/var-dumper package.

**Comment by nicolas-grekas** [comment]
@friparia do you know any way to make it work again? Can it be made to work at all now?

**Comment by friparia** [comment]
Well, I have found the newly updated chrome network preview also cannot render pure html document. 

It is not a symfony bug, it is a chrome bug.

**Comment by jasonvarga** [comment]
This is not a solution, just a workaround - but I noticed that Chrome will render errors as HTML, so setting the response code first will bypass the new behavior.

``` php
http_response_code(500);
dd('foo');
```

Of course, it means the request will also be a 500.

**Comment by joebenson** [comment]
For convenience until it's resolved, consider creating a new helper function:
```
function ddd(...$args){
    http_response_code(500);
    dd($args);
}
```

**Comment by iulian34** [comment]
This problem is on all browsers. Tested with Chrome/Firefox/Edge/Opera

**Comment by kylesean** [comment]
@iulian34 ,So,the issue lies in the dd method?

**Comment by friparia** [comment]
new version of chrome has fixed this...

**Comment by oriceon** [comment]
And 72 broke again....

**Comment by 5SMNOONMS5** [comment]
Face same problem here also

**Comment by nicolas-grekas** [comment]
Please report to Chrome and post the link of the issue here.

**Comment by IllyaMoskvin** [comment]
**Issue 930061: DevTools Network Preview no longer displays a preview of HTML content**
https://bugs.chromium.org/p/chromium/issues/detail?id=930061

I think this is the relevant issue. Assigned 4 days ago.

**Comment by edurodriguesdias** [comment]
Same issue here.
Chrome Version: 72.0.3626.109

**Comment by tiagosimoesdev** [comment]
72.0.3626.119 too ..

**Comment by smallknife1120** [comment]
72.0.3626.121 too..

**Comment by lxiaoxiang** [comment]
73.0.3683.75 work fine

**Comment by oriceon** [comment]
Yes, confirm that!

mie., 20 mar. 2019, 10:12 luoxiaoxiang <notifications@github.com> a scris:

**Comment by chiqui3d** [comment]
It doesn't work for me :(

**Comment by max-petrovich** [comment]
The same issue on Chrome 77.0.3865.120 (macos)

**Comment by yoshiki-t** [comment]
Chrome Version 123.0.6312.59 It recurred again.
Is there any workaround?

![image](https://github.com/symfony/symfony/assets/49905427/bdb517b1-89e1-4c34-8566-3e4db27e5e7e)
![image](https://github.com/symfony/symfony/assets/49905427/79a8b242-ce05-4f52-b9ab-62fe852b799b)

**Comment by oriceon** [comment]
On last version has been fixed

**Comment by derrabus** [comment]
Let's lock this issue. I don't want everyone in this list to be ping'ed whenever Chrome ships another regression. Please report any regressions to Chromium first. If you believe we should fix something on Symfony's side, please open a new issue.
