### ISSUE TITLE
Symfony language code mangling makes it hard to reuse

### ISSUE THREAD

**Issue by goba** [symfony/symfony#2468]
Symfony mangles language codes for its internal use to (a) uppercase all components but the first and (b) replace component separating dashes with underscores. This is maybe conforming to a standard or common practice, but the W3C never suggested people use language codes like that and their recent recommendations with HTML5 are clearly very far from how Symfony treats language codes.

There is certainly nothing wrong with picking a language code format and doing conversion on incoming data and outgoing data. We in Drupal try to avoid this by using a standard that is much closer to the W3C specs. We use all lowercase codes (which is not strictly W3C) and we use dashes (like the W3C). Now that Drupal 8 is adapting Symfony in certain places, we cannot reuse the language handling code at all since the language codes are so far from how the web expects them, and we don't want to convert back and forth if we can work with formats that are exactly or at least much more closely resemble web standards.

More information on language codes on the web: http://www.w3.org/International/articles/language-tags/

**Comment by jakzal** [comment]
Few clarifications:
* Symfony doesn't "mangle language codes". It uses a locale, which might be a language code but it doesn't need to be. It [is defined as](http://symfony.com/doc/current/reference/constraints/Locale.html) (also [here](http://symfony.com/doc/current/book/translation.html)):

    >Locale [...] is either the two letter ISO 639-1 language code (e.g. fr), or the language code followed by an underscore (_), then the ISO 3166-1 alpha-2 country code (e.g. fr_FR for French/France). 

* BCP47 is not an accepted standard yet. As far as I know there's no data or libraries we could import and use like we do with ICU. As you said W3C formatted language codes are hard to generate.

PHP's intl extension uses the ICU data.  We've got pretty-much built in support for it, and I don't see why we should change (and break BC).

This is an old issue and I'm gonna close it. I guess Drupal has solved this issue by now in their own way. If anyone's got more input we can always re-start the discussion.
