### ISSUE TITLE
[Security] cutomize authentification Symfony2.7

### ISSUE THREAD

**Issue by persiasama** [symfony/symfony#24698]
I'm using Symfony2.7 then I would like that when disable users (enabled=0) try to get logged symfony don't reject them.
I tried this but it doesn't work or Symfony2.7
https://symfony.com/doc/current/security/user_checkers.html.

So I think to create my own authentification service to manage it manually?
So is it a bad idea? what are the risks for security.

thanks

**Comment by dmaicher** [comment]
As this is not an issue with symfony itself I would suggest to have a look here instead: https://symfony.com/support

**Comment by chalasr** [comment]
This is not a bug, nothing we can do for 2.7. Hope you find a workaround on support platforms

**Comment by chalasr** [comment]
Perhaps you can [decorate](https://symfony.com/doc/current/service_container/service_decoration.html) the `security.user_checker` service.

**Comment by persiasama** [comment]
thanks you a lot @chalasr it's working like a charm
