### ISSUE TITLE
[Console] Console actually is dependent on Dotenv

### ISSUE THREAD

**Issue by Elsensee** [symfony/symfony#24714]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

I gave Symfony 4 a go and installed it with composer - everything went well. But when I ran a `composer install --no-dev` the `symfony/dotenv` component got removed and thus the script `cache:clean` returned with error code 255 because it is referenced in the `bin/console` file installed by Flex.

So either the reference should somehow be removed or the dependency on dotenv added to the Console component.

**Comment by Tobion** [comment]
The symfony/console component does not depend on dotenv. What requires it is the console flex recipe: https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console

**Comment by Tobion** [comment]
Also installing with --no-dev only makes sense for deployment. But there you should also have the env variables set. And then it will not use the dotenv. So your actions seems strange. i think all we need to do is throw an explicit exception in bin/console when APP_ENV is not set and dotenv not installed to help explain the situation.

**Comment by xabbuh** [comment]
I agree with @Tobion. But as this is something that needs to be fixed in the recipes repository I am going to close here.
