### ISSUE TITLE
[HttpKernel] Strange controller argument behaviour

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#24729]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4 (maybe earlier)

With default routing and services configuration create a simple controller with a non-service class like this: 

```php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends AbstractController
{
    /**
     * @Route(name="index")
     */
    public function indexAction(A $a)
    {
        dump($a);

        return new Response();
    }
}

class A
{
}
```

Expected result: an exception about wrong argument. Actual result:

![image](https://user-images.githubusercontent.com/2552865/32139051-005f9c84-bc48-11e7-8088-e609a0b38ae8.png)

Which means that a new instance of a non-DI class is injected.

I investigated a little and found that `Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver` does this.

**Comment by mvrhov** [comment]
AFAIR this is expected behavior since 3.4 and controller action injection.

**Comment by ogizanagi** [comment]
@vudaltsov : Could you try v3.4.0-BETA2 and setting the [`container.autowiring.strict_mode`](https://github.com/symfony/symfony/pull/24671) to true? It should solve this issue.

Looks a duplicate of https://github.com/symfony/symfony/issues/24569

**Comment by vudaltsov** [comment]
@ogizanagi , yes, thank you!
