### ISSUE TITLE
[security] serialize the user, again

### ISSUE THREAD

**Issue by johndodev** [symfony/symfony#24731]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no
| Symfony version  | silex 2

One more time I have a "Class __PHP_Incomplete_Class has no unserializer" thanks to security component. It is probably caused by a doctrine relation, the security component wants to serialize a proxy or something, I don't know. 

However I implemented \Serializable on my User, and serialize only the ID, so why implement serializable seems completely useless ? 
As the doc say, _This may or may not be needed depending on your setup, but it's probably a good idea._ not very clear...

I still have to do a special object like SecurityUser to log my users, and have to surcharge "user" service, etc... and this solution is not in SF docs (but in some blogs).

After all those years, this serialize thing has always been a balls breaker thing to me. Could you try to simplify it ? Une fois pour toute qu'on en parle plus !

**Comment by iltar** [comment]
The `__PHP_Incomplete_Class` sounds like it can't find your class, perhaps something in the FQCN changed?

I agree that it should be simplified, but there's one thing you can do already: https://stovepipe.systems/post/decoupling-your-security-user

**Comment by johndodev** [comment]
Yes that's the blog I was talking about and what I'm doing, but if it is the only solution to have a proper login system it should be on the official doc...

I dont know about my FQCN, i'm not doing any fancy things, just a user with some relations.

:(

**Comment by sashaaro** [comment]
What about introduce to TokenSerializerInterface like that
```php
interface TokenSerializerInterface {
    public function serialize(TokenInterface $token): mixed
    public function unserialize(mixed $data): TokenInterface
    public function supports(TokenInterface $token): bool
}

class StandardTokenSerializer implements TokenSerializerInterface {
    public function serialize(TokenInterface $token): mixed
    {
         return serialize($token);
    }
    public function unserialize(mixed $data): TokenInterface
    {
        return unserialize($data);
    }
    public function supports(TokenInterface $token): bool
    {
          return $token instanceof \Serializable
    }
}

class MyTokenSerializer implements TokenSerializerInterface {
     public function __construct(UserRepository $repository)
     {
            $this->repository = $repository
     }
     public function serialize(TokenInterface $token): mixed
     {
          if (!$token instanceof UserPasswordToken) { throw new UnsupportedToken() }
          return $token->getUser()->getId();
     }
     public function unserialize(mixed $data): TokenInterface
     {
         return new UserPasswordToken($this->repository->find($data));
     }
     public function supports(TokenInterface $token): bool
     {
          return $token instanceof UserPasswordToken
     }
}

**Comment by mvrhov** [comment]
No workarounds serializer interfaces etc, the only proper solution is what @iltar is suggesting.
