### ISSUE TITLE
[Form] empty_data is not used when creating form

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#24753]
| Q                | A
| ---------------- | -----
| Bug report?      | test
| Feature request? | no
| BC Break report? | 
| RFC?             | no
| Symfony version  | 3.3.10

Maybe related to #21890

I ran `symfony new TestManyToOneForm` and copied over my formtypes and DTO's from an existing project and created this: https://github.com/Richard87/TestManyToOneForm

Basically, `empty_data` does not set any default data, but If I pass in the data in the `$this->createForm(Type:class, $data)` it works, so If I have understood the documentation correctly, there is a bug somewere...

[EDIT]
So the same bug appears when creating simple forms too, so I have removed alot more of the code to simplify the test...

**Comment by issei-m** [comment]
The `empty_data` is the option used when data submission, the data you specified is used as default value when you empty data is submitted to the form. So not used for form initialization.

Wouldn't be `data` option is what you want?

```php
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ColleagueDTO::class,
            'data' => new ColleagueDTO(0, "Test", "Test@test.no", 0)
        ]);
    }
```

**Comment by Richard87** [comment]
Perfect, that's exactly what I wanted!
