### ISSUE TITLE
commits break yml parsing when using anchors

### ISSUE THREAD

**Issue by dreamer79** [symfony/symfony#24757]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 2.7

commit faf671db0f7493c15fdcef8446b9472a1ce80445
commit c891413f6c82257777eb3673827eea3ee47f0501

These commits clear $this->refs inside the Symfony\Component\Yaml\Parser\parse method and references to anchors in previously parsed files don't work. Removing the lines solves the problem and configurations based on such overrides/includes work as expected.

Please, make a revision of the commited code and put some proper unit tests for such configurations.

**Comment by jvasseur** [comment]
References were never supposed to work across files, the fact that it used to work was a bug that is fixed by the commits you linked.

**Comment by stof** [comment]
Closing this issue, as things are now working as expected. Parsing 2 separate Yaml files should not impact each other.

**Comment by dreamer79** [comment]
So you say in config.yml I can't include a file that is linked to anchors in config.yml to override just some of the fields, but have to duplicate the whole structure in the main file? Because the problem I describe is about the following scenario:

config.yml

Import:
      -resource{file1.yml}
      -resource{file2.yml}

File1.yml
Params: &params
     Test: test
     test1: 123

File2.yml
Params: 
     <<: *params
     Test: 567

This is parsing the same tree with the idea that a bundle/application deployed yml may be overriden with something in a file out of the symfony directory(for storing configs on installs and updates ot sharing them across multiple projects). This is described in the Symfony docs as a valid scenario.

I repeat that in this case we are talking about parsing the same yml configuration tree.

**Comment by stof** [comment]
Well, Symfony DependencyInjection has a concept of imports. But this does not means that both YAML files become linked together at the YAML level.

Btw, you don't need to duplicate the whole structure if you just want to override some settings, as the other file is still imported. You just need to configure what is needed for the override.

**Comment by dreamer79** [comment]
Look, Christof. I will try to explain why I find the change as a bug- it breaks old code without any sign about it(you just start composer update and all stops working) and somehow breaks the idea about importing files.

 Actually in an YAML if you need to change a single field in a nested structure you can't do it using the Symfony parser. You just lose all the other fields. And maybe you need a db config block to just change the database name, but keep host, user and password. Without an anchor you will get a db config with database name only(even the main YAML docs describe this and tell you to use anchors.) The anchor works as a macros to inject all fields of the nested(level 2 or deeper block) and then you override what you need. Actually if they work in the same file only YAML anchors are almost useless as configs are usually relatively small.

Let me try to explain why I think the parser is broken now. Lets move to core programming concepts. Imagine some C code where you import external libs of functions, classes and macros. If macro definitions from includea were lost during a compile cycle? What about PHP and its include statement? When you use such a statement you expect the other file to replace it on the same place and then the whole glued content to be parsed at once. And actually inside the same YAML tree people would expect a normally behaving parser that does this. 

Sharing anchors between trees is somehing else and is a buggy behaviour. But for the same yree what about such a simple fix? In parse method add a new parameter $clearRefs=true(e.g. definition with default value) . Any call will normally clear anhors(macros). Only while iterating imported files call parse with false for this parameter(there should be only one place in cide for this iteration anyway). This way the parser will work as any normal parser allowing imports, will not break compatibility with code written prior to the changes, the sharing anchors between trees bug will be fixed and memory allocation will be optimized(which actually is in the commit message).

**Comment by buffcode** [comment]
(Re-) Implementing this feature could be an elegant way to allow partial changes/addendums to `security.*`:
- https://github.com/symfony/symfony/issues/25021
- https://github.com/symfony/symfony/issues/22308
