### ISSUE TITLE
Facebook API [Login / Security]

### ISSUE THREAD

**Issue by persiasama** [symfony/symfony#24754]
Hi,
I'm developing a website where users can create an account with email + password or just via login with facebook (in one click).
I want to give them to possibility to disable their account but before they must enter their password.
For the first users ( who  create an account with email + password ) it is ok.
But for others (facebook users) I can't ask them for password because they are logged via facebook.
does anyone have an idea to solve this?
thanks

**Comment by javiereguiluz** [comment]
@persiasama in this GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in https://symfony.com/support Thanks!
