### ISSUE TITLE
Symfony Form fails to validate multiple uniqueEntity fields

### ISSUE THREAD

**Issue by Herod** [symfony/symfony#24765]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

I have a problem in validating `UniqueEntity` with multiple fields.
I have the following code:

    /**
     * @ORM\Entity()
     * @ORM\Table(name="app_languages", uniqueConstraints={@ORM\UniqueConstraint(name="IDX_LANGUAGE_CONSTRAINT", columns={"language_id", "app_id"})})
     *
     * @UniqueEntity(fields={"languages", "app"})
     */
    class AppLanguages extends AbstractEntity

When I am trying to post the same language_id and app_id i am getting an `PDOException > PDOException > UniqueConstraintViolationException`

I checked the [documentation][1] of symfony I also checked this answer [here][2] but it does not work as it should.
There is also a Validator for done under the namespace `Symfony\Bridge\Doctrine\Validator\Constraints` but still this is not working...

I have the following cases (database table is empty):
lang_id = 1 app_id = 1 -> saved
lang_id = 1 app_id = 2 -> saved
lang_id = 1 app_id = 2 -> fail

  [1]: https://symfony.com/doc/current/reference/constraints/UniqueEntity.html#errorpath
  [2]: https://stackoverflow.com/a/8491895/900145

**Comment by Simperfit** [comment]
Status: Needs Review

This behaviour occurs when you are doing something like : 
`app_id=1&language_id=1` ?

**Comment by Herod** [comment]
i have the following cases (database table is empty):
lang_id = 1 app_id = 1 -> saved
lang_id = 1 app_id = 2 -> saved
lang_id = 1 app_id = 2 -> fail

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by dmaicher** [comment]
And you are sure the fields are named correctly? `@UniqueEntity(fields={"languages", "app"})`

Should it not be called `language` if it refers to one language and not a collection?

**Comment by jakzal** [comment]
@Herod could you provide more details? At least your field mappings for properties involved, ideally a project to reproduce the issue.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
