### ISSUE TITLE
handler in symfony3

### ISSUE THREAD

**Issue by med004** [symfony/symfony#24776]
hello,
haw to use handler for invoque data from view and persist object ( for exemple I have input name in test.html.twig .. I send value input name but how to invoque this value in handler ) !!

**Comment by Simperfit** [comment]
I don't understand what you want to achieve but github issues are more for bug reporting and new feature, maybe you should ask this on the [#support chan of symfony or in stackoverflow](http://symfony.com/community)

**Comment by xabbuh** [comment]
I am closing here as we do not use GitHub for support questions. Thank you for understanding.
