### ISSUE TITLE
Deprecation and renaming of Request::getRequestFormat

### ISSUE THREAD

**Issue by mattwillo** [symfony/symfony#24773]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.6

I believe the naming of HttpFoundation\Request::getRequestFormat is confusing and can result in people incorrectly assuming this is the format of the request rather than the requested format of the response.

I would propose deprecating this method in favour of getRequestedResponseFormat or getRequestedFormat as this is more clear.

I am happy to patch this if others agree.

**Comment by Simperfit** [comment]
👍 for me, could you provide the pull request ?

**Comment by javiereguiluz** [comment]
Before sending a PR for this, I recommend you to wait for more support for this idea. The reason is that HttpFoundation's Request class is super critical and we are very reluctant to make any change on it. Thanks!

**Comment by mattwillo** [comment]
OK, I will wait for more opinions before I act on this.
