### ISSUE TITLE
[Console]  How provide input stream for ApplicationTester?

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#24784]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Symfony version  | 3.3.7

I am using the following code to test interactive console application.
```php
$input_stream = $this->getInputStream("Some user input\n");
$question_helper = new QuestionHelper();
$question_helper->setInputStream($input_stream);

$helper_set = $application->getHelperSet();
$helper_set->set($question_helper);

$tester = new ApplicationTester($application);
$tester->run($arguments);
```
It works well but it is not compatible with Symfony 4 because _setInputStream()_ method has been removed.

The documentation suggests using _StreamableInputInterface::setStream()_ but I could not find any way to set Input for ApplicationTester.

Any suggestions?

**Comment by dmaicher** [comment]
Did you check https://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input ? Does it solve your problem?

**Comment by Chi-teck** [comment]
@dmaicher, Yes, I did. It works fine with command tester. I need the same for application tester.

**Comment by chalasr** [comment]
There's no reason to not be able to do the same using the application tester.
👍  for `ApplicationTester::setInputs()`.
Might need an internal trait to reuse logic between `CommandTester` and `ApplicationTester`, PR welcomed

**Comment by Simperfit** [comment]
@Chi-teck Do you want to provide the PR ?

**Comment by Chi-teck** [comment]
@Simperfit, I can't work on this at the moment. Feel free to submit the PR if you want.

**Comment by Simperfit** [comment]
I'm gonna do it.
