### ISSUE TITLE
Failure to extend doctrine command UpdateSchemaDoctrineCommand

### ISSUE THREAD

**Issue by tuxgasy** [symfony/symfony#24787]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hi,

To ignore some entities when running doctrine:schema:update, I extends UpdateSchemaDoctrineCommand like that :

```php
<?php

namespace AppBundle\Command;

use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\ORM\Tools\SchemaTool;

class DoctrineUpdateCommand extends \Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand
{
	protected $ignoredEntities = array(
		'AppBundle\Entity\Test',
	);

	protected function executeSchemaCommand(InputInterface $input, OutputInterface $output, SchemaTool $schemaTool, array $metadatas)
	{
    $newMetadatas = array();
    foreach($metadatas as $metadata){
      if(!in_array($metadata->getName(), $this->ignoredEntities)){
        array_push($newMetadatas, $metadata);
      }
    }

    parent::executeSchemaCommand($input, $output, $schemaTool, $newMetadatas);
  }
}
```

When I update dependencies with composer, it does not work anymore. I tried with a new installation, it work but not after update.

Sorry for my very bad english! Thank you all!

**Comment by javiereguiluz** [comment]
@tuxgasy thanks for reporting this. However, this command is not part of Symfony but part of DoctrineBundle. I've moved your issue there: https://github.com/doctrine/DoctrineBundle/issues/728  Thanks!
