### ISSUE TITLE
[Serializer] Example from documentation does not work

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#24783]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I was reading the documentation of Symfony/Serializer component. [Here](https://symfony.com/doc/current/components/serializer.html#deserializing-an-object) I found info about a new feature in Symfony 3.3, the `allow_extra_attributes` option. However the example from documentation does not work. This should throw a `Symfony\Component\Serializer\Exception\ExtraAttributesException` but it does not:

```php
<?php declare(strict_types = 1);

require __DIR__ . '/vendor/autoload.php';

(new \Symfony\Component\Dotenv\Dotenv())->load(__DIR__.'/.env');

$kernel = new \App\Kernel('dev', true);
$kernel->boot();

$container = $kernel->getContainer();
$serializer = $container->get('serializer');

class Person
{
	private $age;
	private $name;
	private $sportsman;

	// Getters
	public function getName()
	{
		return $this->name;
	}

	public function getAge()
	{
		return $this->age;
	}

	// Issers
	public function isSportsman()
	{
		return $this->sportsman;
	}

	// Setters
	public function setName($name)
	{
		$this->name = $name;
	}

	public function setAge($age)
	{
		$this->age = $age;
	}

	public function setSportsman($sportsman)
	{
		$this->sportsman = $sportsman;
	}
}

$data = <<<EOF
<person>
    <name>foo</name>
    <age>99</age>
    <city>Paris</city>
</person>
EOF;

$person = $serializer->deserialize($data, 'Person', 'xml', array(
	'allow_extra_attributes' => false,
));

var_export($person);
```

cc @juliendidier ref #19958, symfony/symfony-docs#6975

**Comment by enumag** [comment]
The problem is that [`AbstractNormalizer::getAllowedAttributes()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L206-L210) returns false.

**Comment by javiereguiluz** [comment]
Given that this is a documentation issue, I've mode this to https://github.com/symfony/symfony-docs/issues/8576 Thanks!

**Comment by enumag** [comment]
@javiereguiluz Actually I believe that the documentation is correct and the feature should work as described. Meaning it is a code issue rather than doc issue.

**Comment by javiereguiluz** [comment]
The I read your issue too fast. I'm sorry.

**Comment by Simperfit** [comment]
Do you want to work on a PR @enumag ?

**Comment by enumag** [comment]
@Simperfit Not really.

**Comment by Simperfit** [comment]
I'm gonna do it.
