### ISSUE TITLE
Asset Component base URL ignored for some resources

### ISSUE THREAD

**Issue by validumitruro** [symfony/symfony#24789]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

There's an issue with the PathPackage class, because the assets.base_url and assets.base_urls settings are completely ignored when dealing with Javascript files. Images are being prepended the correct base URL, but not JS scripts.

The following configuration was tried:

```yaml
# config/packages/framework.yaml
framework:
	assets:
		base_urls:
	    	- http://localhost:8080/
```

```yaml
framework:
	assets:
		base_url: http://localhost:8080/
```

Both these settings behave exactly the same way: images get the base URL prepended, while javascript files don't (haven't tried more resources as I didn't need any other yet).

The controller setup is quite simple:

```php
$this->assetPackage = new PathPackage('/static', new EmptyVersionStrategy());

// Expected output is correct: http://localhost:8080/static/img/logo.png
$this->assetPackage->getUrl('img/logo.png');

// Expected output: http://localhost:8080/static/builds/entrypoint.js
// Actual output: /static/builds/entrypoint.js
$this->assetPackage->getUrl('builds/entrypoint.js');
```

For now I had to work around this by injecting the Kernel into the controller and checking for the debug flag:

```php
public function __construct(KernelInterface $kernel)
    {
        if($kernel->isDebug()) {
            $this->assetPackage = new UrlPackage('http://localhost:8080/static', new EmptyVersionStrategy());
        } else {
            $this->assetPackage = new PathPackage('/static', new EmptyVersionStrategy());
        }
    }
```

But this is obviously wrong and error-prone, it's just meant to give perspective and alternative working scenarios for this bug. It seems like the Twig asset() helper function is behaving properly, though.

**Comment by weaverryan** [comment]
Hey @validumitruro!

This seems very odd, as the Asset component doesn't do anything based on the file type (e.g. images versus JavaScript). Can you post your *full* configuration under `framework.assets`? Are you using Encore by change with the `json_manifest_path` option?

**Comment by javiereguiluz** [comment]
@validumitruro I've edited your original issue to add code highlighting and as you can see, the YAML code blocks looks weird because they contain TABS instead of spaces. Is this a problem when copying the code into this issue or does your application contain those TABS too?

**Comment by validumitruro** [comment]
Hello, @weaverryan , that is actually the full configuration. No manifest or anything else. For now I'm just using the asset() helper, as that works properly. The PathPackage tho, now that I think about it, I'm not really sure it's supposed to add the actual URL, being a **path** package. But I don't think there's a way to do that with UrlPackage either (e.g.: use the assets.base_url config) unless the full target URL is specified in the constructor or the container config is injected. That does work, but then the YAML configuration kinda becomes obsolete. I think the 2 ways of declaring assets configuration - via YAML and via code - should be exclusive of each other, even though it might not be best practice. This is what threw me off from following the docs, because I was under the impression they worked hand in hand.

@javiereguiluz the code is using tabs indeed, the indentation is correct in the actual config and there are no errors on the actual server, it's just an indentation copy&paste issue.

**Comment by xabbuh** [comment]
If the `getUrl()` method's result was inconsistent in regards of the file type being used, that would indeed be an issue. However, I do not see how that could happen. Could you please provide a small project allowing to reproduce this behaviour?

**Comment by validumitruro** [comment]
Hmm, sorry, just tried to reproduce this by setting up a whole new project (the original one was based on symfony-skeleton), but could not reproduce the problem any more, so I don't know what happened there. Maybe some faulty config, files not saved correctly by the IDE, or Apache locking files (had an issue with that last night). Sorry for the false alarm, next time I'll definitely set up 2 projects in parallel when something like this happens, just to confirm.
