### ISSUE TITLE
Yaml component parse object doesn't work

### ISSUE THREAD

**Issue by ttimot24** [symfony/symfony#24794]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

The Yaml component doesn't parse into object even if PARSE_OBJECT is set/passed to the function.

```php
$this->info = \Symfony\Component\Yaml\Yaml::parse(
file_get_contents($file),
\Symfony\Component\Yaml\Yaml::PARSE_OBJECT
 );

```

**Comment by xabbuh** [comment]
Would you mind sharing with us the code that you use and the YAML string that you tried to parse in order to allow us to reproduce the issue?

**Comment by ttimot24** [comment]
Hi!

I updated the issue with the code.

Thanks!

**Comment by chalasr** [comment]
Please make your example uses the result of `file_get_contents()` i.e. the concrete yaml you are trying to parse (with dummy values of course).

**Comment by xabbuh** [comment]
@ttimot24 using

```php
print_r(Yaml::parse('foo: !php/object:O:8:"stdClass":1:{s:3:"foo";s:3:"bar";}', Yaml::PARSE_OBJECT));
```

results in:

```
Array
(
    [foo] => stdClass Object
        (
            [foo] => bar
        )

)
```

As you can see the result is as expected. Thus, the issue must be related to the input you use.

**Comment by ttimot24** [comment]
It's okey thanks. I close the issue.
