### ISSUE TITLE
[HttpKernel] Missing dependency to DI component in composer.json

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#24798]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-BETA2

Hi,

I am not sure whether this was already discussed here, but the `symfony/http-kernel` has a hard dependency on `symfony/dependency-injection` due to the usage of the `ContainerAwareTrait` in `Bundle`: https://github.com/symfony/http-kernel/blob/master/Bundle/Bundle.php#L28

However, the DI component ist only a "suggestion" and not a dependency of the component: https://github.com/symfony/http-kernel/blob/master/composer.json#L55

Is that expected?

Thanks

**Comment by fabpot** [comment]
Closing as explained in the PR.
