### ISSUE TITLE
This form should not contain extra fields

### ISSUE THREAD

**Issue by med004** [symfony/symfony#24795]
Hello,
I have submitted Form but I have this error:

> This form should not contain extra fields

code controller:

`<?php

    namespace AppBundle\Controller\Condidate;

    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Symfony\Component\HttpFoundation\Request;
    use AppBundle\Entity\Skill;
    use AppBundle\Controller\AbstractController;
    use AppBundle\Form\SkillType;

    /**
     *Class SkillController.
     */
    class SkillController extends AbstractController
    {

         /**
         *function handler.
         */
         protected function getHandler(){
            return $this->get('recurit.handler.skill');
        }

        public function getSkillAction(Request $request){
             return $this->render('skills/listkill.html.twig');
        }

        /**
         *function addSkill
         * @param Request $request
         * @return \Symfony\Component\Form\Form The form
         */
        public function addSkillAction(Request $request) {
              $skill =$this->getHandler()->post($request->request->all());
            if ($skill instanceof Skill) {
                //return $this->redirectToRoute('list_skills');
        }

        return $this->render('skills/newskill.html.twig', array(
            'form' => $skill->createView(),));
        }

}
`

code service:

`/**
           *function post
           */
        public function post(array $parameters, array $options = []) {
            $form = $this->formFactory->create(\AppBundle\Form\SkillType::class, new Skill(), array("csrf_protection" => "false"));
           $form->submit($parameters);
           //var_dump($form->getErrors());
            if ( $form->isSubmitted() ) {
                var_dump('1');
                var_dump($form);
                //var_dump($form->getData());
                /*$skill = $form->getExtraData();
                $this->persistAndFlush($skill);
                return $skill;*/
            }

            return $form;
        }

        /**
         *function persisteAndFlush
         */

        protected function persistAndFlush($object) {
           $this->em->persist($object);
           $this->em->flush();
        }
`

code formtype:

`/**
         * {@inheritdoc}
         */
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder->add('nomComp',TextType::class);
            //$builder->add('submit',SubmitType::class);

        }

        /**
         * {@inheritdoc}
         */
        public function configureOptions(OptionsResolver $resolver)
        {
            $resolver->setDefaults(array(
                'data_class' => 'AppBundle\Entity\Skill',
                "csrf_protection" => "false"
            ));
        }
`

code view:

`{% extends 'base.html.twig' %}
    {% block body %}

    {{ form_start(form) }}

        {{ form_row(form.nomComp) }}

    <input type="submit" value="Create" />
        {{ form_end(form) }}

    {%endblock%}
`

I should this error in $form->getErrors():

> private 'errors' => 
    array (size=1)
      0 => 
        object(Symfony\Component\Form\FormError)[732]
          private 'message' => string 'This form should not contain extra fields.' (length=42)
          protected 'messageTemplate' => string 'This form should not contain extra fields.' (length=42)
          protected 'messageParameters' => 
            array (size=1)
              ...
          protected 'messagePluralization' => null
          private 'cause' => 
            object(Symfony\Component\Validator\ConstraintViolation)[700]
              ...
          private 'origin' => 
            object(Symfony\Component\Form\Form)[457]
              ...

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
