### ISSUE TITLE
Issues in rendering choice type: Array to string conversion (symfony 3.3.10, twig, doctrine)

### ISSUE THREAD

**Issue by kasra-appscore** [symfony/symfony#24790]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
Feature request? | no
BC Break report? | no
RFC?| no
Symfony version  | 3.3.10

I am trying to have a simple dropdown with 2 options (admin,csr) in a form, so that the user be able to update the role if necessary. There is no problem when I use a text type and I am able to change and update the value (in DB):

```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('number', TextType::class, [
                'disabled' => true
            ])
            ->add('code')
            ->add('name')
            ->add('access_level');
    }
```

Twig

```twig
<div class="input-group">
    <span class="input-group-addon hidden-sm">Access Level</span>
    {{ form_widget(form.access_level) }}
</div>
```

But when I change it to be displayed as a dropdown, it's throwing an error as follows:

An exception has been thrown during the rendering of a template ("Array to string conversion"). in form_div_layout.html.twig (line 82)
What am I missing in here:

```php
....
->add('name')
->add('access_level', ChoiceType::class, array(
     'choices' => array(
          'admin' => 'Admin', 
          'csr' => 'CSR'),
 ) );
```

twig: (no changes)

```twig
<div class="input-group">
    <span class="input-group-addon hidden-sm">Access Level</span>
    {{ form_widget(form.access_level) }}
</div>
```

also here is the column type in the entity:

```php
/**
 * @var string
 * @ORM\Column()
 * @JMS\SerializedName("access_level")
 * @JMS\Type("string")
 */
protected $access_level;
```

I changed the form builder like this:

```php
->add('access_level', ChoiceType::class, array( 
        'choices' => array('admin', 'csr'), 
        'choices_as_values' => true, 
```

and it's working now, but it's showing the keys in the dropdown instead of choices! Even after I added 'choices_as_values' => true, it doesn't fix however the choice is stored in the db when I edit the form! Do you have any idea how can I fix it?

**Comment by xabbuh** [comment]
Are you sure that you are using Symfony 3.3? Adding the `choices_as_values` option should not make a difference as `true` is already its default value.

**Comment by kasra-appscore** [comment]
That is really weird and confusing. If I put anything in the key of choices array other than "Admin", it works fine!

```
->add('access_level', ChoiceType::class, array(
     'choices' => array('whateveradfafafa' => 'admin', 'CSR' => 'csr'),
```
But if I change the key to "Admin" it throws ("Array to string conversion") error!

```
->add('access_level', ChoiceType::class, array(
     'choices' => array('Admin' => 'admin', 'CSR' => 'csr'),
```
So I fixed it by adding a space at the end "admin "!

Does anyone have any idea why it's happening?

**Comment by kasra-appscore** [comment]
@xabbuh you are right, it's deprecated in Symfony 3.3, so I removed it!

**Comment by xabbuh** [comment]
You will have to provide a small example project that allows to reproduce your issue then. Otherwise it's impossible to help you.

**Comment by Simperfit** [comment]
Here are the steps to provide a reproducer : 

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by Simperfit** [comment]
@kasra-appscore do you still have an issue ?

**Comment by kasra-appscore** [comment]
Hi @simperfit 
I don't have that issue any more. I put another name for the key and that worked.
