### ISSUE TITLE
DateType storing wrong format date

### ISSUE THREAD

**Issue by shakaran** [symfony/symfony#24791]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.10

I am using a custom type based in DateType and when it stores the date in the database is changing the format, even if I indicate the format in the widget.

This is my code:

```php
<?php

namespace MyApp\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class DatePickerType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
                [
                    'data_class' => null,
                    'widget' => 'single_text',
                    'format' => 'dd/mm/yyyy', // Note here, it will change to default {{ year }}{{ month }}{{ day }} but dd/MM/yyyy will work
                                'html5' => FALSE,
                                'input' => 'datetime',
                                'model_timezone' => 'Europe/Madrid',
                                'view_timezone' => 'Europe/Madrid',
                                 'attr' => [
                                ]
                 ]
                );
    }

    public function getParent()
    {
        return DateType::class;
    }
}  
```     

Note that using  'format' => 'dd/mm/yyyy' will fail [because this line that make a preg_match](https://github.com/symfony/Form/blob/master/Extension/Core/Type/DateType.php#L171) it is not parsing or taking in mind the month in lowercase format and resulting as fallback as [{{ year }}{{ month }}{{ day }}](https://github.com/symfony/Form/blob/master/Extension/Core/Type/DateType.php#L175) which stores in database like yyyy-MM-dd, so I always get corrupted the month value.

So a possible fix could be allow "M" or "m", thats is (M|m) in the regex:

```php
if (preg_match('/^([y(M|m)d]+)[^y(M|m)d]*([y(M|m)d]+)[^y(M|m)d]*([y(M|m)d]+)$/', $pattern)) {
                $pattern = preg_replace(array('/y+/', '/M+/', '/d+/'), array('{{ year }}', '{{ month }}', '{{ day }}'), $pattern);
            }
```

**Comment by Simperfit** [comment]
As i'm reading the comments on the preg_match, I followed the link for ICU, if you look at this, it will tell you that you will need to use MMM or MMMM, for exemple you can look [at the test about MMM in de_AT](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php#L504)

**Comment by shakaran** [comment]
@Simperfit interesting, the problem is that Symfony don't throw or log any message falling in the fallback case, so I didn't notice this until I debug or experience problems with corrupted data in applications. It would be nice if Symfony add at least some warning or even throws a exception if the format is invalid or don't verify the ICU format

**Comment by Simperfit** [comment]
What could be the best behaviour here ? I guess throwing will be a little too much, just logging a warning maybe the same type when the translation is missing ?

Something like, 'The DateTime format %s is not supported in ICU falling back to default format.'

**Comment by shakaran** [comment]
@Simperfit yep, logging the warning at least could be more easily to detect in development or production for avoid the data loss or wrong dates set

**Comment by Simperfit** [comment]
@shakaran Could you provide the PR adding this behaviour.

**Comment by shakaran** [comment]
@Simperfit it seems that you already address some PR to that with trigger_error, which could be a nice solution unless that someone purpose other way to do it

**Comment by ostrolucky** [comment]
Hold on, something doesn't add up here. 

You have specified single_text as widget option. Code you linked is evaluated only if formatter option is set. And formatter option is set only if widget is not set to single_text.

**Comment by Simperfit** [comment]
@shakaran Could you please look what @ostrolucky said, it seems that's more of a misunderstanding than a bug.

**Comment by shakaran** [comment]
@ostrolucky @Simperfit my intention is clear. Use single_text as widget and user formatter option set. I think that it is not a misunderstanding.

The formatter option is set in my code as:

`'format' => 'dd/mm/yyyy'`

And not:

'format' => 'dd/MM/yyyy'

The regex in the code will not allow "m", only "M".

**Comment by ostrolucky** [comment]
@shakaran I wasn't talking about `format` option, but `formatter` attribute. 

Once again, [this block](https://github.com/symfony/symfony/blob/39a5801fc921f34401666248afdacf8f6e4322d1/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L157-L177) is not supposed to be executed in your case, because that condition fullfills only when [this line executes](https://github.com/symfony/symfony/blob/39a5801fc921f34401666248afdacf8f6e4322d1/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L122) And that whole branch is executed only for non single_text widgets. So this is impossible to reproduce for us with given information. Are you able to create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
