### ISSUE TITLE
Performance comparison of 3.3.9 vs 4.0 beta2

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24808]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

We're so close to 4.0 release that I wanted to analyze its performance in comparison with 3.3. If my profiles are correct, then I'm disappointed because Symfony 4.0 is significantly slower, both at `dev` and `prod`.

### Context

The analyzed application was [Symfony Demo](https://github.com/symfony/demo). I used `master` branch for Symfony 3.3.9 and https://github.com/symfony/demo/pull/673 for Symfony 4.0 beta2.

I executed `rm -fr var/cache/*` and `composer dump -o` and restarted my web server before each benchmark (3.3.9 dev, 3.3.9 prod, 4.0 beta2 dev 4.0 beta2 prod).

The environment was PHP 7.1, Apache, SSD disk, OPCache enabled, Xdebug disabled, native PHP (no Docker or VM).

### Results for PROD environment

(differences are from 3.3 to 4.0; positive values means worse performance)

| Page | URL | Time difference | Memory difference | Comparison profile
| ---- | --- | --------------- | ----------------- | -------------------
| Home | `/` | +17% | +4% | [Details](https://blackfire.io/profiles/compare/ab0cda3c-0ebd-4b04-9c42-dcd30f3244f4/graph)
| Blog index | `/en/blog/` | +8% | +0% | [Details](https://blackfire.io/profiles/compare/491ae711-2cdd-40f3-9ab2-572a4bf07bc7/graph)
| Blog show | `/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit` | +12% | +1% | [Details](https://blackfire.io/profiles/compare/6aa3f495-93ab-429f-bb23-9234aaaa69a6/graph)
| Backend index | `/en/admin/post/` | +16% | +0% | [Details](https://blackfire.io/profiles/compare/bc0ae1cc-843c-4f3b-a9c7-c3741aa2282f/graph)
| Backend edit | `/en/admin/post/1/edit` | +10% | +0% | [Details](https://blackfire.io/profiles/compare/db5f7b9f-dae3-411e-ad27-c8388acaee97/graph)

### Results for DEV environment

(differences are from 3.3 to 4.0; positive values means worse performance)

| Page | URL | Time difference | Memory difference | Comparison profile
| ---- | --- | --------------- | ----------------- | -------------------
| Home | `/` | +24% | +10% | [Details](https://blackfire.io/profiles/compare/aa65571c-637e-4eaf-acb0-37a36096916b/graph)
| Blog index | `/en/blog/` | +15% | +6% | [Details](https://blackfire.io/profiles/compare/eaef1abe-ab85-439b-8581-522463b24452/graph)
| Blog show | `/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit` | +16% | +7% | [Details](https://blackfire.io/profiles/compare/ff18c9f8-b391-4d89-9b60-a903fa79a68d/graph)
| Backend index | `/en/admin/post/` | +20% | +8% | [Details](https://blackfire.io/profiles/compare/77d8c1b0-4ce0-440b-82ed-605a55495a89/graph)
| Backend edit | `/en/admin/post/1/edit` | +17% | +6% | [Details](https://blackfire.io/profiles/compare/5244fdf3-046d-4144-8a41-374b0441f22f/graph)

In the `dev` environment, there's an explosion of new function calls. Example:

![function-calls](https://user-images.githubusercontent.com/73419/32373566-26557af2-c09a-11e7-9823-a3a4fb99268e.png)

**Comment by sstok** [comment]
Was this test conducted at an SSD based system or harddisk? And was opcache enabled?

**Comment by xabbuh** [comment]
Is there a special reason you didn't profile the application with a warmed up cache?

**Comment by theofidry** [comment]
@javiereguiluz I think it's important you clarify what kind of performances you are looking for: dev & prod performances.

Obviously dev performances are not as important, although you don't want it to be too slow either.

For production performances, I think the basic optimization steps should be followed otherwise benchmarking them is useless:

- `composer dump-autoload --classmap-authoritative` (it's better than optimized)
- warm up the cache beforehand
- enable opcache with an acceptable expiration time and cache (cf. [this article](https://tideways.io/profiler/blog/fine-tune-your-opcache-configuration-to-avoid-caching-suprises))

**Comment by javiereguiluz** [comment]
I've updated the description with more information:

> The environment was PHP 7.1, Apache, SSD disk, OPCache enabled, Xdebug disabled, native PHP (no Docker or VM).

@xabbuh not sure what do you mean. I cleared the cache and fully regenerated it before performing each benchmark. In any case, if I did it wrong, I did the same for all benchmarks, so it doesn't matter.

@theofidry prod is more important, but dev is super important. "dev" is what you see all day every day as a developer. It can't be slow.

**Comment by wouterj** [comment]
> @xabbuh not sure what do you mean. I cleared the cache and fully regenerated it before performing each benchmark. In any case, if I did it wrong, I did the same for all benchmarks, so it doesn't matter.

Your PR description only says you cleared the cache, not fully regenerated it. It's better to always start with a freshly warmed-up cache, as that's the case with your prod app normally as well.

**Comment by cordoval** [comment]
don't show percentages, show ms response time for both columns and amount of RAM, percentages are sometimes deceiving

**Comment by theofidry** [comment]
@cordoval a percentage can be consistent from a machine to another whereas the time can greatly differ

**Comment by cordoval** [comment]
you need always a scale, just as a reference, when you take a look at google maps you have a horizontal bar of 1 mile or 1 kilometer to give you the idea of the scale, that is.

**Comment by dmaicher** [comment]
I have some similar results on my biggest app when comparing `3.3.10` vs `3.4.0-BETA2`.

I used `ab -n 10000 -c 1 ...` and:

-  `prod` env + `debug=false` 
- `composer dump --classmap-authoritative`
- warmed up cache
- opcache enabled
- restarted php 7.1 fpm before each run

The only package changed is `symfony/symfony`.

I tried each version multiple times and the results are consistent to +- 0.5ms.

| page  | mean time per request 3.3.10 | mean time per request 3.4.0-BETA2 | diff |
| ------------- | ------------- | ---- | --- |
| html page with heavy twig template rendering | 40.697 ms | 49.621 ms | +21,9% |
| json api endpoint | 24.992 ms | 29.555 ms | +18,2% |

**Comment by cordoval** [comment]
which new PRs/changes those function call explosion is coming from/correcto to? from the components or classes?

**Comment by nicolas-grekas** [comment]
As always, reproducer welcomed.

**Comment by dmaicher** [comment]
I'm currently doing binary search to find the commit :smile: Went back quite a few commits on 3.4 and now its the same performance as 3.3. Will let you know once I found out more.

**Comment by dmaicher** [comment]
This is a part of the git history of 3.4:

```
commit a442e378e18d399e942bcffe0c2e960fcdc0b53f
Merge: 537c496 fa62e50
Author: Fabien Potencier <fabien.potencier@gmail.com>
Date:   Thu Sep 28 16:21:02 2017 -0700

    feature #24362 [HttpKernel] Deprecate some compiler passes in favor of tagged iterator args (nicolas-grekas)

    ...

commit 537c496dfee1d04aab832f8441f8b6cfe7dc2af5
Merge: c7f664c 95358ac
Author: Fabien Potencier <fabien.potencier@gmail.com>
Date:   Thu Sep 28 16:19:46 2017 -0700

    minor #24366 [Lock] Use cache connection factories in lock (jderusse)
    
    ...
```

The last commit where 3.4 is equally fast as 3.3 is `537c496dfee1d04aab832f8441f8b6cfe7dc2af5`. The commit after (`a442e378e18d399e942bcffe0c2e960fcdc0b53f`) slows it down for me.

https://github.com/symfony/symfony/compare/537c496dfee1d04aab832f8441f8b6cfe7dc2af5...a442e378e18d399e942bcffe0c2e960fcdc0b53f

@nicolas-grekas any idea?

**Comment by nicolas-grekas** [comment]
No idea, if anything, this should impact compile time only, but the bench are about runtime diffs?
A Blackfire comparison could maybe help?

**Comment by dmaicher** [comment]
Ok after some profiling, debugging and slack discussions with @nicolas-grekas I think we found the issue:

https://github.com/symfony/symfony/compare/537c496dfee1d04aab832f8441f8b6cfe7dc2af5...a442e378e18d399e942bcffe0c2e960fcdc0b53f#diff-687bdbb38a4dc672ca2a79f23e764892L127

Replacing this compiler pass with a "tagged argument" is now also done for debug=false whereas before it was only added for debug=true. Means now the `ResourceCheckerConfigCache` constantly iterates over all resourcecheckers and checks if the cache is still fresh which obviously takes time.

I will work on a PR to fix the issue.

**Comment by dmaicher** [comment]
@javiereguiluz can you benchmark the symfony demo again with this change?

https://github.com/symfony/symfony/pull/24824/files#diff-0e793081ceb720201745c982a568903fR364

For me the performance is now pretty much the same again as on 3.3.

**Comment by javiereguiluz** [comment]
@dmaicher I've tested your patch and it improves things a lot. Instead of ~15% worse performance, now I see just ~4% worse performance.

But your patch is only for `prod`, so `dev` is still ~20% slower. Maybe somewhere we could optimize things to not make so many new function calls:

![function-calls](https://user-images.githubusercontent.com/73419/32418349-65482d66-c268-11e7-9a12-30f68eeead4d.png)

**Comment by dmaicher** [comment]
@javiereguiluz ok thanks for confirming. My patch does not have any impact on `dev` environment indeed.

Maybe we should reopen here? the +20% for dev are indeed a bit too much I guess :cry:

**Comment by artasorm** [comment]
I have similar results here : [phpbenchmarks.com]( http://www.phpbenchmarks.com/fr/comparator/compare.html?components=symfony-3.3~symfony-3.4~symfony-3.0&benchmarkType=all&benchmarkTools=apache-bench&phpVersions=php-7.1&concurrencies=)

Each Symfony version drop down query per seconds :(

**Comment by steevanb** [comment]
I have similar results here : [phpbenchmarks.com]( http://www.phpbenchmarks.com/fr/comparator/compare.html?components=symfony-3.3~symfony-3.4~symfony-3.0&benchmarkType=all&benchmarkTools=apache-bench&phpVersions=php-7.1&concurrencies=)

Each Symfony version drop down query per seconds :(

**Comment by nicolas-grekas** [comment]
@steevanb interesting! Can you show me where cache warmups happens for Symfony? I don't see it in https://github.com/phpbenchmarks/symfony-3-4 but maybe I missed it?

**Comment by steevanb** [comment]
You can find benchmark protocol here :
http://www.phpbenchmarks.com/en/benchmark-protocol

`#1` Include `init_benchmark.sh`, and call `init()` ( https://github.com/phpbenchmarks/symfony-3-4/blob/master/init_benchmark.sh for Symfony 3.4).
`#2` Restart `php-fpm` service, to reset `OPCache` etc.
`#3` Cache warmup isn't enough, it do not generate all caches. So, i make a first "non saved" benchmark, with 1,000 calls (instead of 50,000 for the real one), concurrency 1, to be sure all caches and OPCache are OK.

**Comment by nicolas-grekas** [comment]
@steevanb there is one step missing: calling `bin/console cache:warmup`, this one is required to generate some caches that will not be created by just hitting the first 1000 times.

**Comment by dmaicher** [comment]
Just FYI: I benchmarked again two pages (html page and a json api endpoint mentioned above) with `3.3.10` vs `3.4.0-BETA3` using `ab -n 10000 -c 1 ...` and I cannot see any relevant difference between both. Equal performance in my benchmarks.

**Comment by sroze** [comment]
> calling bin/console cache:warmup, this one is required to generate some caches that will not be created by just hitting the first 1000 times

@nicolas-grekas interesting. Which ones?

**Comment by nicolas-grekas** [comment]
eg the annotations' cache

**Comment by info-droid** [comment]
Humm, didn't know that ... Are you sure `cache:warmup` do something that calling url will `never` do ?

If it's true, for now i'm lucky, i don't use annotation. But that's weird.

**Comment by steevanb** [comment]
Humm, didn't know that ... Are you sure `cache:warmup` do something that calling url will `never` do ?

If it's true, for now i'm lucky, i don't use annotation. But that's weird.

**Comment by nicolas-grekas** [comment]
Yes I am :)

**Comment by steevanb** [comment]
Ok, good information ! I don't think it will change my results for now, but i will add it for news benchmark.

Thanks !

**Comment by theofidry** [comment]
Well it's unlikely to be an issue unless for benchmarks and read-only environments which is why the issue can easily get unnoticed

**Comment by sroze** [comment]
@nicolas-grekas is there any reason for that? Shouldn't we generate the caches at the first request?

**Comment by nicolas-grekas** [comment]
That's always been the case in fact: cache warmers are heavy processes. Eg parsing ALL Twig templates on the first request, of ALL annotations, etc. would mean paying a high price in dev.
Then, having ALL annotations (there are others) at hand still allows to generated an even more optimize cache pool (a single PHP file that OPCache can cache.)
I don't think we can improve process, as its logical. But as @theofidry said, that's not bad anyway, you just won't have the extra perf benefit you could achieve. Not a big issue usually.
