### ISSUE TITLE
Report an asset issue

### ISSUE THREAD

**Issue by nimasdj** [symfony/symfony#24803]
As I said here https://github.com/twigphp/Twig/issues/2577#issuecomment-341540954, that's really an issue. Assets should not add a leading slash, but it must be exactly the same as provided in code, otherwise they are not found.

```
$namedPackages = array(
    'img' => new PathPackage('path/to/images', $versionStrategy),
);
```

**Comment by nimasdj** [comment]
Thanks for review. When I use {{ asset() }} it prints something like "/twig/css/styles.css" that leading / is a problem to not found css. I defined the path like "twig/css". Assets should not add leading /. The css path must be intact without leading / something like "twig/css/styles.css". When I hardcode this path it works fine.

**Comment by xabbuh** [comment]
IMO that's expected and the base path passed to the `PathPackage` constructor must be given from the path of your entry point. You can optionally pass a context if your application is hosted under a subpath of your web root.

**Comment by nimasdj** [comment]
Please give example of both ways. Thanks.

**Comment by xabbuh** [comment]
You just have to pass an object that implements the `ContextInterface` as the third argument when constructing the `PathPackage`. This interface requires a `getBasePath()` method where you return the base path to your application. If you use Symfony or any other application that makes use of the HttpFoundation component, you can make use of the `RequestStackContext` class which allows to use the current `Request` instance.

**Comment by nimasdj** [comment]
As you said that RequestStackContext implements ContextInterface with getBasePath method, I did so and passed the instance as third parameter to PathPackage. But no changes yet in css path, there is still a leading / that causes problem to not found the css. what wrong I did? Please advise.

```
use Symfony\Component\Asset\Context\RequestStackContext;
use Symfony\Component\HttpFoundation\RequestStack;

$namedPackages = array(
    'css' => new PathPackage('themes/'.$theme_name.'/css', $versionStrategy, new RequestStackContext(new RequestStack())),
);
```

**Comment by xabbuh** [comment]
Well, you not only need to pass an empty request stack to the context, but you need to put the current request onto the stack. Anyway, this is something you should solve using [one of the support channels](https://symfony.com/support). I am going to close here as we do not use GitHub for support. Thank you for understanding.

**Comment by nimasdj** [comment]
Ok, here I posted on SO would you please advise there? I appreciate your time.
https://stackoverflow.com/questions/47084035/how-to-remove-symfony-asset-leading-slash
@xabbuh

**Comment by nimasdj** [comment]
I did a print debug as code below and noticed it returns nothing. I don't know why. I created my own class implementing ContextInterface using HttpFoundation and it works fine now! Thank you. But now the question is that why code below returns nothing?

```
use Symfony\Component\Asset\Context\RequestStackContext;
use Symfony\Component\HttpFoundation\RequestStack;

$con = new RequestStackContext(new RequestStack);
print($con->getBasePath());
```
@xabbuh

**Comment by xabbuh** [comment]
Well, you just pass an empty request stack to the context. So there is no request that could be used to determine the base path.

**Comment by nimasdj** [comment]
How to pass request stack? Please give example.

**Comment by nimasdj** [comment]
I did so 

```
$stack = new RequestStack();
$stack->push(Request::createFromGlobals());
$context = new RequestStackContext($stack);
```

Then pass $context as third parameter. However it works fine now, I just wanted to ask if this is correct usage and good practice? or needs improvements?
@xabbuh
