### ISSUE TITLE
Translations not extracted via debug:translation with Flex structure

### ISSUE THREAD

**Issue by baptistedonaux** [symfony/symfony#24807]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-BETA2
| Flex | yes

My project is based on Flex structure. My application find translation in server mode.

Now, I would like display translations with `debug:translation` I can only displayed bundles translations but not mine.

After few investiguations, `TranslationDebugCommand` search my translation in `/src/Resources` whereas my translations are located at `/translations`.

I ask me why this command doesn't use `translator` service to retrieve catalogues ? This component could be standalone for Symfony standard or Symfony Flex in using `translator` service.

**Comment by baptistedonaux** [comment]
Same problem with translation keys extracted from templates, search into `/src/Resources/views` instead of `/templates`

**Comment by chalasr** [comment]
See https://github.com/symfony/symfony/pull/24590

**Comment by chalasr** [comment]
fixed by 25065
