### ISSUE TITLE
can't print error message when a service class have error

### ISSUE THREAD

**Issue by lcp0578** [symfony/symfony#24806]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.39

When i make a error in my service, after register it.
In dev environment.
It is blank, http code is 500, not any error message.
When i clear cache
```
$ php bin/console cache:clear
PHP Fatal error:  Redefinition of parameter $type in D:\xampp\htdocs\kitlabs\oa\
src\BaseBundle\Service\SmsService.php on line 122

Fatal error: Redefinition of parameter $type in D:\xampp\htdocs\kitlabs\oa\src\B
aseBundle\Service\SmsService.php on line 12
```

I hope catch exception.
Thanks

**Comment by chalasr** [comment]
Seems like a problem with your webserver/php configuration, not a Symfony bug.
We use github issues for bug reports and feature requests only, you should find help on [support platforms](https://symfony.com/support). Thanks for your understanding.

**Comment by lcp0578** [comment]
thanks
