### ISSUE TITLE
Routes priority - Extraloader

### ISSUE THREAD

**Issue by darkiron** [symfony/symfony#24812]
Hi,
How to defined route priority in Extraloader. 
By default all route defined in ExtraLoaders was first. 
I want my programmatically route was first to escape with error : 
No route found for "GET /page-de-test". 
I can have some tips ?

Thx

**Comment by xabbuh** [comment]
Which extra loader are you talking about?

**Comment by darkiron** [comment]
By custom loader 
https://symfony.com/doc/current/routing/custom_route_loader.html#creating-a-custom-loader

**Comment by xabbuh** [comment]
Routes are loaded in the order they are listed in your routing config.

Anyway, as this does not look like a bug report I am going to close here. Please use on of the [support channels](https://symfony.com/support) to seek help with your code or open an issue in the [docs repository](https://github.com/symfony/symfony-docs) if you think that the documentation needs to be improved.
