### ISSUE TITLE
how to create customised error page in symfony ?

### ISSUE THREAD

**Issue by mmshivukumar** [symfony/symfony#24817]
Dear Team,

i have followed documentation in symfony in creaating customised errorr page.

```
app/
└─ Resources/
   └─ TwigBundle/
      └─ views/
         └─ Exception/
            ├─ error404.html.twig
            ├─ error403.html.twig
            ├─ error.html.twig      # All other HTML errors (including 500)
            ├─ error404.json.twig
            ├─ error403.json.twig
            └─ error.json.twig      # All other JSON errors (including 500)
```

set even 

```yaml
# app/config/routing_dev.yml
_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
```

still custom  page is not displaying 
please help to get solution

thanks
shivukumar

**Comment by javiereguiluz** [comment]
The templates you showed are the correct ones. I'm using them in lots of different projects and they work, so you can create those templates. Then in the app, you must be in `prod` environment to see those custom errors ... or visite `/_error/xxx` where `xxx` is the HTTP Status Code of the error you want to see (`/_error/500`, `/_error/404`, etc.)

If this doesn't work, please go to https://symfony.com/support and see the support channels available to answer questions like this one. Thanks!

**Comment by chen-gloria** [comment]
> ```yaml
> _errors:
>     resource: "@TwigBundle/Resources/config/routing/errors.xml"
>     prefix:   /_error
> ```

Does that mean the documentation is wrong? https://symfony.com/doc/current/controller/error_pages.html#example-404-error-template

Since it doesn't have `views` in the folder.

**Comment by stof** [comment]
@chen-gloria no. the doc is right for the Symfony 5+ folder structure. The one in this ticket from 2017 is based on the old folder structure from Symfony 3.

**Comment by chen-gloria** [comment]
> @chen-gloria no. the doc is right for the Symfony 5+ folder structure. The one in this ticket from 2017 is based on the old folder structure from Symfony 3.

I actually just used the [doc](https://symfony.com/doc/current/controller/error_pages.html#example-404-error-template) trying to overwrite error page this afternoon (I'm using Symfony 5.3). I did `composer require symfony/twig-pack` as what the [doc](https://symfony.com/doc/current/controller/error_pages.html#example-404-error-template) said. But I found no Twig in the vendor. So I guess the [doc](https://symfony.com/doc/current/controller/error_pages.html#example-404-error-template) is outdated. There is `ErrorHandler` (which I found source code is [here](https://github.com/symfony/error-handler)), but no Exception Twig. Only when you change views [here](https://github.com/symfony/error-handler/tree/5.4/Resources/views), the error page will change. I still haven't found a way to overwrite my error pages yet.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
@chen-gloria make sure you follow the doc from the start of the section about customizing error pages: https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates
If you don't have Twig in your vendor folder, it means you haven't done the first step.

**Comment by chen-gloria** [comment]
> @chen-gloria make sure you follow the doc from the start of the section about customizing error pages: https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates If you don't have Twig in your vendor folder, it means you haven't done the first step.

I turned off the dev environment and it works now. I guess it is just because I was in dev mode. The Twig overwrite works fine.
I just added  `APP_DEBUG=0` to my `.env` file. Thanks a lot!

**Comment by chen-gloria** [comment]
> Can you create a small example application that allows to reproduce your issue?

Turned off the DEBUG mode and it works now. Thanks!

**Comment by chen-gloria** [comment]
Direct you to [this discussion](https://github.com/symfony/symfony/discussions/44425) where I just explained what I've done with my problem. Thank you all!
