### ISSUE TITLE
Debug component is not taking a fatal error as exception

### ISSUE THREAD

**Issue by mcapodacqua** [symfony/symfony#24811]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

The next script will generate a fatal error:
```php
        Debug::enable();
        $a = new \stdClass();
        $a->foo = 'bar';
        var_export($a['foo']);
```
When I execute the script I get this message:
> Fatal error: Cannot use object of type stdClass as array ....

Since I'm starting my script with `Debug::enable();` I expect to see that fatal error as an exception.

Here is an example of a fatal error handled as an exception by the Debug component:
```php
        Debug::enable();
        $a = function ($b) {};
        $a();
```
In that example, the execution throws a `Symfony\Component\Debug\Exception\ContextErrorException`:
>   [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                        Warning: Missing argument 1 for ...

**Comment by Simperfit** [comment]
I can't reproduce it, both are throwing FatalThrowableError : 

https://github.com/Simperfit/symfony-reproducer/blob/master/src/Command/DebugTestCommand.php#L34

**Comment by Simperfit** [comment]
Status: Waiting Feedback

**Comment by Simperfit** [comment]
Status: Waiting feedback

**Comment by jakzal** [comment]
@mcapodacqua which version of PHP you're on? 

On PHP 7 both cases will throw FatalThrowableError as @Simperfit pointed out.

**Comment by Simperfit** [comment]
@mcapodacqua Could you please respond to @jakzal's comments ?

**Comment by xabbuh** [comment]
I am closing here for now due to the lack of feedback. We can consider to reopen if anything new comes up.
