### ISSUE TITLE
Script is failing regardless of the correct permission been set, any idea why of this behavior?

### ISSUE THREAD

**Issue by empiricalx** [symfony/symfony#24830]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.10

private function write($file, $data, $expiresAt = null)
    {
        set_error_handler(__CLASS__.'::throwError');
        try {
            if (null === $this->tmp) {
                $this->tmp = $this->directory.uniqid('', true);
            }
            file_put_contents($this->tmp, $data);

            if (null !== $expiresAt) {
                touch($this->tmp, $expiresAt);
            }

            return rename($this->tmp, $file);
        } finally {
            restore_error_handler();
        }
    }

Error: 
[2017-11-05 10:59:53] cache.WARNING: Failed to save key "%5BAppBundle%5CEntity%5CCmmsAccount%24created%40%5BAnnot%5D%5D%5B1%5D" (array) {"key":"%5BAppBundle%5CEntity%5CCmmsAccount%24created%40%5BAnnot%5D%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/cmmsassist/var/cache/prod/pools/RI4N7D-rJr/59ff5fa90279b2.13977301): failed to open stream: Permission denied at /var/www/cmmsassist/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php:87)"} []

**Comment by curry684** [comment]
Please provide more context and properly layout your code. Without more information on what you are trying to achieve and how your question is impossible to answer.

Venturing a wild guess: try `chmod -R 777 var/*` in your Symfony install folder.

**Comment by empiricalx** [comment]
The context is simple, FormObject to EntityObject, Persist and Flush... then Crash with the unable to write on cache folder. I have already done the recursive chmod and it didn't work. Reading about this issue it talks about apc cache, but I was under the assumption that apc is only available for php 5 and below not for php 7. I been unable to find how to change this setting and what file holds the cache configuration (newbie here). Just a critic, this is frustrating, this framework is mature enough that should allow to fix this kind of problem easy and without spending hours researching where this issue is coming from.  I have seen many threats reporting the same issue and 0 solution to the problem.

**Comment by empiricalx** [comment]
Problem fix by enabling OPCache on php.ini. How and why?, I have no clue, that is the issue with frameworks, it get so obscure that things get corrected without knowing for sure the real reason for the failure. It seems the object were unable to be cached because the default caching was apc and wasn't available, this is my assumption I could be wrong.

**Comment by curry684** [comment]
That would actually make it a PHP problem, not a framework problem.

**Comment by empiricalx** [comment]
One can't live without the other, therefore it must be taking into consideration to avoid issues. Documenting it and offering the user alternatives is as good thing.  If it is a requirement to have caching system in place because it may cause issues, telling the user about it and giving instruction how to troubleshoot the issue and to actually solved it is not a triviality or unimportant.
