### ISSUE TITLE
Improve performance of TraceableFirewallListener

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24838]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

While analyzing Symfony 4 performance (see #24808) I saw that [TraceableFirewallListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Debug/TraceableFirewallListener.php) is super slow. It's about 20 times slower than the average debug listener (~22ms vs. ~1ms):

![traceable-firewall-listener](https://user-images.githubusercontent.com/73419/32435311-da066e1a-c2e0-11e7-9e2f-ba38f7b4e1df.png)

It's not a Symfony 4 thing. In previous Symfony versions this was called FirewallListener and it was also 20 times slower:

![firewall-listener](https://user-images.githubusercontent.com/73419/32435347-ed5b49cc-c2e0-11e7-900d-add3cc81d866.png)

I just open this issue in case someone experienced in the Security bundle can take a look and see if this can be optimized somehow. Thanks!

**Comment by backbone87** [comment]
maybe its about the __call magic? https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php#L54

**Comment by sroze** [comment]
From what I can see, it looks like it is because this listener is the first one using a lot of the services from the container. Therefore, it looks like most of the time is within the firewall processing itself, but it is spent loading services.

**Comment by chalasr** [comment]
It does not surprise me, this event listener loops over all security listeners which are heavy themselves (each one having a considerable amount of dependencies). 
Do you know if there is a considerable difference with the normal `FirewallListener` (i.e. in non-debug mode)? If it's particularly slow in debug mode, maybe we can try to improve it.

**Comment by javiereguiluz** [comment]
@chalasr this is the profile of the 4.0 beta3 in prod: https://blackfire.io/profiles/501af859-6695-4df1-ad5c-9f69761967a8/graph  FirewallListener is the slowest listeners, but it takes ~5ms instead of ~22ms in `dev`.

In any case, maybe it's OK that this listener is so slow compared with others. I just wanted to call attention into this in case we could improve it. Maybe we can't and that's OK. Cheers.

**Comment by raziel057** [comment]
@javiereguiluz Thanks for taking care of possible performance regression. There is often few penalties in each new release of Symfony. It's not always important but when you start to cumulate the loose of execution time through the different releases it can be more important.

**Comment by havvg** [comment]
Just stumbled on this issue; I have the same bad performance with Symfony 3.3

![screen shot on 2017-11-12 at 12 3a15 3a57](https://user-images.githubusercontent.com/126898/32698296-6e6cd69a-c7a3-11e7-9c5f-2c2f6ea26758.png)

**Comment by nicolas-grekas** [comment]
I think we can close this issue as recent perf improvements in 3.4 should have removed most of the overhead (nothing we can do for 3.3 @havvg, move to 3.4 once it's released.)

**Comment by havvg** [comment]
@nicolas-grekas if I'm not mistaking, the issue is about Symfony 3.4/4.0. I just added, that the issue is not new, but already existed. Although I can confirm, that it is better on Symfony 3.4 BETA.

```
composer require symfony/symfony:^3.4-BETA
    1/8:	http://packagist.org/p/provider-latest$dcfb36a2c0d2359435b96cb7367069e266290f86581e7bd05da5989454ca6127.json
    2/8:	http://packagist.org/p/provider-2017-10$0050f4465aa962788cd3257f6adc16ed3f212376197e3ccf77ccd63b4e9afc6e.json
    3/8:	http://packagist.org/p/provider-2014$45e2eccd37e55d49168a07eaf2cf55ce50bb87096a754b74310b45c80ca028d7.json
    4/8:	http://packagist.org/p/provider-2017-07$b8c4f320b200a83b95b4670fe64d95155d00873319a5446bc88c1faa59275f75.json
    5/8:	http://packagist.org/p/provider-2015$d0dd953b40fc841092ba6acd1292ae835172fa5dd902ece3e537cafa2cb44d83.json
    6/8:	http://packagist.org/p/provider-2017-01$af75825b5ef1d352eeddd305982222ff18ea6f35af59a0acbf2f00d2835d1841.json
    7/8:	http://packagist.org/p/provider-2017-04$abea449965b0da5211af0fbf334f785c395de703ca168c380ff953ff9d029f90.json
    8/8:	http://packagist.org/p/provider-2016$2ddc6daea6ac00bab23515f293d7a1abcc8a06f7bf21dd5a4e4c52f48c8006d3.json
    Finished: success: 8, skipped: 0, failure: 0, total: 8
./composer.json has been updated
    1/8:	http://packagist.org/p/provider-2017-10$0050f4465aa962788cd3257f6adc16ed3f212376197e3ccf77ccd63b4e9afc6e.json
    2/8:	http://packagist.org/p/provider-latest$dcfb36a2c0d2359435b96cb7367069e266290f86581e7bd05da5989454ca6127.json
    3/8:	http://packagist.org/p/provider-2017-01$af75825b5ef1d352eeddd305982222ff18ea6f35af59a0acbf2f00d2835d1841.json
    4/8:	http://packagist.org/p/provider-2015$d0dd953b40fc841092ba6acd1292ae835172fa5dd902ece3e537cafa2cb44d83.json
    5/8:	http://packagist.org/p/provider-2016$2ddc6daea6ac00bab23515f293d7a1abcc8a06f7bf21dd5a4e4c52f48c8006d3.json
    6/8:	http://packagist.org/p/provider-2014$45e2eccd37e55d49168a07eaf2cf55ce50bb87096a754b74310b45c80ca028d7.json
    7/8:	http://packagist.org/p/provider-2017-04$abea449965b0da5211af0fbf334f785c395de703ca168c380ff953ff9d029f90.json
    8/8:	http://packagist.org/p/provider-2017-07$b8c4f320b200a83b95b4670fe64d95155d00873319a5446bc88c1faa59275f75.json
    Finished: success: 8, skipped: 0, failure: 0, total: 8
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://codeload.github.com/symfony/symfony/legacy.zip/1ae23efa1eaf48dea8c0f382fc9c339e08fa113f
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 0 installs, 1 update, 0 removals
  - Updating symfony/symfony (v3.3.10 => v3.4.0-BETA3): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Changelogs summary:

 - symfony/symfony updated from v3.3.10 to v3.4.0-BETA3
   See changes: https://github.com/symfony/symfony/compare/v3.3.10...v3.4.0-BETA3
   Release notes: https://github.com/symfony/symfony/releases/tag/v3.4.0-BETA3

> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/environments/parameters.yml" file
> Application\Composer\BootstrapHandler::ensureDirectoriesExist
Ensuring the var directory exists.
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug
 // true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

```

![screen shot 2017-11-12 at 18 12 11](https://user-images.githubusercontent.com/126898/32701413-1d8f5a86-c7d5-11e7-9ebe-f54968a34989.png)

**Comment by ossinkine** [comment]
Since security listeners are heavy themselves, maybe it makes sense to log timing of security listeners separately?

**Comment by chalasr** [comment]
@ossinkine you mean https://github.com/symfony/symfony/pull/23105? :)

**Comment by javiereguiluz** [comment]
@chalasr I forgot about that 😱  Here are the details per listener:

![security-listeners-details](https://user-images.githubusercontent.com/73419/32841789-9824d8b4-ca1b-11e7-8b72-c06fb7612bb9.png)

**Comment by nicolas-grekas** [comment]
I'm sorry but this is not a valid issue. There can be a lot of reasons for this long bar. There is no "done" definition I can think of for this.

**Comment by gstolarz-euvic** [comment]
Symfony 3.4.4.
![selection_241](https://user-images.githubusercontent.com/33423096/37903643-eb3e1ecc-30f8-11e8-998b-f8c4c6c6af51.png)
Is this issue closed?

It's working on development machines but on test environment still crashes.

**Comment by er1z** [comment]
I confirm, it takes a bit long.

**Comment by ryancastle** [comment]
If you are seeing very slow times in the TraceableFirewallListener using HTTP Basic authentication, there's a good chance it's the `bcrypt` encoder verifying the password on every request. Because there is no session it has to process the password every time, and the processing the the bcrypt and argon2i encoders is deliberately very slow.

Switching to form/session authentication dropped the time spent in the firewall from 700ms down to 10ms.

**Comment by develth** [comment]
After Update from 3.4.3 to 3.4.11. the requests are pretty slow, the TraceableFirewallListener is about > 10000ms per request. I´m not running the authentication with HTTP Basic.
I run the application on the same server with 3.4.3 against the same database server, and it performs like it should - fast.

**Comment by Joozty** [comment]
Same problem here :/

**Comment by nicolas-grekas** [comment]
To anyone experiencing this issue: `TraceableFirewallListener` is just a wrapper, it does not take time by itself.
Please use a real profiler (e.g. https://blackfire.io) to know what is consuming resources.

I'm locking this issue so that nobody will expect anything to happen by commenting here anymore.
