### ISSUE TITLE
[DoctrineBridge] clean up .class parameters

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/symfony#24835]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 4.0.0

In ExtensionClass of DoctrineBridge several services are defined by using a parameter with `*.class` This should be replaced by a kind of a configuration or an alias. 
One the one hand we decided to abandon those class parameters and on the other hand they are extremely hidden doing it that way.

**Comment by fabpot** [comment]
@ElectricMaxxx Would you like to work on this one? Is it worth it?

**Comment by ElectricMaxxx** [comment]
I can try to do so next days. can be funny as the parameters mostly defined in extension class.

**Comment by dbu** [comment]
what would the solution be? the doctrine bundles prepending configuration for the bridge? we have to avoid manual steps where the user must configure the bridge in a specific way.

**Comment by ElectricMaxxx** [comment]
Sorry for the delay, i am currently on it. If somebody has some insight for me, that would be nice looking into the extension class  is really hard as used to for every extension class in doctrine namespace.

**Comment by fabpot** [comment]
Let's close as nobody really took the time to do it.
