### ISSUE TITLE
Session always started after 3.4.0-BETA3 update

### ISSUE THREAD

**Issue by joker806** [symfony/symfony#24849]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.4.0-BETA3

I have Apache2 + PHP-FPM setup and after update to 3.4.0-BETA3 (from BETA1) I encountered a problem with Apache returning 304 for all consequent requests on a single URL. Even if response body sent from PHP changed.

This is expected behaviour in case when client sends `If-Modified-Since` and PHP response with `Last-Modified` header. The problem is that the `Last-Modified` header is sent even if I don't set the header by myself.

I was able to trace down the problem to the commit 95d0b72. It removes explicit check for a started session in `RequestDataCollector::onKernelResponse` and then by calling `$event->getRequest()->getSession()->has('sf_redirect')` it triggers `session_start()` which directly sends `Last-Modified` header.

Here is dump of `headers_sent()` at end of request for BETA2 and BETA3:

```
# BETA2
array(4) {
  [0]=>
  string(32) "Cache-Control: no-cache, private"
  [1]=>
  string(35) "Date: Tue, 07 Nov 2017 07:23:35 GMT"
  [2]=>
  string(30) "Content-Type: application/json"
  [3]=>
  string(21) "X-Debug-Token: 1366e0"
}
```

```
# BETA3
array(6) {
  [0]=>
  string(33) "Cache-Control: private, max-age=0"
  [1]=>
  string(44) "Last-Modified: Tue, 07 Nov 2017 07:25:09 GMT"
  [2]=>
  string(32) "Cache-Control: no-cache, private"
  [3]=>
  string(35) "Date: Tue, 07 Nov 2017 07:28:31 GMT"
  [4]=>
  string(30) "Content-Type: application/json"
  [5]=>
  string(21) "X-Debug-Token: ad9ad3"
}

```

**Comment by joker806** [comment]
I forget to note that this is API project so I don't use sessions at all. Even the firewall in `security.yml` is configured as stateless.

**Comment by sroze** [comment]
That was the only way for us to ensure all the features of the WDT are working properly... 

TBF, I was expecting the session to be started only when something is written to it. Should  `session->has('...')` really start the session? 🤔

**Comment by nicolas-grekas** [comment]
The session start is expected, but the Last-Modified header is not, we need to find a way to remove it.

**Comment by nicolas-grekas** [comment]
@sroze that's common misconception, but to answer this "has", you must ask the session backed, thus start the session. And the Cache-Control is required, because the response really depends on the conditional.

**Comment by joker806** [comment]
You can prevent sending headers by setting `cache_limiter` option of `NativeSessionStorage` to `0` (as noted in doc), but:
1) there is no way to do it from framework config
2) is it OK to even start the session if my firewall is configured to be stateless?

**Comment by emodric** [comment]
Possibly related to https://github.com/symfony/symfony/issues/24690 ?

**Comment by stof** [comment]
@joker806 the firewall being stateless means that the firewall will not use the session. This has no effect at all on other parts of the framework.
If you don't want to use sessions at all, you can force disabling sessions entirely in the FrameworkBundle config (this is useful if your project is entirely an API, but won't be possible if it mixes an API and a normal website needing the session)
