### ISSUE TITLE
Object data not accessable from {form}.vars.data.{param}

### ISSUE THREAD

**Issue by Diarselimi** [symfony/symfony#24844]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 2.8.2

When I try to access the data from the child element of the form it shows me an error that could not access the attribute in my case it's called imageCategory.

`Impossible to access an attribute ("imageCategory") on a null variable.`

even though when i dump the `{form}.vars.data` It shows the data but as private
`SurveySlideCategory {#2176 ▼
  -id: 23
  -imageCategory: CategoryImage {#2196 ▶}
  -slide: Slide {#1690 ▶}
  -category: null
}`

Keep in mind that this happens when I try to access the data from a child element of the parent form.

This is the form that im trying to access the data from 
These are the forms `Surveytype >has> SlideType >has> SurveySlideCategoryType`
![forms](https://image.ibb.co/gMNKQw/Screen_Shot_2017_11_06_at_18_49_27.png)

And this is the view where im trying to access the data from 
![this is the view](https://image.ibb.co/n0sVXb/Screen_Shot_2017_11_06_at_18_51_02.png)

In the twig view line: 5 when i try to access the values i get the error as explained above.
You have the dump of the data for the .vars.data above.

**Comment by xabbuh** [comment]
Please show us some concrete code that you are using. Without it we cannot really tell you what's going on.

**Comment by Diarselimi** [comment]
@xabbuh I've updated the post maybe it's better now, the other parts controller and entity are with the default configuration.

**Comment by jakzal** [comment]
@Diarselimi I find there's still not enough info to understand your issue. It'd be the best if you forked standard edition and followed these steps: https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
