### ISSUE TITLE
Bootstrap 4 form themes validation errors styling not working on Symfony 3.4

### ISSUE THREAD

**Issue by nullstrike** [symfony/symfony#24841]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

I'm currently studying this framework lately and I'm working on server-side form validation. I'm using Bootstrap 4 for styling my form but after setting a NotBlank validator it print only the validation error message but not styling like adding has-error class on the parent div of the input field. 
The first screenshot is from google chrome v62:
![screenshot from 2017-11-06 20-50-59](https://user-images.githubusercontent.com/29997879/32441934-73d331a6-c334-11e7-9d98-0dba96781ffe.png)

The second screenshot is from mozilla firefox 57
![screenshot from 2017-11-06 20-52-15](https://user-images.githubusercontent.com/29997879/32441935-740951b4-c334-11e7-9ea0-d7efa10b58ab.png)

Here's the html generated by the Form Builder
```
<form name="app_bundle_customer_form_type" method="post">
    <div id="app_bundle_customer_form_type">
        <div class="form-group">
            <label class="form-control-label required" for="app_bundle_customer_form_type_name">Name</label>
            <input type="text" id="app_bundle_customer_form_type_name" name="app_bundle_customer_form_type[name]" required="required" class="form-control form-control is-invalid" />
            <div class="invalid-feedback">
                <ul class="list-unstyled mb-0">
                    <li>Please enter something.</li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <label class="form-control-label required" for="app_bundle_customer_form_type_address">Address</label>
            <input type="text" id="app_bundle_customer_form_type_address" name="app_bundle_customer_form_type[address]" required="required" class="form-control" />
        </div>
        <div class="form-group">
            <label class="form-control-label required" for="app_bundle_customer_form_type_birthdate">Birthdate</label>
            <input type="text" id="app_bundle_customer_form_type_birthdate" name="app_bundle_customer_form_type[birthdate]" required="required" class="js_datepicker form-control" />
        </div>
        <div class="form-group">
            <label class="form-control-label required" for="app_bundle_customer_form_type_age">Age</label>
            <input type="number" id="app_bundle_customer_form_type_age" name="app_bundle_customer_form_type[age]" required="required" pattern=".{2,}" class="form-control form-control is-invalid" />
            <div class="invalid-feedback">
                <ul class="list-unstyled mb-0">
                    <li>Please enter something.</li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <label class="form-control-label required" for="app_bundle_customer_form_type_isActive">Is active</label>
            <select id="app_bundle_customer_form_type_isActive" name="app_bundle_customer_form_type[isActive]" required="required" class="form-control">
                <option value="" selected="selected">Select the status</option>
                <option value="1">Yes</option>
                <option value="0">No</option>
            </select>
        </div>
        <input type="hidden" id="app_bundle_customer_form_type__token" name="app_bundle_customer_form_type[_token]" value="gb985ZjtF6swI8ZL9clgJV2e8o1RCIp35VSwjMeqQHU" />
    </div>
    <button class="btn btn-primary" role="button" formnovalidate>Save</button>

</form>
```

**Comment by xabbuh** [comment]
Is this the same as #24801 which was fixed in #24802?

**Comment by nullstrike** [comment]
I don't think it's the same since the issue you're referencing the is-invalid class contains a style while in this case there's no styling applied to the is-invalid class.

I double check it by inspecting the input field to look for the class then it is not there.

**Comment by nullstrike** [comment]
I updated the main thread together with the html generated by the form builder

**Comment by xabbuh** [comment]
But there the issue actually is that the `is-invalid` class is not added which was fixed in #24802, right?

**Comment by zorn-v** [comment]
No. First there was class rename (is-invalid to has-error), and now using pseudo classes at all.
https://getbootstrap.com/docs/4.0/migration/#forms
Need to check now, but on alpha.6 it not worked coz css class rename.

**Comment by nullstrike** [comment]
My apologies for the late response, I've actually upgrade my symfony to 3.4-BETA3 and it still not working, just a plain text validation error message.

**Comment by zorn-v** [comment]
I mean need check with latest bootstrap4-beta.2 as they changed css classes few times

**Comment by ostrolucky** [comment]
My fix was tested on beta 2

**Comment by nullstrike** [comment]
It wasn't fix on beta 3

**Comment by ostrolucky** [comment]
- bootstrap 4 beta 3 does not exist
- html output you gave us does not contain validation error message, so it's not the same one that is on screenshot

**Comment by nullstrike** [comment]
I wasn't referring to bootstrap but on symfony beta 3.
I've updated the main thread with the validation error message

**Comment by xabbuh** [comment]
Can you please update the generated HTML as well?

**Comment by ostrolucky** [comment]
You need to try it on Bootstrap 4 beta 2, not alpha.

**Comment by nullstrike** [comment]
@xabbuh kindly look at the thread above, I updated the html together with the validation error message

**Comment by xabbuh** [comment]
I still don't see the "This value should not be blank" message from your screenshot in the generated HTML. It would probably easier if you could create an example project that allows to reproduce your issue.

**Comment by nullstrike** [comment]
The "This value should not be blank" message is missing because I use the translator from the config.yml, I disable the translator in the sample project below

I created the sample project to reproduce the issue it is too big so I use google drive.
[https://drive.google.com/file/d/1490nR1qHEfIFjTawmobX4c0709mrgc9f/view?usp=sharing](url)

**Comment by ostrolucky** [comment]
Issue reproduced, it doesn't work with bootstrap 4 alpha 6, but does work with bootstrap 4 beta 2. Please upgrade.

**Comment by xabbuh** [comment]
closing then, thanks for having a look @ostrolucky
