### ISSUE TITLE
[VarDumper] file and line are not shown when using component standalone

### ISSUE THREAD

**Issue by ivoba** [symfony/symfony#24852]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | *

I noticed that line and file are not shown when using the VarDumper component standalone.
If i see it correct file and line are added in DebugBundle in the DumpDataCollector through a $contextDumper closure.

Wouldnt that fit better into the component so that file and line are shown by default?
Is there anything that makes this complicated?
Or can this be configured when using the component outside of symfony?

When Xdebug is installed the native var_dump also displays file and line.

**Comment by ogizanagi** [comment]
I extracted it in a dedicated context provider in https://github.com/symfony/symfony/pull/23831/files#diff-76f4d58bf230ce14d8106ed778b2c076R25, so if #23831 gets merged you can reuse it easily in your own dumper. But perhaps it could also be an option of existing dumpers.

**Comment by ivoba** [comment]
@ogizanagi that looks awesome.
How could you use it with VarDumper? How should it be invoked?

**Comment by nicolas-grekas** [comment]
Closing as this is the expected behavior of the standalone vardumper, and there is work ongoing to package it in a more friendly way already.

**Comment by ivoba** [comment]
Btw: there is a package that adds the desired functionality for the VarDumper component when used outside of symfony context: https://github.com/morrislaptop/var-dumper-with-context
