### ISSUE TITLE
weak_vendors mode and phars

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#24853]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

When introducing this mode, I overlooked the fact that file paths could look like this:

`phar:///usr/local/bin/phpunit-5/phpunit/Util/Fileloader.php`

In that kind of case, there is not always a way to tell if the deprecation was triggered inside or outside a vendor, so IMO I should add a special case just for phar paths in that method:

https://github.com/symfony/symfony/blob/ba3b17719272e614732a3d1323b556cf32da8dfb/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L64-L86

Not sure how `realpath` behave with such paths, BTW

I wonder how / if I'm going to be able to test that though... any ideas?

**Comment by stof** [comment]
`realpath` will return `false`

I think we should consider that any code being inside a phar is vendor code in this mode. When running a testsuite and having code inside a phar, it is much more likely to be the test runner than the code under test (do you actually build a phar before each test execution, taking into account that this cannot be your executable phar if you are doing unit tests ?)

**Comment by greg0ire** [comment]
@stof I experienced this bug with a phar, but non-vendor code: it was eval'd code produced by `getMockForAbstractClass`, and the class was a non-vendor class.

**Comment by greg0ire** [comment]
A simple fix might be to return `true` if `realpath` returns false then?

**Comment by greg0ire** [comment]
I think I will be able to test this by using `eval`
