### ISSUE TITLE
[HttpKernel] not checking if session is started breaks test

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#24861]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.0-BETA3

This PR (https://github.com/symfony/symfony/pull/24774), specifically, this change (https://github.com/symfony/symfony/pull/24774/files#diff-e8f5b14fbfbbeac60fc9f3abe310c3b0L318) is causing an issue in a functional test.

My test logs a user in, ensures they are logged in, then expires the session via `$client->getCookieJar()->expire('MOCKSESSID')`. I then visit another page and ensure the user is not logged in. It worked as expected without this change but the user is still logged in after this change.

My test env is using `MockFileSessionStorage` and I am using `$client->disableReboot()`.

**Comment by kbond** [comment]
Looks like my issue is actually related to `$client->disableReboot()` - see  https://github.com/symfony/symfony/issues/13450

I was able to solve my issue by adding `$client->getContainer()->get('session')->clear()` right after `$client->getCookieJar()->expire('MOCKSESSID')`

Still was a bit of a BC break for me from BETA2 to BETA3.

**Comment by fabpot** [comment]
There is no BC promise between beta versions.

**Comment by kbond** [comment]
I should have said it was a BC break between 3.3 and 3.4-BETA3. Anyway, guess it is an edge case and I found a solution so I will close.
