### ISSUE TITLE
If you answer server:start with N, it starts anyway.

### ISSUE THREAD

**Issue by SerkanYildiz** [symfony/symfony#24879]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 3.3.10

When you run php bin/console server:start and you don't have installed pcntl, the console asks you
"Do you want to execute server:run immediately? [yN]:". 

If you answer this with 'N' or 'n', it just continues and starts the server. You have to leave it empty to stop the command. 

If it's ok, I am candidate to fix this and make my first PR to Symfony.

**Comment by chalasr** [comment]
👍  the command should use `$io->confirm('...')` instead of `$io->ask('... [yN]')`, PR welcomed.

**Comment by chalasr** [comment]
PR should be submitted against the 3.3 branch.

**Comment by SerkanYildiz** [comment]
Thanks! Indeed I already found it. I just need to change ask to confirm. Will send PR within minutes.
