### ISSUE TITLE
Why does symfony/console depend on symfony/debug? 

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#24873]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

Can't the console and debug components be decoupled for version 4?

**Comment by ro0NL** [comment]
it's coupled here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L128

im not sure how to get around this, i.e. what should happen if `FatalThrowableError` is unavailable.

**Comment by timonf** [comment]
I think it does not make sense to have a dependency on `symfony/debug` for just one exception class. Someone could create a own FatalThrowableError exception for `symfony/console`.

**Comment by Tobion** [comment]
I solved this in #24961
