### ISSUE TITLE
[WebServerBundle] Compile error when stopping the webserver after cache clear

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#24885]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4-BETA

I have been getting this type of error when stopping the webserver with `bin/console webserver:stop`:

```
Compile Error: ContainerXb7rorh::load(): Failed opening required '/.../var/cache/dev/ContainerXb7rorh/getConsole_ErrorListenerService.php' (include_path='.:/usr/sh  
  are/php')
```

It only happens if the cache was cleared/warmed between `webserver:start` and `webserver:stop`.

Maybe related to #23741?

**Comment by chalasr** [comment]
Nice catch, confirmed. 

Full trace:
```
Warning: Uncaught ErrorException: Warning: require(/Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/getSwiftmailer_EmailSender_ListenerService.php): failed to open stream: No such file or directory in /Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/Container.php:116
Stack trace:
#0 /Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/Container.php(116): require()
#1 /Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/getEventDispatcherService.php(157): Container1xet4wP->load('/Users/chalasr/...')
#2 /Users/chalasr/Workspace/tests/traceable-firewall/vendor/symfony/event-dispatcher/EventDispatcher.php(229): Container1xet4wP->{closure}()
#3 /Users/chalasr/Workspace/tests/traceable-firewall/vendor/symfony/event-dispatcher/EventDispatcher.php(61): Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('console.termina...')
#4 /Users/chalasr/Workspace/tests/traceable-firewall/vendor/symfony/eve in /Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/Container.php on line 116
PHP Fatal error:  Container1xet4wP::load(): Failed opening required '/Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/local/php5/lib/php') in /Users/chalasr/Workspace/tests/traceable-firewall/var/cache/dev/Container1xet4wP/Container.php on line 116
```

Note that the webserver is properly stopped.

**Comment by chalasr** [comment]
Not sure we can do anything though.

**Comment by kbond** [comment]
Yeah, the command still works as expected. The exception is from the `server:start` command finishing. There is a slight delay between stopping and seeing that exception which makes sense because it checks for the existence of the pid file every second.

One solution albeit a bit hacky would be to add `exit;` to the end of `ServerStartCommand::execute();` (https://github.com/symfony/symfony/blob/cf4eb4602ace6c32523133b09feab79a53f8fa2d/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php#L153)

**Comment by stof** [comment]
One option could be to remove the EventDispatcher from the Application in ServerStartCommand, so that it does not try to trigger the terminate event when we kill the server.

**Comment by kbond** [comment]
Just tried that adding `$this->getApplication()->setDispatcher(new EventDispatcher());` right above the `try` - this seemed to work.

**Comment by kbond** [comment]
I can open a PR to discuss further.
