### ISSUE TITLE
Csrf with ajax

### ISSUE THREAD

**Issue by nimasdj** [symfony/symfony#24890]
I know here is not the correct place to ask. I apologize. But can someone help for this as I am stuck?
https://stackoverflow.com/questions/47196897/how-to-have-jquery-to-return-csrf/

**Comment by xabbuh** [comment]
You are right about that and I ask you to not mistreat GitHub issues anymore to raise awareness for your StackOverflow question. That's not the reason we have an issue tracker.

**Comment by nimasdj** [comment]
Could you help on SO instead what wrong I did in my code? Much appreciated.
