### ISSUE TITLE
[Serializer] Allow default context for JsonEncoder

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#24898]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.*

Allow to set a default context for `JsonEncoder` like `YamlEncoder` already does
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Encoder/YamlEncoder.php#L31

**Comment by ogizanagi** [comment]
Appart from `json_decode_options`, it seems every other options are already configurable by the mean of the `JsonDecode` and `JsonEncode` constructors.
Perhaps we should add the `$options/$bitmask` argument to the `JsonDecode` class (but only the `JSON_BIGINT_AS_STRING` flag exists for now), but I'm not convinced yet about adding a `$defaultContext` to the `JsonEncoder`.

**Comment by bigfoot90** [comment]
Yes, @ogizanagi your solution works.

Slouldn't then remove `$defaultContext` from `YamlEncoder` to make things more homogeneous then?
