### ISSUE TITLE
[Impersonation] Change user entity via SWITCH_USER event

### ISSUE THREAD

**Issue by cadavre** [symfony/symfony#24905]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | ~3

What do you think about adding possibility to modify user entity obtained from `SwitchUserEvent` and injecting it back into `SwitchUserListener`? In some cases on impersonation we need to modify target user entity before being logged in.

Let me show what would be awesome to achieve in custom listener:
```php
class ImpersonationSubscriber implements EventSubscriberInterface
{

    public static function getSubscribedEvents()
    {
        return [
            SecurityEvents::SWITCH_USER => 'onSwitchUser',
        ];
    }

    public function onSwitchUser(SwitchUserEvent $event)
    {
        $targetUser = $event->getTargetUser();
        $targetUser->setFullname('Impersonated User');
        $event->setTargetUser(targetUser); // this line would do the job
    }
}
```

Right now it is only possible via total override of `security.authentication.switchuser_listener` service, also even because `attemptSwitchUser` is private. :/

**Comment by xabbuh** [comment]
Since #21951 which will be part of Symfony 3.4 you can replace the token inside the event listener. Wouldn't that be enough?

**Comment by cadavre** [comment]
Didn't found mentioned PR. Thank you and yes – it sounds like a reasonable solution.

I guess this issue can be closed then.
