### ISSUE TITLE
HttpKernel Client merge leftovers?

### ISSUE THREAD

**Issue by hilovska** [symfony/symfony#24903]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Client.php
line 104 to 128- I guess this is mistake.

**Comment by SerkanYildiz** [comment]
Hi,
It's not a mistake.
http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc

**Comment by xabbuh** [comment]
I am closing here as this is indeed valid PHP code like @SerkanYildiz said. Anyway, thank you for reporting something you thought was a bug @hilovska.
