### ISSUE TITLE
Syntax error @ Symfony\Component\Config\Definition\NumericNode

### ISSUE THREAD

**Issue by PascalEberhardProgramming** [symfony/symfony#24917]
File: https://github.com/symfony/config/blob/master/Definition/NumericNode.php
Line: 26
Content: " public function __construct(?string $name, NodeInterface $parent = null, $min = null, $max = null)"

Error: Isn't the "?" a syntax bug?

**Comment by xabbuh** [comment]
You are looking at the code for Symfony 4 which will require PHP 7.1 where this is valid PHP (see http://php.net/manual/de/migration71.new-features.php). So I am going to close here as there is nothing wrong.
