### ISSUE TITLE
 Failed opening required vendor/autoload.php

### ISSUE THREAD

**Issue by hazasaad** [symfony/symfony#24918]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | x.y.z

 Warning: Unsupported declare 'strict_types' in /home/hol/public_html/app.php on line 12  Warning: require(/home/hol/public_html/../vendor/autoload.php): failed to open stream: No such file or directory in /home/hol/public_html/app.php on line 21  Fatal error: require(): Failed opening required '/home/hol/public_html/../vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/hol/public_html/app.php on line 21

**Comment by xabbuh** [comment]
Can you explain why you think that this should be caused by Symfony?

**Comment by hazasaad** [comment]
nope..i have error and i dont know to resolve

**Comment by iltar** [comment]
This seems like a basic php error, not something wrong with Symfony. You can try one of the support channels: https://symfony.com/support
