### ISSUE TITLE
Symfony 3 Form ChoiceType: Group checkboxes for bootstrap

### ISSUE THREAD

**Issue by antondachauer** [symfony/symfony#24925]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x/4

Is it possible to group checkboxes from a ChoiceType form field into groups? Please take a look to this post on stackoverflow: https://stackoverflow.com/questions/47226548/symfony-3-form-choicetype-group-checkboxes-for-bootstrap

That would be a great feature for large forms...

**Comment by xabbuh** [comment]
see #19514
