### ISSUE TITLE
Issue with form field returning a single value when expanded is set to off in twig

### ISSUE THREAD

**Issue by dimkasta** [symfony/symfony#24938]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

I  am creating a search page, and want to show a collection of options from the db as checkboxes. 
I have  used a formbuilder without an entity, and tried adding the field as a ChoiceType and EntityType, with multiple and expanded set to true.

```php
$classifiedConditionOptions = $entityManager->getRepository("AppBundle:Classified\ClassifiedCondition")->findAll(["name" => "ASC"]);
```

```php
->add('condition', EntityType::class, array(
                'class' => "AppBundle\Entity\Classified\ClassifiedCondition",
                'choices' => $classifiedConditionOptions,
                'choice_label' => function ($option, $key, $index) {
                    return $option->getName();
                },
                'required' => false,
                'multiple' => true,
                'expanded' => true,
            ))
```
```twig
{{ form_widget(search.classifiedType, {"expanded": false, "attr": {"class": "checkbox-wide"}}) }}
```

The problem is when I try to manipulate the expanded option from twig, to render it as a multiselect in one place, and as checkboxes in another.

The problem is that switching expanded to false from twig, removes the [] from the field's name, making pass a single option instead of an array.
I tried the reverse, but when I set expanded to true on twig, the field dissapears.

I am trying a workaround to use two fields with different renderings

Any suggestions?
thanks

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we do not use GitHub for support issues. Please use one of the [support channels] (https://www.symfony.com/support) for that. Thank you for understanding.

**Comment by dimkasta** [comment]
Thanks for your time, but this really sounds like a bug. 
The field changes to a non-array one (name without [] ) when expanded is switched to false from twig, even though the control remains a multiple select. 
And the field disappears when expanded is switched to true.

**Comment by xabbuh** [comment]
Well, changing the `expanded` option inside the template is a bad idea and IMO nothing that we can (or should) support. You may want to look into form themes if you need to modify how a form type is rendered instead.
