### ISSUE TITLE
logout automaticly in application web

### ISSUE THREAD

**Issue by med004** [symfony/symfony#24944]
Hello,
I have this error with logged .. I use fosuserBundle 
I add in this link 2 images form errors : 

https://imgur.com/a/b4EEA

**Comment by javiereguiluz** [comment]
@med004 in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, it's better to use any of the support alternatives shown in http://symfony.com/support In fact, you already asked this question in the Symfony Slack support channel, so it's better to continue this discussion there. Thanks!
