### ISSUE TITLE
How to update after "php bin/console security:check"

### ISSUE THREAD

**Issue by passboltUser** [symfony/symfony#24964]
You write on how to check for security updates: https://symfony.com/doc/current/security/security_checker.html and it works, in Akeneo it shows me one vulnerability. But how to update? I tried `../composer.phar update` and `../composer.phar update symfony/symfony` but unfortunately the vulnerability is still shown. (https://github.com/akeneo/pim-community-dev/issues/7146)

**Comment by xabbuh** [comment]
I am sorry, but we do not use GitHub for support. If you need help with Composer, I suggest to ask on StackOverflow or to got to one of our [support channels](https://www.symfony.com/support). Thus I am going to close here. Thank you for understanding.

**Comment by passboltUser** [comment]
I just went to your linked site, but in my Firefox I get: 
```
www.symfony.com uses an invalid security certificate. The certificate is only valid for the following names: symfony.com, api.symfony.com Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
It works if I remove the www.

**Comment by xabbuh** [comment]
Thanks for the hint, I have updated my comment accordingly.
