### ISSUE TITLE
Runtime error on fresh install with symfony 3.3.12 

### ISSUE THREAD

**Issue by EnzoDarling** [symfony/symfony#24968]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.12

Hi everyone

Today trying to setup my symfony enviroment i come up with this error after trying a fresh install based on symfony official installer:

`[RuntimeException]                                                           
  The selected version (3.3.12) cannot be installed because it does not exist  
  .                                                                            
  Execute the following command to install the latest stable Symfony release:  
  /usr/local/bin/symfony new blog`

**Comment by javiereguiluz** [comment]
@EnzoDarling thanks for reporting this issue. We're trying to fix it in the Symfony Installer repository. See https://github.com/symfony/symfony-installer/issues/298
