### ISSUE TITLE
Calling `exists` on a symlink to a directory that does not exist returns `false`

### ISSUE THREAD

**Issue by danemacmillan** [symfony/symfony#24984]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.2

Calling `exists` on a symlink to a directory that does not exist returns `false`. This is the default behaviour for PHP's `file_exists` function, which this wraps. 

It would be nice to be able to provide a single array of paths to `exists` and have them all treated similarly, instead of requiring additional logic to determine that a given path is a dangling symlink. Given that the `remove` method includes special handling for removing symlinks, I think the `exists` method should provide similar functionality for detecting them, as the two go hand-in-hand on so many operations like the following.

```
if ($Filesystem->exists($workingEnvironmentPath)) {
    $Filesystem->remove($workingEnvironmentPath);
}
```

In that basic condition, dangling symlinks will remain where they are, instead of being removed, as they do not exist according to the `exists` method.

**Comment by nicolas-grekas** [comment]
That's a feature request, isn't it?

**Comment by Simperfit** [comment]
Yes it is.

**Comment by sroze** [comment]
@danemacmillan could you detail exactly what would be the behaviour you'd expect?

**Comment by stof** [comment]
Changing the behavior of `exists` would be a BC break. And having `exists` return true for dangling symlinks might be unexpected too: exists tells you true, but opening the file then breaks.

Btw, I don't think `remove` has special handling for them. It has special handling for symlinks (dangling or no) so that removing them removes only the symlink (instead of also removing the target, which will happen if you use PHP's `rmdir` on a directory symlink)

**Comment by danemacmillan** [comment]
> Btw, I don't think remove has special handling for [dangling symlinks].

It doesn't. I didn't write that it has special handling for dangling symlinks, either--just symlinks in general: "Given that the `remove` method includes special handling for removing symlinks, I think the `exists` method should provide similar functionality for detecting them [...]."

> Changing the behavior of `exists` would be a BC break. And having `exists` return true for dangling symlinks might be unexpected too: exists tells you true, but opening the file then breaks.

This is the inverse of the problem I wrote about, which is no stronger of a reason. In my example, `exists` tell me false, so any secondary action then breaks. It's a problem no matter what side the coin lands on, so to speak. Ultimately, then, the discussion is more about what makes more sense, or is more meaningful.

We have the BC issue, which is a practical reason that recommends doing nothing. Nothing is easy to do. Nevertheless, there's a valid argument for reviewing the underlying logic of `exists`, which I personally think has implemented logic for the wrong side of the coin. If we can cast aside the argument that something should continue to remain as it is simply because it has always been, we will be able to discuss this properly. Making this request, then, here's my thinking.

My reason for `exists` to also implement logic that accounts for symlinks:

- Consistency: `remove` implements logic that accounts for symlinks. If we don't want `exists` to account for symlinks, then neither should `remove`. I don't want `remove` to stop its special handling of symlinks, though, because it makes sense. If we all agree that makes sense, then for consistency's sake, `exists` should also have special handling of symlinks. The two methods go hand-in-hand on so many operations when dealing with a filesystem. Currently, checking for the existence of a path that is a symlink will return inconsistent results. If the actual path the symlink references exists, `exists` will return true; if the actual path the symlink references does not exist, `exists` will return false. The symlink exists in both examples, though, so where do we draw the line? Why would we allow `remove` to handle symlinks, but we draw the line at `exists`?

If we don't want to mistakenly remove the actual path that a symlink references, and instead we simply unlink the symlink, we shouldn't also mistakenly identify a symlink that exists (as non-existent) if its referenced path no longer exists. In the former example, we're granting importance to symlinks, while in the latter, we're denying their very existence.

Think of the symlinks, people. They have a right to exist. No symlinks left behind. 🦅 🇺🇸 

In the end, I think consistency trumps tradition. If this means waiting for a major version update, I think it should be done.

**Comment by ro0NL** [comment]
> Given that the remove method includes special handling for removing symlinks, I think the exists method should provide similar functionality for detecting them

Which it does; just not dangling symlinks. In general i think it's programmer responsibility to detect and/or cleanup here.

> Consistency: remove implements logic that accounts for symlinks. If we don't want exists to account for symlinks, then neither should remove.

Again; `exists` does account for symlinks :)

> The symlink exists in both examples, though, so where do we draw the line? Why would we allow remove to handle symlinks, but we draw the line at exists?

I'd say at dangling symlinks, yes :)

> The Symfony logic makes it pretty clear that it's willing to make an assumption about an author's intent when calling remove, so why not make the same assumption when calling exists?

The focus is too much on `exists > remove`, while not considering other operations (as @stof mentioned). Returning true and blowing up a read-op does not make sense IMHO. While current behavior does.

**Comment by danemacmillan** [comment]
>  In general i think it's programmer responsibility to detect and/or cleanup here.

I agree. This is why I want to be able to get a consistent response from `exists`. I know that `remove` can just be called instead to simplify the code, but I've been writing software too long to drop good defensive habits that make no assumption about the existence of things before attempting to manipulate or access them.

I assure you this doesn't bug me. Saying it does would be tantamount to me recommending you settle down, when I'm confident you're as aloof to this as I am. I would hope, at least. I wouldn't cheapen someone's pragmatic defense by making it personal. Grant me that. I enjoy discussing this. My earlier points stand. I don't expect everyone to agree. The maintainers have tagged this for review, so there's some merit to a discussion, which is nice.

**Comment by ro0NL** [comment]
> What should I do? Be a responsible programmer that detects things, or just run blind and remove things?

Be a responsible programmer. Id say `$fs->exists($file) || is_link($file)`, where is_link now implies a dangling symlink. That's explicit in terms of you expecting a broken state.

I see your point, i just dont think it's worth to change API here. The current behavior IMHO fits the majority of use cases; considering you'd expect a path in valid state after calling exists() (happening today) instead of having to expect dangling symlinks _all the time_ (as a responsible programmer would do).

**Comment by Simperfit** [comment]
To move this forward I think adding the `dangling = false` by default  is a good idea.

WDYT @stof of this ? Do we need to take action  ?
