### ISSUE TITLE
Command Generate Bundle

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/symfony#24985]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Doc?             | yes
| Symfony version  | 3.3.12

```bash
$ ./bin/console generate:bundle
````
![image](https://user-images.githubusercontent.com/1480617/32865133-ecdba05a-cab5-11e7-9e6e-72b23c767445.png)

This error [is well documented in the docs](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_bundle.html#usage).

Is the fail due to permission issues, or is there a way to fix this issue instead of:
- Editing `composer.json` manually everytime
- Running `composer dump-autoload` everytime

If it is possible, I think we should document it?

Let me know if I can help

**Comment by xabbuh** [comment]
This command is not part of the Symfony core but of the SensioGeneratorBundle. Please check [their repository](https://github.com/sensiolabs/SensioGeneratorBundle) and report it there if not already known. Thank you for understanding.
