### ISSUE TITLE
 The debug:autowiring command is confusing 

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#24986]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

That's because of #24562, so this is actually a duplicate.

BUT, we can fix this one now, by not using FQCN ids internally. This has to be done NOW, before the release.
WDYT?

**Comment by Simperfit** [comment]
I agree.

**Comment by nicolas-grekas** [comment]
Anyone willing to do a PR? The list of services that should be fixed is visible when running `debug:autowiring` on the standard edition.

**Comment by Simperfit** [comment]
Yeah ill do it
Le jeu. 16 nov. 2017 à 15:39, Nicolas Grekas <notifications@github.com> a
écrit :

**Comment by weaverryan** [comment]
Ah, I see: there are many services (e.g. `RouterDebugCommand`) that aren't useful for autowiring... but we use the FQCN as the service id internally, so it's reported by the command. +1 for renaming as many of those service id's as possible so that the list of services in the command contains less/no "garbage"

**Comment by ro0NL** [comment]
What about additionally `debug:autowiring --unused` to cleanup by default for everybody?

**Comment by weaverryan** [comment]
I think the idea here is to simply remove (by renaming the service ids) the core services that really shouldn't be autowireable. I don't think any option is needed, it's really more of a fix (i.e. making `RouterDebugCommand` autowireable is a bug).

**Comment by ro0NL** [comment]
Agree. But we need to be aware of 2 things going on;
- class named services as a naming strategy
- class named services being autowireable

I dont agree going back to plain service ids is always the solution for everyone, even vendors. Personally  for me the naming strategy has more value, taking garbage here for granted. Therefor i think the command eventually needs some filters / other logic or so. For me addding `--interfaces[-only]` would help actually.

Adding `--unused|discover` defeats the command, so ignore that :)

**Comment by nicolas-grekas** [comment]
@ro0NL I agree with you that we need something more explicit on 4.x, this is what #24562 asks for in fact. Here, I made a separate issue to be considered as a bug fix, and the naming convention is a good enough fix for 3.4, which cannot have new features anymore.
