### ISSUE TITLE
[RFC] Rename the legacy profiler.dsn option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24998]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

While upgrading profiler docs to Symfony 4 (https://github.com/symfony/symfony-docs/pull/8685) it was strange to see the `profiler.dsn` config. In the past this made sense because profiler data could be saved in Redis, databases, etc. But now you can only save it in files, so this is not a DSN but a simple directory path.

This is a very unimportant option ... but maybe we can update its name to be more appropriate.

**Comment by ostrolucky** [comment]
That's weird because FileProfilerStorage forces dsn format https://github.com/symfony/symfony/blob/422c4468b2e2367c50bbcf7d1f37a3aa192e0fca/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php#L38

**Comment by javiereguiluz** [comment]
Closing because this proposal didn't gain any traction. Thanks!
