### ISSUE TITLE
StreamedResponse unit tests fail as content gets sent to stdout

### ISSUE THREAD

**Issue by adam-nielsen** [symfony/symfony#25005]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I'm new to Symfony but as far as I can tell I am doing everything correctly.

I am writing a unit test for an API call that uses `StreamedResponse`.  In the `StreamedResponse` callback I am using `echo` to display the content, as [suggested in the docs](https://symfony.com/doc/current/components/http_foundation.html#streaming-response).

However when this API is called in the context of a unit test, the `echo` statement in the `StreamedResponse` callback ends up displaying the data in the PHPUnit output, and the API call thus appears to return an empty response.

It looks like PHP's output buffer is not being captured while the test is running.

The test code looks like this:

    $client = static::createClient();
    $crawler = $client->request('GET', '/example');

This is enough to trigger the bug if that API endpoint responds with a `StreamedResponse`.

Here is some example PHPUnit output, and you can see the file content appears in the `...` progress bar instead of being captured and passed to the code as the response to the API call.

```
$ php vendor/bin/phpunit
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

.FContent goes here...............                                                 17 / 17 (100%)

Time: 1.75 seconds, Memory: 28.00MB

There was 1 failure:

1) Tests\AppBundle\Controller\ExampleControllerTest::testGetExample
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'Content goes here'

/php/tests/AppBundle/Controller/ExampleControllerTest.php:69

FAILURES!
```

**Comment by adam-nielsen** [comment]
Just confirming that it's definitely an output buffering issue, as the following workaround captures the output so the tests can access it:

    // BEGIN 1/2 - Symphony bug workaround - https://github.com/symfony/symfony/issues/25005
    ob_start();
    // END 1/2 - Symphony bug workaround

    $crawler = $client->request('GET', '/example');
    $response = $client->getResponse();
    $getContent = $client->getResponse()->getContent();

    // BEGIN 2/2 - Symphony bug workaround
    $getContent = ob_get_contents();
    ob_end_clean();
    // END 2/2 - Symphony bug workaround

    $this->assertEquals('Content goes here', $getContent);

**Comment by curry684** [comment]
I'm not sure it's a bug, rather a technical limitation based on the concept of how streaming works on one side, and how the crawler works on the other side. Having a streaming response implies there is no single stateless transactional result to be tested to begin with. Your streaming callback could also contain:
```
while(true) {
  echo $i++ . PHP_EOL;
  flush();
  sleep(1);
}
```
Which would be 'valid' but untestable.

I don't think that's *good*, but I also don't see a generic way to get around this.

**Comment by adam-nielsen** [comment]
Would this also explain why I don't seem to get any content in the test code if the API returns a `BinaryFileResponse` as well?

**Comment by adam-nielsen** [comment]
Just to follow up with this, one possible solution appears to be to modify `Client::request()` so that it captures the PHP output buffer, then in the event that a `StreamedResponse` is returned, it converts that into a normal response object.

This is some pseudocode based on how I am doing this now:

    ob_start();
    // Do normal request stuff here
    $r = $client->getResponse();
    if (get_class($r) == 'Symfony\Component\HttpFoundation\StreamedResponse') {
        $r = new \Symfony\Component\HttpFoundation\Response(ob_get_contents(), $r->getStatusCode(), $r->headers->all());
        // Set $r to be the value returned by future getResponse() calls
    }
    ob_end_clean();

This does mean that you'd buffer the whole response object in memory, but for test code with typically small objects, I don't think it would be an issue.

**Comment by nicolas-grekas** [comment]
Closing as everything is well described here, and that's how things work.

**Comment by cbj4074** [comment]
I'm using Laravel, which in turn uses Symfony's `StreamedResponse` class, so while a bit off-topic, I thought I'd explain how this is done in Laravel tests, for anyone who lands here via search:

```php
$response = $this->get(...);
$content = $response->streamedContent();
```

`$content` will contain the downloaded binary file data as a string.

*(maybe this works the same way in native Symfony these days; I haven't looked)*

See also: https://laravel-news.com/testing-streamed-responses-in-laravel

**Comment by mdeboer** [comment]
For the people here using Symfony Framework, the `streamedContent` helper method is not available (and not needed). 

To fix this issue without having to change your tests, simply extend the `Symfony\Component\HttpKernel\EventListener\StreamedResponseListener` class and override the `onKernelResponse` to wrap the `$response->send()` with an output buffer and replace the response with a regular response like so:

```php
public function onKernelResponse(ResponseEvent $event)
{
    if (!$event->isMasterRequest()) {
        return;
    }

    $response = $event->getResponse();

    if (!$response instanceof StreamedResponse) {
    	return;
    }

    // Buffer output
    ob_start();

    // Output response contents
    $response->send();

    // Get and clean output buffer contents
    $contents = ob_get_clean();

    // Return normal response
    $event->setResponse(
        new Response($contents, $response->getStatusCode(), $response->headers->all())
    );
}
```

Next decorate the `streamed_response_listener` service with your service and verify it has been replaced with your service with `bin/console debug:event-dispatcher kernel.response`.

```yaml
App\Event\Subscriber\StreamedResponseSubscriber:
  decorates: 'streamed_response_listener'
  tags:
    - { name: kernel.event_subscriber }
```

Make sure you **only** do this for the **test** environment.

**Comment by MatTheCat** [comment]
@nicolas-grekas it seems weird to me because the HttpKernelBrowser tries to handle this case in [its `filterResponse` method](https://github.com/symfony/http-kernel/blob/13303cfc1a50404868621232055b94dc094945da/HttpKernelBrowser.php#L199-L207) but it does nothing as at this point `StreamedResponse::$streamed` is `true` because of the [StreamedResponseListener](https://github.com/symfony/http-kernel/blob/13303cfc1a50404868621232055b94dc094945da/EventListener/StreamedResponseListener.php).

Even if it is what we want, https://github.com/symfony/symfony/issues/25005#issuecomment-693049282 should be documented somewhere because it truly is unintuitive. Is it really the best way to handle `StreamedResponse`s in tests?

**Comment by nicolas-grekas** [comment]
Sure, PR welcome as always, either as doc or code if you figured out a way to improve things.

**Comment by mdeboer** [comment]
Careful with large responses though (usually why you want to use a streamed response anyway). I haven't looked at the crawler, which maybe be a better point to start looking for a fix. As no matter what kind of response, that should really handle it all.

**Comment by aborza** [comment]
The solution mentioned here works great: 
https://stackoverflow.com/questions/15734677/how-to-retrieve-a-streamed-response-e-g-download-a-file-with-symfony-test-cli
![image](https://github.com/symfony/symfony/assets/8749629/1e29bf03-d2d8-4401-978d-a157907506c3)
