### ISSUE TITLE
Undefined class constant 'PARSE_KEYS_AS_STRINGS'

### ISSUE THREAD

**Issue by pdias** [symfony/symfony#25004]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.12

Hello,

I have this error:

**FatalThrowableError  Undefined class constant 'PARSE_KEYS_AS_STRINGS' in YamlFileLoader.php (line 68)**

```
...
try {
            $parsedConfig = $this->yamlParser->parse(file_get_contents($path), Yaml::PARSE_KEYS_AS_STRINGS);
        } catch (ParseException $e) {
            throw new \InvalidArgumentException(sprintf('The file "%s" does not contain valid YAML.', $path), 0, $e);
        } finally {
            restore_error_handler();
        }
...
```

But it is strange because the constant is defined.

```
namespace Symfony\Component\Yaml;

use Symfony\Component\Yaml\Exception\ParseException;

/**
 * Yaml offers convenience methods to load and dump YAML.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class Yaml
{
    const DUMP_OBJECT = 1;
    const PARSE_EXCEPTION_ON_INVALID_TYPE = 2;
    const PARSE_OBJECT = 4;
    const PARSE_OBJECT_FOR_MAP = 8;
    const DUMP_EXCEPTION_ON_INVALID_TYPE = 16;
    const PARSE_DATETIME = 32;
    const DUMP_OBJECT_AS_MAP = 64;
    const DUMP_MULTI_LINE_LITERAL_BLOCK = 128;
    const PARSE_CONSTANT = 256;
    const PARSE_CUSTOM_TAGS = 512;
    const DUMP_EMPTY_ARRAY_AS_SEQUENCE = 1024;
    const PARSE_KEYS_AS_STRINGS = 2048;

.....
```

I have no idea what it will be about.

Thanks,

Paulo

**Comment by nicolas-grekas** [comment]
Hello, usually the reason is that you're using phpunit, which ships an incompatible (old) version of the Yaml class.
You should use a more recent version of phpunit, or use the phpunit bridge of Symfony, which embeds a solution for this issue. I invite you to check the doc about it.

**Comment by pdias** [comment]
Hello Nicolas,

I'm not making tests in the application, the application is running in dev.

The server where the application runs is a Centos 7, with PHP 7.0.10-2.

I followed your advice and read this documentation:

http://symfony.com/blog/how-to-solve-phpunit-issues-in-symfony-3-2-applications

Following this documentation I run simple-phpunit and phpunit-5.7 was installed on phpunit-bridge.

But I still get the same error...

Now what seems even stranger is that I imported the same Project (the application) to a windows machine with PHP 7.0.24 and it works without errors.

**Comment by xabbuh** [comment]
Maybe you have Opcache enabled and your application uses an older version of the class? Or two applications with different Symfony versions share the same Opcache. Since your project is working on another server I do not think that this an issue with Symfony itself. So I am going to close here. But of course we can reopen if we have new hints that this might be an actual issue.

**Comment by pdias** [comment]
I found the problem and i solved it. 
I'm using SimpleSaml and this it lib is loading phpunit 3.8.

Thanks.
