### ISSUE TITLE
Symfony 4 doctrine:mapping:import missing bundle

### ISSUE THREAD

**Issue by pedroresende** [symfony/symfony#25013]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-beta4

If I ty to run the command

```
php bin/console doctrine:mapping:import
```

I receive the following message 

```
Not enough arguments (missing: "bundle").
```

However in Symfony 4 there is no bundle.

**Comment by javiereguiluz** [comment]
@pedroresende thanks for reporting this error. However, this command belongs to DoctrineBundle, which has its own repository to track issues. That's why I've moved your issue there: https://github.com/doctrine/DoctrineBundle/issues/736

**Comment by pedroresende** [comment]
@javiereguiluz Thanks :)
