### ISSUE TITLE
[HttpKernel] 3.2.14 version number seems to be wrong?

### ISSUE THREAD

**Issue by issei-m** [symfony/symfony#25012]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.2.14

The version number seems not to be bumped from 3.2.13🤔

https://github.com/symfony/symfony/blob/v3.2.14/src/Symfony/Component/HttpKernel/Kernel.php#L61-L65

```php
const VERSION = '3.2.13';
const VERSION_ID = 30213;
const MAJOR_VERSION = 3;
const MINOR_VERSION = 2;
const RELEASE_VERSION = 13;
```

See: https://github.com/symfony/symfony/pull/25001#pullrequestreview-77612351

**Comment by javiereguiluz** [comment]
@issei-m thanks for reporting. You are totally right. Sadly, I don't think there's nothing we can do to fix this issue. If I'm right, we cannot re-release a Symfony version, so this will be fixed in the next version. Thanks!

**Comment by pureugong** [comment]
@javiereguiluz 
It looks like v2.5.11 has same issue.
[[HttpKernel] 2.5.11 version number seems to be wrong](https://github.com/symfony/symfony/issues/25006)

```
    const VERSION = '2.5.10';
    const VERSION_ID = '20510';
    const MAJOR_VERSION = '2';
    const MINOR_VERSION = '5';
    const RELEASE_VERSION = '10';
    const EXTRA_VERSION = '';
```
https://github.com/symfony/symfony/blob/v2.5.11/src/Symfony/Component/HttpKernel/Kernel.php#L61-L65

**Comment by rodrigm** [comment]
Ok, thanks!

This is also resolved: https://github.com/symfony/symfony/pull/25001#pullrequestreview-77612351
