### ISSUE TITLE
[Router] Slow RegEx in AnnotationClassLoader

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#25029]
The RegEx `/^(?:\\\\?[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)+$/` used in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L172 should be very slow for non-matches, because it allows for a ton of backtracking.

A solution would be to disable backtracking:
`/^(?>\\\\?+[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+)++$/`

Idk how much time this saves and ofc this only affects container build time, but it could be a nice DX improvement.

**Comment by nicolas-grekas** [comment]
I never saw this call coming as slow in profiles I did, so we may ignore (or not) this inefficiency  :)

**Comment by backbone87** [comment]
like i said, this should only occur during container (re)compilation or router generation

**Comment by nicolas-grekas** [comment]
I read that part, I was also talking about profiling the compilation step.

**Comment by backbone87** [comment]
no problem, i just noticed the regex while browsing the 4.0 source. feel free to close, if you think it isnt worth the micro optimization

**Comment by nicolas-grekas** [comment]
Closing as there is no bug, nor measured perf issue. This could still be submitted on master if you want @backbone87.
