### ISSUE TITLE
[WebServerBundle] Get address + port in json format after starting server

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#25024]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Since port is dynamic now, getting address + port in json format after starting server would be very useful.

```
php bin/console server:start --format json
```

**Comment by nicolas-grekas** [comment]
just use  `php bin/console server:status --filter port`
