### ISSUE TITLE
ClockMock::microtime(false) return value has a trailing \n character

### ISSUE THREAD

**Issue by arnaud-lb** [symfony/symfony#25050]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x / master

The return value of `ClockMock::microtime(false)` has a trailing \n character. This differs from PHP's microtime behaviour: https://3v4l.org/vVjUl

**Comment by Simperfit** [comment]
The thing is, if we remove the `\n` people might rely on it for whatever reason.

Should we deprecate the behaviour to be removed after or could we remove it already ?

**Comment by arnaud-lb** [comment]
Thanks @nicolas-grekas !
