### ISSUE TITLE
[Form] ContextErrorException in FileType

### ISSUE THREAD

**Issue by chihiro-adachi** [symfony/symfony#25063]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.38, 3.3.13

In symfony 2.7.38 / 3.3.13, the following warning occurred with FileType.

```
ContextErrorException in FileType.php line 43:
Warning: Invalid argument supplied for foreach()
```

It is reproduced with the following code. (I am using Silex)

```
        $builder = $app['form.factory']->createBuilder();
        $builder->add('file', FileType::class, [
            'multiple' => true,
        ]);

        $form->submit([]);
```

`$event->getData()` returns null, so it appears to be warned by foreach ().

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L38

**Comment by Simperfit** [comment]
Hi @chihiro-adachi I think this should be handle whenever getData() is null.

Do you want to provide a PR to fix the behaviour ?

**Comment by chihiro-adachi** [comment]
@Simperfit 
thank you. I'll give it a try.

**Comment by xabbuh** [comment]
see #25102
