### ISSUE TITLE
[DIC] Removal of service definition leaves orphan aliases

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#25060]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | maybe?
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 4.0 (probably also 3.4)

## What happens
I discovered a weird behavior for me in how `ContainerBuilder::removeDefinition()` works. Basically I assumed (wrongly) that removal of definition will also get rid of aliases. Unfortunately it's not the case - removing a definition leaves aliases which crashes `ReplaceAliasByActualDefinitionPass` later on during the compilation process.

## Test script
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

use Symfony\Component\DependencyInjection\Alias;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Definition;

$definition = new Definition(stdClass::class);
$definition->setPublic(true);

$alias = new Alias($definition->getClass(), true);

$container = new ContainerBuilder();
$container->setDefinition($definition->getClass(), $definition);
$container->setAlias('stdSvc', $alias);
$container->removeDefinition($definition->getClass());

$container->compile();
```

Shouldn't the aliases be removed along with the definition?

**Comment by nicolas-grekas** [comment]
IMHO that's expected, as you are responsible for writing technically correct configuration there.
There are so many ways to break it that supporting them would be a nightmare.
Just be careful when writing this...

**Comment by kiler129** [comment]
@nicolas-grekas: For me it's a slightly unexpected behavior and breaks existing code. In 3.3 the container compiled without any problems after services were removed.

I agree the current behavior of exploding during compilation when references are invalid is more correct, however for me it sounds counter-intuitive that removing a service using its id causes container to be left in unknown state.

**Comment by xabbuh** [comment]
I agree with @nicolas-grekas. There could even be valid use cases where you wanted to keep the alias (for example, because the definition is added again later).

**Comment by stof** [comment]
@kiler129 do you assume this will also remove all references to the definition you removed (and how to remove them ? Removing the other definitions using them ?).
There is **nothing** ensuring that the container is in a working state before compilation (you can create references to services that never existed).
And forcing the container to always be in a valid state is totally impossible (as it would require to register services after their dependencies all the time, which is impossible to implement when multiple bundles are providing services)

**Comment by nicolas-grekas** [comment]
Closing as explained.
