### ISSUE TITLE
cache:clear fails after upgrading to symfony 3.4.0-BETA4

### ISSUE THREAD

**Issue by phoenixgao** [symfony/symfony#25066]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-BETA4

I upgraded to symfony 3.4.0-BETA4 by updating composer.json and replacing changes files according to symfony-standard repository.

Everything goes well except the `php bin/console cache:clear --no-warmup` constantly fails with this error:

```
 // Clearing the cache for the dev environment with debug true

In Filesystem.php line 181:

  Failed to remove directory "/path/to/my/project/var/cache/de~/ContainerWocmr4b": Undefined variable: lightTrace.
```

So there is an undefined variable in the debug component.
The actually error is:

```
"Failed to remove directory "/path/to/my/project/var/cache/de~/ContainerWocmr4b": rmdir(/path/to/my/project/var/cache/de~/ContainerWocmr4b): Directory not empty."
```

Even I manually rm all the cache folders on cli and still getting this.

btw I'm using Macos 10.13.1 and vagrant nfs shared folder to ubuntu 16.04.3 vbox. command is ran in vbox. php 7.1.13

**Comment by nicolas-grekas** [comment]
The undefined variable part is now fixed, see #25069.
For the rm that fails, I already see something similar when using vargant+shared folder.
Would you be able to debug that?

**Comment by phoenixgao** [comment]
@nicolas-grekas  Thanks!

I just found similar issues:
https://github.com/symfony/symfony/issues/19851
https://github.com/symfony/symfony/issues/2600

It seems related to the "de~" folder name under var/cache, but before upgrading to 3.4 beta from 3.3.10 this directory was created as "dev" so everything worked fine.

I'll try to debug more on this.

**Comment by phoenixgao** [comment]
@nicolas-grekas 

I pulled https://github.com/symfony/symfony/pull/25069 the undefined error is gone now, but the error message is not showed. I got this:

```
In Filesystem.php line 181:

  Failed to remove directory "/var/www/sites/TNC/kaufmich2/var/cache/de~/Cont
  ainerIiegcfg": .
```

and the rm issue...

I was not able to debug this in symfony ~><~ code too complex for me, so I found it's also related to
https://github.com/hashicorp/vagrant/issues/8788
and
https://github.com/hashicorp/vagrant/issues/8061

As described at the end of this issue, https://github.com/hashicorp/vagrant/issues/8788
I tried to upgrade my macos to 10.13.2 Beta2 and the problem completely gone.

Since it's actually an apple filesystem bug and 10.13.2 will be release soon (hopefully), I think this issue could be closed
Thanks for the help

**Comment by nicolas-grekas** [comment]
OK, thanks for digging
