### ISSUE TITLE
Type error: Argument 2 passed to Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension::dumpData() must be an instance of Symfony\Component\VarDumper\Cloner\Data, array given

### ISSUE THREAD

**Issue by danhanly** [symfony/symfony#25061]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | v4.0.0-BETA4

Whenever I visit the Doctrine panel on the Web Profiler, I get the following error:

```
Type error: Argument 2 passed to Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension::dumpData() must be an instance of Symfony\Component\VarDumper\Cloner\Data, array given
```

This may be specific to my case (I'm hoping not), but regardless, here's the trace:

```
Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Argument 2 passed to Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension::dumpData() must be an instance of Symfony\Component\VarDumper\Cloner\Data, array given

at vendor/symfony/web-profiler-bundle/Twig/WebProfilerExtension.php:72
  at Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension->dumpData(object(Twig_Environment), array())
     (var/cache/dev/twig/c5/c52dd6d881123c07a15bf4b9f0fac2c49fa308aaf52b4025d11965ef9cc643af.php:630)

```

And the highlighted line in the Web Profiler vendor folder:

```
// line 241
echo $this->env->getExtension('Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension')->dumpData($this->env, twig_get_attribute($this->env, $this->getSourceContext(), $context["query"], "params", array()));
```

## Information about setup

This is a simple controller that loads the data via the doctrine repository and passes it to a twig template:

```
$orders = $this->getDoctrine()->getRepository(Order::class)->findAll();
return $this->render('orders/index.twig', ['orders' => $orders]);
```

Code runs and displays perfectly, the only error in when viewing the Doctrine panel of the web profiler. The Order entity has a relationship with the Address entity on both the shipping_address field and the billing_address field. Not sure if that is helpful information, but could explain any issues that may or may not be specific to my case.

**Comment by Simperfit** [comment]
Could you do the following, so we could get a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by ogizanagi** [comment]
Thanks for the report. Actually this issue was already reported on the DoctrineBundle repository: https://github.com/doctrine/DoctrineBundle/issues/730 and previously in https://github.com/symfony/symfony/issues/24804.

**Comment by Simperfit** [comment]
@nicolas-grekas @ogizanagi I think we should add a conflict in the web-profiler-bundle because it does not work when using web-profiler-bundle v4 with doctrine < 1.10.0

**Comment by stof** [comment]
We cannot add conflicts in existing releases anyway.
