### ISSUE TITLE
Server:run  -  [UnexpectedValueException]

### ISSUE THREAD

**Issue by Xenofexs** [symfony/symfony#25075]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3 I think. See below
| PhP version  | 5.6.19
I don't know why but I can't use server:run. I've try to add this bundle : https://github.com/webburza/sylius-article-bundle

> PS C:\myProject> php bin/console server:run -vvv
> 
> 
>   [UnexpectedValueException]
> 
> 
> Exception trace:
>  () at C:\myProject\vendor\symfony\symfony\src\Symfony\Component\Config\ResourceCheckerConfigCache.php:83
>  Symfony\Component\Config\ResourceCheckerConfigCache->isFresh() at C:\myProject\vendor\symfony\symfony\src\Symfony\Component\Config\ConfigCache.php:60
>  Symfony\Component\Config\ConfigCache->isFresh() at C:\myProject\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:485
>  Symfony\Component\HttpKernel\Kernel->initializeContainer() at C:\myProject\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:116
>  Symfony\Component\HttpKernel\Kernel->boot() at C:\myProject\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:68
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\myProject\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:121
>  Symfony\Component\Console\Application->run() at C:\myProject\bin\console:28
> 
> PS C:\MyProject> php bin/console --version
> 
> 
>   [UnexpectedValueException]
>

**Comment by derrabus** [comment]
Can you provide a small git project to reproduce the issue?

**Comment by Simperfit** [comment]
Could you please provide more information ? 

- PHP version
- Symfony version
- are they other bundle installed ?

If you could do like @derrabus said we could be able to fix the bug faster if there is one ;).

**Comment by Xenofexs** [comment]
Thank. I'm not sure how create new git with all the code. I've zip the code and use we transfert. This is the link : https://wetransfer.com/downloads/31efb955cec369d142548b53b5d50de520171128083142/8958fb408c84252db331045aa462ab4720171128083142/821976

I'm using Sylius bundle and custom bundle. But it's only bug after install this bundle : https://github.com/webburza/sylius-article-bundle 

How proprely disable this bundle ?

**Comment by nicolas-grekas** [comment]
@Xenofexs I'm sorry your file on wetransfer expired, I cannot download it. You can upload files as attachments to github comments I think instead.

**Comment by javiereguiluz** [comment]
Closing because of the lack of feedback. Hopefully this was fixed because we haven't receive similar bug reports from the community. Thanks.
