### ISSUE TITLE
Finder should optionally check other time types

### ISSUE THREAD

**Issue by simonhayre** [symfony/symfony#25076]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x

## Issue
When using finder component, the DateComparator only allows for a user to compare MTime. 
My system requires the use of CTime which is the Change Time of a file (moved, renamed, permissions changed). The MTime only changes when the file contents has been changed.
### finder/Iterator/DateRangeFilterIterator.php:50
`$filedate = $fileinfo->getMTime();
`
## Proposed solution
I propose that we allow a user to define which Time type a user wishes to filter on.
### finder/Finder.php:431
```
    public function date($date, $type = 'm')
    {
        $this->dates[] = new Comparator\DateComparator($date, $type);
```

### finder/Comparator/DateComparator.php:20
```
    {
        private $timeType;

        /**
         * @param string $test A comparison string
         * @param string $type The time type to compare
         *
         * @throws \InvalidArgumentException If the test is not understood
         */
        public function __construct($test, $timeType)
        {
            $this->timeType = $timeType;
        //....

       public function getTimeType()
       {
        return $this->timeType;
       }
```
### finder/Iterator/DateRangeFilterIterator.php:41

```
    public function accept()
    {
        /** @var \SplFileInfo $fileinfo */
        $fileinfo = $this->current();

        if (!file_exists($fileinfo->getPathname())) {
            return false;
        }

        foreach ($this->comparators as $compare) {
            if ($compare->getTimeType() === 'c') {
                $filedate = $fileinfo->getCTime();
            } elseif ($compare->getTimeType() === 'a') {
                $filedate = $fileinfo->getATime();
            } else {
                $filedate = $fileinfo->getMTime();
            }

            if (!$compare->test($filedate)) {
                return false;
            }
        }

        return true;
    }
```
## Notes

- This could also be achieved using the regular expression, rather than passing another parameter?
- Should there be a constant for the Time Types?
- Time times are defined as 
    -- M : modified
    -- C : Changed
    -- A : Accessed

**Comment by fabpot** [comment]
Closing as the related PR was closed a while ago.
