### ISSUE TITLE
Temporary Kernel is buggy

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#25074]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

Latest symfony generates a `App\Kerne_` class into `/var/cache/de_/kernel.tmp`. This is causing some issues.

Firstly my Kernel class was final causing this error:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]                        
  Compile Error: Class App\Kerne_ may not inherit from final class (App\Kernel)  
```

It should probably cause a proper exception when the class is generated instead.

Secondly my Kernel has return types which causes this error:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                            
  Compile Error: Declaration of App\Kerne_::getCacheDir() must be compatible with App\Kernel::getCacheDir(): string
```

Symfony should respect that when generating the code and add the return types too.

**Comment by nicolas-grekas** [comment]
This may have worked early 3.3, but this never worked before, and has been reverted again, when warmup has been undeprecated from cache:clear.
This should be supported starting with 3.4/4.0, which doesn't need a temporary kernel anymore thanks to RebootableInterface.

**Comment by enumag** [comment]
Are you sure? Early 3.3 didn't throw this error, it only started very recently. And the latest stable does cause the error. It's not too important, I have removed the type hints until 3.4 is up, just to let you know the current state.
