### ISSUE TITLE
[Twig Bridge] Getting flashes should start the session

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#25073]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

In 5a56b23 you can see `app.flashes` [returns an empty array if the session hasn't started](https://github.com/symfony/symfony/commit/5a56b23327eb660620638ba16b143a57723b87c9#diff-4a6980ec2d62f77827809c4fcc980d29R162). Reading http://symfony.com/doc/current/session/avoid_session_start.html this seems really weird to me; this means I have to add `app.session.start()` after checking for`app.request.hasPreviousSession` if I want to make sure any flash is displayed.

Is this really wanted? If we must check for `app.request.hasPreviousSession` then reading flashes could start the session.

**Comment by nicolas-grekas** [comment]
I agree, this was a workaround that prevented starting the session when "just" checking for flashed, but now that the session is more lazy (since #24523), we could be more "correct" here.
PR welcomed.

**Comment by sroze** [comment]
You can definitely PR a removal of the `isStarted()` method call 👍

**Comment by MatTheCat** [comment]
Hmm should I base it on master?

**Comment by sroze** [comment]
I'd go from 3.4, as sessions have been improved massively from this version.

**Comment by MatTheCat** [comment]
Okay, any idea how to update `testGetFlashesWithNoSessionStarted`?
