### ISSUE TITLE
Single letter console namespace doesn't work on Windows

### ISSUE THREAD

**Issue by lancepioch** [symfony/symfony#25095]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6
| Laravel Version | 5.4.27
| PHP Version | 7.0

### Description:
Having only a single letter before the first colon will prevent the command from being run on Windows. It tries to capitalize the letter, then find the namespace of that capitalized letter and fails. Having 2 or more lets the command be recognized fine.

`php artisan p:user` returns an error
`php artisan pt:user` works fine

Error in console:
```
develop.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: There are no commands defined in the "P" namespace. in C:\wamp\www\panel\vendor\symfony\console\Application.php:538
Stack trace:
#0 C:\wamp\www\panel\vendor\symfony\console\Application.php(570): Symfony\Component\Console\Application->findNamespace('P')
#1 C:\wamp\www\panel\vendor\symfony\console\Application.php(209): Symfony\Component\Console\Application->find('P:user')
#2 C:\wamp\www\panel\vendor\symfony\console\Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\wamp\www\panel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\wamp\www\panel\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main} 
```

### Steps To Reproduce:

Create command with single letter before colon:
`protected $signature = 'p:test';`

If you add another letter before the colon, it works just fine.

**Comment by xabbuh** [comment]
Are you sure that you are trying to call the command with a lowercased `p`? The stack trace contains `P`.

**Comment by nicolas-grekas** [comment]
Could it be the windows shell trying to turn `x:` into an `X:` drive letter?
If that's the case, we cannot do anything...

**Comment by nicolas-grekas** [comment]
BUT, if I remember correctly, we made this case insensitive now, when there is no ambiguity. Could mean that the DX could be already fixed in more recent versions.

**Comment by lancepioch** [comment]
> Are you sure that you are trying to call the command with a lowercased p? The stack trace contains P.

Yes, that's why I mentioned it "tries to" (actually it does) capitalize the letter. I happened to be using (any version of) Laravel. This might actually be Laravel capitalizing it in hindsight...

**Comment by lancepioch** [comment]
After some more checking, this is able to reproduce the capitalization:

    $input = new Symfony\Component\Console\Input\ArgvInput; // first letter will be capitalized

**Comment by nicolas-grekas** [comment]
@lancepioch would you be able to look for the reason and submit a fix? Anyone else otherwise?

**Comment by Simperfit** [comment]
I'm looking at it ;).

**Comment by fabpot** [comment]
@Simperfit Have you made any progress? Are we sure this is a Symfony issue?

**Comment by Simperfit** [comment]
@fabpot I'm working on a fix, but it's not ready yet, i'm going to push it at the end of the week I think.

**Comment by lancepioch** [comment]
This is no longer an issue with the latest versions of symfony, thank you!
