### ISSUE TITLE
[DI] Infinite loop in PhpDumper::analyzeCircularReferences()

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#25101]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-RC1

Trying to upgrade to the 3.4.0-RC1 version on an app, I'm getting a:

> Allowed memory size of [...] in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 369

The issue is an infinite loop in `PhpDumper::analyzeCircularReferences()`, introduced in https://github.com/symfony/symfony/pull/25055.

See https://github.com/ogizanagi/symfony-standard/commit/13ec4374701b3cb880fdf836293e182be7182a2a for a reproducer, which worked fine with 3.4.0-BETA4, or if there is only one `nelmio_alice.faker.provider` tagged service.

By dumping the `$currentPath` var, I infinitely get:

```php
array:7 [
  "nelmio_alice.generator.caller" => "nelmio_alice.generator.caller"
  "nelmio_alice.generator.caller.simple" => "nelmio_alice.generator.caller.simple"
  "nelmio_alice.generator.resolver.value.registry" => "nelmio_alice.generator.resolver.value.registry"
  "nelmio_alice.generator.resolver.value.chainable.function_argument_resolver" => "nelmio_alice.generator.resolver.value.chainable.function_argument_resolver"
  "nelmio_alice.generator.resolver.value.chainable.php_value_resolver" => "nelmio_alice.generator.resolver.value.chainable.php_value_resolver"
  "nelmio_alice.generator.resolver.value.chainable.faker_value_resolver" => "nelmio_alice.generator.resolver.value.chainable.faker_value_resolver"
  "nelmio_alice.faker.generator" => "nelmio_alice.faker.generator"
]
array:6 [
  "nelmio_alice.generator.caller" => "nelmio_alice.generator.caller"
  "nelmio_alice.generator.caller.simple" => "nelmio_alice.generator.caller.simple"
  "nelmio_alice.generator.resolver.value.registry" => "nelmio_alice.generator.resolver.value.registry"
  "nelmio_alice.generator.resolver.value.chainable.function_argument_resolver" => "nelmio_alice.generator.resolver.value.chainable.function_argument_resolver"
  "nelmio_alice.generator.resolver.value.chainable.php_value_resolver" => "nelmio_alice.generator.resolver.value.chainable.php_value_resolver"
  "nelmio_alice.generator.resolver.value.chainable.faker_value_resolver" => "nelmio_alice.generator.resolver.value.chainable.faker_value_resolver"
]
```

**Comment by nicolas-grekas** [comment]
Cool, one less bug very soon :)
Can you work on a fix, or do you need help?

**Comment by ogizanagi** [comment]
I cannot work on a fix for now, that's why I opened the issue 😄

**Comment by Simperfit** [comment]
I can work on a fix tomorrow morning if it's ok for you ;) @nicolas-grekas
