### ISSUE TITLE
[Form] Allow filtering TimezoneType by country

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#25105]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

The second argument of `\DateTimeZone::listIdentifiers` cannot be set which prevent to use `\DateTimeZone::PER_COUNTRY`.

**Comment by Simperfit** [comment]
I'm doing it.

**Comment by xabbuh** [comment]
This was (still is) possible using the `regions` option, but will be deprecated in 4.2 in favour of the use of custom choice loaders.
