### ISSUE TITLE
Form flows over session like CraueFormBundle

### ISSUE THREAD

**Issue by placid2000** [symfony/symfony#25114]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.x.x

Hi,

It would particularly appreciate to have Symfony coming with a new component like CraueFormBundle but managed by Symfony Core developers to have something consistent.

Since we often have multisteps forms, we would appreciate to persist completed data only to the DB at the very end of the form flow to keep a dry database.

Is just a thing imaginable as an alternative to CraueFormBundle?

**Comment by iltar** [comment]
You could easily do this by binding data transfer objects to your form, rather than entities.

**Comment by vudaltsov** [comment]
I have a draft of my own implementation of form flows. [ruvents/form-wizard-bundle](https://packagist.org/packages/ruvents/form-wizard-bundle).

Here are the main differences from the `CraueFormBundle`:
1. more Symfony Forms-like approach (Type -> Builder -> Wizard approach)
2. gives you full control of what to keep in session and how to denormalize it back with `WizardTypeInterface::normalize()` and `WizardTypeInterface::denormalize()`. Besides in my bundle you are serializing the data object, not the request form data as in `CraueFormBundle`
3. easier dynamic forms thanx to `StepTypeInterface::canSkip()`

[Example code](https://github.com/ruvents/form-wizard-bundle)

If someone gets interested I would be happy to receive PRs and feedback.

**Comment by placid2000** [comment]
Thank you @vudaltsov I'll give it a try.

**Comment by xabbuh** [comment]
I don't think this is happening in Symfony core and having it in a third-party bundle is totally fine. So I am going to close here.
