### ISSUE TITLE
cURL error 35: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature

### ISSUE THREAD

**Issue by lindabouzid** [symfony/symfony#25111]
Hi,

I am trying to install symfony by following the steps on the official website, after installing the CA as indicated on the website, I had this error : 

[GuzzleHttp\Exception\ConnectException]
  cURL error 35: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature

Could anyone help me please??

**Comment by greg0ire** [comment]
Something I forgot to mention: can you try running your command like this : `symfony -vvv new test`? It will give you more indication about the failure (please post it)

**Comment by chalasr** [comment]
We use github issues for bug reports and feature requests only, please give a try to our [support platforms](https://symfony.com/support) instead. Thanks for your understanding.

**Comment by greg0ire** [comment]
@chalasr this is not likely to be a bug in the code, but might be a bug with the infrastructure. Where should that kind of issue be reported?

**Comment by chalasr** [comment]
I think https://github.com/symfony/symfony-installer should be a better place

**Comment by javiereguiluz** [comment]
@lindabouzid we're discontinuing the Symfony Installer in favor of using just regular [Composer](https://getcomposer.org/) commands. So meanwhile you can execute this to install Symfony:

```
composer create-project symfony/framework-standard-edition my-project-name
```

**Comment by lindabouzid** [comment]
@greg0ire  I tried with the -vvv option and it gave me that : 

*   Trying 54.230.79.63...
* TCP_NODELAY set
* Connected to get.symfony.com (54.230.79.63) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\wamp64\bin\php\cacert.pem
  CApath: none
* error:04091068:rsa routines:INT_RSA_VERIFY:bad signature
* stopped the pause stream!
* Closing connection 0



  [GuzzleHttp\Exception\ConnectException]
  cURL error 35: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature



Exception trace:
 () at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:49
 GuzzleHttp\Exception\RequestException::wrapException() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php:103
 GuzzleHttp\RequestFsm->__invoke() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at phar://C:/wamp64/www/symfony.phar/vendor/react/promise/src/FulfilledPromise.php:25
 React\Promise\FulfilledPromise->then() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 GuzzleHttp\Message\FutureResponse::proxy() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php:134
 GuzzleHttp\RequestFsm->__invoke() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Client.php:125
 GuzzleHttp\Client->get() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/DownloadCommand.php:567
 Symfony\Installer\DownloadCommand->getUrlContents() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/DownloadCommand.php:113
 Symfony\Installer\DownloadCommand->initialize() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/NewCommand.php:46
 Symfony\Installer\NewCommand->initialize() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Command/Command.php:238
 Symfony\Component\Console\Command\Command->run() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/Application.php:32
 Symfony\Installer\Application->doRun() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://C:/wamp64/www/symfony.phar/symfony:46
 require() at C:\wamp64\www\symfony.phar:10





  [GuzzleHttp\Ring\Exception\ConnectException]
  cURL error 35: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature



Exception trace:
 () at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:126
 GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:91
 GuzzleHttp\Ring\Client\CurlFactory::createResponse() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:96
 GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:68
 GuzzleHttp\Ring\Client\CurlHandler->__invoke() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:54
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:30
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/RequestFsm.php:129
 GuzzleHttp\RequestFsm->__invoke() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at phar://C:/wamp64/www/symfony.phar/vendor/guzzlehttp/guzzle/src/Client.php:125
 GuzzleHttp\Client->get() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/DownloadCommand.php:567
 Symfony\Installer\DownloadCommand->getUrlContents() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/DownloadCommand.php:113
 Symfony\Installer\DownloadCommand->initialize() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/NewCommand.php:46
 Symfony\Installer\NewCommand->initialize() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Command/Command.php:238
 Symfony\Component\Console\Command\Command->run() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/wamp64/www/symfony.phar/src/Symfony/Installer/Application.php:32
 Symfony\Installer\Application->doRun() at phar://C:/wamp64/www/symfony.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://C:/wamp64/www/symfony.phar/symfony:46
 require() at C:\wamp64\www\symfony.phar:10


new <directory> [<version>]

**Comment by lindabouzid** [comment]
@javiereguiluz  the problem is that I can not install the composer, I always have the same error, it is an ssl operation problem

**Comment by xabbuh** [comment]
If you are also  not able to install Composer, this is at least not a problem related to Symfony. I am sorry for you but that's not something we can help with on GitHub. Hopefully, any other Windows user can help you with that on one of the support channels mentioned above.
