### ISSUE TITLE
[Security][Factory] use ArrayNodeDefinition instead of NodeDefinition

### ISSUE THREAD

**Issue by juliendidier** [symfony/symfony#25112]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.1

``NodeDefinition`` does not have ``children`` or ``fixXmlConfig`` methods.
But the ``ArrayNodeDefinition`` have those methods.
This could throw errors with a linter.
Is it normal?

**Comment by xabbuh** [comment]
Can you be a bit more precise what you are referring to?

**Comment by ro0NL** [comment]
I think @juliendidier refers to https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php#L51

But it's interface bound; `SecurityFactoryInterface::addConfiguration(NodeDefinition $builder)` :-)

**Comment by juliendidier** [comment]
Absolutely @ro0NL.
I'm the only one who think this is weird?

**Comment by ro0NL** [comment]
Nope :) https://github.com/symfony/symfony/pull/19960

But im not sure it's really worth the effort (we improve the error only). Also not sure we wanna change the typehint from `NodeDef` to `ArrayNodeDef`, that might be too specific. See also https://github.com/symfony/symfony/pull/19960#discussion_r81571700

**Comment by chalasr** [comment]
I understand the intend but there is nothing to do to me. 
Changing the typehint would be a big BC break and throwing would not fix anything to me: since you are implementing the method, you know which type you have in hands, so you can perform some extra `instanceof` checks if you care (the core doesn't).
I'm for closing as won't fix.

**Comment by chalasr** [comment]
Closing as explained.
