### ISSUE TITLE
[DX][WebProfilerBundle] Add a link to open twig template

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#25118]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

---

![image](https://user-images.githubusercontent.com/408368/33135778-b595bbf6-cfa3-11e7-9bcc-d9f8bef58eef.png)

On this image, I would like to be able to click on the template name to open directly the open in my IDE.

Plus It would be awesome if the (fist?) rendered template could be clickable too from the toolbar (in the bottom of a page). I guess this could be hard, as a this is not necessarily the first template to be rendered: For exemple if one render a template to send it by mail.

WDYT? Is it hard to implement?

**Comment by ogizanagi** [comment]
I think it's already done in https://github.com/symfony/symfony/pull/24236 and available in 3.4 :)

Being able to access the rendered template(s) from the toolbar was also suggested in https://github.com/symfony/symfony/pull/24236#issuecomment-330048491.

**Comment by ro0NL** [comment]
@lyrixx anything to do? :-)

**Comment by lyrixx** [comment]
yes, it would be awesome to be able to open my IDE on the "first" rendered template.

**Comment by lyrixx** [comment]
BTW, thanks for #24236 I missed it.

**Comment by javiereguiluz** [comment]
@lyrixx as you said in the description, getting the right Twig template in every situation can be very difficult (impossible?). Not sure the added complexity is worth it for a feature that will probably not work perfectly right.

**Comment by lyrixx** [comment]
Okay, let's close this issue ;)
