### ISSUE TITLE
[DIC][DX] Detect case mismatch in autowired service names

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#25122]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

Currently when someone misspell service name the message suggesting proper spelling is displayed. However when someone puts a correct service name, but the case doesn't match a generic error message is displayed:

```
Cannot autowire service "AutowiredService": argument "$autowiredParam" of method "__construct()" references class "caseMissmatchService" but no such service exists. It cannot be auto-registered because it is from a different root namespace.
```

PhpStorm (I don't know about other IDEs) doesn't have case inspection enabled by default, so such error is hard to catch just by looking. I agree autocompletion should be used whenever possible, but such errors still happen for peoples using simple editors.

I suggest improving DX of the `AutowirePass` to contain more detailed error message when service name is correct but case doesn't match. Class loader already behaves like that: https://github.com/symfony/symfony/blob/4b9ed9e125fbda52cf18560a645a069f2a4512f6/src/Symfony/Component/Debug/DebugClassLoader.php#L163

What do you think?

**Comment by sroze** [comment]
Proposed #25155 to add such behaviour.
