### ISSUE TITLE
[Process] Process created but doesn't execute command

### ISSUE THREAD

**Issue by fnev-eu** [symfony/symfony#25120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.28, 2.8.31

I am trying to execute a command via a Process. The process is correctly created (I get a Pid), but the command does not run.
I have investigated, made several tests, and I arrive at the following result: when I comment line 290 of the class [Process.php](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Process/Process.php#L290) (`$this->status = self::STATUS_STARTED;`) then the command is executed. If no, nothing happens.

**Comment by Simperfit** [comment]
I'm trying to reproduce this, if I find the bug ill provide the fix orif you want to @fnev-eu feel free to do it ;).

Could you please upgrade to 2.8.31 too ?

**Comment by fnev-eu** [comment]
I have the same issue with version 2.8.31, and comment the same line fix again the problem.

I do not understand the link between the assignment and the execution of another process. :/

**Comment by nicolas-grekas** [comment]
@fnev-eu can you find a version where it worked?

**Comment by fnev-eu** [comment]
@nicolas-grekas I already used this code on Symfony 2.8.11 without problem. I did not try on the intermediate versions.

**Comment by nicolas-grekas** [comment]
Can you try copy/pasting the code from 2.8.11 in your app, does it fix anything?
If yes, can you revert the changes one by one until it breaks again?

**Comment by Simperfit** [comment]
What are you trying to run ?

Because using 2.8.28 with php 5.6 and process containing `ls` is working properly see https://github.com/symfony/symfony-standard/compare/2.8...Simperfit:reproduce-the-process

**Comment by fnev-eu** [comment]
It works perfectly in 2.8.11, without `wait`. But indeed it does not work without `wait()` in this case.

**Comment by nicolas-grekas** [comment]
@fnev-eu I think we need your help to debug this. Can you provide a reproducer?
Or can you debug locally, eg trying to revert the change between now and 2.8.11 one by one the Process class?

**Comment by Simperfit** [comment]
@fnev-eu In order to fix this bug you have to help us on the how-to to reproduce it : 

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this doc entry : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
