### ISSUE TITLE
Sensio CRUD Generator change entity name in spanish and restart Apache server

### ISSUE THREAD

**Issue by beauty24** [symfony/symfony#25124]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.2

I create a entity name like: Venta,Operaciones, Oferta, etc. I generate crud y in the OfertaController.php appear like this.
```
public function newAction(Request $request)
    {
        $ofertum = new Ofertum();
        $form = $this->createForm('PrincipalBundle\Form\OfertaType', $ofertum);
---------
public function newAction(Request $request)
    {
        $operacione = new Operacione();
```
I looked in the vendor folder and it seems that "Inflector Component" is being activated, converting the words of the Spanish language, when it should be an internal component(https://github.com/symfony/inflector) and not modify the names of the entities.

After generating the crud and changing by hand the name of the entity that should be, for example "Offer" the links of the function showAction, or the other functions below it, do not work. When creating other functions within that Controller, it restarts the Apache server and enters a cycle that never ends.

**Comment by javiereguiluz** [comment]
@beauty24 thanks for reporting this issue ... but this should be reported to the repository of the SensioGeneratorBundle. I've moved your issue there. See https://github.com/sensiolabs/SensioGeneratorBundle/issues/582
