### ISSUE TITLE
[DI][Cache] Cache pool factory arguments are replaced by autogenerated cache NS

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#25126]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13, 3.3.0, 4.0.0-RC1

## Intro
I discovered that something changes how my cache pool factory is called effectively destroying arguments passed to the factory and making cache pool factories unusable. This bug reports lack exact details, since I wasn't able to trace the reason for the behavior.

## How to replicate
I used standard Symfony 4 installation (also tested w/3.3.0 & 3.3.13) with following composer packages installed via flex:

```
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/profiler-pack": "^1.0",
        "symfony/twig-bundle": "^4.0@beta",
        "symfony/web-server-bundle": "^4.0@beta",
        "symfony/yaml": "^4.0"
```

Next I created `config/bug.yaml` and imported it from the main `config/services.yaml` to isolate all default autoconfiguration options. The `bug.yaml` file has the following content (which I believe is a core of this bug report):

```yaml
services:
    App\Pool\FooPool:
        factory: 'App\Factory\CachePoolFactory:getPool'
        public: true
        arguments:
            - 'TestString'
        tags:
            - { name: cache.pool }
```

The factory is bare simple:
```php
<?php
namespace App\Factory;

use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;

class CachePoolFactory
{
    public function getPool(string $name): TagAwareAdapterInterface
    {
        die('Param: ' . $name);
    }
}
```

The pool class itself is empty:
```php
<?php
namespace App\Pool;

use Symfony\Component\Cache\Adapter\TagAwareAdapter;

class FooPool extends TagAwareAdapter {}
```

To trigger the bug you also have to call `$this->container->get('App\Pool\FooPool');` e.g. in index action of a controller to run the factory.

#### Result
The results is `Param: R7dy-yHf7x` instead of `Param: TestString`, so definitely factory looses the argument for something "random".

## Where bug lies?
I traced the problem to `\Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\CachePoolPass`, which first generates the string in https://github.com/symfony/symfony/blob/44b2f97dcd2ba10857dd545e424ad4f48c9dbea1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php#L60 and next replaces the arguments to the factory with the generated string in https://github.com/symfony/symfony/blob/44b2f97dcd2ba10857dd545e424ad4f48c9dbea1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php#L84

Any ideas? Am I doing something horribly stupid or wrong that the arguments are replaced?

**Comment by nicolas-grekas** [comment]
Not sure that's a bug: adding the `cache.pool` tag does tell you want that to happen (that's the behavior that the tag asks for).
Can't you just remove the tag?

**Comment by nicolas-grekas** [comment]
BTW, why are you doing that ?
If you need tagged pools, just use a service decorator?

**Comment by kiler129** [comment]
@nicolas-grekas I guess I can, since correct me if I'm wrong the tags are pointless when cache component is used standalone, since no passes are processing the tags?

I don't really get the idea of using tagged pools and service decorator - what do you think should decorate what? Generally I have to fix this anyway, since current way we handle caching is multiple pools defined as services and these pools are autowired to services needing them, but since they're wrapped in `CacheCollectorPass` into `TraceableTagAwareAdapter` our solution collapsed and there's clearly something which we tripped over. Maybe you can suggest a proper way of doing this? At this point I don't see a way to automatically wire different pools to different services.

I'm currently migrating a project which uses some of the Symfony components to use Symfony 4 and I'm finding a lot of such small things which are hards to debug. If the `CachePoolPass` intentionally doesn't support arguments (sorry for my ignorance, since I don't know how exactly this pass works) maybe we should warn about such situation, since it's really confusing - I had a service definition which magically got initialized with "random" string instead of the one which was defined.

**Comment by nicolas-grekas** [comment]
Adding a tag adds behavior, and with this case, it's defining these arguments. Maybe you can just change your factory's signature to match those? See other existing adapters

**Comment by nicolas-grekas** [comment]
BUT!
From your description, I think the goal you're pursuing would lead to a bad practice.
DI configuration has a purpose, and the use case you're describing is exactly it. Creating classes for the sake autowiring is doing things reverse.
Instead, you should define pool, and wire them in Yaml.
Otherwise, you'll end up with hardcoded configuration in your code, which what dependency injection advocates NOT doing.

**Comment by nicolas-grekas** [comment]
I'm closing as explained: that's the expected behavior. I'd be happy to hear your reaction about my previous comment though.

**Comment by kiler129** [comment]
@nicolas-grekas Thank you for an extensive explanation, appreciate. After sleeping with the problem (and spending holidays with it ;)) I think you're right and services itself should expect just an interface for tagged pool and which pool is wired should be wired manually in DI, since as you said I created empty classes just for sake of having something unique to autowire.
