### ISSUE TITLE
MoneyType renders incorrect symbol for currency € when serving pages in ISO-8859-15

### ISSUE THREAD

**Issue by nzurita** [symfony/symfony#25135]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

When serving pages in charset ISO-8859-15 instead of default UTF-8 and rendering a form MoneyType, currency symbol (€ in my case) is shown in wrong codification (see screen captures).

![imagen](https://user-images.githubusercontent.com/921345/33180056-c6fc85e6-d06b-11e7-852f-ea6974e53411.png)
![imagen](https://user-images.githubusercontent.com/921345/33180072-d71ac44c-d06b-11e7-8c47-68e77cb62c64.png)

As additional information, this is my code in `AppKernel.php` regarding charset:

    /**
     * Get the framework charset
     *
     * @return string The charset
     */
    public function getCharset()
    {
      return 'ISO-8859-15';
    }

And a link showing details of ISO-8859-15 charset, which supposedly has an euro (€) symbol. My twig template is also encoded in ISO-8859-15. A possible cause of this problem is that the source code file for money template is encoded in UTF-8, which is of course right.

I know I can override MoneyType template, but a correct solution, I think, is writing the euro symbol as the `&euro;` *html entity*, which is charset independant.

**Comment by ro0NL** [comment]
I think the issue comes from NumberFormatter returning a UTF-8 encoded string. Which is not properly converted to ISO.

See https://3v4l.org/O5sTJ

```php
echo htmlentities(iconv('UTF-8', 'ISO-8859-15', $pattern), \ENT_HTML5, 'ISO-8859-15');
```

should do.

**Comment by nzurita** [comment]
Sorry, I need some context, do you mean I should use this in a template to override default rendering?

**Comment by stof** [comment]
What could be done is accounting for the fact that Intl returns UTF-8 things, and so converting it:

```twig
{{ foo|convert_encoding(_charset, 'UTF-8') }}
```

However, I suggest you to do it in a custom form theme instead of changing the form theme in Symfony. Applying iconv for all people actually using UTF-8 would have overhead (and UTF-8 is the default).

**Comment by ro0NL** [comment]
we could convert on the fly no? if needed. `{%if _charset != 'UTF-8' %} {{ foo|convert_encoding(...) }}{% endif %}`

Did not know about `convert_encoding` :sweat_smile:

**Comment by stof** [comment]
@ro0NL I'm not sure having lots of `if` for the charset in form themes would be a good idea though, even if the condition is simple. Form rendering tends to make lots of calls to Twig.
I think non-UTF-8 charset is not that widespread nowadays.

**Comment by ro0NL** [comment]
we could do it from MoneyType =/

> I think non-UTF-8 charset is not that widespread nowadays.

Tend to agree; but a fix might be nice / solving this issue (should we close?).

**Comment by nzurita** [comment]
> I think non-UTF-8 charset is not that widespread nowadays.

Sure it isn't, in my case, it's a new Symfony module over a legacy app, so we are forced to apply legacy charset

**Comment by nicolas-grekas** [comment]
This looks like a bug to me. I would expect at least `htmlentities($money_pattern, ENT_HTML5, 'UTF-8')` to be called (not sure about `convert_encoding`, because that requires extra knowledge about the charset, which htmlentities doesn't)

**Comment by derrabus** [comment]
> that doesnt help with `€` (euro) char, as it's not part of the charset

Actually, ISO-8859-15 has the Euro symbol as `0xA4`. So a simple charset conversion should be enough.

**Comment by ro0NL** [comment]
@derrabus you're right, however ` ISO-8859-1` hasnt. I believe htmlentities fits all cases.

**Comment by derrabus** [comment]
@ro0NL

> you're right, however `ISO-8859-1` hasnt.

ISO-8859-1 is deprecated and 8859-15 is supposed to replace it. Both charsets are similar enough, so you can read ISO 5559-1 encoded data and treat it as ISO-8859-15. The difference is that eight character codes have been reassigned.

> I believe htmlentities fits all cases.

I agree. If you can switch to HTML entities in a non-breaking way, go for it.
