### ISSUE TITLE
Why are query strings stripped from referer when creating a redirect response after login?

### ISSUE THREAD

**Issue by andrewbrereton** [symfony/symfony#25139]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.3.13

Hi, sorry if this is not the right place. I have a question regarding this commit by @fabpot on 19 July: https://github.com/symfony/symfony/commit/9c7a1406cb81f4d1ccd7e3521347e2d847b7467c#diff-a654f85d03c2e834cb8701bec08e2a4f

Can someone explain why it is a security risk to redirect to the referer with the querystring after successful login?

I have a login form in a modal and if a customer logs in on the search page, they are redirected to the search page but without their search term because this commit strips the querystring.

I can easily work around this in my `onAuthenticationSuccess` but I'm concerned about security implications.

Thanks.

**Comment by jakzal** [comment]
See #23580.

I think it might've been done to compare URLs properly more than actually return the URL with no query string. I might be wrong though.
