### ISSUE TITLE
[HttpFoundation] getPreferredLanguage() failover to better match

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#25143]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

This might not be a bug but a desired behaviour, but just to confirm; if I'm missing a base language in my locales, `getPreferredLanguage()` will return the first entry from param no matter what:

```php
$_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'en_ES'; // can be either en or en_ES
$request = Request::createFromGlobals();

// de
var_dump($request->getPreferredLanguage(['de', 'en_GB', 'en_US', 'it']));
```

As long as the param doesn't contain `en`, it will always return `de` even though a better match is available (say, `en_GB` as the first `en_*` entry?)

**Comment by nicolas-grekas** [comment]
That's how the HTTP spec says this should be handled...

**Comment by nicolas-grekas** [comment]
Closing as explained.

**Comment by dkarlovi** [comment]
Fair, tnx 👍
