### ISSUE TITLE
[DI] Get only public service ids

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#25141]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x

Is there a way I can get only the public service ids?

If I use `$container->getServiceIds()` it brings all the service ids (private and public). If not is this a feature you might be interested?

**Comment by nicolas-grekas** [comment]
Hello,
that's correct in 3.3, but that's been fixed in 4.0.
We cannot fix it before because that would break backward compatibility.

**Comment by stof** [comment]
@nicolas-grekas but we would need to FC layer allowing to opt-in for the new behavior earlier than 4.0 (otherwise, this method is useless, as you cannot know whether the id is usable with `get` and `has` without deprecations)

**Comment by nicolas-grekas** [comment]
@stof it's been always like that, and is fixed by moving to 4.0. I would not consider this as a bug fix, so not applicable to 3.*

**Comment by stof** [comment]
@nicolas-grekas this is a missing place for the FC layer. The only way to stop getting deprecation warnings on a place using `getServiceIds` is often to drop the code, which is not good.

When doing changes like that in the past, we generally added a way to opt-in for the new behavior in the previous version (so that you can make your code ready for dealing only with public services) .

**Comment by nicolas-grekas** [comment]
@gmponos what's your use case? would that help? would it be required for you?

**Comment by gmponos** [comment]
I have this test class

``` php
namespace Tests\SmokeTests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\ContainerInterface;

class ServicesTest extends WebTestCase
{
    /**
     * @var Container|ContainerInterface
     */
    private static $container;

    /**
     * @var array
     */
    private static $ignoreServices = [
        'lexik_jwt_authentication.encoder.lcobucci',
        'monolog.activation_strategy.not_found',
        'monolog.handler.fingers_crossed.error_level_activation_strategy',
    ];

    /**
     * @inheritdoc
     */
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass();
        self::bootKernel();
        self::$container = self::$kernel->getContainer();
    }

    /**
     * Smoke test that checks whether all the services
     * load properly or not
     */
    public function testSmokeTestServiceLoading()
    {
        $serviceIds = self::$container->getServiceIds();
        foreach ($serviceIds as $serviceId) {
            if (in_array($serviceId, self::$ignoreServices, true)) {
                continue;
            }

            $service = self::$container->get($serviceId);
            $this->assertNotNull($service);
        }
    }
}
```

The goal of this Test Class is to detect if in your Yaml if you have declared services in a wrong way. Something like this:

```
services:
    app.myservice:
        class: NotExisting\Namespace
    app.yourservice:
        class: Existing\Namespace
```

`$container->getServiceIds()` brings also the private ones and I get a deprecation warning in my tests.

As I work arround I did this:

```
        $publicServices = function () {
            /** @var Container $container */
            $container = $this;
            return array_unique(array_diff($container->getServiceIds(), array_keys($container->privates)));
        };

        $publicIds = \Closure::bind($publicServices, self::$container, Container::class);
```

As I dig deeper in Container stuff I also saw that you are not able also to check if a service is deprecated or not before fetching it.

**Comment by nicolas-grekas** [comment]
OK: that's the job of a compiler pass (enabled only on the test env I guesss), not something you should to on a compiled container.

**Comment by nicolas-grekas** [comment]
I'm closing as explained, this logic belongs to a compiler pass IMHO.
