### ISSUE TITLE
Multiple entity managers in Symfony 3.3 seams to not work as service arguments

### ISSUE THREAD

**Issue by hardcoremore** [symfony/symfony#25149]
| Q
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

Since Symfony framework does not have official forum and official channel of communication is StackOverflow so I asked a question on StackOverflow here:

https://stackoverflow.com/questions/47441870/multiple-entity-managers-in-symfony-3-3-seams-to-not-work-as-service-arguments

This is my first issue that I have opened on GitHub so please guide me if I did anything wrong :)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by hardcoremore** [comment]
Yes I understand. But I asked here because no one is answering on the StackOverflow. Do you think that this is now a bug? Thanks.
