### ISSUE TITLE
*.Yaml extension

### ISSUE THREAD

**Issue by cordoval** [symfony/symfony#25153]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | x.y.z

I am not sure which version of what is the nature of this. But let me bring this up:

There was a rumour about moving to *.yaml 4 letter extension, i did change my files to it but for mapping on doctrine bundle, the bridge seems to be hardcoded to 'yml' extension only because this is the filedriver yamldriver default. On the registerMappingDrivers method there is some automation done but no case for doing a call to setFileExtension and nowhere on the configuration tree to pass this custom stuff or even hard coded or make the locator find both yaml and yml.

Is this planned for symfony 4? if so, i did not see a PR and we are close to be the end of the month would be great to see this decided. thanks

**Comment by nicolas-grekas** [comment]
It's not a rumor, see https://medium.com/@fabpot/symfony-4-directory-structure-5b84bd1ce65a#7ef7
Symfony starting with 3.3, but continuing with 3.4 now handles the more standard `.yaml` extension.
Of course, just changing your file names without upgrading won't work.
Therefore, I'm now closing this issue, as the report is not describing anything that doesn't work and should be fixed.
If you found something that should be working, but doesn't, please provide accurate description.
Cheers.
