### ISSUE TITLE
Symfony.com navbar issue

### ISSUE THREAD

**Issue by boykodev** [symfony/symfony#25156]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

This isn't a bug report not for Symfony itself, but for the documentation website (symfony.com)
When browsing it from a tablet (iPad 2) and focusing on the main content, there's an annoying bug with the navbar. See the screenshot:
![fullsizeoutput_655](https://user-images.githubusercontent.com/6420099/33231814-33c09322-d204-11e7-9748-6b7cc283a11d.jpeg)

**Comment by javiereguiluz** [comment]
Thanks for reporting ... but symfony.com issues are usually reported in Symfony Docs repository. I moved your issue there: https://github.com/symfony/symfony-docs/issues/8749  Thanks!
