### ISSUE TITLE
[Docs][DX] Cumbersome environment variables for commands

### ISSUE THREAD

**Issue by yannickl88** [symfony/symfony#25157]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 3.3

First of, I am all in favor of environment variables. I think they are a great way to decouple your app from the server it is ran on.

That being said, I'm feeling they are a step backwards in DX compared to the `parameters.yml` files for different environments when having commands that require them. For instance: if I have a command that does anything with the database (i.e., uses doctrine) I will need to export that correct variables to make it work. **This includes the cache warmup** which warms the doctrine proxies. To illustrate this, here is a quick config:

```yaml
parameters:
    database_driver: pdo_mysql
    database_host: %env(DATABASE_HOST)%
    database_port: %env(DATABASE_PORT)%
    database_name: %env(DATABASE_NAME)%
    database_user: %env(DATABASE_USER)%
    database_password: %env(DATABASE_PASSWORD)%
    secret: %env(APP_SECRET)%

framework:
    secret:          "%secret%"
    // [...]

doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        UTF8
// [...]
```
Which seems to me like the intended prefect example. However, this will throw the following error when running any command:
```
$ bin/console
  [Symfony\Component\DependencyInjection\Exception\EnvNotFoundException]
  Environment variable not found: "DATABASE_HOST".
```

Since the environment variables were configured in my Virtual Host settings, they are missing on the command line. So I'm stuck with [creating this *massive* export block](https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables) anytime I want to do something on the command line. Worst of all, this includes any deployment script, which needs to preform a cache warmup.

So what is the point of this issue? 

Well I was wondering if we could document in the Symfony docs a good solution to dealing with environment variables for commands. Especially so I do not have to define them twice (vhost & cli exports). Because as it stand now I feel as if the current docs isn't really showing a proper solution.

**Comment by nicolas-grekas** [comment]
You're correct :)
This has already discussed in #24927 and #25010 so that I'm now closing this issue as duplicate. I invite you to check the discussion there (esp. in #25010.)
The solution in on your side, and specific to Doctrine. Already implemented as a recipe here:
https://github.com/symfony/recipes/pull/258

**Comment by yannickl88** [comment]
Okay, the linked tickets are indeed about the doctrine warmup. But that is only *half* of what I was trying to say with this issue.

What remains is that environment variable are not present for console commands if not exported to the user running the command. Which still requires two places (vhost & cli exports) to define **and manage** them which feels cumbersome. I see a [similar issue at deployer where somebody brought this up too](https://github.com/deployphp/deployer/issues/527#issuecomment-178109608).

**Comment by nicolas-grekas** [comment]
> What remains is that environment variable are not present for console commands if not exported to the user running the command. Which still requires two places (vhost & cli exports) to define

that's correct. That's solved for "dev" thanks to the ".env" file.
then for "prod", you should have deployment scripts that do the job for you...
nothing we can improve here IMHO. What would you propose?

**Comment by yannickl88** [comment]
I know this cannot be solved with code, but it can be clarified in the docs, which is a bit vague at the moment. And I know it isn't Symfony's job to tell me how to organize a webserver, but as I read the docs it doesn't feel like a proper solution now.

**Comment by nicolas-grekas** [comment]
doc PR welcomed then I guess :)

**Comment by yannickl88** [comment]
Well that is why I made this issue, I do not have a good solution (else I made a PR). I was hoping other would have had better ideas.

**Comment by nicolas-grekas** [comment]
You should maybe try on https://github.com/symfony/symfony-docs/?

**Comment by nicolas-grekas** [comment]
FYI, on my deployment env (SensioCloud), I set prod env vars using some tool provided by the hoster, and then they are automatically available to the web and cli env, so that this issue in a non issue on my side.

**Comment by tecnocat** [comment]
Our solution was tricky, we _overwrapped_ the Symfony Environment variables (and DotEnv) component with a custom EnvVarProcessor, all our microservices always have 4 services inside up and running: **PHP-FPM**, **Nginx**, **Consul** and **Memcached**, with this scenario we follow this simply steps:

In **bin/console** we put this line (api is the name of the microservice):

```
$input = new ArgvInput();
$env   = $input->getParameterOption(['--env', '-e'], 'dev', true);

ConsulEnvVarProcessor::loadEnvironmentValues('api', $env); // <--- THIS LINE !!!

$debug = (bool) ($_SERVER['APP_DEBUG'] ?? ('prod' !== $env)) && !$input->hasParameterOption('--no-debug', true);
```

In **bin/phpunit** we put this line:

```
require_once dirname(__DIR__) . '/vendor/autoload.php';

App\EnvVarProcessor\ConsulEnvVarProcessor::loadEnvironmentValues('api', 'test');
```

In **public/index.php** we put this othe line:

```
require __DIR__ . '/../vendor/autoload.php';

ConsulEnvVarProcessor::loadEnvironmentValues('api');
```

In **features/bootstrap/bootstrap.php** we put the same line (Behat):

```
<?php

App\EnvVarProcessor\ConsulEnvVarProcessor::loadEnvironmentValues('api', 'test');
```

And our **ConsulEnvVarProcessor**:

```
class ConsulEnvVarProcessor implements EnvVarProcessorInterface
{
    private static $kv;

    public static function getProvidedTypes()
    {
        return [
            'consul' => 'string',
        ];
    }

    public static function loadEnvironmentValues(string $id, string $appEnv = null): void
    {
        if ('test' === $appEnv)
        {
            VCR::turnOn();
            VCR::insertCassette('VHS');
        }

        self::initEnvironment($id, $appEnv);
        self::preloadEnvironmentValues();
    }

    private static function getConsulKVService(): KVInterface
    {
        return self::$kv = self::$kv ?? (new ServiceFactory())->get(KVInterface::class);
    }

    private static function getConsulKeys(): array
    {
        $id = getenv('MICRO_SERVICE_ID');

        $consulResponse = self::getConsulKVService()->get($id, ['keys' => true]);

        if (Response::HTTP_OK !== $consulResponse->getStatusCode())
        {
            return [];
        }

        return json_decode($consulResponse->getBody());
    }

    private static function getConsulValue(string $name): ?string
    {
        try
        {
            $id = getenv('MICRO_SERVICE_ID');

            $consulResponse = self::getConsulKVService()->get($id . '/' . $name);

            if (Response::HTTP_OK !== $consulResponse->getStatusCode())
            {
                throw new \Exception("Consul parameter $name of microservice $id not found!");
            }

            $data = json_decode($consulResponse->getBody());

            return base64_decode(current($data)->Value) ?: null;
        }
        catch (ClientException $e)
        {
            if (Response::HTTP_NOT_FOUND === $e->getCode())
            {
                throw new \Exception("Consul parameter $name of microservice $id not found!");
            }

            throw $e;
        }
        catch (ServerException $e)
        {
            throw new \Exception('Consul server error: ' . $e->getMessage());
        }
    }

    private static function getEnvironmentValue(string $name): string
    {
        if (false === $value = CacheHelper::getCacheData($name))
        {
            if ($value = self::getConsulValue($name))
            {
                CacheHelper::setCacheData($name, $value);
            }
        }

        return (string) $value;
    }

    private static function initEnvironment(string $id, string $appEnv = null): void
    {
        $environmentValues = [
            'APP_ENV'          => $appEnv ?: CacheHelper::getCurrentEnvironment(),
            'MICRO_SERVICE_ID' => $id,
        ];
        self::populateEnvironmentValues($environmentValues);
    }

    private static function parseEnvironmentValues(): array
    {
        $envFile = realpath(__DIR__ . '/../../.env.' . CacheHelper::getCurrentEnvironment());

        return (new Dotenv())->parse(file_get_contents($envFile), $envFile);
    }

    private static function populateEnvironmentValues(array $environmentValues): void
    {
        (new Dotenv())->populate($environmentValues);
    }

    private static function preloadEnvironmentValues(): void
    {
        $cacheKey = 'ENVIRONMENT_VALUES';

        if (false === $environmentValues = CacheHelper::getCacheData($cacheKey))
        {
            switch (CacheHelper::getCurrentEnvironment())
            {
                case 'prod':
                    $environmentValues = [];

                    foreach (self::getConsulKeys() as $key)
                    {
                        if ('/' === mb_substr($key, -1))
                        {
                            continue;
                        }

                        $explode  = explode('/', $key);
                        $variable = end($explode);

                        try
                        {
                            $environmentValues[$variable] = self::getEnvironmentValue($variable);
                        }
                        catch (\Exception $e)
                        {
                        }
                    }
                    break;

                case 'dev':
                case 'test':
                    $environmentValues = self::parseEnvironmentValues();
                    break;
            }

            CacheHelper::setCacheData($cacheKey, $environmentValues);
        }

        self::populateEnvironmentValues($environmentValues);
    }

    public function getEnv($prefix, $name, \Closure $getEnv)
    {
        try
        {
            $value = $getEnv($name);
        }
        catch (EnvNotFoundException $e)
        {
            $value = self::getEnvironmentValue($name);
        }

        return (string) $value;
    }
}
```

We read only .env files in a **dev/test** environment, in a **prod** we use Consul. Our cache helper is a tiny wrapper over localhost Memcached.

And our **services.yml** we use consul env processor:

```
parameters:
    api_secret: '%env(string:consul:API_SECRET)%'
    dns_api_host: '%env(string:consul:DNS_API_HOST)%'
    http_api_host: '%env(string:consul:HTTP_API_HOST)%'
```
