### ISSUE TITLE
Error: Call to a member function set() on integer

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#25175]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4RC2

```
Fatal error: Uncaught Error: Call to a member function set() on integer in /Users/andreybolonin/www/asat/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:640 
Stack trace: 
#0 /Users/andreybolonin/www/asat/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(137): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#1 /Users/andreybolonin/www/asat/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(197): Symfony\Component\HttpKernel\Kernel->boot() 
#2 /Users/andreybolonin/www/asat/web/index.php(20): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#3 {main} thrown in /Users/andreybolonin/www/asat/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 640
```

**Comment by javiereguiluz** [comment]
The line number 640 on Symfony 3.4 Kernel.php is this one:

https://github.com/symfony/symfony/blob/a19d1e5d15c174d9d66758e587fb1788b82bb19e/src/Symfony/Component/HttpKernel/Kernel.php#L640

It's really strange that this particular line of code is failing. Can you give us some context about your Symfony application? It's a new one or are you upgrading an existing app? Is it a regular app or are you doing something fancy with the Symfony internals? Thanks!

**Comment by stof** [comment]
Does it happen when running Symfony in debug mode or in non-debug mode ?

I think that one case where this might happen is if you are running Symfony in non-debug mode with a cache generated with Symfony 3.3 or older (as it will try to boot the kernel with the old cache in this case).
If this is your case, delete your old cache.

**Comment by andreybolonin** [comment]
@stof `$kernel = new AppKernel('prod', false);`
