### ISSUE TITLE
Support Doctrine DSN in PdoSessionHandler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#25186]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

As reported in https://github.com/symfony/symfony-docs/issues/8420 PdoSessionHandler allows using PDO DSN ... which are completely different from the Doctrine DSN used in modern Symfony apps.

Adding Doctrine DSN support without breaking things would be simple because it's easy to detect which of the two DSN are being used. Is this something we want to do? Thanks!

**Comment by stof** [comment]
A simpler option would be to allow passing a DBAL Connection object to this SessionHandler. We already do it for the cache.

Adding support for the DBAL URL-based DSN directly and converting it to a PDO DSN would require duplicating lots of logic from DBAL.

**Comment by nicolas-grekas** [comment]
:+1: to what @stof said
