### ISSUE TITLE
[DependencyInjection] Autoconfiguration for more complex cases

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#25184]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.0

Recently symfony added two great features - [lazy console commands](https://symfony.com/blog/new-in-symfony-3-4-lazy-commands) and [service autoconfiguration](https://symfony.com/blog/new-in-symfony-3-3-service-autoconfiguration).

Correct me if I'm wrong but I don't think these two work together very well now. If I add a command and setup autoconfiguration like this:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Console\FooCommand: ~
```

```php
$container
    ->registerForAutoconfiguration(Command::class)
    ->addTag('console.command');
```

then the command won't be lazy because the command attribute is missing in the tag, right? And there is no way to fix this at the moment as far as I know without adding the tag manually in yaml.

This applies for many other cases where some details need to be added to the service tags - the tags need to be added manually even though it could theoretically be solved with some custom magic.

For example commands could be solved with something like this:

```php
$container
    ->registerForAutoconfiguration(Command::class)
    ->addCallback(
        function (Definition $definition) {
            $command = new $definition->getClass();
            // Or `ReflectionClass::newInstanceWithoutConstructor` to allow constructor injection.
            $definition->addTag('console.command', ['command' => $command->getName()])
        }
    );
```

Could something like this be added to Symfony 4.1? I'm only talking about the autoconfiguration callback feature, not the magic for commands - that's just an example to demonstrate a use-case.

I can try to send a PR if such feature is wanted in Symfony. But I need some advice with what the API should look like as I'm not that familiar with DependencyInjection component internals.

**Comment by nicolas-grekas** [comment]
I'm not sure I understand what you mean. What I understand from your description is something that is already solved in #23887, by allowing you to provide a default command name via a `protected static $defaultName` property that the pass handles. Do you mean something else?

**Comment by stof** [comment]
Our policy in this case is rather to have the compiler pass running the autodetection logic, which does not require any new feature (and works even when the tag is added manually).

If you are able to run the logic in callback, you can as well run it in the compiler pass. So I'm -1 on this feature.

**Comment by enumag** [comment]
@stof The same can be said about all autoconfiguration. Why was that feature added then?

**Comment by stof** [comment]
@enumag no. The autoconfiguration is all about adding the tag automatically (and in a way leaving things in the control of the user, to be able to turn it off for some services).

Making tag attributes optional by providing sane defaults for them exists since years (way before we started autoconfiguration, except that we extended it to more tags after enabling autoconfiguration)

**Comment by enumag** [comment]
@stof Alright, thank you!
