### ISSUE TITLE
UniqueEntityValidator overwrites data in loaded entity

### ISSUE THREAD

**Issue by bedrich-schindler** [symfony/symfony#25181]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.3.2

Hello,

I spent several hours with debugging Symfony and I have discovered a bug inside of the `UniqueEntityValidator.php`. First let me explain surrounding of the problem and then the problem itself. First I am attaching snippets, problem is described bellow.

I have (simplified) controller `CountryController.php` with `editAction` method:

    public function editAction(Request $request, $id)
    {
        /** @var CountryService $countryService */
        $countryService = $this->get('app.country');
        /** @var Country $country */
        $country = $countryService->findById($id);

        if (!$country) {
            $this->addFlash('error', 'back.country.not_found');
            return $this->redirectToRoute('back_country_list');
        }

        $form = $this->createForm(
            CountryType::class,
            $country
        );
        $form->handleRequest($request);

        if ($form->isValid()) {
            $countryService->edit($country);

            $this->addFlash('success', 'back.country.edited');
            return $this->redirectToRoute('back_country_edit', ['id' => $id]);
        }

        return $this->render(
            'AppBundle:back\country:edit.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

I have `CountryService.php` (only snippet):

        /**
         * @var EntityManager $em
         */
        private $em;
    
        /**
         * CountryService constructor
         *
         * @param EntityManager $em
         */
        public function __construct(EntityManager $em)
        {
            $this->em = $em;
        }
    
        /**
         * Find country by id
         *
         * @param $id
         * @return Country|null
         */
        public function findById($id)
        {
            return $this->em->getRepository('AppBundle:Country')->find($id);
        }

I have form `CountryType.php` with `buildForm` method:

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', TextType::class, [
                'label' => 'country.label'
            ])
            ->add('shortLabel', TextType::class, [
                'label' => 'country.short_label'
            ])
            ->add('chief', EntityType::class, [
                'label' => 'country.chief',
                'class' => 'AppBundle:User',
                'choice_label' => 'username',
                'placeholder' => '-',
                'empty_data' => null,
                'required' => false,
            ])
            ->add('contactPerson', EntityType::class, [
                'label' => 'country.contact_person',
                'class' => 'AppBundle:User',
                'choice_label' => 'username',
                'placeholder' => '-',
                'empty_data' => null,
                'required' => false,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'action.save'
            ]);
    }

I have entity `Country.php` (without copied getters and setters):

    /**
     * Class Country
     * @package AppBundle\Entity
     */
    class Country
    {
        /**
         * @var integer Id of the country
         */
        protected $id;
        /**
         * @var string Label of the country
         */
        protected $label;
        /**
         * @var string Short label of the country
         */
        protected $shortLabel;
        /**
         * @var User|null Chief of the country
         */
        private $chief;
        /**
         * @var User|null Contact person of the country
         */
        private $contactPerson;

        // without copied getters and setters
    }

I have ORM configuration file `Country.orm.yml` :

    AppBundle\Entity\Country:
        type:  entity
        table: country
        id:
            id:
                type: integer
                generator:
                    strategy: AUTO
        fields:
            label:
                column: label
                type: string
                nullable: false
                unique: true
                length: 64
            shortLabel:
                column: short_label
                type: string
                nullable: false
                unique: true
                length: 32
        manyToOne:
            chief:
                targetEntity: AppBundle\Entity\User
                joinColumn:
                    name: chief
                    referencedColumnName: id
                    onDelete: RESTRICT
                    nullable: true
                fetch: EAGER
            contactPerson:
                targetEntity: AppBundle\Entity\User
                joinColumn:
                    name: contact_person
                    referencedColumnName: id
                    onDelete: RESTRICT
                    nullable: true
                fetch: EAGER

I have validation file `validaiton.yml`:

    AppBundle\Entity\Country:
        constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: label
                message: 'back.country.validation.label_not_unique'
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: shortLabel
                message: 'back.country.validation.short_label_not_unique'
        properties:
            label:
                - NotBlank:
                    message: 'back.country.validation.label_not_blank'
                - Length:
                    max: 64
                    maxMessage: 'back.country.validation.label_max_length'
            shortLabel:
                - NotBlank:
                    message: 'back.country.validation.short_label_not_blank'
                - Length:
                    max: 32
                    maxMessage: 'back.country.validation.short_label_max_length'

In attached `Country` form, there are two non-required fields `chief` and `contactPerson` which are of type `User` (that is extended entity of FOSUser entity). I use `EntityType` to load these users to selectbox. If there is any user set as `chief` or `contactPerson` and I want to unset them I simply select empty value, `chief => null` or `contactPerson => null` is then sent over the POST request. But even if request is passed to the `$form->handleRequest($request)` method, `chief` or `contactPerson` will remain unchanged (in state before editation). This shoud works according to documentation, so I started to debug ...

I opened Forms tab in the Profiler. For `country.chief` or  `country.contactPerson` form attributes under the submitted data section  there was correctly:

| Key                | Value
| ---------------- | -----
| View Format      | ""
| Normalized Format | null
| Model Format  | same as normalized format

But if I look directly into the `country` form (instead of `country.chief` or `country.contactPerson`) I saw:

| Key                | Value
| ---------------- | -----
| View Format      | same as normalized format
| Normalized Format | Country {
|| #id: 1
 || #label: "Label changed"
 || #shortLabel: "Short label"
 || -chief: User {}
 || -contactPerson: User {}
||}
| Model Format  | same as normalized format

**This is not correct, why value in the first table is correctly unset and same attribute in the entity is set to original user? .... So after few hours of debugging I discovered following bug in** `UniqueEntityValidator.php`:

I use `UniqueEntityValidator` for validating uniqueness of `label` and `shortLabel` (it can be seen in snippet above). If debugging cursor stepped from `Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator` line `138` (code `$result = $repository->{$constraint->repositoryMethod}($criteria);`), form data and `$country` in attached controller changed value to value received from repository on line 138. This is exact line that changes data in the rest of Symfony application. 

But this only changes null values to values fetched from database, string value remain unchanged.  If I remove Unique validation, everythink works ok. So line 138 of ``Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator` is the place where the problem is.

Thank you.

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue? And please also try to update your application first. There have been changes in the validator in more recent patch releases.

**Comment by bedrich-schindler** [comment]
@xabbuh Update tu current version 3.3.13 did not help. I will try to create example project but It will unfortunately take one or two days because of the lack of time.

**Comment by bedrich-schindler** [comment]
**Simple project that can reproduce this bug can be found here: https://github.com/bedrich-schindler/symfony_25181**

I discovered that ... Inside of the `$form->handleRequest($request)` method that is called in `editAction` method in `DefaultController.php` and then in `Symfony\Component\Form\Form.php` on line 667, `$dispatcher->dispatch(FormEvents::POST_SUBMIT, 'form.post_bind')` is called. Then some validator listener with `validateForm` method is callled. 

Before form validation, `contactPerson` is correctly set to `null`, but when validator starts to loop over constrains validators and line 139 in UniqueEntityValidator (` $result = $repository->{$constraint->repositoryMethod}($criteria);`) is reached, form data and data in controller (that are fetched from service using `findBy($id)` method) are overwritten. If you remove unique validation of `label` from `Country` in my project, it starts to work properly.

**Comment by bedrich-schindler** [comment]
@xabbuh I know you have a lot of stuff to do but I still see `Status: Waiting feedback` even if I have already posted example project with steps to reproduce. Did I forget something or everything is ok, only status did not change yet? :)

**Comment by Simperfit** [comment]
Status does not change automatically ;).

Do you want to try to fix this behaviour if we found out that this is really a bug ? Just wait for someone to acknowledge that this is a bug.

**Comment by Simperfit** [comment]
Status: Needs Review

**Comment by bedrich-schindler** [comment]
@Simper I 'm not sure whether I'm able to do that but I can try. Problem is that I don't know Symfony from inside and If there is problem somewhere else, I might not be able to fix it correctly as Symfony developers :)

**Comment by xabbuh** [comment]
@bedrich-schindler Thank you for providing the example application. Sadly, I didn't have any time yet to look into it. I hope to be able to do that "soon" and come back to you with some feedback.

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
This is related to your association being defined as eager. As we already have an existing issue for this (see #23961) I am going to close here. Thanks for the reproducer.
