### ISSUE TITLE
[HttpKernel] Arrays with scalar values passed to ESI fragment renderer throw deprecation notice

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#25191]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1

[`AbstractSurrogateFragmentRenderer::containsNonScalars`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Fragment/AbstractSurrogateFragmentRenderer.php#L98-L109) checks if URI attributes passed to ESI fragment renderer contain objects and if so, throws a deprecation notice. As I understand, arrays with scalar values should also be accepted, however, the method fails with arrays that contain pure scalar values.

It seems to me that the first `if` condition in the method should be:

```
if (is_array($value)) {
    return $this->containsNonScalars($value);
}
```

rather than:

```
if (is_array($value) && $this->containsNonScalars($value)) {
    return true;
}
```

**Comment by ro0NL** [comment]
Looks like you're right.

See also #https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Fragment/RoutableFragmentRenderer.php#L84
