### ISSUE TITLE
Improve error message when a service is missing and ServiceSubscriberInterface/a ServiceLocator is used

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#25196]
| Q                | A
| ---------------- | -----
| Bug report?      | DX one
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4/3.3

As seen in #25194, it can be hard for newcomers to know why `$this->get(Some::class)` doesn't work.
In a "failure driven development" spirit, we should improve the message, so that ppl can resolve that on their own.

**Comment by ro0NL** [comment]
if you're aiming for a `Did you forget to add <service> to <class>::getSubscribedServices()` that be cool i guess :)

Which makes me wonder should the proposed array_merge in https://github.com/symfony/symfony/issues/25194#issuecomment-347581793 happen out-of-the-box? Resolving parents at compile time.

**Comment by nicolas-grekas** [comment]
Something like that yes :)

> Resolving parents at compile time

calling the parent explicitly allows child classes to override and esp remove entries from the parent
not sure removing that responsibility/possibility from user's hand is a good idea

**Comment by ro0NL** [comment]
Right, perhaps too far fetched either. In a way it seems reasonable to say "define deps, per class" where parent access is implied / just works. Steering you to not rely on transitive deps.

> allows child classes to override 

That doesnt really require calling the parent anyway ;)

> and esp remove entries from the parent

That might even break the parent no?

Sorry for the different topic :) but it would make a `Did you forget to add` suggestion straightforward.

**Comment by nicolas-grekas** [comment]
> That might even break the parent no?

not if the child doesn't/replaces the part of the parent that needs the removed dep

**Comment by ro0NL** [comment]
i guess keeping the services tied is nice, but in _that case_ do you/we really care about an unused parent service? Guess what im thinking of is the feature as a spec, that you can extend. Not really requiring to let you do array_merge+parent::get. But that's perhaps also counter-intuitive-ish as from PHP perspective it might look weird ignoring the parent call.

Either way :+1: for the message.
