### ISSUE TITLE
[FrameworkComponent] Add options parameter to cache pools

### ISSUE THREAD

**Issue by fnxnet** [symfony/symfony#25199]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.0

I've just found out that while using config.yaml in order to configure cache pools there is no way to pass options to the adapter. As per _symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php_ it accepts only: adapter, public, default_lifetime, provider and clearer parameters. It would be grate if additional associative array named options could be added and then injected into adapter so i.e. environment variables could be passed.

**Comment by nicolas-grekas** [comment]
Which options would you provide? AFAIK, no adapter allow any option.

**Comment by Simperfit** [comment]
@fnxnet Could you please explain more the options you will need.

**Comment by fnxnet** [comment]
I mean the **MemcachedAdapter**. As far as I saw when you define pool it's created by factory using the **createConnection** static function from the provided adapter. Unfortunately I did not find any option to pass options to poll configuration so they can be passed over to createConnection. I guess that would be useful if possible.

**Comment by nicolas-grekas** [comment]
You should be able to provide the options as part of the DSN: `...?foo=bar`
Unless you have a more specific need, I don't think there is anything else to do here.

**Comment by fnxnet** [comment]
Sorry my bad - not the header but the client option. In MemcachedTrait I have:
` $client->setOption(\Memcached::OPT_BINARY_PROTOCOL, true);` which in my case does not work properly and causes delay in communication with memcache therefore only setting this to false would be any help.

**Comment by nicolas-grekas** [comment]
did you try adding `?binary_protocol=0`

**Comment by fnxnet** [comment]
no as I didn't know it will be parsed from the DSN. According to doc https://symfony.com/blog/new-in-symfony-3-3-memcached-cache-adapter there is nothing like that possible. Now I see in the code that should work:
```
if (isset($params['query'])) {
    parse_str($params['query'], $query);
    $params += $query;
    $options = $query + $options;
}
```
It's worth mention in the documention I guess.

**Comment by nicolas-grekas** [comment]
Please open a doc PR :)
I'm closing here as this should be resolved now.
