### ISSUE TITLE
[VarDumper] VarCloner chokes on GMP numbers

### ISSUE THREAD

**Issue by FGM** [symfony/symfony#25198]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Symfony version  | 3.3.13
| PHP Version | 7.1.11 

When dumping data, the VarCloner incorrectly attempts to clone elements in the data tree in doClone() depending on their type, looping on this switch: 
```php
                // [...]
                switch (true) {
                    case empty($v):
                    case true === $v:
                    case \is_int($v):
                    case \is_float($v):
                        continue 2;
                // [...]
```

However, if $v is a GMP number, this switch throws a recoverable fatal error, because the switch evaluation tries to evaluate `empty($v)` but `empty()` does not accept a GMP argument:

```php
// Minimal example in psysh:
$g = gmp_init('0');
=> GMP {#217}
empty($g);
// PHP Recoverable fatal error:  Object of class GMP could not be converted to boolean on line 1
```

The error needs to be caught to avoid crashing the dumper.

**Comment by nicolas-grekas** [comment]
See #25209
Would you like to contribute a caster for GMP numbers btw?
Displayed just "GMP {#217}" is a bit terse, would be great to display the actual value.

**Comment by FGM** [comment]
You beat me to it :+1:
