### ISSUE TITLE
File upload check(question)

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony#25208]
| Q                | A
| ---------------- | -----
| Bug report?      | possible
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.31

As I see, [here](https://github.com/symfony/symfony/blob/v2.8.31/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L113) handler have method to ensure that we are uploading files. In documentation I can read that all uploaded files will have `UploadedFile` type, while handler checks for `File` class. May be it is better to check for `UploadedFile` (or add comment in code to prevent future questions 😄 )?

**Comment by nicolas-grekas** [comment]
UploadedFile represents files managed by PHP, the ones that return "true" when http://php.net/is_uploaded_file is called on them.
But the linked request handler is not tied to only PHP as a source for uploaded files (some ppl do http servers in php directly.)
This opens the possibilty.
