### ISSUE TITLE
FatalErrorException: Class Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset)

### ISSUE THREAD

**Issue by laszlodobos** [symfony/symfony#25215]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-RC2

1. I have a working symfony 4.0.0-RC2.
2. composer require "doctrine/doctrine-bundle"

Using version ^1.8 for doctrine/doctrine-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/doctrine-bridge (v3.3.13)
    Loading from cache

  - Installing doctrine/doctrine-cache-bundle (1.3.2)
    Loading from cache

  - Installing jdorn/sql-formatter (v1.2.17)
    Loading from cache

  - Installing doctrine/dbal (v2.6.3)
    Loading from cache

  - Installing doctrine/doctrine-bundle (1.8.1)
    Loading from cache

Symfony operations: 2 recipes (e70c24a7aa43f7443d645ed209808347)
  - Configuring doctrine/doctrine-cache-bundle (1.3.2): From auto-generated recipe
  - Configuring doctrine/doctrine-bundle (1.6): From github.com/symfony/recipes:master

3. LogicException: To configure the ORM layer, you must first install the doctrine/orm package.

I remove the orm section from the doctrine.yaml config.

4. I get fatal error if I open the site or try to use the console:

> FatalErrorException: Error: Class Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset)

Thank you for the fix.

**Comment by xabbuh** [comment]
Until Symfony 4 is released you will manually update `symfony/doctrine-bridge` to 3.4 or 4.0 which comes with a `DoctrineDataCollector` implementation that is compatible with HttpKernel 4.0.
