### ISSUE TITLE
Form object unchanged upon submit

### ISSUE THREAD

**Issue by empiricalx** [symfony/symfony#25211]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.13

Upon submitting my form object seen unchanged,
Pre Populated value for record edit/update:

```
           Id: 7               ($form['id']->getData() )
    Name:  Entrances ($form['name']->getData() )
Parent Id: 1               ($form['parentId']->getData() )
 Is Active: 1               ($form['isActive']->getData() )
```

These values never got change upon submission.
Now the POST object shows the updated values:

```
[section_form] => Array
        (
            [id] => 7
            [name] => Entrances
            [parentId] => 6
            [isActive] => 1
            [_token] => YzRtP3HrejixB76UBKxE4emvvGCGIQgBcY0tAtbUJyA
        )
```

At this point I don't know if this is a normal behavior, a bug or something else (am I doing something wrong, or this way is not longer supported)
If is not a bug please provide an explanation of this behavior.

Thank you

**Comment by xabbuh** [comment]
I am sorry, but I do not understand what you mean. Would you mind showing some code (or even a small project) that allows to see what your are doing, what you expect and what happens instead?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by empiricalx** [comment]
You can close it, I have solved the issue, thank you.
