### ISSUE TITLE
ContextException instead of !isValid() with form Number type

### ISSUE THREAD

**Issue by anthonyrossetto** [symfony/symfony#25216]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

Hi,

I think there is a bug with the NumberType class. 

```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('label', TextType::class, [
                'label'         => 'XXX',
                'required'      => true
            ])
            ->add('hierarchicalWeight', NumberType::class, [
                'label'     => 'YYY',
                'required'  => true
            ]);  
}
```
And the controller :

```php

             $status = $this->get('users_hiearchical_status_repository')->find($id);

                $form = $this->createForm(MyFormType::class, $status, ['validation_groups'   => 'update', 'method'  => $request->getMethod()]);
                $form->handleRequest($request);

                if ($form->isSubmitted() AND $form->isValid()) {
                    $this->persistEntity($status);
                } else {
                  // ...
echo 'errors found !';
                }
```

When I submit the form with a value that is not a number (ie : "aaa"), there is a ContextException instead of showing 'errors found'.

If I use (as a workaround) a TextType instead of NumberType and a regex in the entity as a constraint, the 'errors found' is displayed.

Entity : 

```php
    /**
     * @ORM\Column(type="integer",unique=true, name="hierarchical_weight")
     * @Assert\NotBlank(message="...")
     * @Assert\Regex(
     *   pattern="/^[0-9]+$/i",
     *   message="...",
     *   groups={"create", "update"}
     * )
     */
    private $hierarchicalWeight;
```

This issue seems to be the same as https://github.com/symfony/symfony/issues/2389

**Comment by stof** [comment]
This does not seem to be the same than #2389 as this one was related to an incomplete implementation of the Intl stub, which was improved 6 years ago.

But as you don't give any information about the exception you get, there is no way for us to help you.

Please give details about the exception:

- exception message
- exception location (file and line)
- exception stack trace

**Comment by anthonyrossetto** [comment]
Exception message : Warning: NumberFormatter::parse(): Number parsing failed
Exception type : Symfony\Component\Debug\Exception\ContextErrorException

in vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer.php (line 174)

```php
   $result = $formatter->parse($value, $type, $position);
```

**Comment by Simperfit** [comment]
It's the Debug compenets catching the warning and showing it to you. But I guess the warning is intended, you should not pass text to the number formatter.

It this is DEV or in PROD ?

**Comment by anthonyrossetto** [comment]
In DEV ;)

**Comment by anthonyrossetto** [comment]
UP

**Comment by xabbuh** [comment]
Can you create a small project that allows to reproduce your issue?

**Comment by xabbuh** [comment]
@anthonyrossetto Any chance for a reproducing example?

**Comment by anthonyrossetto** [comment]
It works with a small project.

I'll try to find the bug with a more complicated example that is not my full Symfony project ;)

**Comment by anthonyrossetto** [comment]
1) Create a new Symfony project (3.4)
2) Open the zip attached to this message and replace **app**, **src**, **web** folders of your project.
3) Clear the cache
4) Enjoy 

[app.zip](https://github.com/symfony/symfony/files/1591914/app.zip)

**Comment by anthonyrossetto** [comment]
UP ;)

**Comment by anthonyrossetto** [comment]
UP :)

**Comment by anthonyrossetto** [comment]
@xabbuh UP :)

**Comment by xabbuh** [comment]
@anthonyrossetto Sorry, but I cannot reproduce. For me, there is no PHP warning and the `TransformationFailedException` is thrown as expected.

**Comment by anthonyrossetto** [comment]
Could I send you all my project folder (with Symfony) ?

**Comment by xabbuh** [comment]
Can't you just create a repository on GitHub?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
