### ISSUE TITLE
symfony-lock: ensure that all packages are using a specific major version

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony#25210]
| Q                | A
| ---------------- | -----
| Bug report?      |  no
| Feature request? | yes
| BC Break report? |  no
| RFC?             | yes
| Symfony version  | any

I created a package similar to `symfony/lts` with the difference that it ensures that every installed Symfony packages are in a specific major version (2, 3 or 4).
It is designed to be used in CIs (Travis) to check that a given library and its dependencies are 100% compatible with a specific major version (i.e. Symfony 2.8, 3.4 or 4.0), without requiring packages from previous major versions (`symfony/lts` allows this behavior).
It is especially useful now to find bundles using dependencies not compatible yet with Symfony 4.

It is available here: https://github.com/dunglas/symfony-lock

Would you be interested to move it in the `symfony` org?
I should also be integrated in symfony/symfony-docs#8701 (ping @Nyholm, @symfony/deciders)

**Comment by stof** [comment]
Well, I actually argued in the past with @nicolas-grekas about the fact that `symfony/lts` 3.x should conflict not only with 4+ but also with 2.x (because people are asking about having symfony 3.x when they use it IMO).

I'm not sure we need 2 different packages doing almost the same.

**Comment by nicolas-grekas** [comment]
The discussion happened here: https://github.com/symfony/lts/issues/3
And I'm still convinced the lower bound is restricting the choice for the user, in a way that cannot be escaped, so symfony/lts is fine as is IMHO.
FOR CI ONLY, I think this makes sense though.

**Comment by Tobion** [comment]
I agree with @stof to not overcomplicate it and just do that in lts.

**Comment by dunglas** [comment]
I agree on the principle (I was sure that it was the behavior of `lts`), but `lts` is installed by default by Flex. So if we do that now, it means that a lot of bundles will not be able to be installed when using the Symfony 4.

**Comment by xabbuh** [comment]
There could be a different package which does exactly what you are asking for (which may be useful in CI environments). For users, being so restrictive does not sound convenient to me. For example, when starting a new application you do not care whether the component you get is 3.4 or 4.0. Allowing both makes it easier if you depend on other libraries which only partially are compatible with Symfony 4.

**Comment by Nyholm** [comment]
I, as an application developer, does not care what version of the component I use. As long as it "works". 

I, as a library author, I would very much would like to test if my library works with SF4 only components. I would love to get an installation error on travis if my package cannot be installed.

**Comment by dunglas** [comment]
@Nyholm great we'll move `lock` in :)

**Comment by Nyholm** [comment]
FYI: https://github.com/php-http/stopwatch-plugin/pull/8

**Comment by lyrixx** [comment]
I like the idea, but I'm not sure the name is the best, because it kind of conflicts with the [lock component](https://github.com/symfony/lock) :/

**Comment by nicolas-grekas** [comment]
symfony/lts-lock?
symfony/lts-strict?

**Comment by nicolas-grekas** [comment]
symfony/lts-for-tests

**Comment by dunglas** [comment]
`symfony/major`?

**Comment by nicolas-grekas** [comment]
"major" is dead :)
https://medium.com/sapioit/why-having-3-numbers-in-the-version-name-is-bad-92fc1f6bc73c

**Comment by dunglas** [comment]
We could rename it to `symfony/breaking` when we'll switch to explicit versioning ^^

**Comment by Nyholm** [comment]
Just a crazy idea: `symfony/force-version`

It will be super readable in .travis.yml: 

```
  DEPENDENCIES="symfony/force-version:4"
```

**Comment by nicolas-grekas** [comment]
>   DEPENDENCIES="symfony/force-version:4"

love it :)

**Comment by dunglas** [comment]
👍 for force version

**Comment by keradus** [comment]
Regardless that I would be happy having it even in `lts` directly, I could understand the reasoning why not to do it.
`symfony/force-version` would be really great in that case indeed, now I see ppl adding crap to their CI config like manually update every single Sf dependency they have, `lts` is not fixing that fully (due to discussion above), and this new package would ease that a lot.

Eager to see it happening :+1:
Happy to help, if needed.

**Comment by Nyholm** [comment]
What is the status on this issue? Should we ask @fabpot to create the repo and package?

**Comment by ostrolucky** [comment]
This is slippery slope. In CI, I would like a way to lock to specific minor version too. 

Just use similar snippet [I used in DoctrineBundle](https://github.com/doctrine/DoctrineBundle/blob/4ab04c00f1c6449c4aaa3fc60d57c3238ea3530e/.travis.yml#L38). Much more flexible.

**Comment by dunglas** [comment]
Any update?

**Comment by nicolas-grekas** [comment]
Related to https://github.com/symfony/skeleton/pull/61: we might want to create a new metapackage that would allow restricting to a lowest major*+minor* version.

**Comment by Tobion** [comment]
How about a new meta package with versions 
- 4: allows any symfony packages in 4.x
- 4.1: allows any symfony packages in 4.1.x
- 4.2: allows any symfony packages in 4.2.x
- etc.

So it would behave like symfony/symfony in terms of versions.

**Comment by nicolas-grekas** [comment]
New package released, see https://github.com/symfony/force-lowest

**Comment by keradus** [comment]
great news !
