### ISSUE TITLE
[VarDumper] Create a caster for GMP numbers

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#25222]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

right not, dumping a GMP number it a bit terse:
```
dump(gmp_init('0'));
=> GMP {#217}
```
would be better to display the actual value.

**Comment by Simperfit** [comment]
I'm doing it.
