### ISSUE TITLE
simple-phpunit looping until the root

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#25228]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

#25068 introduced a bug when using `bin-dir: bin` in Composer.

This condition will always return `true` until `/` is reached: 
https://github.com/symfony/symfony/blob/bd4fe8d86fc01316b158703c3aa57b0325001340/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L30-L35

A simple workaround is to avoid using `bin` as a `bin-dir`.

**Comment by COil** [comment]
I confirm the issue and the fix. 👍
