### ISSUE TITLE
[YAML] Nested array incorrectly parsed

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#25239]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

Given

```php
$yaml = <<<YAML
services:
    foo:
        class: Foo
        arguments: ['@bar', '@baz', [
            '@qux',
            '%foo%',
            bar,
            123
        ]]

YAML;

dump(Symfony\Component\Yaml\Yaml::parse($yaml));
```

I get

```
Malformed inline YAML string: ['@bar', '@baz', [ '@qux', '%foo%', bar, 123 at line 8 (near " 123").
```

While this is valid at http://www.yamllint.com/

To make it work in SF i had to change the last lines to `123]]`

cc @xabbuh :-)

**Comment by xabbuh** [comment]
Do you know if this worked in a previous version?

**Comment by ro0NL** [comment]
For 2.7.38 i get

```
Malformed inline YAML string: ['@bar', '@baz', [ at line 4 (near "arguments: ['@bar', '@baz', [").
```

**Comment by xabbuh** [comment]
Thanks for the response. I think this needs to be fixed in 3.3 as this is the oldest maintained version that has support for multi-line structures. However, we would still need to rewrite some of its logic. You can take a first look at https://github.com/symfony/symfony/compare/3.3...xabbuh:issue-25239?expand=1 which still needs some work to cover certain edge cases.

**Comment by Simperfit** [comment]
@xabbuh did you advanced on that ? is it fixed already ?

**Comment by xabbuh** [comment]
IIRC it's the same as https://github.com/symfony/symfony/issues/25379#issuecomment-487478998

**Comment by xabbuh** [comment]
Can you confirm that #33658 will solve your issue?

**Comment by ro0NL** [comment]
i dont have the actual code at hand anymore, if the reproducer here now passes im fine :)

**Comment by xabbuh** [comment]
@ro0NL I just tried your example with the following script:

```php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Yaml\Yaml;

$yaml = <<<YAML
services:
    foo:
        class: Foo
        arguments: ['@bar', '@baz', [
            '@qux',
            '%foo%',
            bar,
            123
        ]]

YAML;

dump(Symfony\Component\Yaml\Yaml::parse($yaml));
```

The result is this:

```
array:1 [
  "services" => array:1 [
    "foo" => array:2 [
      "class" => "Foo"
      "arguments" => array:3 [
        0 => "@bar"
        1 => "@baz"
        2 => array:4 [
          0 => "@qux"
          1 => "%foo%"
          2 => "bar"
          3 => 123
        ]
      ]
    ]
  ]
]
```
