### ISSUE TITLE
[DependencyInjection][4.0] Private services are removed from compiled container

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#25242]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | unsure
| RFC?             | no
| Symfony version  | 4.0.0

The DI component is acting weird in 4.0.0. I'm currently working on https://github.com/facile-it/paraunit/pull/112 to allow Symfony 4, and [the build is broken only with Symfony 4](https://travis-ci.org/facile-it/paraunit/builds/309981797), no deprecations on 3.4.

I've already fixed the private/public service deprecations, and I'm currently debugging the issue. I found the root cause in the `RemoveUnusedDefinitionsPass`: many private services are considered unused and so removed from the DI. Maybe it's because they are inlined? If that's true, I'm not able to make them public in tests afterward to retrieve and inspect them.

**Comment by Jean85** [comment]
@nicolas-grekas maybe this has the same root cause of #25240?

**Comment by nicolas-grekas** [comment]
Fixed in #25244
That's just a missing deprecation.

**Comment by nicolas-grekas** [comment]
The linked patch is wrong: making a service public after compilation is a no-op/dead code basically.
You need to move that to a compiler pass, or better: create public aliases for tests.
See https://github.com/symfony/symfony/issues/24543

**Comment by Jean85** [comment]
> The linked patch is wrong: making a service public after compilation is a no-op/dead code basically.

Ok, good to know. Maybe we should deprecate/throw an error there?

> You need to move that to a compiler pass, or better: create public aliases for tests.

I'll try, thanks for the suggestion.

**Comment by nicolas-grekas** [comment]
Please check #26499
