### ISSUE TITLE
Var Dumper - Backwards compatibility error in 3.3.x to 3.4.0

### ISSUE THREAD

**Issue by Cheezykins** [symfony/symfony#25248]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.0

The dump helper method in 3.3.x had no return value,

In 3.4.0 it returns the input variables.

This unexpected change of signature from void return to mixed has caused breaking changes.

For example, in a template (in this case blade) doing ```{{ dump($var) }}``` has always worked, but because behind the scenes blade renders that to ```<? php echo e(dump($var)); ?>``` now that dump returns the input, it attempts to escape and echo the returned value, which can cause errors.

```(E_ERROR) htmlspecialchars() expects parameter 1 to be string, object given```

**Comment by nicolas-grekas** [comment]
I'm not sure we should change anything here: `dump()` never had a return value, so it's return value shouldn't be echoed in the first place. I'd suggest a fix in blade instead.

**Comment by ostrolucky** [comment]
Well according to [Backward Compatibility Promise](https://github.com/symfony/symfony-docs/blob/e177b95373d4715dbc0e6d899d95f530d3229775/contributing/code/bc.rst#id24) this is indeed BC break, but I guess it's too late for that now.

**Comment by nicolas-grekas** [comment]
Well, the global dump has never been really part of the promise. The VarDumper::dump() method is thought.
This one should be used instead to build the blade helper.
I'm closing as this won't change yes.
