### ISSUE TITLE
[3.4] "The "esi" renderer does not exist."

### ISSUE THREAD

**Issue by stefandoorn** [symfony/symfony#25246]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

I just upgraded my app from 3.3.13 to 3.4.0. I'm using `render_esi` but without Varnish (local) and this exception gets thrown now. I cannot find anything in the changelog that points me to this issue, and haven't changed anything. In 3.3.13 it was working (and is) properly. 

```
InvalidArgumentException:
The "esi" renderer does not exist.

  at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php:80
  at Symfony\Component\HttpKernel\Fragment\FragmentHandler->render('http://webshop.tj.dev/app_dev.php/_partial/prods/all-ordered-position?template=Header/Menu/mobileProducts.html.twig', 'esi', array('ignore_errors' => false))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php:77)
  at Symfony\Component\HttpKernel\DependencyInjection\LazyLoadingFragmentHandler->render('http://webshop.tj.dev/app_dev.php/_partial/prods/all-ordered-position?template=Header/Menu/mobileProducts.html.twig', 'esi', array())
     (vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/HttpKernelRuntime.php:62)
  at Symfony\Bridge\Twig\Extension\HttpKernelRuntime->renderFragmentStrategy('esi', 'http://webshop.tj.dev/app_dev.php/_partial/prods/all-ordered-position?template=Header/Menu/mobileProducts.html.twig')
     (/dev/shm/sylius/cache/dev/twig/e9/e9fbf256aa4ffb13ca307869b1d470db72cf5d5d8326ad0bbeee5556f72fc6ef.php:43)
  at __TwigTemplate_afcdc7b528eb52c92a069d8db9eef3173363b272acab665985298629010d2c72->doDisplay(array(
...
Lots of variables here :-)
...
 (vendor/twig/twig/lib/Twig/Template.php:366)
  at Twig_Template->display(array())
     (vendor/twig/twig/lib/Twig/Template.php:374)
  at Twig_Template->render(array())
     (vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:49)
  at Symfony\Bridge\Twig\TwigEngine->render('@SyliusShop/Homepage/index.html.twig', array())
     (vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:45)
  at Symfony\Bundle\TwigBundle\TwigEngine->render('@SyliusShop/Homepage/index.html.twig', array())
     (vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:72)
  at Symfony\Bundle\TwigBundle\TwigEngine->renderResponse('@SyliusShop/Homepage/index.html.twig')
     (src/AppBundle/Controller/HomepageController.php:50)
  at AppBundle\Controller\HomepageController->indexAction(object(Request))
  at call_user_func_array(array(object(HomepageController), 'indexAction'), array(object(Request)))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:42)
```

**Comment by nicolas-grekas** [comment]
ping @ro0NL?

**Comment by dmaicher** [comment]
Can confirm the problem. For some reason the `EsiFragmentRenderer` service seems not properly registered?

```
app/console debug:container fragment.renderer.esi
```
```
In ContainerDebugCommand.php line 211:
                                                         
  No services found that match "fragment.renderer.esi".  
                                                         

debug:container [--show-private] [--show-arguments] [--tag TAG] [--tags] [--parameter PARAMETER] [--parameters] [--types] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]

**Comment by dmaicher** [comment]
With this diff it seems to be working again for me.

```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
index e284821..26d3c5b 100644
--- a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
+++ b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
@@ -451,15 +451,10 @@ class FrameworkExtension extends Extension
     private function registerEsiConfiguration(array $config, ContainerBuilder $container, XmlFileLoader $loader)
     {
         if (!$this->isConfigEnabled($container, $config)) {
-            $container->removeDefinition('fragment.renderer.esi');
-
             return;
         }
 
         $loader->load('esi.xml');
-
-        $container->getDefinition('esi')->setPrivate(true);
-        $container->getDefinition('esi_listener')->setPrivate(true);
     }
 
     private function registerSsiConfiguration(array $config, ContainerBuilder $container, XmlFileLoader $loader)
```
This was changed by @xabbuh and @nicolas-grekas in 3.4+

**Comment by stefandoorn** [comment]
Then it might also be related to this change (making the services private in the service definition): https://github.com/symfony/symfony/compare/v3.3.13...v3.4.0#diff-ff277ab5809bae0fa5fdf6f5ccfec9d3

**Comment by ro0NL** [comment]
#23088 is this related in a way?

**Comment by xabbuh** [comment]
Can you show the `framework` configuration you use?

**Comment by stefandoorn** [comment]
Config.yml:

```
framework:
    translator: { fallbacks: ["%locale%", "en"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        handler_id: ~
```

Config_dev.yml (as I only tested it on my dev environment for now):

```
framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
```

**Comment by stefandoorn** [comment]
In my config_prod.yml I have this:

```
framework:
    esi: { enabled: true }
```

On `dev` I don't have that, as I don't want the stuff to be cached while developing. Might be the issue, but used to work in 3.3.13.

**Comment by xabbuh** [comment]
Is your application based on the Standard Edition or did you create it using Flex?

**Comment by stefandoorn** [comment]
It's based on the Standard Edition, created about an year ago.

**Comment by xabbuh** [comment]
This looks expected to me. If you do not enable ESI in the `dev` environment, your templates will indeed be not able to make use of the renderer. If that did not throw an error before, this looks like an issue in 3.3 to me instead.

**Comment by stefandoorn** [comment]
Sounds reasonable. So in that case it's advised to enable `esi` on global configuration but not include an `AppCache` instance in `app_dev.php`? I would like to have ESI not really working locally, to avoid caching requests internally while developing.

**Comment by xabbuh** [comment]
If the requests does not come from a client that is capable to deal with ESI tags, the renderer will fall back to the inline renderer. So yes, just enabling the option for all environments, but not enabling the `AppCache` would be the way to got.

But be aware, that not having the cache enabled during development, will make it very hard to detect cache misconfiguration before they go to production.

**Comment by nicolas-grekas** [comment]
So, we need a PR on 3.3 throwing an exception? Anyone willing to do it?

**Comment by dmaicher** [comment]
@nicolas-grekas throwing where?

Just do `$container->removeDefinition('fragment.renderer.esi');` on 3.3 as well and let it throw `InvalidArgumentException: The "esi" renderer does not exist.`? Or something more specific?

**Comment by nicolas-grekas** [comment]
> If that did not throw an error before, this looks like an issue in 3.3 to me instead.

I was just reacting to @xabbuh's comment :)

**Comment by xabbuh** [comment]
Whatever the reason but being able to use the ESI renderer without enabling ESI looks wrong to me and I think this did not always work like this in the past.

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/25489

WDYT?

**Comment by bruno-ds** [comment]
Hello, 
maybe the doc. should include : 
```
framework:
    esi: { enabled: true }
```

ie in : https://symfony.com/doc/current/http_cache/esi.html  it sohuld be added to : 
```
# config/packages/framework.yaml
framework:
    # ...
    fragments: { path: /_fragment }
```

may here also :  https://symfony.com/doc/current/reference/twig_reference.html#render-esi

**Comment by xabbuh** [comment]
@bruno-ds For the record, this seems to documented here: https://symfony.com/doc/current/http_cache/esi.html#using-esi-in-symfony
