### ISSUE TITLE
[RFC] Exceptions that suggest your missing package

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25256]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1.0

The negative of Flex is that if you try to use a feature that's not installed, you'll get an error. Recently, we updated the exception messages in `ControllerTrait` to suggest the package that the user is missing when necessary.

But there are so many other cases. For example, if you use `{{ asset() }}` in Twig without the `Asset` component:

<img width="565" alt="screen shot 2017-12-01 at 1 28 32 pm" src="https://user-images.githubusercontent.com/121003/33497328-8c9c641c-d69b-11e7-8671-c4c97533b4a8.png">

Idea: Add new dev-only behavior that somehow *enhances* this error page to add a:

> To fix this, run "composer require asset"

We would maintain a list of error patterns/strings and what package is needed somewhere. This could even be stored in Flex itself, so that it could be updated easily and more often.

**Comment by nicolas-grekas** [comment]
in the Debug component?
be a more local patch would be easier to maintain.
e.g. in this case, is there anyway to hook into the failure, should we create one?

**Comment by fabpot** [comment]
ahah, this is on my todo-list. Not sure where that would be best though.

**Comment by nicolas-grekas** [comment]
Locally to every failure IMHO. There need to be an inventory somewhere. And I fear maintaining that in a separate location will be unmaintainable.

We could also keep the messages, but add a method on exception classes like "setMissingComponent", and use that in some generic renderer.
Or we could just put that in the messages.

**Comment by sroze** [comment]
I don't think that putting this in the messages is sustainable. @weaverryan's example is good to show that it won't be possible to add something about the component to be installed with such exception.

The thing that is installed with every Symfony skeleton application is the `FrameworkBundle` and I believe it's the right place to add such handling. We could have some extensions in it that would catch Twig's functions, missing classes and services and suggest components, based on the list of provided twig functions, classes and services for a given list of components.

**Comment by weaverryan** [comment]
Yea, I agree with @sroze: I'm not sure this is really possible (the missing Twig function is a good example) by calling a `setMissingComponent` method everywhere necessary. But yea, maintaining this list and causing extra traffic on the main repo is legitimate.

One option would be to create a new repository that contains *just* this data and add that as a dependency to `frameworkbundle`. That would simply be a way to push the traffic to a different repository... if it's worth it.

**Comment by sroze** [comment]
@fabpot what's the way forward to improve the DX here?

**Comment by weaverryan** [comment]
Well, it was solved for Twig filters/functions specifically.... So the question now is: can/should we just continue to solve these issues one-at-a-time as we discover them? Or should we add a more over/arching system.

Right now... I can’t be sure... but I think we may be able to solve this on a case-by-case basis.
