### ISSUE TITLE
[Twig] Whitespace control modifier missing in form layouts

### ISSUE THREAD

**Issue by kubawerlos** [symfony/symfony#25252]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=2.7

There is a single whitespace control modifier missing in form layouts, so new line from here: [form_div_layout.html.twig#L351](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L351) would be present in e.g. CollectionType Field in `data-prototype` attribute.

**Comment by Simperfit** [comment]
Do you want to provide a PR for this?
