### ISSUE TITLE
[DependencyInjection][4.0] Defining a private synthetic service shouldn't be possible

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#25253]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0

[UPDATE] I was attempting to do something that shouldn't have worked.

This stems from https://github.com/facile-it/paraunit/pull/112 too, as #25242.

I was following [the suggestion](https://github.com/symfony/symfony/issues/25242#issuecomment-348482620) from @nicolas-grekas to use public aliases to access private services during tests, but I've found an issue with **private synthetic services**.

Basically, if you have a private synthetic service that you want to access during a test, you have to do these 4 operations:

 * add synthetic service definition **as private**
 * add public alias
 * compile
 * set the synthetic service

...and the retrieve the service through the alias.

With 3.4 and that order of operations, it works.
With 4.0, it doesn't work, even with different orders. Basically I can move around just the command that sets the synthetic service, but:
 * setting the synthetic service as the first operation makes the service unreachable by the consequent alias definition:
> InvalidArgumentException: Unable to replace alias "public_alias" with actual definition "[...]".
>
> /home/user/project/vendor/symfony/dependency-injection/Compiler/ReplaceAliasByActualDefinitionPass.php:57
[...]
> Caused by
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "[...]"

 * setting the synthetic service erases any linked alias, so it must be done after the compilation, or the alias must be defined after;
 * the alias must be defined before the compilation, or the service gets inlined since it's private

Am I missing something else?

**Comment by nicolas-grekas** [comment]
how can a synthetic service be private?
there is even a compiler pass that forbids that...

**Comment by Jean85** [comment]
Well, why it shouldn't? I'm using it to inject the actual instance of `OutputInterface`, and by default in SF 4 is private. I don't need it public because it's already injected where it's needed, except for the tests, where I want to check the console output of my application.

Obviously I've set it public for now as a workaround.

PS: I'm not talking about a full SF stack app, it's a CLI lib, does it change anything?

**Comment by nicolas-grekas** [comment]
If you can "set" a service from the outside, then you can "get" is also.
Which means it's public. That's why.
The most surprising is that you actually managed to create this private synthetic definition and compile the container with it.

**Comment by Jean85** [comment]
Found the issue then.
```php
        $container = new ContainerBuilder();
        $container->register('test')
            ->setPrivate(true)
//            ->setPublic(false)
            ->setSynthetic(true);
        
        $container->compile();
```
This works until I uncomment that line, and then the compiler pass you were talking about start complaining.

**Comment by nicolas-grekas** [comment]
correct, that's because setPrivate marks the service as "public but private in SF4"
so it's still public, but with a deprecation

**Comment by nicolas-grekas** [comment]
@Jean85 could you please check that #25264 now throw a deprecation in this situation?
If you want to contribute a test case, you're more than welcomed :)

**Comment by Jean85** [comment]
@nicolas-grekas #25264 seems to work, opened #25302 for the test.

Still, shouldn't we disallow (or throw a deprecation) when setting a synthetic service as private?

**Comment by nicolas-grekas** [comment]
@Jean85 see https://github.com/symfony/symfony/pull/25302/files#diff-8aeba2b88d0347062017ee160a6beb49R544

That's exactly the deprecation you're asking for :)
