### ISSUE TITLE
[DI] Local service binding conflict

### ISSUE THREAD

**Issue by grachevko** [symfony/symfony#25251]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no?
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

```yaml
services:
    _defaults:
        bind:
            $debug: '%kernel.debug%'
```
```php
use App\Debug\Debug;

class Foo 
{
    public function __construct(Debug $debug) {}
}
```

`
Type error: Argument 1 passed to Foo::__construct() must be an instance of App\Debug\Debug, bool given
`

Class `Debug` also exist in container. This is normal behavior or maybe it need to compare types between bind and type hinting?

**Comment by stof** [comment]
name-based bindings are winning over typehint-based autowiring

**Comment by nicolas-grekas** [comment]
Yes, that's expected, as explained by @stof.
Use more specific bindings.
