### ISSUE TITLE
[RFC] Split exception logging from rendering

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#25266]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Recently did a project where, for API purpose, we created an exception listener to transform those into specialized json responses.

The funny part is we now effectively disabled exception logging; discovered on prod :-) Because our custom  response set, the built-in exception listener no longer runs; thus no logging.

The trick is to copy `Symfony\Component\HttpKernel\EventListener\ExceptionListener::logException()` and call as needed. Basically you need to dive into internals to figure it out.

Wondering... can we move the `logException()` logic and make it a (better) feature?

**Comment by ovrflo** [comment]
Had the exact same problem on 2 projects that were mainly APIs. Also fixed it by copy/paste.
+1 For decoupling logging from generating a response.

**Comment by weaverryan** [comment]
Yea, this has been in my mind for awhile too. Can you create a PR?
