### ISSUE TITLE
Invalid deprecation warnings due to service argument locator

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25265]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

Simple to repeat:

1) Create a controller that had an entity type-hint (i.e. one that uses the param converter): `public function showAction(Product $product)`

2) Clear the cache and refresh

You will see a deprecation warning that looks like this:

> Relying on service auto-registration for type "AppBundle\Entity\Product" is deprecated since version 3.4 and won't be supported in 4.0. Create a service named "AppBundle\Entity\Product" instead.

This is coming from the service locator that's created for the service argument resolver. In practice, this is a false deprecation, because we will never rely on this `Product` service being available. In fact, `container.autowiring.strict_mode: true` removes the deprecation but doesn't trigger any error.

Is there an easy way to fix this? Or should we simply document that you should add `container.autowiring.strict_mode: true` to your 3.4 project when trying to remove your autowiring deprecations (i.e. so that you can see errors instead of deprecation warnings).

**Comment by nicolas-grekas** [comment]
Documenting the parameter.

**Comment by weaverryan** [comment]
thx - I've added it as a task in the docs

**Comment by Herz3h** [comment]
So whats the solution to this ?

**Comment by mattiaswelander** [comment]
> 

I think the solution is to use the setting container.autowiring.strict_mode: true in the parameters section of the config.yml to avoid the false deprecation notices.
