### ISSUE TITLE
[WebProfilerBundle] Bug on installing symfony/web-profiler-bundle 3.4

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#25269]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

<img width="742" alt="screen shot 2017-12-02 at 3 01 48 pm" src="https://user-images.githubusercontent.com/2576509/33515909-d1c66f48-d771-11e7-875e-7b7bd48662cc.png">

**Comment by fabpot** [comment]
You should use `composer req profiler` instead.

We can't fix this as Web profiler does not depend on Twig bundle (for Silex for isntance).

**Comment by andreybolonin** [comment]
@fabpot thx
