### ISSUE TITLE
Upgrade the Web Framework Benchmarks to Symfony 4

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#25286]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

https://www.techempower.com/benchmarks/ runs and advertises a multi-technology benchmark for Web frameworks. Here are the ones for PHP:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP

As you can see, there is Symfony 3.3 app right now, contributed by @raziel057.

We should upgrade this to Symfony 4.0 (and rename the folder from "symfony2" to "symfony" btw).

@raziel057 are you willing to do it?

**Comment by raziel057** [comment]
@nicolas-grekas I already created a PR with improvements (renaming of folder and other small cleanups) which is not yet merged here:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/3000

Note that in last test (round 14), Symfony was running in version 2.8 with PHP 5.

You can see the performance improvement with Symfony 3.3 / PHP 7 here:
https://www.techempower.com/benchmarks/previews/round15/r14-vs-r15p1.html
https://www.techempower.com/benchmarks/previews/round15/

I can try to update to SF4 in another PR but if you prefer you can also do it.

**Comment by nicolas-grekas** [comment]
@raziel057 cool, thanks for it, you're doing well, I'm not going to borrow that from you :)
I've added some comments. Let's merge this first PR, then submit a new Flex+SF4-based one?

**Comment by raziel057** [comment]
@nicolas-grekas Thanks for your comments.

Maybe we can let the round 15 with SF 3.x and round 16 with SF 4 to show new perf improvements?

**Comment by nicolas-grekas** [comment]
when will that happen? what would be the benefit?

**Comment by raziel057** [comment]
It would be to have a profile for Symfony 3. But indeed if it takes to long to have a new round, maybe it's better to directly reflect the perfs of last release.

**Comment by fabpot** [comment]
I would not wait for 2 rounds before getting some Symfony 4 perf numbers. People are excited about  Symfony 4, let's give them some numbers ASAP.

**Comment by nicolas-grekas** [comment]
@raziel057 I'd be happy to review the PR to go to SF4, please ping me when you've opened it.
Cheers

**Comment by raziel057** [comment]
@nicolas-grekas Thanks for your review.

New PR is here: https://github.com/TechEmpower/FrameworkBenchmarks/pull/3139

**Comment by raziel057** [comment]
@nicolas-grekas PR https://github.com/TechEmpower/FrameworkBenchmarks/pull/3139 is ready to be merged.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/3139

Do you know if it's a good idea to use the same #FastCGI optimizations that are applied for ngnix config of Laravel ? https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/laravel/deploy/nginx.conf

I don't have time now to bench the perf improvements with this server. I used Apache 2.4.25 for my tests.

**Comment by raziel057** [comment]
I think you can close this ticket as TechEmpower/FrameworkBenchmarks#3139 is merged. Round 15 will use SF 4.0.2 with Flex.

**Comment by nicolas-grekas** [comment]
Thanks for your work and help @raziel057!
