### ISSUE TITLE
Data Transformers return null

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#25281]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

Since I upgraded to symfony 3.3.13 , Data Transformers return null
https://github.com/dustin10/VichUploaderBundle/issues/796

**Comment by dmaicher** [comment]
Could you create a reproducer for this bug? https://symfony.com/doc/3.3/contributing/code/reproducer.html

**Comment by imsheng** [comment]
https://github.com/imsheng/symfony-standard

**Comment by xabbuh** [comment]
Your data is set to `null` inside the event listener of the built-in `FileType` that we introduced in #24993 for security reasons. So you need to adapt your form type to account for these changes. I am going to close here as there is no bug to fix. Thank you for understanding.
