### ISSUE TITLE
[3.4] FrameworkBundle 3.4.0 requires beta version of symfony/event-dispatcher

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#25291]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.4.0

I just found out that FrameworkBundle 3.4.0 requires `symfony/event-dispatcher: ^3.4-beta4|~4.0-beta4`.

That doesn't seem right. 

Composer.json for v3.4.0
https://github.com/symfony/symfony/blob/0a47db379b8cc74cdd84e1e6870fafc4a4ac8351/src/Symfony/Bundle/FrameworkBundle/composer.json#L25

**Comment by curry684** [comment]
Also doesn't matter as Composer will not consider installing a beta unless you allowed it to do so, at which point it would anyway. The constraint is therefore valid and safe, and correctly indicates the minimum version it can work with.

**Comment by ruudk** [comment]
Weird. I have a hard time using the version on Travis.

It only works when `minimum-stability: dev`. 

See https://github.com/SimpleBus/JMSSerializerBundleBridge/pull/15 

In the last commit I removed the minimum-stability requirement and it doesn't install anymore.

**Comment by curry684** [comment]
I'm not really sure sure why specifically the 3.4.* build is failing, would have to dive into that, but rest assured that `minimum-stability` is not the proper fix, as it's a root package parameter only in Composer, meaning it's ignored in all libraries when included. Only the project itself can decide what stability it finds acceptable.

So no matter the reason behind the fail there, minimum-stability will only "fix" or rather mask it for the test suite, not for dependent projects.

I'd recommend a good session, starting with `composer why-not simple-bus/asynchronous-bundle:3.0.3`, to get to the root of that failure.

**Comment by ruudk** [comment]
@curry684 Thanks for the good explaination. You were right, it was related to another dependency. Once that dependency was tagged stable, it worked again. TIL about `why-not` command, thanks :v:

**Comment by curry684** [comment]
I wrote that command, I should know  😆
