### ISSUE TITLE
Different behaviours of YAML parsing of NULL with !php/const and !php/const:

### ISSUE THREAD

**Issue by IwfY** [symfony/symfony#25307]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

The deprecation warning suggests when parsing a YAML file to use **!php/const** instead of **!php/const:** for PHP constants. But the former is not able to evaluate the NULL constant.
See the difference between
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Yaml/Inline.php#L697
and
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Yaml/Inline.php#L710

**self::parseScalar('null')** returns the empty string so **constant('')** fails.

What should be used in YAML to express PHP's NULL constant?

For XML definitions it is still possible: https://github.com/symfony/framework-bundle/blob/master/Resources/config/workflow.xml#L12

**Comment by xabbuh** [comment]
In YAML, you don't need a constant for this:

```yaml
foo: ~
bar: null
```

Both examples will result in a `null` value.

However, we should of course look into this issue.

**Comment by xabbuh** [comment]
see #25325
