### ISSUE TITLE
[DX] Configure a default CSRF provider

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#25303]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

In this article -> https://symfony.com/doc/current/security/csrf_in_login_form.html we say:

> Then, the security component needs a CSRF token provider. You can set this to use the default provider available in the security component:

And we force the user to add some config somewhere. Can't we make this built-in CSRF provider the default value of this option to save one config step? Thanks!

**Comment by Simperfit** [comment]
I think this would help having an easier configuration, so I'm +1 on this!

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because it's been solved differently: simplifying docs and encouraging to use Guard authenticators instead of the old fomr_login config, which is where we showed this config.
