### ISSUE TITLE
ContainerInterface not found

### ISSUE THREAD

**Issue by ChrisWesterfield** [symfony/symfony#25316]
I just installed Symfony 4 from the Skeleton App according to the Website

http://symfony.com/doc/current/setup.html

Composer installs all required components.
But as soon as the console is executed I get the following error:
[vagrant@registration:/application$ ./bin/console 
PHP Fatal error:  Interface 'Symfony\Component\DependencyInjection\ContainerInterface' not found in /application/vendor/symfony/dependency-injection/ResettableContainerInterface.php on line 21
PHP Stack trace:
PHP   1. {main}() /application/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /application/bin/console:39
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /application/vendor/symfony/console/Application.php:122
PHP   4. App\Kernel->boot() /application/vendor/symfony/framework-bundle/Console/Application.php:63
PHP   5. App\Kernel->initializeContainer() /application/vendor/symfony/http-kernel/Kernel.php:125
PHP   6. App\Kernel->buildContainer() /application/vendor/symfony/http-kernel/Kernel.php:494
PHP   7. App\Kernel->getContainerBuilder() /application/vendor/symfony/http-kernel/Kernel.php:588
PHP   8. spl_autoload_call() /application/vendor/symfony/http-kernel/Kernel.php:635
PHP   9. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/http-kernel/Kernel.php:635
PHP  10. require() /application/vendor/symfony/debug/DebugClassLoader.php:142
PHP  11. spl_autoload_call() /application/vendor/symfony/dependency-injection/ContainerBuilder.php:50
PHP  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/dependency-injection/ContainerBuilder.php:50
PHP  13. require() /application/vendor/symfony/debug/DebugClassLoader.php:142
PHP  14. spl_autoload_call() /application/vendor/symfony/dependency-injection/Container.php:40
PHP  15. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/dependency-injection/Container.php:40
PHP  16. require() /application/vendor/symfony/debug/DebugClassLoader.php:142

Fatal error: Interface 'Symfony\Component\DependencyInjection\ContainerInterface' not found in /application/vendor/symfony/dependency-injection/ResettableContainerInterface.php on line 21

Call Stack:
    0.2018     398544   1. {main}() /application/bin/console:0
    0.2308    1527232   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /application/bin/console:39
    0.2442    1816768   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /application/vendor/symfony/console/Application.php:122
    0.2442    1816768   4. App\Kernel->boot() /application/vendor/symfony/framework-bundle/Console/Application.php:63
    0.2483    1871904   5. App\Kernel->initializeContainer() /application/vendor/symfony/http-kernel/Kernel.php:125
    0.2513    1908168   6. App\Kernel->buildContainer() /application/vendor/symfony/http-kernel/Kernel.php:494
    0.2514    1908208   7. App\Kernel->getContainerBuilder() /application/vendor/symfony/http-kernel/Kernel.php:588
    0.2514    1908208   8. spl_autoload_call() /application/vendor/symfony/http-kernel/Kernel.php:635
    0.2514    1908288   9. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/http-kernel/Kernel.php:635
    0.2539    2120936  10. require('/application/vendor/symfony/dependency-injection/ContainerBuilder.php') /application/vendor/symfony/debug/DebugClassLoader.php:142
    0.2539    2120936  11. spl_autoload_call() /application/vendor/symfony/dependency-injection/ContainerBuilder.php:50
    0.2539    2121016  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/dependency-injection/ContainerBuilder.php:50
    0.2549    2172112  13. require('/application/vendor/symfony/dependency-injection/Container.php') /application/vendor/symfony/debug/DebugClassLoader.php:142
    0.2550    2172112  14. spl_autoload_call() /application/vendor/symfony/dependency-injection/Container.php:40
    0.2550    2172208  15. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/vendor/symfony/dependency-injection/Container.php:40
    0.2555    2175512  16. require('/application/vendor/symfony/dependency-injection/ResettableContainerInterface.php') /application/vendor/symfony/debug/DebugClassLoader.php:142

As soon as I add the ContainerInterface from the Github Bundle, I get an error with the notification that the Exception Class is missing.
I thought symfony 4 is expected to be stable.
But currently I can't even get an running core package.

Please advise

**Comment by ChrisWesterfield** [comment]
Just tried it with an alternative documented way

> vagrant@registration:/application$ symfony/skeleton my-project-flex
-bash: symfony/skeleton: No such file or directory
vagrant@registration:/application$ composer create-project symfony/skeleton my-project-flex
Installing symfony/skeleton (v4.0.0)
  - Installing symfony/skeleton (v4.0.0): Loading from cache
Created project in my-project-flex
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.44): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/console (v4.0.0): Loading from cache
  - Installing symfony/routing (v4.0.0): Loading from cache
  - Installing symfony/http-foundation (v4.0.0): Loading from cache
  - Installing symfony/event-dispatcher (v4.0.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.0): Loading from cache
  - Installing symfony/http-kernel (v4.0.0): Loading from cache
  - Installing symfony/finder (v4.0.0): Loading from cache
  - Installing symfony/filesystem (v4.0.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.0.0): Loading from cache
  - Installing symfony/config (v4.0.0): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.0.0): Loading from cache
  - Installing symfony/framework-bundle (v4.0.0): Loading from cache
  - Installing symfony/yaml (v4.0.0): Loading from cache
  - Installing symfony/dotenv (v4.0.0): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 4 recipes (06d7f52eafb051375ecdf86354221edb)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Interface 'Symfony\Component\DependencyInjection\ContainerInterface' not found in /application/my-project-flex/vendor/symfony/dependency-injection/ResettableContainerInterface.php on line 21
!!  PHP Stack trace:
!!  PHP   1. {main}() /application/my-project-flex/bin/console:0
!!  PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /application/my-project-flex/bin/console:39
!!  PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /application/my-project-flex/vendor/symfony/console/Application.php:122
!!  PHP   4. App\Kernel->boot() /application/my-project-flex/vendor/symfony/framework-bundle/Console/Application.php:63
!!  PHP   5. App\Kernel->initializeContainer() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:125
!!  PHP   6. App\Kernel->buildContainer() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:494
!!  PHP   7. App\Kernel->getContainerBuilder() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:588
!!  PHP   8. spl_autoload_call() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:635
!!  PHP   9. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:635
!!  PHP  10. require() /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!  PHP  11. spl_autoload_call() /application/my-project-flex/vendor/symfony/dependency-injection/ContainerBuilder.php:50
!!  PHP  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/dependency-injection/ContainerBuilder.php:50
!!  PHP  13. require() /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!  PHP  14. spl_autoload_call() /application/my-project-flex/vendor/symfony/dependency-injection/Container.php:40
!!  PHP  15. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/dependency-injection/Container.php:40
!!  PHP  16. require() /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!  
!!  Fatal error: Interface 'Symfony\Component\DependencyInjection\ContainerInterface' not found in /application/my-project-flex/vendor/symfony/dependency-injection/ResettableContainerInterface.php on line 21
!!  
!!  Call Stack:
!!      0.2008     401632   1. {main}() /application/my-project-flex/bin/console:0
!!      0.2286    1533072   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /application/my-project-flex/bin/console:39
!!      0.2441    1822896   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /application/my-project-flex/vendor/symfony/console/Application.php:122
!!      0.2441    1822896   4. App\Kernel->boot() /application/my-project-flex/vendor/symfony/framework-bundle/Console/Application.php:63
!!      0.2503    1878248   5. App\Kernel->initializeContainer() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:125
!!      0.2555    1914728   6. App\Kernel->buildContainer() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:494
!!      0.2570    1914792   7. App\Kernel->getContainerBuilder() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:588
!!      0.2570    1914792   8. spl_autoload_call() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:635
!!      0.2570    1914872   9. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/http-kernel/Kernel.php:635
!!      0.2601    2127680  10. require('/application/my-project-flex/vendor/symfony/dependency-injection/ContainerBuilder.php') /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!      0.2601    2127680  11. spl_autoload_call() /application/my-project-flex/vendor/symfony/dependency-injection/ContainerBuilder.php:50
!!      0.2601    2127760  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/dependency-injection/ContainerBuilder.php:50
!!      0.2616    2178920  13. require('/application/my-project-flex/vendor/symfony/dependency-injection/Container.php') /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!      0.2616    2178920  14. spl_autoload_call() /application/my-project-flex/vendor/symfony/dependency-injection/Container.php:40
!!      0.2616    2179016  15. Symfony\Component\Debug\DebugClassLoader->loadClass() /application/my-project-flex/vendor/symfony/dependency-injection/Container.php:40
!!      0.2624    2182400  16. require('/application/my-project-flex/vendor/symfony/dependency-injection/ResettableContainerInterface.php') /application/my-project-flex/vendor/symfony/debug/DebugClassLoader.php:142
!!  
!!

**Comment by fabpot** [comment]
It works for me. That's weird. I can see that you are using Vagrant. Is it on a shared disk?

**Comment by nicolas-grekas** [comment]
One of the latest MacOS had a bug that triggered this AFAIK.

**Comment by ChrisWesterfield** [comment]
It'S inside an vagrant environment.
I'll try to run it in filesystem

**Comment by ChrisWesterfield** [comment]
I installed it from within macos this time it worked.
On an nfs mounted directory it doesn't work.

OS: MacOS High Sierra
Vagrant current Version
Parallels Desktop Pro
PHP on MacOS and Linux is Version 7.2

You propably might want to add a note with macos/vagrant that the composer plugin might not work correct and should be executed from within macos

thanks for the hint :-)

**Comment by nicolas-grekas** [comment]
Latest/next Sierra should fix it. Closing as that's an os bug.
