### ISSUE TITLE
Cannot install server on Symfony 3.4 with Flex without specifying the version number

### ISSUE THREAD

**Issue by mathieuimbert** [symfony/symfony#25314]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

This issue is pretty straightforward to reproduce.

I installed Symfony 3.4 with composer create-project:

    composer create-project symfony/skeleton my-project

Then trying to install the development server:

    composer require server

Installation of the web server will fail with the following errors:

```
Using version ^4.0 for symfony/web-server-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/web-server-bundle v4.0.0 conflicts with symfony/lts[v3].
    - symfony/web-server-bundle v4.0.0 conflicts with symfony/lts[v3].
    - symfony/web-server-bundle v4.0.0 conflicts with symfony/lts[v3].
    - Installation request for symfony/web-server-bundle ^4.0 -> satisfiable by symfony/web-server-bundle[v4.0.0].
    - Installation request for symfony/lts ^3 -> satisfiable by symfony/lts[v3].


Installation failed, reverting ./composer.json to its original content.
```

It seems like a version constraint issue, since `composer require server:3.4` works as expected.

**Comment by nicolas-grekas** [comment]
That's a valid issue, but on Composer's side.
In fact, I just opened https://github.com/composer/composer/issues/6869 on the topic.
Closing here (thanks for the issue anyway!)

**Comment by xabbuh** [comment]
That's how Composer behaves. If you omit the version, it will pick the highest stable version which is 4.0. So you have to be explicit here.
