### ISSUE TITLE
Invalid option(s) passed to @ParamConverter: format

### ISSUE THREAD

**Issue by kroshp** [symfony/symfony#25320]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.4.0

While 2.8 to 3.4 upgrade this error 

> `Invalid option(s) passed to @ParamConverter: format`

 is thrown for this kind of controller configuration working with 2.8 but no more in 3.4 :

```
...
@ParamConverter("listing", class="AppBundle:Listing", options={"id" = "listing_id"})
@ParamConverter("start", options={"format": "Y-m-d-H:i"})
@ParamConverter("end", options={"format": "Y-m-d-H:i"})
...
```

Here are the exception:

```
InvalidArgumentException
in vendor\sensio\framework-extra-bundle\Request\ParamConverter\DoctrineParamConverter.php (line 293)

       ...
          @trigger_error('The map_method_signature option of @ParamConverter is deprecated and will be removed in 5.0. Use the expr option or @Entity.', E_USER_DEPRECATED);
        }

        $extraKeys = array_diff(array_keys($passedOptions), array_keys($defaultValues));
        if ($extraKeys) {
            throw new \InvalidArgumentException(sprintf('Invalid option(s) passed to @%s: %s', $this->getAnnotationName($configuration), implode(', ', $extraKeys)));
        }

        return array_replace($defaultValues, $passedOptions);
    }
```
Doctrine converter seems to convert DateTime parameter instead of the DateTime converter.
Is it a bug?

The solution to fix this error was to precise each converter names and other ParamConverter informations in a precise order:

```
@ParamConverter("listing", class="AppBundle:Listing", options={"id" = "listing_id"}, converter="doctrine.orm")
@ParamConverter("start", options={"format": "Y-m-d-H:i"}, converter="datetime")
@ParamConverter("end", options={"format": "Y-m-d-H:i"}, converter="datetime")
```

It works if `converter ` option is at the end of `@ParamConverter`
It does not work if `converter `is at the beginning.

It would be nice to precise into the documentation that the ParamConverter options order is important  or maybe better to not take care of the order of `@ParamConverter` options.

Thanks

**Comment by xabbuh** [comment]
The param converters are part of SensioFrameworkExtraBundle. So please open an issue in their repository if you think you have found a bug. Thank you for understanding.
