### ISSUE TITLE
User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0

### ISSUE THREAD

**Issue by edurenye** [symfony/symfony#25328]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.4

I got the following deprecation after updating to Symfony 3.4:

> User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

Error:

> "exception" => ErrorException {#2303 ▼
    #message: "User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead."
    #code: 0
    #file: "vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php"
    #line: 275
    #severity: E_USER_DEPRECATED
    trace: {▼
      vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275 {▶}
      vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:85 {▶}
      src/AppBundle/Controller/Backend/DashboardController.php:16 {▼
        ›     ->setPageTitle('Dashboard')
        ›     ->addBreadcrumb('Dashboard', $this->generateUrl('backend.dashboard'), 'dashboard')
        › ;
      }
      AppBundle\Controller\Backend\DashboardController->indexAction() {}
      vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153 {▶}
      vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {▶}
     vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202 {▶}
      web/app_dev.php:33 {▶}
    }
  }

**Comment by javiereguiluz** [comment]
This is the kind of error I'd expect when using `$this->get('router')` in the controller, but in your case you are just using `$this->generateUrl()`, so I'd say this error shouldn't happen?

**Comment by stof** [comment]
The router is explicitly public in Symfony itself.

I suspect that this issue comes from a bundle overriding the router service, without making it as public explicitly (and without using the Symfony service decoration feature, which would take care of it).
Please check the list of bundles you are using.

**Comment by edurenye** [comment]
ControllerTrait.php:85 is doing $this->get('router') this is the problem.
Well, in Symfony 3.4 the default configuration sets everything including the routing to public false:

> services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

**Comment by sroze** [comment]
@edurenye as stated in the 2nd line of your copy/paste, this configuration is only for this given file, not for the entire configuration.

I believe that you should take more attention to @stof's answer as I shared the PoV. The `router` is explicitly public in Symfony 3.4+, therefore, you can use it. Maybe it is overwritten by another bundle or something? 🤔

**Comment by edurenye** [comment]
I'll check it, I paid attention to @stof's answer, just that I was confused about how Symfony works, thanks for your answers.

**Comment by edurenye** [comment]
Looks like this bundle is doing it: https://github.com/schmittjoh/JMSI18nRoutingBundle and it was fixed here: https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/215

Thank you very much!
 :+1:

**Comment by edurenye** [comment]
Still somebody is overwriting it and setting it to private, but I can't find who it is.

**Comment by sroze** [comment]
Can you paste the list of the enabled bundles you have?

**Comment by edurenye** [comment]
In fact it is the JMSI18nRoutingBundle bundle, and that did not fix it, I'm using the version 2.0.2 and this is still happening, I disable the bundle and it disappears, but now I don't get where is doing it, I checked the code and can't find it. I'll write it there and we can leave this issue closed.
