### ISSUE TITLE
[DependencyInjection] legit definition seems removed

### ISSUE THREAD

**Issue by Ioni14** [symfony/symfony#25335]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.1

Hello,

I'm not 100% sure if this is a bug, but when I use a controller service ID in a route (not elsewhere), the `RemoveUnusedDefinitionsPass` removes the controller.

Example :
```xml
<!-- routes.xml -->
<?xml version="1.0" encoding="UTF-8" ?>
<routes xmlns="http://symfony.com/schema/routing"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://symfony.com/schema/routing
        http://symfony.com/schema/routing/routing-1.0.xsd">
    <route id="app.my_route" path="/" methods="GET">
        <default key="_controller">app.my_controller</default>
    </route>
</routes>
```

```xml
<!-- services.xml -->
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="app.my_controller" class="App\Controller\MyController">
            <argument type="service" id="twig" />
        </service>
    </services>
</container>
```

**Comment by nicolas-grekas** [comment]
what's the error message?

**Comment by Ioni14** [comment]
In the exception : `Unable to parse the controller name "app.my_controller".`
and in the srcDevDebugProjectContainerCompiler.log : `Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass: Removed service "app.my_controller"; reason: unused.`

**Comment by nicolas-grekas** [comment]
> Unable to parse the controller name "app.my_controller".

that's enough for the first step: did that ever work? would that work `app.my_controller:yourAction`?

then, you should get another failure. I'd like to see if you can resolve the issue on your own :)

**Comment by Ioni14** [comment]
With `app.my_controller:myAction` :

```The "app.my_controller" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

**Comment by nicolas-grekas** [comment]
OK, so we should ensure this error is also displayed instead of `Unable to parse the controller name "app.my_controller".` in your previous situation (for ppl using `__invoke`).

Then, the message should be OK to resolve the issue on your own, isn't it?

**Comment by Ioni14** [comment]
My controller had `__invoke` in the previous situation. :/

**Comment by nicolas-grekas** [comment]
Yes, that's what I noted in my previous comment: we should throw a better error message - basically the second one you're getting.
Then, based on it, you should be able to fix your configuration, and to revert to using `__invoke`.

**Comment by Ioni14** [comment]
I'm sorry but unfortunately I don't understand why my declaration with `__invoke` is bad. :(
Is mandatory to make my controller public ?

**Comment by xabbuh** [comment]
Yes, controllers need to be public services.

**Comment by Ioni14** [comment]
ah, nice to know !
Thanks @nicolas-grekas and @xabbuh.

With the default `services.yaml`, the `App\Controller\` does not have explicit `public: true`. That's done by the tag `controller.service_arguments` ?

**Comment by xabbuh** [comment]
Exactly, the compiler pass that processes this tag makes sure that the tagged services are public.

**Comment by Ioni14** [comment]
ok, thanks a lot.
Sorry for the false report.

**Comment by nicolas-grekas** [comment]
@Ioni14 no pb :)

Actually that's not a false report: the message `Unable to parse the controller name "app.my_controller".` is not accurate. We need to generalize the work started in #25201 to all situations where a failure is related to private services.
