### ISSUE TITLE
[3.4] Cannot redeclare class Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser

### ISSUE THREAD

**Issue by gnutix** [symfony/symfony#25334]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.*
| PHP version  | 5.6.25

![Stacktrace](https://imgur.com/sZRqEgK)

We're currently upgrading a Symfony project to 3.4 on PHP 5.6.25 and my colleague has been having this issue since I've added the following block of code to our `AppKernel::registerContainerConfiguration` method: 

```
        $loader->load(function (ContainerBuilder $container) {
            $container->setParameter('container.autowiring.strict_mode', true);
            $container->setParameter('container.dumper.inline_class_loader', true);
            $container->addObjectResource($this);
        });
```

It only happened on a second request, and often it had to be a different request, not just the same one (aka refresh didn’t cause it).

He found two ways to make it work : 

1. Commenting out the line `$container->setParameter('container.dumper.inline_class_loader', true);`, or
2. Commenting out the line `$kernel->loadClassCache();` in `app_dev.php`

I personally can't reproduce the issue on my setup. Any idea what might be happening here ?

Also, it might look like we're not the only ones : https://stackoverflow.com/questions/47617879/symfony-duplicate-class-definition-in-cache

Thanks for your help.
gnutix

**Comment by rpac-tump** [comment]
His 1st way is ok for me, i can refresh without error. 
The solution on stackoverflow doesn't work for now...

**Comment by nicolas-grekas** [comment]
I think you need to remove this line from app*.php:
https://github.com/symfony/symfony-standard/blob/3.3/web/app.php#L7

**Comment by nicolas-grekas** [comment]
Try also removing L12 btw (loadClassCache)

**Comment by gnutix** [comment]
@nicolas-grekas That's indeed the second solution he found. However, I'm wondering why it happens and if it's a good idea to release standard code for Symfony that provoke this issue. I don't know the caching mechanism in details, but I guess there's an impact on performance for both solutions (disabling the inline dumper or the loadCacheClass) ?

I was also thinking that these code lines in app(_dev).php are not at all documented, and it might make sense to do so (especially if they can or should be removed under certain circumstances). WDYT ?

**Comment by nicolas-grekas** [comment]
Alternatively, can you try to turn container.dumper.inline_class_loader to false? and then to remove it?
(while reverting the previous change)

**Comment by weaverryan** [comment]
So are those 2 settings (loadClassCache and inline_class_loader) incompat? Is there something that needs fixing or not?

**Comment by nicolas-grekas** [comment]
There are incompatible, but that should be already handled:
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpKernel/Kernel.php#L842

dunnon what's missing - maybe a PHP version check also, adding `\PHP_VERSION_ID >= 70000` to the existing check.

@gnutix some more debugging hints would help (also trying this additional check please)

**Comment by gnutix** [comment]
So the `container.dumper.inline_class_loader` parameter should only be used in PHP >= 7 ?

**Comment by gnutix** [comment]
Setting `container.dumper.inline_class_loader` to `false` resolves the issue. My colleague will test with the additional PHP_VERSION check in Kernel.php.

**Comment by gnutix** [comment]
Thanks Nicolas for the fix. So the idea is that the AppKernel.php codes enables it, and behind the scene it's disabled for PHP < 7. Guess that's alright for such a "not-well-know" optimization parameter, but still I find it a bit strange. We do have PHP 7 conditions in app.php/app_dev.php so it's explicit. Why not in AppKernel too ?

**Comment by seblegall** [comment]
Thx for the fix @nicolas-grekas. We just crashed the all Meetic website due to this error. :-) I guess we will wait for the 4.4.2 to be release before upgrading to sf 3.4.

**Comment by sroze** [comment]
@seblegall You mean 3.4.2, right? 😄

**Comment by seblegall** [comment]
Yeah, of course. ;-)

**Comment by behradkhodayar** [comment]
Right after installing a `SF 3.4.1` it worked fine, but **only after a server restart** everything crashed getting the same error!

**Comment by mehdimabrouk** [comment]
You can upgrade to symfony3.4.2 and resolve the problem

**Comment by bennet-enqos** [comment]
I just removed the files in var/cache/prod and var/cache/dev inside the project folder. It worked for me
