### ISSUE TITLE
[DI] Compiled Container Does Not Call Base Class Constructor

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#25343]
| Q                | A
| ---------------- | -----
| Bug report?      | no (unexpected behavior)
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

While using the DIC component outside of the Symfony I found I need to define my own `base_class` while calling `PhpDumper::dump` in order to provide custom functionality. Compiled container indeed contains my class as a parent, however constructor of the class is not called. The generated constructor looks like that:

```php
    public function __construct()
    {
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = array();
        $this->syntheticIds = array(
            //...
        );
        $this->methodMap = array(
            //...
        );
        $this->aliases = array(
            //...
        );
    }
```

I checked and this behavior is consistent across 4.0, 3.4 and 3.3 with or without `as_files` enabled. I guess then the decision was deliberate.

Is there any reason why not to call the base container constructor? WDYT about adding such option?

**Comment by nicolas-grekas** [comment]
We could add some "initialize" hook that could be called at the end of the constructor, based on a new option to the "dump()" method.
Since you have a use case, you might have want to submit a PR?

**Comment by kiler129** [comment]
@nicolas-grekas Sure, I'll work something out probably tomorrow.

**Comment by nicolas-grekas** [comment]
I think we make this non-optional: the parent constructor used to be called with a ParameterBag instance previously at the very beginning of the overridden constructor. Let's always call `parent::__construct` with no arguments. PR welcome.

**Comment by xabbuh** [comment]
see #25762
