### ISSUE TITLE
Potential BC Break by removing Symfony\Component\Form\Tests\Extension\Validator\Type\TypeTestCase after updating from Symfony 3.3 to 3.4

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony#25358]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | maybe?
| RFC?             | no
| Symfony version  | 3.4.1

Hi,

To test our own `FormType` we extended the class `TypeTestCase` which is in the namespace `Symfony\Component\Form\Tests\Extension\Validator\Type`

I just upgraded my Symfony 3.3 projects to Symfony 3.4 and all tests extending this class are now failing, however the [UPGRADE-3.4.md](https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.4.md) doesn't state anywhere that this class has been removed. But I saw the [CHANGELOG.md](https://github.com/symfony/symfony/blob/3.4/CHANGELOG-3.4.md) containing this information

> feature #21960 Remove Validator\TypeTestCase and add validator logic to base TypeTestCase (pierredup)

Link to the issue: https://github.com/symfony/symfony/pull/21960

Now I see no mentioning of having the `TypeTestCase` in the namespace `Symfony\Component\Form\Tests\Extension\Validator\Type`, so I don't know if this class should've been used outside of Symfony anyway, but it's not marked `internal` or anything, so I think we were safe to use this class.

Now, in my opinion this would be a BC break, but before creating a PR etc. I wanted to ask the members of the Symfony community if you see it the same way.

**Comment by iltar** [comment]
If you look carefully, you see the `Tests` namespace, which are the tests for Symfony, not an extension point. See #22064 for a related issue.

**Comment by tzfrs** [comment]
@iltar Ah, I see... The new class has `Symfony\Component\Form\Test` namespace, so Symfony differs between `Tests` and `Test`?

**Comment by xabbuh** [comment]
`Tests` is the namespace that contains the Symfony test suite. And indeed we do not apply the BC promise to our test suite.
