### ISSUE TITLE
[RFC][Translation] Fallback Locales interface?

### ISSUE THREAD

**Issue by Warxcell** [symfony/symfony#25356]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | maybe, depends
| RFC?             | yes
| Symfony version  | *

You do plan of having some kind of interface for `setFallbackLocales` and `getFallbackLocales`?
I have written software which translates entities/objects and it's using Symfony's Translator to get current locale and fallback locales transparently, instead of having own configuration.

I have to check for existence of methods with `method_exists($translator, 'getFallbackLocales')` - and I don't like that. :)

**Comment by nicolas-grekas** [comment]
Closing in favor of #28579
