### ISSUE TITLE
Outdated documentation because of new Flex tool

### ISSUE THREAD

**Issue by mariopr25** [symfony/symfony#25365]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >3.x (since Symfony uses Flex tool)

I think your documentation isn't updated for symfony 3.x and 4.x because new Flex tool (I saw it trying to upgrade from a project, using Flex, from Symfony 4.0.0 to 4.0.1). 

In section 
"_Upgrading a Patch Version (e.g. 3.3.2 to 3.3.3)_" for symfony version 4.0 it tells that the command to upgrade is: 
`composer update symfony/symfony`
but in a Symfony project created with Flex (`composer create-project symfony/skeleton my-project`), the default method from version 4.0, there isn't any symfony/symfony package, so for upgrading in that case the command must to be (at least i think so):
`composer update`
or maybe:
`composer update symfony/framework-bundle`
So, perhaps you must add an subsection "_Upgrading projects using Flex_" (or something so) in documentation for 3.x and 4.x (or better, add it in documentation for 3.x versions and replace actual documentation for 4.x with this, since Flex is the default install method in that version, and add an "Upgrading a project created without Flex" subsection).

Also the old install method (without Flex) is still available in Symfony 4.x:
`composer create-project symfony/framework-standard-edition my_project "4.0"`
whose result is similar to upgrading from version 3.x to 4.0, and there is nothing about it in your 4.x version documentation.

And finally, if i start a new project version 3.x with, for example:
`composer create-project symfony/framework-standard-edition my_project "3.4"`
and try to update to version 4.0.1 following the instructions of the subsection _2) Update to the New Major Version via Composer_ from _Upgrading a Major Version (e.g. 3.4.0 to 4.0.0)_ [go to this documentation section](https://symfony.com/doc/current/setup/upgrade_major.html#update-to-the-new-major-version-via-composer)
Neither 
`composer update symfony/symfony`
nor
`composer update symfony/symfony --with-dependencies`
do the work, only:
`composer update`
works rightly. In the other cases i get those messages:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install symfony/symfony v4.0.1
>     - sensio/generator-bundle v3.1.6 requires symfony/yaml ~2.7|~3.0 -> satisfiable by symfony/symfony[v3.4.1], symfony/yaml[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1].
>     - sensio/generator-bundle v3.1.6 requires symfony/yaml ~2.7|~3.0 -> satisfiable by symfony/symfony[v3.4.1], symfony/yaml[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1].
>     - sensio/generator-bundle v3.1.6 requires symfony/yaml ~2.7|~3.0 -> satisfiable by symfony/symfony[v3.4.1], symfony/yaml[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1].
>     - Can only install one of: symfony/symfony[v4.0.0, v3.4.1].
>     - don't install symfony/yaml v2.7.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.10|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.11|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.12|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.13|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.14|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.15|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.16|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.17|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.18|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.19|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.20|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.21|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.22|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.23|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.24|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.25|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.26|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.27|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.28|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.29|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.30|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.31|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.32|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.33|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.34|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.35|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.36|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.37|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.38|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.39|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.7.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.10|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.11|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.12|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.13|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.14|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.15|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.16|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.17|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.18|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.19|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.20|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.21|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.22|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.23|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.24|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.25|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.26|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.27|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.28|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.29|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.30|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.31|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.32|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v2.8.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.0.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.10|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.1.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.10|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.11|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.12|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.13|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.14|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.2.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.1|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.10|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.11|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.12|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.13|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.14|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.2|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.3|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.4|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.5|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.6|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.7|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.8|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.3.9|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.4.0|don't install symfony/symfony v4.0.0
>     - don't install symfony/yaml v3.4.1|don't install symfony/symfony v4.0.0
>     - Installation request for symfony/symfony ^4.0 -> satisfiable by symfony/symfony[v4.0.0, v4.0.1].
>     - Installation request for sensio/generator-bundle (locked at v3.1.6) -> satisfiable by sensio/generator-bundle[v3.1.6].

this is my composer.json file:

```
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": { "Tests\\": "tests/" },
        "files": [ "vendor/symfony/symfony/src/symfony/Component/VarDumper/Resources/functions/dump.php" ]
    },
    "require": {
        "symfony/symfony": "^4.0"
    },
    "require-dev": {
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "platform": {
            "php": "7.1.11"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.4-dev"
        }
    }
}
```

I have deleted all the lines in require and require-dev sections but the "symfony/symfony" one and edited config/platform/php section
I don't know if i'm doing something wrong or there is an error in documentation or in Symfony's dependencies.

So summarizing, i think you need:
- Add a "Upgrading projects using Flex" subsection in documentation to upgrade for Symfony 3.x versions:

> Upgrading a Major Version (e.g. 3.4.0 to 4.0.0)

> Upgrading a Minor Version (e.g. 3.3.3 to 3.4.0)

> Upgrading a Patch Version (e.g. 3.3.2 to 3.3.3)

- Add an "Installing whitout Flex" subsection in documentation to install for Symfony 4.x versions: 
Installing & Setting up the Symfony Framework
- Replace upgrade documentation for Symfony 4.x versions to the new default method, Flex (so no "composer update symfony/symfony" command in that subsection)
- Add an "Upgrading projects using Flex" subsection in documentation to upgrade for Symfony 4.x versions
- Perhaps, correct section "Upgrading a Major Version (e.g. 3.4.0 to 4.0.0)" or whatever is wrong with this upgrade process if something.

I hope have explain it correctly, there are some information about Flex that don't appear in the documentation or it's wrong and i think it should be corrected. In version 3.x Flex isn't the default method, so it's an secondary data, but in version 4.x it is, so it is a main data and the information about the old method is the secondary data. But Both of them should appear in the documentation. Of course the structure not must to be the one i suggest, it's only an idea

**Comment by Tobion** [comment]
Please open this issue on https://github.com/symfony/symfony-docs instead
