### ISSUE TITLE
[RFC] fabbot feature request.

### ISSUE THREAD

**Issue by Simperfit** [symfony/symfony#25360]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | fabbot

There are two things that could be nice to have in fabbot : 
- a copy button
- curl patch | git commit (the files) -m 'fabbot'

That would be handy since it will be faster then now when you have to click, select, copy then past, then commit, then rebase ;).

**Comment by nicolas-grekas** [comment]
Isn't the provided "curl" command enough?

**Comment by Simperfit** [comment]
I guess it could be enough but a copy button could be really handy.

**Comment by lyrixx** [comment]
And also a curl command to is able to apply *all* patches at once

**Comment by Simperfit** [comment]
I meant by the copy button, directly copy the curl command, not the patch.
To be able to go faster with it.

2017-12-06 15:46 GMT+01:00 Grégoire Pineau <notifications@github.com>:

**Comment by javiereguiluz** [comment]
Adding such a button is not trivial because even with the JavaScript clipboard support, there's still permission issues in some browsers. Let's keep using the always-working text select + copy and let's focus our resources on bigger features. Thanks!
