### ISSUE TITLE
how to update symfony

### ISSUE THREAD

**Issue by benyang2015** [symfony/symfony#25374]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

WANT TO UPDATE TO 3.3.14,use composer update symfony/symfony:3.3.14,can't work,it update to 3.4.1,how can I do?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
