### ISSUE TITLE
The form problem

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#25372]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | 
| RFC?             | 
| Symfony version  | >=3.3.10 ？

        $formData = (object)[
            'value1' => (new Entity),
            'value2' => null
            .......
        ];
        $form = $this->createForm('TheFormType', $formData);
        $form->handleRequest($request);
        if ($form->isValid() && $form->isSubmitted()) {
                 dump($formData);
         }

Hi,
Before the update, my project is running normally.
Since I upgraded to symfony 3.3.10，the $formData return empty value.

**Comment by dkozickis** [comment]
Second that. Trying to trace an issue. For whatever reason after handleRequest my Entity has one of the fields as null. Trying to swap around order of entity parameters in Form - parameter in some position ([2] in my case) gets the null

**Comment by xabbuh** [comment]
I am sorry, but without further information we won't be able to help you. We would at least need a description of steps that one must perform to reproduce the issue (best would be a project one could just check out).

**Comment by Simperfit** [comment]
Could you do the following, so we could get a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html
