### ISSUE TITLE
how to Solve password_verify response time too long

### ISSUE THREAD

**Issue by spectrelb** [symfony/symfony#25387]
I use  BCryptPasswordEncoder.php generate password , When I implement the login api , i find  response time too long , The reasons are as follows：

    /**
     * {@inheritdoc}
     */
    public function isPasswordValid($encoded, $raw, $salt)
    {
        return !$this->isPasswordTooLong($raw) && password_verify($raw, $encoded);
    }

i find password_verify response time too long,  500ms ！！！
I don't know why, I hope to help me

**Comment by noniagriconomie** [comment]
Hi, with a cost of 15, no problem on all of my projects
php 7.1
are you sure it is this method ?

**Comment by curry684** [comment]
500ms is pretty normal and acceptable in general. You are aware password hashing is supposed to be slow?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
