### ISSUE TITLE
Cookie-Names are prefixed with "Set-Cookie:" by AbstractSessionHandler::destroy

### ISSUE THREAD

**Issue by pableu** [symfony/symfony#25393]
When creating cookies using setcookie() whilst having a session started, our own cookies are prefixed by "Set-Cookie". 

I think the issue becomes quite obvious by reading AbstractSessionHandler::destroy: 
https://github.com/symfony/symfony/blob/ecf54d5aa06cc3e26bfa554cd3dac70cc07dea1f/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php#L159

In line 143, all headers that *don't* start with "Set-Cookie:" are skipped. Then in Lines 150 and 153, they are added to `$otherCookies`.

In line 159, they are prefixed again with "Set-Cookie:" and passed to `header()`. This results in headers such as `Set-Cookie: Set-Cookie: test=foo; path=/`.

I think the correct solution would be to change line 159 to `header($h, false);`.

Symfony Version: 3.4.1
PHP-Version: 7.0.22
OS: Ubuntu 16.04

Some Screenshots from the Chrome Devtools: 
Headers:
![headers](https://user-images.githubusercontent.com/305859/33765389-ea6b5558-dc18-11e7-91cb-0c2044e14873.png)
Cookies: ![cookies](https://user-images.githubusercontent.com/305859/33765402-f397cbc0-dc18-11e7-9253-0d633644bb95.png)

**Comment by Simperfit** [comment]
Do you want to provide the Pull Request ?

**Comment by pableu** [comment]
Does #25398 work?

**Comment by nicolas-grekas** [comment]
Perfectly, thank's for it, and congrats for your first PR!

**Comment by Simperfit** [comment]
Congrats for the first PR !

**Comment by pableu** [comment]
Great! Thanks for accepting it so quickly :-)
