### ISSUE TITLE
Old default value

### ISSUE THREAD

**Issue by PatrickLEBON974** [symfony/symfony#25390]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

Hi,
it's just a little missing thing in the v4, for the HttpFoundation component, in the request.php line.315,
the default HTTP_USER_AGENT is still 'Symfony/3.X'

**Comment by javiereguiluz** [comment]
Closing as fixed by #25392.
