### ISSUE TITLE
[Validator] Bad path starting with 'data'

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#25401]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.1

When using the validator with `@Callback()` annotation, there is an issue with path being preprended by `data.`.

```php
<?php

class DTO
{
    /**
     * @Constraints\Callback()
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        $context
            ->buildViolation('Error message')
            ->atPath('children[attribute]')
            ->addViolation();
    }
}
```

The error is displayed at top-level since it is attached to the root form. It seems to come from the path that is prepended by `data.`:

In profiler, validator pane:

Path | Message | Invalid value | Violation
-- | -- | -- | --
data.children[attribute] | Error message | DTO | ConstraintViolation

While it should be in order to work:

Path | Message | Invalid value | Violation
-- | -- | -- | --
children[attribute] | Error message | DTO | ConstraintViolation

A quick fix consist in adding the following lines at the begining of the callback:

```php
$context->setNode($context->getValue(), $context->getObject(), $context->getMetadata(), '');
```

The `data` path seems to be added here:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php#L52

**Comment by Vinorcola** [comment]
Other remarks:

It seems the documentation is out of date since the path convention as changed.
https://symfony.com/doc/current/reference/constraints/Callback.html#the-callback-method
The path is no longer the attribute names, but `children[attributeName]` in order to work.

**Comment by xabbuh** [comment]
Can you create an example project that allows to reproduce your issue? The `data` part of the property path is coming from the form validator so with a quick glance this looks expected to me.

**Comment by Simperfit** [comment]
Could you do the following, so we could get a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by Vinorcola** [comment]
Unfortunatelly, starting from a new project does not reproduce...
I will try to understand why in this specific project it work differently.

**Comment by xabbuh** [comment]
Thank you for the response. Let's close for now then. We can reconsider this decision when more details pop up.

**Comment by Vinorcola** [comment]
Ok, I've been able to reproduce: https://github.com/Vinorcola/sf-form-validation-bug
Load the home page and submit the form.

I've added some javascript to auto trigger an error: https://github.com/Vinorcola/sf-form-validation-bug/blob/master/templates/Main/home.html.twig#L68-L70
This will alter a choide value and trigger an invalid value from the ChoiceType.

This gave me the tips on how the validation path is built. And in order for my Callback validation to display properly, I have to add the following lines: https://github.com/Vinorcola/sf-form-validation-bug/blob/master/src/FormDTO/MappingDTO.php#L26-L31
Otherwise, it is preprended by `data.` and doesn't work.

**Comment by xabbuh** [comment]
This is the expected behaviour when the validation process is triggered by the Form component. Otherwise, the errors couldn't be properly mapped in the form. Thus, I am going to close here.

**Comment by xabbuh** [comment]
@Vinorcola I had a more detailed look at your reproducer app and doing this little change makes it work as you expect:

```php
    public function validate(ExecutionContextInterface $context, $payload)
    {
        $usedColumns = [];
        foreach ($this->contextMapping as $contextId => $dto) {
            if ($dto->columnName && key_exists($dto->columnName, $usedColumns)) {
                $context
                    ->buildViolation(
                        'The column "' . $dto->columnName . '" is already used for ' .
                        $usedColumns[$dto->columnName]['type'] . ' "' .
                        $usedColumns[$dto->columnName]['title'] . '".'
                    )
                    ->atPath('contextMapping[' . $contextId . '].columnName')
                    ->addViolation();
            } else {
                $usedColumns[$dto->columnName] = [
                    'type'  => 'context',
                    'title' => $dto->title,
                ];
            }
        }
        foreach ($this->filterMapping as $filterId => $dto) {
            if ($dto->columnName && key_exists($dto->columnName, $usedColumns)) {
                $context
                    ->buildViolation(
                        'The column "' . $dto->columnName . '" is already used for ' .
                        $usedColumns[$dto->columnName]['type'] . ' ' .
                        $usedColumns[$dto->columnName]['title'] . '.'
                    )
                    ->atPath('filterMapping[' . $filterId . '].columnName')
                    ->addViolation();
            } else {
                $usedColumns[$dto->columnName] = [
                    'type'  => 'filter',
                    'title' => $dto->title,
                ];
            }
        }
    }
```

When specifying the property paths where to attach the violations, you need to think of this from the model's POV. The `children` path part is only present later in the form. However, this will then be mapped properly by the Form component's `ViolationMapper` class (it compares the property paths configured in the form types with the property paths given here in your violations).
