### ISSUE TITLE
Command for generating login and register.

### ISSUE THREAD

**Issue by fiher** [symfony/symfony#25406]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.1

First off - Thank you for developing and managing Symfony! This is my first ever contribution after using symfony for more than a year.

At the beginning of my experience with Symfony and currently after the new version I have been creating lots of small projects to test new stuff and play with the framework. I have always found it really annoying that I have to do the same login and register. First I create my User entity and then I edit routes.yml, security.yml and so on...I suppose that you are familiar with the procedure but if not here is the documentation [Login Form]( https://symfony.com/doc/current/security/form_login_setup.html) and [Register form](http://symfony.com/doc/current/doctrine/registration_form.html).

I have always found it annoying that the register documentation uses `RegisterController` and login documentation uses `SecurityController` , but this is not what I am talking about here.

Could there be any command to be executed that does this? The reason behind this is that it is really repetitive work which is always the same (unless some really really specific occasion arrives) and it is mostly magic. In the documentation its not really explained how it works and you have to figure it out by yourself by looking at the stack trace and debugging. Which means that for new programmers like myself there isn't really a point of doing it each time and we do it really often because we train and make demo projects all the time.

**Requirements for the project in order to run the command**
  - Having symfony project structure
  - Having entity which extends `UserInterface`

**Options to the command**
  - **algorithm**: The algorithm used. Default is bcrypt
  - **withsalt**: Defines that you want your algorithm to use salt (if it uses salt)
  - **register path**: The route to be used for login.Default is "/register"
  - **login path**: The route to be used for login. Default is "/login"
  - **check path**: The route to be used for check login. Default is "/login"
  - **entity**: The entity to be used for login and register. Must implement `UserInterface`. Default looking for `User`

The idea is that the code needed is already in the documentation from the twig to the controller and configuration. It just needs to be auto generated rather than copy pasted every time.

It doesn't seem as much work to be implemented since the code needed is already in the documentation and I would love to give it a try, but I have never contributed to a framework before or any project of such scale. If there is anyone good enough to guide me I would love to contribute to Symfony and if it goes well implement other features as well. Currently I can't seem to find an entry point for such function to be implemented. I know how to write to files and create files and such, but I don't know where should I write my function and how to properly check if the project structure is valid. If anyone is willing to help me for my first contribution to this project I would be more than happy to continue contributing. If not - I hope the community likes the idea and implements it so that I can use it.

**Comment by iltar** [comment]
This sounds pretty much like the [FOS User Bundle](https://symfony.com/doc/current/bundles/FOSUserBundle/index.html).

However, if you wish to create some sort of a generator, I would highly advice to make the generated code follow good practices, thus [not having an entity implement the UserInterface](https://stovepipe.systems/post/decoupling-your-security-user).

**Comment by fiher** [comment]
@iltar Thank you for this article. I indeed didn't know that implementing the UserInterface is a bad practice. As for FOSUserBundle - You don't really generate login and register...you just download them with the bundle. The one thing I dislike about FOSUserBundle is that to a new user it looks like magic. It looks like magic anyway, but with FOSUserBundle it is even more so.

My idea with the generated login and register is to make Symfony more....user friendly. With auto generated code there is no need to hide anything which will make Symfony easier to understand.

**Comment by javiereguiluz** [comment]
> I indeed didn't know that implementing the UserInterface is a bad practice

It's not a bad practice. Iltar thinks so ... and others agree ... but some others disagree.

In any case, I like your comments a lot. Recently we [introduced a new Symfony Maker Bundle](https://symfony.com/blog/introducing-the-symfony-maker-bundle) where we are creating commands that generate boilerplate code. One of our TODO things is to add commands that simplify the security part of Symfony apps. For example: https://github.com/symfony/maker-bundle/pull/41

So, I'm closing this issue because we can't fix it in Symfony core repository, but please add your comments and ideas in the MakerBundle repository to help us fix this problem. Thanks!
