### ISSUE TITLE
Symfony/Lock doesn't work as expected

### ISSUE THREAD

**Issue by glensc** [symfony/symfony#25418]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.4.1

so, great, i discovered this component:
- https://symfony.com/blog/new-in-symfony-3-3-lock-component
- [symfony/lock](https://symfony.com/doc/3.4/components/lock.html) seems to have timeout support, and blocking/non-blocking mode

however flock doesn't seem to work as i expect:
1. with ttl set and blocking mode too, it would still be blocked until lock is held by other process, exceeding the ttl. i would expect `LockConflictedException` or `LockAcquiringException` being thrown when timeout is reached, with ttl 10 i wait for 60 seconds and no exception being thrown.
2. <del>with non-blocking mode, i would expect to be thrown `LockConflictedException` or `LockAcquiringException` when lock is acquired by another process, but `acquire()` returns immediately even if the lock is not acquired, and as the method is `void` can't even tell if the lock acquire was failure.</del>: EDIT: the `acquire` is returns `bool`, not `void`.

I created gist demonstrating this https://gist.github.com/glensc/95d0c8964d4ab5d28145dc8cf905a3fd

**Comment by glensc** [comment]
I created gist demonstrating this https://gist.github.com/glensc/95d0c8964d4ab5d28145dc8cf905a3fd:

1. test with blocking mode, ttl 3 seconds. i'd expect second and third process locked at most 3 seconds, and. or at least throw if wait time was exceeded. reality: 2nd waits for x seconds, 3rd waits for y seconds, no exception thrown.
```
➔ ./locker.php 1 3 10 & ./locker.php 1 3 10 & ./locker.php 1 3 10 &
[1] 11075
[2] 11076
[3] 11077
[11075] starting up, ttl=3.00s, blocking=true, sleep=10s
[11075] Waited 0.005921 seconds for lock
[11075] Sleeping 10 seconds
[11076] starting up, ttl=3.00s, blocking=true, sleep=10s
[11077] starting up, ttl=3.00s, blocking=true, sleep=10s

[11075] Sleeped 10 seconds
[11077] Waited 9.951352 seconds for lock
[11077] Sleeping 10 seconds
[11077] Sleeped 10 seconds
[11076] Waited 19.982807 seconds for lock
[11076] Sleeping 10 seconds
[11076] Sleeped 10 seconds
```

**Comment by glensc** [comment]
2. test with non-blocking mode. i would expect first one take the lock, second and third one get exception or return false. exception is not thrown, and method can't return false because by api it's declared void. this effectively makes non-blocking mode destructive, because lock is given even if acquiring it really did not succeed.

```
➔ ./locker.php 0 3 10 & ./locker.php 0 3 10 & ./locker.php 0 3 10 &
[1] 17953
[2] 17954
[3] 17955
[17953] starting up, ttl=3.00s, blocking=false, sleep=10s
[17953] Waited 0.002588 seconds for lock
[17953] Sleeping 10 seconds
[17955] starting up, ttl=3.00s, blocking=false, sleep=10s
[17955] Waited 0.007147 seconds for lock
[17955] Sleeping 10 seconds
[17954] starting up, ttl=3.00s, blocking=false, sleep=10s
[17954] Waited 0.003118 seconds for lock
[17954] Sleeping 10 seconds

[17953] Sleeped 10 seconds
[17955] Sleeped 10 seconds
[17954] Sleeped 10 seconds


```

**Comment by nicolas-grekas** [comment]
Ping @jderusse

**Comment by jderusse** [comment]
Hello @glensc 

Thank for the feedback, I'll try ot help you. But first, there are some misconception in the bellow statments:

The biggest one, is that flock does not supports TTL: TTL is a mechanism dedicated to expiring lock (see http://symfony.com/doc/3.4/components/lock.html#expiring-locks) and flock is not expirable (see the comparison table https://github.com/symfony/symfony-docs/blob/3.4/components/lock.rst#available-stores). 

The second, is the method `acquire` does not throws any exception (design choice), but returns a boolean to tell you if the lock is acquired or not. See a sample of code in http://symfony.com/doc/3.4/components/lock.html#usage. And https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/LockInterface.php#L31 for the interface definition.

Those 2 tips should explains your results: 
- With blocking mode, your locks were released at the end of the process (after the 10 sec sleep) and explain why Locker 2 waited 10 seconds and Locker waited 20 seconds
- Without blocking mode nor a test on `if ($lock->acquire())` every lockers enter in the code at the same time.

**Comment by glensc** [comment]
ok, i see, no real solution available.

you may wish to look discussion of similar problem in other project: https://github.com/malkusch/lock/issues/6

**Comment by jderusse** [comment]
If you need to define a blocking timeout, I suggest to implement a loop until you acquire the lock or timeout is reached.

```
$start = microtime(true);
while (!lock->acquire(false)) {
  if (microtime(true) - $start > $timeout) {
    return false;
  }

  usleep(100000);
}

return true;
```
