### ISSUE TITLE
RuntimeException | Stream Socket: Broken pipe 

### ISSUE THREAD

**Issue by unckleg** [symfony/symfony#25411]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Assigning value of Symfony\Component\HttpFoundation\File()  to entity file property leads to partial rendered view and bad exception printing on the same.

`$entity->setPhoto(new File(null, false));`

**Comment by javiereguiluz** [comment]
@unckleg thanks for reporting this issue. However, to be able to help you, we need some code able to reproduce this bug. Here you can find more information about this: https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by Simperfit** [comment]
@unckleg Could you please do what @javiereguiluz suggested ?

**Comment by unckleg** [comment]
I will in two days.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by rahulpanteon** [comment]
I got the same issue here. It shows validation with partial exception. 
When I tried to upload big image, I got this.
   ```
 /**
     * @var string
     * @ORM\Column(name="picture", type="text", nullable=true)
     * @Assert\File(
     *     maxSize = "10M",
     *     mimeTypes = {"image/gif", "image/png", "image/jpg", "image/jpeg"},
     * )
     */
    private $picture;
```
`"data.picture":"The file is too large. Allowed maximum size is 2 MiB.
`
```
(1/1) RuntimeException
stream_socket_sendto(): Broken pipe

```
See the max size is also wrong. I provided 10M and it gives me 2 MiB
