### ISSUE TITLE
[DX][Console] Improve error message when the parent constructor is not called

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#25423]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

If you add a constructor in your command and forget to add the `parent::__construct()` call, you'll end up with this misleading error:

```
There are no commands defined in the "app" namespace.
```

This was not a very important issue in the past, but now that adding a constructor is the recommended way to inject services, we're starting to get issue reports about this (e.g. https://github.com/symfony/symfony-docs/issues/8843#issuecomment-349955835).

Could we detect this issue and change the error message to tell the user that they must add the `parent::__construct()` call?

**Comment by iltar** [comment]
That's probably because the `configure()` must be called and this is done via the constructor. Instead of telling the developer to add an extra call to the parent constructor, would it be possible to somehow call this configure in a static context? This would allow even lazier commands in certain conditions. I'm not sure if the current proposal is easy to detect.

Ideally I'd not see the parent class at all, just like I can do with controllers. I would like to see a form of composition over inheritance here to solve this issue.
```php
final class MyCommand implements CommandInterface
{
    public static function configure(CommandConfiguratorInterface $config)
    {
        $config->setName('foo:bar');
        $config->setDescription('...');
        $config->addArgument('some-argument');
    }
    
    function execute(InputInterface $input, OutputInterface $output)
    {
        // do something awesome
    }
}
```

Could be solved by simply wrapping this inside an instance of the current Command class.

**Comment by nicolas-grekas** [comment]
@iltar the issue is that any static is out of any service layer. I know that some projects do fetch configuration of their commands via a DB call. And that's fine. So, "object oriented" is a requirement here.

**Comment by iltar** [comment]
Both methods could be supported, my proposal would be merely feeding the actual command class with information, which can be cached during container building and would thus make them very lazy. As the current situation is still possible, it wouldn't make an existing solutions impossible to build. 

```php

final class CommandWrapper extends Command
{
    public function __construct(CommandInterface $command, CommandMetadata $metadata)
    {
        // ...
    }

    protected function configure()
    {
        // use the CommandMetadata to configure $this
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $this->command->execute($input, $output);
    }
}

```

**Comment by nicolas-grekas** [comment]
I just create a command with the maker bundle, added a constructor that didn't call the parent, and this is the message I'm seeing:

>Command class "App\Command\AppBraveKangarooCommand" is not correctly initialized. You probably forgot to call the parent constructor.  

Looks perfect to me, nothing to do here. What did I miss?

**Comment by chalasr** [comment]
Can we close? I can't reproduce either
