### ISSUE TITLE
getAllKeys for Memcached

### ISSUE THREAD

**Issue by tobiasehlert** [symfony/symfony#25424]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x

Somehow, I can't use `getAllKeys()` functionality, as it exists in normal PHP.

How I've made a workaround my connecting to memcached over a separate php file, but would be nice to be able to retrieve all keys somehow.

Could that be implemented? :)

**Comment by dmaicher** [comment]
Can you elaborate where exactly you want this functionality to be available?

**Comment by tobiasehlert** [comment]
Hi @dmaicher,

Yes, the reason for this that I don't keep a record on which keys I have in memcached. The thing I want to get out from this is that I want to be able to see which those are, since I use mostly use TTL keys over a pretty short period of time.
That is basically it :)

Regards,
Tobias

**Comment by dmaicher** [comment]
Sorry still very unclear **where** this functionality should be added. Are you talking about `MemcachedAdapter`?

**Comment by nicolas-grekas** [comment]
Assuming this is for the Cache component (please be more explicit in your reports @tobiasehlert ...):
you can already call getAllKeys if you get access to the connection object. Doing so is possible by e.g. manually creating it, then injecting it to the constructor of your cache adapter.

Note that fetching all keys is not a recommended practice because it doesn't scale.

**Comment by tobiasehlert** [comment]
@dmaicher as of today, I can do this:
```
$cache = new Memcached();
$cache->addServer( 'localhost', 11211 ) or error_log( "Memcached: could not connect!" );
print_r( $cache->getAllKeys() );
```
But I would like to run this:
```
$memcached = new Memcached();
$memcached->addServer( 'localhost', 11211 ) or error_log( "Memcached: could not connect!" );
$cache= new Symfony\Component\Cache\Adapter\MemcachedAdapter( $memcached );
print_r( $cache->getAllKeys() );
```
Well, I could rewrite a little of this and remove the adapter stuff and choose to run the query directly. But I like to use the isHit() function to see if I got a hit. I could possibly create my own, but thought extending the current tool with a new function would be nice.

In addition, this is in purpose of a status page only @nicolas-grekas, so nothing that is supposed to be scaling anyhow.

Regards,
Tobias

**Comment by nicolas-grekas** [comment]
You can and should both objects at once. I don't think we should have getAllKeys in core.

**Comment by tobiasehlert** [comment]
Alright, so basically, when removing the symfony adapter stuff, I can like run all my stuff I want. But with it, I can't do everything. I guess then I got no more extra use, except for the isHit function? :)

**Comment by nicolas-grekas** [comment]
When using the adapter, you gain all the properties of PSR 6. That is: abstraction over the actually data storage, accurate error handling, etc.
As said before, you can use both objects at once if you need Memcached specific features and generic ones at the same time.
Closing as there is no issue to track here.
