### ISSUE TITLE
[Symfony 4] Where is the 'Method' annotation for controllers endpoints?

### ISSUE THREAD

**Issue by din-gi** [symfony/symfony#25435]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

Hello,
I am trying to upgrade to Symfony 4,
Having some issues..

One of them is to understand where did the Method annotation go?

I have the following code:
```
namespace ListerBundle\Controller;

use \CoreBundle\Controller\AuthenticatedController;
use \CoreBundle\ResponseGenerator;
use CoreBundle\Dto\BaseDto;
use \ListerBundle\Service\ListerService;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class ListerController extends AuthenticatedController
{
	/**
	 * @Route("/lister", name="viewListerPage")
	 * @Method({"GET"})
	 *
	 * Example: /lister
	 *
	 * @param Request $request The Symfony request object
	 *
	 * @return \Symfony\Component\HttpFoundation\Response The output
	 */
	public function viewListerPageAction(Request $request)
	{
		return $this->renderApp();
	}
}
```

Now `Route` and `Method` annotatation classes used to be:
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
```

I found Route annotation but can't find Method annotation

Where is it?
Thanks

**Comment by din-gi** [comment]
so I found out that instead of:
```
* @Route("/finder", name="viewFinderPage")
* @Method({"GET"})
```

On Symfony 4 it needs to be:
```
* @Route("/finder", name="viewFinderPage", methods={"GET"})
```

Nothing stated in the docs regarding this change to the annotations..

**Comment by iltar** [comment]
The annotations are from the Framework Extra Bundle, not the Symfony core.

**Comment by din-gi** [comment]
So what I notated isn't valid? and I should install the FrameworkExtraBundle?

**Comment by iltar** [comment]
If you wish to use the `@Method` annotation, yes. But you can also see in the namespace that it doesn't come from Symfony.

**Comment by din-gi** [comment]
Yes I know.. but is the Route annotation from `Symfony\Component\Routing\Annotation\Route` won't suffice for limiting the Method of the controller as well?

Thanks

**Comment by iltar** [comment]
These 2 route annotations are identical for routing purposes. The only additional feature the bundle one gives, is a service definition on controller level (but obsolete as of sf 3.3).

**Comment by din-gi** [comment]
Got it..

Thank you very much my man!

**Comment by andriamasy** [comment]
@Route("/show/{id}", methods={"GET","HEAD"})
