### ISSUE TITLE
[Routing] BC break on the annotated route loading

### ISSUE THREAD

**Issue by mRoca** [symfony/symfony#25436]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.14

Hello, while updating a `3.3.13` project to `3.3.14`, I've an issue with the following routing declaration:
```yaml
my_route:
    resource: 'Foo\BarBundle\Controller\UserController'
    type: annotation
    prefix: /
```

The error is : 
```
FileLocatorFileNotFoundException
The file "Foo\BarBundle\Controller\UserController" does not exist (in: /srv/app/app/config, /srv/app/app, /srv/app/app/Resources) in Foo\BarBundle\Controller\UserController (which is being imported from "/srv/app/app/config/routing.yml"). Make sure annotations are enabled.
```

The problem :
The `AnnotatedRouteControllerLoader` is called after the `AnnotationDirectoryLoader` one, and both can support the `(string, 'annotation')` routing entry.

It seems it's caused by the merge of https://github.com/symfony/symfony/pull/25113 in the `3.3` branch. This problem can be fixed by https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/537 , but the commit is only available for the `5.1.3` SensioFrameworkExtraBundle version, whereas the `3.3` symfony branch only requires `"sensio/framework-extra-bundle": "^3.0.2"`.

Another PR, the https://github.com/symfony/symfony/pull/25231 one, can fix the problem but has been rejected in favor of the SensioFrameworkExtraBundle one.

**Comment by xabbuh** [comment]
Can't you update to SensioFrameworkExtraBundle 5?

**Comment by mRoca** [comment]
I can also update my routing file by using the `resource: '@FooBarBundle/Controller/UserController.php'` format, and it's what I did : it works without problem.

I've created the issue to track the bug : indeed we can also update to SensioFrameworkExtraBundle 5, but as there are at least 2 bc breaks between the 3 and the 5 version, there is still a potential bc break problem for other sf3.3 users.

**Comment by xabbuh** [comment]
I am not completely sure how @fabpot wants to handle releases for FrameworkExtraBundle before 5. But IMO that would be the only way to entirely fix it.

**Comment by fabpot** [comment]
I'm more than willing to merge a pull request that would fix version 3 and 4 of FrameworkExtraBundle.

**Comment by dmaicher** [comment]
@fabpot I created a PR for backporting the fix from 5 to 3: https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/543

There seems to be no branch for version 4 though?

**Comment by fabpot** [comment]
v3.0.29 is out with the fix. Version 4.0 is not supported as it was a short-lived version, so one should jump from 3 to 5 directly.
