### ISSUE TITLE
[Form] UniqueEntity constraint fails on a EntityType field

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#25437]
I am encountering an issue with the validation of a form which fails on a `UniqueEntity` constraint attached to an `EntityType` field.

Why is a `UniqueEntity` constraint failing on an `EntityType` since it is a field used to select existing entities? (not to create an entity)

On my example, `members` field is an array, not an entity.
The `UniqueEntity` error message is displayed on each `member` field of the collection.

``` php
class ParentFormType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('members', CollectionType::class, [
                'entry_type'   => ChildFormType::class,
                'allow_add'    => true,
                'allow_delete' => true,
                'by_reference' => false,
            ])
        ;
    }
}
```

``` php
class ChildFormType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('user', EntityType::class, [
                'class'         => User::class,
                'choice_label'  => 'name',
                'constraints'   => [new Assert\NotBlank()],
            ])

            ->add('role', ChoiceType::class, [
                'choices' => [
                    'Membre'  => 'member',
                    'Manager' => 'manager',
                ],
                'constraints' => [new Assert\NotBlank()],
            ])

        ;
    }
}
```

**Comment by xabbuh** [comment]
I am not sure I follow what you are trying to achieve. Would you mind to create a small example project that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
