### ISSUE TITLE
[HttpFoundation] BC break for Cache-Control headers

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#25448]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.1

Today I deployed an upgrade of my biggest app from symfony 3.3 to 3.4.1. So far so good but unfortunately there seems to be a BC break regarding some `Cache-Control` headers that are being sent now for some reason once a session is started.

This seems to be caused by this line https://github.com/symfony/symfony/pull/24878/files#diff-d29419a0d7043fce54a98005c26a82aaR36

I have some responses that are cached publicly in Varnish using some cache control headers being added to the response in the controller action:

```
    "cache-control" => array:1 [
      0 => "public, s-maxage=3600"
    ]
```

Those headers are now unfortunately useless and the final headers being received from the backend by Varnish are:

```
Cache-Control: max-age=0, private, must-revalidate, public, s-maxage=3600
```

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
The description is correct. If you want to opt-out from sending the header, you need to set the        `'cache_limiter'` option to `'0'`.
BUT: what's the meaning of "public" when a page has been using the session to be generated? How can it be public anymore?

**Comment by dmaicher** [comment]
Shouldn't this be opt-in then for BC reasons? I will try setting `cache_limiter`.

I would have to debug where and why a session is started for those pages actually. Seems weird indeed but nevertheless the Cache-Control headers are correct and should be effective.

**Comment by nicolas-grekas** [comment]
The behavior change is a bug fix actually...

**Comment by dmaicher** [comment]
Hmm ok.

Is there any easier way of setting that option? Seems its not supported on `framework.session.cache_limiter`. The value of `session.cache_limiter` from php.ini is ignored/overwritten by Symfony.

So doing this in a compiler pass works:

```php
    public function process(ContainerBuilder $container)
    {
        $options = $container->getParameter('session.storage.options');
        $options['cache_limiter'] = '0';
        $container->setParameter('session.storage.options', $options);
    }
```

Then the behavior is indeed like it was before :+1:

**Comment by nicolas-grekas** [comment]
Could be added. But I'm not sure it makes sense, unless in specific cases maybe. Why allowing a "public" C-C when the session is used. I still don't get it... (but you have your solution so you don't need me to understand :) )

**Comment by dmaicher** [comment]
Ok after some debugging I found the reason the session is started :yum: 

We have a locale listener that stores the locale in the session.

Thanks for your help anyway :+1:

**Comment by emodric** [comment]
@nicolas-grekas @dmaicher The exact same thing happens for me even if no session is started.

But even if there is a session, still, public response with shared max age is perfectly valid for example in eZ Platform usecase, which caches the pages in Varnish even if there is a session, because the cache variation is not done on session itself, but on user group ID.

**Comment by teohhanhui** [comment]
@nicolas-grekas

Calling `isEmpty` on the `Session` causes its `$usageIndex` to be incremented here, which means the `Cache-Control: private` header is always set in a test environment:
https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Component/HttpKernel/EventListener/AbstractTestSessionListener.php#L74

Is it intentional (why?) or is it a bug?

**Comment by dmaicher** [comment]
@teohhanhui yes currently there is a bug in the implementation. See this test fail: https://github.com/symfony/symfony/pull/27714

Nicolas is looking into it :wink:
