### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ptomulik** [symfony/symfony#25440]
https://github.com/symfony/symfony/blob/efc19fc6d7df6979ac34d7fd864370d722b1cb2c/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L76

I believe, it should refer to ``$this->options['scope']`` (currently it refers ``$this->options['scopen']`` (extra ``n``)).

**Comment by Simperfit** [comment]
@ptomulik Do you want to provide a pull request for this ? It seems like a typo for me too ;)
