### ISSUE TITLE
User Deprecated: Passing "false" as the second argument to Symfony\Component\HttpKernel\Kernel::getBundle() is deprecated as of 3.4 and will be removed in 4.0.

### ISSUE THREAD

**Issue by krushnaghodke** [symfony/symfony#25457]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.1

when i update symfony version from 3.3. to 3.4. Showing deprecation as  

> User Deprecated: Passing "false" as the second argument to Symfony\Component\HttpKernel\Kernel::getBundle() is deprecated as of 3.4 and will be removed in 4.0.

[▼
  "exception" => ErrorException {#312 ▼
    #message: "User Deprecated: Passing "false" as the second argument to Symfony\Component\HttpKernel\Kernel::getBundle() is deprecated as of 3.4 and will be removed in 4.0."
    #code: 0
    #file: "/Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php"
    #line: 237
    #severity: E_USER_DEPRECATED
    trace: {▶}
  }
]

**Comment by iltar** [comment]
Can you post the stack trace? This is not really meaningful.

**Comment by krushnaghodke** [comment]
/Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:237 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/FileLocator.php:185 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/FileLocator.php:135 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/TemplateLocator.php:85 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Twig/Loader/FilesystemLoader.php:77 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:150 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Environment.php:330 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Environment.php:424 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:125 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:49 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:45 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:72 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php:107 {▶}
  Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener->onKernelView() {}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:104 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:139 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:158 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/web/app_dev.php:37 {▼
    › 
    › $response = $kernel->handle($request);
    › $response->setSharedMaxAge(604800);
    arguments: {▶}
  }
}

**Comment by xabbuh** [comment]
This code is part of LiipThemeBundle (see https://github.com/liip/LiipThemeBundle/blob/master/Locator/FileLocator.php#L185). Please report the issue in their repository. Thank you for understanding. :)

**Comment by krushnaghodke** [comment]
@xabbuh  ok thanks :)
