### ISSUE TITLE
[Form] Form name validation does not accept dot

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#25462]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no
| Symfony version  | 3.4

The method `FormConfigBuilder::isValidName` check the validity of the `name` attribute in forms. Actually this attribute must start with a letter, a digit or an underscore and contains letters, digits, numbers, underscores, hyphens, and colons.

The problem is that the DTD say that the name attribute is a CDATA. The [specification of CDATA](https://www.w3.org/TR/html401/types.html#type-cdata) tell use that :

```
 ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
```

This issue is not to refuse digits and underscore for the fist character (which imply BC break), but to accepts periods (".") in the rest for the name.

**Comment by xabbuh** [comment]
The source of truth here is the PHP code. We cannot reflect all the limitations in the schema definition (the same applies to the semantic configuration of bundles for example).

**Comment by xabbuh** [comment]
To clarify: I do not think there is anything that needs to be fixed here.
