### ISSUE TITLE
[HttpKernel] Replace \Exception with \Throwable?

### ISSUE THREAD

**Issue by roukmoute** [symfony/symfony#25467]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

I've just seen that the entire application is [try\catch](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php#L65-L78) with an `\Exception` not with `\Throwable`.
Are you interested with this update?

**Comment by chalasr** [comment]
Already proposed and rejected in https://github.com/symfony/symfony/issues/22128, because errors are managed by the Debug component. 
I don't think we changed our mind, I let @nicolas-grekas confirm

**Comment by nicolas-grekas** [comment]
Yes, the current code is really fine and on purpose.

**Comment by roukmoute** [comment]
@nicolas-grekas Debug component is loaded by default in Symfony3.x?

**Comment by nicolas-grekas** [comment]
Here: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L64

and when it's not, the low level idea is that errors should not be dealt with the same way as exceptions.
So letting them throw is in fact much better. Don't catch Throwable in your own code base, unless you actually want to deal with raw errors ( but you don't, that's too big mistakes to be dealt with in userland generally)
