### ISSUE TITLE
Dotenv: fatal error

### ISSUE THREAD

**Issue by jrodshaffer** [symfony/symfony#25469]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.1

Doing a clean install of Symfony 4.0.1 I get the following error.

[Tue Dec 12 09:43:46.643701 2017] [:error] [pid 2954] [client 192.168.6.39:50707] PHP Fatal error:  Uncaught TypeError: Return value of Symfony\\Component\\Dotenv\\Dotenv::populate() must be an instance of Symfony\\Component\\Dotenv\\void, none returned in /var/www/html/my-project/vendor/symfony/dotenv/Dotenv.php:95\nStack trace:\n#0 /var/www/html/my-project/vendor/symfony/dotenv/Dotenv.php(57): Symfony\\Component\\Dotenv\\Dotenv->populate(Array)\n#1 /var/www/html/my-project/public/index.php(15): Symfony\\Component\\Dotenv\\Dotenv->load('/var/www/html/m...')\n#2 {main}\n  thrown in /var/www/html/my-project/vendor/symfony/dotenv/Dotenv.php on line 95

**Comment by Simperfit** [comment]
You seems to have the wrong version of PHP, what PHP version are you using ?

**Comment by jrodshaffer** [comment]
PHP 7.1.12-2+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Dec  7 2017 20:12:04) ( NTS )
Copyright (c) 
1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-2+ubuntu16.04.1+deb.sury.org+2, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Simperfit** [comment]
Is it the same as the one running the server ?

```
Symfony\Component\Dotenv\void,
```
because `void` here is not interpreted by php, which means that the server is not in 7.1 but in 7.0 since void return types [has been introduced in 7.1](https://wiki.php.net/rfc/void_return_type)

**Comment by xabbuh** [comment]
@Simperfit is right here. This is the kind of error you get when running PHP code using the `void` return type hint on PHP 7.

**Comment by krishnaspace** [comment]
I also had the same issue when I tried to run Symfony 4 on Ubuntu 16.04 server. In my situation I forgot to enable the new php version in the Apache server after upgrading from v7.0 to v7.2 . I hope below details would help you to check on your server.

Run following command to see which php version is active.  
`ls /etc/apache2/mods-enabled/php*`

Disable previously installed php version.  
`sudo a2dismod php7.0`  

Enable new installed php version.  
`sudo a2enmod php7.2`

Do not forget to restart Apache server.

**Comment by NDjalo** [comment]
> I also had the same issue when I tried to run Symfony 4 on Ubuntu 16.04 server. In my situation I forgot to enable the new php version in the Apache server after upgrading from v7.0 to v7.2 . I hope below details would help you to check on your server.
> 
> Run following command to see which php version is active.
> `ls /etc/apache2/mods-enabled/php*`
> 
> Disable previously installed php version.
> `sudo a2dismod php7.0`
> 
> Enable new installed php version.
> `sudo a2enmod php7.2`
> 
> Do not forget to restart Apache server.

it Worked for me thank you very much

**Comment by cgcerro** [comment]
For people looking for this error at built-in server at symfony 4

You can choose your own php versión creating a .php-version in your project directory. i.e:

`echo "7.1" > .php-version`
