### ISSUE TITLE
[DependencyInjection] Add ability reference tagged services as service locator

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#25465]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

It would be nice allow inject tagged services as `ServiceLocator` instead of `iterable`. For example we have set of report generators, all of them implements `ReportGenerator` interface. We have tagged them with tag `app.report_generator` using autoconfigure, but we require compiler pass for creating `ServiceLocator` with them.

**Comment by Koc** [comment]
We could get rid of some passes like this https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPass.php#L28

**Comment by ro0NL** [comment]
Think im :-1: we discussed many variants for this feature, and eventually settled with a straightforward implementation; inject services by tag, ordered by priority. Anything else is more or less opinionated / bloats the syntax, and should be done in a custom compiler pass IMHO.

For sure we could think of something like `!tagged { tag: some, key_attribute: id }`. Which probably looks better in XML anyway :) But what happens with duplicate keys etc? Hence; opinionated.

**Comment by nicolas-grekas** [comment]
We wondered about that with @ro0NL a few months ago an concluded what he says: because there is no single way to set names of the ids, we cannot generate service locators from tagged services.

**Comment by nicolas-grekas** [comment]
Just to make this PR closeable one day: I'm personally 👎 as previously explained.
