### ISSUE TITLE
[DI] Can't dump container if undefined constants (e.g ext not installed)

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#25472]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0+ ?

I'm currently working on a bundle which can support another service if an extension is installed (amqp's pecl). So I made a service that can use `AMQP_` constants.

The thing is, if the extension is *not* installed, and if I don't plan to use that one, and want to use another service (e.g phpamqplib's php implementation), as the dic is scanning the files, it complains about undefined constants and assuming its string form.

Tested with a basic flex installation on the master version of my bundle https://github.com/Wisembly/AMQPBundle and the recipe available on the recipe contrib repo.

```
bin/console -vvv

In ReflectionClassResource.php line 124:

  [ErrorException]
  Notice: Use of undefined constant AMQP_EX_TYPE_DIRECT - assumed 'AMQP_EX_TYPE_D
  IRECT'

Exception trace:
 Symfony\Component\Config\Resource\ReflectionClassResource->generateSignature() at /home/talus/dev/test-amqp-bundle/vendor/symfony/config/Resource/ReflectionClassResource.php:108
 Symfony\Component\Config\Resource\ReflectionClassResource->computeHash() at /home/talus/dev/test-amqp-bundle/vendor/symfony/config/Resource/ReflectionClassResource.php:60
 Symfony\Component\Config\Resource\ReflectionClassResource->serialize() at n/a:n/a
 serialize() at /home/talus/dev/test-amqp-bundle/vendor/symfony/config/ResourceCheckerConfigCache.php:132
 Symfony\Component\Config\ResourceCheckerConfigCache->write() at /home/talus/dev/test-amqp-bundle/vendor/symfony/framework-bundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php:32
 Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->process() at /home/talus/dev/test-amqp-bundle/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /home/talus/dev/test-amqp-bundle/vendor/symfony/dependency-injection/ContainerBuilder.php:707
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /home/talus/dev/test-amqp-bundle/vendor/symfony/http-kernel/Kernel.php:503
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /home/talus/dev/test-amqp-bundle/vendor/symfony/http-kernel/Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at /home/talus/dev/test-amqp-bundle/vendor/symfony/framework-bundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/talus/dev/test-amqp-bundle/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/talus/dev/test-amqp-bundle/bin/console:36
```

**Comment by Taluu** [comment]
Note ; to solve this, I had to remove the array constant `TYPES` in the `PeclBroker` and port this into a static var in the `declare()` method.

But still, as the file is loaded and scrutinized, even if the class is not destined to be loaded if the extension is missing, having this error is not really expected. I'll let you close if you think it is not really worth it.

**Comment by nicolas-grekas** [comment]
This means the service has not been removed, even if it's broken (because the ext is missing as you said).
Can't you remove this service conditionally (or make it private so it's garbage collected?)

**Comment by Taluu** [comment]
It's actually private, but for BC reasons I need a public alias on it. But removing it in the extension would be an option, will have a look.

**Comment by nicolas-grekas** [comment]
Actually it might still fail. You'll tel me :)

**Comment by iltar** [comment]
Keeping the Alias will for sure make it crash, I had a similar issues this week.

**Comment by Taluu** [comment]
Removing the definition in the extension works. I'll let you close if you don't think it's worth the trouble to look for a fix as this kind of an edge case imo.

**Comment by nicolas-grekas** [comment]
OK, thanks for checking, looks the best IMHO.
We could actually do something in `ReflectionClassResource` to make it resilient to broken consts.
BUT, as far as I tried, this would introduce a significant complexity.
I'd say it's not worth it now. Closing.
Thanks for the feedback.
