### ISSUE TITLE
[HttpFoundation] etag handling with mod_deflate

### ISSUE THREAD

**Issue by Nemo64** [symfony/symfony#25475]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

If apaches mod_deflate is used, it adds a suffix to the etag. something like: `73832eb3-gzip`. The Problem is that this is passed to the php script so the etag comparison fails every time. Now I'm not sure if this is an issue for apache to solve as i think mod_deflate should strip the gzip suffix again. But it would probably be nice if the http foundation would respect that or at least warn that something is wrong.

**Comment by Simperfit** [comment]
@Nemo64 Do you want to provide a PR for this ?

**Comment by javiereguiluz** [comment]
Could we first check how do other frameworks solve this (not necessarily PHP frameworks because this looks like a universal problem). Thanks!

**Comment by nicolas-grekas** [comment]
100% agree with Javier: this behavior of mod_deflate is strange. It needs to be investigated, and I don't think there is anything to do on Symfony side: we should just deal with HTTP, not with things that alter its semantic for unknown reasons.

**Comment by Nemo64** [comment]
The reason for adding the suffix is simple. It factors in reverse proxies
and clients which might not accept compression. If a client can't handle
compression it gets an uncompressed version with a different etag so that
the reverse proxy knows that those are 2 different responses. And php just
gets the raw headers and therefore sees the suffix. I haven't put effort
into creating an issue for apache yet. But I think a workaround might still
be necessary.
Nicolas Grekas <notifications@github.com> schrieb am Do. 14. Dez. 2017 um
09:33:

**Comment by nicolas-grekas** [comment]
Can you try using [strong etags](https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation)? Does it change anything?

**Comment by Nemo64** [comment]
I don't recall ever using weak etags. strong etags are the default.

Also, others are suffering from this problem too, it seems to be old https://fullstackhack.wordpress.com/2014/12/10/the-pain-of-etags-mod_deflate-apache-2-4-and-tomcat-7/

Apache 2.5 introduces `DeflateAlterETag` directive which can solve it. Another one (as mentioned in the blog above) is to force remove the suffix in the configuration using `Header` directives.

If I think about it, it doesn't really make sense to add that suffix. Yes, the response is different, but if I downloaded the content uncompressed I don't have to redownload it compressed if it is still the same. Maybe it's just for proxies but apache adds a `Vary: Accept-Encoding` anyways so the proxy should cache those separately anyways.

I don't know if there is anything the http component can do to hint to those workarounds without the possibility of false positives.

**Comment by fabpot** [comment]
Looks like there is nothing to do on our side. Let's close.
