### ISSUE TITLE
More readable error in the console

### ISSUE THREAD

**Issue by mickaelw** [symfony/symfony#25481]
I'm on Symfony 3.2, when I have an error in the console is unreadable.

For example:
![screen shot 2017-12-13 at 13 10 19](https://user-images.githubusercontent.com/23268376/33938312-5eeb5eea-e007-11e7-8a2a-a53b7311e35f.png)

Maybe it's corrected on next version?

**Comment by Simperfit** [comment]
Hey @mickaelw What terminal are you using ?

**Comment by mickaelw** [comment]
I use the terminal of Intellij IDEA last version

**Comment by xabbuh** [comment]
Duplicate of #24125?
