### ISSUE TITLE
[Cache] Cannot redeclare class Acme in /path/to/Acme.php

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#25484]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.1
| PHP version | 5.6.x

After upgrading to Symfony 3.4.1 I'm encountering strange caching issues.

In dev I get "Cannot redeclare class EventSubscriberInterface" with a fresh cache after the first successfull page load. In that case the first broken call is the web profiler on that exact page. Reloading the page directly runs into the FatalErrorException. I got it twice directly after executing a `doctine:migration:foo` command and once after switching branches or something like that.

In prod I get (on my dev and another totally different machine) a "PHP Fatal error:  Cannot redeclare class appProdProjectContainer in /var/www/conti.ido.software/git/devel/var/cache/prod/appProdProjectContainer.php on line 7519" on warming up the cache.

In dev I could fix it by randomly removing cache, clearing cache and writing `dump("foo")` into the EventSubscriberInterface file in no particular order. I found #21520 which sounds related.

It's driving me nuts.

**Comment by javiereguiluz** [comment]
In the Symfony Demo repository we're also getting reports about similar issues: *"Cannot declare class XXX because the name is already in use"*: https://github.com/symfony/demo/issues/411#issuecomment-342176785

**Comment by althaus** [comment]
I got it sorted out once by removing the boostrap.cache file. I have to check if this is the cure, if it happens again.

**Comment by nicolas-grekas** [comment]
This issue is generally due to this: conflicting inlining strategies between `boostrap.cache.php`, `classes.php` and now maybe the inlined "include" in the container. Fortunately, we deprecated the two former, so this will die soon. Just don't use them and done.

**Comment by althaus** [comment]
>Just don't use them and done.

How? I just upgrade from 3.3 to 3.4 and did all relevant upgrades from UPGRADE-3.4.md. There's nothing stated about those files?

**Comment by althaus** [comment]
Ok... just killing the bootstrap file isn't the solution. Redoing all caches still falls back to the exception.

btw: I'm currently pinned on PHP 5 and as far as I understand the app*.php files, dropping the bootstrap file is for PHP 7 only.

**Comment by nicolas-grekas** [comment]
v3.4.2 will embed a fix for this so that no action will be required anymore. See #25363

**Comment by althaus** [comment]
Okay, thanks!

I'll got for setting `container.dumper.inline_class_loader` to `false` and see if the issue vanishes for me, too.

**Comment by simonbertonsugasti** [comment]
Hi, did the container.dumper.inline_class_loader false, fixed the problem?

Using Symfony 3.4.6 and keep getting the "cannot declare class Locale, because the name is already in use" 

/Symfony/Component/Intl/Resources/stubs/Locale.php:21

Thanks !!!

**Comment by YoannBuzenet** [comment]
Hello, in which file do you add this parameter ?

**Comment by TomasVotruba** [comment]
> Hi, did the container.dumper.inline_class_loader false, fixed the problem?

I can confirm this finally helped me, thank you :+1: 

> Hello, in which file do you add this parameter ?

In your `Kernel`, e.g. here:

```php
protected function build(ContainerBuilder $containerBuilder): void
{
        $containerBuilder->setParameter('container.dumper.inline_class_loader', false);
}
```
