### ISSUE TITLE
Web Debug Toolbar 404

### ISSUE THREAD

**Issue by VaN-dev** [symfony/symfony#25494]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

just install a fresh symfony 4 project, added the profiler recipe. the debug tool bar displays, but contains the following error : An error occurred while loading the web debug toolbar. Open the web profiler.

when clicking the link, got a 404 on /_profiler/d71137

my installation process :

composer create-project symfony/skeleton my-project
composer require twig
composer require --dev profiler
composer require annotations

however, i can see the profiler routes with debug;router :

 -------------------------- -------- -------- ------ ----------------------------------- 
  Name                       Method   Scheme   Host   Path                               
 -------------------------- -------- -------- ------ ----------------------------------- 
  _twig_error_test           ANY      ANY      ANY    /_error/{code}.{_format}           
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                      
  _profiler_home             ANY      ANY      ANY    /_profiler/                        
  _profiler_search           ANY      ANY      ANY    /_profiler/search                  
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar              
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                 
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                    
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                 
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router          
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception       
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css   
  index                      ANY      ANY      ANY    /                                  
 -------------------------- -------- -------- ------ -----------------------------------

**Comment by sroze** [comment]
Erm... I can't reproduce. What do you have in the `routes` folder? 🤔 

Also... did you clear the cache? This would cause the profiles to disappear. What is the result of the `/_profiler/` page?

**Comment by VaN-dev** [comment]
my routes folder contains the following :

- dev
-- twig.yaml
-- web_profiler.yaml
- annotations.yaml

web_profiler.yaml contains the following :
```
web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler
```

I did clear the cache, even if the recipes already perform it.

/_profiler/ also returns a 404

**Comment by sroze** [comment]
Did you change anything? Like the `.env` file? How do you run the web server?

**Comment by VaN-dev** [comment]
didn't change anything to .env file. contains the following :
```
# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=7f6817ada6935d26cd71b958e6c30cee
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###
```

As a web server, i use a local apache with the following vhost :
```
<VirtualHost *:80>
	ServerName my-project.localhost

	DocumentRoot /home/dmi/Work/Perso/my-project/public
	<Directory /home/dmi/Work/Perso/my-project/public>
	    AllowOverride All
	    Require all granted
	    Allow from All
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by xabbuh** [comment]
Can you share your log?

**Comment by VaN-dev** [comment]
closing this issue, i solve dthe problem by following the current doc : https://symfony.com/doc/current/setup/web_server_configuration.html

didn't I had to install an apache recipe

**Comment by Mondane** [comment]
Just found out the debug bar does work when opening /public/index.php .
