### ISSUE TITLE
Locale fallback split on dash for BCP47

### ISSUE THREAD

**Issue by thejahweh** [symfony/symfony#25498]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

Is there a reason for not supporting a BCP47 locale fallback.
As far as I see it would only require 2 more lines at `\Symfony\Component\Translation\Translator::computeFallbackLocales`.

There was something similar for version 3.3.8: https://github.com/symfony/symfony/issues/24154

**Comment by Simperfit** [comment]
Like @xabbuh said the changes seems to be already in, what do you need ?

**Comment by javiereguiluz** [comment]
@Simperfit is referring to [this comment](https://github.com/symfony/symfony/issues/24154#issuecomment-351714866) where @xabbuh says that these changes are already present in Symfony 4.0: https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Intl/Locale.php#L70

@thejahweh for this reason I'm closing this as "not needed to fix" ... but if we missed something, please reopen it. Thanks!
