### ISSUE TITLE
Incompatible types of Request in Symfony tests

### ISSUE THREAD

**Issue by indapublic** [symfony/symfony#25501]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.13

I have legacy code which use overrided Symfony\Component\HttpFoundation\Request

```
use Symfony\Component\HttpFoundation\Request as CoreRequest;

class Request extends CoreRequest
{
```

So controllers look like

```
public function myAction(OverridedRequest $request)
{
```

I want to write some simple tests for these controllers, but I'm received errors about incompatible types.

> 1) Tests\AppBundle\Controller\ResidentControllerTest::testGetResidents
> 
> TypeError: Argument 1 passed to AppBundle\Controller\ResidentController::getResidentsAction() must be an instance of AppBundle\Component\HttpFoundation\Request, instance of Symfony\Component\HttpFoundation\Request given

How I should fix test for correct work?

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
