### ISSUE TITLE
IdentityTranslator does not consider delimiter characters (%)

### ISSUE THREAD

**Issue by TPete** [symfony/symfony#25509]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8 - 4.0

The [IdentityTranslator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/IdentityTranslator.php) does not respect delimiter characters (%) when replacing parameters. If the parameter is found as a substring within in the translation key, it will be replaced even if there are no delimiters present in the key.

    $translator = new IdentityTranslator();
    $translator->trans('domain.count', ['%count%' => 42]);
    //results in 'domain.42', but should leave the translation key unchanged

I guess this is due to `strtr` which is used internally and shows the same behavior.

**Comment by stof** [comment]
`strtr` does not have this behavior: https://3v4l.org/IIdI6

so this report looks really weird to me (especially when you says that `strtr` shows the same behavior)

**Comment by TPete** [comment]
Thanks for checking! 

It actually was a feature in our setup, which allows us to leave out the delimiters, that caused my misinterpretation. Sorry for bothering.
