### ISSUE TITLE
[VarDumper] Stub could not be converted to string

### ISSUE THREAD

**Issue by DylanDelobel** [symfony/symfony#25500]
| Q                | A
| ---------------- | -----
| Bug report?      | Yes
| Feature request? | No
| BC Break report? | Yes
| RFC?             | No
| Symfony version  | 3.2.13

From the profiler page, the Doctrine panel ran into this error
```
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: 
Object of class Symfony\Component\VarDumper\Cloner\Stub could not be converted to string").
```
From the logs

```
CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the 
rendering of a template ("Catchable Fatal Error: Object of class 
Symfony\Component\VarDumper\Cloner\Stub could not be converted to string")."
``` 
at `vendor\doctrine\doctrine-bundle\Resources\views\Collector\db.html.twig line 264 `

The error disappear if i remove `|doctrine_replace_query_parameters(query.params)` from `db.html.twig`

```
<div id="original-query-{{ i }}-{{ loop.parent.loop.index }}" class="sql-runnable hidden">
 {{ (query.sql ~ ';')|doctrine_replace_query_parameters(query.params)|doctrine_pretty_query(highlight_only = true) }}
</div>
```

I think this last commit for SF4 compatibility break this
https://github.com/doctrine/DoctrineBundle/commit/eb6e4fb904a459be28872765ab6e2d246aac7c87#diff-6d007bf31d98cd56440dedea1d2956ecL291

Not entirely sure if it's `Stub` from symfony or `replaceQueryParameters` from doctrine should be fix, i wait for your comments

**Comment by nicolas-grekas** [comment]
3.2 is not maintained anymore. Please upgrade to lastest 3.3 or 3.4, this may have been fixed already.

**Comment by lcp0578** [comment]
= =
