### ISSUE TITLE
[Process] ContextErrorException | Array to string conversion

### ISSUE THREAD

**Issue by nanofelis** [symfony/symfony#25511]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.2

Environnement variables passed to `proc_open()` in https://github.com/symfony/symfony/blob/v3.4.2/src/Symfony/Component/Process/Process.php#L334 throw a `ContextErrorException "Array to string conversion"`

The reason seems to be that env vars are now always inherited https://github.com/symfony/symfony/compare/v3.4.1...v3.4.2#diff-f9f2411040cda7b73402481facf3e4dd
but if a query string is present in the url then $env contains `argv` as an array

```php
[
 "CONTENT_LENGTH" => "8610"
 "CONTENT_TYPE" => "application/x-www-form-urlencoded"
 "REQUEST_METHOD" => "POST"
 "QUERY_STRING" => "uniqid=s5a339da72130a"
 "argv" => [
          0 => "uniqid=s5a339da72130a" 
   ]
]
```
and apparently `proc_open()` does not expect a multi dimensionnal array for this parameter.

**Comment by nicolas-grekas** [comment]
How can that happen?
non-strings are filtered in https://github.com/symfony/symfony/blob/v3.4.2/src/Symfony/Component/Process/Process.php#L1723
Can you provide a reproducer?

**Comment by nanofelis** [comment]
Apparently the filter only applies to values fetched from $_ENV but the argv array is already present in $env from the line `$env = getenv();` line. Yes, I'll provide a reproducer today.

**Comment by nanofelis** [comment]
Ok after some enquiry it seems we have a weird server behavior on our side that makes `getenv()` always include argc and argv. It has nothing to do with Symfony, sorry about that !

**Comment by Toyinster** [comment]
This issue just cropped up over here, same as OP, `getenv()` is including the `argv` as an array. and it's causing a Array to string exception. 

@nicolas-grekas There isn't any validation on what `getenv()` returns. If you are on a high enough PHP version.

Reverting back to v3.4.1 fixes the issue for me.

**Comment by acidline** [comment]
Hi,

I have the same problem than @nanofelis, the getDefaultEnv() method preserves the "argc" & "argv" parameters from  `$env = getenv();`

For me, the trick is as follow (radical) : 

```php
private function getDefaultEnv()
{
    $env = getenv();
    foreach ($_ENV as $k => $v) {
        if (is_string($v)) {
            $env[$k] = $v;
        } else {
            unset($env[$k]);
        }
    }
    return $env;
}
```
What is the "good way" to avoid this problem ?

Nicolas

**Comment by Lavoaster** [comment]
Alrighty then. This is a bit weird.

If a script accesses `argv` from the `$_SERVER` variable at any point in the script REGARDLESS of if it is called, PHP will make it available in the `getenv` output. HOWEVER, If you have xdebug installed, it won't affect you. 

In my case this is actually caused because of a composer file include in `psy/psysh `, https://github.com/bobthecow/psysh/blob/master/src/Psy/functions.php#L295

@nicolas-grekas 

Here's smallest (well, not codegolf small :P) piece of code to reproduce it:

```php
<?php

var_dump(getenv());

function notcalled()
{
    $_SERVER['argv'];
}
```

**Comment by nicolas-grekas** [comment]
Thanks for the hints. Fixed by #25559

**Comment by stof** [comment]
this should probably be reported as a bug to PHP though

**Comment by Lavoaster** [comment]
Following @stof's comment I filed this https://bugs.php.net/bug.php?id=75712

Thanks for the fix @nicolas-grekas, do you know when it will be tagged?
