### ISSUE TITLE
Where has the SimplePreAuthenticatorInterface gone?

### ISSUE THREAD

**Issue by MonsieurBon** [symfony/symfony#25517]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.2

Hi all

I implemented an authentication system with API keys in Symfony 3.3 following [this guide](https://symfony.com/doc/3.3/security/api_key_authentication.html). Today I tried upgrading to Symfony 4 after upgrading to 3.4 and getting rid of all deprecation warnings. Currently I'm stuck because I can't find the SimplePreAuthenticatorInterface, AuthenticationFailureHandlerInterface and AuthenticationSuccessHandlerInterface. Where have they gone? What should I be using instead? The linked guide still mentions them for Symfony 4 (and 4.1).

Thanks for your help.

**Comment by chalasr** [comment]
None of them are gone https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Authentication/SimplePreAuthenticatorInterface.php, part of the `symfony/security-http`(and security, and security-bundle).

**Comment by MonsieurBon** [comment]
Ok, so I need to install that additional package. This should be noted in the documentation.

Next I'm getting this exception:
`method "__construct()" references interface "Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface" but no such service exists. It cannot be auto-registered because it is from a different root namespace.`

The interface and the implementing class is there.

What do I need to do about that? This is also mentioned in the documentation.

**Comment by Taluu** [comment]
Actually it is... https://symfony.com/doc/current/components/security.html

**Comment by chalasr** [comment]
You are probably moving to flex which is all about installing only what you need. 
Run `composer req security` and it should be ok. 
If you think there is a doc issue, please report it on https://github.com/symfony/symfony-docs if there is no similar issue. Thanks
