### ISSUE TITLE
[DI]  Service Definitions are not merged with previous ones when importing from resources

### ISSUE THREAD

**Issue by goatfryed** [symfony/symfony#25528]
| Q                | A
| ---------------- | -----
| Bug report?      | I think so
| Feature request? | maybe
| Symfony version  | 4.0.1

Service Definitions loaded by resource imports are not merged with previously defined definitions for the same service. All Definitions, that are defined after are properly merged.
I'm not sure, whether this is unintended and shouldn't be relied on, but I'd expect the service definitions to be merged in both cases.

Let's say we have a folder with two classes `App\FirstService` and `App\SecondService` and the following definition:

    services:
        App\FirstService:
            arguments:
                $someScalar: "Symfony can't read my mind on scalars :("
    
        App\:
            resource: 'path/to/folder/*'
            autowire: true      
            autoconfigure: true 
            public: true

        App\SecondService:
            arguments:
                $anotherScalar: "But it still works great :)"

I'd expect both services to be configured properly, but only `App\SecondService` is. The container will throw an exception for `App\FirstService`, since the constructor requires a value for `$someScalar`can't

In my use case, I need to configure some services for a bundle. Since they are only related to that bundle, I wanted to define them in the bundle specific configuration that is loaded before the `services.yaml` is loaded. I moved the definition into services.yaml, so it works, but if I were to remove the bundle, I'd need to drop more than just the bundle config.

**Comment by goatfryed** [comment]
Okay, it occured to me, that the definitions aren't merged at all. If the class is not defined, the service name is assumed to be the class and the later definition replaces the previous one completely.

Since I hadn't defined the class, I assumed that the definitions merged.

**Comment by nicolas-grekas** [comment]
Correct, that's what we tried to hint in the last line here:
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/services.yaml
