### ISSUE TITLE
[ExpressionLanguage] Allow custom Lexer

### ISSUE THREAD

**Issue by cyberhorse** [symfony/symfony#25520]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

It should be possible to set a custom Lexer (extended from the Lexer class) to modify how expressions are written and parsed.

Example use case - allow variables to be escaped in different ways. If for business reasons variables are already tokenized using a certain syntax, allow handling that syntax via a Lexer, rather than string manipulation.

It should be possible through a custom Lexer to handle these examples:
- `[var1] + [var2] > 10` to be equivalent to `var1 + var2 > 10`
- `{var1} + {var2} > 10` to be equivalent to `var1 + var2 > 10`
- `[var1 prop1] > 10` to be equlivalent to `var1.prop1 > 10`
- `Hello [var1 name]` to be equivalent to `"Hello "~var1.name`

**Comment by fabpot** [comment]
We made a conscious choice to not allow a different Lexer or Parser for this component. It has been proposed in the past to make it more "flexible" but it was always rejected. So, I'm closing this issue. Thanks for proposing.
