### ISSUE TITLE
fetch() with URL object errors: "url.match is not a function"

### ISSUE THREAD

**Issue by hlb-schmidt** [symfony/symfony#25538]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | dunno
| RFC?             | dunno
| Symfony version  | 3.3.10

to reproduce, open a page that has the symfony profiler, and then in browser devtools javascript console run following:

- `fetch("https://symfony.com")` works as intended, we get a CORS error.

- `fetch(new URL("https://symfony.com"))` also gets the CORS error, but also a fatal error `url.match is not a function` that points to a oneliner added by symfony.

i guess its the symfony profiler assuming the url in fetch is a string...

**Comment by hlb-schmidt** [comment]
for a quick fix i added locally:

```
if (url instanceof URL) {
	url = url.href;
}
```

before https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L244

i guess for a real fix we want to use `paramType`...

**Comment by hlb-schmidt** [comment]
i guess this could be a proper fix
```
diff --git a/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig b/src/Symfony/Bundle/WebP
rofilerBundle/Resources/views/Profiler/base_js.html.twig
index e83e95a..7f0a4f0 100644
--- a/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig
+++ b/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig
@@ -250,6 +250,8 @@
                             mode: arguments[0].mode,
                             redirect: arguments[0].redirect
                         };
+                    } else if (paramType === '[object URL]') {
+                        url = url.href
                     }
                     if (!url.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
                         var method = 'GET';
```
ps. i know nothing about symfony internals!

**Comment by hlb-schmidt** [comment]
or, to follow the `if` before:
```
url = arguments[0].href
```

**Comment by ro0NL** [comment]
Status: reviewed
