### ISSUE TITLE
Yaml Constant Error On Symfony 4.0.2

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony#25534]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yno
| RFC?             | no
| Symfony version  | 4.0.2

When using constant in yaml like ```!php/const:App\Kernel::SEMART_VERSION```

in Symfony 4.0.2 is catching an error

```Notice: Uninitialized string offset: 69 in <yaml file path>```

When use 3.4.2 version, the error is gone

**Comment by ad3n** [comment]
```!php/const App\Kernel::SEMART_VERSION```

Change to space in version 4.0.X

**Comment by funcphp** [comment]
Thakns! @ad3n 
Also why we use space instead of dots in Symfony 4?

**Comment by xabbuh** [comment]
that's how one should use tags in regard to the specification

**Comment by rsnitsch** [comment]
Please add a note about the ! -> space replacement in this blog post:
https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

This blog post appears in the top Google results, so it's still relevant. I guess I am not the only one who's run into this problem...

**Comment by javiereguiluz** [comment]
@rsnitsch we've just updated the blog post you mentioned to fix this error. Thanks!

**Comment by iluuu1994** [comment]
User error or not, shouldn't Symfony check the bounds of the string?

**Comment by xabbuh** [comment]
@iluuu1994 You are absolutely right. See #33517 for the fix.

**Comment by iluuu1994** [comment]
Cool, thanks @xabbuh!
