### ISSUE TITLE
[Routing] Duplicate slashes in URL

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony#25537]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.2

Hi,

I have an issue with routing and using an explicit PHP file as frontend controller.

Please take a look at the example project: https://github.com/apfelbox/symfony-slashes

The gist is:

#### Files setup

```php
class IndexController extends Controller
{
    /**
     * @Route("/", name="index")
     */
    public function index(RouterInterface $router)
    {
```

```php
class TestController extends Controller
{
    /**
     * @Route("/test", name="test")
     */
    public function index()
    {
```

#### Transparent Frontend Controller

I am using a transparent frontend controller like: `https://my-example.test` (`index.php` or set via rewrite rules).

| Current URL | Generated URL | |
| -- | -- | -- |
| `https://my-example.test/` | `/test` | ✅  | 

#### Explicit Frontend Controller

I am using an explicit frontend controller like: `https://my-example.test/app.php` or `https://my-example.test/app_dev.php`.

| Current URL | Generated URL | |
| -- | -- | -- |
| `https://my-example.test/app_dev.php` | `/app_dev.php/test` | ✅  | 
| `http://my-example.test/app_dev.php/` | `/app_dev.php//test` | ❌  |

**Comment by apfelbox** [comment]
Hmm, I can reproduce this in Symfony 3.3.14.

**Comment by apfelbox** [comment]
Okay, so I can reproduce this way back to 3.2 (I stopped testing there).

The interesting thing though is that generating an URL for `"index"` will produce an URL **with** the slash, so even if you start out at the URL without slash, clicking one link will bring you back to the one with the slash.

**Comment by Simperfit** [comment]
@apfelbox Do you want to (or have time to) propose pull request for this ?

**Comment by apfelbox** [comment]
@Simperfit I can send a PR, but I am not sure about where to fix this.

The issue finally manifests here:
https://github.com/symfony/symfony/blob/4058f2f284c6943e459a83e6bc368d3984da1c57/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L240

The `$requestContext->getBaseUrl()` is `/app_dev.php/` and the generated `$url` starts with `/...`.

The request context comes untouched from `$request->getBaseUrl()`.
Where should we fix this?

**Comment by apfelbox** [comment]
For reference, I am using a regular default configured nginx locally (for an example configuration see here): https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/
But I can reproduce it using the built-in PHP webserver `php -S localhost:8000`

And as I read it, these tests are wrong: https://github.com/symfony/symfony/blob/2b725ca200dfcb52b5cc11b943e49cee48970b6e/src/Symfony/Component/HttpFoundation/Tests/RequestTest.php#L1509-L1594

The issue seems to lie here:
https://github.com/symfony/symfony/blob/2b725ca200dfcb52b5cc11b943e49cee48970b6e/src/Symfony/Component/HttpFoundation/Request.php#L1755

`getUrlencodedPrefix` returns:
* for `/app_dev.php` -> `/app_dev.php`
* for `/app_dev.php/` -> `/app_dev.php` ❌  
* for `/app_dev.php/xyz` -> `/app_dev.php`

**Comment by sroze** [comment]
Interesting. That's weird. Not something we can fix within Symfony though, so I'd close the issue...
