### ISSUE TITLE
bin/console has not auto complete commands

### ISSUE THREAD

**Issue by lockland** [symfony/symfony#25535]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

bin/console is an awesome tool for people whose use symfony but remember all possible commands is not productive. Thus I believe if you implement auto complete for its options, it would be perfect for these users, like git.

**Comment by ro0NL** [comment]
https://github.com/bamarni/symfony-console-autocomplete works pretty well =/ Im not sure this is easy / worth implementing out-of-the-box.

**Comment by lockland** [comment]
Amazing. It worked very well for me. But if this tool comes with symfony installation would be interesting.

**Comment by ro0NL** [comment]
symfony/console could add a suggest entry to composer, then again this is as simple as googling `symfony console autocomplete` :thinking: 

Im not sure there's any motivation to transfer this into core... could be cool :)

**Comment by lockland** [comment]
I disagree with you because I believe that our job is to simplify users life. So, even is simple use google to found a solution for it, a framework should come with all facilities and, of course, provides an easy configuration for.

Of course that many people can use google to access the solution, but we need to know which words use and what solution will work as expected. Therefore, if a solution came in the box we'll know this one works. We can use many tools to endorse it such as Doctrine, SwiftMailer or Monolog.

I understood your point and know that to transfer this project into core is not an option, but there is no problem in use composer to install and configure it in my opinion.

**Comment by nicolas-grekas** [comment]
should we do something in a recipe ?

**Comment by Simperfit** [comment]
I agree with adding this to a recipe, should it be contrib one or official one ?

**Comment by ro0NL** [comment]
The required setup is adding `eval "$(/path/to/symfony-autocomplete)"` in your bash profile. So typically it would be a global composer install. Not sure what a recipe would do..?

Perhaps add a note in docs?

**Comment by Pierstoval** [comment]
This does not work the same way depending on the platform, so I'm not sure it's a good idea to integrate this in Symfony.

**Comment by javiereguiluz** [comment]
I was thinking about creating a recipe ... but then I realized that this autocomplete utility:

* Must be installed globally, not per project
* It doesn't work depending on your operating system and shell
* It requires to make some changes in your shell profile

For all these reasons we cannot include it in Symfony and we cannot create a recipe because the installation cannot be automated. However, I've created an issue in Symfony Docs to consider if we should mention this somewhere (see https://github.com/symfony/symfony-docs/issues/8936).

**Comment by lsmith77** [comment]
BTW there is also an accessability dimension to supporting this out of the box. Some developers, due to physical impairment, heavily rely on auto complete to be able to get work done.

**Comment by lsmith77** [comment]
so yeah if we cannot find a good out of the box solution .. then we should at least make an effort to make it easy to set this up via the docs
