### ISSUE TITLE
[Bug] Valid constraint on non object alters property path behavior

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#25546]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3 (perhaps lower)

My form looked like this (files pasted in bottom):
 - AddClientType with contact and a boolean field. Both fields had `@Valid()`
 - contact was a type of ContactInfoType, which binds to a data object, ContactInfoData
 - ContactInfoData has a field called first_name, which binds to a TextType
 - ContactInfoType had the constraints options set

What happens, was that the validation of the constraints from the form option, were bound to `[contact].data.first_name` rather than `children[contact].data.first_name`. In turn, this causes the errors to bubble up to the root, rather than where they belong, and were no longer rendered.

The culprit was the `@Valid` on the boolean field, for some reason it causes the property paths of the `constraints` option to be invalid. I know this shouldn't be done on boolean fields, but my colleague didn't know about this one and a half month ago, and it has been broken ever since.

While debugging, I've seen an exception come by that told me: `Cannot create metadata for non-objects. Got: boolean`. I think this is related to the issue:
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php#L82
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L349

With the examples below, my expectation would be
 - Either an exception that I have `@Valid` on a wrong data type _(preferred)_
 - Or that the mapping is still correct for `constraints`

The result will be that only 1 out of 3 errors is properly mapped to first_name. FirstNameNotEmptyValidator.first_name and Callback.first_name are unmapped errors.

/cc @Vinorcola could this be your issue in #25401 as well?

Code you can use to reproduce the issue (sorry I don't have a working repository atm).

##### src/Form/AddClientType.php
```php
<?php
namespace App\Form;

use Hostnet\Component\ContactPersonForm\Type\ContactInfoType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class AddClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('contact', ContactInfoType::class);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class'  => ClientData::class]);
    }
}
```
##### src/Form/ClientData.php
```php
<?php
namespace App\Form;

use Symfony\Component\Validator\Constraints as Assert;

class ClientData
{
    /** @Assert\Valid() */
    public $contact;

    /** @Assert\Valid() */
    public $a_bool;

    public function __construct()
    {
        $this->contact = new ContactInfoData();
        $this->a_bool  = true;
    }
}
```
##### src/Form/ContactInfoData.php
```php
<?php
namespace App\Form;

use Symfony\Component\Validator\Constraints as Assert;

class ContactInfoData
{
    /** @Assert\NotBlank() */
    public $first_name;
}
```
##### src/Form/ContactInfoType.php
```php
<?php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\ConstraintValidator;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

final class ContactInfoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('first_name', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ContactInfoData::class,
            'constraints' => [
                new FirstNameNotEmpty(),
                new Callback(['callback' => function (ContactInfoData $data, ExecutionContextInterface $context) {
                    if (empty($data->first_name)) {
                        $context->buildViolation('Callback.first_name')
                            ->atPath('first_name')->addViolation();
                    }
                }])
            ],
        ]);
    }
}

class FirstNameNotEmpty extends Constraint
{
}

class FirstNameNotEmptyValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        if (empty($value->first_name)) {
            $this->context->buildViolation('FirstNameNotEmptyValidator.first_name')
                ->atPath('first_name')->addViolation();
        }
    }
}
```

**Comment by Vinorcola** [comment]
Maybe this is indeed related to #25401.

In my buggy project, I'm using FormDTOs as underlying data. I've tried to reproduce #25401 from scratch project, but without using FormDTOs, and with no success to reproduce the bug.

Unfortunatelly, I don't have much time rigth now to investigate. I'll try to do my best to do some review and help.

**Comment by Vinorcola** [comment]
@iltar I've updated #25401 with a reproducer. I'm not sure your issue is related though...

**Comment by iltar** [comment]
No, I don't think so. I was unable to use your fix yesterday, didn't work for me.

**Comment by deadcowfr** [comment]
Change your field name to camelCase in your buildForm : 

`$builder->add('firstName', TextType::class);` (and everywhere else if needed)

Had the exact same problem for 2 days and this ended up magically solving everything.

If it does solve your problem, would be great to have an expert explain why + if needed document that somewhere cause I found several developers having the same problem, with no solution.
