### ISSUE TITLE
Increase RTL (right to left) support in form

### ISSUE THREAD

**Issue by vasilvestre** [symfony/symfony#25544]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             |no
| Symfony version  | all

There's a simple way to make textarea and input compatible with both RTL and LTR languages.
Add dir="auto" do the trick ! Here's a really complex demo : https://codepen.io/anon/pen/ooBpxV

It's a simple feature, yet useful. I can make a PR for that, it's only a question of minutes and I'd be so proud to do it.

I got this idea from [this link](https://listed.standardnotes.org/@mo/312/psa-add-dir-auto-to-your-inputs-and-textareas).

**Comment by vasilvestre** [comment]
@javiereguiluz I can make a PR for that ?

**Comment by javiereguiluz** [comment]
Sadly nobody has commented on this proposal yet. This is common for Form related issues, which lots of them are ignored.

If you consider that the pull request is small and you don't mind wasting a bit of time in case it's ultimately rejected, you can make the PR. If it's a complex PR, I'd wait. Thanks for your patience and for wanting to contribute to Symfony!

**Comment by xabbuh** [comment]
Can the `dir` attribute be added to all forms without any drawback? Is this something that must be configurable through options?

**Comment by vasilvestre** [comment]
I could/should be configurable. In fact  I think this could be for everyone knowing that it's just improve the app. There's no bad thing that can happen.. And it work on nearly all browser, even the old versions.
I can make it configurable but it's not really useful. I still can :)

**Comment by xabbuh** [comment]
Well, if there is no harm in adding this attribute, I think we could just update the existing form themes.

**Comment by vasilvestre** [comment]
That's what I would like to do 😄

**Comment by xabbuh** [comment]
If you'd like to create a pull request, I'd say just do so. :)

**Comment by ker0x** [comment]
Hello,

@vasilvestre are you going to work on this feature ? If not, i would like to try !

@xabbuh I have some questions about this features:

- does the `dir` attribute should be applied only on `input`/`textarea` or also on `label` and `button`?
- does the `dir` attribute should be displayed by default with it's value to `auto` or should we let people to choose if they want it or not ?

**Comment by vasilvestre** [comment]
I would like to make it my first contribution, could you let me two weeks
please? :D

As the article point, there's no reason to do not make it auto :)

Le lun. 14 mai 2018 à 18:44, Romain Monteil <notifications@github.com> a
écrit :

**Comment by vasilvestre** [comment]
Here's my first attempt : [https://github.com/vasilvestre/symfony/commit/1191103692678b4c452f912f9c97cdb162567bd7](url)
[https://github.com/vasilvestre/symfony/commit/ea65a46408ade92aa88aca805b9e5ecd9f19dad4](url)
I'm not sure my test have been tested by PHPUnit, I will try to get help on Slack !

**Comment by xabbuh** [comment]
@vasilvestre Can you make it a PR to the official Symfony repository? I nearly missed your attempt. 🙈

**Comment by vasilvestre** [comment]
@xabbuh I think the attempt do not work ! I'm not sure tbh, I could try again. I think I have to test it again, squash it then maybe make it a PR.
You are interested by this PR ?

**Comment by xabbuh** [comment]
If we can easily solve this feature request, I am all in to review such a PR. :)

**Comment by xabbuh** [comment]
According to the W3 the `dir` attribute is better suited in the `html` element of your HTML markup (see https://www.w3.org/International/questions/qa-html-dir) if your whole website follows the same direction. So I think we can safely close here then.

Thanks to @nevercodealone for investing some time into looking this up. 👍

**Comment by vasilvestre** [comment]
Nice so ! :)

**Comment by nevercodealone** [comment]
Here is my point:

As you see on the link the W3C  do not want to use multiple dir attributes. For my understanding you need to set <html dir="rtl"> on the top of your html markup.

There can be special cases like a language switcher dropdown. There you will add the dir attribute to the li element like <li dir="rtl">. This is to show a readable item for a arabic translation for example.

When i use the dir attribute on the html tag, everything on my page is right to left. This looks good. My slider crashes, but that is a problem with the slider. 

As you see on the offical visitabudhabi.ae they use very often the dir attribute. I think that is not a good use. In fact I do not have the usecase so far and can not say something about user experience. When you have better feedback please inform me it is a very nice topic.

Hope that helps.
