### ISSUE TITLE
JMS Serializer having problem loading it's annotations?

### ISSUE THREAD

**Issue by din-gi** [symfony/symfony#25555]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.2

I have problem with the load of JMS serializer,
I am using the jms bundle `"jms/serializer-bundle": "^2.3"` which states that it supports symfony 4^.

But still when ever I run my symfony command for the first time everything is good and the command which uses a class is ok:
```
<?php
/**
 * @copyright   2016 Oversell. All rights reserved
 * @author      Oversell
 *
 * @link        http://oversell.tk
 */

/**
 * Created by PhpStorm.
 * User: dinbracha
 * Date: 12/1/17
 * Time: 8:06 PM
 */

namespace MonitorBundle\Dto;

use \CoreBundle\Core\Errors;
use \CoreBundle\Utils\ValidationUtil;
use \CoreBundle\Exceptions\ValidationException;

use \JMS\Serializer\Annotation\Exclude;
use \JMS\Serializer\Annotation\Type;

class InventorySyncWorkerDto extends \CoreBundle\Dto\BaseWorkerDto
{
	/**
	 * @var string $loggerId
	 * @Type("string")
	 */
	public $loggerId;

	/**
	 * @var \MonitorBundle\ViewEntity\SyncApiAccessDataView $apiAccessData
	 * @Type("string")
         * @Exclude()
	 */
	public $apiAccessData;

	/**
	 * @var \CoreMarketplaceBundle\ViewEntity\MonitoredProductsView[] $inventory Full inventory of the store to sync (only monitored products)
	 * @Type("array<CoreMarketplaceBundle\ViewEntity\MonitoredProductsView>")
	 */
	public $inventory;

	/**
	 * InventorySyncWorkerDto constructor.
	 * {@inheritdoc}
	 */
	public function __construct(array $di = array(), array $props = array())
	{
		parent::__construct($di, $props);

		$this->workerType = \CoreBundle\Core\WorkerType::INVENTORY_SYNC;
	}
}
```

But after the symfony cache as warmed-up after running my command for the first time.

I run my command for the second time and I receive the following error:
```
string(160) "[Semantical Error] The annotation "@JMS\Serializer\Annotation\Exclude" in property CoreBundle\Dto\BaseDto::$request does not exist, or could not be auto-loaded."
```

There is no problem with the `Exclude` annotation.. because it also happens with the `Type` annotation of JMS serializer.

My Symfony 4.0.2 installation is from a fresh start (and not from an update).

For me it seems that the AnnotationRegistery in the cache doesn't load the JMS serializer annotations well.

As I stated - my command works well before warmup and after warmup of symfony's environment cache it breaks.

I have tried falling out over the code.. after checking composer autoload files which seems to load the files correctly, I decided to follow the symfony cache a bit, and the command (that uses the JMS serializer annotation) works well whenever I remove `srcDevDebugProjectContainer.php` which is related to the cache of the environment

Anyone has any clue?
Thanks

**Comment by iltar** [comment]
JMS is not in this repository, nor are the annotations:
 - https://github.com/schmittjoh/serializer
 - https://github.com/doctrine/annotations

Sounds to me like an issue related to the jms serializer though.

**Comment by din-gi** [comment]
Yes I know.. has noted.. this is not a problem due to JMS. this is a problem with Symfony which in it's cache directory doesn't load the annotations of JMS well..

I had no problem regarding this annotations with symfony 3 up until I fresh updated to symfony 4

**Comment by dinbrca** [comment]
after investigating deeper..

the following post solved my problem:
https://stackoverflow.com/questions/25937261/autloading-not-working-correct-using-autoloader-php-in-vendor-directory

on symfony 3.4 and lower adding the following line to the autoload.php solves the problem:
```
AnnotationRegistry::registerLoader('class_exists');
```

on symfony 4 the following line on the `srcDevDebugProjectContainer.php` file in the cache solves the problem:
```
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader('class_exists');
```
The problem with this is that the cache is reloaded every now and then.. so instead I decided to try the second solution which is having the following bundle:
`composer require indigophp/doctrine-annotation-autoload`

**Comment by iltar** [comment]
I'm not sure, but I think @nicolas-grekas does know a lot more about this than I do

**Comment by nicolas-grekas** [comment]
Jms should use the annotation reader service provided by Symfony, I think that's the issue (or it should register the annotation loader itself.)

**Comment by din-gi** [comment]
On the environment cache directory I have the following files:
<img width="946" alt="screen shot 2017-12-20 at 10 30 09 am" src="https://user-images.githubusercontent.com/29832557/34198890-8c38dd7e-e574-11e7-9526-1b99fee654a5.png">

Which files should I take a look regarding this annotation loader?

**Comment by xabbuh** [comment]
I am closing here as this looks like an issue that needs to be fixed in JMSSerializerBundle instead.
