### ISSUE TITLE
Session times  out like immediately  Symfony 3.3.9

### ISSUE THREAD

**Issue by zico4reel** [symfony/symfony#25560]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.3.9

Hi, please I need help,I have gone through several issues raised, but still no luck, i Have tried almost everything, looked elsewhere online still no solution, The issue my session sometimes logs me out immediately before i can even redirect to the session restricted area on login or after viewing one or two pages on the session restricted I get logged out, am doing this in dev mode

I have switched to using redis with snc session handler  for my session handling since am getting the issue with the native file session handler, based on what people said works for them, i switched from php5.6 to php7  yet still no luck. am running out of time right now, an application which should have been launched 3 days ago, has now extended because of this session issue.
PLEASE can someone help me out with it

**Comment by iltar** [comment]
Sounds like you have no permissions to write the sessions

**Comment by zico4reel** [comment]
@iltar Please its on my laptop am using window 10, how is  it that I don't have permission? am using redis and not the native file, switched since that didn't work, the support link doubt it will work being searching since yesterday

**Comment by Simperfit** [comment]
@zico4reel Could you please post a reproducer so we can see if we find a bug or another problem ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by zico4reel** [comment]
Thanks @Simperfit and Thanks to everyone that participated. I got a solution to my problem

**Comment by iltar** [comment]
Mind sharing your solution? In case someone has the same issue and ends up here.

**Comment by zico4reel** [comment]
Basically the person should try to setup using apache rather than using the default php in built server while in development.
