### ISSUE TITLE
Why ServiceSubscriberInterface uses only PSR-11-based service?

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#25561]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

Sometimes its not possible to use FQCN-based service names
```
/**
     * @inheritDoc
     */
    public static function getSubscribedServices()
    {
        return [
            'foo_client' => 'app.foo.http', // GuzzleHttp/ClientInterface
            'bar_client' => 'app.bar.http', // GuzzleHttp/ClientInterface
        ];
    }
```
```
Type error: Return value of ContainerEs491xr\srcDevDebugProjectContainer::{closure}() must be an instance of app.foo.http or null, instance of GuzzleHttp/Client returned
```

**Comment by stof** [comment]
ServiceSubscriberInterface is here to ask for a mapping between a local name and a *type*, not a local name and a name in the main container.

**Comment by stof** [comment]
not however that you can wire a ServiceLocator instance manually with the different clients in it.

**Comment by BoShurik** [comment]
> ServiceSubscriberInterface is here to ask for a mapping between a local name and a type

So it must be `TypeSubscriberInterface` :)

**Comment by nicolas-grekas** [comment]
> So it must be TypeSubscriberInterface :)

too bad this is too late, would have been worth discussing...
closing as there is no bug here, @stof is right.

**Comment by romainneutron** [comment]
So bad nobody mentioned an existing way to solve this issue :

```
    tags:
            - { name: container.service_subscriber, key: foo_client, id: 'container_foo_client_id' }
            - { name: container.service_subscriber, key: bar_client, id: 'container_bar_client_id' }
```
