### ISSUE TITLE
SF 3.4.2 Console commands infinity loop (after update from 3.4.1)

### ISSUE THREAD

**Issue by emodus** [symfony/symfony#25569]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.4.2 (production setup)

php version: PHP 7.1.12 (cli), CENTOS 7.4.1708

After upgrading symfony/symfony from 3.4.1 to 3.4.2 all commands are  executed from crontab  (every 1 min, every 15 min, every 1 hour, etc).

After some working time randomly and unpredictable commands start use maximum CPU resources, processes never end, need kill. 

Look like in SF core appears infinity loop (maybe its happen when application rise exception, but exception handler stuck in processing). 

https://github.com/symfony/symfony/compare/46d4a90...29961b6#diff-e7d086f2c2086fdb8f108e74f11dac5b

**Comment by Simperfit** [comment]
The diff you provided does not work, could you modify it or provide a reproducer ?

- Fork the [Symfony Standard Edition](https://github.com/symfony/symfony-standard)
- Do the minimum modification to reproduce the bug
- Post the link in here

In case you need some help you can read this blog post : https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by nicolas-grekas** [comment]
@emodus can you try with `3.4@dev`? I don't know why this is happening since 3.4.2, but since branch 3.4 contains several fixes already, maybe one could fix that? Otherwise a reproducer would be great (or better: some more debugging info you could inspect for us?)

**Comment by zorn-v** [comment]
Dear scientists. At me, which year, in a subfield happens underground knock. Please explain how it happens.

**Comment by Simperfit** [comment]
@emodus could you either try to use 3.4@dev or create a reproducer ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by emodus** [comment]
Hello,

My devops team also can not find any hint using `strace` whats wrong. 

@nicolas-grekas 
Few days ago we launched 3 new backends with php7.2 and `3.4.3`, same problem.

We can not reproduce also this case, just monitoring tells us that production poll backends starts using to much CPU and its only one way `kill -9 <PID>`.

Note: php-fpm works fine, but console commands sometimes hangs unpredictable and eat CPU resource infinite.

I have feelings that something crash on end of console life(error handling process, events - only standart). 

All commands just delegate logic for services  do certain tasks (process payments queues, rabbitMQ consumers), nothing special, with SF we are living from 2.7 version, this is first time that we can not sort this ghost issue...

**Comment by chalasr** [comment]
@emodus fixes have not been released yet. Could you try with `3.4@dev`?

**Comment by emodus** [comment]
@chalasr in production pool its not possible... in dev environment we also do not have any pattern how to reproduce.

We will try to thing tomorrow how to simulate in dev env with 3.4@dev.

**Comment by emodus** [comment]
I have feelings that previous console bug fix it could  give side affect.

https://github.com/symfony/symfony/compare/v3.4.1...v3.4.2#diff-e7d086f2c2086fdb8f108e74f11dac5bR600

`src/Symfony/Component/Debug/ErrorHandler.php`
handleFatalError while part

**Comment by chalasr** [comment]
v3.4.4 has been released, it embeds the fixes

**Comment by emodus** [comment]
@chalasr going to test it immediately.
