### ISSUE TITLE
env var APP_FRONT_CONTROLLER empty after upgrading from 3.3 to 3.4 (the same issue is on fresh 3.4 installation)

### ISSUE THREAD

**Issue by skornev** [symfony/symfony#25575]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.4.2

 PHP 7.0.19-1 
After upgrading from 3.3 to 3.4 (even on a fresh installed symfony 3.4) there is no way to start application. The webserver returns 500 error. The problem is that APP_FRONT_CONTROLLER env variable 
 is empty.

```
 bin/console -vvv server:run 0.0.0.0:8000
PHP Warning:  require(index.php): failed to open stream: No such file or directory in vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php on line 42
[Thu Dec 21 13:28:03 2017] PHP Fatal error:  require(): Failed opening required 'index.php' (include_path='.:/usr/share/php') in vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php on l
```

**Comment by nicolas-grekas** [comment]
Fixed by #25523, will be in next release.
