### ISSUE TITLE
Redirection loop after validate redirect targets - Logging in to a different domain

### ISSUE THREAD

**Issue by tjurdzinski** [symfony/symfony#25572]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Symfony version  | 3.2.13 and never

After this change: https://github.com/symfony/symfony/commit/52b06f1c21c69a4557ab3716afe56dea4815dfdf#diff-76577aed100434c043a441fee636edad

I have a problem with redirection to a login page that is under a different domain. 
Regex detects a different domain in login path and sets up a cookie domain redirection.
The result is a redirection loop.

The problem would be solved by adding a trusted domain for login page.
I understand that it increases security but in some situations it is a breaking change.

**Comment by xabbuh** [comment]
Could you set up a small example project that allows to reproduce your issue?

**Comment by Warxcell** [comment]
I had same problem. I had user.example.com and login was at example.com. I had to set cookie domain to '.example.com' in order to have proper redirect.

**Comment by fabpot** [comment]
@Warxcell is correct. Closing as this is not a bug.
