### ISSUE TITLE
Writing functional tests outputs logs in tests since 3.4

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#25570]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4

When using a kernel, booting it and fully running it, logging is now on by default and outputting everything on your console. This means that in every kernel I define, I'll have to add the following line of configuration:
```php
$container->register(NullLogger::class)->setDecoratedService('logger');
```

This issue is quite annoying as it garbles up the entire phpunit output, even when tests succeed. While I can understand that it might be nice for console apps to display this by default, I'm not interested in output like this when running tests (and nothing goes wrong).

**Comment by xabbuh** [comment]
If you turn down the shell verbosity (like done here: https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/3.3/phpunit.xml.dist#L16), you should only see errors.

**Comment by iltar** [comment]
It's still a manual step that I have to take between 3.3 and 3.4. I expect this to be backwards compatible and throw a deprecation if I don't pass it. For 4.0 it's fine.

**Comment by nicolas-grekas** [comment]
You need to change SHELL_VERBOSITY in phpunit.xml, as done here:
https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/3.3/phpunit.xml.dist#L16

**Comment by iltar** [comment]
@nicolas-grekas I'm aware of that for 4.0, but for 3.4 it should remain unchanged, should it not? Extra output is imo a change of behavior and thus a BC break.

**Comment by Pierstoval** [comment]
By the way, using SHELL_VERBOSITY will still show the errors. If one expects a 404 exception, for example, it'll be shown in the console output.

Only solution is to use a NullLogger, I'm not sure it's the best option though 😕

**Comment by iltar** [comment]
So this is also causing a lot of issues in commands with monolog:

```yaml
monolog:
    handlers:
        console:
            type: console
```

Even when using the `--raw` it's being displayed, which makes it 100% useless right now.

![image](https://user-images.githubusercontent.com/1754678/34611795-308660ea-f227-11e7-88c6-8aa17c3fefc4.png)

```php
if ($this->debug && !isset($_ENV['SHELL_VERBOSITY']) && !isset($_SERVER['SHELL_VERBOSITY'])) {
    putenv('SHELL_VERBOSITY=3');
    $_ENV['SHELL_VERBOSITY'] = 3;
    $_SERVER['SHELL_VERBOSITY'] = 3;
}
```

**Comment by iltar** [comment]
The above issue can be disregarded, this seems to be an edge-case when the kernel is booted before the application run is called.

**Comment by iltar** [comment]
Closing this as it doesn't affect me anymore
