### ISSUE TITLE
Simple Cache - cannot set non-expiring entry when a cache has a default lifetime.

### ISSUE THREAD

**Issue by alex-billetsca** [symfony/symfony#25586]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

When a cache has a default lifetime it seems impossible to set a non-expiring entry (no ttl).

The Symfony\Component\Cache\Traits\RedisTrait supports 0 as a ttl for non-expiry:
```
               if (0 >= $lifetime) {
                   yield 'set' => array($id, $value);
               } else {
                   yield 'setEx' => array($id, $lifetime, $value);
               }
```

But when the ttl gets normalized Symfony\Component\Cache\Simple\AbstractCache:
```
       if (null === $ttl) {
           return $this->defaultLifetime;
       }
       if ($ttl instanceof \DateInterval) {
           $ttl = (int) \DateTime::createFromFormat('U', 0)->add($ttl)->format('U');
       }
       if (is_int($ttl)) {
           return 0 < $ttl ? $ttl : false;
       }
```

There is no logic allowing the 0. (The int ttl -> false return flags a delete)

**Comment by nicolas-grekas** [comment]
Actually I think this is expected by PSR6/16. There's no way to express infinite TTL per the standard.
So the only way is either to set a very long TTL, or configure the adapter to default to "infinite" TTL by setting defaultLifetime to zero (the constructor is not covered by the PSR so this is not violating it)

**Comment by nicolas-grekas** [comment]
Closing as explained. We're bound to a standard and that a strength :)
