### ISSUE TITLE
Following the Databases and the Doctine ORM guide results in an SQL error

### ISSUE THREAD

**Issue by stevespages** [symfony/symfony#25587]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

I created a new Symfony 4 skeleton project and carefully followed the Databases and Doctrine ORM guide up to the following command:

steve@Dell ~/doctrine-guide $ php bin/console doctrine:migrations:migrate
                                                              
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20171222115257 from 20171222114317

  ++ migrating 20171222115257

     -> ALTER TABLE product ADD COLUMN description CLOB NOT NULL
Migration 20171222115257 failed during Execution. Error An exception occurred while executing 'ALTER TABLE product ADD COLUMN description CLOB NOT NULL':

SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
2017-12-22T11:56:28+00:00 [error] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE product ADD COLUMN description CLOB NOT NULL':

SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL"

In AbstractSQLiteDriver.php line 89:
                                                                                                     
  An exception occurred while executing 'ALTER TABLE product ADD COLUMN description CLOB NOT NULL':  
                                                                                                     
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL             
                                                                                                     

In PDOConnection.php line 106:
                                                                                          
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL  
                                                                                          

In PDOConnection.php line 104:
                                                                                          
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL  
                                                                                          

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

steve@Dell ~/doctrine-guide $ nano src/Migrations/Version20171222115257.php 
steve@Dell ~/doctrine-guide $ php bin/console doctrine:migrations:migrate
                                                              
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20171222115257 from 20171222114317

  ++ migrating 20171222115257

     -> ALTER TABLE product ADD COLUMN description CLOB

  ++ migrated (0.04s)

  ------------------------

  ++ finished in 0.04s
  ++ 1 migrations executed
  ++ 1 sql queries
steve@Dell ~

I did get the database to be created by editing the src/Migrations/Version20171222115257.php file. I removed the NOT NULL after CLOB. I suspect this is a bug or error in the documentation but cant rule out that I did not follow the guide as carefully as I thought, Steve

**Comment by mvrhov** [comment]
This has nothing to do with Symfony. You posted this into the wrong issue tracker.

**Comment by stevespages** [comment]
Can you advise which issue tracker would be the correct one?

**Comment by cybernet** [comment]
https://github.com/doctrine/doctrine2 :)

**Comment by carnau** [comment]
Anyway, before adding a new issue in the doctrine project check that you added the correct annotation information. I've tried this and works as expected, description is defined as text and the migration should try to create a LONGTEXT field instead CLOB.

**Comment by Tobion** [comment]
Closing as not related to symfony.

> Cannot add a NOT NULL column with default value NULL

Btw this seems quite self-explaining. There is an option called default on columns that you can set.
