### ISSUE TITLE
Set custom project dir

### ISSUE THREAD

**Issue by brucepc** [symfony/symfony#25590]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

With this feature we can write a functional application test to some library/SDK in development in another path (e.g. tests/Application).

```json
//composer.json
{
    "..." : "...",
    "extra" : {
        "..." : "...",
        "symfony-project-dir" : "tests/Application"
    }
}
```

**Comment by xabbuh** [comment]
What would be the difference compared to overwriting the `getProjectDir()` method of the kennel?

**Comment by brucepc** [comment]
When we install the bundles to create a basic symfony application into some subtree of project, the [Symfony/Flex](https://github.com/symfony/flex) copy/create/update files into project dir, files such as bundle.php and configuration files. In case of a test application, the path is not the same of the compose.json file, where they aways create/update/copy the files specified into the respective [recipes](https://github.com/symfony/recipes) bundle.

**Comment by xabbuh** [comment]
I am not sure if I understand what problem you want to solve. Can you give a more concrete example?

**Comment by brucepc** [comment]
Let's assume that the lib is all in ```src/``` my application test should be created in ```test/Application/```
to create the test app we have to install ```symfony/framework-bundle``` and some others bundles

To enable symfony flex we execute
```
composer require symfony/flex --dev
```

To add the basics bundles to symfoy 4 app we execute
```
composer require framework-bundle --dev
```
After that Symfony Flex has already configured some files into project path as the same path as composer.json.
```
 |- src   
 |   |- Controller
 |   |- Kernel.php
 |   |- .... lib files ...
 |- tests
 |   |- Behat
 |   |- Unit   
 |- config   
 |- public   
 |- vendor   
 |- composer.json   
 |- composer.lock   
 |- symfony.lock   
 |......   
```

We want to have the chance to change those project path to ```tests/Application``` instead of the 
same path as project.
to looks like bellow  
```
 |- src   
 |   |-.... lib files ...
 |- tests   
 |   |- Application
 |   |   |- src
 |   |   |   |- Controller
 |   |   |   |- Kernel.php
 |   |   |- config   
 |   |   |- public   
 |   |   |- symfony.lock   
 |   |- Behat
 |-vendor   
 |-composer.json   
 |-composer.lock   
 |......   
```

**Comment by xabbuh** [comment]
Thanks for the example. I think I now understand what you want to achieve. However, this is something that needs to be done in Flex and we already have an issue for this. So I am going to close here in favour of symfony/flex#196.
