### ISSUE TITLE
[RFC][DependencyInjection] Allow set DI attributes using annotations

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#25592]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

For the now we could create class that implements some specific interface and created service automatically will be tagged with DI tag. Also new service could recieve other services via constructor. 0-line configuration. 

But what to do if we want set some specific attribute, like `priority`? We should create configuration files and explictly define our service.

It would be nice provide some syntax like:

```php
/**
 * @TagAttribute("priority", 128)
 */
class SomeDataProvider implements DataProvider
{

}
```
This would allow do not create config file with explict service definition.

But there is another problem: if new service implements multiple interfaces (`Encoder`/`Decoder`) and we need different priorities for each interface.

**Comment by nicolas-grekas** [comment]
Starting with just tag attributes will end up calling for full DI configuration in annotations.
I think DI configuration in annotations has been rejected in the past.
I'm personally :-1: as this is not the proper place to do DI configuration IMHO.

**Comment by Koc** [comment]
> Starting with just tag attributes will end up calling for full DI configuration in annotations.
🤣 cann't disagree with you.

We already have `ServiceSubscriberInterface::getSubscribedServices()`, `EventSubscriberInterface::getSubscribedEvents()`, what about adding something similar for autoconfiguration: `AutoconfiguredServiceInterface::getAutoconfiguration()`?

```php
class SomeDataProvider implements Encoder, Decoder, AutoconfiguredServiceInterface
{
    public static function getAutoconfiguration()
    {
        return [Encoder::class => ['priority' => -100]];
    }
}
```

**Comment by nicolas-grekas** [comment]
@Koc not really the same: `ServiceSubscriberInterface` and `EventSubscriberInterface` add meta-information to the inner working of the classes implementing them. DI uses that added semantic to help wire them.
But `AutoconfiguredServiceInterface` would not be of the same kind - it wouldn't help know more about the current class independently of how it is wired. Instead, it just tells how to wire it. i.e. it's configuration via static data. Not better than configuration via annotations IMHO again...

**Comment by Koc** [comment]
Agree that `ServiceSubscriberInterface` really about how to it is wired. But `EventSubscriberInterface` about how to wire subscriber:

```php
    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::REQUEST => array(array('onKernelRequest', /* priority */ 32)),
            KernelEvents::FINISH_REQUEST => array(array('onKernelFinishRequest', 0)),
        );
    }
```

**Comment by iltar** [comment]
Seems heavily related to an issue I have: #25327
