### ISSUE TITLE
Allow Custom Request object with Guard Authenticator

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/symfony#25607]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.2

We can [override the request](http://symfony.com/doc/current/components/http_foundation.html#overriding-the-request) - that's great.

For example, one would simply extend symfony base request class.

```php
<?php

namespace App\Component\HttpFoundation;

use Symfony\Component\HttpFoundation\Request as BaseRequest;

class Request extends BaseRequest {

    /**
     * @return bool true if it is an Api request, false otherwise.
     */
    public function isForApi()
    {
        $path = $this->getPathInfo();

        return (strpos($path, '/api/') === 0);
    }

}
```

However, is doesn't seem possible yet to use that custom request when implementing a `LoginFormAuthenticator` as it extends [AbstractFormLoginAuthenticator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Guard/Authenticator/AbstractFormLoginAuthenticator.php)

![image](https://user-images.githubusercontent.com/1480617/34371015-69489350-eb1d-11e7-8f30-88e7f9981114.png)

Wouldn't it be great to use our own custom request too?

**Comment by xabbuh** [comment]
Well, this is simply how PHP works. By following the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle) you cannot restrict the argument type of a method in a child class. What you would have to do is not changing the type hint but throw an exception instead if the given object is not an instance of your custom request class. I am closing here as there is nothing to do here on Symfony's side.
