### ISSUE TITLE
Can't install symfony properly

### ISSUE THREAD

**Issue by Dmytro4** [symfony/symfony#25602]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | ?
| Symfony version  | 4.0.4

Mine installation log is - https://gist.github.com/anonymous/92753a558b7532694b84b84cee472f30
Normal installation log is - https://gist.github.com/tarlepp/3f64633c4c4dc98df1cd43b90dfb26d2

My installation creating only "Vendor" folder but it should be more.
In my log "Installing dependencies (including require-dev) from lock file" already said than stuff going from lock file but in normal log there is only "Updating dependencies (including require-dev)" and then going "Writing lock file" but in mine not.

Normal log - is log from normal installation. I tried to install composer and symfony with same win/php/apache versions just on different machines. Please help! I just can't start even use of symfony.

**Comment by ostrolucky** [comment]
You should create this issue on [symfony/flex](https://github.com/symfony/flex)

**Comment by ostrolucky** [comment]
Make sure composer version is up to date

**Comment by Dmytro4** [comment]
it is, v1.5.6

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
