### ISSUE TITLE
Twig extensions without autowiring

### ISSUE THREAD

**Issue by petforsberg** [symfony/symfony#25600]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

I get the "Cannot autowire service method "__construct()" must have a type-hint or be given a value explicitly" error.

I created a Twig Extension which requires injecting my own service before (in other words, Twig extension is a wrapper for my own, general use service). I don't use autowiring for my own services for now. And this lack of autowiring seems to cause an error.

It seems that Symfony 4 looks **_first_** for automatic load of Twig Extensions, and **_then_** for my own services. But perhaps it should be the other way around. Because I have given the explicit config in the services.yaml file, as seen here:

    app.my_helper:
        class: App\MyHelper
        autowire: false
        public: true

    app.twig.extension.my_helper:
        class: App\Twig\MyHelper
        autowire: false
        arguments:
            - '@app.my_helper'
        tags: [twig.extension]

**Comment by nicolas-grekas** [comment]
I think you'd need to disable autoconfiguration, thus use `autoconfigure: false` instead.

**Comment by petforsberg** [comment]
Am I forced to do this for the whole app?

Because when I add the "autoconfigure: false" to the services, the error still appears. And when I put it under the _defaults section, the app works, but I guess I won't be able to use the autoconfiguration option in future...

    # with disabling "autoconfigure" for the whole app in the services.yaml, the app works
    _defaults:
        autowire: true
        autoconfigure: false

**Comment by unckleg** [comment]
You can define it per service.

**Comment by javiereguiluz** [comment]
@petforsberg is the problem solved if you make this change?

```diff
app.twig.extension.my_helper:
    class: App\Twig\MyHelper
    autowire: false
+   autoconfigure: false
    arguments:
        - '@app.my_helper'
    tags: [twig.extension]
```

**Comment by Koc** [comment]
I also had similar problem recently but in another component, not in twig. And my service was added twice: first autoconfigured without any constructor args, second passed from `services.yaml`, relates to #25594

**Comment by xabbuh** [comment]
Can one of you create a small example project that allows to reproduce your issue?

**Comment by Koc** [comment]
of course, will try, but not at this week.

**Comment by nicolas-grekas** [comment]
I'm closing here as AFAIK there is no bug.
@Koc please open separate issue with reproducer if you found any.

**Comment by petforsberg** [comment]
Well, defining by a service (assuming autoconfigure setting to false) won't work if you want a global autoconfigure set to true.

**Comment by xabbuh** [comment]
What do you mean with a global autoconfigure?

**Comment by petforsberg** [comment]
I mean _defaults, as above:

_defaults:
    autoconfigure: false

**Comment by xabbuh** [comment]
Sorry, I don't follow. Can you give a more detailed example of what you tried but didn't work?

**Comment by petforsberg** [comment]
Sorry for the late reply.

This is setting in the `/config/services.yaml`:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

This is what I meant as "global", because all the services in the app are by default treated by Symfony as autowired and autoconfigured.

But my understanding is that when I for example disable these features for a single service, like a Twig Extension, Symfony should skip it when looking for the services to configure... But it turns out Symfony doesn't do it - it seems to _first_ look for the autoconfiguring services, and then "takes into account" the config in my services configured as follows:

    app.my_helper:
        class: App\MyHelper
        autowire: false
        public: true

    app.twig.extension.my_helper:
        class: App\Twig\MyHelper
        autowire: false
        arguments:
            - '@app.my_helper'
        tags: [twig.extension]

**Comment by xabbuh** [comment]
If you do not use the class name as the service id, you will end up with two services for the same class. One is registered automatically for you by the PSR-4 based discovery (and this one will still be autoconfigured) while only your manually wired service is not autoconfigured. The easiest solution is to use the class name as the service id and thus overwrite the automatically discovered service.

**Comment by petforsberg** [comment]
How about letting Symfony do the work regardless the chosen by a dev format? I.e. to be consistent with any format?

**Comment by petforsberg** [comment]
"This avoids having to implement a logic converting the class name to a different id"

Why not? I mean, it worked well before in Symfony 2 and 3, why to ignore this ability to use the general id name in the project, as this allows to replace different classes and still use the service with the same name, i.e. allowing avoiding hunting down all the references to classes when changing it to another one?

**Comment by xabbuh** [comment]
Well, you can still use custom IDs. It's just that the PSR-4 discovery uses class names as ids and thus you need to replace services named this way or exclude some classes that you do not want to have registered this way.
