### ISSUE TITLE
Security component should explain when logout user

### ISSUE THREAD

**Issue by ebuildy** [symfony/symfony#25613]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 4.0.2

``ContextListener`` (https://github.com/symfony/security/blob/master/Http/Firewall/ContextListener.php#L176) should give a reason why the token is cleaned, I think something in the session like ``_security.logout_reason``.

So the application could handle this kind of logout more user friendly by displaying a message "You have been disconnected because you have changed your password".

Also, that could help developers to setup properly the security (by reading https://symfony.com/doc/current/security/entity_provider.html until the end ^^).

**Comment by abzolv** [comment]
I think this is a very good idea.

**Comment by iltar** [comment]
I agree, this was something I tried to solve when fixing the logout issue, but I couldn't come up with anything decent enough. My own idea back then was to set it the same way as the authentication errors, meaning you don't have to change the front-end to get the last authentication error.

https://github.com/symfony/security/blob/930ab82d4485e83ab3f05c09c62afd3d5651267b/Http/Authentication/AuthenticationUtils.php#L38

**Comment by abzolv** [comment]
If this feature is approved, would you please also add it to V3.4?

**Comment by iltar** [comment]
New features go into 4.1, unless it's considered a bug fix (which I doubt).

**Comment by abzolv** [comment]
An alternative solution could be for the framework to simply emit an event before automated logout, so that the application can subscribe to the event and then do whatever user-friendly stuff it wants to do.

**Comment by ebuildy** [comment]
hello @iltar , you are right, I forgot this thing. So I have just to feed ``Session[Security::AUTHENTICATION_ERROR]`` actually, this makes sense.

Do you want I make a PR or something more complex is planed by the team?

Thanks you,

**Comment by iltar** [comment]
If you wish, you can make a PR, I think it's a good idea from a UX perspective and I think the core team will agree. The PR itself shouldn't be hard, but just make sure it's backwards compatible and that the target branch is the master (4.1) for now.

**Comment by Simperfit** [comment]
@ebuildy Do you have time to work on this ?

**Comment by ebuildy** [comment]
Maybe tomorrow, I keep you posted here.

**Comment by ebuildy** [comment]
I have done this: https://github.com/symfony/symfony/compare/master...ebuildy:issue/25613-security-logout?expand=1

**Comment by Simperfit** [comment]
You need to add tests and to create the pull request if not already done.

**Comment by vivekaviva** [comment]
What Path i should give for logout button using symfony 4

**Comment by Simperfit** [comment]
@ebuildy what is the status of this ?

**Comment by ebuildy** [comment]
Hello, no time/skills enough to make it happens :/

**Comment by Simperfit** [comment]
Since we have now an event for automated logout, is this really needed ? cc @linaori @chalasr

**Comment by linaori** [comment]
The event can be used to display the message if needed, so I suppose we can close this?

**Comment by Simperfit** [comment]
I agree.

**Comment by xabbuh** [comment]
closing then
