### ISSUE TITLE
[Security] Form authentication throws error on non string username

### ISSUE THREAD

**Issue by zlikavac32** [symfony/symfony#25612]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

`\Symfony\Component\Security\Http\Firewall\UsernamePasswordFormAuthenticationListener` trusts that submitted data will contain string as username.

In case that provided data is array, `trim` (that's used on the input values) will throw `trim() expects parameter 1 to be string, array given` which results in a 500 status code.

Simple CURL that causes this behaviour would look like this:

```
curl \
    'http://127.0.0.1:8080/app_dev.php/login_check' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    --data '_username%5Bname%5D=user&_password=pass'
```

One quick solution would be to cast before passing to `trim` but perhaps some use of validator component would be a better approach?

**Comment by ebuildy** [comment]
I am wondering why the ``Form`` firewall from ``Security`` component is not using a Symfony form? (to take advantage of Form validation etc...)

**Comment by chalasr** [comment]
The username must be a string here. The only relevant change would be to throw an exception for DX but I'm not sure it's worth it, let's see what others think.

**Comment by xabbuh** [comment]
Well, I agree so far that the user should not be able to cause an internal server error by submitting malformed data. It's not too critical, but since you will probably treat 5xx errors in production differently than client errors, we should IMO still fix this.

**Comment by chalasr** [comment]
See #25657

**Comment by acasademont** [comment]
Yes please, full stack traces for this errors are unnecesary

**Comment by nCrazed** [comment]
Is error response on `null` username (happens when username parameter is not inclued in the request body) intended?

We have a set of sanity tests for all of our routes (using PHPUnit's `@dataProvider`) that ensure that certain user types are allowed to make requests to specific URLs: 

```php
$this->assertFalse($response->isServerError(), $message);
$this->assertFalse($response->isClientError(), $message);
```
This change breaks our ability to point a guest `Client` instance at /login without specifying post data for the request because `POST /login` without a request body will now fail due to a `400` response.
