### ISSUE TITLE
PHPUnit Test header already send by "phpunit-5.7/src/Util/Printer.php"

### ISSUE THREAD

**Issue by rehoehle** [symfony/symfony#25615]
| Q                           | A
| ----------------- | -----
| Bug report?          | yes
| Symfony version  | 3.4.1
| PHPUnit                | 5.7.26

I have a problem after the upgrade to symfony 3.4. I have a login in my unit test. I've implemented the login like the documentation describes here:

https://symfony.com/doc/current/testing/http_authentication.html

I use that code for years now and before 3.4 is was working well. 

```php
$session = $client->getContainer()->get('session');
$token = new UsernamePasswordToken($testUser, $testUser->getPassword(), $firewall, $roles);
$session->set('_security_'.$firewall, serialize($token));
$session->save();

$cookie = new Cookie($session->getName(), $session->getId());
$client->getCookieJar()->set($cookie);
```
if i run the phpunit command over the bridge. I get the following error:

```bash
#bin/simple-phpunit
1) Tests\APIBundle\Controller\AutoresponderApiControllerTest::testAutoresponderInsAPI
RuntimeException: Failed to start the session because headers have already been sent by "/xxxx/.phpunit/phpunit-5.7/src/Util/Printer.php" at line 110.

/xxx/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:141
/xxx/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:302
/xxx/vendor/symfony/http-foundation/Session/Session.php:260
/xxx/vendor/symfony/http-foundation/Session/Session.php:80
/xxx/tests/MainBundle/ExtendedWebTestCase.php:151
/xxx/tests/MainBundle/ExtendedWebTestCase.php:62
```

without the lines with the login it's working.

**Comment by sroze** [comment]
Can this be a duplicate of https://github.com/symfony/symfony/issues/24524 ?

**Comment by rehoehle** [comment]
It looks similar. I've testet die options in the ticket with APP_ENV=test but it's already in my PHPUnit XML file. There should be a fix merged to 3.4 it's a bit strange. Perhaps i've made something wrong but i've tried not a lot to find the problem.

**Comment by sstok** [comment]
FYI. PHPUnit doesn't (by default) overwrite env variables that are already set. You can use the force="true" option to force this (requires PHPUnit v6.3 - sebastianbergmann/phpunit#2723)

**Comment by rehoehle** [comment]
I've tested my case with PHPUnit 6.3 but same error. The Printer print the buffer on the line 110 and then you have an output before the session is started.

**Comment by FlorianKromer** [comment]
Symfony version | 4.0.2
-- | --
PHPUnit | 6.5



I had got the same error, solved by enabling : session.storage.mock_file
**config/packages/tests/framework.yml**
```
framework:
    test: ~
    # Uncomment this section if you're using sessions
    session:
       storage_id: session.storage.mock_file
```

**Comment by rehoehle** [comment]
@FlorianKromer ok yes that works. Perhaps some should add a note to the documentation.

**Comment by sroze** [comment]
@rehoehle that would be nice. Maybe you could submit a PR on the symfony-docs repository, to add a quick note where you believe it would be the best?

**Comment by sroze** [comment]
The issue can be closed, right?

**Comment by rehoehle** [comment]
Yes thx i can change the documentation.

**Comment by buba71** [comment]
Great ! Thanks

**Comment by slk500** [comment]
can I also set this option on dev env? Without any consequence?

**Comment by fmonts** [comment]
If you struggle with this in 2021, in my case `packages/test/framework.yaml` isn't read (why?), you have to add/uncomment this in `packages/framework.yaml`:

```
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```
