### ISSUE TITLE
Warning: require(index.php): failed to open stream: No such file or directory in C:\www\myproject\vendor\symfony\symfony\src\Symfony\Bundle\WebServerBundle\Resources\router.php on line 42

### ISSUE THREAD

**Issue by AmineBelais** [symfony/symfony#25625]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.2

After installing **Symfony 3.4.2** and starting the built-in server (server:run) (on Windows 10, **PHP 7.0.10**) and navigating to 127.0.0.1:8000, results in this errror:

> Warning: require(index.php): failed to open stream: No such file or directory in C:\www\MyProject\vendor\symfony\symfony\src\Symfony\Bundle\WebServerBundle\Resources\router.php on line 42

> Fatal error: require(): Failed opening required 'index.php' (include_path='.;C:\php\pear') in C:\www\MyProject\vendor\symfony\symfony\src\Symfony\Bundle\WebServerBundle\Resources\router.php on line 42

The same project and version seems to run smoothly on Linux but not Windows!

**Comment by nicolas-grekas** [comment]
Should be fixed already on 3.4@dev
