### ISSUE TITLE
[Form][Bootstrap 4 template] btn class is duplicated

### ISSUE THREAD

**Issue by jgrygierek** [symfony/symfony#25638]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

Hi, the "btn" class is added twice, if button is rendered in form type class.

![obraz](https://user-images.githubusercontent.com/3065409/34457204-29ecc714-edaa-11e7-9690-356b0c96cd59.png)

**Comment by xabbuh** [comment]
Can you show some code that you used that led to this result?

**Comment by jgrygierek** [comment]
Sorry, after more digging it seems to be my mistake (caused by template inheritance inside my custom template).
