### ISSUE TITLE
[Form][Bootstrap 4 template] form-control class is duplicated

### ISSUE THREAD

**Issue by jgrygierek** [symfony/symfony#25635]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

Hi, the "form-control" class is added twice.

![obraz](https://user-images.githubusercontent.com/3065409/34456387-08b5116a-ed95-11e7-8e25-9db9c997d6fc.png)

**Comment by xabbuh** [comment]
Can you show some code that you used that led to this result?

**Comment by jgrygierek** [comment]
Config:
```
twig:
    form_themes:
        - bootstrap_4_layout.html.twig
```

Form type class:
```
$builder
    ->add( 'username', TextType::class)
    [..]
;
```

View:
```
{{ form_start(form) }}
    {{ form_rest(form) }}
    <div class="form-group">
        <button class="btn btn-primary btn-lg w-100">{{ 'form.action.register'|trans({}, 'forms') }}</button>
    </div>
{{ form_end(form) }}
```

And my bad - duplication only appears, if field has validation error.

**Comment by xabbuh** [comment]
Are you sure this is not caused by the same as #25638?

**Comment by jgrygierek** [comment]
No, I disabled my custom boostrap template and this error still exists.

**Comment by xabbuh** [comment]
maybe related to #24802

@ostrolucky Would you like to take a look at it?

**Comment by ostrolucky** [comment]
I can confirm this issue. Nevertheless, it's pretty insignificant.

It's not worth to work more on these templates until there is main bootstrap 4 release, only then we can be sure stuff won't have to be re-done.

status: reviewed

**Comment by xabbuh** [comment]
Bootstrap 4 is stable now

**Comment by ostrolucky** [comment]
This may be solved by https://github.com/symfony/symfony/pull/25715
