### ISSUE TITLE
After filter and handleRequest() issue

### ISSUE THREAD

**Issue by ch22843** [symfony/symfony#25658]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.4.2

Hi. I have a edit form and event subscriber. Event subcriber executing after controller method executed.

[https://symfony.com/doc/3.4/event_dispatcher/before_after_filters.html](url)

I am resetting user roles in this event.

`$user = $person->getUser();`
 `$user->setRoles(['ROLE_USER']);`
`$this->entityManager->persist($user);`
`$this->entityManager->flush();
`

and edit method look like this:

`$form = $this->createForm(ProjectType::class, $project, [
            'action' => $this->generateUrl('projects.edit', ['id' => $id])
        ]);`

`$form->handleRequest($request);`

`if($form->isSubmitted() && $form->isValid())`
`{`
`// to do`
`}`

i post empty data ( i have constraint NotBlank()) and it return 'This value should not be blank' message. But entity get update.

I think 
`$form->handleRequest($request);`
persist entity and when event subscriber execute its get update.

What can i do?

I hope you understood my english :)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
