### ISSUE TITLE
Form extension back compatibility broken at 3.4

### ISSUE THREAD

**Issue by Avariya** [symfony/symfony#25659]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | nope?
| Symfony version  | 3.4.2

Hi, vendor I using expected that `twig.form.renderer` service is implementing `TwigRendererInterface`. It was removed at Symfony4 and marked as deprecated at 3.4.
But at Symfony 3.4 already FormRendererInterface implementation was received. So, now I need to change expected type, what brakes BC with 3.*,
So, my request is to let `twig.form.renderer` implement `Symfony\Bridge\Twig\Form\TwigRendererInterface` at Symfony3.4 only.

Vendor lib: 
https://github.com/genemu/GenemuFormBundle/pull/446/files
https://github.com/genemu/GenemuFormBundle/blob/master/Resources/config/twig.xml

IMHO, the bug should be fixed at Symfony 3.4 side. Am I right?

Related issue: https://github.com/symfony/symfony/issues/24616

**Comment by Avariya** [comment]
Related: https://github.com/symfony/symfony/issues/24616

**Comment by dmaicher** [comment]
If we revert the service definition change on 3.4 (so keep using the deprecated `TwigRendererInterface`) then it might be fine for all people who expect an instance of `FormRendererInterface`.

An issue is that the twig runtime would also change again and possibly introduce problems again for projects that adapted to the non-deprecated class.

See https://github.com/sonata-project/SonataAdminBundle/issues/4758

What do you think @Tobion @nicolas-grekas ? Should we try to fix this on 3.4? Or do we allow this BC break?

Maybe we can somehow have both runtimes?

So

```php
$twig->getRuntime('Symfony\Bridge\Twig\Form\TwigRenderer')
```

and

```php
$twig->getRuntime('Symfony\Component\Form\FormRenderer')
```

will work?

**Comment by nicolas-grekas** [comment]
@dmaicher if you want to give it a try, please do. The less BC break the better (reverting a BC break is a BC break as you said, so we should be careful, and select the best middle ground, if any)

**Comment by dmaicher** [comment]
@nicolas-grekas I had some time to check it and proposed a PR: https://github.com/symfony/symfony/pull/26553

If you have time please have a look :wink:
