### ISSUE TITLE
Bootstrap 4 layout - MoneyType bug

### ISSUE THREAD

**Issue by andrzejpakula** [symfony/symfony#25655]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

Hi. In new bootstrap 4 layout,  input-group-addon class does not exist. Instad of this, you should use 'input-group-prepend' and 'input-group-text' . Please  looks it https://getbootstrap.com/docs/4.0/components/button-group/ . Actually money type widget template does not show correctly  currency. Sorry for my bad english. Best Regards.

**Comment by ostrolucky** [comment]
That's a change in bootstrap 4 beta 3. Current template was optimized for bootstrap 4 beta 2. I recommend downgrade to bootstrap beta 2, until there is support for more recent version.
