### ISSUE TITLE
Uninstalling Encore removes your package.json and Webpack config

### ISSUE THREAD

**Issue by szymach** [symfony/symfony#25651]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3+

I have been using Webpack for a while now, so I have decided to give the Encore bundle a try. After some tinkering I have decided against using it and have removed it via composer (with Flex). To my surprise, I have found that both my `package.json` and `webpack.config.js` files have been deleted as well. Now I know that Flex is supposed to help with cleanup (which I approve of), but in this case it deletes files that can be used without the related bundle and it does it without even informing you. It would be nice to either have a prompt for deleting these or at least a console output with a list of deletions.

Cheers.

**Comment by ostrolucky** [comment]
related: https://github.com/symfony/flex/issues/213

**Comment by javiereguiluz** [comment]
@szymach as @ostrolucky showed, this is the expected behavior. I know it may be surprising at first but Flex installation/uninstallation is symmetric, so uninstalling something removes all files/dirs created during its installation.

In theory this may sound even dangerous ... but in practice this should be safe because it should be impossible for a real application to not use Git or similar to avoid losing information.

**Comment by szymach** [comment]
Well it also removes files which were not created during installation. Is there no option to list created / deleted files with for example the `--verbose` flag? Manually checking which files it removed or added via `git status` does not seem very elegant.

**Comment by fabpot** [comment]
@szymach Which files were removed that were not installed? If there are some, it might be a bug.

**Comment by szymach** [comment]
@fabpot what I meant is that these files (`package.json` and `webpack.config.js` existed prior to me using Webpack Encore and were removed anyway. I understand the limitation of the tool, what I ask for is more information on what is being done.

**Comment by fabpot** [comment]
Ah, ok, understood. Well, being more verbose when using `-v` is certainly possible. Would you like to try making the needed changes in Flex?

**Comment by szymach** [comment]
Sure, I will take a shot somewhere this week. Will let you know if I get anywhere.

**Comment by fabpot** [comment]
Thank you
