### ISSUE TITLE
[Validator] Url and Email validator possible bug

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#25666]
hello

if there is in DNS record *.domain.com and I want validate url or email with fourth domain level (something.dev.domain.com) then validator is not working properly

**Comment by javiereguiluz** [comment]
If you refer to the Url validator and `checkDNS` option, I'm afraid that we just deprecated them (https://github.com/symfony/symfony/pull/25516) and they will be removed in Symfony 5.0.

**Comment by poolerMF** [comment]
now this bug should be fixed ... or just update documentation, that validator is not working for fourth domain level

**Comment by xabbuh** [comment]
Can you give an example of a domain that would allow to reproduce the issue?

**Comment by poolerMF** [comment]
![domain](https://i.imgur.com/bir6WXt.png)

DNS records:
https://goo.gl/mUQG38
https://goo.gl/y2AkwC
https://goo.gl/iZPLgX

finally I see, it's DNS record type is RRSIG

**Comment by xabbuh** [comment]
How did you configure the `Url` constraint?

**Comment by poolerMF** [comment]
I just use checkDns ... "problem" is with function checkdnsrr that checks it ... it looks like, it's not supporting RRSIG

how to check rrsig (found, not tested):
https://github.com/datenknoten/check-rrsig/blob/master/check-rrsig.php

**Comment by poolerMF** [comment]
but when using UrlValidator, you can not specify DNS record type

    if ($constraint->checkDNS) {
            $host = parse_url($value, PHP_URL_HOST);

            if (!is_string($host) || !checkdnsrr($host, 'ANY')) {
                $this->context->buildViolation($constraint->dnsMessage)
                    ->setParameter('{{ value }}', $this->formatValue($host))
                    ->setCode(Url::INVALID_URL_ERROR)
                    ->addViolation();
            }
        }

so checkdnsrr is working weird .. and then UrlValidator is not working properly

**Comment by curry684** [comment]
> validator is not working for fourth domain level if DNS record is with wildcard for third domain level

That is by spec, wildcard records in DNS define a single level. A.b.c.d will never resolve on *.c.d, you need to define your own subzone explicitly for that.
