### ISSUE TITLE
Form templates overrides do not work in /templates

### ISSUE THREAD

**Issue by nesl247** [symfony/symfony#25661]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.2

With #24179 the `default_path` configuration key was added. Part of this was to allow bundle overrides in `/templates/<BundleName>`. However, this doesn't appear to be working for Form templates.

Specifically templates in `templates/bundles/BundleName/Form/something.html.twig` does not override the original. In my case this is for https://github.com/excelwebzone/EWZRecaptchaBundle but I'm guessing this would apply to any Form templates.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue?

**Comment by yceruto** [comment]
This looks like the referenced bundle use Templating Component and its syntax to load the form theme template [`EWZRecaptchaBundle:Form:ewz_recaptcha_widget.html.twig`](https://github.com/excelwebzone/EWZRecaptchaBundle/blob/06fc8c00937687f615b5797ae7760d1f4e841cb5/src/DependencyInjection/EWZRecaptchaExtension.php#L50) which is not compatible with the overriding mechanism of Twig (i.e they are different templates loaders).

In that case you must put your custom template in `app/Resources/EWZRecaptchaBundle/views/Form/ewz_recaptcha_widget.html.twig` (http://symfony.com/doc/3.4/templating/overriding.html). To use the modern way (`templates/bundles/...`), the bundle should configure it as `@EWZRecaptcha\Form\ewz_recaptcha_widget.html.twig` instead.

**Comment by nesl247** [comment]
Aah gotcha. I completely forgot about the format differences in the template name. That would definitely explain it. I'll go ahead and close this issue.

I had resolved it already by using `src/Resources/EWZRecaptchaBundle/views`, so at least that works.

**Comment by phoenixgao** [comment]
It took me half day to finally reach here... if this information could be added to the documentation it would be perfect @yceruto
