### ISSUE TITLE
[FORMS] validation_groups and group_sequence_provider bug ?

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#25664]
RecursiveContextualValidator:501

```php
    if (Constraint::DEFAULT_GROUP === $group) {
        if ($metadata->hasGroupSequence()) {
            // The group sequence is statically defined for the class
            $group = $metadata->getGroupSequence();
            $defaultOverridden = true;
        } elseif ($metadata->isGroupSequenceProvider()) {
            // The group sequence is dynamically obtained from the validated
            // object
            /* @var \Symfony\Component\Validator\GroupSequenceProviderInterface $object */
            $group = $object->getGroupSequence();
            $defaultOverridden = true;

            if (!$group instanceof GroupSequence) {
                $group = new GroupSequence($group);
            }
        }
    }
```

- **groupSequenceProvider** is working only when **validation_groups** contains default group '**Default**'
- I dont think, this solution/logic is good .. it sounds weird for me, that I need tu put group '**Default**' if I want to use **groupSequenceProvider**

I'm validating entity and setting custom **validation_groups** into form (for example **[update, create]**) ... and I also want to use **groupSequenceProvider** somewhere in relations ... how to do it without using extra group '**Default**' ?

**Comment by xabbuh** [comment]
That's the expected behaviour. How your particular problem can be solved is depending on the context you are using this in. However, I suggest you use on of the [support channels](https://symfony.com/support) to seek for help with your problem.

I am closing here as there is no bug in the code. Thank you for understanding.
