### ISSUE TITLE
Composer run scripts do not respect 'extra.symfony-public-dir' value when using %PUBLIC_DIR% var

### ISSUE THREAD

**Issue by jennevdmeer** [symfony/symfony#25677]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

For me the command:
`"assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"`

Triggers an error when my public directory is not `./public`, as the variable always returns 'public' and not the value of `extra.symfony-public-dir`.

```
Script assets:install --symlink --relative %PUBLIC_DIR% returned with error code 1
!!  2018-01-04T08:40:46+00:00 [error] Error thrown while running command
	"--ansi assets:install --symlink --relative public".
	Message: "The target directory "public" does not exist."
!!
!!  In AssetsInstallCommand.php line 97:
!!
!!    The target directory "public" does not exist.
```

In my case I have the following directory structure
- www
	- public_html
	- symfony
		- config
		- src
		- ...
		- composer.json

And changed `extra.symfony-public-dir` to `../public_html/`.

---

Am I missing something/ something wrong or bug? My current work around is as hinted in the docs by creating a symlink `./public ../public_html` however I guess this error goes beyond this as there are more variables?

Regards

**Comment by SamuelSSalazar** [comment]
Did you found a solution ??
I´m having the same problem and i have already double check the documentation posted in here:

https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory

**Comment by xabbuh** [comment]
This is indeed an issue of the documentation (see symfony/symfony-docs#8766).

**Comment by dzuelke** [comment]
So which is it now? `config.public-dir` or `config.extra.public-dir`?

**Comment by dzuelke** [comment]
Ah, looks like `extra.public-dir`: https://github.com/symfony/flex/blob/5e610d4b66a1f17736f6025fc81fd794d8ac69d6/src/Flex.php#L353
