### ISSUE TITLE
[Translation] Missing Alias for Services (Writer, Reader, Extractor)

### ISSUE THREAD

**Issue by Nijusan** [symfony/symfony#25679]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.+

I lately updated a legacy Command to the new auto wire feature which needs the Translation Services.

After Updating the Command with:
`
public function __construct(
        TranslationWriterInterface $writer,
        TranslationReaderInterface $reader,
        ExtractorInterface $extractor
    ) {
...
`
I got the error: argument "$writer" of method "__construct()" references interface "Symfony\Component\Translation\Writer\TranslationWriterInterf
  ace" but no such service exists. It cannot be auto-registered because it is from a different root namespace.

Maybe i did not read the documentation carefully or just wasnt aware of how the identification of the services is done, so only with the help of the support channel i got the hint that there are default alias for other services, but not here.

If there is no side-effect, its maybe better to just create the aliases in the core then having them defined in the own service.yml:

`
Symfony\Component\Translation\Extractor\ExtractorInterface: '@translation.extractor'
Symfony\Component\Translation\Writer\TranslationWriterInterface: '@translation.writer'
Symfony\Component\Translation\Reader\TranslationReaderInterface: '@translation.reader'
`

**Comment by chalasr** [comment]
Adding these aliases in core sounds good to me.

**Comment by Simperfit** [comment]
@Nijusan Do you want to provide the pull request? It seems like an easy pick to me ;).

**Comment by Nijusan** [comment]
@Simperfit i tried :) please correct me if i did something wrong
