### ISSUE TITLE
EmailValidator should use filter_var in strict mode if Egulias library is missing

### ISSUE THREAD

**Issue by ebuildy** [symfony/symfony#25674]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 4.0.0

``Egulias\EmailValidator\EmailValidator`` is not really perfect (``toto@toto.___c`` is valid whereas it's not for HTML5 or filter_var), so I propose to use ``filter_var`` with ``FILTER_VALIDATE_EMAIL`` if Egulias is not installed:

EmailValidator:

```
if (!class_exists('\Egulias\EmailValidator\EmailValidator')) {
                if (filter_var($value, FILTER_VALIDATE_EMAIL) === false) {
                    $this->context->buildViolation($constraint->message)
                        ->setParameter('{{ value }}', $this->formatValue($value))
                        ->setCode(Email::INVALID_FORMAT_ERROR)
                        ->addViolation();

                    return;
                }
            }
```

**Comment by jvasseur** [comment]
:-1: having the behavior of the constraint change based on the presence of a dependency looks like a bad idea.

We could add another validation mode that is based on `FILTER_VALIDATE_EMAIL` but I'm not sure if it's worth it since `FILTER_VALIDATE_EMAIL` doesn't match any standard (that's why we stopped using it).

**Comment by ebuildy** [comment]
Yes you are right, I should declare the bug on the library ``Egulias\EmailValidator`` instead.

We are using ``FILTER_VALIDATE_EMAIL`` in lot of projects, do you have sources saying it's bad?

Thanks you, I am closing the issue so.

**Comment by jvasseur** [comment]
@ebuildy you can look at the references in the PR that removed the use of `filter_var` : https://github.com/symfony/symfony/pull/9140
