### ISSUE TITLE
passing an object from an EntityType to another EntityType (Controller -> ParentType -> ChildType)

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [symfony/symfony#25675]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3-dev

Hi,

I want to pass an object from an EntityType to another EntityType called in a Controller.

I found that there is two methods to do this:

**First method : Through the constructor**
This works fine the objects that they didn't need any modification before passing them to the EntityType (like the EntityManager) because this method requires to create a service for the EntityType with the parameter arguments: [For more detail](https://symfony.com/doc/3.3/form/create_custom_field_type.html#accessing-services-and-config)

But since Symfony3 will automatically create the object defined an attribute in the EntityType in the __construct() method, we can't pass an object with a modified attribute's values:

I mean:

1. In the Controller, the EntityType classes are called using this syntax:

`$form = $this->createForm(EntityType::class, $entitytypeObject,array());`

So, if I want pass an object which is not an instance of EntityType to the EntityType class I can't do that since Symfony3 (in Symfony2.7 it's possible) because the createForm method need only the EntityType type, the EntityType object and an array of options and it did there is no way to pass another specific object.

2. In the ParentType, the ChildType classes are called using this syntax in the buildForm() method using this syntax:

`$builder->add('attribute_name', CollectionType::class,array(
      'entry_type' => ChildType::class,
      'required'=> true,
      'allow_add' => true,
      'by_reference' => false,
);`

And also here, we can't call the ChildType with the constructor so we can't pass any other object (for example an object which come from the Controller that we want to pass it to the ChildType through the ParentType)

**Second method : Through the options**

Here, I did some researches and I found that we can pass any object (instance of any EntityType class) using the third parameter (options) of those methods:

- For the controller: `$form = $this->createForm(EntityType::class, $entitytypeObject,array('custom_option'=>$custom_object));` . This works fine thanks to this solution [stackoverflow](https://stackoverflow.com/a/36907431/8239292)

- For the ParentType: `$builder->add('attribute_name', CollectionType::class,array(
      'entry_type' => ChildType::class,
      'required'=> true,
      'allow_add' => true,
      'by_reference' => false,
      'custom_option'=>$custom_object
);` . This didn't work

So if I need to pass an object (instance of EntityX) from the Controller through the ParentType to the ChildType, we have three level of code:

The first is the Controller class:

```
public function postParentAction(Request $request)
{
    //$entityX = ...; //entityX is an instance of EntityX with some modifications in the value of the attributes
    $parentType = new ParentType();
    $form = $this->createForm(ParentType::class, $parentType, array(
            'validation_groups' => array('Default'),
            'custom_option' => $entityX,
    ));
    //submission and validation ...
}
```

In the ParentType class:

```
class ParentType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    //dump($options['custom_option']); //this line works fine and it dump the $entityX
    // so we successfully edited the options from the Controller to the ParentType
    $builder->add('parent_name', CollectionType::class,array(
      'entry_type' => ParentType::class,
      'required'=> true,
      'allow_add' => true,
      'by_reference' => false,
      'custom_option' => $options['custom_option'] //without this line, there is no error if we delete the use of 'custom_option' also from the ChildType
    );
  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults([
      'data_class' => 'PATH\NAMEBundle\Entity\Parent',
      'cascade_validation' => true,
      'error_bubbling' => false,
      'custom_option' => null, //this will register the 'custom_option', otherwise we get an error [The option "custom_option" does not exist. Defined options are: ...]
    ]);
    $resolver->setRequired('custom_option');
  }
}
```

And finally the ChildType:

```
class ChildType extends AbstractType
    {
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    dump($options['custom_option']); //this line can't be executed because of the error
    $this->custom_option = $options['custom_option'];
    $builder->add('full_name');
  }
  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults([
        'data_class' => 'PATH\NAMEBundle\Entity\Child',
        'validation_groups' => array('Default'),
        'cascade_validation' => true,
        'error_bubbling' => false,
        'custom_option' => null, //this line should register the 'custom_option' as it did with the use case Controller-ParentType but this line has no effect here
    ]);
    $resolver->setRequired('custom_option');
  }
}
```

But I get this error when I add the ChildType class : 

```
"message": "The option \"em\" does not exist. Defined options are: \"action\", \"allow_add\", \"allow_delete\", \"allow_extra_fields\", \"attr\", \"auto_initialize\", \"block_name\", \"by_reference\", \"compound\", \"constraints\", \"csrf_field_name\", \"csrf_message\", \"csrf_protection\", \"csrf_token_id\", \"csrf_token_manager\", \"data\", \"data_class\", \"delete_empty\", \"disabled\", \"empty_data\", \"entry_options\", \"entry_type\", \"error_bubbling\", \"error_mapping\", \"extra_fields_message\", \"horizontal_input_wrapper_class\", \"horizontal_label_class\", \"horizontal_label_offset_class\", \"inherit_data\", \"invalid_message\", \"invalid_message_parameters\", \"label\", \"label_attr\", \"label_format\", \"label_render\", \"mapped\", \"method\", \"post_max_size_message\", \"property_path\", \"prototype\", \"prototype_data\", \"prototype_name\", \"required\", \"sonata_admin\", \"sonata_field_description\", \"sonata_help\", \"translation_domain\", \"trim\", \"upload_max_size_message\", \"validation_groups\".",
"class": "Symfony\\Component\\OptionsResolver\\Exception\\UndefinedOptionsException",
```

This line of the ChildType `'custom_option' => null` should register the 'custom_option' as it did with the use case Controller-ParentType but this line has no effect here.

I think there is a bug or something like this.

If adding a custom option from the Controller to the ParentType works, why it should not work from the ParentType to the ChildType ?

I tried also the solution that I mentioned in the beginning (using the services) (with autowiring and without it) but it didn't help me because I don't want that the __construct() method creates only an object of EntityX. I need to pass the modified object from the Controller to the ChildType through the ParentType and not creating a new object in the __construct().

For more details of the problem and the suggested solutions that didn't help me, see here: [stackoverflow](https://stackoverflow.com/questions/48054345/passing-the-entitymanager-from-an-entitytype-to-another-entitytype).

Maybe registering a custom_option should not be done using setDefaults() method when we create the custom_option from an ParentType to ChildType ?

I didn't found where is the bug in the code.

Here is some links for the source code of these steps in the master symfony/symfony project maybe you can find it or maybe it can be a new feature that can be added:

I want to pass an object from the Controller ([ControllerTrait.php](https://github.com/symfony/framework-bundle/blob/3.3/Controller/ControllerTrait.php)) (using the [createForm() method](https://github.com/symfony/framework-bundle/blob/3.3/Controller/ControllerTrait.php#L329)) (this method will call the [create() method](https://github.com/symfony/form/blob/3.3/FormFactory.php#L28) of the form.factory service) through the ParentType which it will call the [add() method](https://github.com/symfony/form/blob/3.3/FormBuilderInterface.php#L32) (in the [buildForm() method](https://github.com/symfony/form/blob/3.3/AbstractType.php#L25) of the AbstractType) to pass this object to the ChildType class. (Controller -> ParentType -> ChildType)

The problem is also related to the [OptionsResolver class](https://github.com/symfony/options-resolver/blob/3.3/OptionsResolver.php) which is the responsible of generating this error.

Thank you for any solution for this problem.

**Comment by iltar** [comment]
This looks like a question you should ask through https://symfony.com/support instead. It's not really an issue in Symfony, the community can help you with this.

**Comment by mohamedaymenkarmous** [comment]
Hi,

I resolved this problem thanks to the support team symfony-devs on Slack especially a special thank to @gerryvdm .

The problem was that the ParentType class contains an embeded form and to pass any option (even a custom one) to the ChildType, the option should be in the 'entry_options' row of the third argument of the buildForm:add(). Otherwise the option will be sent to the CollectionType and not ChildType class.

Reference: [collection.html#entry-options](https://symfony.com/doc/current/reference/forms/types/collection.html#entry-options)

So the modified ParentType should be like this:

```
class ParentType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    //dump($options['custom_option']); //this line works fine and it dump the $entityX
    // so we successfully edited the options from the Controller to the ParentType
    $builder->add('parent_name', CollectionType::class,array(
      'entry_type' => ParentType::class,
      'required'=> true,
      'allow_add' => true,
      'by_reference' => false,
      'entry_options' => array('custom_option' => $options['custom_option']), // ->>>we modified this line <<<-
    );
  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults([
      'data_class' => 'PATH\NAMEBundle\Entity\Parent',
      'cascade_validation' => true,
      'error_bubbling' => false,
      'custom_option' => null, //this will register the 'custom_option', otherwise we get an error [The option "custom_option" does not exist. Defined options are: ...]
    ]);
    $resolver->setRequired('custom_option');
  }
}
```

Thank you.

Best regards

**Comment by selimppc** [comment]
@mohamedaymenkarmous , thanks for your solution- it helps. 

I need an idea about the parent FormType:

    ```
->add('productAttributes',  ProductAttributeType::class, [
                'data_class' => null,
                'entry_options' => array(
                    'custom_option' => $options['custom_option']),
            ])
```

**Issue**: `entry_options`   does not exist for this situation.

**Comment by selimppc** [comment]
@mohamedaymenkarmous , I think I got the solution. We just need to add `custom_option` as like: 


        ->add('child',  ChildType::class, [

            'data_class' => null,

           'custom_option' => $options['custom_option']),

        ])


This works!
