### ISSUE TITLE
interactive shell activated by default

### ISSUE THREAD

**Issue by garak** [symfony/symfony#25681]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.32

I'm getting while running my continuous integration, specifically Bitbucket pipelines. As you can see in attached screenshot, interactive shell is triggered even without passing `-s` flag. Even worst, passing `-n` is also ineffective
![screenshot-pipelines bitbucket](https://user-images.githubusercontent.com/179866/34562956-e281b60a-f150-11e7-952b-ef9228d4442e.png)

**Comment by nicolas-grekas** [comment]
isn't this an issue for https://github.com/doctrine/DoctrineBundle?

**Comment by garak** [comment]
I don't think so.
Doctrine commands are just extensions of Symfony ones, and I can't find anything specifically related to interactive shell in them.

**Comment by Simperfit** [comment]
This has been fixed in https://github.com/symfony/symfony/releases/tag/v2.7.40 could you please update to this version ?

**Comment by garak** [comment]
As you can see in above screenshot, I'm currently on Symfony 2.8.32

**Comment by xabbuh** [comment]
Does updating to 2.8.33 help?

**Comment by garak** [comment]
I was a bit skeptical, but it did the trick! Thanks for suggestions
