### ISSUE TITLE
stty: stdin isn't a terminal in PHP Storm (Console)

### ISSUE THREAD

**Issue by HeathNaylor** [symfony/symfony#25687]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

This is a problem specific to Symfony Console and the Questions Helper. This appears to only be a problem when I set the question input to be hidden using the `Question` class method `setHiddent(true)`. When executing tests just using PHPStorm I get the following output with an error:

```
Testing started at 11:24 AM ...
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.25 with Xdebug 2.5.5
Configuration: phpunit.xml

stty: stdin isn't a terminal
```
If I run the tests through a terminal everything is fine. Is there a reasonable way to run console tests through a tool like PHPStorm?

**Comment by tomzx** [comment]
Hello @HeathNaylor, would it be possible for you to provide an example test case to make it easier for others to debug?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
