### ISSUE TITLE
non-existent service "security.csrf.token_manager"

### ISSUE THREAD

**Issue by Sozialarchiv** [symfony/symfony#25683]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

I followed https://symfony.com/doc/current/security/csrf.html. But i always get the message

`The service "security.authentication.listener.form.main" has a dependency on a non-existent service "security.csrf.token_manager".`

symonfy/symfony/security-csrf is installed.

Thank you very much for help.

**Comment by nicolas-grekas** [comment]
you need symfony/security-bundle also
where did you get the suggestion to install symfony/securty-csrf instead?

**Comment by xabbuh** [comment]
Let's fix the docs (see https://github.com/symfony/symfony-docs/pull/8955#issuecomment-355304835). I am going to close here as this is something that cannot be fixed in the code.

**Comment by Sozialarchiv** [comment]
> where did you get the suggestion to install symfony/security-csrf instead?

https://symfony.com/doc/current/security/csrf.html
> composer require security-csrf form

**Comment by Sozialarchiv** [comment]
> you need symfony/security-bundle also

The security-bundle is installed, too.

**Comment by weaverryan** [comment]
Yea, I don’t think the security bundle is the problem - after all, the service that’s throwing the errors is from the security bundle.

Did you enable the csrf_protection in framework.yaml?

**Comment by Sozialarchiv** [comment]
> Did you enable the csrf_protection in framework.yaml?

Thank you that was is.  I changed 
```
framework:
    #csrf_protection: ~
```
to

```
framework:
    csrf_protection: ~
```

Thanks a lot to all for your fast help.

**Comment by PF4Public** [comment]
I was trying to disable csrf via `csrf_protection: false` and got exactly this error: `The service "security.authentication.listener.form.main" has a dependency on a non-existent service "security.csrf.token_m  
  anager".`

How do I disable csrf?

**EDIT** For anyone coming here with the above issue. I solved it by disabling also:
```yaml
            form_login: false
            remember_me: false
```
