### ISSUE TITLE
weak_vendors mode and isolated test

### ISSUE THREAD

**Issue by alexpott** [symfony/symfony#25684]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

If you set SYMFONY_DEPRECATIONS_HELPER to weak_vendors and then have a test uses the `@runTestsInSeparateProcesses` annotation and does not have an `@group legacy` even though deprecations are triggered from non-vendor code, they are ignored. This is because the with-process-isolation-silenced-error is actually triggered from \Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait::endTest() which is vendor code for most projects (eg. Drupal). For a real world example see: https://www.drupal.org/project/drupal/issues/2934336

**Comment by greg0ire** [comment]
I think that will imply changing how this method: https://github.com/symfony/symfony/blob/96e53f8837255d4f9ad3c7d2c68dcda1abbb0cb5/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L64-L86

Right now it accepts only one file, maybe it should accept the whole trace, and then we should go one step up in the trace if the file happens to be the trait.

**Comment by greg0ire** [comment]
The offending piece of code, for reference: https://github.com/symfony/symfony/blob/96e53f8837255d4f9ad3c7d2c68dcda1abbb0cb5/src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php#L261-L273

**Comment by greg0ire** [comment]
@alexpott I believe this can be closed, right?
