### ISSUE TITLE
Session indirectly started by RequestDataCollector in HttpKernel

### ISSUE THREAD

**Issue by adamquaile** [symfony/symfony#25698]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | *

In any environment where the profiler is enabled, I noticed Cache-control headers were not working correctly. This seems due to this bit of code, marking all requests in sessions as private with a max-age of 0 https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/SaveSessionListener.php#L54 .

I wasn't aware my requests were actually using sessions, and on debugging with help in Slack, it looks like it's started by this RequestDataCollector as it doesn't check whether the session is started or not before inspecting it. Inspecting it starts the session, and overrides my cache headers. 

The fix seems to be adding 
```
if (!$event->getRequest()->getSession()->isStarted()) {
    return;
}
```

In https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/RequestDataCollector.php#L328

`*` I'm not sure exactly which symfony versions this affects, but it could have been introduced here: https://github.com/symfony/symfony/commit/95d0b7235f1d9c84d30c8a22146d0a2daced2cf8#diff-e8f5b14fbfbbeac60fc9f3abe310c3b0 . Does this commit need reverting or changing, or am I misunderstanding something?

**Comment by nicolas-grekas** [comment]
Actually that's expected behavior: this page is not cachable - it used the session to be generated.
See #24774, which *fixed* the `isStarted` check.

**Comment by adamquaile** [comment]
@nicolas-grekas I don't quite understand, then. As my code didn't explicitly start and doesn't need it, can I disable the session functionality completely or is that required by the profiler too function?

**Comment by mvrhov** [comment]
@nicolas-grekas: This is what I was talking about when you started the session refactoring. The framework or it's debug components shouldn't start the session unless it has been started by the developer's code explicitly.

**Comment by Tobion** [comment]
This looks like a huge bug to me introduced with #25583. RequestDataCollector always starts the session  and then SaveSessionListener will always mark the request uncachable due to #25583. So even if you don't use a session, the no cache headers will be set automaticall.

**Comment by nicolas-grekas** [comment]
As stated above, this is not a bug to me, and this is totally independent from #25583.
See #24774 and #24730: the profiler cannot work without the session, so it has to use it.
This is just normal behavior and a side effect of using the profiler. Not doing so means re-introducing #24730.

**Comment by adamquaile** [comment]
This make a little more sense to me now, so 

A session is required for the profiler to work (to catch redirects I believe)

A session being started (even for an indirect reason such as this) means the response should be considered private, even if this could sometimes be inconvenient. 

But, do we really need to `setMaxAge(0)` and override what a dev has specified as the cacheability for a response in their controller? And if we do, I think this should be clearly explained in the documentation on caching, as following the instructions in the docs in a dev environment don't seem to work right now.

**Comment by nicolas-grekas** [comment]
Actually, this may be fixable: we should just not use the session to forward the `sf_redirect` array from one request to another, and just use a json_encoded cookie!
@adamquaile would you like to give it a try?

**Comment by sroze** [comment]
> we should just not use the session to forward the sf_redirect array from one request to another, and just use a json_encoded cookie

It's a tradeoff: using a cookie would mean that both the redirection and the target page will not be cachable (because of the `Set-Cookie` to set the `sf_redirect` and the one to clear it). 

> or URL parameter

IMHO that might confuse developers, but there are less hidden moving parts, so this might be a good idea, you've got my 👍 on this one.

Depending on the feedback, I'm happy to help going to either direction by PRing the changes.

**Comment by adamquaile** [comment]
I think a URL parameter might be the simplest here, because there's no need to really clear it. I can imagine browser extensions or settings potentially causing more problems with cookies too. Happy to help on this when I next get a chance too, if that's the way people want to go.

**Comment by sroze** [comment]
The obvious problem is the URL parameter is that it requires the user to generates the URL using Symfony's router, and would require the HttpKernel component to know about it... which is not going to work well IMHO. The Cookie option _seems_ to be the only suitable alternative.

**Comment by sroze** [comment]
See #25719
