### ISSUE TITLE
Calling handleRequest() after setData() on a form may cause unhandled exceptions

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony#25697]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Symfony version  | 4.0.3

I have a form configured as a service, and reused from the controller. When I try to update an existing entity with empty submitted data, an unhandled Exception is thrown, because the form attempts to set object's property to null, even though both object and the form itself require that property to be a non-empty string. Here's the relevant method:

```
    public function edit(Request $request, Customer $customer): Response
    {
        $this->form->setData($customer);
        $this->form->handleRequest($request); //  <-----THIS FAILS!

        if ($this->form->isSubmitted() && $this->form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash('success', 'Customer updated successfully.');

            return $this->redirectToRoute('customer.show', ['id' => $customer->getId()]);
        }

        return $this->render('customer/edit.html.twig', [
            'customer' => $customer,
            'form' => $this->form->createView(),
        ]);
    }
```

This looks like a bug to me. If it isn't, any pointers to how my code should be fixed would be appreciated.

**Comment by xabbuh** [comment]
What do you mean with "this fails"? Do you get an error? If yes, what is the error?

**Comment by iltar** [comment]
How do you create your form? Because usually you don't make your forms a service, you use the form factory to make them.

**Comment by rimas-kudelis** [comment]
@xabbuh by "this fails", I mean this throws an exception. Here's the stack trace:
```
Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Argument 1 passed to App\Entity\Customer::setName() must be of the type string, null given, called in .../vendor/symfony/property-access/PropertyAccessor.php on line 527

  at src/Entity/Customer.php:72
  at App\Entity\Customer->setName(null)
     (vendor/symfony/property-access/PropertyAccessor.php:527)
  at Symfony\Component\PropertyAccess\PropertyAccessor->writeProperty(array(object(Customer), object(Customer)), 'name', null)
     (vendor/symfony/property-access/PropertyAccessor.php:138)
  at Symfony\Component\PropertyAccess\PropertyAccessor->setValue(object(Customer), object(PropertyPath), null)
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:85)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(object(RecursiveIteratorIterator), object(Customer))
     (vendor/symfony/form/Form.php:628)
  at Symfony\Component\Form\Form->submit(array(), true)
     (vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php:108)
  at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(Request))
     (vendor/symfony/form/Form.php:498)
  at Symfony\Component\Form\Form->handleRequest(object(Request))
     (src/Controller/CustomerController.php:80)
  at App\Controller\CustomerController->edit(object(Request), object(Customer))
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:190)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:34)
```
I could catch the exception of course, but I wonder if this is the expected course of events.
Also, if I call `handleRequest()` with same Request content, but without calling `setData()` and passing an object to it first, no exception is thrown.

Like I said, during `handleRequest()`, the form appears to be setting object properties without checking submitted data for validity first. I would expect it to either validate data beforehand, or to anticipate and handle potential exceptions.

**Comment by rimas-kudelis** [comment]
@iltar the form and the controller are described in `services.yaml` like this:

```
   App\Controller\CustomerController:
        arguments:
            - '@app.form.customer'

    app.form.customer:
        class: 'Symfony\Component\Form\Form'
        factory: [ '@form.factory', 'create' ]
        arguments:
            - 'App\Form\CustomerType'
            - null
            - { 'attr': { 'novalidate': 'novalidate' } }
```
The constructor for `CustomerController` looks like this:
```
    public function __construct(FormInterface $form, EntityManagerInterface $entityManager, CustomerRepository $repository)
    {
        $this->form = $form;

        $this->entityManager = $entityManager;

        $this->repository = $repository;
    }
```

This is my first Symfony project, so I can't rationalize too much here, but that's what my senior programmers with Symfony certificates and years of experience told me to do (and what they seem to be doing in their other projects), so I comply.

**Comment by iltar** [comment]
I guess registering your form like that is possible, but I wouldn't recommend it. This will give every form where it's injected, the same instance, rather than a unique and isolated instance. It also prevents you from properly binding your data.

Besides of that, could it be that your field is empty? It seems like you want strictness (entity is my guess), but you're using your entity as a form object if I see it correctly. This conflicts, you can't have a valid entity because the form forces it to be invalid at a given point: https://stovepipe.systems/post/avoiding-entities-in-forms

```php
    public function edit(Request $request, Customer $customer): Response
    {
        $this->form_factory->create(CustomerType::class, $customer/*, $options*/);
        $this->form->handleRequest($request);

        if ($this->form->isSubmitted() && $this->form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash('success', 'Customer updated successfully.');

            return $this->redirectToRoute('customer.show', ['id' => $customer->getId()]);
        }

        return $this->render('customer/edit.html.twig', [
            'customer' => $customer,
            'form' => $this->form->createView(),
        ]);
    }
```

**Comment by rimas-kudelis** [comment]
Yes, the field is empty, and the object requires it not to be. I mentioned teat in my initial report.

Like I said, it's not my choice to turn forms into services. I personally find it unnecessary, but that's not what this ticket is about. It's about whether it's indeed expected that the form will recklessly try setting entity properties without validating them first, or expecting such action to fail and throw an exception.

If this is all expected, I'll look for ways to work it around, but if not, I suppose it should probably be fixed, no? :)

**Comment by iltar** [comment]
It fills the object with the values and _then_ validates, which is what my blog posts are about.

**Comment by rimas-kudelis** [comment]
I'm reading the blog posts now, but filling and then validating doesn't sound like a logical approach to me. Is there anything preventing the form from performing these actions in reverse order?

**Comment by iltar** [comment]
No, that's just how it works, hence you should probably use DTOs and fill your entities after the validation.

**Comment by rimas-kudelis** [comment]
Okay, thanks for the pointers. One last question: was it "No" as in "No, there's nothing preventing the form from performing these actions in reverse order", or was it "No" as in "No, that is not possible to do in reverse order"? :)

**Comment by iltar** [comment]
No, you can't do it in reverse order.  Your form type tells what your input should be mapped to (either array or object). The property access maps those properties to the object. The validator then validates the object (or array ofc). This due to model and view transformations that might happen.

**Comment by rimas-kudelis** [comment]
OK, thanks once again!

**Comment by xabbuh** [comment]
I am closing then as there is nothing to fix.

**Comment by tlenoir** [comment]
Hi, in fact to setData() before $handleRequest, not use $form->setData(), use $event->setData()

**Comment by Volmarg** [comment]
So before someone stumbles upon the same problem where for some reason `handleRequest()` throws exception that `null` was returned.

This makes no sense at all - because data should not be accesed at this point, yet i debugged it and found out that there is some logic which actually calls getters on empty entity.

And well, since I had fields not allowed to be null it keept throwing this error.
There are 2 solutions here:
- make this fields nullable in entity (yet keep validation in DB intact),
- define default values for all fields in entity,

I however use the first solution, becuase i dont want accidental empty strings in DB

**Comment by linaori** [comment]
@Volmarg it's a bad idea to modify your entity just to make it work for the form, I will advise to use an intermediate DTO instead.

**Comment by Volmarg** [comment]
But DTO is also workaround here. Besides that won't solve the problem as this logic is triggered in the symfony core. I can provided some screenshots and info where this happens, but at this point it works.

**Comment by Volmarg** [comment]
Oh wait... You want to use data_class as DTO?

**Comment by linaori** [comment]
Yes, and ideally binding the DTO as `$data` argument when building your form. This means you have full control over the initial state, the temporary state before and after validation, and how you process the data.

**Comment by xabbuh** [comment]
@Volmarg You may also want to take a look at [the RichModelFormsBundle](https://github.com/sensiolabs-de/rich-model-forms-bundle) which allows you to use your entity as is and will catch some specific exceptions/error that can occur when mapping data and turns them into nice form errors.
