### ISSUE TITLE
[Security] LogoutListener has private properties

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#25694]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x

I've got an issue with the usage of the `LogoutListener`. I'm trying to add some customized handling, but got stopped by the `requiresLogout()` method. It's protected and the docblock reads:

>The default implementation only processed requests to a specific path,
>but a subclass could change this to logout requests where
>certain parameters is present.

I've created a custom class extending the base one, but now I cannot access e.g. the TokenStorage, because it's a private property. I can copy&paste the required stuff, but that must be wrong.

Did I miss something how this should be done or should the private proprties be protected?

Cheers
Matthias

**Comment by xabbuh** [comment]
I don't see anything wrong with adding something like the token storage as a property in your custom listener class to be able to use it. That can be easily achieved and you just forward all the other constructor arguments to the parent class' constructor.

**Comment by ostrolucky** [comment]
Constructor overriding as an only way to access injected services in classes designed for inheritance increases likehood of BC break. Any signature change in constructor might break subclass which only passes these arguments over to parent. 

So I think it would be better to give easier access to these services in such classes. It reduces impact of such changes and improves DX.

**Comment by chalasr** [comment]
We don't do breaking changes in constructor signatures, only adding optional argument at last position is allowed, a BC layer must be added otherwise (deprecation notices). 
Protected things are way more impacting regarding maintenance, I agree with @xabbuh here.

**Comment by ostrolucky** [comment]
Well I know it's your policy and you try hard, but you do breaking changes in constructors in patch releases from time to time anyway

https://github.com/symfony/symfony/commit/860575a88240a1eca46fc9a660212816827d32df#diff-9d2030564e7539d11d2a4923b6ae96b4R34
https://github.com/symfony/symfony/commit/baaff20f4aa3b587617c05e201208527922871fd#diff-40ba7de9e4147b219f8ed3a42dede24dR89
https://github.com/symfony/symfony/commit/4bcef3d67c23e6006cbe8516e7951e51d8810376#diff-d4464c00b7613bfaad324d7f2d062a0eR26
https://github.com/symfony/symfony/commit/cd602d691a558f7f71f6aeaca0acbfc5f6b98e5b#diff-f0fa83480490a3b4f9887a6ba30a298a

But I wasn't talking just about patch releases. Changing those signatures as you wish is fair game for you in major releases, but it breaks subclasses nevertheless. That's my point. All that subclass wants is access to injected object. Developer is guided to override constructor, which increases likehood of it getting broke in future.

I haven't suggested to use protected properties either, getter or __get would be safer option. As a bonus, you can trigger deprecations from within it, which signalizes you are going to stop injecting value it retrieves in future release.

**Comment by unkind** [comment]
Regarding the design of the class, it could've been done like this:
```php
final class LogoutListener
{
    public function __construct(..., callable $requiresLogout = null)
    {
        // ...
    }
}

// ...

final class MyCustomLogoutListenerFactory
{
    public function getListener(): LogoutListener
    {
        return new LogoutListener(..., function (Request $request, callable $default) {
            return $this->tokenStorage->... && $default($request);
        });
    }
}
```
There is no need to deal with inheritance.

**Comment by ostrolucky** [comment]
With that approach, you don't have any guarantee you will get same tokenStorage object that is injected in LogoutListener. But it's offtopic. I just wanted to improve policy regarding classes **meant** for inheritance.

**Comment by unkind** [comment]
>  you don't have any guarantee you will get same tokenStorage object that is injected in LogoutListener

Why? You inject `tokenStorage` and use the same instance within closure.

**Comment by chalasr** [comment]
@xabbuh's suggestion seems good enough to me. 
Closing here as this is staling, feel free to reopen or submit a PR if you think the situation can be improved.
