### ISSUE TITLE
[Console] Change TypeHinting array to iterable in public methods

### ISSUE THREAD

**Issue by Smolky** [symfony/symfony#25702]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | -
| RFC?             | -
| Symfony version  | -

This issue is related to the use of the **console component as standalone**.

The methods ```setHeaders```, ```setRows```, etc expects an ```array``` as parameter by type hinting, but I think this approach limit how we can use this component. For example, sending a ```SplFixedArray``` results in a error. 

It is possible to change it to ```iterable``` 

Here is the reference:
http://php.net/manual/en/language.types.iterable.php

**Comment by tomzx** [comment]
The issue with moving from `array` to `iterable` is that you cannot address arrays directly (use keys) anymore as an iterator is going to return values one by one. This would thus require calls to [iterator_to_array](http://php.net/iterator_to_array) to obtain the same result while making the code less readable (and a bit slower).

**Comment by ostrolucky** [comment]
No, that would be BC break for subclasses https://3v4l.org/UloRM.  Symfony does not do such changes without deprecation path.

**Comment by Smolky** [comment]
Understood. Thanks.
