### ISSUE TITLE
[Cache] Document \Symfony\Component\Cache\CacheItem properties

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#25703]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

Please document these properties https://github.com/symfony/symfony/blob/ebf3f0e051d7286eb5667bea5f3873d0db0e8fe8/src/Symfony/Component/Cache/CacheItem.php#L23-L31

I can't even say what units does `$defaultLifetime` use.

I'm aware this is internal class, this still needs to be done though. Developers spend ton of time digging through sources of libraries they use and this needs to be readable for contributors too.

**Comment by nicolas-grekas** [comment]
But you shouldn't care: you don't have access to them. Only the methods are part of the contract and they have full doc blocks...
Anyway, just send a PR if you really think we should doc these :)

**Comment by ostrolucky** [comment]
I would send PR, but I don't know how it works. That's why I created this issue. Someone who knows how it works should document it.

I explained why I care even though I don't have access there. I was tracking down the bug I had, got to this class and was suddenly lost.

**Comment by Simperfit** [comment]
What do you want to say on the properties ? most of them seems self-explanatory to me, and looking a the code, you can understand what it does. Where were you lost ?

I kind of agree if you think it needs to be updated then I guess It can for the DX.

**Comment by ostrolucky** [comment]
I think you might be right. After getting some sleep and looking at it again I think it might be clear enough
