### ISSUE TITLE
*.symfony.com certificate expired

### ISSUE THREAD

**Issue by klausbreyer** [symfony/symfony#25713]
I wanted to use https://symfony.com/installer in my ansible script, but it seems your certificate is expired. 

![screen shot 2018-01-08 at 09 56 32](https://user-images.githubusercontent.com/32771/34664058-468b72ce-f45a-11e7-8ab7-66206e3b6597.png)

**Comment by bodik** [comment]
i encountered exactly the same during puppet CI, you can use composer as workaround
```
composer --no-interaction create-project symfony/framework-standard-edition:3.3.10 ./
```

**Comment by fabpot** [comment]
Fixed now.
