### ISSUE TITLE
Period in URL crashes profiler

### ISSUE THREAD

**Issue by codedmonkey** [symfony/symfony#25711]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             |  no
| Symfony version  | 4.0.3

I'm currently experiencing an issue where the Profiler crashes when a period is used in the URL. I came across https://github.com/symfony/symfony/issues/25541, but it seems to be a bit different, although related.

My route is as follows: `@Route("/{param1}/", name="test_route")`

When going to `/foo/`, the profiler works, and I can debug the request afterwards. When going to `/foo.bar/` the profiler does not work, and it doesn't show a profile of the request.

In the linked issue, the point is raised that the problem won't be fixed, which is fine by me, but if it makes it unable to debug a request that is obviously a problem. Although I'm still unsure whether this is really the same problem.

**Comment by xabbuh** [comment]
Would you mind creating a small example application so that we can easily debug where exactly this is breaking?

**Comment by codedmonkey** [comment]
The reason I didn't was because it was very easy to replicate on my development machine. I'm currently trying to replicate it on a second machine but I'm unable to do so. Will report back if I can find the real culprit tongiht. Thanks :)

**Comment by iltar** [comment]
When you open your network tab, does it show anything? It could be related to an .htaccess setting if you're using that.

**Comment by codedmonkey** [comment]
After some debugging, I found that for whatever reason if I add a period to the URL, I end up with a completely different `$_SERVER` variable. Hopefully can somebody explain to me where these parameters come from:

      "REQUEST_TIME_FLOAT" => 1515461685.9981
      "REQUEST_TIME" => 1515461685
      "APP_SYMFONY_VERSIONS" => "2.3;2.7;2.8;3.4;4.0;master=4.1"
      "USER" => "codedmonkey"
      "XDG_SEAT" => "seat0"
      "SSH_AGENT_PID" => "900"
      "XDG_SESSION_TYPE" => "x11"
      "LD_LIBRARY_PATH" => "share/jetbrains-toolbox:share/jetbrains-toolbox/lib:./lib/:./lib/i386-linux-gnu/:./lib/x86_64-linux-gnu/:./lib32/:./lib64/:../lib/:../lib/i386-linux-gnu/:../lib ▶"
      "OLDPWD" => "/home/codedmonkey/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/173.4127.29/bin"
      "APPDIR" => "/tmp/.mount_9q6gOB"
      "HOME" => "/home/codedmonkey"
      "DESKTOP_SESSION" => "default"
      "APP_FRONT_CONTROLLER" => "index.php"
      "GIO_LAUNCHED_DESKTOP_FILE" => "/home/codedmonkey/.config/autostart/jetbrains-toolbox.desktop"
      "PERLLIB" => "./share/perl5/:./lib/perl5/:"
      "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" => "1"
      "GTK_MODULES" => "gail:atk-bridge"
      "DBUS_SESSION_BUS_ADDRESS" => "unix:path=/run/user/1000/bus"
      "QT_QPA_PLATFORM_PLUGIN_PATH" => "share/jetbrains-toolbox"
      "GIO_LAUNCHED_DESKTOP_FILE_PID" => "1053"
      "QT_QPA_PLATFORMTHEME" => "qgnomeplatform"
      "APP_DOCUMENTATION_DIRECTORY" => "var/documentation"
      "APP_SYMFONY_CURRENT_VERSION" => "4.0"
      "LOGNAME" => "codedmonkey"
      "JOURNAL_STREAM" => "8:21657"
      "DESKTOP_AUTOSTART_ID" => "10f534d19d90ba769151537821741450900000008520002"
      "OWD" => "/home/codedmonkey"
      "SYMFONY_DOTENV_VARS" => "APP_DOCUMENTATION_DIRECTORY,APP_SYMFONY_VERSIONS,APP_SYMFONY_CURRENT_VERSION,APP_ENV,APP_SECRET,GITHUB_AUTH_METHOD,GITHUB_USERNAME,GITHUB_SECRET"
      "USERNAME" => "codedmonkey"
      "XDG_SESSION_ID" => "4"
      "GNOME_DESKTOP_SESSION_ID" => "this-is-deprecated"
      "WINDOWPATH" => "2"
      "APP_SECRET" => "some+secret"
      "PATH" => "./bin/:./sbin/:./games/:../bin/:../sbin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
      "APPIMAGE" => "/home/codedmonkey/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
      "SESSION_MANAGER" => "local/scrubs:@/tmp/.ICE-unix/852,unix/scrubs:/tmp/.ICE-unix/852"
      "GDM_LANG" => "en_US.UTF-8"
      "XDG_MENU_PREFIX" => "gnome-"
      "XDG_RUNTIME_DIR" => "/run/user/1000"
      "DISPLAY" => ":1"
      "XDG_CURRENT_DESKTOP" => "GNOME"
      "LANG" => "en_US.UTF-8"
      "XAUTHORITY" => "/run/user/1000/gdm/Xauthority"
      "XDG_SESSION_DESKTOP" => "default"
      "SSH_AUTH_SOCK" => "/run/user/1000/keyring/ssh"
      "GSETTINGS_SCHEMA_DIR" => "./share/glib-2.0/schemas/:"
      "SHELL" => "/bin/bash"
      "GDMSESSION" => "default"
      "QT_ACCESSIBILITY" => "1"
      "GITHUB_USERNAME" => "some+key"
      "force_s3tc_enable" => "true"
      "GITHUB_SECRET" => "null"
      "GPG_AGENT_INFO" => "/run/user/1000/gnupg/S.gpg-agent:0:1"
      "XDG_VTNR" => "2"
      "APP_ENV" => ""
      "PWD" => "/home/codedmonkey/development/insights/public"
      "XDG_DATA_DIRS" => "./share/:/usr/share/gnome:/usr/local/share/:/usr/share/"
      "PYTHONPATH" => "./share/pyshared/:"
      "QT_PLUGIN_PATH" => "./lib/qt4/plugins/:./lib/i386-linux-gnu/qt4/plugins/:./lib/x86_64-linux-gnu/qt4/plugins/:./lib32/qt4/plugins/:./lib64/qt4/plugins/:./lib/qt5/plugins/:./lib/i386 ▶"
      "GITHUB_AUTH_METHOD" => "http_token"

Anyway, because `$_SERVER['APP_ENV']` is an empty string, the following line in the default Symfony skeleton doesn't enable the dev environment:

$env = $_SERVER['APP_ENV'] ?? 'dev';

Thus causing none of the bundles explicitly specified as `dev` bundles to run. Changing it to a `?:` fixed it for me. I'm not sure whether this is intended behavior, an empty string does not equal true in my opinion.

**Comment by codedmonkey** [comment]
Continued discussion here https://github.com/symfony/skeleton/issues/53
