### ISSUE TITLE
[Process] setCommandLine() with SSH command causes process to hang

### ISSUE THREAD

**Issue by HornskovVindberg** [symfony/symfony#25716]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

A laravel project calls Process setCommandline with an ssh command. This causes system to 
hang.  Changed back to 3.4.2 and it works.

**Comment by Simperfit** [comment]
Could you please provide a reproducer ?
