### ISSUE TITLE
[HttpFoundation] Remove X-Sendfile internal http headers once they were used ?

### ISSUE THREAD

**Issue by Alsatian67** [symfony/symfony#25722]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

I'm using X-Accel with Symfony & nginx

By https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L210

If I unterstand how it works, when I do something like this : 

```
        BinaryFileResponse::trustXSendfileTypeHeader();
        $response = new BinaryFileResponse($realPath);
        $response->headers->set('X-Sendfile-Type', 'X-Accel-Redirect');
        $response->headers->set('X-Accel-Mapping', '/home/foo/=/protected_files/');
```

Symfony is converting the headers "X-Sendfile-Type" and "X-Accel-Mapping" to a unique "X-Accel-Redirect" header (with a converted url) which will be unterstood by nginx.

So, I'm wondering why these two headers are not removed from the request, once Symfony has done its job.

Currently, the final client receive these two temporary headers and receive useless informations about the server configuration (he knows that X-Accel is used and that the real file location is "/home/foo/").

Don't you want to remove them ?

**Comment by mvrhov** [comment]
Symfony can't remove those headers. It's nginxes/apaches job to do that. 
The nginx/apache wouldn't know that it has to use the X-accel without them!

**Comment by Alsatian67** [comment]
May be I'm wrong, but I unterstand it so :

The Controller set "X-Sendfile-Type" and "X-Accel-Mapping" only to inform Symfony that Symfony has to create a third header "X-Accel-Redirect" (the name of this header is the value of the "X-Sendfile-Type" header, and its value is found using the "X-Accel-Mapping" description.

The server knows nothing about "X-Sendfile-Type" and "X-Accel-Mapping" headers, they are only internaly used to create the good one.

**Comment by Alsatian67** [comment]
But I'm not a security expert, and I don't know if it is a problem to expose these internal headers to the end client.

**Comment by mvrhov** [comment]
If this is true, then you of course are correct and those two headers should be removed.

**Comment by Simperfit** [comment]
@Alsatian67 Do you want to provide the PR ?

I guess we can remove these two headers safely.

**Comment by nicolas-grekas** [comment]
What about https://www.google.fr/search?q=X-Accel-Mapping?

**Comment by Alsatian67** [comment]
@nicolas-grekas 

I also searched on google and found that : https://github.com/symfony/symfony/issues/13502

-> Symfony API has been synchronised with ruby/rack.

So I think "X-Accel-Mapping" is a common framework trick to deal with nginx which want a url. The framework use it only to build an url from the real file path.


X-Accel headers are nginx specific, and the nginx doc, doesn't mention "X-Accel-Mapping" : 

https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/#special-headers

**Comment by msheakoski** [comment]
@Alsatian67 Please see #28502. The x-sendfile-type and x-accel-mapping headers should be added to the incoming request by using add_header in your Nginx website config. They give Symfony a hint about the correct headers to add to the response to trigger Nginx to serve the file directly.

**Comment by Alsatian67** [comment]
If this is true it makes sense. Till yet I had only found examples where these headers where set in Symfony ...

Should the developer then also remove these headers from nginx ?

**Comment by Alsatian67** [comment]
OK, the Rack source code is also documenting this usage @msheakoski  https://github.com/rack/rack/blob/master/lib/rack/sendfile.rb#L46

**Comment by msheakoski** [comment]
I am assuming that Nginx does not pass along the x-accel-* headers to the client since they are internal to Nginx's purposes.

**Comment by Alsatian67** [comment]
OK, I finally understand, that my method never worked ...

1. I had set these headers to the response, which was absolutely wrong.
    Then it was normal that they were passed to the client.

2. I tried to set these headers in nginx using "add_header" or "proxy_add_header".
    It was also wrong, because it doesn't work with a fastcgi_pass.

3. I always believed everything works, because php was serving the file, instead of the nginx X-Accel system.


Working solution, in the nginx configuration :

```
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_split_path_info ^(.*\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param APP_ENV prod;
        fastcgi_param SCRIPT_FILENAME $realpath_mroot$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_param  HTTP_X-Sendfile-Type     X-Accel-Redirect;
        fastcgi_param  HTTP_X-Accel-Mapping    /home/foo/=/protected_files/;

        internal;
    }
```


Everything works well, and this issue was not an issue. Just a missusage. Sorry.

But now I have a real problem : 

This feature doesn't work when uppercase letters are in the real path of the file.
(Because the X-Accel-Mapping value is transformed to lower case here : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L222)

Thank you to everyone.
