### ISSUE TITLE
Symfony 3.4 installation oddity

### ISSUE THREAD

**Issue by WubbleWobble** [symfony/symfony#25727]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

I visited https://symfony.com/download and grabbed the project creation command-line with the intention of creating a 3.4 LTS project.

The command given on the download page was:
`composer create-project symfony/skeleton my_project 3.4`

However, when I did this, although all of the packages downloaded were labelled as v3.4.3, and Symfony identified itself as 3.4, the code that was downloaded into that directory had a distinctly 4.0 smell to it:  
* There was a "public" dir instead of a "web" dir
* There was no "AppBundle" directory inside "src"

I later used the symfony installer tool to create a project:
`symfony new my_project 3.4`

This did correctly install a Symfony instance which both declared itself to be a 3.4 project and also had the expected 3.4 directory structure.

I'm not sure quite where the issue is, or indeed the difference behind the scenes between using the symfony installation tool, and symfony/skeleton, but I definitely seemed to end up getting a copy of a 4.0-based Symfony that was presenting itself as being 3.4.3.

**Comment by javiereguiluz** [comment]
We discussed a bit about this on Symfony Docs repo last week: https://github.com/symfony/symfony-docs/pull/8886

I agree this is confusing. Maybe we can tweak somehow the composer.json file provided by Symfony Skeleton 3.4? https://github.com/symfony/skeleton/blob/3.4/composer.json

**Comment by WubbleWobble** [comment]
The gist I get from your discussion there is that skeleton is good for installing major versions but can't install specific minor versions (e.g. you ask for 3.3 and end up with 3.4 packages)

So I just want to point out that I did actually get 3.4 packages as expected (see below), but that the directory structure was just completely wrong for a 3.4 project, and so if I were to try to follow the 3.4 documentation it wouldn't make any sense at all :D

```
wobble@devbox:~/web$ composer create-project symfony/skeleton my_project 3.4
Installing symfony/skeleton (v3.4.0)
  - Installing symfony/skeleton (v3.4.0): Loading from cache
Created project in my_project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 25 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.59): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.3): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/console (v3.4.3): Loading from cache
  - Installing symfony/routing (v3.4.3): Loading from cache
  - Installing paragonie/random_compat (v2.0.11): Loading from cache
  - Installing symfony/polyfill-php70 (v1.6.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.3): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.3): Loading from cache
  - Installing symfony/http-kernel (v3.4.3): Loading from cache
  - Installing symfony/finder (v3.4.3): Loading from cache
  - Installing symfony/filesystem (v3.4.3): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v3.4.3): Loading from cache
  - Installing symfony/config (v3.4.3): Loading from cache
  - Installing symfony/class-loader (v3.4.3): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/polyfill-apcu (v1.6.0): Loading from cache
  - Installing symfony/cache (v3.4.3): Loading from cache
  - Installing symfony/framework-bundle (v3.4.3): Loading from cache
  - Installing symfony/yaml (v3.4.3): Loading from cache
  - Installing symfony/dotenv (v3.4.3): Loading from cache
```

**Comment by xabbuh** [comment]
I think we need to make a decision whether we want to show the Flex way or the old way using the installer for Symfony 3.4. Right now, this is inconsistent as you end up using Flex when using the command displayed on the download page, but all the docs contents still refer to the old structure as we only adapted the 4.0 docs for the Flex way.

**Comment by xabbuh** [comment]
So IMO we should still show the installer command for 3.4 on the download page *or* backport most of the changes we did for the 4.0 docs to the 3.4 branch.

**Comment by WubbleWobble** [comment]
My five pence would be to go for the "show the install command for 3.4" option, as 4.0 is where you've introduced Flex, and going from 3.* to 4.* is where I expect to have to study and learn new things.

If you backported your 4.0 docs to 3.4, then you'd end up messing up those with different use cases,  such as users who were simply upgrading from 3.3 to 3.4.

**Comment by Tobion** [comment]
> If you backported your 4.0 docs to 3.4, then you'd end up messing up those with different use cases, such as users who were simply upgrading from 3.3 to 3.4.

If you are upgrading a project, you don't go to the download page.
Also you can use flex with SF 3.3 even. But most people associate flex with sf 4. And it might be too confusing to explain all these things when you just want to download something.

**Comment by WubbleWobble** [comment]
> If you are upgrading a project, you don't go to the download page.

What I generally mean to say is that if you backport the documentation to make the 3.4 documentation flex-style, then you are messing it up for those who are used to non-flex style (such as those who already have a non-flex style 3.4 project, or are upgrading from 3.3)

Or put another way, having the 3.4 documentation remain non-flex style would benefit many more people than backporting things to make it flex style - something that would cause a lot of confusion :D

**Comment by kejwmen** [comment]
Maybe we can just call 4.0 docs `3.4 with flex/4.0`?
Alternatively, could 3.4 docs point out that 3.4 is actually 4.0 without deprecated features, so people installing 3.4 with flex (preferred way) can safely use 4.0 docs?

**Comment by murilolobato** [comment]
For now, what should we do as a work around? Install 3.4 LTS and look at the 4.0 docs?

**Comment by chalasr** [comment]
What needs to be done here?

**Comment by ostrolucky** [comment]
I suggest to replace with issue in symfony-docs. Flex structure in Symfony 3.4 is fine.

**Comment by fabpot** [comment]
I'm closing this issue as there is nothing wrong with Symfony itself. However, this is indeed a documentation issue.

**Comment by alexseif** [comment]
I am not sure, if this is closed. 
The issue here, is that you install a Symfony version with an expected structure and you get a different structure, in your confusion you seek the docs and find that even the docs describe your expected structure.
