### ISSUE TITLE
bin/console required Memcached 2.2

### ISSUE THREAD

**Issue by rakodev** [symfony/symfony#25723]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

When I execute this command:
`php bin/console`

I have this response:
<pre><code>Symfony 4.0.2 (kernel: src, env: dev, debug: true)

In MemcachedTrait.php line 84:
  Memcached >= 2.2.0 is required  
</code></pre>

But the last Memcached available is 1.5.4
https://memcached.org/downloads

**Comment by nicolas-grekas** [comment]
2.2.0 is the minimum version of the *extension*! if you think the message could be improved, PR welcome.

**Comment by rakodev** [comment]
Ok I found it, it's because I don't have this line in my /etc/php/7.1/cli/php.ini file:
<code>extension=memcached.so<code>
