### ISSUE TITLE
@Assert\Valid() doesn't work with groups 

### ISSUE THREAD

**Issue by KamilPesek** [symfony/symfony#25726]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.4.3

I need to use conditional validation for some property, so I added **validation groups** to **Valid constraint** (see below). But this validation is not called. 
I tried it without groups option and for another constraint (NotBlank) and that's working. So I assume I have everything right.

I also created small project to reproduce this error - https://ubkcz-my.sharepoint.com/personal/kamil_pesek_ubk_cz/_layouts/15/guestaccess.aspx?docid=0d0dd0ef2934245e691cf568ff8cf0c96&authkey=AbAS0G-iJ8kcm9he7J-965M&e=vsPQRf

Thx for you answers!
```
/**
     * @Assert\Valid
     */
    protected $childWorking;

    /**
     * @Assert\Valid(
     *  groups={"extended"}
     * )
     */
    protected $childNotWorking;

    /**
     * @Assert\NotBlank(
     *  groups={"extended"}
     * )
     */
    protected $blankWorking;

    /**
     *
     * Set conditional validation groups
     *
     * @return array
     */
    public function getGroupSequence()
    {
        $groups[] = 'ParentEntity';

        if (1 === 1) {//some extra condition
            $groups[] = 'extended';
        }

        return [$groups];
    }

```

**Comment by xabbuh** [comment]
The nested object is only validated in the group(s) that you specified with the `Valid` constraint (i.e. `extended` in your example). So you need to add these groups to the constraints of your nested object too.

By the way, you also had an issue in the implementation of your `getGroupSequenceMethod()`. It must not return a nested array:

```php
public function getGroupSequence()
{
    $groups = ['ParentEntity'];

    if (1 === 1) {//some extra condition
        $groups[] = 'extended';
    }

    return $groups;
}
```

I am closing here as the observed behaviour is expected.
