### ISSUE TITLE
Swiftmailer spool send try to connect to localhost instead of gmail

### ISSUE THREAD

**Issue by rakodev** [symfony/symfony#25724]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

İn my .env file I have a configuration like this:
<code>MAILER_URL=gmail://username:password?encryption=tls&auth_mode=oauth</code>

My swiftmailer.yaml file:
<pre><code>swiftmailer:
    url: '%env(MAILER_URL)%'
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'
</code></pre>

My dev/swiftmailer.yaml file:
<pre><code>swiftmailer:
    disable_delivery: false</code></pre>

But when I try to spool emails:
<code>php bin/console swiftmailer:spool:send --message-limit=10 -v</code>
I have this error message:
<pre><code>[2018-01-09 11:39:27] Processing default mailer spool... 
In StreamBuffer.php line 269:
  [Swift_TransportException]                                                         
  Connection could not be established with host localhost [Connection refused #111]</code></pre>

Why it said localhost when I have gmail in my configuration?
Do I need to configure a mail server in my localhost?

**Comment by xabbuh** [comment]
Swiftmailer is not part of the Symfony core. I suggest you open an issue on the [Swiftmailer](https://github.com/swiftmailer/swiftmailer) or [SwiftmailerBundle](https://github.com/symfony/swiftmailer-bundle/) repository instead.
