### ISSUE TITLE
Auto add the `cache-control` headers?

### ISSUE THREAD

**Issue by wenmingtang** [symfony/symfony#25736]
| Q                | A
| ---------------- | -----
| Bug report?      | Maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

hello everybody,

I need my CDN service cache my website, so I set 

```php
    /**
     * @Route("/", defaults={"page": 1}, name="homepage")
     * @Method("GET")
     * @Cache(smaxage="3600")
     */
    public function indexAction(ArticleRepository $articles, int $page): Response
    {
        $articles = $articles->findLatest($page);

        return $this->render('article/index.html.twig', [
            'articles' => $articles
        ]);
    }
```

then the `cache-control` header is `cache-control:max-age=0, must-revalidate, private, s-maxage=3600`

It contains the `max-age=0, must-revalidate, private` is not what I want.

What should I do?

Because the response header, so my CDN cannot cache my pages.

thx.

**Comment by nicolas-grekas** [comment]
That's because your page is using the session, so that it's different per-user, and thus cannot be shared.

**Comment by wenmingtang** [comment]
@nicolas-grekas, Thanks.

But I not login my account, I want to shared,  Because  I need CDN cache my pages, can't be implemented?

**Comment by nicolas-grekas** [comment]
I guess you need to understand where the session is used, and then figure out a way to not call that code.

**Comment by emodric** [comment]
> your page is using the session, so that it's different per-user, and thus cannot be shared.

@nicolas-grekas I still don't understand the rasoning behind this. Why force those headers in the first place? In eZ Platform, it's possible (and on Symfony 2.8 behaves that way) to have a single HTTP cache for two different users, since eZ Platform varies the cache not by cookie, but by user policies, by using `X-User-Hash` header from FOS HTTP Cache bundle and varying on it instead on cookie. So if two different users have a same set of policies, they can have the same http cache which is then cached by Varnish. With eZ Platform on Symfony 3.4, this is broken.

**Comment by emodus** [comment]
Yes, on SF 3.4.3 varnish skipping cache.

**Comment by nicolas-grekas** [comment]
@emodric that's very likely, yet Symfony doesn't know about this logic in eZ. Not sending this header was a bug, on which eZ relied apparently. This should be fixed on eZ side.

**Comment by emodric** [comment]
Agreed, but nevertheless, it breaks the way eZ worked for years.

Forcing these headers should at least be configurable.

**Comment by nicolas-grekas** [comment]
Symfony should respect HTTP semantic by default, this is not an option IMHO.

**Comment by emodric** [comment]
I'd rather say Symfony should first respect what user/developer intended to do with the Response object in his controller. Symfony overriding something user might've explicitly set in his controller is not a good thing IMO, without being able to disable it.

Is there a standard or RFC specifying that these headers must be set if session cookie is present?

**Comment by nicolas-grekas** [comment]
> Is there a standard or RFC specifying that these headers must be set if session cookie is present?

It's "if session cookie is present", it's "if the session is read". See HTTP RFC.

@emodric you should open an issue on eZ really. The behavior here is correct.

**Comment by andrerom** [comment]
@nicolas-grekas Noot looking in depth on this, but when was it introduced?
From the sound of it be aware this breaks FOSHttpCache _(which is what we are using/extending)_.

**Comment by andrerom** [comment]
That said, I agree on the RFC, however to really follow it we all need to look at this from a system perspective.

Where we want this behaviour is from the reverse proxy and out.
Not from app breaking reverse proxy behaviour on current applications and installs out there. In today's world we _(frankly anyone using Varnish and touching it's VCL really)_ have custom logic in between app and reverse proxy, so reverse proxy is effectively part of the app here.

/cc @dbu

**Comment by dbu** [comment]
with FOSHttpCache, we explicitly set cache-control headers. unless you set a response to be cacheable, it will still be no-cache. is the current implementation in the response object preventing the application from explicitly setting cache-control headers or does it merely change defaults when there is a cookie?

**Comment by nicolas-grekas** [comment]
Here is the most recent fix on this, it should give you the answers: #25699

**Comment by emodric** [comment]
@dbu As far as I understand, this prevents and overrides headers set by the app in controllers, no questions asked (presuming session is present and started)

**Comment by nicolas-grekas** [comment]
That's correct, you need a listener registered after the SessionListener to override this behavior.
There is no way around internally, so you should do with.

**Comment by dbu** [comment]
ugh. well i think it makes sense in all cases except when we do special things where it does make sense to maybe cache a response. its not "hardcoded" in the Response itself, we can still overwrite it. we could put the FOSHttpCacheBundle listener to `-1001` - but then if you just configure cache control rules that match on paths, but not use the user context system, we could re-introduce the cache mixup bugs that have been fixed in #25699 .

in FOSHttpCacheBundle we provide the [reverse-proxy-ttl](http://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/headers.html#reverse-proxy-ttl) custom header and configuration for varnish / a listener for symfony cache kernel to use that over the cache-control header. that is safer, because all systems after the reverse proxy indeed must not cache this. we should encourage people to only use that for user context caching. we have to check if that header is still used when a response is private.

its a tricky thing either way - we do not want unsafe defaults, and want to make it at least difficult to shoot yourself into the foot.

i am quite busy atm, if somebody can have a deeper look into it and propose a pull request, please do.

**Comment by pixeltreiber** [comment]
This could be related https://github.com/symfony/symfony/issues/25826#issuecomment-358788270

**Comment by nicolas-grekas** [comment]
Closing as discussed.

**Comment by teohhanhui** [comment]
@nicolas-grekas 

> It's "if session cookie is present", it's "if the session is read". See HTTP RFC.

Could you kindly point us to the relevant RFC sections on this? I cannot find any mention of it in RFC 7234: https://tools.ietf.org/html/rfc7234

**Comment by nicolas-grekas** [comment]
@teohhanhui all the RFC. It's about what can be cached or not. As soon as a page contains a check based on the session, we cannot assume without external knowledge that it doesn't contain personal data/state. As such the default must be "private".

**Comment by teohhanhui** [comment]
I definitely agree about the default. No arguments there. But overriding what the user has explicitly set in their application is going much further than having a good default.

**Comment by apfelbox** [comment]
> we cannot assume without external knowledge

The default is fine. But this "external knowledge" is exactly the app developer, that says "yes, I know all of that, but the response is *still* cacheable". Why prevent it then?

**Default** is fine. **Forcing** it not and might be considered a bug imo.

**Comment by teohhanhui** [comment]
If we set the header only if no cache-related headers have been set, it'll greatly reduce the pulling-out of hair for many people. :smile:

**Comment by nicolas-grekas** [comment]
Using the session without noticing is super easy: just dump flash messages in your layout and done. I would not consider that the explicitly set "public" C-C is enough to consider it not a mistake when the session has also been used. The current logic considers this as a conflict and defaults to the safest. If you really want to make session-related state into shared caches, you are required to do extra work yes. That's expected to me.

**Comment by apfelbox** [comment]
I don't argue with the reasoning, as in a general case it is very likely that caching a response that is using the session will be a bug.

I guess as workaround a custom response listener and passing the cache config in `Request::$attributes` and reapplying them in the listener might work.

However – do we log anything in case we are overriding explicitly set cache headers? Might reduce the amount of wtf in this case.

**Comment by teohhanhui** [comment]
The correct thing to do is to let the user opt-in to this stricter check, and we could deprecate not using the strict mode, to be removed in the next major version.

**Comment by nicolas-grekas** [comment]
@apfelbox I feel like you may have missed #26681

**Comment by apfelbox** [comment]
@nicolas-grekas I did indeed. That looks perfect, so 👍 all around. 

Sorry for the noise.

**Comment by deniz777** [comment]
I am using just http foundation 4.1 and twig packages. They are creating duplicated response headers like that:
`Cache-Control: max-age=0, private, must-revalidate`
`Cache-Control: no-cache, private`
I know sending duplicated responses are acceptable but sending same values more than once is valid? I mean "private" value in this example. Can somebody answer this?

**Comment by albingi** [comment]
You can add this header'Symfony-Session-NoAutoCacheControl' in the response to force to use your Cache-Control : 
https://github.com/symfony/http-kernel/blob/master/EventListener/AbstractSessionListener.php#L83-L90
