### ISSUE TITLE
Recursive validation might be broken with reused constraint validators

### ISSUE THREAD

**Issue by hchonov** [symfony/symfony#25739]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all?

We've encountered an issue in Drupal 8 where the constraint validator instances are shared and not newly instantiated for each started validation. The constraint validators get the current execution context injected through `\Symfony\Component\Validator\ConstraintValidatorInterface::initialize($context)`, which in case of shared validator instances would cause problems in a recursive validation where a constraint validator is triggering a new validation chain leading to retrieving the same validator instance again and changing its context, in which case the root call suddenly will become the context from the subsequent validation.

I've seen that Symfony has a static cache for the constraint validator instances in `\Symfony\Component\Validator\ConstraintValidatorFactory::getInstance()` similar to the one in Drupal, therefore I think that the same problem might exist in Symfony as well.

The problem has been detected in https://www.drupal.org/project/drupal/issues/2438017#comment-12412763 and a new issue has been opened to deal only with this problem - https://www.drupal.org/project/drupal/issues/2935405.

**Comment by xabbuh** [comment]
Would you be able to provide a failing test case?

**Comment by hchonov** [comment]
Unfortunately I am not familiar enough with Symfony to prepare a test case. I've only reported the issue as the recursive validation in Drupal and Symfony looks pretty similar and I think that there is a high chance that Symfony has the same issue.

**Comment by xabbuh** [comment]
Closing for now then. We can reopen if someone can come up with a failing test.
