### ISSUE TITLE
Validating form with UniqueEntityValidator throws exception  v => 4.0

### ISSUE THREAD

**Issue by jkhaled** [symfony/symfony#25730]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

### Description

Using EntityReposiroty as service 'autowiring' with UniqueEntityValidator produce exception 
```php 
The "\App\Repository\UserRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".
```
### Steps to Reproduce

1. I have a UserEntity  with unique entity validator
```php  
/**
 * @ORM\Table(name="app_user")
 * @ORM\Entity(repositoryClass="\App\Repository\UserRepository")
 *
 * @UniqueEntity(fields="email", message="Email Already exist")
 */
class User implements AdvancedUserInterface, \Serializable
{}
```
2.  with repository class (autowired service)
```php
class UserRepository extends ServiceEntityRepository implements UserLoaderInterface
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, User::class);
    }
}
```

3. from a controller (exp: registration) when I try to validate a form
```php 
 public function register(
        Request $request,
        FormFactoryInterface $formFactory,
        UserPasswordEncoderInterface $passwordEncoder,
        Environment $twig,
        EntityManagerInterface $entityManager
    ): Response
    {
        $user = new User();
        $form = $formFactory->create(UserType::class, $user);
        $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {} // throws exception
    }
}
```
#### Expected behavior

check the data and validate the form and continue 

#### Actual behavior

throws exception  from the class  ```\Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator::validate()``` at line **136**
 ```php
  } else {            
        $repository = $em->getRepository(get_class($entity));
 }
```
### Affected Versions
>4.0

**Comment by xabbuh** [comment]
I think your problem is the leading backslash in the `repositoryClass` config (the class name given there must match the service ID). Try changing it to something like this:

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
```

**Comment by jkhaled** [comment]
@xabbuh  the  ```UniqueEntityValidator ``` try to call the Reposiroty without DIC (container) , and tha leads to the exception  because the ```EntityManager``` is not injected

**Comment by xabbuh** [comment]
@jkhaled Since doctrine/DoctrineBundle#727, the repository can be fetched from the container. Did you try if changing the `repositoryClass` option changes anything?

**Comment by jkhaled** [comment]
@xabbuh yes it works , thank you
