### ISSUE TITLE
[RFC] `server:run` starts Encore

### ISSUE THREAD

**Issue by sroze** [symfony/symfony#25748]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

The work that has been done on Encore is great, it's a smooth entry for developers not much familiar with webpack and all these things. But there is one thing they need to do: start it. On most of my `Encore`d projects, I've got the following `Makefile`:
```Makefile
dev:
	bin/console server:start
	./node_modules/.bin/encore dev --watch
```

But what if, like other framework like Phoenix (Elixir), we would start `./node_modules/.bin/encore dev --watch` when starting the server in the `dev` environment?

**Comment by jvasseur** [comment]
This means you wouldn't be able to start the server without encore. Maybe create another command "bin/console start" that starts everything needed in the project ?

**Comment by apetitpa** [comment]
Or maybe not starting Encore by default but only when using `bin/console server:start --with-encore` ?

**Comment by jvasseur** [comment]
The advantage of a separate command is that it could be implemented as an extension point where bundles (or your project with a config option) could add commands to run.

Some example use cases:
 - Start a background worker
 - Use PHP-PM instead of the WebServerBundle
 - Use another frontend build tool

It also have the advantage to work if you use encore but not the WebserverBundle.

**Comment by curry684** [comment]
> `./node_modules/.bin/encore dev --watch`

Which I definitely don't want in my current project, I use `yarn encore dev-server --port 8080`. Some people use dev, others use dev-server. Those often want to specify the port. Which may vary depending on the number of projects you have open, and therefore sometimes during the day.

If I were using Phoenix in this case it would be making an opinionated choice for me I don't want. Symfony's core strength is not being very opinionated. Developers that really want to eliminate the extra command can write the 2 liner bash-script or Makefile that fits their specific current needs themselves methinks.

**Comment by sroze** [comment]
> so it's simpler for users to just create a Makefile task or a Bash script

If the users need to write a bash script or a Makefile for the very basics of writing an application, there is something wrong here IMHO. That was Assetic's power, not to have to run any watcher or anything.

My point is that a lot of "backend developers" are not used to these things such as grunt, gulp or webpack. In fact, maybe they should not even have to know the details and run a separate command to generate the assets, it should be done when installing the application. That last sentence: that's exactly what was happening before (i.e. the `installAssets` script in Composer's `post-install`) :)

I agree with @jvasseur as well: maybe it could wraps more than just the server and the assets and should be separate from the server command.

**Comment by javiereguiluz** [comment]
Let's not exaggerate about this:

> If the users need to write a bash script or a Makefile for the very basics of writing an application ...

You don't need to write anything to work with Symfony ... but if your application has many "moving parts" that must be started before you can work on your app ... then you can put those commands in a bash script and just run `./start` everyday before starting on your app.

Moreover, most people don't work alone on projects, so there's probably a script like that already created for you.

**Comment by sroze** [comment]
Yeah, it was a bit strong on purpose, I have to admit 😄I got your PoV though. I still believe we can improve this because as you say, teams or individuals usually have to create a script for such things.

**Comment by curry684** [comment]
Given that webserver has its own bundle nowadays and its own Flex recipe it's actually trivial to give it its own best-practice configuration for dev environments:
```
webserver:
  encore:
    run: watch  # one of no, watch or server
    port: 8080 # only used if run eq server
```
I'm open to that as long as I can disable it once forever, and the config is only considered if Encore is actually installed.

**Comment by Simperfit** [comment]
@sroze WDYT of this proposal ? Do you want to implement it :p ?

**Comment by sroze** [comment]
I like the idea but I’d prefer somebody else to implement it. Wanna take
it? ;)

**Comment by stof** [comment]
Should we rather recommend using the [Symfony local server](https://symfony.com/doc/current/setup/symfony_server.html) instead, which already supports such feature and has better performance than WebserverBundle (because it uses PHP-FPM rather than `php -S`) ?

**Comment by Simperfit** [comment]
So that means deprecated WebserverBundle in favor of the Symfony local server ?

**Comment by fabpot** [comment]
I would indeed use the Symfony local server for that.

@Simperfit I think this is something we need to do at some point.

**Comment by javiereguiluz** [comment]
Now that WebServerBundle is deprecated and soon will be removed ... I've created an issue in the Symfony loca web server issue repository to discuss about this: https://github.com/symfony/cli/issues/109 Thanks!
