### ISSUE TITLE
[RFC] Create a dedicated WebProfiler tab for the Session

### ISSUE THREAD

**Issue by sroze** [symfony/symfony#25747]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

There are a lot of issues related to the "Cache". The "cache" is not working... because the users are using a session, for whatever reason.

I suggest we do two things:
1. Move the "Session" in its own tab within the profiler, so it's not hidden in the "Request / Response" tab. Also, we can display a green/orange status for started and not started.
2. We could track what started the session by decorating it, and displaying what first started the session

**Comment by javiereguiluz** [comment]
About this:

> Also, we can display a green/orange status for started and not started

We should change it to follow the common toolbar logic:

* If there is no session: don't show the panel
* If there's a session: show the panel (no green color because the session can't succeed/fail as doctrine, forms, etc.)

**Comment by Simperfit** [comment]
I agree with this feature, it will be better for developers. 👍

**Comment by ostrolucky** [comment]
Can you reference those issues which gave you incentive to create this RFC? I'm not aware of them and I am not sure from the description how would this proposal solve those.

For now I'm 👎 , I don't think there is enough useful information regarding sessions to create new profiler section. Even more against I am for creating new item in *toolbar*. That space is very constrained and this doesn't bring enough value.

I'm of course 👍 for `2.`, but that can be built into current section

**Comment by javiereguiluz** [comment]
Closing as fixed by #36364.
