### ISSUE TITLE
All requests hang with New Relic module as of v2.8.33

### ISSUE THREAD

**Issue by oradwell** [symfony/symfony#25743]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.33

Using Symfony 2.8.33 with New Relic PHP module on PHP 5.5.9 causes all web requests to hang. 2.8.32 did not have any issues.

**Comment by nicolas-grekas** [comment]
Same as #25718 isn't it?

**Comment by dbu** [comment]
most likely. for us it happened during deployment already, because there where some hidden errors (`@unlink()` calls) during a composer task.

**Comment by nicolas-grekas** [comment]
what does `var_dump(set_exception_handler('var_dump'))` display when new relic is enabled?

**Comment by nicolas-grekas** [comment]
Can you please confirm that #25755 fixes the issue?

**Comment by oradwell** [comment]
@nicolas-grekas 
```
php > var_dump(set_exception_handler('var_dump'));
string(26) "newrelic_exception_handler"
```
I'll test and come back to you

**Comment by oradwell** [comment]
@nicolas-grekas yes, it works!
