### ISSUE TITLE
[WebServerBundle] Under certain conditions, APP_ENV is an empty string

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#25754]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4+

Steps to reproduce:

1. `composer create-project symfony/skeleton my-project`
2. `cd my-project`
3. `composer require --dev profiler webserver`
4. `bin/console server:start`
5. Navigate to http://127.0.0.1:8000/foo/bar
6. You get a 404 as expected and the profiler toolbar shows the `dev` environment as expected
7. `mkdir public/foo`
8. Again navigate to http://127.0.0.1:8000/foo/bar
9. Notice the profiler toolbar is missing and if you inspect the `$env` var in `public/index.php` it is an empty string

I think this bug is related to #23799 (https://github.com/symfony/symfony/pull/23799/files#diff-17a9fecf57df3ecbd28ddf129c45ff70R157) but I'm not sure why creating a the `/foo` directory causes this issue.

A work around is to change the following in `public/index.php`:

```php
if (!isset($_SERVER['APP_ENV'])) {
```

to:

```php
if (!isset($_SERVER['APP_ENV']) || !$_SERVER['APP_ENV']) {
```

**Comment by nicolas-grekas** [comment]
or if (empty(...))
but where does the empty string come from?

**Comment by kbond** [comment]
I think in that linked diff, setting `APP_ENV` to `false` - if I remove that line (and restart the webserver) it works as expected.

**Comment by fabpot** [comment]
Setting `APP_ENV` to `false` is wrong. We should fix that line.

**Comment by kbond** [comment]
If you inspect the `$_SERVER` variable at the top of the front controller without the `public/foo` dir it doesn't contain any `APP_*` keys but with the `public/foo` dir, it shows all the `APP_*` keys (but with with `APP_ENV => ""`)

**Comment by Simperfit** [comment]
@kbond Do you want to provide a PR to fix this behaviour ?

**Comment by kbond** [comment]
What should the fix be? I'm also not sure why the existence of the subfolder causes the issue.

**Comment by rakeev** [comment]
Another case:
@Route("/{path}")

GET http://127.0.0.1:8000/foo
env=dev

GET http://127.0.0.1:8000/foo.json (dot present)
env= (empty)

**Comment by kbond** [comment]
Running my steps to reproduce above, I no longer see the issue.

@rakeev I tried your example and didn't see the issue anymore either - can you confirm?

If someone else can confirm this is no longer happening we can close this.

**Comment by rakeev** [comment]
Does not reproduce on latest version

**Comment by xabbuh** [comment]
Thanks for the feedback. I am closing then.
