### ISSUE TITLE
Custom exception handler in command

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#25769]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4

Hello, first of all excuse me if this is not a BC break or if my code is really bad but the exception / error handling is something I don't master at all.

So in one of my project command, I did this : 
```php
$this->getApplication()->setCatchExceptions(false);
$errorHandler = ErrorHandler::register(null, false);
$errorHandler->throwAt(E_ALL, true);
$errorHandler->setExceptionHandler(function () {
	// .... my code
});
```
 to execute something whenever a Symfony command throws an exception or has any error.

In 3.3 and before, if this command throws an exception it goes in my custom exception handler. In 3.4 it doesn't.

**Comment by nicolas-grekas** [comment]
Can you check if #25753 changes that?

**Comment by fancyweb** [comment]
No it doesn't fix it.

If it can help, this is the output I get for : 
```php
        $this->getApplication()->setCatchExceptions(false);
        $errorHandler = ErrorHandler::register(null, false);
        $errorHandler->throwAt(E_ALL, true);
        $errorHandler->setExceptionHandler(function () {
            die('INSIDE MY CUSTOM EXCEPTION HANDLER');
        });

        throw new \Exception('MY EXCEPTION MESSAGE');
```

![exc](https://user-images.githubusercontent.com/3658119/34834644-d3b58f82-f6f2-11e7-94b8-e181c83ca25d.png)

The first run is 3.4, the second 3.3.
