### ISSUE TITLE
Add a ProcessSignaledException

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#25768]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | v3.4.3

As for `ProcessTimedOutException`, it would be great to have an exception when a signal has been sent to the sub-process.

Basically, on this line: https://github.com/symfony/symfony/blob/1df45e43563a37633b50d4a36478090361a0b9de/src/Symfony/Component/Process/Process.php#L389-L391

This would allow to catch signaled sub-process on a higher code level and retrieve the concerned process when running many, thanks to the process property of the exception.

**Comment by lyrixx** [comment]
Hello @Soullivaneuh 
This is a good idea.
Do you want to submit the PR?

**Comment by Soullivaneuh** [comment]
Hey @lyrixx sure, I'll do it ASAP! :+1:
