### ISSUE TITLE
Process are differents, before and after cache ?

### ISSUE THREAD

**Issue by GuigZ-** [symfony/symfony#25766]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Hi,

(Sorry for my bad english, i hope that you understand my issue 😄 )

I use doctrine on my project to set a dispatcher with different key. To apply this, i use a wrapperClass in doctrine.

So for my map, i need the request. And i have two different process.

**First process without cache:**
Doctrine was built before the request stack was hydrated.

**Second process with cache:**
Doctrine was built after the request stack was hydrated.

For my business, at the first time have not a real stack for my needs.

**Comment by xabbuh** [comment]
Are you accessing the request stack in the constructor of your service?

**Comment by GuigZ-** [comment]
At the first process, RequestStack is empty... but when the cash was built yes ...

**Comment by xabbuh** [comment]
This doesn't answer the question whether you are trying to access the request stack in the constructor of your service.

**Comment by GuigZ-** [comment]
Oh sorry,

yes i try to access in my constructor.

**Comment by xabbuh** [comment]
Then the solution is not to do that. With dependency injection, you don't have much control on when your service is created. So other parts of the application may not yet be in the state that you expect. Just store the request stack in a property and access it when you actually need it.

I am going to close here as there is no bug.

**Comment by GuigZ-** [comment]
Why ... sf has not a same process ... 

`class Dispatcher
{
    /**
     * @var Request
     */
    private $request;
    /**
     * @var array
     */
    private $apiKeys;

    /**
     * @param RequestStack $request
     */
    public function __construct(RequestStack $request, array $apiKeys)
    {
        $this->request = $request;
        $this->apiKeys = $apiKeys;
    }
}
`

I store request stack in property ...

**Comment by xabbuh** [comment]
In this case, we will need some example application that allows to reproduce your issue.

**Comment by GuigZ-** [comment]
```yaml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        wrapper_class: App\Dispatcher\DBAL\DispatcherConnection```

Doctrine configuration for my wrapper class.

```php
<?php

namespace App\Dispatcher\DBAL;

use Doctrine\Common\EventManager;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver;

class DispatcherConnection extends Connection
{
    const DISPATCH = 'connectionDispatcher';

    /**
     * @param array              $params
     * @param Driver             $driver
     * @param Configuration|null $config
     * @param EventManager|null  $eventManager
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    public function __construct(
        array $params, Driver $driver, ?Configuration $config = null, ?EventManager $eventManager = null
    ) {
        $eventArgs = new DispatcherEventArgs($params);

        if ($eventManager) {
            $eventManager->dispatchEvent(self::DISPATCH, $eventArgs);
        }

        parent::__construct($eventArgs->getParams(), $driver, $config, $eventManager);
    }

}```

My wrapper class. (I think that the problem is here)

```php
<?php

namespace App\Dispatcher\DBAL;

use App\Exception\ApiKeyNotFoundException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

class Dispatcher
{
    /**
     * @var Request
     */
    private $request;
    /**
     * @var array
     */
    private $apiKeys;

    /**
     * @param RequestStack $request
     */
    public function __construct(RequestStack $request, array $apiKeys)
    {
        $this->request = $request;
        $this->apiKeys = $apiKeys;
    }

    /**
     * @param DispatcherEventArgs $args
     *
     * @throws ApiKeyNotFoundException
     */
    public function connectionDispatcher(DispatcherEventArgs $args)
    {
        $apiKey = $this->request->headers->get('apikey');

        if (!in_array($apiKey, $this->apiKeys)) {
            throw new ApiKeyNotFoundException(sprintf('Api key %s not found', $apiKey));
        }

        $params = $args->getParams();

        $params['dbname'] = array_flip($this->apiKeys)[ $apiKey ];

        $args->setParams($params);
    }
}```

**Comment by GuigZ-** [comment]
So, i fix my bug with multiple manager for one connection ... but multiple db.

Sorry for my issue.
