### ISSUE TITLE
[DependencyInjection] ArrayNodeDefinition::canBeEnabled() doesn't make the configuration disabled by default

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony#25760]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Consider the following configuration:

```php
$builder = new TreeBuilder();
$root = $builder->root('acme_foo');
$root->canBeEnabled();
```

**Expected behaviour**

If the section wasn't provided in configuration, it will be disabled.

**Actual Behaviour**

The section is enabled unless it was explicitly disabled. 

**Supporting information**

It only seems to be an issue for root nodes. Any child nodes work as expected (i.e. `$root->children()->arrayNode('foo')->canBeEnabled()`).

The docblock for `canBeEnabled()` says that the section should be disabled by default (which is also what I expected):

```php
    /**
     * Adds an "enabled" boolean to enable the current section.
     *
     * By default, the section is disabled. If any configuration is specified then
     * the node will be automatically enabled:
     *
     * enableableArrayNode: {enabled: true, ...}   # The config is enabled & default values get overridden
     * enableableArrayNode: ~                      # The config is enabled & use the default values
     * enableableArrayNode: true                   # The config is enabled & use the default values
     * enableableArrayNode: {other: value, ...}    # The config is enabled & default values get overridden
     * enableableArrayNode: {enabled: false, ...}  # The config is disabled
     * enableableArrayNode: false                  # The config is disabled
     */
```

**Comment by Simperfit** [comment]
Do you want to submit a PR to fix this behaviour ?

**Comment by jakzal** [comment]
@Simperfit I haven't got the time to find the root cause of the problem yet. Feel free to pick it up if you're available :)

**Comment by kejwmen** [comment]
@jakzal could you provide us a reproducer?

I tried at d78a98d793c2846d6decbff652d63f981e4f32f4 with test cases like this:

```
$builder = new TreeBuilder();

$builder->root('test')
	->canBeEnabled();

$tree = $builder->buildTree();
$children = $tree->getChildren();

$this->assertFalse($children['enabled']->getDefaultValue());
```

```
$builder = new TreeBuilder();

$builder->root('test')
	->canBeEnabled();

$tree = $builder->buildTree();

$processor = new Processor();
$result = $processor->process($tree, array());

$this->assertEquals(array('enabled' => false), $result);
```

And these work just fine.

Either I misunderstood your issue or it's not configuration component issue,but something higher.

**Comment by jakzal** [comment]
@kejwmen try the same in a full Flex project.

**Comment by kejwmen** [comment]
@jakzal reproduced, thanks ;)

**Comment by xabbuh** [comment]
Can you please check #25891?

**Comment by xabbuh** [comment]
@kejwmen Thanks so much for investigating the cause of this issue. This helped a lot fixing it.

**Comment by kejwmen** [comment]
that's my first regression, glad I was at least able to find the real cause here ;)
