### ISSUE TITLE
Stuck in a loop

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#25774]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | v4.0.3

I got a use case where Im stuck in this loop: 

https://github.com/symfony/symfony/blob/v4.0.3/src/Symfony/Component/Debug/ErrorHandler.php#L567-L576

```
$handler = self::$reservedMemory = null;
        $handlers = array();
        while (!is_array($handler) || !$handler[0] instanceof self) {
            $handler = set_exception_handler('var_dump');
            restore_exception_handler();
            if (!$handler) {
                break;
            }
            restore_exception_handler();
            array_unshift($handlers, $handler);
        }
``` 

For each iteration I the `$handlers` array get one more item in the array. The item is `"newrelic_exception_handler"`.

**Comment by nicolas-grekas** [comment]
Votes pending on #25755 :)

**Comment by Nyholm** [comment]
Wow, you are quick... It took me a week to find this issue.
