### ISSUE TITLE
security json_login doesn't allow login_path

### ISSUE THREAD

**Issue by AlexandreKilian** [symfony/symfony#25776]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.4

Over a year ago, a new json_login firewall option was introduced (see [here](https://symfony.com/blog/new-in-symfony-3-3-json-authentication)). Unfortunately, this does not allow the parameter login_path in order to redirect users to login if they access a route.
Configuring both form_login and json_login doesnt work because form_login is used instead of json_login, even if form_login has no check_path defined

**Comment by chalasr** [comment]
The `json_login` listener is stateless oriented, meaning no redirection. If you want to use it as a form_login, you have to implement your own `failure_handler`.
