### ISSUE TITLE
[Security] AuthenticationException not implementing ExceptionInterface 

### ISSUE THREAD

**Issue by paq85** [symfony/symfony#25770]
Is there any reason why `\Symfony\Component\Security\Core\Exception\AuthenticationException` does not implement `\Symfony\Component\Security\Core\Exception\ExceptionInterface`?

I would like to be able to catch all kind of Security related exceptions simply by using 
```php
} catch (\Symfony\Component\Security\Core\Exception\ExceptionInterface $sex) {
```
and I'm not able to catch for example `\Symfony\Component\Security\Core\Exception\BadCredentialsException` using that `catch`

Cheers.

**Comment by sroze** [comment]
Oups, that's a good point. I think this should be fixed as it's this way for the other components.

**Comment by sroze** [comment]
See #25772

**Comment by unkind** [comment]
> I would like to be able to catch all kind of Security related exceptions

@paq85 I'm curious, what's the use case?

**Comment by paq85** [comment]
@unkind I have a controller where I'm authenticating user. 
That requires a couple of things. Among them I'm using `\Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager` and I would like to know in case of a failure if that was the Security component that failed or was it for example an issue with the database or some other service.

**Comment by unkind** [comment]
@paq85 you show user that it's his fault or something? Because this exception is from the Security component?

**Comment by paq85** [comment]
@unkind it's usefull for me to handle the error the way I want (log properly, take some "rescue" action) and to decide what message should I show the client/user
