### ISSUE TITLE
Can't parse YAML that the parser used to be able to parse

### ISSUE THREAD

**Issue by alexpott** [symfony/symfony#25786]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | first occurred in 3.3

Symfony 3.2 is able to parse yaml that looks like this:
```
factory.keyvalue.expirable: 
  {}
  # Default key/value expirable storage service to use.
  # @default keyvalue.database.expirable
  # default: keyvalue.database.expirable
```

Symfony 3.3+ it results in `Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 2 (near "{}")`

Using git bisect shows that this break was introduced by https://github.com/symfony/symfony/pull/25241

**Comment by xabbuh** [comment]
Which patch version of Symfony 3.3 did you use when the error occurred? Does it still exist in 3.3.15?

**Comment by alexpott** [comment]
@xabbuh it occurs on the 3.3 branch and 3.4 - so the development branches.

**Comment by alexpott** [comment]
Over in https://github.com/symfony/symfony/pull/25787 I managed to show that the following YAML also works on 3.2 but fails on 3.3 and 3.4:
```
a:
    d:
        1.1
# comment
```
