### ISSUE TITLE
Missing final keywords on Process class for v4

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#25788]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (kindof)
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

The following methods should be final since v4.0:

- `run`:
https://github.com/symfony/symfony/blob/ddb602b36b14a1ec7d31329c9a4cdc4db3aba64c/src/Symfony/Component/Process/Process.php#L195-L197
- `mustRun`:
https://github.com/symfony/symfony/blob/ddb602b36b14a1ec7d31329c9a4cdc4db3aba64c/src/Symfony/Component/Process/Process.php#L217-L219
- `restart`:
https://github.com/symfony/symfony/blob/ddb602b36b14a1ec7d31329c9a4cdc4db3aba64c/src/Symfony/Component/Process/Process.php#L336-L338

But they are not. Is this wanted or it was something missed before the release of v4?

Upgrade ref: https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.3.md#process

**Comment by chalasr** [comment]
The final annotation means that we won't ensure BC for inheritance use cases starting from the major version which comes next to the minor version where the annotation has been added on the method/class. Most of the time we won't make it truly final, but you're on your own if you keep extending it, and you get a deprecation notice until you stop.

**Comment by Soullivaneuh** [comment]
> Most of the time we won't make it truly final

So my second question is coming: why? :smiley:

**Comment by jvasseur** [comment]
@Soullivaneuh not making them truly final allow creating proxies or mocking the class if needed.

**Comment by chalasr** [comment]
Because we consider that final is a very strong statement which shouldn't be used unless using the element a is dangerous for end users, especially because symfony is a framework. People are advertised and can still do what they want.

**Comment by Soullivaneuh** [comment]
> People are advertised and can still do what they want.

That's the issue to me. If library maintainers keep the override anyway, we have no way to remove the deprecation warning.

The @jvasseur argument make more senses to me BTW.

**Comment by greg0ire** [comment]
advertised is what you'd call a *faux ami* :P

**Comment by chalasr** [comment]
> That's the issue to me. If library maintainers keep the override anyway, we have no way to remove the deprecation warning.

I don't get your point. Library maintainers should stop extending them as soon as they get the corresponding deprecation notices, a notice is just smoother than a fatal error. Even if they are not truly final on the next major, inheritance can break at any time starting from it (e.g. argument type change in method signature), hence you are on your own if you keep extending them. Not making them truly final also allows to keep extending them internally (no deprecation notice when extended from the same vendor) for BC reasons.

> The @jvasseur argument make more senses to me BTW.

Proxying based on inheritance or mocking would lead to deprecations notices as well. 
If we stop supporting inheritance for a class or method, that's because we consider that there is no valid use case for extending it. If we don't make it truly final, that's because we don't see the need for strictly forbidding, rather let people do what they want, making them aware that they on their own. That's the reasoning behind the decision.

**Comment by ostrolucky** [comment]
Symfony, thank you for being sensible and not marking (most) classes truly final. Not offering BC compatibility and discouraging inheritance of a class, but still have a way to override behaviour if userspace REALLY want to do is most sensible approach. I don't see any advantages from making it truly final.

> If library maintainers keep the override anyway, we have no way to remove the deprecation warning.

This doesn't make sense, what deprecation warning? @chalasr probably meant warning in form of `@final` annotation only. And I don't see why would you want to ever remove it. That annotation is there in place of real `final` construct.

**Comment by Soullivaneuh** [comment]
> Library maintainers should stop extending them as soon as they get the corresponding deprecation notices, a notice is just smoother than a fatal error

@chalasr That the point, they may does not. :wink: 

> If we don't make it truly final, that's because we don't see the need for strictly forbidding, rather let people do what they want, making them aware that they on their own. That's the reasoning behind the decision.

I understand, just my two cents about the possible cons.

> This doesn't make sense, what deprecation warning?

@ostrolucky The `@final` annotation makes Symfony producing a warning when you call the `parent` method: https://github.com/cpliakas/git-wrapper/issues/147

But not if we just make a inherithance without parent call: https://github.com/cpliakas/git-wrapper/pull/144 That's quiet weird BTW.

**Comment by nicolas-grekas** [comment]
> The other solution would be to override the start method instead, which is called by run.

That should haven been the correct fix :)

> warning when you call the parent method [...] but not if we just make a inherithance without parent call

Are you 100% sure of that? That's not intended - and looking at the code and at corresponding test, I'm very unsure this is correct. Can you please check again?

**Comment by ostrolucky** [comment]
> @chalasr That the point, they may does not. 😉

So? It's their problem. Symfony don't need to concern with such use cases and they can still extend it. Seems like win-win for me. Symfony doesn't gain anything by making it truly final.

**Comment by chalasr** [comment]
> Symfony doesn't gain anything by making it truly final.

Library maintainers either to me.

> But not if we just make a inherithance without parent call: cpliakas/git-wrapper#144 That's quiet weird BTW.

Just tried, not on my side,  and I don't see how could that happen as the class loader doesn't know about the body of the method.

```php
namespace App;

use Symfony\Component\Process\Process as BaseProcess;

class Process extends BaseProcess
{
    public function run(callable $callback = null, array $env = array()): int
    {
        return 1;
    }
}
```

> The "Symfony\Component\Process\Process::run()" method is considered final since version 3.3. It may change without further notice as of its next major version. You should not extend it from "App\Process".

**Comment by chalasr** [comment]
Can be closed?
