### ISSUE TITLE
in addition to route `/`, i can't got `query` with any other router

### ISSUE THREAD

**Issue by jtleon** [symfony/symfony#25782]
| Q                | A
| ---------------- | -----
| Bug report?      | uncertain
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.2

**In addition to route `/`, i can't got `query` as shown below:**

```php
/**
 * @Route("/user/login", name="app_user_login")
 */
```
![no](https://user-images.githubusercontent.com/9757844/34902574-6b897e42-f859-11e7-8741-bab538c2aebd.jpeg)

```php
/**
 * @Route("/", name="app_host_index")
 */
```
![yes](https://user-images.githubusercontent.com/9757844/34902567-32ad7376-f859-11e7-94e4-4aad1e0938ad.jpeg)
  
  
> I'm `sf` novice, and found few documents about `query`, help me, thanks!

**Comment by curry684** [comment]
What is in the controller code? Did you configure anything in security.yaml? Did you configure routes in routing.yaml?

**Comment by jtleon** [comment]
@curry684 without any configure, just `dump in controller`.

```php
   /**
     * @Route("/user/login", name="app_user_login")
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     * @return Response
     */
    public function login(\Symfony\Component\HttpFoundation\Request $request)
    {
        dump($request->query);exit;
        ...
```

**Comment by jvasseur** [comment]
This looks like an URL rewriting problem, since the front controller is `index.php` going to `/` skips url rewriting.

**Comment by dmaicher** [comment]
@jtleon can you add this into your controller for both cases and post the output here?

```php
dump($_SERVER['REQUEST_URI'], $_GET);die;
```

**Comment by jtleon** [comment]
@dmaicher have the same affect.

![_20180115113423](https://user-images.githubusercontent.com/9757844/34926064-18301252-f9e8-11e7-9394-824da9cbbb83.png)

**Comment by xabbuh** [comment]
@jtleon Can you create a small example project that allows to reproduce your issue?

**Comment by dmaicher** [comment]
@jtleon sorry I meant dumping `$_SERVER['QUERY_STRING']` :yum: 

I also suspect that this is a webserver rewriting issue as you can see that even `$_GET` is empty.

**Comment by jtleon** [comment]
@dmaicher i think so, and dump `$_SERVER['QUERY_STRING']` got `""`

**Comment by dmaicher** [comment]
ok @jtleon so this is not a symfony issue and can be closed, right?

**Comment by jtleon** [comment]
problem with my nginx configuration, use the [cnf](https://symfony.com/doc/current/setup/web_server_configuration.html#nginx), it working, and thanks @dmaicher @xabbuh @jvasseur @curry684 @carsonbot
