### ISSUE TITLE
Symfony 2.3: The “actions” extension is not enabled

### ISSUE THREAD

**Issue by antondachauer** [symfony/symfony#25793]
I am currently updating a Symfony 2.1 project to Symfony 2.3 (and later to 3.4).

I just got the error message The "actions" extension is not enabled.. Can someone tell me where I can find the fault? Google could not help me unfortunately....

thanks Anton

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
