### ISSUE TITLE
[RFC] [Form] [Validator] Support 5+ digit years

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#25790]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | all

As discussed in #25781 Symfony's Form and Validator components are pretty much hardcoded all over to support only 4 digit years. This made sense when they were written as PHP had no support whatsoever for large dates, and right now it's still flaky at best. It is however practically feasible today, likely since PHP 7, to provide fundamental support for large dates.

The so-called [Year 10000 problem](https://en.wikipedia.org/wiki/Year_10,000_problem) may seem highly hypothetical, but for example in scientific applications calculating nuclear waste effects it has practical consequences, and people may be building those in Symfony. It does also note that ISO-8601 doesn't bother with the problem and just states that years at 4 digits unless otherwise specified by data exchanging parties.

The RFC is to discuss whether we should even bother right now as Symfony, and research practical issues. What does it mean for data exchange, for example does (de)serialization support it if ISO-8601 doesn't? Do Doctrine's supported data backends support it? Etc.

**Comment by ostrolucky** [comment]
> Form and Validator components are pretty much hardcoded all over to support only 4 digit years

DateValidator has hardcoded support for dates with 4 digit year if input is string, I'll give you that. Changing that is just a matter of two keystrokes in regex pattern. But transfomers aren't hardcoded. If they don't support > 4 digits, that's done implicitly, because 'Y-m-d' in DateTime constructor doesn't preserve 5 digits. They work when you pass a timestamp.

> likely since PHP 7, to provide fundamental support for large dates.

PHP 7 has nothing to do with it. As I have shown in my [3v4l snippet](https://3v4l.org/qK9BQ), it can be done since PHP 5.3.0.

> ISO-8601 doesn't bother with the problem and just states that years at 4 digits unless otherwise specified by data exchanging parties.

I don't think that's correct interpretation.

**Comment by curry684** [comment]
> DateValidator has hardcoded support for dates with 4 digit year if input is string, I'll give you that.

There are far more places where we just do `new \DateTime($string)` or use `strtotime`. Both cause corruption or exceptions. 
```
curry@ubuntu:~/Projects/symfony/symfony$ grep -r strtotime * | wc -l
54
```
> I don't think that's correct interpretation.

[Tell W3C that](https://www.w3.org/TR/NOTE-datetime):

> PHP 7 has nothing to do with it. As I have shown in my 3v4l snippet, it can be done since PHP 5.3.0.

Indeed, just tested a bunch of conversions, and every one I tried either completely functioned in all supported versions, or broke down identically. The breaking down part is worrying though  😉  

It is actually the other way around, [things worked better before PHP 5.1](https://3v4l.org/Ztlsg). Not sure why it's a day off though, looks like TZ correction.

> A particular problem with ISO 8601 is that it allows the century to be omitted from years, which is likely to cause trouble as we approach the year 2000. This profile avoids the problem by expressing the year as four digits in all cases.

The standardized ISO-8601 profile for use in web protocols states years are always 4 digits.

Javascript uses the custom extension where `+0` is prefixed to communicate 5+ digit years:
```
console.log((new Date('20107-12-31 14:48 UTC')).toISOString());
+020107-12-31T14:48:00.000Z
```

**Comment by ostrolucky** [comment]
> There are far more places where we just do new \DateTime($string) or use strtotime

Yes, that's why I said transformers are broken implicitly. Not by intent. Only DateValidator requires mask to have 4 digits.

> The standardized ISO-8601 profile for use in web protocols states years are always 4 digits.

Where does it say it cannot have more than 4 digits? The citation you linked deals with Year 2000 problem, not year 10000.

https://en.wikipedia.org/wiki/ISO_8601#Years

> ISO 8601 prescribes, as a minimum, a four-digit year

**Comment by curry684** [comment]
> Yes, that's why I said transformers are broken implicitly. Not by intent. 

Mostly implicitly indeed. This RFC is the "should we bother" question to write a ton of breaking tests and fix the underlying code. Just adding a date in 20107 to the [test sets](https://github.com/symfony/symfony/blob/6781e53f86997634566c0f9cdef597ab1795d231/src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformerTest.php#L53-L82) breaks 10+ tests, I tried.

> Where does it say it cannot have more than 4 digits?

ISO-8601 is an open standard which allows implementers to specify deviations or additional specifications. It doesn't make any statement itself on the length of years, but specifically W3C did in this case, affecting both the Year 2000 problem positively and Year 10000 problem negatively by prescribing that years always have 4 digits. As far as W3C is concerned the world does not exist 7982 years from now, so it's not weird in itself that web based platforms like PHP do not handle 5+ digit years well.

An additional reason the Javascript implementation follows the `+` prefix is that it causes lexical sorting to still work correctly after New Year 10000, which is potentially a huge issue when naively evaluating the chronological order of events.

**Comment by Simperfit** [comment]
How we can go forward with this ?

**Comment by curry684** [comment]
> Just adding a date in 20107 to the test sets breaks 10+ tests, I tried.

That would be my starting point - add a bunch of tests using the functionality and start fixing it from there. I actually looked into picking up this issue at EUFOSSA but I think it's better left to 5.x as you'd need full 5+ digit year support from all native PHP date parsing functions.

So well, even before adding the tests I'd go check some of the issues encountered before on whether they've been reliably fixed in PHP itself by now. [Superficial testing does not stem hopeful](https://3v4l.org/DA2I0/rfc#output).

**Comment by nicolas-grekas** [comment]
Let's solve climate change before?

**Comment by stof** [comment]
I suggest we first analyse what the state of support in PHP itself is.

I don't think trying to support 5-digit years in Symfony is a wise idea if they are really broken in PHP (that would be a huge pain, as we rely on PHP dates). And if things are fixed in PHP, it might actually fix things for Symfony automatically in most places.

**Comment by derrabus** [comment]
> I suggest we first analyse what the state of support in PHP itself is.

Looks rather quirky to me. You can set a five-digit year via `setDate()` and you can render a date string with a five-digit year. On the other hand, a string with a five-digit year is not parsed properly.

https://3v4l.org/MNKUu

**Comment by curry684** [comment]
> it might actually fix things for Symfony automatically in most places.

Not quite, there's a few regular expressions enforcing 4 digit years right now. I suspect the same happens in the core as some of the (accidental) Y10K support was [actually broken in 5.1](https://3v4l.org/Ztlsg). This is also the cause of what @derrabus mentions above that `\DateTime` actually completely supports all 5 digit years *except in parsing*. If you initialize it with a big enough timestamp it'll work fine from there.

I'm all for parking this issue for another year. It's something to fix eventually but has become pretty low impact and importance since I fixed the harmful side effects in https://github.com/symfony/symfony/pull/25781.

**Comment by fabpot** [comment]
I would not bother... especially if PHP is not even ready yet.

**Comment by xabbuh** [comment]
I am closing here as I agree with @stof and @fabpot that it isn't worth it to put too much effort into something that is ultimately blocked by PHP not properly supporting these dates. Once when PHP is ready we can reconsider our decision.
