### ISSUE TITLE
Session lost all values after form->isSubmitted

### ISSUE THREAD

**Issue by vrGn** [symfony/symfony#25797]
| Symfony version  | 3.4.2

I have an issue, may be i didn't understand some thing. But any way, here is the thing:
I have a registration form where i want to put some values which i have stored in session, and all will be good if after check `if ( $form->isSubmitted() ) {` all values are `null`

**Comment by curry684** [comment]
Please provide more relevant code on how your controller is implemented.

**Comment by vrGn** [comment]
`<?php

namespace AppBundle\Controller;

use AppBundle\Entity\RegistrationForm;

use AppBundle\Form\RegistrationFormType;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;


class PageController extends Controller
{
    use FormTrait;
    use CommonTrait;

    public function indexAction(Request $request)
    {
        return $this->render('AppBundle:pages:index.html.twig');
    }

    public function registrationAction(Request $request)
    {
        $session = $this->container->get('session');
        $session->set('amount', $request->request->get('amount'));
        $session->set('term', $request->request->get('term'));
        $session->save();

        $contentRegistrationForm = new RegistrationForm();
        $registrationForm = $this->createForm(RegistrationFormType::class, $contentRegistrationForm);
        $result = $this->isSubmittedForm($registrationForm, $request, RegistrationForm::class);
          if($result){
              return $result;
          }

        return $this->render('AppBundle:pages:registration.html.twig', [
            'registrationForm' => $registrationForm->createView()
        ]);
    }
}`

`<?php
namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Common features needed in controllers.
 */
trait FormTrait
{
    /**
     * @param $form
     * @param Request $request
     * @param $entityClass
     * @return bool|JsonResponse
     */
    public function isSubmittedForm($form, Request $request, $entityClass)
    {
        $form->handleRequest($request);

        if ( $form->isSubmitted() ) {

            if( $form->isValid() ) {

                $params = $this->getParams($form, $entityClass, $request);

                $result = $this->applyParams($params, $entityClass);

                $return = $this->response($result, $entityClass, $request, $form);

            } else {
                $return = ['success' => 0, 'errors' => $this->getErrorMessages($form)];
            }
            return new JsonResponse($return);
        }
        return false;
    }
`

**Comment by vrGn** [comment]
Is there is some ideas
It's bug, feature or my straight hands?

**Comment by xabbuh** [comment]
Could you create a small fully working application that allows to reproduce your issue? Just by looking at these two classes I don't see anything that could cause this. But I could as well just miss something.

**Comment by vrGn** [comment]
git@github.com:vrGn/example.git

**Comment by vrGn** [comment]
UPDATE:
This issue also affects on Global variables
And it makes Null values only what i set on index page

**Comment by xabbuh** [comment]
@vrGn I tried to reproduce, but unfortunately your example application is not runnable (for example, the template files are missing). Please upload a fully working example application where we would just need to run `composer install` to make it executable.

**Comment by vrGn** [comment]
Problem has been solved, the issue was in my hands, and hided in this place:

`  public function registrationAction(Request $request)
    {
        $session = $this->container->get('session');
        $session->set('amount', $request->request->get('amount'));
        $session->set('term', $request->request->get('term'));
        $session->save();`

in my case simple check on NULL resolve problem:

`  public function registrationAction(Request $request)
    {
        if ( null !== $request->request->get('amount') && null !== $request->request->get('term') ) {
               $session = $this->container->get('session');
               $session->set('amount', $request->request->get('amount'));
               $session->set('term', $request->request->get('term'));
               $session->save();
        }`
