### ISSUE TITLE
Usort and PHP5.* exception "array was modified by the user comparison function"

### ISSUE THREAD

**Issue by joshlopes** [symfony/symfony#25800]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.3

I'm getting this issues every time one E_DEPRECATED notice comes from the usort. This seems to be a bug known to php https://bugs.php.net/bug.php?id=50688 and has been fixed for 7.* but it happens across all 5.*. It only happens when i have the debug enabled, it will pass if it's disabled / false.

e.g.: It seems that happens when one of my legacy app uses a private service:

Copy paste this after the kernel has been booted

```
$items = [2, 1];
usort($items, function ($a, $b) use ($container) {
    // this will throw an E_DEPRECATED message
    $container->get('date_parser');

    return $a > $b ? 1 : 0;
});
```

Error:

```
root@ubuntu-14:/var/www/$ php web/app_dev.php
PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: usort(): Array was modified by the user comparison function' in /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:207
Stack trace:
#0 /var/www/web/app_dev.php(22): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#1 {main}
  thrown in /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 207
```

**Comment by javiereguiluz** [comment]
I'm missing some information in the issue description: where have you put the failing `usort()` code? What do you disable to make the app work: the entire debug bundle? thanks

**Comment by joshlopes** [comment]
I'm not sure if this is a BC anymore or if you can do anything about it. Basically now that the container throws warnings / notices when we attempt to grab a private service, it is also exploding my app due to the fact that php5.* can't handle this notices inside the usorts.

**Comment by nicolas-grekas** [comment]
We could workaround this with this patch I guess. But is it legitimate enough?
```diff
--- a/src/Symfony/Component/Debug/ErrorHandler.php
+++ b/src/Symfony/Component/Debug/ErrorHandler.php
@@ -488,7 +488,12 @@ class ErrorHandler
                 }
             }
 
-            throw $errorAsException;
+            if (\PHP_VERSION_ID >= 70000 || false === strpos($message, 'sort(): Array was modified by the user comparison function')) {
+                throw $errorAsException;
+            }
+            if (!$log) {
+                return false;
+            }
         }
```

**Comment by stof** [comment]
I would say that the issue is the usage of `usort`on PHP 5.x (triggering any notice in the callback breaks it, by being detected as an array modification, which is non-sense). Btw, I think throwing exceptions inside the callback has the same kind of issues.

Trying to stop any notice from appearing anywhere in Symfony to avoid issues with the buggy behavior of usort on PHP 5 would force us to stop reporting deprecations AFAICT.

Hiding this `sort(): Array was modified by the user comparison function` warning entirely does not seem legitimate, as it could hide actual modifications.

**Comment by joshlopes** [comment]
I agree with everyone, i will try and take the few lines of code that is deprecated and workaround the issue. Thank you.
