### ISSUE TITLE
[Serializer] AbstractObjectNormalizer Does Not Pass Context to the Type Extractor

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#25807]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4, 4.X

When invoking `PropertyTypeExtractorInterface::getTypes`, the `AbstractObjectNormalizer` does [not passing the context](https://github.com/symfony/symfony/blob/d81f43fc368de04f862c76e17fa1c31fea5d72a8/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L286).

This would be very nice to have, I think, so context from the serializer could be used make decisions about what the types are.

**Comment by chrisguitarguy** [comment]
My own use case of this is actually taken care of by the new `ClassDiscriminatorResolverInterface`.

I still think this is a good idea to do, but maybe it would mean having two ways to do one thing.

**Comment by dunglas** [comment]
It looks sensitive to me. Because the PropertyInfo context isn't the same thing than the Serializer context, maybe the serializer context should be injected trough a `serializer` key?

**Comment by Simperfit** [comment]
@fabpot since the PR has been rejected could we close this as won't fix ?

**Comment by xabbuh** [comment]
closing for the reasons given in https://github.com/symfony/symfony/pull/26235#issuecomment-366821035
