### ISSUE TITLE
DI Container should be used to instantiate integration tests

### ISSUE THREAD

**Issue by fracz** [symfony/symfony#25814]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

IMO, testing of services from DI container deserves some love. Currently, some workarouds are being planned so testing a private service is still possible in Symfony 4.x and does not throw deprecation errors in 3.2+. See: https://github.com/symfony/symfony-docs/issues/8097 and https://github.com/symfony/symfony/issues/24543

Having some Java background, I have a suggestion that tests should be instantiated by the container just like other production services and they should expose their dependencies via setters or constructor. I mean:

```php
class PostControllerTest extends ContainerAutoconfiguredTestCaseOrWhatever
{
    /** @var MyPrivateService */
    private $serviceToTest;

    public function __construct(MyPrivateService $service) {
        $this->serviceToTest = $service;
    }

    public function testSomething() {
        //...
    }
}
```

In Java with Spring IoC Container this is achieved by custom test runner that registers appropriate listeners that inject required dependencies after test instantiation and before its launch. [Spring docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#integration-testing).

Is it possible in PHP and PHPUnit? Do you think this would mitigate some "hacky" configuration of making some services non-container-private just for sake of testing?

**Comment by iltar** [comment]
> IMO, testing of services from DI container deserves some love

Why would you test this specifically? You can already test the classes as units (unit-tests), but you can also initiate the kernel or even make fake web requests to trigger your application as a whole (functional tests), via `WebTestCase` and `KernelTestCase`.

**Comment by fracz** [comment]
Functional tests are pretty slow when compared to directly testing of services fetched from DI. Moreover, if the Controllers provide API for web clients only, the whole functional testing boils down to making a request and checking if the retured JSON/XML contains appropriate data. The whole Crawler* classes are useless in such cases.

Why would I integration test some services? Well, all cases that cannot be thoroughly unit tested and do not deserve "functional" HTTP request apply:
- a repository with complex database query: test to check if it fetches correct data for various parameters
- a console command in action: to see if the results of its launch are what they meant to be
- a bunch of services copuled together, including 3rd party ones: to verify that they work with each other as expected
- a workflow implemented on top of [Symfony Workflow](https://symfony.com/doc/current/components/workflow.html) component: to see if the conditions I have put on it do what they should in certain conditions
- any command/query that can be sent to the domain layer if your app follows the CQRS and/or [hexagonal](http://fideloper.com/hexagonal-architecture) structure: test that ensures that your domain works at all


I don't like the fact that functional tests in Symfony have been downgraded to making HTTP requests only. Symfony app is not only a "website", it often contains smart business logic that IMO needs integration testing without burden of HTTP request.

**Comment by iltar** [comment]
> I don't like the fact that functional tests in Symfony have been downgraded to making HTTP requests only. Symfony app is not only a "website", it often contains smart business logic that IMO needs integration testing without burden of HTTP request.

But that's not the case. If you want to use the container, you have to compile it. To compile it, you have to boot the kernel.

It basically boils down to this:
 - Create the kernel
 - Boot the kernel
 - Get the container from the kernel

Yes, it's slow(ish). However, if you want to make use of the DIC and test stuff, that's how you do it.

**Comment by dmaicher** [comment]
@iltar I think what @fracz is pointing out is that non-public services cannot be tested like this anymore as retrieving them from the container directly in tests is not possible

So he suggests to use DI to inject the needed services (so they don't need to be public) into the test classes if I understood correctly.

**Comment by fracz** [comment]
@dmaicher this is exactly what I meant, thank you for clarification.

**Comment by TomasVotruba** [comment]
Have you seen this package? https://github.com/lastzero/test-tools#service-container
It has many ideas already implemented

**Comment by sstok** [comment]
Somewhat related https://github.com/SymfonyTest 👍 this works great for testing DependencyInjection related classes (including extensions) without having to set-up a complete application.

You can prevent services from becoming private using a Compiler-pass that marks all services as public (this should however only be done for testing). **Maybe we can prevent services from becoming private when using the WebTestCase? Or add an config option to toggle this.**

I actually struggle with this problem myself, for now I'm using a CompilerPass that marks the services I need for testing as public.

FYI: It's not required to boot the kernel, only if you want to test with the Symfony request flow this is required; but you can also initialize the Container creation yourself!

**Comment by jakzal** [comment]
I'm also playing with some ideas here: https://github.com/jakzal/phpunit-injector#symfony

Injecting services as constructor deps would require messing too much with phpunit's internals. I did manage to inject services into test class properties though.

Example:


```php
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Zalas\Injector\PHPUnit\Symfony\TestCase\SymfonyContainer;
use Zalas\Injector\PHPUnit\TestCase\ServiceContainerTestCase;

class ServiceInjectorTest extends TestCase implements ServiceContainerTestCase
{
    use SymfonyContainer;

    /**
     * @var SerializerInterface
     * @inject
     */
    private $serializer;

    /**
     * @var LoggerInterface
     * @inject logger
     */
    private $logger;

    public function testThatServicesAreInjected()
    {
        $this->assertInstanceOf(SerializerInterface::class, $this->serializer, 'The service is injectd by its type');
        $this->assertInstanceOf(LoggerInterface::class, $this->logger, 'The service is injected by its id');
    }
}
```

**Comment by nicolas-grekas** [comment]
Please check #26499
