### ISSUE TITLE
Unable to find template in symfony3;   I don't know what is the problem please someone help me

### ISSUE THREAD

**Issue by hafssaeloiaabane** [symfony/symfony#25815]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | x.y.z

**Comment by curry684** [comment]
Please change the title to something concise and readable, and put the issue description in the content of the ticket. The error itself may make perfect sense, you will need to provide some more information on how you are requesting that template and where it is located in your project.

**Comment by iltar** [comment]
Have you tried https://symfony.com/support and ask for help? Github is meant for actual issues while the mentioned supports channels are for support.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
