### ISSUE TITLE
[Security] Deprecation warning in_memory user with autowiring

### ISSUE THREAD

**Issue by stefantalen** [symfony/symfony#25820]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.15

In my current application I'm getting the following deprecation warning in my logs:

    Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "security.user.provider.concrete.in_memory_info@website.xyz" service to "Symfony\Component\Security\Core\User\UserInterface" instead.

I'm kinda confused about what I should do to fix this warning.

My `security.yml` looks like this:

    security:
        encoders:
            My\Bundle\CompanyBundle\Entity\Contact:
                algorithm: bcrypt
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
    
        providers:
            chain_provider:
                chain:
                    providers: [in_memory, contact_provider]
            in_memory:
                memory:
                    users:
                        info@website.xys:
                            password: "some encrypted password"
                            roles: ["ROLE_SUPER_ADMIN"]
            contact_provider:
                entity:
                    class: MyCompanyBundle:Contact
                    property: emailAddress
    
            api_user_provider:
                entity:
                    class: ApiBundle:ApiUser
                    property: apiKey
        firewalls:
            # disables authentication for assets and the profiler, adapt it according to your needs
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            api:
                pattern: ^/
                stateless: true
                provider: api_user_provider
                guard:
                    authenticators:
                        - App\Component\Security\TokenAuthenticator
            main:
                anonymous: ~
                provider: chain_provider
                form_login:
                    username_parameter:  login[username]
                    password_parameter:  login[password]
                    csrf_parameter: login[_token]
                    login_path: login
                    check_path: login
                logout:
                    path:   /logout
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

Stripping the security file to only have an in_memory provider doesn't fix the warning.

**Comment by chalasr** [comment]
Can you try to set a `container.autowiring.strict_mode` parameter to `true` and see if it fixes the issue?

**Comment by stefantalen** [comment]
Added the parameter, the warnings are still there

**Comment by xabbuh** [comment]
This looks like the same as #23188.

@stefantalen Can you create a small example application that allows to reproduce your issue?

**Comment by iltar** [comment]
My best guess is, is that you typehint the `UserInterface` in an action argument and then autowiring tries to pick it up, notices this implementation is found and registered as service and then binds the interface to the user object. Do you happen to have a stack trace as well?

**Comment by chalasr** [comment]
Ok, I wasn't even aware that in_memory users were registered as services. 
I would consider this as a bug and fix it on 2.7 by injecting username-attributes couples in the InMemoryUserProvider constructor instead of [adding `createUser()` method calls](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/UserProvider/InMemoryFactory.php), dropping the `security.user.provider.in_memory.user` abstract private service. @xabbuh WDYT?

**Comment by xabbuh** [comment]
This sounds like a good idea to me.

**Comment by chalasr** [comment]
See #25837
