### ISSUE TITLE
[PropertyInfo] DoctrineExtractor - There is bug when indexBy is meta key id

### ISSUE THREAD

**Issue by insekticid** [symfony/symfony#25834]
There is bug when indexBy is meta key id introduced in doctrine pull
https://github.com/doctrine/doctrine2/pull/639
originally from issue
https://github.com/doctrine/doctrine2/issues/3094
https://github.com/doctrine/doctrine2/issues/1784

Buggy line is
https://github.com/symfony/symfony/blob/6e6ac9eaeec9e6a6cc0ab003cac3738460542b0a/src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php#L99

where `$typeOfField = $subMetadata->getTypeOfField($indexProperty);` returns `null` 
-> `$collectionKeyType = $this->getPhpType($typeOfField);` returns `null`
-> `return array(new Type(null)` throws `throw new \InvalidArgumentException(sprintf('"" is not a valid PHP type.', $builtinType));`

I discoverred this bug when I attached Api Platform ApiLoader
https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L108

**Comment by xabbuh** [comment]
fixed in #25841
