### ISSUE TITLE
bootstrap_3_layout.html.twig with inline-form has no spacing

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#25831]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.4

Hi,
I am using the bootstrap_3_layout.html.twig and configure the following form:

```
$data = [
            'startDate' => new DateTime('2017-10-01'),
            'endDate' => new DateTime('2017-12-31'),
            'reportDate' => new DateTime()];        
        
        $builder = $this->createFormBuilder($data, ['attr' => ['class' => 'form-inline']]);
        $builder
            ->add('startDate', DateType::class, [
                'label' => 'Von: ', 
                'html5' => true, 
                'widget' => 'single_text'])
            ->add('endDate', DateType::class, [
                'label' => 'Bis: ', 
                'html5' => true, 
                'widget' => 'single_text'])
            ->add('reportDate', DateType::class, [
                'label' => 'Berichtsdatum: ', 
                'html5' => true, 
                'widget' => 'single_text'])
            ->add('save', SubmitType::class, array('label' => 'Aktualisieren', 'attr' => ['class'=> 'btn-success']));
```
as result, I see the following:
![image](https://user-images.githubusercontent.com/15819451/35094377-5cad6bfa-fc45-11e7-97a1-3578e65f9805.png)
So, there is no space between the form elements. 

The created html looks fine, however, I have read [here](https://stackoverflow.com/questions/42954262/bootstrap-spacing-between-form-inline-elements) that maybe a only a space/newline is missing?

[This Fiddle](https://jsfiddle.net/u12zhaqn/) shows my created html code. If you just click on "Tidy" the newlines are created and the spaces appear.

**Comment by Nyholm** [comment]
This sure is an interesting issue. I can confirm that this behavior is reproducible. However, reading the boostap docs: http://getbootstrap.com/docs/3.3/css/#forms, I see that inline forms are expected to have like this. 

Ie, there is nothing we could do about it. You should remove "form-inline" and you will be better off. (maybe 😕 )

Here is an image from the docs: 

<img width="951" alt="screen shot 2018-03-18 at 16 01 20" src="https://user-images.githubusercontent.com/1275206/37567348-024412d6-2ac6-11e8-9e70-5a5082a937da.png">


I suggest closing this issue.

**Comment by flaushi** [comment]
Well if the code to render the html form would just output a newline character after each form element, the problem would be solved.

**Comment by Nyholm** [comment]
Im not sure that is correct. HTML does not really care about new lines.

**Comment by flaushi** [comment]
but the newline character would be interpreted like a space character. You have to understand that the browsers interpret the form fields like "one word" because there is absolutely no space between them. Try my fiddle, as soon as you give a space or newline, the form is displayed correctly.

**Comment by Nyholm** [comment]
I did try your fiddle. I did not see any difference from before and after clicking the "tidy" button.

**Comment by flaushi** [comment]
which browser are you using? on my chrome, I see a difference if i just up a newline after each form-group-div:
![image](https://user-images.githubusercontent.com/15819451/37571857-91b66748-2b02-11e8-976e-d2a84969f73f.png)
https://jsfiddle.net/u12zhaqn/2/

**Comment by Nyholm** [comment]
Im on Firefox and Safari. Same results. Same in your fiddle and same on the bootstrap docs. I cannot see that whitespace matters.

**Comment by flaushi** [comment]
Now I also tried with Safari, and I do see a difference. Please try these two fiddles:
https://jsfiddle.net/u12zhaqn/ (original code as generated by symfony)
https://jsfiddle.net/u12zhaqn/5/ (with a newline after each <div class="form-group">..</div>)

This is the original output (this time on Safari):
![image](https://user-images.githubusercontent.com/15819451/37581807-6145b7ba-2b4a-11e8-8f70-2f0c2bd9ae38.png)




and this is the result with newlines (/5/):
![image](https://user-images.githubusercontent.com/15819451/37581831-7b4d2ad0-2b4a-11e8-9db6-d921764fa5a3.png)

**Comment by xabbuh** [comment]
@flaushi Would you like to send a pull request?

**Comment by flaushi** [comment]
I think you misunderstood the problem. 
If there is no space or newline **in the produced HTML code** then the rendered result in  a browser looks bad. I tried to change the template to create a PR, but did not find the position where the change must be done.

**Comment by xabbuh** [comment]
@flaushi Can you confirm that #30922 fixes this issue?

**Comment by flaushi** [comment]
Perfect, thanks!!!

**Comment by xabbuh** [comment]
Thank you for the confirmation. 👍
