### ISSUE TITLE
Compile error on composer install

### ISSUE THREAD

**Issue by Romashka** [symfony/symfony#25845]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.3

## Steps to reproduce

```
composer create-project symfony/skeleton:3.4 sf34-issue
cd sf34-issue
composer require orm
composer install
```

>  In srcDevDebugProjectContainer.php line 352:
!!                                                                                 
!!    Compile Error: ContainerXqjmwyq\srcDevDebugProjectContainer::load(): Failed  
!!     opening required '/home/me/tmp/sf34-issue/var/cache/dev/Co  
!!    ntainerXqjmwyq/getCacheWarmerService.php' (include_path='.:/usr/share/php')  

Seems like kernel removes current container after dumping because it is marked as legacy.

**Comment by andrew-demb** [comment]
I also have the same on 3.4.3.
3.4.2 is fine.

**Comment by Romashka** [comment]
#25733 fixes this
