### ISSUE TITLE
Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK breaks dump

### ISSUE THREAD

**Issue by axel-rutz** [symfony/symfony#25842]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8 (but should be same as current)

I [stepped forward](https://www.drupal.org/project/drupal/issues/2933070) to leverage Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK to make Drupal config dumps more diff-friendly.

Unfortunately special chars, especially "\r" are not round-tripping. Did not test other cars yet.
Tested with (drupals current) 3.2.8, but commit history does not indicate a relevant change since then.

A manual test:
```
$ drush ev 'print json_encode(\Symfony\Component\Yaml\Yaml::parse(\Symfony\Component\Yaml\Yaml::dump(["a\r\nb"]))) . "\n";'
["a\r\nb"]
$ drush ev 'print json_encode(\Symfony\Component\Yaml\Yaml::parse(\Symfony\Component\Yaml\Yaml::dump(["a\r\nb"],2,4, \Symfony\Component\Yaml\Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK))) . "\n";'
["a\nb\n"]

```

**Comment by xabbuh** [comment]
see #25864
