### ISSUE TITLE
date.timezone exception  symfony 4

### ISSUE THREAD

**Issue by ouerghi** [symfony/symfony#25850]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 4.3

Runtime Notice: DateTime::createFromFormat(): We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead

in ResponseHeaderBag.php (line 336)
--
at ResponseHeaderBag->initDate()in ResponseHeaderBag.php (line 41)

```php
private function initDate()
    {
        $now = \DateTime::createFromFormat('U', time());
        $now->setTimezone(new \DateTimeZone('UTC'));
        $this->set('Date', $now->format('D, d M Y H:i:s').' GMT');
    }
}
```

**Comment by xabbuh** [comment]
Can you be a bit more precise? When exactly does this happen? How can we reproduce it?

**Comment by ouerghi** [comment]
after downloading symfony by accessing the site/public folder I find this message 
![datetime](https://user-images.githubusercontent.com/13417561/35183007-208d4438-fddf-11e7-8185-c24d7d3573b7.PNG)

**Comment by javiereguiluz** [comment]
@ouerghi maybe the timezone is not configured in PHP config file? Try adding this to your php.ini:

```ini
date.timezone = Europe/Berlin
```

**Comment by ouerghi** [comment]
I didn't know the problem but I referred to this page and wrote this script and now it works I think I need to configure php. ini in all directories. 
https://assistance.1and1.fr/hebergement-c65619/programmation-c65626/php-c65653/copier-automatiquement-le-fichier-phpini-dans-tous-les-repertoires-a703438.html

**Comment by ouerghi** [comment]
always the same problem when I try to change the root other than 
 /**
     * @Route ("/salut")
     */
    public function index ()
    {
        return new Response (' hello');
    }
it doesn't work anymore and when I do an update I find this error message 
![console](https://user-images.githubusercontent.com/13417561/35183586-040bd284-fde9-11e7-80d0-1cc635960182.PNG)

**Comment by xabbuh** [comment]
Did you make sure that you modified the `php.ini` file that is used for the CLI binary (you can check which file to edit using `php7.1-cli --ini`)?

**Comment by xabbuh** [comment]
And you can use `php7.1-cli -i` to check which config values are actually used by the CLI.

**Comment by ouerghi** [comment]
yes I have checked with phpinfo () the date value. timezone is well Europe/paris.

**Comment by xabbuh** [comment]
Can you please show the output of `php7.1-cli -i`?

**Comment by ouerghi** [comment]
with the -i option of php-cli date. timezone has no value which command allows me to change the date value. timezone with php-cli

**Comment by xabbuh** [comment]
You can define ini entries using the `-d` option when using the CLI binary like this:

```
/usr/bin/php7.1-cli -d date.timezone=Europe/Berlin ...
```

I am closing here as this is a server configuration issue and there is nothing to fix in Symfony.
