### ISSUE TITLE
[Yaml] Excess whitespace around tagged scalars in inline arrays

### ISSUE THREAD

**Issue by z38** [symfony/symfony#25856]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3/master

I'm not sure whether I understand the [YAML standard](http://yaml.org/spec/1.2/spec.html#id2790320) correctly, however it seems that entries of flow sequences can contain trailing whitespace.

At the moment the trailing whitespace is part of the tagged value:
```php
use Symfony\Component\Yaml\Yaml;

$yaml = Yaml::parse('[ !foo bar ]', Yaml::PARSE_CUSTOM_TAGS);
var_dump($yaml[0]->getValue() === 'bar'); // returns false because value is 'bar '
```

**Comment by xabbuh** [comment]
see #25863
