### ISSUE TITLE
[DI] Trim tag name before injecting tagged services

### ISSUE THREAD

**Issue by z38** [symfony/symfony#25855]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3, master

When injecting tagged services the whitespace around the tag name is significant (at least with YAML). Because unquoted, tagged values are not evaluated in the YAML parser, the whitespace will be passed to the DI component. It would be nice if the `!tagged` would behave more like `!!str` which seems to trim whitespace around unquoted strings. Alternatively, a warning message which indicates an invalid tag name would be fine too.

Example:
```yaml
services:
    app.foo:
        class: App\Foo
        arguments: [ !tagged bar ]
```
The container compiler will try to inject services with the tag "bar " (note the trailing space).

**Comment by nicolas-grekas** [comment]
This must be an issue in the Yaml parser instead.

**Comment by z38** [comment]
Thank you for the quick assessment! I opened #25856 to track the issue in the Yaml component.

**Comment by javiereguiluz** [comment]
Closing in favor of #25856 then.
