### ISSUE TITLE
[Config] canBeEnabled() not properly handling null

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#25862]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | all not yet released

#25789 seems to have broken the handling for `null` values if a (nested) array node can be enabled (this can be easily reproduced by using `null` instead of the nested `enabled` node in the changes made in #25847.

**Comment by fabpot** [comment]
PR reverted

**Comment by kejwmen** [comment]
Reproducer: https://github.com/symfony/symfony/commit/38a5d64f8224e7e09a61c0c7fb7996071823502a

**Comment by kejwmen** [comment]
And that's the line converting `NULL` to `[]`:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L772
