### ISSUE TITLE
[DI], [Config] - Environment variables can not be used with configuration nodes of concrete types

### ISSUE THREAD

**Issue by edefimov** [symfony/symfony#25868]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Suppose we have defined such configuration in `Configuration.php`:
```php
public function getConfigTreeBuilder()
{
    $tree = new TreeBuilder();
    $root = $tree->root('my_bundle');
    $root
        ->children()
            ->floatNode('float_value')->end()
        ->end();
    return $tree;
}
```

Next we want to use environment variable for this configuration, as described [here](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables):
```yaml
my_bundle:
  float_value: "%env(float:MY_VALUE)%"
```

After that we add `MY_VALUE` into `.env` file and try to run 
```bash
php bin/console cache:clear
```

The execution result will be an error:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In FloatNode.php line 34:
!!                                                                                 
!!    Invalid type for path "my_bundle.float_value"  
!!    Expected float, but got string.                                   
!!                                                                              
!!  
```
The command should be executed successfully.

[Repository](https://github.com/edefimov/symfony-reproduce/tree/6b5bcb86b0e1cfd6558f628f8ade30cca71674db) with code to reproduce this situation. The steps:
```bash
composer install
bin/console list
```

**Comment by gregurco** [comment]
To add more details: floatNode will receive for validation the placeholder of parameter created in https://github.com/symfony/dependency-injection/blob/master/ParameterBag/EnvPlaceholderParameterBag.php#L51 but not the value. Evident that  placeholder is string, but not float, int or whatever we expect.

A little bit more detailed description: https://github.com/8p/EightPointsGuzzleBundle/pull/184#issuecomment-359203277

**Comment by chalasr** [comment]
Fix in progress in https://github.com/symfony/symfony/pull/23888?

**Comment by nesl247** [comment]
This is actually a critical issue blocking replacement of parameters with environment variables for us, as well as I'm guessing many others (working to use Docker right now).

Hopefully the fix isn't stuck for too long as the last comment suggested.

**Comment by sebwebdev** [comment]
Kind of critical for us too, since some third-party bundles require types, e.g. integers for port numbers: `%env(int:PHP_REDIS_PORT)%`.

Of course we could fork the bundle and adapt, but would be great to have this working out-of-the-box.

**Comment by ro0NL** [comment]
Anyone willing to try an updated version of #23888 :) I think it's working.

**Comment by edefimov** [comment]
@ro0NL ,  It seems working! [Here](https://github.com/edefimov/symfony-reproduce/tree/a4448e053841dc1c600edca74c8b155ac84124d2) is the test.
