### ISSUE TITLE
[MonologBridge] DebugHandler buffers ad nauseum

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#25876]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Up to OOM, problematic on the CLI especially.
See #21061 and symfony/monolog-bundle#165

**Comment by ostrolucky** [comment]
I'm interested in fixing this issue. My idea is to start to write into `tmpfile()` instead of memory in non-blocking mode after certain static limit, e.g. 10000 records. `getLogs()` method would then return concatenated records in array and in file.

**Comment by iltar** [comment]
Ran into this issue as well, doesn't seem to be a clean way to disable this.

**Comment by alex-pravdin-springernature** [comment]
How to disable this feature? I need to collect all logs in unit tests which obviously runs in CLI mode.
