### ISSUE TITLE
[HttpFoundation] AcceptHeader ignores */*

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#25877]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | all

Consider this example:

```php
use Symfony\Component\HttpFoundation\AcceptHeader;

$acceptHeader = 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8';
$quality = AcceptHeader::fromString($acceptHeader)
    ->get('text/xml')
    ->getQuality();
```

I thought this code was going to return `0.8`, because `text/xml` falls into `*/*` category ... but instead I see this error message:

```
Call to a member function getQuality() on null
```

Is this a Symfony bug or is this strange behavior really expected?

**Comment by javiereguiluz** [comment]
I've tested this code using the [willdurand/Negotiation](https://github.com/willdurand/Negotiation) library and the result is different ... but it looks wrong to me too:

```php
use Negotiation\Negotiator;

$acceptHeader = 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8';
$quality = (new Negotiator())
    ->getBest($acceptHeader, array('text/xml'))
    ->getQuality()
;
// $quality = 1
```

**Comment by sroze** [comment]
I'd argue your first example is definitely a bug...

**Comment by sroze** [comment]
Actually, that's just a missing feature.
