### ISSUE TITLE
[Finder] Refactor some conditions

### ISSUE THREAD

**Issue by inhere** [symfony/symfony#25871]
https://github.com/symfony/symfony/blob/2aa54b8cbd43fdbe9c2116afd2c47d50f7fa3c34/src/Symfony/Component/Finder/Finder.php#L635-L641

Perhaps the above judgment should be moved here： LINE 562 ?

https://github.com/symfony/symfony/blob/2aa54b8cbd43fdbe9c2116afd2c47d50f7fa3c34/src/Symfony/Component/Finder/Finder.php#L559-L565

**Comment by xabbuh** [comment]
Can you explain why you think making this change would be good?

**Comment by inhere** [comment]
Thank you for your reply

when add multi dirs by `in()` ,  `Finder::$vcsPatterns` is repeated a plurality of times is added to `Finder::$exclude `.  

Is that right? :)

**Comment by xabbuh** [comment]
I am not sure I follow. :) Maybe you should better create a PR with a test that illustrates the issue you have.

**Comment by theofidry** [comment]
@inhere if you are uncomfortable with making a PR, you can try to create a small repository where you can show the issue :)

**Comment by jakzal** [comment]
I'd say it might not be particurarly harmful, but it is unnecessary.

**Comment by Destroy666x** [comment]
> but that's by design isn't it?

What's the purpose of it though? What's the benefit of having the same exclude 10 times in an array? You can't ignore it more than once anyways

**Comment by Simperfit** [comment]
@inhere, do you agree with what have been said ? Do you want to create a PR ?

**Comment by stof** [comment]
I think the issue here is the fact that `$this->exclude` is mutated to include the default exclusions, instead of using a local variable for the merged list

**Comment by inhere** [comment]
I have no objection
PR, no. . . If necessary, you can adjust it :)

**Comment by Simperfit** [comment]
@fabpot I think this can be closed @stof already refactored this part.
