### ISSUE TITLE
MultiReasonException reporting in console component

### ISSUE THREAD

**Issue by kelunik** [symfony/symfony#25883]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

Amp makes use of a `MultiReasonException` to combine multiple exception reasons, which can happen on concurrent execution. These exceptions are just reported as `Multiple errors encountered`.

```
In functions.php line 59:
                               
  Multiple errors encountered  
```

Would you accept a PR that checks for `Amp\MultiReasonException` and prints `getReasons()` additionally? The current behavior makes it a bit annoying in situations like https://github.com/humbug/box/pull/32. Exceptions need either a debugger + break points or code modifications.

**Comment by fabpot** [comment]
We won't add something that is specific to another package. I haven't had a look at this exception implementation, but it should behave like any other exception.
