### ISSUE TITLE
Clear aliases on definition removal

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#25884]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1 

Given `class Some implement SomeInterface`, i create a service definition for `Some` and an alias `SomeInterface` pointing to it.

In an extension i remove the definition because some conditions are not met. Technically the alias is dropped during compile time for being unused.

However, during build time it's a pain to check for availability with `has(SomeInterface::class)` as it still returns true at this point. (In my case i set the alias per concrete i configure).

So im stuck with removing the aliases myself.. can/should it be done for me? In general im leaning to add a util in my codebase a la  `removeDefinitionAndAliasesPointingToIt`.

**Comment by nicolas-grekas** [comment]
The alias is created by the PSR-4 loader, isn't it?
I'd say it's your duty to remove it.

**Comment by ro0NL** [comment]
Close yes ) :) i load a bunch of services with PSR and then use reflection to create the aliases from interfaces (different root namespace / me being lazy).

In the extension only `removeDefinition(Some::class)` is invoked conditionally, while other wiring checks generic availability (thus `has(SomeInterface::class)`.

i guess it's reasonable to say im on my own here. The approach works well though.. 

Actual scenario:
https://github.com/msgphp/msgphp/blob/master/src/UserBundle/Resources/config/doctrine.php#L27 + https://github.com/msgphp/msgphp/blob/master/src/UserBundle/DependencyInjection/Extension.php#L113

**Comment by ro0NL** [comment]
`removeDefinition($id, bool $clearAliases = false)` seems elegant?

**Comment by kiler129** [comment]
@ro0NL This was already discussed and rejected, see https://github.com/symfony/symfony/issues/25060.

**Comment by xabbuh** [comment]
Shouldn't we rethink this decision now that we register some alias implicitly?

**Comment by nicolas-grekas** [comment]
@xabbuh that's not the reported case, and even though, that's an impossible task. Users are responsible for their configuration.

**Comment by kiler129** [comment]
@xabbuh Yes and no really, for me @stof still has the point.
