### ISSUE TITLE
Adjusting form theme for Bootstrap 4

### ISSUE THREAD

**Issue by jiff88** [symfony/symfony#25882]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 3.3

Hello, 
it seems Bootstrap 4 changed it again; **checkboxes and radios** should not render inside label anymore. My problem is that Symfony form theme for Bootstrap 4 does it the old way; and i am struggling with changing it. It's too damn complex for me. Can someone please help with this?

I am using
**bootstrap_base_layout.html.twig**
**bootstrap_4_layout.html.twig**

from here
https://github.com/symfony/symfony/tree/master/src/Symfony/Bridge/Twig/Resources/views/Form

It generates:

```html
<div class="form-check">
  <label class="form-check-label">
    <input type="checkbox" id="xxx" name="xxx" class="form-check-input">
    Text
  </label>
</div>
```

instead of (as described here https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios)

```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" id="xxx">
  <label class="form-check-label" for="xxx">
    Text
  </label>
</div>
```

I tried to override the block to fix it for my usage, but as i understand it, i would have to override more blocks, as they are calling themselves, so it will be great relief if we can make it right here for everyone.

Thank you very much,
Josef

**Comment by jiff88** [comment]
Sorry, my bad, i see now there is a PR in progress https://github.com/symfony/symfony/pull/25715
Thanks..

**Comment by fabpot** [comment]
Closing this issue then.
