### ISSUE TITLE
Get "Script cache:clear returned with error code 1"

### ISSUE THREAD

**Issue by krypton-code** [symfony/symfony#25885]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Hello.
I install `composer require security` and get this error.
What is the problem with? Is it worth worrying about the problem or can I ignore it?
Thanks for help.

![image](https://user-images.githubusercontent.com/6662917/35219690-b070f530-ff84-11e7-9249-1495f1669c96.png)

I was remove my created file and package security and reinstall package.
And got this:

![image](https://user-images.githubusercontent.com/6662917/35220008-c7638c02-ff85-11e7-8101-5948146e7cc2.png)

**Comment by MaxouMiles-tech** [comment]
hey can you please explain with details i'm a very big beginner and i have the same probleme
