### ISSUE TITLE
Add ability to define log level for Lock component

### ISSUE THREAD

**Issue by omnilight** [symfony/symfony#25887]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Currently, when lock component can not acquire lock, it always report this as warning. It would be greate if it will be possible to specify what level to use when reporting about acquiring problem.

**Comment by omnilight** [comment]
Line is talked about:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/Lock.php#L92

**Comment by Simperfit** [comment]
@omnilight Do you want to implement this feature ? 
@jderusse Is it ok for you ?

**Comment by omnilight** [comment]
Yes, I will

23 янв. 2018 г. 16:07 пользователь "Hamza Amrouche" <
notifications@github.com> написал:
