### ISSUE TITLE
[Security] No token after authentication

### ISSUE THREAD

**Issue by Arzaor** [symfony/symfony#25880]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

## Server configuration

- Debian 9.3 Stretch
- Nginx
- PHP 7.2

## Code

```yaml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/

            anonymous: true

            provider: database_users

            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: /

            logout:
                path: security_logout
                target: /
```

```php
public function login(Request $request, AuthenticationUtils $utils): Response
{
    return $this->render('Security/login.html.twig', [
        'lastUsername'  =>  $utils->getLastUsername(),
        'error'         =>  $utils->getLastAuthenticationError()
    ]);
}
```

```twig
<form action="{{ path('security_login') }}" method="POST">
    <div class="form-group">
        <label for="username">{% trans %}Nom d'utilisateur{% endtrans %}</label>
        <input type="text" class="form-control" id="username" name="_username" value="{{ lastUsername }}">
    </div>
    <div class="form-group">
        <label for="password">{% trans %}Mot de passe{% endtrans %}</label>
        <input type="password" class="form-control" id="password" name="_password">
    </div>
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>
    <a href="">{% trans %}Mot de passe oublié ?{% endtrans %}</a><br><br>
    <button type="submit" class="btn-secondary btn">{% trans %}Connexion{% endtrans %}</button>
</form>
```

## Bug

If the user try to log in, he is redirected to the page */{_locale}/login* 
However, the page will remain entirely blank without displaying the *Profiler* 
The only solution is to refresh the user page but the user is still not logged in even if the logs by Monolog certified that the authentication is done correctly.

```
[2018-01-21 03:09:28] request.INFO: Matched route "security_login". {"route":"security_login","route_parameters":{"_locale":"fr","_controller":"App\\Controller\\SecurityController::login","_route":"security_login"},"request_uri":"http://snowtricks.jeremy-barette.fr/fr/login","method":"GET"} []

[2018-01-21 03:09:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []

[2018-01-21 03:09:29] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"818ef5","_route":"_wdt"},"request_uri":"http://snowtricks.jeremy-barette.fr/_wdt/818ef5","method":"GET"} []

[2018-01-21 03:09:35] request.INFO: Matched route "security_login". {"route":"security_login","route_parameters":{"_locale":"fr","_controller":"App\\Controller\\SecurityController::login","_route":"security_login"},"request_uri":"http://snowtricks.jeremy-barette.fr/fr/login","method":"POST"} []

[2018-01-21 03:09:35] doctrine.DEBUG: SELECT t0.id AS id_1, t0.avatar AS avatar_2, t0.username AS username_3, t0.email AS email_4, t0.password AS password_5, t0.is_active AS is_active_6, t0.token_reset AS token_reset_7 FROM users t0 WHERE t0.username = ? LIMIT 1 ["Test"] []

[2018-01-21 03:09:36] security.INFO: User has been authenticated successfully. {"username":"Test"} []
```

## Reproduce the bug

Do not hesitate to go on the following link to see what is happening : http://snowtricks.jeremy-barette.fr/en/login

- Username : Test
- Password : test

**Comment by iltar** [comment]
Looks like you're missing authorization rules, do you have access control active? If not, that would explain why you're not authenticated, as Symfony won't bother with proper authentication if you don't define minimum access levels while having `anonymous: true`.

Example:
```yaml
firewall:
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

**Comment by Arzaor** [comment]
Thank you for your help but I've same bug...

**Comment by Arzaor** [comment]
Same bug in local, I don't understand, my configuration is correct normally...

**Comment by xabbuh** [comment]
Uploading a small example application that allows to reproduce your issue would help.

**Comment by Arzaor** [comment]
Good, you can clone this repository https://github.com/Arzaor/Small-Example  !

**Comment by xabbuh** [comment]
I don't see any access control rules as mentioned by @iltar in your example application.

**Comment by Arzaor** [comment]
First rule, yes, I want, but I don't want the second rule.

**Comment by xabbuh** [comment]
I don't understand your issue then. What is the point in not configuring any restrictions for the routes that are not required for the user to log in?

**Comment by Arzaor** [comment]
I don't understand what do you mean, I don't have any problems with access control, I've a blank page after authentication with Safari and error 500 with Google Chrome and I don't understand.

**Comment by xabbuh** [comment]
From your previous description it was not clear that you get a server error. Can you please share the error log entries with us?

**Comment by chalasr** [comment]
Here is your mistake https://github.com/Arzaor/Small-Example/blob/master/src/Entity/User.php#L114

> [500]: /login - Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /Volumes/HD/Sites/tests/Small-Example/src/Entity/User.php on line 114

Patch:

```diff
- return $this->serialize(array(
+ return serialize(array(
```

**Comment by Arzaor** [comment]
Oh Thank you so much !
