### ISSUE TITLE
Cannot use autowiring on Profiler class

### ISSUE THREAD

**Issue by ahazebroucq** [symfony/symfony#25897]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Hello,
On a fresh Symfony 4.0.3 project, I'm trying to disable the profiler for a certain route as per [the docs](https://symfony.com/doc/current/profiler/matchers.html).

````php
/**
 * @Route("/no-profiler")
 */
public function noProfiler(Profiler $profiler)
{
    $profiler->disable();
    // some more code
}
````

Auto-wiring doesn't seem to be available with this class, we get the following error :

`Controller "App\Controller\DefaultController::noProfiler()" requires that you provide a value for the "$profiler" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.`

Declaring the `Profiler` as a public service doesn't work either :
````yaml
#config/services.yaml
services:
    Symfony\Component\HttpKernel\Profiler\Profiler:
        public: true
````
Gives us the following error :
`Cannot autowire service "Symfony\Component\HttpKernel\Profiler\Profiler": argument "$storage" of method "__construct()" references interface "Symfony\Component\HttpKernel\Profiler\ProfilerStorageInterface" but no such service exists. You should maybe alias this interface to the existing "profiler.storage" service. Did you create a class that implements this interface?`

Are the docs missing something or is this class supposed to be auto-wirable ?

**Comment by xabbuh** [comment]
The `profiler` service cannot be autowired as their is no service whose id matches the FQCN of the `Profiler` class. But you can define your own alias:

```yaml
services:
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'
```

**Comment by javiereguiluz** [comment]
Maybe we should make this service *autowirable*?

**Comment by weaverryan** [comment]
Unrelated to the decision about the code, I created a docs issue to fix this: symfony/symfony-docs#9122

**Comment by weaverryan** [comment]
About adding an autowireable alias for it... are there any other use-cases beyond enabling/disabling that would make you want to access the Profiler object directly? If it's really not an object that should be used commonly, then adding an alias adds noise (and we can just fix the docs for this one situation)

**Comment by fabpot** [comment]
I would not make Profiler autowireable. Docs fix is enough.

**Comment by ahazebroucq** [comment]
Thanks everyone for your answers.
