### ISSUE TITLE
[Form] empty_data in ChoiceType can be a string what must not be called

### ISSUE THREAD

**Issue by peter-gribanov** [symfony/symfony#25896]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.33

Example problem:

```php
->add('order', ChoiceType::class, [
    'expanded' => true,
    'choices' => [
        'view' => 'news.search.order.view',
        'name' => 'news.search.order.name',
        'date' => 'news.search.order.date',
    ],
    'empty_data' => 'date',
])
```
In this case, i get an error at [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L94) line:

> Warning: date() expects parameter 1 to be string, object given

**Comment by xabbuh** [comment]
You are right. But I don't see what we can do here without break BC. The solution for you would be to pass an anonymous function that just returns the string.

**Comment by xabbuh** [comment]
In other places, we deprecated the ability to pass callables as string to avoid such issues. That's something we could do here in 4.1 too so that we can remove support for it in 5.0.

**Comment by derrabus** [comment]
@xabbuh Do we still have more places like that? That sounds like an ugly pitfall in general.

**Comment by xabbuh** [comment]
I think it's very likely that we have similar code in other places.

**Comment by peter-gribanov** [comment]
Maybe, a similar problem can be [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L53), [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/FileType.php#L60) and [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L140).

**Comment by peter-gribanov** [comment]
> I'm not sure about DefaultChoiceListFactory though. Here it's either a callable or an array and callable arrays should have a different structure than the mapping arrays that we expect here.

@derrabus it may seem absurd, but it's still possible.

This code seems innocuous:

```php
$builder->add('body', ChoiceType::class, array(
    'attr' => ['title' => 'sum'],
));
```

But everything can turn out to be [very unexpected](https://3v4l.org/purtT) if the project has such class:

```php
class Title
{
    public static function sum($x, $y)
    {
        return sprintf('Sum x + y = %d', $x + $y);
    }
}
```

**Comment by derrabus** [comment]
@peter-gribanov No, because to call the class in your example, the array would be `['title', 'sum']` and not `['title' => 'sum']`.

**Comment by peter-gribanov** [comment]
@derrabus exactly. sorry
