### ISSUE TITLE
JavaScript error on all Exception pages with profiler

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25894]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0 (but probably earlier)

When the profiler is present, the following JS error shows on every exception page:

<img width="639" alt="screen shot 2018-01-22 at 9 25 54 pm" src="https://user-images.githubusercontent.com/121003/35255045-fbb53ac0-ffba-11e7-8d90-abe40185afae.png">

To repeat:

```
composer create-project symfony/skeleton exception_js_error
cd exception_js
composer require twig profiler
php -S 127.0.0.1:8000 -t public
```

Then go to any error page, like `http://localhost:8000/foo`.

It appears that the `Sfjs.createTabs()` (that executes the `createTabs()` method in `base_js.html.twig` of the WebProfilerBundle) is called twice. The first time works, but the second time, some classes (which were removed the first time) are missing.

~~It's *possible* this came from https://github.com/symfony/symfony/commit/1c595fcf48d689b49ca9f4b8790cdf5cd9275caf#diff-de00cc2fe56e59a48a4d26e7a0dccca3, but I'm very not sure~~ - maybe @ro0NL can prove/disprove my theory. **Updated** - it doesn't look like that *specific* change was the problem - as changing back has no effect. Sorry for the noise.

Cheers!

**Comment by ro0NL** [comment]
See #24281 also ;)

**Comment by weaverryan** [comment]
@ro0NL yea, that one looks suspicious... but huge :). I was hoping you could help me navigate the possible cause - I'm a bit lost in this area 😇

**Comment by ro0NL** [comment]
AFAIK it's historic, never worked. Dunno :)

General fix shouldnt be too hard.. assign/check a `data-processed` attr or so on both sides.

**Comment by weaverryan** [comment]
@ro0NL So in your opinion, it's not some bigger "clash" between the profiler and exception page JavaScript? On the surface, if you look at the code in https://github.com/symfony/symfony/commit/1c595fcf48d689b49ca9f4b8790cdf5cd9275caf, it *looks* like both the exception page and the web debug toolbar JavaScript call the *same* `Sfjs.createTabs();` function - i.e. so that it's called twice. But, my impression is probably that the `Sfjs` is actually *two* distinct variables (just with the same name) that exist independently on the page. Or am I wrong? And when we're on a page where both sets of JavaScript exist (i.e. error page + web debug toolbar), the `Sfjs` variable IS the same one instance.

**Comment by ro0NL** [comment]
> some bigger "clash" between the profiler and exception page 

It is, yes. The exception page (TwigBundle) needs to work independent from the profiler (WebProfilerBundle). If you hit the exception page _with_ profiler enabled then it conflicts.

> Sfjs is actually two distinct variables

The PR was a first cleanup to reduce the big copy/paste of javascript. But yeah both truly provide a JS api, rooted by `Sfjs`. But it's copy/paste... in fact i believe when i faced the issue the tabs from the exception we're actually rendered by the profiler JS, letting it's own JS crash :grinning: 

If we can find a way to share frontend thingy's in general.. that be nic. I.e. the toggle links for logs in profiler is not available at the exception page. Maybe drop the JS feastures on the exception? Gracefully enable if profiler is enabled?

**Comment by ro0NL** [comment]
In the long run.. it would be really cool if we can adapt a frontend framework/standard or so (basically #21050).  So we can enhance the profiler/UI way more powerful with better UX and code. I.e. rich features a la #24263 could be done less cheap :-)

**Comment by stof** [comment]
maybe the JS on the exception page should use a different variable for its JS to avoid clashing with the profiler (as they are meant to be usable separately or in parallel)

**Comment by ro0NL** [comment]
@stof see #26119 i think handling it gracefully is the better fix opposed to renaming variabels (which can only lead to more issues :))

**Comment by emschu** [comment]
I can confirm this bug with current Symfony 3.4.4 version.
Does your fix affect this version?
Thank you.

**Comment by ro0NL** [comment]
@emschu AFAIK it will be in 3.4.5
