### ISSUE TITLE
Container is rebuilt with any change to a Controller due to ServiceSubscriberInterface

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25906]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3 I believe

Hi guys!

Currently, if you make *any* change to a controller (that extends `AbstractController`), the container will rebuild. This is caused by the `ServiceSubscriberInterface` and `RegisterServiceSubscriberPass`: 

https://github.com/symfony/symfony/blob/332ad0ab9bd5a24b7f86435277346a0ad3ddd019/src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php#L66

That line ultimately means that a normal `FileResource` is added for the controller file, and any time its modified time is updated, it is updated. This may have just been a quick way of handling this: all we *really* care about is if the contents of the `getSubscribedEvents()` method changed.

**Comment by nicolas-grekas** [comment]
Good catch. IMHO we could replace this object-resource by a `ReflectionClassResource`, which should before be updated to consider `ServiceSubscriberInterface` when computing its internal hash.

**Comment by weaverryan** [comment]
@nicolas-grekas can we add the logic (e.g. `if ($this->className, ServiceSubscriberInterfce::class)`) directly to `ReflectionClassResource`? It wouldn't hurt anything, but that would put a DI component interface name in a Config component class.

**Comment by nicolas-grekas** [comment]
That's just semantic that Config know and can use. Not a binding to me. E.g. VarDumper know about a lot of third party semantics (Casters), not an issue. The alternative is to make another ReflectionClassResource in DI. Not sure it's better. What do others think?

**Comment by weaverryan** [comment]
A sub-class would be easy to make... but only if we made `ReflectionClassResource::generateSignature()` protected.
