### ISSUE TITLE
[RFC][DX] TagAware cache & Better Interface Name

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25903]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

There are 2 usability problems with the cache that I think it's important to solve:

1) Though there is a `TagAwareAdapter` class, to use cache tagging, you need to setup your own service via decoration (#20764). That's too much complex work and makes cache tagging out-of-reach for most users.

2) The interface names for autowiring are quite bad: `CacheItemPoolInterface` or `AdapterInterface`. A `TaggableCacheInterface` would be much better ... and it would extend `TagAwareAdapterInterface`. It's a bit silly... as this would exist just for better autowiring, but it *is* important. In 4.1, this would give us autowiring with `CacheInterface` (for simple PSR-16 style) or `TaggableCacheInterface`(in addition to the 2 uglier [sorry] interface names I listed first).

Question: Is there a downside to always using `TagAwareAdapter`? My guess is that there's some performance impact. If so, we could "opt-in" to wrapping `cache.app` in `TagAwareAdapter` with config. Or have a separate, wrapped service *always* exist, but only autowire when the `TaggableCacheInterface` is used.

**Comment by nicolas-grekas** [comment]
I think we should embrace standards. Providing a new name for `CacheItemPoolInterface` means encouraging people to opt-out from PSR-6 for no valid reason. Not a good ideam IMHO.
Renaming `TagAwareAdapterInterface` is possible. But that's some work, so its need a good enough reason.
I don't like encouraging PSR-16, because that's a dead end: it is not extensible. But I know you have another opinion on that.

> Is there a downside to always using TagAwareAdapter

yes: extra round-trips/queries to the backend for each fetch/has/save.

I think we can provide a `TagAwareAdapterInterface` service for autowiring quite easily. We will have to decide of much configurable we make it (tag aware adapters can use two different pools for items & tags.)

**Comment by weaverryan** [comment]
> Renaming TagAwareAdapterInterface is possible. But that's some work, so it needs a good enough reason.

You're right, of course. In the autowiring world, the interface name *does* become quite important - compare `CacheInterface $cache` with `TagAwareAdapterInterface $cache`: the second suffers f rom both (a) discoverability/guessability and (b) clarity in the code (what the heck is an "adapter"?). 

> I think we can provide a TagAwareAdapterInterface service for autowiring quite easily.

👍 :)

> We will have to decide of much configurable we make it, if at all (tag aware adapters can use two different pools for items & tags.)

Oh, so the `TagAwareAdapter` use the same pool for items and tags? I think the configurability should not be too complex: we only need to provide *one* "tag aware" service (that wraps `cache.app`) - I don't think it makes sense to make it possible to also provide taggable services for other pools the user creates. So the config might just be an extra key under `framework.cache` that would allow the user to set the cache pool service id, if they want to (otherwise, it would just use the `cache.app` pool for both items and tags?)

**Comment by nicolas-grekas** [comment]
> TagAwareAdapter use the same pool for items and tags

by default yes, but that's configurable via the constructor as you know.

> provide taggable services for other pools

I think it makes sense - at least I would only use tags on a dedicated pool myself. Config wise, this should be easy: just add a new config option on pools (eg "tag") and make it accept a boolean (for self-tag storage) or a service id (the one to use for tags.)

**Comment by nicolas-grekas** [comment]
I propose #26929 to fix this RFC.

**Comment by nicolas-grekas** [comment]
Fixed: use `Symfony\Contracts\Cache\CacheInterface` and `Symfony\Contracts\Cache\TagAwareCacheInterface`.
