### ISSUE TITLE
Response uncacheable if there is an ESI fragment

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#25902]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

**Prolog**

The `ResponseCacheStrategy::update()` method makes all responses uncacheable if one of the embedded responses is not cacheable:

https://github.com/symfony/symfony/blob/f004895e46f48fb2c369710a66f92e96f5ff4a72/src/Symfony/Component/HttpKernel/HttpCache/ResponseCacheStrategy.php#L75-L77

Note that `$this->cacheable` is never set to `true` again.

**Current behavior**

This together with https://github.com/symfony/symfony/pull/18164 prevents the main response from being cached by the client if there is an embedded response. My web page is delivered with `must-revalidate, no-cache, private` although I have specified `max-age: 1800`.

**Expected behavior**

I would have expected the main response (the web page) to be cacheable by the client (`max-age=1800, …`). Is this the intended behavior or is it a bug?

**Comment by leofeyer** [comment]
https://github.com/symfony/symfony/blob/f004895e46f48fb2c369710a66f92e96f5ff4a72/src/Symfony/Component/HttpKernel/HttpCache/ResponseCacheStrategy.php#L67-L69

From reading this I conclude that the behavior is intended. But is the premise "if there is an embedded response, the client must never cache the page" really always true?

**Comment by nicolas-grekas** [comment]
It looks totally logic to me: if a part of a page is uncacheable, then the full page is uncacheable.
Or do you mean something else?

**Comment by xabbuh** [comment]
Are the ESI fragments rendered using the inline strategy or are they actually requested by a proxy?

**Comment by leofeyer** [comment]
They are rendered via `$this->surrogate->handle()` using the Symfony reverse proxy.

>  if a part of a page is uncacheable, then the full page is uncacheable.

I agree that this is often the case, but not always.

We are using ESI to render an individual fragment depending on the user's browser. The fragment will always be the same as long as the browser does not change, so the browser could cache the final response if it were not sent with `must-revalidate, no-cache`.

**Comment by xabbuh** [comment]
@leofeyer Are you sure that the reverse proxy is actually and that Symfony does not fall back to the inline strategy? Maybe you are able to create a small example application that allows to reproduce your issue?

**Comment by leofeyer** [comment]
I am 100% sure. If I switch to the inline strategy, the cache header is `max-age=1800, public`. Also, as @nicolas-grekas confirmed, we are not talking about a bug in Symfony but rather about an edge case to the premise of the response cache strategy.

**Comment by xabbuh** [comment]
Then that's a bug to me as this completely defeats the use of ESI fragments which should allow proxy caches to only cache parts of the response.

**Comment by nicolas-grekas** [comment]
Another reason is that your response is using the session - could be the case if your have the profiler enabled - and is already fixed in branch 3.4-/4.0-dev. Can you try with it?

**Comment by leofeyer** [comment]
I am neither using the profiler nor the session. And I am aware that the response is now always private if the session has been started. 😉

**Comment by stof** [comment]
@leofeyer if the ESI fragment depend only on the browser, you should make it cacheable with a VARY header on the User-Agent. Then, the final page would also become cacheable client-side (with the same varying).

**Comment by leofeyer** [comment]
Thank you guys for your input. I know that the final response will be cacheable if all embedded responses are cacheable as well. Maybe this is the answer to my initial question whether the response cache strategy is implemented correctly already.

**Comment by nicolas-grekas** [comment]
So, everything is fine here? Let's close?

**Comment by leofeyer** [comment]
@nicolas-grekas Well, if you think that a response should never (like really never) be cached if there is at least one uncacheable embedded response, feel free to close the issue on my behalf. 😄

**Comment by nicolas-grekas** [comment]
I do :)

**Comment by nicolas-grekas** [comment]
Please review #26352
