### ISSUE TITLE
[ExpressionLanguage] Compare floats

### ISSUE THREAD

**Issue by TurningTide** [symfony/symfony#25900]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | component

There is an old problem with comparing floats in php aka "Don't Trust PHP Floating Point Numbers When Equating".
So i got this problem by using ExpressionLanguage :(
My expression looks like "7079.31 <= (7877 - 797.69)" that is expected to be true. But it's not.. Is there any workarounds in ExpressionLanguage about this issue?

**Comment by fabpot** [comment]
No, PHP is what we are using anyway. I would recommend to compare something like `707931 <= 787700 - 79769` instead.
