### ISSUE TITLE
CacheItem has methods wich are part of no interface

### ISSUE THREAD

**Issue by bruno-ds** [symfony/symfony#25912]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | at least 3.4.x

Hello, 

`\Symfony\Component\Cache\CacheItem` has methods wich are not part of its interface `\Psr\Cache\CacheItemInterface`.
Therefore it is final, so mocking those custom interfaces is harder than it should (you cannot mock final class).

It would be great if you add a custom interface extending `\Psr\Cache\CacheItemInterface` & adding the new method.

ie : 
```php
interface CacheItemInterfaceWithLackingMethods extends \Psr\Cache\CacheItemInterface {
    /**
     * Adds a tag to a cache item.
     *
     * @param string|string[] $tags A tag or array of tags
     *
     * @return static
     *
     * @throws InvalidArgumentException When $tag is not valid
     */
    public function tag($tags);
    /**
     * Returns the list of tags bound to the value coming from the pool storage if any.
     *
     * @return array
     */
     public function getPreviousTags();
    /**
     * Validates a cache key according to PSR-6.
     *
     * @param string $key The key to validate
     *
     * @return string
     *
     * @throws InvalidArgumentException When $key is not valid
     */
     public static function validateKey($key);
    /**
     * Internal logging helper.
     *
     * @internal
     */
     public static function log(LoggerInterface $logger = null, $message, $context = array())
}
```

**Comment by nicolas-grekas** [comment]
You should never need to mock a `CacheItem`, because you should never need to type-hint it.
Instead, you should pass cache pools, and type-hint either `CacheItemPoolInterface`, or `TagAwareAdapterInterface`. For testing, just pass a `ArrayAdapter`.
I don't think we want to do anything special here.

**Comment by bruno-ds** [comment]
Well then, sorry.
