### ISSUE TITLE
debug:container does not work if a parameter is binary string with non-ascii characters

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony#25916]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3, 3.4, 4.0, master

Steps to reproduce:
```bash
composer create-project symfony/skeleton test-binary-parameter 3.3
cd test-binary-parameter
composer require debug
composer require console
sed -i -e 's#secret: .*#secret: !!binary 8PDw8PDw8PDw8PDw8PDw8A==#' config/packages/framework.yaml
./bin/console debug:container
```
I end up with:
```bash
$ ./bin/console debug:container

In XmlFileLoader.php line 382:
                                                                                                                                  
  Unable to parse file "/home/bburnichon/Github/bburnichon/test-binary-parameter/var/cache/dev/srcDevDebugProjectContainer.xml".  
                                                                                                                                  

In XmlUtils.php line 62:
                                                                               
  [ERROR 522] Validation failed: no DTD found ! (in n/a - line 2, column 228)  
  [ERROR 9] Input is not proper UTF-8, indicate encoding !                     
  Bytes: 0xF0 0xF0 0xF0 0xF0 (in n/a - line 46, column 36)                     
                                                                               

debug:container [--show-private] [--show-arguments] [--tag TAG] [--tags] [--parameter PARAMETER] [--parameters] [--types] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]

```

The above secret was generated by `base64_encode(str_repeat(chr(240), 16))`

Actually, I think this is linked to #16930

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by curry684** [comment]
Offending code is at https://github.com/symfony/symfony/blob/4058f2f284c6943e459a83e6bc368d3984da1c57/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php#L305

Underlying issue is this: https://bugs.php.net/bug.php?id=74036

It should be noted that the .php dump of the container also contains the unescaped raw binary data. Unlike the XML parser that doesn't choke on all ASCII characters below 32, but it likely won't be happy with an accidental null byte in there, and LF and CR may also break it, causing the entire application to fail.

**Comment by curry684** [comment]
Likely the XML solution will be to add an extra clause:
```php
            } elseif (preg_replace('/\p{C}/u', '', $value)) {
                $element->setAttribute('type', 'binary');
                $text = $this->document->createTextNode(base64_encode(self::phpToXml((string) $value)));
                $element->appendChild($text);
            }
```
The new attribute would need to be respected in the debugging tools though.

**Comment by nicolas-grekas** [comment]
> the .php dump of the container [...] likely won't be happy with an accidental null byte in there,

PHP is binary safe AFAIK, so this shouldn't be an issue.

Would you mind sending a PR for XML? Maybe see Yaml also?

**Comment by curry684** [comment]
I was planning to pick it up this weekend, but @bburnichon already picked it up   👍
