### ISSUE TITLE
bootstrap_4_layout.html.twig need to be updated

### ISSUE THREAD

**Issue by chatlumo** [symfony/symfony#25918]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.X

Since final version of Bootstrap 4, .col-form-legend class is removed and replaced by .col-form-label : 
https://getbootstrap.com/docs/4.0/migration/#forms

So, line 130 of bootstrap_4_layout.html.twig need to be updated.

Thanks !

**Comment by fabpot** [comment]
There is already a PR about updating Bootstrap 4 support. It would great if you could have a look at it. See #25715
