### ISSUE TITLE
[RFC] deprecate bundle:controller:action notation

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#25910]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

There are currently three ways to reference controllers in symfony:
1. service:method, e.g. `_controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController:redirectAction`
2. class::method, e.g. `_controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction`
3. bundle:controller:action, e.g. `_controller: FrameworkBundle:Redirect:redirect`

Having many ways to do the same thing just confuses people. And the old bundle:controller:action notation does not fit anymore for several reasons:
1. bundle:controller:action does not work with bundle-less apps obviously
2. Symfony 4 is advocating defining controllers as services. Symfony framework bundle itself also defines controllers as services since #24409. So service:method would work as well.
3. it causes overhead for parsing different notations and workarounds like #23013
4. bundle:controller:action also doesn't work when using invokable controllers (#22338)
5. bundle:controller:action assumes a certain namespace structure and *Action suffix for controllers, see  https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php#L70-L73 This is not fit the new documented best practice to not use the *Action suffix anymore, see https://symfony.com/doc/current/routing.html which does not use it.
6. when using annotations for routes, you don't care about these things anyway

For these reasons I think we should deprecate this notation.

**Comment by xabbuh** [comment]
👍 from me

**Comment by chalasr** [comment]
👍

**Comment by fabpot** [comment]
👍

**Comment by javiereguiluz** [comment]
Nice idea! Could we also update the `service_id:method_name` syntax to use `service_id::method_name` syntax? In other words, always use two dots (`::`) to separate the service from the method?

The single dot syntax is used in places like:

1) Custom route loader based on a service:

```yaml
admin_routes:
    resource: 'App\Router\AdminRouter:loadRoutes'
    type: service
```

2) Controller as a service (traditional notation):

```yaml
hello:
    path:     /hello
    defaults: { _controller: app.hello_controller:indexAction }
```

(By the way ... this is a very annoying and unjustified constraint -> *"When using the `service_id:method_name` syntax, the method name must end with the Action suffix."*)

**Comment by xabbuh** [comment]
> (By the way ... this is a very annoying and unjustified constraint -> "When using the service_id:method_name syntax, the method name must end with the Action suffix.")

Well, you have to specify the full method name here. IMO that's much more clear than the old triple syntax where you had to omit parts because of the convention. If one doesn't like the `Action` suffix, they can just rename their controller method accordingly.

**Comment by javiereguiluz** [comment]
@xabbuh understood. It's a doc issue: you don't have to use `Action` suffix ... you just need to use the complete method name.

**Comment by xabbuh** [comment]
@javiereguiluz I think we already updated the docs to not use the `Action` suffix in the method name anymore, didn't we?

**Comment by fabpot** [comment]
We must not change the notation:

`a::b` always means that `a` is a class.
`a:b` always means that `a` is a service.

**Comment by Tobion** [comment]
@fabpot I think it would be good to only have one syntax `a::b`. If `a` is a service, use the service. Otherwise try to use `a` as a class (`new $a()`).
1. you only need to know one syntax
2. when changing controllers to services, you don't need to change the references. it still works and will use the services automatically.
3. this is consistent with the form component, where form types are either loaded from the container or with `new $name()` as fallback. see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormRegistry.php#L71

But let's first start with deprecating bundle:controller:action and then we can see if we want to go the next step as well.

**Comment by javiereguiluz** [comment]
To make things worse, in modern Symfony applications a class and a service ID are indistinguishable. Can anyone tell me if `App\Controller\SecurityController` is a service ID or a FQCN?

**Comment by Tobion** [comment]
Actually, `a::b` is already behaving like I proposed above. `a` will be used as a service or as a class. See https://github.com/symfony/symfony/blob/32cc2e06a326b1dd888c02e1cc48988a14cb9a65/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php#L93

This is also required because the annotation route loader uses `a::b` syntax even if `a` is a service. See https://github.com/symfony/symfony/blob/32cc2e06a326b1dd888c02e1cc48988a14cb9a65/src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php#L32
Another example is the documentation that uses `a::b` for services often as well. See https://symfony.com/doc/current/routing/redirect_in_config.html#redirecting-using-a-route that uses `Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction`

So the `a:b` syntax does not provide anything that `a::` does not. So we should deprecate `a:` as well IMO.

**Comment by fabpot** [comment]
👍 for deprecate `a:b` then.

**Comment by Simperfit** [comment]
👍
