### ISSUE TITLE
WebTestCase Client::getContainer null return type

### ISSUE THREAD

**Issue by soullivaneuh** [symfony/symfony#25920]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

According to this code part: https://github.com/symfony/symfony/blob/332ad0ab9bd5a24b7f86435277346a0ad3ddd019/src/Symfony/Bundle/FrameworkBundle/Client.php#L42-L50

The container may be `null` if the kernel has been shutdown.

But this simply call `$this->kernel->getContainer();` and according to the PHPDoc: https://github.com/symfony/symfony/blob/332ad0ab9bd5a24b7f86435277346a0ad3ddd019/src/Symfony/Component/HttpKernel/KernelInterface.php#L127-L132

It should never return `null`, always a `ContainerInterface`.

This also make PHPStan yelling on web tests:

```
Calling method get() on possibly null value of type Symfony\Component\DependencyInjection\ContainerInterface|null.
```

If am I right, the PHPDoc of the `Client` must be corrected.

If it may return null, I suggest to throw an exception instead. This method should not called if the kernel is not booted AFAIK.

What do you think?

**Comment by xabbuh** [comment]
Throwing an exception does make sense to me. However, someone might rely on the current behaviour and that would break their code. So changing the docblock looks like the safe solution to me.

**Comment by nicolas-grekas** [comment]
@Soullivaneuh would you mind sending a PR?

**Comment by stof** [comment]
I suggest deprecating this call when the kernel is not booted (and changing the phpdoc in the meantime)

**Comment by Soullivaneuh** [comment]
@nicolas-grekas Right now, I don't have enough time for that. Maybe later, but if anyone want to manage it, just tell! :+1:

**Comment by Soullivaneuh** [comment]
> I suggest deprecating this call when the kernel is not booted

Why not, but I'm not sure. If the kernel is not booted, container will be null. Is that really an issue? The method from `Client` is just a shortcut after all.

In any case, deprecation will be for next minor. I'll first prepare a PR to fix the PHPDoc.

**Comment by nicolas-grekas** [comment]
If the target is to deprecate calling with no container, then no need to change the PHP doc (we don't document deprecated APIs)
