### ISSUE TITLE
Inconsistency on Symfony Versions

### ISSUE THREAD

**Issue by adrianalonso** [symfony/symfony#25923]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.14

Hi, we have some problems to update to symfony 3.2.14 in our project. We force version 3.2.14 on composer.json and after update composer return the correct versión, but when we execute php bin/console --version cli indicates 3.2.13. We have some screenshoot with our problem.

We upgraded because of some security issues, and security department require to update to 3.2.14, but we are some confused.

![image](https://user-images.githubusercontent.com/3645707/35377989-7e53efb0-01b1-11e8-84e3-3ddc15c0ef2f.png)

![image](https://user-images.githubusercontent.com/3645707/35378014-89d003ec-01b1-11e8-9498-ca9a46dbdac1.png)

Thanks for everything

**Comment by fabpot** [comment]
Indeed, updating the version was unfortunately forgotten during the release. See https://github.com/symfony/symfony/blob/v3.2.14/src/Symfony/Component/HttpKernel/Kernel.php where the version is 3.2.13 instead of 3.2.14. Sorry about that.

**Comment by adrianalonso** [comment]
Thanks a lot!
