### ISSUE TITLE
PSR4 service loader causes failure for dev dependencies and --no-dev

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25929]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Originally reported here: https://github.com/doctrine/DoctrineFixturesBundle/issues/225#issuecomment-352538507

The problem: when the PSR4 service loader scans for services, if it opens a class whose parent class is missing, it fails with a fatal error. Iirc, that was by design to help show errors faster. But, it's a problem with dev dependencies, like fixtures. In that case, when you deploy with `--no-dev`, cache warmup *fails* because suddenly the parent class/interface for those classes are missing. Instead, those services should just become not available.

Actually, I *think* we could possibly still load a "dummy" `Definition` object in these cases, and add the error to it via `Definition::addError()`. Then, if the service IS referenced, we can get a better error than "service does not exist".

**Comment by nicolas-grekas** [comment]
> Iirc, that was by design to help show errors faster

any link? would help reason about this :)

**Comment by nicolas-grekas** [comment]
> Actually, I think we could possibly still load a "dummy" Definition object in these cases, and add the error to it via Definition::addError()

worth a try! do you plan to work on it or are you looking for a volunteer? (not me preferably :) )

**Comment by weaverryan** [comment]
@nicolas-grekas let me try to find one. But I believe YOU built it to fail silently, and then I told you to change it :p

**Comment by weaverryan** [comment]
> Actually, I think we could possibly still load a "dummy" Definition object in these cases, and add the error to it via Definition::addError()

> worth a try! do you plan to work on it or are you looking for a volunteer? (not me preferably :) )

Looking for a volunteer of course! But this is on my list - but someone else may be able to do it faster than I can ... and I would be willing to help guide them... :D.

**Comment by curry684** [comment]
I didn't know we actively support dummy definitions? I also had the use case a while back of a service crashing during compilation because of a missing dependency, where I would have preferred it to crash at runtime as it was optional and only relevant if you used the service actively.

**Comment by weaverryan** [comment]
@curry684 I don't think the "dummy definition" thing has been tried yet :). We *do* already have situations where we take an existing, real, `Definition` and, instead of exploding, call `addError()` on it so that it will explode during compiler pass, *only* if it still exists. But in this case, we can't create a real `Definition` (at least I don't think we can) due to the missing parent class. It *should* work... but it's new territory ;)

**Comment by derrabus** [comment]
Would #25932 do the trick?

**Comment by curry684** [comment]
@weaverryan that would have been too soon for me still as the specific use case injected the incomplete service in a locator. My idea was to replace it with an `IncompleteService` placeholder in that case to ensure it wouldn't crash until actual instantiation, with a crystal clear DX exception.

**Comment by weaverryan** [comment]
@curry684 What you're talking about is not the same issue as this. But, it IS actually needed in core: a way to attach errors to a definition, but *not* actually throw that error until/unless the service is used at runtime. Are you interested in working on this? It's actually quite important - it affects controller argument autowiring. Currently, if you have `indexAction(NonAutowireableClass $foo)`, it will fail with just `missing argument $foo`. The missing piece to seeing the real error is this deferred error functionality (and then a little bit of work also needs to be done the argument resolve system... but one step at a time ;)).

**Comment by curry684** [comment]
Yeah sorry I know it's not the core issue at hand here but I raised it anyway as the solutions are (imo) tightly related.

**Comment by inverse** [comment]
Thanks guys!

**Comment by mpdude** [comment]
Just ran across a variant of this issue that I wanted to share:

When the fixtures are defined as *public* services (for example, due to service configuration in older projects with other defaults), the DIC fails to optimize them away. As a result, you'll get the error message from the `DefinitionErrorExceptionPass`, even though symfony/symfony#25932 has been applied.

The solution is to make sure your fixtures are *private*  services.
