### ISSUE TITLE
[RFC][DI] Add !typed tag to get all services of that type

### ISSUE THREAD

**Issue by TomasVotruba** [symfony/symfony#25936]
This is follow up to:

- PR [[DI] Reference tagged services in config](https://github.com/symfony/symfony/pull/22200)
- post [New in Symfony 3.4: Simpler injection of tagged services](https://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services)

It is the same, just instead of tags, it uses directly types.

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Let's say we have 2 classes:

- `ResolverCollector` - one services
- `SingleResolverInterface` - many services

**We want to collect all services of `SingleResolverInterface` and pass them to `ResolverCollector`** (ctor or via method is not relevant).

The similar way `Commands` to `Console\Application`, but for own class and without tags.

Right now we have to create `CollectorCompilerPass` similar to this:

```php
final class CollectorCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $containerBuilder): void
    {
        $collectorDefinition = $containerBuilder->get(ResolverCollector::class);

        foreach ($containerBuilder->getDefinitions() as $name => $definition) {
            if (! is_a($definition->getClass(), SingleResolverInterface::class, true)) {
                 continue;
            }

            $collectorDefinition->addMethodCall('addSingleResolver', [new Reference($name)]);
        }
    }
}
```

### Negatives

- bundle must exists
- or must be registered in Kernel with interface
- it's not right in config, kind of hidden configuration
- requires split configuration in PHP

### Desired state

- config only
- 1 place to setup to collect services from container x  **not just current one** like `_defaults` and `instanceof` does
- not 2 places: config + PHP (Kernel, CompilerPass or Extension)

### From Bundle to Config

Since Symfony 3.4/4.0 goes more and more bundle-less and moves to config:

```yml
services:
    ResolverCollector:
        calls:        
            - ['addSingleResolvers', [!tagged single_resolver]]
```

**This would the best solution then:**

```yml
services:
    ResolverCollector:
        calls:
            - ['addSingleResolvers', [!typed SingleResolverInterface]]
```

How to achieve that? Could similar code from [[DI] Reference tagged services in config](https://github.com/symfony/symfony/pull/22200) PR work?

**Comment by derrabus** [comment]
The current way would be to enable autoconfiguration for your interface with a tag and then use `!tagged` on that tag. The advantage of that is that you can opt-out of the autoconfiguration, in case you might want to create a class that implements `SingleResolverInterface` but shouldn't be injected into `ResolverCollector`.

**Comment by stof** [comment]
note that for a local usage, you can also use `_instanceof` instead of registering your interface for autoconfiguration (in this case, the opt-out is moving the definition to a different service)

**Comment by TomasVotruba** [comment]
The goal is to:

- use config only
- collect services from all configs, not just current one

Neither of those 2 options meets this

**Comment by derrabus** [comment]
> use config only

I'm curious: What's the reason behind this requirement?

So basically, if you were able to extend the autoconfiguration from a YAML file, your requirements would be met?

**Comment by TomasVotruba** [comment]
See PR and post right in the top of description for this issue. It possible with tags, so the same should be with types.

> So basically, if you were able to extend the autoconfiguration from a YAML file, your requirements would be met?

I'm not sure what you mean. But if I could be add own Yaml tag and configure it, it would be great.

**Comment by nicolas-grekas** [comment]
I think this kind of binding is a very bad idea. Forcing a behavior based on the type prevents opting out from said behavior. Tags are exactly here to decouple behavior and types. Just use them.

**Comment by EdoBarnas** [comment]
Interface can declare type or behavior. I think, I did not need to declare interface with behavior if I do not want to use it.

**Comment by derrabus** [comment]
> I'm not sure what you mean.

I was referring to the php block in [my previous comment](https://github.com/symfony/symfony/issues/25936#issuecomment-360795869). I you were able to configure this inside a services.yml, your requirements would be met, correct?

Something like that (syntax debatable):

```YAML
services:
    SingleResolverInterface:
        autoconfiguration:
            tags: [app.single_resolver]

    ResolverCollector:
        calls:
            - ['addSingleResolvers', [!tagged app.single_resolver]]
```

**Comment by TomasVotruba** [comment]
@derrabus That would be fine.

**Comment by TomasVotruba** [comment]
> Forcing a behavior based on the type prevents opting out from said behavior. Tags are exactly here to decouple behavior and types. Just use them.

Same applies for tags. Using this feature it optional and desired.

**Comment by derrabus** [comment]
> Same applies for tags.

The sole purpose of tags is to make services discoverable for compiler passes. Tags only live in the context of the DIC compiler and there is nothing else you can do with them. Opting-out of a certain compiler pass would mean removing the tag.

But you cannot opt-out of a functionality tightly coupled to an interface.

**Comment by TomasVotruba** [comment]
@derrabus That topic is getting far away. I'd like to discussion close to what I asked if possible

**Comment by nicolas-grekas** [comment]
As explained above, I'm 👎 , behavior and interfaces must be decoupled, that's what tags are for.

**Comment by stof** [comment]
@derrabus your proposed syntax has an issue: this makes think that this new autoconfiguration applies only to the current file, while this is not possible with the current system. You should just use the existing `_instanceof` feature instead.

**Comment by derrabus** [comment]
> your proposed syntax has an issue

@stof I didn't want to propose a specific syntax, that snippet was just an example of how such a feature _could_ look like. We can try to find a better one.

> this makes think that this new autoconfiguration applies only to the current file

Okay, that was not what I've had in mind. Local autoconfiguration would be a bit pointless, I guess.

My point was that we currently cannot add autoconfigurations in config files. We have to do it programmatically at the moment. This is something we could change, imho. If someone comes up with good syntax scheme, that is. 😉

**Comment by TomasVotruba** [comment]
> @nicolas-grekas As explained above, I'm -1 , behavior and interfaces must be decoupled, that's what tags are for.

You talked about forcing, I wrote there is none, since it's optional.

> behavior and interfaces must be decoupled, that's what tags are for.

Why? Also, this is **not about behavior, but collecting services of specific type*. How is that related to tags?

**Comment by regniblod** [comment]
Any news on this issue? I'd love to use this feature and not having to create intermediary tags to get the same behavior.

**Comment by nicolas-grekas** [comment]
Still :-1: for the given reasons on my side;

**Comment by TomasVotruba** [comment]
It should not be enforced, it should be only an option.

**Comment by xabbuh** [comment]
I am 👎 on having this in the core for the reasons that have been given. But it should be possible to build this as a third-party library, shouldn't it?

**Comment by TomasVotruba** [comment]
@xabbuh Agreed. I'd post a link to package if I didn't fail trying that :(. Could you share working code?

**Comment by nicolas-grekas** [comment]
Closing as discussed. Thanks for the proposal anyway.

**Comment by TomasVotruba** [comment]
I miss working solution.

**Comment by nicolas-grekas** [comment]
Actually, you need to *not* do this, it's a terrible idea (as explained above)...
