### ISSUE TITLE
[Console] Running commands with short options is broken if value contains "h"

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony#25938]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 2.7.39

Behat tests started failing because of this issue (see [here](https://travis-ci.org/Behat/Behat/jobs/324067796#L612)).

The following command started displaying a help message, instead of running the test suite:

```
behat --no-colors -sbig_brother -fpretty --format-settings='{\"paths\": true}' features
```

The cause of the issue seems to be #24987 which allowed grouping short options. `-sbig_brother` contains the "h" letter which is treated as `-h` and the `Application` assumes it needs to display a help message:

https://github.com/symfony/symfony/blob/7b4d519885e9a8272c8d8690933e4be352c75954/src/Symfony/Component/Console/Application.php#L164-L172

**Comment by stof** [comment]
Well, only `VALUE_NONE` short options should be allowed to be grouped IMO

**Comment by jakzal** [comment]
This is tricky as currently at the point we check if `-h` was passed, the definition is not bound yet. We currently can't tell which options are defined on the command (`hasParameterOption` doesn't care about it anyway).

**Comment by stof** [comment]
Actually, #24987 is not about supporting grouping of options when calling a command (which was implemented before).
It is about supporting this grouping when detecting the usage of `-h`, which happens early in the input processing (and may not know the list of available options yet). So this might be much harder to fix without reverting the PR.
I would be in favor of reverting though if we cannot find a fix then, as the broken behavior is much worse than the fact that `-h` could not be grouped with others before.

**Comment by jakzal** [comment]
I looked into this a bit and a fix wouldn't be trivial. I also think it's better to revert.

Anyway, I think I created a duplicate of #25825. Let's move the discussion there.
