### ISSUE TITLE
Finder exclude not working as expected with absolute paths

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#25945]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.3 (surely affects previous versions as well)

Given you have the following files:

```
/path/to/project
  \-- A/
        |-- a0
        |-- a1
        \-- B
             |-- b0
             \-- b1
```

The following script:

```php
// /path/to/project/index.php
<?php declare(strict_types=1);

use Symfony\Component\Finder\Finder;

require __DIR__.'/vendor/autoload.php';

$finder = Finder::create()
    ->files()
    ->in(__DIR__)
    ->exclude(__DIR__.'/A/B')
;

// This is just to pretty print those files path
$files = array_values(
    array_map(
        function (SplFileInfo $fileInfo): string {
            $path = $fileInfo->getRealPath();

            return str_replace(__DIR__.DIRECTORY_SEPARATOR, '', $path);
        },
        iterator_to_array($finder)
    )
);

var_dump($files);

```

Will output:

```
- A/a0
- A/a1
- A/B/b0
- A/B/b1
```

Where I would have expected the files `A/B/b0` and `A/B/b1` to have been excluded.

If you however switch the exclude to relative paths, i.e. you change `->exclude(__DIR__.'/A/B')` by `->exclude('B')` this will work as expected.

**Comment by nicolas-grekas** [comment]
This is expected IMHO. That's also how the find command works e.g.

**Comment by theofidry** [comment]
Do you mind to further explain? Because as it is that doesn't make sense to me at all

**Comment by sroze** [comment]
To me, this is the expected behaviour as well. In your example, `in` the `__DIR__` folder, you exclude the given pattern. And either way, changing this behaviour would introduce a BC-break :)

**Comment by kniziol** [comment]
@theofidry Have you verified it using `->exclude('A/B')` (path starts without slash)?

Guys, take a look at this example:

```
/root/path
  \-- A/
        |-- a0
        |-- a1
        \-- B
             |-- b0
             \-- b1
             \-- C
                   \-- D
                        \-- A
                              \-- B
                                    |-- b2
                                    |-- b3
                              \-- E
                                    |-- e0
```

Using `->exclude('/A/B')` should exclude `A/B/C/D/A/B/b2` and `A/B/C/D/A/B/b3` too?

**Comment by theofidry** [comment]
@kniziol the slash was a typo I actually didn't intend to include it.

IMO your example doesn't work because an absolute path is absolute, you don't make it relative to something

**Comment by theofidry** [comment]
Actually edited to put the right path. Alright well since you consider that's the expected behaviour I guess I'll open an issue in the documentation rather

**Comment by kniziol** [comment]
@theofidry, @nicolas-grekas 
IMHO, if in `->in()` method we provide path of the root directory, then in `->exclude()` method we should provide path related to the root directory (without full path of the root directory).

Maybe we should throw an exception while using full path as @theofidry mentions in his example: `->exclude(__DIR__.'/A/B')`? Proposal of exception's message:
> Hey, you should provide relative path to the root, not full path

**Comment by theofidry** [comment]
It's true that from what I get an absolute path has nothing to do in an `exclude`, up to you if you agree an adding a guard there

**Comment by xabbuh** [comment]
see also #26396 which improved the docblock
