### ISSUE TITLE
constructor executing automatically

### ISSUE THREAD

**Issue by thapame** [symfony/symfony#25946]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Not sure whether this is a default behaviour or a bug but there is strange behaviour while using dependency injection with console command.
No matter which command I run, the constructor of my custom class is being executed.

Here is steps to reproduce it (repo url: https://github.com/thapame/issue-25946).

```
<?php

namespace App\Command;

use App\TestA;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    public function __construct(TestA $a)
    {
        parent::__construct();
    }

    protected function configure()
    {
        $this->setName('app:test');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
    }
}
```

```
<?php

namespace App;

class TestA
{
    public function __construct()
    {
        dump('this is being executed');
    }
}
```

now running any unrelated command that does not have dependency for the class e.g: `bin/console` `bin/console about` `bin/console doctrine:schema:update` or custom app command will execute the constructor of the class TestA and dump the text.

**Comment by xabbuh** [comment]
Without more information we will probably not be able to help you. Either you need to provide the stack trace of the constructor call or create a small example application that allows to reproduce your issue.

**Comment by thapame** [comment]
@xabbuh I have created a repo to reproduce this issue: `https://github.com/thapame/issue-25946`

**Comment by tomzx** [comment]
I'd expect it's normal behavior for the dependencies of a command to be instantiated. The command itself needs to be instantiated and added to the application in order to be listed in the command list as well as to be callable.

**Comment by derrabus** [comment]
The application has to instantiate all commands to determine which of them has to be executed. The name of the command (`app:test` in your case) is set during instantiation, so the application does not know it upfront.

If that is a problem (e.g. if building the dependencies is expensive), you have two options:

* Extend `ContainerAwareCommand` and pull your dependencies during execution from the container.
* Enable lazy-loading for your command, see https://symfony.com/doc/4.0/console/commands_as_services.html#lazy-loading

**Comment by xabbuh** [comment]
@tomzx and @derrabus are right here. If your command is not lazy, it will be created to allow the application to determine which command to call.

**Comment by thapame** [comment]
The issue is not about constructor of a command being executed, but it is about constructor of a dependency class for that command is being executed. I thought during instantiation a proxy class is passed to the command's dependencies until any method or property is accessed.

**Comment by derrabus** [comment]
> I thought during instantiation a proxy class is passed to the command's dependencies until any method or property is accessed.

This is not done automatically, but you can achieve this by defining the service of the class with the expensive constructor as lazy: https://symfony.com/doc/current/service_container/lazy_services.html
