### ISSUE TITLE
Wrong default value for excluded_ajax_paths option in 3.4?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#25941]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

The default value of this option is `^/(app(_[\\w]+)?\\.php/)?_wdt`. See https://github.com/symfony/symfony/blob/9bd28fc728a500ca2cea4cfdb7c3146ff2cb90f2/src/Symfony/Bundle/WebProfilerBundle/DependencyInjection/Configuration.php#L41

Shouldn't we update it now that `app.php` and `app_dev.php` no longer exist by default in Symfony apps?

**Comment by nicolas-grekas** [comment]
we should accould for index.php in 3.4 first, isn't it?

**Comment by javiereguiluz** [comment]
Yes. What do you think if we reserve this issue exclusively for newcomers?

**Comment by sroze** [comment]
> What do you think if we reserve this issue exclusively for newcomers?

You mean as an "easy pick"?

**Comment by javiereguiluz** [comment]
I was thinking about something like this: https://github.com/symfony/symfony-docs/issues/9009

**Comment by nicolas-grekas** [comment]
I know @michellesanver has a 2018's year resolution of contributing to OSS and Symfony esp.
Maybe this one could be the first? :)
