### ISSUE TITLE
No route found for "GET /"

### ISSUE THREAD

**Issue by Jenderz** [symfony/symfony#25950]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

![2018-01-28-155719_1024x600_scrot](https://user-images.githubusercontent.com/33388647/35486439-7035e4b6-0444-11e8-94ab-16663ee80ee1.png)
- sudo apt-get install -y python-software-properties
- sudo add-apt-repository -y ppa:ondrej/php
- sudo apt-get update -y
- apt-cache pkgnames | grep php7.1
- sudo apt install -y php7.1 php7.0-cli php7.1-common php7.1-mbstring php7.1-intl php7.1--xml php7.1-mysql php7.1-mcrypt
- php -v
- sudo apt-get install composer 
- sudo chown -R nombredeusuario directoriowww ----> dar privilegios en var
- cd www
- composer create-project symfony/website-skeleton my-project
- composer req server
- bin/console server:run

**Comment by xabbuh** [comment]
That's expected. In a Symfony Flex based project you start with almost nothing. No default controller, no default routes and so on. So you need to create a controller and configure a route for `/` to not get a 404 error.
