### ISSUE TITLE
[DI] Service auto-registration error message still exists

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#25959]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Just a minor thing: in 4.0 (or 3.4 with strict mode on), we removed the "service auto-registration" functionality of autowiring (i.e. where autowiring would automatically register a service for you if non existed for a class). But, the error message and some related code still exists: 

https://github.com/symfony/symfony/blob/7693469bc8634b00aff052467fbc4699ae36885f/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L363

Unless I'm mistaken, this stuff should be removed in 4.0: the error message should not mention anything about auto-registration :). But, it's *not* as simple as just removing the if statement - in practice, the final error doesn't quite make sense.

To repeat the situation:

1) Type-hint some *vendor* class (e.g. `MyLib\FooClient` that has a service in the container (e.g. `my_lib.foo_client`, but does not have an autowireable alias.

2) The error will mention auto-registration. But if you simply remove the last `elseif`, the final message will also not make sense: it should suggest adding an alias from `MyLib\FooClient` to `my_lib.foo_client`.

**Comment by nicolas-grekas** [comment]
The bug must also exist in 3.4, when strict mode is on.

**Comment by weaverryan** [comment]
You're right - updated the PR and milestone accordingly.

**Comment by Tobion** [comment]
Aren't there circumstances where autoregistration still happens? Like explained in https://github.com/symfony/symfony/pull/22295#issuecomment-292000231 and #22306
Or did that get deprecated in 3.4 again?

**Comment by weaverryan** [comment]
@Tobion It eventually got totally deprecated in 3.4 and removed in 4.0. It's kinda nice: in 4.0 there is 0 auto-registration from autowiring
