### ISSUE TITLE
Warmup part from cache:clear is not removed as it was announced

### ISSUE THREAD

**Issue by istrof** [symfony/symfony#25963]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Hello,

I noticed blog post from @fabpot regarding removal of **warmup** part in **cache:clear**:
https://symfony.com/blog/new-in-symfony-3-3-deprecated-cache-clear-with-warmup

But in 4.0.4 I see that cache:clear still contains such params.
I'm wondering, is this part is going to be removed or will it be kept as is?

**Comment by nicolas-grekas** [comment]
The deprecation has been reverted in #23825
@javiereguiluz it would be great to update the blog post if possible.

**Comment by javiereguiluz** [comment]
I'm sorry for not having updated the article. We've just updated it to include this warning message at the beginning:

> UPDATE: the deprecation described in this article was ultimately reverted. You can safely ignore this article and keep warming up the cache when clearing it.

So, closing as fixed. Thanks!
