### ISSUE TITLE
Bug in debug:container

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#25987]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I'm not quite sure but it seems to be a bug here to me. I'm upgrading a SF 3.4 application to SF 4 and got the typical `private/public` service issue when I ran my behat tests:

```
The "lexik_jwt_authentication.jwt_manager" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.  
```

Okay, my service is probably not public and when I debugged in the `RemoveUnusedDefinitionsPass` that actually seems to be true (`$definition->isPublic()` returns `false`), but when I run `bin/console --env=test debug:container lexik_jwt_authentication.jwt_manager` I get this:

```

Information for Service "lexik_jwt_authentication.jwt_manager"
==============================================================

 ---------------- ---------------------------------------------------------- 
  Option           Value                                                     
 ---------------- ---------------------------------------------------------- 
  Service ID       lexik_jwt_authentication.jwt_manager                      
  Class            Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager  
  Tags             -                                                         
  Calls            setUserIdentityField                                      
  Public           yes                                                       
  Synthetic        no                                                        
  Lazy             no                                                        
  Shared           yes                                                       
  Abstract         no                                                        
  Autowired        no                                                        
  Autoconfigured   no                                                        
 ---------------- ---------------------------------------------------------- 
```

So the debug command tells me it's public, even if it does not seem to be.

**Comment by xabbuh** [comment]
The code that triggered this error runs in the `test` environment too?

**Comment by Toflar** [comment]
Yes, I double checked that :) I just wanted to submit the issue so it's on the tracker and not forgotten about, I'll track it down in a spare minute.

**Comment by Toflar** [comment]
Oh, thank you @chalasr 👍
