### ISSUE TITLE
Range validator: add a "step" option

### ISSUE THREAD

**Issue by ymarillet** [symfony/symfony#25982]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | ≤ 4.0.4

Hi there,

We have a use case where we need to validate a float value between 1.0 and 3.5 with steps of 0.1 - unfortunately, we currently have to add another constraint (i.e. regex) to validate this behavior.

It would be nice to add a "step" option to the Range validator

**Comment by fabpot** [comment]
See the last comments in the related PR.

**Comment by ymarillet** [comment]
TLDR: use combination of Range and DivisableBy (when released :D)

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/DivisibleBy.php
