### ISSUE TITLE
GlobResource in dev env is extremely slow

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#25983]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

GlobResource checks fresh state on every request, it's ok, but it takes a lot of time, about 10-30s.
I got some custom bundles in subfolder with symfony 3.3 config.
And I actually don't know what to do. How remove this lag in initialization?
Any ideas, any help?

**Comment by nicolas-grekas** [comment]
some ideas:
- don't use glob for bundles
- move custom bundles to vendor, using eg. a composer's "path" repository, or equivalent

**Comment by wtorsi** [comment]
Great, thanks.
Composer path is what i need.
