### ISSUE TITLE
Symfony 4: No route found for "GET /" just after installation

### ISSUE THREAD

**Issue by zer0uno** [symfony/symfony#25980]
I'm starting out with Symfony 4 following this guide https://symfony.com/doc/current/setup.html, so I have executed one after the other these commands:

1. `composer create-project symfony/website-skeleton my-project`
2. `cd my-project`
3. `composer require server --dev`
4. `php bin/console server:run`

but when I browse to `http://localhost:8000` I get a `No route found for "GET /"` error.

**Comment by musthero** [comment]
I have exactly same problem. I follow the instructions from https://symfony.com/doc/current/setup.html.

**Comment by xabbuh** [comment]
see symfony/symfony#26041
