### ISSUE TITLE
PHP syntax error on css-selector

### ISSUE THREAD

**Issue by suica2k4** [symfony/symfony#25986]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 4.0.0 beta3~

PHP FatalThrowableError :
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

class:
css-selector/XPath/Extension/AttributeMatchingExtension.php

exp:
```
    public function translateExists(XPathExpr $xpath, string $attribute, ?string $value): XPathExpr
    {
        return $xpath->addCondition($attribute);
    }
```

**Comment by xabbuh** [comment]
You need PHP 7.1 or higher to be able to use Symfony 4.0. The error indicates that you tried to use the component with PHP 5.

**Comment by suica2k4** [comment]
Thanks to support.
Version up to PHP7.1 , The error was resolved!!

**Comment by Sofianio** [comment]
I installed Laravel 5.4 to be compatible with php 5.6+
It's supposed to **only require** dependencies that are **compatible** with php 5.6+
I shouldn't have to lock it manually using `composer require "symfony/css-selector:3.4.4"`
just sayin ..

**Comment by xabbuh** [comment]
@Sofianio Either you need to run Composer with PHP 5.6 then or configure the target PHP version using Composer's [`config.platform`](https://getcomposer.org/doc/06-config.md#platform) config option.

**Comment by Sofianio** [comment]
Why would composer install a dependency that is not compatible with current php version?

I installed Laravel 5.4 on a server running php7.0 but composer installed "symfony/css-selector" v4 which is not compatible with php7.0 ... isn't that strange?

I believe the version of  "symfony/css-selector" on Laravel 5.4 should be locked to 3.4.4 by default

**Comment by Sofianio** [comment]
Ok my bad, I have php7.1.10 in cli and 7.0.10 in apache :/

But i still believe Laravel 5.4 should have locked dependencies to be compatible with php5.6 no matter what php version composer was run in, 
although i know it's a rare case where cli has higher php version than apache.

Anyway thanks for the help, and sorry for wasting your time :)

**Comment by stof** [comment]
@Sofianio but then, you would have to do the same for all transitive dependencies. And this would hurt people running on a newer PHP version (which might be using a newer version of the lib), and creates lots of work for maintainers.
Composer has already all the logic necessary to choose dependencies compatible with a given PHP version. By default, it is the PHP CLI version, but it even allows you to configure a different PHP target version (so if you run PHP 7.0 in Apache, you can ask composer to resolve dependencies for PHP 7.0 rather than 7.1).

**Comment by Sofianio** [comment]
@stof  yes that's what i did eventually, i configured composer to target php7.0

**Comment by Tochine** [comment]
Please how do I resolve this error?

Problem 1
    - symfony/css-selector v4.0.4 requires php ^7.1.3 -> your PHP version (7.1.2) does not satisfy that requirement.
    - symfony/css-selector v4.0.4 requires php ^7.1.3 -> your PHP version (7.1.2) does not satisfy that requirement.
    - symfony/css-selector v4.0.4 requires php ^7.1.3 -> your PHP version (7.1.2) does not satisfy that requirement.
    - Installation request for symfony/css-selector (locked at v4.0.4) -> satisfiable by symfony/css-selector[v4.0.4].

**Comment by nicolas-grekas** [comment]
Hello, you need to upgrade to PHP 7.1.3 or higher, your version (7.1.2) is outdated.

**Comment by Tochine** [comment]
how do I upgrade?

**Comment by xabbuh** [comment]
That depends on how you installed PHP and which system you are using. I suggest to look for information in your system's documentation and/or seek for help in one of the [support channels](https://symfony.com/support). Thank you for understanding.
