### ISSUE TITLE
Dump() function returns and outputs at the same time

### ISSUE THREAD

**Issue by michielvandenboogaart** [symfony/symfony#25991]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

The latest changes in the dump() function is broken. It now echo's ánd returns. It should be one of those, not both.

**Comment by javiereguiluz** [comment]
@michielvandenboogaart it's not "broken" ... but it has changed comparing it with previous Symfony versions. In the original PR we explained the reasons behind this change: https://github.com/symfony/symfony/pull/24280

Most people seem to like this new feature, so it will probably not be reverted. In any case, could you please explain a bit more why this change broke your application? Thanks!

**Comment by michielvandenboogaart** [comment]
Like I said, the functionality has changed. A function should never do two different things. 

When I use
dump('test');

I get test.

When I use
echo dump('test');
I get test test.

That doesn't make sense. It's fine if people want a return value, but don't also echo it at the same time.

**Comment by javiereguiluz** [comment]
I think I understand the problem now. I'm not saying that you are doing it wrong ... but there's no need to add `echo` to the `dump()` function. As we explain in the docs (see https://symfony.com/doc/current/components/var_dumper.html#the-dump-function) calling the `dump()` function is enough to display contents. That would solve your issue with the repeated information.

**Comment by michielvandenboogaart** [comment]
Yeah, but here the thing. 

Templating engines do not work like that. Second, the function no longer does what is says it does. It no longer just dumps, it also returns stuff. I have to use workarounds for something that shouldn't not require workarounds.

This 'extension' of the function has made it utterly useless for me and I already replaced it with the original in my development environment. I do not expect symfony to revert this change since it's already clear that people don't care about proper code for this function since it's only used for debugging.

**Comment by javiereguiluz** [comment]
@michielvandenboogaart I'm sorry this change created some troubles for you. Luckily you could solve it recreating the original `dump()` function yourself. That's why we're closing this as "won't fix" for now ... but we'll keep an eye on this to see if we receive more complaints like this. Thanks!
