### ISSUE TITLE
[Serializer][DI] Auto-tagging breaks behavior of custom Normalizers/Encoders

### ISSUE THREAD

**Issue by cjost1988** [symfony/symfony#25990]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.4.*

We figured out that if you're running multiple `Serializer` with custom `Normalizers` implementing `NormalizerInterface` all your custom `Normalizers` are injected into symfony's default serializer since all normalizers that implements the `NormalizerInterface` will be tagged with `serializer.normalizer`. 
This is the same for the `Encoders`.

Since a `Serializer` is injecting itself into all referenced `Normalizers` and `Encoders` at construction time the last (or maybe highest prio) `Serializer` in the container will be referenced in all `Normalizers` and `Encoders`.

This makes it impossible to create custom `Normalizer`/`Encoders` and configure your own `Serializer` beside the frameworks one if you want to use the interfaces which are provided by symfony. 

Short term solution was to not use the `NormalizerInterface` and `EncoderInterface` and we lose the opportunity to use the very useful `ObjectNormalizer` class and others.

A suggestion would be to add a new interface which will be used for automatic tagging in the CompilerPass. This can be the default to be easy to use but also provides the ability to create custom `Serializer`/`Normalizer`/`Encoder` instances.

Thanks,
Christian

**Comment by xabbuh** [comment]
IMO that's the expected behaviour. The solution is to turn off autoconfiguration for those services where you do not want to make use of that feature.

**Comment by stof** [comment]
And this is precisely the reason why autoconfiguration is opt-in for services.

**Comment by cjost1988** [comment]
Thank you for your quick response.
So the only thing I've to do is to set `autoconfigure` to `false` for my services (e.g. `Normalizer`) and it will work as expected?

Or do I've to disable autoconfigure completely for symfony's `Serializer`?

**Comment by cjost1988** [comment]
Ok, I've tested it with just setting it for my `Normalizer` and it works. Thank you for the hint :D

Then this issue can be closed.

**Comment by xabbuh** [comment]
👍 By the way, you can close your own issues yourself. :)

**Comment by stof** [comment]
@cjost1988 yeah, the autoconfiguration is responsible for adding the appropriate tag on your normalizer, not for configuring the serializer service (another part is responsible for that, based on tagged services, not caring about who added the tag). So disabling it is done on the normalizer.

**Comment by cjost1988** [comment]
@xabbuh didn't know that :D Thanks, I'll do it on my own in the future.
