### ISSUE TITLE
Add Symfony 4 + PHP-PM in TechEmpower's benchmark

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#25994]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

PHP-PM advertises high performing apps. Symfony 4 is our fastest version.
Let's demonstrate the combination of both in TechEmpower's benchmark.

Here is the PR adding Symfony 4 to it: https://github.com/TechEmpower/FrameworkBenchmarks/pull/3000

Anyone willing to work on this?
ping @raziel057 @markj @andig @florianbelhomme

**Comment by javiereguiluz** [comment]
We also updated recently the server config used for the Symfony benchmark to match other frameworks server configs (https://github.com/TechEmpower/FrameworkBenchmarks/pull/3162). 

Please be very careful when changing the server config and always validate that it's faster than the existing config. We don't want to lose the great Symfony 4 performance because of a wrong server config. Thanks!

**Comment by raziel057** [comment]
@nicolas-grekas Hi just added a ticket to check if it's best to add PHP-PM in the toolset so that a project can just depend to it. Anyway I will try to add it as soon as I have free time.

**Comment by andig** [comment]
@nicolas-grekas I'm playing with the implementation but am stuck at ppm not being able to open a unix socket. Adding daemon mode in the meantime to simplify running in background (https://github.com/php-pm/php-pm/pull/351).

Will take some more time before I get there...

**Comment by nicolas-grekas** [comment]
They're calling us on the topic: https://github.com/the-benchmarker/web-frameworks/pull/1570
Anyone would like to have a look?

**Comment by andig** [comment]
Unfortunately, and although people have been using php-pm inproduction for quite some time, we're currently having issues with this, e.g. https://github.com/php-pm/php-pm/issues/456.

**Comment by nicolas-grekas** [comment]
Symfony is the fastest framework around thanks to your hard work, special mention to @jderusse!
https://www.techempower.com/benchmarks/#section=test&runid=ca07ce5b-053c-4d75-b204-53eb5a6c5aeb&hw=ph&test=update&c=6&d=d&o=8
