### ISSUE TITLE
Need configure for blacklisting annotations

### ISSUE THREAD

**Issue by dvc** [symfony/symfony#26005]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 4.0.4

Annotations is fragile functionality some times. See https://github.com/symfony/symfony/issues/17000#issuecomment-361537177

My workaround works because AnnotationReader::addGlobalIgnoredName is static method.

But i's dirty hack, imho.

Better to have configutation ability for blacklisting annotations:

1) by path (ignore vendors by default?)
2) by namespace
3) by annotation name

**Comment by xabbuh** [comment]
Wouldn't this better fit in the `doctrine/annotations` package directly?

**Comment by Simperfit** [comment]
@dvc Tell me if i'm wrong but I think this one can be closed since you got an answer in the doctrine/annotations repository directly.

**Comment by dvc** [comment]
I don't know exactly. Configuration of reader servise required on compile phase. I'm not shure about details of this process.

I'll try to create same issue in doctrine/annotations tracker on next week

Thank you

**Comment by jakzal** [comment]
@dvc is there anything to do in Symfony regarding this issue?

**Comment by dvc** [comment]
No. Close. Thanks!
