### ISSUE TITLE
Migrate database pgsql

### ISSUE THREAD

**Issue by Jenderz** [symfony/symfony#26001]
| Q                | A
| ---------------- | -----
| Bug report?      | Yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

![2018-01-31-220254_1024x600_scrot](https://user-images.githubusercontent.com/33388647/35657520-3e183614-06d3-11e8-9a3b-ba688f510d27.png)

**Comment by mvrhov** [comment]
Hi @Jenderz this is not support forum this is only for bug reports and/or feature requests.
For support please use one of the ways described [on Symfony website](https://symfony.com/support)
