### ISSUE TITLE
Minor BC break in TranslationUpdateCommand

### ISSUE THREAD

**Issue by pevdh** [symfony/symfony#26007]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.4

According to the [documentation](http://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically) and the `translation:update` description, `php bin/console translation:update --force --dump-messages en` is supposed to store translations in `app/Resources` by default.

However, in #25065 the defaultTransPath constructor argument was set to `%kernel.project_dir%/translations` instead of `%kernel.project_dir%/app/Resources`:

https://github.com/symfony/symfony/blob/8dadff2ece98d0b292291113eb6fbbfe2c4baa04/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L54 

https://github.com/symfony/symfony/blob/8dadff2ece98d0b292291113eb6fbbfe2c4baa04/src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml#L86-L94

https://github.com/symfony/symfony/blob/8dadff2ece98d0b292291113eb6fbbfe2c4baa04/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1141

https://github.com/symfony/symfony/blob/8dadff2ece98d0b292291113eb6fbbfe2c4baa04/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L688-L691

The former is indeed correct for sf4 projects, but directly contradicts the description of the command (and probably some documentation) in 3.4:

```
Usage:
  translation:update [options] [--] <locale> [<bundle>]

Arguments:
  locale                               The locale
  bundle                               The bundle name or directory where to load the messages, defaults to >>> app/Resources <<<  folder
```

`php bin/console translation:update --force --dump-messages en app` does store the translations in `app/Resources/translations`.

I really don't mind typing the 3 extra letters, but I thought I'd mention it either way :)
Also, not really sure if I missed anything here.

**Comment by nicolas-grekas** [comment]
@yceruto maybe something you'd like to look at?

**Comment by yceruto** [comment]
Will take a look soon, thanks!

**Comment by yceruto** [comment]
I can't reproduce the BC break. I just migrated one app from `3.3` to `3.4` and still this command work as expected (updating all translations in `app/Resources/translations` directory by default) **unless you've created the `translations/` directory at the root manually**, meaning as of there you're starting to migrate to `4.0` structure, then it's your new default translations directory. IMHO this behavior is appropriate to migrate  easily.

My suggestion, remove the `translations/` dir at the root if you aren't ready to migrate to `4.0` structure, thus `app/Resources/translations` will remain the default directory.

**Comment by yceruto** [comment]
Btw, there isn't option to work with `translations/` dir at the root if we change the current behavior to make `<kernel_root>/Resources/translations>` be always the default one, because `<bundle>` argument doesn't accept absolute paths but relative paths to `/Resources/*` dir:
https://github.com/symfony/symfony/blob/b9a2e21326ad93aab1350e566afced701942ac6d/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L189-L191

**Comment by Simperfit** [comment]
@yceruto Do you think there is something to do here or can we say that's the expected behaviour ?

**Comment by yceruto** [comment]
I think this can be closed, there is no bug IMO.
