### ISSUE TITLE
PHPUnit 7 compatibility

### ISSUE THREAD

**Issue by carusogabriel** [symfony/symfony#26017]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Symfony version  | ?

With the release of PHPUnit 7, the `PHPUnit\Framework\BaseTestListener` has been removed. The correct fix is implement `PHPUnit\Framework\TestListener` interface and use `PHPUnit\Framework\TestListenerDefaultImplementation` trait. What version should we do that?

Ref: https://phpunit.de/announcements/phpunit-7.html

**Comment by nicolas-grekas** [comment]
In 3.4 I'd say.

**Comment by shieldo** [comment]
Have made a PR for this: https://github.com/symfony/symfony/pull/26024

Would love comments.

**Comment by stof** [comment]
is the trait already available in PHPUnit 6 or no ?

**Comment by shieldo** [comment]
@stof It was introduced for the 6.4 release, whereupon the old base class was deprecated for removal in 7.0.
