### ISSUE TITLE
[DX] Display the actual error class instead of FatalThrowableError

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#26025]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 4.1

If an error is thrown, Symfony wraps it into a `FatalThrowableError`. The consequence is that the actual error class is lost.

<img width="382" alt="bildschirmfoto 2018-02-02 um 20 09 33" src="https://user-images.githubusercontent.com/1506493/35750878-c5c24788-0856-11e8-85be-c3e3860006ee.png">

What I'd like to see instead is this.

<img width="402" alt="bildschirmfoto 2018-02-02 um 20 08 42" src="https://user-images.githubusercontent.com/1506493/35750894-d30f59e4-0856-11e8-96a3-bb71a6f5d7a6.png">

I think, we can fix this issue without switching the whole error handling to `Throwable` (see #22128 for that).

**Comment by nicolas-grekas** [comment]
good idea (yes we can, nothing is impossible :) )
