### ISSUE TITLE
Ability to search a route on debug:router

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26033]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

As the `debug:container` does, it would be great to have the `debug:router` searching routes matching the name and the url when the given route does not exist.

**Comment by Simperfit** [comment]
I'm going to do it.
