### ISSUE TITLE
Show the class of the command on help

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26034]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

When running `./bin/console help <command>`, show the class name corresponding to the command.

Can be useful for example to easily find the class of a vendor when you want to edit then for future contribution.

**Comment by jvasseur** [comment]
The idea is interesting but I don't think it should go into the `help` command. Command help is supposed to be about how to use the command. Maybe this could be added in some kind of `debug:command` command ?

**Comment by Soullivaneuh** [comment]
@jvasseur I first though about a `debug:command`, but it will be very repetitive IMHO.

**Comment by Simperfit** [comment]
If we add a `debug:command` it will be repetitive with the help one, I agree.

`bin/console help <command> --classname` ?

**Comment by Simperfit** [comment]
I'm doing it. without the --classname; we'll see in the PR if it's ok or if we need to modify
