### ISSUE TITLE
PHPUnit Bridge throwing exception when using PHPUnit 7

### ISSUE THREAD

**Issue by iSDP** [symfony/symfony#26047]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I'm using PHPUnit 7, and I'm getting the following exception:
```
Fatal error: Class 'PHPUnit\Framework\BaseTestListener' not found in C:\(...)\vendor\symfony\phpunit-bridge\SymfonyTestsListener.php on line 31
```

Which is expected because it's in the changelog:

> The PHPUnit\Framework\BaseTestListener class has been removed, it was deprecated since PHPUnit 6.4. Please use the PHPUnit\Framework\TestListenerDefaultImplementation instead.

**Comment by Tobion** [comment]
#26017 please use the search.
