### ISSUE TITLE
Redirect _escaped_fragment_ urls

### ISSUE THREAD

**Issue by ddimitrioglo** [symfony/symfony#26044]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 3.4.4

I have SPA, and have `?_escaped_fragment_` hook to make the content visible for crawlers.
Now I want to throw away this approach, and redirect (301) all the `_escaped_fragment_` pages to simple symfony3.4 application 

I have following routings: 
1. `@CFG\Route("/", defaults={"page":1}, name="xxx1")`
2. ` @CFG\Route("/page/{page}", requirements={"page":"\d+"}, name="xxx2")`
3. *What I have to do here to catch `_escaped_fragment_` and redirect them properly?*
4. `@CFG\Route("/about", name="xxx4")`
5. etc...

I've tried to do it like this: `@CFG\Route("/{_escaped_fragment_}", name="xxx5")`  but it redirects to homepage anyway.

Please help me here. Thanks.

P.S. old urls have the format: `https://domain/?_escaped_fragment_=/article/my-awesome-post`

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by ddimitrioglo** [comment]
Slack community have not gave an answer ;(
