### ISSUE TITLE
how to solve Assert\NotBlank not found in uploading images in symfony 4.0?

### ISSUE THREAD

**Issue by kenntinio** [symfony/symfony#26048]
Please refer to my stackoverflow question:
https://stackoverflow.com/questions/48597409/how-to-solve-assert-notblank-not-found-in-uploading-images-in-symfony-4-0

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
