### ISSUE TITLE
Improve autowiring services error message

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#26055]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

Currently it says something like:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "foo.bar" service to "Foo\Bar" instead.

The problem here is that in the large project there may be hundreds of services using `Foo\Bar`, and only one of them using autoregister. So, it's hard to find which service is causing the issue.

Including the ID of the service where `Foo\Bar` is injected using autoregistration would help in this case.

In `AutowirePass::getAutowiredReference()` there is a `$reference` parameter, so needed information is at hand. If agree, I can PR this.

**Comment by stof** [comment]
But the resolution of this error does not involve changing the service *consuming* `Foo\Bar`. It requires changing the `Foo\Bar` service being injected by autowiring. And there is only one of them.
So I don't think this request makes sense.

**Comment by umpirsky** [comment]
@stof Only if you want to resolve it by renaming or aliasing the service. But yes, my case was specific, I wanted to remove `autowire: true`, I guess that's not so common.
