### ISSUE TITLE
Huge memory increase in 3.4.4

### ISSUE THREAD

**Issue by pengend** [symfony/symfony#26052]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

When I update my application to 3.4.4, I got a huge memory issue in my behat tests. 

[Blackfire profiler with 3.4.3](https://blackfire.io/profiles/e5452307-807e-47ac-b76c-185ddbf43845/graph)
[Blackfire profiler with 3.4.4](https://blackfire.io/profiles/73eab24f-69e1-4e70-a5a5-5b09594a114e/graph)

All functions has their memory increased like 5x to 10x.

**Comment by al37350** [comment]
Please refer to #25965.

**Comment by chalasr** [comment]
Closing as duplicate
