### ISSUE TITLE
Invalid HiddenType value when mapped is false

### ISSUE THREAD

**Issue by Dbokobza** [symfony/symfony#26053]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

When a form is linked to an entity and you have a HiddenType non mapped field with a default value = 1 (data is set to 1) for instance
If the form is submit with value = 2, then the form displays value = 2 instead of 1

**Comment by yceruto** [comment]
Hi @Dbokobza, always the submitted data takes precedence over default data, it's the normal behavior. 

Do you want to disable this behavior? set `disabled` option to `true` on this form field.

**Comment by xabbuh** [comment]
I am closing here as this is the expected behaviour (see @yceruto's explanation).
