### ISSUE TITLE
SymfonyTestsListener sending headers too soon in functional tests

### ISSUE THREAD

**Issue by alulord** [symfony/symfony#26061]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

## Versions of my packages

"codeception/codeception": "^2.3",
"symfony/phpunit-bridge": "~2.7",
"phpunit/phpunit": "4.8.*@stable",
"symfony/symfony": "2.8.*",
PHP 7.1.13 
OS openSUSE Leap 42.3

## Location of problem

https://github.com/symfony/symfony/blob/c337bf68105eeed88db5306a10bb1b00d433d225/src/Symfony/Bridge/PhpUnit/SymfonyTestsListener.php#L82

## Description

I have a problem running functional tests with Codeception, using Symfony module. I have a test:

```php
    public function goodGetCSRFTokenTest(FunctionalTester $I, Example $example)
    {
        $I->wantToTest('if I get CSRF token');
        $I->amOnPage('/api/v1/csrf/'.$example[0]);
        Debug::debug($I->grabResponse());
        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();
        $I->seeResponseContains($example[1]);
        $I->seeResponseContains('value');
    }
```

However, when I try to go to that page, I get  error 500, with error message:

> session_start(): Cannot send session cookie - headers already sent by (output started at /srv/www/artemis-project/vendor/symfony/phpunit-bridge/SymfonyTestsListener.php:82)

If I comment out that line, saying `echo "Testing $suiteName\n";`, everything runs OK. I've been googling for it, but can't find any relevant data.

Controller action, running in tests is:

```php
    public function getCSRFTokenAction(Request $request, $action)
    {
        $this->checkOrigin($request);
        $tokenId = $this->getCSRFTokenIdForAction($action);

        $csrfManager = $this->get('security.csrf.token_manager');
        $token = $csrfManager->refreshToken($tokenId);
        $view = $this->view($token, 200);

        return $this->handleView($view);
    }
```

**Comment by Simperfit** [comment]
@alulord Could you please create a little project that we can run to reproduce the error ? It will help to find and fix if it's a bug.

**Comment by alulord** [comment]
@Simperfit I'm a little busy right now, but I'll do it ASAP

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
