### ISSUE TITLE
symfony/form blockPrefix of choice entries not include custom parent blockPrefix

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#26062]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

According to [this document](http://symfony.com/doc/current/form/create_custom_field_type.html), in case if I create custom form type, extending `ChoiceType` or `EntityType` (for example ShipmentType) and override it `getBlockPrefix` method (for example "my_custom_shipment"), I can use `overrided_block_prefix_entry_widget` to override widget of `CheckboxType` of `RadioType`. But this does not work. `overrided_block_prefix` is not added to `block_prefixes` of choices.

This happens because in `BaseType` while `blockPrefixes` calculate, only parent types of choices are used, without adding parent block_prefix.

Full example:

```twig
{% block my_shipment_widget %}
    this works
    {{ block("choice_widget_expanded") }}
{% endblock %}

{% block my_shipment_entry_label %}
    this does not work
{% endblock %}

{% block my_shipment_entry_widget %}
    this does not work
{% endblock %}
```

```php
class ShipmentType extends AbstractType
{
	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'class'         => Shipment::class,
			'multiple'      => false,
			'expanded'      => true,
			'choice_label'  => "name",
		]);
	}

	public function getParent(): string
	{
		return EntityType::class;
	}

	public function getBlockPrefix(): string
	{
		return "my_shipment";
	}
}
```

**Comment by webnet-fr** [comment]
Hi @wtorsi ! 

as far as I understand you are trying to create a collection of shipments:

```
class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('shipments', CollectionType::class, [
            'entry_type' => ShippingType::class
        ]);
    }
}
```

Note that in this case the list of prefixes of single shipment entry will be : 

> 0 => "form"
> 1 => "choice"
> 2 => "my_shippment"
> 3 => "_order_shipments_entry"

In particular the prefix "_order_shipments_entry" is composed from :
- "order" - is the prefix of OrderType 
- "shipments" - field name speficied in `OrderType::buildForm`
- "entry" - indicates the single entry of the "shipments" collection

So, if you want to apply a theme to all entiries of "shipment" collection in "OrderType" form you should use these blocks:

```
{% block _order_shipments_entry_row %}
    ....
{% endblock %}

{% block _order_shipments_entry_widget %}
    ....
{% endblock %}

{% block _order_shipments_entry_label %}
    ....
{% endblock %}
```

As you can see the prefix in this case doesn't depend on prefix of underlying type. And should not.

On the other hand if you want to apply a theme to all fields of `ShipmentType` (in any form) you can do so by adding these blocks:

```
{% block my_shippment_row %}
...
{% endblock %}

{% block my_shippment_widget %}
...
{% endblock %}

{% block my_shippment_label %}
...
{% endblock %}
```

Status: Works for me

**Comment by wtorsi** [comment]
Hi @webnet-fr
Your code works fine, I can approve.
But, I would like to override blocks for all collection entries for my ShipmentType, in any kind of ParentType.  As said in this info block from doc page

```
You can further customize the template used to render each children of the choice type. 
The block to override in that case is named "block name" + _entry + "element name" 
(label, errors or widget) (e.g. to customize the labels of the children of the Shipping 
widget you'd need to define {% block shipping_entry_label %} ... {% endblock %}).
```

I mean
```
{% my_shipment_entry_label %}
...
{% endblock %}

{% my_shipment_entry_widget %}
...
{% endblock %}
```

**Comment by webnet-fr** [comment]
Ok, I found a problem and it certanely looks like a bug. I suppose it is an error in the documentation rather than in the code.
Here is an example. Order type:
```
class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('shipment', ShippingType::class, [
                'expanded' => true // Only when the choice is expanded it has children
            ])
        ;
    }
}
```

ShippingType:
```
class ShippingType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => array(
                'Standard Shipping' => 'standard',
                'Expedited Shipping' => 'expedited',
                'Priority Shipping' => 'priority',
            )
        ));
    }

    public function getParent()
    {
        return ChoiceType::class;
    }

    public function getBlockPrefix()
    {
        return 'my_shipment';
    }
}

```

Prefixes of `$formView['shipment']['0']`, `$formView['shipment']['1']` and `$formView['shipment']['2']`:
```
0 => "form"
1 => "checkbox"
2 => "radio"
3 => "_order_shipment_entry"
```
Pay attention that the type of these children is `RadioType`.  In this case `form`, `checkbox` and `radio` are the prefiexes of all parents of `RadioType` **type**. That is because `block_prefixes` reflects the inheritace of form types: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L79.
Anyway `my_shipment_entry_label` will not work today and the documentation should be updated.

Status: Reviewed

**Comment by wtorsi** [comment]
Yes, you are right @webnet-fr,
It look's like a bug in documentation.
But now, I suppose it will a great feature to override `entry block` of custom `ChoiceType` according to it's container block prefix.

**Comment by emmanuelballery** [comment]
Hi, for those trying to complete their entry block prefixes with the parent form prefix, you may be able to solve this using a form extension. Here is an example in my case:

- I'm extending the `CheckboxType` as it is the child entry type in a `ChoiceType`;
- I'm looking for an `expanded` configuration in the parent form and expecting this value to be `true`;
- I'm adding a block prefix in `block_prefixes` based on the parent form type block prefix;

```php
namespace AppBundle\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class FormEntryExtension extends AbstractTypeExtension
{
    public function getExtendedType()
    {
        return CheckboxType::class;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        if (true === $form->getParent()->getConfig()->getOption('expanded')) {
            $blockPrefix = $form->getParent()->getConfig()->getType()->getBlockPrefix();
            $view->vars['block_prefixes'][] = $blockPrefix . '_entry';
        }
    }
}
```

Then, register your form extension:

```yaml
services:
    AppBundle\Form\Extension\FormEntryExtension:
        tags:
          - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\CheckboxType' }
```

**Comment by xabbuh** [comment]
I am closing here as it looks like we rather need to improve the documentation instead.
