### ISSUE TITLE
[Validator] NotChoice?

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#26074]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

I'm probably missing something very obvious, but how do I do a validation opposite of `Choice`, to make sure a value is **not** part of some predefined set?

I can obviously do a `Callback`, but that's not as clean as I'd like.

**Comment by dkarlovi** [comment]
[The example for `Callback` is literally this use-case](https://symfony.com/doc/current/reference/constraints/Callback.html#the-callback-method) so I'm not missing anything, the only question is if this is worth adding.

**Comment by Zuhayer** [comment]
@dkarlovi Seems like to could be worth exploring.

**Comment by ro0NL** [comment]
@dkarlovi perhaps something like https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/RegexValidator.php#L45 to allow to invert the behavior?

**Comment by ostrolucky** [comment]
Duplicity of https://github.com/symfony/symfony/issues/9888

**Comment by dkarlovi** [comment]
@ro0NL you mean like `match: false`? Yes, that would work, but that's not inline with current architecture where the opposite validator gets the `Not` prefix and a full class, not just a flag.

Either way is OK, I guess.

**Comment by ro0NL** [comment]
TBH i dont see #9888 happen any time soon :) It's nice.. but also very abstract (so far we did without such an architecture).

So yeah `match: true|false` sounds elegant... or at least more elegant then a `NotChoice` which sounds a bit weird-ish in this context IMHO.

> but that's not inline with current architecture 

Not sure we always pursue the `Not` prefix. `NotChoice` sounds really weird to me (opposed to `NotBlank`). And `Regex` already implies it's a valid architecture, probably favored over `NotRegex` for the same reason :)

**Comment by dkarlovi** [comment]
Agreed, `NotChoice` indeed sounds weird. :smile: I'll create a PR with `match` and see what happens. 

Thanks @ro0NL :+1:

**Comment by ostrolucky** [comment]
#9888 is not very abstract. There even is closed PR for it. Someone just needs to take it over.

**Comment by fabpot** [comment]
Closing as there is no more activity here.
