### ISSUE TITLE
[Console] Improve Table performance add BC Break

### ISSUE THREAD

**Issue by Johnmeurt** [symfony/symfony#26081]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | master:2c9922e8afc8f4b2d6d93b63dbfb865b139eac48

The console `Symfony\Component\Console\Helper\Table::render()` gets a fatal error line 282. 

Its method `calculateColumnsWidth` expects an array parameter but `buildTableRows` returns an iterable object.

The error I've got:
`Argument 1 passed to Symfony\Component\Console\Helper\Table::calculateColumnsWidth() must be of the type array, object given`

**Comment by edvordo** [comment]
Can confirm this.

From my testing swapping the lines (281 and 282) fixes this issue and everything seems to work

https://github.com/symfony/console/blob/3a5d4a855f7fb4741cbb34756bf11de3bb31ea6b/Helper/Table.php#L281

**Comment by xabbuh** [comment]
Would you like to submit a PR for this?
