### ISSUE TITLE
Request for Translation in Tagalog Language

### ISSUE THREAD

**Issue by ergiegonzaga** [symfony/symfony#26097]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x

**Comment by stof** [comment]
Translation are contributed by the community. So unless someone knowing this language contributes, this won't happen (I don't think we have anyone in the core team able to do it)

**Comment by ergiegonzaga** [comment]
I am knowledgeable enough with the Tagalog language sir, will you allow me
to have it translated into Tagalog language sir?

**Comment by wnoveno** [comment]
Which part would you want to translate? 
Do you mean the documentation?
You can translate and make a pull request. 
But I don't get the purpose since most Tagalog speakers are bilingual anyway.

**Comment by ergiegonzaga** [comment]
Yes sir i would like to translate the documentation in Tagalog dialect sir. So, you mean sir that you already approve me to translate it in Tagalog sir?

**Comment by xabbuh** [comment]
I would not recommend to translate the documentation. Some time ago we stopped promoting translations that were quite popular back then because they were never (almost) in sync with the English version. Of course, you can try to do that if you want. The license allows for doing it. It's just that you will need to manage everything on your own.

**Comment by ergiegonzaga** [comment]
Okay sir thanks. I will try my best that it will be in sync with the English version.

**Comment by javiereguiluz** [comment]
@ergiegonzaga thanks for your proposal to help Symfony. According to Wikipedia, Tagalog has 28 million native speakers and 45 million L2 speakers, so it's definitely an important language!

Something that you could easily do and would be very helpful is to translate the files Symfony uses to display error messages and other information. There are two main files to translate:

* https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Security/Core/Resources/translations
* https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Validator/Resources/translations

If you need help, this is the guide about how to contribute code to Symfony: https://symfony.com/doc/current/contributing/code/index.html

-----

About translating the Symfony Docs, please don't do it. You'll need several hours per day during several months to translate the entire docs. Then you'll need at least 1 hour a day (forever!) to keep in sync with the latest changes. If you still want to give it a try, I strongly recommend you to only translate the six chapters of the "Getting Started" guide that you'll find at https://symfony.com/doc/current/index.html

Those chapters are enough to help anyone start with Symfony and they are small enough to translate them easily.

**Comment by ergiegonzaga** [comment]
Okay sir thanks :) I will translate the six chapters you recommended to me sir.

**Comment by stof** [comment]
I would still be great if you could contribute the translations for validation messages though.

**Comment by ergiegonzaga** [comment]
okay sir, I have done one string for security sir, I will just start next on validation message.
