### ISSUE TITLE
Symfony profiler don't show password

### ISSUE THREAD

**Issue by biji** [symfony/symfony#26093]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Symfony version  | 4.0

Symfony profiler should not show sensitive data/password from .env, such as

DATABASE_URL
DB_PASS
SMTP_PASS

Thanks

**Comment by dmaicher** [comment]
Why do you think this is a problem? Are you using the web profiler somewhere else except locally on your dev environment?

**Comment by javiereguiluz** [comment]
@biji this feature has been asked occasionally in the past but rejected for several reasons:

* We could remove some default sensitive env vars ... but apps can define lots of other custom sensitive env vars. What if your app defines an env var called `APP_SUPER_SECRET_MASTER_PASSWORD`? That's the most sensitive env var in your app and we'll never remove it because it has a custom name and we know nothing about it.
* Symfony code (both ld and new versions) have code protections to never display the profiler on production servers. If you see the profiler in production, is because someone deliberately has enabled the profiler in production. We can't do anything here because we already protect the profiler but someone removed that protection.

In any case, thanks for taking acre of things like this and proposing ideas to improve Symfony. Cheers!

**Comment by biji** [comment]
Yes, sometimes when troubleshooting we need to enable dev mode in production server

**Comment by biji** [comment]
Ok hiding env vars should be enough :) 

other case, dear client please check this demo site (oops i forget disabling dev mode) 
My client now knows my smtp auth password

**Comment by nicolas-grekas** [comment]
> Yes, sometimes when troubleshooting we need to enable dev mode in production server

if you do that, you have to at least restrict that by IP.

**Comment by biji** [comment]
@javiereguiluz understood, but at least no clear text password easily exposed. if profiler loops $_SERVER , DATABASE_URL and MAILER_URL might be masked too, or removed instead

> The .env file is special, because it defines the values that usually change on each server. For example, the database credentials on your local development machine might be different from your workmates. That's why this file is not committed to the shared repository and is only stored on your machine. In fact, the .gitignore file that comes with Symfony prevents it from being committed.

From docs: preventing .env being commited is to protect credentials, even among developer team. 
For example when developing: "Bro, check out my laptop URL, is the bug fixed?" then his friend knows the super secret password personal smtp password

**Comment by biji** [comment]
![image](https://user-images.githubusercontent.com/665559/36024846-99d64ac6-0dc3-11e8-8fec-9bf4dcddddff.png)

![image](https://user-images.githubusercontent.com/665559/36024793-683b8f62-0dc3-11e8-94ab-8dbd11e66d2f.png)

created dirty hack by masking values in SYMFONY_DOTENV_VARS

**Comment by curry684** [comment]
> Yes, sometimes when troubleshooting we need to enable dev mode in production server

Don't, just don't. Can't find the link right now but fabpot himself recently posted explicitly that any kind of access to the profiler essentially means remote full control over your webserver. The env variables with passwords are the least of your problems if you accidentally *or intentionally* enable the profiler in production environments.

Use logging to discover production issues, or snapshot them so you can reproduce them in an actual dev environment where it is safe to run the profiler.

**Comment by biji** [comment]
Is there any doc/example to put the password in yml (the old way :)
Sorry for asking support here, I'm new symfony user was using ZF

**Comment by javiereguiluz** [comment]
@biji if you don't want to use env vars and don't want to make lots of changes in your app, you can remove them from your `.env`/`.env.dist` files and define them as regular parameters in `config/services.yaml` (in Symfony 4) or `app/config/parameters.yml` (in Symfony 3):

```yaml
parameters:
    env(DATABASE_URL): '...'
```

If you have more questions about this, it's better to use any of the channels shown here: https://symfony.com/support

**Comment by sstok** [comment]
A better and saver solution to store password and access tokens is to store them in a separate file, and use an env processor to load the file's contents. This still allows the same flexibility as using env variables is much more secure. http://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables

If your using Docker there also additional techniques for this 👍
