### ISSUE TITLE
Routes containing a period/dot don't work

### ISSUE THREAD

**Issue by RiesWeug** [symfony/symfony#26099]
| Q                | A
| ---------------- | -----
| Bug report?      | **yes**/no
| Feature request? | yes/**no**
| BC Break report? | yes/**no**
| RFC?             | yes/**no**
| Symfony version  | 4.0.0

I have created my routing using the following annotation:
```
/**
* @Route("/project/{id}/{file}.{extension}", methods={"GET"}, name="get_project_image")
*/
```

When I run `php bin/console debug:router`, it shows my route:
`get_project_image               GET      ANY      ANY    /api/project/{id}/{file}.{extension}`

However, when I navigate towards the URL, it gives me the following error (the "/api" in front of the URL is because I have another route on my controller":
`No route found for "GET /api/project/1/test.xml"`

This is very confusing to me, this should work [according to the Symfony docs](https://symfony.com/doc/current/routing.html#id1).

**Comment by wnoveno** [comment]
Is it possible that you might have a collision on your routes?
If you have
```
/api/project/{id}/{file}
/api/project/{id}/{file}.{extension}
```
GET /api/project/1/test.xml would be read as the first one.

**Comment by javiereguiluz** [comment]
@RiesWeug as @wnoveno said, this is probably because of a route collision. That's why we include a handy command called `router:match` to ask Symfony which route is responding to some given URL. That's how you can verify if the route you want is matching that URL:

```bash
$ ./bin/console router:match /api/project/1/test.xml
```

Now that this question looks like a Symfony support question, we must close it. In GitHub repo we only discuss about new Symfony features and Symfony bugs. For this kind of support questions, you can find more help here: https://symfony.com/support Thanks!

**Comment by RiesWeug** [comment]
@javiereguiluz @wnoveno There's no collision on my routes, I've created a completely new unique URL just to make sure. The outpout of `router:match` actually says that it matches my controller route, but it still gives me a 404 in my browser...

Is there seriously no one who can reproduce this?

**Comment by javiereguiluz** [comment]
If `router:match` says that the URL matches your controller ... then the code of your app is probably correct. One of these things may be happening:

* The web server config is messing with URLs somehow (can you try it with Symfony's builtin web server to check if it works?)
* The code of your controller is generating a 404 error somehow.

**Comment by RiesWeug** [comment]
@javiereguiluz Negative. I'm using the builtin web server, I'm running it using the following command: `php bin/console server:run 192.168.1.128:8000`. All I'm doing in the controller is generating a new Response and returning it.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by RiesWeug** [comment]
@xabbuh I just tried reproducing this issue with a clean project, but indeed, it seems to work over there... What could possibly be the difference?

**Comment by xabbuh** [comment]
Does it only happen when using the built-in web server? Could you upload your project somewhere?

**Comment by RiesWeug** [comment]
@xabbuh what is an alternative way to run my server?

**Comment by xabbuh** [comment]
Nginx or Apache for example, see http://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by RiesWeug** [comment]
@xabbuh I can't reproduce this issue with a clean project using the built-in web server, so it's not an issue with that... I'm so lost.

**Comment by NeilMasters** [comment]
I have come across this issue and believe its the period in the actual route. With a basic controller(provided below) router:match works on both /test/example-value and /test/example.value however a http request to example.value will return a 404.

`<?php
declare(strict_types=1);

namespace App\Controller\Web\Site;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    /**
     * @Route("/test/{value}", name="test")
     */
    public function test(string $value): Response
    {
        return new Response();
    }
}
`

`bin/console router:match /test/example-value                                                                         

 [OK] Route "test" matches


+--------------+-----------------------------------------------------------+
| Property     | Value                                                     |
+--------------+-----------------------------------------------------------+
| Route Name   | test                                                      |
| Path         | /test/{value}                                             |
| Path Regex   | #^/test/(?P<value>[^/]++)$#sD                             |
| Host         | ANY                                                       |
| Host Regex   |                                                           |
| Scheme       | ANY                                                       |
| Method       | ANY                                                       |
| Requirements | NO CUSTOM                                                 |
| Class        | Symfony\Component\Routing\Route                           |
| Defaults     | _controller: App\Controller\Web\Site\TestController::test |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler   |
+--------------+-----------------------------------------------------------+
------------------------------------------------------------

curl -I http://localhost:8000/test/example-value                                                                     
HTTP/1.1 200 OK
Host: localhost:8000
Date: Thu, 06 Jun 2019 07:57:14 +0000
Connection: close
X-Powered-By: PHP/7.2.17
Cache-Control: no-cache, private
Date: Thu, 06 Jun 2019 07:57:14 GMT
Content-Type: text/html; charset=UTF-8

bin/console router:match /test/example.value                                                                         


 [OK] Route "test" matches


+--------------+-----------------------------------------------------------+
| Property     | Value                                                     |
+--------------+-----------------------------------------------------------+
| Route Name   | test                                                      |
| Path         | /test/{value}                                             |
| Path Regex   | #^/test/(?P<value>[^/]++)$#sD                             |
| Host         | ANY                                                       |
| Host Regex   |                                                           |
| Scheme       | ANY                                                       |
| Method       | ANY                                                       |
| Requirements | NO CUSTOM                                                 |
| Class        | Symfony\Component\Routing\Route                           |
| Defaults     | _controller: App\Controller\Web\Site\TestController::test |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler   |
+--------------+-----------------------------------------------------------+

curl -I http://localhost:8000/test/example.value                                                                     
HTTP/1.1 404 Not Found
Host: localhost:8000
Date: Thu, 06 Jun 2019 07:58:11 +0000
Connection: close
Content-Type: text/html; charset=UTF-8
Content-Length: 551`

If i come across anything further I will add some notes.

**Comment by TomasVotruba** [comment]
I have same issue:

- built-in PHP server
- Symfony 5.0.5
- it can be found in `debug:routing`
- dot in the route path

```php
* @Route(path="api/groups.json", name="api_groups_json", methods={"GET"})
````

- `api/groups_json` works
- `api/groups.json` does not

**Comment by NeilMasters** [comment]
@TomasVotruba 

router.php:

`<?php
/**
 * This router is required if you are running the built in PHP web server
 * as it attempts to route static files through the natural router(index).
 */
if (php_sapi_name() == 'cli-server') {
    $info = parse_url($_SERVER['REQUEST_URI']);

    if ($info !== false && file_exists(sprintf("./%s", $info['path']))) {
        return false;
    } else {
        include_once "index.php";
        return true;
    }
}
`

Dump that into your public directory and when you start the php server append it with `router.php` as in `php -S localhost:8000 router.php`

This is a bug with php' built in server so the issue is correctly closed. The problem is that the server is detecting the route as a static file. I had the issue with /sitemap.xml which was dynamically generated and you have the same issue with groups.json

**Comment by TomasVotruba** [comment]
@NeilMasters Thanks for reaching out. I would not figure that out in million years.

How exactly that looks from the root directory? I can't find a way to make it work :/ Either routers doesn't work, or css are broken.

```php
php -S localhost:8001 -t public public/router.php
```

**Comment by stof** [comment]
@TomasVotruba Try to replace the `./%s` in the `file_exists` check to use `$_SERVER['DOCUMENT_ROOT'].` rather than `.` as base, to make this relative to the document root rather than the current working directory.

**Comment by TomasVotruba** [comment]
I think I'll settle with non-suffixed files for now. This could be really WTF as I don't know anybody using local server with extra files.

Thanks for explaning.

**Comment by stof** [comment]
well, common extra files are your assets. and another case is when you don't have a router entrypoint.

**Comment by kennaar** [comment]
> I think I'll settle with non-suffixed files for now. This could be really WTF as I don't know anybody using local server with extra files.
> 
> Thanks for explaning.
> 
> Btw, any link to the PHP bug issue?

This seems to be the one: https://bugs.php.net/bug.php?id=61286

**Comment by MusikAnimal** [comment]
I ran into this issue after upgrading Symfony. In my case I still had the Symfony built-in server running as I made my changes, and it somehow got confused -- only failing for routes with periods in the path. Doing a hard stop/start of the server didn't work either; I ended up having to `kill -9` the process. Recording my findings here in case it helps anyone else.

**Comment by kadnan** [comment]
@NeilMasters 

> ```
> @Route(path="api/groups.json", name="api_groups_json", methods={"GET"})
> ```

I get error:

```
Fatal error: Uncaught TypeError: Invalid return value: callable object expected, "bool" returned from "router.php". in /Users/xx/Data/xxx/xx/development/LAMP/vendor/autoload_runtime.php:18 Stack trace: #0 /Users/xx/Data/xxx/xx/development/LAMP/public/index.php(5): require_once() #1 /Users/xx/Data/xxx/xx/development/LAMP/public/router.php(12): include_once('/Users/xx...') #2 {main} thrown in /Users/xx/Data/xx/xxx/development/LAMP/vendor/autoload_runtime.php on line 18
```

**Comment by NeilMasters** [comment]
@kadnan That code was written 3.5 years ago I think for php 7.1 maybe 7.2... I am not suprised it no longer works.

**Comment by wouterj** [comment]
Please use one of the community support channels (https://symfony.com/support) to get help with your issue.
This tracker is only used to track bugs.
