### ISSUE TITLE
[XmlFileLoader] — Throw exception when key is not a string?

### ISSUE THREAD

**Issue by roukmoute** [symfony/symfony#26105]
| Q                | A
| ---------------- | -----
| Bug report?      | perhaps
| Feature request? | perhaps
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Is it normal that we can get a `key` is not a string when it is not possible to have a key that is not a character string.
So if we have anything like that:
```xml
<parameter id="my.options" type="collection"/>
```
We get in ParameterBag in our container, something like that (via `$container->getParameterBag->all()`):
```php
…
0 => [],
…
```

Si I can do a new P.R. with something like that:
```php
if (false === is_string($key) && 'parameter' === $name && false === empty($arg->getAttribute('type'))) {
    throw new InvalidArgumentException(sprintf('Parameter "%s" has no "key" string in "%s".', simplexml_import_dom($arg)->asXML(), $file));
}
```

**Comment by nicolas-grekas** [comment]
Hello,
yes it is, <parameter> tags allow defining nested arrays also, with numbers as keys.
