### ISSUE TITLE
TwigBundle/ProfilerBundle JavaScript error

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#26118]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Javascript error is report to the JS console (tested in Chrome and Edge) when the exception is handled by Symfony Profiler:
```
Uncaught TypeError: Cannot set property 'className' of null at Object.createTabs
```

May be related to https://github.com/symfony/symfony/pull/24281.

### Steps to reproduce:

1) Create a new flex project
```
composer create-project symfony/skeleton blog
cd blog
composer require server --dev
composer require profiler --dev 
```
2) Create a controller and enable its route in `config/routes.yaml`:
```php
<?php
namespace App\Controller;

class DefaultController {
	public function index()
	{
		throw new \Exception('Wow!');
	}
}
```
3) Run `php bin\console server:run`
4) Open the browser
5) Info about the exception is rendered properly
6) But there is an error in the browser JS console

**Comment by ro0NL** [comment]
Duplicates https://github.com/symfony/symfony/issues/25894

**Comment by mhujer** [comment]
Just noticed https://github.com/symfony/symfony/issues/25894, so I'm closing this one.

**Comment by ro0NL** [comment]
We're fast today :D
