### ISSUE TITLE
[Lock] Semaphore is always released automatically

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony#26129]
| Q                | A
| ---------------- | -----
| Bug report?      | perhaps
| Feature request? | perhaps
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

In the class Factory the method public function createLock($resource, $ttl = 300.0, $autoRelease = true) has the parameter $autoRelease. But it is not passed to the class SemaphoreStore where in the method private function lock(Key $key, $blocking) the function sem_get is used, which fourth parameter $auto_release default is 1 and is not overwritten.

If using SemaphoreStore you will so always get an automatic release, even if you have specified something else in the factory.

**Comment by jderusse** [comment]
In opposition with remote locks (memcached, redis), local locks (filesystem, semaphore) does not expires and couldn't be released if somehing goes wrong.

removing the "autoRelease" on semaphore store could lead on a inconsistent state, where the lock couln't be acquired nor released.

NB: It's impossible to remove the "autoRelease" behavior of fileSystem store. Once the process dies, the lock is automatically released by the kernel.

**Comment by nicolas-grekas** [comment]
@jderusse do you mean this report is not accurate and there is no bug? Shall we close then?

**Comment by jderusse** [comment]
It's not a bug, the lock is not removed by the autorelease feature, it's release because semaphore are linked to the process.

At best, we can improve documentation by reminding that semaphore and flock are released by the kernel at end off process
