### ISSUE TITLE
Generated route name are missing underscores 

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26133]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

This is not really a bug report, but I'm surprised to find any issue about that.

With the given controller:

```php
/**
 * @Route("/oauth")
 * @IsGranted("ROLE_USER")
 */
final class OAuthController extends AbstractController
{
    /**
     * @Route("/redirect/github")
     * @Method("GET")
     */
    public function redirectGithubAction()
    {
    }
```

The generated route is `app_oauth_connectgithub`.

IMHO, it should be more convenient to have `app_oauth_connect_github`.

Of course it's not a "bug" as the thing is working like this, but it may be improved.

Changing route naming is BC break. Maybe an option could be added for that.

WDYT?

**Comment by Tobion** [comment]
👎 To add config for this. Either use the default naming or specify your own name.
