### ISSUE TITLE
Updating packages exhausts my memory while running tests.

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#26145]
| Q                | A
| ---------------- | -----
| Bug report?      | Maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x

Hello,

I have run a composer update to my project runnning PHP 5.6

These are the packages that have been updated:

| Package        | Old Version | New Version
| -------------- | ----------- | ----------
| league/csv | 8.2.2 | 8.2.3
| php-amqplib/php-amqplib | v2.7.0 | v2.7.2
| symfony/polyfill-mbstring | v1.6.0 | v1.7.0
| symfony/polyfill-php70 | v1.6.0 | v1.7.0
| symfony/polyfill-util | v1.6.0 | v1.7.0
| symfony/polyfill-php56 | v1.6.0 | v1.7.0
| symfony/symfony | v3.4.3 | v3.4.4
| symfony/polyfill-intl-icu | v1.6.0 | v1.7.0
| symfony/polyfill-apcu | v1.6.0 | v1.7.0
| sensio/framework-extra-bundle | v5.1.4 | v5.1.5
| symfony/phpunit-bridge | v3.4.3 | v3.4.4
| webmozart/assert | 1.2.0 | 1.3.0
| phpspec/prophecy | 1.7.3 | 1.7.4

One of these packages seems to have increased the memory usage of my tests. Most of them are symfony packages so I thought I might ask here first.

`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /vhosts/payway.trading-point.com/symfony/var/cache/test/ContainerHnbtgen/appTestDebugProjectContainer.php on line 9372`

My tests used to get around 400 MB

**Comment by javiereguiluz** [comment]
@gmponos this is probably related to this issue which has already been fixed and it will be released as part of the next 3.4.5 version:

[Possible regression: Memory consumption 10x higher from 3.4.3 -> 3.4.4](https://github.com/symfony/symfony/issues/25964)

**Comment by gmponos** [comment]
Closing most probably as duplicate.
