### ISSUE TITLE
[SF4] Console Command not working without service declaration

### ISSUE THREAD

**Issue by emulienfou** [symfony/symfony#26155]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

**Issue:** Bundle console command is not working if command not declared as a service!

However, if you create a command in your current application it's working is this case without be declared as a service.
If you create a bundle and use it in your application, the command class need to be declared as a service.

This is not specified in the next documentation page: https://symfony.com/doc/current/console.html

And Yes! I'm using the default configuration as explained here: https://symfony.com/doc/current/service_container.html#service-container-services-load-example

Can you tell if it's an issue or not, and in the other case, need to be specified to the official documentation.

**Comment by xabbuh** [comment]
That's expected, command classes are not auto discovered in Symfony 4 anymore, but must be registered as services (which is done implicitly for you when using the default directory layout and service definition). If you think that this could be improved in the docs, please open a new issue in the documentation repository.
