### ISSUE TITLE
Improve framework.validation.cache deprecation message

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#26151]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.1

Deprecation message:

```The "framework.validation.cache" option is deprecated since Symfony 3.2 and will be removed in 4.0. Configure the "cache.validator" service under "framework.cache.pools" instead.```

It's not clear how one should fix this deprecation. `cache.validator` should be the name, right?

I was reading https://symfony.com/doc/current/reference/configuration/framework.html, but still can't wrap my head around pools and how to govern changes in order to get my applicaion updated without BC breaks. I was using APC cache for validation metadata caching, and I am not sure how to configure it with using pools.

I guess it should be something like (I bet APC is missing somewhere in this config):

```yaml
framework:
    cache:
        pools:
            cache.app.validator:
                name: cache.validator
```

but my debug sessions show that in such case `ValidationBuilder::setMetadataCache()` is not called any more (which was the case with the previous config).

**Comment by umpirsky** [comment]
I'm willing to contribute in fixing this, just need more info about the actual way to fix the deprecation. How should "cache.validator" service config under "framework.cache.pools" look like?

**Comment by nicolas-grekas** [comment]
`cache.validator` is already configured, so you should just remove the config and let the default work IMHO.

**Comment by umpirsky** [comment]
I used:

```yaml
framework:
    validation:
        enable_annotations: true
        cache: my_validation_cache
```

Where:

```xml
<service id="my_validation_cache" class="Symfony\Component\Validator\Mapping\Cache\DoctrineCache">
    <argument type="service" id="my_apc_cache" /> <!-- Doctrine\Common\Cache\ApcuCache -->
</service>
```

Something like that. To cache validation metadata with APCu.

Are you sure that it's the default behavior now? Where is it configured, I'd like to understand that magic if there is one.

@nicolas-grekas Thanks a lot for the answer!

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.xml

`cache.validator` derivated from `cache.system`, which uses `AbstractAdapter::createSystemCache()` as a factory, which uses the best available backend for system caches.

With this knowledge, feel free to change the deprecation message in a new PR if you think you have a better proposal.

**Comment by umpirsky** [comment]
@nicolas-grekas Well, in my case it's `FilesystemAdapter`. I never used or configured `cache.pool` nor `cache.system`, that's why this change is a "breaking" one for me.

In order to keep things backward compatible in my project, I need to configure `cache.system` to use APCu. Looking at https://symfony.com/doc/current/reference/configuration/framework.html#pools just confuses me with "Your pool name must differ from cache.app or cache.system", so, how do I configure `cache.system` then?

Sorry for being PITA. Just link the correct docs page if I'm missing one. Thanks!

**Comment by xabbuh** [comment]
The system cache pool can be configured using the [`cache.system`](https://symfony.com/doc/current/reference/configuration/framework.html#system) option. In your case it should probably be something like this:

```yaml
framework:
    cache:
        system: cache.adapter.apcu

**Comment by nicolas-grekas** [comment]
But the default factory should really be the best, as it allows correct warm up and clearing of apcu, and uses it automatically when it's available.
If Apcu is not used, it means you don't have apcu.

**Comment by umpirsky** [comment]
```
```

@nicolas-grekas

**Comment by xabbuh** [comment]
You could debug what it is going on in `AbstractAdapter::createSystemCache()` (particularly `function_exists('apcu_fetch')` and `ini_get('apc.enabled')`).

**Comment by umpirsky** [comment]
@xabbuh `AbstractAdapter::createSystemCache()` is never called for me. Probably because I never use it.

**Comment by nicolas-grekas** [comment]
@xabbuh I downvoted your comment because there is no reason to ever force apcu.
@umpirski apcu is not enabled on the cli by default, but apcu is not useful on the cli either. So here is what happens: on the cli, there is no apcu, so a filesystem cache is created. Then, on FPM, apcu is enabled hopefully, and then white magic, apcu is seeded by the filesystem cache so that things are already warmed up.

**Comment by umpirsky** [comment]
No, here is the situation. :)

By default:

![screenshot from 2018-02-23 12-05-08](https://user-images.githubusercontent.com/208957/36591301-d94fe170-1891-11e8-9025-2793704f3d42.png)

With:

```yaml
framework:
    cache:
        system: cache.adapter.apcu
```
![screenshot from 2018-02-23 12-06-14](https://user-images.githubusercontent.com/208957/36591337-fc2a6260-1891-11e8-9b3b-951af827233c.png)

Which makes additional forcing config optional as @nicolas-grekas said.

So, it should all work good since validator uses `cache.system`. Just not sure why `cache.system` and `cache.app` use different adapters.

Thanks for useful information!
