### ISSUE TITLE
Requsting for Tagalog translation

### ISSUE THREAD

**Issue by Cyyy1998** [symfony/symfony#26163]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

**Comment by xabbuh** [comment]
Can you be a bit more precise about which translations you are missing?

**Comment by Cyyy1998** [comment]
Filipino translation

**Comment by nicolas-grekas** [comment]
Good news, translations for Tagalog have just been merged thanks to the work of @ergiegonzaga 

See https://github.com/symfony/symfony/pulls?q=is%3Apr+tagalog+is%3Aclosed

Closing therefore.
