### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by boscho87** [symfony/symfony#26164]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| Symfony version  | 3.3.15

The Symfony Email Validator needs to support FILTER_VALIDATE_EMAIL Standards (64 signs local part)

**Comment by xabbuh** [comment]
The email validator moved away from using `filter_var()` some time ago as it did not produce good results. If you want to have more precise results, you will need to use the `strict` mode which uses the `egulias/email-validator` library. Starting with Symfony 4.1 you will also be able to choose HTML5 as the validation mode.
