### ISSUE TITLE
Add cost configuration for argon2i encryption

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony#26174]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 4.0.4

Add cost configuration for argon2i encryption. Just like with bcrypt.
It would be awesome to have a lower cost in the test-environment to speed up functional tests.

**Comment by nicolas-grekas** [comment]
Would be great, please submit a PR doing so :)

**Comment by CoalaJoe** [comment]
Added a base PR, but I am not sure, if this is applicable.
