### ISSUE TITLE
[Cache] Invalidate tags doesn't work

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#26178]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | -
| Symfony version  | 3.x and up ?

Hello,

I assume I found a bug resulting in **not removing tags from a cache pool**

Here's what I did _(link to the reproducible example below)_:

1. Create 2 cache adapter services the default `@cache.app` and `@cache.tags`. The last one will be used to store the tags on another namespace, [like documented here](http://symfony.com/doc/3.4//components/cache/cache_invalidation.html#tag-aware-adapters).

2. Create a `foo` cache key entry and tag it with `tag1` and  `tag2` tags.
Redis view: 
![127_0_0_1_-_phpredisadmin](https://user-images.githubusercontent.com/346010/36215859-88621020-11ad-11e8-8ff4-484d757d04d2.png) ![127_0_0_1_-_phpredisadmin](https://user-images.githubusercontent.com/346010/36215936-b9f061f0-11ad-11e8-97d7-64a6ec385800.png)

2 keys are present under one namespace (X)
 * 1 key containing the tags
 * 1 key containing the cached value

So already, right there, **the first bug is that the tags are not stored inside another namespace of redis like it's supposed to by using the namespace of the 2nd adapter**.

3. Run the command to remove all `tag1` tags from the cache `bin/console test:clear:tags tag1` that calls `$this->cache->invalidateTags($tags);`:
Redis view: 

![127_0_0_1_-_phpredisadmin](https://user-images.githubusercontent.com/346010/36216061-06aa7f76-11ae-11e8-96cb-fac5ed071916.png)

A **new namespace is created** (??¿¿), a new key is created (¿¿??) with a different format than the others, and the **items tagged with `tag1` are not deleted** (still present in the other redis namespace)

I tested this in the same (`dev` environement) because I know that the seed prefix / namespace are generated based on the env (among other things).

Resources:
- [config.yml](https://github.com/tristanbes/symfony-cache-profiler-bug/blob/invalidateTagsBug/app/config/config.yml#L33)
- [services.yml](https://github.com/tristanbes/symfony-cache-profiler-bug/blob/invalidateTagsBug/app/config/services.yml#L25)
- [GlobalStatistics](https://github.com/tristanbes/symfony-cache-profiler-bug/blob/invalidateTagsBug/src/AppBundle/Manager/GlobalStatistics.php#L27)
- [RemoveCacheByTagsCommand](https://github.com/tristanbes/symfony-cache-profiler-bug/blob/invalidateTagsBug/src/AppBundle/Command/RemoveCacheByTagsCommand.php#L41)

Complete github repository:  https://github.com/tristanbes/symfony-cache-profiler-bug/tree/invalidateTagsBug

**Comment by nicolas-grekas** [comment]
I just read carefully your description, and this is just the expected internal behavior. If you found a bug, then please describe it. A bug in this case would be something unexpected happening when using the public interfaces of the tagged cache pool, eg fetching an items while its tag has been invalidated.
The rest is internal detail. Yes, that's how it works, and has to work, to hande race conditions and have decent performances.

**Comment by tristanbes** [comment]
The bug is: the item is not deleted.

I can sum up to: 

A. Store item with X tag
B. Run the command to delete all items with the X tag
C. Items with the X tags are still present under redis.

**Comment by nicolas-grekas** [comment]
Yes, that's correct, and that's not a bug. If you try to fetch the item from the tagged pool, you will get a miss. That's all that matters from the consumer pov.

**Comment by tristanbes** [comment]
oh, okay. I was implementing a command to invalidate tags and I was only checking with the phpRedisAdmin. I excepted keys to be null or deleted. That's why I found it was a bug.
Anyway, hope this issue helps other that will think the same than me ;-)

Thanks @nicolas-grekas, I think I can close the issue then.

**Comment by tristanbes** [comment]
And just for the D. is it a misunderstanding ? or it's when trying to clear the tags that something will be created under a new namespace for perf issues ?

**Comment by nicolas-grekas** [comment]
The list of tags of an item is stored next to the item, in the same pool. This allows fetching them in one single query for many backends, and allows same-time expiration also (not time-delta issue.)
The second pool is used the store the version number of each tag, standalone.
When a tag is invalidated, this version number is incremented and nothing else happens. This allows invalidating an infinite number of related items atomitcally, without killing the backend iterating over a potentially huge number of items.
As stated previously, when an items is fetch, we also fetch the list of tags for the item. But what I didn't say before is that for each tag of the item, we also keep the version of the tag that was valid at the item was stored. If this version differs from the version of the tag in the second pool, then the tag has been invalidated, and that's a miss.
No deletion ever occur because that would create race conditions otherwise.
If you want deletion, just call `->deleteitem()`.

**Comment by sepehr** [comment]
Thank you both for the conversation. Clarified a lot.
