### ISSUE TITLE
307 redirect for POST/PUT requests

### ISSUE THREAD

**Issue by cooldude77** [symfony/symfony#26171]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | unsure
| RFC?             | unsure
| Symfony version  | 2.8.33

I have a version v2 of an API which has majority routes going back to V1, except for a few . 
**For v2**
```

v2_rest_save_adresses:
    pattern:  api/v2/addresses
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: rest_save_adresses
        permanent: false
```

**For V1**
```

rest_save_adresses:
    pattern:  api/v1/addresses
    defaults: { _controller: XYZRestBundle:Address:create}
    methods: [POST]

```

The GET requests get redirected with 302 code successfully, while the post requests see an error like this 

`No route found for "GET /api/v1/addresses": Method Not Allowed (Allow: POST)`

The class that does the routing has handling only for parameters 301 and 302. 

```

    /**
     * Redirects to another route with the given name.
     *
     * The response status code is 302 if the permanent parameter is false (default),
     * and 301 if the redirection is permanent.
     *
     * In case the route name is empty, the status code will be 404 when permanent is false
     * and 410 otherwise.
     *
     * @param Request    $request          The request instance
     * @param string     $route            The route name to redirect to
     * @param bool       $permanent        Whether the redirection is permanent
     * @param bool|array $ignoreAttributes Whether to ignore attributes or an array of attributes to ignore
     *
     * @return Response A Response instance
     *
     * @throws HttpException In case the route name is empty
     */
    public function redirectAction(Request $request, $route, $permanent = false, $ignoreAttributes = false)
    {
        if ('' == $route) {
            throw new HttpException($permanent ? 410 : 404);
        }

        $attributes = array();
        if (false === $ignoreAttributes || is_array($ignoreAttributes)) {
            $attributes = $request->attributes->get('_route_params');
            unset($attributes['route'], $attributes['permanent'], $attributes['ignoreAttributes']);
            if ($ignoreAttributes) {
                $attributes = array_diff_key($attributes, array_flip($ignoreAttributes));
            }
        }

        return new RedirectResponse($this->container->get('router')->generate($route, $attributes, UrlGeneratorInterface::ABSOLUTE_URL), $permanent ? 301 : 302);
    }
```
This is the reason that a request that is post and that should be redirected with [307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) status code is not redirected at all, leading to even POST requests getting transferred as GET. 

I just changed  line `
 return new RedirectResponse($this->container->get('router')->generate($route, $attributes, UrlGeneratorInterface::ABSOLUTE_URL), $permanent ? 301 : 302);`

To
`
return new RedirectResponse($this->container->get('router')->generate($route, $attributes, UrlGeneratorInterface::ABSOLUTE_URL), 307);`

And this works well ( of course not completely correct). I think this needs an enhancement to even allow POST requests to be redirected. 

Proposed solution : (Since I have not learned the pull process completely) 
```
    public function redirectAction(Request $request, $route, $permanent = false, $postOrPut = false, $ignoreAttributes = false)
    {
        if ('' == $route) {
            throw new HttpException($permanent ? 410 : 404);
        }

        $attributes = array();
        if (false === $ignoreAttributes || is_array($ignoreAttributes)) {
            $attributes = $request->attributes->get('_route_params');
            unset($attributes['route'], $attributes['permanent'], $attributes['ignoreAttributes']);
            if ($ignoreAttributes) {
                $attributes = array_diff_key($attributes, array_flip($ignoreAttributes));
            }
        }

        if (true == $postOrPut)
            $code = 307;
        else $code = $permanent ? 301 : 302;

        return new RedirectResponse($this->container->get('router')->generate($route, $attributes, UrlGeneratorInterface::ABSOLUTE_URL), $code);
    }

```
And in routing use this for POST```

v2_rest_save_adresses:
    pattern:  api/v2/addresses
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: rest_save_adresses
        postOrPut: true

```
And for GET it is same as before

**Comment by Tobion** [comment]
I think the RedirectController can just automatically use 307 when the current scheme is not GET and permanent = false.

**Comment by ZipoKing** [comment]
@Tobion I don't think that it will work as I have met a lot of projects where e.g. resource save (POST) action at the end does redirect to show saved resource (GET) - with 307/308 redirect it will stop working. I think that it should be rather additional parameter for the redirect action which will say if it should be 301/302 or 307/308

**Comment by Tobion** [comment]
@ZipoKing you wouldn't use the RedirectController for this. That would be strange.

**Comment by ZipoKing** [comment]
Yes, I won't but as I said I have seen a lot of crazy code over my career. So therefore I'd rather go with extra bool param saying if we should use 301/302 (as default so backward compability will be kept) or 307/308. I'll try to make some PR later today about that.

**Comment by Soullivaneuh** [comment]
@ZipoKing In this case, maybe put an option for 307/308 redirect with a deprecation message telling it will be the default on next major?

**Comment by ZipoKing** [comment]
Pull request created: https://github.com/symfony/framework-bundle/pull/22

**Comment by ZipoKing** [comment]
(One minute, will create proper one for symfony/symfony)

**Comment by cooldude77** [comment]
Thanks for adding it to 4.0. 
Is it going to be added to 2.8 too , as the problem exists over there too ?

**Comment by cooldude77** [comment]
@Tobion Thanks for your reply. However I believe it is more of a requirement not satisfied, and not a  feature only ,  as there are definitely people using 2.8 + or 3.+ who would use POST/PUT requests in the route. So it does have a problem with backward compatibility too.

**Comment by nicolas-grekas** [comment]
I confirm this is a new feature: that's how the redirect controller behaved for now. If you need the new behavior right now, you can copy/paste the new code in a controller of your own.

**Comment by cooldude77** [comment]
Alright @nicolas-grekas , Thanks for your reply :)

**Comment by ElGecko76** [comment]
Is it possible to send POST parameters to a URL via a RedirectResponse 307 where the "name" of an HTML field is the name of a parameter of the array in the RedirectResponse (for example : "NOM" is the "name" of an HTML field)?

I tried this but the server doesn't seem to receive my params :

```
return new RedirectResponse('https://myurl.com', 307, [
    'NOM'        => $utilisateur->getNom(),
    'PRENOM'     => $utilisateur->getPrenom(),
    'TEL'        => $utilisateur->getTel(),
    'EMAIL'      => $utilisateur->getEmail(),
    'PAYS'       => $utilisateur->getPays(),
]);
```
