### ISSUE TITLE
How to migrate stored sessions without logout users?

### ISSUE THREAD

**Issue by index0h** [symfony/symfony#26198]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.4

Hi.
I start migration from symfony:3.3.15 to symfony:4.0.4, in [upgrade](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md) documentation there is suggestion to move `src/AppBundle/` to `src/`. In my case this step changes namespace from `MyVendor\MyProject\AppBundle` to `MyVendor\MyProject`. Sessions of authorized users contain old namespaces.
I have a question: how I could migrate stored sessions, without logout every user?

Regards

**Comment by scaytrase** [comment]
There is no need in changing namespace, you can tune autoloader to keep it same

**Comment by Simperfit** [comment]
@index0h does the message from @scaytrase works for you ?

I don't think it's possible to migrate the session, at least not without writing a migration script, and even with coding something I don't know if it can be working.

**Comment by index0h** [comment]
@Simperfit yes, it could work. But I changed namespace and just flush sessions))

There is one solution for save sessions: temporary create class aliases for all classes used in sessions and in some time remove them.
But in my case there was a trouble with custom role class. It unserializes without corrent value

**Comment by nicolas-grekas** [comment]
@index0h maybe you'd be interested in reviewing/trying/helping somehow on #26096?

**Comment by xabbuh** [comment]
closing here as we now have a session handler that eases the migration of sessions
