### ISSUE TITLE
Can't put PHP templates in /templates

### ISSUE THREAD

**Issue by biji** [symfony/symfony#26192]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 4.0

I use mixed templates, twig and PHP. In symfony 4 all templates should go to /templates, but for PHP templates symfony only find under /src/Resources/views

Thanks

**Comment by mvrhov** [comment]
AFAIK the templating component is deprecated since 3.4 and the only officially supported template engine is twig.

**Comment by nicolas-grekas** [comment]
There is a discussion about deprecating it, but it's not in 3.4/4.0

**Comment by Tobion** [comment]
Ref. #21035

**Comment by QuentinCurtet** [comment]
I have one question, does the use PHP templates will be deprecated in Symfony 4 ?

Thanks in advance.

**Comment by QuentinCurtet** [comment]
Hi,
I ran into the same issue, is it possible to have any update on this ?

Thanks ^^

**Comment by QuentinCurtet** [comment]
@biji It's possible to do this by redefining a new FilesystemLoader with the new path for your templates and then create a new PhpEngine with this filesystemLoader and it will be ok.

**Comment by Simperfit** [comment]
as of https://github.com/symfony/symfony/pull/26243#issuecomment-406175867 can we close this ?

**Comment by javiereguiluz** [comment]
Closing because in 4.3 we've deprecated the Templating component integration (https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration) and we'll remove official support for PHP templates in Symfony 5.0.

**Comment by biji** [comment]
So PHP is not hypertext preprocessor anymore 😔

**Comment by xxorax** [comment]
Can you reconsider it as Symfony 4.4 is LTS ? I think this bug should be fixed, PHP Engine is still supported in v4.

**Comment by Nek-** [comment]
@xxorax it's not removed in 4.4, just as you expect. But it's deprecated to notice you it's removed in Symfony 5.0. This notification is important so you know it.

**Comment by xxorax** [comment]
@Nek- It's surprizing. Symfony team announced the support for the v4.4 LTS version for the next 3 years. If the team cannot support this feature now, which feature(s) will still be supported in 2 years ?!

The trust of everybody in the LTS version is not based on the _most populars_ features only. Should it be ?

**Comment by derrabus** [comment]
> If the team cannot support this feature now, which feature(s) will still be supported in 2 years ?!

The current feature set will be maintained during the LTS period. New functionality is only added in feature releases. That's how Symfony's release process works.

**Comment by Nek-** [comment]
Be sure the feature will be supported for the whole life of the 4.4 version of Symfony.

@xxorax learn more here: https://symfony.com/releases
