### ISSUE TITLE
BinaryFileResponse is the only Response in HttpFoundation that requires a call to prepare beforehand

### ISSUE THREAD

**Issue by jnvsor** [symfony/symfony#26201]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes?
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2+

`Response`, `StreamResponse`, `JsonResponse` and `RedirectResponse` will all work without a call to `prepare` which is described as:

> This method tweaks the Response to ensure that it is compliant with RFC 2616. Most of the changes are based on the Request that is "associated" with this Response.

So in theory calling prepare should be optional. From an API point of view, if the request was required then the `send*` methods should require a `Request` as a parameter.

So why is it that `BinaryFileResponse` is the only response that is designed not to work without calling `prepare`?

The code below would make it work without requiring a call to `prepare` beforehand, and most of these feel like they should be done in `setFile` rather than `prepare`.

Is there a reason it's done this way?

```php
if (!$this->headers->has('Content-Type')) {
    $this->headers->set('Content-Type', $this->file->getMimeType() ?: 'application/octet-stream');
}

if (!isset($this->offset)) {
    $this->offset = 0;
}
if (!isset($this->maxlen)) {
    $this->maxlen = -1;
}

if (!$this->headers->has('Content-Length')) {
    if (false !== $fileSize = $this->file->getSize()) {
        $this->headers->set('Content-Length', $fileSize);
    }
}

if (!$this->headers->has('Accept-Ranges')) {
    // Only accept ranges on safe HTTP methods
    $this->headers->set('Accept-Ranges', 'none');
}
```

**Comment by mpdude** [comment]
So who‘s calling `setFile()` and who calls `prepare()`?

**Comment by mpdude** [comment]
Oh, and is your use case using the HttpFoundation stand-alone or from the full stack framework?

**Comment by jnvsor** [comment]
I'm referring to HttpFoundation on it's own, with no other dependencies.

`setFile()` is called in the `BinaryFileResponse` constructor and `prepare()` is typically called in `HttpKernel` but in a standalone situation it's the only response object that fails to work without explicitly calling `prepare()`, because maxlen is uninitialized the call to `stream_copy_to_stream` takes `null` as it's `int $maxlength` parameter

**Comment by fabpot** [comment]
You must call `prepare()` for all kind of Responses. It just happens that right now, only `BinaryFileResponse` needs it. And we cannot do it automatically as we need the `Request`.
