### ISSUE TITLE
Valid groupSequence seems not to work properly

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony#26205]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Since Symfony 3.4 it is possible to specify `groups` in `Valid` constraint.
[Here](https://github.com/DonCallisto/sf-34-valid-groups-issue) I provided a working example to prove that `groupSequence` seems not to worworking with `Valid` groups.

Is this a bug or am I missing something here?

To test it, clone the repository and run the command `bin/console app:valid-group-test`

**Comment by DonCallisto** [comment]
After debugging this, it seems that problem isn't related strictly to `groupSequence` but to `Valid` itself: it seems that if you provide more than one group, other groups but the first are ignored

**Comment by DonCallisto** [comment]
Don't know if it's clear what I'm trying to point here, let's be more precise:

- if I validate `Foo` without groups --> no `Bar` validation 
- If I validate `Bar`, I would like: in first place, to apply all `validationsGroup` (like `Default`), otherwise to apply all `validationsGroup` passed through `Valid`.

At the moment, this is not be possible for several reason: the biggest problem is that we don't have the chance to specify something like `outerGroup` and `innerGroup` where `outer` is the one of the entity "holding" the sub-one (so `Foo` in my example) whereas `innerGroup` is the group for the other (so `Bar` in my example).

**Comment by DonCallisto** [comment]
The resolution for one of the problems (so, the "single" `validationGroup` passed through `valid`) could be to modifiy 

https://github.com/symfony/symfony/blob/v3.4.0/src/Symfony/Component/Validator/Constraints/ValidValidator.php#L32

in

`->validate($value, null, $constraint->groups);`

**Comment by eschultz-magix** [comment]
If I understand everything correct here, I can conform this bug. This is my non-working example:

validation.yaml:
```twig
App\Model\Outer:
    properties:
        inner:
            - Valid:
                groups: [Inner, Complex]

App\Model\Inner:
    constraints:
        - App\Validator\Constraints\Complex:
            groups: [Complex]
```

I want to validate the ```Outer``` model, which has some more properties, ```inner``` is just an example. The ```Inner``` model also has some more properties with simple validation constraints **and ```Complex``` should only get executed if none of the other constraints were failing!**

**Call:**
```php
$validator->validate($outer, null, new GroupSequence(['Inner', 'Complex']);
```

**Result**: The ```Complex``` validation for the ```Valid``` constraint is skipped.

The bug is in ```RecursiveContextualValidator``` in method ```validateInGroup``` which will check for ```$context->isConstraintValidated($cacheKey, spl_object_hash($constraint))``` and that is ```true``` for the second group ```Complex```.

**Solution (more or less a workaround):**

validation.yaml:
```twig
App\Model\Outer:
    properties:
        inner:
            - Valid:
                groups: [Inner]
            - Valid:
                groups: [Complex]
```

This is working, because both Valid constraints will have a different hash.

**Comment by xabbuh** [comment]
This is related to #17675 (i.e. both issues are caused by the same cache check in the `RecursiveContextualValidator`).

**Comment by xabbuh** [comment]
@DonCallisto Can you confirm that #29499 fixes this issue too?

**Comment by DonCallisto** [comment]
I suppose this is not a valid issue.
Months later, looking at the code, I'm pretty sure that calling that validator with `Bar` and not with `Default` produce the "right" behavior as `GroupSequence` now refers to `Default` (is clearly stated [here](https://symfony.com/doc/current/validation/sequence_provider.html).
WDYT?

**Comment by xabbuh** [comment]
I think I don't follow here. Can you explain a bit more what you mean?

**Comment by DonCallisto** [comment]
@xabbuh Take a look at the code provided. I mean: my expectations were wrong since the moment I've open this issue.
The example is very autoesplicative and there are also some comments that explain what I would have expected.
If something is not understendable for you, let me know.

**Comment by xabbuh** [comment]
So there is no bug and we can close here?

**Comment by DonCallisto** [comment]
I suppose that we can close

**Comment by xabbuh** [comment]
Thanks for the confirmation.
