### ISSUE TITLE
[DX][Console] With many commands, registration warnings are not visible

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#26203]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

## Steps to reproduce

1. create a command e.g. `system:clear-logs`
2. forget to call `parent::__construct();`
3. run `bin/console`
4. command is not listed in the available commands
5. no warning is **visible** (but it is reported correctly, read on)

Output:
![image](https://user-images.githubusercontent.com/353372/36340572-8c1f5224-13e0-11e8-8ff9-91714a0fe831.png)

The warning is printed correctly, but is like two screens of scrolling above. And it looked more like a Command registration issue, so there was no reason to scroll up. I discovered it by accident, after checking the DI configuration, trying manually tagging the command etc.

![image](https://user-images.githubusercontent.com/353372/36340579-aca85edc-13e0-11e8-8d01-61a1c45a3540.png)

**Idea 1:** Move the command registration warnings bellow the command output. (At least for the "default" command)

**Idea 2:** Change the warning to exception. I think it is kind of similar to missing scalar constructor parameter, which throws an exception.

What do you think?

**Comment by chalasr** [comment]
The idea is to not prevent running other commands when only some of them could not be registered, so throwing would be doing one step back.
👍 for displaying registration errors after running the command.

**Comment by nicolas-grekas** [comment]
I'm not sure this would be better actually. The command being run is more important than the others at this time.

**Comment by mhujer** [comment]
I agree that when a specific command is ran, the warning does not matter that much, so it should not mess with the output of the command.

**What about this:**
- when a specific command is ran, display the warning before the command output _(current behaviour)_
- when a default - list - command is ran, display the warning after the list of commands, as it tends to be longer than a screen _(change)_

**Comment by Simperfit** [comment]
👍.
@mhujer do you want to work on it ?

**Comment by mhujer** [comment]
@Simperfit I probably won't get around this until next week, so if you want to fix it, you are welcome 😃

**Comment by Simperfit** [comment]
Yeah, I'm going to do it ;)
