### ISSUE TITLE
Redirect URLs with a Trailing Slash option

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26207]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

On a classic Symfony setup, if we have a route with `/en/blog` url, we will get a 404 error if we try `/en/blog/`.

The documentation well explains how to handle that: https://symfony.com/doc/current/routing/redirect_trailing_slash.html

But I think it's a very common issue.

Why not proposing this as an option (IMHO, it should be activated by default) instead of telling the user to always write the same code? Reuse code is better than rewriting it. :+1: 

Of course, we may create a bundle instead. But I think this feature has his place on the internal Symfony codebase.

**Comment by Soullivaneuh** [comment]
This doc PR should taken in account too: https://github.com/symfony/symfony-docs/pull/9286

**Comment by Tobion** [comment]
See https://github.com/symfony/symfony/pull/26059#issuecomment-365071281

**Comment by Simperfit** [comment]
@Tobion so can we agree on doing this in symfony ? 
@Soullivaneuh if its validated, do you want to do it ?

**Comment by Tobion** [comment]
yes I'm in favor of doing it

**Comment by nicolas-grekas** [comment]
See #26283
