### ISSUE TITLE
Color support detection warning with PHP 7.2 on Windows

### ISSUE THREAD

**Issue by adawolfa** [symfony/symfony#26210]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | dev

[Color support detection](https://github.com/symfony/console/commit/1fd1c91539b8ea33292708981db1273f14475a70) emits a following warning when an unexpected type of stream (like `php://memory`) is passed to the method.

~~~
E_WARNING: sapi_windows_vt100_support() was not able to analyze the specified stream
~~~

I think that we can simply use a stfu operator for that case, since the native function [returns false](https://github.com/php/php-src/blob/4752f8a8ed906ca2be93b0bae5617c2f76a2a8ac/ext/standard/streamsfuncs.c#L1696) when this warning gets emitted, so the detection simply falls back to former behavior.

Also note, that polyfill for PHP < 7.2 does not reproduce this behavior.

**Comment by nicolas-grekas** [comment]
Hi, thanks for the report. PR welcome, against branch 2.7.
The polyfill also should be fixed (ping @johnstevenson FYI)
