### ISSUE TITLE
[MonologBridge] Inconsistent colors between ConsoleFormatter and ConsoleLogger

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#26217]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

[ConsoleLogger uses info/error color tags](https://github.com/symfony/symfony/blob/aaf2265203cfbefa006f0358077d8ade790ad203/src/Symfony/Component/Console/Logger/ConsoleLogger.php#L43), which results in green/white colors.

However, [ConsoleFormatter uses fg= tags](https://github.com/symfony/symfony/blob/a522e04255f5055fe41338f752101305d020a986/src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php#L33) which results in different colors. For example, debug messages are shown in ConsoleLogger green, but in ConsoleFormatter white.

I expected ConsoleFormatter will just extend possibilities of ConsoleLogger, not change default colors.

**Comment by ostrolucky** [comment]
This got no response. Is fix welcome here?

**Comment by Simperfit** [comment]
I think it should be fixed.

**Comment by ostrolucky** [comment]
I appreciate your response. Gonna implement this

**Comment by ostrolucky** [comment]
Closing, because this can't do without deprecation. And deprecation for such trivial thing isn't likely to be approved.

To be more specific, same key-value map is used for determining colors and for determining if it should be written to error output.
