### ISSUE TITLE
Improve profiler navigation for non-GET requests

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#26226]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

In general my app does mostly GET requests, meaning i'm very used to navigate back to my app from the profiler using the clickable title:

![image](https://user-images.githubusercontent.com/1047696/36376530-af30c2c2-1573-11e8-961e-68dd3da0e182.png)

When doing a POST request this is not possible anymore, and it's annoying because im used to it :sweat_smile: at this point i find myself always scanning the page for anything that links back to my app. But you can't and so you're stuck :) i now need to use browser navigation (which im not getting used to).

Can we improve this UX somehow... a 'replay as GET' link would do it IMHO.

**Comment by derrabus** [comment]
Maybe we could add a link to the referrer URL (if there is one)?

**Comment by ro0NL** [comment]
Yes, that sounds reasonable.

First proposal:

![image](https://user-images.githubusercontent.com/1047696/36378953-1b49d116-157d-11e8-8562-455d0b823678.png)
