### ISSUE TITLE
PR #25583 and #25699  BC Break

### ISSUE THREAD

**Issue by smurfy** [symfony/symfony#26237]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| Symfony version  | 3.4.3+

PR #25583 and #25699 overwrites cache-control even if i manually set them to public. This breaks compatibility.  version 3.4.2 works.

I use varnish to cache and have several actions with explicit ``@Cache`` annotation to cache them by varnish, regardless if the user is logged in or not. This worked since 2.7 and till 3.4.2. 

With the PR #25583 this broke, but was relatively easy to fix by overwriting the savesession listener.
With #25699 the change got moved to the abstract class which makes it even harder to overwrite.
Probably by modifying the session object but still, in my opinion its a BC Break.

**Comment by nicolas-grekas** [comment]
Hello, than you for your report.
This has been discussed previously in eg #25736: his is not a BC break, but a bug fix.
I invite you to review this discussion, it should give you the reasoning, and a way to force your logic, if you really want to.

**Comment by smurfy** [comment]
@nicolas-grekas  thanks for the info, i still see it somewhat as BC break, because it worked and then it broke :)

But i fixed it for myself by defining all urls which need the user object in my security.yml so the cache-control will be only changed for these urls, which is fine and wanted.

**Comment by nicolas-grekas** [comment]
OK, all good then. Any bug fix is a BC break :)
