### ISSUE TITLE
Add string normalization option(s) to string-based validators

### ISSUE THREAD

**Issue by Destroy666x** [symfony/symfony#26239]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

As the title says, it would be nice to see trimming and consecutive whitespace merging either as:
- a single `normalize` option
- two `trim` and `mergeConsecutiveWhitespaces` options

in `LengthValidator` at least, maybe also `NotBlank` if the checked value is a string

Why? Data should be normalized in general, but there are cases where you'd like to store formatted text with enough useful content, for instance forum posts.

I could do a PR, if you like the suggestion let me know which branch would be the most appropriate since it's a small feature, I guess still 4.1.x?

**Comment by Simperfit** [comment]
@Destroy666x Hi, thanks for contributing to symfony!
I think you can do a PR against master since this is a new feature, thanks!
