### ISSUE TITLE
Security Provider Configuration Does not accept child elements when registering a provider

### ISSUE THREAD

**Issue by jtangas** [symfony/symfony#26248]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.4

When attempting to register a provider in the security bundle, I am greeted with the following error when trying to execute anything within the symfony stack:

```
$ bin/console -vvv

In ArrayNode.php line 319:
                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "entity" under "security.providers.my_entity_provider"     
                                                                                 
```

I have consulted the docs and do see in the MainConfiguration.php Line 316, that the providers element is a prototype array and using attribute as key.

**My Configuration**
```
security:
    encoders:
        NameSpace\To\Entity\User:
            algorithm: bcrypt

    providers:
        my_entity_provider:
            entity:
                class: NameSpace\To\Entity\User
                property: email
```

**Expected Outcome**
No error, since provider configuration is correctly formatted/configured

**Comment by jtangas** [comment]
I have determined that this is not an issue, but it is a bug in the documentation.

The documentation states that the nested format that I passed above is an acceptable form, however, the form that is being required is the following:
```
        my_entity_provider: { entity: { class: NameSpace\To\Entity\User, property: email } }
```

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by jtangas** [comment]
I am actually going to close this issue out. After doing some more digging, I realized that when I initially installed the security bundle, it was not installed using `composer req security` instead it was installed with the LexikJWT package, this did not fully implement all the necessary classes. Resolved the issue by making sure to run `composer req security` and `composer require doctrine/doctrine-bundle`

**Comment by xabbuh** [comment]
Not sure what the JWT is doing there exactly, but this looks more like an issue in that package then.
