### ISSUE TITLE
Cache does not preserve expiration time

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#26241]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

```php
public function foo(CacheItemPoolInterface $pool)
{
    $item = $pool->getItem('key');

    if (!$item->isHit()) {
        $item->expiresAfter(5);
    }

    dump($item->get());

    $item->set($item->get() + 1);
    $pool->save($item);
}
```

When cache item is created, I set expiration time. In example above, I expect dump will return null after 5 seconds since first call, no matter how many times I call it during those 5 seconds.

What's wrong is that if you call the example code during those 5 seconds, Symfony replaces original expiration time with indefinite one, so after second call item is never erased.

I would expect to update only value of the item and preserve expiration time, since I didn't change it.

Tested with FileSystem adapter.

**Comment by nicolas-grekas** [comment]
Correct, that's consistent with PSR-6, expiration must be set each time you save an item.

**Comment by xabbuh** [comment]
Closing then as there is nothing wrong going.

@ostrolucky Feel free to open a documentation issue if you think we could make this more clear in the docs.
