### ISSUE TITLE
Cannot create doctrine entity

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#26258]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I try to create doctrine entity by guide:
`C:\Users\RSalo\PhpstormProjects\symfony-test-project>D:\program\OpenServer5.2.8\OSPanel\modules\php\PHP-7.1-x64\php.exe bin/console make:entity Product
`
but error appears:
```
In Filesystem.php line 106:

  Failed to create "C:\Users\RSalo\PhpstormProjects\symfony-test-project//C:\Users\RSalo\PhpstormProjects\symfony-test-project\vendor\composer/../../src/Entity"


make:entity [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<entity-class>]
```

**Comment by Simperfit** [comment]
Could you please directly create the issue in the maker-bundle repository ?

This is not linked to symfony.

**Comment by RSalo** [comment]
Fixed.
