### ISSUE TITLE
Document `container.dumper.inline_class_loader` parameter

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#26269]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4/4.0

Parameter `container.dumper.inline_class_loader` should be documented. See https://twitter.com/nicolasgrekas/status/929032213815005184.

**Comment by nicolas-grekas** [comment]
Note that the param is enabled by default for new project that use either Flex or the Std edition.
I think the UPGRADE*.md files are a good fit.
Would you mind sending a PR against branch 3.4?

**Comment by phansys** [comment]
Sure, I'll try to create a PR today.
