### ISSUE TITLE
WebProfiler JS error when updating request in kernel.event_controller

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony#26268]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Hi,

For some reasons, i use the onKernelController method to initiate some stuff, but when i want to alterate the request (updating one parameter), i got a JS error in my console and the debug toolbar doesn't appear : 

```
Uncaught TypeError: Cannot read property 'nodeValue' of null
    at Sfjs.load.maxTries (login:867)
    at login:867
    at XMLHttpRequest.xhr.onreadystatechange (login:867)
```

This is my code : 

```
public function onKernelController(FilterControllerEvent $event) {
    if(null === $user) {
        // These 2 lines provide the JS error !
	$event->getRequest()->attributes->set('_controller', 'App\CommonBundle\Controller\SecurityController::login');
	$event->getRequest()->attributes->set('_route', '/login');
                        
        // If this is alone, i have no error
	$event->setController($this->resolver->getController($event->getRequest()));
	}
}
```

Thanks for your help !

**Comment by stof** [comment]
AFAIK, this JS error is a bug on the TwigBundle exception page (clashing with the profiler JS code), which is fixed in the dev version of Symfony (will be part of the 3.4.5 and 4.0.5 releases at the end of the month).

But anyway, if this is the cause of the JS error, the change is your own code is not triggering the JS error itself. It triggers an exception in your PHP code (so you have a problem) and the page displaying details about the exception has this JS error. But you still need to fix your code to avoid triggering an exception.

**Comment by QuentinCurtet** [comment]
Ok

Thanks for your answer, i will search where the problem comes from but without any idea where this come from, it's not easy ^^

**Comment by QuentinCurtet** [comment]
@stof In order to debug, i tried to install symfony 4.0.x-dev but it uninstall me all the symfony dependencies and uncofigure my project.
![image](https://user-images.githubusercontent.com/6769513/36585532-86a00d5a-187e-11e8-96d5-d14caced72be.png)

**Comment by xabbuh** [comment]
@QuentinCurtet You can instead just update some of the components to `4.0.x-dev`. In your case that should probably be `symfony/web-profiler-bundle`.

**Comment by QuentinCurtet** [comment]
@xabbuh Thanks for your help, but unfortunately, this doesn't change anything...

**Comment by QuentinCurtet** [comment]
This is my composer.json if it can help : 
```
{
	"type": "project",
	"license": "proprietary",
	"require": {
		"php": "^7.1.3",
		"ext-iconv": "*",
		"almasaeed2010/adminlte": "2.4.3",
		"doctrine/dbal": "^2.6",
		"doctrine/doctrine-bundle": "^1.8",
		"knplabs/knp-menu-bundle": "^2.2",
		"sensio/framework-extra-bundle": "^5.1",
		"symfony/asset": "^4.0",
		"symfony/console": "^4.0",
		"symfony/flex": "^1.0",
		"symfony/framework-bundle": "^4.0",
		"symfony/http-foundation": "^4.0",
		"symfony/lts": "^4@dev",
		"symfony/security-bundle": "^4.0",
		"symfony/web-profiler-bundle": "4.0.x-dev",
		"symfony/yaml": "^4.0"
	},
	"require-dev": {
		"symfony/dom-crawler": "^4.0",
		"symfony/debug-pack": "^1.0",
		"symfony/dotenv": "^4.0"
	},
	"config": {
		"preferred-install": {
			"*": "dist"
		},
		"sort-packages": true
	},
	"autoload": {
		"psr-4": {
			"App\\": "src/",
		},
	},
	"autoload-dev": {
		"psr-4": {
			"App\\Tests\\": "tests/"
		}
	},
	"replace": {
		"symfony/polyfill-iconv": "*",
		"symfony/polyfill-php71": "*",
		"symfony/polyfill-php70": "*",
		"symfony/polyfill-php56": "*"
	},
	"scripts": {
		"auto-scripts": {
			"cache:clear": "symfony-cmd",
			"assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
		},
		"post-install-cmd": [
			"@auto-scripts"
		],
		"post-update-cmd": [
			"@auto-scripts"
		]
	},
	"conflict": {
		"symfony/symfony": "*"
	},
	"extra": {
		"symfony": {
			"id": "MY ID",
			"allow-contrib": false
		}
	}
}

```

**Comment by Simperfit** [comment]
Could you use `4@dev` ? Does it says something about the minimum-stability ?

**Comment by Simperfit** [comment]
If you can share the project we may help you faster.

**Comment by QuentinCurtet** [comment]
@Simperfit The project is not versionned on Git ^^

Using 4@dev load the 4.0.0 version, but it's uder my current version.

**Comment by QuentinCurtet** [comment]
@stof @Simperfit @xabbuh I think this is related to the update of existing parameters (_controller, _route, _route_params, _firewall_context) in the request.
Because when i add a non existent parameter and update it, this works fine, but if i override an existing parameter  (_controller, _route, _route_params, _firewall_context), i get the nodeValue error.

**Comment by xabbuh** [comment]
Having some example that allows to reproduce the issue would still help. :)

**Comment by QuentinCurtet** [comment]
I can't post it on Github, i will try to explain it here : 
I have one basic controller, let's name it DefaultController : 
```
class DefaultController extends Controller {
	/**
	 * @return Response
	 */
	public function index() {
		$paramArray = [
			'session'	=> $_SESSION
		];

                // This template just contain a dump of session
		return $this->render('Default/index.html.twig', $paramArray);
	}
}
```
For some reasons, i create a listener : 
```
    App.Bundle.Listener.Controller:
        class: App\MyBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
```

In this listener : 
```
public function onKernelController(FilterControllerEvent $event) {
	$event->getRequest()->attributes->set('_controller', 'App\Bundle\Controller\DefaultController::index');
	$event->setController($this->resolver->getController($event->getRequest()));
}
```
When i update the _NAME parameter (where name could be controller, route, route_params or firewall_context), i got the JS error

**Comment by QuentinCurtet** [comment]
@xabbuh any updates ?

**Comment by stof** [comment]
Please stop caring about the JS error (this is an issue in the exception page of Symfony, which is already fixed in the dev version) and instead look at the PHP error you get (in the **content** of the exception page)

@QuentinCurtet use `^4@dev`, not `4@dev` (so just add `@dev` at the end of your existing constraint, or change `minimum-stability` to `dev`). The `4` constraint allows only 4.0.0.

**Comment by QuentinCurtet** [comment]
@stof I can't find the PHP error, but you were right, the JS is not display  because of the subrequest that i do when i update the _controller parameter of the request.

**Comment by QuentinCurtet** [comment]
Yes we can close this, the error was from a part of my code not a Symfony one.

**Comment by PhilETaylor** [comment]
> the error was from a part of my code not a Symfony one.

I was able to replicate this today.

If anyone is interested, the issue for me was that I was hijacking the request, and redirecting if the user did not meet my criteria... 

however I was also redirecting away _wdt and _profiler and _profiler* routes, and this is what causes the JS issue reported in this issue.

To replicate, create a symfony 4 project, with a Kernel Listener which redirects everything to a certain route, in dev mode with debug enabled = JS error when loading the page.

**Comment by PhilETaylor** [comment]
> Please stop caring about the JS error (this is an issue in the exception page of Symfony, which is already fixed in the dev version) 

No I dont believe it is :) as Im 

PHP Version: 7.3.4
Symfony Version: 4.2.7

> If so, can you provide a small reproducer?

From the office tomorrow :)

**Comment by mkopinsky** [comment]
I came across this as well. The underlying issue was that my security.yaml was mis-ordered with the main firewall above the dev firewall, so anonymous requests to /_wdt/xxxx were getting 302'ed to /login, causing the dev tools to error with:
```
login:95 Uncaught TypeError: Cannot read property 'nodeValue' of null
    at load.maxTries (login:95)
    at login:95
    at XMLHttpRequest.xhr.onreadystatechange (login:95)
```

The offending part of the code was 
```
for (i = 0; i < scripts.length; ++i) {
    eval.call({}, scripts[i].firstChild.nodeValue);
}
```

The fix as I mentioned was to move the dev firewall up in security.yaml, but I'd argue that the dev tool should have a slightly more graceful handling of the error. Hope this helps either symfony users or maintainers. 😄

**Comment by PhilETaylor** [comment]
The "bug" is that you MUST allow the _wdt and _profiler and _profiler* routes access in DEV.

If you firewall those routes, or block with other ACL or logic, and you stop these routes from loading , then you will get this Javascript issue.

**The simple fix is to rewrite your app correctly, to allow these routes unhindered progress while in the dev environment** (unless you have a good reason and know why you want to block these development routes in dev mode), this could be to reorder the firewalls or write logic in your app/code/event listener (the latter being the root of my issue initially).

**Comment by Fadhel1416** [comment]
the probleme is that the option only_exception in profiler doest not set to true  ,so to fix that go to config/package/web-profiler and set the value of only_exception to true it look like this
profiler:
{only_exception:true}

**Comment by michondr** [comment]
> the probleme is that the option only_exception in profiler doest not set to true ,so to fix that go to config/package/web-profiler and set the value of only_exception to true it look like this
> profiler:
> {only_exception:true}

that will disable the profiler on the whole app, unless exceptionis thrown :/
