### ISSUE TITLE
$this can not be used in static methods.

### ISSUE THREAD

**Issue by OliverLeitner** [symfony/symfony#26279]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | current master

file: symfony/console/Tests/Command.php

```
    private static function createClosure()
    {
        return function (InputInterface $input, OutputInterface $output) {
            $output->writeln(isset($this) ? 'bound' : 'not bound');
        };
    }
```

Causes linter error in visual studio code:

```
file: 'file:///.../symfony/console/Tests/Command/CommandTest.php'
severity: 'Error'
message: '$this can not be used in static methods.'
at: '401,36'
source: 'php'
code: 'undefined'
```

and yes... one could disable the linter...

anyways... i am sure youre already aware of this and a good solid fix is already on the way, just wanted to check in and say hi;-)

**Comment by prisis** [comment]
Hey :), you need to use self:: instead of $this-> for static methods.

For more infos http://www.brainbell.com/tutorials/php/Static_Methods.html

**Comment by xabbuh** [comment]
`$this` is not used by the static method, but it is part of the closure for which `Closure::bind()` makes sure that the context is set (see #20847).
