### ISSUE TITLE
[DomCrawler] Create an optimized parsing crawler

### ISSUE THREAD

**Issue by babaorum** [symfony/symfony#26294]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | latest

Hi.
The way the Crawler has been implemented seems way to heavy for what we want in most cases.

Correct me if I am wrong, but I think there are 2 ways of using the crawler.
* Simply parsing a document to retrieve information
* Parsing and editing a document

*(I do not know if we can use it to create a blank document and construct a whole structure not for parsing it after).*

My point being, when only parsing a document, we use the `\DomDocument` / `\DomElement` native functionality. The problem is that PHP is creating a heavy tree structure, that might be a bit much for what we are trying to accomplish.

To give a use case: I tried to parse an XML which contained 3000 similar elements.
My content was contained in a string. When I gave it to the Crawler, it created the whole tree structure which took some time.
Then I needed to loop on each of those elements to gather the desired information.
 
Even if I am not a big XML fan. I think it is still quite used in the way I just described.

For simply parsing data, I think not creating these `\DomDocument` / `\DomElement` when not provided will spare some time. The filtering could be done by regex to avoid the need to create them.
Of course, this can only apply to parsing data only.

I would love some feedback on this. Maybe I am not seeing the whole picture.

**Comment by Aerendir** [comment]
You are missing xPath... a DomDocument is required to use it...

**Comment by babaorum** [comment]
Yes, XPath would not be usable on a string directly. I am not an expert in XPath, but maybe we could translate it into a regular expression. My point being: does creating a `DomDocument` from a string to use XPath really worth it?

**Comment by stof** [comment]
You cannot transform any XPath into a regex matching the XML source IMO (even doing it for a single hardcoded XPath query might already be very hard).

Providing the same feature set with the same API without parsing the DOM would probably not work. If you just want to extract some info using a regex, you could just avoid using the DomCrawler component, and use another tool instead.

> Parsing and editing a document

that's not true. The DomCrawler component does not allow editing a document.

**Comment by Aerendir** [comment]
@babaorum yes. If you need something simpler, you may use something simpler, but simply something already complete is not a good approach: it is an involution.

**Comment by babaorum** [comment]
ok, thank the two of you for answering me so quickly. I might not see all the advantages of XPath and DOMCrawler.

I close the issue.
