### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by babatec** [symfony/symfony#26291]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1
Why am I getting that error in `symfony/src/Symfony/Component/Form/Form.php`

**Comment by theofidry** [comment]
You are getting this error because you are using a version which is no longer supported since end of July 2017 and PHP added this warning to PHP 7.2. So you'd better to upgrade to at least 3.4 (there is no BC break up to that point) :)

**Comment by xabbuh** [comment]
Without more information how you run into this issue we won't be able to help you. Also note that Symfony 3.1 is not maintained for a long time and you should rather update to Symfony 3.4 and check if the issue persists.

**Comment by fabpot** [comment]
Closing as 3.1 is not maintained anymore.

**Comment by anatol06** [comment]
I had the same issue. Updating Symfony from 3.0 to 3.4 is a solution. Thanks!
