### ISSUE TITLE
[Documentation] Improve documentation: add an explanation how to run Symfony server together with Webpack dev server

### ISSUE THREAD

**Issue by wujekbogdan** [symfony/symfony#26301]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.x

Hey,

I'm new to Symfony. I've just installed the `symfony/website-skeleton` template with Flex and the first thing I wanted to add to the project was a build process for CSS/JS. I'm more a front-end dev than a backend programmer, I'm familiar with Grunt/Gulp/Webpack/Fusebox, etc so I could add any of these tools on my own, but I found that there's a tool like Encore so I decided to give it a try.

Thanks to docs I didn't have any problem with setting it up, but I found one detail that is missing in docs that might be very confusing for newcomers or for people who are not so familiar with modern front-end build tools.

For me, it was quite obvious that Webpack dev server serves compiled assets over HTTP and a Symfony application is able to point to these assets thanks to the manifest.json file and the `Assets` component. It was also obvious that I have to run the Symfony web server and the Webpack dev server separately (in 2 separate console windows, or with `php bin/console server:start && yarn run dev-server`). But the documentation is not very clear about it.

IMO it should be explicitly said that these are 2 separate tools. One might think that Encore is something that integrates with Symfony and running Symfony's web server would execute Webpack devs server under the hood. I know that it doesn't make much sense... but on the other beginner's guides should rather be explicit than making assumptions.

So IMO this part of the documentation needs some improvements... or maybe you could implement a feature like `bin/console server:startWithDevServer` command that would start the Symfony's server in a background mode + Webpack dev server?

**Comment by Simperfit** [comment]
I guess this has more it's place in https://github.com/symfony/symfony-docs for the documentation issue part.

for the feature request, I think we could have a bundle that does that, but I don't think it should in the framework since Symfony Encore is another tool that helps using webpack with symfony but maybe @weaverryan has an idea ?

**Comment by wujekbogdan** [comment]
@Simperfit 

> I guess this has more it's place in https://github.com/symfony/symfony-docs for the documentation issue part.

I'm sorry. I didn't know that there's a separate repo for docs. Already posted the same message there: https://github.com/symfony/symfony-docs/issues/9331

> for the feature request, I think we could have a bundle that does that, but I don't think it should in the framework since Symfony Encore is another tool that helps using webpack with symfony but maybe 

Good point. Adding such feature would make Symfony coupled with Encore, which is indeed a separate, standalone tool. 

---

But on the other hand maybe additional bin/console parameters could be added on the setup stage when the `composer create-project` is run? I'm not sure is it possible with composer installer to add prompts during install. But it would be great if a user could pre-configure the Symfony project on the installation stage - this is how CLI tools for some modern JS frameworks work. For example the Vue.js CLI tool asks a series of questions, then depending on user's answers the final webpack configuration is created. 

Such flexibility would make Symfony website-skeleton even more modular.... or maybe even you wouldn't need skeleton and website-skeleton. There could be one, configurable skeleton. 

PS
Sorry for such a big offtopic, but It just came to my mind when writing the response.

**Comment by Simperfit** [comment]
@wujekbogdan I think it's OK to open an RFC/question about something that could improve the DX when using front tools and symfony, I guess when Ryan will have some time we could see how we can improve it and if it could be directly in the framework or out of it ;).
