### ISSUE TITLE
[2.2] [Translation] Po/Mo file readers do not parse plurization rules

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#2630]
I've been experimenting with the new PO/MO file readers that @stealth35 added recently.  There is one very unfortunate thing missing from this however, is that they don't parse the plurization rules.  In Gettext, these are part of the header so the framework doesn't need to know hard coded values as is required in Symfony2.  In order for these readers to be useful, they really need to parse this information.  It will require an extra property in the `MessageCatalog` class I guess.

**Comment by jiru** [comment]
If that’s any interest to you, I implemented a Gettext pluralization rules parser as part of a PR to CakePHP: cakephp/cakephp#5348. They ended up keeping hardcoded rules though. You can reuse my code freely if you want.

**Comment by javiereguiluz** [comment]
@aitboudad do you think that this feature is needed and doable without complicating code much? Or do you think we could close it as "won't fix"? Thanks.

**Comment by aitboudad** [comment]
@javiereguiluz   Well I think this require many changes, the way we handle pluralization is a bit different than this one which need to define the pluralization rules per files so I'm ok to mark it as `wont fix`

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" as per @aitboudad's comments. Thanks.
