### ISSUE TITLE
Compile error in 3.4 by using handler lowercase name in config.yml

### ISSUE THREAD

**Issue by Laurent3170** [symfony/symfony#26306]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | No
| BC Break report? | No
| RFC?             | No
| Symfony version  | 3.4

I don’t know if it’s really a bug, but as stated in https://stackoverflow.com/q/48909964/6028808, when a handler for the logout is specified using a lowercase for second part of the name, i.e. Logoutlistener, symfony tries to find an unexisting file named with a 2.

I saw, after having found the solution, that declaring with lowercase is deprecated in 3.4.x and throws an error in 4.

The purpose of this issue is to, maybe, improve the error message, the error was on my side, as I had the typo in my code but was hard to find.
Furthermore, as it is deprecated but still in use in 3.4, I think it should « compile » without error, except the deprecate warning, so I think the error is not attended, that’s why I submit it as a bug, but feel free to close, if you don’t think it is.

**Comment by nicolas-grekas** [comment]
Would you mind creating a small project that reproduces the issue?

**Comment by Laurent3170** [comment]
Yes no problem, but what do you mean by « creating a small project »? That I write here the code to reproduce or something else?

**Comment by nicolas-grekas** [comment]
Yes, or better, provider a repository on github we could clone and that would allow us to easilly reproduce the issue. There is some doc about that here, might help also:
https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by Laurent3170** [comment]
Ok I’ll do a github repository, but only tomorrow. Thanks for the doc, I didn’t know about it.

**Comment by Laurent3170** [comment]
@nicolas-grekas I've created the repository https://github.com/Laurent3170/SymfonyIssue26306, you should be able to reproduce the bug by uncomment in `security.yml` the `handlers` value
```
#handlers: [c975L\UserBundle\Listeners\Logoutlistener] #listener with a lowercase l -> bugs
handlers: [c975L\UserBundle\Listeners\LogoutListener] #Listener with an uppercase L -> works 
```
If not let me know

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer, see fix in #26355

**Comment by Laurent3170** [comment]
Wow! Great!
What should I do with my repository? Can I delete it or should I keep it?

**Comment by nicolas-grekas** [comment]
You can delete it :)
