### ISSUE TITLE
Random compat 1.x security advisories

### ISSUE THREAD

**Issue by cmodijk** [symfony/symfony#26315]
| Q                | A
| ---------------- | -----
| Bug report?      | yes and no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.41

At the moment Symfony 2.7 uses `paragonie/random_compat` at version `~1.0` but the security advisories advies to update to `~2.0` is there a way to upgrade this in Symfony 2.7 to the `~2.0` version? 
* https://github.com/paragonie/random_compat/issues/96
* https://github.com/symfony/symfony/blob/2.7/composer.json#L22

**Comment by nicolas-grekas** [comment]
You should upgrade to 2.8, which removes this restriction restrict

**Comment by cmodijk** [comment]
@nicolas-grekas Thanks for the quick response! This change wil not land in the 2.7 LTS version?

**Comment by nicolas-grekas** [comment]
That might break existing setup, that rely on openssl (ie on v1): imagine they upgrade and v2 is installed.

**Comment by xabbuh** [comment]
Was there a special reason we did never allow version 2 too (as an addition not as a replacement)?

**Comment by nicolas-grekas** [comment]
@xabbuh the one I just gave yes

**Comment by cmodijk** [comment]
@nicolas-grekas Thanks for the quick response / support i wil try to upgrade the project.
