### ISSUE TITLE
[Routing] Regexp pattern matching - unintuitive behaviour 

### ISSUE THREAD

**Issue by mimol91** [symfony/symfony#26311]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

I've defined route as bellow
```php
use Symfony\Component\Routing\Matcher\UrlMatcher;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Routing\Route;

$coll = new RouteCollection();
$coll->add('foo', new Route('/foo/{page}/bar', [], ['page' => '^(?!123$)[\d]+']));

$matcher = new UrlMatcher($coll, new RequestContext());
$result =  $matcher->match('/foo/123/bar');
```

There is requirement for {page} parameter - which should be any digit, but not exactly `123`
The _$result_ is an array with matched route (foo). - I think it is not expected, because '123' does not match to pattern (at least according to https://regex101.com/r/s07hLC/1)

If I define route as 
```php
$coll->add('foo', new Route('/foo/{page}', [], ['page' => '^(?!123$)[\d]+']));

$matcher = new UrlMatcher($coll, new RequestContext());
$result =  $matcher->match('/foo/123');
```
Everything back to normal (Symfony\Component\Routing\Exception\ResourceNotFoundException)

Is it really an bug? Or there is a way to define such an pattern?

**Comment by nicolas-grekas** [comment]
here is how you need to think about the requirement: it is just inserted at the placeholders position;
this means you needs a regex that would do what you want when matching against.
Eg. here, what you wrote is interpreted as: `#^/foo/(^(?!123$)[\d]+)/bar*#sD`.

**Comment by nicolas-grekas** [comment]
I'm closing because there is no bug description here, so nothing to track.
