### ISSUE TITLE
Cache key "email@address" contains reserved characters {}()/\@:

### ISSUE THREAD

**Issue by dadepl** [symfony/symfony#26313]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

Hi,

I have problem when submitting user form. I use FOSUserBundle and there's simple form with only two fields:
`->add('name', TextType::class, [
'label' => 'name and surname',
])`
`->add('department', TextType::class, [
'label' => 'department',
])`

It's also standard in controller:
`$editForm = $this->createForm('Company\AdminBundle\Form\UserEditType', $user);`
`$editForm->handleRequest($request);`

When I submit form **in production** env I get error in prod.log:
`[2018-02-26 08:50:35] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Cache key "email@address" contains reserved characters {}()/\@:" at /Users/local/Sites/projectname/vendor/symfony/cache/CacheItem.php line 162 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Cache key \"email@address\" contains reserved characters {}()/\\@: at /Users/local/Sites/projectname/vendor/symfony/cache/CacheItem.php:162)"} []`

As far as I can check, the problem occurs on `handleRequest($request)` in controller and later on Symfony `Form` class when dispatches `POST_SUBMIT`
`$dispatcher->dispatch(FormEvents::POST_SUBMIT, $event);`
and then in `ValidationListener` class when running
`$violations = $this->validator->validate($form);`

I do not use any custom cache bundles / vendors and it's first time I have such problem. Just don't know why. I understand error itself, that there's problem with "`@`" character in cache and with PSR-6, but have no idea what to check or change.

Thank you for help.

**Comment by nicolas-grekas** [comment]
can you dump the full stack trace of that exception please?

**Comment by dadepl** [comment]
`[2018-02-26 09:16:01] request.INFO: Matched route "admin_user_edit". {"route":"admin_user_edit","route_parameters":{"_controller":"Company\\AdminBundle\\Controller\\UserController::editAction","id":"1","_route":"admin_user_edit"},"request_uri":"http://projectname.test/admin/user/1/edit","method":"POST"} []`
`[2018-02-26 09:16:01] security.DEBUG: Read existing security token from the session. {"key":"_security_admin","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []`
`[2018-02-26 09:16:01] security.DEBUG: User was reloaded from a user provider. {"provider":"FOS\\UserBundle\\Security\\EmailUserProvider","username":"dade"} []`
`[2018-02-26 09:16:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Cache key "email@address" contains reserved characters {}()/\@:" at /Users/local/Sites/projectname/vendor/symfony/cache/CacheItem.php line 162 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Cache key \"email@address\" contains reserved characters {}()/\\@: at /Users/local/Sites/projectname/vendor/symfony/cache/CacheItem.php:162)"} []`
`[2018-02-26 09:16:01] security.DEBUG: Stored the security token in the session. {"key":"_security_admin"} []`

**Comment by nicolas-grekas** [comment]
We'd need to know where the invalid key is used.
To do so, we'd need to get the full stack trace, which is something you could get by eg opening `vendor/symfony/cache/CacheItem.php` and inserting `echo new \Exception();` just before the exception is thrown. (don't forget to remove the line once you copy/pasted the output)

**Comment by dadepl** [comment]
echoing new exception just before `throw new InvalidArgumentException(sprintf('Cache key "%s" contains reserved characters {}()/\@:', $key));` results in:

`Exception in /Users/local/Sites/project/vendor/symfony/cache/CacheItem.php:162 Stack trace: #0 
/Users/local/Sites/project/vendor/symfony/cache/Traits/AbstractTrait.php(232): Symfony\Component\Cache\CacheItem::validateKey('firstname.lastna...') #1 
/Users/local/Sites/project/vendor/symfony/cache/Adapter/AbstractAdapter.php(148): Symfony\Component\Cache\Adapter\AbstractAdapter->getId('firstname.lastna...') #2 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Cache/Psr6Cache.php(44): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem('firstname.lastna...') #3 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php(91): Symfony\Component\Validator\Mapping\Cache\Psr6Cache->read('firstname.lastna...') #4 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(328): Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor('firstname.lastna...') #5 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(724): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject('firstname.lastna...', 'data.email', Array, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #6 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(577): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateGenericNode('firstname.lastna...', Object(Client\AppBundle\Entity\User), '000000002c28ba2...', Object(Symfony\Component\Validator\Mapping\PropertyMetadata), 'data.email', Array, Array, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #7 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(347): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateClassNode(Object(Client\AppBundle\Entity\User), '000000002c28ba2...', Object(Symfony\Component\Validator\Mapping\ClassMetadata), 'data', Array, NULL, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #8 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(139): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject(Object(Client\AppBundle\Entity\User), 'data', Array, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #9 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php(52): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate(Object(Client\AppBundle\Entity\User), NULL, Array) #10 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(829): Symfony\Component\Form\Extension\Validator\Constraints\FormValidator->validate(Object(Symfony\Component\Form\Form), Object(Symfony\Component\Form\Extension\Validator\Constraints\Form)) #11 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(542): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateInGroup(Object(Symfony\Component\Form\Form), '000000002c28bac...', Object(Symfony\Component\Validator\Mapping\ClassMetadata), 'Default', Object(Symfony\Component\Validator\Context\ExecutionContext)) #12 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(347): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateClassNode(Object(Symfony\Component\Form\Form), '000000002c28bac...', Object(Symfony\Component\Validator\Mapping\ClassMetadata), '', Array, NULL, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #13 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(139): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject(Object(Symfony\Component\Form\Form), '', Array, 1, Object(Symfony\Component\Validator\Context\ExecutionContext)) #14 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveValidator.php(100): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate(Object(Symfony\Component\Form\Form), NULL, Array) #15 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php(55): Symfony\Component\Validator\Validator\RecursiveValidator->validate(Object(Symfony\Component\Form\Form)) #16 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\Form\Extension\Validator\EventListener\ValidationListener->validateForm(Object(Symfony\Component\Form\FormEvent), 'form.post_bind', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #17 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'form.post_bind', Object(Symfony\Component\Form\FormEvent)) #18 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php(33): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('form.post_bind', Object(Symfony\Component\Form\FormEvent)) #19 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(665): Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch('form.post_bind', Object(Symfony\Component\Form\FormEvent)) #20 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(108): Symfony\Component\Form\Form->submit(Array, true) #21 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(498): Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(Object(Symfony\Component\Form\Form), Object(Symfony\Component\HttpFoundation\Request)) #22 
/Users/local/Sites/project/src/Company/AdminBundle/Controller/UserController.php(138): Symfony\Component\Form\Form->handleRequest(Object(Symfony\Component\HttpFoundation\Request)) #23 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Client\AdminBundle\Controller\UserController->editAction(Object(Client\AppBundle\Entity\User), Object(Symfony\Component\HttpFoundation\Request)) #24 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #25 
/Users/local/Sites/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 
/Users/local/Sites/project/web/app.php(20): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #27 
{main}`

**Comment by nicolas-grekas** [comment]
Are you sure you put that echo *inside* the "if"? The trace tells about key `firstname.lastna...`, but your report is about about `email@address`. Can you get a trace with the failing key also?

**Comment by dadepl** [comment]
Yes, echo exception is within this `if`, before throwing `InvalidArgumentException`:
`if (false !== strpbrk($key, '{}()/\@:')) {`
`echo new \Exception();`
`throw new InvalidArgumentException(sprintf('Cache key "%s" contains reserved characters {}()/\@:', $key));`
`}`
Sorry for inconvenience, `firstname.lastna` is placeholder for my e-mail address that is visible in original stack trace.

**Comment by xabbuh** [comment]
For some reason, the metadata factory in the Validator component is called with an e-mail address which is then treated as a class name there. Would you be able to provide a small example application that allows to reproduce your issue?

**Comment by dadepl** [comment]
Source code or as www?

**Comment by xabbuh** [comment]
The source code :) The best is a small application that you push to GitHub.

**Comment by dadepl** [comment]
Repo, cut to minimum: https://github.com/dadepl/sfusertest
Install, create db and user account with fos:user:create and promote it to ROLE_ADMIN, go to /admin and then through link to user edit form. It gives me 500 when saving form and "reserved characters" exception in prod.log (dev env is ok).

**Comment by xabbuh** [comment]
Are you sure that you cleared the cache properly?

**Comment by dadepl** [comment]
If by "properly" you mean running `bin/console cache:clear --env=prod` then yes, I have cleared the cache for both, prod and dev environments.
I have same cache exception results when running project online on shared hosting.
If this helps somehow, I'm running Apache localhost with php 7.1 on OSX.

**Comment by dmaicher** [comment]
@xabbuh could this be the problem?

https://github.com/dadepl/sfusertest/blob/master/src/Company/AppBundle/Entity/User.php#L40

So somehow it treats the email as an object and tries to get the metedata for it? :see_no_evil:

**Comment by dadepl** [comment]
@dmaicher Thanks! It helped when I removed `@Assert\Valid` or changed it to `@Assert\Email()`!
Other case is I don't know why there was such behaviour and despite of that, I will have to investigate why I had such code in my entity file ;)

Thanks one more time!

**Comment by xabbuh** [comment]
@dmaicher Great catch :+1: not sure though why this didn't fail for me. So this does not look like an error in the Cache component, but we need to investigate why using the `Valid` constraint here doesn't fail earlier.

**Comment by dmaicher** [comment]
@xabbuh I checked a bit and actually here

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L717

The Validator just passes any scalar value and treats is as an object. So it tries to fetch the meta data here:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L328

And the value is then passed through to the `Psr6Cache` which is not properly escaping it?

**Comment by pmontoya** [comment]
Maybe i could have a try for my first issue?

**Comment by xabbuh** [comment]
@pmontoya That would be great! 👍

**Comment by pmontoya** [comment]
Ok, it's for me! 🤞

**Comment by stof** [comment]
> And the value is then passed through to the Psr6Cache which is not properly escaping it?

the escaping is done assuming the fact that metadata are loaded for a class name, which cannot contain a `@`.

but the `class_exists` check in the factory is done *after* trying to read from the cache rather than before: https://github.com/symfony/symfony/blob/ee51f74a8c3f2d941e50697bb0c15a8e5fc7038d/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php#L98

**Comment by dmaicher** [comment]
@stof indeed :+1: Should be fine to move this check before trying to retrieve something from the cache then

**Comment by abelardolg** [comment]
This issue happens again.
This is my setup:

Symfony cli version 5.4.7

My composer.json contains:
_"extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    }_
   
PHP Version: 7.4
OS Version: Windows 10 Home

The message is:
![image](https://user-images.githubusercontent.com/22522883/166877437-7220ca06-87a2-4fa0-8aea-9c5066be725f.png)

Cache and log dirs were deleted.

Point of my code where this error starts: 
![image](https://user-images.githubusercontent.com/22522883/166877695-17f1b7f1-ed42-4d3e-b3c9-c40a437210aa.png)

Point of my code where this message is showed:
![image](https://user-images.githubusercontent.com/22522883/166877724-0763b758-afed-491e-af5d-ac8598913d3d.png)

How could I solve this issue, please?
This link https://github.com/dadepl/sfusertest/blob/master/src/Company/AppBundle/Entity/User.php#L40
is 404.

Best regards.

**Comment by xabbuh** [comment]
This is probably related to an update of Doctrine packages. You now need to access the repository using the FQCN instead of the alias like this:

```php
$user = $em->getRepository(User::class)->findOneBy(['email' => $email);
```

**Comment by abelardolg** [comment]
Thanks, Christian. @xabbuh
