### ISSUE TITLE
Console - make:subscriber - interactive mode autocomplete - bug

### ISSUE THREAD

**Issue by youssefbenhssaien** [symfony/symfony#26321]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

## Description :
Using the command **make:subscriber** with an event suscriber **kernel.controller** on the interactive mode (Responding to the 'What event do you want to subscribe to?' question).
Submited : **kernel.controller**
Result : **kernel.controller_arguments**

## Console :

![image](https://user-images.githubusercontent.com/7301643/36678860-2363187c-1b12-11e8-93d1-b2c6900222d8.png)
<h2>Result :</h2>

![image](https://user-images.githubusercontent.com/7301643/36679102-b0d6f502-1b12-11e8-83fd-43d1c8aae9d0.png)

## Bug caused by :
When puting an **Enter** character on the console, a last check is made to verify even the character is a new line **\n** or a tabulation **\t**, then choose the returned autocomplete from the **matches** array with an **$ofs = 0** which return **$matches[0] = 'kernel.controller_arguments** on the following lines :
https://github.com/symfony/symfony/blob/cd5f4105a43208632c8b62fd75b4dad53dcd8a41/src/Symfony/Component/Console/Helper/QuestionHelper.php#L235-L239

**Comment by youssefbenhssaien** [comment]
Rewriting the same function, this is my suggestion and not well tested :
<code>
/**
     * Autocompletes a question.
     *
     * @param OutputInterface $output
     * @param Question        $question
     * @param array           $autocomplete
     */
    private function autocomplete(OutputInterface $output, Question $question, $inputStream, array $autocomplete): string
    {
      $word = $this->readLineFromStream();

      /* if the typed word exits on autocomplete list will return it */
      if(in_array($word, $autocomplete)){
        return $word;
      }

      /* calculate the word matches from autocomplete */
      $matches = $this->getWordMatchesSuggestion($word, $autocomplete);

      if(count($matches) > 0){
        do{
          $response = $this->suggestWordsList($output, $matches);
        }while($response && !in_array($response, $autocomplete));

        /* replace the old word only if response is different than false and the old one */
        if($response && $word != $response){
          $word = $response;
        }
      }

      return $word;
    }

    /**
     * Ask question with keywords list and return response
     *
     * @param OutputInterface $output
     * @param array           $suggestionList
     * @param int             $returnedRows
     */
    private function suggestWordsList(OutputInterface $output, $suggestionList = array())
    {
      /* Suggest new words based on matches result */
      $output->writeln(sprintf('Did you mean : %s ? type No if you want to keep your choice.', implode(', ', $suggestionList)));
      $response = $this->readLineFromStream();

      return ('no' == strtolower($response))?false:$response;
    }

    /**
     * Return similar word list from suggestion list.
     *
     * @param OutputInterface $output
     * @param array           $suggestionList
     * @param int             $returnedRows
     */
    private function getWordMatchesSuggestion($word, array $suggestionList, int $returnedRows = 1)
    {
      $wordLength = strlen($word);
      $minCharsToMatch = $wordLength/2;

      foreach ($suggestionList as $suggestion) {
        /* calculate matches keys */ 
        $matchesKeys = similar_text($word, $suggestion);
        if($matchesKeys > $minCharsToMatch){
          if(isset($matches[$matchesKeys])){
            $matches[$matchesKeys] = array_merge((array)$matches[$matchesKeys], (array)$suggestion);
          }else{
            $matches[$matchesKeys] = $suggestion;
          }
        }
      }

      /* sort the matches keywords */
      krsort($matches);

      return ($returnedRows > 1)?array_slice($matches, 0, $returnedRows):current($matches);
    }

    /**
     * read line from console.
     */
    private function readLineFromStream(){
      /* read until getting an empty word */
      do{
        $word = trim(fgets(STDIN));
      }while(empty($word));

      return $word;
    }
</code>

**Comment by Simperfit** [comment]
Do you want to provide a pull request directly ?

**Comment by nicolas-grekas** [comment]
Fixed by #26875.
