### ISSUE TITLE
Make ExpressionLanguage more extensible

### ISSUE THREAD

**Issue by markoffk** [symfony/symfony#26322]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Hello!

I need to **restrict** one binary operator from Symfony expression language (for example: .. double dot operator). All binary operators are defined in `Symfony\Component\ExpressionLanguage\Parser`. 
So I came to conclusion that I need somehow to redefine $this->binaryOperators in Parser.
That Parser is used later in `Symfony\Component\ExpressionLanguage\ExpressionLanguage`. But unfortunately, it is not possible to override ExpressionLanguage class to make it use another custom Parser in any way (except of just creating own class by copying 99% of ExpressionLanguage class), because of this piece of code:
```
    private function getParser()
    {
        if (null === $this->parser) {
            $this->parser = new Parser($this->functions);
        }

        return $this->parser;
    }
```

May I kindly ask SF developers to adjust this class: make this function protected or make it possible to use Parser injection from constructor?

Thanks!

**Comment by ostrolucky** [comment]
I suggest to use [hoa/ruler](https://github.com/hoaproject/Ruler) instead. It's more flexible and less quirky than Symfony ExpressionLanguage.

**Comment by stof** [comment]
The ExpressionLanguage component is not meant to provide an extendable parser to build your own languages. This is not the goal of the component. There is already dedicated libraries targetting such goal.

**Comment by nicolas-grekas** [comment]
Closing as explained. Thanks for the proposal anyway.
