### ISSUE TITLE
[RFC] Configure default form fields from annotations

### ISSUE THREAD

**Issue by florentdestremau** [symfony/symfony#26323]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.x

I have been thinking lately about a new type of annotation to configure default Form options from the entity. What I have in mind is something like this.

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    // [...]

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(max="100")
     *
     * @Form(placeholder="Your post title", required=true, attr={"class": "input-lg"})
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     *
     * @Form(placeholder="Write something here!", required=true, type=CKEditorBundle\Types\CKEditorTextareaType)
     */
    private $body;

    // [...]
}
```

And then the form would be 

```php
class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('body')
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}
```

And the body would have a proper CKEditor widget for instance, and my title input would be large anytime I would call it.
It is considered best practice to handle Doctrine configuration, Validation constraints, why not Form defaults ? Everything would be overridden by any configuration in the Form class of course. 

Especially when you have multiple forms for your entities (User registration, User profile, User notifications, pictures, whatever...), and when you are reusing several fields but not exactly in an extendable way, this would make it a bit easier for rapid configuration.

This looks a bit like form themes but these are made only for display, while this could have a complete configuration pre-set.

**Comment by xabbuh** [comment]
IIRC something like this has been proposed in the past. To me this is something that would rather be implemented in a third party library.

**Comment by ogizanagi** [comment]
See https://github.com/symfony/symfony/issues/20976 for a previous suggestion with similar ideas.

While, in most cases, I'm not fond about these annotations on entities (cf [this](https://stovepipe.systems/post/avoiding-entities-in-forms) for instance), I agree such a feature could be useful to solve the most simple use-cases in your Application/UI layer.

Anyway, I agree this should be experimented first in a community bundle before agreeing on including it in the core and having to maintain it for years.

**Comment by ro0NL** [comment]
Kinda defeats type guessers no? Im not sure it really fits the Form component, assuming if we do annotations we can do Yaml, XML, etc. also. Introducing a another metadata factory practically.

Also most options ideally are defined at the view level anyway, IMHO :)

**Comment by florentdestremau** [comment]
I'll try to make a bundle and submit it here then :)
Not sure about what you mean by 'view level' @ro0NL ?

**Comment by ro0NL** [comment]
@florentdestremau template files :)

`SomeType.php`

```php
<?php

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TexType;
use Symfony\Component\Form\FormBuilderInterface;

final class SomeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('field', TextType::class);
    }
}
```

`form.html.twig`

```twig
{{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_row(form.field, { label: 'Field label'|trans, attr: { class: 'special-class' } } }) }}

    <div>
        <input type="submit" value="{{ 'Submit'|trans }}" />
    </div>
{{ form_end(form) }}
```

**Comment by florentdestremau** [comment]
I prefer using `{{ form(form) }}` whenever possible with form themes, because it keeps the configuration reusable, but I understand your point :wink:

**Comment by florentdestremau** [comment]
I mean my dream is to actually have an automatic FormType kind of like [a serializer](https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies) with "exposed" fields within groups...and then directly use `{{form(form)}}` which would use the field configuration and automatically render the form like you want it.

In an app where you can have a user form, an admin user form, and several declination of them, this would be my dream : pick only the fields you need to edit, having their configuration already defined.

Maybe a `config/forms.yml` could actually hold this configuration ? Kind of like easyadminbundle

**Comment by ro0NL** [comment]
Right.. i see where you're going. And technically nothing against that also.

But in terms of speaking about dreams, mine's about separating concerns :) which is already possible today as shown in above snippet. You can do multiple types, inheritance, etc.

If SF adds such a concept to core chances are it becomes a best/known practice. Do we want that? It needs serious thought. These types of decisions lead to "entities bound to forms" to be a de facto standard. Not bad, but it raises other issues that sooner or later might backfire.

My point is; many of these issue can be avoided when you decouple / separate concerns by default. This proposal goes against that IMHO. And TBH in my experience enables RAD already.

If anything needs improvement it's form theming itself :) make it easier / more intuitive from the view layer to work with.

**Comment by florentdestremau** [comment]
Alright I'll try out something with a bundle and keep this issue updated. Or should I close it and re-open when I have something to show? Not sure about the guidelines here.

**Comment by ro0NL** [comment]
I'd say keep it open to get more possible feedback in between :)

:+1: for trying. Dont want to shoot down your idea or so, which is not bad on itself.

**Comment by deeky666** [comment]
There is already a bundle featuring something like this: https://github.com/codete/FormGeneratorBundle

**Comment by xabbuh** [comment]
For the record, to me this does not belong into the core, but should be solved by using a third-party bundle.

**Comment by nicolas-grekas** [comment]
Closing then.
