### ISSUE TITLE
Add Symfony 4 to kenjis/php-framework-benchmark

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#26336]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

This benchmark contains old versions of Symfony:
https://github.com/kenjis/php-framework-benchmark

Anyone willing to send an update for Symfony 4?

**Comment by rpkamp** [comment]
I have opened a pull request there: https://github.com/kenjis/php-framework-benchmark/pull/86

**Comment by nicolas-grekas** [comment]
Thank you @rpkamp!
