### ISSUE TITLE
Custom headers in 4.x Request

### ISSUE THREAD

**Issue by IlCallo** [symfony/symfony#26333]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

I searched issues and PRs and found nothing about the ability to re-add custom headers mapping in some form, like it where possible in previous versions.

My use case has been described in https://github.com/jdavidbakr/CloudfrontProxies package readme, but also other packages are struggling with the need of managing custom headers (https://github.com/fideloper/TrustedProxy/issues/108).
It's not a critical feature probably, but it was really simple to do before, now it seems that it's no more possible.

Anyone else got this need?

**Comment by nicolas-grekas** [comment]
Hello @IlCallo thanks for your report. I think we were not aware that custom headers were actually useful - at least nobody reported any use case when we removed the possibility to use custom headers.
I think you can do this now instead, WDYT?
`$_SERVER['HEADER_X_FORWARDED_PROTO'] = $_SERVER['HEADER_X_FORWARDED_PROTO_CUSTOM'];`

**Comment by IlCallo** [comment]
> Can you do this early enough now instead, WDYT?
I can't really understand this sentence, I guess you where asking if the code you suggested is a valid workaround for the problem.

The first package I linked already solves the problem for this use case scenario using a custom middleware, I created this issue just to let you know that some people is missing that feature and would welcome a way to define custom headers, parallel to the current management or integrated into it.

**Comment by Simperfit** [comment]
@IlCallo do you want to work on this feature ?

**Comment by IlCallo** [comment]
I actually moved from backend to frontend development, so I'm a bit rusty and won't have time to catch up...

**Comment by Simperfit** [comment]
@IlCallo Don't worry !
