### ISSUE TITLE
[FORM] Add Bootstrap 4 "help text"

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#26331]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 

Bootstrap 4 has a feature they call "help text" ([documentation](https://getbootstrap.com/docs/4.0/components/forms/#help-text)). I think it would be a great idea to support that. 

FYI, @mpiot you did an awesome implementation to this before. Do you mind doing a new PR with that feature?

**Comment by mpiot** [comment]
I actually search how to add a `form_help` like `form_label`, `form_widget`, `form_row`, etc...
And have a way in the `FormType`, to directly have a key: `help` like `attr`, `choices`, `expanded`, etc... And common for all `FormType` that aren't a button.

But, I'm a little lost in all the files, the way to do it...

My previous version, is just a `data-help` in the `attr`, and I retrieve it in the twig template, it's not very nice for a new feature...

**Comment by Nyholm** [comment]
I think we could start with that implementation. Lets see what comments we got when the PR is opened.

**Comment by javiereguiluz** [comment]
While we are at this, why don't we add a feature to define help text in form fields? It's so embarrassing that that Form component doesn't support such a trivial and common feature.

In a private application I needed to create a Form extension just to define and display the help message. Things like that make Symfony look worse than it is. In EasyAdmin we also need to add some custom logic to display help text in form fields: https://github.com/EasyCorp/EasyAdminBundle/blob/0f0a3a389f2555c2131867b18aca6e39eafa6153/src/Resources/views/form/bootstrap_3_horizontal_layout.html.twig#L44

Please, add this basic and much needed feature 🙏

**Comment by mpiot** [comment]
I've maybe find how to do, I do a branch, and create the PR.
