### ISSUE TITLE
[Security] Allow RoleHierarchyVoter to abstain from certain roles (in unanimous mode)

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#26342]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I have a role called `ROLE_OWNER` which is a contextual role granted by a custom voter, `UserOwnerVoter`.

I'm building a somewhat complex privilege system (for a multi-tentant API app where clients will be able to share access to their content to other clients, etc) and need to use unanimous strategy.

In this case, `RoleHierarchyVoter` (or `RoleVoter` in general) gets asked if the user is granted the `ROLE_OWNER` role. But, the role is contextual and cannot be checked like that. What would be useful is to tell `RoleVoter` to abstain from certain roles, as they're "different".

Currently, I'm working around that by simply not specifying the `ROLE_` prefix but, that took some time and debugging to get right (partly because of #26343) and also feels Symfony-ish "If you don't do this special thing, magic (doesn't) happen".

**Comment by stof** [comment]
Well, you could use a different naming than `ROLE_OWNER` (for instance just `OWNER`). Abstaining in this voter is precisely done by checking the `ROLE_` prefix.

And this is not about magic or not magic at all.

A voter is not asked to vote on a role, but on a permission attribute. These can be roles or anything else you want (and using other things is *precisely* the use case for custom voters)

**Comment by dkarlovi** [comment]
> A voter is not asked to vote on a role, but on a permission attribute. 

True, but `RoleVoter` **does** vote on a role. It took quite a bit of work to figure out `RoleVoter` was voting where it didn't need to (although having #26343 would fix that).

**Comment by curry684** [comment]
I'm not sure I follow your reasoning, the behavior of the default `RoleVoter` is [pretty well documented](https://symfony.com/doc/current/components/security/authorization.html#rolevoter).

It votes on all strings with a `ROLE_` prefix. It doesn't vote on any other attributes. So you should not mix custom attributes which are a string with a `ROLE_` prefix if you don't want `RoleVoter` to vote on it.

**Comment by stof** [comment]
@dkarlovi no, it votes on attributes (like any other voter), abstaining from anything which is not a string starting with the `ROLE_` prefix.

**Comment by javiereguiluz** [comment]
I'm closing this one because, as explained, this is the expected behavior and it's also documented that way. Thanks.
