### ISSUE TITLE
[Validator] Choice constrait callback service call

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#26340]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

I would like to get choice list as result of call some service method. Looks like it is impossible for now.

**Comment by iltar** [comment]
Do you have an example of how you'd like to use this feature? I know that it's already possible, but is a bit of extra work.

**Comment by Strate** [comment]
For example if I have a list of choices in database, or on a different server, and I want to implement cache, etc

**Comment by rpkamp** [comment]
The way I do this is by [registering the form type as a service](https://symfony.com/doc/current/form/form_dependencies.html#define-your-form-as-a-service), pass it the service that has the choices I need, call that service in the `buildForm` method, and pass the choices.

Something like this:

```php
<?php

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface

class TaskType extends AbstractType
{
    private $service;

    public function __construct(MyService $service)
    {
        $this->service = $service;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $choices = $this->service->getSomeChoices();

        $builder->add('foo', ChoiceType::class, ['choices' => $choices]);
    }
}
```

**Comment by rpkamp** [comment]
Well in that case it's probably easiest to create a custom constraint with a custom validator. It's quite easy and gives you all the flexibility to cache and whatever you might need.

See https://symfony.com/doc/current/validation/custom_constraint.html

**Comment by Strate** [comment]
@rpkamp yes, right now my solution is close to that. Btw, this issue about improve DX in this case.

**Comment by xabbuh** [comment]
How do you see the feature being used? Would you somehow configure the constraint to let it know where to find the choices? Or do you see it as something that would be done only when the data is being validated by the validator?

**Comment by Simperfit** [comment]
@xabbuh I think this can be closed. As we can do the same with custom validator/constraint.
