### ISSUE TITLE
Unable to install SF4 behind a proxy

### ISSUE THREAD

**Issue by Isarien** [symfony/symfony#26353]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

Hi,

I don't know if it's a composer issue or a SF4 issue, but I think it's Symfony because, lastest version of SF3 install fine with composer. 

HTTP_PROXY and HTTPS_PROXY are correctly filled in system variables environnement of my Windows 7. I also set these variables in bash environnement (MINGW64).
Composer was updated to the lastest version.

When I execute the first command of the symfony setup documentation : composer create-project symfony/website-skeleton my-project , the 2 first libraries dowload and install fine (ocramius/package-versions (1.2.0) and symfony/website-skeleton (v3.4.4)), but the third ( symfony/flex (v1.0.70)) give me the following network error : 

  [Composer\Downloader\TransportException]
  The "https://symfony.sh/ulid" file could not be downloaded: failed to open
  stream: Cannot connect to HTTPS server through proxy

It's strange because everything work fine with SF3.

**Comment by nicolas-grekas** [comment]
Thanks for the report. This looks like an issue for https://github.com/symfony/flex
Do you have the curl extension enabled? If yes, can you try disabling it?
Also, which version of composer do you use? If based on "master" (ie 1.7), can you try a stable one (ie 1.6 or lower)?

**Comment by Isarien** [comment]
Nicolas,
Thank you for your answer. Yes curl was enabled. I try the command line with curl disabled, and I get the same issue.
My version of composer is 1.6.3. I try with 1.5.6 and same issue.

**Comment by xabbuh** [comment]
let's close here in favour of symfony/flex#328
