### ISSUE TITLE
[RFC] Deprecate end() in config fluent interface

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#26351]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.x

I believe this was already proposed once when building the DI fluent config format. Moreover, i think it's possible in a way.. relying on something like what's currently also being proposed for DI config: #25650

However for Config component it would be required to do it that way, as without `end()` we dont know the scope of the node definition (meaning based on indentation things could either apply to a child- or parent node).

Overall, i think it could be a cool step. Aiming for a bit more simplicity as well as better support for custom node types in the long run.

Im thinking something along the lines of:

```php
<?php
$rootNode
    ->children(function (YourNodeBuilder $builder): void {
        $builder
            ->scalarNode('foo')
                ->isRequired()
            ->booleanNode('bar')
                ->cannotBeEmpty();
    })
    ->validate()->always(function ($value) {
        // ...
    });
```

Thoughts?

**Comment by ro0NL** [comment]
Some more suggestion from my side:
- consider `allowEmpty()` over `cannotBeEmpty()` (the no. of configs i saw forgetting this is too high).
- default features handled in `VariableNodeDefinition/ArrayNodeDefinition::createNode()` should be shared by `NodeDefinition::create/prepareNode()`, ideally :)

**Comment by stof** [comment]
I'm not sure the usage of nested closures to configure nested hierarchies is actually that much easier to use.

**Comment by ro0NL** [comment]
Yes, it looks a bit more cluttered. Then again, it makes the current node scope also look more explicit IMHO :thinking:

Eventually what convinced me to do the RFC is it could solve autocomplete/static analysis issues, considering custom node types (which is what im getting into currently :)). Depending on the use case i really started to like having those.

Currently if you do a custom `NodeBuilder` (to provide `myNode(...)` you need to override all `end()` definitions in order to let config know about the builder, in terms of always providing autocompletion.

But now thinking about it.. im not sure closures solve it :thinking:

**Comment by ro0NL** [comment]
So basically this is about:
```
@return NodeParentInterface|NodeBuilder|NodeDefinition|ArrayNodeDefinition|VariableNodeDefinition|null
```

on `end()`; mother of mixed API :)

- `null` is a pain to deal with in terms of static analysis
- my custom node builder is missing from the list, as well as my custom node type
- technically, all the calls work =/

**Comment by stof** [comment]
well, normal nodes would still not have a defining `myNode` method, so it would either need to rely on the generic `node` method (which cannot tell the IDE that passing `my` as second argument returns a MyNodeDefinition object) or using `__call` to allow using `myNode()`, which is even worse as NodeBuilder would not even be able to tell your IDE that it has a magic `myNode` method (as it does not have it until you register your custom node type).

So your proposal would not solve anything for custom node types (as all methods in Symfony would still document NodeBuilder, not your custom child class)

**Comment by stof** [comment]
btw, your example is wrong. The argument passed to the `children` callback would not be an ArrayNodeDefinition

**Comment by ro0NL** [comment]
^ correct. You'd get a builder :) just wrote that quickly.

> So your proposal would not solve anything for custom node types (as all methods in Symfony would still document NodeBuilder, not your custom child class)

I think you're right. It bugs me a bit though :) as technically it's working as expected/designed. But today that's not enough without proper autocompletion/static analysis IMHO. Defeating a useful thing...

So ... put different; can we think of something clever?

**Comment by fabpot** [comment]
Yes, I can think of something clever: let's not change anything. I mean, I don't see why we should change the way it works today. I've never seem anybody complaining about the current syntax. And changing it to something means breaking all configs out there (at the minimum, people would have to remove all their `end()` calls at some point).

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/blob/1f7b9f0fc5dcb174decba523280f81dd23c122f3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L369-L374

would be solved with closures. Today  i'd prefer that.. but i understand making the change now is not a top prio.

if something could solve SA/autocompletion that be nice. With either end() or closures... but  it's not possible AFAIK.

Sorry for the noise :)
