### ISSUE TITLE
Improve misleading error message when controller service is not found

### ISSUE THREAD

**Issue by ahundiak** [symfony/symfony#26359]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.3

So I got this:

    Controller "fos_rest.exception.twig_controller" 
    cannot be fetched from the container because it is private. 
    Did you forget to tag the service with "controller.service_arguments"

And naturally went looking for why the controller was not public.  Turned out the controller was simply not defined at all.  I think a simple:

    cannot be fetched from the container because it is undefined or private

Might save some developer effort.

**Comment by nicolas-grekas** [comment]
The message is thrown is a code path that first checks if the service was defined.
Which means the service was private, really.
Because it didn't get any use, it was later on removed.
But it was defined first, as private;

**Comment by ahundiak** [comment]
I understand and that is indeed what happened in this case.  Still think it is somewhat misleading since, at the time the exception is thrown, the service is no longer defined.   But at least now I know what to look for when --show-private does not show the service.  Maybe we need a 

    bin/console debug:container --show-removed

**Comment by stof** [comment]
The fact that `--show-private` does not allow seeing removed private services (and probably not inlined private services either for the same reason) might be the issue to me.

**Comment by nicolas-grekas** [comment]
I agree. @ahundiak would you like to send a PR that would add removed ids to the list displayed by --show-private? There is a new getRemovedIds() method on 3.4 that allows so.

**Comment by chalasr** [comment]
There should be nothing to fix regarding `debug:container --show-private`, it does show removed and inlined services since https://github.com/symfony/symfony/pull/22385. Just tested with a private controller, it is listed (and getting the very same runtime error).

**Comment by chalasr** [comment]
@ahundiak right, the linked PR just skips compiler passes of type `REMOVING`, the one that removes the `fos_rest.exception.twig_controller` is of type `BEFORE_OPTIMIZATION`.
So the command indeed needs to deal with `removedIds`. 
If you can't manage to make fix it I can give it a try or try to help you, don't hesitate to ping me e.g. on slack.

**Comment by chalasr** [comment]
Thinking about this twice, I doubt we want to display services that are explicitly removed by something else that core removing passes. 
Here the definition is removed because it is incomplete, so the service would be unusable really. Seems more like a DX issue in FOSRestBundle, I think we can close.

**Comment by chalasr** [comment]
Closing, please reopen if I'm wrong.
