### ISSUE TITLE
How to make a default url for every controller in Symfony 3 ?

### ISSUE THREAD

**Issue by zjsxwc** [symfony/symfony#26367]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.13

I need a default url(and a corresponding twig file) for every controller so that other people who only write css/js can simply edit the corresponding twig without adding a new action method for the php controller.

currently, I map the URL path to a controller action by annotation.

How to make this default url in Symfony 3 ?

**Comment by WitteStier** [comment]
Create a controller and accept a template name param. Use this param to define a template.

``` php
class defaultController {
    public function twigAction($tmpl)
    {
        return new Response($tmpl);
    }
}
```

**Comment by iltar** [comment]
Github is not meant for support question, please check http://symfony.com/support

I can recommend joining slack and check out the support channel :+1:

**Comment by chalasr** [comment]
Closing as it's a support issue as explained by @iltar, thanks for your understanding.

**Comment by zjsxwc** [comment]
`render_without_controller` solves my problem.

http://symfony.com/doc/3.2/templating/render_without_controller.html
