### ISSUE TITLE
[Translator] translator.data_collector service missing in 4.0.5

### ISSUE THREAD

**Issue by mnavarrocarter** [symfony/symfony#26374]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.5

Okay, I don't know if this is my fault or not. I've been trying to debug this for a while now, and I have some hints.

I'm developing a RestBundle for Symfony `composer require mnavarrocarter/rest-bundle dev-master`. It works fine in Symfony 3.4. But when I try to install in on 4.0.5, it throws the following Exception on line 32 of the `CheckExceptionOnInvalidReferenceBehaviorPass.php`

```
The service "serializer" has a dependency on a non-existent service "translator.data_collector".                           
```

This is my bundle's `composer.json`:

```
"require": {
        "php": ">=5.5.9",
        "pagerfanta/pagerfanta": "^1.0",
        "symfony/security-bundle": "~2.8|~3.0|^4.0",
        "symfony/orm-pack": "^1.0",
        "symfony/framework-bundle": "~2.8|~3.0|^4.0",
        "league/fractal": "^0.17",
        "limenius/liform": "^0.12",
        "symfony/form": "~2.8|~3.0|^4.0",
        "symfony/translation": "~2.3|~3.0|^4.0",
        "symfony/serializer": "~2.8|~3.0|^4.0",
        "symfony/validator": "~2.8|~3.0|^4.0"
    },
```

My lock says dependencies are:

```
symfony/serializer 4.0.5 0526b430c8548520fd5817f425d9a3d8a11a21e1
symfony/serializer-pack 1.0.1 35cea385ea44d1f40ec12571996bf768fbe409de
symfony/translation 4.0.5 e20a9b7f9f62cb33a11638b345c248e7d510c938
symfony/framework-bundle 4.0.5 1221c54863061e71573b07882b4c53795fbfc229
```

I've found a [CompilerPass](https://github.com/symfony/framework-bundle/blob/master/DependencyInjection/Compiler/DataCollectorTranslatorPass.php) in FrameworkBundle that removes from the container definitions for this service if the translation service is enabled.

Turns out my bundle needs that definition, but it's being removed for some reason that I ignore.

I traced some commits to that file. My guess is that there was a major change in the translation service from 3.4 to 4.0 that I'm not aware of.

If someone could point me to a resource or give me some help in how to fix this dependency issue, I would be very grateful. Maybe I have to fix some dependency in my bundle to make it work with Symfony 4.

**Comment by xabbuh** [comment]
How can we reproduce your issue? Could you create a small example application?

**Comment by mnavarrocarter** [comment]
I could create something and put it into a VPS, but it is really easy to reproduce. Just do:

```
composer create-project symfony/skeleton Test
cd Test
composer require mnavarrocarter/rest-bundle dev-master
```

The third command will not terminate successfully, showing the error.

**Comment by xabbuh** [comment]
I have checked that. The error message is not the best, but the error actually comes from your `Limenius\Liform\Serializer\Normalizer\FormErrorNormalizer` service which requires the `translator.data_collector` service.

**Comment by mnavarrocarter** [comment]
Interesting, to me it was was showing that the serializer needed that service. I'll reproduce as well and tell you what I found. Thanks for the help.

**Comment by xabbuh** [comment]
Yeah, that's what I meant with that the exception message is confusing.

**Comment by mnavarrocarter** [comment]
![screenshot from 2018-03-05 09-38-49](https://user-images.githubusercontent.com/17072441/36975511-0e01ed5e-2059-11e8-91f7-ca9c4f0d5cf8.png)

So weird. Anyway, I think the compiler pass I mentioned above unregisters the service definition in question from the container if the translation service follows a determined interface. It does that only in SF4. I wonder why.

I just need to find a replacement for that service in SF4, and write a compiler pass that changes the argument of those services when in SF4. It's the only thing I can think of.

**Comment by mnavarrocarter** [comment]
@xabbuh I just realized you wrote that compiler pass, haha. Is there a reason for unregistering those services? I understand that maybe those services where deprecated in light of a new translator service interface, but is there a replacement for `translator.data_collector` service in SF4?

**Comment by xabbuh** [comment]
That compiler pass is there to make sure that the code does not break in case a custom `translator` service's class does not implement the `TranslatorBagInterface` which [is required by the `DataCollectorTranslator`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/DataCollectorTranslator.php#L37-L39).

In your case, this compiler pass is not a problem. It is simply never registered because the WebProfilerBundle is not installed.

**Comment by mnavarrocarter** [comment]
Ah, that was it! Thanks so much. I'll make sure I add the web profiler bundle as a dependency in my bundle composer.json. Thanks for all your help!
