### ISSUE TITLE
[DX] Console command description/help

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#26376]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | maybe
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.7

Hi,

In a console command, we can have a description and an help.
I think it could be better to have the description on top of the --help option output instead of at the end. 

- Description first
- Usage then
- Help at the end

before

<img width="1016" alt="before" src="https://user-images.githubusercontent.com/13205768/36901130-3f1383c4-1e26-11e8-90af-e3d56a89bb5d.png">

after

<img width="1018" alt="after" src="https://user-images.githubusercontent.com/13205768/36901134-44acafae-1e26-11e8-8800-909802545ec4.png">

What do you think?

**Comment by iltar** [comment]
Sounds like a good idea to me!

**Comment by chalasr** [comment]
👍

**Comment by Simperfit** [comment]
@noniagriconomie Do you want to provide a Pull Request for this ?

**Comment by noniagriconomie** [comment]
I can work on it yes
Should i do it on 4.0 ? 3.4 ? Or 2.8 ?
Thank you

**Comment by Simperfit** [comment]
@noniagriconomie Since this has been tagged as a bug/dx you should do it on the lowest branch that contains the feature, we will treat it as a bugfix.

Thanks for contributing to symfony! :)

**Comment by Simperfit** [comment]
Status: Reviewed

**Comment by noniagriconomie** [comment]
@Simperfit i will do a PR on 2.7 for this little fix then :)
