### ISSUE TITLE
[Form] Entity wrongly hydrated when using @UniqueEntity

### ISSUE THREAD

**Issue by cedricdo** [symfony/symfony#26375]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.5

Hi, i've a weird issue with symfony form.

__Description:__
 I have an entity (Certification) linked to another (Filiere). When i use a form to modify the Certification, if i select a filiere in the select and submit the form, the data are correctly persisted in database.

However, since i allowed empty value with `required = false` in my form type, i want to remove the link between a certification and a filiere. I select the placeholder in the list, clic the button, and nothing is persisted.

__Expected behavior:__
When i select the placeholder in the list, the link between the entities should be removed (set null in apropriate column in certification table).

__How to reproduce:__

I created a small project which reproduce the issue.

```sh
git clone https://github.com/cedricdo/bug_sf.git
cd bug_sf
composer install
cp .env.dist .env
# execute bug_sf/db.sql to generate dabatase
# edit .env to put correct DABATASE_URL
php -S 127.0.0.1:8000 -t public/
```
Go to http://localhost:8000 on your favorite brower, you should see a form with a text field and a select.

__Investigations__:
After some search, it seems the issue come from the `@UniqueEntity` on the `Certification` entity. If i remove it, everything works fine.
I tracked down the issue and found some stuff:
- The `App\Entity\Certification::setFiliere` method is correctly called with `null` as parameter during by `Symfony\Component\Form\Form::submit` method
- During the form validation, specificaly the `UniqueEntityValidator`, the `$filiere` property of  the `Certification` entity get hydrated again with a `Filiere` entity and the `null` is lost. This hydratation is done without calling the setter
- This hydratation happens on [`UniqueEntityValidator` constraint of the `doctrine-bridge`](https://github.com/symfony/doctrine-bridge/blob/70d60f31811c0e522a75f4d0974da1cd4910c368/Validator/Constraints/UniqueEntityValidator.php#L139):  before this line is executed, the `$entity` parameter of the method has the correct value for `filiere` property. After this line, the property is hydrated with a `Filiere`entity

**Comment by iltar** [comment]
Is this the owning side of a relation with a nullable join by any chance? If so, doctrine will probably re-hydrate the related entity, because it cannot determine whether or not it's actually null or an entity when querying again. I'm not sure if fetching an entity again is supposed to modify it (I know for sure `em::refresh()` does), so this is my best guess.

**Comment by xabbuh** [comment]
see #25181 and #23961
