### ISSUE TITLE
Ajax requests not working when web-profiler-bundle is used

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#26380]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.5

Hi,

'tbody.rows.count is not a function' error is showed in console when i try to make an ajax request, with profiler toolbar open.
It works if I revert to version 4.0.4.

Regards,
Marton

**Comment by Simperfit** [comment]
A fix has been already merged to fix the wrong behaviour. Sorry about that.
It will be released with the next version.

**Comment by Simperfit** [comment]
This was discussed [here](https://github.com/symfony/symfony/issues/26364), there are workaround in the issue if you need them and if you downgrade only the web-profiler-bundle it works too.
