### ISSUE TITLE
Customize AppKernel for cache/log location

### ISSUE THREAD

**Issue by woofiewilly** [symfony/symfony#26386]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

This is something that I asked for feedback in the Symfony slack for, and got some support and confirmation that many people come up with similar solutions.

# Background
The issue is that for different environments - particularly Virtual Machines - it's desirable to have different paths for the `var` directory. Furthermore, it's desirable to have a different location for the Composer `vendor` directory. The specific situation where this is necessary is in virtual machines where the project lies in a synced/network mounted folder. Often the extensive reading/writing that Symfony does with these three directories on every request results in a big performance hit when they are inside the synced folder. Moving the directories to a local location in the VM resolves this, but people might not want the same override on their deployment servers.

# Solution
I have a fairly clean solution for making this more flexible. There is a default path for these directories, but I have a check for a `SYMFONY_VAR_DIR` environment variable. If it exists, that path as a prefix to `cache` and `var` instead. This is done in the AppKernel.

Composer supports a `COMPOSER_VENDOR_DIR` environment variable, which it will automatically use as the install path for vendor files. Again, I added a check in `index.php` for this environment variable, and it will be used to include `autoload.php` if it exists, otherwise a default path will be used.

I think that it would be nice if this kind of behavior was natively supported by Symfony, and adding it would not require much extra logic. I think it would be best configured as one of Symfony's environment parameters so that it could be configured per machine. In addition to `SYMFONY_VAR_DIR`, the optional variables `SYMFONY_CACHE_DIR` and `SYMFONY_LOG_DIR` could be supported, if specific control over those paths are desired.

For Composer, I'm not sure if it could cause any unpredictable behavior for some people to just add the same environment variable check that I described above. Hypothetically if the `COMPOSER_VENDOR_DIR` variable exists, there should be no reason to expect the vendor directory elsewhere. I'd like to make that check native to Symfony.

I'm requesting comment on this issue because I'm not sure if these changes would be accepted. I could imagine them being denied on the basis that the Symfony skeleton is desired to be as barebones as possible, and these modifications can be added by anyone that needs them. Although there seems to be  Also, these changes would be useful for all currently supported releases of Symfony; I'm not sure if these changes are too significant to safely add into the older LTS releases.

If there are recommendations on how to better deal with adding this functionality into the project, please share them. There seem to be quite a few people that are interested in this feature; people that always copy paste their code to overwrite these methods when they make a new project.

**Comment by javiereguiluz** [comment]
For the cache/ and log/ dir it would be easy to implement that as explained in https://symfony.com/doc/current/configuration/override_dir_structure.html  You just ened to override those methods with something like:

```php
```

**Comment by javiereguiluz** [comment]
@woofiewilly I now understand. Here's my opinion about this proposal: I'm not a big fan of env vars because they complicate everything ... but I understand that in some cases they are the best solution.

For config values (e.g. database password) is OK, but for foundational features of the application, such as the `var/` dir location, they look "risky" to me. An external system config (that can fail, be undefined, etc.) changes the behavior of your app dramatically. And it may be really hard to discover what's going on when things don't work as expected.

This reminds me of the PHP options that affect the behavior of the language and can be defined in the php.ini. I' not a big fan of them either.

**Comment by fabpot** [comment]
Env vars are not for configuring the app directories; this would look very wrong to me. But when overriding the `getCacheDir()` directory, you can implement the logic you want, including reading an env vars. So, I'm closing the issue as such a solution will never be part of core.
