### ISSUE TITLE
[Form] No validation violation occurs on invalid values in EntityType. 

### ISSUE THREAD

**Issue by gingerCodeNinja** [symfony/symfony#26389]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.*

No validation violation occurs on invalid values in EntityType. 

This seems to be because EntityType uses ORMQueryBuilderLoader, and it's getEntitiesByIds does not validate that the number of inputs matches the number of outputs. It only does an SQL WHERE IN (provided IDs) query to get whatever values are valid.

To replicate - add an entity in the form type on the form, then either manually delete the entity in the database before submitting, or manipulate the request (POST) data to have invalid values on submit. The invalid values just drop, the valid values remain, and no validation error is raised.

I'm breaking this out from https://github.com/symfony/symfony/issues/17488 as that ticket is specifically addressing that it causes exceptions when using PostgreSQL; however, the bigger issue is that invalid values don't raise any validation.

This is not easy to workaround because $queryBuilder in ORMQueryBuilderLoader is private rather than protected, so the variable and every method in the class needs to be duplicated.

**Comment by xabbuh** [comment]
@gingerCodeNinja Would you be able to write a failing test case that allows to reproduce this bug?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by gingerCodeNinja** [comment]
The problem exists, but I've just not had the time to write a failing unit test. 

The ticket that I branched this off, #17488, has not been closed and also does not have failing unit tests. What criteria is used to determine which tickets to close vs others?

**Comment by xabbuh** [comment]
We do not strictly need a failing unit test. But some instructions on how to reproduce the described issue are needed for anyone wanting to fix a bug.
