### ISSUE TITLE
Web profiler toolbar in 3.4.5 interferes with JQuery Ajax submit

### ISSUE THREAD

**Issue by abzolv** [symfony/symfony#26390]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.5
|JQuery | 3.2.1
| PHP | 7.0.16
| MacOS | High Sierra

Something in the web profiler toolbar of 3.4.5 is breaking the proper functioning of Symfony Form Events.

The problem does not occur when one disables the web profiler toolbar on config.yml, meaning then the form events are triggered as expected. Also, the problem does not occur in v3.4.4 with the web profiler toolbar enabled.

Here's what happens, in short.

There's a form with a ChoiceType field and a JQuery change event that ajax submits the form. On success it replaces a div. Standard stuff, as per the [Symfony documentation](http://symfony.com/doc/3.4/form/dynamic_form_modification.html#form-events-submitted-data).

In 3.4.5 with the web profiler toolbar enabled, the change event fires, but the Ajax request never reaches the controller action (a debug logger at the top of the controller action writes a log entry when the action is opened in the web browser, but does not write a log entry when the change event fires). 

Disable the web profiler toolbar, and the Ajax request reaches the controller (both log entries are written), and the form works as expected. 

Also, go back to 3.4.4 with the web profiler toolbar enabled, and the form also works as expected.

So, logic says something in the 3.4.5 web profiler toolbar code is interfering with the JQuery Ajax submit code.

The view file uses a simple inline Javascript for the change trigger:

```javascript
<script type = "text/javascript" > /*<![CDATA[*/ $('#the_form_choicetype').change(function () {
    var $form = $(this).closest('form');
    var data = {};
    data[$('#the_form_choicetype').attr('name')] = $('#the_form_choicetype').val();
    $.ajax({
        url: $form.attr('action'),
        type: $form.attr('method'),
        data: data,
        success: function (html) {
            $('#the_form_replace_div').replaceWith($(html).find('#the_form_replace_div'));
        }
    });
}); /*]]>*/</script>
```

**Comment by dmaicher** [comment]
See also

https://github.com/symfony/symfony/issues/26380
https://github.com/symfony/symfony/issues/26364

Has been fixed but not released yet.

**Comment by javiereguiluz** [comment]
As @dmaicher said this is sadly a known bug that has been fixed but not released yet as a stable version. Closing as fixed then. Thanks!
