### ISSUE TITLE
UndefinedMethodException setHotPathEvents

### ISSUE THREAD

**Issue by wajaja** [symfony/symfony#26391]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | x.y.z

I get this error by updating symfony from 3.0.9 to 3.4.0 

> Attempted to call an undefined method named "setHotPathEvents" of class "Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass".

is this a symfony bug?
please help me to understand what happens

**Comment by xabbuh** [comment]
Can you provide more information on how we can reproduce your issue? Where is this method getting called (best provide a stack trace for it)? What is the output of `composer show`?

**Comment by wajaja** [comment]
composer show output is: 

$ composer show
alcaeus/mongo-php-adapter            1.1.3                     Adapter to provide ext-mongo interface on top of mongo-php-libary
algolia/algolia-search-bundle        1.0.13                    Seamless integration of Algolia Search into your Symfony project.
algolia/algoliasearch-client-php     1.25.1                    Algolia Search API Client for PHP
beberlei/DoctrineExtensions          dev-master b4dc688        A set of extensions to Doctrine 2 that add support for additional query functions available in MySQL and...
behat/transliterator                 v1.2.0                    String transliterator
bjeavons/zxcvbn-php                  0.3.0                     Realistic password strength estimation PHP library based on Zxcvbn JS
cboden/ratchet                       v0.4.1                    PHP WebSocket library
clue/redis-protocol                  v0.3.1                    A streaming redis wire protocol parser and serializer implementation in PHP
composer/ca-bundle                   1.1.0                     Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
doctrine/annotations                 v1.4.0                    Docblock Annotations Parser
doctrine/cache                       v1.6.2                    Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.4.0                    Collections Abstraction library
doctrine/common                      v2.7.3                    Common Library for Doctrine projects
doctrine/dbal                        v2.5.13                   Database Abstraction Layer
doctrine/doctrine-bundle             1.8.1                     Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.2                     Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.2.0                    Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5                     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1                    Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/mongodb                     1.6.1                     Doctrine MongoDB Abstraction Layer
doctrine/mongodb-odm                 1.1.6                     Doctrine MongoDB Object Document Mapper
doctrine/mongodb-odm-bundle          3.1.0                     Symfony2 Doctrine MongoDB Bundle
doctrine/orm                         v2.5.14                   Object-Relational-Mapper for PHP
elasticsearch/elasticsearch          v6.0.1                    PHP Client for Elasticsearch
evenement/evenement                  v2.1.0                    ├ëv├®nement is a very simple event dispatching library for PHP
exsyst/swagger                       v0.4.0                    A php library to manipulate Swagger specifications
fig/link-util                        1.0.0                     Common utility implementations for HTTP links
firebase/php-jwt                     v4.0.0                    A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friendsofsymfony/elastica-bundle     v5.0.3                    Elasticsearch PHP integration for your Symfony project using Elastica
friendsofsymfony/jsrouting-bundle    2.2.0                     A pretty nice way to expose your Symfony2 routing to client applications.
friendsofsymfony/rest-bundle         2.3.1                     This Bundle provides various tools to rapidly develop RESTful API's with Symfony
friendsofsymfony/user-bundle         v2.1.1                    Symfony FOSUserBundle
gedmo/doctrine-extensions            v2.4.33                   Doctrine2 behavioral extensions
gesdinet/jwt-refresh-token-bundle    v0.3.2                    Implements a refresh token system over Json Web Tokens in Symfony
get-stream/stream                    2.6.0                     A PHP client for Stream (https://getstream.io)
gos/pnctl-event-loop-emitter         v0.1.6                    Pnctl event emitter for event loop
gos/pubsub-router-bundle             v0.3.3                    Symfony PubSub Router Bundle
gos/web-socket-bundle                v1.8.12-rc5               Symfony Web Socket Bundle
gos/websocket-client                 v0.1.2                    WAMP client in PHP
guzzlehttp/guzzle                    6.3.0                     Guzzle is a PHP HTTP client library
guzzlehttp/promises                  v1.3.1                    Guzzle promises library
guzzlehttp/psr7                      1.4.2                     PSR-7 message implementation that also provides common utility methods
guzzlehttp/ringphp                   1.1.0                     Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                   3.0.0                     Provides a simple abstraction over streams of data
imagine/imagine                      v0.7.1                    Image processing for PHP 5.3
incenteev/composer-parameter-handler v2.1.3                    Composer script handling your ignored parameter file
ismaambrosi/generator-bundle         v2.5.0                    Generates Symfony2 documents, forms and CRUD
jdorn/sql-formatter                  v1.2.17                   a PHP SQL highlighting library
jms/metadata                         1.6.0                     Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0                     A library for easily creating recursive-descent parsers.
jms/serializer                       1.11.0                    Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                2.3.1                     Allows you to easily serialize, and deserialize data of any complexity
knplabs/gaufrette                    v0.1.9                    PHP5 library that provides a filesystem abstraction layer
knplabs/knp-gaufrette-bundle         dev-master eec5b70        Allows to easily use the Gaufrette library in a Symfony project
leaseweb/memcache-bundle             v2.1.12                   Memcache Doctrine caching and session storage in the Web Debug Toolbar
lexik/jwt-authentication-bundle      v2.4.3                    This bundle provides JWT authentication for your Symfony REST API
liip/imagine-bundle                  1.9.1                     This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
limenius/liform                      v0.10.2                   Library to transform Symfony Forms into Json Schema
limenius/liform-bundle               v0.10.2                   Bundle for Liform: Transform Symfony Forms into Json Schema
limenius/react-bundle                v0.14.1                   Client and Server-side react rendering in a Symfony Bundle
limenius/react-renderer              v0.14.3                   Client and Server-side React rendering
mongodb/mongodb                      1.2.0                     MongoDB driver library
monolog/monolog                      1.23.0                    Sends your logs to files, sockets, inboxes, databases and various web services
nacmartin/phpexecjs                  v0.8.8                    Run JavaScript code from PHP
namshi/jose                          7.2.3                     JSON Object Signing and Encryption library for PHP.
nc/faye-client                       v1.1.1                    Php client for interacting with faye server
nelmio/api-doc-bundle                v3.1.0                    Generates documentation for your REST API from annotations
nelmio/cors-bundle                   1.5.3                     Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony2 application
nesbot/carbon                        dev-master 21ed8bb        A simple API extension for DateTime.
ocramius/proxy-manager               1.0.2                     A library providing utilities to generate, instantiate and generally operate with Object Proxies
oneup/uploader-bundle                dev-release-1.4.0 ea2804c Handles multi file uploads in Symfony2. Features included: Chunked upload, Orphans management, Gaufrette...
oyejorge/less.php                    v1.7.0.5                  PHP port of the Javascript version of LESS http://lesscss.org
pagerfanta/pagerfanta                v1.0.5                    Pagination for PHP 5.3
paragonie/random_compat              v2.0.11                   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpcollection/phpcollection          0.5.0                     General-Purpose Collection Library for PHP
phpdocumentor/reflection-common      1.0.1                     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    4.3.0                     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve i...
phpdocumentor/type-resolver          0.4.0
phpoption/phpoption                  1.5.0                     Option Type for PHP
pimple/pimple                        v3.2.3                    Pimple, a simple Dependency Injection Container
predis/predis                        v1.1.1                    Flexible and feature-complete Redis client for PHP and HHVM
predis/predis-async                  dev-master 5cd854e        Asynchronous version of Predis
psr/cache                            1.0.1                     Common interface for caching libraries
psr/container                        1.0.0                     Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1                     Common interface for HTTP messages
psr/link                             1.0.0                     Common interfaces for HTTP links
psr/log                              1.0.2                     Common interface for logging libraries
psr/simple-cache                     1.0.0                     Common interfaces for simple caching
ptrofimov/tinyredisclient            1.1.1                     The most lightweight Redis client written in PHP
rase/socket.io-emitter               0.7.0                     A PHP implementation of socket.io-emitter
ratchet/pawl                         v0.3.1                    Asynchronous WebSocket client
ratchet/rfc6455                      v0.2.3                    RFC6455 WebSocket protocol handler
react/cache                          v0.4.2                    Async, Promise-based cache interface for ReactPHP
react/child-process                  v0.5.2                    Event-driven library for executing child processes with ReactPHP.
react/dns                            v0.4.13                   Async DNS resolver for ReactPHP
react/event-loop                     v0.4.3                    Event loop abstraction layer that libraries can use for evented I/O.
react/http                           v0.8.1                    Event-driven, streaming plaintext HTTP and secure HTTPS server for ReactPHP
react/http-client                    v0.5.8                    Event-driven, streaming HTTP client for ReactPHP
react/promise                        v2.5.1                    A lightweight implementation of CommonJS Promises/A for PHP
react/promise-stream                 v1.1.1                    The missing link between Promise-land and Stream-land for ReactPHP
react/promise-timer                  v1.2.1                    A trivial implementation of timeouts for Promises, built on top of ReactPHP.
react/react                          dev-master 327c332        Nuclear Reactor written in PHP.
react/socket                         v0.8.10                   Async, streaming plaintext TCP/IP and secure TLS socket server and client connections for ReactPHP
react/stream                         v0.7.7                    Event-driven readable and writable streams for non-blocking I/O in ReactPHP
react/zmq                            v0.3.0                    ZeroMQ bindings for React.
ringcentral/psr7                     1.2.2                     PSR-7 message implementation
ruflin/elastica                      6.0.1                     Elasticsearch Client
sensio/distribution-bundle           v5.0.21                   Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v5.1.3                    This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.7                    This bundle generates code for you
sensiolabs/security-checker          v4.1.8                    A security checker for your composer.lock
silex/silex                          v2.2.3                    The PHP micro-framework based on the Symfony Components
snc/redis-bundle                     2.0.6                     A Redis bundle for Symfony
stof/doctrine-extensions-bundle      v1.3.0                    Integration of the gedmo/doctrine-extensions with Symfony2
swiftmailer/swiftmailer              v5.4.9                    Swiftmailer, free feature-rich PHP mailer
symfony/event-dispatcher             v3.0.2                    Symfony EventDispatcher Component
symfony/monolog-bundle               v2.12.1                   Symfony MonologBundle
symfony/phpunit-bridge               v2.8.35                   Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.7.0                    Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu            v1.7.0                    Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.7.0                    Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.7.0                    Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.7.0                    Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.7.0                    Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.6.7                    Symfony SwiftmailerBundle
symfony/symfony                      v3.4.0                    The Symfony PHP framework
thruway/client                       0.5.2                     Thruway WAMP client
thruway/pawl-transport               0.5.0                     Pawl WebSocket Transport for Thruway Client
thruway/ratchet-transport            0.5.0                     Ratchet Transport for Thruway
twig/twig                            v1.35.2                   Twig, the flexible, fast, and secure template language for PHP
voryx/thruway                        0.5.2                     Thruway WAMP router core
voryx/thruway-bundle                 dev-master a652337        WebSockets (WAMP2) integration for Symfony2
voryx/thruway-common                 1.0.3                     WAMP2 Common Library for Thruway
webmozart/assert                     1.3.0                     Assertions to validate method input/output with nice error messages.
willdurand/jsonp-callback-validator  v1.1.0                    JSONP callback validator.
willdurand/negotiation               v2.3.1                    Content Negotiation tools for PHP provided as a standalone library.
zendframework/zend-code              2.6.3                     provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager      3.2.0                     Trigger and listen to events within a PHP application
zircote/swagger-php                  2.0.13                    Swagger-PHP - Generate interactive documentation for your RESTful API using phpdoc annotations

**Comment by xabbuh** [comment]
You will need to remove the single `symfony/event-dispatcher` package. The EventDispatcher component is already provided by `symfony/symfony`.
