### ISSUE TITLE
After upgrading from 4.0.4 to 4.0.5 my tests fail since no more routes present.

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony#26392]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.5

After upgrading from 4.0.4 to 4.0.5 my tests fail since no more routes present.

I broke it down to this commit: https://github.com/symfony/symfony/pull/25989

**Comment by iltar** [comment]
Do you have some more information on how your routing is configured?

**Comment by ThomasTr** [comment]
Ok, will try to explain my setup for my controller tests:

My tests have an own Kernel in tests/Controller/app with:

```
    protected function configureRoutes(RouteCollectionBuilder $routes)
    {
        $routes->import(__DIR__ . '/config/routes.yaml', '/', 'glob');
    }
```

then in tests/Controller/app/config/routes.yaml

```
controllers:
    resource: '../../../../src/Controller/'
    type: annotation

logout:
    path: /logout
```

My tests classes extends ControllerTestCase with these methods

```
    /**
     * @return string
     */
    protected static function getKernelClass(): string
    {
        require_once __DIR__.'/app/Kernel.php';

        return 'App\Tests\Controller\app\Kernel';
    }

    /**
     * @param array $options
     *
     * @return mixed|\Symfony\Component\HttpKernel\KernelInterface
     */
    protected static function createKernel(array $options = array())
    {
        $class = self::getKernelClass();

        if (!isset($options['test_case'])) {
            throw new \InvalidArgumentException('The option "test_case" must be set.');
        }

        return new $class(
            static::getVarDir(),
            $options['test_case'],
            isset($options['root_config']) ? $options['root_config'] : 'config.yaml',
            isset($options['environment']) ? $options['environment'] : strtolower(static::getVarDir().$options['test_case']),
            isset($options['debug']) ? $options['debug'] : true
        );
    }
```

with 4.0.4 this setup works fine after upgrade to 4.0.5 i get the errormessage: No route found for xxx

**Comment by xabbuh** [comment]
Could you create a small example application that allows to reproduce the issue? That would be way easier to debug.

**Comment by ThomasTr** [comment]
Hi xabbuh,
here we go: https://github.com/ThomasTr/sf4routes
symfony/framework-bundle is downgraded to 4.0.4 and test pass
after upgrading symfony/framework-bundle to 4.0.5, test fail
don't forget to clear cache in tests/Controller/app/var/cache after upgrading and before testing

Thx for help on this issue on weekend :)

**Comment by ThomasTr** [comment]
@nicolas-grekas : any idea, why this commit https://github.com/symfony/symfony/pull/25989 break my tests?

**Comment by Simperfit** [comment]
I will be looking at this today :).

**Comment by dmaicher** [comment]
I had a look and you are actually using the type `'glob'` incorrectly here :wink: 

https://github.com/ThomasTr/sf4routes/blob/master/tests/Controller/app/Kernel.php#L118

I mean the resource is not a glob pattern but a simple file path?

So with either of those changes it works fine:

```diff
diff --git a/tests/Controller/app/Kernel.php b/tests/Controller/app/Kernel.php
index 1d06ddc..a59e00d 100644
--- a/tests/Controller/app/Kernel.php
+++ b/tests/Controller/app/Kernel.php
@@ -115,6 +115,6 @@ class Kernel extends \Symfony\Component\HttpKernel\Kernel
      */
     protected function configureRoutes(RouteCollectionBuilder $routes)
     {
-        $routes->import(__DIR__ . '/config/routes.yaml', '/', 'glob');
+        $routes->import(__DIR__ . '/config/*', '/', 'glob');
     }
 }
```

or

```diff
diff --git a/tests/Controller/app/Kernel.php b/tests/Controller/app/Kernel.php
index 1d06ddc..25dab04 100644
--- a/tests/Controller/app/Kernel.php
+++ b/tests/Controller/app/Kernel.php
@@ -115,6 +115,6 @@ class Kernel extends \Symfony\Component\HttpKernel\Kernel
      */
     protected function configureRoutes(RouteCollectionBuilder $routes)
     {
-        $routes->import(__DIR__ . '/config/routes.yaml', '/', 'glob');
+        $routes->import(__DIR__ . '/config/routes.yaml', '/');
     }
 }
```

I mean at least this is my understanding. The `GlobFileLoader` only supports actual `glob` patterns and no file paths? Is that correct @nicolas-grekas ?

Before https://github.com/symfony/symfony/pull/25989 it was using a loader from `Symfony\Component\Config\Loader` which seems to behave differently.

**Comment by ThomasTr** [comment]
Thank you very much @dmaicher for investigation. Indeed, this was my error. My tests are all fine now 👍
