### ISSUE TITLE
[DX] Improve `debug:router` command

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#26409]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | all

After I had to do some route debugging, I'd love if the debug console command would be improved. I'm using this all the time and basically never the panel (#26302).

In: `console deb:rout user`
Out: The route "user" does not exist.

In: `console deb:cont user`
Out: Select one ...
In: `123`
Out: What I was looking for.

So I always end in doing a grep:

In: `console deb:rout | grep user`
Out: List of matching routes
In: `console deb:rout the_user_route_i_was_looking_for`
Out: What I was looking for.

Improving the console command to match the behaviour of the container debug command would improve the DX in a nice and simple way.

Cheers
Matthias

**Comment by Simperfit** [comment]
Hey @althaus,

I think I've created a PR for this behaviour, is it really what you need ? 

https://github.com/symfony/symfony/pull/26121

Could you test it and tell me if it's ok for you ? Thanks ;).
