### ISSUE TITLE
Symfony upgrade from 2.7 to 3 version

### ISSUE THREAD

**Issue by jigarpancholi** [symfony/symfony#26404]
Currently I have one project setup and working fully with Symfony 2.7 version. Now I want to upgrade to Symfony 3 version. I have tried to upgrade version but it gives me lots of error with conflict with different bundles. I am following this link https://symfony.com/doc/2.6/cookbook/upgrade/major_version.html.

So please suggest me how to proceed?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
