### ISSUE TITLE
need .htaccess for a symfony 4.0 project

### ISSUE THREAD

**Issue by luxferoo** [symfony/symfony#26419]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

I'm working on a symfony 4.0 project and I'm struggling with .htaccess file for rewriting to public folder.
Host public folder is public_html so the path is : public_hml/public/index.php

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
