### ISSUE TITLE
Make FileException more detailled (or split exception)

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26411]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

If an uploaded file encounter an error, a `FileException` instance like this is thrown: 

```php
The file "5MB.zip" exceeds your upload_max_filesize ini directive (limit is 2048 KiB).
```

The message template is choose thanks to this code part: https://github.com/symfony/symfony/blob/a8dc953279621398a4361c0beeff22c54cc9fce5/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L259-L265

The issue is we don't have any access to the related PHP constant and we have to check the exception compare with string comparison which is not really reliable.

Two solutions:

1. The simplest one: Add the PHP error constant on the `FileException` to make it accessible from the catch.
2. The best (IMO): Create new exception based on the PHP error constant such as `IniSizeFileException` or `FormSizeFileException`.

What do you think?

**Comment by Simperfit** [comment]
IMHO it's better to to create a new exception. 

@Soullivaneuh Do you want to work on it ?

**Comment by Soullivaneuh** [comment]
@Simperfit Not right now I'm afraid. It's just a suggestion. :wink: 

If anybody want to do it, feel free! I'll take a look later if nobody want to carry this issue.

**Comment by fmata** [comment]
@Soullivaneuh I gave a try in #26475
