### ISSUE TITLE
symfony/translation v4.0.6 unexpected ? in construct

### ISSUE THREAD

**Issue by MelinaCahnbley** [symfony/symfony#26425]
Der Test VarDumperTestTraitTest.php wirft bei der neuen Version von symfony/translation folgenden Fehler:

```
In Translator.php line 79:
                                                                             
 Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
```

Wenn ich die vorherige Version 3.4.6 nehme, läuft alles wieder rund.

**Comment by javiereguiluz** [comment]
@MelinaCahnbley thanks for reporting this error. However, we can only support issues written in English. Could you please edit your issue to translate it to English? Thanks!

**Comment by xabbuh** [comment]
@MelinaCahnbley It looks like you are trying to use the component with a PHP version before 7.1 which is the minimum required PHP version for Symfony 4.
