### ISSUE TITLE
FlattenException does not work with Throwable

### ISSUE THREAD

**Issue by instabledesign** [symfony/symfony#26429]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony/Debug  | >=4.0.0

The class [FlattenException](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/Exception/FlattenException.php#L36) doesn't work with Throwable

```php
Symfony\Component\Debug\Exception\FlattenException::create(new TypeError('Bad type error.'));
```
```
TypeError: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of TypeError given, called in /var/www/index.php on line 5 in /var/www/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php on line 36
```

**Comment by stof** [comment]
The Debug component is wrapping Error in FatalThrowableError. `FlattenException::create` was never documented as accepting Error objects directly.

**Comment by instabledesign** [comment]
Yes but it cost nothing to do. Didn't he?

**Comment by ostrolucky** [comment]
Name of the method would be wrong then, wouldn't it? It's called flattenexception, not flattenerror.

**Comment by instabledesign** [comment]
You right. We must rename into `FlattenThrowable` instead.
