### ISSUE TITLE
Missing changelog for new versions

### ISSUE THREAD

**Issue by remicollet** [symfony/symfony#26422]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.36, 3.4.6, 4.0.6

Changelog entries are missing for these newly released versions

**Comment by xabbuh** [comment]
Not sure what you mean, but I can see them [here](https://github.com/symfony/symfony/blame/2.8/CHANGELOG-2.8.md#L10-L13), [here](https://github.com/symfony/symfony/blame/3.4/CHANGELOG-3.4.md#L10-L17) and [here](https://github.com/symfony/symfony/blame/4.0/CHANGELOG-4.0.md#L10-L18).

**Comment by remicollet** [comment]
See https://github.com/symfony/symfony/blob/master/CHANGELOG-4.0.md
Nothing for 4.0.6

**Comment by xabbuh** [comment]
You are looking at the changelog file in the `master` branch where the `4.0` branch just wasn't merged yet. :)
