### ISSUE TITLE
[phpunit-bridge] Cannot autoload class "\Symfony\Bridge\PhpUnit\SymfonyTestsListener"

### ISSUE THREAD

**Issue by yakobe** [symfony/symfony#26430]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.4.5

If you run install `composer install --classmap-authoritative` then running phpunit fails with the error `Class "\Symfony\Bridge\PhpUnit\SymfonyTestsListener" does not exist`. 

The cause seems to be that the class is now just an alias and not a concrete class (see https://github.com/symfony/phpunit-bridge/commit/48139af8d043a785b6f9e46ed0bbe23ee9ef7ebb#diff-7f2565259188dda68869a0605b70c219L33) so composer cannot add this to the class map.

I am nut using simple-phpunit but a the phpunit defined in my composer require-dev because i wish to use `johnkary/phpunit-speedtrap`.

**Comment by yakobe** [comment]
Perhaps it would be enough to just declare the class as before but wrap it in `if (false)` statement?

**Comment by nicolas-grekas** [comment]
> Perhaps it would be enough to just declare the class as before but wrap it in if (false) statement?

looks like a good idea, would you mind sending a PR for this?

**Comment by yakobe** [comment]
I have added a PR to 3.4. I hope that is correct?
