### ISSUE TITLE
Warning: class_implements(): Class 57.1 does not exist and could not be loaded

### ISSUE THREAD

**Issue by aiherrera** [symfony/symfony#26431]
Today I got this error, I tried to clear cache, to delete vendors folder and run the composer install for fresh, I thought maybe could be a corrupted file, but it doesn't fixed the issue. I have not idea on what could be wrong and certainly I've not a clue on what is Class 57.1...

```
(1/1) ErrorException Warning: class_implements(): Class 57.1 does not exist and could not be loaded

in DebugClassLoader.php (line 397)
at DebugClassLoader->getOwnInterfaces('Symfony\\Component\\HttpKernel\\KernelInterface', false)in DebugClassLoader.php (line 217)
at DebugClassLoader->checkClass('Symfony\\Component\\HttpKernel\\KernelInterface', 'D:\\WORK\\api.pendientes.cu\\vendor\\composer/../symfony/http-kernel\\KernelInterface.php')in DebugClassLoader.php (line 159)
at DebugClassLoader->loadClass('Symfony\\Component\\HttpKernel\\KernelInterface')
at spl_autoload_call('Symfony\\Component\\HttpKernel\\KernelInterface')in Kernel.php (line 46)
at require('D:\\WORK\\api.pendientes.cu\\vendor\\symfony\\http-kernel\\Kernel.php')in DebugClassLoader.php (line 145)
at DebugClassLoader->loadClass('Symfony\\Component\\HttpKernel\\Kernel')
at spl_autoload_call('Symfony\\Component\\HttpKernel\\Kernel')in Kernel.php (line 11)
at require('D:\\WORK\\api.pendientes.cu\\src\\Kernel.php')in DebugClassLoader.php (line 145)
at DebugClassLoader->loadClass('App\\Kernel')
at spl_autoload_call('App\\Kernel')in index.php (line 47)
```

**Comment by stof** [comment]
Can you give more details about your setup (PHP version, version of Symfony, etc...) ?

**Comment by aiherrera** [comment]
PHP: 7.1.3
Symfony: 4.0

I created an API and it was working fine, but suddenly it started to give me that error back.

**Comment by aiherrera** [comment]
Ok, the problem has gone. I just restarted my Apache server and that was all... I am really more confused than before, but everything is working well know.

**Comment by alx-web** [comment]
> Ok, the problem has gone. I just restarted my Apache server and that was all... I am really more confused than before, but everything is working well know.

Same problem and same solution!
