### ISSUE TITLE
Validator - how to validate properties that are objects

### ISSUE THREAD

**Issue by mrWodoo** [symfony/symfony#26437]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

Hello, I have a class called Email with property calle Recipient ($recipient), which is an instance of Recipient class, how to validate Email with all of properties including those that are objects?

**Comment by fancyweb** [comment]
Hello, GitHub issues must only be used to discuss new features or to report bugs. For support questions, please use one of the support channels : https://symfony.com/support

And what you're looking for is the Valid constraint : https://symfony.com/doc/current/reference/constraints/Valid.html
