### ISSUE TITLE
Autowiring trying to wire explicitly set primitive type in construct

### ISSUE THREAD

**Issue by MichaelHindley** [symfony/symfony#26434]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I have a simple class with a property that accepts it through constructor injection.

![image](https://user-images.githubusercontent.com/1016639/37064167-e704469a-2169-11e8-9850-06528a4ebb82.png)

I would expect auto-wiring to not try to wire the primitive string property, instead it throws an error that the property needs to have a type-hint, even though the type is explicitly defined.

Error:
```
Cannot autowire service "App\Domain\Client\ClientRequest": argument "$title" of method "__construct()" must have a type-hint or be given a value explicitly.`

**Comment by MichaelHindley** [comment]
I noticed in docs that this behaviour is intended, strange as that may seem

**Comment by stof** [comment]
The issue here is that the error message is confusing. In case we have a non-class typehint, we should not say that it must have a type hint, but use a different message instead /cc @weaverryan @nicolas-grekas
