### ISSUE TITLE
Synthetic services with on-invalid does not work

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#26440]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.31

I am currently trying to inject a synthetic service, to a another service. The synthetic service is later in the request available, so its throws normal a exception "You have requested a synthetic service" which makes sense. But i if apply on-invalid to the argument with null, the exception is also thrown.

Example:
```xml
<service id="shop" class="Shopware\Models\Shop\Shop" synthetic="true"/>

<service id="bla.configuration" class="Shopware\Components\Plugin\CachedConfigReader">
     <factory service="shopware.plugin.cached_config_reader" method="getByPluginName"/>
     <argument type="string">CoeArticleRatingOptIn</argument>
     <argument type="service" id="shop" on-invalid="null"/>
</service>
```

Actual:
You have requested a synthetic service ("shop"). The DIC does not know how to construct this service.

Expected:
It injects null until the synthetic service is set.

**Comment by stof** [comment]
Setting synthetic services late is generally a bad idea, as any services wanting to use them will **not** be recreated or updated after set the synthetic service.

So even if we fix this to consider than a synthetic service not set yet is invalid (not sure we should do it, as we are currently able to deal with `on-invalid="null"` at compile-time in Symfony 4 IIRC), it might still not work for you.

**Comment by nicolas-grekas** [comment]
I agree with @stof, behaving like that would make the logic very context sensitive. Not sure it's legitimate.

**Comment by nicolas-grekas** [comment]
Closing as discussed, this is expected behavior.
