### ISSUE TITLE
Randomly/intermittently being logged out since upgrade to 3.4.4

### ISSUE THREAD

**Issue by ReSpawN** [symfony/symfony#26454]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.4

Ever since we've updated from 3.3.10 to 3.4.4 we've been getting numerous complaints, next to experiencing it ourselfs, that people are randomly being logged out of the application. The problem seems to occur every hour, but we cannot be sure of that since testing that is a very tedious process. 

We actually haven't changed any settings since 3.3.10 that are bound to session management so we're at a loss as to what might be causing this problem. We've removed various bundles to be sure, like the Scheb TwoFactor bundle but to no success. 

The log's don't give any hints, besides saying the following: 

```
[2018-03-08 09:37:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-03-08 09:37:31] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:68)"} []
[2018-03-08 09:37:31] security.DEBUG: Calling Authentication entry point. [] []
```

Can anybody point me in the right direction? Or might this actually be a bug in the upgrade?

**Comment by ReSpawN** [comment]
Debugging with two heads at this time points towards cookie_lifetime not being updated. We've set it to 20, clicking around vigorously still logs us out after 20 seconds, no matter the activity.

**Comment by ReSpawN** [comment]
We've traced it down to the cookie_lifetime being set to an absolute 3600 seconds. This value is static. Our server php's INI has the value 0 as well as the old server, but this was overwritten by Symfony.

We absolutely have no idea why one would use this setting like this. Setting it to null when PHP's setting is also 0 solves the problem. Otherwise, forcibly setting it to 0 in Symfony's config works as well.

**Comment by rpcabrera** [comment]
Meanwhile, can you share some solutions like that you've mentioned about migrating the session or overriding PHP and Symfony settings? I'm in same issue but can't wait for an upgrade solution.

**Comment by theredled** [comment]
I'm having this issue too with SF 4.3.
