### ISSUE TITLE
Environment variables are not inherited when $_ENV is empty

### ISSUE THREAD

**Issue by hongaar** [symfony/symfony#26451]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | not sure
| RFC?             | no
| Symfony version  | >=3.3

It looks like starting with version 3.3.x in the `symfony/process` component, there's an issue with inheriting environment variables when `$_ENV` is empty - which is the recommended setup for production systems (see http://php.net/manual/en/reserved.variables.environment.php#98113).

Could be solved by including an extra loop with `getenv()` in `Process::getDefaultEnv()`, but not sure if there's a rationale to not do this.

This bug might cause hard to find bugs - i.e. I discovered this issue after debugging an issue for hours where a headless chrome instance wouldn't listen to the specified port when ran with `--remote-debugging-port=9222`, turned out it was missing some - apparently - critical env vars.

Reproduce:

```php
$_ENV = [];
$process = new PhpProcess(<<<EOF
<?php var_dump(getenv()); ?>
EOF
);
$process->setEnv(getenv()); // <-- comment out this line to see bug
$process->run();

echo "<pre>".$process->getOutput();
```

_Edit_: seems to conflict with #25559, though I think that could be solved by introducing a loop and filtering out all non-string values, like in the other loops.

**Comment by nicolas-grekas** [comment]
The env is inherited using the values in both `$_SERVER` and `$_ENV`. `getenv()` is not used because it is not available in PHP 5.5, and it shouldn't be needed since either `$_SERVER` or `$_ENV` contain the env vars. If you modify these arrays, it's your responsibility to do it wisely I believe.

**Comment by hongaar** [comment]
If I'm not mistaken, `getenv()` is around since PHP 4 😉 

On the other hand, `$_ENV` is unavailable on production systems using [`php.ini-production`](https://github.com/php/php-src/blob/PHP-5.5.10/php.ini-production#L612).

**Comment by nicolas-grekas** [comment]
getenv() with no arguments exists only since 7.1. $_SERVER also contains the env vars.

**Comment by hongaar** [comment]
Snap, I missed that from the docs. Thanks for the clarification.

**Comment by hongaar** [comment]
I think I traced it down to being an issue with PHPs [built-in web server](http://php.net/manual/en/features.commandline.webserver.php).

```php
<?php
# test.php
var_dump($_SERVER);
var_dump($_ENV);
var_dump(getenv());
```

And run with `php -S 0.0.0.0:88 test.php` results in:

```
array(23) {
  ["DOCUMENT_ROOT"]
  // ... some more server vars, without env vars
}
array(0) {
}
array(62) {
  ["PATH"]
  // ... all env vars
}
```

A simple workaround for this would be (granted you're on PHP >= 7.1):

```php
if (php_sapi_name() === "cli-server") {
    $_ENV = getenv();
}
```
