### ISSUE TITLE
KernelInterface::locateResource has not been upgraded to take Symfony 4 bundle less folder structure in mind

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#26457]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

https://github.com/symfony/symfony/blob/d79c528b400eaeecc53e97cc4c5f3cbf7df33650/src/Symfony/Component/HttpKernel/KernelInterface.php#L70-L79

**Comment by chalasr** [comment]
What do you suggest? Bundles still exist and can provide resources, especially 3rd party ones

**Comment by ostrolucky** [comment]
I suggest to fall back to project_dir if no bundle prefix has been provided

**Comment by stof** [comment]
Well, I suggest not using the `Kernel::locateResource` API at all to locate something which is not part of a bundle. There is no need for custom logic in such case (as there would not be ways to override the resource in such case).

**Comment by ostrolucky** [comment]
Ok, so is this by design? Might be worth to make it more obvious, I genuinely thought bundle specific checks were just forgotten there.

There is also this https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/KernelInterface.php#L21

Every project, even Symfony 4 one relies on implementing this class.

**Comment by stof** [comment]
Well, bundles are not dead in Symfony 4. They are just not recommended anymore for *project* code. So locating bundle resources still make sense in Symfony 4.

**Comment by ostrolucky** [comment]
By bundle specific checks I mean conditions specifically preventing use in non-bundle environment.

It seems weird because Symfony 4 *project* code is not a bundle, but [extends](https://github.com/symfony/recipes/blob/6a6b3f98a15c8c2f8b566b6364db4dcd044affcb/symfony/framework-bundle/3.3/src/Kernel.php) class meant to *manage an environment made of bundles* regardless. 

This is just semantics, but if you don't want to make methods provided there available in non-bundle environment, maybe descriptions like such should be changed.

**Comment by Tobion** [comment]
@ostrolucky feel free to provide a PR making it more understandable

**Comment by ostrolucky** [comment]
This issue is still marked as unconfirmed so not sure what kind of fix is welcome.

Ideally, locateResource should be deprecated and replaced with locateBundleResource, or make it work in bundle-less environment.

Removing misleading class description of course as well.

**Comment by Tobion** [comment]
It's not worth to change the method name but clarifying the phpdoc could be done.
