### ISSUE TITLE
[Form] Add Bootstrap 4 style for field FileType

### ISSUE THREAD

**Issue by ArmRes** [symfony/symfony#26464]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 

Add Bootstrap 4 style for field FileType
https://getbootstrap.com/docs/4.0/components/forms/#file-browser

**Comment by zzenmate** [comment]
I am going to do it, but I just started. PR: https://github.com/symfony/symfony/pull/26502
