### ISSUE TITLE
Methor getClientIp() dont return real IP address

### ISSUE THREAD

**Issue by PopcornPHP** [symfony/symfony#26466]
Hi! I'm trying getClientIp() , but this methon dont return real client IP address. On my VestaCP server, with apache, nginx and settings by default, this function return current server IP, not user IP. All users have same IP address.

But I found decision:
[https://stackoverflow.com/questions/1634782](https://stackoverflow.com/questions/1634782)

This function return real user IP address.

Can you fix this problem? Because many frameworks and CMSs using your package as vendor, and this problem must be resolve on the lower level.

Thank you!

**Comment by xabbuh** [comment]
If your application runs behind a proxy server, you need to configure Symfony accordingly to allow it to determine the real client IP address (see https://symfony.com/doc/current/deployment/proxies.html).
