### ISSUE TITLE
Session lost after multiple refresh

### ISSUE THREAD

**Issue by BinovaYasmina** [symfony/symfony#26462]
Hello,
I'm using Symfony 3.4 with php 7 and I wonder if the symfony session doesn't quite work. Everything works well except one thing. When I'm entering correct credentials, the profiler first shows that I am correctly logged in. However, on the next page, zap! (e.g. if I refresh the page, or after being redirected) I become anonymous again, my page contains many ajax calls

I have made a dummy action that simply dumps the $this->get('session');, after refreshing, let say two times in a row, all the session is cleared, and the session file is deleted even if the session id is always the same, I've also made another script that displays the global variable $_SESSION, here everything goes fine, and the session lives correctly.

I wonder if it is a problem in my server, or I just missed something, even if  in php.ini I put the directive session.auto_start to false

Thank you in advance

**Comment by qwarnant** [comment]
Same for me, the security log says that the user became not authenticated and then, redirect me to the login page. Only one page is affected on my site but the page and the route annotations are not different from another. 

The bug occurred after the upgrade of Sf 3.4.5 to 3.4.6 this morning.  

**Rollback in 3.4.5 to fix the issue **

**Comment by xabbuh** [comment]
Can you please provide a small example application that allows to reproduce your problem?

**Comment by BinovaYasmina** [comment]
this is the dumps I have made, after, let say 5 refreshes all the session is gone...
/**
     * @Route("/testSession.html", name="test_session")
     * @Template()
     */
	public function testSessionAction(Request $request){
		$session = $this->get('session');
		dump($session->getId());
		dump($session->getName());
		dump($session->getMetadataBag());
		$session->set('test' . date('Y-m-d h:i:s'), ['test - key'=>'test - value']);
		dump($_SESSION);
		dump($session->all());
		
		dump(strlen( serialize( $_SESSION ) ));
		return new Response('END TEST');
	}

and in fact I've put symfony back to 3.4.5 but nothing changes,

**Comment by timothee-pinon** [comment]
i have exactly the same bug

**Comment by BinovaYasmina** [comment]
Hello,

I have finally found the source of my problem, it is the Suhosin module that was installed on the server, I have just desactivated it and all goes fine.

Hope this will fix your problem too,

Regards..

**Comment by amigainc** [comment]
I have the same issue on Symfony 5.0+, it happens on **asynchronous Ajax requests** or if I click quickly on links before the server request returns the template. 
Suhosin module is not installed.
My first solution was to force synchronous Ajax requests, but I'd be interested to avoid this behaviour.
Regards.

**Comment by oriole9g** [comment]
Same problem with SYmfony 4.4 :(
