### ISSUE TITLE
Profiler bar breaks jquery.ajax calls

### ISSUE THREAD

**Issue by villalvilla** [symfony/symfony#26460]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.4.5

Hi,
I've checked very basic behaviour with last version of jquery (it also happens with previous versions, at least till v1.9 of jquery, that I had in another installation) and if you activate profiler and try to call a very simple ajax function with jquery, javascript is unable to find callback and doesn't fire request to the server. I've been able to reproduce it with a very simple code. 

I have to say that I use bootstrap 3 in my webpages, and this could be related to previous issues with profiler version 2.8+ (just for you to keep in mind).

Hope this helps

**Comment by iltar** [comment]
Have you checked if there's a new version available? :wink: 

http://symfony.com/blog/symfony-3-4-6-released

**Comment by villalvilla** [comment]
Just updated to 3.4.6 and can confirm that it works now. Thanks for your help
