### ISSUE TITLE
[DoctrineBridge] BC Break dropping memcache type

### ISSUE THREAD

**Issue by rubenrua** [symfony/symfony#26479]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.2

`symfony/doctrine-bridge` 4.0.2 drops memcache type. Where is the Backward Compatibility Promise? Memcached type is used instead, but IMHO it's a big change to do in a patch release.

Commit https://github.com/symfony/doctrine-bridge/commit/d14c17af9290634eb1588b75ed64a64ee286ba3e.

This change breaks the [DoctrineMongoDBBundle travis CI](https://travis-ci.org/doctrine/DoctrineMongoDBBundle/builds/324947053?utm_source=github_status&utm_medium=notification)

Origin: https://github.com/doctrine/DoctrineMongoDBBundle/pull/451

**Comment by sstok** [comment]
See https://github.com/symfony/symfony/pull/25409 this was removed because there is no memcache in PHP 7 which is the minimum version of Symfony 4 so this wouldn't have worked already.

**Comment by rubenrua** [comment]
<irony>Looks like a Backward Compatibility Break in PHP </irony>

Thank you.
