### ISSUE TITLE
[phpunit-bridge] DeprecationErrorHandler doesn't catch deprecation triggered by SymfonyTestListenerTrait

### ISSUE THREAD

**Issue by bojanz** [symfony/symfony#26476]
PHPUnit 6.5.7, Symfony 3.4 via Drupal 8.5.0

Testing deprecation messages locally, I keep getting "Legacy deprecation notices (6)" instead of the expected "Remaining deprecation notices (6)" followed by the actual notices.

Jumping into DeprecationErrorHandler, I have found that the problem is here:
```
if (isset($trace[$i]['object']) || isset($trace[$i]['class'])) {
                if (isset($trace[$i]['class']) && in_array($trace[$i]['class'], array('Symfony\Bridge\PhpUnit\SymfonyTestsListener', 'Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListener'), true)) {
```
The second IF parses the message, but it's never triggered.  If I replace the condition with TRUE, I get the expected behavior. The condition fails because $trace[$i]['class'] on my machine points to Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV6, not the aliased version.

debug_backtrace() seems to always return unaliased classes, so how is the condition expected to work? What am I missing?

**Comment by bojanz** [comment]
This looks like a regression introduced in 3.4.5 by 48139af8d043a785b6f9e46ed0bbe23ee9ef7ebb.

Downgrading my symfony/phpunit-bridge from 3.4.6 to 3.4.4 resolves the problem.

**Comment by nicolas-grekas** [comment]
@bojanz up for a PR to fix the issue?

**Comment by bojanz** [comment]
Thank you! Sorry, march has been busy with travel, lost sight of this issue.
