### ISSUE TITLE
[DI] Loop during container build regression in 4.0.5

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony#26471]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6, 4.0.5

I have hard time reproducing it in a minimal.  But maybe it will remind something for dependency injection gurus like @nicolas-grekas :D

- Service `Foo`, has the service `doctrine.orm.entity_manager` as only argument
- Service `Bar`, has the service `Foo` as only argument, but has tag `doctrine.event_listener`.

The built container does the following loop:

1. `getDoctrine_Orm_DefaultEntityManagerService`
2. calls `getDoctrine_Dbal_DefaultConnectionService`
3. calls `getServiceFoo`
4. calls `getDoctrine_Orm_DefaultEntityManagerService`, get back to 1

It was working in 4.0.4, but not anymore in 4.0.6

**Comment by magnetik** [comment]
Adding `lazy=true` to the `doctrine.event_listener` fixes it. But it was working anyway before.

**Comment by stof** [comment]
having it working in 4.0.4 but not 4.0.6 looks weird to me if there is no other changes. If none of the services are lazy, this kind of circular references should be forbidden in both versions (and it cannot be instantiated)

**Comment by magnetik** [comment]
Hum, I face this in symfony 4.0.4 indeed, my previous test was bad somehow.

Is it possible that this was working in SF 3.4? This is a project ported from 3.4.

**Comment by nicolas-grekas** [comment]
Feels suspicious.
We'd need a reproducer to work on this if there is any persistent issue.
Eg some repo that work with 3.4, but not with 4.0

**Comment by dkarlovi** [comment]
I've seem to have been bitten by the same issue. In my case, if you typehint a `Doctrine\Common\Persistence\ManagerRegistry` (interface) for your Doctrine listener, it leads to a undetected circular dependency.

What I actually wanted was `Doctrine\Bundle\MongoDBBundle\ManagerRegistry` (class).

It might be dependendt on something else in my repo so will try to extract it.

**Comment by xabbuh** [comment]
@dkarlovi Which version of the DoctrineBundle do you use? There used to be an alias for the interface defined by the bundle which was removed in doctrine/DoctrineBundle#740, but which wasn't part of a release yet.

**Comment by dkarlovi** [comment]
@xabbuh 1.8.1.

**Comment by xabbuh** [comment]
Okay, let's close for now then.
