### ISSUE TITLE
Option to dump ~ yaml key on null value

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26497]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

https://github.com/symfony/symfony/blob/9e82562948253bf547243aa1c4cf6ec734d608da/src/Symfony/Component/Yaml/Inline.php#L159-L160

The `null` keyword is the only one used if the value is null. It would be great to have a flag to use `~` instead.

**Comment by fabpot** [comment]
I'm closing as won't fix here as I don't see why we should make this configurable. Both are equivalent.
