### ISSUE TITLE
Environment and Console Component

### ISSUE THREAD

**Issue by t-veron** [symfony/symfony#26492]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.6

I've juste updated my project to Symfony 3.4.6 and the console component seems have a bug. In fact when I execute command like

`bin/console c:c -e=prod
`

I have this error

```
In FileLocator.php line 44:

  The file "/var/www/[my_project]/app/config/=prod/config.yml" does not exist.

```

I've noticed that the method getParameterOption of ArgvInput's class have been refactored. This refactor seems to be the cause of the bug.

**Comment by xabbuh** [comment]
see #26378
