### ISSUE TITLE
[Console] Command aliases are ignored when using the console.command tga

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26495]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

*Reported originally by @hacfi in https://github.com/symfony/symfony-docs/issues/9421*

I just noticed that using the `console.command` tag command aliases set via `setAliases` in `configure` are not taken into account. [Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php) needs to call `getAliases` of each command instance.

**Comment by hacfi** [comment]
@javiereguiluz Thanks! I will try to find some time to work on this by the end of the week. As it’s a bug: PR against 4.0 or 3.4?

**Comment by chalasr** [comment]
`AddConsoleCommandPass` cannot call `getAliases()` for each command, services are only definitions at this stage (compile time), not instances. 
About the issue, it should only happen for lazy commands (i.e. when you set the command name via `protected static $defaultName` or the `command` attribute on the `console.command` tag), in this case the way right way to set aliases is to add one tag per alias.

**Comment by hacfi** [comment]
Personally I would expect that aliases would be automatically registered too when using the `console.command` tag so the need to add multiple tags with each alias should be properly documented then.

**Comment by chalasr** [comment]
Yes, reopening the documentation issue and closing this one.
