### ISSUE TITLE
Symfony 3.4.6 CSRF-Token invalid

### ISSUE THREAD

**Issue by mark-wolff** [symfony/symfony#26507]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  | 3.4.6

I use Symfony 3.4.6 with PHP 7.1.15.  After update to 3.4.6 the CSRF-Token is always invalid. The Problem only appears in prod Enviroment. In dev everything works fine.

**Comment by derrabus** [comment]
Can you create a small Symfony project that reproduces the problem?

**Comment by lostfocus** [comment]
Okay, _mea culpa_ - I'm the colleague of @mark-wolff who messed it up, the issue was completely unrelated to the update from 3.3 to 3.4. This can be closed as invalid.
