### ISSUE TITLE
Entity Manager return repository with old entity manager after entity manager reset

### ISSUE THREAD

**Issue by DangerLifter** [symfony/symfony#26503]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

There are entities Product and Category with Many-to-One relation. In controller multiple products added in a loop. Each product is assigned to same category, which is loaded before loop. Product has unique field in database, so in loop "UniqueConstraintViolationException" is caught and loop going further with next product. Because exceptions causes entity manager to be closed there is code in cycle to reset manager if need it:

```php
if (!$em->isOpen()) {
    $em = EntityManager::create(
        $em->getConnection(), $em->getConfiguration()
    );
    // have to reload entity after recreate entity manager
    if ($category) {
        //$category = $em->getRepository(Category::class)->find($category->getId());
        //$category = $em->find(Category::class, $category->getId());
    }
}
```
As category loaded once before loop it needs to be reloaded for new entity manager. If 
`$category = $em->getRepository(Category::class)->find($category->getId());` is used it does not work and causes 

> Product "" error: A new entity was found through the relationship 'App\Entity\Product#category' that was not configured to cascade persist operations for entity: App\Entity\Category@00000000380b58f9000000004390b330. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\Category#__toString()' to get a clue..

But it correctly works with usage
`$category = $em->find(Category::class, $category->getId());`

As I found it happens because $em->getRepository(Category::class) returns repository with old instance of entity manager.

**Comment by iltar** [comment]
This is not an issue in Symfony though, you'll have to check-in with the [Doctrine repository](https://github.com/doctrine/doctrine2/).

My advice would be to query before you insert and avoid the constraint exception, if you intend to insert a batch this way.
