### ISSUE TITLE
Visual Studio Extension

### ISSUE THREAD

**Issue by bm-stschneider** [symfony/symfony#26505]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Will the be a Visual Studio Code Extension for Symfony in the near future?

**Comment by xabbuh** [comment]
I am not aware of someone working on such an extension (I don't even think that I know someone who uses Visual Studio). Anyway, the development of an IDE extension would surely have to happen outside the Symfony core code and would be independent of the framework. Thus I am going to close here as there is nothing we can do in the core.

**Comment by bm-stschneider** [comment]
Ok, I understand, I also forgot the 'Code' in the title :)

**Comment by javiereguiluz** [comment]
@bm-stschneider Visual Studio Code is an amazing editor (some might even say IDE!) and it's increasingly popular. A great extension, like the PhpStorm Plugin, would be great. Maybe you can ask in the Symfony Slack (https://symfony.com/support) to see if there's interest in the community to work on such a feature. Thanks!
