### ISSUE TITLE
Dump don't working

### ISSUE THREAD

**Issue by marek5816** [symfony/symfony#26500]
I trying to dump some values, but issue is that when I use dump, it don't show any error message and don't dump any value. I have installed symfony/var-dumper.
Source code - https://pastebin.com/196JGbAd

**Comment by lxg** [comment]
This is not a support forum. If you think this is a bug in Symfony, you explain how specifically Symfony is broken. If you have a problem with your implementation, please try to find help at sites like StackOverflow.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
