### ISSUE TITLE
Config\Resource\ReflectionClassResource have not needed dependencies on EventSubscriberInterface

### ISSUE THREAD

**Issue by mpoiriert** [symfony/symfony#26501]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | >= 3.4.5

There is a dependency on **Symfony\Component\EventDispatcher\EventSubscriberInterface** in **Symfony\Component\Config\Resource\ReflectionClassResource**.
I am using the config and dependency-injection components and when trying to compile/dump the container I get a exception. Same thing would happen on **Symfony\Component\DependencyInjection\ServiceSubscriberInterface**.

Those if should also have a class_exists check:

```php
 if ($class->isSubclassOf(EventSubscriberInterface::class)) {
            yield EventSubscriberInterface::class;
            yield print_r(\call_user_func(array($class->name, 'getSubscribedEvents')), true);
        }

        if ($class->isSubclassOf(ServiceSubscriberInterface::class)) {
            yield ServiceSubscriberInterface::class;
            yield print_r(\call_user_func(array($class->name, 'getSubscribedServices')), true);
        } 

```

**Comment by nicolas-grekas** [comment]
Will be fixed by #26400
