### ISSUE TITLE
[RFC] Resolving environment variables inside another one

### ISSUE THREAD

**Issue by julienfalque** [symfony/symfony#26522]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

Using the `resolve` environment variable processor, one may use parameters in the value of an environment variable, e.g. `FOO="%foo%"`. But this doesn't work to reference an environment variable inside another one:

```
FOO="foo"
BAR="%env(FOO)%/bar"
```

This is because the processor expects the literal parameter `env(FOO)` to exist. So it only works if the parameter is explicitly defined:
```yaml
parameters:
    env(FOO): "%env(FOO)%"
```

I think it would be nice to allow this to work without defining the parameter. Is this requirement intended? If not, would you consider this a bugfix or a new feature?

**Comment by Tobion** [comment]
what's the use-case?

**Comment by julienfalque** [comment]
I have an environment variable to define a base URI and another one to define the URI of a specific page:
```
FOO_BASE_URI="http://foo"
FOO_SOME_PAGE_URI="%env(FOO_BASE_URI)%/bar"
```

**Comment by xabbuh** [comment]
```
FOO_BASE_URI="http://foo"
FOO_SOME_PAGE_URI="%env(FOO_BASE_URI)%/bar"
FOO_RESOLVED="%env(resolve:FOO_SOME_PAGE_URI)%"
```

Something like that does not work?

**Comment by julienfalque** [comment]
I use `'%env(resolve:FOO_SOME_PAGE_URI)%'` to inject the `FOO_SOME_PAGE_URI` variable into a constructor argument of a service. This results in an exception being thrown:
```
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "env(FOO_BASE_URI)" must be defined.
```
which is why I have to either create the parameter or stop using `%env(FOO_BASE_URI)%` in `FOO_SOME_PAGE_URI`.

**Comment by Tobion** [comment]
I would not recommend concatenating URI parts in env variables. Better use a PSR-7 library for real uri manipulation like https://github.com/guzzle/psr7
So I would consider this use case not valid.

**Comment by fabpot** [comment]
I don't think this needs to be supported. Env vars are not a replacement for parameters. They should only be used for things that change per environment (I don't think this is the case here, right?).

**Comment by julienfalque** [comment]
It is the case: both variables I use hold full URIs used to redirect the user at some point. The URLs vary depending on the environment.

I didn't want to have something like `FOO_HOST`, `FOO_PATH` and make the code concatenate them because that would be assuming that both redirect URIs share the same hostname (one redirecting to `/` and the other redirecting to `FOO_PATH`). I wanted to be able to specify completely unrelated URIs if needed. It also simplifies the code as I can inject the full URIs in the services that use them without any extra processing.

**Comment by fabpot** [comment]
Sorry, I missed one important thing in my description. Something that depends on the environment should be done with parameters. Env vars are for things that can **dynamically** change. For instance, a DB URL. It might change without a new deployment. That makes it perfect for an env var as Symfony would take the new value immediately (the env var values are never dumped into the cache and read at runtime for each request). As you can see, that makes the use case for env vars very tiny and very specific. Another use case is for secrets that should not be stored in the main code source tree.

**Comment by francoispluchino** [comment]
There is a use case that this feature witch would simplify the DX, and knowing that in this use case, the environment variables do not replace the parametres. See the issue #32021.
