### ISSUE TITLE
Register bundles not working as expected (or not well documented)

### ISSUE THREAD

**Issue by tburschka** [symfony/symfony#26526]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 3.4, 4.0

Im facing currently the problem that the condtion to load a bundle in the kernel method registerBundles not work as the bundles.php maybe intends it.

Example:

```php
// CASE 1: this loads the bundle every time
Symfony\Bundle\DebugBundle\DebugBundle::class => ['all' => true]

// CASE 2: this loads the bundle on dev and test 
Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' =>true]

// CASE 3: this should not load for test, but it's loaded, since the isset condition gets false, and false !== null
Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => false, 'prod' => true]

// CASE 3.5: this should load for all, except for prod, but it's loaded since the or conditons is always true
Symfony\Bundle\DebugBundle\DebugBundle::class => ['all' => true, 'prod' => false]
```

In my opinion it should looks like this (i know, this implementation it can throw notices)

```php
        foreach ($contents as $class => $envs) {
            if ($envs[$this->environment] === true || ($envs['all'] === true && (!isset($envs[$this->environment]) || $envs[$this->environment] !== false))) {
                yield new $class();
            }
        }
```

to "fix" the cases 3 and 3.5. In addition it's alsow allow blacklist a bundle for specific environments.

**Comment by Tobion** [comment]
Please open the issue on https://github.com/symfony/recipes as the code you are referring to is from https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php Thanks
