### ISSUE TITLE
Password authentication not correct

### ISSUE THREAD

**Issue by SimonRininsland** [symfony/symfony#26525]
https://github.com/symfony/symfony/blob/9e82562948253bf547243aa1c4cf6ec734d608da/src/Symfony/Component/Security/Core/Authentication/Provider/LdapBindAuthenticationProvider.php#L77

We found an Issue with this Line. If removing the password input field in the DOM Symfony gets a null here. But NULL compared to '' is not true - so it seems okay and throws no Error. 
Checking the password with an "empty($password) === true)" solves the Issue.

**Comment by ismail1432** [comment]
I don't try to reproduce the bug, but this condition `if(empty($password))` make sense for me [empty](http://php.net/manual/fr/function.empty.php)
