### ISSUE TITLE
[RFC] Predefined conditions in route parameter requirements

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#26524]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Often enough when defining a route, you want a certain condition bound to your parameter. Often those conditions are a digit, a set of alpha-numerical characters or maybe even a uuid. The gives a lot of repetition and chances of faulty conditions.

It would be nice if we could add some predefined conditions in the form of configuration via either the application or provide it via a bundle. The discussion on slack:

@Taluu 
> What could be good IMO could be to be able to set "default requirements" on routes. We have a lot of `"requirements"={"id"="[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"}` in our routes (uuids), so being able to have a kind of template / default "for `id`, if not specified otherwise, use this requirement"

@iltar 
> the ability to refer to predefined conditions would be nice
> `@Route("/foo/{bar<:uuid>}/")`

@nicolas-grekas 
> using subroutines, we could make it `@Route("/foo/{bar<(?&uuid)>}/")` https://pcre.org/current/doc/html/pcre2syntax.html#SEC21
> we would "just" need a way to define subroutines
> please open an issue if you want to keep track of the idea

This in reference to the awesome feature that nicolas is working on: #26518

**Comment by ostrolucky** [comment]
For inspiration, Django calls these "Path converters" https://docs.djangoproject.com/en/2.0/topics/http/urls/#path-converters

> The following path converters are available by default:
> 
>     str - Matches any non-empty string, excluding the path separator, '/'. This is the default if a converter isn’t included in the expression.
>     int - Matches zero or any positive integer. Returns an int.
>     slug - Matches any slug string consisting of ASCII letters or numbers, plus the hyphen and underscore characters. For example, building-your-1st-django-site.
>     uuid - Matches a formatted UUID. To prevent multiple URLs from mapping to the same page, dashes must be included and letters must be lowercase. For example, 075194d3-6885-417e-a8a8-6c931e272f00. Returns a UUID instance.
>     path - Matches any non-empty string, including the path separator, '/'. This allows you to match against a complete URL path rather than just a segment of a URL path as with str.
>

**Comment by Taluu** [comment]
This isn't really what I had in mind (I had something like a `_defaults` as it is done on the DIC), but still, this looks like a good idea. So :+1:

**Comment by iltar** [comment]
The path converters seem like a mix of parameter matching and argument value resolvers :thinking:

**Comment by nicolas-grekas** [comment]
we could just create a special entry in configuration files, eg.:
```
_subroutines:
    yyyymmdd: \d{4}-\d{2}-\d{2}
    uuid: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
```

that would allow bundle or core to provide some, and you to add more, the last overwrites the previous as usual.

**Comment by javiereguiluz** [comment]
I don't like this much. The reason is that Django-like converters look confusing to me. I would always need to double check the details. Example: does `int` allow negative numbers or not? It does not ... but why? A negative integer is an integer too! Same with `str` ... does it allow empty strings? If not, why not? An empty string (`''`) is always considered a string in PHP, etc.

The only converter that I'd find useful is the `uuid`one, because the related regex is a monstrosity.

-----

My advice would be to not implement this in 4.1 ... let's merge the other PR, test it for real in 4.1 and we can improve it in 4.2 with this or other ideas.

**Comment by iltar** [comment]
I have no problems waiting for 4.2 :+1: I personally won't have time to try and build this before 4.1 either way.

**Comment by Taluu** [comment]
IMO the subroutine shouldn't be supported only on the inline definition, but also supported in the `requirements` of a Route more globally, such as

```
@Route(
    path='/foo/bar/{id}',
    requirements={
        "id"="&uuid"
   }
)
```

(the options are probably not adequately named, but you get the idea)

**Comment by nicolas-grekas** [comment]
Downvoting Django-style because we don't want any conversion. Still fine with subroutines, for 4.1 is fine, that's quite easy to add.

**Comment by nicolas-grekas** [comment]
> subroutine shouldn't be supported only on the inline definition

this proposal is 100% decoupled to inline definition. so obviously yes, it should be supported in both styles

**Comment by javiereguiluz** [comment]
Maybe it's because I'm too old ... but "subroutine" doesn't look like a very descriptive name for this feature:

> In computer programming, a subroutine is a sequence of program instructions that perform a specific task, packaged as a unit. This unit can then be used in programs wherever that particular task should be performed.

Source: https://en.wikipedia.org/wiki/Subroutine

**Comment by nicolas-grekas** [comment]
@javiereguiluz that's the accurate name, see https://www.regular-expressions.info/subroutine.html

**Comment by Taluu** [comment]
About configuration, should it support nested subroutines ? such as 

```yaml
_subroutines:
    yyyymmdd: \d{4}-\d{2}-\d{2}
    uuid: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
    id: &uuid
```

**Comment by nicolas-grekas** [comment]
@Taluu it will, thanks to PCRE (but actual syntax is `(?&uuid)`)

**Comment by ostrolucky** [comment]
Can be named subroutine internally. Exposing this name externally is terrible idea IMO. How about *routing constraints*?

**Comment by nicolas-grekas** [comment]
The name is already exposed on the web, see PCRE doc and tutorial. Reinventing our own vocabulary looks even more terrible to me :)

**Comment by ostrolucky** [comment]
Name is fine in context of regular expressions. This context is missing in routing definitions though. Same reason why it's named `requirements` in routing files and not `regex`

**Comment by sstok** [comment]
Constants maybe? But there not really constants and their context is not very clear then 🤔
subroutines on it's self not very descriptive, we would need something to make it more apparent.

regex_subroutines (+1), regex_variables? (-0), pattern_subroutines (-1).

If we can explain what subroutines mean in this context I think it's good enough.
Otherwise we can make it an experimental feature, until we find a more concrete name.

**Comment by fabpot** [comment]
I would NOT name it subroutine.

**Comment by fancyweb** [comment]
Shouldn't the name contains at least the word "requirements" to be logical with where it's going to be used ?
I'm thinking of something like "_defined_requirements_patterns".

**Comment by nicolas-grekas** [comment]
See prototype implementation in #26529

**Comment by hhamon** [comment]
I remember I submitted such an idea to Fabien few years ago. Glad to see this topic brought on the table again!

I'm not a big fan of the proposed syntaxes. I would better see something like:

```
@Route("/foo/{uuid:id}")
@Route("/foo/{date:birthdate}")
@Route("/foo/{time:timestamp}")
```
Where `uuid`, `date`, `time` represent the predefined placeholders' regex constraints.

Couldn't we defined this predefined constraints under the `framework.router` global configuration?
It would be also easy to override them per routing file at the top level.

```
_defaults:
    predefined_requirements:
        date: '\d{4}-\d{2}-\d{2}'

my_route:
    path: '/yo/{date:deathdate}'
    ...
```

**Comment by nicolas-grekas** [comment]
Closing as the discussion in #26529 led to consider the current situation "good enough" (use parameters).

**Comment by nicolas-grekas** [comment]
About your proposal @hhamon, the requirements are already parsed 2 times: one for parameters, two by PCRE itself. Adding a 3rd way to parse the string looks like a bad idea to me. We should either stick to parameters (current situation), or leverage the parser of PCRE (#26529). The *status quo* won for now.

**Comment by Nek-** [comment]
This issue was closed without mentioning an alternative. Here is a link to the post describing it: https://github.com/symfony/symfony/pull/26529#issuecomment-373320865

**Comment by patrickbussmann** [comment]
What is the current status here?
With Symfony5 the alternative is gone.
@Nek-

**Comment by Nek-** [comment]
@patrickbussmann it is not, the following works well:

```yaml
# config/services.yaml
parameters:
    routing.uuid: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
```

And in the routing configuration, if you use YAML ([here for annotations](https://github.com/symfony/symfony/pull/26529#issuecomment-373320865)):
```yaml
# Example of routing file
# config/routes/item.yml
update:
    path: '/api/v1/items/{id}'
    controller: 'melodiia.crud.controller.update'
    methods: ['PATCH']
    requirements:
        id: '%routing.uuid%'
    defaults:
        melodiia_model: App\Domain\Item\Model\Item
        melodiia_form: App\Domain\Item\Form\ItemType
```

**Comment by nicolas-grekas** [comment]
See #45528 for possible implementation.
