### ISSUE TITLE
Bootstrap 4 template for Symfony does not display error messages when form element is rendered without label

### ISSUE THREAD

**Issue by xawiers** [symfony/symfony#26536]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

Bootstrap 4 template for Symfony does not display error messages when form element is rendered without label.
Create form with option 'label'=>false, create validator, submit form that should have not valid data.
Form element is rendered in red not knowing what kind of error it is.

**Comment by Nyholm** [comment]
I added a PR for this. See #26591

**Comment by xawiers** [comment]
:thumbsup:
