### ISSUE TITLE
[Form] Render same field multiple times

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#26531]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

This is a [common problem](https://www.google.sk/search?client=ubuntu&channel=fs&q=symfony+form+render+multiple+times&ie=utf-8&oe=utf-8&gfe_rd=cr&dcr=0&ei=szCpWvGNEuvf8geps6z4CA). Only workarounds exists is not using form_* functions for subsequent fields.

Wanted to solve this by doing

```twig
{{ form_row(form.save) }}
{% do form.save.setRendered(false) %}
{{ form_row(form.save) }}
```

quickly found [setRendered does not accept arguments](https://github.com/ostrolucky/symfony/blob/3c0693de23ea30c1a54ff7179ebf3168e1328793/src/Symfony/Component/Form/FormView.php#L86) and PRs for multiple different use cases has been [rejected<sup>1</sup>](https://github.com/symfony/symfony/issues/10898) [in<sup>2</sup>](https://github.com/symfony/symfony/pull/8128) [past<sup>3</sup>](https://github.com/symfony/symfony/pull/8676). Is this use case good enough for this change now?

This is specifically very useful to split form visually to two, where one block is just for RepeatedType and SubmitType. Here was the requirement from our designer

![37027104-b990ff70-2130-11e8-9f2b-469c0a1c2b03](https://user-images.githubusercontent.com/496233/37410483-0ade9ef2-27a1-11e8-8574-3726d147a32c.jpg)

If I could render same field twice, I could reuse same button field and be done with it.

**Comment by javiereguiluz** [comment]
Question for Form experts: is this limitation just to allow `form_rest()` and the closing `form` tag to know which fields have been already rendered ... or is this limitation needed for some other strong reasons? Thanks!

**Comment by jvasseur** [comment]
There is the limitation of ids that are supposed to stay unique in the page, this could lead to labels not being correctly linked to their inputs.

**Comment by yceruto** [comment]
> This is specifically very useful to split form visually to two

By adding another submit button with different name and same label shouldn't be enough to cover the use case?

**Comment by ostrolucky** [comment]
Yes, that's what I ultimately did. Not a fan of duplications tho.

**Comment by ogizanagi** [comment]
A workaround for this is to set a var:

```twig
{% set saveBtn = form_row(form.save) %}
```

and rendering it twice (or as much as you need).

**Comment by iltar** [comment]
If you want to render the same form multiple times, you can use named forms for this afaik. Your screenshot is too small to clearly see how or what.

**Comment by mickaelandrieu** [comment]
> A workaround for this is to set a var:

You'll duplicate the id everytime you re-use the form field.

**Comment by grachevko** [comment]
[Symfony best practice](https://symfony.com/doc/current/best_practices/forms.html#form-button-configuration): `Add buttons in the templates, not in the form classes or the controllers.`

**Comment by ostrolucky** [comment]
Ok plenty things have been answered and even some good workarounds given. I am going to ask different question now. What's the reason for [returning empty string for fields which were already rendered](https://github.com/ostrolucky/symfony/blob/1e1b37753c1a6da4a56ede0e2fc9df19e1150ff1/src/Symfony/Component/Form/FormRenderer.php#L135), if user tries to render them multiple times, instead of throwing exception with explanation? See here

**Comment by ogizanagi** [comment]
@ostrolucky: It would make sense to me, indeed.

**Comment by ostrolucky** [comment]
See https://github.com/symfony/symfony/issues/26531

If we disallow calling this for same field twice, we are opening up opportunity to change this behaviour in future.

E.g. in Symfony 6 we can make it no longer throw exception and allow to render same field more times, while shifting responsibility of making sure IDs do not collide to user, or even generate different IDs for subsequent fields. Currently this can't be changed due to BC.
