### ISSUE TITLE
Know which Interfaces/Classes are supported for auto tagging service with autoconfigure

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#26533]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | -
| RFC?             | -
| Symfony version  | -

Hello,

I'm constantly wondering myself which Interface are picked up by the container to add service tag automatically when you use `autoconfigure: true` config.

The [documentations](http://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags) mentions the `Twig_ExtensionInterface` Interface, but It would be awesome to **have a command that tells us all the interfaces and classes that will apply a tag to my autoconfigured service**.

ex: `bin/console debug:autotags` <--- not a good name, but 😅
 
PS: Is this already possible to know that (even without a command) ? If so I'd like to know how.

**Comment by nicolas-grekas** [comment]
100% agree, closing as duplicate of #26295
