### ISSUE TITLE
Request::getSession return type should not be null

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#26539]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0

As we have a `hasSession` method:

https://github.com/symfony/symfony/blob/3e999880ed6bcf264a45c7d92080da7a671dc7d7/src/Symfony/Component/HttpFoundation/Request.php#L750-L755

IMHO, `getSession` should not be nullable for the return type:

https://github.com/symfony/symfony/blob/3e999880ed6bcf264a45c7d92080da7a671dc7d7/src/Symfony/Component/HttpFoundation/Request.php#L719-L729

It should throw an exception instead. Plus, thanks to PHP 7 type-hinting, throwing an exception will not be necessary in the future.

This will reduce some tools alerts like this:

```
Calling method set() on possibly null value of type Symfony\Component\HttpFoundation\Session\SessionInterface|null.
```

WDYT?

**Comment by xabbuh** [comment]
Throwing an exception would be a BC break. Thus we would need to implement a forward-compatibility layer. I am not sure if it's really worth it.

**Comment by nicolas-grekas** [comment]
We could trigger a deprecation for now, and throw in 5

**Comment by iltar** [comment]
I'm personally in favor of this change. As not having a session won't happen, but the signature allows `null`, I still have to add a test-case for it.

**Comment by javiereguiluz** [comment]
Not sure about this proposal DX-wise:

### Before

```php
$foo = $request->getSession() ?? something_else();
```

### After

```php
$foo = $request->hasSession() ? $request->getSession() : something_else();

// or...

try {
    $foo = $request->getSession();
} catch(SomeException $e) {
    $foo = something_else();
}
```

**Comment by nicolas-grekas** [comment]
@javiereguiluz I'm not sure that's a very common situation. What `something_else()` do you use here as an expression?

**Comment by fmarchalemisys** [comment]
Why throw an exception instead of creating a new session and returning it?

Consider the two following methods:

~~~~~
public function injectingRequestAction(Request $request)
{
    $session = $request->getSession();
}

public function injectingSessionAction(SessionInterface $session)
{
}
~~~~~

The first one will throw an exception. What happens with the second method? Does it fail with an exception before it is called? I hope not.  Does it get an empty session? If yes, then the first method should do the same.
