### ISSUE TITLE
[Question] What's best practice for environment variables ? (HTTP and CLI) 

### ISSUE THREAD

**Issue by romaricp** [symfony/symfony#26558]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

I would like to know what's the best practice to define my environment variables in production mode ? 

In the official documentation we can find [Configuring Environment Variables in Production ](https://symfony.com/doc/current/configuration/external_parameters.html#configuring-environment-variables-in-production) but this is ok for project with url address (http) and this doesn't work with a CLI.

So I found a **bad solution** with global environment variable : https://stackoverflow.com/a/23635043
But if one server have a lot of projects, every project can access to other project's variable.. :( 

So what's the best practice for @SensioLabs to use environment variables with a project (HTTP and CLI) 

Thanks very much.
Romaric.

**Comment by Tobion** [comment]
Define the env variables on the server or whereever your cli commands run. If you can't do that, you can also use .env file parsing as done in dev mode. You can enable that in prod mode as well if you don't have a different way to define env variables.

I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by ebuildy** [comment]
@romaricp this is not related to Symfony, but to https://12factor.net/, I agree the transition for pure developers between SF3 and SF4 is quite rude. So as a developer, you must look at ops tools, such as:
- consul.io and https://github.com/hashicorp/envconsul (and https://github.com/hashicorp/consul-template for php-fpm/nginx)
- python envdir
- Docker (via --env-file or --env options) (to me the best way to isolate projects)
- natively before running the Symfony console:   ``export $(grep -v '^#' /PATH/.env.dist | xargs)``

**Comment by romaricp** [comment]
Hi @ebuildy and @Tobion, 
Thanks all for your reply. 

In my project case, I can't use any container for the production server.. So as you suggest recently @Tobion I will use directly the parameters -> https://github.com/symfony/symfony/issues/25643#issuecomment-363802598 I'm thinking it's the best and esay way for now.
