### ISSUE TITLE
Requirements test returning: "Your default timezone is not supported by PHP." But America/Sao_Paulo is not deprecated. 

### ISSUE THREAD

**Issue by Maykonn** [symfony/symfony#26550]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Both my php.ini files have correct values for date.timezone var:

```
> php -i | grep "timezone"
Default timezone => America/Sao_Paulo
date.timezone => America/Sao_Paulo => America/Sao_Paulo
```
But Symfony 3.4 requirements test returning error:
```
> php test/bin/symfony_requirements
Configured default timezone "America/Sao_Paulo" must be supported
   by your installation of PHP
   > Your default timezone is not supported by PHP. Check for typos in
   > your php.ini file and have a look at the list of deprecated
   > timezones at http://php.net/manual/en/timezones.others.php.
```
But America/Sao_Paulo isn't deprecated.

**Comment by javiereguiluz** [comment]
`America/Sao_Paulo` is indeed included in the list of supported timezones. It appears when dumping `timezone_identifiers_list()` info in PHP 7.2 and before.

However, see [this old note](http://php.net/manual/en/timezones.america.php#114338) in the PHP manual:

```
At Brazil, note that the Brazilian official timezone is wrongly described as
"America/Sao_Paulo", when it should be "America/Brasilia".

The Sao Paulo timezone does not exist, since this city follow the Brasilia
official timezone (BRT or BRST).
```

A [more recent note](http://php.net/manual/en/timezones.america.php#117000) says:

```
This nore is wrong by saying that "America/Sao_Paulo" timezone does not
exist and should be changed to "America/Brasilia".
```

So, not sure what's going on here 😕

**Comment by nicolas-grekas** [comment]
Closing as `America/Brasilia` is the correct TZ to use instead.

**Comment by andrenth** [comment]
This is incorrect. `America/Brasilia` is not the correct timezone. `America/Sao_Paulo` is correct, and listed by `DateTimeZone::listIdentifiers()`, but for some reason, it's not included in `DateTimeZone::listAbbreviations()`.

**Comment by derickr** [comment]
The argument that "America/Brasilia" is the correct one comes from the *wrong* assumption that the name of the timezone identifier is the capital of a country. That's incorrect. Timezone identifiers are named after the largest city (population wise) in a specific geographic area.

It *is* however correct that America/Sao_Paulo does not show up in "listAbbreviations", as there is no abbreviation for this timezone:

``
derick@singlemalt:~ $ zdump -v America/Sao_Paulo -c2017,2019
America/Sao_Paulo  -9223372036854775808 = NULL
America/Sao_Paulo  -9223372036854689408 = NULL
America/Sao_Paulo  Sun Feb 19 01:59:59 2017 UT = Sat Feb 18 23:59:59 2017 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 19 02:00:00 2017 UT = Sat Feb 18 23:00:00 2017 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Oct 15 02:59:59 2017 UT = Sat Oct 14 23:59:59 2017 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Oct 15 03:00:00 2017 UT = Sun Oct 15 01:00:00 2017 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 18 01:59:59 2018 UT = Sat Feb 17 23:59:59 2018 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 18 02:00:00 2018 UT = Sat Feb 17 23:00:00 2018 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Nov  4 02:59:59 2018 UT = Sat Nov  3 23:59:59 2018 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Nov  4 03:00:00 2018 UT = Sun Nov  4 01:00:00 2018 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  9223372036854689407 = NULL
America/Sao_Paulo  9223372036854775807 = NULL
``

As you can see, it uses ``-02`` and ``-03``.

**Comment by derickr** [comment]
I've removed these notes from the PHP manual, as they are wrong.

**Comment by javiereguiluz** [comment]
@derickr thanks for the insights about this issue. We couldn't have a better source for this information. Cheers!

**Comment by andrenth** [comment]
That's strange, it used to be that America/Sao_Paulo corresponded to "BRT", or "BRST" during daylight saving time.

With regards to Symfony, I guess it would be better to make timezone detection based on `listIdentifiers` then?

**Comment by derickr** [comment]
Yes, it used to, but not since ``2017a``:

- http://mm.icann.org/pipermail/tz/2016-December/024645.html
- http://mm.icann.org/pipermail/tz-announce/2017-February/000045.html

And yes, Symfony needs to fix this. You can't rely on abbreviations. They are only for *display* output purposes.
