### ISSUE TITLE
open_basedir restriction in effect

### ISSUE THREAD

**Issue by temperatur** [symfony/symfony#26563]
Hi, 
The https://github.com/contao/contao-manager uses Composer to update the installation.
The manager just work fine until it gets to the post-install-cmd Script of the composer.
Contao is using the PhpExecutableFinder to get the php binaries.  If the open_basedir is set is_file(PHP_BINARY) is false.
https://github.com/symfony/symfony/blob/5cf0a2ea8f32e86e6636c409ce92cf53ea098cb1/src/Symfony/Component/Process/PhpExecutableFinder.php#L50

Here the contao issue https://github.com/contao/manager-bundle/issues/57 for more information.

**Comment by Tobion** [comment]
So what do you propose? Just removing the file check?

**Comment by temperatur** [comment]
Yes, since the PHP_BINARY constant specifies the PHP binary path during script execution. 
So if it set there is no need to check if the file exists because if we are using cli we already used the binary.

**Comment by Tobion** [comment]
Could you create a PR?
