### ISSUE TITLE
[Question]symfony/templating still available?

### ISSUE THREAD

**Issue by etshy** [symfony/symfony#26579]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

I'd like to know if symfony/templating  is still existing ?
I found the repo but when I run 
`composer require symfony/templating`
I got a message `Nothing to install or update`
And I wanted to use FOSUser that need this templating repo.

thanks in advance.

**Comment by etshy** [comment]
After some research I found my error with FOSUser, I didn't specified the 'templating' key in framework.yaml config file.

Seems it's not needed by default (I could see my twig template without it) but it's necessary for FOSUser.

**Comment by fabpot** [comment]
templating should be avoided as of Symfony 4. It still works, but it makes applications heavier. I'd suggest FOSUser bundle to switch to not using templating.
