### ISSUE TITLE
Let ServiceSubscriberInterface Implementations Fetch Private Services

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#26574]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 4.x

The idea of `ServiceSubscriberInterface` doesn't seem perfectly clear to me, however from what I've seen in the past it allows building small containers which are injected instead of primary one. If I understand the idea correctly this should give more performance, and additionally prevent side effects (since dependencies are clearly exposed).

Despite the fact I wasn't able to trigger ServiceContainer to built me a dedicated container (is it implemented currently?) for a class implementing `ServiceSubscriberInterface` I wish I can mark services used by such implementations private. That way I can be 100% sure nothing is using service I'm planning to refactor/remove besides direct injections and implementations of `ServiceSubscriberInterface`.

WDYT?

**Comment by xabbuh** [comment]
I am not sure I understand what needs to be done from your perspective. Could you provide a small example of what you tried to do and what did not work?

**Comment by nicolas-grekas** [comment]
From your description, that's what `ServiceSubscriberInterface` provides already. You need to use the `container.service_subscriber` of course (or rely on autoconfiguration).
If there is some documentation missing, please open an issue on https://github.com/symfony/symfony-docs/
If not, then this looks a lot like a support request, therefore I'm closing. See https://symfony.com/support for more help.
