### ISSUE TITLE
[DI] Extending Abstract Service Definition setting argument with index gets not replaced in compiled definition

### ISSUE THREAD

**Issue by aurimasniekis** [symfony/symfony#26588]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

```php
$configurator->services()->set('monolog.my_channel', 'Symfony\Bridge\Monolog\Logger')
            ->parent('monolog.logger_prototype')
            ->arg(0, 'my_channel')
            ->public());
```

This is what definitions looks:

```
#id: "monolog.my_channel"
  -defaultTags: []
  #definition: Symfony\Component\DependencyInjection\ChildDefinition {#375
    -parent: "monolog.logger_prototype"
    -class: "Symfony\Bridge\Monolog\Logger"
    -file: null
    -factory: null
    -shared: true
    -deprecated: false
    -deprecationTemplate: null
    -properties: []
    -calls: []
    -instanceof: []
    -autoconfigured: false
    -configurator: null
    -tags: []
    -public: true
    -private: false
    -synthetic: false
    -abstract: false
    -lazy: false
    -decoratedService: null
    -autowired: false
    -changes: array:2 [
      "class" => true
      "public" => true
    ]
    -bindings: []
    -errors: []
    #arguments: array:1 [
      0 => "my_channel"
    ]
  }
}
```

This how compiled service looks:

```php
$this->services['monolog.my_channel'] = $instance = new \Symfony\Bridge\Monolog\Logger('', 'my_channel');

$instance->pushProcessor(($this->privates['debug.log_processor'] ?? $this->privates['debug.log_processor'] = new \Symfony\Bridge\Monolog\Processor\DebugProcessor()));

return $instance;
```

**Comment by fancyweb** [comment]
Looks like it is expected and not a bug.

Arguments with numeric keys always get added to the definition. In your case, the "monolog.logger_prototype" service defines an empty first argument, so yours get added after this one.

To replace it, you have to prefix the argument with "index_". In your case you must use : `->arg('index_0', 'my_channel')`

cf this foreach https://github.com/symfony/symfony/blob/9446fa01c4d42f9efff79f948b8d6dd027a67a6e/src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php#L146

**Comment by xabbuh** [comment]
@fancyweb is right here about this behaviour (see also the example at http://symfony.com/doc/current/service_container/parent_services.html#overriding-parent-dependencies). Though I would not use the `index_` notation to replace an existing argument (that's an implementation detail you shouldn't rely on), but use named arguments instead.

**Comment by stof** [comment]
Our PHP DSL should expose our `replaceArgument` method IMO, as it exposes the inheritance /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
@stof why not, could be something like `$service->index(0, $value)` to borrow from XML.

**Comment by stof** [comment]
@nicolas-grekas there is nothing talking about argument in this call, so no clear (in XML, the tag itself is `<argument>`)
