### ISSUE TITLE
Use specific exception class for Workflow exceptions [Workflow] [Feature] [RFC]

### ISSUE THREAD

**Issue by andrewtch** [symfony/symfony#26581]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.0

As it is hard to tell Workflow exceptions from other Logic exceptions, it would be nice to have specific exception class instead of `LogicException`. It could be `WorkflowException` extending `LogicException`, with additional `workflow` and `transition` fields.

Currently, one needs to parse exceptions message to make sure it comes from the Workflow component.

Can make a PR if this looks good enough.

**Comment by lyrixx** [comment]
See #26076

**Comment by andrewtch** [comment]
Not quite. You still merge exception to not very informative string message.
