### ISSUE TITLE
[Form] Checkbox input field with NotNull constraint is erroneous guessed as required

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony#26593]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.4

A boolean field is guessed in a form as checkbox input with the values 0 (not checked) or 1 (checked). If adding a NotNull constraint to the field, it is erroneous guessed as required. So it is necessary to check the field to submit the form. This is wrong, because the not checked field with the value 0 would be also valid.

**Comment by ismail1432** [comment]
Hi, IMHO it's not an issue, You should implement the logic to set a `default value` as 0 if not checked [see](https://symfony.com/doc/current/reference/forms/types/checkbox.html#data) you can found help on [stack](https://stackoverflow.com/questions/tagged/symfony) or in the [official slack](https://symfony.com/slack-invite) #support channel

**Comment by Mynyx** [comment]
The value is correct with 0 (not checked) or 1 (checked), the problem is the erroneous guessing as required.

**Comment by xabbuh** [comment]
Unfortunately, the guesser guessing the `required` attribute does not know for which form type the guessing is happening. Thus, the only solution here is to configure the attribute explicitly and I am closing here as there isn't anything we can do about it.
