### ISSUE TITLE
An exception has been thrown during the compilation of a template ("Warning: Illegal offset type")

### ISSUE THREAD

**Issue by jojivijay** [symfony/symfony#26594]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8

- After upgrading symfony 2.7 to 2.8, I am facing twig issue like "An exception has been thrown during the compilation of a template ("Warning: Illegal offset type")

$ composer show -i | grep twig
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
asm89/twig-cache-extension 1.3.2              Cache fragments of templates directly within Twig.
twig/extensions                      v1.5.1             Common additional features for Twig that do not directly belong in core
twig/twig                            v1.35.2            Twig, the flexible, fast, and secure template language for PHP

"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "gedmo/doctrine-extensions": "2.3.9",
        "snc/redis-bundle": "*",
        "white-october/pagerfanta-bundle": "*",
        "jms/translation-bundle": "*",
        "lexik/translation-bundle": "4.0.7",
        "asm89/twig-cache-extension": "*",
        "pinano/select2-bundle" : "3.5.2",
        "friendsofsymfony/jsrouting-bundle" : "@stable",
        "jwage/easy-csv": "1.0.*@dev",
        "facebook/graph-sdk" : "4.0.*",
        "stfalcon/tinymce-bundle": "~2.1",
        "google/apiclient": "1.0.*@beta",
        "salavert/time-ago-in-words":"1.*",
        "doctrine/data-fixtures": "1.0.*@dev",
        "doctrine/doctrine-fixtures-bundle": "@stable",
        "kriswallsmith/buzz": "dev-master",
        "aws/aws-sdk-php": "^3.46",
        "php-curl-class/php-curl-class": "^4.6",
        "egulias/email-validator": "~1.2",
        "jaybizzle/crawler-detect": "1.*",
        "amzn/amazon-pay-sdk-php": "^3.1"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "symfony/phpunit-bridge": "^4.0"
    },

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
