### ISSUE TITLE
Yaml PARSE_DATETIME getTimestampRegex does not support string timezones

### ISSUE THREAD

**Issue by leigh-ols** [symfony/symfony#26607]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | At least 3.3 onwards

The Yaml component will attempt to parse strings as DateTime objects if they match the regex in the `private static function getTimestampRegex`.

It passes `new \DateTimeZone('UTC')` as the second parameter to `DateTime`. Causing php to use UTC instead of the default timezone unless there is a timezone set specifically in the parsed string.

PHP allows passing time zones as strings to `DateTime`, overriding the second timezone parameter.

The regex in `getTimestampRegex` does not however recognize these strings as a timestamp and so they are never parsed.

So a value such as `2018-3-21 00:00:00.00 Europe/London` never gets parsed as a `DateTime` as it does not match the regex.

It is almost impossible to make the Yaml parser parse strings as date times with a string timezone other than UTC. As the method containing the regex is private and cannot be overridden, the method containing the call to that method is also private and cannot be overridden.

What this means is that the yaml DateTime parser is useless for parsing config files in time zones that use daylight savings. 

To be clear numeric time zones such as something like `2018-3-21 00:00:00.00 -0100` do in fact work... but this is no good for daylight savings when loading from a config file, unless the values in the config file are to be adjusted each time daylight savings changes.

**Comment by stof** [comment]
Well, AFAIK, the YAML timestamp format does not allow using ` Europe/London` as timezone: http://www.yaml.org/spec/1.2/spec.html#id2761573

**Comment by stof** [comment]
and btw, the value in the config file contains a single timestamp, so you know whether DST is in effect at this point. So depending on how you manage this config file, things might still be fine (if it is managed manually, this is indeed annoying).

**Comment by stof** [comment]
Well, the timestamp type of YAML is badly specified anyway, as it does not belong to the Core schema of Yaml 1.2 so there is no explicit spec about what they look like, only the small example I linked above (inherited from earlier versions of the spec).

**Comment by leigh-ols** [comment]
I appreciated your response.... Yaml timestamp format may not officially support this, but the php timestamp format does, so although not officially supported by Yaml, it may be worth considering including just for the convenience.

In my case my config files are managed manually, and doing any date/time comparisons within the application against dates/times placed in to the config files requires manually converting all dates/times to UTC before any comparison can be made.

Even turning off  DateTime parsing doesn't help because they get returned as timestamps in UTC also:
```
                        $timeZone = date_default_timezone_get();
                        date_default_timezone_set('UTC');
                        $time = strtotime($scalar);
                        date_default_timezone_set($timeZone);
```

This is awkward and fudgy to say the least.

**Comment by stof** [comment]
@leigh-ols if you want to perform the DateTime conversion on your own with all PHP features rather than the YAML syntax, wrap the value in quotes so that it is a YAML string and not a YAML timestamp.

The fact that PHP supports `Europe/London` as timezone does not mean that our Yaml parser should support it when parsing YAML. It must support YAML, not PHP, as your file is a YAML one. We worked hard in the past few versions of Symfony to bring our parser closer to the spec when finding places where it was not respecting it.

**Comment by leigh-ols** [comment]
@stof That makes perfect sense... however to my mind there is a difference between breaking spec and expanding/improving on it in a manner that improves usability. Personally don't see an issue with considering doing the latter as long as it doesn't involve the former.

I appreciate that sticking to spec is important... but personally i'm not sure I agree with religiously sticking to a spec that makes a feature almost entirely useless across half of the entire world?

As it stands any manually inserted date gets parsed in a manner that is almost useless in any country that uses DST. With no work around in existence that remains more efficient than simply not using the feature at all.

**Comment by stof** [comment]
@leigh-ols Well, this would break the spec, as an unquoted `2018-3-21 00:00:00.00 Europe/London` is a string in YAML, not a timestamp.

**Comment by leigh-ols** [comment]
In the purest sense, yes it breaks the spec. But I feel you've gone out of your way to ignore the rest of my comment.

There is breaking spec for a bad reason and there is improving upon spec which is still technically breaking out of spec.

`2018-3-21 00:00:00.00 Europe/London` is a string in yaml because it is not defined as anything else.

So while in the purest sense, yes it `breaks` the spec. It wouldn't break the spec in a way that would be none intuitive or likely to have a negative impact on an end user. It could easily be considered as further drilling down/improving the spec of DateTime, which you said yourself is poorly defined.

Regardless of whether you can/can't accept these semantics, the point stands that religiously sticking to a poorly defined spec in a manner that results in a net loss to the end user is not a good idea.
The reasons for having and sticking to any spec are that they ultimately benefit end users, this doesn't, quite the opposite, by its very nature sticking to it causes more far harm than good.

It is very unlikely that someone is going to put an unquoted `2018-3-30 01:00:00.00 London/Europe` in to a yaml file and expect it to be parsed as a string under the knowledge that `2018-3-30 01:00:00.00 -0100` gets parsed as a date time.
And even under such an event, it would be very intuitive to simply quote it should a user with super in depth knowledge of the yaml spec expect that.

The alternative is a feature which as I stated before, is almost useless across half of the planet.

**Comment by xabbuh** [comment]
While I can see that the spec and thus the implementation of the parser make things more complicated for you then you wish it to be I agree with @stof about the fact that we spend a lot of effort on making the Yaml component acting according to the spec. That's why I am going to close here as any change we made here would break the Yaml specification.

**Comment by leigh-ols** [comment]
@stof @xabbuh That's fair enough. I appreciate you taking your time to consider the change.
