### ISSUE TITLE
Add clear command to Console

### ISSUE THREAD

**Issue by dfridrich** [symfony/symfony#26603]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8, 3.*, 4.*

It would be great to add ability to clear the screen in Console. This feature should be implemented to `Symfony\Component\Console\Style\SymfonyStyle` class and should work like `$io->clear();`.

This can be done now using `$output->write(sprintf("\033\143"));`

**Comment by chalasr** [comment]
See https://github.com/symfony/symfony/pull/24363.

**Comment by javiereguiluz** [comment]
@dfridrich we had some proposals for a simple way to clear the screen (#23318 and #24449) but they were closed for some reasons. The #24363 feature mentioned by @chalasr allows to clear "output sections" ... but I don't know if it's simple to clear the entire screen without using any of its other (great) features. Maybe @pierredup, who created that feature, can tell us if that's possible. Thanks!

**Comment by pierredup** [comment]
It's possible to clear the entire screen by creating a single output section, E.G

```php
$output = $output->section();

// use $output as normal

$output->clear(); // Will clear the entire screen
```

**Comment by chalasr** [comment]
> Note that this will only clear the output that was printed by the command and not any previous output before the command was run

Actually I think it's a good thing, why should a single command be able to clear the output of previously run (unrelated) commands? I suggest to keep using `$output->write(sprintf("\033\143"));` for such needs, for others, clearable output sections should be enough as demonstrated by @pierredup.

**Comment by javiereguiluz** [comment]
I disagree :)  Sometimes I like to clear the entire screen before running a command.

**Comment by dfridrich** [comment]
@javiereguiluz, me as well. Almost all my commands begin with clear screen :-)

**Comment by ogizanagi** [comment]
Appart from very specific use cases (a full height command like top for instance), I don't think this is the responsibility of a command to clear the entire screen. The user can still prefix the command call with `clear && ` or CML + L and similar shortcuts.

**Comment by xabbuh** [comment]
I agree with @ogizanagi.

**Comment by fabpot** [comment]
I agree as well, let's close. Thanks for proposing.

**Comment by serious-angel** [comment]
Just in case, in certain terminals (e.g. KDE [Konsole](<https://github.com/KDE/konsole>)):

```php
/**
 * 1. `\x1B` - ANSI Escape;
 * 2.  `[2J` - Erase in Display (clear entire screen);
 * 3. `\x1B` - ANSI Escape;
 * 4.   `[H` - Move Cursor (move to 1x1).
 */
$this->output->write("\x1B[2J\x1B[H");
```

The following [may](<https://stackoverflow.com/a/37778152/5113030>) also work:

```php
/**
 * 1. `\x1B` - ANSI Escape;
 * 2. `\x63` - RIS – Reset To Initial State.
 */
$this->output->write("\x1B\x63");
```

# Related

\- [CSI (Control Sequence Introducer) sequences](<https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences>);
\- [vt100 - RIS](<https://vt100.net/docs/vt100-ug/chapter3.html#RIS>);
\- [ANSI Escape Sequences - Cursor Controls](<https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b>).
