### ISSUE TITLE
DX when installing profiler pack

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#26606]
| Q                | A
| ---------------- | -----
| Bug report?      | don't know
| Feature request? | no
| BC Break report? | don't know
| RFC?             | no
| Symfony version  | 4.0.6

Hello,

I ran into an issue when installing the profiler pack on Symfony 4.0.6 (on a Windows 10 server).

The web debug toolbar produced an error and all profiler's routes resulted in 404 errors.

I solved this issue by using and adapting the .htaccess of a previous Symfony version in the "public" dir.

Can you tell me if it's the proper way to fix this? Did I missed something in the documentation in order to get the profiler working seamlessly when requiring it via composer?

Thank you!

Fabien

**Comment by xabbuh** [comment]
> I solved this issue by using and adapting the .htaccess of a previous Symfony version in the "public" dir.

What do you mean with this? What was the change that you had to do to make things work?

**Comment by fabienlem** [comment]
@xabbuh I just renamed app.php in index.php in the .htaccess file.

**Comment by BoShurik** [comment]
@fabienlem Do you use apache? Did you install apache-pack?

**Comment by fabienlem** [comment]
@BoShurik that was it! I didn't know about this pack.

Thank you both for your help.

**Comment by stof** [comment]
I'm closing this, as there is nothing related to the profiler-pack here.
