### ISSUE TITLE
[Workflow] Add a method to the Registry which returns all workflows associated to a certain object

### ISSUE THREAD

**Issue by alexpozzi** [symfony/symfony#26618]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x/4.x

First of all thanks for the great work!

It would be great to have a method in the Registry class that returns all the workflows associated to a specific object class.
This would add the possibility to easily implement, for example, an admin UI where the admin can see the status of all the workflows associated to a specific object.

Would it be useful? 
Is there a reason why it has not been implemented yet? 

I would implement it this way:
```
class Registry
{
   ...

   /**
     * @param object      $subject
     *
     * @return Workflow[]
     */
    public function all($subject)
    {
        $matched = array();
        foreach ($this->workflows as list($workflow, $supportStrategy)) {
            if ($supportStrategy->supports($workflow, $subject)) {
                $matched[] = $workflow;
            }
        }
        if (empty($matched)) {
            throw new InvalidArgumentException(sprintf('Unable to find any workflow for class "%s".', get_class($subject)));
        }
        return $matched;
    }

   ...
}
```

**Comment by lyrixx** [comment]
It has not been implemented yet because no-one asked it before.

You use case seems valid to me, so it's a :+1: for me.

Would you mind to submit a PR?

**Comment by alexpozzi** [comment]
Perfect, I will submit a PR later this day!

Thanks

**Comment by lyrixx** [comment]
@alexpozzi The feature freeze is in less than a week. If you want this feature for 4.1 you need to hurry up.
But if you don't have time to do that, don't worry, I can do it for you. But you have to tell me as soon as possible.

**Comment by alexpozzi** [comment]
@lyrixx Sorry, yesterday I didn't have time to submit the PR.
I'll do it today or tomorrow top.
