### ISSUE TITLE
[HTTPFoundation] Set many session parameters at one time

### ISSUE THREAD

**Issue by zzenmate** [symfony/symfony#26616]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

Is it possible to set many session parameters at one time?
In a case with the session we do:
```php
$session = new Session();
$session->set('first_param', 'a');
$session->set('second_param', 'b');
```

I want to set many paramеters by analogy with set many paramеters to request.
For, a request we do:
```php
$request = new Request();
$request->request->add([
    'first_param' => 'a',
    'second_param' => 'b',
]);
```
I think it will be good feature for session if we can set many params?
What do you think?

**Comment by ismail1432** [comment]
IMHO It's a good helper and it's seems not difficult too develop 👍

**Comment by fabpot** [comment]
The question is how frequently people would use it. I would refrain from adding another public method if usage would be limited.

**Comment by iltar** [comment]
I've personally never needed it. Whenever there's information that's supposed to be stored at the same time, it's usually related and thus I use a serializable object to keep it sane. You can simply set this under a single key and doesn't cause any problems.

**Comment by zzenmate** [comment]
I had a case with many parameters maybe few times. Yes, and a serializable object is solved this problem in many cases. But, maybe the way with set many parameters at one time is more easier in some cases.
Does this feature require other developers?

**Comment by iltar** [comment]
What about something like this?

```php
$session->set('user_info', [
    'username' => 'hdevries', 
    'real_name' => 'Henk de Vries',
]); 
// vs
$session->set('user_info_username', 'hdevries');
$session->set('user_info_real_name', 'Henk de Vries');
// vs
$session->set([
    'user_info_username' => 'hdevries', 
    'user_info_real_name' => 'Henk de Vries',
]); 
```

Personally I feel that the case already possible (the first), would be the cleanest (regarding of the array setter name). So I'm personally :-1: on this feature. I can see where it's coming from, but I don't think it's worth the API change.

**Comment by javiereguiluz** [comment]
I've never needed this feature so I can't feel how painful is to not have this feature ... but the latest proposal from @iltar looks like a good solution that already works and it shouldn't complicate apps much:

```php
$session->set('user_info', [
    'username' => 'hdevries', 
    'real_name' => 'Henk de Vries',
]); 
```
