### ISSUE TITLE
[Feature] BDD Symfony Pack

### ISSUE THREAD

**Issue by mnavarrocarter** [symfony/symfony#26610]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1.0

I would like to propose a new feature using the awesome stuff that we can build with flex!

Right now, if you want to start with Behat in Symfony, it's not like the experience you get with doctrine or other "packs". You just have to do everything using regular composer.

I'm aware of several composer packages that integrate Behat to Symfony. Few of them are tested and well supported.

So what I'm proposing is something along the lines of a `symfony/bdd-pack`. That will install require a `symfony/behat-extension` (to be developed), and of course behat itself. The `symfony/behat-extension` will contain some useful contexts related to symfony, and useful symfony contexts, like a KernelAwareContext, ContainerAwareContext or something along those lines.

We can use flex to create a recipe that will create some dummy features tests and basic config.

Everything I said here can be modified. TLDR: Maybe will be a good idea to implement a bdd testing pack.

**Comment by stof** [comment]
@mnavarrocarter Behat already has a `behat/symfony2-extension` (which is actually for Symfony 2+ but renaming it would have been a BC break without any benefit).

You can already require it, and a Flex recipe will create a basic behat config file (and Behat will be installed too, as the extension requires it). So I don't see the benefit for such a pack.

**Comment by mnavarrocarter** [comment]
Silly me. I did't notice that package was compatible with Symfony 4. Thanks @stof!

**Comment by sroze** [comment]
Might be why the renaming is worth 🤨
