### ISSUE TITLE
When a service file is not valid, the exception does not show the invalid file

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#26638]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

---

I'm migrating an app (SF 3.4) to the new "DIC architecture" and at some point I made a type. Instead of `_defaults` I typed `_default` (missing `s`).

And I got the following exception:

```
(1/1) RuntimeException
The definition for "_default" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.
```

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/408368/37775698-e8665498-2de3-11e8-9b44-aae9406439a8.png)

</details>

As we have many `services/*.yml` files it was not clear which file was wrong.

I think we can improve the DX by adding the `$filename` in the exception message.

---

Note: I [pushed a producer](https://github.com/lyrixx/test/commit/0e905d0fff6305a47cc55ab5e4362af7d5d49eba)

**Comment by xabbuh** [comment]
What makes this one tricky is that the error is not detected by the `YamlFileLoader` which could provide the context to improve the error message, but is triggered by a compiler pass that checks if your service definitions are valid. For BC reasons the `YamlFileLoader` will treat the `_default` section as a regular service definition.

**Comment by lyrixx** [comment]
Yes I noticed this error could not occurs on Symfony 4.X.

**Comment by stof** [comment]
Well, the thing is, we cannot forbid `_default` as service id in the YamlFileLoader in 3.4 for BC. 4.0 made leading underscores reserved in the YAML loader to be able to warn for such typos.

Btw, you should also be getting a deprecation warning in 3.4 for such case (but as things break too early for the profiler, the profiler itself cannot be used to see it, it requires looking at logs).

Adding the filename to the exception message is not possible. Definition objects are not associated to a file (and they might be the result of changes occuring in multiple places as they can be modified after the loader loaded them).

**Comment by lyrixx** [comment]
> Adding the filename to the exception message is not possible

Ok. So I think we can close the issue
