### ISSUE TITLE
symfony/form `Symfony\Component\Form\FormBuilder->add()` does not support instances of `Symfony\Component\Form\FormTypeInterface`

### ISSUE THREAD

**Issue by lxxps** [symfony/symfony#26633]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

In the source code (https://github.com/symfony/symfony/blob/v4.0.6/src/Symfony/Component/Form/FormBuilder.php#L70), we can see that the `Symfony\Component\Form\FormBuilder->add()` method should accept `Symfony\Component\Form\FormTypeInterface` instances as second argument (`$type`).

But when I attemp to pass an instance that implements `Symfony\Component\Form\FormTypeInterface`, the `buildForm()` method fails, especially on the `resolveChildren()` process.

```
        $formbuilder
            ->add( 'subform' , new class() extends \Symfony\Component\Form\AbstractType {
                public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
                {
                    $builder->add( 'field1' );
                    $builder->add( 'field2' );
                    $builder->add( 'field3' );
                    $builder->add( 'field4' );
                }
            } , [] );
```

I think that, on `add()` method, child should be considered as *resolved* if the `$type` argument is an instance of `Symfony\Component\Form\FormTypeInterface`, so the assignement to `$this->children` or `$this->unresolvedChildren` properties should be conditional (https://github.com/symfony/symfony/blob/v4.0.6/src/Symfony/Component/Form/FormBuilder.php#L73).

Am I wrong?

Thanks

**Comment by lxxps** [comment]
Ok, the child cannot be considered as resolved, never.

**Comment by xabbuh** [comment]
> But when I attemp to pass an instance that implements Symfony\Component\Form\FormTypeInterface, the buildForm() method fails, especially on the resolveChildren() process.

What does "it fails" mean? Do you get an error?

**Comment by lxxps** [comment]
> What does "it fails" mean? Do you get an error?

Of course, a `Symfony\Component\Form\Exception\UnexpectedTypeException` on `Symfony\Component\Form\FormFactory->createNamedBuilder()` method.

But, do not worry, I have found how to fix it, I just need to do a pull request :)

Thanks

**Comment by stof** [comment]
I think the issue here is the usage of an anonymous class. Form types are named based on their class name in Symfony, so anonymous classes are quite unlikely to work.

and a type instance being passed is definitely *not* resolved, and it must be resolved (the default parent of a form type is the core FormType, not no parent, as it allows applying the common necessary logic).

**Comment by stof** [comment]
anyway, I think passing a Type *instance* was deprecated in the past and support was dropped (as it was causing lots of issues, including performance ones, as you could have multiple instances of the same type registered over time and replacing each other). I think the error message in `Symfony\Component\Form\FormBuilder->add()` was forgotten when changing the code in the inner level.

**Comment by stof** [comment]
yeah, support for it was indeed removed in Symfony 3.0: https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

**Comment by stof** [comment]
If you don't want to create a type class for your subform, here is how you can do it:

```php
        $formbuilder
            // If the form does not have a data class set properly, type guessing for
            // subfields does not work (it always use TextType). The class can be omitted if
            // subfields are configured explicitly.
            ->add($formbuilder->create('subform' , FormType::class, ['data_class' => 'Foobar'])
                    ->add('field1')
                    ->add('field2')
                    ->add('field3')
                    ->add('field4')
            );
```

**Comment by lxxps** [comment]
> yeah, support for it was indeed removed in Symfony 3.0

Ah ah! Thanks a lot for your awesome workaround!
