### ISSUE TITLE
[WebProfilerBundle] If exception during AJAX request occured, make profiler url point to exception page

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#26646]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

So here is second annoying issue with this part of profiler I have
![selection_001](https://user-images.githubusercontent.com/496233/37802877-80fb3cee-2e2c-11e8-9292-88b96835da31.png)

What do you want to see when you click on that link? In my case, it's in 100% of the cases exception trace. Instead, i'm always taken to request/response tab and then I have to switch to Exception trace by myself.

Can we generate URL here pointing to exception tab by default, when 4xx/5xx error occurs?

Again summoning @javiereguiluz as our UX/DX profiler expert.

**Comment by javiereguiluz** [comment]
@ostrolucky I'd say this proposal makes a lot of sense! I can't see any drawback to doing this.

**Comment by fancyweb** [comment]
Also, what do you think of displaying the profile column first ?

The links are the furthest possible from where you toggle the panel, so it's hard to not lose the focus when you only have one ajax request.
And this is the only column with a link in the panel.

**Comment by fabpot** [comment]
Makes sense to me as well.
