### ISSUE TITLE
Is it will be better to use `is_callable` to check if it should call a function to check allowed type?

### ISSUE THREAD

**Issue by mrself** [symfony/symfony#26664]
https://github.com/symfony/symfony/blob/4a602ca6529090197e09555796b27500111aee31/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L805

When I set allowed type for an option I initially used `$resolver->setAllowedTypes('option', [$this, 'checkOption']`. But then saw that it did not work. The resolver checks if a type is a clousure instance, not if it is a callable. So is it will be better to check if it is callable instead to allow callable array?

**Update**: the same with `defaults`: https://github.com/symfony/symfony/blob/4a602ca6529090197e09555796b27500111aee31/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L145

**Comment by jvasseur** [comment]
Allowing any callable could create situations where the intention behind the passed value is ambiguous. For example if you have want to allow instances of `Foo` and `Bar` you would pass the `['Foo', 'Bar']` array, but if the `Foo` class has a `bar` static method this is a valid callable.

You can use `Closure::fromCallable` if you want to use a non-closure callable.

**Comment by mrself** [comment]
`Closure::fromCallable` if you use `7.1`. But agree, it goud ambiguous. Close it.
