### ISSUE TITLE
[DI] Automatic registration of decorating service

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#26666]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

With [autowiring decorators available](https://github.com/symfony/symfony/pull/25631), it would be nice if we could have them registered automatically with no yaml code.

Just like it works for EventSubscriberInterface::getSubscribedEvents(). Example:

```php
class FooDecorator implements DecoratorInterface
{
    public static function getDecoratedService()
    {
        return Foo::class; // just the service name
        return [Foo::class, 5]; // service name, priority
    }

    public function __construct(Foo $decorated)
    {
        //...
    }   
}

**Comment by nicolas-grekas** [comment]
:-1: that's not a good idea to me: the proposed method would return service identifiers. But those do not belong to the world of OOP. A service id shouldn't have any meaning from a class' author POV (only types do.)

**Comment by zmitic** [comment]
@nicolas-grekas I agree, returning something like `guzzle.client.my_api` looks wrong. 

But most classes are creating only one service like `FormBuilderInterface::class`. Having it in above method also allows quick-jumping to original service.

**Comment by nicolas-grekas** [comment]
Correct, but that's a hack, not a proper design :)
