### ISSUE TITLE
[WebServerBundle] server:start does not run in test environment when started in it.

### ISSUE THREAD

**Issue by tarjei** [symfony/symfony#26673]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.6

When using Symfony 3.3 `console server:start` respected the environment you started it in. Thus it was possible to call `console server:start -e test`.

Now, trying to run `console server:start -e test` ends up with the command succeeding but the webserver environment depends on wether you access app.php of app_dev.php. 

Either server:start should fail when run with the `test` environment or at least run a very large warning since this is a BC break.

**Comment by fancyweb** [comment]
From what I understood, I cannot find anything that is not working as expected.
Can you be more precise please ?

**Comment by zairigimad** [comment]
in symfony 3.4.6 the WebServerBundle is only enabled in the dev environment : 
``` php
            if ('dev' === $this->getEnvironment()) {
                $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
                $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            }
`
and when executing the command you should see the following error : 
 There are no commands defined in the "server" namespace.

Can you provide us more details, please?

**Comment by nicolas-grekas** [comment]
Is this still the case with recent projects? Flex and recipes changed a lot recently in related parts.

**Comment by tarjei** [comment]
@zairigimad  I seem to remember that it wasn't just an issue with the webserver bundle not being enabled, but that the webserver bundle hardcoded the environment somehow.
T

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce this issue?

**Comment by xabbuh** [comment]
I am closing here for now. We can reopen if we are able to reproduce the issue anyway. Thank you for understanding.
