### ISSUE TITLE
git clone fails

### ISSUE THREAD

**Issue by emimarz** [symfony/symfony#26678]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

When I run this command
git clone --no-checkout 'https://github.com/symfony/process.git' .

it give me this error
Cloning into ....
error: gnutls_handshake() failed: A TLS fatal alert has been received. while accessing https://github.com/symfony/process.git/info/refs

fatal: HTTP request failed

git --version
git version 1.7.2.5

openssl version
OpenSSL 1.0.1 14 Mar 2012

**Comment by SpacePossum** [comment]
This is an issue with either the github server setup up or the git client you use (so not directly related to the SF project). Can you check the `libcurl3-gnutls` version you are using, `7.21.6-3` is known to have some issues and downgrading to `7.21.0-1` might help.

**Comment by Nyholm** [comment]
Thank you @SpacePossum for your answer. 

This issue should be closed as it is not related to Symfony. Please use other forums like StackOverflow for this issue.

**Comment by stof** [comment]
Github recently dropped weak cryptographic standards for SSL access. You might need to update your stack: https://blog.github.com/2018-02-02-weak-cryptographic-standards-removal-notice/
