### ISSUE TITLE
[Workflow] Rename the workflow_build_transition_blocker_list() function?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26689]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

I don't have real experience with Workflow, so this is a question for developers who have that experience. Don't you think that the name of the new `workflow_build_transition_blocker_list()` Twig function is too long? Would it be better to make it more concise?

Example:

### Before

```twig
{% for blocker in workflow_build_transition_blocker_list(article, transition.name) %}
  ...
{% endfor %}
```

### After

```twig
{% for blocker in workflow_transition_blockers(article, transition.name) %}
  ...
{% endfor %}
```

or:

```twig
{% for blocker in workflow_blockers_list(article, transition.name) %}
  ...
{% endfor %}
```

or:

```twig
{% for blocker in workflow_blockers(article, transition.name) %}
  ...
{% endfor %}
```

**Comment by lyrixx** [comment]
This function does not exist (yet ?) in symfony. It's only in my demo application. 

But I could move it to symfony :-)

**Comment by javiereguiluz** [comment]
Ah sorry! And if it doesn't exist in Symfony ... what is the equivalent in Symfony for this example? Thanks!

**Comment by lyrixx** [comment]
This function is not exposed in twig because I was not sure if it is useful.
I supposed it's more common to call the method in the controller and pass the result to the view. 
But more over I think this method will not be called so often, and the result will be get via a try catch around the apply method (like asked in the original ticket)

Anyway, as I said, we could implement it. It's just 5 LOC

**Comment by javiereguiluz** [comment]
If there is not a strong use case for it, let's not add it. But people who use the Workflow component should tell us if they need this or not.

**Comment by lyrixx** [comment]
Ok. Let's close this issue for now

**Comment by geoff-maddock** [comment]
Is this intended to be part of the codebase?  It's mentioned in the what's new from 4.1:
https://symfony.com/blog/new-in-symfony-4-1-workflow-improvements

**Comment by lyrixx** [comment]
Hi @geoff-maddock. You can find the code in [my demo](https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/master/src/Twig/WorkflowExtension.php#L33-L38)

**Comment by loevgaard** [comment]
It is in the docs here: https://symfony.com/doc/current/workflow/usage.html. Is that intended? (I guess not)

**Comment by geoff-maddock** [comment]
IMO, that should be removed from the docs.
