### ISSUE TITLE
Symfony 3.3  or 3.1 Unable to find template in vendor/.../Resources/views/Form.

### ISSUE THREAD

**Issue by dodwina** [symfony/symfony#26688]
Symfony version  |3.3 or with 3.1  => same issue

My error:  _" Twig_Error_Loader: Unable to find template "UpnsUserBundle:Moocs:mooc.html.twig " (looked into: /Applications/MAMP/htdocs/www/site/app/Resources/views, /Applications/MAMP/htdocs/www/site/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).  "_
->I changed route syntax and move folder but same error / like this=

**app>Resources>views> Moocs>mooc.html.twig  
or 
move folder "Moocs" in Upns>UserBundle>Resources>views>Moocs>mooc.html.twig .**  
by adapting the path in the controller

-mooc.html.twig extends base.html.twig
-base.html.twig  is in  app>Resources>views
-debug router is good. 

->I have same issue for 2 routes , common point:  **"/mooc{id}/", name=" mooc", requirements={"id": "\d+"}**

**Comment by stof** [comment]
if you don't have the templating component enabled in your project, the old `UpnsUserBundle:Moocs:mooc.html.twig ` notation for template names does not work (as the templating component is the one responsible to resolve it).

You should either enable the templating component, or use the native Twig notation (`@UpnsUser/Moocs/mooc.html.twig` in this case)

**Comment by dodwina** [comment]
je sais que le issue est fermée, mais je tiens a dire que l'annotation native ne passe pas. j'avais essayé de nombreuses syntaxes. Je vais tester avec le composant de templates en espérant que cela n'oblige pas a changer l'architecture du site. Merci
