### ISSUE TITLE
Same template is cached with different references

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony#26692]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

When the cache is warmed up, a template with the path ````app/Resources/views/default/test.html.twig```` is referenced in the cache as ````:default:test.html.twig````.

If using the same template in a controller where the template is referenced as ````default/test.html.twig```` the template is not found in the cache and is parsed again.

**Comment by javiereguiluz** [comment]
Just to be sure ... you don't use `:default:test.html.twig` anywhere in your application and this is just something that Symfony does on its own, right?

**Comment by Mynyx** [comment]
Yes, it is not used anywhere.

**Comment by xabbuh** [comment]
Can you create a small application that allows to reproduce your issue?

**Comment by Mynyx** [comment]
If you have created the template, warmed up the cache and visited a page where the template is referenced as ````default/test.html.twig```` in the controller, you can verify the issue with ````grep 'test.html.twig' var/cache/dev/ -r````.

**Comment by javiereguiluz** [comment]
I've used the Symfony Demo app to do some quick test. Remove the entire cache, run `cache:warmup` and see which templates are compiled in `twig/`. The result was the expected one. Our own templates use the new syntax:

```
/* base.html.twig */
/* blog/about.html.twig */
/* blog/index.html.twig */
```

And Symfony's templates also used the right syntax:

```
/* form_table_layout.html.twig */
/* @Swiftmailer/Collector/swiftmailer.html.twig */
/* @WebProfiler/Collector/cache.html.twig */
```

So, I can't reproduce this error. Does your project includes the Symfony Templating component? In any case, please create a bug reproducer as explained in https://symfony.com/doc/current/contributing/code/reproducer.html Thanks!

**Comment by Mynyx** [comment]
Which version of the Symfony Demo you have used? This ticket relates to Symfony 3.4.6, so I have used the old version.

````
./symfony demo
cd symfony_demo/
php -d memory_limit=-1 ../composer update
bin/console cache:clear --no-warmup
bin/console cache:warmup
grep 'about.html.twig' var/cache/dev/ -r
````

The first result would be with the old syntax ````/* :blog:about.html.twig */````. 

If this does not help, I will create a new project later.

**Comment by javiereguiluz** [comment]
I used the latest version, so 4.0.x.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
