### ISSUE TITLE
Failed to parse command output

### ISSUE THREAD

**Issue by nanofarade** [symfony/symfony#26694]
So this is what I got when I try to add the Symfony tool (Symfony version : 3.*.*)

The project was created from another machine and cloned into mine (Git)

I could make the necessary changes for composer.phar and php.exe when adding the Composer tool and I had no problem concerning that but when it comes to add the Symfony tool I got a " Failed to parse command output " error message and there are the details of the error

![failed](https://user-images.githubusercontent.com/36171915/38028149-4a2b2980-3292-11e8-8a9a-f43303c2b9cf.png)

What sould I do?
Thank you

**Comment by Dainerx** [comment]
Was composer added as global or local to the project? 

One thing you can try is: 

1. Remove the composer tool
2. Add it again using the composer.phar file located on the **local** project
3. Retry adding the Symfony tool which console is located under bin/console

**Comment by nanofarade** [comment]
Just in case some people might have the same problem, it was simply an issue of "Git ignored" config files...
