### ISSUE TITLE
Command "symfony demo" installs old version without warning

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony#26705]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

The command ````symfony demo```` installs an old version based on symfony 3.3. 

If using the command ````symfony new my_project```` a warning is shown:
````
  [RuntimeException]
  The Symfony Installer is not compatible with Symfony 4.x or newer versions.
  Run this other command to install Symfony using Composer instead:
  composer create-project symfony/skeleton my_project
````

Maybe a warning would be helpful for ````symfony demo```` too, because this command is referenced in multiple blog posts about the symfony demo.

**Comment by jakzal** [comment]
You should probably raise it in https://github.com/symfony/symfony-installer instead of here

**Comment by javiereguiluz** [comment]
@Mynyx please copy this issue in the https://github.com/symfony/symfony-installer repo as suggested by Jakub so we can fix it. Thanks!
