### ISSUE TITLE
[FrameworkBundle] Annotations cache warmed up with opcache enabled is not valid when application run without opcache

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#26709]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.*

If cache warming up happens on environment with `opcache.enable = 1`, and then application wants to be run on environment with disabled opcache, warmed up cache become inconsistent.

This happens because method `\Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache` detects best match adapter for enviroment, and this method used both when warming up and executing code. With opcache enabled, `PhpFilesAdapter` used, without opcache `FilesystemAdapter` used. So, cache warmed for PhpFilesAdapter, but at runtime FilesystemAdapter is used, without warmed cache as a result.

To solve this problem, I warm up cache twice:
```
php app/console cache:warmup -e prod
php -d opcache.enable=0 app/console cache:warmup -e prod
```
This helps, but I think it should be documented, or cache should be warmed up to all possible environments.

**Comment by xabbuh** [comment]
IMO this needs to be "fixed" in the documentation. Would you like to open an issue over there?

**Comment by nicolas-grekas** [comment]
I'm not sure the warning about the mismatch is possible: once warmed up and run in prod, we don't want such a check on every single request (where would we put it?)
So I agree with @xabbuh: this should be documented instead.
@Strate would you mind opening a doc issue or PR?

**Comment by Strate** [comment]
@nicolas-grekas for example, we can "remeber" opcache state in warmed up folder somehow, and if application run with different, non-warmed-up state of opcache, log this at "WARNING" level. Or "NOTICE".

This is significant on encoded environemtns (sourceguardian for example), because on that environment we can't make a lazy-warmup.

**Comment by nicolas-grekas** [comment]
This is now fixed (as a new feature) on master.
