### ISSUE TITLE
[Configuration] environment variables don't work on booleanNodes

### ISSUE THREAD

**Issue by sebastianblum** [symfony/symfony#26704]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Symfony version  | 4.0.6

I tried to use environment variables for booleanNodes and get this exception:

In [BooleanNode.php](github symfony/symfony boolean node) line 29:                                                                                               
  Invalid type for path "web_profiler.intercept_redirects". Expected boolean, but got string.  

To reproduce the issue, I forked symfony demo and changed this:
https://github.com/sebastianblum/demo/commit/4df780b0fcfd593d3dbdac721f5ae32ae374367e

I extended the exception and the value was:
In BooleanNode.php line 29:                                                                                                                                               
  Invalid type for path "web_profiler.intercept_redirects". Expected boolean, but got string. Value was: %env(bool:APP_INTERCEPT_REDIRECTS)% 

It looks like that the environment variables are not correct resolved for booleanNodes.

**Comment by nicolas-grekas** [comment]
Correct, supporting this is a new feature that will ship in 4.1, see #23888

**Comment by damour** [comment]
@nicolas-grekas any chance to backport this to 3.4? From user perspective it's looks like a bug, because environment variables not usable in symfony 3.4. Validation failed  in many bundles: I18nRoutingBundle, SwarrotBundle, leaseweb/memcache-bundle, sentry, etc.

**Comment by mathroc** [comment]
should the documentation be fixed then ?

https://symfony.com/doc/3.4/configuration/external_parameters.html#environment-variable-processors

**Comment by xabbuh** [comment]
@mathieutu I don't know if I understand what exactly you want to see changed in the documentation. But since we have our own repository for the docs I suggest that you open an issue [there](https://github.com/symfony/symfony-docs).

**Comment by xabbuh** [comment]
@mathieutu ops sorry :)

**Comment by nesk** [comment]
Is this really fixed in 4.1? I still encounter the issue with a clean install through `composer create-project symfony/website-skeleton optional-env-demo`.

Here is [the commit adding a environment variable](https://github.com/nesk/symfony-demo-broken-env/commit/84a393ce36944666d9238f91c1729d12ab4f52bd) to enable/disable the web profiler toolbar. This fails with the following exception:

```
Environment variables "bool:WEB_PROFILER_TOOLBAR" are never used. Please, check your container's configuration.
```

**Comment by ro0NL** [comment]
@nesk can you create a new issue for that?

**Comment by nesk** [comment]
Yes! #29276
