### ISSUE TITLE
Bundle "EventBundle" does not exist or it is not enabled. (New to the framework)

### ISSUE THREAD

**Issue by kirbygit** [symfony/symfony#26719]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe cause I am new to this framework
| BC Break report? | maybe cause I am new to this framework
| Symfony version  | 2.8 Tuts from knp

**Comment by kirbygit** [comment]
<img width="1280" alt="screen shot 2018-03-30 at 12 28 12 pm" src="https://user-images.githubusercontent.com/20747057/38150984-442fe504-3416-11e8-86f9-9de79fcef99d.png">

**Comment by kirbygit** [comment]
ok i think I figured it out however, I run to this new error
<img width="1280" alt="screen shot 2018-03-30 at 12 47 52 pm" src="https://user-images.githubusercontent.com/20747057/38151550-a27c2206-3418-11e8-80ea-4b780e84378d.png">

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
