### ISSUE TITLE
Bug? isXmlHttpRequest()

### ISSUE THREAD

**Issue by kironet** [symfony/symfony#26716]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Symfony version  | 4.0.6

Hi,

I've already posted this on Stackoverflow because I'm not sure if this is a bug:

I'm not sure how to explain my problem. I have a controller that has this piece of code to check if URL is accessed using ajax or not.

```
        //check if ajax request
        if ($request->isXmlHttpRequest()) {
            ...
        } else {
            ...
        }
```
If url is accessed using ajax it's returning JSON if not it's returning view. When I access this URL in chrome it's showing right data(view) but if I move to for example google.com and click "back arrow" in Chrome's UI, it takes me back to my URL but now it's showing JSON.

Everything is working fine in Safari.

Same code works fine on Symfony 3.3(old project)

**Comment by ismail1432** [comment]
The documentation method said :

« Returns true if the request is a XMLHttpRequest.

It works if your JavaScript library sets an X-Requested-With HTTP header. It is known to work with common JavaScript frameworks » cf https://api.symfony.com/3.2/Symfony/Component/HttpFoundation/Request.html#method_isXmlHttpRequest

Did you checked the header when you clicked on the back arrow ?

**Comment by kironet** [comment]
@ismail1432 No, looks like X-Requested-With is not set when I click "back arrow".

![2lqduiz](https://user-images.githubusercontent.com/2453329/38146122-dcf403ca-344c-11e8-9da7-09b86b9a88de.png)

**Comment by dmaicher** [comment]
I believe its your browser that is serving a "cached" response? So the request does not even reach symfony when you "go back" in the browser? Can you check that?

**Comment by ostrolucky** [comment]
OP says it works in Symfony 3.3, so that's not gonna be the case

**Comment by dmaicher** [comment]
@ostrolucky well in the screenshot I see "Status Code: 200 (from disk cache)" and "Request Headers: Provisional headers are shown" so I would not be so sure...

**Comment by kironet** [comment]
@dmaicher Looks like you're right. I disabled cache in chrome's dev panel and it's ok...
Any ideas how to deal with this?

**Comment by dmaicher** [comment]
Are you using `Content-Type: application/json` for the json response? In the screenshot it seems like its `text/html`?

And you are sure with Symfony 3.3 you are not having those issues?

**Comment by kironet** [comment]
Oh, I looked at my old code and now remember that I was struggling with this and used different technique(checking if callback parameter exist in a url).

And yes I'm using Content-Type: application/json, just in time when I took the screenshot I was testing Response() and JsonResponse().

PS: Tested int Firefox, Opera same result.

**Comment by grachevko** [comment]
@kironet try to add annotation `@Cache(vary={"X-Requested-With"})` to this action.

**Comment by MustaphaGhlissi** [comment]
You have to add the X-Requested-With header param config : 
'X-Requested-With': 'XMLHttpRequest'
