### ISSUE TITLE
Override alias for given environment

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#26712]
| Q                | A
| ---------------- | -----
| Bug report?      | not sure
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

I have two services implementing one interface. One must be loaded on production, the other on dev or test so in `config/services.yaml` I put 

```yaml
SendinBlue\Organization\DatabaseManager:
        alias: SendinBlue\Organization\LocalDatabaseManager
```

and in `config/packages/prod/services.yaml`:

```yaml
SendinBlue\Organization\DatabaseManager:
        alias: SendinBlue\Organization\DnsCacheDatabaseManager
```

But whatever the environment I always get instances of `LocalDatabaseManager`. Am I missing something? What would be the best way to do that?

**Comment by iltar** [comment]
I think one overwrites the other. What if you put it in `config/packages/dev/services.yaml` instead of `config/services.yaml`?

**Comment by MatTheCat** [comment]
It is working in that case.

That would mean services defined per environment are overriden by those defined globally? Seems counter-intuituve to me.

**Comment by iltar** [comment]
I would personally expect environment specific to overwrite the generic ones, but I'm not sure what the intention is from the framework perspective, perhaps someone else can clear this up :sweat_smile:

**Comment by MatTheCat** [comment]
Oh gawd just found it. File must be `config/services_prod.yaml` -_-
