### ISSUE TITLE
[Config] Add "and()" method as an alternative to "end()"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26711]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Today I was looking at [this DSL of the Spring Framework SAML feature](https://github.com/spring-projects/spring-security-saml-dsl/blob/929b94b349e894f17a7ff89375446b48f1c7f637/samples/spring-security-saml-dsl-sample/src/main/java/com/example/SecurityConfiguration.java#L21-L41) and I noticed that they use `and()` instead of `end()` in their fluent interface.

So I wonder if we could add the `and()` method as a synonym of `end()` for those who prefer that alternative. Comparison:

## Config with end()

```php
$node
    ->children()
        ->scalarNode('class')->isRequired()->cannotBeEmpty()->end()
        ->scalarNode('property')->defaultNull()->end()
        ->scalarNode('manager_name')->defaultNull()->end()
    ->end()
;
```

## Config with and()

```php
$node
    ->children()
        ->scalarNode('class')->isRequired()->cannotBeEmpty()
        ->and()->scalarNode('property')->defaultNull()
        ->and()->scalarNode('manager_name')->defaultNull()
    ->end()
;
```

**Comment by iltar** [comment]
That actually looks a lot more readable! :+1:

**Comment by iltar** [comment]
Hm to be fair, I read it from the perspective for each child, the same way I'd read SQL, it didn't come up to me as it could ever be part of the `scalarNode('class')`, but this could be related to the way it's formatted.

**Comment by Aerendir** [comment]
I think that one way of doing something is better to maintain consistency.

And this and() notation is also more confusing: I think we should not rely on formatting to make code clear.

The end() method clearly states that the configuration of a node ends. And() notation suggests that we are adding something to the previous node and this is confusing. IMHO.

**Comment by sstok** [comment]
👎 There no direct connection between the nodes, each Node method creates a new builder that you close or "end". `and()` feels a bit strange here, it would make sense when building an expression (with multiple conditions) or when you chain operations, but not here;

`->scalarNode('class')->isRequired()->and()->cannotBeEmpty()->end()` (a little verbose)

The spring example is actually about composing a result/object that is used as a whole, it would make sense for the Config Component when you use methods to compose or combine something with a fluent method call (like we have for DI DSL 🤤 or something @ro0NL used for the phpmsg configuration builder https://github.com/msgphp/msgphp/blob/master/src/EavBundle/DependencyInjection/Configuration.php#L55).

**Comment by javiereguiluz** [comment]
Let's close this proposal as "won't fix" because it doesn't have enough support from the community. Thanks!
