### ISSUE TITLE
Checking that the bundle is autoloaded FAILED

### ISSUE THREAD

**Issue by kirbygit** [symfony/symfony#26720]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Symfony version  | 2.8

When generating bundle it is not somehow completed and got this message in my terminal
<img width="1280" alt="screen shot 2018-03-30 at 1 30 55 pm" src="https://user-images.githubusercontent.com/20747057/38152891-b86e2c52-341e-11e8-8f36-2f52dfc0a658.png">

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by kirbygit** [comment]
Thanks got it
