### ISSUE TITLE
[RFC] [Graph] Introduce a non-oriented graph management

### ISSUE THREAD

**Issue by Simperfit** [symfony/symfony#26724]
| Q | A
| ---------------- | -----
| Bug report? | no
| Feature request? | no
| BC Break report? | no
| RFC? | yes
| Symfony version | 4.2 or 4.3

Today
------

The Workflow component works with workflow and state machines, based on the workflow-net implementation.

Statement
----------

The point is why not be able to support more than that, support writing non-oriented graph ?

It will not be based on the workflow-net implementation.

But I think we need a new implementation to be able to write non-oriented non-weighted/weighted graphs and to dump them. (it could contain like a Dijkstra implementation in order to find the shortest path).

What for ?
----------

There are existing implementation in PHP in order to create trees and non-oriented graphs, but as symfony support creating workflows and state machines, why not supporting creating trees and non-oriented graphes ?

It could be used to manage decision trees, or simply to be able to modify graph coming from a graph database or to read directly from it with tools written directly in symfony.

How is that RFC coming ?
---------------------

Thinking back of the discussion (this night) with @stof about the workflow component at SymfonyLive Paris made me think, why couldn't we implement this in Symfony ?

Thanks for reading this RFC.

If this is something we want to do, I will be glad to open a pull request containing the first implementation.

cc @lyrixx

**Comment by javiereguiluz** [comment]
For people like me who don't know this topic well this description is a bit vague. Which problem can't be solved with Workflow and could be solved with this proposal? Could Workflow be improved to solve this problem too? Could you show some simple code example (using pseudo-code if needed) to see this in action? Thanks!

**Comment by Simperfit** [comment]
@javiereguiluz I'm working on a simple exemple using some part of the workflow component. I try to push as soon as possible.

The RFC here is indeed not about adding a new component but improving the workflow component with this new feature.

**Comment by xabbuh** [comment]
While I can see that some part of the Workflow component (and possibly the DI component as well) could benefit from a common graph component I doubt that graphs itself are something that is common enough to be part of the Symfony core. So I am not sure if we really want to invent such a component.

**Comment by Simperfit** [comment]
Thanks for reading this Christian, as I said if we can ( and I will try too
if the core team thinks it can be a new big feature of symfony) it should
be implemented in the workflow component even if the workflow is a
sub-element of the graph. Do you think, this way it does make more sens ?

**Comment by jkufner** [comment]
If you need to visualize the graphs, take a look at [Grafovatko](https://grafovatko.smalldb.org/).

**Comment by nicolas-grekas** [comment]
We can, but we would need a broad enough use case. I'm as @xabbuh: I don't see it right now.

**Comment by stof** [comment]
I don't see a use case for turning thr workflow component into a generic graph component (most features we have today in the component are specific to workflows and would not make sense at all in a generic graph component btw).

**Comment by stof** [comment]
and I also fail to see which kind of features you would like to see implemented in such a graph component (just having a way to visualize such a graph with graphviz without any other does not justify a graph IMO)

**Comment by fabpot** [comment]
Let's close for now then.
