### ISSUE TITLE
Percent-encoded special characters for database password confused as a parameter

### ISSUE THREAD

**Issue by robolmos** [symfony/symfony#26721]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.6

I'm experiencing an issue with a database password that contains special characters like symbols for the DATABASE_URL parameter in ".env" in combination with Doctrine.

Doctrine expects the URL to be rawurlencode()ed, and that seems to work fine if there's only one special character, but with two or more special characters there's a warning and it doesn't work.

**Working case:**

DB pass: abc@123
.env DATABASE_URL='mysql://test:abc%40123@127.0.0.1:3306/test'

[test@test-web-1 html]$ php console doctrine:query:sql 'show tables'
int(0)

**Non-working case:**

DB pass: abc@@123
.env DATABASE_URL='mysql://test:abc%40%40123@127.0.0.1:3306/test'

[test@test-web-1 html]$ php console doctrine:query:sql 'show tables'
 [WARNING] Some commands could not be registered:
In srcDevDebugProjectContainer.php line 9385:
  The parameter "40" must be defined.

_... no int(0) output; command does not run_

I seems to be an issue with Symfony interpreting the percent-encoded values as parameters or services.

**Comment by nicolas-grekas** [comment]
That's correct, and expected, this line in your configuration gives special meaning to `%`:
https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml#L19

You either need to escape the `%` by doubling them. You can also remove the `resolve:` prefix in your configuration if you don't need parameter resolution there.

Closing as there is no bug here.

**Comment by nehemiekoffi** [comment]
You can set your especial charater password directly in config/packages/doctine.yml like I did and it worked fine for me 
       # I'm adding my database credentials with espacial character password
        dbname: 'app_bd'
        host: 'localhost'
        port: 3306
        user: 'root'
        password: 'sDF90dd@InE@'
check this link for more info : https://symfony.com/doc/current/reference/configuration/doctrine.html

**Comment by fnagel** [comment]
I love how this is not documented.

**Comment by xabbuh** [comment]
We will happily review any pull request improving the current state.
