### ISSUE TITLE
Programmatically disabling the profiler doesn't optimize the memory usage

### ISSUE THREAD

**Issue by bilel-noomene** [symfony/symfony#26722]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.6

I'm trying to import data from a CSV file to a table in the database with the data validation. To do this, I use the form component for data transformation and validation. I had a problem with memory consumption.
My simplified code looks like this:

```
public function importCSV($filePath)
    {
        $reader = Reader::createFromPath($filePath)->setHeaderOffset(0);
        $line = 0;
        $offset = 0;
        $batchSize = 10;
        $batchesNumber = ceil($reader->count() / $batchSize);

        $start = memory_get_usage();
        
        for ($i = 0; $i < $batchesNumber; $i++) {
            $statement = (new Statement())->offset($offset)->limit($batchSize);
            $offset += $batchSize;
            $line++;
            $records = $statement->process($reader);

            foreach ($records as $record) {
                $form = $this->formFactory->create(CustomFormType::class);
                $form->submit($record);

                if ($form->isValid()) {
                    $this->em->persist($form->getData());
                } else {
                    // log ...
                }
            }

            $this->em->flush();
            $this->em->clear();

            echo 'line ' . $line . ' : ' . round((memory_get_usage() - $start) / 1048576, 2) . " MB \n";
        }
    }
```
I got is the following result:

> line 10 : 8.94 MB 
> line 20 : 20.24 MB 
> line 30 : 31.56 MB 
> line 40 : 42.81 MB 
> line 50 : 56.2 MB 
> …..
> line 130 : 146.48 MB 
> line 140 : 157.72 MB 
> (1/1) OutOfMemoryException
> Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388608 bytes)
> 
> 
After debugging, I realized that the memory leak comes mainly from the profiler. 
When I disable the profiler
```
framework:
    profiler: { enabled: false }
```
the import is done correctly and I get the below result:

> line 10 : 5.35 MB 
> line 20 : 7.59 MB 
> line 30 : 4.72 MB
> …..
> line 880 : 32.1 MB 
> line 890 : 33.62 MB 
> line 900 : 30.23 MB

When I tried to disable the profiler programmatically ($ profiler-> disable ()), nothing is written in the profiler web interface but I got almost the first result as if the profiler is activated.

Is there a way to prevent the profiler from consuming memory?

**Comment by iltar** [comment]
Have you tried using the validator directly on data objects, rather than creating a form per row and submitting it? This is not what forms are used for and might case unwanted side effects.

**Comment by bilel-noomene** [comment]
@iltar I need to use the data transformers. In addition, the form can automatically load associations.
Actually, I'm trying to implement a generic solution that can be used for other entities.

**Comment by iltar** [comment]
> I need to use the data transformers

You can use "data transformers" while building your data object. Simply query what you need and insert it.

> the form can automatically load associations

The form simply uses doctrine to do so, so can you (https://stovepipe.systems/post/avoiding-entities-in-forms)

> I'm trying to implement a generic solution that can be used for other entities

My proposal is generic enough

**Comment by ostrolucky** [comment]
Yes, logs are collected even if profiler is disabled. This is for profiler to have logs even in case when user decides to enable it mid-session.

I bet problem goes away if you run it with `prod` env, or when you set `kernel.debug` to false, correct?

**Comment by ostrolucky** [comment]
This is because even if you disable profiler, debug loggers are still kept registered. I bet you will need to remove DebugProcessor from monolog handler stack.

**Comment by ostrolucky** [comment]
I think leak will be in \Symfony\Component\Form\Extension\DataCollector\EventListener\DataCollectorListener. Try to overwrite services registered via form_debug.xml.

**Comment by bilel-noomene** [comment]
@iltar I understand your concerns. But in my case, I work on entities that are dedicated to the import. Once the data is validated and stored in the import tables, it will be transformed into other tables via other entities. This import entities therefore looks like the DTO you mentioned in the post.

IMO using the data transformers seems a little complex. I have to make a long switch-case. In addition, I have to handle the transformation errors myself and combine them with the errors generated by the Validator. I feel that I will reproduce the work already done by the form component.

> might be interesting for you: https://symfony.com/blog/new-in-symfony-3-2-csv-and-yaml-encoders-for-serializer

I work with the League\CSV library which is more dedicated to csv files handling. But the result is the same: an associative array.

**Comment by bilel-noomene** [comment]
I changed my code to build the form once and clone it for each record.
@ostrolucky The service I had to override is data_collector.form:
```
class FormDataCollector extends BaseFormDataCollector {
    public function collectSubmittedData(FormInterface $form) {
        if ($form->getConfig()->getOption('disable_data_collection')) {
            return;
        }
        parent::collectSubmittedData($form);
    }
    public function buildPreliminaryFormTree(FormInterface $form) {
        if ($form->getConfig()->getOption('disable_data_collection')) {
            return;
        }
        parent::buildPreliminaryFormTree($form);
    }
}
```
I use the `disable_data_collection` option in the form to disable data collection.
Finally it gave an acceptable result.

But I still think that the data collectors shouldn't work when the profiler is disabled. It can restart collecting data when it's activated again.

**Comment by ogizanagi** [comment]
@bilel-noomene : Instead, you could replace the `form.type_extension.form.data_collector` service to not add the `DataCollectorListener` when setting a `disable_data_collection` option to `true`.

I don't know if this is worth a patch in the core. 
Perhaps it makes sense for tests, where the profiler might be enabled, but collect only enabled on a per need basis.
The thing is it'll probably require exposing a new `Profiler::isEnabled()` method, and add check in different places, including the `DataCollectorTypeExtension` & `ResolvedTypeFactoryDataCollectorProxy` services, just for this use-case.

<details>
<summary>See patch</summary>

```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/Resources/config/form_debug.xml b/src/Symfony/Bundle/FrameworkBundle/Resources/config/form_debug.xml
index 525b18c57b..678b471aec 100644
--- a/src/Symfony/Bundle/FrameworkBundle/Resources/config/form_debug.xml
+++ b/src/Symfony/Bundle/FrameworkBundle/Resources/config/form_debug.xml
@@ -12,12 +12,14 @@
                 <service class="Symfony\Component\Form\ResolvedFormTypeFactory" />
             </argument>
             <argument type="service" id="data_collector.form" />
+            <argument type="service" id="profiler" />
         </service>
 
         <!-- DataCollectorTypeExtension -->
         <service id="form.type_extension.form.data_collector" class="Symfony\Component\Form\Extension\DataCollector\Type\DataCollectorTypeExtension">
             <tag name="form.type_extension" extended-type="Symfony\Component\Form\Extension\Core\Type\FormType" />
             <argument type="service" id="data_collector.form" />
+            <argument type="service" id="profiler" />
         </service>
 
         <!-- DataCollector -->
diff --git a/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php b/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php
index 068d5cc0bf..247da5a4a5 100644
--- a/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php
+++ b/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php
@@ -15,6 +15,7 @@ use Symfony\Component\Form\Extension\DataCollector\FormDataCollectorInterface;
 use Symfony\Component\Form\FormTypeInterface;
 use Symfony\Component\Form\ResolvedFormTypeFactoryInterface;
 use Symfony\Component\Form\ResolvedFormTypeInterface;
+use Symfony\Component\HttpKernel\Profiler\Profiler;
 
 /**
  * Proxy that wraps resolved types into {@link ResolvedTypeDataCollectorProxy}
@@ -26,11 +27,13 @@ class ResolvedTypeFactoryDataCollectorProxy implements ResolvedFormTypeFactoryIn
 {
     private $proxiedFactory;
     private $dataCollector;
+    private $profiler;
 
-    public function __construct(ResolvedFormTypeFactoryInterface $proxiedFactory, FormDataCollectorInterface $dataCollector)
+    public function __construct(ResolvedFormTypeFactoryInterface $proxiedFactory, FormDataCollectorInterface $dataCollector, Profiler $profiler = null)
     {
         $this->proxiedFactory = $proxiedFactory;
         $this->dataCollector = $dataCollector;
+        $this->profiler = $profiler;
     }
 
     /**
@@ -38,6 +41,10 @@ class ResolvedTypeFactoryDataCollectorProxy implements ResolvedFormTypeFactoryIn
      */
     public function createResolvedType(FormTypeInterface $type, array $typeExtensions, ResolvedFormTypeInterface $parent = null)
     {
+        if ($this->profiler && !$this->profiler->isEnabled()) {
+            return $this->proxiedFactory->createResolvedType($type, $typeExtensions, $parent);
+        }
+
         return new ResolvedTypeDataCollectorProxy(
             $this->proxiedFactory->createResolvedType($type, $typeExtensions, $parent),
             $this->dataCollector
diff --git a/src/Symfony/Component/Form/Extension/DataCollector/Type/DataCollectorTypeExtension.php b/src/Symfony/Component/Form/Extension/DataCollector/Type/DataCollectorTypeExtension.php
index 5c4076d060..99631403e7 100644
--- a/src/Symfony/Component/Form/Extension/DataCollector/Type/DataCollectorTypeExtension.php
+++ b/src/Symfony/Component/Form/Extension/DataCollector/Type/DataCollectorTypeExtension.php
@@ -15,6 +15,7 @@ use Symfony\Component\Form\AbstractTypeExtension;
 use Symfony\Component\Form\Extension\DataCollector\EventListener\DataCollectorListener;
 use Symfony\Component\Form\Extension\DataCollector\FormDataCollectorInterface;
 use Symfony\Component\Form\FormBuilderInterface;
+use Symfony\Component\HttpKernel\Profiler\Profiler;
 
 /**
  * Type extension for collecting data of a form with this type.
@@ -28,10 +29,12 @@ class DataCollectorTypeExtension extends AbstractTypeExtension
      * @var DataCollectorListener
      */
     private $listener;
+    private $profiler;
 
-    public function __construct(FormDataCollectorInterface $dataCollector)
+    public function __construct(FormDataCollectorInterface $dataCollector, Profiler $profiler = null)
     {
         $this->listener = new DataCollectorListener($dataCollector);
+        $this->profiler = $profiler;
     }
 
     /**
@@ -39,7 +42,9 @@ class DataCollectorTypeExtension extends AbstractTypeExtension
      */
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
-        $builder->addEventSubscriber($this->listener);
+        if (!$this->profiler || $this->profiler->isEnabled()) {
+            $builder->addEventSubscriber($this->listener);
+        }
     }
 
     /**
diff --git a/src/Symfony/Component/HttpKernel/Profiler/Profiler.php b/src/Symfony/Component/HttpKernel/Profiler/Profiler.php
index a97d63b05f..fead28faa7 100644
--- a/src/Symfony/Component/HttpKernel/Profiler/Profiler.php
+++ b/src/Symfony/Component/HttpKernel/Profiler/Profiler.php
@@ -59,6 +59,11 @@ class Profiler
         $this->enabled = true;
     }
 
+    public function isEnabled(): bool
+    {
+        return $this->enabled;
+    }
+
     /**
      * Loads the Profile for the given Response.
      *
```

</details>

**Comment by bilel-noomene** [comment]
> Instead, you could replace the form.type_extension.form.data_collector service to not add the DataCollectorListener when setting a disable_data_collection option to true.
Yes, I did it.
I also tried the patch. It solves the problem.
Thanks

**Comment by nicolas-grekas** [comment]
Closing as this is expected and a solution has been provided to change the default behavior.
