### ISSUE TITLE
[Form] Scale parameter of IntegerType is ignored

### ISSUE THREAD

**Issue by dlabouesse** [symfony/symfony#26734]
As described is the [documentation](https://symfony.com/doc/3.4/reference/forms/types/integer.html#scale), this parameter is supposed to set the number of decimal before rounding. 
Whatever the value of this parameter is, there is no any decimal after rounding (which may make sense regarding the form field type name although not in accordance with its documentation).

As `IntegerType` is the only  form field type being rendered as a `type="number"` HTML field type, it would be great to restore rounding behavior depending of `scale` parameter.

This issue can be illustrated by this unit test to be added to _IntegerTypeTest_ class:
```
    public function testRoundingWithScale()
    {
        $form = $this->factory->create(static::TESTED_TYPE, null, array('scale' => 2));
        $form->setData('12345.67890');

        $this->assertSame('12345.67', $form->createView()->vars['value']);
    }
```

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.6

**Comment by xabbuh** [comment]
In your example test you are never submitting any data. So if I do not misunderstand your issue, scale should never be used in your example.

**Comment by xabbuh** [comment]
Okay, I think I now understand your issue. IMO we need to update the documentation to remove the reference too the `scale` option for the `IntegerType`.

**Comment by dlabouesse** [comment]
Thanks for your reply.
So you mean you would definitely remove the `scale`option of the `IntegerType`? Then, how would you render a `type="number"` HTML input field, that handles decimal numbers? Is there an other way to do that?

**Comment by xabbuh** [comment]
I am not sure I understand what you mean. Why would you want to care about decimals for an integer?

**Comment by dlabouesse** [comment]
Because `NumberType` is rendered as a `type="text"` HTML input field, so browsers doesn't show keyboards adapted to numbers only. 
As `IntegerType` is the only type being rendered this way, I would use it for numbers that may be integers or not, as described in the [documentation](https://symfony.com/doc/3.4/reference/forms/types/integer.html#scale).
I know that it's confusing regarding it's name, but I did not found any other way to natively handle decimal numbers with adapted HTML rendering. BTW, as the default scale is 0, it keeps well the behavior of an integer by default.

**Comment by xabbuh** [comment]
I still think that using the `IntegerType` for that use case isn't the right approach. IMO you are better off with using a custom form type that the extends the built-in `NumberType` and renders as an HTML `number` type.

**Comment by dlabouesse** [comment]
Thank you. You're right, I can override the `NumberType` rendering only, or even create a custom type extending it as well.
So it makes sense to remove the `scale` section from the `IntegerType` documentation, restricting its usage for integers only, as suggested by its name.

BTW, I've been overriding the default rendering of `NumberType`in order to get `number` HTML type, but I've found it may cause issues depending of user's locale with browsers supporting only a period as decimals separators for `value` HTML attribute.
Although theoretically supported, I'm now convinced that using properly `number` HTML type for decimal numbers is pretty tricky, especially when working with different locales...

**Comment by xabbuh** [comment]
@dlabouesse Do you think there is anything we should still do in the core to ease anything or shall we close here? Would you like to open a pull request to update the documentation as discussed?

**Comment by dlabouesse** [comment]
@xabbuh, everything's ok for me. I've opened the [pull request](https://github.com/symfony/symfony-docs/pull/9542) to update the documentation accordingly to our discussion.
