### ISSUE TITLE
Clear cache timeout while creating symfony/skeleton project

### ISSUE THREAD

**Issue by mahadev-env** [symfony/symfony#26733]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

**composer create-project symfony/skeleton projectName** is failing with this error

```
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "'/usr/local/Cellar/php71/7.1.14_25/bin/php' '--php-ini=/usr/local/etc/php/7.1/php.ini' 'bin/console' --ansi cache:clear" exceeded the timeout of 300 seconds.
```
Composer version 
1.6.3 2018-01-31 16:28:17

Php version 
PHP 7.1.14 (cli) (built: Feb  2 2018 08:42:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

See the attached file for details ( -vvv option )

[symfony_clear_cache_timeout.txt](https://github.com/symfony/symfony/files/1866619/symfony_clear_cache_timeout.txt)

**Comment by xabbuh** [comment]
Does increasing PHP's maximum execution time help to resolve the issue?

**Comment by nicolas-grekas** [comment]
the timeout is on the Process component that runs cache:clear
can you try adding the `--no-scripts` flag, then running `bin/console cache:clear`?

**Comment by mahadev-env** [comment]
@xabbuh Increasing execution time did not help.

**Comment by mahadev-env** [comment]
@nicolas-grekas Yes That's how I am doing it right now to handle this issue. But this is not a permanent solution for me. I need to execute the `auto-scripts` for doing other important things automatically.

**Comment by mahadev-env** [comment]
It has also affected my previous symfony projects. I am getting the same error while doing `composer update`.

**Comment by nicolas-grekas** [comment]
How long does the manual `bin/console cache:clear` command take? if its slow also, can you try profiing to know why? are you inside a VM with cache and log folders on a shared folder?

**Comment by xabbuh** [comment]
@mahadev-env Can you answer @nicolas-grekas' questions?

**Comment by DrummerKH** [comment]
Guys, i have solved my issue of maximum execution time. The reason was because of with configured xDebug PhpStorm listen it on default 9000 port and php. My xDebug configured with autostart always. On console commands i just disable listening of xDebug port by PhpStorm and it continues. Here is the button:
![_ _06_07_18__10_56](https://user-images.githubusercontent.com/6223175/42369787-504da212-810b-11e8-96f3-f24da2438137.png)
My be it will help someone.
I have spent a lot of time on this issue.

**Comment by xabbuh** [comment]
Thanks for the feedback. 👍 I am closing here then.
