### ISSUE TITLE
Flag all cookies as Secure

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#26731]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | n/a
| Symfony version  | n/a

As per @xabbuh 's suggestion on this other issue https://github.com/symfony/symfony/issues/26667#event-1551012664 I believe that it's a problem when I set the flag for `Secure` Session Cookies but it doesn't affect the rest of the cookies that I have.

I believe that two global parameters to flag **all Cookies** as `Secure` as well as `HttpOnly` automatically (not just the Session Cookie) could provide a great enhancement to the framework, due it might help developers to increase the security of their projects on an easier way than the current case, where I need to add a new `Kernel.ResponseListener` to check for all existing cookies and re-set all of them with Secure flag in the event that they aren't.

Although I could use an update like this on several projects starting from Symfony 2.8 and ending on Symfony 4.x, I don't know if this is something that could be implemented on all these Symfony versions.

Happy to discuss!

**Comment by curry684** [comment]
It's a new feature so it should go in master. However I do think it should also deprecate the session cookie setting as I'm not sure there would be a reason to just flag the session cookie and not others, unless you are on multiple domains, which should be configurable anyway in this feature.

**Comment by nicolas-grekas** [comment]
I don't think we should change the default globally, as that would break portability (like "ini settings")
Thus I'd be :-1: here.

But for the session, see #28244 and #28338

**Comment by DavidGarciaCat** [comment]
Hi @nicolas-grekas 

For log in session, this was not a problem, as it was discussed with @xabbuh 

If you believe this could break previous settings when moving to newer versions, then I would suggest thinking about this with another parameter, as I was suggesting. My point is that seems useless to ask me if I want to secure my Session Cookie but any other cookie is set by default with no security.

Maybe this can be included on next major release but seems useless to create an Event Listener to check all cookies on `kernel.response` to change this flag, instead Symfony could do this automatically based on an existing parameter, like:

`null` or `false` => do nothing (keep same behaviour)
`true` => secure the cookie automatically

Do you think this might be a problem?

**Comment by nicolas-grekas** [comment]
I do, because that would make the setting global. I.e. bundles wouldn't be able to know what is the default. That's the exact same issue as with PHP ini settings.

**Comment by nicolas-grekas** [comment]
See #28447

**Comment by DavidGarciaCat** [comment]
Thanks, @nicolas-grekas - I'll follow the progress of that PR with high expectations!
