### ISSUE TITLE
Valid Constraint causes 500 error

### ISSUE THREAD

**Issue by Atiragram** [symfony/symfony#26744]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

```
class Module {

    /**
     * @var FileUpload
     *
     * @ORM\ManyToOne(targetEntity="FileUpload", cascade="all")
     * @ORM\JoinColumn(name="intFileUploadId", referencedColumnName="intFileUploadId", nullable=false)
     *
     * @Assert\NotNull(message="Upload File cannot be null.", groups={"FileNotNull"})
     * @Assert\Valid(groups={"FileNotNull"})
     */
    protected $file;
```

Class Module has property file and since v3.4 where groups param for Valid constraint was added it raises 500 error if file is null.
![photo_2018-04-02_15-41-53](https://user-images.githubusercontent.com/7505581/38196553-6b5b15fe-368c-11e8-97e5-e347223518a5.jpg)

**Comment by xabbuh** [comment]
Looks like you need to update. This was fixed in #25297.
