### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Could not load type "fa_top_search": class does not exist.")

### ISSUE THREAD

**Issue by jojivijay** [symfony/symfony#26746]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.4

I am getting error like
An exception has been thrown during the rendering of a template ("Could not load type "fa_top_search": class does not exist.").
while upgrading symfony 2.7 to 3 and 3.4

**Comment by xabbuh** [comment]
I am closing here as this does indeed look like a misuse. Feel free to provide more information and we can consider to reopen.
