### ISSUE TITLE
Disallowed HTTP verbs throw 404 instead of 405

### ISSUE THREAD

**Issue by tehplague** [symfony/symfony#26759]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.7

Symfony 4.0.7 now throws an HTTP 404 (Not Found) when you perform a request with a method excluded in the route configuration (e.g. when there are only routes supporting GET and you perform a POST). Previously (tested with 4.0.6) this used to be a HTTP 405 (Method not allowed) that IMHO fits better in this case. At least, if this behaviour was desired, it breaks BC.

**Comment by nicolas-grekas** [comment]
Don't you have also a trailing slash issue?
It should still throw a 405 on method missmatch, but if there is also a missing trailing slash, it now throws a 404, which is more correct.

**Comment by tehplague** [comment]
The affected route is the / one (although restricted to a certain hostname) so AFAIK no trailing slash issue.

**Comment by nicolas-grekas** [comment]
I just tried to reproduce this (allow only `GET` on `/`, and I get a 405 when hitting with a `POST`) and it works.
Can you provide a reproducer please?

**Comment by nicolas-grekas** [comment]
Wait, on 2.7 it works as expected, but not on 3.4. I'm on it.
