### ISSUE TITLE
Dynamic load of forms with cascade events at multiple levels

### ISSUE THREAD

**Issue by nzurita** [symfony/symfony#26761]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.15

Hello, this is a feature request, not a bug report (I guess). To dynamically load form contents, like a select list for an entity or choice type, we have the posibility to use form events and there are some tutorials to do so. When this load involves multiple levels and the events are fired in cascade, this events mechanism, is, to say the less, not developer friendly, I've seen some tutorials but always find them difficult to adapt to my own needs.

The method I actually would prefer is handling events with pure Ajax, calling controller methods from javascript that return a JSON with dynamic new values, but here is the problem: if I load a select field (choice or entity) with options that where not present when the form was created I receive some errors:

> ConstraintViolation
> TransformationFailedException: message: "Unable to reverse value for property path "XXX": The choice "40" does not exist or is not unique"
> TransformationFailedException: message: "The choice "40" does not exist or is not unique"

So my request is to allow developers to choose a server based mechanism, like form events, or an ajax based method, allowing new values for choice and entity fields. Maybe what I'm asking crashes completely with the Symfony way of doing things :-P but I don't think I'm the only one who finds cascade form events not developer friendly.

Thank you

**Comment by xabbuh** [comment]
This looks like the same as #9310 to me. So I am going to close here as a duplicate.
