### ISSUE TITLE
Twig_Error_Syntax  Unknown "abbr_class" filter.

### ISSUE THREAD

**Issue by aBanhidy** [symfony/symfony#26766]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.6.7

I've just run composer update and updated my system form Symfony 3.4.6 to 3.4.7. Result is:

- Twig_Error_Syntax Unknown "abbr_class" filter.
- ServiceCircularReferenceException Circular reference detected for service "routing.loader", path: "routing.loader".

I would like to ask some help what I have to do to resolve them. If I drop away this updates my application works fine.

Thanks and sry if there is already an opened issue with same topic.

**Comment by nicolas-grekas** [comment]
Should be fixed by #26758

**Comment by aBanhidy** [comment]
Ohhh....I see! Thanks the fast answer!

**Comment by fabpot** [comment]
Let's close then.
