### ISSUE TITLE
[HttpKernel][Bug] ServiceValueResolver fails if controller namespace starts with a backslash in routing.

### ISSUE THREAD

**Issue by mathieutu** [symfony/symfony#26772]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.

Hi,
I've seen a problem when configuring my routes:
> Controller "App\Controllers\Foo" requires that you provide a value for the "$foo" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

 
```yaml
# config/routes.yaml
foo:
    methods: POST
    path: /foo
    controller: \App\Controllers\Foo
```

```php
// src/Controllers/Foo.php
class Foo
{
    public function __invoke(FooService $foo, Request $request)
    {
        // ...
    }
}
```

The `services.yaml` is properly configured: Foo is tagged as a 'controller.service_arguments' and `FooService` is correctly autowired, and can be seen in `php bin/console debug:autowiring`.

The service locator is correctly generated in container cache.

When debugging, I've seen that in the `\Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver::supports` method, the controller passed to the route (`"\App\Controllers\Foo"`) is searched in container factories (`["App\Controllers\Foo" => (...)]`) and not found because of the first backslash of the namespace.

The router find the proper controller with this backslash, so in my opinion the ServiceValueResolver should not fail at this point.

The following PR fixes this issue: https://github.com/symfony/symfony/pull/26773

Thanks for you work.

**Comment by xabbuh** [comment]
The failure is excepted and I would not change that. Otherwise, this would be the only part of the framework where you could reference a service by something that looks like its ID. I think we should rather improve the error handling here to make it more clear what is going wrong.

**Comment by mathieutu** [comment]
@xabbuh The problem is that in the routing you actually can register the controller with this backslash. And if you don't try to inject services directly in method, it will work perfectly.

It fails only when you want to inject the service in the controller method. 

If the failure is normal, it has to fail much earlier and always, during the routing with a `Controller not found`, and not during the argument resolving phase just for some case.
