### ISSUE TITLE
web-profiler-bundle update from v4.0.5 to v4.0.7 breaks

### ISSUE THREAD

**Issue by alcohol** [symfony/symfony#26784]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe?
| Feature request? | no
| BC Break report? | maybe?
| RFC?             | no
| Symfony version  | 4.0.x

Related project commit: https://github.com/alcohol/paste.robbast.nl/commit/1c1a1da627627751acfa510b672027019f96f210
Related travis build: https://travis-ci.org/alcohol/paste.robbast.nl/jobs/361979916

I use only a few Symfony components, so maybe that is why it does not work as expected; when updating `web-profiler-bundle` from [v4.0.5 to v4.0.7](https://github.com/symfony/web-profiler-bundle/compare/v4.0.5...v4.0.7) all my web-tests started to fail because the application cannot generate a route due to a missing parameter or something (should flex not have auto-updated the configuration or is this route not part of the default config of the profiler "bundle"?).

```
Symfony\Component\Routing\Exception\RouteNotFoundException: 
Unable to generate a URL for the named route "_profiler_open_file" as such route does not exist.
```

Did I screw up the whole way flex is supposed to be used and such? :p

**Comment by alcohol** [comment]
My fault, I was missing a `test` environment config directory/files.

**Comment by xabbuh** [comment]
Your former config will work again in 4.0.8 (see #26758).

**Comment by alcohol** [comment]
Oh. Well https://github.com/alcohol/paste.robbast.nl/commit/3dba93ae120609ef968d8d489298aa6492de7a67 also fixed it for me. What is the difference exactly?

**Comment by xabbuh** [comment]
The route the WebProfilerBundle was trying to generate a route for is usually only registered in the `dev` environment. That broke when you enabled the profiler for tests (where you do not need the visible toolbar but only the data collector) as the bundle still tried to generate the path for the now unexistent route. Your workaround will make sure that there always is the needed route, the fix in Symfony will only try to generate it when necessary.

**Comment by k00ni** [comment]
I ran into this issue this morning and adding the yaml files, as described in https://github.com/alcohol/paste.robbast.nl/commit/3dba93ae120609ef968d8d489298aa6492de7a67, fixed it for me. Thanks @alcohol

**Comment by stof** [comment]
you don't need to register WebProfilerBundle in tests. This bundle is **not** responsible for the profiling itself (FrameworkBundle is). It is only the web UI.

**Comment by k00ni** [comment]
> you don't need to register WebProfilerBundle in tests. This bundle is not responsible for the profiling itself (FrameworkBundle is). It is only the web UI.

You are right, but without this "hack", my Controller tests failed.

**Comment by stof** [comment]
Well, registering the bundle without registering its routes is indeed broken in 4.0.7. But you don't even need to register the bundle at all in tests (unless you tests are about ensuring that the toolbar itself is properly injected)

**Comment by alcohol** [comment]
@stof but registering it the test environment is the default according to the recipe: https://github.com/symfony/recipes/blob/master/symfony/web-profiler-bundle/3.3/manifest.json

**Comment by stof** [comment]
hmm, indeed (but why ?)

**Comment by alcohol** [comment]
> but why ?

Beats me.. 😶

**Comment by alcohol** [comment]
Maybe unittests are considered a dev thing, whereas test is seen more in the traditional sense of a DTAP flow?
