### ISSUE TITLE
[Sf 3.4.7] Circular reference detected for service "routing.loader" on cache clear

### ISSUE THREAD

**Issue by mmendjeli** [symfony/symfony#26793]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 3.4.7

Hello,

Updating one of our project from Sf 3.4.4 to 3.4.7 i see an error at cache:clear  command or any other cli command from the console.

```
./app/console cache:clear --no-warmup --env=local (same for dev)

In Container.php line 297:

  Circular reference detected for service "routing.loader", path: "routing.loader".
```

Try to check our routing import but did not found any duplicate... anyway it is only appearing when updating to 3.4.7 .

Did something changed related to this subject? do we need to take care of something in special in our configs?

Thx

**Comment by xabbuh** [comment]
see #26755 (this was fixed in #26758 and will be part of the next release).
