### ISSUE TITLE
Using throws_at disables logging

### ISSUE THREAD

**Issue by joeyhub** [symfony/symfony#26790]
When I enable strict mode with:

    debug.error_handler.throw_at: 32767

Errors simply vanish. The HTTP error code is set and exception subscribers are invoked but the errors are no longer logged anywhere at all.

Symfony 3.4

**Comment by joeyhub** [comment]
/**
     * Sets a response and stops event propagation.
     */
    public function setResponse(Response $response)
    {
        $this->response = $response;

        $this->stopPropagation();
    }

The bug is here. You've put in stopPropagation.

Setting the priority to -255 also doesn't work so basically people should just echo as the work around.

**Comment by joeyhub** [comment]
Workaround:

(new Response())->send() instead of $event->setResponse(new Response())

**Comment by nicolas-grekas** [comment]
@joeyhub does this mean you know how to fix the issue? Would you like to submit a PR?

**Comment by nicolas-grekas** [comment]
Actually, re-reading your comment, these are totally unrelated part of the code.
Turning PHP errors to exceptions make them take the path of all other exceptions.
Unhandled ones should be logged for sure (but handled one are handled, so the handler take the responsibility to do what it wants with them.)

**Comment by nicolas-grekas** [comment]
Can you provide a reproducer please (ie a repo someone could clone and is preconfigured to reproduce the issue?)

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
