### ISSUE TITLE
Annotation assertions not detected on Windows

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#26809]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.7

We have an issue on doctrine dbal with an assertion as annotation not being detected and the test being marked as risky on Windows:

> This test did not perform any assertions
OK, but incomplete, skipped, or risky tests!

Here is a PR where I tried to isolate the issue as much as possible: https://github.com/doctrine/dbal/pull/3087, leaving only a class and its test.

[The test code](https://github.com/greg0ire/dbal/blob/isolate_risky_test/tests/Doctrine/Tests/DBAL/FooTest.php):

```php
<?php

namespace Doctrine\Tests\DBAL\Schema;

use Doctrine\DBAL\Foo;

class ColumnTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @group legacy
     * @expectedDeprecation Hi
     */
    public function testThatIsGoingToBeRisky() : void
    {
        new Foo();
    }
}
```

The subsequent appveyor build: https://ci.appveyor.com/project/doctrine/dbal/build/1.0.114/job/3nke06rul3e04598

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/symfony/pull/26800?

**Comment by Majkl578** [comment]
I don't think so, Doctrine doesn't use simple-phpunit at all, it only registers a listener: https://github.com/doctrine/dbal/blob/master/phpunit.xml.dist#L57

**Comment by greg0ire** [comment]
Yeah, not sure how it would relate to this bug anyway, but I can try with `dev-master`, just to be sure.

**Comment by greg0ire** [comment]
Just pushed a commit that should make the build failed (I changed the expectedDeprecation message). It doesn't.

**Comment by greg0ire** [comment]
Ah I think the Windows build simply use a different configurations, and I didn't add the listeners, let me check.

**Comment by greg0ire** [comment]
Stupid mistake, it works just fine, sorry for bothering you with this.
