### ISSUE TITLE
Web Profiler Bundle v4.0.7 breaks clearing cache in test env.

### ISSUE THREAD

**Issue by tdbui22** [symfony/symfony#26805]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | v4.0.7

The changes to the web-profiler-bundle v4.0.7 causes this error
[Symfony\Component\Routing\Exception\RouteNotFoundException]
  Unable to generate a URL for the named route "_profiler_open_file" as such route does not exist.

When clearing cache with test env.
APP_ENV=test bin/console cache:clear

In v4.0.6 the Resource/config/profiler.xml in the web-profiler-bundle had the service id debug.file_link_formatter using straight arguments whereas in v4.0.7 it is using a factory and uses the router to generate the url which the route does not exists in the test env.

**Comment by dmaicher** [comment]
Can you check if it was fixed by https://github.com/symfony/symfony/pull/26758 ?
