### ISSUE TITLE
[EventDispatcher] Possible bug in test

### ISSUE THREAD

**Issue by a-s-y-n-c** [symfony/symfony#26810]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

Hi, on [this line](https://github.com/symfony/event-dispatcher/blob/606803460db12e1997cbde2504dfdd0175798885/Tests/AbstractEventDispatcherTest.php#L161) `$otherListener->preFoo` is registered as a listener.

Is this not a bug? 3 lines later, the `$otherListener->postFooInvoked` is checked. The only way it could ever change to `true` is by `$otherListener->postFoo` being called...

The test is passing, but I was wondering if this is not a "false positive".

Thanks.

**Comment by xabbuh** [comment]
@a-s-y-n-c This indeed looks like a mistake. Would you like to submit a pull request?

**Comment by a-s-y-n-c** [comment]
Yes, I will submit it today 👌 Thanks!

**Comment by xabbuh** [comment]
Thanks @a-s-y-n-c!
