### ISSUE TITLE
[DX] Jump to Exception in Chain Using Breadcrumbs

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#26824]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 4.1

Sometimes exception chains can be long:
![image](https://user-images.githubusercontent.com/1227834/38391241-5426d3dc-38e9-11e8-8ffa-624553f5bf19.png)

In order to get to them developer needs to scroll to a particular one. I suggest we add link with `#` pointing to an exception in chain as well as add ids to each of the foldable boxes with exceptions.

This small change will allow to quickly jump to interesting exception just by clicking on the top bar.

WDYT?

**Comment by javiereguiluz** [comment]
I think it's a brilliant idea to make this page more usable! @kiler129 would you like to give a shot at this and send a pull request? Thanks!

**Comment by kiler129** [comment]
@javiereguiluz: Sure, I will submit PR today :)
