### ISSUE TITLE
dom-crawler ignores field checkbox

### ISSUE THREAD

**Issue by rvasquezz** [symfony/symfony#26827]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | dev-master

dom-cralwer does not handle the tilde checkbox. takes by default the hidden input

```

<form action="#">
<input id="chkgrupo1_2" name="chk_chkgrupo1_2" onfocus="saveFocusedControl(&quot;chkgrupo1_2&quot;);" style="position: absolute; top: -0px; right: -2px; vertical-align: middle;" tabindex="14" title="" value="1" type="checkbox">
<input name="chk_chkgrupo1_2" value="1" type="hidden">
</form>
```
Here my code
$form = $crawler->selectButton('Continuar')->form();
$form['chk_chkgrupo1_2']->tick(); 
$crawler = $client->submit($form);

> FatalThrowableError (E_ERROR)
Call to undefined method Symfony\Component\DomCrawler\Field\InputFormField::tick()

**Comment by xabbuh** [comment]
I am not convinced this qualifies as a bug. How is the crawler supposed to know that you are interested in the checkbox when both fields have the same name?

**Comment by stof** [comment]
Yeah, this case was already rejected in the past. The DomCrawler won't support cases with 2 fields with the same name, as it references them by name.

**Comment by rvasquezz** [comment]
any solution to this problem?
