### ISSUE TITLE
Simpler testing of security protected resources

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26839]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.2

The [official Symfony solution](https://symfony.com/doc/current/testing/http_authentication.html#creating-the-authentication-token) to log in a user in the app before testing security-protected resources looks like this:

```php
public function testSomething()
{
    $client = static::createClient();

    // --- log in the user ----------------------------------------------------
    $username = 'admin';
    $session = $client->getContainer()->get('session');

    // the firewall context defaults to the firewall name
    $firewallContext = 'secured_area';

    $token = new UsernamePasswordToken($username, null, $firewallContext, array('ROLE_ADMIN'));
    $session->set('_security_'.$firewallContext, serialize($token));
    $session->save();

    $cookie = new Cookie($session->getName(), $session->getId());
    $client->getCookieJar()->set($cookie);
    // --- end of user log in -------------------------------------------------

    // ... test something ...
}
```

I think we can do better. I'd like to have a different way to test security-protected resources. A solution that is simple to use and easy to understand. Thanks!

**Comment by sstok** [comment]
For Park-Manager I created a special Guard Authenticator that allows to provide the username and password (plain) as server variables:

<details>

```php
namespace ParkManager\Bundle\UserBundle\Security;

use ParkManager\Component\User\Security\SecurityUser; // UserInterface implementation
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;

final class BrowserKitAuthenticator extends AbstractGuardAuthenticator
{
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    public function getCredentials(Request $request): array
    {
        return [
            'username' => $request->server->get('TEST_AUTH_USERNAME'),
            'password' => $request->server->get('TEST_AUTH_PASSWORD'),
            'password_new' => $request->server->get('TEST_AUTH_PASSWORD_NEW'), // This is only used when the password changes (properly need to fix this in a better way :-) )
        ];
    }

    public function getUser($credentials, UserProviderInterface $userProvider): ?SecurityUser
    {
        $email = $credentials['username'];
        if (null === $email) {
            return null;
        }

        return $userProvider->loadUserByUsername($email);
    }

    public function checkCredentials($credentials, UserInterface $user): bool
    {
        if (!$user->isEnabled()) {
            throw new AuthenticationException();
        }

        if (!$this->passwordEncoder->isPasswordValid($user, $credentials['password']) &&
            (null !== $credentials['password_new'] &&
             !$this->passwordEncoder->isPasswordValid($user, $credentials['password_new']))
        ) {
            throw new BadCredentialsException();
        }

        return true;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return null;
    }

    public function start(Request $request, AuthenticationException $authException = null): Response
    {
        return new Response('Auth header required', 401);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response
    {
        $data = [
            'message' => strtr($exception->getMessageKey(), $exception->getMessageData()),
        ];

        return new JsonResponse($data, Response::HTTP_FORBIDDEN);
    }

    public function supportsRememberMe()
    {
        return false;
    }

    public function supports(Request $request)
    {
        return $request->server->has('TEST_AUTH_USERNAME');
    }
}
```

</details>

This needs to be registered _after_ the firewalls are registered (in config/packages/test/security.yaml):

```yaml
firewalls:
    main:
        guard:
            entry_point: 'ParkManager\Bundle\UserBundle\Security\BrowserKitAuthenticator'
            authenticators:
                - 'ParkManager\Bundle\UserBundle\Security\BrowserKitAuthenticator'
```

Used as:

```php
$client = self::createClient([], [
    'TEST_AUTH_USERNAME' => 'rick',
    'TEST_AUTH_PASSWORD' => 'never-gonna-give-you-up',
]);

$crawler = $client->request('GET', '/profile');
```

Basically this works similar to HTTP Basic, but keeps the token after the current request (like a log-in form), so you only need it in `createClient` :+1: as a pre-condition.

I am not saying this is perfect but maybe this can be used as a step-up for something better (`test` security firewall listener or something?)

I believe the simplest solution is to set the username and password with the create client (as default) but allow them to change per request (for example a password reset/change operation), you can provide the new password to overwrite the client default (this covers the 90% use-case while still allowing the 10% exceptional use-case).

**Comment by javiereguiluz** [comment]
@sstok thanks for your proposal! However, I was thinking about something easier to learn and use. For example: `login()` and `logout()` methods:

```php
// login when creating the client...
$client = static::createClient();
$client->login('the_username', 'the_password');

// ...or when making a request...
$crawler = $client->login('the_username', 'the_password')->request('GET', '/profile');

// logout for some special request...
$crawler = $client->logout()->request('GET', '/contact');

// ... or logout for all the next requests
$client->logout()
```

Other frameworks like Laravel also lets you pass an object representing the user:

```php
$client->login(UserInterface $theUserObject)->...
```

**Comment by iltar** [comment]
I think the `$client->login` solution looks the cleanest tbh

**Comment by normisg** [comment]
I just created a class in tests directory and put symfony suggested code in it

###
namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\BrowserKit\Cookie;

class ControllerTestCase extends WebTestCase
{

    protected static function createAuthClient(
        array $roles = ['ROLE_USER'],
        array $options = array(),
        array $server = array()
    ) {
        $client = parent::createClient($options, $server);
        $session = $client->getContainer()->get('session');

        // the firewall context defaults to the firewall name
        $firewallContext = 'main';

        $token = new UsernamePasswordToken('bonzo', null, $firewallContext, $roles);
        $session->set('_security_'.$firewallContext, serialize($token));
        $session->save();

        $cookie = new Cookie($session->getName(), $session->getId());
        $client->getCookieJar()->set($cookie);

        return $client;
    }
.
.
.
###

Than just used it when I need.

namespace App\Tests\Controller;

use App\Controller\SecurityController;

class SecurityControllerTest extends ControllerTestCase
{

    public function testUserCanNotOpenAdmin()
    {
        $client = self::createAuthClient();
        $client->request('GET', '/admin');
        $this->assertTrue($client->getResponse()->isForbidden());
    }

.
.
.

**Comment by Pierstoval** [comment]
I also implemented something similar here: https://gist.github.com/Pierstoval/db09556cff141aada5b608a26b23f260 , there's one for native WebTestCase and another one for Panther.

Most implementations tend to use the same kind of system.

To me, a clean solution would be to implement a mix of all existing solutions, and provide an additionnal argument for the firewall name. We could even make the firewall name totally optional and default to "the first firewall with active security" ( = not the "dev" one).

Also, important thing here, I'm not sure this logic should be put in the Client class, but rather in the WebTestCase itself, with a trait maybe, to make it customizable by the end user (which wouldn't be possible if put in the Client class)
