### ISSUE TITLE
official docker images?

### ISSUE THREAD

**Issue by laurencefass** [symfony/symfony#26848]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
no
| Feature request? | yes/no
no
| BC Break report? | yes/no
no
| RFC?             | yes/no
no
| Symfony version  | x.y.z
4

I would very much like to have access to an instant symfony flex site built on best practices with all tools preinstalled. 
Do you publish official docker images? If not do you have any plans to? 
Thanks.

**Comment by ismail1432** [comment]
HI 👋 
There is no official image but you can see these links https://github.com/mykiwi/dockerfiles and https://github.com/dunglas/symfony-docker

**Comment by javiereguiluz** [comment]
We just need to ask ourselves if we should publish official Docker images. Have projects comparable to Symfony published their own Docker images?

This is very important because Docker is one of the biggest things in the tech landscape ... and it looks like it's going to get much bigger.

**Comment by ismail1432** [comment]
IMHO we should provide this solution to avoid most common installation problem.
Api platform 
https://github.com/api-platform/api-platform and it works like a charm

**Comment by curry684** [comment]
What is the point of having a Docker image with a framework that is in itself a building block for applications that are themselves candidates for Docker images?

To me it makes as much sense as having Docker images for the C++ stdlib or the PHP Xdebug extension. Building blocks are built into other images, not into their own.

**Comment by bitgandtter** [comment]
I agree with @curry684 the a common Dockerfile for symfony or any other framework include steps to build, install libraries, copy source files, execute custom steps, etc. A base image of symfony cant provide any of this steps. Maybe the question is if symfony can provide a set of Dockerfiles which could be used for our constructions

**Comment by ostrolucky** [comment]
Doesn't make sense to me either. Symfony is a framework, not a service. @laurencefass what's your goal? You want just preconfigured LEMP stack? Chosen stack would have be very opinionated and many people wouldn't like that.

**Comment by ismail1432** [comment]
So why Symfony provide an easy way to use the PHP built it server if nobody need it ? 
I think most of people copy the same basic  Docker file for each new Symfony project.
The idea is just to create one « official »

**Comment by ismail1432** [comment]
Thanks @curry684

**Comment by ro0NL** [comment]
Also have a look at [Lando](https://github.com/lando/lando), which utilizes Docker. Building a LEMP stack with Symfony is really super easy, here's how i did it: https://github.com/ro0NL/symfony-lando

**Comment by ZipoKing** [comment]
IMHO Symfony Docker images by itself will not work as previous guys said, Symfony is only a framework to build other apps. All you need is Docker image with PHP of your need (and probably composer + some PECL/PEAR packages but it also may be made with small Dockerfile) and things will work fine.

**Comment by mleczakm** [comment]
Looks like a really good idea - IMHO we should provide inside symfony-skeleton base dockerfile (it is really easy to maintain) which allows to run symfony with only docker on host.

**Comment by GromNaN** [comment]
To run a Symfony app in Docker, the base is a PHP image with required extensions and some php.ini configuration (timezone). This can be a php-fpm or php-cli image. It might be possible to create de Composer plugin that generate a Dockerfile with the extensions required by the project.

Then, an ngnix or Apache vhost must be configured.

**Comment by tgalopin** [comment]
What about integrating this into Flex, to provide a recipe for a basic Dockerfile and allow packages to add elements into this Dockerfile like in the env file? It would be the best way IMO.

**Comment by mhujer** [comment]
Related Flex issue: https://github.com/symfony/flex/issues/54 and PR: https://github.com/symfony/flex/pull/128

**Comment by ro0NL** [comment]
Also related.. instead of images a docker-compose in symfony/symfony would be nice, to run the tests :)

**Comment by Guikingone** [comment]
I don't think having an official image is preferable, Symfony is a light-weight framework since Flex and providing an image can be counterproductive due to the fact that what if the developers don't want to use Docker but Vagrant or other?

I know that using Docker is optional but as long as you have PHP or a PHP image in your desktop, Symfony can work like a charm.

For me, it could be way more valuable to have a full configuration (using Docker-Compose and Kubernetes) for Symfony, this way, we can both use the advantages of Docker and Kubernetes and keep the framework away from the usage of Docker is the developer doesn't want it.

**Comment by dkarlovi** [comment]
This was rejected in https://github.com/symfony/symfony-standard/issues/992

**Comment by covex-nn** [comment]
Official docker image (or images) could contain compiled php extensions and instructions how to install them with `RUN apk add` / `RUN apt-get install` and `COPY --from=symfony/php ...`

**Comment by curry684** [comment]
Speaking from experience I stopped using the official PHP images altogether as they're bloated and the `docker-php-ext-install` command and its kin are a mess. Instead I just use `debian:stretch-slim` as a base image and install Sury packages into them. More fine-grained control, less build issues, builds 10 times faster, and to top it all gives smaller images as a bonus.

Had too many issues with Alpine packages being severely outdated as well, hence Debian Slim.

**Comment by curry684** [comment]
If it's to be published somewhere with enough readers sure. Like I said it's hardly Symfony specific but I've got a lot of experience in deploying various PHP applications via Docker. I could also set up an example repo with Nginx, Redis etc.

Just don't expect anything soon as I'm swamped in work hehe, and I've also got stuff to do on my own bundles.

**Comment by webda2l** [comment]
Yes the debian:stretch-slim + Sury packages sound interesting.
See https://github.com/search?q=debian%3Astretch-slim+sury&type=Code whose nice Akeneo version https://github.com/akeneo/Dockerfiles/blob/master/php/7.2/Dockerfile

**Comment by covex-nn** [comment]
Official docker image `php:7.2.6-fpm-stretch` contains a [layer with $PHPIZE_DEPS](https://github.com/docker-library/php/blob/cf5482724142c2c249c7f873b0f7f4910e502b63/7.2/stretch/fpm/Dockerfile#L32-L37). It is **200Mb** (i used `docker save php:7.2.6-fpm-stretch > stretch.tar` to check, all files are not zipped there), all layers for PHP image (without debian) take **316Mb**. Debian's layer takes **56Mb**

Images, based on `debian:stretch-slim`, that uses Sury packages, will not contain a layer with `phpize`, and php-containers will be smaller! I found some [Dockerfile](https://github.com/edyan/docker-php/blob/master/7.2/Dockerfile), removed some tweaks, simplified and made my own [Dockerfile](https://github.com/covex-nn/docker-php7.2/blob/master/Dockerfile) just with `php-fpm`. Two my layers take **73Mb** =)

**Comment by Simperfit** [comment]
@curry684 still busy ?

**Comment by curry684** [comment]
Permanently    😉   but it also kinda got off my radar for lack of a publishing platform. Not sure it would still be needed now a year later.

**Comment by fabpot** [comment]
Let's close this one as I don't see how a Docker image for Symfony would help anyone. As other people said, there is nothing Symfony specific. We might have some docs about how to use Docker though.

**Comment by Aerendir** [comment]
+1 for the docs!
