### ISSUE TITLE
[Dotenv] Tell component to override

### ISSUE THREAD

**Issue by natebrunette** [symfony/symfony#26846]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

We use this component in development with Docker. We like to put defaults for environment variables in the Docker config, but we let developers override those values in the `.env` file. After switching to the Symfony component, we realized that those overrides were no longer happening.

The `Dotenv` class could accept an optional flag that would tell it if it should override system environment variables. It could default to `false` to maintain BC.

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR doing so?

**Comment by fmata** [comment]
I gave a try in #26859 because my team needs this feature too. I hope it's ok :)
