### ISSUE TITLE
[Console] - Add support to declare more then one environment on cache:clear command parameter --env

### ISSUE THREAD

**Issue by lockland** [symfony/symfony#26842]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

Whereas we have at least 3 environment on symfony and all off them permit us to use cache, sometimes things go wrong because of these cache corruption and perform a cache clear is necessary, however run the command for every environment one by one isn't agile, so to add support for more then one environment on --env parameter seems coolest: e.g
```
$ php bin/console cache:clear --env test,prod,dev
```

**Comment by nicolas-grekas** [comment]
just do 
`echo test prod dev | xargs -n1 php bin/console cache:clear --env`

**Comment by lockland** [comment]
Is it documented on somewhere?
I read a lot of documentation looking for it and I couldn't find anywhere. Anyway, it will work on Unix-like OS only because I will depend on at least two unix commands, so if I have programming on windows I won't be able to use this.

Does Symfony provide some solution for this problem which works on Windows, Linux, Unix and etc?

**Comment by javiereguiluz** [comment]
If you just want to delete all environments, the command I always run to clear the cache (and the command that is popular too among Symfony Slack people) is just `rm -fr var/cache/*`

**Comment by Tobion** [comment]
You can also create an alias or a custom script. I don't think this needs to be solved in symfony core.

**Comment by nicolas-grekas** [comment]
I agree with @Tobion, this shouldn't be solved in symfony core. Thanks for the proposal.

**Comment by lockland** [comment]
Can Someone tell me what should?

I am asking this because you all have created a feature that do something wrong on the symfony core and now to change this behavior shouldn't be doing in the core.

How is it possible?

But OK, thanks for you taking time to read this proposal.
