### ISSUE TITLE
[Profiler] events.html.twig cannot display on 4.1

### ISSUE THREAD

**Issue by FroggDev** [symfony/symfony#26855]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1.0

Testing the 4.1-dev master

When i click on the Events links of the profiler page i get this error message:

Neither the property "event" nor one of the methods "event()", "getevent()"/"isevent()"/"hasevent()" or "__call()" exist and have public access in class "Symfony\Component\VarDumper\Cloner\Data".

```
Twig_Error_Runtime
in vendor\symfony\web-profiler-bundle\Resources\views\Collector\events.html.twig (line 81)
                <th class="text-right">Priority</th>  
                <th>Listener</th>            
          </tr>       
 </thead>
 {% set previous_event = (listeners|first).event %}
```
The project is almost empty at the moment : https://github.com/FroggDev/Symfony_StockManager

Same code tested on 4.0, and profilier event is working. 

Thanks

**Comment by xabbuh** [comment]
I cannot reproduce your issue. The only thing I see is a 404 page as no route was found to handle the request. But I can then open the profiler and also open the events section there.

**Comment by FroggDev** [comment]
I made an updated this morning and it seems fixed now.

If you are insterested, this was the composer configuration when the bug occuerd:

```
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.2@dev",
        "symfony/asset": "dev-master",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/form": "dev-master",
        "symfony/framework-bundle": "dev-master",
        "symfony/maker-bundle": "^1.0@dev",
        "symfony/monolog-bundle": "^3.0@dev",
        "symfony/orm-pack": "dev-master",
        "symfony/security-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "^3.2@dev",
        "symfony/translation": "dev-master",
        "symfony/twig-bundle": "dev-master",
        "symfony/validator": "dev-master",
        "symfony/webpack-encore-pack": "dev-master",
        "symfony/yaml": "^4.0"
    },
    "require-dev": {
        "sensiolabs/security-checker": "^5.0@dev",
        "symfony/dotenv": "^4.0",
        "symfony/profiler-pack": "dev-master",
        "symfony/thanks": "^1.0@dev",
        "symfony/web-server-bundle": "dev-master"
    },
```

**Comment by FroggDev** [comment]
Tested on php 7.2 with server:run & on Apache 2.4 with php 7.2, with same result

This is the url to vsualize the tool bar event error:
https://test.frogg.fr

**Comment by ostrolucky** [comment]
Confirmed. Can be reproduced with barebones symfony/website-skeleton. All you need to do is make it trigger controller action. It's caused by 509f9a923399c5e1c624f0c4e814f2f87a78034b @kejwmen can you check this?

**Comment by kejwmen** [comment]
@ostrolucky thanks, prepared PR to fix this
