### ISSUE TITLE
[RFC] Favor 200 OK instead of 404 not found status for default homepage

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#26858]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

Hi,

I like to propose a `200 OK` response for the default homepage when no routing is configured. I.e. the page showing:

```
You're seeing this page because debug mode is enabled and you haven't configured any homepage URL.
```

It currently is a `404 Not Found`.

I've no strong opinion about one or another, however using 404 causes e.g. [Lando](https://github.com/lando/lando) to think the service is not working, as it checks its URL to see if it's up.

So im not sure who's to blame here :) but they said basically:

> Oh Symfony, everyone else throws a 200

I think 200 OK is at least reasonable and fixes the Lando "issue" (it's just annoying on CLI to see it try and keep checking while in fact the service is working already).

Thoughts?

**Comment by Tobion** [comment]
👎 200 would make it inconsistent with prod mode.

**Comment by ro0NL** [comment]
Well.. it's a feature enabled by debug=true. So put different; it might be reasonable to say 200 with debug=true vs. 404 with debug=false, also given we actually route `/` with debug=true to a welcome page.

**Comment by EarthSchlange** [comment]
What you are proposing sounds like there would be a default page and route not just a 200 Status OK from the server. I am good with that setup, but I am not with having the server return a Status 200 OK if there is nothing there. A 404 error should be there if there is no default route or page setup at that location.

**Comment by javiereguiluz** [comment]
I disagree too with this proposal. `404` is what's really happening when you don't configure a homepage route and browse the homepage ... we just show a beautiful error page (in fact we call it the "Welcome Page") ... but we cannot hide the fact that this is a `404` error and not a `200 OK` page.

**Comment by ro0NL** [comment]
:+1: im not really convinced either :) ill see if i can fix this on lando's side.
