### ISSUE TITLE
How to make file versioning work in emails sent?

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#26853]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

In emails I send it seems the versioning doesn't work.

While in the front end all assets are loaded correctly, reflecting the `manifest.json` file generated on build by Webpack Encore, this doesn't happen in emails and the files always have their original name, without the version nonce.

I'm generating the assets paths through the `asset` function:

    <img src="{{ absolute_url(asset('/build/assets/App/images/logos/logo-blue.png'))}}" />

The generated URL in the email is then

    <img src="https://ci4.googleusercontent.com/proxy/s2bbJt2lnZDyjaUmQ2cMsWt2mUw6vHIsHT4FzvRguN-MlSw5HuezokfMNRxvan2LeiloGVyjIVoJXuWYjW5em0irIsaN1XYs11ZeiGscATfqfSfGG1aA6KmVcxqe1Jg=s0-d-e1-ft#http://127.0.0.1:8000/build/assets/App/images/logos/logo-blue.png" >

As you can see it is `http://127.0.0.1:8000/build/assets/App/images/logos/logo-blue.png` while in the frontend it is something like `<img src="/build/assets/App/images/logos/logo-blue.6bbd877e.png" />`.

So, why the versioning isn't working in emails? Any ideas?

**Comment by javiereguiluz** [comment]
I guess this is because you generate the emails outside of the web environment, so Symfony doesn't have information about the real hostname, the port, etc. It may be the same case as generating absolute URLs in console commands. See https://symfony.com/doc/current/console/request_context.html in case it helps to solve your problem.

**Comment by Aerendir** [comment]
Hi @javiereguiluz , thankyou for your reply.

I've already set the schema and the host in the `request_context` but unfortunately this doesn't work: The path generated are correct and they correctly use the right URL but the name of the resource doesn't include the hash generated by Webpack, so the images are not correctly displayed in the email.

Any otherr idea about how to solve the issue?

**Comment by Aerendir** [comment]
Ok, after a lot of debugging tracing down the flow of data, I found that the orr was on my side as I set the path as this:

    /build/assets/path/to/image.png

Can you spot the error?

I'm using a leading slash and this makes impossible for `JsonManifestVersionStrategy` to find the path in the lookup array.

I think this will cause trouble to others too, so, if all seems to be correctly setup, **check the path you are using to build the asset URL: is MUST not contain a leading slash!**
