### ISSUE TITLE
[Form] Wrong DateType parsing

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony#26865]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

If the form below is submitted with the value "01.07.70" it is parsed as "30.06.0070". If submit this value again, it is parsed as "29.06.0070". With each submission, the date is decreasing by one day.

````
    /**
     * @Route("/test")
     */
    function testAction(Request $request)
    {
        $form = $this->createFormBuilder()
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd.MM.yyyy',
            ])
            ->getForm();

        $form->handleRequest($request);

        return new Response(
            $this->get('twig')
                ->createTemplate('{{ form(form) }}')
                ->render(['form' => $form->createView()])
        );
    }
````

**Comment by xabbuh** [comment]
This seems to be caused by the same root cause as #16368. So I am going to close here as a duplicate.
