### ISSUE TITLE
[Security] remember_me secret cannot access to env(APP_SECRET) or kernel.secret on 4.1

### ISSUE THREAD

**Issue by FroggDev** [symfony/symfony#26860]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

In the version 4.1 the secret parameter cannot read the global secret

```
            remember_me:
                secret:   '%env(APP_SECRET)%'
```
or even

```
            remember_me:
                secret:   '%kernel.secret%'
```

return the error 

```
The path "security.firewalls.main.remember_me.secret" cannot contain an empty value, but got "".
```

The same code works without trouble on 4.0

**Comment by ro0NL** [comment]
Hi @FroggDev it's a duplicate of https://github.com/symfony/symfony/issues/26747 right?

That's fixed in https://github.com/symfony/symfony/pull/26799 already :)

**Comment by xabbuh** [comment]
Closing as a duplicate of #26747. But please feel free to provide more information if you still experience the issue and we can reopen.

**Comment by FroggDev** [comment]
I updated to last version and it is fixed, sorry about it !
