### ISSUE TITLE
SimpleAutheticationProvider anonymous user handle

### ISSUE THREAD

**Issue by BerislavSapina** [symfony/symfony#26871]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

Two commits that are added in class SimpleAuthenticationProvider break our application.

Commit #1: c318306b446c64c7fa5b9097129b3cdb1355e0c5
Commit #2: cb9c92d06553f60a0b7b6b036c4b2a3c1813e738

Problem is when I have a token class that have anonymous user. So in getUser() i get an empty string. ('')

Also in last version it wasn't necessary to pass $user object, now it is. 

It is needed to find way how to handle public token when we have anonymous user. 

Corresponding PR #26370 

Thanks for your time :D

**Comment by BerislavSapina** [comment]
Hi, even if I add `anonymous: ~` in my firewall, still SimpleAuthenticationProvider is called and there it breaks.

**Comment by BerislavSapina** [comment]
This one ```if (empty($user)) {
            return $authToken;
        }``` 
will resolve my problem. I do not know is the best solution ??

**Comment by BerislavSapina** [comment]
You are right. I agree with you :D

**Comment by aschempp** [comment]
> What about an early return if $token instanceof AnonymousToken to restaure the previous behavior?

Be aware that this is not necessarily correct. At least for the `AuthenticationTrustResolver`, the token class that is supposed to be considered anonymous can be configured: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Resources/config/security.xml#L8

**Comment by iltar** [comment]
parameters are not an extension point you should rely on. Previously all parameter based class names for services were removed. I'm not sure why this one still exists, because it's extremely fragile to make a token like this. I didn't find any documentation on this either.

**Comment by aschempp** [comment]
I totally agree, just saying you can configure the *ToBeConsideredAnonymousToken* in the trust resolver, so just assuming `AnonymousToken` is the one to look for is not necessarily true 😉

**Comment by NaxYo** [comment]
Same issue here, breaking on version 2.8.38. Similar scenario with 'anon.' user token from a custom authenticator.

I'm trying to understand the AnonymousToken + UsernameNotFoundException think, but can't really get it working just with changes on my Authenticator and Provider... am I missing something?

**Comment by chalasr** [comment]
See #27044
