### ISSUE TITLE
Event Dispatcher on Router:generate

### ISSUE THREAD

**Issue by cpaulsen1812** [symfony/symfony#26876]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x

in some cases we need a redirection before the route is generated, instead of change all the router and add the condition if condition else ... inside controller, services and twig templates and blow up the code we can do this a Event Subscriber or Listener very easy...

change on config:
router.default add:

```xml
<call method="setEventDispatcher">
    <argument type="service" id="event_dispatcher" />
</call>
```
change for the Router:
`property: $eventDispatcher`
method:
`public function setEventDispatcher(?EventDispatcherInterface $eventDispatcher = null) : Router; ....`

change Router:generate method, add additional functionality:
```php
public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH) {
    if ($this->eventDispatcher) {
        $event = new RouterGenerateEvent($name, $parameters, $referenceType);
        $this->eventDispatcher->dispatch(RouterGenerateEvent::PRE_GENERATE, $event); /* new Event ... */
        $name = $event->getRoute();
        $parameters = $event->getParameters();
        $referenceType = $event->getReferenceType();
    }

    return $this->getGenerator()->generate($name, $parameters, $referenceType);
}
```
if you need a working example ask :-)

**Comment by iltar** [comment]
This would cause a pretty big overhead when generating a route and I don't see how this is an expected flow. This is a side effect that can also happen during template rendering and such. What if I generate the route via a command?

> in some cases we need a redirection before the route is generated

Why do you need to redirect when generating a route? It doesn't really make sense to me.

**Comment by xabbuh** [comment]
I agree with @iltar. And if you really want to do that, you could still implement it in your own URL generator that would then decorate the one from core.

**Comment by nicolas-grekas** [comment]
Closing as discussed, thanks for the proposal.
