### ISSUE TITLE
metadatabag is breaking session laziness

### ISSUE THREAD

**Issue by cosma** [symfony/symfony#26887]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.13

According to https://symfony.com/doc/3.4/reference/configuration/framework.html#metadata-update-threshold  the metadata update treshold configuration is not needed anymore because
"Starting in Symfony 3.4, session data is only written when the session data has changed. Previously, you needed to set this option to avoid that behavior."
Unfortunately,  this is not quite true in reality used withy the MemcachedSessionHandler which was presented here https://symfony.com/blog/new-in-symfony-3-4-session-improvements.

For consecutive calls with unchanged session, the Memcached adapter is actually using doWrite() instead of  updateTimestamp() because,  internally , Symfony updates at every http request the metadatabag(the update field is always changed).

So we still need to use the `framework.session.metadata_update_threshold` configuration to solve our problem.

**Comment by Tobion** [comment]
This is a documentation issue. Please open it at https://github.com/symfony/symfony-docs
The metadata_update_threshold  says how often the metadata timestamp updates. So when it updates evey requests, it also means the session is written every request because the timestamp changed.

**Comment by cosma** [comment]
Let's say that on consecutive request I am setting the same session key with the same value.
So,  symfony is not comparing the content of the session?
If  I set an already existing key with the same value ,  the metadata bag is change too, hence my behaviour.
Is this the behaviour you want? 
Then,  I should never set anything in a session. 
Where is the laziness then?

**Comment by cosma** [comment]
Moved to https://github.com/symfony/symfony-docs/issues/9920
