### ISSUE TITLE
Error control operators in various files

### ISSUE THREAD

**Issue by gtbono** [symfony/symfony#26888]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.5

Hello,

I don't know if this is exactly an issue, maybe I'm the one who's not understanding it.

I recently created a new Symfony 3.4.5 project using Composer, and in the root of the default directory structure, I've ran the following regular expression in a Linux terminal:

`grep -rs '@[a-z]\+('`

Which should pick everything that begins with an @, and a to z characters repeated more than once, which should pick up the PHP error control operator http://php.net/manual/en/language.operators.errorcontrol.php and It surprised me because there were lots of ocurrences, and to my knowledge, error control operators are code smells which we should try to avoid.

My question is there are a reason why they are there? the functions that the operator is applied maybe seem to operate with I/O, are there any motives to use them? or are they bugs that we should catch and submit a PR?

For example, this is a snippet from the output of the regular expression command in a vanilla Symfony installation: 
```
symfony/vendor/symfony/http-kernel/HttpCache/Store.php:            @fwrite($fp, $data);           
symfony/vendor/symfony/polyfill-mbstring/Mbstring.php:                $s = @iconv('UTF-8', 'UTF-8//IGNORE', $s);
symfony/vendor/symfony/http-kernel/Log/Logger.php:        if (false === $this->handle = is_resource($output) ? $output : @fopen($output, 'a')) {   
symfony/vendor/symfony/http-kernel/HttpCache/Store.php:            $len = @fwrite($fp, $data); 
```

This is one of my first interactions with this type of issue so tell me if I reported it wrong.

Thanks in advance

**Comment by javiereguiluz** [comment]
You reported this issue correctly ... and you are right ... in theory at least 😄 

Problem is that *"never use @ in your PHP code"* is more a theoretical idea instead of a practical one. If we removed all the `@` operators, our code would be better but our users would hate us because of all the error notifications. I'm afraid we must close this as "can't fix" 😞

**Comment by fabpot** [comment]
Indeed, all usages of the `@` operator have been reviewed many times. They are all required. Thanks for reaching out.
