### ISSUE TITLE
Repeating error code in Constraints

### ISSUE THREAD

**Issue by hilovska** [symfony/symfony#26883]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3 or 3.4. and higher

Hello,
we are working with 3.3 or 3.4. and
I am not sure if it is really a problem, but I noticed, that 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/LessThan.php
and 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/LessThanOrEqual.php
have same TOO_HIGH_ERROR value.
They are only ones from all Constraints like that,
for example https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/GreaterThan.php and https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/GreaterThanOrEqual.php have different values for same constant.

Have a nice day!

**Comment by iltar** [comment]
Nice catch! I think they should be different as they are both a different error, but perhaps someone of the core team can confirm this before I ask you to try and make a PR to fix this :smile:

**Comment by hilovska** [comment]
I was testing, if we will not have repeating codes with yours (or ours), that's how it started.

Well, now, after I added some tests to our new functionality, it is creating a failure, so it would be awesome to repair it... but I have no idea how to make a PR... or what it is. Or how they got these error codes - randomly?

**Comment by javiereguiluz** [comment]
@iltar while we are at this, could we please rethink if using these UUIDs for errors is the best possible solution? We don't do that anywhere else on Symfony and it feels weird (and it can easily introduce bugs, as show in this issue). Thanks!

**Comment by stof** [comment]
@javiereguiluz all our core constraints have error codes being UUID

**Comment by javiereguiluz** [comment]
@stof yes!! I meant in other part of Symfony except the Validator component.

**Comment by iltar** [comment]
I'm not entirely sure if there's a good alternative, as I'm not aware of what problem it actually solves.

**Comment by stof** [comment]
Well, the code is meant to be machine-readable. This is why a UUID was used (an auto-incremented id would have been a pain to manage for contributions)

**Comment by javiereguiluz** [comment]
To be honest, I'm like @iltar and I don't understand why this is needed or which problem do these UUIDs solve. I just find it strange because we don't use this technique in any other component. Also, none of the comparable validator components do this. I like the solution used by Zend Validator because it's exactly what I expected Symfony to do. Example: https://github.com/zendframework/zend-validator/blob/master/src/EmailAddress.php

**Comment by fabpot** [comment]
@javiereguiluz Indeed, having a unique string (which is the case if it includes the class name) would work as well. Anyway, I don't see any problem to fix here, that's purely an internal detail.

**Comment by adamcameron** [comment]
Rightly or wrongly we use these constants to vary our human-readable message back to the user. So as it stands - unlike all other constraints - we cannot rely on these TOO_HIGH_ERROR constants to differentiate between violations of LessThan or LessThanOrEqual.

It's not serious, but it's a real-world bug for us. And now I have to work around it. Fun :-/

As the values are meaningless beyond comparison back to themselves, can't see it being a problem fixing it? Might be considered a backwards compat break though.

**Comment by javiereguiluz** [comment]
@hilovska thanks a lot for reporting this issue. I think it's perfect for a "first Symfony contribution", so I've transformed this issue into a "curated issue for newcomers" in #30285. I'm closing this in favor of the new one. Thanks a lot!
