### ISSUE TITLE
[Twig][DX] report unknown folders in templates/bundles in debug:twig

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#26898]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

Had [an issue](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/557) in FOSOAuthServerBundle where users had a hard time discovering what the proper path for overriding bundle views is (also, me).

A small tweak for `debug:twig` might be to note folders in `templates/bundles` which don't (properly) map to any known bundle?

Say: 
```
Path "templates/bundles/FOSOAuthServer" not matching any bundle found, did you mean "templates/bundles/FOSOAuthServerBundle"?
```

**Comment by pmontoya** [comment]
It's for me!
