### ISSUE TITLE
[HttpKernel] Kernel::getName return the containing path instead of the class name

### ISSUE THREAD

**Issue by symcaster** [symfony/symfony#26904]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.?->4.1

I don't really know if this is a bug, but I'm surprised that the kernel name (displayed in the web profiler toolbar) show the name of the folder that contains the Kernel.php class (for exemple `app` or `src`) instead of the kernel class name? It's like this since long time... Maybe this information was usefull with AppKernel and AppCache?
What do you think?

**Comment by ro0NL** [comment]
See also https://github.com/symfony/symfony/pull/24292 :)

**Comment by romain-pierre** [comment]
Thank you for the reference. So I see two options:

- consider that Symfony 4 rely on an unique kernel so we don't care about the name, and the information can be removed from the profiler
- using the class name (ok there is always a risk of collision but it's still better than using the directory name, if we admit that many projets have all kernel classes in the same directory)
