### ISSUE TITLE
[Security] Dispatch an event when "logout user on change" steps in

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#26902]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 

With the new logout on user change feature the user token is set to `null` when a user was changed compared to the one stored in the session. Right now we cannot hook into this steps to perform some more clean up tasks like what we can do on manual logouts where we can register custom logout success handler, but we would need to manually wrap the `ContextListener` instead.

We should find a way to allow this kind of customisation in the `ContextListener` too to allow for a consistent behaviour between manual and "forced" logouts.

**Comment by iltar** [comment]
Would it count as "forced" logout when the user checker denies access on a request that would've otherwise been authenticated?
