### ISSUE TITLE
[RFC] - Not having constructors for service classes with annotations & traits

### ISSUE THREAD

**Issue by oliverde8** [symfony/symfony#26915]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/maybe
| BC Break report? | no
| RFC?             | yes
| Symfony version  | x.y.z

**Why ?**

Generally speaking creating a cosntructor is not a problem. The issue is when you are extending existing services of "other" applications using symfony(Akeneo & Ez...). For exemple serviceA has a class looking like this : 

```php
<?php
class serviceA {
    protected $propertie1A; 

    public function __construct(InjectedService1A $propertie1A) {
        // ....
    }
}
```

We extend this service to change a particular behavior. 

```php
<?php
class serviceB extends serviceA {
    protected $propertie1B; 

    public function __construct(InjectedService1A $propertie1A, InjectedService1B $propertie1B) {
        // ....
    }
}
```
At this point if the maintainers of `serviceA` changes service A to add a new property you will need to change your `serviceB`. Which is why constructor changes are usually considered BC. I don't like extending services but when changing the behaviours of existing system sometimes it's the only choice. 

**Proposal**

What I thought of  is use annotations & trait to make it a bit magic 

```php
<?php
class serviceA {
    use AutoConstructTrait
    /**
     * @var InjectedService1A
     * @AutoConstructAnnotation()
     */
    protected $propertie1A; 
}
```

With the trait lookingsomething like : 

```
trait AutoConstructTrait {
    public function __construct(...$args)
    {
        $class = get_class($this);
        $properties = AutoConstructAnnotation::getClassProperties($class);

        $count = 0;
        foreach ($properties as $field => $constrains) {
            if (isset($args[$count])) {
                // TODO validate value with constraints? using the type in @var. 
                $this->$field = $args[$count];
            } else {
                throw new \Exception("$class is expecting parameter $field");
                // TODO nice exception.
            }
            $count++;
        }
    }
}
```

**Advantages/Disadvantages :**
:+1: No need to maintain the constructors
:+1: I quite often see new developers putting logic that shouldn't be in constructors in constructors. This would make it less probable.

:-1: : Having annotations for DI, 
:-1: : Instancing the class without the DI is harder as we have no idea what parameter it takes. 

I think it's a interesting subject of discussion, it might be just a waste of time. Whad do you think?

**Comment by oliverde8** [comment]
I really don't like the idea of having annotations on parameters, even less having annotations to configure the DI. I like a lot the current system as it is.

The annotations here are to decide which properties should be in the constructor. If we could avoid that I would be much happier. In other languages you could say that anything that is a `final` property should be in the constructor.

Auto-wiring does not not resolve the issue of maintaining the constructors. It resolve the issue of maintaining the service declaration(yml). 

Maybe someone can have an idea to get this working without annotations and with less drawbacks. If not well we close it.

**Comment by ostrolucky** [comment]
Symfony DI already supports automatic injections for setters if you annotate them. Not sure what exactly do you propose here.

**Comment by nicolas-grekas** [comment]
If I understand well, `serviceA` would provided by a vendor? IMHO, there is no way any reasonable vendor will design their classes this way.

**Comment by nicolas-grekas** [comment]
Closing as that's not something we want to provide in Symfony.
