### ISSUE TITLE
Dynamically using test environment

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#26925]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | Symfony 4.0.8

This is regarding to: https://symfony.com/doc/current/configuration/environments.html#executing-an-application-in-different-environments

> The test environment is used when writing functional tests and is usually not accessed in the browser directly via a front controller.

My Behat tests are broken because they all depend on `sqlite` database and it gets picked up when I use `app_test.php` before version 4. To make it work I have to manually update `.env` file (see below) before running the tests and then revert them manually again while developing which is a pain.

How do we solve this manual problem?

```
# config/packages/test/doctrine.yaml

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        server_version: '3.11.0'
```

```
# .env

###> symfony/framework-bundle ###
#APP_ENV=dev
APP_ENV=test
APP_SECRET=d7f88292186a64eeef558337bb2f0f43
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
#DATABASE_URL=mysql://root:root@127.0.0.1:3306/symfony
DATABASE_URL=sqlite:///%kernel.project_dir%/var/cache/test/database.db
###< doctrine/doctrine-bundle ###
```

**Comment by dmaicher** [comment]
I have 2 different nginx configs using different ports. I use port 80 for dev and pass `APP_ENV=dev` via `fastcgi_param`. For acceptance tests I use port 81 and pass `APP_ENV=test`.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
