### ISSUE TITLE
[RFC] Allow to configure error level by path at `ErrorHandler::handleError()` in order to not throw `ContextErrorException`

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#26924]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.2.0

I'd like to add support to configure ignored paths at `ErrorHandler::handleError()`. I often work with third party libraries which emit `E_NOTICE` or `E_WARNING` errors, and I know that I can not get rid of these issues; but I don't want to silence these error for the rest of my app (`Debug::enable(E_ALL & ~E_WARNING & ~E_NOTICE);`).
In order to silence these 3rd party errors that I know, I'm currently editing by hand `ErrorHandler::handleError()`, adding this condition:
```php
if ($errorAsException && false !== strpos($errorAsException->getFile(), '/vendor/depenendency-with-errors/') && in_array($errorAsException->getSeverity(), [E_WARNING, E_NOTICE], true)) {
    $throw = 0;
}
```
I think the configurable paths could accept an array or a regex with ignored paths.

**Comment by nicolas-grekas** [comment]
That's quite fragile, isn't it?
Can't you fix these instead?

**Comment by phansys** [comment]
>That's quite fragile, isn't it?

I agree that ignoring an error is quite fragile, but when you already know about the well known errors in one of your dependencies, be notified (stopping the execution through a `ContextErrorException`) about these unfixable errors everytime doesn't help. Please, note that I'm not proposing to not collect those errors, but just not throwing an exception for them.
>Can't you fix these instead?

Not really. Sometimes old libraries seems to become abandoned and have very old PRs trying to fix these kind of issues and there is nothing I could do about that (at least, not without maintaining a fork with the fixes by my own).

**Comment by chalasr** [comment]
Unjustified errors should be fixed in the dependency itself, not silenced by the dependent. I don't think the component should ease doing so

**Comment by phansys** [comment]
>Unjustified errors should be fixed in the dependency itself, not silenced by the dependent.

It's clear that this is the way to go, but the cases I'm trying to solve doesn't have a maintainer or someone else working on fixing these errors or even merging PRs which do the work.
So, having no optional replacement for these libraries, the current scenario forces me to disable the debug for the errors that I already know my dependences have, making my own code risky since the disabled debug operates in a plain way over the whole app.
And again, I'm not proposing to silence these ignored errors based on the configured paths, I think they should must be collected as today; I'm just proposing to not throw an exception for them. I think I must reword the issue's title in order to make clearer this aspect.

**Comment by stof** [comment]
I would say that your own issue is that you depend on an unmaintained buggy library.

Adding a fragile feature in Symfony itself because of that looks like a bad idea to me.

**Comment by phansys** [comment]
In my case, one example for these buggy libraries is the official SDK for a support platform (with no opt-in replacement), so as mentioned before, I must trust that SDK AS IS or start to maintain my own fork, taking the responsibility to keep it up to date, following the release process, etc.

**Comment by phansys** [comment]
If the current approach doesn't attempts against the robustness, I think we could analyze at least a solution similar to the deprecations helper implemented at [PHPUnitBridge](https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail), where "weak_vendors" simply collect the errors triggered from vendors, ignoring them at moment to decide which exit code to return.

**Comment by nicolas-grekas** [comment]
IMHO, this is too specific to be put in core. What you could do on your side is register a custom error handler that implements the logic you want (it could wrap Symfony ErrorHandler for sure).

**Comment by phansys** [comment]
Closing since this doesn't have enough acceptation. I'll try to register a custom error handler.
Thank you for your feedback.
