### ISSUE TITLE
phpunit-bridge compatibility with phpunit v7.*

### ISSUE THREAD

**Issue by juliendufresne** [symfony/symfony#26931]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.*

Since [this commit of PHPUnit](https://github.com/sebastianbergmann/phpunit/commit/a7ab2b9b53c88a9020babcd547d6d71279fba087), PHPUnit has added return types to some methods.

This causes some compatibility issue when using PHPUnit version 7 or later and symfony/phpunit-bridge.

For example, the method `Symfony\Bridge\PhpUnit\TextUI\Command::createRunner()` does not specify the return type.

<details>
<summary>Output of `SYMFONY_PHPUNIT_VERSION=7.0 php vendor/bin/simple-phpunit`</summary>

PHP Fatal error:  Declaration of Symfony\Bridge\PhpUnit\TextUI\Command::createRunner() must be compatible with PHPUnit\TextUI\Command::createRunner(): PHPUnit\TextUI\TestRunner in &lt;path&gt;/vendor/symfony/phpunit-bridge/TextUI/Command.php on line 24
</details>

**Comment by nicolas-grekas** [comment]
@greg0ire maybe you'd like to have a look?

**Comment by greg0ire** [comment]
@nicolas-grekas will do

**Comment by geoff-maddock** [comment]
Running into this.  Any fix pending?

./bin/phpunit -v
#!/usr/bin/env php

Fatal error: Declaration of Symfony\Bridge\PhpUnit\TextUI\TestRunner::handleConfiguration(array &$arguments) must be compatible with PHPUnit\TextUI\TestRunner::handleConfiguration(array &$arguments): void in /srv/myapp/vendor/symfony/phpunit-bridge/TextUI/TestRunner.php on line 25

**Comment by greg0ire** [comment]
@geoff-maddock currently looking into it.
