### ISSUE TITLE
[RFC] Improve the "sortByName" algorithm of the Finder — apply "natural ordering" (SortableIterator::SORT_BY_NAME)

### ISSUE THREAD

**Issue by vyshkant** [symfony/symfony#26930]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4.6

Using an `strcmp` algorithm for sorting by name leads to unexpected results.

Suppose we have the next code:

```
$finder = new Finder();

$finder->files()->sortByName()->in('/path/to/directory');

foreach ($finder as $file) {
    echo $file->getBasename().PHP_EOL;
}
```

We are trying to order the next set of files:
<details>
<summary>Files as they are ordered in file manager</summary>

```
foo_0.txt
foo_1.txt
foo_2.txt
foo_10.txt
foo_11.txt
foo_12.txt
foo_100.txt
foo_101.txt
foo_102.txt
foo_1000.txt
foo_1001.txt
foo_1002.txt
```
</details><br>

The order shown above seems to be "expected", because it is used in many of popular file managers ("File Explorer", "Windows Explorer" on Windows, "Nautilus", "Caja" on Linux, etc).

Nevertheless, when you try to get ordered list of these files using Finder, you will be surprized:

<details>
<summary>Files as they are ordered by Finder</summary>

```
foo_0.txt
foo_1.txt
foo_10.txt
foo_100.txt
foo_1000.txt
foo_1001.txt
foo_1002.txt
foo_101.txt
foo_102.txt
foo_11.txt
foo_12.txt
foo_2.txt
```
</details><br>

Moreover, sorting the next file set (as it is shown in a file manager):

<details>
<summary>Files as they are ordered in file manager (1)</summary>

```
foo_1_1.txt
foo_2_1.txt
foo_10_1.txt
foo_11_1.txt
foo_12_1.txt
foo_100_1.txt
foo_101_1.txt
foo_102_1.txt
foo_1000_1.txt
foo_1001_1.txt
foo_1002_1.txt
```
</details><br>

will give the next result:

<details>
<summary>Files as they are ordered by Finder (1)</summary>

```
foo_1000_1.txt
foo_1001_1.txt
foo_1002_1.txt
foo_100_1.txt
foo_101_1.txt
foo_102_1.txt
foo_10_1.txt
foo_11_1.txt
foo_12_1.txt
foo_1_1.txt
foo_2_1.txt
```
</details><br>

I think this kind of sorting is wrong.

## What do I suggest

My suggestion is to create a sorting algorythm, which will return "the same as file manager" files order.

I believe that ideally this new algorithm should be used when calling the "sortByName" method, but even if not, this should be implemented at the Finder component level, because this is a quite common task.

If you agree with my arguments, I will gladly write a PR.

**Comment by vyshkant** [comment]
As far as I managed to find out, PHP provides a built-in [natsort](http://php.net/manual/ru/function.natsort.php) function that makes it possible to compare files with the "natural ordering" algorithm.

**Comment by nicolas-grekas** [comment]
PR welcome of course. If you ca make the behavior opt-in (using a flag somewhere), would be best for BC I suppose.
