### ISSUE TITLE
[VarDumper] ServerDumpPlaceholderCommand should not extend ServerDumpCommand

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26944]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

After updating a Symfony app to `^4.1@dev` I'm seeing this deprecation which I guess should be fixed by Symfony itself:

```
The "Symfony\Component\VarDumper\Command\ServerDumpCommand" class is
considered final. It may change without further notice as of its next
major version. You should not extend it from 
"Symfony\Bundle\DebugBundle\Command\ServerDumpPlaceholderCommand".
```

**Comment by ogizanagi** [comment]
Erf, I thought the noticed would be dropped considering the vendor namespace, but apparently not. 😕
The 2 commands actually are in two different packages.
Anyway, see #26955. Thanks for the issue!
