### ISSUE TITLE
[Security] Deprecated use of the logout_on_user_change option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26943]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

After updating a Symfony app to `^4.1@dev` I'm seeing this deprecation. I don't use the `logout_on_user_change` option myself in any config file, so I guess this should be fixed by Symfony itself:

```
The "security.firewalls.main.logout_on_user_change" configuration
key has been deprecated in Symfony 4.1.
```

**Comment by xabbuh** [comment]
Are you able to trace down what exactly is triggering this deprecation?

**Comment by javiereguiluz** [comment]
I was tracing down this issue and I found that one of my YAML files did include this option. Sorry for the wrong report! The other deprecation reported in #26944 seems to be caused by Symfony though.
