### ISSUE TITLE
console error => cache:clear Memcached >= 2.2.0 is required

### ISSUE THREAD

**Issue by BernardA** [symfony/symfony#26951]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

Whenever I am installing packages with composer as, for instance,:

> composer require beberlei/DoctrineExtensions

, it throws following error when attempting to clear cache as 

> Executing script cache:clear:

> Script cache:clear returned with error code 1
!!  
!!  In MemcachedTrait.php line 84:
!!                                    
!!    Memcached >= 2.2.0 is required 

I do have memcached 3.0.4 enabled, as per php_info(), and I am actually using it extensively on my app. 
Besides being activated at config/packages/doctrine.yaml, I am also using directly in the controllers as

> use Symfony\Component\Cache\Adapter\MemcachedAdapter;

So, it's there. 

I checked [https://github.com/symfony/symfony/issues/25723](url) this question as well, but my php.ini on MAMP already includes that configuration.

Also, when I clear cache directly as follows, the issue does not come up.

> php bin/console cache:clear --no-warmup --env=dev

thanks

**Comment by xabbuh** [comment]
I guess your PHP configuration differs on the CLI from what you are using with the web server. `php -i` will probably give you some useful information.

**Comment by BernardA** [comment]
Well, they look the same.

Here's what php -i tells me concerning memcached

> memcached
memcached support => enabled
Version => 3.0.4
libmemcached version => 1.0.18
SASL support => yes
Session support => yes
igbinary support => no
json support => no
msgpack support => no

**Comment by javiereguiluz** [comment]
@BernardA the code that triggers the error is this one:

```php
        if (!static::isSupported()) {
            throw new CacheException('Memcached >= 2.2.0 is required');
        }
```

But the `isSupported()` method is like this:

```php
    public static function isSupported()
    {
        return extension_loaded('memcached') && version_compare(phpversion('memcached'), '2.2.0', '>=');
    }
```

So the error may be misleading. What could be happening is that `memcached` is not enabled. Add this to `isSupported()` method to check it:

```php
var_dump(extension_loaded('memcached'), version_compare(phpversion('memcached'), '2.2.0', '>='));
```

If the first value is `false`, the reason may be what @xabbuh said. In any case, we should update the error message to mention that Memcached must be enabled and newer than 2.2.0.

**Comment by BernardA** [comment]
As said, it is both installed and enabled. 
First, I am using it and then I showed you the output from php -i that confirms that.

In any case, I did as instructed and here's the output:

> bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true) bool(true)

**Comment by xabbuh** [comment]
Is there a different output when you run `/use/bin/env php -i`?

**Comment by xabbuh** [comment]
I am afraid there is not much we can do in Symfony about that (see also composer/composer#7271).

**Comment by BernardA** [comment]
Ok, I will open this on the composer repository.  I believe that's what you are suggesting, right?

**Comment by xabbuh** [comment]
@BernardA Since there is an existing issue (see my comment above) it should be necessary to open another one.
