### ISSUE TITLE
Safari Top Hit preload leads to LogicException 'You are already switched to %s user.'

### ISSUE THREAD

**Issue by BernhardWebstudio** [symfony/symfony#26952]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | all

If in Safari Browser the feature "Preload Top Hit in the background" is enabled, the LogicException 'You are already switched to %s user.' will be thrown upon entering a ?_switch_user URL with another username than the one suggested by Safari. This issue can be reproduced in Safari with the feature enabled after opening a few user-switch URLs. 

I am honestly not sure if this is an issue which should be fixed in any way other than disabling the feature in the browser, but I wanted to note it here in case anyone is confronted with the same problem. As a fix on Symfony side, I could only imagine allowing to switch user when impersonated (why not?) or finding a hacky way to either detect if the site is being preloaded (redirect via HTML/JavaScript to the "real"-switching-site) or disabling the preload (link rel no preload). I do not consider the latter two realistic respectively sensible and am aware that the first one was already discussed.

Anyway, don't hesitate to close the issue as-is, but I hope someone one day might be thankful for my discovery.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue!

As you guessed, this is probably going to be closed as "can't fix" because the issue is out of our control. But maybe someone can come up with a simple and brilliant solution for this.

**Comment by sstok** [comment]
Does the pre-loading also happen when caching is completely disabled (for the page)?

**Comment by BernhardWebstudio** [comment]
The preload happens as the URL gets completed while entering it. When the _switch_user was called already once with another user, this URL gets suggested as Top Hit and, therefore, preloaded. As Safari does not consider the URLs of the visited site as cache, disabling it does not help, as a test just confirmed. Emptiing the history, in turn, helps, but is not more feasible than disabling the `Preload Top Hit in background` option.

**Comment by stof** [comment]
The way to avoid this issue is to avoid doing user impersonation (which is changing state on the server) through a GET request. Using a POST request would not have this issue, as the form submission cannot be replayed by Safari Top Hit (btw, Chrome used to have a similar behavior in the past. I don't know whether it is still the case). But this would require reworking the user impersonation feature in a non-BC way.

**Comment by chalasr** [comment]
Closing as there is nothing we can do.
