### ISSUE TITLE
"Translator" not working. Symfony 3.4.7, 3.4.8

### ISSUE THREAD

**Issue by nochek07** [symfony/symfony#26953]
**CODE**
```php
// MyBundle/Controller/MainController.php
namespace MyBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class MainController extends Controller
{
    /**
     * @Route("/", name="page")
     * @param  \Symfony\Component\HttpFoundation\Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
         $this->get('translator')->addLoader('yaml', new YamlFileLoader());
         $this->get('translator')->addResource('yaml', __DIR__ . "/../lang/page.ru.yml", "ru", "page");

         return $this->render("default/index.html.twig", array());
    }
}
```
**Symfony 3.4.6**: code works!

**Symfony 3.4.7, 3.4.8**:
```txt
[2018-04-15 20:12:17] translation.WARNING: Translation not found. {"id":"NUMBER","domain":"page","locale":"ru"} []
[2018-04-15 20:12:17] translation.WARNING: Translation not found. {"id":"EXAMPLE","domain":"page","locale":"ru"} []
```

**Comment by iltar** [comment]
I'm not sure if it's intended to load at all, you should be configuring this during the container compilation, not when the action is executed.

**Comment by javiereguiluz** [comment]
@nochek07 it looks like you are complicating your code unnecessarily. It looks like you followed the docs about using the translation component outside of Symfony (https://symfony.com/doc/current/components/translation.html) but you are using it inside Symfony, so everything is simpler.

If you store your translation files in a custom directory, you just need to configure one option. There's no need to enable the YAML loader, etc.

```yaml
framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/page'
            - '%kernel.project_dir%/translations' 
        fallbacks:
            - '%locale%'
```

Also, using a translation domain different than the default `messages` (`page` in your case) will bring you lots of troubles for very little gain (https://symfony.com/doc/current/components/translation.html#using-message-domains). I possible, reconsider this decision and rename your files to `messages.ru.yml`. It will greatly simplify your work in the app.

**Comment by chalasr** [comment]
Closing as unsupported.
