### ISSUE TITLE
[Console] Exception gone from ExceptionListener error context

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#26957]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe
| RFC?             | yes
| Symfony version  | 3.4

Since 3.3 #18140 change the way of handling console errors there is no more `exception` in context, only `error`, but currenty most monolog hanlders consider only `exception` field to possibly contain instance of `\Throwable` to handle automagickally

https://github.com/symfony/symfony/pull/18140/files#diff-bcbaf1687828ceb673942278dfd1dfaeR42
I'm not sure which is most proper solution to this, reverting context back to contain `exception` or handle `error` field like this in several handlers
https://github.com/Seldaek/monolog/compare/1.x...scaytrase:feature/errors?expand=1

**Comment by xabbuh** [comment]
I think changing the context key to `error` was a mistake. `exception` is the special key that is defined by PSR-3: https://www.php-fig.org/psr/psr-3/#13-context

**Comment by scaytrase** [comment]
Created fix PR #26959 (my ide gone mad on first one, sorry)
