### ISSUE TITLE
[Monolog] Deprecate excluded_404s in favor of excluded_http_codes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26969]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.2

The new `excluded_http_codes` option (https://symfony.com/blog/new-in-symfony-4-1-ignore-specific-http-codes-from-logs) does the same as `excluded_404s` (http://symfony.com/doc/current/logging/monolog_regex_based_excludes.html) but for any HTTP code, not only 404. Should we deprecate `excluded_404s` then?

Note: maybe this issue should go to MonologBundle repo instead of this one?

**Comment by Simperfit** [comment]
Maybe the PR can be merged and this closed, everything seems ready.
