### ISSUE TITLE
[Maker] Fluent Api For Class Source Manipulator

### ISSUE THREAD

**Issue by mnavarrocarter** [symfony/symfony#26963]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

Hi everyone!

I've been working on a RestBundle recently that makes some heavy use of the Glorious Maker Bundle to easily scaffold a lot of the utilities that I've implemented in the bundle itself. I've found very useful classes like the `DoctrineEntityHelper` and the `ClassSourceManipulator`.

However, this last one only works pretty much with entities. So what I'm trying to propose here is to implement a fluent interface for the `ClassSourceManipulator` class.

Something along the lines of:

```php
<?php

$this->source->addMethod('someMethodName')
    ->addArgument('someMethodName', 'argumentName', 'argumentType');
```

I know my example is pretty vague. I'm working to come up with a good API myself, but I've been studying how the php parser works first. I think the best implementation will be one that holds the operations into the class state (like doctrine's query builder does) and then execute them with a method called `write` or something like that.

I think that the Maker Bundle will benefit greatly of a feature like this, and will allow developers to easily modify source code and make awesome automation tools.

**Comment by javiereguiluz** [comment]
Thanks for proposing this new feature for the MakerBundle. However, the feature requests of that bundle are managed using issues and pull requests on its own repository. So I've moved your issue there --> https://github.com/symfony/maker-bundle/issues/153 and that's why I'm closing this one.
