### ISSUE TITLE
Form, CollectionType, update by UniqueEntity

### ISSUE THREAD

**Issue by pcholewa** [symfony/symfony#26968]
| Q                  | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x.x

I have form with field CollectionType. Example, in base i have 10 rows, when i send form with one row, i would like to update entity if exists by UniqueEntity fields, now it's add new row with same unique fields. How can i do this?

    class SurveyResponseType extends AbstractType {
    
        public function buildForm(FormBuilderInterface $builder, array $options){
    
            $builder
                ->add('responsesQuestion', CollectionType::class, [
                    'entry_type' => QuestionType::class,
                    'entry_options' => [
                        'label' => false
                    ],
                    'allow_add' => true,
                    'allow_delete' => false,
                    'by_reference' => false
                ])
            ;
        }
    
        public function configureOptions(OptionsResolver $resolver){
            $resolver->setDefaults(array(
                'data_class' => SurveyResponse::class,
                'csrf_protection' => false
            ));
        }
    }

  

    class QuestionType extends AbstractType
    {
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('response', EntityType::class, [
                    'class' => SurveyResponse::class,
                ])
                ->add('question', EntityType::class, [
                    'class' => Question::class,
                ])
                ...
            ;
        }
    
        public function configureOptions(OptionsResolver $resolver)
        {
            $resolver->setDefaults(array(
                'data_class' => SurveyResponse\Question::class,
                'csrf_protection' => false
            ));
        }
    }

 

    class SurveyResponse
    {
        ...

        /**
         * @ORM\OneToMany(targetEntity="App\Entity\SurveyResponse\Question", mappedBy="response", cascade={"persist", "remove"})
         */
        private $responsesQuestion;

        ...
    }

 

    /**
     * @UniqueEntity(fields={"response", "question"})
     */
    class Question
    {
        ...

        /**
         * @ORM\ManyToOne(targetEntity="App\Entity\SurveyResponse", inversedBy="responsesQuestion")
         */
        private $response;

        /**
         * @ORM\ManyToOne(targetEntity="App\Entity\Question", inversedBy="responsesQuestion")
         */
        private $question;

        ...
    }

**Comment by javiereguiluz** [comment]
As @iltar said, this looks like a support question, so please use the options shown in http://symfony.com/support. You can also check this article: https://symfony.com/doc/current/doctrine/associations.html

**Comment by pcholewa** [comment]
thanks!
