### ISSUE TITLE
[Filesystem] Filesystem.php line 732

### ISSUE THREAD

**Issue by codingjungle** [symfony/symfony#26977]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

in Filesystem.php line 732, it is expecting return type to be :iterable, but the method toIterable() can also return an array, this cause an error to be thrown when an array is returned.

**Comment by nicolas-grekas** [comment]
You need PHP 7.1 to run any Symfony 4 components.

**Comment by codingjungle** [comment]
yeah i see that, it was from another dev that had reported it to me, i assumed they were on php 7.1 (but they are on php 7.0.28)
