### ISSUE TITLE
[VarDumper] Call to undefined function spl_object_id()

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#26976]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.0.8

```
Error: Call to undefined function spl_object_id()
    
vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php:175
vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/AbstractCloner.php:229
vendor/symfony/symfony/src/Symfony/Component/VarDumper/VarDumper.php:34
vendor/symfony/symfony/src/Symfony/Component/VarDumper/VarDumper.php:38
vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php:20
```

Happens with `PHP 7.1.14`, `spl_object_id()` is available in PHP `7.2.0`.

**Comment by xabbuh** [comment]
That function should be provided by the `symfony/polyfill-php72` package which is required by the VarDumper component. Is it installed in your project?

**Comment by umpirsky** [comment]
Ah, I added it to `replace` section. Thanks!
