### ISSUE TITLE
[Command] How to properly run a command with env vars in prod ?

### ISSUE THREAD

**Issue by MrMitch** [symfony/symfony#26978]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

Hi,

I'd like to jump on the Symfony 4 bandwagon but I'm usure how a Command can use env vars when it's part of a website project.

The symfony documentation recommends to define the necessary env vars [in the web server](https://symfony.com/doc/current/configuration/external_parameters.html#configuration-env-var-in-prod). In my case, that would be in the virtual host configuration file for apache2. So far, 

For example, let's say i define a `DATABASE_URL` var that is used by Doctrine to connect to my database. This works fine for my app when I access the website.

Let's say I need a Command to be executed periodically (using `cron` the server) to compute and save some new data, based on the data currently stored in the database. My Command would need to access the database but it won't be launched from the web server, so the virtual host config file won't set the environment variables.

I could put everything I need in an `.env` file, install `symfony/dotenv` in prod but : 
- that would go against the good practice recommended by Symfony : 
    > In production, it is recommended to configure the environment variables in your web server configuration.
    https://symfony.com/doc/current/configuration/environments.html#executing-an-application-in-different-environments
- I would have duplicated the same content across 2 files, which is a pain to maintain 

**Is there a way to keep within the best practices and not duplicate my config ?**

**Comment by liweiyi88** [comment]
There are some ways:
1. export env vars in .bashrc.
2. use .env file and require `symfony/dotenv` as you said in your description. In terms of `that would go against the good practice recommended by Symfony`, please see the discussion in #26558 and https://github.com/symfony/symfony/issues/25643
Hope it will help.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
