### ISSUE TITLE
Bad syntax in the Symfony\Component\Translation\Translator class

### ISSUE THREAD

**Issue by s001dxp** [symfony/symfony#27005]
This is a bug.

There is a "?" in the type hint of the constructor.

See https://github.com/symfony/translation/blob/7308ac2cf60d16adcc58bc4897154bccd39daec6/Translator.php#L79

It's causing the following error: ParseError: Composer\Autoload\includeFile()

**Comment by javiereguiluz** [comment]
@s001dxp I'm afraid @dmaicher is right. This `?` character is expected in this case. It's a new PHP 7.1 feature called "nullable types". See http://php.net/manual/en/migration71.new-features.php
