### ISSUE TITLE
Session ini_set bug ?

### ISSUE THREAD

**Issue by ncou** [symfony/symfony#27011]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Symfony version  | 4.x

Hi,

After looking at the code, I think there is two small bugs in the session class
https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L356

There is the possibilite to apply a "url_rewriter.tags" parameter value, but this parameter doesn't start with "session.xxxx" so i think this will not work.

And there is a "upload_progress.min-freq" but looking at the doc it should be an underscore beetween min and fred => upload_progress.min_freq if i look at the doc : http://php.net/manual/fr/session.configuration.php#ini.session.upload-progress.min-freq

Am i missing something ? or are these 2 small potential bugs ?

**Comment by Tobion** [comment]
I think your observations are correct. Would you mind opening a PR?

**Comment by ncou** [comment]
sorry i didn't get the first message. happy my observation could have helped.
