### ISSUE TITLE
[VarDumper] [DX] Add dump stub in production mode to prevent "call to undefined function"

### ISSUE THREAD

**Issue by Deltachaos** [symfony/symfony#27015]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no
| Symfony version  | 4.*

Debug code leftover in production is smelly, but there are cases where this occurs (for example you are debugging somethin in production and you run the same codebase in development and production mode on different ports or domains).

In such a case it would help alot if the `dump` function would be replaced with an empty stub (or something that sends warning messages to the logger that there is a forgotten `dump` function in the code) to not exit at this position with an "call to undefined function".

**Comment by iltar** [comment]
To be honest, I rather have my code crashing, as a reminder that I'm wrong for deploying this without proper code reviews and not being detected in staging.

**Comment by chalasr** [comment]
Closing as explained, thanks for proposing.
