### ISSUE TITLE
Lazy load Translator service or make constructor lighter

### ISSUE THREAD

**Issue by grisendo** [symfony/symfony#27010]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.x (maybe 2.x and 4.x also?)

I am debugging a custom CMS made with Symfony (3.x) using Blackfire, in order to improve the performance as much as possible (and learn!). I already removed all heavy constructor services (Doctrine, Twig/Templating) from event listeners/subscribers, but there is one which I can't (or maybe shouldn't) remove, since it's in core. I am talking about Symfony\Component\HttpKernel\EventListener\TranslatorListener, which has "translator" service as dependency, and that service has a heavy constructor. It takes ~10% of the time in my current best case scenario.

I was looking for some issue similar to this, to no create a duplicate, I found some others about improve it (i.e. limiting some loaders/dumpers), but I didn't find any issue about lazy-loading that service (or its heavy logic) to avoid its construction at all unless required.

**Comment by Tobion** [comment]
Making the translator lazy would not change anything. The event listener sets the locale on the translator. This initializes the translator even if it was lazy.

So instead you need to make the translator constructor itself faster, e.g. by lazy loading one of the dependencies.

**Comment by xabbuh** [comment]
Could you make the profile public and add a reference to it here? :)

**Comment by grisendo** [comment]
https://blackfire.io/profiles/8e320963-fced-48b8-a7ca-d2f55426f772/graph

**Comment by chalasr** [comment]
The whole `Translator::$resources` _private_ prop is about lazy loading:
https://github.com/symfony/symfony/blob/e775871d82ab58cd34018f92b18178073742f2a2/src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php#L40-L46
and the fact it is set from the constructor has been challenged in https://github.com/symfony/symfony/pull/23057 but apparently not addressed. 

No blocker for moving the `addResourceFiles()` call to the `initialize()` method to me 👍
