### ISSUE TITLE
[serializer] allowed_extra_attributes doesn't throw Exception like docs says

### ISSUE THREAD

**Issue by tolbon** [symfony/symfony#27036]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.X

Hello I think I find a bug in serializer of Symfony
I follow the docs of [serializer in SF4](https://symfony.com/doc/current/components/serializer.html#deserializing-an-object) 
If you reproduce the second example with `'allow_extra_attributes => false'` it's not work.
Test of allowed_extra_attributes didn't cover this.

**Comment by ogizanagi** [comment]
Hi @tolbon. Indeed, you're right. But this feature actually requires a metadata factory to be registered in the object normalizer. 
Using it without will result into an exception in the future. See #26534 (closing in favor of it).

**Comment by tolbon** [comment]
Oups very sorry I search a bug like this in open tickets not in closed before create. Thanks for take this time to create a complete answer.
