### ISSUE TITLE
[4.1] BC Break(?) when not implementing the ConfigurationInterface 

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#27040]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 4.1:dev-master

When testing out 4.1 in my application, I got the following exception:

> Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Config\Definition\Processor::processConfiguration() must implement interface Symfony\Component\Config\Definition\ConfigurationInterface, instance of Ornicar\GravatarBundle\DependencyInjection\Configuration given, called in /home/ivanderberg/projects/symfony/src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php on line 80 and defined in /home/ivanderberg/projects/symfony/src/Symfony/Component/Config/Definition/Processor.php on line 50

Turns out, the Configuration class in this vendor package, is not using the `ConfigurationInterface`. Not sure when this broke, but it still worked in 4.0.

My guess is that it's working for 4.0 because it's manually added in the process:
```php
$configuration = new Configuration();
$processor = new Processor();
$config = $processor->process($configuration->getConfigTree(), $configs);
```

The fix for this problem is henrikbjorn/GravatarBundle#57, not sure if anything _should_ be fixed on the Symfony side.

**Comment by ro0NL** [comment]
Maybe we should validate this from https://github.com/symfony/symfony/blob/817da643ebfc31d274523ff41b9393be475f4611/src/Symfony/Component/DependencyInjection/Extension/Extension.php#L80

Not implementing `ConfigurationInterface` is a violation at this point due to https://github.com/symfony/symfony/blob/817da643ebfc31d274523ff41b9393be475f4611/src/Symfony/Component/DependencyInjection/Extension/ConfigurationExtensionInterface.php#L27-L29

**Comment by stof** [comment]
one solution: detect the implementation of the interface on the class is the pre-defined implementation of the method. Then trigger a deprecation warning and return `null` if the class exists without the interface.

A bundle not implementing the interface on its Configuration class is unlikely to use `getConfiguration` itself

**Comment by stof** [comment]
and for bundles overriding the method, they are the one violating the contract so a TypeError in 4.1 is fine.

But we should avoid violating the contract ourselves.

**Comment by ro0NL** [comment]
What about `return null` + deprecation if the auto-discovered configuration class is not a `ConfigurationInterface`? As you mentioned, i think its unlikely they use `getConfiguration` itself so returning null might do it :)

**Comment by stof** [comment]
@ro0NL that's exactly what I suggested in https://github.com/symfony/symfony/issues/27040#issuecomment-384224638

**Comment by ro0NL** [comment]
Ah sorry, i totally overread the `Then trigger a deprecation warning and return null if the class exists without the interface.` my bad :")

On it.
