### ISSUE TITLE
[Debug] the search does not work well

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#27045]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.x (may be on lower branch too)

---

PHP code: `dump(['foo' => ['bar' => 'toto']]);die;`

![screencast-2018-04-25-14_48_33](https://user-images.githubusercontent.com/408368/39246824-f4370848-4897-11e8-8cb3-b33bfcc3e7b7.gif)

---

as you can see, when I type `tot` the search works, and when I add an extra `o`, the search is broken.
Then I remove everything and type again `toto` and it still does not work

**Comment by ogizanagi** [comment]
See #27064 😉
