### ISSUE TITLE
[DependencyInjection] Rethink getDefinition() and findDefinition()

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27050]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.2

On Symfony Slack we were discussing about the `getDefinition()` and `findDefinition()`. They are almost identical, but `findDefinition()` resolves service aliases and that's why most people always use that method.

So, should we deprecate `getDefinition()` in favor of keeping just `findDefinition()`. Is there any legitimate `getDefinition()` use case that we're missing? Thanks!

**Comment by stof** [comment]
when processing services in some generic code, `getDefinition` has advantages compared to `findDefinition`, as it allows you to be sure about the id for the Definition with which you are working. Any times you write code which will re-assign something in the container based on this definition, knowing that you got it for this id (rather than through a chain of aliases) is meaningful.

I'm not sure how much guarantees this provides though

**Comment by kiler129** [comment]
@stof: But really when you want to replace a definition you're not looking for alias but exactly for root Definition, or do you maybe have some specific use case in mind?

I reviewed few of the large closed source projects with a lot of compiler passes and I wasn't able to find any use case for `getDefinition()` which couldn't be replaced by `findDefinition()`.

**Comment by nicolas-grekas** [comment]
The code base is using both. If anyone would like to wonder about replacing all getDefinition by findDefintion and see if nothing breaks, that would be a start.

**Comment by curry684** [comment]
I explicitly use getDefinition when adding dynamic or optional extensions during compilation to a service prepared in config. If I one day replace the original service with a different one and keep the old one as an alias for BC I want my code to fail as it will likely conflict with new implementation.

I realize that's not a great case for keeping a function around apart from not seeing a clear alternative for it now, comparing names on the result of findDefinition would be hacky.

**Comment by javiereguiluz** [comment]
Let's close this because there are use cases for having two methods and also, removing one method wouldn't simplify things so much. Thanks!
