### ISSUE TITLE
[Profiler] Doctrine - Query Metrics - Explain query - v4.1

### ISSUE THREAD

**Issue by FroggDev** [symfony/symfony#27058]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

Hi, 

when i try to use the profiler to track Doctrine queries, i am getting an error message : ```An error occurred while loading the query explanation.``` when i use the "Explain query" link.

This is the information i am getting in the ajax request made by the profiler :

http://127.0.0.1:8000/_profiler/e4bfea?panel=db&page=explain&connection=default&query=2

> Argument 2 passed to Doctrine\DBAL\Connection::executeQuery() must be of the type array, object given, called in C:\symfony\Symfony_StockManager\vendor\doctrine\doctrine-bundle\Controller\ProfilerController.php on line 87

```public function executeQuery($query, array $params = [], $types = [], QueryCacheProfile $qcp = null)```

Thanks.

**Comment by iltar** [comment]
Actually noticed this as well from time to time in 4.0

**Comment by psychob** [comment]
Bug is present in v4.0 too.

I don't know internals of Symfony, but quick and dirty fix that works in my case is to change file `doctrine/doctrine-bundle/Controller/ProfilerController.php` on line `85-89`:

```php
    private function explainOtherPlatform(Connection $connection, $query)
    {
        return $connection->executeQuery('EXPLAIN ' . $query['sql'], $query['params']->getValue(), $query['types'])
            ->fetchAll(\PDO::FETCH_ASSOC);
    }
```

**Comment by xabbuh** [comment]
It looks like this needs to be fixed in DoctrineBundle then. Please report the issue in [their repository](https://github.com/doctrine/DoctrineBundle).

**Comment by stof** [comment]
This is already a known bug, which has been fixed in the dev version of the bundle already.
