### ISSUE TITLE
How to control the cache from default

### ISSUE THREAD

**Issue by harikumar99** [symfony/symfony#27060]
| Symfony version  | 3.4.3

Hi all,

I want to change response header cache-control
Default it displays Cache-Control: max-age=0 must-revalidate private
i want to change max-age. is that possible?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
