### ISSUE TITLE
FOSUserBundle doesn't redirect to /login on 3.4.8. It did on 3.4.6

### ISSUE THREAD

**Issue by spyridonas** [symfony/symfony#27072]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             |no
| Symfony version  | 3.4.8

Today i upgraded from Symfony 3.4.6 to 3.4.8 and the automatic redirect to website.test/login stopped working when hitting the homepage ( website.test ) as anonymous user using FOSUserBundle. All I see is welcome to Symfony 3.4.8

**Comment by dmaicher** [comment]
As commented in https://github.com/symfony/symfony/issues/27057 a reproducer will help :blush:

**Comment by spyridonas** [comment]
Duplicate of #27057
