### ISSUE TITLE
[Messenger] Configure a handler to subscribe to messages by their interface/parent class

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#27076]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

With `MessageSubscriberInterface::getHandledMessages()` we can return an array of classes that should be handled but this requires knowing the exact classes before hand. What if we wanted all messages that implement an interface to be handled by a handler?

One solution I came up with was to loop through `get_declared_classes()` in `MessageSubscriberInterface::getHandledMessages()` and return the classes that implement an interface but this seems clunky (and perhaps error prone).

Any thoughts on how we can handle this?

**Comment by yceruto** [comment]
Maybe related to https://github.com/symfony/symfony/pull/27034 ?

**Comment by ro0NL** [comment]
In theory you could decorate the bus and dispatch e.g. an `EventMessage` that wraps the original message (if it implements X). Then you can listen for any EventMessage being dispatched..

**Comment by kbond** [comment]
Or, if `MessageSubscriberInterface::getHandledMessages()` is changed to `iterable`, something like:

```php
public static function getHandledMessages(): iterable
{
    return new MessageImplements(MyInterface::class);
}
```

**Comment by sroze** [comment]
We are going to change the `MessageSubscriberInterface::getHandledMessages()` signature from a "`EventSubscriber`-like" to something more explicit and easily configurable:
```php
static function configureHandledMessages(Configurator $config)
{
    $config->handleMessageClass(MyMessage::class):
    $config->handleMessageInterface(MyInterface::class):
}
```

This has been discussed in here https://github.com/symfony/symfony/pull/27034#issuecomment-384935800 and in the core team, as we know the subscriber syntax is confusing for a lot of people and not explicit at all. The `$config->handleXXX` will be easy to discover for newcomers (typically, the auto-completion will work, first).

**Comment by kbond** [comment]
Now that `MessageSubscriberInterface::getHandledMessages()` is iterable would it make sense to have a helper class like described in https://github.com/symfony/symfony/issues/27076#issuecomment-385027060 or should this not be provided by the framework?

**Comment by nicolas-grekas** [comment]
> static function configureHandledMessages(Configurator $config)

for the record, this proposal has been rejected, see https://github.com/symfony/symfony/pull/27034#issuecomment-385229190

@kbond could be worth giving it a try. The iterable should yield only basic arrays of course.

**Comment by kojiDev** [comment]
Well great, but how do I avoid sending the message to multiple handlers now if one message extends from another?
`handles` in `messenger.message_handler` does not work

**Comment by chalasr** [comment]
@kojiDev Please consider opening a new issue with enough details to reproduce, comments on closed tickets are likely to be lost.
