### ISSUE TITLE
[DI][FrameworkBundle] (Idea) PHP-DSL base class for simple shortcuts for DI

### ISSUE THREAD

**Issue by aurimasniekis** [symfony/symfony#27073]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

Hi,

Thanks for merging my PR #27065 my whole point of that change was to ability use inline classes with `__invoke` method and some shortcuts like `addCommand`, `addService`, `addControllers`, `addRepository`.

So I thought about something a bit wider scope for e.g. Make a base class inside FrameworkBundle which would have all shortcuts for main features and would allow extending default properties of it and etc.

Something like this:

```php
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

abstract class ContainerConfig
{
    /**
     * @var ContainerConfigurator
     */
    private $containerConfig;

    public function addController(string $class, bool $autoWire = true)
    {
        // ...
    }

    public function addDoctrineRepository(string $entityClass)
    {
        // ...
    }

    public function addService(string $class, bool $autoWire = true, bool $public = false)
    {
        // ...
    }
    
    public function addEventListener(string $class, string $eventName)
    {
        // ...
    }

    public function __invoke(ContainerConfigurator $containerConfigurator)
    {
        $this->containerConfig = $containerConfigurator;
        
        $this->configure($containerConfigurator);
    }

    abstract public function configure(ContainerConfigurator $container);
}

return new class extends ContainerConfig {
    public function configure(ContainerConfigurator $container)
    {
        $this->addController(UserController::class);
        $this->addDoctrineRepository(User::class);
        $this->addService(UserCreationService::class);

        $this->addEventListener(UserCreationListener::class, 'user.new');
    }
};
```

Either way, I am going to make it either an external library or try to integrate inside FrameworkBundle. But I just don't know all shortcuts I should add and if someone could suggest more these kind of shortcuts I would not mind spending time implementing this util class.

**Comment by stof** [comment]
We already have autoconfiguration being able to identifier event subscribers and doctrine repositories (and controllers when they extend the base class). So what would be the benefit of these shortcuts when the minimal code needed in *all* of them is to register the service ?

**Comment by aurimasniekis** [comment]
Hmm, haven't heard about identifying doctrine repositories, cause all the time you need to define repo as a service via factory if you want to inject it... The key point of this idea is to minimize repetitive code when working on big projects, so for e.g. Instead of writing 5 lines of code every time you need to define repository as a service.

P.S. I think autoconfiguration identifier doesn't work with out of src folder code for e.g. If the application is designed to be modular.

**Comment by nicolas-grekas** [comment]
As @stof, I'm not sure this would provide many benefits over the current way to express the same. It would also be for sure much more restrictive.

BUT, that could instead be a great start to implement per bundle PHP-DSL-style configuration, instead of the current ->extension('foo', array(........)):

```
return new class extends FrameworkBundleConfigurator {
    public function configure()
    {
        $this->...; // to be created
    }
};
```


> autoconfiguration identifier doesn't work with out of src folder code

Yes it does: autoconfiguration works where you configure it. Can be anywhere.

**Comment by stof** [comment]
> Hmm, haven't heard about identifying doctrine repositories, cause all the time you need to define repo as a service via factory if you want to inject it...

Look at the new features of DoctrineBundle 1.8 about that: https://github.com/doctrine/DoctrineBundle/pull/727

Registering the Doctrine repository as a service without this feature is a very bad idea, as it breaks the entity manager resetting (your service keeps using the old entity manager). And with this feature, it can be autoconfigured.

**Comment by sstok** [comment]
FYI. https://github.com/park-manager/park-manager/blob/887533c2ce6d6eeb3d274482b220ccb9ee590abb/src/Module/Webhosting/Infrastructure/Resources/config/services/core.php#L26-L36

**Comment by fabpot** [comment]
Closing this issue as it didn't get traction.
