### ISSUE TITLE
Add example to serializer component docs about XML attribute extraction

### ISSUE THREAD

**Issue by arechsteiner** [symfony/symfony#27080]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

I'm trying to use the package `symfony/serializer` to extract data from this XML structure:

    <?xml version="1.0" encoding="utf-8"?>
    <result>
      <code><![CDATA[SUCCESS]]></code>
      <message><![CDATA[List of things retrieved.]]></message>
      <data>
        <category id="123123123" name="some name" url="/some/url">
          <category id="123123123" name="some name" url="/some/url/" />
          <category id="123123123" name="some name" url="/some/url/">
            <thing id="123123123" name="some name" url="/some/url/" />
            <thing id="123123123" name="some name" url="/some/url/" />
          </category>
          <category id="123123123" name="some name" url="/some/url/">
            <category id="123123123" name="some name" url="/some/url/">
              <thing id="123123123" name="some name" url="/some/url/" />
              <thing id="123123123" name="some name" url="/some/url/" />
              <thing id="123123123" name="some name" url="/some/url/" />
            </category>
          </category>
        </category>
      </data>
    </result>

I've been reading this site in the documentation: [The Serializer Component](https://symfony.com/doc/current/components/serializer.html). Unfortunately all the examples deal with data that is stored in child nodes. It would be great if there was a section that explains how to extract data from the XML attributes. The only hint I found was when [serializing from an array to XML](https://symfony.com/doc/current/components/serializer.html#the-xmlencoder) (with the `@` syntax). I'm unable to figure out how to do it in the opposite direction.

**Comment by iltar** [comment]
If there's an issue with the docs (or you're missing something), you can open an issue in the symfony/symfony-docs repository. For support, you can check out symfony.com/support

**Comment by javiereguiluz** [comment]
@arechsteiner as @iltar said, we deal with issues related to Symfony Docs in the symfony-docs repo. I've moved your issue there: https://github.com/symfony/symfony-docs/issues/9705 Cheers!
