### ISSUE TITLE
Routes security not working

### ISSUE THREAD

**Issue by fabionvs** [symfony/symfony#27091]
Hello,
I am working on a project using Symfony 3.4, and it seems access_control routes are not working properly. When I try to access a protected route by access_control, anonymous and users still could get access from a protected route. As the following security.yml:

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        secured_area:
            anonymous: true
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    linkedin:           "/login/check-linkedin"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider

            logout:
                path: /logout

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/, role: ROLE_CLIENT }
        - { path: ^/admin/, role: ROLE_ADMIN }`

But, if I use annotation inside a controller to prevent acess the security works! 

> /**
> * @Security("is_granted('ROLE_ADMIN')")
> */
>class DefaultController extends Controller {
>}

And, use security annotation in every controller sounds a little bit annoying. What should I do? What could be the error causing acces_control not to work?

	"php": ">=7.1",
        "symfony/symfony": "3.4.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "hwi/oauth-bundle": "^0.6.2",

**Comment by javiereguiluz** [comment]
@fabionvs I'm sorry but in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

In any case, the solution to your question seems to be that the order of the URLs in `access_control` is wrong. You must put the more generic URL (`^/`) at the end, not the first one. It's explained here: https://symfony.com/doc/current/security.html#security-authorization-access-control
