### ISSUE TITLE
[BC Break] OptionsResolver::formatTypeOf does not work on Symfony 3.4

### ISSUE THREAD

**Issue by danemacmillan** [symfony/symfony#27101]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4

My project has the following requirements:

```
    "require": {
        "php": ">=7.0",
        "symfony/config": "^3.4",
        "symfony/console": "^3.4",
        "symfony/event-dispatcher": "^3.4",
        "symfony/filesystem": "^3.4",
        "symfony/finder": "^3.4",
        "symfony/lock": "^3.4",
        "symfony/process": "^3.4",
        "symfony/yaml": "^3.4"
    }
```

One of them also pulls in [`options-resolver`](https://github.com/symfony/options-resolver). Options Resolver specifies that it needs a minimum PHP version of `7.1.3`. Symfony `3.4`'s [`composer.json`](https://github.com/symfony/symfony/blob/3.4/composer.json) file specifies `"^5.5.9|>=7.0.8"` as the PHP version.

Symfony `3.4` is advertised with [minimum support for PHP `5.5.9` and higher](https://symfony.com/doc/3.4/reference/requirements.html).

Given this information, I'm getting the following error:

```
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /vagrant/sites/linus/vendor/symfony/options-resolver/OptionsResolver.php on line 980
```

The error line is: https://github.com/symfony/options-resolver/blob/master/OptionsResolver.php#L980

The error is happening because my version of PHP, `7.0.27`, does not support [nullable types](http://php.net/manual/en/migration71.new-features.php).

Given my project requirements for only Symfony `3.4` packages, I should not be getting this error. This is breaking code that is respecting requirements. The nullable type should be allowed to be used when the Symfony requirements specify Symfony `3.4`. If I wanted to use Symfony `4.0`, I would upgrade to PHP `7.1.3` and specify that the Symfony versions for those requirements be bumped to `4.0`.

**Comment by nicolas-grekas** [comment]
When running composer on your PHP v7.0, it will use option-resolver v3.4, which is the one compatible with your requirements. I suppose you ran composer update on a PHP 7.1, then you did a composer install on your PHP 7.0, which is a workflow that leads to broken deps for sure.
You might also want to set your platform in your composer.json file, see
https://getcomposer.org/doc/06-config.md#platform

**Comment by danemacmillan** [comment]
That's pretty much what happened. I've since ended up explicitly requiring `"symfony/options-resolver": "^3.4"` and that took care of the issue between PHP versions. For the meantime I need to be able to run at minimum PHP `7.0`, but also allow up to `7.2`. Explicitly defining `options-resolver` has allowed me to do that.

Thanks for the super fast response. I'll close this, given the inevitability of this mixture.

**Comment by xabbuh** [comment]
@danemacmillan You can also tell Composer to use a particular PHP version when resolving your requirements: https://getcomposer.org/doc/06-config.md#platform
