### ISSUE TITLE
Bootstrap 4 Form Theme for PHP Templating Engine?

### ISSUE THREAD

**Issue by chris14465** [symfony/symfony#27114]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.3

Am I missing something, or is there no Bootstrap 4 Form Theme available when using PHP als templating engine?
Documentation is not mention anything about it, and setting the form theme to "bootstrap_4_layout.html.php" isn't working either.
(https://symfony.com/doc/current/form/form_customization.html)

**Comment by iltar** [comment]
As far as I know, active development for the php engine is discontinued and only twig implementations will be provided.

**Comment by fabpot** [comment]
Indeed, we are now focused on Twig for new templating features.
