### ISSUE TITLE
[Cache] Does an ArrayAdapter at the top of the cache chain improve performance?

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#27119]
https://stackoverflow.com/a/27393049

Each cache retrieval for the same key returns (in case of an object value) a new instance of the cache value. There are some components that repeatedly access the same cache key (mainly the metadata/annotation using components like validator/serializer/property access).

I wonder if an ArrayAdapter (with no serialization behavior) on top of the chain would improve performance (to a somewhat meaningful degree)? Ofc its a tradeoff between memory and cpu usage, since you keep the reference for the rest of the script runtime. So insteadof fetch, memcopy (in case of apcu), gc, refetch, memcopy we would get just one one memcopy and keep the object referenced in the ArrayAdapter.

If this has already been checked, just close.

**Comment by nicolas-grekas** [comment]
About the "no serialization" behavior, this would be dangerous, as the same object would be reused, which could have bad side effects. Not sure we can do it; at least we should not do it lightly.
For caches that use PhpArrayAdapter (ie all system caches that have a warmer: annotations, validator, and serializer), the benefit, if any, should be small, as this adapter is pretty fast.

But that's only theory, the only way to answer this question is by measuring.

**Comment by nicolas-grekas** [comment]
Closing as explained. Note that the listed caches have been made faster with #27543.
