### ISSUE TITLE
[YAML] Underscores are removed from strings treating them as integers.

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony#27120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.

Hello, I've created a YAML file where the value `6000_5000` was stored. This YAML was simply created for populating database tables with data for test cases. When I wrote the test case, I searched for data containing `6000_5000` but had no results. After some research, I saw, that `6000_5000` was saved as `60005000`, so I digged deep to see why that happens.

I found [this line (including blame)](https://github.com/symfony/symfony/blame/95ceeab3d718a02317e190a780435822a0bfb03f/src/Symfony/Component/Yaml/Inline.php#L738) and [this PR](https://github.com/symfony/symfony/pull/18486) where it states

> Allows to use the _ to group "big" ints, as suggested in the yaml integer type specification. As discussed in #18094, we should check if it is still part of the 1.2 specification, but I don't really see why not?

Okay, so I searched a bit and found [this type definition](http://yaml.org/type/int.html) where it states exactly what the PR should do, however this is, as the PR, for YAML version 1.1, so I opened the int specs for 1.2 which you can [find here](http://yaml.org/spec/1.2/spec.html#id2803828)

In this definition, there is no mentioning of using `_` as readability help, and I didn't find this recommendation anywhere else, so in order to comply with 1.2 standards of the YAML definition, I'd say Symfony needs to remove this.

Now I don't know how to handle this correctly. I'd open a PR, but this is a BC break, so it's not possible to  merge this into the `4.x` branch, but this violates the YAML definition, so a user, who reads version 1.2 of the YAML definition and uses Symfony will have NO idea WHY this happens.

Thoughts?

**Comment by tzfrs** [comment]
According to the [page of the Yaml component](http://symfony.com/doc/current/components/yaml.html) 

> The Symfony Yaml Component implements a selected subset of features defined in the YAML 1.2 version specification.

so since this is not in the 1.2 specs, I'd say this is indeed a bug and not a feature request.

**Comment by javiereguiluz** [comment]
@tzfrs this feature was introduced in Symfony 3.2 and it's explained in https://symfony.com/blog/new-in-symfony-3-2-better-readability-for-yaml-numeric-literals  In that blog post you can read:

> This feature is defined in the YAML specification and it's widely supported in other programming languages (Java, Ruby, Rust, Swift, etc.).

And this is where the YAML spec defines this feature: http://yaml.org/type/int.html

> Any “_” characters in the number are ignored, allowing a readable representation of large values.

**Comment by tzfrs** [comment]
@javiereguiluz The spec you linked is the one I already linked and is from version 1.1. Since Symfony says they implement version 1.2 a user only browsing that spec (because 1.1 is out of date) will have no idea why this happens.

I would at least put it somewhere in the docs of the Yaml component.

**Comment by stof** [comment]
Well, the YAML 1.2 spec explicitly links http://yaml.org/type/ to for types to implement, even though pages there are titled as YAML 1.1: http://yaml.org/spec/1.2/spec.html#id2805770

The YAML spec is a bit of a mess

**Comment by xabbuh** [comment]
closing as explained by @stof

**Comment by stof** [comment]
Note that if you want to put the string `6000_5000` in a YAML file, you can quote the value, and this will always stay a string, not the `60005000` number.

**Comment by tzfrs** [comment]
@stof That's what we're doing in our YAML files. Just thought it *might* be a bug.
