### ISSUE TITLE
Gender and number-dependent words in translation

### ISSUE THREAD

**Issue by codedokode** [symfony/symfony#27132]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | irrelevant

In many languages (for example, in Russian) the words in phrases use different forms depending on gender and count. For example, in this phrase:

> Ivan has _shared_ 5 _files_ and 3 _documents_.

in Russian the word "shared" has two forms depending on user's gender and words "files" and "documents" depend on numbers before them. Currently [Symfony Translation ](https://symfony.com/doc/current/translation.html) has no support for this. The method [transChoice()](http://api.symfony.com/4.0/Symfony/Component/Translation/Translator.html#method_transChoice) is too limited and is not usable in many cases. 

PHP Intl extension has [formatMessage](http://php.net/manual/en/messageformatter.formatmessage.php) method that can handle such cases. [Formatting syntax](http://userguide.icu-project.org/formatparse/messages). But it requires to embed pluralization rules in every translated message. This can be solved by using "select" instead of "plural" and delegating choice to an external function.

So the question is, would not it make more sense to use Intl's formatter as default?

**Comment by jvasseur** [comment]
There has been work done to try to add a formatter based on the Intl extension to Symfony (https://github.com/symfony/symfony/pull/20007) but it's currently blocked because it's hard to do it without breaking BC.

**Comment by nicolas-grekas** [comment]
fixed by #27399
