### ISSUE TITLE
[DX] Improve the "the controller must return a response (null given)" exception page

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#27137]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | all 

---

![image](https://user-images.githubusercontent.com/408368/39577693-4e09f754-4ee2-11e8-9d02-e01ad08e77fa.png)

I think we can improve a lot this page by showing the controller that is responsible of this exception.
I guess many new-comers hit this page, and it could be complicated to find the controller, even if it's name is in the debug bar.

Do you think it worth it or should we close?

**Comment by javiereguiluz** [comment]
It looks like a good idea. Are you thinking of just creating a better error message that includes the exact failing controller ... or are you proposing to create a different error page for that error?

**Comment by lyrixx** [comment]
We could do that also. Did you see my PR ? being able to click on the filename to open the file in the IDE is a must have ;)

**Comment by iltar** [comment]
One option could be to create `DxExceptionListener` in dev mode that analyzes the exception and then tries to create a useful error message for you. There are a bunch more of common exceptions (argument value resolver for example), that could benefit from such a generic extension point. It also means that vendors can hook in on this and make it even better for either their own packages, or others.
