### ISSUE TITLE
[Form] Add a way to add empty rows to a CollectionType

### ISSUE THREAD

**Issue by kevin-verschaeve** [symfony/symfony#27131]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | no
| Symfony version  | 4.1 (or 4.2 ?)

Hello,
I recently needed to add some empty rows to a CollectionType and I was wondering if adding an option to this Type could be useful.

```
$builder->add('exemple', CollectionType::class, [
   'entry_type' => IntegerType::class,
   'entry_count' => 3,
]);
```
Here, the new option is `entry_count` (or maybe a better name ?), which allow to add 3 integer fields on the page with their default values.

I think, options like this can be useful for beginners, as this will be easier than adding the rows themselves.

This shouls also work with custom types.
Let's say we have an `Example` class:
```
class Example
{
    private $example1 = 'yay !':
    private $example2 = 'SF rocks !';

    // getters / setters
}
```
Which come along with an associated form Type (e.g ExampleType) that add 2 TextType.
And we have our main form that embed the other into a Collection:
```
class DemoType extends AstractType
{
   public function buildForm(...)
   {
        $builder->add('examples', CollectionType::class, [
               'entry_type' => ExampleType::class,
               'entry_count' => 3,
        ]);
   }
}
```
This should display 3 rows of 2 text inputs with "yay !" as a default value for the first one and "SF rocks !" for the second one.

I would be glad to work on this, actually I have already started, but before going on, please let me know if you think that this could be a nice feature for Symfony.

**Comment by yceruto** [comment]
If I've understood correctly, you're suggesting to avoid doing this:
```php
$data = [
    'examples' => [new Example(), new Example(), new Example()],
];

$form = $this->createFormBuilder($data)
    ->add('examples', CollectionType::class, [
        'entry_type' => ExampleType::class,
    ])
    ->getForm();
```
? if yes, your new option is all about default values, which (as a rule) should always be passed in the default data when creating your form builder (yes, "adding the rows themselves"), at least that's what the documentation says.

Also, what will happen if I provide some initial data in combination with this new option?:
```php
$data = [
    'examples' => [new Example()],
];

$form = $this->createFormBuilder($data)
    ->add('examples', CollectionType::class, [
        'entry_type' => ExampleType::class,
        'entry_count' => 3,
    ])
    ->getForm();
```
Should it add two new `Example` more? or simply do nothing?

**Comment by yceruto** [comment]
Even though I like the proposal :+1:

**Comment by kevin-verschaeve** [comment]
For your first question, yes I think this should be handled this way. About default values, when we have a custom type linked to an Entity / Model, the default values are the one on this class, see my exemple above with "yay !" and "SF rocks !". For some "simple" input, I don't know for now how to add default values.

For your second question, yes, I think it is a good idea to add missings rows to get the number the user asked for.

**Comment by kevin-verschaeve** [comment]
Should I close this issue as it is not worth it ?

**Comment by xabbuh** [comment]
I am not sure if this really is a common use case.

@kevin-verschaeve If you like to give this a try and find a way to implement this without rewriting too mich of the existing implementation, we may consider this. Otherwise, I tend to think that we should rather close here.

**Comment by kevin-verschaeve** [comment]
Let's close it. It does not seems to be something usefull for a lot a people.
Thanks for the feedback everyone :)

**Comment by jrbarnard** [comment]
I achieved this with an extension, I think there would be use in core for it though and am happy to do a PR?
For me the use case is because I am storing form config in the database and therefore want it to be quite configurable and tied to the specific form type when it is added to the form.

I've only done some initial testing, but it seems to work when you set data with no explicit key set for the collection, but it will override otherwise.

```
<?php
namespace App\Form\Extensions;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class CollectionDefaultCountExtension extends AbstractTypeExtension
{
    public static function getExtendedTypes()
    {
        return [CollectionType::class];
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault(
            'entry_count',
            0
        );

        $resolver->setAllowedTypes('entry_count', 'int');
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $default = array_fill(0, $options['entry_count'], []);
        $builder->setData($default);
    }
}
```
