### ISSUE TITLE
[Cache] CachePoolPrunerPass uses wrong service id in 3.4

### ISSUE THREAD

**Issue by DemonTPx** [symfony/symfony#27134]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.9

I was running the `cache:pool:prune` command and nothing was pruned. I discovered that no pools were added to the command even though I have about 6 of them in my application.

The `CachePoolPrunerPass` is responsible for adding the pools to the command, but uses the class name of the command to find its service. This might be fine for Symfony 4, but in my 3.4 application it cannot find the service. After I changed the service id to `console.command.cache_pool_prune` the compiler pass worked correctly again and I could prune my cache pools.

I could make a PR for this, but I think it might break it on Symfony 4. What would be the best way to proceed with this?

**Comment by xabbuh** [comment]
@DemonTPx please do :) (it looks like this broke in #24713

**Comment by xabbuh** [comment]
and the service id is still the same in 4.0: https://github.com/symfony/symfony/blob/4.0/src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml#L36

**Comment by xabbuh** [comment]
to add another PR that provides some context: the service id was indeed removed at some point but it was added back in #25011

**Comment by DemonTPx** [comment]
Thanks for the extra context. I just checked one of my projects using Symfony 4 and it has the same problem, as you pointer out. I'll work on a PR :)
