### ISSUE TITLE
[DependencyInjection] Wrong error message when using bindings on a service with missing parents

### ISSUE THREAD

**Issue by jvasseur** [symfony/symfony#27146]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

When you use bindings on a service with a missing parent class or interface you get the unused binding error which doesn't point to the real problem (a parent is missing).

This is probably related to #27088.

**Comment by nicolas-grekas** [comment]
Would you be able to debug why and provide a fix maybe? That'd be awesome :)

**Comment by nicolas-grekas** [comment]
see #27191
