### ISSUE TITLE
[Cache] Tag invalidation does not persist after script execution

### ISSUE THREAD

**Issue by Loupax** [symfony/symfony#27147]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^4.0

I am using the `TagAwareAdapter` so I can invalidate my REDIS cache by tag. The problem is that, while the cache item gets invalidated, this change does not persist between requests.

See this reproduction [repo](https://github.com/Loupax/CachingTagInvalidationBug) , it has four commands:
One that populates the cache, one that invalidates the cache by tag, one that fetches the keys and one that does all three in a single command.

Expected behaviour:
```
$ bin/console app:add
$ bin/console app:invalidate
$ bin/console app:get
```
The final command should output:
```
item-0, isHit:false
item-1, isHit:false
item-2, isHit:false
item-3, isHit:false
item-4, isHit:false
```
Actual output:
```
item-0, isHit:true
item-1, isHit:true
item-2, isHit:true
item-3, isHit:true
item-4, isHit:true
```

Running the command `$ bin/console app:add-invalidate-and-get` works as expected

**Comment by harmbandstra** [comment]
@Loupax I ran into the same issue. You can downgrade the cache component to 4.0.8 as a workaround.

**Comment by Loupax** [comment]
@harmbandstra can confirm, downgrading to 4.0.8 works correctly right now
