### ISSUE TITLE
Script cache:clear returned with error code 1

### ISSUE THREAD

**Issue by lperry65** [symfony/symfony#27154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Symfony version  |  4.0.9 

 In Filesystem.php line 182:
!!
!!    Failed to remove directory "/home/vagrant/Code/symfony/my-project/var/cache
!!    /loca~/pools": unlink(/home/vagrant/Code/symfony/my-project/var/cache/local
!!    /ContainerLzydxqx.legacy): No such file or directory.
!!

**Comment by lperry65** [comment]
I’m evaluating symfony as an alternative to Laravel. I was following the setup guid and got as far as installing the php web server. 

composer require server --dev
Then I got the error.

**Comment by javiereguiluz** [comment]
@lperry65 thanks for opening this issue and I'm sorry you faced this issue while evaluating Symfony. Sadly when using Vagrant, containers, etc, things may be a bit more complex to setup than when using native operating systems. But we'll try to help you debug this problem!

By the way, we recently merged a bug fix (https://github.com/symfony/symfony/pull/27061) that maybe is related to this somehow? @nicolas-grekas what do you think? Thanks!

**Comment by lperry65** [comment]
@nicolas-grekas thanks for your reply.

 I’m running Release v4.0.9, Is homestead considered a legacy container ?

Running : 
rm -R /home/vagrant/Code/symfony/my-project/var/cache/local
rm -R /home/vagrant/Code/symfony/my-project/var/cache/loca~

before `composer require server –dev` seems to have worked.

But know getting  `There are no commands defined in the "server" namespace.`

I’m just trying to work through the following guide ?

https://symfony.com/doc/current/setup.html

Thanks,

Lee.


Sent from Mail for Windows 10

**Comment by javiereguiluz** [comment]
@lperry65 as a temporary solution, forget about installing the development server and also forget about running `server:*` commands. Just enter into the directory of your Symfony project and run this command:

```bash
php -S 127.0.0.1:8000 -t public
```

Now you can browse the app at http://127.0.0.1:8000 in your browser.

-----

Regarding the "legacy container" ... is something internal used by Symfony and it doesn't refer to Laravel's Homestead. By the way, in case you missed it, this document about using Symfony with Homestead may be helpful: https://symfony.com/doc/current/setup/homestead.html

**Comment by Marat-Tanalin** [comment]
Maybe related: today I noticed that my **file-cache invalidation** has stopped to work.

I found that this is due to the commit [42ee14b](https://github.com/symfony/cache/commit/42ee14b6671a2a4cd1c0a1bd6fae198e5ae99434) (“[Cache] fix logic for fetching tag versions on TagAwareAdapter”). Once I revert it (add the `$fetchTagVersions = true;` line back to `Adapter/TagAwareAdapter.php`), cache invalidation gets working again.

Please let me know if I should file a separate issue.

**Comment by lperry65** [comment]
Why has this been closed, is it fixed ?
