### ISSUE TITLE
isXmlHttpRequest dont work with jQuery ajax requests.

### ISSUE THREAD

**Issue by marceloxp** [symfony/symfony#27161]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Symfony version  | 3.4.6

The function `isXmlHttpRequest` on `symfony\http-foundation\Request.php` uses only one parameter to return if request is an Ajax.
A simlpe jQuery ajax returns false unless add *X-Requested-With* on header.

see: <https://bugs.jquery.com/ticket/2356>
```plain
Changed 10 anos ago by flesler
Estado:	new -> closed
Resolução: -> invalid
Script and json requests just can't have X-Requested-With (XMLHttpRequest) and adding that would be a lie :)
```

> To call an API as a json request, the header *X-Requested-With* is not sent.

```php
    public function isXmlHttpRequest()
    {
        return 'XMLHttpRequest' == $this->headers->get('X-Requested-With');
    }
```
see: <https://benjaminlistwon.com/blog/adding-more-robust-ajax-detection-in-laravel/>

This function is used on Laravel 5.5:  `laravel\framework\src\Illuminate\Http\Request.php`

```php
    class Request extends SymfonyRequest implements Arrayable, ArrayAccess

    ...

    /**
     * Determine if the request is the result of an AJAX call.
     *
     * @return bool
     */
    public function ajax()
    {
        return $this->isXmlHttpRequest();
    }
```

Thanks ;)

**Comment by mx03** [comment]
Ajax can't be recognized, only with the custom header that some libraries use.
Dont detect ajax, check what the requests wants (accept, content-type header).

**Comment by hktr92** [comment]
I'm using `"jquery": "^3.3.1"` in a project that heavily relies on `$.ajax` and I didn't had any issues with this.The `X-Requested-With` header is sent to server and the method works without any issues.
![image](https://user-images.githubusercontent.com/7689151/39700812-50e6b886-5207-11e8-96ff-3f2aafc08550.png)

Method:

    let apiCall = (url, method = 'GET', data = {}) => {
                return $.ajax(url, {
                    async: true,
                    method: method,
                    data: data,
                    dataType: 'json',
                    jsonp: false,
                    headers: {
                        // some custom headers
                    }
                });
            };

**Comment by marceloxp** [comment]
I'm missed a important information: its a Cross-Domain.

**Comment by stof** [comment]
Yeah, jQuery does not add the header for cross-domain requests, as that would be too painful (the CORS config would have to whitelist it as an allowed header).

Btw, that's the reason why we don't have a `isAjax` method on the Request object. We cannot identify Ajax requests by themselves (they are just plain old HTTP requests triggered by some JS code).

So the advice of @mx03 is the good one here: don't rely on detecting server-side whether it was an ajax request. Instead, embed the info about what you want in the request (through the Accept header, a query string parameter, a header that you set yourselves in JS and take care of when building the CORS config, etc...)

**Comment by marceloxp** [comment]
Solved with `JSONP` and *callback* parameter.

Thanks, guys ;)
