### ISSUE TITLE
[ERROR] The database schema is not in sync with the current mapping file.

### ISSUE THREAD

**Issue by MikSDigital** [symfony/symfony#27166]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.9

```
[ERROR] The database schema is not in sync with the current mapping file.
```
When using ```@ORM\Column(type="string", nullable=true)``` Doctrine annotation there is still error 
after executing ```php bin/console doctrine:schema:validate``` console command.

Tested with databases: SQLite, MariaDB.

But in the application itself all queries are working fine.

If ```nullable=true``` is not using, then schema validation runs without error.
Also if using ```@ORM\Column(type="text", nullable=true)``` (type=TEXT) there is no validation error.

**Comment by Tobion** [comment]
Does not look like a bug. Have you tried to update your schema to match your mapping?

Also this issue is about doctrine not Symfony. Please refer to https://github.com/doctrine/DoctrineBundle

**Comment by MikSDigital** [comment]
@Tobion , thanks for your quick reply! schema:update does not fix this issue also.

**Comment by sstok** [comment]
@MikSDigital MySQL (and MariaDB) "optimizes" the table structure in some cases when there is a varchar and char type within in the same table, IIRC setting the length of a char field to 10 will change all char fields to varchar.

I can't the reference information about this, but it's not something really worry about.
To know whats happening execute `schema:update` with `--show-sql` to see what will change and compare this with your current table structure 👍

**Comment by siewert87** [comment]
I have the same problem (MariaDB 10.3) and maybe it also has something to do with internal optimization. The problem is that I run a `diff` and then a `migrate`. When I run a `diff` again, doctrine creates the same migration file and so on. Is there anything we can do?

**Comment by parijke** [comment]
same problem here... using 10.3.17-MariaDB-1:10.3.17+maria~bionic

**Comment by siewert87** [comment]
@parijke According to another github issue related to this issue, I setted `server_version: 'mariadb-10.3.17'` in `doctrine.yaml`. Unfortunately, I can't find it now, but maybe this helps you. For me the error is gone since I added this.

**Comment by WildWestDesigns-H** [comment]
Same problem here. Using 10.1.37-MariaDB with InnoDB, doctrine/dbal 2.9.2, orm 2.6.3 and migrations 2.1.0
When I run a `diff` again, doctrine keeps creating the same migration file for just 4 indexes which:
1/ I can see in the database after the first migration
2/ are correctly declared in annotations (i've checked and checked again)
3/ are correctly created in the first migration

Changing `server_version` in `doctrine.yaml` didn't change anything. Dropping the database and starting fresh with a new migration didn't work either.

**Comment by savedario** [comment]
Same issue here:
```
bin/console doctrine:schema:drop
bin/console doctrine:schema:create
bin/console doctrine:schema:validate

```
keeps returning the error.
@siewert87 suggestion fixed it for me.

**Comment by JBx0** [comment]
This one fixed it for me:
`php bin/console doctrine:schema:update --force --complete --dump-sql
`

**Comment by pierrealexaline** [comment]
Same here, with sqlite + Symfony 5.3.0 + Symfony CLI version v4.25.1 + PHP 7.4.3(cli). When i tried to validate shema with :
`php bin/console doctrine:schema:validate`. 
I always get :
 `[ERROR] The database schema is not in sync with the current mapping file.`.
It's the same after  :
`php bin/console doctrine:schema:update --force --complete --dump-sql` and 
`php bin/console doctrine:schema:validate`. 
I always get : `[ERROR] The database schema is not in sync with the current mapping file.`. 
I've controlled both entities, attributes, and the sqlite database and find no problem.

I tried to reproduce that with a new database with the same result. Now, i tried to reproduce that with a simple entity, without relations ans just and just an attribute. I come back later for the result.

**Comment by DelphineCogi** [comment]
Not sure if it's a general solution but..
I found out that my issue comes from a column type '"json" in one entity.

The migration is capable of detecting and generating the SQL order :

`CREATE TABLE report_order (report_order_id INT AUTO_INCREMENT NOT NULL, hotel_id INT NOT NULL, report_infos JSON NOT NULL,..`

But, if i launch migr:diff, it creates a new migration to ALTER this json column to.. a json type as if it is not able to read the json datatype in DB.

If I change :   
`@ORM\Column(name="report_infos", type="json")`

to

`@ORM\Column(name="report_infos", type="array")`

It works and no more diff file generated, and `php bin/console doctrine:schema:validate` is finally in sync

NB : 
- doctrine/dbal 2.13.9 
- doctrine/orm  2.12.3

**Comment by stof** [comment]
The schema comparison logic has been revamped entirely in doctrine/dbal 3.2 to solve many of those issues. You should definitely not be using DBAL 2.13 anymore (side note: DBAL 2.x is not maintained anymore, and doctrine/orm 2.12.x is not either).

**Comment by DelphineCogi** [comment]
> The schema comparison logic has been revamped entirely in doctrine/dbal 3.2 to solve many of those issues. You should definitely not be using DBAL 2.13 anymore (side note: DBAL 2.x is not maintained anymore, and doctrine/orm 2.12.x is not either).

You're preaching a converted.. !

**Comment by stof** [comment]
Well, commenting on an issue closed 6 years ago while using a version from 3 years ago was not making that clear to be honest (and the Doctrine team won't be able to do anything for you as they already fixed the issue years ago)

**Comment by DelphineCogi** [comment]
OK sorry, comments deleted

**Comment by pierrealexaline** [comment]
Ok with you Stof...the issues are linked to oldest version and have been resolved since with the updates of Doctrine and Symfony. You should not use unmaintained version.

**Comment by DelphineCogi** [comment]
Pas la peine d'en rajouter une couche sur une issue fermée
