### ISSUE TITLE
[3.4.9] symfony/http-foundation broken

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/symfony#27167]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.9

Upgrading `symfony/http-foundation` from 3.4.8 to 3.4.9 breaks `laravel/framework` 5.5 LTS.

That is, Laravel's sessions are functionally broken. Sorry this is quite vague. Looking through the [commit history](https://github.com/symfony/http-foundation/compare/v3.4.8...v3.4.9), it's likely either https://github.com/symfony/http-foundation/commit/dfc4b2f307dd65a863043a95fc12771e8322830b or https://github.com/symfony/http-foundation/commit/4b15446b894d0dca1d7f03a54734ae9121942420 is the culprit.

---

// cc @taylorotwell

**Comment by nicolas-grekas** [comment]
Please provide some description of the outcome, and a reproducer also.
There is nothing we can do here.

**Comment by nicolas-grekas** [comment]
@javiereguiluz I removed the BC break flag, this just a bug...

**Comment by GrahamCampbell** [comment]
Laravel is still broken by this.

**Comment by GrahamCampbell** [comment]
Can we keep this open, otherwise I have no way of tracking this. I will get around to this eventually, or someone else can step in if it's open, otherwise, this is not tracked.

**Comment by xabbuh** [comment]
Sure we can, but if we don't know *what* is broken and there is no reproducer, we won't be able to fix it. Did you manage to create a failing test or an example application in the meantime?

**Comment by GrahamCampbell** [comment]
I've had no time at all yet, but I will get around to it. :)

**Comment by xabbuh** [comment]
@GrahamCampbell I am going to close here for now. From Symfony's point of view there does not seem anything to be broken. I suggest to open an issue in the Laravel repo if you need something to keep track of it. We can consider to reopen here when there is any evidence that the misbehaviour is actually caused by an issue in the Symfony code.

**Comment by nicolas-grekas** [comment]
@GrahamCampbell see https://github.com/symfony/symfony/issues/27167#issuecomment-386837703
