### ISSUE TITLE
"Call to a member function getBaseUrl() on null" on exception in KernelTerminate event

### ISSUE THREAD

**Issue by maartendekeizer** [symfony/symfony#27174]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.9

When an exception occurred during a KernelTerimate event and a user is logged in the following fatal error occured:

`
PHP Fatal error:  Uncaught Symfony/Component/Debug/Exception/FatalThrowableError: Call to a member function getBaseUrl() on null in project_dir/vendor/symfony/security/Http/Logout/LogoutUrlGenerator.php:118
Stack trace:
#0 project_dir/vendor/symfony/security/Http/Logout/LogoutUrlGenerator.php(65): Symfony/Component/Security/Http/Logout/LogoutUrlGenerator->generateLogoutUrl(NULL, 1)
#1 project_dir/vendor/symfony/security-bundle/DataCollector/SecurityDataCollector.php(115): Symfony/Component/Security/Http/Logout/LogoutUrlGenerator->getLogoutPath()
#2 project_dir/vendor/symfony/http-kernel/Profiler/Profiler.php(162): Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector->collect(Object(Symfony/Component/HttpFoundation/Request), Object(Symfony/Component/HttpFoundation/Response), NULL)
#3 project_dir/vendor/symfony/http-kernel/EventListener/ProfilerListener.php(91): Symfony/Component/HttpKernel/Profiler/Profiler->collect(Objec in project_dir/vendor/symfony/security/Http/Logout/LogoutUrlGenerator.php on line 118
`

**Comment by xabbuh** [comment]
@maartendekeizer I am closing here for now as we were not able to track the real issue. But please feel free to leave a comment when you have more information and we can consider to reopen.

**Comment by garak** [comment]
I'm experiencing the same problem with Symfony 4.4-dev (but I see the same problem is present in master): the problem is in the following code:

```php
$request = $this->requestStack->getCurrentRequest();
$url = UrlGeneratorInterface::ABSOLUTE_URL === $referenceType ? $request->getUriForPath($logoutPath) : $request->getBaseUrl() . $logoutPath;
```

This is wrong, since `getCurrentRequest` can return `Request` or `null` and then no check is performed on returned value. So, when method is actually returning `null`, every call on `Request` methods causes an exception.

While I'm not able to clarify the situation when `$request` can be `null`, the only fact that it **can** be `null` should lead to a check on it

**Comment by krzyc** [comment]
The problem is still relevant in security-http v4.4.44. I agree that $request should be checked against null value to avoid Fatal Error _Call to a member function getBaseUrl() on null_ @xabbuh

**Comment by nicolas-grekas** [comment]
This issue is closed. Please open a new one or better a PR, if you think there's something to fix.
Commenting on closed issues is going to be lost (as happened to the previous comment btw)
