### ISSUE TITLE
Labels in CheckboxType are not translated

### ISSUE THREAD

**Issue by plecler** [symfony/symfony#27173]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.8

The label in a CheckboxType are not translated:

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('available',
                                "Symfony\Component\Form\Extension\Core\Type\CheckboxType",
                                array('label' => 'form.label.available'));
    }
```
```
# messages.fr.yml
"form.label.available": "Disponible"
```
The label displayed in the form view is _form.label.available_.

If I replace _Symfony\Component\Form\Extension\Core\Type\CheckboxType_ by _Symfony\Component\Form\Extension\Core\Type\TextType_, it is OK. The label displayed is _Disponible_

**Comment by xabbuh** [comment]
Which form theme do you use?

**Comment by HeahDude** [comment]
Hello @plecler I was not able to reproduce your issue in any maintained version. You can have a look at the Twig profiler to look form something like:
<img width="616" alt="form_debug_templates" src="https://user-images.githubusercontent.com/10107633/39693550-a9dacd74-51e4-11e8-986e-ad5a2c7c2fdc.png">

and try to know which template is used to render your checkbox.

**Comment by plecler** [comment]
Ooops, the error was in a customized template.
Thank you very much.
