### ISSUE TITLE
dump() breaks web debug toolbar

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#27180]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.1

When calling `dump('foo')` in my code, the web debug toolbar doesn't load and I get this error in my console:

```
Uncaught ReferenceError: Sfdump is not defined
    at eval (eval at load.maxTries ((index):1), <anonymous>:1:9)
    at load.maxTries ((index):23)
    at (index):23
    at XMLHttpRequest.xhr.onreadystatechange ((index):23)
```

**Comment by ogizanagi** [comment]
A quick git bisect indicates that it seems to happens since e4e591b46bcb81a436a8837d5cf5d5f335047da0

**Comment by kbond** [comment]
Thanks @ogizanagi, I hadn't had a change to dig in yet.

**Comment by ogizanagi** [comment]
Here is a fix: https://github.com/symfony/symfony/pull/27189
