### ISSUE TITLE
Bootstrap 4 form template file field looks ugly!

### ISSUE THREAD

**Issue by Chepainais** [symfony/symfony#27205]
**Symfony version(s) affected**: 4.1

**Description**  
Horizontal Form  bootstrap4  uses label tag to display file field, so in generated output all fields are located in wrong position.

**Comment by Chepainais** [comment]
![image](https://user-images.githubusercontent.com/2128351/39782635-671a0896-531b-11e8-9b87-7fd47908cf12.png)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue? Do you experience the same using Symfony 3.4 or 4.0?

**Comment by Chepainais** [comment]
Here it is!
Created test project with simple form, that user Bootstrap 4 horizontal form.
https://github.com/Chepainais/sf4-bs4-file-field

**Comment by mmarton** [comment]
The first problem is the size.
In the `{% block form_label_class -%}col-sm-2{%- endblock form_label_class %}` part of the bootstrap_4_horizontal_layout.html.twig file.
In BS the file input is hidden and the label is what seen as input, and the col-sm-2 makes it small.

The second problem is the position. The widget needs a legend tag like compound widgets, that pushes it right.

hope this helps

**Comment by xabbuh** [comment]
Is this still an issue with Symfony 4.1.2?

**Comment by xabbuh** [comment]
@Chepainais @mmarton Can you check if this is still an issue with the latest release?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
