### ISSUE TITLE
@Security annotations with the possibility to add the template option

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#27204]
**Description**  
My request is about the possibility of adding in the security annotations an option to request a certain template.

Since many times we will need a different security template than the typical one that lets us customize Symfony by default for everything.

**Example**  
`@Security("user.getEmail() == post.getAuthorEmail()", "template" = "CustomErrors/CustomTemplate.twig.html")`

**Comment by iltar** [comment]
There's also need for a special redirect based on authorization. We currently lack an extensible way of defining this kind of "middleware"

**Comment by ogizanagi** [comment]
There is an old issue related to this on the FrameworkExtraBundle repo: https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/332

**Comment by Simperfit** [comment]
This is more linked to FrameworkExtraBundle, can we close this one and reopen it on the right repo ?

**Comment by Aerendir** [comment]
@xabbuh , was this reopened in the right repo?

**Comment by xabbuh** [comment]
@Aerendir I thought the issue linked in https://github.com/symfony/symfony/issues/27204#issuecomment-387671517 was the good one. If that's not the case, can you please open one in the FrameworkExtraBundle repository?

**Comment by Aerendir** [comment]
@xabbuh , currently I have no use case, so any solution you will provide will be good for me.

But I'm in the process of working on customizing this kind of pages, so I was waiting for the proposed solution...

I will read the ticket you linked and see if I can add any useful...

Thank you for your reply!
