### ISSUE TITLE
[RFC] Introduce "semantics": a way to make service ids meaningful by binding them to types+descriptions

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#27207]
**Introduction**

Some service ids are more important than others: they are like entry points for the features provided by core or third party bundles (or the app itself). Yet, we are missing a way to reliably identify them amongst all the other service ids that are here just to make things work.

The `debug:container` command used to use the public/private concept as a way to make this distinction, but now that all/most services are private, we know this was a broken hack (which [has been removed in 4.1](https://github.com/symfony/symfony/pull/26921)). Autowiring gave us a different perspective on the topic: the aliases [we added](https://github.com/symfony/symfony/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+%22autowiring+aliases%22) to make it work *are* some of these meaningful identifiers. But there are more, like all the cache pools that users define in their configuration, or command buses, or logger channels, *etc.* - all sort of non-autowireable services that are still part of the useful services for users.

In #26142, @weaverryan tried to introduce "key services". This is another hint we're missing something, like a blind spot for a concept we didn't grasp yet. I'd like to introduce you to "semantics", which is a proposal I brainstormed about with @tgalopin and that IOHO could fill this hole.

**Semantics**

These meaningful services have 3 properties that make them special:
- their **id** convey semantics: it is a *meaningful* string that hints the purpose of the service (e.g. "logger", or "bus.command", etc.);
- we want to be able to enforce their type, so that 1. their id is bound to an abstraction and 2. they are made easy to discover and type-hint for;
- their purpose is documented, so that people can know why and when they should use any of them.

These 3 properties should be independent from the actual definition of the services that provide them. For this reason, we need something new, independent from Alias and Definition instances.

Given these contraints and definitions, the proposal is to make "semantics" a first class concept.
Technically, one could create them like that:

Using the ContainerBuilder directly:
```php
$container->setSemantics(string $id, array $types, string $description = null);
```

Using yaml:
```
semantics:
  cache.forecast:
    types: [Psr\Cache\CacheItemPoolInterface, Symfony\Component\Cache\Adapter\AdapterInterface]
    description: The cache pool where forecast-related items should be stored.
```

(the listed types should inherit from each others, so that this wouldn't allow creating new types that don't exist in PHP.)

**Use cases**

Provided with this additional semantics, we'll be able to:
- enforce that the service named "logger" implements the required interface
- build a better container-introspection command
- provide autowiring for multi-implemented interfaces (like in #27172)
- etc.

This should not incur any burden on regular users as the concept should be manipulated only by bundle authors.

**Comment by teohhanhui** [comment]
"Semantic" is an adjective, not a noun. The noun is "semantics".

**Comment by stof** [comment]
yeah, the suggest YAML fomat is inconsistent with the PHP API, as it uses a map of type to description. To map to the suggested PHP API, it should has 2 childs: `type` and `description`.

**Comment by nicolas-grekas** [comment]
> Could each semantic id be tied to multiple interfaces?

I think yes, but with a restriction: the listed interfaces should inherit from each other. It should not be possible to list unrelated interfaces there, because this would kinda define a new type that wouldn't exist in the code. Description updated.

**Comment by stof** [comment]
but then, does it even make sense to list multiple ones ? Listing the child one should be enough, no ?

**Comment by nicolas-grekas** [comment]
Technically, it would be enough, but I think it would be important to be able to select which interfaces are really the meaningful ones amongst the parents, so that we can build a better command line out of this info. That's quite similar to the fact that we create only selected aliases for autowiring. Does that make sense?

**Comment by michellesanver** [comment]
I just yesterday thought about how there currently is not an intuitive solution for this problem, this seems pretty straight forward and logical. I like it! I think with semantics the idea is to be very *explicit* about it all, so listing **all** the meaningful interfaces does make sense in my eyes. It also accidentally on purpose documents a part of the documentation that currently is looking a little bit like magic.

**Comment by michellesanver** [comment]
I’m going to work on this RFC as my first core contribution, with the mentoring of my knowledgeable colleagues at Liip 💚

It will take a little time to get into everything, I’ll start on Monday 👍

**Comment by michellesanver** [comment]
Just an update so you know, since I said I would get started: I got sick and had to prioritise other work when I got back on track, but I reserved some days to work on it the coming week 👍
