### ISSUE TITLE
[Debug] Ability to register custom fatal error handlers

### ISSUE THREAD

**Issue by fduch** [symfony/symfony#27201]
My purpose is to register custom fatal error handler inside my own bundle. 

As i initially understood the right way to do it is to override [ErrorHandler's getFatalErrorHandlers](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ErrorHandler.php#L653) method. 

The entire problem here is that i am not sure about how to replace original error handler with extended one. 

My first attempt involved substitution of original error handler inside my bundle's boot method:

```php
class MyBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function boot()
    {
        ErrorHandler::register(new MyErrorHandler($this->container), true)
            ->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
    }
}
```
But after https://github.com/symfony/symfony/pull/15521 was merged this approach became inconsistent with Debug::enable since initial error handler is registered depending on `$displayErrors` inside Debug::enable and after that it is hardly replaced by custom one (and original one is lost). 

So what is the right way to register custom fatal error handler without making all the things by myself (i mean replacing Debug::enable with custom logic that registers custom error handler)?

May be it would be reasonable to add something like `addFatalErrorHandler` method to ErrorHandler in order to make possible dynamic registration of fatal handlers?

**Comment by nicolas-grekas** [comment]
Can't you hook on the exception event from the kernel instead?
Fatal errors are turned into exception and thus you should be able to deal with them using a regular listener.
I'd suggest doing it this way (if it works of course).

**Comment by medliii** [comment]
Hi! 
Some errors (like E_PARSE) could be catch only with register_shutdown_function
event: kernel.exception doesn't work for them. At least for me)

**Comment by lisachenko** [comment]
Maybe, it would be nice to introduce an API to manipulate the fatal handler stack? For example, via compiler passes or by manual calling this API in vendor bundles.

**Comment by nicolas-grekas** [comment]
Did you register an exception handler on the error handler? This should work actually so that adding fatal error handlers should not be needed. How are you using the Debug component? Can you share a repos ?

**Comment by xabbuh** [comment]
@fduch Can you answer @nicolas-grekas' questions?

**Comment by fduch** [comment]
@nicolas-grekas @xabbuh, sorry for the late reply. 

I tried to use fatal error handler in order to pursue some "shutdown" work (aka collect failure statistics and finish up) in case of failures inside of one of infrastructure bundle. 

Nowadays i perform all the actions needed on the exception listener level and it looks acceptably.

So let's close the issue.
