### ISSUE TITLE
ServiceContainer Injection Loop leading into SegFault

### ISSUE THREAD

**Issue by moay** [symfony/symfony#27211]
**Symfony version(s) affected**: >3.2

**Description**  
When a service injects itself via autowiring, an injection loop happens which is not recoverable and leads to a SegFault (or an `OutOfMemory` exception).

**How to reproduce**  
We encountered this in a specific use case where we have an interface which we use for autoconfiguration with a tag. We used the tag to autoinject into a service which implemented the interface itself. 

As this is a complex usecase, I'll describe it in greater detail below.

**Additional context**  
For better understanding I want to layout the use case we encountered. I abstracted the actual use case, but the logic should be understandable. Consider this interface:

```php
// src/ScrewDrivers/ScrewDriverInterface
interface ScrewDriverInterface {
    public function supports(Screw $screw): bool;

    public function leftyLoosy(Screw $screw);

    public function rightyTighty(Screw $screw);
}
```

For this interface, we have a multitude of screwdrivers, let's just mention two of them:

```php
// src/ScrewDrivers/PhillipsScrewDriver
class PhillipsScrewDriver implements ScrewDriverInterface {
    public function supports(Screw $screw): bool
    {
        return ScrewHeadType::PHILLIPS === $screw->getHeadType();
    }

    public function leftyLoosy(Screw $screw)
    { //... turn left and do stuff }

    public function rightyTighty(Screw $screw)
    { //... turn right and do other stuff }
}
```

```php
// src/ScrewDrivers/TorxScrewDriver
class TorxScrewDriver implements ScrewDriverInterface {
    public function supports(Screw $screw): bool
    {
        return ScrewHeadType::TORX === $screw->getHeadType();
    }

    public function leftyLoosy(Screw $screw)
    { //... turn left and do stuff }

    public function rightyTighty(Screw $screw)
    { //... turn right and do other stuff }
}
```

And so on, you get what I mean. In order to have a cool ScrewingService, we want to autoinject the right screwdriver. This is done using a resolver which will be injected and automatically use the right screwdriver for the screw.

```php
// src/ScrewDrivers/MagicScrewDriver
class MagicScrewDriver implements ScrewDriverInterface {
    private $screwDrivers;

    public function __construct(iterable $screwDrivers) {
        $this->screwDrivers = $screwDrivers;
    }

    public function supports(Screw $screw): bool
    {
        foreach ($this->screwDrivers as $screwDriver) {
            if ($screwDriver->supports($screw)) {
                return true;
            }
        }
        return false;
    }

    public function leftyLoosy(Screw $screw) {
        foreach ($this->screwDrivers as $screwDriver) {
            if ($screwDriver->supports($screw)) {
                return $screwDriver->leftyLoosy($screw);
            }
        }
        
        throw new UnknownScrewException('Screw it!');
    }

    // Same for rightyTighty()
}
```

This setup allows us to have a great interface which we would now like to use in our service by injecting it and aliasing it to the magic screw driver.

```yaml
// config/services.yaml
services:
    _defaults:
    	autowire: true
    
    App\ScrewDrivers\ScrewDriverInterface:
        alias: App\ScrewDrivers\MagicScrewDriver
        
    App\ScrewDrivers\MagicScrewDriver:
        arguments:
            $screwDrivers: !tagged app.screwdriver

```

```yaml
# src/Kernel

    function build(ContainerBuilder $container)
    {
        $container->registerForAutoconfiguration(ScrewDriverInterface::class)
            ->addTag('app.screwdriver')
        ;
    }

```

And finally, in my ScrewingService:

```php
// src/Service/ScrewScrewer
class ScrewScrewer {
    private $screwDriver;
	
    public function __construct(ScrewDriverInterface $screwDriver) {
        $this->screwDriver = $screwDriver;
    }

    public function loosen(Screw $screw) {
        if (!$this->screwDriver->supports($screw)) {
            throw new WrongScrewDriverException('Screw it again!');
        }
	
        while(!$screw->isLooseEnoughToTakeByHand()) {
            $this->screwDriver->leftyLoosy($screw);
        }
    }
}
```

This *could* be the perfect setup for a completely reusable service with autowiring and autoconfiguration doing all the hard work. Sadly, the `MagicScrewDriver` will be injected into it's own constructor and lead to a loop of death.

I hope the use case is understandable? Do you (like me) think that this issue deserves a solution (other than just letting the SegFault happen)?

**Possible Solution**  
I find it very hard to think of a good solution. There are few use cases where this is applicable and where a service class layout as the above might be useful.

There should be a solution (at least a proper Exception), just letting the SegFault happen is not very debuggable.

After thinking of it, I come up with these ideas:

- Detect the injection loop and throw a proper Exception
- Do automatically not inject the service into itself (Which would still allow for loops via two or more services)
- Allow exceptions on autoconfiguration (like `registerForAutoconfiguration(SomeInterface::class)->except([MagicScrewDriver::class])` (which is kind of ugly)) or on injection in the services.yaml (`$injection: !tagged my.tag (here?)` or maybe exlcude the MagicScrewDriver from Autoconfiguration by overwriting the auto tag or by disabling autoconfiguration
- Just force people to write an additional service (`ScrewDriverResolver`) which will render the using service less reusable (which one could consider a minor issue) and would make me sad (which is a major issue).

**Comment by jvasseur** [comment]
The infinite loop doesn't happens during injection because `!tagged` inject a lazy iterator that creates services only on first iteration.

The thing is, we can't forbid injection loops because they have valid use cases: a service could call itself with different arguments weaning we don't have an infinite loop (or more common: call another service that will call the first one).

I think what you should do is disable autoconfiguration for the `MagicScrewDriver` service to stop him for being tagged and injected into itself.

**Comment by jvasseur** [comment]
Not sure why you still get an infinite loop when filtering by class, it should work.

You can disable autoconfiguration by putting `autoconfigure: false` in your `MagicScrewDriver` service definition.

**Comment by moay** [comment]
I'll look into it next week, thanks for the hint!

**Comment by moay** [comment]
Just tested that, this kind of blacklisting approach works and does exclude my service from autoconfiguration. For my special use case this is the right solution, I guess.

Besides me not being able to figure out the simple stuff, there still is the problem of the injection loops being hard to debug. A segmentation fault or an OutOfMemory exception don't tell anything about the actual problem and will lead to huge bug searches, especially for less advanced developers.

There should be some sort of loop injection detection and at least a hint that this could be a problem.

**Comment by nicolas-grekas** [comment]
Closing as resolved. About the infinite loop, there is nothing we can do on Symfony side. Sure a segfault is not nice, but that's on PHP, not Symfony. Thanks for the report.
