### ISSUE TITLE
Unknown database type enum requested

### ISSUE THREAD

**Issue by flik** [symfony/symfony#27218]
**Symfony version(s) affected**: 3.4

**Description**  
 php bin/console doctrine:schema:update --force

Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Pl
 atform may not support it.

**How to reproduce**  
 php bin/console doctrine:schema:update --force

**Possible Solution**  
https://stackoverflow.com/questions/8312271/how-to-enable-enums-in-symfony-2-doctrine

**Additional context**

**Comment by xabbuh** [comment]
I am going to close here as the code responsible for this is part of the `doctrine/*` packages.
