### ISSUE TITLE
[RFC][OptionsResolver] Add ability to deprecate options

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#27216]
**Introduction**  

Currently the consumers of the `OptionsResolver` component (mainly the `Form` component, later `LDAP` started to use it and possibly many bundles and libraries too) need sometime to delete or rename an already defined option or change its default value keeping BC, seeing itself in the need to create notes like this:
https://github.com/symfony/symfony/blob/07d25709a9da7fc55b000cda3de0502085e1854f/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L302

and manage themselves where and how to trigger the corresponding depreciation message:
https://github.com/symfony/symfony/blob/07d25709a9da7fc55b000cda3de0502085e1854f/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php#L250-L257

Moreover, _it isn't always effective if the option has a default value_. For instance, according to the previous code doing this:
```php
$builder->add('foo', EntityType::class, [
    // ...
    'property' => null,
]);
```
it wouldn't show the deprecation message because _when the configured default value is equal to the given value -> we don't know that this option is being used. Also, the normalizer function (as just one is allowed) can be overridden by any current child type or type extension in userland, in that case, the message wouldn't show either._

**Proposal to improve the current scenario**

Introduce a simpler and safer way to deprecate an option using a new method in `OptionsResolver`:
```php
public function setDeprecated(string $option, string $deprecationMessage = 'The option "%name%" is deprecated.', callable $callback = null): self
```
Then, if this option is used or has default value, the deprecation message always will be triggered. Conditionally you could deprecate some values of many feasible by using the 3rd argument.

It is a small but powerful feature as this information can be displayed anywhere, in the form profiler, `debug:form` command, etc. 

Other method that could help to know whether a given option is deprecated or not is:
```php
public function isDeprecated(string $option): bool
```

**Example**  

Deprecating a whole option:
```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'property' => null,
        'choice_label' => // ...
    ]);

    $resolver->setDeprecated('property', 'The option "property" is deprecated since Symfony X.Y. Use "choice_label" instead.');
}
```
Deprecating an option value:
```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver
        ->setDefault('foo', false)
        ->setAllowedTypes('foo', ['null', 'bool'])
        ->setDeprecated('foo', 'Passing "null" to option "foo" is deprecated since ...', function ($value) {
            return null === $value; // value before normalization
        })
    ;
}
```

Let me know first if it's something that core & community need. I've prepared a tiny PR for that.

Cheers!

**Comment by phansys** [comment]
It's an interesting feature, it would be nice to make possible to cover all the aspects supported by the component, like argument values and its types.

**Comment by yceruto** [comment]
@phansys yes, argument values and their types are already covered in the @iltar's idea: into callback func you could do that, e.g:
```php
->setDeprecated('foo', 'Passing "null", an integer or instance of "\Bar" to option "foo" is deprecated since ...', function ($value) {
    return null === $value || is_int($value) || $value instanceof \Bar;
})
```

**Comment by yceruto** [comment]
Although to be more accurate, probably we should accept a `string` or a `callable` as 2nd argument, if a callable is given it must return the deprecation message or `false` to skip, so:
```php
->setDeprecated('foo', function ($value) {
    if (null === $value) {
        $str = '"null"';
    } elseif (is_int($value)) {
        $str = sprintf('an integer "%d"', $value);
    } elseif ($value instanceof \Bar) {
        $str = sprintf('an instance of \Bar "%s"', get_class($value));
    } else {
        return false;
    }
    
    return sprintf('Passing %s to option "foo" is deprecated since ...', $str);
});
```

**Comment by yceruto** [comment]
Although to be more accurate, probably we should accept a `string` or a `callable` as 2nd argument, if a callable is given it must return the deprecation message or anything else to skip, so:
```php
->setDeprecated('foo', function ($value) {
    if (null === $value) {
        $str = '"null"';
    } elseif (is_int($value)) {
        $str = sprintf('an integer "%d"', $value);
    } elseif ($value instanceof \Bar) {
        $str = sprintf('an instance of \Bar "%s"', get_class($value));
    } else {
        return;
    }
    
    return sprintf('Passing %s to option "foo" is deprecated.', $str);
});
```

**Comment by Aerendir** [comment]
I like more to have three arguments each one with its purpose than have two.

**Comment by yceruto** [comment]
I think the purpose of the 2nd argument can be documented as well:
```php
/** 
 * @param string|callable $deprecationMessage The option deprecation message or function
 *                                            that accept the value and must return a string
 *                                            or anything else to skip
 */
```
In fact, that'll simplify a bit the implementation as only we've to save two data: option name (string) and deprecation message (string or callable), so with one internal variable `private $deprecated = array()` will be enough.

I can send the PR this week if there is no one against, it feels like enough :+1: to me :)
