### ISSUE TITLE
ImageValidator expect a string

### ISSUE THREAD

**Issue by etshy** [symfony/symfony#27226]
Symfony version : "symfony/framework-bundle": "^4.0",

Hi
I use MongoDB and I store my Images in DB with mongoGridFS.
I made a custom Transformer and UploadFileType to transform the UploadedFile into my own File class (possibly a childClass Image)

When i upload a File within a Form I have this message : `Expected argument of type "string", "App\Model\Document\Files\Image" given`
The file seems converted to my own Image Class but the validator wants a string.

My File class is the same than the Doctrine example : https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/storing-files-with-mongogridfs.html#storing-files-with-mongogridfs

My Image class just have $width and $heigth properties added.

Dunno if this behaviour is a bug or it's me that misread the doc.

**Comment by xabbuh** [comment]
This looks like a documentation issue to me. Would you like to open another issue in the docs repository? We could keep this issue open though and improve the validator in a future version to behave more like the file one.

**Comment by xabbuh** [comment]
closing here as no-one seems to really care
