### ISSUE TITLE
unable to make select in formtype  symfony4

### ISSUE THREAD

**Issue by valdanioDanio** [symfony/symfony#27223]
i am get this error: Type error: Return value of App\Entity\Estante::getDeposito() must be an instance of App\Entity\App\Deposito, null returned

this my code:

public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('numero', NumberType::class)
                ->add('deposito', EntityType::class, array(
                    'class' => Deposito::class,
                    'choice_label' => 'numero',
                ))
        ;
    }

**Comment by valdanioDanio** [comment]
It fixed

**Comment by iltar** [comment]
For support questions, please check https://symfony.com/support next time

**Comment by valdanioDanio** [comment]
Ok
