### ISSUE TITLE
[Form] DateTimeType value does not work for HTML5 datetime-local input in chrome

### ISSUE THREAD

**Issue by franzwilding** [symfony/symfony#27233]
**Symfony version(s) affected**: 4

**Description**  
DateTimeType passes values in format *yyyy-MM-dd'T'HH:mm:ssZ* to the html5 input element. However chrome expects the format *yyyy-MM-dd'T'HH:mm:ss* for datetime-local input types.

**How to reproduce**  
- Create a form with a DateTimeType child, widget = 'single_text'
- Pass data to the form
- Render the form in chrome (v66)
- An empty datetime input will be rendered

**Possible Solution**  
When trying to set the format to DateTimeType::HTML5_FORMAT (yyyy-MM-dd'T'HH:mm:ss), the DateTimeType will automatically add the DateTimeToRfc3339Transformer viewTransformer which uses the format *yyyy-MM-dd'T'HH:mm:ssZ*.

- One solution would be make the use of DateTimeToRfc3339Transformer optional
- Another solution would be to get rid of the trailing Z in DateTimeToRfc3339Transformer, which would also be valid in RFC3339 I think.

**Comment by nicolas-grekas** [comment]
Doesn't the issue also exist on lower branches?
Would you like to submit a fix?

**Comment by franzwilding** [comment]
This also is an issue for lower branches, starting with the introduction of datetime-local in 2.7. Yes, I can submit a fix, however I'm not surre about the best way to fix this. 

HTML specs says, that input of a datetime-local should: [... consists of a specific proleptic-Gregorian date, consisting of a year, a month, and a day, and a time, consisting of an hour, a minute, a second, and a fraction of a second, but expressed without a time zone.](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#concept-datetime-local)

This is not valid RFC3339, because the timezone is mandatory. I think the cleanest solution would be to rename DateTimeToRfc3339Transformer (it is not used anywhere else) to something like DatTimeToHTML5DateTimeLocalTransformer and get rid of "Z" in the transform method of the transformer. What do you think?

**Comment by xabbuh** [comment]
I would introduce a new transformer to avoid BC breaks. We can deprecate the then unused transformer in Symfony 4.2.
