### ISSUE TITLE
Thow expection with EntityType and 'choices' option 

### ISSUE THREAD

**Issue by makm** [symfony/symfony#27235]
Symfony version  4.0.9
symfony/form v4.0.9
symfony/doctrine-bridge v4.0.9

Simple use symfony's form builder

        $formBuilder->add('categories', EntityType::class, [
            'class'        => Category::class,
            'choices'      => $categoryRepository->findAll(),
        ]);

Actual result: throw RuntimeExcetion with message:
Entities passed to the choice field must be managed. Maybe persist them in the entity manager?

After investigation problem found solution, use : 
 'choice_value' => null,

Is it correct bihouver ?

**Comment by yceruto** [comment]
Are you using two database connection? It seems that the default entity manager is not the one related to `$categoryRepository`... or `findAll()` method has been overloaded into `$categoryRepository` ?

**Comment by yceruto** [comment]
If you remove this line:
```php
'choices'      => $categoryRepository->findAll(),
```
does it work for you?

**Comment by makm** [comment]
It's work. $categoryRepository - simple repository created by em & findAll - original method.
I talk about non-obvious behavior, it's not problem. Thank you

**Comment by xabbuh** [comment]
Can you create a small application that allows to reproduce your issue?
