### ISSUE TITLE
tests for UnsupportedMediaTypeHttpExceptionTest and UnprocessableEntityHttpExceptionTest

### ISSUE THREAD

**Issue by ncou** [symfony/symfony#27238]
Hi,

It seems to me there is some strange tests for the 2 exceptions UnprocessableEntityHttpExceptionTest and UnsupportedMediaTypeHttpExceptionTest, it looks like the constructor is instancied with a 10 value, but there is no use for this test. perhaps it's a problem with a copy/paste from another class test who need to use for example a retryValue = 10.
To me a function "createException()" with no param in the constructor seems enough for the tests.

I am missiong something ?

**Comment by ncou** [comment]
hi, i could try a PR, but i am not really friendly with github, and didn't could run the tests before submitting the PR. here is my explanation,  if it's not clear i will submit a PR without testing.

For the 2 tests, there is a new class with a parameter = 10 : 

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Tests/Exception/UnprocessableEntityHttpExceptionTest.php#L19

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Tests/Exception/UnsupportedMediaTypeHttpExceptionTest.php#L14

but these 2 class doesn't take a first parameter as integer :
here are the 2 constructors :

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Exception/UnprocessableEntityHttpException.php#L25

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Exception/UnsupportedMediaTypeHttpException.php#L25

The "testHeadersSetter()" function is used to test the getter/setter for a class with a constructor who need a parameter int like "retryAfter". in this case, this function is not needed (in my opinion) for these 2 test class.

I think it's a wrong copy/paste from for example : 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Tests/Exception/ServiceUnavailableHttpExceptionTest.php#L33

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Tests/Exception/TooManyRequestsHttpExceptionTest.php#L33

who use a retry value in the constructor.

But perhaps i am missing something.

**Comment by xabbuh** [comment]
@ncou removing the argument from these two examples looks fine to me. Would you like to create the PR?

**Comment by ncou** [comment]
Ok i will submit a PR. If the constructor is the same, the tesHeaderSetter() test is useless because it's tested via the "mother class" used to extend the test class. I will clean the 2 class and submit a PR.

**Comment by ncou** [comment]
Ok the PR is here : https://github.com/symfony/symfony/pull/27256
Let me know if all is ok.

Keep up the good work.
