### ISSUE TITLE
Warning on cache:warmup with empty var/cache dir

### ISSUE THREAD

**Issue by antonmedv** [symfony/symfony#27234]
**Symfony version(s) affected**: 4.1.x

**Description**  
Running  `bin/console cache:warmup` on empty cache dir triggers error reporting to rollbar, really annoying.

**How to reproduce**  
* Remove/or create empty `var/cache` dir
* Run `bin/console cache:warmup`
* **E_WARNING**
  ```
  include(/.../var/cache/prod/srcProdProjectContainer.php):: include(...): failed to open stream: No such file or directory
  ```
**Possible Solution**  
Do NOT trigger **E_WARNING**.

**Additional context**  
https://github.com/symfony/symfony/blob/226e2f3949c5843b67826aca4839c2c6b95743cf/src/Symfony/Component/HttpKernel/Kernel.php#L531-L540

**Comment by nicolas-grekas** [comment]
Can you share some steps to reproduce the issue? I just did this but failed to reproduce:
```
composer create-project -s dev symfony/skeleton
cd skeleton
./bin/console c:w
```

**Comment by antonmedv** [comment]
Yes, output is ok to console. Try to add rollbar or set error handler.

**Comment by nicolas-grekas** [comment]
So, this is a silenced error, there's no bug here, that's how things work...

**Comment by xabbuh** [comment]
I am going to close as explained.

**Comment by nicolas-grekas** [comment]
Hum, we can still prevent the notice in the usual case, see #27249
