### ISSUE TITLE
[Console] Shell verbosity BC break

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#27242]
**Symfony version(s) affected**: 3.3.3+

From what I see, this [commit](https://github.com/symfony/symfony/commit/87bd741f2d4f6b66f03b5856d6bafa9fa7e7f6c5) introduce a BC break kept up to the current master.

To illustrate the issue, if you have a test case testing a command with different levels of verbosity:

- check the output with the command run in quiet verbosity
- check the output with the command run in normal verbosity
- ...

And those verbosity levels are set by passing `-q`, `-v`, `-vv` or `-vvv` with the `ApplicationTester`, the first test is going to set the `SHELL_VERBOSITY` environment variable to `-1` where previously it was not existent. And for the next test (normal verbosity), it will pick up the environment variable using and as a result using the quiet verbosity instead of normal

/cc @nicolas-grekas since you are the author of that commit. I'm not sure if it was intended or not.

**Comment by theofidry** [comment]
ping?

If it doesn't bother much people I'm fine with this BC break, but IMO it should at the very least be documented...

**Comment by nicolas-grekas** [comment]
Doc PR welcome.
