### ISSUE TITLE
[Windows] hiddeninput.exe will hang permanently during phpunit test

### ISSUE THREAD

**Issue by lancepioch** [symfony/symfony#27248]
**Symfony version(s) affected**: 4.0.9 (symfony/console)

**Description**  

https://github.com/symfony/symfony/blob/v4.0.9/src/Symfony/Component/Console/Helper/QuestionHelper.php#L309
This `shell_exec` will permanently hang while running through a phpunit (my version: 7.1.5) test

**How to reproduce**  

Run a test with phpunit that utilizes the getHiddenResponse method (such as the Laravel console `$this->secret`)

**Comment by sstok** [comment]
There is some special logic required for using the Question Helper in a test, see https://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input for a more complete example.

**Comment by lancepioch** [comment]
@sstok Thanks for this. I'm not sure if I should keep the issue open, because this isn't an issue with Linux, only on Windows does this happen. What do you think?

**Comment by lancepioch** [comment]
@sstok I just wanted to update you here and let you know that using `->setInputs` doesn't work with the CommandTester.

The only workaround I've managed so far is changing `->setHidden(true)` to `->setHidden(false)`

Without doing that, the hiddeninput.exe is still called which infinitely hangs then.

**Comment by stof** [comment]
the InputTester indeed cannot work for hidden questions on windows, as these hidden questions on windows are precisely *not* using the Input object (because there is no way to actually hide the input in the shell on windows).

**Comment by javiereguiluz** [comment]
I'm closing because it looks like a problem that can't be solved ... but we're improving the docs to explain this: https://github.com/symfony/symfony-docs/pull/9964
