### ISSUE TITLE
Incompatibility between internationalized routing and prefix imported route names

### ISSUE THREAD

**Issue by pfx2** [symfony/symfony#27244]
**Symfony version(s) affected**: 4.1.0-beta

**Description**  
When using "name_prefix" to prefix all names of some imported routes AND when defining an internationalized route, it's not possible to generate a route with the normal route name (not including the locale with the dot).

**How to reproduce**  
1) Add a name_prefix for some imported routes
```yaml
front:
    resource: ../../src/Controller/Front
    type: annotation
    prefix: /
    name_prefix: front_
```
2) Add an internationalized route in a controller matched by the previous definition
```php
/**
 * @Route({
 *     "fr": "/test-fr",
 *     "en": "/test-en"
 * }, name="home_test")
 * @Template
 */
public function test(): array
{
    return [];
}
```

3) You can't generate a route for "front_home_test", which would use the current locale, as excepted, you can only generate a route for "front_home_test.fr" and "front_home_test.en". If you remove the name_prefix and include "front_" inside the name of the route, it works as excepted.

**Comment by nicolas-grekas** [comment]
@pfx2 would you like submitting a fix?

**Comment by javiereguiluz** [comment]
@pfx2 thanks for reporting this issue and for explaining how to reproduce it! As Nicolas hinted, we are always looking for new contributors so, would you like to give a shot at fixing this bug? We can help you during the entire contribution process. If you don't have time for this, it's OK, just tell us. Thanks!

**Comment by ismail1432** [comment]
The problem comes from this [line](https://github.com/symfony/routing/blob/master/Generator/UrlGenerator.php#L113) the`$name` is not prefixed as expected/defined in configuration.
I can't find where the `$name` is defined and where this function is called ^^

**Comment by nicolas-grekas** [comment]
@ismail1432 this function is called by *you* when you generate URLs, see https://github.com/symfony/routing/blob/master/Router.php#L238, so *you* pass it a name, when using the URL generator in e.g.  your controllers or templates.

**Comment by ismail1432** [comment]
I get a solution working for me, but I don't know it's **the good solution**.
I add the prefix to the route name cf : `_canonical_route` index in `$defaults` property from `Route` class.

Can you check the sample code before I create a PR and add more test.
I updated the `addNamePrefix()` from [RouteCollection](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Routing/RouteCollection.php#L159)
```php

public function addNamePrefix(string $prefix)
    {
        $prefixedRoutes = array();

        foreach ($this->routes as $name => $route) {
            if (null !== $route->getDefault('_canonical_route')) {
                $routeName = $route->getDefault('_canonical_route');
                $prefixedRouteName = $prefix.$routeName;
                $route->setDefault('_canonical_route', $prefixedRouteName);
            }

            $prefixedRoutes[$prefix.$name] = $route;
        }

        $this->routes = $prefixedRoutes;
    }
```
Another thing that I saw if it's you add the `name_prefix` option in `routes/annotation.yaml` It will add the prefix for all included routing resources.
```yaml
no_prefix_please:
    resource: ../../src/Controller/NoPrefix/
    type: annotation

app:
    resource: ../../src/Controller/
    type: annotation
    prefix: /
    name_prefix: front_
```
```php
//NoPrefixController
     /**
     * @Route("/bonjour", name="bonjour")
     */
    public function bonjour()
    {
        return $this->render('base.html.twig');
    }
```
For this action the Routing component wille create two routes `bonjour` and `front_bonjour` I don't know if it's the expected behavior.

I hope I've helped you

**Comment by stof** [comment]
> For this action the Routing component wille create two routes bonjour and front_bonjour I don't know if it's the expected behavior.

that's expected, as you still import this with the prefix. Being able to import the same resource with different prefixes is a feature actually as it might allow you to reuse the same shared code with different import-level config (name prefix, prefix, and maybe `_default`

**Comment by ismail1432** [comment]
Thanks @stof for explaination
