### ISSUE TITLE
Toolbar not showing when dumping variable

### ISSUE THREAD

**Issue by FabienPapet** [symfony/symfony#27258]
**Symfony version(s) affected**: 4.1-BETA1 - Worked on 4.0.9

**Description**  
A Js error generated by the Symfony toolbar, then it isn't showing up
```
ReferenceError: assignment to undeclared variable Sfdump
```

**How to reproduce**  

Clone this repository then run `composer install && php bin/console server:run`
https://github.com/FabienPapet/symfony-issue

**Possible Solution**  

n/a

**Additional context**  

```php
<?php
namespace App\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
class TestController extends Controller
{
    /**
     * @Route("/test", name="test")
     * @return Response
     */
    public function fooAction()
    {
        dump('test');
        return $this->render('base.html.twig');
    }
}
```

![image](https://user-images.githubusercontent.com/1446265/39995467-8f4f9532-577c-11e8-8572-df09ce2b5a84.png)

**Comment by ogizanagi** [comment]
Thanks for opening, but it's already fixed by #27189 😉 (will be available in beta2)
