### ISSUE TITLE
kernel.exception doesn't work with sentry

### ISSUE THREAD

**Issue by medliii** [symfony/symfony#27253]
There are 3 continious steps:
1) 
![image](https://user-images.githubusercontent.com/1991105/39983961-33e2eeac-5762-11e8-98bc-ef5dd46bd3e1.png)
2) 
![image](https://user-images.githubusercontent.com/1991105/39984012-5faf118c-5762-11e8-9616-2a1869fe460a.png)
3) 
![image](https://user-images.githubusercontent.com/1991105/39984018-674b185a-5762-11e8-81d2-96a6af0a08b8.png)

Bug on 3d screenshot.
So this code never triggered

``$this->exceptionHandler = function (\Exception $e) use ($kernel, $request, &$hasRun) {
                        if ($hasRun) {
                            throw $e;
                        }
                        $hasRun = true;
                        $kernel->terminateWithException($e, $request);
                    };
``

**Comment by medliii** [comment]
I am not sure too)
Any bundle makes this bug if it calles function **set_exception_handler** between 1 adn 3 steps .
Is it deprecate to call set_exception_handler? Then it is bundle bug
If not - symfony bug.

**Comment by stof** [comment]
Well, if the sentry integration replaces the exception handler registered by Symfony by its own, you will indeed loose all the exception handling performed by Symfony, as PHP can have only one handler.

A proper integration of sentry inside Symfony should hook into the `kernel.exception` event instead of replacing the exception handler.

**Comment by Jean85** [comment]
Sentry Bundle maintainer here. 

The bundle does both, because we want to catch also stuff like fatals and memory exhausted errors; we do not remove the Symfony error handler BTW, we register ours but we pass the errors back when handling. So I'm not sure what this report is about...

**Comment by medliii** [comment]
Standart ErrorHandler has
\Symfony\Component\Debug\ErrorHandler::$exceptionHandler
It's null at the beggining. And you (Sentry) save it's instance with null.
But later 
\Symfony\Component\HttpKernel\EventListener\DebugHandlersListener
tries to init it (3d screen). But it can't, because it doesn't see it. It sees you handler only (watch 3d screen params)

**Comment by Jean85** [comment]
I still don't understand what you're pointing to. We register Sentry's error handler later, on top of Symfony's, so we do not interfere with that.

What is the reproducing case for your bug? What steps are required? What behavior do you get? What would you expect instead?

**Comment by ste93cry** [comment]
I think that what he is saying is that the Symfony error handler is registered in `app_dev.php` (so the application is not initialized yet) but configured in the [`DebugHandlersListener`](https://github.com/symfony/symfony/blob/32cd453196914854f6957868948df09e5dad0d71/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php#L148) event listener 
which has a priority of 2048. The Sentry error handler is instead initialized with a method call [declared](https://github.com/getsentry/sentry-symfony/blob/566fa53c42cd720343937ec47e2432717a5bd270/src/Resources/config/services.yml#L7) in its service, which in turn is first used by the constructor of the [`ExceptionListener`](https://github.com/getsentry/sentry-symfony/blob/566fa53c42cd720343937ec47e2432717a5bd270/src/EventListener/ExceptionListener.php#L68) class provided by the Sentry Symfony bundle. Now what happens is quite clear: this last listener is invoked before the Symfony one and so the PHP error handler is set to the error handler provided by Sentry when the `DebugHandlersListener::configure` method is called. In turn the `if ($handler instanceof ErrorHandler) {` condition does not pass, leading to this issue

**Comment by Jean85** [comment]
I'm still unclear on a few details:

 * The `DebugHandlersListener` is active in dev env, right? So why are you using Sentry in dev?
 * Are you using ocramius/proxy-manager to have proper lazy loading?
 * what's the effect of this bug? the event `kernel.exception` is never dispatched?
 * does this affect the prod env too?

**Comment by xabbuh** [comment]
@medliii Can you answer the questions @Jean85 raised?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
