### ISSUE TITLE
The "," character should not be escaped in query strings using the URL generator

### ISSUE THREAD

**Issue by egonolieux** [symfony/symfony#27266]
**Symfony version(s) affected**: 3.4.8

**Description**  

I have a query string in which multiple values for a single parameter are delimited by a comma ",". According to RFC 3986 this comma does not need to be escaped in the query string. However, when I try to generate routes using the URL generator, the comma seems to get encoded. Is this by design or is this an oversight?

For example, the following code:

```
$url = $urlGenerator->generate('routeName', array(
    'category' => '1,2'
));
```

produces *https://www.example.com/path?category=1%2C2* instead of *https://example.com/path?category=1,2*.

**Comment by ismail1432** [comment]
@egonolieux I'm not agree. The ',' seems to be a  [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2) read more [here](https://stackoverflow.com/questions/2366260/whats-valid-and-whats-not-in-a-uri-query)

**Comment by sstok** [comment]
A common approach is to use `~` instead of a comma for separating values.

**Comment by ismail1432** [comment]
The problem is that we are using [http_build_query.php](http://php.net/manual/fr/function.http-build-query.php) and IMHO it could be tricky to override a native function created for that. [see code](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L267) where function is called

**Comment by egonolieux** [comment]
It might be a reseverd character indeed, but that does not mean it cannot be used in a certain context.
The accepted answer from the stackoverflow question you referred to states this:

> Thus commas are explicitly allowed within query strings and only need to be escaped in data if specific schemes define it as a delimiter. The HTTP scheme doesn't use the comma or semi-colon as a delimiter in query strings, so they don't need to be escaped

and

> Since commas don't have a reserved purpose under the HTTP scheme, they don't have to be escaped in data. The note from § 2.3 about reserved characters being those that change semantics when percent-encoded applies only generally; characters may be percent-encoded without changing semantics for specific schemes and yet still be reserved.

**Comment by ostrolucky** [comment]
https://github.com/symfony/symfony/pull/12223 is a precedent things like this are done in symfony though

**Comment by egonolieux** [comment]
@ostrolucky I wouldn't suggest hardcoding things like comma's though. The issue you referred to regarding */* is generally applicable to all URIs: https://tools.ietf.org/html/rfc3986#section-3.4.

Because there are many more characters than *,* which might be allowed in the query string in certain circumstances, I feel like it should be possible to override these characters by configuration.

The main issue is that if an URL with such characters in the query string is entered, the next page (using pagination for example), encodes these characters by default causing the URL to change.

**Comment by Simperfit** [comment]
Is there something to do here ?

**Comment by Tobion** [comment]
I'm fine with adding the `,` to the decoded chars similar to https://github.com/symfony/symfony/pull/12223/files.

**Comment by Tobion** [comment]
I opened a PR for this.
