### ISSUE TITLE
[RFC][Profiler] Enhance the performances panel & time collector

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#27262]
**Description**

I feel like this panel could benefits from some improvements.
Some of these are actionable right now, but there are some that could be discussed before sending PRs.

For instance:

- [x] **1.** The panel currently shows a set of categories hard-coded in the `time.html.twig` template, even if no stopwatch event for these occurred (e.g: `propel`). The `event_listener_loading` one isn't even used since 2.3:
    ![capture d ecran 2018-05-14 a 17 05 21](https://user-images.githubusercontent.com/2211145/40005762-181d3a10-5799-11e8-93d7-c72c3213f285.png)
    The time collector could provide the list of categories actually used during the request, so the template would only show them.

- **2.** https://github.com/symfony/symfony/pull/26833 traces controller argument resolvers since 4.1. But this is not easily identifiable in the panel. We could add a category for it:
   ![capture d ecran 2018-05-14 a 17 05 39](https://user-images.githubusercontent.com/2211145/40005763-18520d30-5799-11e8-971a-5c74647185a9.png)
    - [x] Dedicated category for controller argument resolvers (#28387)
   This PR also let me think we could add some other relevant categories. For now, I've in mind two other components for which these kind of metrics would be useful:
     - [ ] Serializer normalizers
     - [x] [Messenger middleware](https://github.com/symfony/symfony/pull/27321)

  👷🚧 _Part of this is started in https://github.com/symfony/symfony/pull/27321_

- [x] **3.** Disabling some categories by clicking on it would be useful:
      ![capture d ecran 2018-05-14 a 17 09 35](https://user-images.githubusercontent.com/2211145/40006660-39f4f400-579b-11e8-8398-47fff2ff6c66.png)

- [x] **4.** Rendering the graph using a canvas has some drawbacks:
     - no interactivity allowed
     - no text selection allowed
     - we can't use the browser search input to quickly jump to an event
     - the graph has a fixed size, which sometimes leads to truncated events (when the event is a long FQCN like the resolvers ones for instance)
  
  Perhaps we could switch to an SVG version to solve these limitations.

Do you think these kind of improvements are worth it? Do you have some others in mind?

**Comment by fabpot** [comment]
Quick note: "propel" can be removed permanently.

**Comment by stof** [comment]
I totally welcome any improvement to this graph if you have time to contribute to it.

Regarding the handling of categories, I'm wondering whether it would be possible to avoid having a hardcoded list, while still providing stable colors (so that `doctrine` does not change colors between views). This would make it work for any third-party event type too.

**Comment by ogizanagi** [comment]
We can probably try generating an hexadecimal color value from the category identifier, yes.

**Comment by javiereguiluz** [comment]
I'd love to maintain hardcoded the colors of Doctrine, Template, Events, Default and Section.

**Comment by stof** [comment]
`default` and `section` should indeed stay hardcoded in gray, as they are special (default is used when not having a special color, so gray makes sense, and sections are a totally different thing in the graph)

For doctrine, template and events, I don't actually care if the colors stay the same than the current ones with the new logic. It might be fine to have them different in 4.2.
We should still ensure that they get different colors with the new palette though, as they are event types which will likely almost always be there in the graph (yeah, I know you can create a project without Doctrine)

**Comment by javiereguiluz** [comment]
> For doctrine, template and events, I don't actually care if the colors stay the same than the current ones with the new logic. It might be fine to have them different in 4.2.

The orange color used in the Doctrine category is the same as the Doctrine logo and the green color used in the Template category is the same as the Twig logo. Using those colors reduce (a bit) the cognitive load needed to interpret the graph.

**Comment by Tom32i** [comment]
Hi there! I just submitted a draft pull request to implement the SVG graph renderer (4th point of the issue).

I'm still working on it and I welcome any thoughts or ideas on the subject.

**Comment by Simperfit** [comment]
So I if understand properly only the 1. and the  Serializer normalizers is missing ?

**Comment by ogizanagi** [comment]
Indeed. Also, feature requests as https://github.com/symfony/symfony/issues/17843 might benefit from recent changes to display more info interactively on the graph.

**Comment by ogizanagi** [comment]
Thanks to @javiereguiluz in #33535, I think we can consider closing this officially. Thanks!
