### ISSUE TITLE
Symfony serializer does not map collections correctly

### ISSUE THREAD

**Issue by fhink** [symfony/symfony#27279]
**Symfony version(s) affected**:  4.1.0

**Description**  
When there is a collection with a single item, the serializer creates produces an error instead of an array with one object.

```
Fatal error: Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the key "company" must be "int" ("string" given). in /Users/f.hink/www/collection_mapping_bug/Normalizer/ArrayDenormalizer.php:57
Stack trace:
#0 /Users/f.hink/www/collection_mapping_bug/Serializer.php(172): Symfony\Component\Serializer\Normalizer\ArrayDenormalizer->denormalize(Array, 'App\\Entities\\Of...', 'xml', Array)
#1 /Users/f.hink/www/collection_mapping_bug/Normalizer/AbstractObjectNormalizer.php(271): Symfony\Component\Serializer\Serializer->denormalize(Array, 'App\\Entities\\Of...', 'xml', Array)
#2 /Users/f.hink/www/collection_mapping_bug/Normalizer/AbstractObjectNormalizer.php(202): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize('App\\Entities\\Of...', 'office', Array, 'xml', Array)
#3 /Users/f.hink/www/collection_mapping_bug/Serializer.php(172): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denorm in /Users/f.hink/www/collection_mapping_bug/Normalizer/ArrayDenormalizer.php on line 57
```

**How to reproduce**  
https://github.com/fhink/symfony-collection-serializer-bug
Just run `php src/serialize.php`

**Possible Solution**  
https://github.com/fhink/symfony-collection-serializer-bug/commit/2f5984bcd87d8e24ccc824e33a461875cc92d69a

**Additional context**  
Tested with PHP 7.1+

https://stackoverflow.com/questions/49816306/symfony-serializer-deserialise-xml-which-contains-an-element-with-variable-amoun

**Comment by webnet-fr** [comment]
Yes it definetly looks like a bug. Current implementation of XmlEncoder decodes
```
<restaurants>
  <restaurant>
    <name>Some restaurant name</name>
    <type>Chinese</type>
  </restaurant>
  <restaurant>
    <name>Another restaurant name</name>
    <type>Italian</type>
  </restaurant>
</restaurants>
```
as
```
restaurants = {array} [1]
 restaurant = {array} [2]
  0 = {array} [2]
   name = "Some restaurant name"
   type = "Chinese"
  1 = {array} [2]
   name = "Another restaurant name"
   type = "Italian"
```
At the same time this xml
```
<restaurants>
  <restaurant>
    <name>Some restaurant name</name>
    <type>Chinese</type>
  </restaurant>
</restaurants>
```
will be decoded to:
```
restaurants = {array} [1]
 restaurant = {array} [2]
  name = "Some restaurant name"
  type = "Chinese"
```
This situation seems natural as there is no way in xml to indicate that a particular node is an element of a collection (unlike yaml or json).
Your possible solution seems ok because IMHO there is nothing to do with XmlEncoder because it is unaware of underlying type of `restaurants`. However I would wrap `data` in array only for xml format:

```
if ('xml'=== $format && !is_int(key($data))) {
    $data = array($data);
}
```

Otherwise two different yaml snippets :
```
restaurants:
  restaurant:
    - name: Some restaurant name
      type: Chinese
```
and
```
restaurants:
  restaurant:
    name: Some restaurant name
    type: Chinese
```
would be deserialized without any problem though the second snippent is not quite appropriate for your model.

Status: Reviewed

**Comment by nicolas-grekas** [comment]
Thanks for the report and the confirmation. Would any of you like to submit a fix?

**Comment by nano-freelancer** [comment]
I ask @fabpot attention to reopen issue

Faced the same issue, but now for the json-data(nested object) 
`{"object1":{"object2":[{"key1":0,"key2":1,"key3":2,"key4":3},{"key1":4,"key2":5,"key3":6,"key4":7}]}}`

Same error:
`Fatal error: Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the key "object2" must be "int" ("string" given)`

Fix provided in commit [1f346f4](https://github.com/symfony/symfony/pull/27326/commits/1f346f446d462e5d0b79bf0642ed4b89621a1684) works well if remove xml condition. I believe it is necessary to expand fix for json too.

**Comment by nicolas-grekas** [comment]
@nano-freelancer if you want anyone to really care, you'd better submit a new issue with detailed description. If you can submit a fix, that'd be even better. Thanks.

**Comment by nano-freelancer** [comment]
@nicolas-grekas done #28550

**Comment by dunglas** [comment]
@nano-freelancer can you post the corresponding PHP entity please?

**Comment by nano-freelancer** [comment]
> @nano-freelancer can you post the corresponding PHP entity please?

```
namespace App\Model;

use Doctrine\Common\Collections\ArrayCollection;

class ApiCall
{
    public $object1;

    public function __construct()
    {
         $this->result = new ArrayCollection();
    }

    public function getObject1() { 
         return $this->object1; 
    }
    public function setObject1($object1) { 
         $this->object1 = $object1; 
    }
    public function addObject1(Object1 $object1) { 
         if ($this->object1->contains($object1)) {
             return;
         }
         $this->object1->add($object1);
    }

}

class Object1
{
    public $object2;

    public function __construct()
    {
         $this->object2 = new ArrayCollection();
    }

    public function getObject2() { 
         return $this->object2; 
    }
    public function setObject2($object2) { 
         $this->object2 = $object2;
    }

    public function addObject2(Object2 $object2) {
         if ($this->object2->contains($object2)) {
             return;
         }
         $this->object2->add($object2);
    }
}

class Object2
{
    public function getKey1() { 
         return $this->key1; 
    }
    public function setKey1($key1) { 
         $this->key1 = $key1; 
    }
    public $key1; //String

    public function getKey2() { 
         return $this->key2; 
    }
    public function setKey2($key2) { 
         $this->key2 = $key2; 
    }
    public $key2; //int

    public function getKey3() { 
         return $this->key3; 
    }
    public function setKey3($key3) { 
         $this->key3 = $key3; 
    }
    public $key3; //String

}
```
in controller:
`$result = $serializer->deserialize($data, ApiCall::class, 'json');`
