### ISSUE TITLE
Autowiring twig environment crashes in 4.1

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#27283]
**Symfony version(s) affected**: 4.1.0-BETA1

**Description**  

Autowiring `Twig\Environment $twig` crashes

```
Controller "App\Controller\DefaultController" requires that you provide a value for the "$twig" argument.
Either the argument is nullable and no null value has been provided,
no default value has been provided or because there is a non optional argument after this one.
```

**How to reproduce**  
Upgrade from 4.0.9 to 4.1.0-BETA1 + require `symfony/debug-pack`

**Additional context**  
`cache:clear` went fine, web crashes.

See https://github.com/ro0NL/sf-project/commits/issues/27283

**Comment by ro0NL** [comment]
After unpacking `debug-pack + profiler-pack` it seems `"symfony/stopwatch": "^3.3|^4.0"` is causing it. Removing the dep solves it.

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/blob/4a7e6fa9bcc3f3aebffaa60a357b65054f8d6fa4/src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php#L50-L57

is causing it

**Comment by ogizanagi** [comment]
Already fixed in https://github.com/symfony/symfony/pull/27214 😉
