### ISSUE TITLE
Entity maker : $__EXTRA__LINE

### ISSUE THREAD

**Issue by mysterty** [symfony/symfony#27288]
**Symfony version(s) affected**: 4.0.4

**Description**  

command make:entity insert `private $__EXTRA__LINE;` when it should simply insert an extra line in the relatated entities.

It some times generate an error :

> PHP Fatal error:  Cannot redeclare App\Entity\Structure::$__EXTRA__LINE in /home/mysterty/Creations/www/vagrant-sellinity/sellinity/src/Entity/Structure.php on line 487

**How to reproduce**  

* run bin/console make:entity
* insert a new property ManyToMany or ManyToOne
* say yes when asked if it should add a new property to Child so it can access Parent

**Comment by stof** [comment]
This is a bug in the MakerBundle (and the developer reporting it earlier said it does not happen anymore for them in the latest version of the bundle).

So please try the latest version of MakerBundle and report the issue there if it still happens (with a reproducing case).

I'm closing this issue as `make:entity` does not come from symfony/symfony.

**Comment by mysterty** [comment]
The issue in MakerBundle is still openned. Direct link : https://github.com/symfony/maker-bundle/issues/170
