### ISSUE TITLE
Symfony CreateForm memory exhausted

### ISSUE THREAD

**Issue by jmoralespestana** [symfony/symfony#27298]
**Symfony version(s) affected**: 3.4.9

**Description**  
After update one of my projects to version 3.4.9 from 3.4..6 an OutOfMemoryException is thrown when creating a form in controller.
In version 3.4.6 all works fine

`$this->createForm('FormClass',$formData);`

> PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/sicocmeapi/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php on line 145

**How to reproduce**  
This is the environment where all happened

```
-------------------- --------------------------------------------
  Symfony
 -------------------- --------------------------------------------
  Version              3.4.9 <= here is the only change, at 3.4.6 all worked fine
  End of maintenance   11/2020
  End of life          11/2021
 -------------------- --------------------------------------------
  Kernel
 -------------------- --------------------------------------------
  Type                 AppKernel
  Name                 app
  Environment          dev
  Debug                true
  Charset              UTF-8
  Root directory       ./app
  Cache directory      ./var/cache/dev (365.1 MiB)
  Log directory        ./var/logs (134.0 MiB)
 -------------------- --------------------------------------------
  PHP
 -------------------- --------------------------------------------
  Version              7.0.28-0ubuntu0.16.04.1
  Architecture         64 bits
  Intl locale          n/a
  Timezone             America/Havana (2018-05-17T11:25:15-04:00)
  OPcache              true
  APCu                 false
  Xdebug               false
 -------------------- --------------------------------------------
```
Is this a bug from the update??

**Comment by ostrolucky** [comment]
Can you try going gradually from 3.4.6 up to 3.4.9 to see which specific version causes this?

**Comment by jmoralespestana** [comment]
It seem to be some incorrect configuration but I don't know where. I just generate a new 3.4.6 version and recreate the scenario from scratch

1. created the entities, the forms and test

2. then updated the symfony version to 3.4.9

After that all works fine, I did not change my server config at all.

**Comment by ostrolucky** [comment]
If you no longer have the reported issue, yes please close it :+1:

**Comment by RazaChohan** [comment]
@jmoralespestana I am facing the same issue on Symfony 3.4.40 can you kindly recommend how can I solve the issue ? Upgrading to Symfony 3.4.9 is not easier for me
