### ISSUE TITLE
Memcached with persitent connections segfaults

### ISSUE THREAD

**Issue by palex-fpt** [symfony/symfony#27299]
**Symfony version(s) affected**: 4.0.0

**Description**  
Enabling persistent connections for memcached provider, call to Memcached::createConnection starts throw segfault. 

**How to reproduce**  
```
public function testPersistentConnectionCreation()
	{
		/** @var \Memcached $instance */
		$instance = MemcachedCache::createConnection("memcached://localhost", ['persistent_id' => 'persistent']);
		$this->assertCount(1, $instance->getServerList());

		$instance = MemcachedCache::createConnection("memcached://localhost", ['persistent_id' => 'persistent']);
		$this->assertCount(1, $instance->getServerList()); // fail here. 

		// disabling previous assert leads to segfault due libmemcached-1.0.18 bug
		$instance = MemcachedCache::createConnection("memcached://localhost", ['persistent_id' => 'persistent']);
		$this->assertCount(1, $instance->getServerList());
	}
```

**Possible Solution**  
MemcachedTrait::createConnection should not add server to lists of servers when connection is not pristine and its servers list equals to configuration list

**Comment by nicolas-grekas** [comment]
would you provide a PR?
the segfault should also be reported to ext-memcache devs.

**Comment by palex-fpt** [comment]
Yes, I would provide PR.
It is old known bug in libmemcached: https://bugs.launchpad.net/libmemcached/+bug/1154159

**Comment by palex-fpt** [comment]
@nicolas-grekas I added PR to 3.3 branch. It is failed Travis CI build at unrelated components on some build configurations. Should I do something else?
