### ISSUE TITLE
Symfony PHPUnit Bridge is not compatible with Behat

### ISSUE THREAD

**Issue by sinner** [symfony/symfony#27300]
**Symfony version(s) affected**: 4.x.x

**Description**  
The developer is not able to use the Symfony PHPUnit bridge and PHPUnit functions using Behat.

**How to reproduce**  
If I'm using PHPUnit to test my services and other methods belongs to my project and moreover, I'm using Behat for testing my endpoints the PHPUnit functions are not available to be used into Behat context clasess.

Moreover, if I try to install PHPUnit to have those function available Symfony throw me an error:

```sh                                                                                             

 Adding phpunit/phpunit as a dependency is discouraged in favor of Symfony's PHPUnit Bridge. 
                                                                                             
  * Instead:
    1. Remove it now: composer remove --dev phpunit/phpunit
    2. Use Symfony's bridge: composer require --dev phpunit
```

**Comment by xabbuh** [comment]
In fact, this is not an error, but just a general recommendation that is triggered by [this recipe](https://github.com/symfony/recipes/tree/master/phpunit/phpunit/4.7). The `phpunit/phpunit` package should have been installed nonetheless and your code should work as expected. For the warning itself, we already have an open issue (see #27289). So I am going to close this one as a duplicate.
