### ISSUE TITLE
kernel.request event dispatch changed request method

### ISSUE THREAD

**Issue by ScorpioRen** [symfony/symfony#27302]
**Symfony version(s) affected**: x.y.z
  symfony/symfony (v3.4.9) php(7.2.4 )
**Description**  

when i use event kernel.request , i send http OPTIONS request when i try to get request in $event->getRequest() and call getMethod() function but it give me a GET method, so i print the php $_SERVER and $request->server and  find the array key 'REQUEST_METHOD' is different and php $_SERVER is right , so i debug find in HttpKernel.php 127 line after dispatch ,$event getRequest call getMethod change to GET
**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by ScorpioRen** [comment]
en , i try to create a app but it's right , en , i think  is my package do some thing , i don't know so i try create new project from a empty framwork

**Comment by ScorpioRen** [comment]
hello, i find wen i use FOSRestBundle make is change GET but in controller is OPTIONS

**Comment by ScorpioRen** [comment]
oh，I'm Sorry, I found the reason, because my listen is low priority, thanks

**Comment by xabbuh** [comment]
Thanks, I am closing here then.
