### ISSUE TITLE
Upgrade Symfony 2 to 3 - symfony-script error

### ISSUE THREAD

**Issue by nirvo** [symfony/symfony#27304]
Hi,

When I upgrade Symfony from 2.8 to 3.4 using "vcs", I get this error : 
![2018-05-18_050318](https://user-images.githubusercontent.com/39260499/40229540-d2032518-5a94-11e8-9429-b19b74d5387d.png)

My composer.json configuration is : 
![2018-05-18_050436](https://user-images.githubusercontent.com/39260499/40229599-fe7d37d2-5a94-11e8-8f7a-d207747fdfd3.png)

Suggestions ?

Best Regards

**Comment by iltar** [comment]
Is the Incenteev parameter installed?

**Comment by nirvo** [comment]
Woh I can check ?

**Comment by javiereguiluz** [comment]
@nirvo run `composer show` inside your project to get the list of packages (and versions) installed.

**Comment by nirvo** [comment]
@javiereguiluz I have no project, I am trying to upgrade the framwork itself (2.8 to 3.4)

**Comment by nirvo** [comment]
I have the same error after adding to composer.json the line : 
`"incenteev/composer-parameter-handler":` "~2.0"`

![2018-05-18_223214](https://user-images.githubusercontent.com/39260499/40256620-58d9a44e-5aeb-11e8-835b-abdc84b5ed30.png)

**Comment by nirvo** [comment]
yes, it works with   "sensio/distribution-bundle": "^5.0",
but I have not a message which confirm that updrage is OK : 

![2018-05-20_003710](https://user-images.githubusercontent.com/39260499/40273719-47a95da0-5bc6-11e8-826f-aa9a7a5e7591.png)

**Comment by xabbuh** [comment]
I am closing here as the issue seems to be resolved.
