### ISSUE TITLE
Are we love freedom? 

### ISSUE THREAD

**Issue by azatyan** [symfony/symfony#27313]
https://gist.github.com/azatyan/d63bc2a8e5848b5e059ab98a138a0975

FACEBOOK PROFILE DISABLED

https://www.facebook.com/tigran.v.azatyan

Dear Facebook, please open my profile publicly.
You simply can't stop this.
I don't have a any criminal case in Armenia...
Please open my public facebook profile....
#Armenia100 #Freedom #Iloveeverypeople #wecantstopthis #help #letsbuildthenewworldnow

My power is natural. Simply from the hardest life and i am not one.. <3

I am forgiving now everyone!

https://soundcloud.com/tigranazatyan/do-not-close-public-account-in-the-facebook-httpswwwfacebookcomtigranvazatyan

**Comment by azatyan** [comment]
@fabpot

**Comment by robfrawley** [comment]
This looks super sketch.

**Comment by azatyan** [comment]
This info is hidden from outside out Armenia.

Check with this link and do not share: https://pastebin.com/K0HBvKFX
