### ISSUE TITLE
Start Time Is Not Reset During Kernel Reboot

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#27319]
**Symfony version(s) affected**: 4.1-beta1, master

**Description**  
I started using Symfony with ReactPHP and discovered rather unusual behavior. While requests were lightning fast the profiler was more and more upset with each request.

<img width="823" alt="screenshot 2018-05-19 21 20 06" src="https://user-images.githubusercontent.com/1227834/40275005-6af2edc4-5baa-11e8-8407-09f3da1e8bd0.png">
<img width="299" alt="screenshot 2018-05-19 21 08 35" src="https://user-images.githubusercontent.com/1227834/40274974-18899146-5baa-11e8-9500-277d6fd33a4f.png">
<img width="311" alt="screenshot 2018-05-19 21 08 40" src="https://user-images.githubusercontent.com/1227834/40274975-1ce74652-5baa-11e8-84c5-a20f5471c68e.png">
<img width="300" alt="screenshot 2018-05-19 21 09 15" src="https://user-images.githubusercontent.com/1227834/40274980-21302e9a-5baa-11e8-95bb-662a9e7f783d.png">

**How to reproduce**  
1. Create kernel
2. Reboot kernel
3. Handle request
4. Terminate kernel
5. Go to step 2

**Possible Solution**  
I started digging and apparently `\Symfony\Component\HttpKernel\DataCollector\TimeDataCollector` calculates times based on `Kernel::getStartTime()` with fallback to request start time. While this approach works when kernel is created and destroyed during the request rebooting kernel doesn't cause `TimeDataCollector` to reflect the rebooted kernel state.

Workaround is simple - overwriting `reboot()`. However I think we should fix this in abstract kernel by calling `$this->startTime = microtime(true);` in `reboot()` just before `boot()` like so:

```php
    public function reboot($warmupDir)
    {
        $this->shutdown();
        $this->warmupDir = $warmupDir;

        if ($this->debug) {
            $this->startTime = microtime(true);
        }
        
        $this->boot();
    }
```

WDYT?

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR? I'd put the call in the boot method, next to the call to the `services_resetter`.

**Comment by kiler129** [comment]
Sure! I will do in the evening ;)
