### ISSUE TITLE
Issue with isPasswordValid in BCryptPasswordEncoder

### ISSUE THREAD

**Issue by DerKnerd** [symfony/symfony#27311]
**Symfony version(s) affected**: 4.0.9

**Description**  
The current version of symfony has an issue in the BCryptPasswordEncoder. When you use the following code to create a new user the user will be unable to login.

```php
$user->setPassword($this->userPasswordEncoder->encodePassword($user, $user->getPassword()));
```

Where user is the User class from symfony.

**IMPORTANT NOTICE** The example stated here is wrong cause it access the BCryptPasswordEncoder directly. Actually it is accessed via UserPasswordEncoderInterface, see [this comment](https://github.com/symfony/symfony/issues/27311#issuecomment-391753879) for details.

**How to reproduce**  
```php
<?php

$encoder = new \Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder(30);
$password = 'test';

$user = new User(); // User class based on symfony security User class
$user->setSalt(uniqid());
$user->setPassword($encoder->encodePassword($user, $password));

if ($encoder->isPasswordValid($user->getPassword(), $password, $user->getSalt())) {
    echo 'Authenticated';
} else {
    echo 'Wrong username or password';
}
```

**Possible Solution**  
Not actually meant as a solution, but when I reencode the password and compare them it works fine.

```php
<?php

$encoder = new \Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder(30);
$password = 'test';

$user = new User(); // User class based on symfony security User class
$user->setSalt(uniqid());
$user->setPassword($encoder->encodePassword($user, $password));

if ($encoder->encodePassword($user, $password) === $user->getPassword()) {
    echo 'Authenticated';
} else {
    echo 'Wrong username or password';
}
```

**Additional context**  
If it helps you can checkout the project I use the code in. See [here](https://github.com/Jinya-CMS/Jinya-Gallery-CMS/tree/44529ca04a55f9d4cd63184377b64ab5d5b2c5dd) the linked commit is the state of writing this issue.

**Comment by xabbuh** [comment]
This does sound more like a misconfiguration in your application. I suggest to seek for help in one of the [support channels](https://symfony.com/support) first and if that does not come to a solution add some more additional information here on where exactly the authentication is failing.

**Comment by DerKnerd** [comment]
@xabbuh Like I said, it is that the isPasswordValid method fails cause it ignores the salt completely, I already debugged it entirely even the symfony code. This is the position in the framework:

This is the call in `Symfony\Component\Security\Core\Encoder\UserPasswordEncoder`

```php
    /**
     * {@inheritdoc}
     */
    public function isPasswordValid(UserInterface $user, $raw)
    {
        $encoder = $this->encoderFactory->getEncoder($user);

        return $encoder->isPasswordValid($user->getPassword(), $raw, $user->getSalt());
    }
```

This is the call in the `Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder`

```php
    public function isPasswordValid($encoded, $raw, $salt)
    {
        return !$this->isPasswordTooLong($raw) && password_verify($raw, $encoded);
    }
```

Like I said, it completely ignores the fact, that a salt is passed or am I missing something?

**Comment by xabbuh** [comment]
That's expected. The salt is part of the hash when using bcrypt. Are you sure that `isPasswordValid()` returns with `false` in your case?

**Comment by DerKnerd** [comment]
Yes pretty sure. When I called it it didn't go into the if clauses body.

**Comment by jvasseur** [comment]
This looks strange. The BCrypt password encoder is ignoring the salt argument both when decoding (because it generate it's own salt) and when decoding (because the salt is contained into the hashed password).

This also means doing `$encoder->encodePassword($user, $password) === $user->getPassword()` shouldn't work because the pasword will be rehashed with a different salt thus resulting in a different hash.

**Comment by DerKnerd** [comment]
@slootjes a crap, I just noticed I have a mistake in the example. This is the correct example:

```php
<?php

$container = SymfonyContainer;
$encoder = $container->get('security.user_password_encoder.generic');
$password = 'test';

$user = new User(); // User class based on symfony security User class
$user->setSalt(uniqid());
$user->setPassword($encoder->encodePassword($user, $password));

if ($encoder->isPasswordValid($user->getPassword(), $password, $user->getSalt())) {
    echo 'Authenticated';
} else {
    echo 'Wrong username or password';
}
```

This code has the same behavior like the one stated in the original issue.

**Comment by DerKnerd** [comment]
@slootjes I tried and it didn't work. I also checked the implementation of the BCryptPasswordEncoder and it actually ignores the salt passed so it wouldn't matter at all.

So yeah the current code is the following:

```php
<?php

$container = SymfonyContainer;
$encoder = $container->get('security.user_password_encoder.generic');
$password = 'test';

$user = new User(); // User class based on symfony security User class
$user->setSalt(uniqid());
$user->setPassword($encoder->encodePassword($user, $password));

if ($encoder->isPasswordValid($user, $password) {
    echo 'Authenticated';
} else {
    echo 'Wrong username or password';
}
```

**Comment by stof** [comment]
@DerKnerd can you show us the implementation of `setPassword` and `getPassword` in your user ?

**Comment by DerKnerd** [comment]
An exception when I try to access it by the id you provided. Accessing it by the Interface gets the following type `Symfony\Component\Security\Core\Encoder\UserPasswordEncoder`

This is the exception message:
```
The "security.user_password_encoder.generic" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.         
```

**Comment by slootjes** [comment]
But how did you come up with the code you posted earlier to reproduce this then?

**Comment by slootjes** [comment]
How does that code work if you say the service that you are using is not available? Please be more specific in your code examples...this way no one can help you.

**Comment by DerKnerd** [comment]
Ok, the code I actually use is this piece, I tried to break it down. This is the code currently running and working against all odds.

```php
<?php
namespace Jinya\Services\Users;

use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Jinya\Entity\User;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;

class UserService implements UserServiceInterface
{

    /** @var EntityManagerInterface */
    private $entityManager;
    /** @var UserPasswordEncoderInterface */
    private $userPasswordEncoder;

    /**
     * UserService constructor.
     * @param EntityManagerInterface $entityManager
     * @param UserPasswordEncoderInterface $userPasswordEncoder
     */
    public function __construct(EntityManagerInterface $entityManager, UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $this->entityManager = $entityManager;
        $this->userPasswordEncoder = $userPasswordEncoder;
    }

    /**
     * Gets the user by username and password
     *
     * @param string $username
     * @param string $password
     * @return User
     */
    public function getUser(string $username, string $password): User
    {
        try {
            $user = $this->entityManager->createQueryBuilder()
                ->select('user')
                ->from(User::class, 'user')
                ->where('user.email = :username')
                ->setParameter('username', $username)
                ->getQuery()
                ->getSingleResult();
        } catch (Exception $e) {
            throw new BadCredentialsException($e->getMessage(), $e);
        }

        if (!$this->userPasswordEncoder->encodePassword($user, $password) === $user->getPassword()) {
            throw new BadCredentialsException("Invalid username or password");
        }

        return $user;
    }
}
```

But this code doesn't actually work, cause it lets everyone in. So I was wrong, currently there is no working solution.

This is the code that does not work, a BadCredentialsException is thrown.

```php
<?php

namespace Jinya\Services\Users;

use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Jinya\Entity\User;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;

class UserService implements UserServiceInterface
{

    /** @var EntityManagerInterface */
    private $entityManager;
    /** @var UserPasswordEncoderInterface */
    private $userPasswordEncoder;

    /**
     * UserService constructor.
     * @param EntityManagerInterface $entityManager
     * @param UserPasswordEncoderInterface $userPasswordEncoder
     */
    public function __construct(EntityManagerInterface $entityManager, UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $this->entityManager = $entityManager;
        $this->userPasswordEncoder = $userPasswordEncoder;
    }

    /**
     * Gets the user by username and password
     *
     * @param string $username
     * @param string $password
     * @return User
     */
    public function getUser(string $username, string $password): User
    {
        try {
            $user = $this->entityManager->createQueryBuilder()
                ->select('user')
                ->from(User::class, 'user')
                ->where('user.email = :username')
                ->setParameter('username', $username)
                ->getQuery()
                ->getSingleResult();
        } catch (Exception $e) {
            throw new BadCredentialsException($e->getMessage(), $e);
        }

        if (!$this->userPasswordEncoder->isPasswordValid($user, $password)) {
            throw new BadCredentialsException("Invalid username or password");
        }

        return $user;
    }
}
```

**Comment by DerKnerd** [comment]
I just found my mistake, @xabbuh was right the whole time. My mistake was, that I updated the password on every save and not only when the password actually changed. This was my mistake and I want to apolagize for all the stress it made.

**Comment by AdamReece-WebBox** [comment]
Also hit this today. Same mistake. `"mapped" => false` in my user edit form class for the new password field is necessary.
