### ISSUE TITLE
debug:route in yml

### ISSUE THREAD

**Issue by biji** [symfony/symfony#27334]
**Description**  

Please add feature to debug:route in yml format. This would help migrating from annotation route to yml

**Example**  

There was a bundle name: sed/route-exporter-bundle , but does not work in symfony 4

`./bin/console debug:route --show-controllers` already output required fields, but not in yaml format

Thanks

**Comment by iltar** [comment]
You can grab the json and convert it to an array and then to yaml via the yaml dumper. In case you want to do it right now.

**Comment by Dannebicque** [comment]
I can try to propose something to this issue. My first contribution :)

**Comment by Dannebicque** [comment]
Hello everyone,

I work on this issue, and I obtain this result (on an example):

`qr_code_generate:
  path: /qr-code/{text}.{extension}
  controller: Endroid\QrCodeBundle\Controller\GenerateController
  methods: ANY
  defaults:
  requirements:
    text: [\w\W]+


fos_js_routing_js:
  path: /js/routing.{_format}
  controller: fos_js_routing.controller::indexAction
  methods: GET
  defaults:
    _format: js
  requirements:
    _format: js|json


translation_edit_in_place_update:
  path: /admin/_trans_edit_in_place/{configName}/{locale}
  controller: Translation\Bundle\Controller\EditInPlaceController::editAction
  methods: POST
  defaults:
`

Is-it the good way ?

**Comment by fabpot** [comment]
I think what @linaori  proposed is enough. Let’s close.
