### ISSUE TITLE
[Messenger] Allow defining an empty sender service

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27335]
**Symfony version(s) affected**: 4.1

**Description**  
While improving Messenger docs (https://github.com/symfony/symfony-docs/pull/9771) we found an example that we don't know if it's going to work or not.

```xml
<framework:config>
    <framework:messenger>
        <framework:routing message-class="My\Message\ThatIsGoingToBeSentAndHandledLocally">
            <framework:sender service="amqp" />
            <framework:sender service="" />  <!-- <==== WOULD THIS WORK? -->
        </framework:routing>
    </framework:messenger>
</framework:config>
```

Original comment from @xabbuh: https://github.com/symfony/symfony-docs/pull/9771#discussion_r189308476

**Comment by ogizanagi** [comment]
Oops! I was trying to answer @xabbuh in https://github.com/symfony/symfony-docs/pull/9771#discussion_r188225247 but missed https://github.com/symfony/symfony-docs/pull/9771#discussion_r189308476 afterwards.
This isn't supposed to work anymore AFAIK, as it was replaced by a new `send_and_handle` option on the routing node instead in https://github.com/symfony/symfony/pull/27002

**Comment by sroze** [comment]
Closing, as @ogizanagi explained.
