### ISSUE TITLE
Problem JS custom data collector

### ISSUE THREAD

**Issue by vDenizart** [symfony/symfony#27332]
Hi,

according to this page : https://symfony.com/doc/current/profiler/data_collector.html

I created a custom data collector that works fine, but I think there's a problem with the head block : Whether I put js or css in it, it doesn't work

I tried with a simple JS alert, and nothing...

For now I put my JS at the end of the toolbar block and it works fine. Is there something I have to do in the head block to make my JS work in it, or this is a bug ?

I was working on SF 4.0, and I just upgraded to 4.1 BETA-2, and still not working.

Thank you

**Comment by stof** [comment]
the head block is for the panel display, for the toolbar block (there is no head in the toolbar as it is not a full page)

**Comment by vDenizart** [comment]
oh Ok, so if I have some JS is it correct to put it in the the toolbar block ?

Thanks for your quick reply.

**Comment by stof** [comment]
if you have some JS for the toolbar itself, yes (but then, be careful about the browser compatibility of this JS, as this code will have to run inside the user page and so must never break the user app due to a bug in the debug tools)

**Comment by vDenizart** [comment]
Yes of course. Thanks for your help !
