### ISSUE TITLE
[Lock] Support for MongoDB Store

### ISSUE THREAD

**Issue by kralos** [symfony/symfony#27345]
**Description**  
We should support Semaphore Locks with a MongoDB back end to allow those that already use MongoDB as a distributed storage engine.

Symfony already partially supports MongoDB for session storage: `Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler`

**Example**

```php
$client = new MongoDb\Client();

$store = new Symfony\Component\Lock\Store\MongoDbStore(
    $client
    array(
        database: '%mongo_database%'
        collection: lock
    )
);
$lockFactory = new Symfony\Component\Lock\Factory($store);
$lock = $lockFactory->createLock('my-resource');
```

**Comment by fabpot** [comment]
As this would be a new feature, it would go into 4.2, so it would not support the legacy drivers.

**Comment by kralos** [comment]
I've rebuilt the branch off `master` and stripped out the legacy support.
