### ISSUE TITLE
./vendor/bin/simple-phpunit sh: 1: composer: not found

### ISSUE THREAD

**Issue by phpdevnaga** [symfony/symfony#27354]
"symfony/phpunit-bridge": "^4.0" 
added this package in to composer --dev, which composer available in docker container 
I am trying to run  the phpunit test inside php docker container, throwing error says composer not found

**Comment by stof** [comment]
is `composer` available in your path in the container running `simple-phpunit` ?

**Comment by javiereguiluz** [comment]
@phpdevnaga thanks for reporting this issue. However, we're missing some information to be able to help you. Please update the description of your issue to include the information asked in the template GitHub showed you when creating the issue:

```
**Symfony version(s) affected**: x.y.z

**Description**  
<!-- A clear and concise description of the problem. -->

**How to reproduce**  
<!-- Code and/or config needed to reproduce the problem. If it's a complex bug,
     create a "bug reproducer" as explained in:
     https://symfony.com/doc/current/contributing/code/reproducer.html -->

**Possible Solution**  
<!--- Optional: only if you have suggestions on a fix/reason for the bug -->

**Additional context**  
<!-- Optional: any other context about the problem: log messages, screenshots, etc. -->
```

**Comment by nicolas-grekas** [comment]
The reason is what @stof hints: `composer` is not found in the `PATH`. We could throw a better error message for sure when this happens. Anyone willing to give it a try?

**Comment by derrabus** [comment]
We could also download a composer.phar if composer is not in the path. Or would that be too intrusive?

**Comment by lyrixx** [comment]
>  Or would that be too intrusive?

Yes IMHO

**Comment by ostrolucky** [comment]
Lot of people use different docker container for running composer than php binary they use to run the project. IMO this is completely wrong practice and should be clarified by documentation to avoid issues like this one

**Comment by nicolas-grekas** [comment]
one could run `./bin/phpunit install` in this other container where composer is installed thought!

**Comment by ostrolucky** [comment]
yep and if php binary in composer is different version than php binary project uses, it might install wrong dependencies

**Comment by KamilKopaczyk** [comment]
1.
> Is it really an issue to have composer on your systems ?

The question should be: why am i forced to have composer installed, in a context in which i only want to run tests? 
This makes testing harder, adds dependencies and in the end makes it more complicated (why is called "simple-phpunit"?)

2. Is composer required only for making sure, that user has everything that's required installed?

3. Is there a really simple way to run tests without those steps?

**Comment by nicolas-grekas** [comment]
The reason is because the bridge builds a reconfigured phpunit to make its job. That's why there is the "install" command: so you can build it "offline".

**Comment by lukaszwit** [comment]
Thank you all for responses.
Your suggestions are ok but not in may case for now. I'm forced not to use phpunit bridge for now.
However I would suggest to put this in documentation in red flaming font that when you're requiring phpunit-bridge it will make 
`bin/phpunit`
file which is not **phpunit** but **simple-phpunit** script and makes documentation https://symfony.com/doc/current/components/phpunit_bridge.html (which stands that you can run simple php unit by `./vendor/bin/simple-phpunit`) **misleading**

**Comment by nicolas-grekas** [comment]
Doc PR welcome.
