### ISSUE TITLE
FOSUserBundle doesn't redirect to /logout on 3.4.10. 

### ISSUE THREAD

**Issue by Manalro** [symfony/symfony#27353]
I was using the 3.4.9 version of symfony, and my FOSUserBundle had a problem to redirect to /logout. I read the documentation and apparently the problem was due to my symfony version. They next said that the problem was resolved in the 3.4.10 version, so I upgraded mine to this latter, but still I have the same problem, FOSUserBundle is always unable to redirect to /logout. Can you please help ?

**Comment by Bonfante** [comment]
The route exists?
https://symfony.com/doc/current/security.html#logging-out

**Comment by xabbuh** [comment]
Without more information I am afraid we will not be able to help you. How can we reproduce the issue (best would be a small example project)? What is the error message (and stack trace) that you get?

**Comment by javiereguiluz** [comment]
@Manalro thanks for reporting this issue. A minor comment: please don't delete the given issue template when reporting an issue. That helps us a lot to review the issues. Thanks!

**Comment by axzx** [comment]
@Manalro do you use `switch_user`?
check `?_want_to_be_this_user=_exit` instead logout

**Comment by spyridonas** [comment]
@Manalro try to downgrade to 3.4.6. After the 3.4.6 version i can't get the auto redirect to login page working.

**Comment by Manalro** [comment]
@Bonfante yes the route exists, I've done as shown in the symfony docs but still the redirection doesn't work. @xabbuh I am using a 3.4.10 version of symfony, I've installed the FOSUserBundle for the users management of my project, but this latter is unable to redirect me to /logout. I can get to login my users but when I try to logout, I get the following error :  Unable to generate a URL for the named route "login" as such route does not exist.
Here's the stack trace :
`
RouteNotFoundException
--
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "login" as such route does not exist.    at var\cache\dev\appDevDebugProjectContainerUrlGenerator.php:56   at appDevDebugProjectContainerUrlGenerator->generate('login', array('_controller' => 'AppBundle\\Controller\\DefaultController::indexAction', '_route' => 'homepage', '_route_params' => array(), '_firewall_context' => 'security.firewall.map.context.main'), 0)      (var\cache\dev\classes.php:2106)   at Symfony\Component\Routing\Router->generate('login', array('_controller' => 'AppBundle\\Controller\\DefaultController::indexAction', '_route' => 'homepage', '_route_params' => array(), '_firewall_context' => 'security.firewall.map.context.main'), 0)      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\HttpUtils.php:151)   at Symfony\Component\Security\Http\HttpUtils->generateUri(object(Request), 'login')      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\HttpUtils.php:66)   at Symfony\Component\Security\Http\HttpUtils->createRedirectResponse(object(Request), 'login')      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\EntryPoint\FormAuthenticationEntryPoint.php:61)   at Symfony\Component\Security\Http\EntryPoint\FormAuthenticationEntryPoint->start(object(Request), object(InsufficientAuthenticationException))      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php:199)   at Symfony\Component\Security\Http\Firewall\ExceptionListener->startAuthentication(object(Request), object(InsufficientAuthenticationException))      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php:129)   at Symfony\Component\Security\Http\Firewall\ExceptionListener->handleAccessDeniedException(object(GetResponseForExceptionEvent), object(AccessDeniedException))      (vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php:94)   at Symfony\Component\Security\Http\Firewall\ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))   at call_user_func(array(object(ExceptionListener), 'onKernelException'), object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))      (vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php:104)   at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher))   at call_user_func(object(WrappedListener), object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher))      (var\cache\dev\classes.php:3714)   at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent))      (var\cache\dev\classes.php:3597)   at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))      (vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher.php:139)   at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))      (var\cache\dev\classes.php:4650)   at Symfony\Component\HttpKernel\HttpKernel->handleException(object(AccessDeniedException), object(Request), 1)      (var\cache\dev\classes.php:4582)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (web\app_dev.php:29)   at require('C:\\wamp64\\www\\webis-symfony\\web\\app_dev.php')      (vendor\symfony\symfony\src\Symfony\Bundle\WebServerBundle\Resources\router.php:42)
`
Here's a shortcut of my code : 
`
#security.yml
firewalls: 

main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout: 
                path:   /logout
                target: /      
            anonymous:    true
            # Use the default LDAP user provider defined above
            provider: ldap
            pattern: ^/
            logout: ~
            ldap_tools_form:
               check_path: login_check
               login_path: login
            # Using the LDAP Guard to authenticate the users...
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator

        login:
            pattern: ^/login$
            anonymous: ~`
`#routing.yml
app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
logout:
    path: /logout    
`
I have now succeeded to logout, by adding this to my routing file : 
`login: 
    path: /login ` 
But that wasn't mentioned anywhere in the symfony documentation, it is normally supposed to work without us having to add this path to our routing file. 
I'm glad it worked, but I'd like to know if what I've done is normal or correct ?

**Comment by xabbuh** [comment]
That's indeed expected, you are required to create the proper routes for the login (see https://symfony.com/doc/current/security/form_login_setup.html#create-the-correct-routes). So I am closing here as there is nothing to fix.
