### ISSUE TITLE
[DI] [BC] Building service locator with non-shared services fails

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#27360]
**Symfony version(s) affected**: 4.1.0-beta2

**Description**  
See https://travis-ci.org/omines/datatables-bundle/builds/382768680, build is failing only on 'dev', which is Symfony master branch. Following error occurs only in this build config:

> PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid ignore-on-uninitialized reference found in service ".2_ServiceLocator~i_rgpvA": target service "Omines\DataTablesBundle\Adapter\ArrayAdapter" is not shared. in /home/travis/build/omines/datatables-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:35

Same error also occurs when running tests in a real application with 4.1.0-beta2, but strangely not in its dev environment.

**How to reproduce**  
```
git clone git@github.com:omines/datatables-bundle.git reproducer
cd reproducer
composer config minimum-stability dev
composer update
vendor/bin/phpunit
```

**Comment by curry684** [comment]
Pinpointed issue down to https://github.com/symfony/symfony/blame/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/TestServiceContainerWeakRefPass.php#L35

This explains why I'm only seeing it during tests. This compiler pass makes a copy of the service with IGNORE_ON_INVALID_REFERENCE, violating its own rules in the later Invalid Reference Behavior check.

**Comment by stof** [comment]
@nicolas-grekas how should we handle non-shared services for this test container ?

**Comment by nicolas-grekas** [comment]
See #27364

**Comment by curry684** [comment]
If anyone else also got his CI/CD pipelines stuck waiting for this to be fixed, just add a compiler pass temporarily with:
```
    public function process(ContainerBuilder $container)
    {
        if ($container->has('test.service_container')) {
            $container->setAlias('test.service_container', 'service_container');
        }
    }
```

**Comment by stof** [comment]
@curry684 that won't give you access to the private services though

**Comment by curry684** [comment]
Wasn't using that feature yet anyway as it's a 4.1 exclusive   😉

**Comment by stof** [comment]
@curry684 `test.service_container` is also 4.1 exclusive :smile:

**Comment by curry684** [comment]
I had already upgraded my application to 4.1.0-beta2 to test it, but wasn't using the private service tester yet, as the tests kept crashing because of this bug before I could do so    😆

**Comment by curry684** [comment]
Confirmed fixed @ https://travis-ci.org/omines/datatables-bundle/jobs/382768689
