### ISSUE TITLE
Some Component files are "contaminated" with "?"s

### ISSUE THREAD

**Issue by wagnered** [symfony/symfony#27372]
Syphony 4.0, and 4.1.

The following files have "?"s pre-pending function parameter types (ie: function(?string $name)) and function return types in the following files:
1. Components/routing/route.php
2. Components/HttpFoundation/response.php.
3. Components/HttpFoundation/cookie.php
4. Components/HttpFoundationEdirectResponse.php
5. Components/HttpKernel/Exception/MethodNotAllowed.php
6. Components/Finder/NumberComparator.php
7. Components/HttpKernel/Exception/HttpException.php

I updated Laravel to 5.6 and it required Symphony 4.0, so the Composer packages probably needs rebuilt.

There may be more problem files but the above files were the ones that prevented me from working on the Ampache/Laravel project until I purged the "?"s from them. :smile:

**Comment by curry684** [comment]
Symfony 4 requires PHP 7.1 which supports optional parameters by prefixing them with ? signs.

**Comment by wagnered** [comment]
OK, Thanks... I got it.  my php-fpm was still version 7.0 for some reason.
