### ISSUE TITLE
Cannot call a static method on factory superseeded by magic overloads

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#27373]
**Symfony version(s) affected**: 3.3, at least

**Description**  
When making a factory to instantiate a service, if the called method does not exist in the class _but_ is supported by a `__call`, `__callStatic` method, the `AbstractRecursivePass` throws an exception saying that the method doesn't exist (cf https://github.com/symfony/dependency-injection/blob/3.3/Compiler/AbstractRecursivePass.php#L154-L156).

Using instead the factory call on `__callStatic` (or `__call`), with the first argument the method we want to call, and second argument an array of parameters, this works fine, but IMO this is kinda strange DX wise.

**How to reproduce**  
Have a static factory class, such as omnipay's entrypoint (https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay.php). Try the following :

```yaml
My\Service\Name:
    factory: 'Omnipay\Omnipay::create'
    arguments: ['%provider%']
```

To make it work, you have to do the following :

```yaml
My\Service\Name:
    factory: 'Omnipay\Omnipay::__callStatic'
    arguments: ['create', ['%provider%']]
```

**Possible Solution**  
Check if there is a `__callStatic` or `__call` method ?

**Comment by nicolas-grekas** [comment]
Having a magic call breaks autowiring. This should work if you disable autowiring for this service, isn't it?

**Comment by Taluu** [comment]
Not sure it has anything to do with autowiring ? Here is the exception trace...

```bash
$ php bin/console -vvv
In DefinitionErrorExceptionPass.php line 37:
                                                                                                
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                            
  Invalid service "Omnipay\Stripe\Gateway": method "Omnipay\Omnipay::create()" does not exist.  
                                                                                                
Exception trace:
 Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue() at /srv/api/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:60
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /srv/api/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:30
 Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue() at /srv/api/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:39
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at /srv/api/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /srv/api/vendor/symfony/dependency-injection/ContainerBuilder.php:732
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /srv/api/vendor/symfony/http-kernel/Kernel.php:513
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /srv/api/vendor/symfony/http-kernel/Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at /srv/api/vendor/symfony/framework-bundle/Console/Application.php:64
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/api/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /srv/api/bin/console:40
```

With the following config :

```yaml
Omnipay\Stripe\Gateway:
       factory: 'Omnipay\Omnipay::create'
       arguments: ['Stripe']
       calls:
         - method: setApiKey
           arguments:
             - '%env(STRIPE_API_KEY_TEST)%'
```

**Comment by nicolas-grekas** [comment]
> Not sure it has anything to do with autowiring ?

there are only two passes that populate the errors thrown by DefinitionErrorExceptionPass: ResolveBindingsPass or AutowirePass. It's one of them.

We could make `AbstractRecursivePass::getConstructor()` return null in this situation.
Would you like to give it a try?

**Comment by Taluu** [comment]
It is indeed configured to be autowired, but as it is a factory from another class (`Omnipay` here), it shouldn't really matter and just construct the service from the factory, no ? Unless I also have to disable the `Omnipay` service or something ? It is not meant to be a service, but a static call...

**Comment by nicolas-grekas** [comment]
Once you wite this config, you take responsibility for writing it in a way that works, another class or not doesn't matter. When you declare a factory, it becomes the constructor of the service.

I agree with @stof: we could improve the error message here.

**Comment by stof** [comment]
@Taluu autowiring works for factory-based services, wiring the arguments needed by the factory function. but for a magic call, it cannot wire these arguments (as it cannot determine what they are).

**Comment by Taluu** [comment]
Ok then, so it should either be documented and the error message could indeed use some modifications then. :}

**Comment by nicolas-grekas** [comment]
@Taluu up for a PR, doc and/or for the exception message?

**Comment by Taluu** [comment]
Not sure what I should put but I'll try in the week to do that

**Comment by Taluu** [comment]
I just added `autowire: false` on my service declaration, and it looks like it is still complaining that `Omnipay/Omnipay::create` doesn't exists. So this is not really a matter of autowiring.

**Comment by stof** [comment]
@Taluu do you have a small project reproducing the bug to help debugging ?

**Comment by Taluu** [comment]
It seems I can't reproduce it on a simple `skeleton` (the service and all are declared, with the correct methods call, ... and so on), but on my project, it doesn't seem to be the case :/

**Comment by xabbuh** [comment]
Is there anything we can do? Should we close until we have a clear vision of what is actually going wrong?

**Comment by xabbuh** [comment]
closing for now, please leave a comment when you were able to create a reproducible example

**Comment by blyxxyz** [comment]
I can reproduce this. I've put up an [example project](https://github.com/blyxxyz/symfony-di-magic-factory-method) (Symfony 4.2, but I originally ran into it on 3.4).

With [this class](https://github.com/blyxxyz/symfony-di-magic-factory-method/blob/master/src/SomeServiceProvider.php):
```php
namespace App;

/**
 * @method \DateTime magicFactoryMethod
 */
class SomeServiceProvider
{
    public function ordinaryFactoryMethod(): \DateTime
    {
        return new \DateTime();
    }

    public function __call($name, $arguments)
    {
        if ($name === 'magicFactoryMethod') {
            return new \DateTime();
        }
        throw new \Exception("Unknown method '$name'");
    }
}
```

And [this service](https://github.com/blyxxyz/symfony-di-magic-factory-method/blob/master/config/services.yaml#L34):

```yaml
    example.broken:
        class: DateTime
        factory: App\SomeServiceProvider:magicFactoryMethod
        arguments: []
        public: true
```

There is an error message `Invalid service "example.broken": method "App\SomeServiceProvider::magicFactoryMethod()" does not exist.`.

[This way](https://github.com/blyxxyz/symfony-di-magic-factory-method/blob/master/config/services.yaml#L40) works:

```yaml
    example.fixed:
        class: DateTime
        factory: App\SomeServiceProvider:__call
        arguments: [magicFactoryMethod, []]
        public: true
```

A different error message if the factory defines `__call`/`__callStatic` would be helpful. I don't know if suggesting this particular workaround would be reasonable.

**Comment by stof** [comment]
Well, your service is marked as autowired there (through file-level defaults). Does it still break if you disable it for this service ? Autowiring a magic method is not expected to work.

**Comment by blyxxyz** [comment]
Adding `autowire: false` fixes it. That's certainly the right solution here. It just clicked for me, thank you.
