### ISSUE TITLE
[DI] Improve container logs when service inlined/removed

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#27386]
**Description**  
Currently when a service is inlined in anoter service you get a log message like

> Inlined service "abc" to "xyz".

And at the same time you also get a log message that the service got removed

> Removed service "abc"; reason: unused.

IMO when it a service is inlined, it should not also log that it got removed.
This way you can actually find services that are unused. Currently you get alot of duplicate messages for inlined services. And the reason "unused" is even more irritating as it is not really unused, it was just inlined because it's only used once.

Another improvement can be made for the autowire pass. When an object argument has a default value that cannot be wired, it does not error but logs a message like

> Symfony\Component\DependencyInjection\Compiler\AutowirePass
> Cannot autowire service "Ekino\NewRelicBundle\Listener\ResponseListener": argument "$newRelicTwigExtension" of method "__construct()" references class "Ekino\NewRelicBundle\Twig\NewRelicExtension" but no such service exists.

This is good. But for consistency and debugging purposes, it would be good if a scalar argument that has a default value that wasn't wired explicitly, also triggers a log. You might have just forgotten to wire it with a parameter for example and that is hard to spot.

**Comment by stof** [comment]
that might be hard to change though, as the container cleaning is a multi-pass processing (we repeat it until a pass becomes a no-op), and it would require remember whether a previous pass was inlining it or no).

**Comment by nicolas-grekas** [comment]
A way to do this could be to give the inlining pass the responsibility to remove the definitions it left unreferenced.

**Comment by nicolas-grekas** [comment]
Another could be for the inlining pass to add a tag on the definition (e.g. `container.inlined`) that would tell the removing pass to not log when found.
@Tobion would you like to submit a PR ?
