### ISSUE TITLE
Turn of translation warnings (logs?) from configuration

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony#27381]
I think it would be quite useful to get rid of translation warnings from configuration. As a use case, think about a situation where an application is not localized at all but use bundles that provides translations. Let's pretend that this bundle has missing translations. In this situation I can't just turn off translations as bundle will possibly fall back in a locale that I don't want to use and in the meantime I don't want to see all those warning messages in development. In my case I'm migrating a symfony application from LTS to next major version and I'm forced everytime to check what toolbar "errors/warning/deprecations" are about. 

This is the code

```
private function log($id, $domain, $locale)
{
  if (null === $domain) {
    $domain = 'messages';
  }

  $id = (string) $id;
  $catalogue = $this->translator->getCatalogue($locale);
  if ($catalogue->defines($id, $domain)) {
    return;
  }

  if ($catalogue->has($id, $domain)) {
    $this->logger->debug('Translation use fallback catalogue.', array('id' => $id, 'domain' => $domain, 'locale' => $catalogue->getLocale()));
  } else {
    $this->logger->warning('Translation not found.', array('id' => $id, 'domain' => $domain, 'locale' => $catalogue->getLocale()));
  }
}
```

that could be simply changed in

```
private $logTrans;

public function __construct(TranslatorInterface $translator, LoggerInterface $logger, bool $logTrans)
{
  [...]
  $this->logTrans = $logTrans;
}

[...]

private function log($id, $domain, $locale)
{
  if (!$this->logTrans) {
    return;
  } 
  [...]
}
```

For BC reasons this will be `true` by default and can be changed anytime in the config file (so we need also to add some configuration to the bundle that I won't report here as are pretty standard).

WDYT? If it's a feature we're interested in, I could try to implement that.

**Comment by sstok** [comment]
Can't you pass a NullLogger to the constructor? Or configure the translation channel to not log anything (blackhole).

**Comment by DonCallisto** [comment]
Yes, that's true, maybe I can configure a channel only for this purpose. 
Nevermind and thanks for the idea.

**Comment by stof** [comment]
you can also disable logging missing translations from the config: http://symfony.com/doc/current/reference/configuration/framework.html#logging

**Comment by DonCallisto** [comment]
Cool!
