### ISSUE TITLE
[Routing] Route does not match with requirements for second parameter when the first one contains dash

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#27392]
**Symfony version(s) affected**: 4.0.11 / 4.1.0-BETA3

**Description**  
When having following URL `/product/my-super-cool-product-11` (where the number in the end is `productId`) the following route does not match:

```
@Route(
    "/product/{productSlug}-{productId}/",
    methods={"GET"},
    name="product_detail",
    requirements={
        "productId"="\d+"
    }
)
```

I discovered that it is because the dash is excluded from the `productSlug`:

```php
// in the var/cache/dev/srcDevDebugProjectContainerUrlMatcher.php
'|/product/([^/\\-]++)\\-(\\d+)/(*:537)'
```

I manually specified the pattern for the `productSlug` as a temporary workaround:
```
@Route(
    "/product/{productSlug}-{productId}/",
    methods={"GET"},
    name="product_detail",
    requirements={
        "productSlug"="[\-0-9a-z]+",
        "productId"="\d+"
    }
)
```

Which generates a working regex:
```
'|/tour/([\\-0-9a-z]+)\\-(\\d+)/(*:540)'
```

Now I got more time to dive into the issue and I have created following tests which can be copied into `routing/Tests/Matcher/UrlMatcherTest.php`:

1. `testMatchWithSlugAndNumericIdSeparatedByDash` reproduces the issue
2. `testMatchWithSlugAndNumericIdSeparatedByDashAndPatternForSlug` confirms that the workaround with manually specified pattern works
3. `testMatchWithNumericIdAndSlugSeparatedByDash` shows that it actually works when the numeric id is first and the slug is second in the URL (it generates `'|/product/(\\d+)\\-([^/]++)/(*:535)'`)

```php

    public function testMatchWithSlugAndNumericIdSeparatedByDash()
    {
        $collection = new RouteCollection();
        $collection->add('foo', new Route('/bar/{foo}-{fooId}', array(), array(
            'fooId' => '\d+',
        )));

        $matcher = $this->getUrlMatcher($collection);
        $this->assertEquals(array(
            '_route' => 'foo',
            'foo' => 'my-cool-product',
            'fooId' => 11
        ), $matcher->match('/bar/my-cool-product-11'));
    }

    public function testMatchWithSlugAndNumericIdSeparatedByDashAndPatternForSlug()
    {
        $collection = new RouteCollection();
        $collection->add('foo', new Route('/bar/{foo}-{fooId}', array(), array(
            'foo' => '[\-0-9a-z]+',
            'fooId' => '\d+',
        )));

        $matcher = $this->getUrlMatcher($collection);
        $this->assertEquals(array(
            '_route' => 'foo',
            'foo' => 'my-cool-product',
            'fooId' => 11
        ), $matcher->match('/bar/my-cool-product-11'));
    }

    public function testMatchWithNumericIdAndSlugSeparatedByDash()
    {
        $collection = new RouteCollection();
        $collection->add('foo', new Route('/bar/{fooId}-{foo}', array(), array(
            'fooId' => '\d+',
        )));

        $matcher = $this->getUrlMatcher($collection);
        $this->assertEquals(array(
            '_route' => 'foo',
            'foo' => 'my-cool-product',
            'fooId' => 11
        ), $matcher->match('/bar/11-my-cool-product'));
    }


```

**Comment by nicolas-grekas** [comment]
Actually that's the expected behavior: any placeholder followed by a separator is exclude from containing said separator. See 
https://github.com/symfony/symfony/blob/f557f943babf2893442ceb240521ef1bde785c50/src/Symfony/Component/Routing/RouteCompiler.php#L29 for the list of separators.

**Comment by Tobion** [comment]
One purpose is to be able to use possessive quantifiers `++` making matching faster by preventing backtracking. But as you found out yourself, you can still overwrite the default requirement if it's too restrictive.

**Comment by mhujer** [comment]
@nicolas-grekas @Tobion Thank you very much for the explanation! 👍
