### ISSUE TITLE
RememberMe cookies are invalid with eraseCredentials()

### ISSUE THREAD

**Issue by Ne-Lexa** [symfony/symfony#27391]
**Symfony version(s) affected**: 4.0.11 and below

**Description**  
`RememberMe` cookies do not pass hmac checking, if in the `UserInterface::eraseCredentials()` method, remove the password.

**How to reproduce**  
```php
use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    ...
    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        $this->password = null;
    }
    ...
}
```
Next, log in with "Remember me".
In the method `\Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices::generateCookieHash()` the password comes as `null`.
```php
protected function generateCookieHash($class = 'App\Entity\User', $username = 'AcmeUser', $expires = 1542908680, $password = null)
{
    return hash_hmac('sha256', $class.$username.$expires.$password, $this->getSecret());
}
```
If you delete the session cookie and refresh the page, then when `$rememberMeServices->autoLogin()`, the password will no longer be `null`, and the token will be invalid, which will cause the user to logout.
```php
protected function generateCookieHash($class = 'App\Entity\User', $username = 'AcmeUser', $expires = 1542908680, $password = 'Pa$$w0rD')
{
    return hash_hmac('sha256', $class.$username.$expires.$password, $this->getSecret());
}
```

**Comment by xabbuh** [comment]
This looks like a mistake in your `User` class. The hashing algorithm uses the return value of the `getPassword()` method. This method must return the hashed (encoded) password of the user. On the contrary, `eraseCredentials()` is not supposed to remove the hashed password from the user, but must only remove a plaintext password if that was stored inside the user object during login. I am going to close here as there is nothing to fix.
