### ISSUE TITLE
TagAwareAdapter over nonbinary memcached connections corrupts memcache.

### ISSUE THREAD

**Issue by palex-fpt** [symfony/symfony#27405]
**Symfony version(s) affected**: 4.0.0

**Description**  
TagAwareAdapter over nonbinary memcached connections corrupts memcache.

**How to reproduce**  
```
	public function testTagAwareAdapterOverMemcached()
	{
		$nonbinaryMemcached = new \Memcached();
		$nonbinaryMemcached->addServer('memcached', 11211);
		$nonbinaryMemcached->setOption(\Memcached::OPT_BINARY_PROTOCOL, false);
		$simpleCache = new MemcachedAdapter($nonbinaryMemcached);
		$tagAwareCache = new TagAwareAdapter($simpleCache);

		$simpleCache->save($simpleCache->getItem("simple")->set(1));

		// TagAwareAdapter corrupts nonbinary memcached
		$tagAwareCache->save($tagAwareCache->getItem("tagged")->set(1));

		$this->assertEquals(1, $simpleCache->getItem("simple")->get());
	}
```

**Possible Solution**  
TagAwareAdapter uses '\0' in key names, that are incompatible with memcached in normal mode. Possible solution is to change key prefix.

**Comment by nicolas-grekas** [comment]
Yes, that's expected: non binary protocol is too loose, just turn it one.

**Comment by palex-fpt** [comment]
Actually we use [mcrouter](https://github.com/facebook/mcrouter) to balance memcache servers. It does not support binary protocol. It was surprise when cache starts randomly returns null values. Should it be mentioned in docs?

**Comment by nicolas-grekas** [comment]
Hum, it could make sense actually to make it work in no-binary mode. We'd need to encode the keys using `rawurlencode()` I suppose. Would you like to give it a try?

**Comment by palex-fpt** [comment]
ok. i'll try
