### ISSUE TITLE
Problem to create a Collection of Forms

### ISSUE THREAD

**Issue by Anouchka25** [symfony/symfony#27407]
**Symfony version(s) affected**: 4.0.0

**Description**  
I would like create a Collection of Forms. I looked this tuto: [http://symfony.com/doc/current/form/form_collections.html](url)
It don't work, i don't understand all code, my code is not work. Help me please !
This is error that i have : 

> Expected argument of type "array or (\Traversable and \ArrayAccess)", "string" given

Those my entities : Facture.php and Prestation.php
Each Facture belongs to multiple Prestation objects

Please i put link where can you look at my code : [https://github.com/Anouchka25/monsymfony](url)

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
