### ISSUE TITLE
[Translation] [BUG?] TransChoice invalide plural translation

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony#27401]
**Symfony version(s) affected**: 2.7+

**Description**  
TransChoice invalide plural translation
see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/MessageSelector.php#L81

**How to reproduce**  
Try to transchoice a failed plural translation (with missing portion)

**Possible Solution**  
Replace exception by critical/error log?

**Additional context**  
The context is that we may have non tech users that translate those translations (eg: web based GUI, software, etc) and they can make some human errors.
Then we extract those data to inject them into our application
We do have some tools to check the translation format etc, but this one is particular
and it should (must?) be non critical for production IMO

What do you think?
Does this ex have been coded on purpose?
Does symfony dev implements an ex listener to catch this very specific error to handle it?

May thanks

**Comment by noniagriconomie** [comment]
ping @xabbuh @aitboudad

**Comment by xabbuh** [comment]
We may want to make this configurable in that it fails during development, but is silent in production which would be in line by the default behaviour of Twig in a Symfony application.

**Comment by noniagriconomie** [comment]
@xabbuh what do you mean by configurable?

either logging in prod or throwing in dev?
If I open a PR it will be considered as bug fix or feature?
we are now on 3.4 LTS

thank you

**Comment by xabbuh** [comment]
We could inject a flag which would be set to the value of the `kernel.debug` parameter when the FrameworkBundle wires the service. But I think that would be a new feature (so for Symfony 4.2+).

**Comment by noniagriconomie** [comment]
@xabbuh oki I see, but as I said we are on LTS 3.4, imposible to upgrade to 4.X
what do you suggest to handle this ex properly?

thank you

**Comment by noniagriconomie** [comment]
@xabbuh friendly ping, no way to propose this for 3.4 ? as an LTS, and i really think this is a bug

**Comment by nicolas-grekas** [comment]
There is nothing to expose as nobody sent a PR implementing what @xabbuh suggested ;)
Then sorry but that's a new feature, so for master only.

**Comment by noniagriconomie** [comment]
@nicolas-grekas ok, will try to do it then, event if for 4.x

**Comment by Simperfit** [comment]
PR has been done, since it has changed alot since the issue, could you please confirm that the implementation is linked to what you had in mind @xabbuh ?

**Comment by noniagriconomie** [comment]
For my part it is ok
Many thank
