### ISSUE TITLE
anyAttribute support in routing.xsd

### ISSUE THREAD

**Issue by vbartusevicius** [symfony/symfony#27408]
**Description**  
Currenty it is practically impossible to extend `routing.xml` due to restrictions in `routing.xsd`

**Example**  
```xml
<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:vnd="custom-vendor.xsd"
    xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">
    <route id="my_bundle.route_name" path="/category/{categoryId}">
        <default key="_controller">my_bundle.controller.category:someMethod</default>
       <vnd:my-attribute>something here</psr:api>
    </route>
```
Imagine we want to define custom logic how `categoryId` is mapped to Entity or how other things related to Request/Response are handled here. Allowing `anyAttribute` here would allow developers to recongize and configure some advanced logic they want without braking current functionality. 

Currently developers are finding ways how to work-around this, in example:
* `FOSJsRoutingBundle` uses `<option key="expose">true</option>` to mark route available in Javascript;
* `FOSRestBundle` uses `type: rest` to mark resource as `rest`

Doctrine has this in their `doctrine-mapping.xml`: https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd - allows any attribute and any property.

I could provide PR to `routing.xsd` if this feature would be considered as useful.

**Comment by nicolas-grekas** [comment]
What would be the downside of doing this? e.g. could it make harder to spot some mistakes?
Feel free to provide a PR of course.

**Comment by Simperfit** [comment]
@vbartusevicius do you want to work on this ?

**Comment by fabpot** [comment]
Using `options`s is the way to go. Allowing anything means that validation would be less effective.
