### ISSUE TITLE
Exclude Some Vendors From Being Hidden

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#27409]
**Description**  
#26671 reduced clutter while looking at exceptions, however made working with internal-vendor stuff harder. In larger projects it's not uncommon to have private packages and use them in the project. It's very useful to actually see them in stack traces.

**Ideal solution**
When vendor part of PSR-4 namespace matches current project namespace code should be treated as belonging to the project..

**Simple solution**
Maybe we can add configurable whitelist for vendors based on `vendor/[directory]` which should be ignored while deciding on the code being vendor vs. non-vendor?

ping @javiereguiluz

**Comment by fabpot** [comment]
I'm closing this issue as it didn't gain any traction.
