### ISSUE TITLE
./bin/phpunit No such file or directory

### ISSUE THREAD

**Issue by nguyenthaialan** [symfony/symfony#27411]
![image](https://user-images.githubusercontent.com/7870291/40682383-db6b4f72-638b-11e8-89a7-c2f16c82abda.png)

**Comment by xabbuh** [comment]
Please provide more information about which steps you did and why you think the current behaviour is a bug under these circumstances.

**Comment by spyridonas** [comment]
try ./bin/simple-phpunit but you will need symfony/phpunit-bridge installed

**Comment by javiereguiluz** [comment]
To give more context, as explained in https://symfony.com/doc/current/testing.html, the `./bin/phpunit` only works if these two conditions are met:

1) Your app uses Symfony Flex (which internally installs the PhpUnitBridge recipe)
2) You run `composer require --dev symfony/phpunit-bridge` or `composer require --dev symfony/test-pack` to add support for tests in the app

**Comment by nicolas-grekas** [comment]
here, it looks like the"php" binary is not in the path

**Comment by nicolas-grekas** [comment]
I'm closing because this is not a bug, please use https://symfony.com/support if you need further assistance.
