### ISSUE TITLE
Making `ExtensionInterface`s extending `\Throwable` is a BC break

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony#27419]
**Symfony version(s) affected**: 4.1

**Description**
#26702 introduces an annoying BC break:
when using Prophecy, it's not possible to prohesize our interfaces anymore.

**How to reproduce**  

        $serializerException = $this->prophesize(ExceptionInterface::class);
        $serializerException->willExtend(\Exception::class);

        $serializerException->reveal();

Was working before, now throws `Prophecy\Exception\Doubler\MethodNotExtendableException: Method `getMessage` is not extendable, so can not be added.`

**Possible Solution**  
Reverting #26702. (I'm trying to figure another solution).

**Comment by nicolas-grekas** [comment]
#26702 should be reverted for sure.

**Comment by curry684** [comment]
It's even formally illegal, ref http://php.net/manual/en/class.throwable.php

> PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.

**Comment by stof** [comment]
@curry684 but that does not mean you cannot have an interface extending it. `Traversable` already works that way. It only means that classes which want to implement this interface must extend Exception or Error (like classes implementing an interface extending `Traversable` must implement either `Iterator` or `IteratorAggregate`)

**Comment by teohhanhui** [comment]
I don't see how it's a BC break, to be honest. The methods on `\Throwable` are exactly the same as `\Exception`, which any sane implementation would be based on anyway.

**Comment by teohhanhui** [comment]
Maybe it could be merged again after the issue with Prophecy is fixed?

**Comment by dkarlovi** [comment]
It seems like a bug in Prophecy, here's the WIP PR: https://github.com/phpspec/prophecy/pull/412

**Comment by Wirone** [comment]
@nicolas-grekas @fabpot Do you consider re-merging #26702 ? It actually looks like a bug not related to Symfony and `\Throwable`.

**Comment by dunglas** [comment]
With Symfony 4.2 and the latest version of Prophecy (1.8.0) this issue came back...
ping @ciaranmcnulty @ostrolucky

**Comment by dunglas** [comment]
Some details after more tests:

Still fail:
```php
    $serializerException = $this->prophesize(ExceptionInterface::class);
    $serializerException->willExtend(\Symfony\Component\Serializer\Exception\ExceptionInterface::class);

    $serializerException->reveal();
```

Works:

```php
    $serializerException = $this->prophesize(\Symfony\Component\Serializer\Exception\ExceptionInterface::class);

    $serializerException->reveal();
```

**Comment by stof** [comment]
@dunglas please report it to Prophecy

**Comment by dkarlovi** [comment]
This looks like a Prophecy regression, yes.

**Comment by ciaranmcnulty** [comment]
@dunglas can you report that example on prophecy, ideally with namespaces attached?

**Comment by ciaranmcnulty** [comment]
@ostrolucky that issue was fixed with a test that covers the case. If there’s a different case triggered in symfony someone needs to report it :-)

**Comment by ostrolucky** [comment]
Nope, patch covers `$this->prophesize('Throwable')->reveal()` instead of `$this->prophesize('Throwable')->willExtend('Exception')->reveal()` as was reported in https://github.com/phpspec/prophecy/issues/410 and here

**Comment by pierredup** [comment]
```
$this->prophesize('Throwable')->willExtend('Exception')->reveal()
```

doesn't look quite right, since `Throwable` shouldn't extend `Exception`.
Should it not rather be
```
$this->prophesize('CustomExceptionInterface')->willExtend('Throwable')->reveal()
// or
$this->prophesize('CustomExceptionInterface')->willExtend('Exception')->reveal()
```
?

**Comment by teohhanhui** [comment]
@pierredup

```php
$this->prophesize('Throwable')->willExtend('Exception');
```

This does not mean that `Throwable` extends `Exception`. What it says is: mock a `Throwable`, but it should also extend `Exception`. And that's perfectly valid.
