### ISSUE TITLE
Why Monolog processor are not used to fill the LoggerDataCollector

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#27426]
**Description**  
I have many processor in my application, and some of them are really useful, like castring to string a PSR7/Request (the body is a stream).

**Example**  
ATM, I only see that 
![image](https://user-images.githubusercontent.com/408368/40725031-b46f1786-6422-11e8-9b10-863e0837e737.png)

Because my processor in not plugged in the stack that collect all logs.

in others logs handlers (filesystem / ...) the processor is well enabled and called.

**Question**
Why Monolog processor are not used to fill the LoggerDataCollector ?

**Comment by stof** [comment]
are you registering your processors on specific handlers only, or at the logger level ?

for handler-level processors, they are indeed not applied to the data collector (unless you register it on the debug handler too explicitly). But for logger-level processors, I think it is supposed to work.

**Comment by lyrixx** [comment]
They are just tagged so it's at the logger level.
I did not look at the code yet. Imho I should be easy to fix

**Comment by Simperfit** [comment]
@lyrixx do you want to work on a fix so we can move forward with this ?

**Comment by lyrixx** [comment]
@Simperfit This si just a question. I think there is no valid reason to not wire them.
So I will submit a PR asap :)

**Comment by lyrixx** [comment]
Fixed by #31509
