### ISSUE TITLE
[4.1] The "parameter_bag" service is not available.

### ISSUE THREAD

**Issue by emulienfou** [symfony/symfony#27436]
**Symfony version(s) affected**: 4.1.0

**Description**  
Since updated to Symfony 4.1, I switch to use `AbstractController` instead of `Controller` class, as suggested!

However, I receive now the **LogicExtension**: `The "parameter_bag" service is not available. Try running "composer require dependency-injection:^4.1"`.

It seems the the service `parameter_bag` is not public and cannot be acceded!

Using the debug command: `php bin/console debug:container parameter_bag`
```bash
Information for Service "parameter_bag"
=======================================

 ---------------- ----------------------------------------------------------------- 
  Option           Value                                                            
 ---------------- ----------------------------------------------------------------- 
  Service ID       parameter_bag                                                    
  Class            Symfony\Component\DependencyInjection\ParameterBag\ContainerBag  
  Tags             -                                                                
  Public           no                                                               
  Synthetic        no                                                               
  Lazy             no                                                               
  Shared           yes                                                              
  Abstract         no                                                               
  Autowired        no                                                               
  Autoconfigured   no                                                               
 ---------------- ----------------------------------------------------------------- 
```

**How to reproduce**  
```php
class TestController extends AbstractController
{
    public function index()
    {
       // ...
       $variable = $this->getParameter('service_name');
       // ...
    }
}
```

**Possible Solution**  
In the file: `framework-bundle/Resources/config/services.xml`

Change:
```xml
<service id="parameter_bag" class="Symfony\Component\DependencyInjection\ParameterBag\ContainerBag">
        <argument type="service" id="service_container" />
</service>
```
By:
```xml
<service id="parameter_bag" class="Symfony\Component\DependencyInjection\ParameterBag\ContainerBag" public="true">
        <argument type="service" id="service_container" />
 </service>
```

To make the service has `public` seems to resolve the issue!

**Comment by curry684** [comment]
The service doesn't have to be public as the AbstractController injects it in a private service locator. Does the problem occur again if you change it back to private now? You may have just into a caching issue.

**Comment by emulienfou** [comment]
I already try that, if I put the service back to private the problem is not occurring.   
However when I clear my cache the problem occur again! So there is an issue for me

**Comment by curry684** [comment]
Can you share the output of `composer show | grep symfony`?

If on a Windows system just run `composer show` and copy/paste all lines beginning with `symfony`.

**Comment by emulienfou** [comment]
```
symfony/asset                       v4.1.0               Symfony Asset Component
symfony/cache                       v4.1.0               Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.1.0               Symfony Config Component
symfony/console                     v4.1.0               Symfony Console Component
symfony/debug                       v4.1.0               Symfony Debug Component
symfony/dependency-injection        v4.1.0               Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.1.0               Symfony Doctrine Bridge
symfony/dotenv                      v4.1.0               Registers environment variables from a .env file
symfony/event-dispatcher            v4.1.0               Symfony EventDispatcher Component
symfony/filesystem                  v4.1.0               Symfony Filesystem Component
symfony/finder                      v4.1.0               Symfony Finder Component
symfony/flex                        v1.0.80             
symfony/form                        v4.1.0               Symfony Form Component
symfony/framework-bundle            v4.1.0               Symfony FrameworkBundle
symfony/http-foundation             v4.1.0               Symfony HttpFoundation Component
symfony/http-kernel                 v4.1.0               Symfony HttpKernel Component
symfony/inflector                   v4.1.0               Symfony Inflector Component
symfony/intl                        v4.1.0               A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lts                         dev-master 6de50b2   Enforces Long Term Supported versions of Symfony components
symfony/maker-bundle                v1.5.0               Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge              v4.1.0               Symfony Monolog Bridge
symfony/monolog-bundle              v3.2.0               Symfony MonologBundle
symfony/options-resolver            v4.1.0               Symfony OptionsResolver Component
symfony/polyfill-ctype              v1.8.0               Symfony polyfill for ctype functions
symfony/polyfill-intl-icu           v1.8.0               Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.8.0               Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.8.0               Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/profiler-pack               v1.0.3               A pack for the Symfony web profiler
symfony/property-access             v4.1.0               Symfony PropertyAccess Component
symfony/routing                     v4.1.0               Symfony Routing Component
symfony/security                    v4.1.0               Symfony Security Component
symfony/security-bundle             v4.1.0               Symfony SecurityBundle
symfony/serializer                  v4.1.0               Symfony Serializer Component
symfony/stopwatch                   v4.1.0               Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.2               Symfony SwiftmailerBundle
symfony/templating                  v4.1.0               Symfony Templating Component
symfony/translation                 v4.1.0               Symfony Translation Component
symfony/twig-bridge                 v4.1.0               Symfony Twig Bridge
symfony/twig-bundle                 v4.1.0               Symfony TwigBundle
symfony/validator                   v4.1.0               Symfony Validator Component
symfony/var-dumper                  v4.1.0               Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle         v4.1.0               Symfony WebProfilerBundle
symfony/webpack-encore-pack         v1.0.2               A pack for Symfony Encore
symfony/yaml                        v4.1.0               Symfony Yaml Component
```

**Comment by curry684** [comment]
Ok that should all be fine. I cannot reproduce your issue however. I suspect in migrating from `Controller` to `AbstractController` you didn't clean up the config correctly. The issue you describe would occur if you are manually injecting `@service_container` in your controller and storing it in `$this->container`, thereby hiding the locator. This would show if `dump(get_class($this->container));` in the controller would show anything other than `ServiceLocator`.

Would it be possible for you to [create a reproducer](http://symfony.com/doc/current/contributing/code/reproducer.html)?

**Comment by emulienfou** [comment]
Trying to reproduce the issue, but not so simple.
However when I do `var_dump(get_class($this->container));`

- I got: `Symfony\Component\DependencyInjection\ServiceLocator` from the skeleton,
- However, I got `Container9Izl7V4\srcDevDebugProjectContainer` in my project.

**Comment by emulienfou** [comment]
Hi there, I create a reproducer here: https://github.com/emulienfou/symfony_issue_27436   
I successfully reproduce the bug.

The issue is when trying to access to the **ParameterBag** service, using `$this->container->has('parameter_bag')` directly from a controller in a Symfony project, it's working perfectly.

However, if you are trying to do the same in a bundle, the **ParameterBag** service seems to be not available.

You can try my reproducer by accessing directly to: [http://issue_27436.symfony:9999](http://issue_27436.symfony:9999) using my docker configuration to the App controller. It will display `true`.   
You can also access to: [http://issue_27436.symfony:9999/issue](http://issue_27436.symfony:9999/issue) to display the response of the same code: `false`

**Comment by ogizanagi** [comment]
@emulienfou : The issue is that your bundle controller is not manually wired, nor autowired nor autoconfigured, so `ServiceSubscriberInterface` is not detected and corresponding tag not added. Hence service locator is not injected. Your bundle misses wiring the controller properly.

**Comment by curry684** [comment]
Although this indeed makes it not a bug I'm surprised `AbstractController` then gets the full container indeed by default instead of erroring out, there is definitely a DX issue there methinks.

**Comment by ogizanagi** [comment]
That's because of https://github.com/symfony/symfony/blob/59375662a3d7f020abc31b673ccbe2b76dbba7b7/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L62-L64

I don't remember what motivated this.

**Comment by ogizanagi** [comment]
Some explanations in https://github.com/symfony/symfony/pull/22157/files#r108040463

**Comment by curry684** [comment]
Hmm ok the reasoning there is not unfair, but the result seen in this issue is most unfortunate and I understand the confusion.

@weaverryan @nicolas-grekas what's your opinion on this?

**Comment by nicolas-grekas** [comment]
My opinion is that the core issue is a bad configuration, it needs to be fixed there :)
And the exception message also should be changed, "Try running "composer require dependency-injection:^4.1"" is odd

**Comment by curry684** [comment]
Yeah no contest that it's a configuration issue, just pointing out the DX sucks if you run into this situation. First of all we could actually detect DI being installed at runtime before throwing the current exception, and then fix both by changing the alternative exception to something like *"The parameter_bag service could not be located. Ensure that the controller is either set to be autoconfigured or wire it up manually"*.

**Comment by nicolas-grekas** [comment]
Yep. PR welcome :)
About DI, it is always installed, but not necessarily at v4.1, that's what the current message is about (but is wrong in this case, so yes, more logic is needed here to provide an accurate message)

**Comment by nicolas-grekas** [comment]
PR to improve the message is #27443, more reviews welcome.

**Comment by curry684** [comment]
@emulienfou you should also add `autoconfigure: true`

Autowire = try to automatically inject right services based on typehints
Autoconfigure = try to automatically add behaviors to service based on common interfaces or base classes

In this case the autoconfigure is required to pick up the `ServiceSubscriberInterface` which injects a bunch of services (like `parameter_bag` via a much smaller and more performant ServiceLocator rather than the entire container as it was before.

Also see https://symfony.com/blog/new-in-symfony-3-3-service-autoconfiguration

**Comment by emulienfou** [comment]
After adding the `autoconfigure: true`, I've got an other exception:
**Service "dcs_rating.manager.rating" not found: even though it exists in the app's container, the container inside "App\Issue27436Bundle\Controller\Issue27436Controller" is a smaller service locator that only knows about the "doctrine", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "session" and "twig" services. Unless you need extra laziness, try using dependency injection instead. Otherwise, you need to declare it using "Issue27436Controller::getSubscribedServices()".**

I just update my reproducer code: https://github.com/emulienfou/symfony_issue_27436

**Comment by curry684** [comment]
That error has no lack of DX at all and explicitly tells you how to fix it.
