### ISSUE TITLE
index.php could also check for $_ENV

### ISSUE THREAD

**Issue by tavlima** [symfony/symfony#27433]
**Description** 
Given [this](https://bugs.php.net/bug.php?id=67808) PHP bug report (and the comments on it), couldn't the generated `index.php` [1] also check for the existence of the environment variables (`APP_ENV`, `APP_DEBUG`, etc) not only in the global `$_SERVER`, but also in `$_ENV`?

If doing that for all web servers quickly becomes a security vulnerability (haven't really thought this through), at least we could have allowances for the PHP Development Server (detected by `$_SERVER['SERVER_SOFTWARE']`, perhaps?)

[1] https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/public/index.php

**Comment by Tobion** [comment]
As you linked the relevant piece of code yourself, please open the issue in https://github.com/symfony/recipes/issues Thanks.
It would also help to write what you are trying to solve in the ticket. I guess supporting env variables passed in the built-in webserver? But for what purpose? That is what the .env file is for.
