### ISSUE TITLE
Documentation about `ClassDiscriminatorResolver` unclear

### ISSUE THREAD

**Issue by thasmo** [symfony/symfony#27451]
**Symfony version(s) affected**: 4.1

**Description**  
[Documentation](https://symfony.com/doc/master/components/serializer.html#serializing-interfaces-and-abstract-classes) mentions the use of `ClassDiscriminatorResolver` which is absent from Symfony 4.1 so either the docs need an update or `ClassDiscriminatorResolver` is missing from Symfony 4.1.

**Comment by Tobion** [comment]
https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Serializer/Mapping/ClassDiscriminatorResolverInterface.php 
The api docs seems to be outdated as those classes are missing: https://api.symfony.com/4.1/Symfony/Component/Serializer/Mapping.html

**Comment by sroze** [comment]
@thasmo fancy sending a pull-request on the documentation to refers to the interface ( `ClassDiscriminatorResolverInterface`) instead? We'll see in the core team how we can fix the issue that the file don't exists (but should).

**Comment by sroze** [comment]
Documentation PR is here: https://github.com/symfony/symfony-docs/pull/9873
The missing classes in the API documentation will be handled by @fabpot :)
