### ISSUE TITLE
The configuration tree has no root node  (symfony 4.1)

### ISSUE THREAD

**Issue by N-M** [symfony/symfony#27450]
**Symfony version(s) affected**: 4.1 (Without Flex)

**Description**  

After update from 4.0.11 to 4.1 error ```The configuration tree has no root node.``` is presented. Issue is mentioned in comment https://symfony.com/blog/symfony-4-1-0-released#comment-22501
**How to reproduce**  

Update non flex symfony app to 4.1 with bundle without root node.

**Additional context**  

![screen shot 2018-05-31 at 5 18 27 pm](https://user-images.githubusercontent.com/781417/40791006-b1719ade-64f6-11e8-9163-f2032ce1730b.png)

**Comment by ro0NL** [comment]
Ill check this asap :)

**Comment by N-M** [comment]
I have made example application where you can reproduce the issue.
Branch below is where you can reproduce it and master branch is code with symfony 4.0.11 that works
[https://github.com/N-M/symfony_bug_reproduction/tree/bug_reproduction](https://github.com/N-M/symfony_bug_reproduction/tree/bug_reproduction)

**Comment by stof** [comment]
this Configuration class does not have a root node, indeed: https://github.com/N-M/symfony_bug_reproduction/blob/bug_reproduction/src/CoreBundle/DependencyInjection/Configuration.php

As this bundle does not care about its config (it does not expose a semantic config), the Configuration class is a fake one, not properly built. And this is not handled properly by the new code dealing with env placeholders.

**Comment by Adapik** [comment]
I've also encountered a similar error. I suppose it's not a bug and you should just add a root node to your config
