### ISSUE TITLE
AJAX GET requests are not displayed in debug panel

### ISSUE THREAD

**Issue by shmigandrew** [symfony/symfony#27464]
**Symfony version(s) affected**: 3.4.10

**Description**  
If a web page performs ajax GET request there is no info about this request in debug panel (modal popup window).

![screen shot 2018-06-01 at 12 14 36](https://user-images.githubusercontent.com/31700633/40833027-672da1da-6595-11e8-89aa-1da9b8b6c94a.png)

But the same request is in 'Last 10' tab:

![screen shot 2018-06-01 at 12 15 21](https://user-images.githubusercontent.com/31700633/40833054-7f51c110-6595-11e8-955c-7b38141eaf8b.png)

**How to reproduce**  
Perform any GET ajax request with active debug panel.

**Possible Solution**  

**Additional context**

**Comment by maisoui** [comment]
+1 with Symfony 4.1
