### ISSUE TITLE
[DX] Better error message when symfony/templating is needed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27468]
**Description**  
As reported on Symfony Docs (https://github.com/symfony/symfony-docs/issues/9867):

> I created a new Symfony project and added Twig. I also added an external Bundle that use the syntax FooBarBundle::template.html.twig and I got this exception:
>
> Unable to find template "FooBarBundle::template.html.twig" (looked into: /srv/templates, /srv/templates).

**Possible Solution**  
If the not found template contains `:` and `symfony/templating` is not installed, display a different error message explaining the user that they must install symfony/templating.

**Comment by fabpot** [comment]
I would recommend to fix the third party bundle. Adding `symfony/templating` would work of course, but that comes with a performance penalty and this is not a long term solution. I agree though that a better error message would be nice.
