### ISSUE TITLE
[Console][DX] Make Ambiguous Commands Nicer

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#27473]
**Description**  
Symfony comes with a lot of commands, few bundles here and there and we end up with a long list:
```
$ php7.2 bin/console | wc -l
141
```

Symfony provides awesome `list namespace` command which can list commands just from a namespace I need:
![image](https://user-images.githubusercontent.com/1227834/40857812-e602729a-65a1-11e8-820a-d39affa24d4e.png)

However when I type `php7.2 bin/console make:` an angry error message appears (which in PhpStorm is unreadable anyway):
![image](https://user-images.githubusercontent.com/1227834/40857847-0246fdd6-65a2-11e8-8341-4589ee65485a.png)

**Make it better**
Maybe instead of displaying the error message we can display list of commands like `list namesapce` does when someone:
1. Executes command which doesn't exists
2. Name of the command ends with `:` **OR**
3. Name of the command matches namespace

WDYT?

**Comment by nicolas-grekas** [comment]
:100: ! Would you like to work on this?

**Comment by kiler129** [comment]
@Nicals Sure, it annoys me every day ;)

**Comment by chalasr** [comment]
As explained in #30971, the error is legitimate here.
