### ISSUE TITLE
Finder test failure

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#27480]
**Symfony version(s) affected**: master (of today)

**Description**  
mkdir failure

**How to reproduce**  
`./phpunit src/Symfony/Component/Finder/`

**Possible Solution**  
no

**Additional context**  

```
Testing src/Symfony/Component/Finder/
..............................EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  63 / 168 ( 37%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.........EEEEEEEEEEEEE....... 126 / 168 ( 75%)
.................................EEEEEEEEE                      168 / 168 (100%)

Time: 43.95 seconds, Memory: 6.00MB

There were 89 errors:

1) Symfony\Component\Finder\Tests\FinderTest
mkdir(): File exists

/proj/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php:57
```
Truncated many more lines all caused by failure at line 57 of `RealIteratorTestCase.php`

PHP 7.2.5
OS: ubuntu 16.04

**Comment by nicolas-grekas** [comment]
Hello, I don't reproduce this issue, tests pass on my laptop. Can you debug why it fails and submit a PR if you find something to fix?

**Comment by flip111** [comment]
I don't know how to debug this, please advise.

**Comment by flip111** [comment]
I can't reproduce this anymore, i will reopen and try to look around in the fileystem at the time this error occurs.

**Comment by flip111** [comment]
Oh actually i can reproduce this .. i had another project with Finder that doesn't clean up. I'll try to find the problem and make Finder a bit more resilient.

**Comment by flip111** [comment]
About the FinderTest .. all paths are hardcoded, should they stay like that or can the right paths be searched? For example ..  https://github.com/symfony/symfony/blob/d8739d183e2e24f7da5741658bf22bf55eb9f0af/src/Symfony/Component/Finder/Tests/FinderTest.php#L330-L352  the thing is that by changing the fixture all the test cases need to be updated. It's tedious
