### ISSUE TITLE
France Metropolitan missing in Intl

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony#27487]
**Symfony version(s) affected**: Probably all

**Description**  
The country France Metropolitan is missing in the Intl bundle. 
I am currently migrating an old database into the new application and can't import the users that have the country `France Metropolitan`. The code would be `FX` and `FXX`, but the Intl thinks it is invalid.

**How to reproduce**  
```php
$user->setCountry('FX');
```

**Possible Solution**  
Add the missing dataset.

**Additional context**

**Comment by fabpot** [comment]
We don't manage the data for Intl. But in any case, `France Metropolitan` is not a country (it refers to the European part of France, without the overseas territories).

**Comment by CoalaJoe** [comment]
@fabpot Thanks for the clearance. What am I to do now? Should I cast it to France?

**Comment by fabpot** [comment]
I think so.
