### ISSUE TITLE
test.service_container doesn't work with private shared:false services

### ISSUE THREAD

**Issue by vfalduto** [symfony/symfony#27488]
**Symfony version(s) affected**: 4.1.x

**Description**  

test.service_container doesn't work with private shared:false services

```yaml
App\MyService:
    shared: false
    public: false 
```
When we try to load the MyService from the new "test.service_container" we have an exception : 

```php
 $client = static::createClient();
 $privateContainer = $client->getContainer();
 $privateContainer->get(App\MyService::class);
```

The 'AppMyService' service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
Hello, this is expected right now: the test containers gives access to private services only if they have not been removed or inlined. Since non-shared services are almost always inlineable, you cannot get them.

What is the use case of fetching a non-shared service in a test case?

**Comment by vfalduto** [comment]
My non-shared service represents complex's operations on third party API with a session.
These operations are used by some manager who determine how to send the request.

In our tests, we only want to check if the complex's operations are well craft.
But the operations depends on other services with no need to mock for testing.

**Comment by nicolas-grekas** [comment]
OK, then I would suggest you access the service via a public alias enabled in the test's config only. The current behavior is correct IMHO.

**Comment by nicolas-grekas** [comment]
I think this can be kept as a feature request. I would even extend it to private aliases: we could allow accessing remaining private services via their private alias if any (like the autowiring aliases.)
Implementing could be done in `TestContainer*Pass` in FrameworkBundle I suppose.

**Comment by nicolas-grekas** [comment]
I changed my mind, see #27528 :)
