### ISSUE TITLE
Debug exception classes fail to pass $previous to FatalErrorException

### ISSUE THREAD

**Issue by alreece45** [symfony/symfony#27483]
**Symfony version(s) affected**: 4.1.2 (appears to affect 4.1.0)

**Description**  

Debug exceptions pass an invalid parameter when `$previous` is set. e.g:

```
Uncaught TypeError: Argument 6 passed to Symfony\Component\Debug\Exception\FatalErrorException::__construct() must be of the type integer or null, object given,
```

Classes that appear to be affected:

 * [`ClassNotFoundException`](https://github.com/symfony/symfony/blame/4.1/src/Symfony/Component/Debug/Exception/ClassNotFoundException.php#L29)
 * [`UndefinedFunctionException`](https://github.com/symfony/symfony/blame/4.1/src/Symfony/Component/Debug/Exception/UndefinedFunctionException.php#L29)
* [`UndefinedMethodException`](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Debug/Exception/UndefinedMethodException.php)
 
**How to reproduce**  
Trigger an undefined method, class, or function with another exception.

**Possible Solution**  

1. Accept an object as the 6th parameter (BC issue?)
2. Don't pass `$previous` to the `FatalErrorException` constructor (potentially use a setter?)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by alreece45** [comment]
I was hoping it'd be obvious enough that `$previous` is not an integer.

Below is an example controller that contains routes that trigger an error in each one of the classes:

```php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class BugController extends Controller
{
    /**
     * @Route("/bug/method")
     */
    public function me()
    {
        try {
            throw new \RuntimeException("This exception doesn't matter much");
        } finally {
            $a = new \stdClass();
            $a->undefinedmethod();
        }
    }
    /**
     * @Route("/bug/function")
     */
    public function fu()
    {
        try {
            throw new \RuntimeException("This exception doesn't matter much");
        } finally {
            undefined_function();
        }
    }
    /**
     * @Route("/bug/class")
     */
    public function cl()
    {
        try {
            throw new \RuntimeException("This exception doesn't matter much");
        } finally {
            $a = undefinedClass();
        }
    }
}
```

**Comment by pmontoya** [comment]
Can I take this one?

**Comment by pmontoya** [comment]
My suggestion

- Add a parameter to Symfony\Component\Debug\Exception\FatalErrorException constructor with default value null
- Call \ErrorException with this parameter.
- Call parent constructor of classes that extend FatalErrorException with default parameters followed by $previous : 
```
parent::__construct(
    $message,
    $previous->getCode(),
    $previous->getSeverity(),
    $previous->getFile(),
    $previous->getLine(),
    null,
    true,
    null,
    $previous->getPrevious()
);
```

Is it ok for you?

**Comment by pmontoya** [comment]
@xabbuh : The bug exists in 2.8 bug type hint error in 4.0. On which branch I create the fix please?
