### ISSUE TITLE
Regression in FrameworkBundle's client when using custom container base class

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#27494]
**Symfony version(s) affected**: 4.1.0

**Description**  
Service `test.service_container` does not respect the output of kernel's `getContainerBaseClass` method. 

Therefore, when FrameworkBundle's `Client` returns it on `getContainer`, we receive an instance of `TestContainer` instead of `SomeCustomContainer`. This makes it impossible to call a custom method added to the container (in our case - https://github.com/PolishSymfonyCommunity/SymfonyMockerContainer).

**How to reproduce**  
Either: 
 - Define custom container base class and call a method on custom container coming from FrameworkBundle's `Client`.
 - Install Sylius v1.2.0-BETA and try to run phpunit tests.

**Possible solution**  
Adding a `__call` method on TestContainer which passes unknown calls to `TestContainer`'s public container.

**Additional context**
I'm up to making a PR fixing it (using the solution proposed above), but not before Wednesday, and I don't mind anyone fixing it before that :)

![screen shot 2018-06-04 at 18 34 08](https://user-images.githubusercontent.com/1897953/40929729-ec11b4bc-6825-11e8-94d9-7e022a9ee99a.png)

**Comment by nicolas-grekas** [comment]
Another solution is to revert to returning the real container when using Client::getContainer(), and provide the test container via static::$container only.

**Comment by pamil** [comment]
@nicolas-grekas which solution do you prefer? I find getting the same container when you call `Client::getContainer()` or `static::$container` more intuitive.

If anyone (like me) needs a hotfix, make your test kernel implement `CompilerPassInterface` and paste this:
```php
public function process(ContainerBuilder $container): void
{
    $clientDefinition = $container->findDefinition('test.client');

    if (count($clientDefinition->getArguments()) >= 5) {
        $clientDefinition->replaceArgument(4, null);
    }
}
```

**Comment by nicolas-grekas** [comment]
I'd prefer reverting any possible BC break, and `__call` is not bullet proof...

**Comment by nicolas-grekas** [comment]
see #27501
