### ISSUE TITLE
PHPUnit Bridge | SymfonyTestsListener V7

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony#27495]
**Symfony version(s) affected**: 4.1.0

**Description**  
Since the update to 4.1.0, the Symfony listeners fail the suite tests due to a wrong signature of the method `addError()`. 

**How to reproduce**  
Just launch a new suite test using the latest version of PHPUnit and PHPUnit-Bridge. 

**Possible Solution**  
None at this time as the bug still be prompt when the listener is disabled. 

**Additional context**  
![PHPUnit](https://imageshack.com/a/img922/5163/EtwgEq.png)

**Comment by nicolas-grekas** [comment]
I think this can arise when having phpunit installed twide: once via the bridge, twice via your phpunit deps.
Remove it from your composer.json file and that should fix it.

**Comment by Guikingone** [comment]
Ok, seems to work locally, just launched tests via CircleCI, the error is due to the `phpunit.xml.dist` file which is absent bug the bug seems to be fixed. 

Many thanks @nicolas-grekas, if no one reference the issue, I think it could be closed :)
