### ISSUE TITLE
[Console] Console errors are displayed twice on screen

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#27510]
**Symfony version(s) affected**: 3.4+

**Description**  
This happens when you install a fresh Symfony app.

**How to reproduce**  
```bash
$ composer create-project symfony/skeleton foo
$ cd foo
$ bin/console cache:
```

**Additional context**  
At this moment, the kernel's [`logger`](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpKernel/Log/Logger.php) is the one activated in the system, showing error logs on `stderr` stream by default. 

I'm not sure if it's expected, but it looks like a visual issue for CLI apps:
![logger-outerr](https://user-images.githubusercontent.com/2028198/41011682-e6bff6cc-690b-11e8-832f-02ef98e30c61.png)

https://github.com/symfony/symfony/blob/9a077ca60406eb3b437eedc41bfe5cf55f16b129/src/Symfony/Component/HttpKernel/Log/Logger.php#L40

https://github.com/symfony/symfony/blob/9a077ca60406eb3b437eedc41bfe5cf55f16b129/src/Symfony/Component/Console/EventListener/ErrorListener.php#L46

**Comment by chalasr** [comment]
Confirmed and I agree it is not desirable. 
We already fixed that for the monolog logger on the standard edition https://github.com/symfony/symfony-standard/pull/1044 (flex recipe settings are the same).

**Comment by modiamir** [comment]
Hello, should the `ErrorListener` prevent logging if the logger handler is stream?

**Comment by yceruto** [comment]
@modiamir I don't think so. The `ErrorListener` is not aware of the logger handler as it doesn't belong to the public API.

This affects the most CLI app that don't need a log file. So what about to configure a `minLevel` to `LogLevel::CRITICAL` by default here?:
https://github.com/symfony/symfony/blob/4435144a24bea3d8b064a7825121132abcc7c005/src/Symfony/Component/HttpKernel/DependencyInjection/LoggerPass.php#L38-L39

This would avoid to display twice each console error by default. Later, if necessary we can set the min level by configuration:
```yaml
services:
    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments: ['warning']
```
