### ISSUE TITLE
Running commands from controller ignores verbosity setting

### ISSUE THREAD

**Issue by charj** [symfony/symfony#27517]
**Symfony version(s) affected:** 4.0

**Description**  
When running commands from controllers, specifying the verbosity on the BufferedOutput appears to be ignored. But running the same command directly from the console it behaves as expected.

**How to reproduce**
Controller
```
    /**
     * @Route("/test")
     */

    public function test(Request $request, KernelInterface $kernel): Response
    {
        $application = new Application($kernel);
        $application->setAutoExit(false);

        $input = new ArrayInput([
            'command' => 'verbose:test'
        ]);

        $output = new BufferedOutput(OutputInterface::VERBOSITY_NORMAL);
        $application->run($input, $output);

        var_dump($output->fetch());
        die;
    }
```
Command
```
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Serializer\Encoder\CsvEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Serializer;

class TestCommand extends Command
{
    protected function configure()
    {
        $this
            ->setName('verbose:test');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        var_dump($output->isVerbose());
    }
}
```
**Possible Solution**  
I'm not sure whether this is a bug, or I have been lead down a path due to misleading documentation.
https://symfony.com/doc/current/console/command_in_controller.html 

**Additional context** 
Example cli output (Behaves exactly as expected, but the controller does not match this behaviour)
```
root@66d918d5d145:/var/www/html# bin/console verbose:test   
bool(false)
root@66d918d5d145:/var/www/html# bin/console verbose:test -v
bool(true)
```

PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:33:27) ( NTS )

**Comment by SpacePossum** [comment]
My guess is that your `Application` (assuming `Symfony\Component\Console\Application`) set the verbosity again on the output buffer to `OutputInterface::VERBOSITY_NORMAL`, which is the default for an `Application`.
You can try changing the input to:

```
        $input = new ArrayInput([
            'command' => 'verbose:test',
            '--quiet',
        ]);
```

and drop the setting for the output, I think the output will still be reconfigured by the `Application` to be quiet.

**Comment by charj** [comment]
Hi, Thanks for your input.

The following does work, but I was expecting to see `normal` output which I currently am unable to achieve for what I can see. Unless you have any other suggestions?

**Comment by tienvx** [comment]
I think this is a bug. It affect Symfony 4.2 too.
This code remain quiet:
```
$input = new ArrayInput([
    'command' => 'mbt:path:generate',
    'model' => $model,
    '--generator' => $generator,
    '--meta-data' => $metaData,
]);

$output = new BufferedOutput();
$output->setVerbosity(OutputInterface::VERBOSITY_NORMAL);
$application->run($input, $output);

var_dump($output->fetch());
```
While this code verbose normal:
```
$input = new ArrayInput([
    'command' => 'mbt:path:generate',
    'model' => $model,
    '--generator' => $generator,
    '--meta-data' => $metaData,
    '-v',
]);

$output = new BufferedOutput();
$output->setVerbosity(OutputInterface::VERBOSITY_NORMAL);
$application->run($input, $output);

var_dump($output->fetch());
```

**Comment by Simperfit** [comment]
PR welcomed, if someone wants to work on a fix, if not, ill try to do it :p.

**Comment by charj** [comment]
> PR welcomed, if someone wants to work on a fix, if not, ill try to do it :p.

Do it! I'll help test and code review! :+1:

**Comment by dimabory** [comment]
@charj @tienvx Please read more about verbosity levels to understand why `isVerbose` method call responds with either `false` or `true`. It returns `true` only in the case when actual verbosity value is more than `OutputInterface::VERBOSITY_VERBOSE`.

https://symfony.com/doc/current/console/verbosity.html

**Comment by tienvx** [comment]
Thank you for clarify it @dimabory +1

But I think this is still a bug, right?

```
$input = new ArrayInput([
    'command' => 'mbt:path:generate',
    'model' => $model,
    '--generator' => $generator,
    '--meta-data' => $metaData,
]);

$output = new BufferedOutput();
$output->setVerbosity(OutputInterface::VERBOSITY_DEBUG);
$application->run($input, $output);

var_dump($output->fetch());
```

This code print empty string

**Comment by tienvx** [comment]
In order to help debugging, here are commands to reproduce the bug:
```
git clone git@github.com:tienvx/mbt-api-bundle.git
cd mbt-api-bundle
composer install -v
phpunit --filter "ModelTest::testModelTest"
```
Here is the code https://github.com/tienvx/mbt-api-bundle/blob/master/src/Controller/ModelController.php#L146

Hope it help!

**Comment by dimabory** [comment]
@tienvx I don't think this is a bug. Could you explain what do you actually expect from the command (please add command's code as well to above comment)?

**Comment by charj** [comment]
@dimabory There is no verbose output despite the flag being added

**Comment by dimabory** [comment]
> @dimabory There is no verbose output despite the flag being added

In the description of the issue you've provided this
```php
$output = new BufferedOutput(OutputInterface::VERBOSITY_QUIET);
```

**Comment by charj** [comment]
@dimabory Apologies, I have corrected my orignal post.

**Comment by dimabory** [comment]
> @dimabory Apologies, I have corrected my original post.

@charj Please re-read this comment - https://github.com/symfony/symfony/issues/27517#issuecomment-483387520


`bin/console verbose:test -q` = `OutputInterface::VERBOSITY_QUIET`
`bin/console verbose:test` = `OutputInterface::VERBOSITY_NORMAL`
`bin/console verbose:test -v` = `OutputInterface::VERBOSITY_VERBOSE`
`bin/console verbose:test -vv` = `OutputInterface::VERBOSITY_VERY_VERBOSE`
`bin/console verbose:test -vvv` = `OutputInterface::VERBOSITY_DEBUG`

**Comment by charj** [comment]
Thanks for the info @dimabory I'll investigate later today when I have some more time.

**Comment by xabbuh** [comment]
Can we close here or is there still something that needs to be fixed?

**Comment by tienvx** [comment]
I think it's still a bug. As mentioned in the issue's description:
* Running command from the **code** does not print the output (bug - does not work as expected)
* Running command directly from the **cli** does print the output (work as expected)

@dimabory Are you trying to say that running command from the cli work as expected?

**Comment by charj** [comment]
Sorry All, I've been super busy recently, I'll get to this when I can.
But essentially, what @tienvx said aligns with my findings.

**Comment by sergey-shambir** [comment]
I've faced with similar bug: console scripts doesn't print anything after another command called with `Application::run(...)`.

The problem is that ConsoleHandler class instance shared between old and new Application objects, so new Application drops console settings by calling `ConsoleHandler::setOutput` and `ConsoleHandler::close` methods.

There is workaround: create a new Kernel using an old one.

```php
// Create independent Kernel to avoid overriding global ConsoleHandler.
$kernel = new Kernel($this->appKernel->getEnvironment(), $this->appKernel->isDebug());

// Create independent Application instance and disable php process auto exit
$application = new Application($kernel);
$application->setAutoExit(false);
```

It's the only difference from example in [How to Call a Command from a Controller](https://symfony.com/doc/current/console/command_in_controller.html) in my case

**Comment by sergey-shambir** [comment]
And yet one thing: you need to call `$kernel->shutdown();` for the new Kernel after `$application->run(...)` - otherwise PHP will not free database connections until process exit (at least when `Kernel` created in Debug mode, i.e. `$this->appKernel->isDebug()` is true)

**Comment by Tobion** [comment]
To the original issue. There doesn't seem to be a bug. If you run the command, it set's the output verbosity depending on the arguments. See https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Console/Application.php#L886-L894
So `$output = new BufferedOutput(OutputInterface::VERBOSITY_NORMAL);` has no effect.
