### ISSUE TITLE
[Routing][4.1][BC Break] Controller names drop single colon notation

### ISSUE THREAD

**Issue by Majkl578** [symfony/symfony#27522]
**Symfony version(s) affected**: 4.1.0

**Description**  
Route loader (DelegatingLoader) now always returns controllers with double-colon notation.
This breaks existing code that relies on the single-colon format.

**How to reproduce**
Have a controller referenced with single colons. Although the code affected is a custom route loader that generates such controller names, it shouldn't be directly needed to have one to reproduce.

**Possible Solution**  
Revert the change for implicitly changing `:` to `::`:
```php
$controller = str_replace(':', '::', $controller);
```
_[as commented here](https://github.com/symfony/symfony/pull/26085#discussion_r193406040)_

Suggesting to keep the deprecation, but revert forced change from `:` to `::`.

**Additional context**  
The code affected performs different logic based on whether controller is single-colon or double-colon notation (in the `_controller` request attribute). Single colon is used for a controller that is registered as a DI service, double colon is used for non-registered controllers.
Although possibly unfortunate (dates back to SF 2.6), this has been working flawlessly until SF 4.1.

Introduced in #26085.

**Comment by stof** [comment]
> Single colon is used for a controller that is registered as a DI service, double colon is used for non-registered controllers.

but that detection is already wrong in 3.4 and 4.0: if your service is registered as a service using its FQCN as id, you could already use the double colon in 3.4 and 4.0, but the service would still be used.
so the custom logic relying on the fact that anything using double colon would not be a service was already not working on older 3.4 and 4.0.

thus, if we consider this change a BC break, it would also mean that we can **never** add any new feature in the controller syntax, as any logic assuming the old rules would break when using the new feature.

**Comment by Tobion** [comment]
> The code affected performs different logic based on whether controller is single-colon or double-colon notation (in the _controller request attribute). Single colon is used for a controller that is registered as a DI service, double colon is used for non-registered controllers.

This is not a safe assumption. Even before SF 3.4, double colon could be used for controllers as services under some circumstances. This is why we deprecated the single column syntax.
Considering this, you need to change your logic anyway to make it work properly.

**Comment by Majkl578** [comment]
> so the custom logic relying on the fact that anything using double colon would not be a service was already not working on older 3.4 and 4.0

As you can see, it was working perfectly fine until 4.1.0. Maybe because no other bundles (Rest, Twig etc.) were used, but it was working flawlessly.

> it would also mean that we can never add any new feature in the controller syntax

Well you can, in major version for sure. But breaking bundles in minor versions is unfortunate.

> This is not a safe assumption.

Agreed, as I said, this is coming from days of SF 2.6.

> This is why we deprecated the single column syntax.

I totally agree with that, it has always been confusing.

> Considering this, you need to change your logic anyway to make it work properly.

Yes: 4.x should throw deprecation (as it does), but it should still work until 5.0, otherise the BC promise is broken. :/

**Comment by nicolas-grekas** [comment]
Anyone willing to try a fix?

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/27566
