### ISSUE TITLE
[RFC] Allow for an integer $type on ControllerTrait::addFlash() and FlashBagInterface::add()

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#27520]
Currently both `ControllerTrait::addFlash()` and `FlashBagInterface::add()` have a `string` type hint.

This is not useful to set messages.

I found myself using Monolog `Logger` constants to set the type of messages:

```php
use Monolog\Logger;

$this->addFlash(Logger::ERROR, 'An error happened');
```

But using `declare(strict_types=1)` cause this to be considered an error (correctly).

I suggest remove the method type hint and add a check inside the `ControllerTrait::addFlash()` method:

```php
    /**
     * Adds a flash message to the current session for type.
     *
     * @throws \LogicException
     *
     * @final
     */
    protected function addFlash($type, string $message)
    {
+        if (!is_string($type) && !is_int($type)) {
+            throw new \InvalidArgumentException('Only strings and ints are accepted');
+        }
        
        if (!$this->container->has('session')) {
            throw new \LogicException('You can not use the addFlash method if sessions are disabled. Enable them in "config/packages/framework.yaml".');
        }

        $this->container->get('session')->getFlashBag()->add($type, $message);
    }
```

According to this, also the `FlashBagInterface::add()` DocComment has to be updated:

```php
    /**
     * Adds a flash message for type.
     *
-     * @param string $type
+     * @param string|int $type
     * @param string $message
     */
    public function add($type, $message);
```

The classes that implement `FlashBagInterface` don't have any method type hint and inherit the DocBlock from `FlashBagInterface`, so no changes are required.

**CONCRETE PROBLEM**

This type hint causes concrete problems.

In fact I could bypass the type hinting forcing using the typecasting of the constants provided by `Logger`:

```php
use Monolog\Logger;

- $this->addFlash(Logger::ERROR, 'An error happened');
+ $this->addFlash((string) Logger::ERROR, 'An error happened');
```

But this cause problems in Twig:

```
<div class="Notifications">
    {% for notification in notifications %}
        {# INFO #}
        {% if 200 === notification.level %}
            {% set level = 'info' %}
...
```

**Comment by Tobion** [comment]
Changing the interface would be a bc break. See http://symfony.com/doc/current/contributing/code/bc.html

To me it does not seem worth to create a bc break for this.

**Comment by Aerendir** [comment]
@Tobion , it is not a BC as the `string` type hint remains: all the current code will continue to work as expected and as usual.

**Comment by Aerendir** [comment]
Ok, the problem is this: we have a helper method in the `ControllerTrait` that forces to use only strings and the real method `FlashBagInterface::add()` that doesn't: this is a contradiction.

Considering that the `$type` can also be an `integer` (as demonstrated by the use of `Logger`), the wrong method is the one in the `ControllerTrait`: this forces uselessly to use `string`s.

The fact that it was type hinted in the 4.0 version is irrelevant: if there is an error, there is an error, and it it not relevant when the error was introduced: it has to be removed.

**Comment by nicolas-grekas** [comment]
The method is final so it's ok changing it btw.

**Comment by Tobion** [comment]
It's a bc break because implementations of `FlashBagInterface::add()` might need to support int now which they didn't need before.

**Comment by Aerendir** [comment]
@Tobion , forgive me if I insist: the BC policy involves only the methods that are directly used by the end developer.

It doesn't involve the internals.

**Comment by Aerendir** [comment]
@ostrolucky , yes, for sure: but this is "dirty".

The real point I miss is why the helper has to introduce a restriction that the real method `FlashBagInterface::add()` hasn't.

**Comment by ostrolucky** [comment]
my comment was directed to @Tobion

**Comment by Aerendir** [comment]
@Tobion , more about internal implementation: they are simple arrays: the `$type` is used only as keys, and array keys can be `string`s or `int`s.

- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/AutoExpireFlashBag.php#L63-L66
- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.php#L57-L61

These are the only two concrete implementations.

Anyway, I repeat: `$type` will continue to accept `string`s: it only will accept also `int`s.

**Comment by iltar** [comment]
It's pretty common to put objects in flash messages, like a data container for a delayed translation. I've written this code before (and I know it breaks the docblock), but it's a very clean solution. I would prefer that the interface would accept "mixed" instead.

**Comment by Aerendir** [comment]
@iltar , are you speaking about the second param, `$message`?

**Comment by iltar** [comment]
@Aerendir correct

**Comment by nicolas-grekas** [comment]
Rereading this, I understand that you're using a number as the name of a flash message?
I think it's correct to fail in strict mode. A number is a very loose name for a message, imagine someone else uses `->set(ANOTHER_CONST, ...)` but `ANOTHER_CONST` also equals `Logger::ERROR`. Using a number, this is much more likely to collide.

**Comment by Aerendir** [comment]
@nicolas-grekas , I think the messages should be standardized in the team: a scenario like the one you are describing is caused by a poor development habit... The same thing may happen also using strings with the exact same probability...

Anyway, as I already told, there is anyway an inconsistency: one method put the restriction (the one in the trait) while another doesn't (the one in the Session): there are only two alternatives: both of them put restrict to strings or both of them don't.

But having one method that restricts and another that doesn't for me is an inconsistency.

**Comment by Aerendir** [comment]
Anyway, just as a side note, I switched from `Monolog\Logger` to `Psr\LogLevels`: this last one uses strings instead of numbers and so the problem is not relevant to me anymore.

But remains the inconsistency for which a clear decision should be taken, IMHO.

**Comment by Aerendir** [comment]
As "inconsistency" I meant there is no type hinting in the concrete implementations... While there is for the helper method of `ContainerTrait`.

You are right: the interface hints for `string`s only: the concrete implementations don't type hint for them.

**Comment by jvasseur** [comment]
The lack of type hinting comes from the fact that adding them now would break extending classes for people using PHP < 7.2 so we can't add them now.

And the concrete implementations does hint for `string`s, they are using `{@inheritdoc}` meaning they inherit the phpdoc from their parent including the type hints.

**Comment by Aerendir** [comment]
And as a side note: I don't understand what do you mean by "BC".

If until now you had to deal with only `string`s, nothing changes if you deal also with `int`s: also if you enable the `strict_mode` the current code will continue to work as until now you only passed `string`s.

Different discourse is if you make possible to pass also `null` or objects.

But in this specific case I don't see any BC.

**Comment by nicolas-grekas** [comment]
The BC is for other implementations, extending these interfaces/classes: adding the type would break them. What you describe as inconsistent will be fixable with Symfony 5, when PHP will be bumped to 7.2 or higher. For now, we can't do anything I believe.

**Comment by Aerendir** [comment]
Ok @nicolas-grekas , then this issue can be closed if reputed not relevant.

I solved my specific use case, so it is all about Symfony: if you think this is something should be fixed or not...

Or if the type hinting has to be added to the `SessionBag` class too, or not...

I made you aware that there are methods type hinted and methods that aren't: the choice is yours.

Just for reference:

[`FlashBagInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBagInterface.php#L23-L29) (_not_ type hinted):

```php
    /**
     * Adds a flash message for type.
     *
     * @param string $type
     * @param string $message
     */
    public function add($type, $message);
```

[`FlashBag`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.php#L54-L60) (_not_ type hinted)

```php
    /**
     * {@inheritdoc}
     */
    public function add($type, $message)
    {
        $this->flashes[$type][] = $message;
    }
```

[`AutoExpireFlashBag`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Flash/AutoExpireFlashBag.php#L60-L66) (_not_ type hinted)

```php
    /**
     * {@inheritdoc}
     */
    public function add($type, $message)
    {
        $this->flashes[$type][] = $message;
    }
```

[`ControllerTrait`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L145-L159) (**type hinted**)

```php
    /**
     * Adds a flash message to the current session for type.
     *
     * @throws \LogicException
     *
     * @final
     */
    protected function addFlash(string $type, string $message)
    {
        if (!$this->container->has('session')) {
            throw new \LogicException('You can not use the addFlash method if sessions are disabled. Enable them in "config/packages/framework.yaml".');
        }
        $this->container->get('session')->getFlashBag()->add($type, $message);
    }
```

**Comment by jvasseur** [comment]
The difference comes from the fact that the `addFlash` method in the `ControllerTrait` is marked as final. That allowed us to add the type hint in Symfony 4.0 since we don't have to deal with inheritance. Since the other methods aren't final we can't add the type hint until we require PHP >= 7.2.

**Comment by Aerendir** [comment]
@jvasseur , excuse me again if I insist again: I'm only trying to understand as much as I can...

The `composer.json` of both `symfony/http-fundation` and of `symfony/framework-bundle` require `"php": "^7.1.3"`.

And from what I read, the type declaration (alias type hinting) was added in [PHP 7.0](http://php.net/manual/en/migration70.new-features.php).

So, what is the relation between the PHP version and the difference highlighted?

**Comment by Aerendir** [comment]
Yes, it is true! I forgot this particular! You are right, I’m wrong.

Thank you for your immense patience :)
