### ISSUE TITLE
Invalid lazy load proxy generation

### ISSUE THREAD

**Issue by speller** [symfony/symfony#27537]
**Symfony version(s) affected**: 4.1.0

**Description**  
When two services with different names are implemented by the same class the compiled container become broken with PHP fatal error.

**How to reproduce**  
1. Create the following services declaration:
```
        <service id="bar" class="foo" lazy="true"/>
        <service id="baz" class="foo" lazy="true"/>
```
2. Create empty class definition `class foo {}`.
3. Compile the container and run compiled version.

Expected: Normal lazy-loaded operation.

Actual:

> Fatal error: Cannot declare class foo_40d7466, because the name is already in use in path-to-container\container-name.php on line 13706

**Possible Solution**  
Pass service id to the hash suffinx generator function or don't duplicate definition of the same proxied class.

**Comment by dmaicher** [comment]
I cannot reproduce this.

Use this simple example:

```yaml
    bar:
        class: Symfony\Component\HttpFoundation\RequestStack
        lazy: true
        public: true

    baz:
        class: Symfony\Component\HttpFoundation\RequestStack
        lazy: true
        public: true
```

And I can retrieve both services from the container without any issues.

Dumped factory files look like this:

```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bar' shared autowired service.

if ($lazyLoad) {
    return $this->services['bar'] = $this->createProxy('RequestStack_e1a8ddd', function () {
        return \RequestStack_e1a8ddd::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getBarService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Symfony\Component\HttpFoundation\RequestStack();
```

```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'baz' shared autowired service.

if ($lazyLoad) {
    return $this->services['baz'] = $this->createProxy('RequestStack_e1a8ddd', function () {
        return \RequestStack_e1a8ddd::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getBazService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Symfony\Component\HttpFoundation\RequestStack();
```

**Comment by speller** [comment]
@dmaicher do you have the only one declaration of the `\RequestStack_e1a8ddd` class?

**Comment by speller** [comment]
@dmaicher The issue is happen when the `as_files` parameter of the `PhpDumper` is set to `false`. When separate files are generated the duplicated code not appeared because the same class name (thus, the same file name) is used for duplicate code output. When single output file is used the duplicated code has no chance to be omitted and two identical class declarations are written to the compiled container code.

**Comment by dmaicher** [comment]
> The issue is happen when the as_files parameter of the PhpDumper is set to false

Where exactly did you set this to false? :blush:

**Comment by speller** [comment]
Actually I use the Dependency Injection package separately.

**Comment by nicolas-grekas** [comment]
@speller could you provide a small repository we could clone to work on the issue? Also, is this new to 4.1 or does it also happen on 3.4? The class should be generated once for sure (passing the service id to the hash suffix generation would be creating two identical class with a different name, thus wasting some resource.)

**Comment by speller** [comment]
@nicolas-grekas This issue was found in 3.4. I've tried to update to 4.1 but with the same result.

Here is the test project: https://github.com/speller/symfony_di_bug . The `as_files` option is `false` by default. Including the generated container cause error: `Fatal error: Cannot declare class TestClass_92ba666, because the name is already in use`
