### ISSUE TITLE
Process package on windows

### ISSUE THREAD

**Issue by oriceon** [symfony/symfony#27539]
Hi there. I'm using symfony/process 4.1.0 on Windows 10, PHP 7.2 and trying to start a process in background but seems that does`t work.

I have to run this command: ```start /B php artisan queue:async 15 async > NUL```

I see that Process.php class get me this command: ```cmd /V:ON /E:ON /D /C (start /B php artisan queue:async 15 async > NUL) 1>"C:\Apache24\tmp\sf_proc_00.out" 2>"C:\Apache24\tmp\sf_proc_00.err"```

If i manualy run this command, will not work because as i see, the command should be market with extra double quotes before and after parenthesis like: ```cmd /V:ON /E:ON /D /C "(start /B php artisan queue:async 15 async > NUL)" 1>"C:\Apache24\tmp\sf_proc_00.out" 2>"C:\Apache24\tmp\sf_proc_00.err"```

Running new command from cli will execute that process... but not directly from web server...

The problem is that even though I have modified the Process.php class, it still does not launch the process.

Also with no luck :) i tryed with vanilla php: ```pclose(popen("start /B php artisan queue:async 15 async", "r"))```

After a wile i get: ```client.ERROR: The process "start /B php artisan queue:async 15 async > NUL" exceeded the timeout of 60 seconds. ... \\vendor\\symfony\\process\\Process.php:1158```

What else can do?
Thanks!

**Comment by nicolas-grekas** [comment]
I'm not sure I understand what you're asking for? If you need help to start a process in the background on Windows, you'll have a better chance asking on stackoverflow I suppose. You write you tried with vanilla php: did it work as you wanted? Also, what is the code you ran that is using the `Process` component?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
