### ISSUE TITLE
Add getConstraintViolationList to FormInterface [DX]

### ISSUE THREAD

**Issue by leevigraham** [symfony/symfony#27533]
**Description**  

Symfony 4.1 [added a ConstraintViolationListNormalizer](https://symfony.com/blog/new-in-symfony-4-1-serializer-improvements#added-a-constraintviolationlistnormalizer). The example shows how to get violations from the validator. I wonder if we should add a shortcut to get a ConstraintViolationList from a form.

**Example**  

Based on the example in the announcement:

```php
/**
 * @Route("/blog/new", name="api_blog_new")
 * @Method("POST")
 * @Security("is_granted('ROLE_ADMIN')")
 */
public function new(Request $request)
{
    $blogPost = new BlogPost();
    $this->createForm(BlogPostType::class, $blogPost);
    $form->handleRequest($request);

    $violations = $form->getConstraintViolationList();
    if($violations->count()) {
        $repr = $serializer->serialize($violations, 'json');
        return JsonResponse::fromJsonString($repr, 400);
    }
    // ...
} 
```

I know there's mixed feelings about using Forms in API endpoints but I think this could be a simple improvement.

Maybe something like (untested):

```php
    public function getConstraintViolations($deep = false, $flatten = true) {
        $errors = $this->getErrors($deep, $flatten);
        $constraintViolations = new ConstraintViolationList();
        foreach($errors as $error) {
            $constraintViolations->add($error->getCause());
        }
        return $errors;
    }
```

**Comment by stof** [comment]
I'm -1 for this. form errors might not all be coming from validator violations, so asking to return the form errors as validator violations is broken.

the ConstraintViolationListNormalizer is meant for cases dealing with the validator directly.
If you want to serialize form errors, it is better to build a dedicated normalizer (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Serializer/Normalizer/FormErrorNormalizer.php is one such example, but the format may not suit you)

**Comment by stof** [comment]
Thus, it would create a hard dependency between Form and Validator, while currently the integration between them is totally optional

**Comment by leevigraham** [comment]
bq. form errors might not all be coming from validator violations, so asking to return the form errors as validator violations is broken.

Yep I've just found this during some early testing. Two examples are CSRF validation and max file upload size.
