### ISSUE TITLE
Symfony\Bridge\Twig\Form\TwigRendererEngine causes dynamic 'extends expressions' to be evaluated twice.

### ISSUE THREAD

**Issue by Yoshix** [symfony/symfony#27541]
**Symfony version(s) affected**: (at least) v2.8 - v4.1

**Description**  

1. Have a template that extends another template using a dynamic expression.
2. Have that expression require something from the current context.  

        // Either by declaring `['needs_context' => true]`
        {% extends 'main.html.twig'|some_filter %}
  
        // or by passing some context variables.
        {% extends 'main.html.twig'|some_filter(someVar) %}

3. Use `{% form_theme form _self %}` somewhere in the template chain.  
4. Have a form rendered somewhere in that template chain.

If the above conditions are met, through

    Symfony\Component\Form\FormRenderer::searchAndRenderBlock
 
somewhere down the line

    Symfony\Bridge\Twig\Form\TwigRendererEngine::loadResourcesFromTheme

will be called, which internaly initializes the context to include global variables only (ignoring the actual context).

    $context = $this->environment->mergeGlobals(array());

  
This ultimately leads to the dynamic expression being evaluated twice. First with an incomplete and a second time with a complete context.

This is problematic because, if the expression:
- does *heavy work*, it cannot be cached as the first call is unreliable
- absolutely requires the context to be as expected it will produce unexpected errors

**How to reproduce**  

See above, or https://github.com/Yoshix/symfony_issue_27541

With the bug reproducer go to `/without-form` to have it function properly, go to `/with-form` to see the problem.

**Possible Solution**  

Pass down the correct context.

---

*updated* point 3, as it seems to only happen when `_self` is used as the form theme.

**Comment by stof** [comment]
which form theme do you use ?

If you use the current template as a form theme, that's totally normal, as the loading of the form theme will need to be able to resolve inheritance (and dynamic inheritance might then not work at all if it relies on the context as the context is different during form rendering).

If you need a special form theme for a form rendering, the best solution in this case is to store it in a different template (not using the dynamic inheritance of the page) instead of the current one. The {% form_theme %}` tag accepts any template as form theme, not only `_self` (which is a magic value referring to the name of the current template)

**Comment by Yoshix** [comment]
Thanks for your reply!

I understand why this is happening, though two things:

- I'll have to check whether in my production code I actually used the current template, but I believe I didn't and instead used a globally configured form theme (bootstrap with 2.8 probably).

- I'd atleast expected, if the filter is called twice, that both times the correct context would have been supplied. If that's not possible then maybe a note in the documentation would be appropriate? Or a flag indicating to the filter function that the context is not complete.

**Comment by stof** [comment]
The correct context is passed: the **current** context. During the rendering of a form itself (inside `form_widget(form)`, the context of the form theme is not the context of your own template (it cannot even access it).

**Comment by stof** [comment]
I'm not sure Twig allows to detect whether a template is using a dynamic parent. If it does, we could have TwigRendererEngine log a warning for such case.

**Comment by fabpot** [comment]
Closing as there is no more feedback.
