### ISSUE TITLE
Exception in kernel.terminal are not easy to debug

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#27544]
**Description**  
If an exception occurs in the "kernel.terminate" listerner:

1. The response is broken (see screenshot bellow) 
2. It's hard to understand what's happening. Even for me, it took me a moment to get what's happening. Actually in my project, I got 2 exceptions (one on kernel.request, and another one on kernel.terminate) ; That made it even harder to debug.

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/408368/41110014-aff75004-6a78-11e8-97ce-31448be9002c.png)

</details>

I created a small reproducer on SF4.1: https://github.com/lyrixx/test/commit/29ddcf5c6012433d6c2ea6e8d9f94039e76bcdb0
(yeah, the code is YOLO :) )

**Example**  
I don't know how we could fix that. May be we can add a special [workflow](https://github.com/symfony/workflow)  for error happening on kernel.terminate because they do are specials.

WDYT?

**Comment by nicolas-grekas** [comment]
Not sure what we can do here. Is the error logged? If you use FPM, you'd even not be able to see the error, because of fastcgi_finish_request. What is displayed in stderr in `php -S` mode? Is there a profiler page with the exception reported?
Honestly, there are some cases where either Symfony or PHP are is shuting down.

**Comment by fabpot** [comment]
Let's close. Using `kernel.terminate` is very dangerous and should be avoided at all costs. Here, the Messenger component helps a lot as we now have a core built-in way of doing things out of band.

**Comment by ogizanagi** [comment]
@fabpot : Out of curiosity, why do you think it is very dangerous and what would you think about https://github.com/symfony/symfony/issues/28646? Should we avoid doing it? That's cheap, but can be valuable on some projects.

**Comment by fabpot** [comment]
For #28646, I'm the one who suggesting it, so I'm fine with it as a poor man solution :)

**Comment by stof** [comment]
@ogizanagi `kernel.terminate` is meant to run the logic after the Response was sent. This means that we cannot provide any feedback about what is happening at that time (that's too late for sending feedback about failure)
