### ISSUE TITLE
Make NotBlank constraint convert value to string

### ISSUE THREAD

**Issue by wwwd3v** [symfony/symfony#27550]
Hi, in our app, we work with user contact DTOs rather than with plaintext:
```
$user->addContact(
    new Contact('email', 'a@b.com)
)
```
To get an email, you would normally have to:
```
$user->getContact('email')->getValue(); // a@b.com
```
But in order to simplify the API, the Contact utilizes a `__toString()` method:
```
(string) $user->getContact('email'); // a@b.com
```
**This actually plays out really nicely with String constraints:**
```
// DataTransformer transformed user input to instance of Contact

/**
 * @Constraints\Email
 * @Constraints\Length(max=256)
 *
 * @var Contact
 */
public $email;
```
This works beautifully, because all string constraints **automatically convert values to strings** before they continue with validation.

However, this will not work:
```
/**
 * @Constraints\NotBlank
 *
 * @var Contact
 */
public $email;
```
as NotBlank check is guided by this algorithm, which does not take into account the `__toString` method:
```
if (false === $value || (empty($value) && '0' != $value)) {
    // validation will fail
}
```
I think it would be really neat to enable the `__toString` check in NotBlank as well, do you not think?

I could prepare a PR if there is a will.

I believe philosophically it would make sense, as the goal of `NotBlank` is to determine whether a user has posted _nothing_. If an object has a string representation `""`, then that object indeed is _nothing_ from the perspective of the user input validation.

Thank you.

**Comment by iltar** [comment]
I don't agree with this. I think usage of `__toString` should be avoided at all cost. An object can't have a string representation unless it's a value object with only 1 value (more aiming at a struct). I've worked in far  too much code where `__toString` was implicitly used. Enabling the support of `__toString` as use-case, means more people will use it and more developers will feel the frustration of this kind of magic.

What about objects that already have a `__toString` for another purpose similar to this? Example, you have a contact object and a developer added `__toString` to return the slug value for a url (string value of the PK), how are you going to solve this for your `NotBlank` scenario?

If anything, you could probably propose an interface for this specific situation, or perhaps an option in the constraint (I think this would be the best). I see what you're trying to solve here, I'm just not sure if your proposed solution is a good idea.

**Comment by xabbuh** [comment]
For the records, I am 👎 on such a change. For me that's too much behaviour that is unexpected and can lead to hard to debug issues. I would rather be in favour of deprecating the silent `__toString()` support in the other validators instead.

**Comment by wwwd3v** [comment]
@xabbuh I think you are right in what you're saying about consistency. When you learn string constraints work with `__toString`, there is no reason to expect `NotBlank` does not work.

I do not share worries that @iltar does, I believe magic methods can be an enormous help if you know precisely what you're doing on a very limited scope. However, I do recognize now that my use case is one of those "not intended", which means it will probably be best if this remains in user land.

I am OK with having a custom constraint, I got confused because string constraint support this, they explicitly cast to string, which hinted it was a feature, and not something to evade.

Thanks for your comments anyway 👍

**Comment by iltar** [comment]
> I believe magic methods can be an enormous help if you know precisely what you're doing on a very limited scope

That's because _you_ are writing the code and you know how it _should_ work. Now if I were to join your company and I see your code, the amount of `wtf`'s per minute would rise tremendously, because I have no idea how it should work, why it works like that and why there's all kinds of magic being used. It's important to keep in mind that you won't always be the only developer using this code.

**Comment by wwwd3v** [comment]
@iltar I understand your point, I made sure my teammembers don't mind, we discuss these kinds of things in our company. 

To be honest, I feel this issue is unopinionated, I think it stands irrespective of what anyone thinks about magic methods. The point here was with consistency - there is no reason why some string-checking constraints should support `toString` operations and some shouldn't.

What I was proposing was to make things consistent and let people decide.

Peace ☮️

**Comment by iltar** [comment]
In that case, my vote goes for no support on `__toString` by Symfony, so if we want consistency (always good), it's better to deprecate this behavior in 4.2.
