### ISSUE TITLE
[Lock] The choice of a store name from env vars doesn't work

### ISSUE THREAD

**Issue by andsm** [symfony/symfony#27555]
**Symfony version(s) affected**: 4.1.0

**Description**  

> Symfony\Component\Cache\Exception\InvalidArgumentException: Unsupported DSN: semaphore.

semaphore/flock - error
redis/memcached dsn - ok

**How to reproduce**  
```
parameters:
    env(LOCK_STORE_DSN): 'semaphore'

framework:
    lock: '%env(LOCK_STORE_DSN)%'
```

**Comment by ronisaha** [comment]
This still not working! If we set `semaphore` or `flock` as `LOCK_STORE_DSN` value,  getting `Unsupported DSN: semaphore/flock.` error whiling using the lock service.

console output:

> [2019-07-02 01:02:16] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Unsupported DSN: semaphore." at vendor/symfony/cache/Adapter/AbstractAdapter.php line 143 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Unsupported DSN: semaphore. at  vendor/symfony/cache/Adapter/AbstractAdapter.php:143)"} []

Symfony version: 4.3.2

**Comment by xabbuh** [comment]
@ronisaha This looks like a configuration issue to me. The error mentions the Cache component.

**Comment by ronisaha** [comment]
@xabbuh This is because the factory used [Symfony\Component\Cache\Adapter\AbstractAdapter](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1586)

**Comment by ronisaha** [comment]
Any update on this issue?

**Comment by jderusse** [comment]
This should be fixed by https://github.com/symfony/symfony/pull/34043/files and release in Symfony 4.4

Could you have a try?

**Comment by ronisaha** [comment]
@jderusse  Tested in 4.4.4, it's working.
