### ISSUE TITLE
[LDAP] Ldap bind authentication does not load my user entity class but the core class symfony user

### ISSUE THREAD

**Issue by jfsenechal** [symfony/symfony#27554]
Hi

If the verification of the password is done on the provider sql it is well my class user which is charged
"AcMarche\Travaux\Entity\Security\User"
But if the check is done on the ldap is the class
"Symfony \ Component \ Security \ Core \ User \ User" which loaded

What's wrong in my config ? 

Thanks

`# security
security:
    providers:
        sql_provider:
            entity:
                class: AcMarche\Travaux\Entity\Security\User
                property: username
        ldap_provider:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(ACLDAP_DN)%'
                search_dn: '%env(ACLDAP_USER)%'
                search_password: '%env(ACLDAP_PASSWORD)%'
                default_roles: ROLE_USER
                uid_key: sAMAccountName

    encoders:
        AcMarche\Travaux\Entity\Security\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider: sql_provider
            form_login:
                use_referer: true
                remember_me: true
            form_login_ldap:
                provider: ldap_provider
                use_referer: true
                remember_me: true
                service: Symfony\Component\Ldap\Ldap
                dn_string: '%env(ACLDAP_DN)%'
                query_string: '(&(|(sAMAccountName=*{username}*))(objectClass=person))'
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
`

**Comment by iltar** [comment]
That's working as intended, because your security user has no relation to an entity. Entities are a database implementation. If you wish to change the user object, you'll have to implement a custom user provider: https://symfony.com/doc/current/security/custom_provider.html

But that doesn't change the fact that you should probably not implement this `UserInterface` on your entity: https://stovepipe.systems/post/decoupling-your-security-user

**Comment by jfsenechal** [comment]
With un UserProvider I have this error in my log

[2018-06-08 14:04:13] security.INFO: User has been authenticated successfully. {"username":"xxx"} []
[2018-06-08 14:04:13] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"xxx","provider":"AcMarche\\Travaux\\Security\\UserProvider"} []
Access denied, the user is not fully authenticated; redirecting to authentication entry point.

My provider
https://github.com/acmarche/apptravaux/blob/master/src/AcMarche/Travaux/Security/UserProvider.php

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
