### ISSUE TITLE
Performance issue with the "lint:xliff" command

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27564]
**Symfony version(s) affected**: all

**Description**  
The `lint:xliff` command is too slow.

**How to reproduce**  
I put the following on my Travis CI config:

```bash
$ ./tests/bin/console lint:xliff "src/Resources/translations"
```

But the build runs out of time ([see full details](https://travis-ci.org/EasyCorp/EasyAdminBundle/jobs/380098586#L622)):

```
No output has been received in the last 10m0s, this potentially indicates a
stalled build or something wrong with the build itself.

The build has been terminated.
```

**Additional context**  
I've run this command locally linting just 1 file and it was extremely slow. I share the Blackfire profile:

```bash
$ blackfire run ./tests/bin/console lint:xliff src/Resources/translations/EasyAdminBundle.en.xlf
```

Profile:

https://blackfire.io/profiles/5f1be513-3f01-414d-8759-11ae84a00ce3/graph

The problem seems to be in PHP's `DOMDocument::schemaValidate` but maybe we are doing something that makes it slow?

**Comment by nicolas-grekas** [comment]
> No output has been received in the last 10m0s

if we cannot make the function faster, we could at least output some progress bar so that Travis doesn't think we're freezed.

**Comment by stof** [comment]
> The problem seems to be in PHP's DOMDocument::schemaValidate but maybe we are doing something that makes it slow?

next step would be to profile the C code then.

**Comment by ZHB** [comment]
It appears that the W3C intentionally imposes a delay on the loading of DTDs, as seen here : https://www.w3.org/Help/Webmaster

> The W3C servers are slow to return DTDs. Is the delay intentional?
> Yes. Due to various software systems downloading DTDs from our site millions of times a day (despite the caching directives of our servers), we have started to serve DTDs and schema (DTD, XSD, ENT, MOD, etc.) from our site with an artificial delay. Our goals in doing so are to bring more attention to our ongoing issues with excessive DTD traffic, and to protect the stability and response time of the rest of our site. We recommend HTTP caching or catalog files to improve performance.

We can improve performances by loading http://www.w3.org/2001/xml.xsd in local file system with `libxml_set_external_entity_loader()`.

**Comment by stof** [comment]
OK, found the issue there. The XliffFileLoader has some special logic to use a local copy of the xml schema when validating the schema. But the XliffLintCommand does not use that logic (and so uses the remote copy). We should use the same logic in both cases (we could extract the `getSchema` implementation to an internal utility reused by both classes)

**Comment by stof** [comment]
Btw, the XliffLintCommand is also missing support for xliff 2.0 (unlike the loader). It does not select the schema.

**Comment by stof** [comment]
Suggestion: extract a Xliff (internal) utility, which would allow reusing both the version detection and the schema processing

**Comment by javiereguiluz** [comment]
@ZHB and @stof thanks for this great detective work! The problem is clear now. I'll try to send a fix based on Christophe suggestions. Thanks!
