### ISSUE TITLE
PHP7.1, Symfony4.1 & Apache2.4 broken together.

### ISSUE THREAD

**Issue by saurabh-mishrr** [symfony/symfony#27579]
I'm using 

> PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:55:21) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.1.17-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
> 

for Symfony4.1 with Apache2.4, while I'm running the app error log showing

> Uncaught TypeError: Return value of Symfony\\Component\\Dotenv\\Dotenv::load() must be an instance of Symfony\\Component\\Dotenv\\void, none returned in /var/www/html/project/vendor/symfony/dotenv/Dotenv.php:59\nStack trace:\n#0 /var/www/html/project/public/index.php(15): Symfony\\Component\\Dotenv\\Dotenv->load('/var/www/html/p...')\n#1 {main}\n  thrown in /var/www/html/project/vendor/symfony/dotenv/Dotenv.php on line 59

Please help.

**Comment by ismail1432** [comment]
Symfony 4 requires [PHP 7.1.3 or higher](http://symfony.com/doc/current/reference/requirements.html)

**Comment by saurabh-mishrr** [comment]
I'm using 7.1.17 that is higher than 7.1.3..

**Comment by xabbuh** [comment]
@ismail1432 is right. This is exactly the error you get when running PHP code that makes use of the `void` return type on PHP 7.0. You will need to investigate which process is not using your PHP 7.1 installation and update it too. Sadly, there is nothing we can do about that. So I am going to close. Thank you for understanding.

**Comment by stof** [comment]
@saurabh-mishrr make sure that your Apache setup is using the same PHP version than your CLI. You gave us the PHP version of your CLI, not of your webserver config

**Comment by saurabh-mishrr** [comment]
Thank you so much guys and I'm sorry too. I had installed php7.0 and php7.1 and didn't disable php7.0 module for apache.
