### ISSUE TITLE
Symfony Workflow, Symfony 4

### ISSUE THREAD

**Issue by rernesto** [symfony/symfony#27572]
Refer to [Related Entities Error](https://stackoverflow.com/questions/49265685/symfony-3-4-workflow-marking-stores).
I found this when I got same error and was looking for a solution.
Is pretty similar to errors I got when I migrated to PHP7 with Forms and entitites. I got a solution decoupling FORMS and Entities using DTO or using '?' (null) on returns type hints.

**Comment by stephanvierkant** [comment]
What's your question? Or is this a bug report?

**Comment by lyrixx** [comment]
@rernesto Hello, Could you update your issue to match this [issue template](https://github.com/symfony/symfony/issues/new?template=1_Bug_report.md) . Because I don't really understand your issue. Thanks

**Comment by stephanvierkant** [comment]
I suggest to close this issue. The related question has been deleted from StackOverflow.
