### ISSUE TITLE
Form issue on iOS due to missing action attribute

### ISSUE THREAD

**Issue by mweimerskirch** [symfony/symfony#27585]
**Symfony version(s) affected**: >= 2.8

**Description**  

With commit 130704387ab688fef3a29381fead9ce189fce8e4, the default twig form template was changed so that empty action attributes were removed. However, this leads to a problem in iOS. Forms without a submit button can no longer be submitted. Of course it's possible to override the default form template, but this problem might affect many developers, so it might be good to make it work as expected out of the box.

**How to reproduce**
Simple HTML example to try out in iOS:
 
Without an "action" attribute, iOS will show a "return" button on the keyboard, but users wont be able to submit the form:

```
<form>
 <input type="text">
</form
```

![form-without-action-attribute](https://user-images.githubusercontent.com/362092/41295171-2faa3426-6e5a-11e8-9796-9581aaa091ce.jpg)

With an "action" attribute (even an empty one), iOS will show a "search" button on the keyboard that allows the user to submit the form:

```
<form action="">
 <input type="text">
</form
```

![form-with-empty-action-attribute](https://user-images.githubusercontent.com/362092/41295172-2fc3eace-6e5a-11e8-8a9a-736b5f749a7d.jpg)

AFAIK this only affects iOS. Android shows an "enter" button in both cases and the forms submit just fine. On desktop browsers you can push the "enter" key and the forms also submit. 

**Possible Solution**  
This could be fixed by reverting Commit 130704387ab688fef3a29381fead9ce189fce8e4

**Comment by mweimerskirch** [comment]
@ismail1432 I absolutely agree that this is an iOS issue. But reverting the commit would still improve the developer experience ("DX"), because it would prevent the issue from appearing in Symfony applications.

**Comment by xabbuh** [comment]
I am going to close here as we conform to the HTML specs and this needs to be fixed in iOS. And of course this can still be customised on a per-project level.
