### ISSUE TITLE
Twig Environment part of the controller

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#27587]
**Description**  
I like that `Twig_Environment` could be part of the controller, the truth I found it a little tiring to have to inject `Twig_Environment` into every `constructor` of every `controller` to assign a simple variable to the view.

**Example**  
My current case is that I have a variable `menuActual` in my Template Base , the variable makes it active in the menu of my App, in other words, in each `constructor` and in each `controller method` I have to assign this variable with another value to tell it which menu should be activated.

**Comment by iltar** [comment]
You can use the `@Template` annotation for this, though I personally would like to see a feature that does something in the form of `return new Template('...', [...]);`, to avoid this direct coupling to the twig `Environment`.

**Comment by chiqui3d** [comment]
Thanks but it doesn't work for me.

The code:
` * @Template(vars={"menuActual": "users"}) 
`
also you have to import the template annotations, which is a bit exessive to assign a variable to the view.

**Comment by iltar** [comment]
```php
/**
 * @Template('your/template.html.twig')
 */
public function fooAction($arg1, $arg2)
{
    return ['arg1' => $arg1, 'arg2' => $arg2];
}
```

**Comment by chiqui3d** [comment]
Thank, but it doesn't solve my request.

**Comment by javiereguiluz** [comment]
Maybe you can:

* [Define a Global Twig variable](https://symfony.com/doc/4.0/templating/global_variables.html) and store a service in that variable to do some advanced logic to set the current menu item.
* [Write a custom Twig extension](https://symfony.com/doc/current/templating/twig_extension.html) to define that logic inside a Twig function that you can use in that template.
* If your URLs are structured in a consistent way, you can create a simple Twig fragment with some basic logic that determines the current menu item using the URL.

**Comment by chiqui3d** [comment]
Gracias Javier, but the **first** link you put me, is to assign the default value of the `menuActual` to `home`. That's already done.

**The second** could do a function, of course, but I think it would be too complex to assign a simple variable.

**Third**, Yes, I could do it without using symfony and using only Javascript, that's the easiest and fastest way.

But the **point** is that I find it too much to inject the `twig environment` over and over again into the constructor for a simple variable.

If I do a simple search in another framework for example laravel, I find this and super simple.

`View::share ( 'variable3', 'I am Data 3' );`

That's all, if you don't see it like I do, then nothing, Thank you anyway.

**Comment by javiereguiluz** [comment]
@chiqui3d I agree that injecting the Twig Environment in every controller constructor is too much. I never do that. My controllers always extend from the base controller, so I just do this:

```php
return $this->render('...', ['variable3' => 'I am Data 3']);
```

If you don't like this, you can also use the `@Template` annotation as @iltar said earlier:

```php
/** @Template() */
public function someMethod()
{
    // ...

    return ['variable3' => 'I am Data 3'];
}
```

**Comment by chiqui3d** [comment]
Okay, but as I say in my specific case, it doesn't help me, because I want to make a global variable in the constructor and in the methods also.

In the demo there is no BaseController, which for some large applications should be required and should be indicated as a good practice of symfony or any other framework.
Thank you anyway.

**Comment by javiereguiluz** [comment]
Controllers of the Demo app extend from AbstractController, which is the base controller that provides the useful shortcuts like `render()`. See for example: https://github.com/symfony/demo/blob/60b80cf271d6f83dcfbb8777544e6b89c3b4f828/src/Controller/BlogController.php#L37

I still think there's been a misunderstanding here: passing variables to the templates is as simple as returning them as the result of the controller execution. If you need to execute advanced logic to get the value of a variable in a template, then you must use services via Twig global variables or Twig functions or [embed controllers in a template](https://symfony.com/doc/current/templating/embedding_controllers.html).

In any case, we use GitHub to report Symfony bugs and discuss about new Symfony features, so for this kind of support questions is better to use: https://symfony.com/support We'll be glad to help you on Symfony Slack (`#support` channel or, if you prefer, `#symfony-es`). So, let's close this. Thanks!

**Comment by chiqui3d** [comment]
ok, thanks for all. yes it is possible that I have not explained myself well, here is the example of how I always repeat the same thing.

`
/**
 * @Route("/user", name="user_")
 */
class UserController extends BaseController
{

    public function __construct(\Twig_Environment $twig)
    {
        $this->twig = $twig;
        $this->twig->addGlobal('menuActual', "users");

    }
`

/**
 * @Route("/car", name="car_")
 */
class CarController extends BaseController
{

    public function __construct(\Twig_Environment $twig)
    {
        $this->twig = $twig;
        $this->twig->addGlobal('menuActual', "cars");

    }
`
But it's clear that I've taken a bad path. I'll forget about the constructor.

**Comment by stof** [comment]
Altering the state of Twig in the constructor is a bad idea IMO (any business logic in the constructor is a bad idea when using DI btw).

I'm not sure using a global variable to set which menu item is active is the best way. Mutating Twig globals may lead to hard-to-debug issues (what if both your constructors are executed for instance)

**Comment by chiqui3d** [comment]
Yes you're right, I've taken a wrong road, I just thought `Twig_Environment` was part of the controller a good idea.

thank you all very much.

**Comment by TomasVotruba** [comment]
@chiqui3d I do it the same way, just instead of Controller I use custom `GlobalVariablesTwigExtension`

https://github.com/TomasVotruba/tomasvotruba.com/blob/master/src/Twig/GlobalVariablesTwigExtension.php
