### ISSUE TITLE
Translator is required for form_widget even when tranlsation is disabled.

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony#27589]
**Symfony version(s) affected**: 4.1 and prior (since 6 years i think)

**Description**  
When the translation is disabled (and the translator component not even install) and use a ChoiceType input in your form, we get the following exception : 
`Uncaught PHP Exception InvalidArgumentException: "The helper "translator" is not defined."`

**How to reproduce**  
- Unistall translator component
- Disable translation in the framework.yaml
- Create a form with ChoiceType input
- Set the choice_translation_domain to false

**Possible Solution**  
In the file choice_widget_options.html.php on line 3, it would be nice to add a test on the existence of the translator component. Or check if the enable translator option in conf is set to false.

**Comment by xabbuh** [comment]
For anyone interested in working on this: We can register a kind of dummy translator if the Translation component is not enabled. You can take a look at #24358 where we implemented a similar approach for Twig-based form themes.

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/28523
