### ISSUE TITLE
A simpler way to override third-party bundle translations

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27599]
**Description**  
Make it simpler to override the translation files of third-party bundles.

**Example**  
If you want to override third-party bundle templates, you define them in:

```php
templates/bundles/<bundleName>/<templatePath>
// e.g. template/bundles/TwigBundle/Exception/error.html.twig
```

However, to override third-party bundle translations, you define them in:

```php
src/Resources/<bundleName>/translations/<translationFilePath>
// e.g. src/Resources/FOSUserBundle/translations/FOSUserBundle.es.yml
```

To be consistent with other parts of the framework, could we change this to the following?

```php
translations/bundles/<bundleName>/<translationFilePath>
// e.g. translations/bundles/FOSUserBundle/FOSUserBundle.es.yml
```

**Comment by stof** [comment]
the thing is, translations are not tied to a bundle at all. any bundle is free to provide translations in any translation domain.

To override translations from a third-party bundle, you can put translations in `translations/<translationFilePath>`

**Comment by stof** [comment]
I created https://github.com/symfony/symfony-docs/issues/9923 about improving the doc
