### ISSUE TITLE
File input display change after 4.1 update

### ISSUE THREAD

**Issue by Th3BiSh0p** [symfony/symfony#27592]
**Symfony version(s) affected**: 4.1

**Description**  
I've updated my symfony version on a project from 4.0.11 to 4.1, I'm using bootstrap_4_horizontal_layout form theme and all my file inputs display have changed to bootstrap custom file.
I don't think a framework update should change my input display like that.
Am I wrong ?

**Comment by Th3BiSh0p** [comment]
I guess so, yes

**Comment by xabbuh** [comment]
Thank you, I am closing here then since we already have #27477 (the issue that #27478 is going to fix).
