### ISSUE TITLE
symfony/class-loader v3.4.11 requires php ^5.5.9|>=7.0.8 

### ISSUE THREAD

**Issue by ajita-asthana** [symfony/symfony#27597]
I am working on Laravel . And I get this error after running 
docker run --rm -v $(pwd):/app composer/composer install command.

Can anyone help me out with this?

**Comment by webignition** [comment]
What version of PHP do you have installed in that environment?

**Comment by ajita-asthana** [comment]
Version 5.6.30

**Comment by stof** [comment]
please provide the full composer output.

**Comment by derrabus** [comment]
Does your project' composer.json file have a block like this one?

```JSON
"config": {
    "platform": {
        "php": "x.x.x"
    }
}
```

If yes, what version is specified there?

**Comment by ajita-asthana** [comment]
![screen shot 2018-06-18 at 10 44 33 am](https://user-images.githubusercontent.com/16641779/41519246-a1272bca-72e4-11e8-8814-46bb2717b0ff.png)
Here is the code

**Comment by derrabus** [comment]
That looks good. As @stof said, we would need the full composer output here.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
