### ISSUE TITLE
Allow unqouted string with spaces in dotenv

### ISSUE THREAD

**Issue by spajak** [symfony/symfony#27594]
symfony/dotenv shows error: 
**A value containing spaces must be surrounded by quotes**
if it encounters a variable like this:
`XDEBUG_CONFIG=remote_host=192.168.0.186 remote_enable=1`
But with quotes xdebug **fails** to parse this variable correctly!
I'm using this `.env` with docker-compose.

Please add support for unquoted strings

**Comment by nicolas-grekas** [comment]
Hello, the syntax used in the `.env` file must follow what the standard Linux shell allows.
Spaces in values are not allowed by it, so we cannot add it here neither.

>  But with quotes xdebug fails to parse this variable correctly!

How did you quite the value? Does it work with `XDEBUG_CONFIG="remote_host=192.168.0.186 remote_enable=1"`?

**Comment by spajak** [comment]
No it doesn't work. Quotes are not stripped from the value, the value is shown with quotes in PHP environment, and xdebug fails to process that.
This value is read by `docker-compose` and passed to the container with the following option:
```
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
```
So I guess it's `docker-compose` not stripping the quotes..

**Comment by sstok** [comment]
> So I guess it's docker-compose not stripping the quotes..

Bingo, docker-compose does not follow the Unix environment variables standard. There are actually multiple issues reported about this to the Docker team (don't have time to look these up now).

**Comment by spajak** [comment]
Ok, can be closed now

**Comment by nicolas-grekas** [comment]
Will be fixed by https://github.com/docker/compose/pull/6923 on docker-composer side.
