### ISSUE TITLE
cache:clear fails when deploying to Dokku

### ISSUE THREAD

**Issue by guidolodetti** [symfony/symfony#27595]
**Symfony version(s) affected**: 4.1 (4.0?)

**Description**  
Starting from Symfony 4, when deploying to Dokku the composer after install script fails with `cache:clear`.

**How to reproduce**
Deploy to Dokku with the standard `scripts` section in `composer.json`.
```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    }
```
**Possible Solution**  
My current workaround is to add the missing folder before the script execution:
```
    "scripts": {
        "bug-fix-scripts": [
            "mkdir -p /tmp/build/templates"
        ],
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@bug-fix-scripts",
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@bug-fix-scripts",
            "@auto-scripts"
        ]
    }
```

**Additional context**  
This is the error thrown:
```
       Generating optimized autoload files
       ocramius/package-versions:  Generating version class...
       ocramius/package-versions: ...done generating version class
       Executing script cache:clear [KO]
       [KO]
       Script cache:clear returned with error code 1
       !!
       !!   // Clearing the cache for the prod environment with debug
       !!   // false
       !!
       !!
       !!  In Filesystem.php line 101:
       !!
       !!    The "/tmp/build/templates" directory does not exist ("/tmp/build/templates"
       !!    ).
       !!
       !!
       !!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
       !!
       !!
       Script @auto-scripts was called via post-install-cmd
To xxxx
 ! [remote rejected] feature/symfony4 -> master (pre-receive hook declined)
```

**Comment by nicolas-grekas** [comment]
Similar to #27240, so same questions: Does it work if you create the missing directory? If yes, why hasn't it been created before? Are you using Flex or the standard edition maybe?

**Comment by guidolodetti** [comment]
@nicolas-grekas the only way to make it work is to create the `/tmp/build/templates` directory in the post-install scripts. Honestly I don't know why it is not created before because I am using Dokku which is based on Docker. We are using Flex!
I will try another Symfony 3 → 4 migrations and tell you if it works.

**Comment by nicolas-grekas** [comment]
@guidolodetti do you have some info? Shall we close?

**Comment by xabbuh** [comment]
I am closing here for now given the lack of feedback. But we can of course reopen when we have some more information. Feel free to leave a comment here.
