### ISSUE TITLE
Add new translation files without clearing the cache

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27600]
**Description**  
Don't require to clear cache when adding new translation files.

**Example**  
If you add a new translation file, the app won't use it unless you clear the cache entirely. This is cumbersome and inconsistent with other parts of the framework.

Is there any tech constraint that prevents us from checking if there are new files in the `translations/` dir and load them automatically (in `dev`)?

**Comment by welcoMattic** [comment]
Hi! I had a real-life case for this feature with [php-translation/symfony-bundle](https://github.com/php-translation/symfony-bundle).

With @damienalexandre and @lyrixx, we opened an issue to explain [our case here](https://github.com/php-translation/symfony-bundle/issues/198).

**Comment by stof** [comment]
Well, the handling of translation files is done in 2 steps, both with caching:

- the list of files is built by the DI extension and stored in the service definition (cached by the container cache). This layer should already handle invalidation of the container cache when you add a new translation
- the translation catalogue is cached by the translation component. The different loaded files are used as resources for cache invalidation there. But I don't think the cache gets invalidated if the list of resources in the Translator gets changed compared to the one when dumping the cache.

I think it could be possible to add a new resource in the message catalogue cache checking freshness based on the list of resources in the translator (but it might be hard if this list of resources is maintained by a different object. I don't remember how the architecture works exactly in 4.1 as this changed over time in Symfony)

**Comment by stof** [comment]
@welcoMattic your issue is different, as this is not about a debug mode, but about a prod mode. Your issue is related to the DI-level caching, because you tried to avoid clearing the container cache.
But moving the detection of translation files are runtime rather than at compile-time may have an impact on performance (and would require changing entirely the way resources are working in the component if you don't want to run the finder on each instantiation, as a directory resource would not be associated to a domain and locale).

**Comment by nicolas-grekas** [comment]
There's something I don't get here. @javiereguiluz and @stof gave what I understand as conflicting sentences:

> Is there any tech constraint that prevents us from checking if there are new files [...] (in dev)?
and 
> This layer should already handle invalidation of the container cache when you add a new translation

Who is right?
From what I understand, @welcoMattic has a different issue than the one described by @javiereguiluz, since it is prod-only (if @stof is right?)

**Comment by apfelbox** [comment]
@nicolas-grekas I can confirm that newly added translation files in `dev` won't work until you manually clear the cache. So the comment from @stof describes the supposed state and not the current state.

Tested in 4.1.0

**Comment by stof** [comment]
I'm not describind the supposed state. If you read my first comment, you will see that the second bullet point precisely describes where the invalidation is not done properly.
