### ISSUE TITLE
Auth token not set correctly when using fetch

### ISSUE THREAD

**Issue by stenno** [symfony/symfony#27619]
**Symfony version(s) affected**: 4

**Description**  
When calling a custom login route with ES6 fetch(), the auth token get set to the wrong(?) session. 
Calling the same route with a 'normal' HTTP request from the browser address bar sets the token fine.
Used code: https://hastebin.com/itovadutub.php

**How to reproduce**  

Create a 'User' entity which implements \Serializable and Symfony\Component\Security\Core\User\UserInterface. Create an instance of that user using Fixtures.

Create a controller route "dologin". 
In the route, obtain the created user from the entity repository and create the user session token like this:
```
        $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
        $this->get("security.token_storage")->setToken($token);
        $session->set("_security_main", serialize($token));
```
Create another route "dumpuser" which just dumps the current security token:
```
        $loggedInUser = $this->get("security.token_storage")->getToken();
        dump($loggedInUser);
```

Call the "dologin" route from the browsers address bar, then call route "dumpuser"
You will see the security token set to the correct user as expected.

Call the "dologin" route from ES6 fetch():
```
fetch("/dologin", {
            method: "POST",
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
        })
```
Call the route "dumpuser" again. You will see the security token set to "anon.".

**Possible Solution**  

**Additional context**

**Comment by apfelbox** [comment]
That's because `fetch()` doesn't send any cookies by default. You have to enable it explicitly.

See the article in MDN: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

![2018-06-17 at 15 37](https://user-images.githubusercontent.com/1032411/41508394-665729b4-7244-11e8-8fd3-ce12b597650b.png)

(your browser probably doesn't yet support the change in the last sentence).

So just add them explicitly:

```js
fetch("/dologin", {
    method: "POST",
    credentials: "include", // <-- !
    headers: {
        "Accept": "application/json",
        "Content-Type": "application/json"
    }
})
```

**Comment by stenno** [comment]
setting "credentials" as suggested by @apfelbox solved the issue. I will close this issue now.
