### ISSUE TITLE
Error Cannot access private property Error::$previous ( On every Exception page )

### ISSUE THREAD

**Issue by juju95** [symfony/symfony#27613]
**Symfony version(s) affected**: 4.1.0

**Description**  
Error about $previous property as private requested by the exception Listener

**How to reproduce**  
I have the error directly from a fresh install, each type of exception return this problem ( Page not found, route error, Cache error, every error is replaced with this Exception private property error

```
(1/1) ErrorCannot access private property Error::$previous
--
in ExceptionListener.php line 77
at ReflectionProperty->setValue(object(Error), object(CacheException))in ExceptionListener.php line 77
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent))in ExceptionListener.php line 41
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
at call_user_func(array(object(ExceptionListener), 'onKernelException'), object(GetResponseForExceptionEvent), 'kernel.exception',object(TraceableEventDispatcher))in WrappedListener.php line 104
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(EventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in TraceableEventDispatcher.php line 141
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in HttpKernel.php line 219
at HttpKernel->handleException(object(CacheException), object(Request), 1)in HttpKernel.php line 77
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 188
at Kernel->handle(object(Request))in index.php line 37
```

Do i need to install a specific sub package ? ( still a little lost about the new packages function of symfo 4 to find what is required to install... sorry in advance if it is the problem here ... )

**Comment by lyrixx** [comment]
hello @juju95,

The stack trace does not match [the code in version 4.1](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L77)

Did you change some code in the vendor dir?

Could you paste the exception in plain text format ?
You can get it on the exception page, the 3rd tabs named "stack traces".

Thanks

**Comment by juju95** [comment]
No i didn't change anything to vendor ( i just deleted the directory and  made a composer install to generate it again same result ) 
Yes i pasted it in plain text, here is a screenshoot

And yes i get it on the exception page ( no debug toolbar ) no profiler, just the plain error page like on the screen 

and i get it for every type of exception ( here is a Cache problem, i was installing it ) but i get it for 404 errors, routing problems etc. 

My problem is the exception message i s always about this $previous property of "Error"
I i really want to find the real problem, i need to check the hanfleException line of the debug trace ( In the screenshoot, i have a CacheException for example

![image](https://user-images.githubusercontent.com/3393980/41474950-b2010b7e-70bd-11e8-8e72-9b408f6d37d2.png)

**Comment by juju95** [comment]
( Sorry for my bad english )

**Comment by lyrixx** [comment]
ah ok, for such exception there is not plain text tabs. Sorry about that.

**Comment by xabbuh** [comment]
I am unable to reproduce your issue. Could you create a small project that allows to do so?

**Comment by nicolas-grekas** [comment]
Could this happen when using the `Error` class from symfony/polyfill-php70?
https://github.com/symfony/polyfill/blob/master/src/Php70/Resources/stubs/Error.php
Which version of PHP do you have @juju95 ?

**Comment by Waynestay** [comment]
I have the same issue on symfony 4.1 trying to enable exceptions on FriendsOfSymfony/FOSRestBundle (v2.3) . I have a standard install with web skeleton, fosrest bundle & jms/serializer (v2.4) bundle installed and running php 7.1.8. No changes to vendors or other conflicting packages as far as I can tell. 
As soon as I enable exceptions in Fos_rest, I get the error as above. This is regardless of the exception handler but for the record I have tested using the defaults:

exception:
        enabled: true
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true    

If I switch enable to false, I don't get the error and have also tested with customized error handlers but the exception seems to happen before any fos handlers are invoked. 

(1/1) ErrorCannot access private property Error::$previous
--
in ExceptionListener.php line 77
at ReflectionProperty->setValue(object(Error), object(NotFoundHttpException))in ExceptionListener.php line 77
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent))in ExceptionListener.php line 41
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
at call_user_func(array(object(ExceptionListener), 'onKernelException'),object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))in WrappedListener.php line 104
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception',object(EventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener),object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception',object(GetResponseForExceptionEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in TraceableEventDispatcher.php line 141
at TraceableEventDispatcher->dispatch('kernel.exception',object(GetResponseForExceptionEvent))in HttpKernel.php line 219
at HttpKernel->handleException(object(NotFoundHttpException), object(Request), 1)in HttpKernel.php line 77
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 188
at Kernel->handle(object(Request))in index.php line 37

**Comment by xabbuh** [comment]
Could any of you two create a small example application that allows to reproduce your issue?

**Comment by Waynestay** [comment]
I have set up a default project here: https://github.com/Waynestay/rest_demo_error.git
 Default get request is  'http://127.0.0.1:8000/api/list' - set to throw error

**Comment by xabbuh** [comment]
@Waynestay Thank you 👍 I can reproduce your issue now.

Status: Reviewed
