### ISSUE TITLE
Very weird performance found

### ISSUE THREAD

**Issue by waghanza** [symfony/symfony#27612]
Hi there,

I'm working on benchmarking project, https://github.com/tbrand/which_is_the_fastest.

The main purpose is raw comparison (no battle wanted :stuck_out_tongue_closed_eyes: ).

I have made an implementation of `symfony` => https://github.com/tbrand/which_is_the_fastest/pull/249 which goal is to have `3` endpoints :
* `GET /` => returning an **empty** body
* `GET /user/:id` => returning the **id** given as url param
* `POST /user` => returning an **empty** body

I find a very **huge** `throughput`. Could any one from the community check my code https://github.com/waghanza/which_is_the_fastest/tree/php_symfony/php/symfony ?

Regards, :heart:,

**Comment by ismail1432** [comment]
Sorry but where is the issue ?
Here we're talking about bug or features...
You can find [help](https://symfony.com/community) here.
Regards

**Comment by theofidry** [comment]
Hi, first you would need to optimize the Composer autoloader and since they are not used you can remove the dev dependencies:

```
composer dump-autoload --classmap-authoritative --no-dev
```

And warmup the cache:

```
bin/console cache:warmup
```

And make sure your application (and the cache warmed up) are in `prod` mode

**Comment by B-Galati** [comment]
Symfony performance guide could help too -> https://symfony.com/doc/current/performance.html

**Comment by javiereguiluz** [comment]
@waghanza you may find inspiration and useful resources in https://github.com/phpbenchmarks They publish PHP benchmarks similar to what you want to do. See http://www.phpbenchmarks.com/en/comparator/frameworks.html

And we invite you to [join Symfony's Slack](https://symfony.com/slack-invite) where you can find people willing to help you and the `#support` channel in case you have specific bugs or issues to solve.

As others said, we use GitHub for feature requests and bug reports, so let's close this issues and if you find some Symfony bug, please create a new issue. Thanks!

**Comment by nicolas-grekas** [comment]
I asked for this issue to be created on https://github.com/tbrand/which_is_the_fastest/pull/249#issuecomment-397590750
I think we can have a better look at this, as there is a "marketing" topic related. We can say "just configure correctly", but then we shouldn't cry if we're not top perf in the report.

**Comment by nicolas-grekas** [comment]
Would anyone like to have a better look and help @waghanza?
