### ISSUE TITLE
Review the code and config used in TechEmpower benchmarks

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27624]
**Symfony version(s) affected**: 4.1

**Description**  
The latest TechEmpower benchmark results look wrong for Symfony.

Symfony is faster and faster on each version. Independent benchmarks such as [PHP Benchmarks](http://www.phpbenchmarks.com/en/comparator/frameworks.html) show this clearly. However, in the latest round of [TechEmpower Benchmarks](https://www.techempower.com/benchmarks/) something bad happened. Symfony performance plummeted. For example, in the "Plain Text" benchmark, we went from 11,000 req/sec in Round 15 to 5,000 req/sec in Round 16.

We should carefully review the benchmark code and the server config used in https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/symfony

I'm also pinging @joanhey because you appear in most of the [recent commits made to Symfony benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/commits/master/frameworks/PHP/symfony) so maybe it's easier for you to double check the recent changes. Thank you!

**Comment by nicolas-grekas** [comment]
Thank you for opening this issue @javiereguiluz 
Ping @raziel057 also since you provided SF3/4 support.

**Comment by raziel057** [comment]
It's very strange because all PHP Frameworks have better performances (particulary silex) in Round 16 except Symfony...

**Comment by raziel057** [comment]
From current dockerfile (https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/symfony/symfony.dockerfile), we have: 

```RUN composer install --quiet```

where before (https://github.com/TechEmpower/FrameworkBenchmarks/blob/99cdff30a280749ad794a451e054dff9d68f7c6d/frameworks/PHP/symfony/setup.sh) we had: 

```php composer.phar install --no-dev --no-interaction --no-progress --optimize-autoloader --classmap-authoritative```

Is it normal?

Config files for PHP / ngnix are the same in symfony and silex so I think all is ok from this side. I see nothing special that can explain those bad results.

**Comment by javiereguiluz** [comment]
@raziel057 thanks for reviewing all this. Not adding `--optimize-autoloader` and `--classmap-authoritative` definitely introduces a big performance penalty ... but the difference is so huge, that there might be something else too.

**Comment by nicolas-grekas** [comment]
Interesting comment on the topic if anyone would like to have a look:
https://github.com/the-benchmarker/web-frameworks/pull/249#issuecomment-428925518

**Comment by joanhey** [comment]
Hola Javier,

The commits are for optimize the php stack and then pass it to all the frameworks. But not for change the code in the frameworks.
From round 15 to 16 the gain in req/s is amazing in all php benchs, only symfony is slower.

Definitely you will change the `composer install`  with ` --no-dev --no-interaction --no-progress --optimize-autoloader --classmap-authoritative`. The plain text bench use up to 16,384 concurrent connections so any small change is noticeable.

But also Laravel and silex use only `composer install` (very bad) and have better results in round 16 for the plain text bench.

Framework | Round 15 | Round 16
------------ | ------------- | ---------
Laravel | 3,583 | 7,741
Silex | 11,458 | 22,461

So I recommend that you will also check the code in the bench.

Please, also add persistent db connection for better results in all db benchs.

I try my best to change all php frameworks to use persistent db connections, but I didn't find info for symfony (and some more php fws).

Why is it so difficult to find how to do persistent db connections in symfony ?
It's really beneficial for any application with high load. All the errors in the bd benchs for symfony are for not use persistent db connection.

If I observe anything strange when optimize the php stack, I will send you a ping  @javiereguiluz .
When you need more information only ping me.

TIP:  Check the changes in the continuous benchmark in https://tfb-status.techempower.com before the next round.

Saludos.

**Comment by joanhey** [comment]
Hola
I think that found the problem, after change all composer to `composer install --no-dev` for faster builds.

The `APP_ENV` was incorrect in the dockerfiles.
Before `ENV APP_ENV=prod`  now  `ENV APP_ENV prod`.

And for that with this code in the core:
```
if (!isset($_SERVER['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
    }
    (new Dotenv())->load(__DIR__.'/../.env');
}
```
Never found the `APP_ENV` because was `APP_ENV=prod`, and use the Dotenv class for every request.

I will send you the results of the next run.

Please remember to **add persistent db connection** for better results in all db benchs.

**Comment by raziel057** [comment]
@joanhey For the persistent db connection, you should try to add ``ATTR_PERSISTENT: true`` in options like shown bellow.

```yml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        options:
            ATTR_PERSISTENT: true
```

But it seems it's not recommended for PHP projects as I can read here, so I'm not sure it's a good thing to add:
https://meta.wikimedia.org/wiki/Why_persistent_connections_are_bad

**Comment by raziel057** [comment]
Sorry in fact you need to use 12 rather than ATTR_PERSISTENT (which correspond to PDO::ATTR_PERSISTENT). But in fact it's not supported by Doctrine PDOConnection:

It generates the following issue:
``
Exception thrown when handling an exception (Symfony\Component\Config\Exception\FileLoaderLoadException: Warning: PDO::setAttribute(): SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS cannot be used with persistent PDO instances
``

**Comment by joanhey** [comment]
That persistent connections are bad is a thing of the past.
The article is from 2003 and using mysql db extension (do not exist in actual php versions).

Actually PDO and internally mysqlnd that fixes this problem and more. Also use Asynchronous, non-blocking queries.
https://dev.mysql.com/downloads/connector/php-mysqlnd/

It's a typical misconception in the php community.

And yes. you can't use PDO::ATTR_STATEMENT_CLASS with PDO persistent connections. But it's possible do the same without PDO::ATTR_STATEMENT_CLASS. Very bad for Dontrine :(

**Comment by raziel057** [comment]
@joanhey From the last version https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/symfony/symfony.dockerfile I can see you didn't added ``--optimize-autoloader`` to composer install. Is it normal?

Maybe you could replace:
``RUN composer install --no-dev --quiet``

With:
```RUN composer install --no-dev --quiet --optimize-autoloader --classmap-authoritative```.

**Comment by joanhey** [comment]
Will be added, but to all the frameworks.
I think is sufficient with the` -o`.

**Comment by raziel057** [comment]
@joanhey Ok cool. Using ``-o`` alias should be enough here. You can also use ``-a`` as this automatically enables Level 1 class map optimizations. But maybe it's better to be verbose.

**Comment by raziel057** [comment]
@joanhey Hello, I just noticed that php project are not starting anymore in the continuous benchmark:
https://tfb-status.techempower.com/raw/results.2018-12-20-15-21-40-145.json

In completed you can see: 
ERROR: Problem starting symfony-raw
ERROR: Problem starting slim
ERROR: Problem starting kumbiaphp
ERROR: Problem starting php-pgsql-raw
ERROR: Problem starting cakephp
ERROR: Problem starting laravel
...

It's strange given the fact it's working on Travis. Do you have any ideas?

**Comment by joanhey** [comment]
Was a problem downloading php7.3, and affect all frameworks that use it.
https://tfb-status.techempower.com/unzip/results.2018-12-23-15-04-49-016.zip/results/20181220223653/php-raw7/build/php-raw7.log

Sometimes there are external problems: dockerhub, launchpad, ....
I hope the next run will be OK.

**Comment by joanhey** [comment]
With doctrine, like you said it isn't possible to use persistent connection.
But there are symfony-raw, could you change it for use persistent db connections.

**Comment by joanhey** [comment]
Yes, anyone can change any setting.
The settings from [this page](https://symfony.com/doc/current/performance.html#performance-use-opcache) and more are already in the php.ini.

The only settings that are not changed are: 
```
; php.ini
; maximum memory that OPcache can use to store compiled PHP files
;opcache.memory_consumption=64 ; default Mb
opcache.memory_consumption=256

; maximum number of files that can be stored in the cache
;opcache.max_accelerated_files=2000 ; default
opcache.max_accelerated_files=20000
```
I think that the defaults are big enough for the benchmark.

For a big application with a lot of controllers, models and external libs (image manipulation, create pdf, send email, ....) it is really recommended change that settings.

Actually symfony4 use less than 1Mb for the plaintext and json bench. And for sure than use less than 2000 files.

For now all the frameworks use the same config for php, with enough big values.

**Comment by Simperfit** [comment]
Can we close this one @javiereguiluz

**Comment by raziel057** [comment]
Without the ability to set persistent connections on Doctrine the benchmarks gives bad results and lot of errors. We need to wait for Doctrine Dbal 3.0 to be released to fix this.

**Comment by kaznovac** [comment]
some recommended performance php extensions were missing (opcache, mbstring, intl)

updated to symfony 4.3 and made a pull request (TechEmpower/FrameworkBenchmarks#4979)

**Comment by kaznovac** [comment]
@raziel057 , @javiereguiluz , @nicolas-grekas 

Care to take a look?
Particularly if you have insights in these questions 
https://github.com/TechEmpower/FrameworkBenchmarks/pull/4979#issuecomment-518963631

**Comment by Simperfit** [comment]
@nicolas-grekas @javiereguiluz Since it has been merged on the techEmpower project is this ok ?

**Comment by kaznovac** [comment]
here are the results from continuous benchmark:
https://www.techempower.com/benchmarks/#section=test&runid=26a79c95-5eec-4572-8c94-dd710df659d7&hw=ph&test=fortune&l=zik073-f&w=zik0zf-zik0zj-1r

- much better in jsonserialization, plaintext ~4x more requests served
- db-tests still look grim (too much failed tests, but at least symfony-orm now completes muliple queries test)

**Comment by jderusse** [comment]
I had a deep look into this issue, but didn't found the reason:
- only DB tests are failling (plaintext and json are fine)
- not all request are failling (about 30% are failing)
- works fine on my machine (if you want to test : `./tfb --test symfony`) either with local test AND inside the provided vagrant setup.

If someone want to give a look, output is available here https://tfb-status.techempower.com/unzip/results.2019-09-03-04-13-26-519.zip/results/20190830094757/symfony/db/raw.txt

The first result is interesting : not an heavy test (8 connections), the server respond quickly (<10ms) but return `3064` errors.

**Comment by raziel057** [comment]
We need to wait Doctrine 3 to ne releva ses to be able to set persistent DB connection. See https://github.com/symfony/symfony/issues/27624#issuecomment-482799763

**Comment by kaznovac** [comment]
I had more stable results when prod doctrine cache config was absent.
can someone with more experience take a look at that config `prod/doctrine.yaml`

**Comment by jderusse** [comment]
don't get how persistent connection will avoid error (note the failling test with 8 connection without timeout)

**Comment by jderusse** [comment]
last bench result is available. https://www.techempower.com/benchmarks/#section=test&runid=6949a3d4-db58-4f2a-970f-08607f5c876a&hw=ph&test=fortune&l=zik073-v

**Comment by nicolas-grekas** [comment]
https://www.techempower.com/benchmarks/#section=test&runid=ca07ce5b-053c-4d75-b204-53eb5a6c5aeb&hw=ph&test=update&c=6&d=d&o=8
https://www.techempower.com/benchmarks/#section=test&runid=ca07ce5b-053c-4d75-b204-53eb5a6c5aeb&hw=ph&test=fortune&l=zik073-v&c=6&d=d&o=e
