### ISSUE TITLE
Cannot resolve argument - errored service locator

### ISSUE THREAD

**Issue by bigi123** [symfony/symfony#27625]
**Version : Symfony 4.1.0**

After doing development my service locator for HttpFoundation was errored and for that service cannot be injected. Is that bug or how I can solve this error? 

**Error log:** 

`Cannot resolve argument $file of "App\Controller\OrdersController::index()": Cannot autowire service ".service_locator.SD3r19_": it references class "Symfony\Component\HttpFoundation\File\UploadedFile" but no such service exists.`

**HttpFoundation errored service ID:** 

`.errored..service_locator.SD3r19_.Symfony\Component\HttpFoundation\File\UploadedFile`

**Code:** 

```
 class OrdersController extends Controller
{
    /**
     * @param Request $request
     * @param UploadedFile $file
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(Request $request, UploadedFile $file )
    {...} 
} 
```

**Comment by xabbuh** [comment]
I am not sure I understand what you are trying to achieve here. The `UploadedFile` class is not meant to be used as a service, but acts as a wrapper around files that are submitted by the user as part of the request. What service locator are you referring to here?

**Comment by nicolas-grekas** [comment]
Is there an ArgumentResolver that know how to inject a `UploadedFile` into actions?
The error message should be enhanced, it shouldn't tell about the locator, which is internal detail.

**Comment by bigi123** [comment]
@nicolas-grekas so based in your referenced issue is that bug?

**Comment by nicolas-grekas** [comment]
The error message is buggy, but the error itself is legit, this is not how you get access to uploaded files.

**Comment by bigi123** [comment]
@nicolas-grekas ok, thank you.

**Comment by chalasr** [comment]
> Is there an ArgumentResolver that knows how to inject a UploadedFile into actions?

IMHO this is what the error message should looks like, currently it covers one kind of argument being service. Not sure we can do anything, closing as fixed.
