### ISSUE TITLE
Simplify some parts of the functional tests

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27627]
**Description**  
The code needed to [click links](https://symfony.com/doc/current/testing.html#links) or [submit fomrs](https://symfony.com/doc/current/testing.html#forms) in functional tests looks a bit verbose.

The steps used to get the `Link` object may be OK when using this [inside the DomCrawler component](https://symfony.com/doc/current/components/dom_crawler.html#links) ... because you can do advanced things like calling the `getUri()` on the `Link` object. However, when using this inside a Symfony app, it looks unnecessary.

**Example**  
## Links

**Before:**

```php
$link = $crawler->selectLink('Click here')->link();
$client->click($link);
```

**After:**

```php
$client->click('Click here');

// if click() arguments can't be changed, then
// $client->clickLink(...)
```

## Forms

**Before:**

```php
$buttonCrawlerNode = $crawler->selectButton('Register');
$form = $buttonCrawlerNode->form();
$form = $buttonCrawlerNode->form([
    'my_form_name[name]'    => 'Fabien',
    'my_form_name[subject]' => 'Symfony rocks!',
], 'DELETE');
$client->submit($form);
```

**After:**

```php
$client->submit('Register', [
    'my_form_name[name]'    => 'Fabien',
    'my_form_name[subject]' => 'Symfony rocks!',
], 'DELETE');

// if submit() arguments can't be changed, then
// $client->submitForm(...)
```

We could also change how things work and take the forms via their names (if they don't have a name, then use the traditional way). The above example would look like this:

```php
$client->submit('my_form_name', [
    'name'    => 'Fabien',
    'subject' => 'Symfony rocks!',
], 'DELETE');
```

**Comment by Aerendir** [comment]
Yes, it is really verbose and hiding this logic in helper methods seems a good thing to me. Anyway, if someone wants more control can continue to use the actual ways. +1
