### ISSUE TITLE
Deprecate one of the ways of overriding translation files

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#27636]
**Description**  
Translation files are not related to bundles but to translation domains (see https://github.com/symfony/symfony-docs/pull/9935/files for a recent doc improvement about this).

However, Symfony allows [overriding translation files in these 3 ways](https://symfony.com/doc/4.0/translation.html#translation-resource-file-names-and-locations):

1. `<your-project>/translations/`
2. `<your-project>/src/Resources/<bundle-name>/translations/`
3. `<bundle-src>/Resources/translations/`

`1.` and `3.` look OK, but `2.` looks unnecessary because translations are related to domains, not bundles. Should we deprecate it?

**Comment by fabpot** [comment]
We need to keep 2 so that people can override third-party bundle translations, right?

**Comment by FabienPapet** [comment]
What about just keeping one ?

**Comment by stof** [comment]
@fabpot no. The main `translations` folder can be used for that. Translations are not tied to a bundle, but to a domain. Reusing the same key in the same domain in the main location will override it.

The only advantage of `%kernel.project_dir%/src/Resources/<bundle-name>/translations/` IMO is that it makes it clear that you are overriding a third-party translation (and so you might want to remove the file when you remove the third-party bundle). This can be useful for the `validators` domain overrides for instance. But putting comments in your main validators file to identify third-party overrides could also be used for that.

**Comment by stof** [comment]
@FabienPapet we cannot keep only one. We need 3 to allow bundles to provide translations. and we need 1 to allow the project to provide translations (the project does not define a bundle for its own source in a Flex app)

**Comment by stof** [comment]
For reference, `2.` was added in Symfony 2.1 (by #4030) based on the feature request in #4018.

The main argument at that time was consistency with overriding templates. But loading templates and loading translation files works totally differently (you don't refer to a translation resource when using the translator)

**Comment by deguif** [comment]
I'm taking this one #eufossa

**Comment by deguif** [comment]
This can be closed, as it was implemented in https://github.com/symfony/symfony/pull/28997
