### ISSUE TITLE
Simplify the form submission

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#27638]
**Description**  
At the moment when you want to submit a form in a controller most of the time you should call 3 methods `handleRequest($request)` , `isSubmitted()` and `isValid()` see [documentation](http://symfony.com/doc/current/form/direct_submit.html) and if you call `isValid()` without calling `isSubmitted()` before it will throw an [Exception](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L734)

I know it's little magic but the simple idea is to aggregate the 3 methods in 1. 
the method will handle the request, check if the form isSubmitted and if it's valid.

**Example**  
```
public function add(Request $request)
{
//create $form
//do some stuff
if($form->isCorrect($request)) {
// Do some stuff with $form
}
```

The method name is a simple example. I'am ready to work on if you're OK
I think the community have already spoken about that, but I'm not sure,  WDYT ?

**Comment by BoShurik** [comment]
How to separate not submitted forms with not valid in that case?

**Comment by ismail1432** [comment]
We not remove existing method just create a new one « helper »

**Comment by nicolas-grekas** [comment]
What about providing a callback to a form, that would be called when it is submitted, valid, etc.?

**Comment by HeahDude** [comment]
Like a listener to `POST_SUBMIT`? Not worth it IMHO.

**Comment by xabbuh** [comment]
Not sure if it would be worth it to add some kind of helper method to the `ControllerTrait` in the FrameworkBundle (like below), but I don't see it as part of the Form component.

```php
public function handleFormSubmissionRequest(FormInterface $form, Request $request, callable $onSuccess = null, callable $onFailure = null): void
{
    $form->handleRequest($request);

    if ($form->isSubmitted()) {
        if (null !== $onSuccess && $form->isValid()) {
            $onSuccess($form);
        }

        if (null !== $onFailure && !$form->isValid()) {
            $onFailure($form);
        }
    }
}
```

**Comment by javiereguiluz** [comment]
It's always interesting to see how others solved the same problems you have. So here is for example how do they process forms in Django:

```python
def get_name(request):
    # method is POST -> process the submitted form
    if request.method == 'POST':
        form = NameForm(request.POST)

        if form.is_valid():
            # process the data in form.cleaned_data as required...

            return HttpResponseRedirect('/thanks/')

    # method is GET -> display the initial form
    else:
        form = NameForm()

    return render(request, 'name.html', {'form': form})
```

**Comment by HeahDude** [comment]
I'm not a fan of using callbacks, we will end up with anonymous functions in controllers instead of an explicit API.

But I do like the idea of using the controller trait to get this helper, what about:
```php
// trait
public function isFormValidForRequest(FromInterface $form, Request $request): bool
{
    return $form->handleRequest($request)->isSubmitted() && $form->isValid();
}

// controller
public function action(Request $request): Response
{
    $form = $this->createForm(MyType::class);

    if ($this-> isFormValidForRequest($form, $request)) {
        // do stuff and redirect
    }
    
    // render
}
```

**Comment by nicolas-grekas** [comment]
Something like that @xabbuh yes. By doing this king of logic in the Cache component, we made it much easier to use, and if fact it became much more than a helper as this is now backed by a first class interface and interesting features have been built on top. Maybe applicable here also?

**Comment by symcaster** [comment]
Based on the idea of @xabbuh:

```php
public function handleForm(string $formType, callable $preSubmit, callable $onSuccess)
{
    $form = $this->createForm($formType);

    // Try to get the $request automatically (autowiring, container...)
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        return $onSuccess($form);
    }

    return $preSubmit($form);
}
```

In controller, there is only:

```php
public function myAction()
{
    return $this->handleForm(MyFormType::class, function (FormInterface $form) {
        return $this->render('form.html.twig', ['form' => $form->createView()]);
    }, function (FormInterface $form) {
        return $this->redirectToRoute('success');
    });
}
```

**Comment by javiereguiluz** [comment]
I'm afraid that I agree with @HeahDude ... the proposals don't look much better than the current situation (and considering that it would obsolete all our docs, tutorials, screencasts, etc.) I'm not sure it's worth it.

**Comment by Pierstoval** [comment]
Why not simply `$form->isSubmittedAndValid($request);`? Pretty straightforward, and can call the three methods at once (`handleRequest($request)`, `isSubmitted()` and `isValid()`)?

**Comment by jvasseur** [comment]
The problem I see with `isFormValidForRequest` is that it's both a mutator (via `handleRequest`) and an accessor via `isSubmitted` and `isValid`. People that doesn't know what is under this this method could try to call it multiple times (and get an error because the form is already submitted).

I'm not sure if there is really something to do here but if there was I would be more in favor of combining the `createForm` and `handleRequest` into one method (you rarely have something to do between the two calls) and maybe `isSubmitted` and `isValid` in another one.

**Comment by HeahDude** [comment]
>Why not simply $form->isSubmittedAndValid($request);? 

@Pierstoval because it would make the shortcut be a form interface contract, keeping it in the framework bundle trait is better IMO, since the request object is not tied to the form.

**Comment by ismail1432** [comment]
I am happy to see all proposals, IMO the @HeahDude solution (add a simple method in the `ControllerTrait` ) is the good one

**Comment by Pierstoval** [comment]
Then `$this->formIsSubmittedAndValid($request)` in the `ControllerTrait` seems the best option then 👍

**Comment by ismail1432** [comment]
Good point @lyrixx !
I hope that we will merge your work !

**Comment by iltar** [comment]
A lot of points from this discussion are leading towards the form handler bundle I've worked on, perhaps it's worth checking it out? https://github.com/hostnet/form-handler-bundle

It lets you create thin controllers by extracting any logic to the handler, which can have an "onSuccess" flow and an "onFailure" flow (configurable).

```php
// example taken from the readme
class YourController extends Controller
{
    public function formAction(Request $request, MyEntityUser $user)
    {
        $handler = $this->get('hostnet.form_handler.factory')->create(MyFormHandler::class);

        if (($response = $handler->handle($request, new MyFormData())) instanceof RedirectResponse) {
            return $response;
        }

        // regular or in-valid flow
        return $this->render->renderView('/your/form.html.twig', [
            'form' => $handler->getForm()->createView()
        ]);
    }
}
```

**Comment by lyrixx** [comment]
@iltar In the readme, there are no mention of binding a form to an existing object. Is it intended?
To me it's really weird... I except something like 
```php
        $handler = $this->get('hostnet.form_handler.factory')->create(MyFormHandler::class, $myObject);
```

**Comment by iltar** [comment]
@lyrixx your form is bound to a specific object, you configure which form this is in your handler. At the moment of creation, you might not yet (want to) have your data object: https://github.com/hostnet/form-handler-component/blob/87cbc8444ec20a0c66bc8e05e79a102fb7cf4b0d/src/FormHandler/Handler.php#L92-L104

I guess it could be possible that way, but it was written like this because you handle a specific data set rather than just handling a handler.

**Comment by HeahDude** [comment]
@lyrixx I missed that one too, what about reopening? :)

**Comment by logarytm** [comment]
On a related note, how about reporting an error in `isSubmitted()` if `handleRequest()` hasn't been called? I don't forget to check `isSubmitted()` before `isValid()`, but I frequently find myself not calling `handleRequest()`, which fails silently. I suspect there are some edge cases lurking here, though, and I am aware that could be a BC break.

**Comment by ismail1432** [comment]
The job was done https://github.com/symfony/symfony/pull/24576 I close this issue thanks @lyrixx

**Comment by ismail1432** [comment]
I reopen the issue because the code was revert in https://github.com/symfony/symfony/pull/29813/commits/2be1987ad1dca580a0dfc03e407c8a6343dd47cf

**Comment by xabbuh** [comment]
This issue was opened more than a year ago. We had a lot of ideas, but none of them was convincing enough. Therefore I suggest that we close here as we weren't able to agree on a solution. We could still reconsider if someone comes up with a great new idea that receives enough support.
