### ISSUE TITLE
Missing session values after upgrade to 4.1

### ISSUE THREAD

**Issue by nospor** [symfony/symfony#27640]
**Symfony version(s) affected**: 4.1

**Description**  
Hi, after upgrade from 4.0.7 into 4.1 I have an issue: I do few ajax requests at the same time. Only first ajax works fine. Every another is losing its session values. it only happens with AJAX which are called at the same time. If I add eg. 100 miliseconds delay between calling ajax then all works fine. 

**Additional context**

**Comment by dmaicher** [comment]
I'm afraid without a way for us to reproduce the issue we cannot really help here.

which session handler are you using? native php?

**Comment by RomulusED69** [comment]
Did you think to uncomment these lines in your framework.yaml?
session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

I had a similar issue when i upgraded

**Comment by nospor** [comment]
@dmaicher I think I told you a way how to reproduce it: Run few AJAX at the same time. If I add some delay then it works so this is apparently a problem with reading session files at the same time. This behaviour I have on 4 different servers and only after upgrade to Sf4.1

I use native Symfony session. I didnt introduce nothing by myself.

@RomulusED69 I didnt have that section in my framework.yml file at all. But I added it and it was the same. Then I uncommented it and again the same :(

**Comment by nospor** [comment]
@RomulusED69 so your problems are gone now? And only by commenting that section? You did nothing more?

**Comment by awiech** [comment]
Any news on this?
@nospor Did you find a way to fix your problem?

**Comment by nospor** [comment]
@awiech no, unfortunately not :( I still wait and hope someone if SF team will fix it

**Comment by awiech** [comment]
@nospor It seems, that I'm experiencing the same problem.

I've found something that works for me: In web_profiler.yaml, set toolbar to false.
My scenario is working now. 

But not yet sure why the toolbar is causing the problem

**Comment by nospor** [comment]
I have the same problem without toolbar as well :(

**Comment by awiech** [comment]
@nospor Try changing the session fixation strategy to NONE.
In security.yml:
session_fixation_strategy: none

**Comment by nospor** [comment]
@awiech thank you very much. Seems that fix the problem :)
