### ISSUE TITLE
Not wanted Web Profiler Toolbar link color css override

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#27658]
**Symfony version(s) affected**: v4.0.11

**Description**  

If I put some CSS rules with a body classes, it will apply on the web profiler toolbar.

**How to reproduce**  

```sass
body.logon {
  a:not(.btn) {
    color: map_get($project-colors, 'red');

    &:hover {
      text-decoration: underline;
    }
  }
}
```

And create a template with `<body class="logon">`

You will have something like this:

![image](https://user-images.githubusercontent.com/1698357/41666607-2841a3de-74ab-11e8-88a6-1db10761caa9.png)

I'm pretty sure it's related to the body class case, because I have another global color definition for `a` links and it does not affect the toolbar.

**Comment by stof** [comment]
Well, you final selector is `body.logon a:not(.btn)`. That has a higher specificity than the rules defined in the WDT styles. So it wins over them.

the WDT being in your page, CSS rules will indeed impact them. I don't know of a way to isolate the WDT from your page (using an iframe to render the toolbar is likely to break things entirely)

**Comment by Soullivaneuh** [comment]
> I don't know of a way to isolate the WDT from your page

I'm not a CSS expert, but inline css on the bar would do the trick, would not do? :thinking: 

Or maybe some `!important` tag, but it's quite ugly.

Maybe my sass code could be better too, but I don't know how to do otherwise.

**Comment by stof** [comment]
But we would also have to reset **all** styles coming from your CSS (and there are thousands of CSS properties). So inline styles would become huge (and unmaintainable).
And then, they would also win over the WDT styles (making it impossible to use CSS cascading features in the WDT, as well as hover styles).
`!important` suffers from most of these issues (we could still use some of the CSS features by applying `!important` on *all* WDT styles).

Thus, inline CSS styles are as ugly as `!important` IMO, and they are not compatible with CSP.

> Maybe my sass code could be better too, but I don't know how to do otherwise.

First step to reduce the specificity would be to use `.logon` instead of `body.logon`. That might be enough to go below the specificity of the WDT styles in some cases (not sure for this one though).

another idea could be to apply `logon` class not on `<body>` but on a `<div>` wrapping all your own HTML (but the WDT would be injected after this div, not inside it, and so not match the rule).
And you could also accept the fact that the link in the WDT goes red. That's not totally broken.

**Comment by ro0NL** [comment]
Could https://www.w3schools.com/cssref/css3_pr_all.asp help?

**Comment by stof** [comment]
no, because the more specific rule would still allow setting the color on the button over WDT styles resetting with `all`.

**Comment by Soullivaneuh** [comment]
@stof I will try your two suggestion and give a feedback, thanks.

> And you could also accept the fact that the link in the WDT goes red. That's not totally broken.

Nah, I'm perturbed with that. :stuck_out_tongue_winking_eye:

**Comment by ro0NL** [comment]
could it be related to the fact WDT styling is applied on class level, opposed to id. The latter seems to have higher precedence.

https://jsfiddle.net/kvh0wubd/

**Comment by Soullivaneuh** [comment]
Good catch @ro0NL!

It seems to be indeed better to rely on an id.

**Comment by Soullivaneuh** [comment]
For my case, using `.logon` instead of `body.logon` on my sass file *partially* solve the issue.

Links under boxes are blue again, but the underline effect on hover is still present on link under the `.sf-toolbar-block` divs.

I made things simpler by adding an id on my first layout div: `<div id="logon" class="container">` and rely on it for my CSS custom rules.

I let the issue open. I think the @ro0NL's case is interesting to give a try. :+1: 

Feel free to close if you think nothing more have to be done here.

**Comment by javiereguiluz** [comment]
The thing we could try is to apply `all: initial !important;` to all the important elements of the debug toolbar and see if that overrides any external style applied to it. Any volunteer to test this? Thanks!

**Comment by alcalyn** [comment]
I already used the `all: initial` / `all: unset` trick as described here: https://stackoverflow.com/a/31317986/2960951

But it also reset a lot of css default rules, like `box-sizing`, `display: block` of paragraph, titles, divs, headers, the appearance of radio buttons... Here is how the full css reset I used looks like:

``` sass
// Full reset styles
& {
    all: initial;
    * {
        all: unset;
    }
}

// Normalize
*, ::before, ::after {
    box-sizing: content-box;
}

h1, h2, h3, h4, h5, h6, div, header, footer {
    display: block;
}

input[type="button"], button {
    box-sizing: border-box;
}

input[type="radio"] {
    appearance: radio;
    -moz-appearance: radio;
    -webkit-appearance: radio;
    display: inline-block;
}

footer {
    padding: 0;
}

a {
    cursor: pointer;
}
```

This code is actually used in a website with a lot of visits. I use this to fully isolate css of a plugin that displays popins on many websites, and prevent websites which are displaying popins "break" popins style with their css rules.

It works well but IMHO, it is a big thing for something that impacts someting in dev environment only.

For your use case, you could avoid adding a class on `<body>` tag, and instead adding your class on another tag, like:

``` html
<body>
    <main class="logon">
    </main>
</body>
```

With the css rule `main.logon {}`. What do you think ?

**Comment by alcalyn** [comment]
Assuming that links color can be too easily overriden by application css, this PR set a stronger precedence for links css only. https://github.com/symfony/symfony/pull/27758

**Comment by soullivaneuh** [comment]
I'm sorry, but I still have the issue with `v4.2.5`:

![profiler_link_override](https://user-images.githubusercontent.com/1698357/58110566-10754880-7bf0-11e9-850c-ba68e8a9d2dc.png)

```css
a:not(.btn):not(.close):not([data-dt-idx]):not(.page-link), button:not(.btn):not(.close) {
    color: #2f333d;
    -webkit-text-decoration: underline dotted #e14a4b;
    text-decoration: underline dotted #e14a4b;
    transition: all 0.3s ease-in-out;
}
```

The color is also overriding the link on sub-content like ajax list.
