### ISSUE TITLE
ExpressionLanguage->evaluate( ) has return type `string` in doc block but returns mixed

### ISSUE THREAD

**Issue by Jeroeny** [symfony/symfony#27652]
**Symfony version(s) affected**: 4
**symfony/expression-language version**: 4.0.0

**Description**  
About line: 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ExpressionLanguage/ExpressionLanguage.php#L63 
https://github.com/symfony/expression-language/blob/master/ExpressionLanguage.php#L63

This php doc line states that the return type of `evaluate` is a `string`. However it's not always a `string`. For example when the expression evaluates to `true` the return type will be a `boolean`. Now I am doing strict type comparisons with the result of the evaluation and true / false. But my code quality checks correctly states that according to that documentation, such a comparison (e.g. `$result === true)`) will always return false because a string is expected. 

**How to reproduce**  
`` (new ExpressionLanguage())->evaluate($condition, $input) === true; `` would always return false according to the doc block. 

**Possible Solution**  
Replace `string` in the docblock with either `mixed` or the exact types that can be returned like `string|bool|int`

**Additional context**  
I can create a pull request if my statement is correct. Or is this intended?

**Comment by xabbuh** [comment]
This looks indeed like we need to update the docblock.
