### ISSUE TITLE
Feature Request: Allow to pass an array of fields to `allow_extra_fields` in Form

### ISSUE THREAD

**Issue by pascalwacker** [symfony/symfony#27660]
**Description**  
Currently the Form component in Symfony has the option to allow additional fields by setting `allow_extra_fields` to true (http://symfony.com/doc/current/reference/forms/types/form.html#allow-extra-fields).
As of today, you can only specify a boolean either true or false. I'd propose to, besides having just booleans, also allow passing an array of strings as value. This would work as a mixture of both options, by allowing all fields, whose names are specified in that array, but still forbid all others. This would give devs a finer granularity in what should be allowed in forms and what not.

**Example**  
Currently we can only set a form to accept all or none additional fields. Ex. `$this->createFormBuilder(null, ['allow_extra_fields' => true])`, With this proposal, we could pass something like `$this->createFormBuilder(null, ['allow_extra_fields' => ['foo', 'bar']])`. The form would then accept fields with the name `foo` and `bar` but still reject others, like `baz`.

**Comment by stof** [comment]
What is the use case for that ?

**Comment by pascalwacker** [comment]
Only allowing specific additional fields in a form, for example: `g-recaptcha-response` which is used by [reCAPTCHA](https://developers.google.com/recaptcha/docs/verify) but still don't allow arbitrary form inputs to be added

**Comment by unckleg** [comment]
Great feature, 'll improve form data processing & validation.

**Comment by pascalwacker** [comment]
Glad you like the idea. In this case, I'll see, if I find the time to write some code for it this weekend.

**Comment by unckleg** [comment]
@pascalwacker If you don't find time I'd like to help with PR for this feature :dagger:

**Comment by pascalwacker** [comment]
@unckleg it seemed to be a quick fix and I already made a pull request https://github.com/symfony/symfony/pull/27692

If you do find the time to look at it, I'd be glad for feedback or if you see room for improvement, let me know.

**Comment by xabbuh** [comment]
I am closing here as the related pull request was closed.
