### ISSUE TITLE
grouping in MoneyType not working with bootstrap 4

### ISSUE THREAD

**Issue by morrning** [symfony/symfony#27671]
**Symfony version(s) affected**: 4.1.0

**Description**  

symfony form field type (MoneyType) grouping not work with bootstrap 4 
**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by javiereguiluz** [comment]
@morrning if it's a design error, please add to your description a screenshot of the problem; it it's a code error, please include the error message. Thanks!

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
