### ISSUE TITLE
[Form] choice prefix option doesn't work on ChoiceType object with expanded to true

### ISSUE THREAD

**Issue by Steefler35** [symfony/symfony#27673]
**Symfony version(s) affected**: 3.4

**Description**  
Using ChoiceType object with expanded option to true, the choice prefix option is not working.

**How to reproduce**  
```
$builder->add('field', ChoiceType::class, array(
      'choices' => array(0, 1, 2),
      'choice_prefix' => 'test',
      'expanded' => true,
));
```
![image](https://user-images.githubusercontent.com/40465462/41721785-285a5dfe-7567-11e8-882a-6e8bf1e6a4f9.png)

**Comment by xabbuh** [comment]
It seems that you are using some third-party librabry/bundle which adds this option. But since the Symfony core itself does not provide a `choice_prefix` option I am going to close here. Thank you for understanding.

**Comment by Steefler35** [comment]
Sorry, I was not on the good repo, I did it too fast.
