### ISSUE TITLE
Request.getScheme() return http with X_FORWARDED_PROTO https

### ISSUE THREAD

**Issue by cesco69** [symfony/symfony#27677]
**Symfony version(s) affected**: 4.0.10

**Description**  
`Request.getScheme()` return `http` with `X-Forwarded-Proto` header on  `https`

**How to reproduce**  
make sure the php  `$_SERVER` array has:
```php
$_SERVER['APP_ENV']                 prod
$_SERVER['APP_DEBUG']               0
$_SERVER['TRUSTED_PROXIES']         172.16.0.0/12
$_SERVER['HTTP_X_FORWARDED_FOR']    XXX.XXX.XXX.XXX
$_SERVER['HTTP_X_FORWARDED_HOST']   my.website.com
$_SERVER['HTTP_X_FORWARDED_PORT']   443
$_SERVER['HTTP_X_FORWARDED_PROTO']  https
```
make sure the HTTP Headers has:

```
X-Forwarded-For     XXX.XXX.XXX.XXX
X-Forwarded-Host    my.website.com
X-Forwarded-Port    443
X-Forwarded-Proto   https
```
in `src/public/index.php` put:

```php
if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}
```
carete a new `/src/Controller/TestController.php`

```php
class TestController 
{
    public function index(Request $request)
    {
        $response = new Response();
        $response->setContent(  $request->getScheme() );
        return $response;
    }
}
```

the output is

```
http
```
but the expected output is
```
https
```

**Additional context**  

~~`Request ->getClientIp()` works and return the correct `X-Forwarded-For` ipaddress~~

i'm on Apache with [mod_remoteip](https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html) enabled and this settings:

```
# for mod_remoteip
RemoteIPHeader X-Real-Ip
RemoteIPInternalProxy 172.16.0.0/12
# for symfony
SetEnv TRUSTED_PROXIES 172.16.0.0/12
```

**Comment by nicolas-grekas** [comment]
Does TRUSTED_PROXIES support *`.0.0/12` IPs or only fixed IPs? Can you check?

**Comment by cesco69** [comment]
`TRUSTED_PROXIES` works because `Request->getClientIp()` return the correct `X-Forwarded-For` ipaddress

**Comment by stof** [comment]
Well, what is `$_SERVER['REMOTE_ADDR']` in your case ?

**Comment by cesco69** [comment]
`$_SERVER['REMOTE_ADDR']` is the ipaddress of the reverse proxy (traefik on docker)

**Comment by cesco69** [comment]
Update... 

i have made a test in a local environment with apache

in vhost.conf set:

```
SetEnv TRUSTED_PROXIES 127.0.0.0/8
    
RequestHeader set X-Forwarded-For     "127.0.0.11"
RequestHeader set X-Forwarded-Host    "my.website.com"
RequestHeader set X-Forwarded-Port    "443"
RequestHeader set X-Forwarded-Proto   "https"
```

`$request->getScheme()` return  "https" !

but on production with this setting

SetEnv TRUSTED_PROXIES 172.16.0.0/12

`$request->getScheme()` return  "http" !
