### ISSUE TITLE
`File` validation size format is always in binary (IEC) format, ignoring the `binaryFormat` option

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#27682]
**Symfony version(s) affected**: 3.x, 4.x

**Description** 
According to the [docs](https://symfony.com/doc/3.4/reference/constraints/File.html#binaryformat), setting the `binaryFormat` option on the `File` validation constraint should report all sizes in the decimal (SI-prefixed, as in kB, MB, GB etc.) format. However, the sizes will still be reported in binary (IEC, as in KiB, MiB, GiB etc.) format, completely ignoring the `binaryFormat` configuration.

By setting `binaryFormat=false` I'd expect the `suffix` to be `MB` instead of `MiB`.

Since the history of `megabyte` (MB) and `mebibyte` (MiB) isn't already confusing enough, here's some additional reading material:
- https://en.wikipedia.org/wiki/Mebibyte
- https://en.wikipedia.org/wiki/Megabyte

**How to reproduce**  
Given the following `php.ini` config:

```ini
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 2M
```

and the following validation code:

```php
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Asserts;

$INI_ERROR_MESSAGE = "Max Size: {{ limit }} {{ suffix }}";
// For the convenience of this example code we're using the `Validator` service since I can't just instantiate the `FileValidator` and call it directly as I need to inject an `ExecutionContextInterface` etc.
$validator = $this->container->get("validator");
$fakeFile = new UploadedFile(\tempnam(\sys_get_temp_dir(), 'file-validator-test-'), 'originalName', 'mime', 0, \UPLOAD_ERR_INI_SIZE);

$constraintWithBinaryFormatFalse = new File();
$constraintWithBinaryFormatFalse->binaryFormat = false;
$constraintWithBinaryFormatFalse->uploadIniSizeErrorMessage = $INI_ERROR_MESSAGE;

$constraintWithBinaryFormatTrue = new File();
$constraintWithBinaryFormatTrue->binaryFormat = true;
$constraintWithBinaryFormatTrue->uploadIniSizeErrorMessage = $INI_ERROR_MESSAGE;

$constraintWithBinaryFormatNull = new File();
$constraintWithBinaryFormatNull->binaryFormat = null;
$constraintWithBinaryFormatNull->uploadIniSizeErrorMessage = $INI_ERROR_MESSAGE;

$errorsWithBinaryFormatFalse = (string)$validator->validate($fakeFile, $constraintWithBinaryFormatFalse);
$errorsWithBinaryFormatTrue = (string)$validator->validate($fakeFile, $constraintWithBinaryFormatTrue);
$errorsWithBinaryFormatNull = (string)$validator->validate($fakeFile, $constraintWithBinaryFormatNull);

dump($errorsWithBinaryFormatFalse, $errorsWithBinaryFormatTrue, $errorsWithBinaryFormatNull);
```

and the results looking something like:

![validator output](https://user-images.githubusercontent.com/439899/41768714-50878030-760d-11e8-918e-1e742cea724f.jpg)

**Possible Solution**  
Make the reported size format depend on the `binaryFormat` option:
- https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Constraints/FileValidator.php#L60
- https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Validator/Constraints/FileValidator.php#L60

**Comment by jfredon** [comment]
The value `2M` configured in php.ini file is *2 Mi* in reality: http://php.net/manual/en/faq.using.php#faq.using.shorthandbytes

> By setting binaryFormat=false I'd expect the suffix to be MB instead of MiB.

Since `FileValidator` don’t print rounded value and don’t print value with more that 2 decimals, the error message will not show 2,09 MB nor 2,097152 MB but 2097152 bytes.

More generally, if the constraint is defined in binary format (KiB, MiB, GiB etc.) and the message is displayed in decimal format (kB, MB, GB), almost all the time, the unite used for display the value will be the byte due to the way how the value is formatted to be precise and readable.

I'm not sure it's more legible but it will be more standardized.
Would it be a functioning that you would find more acceptable?

**Comment by keichinger** [comment]
> Since `FileValidator` don’t print rounded value and don’t print value with more that 2 decimals, the error message will not show 2,09 MB nor 2,097152 MB but 2097152 bytes.

That's totally fine and I don't mind the rounding :)

> More generally, if the constraint is defined in binary format (KiB, MiB, GiB etc.) and the message is displayed in decimal format (kB, MB, GB), almost all the time, the unite used for display the value will be the byte due to the way how the value is formatted to be precise and readable.

I agree but isn't that the reason why the `binaryFormat` option even exists? :)

> I'm not sure it's more legible but it will be more standardized.
> Would it be a functioning that you would find more acceptable?

Honestly, I'm not too sure whether I understand you correctly: Do you want to unify the unit being displayed in the error message to *always* show the same?
