### ISSUE TITLE
[DI] Deprecate non-string default envs

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#27680]
**Symfony version(s) affected**: 4.1

**Description**  
Currently it's allowed to do define a scalar value for a default env parameter, e.g. `env(SOME): 1.5` (opposed to its string value`"1.5"`) while that's not possible with real env vars (hence we added the prefix processors). It's a trap and as such I think we should deprecate non-string defaults, and force string values in 5.0.

This way we can safely imply a default `string:...` processor again, and cast to i.e. float using its dedicated `float:...` processor. It was reverted in #27470 to preserve BC (see #27455), but i tend to agree with @stof in https://github.com/symfony/symfony/pull/27470#discussion_r196678923 this is not correct.

cc @nicolas-grekas 

edit: this also requires to forbid setting prefixed defaults, which is possible today but not handled as such. I'd keep this possibility closed until then... today those are silently ignored.

**Comment by nicolas-grekas** [comment]
We should allow `null` at least. We should be sure this solves a real-world issue. Doing it for the sake of it isn't enough a reason IMHO.

**Comment by ro0NL** [comment]
> We should allow null at least. 

Forgot to mention that, but yes totally :)

Moreover, i realized #27470 introduces a small discrepancy. In case of "no prefix" during compile-time we now preserve the actual value, however during runtime the "string" prefix is still forced:

https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Component/DependencyInjection/Container.php#L391

and

https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1888
