### ISSUE TITLE
[Stopwatch][RFC] Add currently used memory and support peak usages

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#27693]
**Description**  

**memory_get_usage**

Currently, the `Stopwatch` component uses the class `StopwatchPeriod` to save the result of `memory_get_usage(true)` ([source code](https://github.com/symfony/stopwatch/blob/master/StopwatchPeriod.php#L34)).

As per [PHP documentation](http://php.net/manual/en/function.memory-get-usage.php):

> memory_get_usage — Returns the amount of memory allocated to PHP

And this is what it states about the `true` parameter passed to the function ([`real_usage`](http://php.net/manual/en/function.memory-get-usage.php)):

> real_usage
> Set this to TRUE to get total memory allocated from the system, including unused pages. If not set or FALSE only the used memory is reported.

This means two things:

1. It returns the amount of memory used in the moment it is called;
2. If `real_usage` is set to `true` it returns the amount of system memory allocated to PHP, not the amount of memory of the allocated system memory used by the script.

With an example, if I have a script that consumes a lot of memory, assuming I call `memory_get_usage(true)` (NOTE the `true` - the `real_usage`) this happens:

1. Call 1: 30MiB
2. Call 2: 32MiB
3. Call 3: 100MiB
4. Call 4: 100MiB
5. Call 5: 100MiB
...

**But it may be possible that during the "Call 4"**, once finished the code that consumes a lot of memory, **the consumption of memory lowered to a lower value than the reported 100MiB, for example to 70MiB**.

Why? Because 100MiB is the amount of memory allocated to PHP (`real_usage` by PHP, not by the script itself that may be consuming less memory than the allocated amount).

To measure the amount of memory consumed by the script, we should call the `memory_get_usage` function with the `real_usage` param set to `false` (or omitted).

During profiling or logging, this value is way more useful because it permits to fine grain the code to spot memory consumption (also if the allocated memory is more than the memory actually consumed).

**memory_get_peak_usage**

The same discourse is valid for the second useful function: [`memory_get_peak_usage`](http://php.net/manual/en/function.memory-get-peak-usage.php).

> memory_get_peak_usage — Returns the peak of memory allocated by PHP

Also, this function can be called with the parameter [`real_usage`](http://php.net/manual/en/function.memory-get-peak-usage.php) set to `true` or to `false`:

> Set this to TRUE to get the real size of memory allocated from system. If not set or FALSE only the memory used by emalloc() is reported.

Honestly, I still haven't clear what it means "only the memory used by emalloc() is reported".

But anyway it is useful to have this information at hand.

**WHAT TO DO**

Add 3 more properties (with getters) to [`StopwatchPeriod`](https://github.com/symfony/stopwatch/blob/master/StopwatchPeriod.php#L30-L35):

```php
private memoryUsed = memory_get_usage(false);
private memoryPeak = memory_get_peak_usage(true);
private memoryUsedPeak = memory_get_peak_usage(false);
```

What do you think?

**Comment by javiereguiluz** [comment]
I'd say that "real_usage" is very important in some situations ... but for the debug toolbar, it's better to not display that metric. The debug toolbar is only for "Symfony things", so displaying the memory consumed just by this script (i.e. by the Symfony app) is more realistic to me.

**Comment by Aerendir** [comment]
@javiereguiluz, Exactly! The stopwatch component, in its simplicity, is a really powerful tool to make. First profile of a script without instrument a more complex tool like Blackfire.

But it’s powerfulness is limited by the fact that it can measure only one memory metric out of the four available.

Aging the other three at hands is something way more powerful that makes the Stopwatch component useful in other situations other than the Console or the Debug toolbar!
