### ISSUE TITLE
Receiving an object with empty attributes in a custom controller

### ISSUE THREAD

**Issue by teratux** [symfony/symfony#27708]
**Symfony version(s) affected**: 4.1

**Description**  
In one of my controllers the **show** and **edit** actions receive an object with null attributes.  The **index** action however works ok.  I'm using a custom root namespace other than the built-in **App**.  For this to work I changed the _composer.json_ and added my custom namespace called **Redbridge**. I also changed the _vendors/composer/autoload_static.php_ and _vendors/composer/autoload_psr4.php_ files to use my custom namespace.  I come from symfony 3.4 and noticed new things in symfony 4.1.  I think the problem may rely on something that's not getting autowired correctly.

These are all the relevant files, sections and commands:
composer.json:
```
    "autoload": {
        "psr-4": {
            "Sylius\\Behat\\": "src/Sylius/Behat/",
            "Sylius\\Bundle\\": "src/Sylius/Bundle/",
            "Sylius\\Component\\": "src/Sylius/Component/",
            "Redbridge\\": "src/"
        },
        "exclude-from-classmap": [
            "src/Sylius/*/*/Tests/"
        ]
    },
```

vendors/composer/autoload_static.php:
```
        'R' => 
        array (
            'Redbridge\\' => 10,
            'Ramsey\\Uuid\\' => 12,
        ),
...
...
        'Redbridge\\' =>
            array (
                0 => __DIR__ . '/../..' . '/src',
        ),
```
vendors/composer/autoload_psr4.php:
`    'Redbridge\\' => array($baseDir . '/src'),`

config.yml:
```
imports:
...
...
         - { resource: "services.yml" }
...
...
maker:
    root_namespace: 'Redbridge'
```
services.yml:
```
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Redbridge\:
        autowire: true
        autoconfigure: true
        resource: '../../src/*'
        exclude: '../../src/{Migrations,Tests,Kernel.php,Sylius}'

    Redbridge\Repository\:
            resource: '../../src/Repository'
            autowire: true
            tags: ['doctrine.repository_service']
```
src/Entity/RedbridgeDomain.php:
```
namespace Redbridge\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Redbridge\Repository\RedbridgeDomainRepository")
 * @ORM\Table(name="redbridge_domain")
 */
class RedbridgeDomain
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
```
src/Controller/RedbridgeDomainController.php:
```
namespace Redbridge\Controller;

use Redbridge\Entity\RedbridgeDomain;
use Redbridge\Form\RedbridgeDomainType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/domain")
 */
class RedbridgeDomainController extends Controller
{
    /**
     * @Route("/", name="redbridge_domain_index", methods="GET")
     */
    public function index( Request $request )
    {
        $em = $this->getDoctrine()->getManager();

        $domains =  $em->getRepository('Redbridge\Entity\RedbridgeDomain')->findAll();

        return $this->render('redbridge_domain/index.html.twig', ['redbridge_domains' => $em->getRepository('Redbridge\Entity\RedbridgeDomain')->findAll()]);
    }

    /**
     * @Route("/new", name="redbridge_domain_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $redbridgeDomain = new RedbridgeDomain();
        $form = $this->createForm(RedbridgeDomainType::class, $redbridgeDomain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($redbridgeDomain);
            $em->flush();

            return $this->redirectToRoute('redbridge_domain_index');
        }

        return $this->render('redbridge_domain/new.html.twig', [
            'redbridge_domain' => $redbridgeDomain,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="redbridge_domain_show", methods="GET")
     */
    public function show( RedbridgeDomain $redbridgeDomain ): Response
    {
        return $this->render('redbridge_domain/show.html.twig', ['redbridge_domain' => $redbridgeDomain]);
    }

    /**
     * @Route("/{id}/edit", name="redbridge_domain_edit", methods="GET|POST")
     */
    public function edit(Request $request, RedbridgeDomain $redbridgeDomain ): Response
    {
        $form = $this->createForm(RedbridgeDomainType::class, $redbridgeDomain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('redbridge_domain_edit', ['id' => $redbridgeDomain->getId()]);
        }

        return $this->render('redbridge_domain/edit.html.twig', [
            'redbridge_domain' => $redbridgeDomain,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="redbridge_domain_delete", methods="DELETE")
     */
    public function delete(Request $request, RedbridgeDomain $redbridgeDomain): Response
    {
        if ($this->isCsrfTokenValid('delete'.$redbridgeDomain->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($redbridgeDomain);
            $em->flush();
        }

        return $this->redirectToRoute('redbridge_domain_index');
    }
}
```

This is a var_dump() inside my show controller action:
`object(Redbridge\Entity\RedbridgeDomain)#35780 (2) { ["id":"Redbridge\Entity\RedbridgeDomain":private]=> NULL ["name":"Redbridge\Entity\RedbridgeDomain":private]=> NULL } `

Notice the NULL attribute values.  This is the row on my table:
`'2', 'partner'`

./bin/console doctrine:mapping:info:
` [OK]   Redbridge\Entity\RedbridgeDomain`

From this I interpret that the Entity is correctly mapped

Hope anyone can help, thanks in advance ...

**Comment by xabbuh** [comment]
Your service config does not exclude the `Entity` subnamespace. This means that there will be a service registered for your `Redbridge\Entity\RedbridgeDomain` class. This object will then be injected into your controller. I suggest to exclude the namespace as it doesn't make much sense to wire your entities as services. Then, you will need to make use of [param converters](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#doctrine-converter) if you want to have your route attributes being converted into objects fetched from the database.

I am going to close here as that's not a Symfony bug.

**Comment by teratux** [comment]
Three things here.
1- If I exclude the Entity directory from the service autowire lookup I get the following error:
`Cannot resolve argument $redbridgeDomain of "Redbridge\Controller\RedbridgeDomainController::show()": Cannot autowire service ".service_locator.JqPQg4a": it references class "Redbridge\Entity\RedbridgeDomain" but no such service exists.`
I managed to avoid it once including the Entity directory
2- If the problem altogether gets resolved with the ParamConverter annotation why doesn't symfony 4 automatically binds the parameter to the object type, I've never needed to use it before in previous versions.
3- From the link you provided the ParamConverter annotation isn't maintained in the symfony 4 version, so what's the alternative? Can this thread be moved to another channel if it's not a symfony bug for further discussion?

**Comment by xabbuh** [comment]
> 1- If I exclude the Entity directory from the service autowire lookup I get the following error:
`Cannot resolve argument $redbridgeDomain of "Redbridge\Controller\RedbridgeDomainController::show()": Cannot autowire service ".service_locator.JqPQg4a": it references class "Redbridge\Entity\RedbridgeDomain" but no such service exists.`
> I managed to avoid it once including the Entity directory

Well, you get something injected into your controller then, but as you can see that's not what you expected to get injected.

> 3- From the link you provided the ParamConverter annotation isn't maintained in the symfony 4 version, so what's the alternative?

Don't be confused by the versions shown in the switcher there. :) The SensioFrameworkExtraBundle is developed independently from the Symfony core and can be used in conjunction with Symfony 4.

> Can this thread be moved to another channel if it's not a symfony bug for further discussion?

You can use one of the [support channels](https://symfony.com/support) if you need further help.
