### ISSUE TITLE
Valid Constraints has not same behaviour on property and on getter

### ISSUE THREAD

**Issue by gregoirepaqueron** [symfony/symfony#27725]
**Symfony version(s) affected**: 3.4.11

Hello,

`@Assert\Valid` seems to work not the same way on a property, and on a getter.

Here's the context : 

On a page, depending of a status, i need to apply different validations groups : 
**Status** | **Validation Group**
electronic | electronic
full_paper | register
half_paper | electronic & register

some validation should always be present, some only for electronic, some only for register, and when in "half_paper" status, every validation should be applied.

I have 1 parent Entity with 2 children Entities, both in OneToMany.
One `@Assert\Valid` is applied on the property for 1 children, and one `@Assert\Valid` is applied on a getter for the second children (because I need to distinguish by name some entities of the second children).
Code :  

**Parent**
`Mandate.php`
```php
    /**
     * @var Customer[]|Collection
     * @Assert\Valid(groups={"electronic"})
     * @Assert\Valid(groups={"register"})
     * @ORM\OneToMany(targetEntity="Customer", mappedBy="mandate", cascade={"persist", "remove"})
     */
    protected $customers;

    /**
     * @ORM\OneToMany(targetEntity="Property", mappedBy="mandate", cascade={"persist", "remove"})
     */
    protected $properties;

    /**
     * @Assert\Valid(groups={"electronic"})
     * @Assert\Valid(groups={"register"})
     */
    public function getMainProperty(): ?Property
    {
        foreach ($this->properties as $property) {
            if ($property->isMain()) {
                return $property;
            }
        }

        return null;
    }


    /**
     * @Assert\Valid(groups={"electronic"})
     * @Assert\Valid(groups={"register"})
     */
    public function getSecondaryProperties(): Collection
    {
        $properties = new ArrayCollection();
        foreach ($this->properties as $property) {
            if (!$property->isMain()) {
                $properties[] = $property;
            }
        }

        return $properties;
    }
```
By the way, I'm forced to duplicate `@Assert\Valid` for every group, because if i merge groups in one `@Assert\Valid`, only the first group detected is applied on the childrens.

**Children**
`Customer.php`
```php
    /**
     * @Assert\NotBlank(groups={"electronic", "register"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $firstName;

    /**
     * @Assert\NotBlank(groups={"electronic"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $email;

    /**
     * @Assert\NotBlank(groups={"register"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $city;
```

**Children**
`Property.php`
```php
    /**
     * @Assert\NotBlank(groups={"electronic", "register"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $lotNumber;

    /**
     * @Assert\NotBlank(groups={"electronic"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $lotNature;

    /**
     * @Assert\NotBlank(groups={"register"})
     * @ORM\Column(type="string", nullable=true)
     */
    protected $programName;
```

Here is how i validate : 
`MandateController.php`
```php
    /**
     * @param ValidatorInterface $validator
     * @param Mandate $mandate
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function summaryAction(ValidatorInterface $validator, Mandate $mandate)
    {
       ...
      // $groups can be : ['electronic'], ['register'] or ['electronic', 'register'] 
        $errors = $validator->validate($mandate, null, $groups);
        ...
    }
```

Conclusion : 

Both group register & electronic are applied on every customers, every fields having the "NotBlank" are triggered. 
**BUT** on properties, only 'electronic' is applied on every properties. 
It looks like this is very difficult to work with multi-groups in input on validate() method + multi-group on `@Assert` on entities. The merging flow looks like hard.

My only solution right now is to work with only 1 group that I will call 'half_paper' and I will apply this group on **every** `@Assert` where electronic and/or register are present.

Thanks

**Comment by xabbuh** [comment]
I am not sure I understand your problem. For example, what do you mean with "BUT on properties, only 'electronic' is applied on every properties."? What behaviour did you expect and what happened instead?

**Comment by gregoirepaqueron** [comment]
Sorry if bad explained.
I validate with group ['electronic', 'register']. 
**What happens :** On properties, only @Assert containing group 'electronic' are triggered. NotBlank on programName is not validated, because it has only 'register' group.
**Expected :** All @Assert containing either 'electronic' or 'register' group should be triggered.

**Comment by gregoirepaqueron** [comment]
Sorry for the noise ...
Without changing anything, it's working now.
Problably related to sync problem with docker, cache refreshment, etc.
