### ISSUE TITLE
HttpFoundation 4.0.12 breaks the web debug toolbar

### ISSUE THREAD

**Issue by nicwortel** [symfony/symfony#27726]
**Symfony version(s) affected**: >=4.0.12, >=4.1.1

**Description**
![afbeelding](https://user-images.githubusercontent.com/1055691/41904511-e146d426-7938-11e8-9243-54e1a03cde18.png)

After upgrading HttpFoundation to version [4.0.12](https://github.com/symfony/symfony/releases/tag/v4.0.12) (due to a security issue reported by SensioLabs Security Checker), our web debug toolbar stopped working. Debugging this issue shows that there seems to be a mismatch between version 4.0.4 of HttpKernel and version 4.0.12 of HttpFoundation, because the method [`hasBeenStarted` has been removed from `Symfony\Component\HttpFoundation\Session\Session`](https://github.com/symfony/symfony/compare/v4.0.11...v4.0.12#diff-6ea44a1c02e94a4394cbc7076fe26bbeL149).

This sounds to me like a BC break. I'm not sure if we are supposed to upgrade all symfony packages at the same time, but I think the `composer.json` of `symfony/http-foundation` should at least contain a `conflicts` entry. I realize that the `hasBeenStarted` method was tagged as `@internal` but apparently it was being used in other Symfony components.

Apparently this affects the web debug toolbar, but not our actual application.

[The same issue seems to occur with version 4.1.1](https://github.com/symfony/symfony/compare/v4.1.0...v4.1.1#diff-6ea44a1c02e94a4394cbc7076fe26bbeL149).

**How to reproduce**  
Have symfony/http-foundation on version 4.0.12 and symfony/http-kernel on a lower version. Open the web interface with the debug toolbar enabled.

**Possible Solution**  
- Restore the `hasBeenStarted` method
- Add a `conflicts` entry to the `composer.json` of HttpFoundation, to point out the conflict with older versions of HttpKernel

**Additional context**
This screenshot shows the request made by the web debug toolbar:
![afbeelding](https://user-images.githubusercontent.com/1055691/41903739-00ef0296-7937-11e8-96a2-ec6145d9073c.png)

Installed Symfony components with their versions (from `composer show symfony/*`):
![afbeelding](https://user-images.githubusercontent.com/1055691/41904612-1f85c828-7939-11e8-8302-f84a9b450c2b.png)

**Comment by javiereguiluz** [comment]
@xabbuh but according to the issue report:

> it seems to be a mismatch between version 4.0.4 of HttpKernel and version 4.0.12 of HttpFoundation, because the method hasBeenStarted has been removed from Symfony\Component\HttpFoundation\Session\Session.

Is this correct? Was that method really removed in a patch version?

**Comment by nicolas-grekas** [comment]
Yes, that was an internal one.

**Comment by javiereguiluz** [comment]
@nicwortel I've checked this and as @xabbuh and @nicolas-grekas said, this is sadly expected. As you can see in this line https://github.com/symfony/symfony/compare/v4.0.11...v4.0.12#diff-6ea44a1c02e94a4394cbc7076fe26bbeL147 the removed method is marked as `@internal`, so there's no promise to keep it:

![internal-method](https://user-images.githubusercontent.com/73419/41919154-17078fb8-795e-11e8-8d89-e92b6f24da62.png)

I'm afraid the only solution possible is to upgrade these two dependencies to the same version. We're closing this issue report for that reason. Thanks!

**Comment by nicwortel** [comment]
@javiereguiluz if it is internal, then why is it used by another component? What is Symfony's policy on this?

**Comment by javiereguiluz** [comment]
I don't know the fine print of this, but a quick review of [our BC policy promise](https://symfony.com/doc/current/contributing/code/bc.html) shows that none of it applies to anything marked as `@internal`. I'm sorry.

**Comment by nicolas-grekas** [comment]
we may miss a "conflict" rule somewhere, but I would advise upgrading all components to 4.1.1 instead.

**Comment by stof** [comment]
@javiereguiluz but the mistake was on our side. The internal HttpFoundation method was used by HttpKernel, not by the user.
so for this case, it is indeed too late as the release is already done. But it means we have to be more careful ourselves with our own cross-component usages of internal APIs.
