### ISSUE TITLE
Newly added CacheInterface::get() method does not expose the lifetime in case of item recomputation

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#27732]
llowing issue #27604 where @nicolas-grekas, I have a tiny question: since that #27604 introduces it in documentation saying:

> added CacheInterface, which provides stampede protection via probabilistic early expiration and should become the preferred way to use a cache

I'm OK with using it, but since I can't expose any lifetime, default will be infinite or whatever the adapter decides for all caches that are set using this method.

Is there a reason for that ?

**Comment by pounard** [comment]
Actually, I'm stupid, the callback is supposed the get the cache item from its signature, it's this item that should be changed.

Wouldn't it break immutability, shouldn't the callback return the modified item instead of modifying the existing one ?

**Comment by stof** [comment]
CacheItem in PSr-6 is not immutable.

**Comment by pounard** [comment]
I didn't caught that, thanks for the answer, I guess it answers my question then.

**Comment by nicolas-grekas** [comment]
yep, thats exactly why the item is passed as argument: to add lifetime, tags, etc
