### ISSUE TITLE
Add a file field but i have a error 

### ISSUE THREAD

**Issue by Anouchka25** [symfony/symfony#27739]
Hi
I would like add upload field in my form. I use symfony demo. But i have this error that i don't understand : 
> Cannot resolve argument $imageUpload of "App\Controller\Admin\BlogPostController::new()": Cannot autowire service "App\FileUpload\ImageUpload": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.
This is services.yaml file: [https://github.com/Anouchka25/MyTopBlog/blob/master/config/services.yaml](url)

App\Controller\Admin\BlogPostController : [https://github.com/Anouchka25/MyTopBlog/blob/master/src/Controller/Admin/BlogPostController.php](url)

Thanks to help me !

**Comment by iltar** [comment]
Hey @Anouchka25, for support questions, you can check out https://symfony.com/support.

My recommendation is to join slack, go to the `#support` channel and ask your question there.

**Comment by Anouchka25** [comment]
slack is not good, i have not never the responses !

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by Anouchka25** [comment]
Ok sorry !
