### ISSUE TITLE
Inconsistency in Symfony\Component\Cache\Tests\Adapter\AdapterTestCase::testGet() method

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#27731]
Following issue #27604 where @nicolas-grekas, I found a minor inconsistency within unit tests:

In the ``Symfony\Component\Cache\Tests\Adapter\AdapterTestCase::testGet()`` method:
```
        $this->assertNull($cache->get('foo', function (CacheItem $item) use (&$isHit, $value) {
            $isHit = false;
            $this->assertTrue($item->isHit());
            $this->assertSame($value, $item->get());
        }, INF));
```

The ``$this->assertTrue($item->isHit())`` asumption is wrong, since that ``$beta`` is ``INF``, probabilistic early expiration will recompute an item, but this new item that's going to be computed which will be passed to the anonymous callback is at the discretion of the implementation, it's not documented as being the previous hit, this test does not makes sense.

In fine, it exposes internal implementation details to a unit test that is supposed to test the behaviour, not how it does it.

Since that a ``$beta`` value to ``INF`` will *always* lead to a recomputation, it could be optimized by not loading the item before recomputing it, case in which this test is even less consistent.

**Comment by nicolas-grekas** [comment]
Nope, the test is correct and matches the expected behavior: even with INF, the item should be created from the backend like any other. Then `isHit()` actually allows implementing the 3rd type of stampede protection: external recomputation, and allow the callback to know this is valid data that is computed ahead of time, if that matters to it.

**Comment by nicolas-grekas** [comment]
PR welcome if any docblock could be improved!

**Comment by pounard** [comment]
> Nope, the test is correct and matches the expected behavior: even with INF, the item should be created from the backend like any other.

> Then isHit() actually allows implementing the 3rd type of stampede protection: external recomputation

Ok, now I get this one, it indeed sure needs documentation. But what happens if a developer does not want to implement external recomputation, do we still want to preload an item we know we are going to rebuild anyway ?

It seems that you actually thought of everything, be sure that I did read the code for a while, and the wikipedia page you linked, and others, and actually worked with cache for a few years in other contextes than Symfony, and yet I couldn't guess every details on my own!

**Comment by nicolas-grekas** [comment]
> do we still want to preload an item we know we are going to rebuild anyway ?

trying to not do so would be a micro-optimization: if the item is in the cache, it is by definition fast to fetch.
I think the feature provided by the behavior I describe is more important than optimizing a specific edge case.

> It seems that you actually thought of everything

I did my best, but you already spotted areas where I was too lazy looks like (locks confirmed ;) )

I really appreciate the discussions you opened because they force me to write down want and why I had in mind when coding - and that will definitely help, either to document or to spot real issues. So thanks for that.

**Comment by pounard** [comment]
> trying to not do so would be a micro-optimization: if the item is in the cache, it is by definition fast to fetch.

True, it is, but it may sound confusing earing that from you, because reading a lot of your code it seems that you often easily choose micro-optimisation over readability (and believe me, that's something I hate most of the time). Don't take that as an aggression, really it's not ! :)

> I really appreciate the discussions you opened because they force me to write down want I had in mind when coding - and why I did things this way. That will definitely help, either to document or to spot real issues. So thanks for that.

You're very welcome.

**Comment by nicolas-grekas** [comment]
> you often easily choose micro-optimisation over readability

I do it heavily when there is no external side effect, and also when actually it's not "micro" anymore - ie when it can be found in a hot loop. Here, it would go against a useful semantics, so cannot win the balance.

**Comment by pounard** [comment]
> I do it heavily when there is no external side effect

There's a common side effect you will never get rid of is readability, and sometime it's working by hacking around PHP internals, which in some cases could be not future proof (even if PHP is very slow to evolve). 

Again, I'm really not freely being mean, just since I always see your changes in the commit log and never when you're building the PR, I don't have the chance to write down those notes during reviews (which mostly are details, once again, I'm never criticizing globally the work you're doing, you're mostly very clever).

I don't think that it's a good thing for example to over-inline stuff for optimization, since PHP 7.3 is again going to extend their optimizations, it will soon enough hit the threshold, I hope at least, where PHP itself will inline at some point.

My point here, it's not always documented in the code itself, whereas it always is in the PR discussion themselves: the very bad thing is I did understand a lot of your code by actually reading the PR discussions, where I was sometime not able to understand the code itself. What will happen the day you'll take a break for a year or so ? Will the candidates for taking over you be smart enough to guess why you did write all those tiny tiny clever details ? Open source is about sharing, readability, comprehensibility.

> and also when actually it's not "micro"

I do agree, this is a good trade-off, yet sometime, you fight for 5% benefit on the container (for example) which in the end is 2% of the total execution time, which makes in the end a 0.1% benefit over some real uses cases. I sometime am doubtful. But once again, I cannot speak for every use case, only those I measured myself, so I guess it's a very opinionated way of seeing things.

> Here, it would go against a useful semantics, so cannot win the balance.

Sure, I get it, and you're right about this.

Thank you once again for answering to all of this, it's very interesting, and I'll try to do some PR to document this when I'll have a few hours to spare, today I have too much to do to start this right now.

**Comment by nicolas-grekas** [comment]
> [...] Open source is about sharing, readability, comprehensibility

Noted that part. Fortunately, PR discussions are part of the accessible history also (they're even in the git history as "git notes"). Not commenting more to keep the focus the original topic :)

Can't wait for your PR(s) adding docblocks for this and the other missing ones you spotted in your other issues :)

**Comment by pounard** [comment]
> Noted that part. Fortunately, PR discussions are part of the accessible history

Sure, but code is code, as developers we mostly do read code from a dist tarball when using a framework or library, in that specific use case, which is 95% of what I do when I read Symfony code, I don't have direct access to git - I could switch from my IDE to do some lookup in github, or clone the repo in some tmp directory, sure, but it's information I have to search for whereas most tricky parts could be directly documented within the code and be there from the begining.
