### ISSUE TITLE
[Config][Sf4.1] ArrayNodeDefinition::prototype() invalid return type?

### ISSUE THREAD

**Issue by watari** [symfony/symfony#27749]
**Description**
Method `\Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::prototype()` in Php-docs has `NodeDefinition` for return type but actually it return  `ArrayNodeDefinition` instance. 

**Consequences**
This mystype brokes PhpStorm autocomplete since all methods that is defined in `ArrayNodeDefinition` is not highlighted.

**Comment by stof** [comment]
That's not true. You can have prototypes of different types, and then the actual NodeDefinition being returned will be different. `prototype('array')` (which is the default value of the argument) indeed returns an `ArrayNodeDefinition`, but `prototype('scalar')` would return a `ScalarNodeDefinition` for instance.

**Comment by watari** [comment]
Thanks for reply. Now I got it. So I close this issue since it just "false alarm" from my side.
