### ISSUE TITLE
Debugger is broken after update - session handling

### ISSUE THREAD

**Issue by cmPns24** [symfony/symfony#27740]
**Symfony version(s) affected**: 4.1.1

**Description**  
After update to version 4.1.1 from 4.1.0 the debugger is broken.
The method hasBeenStarted was removed. But something call them.

https://github.com/symfony/symfony/commit/146e01cb4442fbcb3b05dd8ae2569d9894374044#diff-6ea44a1c02e94a4394cbc7076fe26bbeL145

**How to reproduce**  
composer update
call in browser

**Additional context**  
Call to undefined method Symfony\\Component\\HttpFoundation\\Session\\Session::hasBeenStarted() in /PATH/vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php on line 74\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /PATH/public/index.php:0\nPHP message: PHP   2. App\\Kernel->handle() /PATH/public/index.php:37

Extract from our composer.json
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "excelwebzone/recaptcha-bundle": "1.5.11",
        "pns24/coreapi": "dev-feature/shopRelaunch/product",
        "pns24/logger": "dev-master",
        "pns24/traits": "dev-master",
        "sensio/framework-extra-bundle": "5.1.6",
        "symfony/asset": "4.1.0",
        "symfony/console": "4.1.0",
        "symfony/dotenv": "4.1.0",
        "symfony/expression-language": "4.1.0",
        "symfony/flex": "1.0.80",
        "symfony/form": "4.1.0",
        "symfony/framework-bundle": "4.1.0",
        "symfony/lts": "dev-master",
        "symfony/monolog-bundle": "3.3.0",
        "symfony/orm-pack": "1.0.5",
        "symfony/process": "4.1.0",
        "symfony/security-bundle": "4.1.0",
        "symfony/serializer-pack": "1.0.1",
        "symfony/swiftmailer-bundle": "3.2.2",
        "symfony/twig-bundle": "4.1.0",
        "symfony/validator": "4.1.0",
        "symfony/var-dumper": "4.1.0",
        "symfony/web-link": "4.1.0",
        "symfony/webpack-encore-pack": "1.0.2",
        "symfony/yaml": "4.1.0",
        "gorkalaucirica/hipchat-v2-api-client": "1.5.1"
    },
    "require-dev": {
        "symfony/browser-kit": "4.1.0",
        "symfony/css-selector": "4.1.0",
        "symfony/debug-pack": "1.0.5",
        "symfony/maker-bundle": "1.5.0",
        "symfony/phpunit-bridge": "4.1.0",
        "symfony/profiler-pack": "1.0.3",
        "symfony/web-server-bundle": "4.1.0"
    },

**Comment by iltar** [comment]
Related to #27726 by any chance?

**Comment by nicolas-grekas** [comment]
Yup, closing as duplicate, sorry for the trouble @cmPns24.
