### ISSUE TITLE
[Workflow] BC Break in Event class (potential real issue)

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#27759]
**Symfony version(s) affected**: 4.1.x

**Description**  

```php
$event = new \Symfony\Component\Workflow\Event($subject, $marking, $transition);
```

This previously was an authorized usage. With 4.1 it now fails. But the last (and missing here) arg is still optional while it generates the throw of an exception.

This is due to [this commit](https://github.com/symfony/symfony/commit/bd1f2c858385bca965cb6e8d32b1a21085029981#diff-7ced8e5ceace060a06472087086f06eaR49).

**Possible Solution**  

I thinks something's wrong with the exception `InvalidArgumentException`, I suggest to remove it for now and adding it in 5.0.

https://github.com/symfony/symfony/blob/bd1f2c858385bca965cb6e8d32b1a21085029981/src/Symfony/Component/Workflow/Event/Event.php#L38-L51

**Comment by chalasr** [comment]
Indeed, the 4th argument is now mandatory.
Either no exception should be thrown in case of `null`, or the default value  (string) should be re-added. 
IMO the old default value should be preserved and an extra `|| null === $workflow` should be added to the `elseif` in order to support `?Workflow $workflow` (or `Workflow $workflow = null`) in 5.0.

**Comment by chalasr** [comment]
Apparently, the goal is to make it mandatory in 5.0, so `null` should not be allowed here. I suggest changing `$workflow = null` to `$workflow = 'unnamed'`.

**Comment by nicolas-grekas** [comment]
ping @lyrixx I suppose.

**Comment by lyrixx** [comment]
Indeed, this **could** be a BC break. But you are not supposed to create this event yourself. 
The component does it for you. How did you get this exception ?

**Comment by Nek-** [comment]
I use it in a test. Id have to say it's not critical.

But the fact is that it makes no sense to break the BC with keeping it (which is my point by writing "potential issue"). Let me explain myself: you keep in the constructor `$workflow = null` for BC ofc, but throws if the value is null.

Also to me, it's a BC break because the class is not final and may be extended.

**Comment by lyrixx** [comment]
@Nek- Could you try the PR ? #27848
