### ISSUE TITLE
Object of class Symfony\Component\HttpFoundation\ParameterBag could not be converted to string

### ISSUE THREAD

**Issue by little-isaac** [symfony/symfony#27751]
**Symfony version(s) affected**: ~4.0

**Description**  
I am using laravel(5.6.*) and write simple eloquent query as follows.
$query = "something";
        $products = Product::
                where('title', $query)
                ->paginate($limit);

But i get "Object of class Symfony\Component\HttpFoundation\ParameterBag could not be converted to string"

Yesterday it is working perfectly fine and today i don't know what happened.
Please help me with this.
I am providing simple search functionality using that query.

![https kaan project herokuapp com products json page 1 limit 10 query black](https://user-images.githubusercontent.com/16745709/41993049-d1208346-7a67-11e8-8958-760557b498bf.png)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
