### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by jingjinjingjin** [symfony/symfony#27762]
https://github.com/symfony/http-foundation/blob/master/Response.php#L491
https://github.com/symfony/http-foundation/blob/master/Response.php#L635
and line 692,738,798.......

**Comment by stof** [comment]
What is your question exactly ?

**Comment by jingjinjingjin** [comment]
throw 500 error

**Comment by jingjinjingjin** [comment]
`E:\php_code\crudbooster\vendor\symfony\http-foundation\Cookie.php
            $data['expires'] = time() + (int) $data['max-age'];
        }
 
        return new static($name, $value, $data['expires'], $data['path'], $data['domain'], $data['secure'], $data['httponly'], $data['raw'], $data['samesite']);
    }
 
    /**
     * @param string                        $name     The name of the cookie
     * @param string|null                   $value    The value of the cookie
     * @param int|string|\DateTimeInterface $expire   The time the cookie expires
     * @param string                        $path     The path on the server in which the cookie will be available on
     * @param string|null                   $domain   The domain that the cookie is available to
     * @param bool                          $secure   Whether the cookie should only be transmitted over a secure HTTPS connection from the client
     * @param bool                          $httpOnly Whether the cookie will be made accessible only through the HTTP protocol
     * @param bool                          $raw      Whether the cookie value should be sent with no url encoding
     * @param string|null                   $sameSite Whether the cookie will be available for cross-site requests
     *
     * @throws \InvalidArgumentException
     */
    public function __construct(string $name, string $value = null, $expire = 0, ?string $path = '/', string $domain = null, bool $secure = false, bool $httpOnly = true, bool $raw = false, string $sameSite = null)
    {
        // from PHP source code
        if (preg_match("/[=,; \t\r\n\013\014]/", $name)) {
            throw new \InvalidArgumentException(sprintf('The cookie name "%s" contains invalid characters.', $name));
        }
 
        if (empty($name)) {
            throw new \InvalidArgumentException('The cookie name cannot be empty.');
        }
 
        // convert expiration time to a Unix timestamp
        if ($expire instanceof \DateTimeInterface) {
            $expire = $expire->format('U');
        } elseif (!is_numeric($expire)) {`

**Comment by jingjinjingjin** [comment]
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_PARSE)
syntax error, unexpected '?', expecting variable (T_VARIABLE)
```

```
    public function __construct(string $name, string $value = null, $expire = 0, ?string $path = '/', string $domain = null, bool $secure = false, bool $httpOnly = true, bool $raw = false, string $sameSite = null)
    {
```

```?string```  cause error

**Comment by theofidry** [comment]
This is a PHP 7 feature so you are likely to be running it in PHP 5.x...

**Comment by jingjinjingjin** [comment]
But my PHP version is 7.0.12.

**Comment by stof** [comment]
make sure that you use the same PHP version for your CLI running composer, and for your webserver, or configure composer to force a different PHP version than the current one. Composer already handles fine the fact of selecting a package version compatible with your PHP version. But if you change PHP version after that (using a different one for the webserver), it won't work.

@theofidry actually, that's a PHP 7.1+ feature.

**Comment by jingjinjingjin** [comment]
@stof Yes, my cli PHP version is 7.1.13.  Many thanks.
