### ISSUE TITLE
Twig-Bridge: Checkbox and radio labels do not render properly

### ISSUE THREAD

**Issue by karlbuckland** [symfony/symfony#27761]
**Twig-Bridge version affected**: 3.4.9

**Description**  
It looks like a new block (checkbox_radio_label) has been added to allow labels for checkbox and radio elements to be rendered differently for Bootstrap layouts. This block is present in bootstrap_4_layout.html.twig, but not in form_div_layout.html.twig. This means that label tags no longer have 'for' attributes, for example.

**Possible Solution**  
Add the block into form_div_layout.html.twig. Something like:
`{% block checkbox_radio_label -%}
    {{- form_label(form) -}}
{% endblock %}`

**Comment by xabbuh** [comment]
I do not understand how the missing `checkbox_radio_label` block is related to the `for` attribute in the `form_div_layout.html.twig` form theme. The attribute will be set here: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L259

If you still experience the issue, can you please create a small example application that allows to reproduce?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
