### ISSUE TITLE
Service autowiring for constraint validators does not work when invoked using the Validator component directly

### ISSUE THREAD

**Issue by Kage** [symfony/symfony#27760]
**Symfony version(s) affected**: 3.4.12

**Description**  
Service autowiring for constraint validators does not work when invoked using the Validator component directly.

**How to reproduce**  

First, create a simple Validator with some autowiring in the constructor.  We'll call this "FoobarValidator" from here on.  For example:
```php
  public function __construct(ManagerRegistry $doctrine, RouterInterface $router) {
    $this->doctrine = $doctrine;
    $this->router = $router;
  }
```

This validator and its autowiring will work fine if used in a normal context, e.g. when defined as a constraint within a `FormBuilderInterface` object.

Next, try to call this validator directly from a controller.  For example:
```php
    $validator = Validation::createValidator();
    $violations = $validator->validate('foobar', array(
      new FoobarValidator(array(
        'message' => 'blah',
      )),
    ));
```

This will now give the following error when attempting to access that controller:

    Type error: Argument 1 passed to AppBundle\Validator\Constraints\FoobarValidator::__construct() must implement interface Doctrine\Common\Persistence\ManagerRegistry, none given, called in /home/user/SymfonyProject/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorFactory.php on line 43

**Possible Solution**  
Unknown

**Additional context**  

The steps above will produce the following error:

    Type error: Argument 1 passed to AppBundle\Validator\Constraints\FoobarValidator::__construct() must implement interface Doctrine\Common\Persistence\ManagerRegistry, none given, called in /home/user/SymfonyProject/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorFactory.php on line 43

**Comment by stof** [comment]
that's because your instantiate your own validator not integrated with the DI component. autowiring is not magic. If the validator you use does not know about the DI container, it won't magically use it.

**Comment by stof** [comment]
What you should do is using the validator service configured by FrameworkBundle, which registers this integration (and it is available for autowiring if you typehint the ValidatorInterface)

**Comment by Kage** [comment]
Aha!  Confirmed, injecting a `ValidatorInterface` fixed my problem and works as expected.

Thanks for the advice, @stof !  Closing this issue.

**Comment by koredalin** [comment]
> What you should do is using the validator service configured by FrameworkBundle, which registers this integration (and it is available for autowiring if you typehint the ValidatorInterface)

Can I start Validation service outside Symfony. Without Framework bundle?
