### ISSUE TITLE
Provide intuitive error message when a controller fails because it's not registered as a service

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#27787]
Would make https://github.com/symfony/symfony-docs/issues/7988 unneeded.

When a controller is not found as a service, is thus directly instantiated, but fails as described in #23033 (`Symfony requires that you provide a value for the $passwordEncoder argument`), could we provide a nicer error message, e.g. by registering a very late argument resolver?

**Comment by gonzalovilaseca** [comment]
@nicolas-grekas I can help with this but I'd need some clarification first: Are you sugesting registering an argument resolver that is executed after `ServiceValueResolver`, supports controllers and just throws an exception with a nice error message?

**Comment by nicolas-grekas** [comment]
@gonzalovilaseca correct!
