### ISSUE TITLE
[DependencyInjection] AutowireRequiredMethodsPass does not work with method arguments

### ISSUE THREAD

**Issue by khaperets** [symfony/symfony#27780]
**Symfony version(s) affected**: >=3.4

**Description**  
When you try to use the annotation `@required` - AutowireRequiredMethodsPass is not parsed method arguments.

**How to reproduce**  
Try using autowiring with the `@required` annotation.

**Possible Solution**  
Add parsing of method arguments as in AutowirePass.

**Additional context**  
Bug commit: https://github.com/symfony/symfony/commit/ec111877fa94e1df827c06349925944f44e62d6f

**Comment by nicolas-grekas** [comment]
Hi, this pass does not wire the arguments, it only wires the methods. To wire the arguments, you need to run AutowirePass after this one.
Does that fix your concern?
If not and you think there is a bug, please provide a reproducer, or a failing test case if you can.

**Comment by khaperets** [comment]
Created PR #27788 with failed test

**Comment by khaperets** [comment]
@xabbuh, but `AutowirePass` does not running after `AutowireRequiredMethodsPass`.

**Comment by xabbuh** [comment]
By default it does. How did you set up your compilation process?

**Comment by nicolas-grekas** [comment]
For reference, here is where both are configured:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php#L63
I'm closing here as there is no bug to keep track of. No pb to reopen if we're wrong of course.
