### ISSUE TITLE
No referer to redirect back in Event Subscriber for url with method POST

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#27785]
**Description**  

I was trying to create my own kind a middleware to verify CSRF token using event subscriber for onKernelRequest request. I noticed that, in that event we have no referer to redirect user back when he submits POST form.

**Example**  

UserController.php on line 110:
```
Request {#18 ▼
  +headers: HeaderBag {#25 ▼
    #headers: array:13 [▼
      "cookie" => array:1 [▶]
      "accept-language" => array:1 [▶]
      "accept-encoding" => array:1 [▶]
      "referer" => array:1 [▶]
```
in subscriber
```
  +headers: HeaderBag {#25 ▼
    #headers: array:12 [▼
      "cookie" => array:1 [▶]
      "accept-language" => array:1 [▶]
      "accept-encoding" => array:1 [▶]
      "dnt" => array:1 [▶]
      "accept" => array:1 [▶]
      "user-agent" => array:1 [▶]
```
no referer for that event.

Tried

```
  KernelEvents::FINISH_REQUEST  => [  // or ::REQUEST
                ['onKernelRequest', 0],
            ],
```
no header or server referer, do not know yet how to redirect user back from POST url to GET url with form.

**Comment by iltar** [comment]
Referrer headers are not always sent, so you can't rely on them. If you control the form, you can post the current url along.

**Comment by BonBonSlick** [comment]
Tell me please the best option to do so? Session, cookie? How would you do it?

**Comment by ostrolucky** [comment]
When posting form, previous url is the one where user was filling the form. Is this the URL you want?

**Comment by BonBonSlick** [comment]
@ostrolucky  at the moment we save last url in session on any request

**Comment by xabbuh** [comment]
I am closing here as this does not seem to be a bug.

@BonBonSlick I suggest to use one of the [support channels](https://symfony.com/support) if you need further help with your implementation. Thank you for understanding.
