### ISSUE TITLE
[RFC] Improve UX of Process

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#27796]
Since Symfony 3.3, the `Process` component accepts an array of arguments as the `$commandline` which will then enable autoescaping automatically. See https://github.com/symfony/symfony-docs/pull/9988/ and the [tweet](https://twitter.com/nicolasgrekas/status/1013451684771745792) by @nicolas-grekas. Without that tweet I would have probably completely missed out on that feature and I think a lot of devs are. But I think in probably 99% of all cases you would want to have this feature enabled. However, right now, nothing tells you that you're probably doing things wrong. It will just - maybe even silently - fail on different platforms. And that's not a good situation.
I think most developers still choose `new Process('string commandline');` because that's how it used to work ever since even though they would prefer having the arguments escaped. This is too much magic for me (pass a string -> behaves like this, pass an array -> behaves differently but you never get an error). I think if a developer really wants to handle the underlying details for stream redirection etc. they should explicitly opt-in for that, not opt-out.

So I think the first constructor argument of `Process` should only accept an array and if you really want to pass in a string, you should tell the `Process` that you know what you're doing. There are multiple solutions how we could achieve that:

1. Adding a new method to disable escaping and checking in the `start()` method if argument escaping was disabled explicitly:

```php
$process = new Process('string command');
$process->start(); // Raises deprecation, in 5.0 exception

$process = new Process('string command');
$process->disableArgumentEscaping(); // Developer now explicitly disables escaping which is what we want
$process->start(); // This is fine now
```

2. New class:

```php
$process = new Process('string command'); // deprecated, use ShellProcess if you want to disable argument escaping, in 5.0 use array as typehint

$process = new Process(['string', 'command']); // correct
$process = new ShellProcess('string command'); // correct
```

Wdyt?

**Comment by nicolas-grekas** [comment]
> $process = new ShellProcess('string command'); // correct

I like this one, with a deprecation when "new Process" is called with a string as argument.
Autoescaping is wrong btw: when there is no shell, there is no concept of escaping at all, because there is no parsing of anything, thus... nothing to escape. The array are just arguments passes to the command-executor of the kernel.

**Comment by Toflar** [comment]
I see, I'll leave a comment in https://github.com/symfony/symfony-docs/pull/9988 then :-)

**Comment by Toflar** [comment]
> when there is no shell, there is no concept of escaping at all, because there is no parsing of anything, thus... nothing to escape.

Also, this is kind of an argument against having `ShellProcess`, no? If there is a shell, there **is** a concept of escaping = why would `ShellProcess` accept a string that's not escaped then? 😄

**Comment by nicolas-grekas** [comment]
> why would ShellProcess accept a string that's not escaped then?

I'm sorry i don't get this sentence, it doesn't make sense to me.

**Comment by Toflar** [comment]
Sorry, trying again. You said:

> when there is no shell, there is no concept of escaping at all, because there is no parsing of anything, thus... nothing to escape.

So imho it should be the other way around:

```php
$process = new Process('direct command');

$process = new ShellProcess(['ls', '-la']); // Escapes and then passes the string to the parent
```

**Comment by Toflar** [comment]
I see. I think I need to see where the whole escaping takes place. But I guess the discussion shows that there's room for improvement here 😄

**Comment by javiereguiluz** [comment]
I'm not sure it's worth it to create a whole new `ShellProcess` class. The docs are clear about this and easy to understand for the differences of using array/strings with `Process`.

**Comment by iltar** [comment]
I agree that writing a new class for this might not be a good idea if it does the same but with a different constructor. Out of curiosity though, would it be interesting to make the `Process` class internal and expose different light-weight wrappers instead? It always felt odd to initiate a new process, which could (afaik) accept multiple commands inside.

This is just a brainfart:
```php
$interactiveShell = new InteractiveShell(); // nothing needed as it's interactive
$shell1 = new SimpleShell('ls -la');
$shell2 = new PreparedShell('ls', ['-la']);
$command = new SymfonyCommandShell('debug:container', ['--show-private']);
$customCommand = new SomeComplexCommandWithLotsOfArgumentsForMyDomain([...]);
```

Internally they could all use the process and probably expose a very similar API, but it would make it possible to use a consistent abstraction layer to run commands/tools/scripts etc. with a nicer UX (imo).

**Comment by stof** [comment]
@iltar does it actually make things simpler ? Most of the public methods of the Process object would then have to be proxied. Users would then have to ask themselves "which one should I be using?" all the time.

**Comment by iltar** [comment]
@stof Yeah, that's the only downside, but I don't know how to solve that cleanly without delegation.

One advantage though, is that you can narrow down the public API per "shell". A process that pipes output all the time that needs to be parsed, only needs to expose methods to do just that, where as a simple one time only output command, doesn't have to do this and can just get the output when done. Some custom commands might not have any output at all and you only want to know the return type. 

Writing those might be a bit more difficult and will also narrow down the possibilities. However, as writer I've often noticed that I'm at a loss on which methods I need to call on the process, making it more of a trial and error to see what (kinda) works.

**Comment by Toflar** [comment]
> "which one should I be using?"

Which is what they should. I mean, not talking about the proxy but this is why I've created this issue. Right now devs don't ask. They just use `new Process('string')` and it might cause issues with escaping. I think it would be a good thing to make them decide rather than just making a difference between passing a string or an array. That doesn't feel like devs are deciding. Only if you pass an array you are deciding and imho passing an array is normally what you want. I agree that docs of Symfony are good but it could probably also be improved by the interfaces provided.

**Comment by nicolas-grekas** [comment]
I think deprecating `new Process(string)` is the way to go: it will force people to consider the issue an migrate to using arrays. If they really want the shell, `new ShellProcessor` will be provided.
I don't think there is anything to seek for.

**Comment by nicolas-grekas** [comment]
We can also *not* add any new class and add a static constructor instead for the shell!

**Comment by nicolas-grekas** [comment]
See #27821
