### ISSUE TITLE
[WebLink] Don't send Link headers on XHR request

### ISSUE THREAD

**Issue by cedricziel** [symfony/symfony#27797]
**Symfony version(s) affected**: 3.3.x-current

**Description**  

When referencing a resource with the `preload` helper, Symfony will [send a `Link` header](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/WebLink/EventListener/AddLinkHeaderListener.php#L47), containing resource links according to the spec. So far so good.

IMHO, the links should only be sent under the following circumstances:

* the request is the master request (done)
* the request ist *no* XHR request

If the header is also sent on xhr requests, every request to a resource sending a `Link` header will also force the Browser (Chrome in my case), to re-download the resource, regardless if it was loaded before already. This causes JavaScript to re-execute. - That's not what is intended, when I request a HTML resource through XHR.

**How to reproduce**  

Create a **layout**, referencing a resource with preload:

```jinja2
<script src="{{ preload(asset(build/app.js''), {as: 'script'}) }}"></script>
```

Have an action referencing that layout through a template, in that action load the url (or another URL with the same layout/asset loaded with preload):

```javascript
$.get('/my/action');
```

Watch the browser request console to re-load and re-execute the resource.

**Possible Solution**  

Add additional check in `AddLinkHeaderListener::onKernelResponse` to check if the current response is a XHR, and return early if it is. Similar to / extending the check for the master request.

**Additional context**  

My use case is: Load an HTML snippet from a URL, take a fragment and load it into another element - simple async content.

I will create a Pull Request referencing this issue.

**Comment by dunglas** [comment]
* With the proper cache HTTP headers, browsers will tell the server to cancel the push of files already in cache: https://stackoverflow.com/a/29354100/1352334
* It is often desirable to push related resources even in XHR (think relations of a JSON documents when requesting a web API, assets used only by a specific template, that are unlikely in cache)
* The "problem" only occurs for Twig helpers (in a controller, we can just test if it's an XHR request or not) with cache headers not set properly

I wouldn't change the default behavior. Maybe it can be interesting to add a new `noXHR` flag to Twig helpers. But the best solution is definitely to fix the HTTP headers. Can you try is adding the proper `Cache-control` headers fix your issue @cedricziel?
Btw, in your specific case, using proper JS module loading (with Webpack for instance) would be a better fix.

**Comment by cedricziel** [comment]
Thx for double checking - yes, correct cache headers fixed the problem.

I would even step away from the issue and the since it seems it was solely a server configuration issue and I think server and client need to negotiate.

We use WebPack for the build, but have some logic fiddeling with the dom, so that doesnt help much.

Thank you for the review, @dunglas .
