### ISSUE TITLE
Fatal error in RemoveUnusedDefinitionsPass when building container with injected services

### ISSUE THREAD

**Issue by ciaranmcnulty** [symfony/symfony#27802]
**Symfony version(s) affected**: dev-master

**Description**  
Changes to inlining introduced in #27471 have broken Behat's CLI app.

The services available here:
https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Cli/Application.php#L181-L182
...are triggering a fatal error inside `the RemoveUnusedDefinitionsPass` when building the main application service.

Even if Behat is using the DIC wrongly, this probably shouldn't be causing a fatal at this point.

I'll update this issue if I manage to extract a smaller reproducible bug

Stack trace:
```
In ContainerBuilder.php line 1001:
                                                                              
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "cli.output".                     
                                                                              
Exception trace:
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at /Users/ciaran/Code/Behat/vendor/symfony/dependency-injection/Compiler/RemoveUnusedDefinitionsPass.php:65
 Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass->process() at /Users/ciaran/Code/Behat/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /Users/ciaran/Code/Behat/vendor/symfony/dependency-injection/ContainerBuilder.php:736
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /Users/ciaran/Code/Behat/src/Behat/Testwork/Cli/Application.php:187
 Behat\Testwork\Cli\Application->createContainer() at /Users/ciaran/Code/Behat/src/Behat/Testwork/Cli/Application.php:161
 Behat\Testwork\Cli\Application->createCommand() at /Users/ciaran/Code/Behat/src/Behat/Testwork/Cli/Application.php:122
 Behat\Testwork\Cli\Application->doRun() at /Users/ciaran/Code/Behat/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /Users/ciaran/Code/Behat/bin/behat:34
```

**How to reproduce**  

```
composer create-project behat/behat behat-debug
cd !$
composer config minimum-stability dev
composer update
bin/behat
```

**Comment by jakzal** [comment]
Looks like Behat hasn't been explicitly registering a couple of services as synthetic (see https://github.com/Behat/Behat/pull/1160). However, Symfony didn't use to complain about it. The current message is a bit misleading in this context too.

Status: reviewed

**Comment by ciaranmcnulty** [comment]
Thanks @jakzal - it looks like the call to getDefinition will trigger a fatal any time a service like that exists.

Should this happen earlier when the service is `set()`?

**Comment by stof** [comment]
@nicolas-grekas I think we need to fix this (we could then deprecate the ability to set a service which was not previously defined, but it needs to go through a deprecation process)

**Comment by ciaranmcnulty** [comment]
Further investigation showed that as well as being set(), the service had to be referenced by another service as an argument.

I've submitted a bug fix

**Comment by nicolas-grekas** [comment]
> we could then deprecate the ability to set a service which was not previously defined

not sure it would help anything for internals, so not worth it for now at least IMHO.

**Comment by ciaranmcnulty** [comment]
It seems to be this way for a long time - the only use case I can think of is setting a service on the ContainerBuilder, and then providing the Definition afterwards?

It is weird to have definition-less services though. Perhaps during compilation this could be checked and deprecations issued (rather than at `set()` time)

**Comment by Saeven** [comment]
Ran into this too, thanks for this thread.  Solved it by pinning to:

```
    "symfony/console": "3.4.12",
    "symfony/dependency-injection": "4.1.1",
    "behat/behat": "3.*@stable",
```
