### ISSUE TITLE
Notice: Array to string conversion instead of informative error message when configuration with non-existent Doctrine connection is found in RegisterEventListenersAndSubscribersPass

### ISSUE THREAD

**Issue by kalifg** [symfony/symfony#27811]
**Symfony version(s) affected**: 3.4.11

**Description**  
There is a small bug in an exception thrown by `RegisterEventListenersAndSubscribersPass` when a Doctrine connection that doesn't exist is referenced in configuration.  Instead of getting the helpful exception message:

```
The Doctrine connection "root" referenced in service "stof_doctrine_extensions.listener.sluggable" does not exist. Available connections names: default
```

You instead get 

```
Notice: Array to string conversion
```

**How to reproduce**  
I was able to reproduce this by having the following configuration:

```yml
stof_doctrine_extensions:
    orm:
        root:
            sluggable: true
            timestampable: true
```

after I removed the connection named `root`.

**Possible Solution**  
The variable `$taggedSubscriber` here is actually an array, with the name of the service as the first member.  Changing the reference to `$taggedSubscriber[0]` should fix this.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L72

**Additional context**

**Comment by chalasr** [comment]
👍 The `sprintf()` should use `$id` (from https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L68).
Can you submit a PR? It should target branch 2.8, bug also exists there.

**Comment by chalasr** [comment]
See #27813
