### ISSUE TITLE
[Debug] title of debug link does not use file mapping

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#27842]
**Symfony version(s) affected**: At least 3.4. But I guess all versions are affected

**Description**  

I'm using `xdebug.file_link_format=subl://%f:%l`
I also use the feature to map a folder to another (BTW, this looks like not documented)

I noticed the link title and link href are not synced, as you can see on the screenshot

![screenshot from 2018-07-04 15-14-49](https://user-images.githubusercontent.com/408368/42279555-6739bf4c-7f9e-11e8-9304-c0b31af8399a.png)
 
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
That looks expected to me: the display shows where the file is for the app, and the link how to open it for the IDE.
For the doc, PR welcome :)

**Comment by lyrixx** [comment]
> That looks expected to me: the display shows where the file is for the app, and the link how to open it for the IDE.

:+1:
