### ISSUE TITLE
[RFC] Symfony Translator assertValidLocale()

### ISSUE THREAD

**Issue by bogdanfinn** [symfony/symfony#27853]
**Description**  
When the translation service is created the default locale is injected in this service during creation. After injecting the service into a controller e.g. you can call the setLocale() Method on the injected service and pass `null` as an argument for the `$locale` parameter. The `assertValidLocal()` function does not throw the InvalidArgumentException, because `pre_match()` in this case returns 1 when passing `null` as the second argument. In my opinion this is not correct, because `null` is not a valid locale. For me the Translator should use then the fallback locale but this is a case that can be discussed because when i set the local manually and it is not correct somebody else might do not want the service to use a different locale. I think if `null` is passed as the second argument the function should throw the Exception.
 
 **Example**  
```/**
     * Asserts that the locale is valid, throws an Exception if not.
     *
     * @param string $locale Locale to tests
     *
     * @throws InvalidArgumentException If the locale contains invalid characters
     */
    protected function assertValidLocale($locale)
    {
        if ($locale === null || 1 !== preg_match('/^[a-z0-9@_\\.\\-]*$/i', $locale)) {
            throw new InvalidArgumentException(sprintf('Invalid "%s" locale.', $locale));
        }
    }```

**Comment by ismail1432** [comment]
If you pass `null` as an argument an Exception will be thrown, [see here](https://3v4l.org/rOoVF)

**Comment by bogdanfinn** [comment]
Yes, the example is the function how i would write it. The additional null check is not there in the current Symfony version. In the current version `null` as an argument won't throw an Exception.

The current implementation of the assertValidLocale() function is this:
```
    /**
     * Asserts that the locale is valid, throws an Exception if not.
     *
     * @param string $locale Locale to tests
     *
     * @throws InvalidArgumentException If the locale contains invalid characters
     */
    protected function assertValidLocale($locale)
    {
        if (1 !== preg_match('/^[a-z0-9@_\\.\\-]*$/i', $locale)) {
            throw new InvalidArgumentException(sprintf('Invalid "%s" locale.', $locale));
        }
    }
`
``
See: https://github.com/symfony/translation/blob/master/Translator.php

**Comment by ismail1432** [comment]
Yep !
Maybe we can wait for Core Team member point of view

**Comment by xabbuh** [comment]
The docblock states that a string is expected here which `null` is not. IIRC we generally don't perform such checks.

**Comment by stof** [comment]
indeed, we currently don't make *any* guarantee about what happens when you violate the contract of the API (and this is what you do by passing `null` here). note that the behavior for such violation might change even in patch releases (there is really *no* BC guarantee for them)

**Comment by xabbuh** [comment]
closing as explained
