### ISSUE TITLE
[Process] Bug with the requirement to prepend `exec` to the command line

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony#27861]
**Symfony version(s) affected**: Possibly all, but was tested on 4.1

**Description**  

When creating a new `Process` object, it will prepend `exec` to the command line to be able to communicate with the process and send signals, but only if provided command line is an array.

However, on Linux Alpine distributions, `exec` does not seem to be available, implying the failure of any `Process` object created, whatever the command.

The problem is that this `exec` prefix is added only if the provided command line is an array, and is used as-is when it is provided as a string.

**How to reproduce**  

Take these two examples:

```php
$processArray = new Process(['ls', '-l']);
$processString = new Process('ls -l');
```

Add this `dump()` statement after these lines:

https://github.com/symfony/symfony/blob/7135aa43380c26a38524a045b42414efb45cf48f/src/Symfony/Component/Process/Process.php#L261-L268

```php
dump($commandline);
```

You should see something like this:

```
"exec ls -l"   <-- command line provided as array
"ls -l"        <-- command line provided as string
```

**Questions**

Why is this `exec` prepended only when command line is an array?

Does it have to be prepended if it is a string too?

**Possible Solution**  

For now, workaround is to provide a command line as a string instead of an array. But for the rest, it depends on the questions above.

**Comment by nicolas-grekas** [comment]
Do you have any reference about what you describe on Alpine? Exec is a feature of the shell and yes, it's required to drop the shell precisely.

**Comment by alexislefebvre** [comment]
> Exec is a feature of the shell

But there are many different shells. :)

I think that we can test it with the `alpine` docker image:

```bash
$ docker run alpine ls
bin
dev
[…]
$ docker run alpine exec ls
container_linux.go:247: starting container process caused "exec: \"exec\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"exec\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

**Comment by nicolas-grekas** [comment]
Reading the source code of PHP, it's even more explicit: `/bin/sh` is hardcoded there:
https://github.com/php/php-src/blob/master/ext/standard/proc_open.c#L840

**Comment by nicolas-grekas** [comment]
> docker run alpine exec ls

of course this doesn't work: the arguments passed to docker are not parsed by a shell.
I am not able to reproduce from a `docker run -it --rm php:alpine php -a`.
I can answer why it works this way, but unless there is an issue, all is working as expected.
But there is no description of anything wrong anywhere here, just of how it works.

**Comment by Pierstoval** [comment]
`sh` is not an issue because it's available on Alpine, but `exec` does not and it doesn't seem we can add it, or if we can I expect it to be a dirty hack.

Should we find a way to fix this in the `Process` component then? Or leave it as-is as an incompatibility?

**Comment by nicolas-grekas** [comment]
`exec` is a feature of `sh`, it cannot be "not avaiblable".
Please explain what is the behavior that should work and doesn't.
A reproducer would definitely help.

**Comment by Pierstoval** [comment]
Ok, the bug I actually had was not caused by Alpine, or at least I can't reproduce it with an empty Alpine docker image 😕 

I think the problem comes from the specific tool I wanted to use with Process.

Let's close for now and thanks a lot @nicolas-grekas for helping in Slack to debug this 👍
