### ISSUE TITLE
[Workflow] NotEnabledTransitionException thrown when it shouldn't?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#27862]
**Symfony version(s) affected**: 4.1.1

**Description**

In [`Workflow::apply()`](https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Workflow.php#L174-L176) we can see this code:

```php
        if (!$applied) {
            throw new NotEnabledTransitionException($subject, $transitionName, $this, $transitionBlockerList);
        }
```
And the [description of the Exception](https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Exception/NotEnabledTransitionException.php#L18) explains the usage:

> Thrown by Workflow when a not enabled transition is applied on a subject.

I'm wondering why the exception is thrown when `$applied` is false, it looks like it contradicts the source code. Is code documentation wrong? Is there a bug?

---

**Test**

In [`testApplyWithNotEnabledTransition`](https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Tests/WorkflowTest.php#L258-L278), the `t2` step is applied and this step exists: https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Tests/WorkflowBuilderTrait.php#L16

Why does it [throw a `NotEnabledTransitionException`](https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Tests/WorkflowTest.php#L269)? 

---

**How to reproduce**

IIRC, we had this exception when we tried to apply a transition but the current state of the object was not a starting point for the transition.

**Possible Solution**  
Check that these lines are consistent, refactor code to reflect the expected behaviour or update the documentation of the class.

**Comment by alexislefebvre** [comment]
> If I don't miss anything, the workflow in the test you linked to is in place "a" where transition "t2" is not enabled.

I don't see that it's not enabled, and `t2` is in the graph: https://github.com/symfony/symfony/blob/v4.1.1/src/Symfony/Component/Workflow/Tests/WorkflowBuilderTrait.php#L24

**Comment by lyrixx** [comment]
Hello @alexislefebvre 

An **enabled** transition is a transition that you can "take" / "pass thru". It does not mean the transition exist in the graph.

There are no issue here.

I let you read the [Petri net basics on wikipedia](https://en.wikipedia.org/wiki/Petri_net#Petri_net_basics) to get more information.

(I'm sorry, I'm not a native english speaker, So I miss some word to explain it clearly. I'm pretty sure Wikipedia does it better than me)

**Comment by alexislefebvre** [comment]
I understand now, thanks for the explanations.
