### ISSUE TITLE
Stray ? character in NullableConstructorArgumentDummy.php in symfony/serializer

### ISSUE THREAD

**Issue by razzed** [symfony/symfony#27864]
**Symfony version(s) affected**: Symfony/Serializer v4.1.1

**Description**  
Stray character in symfony/serializer/Tests/Fixtures/NullableConstructorArgumentDummy.php

**How to reproduce**  
From the command line:

    mkdir symfony-broken
    cd symfony-broken
    composer require symfony/serializer
    php -l vendor/symfony/serializer/Tests/Fixtures/NullableConstructorArgumentDummy.php
    PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in vendor/symfony/serializer/Tests/Fixtures/NullableConstructorArgumentDummy.php on line 18

    Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in vendor/symfony/serializer/Tests/Fixtures/NullableConstructorArgumentDummy.php on line 18
    Errors parsing vendor/symfony/serializer/Tests/Fixtures/NullableConstructorArgumentDummy.php

**Possible Solution**  
Remove the stray ? character in the __construct(?\stdClass $foo) on line 18

**Additional context**  
Not sure where this is included but I have a linter which runs across all files across my entire project and that's how this was picked up.

**Comment by Taluu** [comment]
This is because it's a php 7.1 construct, which indicates that an argument can take a `null` value.

**Comment by razzed** [comment]
Wasn't familiar with that 7.1 construct ... thanks for letting me know. I'm on 7.0, obviously. 

I lint the vendors because, oddly, sometimes vendors make mistakes, and production-level code needs to ensure that everything runs; I may exclude `vendors/` it in the future, however, but I'd rather all of the PHP code lint successfully in the version I'm running. I suppose it wouldn't make sense to instead use the PHP 7.0 construct which is nearly equivalent (aside from having a default value), e.g.

    function __construct(\stdClass $foo = null) {

Out of curiosity, why does the `composer.json` file for `symfony/serializer` require PHP >= 7.0.8 then? 

I'm going to assume you're answer is that "Test code isn't subject to the requirements in the `composer.json`", but I'll let you tell me that. It would be nice if the entire package was compatible with PHP 7.0 as it's advertised. I love bleeding edge myself, but the reality is that most production systems aren't bleeding edge.

If that's the case, perhaps add a 

    "require-dev": {
        "php": ">=7.1",

So it's crystal-clear.

Thanks!

**Comment by Taluu** [comment]
Actually, all of Symfony 4.0 is (or should be) `php >= 7.1`. Nice catch if not all components are updated for that...

ping @nicolas-grekas, and probably @dunglas as he's the maintainer of this component.

**Comment by razzed** [comment]
Well, that will then solve my problem then as it won't load this version on my 7.0 install. I'm a little new to bug reporting on GitHub - shall I create a new bug issue with the discovery or will your @ mentions of those folks direct them here and the magic will happen on its own?

**Comment by Taluu** [comment]
I think this issue is enough. :}

**Comment by ogizanagi** [comment]
Well, that's expected as this class is used in `testObjectWithNullableConstructorArgument()` test case, which requires PHP 7.1:

https://github.com/symfony/symfony/blob/7135aa43380c26a38524a045b42414efb45cf48f/src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php#L124-L127

The annotation above the test case ensure it isn't executed unless those requirements are satisfied.
It was actually added for a bug fix in 3.4 (https://github.com/symfony/symfony/pull/27389) where min PHP version required for using Symfony was `^5.5.9|>=7.0.8`. Note that the min PHP version in the composer.json only means the lowest PHP version supported. We also ensure forward compatibility with more recent PHP versions and need to add test cases to cover it.
A PHP 7.0 user can use the component or run the test suite without any issue, but linting vendor isn't expected at all.

The annotation is now useless on the 4.1 branch as the min PHP version is `7.1.3` If you'd like to contribute, you could submit a PR on 4.1 removing it :)

**Comment by razzed** [comment]
Now I understand, thanks; realized now I was using an older version of Symfony components (v3.4.12) in my project; but happy to contribute; added the PR. Closing.

**Comment by stof** [comment]
anyway, even when we advocate support for PHP 5.x, some test fixtures may still require newer PHP versions (to test support for such cases). So trying to run `php -l` on the Symfony tests in your vendor folder is not supposed to always work (it would forbid us to write such tests)
