### ISSUE TITLE
[DI][DX] Raise a warning at build-time if lazy=true is encountered, but ProxyManager bridge is not present

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#27865]
**Description**  

[The docs](https://symfony.com/doc/current/service_container/lazy_services.html) says:

> NOTE
> If you don't install the ProxyManager bridge and the ocramius/proxy-manager, the container will just skip over the lazy flag and simply instantiate the service as it would normally do.

This detail is vital to the functionality of lazy services (which might be yours or [3rd-party bundles'](https://github.com/snc/SncRedisBundle/pull/440), relying on it for specific features) and having it silently not working is confusing at best.

I propose DI raises a build-time warning for each `lazy=true` service if the bridge is not present.

**Comment by nicolas-grekas** [comment]
That should be doable as a compiler log. PR welcome.

**Comment by nicolas-grekas** [comment]
Implemented in #28060 as a compile-time exception when circular loops are found.
