### ISSUE TITLE
NotBlank validator should not invalidate null values

### ISSUE THREAD

**Issue by Taluu** [symfony/symfony#27876]
**Description**  
In most validators, there's a failsafe mecanism that prevent the validator from validating if it's a `null` value, as there's a validator for that (`NotNull`). I think `NotBlank` shouldn't bother on `null` values, especially as `NotBlank` and `NotNull` are used together to prevent `null` values too.

Not really a feature request, but not really a bug too... more like a RFC but for all versions. But I guess this would be a BC break though. :/ So maybe add a deprecated on the validator if it's a null value or something, and remove the `null` invalidation from the `NotBlank` on 5.0 ?

Currently, we need to reimplement the validator just to skip `null` values...

**Possible Solution**  
Either deprecate the validation on `null` value in `NotBlank`, or do as in most validators, (if `null` value, then skip). But as I mentionned, this would probably be a bc break.

**Comment by stof** [comment]
That would be a huge BC break.
And due to the form component setting properties to `null` when submitting an empty field, it might even be confusing to change the behavior of `NotBlank`. So I'm not sure it is worth it.

**Comment by theofidry** [comment]
Maybe we could add a `NullOrNotBlank` and potentially rename `NotBlank` to `NotNullNotBlank`. I'm not too happy with the names but IMO it's the original name that is messed up and we can't change it without BC breaks.

On a side note, I witnessed at least 10 Symfony projects where they declared a `NotBlank` ignoring `null` values, so I also strongly feel there is an issue here.

**Comment by ostrolucky** [comment]
> especially as NotBlank and NotNull are used together to prevent null values too.

Can you provide a source for this? We always use just NotBlank. Usage for NotNull is really rare in projects I've seen.

> rename NotBlank to NotNullNotBlank

How is "not blank" value ever null value? Blank includes null.


> I witnessed at least 10 Symfony projects where they declared a NotBlank ignoring null values,

For what use case?

**Comment by theofidry** [comment]
@ostrolucky because there is a need to check for non null empty values. `null` is often given either as "reset" or "not provided" value.

You can always argue that a form (for an API or not) - and I agree on paper. But in practice for a lot of front-ends omitting non provided fields as opposed to sending null requires too much work for what it's worth, hence this need in the back-end.

**Comment by ostrolucky** [comment]
If you have a text type field in your form and don't type anything there, it's transformed to null. If you omit that field completely, it's again null. There is no difference. This kind of problem is meant to be solved with validation groups.

**Comment by theofidry** [comment]
@ostrolucky I don't really see how that invalidates the points above tbh

**Comment by xabbuh** [comment]
If I don't misunderstand the proposal that would pretty much the same as having the `Length` constraint with `min` set to `1`, isn't it?

**Comment by theofidry** [comment]
Provides the value is a string but NotBlank also works on other types

**Comment by xabbuh** [comment]
How do you use it with other types if you do not want to fail on `null`? I mean do you rely on implicit type casts here?

**Comment by theofidry** [comment]
No we do explicit casts in your blank validator. We don't rely on `empty()` and if the value is `null` we don't validate it with this constraint

**Comment by xabbuh** [comment]
Well, my point is I don't see a use case for the `NotBlank` constraint when you are not validating a string. For other types there are better constraints IMO. Based on this assumption we only need to discuss whether or not we need to distinguish `null` from the empty string which brings us back to the question if we need a shortcut for the `Length` constraint with a minimum length of 1.

**Comment by ogizanagi** [comment]
@xabbuh : The issue with the `Length` constraint is that it ignores empty strings: https://github.com/symfony/symfony/blob/b226859e8a949c0b39071f61ffcc0b4c10e3ba46/src/Symfony/Component/Validator/Constraints/LengthValidator.php#L32-L34

**Comment by theofidry** [comment]
Which makes no sense to me neither tbh...

**Comment by ostrolucky** [comment]
You can also use NotEqualTo with ''

**Comment by theofidry** [comment]
@ostrolucky there is workaround, we are not saying otherwise. We would like however to make those constraints more intuitive

**Comment by Neirda24** [comment]
Definitely agreeing with @theofidry . When using any Constraints in symfony the first rule is "Do not validate what you are not supposed to", so I don't understand why there is a `NotBlank` validating null and a `NotNull`. maybe add something like `allowNull` in the `NotBlank` constraints but set it to deprecated...

We can always find a way to go around this of course. But to stay consistent with any other constraints I feel like `null` should not be tested by `NotBlank`...

**Comment by ostrolucky** [comment]
I don't agree for one. You can't deprecate that without majority agreeing. All I see is loud minority. What you guys want can be achieved with other constraints like Length and NotEqualTo, what NotBlank does currently can't be replaced with any other single constraint, only with multiple.

**Comment by theofidry** [comment]
Again, we are not arguing we cannot achieve what we want. There is several workarounds available for them and we already discussed about them here. Our point is that the default behaviour is confusing and intuitive. That you consider it to be a loud minority and not a design/UX issue is another story and up for debate and why this issue has been created.

**Comment by ostrolucky** [comment]
Seems intuitive to me. Null is blank, NotBlank prevents blank values.

**Comment by Neirda24** [comment]
I know this can be a huge debate but for me "the absence of value" does not mean "a blank value". Also `empty` in PHP also applies to arrays. So `[]` is empty but is not blank... (another reason why I also find it not intuitive).

**Comment by Taluu** [comment]
Adding an option `allowNull` (or something like that), defaulting to `false` would be a good BC imo, and would solve the current problem (and why not remove it on 5.0 ?). As @Neirda24 said, a `null` value is "no value" rather than "blank value"...

**Comment by zanbaldwin** [comment]
This is definitely an issue, especially as `null` values are common in APIs which Symfony is being used to build more and more.

Rather than deprecating existing validators/constraints (`NotBlank` should probably remain as it is because the Form component was historically built for web forms), it might be a good idea to create a new one (as mentioned above) that compliments the already existing two:

- A `NotEmpty` constraint would work exactly the same as `NotBlank` except allowing `null` values.
- The combination of `NotNull` and `NotEmpty` would be equivalent to `NotBlank`.
- APIs get a really useful constraint, whilst preserving backwards-compatibility.

I had a little play with what that might look like and came up with the following that **should** cover most data types an API would receive. It probably needs tidying up a bit if anyone thinks this is a good idea.

```php
/**
 * @Annotation
 * @Target({"PROPERTY", "METHOD", "ANNOTATION"})
 */
class NotEmpty extends Constraint
{
    public const IS_EMPTY_ERROR = '1034929d-a83b-4817-a722-0a4a9266067a';

    protected static $errorNames = array(
        self::IS_EMPTY_ERROR => 'IS_EMPTY_ERROR',
    );

    public $message = 'This value should not be empty, use null instead.';

    public function validatedBy(): string
    {
        return NotEmptyValidator::class;
    }
}
```

```php
class NotEmptyValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        if (!$constraint instanceof NotEmpty) {
            throw new UnexpectedTypeException($constraint, NotEmpty::class);
        }

        if ($value === null
            // Allow zero numerical values, etc.
            || (\is_scalar($value) && !\is_string($value))
            // Pure whitespace counts as being empty?
            || (\is_string($value) && \trim($value, " \r\n\t") !== '')
        ) {
            return;
        }

        if (empty($value) || (\is_string($value) && \trim($value, " \r\n\t") === '')) {
            $this->context->buildViolation($constraint->message)
                ->setParameter('{{ value }}', $this->formatValue($value))
                ->setCode(NotEmpty::IS_EMPTY_ERROR)
                ->addViolation();
        }
    }
}
```

**Comment by dunglas** [comment]
Adding a `allow_null` option is indeed a quick fix, and would help a lot when creating APIs. 👍 on my side.

**Comment by maryo** [comment]
I am not for changing the current behavior nor for deprecating it and I've never had a problem with NotBlank. I can imagine it to be useful in PATCH actions but I use a different system for them (resubmitting the missing previos values). Not sure how often the proponents of this change are gonna need it but if someone wants it to be the default behavior then he might want to use it frequently and then having to almost always specify this option seems weird to me. But it's true that there isn't an ideal solution.  Then isn't creating a new constraint like NotBlankOrNull more convenient?
