### ISSUE TITLE
Update to Symfony 4.1.1 from 4.1.0 broke route matching for specific routes

### ISSUE THREAD

**Issue by ronaldtb** [symfony/symfony#27871]
**Symfony version(s) affected**: 4.1.1

**Description**  
After an update to Symfony 4.1.1 the liip_imagine_filter route "/media/cache/resolve/{filter}/{path}" started returning a 404 response.

After some debugging I could trace the issue back to the generated regex in the srcDevDebugProjectContainerUrlMatcher.php file.

The problem seems to be caused by the change from `[^/]*+` to `(?:(?:[^.]*+\.)++)` near the "/account/" part.

*4.1.1 regex*  
`{^(?|(?i:www\.(mijnsponsoractie.localhost))\.(?|/admin/(?|organization/([^/]++)(?|(*:84)|/edit(*:96)|(*:103))|payment\-gateway/([^/]++)(?|/(?|edit(*:148)|methods/(?|(*:167)|new(*:178)|([^/]++)(?|/edit(*:202)|(*:210))))|(*:221))))|(?i:([^\.]++)\.(mijnsponsoractie.localhost))\.(?|/ac(?|count/(?|activeren/([^/]++)(*:314)|wachtwoord\-reset/([^/]++)(*:348))|ties/([^/]++)(*:370))|/crowdfunding/([^/]++)(?|(*:404)|/doneren(*:420))|/evenementen/([^/]++)(?|(*:453)|/(?|deelnemers/([^/]++)(*:484)|aanmelden(*:501)))|/peer\-to\-peer/([^/]++)(?|(*:538)|/(?|doneren(*:557)|start\-een\-actie(*:582)|acties/([^/]++)(*:605)))|/beheer/(?|a(?|ction/([^/]++)(?|(*:647)|/edit(*:660)|(*:668))|sset/([^/]++)(?|(*:693)|/edit(*:706)|(*:714))|dmin/eventregistration/([^/]++)(?|(*:757)|/edit(*:770)|(*:778)))|campaign/(?|crowdfunding/([^/]++)(?|(*:824)|/edit(*:837)|(*:845))|p2p/([^/]++)(?|(*:869)|/edit(*:882)|(*:890)))|donation/([^/]++)(?|(*:920)|/edit(*:933)|(*:941))|event(?|/([^/]++)(?|(*:970)|/edit(*:983)|(*:991))|package/([^/]++)(?|(*:1019)|/edit(*:1033)|(*:1042)))|in(?|voice(?|/([^/]++)(?|(*:1078)|/(?|edit(*:1095)|lineitems(*:1113))|(*:1123))|lineitem/([^/]++)(?|(*:1153)|/edit(*:1167)|(*:1176)))|stellingen/betalingen/([^/]++)(*:1217))))|(?:(?:[^.]*+\.)++)(?|/account/(?|activeren/([^/]++)(*:1280)|wachtwoord\-reset/([^/]++)(*:1315))|/media/cache/resolve/(?|([A-z0-9_-]*)/rc/([^/]++)/(.+)(*:1379)|([A-z0-9_-]*)/(.+)(*:1406))|/_(?|error/(\d+)(?:\.([^/]++))?(*:1447)|wdt/([^/]++)(*:1468)|profiler/([^/]++)(?|/(?|search/results(*:1515)|router(*:1530)|exception(?|(*:1551)|\.css(*:1565)))|(*:1576)))))$}sD`

*4.1.0 regex*
`{^(?|(?i:www\.(mijnsponsoractie.localhost))(?|/admin/(?|organization/([^/]++)(?|(*:82)|/edit(*:94)|(*:101))|payment\-gateway/([^/]++)(?|/(?|edit(*:146)|methods/(?|(*:165)|new(*:176)|([^/]++)(?|/edit(*:200)|(*:208))))|(*:219))))|(?i:([^\.]++)\.(mijnsponsoractie.localhost))(?|/ac(?|count/(?|activeren/([^/]++)(*:310)|wachtwoord\-reset/([^/]++)(*:344))|ties/([^/]++)(*:366))|/crowdfunding/([^/]++)(?|(*:400)|/doneren(*:416))|/evenementen/([^/]++)(?|(*:449)|/(?|deelnemers/([^/]++)(*:480)|aanmelden(*:497)))|/peer\-to\-peer/([^/]++)(?|(*:534)|/(?|doneren(*:553)|start\-een\-actie(*:578)|acties/([^/]++)(*:601)))|/beheer/(?|a(?|ction/([^/]++)(?|(*:643)|/edit(*:656)|(*:664))|sset/([^/]++)(?|(*:689)|/edit(*:702)|(*:710))|dmin/eventregistration/([^/]++)(?|(*:753)|/edit(*:766)|(*:774)))|campaign/(?|crowdfunding/([^/]++)(?|(*:820)|/edit(*:833)|(*:841))|p2p/([^/]++)(?|(*:865)|/edit(*:878)|(*:886)))|donation/([^/]++)(?|(*:916)|/edit(*:929)|(*:937))|event(?|/([^/]++)(?|(*:966)|/edit(*:979)|(*:987))|package/([^/]++)(?|(*:1015)|/edit(*:1029)|(*:1038)))|in(?|voice(?|/([^/]++)(?|(*:1074)|/(?|edit(*:1091)|lineitems(*:1109))|(*:1119))|lineitem/([^/]++)(?|(*:1149)|/edit(*:1163)|(*:1172)))|stellingen/betalingen/([^/]++)(*:1213))))|[^/]*+(?|/account/(?|activeren/([^/]++)(*:1264)|wachtwoord\-reset/([^/]++)(*:1299))|/media/cache/resolve/(?|([A-z0-9_-]*)/rc/([^/]++)/(.+)(*:1363)|([A-z0-9_-]*)/(.+)(*:1390))|/_(?|error/(\d+)(?:\.([^/]++))?(*:1431)|wdt/([^/]++)(*:1452)|profiler/([^/]++)(?|/(?|search/results(*:1499)|router(*:1514)|exception(?|(*:1535)|\.css(*:1549)))|(*:1560)))))$}sD`

**Comment by ronaldtb** [comment]
Changing the "symfony/routing" dependency to "4.1.x-dev" fixes the problem, thank you for the quick response.

**Comment by xabbuh** [comment]
@ronaldtb Thank you for the confirmation. 👍 I am closing here then.
