### ISSUE TITLE
Installation of var-dumper bundle in framework-standard-edition (with Symfony 3.4.8) fails

### ISSUE THREAD

**Issue by gsymfoner** [symfony/symfony#27884]
I want to install  the var-dumper bundle in my framework-standard-edition project (based on Symfony 3.4.8)
Executing the following command:
composer require symfony/var-dumper --dev
leads to dependency errors:
Using version ^4.1 for symfony/var-dumper
 ./composer.json has been updated
 Loading composer repositories with package information
  Updating dependencies (including require-dev)
  Your requirements could not be resolved to an installable set of packages.
   Problem 1
            - Conclusion: remove sensio/distribution-bundle v5.0.21
            - Conclusion: don't install sensio/distribution-bundle v5.0.21
   ...
- Installation request for symfony/symfony ^4. -> satisfiable by symfony/symfony[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
Installation failed, reverting ./composer.json to its original content

I don't kwnow how to solve this problem.
I don't understand, why symfony 4. is requird, as the var-dumper Bundle surely is also available for symfony 3.4.8  (var-dumper :  branches  2.x , 3.x (and 4.x ) available in github repository.
Have i to manipulate my composer.json or composer.lock file?
@gsymfoner

**Comment by nicolas-grekas** [comment]
try `composer require symfony/var-dumper:3.4`

**Comment by xabbuh** [comment]
actually, try `composer require symfony/var-dumper: ^3.4` to allow for all available releases of 3.4

**Comment by nicolas-grekas** [comment]
I hope you managed to make it work. I'm closing as there is no bug here.
