### ISSUE TITLE
Form does not add required attribute to input nor label to sub forms unless required is true

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#27881]
**Symfony version(s) affected**: 4.1.1

**Description**  
When including a sub-form in a formtype, a `required` attribute can be marked as true/false. If populating the subform is optional, you may choose to set this to be false. However the subform does not have the required labels and inputs (to populate the entity) marked as such with a required class / attribute. To obtain the required class, you have to mark the sub form as being required.

**How to reproduce**  
 - Create two types, which have a relationship, where each have both not null and nullable properties.
 - in the buildForm method of the FormType for the owning class, add a CollectionType of the sub form.
```
        $builder
            ->add('title')
            ->add('methods', CollectionType::class, [
                'entry_type' => ShippingMethodType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'delete_empty' => true,
                'required' => true,
            ])
```
- Render the form and you'll see the required properties have the required class / attribute, whilst those that are not required do not.
- Change `required` to false in the above form definition, and the required disappear.

**Possible Solution**  
Regardless of required or not, add the required class to the properties that are required. If the subform is required, add the required on the label for the subform as well.

**Additional context**

**Comment by xabbuh** [comment]
Are we only talking about the `CollectionType` here or do you observe the same behaviour with other form types too?

**Comment by ChangePlaces** [comment]
@xabbuh I've only tried with `CollectionType`

**Comment by xabbuh** [comment]
For the `CollectionType` configuring the `required` option for the nested type in `entry_options` is probably the solution.

**Comment by ChangePlaces** [comment]
@xabbuh I've tried `'entry_options' => ['required' => true, 'label' => false],` with the outer form with `required => false` to no avail.

**Comment by xabbuh** [comment]
Can you create a small example application allowing to reproduce your issue?

**Comment by ChangePlaces** [comment]
Sorry, I've been busy - how much of an example application would you need?

**Comment by xabbuh** [comment]
The best would be a small Flex based application where we would just have to run `composer install`.

**Comment by ChangePlaces** [comment]
I have not had the time for myself let alone this!

**Comment by xabbuh** [comment]
Let's close this for now then. We can reopen when there is a reproducible example.

**Comment by ThomasLandauer** [comment]
@xabbuh: While investigating https://github.com/EasyCorp/EasyAdminBundle/issues/2673 I stumbled upon this issue here. I've set up an example repository at: https://github.com/ThomasLandauer/easyadminbundle-issue-2673

Instructions:
* Start some server in public
* Open http://localhost:8000/ and view the source code => no `required` attribute there!

**Comment by ThomasLandauer** [comment]
@xabbuh: Yeah, I know, I disabled them on purpose ;-) For this issue here you don't need any constraints. The `required` attribute should be present anyway.

**Comment by xabbuh** [comment]
> The `required` attribute should be present anyway.

I don't understand this sentence. Why should it be present?

**Comment by ThomasLandauer** [comment]
Cause that's how it is explained in the docs at https://symfony.com/doc/current/forms.html#field-type-options
> By default, the `required` option is set to `true`

And I also remember that it did work this way when I first used Symfony (~v2.8). So was this changed on purpose (then the docs should be updated) or is it a bug?

**Comment by xabbuh** [comment]
If you omit the form type when building a form, the `required` option is guessed as well as the form type which, for example, takes Doctrine and validation metadata into account. Maybe we need to clarify the docs around form type guessing.
