### ISSUE TITLE
Translations not working if 'fallbacks' and 'default_locale' are identical (en)

### ISSUE THREAD

**Issue by kyg** [symfony/symfony#27883]
**Symfony version(s) affected**: 4.1 (Possibly others, not tested)

**Description**  
Translations for the default locale do not work if ```default_locale``` and ```fallbacks``` are identical,
for example ```'en'``` or ```'%locale%'``` for both.

**How to reproduce**  
* ```composer create-project symfony/website-skeleton Test-Project```
* Create a Controller and render a template.
* Somewhere in the template add a translation string, for instance ```{{ 'test.string'|trans }}```
* Run ```./bin/console translation:update --dump-messages --force en``` to create a translation file (```messages.en.yml```) in the translations folder
* Go to the previously defined route and you will see the key is not translated, instead the key itself is being rendered.

**Possible Solution**  
This can be fixed by simply replacing the ```fallbacks``` locale with one that differs from the ```default_locale```, or by adding multiple fallback locales. It does not even have to be a valid locale, any string will work and lead to the translation being displayed properly. It it also possible to simply not provide any ```fallbacks``` due to ```en``` being set as a default internally.

I am not certain if this is the intended outcome, but I believe it should not be this way.

Edit: The issue only seems to occur when the locale ```en``` is used. If I try the exact same steps above but replace ```en``` with ```nl```, the translation works properly.

**Comment by xabbuh** [comment]
Did you clear the cache after you created the translation file in your first example?

**Comment by kyg** [comment]
I tried clearing the cache several times, the issue still persists. I don't think this is related to any caching issues, it has something to do with how the fallback locales are handled.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by kyg** [comment]
I am not sure what caused my initial problem, but after setting up a new vagrant box with a clean installation of symfony 4.1 the problem is gone and the translations are working again.

**Comment by kyg** [comment]
Turns out you were right @xabbuh , the issue was cache related. I'm not sure why, but ```php bin/console cache:clear``` did not do the trick for me.. I had to manually delete my cache by deleting the actual directory.
