### ISSUE TITLE
Rename FileLoaderLoadException to LoaderLoadException

### ISSUE THREAD

**Issue by ProgMiner** [symfony/symfony#27895]
**Description**  
[`FileLoaderLoadException`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Exception/FileLoaderLoadException.php) exception is used not only by [`FileLoader`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Loader/FileLoader.php) and other file loading classes but also [`Loader`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Loader/Loader.php) and other classes that can load not file-based resources.

In this regard, I suggest rename this exception from `FileLoaderLoadException` to `LoaderLoadException`.

**Example**
*This is just a cosmetic change to improve the organization of the code without any action.*

**Comment by xabbuh** [comment]
For BC we would need to deprecate the old class name and treat it as an alias for the new one. While that would be a bit more precise, I am not sure if it's really worth the effort.

**Comment by ProgMiner** [comment]
I think this RFC might stay until the next major release. However, if it is really too hard, I will not insist on my suggestion.

**Comment by fabpot** [comment]
Waiting for the next major release won't change anything. We always need to provide an upgrade path. So, the only way is what @xabbuh described: deprecating the old class so that people have time to upgrade to the new one and remove the class in the next major version.
