### ISSUE TITLE
Calling Request::setSessionFactory() "initializes" the session

### ISSUE THREAD

**Issue by dusan-rd** [symfony/symfony#27900]
**Symfony version(s) affected**: 4.1.0 +

**Description**  
Calling `$request->setSessionFactory()` "initializes" the session. 
In `Symfony\Component\HttpKernel\EventListener\AbstractSessionListener` setSessionFactory is called if there is no session, and Request::hasSession() always returns true, so [this blog post](https://symfony.com/blog/new-in-symfony-4-1-session-improvements) is not correct.

**How to reproduce** 

https://github.com/symfony/symfony/blob/f06587388106ddb69177cd8737139f8fd5d8ca18/src/Symfony/Component/HttpFoundation/Request.php#L753-L764

```
    $request = Request::createFromGlobals();
    $hasSession = $request->hasSession(); // false

    $request->setSessionFactory(function() {});
    $hasSession = $request->hasSession(); //true
```

**Possible Solution**  
Request::setSessionFactory shouldn't set Request::session, it should set different class variable.

**Comment by nicolas-grekas** [comment]
Hello, I don't understand what's wrong here. The description matches how things are designed: calling `setSessionFactory` sets the session without yet creating the instance. `hasSession` thus returns true, telling you that if you call `getSession`, you'll get something back. `setSessionFactory` doesn't initializes the session: `getSession` does.

**Comment by dusan-rd** [comment]
Oh, I totally misunderstood v4.1 changes, I apologize.
Actually had problems with session and http cache because of this, already fixed, issue https://github.com/symfony/symfony/commit/fd8fd3df477ff78b194bf5a8e427e1fa14ab1265
