### ISSUE TITLE
Reading from NamespacedAttributeBag adds entries to session

### ISSUE THREAD

**Issue by Gemineye** [symfony/symfony#27912]
**Symfony version(s) affected**: 3.4.12

**Description**  
If i call $session->get('foo/bar/name') on a clean session I will end up with data in the session. 
In my opinion a "get" should not create any entries.

**How to reproduce**  

$session->get('foo/bar/name');
dump($session->get('foo'));

I would expect to see 'null' but i get an array containing "bar => null"

**Comment by webnet-fr** [comment]
This clearly looks a bug. It comes from this line: 

https://github.com/symfony/symfony/blob/3cfdc9e9d739dda0bc8d222d458e6bbb34c10c72/src/Symfony/Component/HttpFoundation/Session/Attribute/NamespacedAttributeBag.php#L127

Pity that we didn't have any appropriate test to spot this bug earlier. 
The quickiest solution I can imagine would be to replace that line with this snippet:

```php
if (!$writeContext) {
    $null = null;

    return $null; // return by reference forces this trick
}

$array[$part] = array();
```

But I would rather not use `resolveAttributePath` method in `has` and `get` methods, IMO that will be clearer.

I can propose a PR later on with extended tests.

Satatus: Reviewed
