### ISSUE TITLE
RememberMe token should be hashed in the database

### ISSUE THREAD

**Issue by aschempp** [symfony/symfony#27910]
**Symfony version(s) affected**: any (since 2.0)

**Description**  
Symfony security supports two different types of rememberme cookies. Persistent rememberme tokens are stored in the database to prevent identity theft. They store a _series_ (sort of like a username for your token) and the _token_ (sort of your password). For each series/username, the token is changed on every successful rememberme login.

If someone get's access to a database dump for any reason, he can possibly manually add a rememberme cookie to his browser and be authenticated by Symfony automatically. To prevent such attach, it is recommended to hash the token value in the database (see [How to Secure Long-Term Authentication](https://paragonie.com/blog/2015/04/secure-authentication-php-with-long-term-persistence#secure-remember-me-cookies) article by Paragon IE). 

This is currently not done in Symfony, and adding it would generally improve security.

**How to reproduce**  
This is more of a theoretical issue in the security implementation, reproducing it would require manipulating your browser cookies.

**Possible Solution**  
The `PersistentTokenBasedRememberMeServices` implementation should be adjusted to store hashed passwords and authenticate for them.

**Additional context**  
I'm very much willing to create a PR for this if the Symfony security experts agree that things should be changed (and for which version). We also need to decide on whether all existing rememberme cookies will become invalid after this implementation or we should continue to support unencrypted database values (for until the user has logged in once and the token is updated).

**Comment by paragonie-scott** [comment]
>  be sure to use a secure hashing system (either bcrypt or Argon) as recommended by the article.

To be clear: the remember me token only needs a SHA256 hash (or equivalent), not bcrypt/Argon2. These tokens are not created by, nor remembered by, humans. They are high-entropy strings that should not require key stretching to be secure. (Otherwise, they were generated poorly.)

Using bcrypt/Argon2 doesn't *hurt* against brute force attackers, but it's a waste of server-side processing power.

**Comment by leofeyer** [comment]
This is how we have currently implemented in your `DatabaseTokenProvider` class:

https://github.com/contao/contao/pull/53/files#diff-74ef2c48393b0a804524d75fee46b1e5

If you agree with the changes, I can create a PR to adjust the [`DoctrineTokenProvider`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Security/RememberMe/DoctrineTokenProvider.php) accordingly.

**Comment by chalasr** [comment]
PR welcome.

**Comment by nicolas-grekas** [comment]
Please check PR #27910
