### ISSUE TITLE
[Profiler] rendered templates always show the vendor one.

### ISSUE THREAD

**Issue by lerminou** [symfony/symfony#27911]
**Symfony version(s) affected**: 4.1

**Description**  
In the Web-Profiler component  the section 'Rendered Templates' seems to show the template from vendor when we override one of them

When we mouse-on the template, the path is good (to the vendor directory or the overriden one) but the label always show @FOSUser/layout.html.twig.

Is there any issue here ? it's difficult to really see which templates are rendered.
Maybe an @app/@FOSUser/layout.html.twig can help to show overriden files ?

**How to reproduce**  
I tried with the FOSUserBundle layout.thig file.
The base template is vendor/friendsofsymfony/user-bundle/Resources/views/layout.html.twig

I override this template in the following directory : templates/bundles/FOSUserBundle/layout.html.twig

Please, have a look at the screenshots.

**Additional context**  
From app directory:
![overriden template](https://user-images.githubusercontent.com/3818051/42495734-3418f3a0-8424-11e8-99dd-7f2611ea6be6.png)

From vendor:
![base template](https://user-images.githubusercontent.com/3818051/42495732-33efa2ac-8424-11e8-9316-39d0046db1ae.png)

**Comment by xabbuh** [comment]
IMO that's expected. What you see here is the template name. To which path that is resolved depends on which template files actually do exist in your application. Maybe we could add another column including the filename relative to the project directory though.

**Comment by stof** [comment]
That's because `@FOSUser/layout.html.twig` is not a path at all. When you override a template, you don't change the template name. You change the source file being used for this name. The template being rendered is still called `@FOSUser/layout.html.twig` (and this is the reason why FOSUserBundle is able to use your overriding template without having to be told about its existence: it does not have a different name)

**Comment by lerminou** [comment]
Thanks for your answer. 
Maybe we can implement a visual effect (to define) to indicate that the template is overriden?

**Comment by ro0NL** [comment]
> it's difficult to really see which templates are rendered

The list is clear, these are all "Rendered templates"

> Is there any issue here ?

I'd say no :) Basically why do you want to know it's a vendor or app template _upfront_? It's being rendered either way...

**Comment by stof** [comment]
> Maybe we can implement a visual effect (to define) to indicate that the template is overriden?

that would require extra work, because it would force to look for all potential location for this template name (to see whether there are multiple existing files) instead of just reading the info from the template object.
Thus, that's not even something the Twig loader allows doing (as its job is to find the source to use, not all other potential sources to ignore).

**Comment by yceruto** [comment]
Perhaps showing the relative path could help a bit to quickly understand which file was rendered:

![rendered-templates](https://user-images.githubusercontent.com/2028198/42530695-d5f6f106-844f-11e8-9777-7e9545882f77.png)

**Comment by lerminou** [comment]
Or to be more compact as actual. We can check if the path begins by 'vendor/'. And if not then we can show a little button or message
@apfelbox yes. I was debugging too and that was the origin of my question.

**Comment by ro0NL** [comment]
I like the proposal by @yceruto, agree a filepath reference is more recognizable then its logical name, without having to hover each link currently.

I don't see any real reason to treat vendor/ templates any different then non-vendor templates, e.g. visually. That's not really relevant IMHO.

**Comment by apfelbox** [comment]
I would just take the proposal by @yceruto as is. :ok_hand:

**Comment by yceruto** [comment]
We could also add a new option to the `debug:twig` command to look for template paths:
```bash
$ bin/console debug:twig --find=@FOSUser/layout.html.twig
templates/bundles/FOSUserBundle/layout.html.twig (default)
vendor/friendsofsymfony/user-bundle/Resources/views/layout.html.twig
```
We would see all the possible templates that match the given name and the search could be easier.

**Comment by yceruto** [comment]
Proposal https://github.com/symfony/symfony/pull/27978 to improve the Twig panel

**Comment by yceruto** [comment]
and see https://github.com/symfony/symfony/pull/27981 for a debug command ;)
