### ISSUE TITLE
Semantic UI form theme

### ISSUE THREAD

**Issue by dfridrich** [symfony/symfony#27928]
**Description**  
Semantic UI is very popular CSS framework. In some cases much better than Twitter Bootstrap. It would be great if Symfony form would support it out of the box. There is even no recommended twig file for Semantic UI so I am creating this issue in their Github too (https://github.com/Semantic-Org/Semantic-UI/issues/6475).

Useful gist can be found here: https://gist.github.com/TorbenKoehn/4c0180c87393bd44315da523f7971b33

**Comment by javiereguiluz** [comment]
I'm not opposing to this proposal ... but Bootstrap is immensely more popular than Semantic UI and that's why we added it in the Symfony core:

![github-popularity](https://user-images.githubusercontent.com/73419/42580999-1760dada-852c-11e8-951d-517080305b7a.png)

**Comment by fabpot** [comment]
I'm fine with adding support for it, but only if someone does the PR and is committed to maintain it over time.

**Comment by dfridrich** [comment]
I'll prepare PR.

**Comment by mbabker** [comment]
Just to add on here, the Sylius UI is built using Semantic UI, so it's possible you'd find some support for maintaining it from there.

**Comment by sstok** [comment]
The stars and watchers of the Sematic-UI are less as the development is (was?) bit a stagnated, Bootstrap is maintained by the (former) people of Twitter while Sematic-UI is mostly maintained by a single person with some help from volunteers on managing issues. There are some major components missing and not many are willing to financially support the project 😞 

It has major potential still, but compared to Bootstrap it's less documented (at the time) and requires a change in mindset (in you are not a frontend developer) which to me was getting more and more annoying.

Having said all this: 👍

**Comment by xabbuh** [comment]
I am closing here as nobody came up with a PR yet. This doesn't mean that we won't review a PR that would provide this seems, but we don't have to keep this issue open if noone is interested in contributing this new theme.
