### ISSUE TITLE
after updated i have a error in Translator.php file character ? in constructor. 

### ISSUE THREAD

**Issue by ferbj** [symfony/symfony#27930]
**Symfony version(s) affected**: x.y.z
Using Laravel 5.5
**Description**  

after updated with composer update in console i got a error 
![image](https://user-images.githubusercontent.com/12809233/42588584-dcd2f97a-8503-11e8-9ea4-e8273d84c57a.png)

**How to reproduce**  

the bug is produced after update with composer. 
**Possible Solution**  

i remove the  ? string in the function construct. 
**Additional context**  

Try to explain why in the construct put the '?' character..

**Comment by dmaicher** [comment]
That code with `?string` is PHP 7.1+ compatible :wink: 

http://php.net/manual/de/migration71.new-features.php

**Comment by xabbuh** [comment]
@dmaicher is right. If you want to use Symfony 4, you will need to use PHP 7.1. I am closing here as there is nothing to fix.

**Comment by ferbj** [comment]
Ok, im using php 7.0 i dont know that ?string is php 7.1 , thank you for the explanation.
