### ISSUE TITLE
Cookie::isCleared() with expire === 0

### ISSUE THREAD

**Issue by mlocati** [symfony/symfony#27946]
**Symfony version(s) affected**: 4.1.1

**Description**  
The `expire` field of a Cookie object (accessible with `getExpiresTime()`) is used when calling [`setrawcookie`](http://php.net/manual/en/function.setrawcookie.php).
From the PHP manual, if `expire` is `0`, the cookie will expire at the end of the session (when the browser closes).
So, a cookie with `expire` set to `0` is valid. BTW `isCleared` returns `true` in this case.

**How to reproduce**  
```php
$cookie = new Symfony\Component\HttpFoundation\Cookie('foo', 'bar');
var_export($cookie->isCleared());
$cookie = new Symfony\Component\HttpFoundation\Cookie('foo', 'bar', 0);
var_export($cookie->isCleared());
```
it should be `false` in both cases, but it is `true`.

**Possible Solution**  
Patch the `isCleared` method, changing from
```php
return $this->expire < time();
```
to
```php
return 0 !== $this->expire && $this->expire < time();
```

**Comment by ro0NL** [comment]
@mlocati looks like you're right. Willing to do a PR?

**Comment by mlocati** [comment]
I'm a few thousands miles away from my PC for a couple of weeks. But feel free to patch it yourself

**Comment by nicolas-grekas** [comment]
Just wondering: why should `0` be a special value? The `Cookie` class doesn't have to match wheat `setrawcookie()`, does it? PHP needs a way to define a session cookie, and passing `0` is the way to go, but `Cookie` does it differently and thus doesn't need to treat `0` is a special way.
Does this make sense?

**Comment by ro0NL** [comment]
it is a special value

https://github.com/symfony/symfony/blob/0eea07752211f464818a54efc7907e8ca4c617a6/src/Symfony/Component/HttpFoundation/Cookie.php#L138-L140

**Comment by nicolas-grekas** [comment]
Thanks, bug confirmed to me also then, PR welcome :)
