### ISSUE TITLE
Invalid .env file causes no exception output - just blank screen

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#27949]
**Symfony version(s) affected**: 4.1.1

**Description**  
Having an invalid .env file causes a blank screen to be output when rendering a view. No outward sign of an error pointing to an invalid .env file. Only the server log file gives the clue:

```
2018/07/13 23:42:19 [error] 825#825: *2521 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Whitespace are not supported after the variable name in "/var/www/html2/public/../.env" at line 45.
...CCOUNT_DISPATCH_TIME = 1\n\n\n...
                      ^ line 45 offset 2082 in /var/www/html2/vendor/symfony/dotenv/Dotenv.php:400
Stack trace:
#0 /var/www/html2/vendor/symfony/dotenv/Dotenv.php(164): Symfony\Component\Dotenv\Dotenv->createFormatException('Whitespace are ...')
#1 /var/www/html2/vendor/symfony/dotenv/Dotenv.php(123): Symfony\Component\Dotenv\Dotenv->lexVarname()
#2 /var/www/html2/vendor/symfony/dotenv/Dotenv.php(57): Symfony\Component\Dotenv\Dotenv->parse('# This file is ...', '/var/www/html2/...')
#3 /var/www/html2/public/index.php(15): Symfony\Component\Dotenv\Dotenv->load('/var/www/html2/...')
#4 {main}
  thrown in /var/www/html2/vendor/symfony/dotenv/Dotenv.php on line 400" while reading response header from upstream, 
```

**How to reproduce**  
As you can see above, the .env file had a space between the env var name, the `=` and the value. Rendering a view from a controller with this error gives no output

**Comment by xabbuh** [comment]
I am not sure if we can do anything here. The `.env` file is parsed right at the beginning before any Symfony code has been bootstrapped and thus no custom error handler has been registered yet.

**Comment by nicolas-grekas** [comment]
We could set display_error to 1 in the front controller, ie in the flex recipe. That's the only solution I can think of we could commit somewhere.

**Comment by mleczakm** [comment]
Simple fix - set `display_errors=1` in your php config ;)

**Comment by ChangePlaces** [comment]
wouldn't setting display_errors=1 be insecure (assuming it wasn't caught during testing - e.g. a last minute change)

**Comment by nicolas-grekas** [comment]
If anything, this could be handled at the recipe level: we could set `display_errors` to `0` during early bootstrap, then turn it to `1` once the kernel is created (of just before it is). If this is considered too risky, we could do that only for the `bin/console` script, so that at least there is one place that screams.
I'm closing as there is nothing to fix in Symfony itself.
PR welcome on https://github.com/symfony/recipes/ if you want to make it happen.
