### ISSUE TITLE
[WebProfilerBundle] - Icons alignment fails with Bootstrap v4.1.2

### ISSUE THREAD

**Issue by pweyl** [symfony/symfony#27942]
**Symfony version(s) affected**: 4.1.1

**Description**  
Since I migrated to Bootstrap v4.1.2 (CSS framework), WebProfilerBundle icons alignment fails.

**How to reproduce**  
I have replaced SASS files and compile it.

**Additional context**  
Before : with Bootstrap v4.1.1
![before](https://user-images.githubusercontent.com/5527353/42695618-462be1e4-86b6-11e8-9c7c-679a540844bf.png)

After : with Bootstrap v4.1.2
![after](https://user-images.githubusercontent.com/5527353/42695738-907cfc88-86b6-11e8-9c11-32bffe8189d2.png)

**Comment by Padam87** [comment]
Can confirm.

Fix:
```css
.sf-toolbar-icon svg {
  vertical-align: baseline;
}
```

**Comment by Kocal** [comment]
PR: https://github.com/symfony/symfony/pull/27941
