### ISSUE TITLE
Bug: Attempted to load interface "ResetInterface"

### ISSUE THREAD

**Issue by topwebstudio** [symfony/symfony#27951]
**Symfony version(s) affected**: 4.2-dev 

**Description**  
Attempted to load interface "ResetInterface" from namespace "Symfony\Contract\Service".
Did you forget a "use" statement for "Symfony\Contracts\Service\ResetInterface"?
in DebugProcessor.php line 20
 
**composer.json**  
[composer.zip](https://github.com/symfony/symfony/files/2194854/composer.zip)

**Comment by xabbuh** [comment]
Can you show the output of `composer show`?

**Comment by topwebstudio** [comment]
[output.txt](https://github.com/symfony/symfony/files/2194900/output.txt)

**Comment by xabbuh** [comment]
@fabpot It looks like the changes from #27947 were not propagated to the subtree split for the Monolog bridge.

**Comment by fabpot** [comment]
Fixed since then.
