### ISSUE TITLE
Yaml\Parser isBlockScalarHeader is slow

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#27960]
**Symfony version(s) affected**: 3.4.11

**Description**  
when parsing yaml files the method `Yaml\Parser::isBlockScalarHeader` is oftentimes on the hotpath, because doing a lot of `preg_match` calls.

see
![grafik](https://user-images.githubusercontent.com/120441/42750473-a2f563d6-88e7-11e8-9e03-0d4acb24bf5a.png)

would it make sense to do a cheaper fast-fail check before actually invoking the regex-engine?

I do not have yet a proper feeling of what this method is trying to check and why, so my suggestion might be rubbish.

**Comment by xabbuh** [comment]
Can you show an example YAML file that show this or a similar profile?

**Comment by xabbuh** [comment]
Can you check if #28106 improves the situation?

**Comment by staabm** [comment]
I will double check on the weekend.

**Comment by staabm** [comment]
It looks like my issue was solved, thx
