### ISSUE TITLE
Symfony notification system

### ISSUE THREAD

**Issue by ed-fruty** [symfony/symfony#27963]
I think this question was discussed already, but I can't find correct answer. 
But so far in the symfony there is no tool for sending notifications out of the box.
I mean notification via slack/email/telegram/viber/sms etc.
I know about wonderful component as `messenger`.

What will be the best practices to use? Will write  our own transport for messenger component (will you expect pull requests for a new transports in such way) ? Or maybe you plan to create another symfony component `notifications` ? 
Or only third party bundles ?

The main thing is to find preferred and easily to use way to send notifications with the symfony.

Thanks!

**Comment by lyrixx** [comment]
Messenger Componant does not really fit this usage.

In your case you can simply use the API of 3rd party services (slack/email/telegram/viber/sms)
Note: almost all 3rd party services have open source package to interact with their API.

**Comment by ed-fruty** [comment]
@lyrixx , I am in a little confuse that such powerful framework with a lot of features doesn't provide any notification integration.

It's not difficult to use one of 3rd party packages  but the question is about official instrument (component).
It something like [laravel has](https://laravel.com/docs/5.6/notifications).

Is it in plans ? I think if it will approve - a lot of pull requests will be submitted. Where it can be discussed?

**Comment by chr-hertel** [comment]
you could easily use monolog for this. there are are plenty of [built in handlers](https://github.com/Seldaek/monolog/tree/master/src/Monolog/Handler) easily configured using Symfony's monolog bundle: [slack example](http://php-symfony.uk/monolog-send-critical-logs-directly-to-slack/)

**Comment by ed-fruty** [comment]
@chr-hertel , if I'm not mistaken, the responsibility of monolog - logs, not notifications about new order for example, isn't it?

And I will repeat again, the question is not about how to do this using hooks. What about independent notification system as a part of symfony components?

**Comment by ed-fruty** [comment]
@fabpot , could you share your vision?

**Comment by curry684** [comment]
I don't really see a case here. Anything Symfony could standardize would require more glue code, config and dependencies than just wiring up the required third party packages yourself.

**Comment by ed-fruty** [comment]
I mean an abstraction layer above the transports (drivers).

Like a command bus, you push your notification and it can be transferred via different transports.

**Comment by ed-fruty** [comment]
@curry684 , according to your mind, symfony should not provide integration (bridge) with twig/doctrine/monolog ;)

**Comment by iltar** [comment]
@ed-fruty please edit your previous message instead of posting multiple in a row, as people get extra notification while it's not really necessary.

It's something that can easily be picked up by a vendor. I've written a component similar to this before, but specific for the company needs and it's not really anything special. If it's a nice component, it can always be considered to integrate it (or something similar) into Symfony.

**Comment by ed-fruty** [comment]
@iltar , ok,  thanks.

And I said it at the beginning, It's not a problem to create such component and I can do it and create pull request to integrate it.
I want to discuss with a community, does it need? Will it be helpful ? Or maybe you have another opinion.

**Comment by iltar** [comment]
What about the sonata bundle? https://sonata-project.org/bundles/notification/3-x/doc/reference/usage.html

Other than that, I don't see any decent existing packages that don't have bloated dependencies or configuration. If you think it would be nice to have, build a vendor package and see if people like it. I think people can use it, while others are satisfied using monolog.

**Comment by ed-fruty** [comment]
@iltar , I am agree with you. And I got a question with a think that it's a lot of different vendor packages exists and no one official.

offtopic.
I know a few situations when notifications/broadcasting/queues out of the box made a decisive decision in a choose of framework for a new project... (it was before messenger component). 
I say it because I think it would be a great to have such features 
(and to lure more developers to the ~~dark side~~ symfony :smile:)

**Comment by curry684** [comment]
> according to your mind, symfony should not provide integration (bridge) with twig/doctrine/monolog ;)

Bridging first class citizens properly has nothing to do with it.

The argument is simply that, to integrate for example Slack, you can just `composer req maknz/slack` and add this to your `services.yaml`:
```yaml
Maknz\Slack\Client:
  arguments:
    - "https://hooks.slack.com/your-hook"
    - username: NotificationBot
      channel: '#notifications'
```
And you're done, no bridges, no glue code whatsoever. You have just written a full-blown Slack integration with 0 lines of code.

The interesting part would indeed be a generic notification broker capable of notifying via Web Push, Slack, text, whatsapp, anything. This would by definition be a highly opinionated collection of limited vendor integrations, because unline AMQP in Messenger, there is no standard to work with whatsoever. And to bridge all those possible platforms in all possible ways, this....

> would require more glue code, config and dependencies than just wiring up the required third party packages yourself

Which is what I said.

**Comment by Pierstoval** [comment]
You could use the Event Dispatcher + the SDK of any 3rd party tool you want to use.

For example:

* A new comment is posted on a blog post
* The controller saves the comment
* Then, it runs `$eventDispatcher->dispatch('comment.posted', new GenericEvent($comment));`
* You have many subscribers listening to this event, such as `CommentSubscriber`, that could look like this:

```php
<?php

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use \Symfony\Component\EventDispatcher\GenericEvent;

class CommentSubscriber implements EventSubscriberInterface 
{
    public static function getSubscribedEvents() {
        return [
            'comment.posted' => ['notifyPostedComment'],
        ];
    }

    public function notifyPostedComment(GenericEvent $event)
    {
        /** @var Comment $comment */
        $comment = $event->getSubject();
        
        // These private methods can call external services
        $this->notifyToSlack($comment);
        $this->notifyToByEmail($comment);
    }
}
```

Then put all the notification logic to external services, like a `SlackNotifier`, `EmailNotifier`, etc.

**Comment by Pierstoval** [comment]
> The interesting part would indeed be a generic notification broker capable of notifying via Web Push, Slack, text, whatsapp, anything. This would by definition be a highly opinionated collection of limited vendor integrations, because unlike AMQP in Messenger, there is no standard to work with whatsoever. And to bridge all those possible platforms in all possible ways, this....

Just noticed this part: If you're looking for this kind of "very live notification", maybe PHP isn't the right language to do it, as it's not meant to be asynchronous and therefore needs middlewares to implement many messaging tools (such as Symfony's Messenger component).

**Comment by michaelperrin** [comment]
@ed-fruty Looks like you've been heard :) https://speakerdeck.com/fabpot/symfony-notifier

**Comment by curry684** [comment]
Funny enough slide 36 makes my point about all the glue code needed for specific transports  ;)

It does seem really well executed though so I'm most certainly going to see it if it gets traction.
