### ISSUE TITLE
UsernamePasswordFormAuthenticationListener cant handle missing field "_username"

### ISSUE THREAD

**Issue by bokonet** [symfony/symfony#27961]
**Symfony version(s) affected**: 3.4.12

**Description**  
We are using a form_login in security.yml. If we submit an empty POST request to the check_path route, an BadRequestHttpException is thrown:
The key "_username" must be a string, "NULL" given.
This happend several times in our production system.

**How to reproduce**  
Send an empty POST Request to the login-page configured in: security.firewalls.xxx.form_login.check_path

**Possible Solution**  
Allow the username to be NULL, so it can be treated as an empty string.
Symfony\Component\Security\Http\Firewall\UsernamePasswordFormAuthenticationListener.php
method: attemptAuthentication()
line 88: `if ((!\is_string($username) && !\is_null($username)) || (\is_object($username) && !\method_exists($username, '__toString'))) {`

**Comment by iltar** [comment]
Isn't that how it should work? I'm not too familiar with requests, but if there's no username field given, it should tell you that it's incorrect.

**Comment by chalasr** [comment]
I think the same way as @iltar, a missing required request parameter deserves a client error. 
But looking a the PR where the request validation was introduced https://github.com/symfony/symfony/pull/25657#issuecomment-356933359, I may miss a good reason to allow omitting these. @xabbuh Is this what you had in mind? looks legit to you?
If confirmed, the same issue applies to the `json-login` listener.

**Comment by xabbuh** [comment]
This behaviour looks correct to me. I mean what is the use case for not passing the username or password?

**Comment by iltar** [comment]
@xabbuh those use-cases are covered by guard (not the guard form-login), which lets you customize it more

**Comment by bokonet** [comment]
I dont know why, but sometimes users/browsers send requests without the _username parameter to the check-login pages. It happend on our systems on different symfony-projects and different domains/servers. I think in this case it would be better so return a credential-error, than an BadRequestHttpException.

**Comment by chalasr** [comment]
The `form_login` listener expects form-data, if an user reaches this endpoint without the username and/or password parameters, telling him "Bad credentials" would be wrong. 
This case should not happen, it should be handled client side.

**Comment by bokonet** [comment]
@iltar Yes, i think the Browser cache is the problem.
@chalasr Right, this case should not happen, but it did. We observe this error every week.

An additional aspect is, we configured monolog to send us an email in prod systems if an error occured:

[2018-07-10 23:05:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "The key "_username" must be a string, "NULL" given." at .../htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php line 89 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): The key \"_username\" must be a string, \"NULL\" given. at .../htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:89)"} []

Different idea: If the username parameter is missing, the UsernamePasswordFormAuthenticationListener should not be called at all. Is this possible?

**Comment by xabbuh** [comment]
From a user's POV it's probably not a big problem if we don't throw that exception. They would (hopefully) see the form again and enter their credentials again. But from a developer's POV things might be different. If you made a mistake in your login form, you won't no longer receive notifications about exceptions (if you configured them) as errors would silently be swallowed. I am unsure what would be the better solution here.

**Comment by ostrolucky** [comment]
Current behaviour seems correct. Such exceptions should be configured to be ignored by your logging system, as they are probably triggered by bots.

**Comment by darknmy** [comment]
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
throw new UsernameNotFoundException(sprintf('Username "%s" does not exist.', $name));

After posting HTML Form: username, password

I receive the same error:
"The key "_username" must be a string, "NULL" given."

Please advise.

**Comment by bokonet** [comment]
@xabbuh Ok, now i understand why our solution is a problem in general. The Develooper needs the Information about misconfigured login-form-settings. 
But in my opinion an invalid client-request should never trigger an uncaught exception.
What if the UsernamePasswordFormAuthenticationListener send an error message like "No Username submitted"? In this case the Developer got the hint of misconfigured login-form-setting as well.

@ostrolucky We are using swift_mailer in monolog-handlers to send Errors in prod environment with the "excluded_404s" parameter. see https://symfony.com/doc/3.4/logging/monolog_email.html
If we change the action_level from 'warning' to 'critical' we will get 500 server errors only.

**Comment by chalasr** [comment]
@darknmy you have to fix your form, it should send `_username` not `username`, as the error hints.

@bokonet As explained above, the client error is desired, not a bug. 
About the exception message when the username parameter is not set, please feel free to submit a PR against master if you think it can be improved.

**Comment by jeremie-crt** [comment]
I got the same issue. In security.yml if you modify the 'login-path' and 'check_path' make sure that the route in the 'UserController' (the one that deals the login process) with the login route has the same naming. ex:login_path: admin_login check_path: admin_login and same route for login the controller

and then, the one that must be checked is the constant variable in the Authenticator LOGIN_ROUTE = 'admin_login'. that fixed it for me. It had the default route so i had the error because of that.

btw: no need to change the name's input in the login form for 'username'. By 'email' it works fine.

**Comment by codedmonkey** [comment]
I don't understand why this got closed. We're not talking about a "client error" we are talking about an exception that's uncatchable because it's from a Symfony event listener.

I agree that its likely bots that are causing this problem, a modern browser prevents submitting an empty username in a properly configured login form, but it should not cause an exception. I have an idea in mind to fix it, but since this is considered a "client error" I don't feel incentiviced to make a PR. Basically, add a `$default` argument to `ParameterBagUtils::getParameterBagValue()` should fix this particular problem but I don't know if this would cause any other problems.

**Comment by fmv-velden** [comment]
We are running into the same issue, the current BadRequestHttpException makes sense in a development environment but not in a production environment. Any unauthenticated user on the internet can call the login url without POST parameters and spam the error logs with this exception, potentially flooding the server if error emails are triggered.

In my opinion it would make more sense if UsernamePasswordFormAuthenticationListener::requiresAuthentication() actually checks if the needed username and password are actually in the POST. It doesn't make a lot of sense to check a login attempt without any credentials. Maybe a warning in the Symfony toolbar could trigger a developer to add the missing fields if they are not present in the login form.

edit:
A workaround seems to be to ignore 400 errors in the logs but I'm not sure if it is the right solution:
```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [400, 404, 405]
```

**Comment by mklewitz** [comment]
Imho though the behaviour to throw an exception is correct, the wrong one is thrown (or rather not catched). It's impossible to configure a handler for the exception thrown.

The error annoyed me, cause I get a slack message on every error that isn't catched. And this was the only one, we weren't able to get rid of and/or handle. Excluding all errors for certain http codes isn't an option for us, cause we may miss important other errors in the future.

That said, I created a compiler pass, that replaces Symfony's FormLoginAuthenticator with a child class that simply replaces BadRequestHttpException with BadCredentialsException (which is catched and can be handled).

```
class ExceptionExchangingFormLoginAuthenticator extends FormLoginAuthenticator
{
    public function authenticate(Request $request): Passport
    {
        try {
            return parent::authenticate($request);
        } catch (BadRequestHttpException $badRequestHttpException) {
            throw new BadCredentialsException('Bad credentials.', 0, $badRequestHttpException);
        }
    }
}
```

```
class ExceptionExchangingFormLoginAuthenticatorPass implements CompilerPassInterface
{
    private const DEFINITION = 'security.authenticator.form_login.FIREWALL_NAME';

    public function process(ContainerBuilder $container)
    {
        if (false === $container->hasDefinition(self::DEFINITION)) {
            return;
        }

        /** @var ChildDefinition $formLoginFirewall */
        $formLoginFirewall = $container->getDefinition(self::DEFINITION);
        $formLogin = $container->getDefinition($formLoginFirewall->getParent());

        $arguments = array_merge(
            [$formLogin->getArgument(0)],
            array_values($formLoginFirewall->getArguments()),
            [new Reference(RequestStack::class)]
        );

        $container->register(ExceptionExchangingFormLoginAuthenticator::class, ExceptionExchangingFormLoginAuthenticator::class)
            ->setArguments($arguments);

        $container->setAlias(self::DEFINITION, ExceptionExchangingFormLoginAuthenticator::class);
    }
}
```

Just replace FIREWALL_NAME in ExceptionExchangingFormLoginAuthenticatorPass::DEFINITION with the name of your firewall (the one you defined in security.yaml)

**Comment by balbinus** [comment]
Thank you so much @mklewitz for this solution! Same as previous commenters, I had bots repeatedly hitting the login page with empty POST data triggering mails from Monolog. I had tried to override the FormLoginAuthenticator class for some time but hadn't thought of the compiler pass way. If anyone tries this method, the way to enable the compiler pass is in your Kernel, as described here: https://symfony.com/doc/current/service_container/compiler_passes.html.

**Comment by fmv-velden** [comment]
I think this bug should be reopened and the exception should be replaced with the `BadCredentialsException`. The problems in a production environment can be far bigger than the gains while developing a login form. 
The workaround from @mklewitz works, but it makes the code more complicated for no reason.

Who would be the appropriate person to tag for this?

**Comment by NMe84** [comment]
This behaviour is _really_ annoying. Even if it's somehow "correct," it's being logged as an error and causes Monolog to mail the developer a digest if they've configured the system to do so. There is no way to block this natively without the compiler pass above. Which would be fine if this was indicative of a mistake I made as a developer, but I really don't need to know about every single time some bot tries to use the login form to spam for blue pills.

_Please_ reconsider reopening this, @chalasr. Throwing a client error is fine. Logging it as an uncatchable exception that makes it hard on a decently busy website to distinguish actual error emails from this nonsense is not.

**Comment by martijn80** [comment]
This still occurs. 

It's really weird the spam bots don't even post any csrf token and that does'nt lead to earlier exceptions.

**Comment by gremo** [comment]
Why was this closed? This is still an issue with modern Symfony 7.4 (and probably Symfony 8 as well). It can generate a large number of emails for users who have error notifications enabled.
