### ISSUE TITLE
php templating engine is refering to wrong folder

### ISSUE THREAD

**Issue by dirkjf** [symfony/symfony#27964]
**Symfony version(s) affected**: 4.x.x

**Description**  
If you use the php templating engine in Symfony 4 this still looks for files in the folder 
`src\Resources\views\` and not `templates\ `

**How to reproduce**  
If you set your templating engine to php in framework.yaml and try to render a .php file in a controller, this only works if that file is in `src\Resources\views\`.

**Comment by yceruto** [comment]
The `templates/` directory is meant to work only with Twig and the `Templating` Component only keep BC with old structure as of Symfony 4. Also:
> templating should be avoided as of Symfony 4 https://github.com/symfony/symfony/issues/26579#issuecomment-374010098

**Comment by javiereguiluz** [comment]
This is similar to #26192, so we must close it for the same reasons given in https://github.com/symfony/symfony/issues/26192#issuecomment-509111413. Sorry!
