### ISSUE TITLE
Add support for valueless parameters in ParameterBag::getBoolean()

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#27973]
**Description**  
Valueless parameters result in unintuitive results when retrieved with `getBoolean()`, you get `false` even if the parameter is present

**Example**  

`GET /myRoute?redirect`

Before:

`$request->query->getBoolean('redirect', true); // false`

After:
`$request->query->getBoolean('redirect', true); // true`

Note: formulating this as a feature because of BC
Other note: `GET /myRoute?redirect=` should still result in `false`

I can contribute it if people think this should be done.

**Comment by ro0NL** [comment]
> Other note: GET /myRoute?redirect= should still result in false

How will you check this?

**Comment by greg0ire** [comment]
That might make things a lot harder indeed, I'll have to check if `$_GET` changes somehow

**Comment by ro0NL** [comment]
Ah of course :) that's possible yes.

I don't like the idea of treating the query different then PHP does.

**Comment by greg0ire** [comment]
Neither do I… maybe this feature request should be for PHP first :/ The alternative is to treat `redirect=` as `true`, but that's really not great either, so closing for now, I will reopen if someone thinks of a better solution.
