### ISSUE TITLE
[Form] MoneyType does not accept inputs with thousands separator

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#27979]
**Symfony version(s) affected**: 3.4.12

**Description**  
When using the MoneyType form field and entering a value with thousands separator, an error  is thrown. So, with German locale entering "1.234,56" (float value is 1234.56) the validation gives an error.
Similarly, the input "1234.56", which is strictly speaking an invalid number in Germany, is accepted.

An overview:
Input string | result (float)
------------|-------------
1234.56 | 1234.56
1234,56 | 1234.56
1.234,56 | error

**Comment by xabbuh** [comment]
@flaushi Are you able to provide a reproducible example?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by flaushi** [comment]
Hey sorry for my delayed reply. I checked it again, and it seems the `grouping` option was the problem. So, as you said, only inputs that are locale-compatible are accepted (with ext-intl and grouping). If grouping is false, the behaviour is neither correct for a default english locale nor another locale. **Maybe one should set grouping to true then by default?**
