### ISSUE TITLE
[Validator] missing translation for Uuid constraint

### ISSUE THREAD

**Issue by garak** [symfony/symfony#27984]
**Symfony version(s) affected**: 4.1.1 (and likely all previous versions)

**Description**  
Message of [Uuid constraint](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/Uuid.php#L52) is missing translations in all languages

**How to reproduce**  
Just try to validate an Uuid with locale enabled.
Expected result: a translated error message. 
Actual result: "This is not a valid UUID."

**Possible Solution**  
We need to add such messages to all validators.XX.xlf in validator translations (I can provide a PR for Italian language only)

**Additional context**  
None

**Comment by fabpot** [comment]
Please, open a PR for Italian. Other languages will follow.
