### ISSUE TITLE
Value from X-Forwarded-Host header retrieved when using url twig helper in combination with AppCache (no trusted proxy set)

### ISSUE THREAD

**Issue by chaosversum** [symfony/symfony#27980]
**Symfony version(s) affected**: 2.8.41/42

**Description**  
The value from X-Forwarded-Host header is used when i'm using the url twig helper function in combination with AppCache.

Removing the AppCache line from app.php fixes the problem.
I have no trusted proxies set.

My current workaround is to call unset($_SERVER['HTTP_X_FORWARDED_HOST']); in app.php.

Any idea how this can be related? Maybe it is releated to my application, but i could not find anything special, so it could be a possible security issue.

Of course, i deleted the the http_cache dir several times while testing and used different random parameters for bursting the cache as well...

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/symfony/symfony/commit/725dee4cd8b4ccd52e335ae4b4522242cea9bd4a
Next time, in any doubt, please report security issues according to https://symfony.com/security
