### ISSUE TITLE
[RFC] Normalize root namespaces with DI

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28006]
**Description**  
For context see: https://github.com/symfony/symfony-docs/issues/8403 and https://github.com/symfony/symfony/pull/24145

> Nobody should prefix their service name by a \\ IMHO.
> -- nicolas-grekas

Currently only namespaced classes are detected as "class named services", i.e.

```yaml
MyClass: ~ # doesnt work
\MyClass: ~ # doesnt work
\My\Class: ~ # doesnt work
My\Class: ~ # works
```
I propose to deprecate leading slashes in service ids. So you most likely end up with the working/last example in the future.

In case a class lives in the root namespace (first example) you'd get the error about a missing class attribute which we can easily explain: "root class named services" are not supported. Hence you must specify the class attribute. Which brings me to the next point;

Currently it's allowed to use both `class: MyClass` and `class: \MyClass` which causes some form of inconsistency, and makes `$def->getClass()  === MyClass::class` error prone.

I propose to normalize leading slashes in a service its class attribute. Although i tend to prefer a deprecation here as well.

Thoughts?

**Comment by stof** [comment]
root class named services are supported. What is not supported for them is the shortcut allowing to guess the class name from the id.

**Comment by ro0NL** [comment]
Correct. My reasoning is, if `My\Class: ~` is described as a _class named service_ then `\MyClass: ~` is a _root class named service_ :)

**Comment by nicolas-grekas** [comment]
:-1: on my side: there should be only one valid id. Normalization creates alternative ways and leads to issues. We deprecated lowercasing for this reason.

**Comment by ro0NL** [comment]
> I propose to deprecate leading slashes in service ids

So yes, a leading `\` would throw eventually. No normalization.

For the `class:` attribute normalization could work, but on 2nd thought i prefer a deprecation here as well. Exactly for the reasons you mentioned.

**Comment by nicolas-grekas** [comment]
But if there are no technical reasons, deprecating for the sake of it is not worth it IMHO.

**Comment by ro0NL** [comment]
Fair, that's why I opened the RFC.

You're right, it's purely a DX issue. No technical reason.

In a way this error is just a weird side effect:

```
The definition for "\My\DateTime" has no class attribute,
and appears to reference a class or interface in the global namespace.
Leaving out the "class" attribute is only allowed for namespaced classes.
```

Nevertheless, we can settle by qualifying it a doc issue. Then i'll go back to https://github.com/symfony/symfony-docs/issues/8403 :)

**Comment by nicolas-grekas** [comment]
Sure, it's always worth asking, and that's just my 2cts :)

**Comment by javiereguiluz** [comment]
@ro0NL thanks for starting this discussion. I disagree about "polluting" the Symfony Docs with these minor details. This can be solved with a great error message generated by Symfony when this happens.

The current error message is good, but I'd like to propose a minor reword to make it more clear what the developer must do to solve it:

```
The "\My\DateTime" service definition must include the "class" attribute because
it references a class or interface in the global PHP namespace. Leaving out the
"class" attribute is only allowed for namespaced classes.
```

**Comment by ro0NL** [comment]
Yeah, improving the error message was something i thought of as well. But i think it should be more explicit.

Something like

```
... "\My\DateTime" appears to reference a namespaced class, but is invalid due its leading slash (/). You should rename the service ID to "My\DateTime" to get rid of this error.
```

For the docs, using `\Class: ~` is plain wrong :)
