### ISSUE TITLE
UndefinedMethodException: Attempted to call an undefined method named "buildTree" of class "ArrayNode".

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#28004]
**Symfony version(s) affected**: v4.1.1

**Description**  
Got this error after updating `symfony/symfony` (`v4.0.10` => `v4.1.1`).

```
(1/1) UndefinedMethodException

Attempted to call an undefined method named "buildTree" of class "Symfony\Component\Config\Definition\ArrayNode".
in Processor.php line 52
at Processor->processConfiguration(object(Configuration), ... in ValidateEnvPlaceholdersPass.php line 80
at ValidateEnvPlaceholdersPass->process(object(ContainerBuilder))in Compiler.php line 95
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 736
at ContainerBuilder->compile()in Kernel.php line 519
at Kernel->initializeContainer()in AppKernel.php line 100
at AppKernel->initializeContainer()in Kernel.php line 123
at Kernel->boot()in Kernel.php line 183
```

**Comment by umpirsky** [comment]
Oh, true, I call `->buildTree()` in `Configuration`. Thanks!

**Comment by Mohdfaheem712** [comment]
Got this error while updating php to 7.4 from 7.2 and symfony from 4.3 to 5.3

!!  Symfony\Component\ErrorHandler\Error\UndefinedMethodError {#6136
!!    #message: "Attempted to call an undefined method named "buildTree" of class "Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition"."
!!    #code: 0
!!    #file: "./vendor/symfony/config/Definition/Processor.php"
!!    #line: 50
!!    trace: {
!!      ./vendor/symfony/config/Definition/Processor.php:50 { …}
!!      ./vendor/symfony/dependency-injection/Extension/Extension.php:111 { …}
!!      ./packages/uvdesk/core-framework/DependencyInjection/CoreFramework.php:48 {
!!        Webkul\UVDesk\CoreFrameworkBundle\DependencyInjection\CoreFramework->load(array $configs, ContainerBuilder $container)
!!        › $configuration = $this->getConfiguration($configs, $container);
!!        › foreach ($this->processConfiguration($configuration, $configs) as $param => $value) {
!!        ›     switch ($param) {
!!      }
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:749 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:545 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:786 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:125 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:167 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:56 { …}
!!      ./vendor/autoload_runtime.php:35 { …}
!!      ./bin/console:11 { …}
!!    }
!!  }
!!  2021-06-14T13:43:27+05:30 [critical] Uncaught Error: Call to undefined method Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::buildTree()
!!
