### ISSUE TITLE
path returning string path

### ISSUE THREAD

**Issue by nicolasvahidzein** [symfony/symfony#28011]
Hello, when i run this:

		$process2 = new Process('echo $PATH');
		$process2->run();
		\Log::info($process2->getOutput());

I get $PATH returned as a string.

And when i try to run a python command i get a command not recognized but all seems to be well on my system. Can you please help me?

**Comment by chalasr** [comment]
We use github issues to track bugs and feature requests, please checkout one of our [support platforms](https://symfony.com/support) instead. Thanks for your understanding.
