### ISSUE TITLE
Form validation with Subforms and Groups

### ISSUE THREAD

**Issue by tniemann** [symfony/symfony#28020]
Hi,

i have an address entity where invoice and shipping entity extends from. 
Each form has his own form type and inherit from address form type.

My goal is to validate the invoice form when the checkbox is checked.
So i add a group to all necessary fields in my Address Entity.

``` 
/**
     * @var string
     * @Assert\NotBlank(message="address.empty.salutation", groups={"Address"})
     * @Assert\Choice({"female", "male"}, message="address.invalid.salutation")
     */
    private $salutation;
```

In my InvoiceForm i add the following:

```
    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults(
            [
                'data_class' => InvoiceAddress::class,
                'translation_domain' => 'forms',
                'validation_groups' => function (FormInterface $form) {
                    /**
                     * @var Address $address
                     */
                    $address = $form->getData();
                    if (1 === 2) {
                        return ['Default', 'Address'];
                    }

                    return ['Default'];
                },
            ]
        );
    }
```

My understanding was, that now my invoice form just validate agains the Default not the Address group what it does but unfortunately my ShippingForm does the same and ignore the validation of the salutation field.

My InvoiceForm:

```class InvoiceAddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options):void
    {
        $builder
            ->add(
                'address',
                AddressFormType::class,
                [
                    'label' => false,
                    'data_class' => Address::class,
                ]
            )
            ->add(
                'country',
                ChoiceType::class,
                [
                    'choices'  => [
                        'country.de' => 'de',
                        'country.at' => 'at',
                        'country.nl' => 'nl',
                        'country.fr' => 'fr',
                        'country.lu' => 'lu',
                        'country.be' => 'be',
                    ],
                    'placeholder' => 'invoice_country',
                    'label' => false,
                    'attr' => ['class' => 'custom-select']
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults(
            [
                'data_class' => InvoiceAddress::class,
                'translation_domain' => 'forms',
                'validation_groups' => function (FormInterface $form) {
                    /**
                     * @var Address $address
                     */
                    $address = $form->getData();
                    if (1 === 2) {
                        return ['Default', 'address'];
                    }

                    return ['Default'];
                },
            ]
        );
    }
}
```
My ShippingForm:

```class ShippingAddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options):void
    {
        $builder
            ->add(
                'email',
                EmailType::class,
                [
                    'attr' => [
                        'placeholder' => 'email',
                    ],
                    'label' => 'email',
                ]
            )
            ->add(
                'address',
                AddressFormType::class,
                [
                    'label' => false,
                    'data_class' => Address::class,
                ]
            )
            ->add(
                'country',
                ChoiceType::class,
                [
                    'choices'  => [
                        'country.de' => 'de',
                        'country.at' => 'at',
                        'country.nl' => 'nl',
                        'country.fr' => 'fr',
                        'country.lu' => 'lu',
                        'country.be' => 'be',
                    ],
                    'placeholder' => 'shipping_country',
                    'label' => false,
                    'attr' => ['class' => 'custom-select']
                ]
            )
            ->add(
                'birthDate',
                TextType::class,
                [

                    'attr' => [
                        'placeholder' => 'birthday',
                    ],
                    'label' => 'birthday',
                    'required' => false,
                ]
            )
            ->add(
                'phone',
                TelType::class,
                [

                    'attr' => [
                        'placeholder' => 'phone',
                        'minlength' => 12,
                        'maxlength' => 30,
                    ],
                    'label' => 'phone',
                    'required' => false,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults(
            [
                'data_class' => ShippingAddress::class,
                'translation_domain' => 'forms'
            ]
        );
    }
}```

My address form:

```
class AddressFormType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options):void
    {
        $builder

            ->add(
                'salutation',
                ChoiceType::class,
                [
                    'choices'  => [
                        'salutation.mister' => 'male',
                        'salutation.misses' => 'female',
                    ],
                    'placeholder' => 'choose_salutation',
                    'label' => false,
                    'attr' => ['class' => 'custom-select']
                ]
            )
            ->add(
                'firstName',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'firstname',
                        'minlength' => 2,
                        'maxlength' => 50,
                    ],
                    'label' => 'firstname',
                ]
            )
            ->add(
                'lastName',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'lastname',
                        'minlength' => 2,
                        'maxlength' => 50,
                    ],
                    'label' => 'lastname',
                ]
            )
            ->add(
                'company',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'company',
                        'minlength' => 2,
                        'maxlength' => 50,
                    ],
                    'label' => 'company',
                    'required' => false,
                ]
            )
            ->add(
                'addressAdditional',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'addressAdditional',
                        'maxlength' => 200,
                    ],
                    'label' => 'addressAdditional',
                    'required' => false,
                ]
            )
            ->add(
                'street',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'street',
                        'minlength' => 2,
                        'maxlength' => 100,
                    ],
                    'label' => 'street',
                ]
            )
            ->add(
                'streetNumber',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'street_number',
                        'minlength' => 1,
                        'maxlength' => 6,
                    ],
                    'label' => 'street_number',
                    'required' => false,
                ]
            )

            ->add(
                'city',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'city',
                        'minlength' => 2,
                        'maxlength' => 200,
                    ],
                    'label' => 'city',
                ]
            )
            ->add(
                'zipCode',
                TextType::class,
                [
                    'attr' => [
                        'placeholder' => 'zipcode',
                        'minlength' => 4,
                        'maxlength' => 6,
                    ],
                    'label' => 'zipcode',
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults([
            'inherit_data' => true
        ]);
    }
}```

In CheckoutForm i build the form:

```class CheckoutFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'shipmentAddress',
                ShippingAddressType::class,
                [
                    'label' => 'shipment_address'
                ]
            )
            ->add(
                'alternativeShipmentAddress',
                CheckboxType::class,
                [
                    'label' => 'alternative_shipment_address',
                    'label_attr' => ['class' => 'checkbox-custom'],
                    'required' => false,
                ]
            )
            ->add(
                'invoiceAddress',
                InvoiceAddressType::class,
                [
                    'label' => 'invoice_address'
                ]
            )
            ->add(
                'privacy',
                CustomerFormType::class,
                [
                    'label' => false
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'translation_domain' => 'forms'
            ]
        );
    }
}
```

Does anybody has an idea what i did wrong?

Regards
Thomas

**Comment by tniemann** [comment]
Hi,

i have an address entity where invoice and shipping entity extends from. 
Each form has his own form type and inherit from address form type.

My goal is to validate the invoice form when the checkbox is checked.
So i add a group to all necessary fields in my Address Entity.

` 
/**
     * @var string
     * @Assert\NotBlank(message="address.empty.salutation", groups={"Address"})
     * @Assert\Choice({"female", "male"}, message="address.invalid.salutation")
     */
    private $salutation;
`

In my InvoiceForm i add the following:

`
    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults(
            [
                'data_class' => InvoiceAddress::class,
                'translation_domain' => 'forms',
                'validation_groups' => function (FormInterface $form) {
                    /**
                     * @var Address $address
                     */
                    $address = $form->getData();
                    if (1 === 2) {
                        return ['Default', 'address'];
                    }

                    return ['Default'];
                },
            ]
        );
    }
`

**Comment by naitsirch** [comment]
Would have been nice, if you have explained why you closed the issue ;-)
I have a similar problem and searching for the reason

**Comment by tniemann** [comment]
HI...

because I solved it :-)

I add a Listener to the CustomerForm:

`$builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {

            $form = $event->getForm();

            if ($form->get('alternativeInvoiceAddress')->getData() === false) {
                /**
                 * @var Customer$customer
                 */
                $customer = $event->getData();
                $customer->setInvoiceAddress(null);
            }
        });`

And on each Child Form I add this ConfigurationOptions:

`public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => InvoiceAddress::class,
                'translation_domain' => 'forms',
                'error_bubbling' => false,
                'error_mapping' => [
                    'zipCodeValid' => 'address.zipCode',
                ],
            ]
        );
    }`

Hope that helps you.

**Comment by naitsirch** [comment]
I see. I have chosen another way to solve it. I have created a custom class constraint that could access the other properties to get the needed information, so that it does not depend on any validation groups.
