### ISSUE TITLE
Exceptions thrown in form types are not caught in phpunit

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28021]
**Symfony version(s) affected**: 4.1.1

**Description**  

I have an error in a form type that is causing an undefined offset (in this case it is actually a problem with missing test data), however, instead of showing as an 'E' in simple-phpunit's output, the exception is uncaught and is displayed during the results:

```
.2018-07-20T21:54:33+00:00 [critical] Uncaught PHP Exception PHPUnit\Framework\Error\Notice: "Undefined offset: 0" at /var/www/html2/src/Form/ShippingMethodType.php line 87
F2018-07-20T21:54:33+00:00 [critical] Uncaught PHP Exception PHPUnit\Framework\Error\Notice: "Undefined offset: 0" at /var/www/html2/src/Form/ShippingMethodType.php line 87
F..........................EE..EE.....
```

**How to reproduce**  
create a functional test that requests a page which displays a form, where the form has an error, e.g. an undefined index error as above

**Comment by xabbuh** [comment]
This seems to be related to #25570 and #25676 (especially https://github.com/symfony/symfony/issues/25676#issuecomment-369619194).

**Comment by javiereguiluz** [comment]
@xabbuh I don't understand how the mentioned issues are related. Do you mean that this is expected and the user must define the shell verbosity config to fix it? Thanks.

**Comment by xabbuh** [comment]
I guess I misread the description back then. The related issues are about the error output.

@ChangePlaces But the tests are failing aren't they?

**Comment by ChangePlaces** [comment]
The tests fail because an exception is thrown.

Anyway, can't be of anymore help as I've discovered go

**Comment by xabbuh** [comment]
Okay, let's close here then. If someone experiences the same and can provide a small example that allows to reproduce, we could reopen here.
