### ISSUE TITLE
[DI] Do not load auto-discovered classes

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#28040]
### Description

Right now when using the following service declaration:

```yaml
services:
    Acme\:
        resource: '%kernel.project_dir%/path/to/my/dir'
```

A list of services will be auto-discovered. There is however one more thing done during the process: **the discovered services are loaded, triggered by [class reflection](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L148-L157)**.

This may appear as a good idea since it ensures the discovered services are valid PHP files, but I would like to request **to turn that off**. Indeed I do not see why auto-discovered services should have a special treatment (this check is not done for other services).

### Use case

Another reason (which is arguably an edge case) is that the service class may not be valid at that time yet. For example some of the services of one of our application depends on files that will be generated (e.g. extends a generated class). A very simplified example would be, given the entity `User` and its repository (interface) `UserRepository`, we generate the following base interface:

```php
interface GeneratedUserRepository {
  function getUser(UserId $id): User;
}
```

And then our `UserRepository` interface can be:

```php
interface UserRepository extends GeneratedUserRepository {}
```

The idea being that since PHP does not have generics, providing a strictly typed API for a lot of services is very boring, tedious, annoying to maintain and most of the time not worth it to do by hand. With our generation strategy, we make it viable. The downside is that we need to generate those additional classes first.

To keep the process very simple and well integrated with the application, we leverage the framework and its compiler passes.

So far it works really well, but when switching to those auto-discovered services to reduce the service definition declarations (the mechanism described above was working since Symfony 2.7), it turns out this no longer works. The reason being if the service `UserRepository` is registered, doing a class reflection on it will fail if its generated class does not exists yet. Although we could deal with this error and remove it via hacky Compiler classes, it would still be dangerous to do since the loaded class would be the incomplete definition and out of sync with the file code.

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
I'm not sure this is possible: Reflection is not just used for validation, it's a core part of the discovery mechanism.
But autodiscovery is just a band-aid: if it doesn't fit your need, you can skip it and register explicitly, so that should not be a blocker to you edge case I'd think.

**Comment by theofidry** [comment]
Damn, I guess there would be some ways to make it work but it wouldn't be without heavy changes/tooling.

I guess we'll just have to accept it and register those explicitly or via another pass then. Thanks for the quick answer :)

**Comment by stof** [comment]
Thus, auto-discovered services are almost always autowired and autoconfigured (as otherwise, it means they have no dependency, and are not tagged for anything else, which is quite rare). And both autowiring and autoconfiguration relies on loading the class:

- autowiring needs to inspect the constructor arguments with Reflection
- autoconfiguration needs to know the types it matches (implemented interfaces and parent classes)

**Comment by stof** [comment]
oh, and auto-discovery also has this rule about discovering interfaces to register them for autowiring, which has the same needs of knowing implemented interfaces.
