### ISSUE TITLE
[Messenger] Add an option to configure message flags

### ISSUE THREAD

**Issue by itsfnk** [symfony/symfony#28053]
**Description**  
Currently there is no option to configure message flags when publishing via Amqp Transport. Flag `AMQP_NOPARAM` is hardcoded into the publishing function: https://github.com/symfony/messenger/blob/v4.1.2/Transport/AmqpExt/Connection.php#L101.
I think it should be configurable by the developer as there is no way to publish e.g. persistent messages. Once this Feature Request is accepted I am happy to provide PR myself.

**Example**  
I imagine that it would look like this in the code:

```php
$message = new MyMessage("Hello world");
$bus->dispatch((new Envelope($message))->withFlags(AMQP_DURABLE));
```

**Comment by PGBastien** [comment]
Indeed use a transport-specific (with flags ex: exchange type, durability, routing_key, ...) is relevant because we can route messages to the transports in `messenger.yaml` by serialized object.

**Comment by raresserban** [comment]
Hello, regarding this, I think the AMQP transport should also allow configuration of the `routing_key` and `attributes` parameters of the amqp `publish` method.

**Comment by PeterFour** [comment]
I'll try to raise a PR if nobody is doing it already. That could be a good first contribution

**Comment by sroze** [comment]
It does now. Such a PR (for the routing key) as been merged a few days ago
:)

**Comment by PeterFour** [comment]
Sorry if I'm wrong but I can still see it hardcoded to `AMQP_NOPARAM` ?https://github.com/symfony/messenger/blob/master/Transport/AmqpExt/Connection.php#L107

**Comment by sroze** [comment]
Closing as https://github.com/symfony/symfony/pull/30008 has just been merged.
