### ISSUE TITLE
SecurityBundle configuration via environment variables

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#28051]
**Symfony version(s) affected**: 4.1

**Description**  

Security bundle configuration does not resolve environment variables (at least `cookie_secure`)

**How to reproduce**  

```
framework:
    session:
        cookie_secure: '%env(bool:APP_SECURE)%'
```

This config looks good, whereas `Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\AddSessionDomainConstraintPass` does not take it into account and uses `$sessionOptions['cookie_secure']` as-is, which holds the `env_b5fff47290c287c9_bool_APP_SECURE_93dabfcdbc8f9f7829f1a29cd3d2d083` value.

**Possible Solution**  

Instead of YAML use the following ugly php-based configuration (or its variations)
```php
<?php

$envSecure = getenv('APP_SECURE');
if ($envSecure === false) {
    $envSecure = true;
} else {
    $envSecure = filter_var($envSecure, FILTER_VALIDATE_BOOLEAN, ['flags' => FILTER_NULL_ON_FAILURE]);

    if ($envSecure === null) {
        $envSecure = true;
    }
}

$container->loadFromExtension('framework', [
    'session' => [
        'cookie_secure' => $envSecure,
    ],
]);
```

**Additional context**

**Comment by nicolas-grekas** [comment]
The unresolved value is normal at this stage: these placeholders are resolved later on, when the container is dumped. The solution you suggest doesn't work as one would expect: is generates a compiled container that will hold the static value that was set a compile time, while the very nature of env vars is to be configurable at run time with a call to getenv() or similar.
What's the real world issue you're facing?

**Comment by zerkms** [comment]
> What's the real world issue you're facing?

inability to set `framework.session.cookie_secure` via environment variables.

**Comment by ro0NL** [comment]
Maybe we can move the logic to runtime for this case?

https://github.com/symfony/symfony/blob/f834c9262b411aa5793fcea23694e3ad3b5acbb4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSessionDomainConstraintPass.php#L33-L37

**Comment by nicolas-grekas** [comment]
We would definitely need a runtime check to allow using an env var here.
PR welcome @zerkms

**Comment by gonzalovilaseca** [comment]
@zerkms Are you working on this? I can pick it up if you're busy

**Comment by zerkms** [comment]
@gonzalovilaseca I'm moving a house and expecting a newborn in couple weeks - I definitely won't be able to do any opensource soon :-D

**Comment by gonzalovilaseca** [comment]
I've done this: https://github.com/symfony/symfony/compare/master...gonzalovilaseca:gv-28051?expand=1

But I'm getting `The parameter "env_0ad3efce154cc146_bool_APP_SECURE_94c20e3f9fd8679095faf3a5596de9e3" must be defined.` @nicolas-grekas any ideas?
(I've debugged and at some point `APP_SECURE` is resolved but not with that long string name.)

**Comment by nicolas-grekas** [comment]
Now that cookies can be auto-secure, is this really worth it? That'd add complexity we'd have to justify...
See #28446, #28447 and related.

**Comment by gonzalovilaseca** [comment]
The compiled container has `return $this->privates['security.http_utils'] = new \Symfony\Component\Security\Http\HttpUtils($a, $a, $this->getParameter('env_0ad3efce154cc146_bool_APP_SECURE_94c20e3f9fd8679095faf3a5596de9e3'), $this->getParameter('%s'));
`
Should it be `APP_SECURE` instead of `env_0ad3efce154cc146_bool_APP_SECURE_94c20e3f9fd8679095faf3a5596de9e3`?

**Comment by gonzalovilaseca** [comment]
Oh, I just picked it up because it had the `help wanted` label, I'm not planning on using it..let me know if it's not needed and will move to another issue.

**Comment by zerkms** [comment]
> Now that cookies can be auto-secure, is this really worth it?

I've personally seen applications that should have had authentication done via https and the rest of the application accessed through http.

**Comment by gonzalovilaseca** [comment]
I had the code almost done, so I've created the PR, if it doesn't go ahead it can always be closed: https://github.com/symfony/symfony/pull/28651
