### ISSUE TITLE
[BC Break] Change of logout path access control behavior

### ISSUE THREAD

**Issue by xelan** [symfony/symfony#28058]
**Symfony version(s) affected**: Reproduced with 2.7.47 (LTS) and 3.4.10 (LTS). Probably other versions where PR #24805 was merged are affected as well.

**Description**  
Apparently, access control behavior for the logout path was changed in bugfix releases of Symfony, I suppose this is caused by #24805.

In Symfony 2.7.46, the logout path was not considered by the `access_control` rules defined in `security.yml`. Starting from 2.7.47 it is, so an "Access Denied" exception is thrown if the logout path is not allowed.

Also see hslavich/OneloginSamlBundle#53

**How to reproduce**  

This example reproduces this issue with a minimal Symfony 2.7 application created with the Symfony installer.

```
git clone https://github.com/xelan/symfony-logout-break.git
cd symfony-logout-break
composer install
php app/console server:start 0.0.0.0:8000
```

* Go to http://localhost:8000/app_dev.php => you see the default index page
* Go to http://localhost:8000/app_dev.php/test => you are prompted for login
* Login with username `user`, password `pass` => you see an example page with a logout link
* Click the logout link => you get an "Access Denied" error message

If you change composer.json to `"symfony/symfony": "2.7.46"`, run `composer update` and test again, the last step (logout) is successful.

**Possible Solution**  
IMHO, two approaches would be possible:
* Revert the access control behavior for the logout path (Retaining BC)
* Consider it a fixed security flaw (as logout path was not considered by the `access_control` configuration before), but clearly document the change in the upgrade guides for all supported versions.

**Additional context**  
`app/config/security.yml`:
```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: pass, roles: [ 'ROLE_USER' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:        ^/
            form_login:
                check_path: example_login_check
                login_path: example_login
                require_previous_session: false
            logout:
                path:       example_logout
                target:     /
            anonymous:      ~

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/test$, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_DUMMY_NO_ACCESS }
```

**Comment by stof** [comment]
hmm, #24805 made the logout listener the last one. But the access listener is also special (it is not about authenticating, but about authorizing), so I think this one should have been kept after the logout one.

**Comment by nicolas-grekas** [comment]
ping @MatTheCat maybe

**Comment by chalasr** [comment]
I'm divided, we must specify an access rule for any login path so the original behavior for logout sounds inconsistent, but I'm not sure it deserves such a behavior change. 
I'm up for a PR that restores the original behavior by making the access listener last, the same way we did for the logout one.

**Comment by xabbuh** [comment]
The current behaviour is a bug to me. What would be the point in not allowing the user to log out (and that's the only affect you could achieve by defining access control rules for this path, right?)? We cannot prevent the user from logging out in most cases anyway (they can delete cookies for example).

**Comment by chalasr** [comment]
I'm on it.

**Comment by MatTheCat** [comment]
@xabbuh the point would be to do what is actually expected. Everyone must ensure their login form is under a public firewall but it makes no sense authenticating someone on a login form. That's just the way it works and I don't see why the access control on logout would be an exception.

**Comment by chalasr** [comment]
See #28100
