### ISSUE TITLE
Overriding service in Symfony 4

### ISSUE THREAD

**Issue by mehira-propertyfinder** [symfony/symfony#28063]
**Symfony version(s) affected**: 4.1.*

**Description** 

I am migrating our project to Symfony 4. In my test suites, we used PHPUnit for functional tests (I mean, we call endpoints and we check result). Often, we mock services to check different steps.

Since I migrated to Symfony 4, I am facing this issue: `Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The "my.service" service is already initialized, you cannot replace it.` 

**How to reproduce**  

`static::$container->set("my.service", $mock);`

**Possible Solution** 

In TestContainer authorize overriding service.

**Comment by mehira-propertyfinder** [comment]
this behaviour seems specific to our needs, I created a test container and overrided `set` method.

**Comment by drzraf** [comment]
I think something still need to be clarified on this.
During integration testing, I want to dynamically replace a service's method to avoid webservice request. I'd expect to be able to do this using `static::$container->set()` during a given test.



Ref: https://stackoverflow.com/questions/51520797
