### ISSUE TITLE
Messenger Bug with transports, not found amqp or something.

### ISSUE THREAD

**Issue by lpj145** [symfony/symfony#28068]
![image](https://user-images.githubusercontent.com/11980109/43280357-02551572-90e7-11e8-9387-42269ec833e4.png)
![image](https://user-images.githubusercontent.com/11980109/43280535-7f0e877e-90e7-11e8-9255-580c9d89b759.png)

**Description**  

When used messenger component, i get a error.

**How to reproduce**  

Install symfony, add or require symfony messenger
configure and try request.

**Possible Solution**  

**Additional context**

**Comment by lpj145** [comment]
ok... to you reproduce this install latest framework version and latest messenger component, i can't share application because she is in production.

**Comment by lpj145** [comment]
my bad mind.... composer require amqp. solved issue.

**Comment by sroze** [comment]
Good to know; thanks for sharing the resolution :)
