### ISSUE TITLE
Grammatical Exception Error: Expected argument of type "array or Traversable and ArrayAccess", "string" given

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28073]
**Symfony version(s) affected**: 4.1.1

**Description**  
Shouldn't it be `Expected argument of type "array, Traversable, __or__ ArrayAccess". "string" given` ?

**Comment by ChangePlaces** [comment]
Have done: https://github.com/symfony/validator/pull/23

**Comment by nicolas-grekas** [comment]
Please submit again on this very repo.

**Comment by ChangePlaces** [comment]
The original error message is fine, mine wasn't! See pr for more details
