### ISSUE TITLE
[Config] Show supported options when unsupported option is provided

### ISSUE THREAD

**Issue by sstok** [symfony/symfony#28075]
**Description**  
In the Symfony Slack someone encountered the following error, the `validator` option does not exist as it's `validation`. Yet the exception message did provide any helpful tips to resolve this issue.

![image](https://user-images.githubusercontent.com/904790/43311340-7907673a-918a-11e8-84cc-ec2f0f0a63bd.png)

I would be helpful to list (if possible) the supported options and/or show a "did you mean?".

**Example**

`Unrecognized option "validator" under "framework", supported options are "validator", "...".`

**Comment by nicolas-grekas** [comment]
For reference the error is fixed in https://github.com/symfony/recipes/pull/445
(but this doesn't invalidate this RFC)
