### ISSUE TITLE
Encore installation with Flex does not create package.json file

### ISSUE THREAD

**Issue by mikemix** [symfony/symfony#28071]
**Symfony version(s) affected**: 4.1

**Description**  
[Docs](http://symfony.com/doc/current/frontend/encore/installation.html) say that if using Flex one can "can initialize your project for Encore via". Then: "This will create a webpack.config.js file, add the assets/ directory, and add node_modules/ to .gitignore.".

I just ran:

`composer require symfony/webpack-encore-pack` and there's no package.json file to be found :(

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you show the output you get when installing this package? Does running `composer fix-recipe` solve the issue you have?

**Comment by JoolsMcFly** [comment]
I just had the same issue.
`composer fix-recipe` did not help.

I ran `composer remove symfony/webpack-encore-pack` and then `composer require symfony/webpack-encore-pack` one more time and  `package.json` and `webpack.config.js` were created as expected.

**Comment by xabbuh** [comment]
I am closing here as there is nothing else we can do.

**Comment by shmolf** [comment]
I was using `symfony/webpack-encore-bundle`. Before I ran `composer require symfony/webpack-encore-bundle`, I had a pre-existing `package.json` file that was mostly empty. It seems that if the file already exists, the recipe won't update the file. It expects the file to not yet exist.

My solution was to delete the the file (version control will retain what lines I had), the run the commands:
- `composer remove symfony/webpack-encore-bundle`
- `composer require symfony/webpack-encore-bundle`

Then, migrate any of my old config from `package.json` to the newly created one.
