### ISSUE TITLE
Error in case of installation symfony/website-skeleton

### ISSUE THREAD

**Issue by opxwebdev** [symfony/symfony#28076]
**symfony/website-skeleton**: 4.1.2.3

**Description**  
When installing website-skeleton, the following error is displayed:
```
...
  - Configuring symfony/phpunit-bridge (>=4.1): From github.com/symfony/recipes:master
  - Configuring symfony/web-server-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 311:
!!                                                       
!!    Unrecognized option "validator" under "framework"  
!!                                                       
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

The error is repeated on two different servers.
First server: composer 1.6.5 and PHP 7.2.7
Second server: composer 1.6.5 and PHP 7.1.19

**How to reproduce**  
`composer create-project symfony/website-skeleton .`

**Comment by nicolas-grekas** [comment]
Duplicate of https://github.com/symfony/website-skeleton/issues/42
Fixed in https://github.com/symfony/recipes/pull/445
Please retry.

**Comment by opxwebdev** [comment]
Thank you. Everything works great.
