### ISSUE TITLE
Allow to explicitly choose argon2id variant - Argon2idPasswordEncoder?

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#28093]
Background: `argon2id` has become the default since `libsodium` 1.0.15: https://github.com/jedisct1/libsodium/blob/7cdf3f0e8419aa1be306effd11a20d980c118e04/ChangeLog#L27-L28

and will also be available (without the `sodium` extension) in PHP 7.3: https://wiki.php.net/rfc/argon2_password_hash_enhancements

It might be a good idea to allow the user to explicitly specify the desired variant. Especially since it is the recommended variant: https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03#section-9.4

**Comment by chalasr** [comment]
Supporting more argon2 variant sounds good to me 👍

**Comment by Simperfit** [comment]
sounds good to me

**Comment by teohhanhui** [comment]
The situation is quite dire now...

For example with the `alpine3.8` variant of PHP 7.2 Docker images recently being added: https://github.com/docker-library/php/pull/688

Be careful!

PHP 7.2's `password_verify` does **NOT** support `argon2id`. If you have previously been using the `sodium` extension's `sodium_crypto_pwhash` / `sodium_crypto_pwhash_str` to encode the password, the default algorithm has been `argon2id` for some time now. Just a heads-up!

Reference: https://igotaprinter.com/blog/argon2i-php-password-hash-not-compatible-libsodium.html (site has expired SSL certificate laughing)

**Comment by teohhanhui** [comment]
This means that Symfony users who have been using the `Argon2iPasswordEncoder` are affected if the following conditions are both satisfied:

- They have been using any recent version of the `sodium` extension, but does not have `PASSWORD_ARGON2I` defined; and
- They now have `PASSWORD_ARGON2I` defined.

An example is anyone who has been using the `php:7.2*-alpine` Docker official image, which I'd guess could be quite a lot of people.

I'm not sure how we should fix this...

**Comment by chalasr** [comment]
@teohhanhui Just spent some hours at trying to understand the situation.
I confirm, the `Argon2iPasswordEncoder` already deals with argon2id depending on the libsodium extension installed version. 
There is no way to choose which variant to use when relying on the extension, as explained by the maintainer:

> sodium_crypto_pwhash_str() uses the best algorithm available in the currently installed version of libsodium for the current platform.
It can be Argon2i, Argon2id, or something else depending on the platform (Argon2 is currently not a good fit for constrained environments and WebAssembly). You shouldn't assume that it is a specific algorithm.
>[...]
>The default algorithm was changed from Argon2i to Argon2id in libsodium 1.0.15. It may change again soon, at least for some platforms. 

Full discussion can be found here: https://github.com/jedisct1/libsodium-php/issues/194

To summarize:
- As of 7.3, PHP provides both `PASSWORD_ARGON2I` and `PASSWORD_ARGON2ID` constants when compiled using `--with-password-argon2`. This means that when at least one of the two constants is available, we can safely choose the variant to use. 
- When none of the `PASSWORD_ARGON2*` constants is available but one of ext-sodium or ext-libsodium is installed, we rely on it. In this case, we have no way to explicitly choose the variant. What we know is that the extension uses `argon2i` for versions <1.0.15, and `argon2id` for versions >= 1.0.15.

I'm not sure about what should be done exactly yet, especially for stable branches. 
At least I'm sure that the current behavior being to use `password_*` functions when `PASSWORD_ARGON2*` is available and falling back to `sodium_crypto_pwhash_str*` is not good for the case you mentionned (argon2id hashed password obtained from `sodium_crypto_pwhash_str` but verified via `password_verify(..., PASSWORD_ARGON2I)`).

I'll keep working on this and try to find a compromise before adding support for the PHP 7.3 `PASSWORD_ARGON2ID` constant. 
Any input welcomed.

**Comment by teohhanhui** [comment]
It seems like it's possible to choose the algorithm being used by calling [sodium_crypto_pwhash](https://secure.php.net/manual/en/function.sodium-crypto-pwhash.php) directly.

I see there are these [predefined constants](https://secure.php.net/manual/en/sodium.constants.php) available for choosing the password hashing algorithm:

- SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13
- SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13

**Comment by chalasr** [comment]
Looks very interesting. 
Hopefully we should be able to make `Argon2iPasswordEncoder` producing only passwords hashed with argon2i. 
For passwords which have already been hashed with argon2id via the extension, I think we can fix the case you mentioned by not using `password_verify()` if the incoming hashed password starts with `$argon2id$v`.
I'm pretty confident we can restrict the current encoder to argon2i only, then support both variants by introducing a new `Argon2PasswordEncoder` that takes the algorithm to use as constructor arg.
PRs coming. Thanks!
