### ISSUE TITLE
Passing '--no-debug' => true to CommandTester execute doesn't appear to disable debugging

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28094]
**Symfony version(s) affected**: 4.1.1

**Description**  
I'm testing a console command and I need to pass `--no-debug` to disable the debugging, otherwise memory is expired and the command runs out of memory. This is do-able when running from the CLI, however is also necessary in testing. I have this following code, and memory limit is still hit causing `Killed` to appear when the command runs out of memory.

```
        $command = $app->find('manager:install-categories');
        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
            '--env' => 'test',
            '--no-interaction' => true,
            '--no-debug' => true,
        ]);
```

The command is certainly receiving the `--no-debug` input, but somehow the symfony system still seems to be chewing up memory. I'm confident it isn't the command itself.

**How to reproduce**  
I'm not sure the best way to reproduce. The command does a lot of database work via doctrine. I've optimised it the best I can after reading a lot, including `$manager->clear()` but symfony still appears to be increasing the memory. This does not happen when using `--no-debug` from when running from command line.

**Comment by ChangePlaces** [comment]
I seem to have stumbled upon a solution - when booting the kernel in the tests, to pass the arg 'debug' => false, e.g. `$kernel = self::bootKernel(['debug' => false]);`

Is this expected behaviour?

**Comment by chalasr** [comment]
Yes, that's expected. 
The `--no-debug` option is only consumed by the `bin/console` script (see https://github.com/symfony/recipes/blob/584967704025c23f12165a259fd80a5ad7717509/symfony/console/3.3/bin/console#L27-L37) for enabling the debug component and setting the kernel's debug mode.

**Comment by ChangePlaces** [comment]
Oh, interesting, thanks. That will come in useful elsewhere!
