### ISSUE TITLE
[Console] Sort alphabetically command arguments and options while describing definition

### ISSUE THREAD

**Issue by natepage** [symfony/symfony#28108]
**Description**  
When running the console application with no command, it provides a full description of itself, listing all `Options`, `Available commands`. The commands (and associated namespaces) are alphabetically sorted which is really handy, but this logic hasn't applied to the arguments and options.

Alphabetical order is amazing, this issue is here to suggest to apply it to the arguments and options when describing the commands definitions.

**Example**  
Here is a screenshot of the current console output:
![image](https://user-images.githubusercontent.com/11576446/43566424-aadf650a-9671-11e8-9447-33839d7c7599.png)

And here the same output with the options alphabetically sorted:
![image](https://user-images.githubusercontent.com/11576446/43566459-cb854086-9671-11e8-9eca-cef1a9358090.png)

**Comment by nicolas-grekas** [comment]
I'm not sure this is desired: instead, I'd expect authors to be able to decide which order makes more sense, with the most important options first. Don't you think?

**Comment by natepage** [comment]
@nicolas-grekas Thanks for your comment. Yes, I understand your point, we can implement a new `$priority` property on `InputOption` and sort them in a similar way as services?

The `$priority` will be optional and default to 0. And to be consistent with services we display first the options with the biggest priority. I'm happy to update my PR this way, I will just wait to see how it sounds to you and others if they want to get involved :)

PS: I will also rename my issue and PR to talk only about options because after reading the documentation again (and think a little bit), sorting arguments would have a really bad impact because they are ordered so if we don't display them in the order you're supposed to pass them people will go through some "funny" situations.

**Comment by TomasVotruba** [comment]
I love the idea because it makes easier to find one option among dozen others.

Not by default though. Optional argument on class turning this on is must have.

**Comment by chalasr** [comment]
I agree with @nicolas-grekas here, I expect my command options/arguments to be listed in the order I defined them. If we want this, it should be optional and disabled by default to me.

**Comment by natepage** [comment]
Hi @here, I would like to ask for a decision, I'm happy to do the work for the solution using `$priority` but before that I would like to know if the community likes the idea and feature :)

**Comment by fabpot** [comment]
I agree with both @nicolas-grekas and @chalasr, not sorting was a conscious decision back then. And I would not make it configurable. Last but not least, arguments must never be sorted as they must be listed in the usage order.

**Comment by TomasVotruba** [comment]
By the example in issue description I guess the point is in sorting *options* only, isn't it @natepage ?

Could elaborate why not make sorting *options only* configurable?

**Comment by nicolas-grekas** [comment]
On my side: because "configurable" means "choice", and "choice" means confusion/complexity.

**Comment by TomasVotruba** [comment]
Not in this case. When there is 20 options like in PHP_CodeSniffer and I look for one related to "format/output something", this *choice* actually brings claritfy, readability and very pleasant developer experience. 

I'd be happy to provide such nice output in CLI applications I make, but I'm to lazy to reorder items manually everytime I add one.

**Comment by TomasVotruba** [comment]
That was just example :D

**Comment by nicolas-grekas** [comment]
`composer help command --sort-options`...

**Comment by chalasr** [comment]
As said, command options and arguments should be defined and listed by order of importance/relevance. I don't think this would help describing commands, really.

Closing as 3 core members are against this feature, thank you for proposing.

**Comment by TomasVotruba** [comment]
It seems like development of framework is based on personal preferences 3 people.
