### ISSUE TITLE
User Deprecated: Doctrine\Common\ClassLoader is deprecated.

### ISSUE THREAD

**Issue by OtezVikentiy** [symfony/symfony#28119]
**Symfony version(s) affected**: 4.1.3

**Description**  
In Symfony Profiler i can see that Doctrine\Common\ClassLoader is deprecated. And in the trace i can see, that it refers to the Repository of one of the classes, that was autogenerated with the Entity. And it refers to the string where is called parent construct of the class ServiceEntityRepository. Could you please provide some instructions how could i get rid of this notice in profiler?

**How to reproduce**  
![image](https://user-images.githubusercontent.com/19647948/43599859-95c968a8-9691-11e8-8385-95e91f1af12d.png)

![image](https://user-images.githubusercontent.com/19647948/43599874-9f7522ac-9691-11e8-83de-9269d07ee7a0.png)

**Comment by Nelrod49** [comment]
Check this answer on StackOverflow 
https://stackoverflow.com/questions/51342512/user-deprecated-doctrine-common-classloader-is-deprecated

**Comment by xabbuh** [comment]
This was fixed in Doctrine ORM (see doctrine/doctrine2#7326) but not released yet. I am closing here as there is nothing we can do in Symfony.

**Comment by OtezVikentiy** [comment]
Thanks a lot, guys! )))

**Comment by ragboyjr** [comment]
I was able to remove this warning by strictly requiring: `"doctrine/common": "2.8.1"` for now.

**Comment by crabnky** [comment]
Hmm, I have 2.9.0 and still can see this deprecation in the profiler...

**Comment by GuillaumeSTEIN** [comment]
@crabnky As suggested by @ragboyjr, I have set `"doctrine/common": "2.8.1",` and not `^2.9`.
The deprecation should not be here anymore.

**Comment by stof** [comment]
@crabnky this deprecation is precisely triggered *when* you have doctrine/common 2.9.0 (because the 2.9.0 release is the one adding the warnings, and the fix in the ORM is not released)

**Comment by crabnky** [comment]
Oh, thanks, understood. Do you know when the new version is planned to be released?

**Comment by stof** [comment]
no. That's something you need to ask to the Doctrine ORM maintainers.
