### ISSUE TITLE
accepting callbacks  for symfony/options-resolver -> setAllowedValues() 

### ISSUE THREAD

**Issue by jkhaled** [symfony/symfony#28129]
**Description**  
component : symfony/options-resolver
class: OptionsResolver
method: setAllowedValues()

add capability for **setAllowedValues** to accept callbacks , instead of rewriting the same Closure for same allowed value  , for sharing and prevent retyping

**Example**  
```php
class MyAllowedValue {
    public function date_type($value){
        //example :  accept only date format to be in dd-mm-yyyy
        return preg_match('[0-9]{2}-[0-9]{2}-[0-9]{4}', $value);
    }
}
$optionResolver->setAllowedValues('date_in', [(new MyAllowedValue()), 'date_type']);

//2nd or inside class
class MySimple {
    public function configureOptions(array $option)
    {
        $resolver = new OptionsResolver();
        $resolver->setDefault('option_name', 'default');
        $resolver->setAllowedValues('option_name', [$this, 'myAllowedValues']);
    }
    public function myAllowedValues($value){
        // do some work
        return true;// | false
    }
}
```

**Comment by yceruto** [comment]
Hi @jkhaled Yes, I also think that allowing `callable` instead of `\Closure` opens more alternatives, but since PHP 7.1 we can use [`\Closure::fromCallable()`](http://php.net/manual/en/closure.fromcallable.php) that converts a callable into a closure, which is enough to solve the problem... what do you think?

**Comment by jvasseur** [comment]
Allowing `callable` would make the argument ambiguous, since it could be interpreted as an array of values that you want to allow.

**Comment by jkhaled** [comment]
@jvasseur I have just created a PR for the implementation, tested
 you can check

**Comment by sstok** [comment]
@jkhaled Can you link the pull-request here? Thanks.

**Comment by xabbuh** [comment]
I am against making such a change. As said above supporting all types of callables makes the option value ambiguous. That's by the way the reason we dropped this kind of support for some options provided by core form types.

**Comment by HeahDude** [comment]
This is a BC break anyway, since a string or an array of two strings currently setting one or two allowed values could then become callable, and there is no way to prevent the break AFAIK.

**Comment by javiereguiluz** [comment]
Let's close this for the reasons given by the maintainers. Also, an alternative solution was given by @yceruto. Thanks.
