### ISSUE TITLE
Error: Class 'Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator' not found in Drupal\

### ISSUE THREAD

**Issue by gecloud** [symfony/symfony#28124]
Yesterday there was a security update of Drupal (8.5.6), which we did. (https://www.drupal.org/SA-CORE-2018-005)
Since then our contact formular modal doesn't work anymore. We get the following error:
Error: Class 'Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator' not found in Drupal\xxx_content\Controller\Helper\SymfonyFormController->createFormBuilder() ......

Looks like following 3 classes are no longer available:
use Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage;
use Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator;
use Symfony\Component\Security\Csrf\CsrfTokenManager;

Is there anything deprecated which we have to change? Does anyone has the same problem?

**Comment by xabbuh** [comment]
I don't know how this is handled inside Drupal, but the missing classes indicate that you are probably missing the `symfony/security-csrf` package.

**Comment by nicolas-grekas** [comment]
I'm closing as this doesn't look like a bug in the code.
