### ISSUE TITLE
Symfony Form conflict with Symfony Security 

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#28132]
**Symfony version(s) affected**: x.y.z
4.1.2
**Description**  

Full description here, it is not spam, just found the same issue. 
https://www.questarter.com/q/symfony-quot-spl-object-hash-expects-parameter-1-to-be-object-string-given-quot-when-editing-with-form-entity-type-27_45386090.html

**How to reproduce**  

Simply. Create user and role antities. User has roles, relation many to one (roles -> user), or if user to roles, one to many. Now, if you create form to update user with checkboxes, as described in links, getRoles method in User entity from UserInterface must return object, this is fo form. Ok, it is fine. But if it returns object, Security component fails to authenticate or authorize user or his actions, because the same method must return string not object as in case of symfony form component. 

**Possible Solution**  

Not good solution, entity Role must extend symfony Role class from core package. It is not comfortable, and very undesirable  dependency. Plu getRoles method  in user entity, have to return $this->roles->toArray(0 method from ArrayCollection class. Here is ok, no problem, but there is another  issue, that if i want to use it As collection, i have to declare one more method. 
Also, i tried to rewrite form type, that roles getter should be another  one. But no luck, seems it is hardcoded and can not be modified, EntityType when you getting roles, must be used exactly  with getRoles method, no way, same with security component. That means  they conflict with each other, which is bad.

**Additional context**  

If you need more info, please tell me. Except creating demo project, i do not have much time at the moment.

**Comment by xabbuh** [comment]
If you want to manage your user roles as real Doctrine entities and not just a plain list of strings, you have two solutions:

Create a different class that implements the interface from the Security component. Then write your own user provider that reads the user from the database and populates the user object based on the data being read from the database, but transform the role objects to their string representation.

Have two methods in your user entity. One that returns the role objects for your form type and one that returns strings to respect the interface from the Security component.

**Comment by BonBonSlick** [comment]
@xabbuh  i told that tried to rewrite forms getRoles method without luck. I did it like this

`  ->add('roles', EntityType::class, [
            'class' => Role::class,
            'multiple' => true,
            'expanded' => true,
            'query_builder' => function(RoleRepositoryInterface $roleRepository) {
                /** @var RoleRepositoryInterface|EntityRepository $roleRepository */
                return $roleRepository->createGetAllEntitiesQueryBuilder();
            }
        ])
        ;
        $builder->setDataMapper(
            new PropertyPathMapper(
                new CustomFormTypePropertyAccessor(
                    [
                        'roles'     => 'rolesObjectsCollection',
                    ]
                )
            )
        );`


`
class CustomFormTypePropertyAccessor extends PropertyAccessor
{
    /**
     * @var array
     */
    private $customSets;

    /**
     * @var array
     */
    private $customGets;

    /**
     * @inheritDoc
     */
    public function __construct(
        array $propertySets = [],
        array $propertyGets = [],
        $magicCall = false,
        $throwExceptionOnInvalidIndex = false
    ) {
        parent::__construct(
            $magicCall,
            $throwExceptionOnInvalidIndex
        );
        $this->customSets = $propertySets;
        $this->customGets = $propertyGets;
    }

    /**
     * @inheritDoc
     *
     * @throws InvalidPropertyPathException
     */
    public function getValue($objectOrArray, $propertyPath)
    {
        if (isset($this->customGets[(string)$propertyPath])) {
            $propertyPath = new PropertyPath($this->customGets[(string)$propertyPath]);
        }

        return parent::getValue(
            $objectOrArray,
            $propertyPath
        );
    }

    /**
     * @inheritDoc
     *
     * @throws InvalidPropertyPathException
     */
    public function setValue(&$objectOrArray, $propertyPath, $value) : void
    {
        if (isset($this->customSets[(string)$propertyPath])) {
            $propertyPath = new PropertyPath($this->customSets[(string)$propertyPath]);
        }
        parent::setValue(
            $objectOrArray,
            $propertyPath,
            $value
        );
    }
}`

**Comment by xabbuh** [comment]
What does it mean that it does not work? What kind of error do you get?

A way simpler approach by the way would be to add methods like `getRoleObjects()` and `setRoleObjects()` and then use the `property_path` option for the entity type with a value of `roleObjects`.

**Comment by BonBonSlick** [comment]
@xabbuh  no errors, it just use old method getRoles, not one from custom accessors array.

**Comment by HeahDude** [comment]
Hello @BonBonSlick, for the solution using another method for the form, you need to set in in your type:
```php
->add('roles', EntityType::class, array(
    'class'=>'AppBundle\Entity\Role',
    'multiple'=>true,
    'expanded'=>true,
    'property_path' => 'rolesCollection'
)
```
and then the Symfony default property accessor will call `get/setRolesCollection`.

**Comment by iltar** [comment]
To make this problem disappear, please decouple your entities from the security and forms:
 - https://stovepipe.systems/post/avoiding-entities-in-forms
 - https://stovepipe.systems/post/rethinking-form-development
 - https://stovepipe.systems/post/decoupling-your-security-user

**Comment by BonBonSlick** [comment]
@iltar @HeahDude @xabbuh  thank you everyone.

**Comment by xabbuh** [comment]
I think we can close here as there is nothing to fix.
