### ISSUE TITLE
Action Argument Resolver  recreates incoming http Request object

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#28131]
**Symfony version(s) affected**: x.y.z
4.1.2
**Description**  

I want to set up validation for request, and then passe further modified url, like set locale code, or pagination values per page, page, or search url. But, if i use such way, with resolver, I have data what i need before request passed, injected in controller method. There i have absolutely  new Request object, without any modifications. that is sad. Pagination, search not work such way.

**How to reproduce**  

Very simple
1 - create [Action ArgumentResolver](https://symfony.com/doc/current/controller/argument_value_resolver.html)
2 - accept there modified request, or modify it in resolver,
3 - inject in controller method new resolving request, example CustomRequest $request you resolving
4 - try to get data from this request. Query is empty, request is empty.

**Possible Solution**  

I do not know yet, we need modified request, it is data. I am thinking about session, but not every package use session, some of them just modifying request, so these package will not work, because they must use session to pass data to server. So we have no good solution at the moment.

**Additional context**  

Code samples i tried
```

{% set route = app.request.get('_route') %}
{% set route_params = app.request.get('_route_params') %}
<a href="{{ path(route, route_params | merge({ '_locale': 'l1' })) }}">lang1</a>
<form action="{{ path(app.request.attributes.get('_route')) }}" method="GET">
                        <button type="submit"
                                value="en>
                            en
                        </button>
                    </form>
{{ dump(path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({
            'locale': 'en',
            })) ) }}
    {{ dump(path(app.request.attributes.get('_route'), app.request.query|merge({
            'locale': 'en',
            }))) }}


Resolver.php
public function supports(Request $request, ArgumentMetadata $argument) : bool
    {
...modifications, checks, whatever actions
        yield new  CustomModifedRequest($request);

Cotnroller
public function index( CustomModifiedRequest $myRequest) 
$myRequest << --- it is empty
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue? Just from your description I am not sure I really understand how your implementation looks like.

**Comment by BoShurik** [comment]
I cant reproduce this
```
public function action(Request $request, DTO $dto)
{
   dump(spl_object_id($request));
   dump(spl_object_id($dto->request));
}
```
Both requests are equal

**Comment by BonBonSlick** [comment]
@BoShurik  oh, thanks, i found an issue with you help, This function helped a lot to debug `spl_object_id`,  there is listener for exception, which thrown when in dto. Thank you  for you time. issue can be closed.
