### ISSUE TITLE
[SecurityBundle][DX] http://symfony.com/schema/dic/security schema is missing

### ISSUE THREAD

**Issue by kaznovac** [symfony/symfony#28141]
**Symfony version(s) affected**: ^3|^4 (and possibly ^2)

**Description**  
SecurityBundle references namespace 'http://symfony.com/schema/dic/security'
but it's xsd schema is missing. this is nice to have but not feature impeding.

**How to reproduce**  
there are numerous references for 'http://symfony.com/schema/dic/security' in 'src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/Fixtures/xml/*.xml'
and `\Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::getNamespace` returns this namespace.

**Possible Solution**  
provide schema for 'http://symfony.com/schema/dic/security', like the ones for services, twig `xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd
                        http://symfony.com/schema/dic/twig http://symfony.com/schema/dic/twig/twig-1.0.xsd"`

**Comment by javiereguiluz** [comment]
@kaznovac sorry for the lack of response. I'm trying to fix this ... but I can't find the `security.xsd` or `security-1.0.xsd` file anywhere in Symfony's code. Do you know where I can find the XSD for `http://symfony.com/schema/dic/security`? Thanks.

**Comment by xabbuh** [comment]
As far as I know we do not have a schema definition file for the SecurityBundle config.

**Comment by kaznovac** [comment]
@javiereguiluz I was suspecting that there is no schema, and @xabbuh confirmed that.

We need to write it (if structure defined in `Symfony\Bundle\SecurityBundle\DependencyInjection\MainConfiguration` allows it).
I can assist, hope I can find some time this weekend or the next one...

**Comment by Simperfit** [comment]
@kaznovac did you find time to do this ?

**Comment by kaznovac** [comment]
@Simperfit sorry I haven't got much time lately (became a father 2.5 moths ago)

I've looked into it, scratched it out, and figured out that I need a XSD refresher course (how to import elements from another schema for providers, see this dynamic definition for providers section https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php#L371-L376) ;)

Also Symfony Security rework #30914 can affect the form of the configuration/schema.

**Comment by Simperfit** [comment]
Thanks for the response ! Congratulation, I’m a father since 1 month in 3
days, I understand :).

Le dim. 7 avr. 2019 à 21:18, Marko Kaznovac <notifications@github.com> a
écrit :

**Comment by HeahDude** [comment]
See #36072 which may add it in master.
