### ISSUE TITLE
[LDAP] No error description on search failure

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#28149]
**Symfony version(s) affected**: 4.1, 3.4

**Description**  
When query fails due to LDAP misconfiguration, i.e invalid query filter, we ran into `Could not complete search with dn` exception statement, which gives us no clue, how to resolve this problem.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L92

In order to resolve it you should manually dig with debugging what happens there and manually use `ldap_error` and `ldap_errno` to discover the actual problem.

**How to reproduce**  
Configure improper filter string for LDAP (i.e wrap it with double quotes, in my case)

**Possible Solution**  
Enrich exception with `ldap_error` and `ldap_errno` output if present

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR? The LDAP component needs love, from someone that actually uses it.

**Comment by scaytrase** [comment]
I think I can propose one, if it will reach 3.4 branch.

**Comment by scaytrase** [comment]
@nicolas-grekas I can propose this simple improvement 

https://github.com/symfony/symfony/pull/28424
