### ISSUE TITLE
[DX][Debug] Fix a service by its class name

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony#28143]
Given the following service registered:

```yaml
services:
    Acme\Foo: ~
```

Running the following will fail:

```shell
bin/console debug:container Acme\Foo
```

The reason being the correct way would be to escape the backslash:

```shell
bin/console debug:container Acme\\Foo
# or
bin/console debug:container "Acme\Foo"
```

~~I however find a bit tedious and unfriendly: I register a service by a class but if I copy/paste the class I won't find the service... Plus it's a bit annoying manually escape if there is a lot of backslashes. Maybe the `debug:container` command could be made a bit smarter to understand the `AcmeFoo` is similar to `Acme\Foo`.~~

Edit: The DX issue here IMO is that the simple copy/paste does not work (you need to escape the service name) and that can lead to confusion. Maybe the error message could help a bit with it

**Comment by apfelbox** [comment]
This might open a can of worms, as not escaping will lead to weird cases, like if your class is named like `App\namespace\hi`. Then you would have a line break inside the text.

Would it help if we add a message to the command in case no class is found, that the user might want to retry with properly escaping the class name?

**Comment by theofidry** [comment]
Hm indeed :/

>Would it help if we add a message to the command in case no class is found, that the user might want to retry with properly escaping the class name?

That's probably the best solution then. It doesn't help when you have `Acme\My\Very\Long\Namespace\To\Escape\Foo` to escape but at the same time one can always just type `Foo` and see the list of results...

**Comment by ogizanagi** [comment]
@theofidry : FYI, just wrapping it with double quotes works. No need to escape each backslash (doesn't mean we should not do anything, though).

**Comment by theofidry** [comment]
oh my, completely forgot about that, cheers :) It definitely helps with the original issue, I'll keep the issue open though as I think we could improve a bit the error message

**Comment by TomasVotruba** [comment]
I would not want to find out to think about escaping this, good idea :+1:

**Comment by stof** [comment]
The thing is, we cannot know whether you wrote `Acme\Foo` or something else (it appears as `AcmeFoo` for PHP), as this escaping is not something expected by PHP or Symfony, but by your shell

**Comment by nicolas-grekas** [comment]
I'm closing because there is nothing we can do here: passing argument to commands in a shell needs to write in the shell's language, including escaping/quoting arguments...

**Comment by theofidry** [comment]
@nicolas-grekas you think it would be ok to change the error message to suggest to escape the service name?

**Comment by nicolas-grekas** [comment]
Opening the code, it might actually be quite easy to ignore backslashes when searching ids,
see https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php#L232 and https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/DebugAutowiringCommand.php#L69

Would you like to give it a try?
I'm reopening meanwhile :)
