### ISSUE TITLE
Adding x-forwarded-port causes application to crash

### ISSUE THREAD

**Issue by tomas7777** [symfony/symfony#28153]
**Symfony version(s) affected**: 2.8.44

**Description**  
After updating an application to 2.8.44 and initially setting `x-forwarded-port` header and then making request which will be making sub request `\Symfony\Component\HttpFoundation\Exception\ConflictingHeadersException` is being triggered which causes application to crash. This didn't happen prior to 2.8.44 release. 

**How to reproduce**  
Add `x-forwarded-port` header and make request which will be making sub requests.

**Comment by xabbuh** [comment]
This will probably be fixed with #28144.
