### ISSUE TITLE
[DoctrineBridge] Add new file extension for YAML mapping

### ISSUE THREAD

**Issue by ossinkine** [symfony/symfony#28154]
**Description**
At the moment, the Doctrine mapping with the `yml` type looks for files with the `.orm.yml` extension.
I suggest adding the `.orm.yaml` extension or adding the ability to specify an extension in config.

**Comment by nicolas-grekas** [comment]
PR welcome.

**Comment by ismail1432** [comment]
Maybe I'm wrong (it's happen often :smile:) but the doc said that [use case is cover](https://symfony.com/doc/current/reference/configuration/doctrine.html#mapping-entities-outside-of-a-bundle)

**Comment by chalasr** [comment]
@ismail1432 You're right for the docs, but not for the code (the one you linked is about validation, not schema mapping) :).

I confirm that the `.orm.yaml` extension is not supported, first because of https://github.com/symfony/symfony/blob/373dad371a0ce8a8d3578d52b01e76dd6d4dbe8b/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php#L243-L244.
But especially because of https://github.com/doctrine/doctrine2/blob/4e715727da55b5d54389dfdc749586ccf3b939d4/lib/Doctrine/ORM/Mapping/Driver/SimplifiedYamlDriver.php#L33.
So this requires a doctrine PR (as a bugfix on 2.x since everything about YAML has been removed from the master branch..).

**Comment by ossinkine** [comment]
@chalasr You refer to the default file extension, but it can be overridden in SimplifiedYamlDriver constructor. We can add a new option to the bundle configurion.

**Comment by chalasr** [comment]
@ossinkine you're right, we should be able to fix this in the bridge only.
I wouldn't add a new option though. I think both `.orm.yml` and `.orm.yaml` extensions should just work naturally when configuring `yml` as mapping` type`, and maybe allow using `yaml` as value for the `type` option, that would give the exact same behavior.

**Comment by rpkamp** [comment]
Or maybe we shouldn't help people using YAML for Doctrine mappings since it will be removed in Doctrine 3 anyway so the best thing to do for new projects is not using YAML at all for doctrine mappings (but rather XML or annotations).

**Comment by ossinkine** [comment]
@rpkamp I didn't know that YAML is deprecated, but it seems it's true: https://github.com/doctrine/doctrine2/pull/7374

**Comment by gonzalovilaseca** [comment]
Is anyone working on this PR?

**Comment by xabbuh** [comment]
I am 👎 on investing any time here as support for the YAML format will be dropped in Doctrine 3.

**Comment by vudaltsov** [comment]
What if we copy Yaml loaders to the Doctrine Bridge? The Symfony community uses Yaml a lot, so why not supporting it on our side?

**Comment by xabbuh** [comment]
I am against that too. In the documentation we recommend to use annotations for configuring the Doctrine mappings. So IMO it's not worth to take over maintenance of the YAML driver. If someone's really interested in still having it supported, they should (from my point of view) create a new dedicated package for that.

**Comment by vudaltsov** [comment]
I agree with you, @xabbuh. Then let's close this issue?

**Comment by stof** [comment]
Taking over the maintenance ourselves would be even worse, because it means that any mapping change in Doctrine would have to be ported to the external YAML driver.
