### ISSUE TITLE
Follow RFC 5646 format for language identification

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#28150]
**Description**  
Translator component use the following format language_REGION (ex: fr_FR) to identify language as per https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations

This format is not the one from the RFC 5646 which requires to use language-REGION (ex: fr-FR) with a hyphen instead of underscore.

For BC reason this underscore format should be kept but the component should also looks for a file with the hyphen format.

Some more reading: https://en.wikipedia.org/wiki/Language_code

Edit: after some research, both formats are wildly used so Symfony should look for both.
IMO, hyphen format is consistent with the HTTP header `Accept-Language` and should be used first when looking for files.

**Comment by Seb33300** [comment]
Format with an underscore is part of [ISO/IEC 15897](https://en.wikipedia.org/wiki/Locale_(computer_software)#POSIX_platforms) specification.

**Comment by nicolas-grekas** [comment]
The benefit of using one single format is nobody can argue anymore about which one is better.
Like for code-style related discussions, what matters most is that everyone remains consistent with the common practice. For this reason, I would not recommend to allow the hyphen alternative.

**Comment by nicolas-grekas** [comment]
Closing as discussed.
