### ISSUE TITLE
[Symfony Form] configureOptions not called while requesting page with form in tests

### ISSUE THREAD

**Issue by SebTM** [symfony/symfony#28155]
Steps to reproduce:

- Create a Form-Class with "configureOptions" method
- Set "csrf_token_id" to defaults
- Make test and use Client to submit form directly (POST-Request | use TokenManager to get csrf-token with given configured ID)
- Get error-message "Invalid csrf-token."

If you debug into "Symfony\Component\Security\Csrf\CsrfToken" into "__construct" and log "$id" and "$value" you will recognize that by browsing the page, you get requested the right token ID. In tests you get a token for your form-name.

If you make a simple output in "configureOptions" you will get this while browsing, but it will not occur while running the tests.

**Comment by xabbuh** [comment]
I am not sure I understand your issue. Can you please create a small example application that allows to reproduce?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by SebTM** [comment]
Hey @xabbuh, sorry for the lack of feedback didn't had time to check it again - was another not symfony related issue!
