### ISSUE TITLE
The profiler URL filter is requiring a valid complete URL with HTML5 input

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#28157]
**Symfony version(s) affected**: 4.1.3

**Description**  

When using the profiler URL filter, the html5 validation required a complete URL.

But if you remove the HTML5 validation, the filter works correctly.

**How to reproduce**  

Try something else than an url, like "test":

![image](https://user-images.githubusercontent.com/1698357/43827132-67a855b2-9af9-11e8-92d5-927351f7d905.png)

**Possible Solution**  

Remove the URL HTML5 validation.

**Comment by javiereguiluz** [comment]
I think we can consider this a bug. When changing this, I thought this was to look for URLs ... but this a free search on any part of URLs ... so the input must should be of `text` type. Could you please send a pull request to dix this? Thanks!

**Comment by Soullivaneuh** [comment]
Here is the commit that introduced the bug: 547076e3ea1f2c9bbab05e1d2f8e6abf09f03153

**Comment by javiereguiluz** [comment]
@Soullivaneuh that's the PR, but only this tiny change should be reverted:

![code](https://user-images.githubusercontent.com/73419/43899697-04b22e48-9be3-11e8-85fd-03aed6cdcdd0.png)
