### ISSUE TITLE
Envelope in symfony/messenger supports only PHP serializable objects

### ISSUE THREAD

**Issue by covobo** [symfony/symfony#28164]
**Description**  
Why does symfony/messenger/Envelope.php (https://github.com/symfony/messenger/blob/master/Envelope.php) support only complex types (classes)? Look at 34 line there is get_class method which makes impossible to use primitive types (like string or boolean).
It's a problem because symfony doesn't support any other header data (it parses only X-Message-Envelope-Items header). How do I share header information between a few microservices? 

**Example**  

If we really want to support only EnvelopeItemInterface items, it's still easy to implement primitives.

There is example:
```
public function __construct($message, array $items = array())
{
        $this->message = $message;
        foreach ($items as $item) {
            if (!is_object($item)) {
                      switch (detect_type($item)) {
                              case TYPE_BOOLEAN:
                                       $item = new EnvelopeItemBoolean($item);
                              break;
                              case TYPE_STRING:
                                       $item = new EnvelopeItemString($item);
                              break;
                             // ..array, int, null
                      }
            }
            $this->items[\get_class($item)] = $item;
        }
 }
```

**Comment by sroze** [comment]
Thank you for opening an issue @covobo. Can you explain a little bit more your use case? What would you like to have as an envelope item exactly?

**Comment by covobo** [comment]
HI @sroze 
Thank you for the attention.

The package symfony/messenger allows us to use rabbitmq message headers.
I have a few microservices which was written in different programming language.
Those services use extra information in headers for deduplication mechanism (they store UUID4 in message headers)..
The package symfony/messenger tries to keep all header information via serialize, right?
So, how do I unserialize php entity in python? I'd like just store primitive type (actually - string) in header information.

My adhoc solution stores in X-Message-Envelope-Items header something like this:
`a:1:{s:65:“BundleNamespace\Bundle\EnqueueMessengerAdapterBundle\UuidEnvelopeItem”;C:65:“BundleNamespace\Bundle\EnqueueMessengerAdapterBundle\UuidEnvelopeItem”:44:{s:36:“cca944be-5ed9-4314-b7fa-4a793114e5a2”;}}`
I can't unserialize it in python, so right now I use regexp.
And it's really funny to gather php-like message in python in order to it will able to work in PHP.

I just want to transfer in headers json-like message:
`"[['uuid' => cca944be-5ed9-4314-b7fa-4a793114e5a2]]"
`

**Comment by covobo** [comment]
It would be better if the package will allow using not only X-Message-Envelope-Items header.

**Comment by sroze** [comment]
Very good point. We've made a significant effort to not "pollute" the message with Symfony nor PHP specific things (like this `serialize`d example). It has been discussed already several times in the [original pull-request](https://github.com/symfony/symfony/pull/26945#issuecomment-386804255), I have to admit I'm not 100% fond of having it, but here is (at least was) the reasoning of using `serialize`:
1. It's super simple
2. These items are "specific" to Symfony
3. We can enforce that every item needs to be `serialize`able with the `Serializable` interface

Obviously, this is describing the reasoning at the time and right now is the good moment to question it as the component is still in an experimental phase.

 > The package `symfony/messenger` tries to keep all header information via serialize, right?

No, it's *only* for the `X-Message-Envelope-Items` header: you can still use any other header. But in order to have access to these headers, right now, you will need to configure a custom message decoder.

> It would be better if the package will allow using not only X-Message-Envelope-Items header.

Can you explain a bit more what you mean by that?

**Comment by covobo** [comment]
I can understand your motivation to use serializer as a packaging and it's really comfortable for symfony-only cases.
But when we are talking about MQ we mean a distributed system and it's multiple language systems by default (not always, but still).
So, in a multilanguage system case, the X-Message-Envelope-Items header is almost useless.
As you mentioned I can configure a custom message decoder and I'm going to do it, but symfony is a framework and I think it will be nice if I will be able to implement my features "out of from the box".

**Comment by sroze** [comment]
I definitely agree with you. Do you use the built-in AMQP transport or do you something else?

**Comment by sroze** [comment]
I believe as well that we should allow having these envelope items being (de)serialized using Symfony's Serializer component. Such a change not being retro-compatible with previous events and have the drawbacks discussed in the PR mentioned earlier, I believe that we need to introduce it as an opt-in.

**Comment by sroze** [comment]
@covobo can you check #28270 and tell me if that would fix your problem?

**Comment by covobo** [comment]
Huge thanks for attention.

@sroze yes, I can, I'll do it this week, but, there is one questionable moment.
Can we avoid that strange keys in headers? Is it possible?
It would be great if I will be able to use some simple keys like 'json-items' in headers for json_encoded data.

I'll do a PR for demonstrating my ideas.
