### ISSUE TITLE
[Validator] BIC country code validation

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#28167]
**Description**  
The BIC validator only checks that the country code is a 2 letters string.

If `symfony/intl` component is available, the validator should check that the country code is valid.

I can submit a PR if you want.

**Example**  
For instance `ASPKAT2LXXX` is valid and `ASPKAA2LXXX` is not as there is no `AA` country code. But both strings pass the validator test.

**Comment by javiereguiluz** [comment]
This looks correct. [ISO-9632](https://en.wikipedia.org/wiki/ISO_9362), the standard behind SWIFT/BIC, says that those two letters must be a "valid ISO 3166-1 alpha-2 country code". So not validating that looks like a bug.
