### ISSUE TITLE
Allow safe usage Response::send in controller

### ISSUE THREAD

**Issue by qRoC** [symfony/symfony#28162]
**Description** 
At the moment the response will be sent every method call.
This is not safe because PHP can fall when you call "echo" after "fastcgi_finish_request".

**Example fall**  
PHP 7.2, sample code. Fail if output after "fastcgi_finish_request" more then 8183.

```php
echo 1;
fastcgi_finish_request();
echo str_repeat(' ', 8183);
echo str_repeat(' ', 1); // fell
$a = 1; // will never be called
```

**Proposal**
```php
private $sendingEnabled = true;
// ...
public function send()
    {
        if ($this->sendingEnabled) {
            $this->sendHeaders();
            $this->sendContent();

            if (\function_exists('fastcgi_finish_request')) {
                fastcgi_finish_request();
                $this->sendingEnabled = false;
            } elseif (!\in_array(\PHP_SAPI, array('cli', 'phpdbg'), true)) {
                static::closeOutputBuffers(0, true);
            }
        }

        return $this;
    }
```

**Comment by nicolas-grekas** [comment]
I would not recommend this change. It's the responsibility of the dev using the response object to do it wisely. Echoing after `fastcgi_finish_request()` is a mistake anyway.

**Comment by qRoC** [comment]
`Echoing after fastcgi_finish_request() is a mistake anyway.`.
But this can not be controlled. Second call in app.php.
Needs or call setContent(''), but this change state of the response object, or add global variable, and wrap second `send` method in condition.

**Comment by fabpot** [comment]
I agree with @nicolas-grekas here, that's not something we want to support.
