### ISSUE TITLE
Do not fail if empty array passed as a value of a property with object array type hint

### ISSUE THREAD

**Issue by mxr576** [symfony/symfony#28161]
**Symfony version(s) affected**: >=3.4.*

**Description**  
`The type of the "foo" attribute for class "Foo\Bar" must be one of "Bar\Baz[]" ("array" given).`

The value was an empty array this is what triggered this error.

**Comment by xabbuh** [comment]
Which exact Symfony version did you use? Can you show some example code that allows to reproduce your issue?

**Comment by mxr576** [comment]
4.1.3

**Comment by xabbuh** [comment]
Okay, and can you show some example code that allows to reproduce?

**Comment by yceruto** [comment]
the exception was thrown here:
https://github.com/symfony/symfony/blob/f834c9262b411aa5793fcea23694e3ad3b5acbb4/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L357

`Serializer` component btw.

**Comment by phpjob** [comment]
I got the same Error.
i have a model e.g.
```
<?php

class Customer {
    /** @var Address[] */
    private $addresses = [];
    
    /**
     * @param Address[] $addresses
     */
    public function setAddresses(array $addresses) {
        $this->addresses = $addresses;
    }
}

class Address {
    private $street = '';
    
    public function setStreet(string $street) {
        $this->street = $street;
    }
}

// untested/prototype -does work
$serializer->denormalize([
    'addresses' => [
        [
            'street' => 'Test Str.'
        ]
    ],
    Customer::class
]);

// untested prototype - error thrown
serializer->denormalize([
    'addresses' => [],
    Customer::class
]);
```

**Serializer Setup:**
- Serializer: `\Symfony\Component\Serializer\Serializer`
- Normalizer: `Symfony\Component\Serializer\Normalizer\ObjectNormalizer`
- PropertyTypeExtractor: `Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor`

**Comment by Kolbasyatin** [comment]
I think it's a not a bug. 
[You have to add the `ArrayDenormalizer` to your `SymfonySerializer`](https://symfony.com/doc/current/components/serializer.html#handling-arrays)

There is my example 

>  `$jsonEncoder = new JsonEncoder();`
> ` $dateTimeNormalizer = new DateTimeNormalizer();`
> ` $arrayDenormalizer = new ArrayDenormalizer();`
> ` $objectNormalizer = new ObjectNormalizer(null, null, null, new ReflectionExtractor());`
>      
> ` return  new SymfonySerializer([$dateTimeNormalizer, $arrayDenormalizer, $objectNormalizer], [$jsonEncoder]);`

**Comment by xabbuh** [comment]
Let's close then. If someone still experiences this issue, please provide an example that allows us to reproduce and we can consider to reopen.
