### ISSUE TITLE
FragmentListener compares exact strings

### ISSUE THREAD

**Issue by maeg77** [symfony/symfony#28163]
**Description**  
Maybe I found a bug in Symfony\Component\HttpKernel\EventListener\FragmentListener

All URL paths **starting** with /_fragment should be handled as content fragments by this listener.

But in line 56 there is an exact comparison and not if the url starts with the configured fragment path:

```
        if ($this->fragmentPath !== rawurldecode($request->getPathInfo())) {
            return;
        }
```

**Possible Solution**  

check if rawurldecode($request->getPathInfo()) starts with $this->fragmentPath

**Comment by nicolas-grekas** [comment]
I'm not sure there is any bug here: fragments are found only at the exact `/_fragment` location (using query parameters to provide additional info.)

**Comment by nicolas-grekas** [comment]
Closing as there as been no anwser so far. Feel free to resubmit and provide more information meanwhile. Thanks for submitting.
