### ISSUE TITLE
Invalid UTF8 User-Agent headers, crash on serialize

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#28172]
**Symfony version(s) affected**: All

**Description**  
We've found some agents that publish the "User-Agent" header with invalid characters, making our app crash when trying to serialize request headers. It's because an invalid UTF8 string.

**How to reproduce**  

```php
<?php

class Message
{

    /**
     * @var string
     * @Serializer\Type("string")
     */
    protected $userAgent;

    public function __construct(string $userAgent)
    {
        $this->userAgent = $userAgent;
    }
}
```

```php
    public function clickAction(Request $request): Response
    {
        $message = new Message($request->headers->get('User-Agent'));
        $this->serializer->serialize($message, 'json');
    }
```

```
curl -X GET \
  https://myserver.com \
  -H 'User-Agent: Hiéá'
```
**Possible Solution**  
Encode User-Agent header with utf8_encode PHP function.

**Comment by javiereguiluz** [comment]
Some info in case it's useful here:

`User-Agent` content is [defined in RFC 7231](https://tools.ietf.org/html/rfc7231#page-46) as:

```
User-Agent = product *( RWS ( product / comment ) )

product         = token ["/" product-version]
product-version = token
```

`token` is defined as:

```
     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters
```

And `comment` is defined as:

```
comment        = "(" *( ctext / quoted-pair / comment ) ")"
ctext          = HTAB / SP / %x21-27 / %x2A-5B / %x5D-7E / obs-text
quoted-pair    = "\" ( HTAB / SP / VCHAR / obs-text )
```

So there are a lot of chars to support for `User-Agent` value.

**Comment by nicolas-grekas** [comment]
I don't think we should do anything here: "you" are responsible for validating/converting inputs' encodings. Using utf8_encode by default would be just a band-aid (as it only converts from iso88591 to utf8, but that's not always the correct thing to do.)
I'm closing therefor. Thanks for submitting.
