### ISSUE TITLE
RFC: Use bundle class for container extensions

### ISSUE THREAD

**Issue by umulmrum** [symfony/symfony#28170]
**Description**  
I'd like to suggest to integrate everything an extension class can do into the bundle class. This would simplify the bundle structure while leaving extensions as a separate concept for use with the standalone DependencyInjection component.

This is why:
- Almost every bundle needs an extension to load services (because that's the main selling point for bundles). Therefore, the extension class is in practice "mandatory", but is currently treated as being optional while the bundle class is promoted as important yet is mostly empty.
- The extension is magically loaded if it has a certain name and lies within a certain namespace. This is error-prone and not straight-forward.
- The bundle class is the most prominent "entry point" for a bundle, although it doesn't do much. For beginners, it would be easier to understand what a bundle does if they only had to look into the bundle class. Not having to find the extension and to understand its importance would improve comprehensibility of the bundle concept. 

The default location of the optional configuration class could then be at the bundle root. Integrating this into the bundle class would be a bit much. A new default location for compiler passes would then make sense.

(maybe it makes sense to load all XML and YAML files in Resources/config automatically if the extension/bundle class does not specify else, so that even less code is required. But this is better discussed in a separate issue)

WDYT?

**Comment by iltar** [comment]
Isn't this very easily done by implementing the `ExtensionInterface`? You'd have to change some guessing on the Extension class (because you can just return `$this` instead)

**Comment by umulmrum** [comment]
Of course I could do this in my code - the downside is that I'd have to use custom code for every bundle, and move away from the Symfony standards and documentation, including the bundle best practices. I'd therefore prefer a canonical solution.

**Comment by jvasseur** [comment]
One downside would be that the extension code would be loaded on every request instead of only when building the container. For big extensions class like the FrameworkBundle this could lead to some measurable difference in performances.

**Comment by nicolas-grekas** [comment]
Good catch, that is a significant downside: the bundle class is a run-time thing that directs to compile-time extras. Compile-time things should really be *not* loaded on every request. For this reason, the current design looks like the best practice we should keep IMHO.

**Comment by umulmrum** [comment]
Didn't think of that indeed. But is the difference really measurable if it is code that is loaded but not executed on every request? With PHP7 and OpCache I'd think this can be neglected (but am of course interested in numbers if you happen to have some).

**Comment by GuilhemN** [comment]
For the record, I opened a PR in the past for something similar https://github.com/symfony/symfony/pull/19596 but it was rejected.

**Comment by umulmrum** [comment]
OK, thank you all for the comments - I think we can close this issue.

Nonetheless the extension system is one of the very few things I don't really like about Symfony and would therefore appreciate simplification in one way or another in the future (as pointed out in the opening post).
