### ISSUE TITLE
[DomCrawler] Add a way to filter only direct children nodes

### ISSUE THREAD

**Issue by Einenlum** [symfony/symfony#28171]
**Description**  

In jQuery, there is the `.find()` method and the `.children([selector])` method. Its documentation [states that](https://api.jquery.com/children/) :

> The .children() method differs from .find() in that .children() only travels a single level down the DOM tree while .find() can traverse down multiple levels to select descendant elements (grandchildren, etc.) as well.

The Dom-Crawler component only has a `filter()` method (to filter the node and all its children) and a `children()` method to return direct children. There is no way to easily filter (thanks to a selector) the direct children of a node.

I think it could be nice to add an optional `$selector` parameter to the `children()` method, to allow to filter direct children, as jQuery allows to.

**Example**  

Considering this example:

```php
$html = <<<'HTML'
<html>
    <body>
        <div id="foo">
            <p class="lorem" id="p1">ipsum</p>
            <p class="lorem" id="p2">era</p>
            <div id="nested">
                <p class="lorem" id="p3">amenos</p>
            </div>
        </div>
    </body>
</html>
HTML;

$crawler = new Crawler($html);
$foo = $crawler->filter('#foo');
```

Currently, there is no way (or am I missing something?) to only return `#p1` and `#p2` starting from the `$foo` variable.

`$foo->filter('.lorem')` returns `#p1`, `#p2` and `#p3`.
`$foo->children()` returns `#p1`, `#p2` and `#nested`.

Adding this new feature would allow `$foo->children('.lorem')` to return `#p1` and `#p2`.
Also, since it would be an optional parameter, it would not break BC.

**Comment by xabbuh** [comment]
`filter()` uses CSS selectors. So doesn't something like `div#foo > p.lorem` work?

**Comment by Einenlum** [comment]
@xabbuh, thanks for your answer.

Sorry, maybe I should have emphasized on this part: there is no way currently to only return `#p1` and `#p2` **from the $foo variable**.

I'm currently working on a project where a crawler is made of multiple different crawlers, all taking care of a small part of the DOM. They only receive the element directly (the `$foo` element in this example).
These small crawlers could access the parent and try somehow to use a selector that is only selecting the `$foo` element in the parent but that would somehow hazardous (here it's an id, but what if my $foo element is part of a few `.some-class` siblings?) and kind of a break of responsibility.

So to keep the example above, I'm in the situation where I have a class with a method like : 

```php
public function getLorems(Crawler $fooElement): array
{
    // … ?
}
```

I think it would save a lot of effort and bad risky code to add this way of filtering direct children.

**Comment by javiereguiluz** [comment]
@Einenlum have you tried what @xabbuh suggested and it doesn't work? `$foo->filter('> .lorem')` ?

**Comment by Einenlum** [comment]
@javiereguiluz yes. It's not a valid selector, according to the CssSelector component.

`Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected selector, but <delimiter ">" at 0> found.`

**Comment by juanmiguelbesada** [comment]
Hi,

Well technically `> .lorem` it's not a valid CSS Selector. But maybe we can find a way to handle  this use case.

BTW, as a workaround you maybe you could use `$foo->filterXpath("/*[@class='lorem']")`

**Comment by Einenlum** [comment]
@juanmiguelbesada It seems it does not work either.

```php
$foo->filter('.lorem')->count() // 3
$foo->children()->filter('.lorem')->count() // 3
$foo->filterXpath("/*[@class='lorem']")->count() // 0
```

**Comment by xabbuh** [comment]
@Einenlum `$foo->filterXPath('child::*/p[@class="lorem"]')` would work, for example.

**Comment by Einenlum** [comment]
@xabbuh Thanks! Your example seems to work :).

So actually we could easily do something like : 

```php
    /**
     * Returns the children nodes of the current selection.
     *
     * @param $selector string|null A option CSS selector to filter children
     *
     * @return self
     *
     * @throws \InvalidArgumentException When current node is empty
     */
    public function children($selector = null)
    {
        if (!$this->nodes) {
            throw new \InvalidArgumentException('The current node list is empty.');
        }

        if ($selector) {
            if (!class_exists(CssSelectorConverter::class)) {
                throw new \RuntimeException('To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead.');
            }

            $converter = new CssSelectorConverter($this->isHtml);
            $xpath = $converter->toXPath($selector, 'child::*/');

            return $this->filterXPath($xpath);
        }

        $node = $this->getNode(0)->firstChild;

        return $this->createSubCrawler($node ? $this->sibling($node) : array());
    }
```

```php
    $foo->children()->count() // 3
    $foo->children('.lorem')->count() // 2
```

Obviously this needs to be tested cause I'm bad at Xpath, but if it works, I think it could be really nice for the end users.
