### ISSUE TITLE
Failed opening required container cache file, when using form system

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#28180]
**Symfony version(s) affected**: master branch

**Description**  
When trying to create *any* form type, a strange container require failure occurs:

<img width="1056" alt="screen shot 2018-08-09 at 12 16 13 pm" src="https://user-images.githubusercontent.com/121003/43911749-39ea63ce-9bce-11e8-916e-5f77366834e3.png">

**How to reproduce**  

I have a small app that reproduces it here: https://github.com/weaverryan/bug-symfony-container-reproducer

Just start the built-in web server and go to `/` to see the error.

To create the reproducer app, I:

1) Created a symfony/skeleton project from dev-master
2) Installed symfony/form (dev-master)
3) Try to create a form in a controller: https://github.com/weaverryan/bug-symfony-container-reproducer/blob/master/src/Controller/ContainerTestController.php#L12

If you have any questions, please let me know! I don't think I'm doing anything funny to cause it, but you never can be sure ;).

Cheers!

**Comment by dmaicher** [comment]
@nicolas-grekas I think this might be related to https://github.com/symfony/symfony/pull/27783

I tried debugging it a bit and for the service `App\SomeFormType` this condition here is false:

https://github.com/symfony/symfony/pull/27783/files#diff-f7b23d463cba27ac5e4cb677f2be7623R841

Can it be a problem with the order in which the services are dumped? Seems like service locators must be dumped/processed first so `$this->locatedIds` is properly filled with all service ids?

**Comment by nicolas-grekas** [comment]
Yep, ordering issue, see #28182

**Comment by weaverryan** [comment]
You guys are the best ❤️
