### ISSUE TITLE
2.8: dependency-injection component needs config, but does not install it

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#28185]
**Symfony version(s) affected**: 2.8.0

**Description**  
I've tried to add the most minimal way to add symfony/dependency-injection support to my deserializer library. https://github.com/chubbyphp/chubbyphp-deserialization/pull/20/files as you can see this works as expected with 4.x but not back to 2.8.0, cause there it depends on symfony/config, which get not installed: https://travis-ci.org/chubbyphp/chubbyphp-deserialization/builds/414380664

For me this seems to be a bug in composer.json of the dependency-injection component back then.

**Comment by nicolas-grekas** [comment]
That's consistent with the way we declare dependencies in Symfony: deps of optional features aren't listed in "require". Here, Config is needed for two main features: loaders and resource tracking. Unless one use these features, one doesn't need Config. Which means adding symfony/config is on you if your lib use these features.
I'm closing therefor, thanks for the report (if I missed anything, please tell of course.)

**Comment by dominikzogg** [comment]
@nicolas-grekas its not me using the config, it's implicitly used. If i would use it directly fair enough (for example providing a command and need symfony/console if I wanna use it), but this way the usage is done behind the scenes which makes dependencies very hard to maintain

**Comment by nicolas-grekas** [comment]
There are some exceptions in the DI code base that hint when Config is needed by missing.
E.g. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php#L183

We could add more in places where this is needed I suppose. PR welcome.
