### ISSUE TITLE
Changes made in the View Transformer are not propagated to children

### ISSUE THREAD

**Issue by felds** [symfony/symfony#28184]
**Symfony version(s) affected**: 4.1.3

**Description**  
When using a View Transformer to turn the form data into my domain representation, the form doesn't change on the subsequent request.

**How to reproduce**  
Clone, `composer install` and `bin/console server:run` this repo:  
https://github.com/felds/view-transform-bug-reproducer

**Additional context**  
In the example/reproducer, the User model only turns the name all caps. However, this change is not reflected when displaying the submitted form.

![image](https://user-images.githubusercontent.com/139979/43929065-b8232380-9c09-11e8-99f2-58fd6be84b4d.png)

**Comment by xabbuh** [comment]
This is the expected behaviour. The form inputs will be populated again with the data the user submitted.  I am closing here as there is nothing to fix.
