### ISSUE TITLE
[Debug] Use dump function without parameters throw an Exception

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#28189]
**Symfony version(s) affected**: 4.1.3

**Description**  
Using the debug `{% dump() %}` throw an Exception when `{{ dump() }}` not. Use `{% dump %}` without `()` works as expected but the error message when you use `{% dump() %}` is ambigous.  

![image](https://user-images.githubusercontent.com/13260307/43967852-c3568082-9cc5-11e8-808c-e0a7bc152a34.png)

![image](https://user-images.githubusercontent.com/13260307/43967880-dba37ffa-9cc5-11e8-95ef-4eccc70f5106.png)

**How to reproduce**  
inside a twig template, call `{% dump() %}` then `{{ dump() }}`

**Possible Solution**  
Don't throw the Exception and render the debug result in the profiler or provide abetter error message

**Comment by xabbuh** [comment]
What is the exact exception and the corresponding stack trace that you get?

**Comment by ismail1432** [comment]
I updated the description with screen shot, feel free if you need others information :-)

**Comment by xabbuh** [comment]
Ah, I see that you have also updated the description. I am afraid there's not much we can do in Symfony since this is a Twig syntax error. And I am even not sure that Twig could provide a better error message here.

**Comment by weaverryan** [comment]
It is technically in our code: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/TokenParser/DumpTokenParser.php

We could, in theory, make this syntax valid (but yea, we couldn't improve the message I don't think). I'm not sure if it's valuable or not - I don't use the `{%` version ever, and it looks like it doesn't normally even use `()` - https://github.com/symfony/symfony/blob/f96753b9ab497a42f7a76188e2de4911b50f5407/src/Symfony/Bridge/Twig/TokenParser/DumpTokenParser.php#L25

**Comment by fabpot** [comment]
This is indeed a wrong usage of the tag. Error message is probably not the best, but nothing we can improve as this comes from the parser, which is generic.
