### ISSUE TITLE
symfony/form DateTimeType label=false doesn't work

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#28198]
**Symfony version(s) affected**: 3.4 (not tested on 4.x)

**Description**  
DateTimeType doe not take into account `label` configuration : 
- if defined to `false`, labels are showned
- if defined to `foo`, `Year` `Month` `Day` `Hour` `Minute` are showned

Maybe `DateType` and `TimeType` have same behavior.

**How to reproduce**  
```php
public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder->add(
        'date',
        DateTimeType::class,
        [
            'label' => false,
            'translation_domain' => false
        ]
    );
}
```

**Possible Solution**  
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L111
Fill $yearOptions, $monthOptions and $dayOptions with our `label` configuration, instead of just `required` and `translation_domain`

**Additional context**  
No additional context

**Comment by xabbuh** [comment]
@steevanb Can you create a small example project that allows to reproduce your issue? I was not able to reproduce:

<img width="721" alt="bildschirmfoto 2018-09-14 um 08 46 39" src="https://user-images.githubusercontent.com/1957048/45534232-c3d4a480-b7fa-11e8-90e7-e8e4b24948b7.png">

**Comment by steevanb** [comment]
Just show generated source code, and you will see label is "hidden" by inputs. Not showned, but written and hidden.

**Comment by xabbuh** [comment]
Hm indeed, for the Boostraph form theme that's true. But is that really an issue if the labels are not shown anyway?
