### ISSUE TITLE
container.dumper.inline_class_loader with self-referencing constants throws errors

### ISSUE THREAD

**Issue by Destroy666x** [symfony/symfony#28205]
**Symfony version(s) affected**: 3.4.14, probably all with the parameter

**Description**  
If you enable the `container.dumper.inline_class_loader` parameter and have a constant that refers to itself in an abstract class and is overriden in child classes, you get `Cannot declare self-referencing constant.` errors everywhere while normally PHP and Symfony allows such behavior. 

**How to reproduce**  
1. Enable the `container.dumper.inline_class_loader` parameter.
2. Have code like:
```php
abstract class SomeAbstractCommand extends Command
{
    const COMMAND_NAME = self::COMMAND_NAME;

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        parent::configure();

        $this->setName($this::COMMAND_NAME);
    }
}
```

```php
class SomeCommand extends SomeAbstractCommand
{
    const COMMAND_NAME = 'some:command';
}
```
3. Run cache clear command or whatever.

**Possible Solution**  
I haven't had time to analyze the code, but I assume there's some static analysis/data collection that fails because the same problem exists in PHPStan too. I know that switching to a property + getter is a solution, but IMO a "hack" for enforcing constants in child classes supported by PHP should be supported here too, if possible.

**Comment by apfelbox** [comment]
Why don't you just use `static:: COMMAND_NAME`?

**Comment by Destroy666x** [comment]
I don't remember exactly, I think I had some issues with it in PHP 7.0. But I upgraded to 7.2 after that so I guess I should retry.

**Comment by stof** [comment]
`const COMMAND_NAME = self::COMMAND_NAME;` ? WTF is that ? What would be the value of the constant here, as it refers to itself to get the value ? Is it even valid code ?

**Comment by Destroy666x** [comment]
As I mentioned - yes, even though it's weird. In runtime PHP gets the constant from the child class if it's defined there.

**Comment by apfelbox** [comment]
Hm, I'm not sure whether this is true, as `self` is not evaluated in runtime time, but in compile time.

**Comment by iltar** [comment]
It works because you grab the instance. If you reference the constant directly, it won't work. https://3v4l.org/X8POm

**Comment by apfelbox** [comment]
Yeah, I just tested it myself. Self-referencing constants never work in PHP, but only throw on access and not on definition.

But the constant in `SomeAbstractCommand` is never really accessed, as you only ever access the children.

So as soon as you add `SomeAbstractCommand::COMMAND_NAME` in the code it will break.

**Comment by Tobion** [comment]
I've never seen code like `const COMMAND_NAME = self::COMMAND_NAME` before. I also don't see the point of it. Just define some default value and overwrite it in the child. No need to make a self-referencing constant. Also you can just use `static:: COMMAND_NAME`: https://3v4l.org/QJls8

**Comment by Destroy666x** [comment]
> Just define some default value and overwrite it in the child.

That's not an equal solution because that doesn't enforce defining the constant in children.

But yeah, `static` seems to work correctly now in that context so I'll definitely switch to that.

>  I just sent an email to the PHP internals mailing list (not sure whether it will be posted because of issues with the mailing list) about this topic.

Yup, it's kind of confusing and probably shouldn't be allowed. What would be nice to see instead is just something like `abstract const SOMETHING;` - it would make it obvious that a constant needs to be defined in a child, `static` doesn't until you run into an error or find its usage.

**Comment by stof** [comment]
Well, any code accessing `SomeAbstractCommand::COMMAND_NAME` will fail because your constant definition is invalid. And I think this includes any code using `(new ReflectionClass(SomeAbstractCommand::class))->getConstants()`. Making your class incompatible with Reflection is not something I would expect Symfony to support (and it is probably also the reason why PHPStan fails btw)

**Comment by Destroy666x** [comment]
Sure, closing this then.
