### ISSUE TITLE
[Process] Option to disable handling signals allowing custom signal handling.

### ISSUE THREAD

**Issue by poppabear8883** [symfony/symfony#28204]
**Description**  
A option to disable handling signals allowing custom signal handling.

**Example**  
```php
$process->setSignalHandler(SIGINT, $this->sigIntHandler);
```
**OR**

```php
$process->handleSignals(false);
```

**The Concept**
So the idea is if a user presses `CTRL + c` it will NOT interrupt the Symfony Process but rather defer to a custom handler.

Example:
```php
public function __construct() 
{
    pcntl_signal(SIGINT, [$this, 'sigIntHandler']);
}

protected function command($command) 
{
    $process = new SymfonyProcess($command);
    $process->handleSignals(false);
    $process->start();

 ...

    $process->wait(function ($type, $buffer) use ($bar) {
        // ... DO STUFF

        $bar->advance();
        usleep(200000);
    });

    // we wait until the current process finishes and then dispatch any signals
    pcntl_signal_dispatch();
}

protected function sigIntHandler()
{
    if ($this->io->confirm('Are you sure you want to abort', false)) {
        die();
    }
}
```

**Comment by poppabear8883** [comment]
Please forgive me as I might not have a clue, However the Process component `Process.php` is full of signal handling ? 

What am I missing ?

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L17
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L97
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L226
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L298
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L425
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L443
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L727
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L743
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L764
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L780
`I could go on but i think this is enough, again maybe i have no idea what i am talking about.`

All i know is that i had tried to register a signal handler manually and but yet the child process was still terminated ...

**Comment by nicolas-grekas** [comment]
What I meant is that the process component doesn't call any `pcntl_*()` function. It just ensures that subprocesses receive signals as they should by default.

**Comment by poppabear8883** [comment]
Ok, again i'm not really sure what to say .. 

I have tried something to the same effect of:

```php
public function __construct() 
{
    pcntl_signal(SIGINT, [$this, 'sigIntHandler']);
}

protected function command($command) 
{
    $process = new SymfonyProcess($command);
    $process->start();

 ...

    $process->wait(function ($type, $buffer) use ($bar) {
       // ... DO STUFF

       // ... I believe the signal is getting through here to kill the 
       // sub-process before i dispatch it to a custom handler

       $bar->advance();
       usleep(200000);
    });

    // wait until the current process finishes and then dispatch any signals
    pcntl_signal_dispatch();
}

protected function sigIntHandler()
{
    // This gets called, but the sub-process is terminated immediately before a confirmation is received.

    if ($this->io->confirm('Are you sure you want to abort', false)) {
        die();
    }
}
```

I feel like by default as you stated this is the expected behavior, what i am proposing is a why to bypass /defer all signal handling in the Process component to allow for a more robust and custom solution.

**Comment by nicolas-grekas** [comment]
You mean: this works, isn't it? This snippet allows doing what you need?
I'm not sure we can provide something like that in core, because signal handling requires the pcntl extension, which is optional, and not available on Windows. The component is about portability...

**Comment by poppabear8883** [comment]
No, the snippet i provided does not work as expected as noted in my comments in the code snippet.

**Comment by nicolas-grekas** [comment]
Looking at articles like https://stackoverflow.com/questions/3232613/how-to-stop-sigint-being-passed-to-subprocess-in-python, I think this is by design in the Unix world: subprocesses receive the signals also. Decoupling is possible but cannot be done easily and in a portable way. At least I can't think of any idea that would allow doing so without resorting to obscure shell tricks, if possible at all.
If confirmed, we should close this RFC as "can't implement". Feel free to prove me wrong, that'd be great :)

**Comment by poppabear8883** [comment]
While I believe this is something that can be done and done cleanly, I personally do not have to to do the research and submit a proposal in the form of a PR. With that said I will close this issue until someone else feels like it should be reopened with the notion they should have something to propose.

Thanks for taking a look into this, it would be a nice feature to add and if I find the time I will revisit this issue.

However, I don't think `can't implement` is the right label as I feel like the research isn't there to say so with certainty ...

**Comment by perk11** [comment]
This appears to be possible: https://stackoverflow.com/questions/72850442/php-prevent-sigterm-to-bubble-to-proc-open-process

**Comment by perk11** [comment]
I also tested it with Symfony Process, and the following user code does the job:

```php
$process = new Process(['sleep', '10m']);
pcntl_signal(SIGTERM, SIG_IGN, false);
$process->start();
pcntl_signal(SIGTERM, function(){ echo 'test'; }, false);
while ($process->isRunning()) {
            pcntl_signal_dispatch();
            usleep(100_000);
            pcntl_signal_dispatch(); // Calling second time for faster feedback, 1 time should be sufficient.
}
```

When the parent receives SIGTERM, the child process does not receive it and "test" is outputed in the terminal.
