### ISSUE TITLE
create symfony4 Service with params 

### ISSUE THREAD

**Issue by valdanioDanio** [symfony/symfony#28201]
This my service code:

    twig.extension:
          # Register the class (The namespace must match)
        class: App\Extensao\TwigExtensions
        # Inject doctrine as first parameter
        arguments: 
            doctrine : '@doctrine'
        tags:
          -  { name: twig.extension }

And this is the error:
 InvalidArgumentException
Invalid service "twig.extension": method "App\Extensao\TwigExtensions::__construct()" has no argument type-hinted as "doctrine". Check your service definition.

**Comment by nicolas-grekas** [comment]
If you want to target a parameter by name, you have to prefix it with a `$`: `$doctrine`.
Closing as we use github only for bugs/features. See http://symfony.com/support if you have more questions.
