### ISSUE TITLE
Symfony Bootstrap4 - Form named FileType tries to render Entity

### ISSUE THREAD

**Issue by StanJansen** [symfony/symfony#28217]
**Symfony version(s) affected**: 4.1.3

**Description**  
Since 4.1.3 (Probably caused by [#26502](https://github.com/symfony/symfony/pull/26502/commits) or [#27919](https://github.com/symfony/symfony/pull/27919/commits/32ad5d9f9cdbc8f175953981ba7df08caf2c07b1), my form named FileType gives the error "App\Entity\File could not be converted to string".
Most likely caused by the rendering for the field type changing from the twig block file_row to file_widget.

**How to reproduce**  
Create a form builder with the class name FileType, and it'll give you the error.

**Possible Solution**  
Revert changes to the file_widget block, keep it in the file_row block.

**Comment by xabbuh** [comment]
If you have a custom FormType that is named the same as a built-in type, you should always implement the `getBlockPrefix()` method to avoid these issues.

**Comment by StanJansen** [comment]
Forgot to add that that initially indeed as it didn't give an error before, thanks :)

Perhaps it would be useful to add a compound check? I'd reckon that more people have this exact same issue, plus it's not the easiest error to debug.

**Comment by xabbuh** [comment]
I am closing here as there is nothing to fix. Of course, if someone has an idea how to improve DX here, I will happily review an code or documentation PR.
