### ISSUE TITLE
i want environment folder ,predefined some  configured params , use command php init can generate paramters  for different environment,yii2 has this feature

### ISSUE THREAD

**Issue by wukchao** [symfony/symfony#28213]
**Description**  
i want environment folder ,predefined some  configured params , use command php init and choice env can generate paramters  for different environment,
**Example**  
yii2 has this feature

**Comment by xabbuh** [comment]
I think I do not understand what you would like to see. Can you explain your idea in more depth?

**Comment by xabbuh** [comment]
I am closing here for now as it is not clear what the goal of this feature request is. But please feel free to update your description with more details an we can consider to reopen.
