### ISSUE TITLE
[Translation] Allow for a default domain to be set for the Translation component.

### ISSUE THREAD

**Issue by Mvannes** [symfony/symfony#28239]
**Description**  
Currently, the translation component sets the `messages` domain as the default domain.
It would be preferable to allow this default domain to be set through constructors / setters. This would also allow the translation component to be more easily extendable and configurable.

**Example**  
Taken from the `Translator`
The current implementation of the `trans` function looks as follows: 
```
public function trans($id, array $parameters = array(), $domain = null, $locale = null)
{
    if (null === $domain) {
        $domain = 'messages';
    }

    return $this->formatter->format($this->getCatalogue($locale)->get((string) $id, $domain), $locale, 
$parameters);
}
```
The `'messages'` string is hardcoded into the functions where a domain is optional but will still be required.

My proposal is to change these functions throughout the component to look as follows: 
```
public function trans($id, array $parameters = array(), $domain = null, $locale = null)
{
    if (null === $domain) {
        $domain = $this->default_domain;
    }

    return $this->formatter->format($this->getCatalogue($locale)->get((string) $id, $domain), $locale, 
$parameters);
}
```

By adding the default domain as a class variable, and injecting it through the constructor or through a setter, the translator becomes much more configurable.
An added bonus will be the removal of hardcoded strings, which really aren't that clear.

Another example, where the hardcoded strings are much clearer can be found in the `MetadataAwareInterface`, which looks like this: (docs removed for clarity)
```
interface MetadataAwareInterface
{
    public function getMetadata($key = '', $domain = 'messages');
    public function setMetadata($key, $value, $domain = 'messages');
    public function deleteMetadata($key = '', $domain = 'messages');
}
```
With the proposed change, the interface will instead look as follows:
```
interface MetadataAwareInterface
{
    public function getMetadata($key = '', $domain = null);
    public function setMetadata($key, $value, $domain = null);
    public function deleteMetadata($key = '', $domain = null);
}
```

**Comment by sstok** [comment]
Changing this on a global scale would mean that every method call now needs to pass the domain.

Currently every method knows that the default domain is "messages", but if you change this is, it's no longer predictable. Even if your own application always uses a same custom one it's still possible this is overwritten somewhere (especially when you use a getter).

If you need this for your own application you can create a custom implementation that wraps around the actual translator and then in the `trans()` method you check if the domain is passed, and use your custom domain otherwise.

```php
public function trans($id, array $parameters = array(), $domain = null, $locale = null)
{
   return $this->translator->trans($id, $parameters, $domain ?? $this->defaultDomain, $locale);
}
```

FYI. The `messages` domain is used in almost all I18n (Internationalization and localization) systems, and therefor Symfony adapted this practice.

**Comment by Mvannes** [comment]
I'm not sure that I see how changing this on a global scale means that every method needs to pass the domain. Surely this is no different from anyone passing a non-default domain right now? 
The `messages` domain should still be the default of course, as this is indeed the standard. 

Wrapping the translator is exactly what I have done now, but it seems wrong to have these strings as hardcoded defaults throughout the component instead of configuring the default in a central location. 
By configuring them in a central location every method would still know that the default domain is `messages` no?

I'm sure I'm missing something here, but it seems to me that while this would be a major change to the component's internals, it would be a much smaller change for anything that uses this component.

**Comment by nicolas-grekas** [comment]
Every existing places that don't provide the domain could suddenly use a different domain, that's what @sstok means I suppose. There need to be a default, so hardcoding one is not bad to me as it allows some standardization. Technically, changing the default value of the domain in the interfaces would be a BC break. Which means we would need a new interface to do this. Really not sure it's worth it IMHO.

**Comment by xabbuh** [comment]
I agree with @nicolas-grekas here. And since creating your own translator decorating the core one but using `null` as the default value can easily be done I suggest to not do this in core as that's IMO too much hassle for everyone without much gain.

**Comment by nicolas-grekas** [comment]
Closing as discussed, thanks for submitting.
