### ISSUE TITLE
Form gets false render with custom PasswordType as form class

### ISSUE THREAD

**Issue by TuxCoder** [symfony/symfony#28235]
**Symfony version(s) affected**: 3.4.14

**Description**  
Twig renders Form false if the Form class is `PasswordType`, but different namespace.

Here the fix for my project:
https://github.com/LenticularCloud/Cloud-Ldap-Admin/commit/8b837bcda17ca3ff677784efadf8d55aecf1fcfa

**How to reproduce**  
I created a example project for reproduce because my project has LDAP server as dependency.

https://github.com/TuxCoder/symfony_bug

**Possible Solution**  
Currently I have the workaround of renaming, but probably other people run into the same issue.

**Additional context**  
On my project I also get a exception because of this:
https://pastebin.com/r4uJjUFK
But I think with the example project it is nicer to debug.

From the example project:
This is two times the exact same code, only other naming.
The first type is called `PasswordType` the secound `RightPasswordType`.
See the additional input in the first form.

![image](https://user-images.githubusercontent.com/2470864/44399436-de8f6280-a547-11e8-9f44-510792656dd6.png)

**Comment by TuxCoder** [comment]
oh oversee there is also the same error in issue #28217

**Comment by xabbuh** [comment]
@TuxCoder In 2.8, `getBlockPrefix()` defaulted to `getName()`: https://github.com/symfony/symfony/blob/0332f861c6fb7493def8d8d36f7dc6a15d2f58ac/src/Symfony/Component/Form/AbstractType.php#L82-L89

**Comment by TuxCoder** [comment]
@xabbuh  Yes, and `getName` is a abstract function, and has be implemented by the developer. So this error is much transparent and less likley.
