### ISSUE TITLE
BinaryFileResponse doesn't work unless prepare is called

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#28237]
**Symfony version(s) affected**: 3.4.14

**Description**  

I'm using the **HttpFoundation** component to stream binary files. I'm using the basic snipped underneath which produces no output. The reason for this is [this line](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L303).

`stream_copy_to_stream` has the following signature:

```php
int stream_copy_to_stream(resource $source, resource $dest[, int $maxlength = -1[, int $offset = 0]])
```

The `maxlen` and `offset` properties are only actually ever set in the `prepare` method. Thus Symfony passes `null` to both of these parameters unless `prepared` is called. PHP will not do anything if these properties are null:

https://3v4l.org/MtBl7

**How to reproduce**  

```php
$response = new BinaryFileResponse($filepath);
$response->send();
```

**Possible Solution**  

The solution is to call `prepare` on the response. The docs do mention the `prepare` method but don't say that it's mandatory.

```php
$response = new BinaryFileResponse($filepath);
$response->prepare(Request::createFromGlobals());
$response->send();
```

Symfony should either:

* Be clearer in the documentation that `prepare` is necessary
* Throw an error when `maxlength` or `offset` are null
* Default to `-1` and `0` as the default values

**Comment by wackymole** [comment]
But the HttpFoundation component docs [does mention `prepare()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/ResponseListener.php#L47) a little further up the page.

**Comment by iluuu1994** [comment]
@wackymole When using the Symfony kernel Symfony will always calls `prepare` on the response under the hood.:

https://github.com/symfony/symfony/blob/4e4b21668a9594ddcbbd67f2be55f733178dde28/src/Symfony/Component/HttpKernel/EventListener/ResponseListener.php#L47

I'm using the `BinaryFileResponse` in a non Symfony project. Try just the `send` but without `prepare`.

**Comment by wackymole** [comment]
I did, and I do see your error in that case.

**Comment by iluuu1994** [comment]
@wackymole Ok 👍 The docs do not mention that `prepare` needs to be called. That would be a valid solution to this issue.

**Comment by wackymole** [comment]
Well, it wasn't the error you mentioned. This works.
```php
$response = new BinaryFileResponse(__DIR__.'/Test.txt');
$response->setContentDisposition(
    ResponseHeaderBag::DISPOSITION_ATTACHMENT,
    'filename.txt'
);
$response->send();
```

**Comment by iluuu1994** [comment]
@wackymole Can you try it completely without a Symfony kernel? In a standalone `.php` file with nothing but the lines from the previous comment?

**Comment by wackymole** [comment]
[Sure can](https://github.com/wackymole/http-foundation-test). This was created as a single `index.php` and a `test.txt` with the only dependency being `symfony/http-foundation@3.4.14`. Setting the content disposition makes it a download rather than open in browser (at least in Chrome). I guess the alternative is to call `prepare()`.

P.S. Do you know how many `hello (x).txt` files I have in my downloads directory now?

**Comment by iluuu1994** [comment]
@wackymole 

> P.S. Do you know how many hello (x).txt files I have in my downloads directory now?

😂

I can reproduce my problem with your example. The file is downloaded (as the content disposition header is set correctly) but the file is empty because `stream_copy_to_stream` doesn't work when the 3rd and 4th parameters are `null`.

**Comment by wackymole** [comment]
Yeah, I noticed that after I commented. Something in `prepare()` sets those two values based on request headers. Perhaps those properties should have default values.
