### ISSUE TITLE
[Validator] Strict mode for BIC and IBAN

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#28232]
**Description**  
BIC and IBAN validators both accept values with spaces that are removed before validation.
IBAN validator accepts values with lower case that are upper-ed before validation, but BIC validator refuses lower case values.

Theses validators should have a consistent behavior on case.

And I'm wondering why these validators accept spaces as it's a display feature.

A solution is to create a strict mode that rejects values with spaces and lower case.
Default value would be false for BC and can be set to true on a major update.

I can provide a PR with unit tests if you want.

**Comment by nicolas-grekas** [comment]
UX wise, why would this be better? I get that it would make devs' life easier, but isn't it the user more important here, following the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle)?

**Comment by sylfabre** [comment]
@nicolas-grekas I understand the UX-goal of this tolerance and we try to always implement this robustness principle in my company (like accepting emails with space and removing them before validation).

But the issue here is about consistance among all validators: why a lower-case IBAN should be valid when a lower-case BIC is invalid? Why a space-formatted IBAN should be valid when a non-breakable-space-formatted IBAN is invalid?

In my own opinion, a validator should be as strict as possible and you may call beforehand a sanitizer to clean the data:
- validator behavior is strict so no unexpected accepted value
- UX is good as you are liberal in what you accept
- data in internal code is in a conservative format which is always a good practice

This may come as an independent component to be used along forms and validators like having a XXXConstraint, a XXXSanitizer and a XXXValidator

**Comment by nicolas-grekas** [comment]
> This may come as a generic "strict" option:

I think we should consider such a plan:  I think we should make a clear distinction when the validator is in "strict" vs "filtering" mode. That should be a concept that applies to almost all validators. (strict meaning the input is exactly the same as the output, after normalization.)

Would you like to open an RFC for this?

**Comment by sylfabre** [comment]
@nicolas-grekas Yes I can open an RFC. How should I do that please?
