### ISSUE TITLE
Laravel Nova for Symfony

### ISSUE THREAD

**Issue by guice12** [symfony/symfony#28242]
Hi,
Since today, Laravel has released Nova : a beautifully designed administration panel https://nova.laravel.com. I tried Easyadminbundle but it's limited. It was interesting to have the same idea of Nova for Symfony.
Thanks.

**Comment by ricknox** [comment]
Hello! 👋

> [..] It was interesting [..]

Do you mean that you have an opinion or suggestion? Maybe you can discuss [this here](https://github.com/EasyCorp/EasyAdminBundle/issues) since it falls outside of this repository.

Thank you.

**Comment by theofidry** [comment]
You also have [Sonata](https://sonata-project.org/) as well as [API Platform](https://api-platform.com/) - see the front-end admin generator which unlike Nova are open source :)

**Comment by ostrolucky** [comment]
There is also new kid on a road - https://github.com/rmznpydn/pd-admin didn't try it personally, though

**Comment by stof** [comment]
Nova seems to rely on a CRUD API and a SPA frontend for the admin. that's exactly what API platform is doing for their admin generator.

**Comment by alanpoulain** [comment]
More precisely, https://github.com/api-platform/admin is an admin SPA based on https://github.com/marmelab/react-admin.
This SPA consumes the documented Hydra API (provided by API Platform or not).

**Comment by nicolas-grekas** [comment]
I'm closing here as symfony/symfony contains only standalone components and "features" are usually provided by bundle - also because the main existing bundles have been listed.
