### ISSUE TITLE
Unique Entity Assert not calling __toString() method when displaying custom message

### ISSUE THREAD

**Issue by deivid11** [symfony/symfony#28245]
**Symfony version(s) affected**: 4.1.0

**Description**  
According to the [documentation](https://symfony.com/doc/master/reference/constraints/UniqueEntity.html#message)  you can use {{ value }} in message option to display a string representation of the invalid entity using the __toString  method of the entity class.
I have implemented the __toString method but I'm getting this kind of message "Object of class __CLASS__ identified by <comma separated IDs>"

**Possible Solution**  
I have checked this [code](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php ) but I can't figure out where is the __toString method called. It can be fixed checking if the entity class is implementing __toString before adding the default message.

**Comment by xabbuh** [comment]
The way that is described in the documentation was implemented in #19227 and broke with #21288.

@dmaicher @HeahDude Can you take a look here and see if that is intended (and we should update the documentation) or if the `__toString()` case was not considered enough in #21288?

**Comment by dmaicher** [comment]
@xabbuh @deivid11 I will check this today after work. Maybe we forgot to handle a case there :confused:

**Comment by HeahDude** [comment]
It seems I've proposed some changes thinking it would be better like this, not being aware of the way it was documented. We could use the `__toString()` as before at first, and then the change introduced as a fallback.

**Comment by HeahDude** [comment]
see https://github.com/dmaicher/symfony/pull/1

**Comment by dmaicher** [comment]
@deivid11 I added a failing test case here

https://github.com/symfony/symfony/compare/master...dmaicher:issue-28245?expand=1#diff-dfcd983a70bb5aef9ec9946a2080ced5R812

```
There was 1 failure:

1) Symfony\Bridge\Doctrine\Tests\Validator\Constraints\UniqueEntityValidatorTest::testValidateUniquenessWithAssociationToStringEntity
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Symfony\Component\Validator\ConstraintViolation Object (
     'message' => null
     'messageTemplate' => 'myMessage'
     'parameters' => Array (
-        '{{ value }}' => 'foo'
+        '{{ value }}' => 'object("Symfony\Bridge\Doctrine\Tests\Fixtures\SingleStringIdEntity") identified by (id => "1")'

/var/www/symfony/src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php:322
/var/www/symfony/src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:835
```

Is this the problem you are having? So a related entity on the entity you are validating is not unique?

**Comment by deivid11** [comment]
@dmaicher yes, that is the use case and it is the fix I was looking for. Thank you!
