### ISSUE TITLE
[Cache] create RedisTagAwareAdapter to reduce roundtrips

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#28250]
Thanks to Lua scripting capabilities of Redis, we should be able to implement the tag invalidation logic in Redis itself:

On data **read**, Redis would return the item *if* its tag versions are up to date. If not Redis would prune the item+its tags. The write + invalidation logic should remain basically the same. We could also implement `PruneableInterface` on this adapter.

I think this would make Redis the most efficient backend for tagged items.
A similar strategy could also work for a `PdoTagAwareAdapter` btw.

See https://redis.io/commands/eval

**Comment by wucdbm** [comment]
Hey there.

This sounds like a great idea, and I'd be interested in some benchmarks against the TagAwareAdapter using redis for both data and tags once this is ready.

However, I am currently wondering about the following use-case:

1. Redis adapter using DB 0 storing data related one domain
2. Redis adapter using DB 1 storing data related to another domain
3. Redis adapter for TAGS using DB 2 and stores common tags shared between 1. and 2.
That is, TagAwareAdapter for 1. and 2. both use Redis Adapter 3. for tags.

Where we do not want to have a shared DB for 1. and 2., but we need them to have common tags for very flexible invalidation across both DBs whenever needed.

And as I am lacking experience with any Redis features beyong get/set and pulling stats out of it, I am wondering if the above use-case would be possible with the proposed implementation?

**Comment by nicolas-grekas** [comment]
Hi @wucdbm, thanks for your interest. Unless I misunderstood, this is already supported. But you need to configure TagAwareAdapter yourself for this situation, using its $tagPool argument for the shared tags pool (but please don't hijack this issue, this is a separate topic.)

**Comment by wucdbm** [comment]
@nicolas-grekas Yup, that's what we have in production for some time now and it's wonderful. My point was whether that will be easily supported by the newly proposed adapter implementation via configs as a drop-in replacement to what we already have for improved performance. I'd be very interested in having this kind of functionality supported by this adapter.

**Comment by nicolas-grekas** [comment]
Oh ok! I think you'll then have to keep using the existing adapter, because the new one would work because it would have both tags and items in the same backend (and also because you cannot call any remote endpoint from the Lua side.)
