### ISSUE TITLE
php7 Compatibility problem

### ISSUE THREAD

**Issue by oasfuyou** [symfony/symfony#28256]
symfony/config/Resource/ClassExistenceResource.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/config/Resource/DirectoryResource.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/config/Resource/FileExistenceResource.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

endor/symfony/config/Resource/FileResource.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/config/Resource/ResourceInterface.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/polyfill/tests/Mbstring/MbstringTest.php

 239 | ERROR | The function mb_chr() is not present in PHP version 7.1 or earlier
 240 | ERROR | The function mb_chr() is not present in PHP version 7.1 or earlier
 248 | ERROR | The function mb_ord() is not present in PHP version 7.1 or earlier
 249 | ERROR | The function mb_ord() is not present in PHP version 7.1 or earlier
 256 | ERROR | The function mb_scrub() is not present in PHP version 7.1 or earlier

symfony/config/Resource/SelfCheckingResourceChecker.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/config/Resource/SelfCheckingResourceInterface.php

 12 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

symfony/polyfill/src/Iconv/Resources/charset/from.cp037.php

 1 | WARNING | File has mixed line endings; this may cause incorrect results

symfony/polyfill/src/Intl/Normalizer/Normalizer.php

 86 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

symfony/yaml/Inline.php

 91 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

symfony/yaml/Parser.php

 99 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

**Comment by xabbuh** [comment]
What tool did you use to create this report? I checked a few of them and it seems to me that this tool did not take into account the context in which code is used and thus complains about things that must not be  changed.

**Comment by stof** [comment]
And for `symfony/polyfill/tests/Mbstring/MbstringTest.php`, that's clearly a false-positive. The mbstring polyfill precisely ensures that this function is defined

**Comment by xabbuh** [comment]
I am closing here as this seems to be an issue of the tool used to perform the static analysis (or its usage).
