### ISSUE TITLE
[Intl] Blacklist Eurozone (sub-continent)

### ISSUE THREAD

**Issue by hlecorche** [symfony/symfony#28260]
Hello. I have a question about Intl component : In RegionDataGenerator, the "eu" code (European Union) is blacklisted (reason: "Look like countries, but are sub-continents") but not "ez" (Eurozone). Is it a mistake ?

```php
     /**
     * Regions excluded from generation.
     */
    private static $blacklist = array(
        self::UNKNOWN_REGION_ID => true,
        // Look like countries, but are sub-continents
        self::OUTLYING_OCEANIA_REGION_ID => true,
        self::EUROPEAN_UNION_ID => true,
        // No longer exists
        self::NETHERLANDS_ANTILLES_ID => true,
        // Uninhabited islands
        self::BOUVET_ISLAND_ID => true,
        self::HEARD_MCDONALD_ISLANDS_ID => true,
        self::CLIPPERTON_ISLAND_ID => true,
    );
```

**Comment by stof** [comment]
Maybe EZ was not yet in the ICU data at the time this code was originally written, and nobody noticed it until now ?

**Comment by hlecorche** [comment]
Yes EZ was added after and the code has not been changed.

There are also these codes 
* AC (Ascension Island)
* DG (Diego Garcia)
* EA (Ceuta & Melilla)
* IC (Canary Islands)
* TA (Tristan da Cunha)
* UN (United Nations)
* Others ???

**Comment by nicolas-grekas** [comment]
PR welcome for the two new zones. For the 5 others, in doubt, I'd keep them.
