### ISSUE TITLE
Console clear:cache fails with clean install and a new controller

### ISSUE THREAD

**Issue by alex2005git** [symfony/symfony#28262]
**Symfony version(s) affected**: 4.1.3 (maybe older, haven't tested)

**Description**  
Clean install, after creating a controller, clear cache fails with a memory issue.  
Increasing the memory limit does not work.

**How to reproduce**  
`composer create-project symfony/website-skeleton my-project`
`cd my-project`
`php bin/console make:controller HomeController`
`php bin/console clear:cache`

**Possible Solution**  
Commenting line 119 from ResolveInvalidReferencesPass.php `throw $this->signalingException;` but it's not a proper solution (commenting it makes the route throw `Call to a member function render() on null` in the browser after deleting the dev folder)  

**Additional context**  
Error message
```
In ResolveInvalidReferencesPass.php line 119:

  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 79659156 bytes)
```
Full error message from console: https://pastebin.com/Rn3C8XAw

**PHP version**
PHP 7.2.5 (cli) (built: Apr 25 2018 02:39:21) ( ZTS MSVC15 (Visual C++ 2017) x86 )

**OS**
Windows 8.1 x64

**Comment by dmaicher** [comment]
Works fine for me on linux. Maybe some Windows specific issue? :confused:

**Comment by nicoweb** [comment]
Hello, can't replicate this issue on mac...

**Comment by ostrolucky** [comment]
Can't replicate on windows as well

**Comment by alex2005git** [comment]
Might be a fringe case on my system... can close, thanks guys!
