### ISSUE TITLE
Automatically creating config file under config/packages directory for custom composer package

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#28261]
Hi,

I created a custom symfony composer package but I couldn't find a way of automatically creating it's config file under `config/packages` directory? I am currently creating it manually before running `composer require my-custom-package` but I would like it to be created automatically with default values below.

```
# config/packages/football.yaml
football:
   country: uk
   league: pl
   teams: ~
```

My parent application is  Symfony 4.1 and the structure of composer package is shown below.

```
├── composer.json
├── src
│   ├── Command
│   │   └── PlayCommand.php
│   ├── DependencyInjection
│   │   ├── Configuration.php
│   │   └── FootballExtension.php
│   ├── Resources
│   │   └── config
│   │       └── services.yaml
│   └── FootballBundle.php
└── vendor
```

Thanks

**Comment by ro0NL** [comment]
You can submit a recipe for your bundle at https://github.com/symfony/recipes#creating-recipes

See also https://github.com/symfony/recipes#creating-recipes

**Comment by xabbuh** [comment]
Creating a recipe is indeed the way to go. If you have more questions about that process, I suggest to use one of the [support channels](https://symfony.com/support) to get further help. I am going to close here as there is nothing to fix. Thank you for understanding.
