### ISSUE TITLE
[Serializer] AbstractObjectNormalizer deserialization performance

### ISSUE THREAD

**Issue by martiis** [symfony/symfony#28276]
**Symfony version(s) affected**: 4.1.3 (havent test other)

**Description**  
I have noticed that deserialiation performance arent as good as serialization, but f.e. jms serializer serialization/deserialization perform roughly the same.

My test is deserializing 1000 objects with various scalar value properies + one property is an object + one property holds 5-15 small objects in array.

Deserialization took about `300 ms` while serialization is about `150 ms` (xdebug disabled)

**How to reproduce**  
My actual test https://github.com/martiis/symfony-serialization-bench/blob/master/src/Command/BenchSymfonySerializerCommand.php#L78

**Possible Solution**  
Based on blackfire lots of calls are being made to resolve class attribute type [here](https://github.com/symfony/symfony/blob/ff1727e2ee44d966a64379e90c58b5c54dc87140/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L363) even if it has done it before. So I tried to cache resolved types to a local variable and lost about `100ms` from the test.

My changed method:
```php
    private function getTypes(string $currentClass, string $attribute)
    {
        if (null === $this->propertyTypeExtractor) {
            return null;
        }

        $key = $currentClass . ':' . $attribute;
        if (isset($this->loadedTypes[$key])) {
            return $this->loadedTypes[$key];
        }

        if (null !== $types = $this->propertyTypeExtractor->getTypes($currentClass, $attribute)) {
            return $this->loadedTypes[$key] = $types;
        }

        if (null !== $this->classDiscriminatorResolver && null !== $discriminatorMapping = $this->classDiscriminatorResolver->getMappingForClass($currentClass)) {
            if ($discriminatorMapping->getTypeProperty() === $attribute) {
                return $this->loadedTypes[$key] = array(
                    new Type(Type::BUILTIN_TYPE_STRING),
                );
            }

            foreach ($discriminatorMapping->getTypesMapping() as $mappedClass) {
                if (null !== $types = $this->propertyTypeExtractor->getTypes($mappedClass, $attribute)) {
                    return $this->loadedTypes[$key] = $types;
                }
            }
        }

        return $this->loadedTypes[$key] = null;
    } 
```

**Additional context** 

[Blackfire graph before](https://blackfire.io/profiles/adea0b03-ea8d-4254-833e-8a65f298265b/graph)
[Blackfire graph after](https://blackfire.io/profiles/6a4f3d36-674c-4e7d-8dd5-f329b9cd9fab/graph)

**Comment by sroze** [comment]
Do you want to open a PR for that?

**Comment by martiis** [comment]
Coming 👍
