### ISSUE TITLE
[Serializer] CacheClassMetadataFactory performance

### ISSUE THREAD

**Issue by martiis** [symfony/symfony#28272]
**Symfony version(s) affected**: 4.1.3 (havent test other)

**Description**  
IDK if it was discussed in the past but recently i was checking symfony serializer (ObjectNormalizer) performance, and in dev env it was faster than in prod. I have configured opcache just like in docs, xdebug disabled.

My test is serializing 1000 objects with various scalar value properies + one property is an object + one property holds 5-15 small objects in array.

Serialize took about `2184 ms` prod env, `152 ms`  dev env.

**How to reproduce**  
My actual test https://github.com/martiis/symfony-serialization-bench/blob/master/src/Command/BenchSymfonySerializerCommand.php#L78

**Possible Solution**  
Found out that in prod [CacheClassMetadataFactory](https://github.com/symfony/serializer/blob/master/Mapping/Factory/CacheClassMetadataFactory.php#L44) does not keep loaded classes like [ClassMetadataFactory](https://github.com/symfony/serializer/blob/ea0ae28471025f43be4624d42d419c3e801a3870/Mapping/Factory/ClassMetadataFactory.php#L32) and everytime it goes into file system checking cache. I thought opcache should fix this but it didint or maybe i missed something? if I put `$loadedClasses` property in `CacheClassMetadataFactory` performance back as in dev env. 

**Additional context**  
Opcache config
```
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.interned_strings_buffer = 16
```

**Comment by martiis** [comment]
Blackfire graphs:
 - [dev](https://blackfire.io/profiles/76b845fe-760e-4aa0-ba2c-f2c9502cf0c6/graph)
 - [prod](https://blackfire.io/profiles/c271a1c8-f5a2-4491-80bc-c12d3576b018/graph

**Comment by GuilhemN** [comment]
A radical but efficient solution would be https://github.com/symfony/symfony/pull/22051 :)

**Comment by nicolas-grekas** [comment]
There's a regression identified in https://github.com/symfony/symfony/pull/28457#issuecomment-422100305.
Someone would need to have a look.

**Comment by martiis** [comment]
This will improve perf, but later I noticed that I haven't enabled opcache for cli, which improved performance (cant remember by how much atm, but near as dev env), because `PhpFilesAdapter` is only working with opcache enabled, else fallbacks to filesystem adapter. CacheClassMetadataFactory always goes into cache adapter, thats why my test was so slow.

**Comment by xabbuh** [comment]
let's close then as the issue seems to be resolved
