### ISSUE TITLE
Migrations directory "Class path doesn't match PSR-0/PSR-4 project structure."

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28274]
**Symfony version(s) affected**: master

**Description**  
A code inspection brings up the error for all migration files that are in the `Migrations` dir: ""Class path doesn't match PSR-0/PSR-4 project structure."" because `namespace DoctrineMigrations`.

Should the migrations dir be renamed to `DoctrineMigrations`?

**Comment by xabbuh** [comment]
These files (and the directory) are created by [the corresponding Flex recipe](https://github.com/symfony/recipes/tree/master/doctrine/doctrine-migrations-bundle/1.2) and this topic is already discussed [in the recipes repository](https://github.com/symfony/recipes/issues/343). Thus, I am closing here in favour of symfony/recipes#343. Thank you for understanding.
