### ISSUE TITLE
Request has both a trusted "FORWARDED" header and a trusted "X_FORWARDED_PORT" header

### ISSUE THREAD

**Issue by insekticid** [symfony/symfony#28279]
https://github.com/symfony/http-kernel/commit/d2e26c510454f758417aa8e562b10a540e5a160b#diff-f1fb6e1fbbca77aacb544d3c6b218515

Introduced in Symfony 4.1.3

From this update I got errors with headers

An exception has been thrown during the rendering of a template ("The request has both a trusted "FORWARDED" header and a trusted "X_FORWARDED_PORT" header, conflicting with each other. You should either configure your proxy to remove one of them, or configure your project to distrust the offending one.").

![image](https://user-images.githubusercontent.com/177340/44632094-4218f600-a975-11e8-80d8-fe3a1c492242.png)

**Comment by xabbuh** [comment]
Do you still experience the same behaviour with the latest development version of the `4.1` branch? There have been some improvements after the last release that are related to this topic.

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/pull/28144 fixes it I think.

**Comment by insekticid** [comment]
Installing symfony/http-foundation (4.1.x-dev 9277f00)
Installing symfony/framework-bundle (4.1.x-dev f62dc69)

Error is still here

Http headers from PHPinfo

![image](https://user-images.githubusercontent.com/177340/44632997-01c17400-a985-11e8-9b48-e8c662f1c56b.png)

**Comment by xabbuh** [comment]
Closing then, thanks for the feedback.
