### ISSUE TITLE
[Doctrine Bridge] Doctrine Extractor - missing DbalType for dates

### ISSUE THREAD

**Issue by Vincz** [symfony/symfony#28285]
**Symfony version(s) affected**: 4.1.3

**Description**  
Using `indexBy` in a relationship with a field of type `date` cause `DoctrineExtractor getTypes` method to create a new `Symfony\Component\PropertyInfo\Type` with `null` as first argument (and then failing) as the `getPhpType` method will return `null`.
Error message :
`
 Argument 1 passed to Symfony\Component\PropertyInfo\Type::__construct() must be of the type string, null given, called in project/ven
  dor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php on line 123
`

**How to reproduce**  
Create an entity with a relationship like : 
`@ORM\OneToMany(targetEntity="App\Entity\A", mappedBy="b", indexBy="date")`

**Possible Solution**  
Add the following missing types to the **getPhpType** method of the **DoctrineExtractor**.
`
DBALType::DATE, DBALType::DATETIME, DBALType::DATETIMETZ, 'vardatetime', DBALType::TIME
`

**Additional context**  
Problem occurs with api platform and ApiResource when api platform try to create metadata with  
`ApiPlatform\Core\Bridge\Symfony\PropertyInfo\Metadata\Property\PropertyInfoPropertyMetadataFactory->create()
`

**Comment by nicolas-grekas** [comment]
Would you like to work on a fix?

**Comment by javiereguiluz** [comment]
Closing as "fixed" because all the mentioned types now exist in Symfony 4.2+. They were added in https://github.com/symfony/symfony/commit/b50360f8bb56f0b86f98de13c445c081b1d74dd5.
