### ISSUE TITLE
Should TemplateIterator return only template files

### ISSUE THREAD

**Issue by dtrputec** [symfony/symfony#28282]
**Description**  
Currently TemplateIterator::findTemplatesInDirectory($dir, $namespace = null) is returning everything from directory because of this line `foreach (Finder::create()->files()->followLinks()->in($dir) as $file)`

**Example**  
Since this is a template iterator, does it makes sense to filter only template files from directory?Something like this `foreach (Finder::create()->name('*.twig')->files()->followLinks()->in($dir) as $file)`

This is useful when you want to have in your template directory related assets like *.js or *.css or event whole `node_modules` directory. 

I can provide a PR with unit tests if you want.

**Comment by ro0NL** [comment]
Is there any reason to do so?  Because non-template files should be ignored anyway..

https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheWarmer.php#L47-L54

Eventually im not sure we can make such an assumption (at least not hardcoded): `->name('*.twig')`

**Comment by stof** [comment]
The thing is, Twig does not restrict itself to the `.twig` extension. Any file extension can be used (and the WebProfilerBundle even takes advantage of it to include SVG file, as a Twig template without any Twig markup is still a valid template). Restricting the extension would prevent warming up these templates.

**Comment by dtrputec** [comment]
We could make this iterator configurable and that way more flexible and with no breaking changes.

**Comment by ro0NL** [comment]
> Why should we care if related assets are in separate assets directory or in the same directory as template files. 

Well.. that's my point. In the framework you dont need to care... as the warmup skips non template files anyway.

**Comment by dtrputec** [comment]
Sorry if my explanations are blurry but I was referring to this line: 
https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Bundle/TwigBundle/TemplateIterator.php#L86

As you can see every file ends up in $templates[] and pointlessly increasing memory usage.

**Comment by ro0NL** [comment]
Clear :) just wondering if it's negligible or not... if not, we could add `twig: { template_pattern: ~ }` configuration i guess.

**Comment by dtrputec** [comment]
I believe it's not negligible :) `twig: { template_pattern: ~ }` should to the trick!

**Comment by javiereguiluz** [comment]
@dtrputec even if I agree with you theoretically ... I don't in practice.

You say ... this would be better in case people store web assets in `templates/` or even the entire `node_modules/` dir inside `templates/`. I don't think those are realistic scenarios at all. I can't think of any valid reason to store the contents of `assets/` or `node_modules/` inside `templates/` ... but if some app does, they can do this:

```
templates/
  assets/
  node_modules/
  twig/
```

And then, configure this option to tell Symfony that templates are actually in `templates/twig/`:

```yaml
# config/packages/twig.yaml
twig:
    # ...
    paths: ["%kernel.project_dir%/templates/twig"]
```

**Comment by javiereguiluz** [comment]
@dbrekalo that's a very good example! I wasn't thinking about that architecture. Thanks!

Now, the question is how many files do you expect even in large apps when using that structure. I'd say "low hundreds" ... so performance shouldn't suffer much (otherwise, there might be a bug in template loading?).

As long as we don't add `node_modules/` inside `templates/` I think we should be fine.

**Comment by fabpot** [comment]
IIUC, the performance issue is only at compilation time. Making it possible to configure which files are parsed globally is not possible as it would break current usages. So, I'm closing as won't fix.
