### ISSUE TITLE
[Workflow] When entering default state, no workflow events are thrown

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28319]
**Symfony version(s) affected**: master

**Description**  
An event is thrown when a workflow enters a place, except upon creating a new instance of an object, there is not a function to transition into the initial place, thus triggering the entered event.

**Comment by lyrixx** [comment]
Indeed, you are right. I made a PR for your issue, but it's a bit weird to me.
Could you explain to us why you need this event ?

**Comment by ChangePlaces** [comment]
Sure. In terms of workflow, it makes more sense to monitor when an object / item is in a certain state rather than having to monitor that state AND when an object is created as it's more complicated to update the system in the future. 

The 'default' state should be transitioned into when the item is created to enable the workflow listeners
