### ISSUE TITLE
UrlGeneratorInterface switches from HTTPS to HTTP when generating AbsolutUrl

### ISSUE THREAD

**Issue by vlahanas** [symfony/symfony#28318]
**Symfony version(s) affected**: 3.4.15

**Description**  
I am using UrlGeneratorInterface to create absolute URLs that point to certain routes of my website (hosted in Heroku, maybe this plays some role due to the Heroku DNS). Up to now, I had faced no issues whatsoever. However, since upgrading to 3.4.15 from 3.4.13, the generated URLs are HTTP although the domain is HTTPS. Any ideas on what might be the cause?

**Comment by nicolas-grekas** [comment]
Could you please create a small reproducer app we could clone locally to experience this?

**Comment by vlahanas** [comment]
I 've just created this repo that illustrates the problem (excuse my code quality, I tried to do it as fast as I could): https://github.com/vlahanas/UrlGeneratorTesting

You can also see an online illustration of it here: https://url-symfony-testing.herokuapp.com/
As you can notice, althouth the url is https, the generated url is http.

**Comment by xabbuh** [comment]
According to [the documentation](https://devcenter.heroku.com/articles/getting-started-with-symfony#trusting-the-load-balancer) Heroku uses reverse proxy that terminate the HTTPS connections and you thus need to configure the trusted proxy address.

**Comment by vlahanas** [comment]
I suspect that Heroku is somehow related, but even so, if I switch to 3.4.13 in the my example, I don't face the same issue. This is why I 've created the issue. In my production app, I bypassed this behavior by using str_replace to change from http to https, but still, I remain curious :)

**Comment by nicolas-grekas** [comment]
If you didn't configure trusted proxies then the new behavior is correct and you need to do it.
Please confirm you did and that it fixed it for you.

**Comment by vlahanas** [comment]
@nicolas-grekas @xabbuh 
Indeed, I 've set trusted proxies and it seems to be working properly now. Thank you!
