### ISSUE TITLE
[Dependency Injection] The service inheritance resolution does not detect circular references

### ISSUE THREAD

**Issue by stof** [symfony/symfony#28312]
**Symfony version(s) affected**: all

**Description**  
When a `ChildDefinition` references itself as parent (or as ancestor in case of longer cycle), an infinite loop happens in the resolution logic.

**How to reproduce**  
see https://github.com/symfony/symfony/issues/28308

**Possible Solution**  
Such loops should be detected and trigger a proper exception instead (like circular references between services in arguments)

**Comment by Seb33300** [comment]
Why not, but I cannot guarantee to have to do this soon.
