### ISSUE TITLE
[Console] Corrupt error output for unknown multibyte short option

### ISSUE THREAD

**Issue by downace** [symfony/symfony#28320]
**Symfony version(s) affected**: 4.1.4

**Description**

Error contains only first byte of multibyte short option

**How to reproduce**

1. `composer require symfony/console:4.1.4`
2. Create `application.php` with simple command. Example:

```php
#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$application = new Application();

$application->add(new class extends Command {
    public function getName() {
        return 'do';
    }

    public function execute(InputInterface $input, OutputInterface $output) {
    }
});

$application->run();
```

3. `./application.php do -С 10` (where `С` is Cyrillic; you can use another letter, e.g. `Щ`)

**Possible Solution**

Use `mb_substr` instead of index access in `\Symfony\Component\Console\Input\ArgvInput::parseShortOptionSet`

**Additional context**

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR fixing this issue?
