### ISSUE TITLE
Close session after fetching token in ContextListener

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#28325]
**Status quo**

Symfony currently implicitly starts the session when user management is used. This is necessary because the user is fetched from the session.

https://github.com/symfony/symfony/blob/c3ec061fd0992797e368a5e608886f7025387e68/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L89

https://github.com/symfony/symfony/blob/c3ec061fd0992797e368a5e608886f7025387e68/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L138

https://github.com/symfony/symfony/blob/c3ec061fd0992797e368a5e608886f7025387e68/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L141

Those lines will implicitly start the session.

**Feature request**

Symfony currently does not close the session after it's accessed. This means that the request will acquire a lock on the session file and make other requests wait for the entire request to finish, even if the session is not used after Symfony authenticates the user.

This could be solved rather easily by adding a `$session->save();` call after accessing the values from the session. This will release the lock and allow other requests to access the session file.

This could have a few potential issues:

1. More overhead because of additional serialization and deserialization of session data
2. Race conditions where requests must be executed in a certain order, start to finish

The big pro would be allowing parallel requests.

WDYT?

**Comment by iltar** [comment]
It does make sense to keep a lock, because you don't know at this point if the session will be used to read/write to afterwards. 

More of a question towards @nicolas-grekas, would it be possible to define at controller level, whether it will write something into the session and optimize this? In theory it should be possible because security is triggered on `kernel.request` earliest, at a point where we already know the current controller (routing takes place before the security listener)

```
/**
 * @Session("write")
 */
public function fooAction()
{
}

/**
 * @Session("read_only")
 */
public function fooAction()
{
}
```

Just an example to point out a possible solution, wouldn't implement the annotations like this myself.

**Comment by iluuu1994** [comment]
@iltar 

> It does make sense to keep a lock, because you don't know at this point if the session will be used to read/write to afterwards.

In my experience sessions aren't used all that much. Of course it does happen in things like shops and multi-page forms but the vast majority of our actions do not access the session. The session should not stay open for the minority of actions IMHO.

**Comment by nicolas-grekas** [comment]
I would to it another way @iltar, e.g. using a new service that would be given access to a read-only session. But let's not hijack this thread.

@iluuu1994 we cannot specialize the default behavior for what (we think) most people do. The default behavior must be valid for everyone.

(If we focus only on security, there is a way, with an implementation in #27817.)

**Comment by iluuu1994** [comment]
@nicolas-bastien 

> we cannot specialize the default behavior for what (we think) most people do. The default behavior must be valid for everyone.

Of course. The question is if closing the session is invalid. Which I don't think it is.

**Comment by nicolas-grekas** [comment]
It is because it will break code that need to write to the session later on.

**Comment by iluuu1994** [comment]
> It is because it will break code that need to write to the session later on.

Will it though? The session component will automatically restart the session. Using the `$_SESSION` variable is already prohibited (or at least highly discouraged).

**Comment by iluuu1994** [comment]
> This allows Symfony to peacefully co-exist with other applications or libraries that might use the $_SESSION super-global and all data remains completely compatible with Symfony's session management.

I was wrong. You can use the `$_SESSION` variable directly.

**Comment by nicolas-grekas** [comment]
It will release the lock, so that there might be race conditions making the data invalid.

**Comment by nicolas-grekas** [comment]
I've reopened #27817 which provides this lock-less behavior (in a different way than proposed here.)
See last comment there.

**Comment by iluuu1994** [comment]
@nicolas-grekas Cool, thanks for investigating!

**Comment by stof** [comment]
I don't think that ContextListener should close the session by itself (it does not own it).

If you want to have a system closing the session early based on the controller, this can be implemented separately, as a kernel.request listener (even outside Symfony itself).
But be careful about the fact that the session could be used by controllers, but also by other code (a kernel.response listener, which would run for many controllers)

**Comment by iluuu1994** [comment]
@stof

> I don't think that ContextListener should close the session by itself (it does not own it).

The `ContextListener` start the session, so it could be considered the owner of the session.

> But be careful about the fact that the session could be used by controllers, but also by other code (a kernel.response listener, which would run for many controllers)

True. If you're using the Symfony session since the session will simply be restarted. Of course this would kind of defeat the purpose since the session would just be locked again a few statements later. I can definitely see your point here.

> this can be implemented separately, as a kernel.request listener

That would work. That might actually be the best solution if you're using the session in `kernel.response` event listeners since the session will only be serialized/deserialized once.

Still feels kind of odd that you'd have to implement this yourself to achieve parallel requests in the best PHP framework.

**Comment by nicolas-grekas** [comment]
I don't think we should do anything here, except finishing #27817 and #28089.
Closing the lock earlier than currently done would rely on assumptions that cannot be valid in the general case.
Being able to have fine grained locked time slices is really hard to achieve and would need a complete redesign of the session logic and user management of it.
If the lock is bad for you, I'd suggest going with a lockless session storage: this is usually just fine, especially if you don't write to much to the session (which you shouldn't really).
That'd be way more effective and way simpler for everyone (maintainers and users.)
I'm therefore closing this issue, thanks for the discussion.
