### ISSUE TITLE
PHPunit does not correctly catch HttpException codes

### ISSUE THREAD

**Issue by InputOutput** [symfony/symfony#28327]
**Symfony version(s) affected**: 4.1

**Description**  
When running unit tests on code that throw a HttpException, the expectedException() method of the PHPunit framework correctly detects the exception. The expectedExceptionCode() method does not however pick up on the exception code.

**How to reproduce**  

```php
<?php

use PHPUnit\Framework\TestCase;

use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpFoundation\Response;

class ExceptionCodeFailTest extends TestCase
{
    private function throwHttpExceptionCodeFromConstant()
    {
        throw new HttpException(Response::HTTP_BAD_REQUEST, 'This status code will not be picked up by expectExceptionCode()');
    }

    private function throwHttpExceptionCodeHardCoded()
    {
        throw new HttpException(400, 'This status code will not be picked up by expectExceptionCode()');
    }

    private function throwSPLException()
    {
        throw new \Exception('Works fine', 400);
    }

    public function testHttpExceptionCode()
    {
        $this->expectException(HttpException::class);
        $this->expectExceptionCode(400);

        $this->throwHttpExceptionCodeFromConstant();
    }

    public function testHttpExceptionCodeHardCoded()
    {
        $this->expectException(HttpException::class);
        $this->expectExceptionCode(400);

        $this->throwHttpExceptionCodeHardCoded();
    }

    public function testExceptionCode()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionCode(400);

        $this->throwSPLException();
    }
}
```

```bash
root@a6c9127a4a93:/var/www/html# vendor/bin/simple-phpunit tests/Unit/ExceptionCodeFailTest.php 
PHPUnit 6.5.12 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.8
Configuration: /var/www/html/phpunit.xml

Testing ExceptionCodeFailTest
FF.                                                                 3 / 3 (100%)

Time: 62 ms, Memory: 4.00MB

There were 2 failures:

1) ExceptionCodeFailTest::testHttpExceptionCode
Failed asserting that 0 is equal to expected exception code 400.

2) ExceptionCodeFailTest::testHttpExceptionCodeHardCoded
Failed asserting that 0 is equal to expected exception code 400.

FAILURES!
Tests: 3, Assertions: 6, Failures: 2.
root@a6c9127a4a93:/var/www/html# 

```

**Possible Solution**  
Only workaround I've found to work is to use a try/catch in the test itself to check HttpException::getStatusCode() instead of ::getCode() which is quite ugly. I see that there's both a statusCode and code set on the HttpException and the code is 0 whereas the statusCode is correct. This might be intentional but it does seem counter-intuitive.

**Comment by InputOutput** [comment]
So yes I just noticed but it does make unittesting of code that throws HttpExceptions difficult. Can you explain the reason for this construction?

**Comment by InputOutput** [comment]
Or would you be open for a PR that sets the code to the statusCode if no code argument is given in the constructor?

**Comment by nicolas-grekas** [comment]
> Or would you be open for a PR that sets the code to the statusCode if no code argument is given in the constructor?

that could make sense, PR welcome so we can discuss it there.

**Comment by rpkamp** [comment]
Why not use specific HTTP exception classes, such as `Symfony\Component\HttpKernel\Exception\NotFoundHttpException`? That way you check for the right exception, and implicitly test for the correct exception as well, without having to mix Exception codes and HTTP status codes, which are completely different things.

**Comment by InputOutput** [comment]
> Why not use specific HTTP exception classes
That would work, but testing if a correct Exception class does still not assert that this exception class returns the correct HTTP status code. 
I quickly browsed the testsuite for the http-kernel, but I could not find systematic testing on the HTTP status codes the Exception classes throw. I could maybe extend the tests in a PR, I'll try to find some time. If I did oversee particular tests testing this, a heads up would be nice.

**Comment by rpkamp** [comment]
> That would work, but testing if a correct Exception class is thrown does still not assert that this exception class returns the correct HTTP status code.

Those kind of tests would indeed belong in the Symfony codebase, not in yours.
I'm not sure if tests would add any value here, as any PR that would change a status code of an HTTP exception would probably be shot down already, but you could of course create a PR to see what the general consensus is.

**Comment by jakzal** [comment]
> Or would you be open for a PR that sets the code to the statusCode if no code argument is given in the constructor?

I'd be careful here. We agreed in past exception codes are not the same as http status codes. Treating them the same in SOME scenarios would only introduce more confusion.

**Comment by InputOutput** [comment]
> Treating them the same in SOME scenarios would only introduce more confusion.

Yes, it didn't seem like a particularly good idea from the bat, maybe that's why I haven't made the PR yet ;)
@rpkamp's suggestion is much more elegant and in line with existing code so I'll go for that and close this issue. Possibly I'll open a PR for a few extra tests on the HTTP status codes returned by particular HttpException extensions.

**Comment by InputOutput** [comment]
Thanks all for the insightfull discussion!
