### ISSUE TITLE
Use multiple connections

### ISSUE THREAD

**Issue by waghanza** [symfony/symfony#28341]
**Symfony version(s) affected**: 4.1.4

I have two open to store my data in **2** different separated databases (`mysql` for now).
Following the documentation for [here](https://symfony.com/doc/current/doctrine/multiple_entity_managers.html), I have the message
~~~php
An exception occurred while executing 'SELECT t0.id AS id_1, t0.firstname AS firstname_2, t0.lastname AS lastname_3 FROM user2 t0':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db1.user2' doesn't exist
~~~

:warning:  **db1** is the default database, not the one I have selected  in https://github.com/waghanza/multidb-sf/blob/master/src/Controller/ApplicationController.php#L17

I have made https://github.com/waghanza/multidb-sf/issues/1 to bug report in a proper implementation,  any solution will be :heart: for me (`symfony` newbie).

Regards,

**Comment by xabbuh** [comment]
As far as I can see this comes from a mistake in the documentation (see symfony/symfony-docs#9878). So I am going to close here in favour of the documentation issue. Thank you for understanding.

**Comment by waghanza** [comment]
@xabbuh Thanks for reaching out. After reading issue in symfony doc https://github.com/symfony/symfony-docs/issues/9878, it appears not to be the exact same case. the issue was about to access the **same** entity using different _em_.

In my case, I have **two** distinct _entities_
