### ISSUE TITLE
Entity Repository support question: Factory based or not?

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#28346]
Hi,

I have two examples for repository usage and wish to know which one is better. Both works fine but in depth, one of them would probably have some advantages over the other one. I have a feeling that the version 2 is better but I would be much appreciated if you guys share your thoughts with me.

Thanks in advance

**Entity**

```
/**
 * @ORM\Entity
 * @ORM\Table(name="country")
 */
class Country
{
    .....
}
```

---------------

**VERSION 1**

**Repository**

```
class CountryRepository implements CountryRepositoryInterface
{
    private $entityRepository;
    private $entityManager;

    public function __construct(
        EntityRepository $entityRepository,
        EntityManagerInterface $entityManager
    ) {
        $this->entityRepository = $entityRepository;
        $this->entityManager = $entityManager;
    }

    public function doSomething()
    {
        $this->getRepository()->...
        $this->getEntityManager()->...
    }
}
```

**Config**

    app.entity_repository.country:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - App\Entity\Country

    App\Repository\CountryRepository:
        arguments:
            $entityRepository: '@app.entity_repository.country'

---------------

**VERSION 2**

**Repository**

```
abstract class AbstractRepository
{
    private $entityManager;
    private $entityName;

    public function __construct(EntityManagerInterface $entityManager, string $entityName)
    {
        $this->entityManager = $entityManager;
        $this->entityName = $entityName;
    }

    protected function getEntityManager(): EntityManagerInterface
    {
        return $this->entityManager;
    }

    protected function getRepository(): EntityRepository
    {
        return $this->entityManager->getRepository($this->entityName);
    }
}

class CountryRepository extends AbstractRepository
{
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, Country::class);
    }

    public function doSomething()
    {
        $this->getRepository()->...
        $this->getEntityManager()->...
    }
}
```

**Config**

`No config is needed.`

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
