### ISSUE TITLE
Console is broken in Symfony 4.1.4

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#28355]
**Symfony version(s) affected**: 4.1.4

**Description**  
The console is broken after upgrading our vendor directory from Symfony 4.1.3 to 4.1.4. The command throws a PhpDumper exception:

**How to reproduce**  
```
bin/console

In PhpDumper.php line 1543:
Cannot dump definitions which have method calls.
```

**Additional context**
![image](https://user-images.githubusercontent.com/1032281/45030616-c261ea00-b04c-11e8-9eae-b85fa430d13f.png)

**Comment by xabbuh** [comment]
Thanks for reporting, but this seems to be the same as #28296. So I am closing here as a duplicate.

**Comment by nicolas-grekas** [comment]
Can you please report if applying #28366 fixes your issue?

**Comment by XWB** [comment]
@nicolas-grekas I'm now getting other errors:

```php
(1/1) ErrorExceptionNotice: Undefined variable: f
--
in srcDevDebugProjectContainer.php line 1786
```

```php
(2/2) Twig_Error_Syntax
Unknown "abbr_class" filter.
```
