### ISSUE TITLE
Php documentation for methods "setOption()/setArgument()" doesn't allow arrays as values

### ISSUE THREAD

**Issue by liarco** [symfony/symfony#28354]
Hi, I'm working on a console application that deals with options registered as `InputOption::VALUE_IS_ARRAY`, but when I call `$input->setOptions('my-option', ['value1', 'value2'])` during initialization/validation my IDE complains about the second argument not matching the documentation (`string|bool`). The same applies to the `setArgument($name, $value)` method which is set to `string` only.

Since I might have array values for both options and arguments, should it be included into the documentation? Is it right to set array values for options/arguments in a this way?

Here is my proposal for the doc update: **(I don't know if "array" is better than "string[]" here...)**
```php
    // File: symfony/console/Input/InputInterface.php

    // ...

    /**
     * Sets an argument value by name.
     *
     * @param string          $name  The argument name
     * @param string|string[] $value The argument value
     *
     * @throws InvalidArgumentException When argument given doesn't exist
     */
    public function setArgument($name, $value);

    // ...

    /**
     * Sets an option value by name.
     *
     * @param string               $name  The option name
     * @param string|string[]|bool $value The option value
     *
     * @throws InvalidArgumentException When option given doesn't exist
     */
    public function setOption($name, $value);

    // ...
```

Thank you for your time, please let me know if you want me to send a pull request for this.

**Comment by chalasr** [comment]
Actually both methods should accept a value of any type except objects not implementing `__toString()`.
I would say that both should say `mixed` and mention the exception in the param's description.
Pull request welcomed anyways, this should be fixed on the 2.8 branch.

**Comment by chalasr** [comment]
Additionally `mixed` would be consistent with `InputArgument::setDefault()` and `InputOption::setDefault()`.

**Comment by liarco** [comment]
@xabbuh imho that would be helpful in case you need to validate/build values with complex operations returning objects as results. Those results might have a meaningful default "string" representation which can be used as value. (e.g. imagine wrapping some strings with something like [danielstjules/Stringy](https://github.com/danielstjules/Stringy) to perform some validation/transformation, then it would be possible to drop the resulting object without explicit casting)

Does it make sense?

**Comment by chalasr** [comment]
@xabbuh I was thinking to the case where input values would be replaced after being casted/resolved e.g. by a console event listener (see also https://github.com/symfony/symfony/issues/19441).  
Right now I don't see a place where such code could break, the `__toString()` method of core InputInterface implementations need to be able to cast the input values to strings for escaping, which would be fine with the proposed set of types.

If you still think this is more risky than useful, then we should probably fix the `setDefault()` docblock for `InputArgument` and `InputOption` to reflect the current `InputInterface::setArgument` and `setOption` docblocks.
