### ISSUE TITLE
Documentation Error (Auto Generation of PDF Broken) on Symphony Website

### ISSUE THREAD

**Issue by Panoramity** [symfony/symfony#28357]
Visiting:   Home  /  Documentation  /  Components
Click:   (Download as PDF)

      https://symfony.com/doc/current/components/index.html

Only get 74 pages (first three components only), then it breaks.
It should include the documentation on all Symphony Components.

From past experience, it should be 300-400 pages in the PDF.

Thank you!

**Comment by javiereguiluz** [comment]
@Panoramity thanks for reporting this issue. Sadly we're aware of it; see https://github.com/symfony/symfony-docs/issues/7268. I'm closing this in favor of the mentioned issue. Thanks!
