### ISSUE TITLE
Failed to save key: User Notice: serialize(): \"groups\" returned as member variable from __sleep() but does not exist at 

### ISSUE THREAD

**Issue by yawa20** [symfony/symfony#28352]
**Symfony version(s) affected**:  4.2.0-DEV

**Description**  
on entity caching get`s an error:
```
cache.WARNING: Failed to save key "<entity_field_name_here>" (array) {"key":"<entity_field_name_here>","type":"array","exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Cache key \"<entity_field_name_here>\" has non-serializable array value. at /vendor/symfony/cache/Traits/PhpFilesTrait.php:171, ErrorException(code: 0): User Notice: serialize(): \"groups\" returned as member variable from __sleep() but does not exist at /vendor/symfony/cache/Marshaller/PhpMarshaller/Marshaller.php:145)"} 
```

**How to reproduce**  
add validation assertions to doctrine entity field without "groups" property, then try to build project
it happend because Constraints have lazily field ("groups"), and it does not exists before $value->__sleep() calls.

**Possible Solution**  
in Marshaller::marshall() method call 
$value->__sleep() before $arrayValue = (array) $value;

**Comment by sroze** [comment]
@yawa20 would you be willing to share your resolution so it can help others in the future? :)

**Comment by nicolas-grekas** [comment]
Actually that's a real bug! See #28352 for the fix.
