### ISSUE TITLE
[HttpCache] Unable to create the store directory

### ISSUE THREAD

**Issue by xsuntel** [symfony/symfony#28360]
**Symfony version(s) affected**: 4.1.4

**Description**  

I have confirmed 500 error message after my application was deployed to Elastic Beanstalk.

When I input commands as below,

    $ php ./bin/console cache:clear --env=dev
    $ php ./bin/console cache:clear --env=prod --no-debug

I could see each of the  different permissions.

    ryan@dev:/var/www/html/var/cache$ ls -ltr
    total 8
    drwxrwxrwx 8 ryan ryan 4096  9월  5 00:52 dev
    drwxrwxr-x 9 ryan ryan 4096  9월  5 00:52 prod

What's more, I can't see a directory : /var/www/html/var/cache/prod/http_cache

Could you please give me an advice?

**How to reproduce**  

    $ php ./bin/console cache:clear --env=prod --no-debug

    open a web browser

    Fatal error: Uncaught RuntimeException: Unable to create the store directory (/var/www/xsuntv/var/cache/prod/http_cache). in /var/www/xsuntv/vendor/symfony/http-kernel/HttpCache/Store.php on line 38
    ( ! ) RuntimeException: Unable to create the store directory (/var/www/html/var/cache/prod/http_cache). in /var/www/html/vendor/symfony/http-kernel/HttpCache/Store.php on line 38

**Additional context**  

    ryan@dev:/var/www/html/var/cache$ ls -ltr
    total 4
    drwxrwxr-x 9 ryan ryan 4096  9월  5 00:31 prod

    ryan@dev:/var/www/html/var/cache/prod$ ll
    total 284
    drwxrwxr-x   9 ryan ryan  4096  9월  5 00:31 ./
    drwxrwxrwx   3 ryan ryan  4096  9월  5 00:31 ../
    drwxrwxr-x 225 ryan ryan  4096  9월  5 00:31 annotations/
    -rw-rw-r--   1 ryan ryan   165  9월  5 00:31 annotations.map
    drwxrwxr-x   2 ryan ryan 36864  9월  5 00:31 ContainerSlSRYL2/
    drwxrwxr-x   3 ryan ryan  4096  9월  5 00:31 doctrine/
    drwxrwxr-x   2 ryan ryan  4096  9월  5 00:31 fos_rest/
    drwxrwxr-x   9 ryan ryan  4096  9월  5 00:31 pools/
    -rw-rw-r--   1 ryan ryan    96  9월  5 00:31 serialization.php
    -rw-rw-r--   1 ryan ryan   748  9월  5 00:31 srcProdProjectContainer.php
    -rw-rw-r--   1 ryan ryan 78530  9월  5 00:31 srcProdProjectContainer.php.meta
    -rw-rw-r--   1 ryan ryan 29717  9월  5 00:31 srcProdProjectContainerUrlGenerator.php
    -rw-rw-r--   1 ryan ryan 14393  9월  5 00:31 srcProdProjectContainerUrlGenerator.php.meta
    -rw-rw-r--   1 ryan ryan 30790  9월  5 00:31 srcProdProjectContainerUrlMatcher.php
    -rw-rw-r--   1 ryan ryan 14393  9월  5 00:31 srcProdProjectContainerUrlMatcher.php.meta
    drwxrwxr-x   2 ryan ryan 12288  9월  5 00:31 translations/
    drwxrwxr-x 185 ryan ryan  4096  9월  5 00:31 twig/
    -rw-rw-r--   1 ryan ryan 12572  9월  5 00:31 validation.php

**Comment by stof** [comment]
hmm, the 4.0 documentation removed the filesystem permission section from the setup chapter. But our cache folder is not fully read-only, and especially not when using the HttpCache kernel (as that one needs to store cache items are runtime, not as a read-only cache after warm-up).

/cc @weaverryan

**Comment by javiereguiluz** [comment]
We didn't remove the permission issue explanation ... but we buried the link to it (https://symfony.com/doc/current/setup/file_permissions.html) inside the Setup article. We did that because permissions should no longer be a problem in Symfony 4 because of the `umask(0000)` changes we did in `debug` mode.

**Comment by nicolas-grekas** [comment]
Closing as, unless I misunderstood, there is no bug in the code.
