### ISSUE TITLE
[Dotenv][Debug]Whitespace fatal error isn't properly formatted

### ISSUE THREAD

**Issue by BackEndTea** [symfony/symfony#28361]
**Symfony version(s) affected**: 4.1.4, and probably lower

**Description**  
When the `.env` file contains a whitespace within a 'token' it will result in a fatal error. Excep that it is not properly formatted like other exceptions.

I get the following errror
```
Fatal error: Uncaught Symfony\Component\Dotenv\Exception\FormatException: Whitespace are not supported before the value in "/home/wwwroot/sf4/public/../.env" at line 15. ...ndtea\nGITHUB_SECRET= <hidden>... ^ line 15 offset 598 in /home/wwwroot/sf4/vendor/symfony/dotenv/Dotenv.php:400 Stack trace: #0 /home/wwwroot/sf4/vendor/symfony/dotenv/Dotenv.php(185): Symfony\Component\Dotenv\Dotenv->createFormatException('Whitespace are ...') #1 /home/wwwroot/sf4/vendor/symfony/dotenv/Dotenv.php(128): Symfony\Component\Dotenv\Dotenv->lexValue() #2 /home/wwwroot/sf4/vendor/symfony/dotenv/Dotenv.php(57): Symfony\Component\Dotenv\Dotenv->parse('# This file is ...', '/home/wwwroot/s...') #3 /home/wwwroot/sf4/public/index.php(15): Symfony\Component\Dotenv\Dotenv->load('/home/wwwroot/s...') #4 {main} thrown in /home/wwwroot/sf4/vendor/symfony/dotenv/Dotenv.php on line 400
```

**How to reproduce**  
Put whitespace in the `.env` file directly after a space and try to load the file.

**Possible Solution**  
The issue here is that at this point we can't be sure what the environment is, because the `.env` file can't be parsed.

I'm not too familiar with the inner workings of the Dotenv component, but if the `APP_ENV` variable is known at the point of the error then the formatting of that enviroment should be followed (e.g. nice display for dev, 500 page for prod)

**Comment by xabbuh** [comment]
This looks like the same as #27949 to me. Thank you for reporting anyway. 👍
