### ISSUE TITLE
./bin/phpunit command not found

### ISSUE THREAD

**Issue by rottenoats** [symfony/symfony#28364]
**Symfony version(s) affected**: 4.0

**Description**  
https://symfony.com/doc/current/testing.html

Just following the tutorial and there is no phpunit file located in my bin directory.

This is my ouput from my terminal when running this `composer require --dev symfony/phpunit-bridge`

> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> ^[[DNothing to install or update
> Generating autoload files
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class
> Executing script cache:clear [OK]
> Executing script assets:install --symlink --relative public [OK]

**How to reproduce**  

`composer require --dev symfony/phpunit-bridge`
`./bin/phpunit`

**Comment by rottenoats** [comment]
@curry684 thanks for the response, however after `composer req symfony/flex`, I'm still not getting the desired `phpunit`. Any thoughts on what I should do next? Thanks.

**Comment by curry684** [comment]
That's because Flex is a Composer plugin only intervening on initial install, as you're actually free to modify/delete anything it adds to your project.

Remove the package and re-add it to let Flex do its job:
```
composer rem --dev symfony/phpunit-bridge
composer req --dev symfony/phpunit-bridge
```

**Comment by xabbuh** [comment]
I am going to close here as we use GitHub only to track bugs and feature requests. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by curry684** [comment]
@xabbuh the docs issue remains that the guide is misleading though.

**Comment by xabbuh** [comment]
The problem is that we assume throughout the whole docs for Symfony 4+ that one uses Symfony Flex. Adding additional notes everywhere how things differ when not using Flex would become a nightmare. But please feel free to open an issue in the documentation repo if you feel that this needs some more discussion.

**Comment by curry684** [comment]
@rottenoats is my assumption correct that you only ran into this issue because you were upgrading a 3.x application, or did you start from scratch?

**Comment by rottenoats** [comment]
@curry684 no, I made this project from scratch using the `composer create-project symfony/website-skeleton my_project`. To be honest, I was surprised when it was assumed that I'm not using Symfony Flex as I was pretty sure it was Flex.

**Comment by xabbuh** [comment]
@rottenoats In this case, updating to the latest version of Symfony Flex and running `composer fix-recipes` afterwards may also help. It will apply all recipes that haven't been applied yet. But I suggest to carefully review the result changes afterwards.

**Comment by javiereguiluz** [comment]
@rottenoats something weird must have happened here. I've just run this command:

```bash
$ composer create-project symfony/website-skeleton my_project
```

and:

```bash
$ cd my_project/
$ ls bin

  console
  phpunit
```

So you don't even have to run this other command:

```bash
$ composer require --dev symfony/phpunit-bridge
```

But if I do, the result is the same and `bin/phpunit` still exists.

**Comment by kyrrr** [comment]
Having the same issue in my flex application. There is no ./bin/vendor file. There is a ./vendor/bin/simple-phpunit, but that's not mentioned anywhere in the docs. Very confusing process for getting this installed and running.

**Comment by przemo-hemmersbach** [comment]
I've installed on Flex enabled app (with many flex recipes working OK), by:

`composer require --dev phpunit`

`bin/phpunit`
Does exists. However it's composer in disguise. It tryies to find `composer.json` in `bin/` (???), and procedes to run `composer install` still in `bin/`

Second run will run phpunit.

**Comment by allan-simon** [comment]
I'm having the same issue in symfony 4.4, and googling only refer this issue so I post here, on a fresh install of my project, the bin/phpunit is not installed (though I do have `symfony/flex` )  ,  running `composer fix-recipes ` seems to fix the issue, however it seems that I even need to run this command in CI (which feels "not right" ? ) , am I missing something ?

**Comment by krazygit** [comment]
> I'm having the same issue in symfony 4.4, and googling only refer this issue so I post here, on a fresh install of my project, the bin/phpunit is not installed (though I do have `symfony/flex` ) , running `composer fix-recipes ` seems to fix the issue once, however now in CI it does not work (it tells me there's no recipes to install )

same here, composer fix-recipes fixes in local but still an issue for CI

**Comment by allan-simon** [comment]
In the meantime, I resolved the issue I had, it was due to the project existing for quite sometime, and  bin/phpunit was in the gitignore (not explicitly but all bin except console were ignore) ,  commiting bin/phpunit solved the issue

**Comment by krazygit** [comment]
> In the meantime, I resolved the issue I had, it was due to the project existing for quite sometime, and bin/phpunit was in the gitignore (not explicitly but all bin except console were ignore) , commiting bin/phpunit solved the issue

Oh thanks a lot, ...
Before migration to SF4, SF3 added phpunit to gitignore  to use simple-phpunit

**Comment by allan-simon** [comment]
I feel good to know that I saved you all the hair pulling :P
