### ISSUE TITLE
[Translation] Automatically replace single placeholder with non-keyed parameter array

### ISSUE THREAD

**Issue by samdjstevens** [symfony/symfony#28369]
**Description**  

I have found that many of my translations often contain only a single placeholder, e.g `Welcome %name%!`.

Currently, to translate this message, a call like the following needs to be made:

```
$translator->trans('welcome_msg', ['name' => $myName]);
```

I propose to implement detection for this "single placeholder scenario" when translating messages, and allow the user to pass in an array containing a single value, not keyed by the placeholder name.

This of course would only work if the user has used the suggested format of `%key%` for their placeholders, something which might be confusing to the user when this does not work as desired.

This would only save a few keystrokes, but when translations are used heavily throughout a Symfony project, it could be a nice feature.

**Example**  

The previous example could not be written as:

```php
$translator->trans('welcome_msg', [$myName]);
```

or in a Twig template as:

```
{{ 'welcome_msg' | trans({myName}) }}
```

**Comment by nicolas-grekas** [comment]
Can't you use `%0%`? (I didn't check :))

**Comment by samdjstevens** [comment]
@nicolas-grekas nice, I didn't think of that. It does indeed work. The only downside I guess is that the translation isn't as descriptive with the`%0%` placeholder (over say `%name%`) but this alone probably doesn't warrant the feature be re-implemented. Will close the issue!
