### ISSUE TITLE
[DoctrineBridge] Dev mode warmups proxy classes for mappedSuperclass, prod does not

### ISSUE THREAD

**Issue by blackandred** [symfony/symfony#28379]
**Symfony version(s) affected**: 4.1.2

**Description**  
Hello, I'm developing an application with an **inherited structure of modules -> components** (DDD like).
I felt an inconsistency between `dev` and `prod` mode, the invalid code was working in `dev` but when running in `prod` was showing runtime errors (not on build stage).

**How to reproduce**  
I suspect this situation (it is incorrect in my perspective):

> Given we have a structure

```
Core/AbstractEntity // mappedSuperclass
SomeModule/Common/AbstractEntity  // mappedSuperclass
SomeModule/DragDrop/Entity // Entity
SomeModule/ElementCreation/Entity // Entity
SomeOtherModule/ElementCreation/Entity // Entity
```

> 1. **SomeModule/Common/AbstractEntity/User has relation to SomeModule/Common/UserGroup** - but it's a mistake, common/shared things should not have relations
> 2. I fetch DragDrop/User that extends CommonUser and do User->getGroup() // will return a PROXY CLASS FOR `mappedSuperclass`?

The problem is that in `dev` mode the proxy class for `mappedSuperclass` was generated... but it shouldn't or I'm wrong?

In `prod` mode the cache warmup was green, but the application were saying that failed to include() a non-existing file (it was trying to include a proxy class for `mappedSuperclass`

```

Fatal error: require(): Failed opening required '/builds/xxx/xxx/var/cache/prod/doctrine/orm/Proxies/__CG__AppDomainSomeModuleCommonComponentEntityClient.php' (include_path='/builds/xxx/xxx/vendor/pear/console_getopt:/builds/xxx/xxx/vendor/pear/db:/builds/xxx/xxx/vendor/pear/file:/builds/xxx/xxx/vendor/pear/pear-core-minimal/src:/builds/xxx/xxx/vendor/pear/pear_exception:.:/usr/local/lib/php') in /builds/xxx/xxx/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 212
```

**Possible Solution**  
Make the `dev` validation better in this case?

**Comment by stof** [comment]
I think that's a bug in DoctrineBundle, in the special autoloader registered to autogenerate proxy classes. It should exclude mapped superclasses.

**Comment by blackandred** [comment]
Should I repost this somewhere else and (or not) close this issue there?

**Comment by xabbuh** [comment]
@blackandred Can you resubmit it [here](https://github.com/doctrine/DoctrineBundle)? Thank you! Closing here as this does not seem to be a bug in the Doctrine bridge.
