### ISSUE TITLE
@validator service is instance of TraceableValidator instead of RecursiveValidator

### ISSUE THREAD

**Issue by lelledaniele** [symfony/symfony#28378]
**Symfony version(s) affected**: 3.4.11

**Description**

Hi All,

My Service
![screenshot from 2018-09-06 09-26-08](https://user-images.githubusercontent.com/6173422/45144764-f1946a80-b1b6-11e8-986e-2739c9a15981.png)

I have an old codebase that I moved into SF 3.4 and one test was falling....
During my debug process I found that `validator` service is not instance of `RecursiveValidator` but is `TraceableValidator` instead

```
<service id="validator" class="Symfony\Component\Validator\Validator\ValidatorInterface" public="true">
     <factory service="validator.builder" method="getValidator" />
</service>
```
`@validator` is comming from `getValidator` method of `validator.builder` service.
`validator.builder` service is `Symfony\Component\Validator\ValidatorBuilder` calss that implemets `Symfony\Component\Validator\ValidatorBuilderInterface` interface.
`getValidator` method always return `return new RecursiveValidator` line 329.

Why `validator` service is instance of `TraceableValidator` in the cache?
![screenshot from 2018-09-06 08-40-40](https://user-images.githubusercontent.com/6173422/45144728-d7f32300-b1b6-11e8-9671-d993029306db.png)

Many thanks for your time,
Lelle

**How to reproduce**  

- Create a service
- Autowire `ValidatorInterface`
- You will get `TraceableValidator` obj instead of `RecursiveValidator`

**Comment by stof** [comment]
that's totally expected. Our contract is that it implements `Symfony\Component\Validator\ValidatorBuilderInterface`. Which implementation is used depends on the config (in dev, we will decorate the validator with a TraceableValidator one)

**Comment by stof** [comment]
@lelledaniele as you closed it, I indeed thought that you might have figured it out by yourselves. But writing an answer explicitly was not taking me a lot of time here (as I was already on the issue anyway and looking at the reason), but it would make a huge difference for someone else running in the same issue than you later and finding this issue when searching.
