### ISSUE TITLE
[Messenger] Add Enhancer for Sleeping on Idle

### ISSUE THREAD

**Issue by ragboyjr** [symfony/symfony#28386]
Currently, the AmqpExt Transport will send a null envelope and then sleep when the connection returns no items to process.

I think that sleep part of the code could be implemented via a Transport Enhancer. If we moved it to a transport enhancer, we could then share this sleeping logic and configuration across any transport made.

This would be a rough example of what that receiver would look like.

```php
class SleepOnNullEnvelopeReceiver implements ReceiverInterface
{
    private $decoratedReceiver;
    private $idleTime;
    private $logger;

    public function __construct(ReceiverInterface $decoratedReceiver, int $idleTime = 200000, LoggerInterface $logger = null)
    {
        $this->decoratedReceiver = $decoratedReceiver;
        $this->idleTime = $idleTime;
        $this->logger = $logger;
    }

    public function receive(callable $handler): void
    {
        $this->decoratedReceiver->receive(function (?Envelope $envelope) use ($handler) {
            $handler($envelope);

            if (null === $envelope) {
                usleep($this->idleTime);
            }
        });
    }
    
    public function stop(): void
    {
        $this->decoratedReceiver->stop();
    }
}
```

**Comment by sroze** [comment]
Yes, you are right; it could definitely be the case! 

Though... maybe this "sleep" mechanism is only required for the Amqp transport? I wish other transports will have a way of "waiting for a message" (anything more or less based on Unix's `select`) so that we don't need to loop and wait at all :)

**Comment by ragboyjr** [comment]
I think the sleep mechanism is more useful in a generic sense where you might have a low traffic queue that you now will only retrieve elements every few minutes, so maybe to save resources, instead of pinging the transport every 5 seconds, you configure it to check every 60 seconds.

Other transports like redis or sqs do provide a long polling type of mechanism, but definitely could imagine any custom type transports not doing that.

Another example where this might come into play would be if you wanted to check an FTP server for files (which is something done all the time when integrating with financial systems or legacy software). Using the sleep enhancer, you could easily configure it in a standardized way to wait before checking again.

**Comment by sroze** [comment]
Closing as it's been moved to [the `Worker` class](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Worker.php#L109). Thank you for suggesting this though 👌
