### ISSUE TITLE
Route not found doesn't send Exception but redirect (ERR_TOO_MANY_REDIRECTS)

### ISSUE THREAD

**Issue by JonathanMartel** [symfony/symfony#28382]
Hi, 

After updating from 4.0.6 to 4.1.4, the symfony router doesn't get the "no route exception", but send a redirect (301) response multiple times, leading to a ERR_TOO_MANY_REDIRECTS error in the browser. 

Documentation isn't clear about the catching of Bad route exception.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by JonathanMartel** [comment]
I'm working on that!

**Comment by JonathanMartel** [comment]
My fault. I had a RedirectController to take care of the trailing slash! Sorry!

**Comment by xabbuh** [comment]
Thank you for the feedback @JonathanMartel. 👍
