### ISSUE TITLE
Out of memory error when installing EasyAdminBundle with Composer

### ISSUE THREAD

**Issue by rjcalifornia** [symfony/symfony#28383]
**Symfony version(s) affected**: 3.4.15

**Description**  
This is related to this one: https://github.com/EasyCorp/EasyAdminBundle/issues/2334

When you try to install the EasyAdminBundle, it start looking for dependencies, and Composer runs out of memory. I found that it might be related to the version of Symfony, because after changing memory limit in PHP.ini, and using a different computer, I tried in a project that I am working on using version 3.4.6 and I installed it without issue

**How to reproduce**  
Create a new Symfony app with the latest version (3.4.15)
Run composer to install easycorp/easyadmin-bundle
Updating dependencies
PHP Fatal Error: Out of memory

**Possible Solution**  
Use another version??

**Comment by nicolas-grekas** [comment]
You need to use symfony/flex and restrict the range of allowed symfony versions using the extra.symfony.require configuration entry in your composer.json file. See e.g. https://github.com/symfony/skeleton/pull/93/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R56

**Comment by rjcalifornia** [comment]
Forgot to mention, this happens using the Symfony Installer

**Comment by xabbuh** [comment]
There's not much we can do in Symfony about that. But you can also set the environment variable `COMPOSER_MEMORY_LIMIT` to `-1` to allow Composer to consume as much memory as necessary.

**Comment by nicolas-grekas** [comment]
Closing as there is nothing more we can do here, this is a Composer issue. Flex works around it, another reason to use it.
