### ISSUE TITLE
Eliminate untyped `@return array` occurrences

### ISSUE THREAD

**Issue by Majkl578** [symfony/symfony#28390]
### Description

```
$ git grep -P '@(param|return)\s+array\b' src/ | wc -l
845
```

There is **a lot** of untyped arrays in parameter and return types in phpDocs.

Using `array` is unhelpful and doesn't say what the array contains or what is expected.
Also doesn't help static analysis as `array` implicitly means `mixed[]`, although in reality it's often an array of specific values, not `mixed`s.

### Proposal

Replace all occurences of `@return array` and `@param array` with the actual contents of these arrays, e.g. `int[]`, `string[][]`, `Header[]`.
For compatibility reasons I'd advice to avoid more advanced syntax as `array<string, Header>` as this breaks tooling (i.e. PhpStorm type inference).

---

This is a follow-up of the following Twitter thread:
https://twitter.com/asgrim/status/1037608448362467328
https://twitter.com/Majkl578/status/1037726994740461573

important part:
![](https://user-images.githubusercontent.com/144181/45224718-f04c6600-b2ba-11e8-97d3-e92ff9a88a78.png)

**Comment by muglug** [comment]
I've created a tool that adds infers return types and updates the code itself: https://github.com/vimeo/psalm/blob/master/docs/fixing_code.md

**Comment by nicolas-grekas** [comment]
We're always keen to accept docblock improvements. PR(s) welcome.
I'm closing because there is no need to keep track of this.
Thanks for asking.

**Comment by ondrejmirtes** [comment]
Really, @nicolas-grekas? :( Having types above methods is really beneficial for DX, do you not understand this?

**Comment by nicolas-grekas** [comment]
Maybe my English skills are at fault, but I just wrote that we've always been accepting docblock improvements. What else did you read?

**Comment by ondrejmirtes** [comment]
On the second reading of your message, I now understand your intentions. I think it may mistakenly be read as "don't bother with sending PRs with more specific array types, I won't accept it" - the number of "thumbs down" on that message certainly indicates that.

Now I get it - there's no need for this issue to be open, anyone can send a PR and it's gonna be fine :)

I'm sorry for my reaction and I'm looking forward to PRs sent in by contributors that improve this area!

**Comment by Majkl578** [comment]
>  I don't get the downvotes either.

My downvote is for closing a valid issue and general disagreement with "_there is no need to keep track of this._".

`array` is same as `mixed[]` which is rarely the correct type, so these documented types are wrong -> bug in my opinion.

**Comment by Majkl578** [comment]
Btw I think this issue would be a great candidate for Hacktoberfest.

**Comment by Majkl578** [comment]
ping @jwage 
cc @fabpot

**Comment by Majkl578** [comment]
ping @nicolas-grekas
cc @fabpot
