### ISSUE TITLE
[RFC] Require strict typing for new components and/or classes

### ISSUE THREAD

**Issue by alcaeus** [symfony/symfony#28423]
With Symfony 4 requiring PHP 7.1, strict typing could be introduce to reduce potential bugs, help with documentation and make the code more robust in general. However, since most of the code in Symfony also needs to run on older PHP versions until 2021 (when Symfony 3.4 is EOL'd), it's not yet practical to enforce strict typing in existing code, even for Symfony 5 where BC breaks would be acceptable.

To work around this issue, strict typing could be required for new components (e.g. the `messenger` component), since they won't be ported to a Symfony version designed to run on PHP < 7.1. Optionally, the requirement could be extended to new classes for existing components to ensure new code is strictly typed in general: in most cases, new classes even for existing components wouldn't be ported to older Symfony versions. If so, the requirement should be relaxed for those cases.

What would strict typing entail:
* `declare(strict_types=1)` on top of the file to completely disable type coercion,
* scalar type hints (including nullable, `void`, excluding `object` since PHP 7.2 isn't required)
* Strict comparisons should be the norm with operators like `==` and `!=` only being used in exceptional cases.

**Comment by Pierstoval** [comment]
I'm totally in favor of this proposal :+1: 

Considering the fact that using these strict types would probably need thousands of instructions like `if (!\is_{type}($data)) { @trigger_error(...); }`, maybe it could be considered nice to start working on this for new features that are coming in 4.2/4.3/4.4 (this basically means that strict typing could be enforced for Symfony 4 but only for new features), and discuss about how it could be possible to handle the strict types for the existing code base either for Symfony 4 or for Symfony 5 (that will be released in November 2019, so we have a bit more than a year for this job).

What I'm thinking about for the current codebase is the fact that lots of people are wishing to contribute to the framework but don't know where to tart: anyone could easily start contributing by deprecating loose-types with simple ifs&trigger_error statements, making things a bit easier for the core team to work on this.

WDYT?

**Comment by stof** [comment]
I'm not sure what `declare(strict_types=1)` will bring us yet (but that's purely internal anyway, as that applies per-file and so does not impact our users).

But I agree we should rely on stricter typehints for all new APIs

**Comment by Pierstoval** [comment]
Strict types can have sile to offer in terms of user responsibility for public APIs, but I agree that for private/internals it can be of poor interest. I'm personally talking mostly about public API rather than internals.

**Comment by alcaeus** [comment]
> that's purely internal anyway, as that applies per-file and so does not impact our users

Yes it does. Consider the following examples:
* No strict typing: https://3v4l.org/25pmB
* With strict typing: https://3v4l.org/VMI9J

There is a huge impact for the users, the change is everything but internal. However, for new APIs this should definitely be enabled. Due to its potential BC breaks, it should not be enabled for code covered by the BC promise.

**Comment by stof** [comment]
@alcaeus strict type is per file. And for calls, it is the mode of the *calling* file impacting the strictness, not the definition file. So your case is about whether *their* code makes it strict.

**Comment by nicolas-grekas** [comment]
I think we already strive for using scalar type hints and strict comparisons as much as possible, so no need to discuss this IMHO, it's already happening, isn't it?

Which leaves `declare(strict_types=1)`. As @stof pointed, this would be absolutely invisible from the outside. So not sure myself also what the benefit would be.

**Comment by alcaeus** [comment]
> And for calls, it is the mode of the calling file impacting the strictness, not the definition file.

My apologies, I had remembered it backwards: I was under the impression that the defining code gets to decide that. Makes sense though since the defining code gets an argument of the respective type anyways.

**Comment by stof** [comment]
@alcaeus it is always the file controlling the value that defines strictness. So for arguments, it is the calling file. And for return types, it is the defining file.

**Comment by dkarlovi** [comment]
>  what the benefit would be

Raising issues within Symfony code itself? The same idea as behind static code analysis, basically.

**Comment by stof** [comment]
The question is how many it would actually catch.

**Comment by dkarlovi** [comment]
From [my initial experience with PHPStan + Symfony](https://github.com/symfony/symfony/pull/25536), Symfony's codebase is of very high quality **for a codebase without static analysis** .

But, [it **did** contain trivial errors](https://github.com/symfony/symfony/pull/25558) (far fewer than I'd expect from a codebase of this size and complexity :+1: ) which just pops up with adding strictness after the fact in any case. Note, we haven't even scratched the surface there, not even passing level 0 checks.

**Comment by vasilvestre** [comment]
> As @stof pointed, this would be absolutely invisible from the outside. So not sure myself also what the benefit would be.
The benefit is that writing good code is what Symfony make, strict type have to become more and more popular in PHP world and I think it's nice for your reputation. Maybe I'm wrong, but Symfony being a member of PHP FIG should recommand strict type..
What do PHP FIG think about strict type ? MUST ? SHOULD ?

**Comment by stof** [comment]
@dkarlovi your comment is actually an argument in favor of adding phpstan to our CI more than to enabling `strict_types` I would say :smile: None of the trivial errors in the PR you linked would have triggered an error when using `declare(strict_types=1)`.

Note that I'm not opposed to using `declare(strict_types=1)`. but I think it is often overrated.

**Comment by dkarlovi** [comment]
@stof absolutely :100: but why not both? PHPStan can also have issues (not discovering every last thing) which your test suite might find by enabling strict type, for example.

**Comment by chalasr** [comment]
Using it partially would put some inconsistency in our codebase , raising one more question for first-time contributors. Not sure it's worth it

**Comment by jvasseur** [comment]
There is one case where `strict_types` can affect users: callbacks

This following example will raise an error where it wouldn't without strict types:
```php
// Some user file
symfonyFunction(function (int $foo) {
});


// Some symfony file
declare(strict_types=1);

function symfonyFunction($callback) {
    $callback('3');
}
```

Since we use a lot of callbacks is some component this could have a huge impact if we blindly add strict types to all our files.

I'm all for more strictness but we have to be careful on this one.

**Comment by nicolas-grekas** [comment]
:-1: on my side: "declare strict" is a purely internal thing with no practical implication on the API side, except unwanted ones (see the previous comment). The hard part in maintaining Symfony is moving the public API forward - internal strictness is almost never an issue - and if it is, it is usually quickly spotted and fixed.

**Comment by fabpot** [comment]
👎 from me as well on `declare strict`.

**Comment by alcaeus** [comment]
While I don't agree with them, I accept your opinions. - maybe we can revisit this when the last Symfony version that supports PHP < 7 is no longer supported.

**Comment by djmattyg007** [comment]
@fabpot It would be good to at least understand why you're against use of `declare(strict_types=1);`

**Comment by BafS** [comment]
> @fabpot It would be good to at least understand why you're against use of `declare(strict_types=1);`

I would be keen to know why too. Especially with the v7.

**Comment by nicolas-grekas** [comment]
https://github.com/Girgias/unify-typing-modes-rfc is a good analysis of why strict types doesn't improve anything.
