### ISSUE TITLE
Csrf FormError does not have a cause value.

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#28427]
**Description**  
Shouldn't the Csrf FormError added when a Csrf token is invalid have a `cause`?

Check the line [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php#L69)

**Example**  
Something like:
`$form->addError(new FormError($errorMessage, null, null, [], new ConstraintViolation(....)));`

**Comment by xabbuh** [comment]
In the context of that listener there is not really an object that would serve the purpose of a cause here. But in my opinion that's okay as the error message is clear enough.

**Comment by gmponos** [comment]
I have a usecase that in the view I need to display the form with any errors that happened.

If there is a CSRF error I need **not** to display the CSRF error message to the user and in cases there is only a CSRF error do not display any Error message at all and display just the form.

In the controller the form still needs to be invalid in case CSRF error occurs so I can not totally disable the CSRF protection.

The error message can be set by the developer so the error message it allowed to be different in various cases so it is not feel safe to filter the error message in the view by the message. The only thing that feels safe is the cause.

**Comment by gmponos** [comment]
Hello,

I saw that you guys added the `Feature` label.. so do you believe this is a valid case.. Shall I start working on PR?

**Comment by xabbuh** [comment]
Introducing something like a new `CsrfValidationError` class does not look bad to me.
