### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by gbenfe** [symfony/symfony#28421]
**Symfony version(s) affected**: 4.1.4

**Description**  
**Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)**

**Possible Solution**  
    /**
     * @throws InvalidArgumentException If a locale contains invalid characters
     */
    public function __construct(**REMOVE ?**string $locale, MessageFormatterInterface $formatter = null, string $cacheDir = null, bool $debug = false)
    {

**Comment by stloyd** [comment]
@gbenfe Seems like you installed (run) Symfony Translator component on unsupported PHP version:
https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Translation/composer.json#L19

**Comment by gbenfe** [comment]
I've apologized, I had a misconfiguration in my system using multiple PHP versions. Now it works.
