### ISSUE TITLE
i wish to ignore LDAP server disconnected error 500

### ISSUE THREAD

**Issue by yedprior** [symfony/symfony#28426]
Hello ,
can we have an `@` for ldap_start_tls in  file vendor/symfony/ldap/Adapter/ExtLdap/Connection.php line 140 pls?

https://github.com/symfony/symfony/blob/deae538245655b2ef6123b729c095a54238c6113/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php#L140-L142

**Comment by iltar** [comment]
The php function is undocumented, but it seems to be able to throw warnings according to the source:

 https://github.com/php/php-src/blob/8ca1f47a7a25f61fcc63313a771e6922e3258046/ext/ldap/ldap.c#L3687

**Comment by chalasr** [comment]
Looks sensible to me then, that would be consistent with similar calls.
PR welcomed, for 2.8 I guess.

**Comment by yedprior** [comment]
Hello,
Yes i get a warning if the ldap server is not available.
But maybe it's a setting problem.

Le lun. 10 sept. 2018 à 20:20, Robin Chalas <notifications@github.com> a
écrit :
