### ISSUE TITLE
symfony - cache - memcached - key versionning

### ISSUE THREAD

**Issue by soleuu** [symfony/symfony#28445]
**Symfony version(s) affected**: >=3.3

**Description**  
Implementation of MemcachedAdapter use "key versionning" (see MemcachedTrait::init)
Implementation of version in cache/Adapter/AbstractAdapter.php use 1 key for global versionning.
This implementation is like tagging witch is not advised with memcached. (see constructor comment on Symfony\Component\Cache\Adapter\MemcachedAdapter)

The problem here is : what happen when the versionning key expires or is evicted from cache ?  
Response : we get older version of cache !

I clearly understand why the actual implementation is interresting on shared memcached : we simply invalidate key for the application without flushing cache of other application. But versionning in that context should be an option and should not be activated by default.

**How to reproduce**  
- store some key on memcached
- flush the cache with symfony command line
- store different values on same key
- manually delete the version key to simulate LRU or eviction
- now you should get old version of your memcached keys

**Possible Solution**  
MemcachedAdapter should not use versionning ! 
Memcached shoud flush the cache when clear command is called !
Or
add option to activate/inactivate key versionning 
=> need to flush when versionning is off

**Comment by nicolas-grekas** [comment]
Thanks for the report. It's strange that the versioning key is being evicted: I would have thought that thanks to LRU, it would always be one of the most recently used one. Anyway, reading https://github.com/memcached/memcached/wiki/ProgrammingTricks#deleting-by-namespace, there is a bug in the implementation: the (re)starting offset should be the current timestamp, while it is always zero right now. That' an issue that should be fixed on 3.4.
About adding an option to disable namespacing, I'm fine with it, as a new feature, against master this time.
Would you be up to submit these as 2 new PRs?

**Comment by soleuu** [comment]
The timestamp will not resolve everything.

Context:
think about one pool with multiple instance of memcached.
- store some datas
=> The version key is stored on server1 for exmple.
- server1 is innaccesible during some times (no restart, just server hang or network problem)
=> now new version key is stored on server2 
- do some clear if you want
- store new values
- server1 come back (problems are stopped)
- all values will be outdated

**Comment by nicolas-grekas** [comment]
Sure, I never said the contrary. We still want to provide a working clear function by default, which means using namespaces. Have an empty cache in some edge case is an acceptable outcome.

**Comment by soleuu** [comment]
Empty cache is not a problem for me, I agry with you.

but i think you dont understand that when servers1 comme back, you will get old version.
because the version key on server2 will not be read any more and here is the problem. The version key will downgrade !

**Comment by nicolas-grekas** [comment]
The downgrade is what using a timestamp would fox isn't it?

**Comment by soleuu** [comment]
The timestamp won't fix the second case I explained. The version key will go back to a previous version.
Consequently, the cache will serve outdated datas.

PS : when i said downgrade in a previous comment, i would have written, "the version come back to a previous version".

**Comment by nicolas-grekas** [comment]
But the probability of going back to an exact timestamp is zero, timestamps are always increasing.

**Comment by nicolas-grekas** [comment]
Let's fix the versioning at least. Would you like to gove it a try?

**Comment by nicolas-grekas** [comment]
Fixed in #28561
