### ISSUE TITLE
[Workflow] may github and composer installs different versions of symfony/workflow?

### ISSUE THREAD

**Issue by sensorario** [symfony/symfony#28442]
**Symfony version(s) affected**:
v3.4.15

**Description**  
The component symfony/workflow may generate unexpected exception in Registry.php at line 56. In that line there is a trigger_error. Error I got is 

> [2018-09-07 09:07:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Workflow\Exception\InvalidArgumentException: "At least two workflows match this subject. Set a different name on each and use the second (name) argument of this method." at /Users/sensorario/Development/****/****/****/vendor/symfony/workflow/Registry.php line 56 {"exception":"[object] (Symfony\\Component\\Workflow\\Exception\\InvalidArgumentException(code: 0): At least two workflows match this subject. Set a different name on each and use the second (name) argument of this method. at /Users/sensorario/Development/****/****/****/vendor/symfony/workflow/Registry.php:56)"} []

**How to reproduce**  
Error is caused just in version 3.4.15. In my configuration I've different workflows for same entity. May this be the cause of the problem?

**Possible Solution**  
Actually I've downgraded symfont/workflow to version v3.4.14 and with this version it works.

**Additional context** 
 ![schermata 2018-09-11 alle 12 21 58](https://user-images.githubusercontent.com/820248/45354559-2c830d80-b5be-11e8-86a3-048b0c4707ab.png)
I am working with symfony/symfony
 v3.4.15 version. `git diff v3.4.14..v3.4.15` is empty. Version installed with `composer symfony/workflow v3.4.15` is different from https://github.com/symfony/workflow/blob/v3.4.15/Registry.php.

**Comment by nicolas-grekas** [comment]
would you mind checking with the latest (unreleased) 3.4 please?

**Comment by sensorario** [comment]
The latest is v3.4.15

**Comment by nicolas-grekas** [comment]
I mean `3.4.16@dev`

**Comment by sensorario** [comment]
[2018-09-11 12:32:01] request.CRITICAL: Uncaught PHP Exception PHPUnit_Framework_Error_Warning: "trigger_error() expects parameter 1 to be string, object given" at /Users/sensorario/Development/xxxx/xxxx/xxxx/vendo
r/symfony/symfony/src/Symfony/Component/Workflow/Registry.php line 56 {"exception":"[object] (PHPUnit_Framework_Error_Warning(code: 2): trigger_error() expects parameter 1 to be string, object given at /Users/sensorario/Development/beanstalkapp.com/mtdistribution?xxx/vendor/symfony/symfony/src/Symfony/Component/Workflow/Registry.php:56)"} []

**Comment by sensorario** [comment]
Ok but, ... where is 3.4.16? I mean, ... not in github nor in packagist is visibile version 3.4.16 ...

**Comment by sensorario** [comment]
And "minimum-stability" does not accept boolean value. I guess right value should be "dev"

**Comment by nicolas-grekas** [comment]
Maybe related to https://github.com/symfony/symfony/issues/28432?

**Comment by sensorario** [comment]
No, ... but now it works. So, ... if someone will get an error on row 56 in Register.php of Symfony/Workflow component have just to

 - add "minimum-stability": "dev" configuration
 - add "symfony/workflow": "~3.4.16@dev" require
 - composer update
