### ISSUE TITLE
DateTime passes validation in form collection when using DateTimeType with single_text

### ISSUE THREAD

**Issue by alex2005git** [symfony/symfony#28455]
**Symfony version(s) affected**: 4.1.4

**Description**  
I have these 2 entities, Test and TestTest.
TestTest has 2 datetime fields, datetimeStart, and datetimeEnd, both `@Assert\NotBlank()` and `@Assert\DateTime()`
TestTest has a ManyToOne relation to Test.
TestType sets testTests as a collection of TestTestType and TestTestType has datetimeStart, and datetimeEnd both as `'widget' => 'single_text', 'date_format' => 'yyyy-MM-dd HH:mm:ss',`

If we go to `test_new` (index redirects here) and submit the form without data we see that not blank works https://i.imgur.com/D8QZvCg.jpg

Reset the page, and set the datetimeStart (or end) to `test`, and it shows correctly that the value is not valid https://i.imgur.com/YKmhilM.jpg

Reset again and set the datetimeStart to `a`, `m`, `y`, `x` whatever character and it gets transformed to a date and passes validation https://i.imgur.com/uo7VvbW.jpg

I don't think this is intended behaviour... What I need it to do is DateTimeValidator should check for the value (`x`) in this example, and return an error that the format is not valid

**How to reproduce**  
https://github.com/alex2005git/symfony_form_validator_datetime
Clone the repo, modify `.env` with the DATABASE_URL and database name `symfony_form_validator_datetime` and run `composer initDB` to create the table and update the schema

**Comment by alex2005git** [comment]
Also whatever format I put in the entity, like `@Assert\DateTime(format="d/m/Y H:I:s")` or in the form type `'date_format' => 'dd/MM/yyy HH:mm:ss',` this date `2018-09-12 11:57:44` still passes just fine

**Comment by ro0NL** [comment]
Validating a `\DateTimeInterface` with `DateTimeValidator` is now deprecated :) see #25015

**Comment by alex2005git** [comment]
@ro0NL Tried it with `@Assert\Type("\DateTime")` and this doesn't change anything

**Comment by ro0NL** [comment]
I'm not sure i follow your problem. Any `\DateTime` value is a valid date time by definition (hence we deprecated validating those using `DateTimeValidator`).

**Comment by alex2005git** [comment]
I'm not sure you read my original comment about the string `x` passing as a valid date time, and being transformed to a datetime object, shouldnt the datetime validator validate the format since the default is `Y-m-d H:i:s` per https://symfony.com/doc/current/reference/constraints/DateTime.html ?
What's the point of having a DateTime constraint, with passing a format if the format gets ignored, in my case using `'widget' => 'single_text'` in `DateTimeType`

**Comment by xabbuh** [comment]
@alex2005git Can you confirm that #28466 fixes the issue for you?

**Comment by alex2005git** [comment]
@xabbuh It does seem to make `a` return an invalid value.
However the field doesn't seem to validate datetimes of format `Y-m-d H:i:s` as set in `Assert\DateTime` by default, it always needs format `Y-m-dTH:i:sZ`  

I'm confused as to how I am supposed to validate date time fields (they could also have different formats other than the default, ie: `@Assert\DateTime(format="d/m/Y H:i")`) :/
