### ISSUE TITLE
Symfony Form(edit) with Attachemnt File(File Upload)

### ISSUE THREAD

**Issue by shubaivan** [symfony/symfony#28454]
I reproduced this example from cookbook 
https://symfony.com/doc/current/controller/upload_file.html
I have problem with edit form and I not undertand how to solve this problem ?

After submit edit form I still have null in field brochure from example :(

I create entity with attachment file, field brochure, after that I had file name in db in field brochure.
Then I open edit form, nothing changing, just submit, before in action did that part:

    $product->setBrochure(
        new File($this->getParameter('brochures_directory').'/'.$product->getBrochure())
    );

and after submitted form in action

    if ($form->isSubmitted() && $form->isValid()) {
        try {
            $em = $this->getDoctrine()->getManager();
            /** @var Application $entity */
            $entity = $form->getData();
            $fileApp = $entity->getBrochure(); // null

I reproduced this example from cookbook 
https://symfony.com/doc/current/controller/upload_file.html
I have problem with edit form and I not undertand how to solve this problem ?

After submit edit form I still have null in field brochure from example :(

I create entity with attachment file, field brochure, after that I had file name in db in field brochure.
Then I open edit form, nothing changing, just submit, before in action did that part:

    $product->setBrochure(
        new File($this->getParameter('brochures_directory').'/'.$product->getBrochure())
    );

and after submitted form in action

    if ($form->isSubmitted() && $form->isValid()) {
        try {
            $em = $this->getDoctrine()->getManager();
            /** @var Application $entity */
            $entity = $form->getData();
            $fileApp = $entity->getBrochure(); // null

why null ? How to create edit form after submit it fields with attachment file will return exist data ?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
