### ISSUE TITLE
Server channel error / Symfony/Messenger

### ISSUE THREAD

**Issue by henri9813** [symfony/symfony#28468]
**Symfony version(s) affected**: x.y.z

**Description**  
I got this error running `php bin/console messenger:consume-messages`
```
In Connection.php line 156:

  Server channel error: 406, message: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'gray
  log_queue' in vhost '/': received 'true' but current is 'false'
```

**How to reproduce**  
create a non-durable queue in rabbitMQ .And try to connect it you will get this error.

*Additional context**  
My queue was previously generated by a graylog plugin so the edition of this queue is not possible.

**Comment by AchillesKal** [comment]
Hey, I was able to reproduce this, I also noticed that the same thing happens for a transient exchange.
```
Error thrown while running command "messenger:consume-messages amqp". Message: "Server channel error: 406, message: PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'test_test' in vhost '/': received 'true' but current is 'false'" In Connection.php line 154:
```

**Comment by sroze** [comment]
You can configure the [`flags` option](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L73) to override the default (which [is durable](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L376)). This should fix your issue :)

**Comment by henri9813** [comment]
Thanks it should be, i will try it in my future's project. Currently i was forced to use RabbitMqBundle by amqp-lib.

Thanks @sroze for your answer ! :+1:

**Comment by NikoGrano** [comment]
@sroze I tried to set queue as non durable, but couldn't do that. Can provide example or/and update documentation?
