### ISSUE TITLE
[YAML][lint] Can not lint !tagged 

### ISSUE THREAD

**Issue by lsv** [symfony/symfony#28465]
**Symfony version(s) affected**: 4.1 (possible 3.4, where !tagged got introduced)

**Description**  
If you use `!tagged` in your yaml file, as described under [Reference tagged services](https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services)

`bin/console lint:yaml config` will throw

```
  ERROR  in config/services.yaml
  >> Tags support is not enabled. Enable the `Yaml::PARSE_CUSTOM_TAGS` flag to use "!tagged" at line 35 (near "- !tagged app.payment_method").
```

So the documentation is missing how to set the `Yaml::PARSE_CUSTOM_TAGS` flag, so its possible to actually lint yaml files.

**How to reproduce**  

Add

Create a `MyClass` under `src`

In services.yaml add the following

```
App\MyClass:
    tags: [!tagged app.myclass]
```

Run `bin/console lint:yaml config`

**Possible Solution** 
Always set the `Yaml::PARSE_CUSTOM_TAGS` when using `bin/console lint:yaml` or if without custom tags throws error, then try again but with `Yaml::PARSE_CUSTOM_TAGS`.

Or add a snippet to the documentation, so state how to set `Yaml::PARSE_CUSTOM_TAGS`

**Additional context**  
Full exception

```
-> % bin/console lint:yaml config

  ERROR  in config/services.yaml
  >> Tags support is not enabled. Enable the `Yaml::PARSE_CUSTOM_TAGS` flag to use "!tagged" at line 35 (near "- !tagged app.payment_method").

                                                                                                                        
 [WARNING] 49 YAML files have valid syntax and 1 contain errors.                                                        
```

**Comment by xabbuh** [comment]
If you want to treat YAML files that make use of tags as valid, you will have to also pass the `--parse-tags` option:

```
$ bin/console lint:yaml config --parse-tags
```

I am going to close here as this is the expected behaviour. Thank you for understanding.

**Comment by lsv** [comment]
@xabbuh indeed its fine, but maybe add it to the documentation then? With a little notice block or similar?
https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services

**Comment by xabbuh** [comment]
Not sure if that's the best place to add it. But we can of course discuss that. Would you like to create an issue in the documentation repository?

**Comment by driskell** [comment]
Hit this too

Possibly the error should be handled, and the error itself tell you that `--parse-tags` exists. I ended up here after some digging.

**Comment by xabbuh** [comment]
see #33651
