### ISSUE TITLE
Add event for pre-authentication

### ISSUE THREAD

**Issue by umulmrum** [symfony/symfony#28461]
**Description**  
For a security-related bundle I would like to react on user login attempt, both before and after authentication. There already are events to use after the authentication attempt, but none is dispatched before. In a project I would simply write a custom UserChecker and be fine with it. But for a (distributed) bundle it feels wrong to hijack the singular user checker option of a firewall as it leaves no room for a project-specific implementation (except decorating, but this means a developer cannot simply install the bundle).

I didn't find another existing way, so I suggest to dispatch a PreAuthenticationEvent (name to be refined) just before UserChecker::checkPreAuth() is called. This event could e.g. be used to intercept any authentication attempts in order to impose user-independent constraints like brute-force protection.

I'm not sure if it makes sense to limit listeners for this event to specific firewalls and how to do this, though. Also I'm not deeply familiar with the security component, so I'm sure there are implications I missed - this is an RFC anyway. Thanks for comments!

**Comment by iltar** [comment]
Seems to be somewhat related to #26050. Pre-authenticate while it makes sense, might introduce an event that passes raw passwords around.

**Comment by curry684** [comment]
Given that we just introduced the `SUCCESS_SENSITIVE` event through that PR I don't think we have fundamental issues with that. Essentially once you get to the point where you can hijack a PreAuthenticationEvent you could've also just hijacked `kernel.request` to the same effect.

However that also raises the reverse point - wouldn't this event be pretty much identical to just listening to `kernel.request`? The brute force example should imo only work on authentication failure, and we already have an event for that.

So while I'm not **against** the implementation I have trouble seeing the added value for it.

**Comment by umulmrum** [comment]
Well, listening to `kernel.request` means to execute the listener on each and every request which is something to avoid because of the performance impact.

Listening to authentication success or failure is also not possible. I'd like to stop attackers from even attempting to login by implementing the device cookie protocol (https://www.owasp.org/index.php/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies). Having the system behave differently on success or failure means the attacker can perform timing attacks even if the same response is returned (I'm no security specialist, so please correct if I'm wrong anywhere).

**Comment by curry684** [comment]
I'm not sure that approach is viable to embed deeply into the current security system. @wouterj plans to do some work on tokens that could be a better fit for that. If you can present a viable approach with PreAuthenticate used in a way that's not currently easily available the event is acceptable to me.

**Comment by umulmrum** [comment]
Please be aware that I just ask for the event, not for integration of device cookies (not sure if you assume this).
There's nothing to add from my perspective - `kernel.request` impacts performance, other events are too late, other extension points aren't generic enough to be used in a bundle.
If you think this event is a bad idea from a conceptual or technical point, reject the proposal, otherwise I'd be happy to have it (or a hint on how to solve this if there's already a suitable solution). Thanks!

**Comment by nieuwenhuisen** [comment]
I am also looking for something like this. I want to build a bundle for a brute force protector, now I copy-and-paste this code in the Guard class for different projects and I am looking for a reusable solution. 

- Before authentication I want to check if the login is blocked on username or IP-address (this will be a configuration option). If the authentication request is block I want to throw an LockedException.
- On authentication failure I can use the existing event to register a failed attempt.
- On authentication success I can use the existing event to reset the failed attempt counter.

**Comment by linaori** [comment]
@nieuwenhuisen I've always used the UserChecker to throw an exception when blocked. The failure/success I do the same way.

**Comment by nforced** [comment]
I just found this thread while looking for a way to block login attempts based on captcha result. So right now subscribing for the FOSUserEvents::SECURITY_IMPLICIT_LOGIN or SecurityEvents::INTERACTIVE_LOGIN events I can do captcha verification but this is post-auth and I want to avoid this db impact. To me it makes sense to have sort of PreAuthenticationEvent as @umulmrum suggests as it will make things way easier and elegant for such scenarios when one wants to prevent authentications based on other factors.

**Comment by wouterj** [comment]
I think this can be closed, as the experimental security system uses events and listeners to implement all core logic. Creating a listener on `CheckPassportEvent` with a higher priority than `UserCheckerListener` creates the requested feature in the issue description.

**Comment by DoobleD** [comment]
`CheckPassportEvent` seems to trigger only if there exist a user for the username provided when attempting to logging in. If it doesn't (e.g. someone is trying to bruteforce login trying any username), we thus can't do what this issue describes (e.g. perform IP checks).
