### ISSUE TITLE
Symfony 4.1.4 new project routing error

### ISSUE THREAD

**Issue by sjj1958** [symfony/symfony#28490]
**Symfony version(s) affected**: 4.1.4

**Description**  
Create new project with two controllers and get the requested URL was not found on this server.

**How to reproduce**  
1. create new symfony project:
composer.phar create-project symfony/website-skeleton test

2. open the new project folder
cd test

3. add annotations
composer.phar require annotations

4. create two controllers
bin/console make:controller aaa
bin/console make:controller bbb

5. attempt to access the default page
http://test.local/aaa
or
http://test.local/bbb

The default page http://test.local/ show just fine.

**Possible Solution**  

**Additional context**  
I have been using symfony since version 1.4 and currently using 2.8 so I'm understand it pretty well. I have cleared the cache, updated the project, ... Maybe I'm missing a step.

When I issue the following the routs show up:
bin/console debug:router

-------------------------- -------- -------- ------ ----------------------------------- 
  Name                       Method   Scheme   Host   Path                               
 -------------------------- -------- -------- ------ ----------------------------------- 
  aaa                        ANY      ANY      ANY    /aaa                               
  bbb                        ANY      ANY      ANY    /bbb                               
  _twig_error_test           ANY      ANY      ANY    /_error/{code}.{_format}           
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                      
  _profiler_home             ANY      ANY      ANY    /_profiler/                        
  _profiler_search           ANY      ANY      ANY    /_profiler/search                  
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar              
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                 
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                    
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                 
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router          
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception       
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css   
 -------------------------- -------- -------- ------ -----------------------------------

**Comment by xabbuh** [comment]
Which web server do you use? How did you configure it?

**Comment by sjj1958** [comment]
I config in apache using httpd-vhosts.conf and the hosts file. The default page shows up fine and if I update the routes.yaml file to point at either controller using just the "/" rout the page displays fine

<VirtualHost *:80>
  ServerName test.local
  ServerAlias test.local
  ServerAdmin aaa.bbb@cox.net
  ErrorLog "/websites/logs/test_error.log"
  LogFormat "%t \"%r\" %>s %b" common
  CustomLog "/websites/logs/test_access.log" common
  DirectoryIndex index.php
  DocumentRoot "/websites/test/public"
  <Directory /websites/test>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
    Require all granted
  </Directory>
</VirtualHost>

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost test.local
255.255.255.255	broadcasthost
::1             localhost

**Comment by sjj1958** [comment]
<VirtualHost *:80>
  ServerName test.local
  ServerAlias test.local
  ServerAdmin aaa.bbb@cox.net
  ErrorLog "/websites/logs/test_error.log"
  LogFormat "%t \"%r\" %>s %b" common
  CustomLog "/websites/logs/test_access.log" common
  DirectoryIndex index.php
  DocumentRoot "/websites/test/public"
  <Directory /websites/test>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
    Require all granted
  </Directory>
</VirtualHost>

**Comment by sjj1958** [comment]
![2018-09-17_08-06-03](https://user-images.githubusercontent.com/6873412/45631816-a00a9c00-ba50-11e8-912c-8f3448aa31bc.png)

**Comment by sjj1958** [comment]
![2018-09-17_08-08-02](https://user-images.githubusercontent.com/6873412/45631898-dfd18380-ba50-11e8-92ea-60797a7f1f53.png)

**Comment by stof** [comment]
do you have mod_rewrite enabled in Apache ? If no, nice URLs (without the `index.php/` in them) won't work.

**Comment by sjj1958** [comment]
Yes, it is enabled

**Comment by itsjakefromstatefarm** [comment]
I'm having exactly the same issue - same configuration, same steps to reproduce, reproduced issue on multiple machines. This is a showstopper and we can't get anything done until we can get this resolved. Any help would be appreciated.

**Comment by debreczeniandras** [comment]
I believe the <Directory> location should match to your document root.
Can you try adding the public folder to the end?
The .htaccess file is also in the public folder, so the allow override would not be useful anyhow in your case.

**Comment by sjj1958** [comment]
I just tried it, same issue

**Comment by debreczeniandras** [comment]
And like this? 
test.local/index.php/aaa

**Comment by xabbuh** [comment]
Did you also perform the step described at https://symfony.com/doc/current/setup/web_server_configuration.html#adding-rewrite-rules?

**Comment by sjj1958** [comment]
my apache httpd-vhosts.conf file was fine as shown above. Here is my create new project process:

composer.phar create-project symfony/website-skeleton test
composer.phar require symfony/apache-pack

bin/console make:controller aaa
bin/console make:controller bbb
bin/console make:controller ccc

the routing worked as is should
