### ISSUE TITLE
[Yaml][Twig-Bridge] Allow passing multiple files/directories to lint command

### ISSUE THREAD

**Issue by BackEndTea** [symfony/symfony#28498]
**Description**  
Currently the `lint:yaml` and `lint:twig` command allow only one file or directory to be passed, e.g.: `bin/console lint:yaml config/` etc.

I'd like to be able to pass multiple files/directories to these commands, which are then all linted. This is because as part of my CI, i lint all my yaml files, which can be in different directories. 

For me the `lint:twig` isn't really needed, but if it is done for yaml, the twig one should work the same way, for consistency.

**Comment by javiereguiluz** [comment]
Given that there is a simple Bash-based alternative to fix this:

```bash
for DIR in dir1 dir2 dir3 file1 file2
do
    bin/console lint:yaml $DIR	
done
```

We should decide if this is a common-enough scenario and add this feature ... or consider it not common enough and not add it.

**Comment by yceruto** [comment]
It's actually possible to pass multiples values (files or directories) to the `lint:twig` command:
```bash
$ bin/console lint:twig filename1 filename2 dir1 dir2
```
I think `lint:yaml` should allow ` InputArgument::IS_ARRAY` too, at least for consistency.

**Comment by chalasr** [comment]
👍

**Comment by yceruto** [comment]
see https://github.com/symfony/symfony/pull/28521 and https://github.com/symfony/symfony/pull/28522
