### ISSUE TITLE
BinaryFileResponse with X-Sendfile

### ISSUE THREAD

**Issue by maxgorovenko** [symfony/symfony#28502]
**Symfony version(s) affected**: 4.1.4

**Description**  
I have nginx + php-fpm. I want to send binary files via XSendfile featue with header X-Accel-Redirect. This feature allows me not to read files in php, but send their paths via header to nginx, and nginx will read and send files to client, not php.

I found \Symfony\Component\HttpFoundation\BinaryFileResponse class. Look like it can do my task with its method trustXSendfileTypeHeader().

**How to reproduce**  
So I have added in controller's action header 'X-Sendfile-Type' to current request. (It looks like hack) And created BinaryFileResponse with filePath, which will be accessible from nginx.
```BinaryFileResponse::create('some/file/path.tar.gz');```
BinaryFileResponse checks if file is accessible, but file 'some/file/path.tar.gz' is not accessible from php-fpm, and I don't have to, because I want to send file via nginx, not php.

**Possible Solution**  
I don't really believe that I understood role of BinaryFileResponse right. But if so, skip checking file if trustXSendfileTypeHeader set could solve this issue.

**Comment by mpdude** [comment]
Just guessing, but `BinaryFileResponse` tries to figure out the full path to the file to pass that in the header. Maybe that is why it needs to make sure it can fine the file?

**Comment by msheakoski** [comment]
You should not be setting X-Sendfile-Type in your controller, but instead the header should be added from your web server, this way your app's code does not have to know whether it is running behind Nginx or Apache:

```nginx
# https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/
location ~ ^/index\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    ...
    add_header x-sendfile-type x-accel-redirect;
}
```

In your controller:
```php
BinaryFileResponse::trustXSendfileTypeHeader();
return new BinaryFileResponse('some/file/path.tar.gz');
```

**Comment by msheakoski** [comment]
If PHP does not have access, maybe you can extend BinaryFileResponse as CustomBinaryFileResponse and write your own setFile() method to not check that the file is readable if the x-accel-redirect or x-sendfile headers are present.

**Comment by maxgorovenko** [comment]
@msheakoski exactly what I did, thanks!

I think this issue done.

**Comment by xabbuh** [comment]
closing then

**Comment by Alsatian67** [comment]
> https://symfony.com/doc/current/components/http_foundation.html#serving-files is not very clear on this topic so I understand why it seems confusing. I found your question because I had a similar issue and here is what I figured out:
> 
> You should not be setting X-Sendfile-Type in your controller. Instead, the header should be added in your web server config. This way, your app's code does not have anything specific for Nginx or Apache:
> 
> ```nginx
> # https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/
> location ~ ^/index\.php(/|$) {
>     fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
>     ...
>     add_header x-sendfile-type x-accel-redirect;
> }
> ```
> 
> In your controller, before sending the response you need to tell it to trust the X-Sendfile-Type header:
> 
> ```
> BinaryFileResponse::trustXSendfileTypeHeader();
> return new BinaryFileResponse('some/file/path.tar.gz');
> ```

Caution: add_header adds an header to the response.

To pass HTTP headers to symfony, you have to use fastcgi_param like that : 

```
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;

        ...

        fastcgi_param  HTTP_X-Sendfile-Type     X-Accel-Redirect;
        fastcgi_param  HTTP_X-Accel-Mapping    /home/foo/=/protected_files/;

        internal;
    }
```

**Comment by msheakoski** [comment]
> Caution: add_header adds an header to the response.
Good catch! I will update my example for future readers.
