### ISSUE TITLE
Twig_Error_Loader after use 'bin/console cache:clear --env=prod --no-debug'

### ISSUE THREAD

**Issue by thedomeffm** [symfony/symfony#28501]
**Symfony version(s) affected**: 4.1

**Description**  
I wanted to deploy my project. I was following the instructions on [https://symfony.com/doc/current/deployment.html](url). After I used 'bin/console cache:clear --env=prod --no-debug' I got these error: 
**Fatal error: Uncaught Twig_Error_Loader** ... **/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 101**

**Possible Solution**  
When I remove the cache manually 'rm -rf cache/' everything work.

**Comment by yceruto** [comment]
Could you show us the configuration for Twig paths? that's in `config/packages/twig.yaml`. 

This error commonly occurs when a nonexistent path is added to the Twig loader. Btw, the error message should says the directory that does not exist. 

Possible solutions: creates the missing directory or simply remove the path configuration.

**Comment by thedomeffm** [comment]
Hi,
`config/packages/twig.yaml`
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'


Fatal error: Uncaught Twig_Error_Loader: The "/myProject/vendor/symfony/framework-bundle/Resources/views" directory does not exist ("/myProject/vendor/symfony/framework-bundle/Resources/views"). in /var/www/vhosts/hostingProvider/myProject/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101 Stack trace: #0 /var/www/vhosts/hostingProvider/myProject/var/cache/prod/ContainerZcRzFGe/srcProdProjectContainer.php(379): Twig_Loader_Filesystem->addPath('/myProjec...', 'Framework') #1 /var/www/vhosts/hostingProvider/myProject/var/cache/prod/ContainerZcRzFGe/srcProdProjectContainer.php(691): ContainerZcRzFGe\srcProdProjectContainer->getTwigService() #2 /var/www/vhosts/hostingProvider/myProject/var/cache/prod/ContainerZcRzFGe/srcProdProjectContainer.php(212): ContainerZcRzFGe\srcProdProjectContainer->getSensioFrameworkExtra_View_ListenerService() #3 /var/www/vhosts/hostingProvider/myProject/v in /var/www/vhosts/hostingProvider/myProject/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 101

**Comment by yceruto** [comment]
Weird, this path `vendor/symfony/framework-bundle/Resources/views/) is verified if exists before adding it to the loader:
https://github.com/symfony/symfony/blob/e4d7c7484564e7c735cfecfaaaea7f019f232bf8/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L177-L179

I can't reproduce the issue.

Could you please create a small reproducer app that show the bug? https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs

**Comment by yceruto** [comment]
> When I remove the cache manually 'rm -rf cache/' everything work.

After that `cache:clear --env=prod --no-debug` the error still appear?

**Comment by thedomeffm** [comment]
Yes, I used `cache:clear --env=prod --no-debug` as it is documented here: [https://symfony.com/doc/current/deployment.html#d-clear-your-symfony-cache](url)

I created a complete new empty project and the error appears here too. Idk probably a problem with my hoster? But as I said, if I remove the cache manually everything work.

**Comment by yceruto** [comment]
> Fatal error: Uncaught Twig_Error_Loader: The "/myProject/vendor/symfony/framework-bundle/Resources/views" directory does not exist ("/myProject/vendor/symfony/framework-bundle/Resources/views").

Well, rereading the error message, seem that the path `/myProject/vendor/symfony/framework-bundle/Resources/views` is wrong, instead should be `/var/www/vhosts/hostingProvider/myProject/vendor/symfony/framework-bundle/Resources/views`.

Which makes me think that the user who executes the command `cache:clear` can only see from here `/myProject/...` (probably a user restriction) missing `/var/www/vhosts/hostingProvider` dirs. I'm not sure how this can happen.

Executing `cache:clear --env=dev`  show the bug too?

**Comment by thedomeffm** [comment]
When I run `cache:clear --env=dev`, an error appear that I need the WebProfilerBundle.
So I let composer install the dev bundles too and re-run `cache:clear --env=dev`,  but still I get the exact same error message. 

And when I manually remove the cache -> everything work fine. So probably it is like you said and Symfony just have problems with the paths.

**Comment by xabbuh** [comment]
@thedomeffm Did you manage to solve your problem? Or could you debug this a bit to see what's going on? I am afraid we cannot really help you there without understanding why this is failing.

**Comment by thedomeffm** [comment]
Hey,
yeah I got it. There where wrong options set in my hosting account. It seems like Symfony could not write session or something. Not 100% sure.

Thanks for help.

Can be closed

**Comment by troxxs** [comment]
> > Fatal error: Uncaught Twig_Error_Loader: The "/myProject/vendor/symfony/framework-bundle/Resources/views" directory does not exist ("/myProject/vendor/symfony/framework-bundle/Resources/views").
> 
> Well, rereading the error message, it seems that the path `/myProject/vendor/symfony/framework-bundle/Resources/views` is wrong, instead should be `/var/www/vhosts/hostingProvider/myProject/vendor/symfony/framework-bundle/Resources/views`.
> 
> Which makes me think that the user who executes the command `cache:clear` can only see from here `/myProject/...` (probably a user restriction) missing `/var/www/vhosts/hostingProvider` dirs. I'm not sure how this can happen.
> 
> The execution of `cache:clear --env=dev` shows the bug too?

Hi there,

I have the exact same prolbem as @thedomeffm  described and I am pretty sure it has to to with the user restriction, since my user actually only sees from /myProject as @yceruto mentioned. Is there a solution for this?

Thank you

**Comment by stof** [comment]
have you removed the composer.json file in the project dir ? I think that this might be related to the guessing logic of `getProjectDir`

**Comment by troxxs** [comment]
How can composer.json be related to the guessing logic? I don't see the point...

**Comment by stof** [comment]
Well, the default logic to identity the project root is based on finding the place where the composer.json is.
If you don't deploy your composer.json alongside your code, you need to overwrite the `Kernel::getProjectDir()` method in your AppKernel

**Comment by ad3n** [comment]
how about this error? i also have this error and i checked the folder `Resources/views` is not exist
