### ISSUE TITLE
NumberToLocalizedStringTransformer incorrect reverseTransform

### ISSUE THREAD

**Issue by koutja** [symfony/symfony#28500]
**Symfony version(s) affected**: 3.4.15
PHP 7.2

**Description**  

Unable to reverse value for property path "foo": The number contains unrecognized characters: "."
when valeu equal '239.' or other string contains number with dot in end. 
It was happend in class Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer when call method reverseTransform

**How to reproduce**  

1. Create form like this
```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('foo', NumberType::class, ['required' => false]);
    }
```

2.  submit values and check valid
```
$form->submit([
    'foo' => '239.'
]);
if (!$form->isValid()){
    echo 'form is not valid';
}
```
OR 
```
$transformer = NumberToLocalizedStringTransformer();
$transformer->reverseTransform('239.');
```

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
I was not able to reproduce your issue. What value is returned by `\Locale::getDefault()` when this fails for you?

**Comment by koutja** [comment]
![image](https://user-images.githubusercontent.com/26272443/45681670-c874c200-bb46-11e8-8a0d-eef6a4d6cd1f.png)

**Comment by koutja** [comment]
I forget say, that I use php version 7.2

**Comment by xabbuh** [comment]
Can you please dump the values of the `$result`, `$length`, `$remainder`, `$position`, and `$length` variables when the exception is thrown?

**Comment by koutja** [comment]
dump
`NumberToLocalizedStringTransformer.php on line 210:
array:7 [
  "$result" => 239.0
  "$remainder" => "."
  "$position" => 3
  "$length" => NumberFormatter {#1415
    #errorCode: 0
    #errorMessage: "U_ZERO_ERROR"
    -style: 1
    -attributes: array:3 [
      8 => 0
      1 => 0
      11 => 4
    ]
    -initializedAttributes: array:1 [
      1 => true
    ]
  }
  "$groupSep" => ","
  "$decSep" => "."
  "$encoding" => "ASCII"
]
NumberToLocalizedStringTransformer.php on line 212:
NumberToLocalizedStringTransformer {#1377
  #grouping: false
  #roundingMode: 6
  -scale: null
}`

**Comment by xabbuh** [comment]
I can confirm the issue when the `NumberFormatter` shipped with the Intl component is being used.

Status: Reviewed

**Comment by xabbuh** [comment]
see #28540
