### ISSUE TITLE
Name function is case sensitive

### ISSUE THREAD

**Issue by mgenereu** [symfony/symfony#28503]
**Symfony version(s) affected**: 4.1.3

**Description**  
`Finder#name` is case sensitive

**How to reproduce**  
With `A.xml` and `B.XML` in `/xmlfiles`
```
$finder = new Finder();
$finder->files()->name('*.xml')->in('/xml_files');
```
Expected return of both files.  Only A was returned.

Switched to more complicated RegEx to get insensitivity.
```
$finder->files()->name('/.xml$/i')->in('/xml_files');
```

**Possible Solution**  
Maybe adding a `iname` function like the Linux `find` command?
```
$finder->files()->iname('*.xml')->in('/xml_files');
```

**Comment by nicolas-grekas** [comment]
Would you like to work on this feature?

**Comment by chalasr** [comment]
Closing as explained in the related PR, thank you for proposing.

**Comment by mgenereu** [comment]
I'm sorry I never answered this.  I dove into the internals and I wasn't able to interpret the engine well enough to create a pull request.
