### ISSUE TITLE
Use of a broken or else risky cryptographic algorithm  md5() in  symfony/debug/ErrorHandler.php 

### ISSUE THREAD

**Issue by suresh-kumara-gist** [symfony/symfony#28509]
Use of a broken or else risky cryptographic algorithm  md5() in symfony/debug/ErrorHandler.php  

This function uses the !php_standard_ns.md5() function, which uses a hash algorithm that is considered weak. In recent years, researchers have demonstrated ways to breach many uses of previously-thought-safe hash functions such as MD5.

**Comment by xabbuh** [comment]
Looks like the report is about this line: https://github.com/symfony/symfony/blob/ed8dd86e20c6a155cb6cbc7a9a471bf1d7645089/src/Symfony/Component/Debug/ErrorHandler.php#L505

Here, we only filter duplicated errors. That's nothing were we need a cryptographically secure hash algorithm. So I am going to close here.

@suresh-kumara-gist Thank you for reporting, but for the next time please follow the process described at https://symfony.com/doc/current/contributing/code/security.html#reporting-a-security-issue if you think that you discovered a security vulnerability.
