### ISSUE TITLE
[DI] Unexpected maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28510]
**Symfony version(s) affected**: 4.1 (maybe 3.4 as well)

**Description**  
The error happens in  `AnalyzeServiceReferencesPass.php(119)` and seems to happen as soon as a service looses some reference. Nested call involved with the service :)

**How to reproduce**  

see https://github.com/ro0NL/sf-di/commits/master

**Additional context**  

not sure if i relied on a bug actually =/

cc @nicolas-grekas

**Comment by ro0NL** [comment]
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /app/vendor/symfony/dependency-injection/Definition.php:120
Stack trace:
#0 /app/vendor/symfony/dependency-injection/Compiler/AnalyzeServiceReferencesPass.php(119): Symfony\Component\DependencyInjection\Definition->getFactory()
#1 /app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\AnalyzeServiceReferencesPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), false)
#2 /app/vendor/symfony/dependency-injection/Compiler/AnalyzeServiceReferencesPass.php(109): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#3 /app/vendor/symfony/dependency-injection/Compiler/AnalyzeServiceReferencesPass.php(120): Symfony\Component\DependencyInjection\Compiler\AnalyzeServiceReferencesPass->processValue(Array)
#4 /app/vendor/symfony/dependency-injection/Compiler/ in /app/vendor/symfony/dependency-injection/Definition.php on line 120

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /app/vendor/symfony/dependency-injection/Definition.php on line 120

Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /app/vendor/symfony/dependency-injection/Definition.php on line 120

Call Stack:
    0.1731    8479368   1. Symfony\Component\Debug\ErrorHandler->handleException() /app/vendor/symfony/debug/ErrorHandler.php:0
```

**Comment by nicolas-grekas** [comment]
I'm unable to reproduce using the linked repo, did I miss something?

**Comment by nicolas-grekas** [comment]
Reproduced by skipping the last commit.
Issue exists also in v4.1.0 and in v3.4.0, so might be old.

**Comment by stof** [comment]
Does it still break if you increase the max nesting level of Xdebug ? This XDebug feature is meant to break infinite recursions without crashing everything, but it is totally possible to write legitimate code doing *finite* recursion with more steps than 256.

If the recursion is infinite, that's a bug. If the recursion is only deeper than 256 calls but finite, that's not really a bug.

**Comment by asoupper** [comment]
I have still the same problem in Symfony 3.4.36

**Comment by xabbuh** [comment]
@asoupper Please open a new issue and provide some steps to reproduce it. Comments on closed issues are likely to get lost. :)
