### ISSUE TITLE
phpunit-bridge ignores <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" /> in phpunit.xml

### ISSUE THREAD

**Issue by soerenbernstein** [symfony/symfony#28519]
**Symfony version(s) affected**: all ?

**Description**  
phpunit-bridge ignores the value "disabled" for the environment variable SYMFONY_DEPRECATIONS_HELPER when set in phpunit.xml. The value "weak" works as expected. 
Also, setting this environment variable in the shell works as expected.

Tested with phpunit-bridge-4.1.4

**How to reproduce**  
set in phpunit.xml

```
<php>
  <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />
</php>
```

and run a test which will cause a deprecation warning.

**Comment by soerenbernstein** [comment]
I've fiddle around a bit. Maybe DeprecationErrorHandler.php:57 is missing a test for DeprecationErrorHandler::MODE_DISABLED?
At first glance it seems to fix the problem, but I'm not sure about possible side effects.

**Comment by nicolas-grekas** [comment]
"disabled" mode is taken into account in https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bootstrap.php#L38 - as you can see, this comes earlier than reading the phpunit.xml.
By yes, we could actually change https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L105 and read `$_ENV['SYMFONY_DEPRECATIONS_HELPER']` there also.
Would you like to submit a PR doing so?

**Comment by soerenbernstein** [comment]
Actually, ```getenv('SYMFONY_DEPRECATIONS_HELPER')``` in https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bootstrap.php#L38 will only report environment variables from the shell at that moment. Parameters from phpunit.xml are probably not parsed yet?

As far as I understand the code - and I might be completely off on this - the problem is, that in https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L104 the mode parameter is reset to 0 because of https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L57 not recognizing "disabled" as a valid value for mode, trying to parse an integer, fails and falls back to 0. 

In consequence mode will never be set to "disabled" in https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L105.

**Comment by nicolas-grekas** [comment]
That's why I used `$_ENV` in my previous comment. Did you try using it?
