### ISSUE TITLE
[RFC] Reconsider the use of the "Violation" word

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#28511]
This issue is about a topic that usually generates heated debates, so here's a quick reminder: [Symfony's Code of Conduct](https://symfony.com/coc) applies to GitHub discussions too. You can express your agreement/disagreement with this proposal, but you must do it in a civilized way.

-----

In the software industry we're seeing lately some debates about the (bad) wording chosen for some concepts/technologies. That's why words like "master/slave" are slowly being replaced by "primary/replica". In the Symfony Validator component we use a word with a strong/negative meaning: `violation`. One of its meanings is literally "rape" (in languages like English, Spanish, etc.)

I propose to remove the use of `Violation` in our code and replace it by something like `Error`, `Issue`, etc. Most of the times we use "violation" in combination with "constraint", so maybe we could rename `ConstraintViolation` as `ValidationError`. It would be more concise to write and even easier to understand.

-----

A usual counter-argument to proposals like this one is: any given word can be offensive to some person; should we ban all words? That's true. However, we don't care if some word offends to one person or a tiny group of people. We only debate about words that are seen as "bad" or "better use a synonym" by a large enough number of people. I think "violation" fits this ... but I can be wrong :)

**Comment by stof** [comment]
well, getting a validation error when a validation constraint fails does not looks weird to me (note that it cannot be a `constraint validation`, as that would make it a `validation`, which does not make sense in this context)

**Comment by Taluu** [comment]
I'm :neutral_face: on that, because even if it may be a strong word (not quite convinced), I'd rather call a cat a cat rather than something else...

Especially as `Error`, `Issue`... and so on are kinda "generic" and does not reflect that you made an input error or something along those lines.

**Comment by javiereguiluz** [comment]
@Taluu yes, `Error`, `Issue`, etc. are too generic. I was thinking about combining it with other word. For example: `ValidationError` (which to me is the most obvious word to use to refer to a validation error ... and it's the most common one used in the validation libraries I checked).

**Comment by stof** [comment]
another option to consider could be to ensure that we **always** talk about `constraint violation`, instead of doing it only "most of the time". This extra context *might* be enough for these people (not sure about that)

**Comment by ping-localhost** [comment]
To me, the word `violation` is the right word in this context, since the input violated the restrictions set by the data object (assuming you use DTO's). Same thing goes for violating the law. You don't "error", you broke a rule and are thus in violation (a quick example would be a [Parking violation](https://en.wikipedia.org/wiki/Parking_violation)).

Something like `ValidationError` sounds like the validation itself failed and not that the data provided is invalid.

I understand that words and their meaning can change over time and that words can mean different things in different languages, but I don't think this applies to `violation`, at least not in this specific context.

**Comment by iltar** [comment]
From the perspective of a developer it can already be a bit confusing:
 - We add constraints
 - We validate values based on those constraints
 - We fire constraint violations when the data is invalid
 - We get validation errors

There's no naming consistency

**Comment by stof** [comment]
@iltar I don't understand what you are considering for the difference between the last 2 points in your checklist. In the current code, the validator gives you a list of constraint violations when the data is invalid. This discussion is about *renaming* that to validation errors, not to have 2 different naming following each other.

**Comment by sstok** [comment]
According to the dictionary https://dictionary.cambridge.org/dictionary/english/violation it means:
" an action that breaks a law, agreement, rule".

It depends on the context, a person is being violated (their rights of freedom not being respected), an object may break a rule thus violating it's constraints.

Error might be broad, is it not respecting the constraints or is it unable to validate them (because of external error, like an API gateway connection-error).

The "master/slave" example has clear meaning because there are no other contexts then being a slave, it literally means having no choice or freedom. In fact, I can't even understand why this wording was chosen 🤨 (maybe because a slave can become a master, but still).

Error and Failure basically mean the same, but violation is limited in it's context and purpose.

**Comment by iltar** [comment]
@stof talking from the context of a form, I wasn't clear about that, my bad:
```php
    /**
     * @return FormErrorIterator An iterator over the {@link FormError}
     *                           instances that where added to this form
     */
    public function getErrors($deep = false, $flatten = true);
```

From a form perspective, this is correct. The conversion from a constraint violation to a form error happens behind the scene.

**Comment by nicolas-grekas** [comment]
In quality language, we would use `Nonconformity` or `Defect`.
@javiereguiluz what would be the cost this would impose on users migrating to the new word?
That's IMHO an important consideration.

**Comment by stof** [comment]
We would have a cost for anyone writing custom constraint (as the API to add violations would be renamed), as well as for anyone using the validator component directly and typehinting some arguments when they pass the returned values (classes would be renamed).
Note that many people are not calling the validator themselves, but rely on the form component calling it, and there is no impact there for the second part.

**Comment by Pierstoval** [comment]
I'm also in keeping the `Violation` name since it's more used as a legal term. Even in French or Spanish I think the word `violation` is not really used in the context of a rape.

Even synonyms are not really representative of what we are using in tech: https://www.thesaurus.com/browse/violation

**Comment by stof** [comment]
@iltar form errors are more generic than constraint violations. When the form fails to process a value (in a data transformer for instance), that's also a form error (but it is not a validation error).
As explained by @sstok, error is a more generic meaning.

**Comment by ciaranmcnulty** [comment]
@javiereguiluz Do you have some examples where affected people advocate this naming change? Or its it pre-emptive?

**Comment by javiereguiluz** [comment]
@ciaranmcnulty it's pre-emptive ... and probably just a personal cultural thing (I'm native in Spanish, where the word *"violación"* has a very negative connotation).

**Comment by ciaranmcnulty** [comment]
@javiereguiluz right, as an English-speaker it doesn't feel strong but there may well be others who have different experiences who feel differently

**Comment by ADmad** [comment]
I wonder how renaming this is going to make someone who's actually "violated" in some way feel any better?

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" because nobody thinks that this is a bad word that should be considered ... so that means we're doing it right 👍  Thank you all for the civilized discussion!

**Comment by fabpot** [comment]
Not sure if closing so fast was a good idea.

**Comment by dereuromark** [comment]
@fabian It was, the author itself realized that this was a bad idea and that this has nothing to do with the actual problem of society. So all good.
