### ISSUE TITLE
[Form] Add form option to not convert empty strings to null

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/symfony#28518]
# :rocket:

**Description**

As Symfony is being used to create more and more APIs, add a form option to **not** convert empty strings to `null` *without* having to attach a `DataTransformerInterface` instance that returns the value unchanged on every text field.

Also, I feel that the current behaviour to convert empty strings to `null` should be a data transformer itself, rather than hard-coded in `Symfony\Component\Form\Form::viewToNorm()`.

**Example**

```php
/** @var \Symfony\Component\Form\FormBuilderInterface $formBuilder */
$formBuilder->create(MyFormType::class, new MyModel, [
    'preserve_empty_strings' => true,
]);
```

**Comment by yceruto** [comment]
It's actually possible, by passing _explicitly_ `''` (empty string) to `empty_data` option for text fields, you'll get an empty string if an empty value is submitted.

Even though [the documentation](https://symfony.com/doc/current/reference/forms/types/text.html#empty-data) says it's the default value, actually, [it's](https://github.com/symfony/symfony/blob/a23a4a439817c3178646813ccdfd7d429cb47525/src/Symfony/Component/Form/Extension/Core/Type/FormType.php#L139-L141) **not** [at the time `TextType` is being built](https://github.com/symfony/symfony/blob/6bfd0f1f45e6c65f8b71c7057522e096eb9289f3/src/Symfony/Component/Form/Extension/Core/Type/TextType.php#L28). Hence, [the data transformer is not added](https://github.com/symfony/symfony/blob/6bfd0f1f45e6c65f8b71c7057522e096eb9289f3/src/Symfony/Component/Form/Extension/Core/Type/TextType.php#L29) and [the default one](https://github.com/symfony/symfony/blob/004c315b0c103e52a81787f2f2dac34e0da115ad/src/Symfony/Component/Form/Form.php#L1127-L1129) is used, returning `null` by default.

**Comment by xabbuh** [comment]
@zanbaldwin Can you confirm that configuring your form type as described by @yceruto solves your problem?

**Comment by zanbaldwin** [comment]
Hi, it seems to work - I was going to test on Monday whether it would also work for other text-based fields like Choice and Date.

**Comment by zanbaldwin** [comment]
Unfortunately the `empty_data` option doesn't give any way to differentiate between an empty string and null.

> Tested with both `TextType` and `EmailType`, from [Symfony Skeleton `v4.1.2.3`](https://github.com/symfony/skeleton) with a form type, controller and route definition, and JSON payload listener. The exact code I used to test can be found at: https://gist.github.com/zanbaldwin/514bcf0e4ebf04e79efac18df5f1df1e

- With `empty_data` **not** set (eg `->add('my_text', TextType::class)`):
  - Submitting `{"my_text":null}` results in `$form->getData()['my_text']` being `null`.
  - Submitting `{"my_text":""}` results in `$form->getData()['my_text']` being `null`.
- With `empty_data` **set** (eg `->add('my_text', TextType::class, ['empty_data' => ''])`):
  - Submitting `{"my_text":null}` results in `$form->getData()['my_text']` being `string(0) ""`.
  - Submitting `{"my_text":""}` results in `$form->getData()['my_text']` being `string(0) ""`.

**Comment by yceruto** [comment]
There is no bug here. The behavior is expected and the related document has been updated already. 
Also if you want to change the current behavior it's possible through a form type extension with ease.

**Comment by DoobleD** [comment]
Not a bug indeed and sure there are ways of implementing it, but an option allowing differentiation between empty strings and null would no doubt be valuable for API builders. 

Or as @zanbaldwin mentioned make it the default behavior, though there might be good reasons the current behavior was chosen in the first place that I'm not aware of.
