### ISSUE TITLE
[symfony/console] Tables using "box" style with colspan break layout

### ISSUE THREAD

**Issue by rhukster** [symfony/symfony#28532]
**Symfony version(s) affected**: 4.1.x

**Description**  
When using the `box` or `box-double` Table styling, regular tables are rendered fine, but tables with nested `TableCell`s using `colspan` break the layout.

**How to reproduce**  

Using this code from the docs (plus a style):

```
$table = new Table($output);
$table->setStyle('box');
$table
    ->setHeaders(array('ISBN', 'Title', 'Author'))
    ->setRows(array(
        array('99921-58-10-7', 'Divine Comedy', 'Dante Alighieri'),
        new TableSeparator(),
        array(new TableCell('This value spans 3 columns.', array('colspan' => 3))),
    ))
;
$table->render();
```

results in this:

<img width="228" alt="monosnap-2018-09-20-20-02-10 image" src="https://user-images.githubusercontent.com/1084697/45856025-112ba700-bd10-11e8-84a8-790839319cb7.png">

compared to this with the default styling:

<img width="217" alt="monosnap-2018-09-20-20-02-34 image" src="https://user-images.githubusercontent.com/1084697/45856045-1ee12c80-bd10-11e8-8f1e-a3a1c6a5aa4e.png">

**Comment by ro0NL** [comment]
See #28548

**Comment by rhukster** [comment]
Nice! Thanks for the quick response!
