### ISSUE TITLE
[Doctrine-bridge] Doctrine\Common\ClassLoader is deprecated Release

### ISSUE THREAD

**Issue by ahinkle** [symfony/symfony#28530]
Hi,

Currently my PHPUnit tests are failing because of `doctrine/common`. 

```
Remaining deprecation notices (1)

  1x: Doctrine\Common\ClassLoader is deprecated.
    1x in aboutUsTest::testValidRequestDemoForm from App\Tests

╰─ composer why doctrine/common                                                                                                                                                                  
symfony/doctrine-bridge        v4.1.4  requires  doctrine/common (~2.4)  
```

There seems to have been a patch [here](https://github.com/symfony/doctrine-bridge/commit/36602b14c83c5cc140f9025e7adb806b75ddb9eb), but it hasn't been released yet.

As a temp fix, I'm using the master branch, but I'm curious when it will be released? I worry about using the master branch in production without an official release for the fix.

Thanks!

**Comment by xabbuh** [comment]
I don't think that this deprecation is triggered by the Doctrine bridge, but by Doctrine ORM which doesn't have a release with the latest changes. Downgrading doctrine/common is the solution for now (see #28119).
