### ISSUE TITLE
Multiple class_data in configureOptions for one form

### ISSUE THREAD

**Issue by toukmed** [symfony/symfony#28535]
Hi!
I'm in front of a challenge for managing import files for massive number of entities and I need to refactor my code in order to create one action and one form to manage import for every single entity (It's too difficult and redundant to create a formType for every single entity and manage it's own action); A LOT OF WORK !!

So my question is : is there some way to specify an array of data_classes in order to generate the unique form and map it to the correspondant entity class

```
public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class1' => Action::class,
            'data_class2' => User::class
            'data_class3' => Mentor::class
            'data_class4' => Question::class
            ....
        ));
    }
```

/ or pass a dynamic entity classname to class_data as a value?

```
public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => $this->entity['name'],
        ));
    }
```

Thanks!

**Comment by iltar** [comment]
Sounds more like a support question, which can be discussed and answered on slack for example: symfony.com/support

What you're looking for is a Data Transfer Object and composition of multiple form types most likely, which can be used to solve your problem: https://stovepipe.systems/post/avoiding-entities-in-forms

**Comment by xabbuh** [comment]
I am going to close here. As @iltar said please use one of the [support channels](https://symfony.com/support) to seek for help.
