### ISSUE TITLE
[symfony/debug] ...MicroKernelTrait::loadRoutes()" method is considered internal...

### ISSUE THREAD

**Issue by mazarini** [symfony/symfony#28549]
**Symfony version(s) affected**: 4.2@dev
Work with 3.4, 4.0 and 4.1 without message.

**Description**  
1x: The "Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait::loadRoutes()" method is considered internal. It may change without further notice. You should not extend it from "App\Kernel".
    1x in ExtensionTest::testService from Mazarini\ToolsBundle\Tests\Controller\DependencyInjection

**How to reproduce**  
Probably append when "$this->bootKernel();" during test
I don't extend it, it's seems append with unmodified kernel.

**Comment by nicolas-grekas** [comment]
Thanks for testing with 4.2 already!
Must be related to #28329, ping @GuilhemN FYI ;)

**Comment by nicolas-grekas** [comment]
can you share a small reproducer please?

**Comment by nicolas-grekas** [comment]
Thanks, fix in progress at #28553

**Comment by mazarini** [comment]
Thank you, sorry don't answer before.
It's work well know for me
