### ISSUE TITLE
[VarDumper] Add more casters for Intl

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#28554]
A Caster is used to convert an object to an array representation that later could be written as a string. All Casters are registered in the `AbstractCloner` and will automatically be used when we try to clone an object. 

There some classes in intl that could benefit from having a caster, see http://php.net/manual/en/book.intl.php

See @nicolas-grekas PR for `MessageFormatter` as an example: #28551 

I think it could be a good idea to have casters for the following classes: 

* [x] NumberFormatter
* [x] MessageFormatter
* [x] IntlTimeZone
* [x] IntlDateFormatter
* [x] IntlCalendar
* [x] ~Locale~

Do we need any more?

**Comment by nicolas-grekas** [comment]
That was quick, thanks @jschaedl for doing the work!

**Comment by Nyholm** [comment]
Awesome. Thank you @jschaedl!
