### ISSUE TITLE
[Messenger] Allow set priority for custom middleware

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#28568]
**Description**  
I'm trying to integrate https://github.com/LongRunning/LongRunning into my application as middleware for Messenger component. This middleware should be executed after logging middleware (because it [closes and clearers](https://github.com/LongRunning/LongRunning/tree/master/src/Plugin/MonologPlugin) Monolog handlers and we should properly log both [start and finish events](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Middleware/LoggingMiddleware.php#L33-L46).

As workaround for now I've just decorating logging middleware, but I think it is better add priority for them. Like in event listeners or services decoration.

**Comment by sroze** [comment]
It has been discussed a lot in the middleware PR: at the time, we settled down for using an explicit declaration of the middleware to represent their priority. Obviously, as you've discovered, there are 3 default middleware configured [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1512-L1515). If you set the [`default_middleware` option](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1087) to `false`, they will not be registered and you can add yours (and the default ones if needed) explicitly, in the order you wish.

**Comment by Koc** [comment]
`default_middleware: false` and explicit registration of them is really good workaround, thank you for suggesting it.

But without priorities we cann't provide automatic integration of thirdparty libraries. Same LongRunning bundle can be shipped with middleware which automatically registers in right order using Symfony Flex. For now we should disable standard config and define own.

**Comment by sroze** [comment]
> Would it be possible to add this option as part of the Factory? Most of these are static constants.

I don't understand. What do you mean exactly? :)

**Comment by sroze** [comment]
I'm closing because we didn't see any activity for a long time and it seems like [the explicit order of middleware is enough](https://github.com/symfony/symfony/issues/28568#issuecomment-423896908).
