### ISSUE TITLE
How do I construct a logical alternative of validation constraints?

### ISSUE THREAD

**Issue by buffalobuffalobuffalobuffalobuffalo** [symfony/symfony#28563]
Like the subject:

What is the simplest way to construct a constraint that uses two or more other constraints as alternatives:
```
@Or({
    @PasswordRequirements(requireSpecialCharacter=true),
    @PasswordRequirements(requireNumber=true)
})
```

**Comment by javiereguiluz** [comment]
This looks like a custom validation constraint, so you can use the [Callback constraint](https://symfony.com/doc/current/reference/constraints/Callback.html). If you have more support questions about this, please use any of the support channels listed here: https://symfony.com/support  (in this repo we only discuss about Symfony bugs and new features). Thanks!
