### ISSUE TITLE
[FrameworkBundle] performNoDeepMerging on translator.fallbacks

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#28576]
In my organization english is the source locale and I was asked to not have any fallback on our staging environment. So I wrote

*packages/translation.yaml*
```php
framework:
    translator:
        fallbacks: en
```

*packages/staging/translation.yaml*
```php
framework:
    translator:
        fallbacks: ~
```

but this resulted in english as fallback. Could deep merging be disabled for this node?

---

As `en` is the default value I worked around this by removing `framework.translator.fallbacks` from *packages/translation.yaml*. But this wouldn't work for any other locale.

**Comment by xabbuh** [comment]
Doing that would be a BC break. Can't you just remove the `fallbacks` option from the main file and only use it explicitly for the environments that need it?

**Comment by MatTheCat** [comment]
@xabbuh yes but that sounds like a workaround too. I can't think of a use-case where it's useful to merge fallbacks :thinking:
