### ISSUE TITLE
[DX] [WebServerBundle] Display the local host IP when binding to 0.0.0.0

### ISSUE THREAD

**Issue by respinoza** [symfony/symfony#28585]
**Description**  
When binding the web server to `0.0.0.0` the success message shows `http://0.0.0.0:8000` which is technically correct but as a developer you can't do anything with it, you will have to look up this (many ways, depending on your environment).
I propose to show the local hostname resolved to an IP in addition to the current message. I understand this won't cover all specific address but might make the developer life easier for common cases.

**Example**  
For example, lets say you use docker, when running the command inside the container like `./bin/console server:start *:8080`, the new output will show this:

```
[OK] Server listening on http://0.0.0.0:8080 (http://172.20.0.2:8080)
```

In this way you can easy copy (or click on it) instead of using docker inspect or something other method to retrieve this address.

**Comment by javiereguiluz** [comment]
If `0.0.0.0` is "useless" ... we could not display it at all. The output of your example could simply be:

```
[OK] Server listening on http://172.20.0.2:8080
```

**Comment by respinoza** [comment]
I improved the message and method name as @javiereguiluz suggested. I kept the 0.0.0.0 as it reminds the developer the server is listening on all interfaces.

**Comment by jkufner** [comment]
Listening on 0.0.0.0 includes listening on 127.0.0.1.

The message could be one of these:

    [OK] Server listening on 0.0.0.0:8080 -- see http://127.0.0.1:8080
    [OK] Server listening on all interfaces, port 8080 -- see http://127.0.0.1:8080

Then it is obvious what is going on. User knows it listens everywhere and still has one link to click.

**Comment by xabbuh** [comment]
I prefer the second suggestions. It's more explicit for users who don't know what it means that a service is listening on 0.0.0.0.
