### ISSUE TITLE
Add support for COMPOSER_VENDOR_DIR for autoloader location in bin/console

### ISSUE THREAD

**Issue by olberger** [symfony/symfony#28583]
**Description**  
Using the COMPOSER_VENDOR_DIR env var allows to divert the location of vendor/. This is handy when for example working on a slow file-system (NFS, or virtual machine shared drive, etc.), where parsing lots of tiny PHP files isn't very much efficient.

However, bin/console relies on the autoloader being in a vendor/ subdir:
```
require __DIR__.'/../vendor/autoload.php';
```
One has to symlink vendor to the location of COMPOSER_VENDOR_DIR, which may be annoying since that dir may be reset if COMPOSER_VENDOR_DIR is diverted to a temporary location.

I guess changing bin/console it so that it supports a different location, if the COMPOSER_VENDOR_DIR env var is set, would make Symfony more flexible.

Something along the lines of https://github.com/symfony/symfony/issues/26386#issuecomment-370213087 would probably make it possible.

Thanks in advance.

**Comment by xabbuh** [comment]
This file is only initially created by Flex (or the Symfony installer) when bootstrapping a new application. After that you can customise it according to your needs. I am not sure I understand what else needs to be done in Symfony to support this use case.

**Comment by olberger** [comment]
The idea would be that newcomers get such a "feature" when they start an application

Maybe my request would be better suited for the flex skeleton (?) and not for Symfony main, then ?

Hth,

**Comment by javiereguiluz** [comment]
@xabbuh I guess @olberger would like to replace the previous line of code by something like this:

```php
require ($_ENV['COMPOSER_VENDOR_DIR'] ?? __DIR__.'/../vendor').'/autoload.php';
```

**Comment by olberger** [comment]
Investigating a bit further, maybe this relates actually to the symfony/console Flex recipe and its bin/console script, as per https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console

I may forward this issue there, then. Suggestion ?

**Comment by xabbuh** [comment]
Yes, that's the place where the Intel script is taken from when you create a new application based on the skeleton or website skeleton. I think moving the issue there makes sense.

**Comment by olberger** [comment]
Closing here, then. Thx.
