### ISSUE TITLE
[TwigBundle] Ability to disable built-in ExceptionListener

### ISSUE THREAD

**Issue by kejwmen** [symfony/symfony#28587]
Hi.
I am developing an app that needs twig bundle to render some templates for infrastructure implementation (sending emails) and twig must be registered as templating engine (because 3rd party code depends on that), but I don't need Twig exception listener.
Current configuration doesn't allow me to disable that.
I would like to pass `null` in `twig.exception_controller` to disable that feature. Now I need to remove definition in compiler pass.
Of course I will prepare a PR.

WDYT?

**Comment by kejwmen** [comment]
No, implementation doesn't handle that and `ExceptionListener` tries to send request  `null` controller, this ends with controller being not found.

Event if it would, listener shouldn't be registered in this case.

**Comment by stof** [comment]
this looks sensible to me. Can you send a PR ?

**Comment by kejwmen** [comment]
Sure, wanted to confirm it makes sense before I start.

**Comment by yceruto** [comment]
Could you check if https://github.com/symfony/symfony/pull/27519 fix your issue?

**Comment by kejwmen** [comment]
Need to check how it behaves along with TwigBundle installed, thanks!

**Comment by yceruto** [comment]
@kejwmen Are you checked it? 

This worked for me:
```twig
# config/packages/twig.yaml
twig:
    exception_controller: ~
```
