### ISSUE TITLE
[security-bundle] - Symfony\Component\Templating\Helper\Helper is not loaded

### ISSUE THREAD

**Issue by roukmoute** [symfony/symfony#28594]
**Symfony version(s) affected**: all

**Description**  
We cannot use [`LogoutUrlHelper`](https://github.com/symfony/symfony/blob/2b9c142f07b7dbc11d4d392b77629fa91a5dcb41/src/Symfony/Bundle/SecurityBundle/Templating/Helper/LogoutUrlHelper.php) correctly.

**How to reproduce**  
```php
<?php

// First, run "composer require symfony/doctrine-bridge"
// Then, execute this file:
require_once __DIR__.'/../vendor/autoload.php';

if (is_a('Symfony\Bundle\SecurityBundle\Templating\Helper\LogoutUrlHelper', 'Symfony\Component\Templating\Helper\Helper', true)) {
    echo 'ok';
} else {
    echo 'not ok';
}
```

produces:
```bash
Fatal error: Class 'Symfony\Component\Templating\Helper\Helper' not found in /www-data/vendor/symfony/security-bundle/Templating/Helper/LogoutUrlHelper.php on line 23

Call Stack:
    0.0026     401344   1. {main}() /www-data/bin/console_dist:0
    0.1030    4637808   2. is_a() /www-data/bin/console_dist:8
    0.1030    4637904   3. spl_autoload_call() /www-data/bin/console_dist:8
    0.1030    4638000   4. Composer\Autoload\ClassLoader->loadClass() /www-data/bin/console_dist:8
    0.1033    4638128   5. Composer\Autoload\includeFile() /www-data/vendor/composer/ClassLoader.php:322
    0.1033    4643208   6. include('/www-data/vendor/symfony/security-bundle/Templating/Helper/LogoutUrlHelper.php') /www-data/vendor/composer/ClassLoader.php:444
```

**Possible Solution**  
In `composer.json`: Add `symfony/templating` to `require`.

**Comment by sstok** [comment]
This is related to #28593 . Adding this dependency would force anyone using the SecurityBundle to also have the templating system. Which is not used for REST-only applications.

This has been discussed before, and Matthias Noback (matthiasnoback) even wrote a few blog posts on this topic. Adding these optional dependencies would make the package more "bloated", while the current method may cause some frustration if a functionality is used that requires this.

Symfony already tries to handle most of this gracefully (in Twig it does at least), but there is still room for improvement. However solving this without adding to much for the runtime is tricky.

-----

FYI. The templating component is considered deprecated, and Twig is recommended now.

**Comment by chalasr** [comment]
We try to throw meaningful exceptions when a feature cannot be used because of a missing dependency (see e.g. #28513), that could apply here I guess.

**Comment by nebkam** [comment]
I don't mind having a feature that is optional. But this also breaks when generating authorative class maps in Composer. It uses reflection and breaks when the `Symfony\Component\Templating\Helper\Helper` is not found (I don't have symfony/templating and didn't need it until now)

**Comment by xabbuh** [comment]
@nebkam Are you you are not affected by #32395?

**Comment by nebkam** [comment]
@xabbuh Yes, judging by the symptoms in that thread, I'd say that might be the root cause. And yes, I'm running Symfony 4.2.4 on PHP 7.2.19
