### ISSUE TITLE
[Dom-Crawler] Crawler change node structure

### ISSUE THREAD

**Issue by vistarsvo** [symfony/symfony#28596]
**Symfony DOM-Crawler version(s) affected**: 4.1

**Description**  
Hi. I have interesting bug, when Crawler change node structure. I can't parse html value.

Original content is:
` <h1><p class="wide_title" id="pPageHeader">Szukanie zaawansowane</p></h1>
` 

After echo (new Crawler($this->content))->html() :
```
 <h1></h1>
<p class="wide_title" id="pPageHeader">Szukanie zaawansowane</p>
``` 
So, output is empty :( :
```
$crawler = new Crawler($content);
foreach($crawler->filter('h1') as $h1DomElement) {
   echo $h1DomElement->nodeValue . PHP_EOL;
}
```

OS: Ubuntu 18.04
PHP ver: PHP 7.1.20-1+ubuntu18.04.1+deb.sury.org+1

Also has same problem on another envirounment:
OS: CentOS
PHP 7.1.20 (cli) (built: Jul 19 2018 10:10:15) ( NTS )

**Html page**  

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl-PL" >
<head>
	<link rel="dns-prefetch" href="//www.google.com" />
</head>
<body>
	<noscript>
        <link rel="stylesheet" type="text/css" href="/css/layout/noscript.css">
        <div class="noscript-error">
	        Some text
        </div>
	</noscript>

    <div class="serp">
        <div class="serp_cont">
            <div class="search_form_pnl new-sf_pnl">
                <div class="stopper"></div>
                    <div class="right-items_wr">
                        <div class="user_wrapper">
                            ...
                        </div>
                    </div>
            </div>
            <div>
                <h1><p class="wide_title" id="pPageHeader">Szukanie zaawansowane</p></h1>
            </div>
            <div class="subs_edit wide_panel">
                <form action="/Help/WideSearch" method="post">   
                </form>        
            </div>
        </div>
    </div>

</body>
</html>
```
![image](https://user-images.githubusercontent.com/5312683/46013802-f40f2380-c0d5-11e8-9e1c-b8b25b911841.png)

**Comment by stof** [comment]
a `<p>` inside a `<h1>` is invalid HTML.

While PHP's DOMDocument API is not aware of all the HTML5 rules, it still knows a bunch of HTML rules.
If you look at your browser dev tools, you will see that the browser is doing the same kind of change when parsing HTML (and in HTML5, this behavior is even part of the spec)

**Comment by stof** [comment]
The spec has an informative note in its description of the `<p>` warning about such auto-closing behavior: http://w3c.github.io/html/single-page.html#the-p-element
The section about `<h1>` does not have the same kind of note, but the behavior are the same (both elements are expecting "Phrasing content" inside them).

**Comment by vistarsvo** [comment]
> If you look at your browser dev tools, you will see that the browser is doing the same kind of change when parsing HTML (and in HTML5, this behavior is even part of the spec)

Ok. Take a look at screenshots.

Firefox:
![image](https://user-images.githubusercontent.com/5312683/46016773-59671280-c0de-11e8-957e-e068d7604d4c.png)

Chrome:
![image](https://user-images.githubusercontent.com/5312683/46016854-97fccd00-c0de-11e8-91df-fd356e684092.png)

As you know, a lot of web-developers ignore rules. So, more then 50% site has invalid HTML structure.
Why Crawler silently change node tree? May be add some param in constructor, like $mode = 'strict' | 'originalHtml'. 
How can i validate some node with Crawler when it  silently change tree?

**Comment by jakzal** [comment]
> How can i validate some node with Crawler when it silently change tree?

The Crawler does not modify the document. It's the DOMDocument extension that's used behind the hood to load documents. See https://3v4l.org/fejIP.

**Comment by stof** [comment]
@fabpot do you remember why we silence the call to `$dom->loadHTML($content)` in the Crawler when loading HTML ? DomDocument is not silent when performing such transformation, but we silence it.

**Comment by vistarsvo** [comment]
I think that silence (catching warnings in constructor and ignore it) is a problem. And hide setting options future when creating DOMDocument is is a problem too.
So, what value of profit and advantage of this component if i cannot use important options and catch mistakes?
I need create DOMDocument myself and then set it to crawler?

**Comment by stof** [comment]
Well, I think silencing was done to avoid them being turned into exception by error handlers (and so breaking everything). but we may want to log some of the DOM warnings to help debugging.

Regarding options, which one are you talking about ?

**Comment by vistarsvo** [comment]
I mean option in loadHTML method of DOMDocument object. 
http://php.net/manual/ru/domdocument.loadhtml.php

public function addHtmlContent($content, $charset = 'UTF-8')
    {
        $internalErrors = libxml_use_internal_errors(true);
        $disableEntities = libxml_disable_entity_loader(true);
        $dom = new \DOMDocument('1.0', $charset);
        $dom->validateOnParse = true;
        set_error_handler(function () { throw new \Exception(); });
        try {
            // Convert charset to HTML-entities to work around bugs in DOMDocument::loadHTML()
            $content = mb_convert_encoding($content, 'HTML-ENTITIES', $charset);
        } catch (\Exception $e) {
        }
        restore_error_handler();
        if ('' !== trim($content)) {
            @$dom->loadHTML($content);
        }
        libxml_use_internal_errors($internalErrors);
        libxml_disable_entity_loader($disableEntities);
        $this->addDocument($dom);
        $base = $this->filterRelativeXPath('descendant-or-self::base')->extract(array('href'));
        $baseHref = current($base);
        if (\count($base) && !empty($baseHref)) {
            if ($this->baseHref) {
                $linkNode = $dom->createElement('a');
                $linkNode->setAttribute('href', $baseHref);
                $link = new Link($linkNode, $this->baseHref);
                $this->baseHref = $link->getUri();
            } else {
                $this->baseHref = $baseHref;
            }
        }
    }
