### ISSUE TITLE
[Process] (Unwanted?) BC break with strict typing

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#28609]
**Symfony version(s) affected**: 4.1.4

**Description**  

If you create a process with an array command-line containing null variable, it will fail:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::escapeArgument() must be of the type string, null given in /code/vendor/symfony/process/Process.php:1533
Stack trace:
#0 [internal function]: Symfony\Component\Process\Process->escapeArgument(NULL)
#1 /code/vendor/symfony/process/Process.php(262): array_map(Array, Array)
#2 /code/vendor/symfony/process/Process.php(200): Symfony\Component\Process\Process->start(NULL, Array)
#3 /code/test.php(13): Symfony\Component\Process\Process->run()
#4 {main}
```

**How to reproduce**  

```php
<?php

declare(strict_types=1);

require_once __DIR__.'/src/autoload.php';

$process = new \Symfony\Component\Process\Process([
    'ls -la',
    'test',
    null,
    'something',
]);
$process->run();
```

**Possible Solution**  

I know it's a new major, but I found nothing about this issue on the upgrade guide. Plus, the error is not very explicit.

Two possibility:

1. Cast all null parameter to string before using `escapeArgument` to have the same behavior as Symfony 3.
2. Complete the upgrade guide and prevent the error by a more explicit one.

**Comment by Soullivaneuh** [comment]
BTW, you are still casting to string here to check empty arguments: https://github.com/symfony/symfony/blob/3cd411af3e5a0fb74a10f2fbb3575c180b6af1b2/src/Symfony/Component/Process/Process.php#L1575-L1577

But this is now not efficient with the strict typing, confirming a bug to me.

**Comment by stof** [comment]
Well, I'm wondering whether `null` was ever meant to be supported in the array syntax of the Process class, even in 3.x

**Comment by Soullivaneuh** [comment]
@stof I don't know, but it was. BTW the current string casting inside the method seems to show us it is.
