### ISSUE TITLE
Symfony 4 throws error when using expanded on EntityType

### ISSUE THREAD

**Issue by OmegaZero** [symfony/symfony#28602]
Symfony 4.1.4

**Description**  
Using 'expanded'=>true on EntityType causes the error "Warning: spl_object_hash() expects parameter 1 to be object, string given".  Removing the 'expanded' option resolves it.

**How to reproduce**  
Entity:
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RolesRepository")
 */
class Roles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $role_id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $role_name;

    public function getRoleId(): ?int
    {
        return $this->role_id;
    }

    public function setRoleId(int $role_id): self
    {
        $this->role_id = $role_id;

        return $this;
    }

    public function getRoleName(): ?string
    {
        return $this->role_name;
    }

    public function setRoleName(string $role_name): self
    {
        $this->role_name = $role_name;

        return $this;
    }
}
```
Type:
```
            ->add('roles', EntityType::class, array(
                'class' => Roles::class,
                'choice_label' => 'roleName', // property to use as the option value
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('c');
                },
                'multiple' => true,
                'expanded' => true,
            ))
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by OmegaZero** [comment]
I can, yes.  I made one but when I try to zip up the folder I get a permission denied error on FileQueryWriteTest.php.  Should I just overwrite the permissions or is there some better way to zip this up to send to you (i.e. just the /src folder?)

**Comment by OmegaZero** [comment]
Ok done

https://github.com/OmegaZero/ExampleBug

**Comment by xabbuh** [comment]
Your `getRoles()` method (which is used when the data is mapped to the form) does not return an array of `Roles` objects, but only their names. This does not work.

Please take a look at #28132 which tackles a similar problem and contains some more information on how to solve it. I am closing here as there is nothing to fix. Thank you for understanding.

**Comment by OmegaZero** [comment]
Thanks.  It makes sense for that unfortunately that entity also controls the security login.  I guess I need to do something like this https://stovepipe.systems/post/decoupling-your-security-user although this seems like old code or something, I have no idea how to make it work.  Back to the drawing board.
