### ISSUE TITLE
[RFC] Improve bean validation

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28611]
**Description**  

I'd like to propose a few steps to improve the validation constraints:

- Deprecate empty strings (`""`) currently happily passing in string constraints (e.g. `Email`)
  - https://docs.jboss.org/hibernate/stable/beanvalidation/api/javax/validation/constraints/Email.html
- Deprecate non string values in `NotBlank` / `Blank` and 'whitespaced' strings passing (`"   "`)
  - https://docs.jboss.org/hibernate/stable/beanvalidation/api/javax/validation/constraints/NotBlank.html
  - allow for null (#27876)
- Consider `NotEmpty` / `Empty` as the current `NotBlank` / `Blank` constraints
  - https://docs.jboss.org/hibernate/stable/beanvalidation/api/javax/validation/constraints/NotEmpty.html
  - I dont think we should add these (but favor specific constraints) as `empty` in PHP is different as described above (ints, bools, etc). Not sure we should follow either one :) thus possible confusion

If this happens we'd do simply

- `@Email`
- `@NotNull @Email`
- `@NotNull @Length(min=3) @NotBlank`
- `@NotNull @NotBlank`
- `@Type(array) @Count(3)`

Thoughts?

**Comment by zanbaldwin** [comment]
Possible duplicate of #27876

**Comment by ro0NL** [comment]
I'd say #27876 is a subset of what's described here

**Comment by zanbaldwin** [comment]
Personally, I'd like to cause as minimal BC breaks as possible - it's possible to bring in these changes with new constraints with better naming, but if you're aiming for `5.0` then at least it's the best possible time to introduce these changes.

**Comment by ro0NL** [comment]
now a feature :man_shrugging: 

https://symfony.com/blog/new-in-symfony-4-4-misc-improvements-part-1#consider-empty-strings-not-valid
