### ISSUE TITLE
[Console][QuestionHelper] Incorrect exception handling in validateAttempts method

### ISSUE THREAD

**Issue by aedart** [symfony/symfony#28617]
**Symfony version(s) affected**: 4.1.*

**Description**  
`\Symfony\Component\Console\Helper\QuestionHelper::validateAttempts` handles validation exception incorrectly. It an `Exception` is captured, then it is not re-thrown, meaning that certain validation exception are handled incorrectly. The end-user will only receive a message stating that the command has "aborted".

```php
    private function validateAttempts(callable $interviewer, OutputInterface $output, Question $question)
    {
        $error = null;
        $attempts = $question->getMaxAttempts();
        while (null === $attempts || $attempts--) {
            if (null !== $error) {
                $this->writeError($output, $error);
            }
            try {
                return \call_user_func($question->getValidator(), $interviewer());
            } catch (RuntimeException $e) {
                throw $e;
            } catch (\Exception $error) {
                 // PROBLEM IS HERE
            }
        }
        throw $error;
    }
```

**How to reproduce**  
1. Ask a hidden question, using the `QuestionHelper`, add a validator that throws an exception with a custom message, e.g. validate input string length
2. Test the command with invalid input, e.g. a too short string

Expecting to see a custom fail message.
Actual message states "aborted"

**Possible Solution**  
Fix the `validateAttempts` to handle `\Throwable` instance and re-throw the exception.
Symfony version 4.1.x does require php verison 7.1 after all.

```php
            try {
                return \call_user_func($question->getValidator(), $interviewer());
            } catch (\Throwable $error) {
                throw $e;
            }
```

**Additional context**  
The proposed solution is nothing more than a "hot-fix". It will conflict with the "max-attempts" logic.
Someone, please refactor this method, as it does appear to be a bit outdated - it simply does not fulfil it's purposes for validating and respect a maximum amount of attempts, if such is given.

**Comment by chalasr** [comment]
I'm unable to reproduce. 
Added the following code to the `bin/console` file and running the `foo` command, I get the expected validation message.

```php
$application->register('foo')->setCode(function (\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output) {
    $q = new \Symfony\Component\Console\Question\Question('Give me a loooooong string');
    $q->setHidden(true);
    $q->setValidator(static function ($v) {
        if (5 > \strlen($v)) {
            throw new \UnexpectedValueException('Too short!');
        }
        return $v;
    });

    (new \Symfony\Component\Console\Helper\QuestionHelper())->ask($input, $output, $q);
});
```

Can you provide a reproducer?

**Comment by aedart** [comment]
Hi @chalasr 
It took me a long time to attempt and reproduce the issue locally on my machine. The strange behaviour happened on my workstation. It appears that the issue is xdebug related, in that when reassigning the `$error` variable, then exception handling is somehow thrown out of scope (or something like that).
The code execution ends up in line 118, inside the `QuestionHelper` component. The reasons for this is way beyond my skill and knowledge about PHP vs. xdebug behaviour.
I'm sorry for wasting your time on that matter - I failed to notice that xdebug was enabled.

**Comment by chalasr** [comment]
@aedart No worries! Closing here
