### ISSUE TITLE
Typed env var and allow nullable

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#28618]
**Description**  
For now, DotEnv component don't allow `null` as value and don't type values.
We can type value when reading, with `%env(int:foo)%`. But if an env var is used more than one time, we have to duplicate type hint at each read.

Can we take that problem (typing at reading) on the other side: typing at declaration, not at reading ?

For null value, it's impossible for now, and that's a problem. Maybe we can have a syntax to allow null at declaration ?

**Example**  
`/.env`
VAR_INT=`!int:`12
VAR_FLOAT=`!float:`12.2
VAR_STRING=`!string:`foo
VAR_STRING_2=foo
VAR_ALLOW_NULL=`!?string:`null
VAR_ARRAY=`!array:`[!int:12, !string:foo]

**Problems**

As DotEnv is installed for dev env by default, how can we do to parse env var in prod env ?

**Comment by steevanb** [comment]
I know i can use parameters to allow null par an env var. But that's weird to define and env var 2 times, no ?

And i really don't like to type my env var at each read, that's duplicate code and i don't understand why i have to do that at reading.

Imagine you do that in PHP, each time you want to use a variable:
```php
$foo = '123';
$service->bar((int) $foo);
```

**Comment by ro0NL** [comment]
> But that's weird to define and env var 2 times, no 

not to me. That's actual vs. default values.

> i don't understand why i have to do that at reading.

because the same env can be processed differently, per case. So to share a single env prefix using a intermediary parameter will do.

> each time you want to use a variable:

same thing actually :) you cast on read or define an intermediary variable: `$bar = (int) $foo`.

**Comment by steevanb** [comment]
I don't agree with that, but if you want.

I will not use env vars for now, too much duplications.

Thanks !

**Comment by nicolas-grekas** [comment]
We should not make the content of the `.env` file diverge from its origin: it's a shell file that defines values for real environment variables. There should be no extra requirement to "parse" it. The responsibility of interpreting the env is as it should right now: the app does it.
:-1: on my side;

**Comment by chalasr** [comment]
Same for me, DotEnv should not be the one altering values of loaded env vars. 👎

**Comment by fabpot** [comment]
I agree as well, DotEnv should only replicate what real env vars can do, and they can only be strings.
