### ISSUE TITLE
Console component: Incompletely cleared section when a question is asked

### ISSUE THREAD

**Issue by Cmytxy** [symfony/symfony#28615]
**Symfony version(s) affected**: 4.1.4

**Description**  
When using `\Symfony\Component\Console\OutputConsoleSectionOutput::clear()` after displaying a Question (regardless whether with or without `\Symfony\Component\Console\Style\SymfonyStyle`) the last previous line of the section isn't cleared.

**How to reproduce**  
```php
class SomeCommand extends \Symfony\Component\Console\Command\Command
{
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $section = $output->section();

        $section->writeln('aaa');
        $section->writeln('aaa');
        // Output:
        // aaa
        // aaa

        $question = new Question('???');
        $questionHelper = new QuestionHelper();
        $questionHelper->ask($input, $section, $question);
        // Output:
        // aaa
        // aaa
        // ???

        $section->clear();
        $section->writeln('bbb');
        $section->writeln('bbb');
        // Output:
        // aaa
        // bbb
        // bbb
    }
}
```

**Possible Solution**  
I didn't found any.

**Comment by chalasr** [comment]
Status: reviewed

**Comment by chalasr** [comment]
The issue is that the section output does not know about lines written to stdin (it does not include it in its internal line counter, only lines written through the output are known), hence it erases a too little number of lines. 
Dunno how to fix that yet. \cc @pierredup

**Comment by chalasr** [comment]
See #28638
