### ISSUE TITLE
How to connect with symfony slack community forum?

### ISSUE THREAD

**Issue by devkbsc** [symfony/symfony#28620]
Hello,
I have been connected until few days before on slack symfony group chat!  Unfortuantly my computer got formetted! 

So, i have lost the URL to reconnect! Does anybody can provide it?

**Comment by chalasr** [comment]
Hey, the slack is https://symfony-devs.slack.com/. You can find it on https://symfony.com/support

**Comment by devkbsc** [comment]
Thank you!
