### ISSUE TITLE
[RFC] Symfony component implementing PSR-18

### ISSUE THREAD

**Issue by kejwmen** [symfony/symfony#28628]
Hi.
Our apps need http client very often, and [PSR-18](https://github.com/php-fig/fig-standards/blob/master/proposed/http-client/http-client.md) is on the horizon.

What do you think about Symfony component implementing that standard? 
We already have HTTPlug (PSR discussions started there), but I believe that Symfony component can help with standard adoption.

In my opinion (after PSR-18) we will still miss two important interfaces, and Symfony can introduce them as part of symfony/contracts and create a reference implementation with great DX.

First one is about client-side middlewares. 
Like PSR-15, meant to prepare client-side requests.
The second one is about http client factory that accepts middlewares.

WDYT?

**Comment by kejwmen** [comment]
PSR-18 is now accepted 🎉

**Comment by stof** [comment]
I'm not sure the 2 interfaces you describe are actually missing. The middlewares you describe could implement PSR-18 itself through decoration. That's really similar to what https://stackphp.com/ did in the server-side using HttpKernelInterface. they haven't needed a new interface.
And then, this invalidates the need for the second one if we don't need the first one.

**Comment by kejwmen** [comment]
That's something I didn't think about, thanks!

Can't we say the same thing about `RequestHandlerInterface`? Or are there some details that make it different?

In this case separate interface sounds more convenient (more precise about responsibility) but I was wrong it's mandatory.

Thanks again for input.

Do you have any thoughts about Symfony component implementing this standard?

**Comment by nicolas-grekas** [comment]
See #30413
