### ISSUE TITLE
-es option for command not working

### ISSUE THREAD

**Issue by kcassam** [symfony/symfony#28623]
**Symfony version(s) affected**: 3.4.15

**Description**  
If I create a command option with shortcut -es (or -e+any letter), il will be confused with -e (--env) option.

**How to reproduce**  
```
$ bin/console headoo:delete:shop --help
Usage:
  headoo:delete:shop [options]

Options:
[...]
  -e, --env=ENV                       The Environment name. [default: "dev"]
  -es, --establishment=ESTABLISHMENT  Which Establishment (table Establishment) ex --establishment=2483
[...]

$ bin/console headoo:delete:shop -es 1677

In FileLocator.php line 44:
                                                                      
  The file "/var/www/headoo/app/config/config_s.yml" does not exist.  

```

**Comment by stof** [comment]
multi-letter shortcuts don't play well with the fact that the POSIX convention allows to merge shortcuts together or to merge the shortcut and its value (depending on whether the first shortcut expects a value or no).

Looking at the code parsing the options, multi-letter shortcuts don't work at all (even without conflicts with `-e`). And I confirmed this in my testing.

I think we are missing a validation at configuration time to forbid shortcuts when `strlen($shortcut) > 1`.

**Comment by chalasr** [comment]
@stof we can't forbid shortcuts longer than 1 char as we rely on it for the special `-vvv` shortcut (`new InputOption('foo', 'f|ffff|ff')` and `new InputOption('foo', ['f, 'ffff', 'ff']);` is supported, sadly).

We could check that it does not contain different chars though, that indeed does not work at all.
