### ISSUE TITLE
[Routing] Bad DX when generate a null named route

### ISSUE THREAD

**Issue by matthieumota** [symfony/symfony#28634]
**Symfony version(s) affected**: 4.1.x

**Description**  
We know that UrlGenerator is cached on Symfony. Code is generated by [PhpGeneratorDumper](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Routing/Generator/Dumper/PhpGeneratorDumper.php#L110) in Routing component. We can easily see that if ```$name``` arg is null and ```$locale``` exists in context (_locale parameter), RouteNotFoundException will not be thrown.

**How to reproduce**  
Easy, install skeleton, install translations and call ```dump($this->container->get('router')->generate(null));```, you will see "Undefined index: .en"

**Possible Solution**  
I already write a fix but... I see that [PhpGeneratorDumper](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/Dumper/PhpGeneratorDumper.php#L110) is greatly improved on master, so what I can do ? Purpose my fix on 4.1 ? (Feature code only exists from 4.1 not before) Or we simply wait 4.2 release and code will fallback to 4.1 with branch strategy ?

**Comment by nicolas-grekas** [comment]
Which line is throwing the notice?

**Comment by matthieumota** [comment]
It's [line 123](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Routing/Generator/Dumper/PhpGeneratorDumper.php#L123) due to non existent array key (Route name).

**Comment by stof** [comment]
`$this->container->get('router')->generate(null)` is an invalid usage of the API. The expected argument type is `string`. So we make no guarantee about the exact behavior in such case.

**Comment by xabbuh** [comment]
closing as explained by @stof

**Comment by nicolas-grekas** [comment]
That used to throw in 3.4, here is a fix: #29191.
