### ISSUE TITLE
@Route("/sitemap.xml") does not work

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#28630]
**Symfony version(s) affected**: 4.1.4

**Description**  
I'm experiencing a strange behavior, I developed a controller that take care of generating a sitemap. I set up a route with annotation, but when I test it, the controller seems to not be executed, and I get a XML related error in the web browser as no XML content is returned.

**How to reproduce**  
With these routes it doesn't work:
```
@Route("/sitemap.{_format}", name="sitemap", requirements={"_format" = "xml"})
@Route("/sitemap.xml", name="sitemap")
```
With this route it works:
```
@Route("/sitemap2.xml", name="sitemap")
```

**Possible Solution**  
No idea.

Thank you for your help!
Regards,

Fabien

**Comment by javiereguiluz** [comment]
I know it sounds silly, but this happened to me once so I'm going to ask you: is it a `sitemap.xml` file stored in the `public/` directory? If it exists, your web server will use that instead of redirecting to `app.php` to execute the Symfony app.

**Comment by fabienlem** [comment]
Ooooh... Silly, yes but that was it.
Thank you a lot! I'm closing this issue.
