### ISSUE TITLE
[Template routing] Error message unclear when Twig fail to load a template route

### ISSUE THREAD

**Issue by LucileDT** [symfony/symfony#28643]
**Symfony version(s) affected**: 3.4.15

**Description**  
An error `There are no registered paths for namespace "App".` is thrown when the Twig engine fail to load a template because of an error in the AppBundle resources folder tree.

Another symptom is that the command `bin/console debug:twig` is not showing the `@App` namespace in the `Loader Paths` list.

Problem: the error thrown should be something like "Twig is unable to find the template path, looked into..." because the path is broken and thus there is no namespace @App. The user should be informed of the root cause, not the consequences.

**How to reproduce**
- In an AppBundle controller action with `/` route, render a twig template using:
```php
return $this->render('@App/template.html.twig', []);
```
- In `AppBundle`, create a folder tree `Ressources` / `views` (note the two -s in `Ressources`, I'm French, we write ressource, that's where the error is coming from in the first place)
- In `AppBundle` / `Ressources` / `views`, create a file `template.html.twig`
- Call the page `127.0.01:8000`

**Possible Solution**  
Maybe create a more precise error message? Or add something in the documentation about this error message?

**Comment by xabbuh** [comment]
I am not sure if we can change that in the Symfony code. IIRC the exception itself is thrown by Twig.

**Comment by LucileDT** [comment]
Should I create an issue in the Twig repository?

**Comment by xabbuh** [comment]
That would be nice. I am closing here as explained.

**Comment by Miel2000** [comment]
THANKS
