### ISSUE TITLE
WindowsPipes is not compatible with php 7.3

### ISSUE THREAD

**Issue by SailorMax** [symfony/symfony#28655]
**Symfony/Process version(s) affected**: 4.1.4

**Description**  
PHP 7.3 allow `unlink()` 'locked' file at Pipes/WindowsPipes.php#L57 and return `true`.
In result if start 2 processes one by one, second process will delete file of previous one.
Possible this is error in PHP, but I can't create good bug report for PHP developers.

**How to reproduce**  
I use `fastest` to use with phpunit in async mode. If run 2+ tests, first always return error.

**Possible Solution**  
before `for ($i = 0;; ++$i) {` add
```php
if (!isset($GLOBALS["sf_proc_i"]))
	$GLOBALS["sf_proc_i"] = 0;
else
	$GLOBALS["sf_proc_i"]++;
$i =& $GLOBALS["sf_proc_i"];
if ($i > 1024)
	$i = 0;
```

plus replace `for ($i = 0;; ++$i) {` on `for (;; ++$i) {`

**Additional context**  
no

**Comment by nicolas-grekas** [comment]
Can you please check if #28689 fixes your issue?

**Comment by nicolas-grekas** [comment]
Oh, and tell us what the error is if not?

**Comment by SailorMax** [comment]
No, this fix did not help. With it logic looks more correct (tries new $i for all pipes, not only for second, for example), but it did not fix the problem.
The real problem in first `!unlink($file)`. In PHP 7.3 it successfully delete the file, which in use by first process, and start to use it for second process.

**Comment by selcuk-karateke** [comment]
Can I uninstall this package?
