### ISSUE TITLE
Type error: Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean given

### ISSUE THREAD

**Issue by hanzx** [symfony/symfony#28657]
**Symfony version(s) affected**: 3.4.16

**Description**  
After update Symfony from v.3.4.15 to 3.4.16

**How to reproduce**  
Type error: Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean given, called in /var/www/artikul/website/var/cache/dev/ContainerDhxuzns/appDevDebugProjectContainer.php on line 1586

**Comment by xabbuh** [comment]
Can you please provide some instructions on how to reproduce this issue?

**Comment by hanzx** [comment]
composer update :) its all

**Comment by MWMathieu** [comment]
Same problem just composer update

**Comment by dpfaffenbauer** [comment]
Yep, same here. Doesn't even apply to just Twig, also happens to other private services. I tracked the problem down, and I think it comes from this commit: 

https://github.com/symfony/symfony/commit/e5c54053c430c9ead09a0a72fe464aeb98f486c8#diff-f7b23d463cba27ac5e4cb677f2be7623

**Comment by crazyball** [comment]
Same problem here since 3.4.16, all my private services are returning boolean instead of themselves.

**Comment by NathanVss** [comment]
Same problem here.

**Comment by yellow1912** [comment]
This is the 2nd time we get this issue with private services, it break tons of things and is a serious bug. I think this is a very serious issue and some kind of testing code must be put in place to prevent this from happening in the future.

**Comment by xabbuh** [comment]
I am going to close here. Even if this issue is newer than #28658 the other one is easier for us to handle as it contains a reproducible example. Thank you for reporting. 👍

**Comment by suknaic** [comment]
Same problem here.

```
$container['view'] = function ($container) {
    $view = new \Slim\Views\Twig(__DIR__ . '/../templates');

    $view->addExtension(new \Slim\Views\TwigExtension(
        $container->router,
        $container->request->getUri()
    ));

    $view->addExtension(new \Twig_Extension_Debug());
    $view->enableDebug();

    $view->getEnvironment()->addGlobal('flash', $container->flash);

    return $view;
};
``
Expected type 'Twig_ExtensionInterface'. Found 'Slim\Views\TwigExtension'.intelephense(10006)

**Comment by xabbuh** [comment]
Please open a new issue with some example that allows to reproduce what you experience.

**Comment by afilina** [comment]
I got this issue after I updated composer packages. I then ran `bin/console cache:clear` for this error to go away. I hope this helps someone.

**Comment by andres030405** [comment]
tienes  @afilina , gracias a mi me funciono

**Comment by andres030405** [comment]
en el directoria raiz se tiene que ejecutar en la consola: php bin/console cache:clear --env=prod

**Comment by SoheibOuad** [comment]
Hi everyone , i have this error when i lunch my application symfony , can anyone help me ? : 
Type error: Argument 1 passed to Twig\Environment::tokenize() must be an instance of Twig\Source, string given, called in /mnt/c/Users/sol/Documents/gestion_projet/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php on line 34
