### ISSUE TITLE
Symfony bundle default configurations

### ISSUE THREAD

**Issue by lightcoresystems** [symfony/symfony#28650]
Hello, I was looking for an answer but i havent find anything helpful..

I am writing a simple symfony bundle, but I have a problem with changing default configurations. I mean that I want to use yaml translations (not xliff), yaml doctrine mappings (not annotations), yaml validation (not annotations), etc. 

Is there any possibility to change this configuration inside a bundle? 
I want my bundles to be self configured, I dont want to configure doctrine, translations, etc inside my main app.

Thanks for help

**Comment by sstok** [comment]
This seems more like a support question that a bug or feature request. 
Please use one of the provided support channels https://symfony.com/support

And please note that YAML support for Doctrine is deprecated and only XML and Annotations will be supported in the future. _The reason behind this is that Doctrine needs to allow customizing the mapping information and therefor cannot fully assert the document structure like Symfony does with the Config component, and then one misplaced space can cause allot of pain of frustration (been their). XML is not format sensitive and can use XSD for validate the structure while still allowing extension._

**Comment by xabbuh** [comment]
As @sstok we don't use GitHub for support so I am going to close here. Thank you for understanding.
