### ISSUE TITLE
[DependencyInjection] Wrong method call order

### ISSUE THREAD

**Issue by tsantos84** [symfony/symfony#28654]
**Symfony version(s) affected**: 4.1.5

**Description**  
Symfony DI is dumping the container in wrong order causing a `Undefined variable b` exception.

**How to reproduce**  
I've created a gist containing the XML version of the entire container and the compiled PHP service that is causing the error:

https://gist.github.com/tsantos84/13683b3341b76a2d2991540e2d12c2c0

In this gist you can see that the method calls is called before the service instantiation. (lines 16 and 20).

**Comment by nicolas-grekas** [comment]
Thanks, I've isolated your reproducer in a smaller reproducing test case. The issue also exists on 3.4. Now wondering about the fix.

**Comment by tsantos84** [comment]
Hi @nicolas-grekas, thanks for checking this issue. Let me know if I can help you in this case.
