### ISSUE TITLE
Bad "configurator" word in Guard authenticator errors

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#28667]
**Symfony version(s) affected**: 2.8.*

**Description**  
A few error messages use the word "guard configurator" - it should be "guard authenticator". I think this is just an old error I created :). 

Here are 2 places that should be updated: 

* https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Guard/Firewall/GuardAuthenticationListener.php#L94

* https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/GuardAuthenticationFactory.php#L115

**Comment by AchillesKal** [comment]
Hey @weaverryan I would like to help on this one!
