### ISSUE TITLE
[Validator] Email validation false-positive due to relative host

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#28665]
**Symfony version(s) affected**: any?

**Description**  
As warned in [the comment to `checkdnsrr()` docs](https://secure.php.net/manual/en/function.checkdnsrr.php#119969), one should pass a fully qualified domain name to get correct results, i.e. `symfony.com.` instead of `symfony.com`

99.9% of the time users do not put a dot at the end of their email which leads to incorrect checks.

**Possible Solution without breaking BC**  
1. Add a config value `framework.validation.make_host_absolute = null` (like [`framework.validation.make_host_absolute`](https://symfony.com/doc/current/reference/configuration/framework.html#email-validation-mode)). If not set explicitly to `true` or `false` a deprecation is shown: `Not setting a value explicitly is deprecated. Will be true by default since 5.0`.
1. Add `EmailValidator::__construct(..., ?bool $makeHostAbsolute = null)` with same BC logic.
1. Add `@Email::?bool $makeHostAbsolute = null` to be able to override validator's default value when needed.
1. `if ($makeHostAbsolute && '.' !== mb_substr($email, -1)) { $email .= '.'; }`

Ready to work on the PR.

**Comment by ro0NL** [comment]
ref https://github.com/symfony/symfony/pull/27559#issuecomment-409875895, #25516

**Comment by vudaltsov** [comment]
@ro0NL , thank you for referencing issues. I failed to find them before opening my own, probably used wrong keywords.

Then at least I would suggest to warn users about these problems in [docs](https://symfony.com/doc/current/reference/constraints/Email.html)...

**Comment by ro0NL** [comment]
we might consider deprecating the options for Email as well 

cc @fabpot

**Comment by xabbuh** [comment]
:+1: for deprecating them
