### ISSUE TITLE
Console application returns exit code 0 on any exception

### ISSUE THREAD

**Issue by perprogramming** [symfony/symfony#28666]
**Symfony version(s) affected**: 4.1.5

**Description**  
The refactoring in commit https://github.com/symfony/symfony/commit/8805cfdf8d4ba6776cfd74e290d8d17b0ae1b62d by @fabpot broke the exit code handling for exceptions. Instead of calling the "exit" function with the correct error code the class simply returns the exit code from the run method. As there is no further code in the default "bin/console" script, php will end with exit code 0 indicating a success.

**How to reproduce**  
Simply throw any exception within a symfony command and check the exit code of the console script.

**Possible Solution**  
Remove the line "return $exitCode", which is line 163 in Console Application in version 4.1.5 (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L163).

**Comment by perprogramming** [comment]
The pull request https://github.com/symfony/symfony/pull/28664 was just created to fix this issue.

**Comment by xavier-rodet** [comment]
I'm using Symfony 4.3.4 an still got this issue, shouldn't it be fixed ?

**Comment by xavier-rodet** [comment]
Oh nevermind,

I just realized i was catching exception to use [console styling](https://symfony.com/doc/current/console/style.html) :

 ```php
   protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);
        $name = $input->getArgument('name');

        try {
            $this->execWorker($name);
            $io->success(sprintf('Worker %s is now running !', $name));
        } catch (\Exception $exception) {
            $io->error(sprintf('Worker failed to run : %s', $exception->getMessage()));
        }
    }
```

Sorry guys 🤦‍♂
