### ISSUE TITLE
[DI] Syntax error exception in Symfony 4.1.5 

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#28660]
**Symfony version(s) affected**: 4.1.5

**Description**  

Upgrading to Symfony 4.1.5 breaks the entire app. In fact, this is the second Symfony release in a row that comes with a broken DI component (https://github.com/symfony/symfony/issues/28355).

```
(1/2) ErrorException
Notice: Undefined variable: f

in srcDevDebugProjectContainer.php line 891
at srcDevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService()
in srcDevDebugProjectContainer.php line 983

(2/2) Twig_Error_Syntax
Unknown "abbr_class" filter.

in exception.html.twig line 6
at Twig_ExpressionParser->getFilterNodeClass('abbr_class', 6)
in ExpressionParser.php line 470
```

**How to reproduce**  

Just run `composer update`.

**Comment by xabbuh** [comment]
Same as #28654?

**Comment by nicolas-grekas** [comment]
Likely, closing as duplicate.
