### ISSUE TITLE
[DI] Unable to override UrlGenerator

### ISSUE THREAD

**Issue by wimpheling** [symfony/symfony#28663]
**Symfony version(s) affected**: 4.1.5.2

**Description**  
I want to override Symfony Framework's Url Generator.

As it is created directly in the cache by the Router, and the router.options.generator_class parameter is no longer available, I've tried redeclaring another router service with the correct generator_base_class, and then redeclare the router.default alias to link to my new service.

Unfortunately, even with the exact same parameters for the new service, when I redefine the alias I get this error : 

> In DelegatingLoader.php line 37:                                   
>  Cannot load resource "kernel::loadRoutes". 

**How to reproduce**  

I've set up a test project here to reproduce the bug : https://github.com/wimpheling/symfony-url-generator-bug

A simple ` bin/console cache:clear ` will reproduce the bug

**Possible Solution**  

When I leave the default config, and I directly edit the srcDevDebugProjectContainerUrlGenerator.php to extend my custom UrlGenerator class, it seems to work fine.

I also have tried to use the decorator pattern, but to no success either.

Of course I may just not have found the correct way to redefine it, but in previous versions (I'm porting an app from symfony 2.5) you could override the generator by changing a simple parameter, if it is not a bug maybe the documentation could be updated to give more indications.

**Comment by stof** [comment]
Well, if you use decoration, you should do it on the `router` service itself (which is the public service implementing UrlGeneratorInterface. Just make sure that your decorator decorates the whole RouterInterface).
The dumped optimized matchers and generators are not exposed as supported extension point. they are considered purely internal to allow us to refactor them as needed.

**Comment by Microtribute** [comment]
@nicolas-grekas Is it still relevant in Symfony 5.1.3?
