### ISSUE TITLE
Symfony 3.4.16 crashes with twig lint

### ISSUE THREAD

**Issue by hectorprats** [symfony/symfony#28671]
**Symfony version(s) affected**: 3.4.16

**Description**  
/usr/bin/php ./bin/console lint:twig src
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean given, called in /var/cache/dev/ContainerLpxnnt7/appDevDebugProjectContainer.php on line 880 in /vendor/twig/twig/lib/Twig/Environment.php:670

**How to reproduce**  
I just updated the symfony library and pass twig lint.

If I get back, it pass.

**Comment by chalasr** [comment]
I'm closing here as this is a duplicate of https://github.com/symfony/symfony/issues/28658.
Thanks for reporting!
