### ISSUE TITLE
[Form] Form parent can't be accessed if form has a child named "parent" in Twig.

### ISSUE THREAD

**Issue by moynzzz** [symfony/symfony#28686]
**Symfony version(s) affected**: All

**Description**
If you have a form that has a child named parent there is no possible way to access the parent variable in Twig.

**How to reproduce**  
Create a simple form and have a child named parent. Then try in the twig template to access the actual form parent. The `form.parent` returns the child.

The problem with this issue is that it is related to how twig accesses properties of an object not specifically to the form component because in PHP there will be no problem to access the parent form or the child named parent. Should I open an issue in the twig repository instead?

Note that this works the same with all other `FormView`'s properties `vars` and `children`.

I found this bug when I tried to fix this issue EasyCorp/EasyAdminBundle#2228 and more specific information can be found there.

**Comment by dmaicher** [comment]
Just call form.getParent() directly?

**Comment by moynzzz** [comment]
There is no such method in `FormView`.

**Comment by dmaicher** [comment]
Oh I'm sorry I confused it. Indeed it does not exist :confused:

**Comment by moynzzz** [comment]
I created a sample repository to reproduce this behaviour https://github.com/moynzzz/bug-reproducer-symfony-28686 and the only solution that I found to the problem is to create a custom form extension to return the parent form view.

**Comment by xabbuh** [comment]
I think for such edge cases you rather need to create a Twig extension that allows to access the parent form. Usually, that's not something that should need to be done in a template. If you just need to find out whether your form is the root form (i.e. it has no parents), you can use the `rootform` test. You can find some background information about this in #18882, #25236 and some other related tickets.

**Comment by moynzzz** [comment]
@xabbuh My idea is to check for the allow_delete variable of the parent form see the EasyAdminBundle issue if you need more information. The rootform test is at no use in this case.

**Comment by xabbuh** [comment]
See #28812 which proposes to add a `getParent()` method to the `FormView` class. For now, I am afraid you will have to live with a custom Twig function/filter to get the parent form in such cases.
