### ISSUE TITLE
Symfony Encore with Nuxt.js 

### ISSUE THREAD

**Issue by khom-outsourcify** [symfony/symfony#28687]
Sorry for my English
I'm front end develop and I newbie with symfony 

**Description**  
Now we can connect Symfony with Vue by Encore.
But! 
How to connect Symfony  encore with Nuxt.js  ?

Do you have an example ? 

Many Thanks for your answer

**Comment by AchillesKal** [comment]
Hey there!

I don't think connecting Nuxt.js with Encore would be a good idea. I am not sure if that's even possible. 

Symfony is great at creating API's, so why not just create the API with Symfony(back-end) and consume it with your Nuxt.js app(front-end). That is what I do.

You can also use the [API Platform ](https://api-platform.com) which is a framework for API's that uses symfony.

**Comment by khom-outsourcify** [comment]
Many thanks for your idea @achillesKal

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by khom-outsourcify** [comment]
I understand :) thanks @xabbuh
