### ISSUE TITLE
Q: Override asset files (image) from used bundle

### ISSUE THREAD

**Issue by nea** [symfony/symfony#28684]
Hi

I have read https://symfony.com/doc/current/bundles/override.html and am confident with overriding templates, translations etc.

But how would you go ahead and override an image, e.g. a logo from a bundle? Is this even possible without overriding the template and its used location?

Thanks a lot in advance

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
