### ISSUE TITLE
Add mermaid.js dumper for workflow/DI graphs

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#28685]
Similar to the existing PlantUml dumper, see https://mermaidjs.github.io/

**Comment by kejwmen** [comment]
I would like to implement this, but first we need a tool to build mermaid diagram.

Today I managed to implement basic flowchart with styling: https://github.com/kejwmen/mermaidjs-php/blob/feature/flowchart/tests/Flowchart/FlowchartTest.php, but I'm not sure how we want to handle this on symfony side? 
Can library like this become a dependency?

We need two dumpers in two separate components, so a shared dependency is something we need anyway, right?

**Comment by nicolas-grekas** [comment]
Thinking twice here, it's going to be extra code that won't be maintained well I suppose...
Not worth it. Thanks @kejwmen for your interest.

**Comment by kejwmen** [comment]
Sure. During development of this library I realized it can be pretty complicated. I will think about something unofficial if there is somebody who really needs it.
