### ISSUE TITLE
Multiple decorations and tagged services

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#28682]
**Symfony version(s) affected**: 3.4.16

**Description**  
We have multiple decorations on a service which will be given to a Factory using tagged services. We get on the factory only the first decoration after the original service.

If i get the service by id, the decoration works.

**How to reproduce**  
Create a factory with a argument tagged services. A tagged service have multiple decorations. In the constructor of the factory you get only the first decoration.

**Possible Solution**  
CompilerPass which each all services of the tags and replaces the argument works.

**Additional context**

**Comment by stof** [comment]
Can you provide a reproducing case ?

**Comment by shyim** [comment]
I have created a example repo. Execute the Test.php in src/App/Test.php
Repo: https://github.com/shyim/di-bug

Deco2 is missing on the tagged call, but if i get directly the service with the decorations Deco2 is there.
