### ISSUE TITLE
Can't move uploaded file to root of a protocol

### ISSUE THREAD

**Issue by jackbentley** [symfony/symfony#28680]
**Symfony version(s) affected**: 
`2.8.*|3|4`?

**Description**  
We have setup custom protocols using Flysystem. We tried to move an uploaded file to the protocol by using the built in symfony methods. Unfortunately, the two slashses for the protocol get cut down to a single slash which breaks.

Caused by https://github.com/symfony/symfony/blob/9610d10034223d031d015bb92488d20040ad1725/src/Symfony/Component/HttpFoundation/File/File.php#L118

**How to reproduce**  
Upload a file and, in a controller, try to move it like so:

```php
$upload->move('cutstom-protocol://', 'filename.txt');
// resolves `custom-protocol://` to `custom-protocol:/`
```

**Possible Solution**  
Current work around is to add `./` on to the end of the protocol. However, I'm unsure how well this would be handled for othe Flysystem adapters and custom protocols that don't write directly to the local filesystem.

`custom-protocol://./`

Ideally, this case should be handled. Maybe check to see if the first and last occurance of a slash are equal to `://`?

**Comment by Simperfit** [comment]
doing it for the  EUFOSSA

**Comment by Deuchnord** [comment]
Taking this for EUFOSSA Hackaton :)

**Comment by Deuchnord** [comment]
Could you please provide a reproducer for this, please?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
