### ISSUE TITLE
console commands always exit with status 0 after updating to 3.4.16

### ISSUE THREAD

**Issue by phil-davis** [symfony/symfony#28695]
**Symfony version(s) affected**: 3.4.16

**Description**  

**How to reproduce**  

- have some project installed with ``symfony/console`` 3.4.15
- run some symfony console command, e.g. an example ownCloud console command:
```
php occ user:add aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Enter password: 
Confirm password: 

In Manager.php line 355:
                                                     
  The username can not be longer than 64 characters  

user:add [--password-from-env] [--display-name [DISPLAY-NAME]] [--email [EMAIL]] [-g|--group [GROUP]] [--] <uid>

$ echo $?
1
```
- update to ``symfony/console`` 3.4.16
```
composer update symfony/console
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating symfony/console (v3.4.15 => v3.4.16): Loading from cache
Writing lock file
Generating optimized autoload files
```
- repeat the console command:
```
php occ user:add aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Enter password: 
Confirm password: 

In Manager.php line 355:
                                                     
  The username can not be longer than 64 characters  

user:add [--password-from-env] [--display-name [DISPLAY-NAME]] [--email [EMAIL]] [-g|--group [GROUP]] [--] <uid>

$ echo $?
0
```

**Possible Solution**  

**Additional context**

**Comment by phil-davis** [comment]
This behaviour change happens for all console commands I have tried, so I am hoping that it is easily reproduced by anyone.

My environment is Ubuntu 18.04, with any of PHP 5.6.38, PHP 7.1.22 and PHP 7.2.10 - the behaviour change is the same with all  PHP versions.

**Comment by nicolas-grekas** [comment]
Thanks for the report, it's already been fixed yesterday. #28664

**Comment by phil-davis** [comment]
I just got to the point of commenting out exactly that line! I had looked to see if there was any open issue or PR, but the PR is already merged and closed, so I missed it.

Hopefully 3.4.17 will be released soon :)

**Comment by phil-davis** [comment]
@nicolas-grekas I see that 3.4.* patch releases seem to happen about every month.
For regressions like this, are new patch releases made more quickly?
Or will it be the end of October to get the fix released?

I am just asking because if a fix will be released "real soon now" (tm) then I will keep  3.4.16 in ``composer.lock`` and then bump again to get the fix.

But if not, then I will need to rollback the 3.4.16 composer update.

**Comment by phil-davis** [comment]
We reverted back to symfony 3.4.15 for now.

**Comment by nicolas-grekas** [comment]
you should upgrade to 3.4.17 instead :)

**Comment by phil-davis** [comment]
I assumed that I would have to wait to the end of the month. I see the 3.4.17 release tag 6 minutes ago :)
I will upgrade again as soon as composer finds the new version - thanks.

**Comment by phil-davis** [comment]
``composer update`` locally, 3.4.17 comes, tested console command exit status - works.
Thanks for the super-quick turn-around to get the fix released.
