### ISSUE TITLE
[Form] Enhanced CollectionType with *dynamic* types

### ISSUE THREAD

**Issue by FabienPapet** [symfony/symfony#28692]
**Description**  
Enhanced CollectionType with *dynamic* types

**Example**  
While making web apps for customers, I usually have the same code that is shared along projects:
The use case is simple, 

Assuming I have a Setting object with three properties:

```php
<?php

namespace App\Model;

class Setting
{
    public $id;
    public $type; // can be 'text' 'text' or other
    public $value;
}
```

If I want to build a custom Form with `NumberType` for number `TextType` for text, I always use the following: 

```php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class ExtendedFieldCollectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $form = $event->getForm();
            $data = $event->getData();

            foreach ($data as $name => $value) {
               $type = .....  // depending on type
                $form->add($value->id, $type, [
                    'property_path' => '[' . $name . '].value', // the value property is my setting value
                ]);
            }
        });
    }
}
```

This is not possible (I think) with CollectionType:
- because of the ResizeFormListener which fixes the type to use. 
- because the form field name is form[0][value] and I want something like form[identifier] as field name

So I think a new Form type based on the CollectionType can be a solution
Something configurable like `field_type` as a callback and `field_value` for the value 

WDYT ? I can propose a PR

Here's a related Stackoverflow question: https://stackoverflow.com/a/52390309/1617144

**Comment by xabbuh** [comment]
This sounds like #9835 which was requested in the past and which we considered as something that better fits a third-party bundle.

**Comment by xabbuh** [comment]
I still think this isn't something we want to provide in the core. So I am closing here. But thank you for proposing anyway.
