### ISSUE TITLE
[WebLink] Do not push known assets to the client

### ISSUE THREAD

**Issue by digilist** [symfony/symfony#28698]
The introduction of server push with the WebLinkExtension and the `preload()` function in Twig is a great way to improve web performance.

With the current implementation, the `Link` header is always set and does not consider that the client already knows a specific asset. So in the worst case, the server is pushing the same asset again and again, even though it is already known to the client. So this leads to unnecessary traffic and loading time, especially on small connections.

Actually, the browser has a way to abort server pushes and "say" that it already knows the asset (https://stackoverflow.com/a/29354100/1044527). However, when the browser is ready to abort a transfer, parts of the asset (or the whole asset) might already be transferred. (see https://www.fastly.com/blog/optimizing-http2-server-push-fastly under "Looking ahead")

In the future there might come [Cache Digests](http://httpwg.org/http-extensions/cache-digest.html), that allows clients to inform the server of their cache's content. However, as this proposal is not ready yet, I think there is a need for a temporary solution.

The [H2O webserver](https://h2o.examp1e.net/) solves this problem by setting a cookie with a fingerprint of all pushed assets (based on a Bloom filter) which is called [CASPer (cache-aware server-push)](https://h2o.examp1e.net/configure/http2_directives.html#http2-casper).

> When enabled, H2O maintains a fingerprint of the web browser cache, and cancels server-push suggested by the handlers if the client is known to be in possession of the content. The fingerprint is stored in a cookie named h2o_casper using [Golomb-compressed sets](https://www.imperialviolet.org/2011/04/29/filters.html) (a compressed encoding of [Bloom filter](https://en.wikipedia.org/wiki/Bloom_filter)).

I think a similar solution would be great for Symfony. What do you think?

**Comment by nicolas-grekas** [comment]
Could this be provided as a third party bundle? That'd be best to iterate and adapt to future RFCs on the topic. I'm therefore closing. Please post a link to the bundle/lib if you manage to create one.
