### ISSUE TITLE
ControllerTrait::getUser() remove "final"

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#28715]
Hi guys!

In #24407, all the controller helper methods were marked as final. I think that usually makes sense, but there is a legitimate use-case for overriding `getUser()`, and I do it all the time :). Specifically, I'll override `getUser()` to add the return type for MY `User` for better auto-completion:

```php
use App\Entity\User;

public function getUser(): User
{
    return parent::getUser();
}
```

This is a super convenient thing to be able to do. Should we consider removing the `@final`?

**Comment by nicolas-grekas** [comment]
What about using the `@method` annotation on the class instead?

**Comment by weaverryan** [comment]
I totally should have thought about `@method` :) 

Thanks!
