### ISSUE TITLE
[Validator] [Unique constraint] Symfony, unique entity validator get error without reason

### ISSUE THREAD

**Issue by kotow** [symfony/symfony#28736]
Symfony 3.1.*

My UniqueEntity validator throw errors without reason. When try to create new User I get error that properties username and email are already in use. In database there no such entries with these parameters.

```
/**
 * User
 *
 * @ORM\Table("users")
 * @ORM\Entity
 * @UniqueEntity(fields={"username"}, errorPath="username", message="Username already in use", inheritedFields=true)
 * @UniqueEntity(fields={"email"}, errorPath="email", message="Email already in use")
 * @ORMInheritanceType("JOINED")
 */
class User extends BaseUser implements TwoFactorInterface
{
```
These properties are declared in BaseUser model that is from FOS User Bundle.

```
    $validator = $this->get('validator');
    $errors = $validator->validate($user);
    if (count($errors) > 0) {
        return new Response($this->container->get('serializer')->serialize($errors, 'json'), Response::HTTP_BAD_REQUEST);
    }
    $em->persist($user);
    $em->flush();
```

**Comment by xabbuh** [comment]
Symfony 3.1 does not get any bugfixes anymore. Do you experience the same with Symfony 3.4 or 4.1?If so, can you please create a small example project that allows to reproduce this issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
