### ISSUE TITLE
Handle HEAD requests (not transform them to GET)

### ISSUE THREAD

**Issue by drastik** [symfony/symfony#28743]
**Description**  
This is causing an issue with TUS implementation.  TUS is an excellent new file transfer protocol that supports chunking, parallel uploading, pausing/resuming (even on browser/device close or crash), checksum integrity, and more.  https://tus.io

TUS uses a HEAD request when resuming an upload to get the current status.
Through Drupal 8 (and thereby Symfony 2), I am routing to a Controller that calls the TUS server.
On the HEAD request, it is rewriting to a GET and causing a different response than the client expects, and breaking the integration.

(For a GET response, the tus-php implementation assumes a download file operation).

**Example**  
https://tus.io/protocols/resumable-upload.html#head

(Cross-post apology https://github.com/symfony/symfony/issues/22028):
I originally added this to an existing thread on the subject, but since it is closed, and this is more of a feature request I suppose - I decided to add it here.

**Comment by nicolas-grekas** [comment]
I'm not sure I understand what would need to be done here. Yes, the router considers HEAD and GET the same. But then, the `Request::getMethod()` would return "HEAD" so that your controller can act accordingly. What did I miss?

**Comment by xabbuh** [comment]
@drastik Any chance you can clarify this a bit? :)

**Comment by drastik** [comment]
@xabbuh @nicolas-grekas 

It's been a while since I was in this code, but all I recall is when the TUS client would perform a `HEAD` request, Symfony would respond to it as if it were a `GET`, which causes 2 very different behaviors in TUS.

**Comment by drastik** [comment]
You can see in #22028 a snippet posted where Symfony internally reacts to HEAD as GET.

**Comment by xabbuh** [comment]
I am sorry, but from reading the comments I do not really understand the issue. Could you create a small example application that allows to reproduce it?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by UBERPHP** [comment]
for the reference: https://github.com/symfony/symfony/issues/22028#issuecomment-763705682
