### ISSUE TITLE
ClassExistenceResource::isFresh autoloads classes ignoring missing interfaces

### ISSUE THREAD

**Issue by ausi** [symfony/symfony#28748]
**Symfony version(s) affected**: 4.1.6

**Description**  
While debugging an issue with a class that is missing an interface (contao/contao#89) I was able to reduce the bug to a simple reproduction case with the `ClassExistenceResource::isFresh()` method.

The method autoloads a class even though it implements a missing interface. I’m not sure if this might be bug in PHP too, because loading a class without one of its interfaces should not be possible I think?

**How to reproduce**  

*composer.json*

```json
{
    "autoload": { "classmap": [ "Foo.php" ] },
    "require": { "symfony/config": "4.1.6" }
}
```

*Foo.php*

```php
<?php
class Foo implements NonExistentInterface {
    public static function bar() { var_dump(__METHOD__); }
}
```

*test.php*

```php
<?php
require __DIR__.'/vendor/autoload.php';
$resource = new \Symfony\Component\Config\Resource\ClassExistenceResource('Foo', false);

// The following line autoloads the Foo class,
// even though it implements a non-existent interface
$resource->isFresh(1);

// The following lines would normally result in a ClassNotFoundException for the missing interface.
var_dump((new \ReflectionClass('Foo'))->getInterfaces());
// array(0) {}
Foo::bar();
// string(8) "Foo::bar"
```

**Comment by nicolas-grekas** [comment]
That's PHP, not Symfony, see https://3v4l.org/nYXIQ

**Comment by ausi** [comment]
👍
I will report it to PHP then.

**Comment by nicolas-grekas** [comment]
Thanks, please link the bug here then we can close :)

**Comment by ausi** [comment]
PHP bug: <https://bugs.php.net/bug.php?id=76980>

@nicolas-grekas thank you for the reduced test case!  
I didn’t fully understand what was going on in `ClassExistenceResource::isFresh()` ☺️
