### ISSUE TITLE
kernel.reset seems to be triggered for ESI requests

### ISSUE THREAD

**Issue by dnna** [symfony/symfony#28749]
**Symfony version(s) affected**: Any with kernel.reset tag

**Description**  
When using `esi_render` to render fragments, it seems they are treated as a master request and `kernel.reset` is executed. For more information please check https://github.com/xyNNN/GoogleTagManagerBundle/issues/32#issuecomment-425953228

**How to reproduce**  
Create a service that uses `kernel.reset` tag and use it behind a reverse proxy that supports ESI, then use esi_render to render a fragment.

**Additional context**  
https://github.com/xyNNN/GoogleTagManagerBundle/issues/32#issuecomment-425953228

**Comment by xabbuh** [comment]
This looks expected to me. When you are using ESI with a reverse proxy that supports it, the proxy will send a single request for every fragment.

**Comment by stof** [comment]
Requests sent by the reverse proxy are indeed master requests, not sub-requests.

And when using PHP-FPM, they would be handled by a different PHP process, so no state can be shared in a PHP property for them. If the GoogleTagManagerBundle does not work for such cases, it is this bundle being incompatible with ESI.

**Comment by xabbuh** [comment]
closing as explained
