### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break" [...]

### ISSUE THREAD

**Issue by monocrstl** [symfony/symfony#28750]
**Symfony version(s) affected**: 4.1.6.1

**Description**  
(I'm not sure if this is a bug). I tried to create a new project following what the [Installing & Setting up the Symfony Framework](https://symfony.com/doc/current/setup.html) section of the docs told me to do (run `composer create-project symfony/website-skeleton my-project`). It installed a bunch of dependencies but in the end I got this:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In UnitOfWork.php line 2718:
!!                                                                                 
!!    Warning: "continue" targeting switch is equivalent to "break". Did you mean  
!!     to use "continue 2"?                                                        
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

**How to reproduce**  
All I did was run `composer create-project symfony/website-skeleton my-project`.

**Comment by monocrstl** [comment]
Ok. Just so you know, the app runs fine. Thanks!

**Comment by gudinoemiliano** [comment]
I'm @nicolas-grekas do you know when that version will be available?

**Comment by nicolas-grekas** [comment]
Not at all, I'm not involved into doctrine much, you should ask there.
