### ISSUE TITLE
Messenger - support for JMS serializer

### ISSUE THREAD

**Issue by r3m4k3** [symfony/symfony#28756]
Hi there!

I use a new component messenger but unfortunately, I got still more and more errors about serialization. Symfony serializer has problems with array collections, interfaces and even nested objects.
In my whole project, I use JMS serializer and there are no problems, for this, I need to use Symfony serializer.
How can I fix this or maybe set as a default serializer JMS in messenger component, is it possible?

I'm struggling with normalization, de- and serialization for almost 2 days, IMO Symfony serializer is one of the weakest components, it's almost unusable when sb got used to JMS and its convenience.

**Comment by dunglas** [comment]
>Symfony serializer has problems with array collections

https://symfony.com/doc/current/components/serializer.html#handling-arrays

> interfaces

https://symfony.com/doc/current/components/serializer.html#serializing-interfaces-and-abstract-classes

> even nested objects

https://symfony.com/doc/current/components/serializer.html#recursive-denormalization-and-type-safety

Be sure to use the `symfony/serializer-pack` to get all required dependencies, and to enable the PropertyInfo component (until a new release containing #28735 is tagged).

**Comment by jewome62** [comment]
If you want use another serializer, you can implement [this interface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/Serialization/SerializerInterface.php) with JMSSerializer if you want ?

**Comment by sroze** [comment]
As @jewome62 mentioned, you can already do it by implementing [this interface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/Serialization/SerializerInterface.php) and set the `framework.messenger.serializer` configuration.

**Comment by sroze** [comment]
I'd recommend using Symfony Serializer though :)

**Comment by webdevilopers** [comment]
@jewome62 You can also use this adapter by @kunicmarco20 :
https://github.com/kunicmarko20/jms-messenger-adapter

**Comment by webdevilopers** [comment]
> I'd recommend using Symfony Serializer though :)

I would love to use it. Unfortunately it requires your serialized class to have a getter prefixes with "get" or public properties. Our DTOs have only private properties and getters never have the "get" prefix. :/

**Comment by spolischook** [comment]
Unfortunately it requires your serialized class to have a getter prefixes with "get" or public properties.

I have fixed this by configuration using `native_php_serializer`:
```yaml
 framework:
     messenger:
         serializer:
-            default_serializer: messenger.transport.symfony_serializer
+            default_serializer: messenger.transport.native_php_serializer
```

**Comment by webdevilopers** [comment]
That's great new @spolischook , thank you.

I will test the serializer in our next project and give you feedback.
