### ISSUE TITLE
By default symfony responds with HTTP 404

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#28761]
**Symfony version(s) affected**: 4.1.6

**Description**  
By default symfony responds with **404 not found** header on base template

**How to reproduce**  
composer create-project symfony/website-skeleton www

![404_default](https://user-images.githubusercontent.com/125879/46597709-2ad33980-cad9-11e8-8036-e90b9d120987.png)

**Possible Solution**  
Add a **DefaultController** ( like in previous versions )

**Comment by fabpot** [comment]
Which is correct as there is no default controller for the `/` resource by default.

**Comment by cybernet** [comment]
seems logic ...
