### ISSUE TITLE
The yml format is not supported by the YamlEncoder

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#28768]
**Symfony version(s) affected**: 4.1.6

**Description**  

The `YamlEncoder` currently support only the `yaml` format:

https://github.com/symfony/symfony/blob/cbe289517470eeea27162fd2d523eb29c95f775f/src/Symfony/Component/Serializer/Encoder/YamlEncoder.php#L25

AFAIK, the `.yml` file format is also accepted for Yaml format. IMO, it should be added to the support of this encoder.

**Comment by Soullivaneuh** [comment]
Possible workaround with service decoration:

```php
namespace App\Serializer\Encoder;

use Symfony\Component\Serializer\Encoder\DecoderInterface;
use Symfony\Component\Serializer\Encoder\EncoderInterface;

/**
 * @see https://github.com/symfony/symfony/issues/28768
 */
final class YamlEncoder implements EncoderInterface, DecoderInterface
{
    private const FORMAT = 'yml';

    /**
     * @var \Symfony\Component\Serializer\Encoder\YamlEncoder
     */
    private $encoder;

    public function __construct(\Symfony\Component\Serializer\Encoder\YamlEncoder $encoder)
    {
        $this->encoder = $encoder;
    }

    /**
     * {@inheritdoc}
     */
    public function encode($data, $format, array $context = array())
    {
        return $this->encoder->encode($data, $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsEncoding($format)
    {
        return $this->encoder->supportsEncoding($format) || self::FORMAT === $format;
    }

    /**
     * {@inheritdoc}
     */
    public function decode($data, $format, array $context = array())
    {
        return $this->encoder->decode($data, $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDecoding($format)
    {
        return $this->encoder->supportsDecoding($format) || self::FORMAT === $format;
    }
}
```

```yaml
services:
    App\Serializer\Encoder\YamlEncoder:
        decorates: serializer.encoder.yaml
```

**Comment by javiereguiluz** [comment]
This looks too restrictive to me too. I think we should support `.yml` too. Thanks!

**Comment by dunglas** [comment]
AFAIK, the `yml` **extension** [is discouraged](http://yaml.org/faq.html) but can be used. But I'm not aware of the `yml` string used as format name.

**Comment by Soullivaneuh** [comment]
> But I'm not aware of the yml string used as format name.

This is not the direct issue, but API system like FOSRest will use it. If you call `domain.com/api/user.yml`, `yml` will be send as format.

Am I wrong?

**Comment by dunglas** [comment]
API Platform does it too. But in this case, it's better to add an adapter in FOSRest/API Platform to pass `yaml` as format to the Serializer if the extension `yml` is passed. WDYT?

**Comment by nicolas-grekas** [comment]
Yml is so common and non-ambiguous that I'd be fine supporting it out of the box personally.
