### ISSUE TITLE
Throw exceptions instead of false for core functions

### ISSUE THREAD

**Issue by Mondane** [symfony/symfony#28765]
**Description**  
Throw exceptions instead of false for core functions by using https://github.com/thecodingmachine/safe . This would be a welcome addition to symfony as it will help developers not forget the false handling.

**Comment by jakzal** [comment]
I'm afraid it's out of Symfony's scope. Nothing stops you from including this library in your own projects though.

**Comment by fabpot** [comment]
Closing as explained by @jakzal
