### ISSUE TITLE
Symfony Notice: Array to string conversion with the popup an error occurred while loading the web debug toolbar (500: Internal Server Error)

### ISSUE THREAD

**Issue by disha2018** [symfony/symfony#28782]
I am new at Symfony and trying to upgrade application from 2.3 to 2.8 and eventually to 4. I am facing the problem to track the error "Notice: Array to string conversion" and the popup with message an error occurred while loading the web debug toolbar (500: Internal Server Error)" is also showing with no trace for Notice. Please help [https://i.stack.imgur.com/zXo9R.jpg](url)

**Comment by ismail1432** [comment]
Hi @disha2018 The url is wrong

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by disha2018** [comment]
> Hi @disha2018 The url is wrong

Hi, please try https://cdn1.imggmi.com/uploads/2018/10/9/6f1df0aee57c1abf709da31ee89ece6c-full.jpg
