### ISSUE TITLE
router not found

### ISSUE THREAD

**Issue by josephzhao** [symfony/symfony#28781]
**Symfony version(s) affected**: x.y.z

    "symfony/framework-bundle": "^4.1",
"sensio/framework-extra-bundle": "^5.2",

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**  

     /**
     * display about page
     *
     * @Route("/vtile/{name}/{zoom}/{x}/{y}",  name="mvt_vtile", options={"expose"=true})
     */

    public function vtile($name, $zoom, $x, $y) {
        
        var_dump($name);
        var_dump($zoom);
        var_dump($x);
        var_dump($y);
        
      
    }

http://localhost:8040/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940

is ok.

http://localhost:8040/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb

The requested resource /vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb was not found on this server.

/**
     * display about page
     *
     * @Route("/vtile/{name}/{zoom}/{x}/{y}.{format}",  name="mvt_vtile", options={"expose"=true})
     */

    public function vtile($name, $zoom, $x, $y,$format) {
        
        var_dump($name);
        var_dump($zoom);
        var_dump($x);
        var_dump($y);

    }

http://localhost:8040/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb

The requested resource /vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb was not found on this server.

http://localhost:8040/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940

No route found for "GET /vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940"

the old version 3.28

http://localhost:8040/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb

is ok.

my debug router info

"/opt/local/bin/php72" "/NetBeansProjects/COBAS_react/bin/console" "--ansi" "debug:router"
 ------------------------------------------ ---------- -------- ------ ---------------------------------------- 
  Name                                       Method     Scheme   Host   Path                                    
 ------------------------------------------ ---------- -------- ------ ---------------------------------------- 
  api_data_post                              ANY        ANY      ANY    /api/data/post                          
  api_data_get                               ANY        ANY      ANY    /api/data/get                           
  default_sidebar_items                      ANY        ANY      ANY    /sidebar_items                          
  default_mainmenu_items                     ANY        ANY      ANY    /mainmenu_items                         
  default_stations                           ANY        ANY      ANY    /stations                               
  default_layerlist                          ANY        ANY      ANY    /layerlist                              
  default_update_layer_feature_type          ANY        ANY      ANY    /update_layer_feature_type              
  default_layersld                           ANY        ANY      ANY    /layersld/:id                           
  default_layerdata                          ANY        ANY      ANY    /layerdata/{id}                         
  default_mvtlayer                           ANY        ANY      ANY    /mvtlayer/{id}/{zoom}                   
  mvt_vtiles                                 ANY        ANY      ANY    /vtiles/{name}/{zoom}/{x}/{y}.{format}  
  layer_savesequence                         POST       ANY      ANY    /savesequence                           
  layer_savelayersld                         POST       ANY      ANY    /savelayersld                           
  mapping_osm_legend                         ANY        ANY      ANY    /mapping/osm_legend                     
  security_login                             POST       ANY      ANY    /users/authenticate                     
  security_register                          POST       ANY      ANY    /users/register                         
  security_users                             ANY        ANY      ANY    /users                                  
  security_logout                            ANY        ANY      ANY    /logout                                 
  spatialdata_upload                         ANY        ANY      ANY    /spatialdata/upload                     
  default_research_content                   ANY        ANY      ANY    /research/{id}                          
  default_station_content                    ANY        ANY      ANY    /station/{id}                           
  overblog_graphiql_endpoint                 ANY        ANY      ANY    /graphiql                               
  overblog_graphiql_endpoint_multiple        ANY        ANY      ANY    /graphiql/{schemaName}                  
  _twig_error_test                           ANY        ANY      ANY    /_error/{code}.{_format}                
  _wdt                                       ANY        ANY      ANY    /_wdt/{token}                           
  _profiler_home                             ANY        ANY      ANY    /_profiler/                             
  _profiler_search                           ANY        ANY      ANY    /_profiler/search                       
  _profiler_search_bar                       ANY        ANY      ANY    /_profiler/search_bar                   
  _profiler_phpinfo                          ANY        ANY      ANY    /_profiler/phpinfo                      
  _profiler_search_results                   ANY        ANY      ANY    /_profiler/{token}/search/results       
  _profiler_open_file                        ANY        ANY      ANY    /_profiler/open                         
  _profiler                                  ANY        ANY      ANY    /_profiler/{token}                      
  _profiler_router                           ANY        ANY      ANY    /_profiler/{token}/router               
  _profiler_exception                        ANY        ANY      ANY    /_profiler/{token}/exception            
  _profiler_exception_css                    ANY        ANY      ANY    /_profiler/{token}/exception.css        
  homepage                                   ANY        ANY      ANY    /{_locale}                              
  easyadmin                                  ANY        ANY      ANY    /admin/                                 
  admin                                      ANY        ANY      ANY    /admin/                                 
  fos_user_security_login                    GET|POST   ANY      ANY    /login                                  
  fos_user_security_check                    POST       ANY      ANY    /login_check                            
  fos_user_security_logout                   GET|POST   ANY      ANY    /logout                                 
  fos_user_profile_show                      GET        ANY      ANY    /profile/                               
  fos_user_profile_edit                      GET|POST   ANY      ANY    /profile/edit                           
  fos_user_registration_register             GET|POST   ANY      ANY    /register/                              
  fos_user_registration_check_email          GET        ANY      ANY    /register/check-email                   
  fos_user_registration_confirm              GET        ANY      ANY    /register/confirm/{token}               
  fos_user_registration_confirmed            GET        ANY      ANY    /register/confirmed                     
  fos_user_resetting_request                 GET        ANY      ANY    /resetting/request                      
  fos_user_resetting_send_email              POST       ANY      ANY    /resetting/send-email                   
  fos_user_resetting_check_email             GET        ANY      ANY    /resetting/check-email                  
  fos_user_resetting_reset                   GET|POST   ANY      ANY    /resetting/reset/{token}                
  fos_user_change_password                   GET|POST   ANY      ANY    /profile/change-password                
  api_login_check                            ANY        ANY      ANY    /api/login_check                        
  overblog_graphql_endpoint                  ANY        ANY      ANY    /graphql/                               
  overblog_graphql_batch_endpoint            ANY        ANY      ANY    /graphql/batch                          
  overblog_graphql_multiple_endpoint         ANY        ANY      ANY    /graphql/graphql/{schemaName}           
  overblog_graphql_batch_multiple_endpoint   ANY        ANY      ANY    /graphql/graphql/{schemaName}/batch     
 ------------------------------------------ ---------- -------- ------ ---------------------------------------- 

Done.

Thanks

Joseph

**Comment by xabbuh** [comment]
Do you use PHP's built-in web server? And if so, do you start it yourself or are you using the `server:*` commands provided by the WebServerBundle?

**Comment by josephzhao** [comment]
I am using PHP's built-in web server and apache2 , same result

**Comment by xabbuh** [comment]
Can you show the configuration that you used for Apache? Can you also give the WebServerBundle a try?

**Comment by josephzhao** [comment]
i have installed "symfony/web-server-bundle": "^4.1" and run php bin/console server:start

get  

[OK] Server listening on http://127.0.0.1:8000    

i input in browser:

http://localhost:8040/vtiles/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1097/1941.pdb

get 

Failed to load resource: the server responded with a status of 404 (Not Found)

and Resource interpreted as Document but transferred with MIME type application/x-protobuf: "http://127.0.0.1:8000/vtiles/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1097/1941.pdb".


apache2 seetings

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName newcobas.juturna.ca
        DocumentRoot /opt/cobas.juturna.ca/cobas_react/current/public
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory /opt/cobas.juturna.ca/cobas_react/current/public>
                DirectoryIndex index.php
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/newcobas_production_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/newcobas_production_access.log combined

    Alias /doc/ "/usr/share/doc/"
    <Directory "/usr/share/doc/">
        Options Indexes MultiViews FollowSymLinks
        AllowOverride None
        Order deny,allow
        Deny from all
        Allow from 127.0.0.0/255.0.0.0 ::1/128
    </Directory>
</VirtualHost>

**Comment by josephzhao** [comment]
can i use router like this:

   
    /**
     * display about page
     *
     * @Route("/vtiles/{name}/{zoom}/{x}/{y}.{format}",  name="mvt_vtiles", options={"expose"=true})
     */
    public function vtiles($name, $zoom, $x, $y, $format) {
}

thanks

Joseph

**Comment by josephzhao** [comment]
> Can you show the configuration that you used for Apache? Can you also give the WebServerBundle a try?

Can I use router like this:

   
    /**
     * display about page
     *
     * @Route("/vtiles/{name}/{zoom}/{x}/{y}.{format}",  name="mvt_vtiles", options={"expose"=true})
     */
    public function vtiles($name, $zoom, $x, $y, $format) {
    }

**Comment by soufianZantar** [comment]
The problem when you add . to URL (in any parametres ) the server not redirect the request to front controller index.php, but i don't know why !!!.

For me it work when i add index.php to url like:

http://localhost:8040/index.php/vtile/d9c8f970-8468-4b91-bded-271f1157d7e1/12/1096/1940.pdb

**Comment by josephzhao** [comment]
if i add index.php, it works too, why before with old version of symfony, it works without index.php

**Comment by soufianZantar** [comment]
@josephzhao to fix your problem you must point on index.php for the **built-in web server** pass index.php as 2 args like : 
`$ php -S 127.0.0.1:8000 -t public public/index.php`
For apache you must change your config to point on index.php.

Old version of symfony use app.php or app_dev.php not index.php

I will update **What's next?** in creating new project this weekdend to replace : 

>  Execute the php -S 127.0.0.1:8000 -t public command

by 

>  Execute the php -S 127.0.0.1:8000 -t public public/index.php command

**Comment by xabbuh** [comment]
So this also happens when using the WebServerBundle? If so, can you please create a small example application that allows to reproduce?
