### ISSUE TITLE
[PhpunitBridge] installs non-stable releases from phpunit repo

### ISSUE THREAD

**Issue by pscheit** [symfony/symfony#28791]
**Symfony version(s) affected**: all

**Description**  
The phpunit bridge sets the COMPOSER_ROOT_VERSION to 6.5.99 (.e.g) and will then install dev versions as well - and not stable versions.

**How to reproduce**  
delete vendor/bin/.phpunit and use simple-phpunit again. It will install the latest commit in phpunit repo (e.g. branch 6.5)

**Possible Solution**  
I'm not 100% sure: use prefer-stable: true and minimium-compability: stable in the composer.json from phpunit?

Thank you

Best regards
Philipp

**Comment by greg0ire** [comment]
I cannot reproduce, do you maybe have a global composer.json specifying a high minimum-compat?

**Comment by xabbuh** [comment]
Closing here for now. We can reopen once we are able to reproduce.

**Comment by stof** [comment]
This was solved when changing the way to install PHPUnit in the bridge in https://github.com/symfony/symfony/pull/29265 (in November 2018). Before that PR, we were indeed always using the dev version, as we were getting the github branch.
