### ISSUE TITLE
make:entity for custom directory

### ISSUE THREAD

**Issue by pierrevensy** [symfony/symfony#28790]
**Description**  
Hi! I congratulate you for your framework, it's a big work and a powerful framework, i really like and i am a fan of Symfony. I used bundle for my business model in Symfony 3, but in 4 the best practice advises us not to use bundle for our business model. So i want to organize my directories this way: 

**Example**  
App/
....User/
........Entity/
........Controller/
        ...
    Blog/
........Entity/
........Controller/
        ...

When i organize my codes like that, i can't create entities in custom folder with make:entity

I searched the entire web for a solution but nothing...

So! my request is, please adds a bundle substitute that will allow us to organize our codes well.
Thank you!

**Comment by xabbuh** [comment]
The `make:*` commands are part of the MakerBundle which has [its own repository](https://github.com/symfony/maker-bundle). I think symfony/maker-bundle#247 and symfony/maker-bundle#51 basically cover the same idea. So I am going to close here.
