### ISSUE TITLE
Symfony 3.4 Collection Type 

### ISSUE THREAD

**Issue by hugoalexmartins** [symfony/symfony#28799]
Hey guys,

I'm having a lot of trouble putting CollectionType and embedded forms in working correctly.

First of all, I have 3 entities that relate to each other, 1: M
Entities are: Wizard, WizardQuestion, WizardQuestionAnswer.

I have the form type Wizard, which I want to adhere to the CollectionType WizardQuestion, here begins my first problem. I need to filter WizardQuestions by a criteria, after that, which I'm already doing, I need the CollectionType to use the date I've filtered.
To add just the filtered choices I use this:

```
$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options) {
      $wizard = $event->getData();
      $form = $event->getForm();

      // lets get Root ou Childs wizard questions
      if (!$options['parent_question_id']) {
        $choices = $this->wizard->getQuestions($wizard);
      } else {
        $choices = $this->wizard->getQuestions($wizard, $options['parent_question_id']);
      }


      $form
              ->add('wizard_questions',
                      CollectionType::class,
                      [
                          'entry_type' => WizardQuestionType::class,
                          'data' => $choices,
                          'label' => false
                      ]
              )
      ;
    });

```

However, when I want to manipulate WizardQuestions from the WizardQuestionsType form, here I do not access any previously added objects.

What am I doing wrong?

Thank you for your help

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by hugoalexmartins** [comment]
Hey, 

After a couple of hours debug, I just realize thats this maybe comes from a Bug, with symfony.
This strange behavior happens when use the collection type in env PROD not in DEV.

Any way you can help me ?

**Comment by xabbuh** [comment]
If you think you discovered a bug, please create a small example application that allows to reproduce your issue.
