### ISSUE TITLE
[HttpFoundation] Request: create from string

### ISSUE THREAD

**Issue by fieg** [symfony/symfony#28792]
**Description**  
It's possible to serialize a request with the `__toString` method. It would be very convenient when there would be a `createFromString` method that accepts the output of `__toString` to restore the request object.

**Example**  
```php
class MyController extends Controller 
{
  public function indexAction(Request $request)
  {
    $previousRequest = Request::createFromString(file_get_contents('last_request.txt'));

    // do business logic with $previousRequest

    file_put_contents('last_request.txt', (string) $request);
  }
}
```

**Comment by enrico69** [comment]
I am looking at this interesting feature.
I think we could add a method:
`public static function createFromString(string) : self`

This method would in fact call the existing method:
`public static function create`

I am testing it currently.

**Comment by fabpot** [comment]
Closing for the reasons explained by @enrico69
