### ISSUE TITLE
Confusion with cache warm-ups in production mode

### ISSUE THREAD

**Issue by eschultz-magix** [symfony/symfony#28800]
Hi,

I'm a bit confused regarding the issue #23571 where APCu is suggested to be used as adapter for the ```cache.system``` key. I am facing around with the same issue ("Cache warmup doesn't warm Symfony\Component\Form\Util\OrderedHashMap") in the ```prod``` environment.

This confuses me:

https://github.com/symfony/symfony/issues/23571#issuecomment-316085011
> Your issue [...] is related to the ```cache.system``` cache pool that is used at runtime

https://symfony.com/doc/current/setup/file_permissions.html
> In the ```prod``` environment [...], as long as you run ```php bin/console cache:warmup```, no cache files will need to be written to disk at runtime.

APCu and APC are not available, but OPCache is enabled, so the optimized ```PhpFilesAdapter``` is used for the ```cache.system``` pool which seems okay to me in production.

I also don't understand the problem. All registered services using the ```cache.system``` service have its own ```CacheWarmer``` implementation, so ```php bin/console cache:warmup``` should also warmup the ```cache.system``` pool, so no cache files should be written at runtime, or am I wrong?

Thanks in advance for any clarification,
Enrico

**Comment by nicolas-grekas** [comment]
Does enabling the apcu extension fix the issue?
If not then #28805 will fix it on next version 4.2

**Comment by eschultz-magix** [comment]
Thanks for the fast reply. Enabling APCu would fix it, of course, but I don't think it would resolve the issue, even after looking at the changes in the commit.

If APCu is the **only** way to use the system cache on read-only file systems, then it should be mentioned in the documentation. Also "no cache files will need to be written to disk at runtime" should not be stated inside the documentation.

I would like to know whether the system cache is built with the ```cache:warmup``` command, because all services using the ```cache.system``` service have its own ```CacheWarmerInterface``` implementation, but the cache seems not to get filled.

In our setup, the cache directory has write access for the command line user, so we can use ```cache:warmup``` to fill the cache after a successful deployment, but the webserver user can only read the files and directories.
