### ISSUE TITLE
The service "web_profiler.controller.profiler" has a dependency on a non-existent service "twig".

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#28803]
**Symfony version(s) affected**: 4.1.6

**Description**  
After installing symfony/web-profiler-bundle, i have this error:
`The service "web_profiler.controller.profiler" has a dependency on a non-existent service "twig".`
I need to manually require `symfony/twig-bundle` to fix it.

**How to reproduce**  
```bash
composer create-project symfony/skeleton test
cd test
composer require --dev symfony/web-profiler-bundle
```

Error:
```bash
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
!!                                                                                 
!!    The service "web_profiler.controller.profiler" has a dependency on a non-ex  
!!    istent service "twig".                                                       
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Possible Solution**  
Add `symfony/twig-bundle` as dependency into `symfony/web-profiler-bundle`.

When i do it manually, problem is solved:
```bash
$ composer require symfony/twig-bundle
Restricting packages listed in "symfony/symfony" to "4.1.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.1.*"
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/twig-bundle (v4.1.6): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 1 recipe (ae6caea8b9fd2e186eea969d92f4bfde)
  - Configuring symfony/twig-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.
```

**Comment by stof** [comment]
> Add `symfony/twig-bundle` as dependency into `symfony/web-profiler-bundle`

this has already been done in master, but it is indeed not done in 4.1.

@symfony/deciders should we backport that change ?

**Comment by fabpot** [comment]
I don't think we need to backport that in 4.1. The error message is quite explicit.

**Comment by lyrixx** [comment]
Maybe we can add a more explicit exception like we do in other part of the framework:

> You must install twig to use the profiler bundle

**Comment by javiereguiluz** [comment]
Sadly this stalled and now it's too late to make this change in 4.1. But I agree with Fabien that the error message should be clear enough. Thanks.
