### ISSUE TITLE
Config dump reference for sub keys

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#28819]
**Description**  

Some of the bundle configurations might be very heavy and harder to read with the `config:dump-reference` command.

It would be great 

**Example**  

```bash
# Will output the orm section of doctrine configuration
./bin/console config:dump-reference doctrine.orm
```

**Comment by chalasr** [comment]
Isn't the [`path` argument](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ConfigDumpReferenceCommand.php) what you are looking for?

**Comment by xabbuh** [comment]
closing here as @chalasr's answer seems to be the solution
