### ISSUE TITLE
Translation commands should not talk about the old "app/" directory since 3.4

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#28816]
**Symfony version(s) affected**: 3.4

**Description**  
`TranslationUpdateCommand` and `TranslationDebugCommand` mentions "the app/ folder" at several places (e.g. [here](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php#L83)) while the `translator.default_path` exists and defaults to `translations/` since 3.4.

**How to reproduce**  
Not really a bug, just a misleading/wrong mention.

**Possible Solution**  
Maybe talk about the configured `translator.default_path` and `twig.default_path` instead of `app/` (which implicitly means kernel.root_dir).

**Comment by chalasr** [comment]
\cc @yceruto

**Comment by yceruto** [comment]
Sure, we can use `$this->defaultTransPath` to build the right description into `configure()` method.
