### ISSUE TITLE
Improve the deprecation logs in the profiler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#28818]
**Symfony version(s) affected**: all

**Description**  
We're updating Symfony Demo to 4.2.x-dev to find deprecations and bugs. Sadly, lots of deprecation logs show information that is not useful.

For example in this one, the error message is very clear ... but I want to see more context info, such as the file where this happens, ideally the line too, etc.

![deprecation-1](https://user-images.githubusercontent.com/73419/46807765-0ee6c680-cd6b-11e8-98de-6d4972fb8072.png)

However, if I click on "Show trace", the info is not useful:

![deprecation-2](https://user-images.githubusercontent.com/73419/46807824-2b82fe80-cd6b-11e8-9db4-7bfa80f00b6c.png)

If I click on "Show context", I get the same "not useful" info:

![deprecation-3](https://user-images.githubusercontent.com/73419/46807855-3e95ce80-cd6b-11e8-8bc1-cb808ffd30f4.png)

-----

Am I doing something wrong ... or should we improve this? Thanks!

**Comment by nicolas-grekas** [comment]
Isn't the message enough?

**Comment by javiereguiluz** [comment]
In this case, probably. But let me show you another deprecation message from the same app:

![deprecation-4](https://user-images.githubusercontent.com/73419/46809388-a39ef380-cd6e-11e8-99ee-7b81edead3bb.png)

Who is the culprit? Who calls/uses the deprecated code? I'd need a file name or class name or class+method ... and ideally the line too.

**Comment by Saphyel** [comment]
I usually log them with monolog... but in profiler looks very unclear :/

example on the logs:
```
[2018-06-11 15:49:09] php.DEBUG: Warning: posix_isatty(): could not use stream of type 'Output' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/vendor/symfony/var-dumper/Dumper/CliDumper.php\",\"line\":470,\"trace\":[{\"file\":\"/var/www/vendor/symfony/var-dumper/Dumper/CliDumper.php\",\"line\":415,\"function\":\"supportsColors\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Dumper\\\\CliDumper\",\"type\":\"->\"}],\"count\":1})"} []
```

**Comment by alterphp** [comment]
IMHO, stack trace can be omitted in the case of deprecations (E_USER_DEPRECATED). As context can not be filled from trigger_error method, it can be omitted too.

**Comment by chalasr** [comment]
I agree that being able to know which file causes the deprecation notice would be useful in some cases.
