### ISSUE TITLE
[Templating] Rendering the same (base) template twice does not reset slots (blocks)

### ISSUE THREAD

**Issue by King2500** [symfony/symfony#28821]
**Symfony version(s) affected**: 3.3.9

**Question**  
Is it intended, that when rendering the same (sub-)template (or other sub-template with the same base template), the blocks are not reset?

**How to reproduce**  
(simplified HTML)
We have this `base.html.php`:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>test</title>
    </head>
    <body>
        <? $view['slots']->output('body', 'Default'); ?>

    </body>
</html>
```
And this sub template `bla.html.php`:
```php
$view->extend('base.html.php');

if (isset($show_bla) && $show_bla) {
	$view['slots']->start('body');
	?> bla <?php

	$view['slots']->stop('body');
}
```
In controller, the template is rendered multiple times (may also be another template "inheriting" the same base):
```php
	public function dummy()
	{

		$html1 = $this->render('bla.html.php', ['show_bla' => '1'])->getContent();
		$html2 = $this->render('bla.html.php')->getContent();

		$output = 'Output 1: <pre>' . htmlspecialchars($html1). '</pre><br><br>';
		$output .= 'Output 2: <pre>' . htmlspecialchars($html2). '</pre><br><br>';

		return new Response($output);
	}
```

The output looks like this:
![image](https://user-images.githubusercontent.com/4896363/46811982-178fca80-cd74-11e8-9db0-4a5ed001852e.png)

As you can see, the second `render` call still has the same "bla" output in the `body` slot. (marked yellow)

Obviously the same slots are stored in `SlotsHelper` until they get further overwritten in subsequent render calls. (Like a "global" variable)

**Possible Solution?**  
Does it make more sense / is less confusing, if slots get reset after each render call...?

**Additional note**  
Maybe this also applies to Twig's block behavior? At least it should be consistent between the two engines.

**Comment by fabpot** [comment]
Changing the behavior would be a BC break. As we are now recommending Twig, I don't think we will change the current behavior.
