### ISSUE TITLE
cannotBeEmpty  in configuration not working as expected

### ISSUE THREAD

**Issue by videni** [symfony/symfony#28827]
I explicitly  set `redirect_host` can 
NOT be empty, but when I try to validate this value , the $host variable with null value is passed. 
```
 $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('app_url_shortener');

$rootNode
            ->children()
                ->scalarNode('redirect_host')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->validate()
                        ->ifTrue(function ($host) {
                            return preg_match('/https?/', $host);  //$host is null even the value is set
                        })
                        ->thenInvalid("You shouldn't specify protocol for 'redirect_host'")
                    ->end()
                ->end()
                ->scalarNode('provider')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->defaultValue('custom')
                    ->validate()
                        ->ifNotInArray(['custom', 'baidu'])
                        ->thenInvalid('The link provider %s is not supported')
                    ->end()
                ->end()
            ->end()
```

```
app_url_shortener:
    redirect_host: '%env(SHORT_LINK_REDIRECT_HOST)%'
    provider: 'baidu'

```

.env
```
SHORT_LINK_REDIRECT_HOST=example.com

```

> ypeError: preg_match() expects parameter 2 to be string, null given in /Users/app/www/app/src/Bundle/UrlShortenerBundle/DependencyInjection/Configuration.php:30
Stack trace:
#0 /Users/app/www/app/src/Bundle/UrlShortenerBundle/DependencyInjection/Configuration.php(30): preg_match('/^https?/', NULL)
#1 /Users/app/www/app/vendor/symfony/config/Definition/Builder/ExprBuilder.php(242): App\Bundle\UrlShortenerBundle\DependencyInjection\Configuration->App\Bundle\UrlShortenerBundle\DependencyInjection\{closure}(NULL)
#2 /Users/app/www/app/vendor/symfony/config/Definition/BaseNode.php(414): Symfony\Component\Config\Definition\Builder\ExprBuilder::Symfony\Component\Config\Definition\Builder\{closure}(NULL)
#3 /Users/app/www/app/vendor/symfony/config/Definition/BaseNode.php(397): Symfony\Component\Config\Definition\BaseNode->finalize(NULL)
#4 /Users/app/www/app/vendor/symfony/config/Definition/ArrayNode.php(246): Symfony\Component\Config\Definition\BaseNode->finalize('env_43b19c36cb4...')
#5 /Users/app/www/app/vendor/symfony/config/Definition/BaseNode.php(408): Symfony\Component\Config\Definition\ArrayNode->finalizeValue(Array)
#6 /Users/app/www/app/vendor/symfony/config/Definition/Processor.php(39): Symfony\Component\Config\Definition\BaseNode->finalize(Array)
#7 /Users/app/www/app/vendor/symfony/config/Definition/Processor.php(52): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array)
#8 /Users/app/www/app/vendor/symfony/dependency-injection/Compiler/ValidateEnvPlaceholdersPass.php(80): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(App\Bundle\UrlShortenerBundle\DependencyInjection\Configuration), Array)
#9 /Users/app/www/app/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\DependencyInjection\Compiler\ValidateEnvPlaceholdersPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#10 /Users/app/www/app/vendor/symfony/dependency-injection/ContainerBuilder.php(746): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#11 /Users/app/www/app/vendor/symfony/http-kernel/Kernel.php(515): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#12 /Users/app/www/app/vendor/symfony/http-kernel/Kernel.php(123): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#13 /Users/app/www/app/vendor/lakion/api-test-case/src/ApiTestCase.php(74): Symfony\Component\HttpKernel\Kernel->boot()
#14 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/Framework/TestSuite.php(703): Lakion\ApiTestCase\ApiTestCase::createSharedKernel()
#15 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/Framework/TestSuite.php(750): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/TestRunner.php(587): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/Command.php(203): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#18 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/Command.php(159): PHPUnit\TextUI\Command->run(Array, true)
#19 /usr/local/Cellar/phpunit/7.3.1/bin/phpunit(595): PHPUnit\TextUI\Command::main()
#20 {main}

**Comment by ro0NL** [comment]
we assume `null` here https://github.com/symfony/symfony/blob/b399527ba1c5c20f8b0f4db2b6563304c31c38ac/src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php#L51

the env does not exists (no lookup happens using e.g. `getenv()` at this point)

since you didn't declare a default, e.g.

```yaml
paramaters:
   env(SHORT_LINK_REDIRECT_HOST): "default"
```

there's no value to value in config, thus `null`. During run-time this would throw (env not found) so perhaps we should do something here :thinking: 

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
The code is expression two conflicting expectations: be validated at compile time + be defined at runtime. Maybe we can improve the error message, but fundamentally the code is "logically broken".
Any proposals?

**Comment by ro0NL** [comment]
the error happens in user-land, so somehow we need to avoid passing `null` as value to validate. Tend to agree that means it should throw somewhere.. :)

looking at

```
https://github.com/symfony/symfony/blob/261c0dea910ade2865128ac28045e22c935111b6/src/Symfony/Component/Config/Definition/ScalarNode.php#L49-L55
```

i think for this case we should actually return true here for the placeholder, and let config do the throw. But we should differ between `null` explicitly set, and `null` currently meaning "undefined" also :thinking:

**Comment by nicolas-grekas** [comment]
Which means we should pass the value with the env placeholder to the validation callback. This would fixit here.

**Comment by ro0NL** [comment]
see #28838  but there's still a semantic issue..

`cannotBeEmpty` is fundamentally incompatible with envs, as we dont know if it's an empty value or not. Assuming false above is just as wrong as assuming true actually.

Right now we say it's not empty, but we actually use a empty placeholder value (either `null` or `""`), that's odd at least.

So additionally we might want to throw a logic for this case instead (when using `cannotBeEmpty` + env).
