### ISSUE TITLE
Modifying bootstrap 4 label for checkbox removes the actual input element

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony#28823]
**Symfony version(s) affected**: 4.1.4

**Description**  
If you try to override *only a label* of a checkbox, the input element disappears. 

The custom label is shown once if using ‘form_widget’ and twice if using ‘form_row’, the actual checkbox/input never appears, just the label.

**How to reproduce**  
Use in a twig view:
```
{% form_theme form _self %}

{% block _user_registration_form_termsAccepted_label %}
    <label class="form-check-label required" for="user_registration_form_termsAccepted">{{ 'label.terms_accepted'|trans({ '%terms_and_conditions_link%': path('terms') })|raw }}</label>
{% endblock %}
```
Render via `{{ form_widget(form.termsAccepted) }}` - shows the label once, with an indent (`form-check` div wrap)
Render via `{{ form_row(form.termsAccepted) }}` - shows the label twice, one without an indent and second with an indent same as with `form_widget`

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you check if #26540 is the same?

**Comment by ptrm04** [comment]
@xabbuh nope it isn’t, what #26540 relates to appears to be an expected behaviour according to the docs, will comment there

**Comment by xabbuh** [comment]
But, the reason is the same, isn't it? I mean the fact that the label is rendered by the widget. This means your custom label won't be shown with `form_widget()` while `form_row()` displays your own label as well as the one rendered by the widget. Isn't that what's happening?

**Comment by ptrm04** [comment]
My custom label is shown with both, as described in the first post above:

“Render via {{ form_widget(form.termsAccepted) }} - shows the label once, with an indent (form-check div wrap)
Render via {{ form_row(form.termsAccepted) }} - shows the label twice, one without an indent and second with an indent same as with form_widget”

The issue here is the actual widget / input disappears here in both scenarios, and additionally with form_row the label is shown twice.

This and the other issue are not the same.

**Comment by ptrm04** [comment]
I’ve updated the original issue description above to hopefully make this clearer.

**Comment by xabbuh** [comment]
👍 I think I understand the issue now. I am looking into it.

**Comment by xabbuh** [comment]
I think this is the expected behaviour. In the Bootstrap 4 theme, the label is not rendered by the `form_label` block, but by calling `form_widget`. The block for the checkbox label then has a check to only be rendered once:

```twig
{% block checkbox_radio_label -%}
    {#- Do not display the label if widget is not defined in order to prevent double label rendering -#}
    {%- if widget is defined -%}
        {% set is_parent_custom = parent_label_class is defined and ('checkbox-custom' in parent_label_class or 'radio-custom' in parent_label_class) %}
        {% set is_custom = label_attr.class is defined and ('checkbox-custom' in label_attr.class or 'radio-custom' in label_attr.class) %}
        {%- if is_parent_custom or is_custom -%}
            {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' custom-control-label')|trim}) -%}
        {%- else %}
            {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' form-check-label')|trim}) -%}
        {%- endif %}
        {%- if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {%- if required -%}
            {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' required')|trim}) -%}
        {%- endif -%}
        {%- if parent_label_class is defined -%}
            {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' ' ~ parent_label_class)|replace({'checkbox-inline': '', 'radio-inline': '', 'checkbox-custom': '', 'radio-custom': ''})|trim}) -%}
        {%- endif -%}
        {%- if label is not same as(false) and label is empty -%}
            {%- if label_format is not empty -%}
                {%- set label = label_format|replace({
                    '%name%': name,
                    '%id%': id,
                }) -%}
            {%- else -%}
                {%- set label = name|humanize -%}
            {%- endif -%}
        {%- endif -%}

        {{ widget|raw }}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
            {{- label is not same as(false) ? (translation_domain is same as(false) ? label : label|trans({}, translation_domain)) -}}
            {{- form_errors(form) -}}
        </label>
    {%- endif -%}
{%- endblock checkbox_radio_label %}
```

So you basically will need to mimic this behaviour in your own label block.

**Comment by ptrm04** [comment]
Thanks @xabbuh - pulling out the snippet from bootstrap_4_layout.html.twig into the overridden label seems to do the trick with the link in the label after adding `|raw` in the label line.

Given this block renders the label as the name of the block suggests, there is a reference to `{{ widget|raw }}` - is it the responsibility of the label block to render the widget itself as well?

Also, in the `{% block checkbox_widget -%}` block https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig#L162, it'd be nice to be able to easily see what block `form_label` is going to use, Twig syntax would be much more readable.

**Comment by ptrm04** [comment]
I see, the label and widget need to live together within the form-check div, that's why they're being output via the widget call, will put together a gist on how to modify to be able to customise and output separately, especially the label.

**Comment by Isengo1989** [comment]
So the solution here is to edit the bootstrap twig file?

**Comment by ptrm04** [comment]
@Isengo1989 Nope, you override them, see this on how to do this: https://symfony.com/doc/current/form/form_themes.html
