### ISSUE TITLE
[RFC][Form] Change TimezoneType to Intl sources / translate timezone choice labels

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28836]
**Description**  
Currently the TimezoneType does not depend on symfony/intl (unlike LanguageType etc.), but uses vanilla PHP based on `\DateTimeZone::listIdentifiers()`.

There are several issues (#26851, #17628, #17636) that request to use localized zone labels.

For that i've finished #28831 to provide the actual translations, based on ICU, just like languages, etc.

However it doesnt mean we should switch from `\DateTimeZone::listIdentifiers()` to `TimezoneBundle::getZoneNames()` per se, hence the RFC.

I see several options:

1. keep using `\DateTimeZone::listIdentifiers()` and only translate using `TimezoneBundle`
1. switch to `TimezoneBundle` as a new feature (including translating)
1. add an option `intl => false` to optionally switch
1. option 3 + deprecating not setting it to true (force intl in 5.0)
1. option 2 + deprecating submitting unsupported zones (few)

Personally i'd prefer symfony/intl so there's no environment dependency, and we have better control to blacklist/mutate etc.

Related

- consider adding `input=intltimezone` to leverage `\IntlTimeZone` as underlying model
- the current `regions` option relies on `\DateTimeZone::listIdentifiers()`, so if in any scenario Intl will be used the option is incompatible, meaning we either implement a fallback or deprecate it all together (favored by  `group_by` to let the user decide in all cases)
- re-consider timezone sorting (going from -xx:00 to +xx:00 makes sense and is intuitive, given the GMT+- offset is included in the label - see e.g. https://github.com/symfony/symfony/pull/28831#issuecomment-429275779)

Thougts?

**Comment by stof** [comment]
Whatever gets decided here, backward compatibility requires that the dependency to symfony/intl stays optional (as the form type is currently usable without it).

**Comment by ro0NL** [comment]
of course :) BC guaranteed, however `symfony/intl` is already a dependency of symfony/form i just found out

https://github.com/symfony/symfony/blob/261c0dea910ade2865128ac28045e22c935111b6/src/Symfony/Component/Form/composer.json#L18-L21

i actually expected it to be a soft-dep :) meaning either we should fix that (we recently updated the types to throw if unavailable :S) or option 2 is viable :D

**Comment by stof** [comment]
hmm indeed, I confused with the validator component, where it is a soft dependency.

**Comment by ro0NL** [comment]
join the club :) i forgot to move the dep myself in #28610 

now thinking about it.. is that a BC break or would a changelog note be sufficient?

**Comment by ro0NL** [comment]
So i've compared the zones from `\DateTimeZone::listIdentifiers()` vs. the compiled list from #28831, to see what's the impact on the practical side.

To me what's important, is that all zones are compatible with `\DateTimeZone`. The ones incompatible with `\IntlTimeZone` are BC, and are very few actually (see also #22302), i'm not sure we care for now. Esp. since Symfony core doesnt use it AFAIK.

Results are pretty close, the difference mostly comes from a few different notations (`Etc/UTC` vs `UTC`) , and PHP and ICU using different form of aliases.

E.g. `America/Argentina/Buenos_Aires` vs. `America/Buenos_Aires`:
- PHP includes the first, and the latter only with `\DateTimeZone::ALL_WITH_BC`
- ICU includes the latter, and marks the first an "alias": https://github.com/unicode-org/icu/blob/e509105c9b07912562481149aaa1da23c8170548/icu4c/source/data/misc/timezoneTypes.txt#L17

AFAIK we should follow ICU here.

Zone | PHP | SF | DateTimeZone | IntlTimeZone
--- | --- | --- | --- | ---
count | 425 | 433 | | 
Africa/Asmara | ✔ | ✗ | ✔ | ✔
America/Argentina/Buenos_Aires | ✔ | ✗ | ✔ | ✔
America/Argentina/Catamarca | ✔ | ✗ | ✔ | ✔
America/Argentina/Cordoba | ✔ | ✗ | ✔ | ✔
America/Argentina/Jujuy | ✔ | ✗ | ✔ | ✔
America/Argentina/Mendoza | ✔ | ✗ | ✔ | ✔
America/Atikokan | ✔ | ✗ | ✔ | ✔
America/Indiana/Indianapolis | ✔ | ✗ | ✔ | ✔
America/Kentucky/Louisville | ✔ | ✗ | ✔ | ✔
America/Punta_Arenas | ✔ | ✔ | ✔ | ✗
Asia/Atyrau | ✔ | ✔ | ✔ | ✗
Asia/Famagusta | ✔ | ✔ | ✔ | ✗
Asia/Ho_Chi_Minh | ✔ | ✗ | ✔ | ✔
Asia/Kathmandu | ✔ | ✗ | ✔ | ✔
Asia/Kolkata | ✔ | ✗ | ✔ | ✔
Asia/Tomsk | ✔ | ✔ | ✔ | ✗
Asia/Yangon | ✔ | ✗ | ✔ | ✗
Atlantic/Faroe | ✔ | ✗ | ✔ | ✔
Europe/Kirov | ✔ | ✔ | ✔ | ✗
Europe/Saratov | ✔ | ✔ | ✔ | ✗
Pacific/Chuuk | ✔ | ✗ | ✔ | ✔
Pacific/Pohnpei | ✔ | ✗ | ✔ | ✔
UTC | ✔ | ✗ | ✔ | ✔
Africa/Asmera | ✗ | ✔ | ✔ | ✔
America/Buenos_Aires | ✗ | ✔ | ✔ | ✔
America/Catamarca | ✗ | ✔ | ✔ | ✔
America/Coral_Harbour | ✗ | ✔ | ✔ | ✔
America/Cordoba | ✗ | ✔ | ✔ | ✔
America/Indianapolis | ✗ | ✔ | ✔ | ✔
America/Jujuy | ✗ | ✔ | ✔ | ✔
America/Louisville | ✗ | ✔ | ✔ | ✔
America/Mendoza | ✗ | ✔ | ✔ | ✔
America/Montreal | ✗ | ✔ | ✔ | ✔
America/Santa_Isabel | ✗ | ✔ | ✔ | ✔
Asia/Calcutta | ✗ | ✔ | ✔ | ✔
Asia/Katmandu | ✗ | ✔ | ✔ | ✔
Asia/Rangoon | ✗ | ✔ | ✔ | ✔
Asia/Saigon | ✗ | ✔ | ✔ | ✔
Atlantic/Faeroe | ✗ | ✔ | ✔ | ✔
CST6CDT | ✗ | ✔ | ✔ | ✔
EST5EDT | ✗ | ✔ | ✔ | ✔
Etc/GMT | ✗ | ✔ | ✔ | ✔
Etc/UTC | ✗ | ✔ | ✔ | ✔
MST7MDT | ✗ | ✔ | ✔ | ✔
PST8PDT | ✗ | ✔ | ✔ | ✔
Pacific/Johnston | ✗ | ✔ | ✔ | ✔
Pacific/Ponape | ✗ | ✔ | ✔ | ✔
Pacific/Truk | ✗ | ✔ | ✔ | ✔

Snippet used: https://gist.github.com/ro0NL/fd815d6242ff8ee8116ee1acfb6db9a7

**Comment by ro0NL** [comment]
I've added option 5 in the issue, describing the ideal scenario: switch to Intl, while keep supporting any submitted value from the old PHP list. At this point i'd like to trigger a deprecation, but it might be a bit complex... not sure yet.

More pragmatically would be to just make the switch as a new feature (option 2). Technically we did the same-ish in #28833  :sweat_smile: 

If we accept the feature (one way or another), i can have a look after #28831 / #28846

**Comment by stof** [comment]
I think the important thing for BC is that `new DateTimeZone($zone)` works, more than having it included in `\DateTimeZone::listIdentifiers()` (assuming the validator is not based on `\DateTimeZone::listIdentifiers()` only of course). And according to your analysis, `new DateTimeZone($zone)` seems to support them all.
Compatibility with `new \IntlTimeZone($zone)` was already not guaranteed at 100%, due to some unsupported ones (see `Asia/Tomsk` in your list for instance)

**Comment by ro0NL** [comment]
@stof we still need to make sure `new DateTimeZone($zone)` happens based on the submitted value, removing zones from the choice list might give us null

However, thinking about #23679, we could get away for free. I haven't really figured out what's casuing it, but it seems as soon as the list is based on a default Intl `choice_list`, the submitted value remains.

I need to check that after #28831

**Comment by ro0NL** [comment]
I tend to believe we should remain practical, and support both PHP or Intl timezones. That's an extra cost though, but saves us the deprecation hassle or being opinionated for that matter :grin: 

Also, m really unsure how common (or uncommon) the Intl timezone IDs in the community really are. For languages, currencies, etc. this was more obvious.

It's also harder to translate the PHP timezones, as we have to map them to Intl first. So adding `intl => true` as an option (default false) seems the most simple/explicit to me, and ignore translating if disabled :man_shrugging: (it's more an Intl semantic anyway).

If `intl=true` we render somewhat as described in https://github.com/symfony/symfony/pull/28831#issuecomment-429275779, otherwise the current rendering is preserved. Perhaps compile the offset metadata per timezone.

The next step would supporting `input => 'intltimezone'` (vs. `datetimezone` for PHP), i.e. https://www.php.net/intltimezone vs https://www.php.net/datetimezone

Here the hard part is to exclude BC timezones (those incompatible with `\IntlTimeZone`) as we cannot provide the model instance in that case. Perhaps compile this info per timezone.

At this point we solved #22302 i believe :)

Then; https://symfony.com/blog/new-in-symfony-4-3-timezone-validator

First, im not sure having a validator to allow both PHP and Intl timezones makes sense. It's one or another IMHO. As such, we should add the same `intl => false` option here :ok_hand:
