### ISSUE TITLE
An error occurred while loading the web debug toolbar.

### ISSUE THREAD

**Issue by SylvainDemaimay** [symfony/symfony#28847]
**Symfony version(s) affected**: 4.1.6

**Description**  
I redirect the user with an an event listener when he want to access to "login" or "register" if he is already logged, that works but then the web debug toolbar display only : "An error occurred while loading the web debug toolbar."

**How to reproduce**  
Use `$this->authChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')` in an event listener like i tryed first with my [KernelRequestListener](https://github.com/SylvainDemaimay/website_reforge/blob/ed5a665c094bf954a0f9b4baa2b074b147ac7fc9/src/EventListener/KernelRequestListener.php) and then with [RememberedSubscriber](https://github.com/SylvainDemaimay/website_reforge/blob/master/src/EventSubscriber/RememberedSubscriber.php) instead.

**Possible Solution** 
Not found yet, i guess it's about the token but after hours in the documentation i still don't get it.

**Additional context**  
I'm using FOSUser dev-master.

```
<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

class RememberedSubscriber implements EventSubscriberInterface
{
    const LOGIN_STEPS = array('register', 'login');

    private $authChecker;
    private $router;

    public function __construct(AuthorizationCheckerInterface $authChecker, UrlGeneratorInterface $router) {

        $this->authChecker = $authChecker;
        $this->router = $router;
    }

    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::RESPONSE => array('onKernelResponse', -256)
            //
            // so just after : -128 ...\WebDebugToolbarListener::onKernelResponse()
            //
            // i tryed also after : -1000 ...\SessionListener::onKernelResponse()
        );
    }

    public function onKernelResponse(FilterResponseEvent $event)
    {
        $logged = $this->authChecker->isGranted('IS_AUTHENTICATED_REMEMBERED');
        //
        // toolbar ---> "An error occurred while loading the web debug toolbar."

        // $logged = false;
        //
        // toolbar ---> OK


        // So "isGranted()" make my issue but the redirection works fine.


        if ($logged) {

            $pathInfo = $event->getRequest()->getPathInfo();

            foreach (self::LOGIN_STEPS as $keyword) {
                if (strstr($pathInfo, $keyword)) {
                    $event->setResponse(
                        new RedirectResponse(
                            $this->router->generate('fos_user_profile_show')
                    ));
                }
            }
        }
    }
}

```

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by SylvainDemaimay** [comment]
Hi,

At this point my app is not "big", i started with **symfony/website-skeleton** and **friendsofsymfony/user-bundle**, except some configuration, the event subscriber and my own css file : nothing more.

If your really prefere debbug it with a smaller version, so i could restart this by starting with **symfony/skeleton** wich will be a good exercice for me and allow us to isolate the bug probably. Otherwise you can [clone it](https://github.com/SylvainDemaimay/website_reforge.git).

**Comment by xabbuh** [comment]
Thanks, your example application helps to reproduce. Looking at the application logs an internal error is triggered by your `RememberedSubscriber` when the `FirewallListener` is not triggered.

I think you need to inject the token storage into your event subscriber and exit early in case there is no token.

I am closing here as there is nothing we can do in Symfony about that.

**Comment by SylvainDemaimay** [comment]
Thanks,

I'll try it and will confirm the success or report any problems if it is helpful.

**Comment by SylvainDemaimay** [comment]
**Maybe the "issue" still going on...** or i need probably to learn more about the token.

[My code](https://github.com/SylvainDemaimay/website_reforge/blob/master/src/EventSubscriber/RememberedSubscriber.php) works well now with : 
```
use Symfony\Component\Security\Core\Security;
// ...
if ($this->security->getUser() !== null) {
// ...
```

But that : 
```
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
// ...
$roles = $this->tokenStorage->getToken()->getRoles();
// ...
```
Toolbar display : "An error occurred while loading the web debug toolbar."

Or that : 
```
use Symfony\Component\Security\Core\Security;
// ...
$granted = [$this->security->isGranted('IS_AUTHENTICATED_REMEMBERED');]([url](url))
```
Toolbar display : "An error occurred while loading the web debug toolbar."

**Comment by SylvainDemaimay** [comment]
@xabbuh do you confirm that's not an issue from Symfony ? I tryed to get some informations about the token in the doc but it still blur for me.

**Comment by xabbuh** [comment]
Yes, when no route is found for a path the  `RouterListener` quits with an exception. Then, the `FirewallListener` will not be called. This means that no token will be populated in the token storage. That's why calling `getRoles()` in your first example does not work. Also, the authorization checker (which is used under the hood in your second example) cannot work without a token. So that usage will fail too.

**Comment by SylvainDemaimay** [comment]
Thank you for the time you have already spend here @xabbuh  

But for what i see in the profiler and also in dev.log there is no exception, just a matched route before the redirect. Well i'll look closer and thanks for the last explanation about the FirewallListener.

**Comment by allartdo** [comment]
I know this is an old post, but I have the same issue and do not belive `if ($this->security->getUser() !== null) {
// ...`  is the correct fix...

I dont know if it's a bug, but it certaintly is weird. Why would the main page do everything as without a problem, but only the symfony toolbar not? No functionality is broken, except from the toolbar.

I get the error when using the event listener `kernel.controller`. I have not tested on other `kernel.someEvent`. It occurs when using/checking the current logged in user. I guess it is not yet logged in for the toolbar. But is for the main page. `dump()` also gives the user object.

When looking into the network tab in chrome dev tools, I get the following error message: "The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL."

And 3 times an `AuthenticationCredentialsNotFoundException`. The toolbar says: "An error occurred while loading the web debug toolbar.".


I guess the "Right" fix would be to login the user before hand. But again it seems to already be logged in (when dumping or looking at main page etc.). Just not for the toolbar.
