### ISSUE TITLE
[HttpKernel] Trying to set custom status code on custom exception listener

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#28844]
**Symfony version(s) affected**: 4.1.x

**Description**
I have created a custom exception listener that it is triggered on `kernel.exception`. On this Listener I am setting on the event a Response with 200 HTTP Status code. It seems that this status code it is ignored and the [HttpKernel](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php#L239) class is setting the exception status code no matter what.

**How to reproduce**  
On this [link](https://github.com/gmponos/routerproblem) I have pushed a symfony project for another issue I am dealing with symfony but the case can be reproduced from there too. You can check [this](https://github.com/gmponos/routerproblem/blob/master/src/Listener/CustomExceptionListener.php) file

**Possible Solution**  
Not sure.. maybe have another flag/function on the event like `forceStatusCode`.

**Comment by xabbuh** [comment]
I think you simply also need to call `$event->allowCustomResponseCode()` in your listener when setting the response.

**Comment by gmponos** [comment]
🤦‍♂️ what? This is a little bit embarrassing... sorry for the trouble.

Yes.. it does work.... I might have been the comment [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php#L234) that made me to believe that if I need a custom status code I need to get inside the if and not skip it.

Thank you for your response.

**Comment by xabbuh** [comment]
@gmponos If you think we can somewhat improve the comment there, please feel free to open a PR with a suggestion for improvement. It seems like the current one is a bit confusing. :)

**Comment by gmponos** [comment]
I made a PR here which I find it better... ty again

https://github.com/symfony/symfony-docs/pull/10485
