### ISSUE TITLE
[RFC] Refactor caching of Translator component

### ISSUE THREAD

**Issue by rpkamp** [symfony/symfony#28851]
Currently the caching of the Translator component is sprinkled all over the place:

1. The Translator itself has a notion that catalogues can be cached (see [Translator#loadCatalogue](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/Translator.php#L270))
1. The Translator Fileloader knows about the Config component for caching (see [FileLoader#load](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/Loader/FileLoader.php#L51))
1. The Container has ~FileResources~ `FileExistenceResource`s and `DirectoryResource`s for translation files so the Container itself will be deemed non fresh when the translation files have changed (see [FrameworkExtension#registerTranslatorConfiguration](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1017))
1. ~~For some reason the Translator and the Router share the same ConfigCacheFactory (see [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.xml#L20) and [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/routing.xml#L75))~~ as @stof pointed out this isn't true
1. All of the above is focused on caching _files_ only, there is no notion of _directories_

This has the following drawbacks:

1. The Translator has too many responsibilities and thus too many reasons to change
1. There is double bookkeeping going on between the Container and Catalogues, so that when a translation file changes both the Container and the Translator cache need to be refreshed, whereas a refresh of just the Translator cache would suffice
1. When a new translation file is added to a directory the container will conclude it needs a refresh (because it has DirectoryResources for the translation directories), but the catalogue itself will never consider the new file (because it only has FileResources, no DirectoryResources - see https://github.com/symfony/symfony/issues/27600)
1. ~~When the routing configuration changes the translator has to be rebuilt and vice versa (because of the shared ConfigCacheFactory)~~ as @stof pointed out this isn't true

Proposal to solve these drawbacks:

1. Remove the responsibility of loading catalogues from the Translator, give this responsibility to a new MessageCatalogueLoader that knows how to load catalogues, but has no idea about caching
1. Add a CachedMessageCatalogueLoader that can decorate the MessageCatalogueLoader (so they both implement a common interface) and that knows how to cache catalogues, but has no idea how to load them (it delegates this to the MessageCatalogueLoader). This CachedMessageCatalogueLoader would also implement `SelfCheckingResourceInterface`, so it can indicate to the Container when it's no longer fresh - the container no longer needs to concern itself with that. This also decouples the Translator cache from the Router cache.
1. ~~Remove the notion of caching from the FileLoader class~~ - as @stof pointed out this isn't going to work because the decorator would need too much knowledge about what it's decorating
1. ~~Add a CacheAwareFileloader that decorates all FileLoaders to add caching (add FileResource to catalogue on load). Symfony Framework would use this decoration by default, but for the Translator component it's optional.~~  - as @stof pointed out this isn't going to work because the decorator would need too much knowledge about what it's decorating
1. Add a new DirectoryLoader that iterates all files in a directory and passes all files to FileLoaders to be loaded
1. ~~Add a CacheAwareDirectoryLoader that decorates DirectoryLoader to add the notion of caching (add DirectoryResource to catalogue on load). Symfony Framework would use this decoration by default, but for the Translator component it's optional.~~  - as @stof pointed out this isn't going to work because the decorator would need too much knowledge about what it's decorating

There are still a lot of implementation details to be considered, but this is the broad overview.

I'd love to hear what people think about this proposal!
If anything is unclear I'd love to clarify - ask me anything!

Also, I'd be willing to create a PR for this if this RFC gets accepted

**Comment by stof** [comment]
The container should only have FileExistenceResource, not FileResource, as it cares about the list of files, not their content.

>     4\. When the routing configuration changes the translator has to be rebuilt and vice versa (because of the shared ConfigCacheFactory)

what makes them shared ? Using the same ConfigCacheFactory does not mean they use the same ConfigCache (each call to the factory creates a separate one, and the router and translator don't use the path).


I'm not convinced by the usage of a decorator to register the resource in the catalogue. Knowing which resource to register depends on the implementation details of the loader, which makes it unsuited for being handled by a decorator.

**Comment by rpkamp** [comment]
> The container should only have FileExistenceResource, not FileResource, as it cares about the list of files, not their content.

Indeed it only checks for directories, so it will have `FileExistenceResource`s and `DirectoryResource`s, no `FileResource`s. My bad.

> what makes them shared ? Using the same ConfigCacheFactory does not mean they use the same ConfigCache (each call to the factory creates a separate one, and the router and translator don't use the path).

Ah, it seems I misunderstood the code there. Indeed they don't seem to share a cache after all.

> I'm not convinced by the usage of a decorator to register the resource in the catalogue. Knowing which resource to register depends on the implementation details of the loader, which makes it unsuited for being handled by a decorator.

In my mind there only were Php, Xml and Yaml loaders, but indeed there is also `ArrayFileLoader`, plus people can write their own by implementing `LoaderInterface`. I agree, decorator won't work here, the logic for adding `FileResource`s should stay in the `FileLoader` as there is no viable alternative (without abstracting it so much it becomes unrecognisable).

I'll update my original proposal to take this feedback on board. Thanks!

**Comment by rpkamp** [comment]
@stof I've updated my proposal. Points 1 (extract catalogue loading from Translator), 2 (caching catalogue loader decorator) and 5 (directory loader) still stand.

How do you feel about those?

**Comment by rpkamp** [comment]
I just tried to implement the `MessageCatalogueLoaderInterface` with a default implementation `MessageCatalogueLoader` and a caching decorator `CachingMessageCatalogueLoader` and it's a lot harder than I thought:

1. It's near impossible to do this without breaking BC in a _huge_ way since everything is so intertwined
1. The concept of fallback catalogues is so inherently complicated (not the Symfony implementation, just the concept on its own) that both the `MessageCatalogueLoader` and the `CachingMessageCatalogueLoader` would need to know a lot about it, kind of missing the point of a decorator

For these reasons I no longer feel this is something that must be pursued any longer. I'll try to solve the directory bug another way.
