### ISSUE TITLE
[Validator] CardScheme contraint with empty schemes option

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#28856]
Why is the `schemes` option of the `CardScheme` constraint required?

If think that if we add the constraint without specifying the `schemes` option, the constraint should validate if the value match one of the card scheme supported by Symfony.

**Comment by xabbuh** [comment]
I don't think that behaviour would be a good idea. Imagine that we add support for a new scheme in the validator. Your application would then claim to support this scheme too while your business code probably is not ready for that.

**Comment by Seb33300** [comment]
Yes but if our business code is dependent to some card scheme, so they have to be hardcoded in our constraint.

Leaving schemes option empty could be a way to ensure that the value looks to be a valid card number and not only random numbers.

**Comment by javiereguiluz** [comment]
I agree with @xabbuh. Saying *"I can accept any credit card you may add in the future"* is not realistic. Even today. it's may be not realistic to think that a business can accept all the cards we support, including Russian `MIR` and Chinese `CHINA_UNIONPAY`.

Given the 👎  votes from the Core Team, we must close this proposal. But we thank you for having proposed this and please, keep proposing new features to improve Symfony. Thanks!
