### ISSUE TITLE
[Security] `security:check` should output an error if `composer.lock` is invalid.

### ISSUE THREAD

**Issue by chrBrd** [symfony/symfony#28857]
**Description**
At present the `security:check` command will pass even if the `composer.lock` file is empty or malformed (as far as the server is concerned the project will have no dependencies). 

Due to `composer.json` being auto-generated, it's rare for it to cause any problems. Mistakes do happen, however, and I feel it's probably worth letting users know there's a problem with their lock file rather than giving a potentially false-positive result. 

I believe there used to be a check done server-side that would take care of this and return a 400 status code and invalid lock file message, but the response wasn't formed properly (the message was returned as a simple string rather than JSON with an `error` key) and consequently the message got swallowed when the resulting exception was thrown. That check now seems to be bypassed due to the client sending a valid array of empty packages even when the lock file is invalid.

**Proposed Solution**
Assuming validation of the lock file should take place client-side, I propose `SensioLabs\Security\Crawler\BaseCrawler::getLockContents()` should execute `json_last_error()` and throw an exception if the returned value is not `JSON_ERROR_NONE` after loading the lock file. For example:
```
protected function getLockContents($lock)
    {
        $contents = json_decode(file_get_contents($lock), true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new RuntimeException('An error occurred decoding the lock file: '.json_last_error_msg());
        }
        ...
```

It may also be worthwhile outputting a 'Nothing to check' error and exiting if both the `packages` and `packages-dev` arrays are empty, and throwing an exception if a package has no `name` or `version` attributes.

I can submit a tentative PR if it's felt this feature request is worth consideration.

**Comment by xabbuh** [comment]
The  `security:check` command is not part of Symfony. Can you please report it over in the [sensiolabs/security-checker repository](https://github.com/sensiolabs/security-checker)? Thank you! :)

**Comment by chrBrd** [comment]
No bother. Apologies for the needless noise. :)
