### ISSUE TITLE
HttpCache does not merge directive no-store is correctly

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#28872]
**Symfony version(s) affected**: all

**Description**  
When you have subrequests in your application and one of them sets the `no-store` `Cache-Control` directive, it will not make it to the client.
This is due to the `ResponseCacheStrategy` ignoring this attribute here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/ResponseCacheStrategy.php#L80

**How to reproduce**  

Have  a master request with `no-store` and an additional ESI request with `no-store`. The final response will have no `no-store` cache control directive.

**Possible Solution**  

Well, the PR that would solve this issue is open for a while: https://github.com/symfony/symfony/pull/26532
It correctly treats all the different cache control directives. This should've been merged a while ago 😄

**Comment by Toflar** [comment]
BTW: This might lead to potential security issues if one of your responses must have `no-store` (e.g. a response when logged into some admin back end) it will end up having **no** `no-store` `Cache-Control` directive and thus it will remain in your browser history.

Checkout this flow chart for the differences between `no-cache` and `no-store`: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en#cache-control

**Comment by mpdude** [comment]
You‘re talking about ESI subrequests only, not subrequests executed by the Kernel („embedded controllers“), right?

**Comment by Toflar** [comment]
Embedded controllers are not master nor surrogate requests so imho they should not be affected. We're talking surrogate master (ESI) requests here, yes: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L202
