### ISSUE TITLE
FlashBagInterface injection not working

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony#28886]
**Symfony version(s) affected**: 4.1.6 (and below)

**Description**  
The injection of the FlashBagInterface does not always work, injecting the SessionInterface instead seems to do the trick.
Note that sometimes, when I usually require the Security component it seems to work then.

**How to reproduce**  
Here is a reproducer: https://github.com/jmsche/flash-bag-reproducer (see master for bug, and branch session_interface for changes that make it work).

**Comment by iltar** [comment]
If you want the flashbag, you can type-hint the `Session` object in your action, which will inject the Symfony specific session object where you can call `getFlashBag()`

**Comment by jmsche** [comment]
@iltar The aim of the service is more advanced than the reproducer: it also gets the Translator so I can call `$service->addFlash($type, $message, $messageParams, $domain)` that will add the message to the flash bag & also translate it.

**Comment by LeFredd** [comment]
Hi @iltar if you read the `https://symfony.com/doc/current/controller.html#flash-messages` doc, you will see that for using the flash messages you need a Session, I think you could read this article too `https://symfony.com/doc/current/components/http_foundation/sessions.html#flash-messages`
