### ISSUE TITLE
[Cache] Null characters used (\0) in tag cache make really hard to use Redis CLI properly

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#28899]
When we use the tag cache feature, the keys of cache items are prefixed by :

https://github.com/symfony/symfony/blob/51f39b99998fad8119b596b3d7fd03b8cf99c562/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L28

The null characters used (`\0`) make really  hard to use Redis CLI properly. Here, an example that blocks me:

```php
$redis->set("\0abc", "z");
// Redis log: 1539762458.514872 [0 127.0.0.1:45978] "SET" "\x00abc" "z"
```
```sh
# Inside Redis CLI, it's ok
➜ redis-cli
127.0.0.1:6379> EXISTS "\x00abc"
(integer) 1

# Outside Redis CLI, I cannot...
➜ redis-cli EXISTS $'\x00'abc     
(integer) 0

# Redis log for the last command: 1539764075.840514 [0 127.0.0.1:46228] "EXISTS" ""
```
- Would you have a solution to execute successfully the last command ?
- And could you explain to me the reason why you decided to use that null character please, because I don't see the purpose (I'm surely missing something).

Thanks.

**Comment by maidmaid** [comment]
ping @nicolas-grekas (it seems that you coded it). Thanks :)

**Comment by nicolas-grekas** [comment]
I chose to add this nul char to be somehow confident that no collision would occur with any userland keys.
I always considered the keys on the backend as opaque strings you shouldn't have a look at directly (since you can/should use the PHP code interface to access it).
That's the reasoning for the current choices at least :)

**Comment by maidmaid** [comment]
Thank you for your answer @nicolas-grekas, and IMO your reasoning makes sense, BUT, in practice I'm having a concret use case where I'd like to handle theses keys through Redis CLI (without entering in Redis CLI shell) and I can't... Would you have a solution/tip to succeed the next command :

```sh
# Outside Redis CLI, I cannot...
➜ redis-cli EXISTS $'\x00'abc     
(integer) 0
```

**Comment by maidmaid** [comment]
Nope... :confused: 
```sh
➜ redis-cli EXISTS $(echo -ne "\0abc")
(integer) 0

# Redis log : 1539768537.573835 [0 127.0.0.1:46550] "EXISTS" "" "abc"
```

**Comment by nicolas-grekas** [comment]
OK, cannot be done from the CLI, see https://utcc.utoronto.ca/~cks/space/blog/unix/NoNullsInArguments

**Comment by maidmaid** [comment]
Ok, at least, it's clear now. Thank you for your help @nicolas-grekas :)

**Comment by maidmaid** [comment]
I let you close that issue, I don't know if you see something to do about it or all is said.

**Comment by gggeek** [comment]
Same pbl here :-(

**Comment by ardabeyazoglu** [comment]
This issue makes things harder and at least should be configurable. It is very hard to debug items or access them manually.  I don't believe it adds value on top of cache component either, it should be developer's responsibility to create unique tag/item names.
