### ISSUE TITLE
[Config] Opt out from env vars per node

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28896]
**Description**  

In #28858 we've concluded that it might be useful for config authors to opt-out from allowing env vars per node. In case a value needs to be known during compile time by definition.

Having such a semantic in core would enable proper error messages by default instead of just passing. Because now the user has to deal with the possibility of an unexpected/unusable value.

> the first real-world use case is in DoctrineBundle. the default entity manager cannot be changed using an env variable

> And we also have many similar cases in Symfony itself, where some settings are necessary at compile time (look at SecurityBundle for instance)

@stof suggested `forbidRuntimeValues()`, but at this point i'd like to propose a straightforward `forbidEnvironmentVariables() / forbidEnv()`

Created this issue in effort to close #28858

**Comment by javiereguiluz** [comment]
I like `forbidEnvironmentVariables()` because it's perfectly self-explanatory!

**Comment by stof** [comment]
another use case in the core: https://github.com/symfony/symfony/issues/28949

**Comment by xabbuh** [comment]
I agree with @javiereguiluz.

**Comment by Simperfit** [comment]
What's the status of this @ro0NL ?

Thanks.

**Comment by ro0NL** [comment]
no progress yet :)

it's more or less matter of exposing https://github.com/symfony/symfony/blob/770c7ddec42d797bfd7b312601594f89e46ff915/src/Symfony/Component/Config/Definition/BaseNode.php#L466-L469

as `forbidEnvironmentVariables()`, and the current `allowPlaceholders()` would tell if this new method is applicable for a node.

**Comment by ro0NL** [comment]
closing in favor of: #40794
