### ISSUE TITLE
ContextListener may disclose sensitive information i.e. credentials

### ISSUE THREAD

**Issue by OlegKunitsyn** [symfony/symfony#28900]
**Symfony version(s) affected**: 2.8.46+

**Description**  
Symfony\Component\Security\Http\Firewall\ContextListener::safelyUnserialize
and
Symfony\Component\Security\Http\Firewall\ContextListener::handle
may log sensitive information i.e. credentials that $serializedToken can have.
There is no way to override the methods or explicitly disable logging of 'received'.

**How to reproduce**  
* create a token
* serialize
* rename the class in
* try to safelyUnserialize

**Possible Solution**  
Exclude 'received' from logging in safelyUnserialize and handle

**Additional context**

**Comment by sstok** [comment]
A log can always have sensitive information, in fact everything in a log should be considered sensitive, but is most times needed to solve complex problems.

If you want to prevent that some information is not logged, there are some options. Use a NullLogger (which logs nothing). Or better if you use Monolog, you can register a custom Processor that removes sensitive information likes credentials, tokens, and other personal information (you don't need during production logging).

https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#processors
Like https://github.com/egeniq/monolog-gdpr

**Comment by javiereguiluz** [comment]
@chalasr do you think we could do something here to improve this ... or is this inevitable for the reasons given by @sstok? Thanks!

**Comment by chalasr** [comment]
Logs may contain sensitive information which are usually useful for debugging.
Sanitizing logs should not be the responsibility of low-level tools like the security component IMHO. 
I think we should close here.

**Comment by chalasr** [comment]
I just discussed with @xabbuh who confirmed that the token should not contain plaintext credentials, closing here.
