### ISSUE TITLE
[WebProfilerBundle] Dumps unreadable

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#28935]
**Symfony version(s) affected**: 4.2 i guess

**Description**  

![image](https://user-images.githubusercontent.com/1047696/47258461-dc8c4600-d49b-11e8-9352-5c4c77948933.png)

(white text on white background)

IMHO the green is too bright also

**Comment by ogizanagi** [comment]
Looks like the dark theme with a transparent background instead of the light one usually defined by the profiler styles.

**Comment by ro0NL** [comment]
So related to #28932 maybe

**Comment by nicolas-grekas** [comment]
Anyone willing to work on this?

**Comment by ro0NL** [comment]
See #29184
