### ISSUE TITLE
 [Profiler] Expose significant app metrics while in production to enable APM-like observability

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#28957]
**Description**  
Currently, the profiler is available when in debug, it attaches additional services and makes understanding what happened during a specific request easier.

The notion of [observability](https://twitter.com/copyconstruct/status/953703302578847745) nudges us to think how our system is behaving in production.

> TLDR of Observability - it's the way to understand how your system is behaving in Production. 
> It's a form of testing as well as discovering and understanding system pathologies. 

What this means for a Symfony app is exposing various metrics which could then be collected, aggregated and monitored. This is where I see the profiler overlapping with this concept: it has all the data (with much, much more), but it's only available in dev.

The proposed feature here is: enable a small subset of data collected by the profiler also be available while in production. This data could then be collected by a side-loaded system (outside of scope here) and shipped to a central metrics collection service, whatever it may be.

**Example**  

1. Doctrine queries: 3 queries in total, took 4msec
2. Redis cache: 109 hits, 3 misses, took 5msec
3. Guzzle: 2 requests, took 2sec
4. Swiftmailer: no mails sent
etc.

So, as said, the general rough idea is having mostly counters with timers, this should allow tracking those in real-time.

**Comment by fabpot** [comment]
Gathering metrics means adding a significant overhead to each request, which is why we do not do that in production. Having a subset would have the same issue and then the some: where do you store the metrics for instance is one of them, how do you anonymize the data (GDPR, ...). I think it's better to use an existing profiler like Blackfire if you want to understand what's going on in production. In any case, not something we are willing to add to Symfony core. Thanks for your proposition.

**Comment by stof** [comment]
And if you want to have APM-like observability rather than profiling, using an actual APM (which already solves this, and is generally implemented as a PHP extension to reduce overhead) would also be better.

**Comment by dkarlovi** [comment]
@stof that's not quite true. For example, if I use [Azure Application Insights for PHP](https://github.com/Microsoft/ApplicationInsights-PHP), I'm still expected to track all data points myself or add tracking code to my application.

My suggestion here was to enable very light-weight tracking of common bottlenecks. The output could then be flushed to Prometheus, InfluxDB or some other metrics tracking service (like mentioned Insights) as-is, at the end of the request.

My expected output would be an in-memory structure like this:
```yaml
metrics:
    router:
        route: some_route
    doctrine:
        queries: 21
        time: 123
    elastica:
        queries: 2
        time: 13
    mailer:
        mails: 1
```

This doesn't seem very resource-intensive to collect (it should easily be dwarfed by even a single database query, for example), GDPR concerns @fabpot mentioned are not applicable here and it would be off by default, impacting performance for only those who wish to use such instrumentation.

Maybe having the word "profiler" was wrong on my part. maybe "metrics" is more correct? This is **not** supposed to contain the body of every single SQL query, all the function calls, etc.
