### ISSUE TITLE
Messenger QueryBus

### ISSUE THREAD

**Issue by sukei** [symfony/symfony#28950]
Since this [recent move](https://github.com/symfony/messenger/commit/156758ac670abe4a0906c1413b1de124043b50cb), the `MessageBusInterface:: dispatch()` method can't return anything. I build CQRS apps using the Messenger since its release and use it to define the following three buses: command bus, event bus, and query bus. How are we supposed to do with the `query` bus right now ? Should I stop using a bus for the query part? Or mutate the `message` to transport the response? Thanks for your answers!

**Comment by nicolas-grekas** [comment]
Hi, thanks for asking. The PR introducing this change gives some alternatives, see #28909.
Would any work for you?

**Comment by sukei** [comment]
Sounds good. I'll follow your advices. Many thanks!
