### ISSUE TITLE
Option to disable rendering name attribute to submit button

### ISSUE THREAD

**Issue by Ferikl** [symfony/symfony#28964]
**Description**  
Add Possibility to not render **name** attribute to **submit button** (SubmitType).

**Example**  

I want to create simple Search Form like this:

```
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

$form = $formFactory->createNamedBuilder(null, FormType::class, null, ['csrf_protection' => false])
            ->setMethod('GET')
            ->add('tag', TextType::class, ['label' => 'Tag name'])
            ->add('Search By Tags', SubmitType::class)

            ->getForm()
        ;
```

When I render my Form in template 

```
{{ form_start(form) }}
{{ form_errors(form) }}
{{ form_end(form) }}

```
I can see:

`<button type="submit" id="Search By Tags" name="Search By Tags" class="btn-secondary btn">Search By Tags</button>`

But I dont want to have **&Search+By+Tags=** in my URL after form submit and Error with message: 

> ERROR This form should not contain extra fields.

So my suggestion is to add some param/option to SubmitType::class or whatever to NOT render **name="Search By Tags"** attribute.

**Comment by xabbuh** [comment]
I wonder why the extra fields error is thrown. Does this happen only when the form name contains a space?

**Comment by Ferikl** [comment]
> I wonder why the extra fields error is thrown. Does this happen only when the form name contains a space?

yes

**Comment by xabbuh** [comment]
I think the issue here is that the `ButtonBuilder` does not validate the passed name. The `FormConfigBuilder` does this and while doing so forbids names containing a space.

**Comment by Ferikl** [comment]
> @Ferikl So in your case the solution is to choose a name that does not contain spaces.

I am not sure that what I want. I want to have an option to not set name attribute to Submit button.

**Comment by xabbuh** [comment]
I don't think this is a use case that is common enough to justify an option for this in the Form component. IMO to achieve this you rather need to make use of the form theming mechanism in your application to make sure that the attribute is not rendered
