### ISSUE TITLE
[RFC][Console] TaskHelper?

### ISSUE THREAD

**Issue by Cydonia7** [symfony/symfony#28978]
**Description**  
I'm currently using Symfony Console for a task runner and I'm creating a `TaskHelper` that helps visualize the multi-step processes that happen. I'm wondering if this would be of any help to include it in the core or if this is too "niche" to be useful.

**Example**  

The goal is to make it look something like this:

![](https://raw.githubusercontent.com/SamVerschueren/listr/master/media/screenshot.gif)

Thank you for your input on this!

**Comment by stof** [comment]
I suggest iterating on it outside the core first. I'm not sure it can be generic enough to be in the core.
