### ISSUE TITLE
[Lock] FlockStore: delete lock files after release

### ISSUE THREAD

**Issue by digilist** [symfony/symfony#28979]
At the moment, the FlockStore does not delete lock files when a lock is released. It would be a great addition to keep the file system clean.

I am not sure, if this is actually possible. I tried to fix it myself, but deleting the file might interfere with another process that obtained the lock subsequently and already opened a file pointer. So I have no idea, if and how it can be fixed, but still wanted to open this issue in case someone else got an idea.

**Comment by nicolas-grekas** [comment]
Hi, you've got it right: the file is not deleted because doing so would create race conditions. There is no way to remove those files safely. There's nothing we can do about that. You should use another locking mechanism if you really don't want those files around.
