### ISSUE TITLE
[Form] Attatching an AbstractComparisonValidator to FormType contains the Form object and throws exception

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#28987]
**Symfony version(s) affected**: 4.1.x

**Description**  
When I attach to an object of mine through Yaml or annotation one of the `EqualsTo/NotEqualsTo/IdenticalTo/NotIdenticalTo` constraints then [this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L56) returns the object that the constraint is attached to.

``` yml
App\Form\Transfer:
    properties:
        from:
            - NotIdenticalTo:
                propertyPath: 'to'
```

So the line above will return the object `App\Form\Transfer`

If I add the constraint on a form type like this:

```php
        $builder
            ->add('from', ChoiceType::class, [
                'constraints' => [
                    new NotIdenticalTo(['propertyPath' => 'to']),
                ],
            ])
```

The line above will bring back a form object.

This causes the constraint to throw an exception because it reaches on [this line](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L58) and in the Form object the path of the property it does not exist.

**How to reproduce**  

Build a form in the way described above and submit it.

**Comment by iltar** [comment]
Setting a constraint via the form builder is not the same as setting a constraint on the data object. Not sure if this is a bug, but their behavior is different.

**Comment by HeahDude** [comment]
Thanks for reporting this @gmponos.

I will investigate on this, but to quickly fix your problem the workaround is to use the property path `data.to` when adding the constraint in the type.

**Comment by xabbuh** [comment]
This looks expected to me. When using the `constraints` option of the form type, the constraint will be associated with the form and thus property paths must be given according to the structure of the form as @HeahDude said. In your first example, you are attaching the constraint to your model.

**Comment by xabbuh** [comment]
I am closing as explained

**Comment by gmponos** [comment]
Hello,

My explanation was wrong

> The line above will bring back a form object.

Basically if I attach a constraint to the field I have only the field visible so if I do something like this:

```
        $builder
            ->add('from', ChoiceType::class, [
                'constraints' => [
                    new NotIdenticalTo(['propertyPath' => 'data.to']),
                ],
            ])
```

I get the following error:

```
PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "string" while trying to traverse path "data.to" at property "to".
```

If I add the constraint to the form I do not have access to both parts of the comparison

```
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver
            ->setDefault('constraints', function (Options $options) {
                return [
                    new NotIdenticalTo([
                        'value' => '', // what?
                        'propertyPath' => 'data.to'
                    ]),
            })
    }
```
