### ISSUE TITLE
The Web Debug Toolbar positionning does not play well with modern layouts

### ISSUE THREAD

**Issue by stof** [symfony/symfony#28981]
**Symfony version(s) affected**: all

**Description**  
Currently, the WDT gets injected at the end of the body, with 2 main DOM elements:

- the toolbar itself, set as `position: fixed` at the bottom
- a clearer element, which is in the flow and makes the same height than a non-wrapping toolbar (in case the toolbar wraps on multiple lines, the clearing does not adjust), to ensure that we don't hide content below the toolbar.

The clearing mechanism works fine when the main layout is based on the flow (it makes the main scrollbar a bit longer to account for the toolbar). But modern layouts can be built in different ways. And in case a grid with a `100vh` height is used, with scroll happening only *inside* the grid, things don't work fine anymore. The toolbar clearer now forces to add a scrollbar on body (it also makes it longer, as before, except that going from `no scrollbar` to `some scrollbar` has a much higher impact), leading to a double scrollbar.

**How to reproduce**  
See https://codepen.io/stof/full/ZqVQGq/ for an example (the toolbar content is not the Symfony one, but the clearer works the same)

**Possible Solution**  
No idea yet. I'm not sure this can actually be solved without knowledge about the way the grid works.

**Comment by javiereguiluz** [comment]
I've been playing with your example a bit and, as you said, I cannot think of any possible solution for this that works for every possible design.

I propose to close this as "won't fix" for now. Why? Because it only affects to developers working on the Symfony app and it just displays an extra scrollbar. Nothing actually "breaks". Thanks for understanding.

**Comment by Isinlor** [comment]
Would it be possible to fix it if having a "clearer element" would be configurable? I don't care whether the tool bar hides some content because I can minimize it anyway.
