### ISSUE TITLE
Serialize form with a CollectionType as an array not as object

### ISSUE THREAD

**Issue by hugoalexmartins** [symfony/symfony#28989]
Hey guys,

I am facing the follow problem:

- I have 2 entities Wizard and WizardQuestions oneToMany;
- I have a WizardType form which embed the WizardQuestions rows related;
- When I try to serialize WizardType I get an object of WizardQuestions with many objects 
- WizardQuestion indexed by keys, and I think I should get and Array.

Here is my output:

```json
{
   "wizard_questions":{
      "0":{
         "question":"Introduza por favor a sua residência igual ao que consta no seu passaporte",
         "type_question":"129",
         "wizard_answers":{
            "0":{

            }
         }
      }
}
```

But should be:

```json
{
   "wizard_questions":[
      {
         "question":"Introduza por favor a sua residência igual ao que consta no seu passaporte",
         "type_question":"129",
         "wizard_answers":[
           {

            }
         ]
       }
   ]
}
```

**Comment by xabbuh** [comment]
I am not sure I understand what you a trying to achieve. Can you create a small example application that allows to reproduce?

**Comment by hugoalexmartins** [comment]
@xabbuh Yes of course how can I do that ?
I have already a small case to show you.

**Comment by xabbuh** [comment]
Yes, like that please. :)

**Comment by xabbuh** [comment]
@hugoalexmartins Did you by any chance managed to create a reproducer? :)

**Comment by hugoalexmartins** [comment]
@xabbuh unfortunately I couldn't make it, but I will tomorrow or on Monday. 
Many thanks for your attention.

**Comment by xabbuh** [comment]
I am closing here for now, but we will reopen once we have a reproducible example.
