### ISSUE TITLE
Flash message behavior changed

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#28991]
**Symfony version(s) affected**: 4.1.3

**Description** 

When saving a boolean to the flash bag, the value is converted to an integer.

The code example below has worked for years, and is currently broken. Has something changed in Symfony?

**How to reproduce**
```php
if ($form->isSubmitted() && $form->isValid()) {
    $this->addFlash('status', true);

    return $this->redirectToRoute(...);
}

$this->addFlash('status', false);
```

```twig
{% from 'general/notify.html.twig' import error, success %}

{% for status in app.flashes('status') %}
    {% if status is same as(true) %}
        {% success('Saved successfully' | trans) %}
    {% elseif status is same as(false) %}
        {% error('An error occurred' | trans) %}
    {% endif %}
{% endfor %}
```

The message will not be printed. After some digging, it turns out that boolean values are converted to integers.

![image](https://user-images.githubusercontent.com/1032281/47561190-dc1c0100-d91a-11e8-9d75-470bf90359a2.png)

Note: our session data is saved in Memcached.

**Comment by nicolas-grekas** [comment]
Flash messages have always been documented as being strings. Anything else worked by chance I suppose. Now that we can use type hints, this is enforced. You should update your code here I suppose.

**Comment by OskarStark** [comment]
Maybe caused by some declare strict types?

**Comment by xabbuh** [comment]
@XWB Do you observe the same behaviour when using another storage like the filesystem?

**Comment by maryo** [comment]
I know it has been documented as being a string for years but I was always "misusing" the missing typehint 😈 by passing a value object like this
```
class FlashMessage
{
    const TYPE_SUCCESS = 'success';
    const TYPE_INFO = 'info';
    const TYPE_WARNING = 'warning';
    const TYPE_DANGER = 'danger';

    /** @var string */
    private $message;

    /** @var array */
    private $parameters;

    /** @var string|null */
    private $domain;

    /** @var string|null */
    private $locale;

    public function __construct(string $message, array $parameters = [], string $domain = null, string $locale = null)
    {
        $this->message = $message;
        $this->parameters = $parameters;
        $this->domain = $domain;
        $this->locale = $locale;
    }

    public function message(): string
    {
        return $this->message;
    }

    public function parameters(): array
    {
        return $this->parameters;
    }

    /**
     * @return string|null
     */
    public function domain()
    {
        return $this->domain;
    }

    /**
     * @return string|null
     */
    public function locale()
    {
        return $this->locale;
    }

    public function __toString(): string
    {
        return $this->message;
    }
}
```

I know it's sort of a hack but I still like. Couldn't the typehint be removed? 👼

**Comment by nicolas-grekas** [comment]
you can try submitting a PR. I don't promise anything!

**Comment by xabbuh** [comment]
In fact, the `FlashBagInterface` accepts any type of message (using `mixed` as the type explicitly). So this only happens when using the `ControllerTrait`.
