### ISSUE TITLE
DI glob resources do not set the class attribute of their definitions in new containers

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#29026]
**Symfony version(s) affected**: 4.1.6

**Description**  
DI glob resources do not set the class attribute of their definitions in new containers. This issue does not affect the main Symfony container, which clearly has some other undocumented steps applied to it that makes it work.

**How to reproduce**  
Create a new container [according to the documentation](https://symfony.com/doc/current/components/dependency_injection.html#setting-up-the-container-with-configuration-files).

```php
(new YamlFileLoader($container = new ContainerBuilder, new FileLocator($configPath)))
    ->load('foo.yaml');
```

Create a glob resource in `config/foo.yaml`:
```yaml
services:
  App\Foo\:
    resource: '../src/Foo/*/*Baz.php'
```

`$container->has('App\Foo\Bar\MyBaz')` returns `true` but `$container->get('App\Foo\Bar\MyBaz')` throws `\ReflectionException`: `Class  does not exist`. This is because the definition for the service has its `class` attribute set to `null`. Setting `autowire` and/or `autoconfig` to `true` make no difference.

**Comment by Bilge** [comment]
It would seem the missing step is simply, `$container->compile();`, although this is [not clearly explained in the documentation](https://symfony.com/doc/current/components/dependency_injection.html#setting-up-the-container-with-configuration-files).

**Comment by stof** [comment]
This is a documentation issue. Lots of things are happening in compiler passes. Not running them at all is not a supported usage of the component.
