### ISSUE TITLE
Autowire single implementation of an Interface

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony#29028]
**Symfony version(s) affected**: 4.*

**Description**  
Looking at the docs about autowiring [is stated that](https://symfony.com/doc/master/service_container/autowiring.html#working-with-interfaces)

> But now, the type-hint (App\Util\TransformerInterface) no longer matches the id of the service (App\Util\Rot13Transformer). This means that the argument can no longer be autowired.

> To fix that, add an alias: [...]

I've managed it to work without any `alias` as long as concrete implementation is unique (see below repository).
Looking around AutowirePass' internals with @garak (that pointed me out in the right direction) we found [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L334-L336).

So that's a discrepancy from what docs says and implementation.

I'm wondering if this is by design (so if it should deserve a better documentation, maybe suggesting equally to implement and `alias` that is "safer" from my POV) which I suppose to be the case, or if that's an unwanted behavior.

**How to reproduce**  
You can clone [this repo](https://github.com/DonCallisto/autowire-single-concrete-interface) and try to debug container with `bin/console debug:container`

If the docs need an enhancement, I would be happy to improve them.

**Comment by Nek-** [comment]
Hello,

You are right. Interfaces are automatically aliased in some cases. Which is great.

But if I add some complexity to your application (basically, namespaces autoloading for many namespaces). It doesn't work anymore: https://github.com/Nek-/autowire-single-concrete-interface (see the last commit).

That's why I think this piece of doc is useful. Please also take in consideration that your issue should probably be on https://github.com/symfony/symfony-docs repository.

**Comment by DonCallisto** [comment]
@Nek- I was just asking if docs were "wrong" or not. If it is the case, we (I) can just update it accordingly

**Comment by Nek-** [comment]
I'm exposing. But well, short answer is: no.

**Comment by DonCallisto** [comment]
@Nek- yes, of course, don't get me wrong just thought you were explaining something that was clear to me. Sorry if I seemed rude, it was not the case.
BTW at least to me, docs are not "wrong" but "inaccurate": if docs say that an alias is needed when there are cases where it's not, at least we should documentate this behaviour. 
WDYT?

**Comment by xabbuh** [comment]
Yes, I think we can clarify the documentation. Can you create an issue (or even propose some wording) in the documentation repository?

I am closing here as this is something we need to improve in the documentation instead of the code.
