### ISSUE TITLE
Problem: missing upgrade guide for abandoned option "framework.templating" (new option: "framework.assets")

### ISSUE THREAD

**Issue by KatharinaSt** [symfony/symfony#29036]
**Symfony version(s) affected**: 2.8 / 3.0 (on upgrade)

**Description**  
As the 2.8 branch will very soon be abandoned even the last legacy systems using 2.8 are now getting upgraded to 3.x (3.4 LTS).
Unfortunately there have been deprecations made earlier that are not documented in any upgrade guide (or at least I have not found any).
I am speaking of those changes:
https://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component#configuration-changes

From the article:
> "The previous options are now deprecated (they will disappear in Symfony 3.0), but for now the Asset component updates them automatically (you don't have to do any change in your application configuration if you don't want to)"

**How to reproduce**  
Upgrade from 2.x to 3.x without having made the changes to asset configuration yet.
You will get errors like that (e.g. when clearing the cache via console):

> Unrecognized option "assets_version" under "framework.templating"

**Possible Solution**  
Include details of the mentioned article in the upgrade guide to 3.x so that it is easier to make all required changes when updating.

**Additional context**  
https://github.com/symfony/symfony-docs/pull/6172/files

**Comment by xabbuh** [comment]
@KatharinaSt Good catch 👍 Would you like to prepare a pull request updating the upgrade files?

**Comment by KatharinaSt** [comment]
@xabbuh Sure, I can do this.

However, I am not sure in which guide this belongs and if it is really a 3.x issue because version 2.8 should already have abandoned all of those old configs.
Nevertheless at least in my project this has not been an issue until yesterday (upgrade from 2.8 directly to 3.4).
By now I will put it into UPGRADE-3.0.md; at least unless I don't find out otherwise.

**Comment by KatharinaSt** [comment]
The 3.0 upgrade guide should actually be the correct one as it says here that those options will be removed in 3.0:
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php

Also mentioned here:
"framework.validation.api" (removed in 3.0 as well)
