### ISSUE TITLE
Expression language, `matches` inconsistency

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#29048]
**Symfony version(s) affected**: any

**Description**  

`matches` operator is documented in the section of the "comparison operators". Yet it still returns not boolean `true | false`, but numerical `1 | 0` instead.

This behaviour is inconsistent with other comparison operators and to my opinion it makes very little sense to return numbers there at all

**How to reproduce**  

```php
$expressionLanguage = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage();

$r = $expressionLanguage->evaluate("'a' matches '~a~'");

var_dump($r);
```

**Possible Solution**  

The `evaluate` step of the `BinaryNode` might be instead:

```
            case 'matches':
                return preg_match($right, $left) === 1;
```

**Additional context**  

It definitely would be a BC. So I'm expecting it won't be changed, this issue is just to track that such inconsistency exists and is known.

**Comment by nicolas-grekas** [comment]
I confirm the behavior and the fact that changing it would be a BC break that I don't think is worth it.
