### ISSUE TITLE
download attribute does not work with annotations

### ISSUE THREAD

**Issue by dlorre** [symfony/symfony#29053]
**Symfony version(s) affected**: Symfony 4.1.6 (kernel: src, env: dev, debug: true)

**Description**  
When using annotations the download attribute of the <a> tag ignores the route.

**How to reproduce**  

Controller:
```
    /**
     * @Route("/json/{lang}/{nom}.json", name="exportPublicJSON")
     */
    public function exportJSONAction($lang, $nom)
    {
        dd($lang, $nom);
        $nomfic = $_SERVER ["DOCUMENT_ROOT"] . "/json/$lang/$nom.json";
        return $this->exportJSON($nom, $nomfic);

    }

```
twig:
```
                            <a href="{{ path('exportPublicJSON', {'lang' : locale, 'nom' : nom}) }}"
                               download>{{ "Exporter l'assistant en JSON"|trans }}</a>

```
If the file does not exist in the path it will display a file not found error instead of calling the controller method.

**Possible Solution**  

There is a workaround by using a route:

route_download:
```
  path:       /json/{lang}/{nom}.json
  controller: App\Controller\ExportController::exportJSONAction
  methods:    [GET]

```
```
                            <a href="{{ path('route_download', {'lang' : locale, 'nom' : nom}) }}"
                               download>{{ "Exporter l'assistant en JSON"|trans }}</a>

```
The controller is now called.

**Comment by xabbuh** [comment]
I do not understand the problem. What do you mean with "the download attribute"? Which file is not found? Can you create a small example application that allows to reproduce your issue?

**Comment by dlorre** [comment]
Hello, the <a> tag has a download attribute that allows you to save the link to a file instead of opening it into the browser.

https://www.w3schools.com/tags/att_a_download.asp

While I could create a sample application, I don't have much time right now and I think that I have described the problem correctly. This can be a nasty bug if the file already exists because I am using the controller method to check if it needs to be updated.

**Comment by xabbuh** [comment]
Well, I have no idea what your `exportJson()` method is doing. Without a reproducible example we will probably not be able to help you and I don't see why defining the route in YAML should be different than defining it using annotations.

If you do not have the time to create a reproducible example, that's okay. But I am going to close here then as we cannot do much here. But we can of course reopen if someone is able to reproduce it.

**Comment by dlorre** [comment]
Yes close it, I don't use annotations anymore, there too many problems with them.

**Comment by soufianZantar** [comment]
@dlorre i tried to reproduce your bug, but i can't find the bug, the annotation work for me.
Which server you use ?

[reproducible example](https://github.com/soufianZantar/issues-download-attribute)

**Comment by dlorre** [comment]
Thanks for checking, I'm using apache but it's not the cause of the problem. It turned out my code was incorrect after the dd() but a cache issue led me to think of a bug.  After refreshing the cache I could make it work with annotations.
