### ISSUE TITLE
Memory usage on Symfony Form

### ISSUE THREAD

**Issue by alexey-okhorzin** [symfony/symfony#29055]
Hello. How to reduce the memory usage on Symfony Form? 
A form can use more then 128 MB, if I build a form with many fields and then render its. For example a form with 500 fields (a form with multiple embedded forms). Such form uses about 12 MB.
Every invoke the add method of the FormBuilder class uses about 16KB.

**Comment by alexey-okhorzin** [comment]
I use symfony framework, not custom integration.
`<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Form\Forms;
use Symfony\Component\Form\Extension\Core\Type\TextType;

$formFactory = Forms::createFormFactoryBuilder()->getFormFactory();

$a = memory_get_usage();
$form = $formFactory->createBuilder()
    ->add('task', TextType::class)
    ->add('task2', TextType::class)
    ->getForm();
$b = memory_get_usage();

var_dump($b - $a);

`
Every field uses about 5.4 KB

**Comment by xabbuh** [comment]
I don't think there is much we can do. The Form component is complex due to how forms can be built, extended and modified. This does not mean that there isn't room for improvement, but on a first glance the numbers you have here don't look too bad.

**Comment by xabbuh** [comment]
Let's close here as there is no ad-hoc solution, but we can always consider to improve parts of the framework if someone proposes a more performant solution.
