### ISSUE TITLE
TextType Field empty_data bug - Expected argument of type "string", "NULL" given.

### ISSUE THREAD

**Issue by dawsza** [symfony/symfony#29061]
The documentation for TextType form field says:

> The default value is '' (the empty string).

[https://symfony.com/doc/current/reference/forms/types/text.html#empty-data](https://symfony.com/doc/current/reference/forms/types/text.html#empty-data)

But probably it isn't true because when we have entity:

```
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FooRepository")
 */
class Foo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $stringField = 'default value to overwrite';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStringField(): ?string
    {
        return $this->stringField;
    }

    public function setStringField(string $stringField): self
    {
        $this->stringField = $stringField;

        return $this;
    }

```

the form:

```
namespace App\Form;

use App\Entity\Foo;
use http\Env\Request;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FooType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('stringField', null, ['required' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Foo::class,
        ]);
    }
}

```

and the controller like this:

```
namespace App\Controller;

use App\Form\FooType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     */
    public function index(Request $request)
    {
        $form = $this->createForm(FooType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            dump($form->getData()->getStringField());
        }

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'form' => $form->createView(),
        ]);
    }
}

```

Then is throw InvalidArgumentException by PropertyAccessor.php:

> Expected argument of type "string", "NULL" given.

because $form->getData()->getStringField() is null instead empty string like default defined in documentation.

**Comment by xabbuh** [comment]
In fact, the documentation is not completely right here. You will explicitly need to set `empty_data` to the empty string to not have it transformed to `null` like this (see #5906 and #18357):

```php
// ...

class FooType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('stringField', TextType::class, [
                'empty_data' => '',
                'required' => false,
            ])
        ;
    }

    // ...
}
```

Does this solve your issue?

**Comment by dawsza** [comment]
It is some kind of issue solving but in my opinion it isn't enough solution because it dosn't work when we want to use type guessing, and documentation is misleading.

**Comment by xabbuh** [comment]
Thanks for the feedback. I am going to close then as the code is working as expected. But I have reopened symfony/symfony-docs#7596 so that we take care of updating the documentation to fix the description there to match the actual behaviour.

**Comment by artyuum** [comment]
@xabbuh 's solution kinda helped me but in my case, I needed to keep empty values as null when persisting the form data. To fix this, I simply needed to set the field argument type to nullable (in the entity):
```php
public function setDisplayName(?string $displayName): self
{
    $this->displayName = $displayName;

    return $this;
}
```
This part `string $displayName` needed to be changed to `?string $displayName`.

**Comment by reddingwebpro** [comment]
> It is some kind of issue solving but in my opinion it isn't enough solution because it dosn't work when we want to use type guessing, and documentation is misleading.

To retain type guessing, you can simply use _null_ instead of _TextType::class_

Such as:

$builder
            ->add('stringField', _null_, [
                'empty_data' => '',
                'required' => false,
            ])
        ;

**Comment by mindaugasvcs** [comment]
It's funny. Why would a non-nullable text property in entity be set to null if HTML form contains empty string for that field?
What's even more funny * @Assert\NotBlank() does not even work as expected in such case. All it says is: Expected argument of type "string", "null" given at property path...

**Comment by stof** [comment]
> What's even more funny `@Assert\NotBlank()` does not even work as expected in such case. All it says is: Expected argument of type "string", "null" given at property path...

Well, that TypeError happens when setting the value in the object, which happens before running the validator on that object.
