### ISSUE TITLE
isSubmitted() doesn't work

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#29060]
**Symfony version(s) affected**: 4.1.6

**Description**  
I try to check form is submitted or not but isSubmitted() always return "false".

**How to reproduce**  
`if($form->isSubmitted()){}`

**Possible Solution**  
```
   public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username', TextType::class)
            ->add('password_hash', PasswordType::class)
            ->add('submit', SubmitType::class)->setMethod(Request::METHOD_PUT)->getForm();
    }
```

**Additional context**  
Possible bug. Didn't see in documentation about method PUT for isSubmitted() function...

**Comment by xabbuh** [comment]
Can you please show how you handle the form submission in your controller?

**Comment by RSalo** [comment]
```
       $userEntity = new User();
        $form = $this->createForm(UserFormType::class, $userEntity);
        $form->handleRequest($request);
        var_dump($form->isSubmitted()); //FALSE
        if ($form->isSubmitted() && $form->isValid()) {
...
        }
```

**Comment by RSalo** [comment]
> I just spotted that you configured the expected HTTP method on the button. This must be done on the form level.
> 
> Either inside the type in `configureOptions()`:
> 
> ```
> public function configureOptions(OptionsResolver $options)
> {
>     $options->setDefault('method', 'PUT');
> }
> ```
> 
> Or when configuring the form in your controller:
> 
> ```
> $form = $this->createForm(UserFormType::class, $userEntity, [
>     'method' => 'PUT',
> ]);
> ```
> 
> Can you confirm that this solves the issue for you?

Hurray! I fixed the problem. I have invalidate "csrf_token_id".
Problem fixed by:
```
class UserFormType extends AbstractType
{
...
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_token_id' => 'login_form_csrf' // <- explicit variable
        ]);
    }
...
}
```

    public function getUser($credentials, UserProviderInterface $userProvider): UserInterface
    {
        $token = new CsrfToken('login_form_csrf', $credentials['_token']);

        if (!$this->csrfTokenManager->isTokenValid($token)) { // <- token is invalid
            throw new InvalidCsrfTokenException();
        }
...
    }

But next question, why this is work on "PUT" method and token doesn't validate in this case?
