### ISSUE TITLE
[DI][4.2] It's a requirement to specify a Metadata Driver and pass it to Doctrine\ORM\Configuration::setMetadataDriverImpl().

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29078]
**Symfony version(s) affected**: 4.2

This is another report of #28304

The reproducing app is at https://github.com/ro0NL/sf

Running `git apply patch.diff && composer install` (to downgrade to 4.1) solves it.

**Comment by ro0NL** [comment]
So, the weird thing is it only happens during initial container building (or cache:clear)

**Comment by nicolas-grekas** [comment]
Should be fixed in #29103

**Comment by nicolas-grekas** [comment]
(now merged up to master, should be easier to test)
