### ISSUE TITLE
DI child containers 

### ISSUE THREAD

**Issue by Bilge** [symfony/symfony#29075]
Symfony supports the concept of just a single DI container for the entire application. If the configuration file becomes too big it can be split into separate files with includes, but it does not support isolating separate groups of services in separate containers. This is true despite the fact that the documentation explains how to [create containers from scratch with configuration files](https://symfony.com/doc/current/components/dependency_injection.html#setting-up-the-container-with-configuration-files).

It may be desirable in some applications to provide sub-containers that contain services of just one type for scenarios where container injection is desirable or required, but one does not want to inject the main container with all services. This is already possible by defining a `ContainerInterface` service that loads a custom configuration file as shown in the aforementioned documentation section. However, even though only services defined in the sub-container can be retrieved from that container, some of the services in the sub-container may have dependencies on services in the main container. For this use-case, it is important to establish a parent/child relationship between the sub-container and the main Symfony container in which the child container defers to the parent for dependencies it cannot fulfil.

Zend Framework already supports separate containers for different groupings of services, such as controllers and forms, but it's a little less trivial in Symfony due to the compiler steps. We cannot simply override `get()` to defer to the parent container for missing service definitions because compilation will fail before we can ever make a `get()` call. The compiler must be made aware of the parent container and either copy in or link to the definitions it needs from the parent according to the dependency graph.

**Comment by jvasseur** [comment]
You can already have a sub-container that has access to only a subset of the main container with [service locators](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-locator).

It's not exactly a child container since it only proxies a subset of services of the main container (but it can make publicly available services that are private in the main container), but I believe it can handle all use cases for child containers.

**Comment by Bilge** [comment]
@jvasseur Whilst that is interesting, it's very limited because each service has to be defined one-by-one in the service locator. That is highly restrictive compared to creating a real DI container that can be configured with glob resources to mass include all services matching a certain file pattern.

**Comment by jvasseur** [comment]
@Bilge you can use glob resources or defaults in a specific file to add a tag to your services that you want to be in the sub-container then use a compile pass to collect all services with that tag and create a service locator with all those services. This is what is done in the framework for form types for example: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/DependencyInjection/FormPass.php#L63-L84.

**Comment by Bilge** [comment]
Thanks @jvasseur. I had presumed I would need to do as much but the code example will surely be helpful. I am not exactly sure which bits I need to replicate, however. It seems that code is probably doing a lot more than I would need to do. Do I just need to copy definitions from the container into the service locator? Documentation on this topic is quite scarce.

**Comment by Tobion** [comment]
`ServiceLocatorTagPass::register($container, $servicesMap);` returns the new service locator. You can then inject that locator to the services that need it. This is what is done with `$definition->replaceArgument(0, $this->processFormTypes($container));`

**Comment by nicolas-grekas** [comment]
There's also another way to create several containers: multi-kernel apps. That's basically what a kernel: a scope for a container. Many apps use these since years.

**Comment by Bilge** [comment]
@nicolas-grekas That doesn't seem like a very intuitive solution, and poses more questions than it answers. Specifically, how would one get services in one kernel that depend on services in another kernel to work together and without being optimized away by the compiler?

**Comment by jakzal** [comment]
> It may be desirable in some applications to provide sub-containers that contain services of just one type for scenarios where container injection is desirable or required, but one does not want to inject the main container with all services. 

I'm still missing a use case here. Could you think of a real life scenario where you'd need a "sub-container"? I thought service locators cover our bases.

**Comment by Bilge** [comment]
@jakzal To my understanding, a service locator is a container with a subset of the parent container's services (that's not its standard definition, but is an intended use-case of service locators within the Symfony framework). Therefore, a service locator *is* a sub-container, and seems to be perfectly suited to my purposes.

I'll try implementing it as described in this ticket tomorrow. However, even if it does work, it's worth noting that this use-case is pretty poorly documented at present. It does not seem easy or intuitive to find `ServiceLocatorTagPass::register` were my attention not guided directly to it by the experts herein.

**Comment by Bilge** [comment]
@nicolas-grekas That would be interesting. Upon re-reading [the doc](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-locator), I now see there is a mention of `ServiceLocatorTagPass::register`. But not only did I not end up using it, and not only does it not really explain why you need to use it, but it seems this statement is patently misleading:

>and will automatically share identical locators amongst all the services referencing them

When I read that, I started to worry that not using the static `register()` method would recreate the service locator every time it's referenced. But a simple `KernelTest` would seem to indicate that's not the case. I've since deleted it but it looked something like this:

```php
$a = self::$container->get('my_locator');
$b = self::$container->get('my_locator');

self::assertSame($a, $b);
```

Since this test passed I assumed I do not need to use `register()` to have the same Service Locator shared between its dependents.

Notwithstanding I don't know the RST format, like I said at the beginning, it's interesting because it seems you originally wrote that piece of documentation but I can't see how it would segue into my implementation because it seems diametrically opposed to what you're currently recommending to people wanting to implement Service Locators!

**Comment by nicolas-grekas** [comment]
I'm not sure to understand all the details here so feel free to share some code/example app.
About ServiceLocatorTagPass::register(), what is does is dedup same locator *definitions* (it's about dedup at compile time - not runtime)

**Comment by nicolas-grekas** [comment]
I'm closing here as this overlaps with #25707 and #28992 + not sure how actionable this is.
