### ISSUE TITLE
symfony cache predis parse auth error

### ISSUE THREAD

**Issue by l396635210** [symfony/symfony#29088]
I use symfony cache companent with preids, and my password whit an "@",the RedisTrait parse the auth is error:

For example : 
 I write 'redis://123@456@127.0.0.1:6379' will parse "123", 
 and when i write 'redis://123\\@456@127.0.0.1:6379' , it will parse the value '123\\',
so it will be bad.

And will can  i do ?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by nicolas-grekas** [comment]
try url encoding the symbol
