### ISSUE TITLE
Unused state of some translations which are really used

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#29085]
I am not sure if it is expected behaviour.
According to docs https://symfony.com/doc/current/translation/debug.html
I run command php bin/console debug:translation nl --domain=messages --only-unused
and got all unused translations, **but, some of them used!**
Example
```
 State         Domain                     Id         Message Preview (nl)        Fallback Message Preview (en)          
  unused  |  messages  |  xml.searchTitle.days.total  | voor %total% ...  |   xml.searchTitle.days.total                
 ---------- ---------- ------------------------------------------------------------------- ---------------------------------------
php bin/console debug:translation nl --domain=messages --only-unused
```
But with global search I found that this translation is used
```
 if ($totalDays <= 3) {
                $params['%days%'] = $this->translator->trans(
                    'xml.searchTitle.days.specific',
                    [
                        '%days%' => $this->availabilitiesToString($availabilitySchedule, true),
                    ]
                );
            } else {
                $params['%days%'] = $this->translator->trans('xml.searchTitle.days.total', ['%total%' => $totalDays]);
            }
```
Why is shows state unused when it is used?

There area thousands  of translations, because this command is not reliable  I cant trust  it, I have to check every translation manually if it is used...
There are a lot of cases with wrong state.
Strange but I found above unused states, that translations  with unused state I removed, now has state missing, if I return them, they have both states, used and unused at the same time.
 It happens not with all translations, some of them really unused, missing or used and has only one state.
Also, I am not sure if translations which used in twig counted, because found many with status used, but they are used in twig templates.
And some message when adding flash in controller is also missed, state unused.

**Comment by xabbuh** [comment]
Unfortunately, that's expected. As the docs state the command is only able to find translation usages in templates.

**Comment by BonBonSlick** [comment]
Thank you @xabbuh So everyone also search translations with global IDE search ?

**Comment by nicolas-grekas** [comment]
Until now yes. In theory it could be possible to extract more messages by analyzing the code, but someone would need to contribute the code :)

**Comment by nicolas-grekas** [comment]
Hum actually there is already a `PhpExtractor` and https://github.com/symfony/symfony/pull/26738 on the topic. Maybe we should allow configuring the paths where the command should look for translations?

**Comment by yceruto** [comment]
The translator config already has a `paths` option that can be used for other translation dirs and they are not supported by commands yet, so yes, we're missing some messages here.

I can try it.

> https://github.com/symfony/symfony/pull/26738#issuecomment-436409236
> Another idea could be to detect all services that have the translator injected into them and consider them all as targets for translation extraction.

Sounds interesting... I'll take a look.

**Comment by BonBonSlick** [comment]
Thanks

**Comment by yceruto** [comment]
I did not change the issue reference after splitting the PR so it should probably remain open waiting for https://github.com/symfony/symfony/pull/30120
