### ISSUE TITLE
symfony/process componet can not record log when use Guzzle request

### ISSUE THREAD

**Issue by nadirvishun** [symfony/symfony#29082]
**Symfony version(s) affected**: 
- not use full Symfony, just use `symfony/process` componet, the version is 3.4
- `guzzlehttp/guzzle` version is 6.0
- the OS is Win10

**Description**  
- In Windows, execute php procee when use Guzzle request ,can not record log.
- In Linux ,no test.

**How to reproduce**  
the master:
```
    public function test()
    {
        //in process run sub function
        $cmd = $this->php . ' ' . ROOT_PATH . 'public' . DS . 'index.php  api/read_feature/sub';
        $process = new Process($cmd);
        $process->start();
    }
```
the process:
```
public function sub()
    {
       //the www.abc.test not real exist,so will throw ConnectException,but nothing record in log file
        $client = new Client(['base_uri' => 'http://www.abc.test', 'timeout' => 2.0]);
        try {
            $response = $client->request('GET');
            $statusCode = $response->getStatusCode();
        } catch (ConnectException $e) {
            Log::error('error1：' . $e->getMessage());//no record log
        } catch (RequestException $e) {
            Log::error('error2：' . $e->getMessage());//no record log
        } catch (Exception $e) {
            Log::error('error3：' . $e->getMessage());//no record log
        }
    }
```
then run the `test` function, then `test` create procee to run `sub` function ,the result:
```
//nothing in log file
```
if run the `sub` function directly without process, the result:
```
//has record in log file 
error1:Failed to connect to www.abc.test port 80: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

if change process and not use guzzle, just throw Exception:
```
public function sub()
    {
        try {
            throw new Exception('abc');
        } catch (Exception $e) {
            Log::error('error3：' . $e->getMessage());//has record in log file
        }
    }
```
then run the `test` function, then `test` create procee to run `sub` function the result:
```
//has record in log，only guzzle Exception has this problem
error3:abc
```

**Possible Solution**  
I do not know why  ,if use `popen` function ,the log can record, but `$process->start()` can't.
```
   public function test()
    {
        $cmd = $this->php . ' ' . ROOT_PATH . 'public' . DS . 'index.php  api/read_feature/sub';
        if (substr(php_uname(), 0, 7) == "Windows") {
            //windows, can record log
            pclose(popen("start /B " . $cmd, "r"));
        } else {
            //linux
           exec($cmd . " > /dev/null &");
        }
    }
```

**Additional context**  
no

**Comment by Tobion** [comment]
Where does `Log:error` log to? Is it sterr? You can also check `$proess->getErrorOutput()` what is has.

**Comment by nadirvishun** [comment]
@Tobion ,`Log::error` just write message to a log file, `$proess->getErrorOutput()` output nothing ,because i use Asynchronously `$process->start()`, if I use `$process->run()`, the log can record correct!

**Comment by xabbuh** [comment]
Probably the child process never finishes as it is terminated when your main PHP script exits. Does it change anything if you add `$process->wait()` after calling `start()`?

**Comment by nadirvishun** [comment]
@xabbuh  if add `$process->wait()`, can get the log message correct.

**Comment by xabbuh** [comment]
That's expected behaviour then. Your main process simply terminates too early to let Guzzle in the child process log anything before the child process is terminated by the kernel. You need to make sure that your parent process waits for your children to end. I am closing here as there is nothing to fix.

**Comment by nadirvishun** [comment]
Thanks! I get it.
```
public function test()
    {
        $processArr=[];
        //open 5 process
        for($i=0;$i<5;$i++){
            //in process run sub function
            $cmd = $this->php . ' ' . ROOT_PATH . 'public' . DS . 'index.php  api/read_feature/sub';
            $process = new Process($cmd);
            $process->start();
            $processArr[]=$process;
        }
       //judge process is end 
        while(count($processArr)){
            foreach ($processArr as $i => $runningProcess) {
                // specific process is finished, so we remove it
                if (!$runningProcess->isRunning()) {
                    unset($runningProcesses[$i]);
                }
                // check every second
                sleep(1);
            }
        }
    }
```
The same question in stackoverflow: [Run an asynchronous PHP task using Symfony Process](https://stackoverflow.com/questions/29223825/run-an-asynchronous-php-task-using-symfony-process)
and this article has detail code: [How to Run Symfony Processes Asynchronously](https://www.tomasvotruba.cz/blog/2018/02/05/how-to-run-symfony-processes-asynchronously/)
