### ISSUE TITLE
[4.2] Contracts 1.0 is missing

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#29087]
**Symfony version(s) affected**: 4.2.0-beta1

**Description**  
Some Symfony 4.2 packages now have the requirement `symfony/contracts: ^1.0`, but there there is no 1.x release of that package yet. I would expect at least an available beta release.

There is however a tag `v4.2.0-BETA1` on the contracts package. This looks like a mistake.

See: https://packagist.org/packages/symfony/contracts

**How to reproduce**  
Try to bootstrap a Symfony 4.2 project with minimum stability `beta`, for example:

```JSON
{
    "minimum-stability": "beta",
    "require": {
        "symfony/framework-bundle": "^4.2"
    }
}
```

Output:
```
$ composer up
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/cache v4.2.0-BETA1 requires symfony/contracts ^1.0 -> satisfiable by symfony/contracts[1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - symfony/framework-bundle v4.2.0-BETA1 requires symfony/cache ~4.2 -> satisfiable by symfony/cache[v4.2.0-BETA1].
    - Installation request for symfony/framework-bundle ^4.2 -> satisfiable by symfony/framework-bundle[v4.2.0-BETA1].
```

**Possible Solution**  
Tag a `v1.0.0-beta1` on the `symfony/contracts` package.

**Comment by jaikdean** [comment]
For anyone who needs to, you can test Symfony v4.2.0-BETA1 while this is being fixed by adding the following requirement to your `composer.json`:

`"symfony/contracts": "v4.2.0-BETA1 as 1.0.0"`

**Comment by fabpot** [comment]
I've fixed the releasing process so that we do not tag contracts anymore automatically. Should be done manually now.
