### ISSUE TITLE
Symfony/Process composer install failed

### ISSUE THREAD

**Issue by thlbaut** [symfony/symfony#29096]
**Symfony version(s) affected**: 2.8.47

**Description**  

I have updated my composer dependencies. Composer install (in Gitlab CI pipeline with same version of PHP) failed with the following error.

How can I resolve the issue ?

**Additional context**  

```
Problem 1
    - Installation request for symfony/process v3.4.18 -> satisfiable by symfony/process[v3.4.18].
    - don't install symfony/symfony v2.8.47|don't install symfony/process v3.4.18
    - Installation request for symfony/symfony v2.8.47 -> satisfiable by symfony/symfony[v2.8.47].
```

**Comment by stloyd** [comment]
It's not bug nor new feature but support request, you should ask on official slack for support.

Saying that you have probably hard lock on `"symfony/symfony": "^2.8.47"` in your `composer.json` file which is clearly reported by Composer itself in your quote.

**Comment by nicolas-grekas** [comment]
This is caused by https://github.com/composer/composer/issues/7764 - ie that's a Composer issue, not a Symfony one.
Thanks for reporting.

**Comment by thlbaut** [comment]
Thanks for your answers !
