### ISSUE TITLE
is there an easy way to mock private service in functional test?

### ISSUE THREAD

**Issue by videni** [symfony/symfony#29091]
Symfony4 has a [TestContainer](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) which can let us get private services , but mocking private service  doesn't work in functional test , because the TestContainer and the real container for functional test are different.
```
static::$container->mock(SmsCaptchaValidator::class, SmsCaptchaValidator::class)
            ->shouldReceive('validate')
            ->once()
            ->andReturn(true);

       $data =
<<<EOT
        {
            "phone_number": "28382388319",
            "code": "123456"
        }
EOT;
        $this->client->request('PUT', '/api/admin/change/phone_number', [], [], $this->getAuthorizedHeaderWithContentType(), $data);

        $response = $this->client->getResponse();
        $this->assertResponseCode($response, Response::HTTP_CREATED);
```

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
