### ISSUE TITLE
Preload RFC and Symfony

### ISSUE THREAD

**Issue by kejwmen** [symfony/symfony#29105]
Hi,

[Preload RFC](https://wiki.php.net/rfc/preload) is now in voting phase, so I thought this is a good time to find out how it works with Symfony and what changes can be made to improve performance even further.

Maybe someone already did that?

**Comment by jvasseur** [comment]
The preloading RFC is about preloading class and function definitions, it can't preload variables.

We could go back to something similar to the class cache we had at some point but IMO preloading is more something that should be resolved at the composer level (composer could provide a script that preload all classes of a project) not at the Symfony level.

**Comment by kejwmen** [comment]
Yes, I thought about class cache to reduce overhead per request.

About composer, Jordi has some ideas: https://externals.io/message/103333#103335

I wanted to say we can do some benchmarks and think about possible improvements on symfony side.

I asked about existing benchmarks on symfony slack today, and got [a response from Marco](https://symfony-devs.slack.com/archives/C6PSS2YKW/p1541502192242600) - I don't know technical aspects of preloading well, but it looks like some changes can be discussed.

**Comment by nicolas-grekas** [comment]
Sure it would; see https://github.com/php/php-src/pull/3538#issuecomment-436312058 for some numbers using Symfony. I'm not sure yet what we should do in code. Having support for preloading at composer stage looks like the way to go to me also.

**Comment by jvasseur** [comment]
The only could be done IMO in Symfony (but I'm not even sure it would bring benefits) is give the possibility to revert to a single file container to allow having the full container code preloaded since included files would not be preloaded.

**Comment by stof** [comment]
@jvasseur the extra container files are not defining any class or function, and so would not benefit from preloading.

**Comment by stof** [comment]
hmm, maybe the bypass of the autoloader by using `require_once` for services of the hot path should be reverted though (unless `require_once` can deal with files required already during the preloading phase of course)

**Comment by friizer** [comment]
I tried the php-preload branch yesterday with symfony 3.4

The preload script was generated by calling an endpoint, and extracting the loaded classes, from php, so not all the classes was preloaded from vendor

After the extraction, i removed the following classes from preloading to make it work currently

 - whole cache dir
 - vendor/twig 
 - vendor/swiftmailer

There can be problems, where the code, is using  if/else constructs for different class declarations or class_exists/interface_exists checks ...

**Comment by stof** [comment]
Well, for swiftmailer, it relies on performing some special initializing when loading the library, so it indeed cannot be preloaded.

The cache should indeed not be preloaded in debug mode (you could maybe preload it in prod, where you can afford restarting PHP-FPM when you rebuild the cache (and it may still be complex to rebuild the cache in such case, so I would not advice doing it). But a preload script generated 

For Twig, maybe preloading does not handle `class_alias` properly. What was the error you were getting ?

**Comment by jvasseur** [comment]
@stof what I meant is by including extra files in the container we have to hit the opcache to get the opcodes necessary to create the service, if the code was included in the container class, the opcodes would already be preloaded with the container class.

**Comment by nicolas-grekas** [comment]
`$container->setParameter('container.dumper.inline_class_loader', false);` would do the trick.

**Comment by stof** [comment]
@jvasseur for services not part of the hot path (or for all services when disabling the `inline_class_loader` optimization), the extra files don't require anything, but rely on the autoloader. So preloading the classes should rather be done by extracting classes from the composer autoloading config.

**Comment by nicolas-grekas** [comment]
About `require_once` this should definitely be handled by the preloading logic. Something to check maybe. But we should add a flag to generate a preloading file for "container.hot_path" services (and thus skip adding `require_once` for those.)

**Comment by jvasseur** [comment]
@stof this has nothing about defining new classes.

We split the container into multiple files because it removes the cost of copying opcodes from opcache to the symbol table. With preloading this cost is removed so we could go back to the old version to remove the cost of including another file.

This is probably a really small optimization but I could be useful to do a benchmark to see if it could bring some benefits.

**Comment by friizer** [comment]
> For Twig, maybe preloading does not handle `class_alias` properly

maybe 

if i just preload  vendor/twig/twig/lib/Twig/RuntimeLoaderInterface.php which contains an additional class_alias:
class_alias('Twig_RuntimeLoaderInterface', 'Twig\RuntimeLoader\RuntimeLoaderInterface', false);

var_dump(interface_exists('\Twig_RuntimeLoaderInterface'));
var_dump(interface_exists('\Twig\RuntimeLoader\RuntimeLoaderInterface'));

bool(true)
bool(false)

I will ask dstogov, on this

**Comment by DavidBadura** [comment]
Here is the issue to implement it in composer: https://github.com/composer/composer/issues/7777

**Comment by Toflar** [comment]
Ah sorry, I missed this!

**Comment by friizer** [comment]
https://github.com/php/php-src/pull/3538#issuecomment-436577780

I think his reply means the class_alias call will not create a peristent, immutable class alias during preload

**Comment by stof** [comment]
the last comment says it should now work

**Comment by stof** [comment]
> We split the container into multiple files because it removes the cost of copying opcodes from opcache to the symbol table. With preloading this cost is removed so we could go back to the old version to remove the cost of including another file.

Preloading is not about avoiding the cost of copying opcodes. It is about avoiding the cost of copying *class and function definitions* (plus the resolving of parents, which is done at runtime when they live in separate files). So AFAIU, preloading won't change things for files not defining classes or functions.

**Comment by stof** [comment]
> We could add a flag to generate a preloading file for "container.hot_path" services (and thus skip generating `require_once` for those.)

that's an interesting idea @nicolas-grekas

**Comment by friizer** [comment]
https://github.com/php/php-src/pull/3538#issuecomment-436940722

I think class_alias calls can remain in the original files,, if include is used instead of opcache_compile_file in preload file

**Comment by nicolas-grekas** [comment]
Please check #32032, feedback and benchs appreciated.
