### ISSUE TITLE
[Form] Non Nested field names in form child

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#29122]
I am using child forms to prevent code duplication as explained here: https://symfony.com/doc/current/form/inherit_data_option.html

But this result in "nested" fields names for child forms (`foo[address]`, `foo[zipcode]`, etc...).

In a classical web application, this is not a problem because Symfony render form HTML and we don't really care about fields names.
But when using it for an API application, we want all the request parameters as the same level and not in a nested sub level.

Actually it's possible to set an empty form name on the root form only.
Why can't we make it possible on child forms too?

Maybe another way exists to add field of a form type we want to include in our form at the same level of the current form?

**Comment by xabbuh** [comment]
Supporting nested forms without being able to deal with arrays structured in the same manner would hugely increase the complexity of the form handling process. So this is probably not going to happen in the future.

For your use case there are several solutions: Using abstract base classes to define common structures for several form types (the Doctrine bridge follows a similar approach), use options to selectively enable/disable some subtypes of a form type, work with form type inheritance or maybe even form type extensions can be a solution What does work best for you depends on your concrete use case, but that's something that should be discussed on one of the [support channels](https://symfony.com/support).

**Comment by xabbuh** [comment]
I am closing here as I don't see anything happen about this in the code. Thank you for understanding.
