### ISSUE TITLE
ENV variable with cast not resolved for `framework.cache.prefix_seed`

### ISSUE THREAD

**Issue by Kowol** [symfony/symfony#29124]
**Symfony version affected:** 4.1.1

**Description:**
When trying to set a `framework.cache.prefix_seed` option by using the ENV variable with env processor:
```
framework:
    cache:
        prefix_seed: '%env(countryenv:CACHE_PREFIX)%'
```

we'll end up with following error:
```
Using a cast in "env(countryenv:CACHE_PREFIX)" is incompatible with resolution at compile time in "Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension". The logic in the extension should be moved to a compiler pass, or an env parameter with no cast should be used instead.
```

I need to use the custom env processor to perform some changes on variable key.
How can I achieve that?

**Comment by nicolas-grekas** [comment]
As the message explains, compile time cannot process variables because services are not ready yet.
And the solution provided by the message is good also: you should be able to compute this value using a compiler pass, or provide an already processes env var. Closing as this is not a bug.

**Comment by ossinkine** [comment]
@nicolas-grekas I decided to don't create a ticket, but to write here, because my issue is similar one.
The documentation says the `prefix_seed` can be useful for blue/green deployment. I want to create a new prefix for each deployment (for example based on commit hash). How can I configured cache to do this?

**Comment by chalasr** [comment]
@ossinkine Please consider using our [support platforms](https://symfony.com/support).
