### ISSUE TITLE
[WebProfiler] Messages marked as missing, when using "+intl-icu" suffix

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#29136]
**Symfony version(s) affected**: 4.2.0-BETA1

**Description**  
I've updated to 4.2-beta, and changed the translation file names with suffix "+intl-icu".
It works great!
But the WebProfiler marks all messages as missing.

![screenshot 2018-11-08 13 42 44](https://user-images.githubusercontent.com/330436/48199387-2e6a1280-e35c-11e8-977a-7dad0edb65de.png)

**Comment by nicolas-grekas** [comment]
anyone willing to give it a try?

**Comment by stof** [comment]
`trans` will handle looking in both catalogues transparently, but the LoggingTranslator and DataCollectorTranslator are relying on accessing the catalogues to check for defined keys. And so they need to be updated to account for that convention too.

**Comment by nicolas-grekas** [comment]
see fix in #29220
