### ISSUE TITLE
Homegenize exception logging between web and console

### ISSUE THREAD

**Issue by tkleinhakisa** [symfony/symfony#29138]
**Description**  
Hi, currently when an exception is thrown it is handled either by `\Symfony\Component\HttpKernel\EventListener\ExceptionListener` in a web context or `\Symfony\Component\Console\EventListener\ErrorListener` in console context.

In the web context, the logging happens depending on the exception code and type
```php
if (!$exception instanceof HttpExceptionInterface || $exception->getStatusCode() >= 500) {
    $this->logger->critical($message, array('exception' => $exception));
} else {
    $this->logger->error($message, array('exception' => $exception));
}
```

In the console context, exception are always logged as errors:
```php
$this->logger->error('Error thrown while running command "{command}". Message: "{message}"', array('error' => $error, 'command' => $inputString, 'message' => $error->getMessage()));
```

If you configure a logger to log only CRITICAL and above, the exception will be logged in the web context but not in a console context

Is there a particular reason for this difference ? do you think the console ErrorListener could be improved to have a similar behavoir like ExceptionListener ?

Thank you

**Comment by Tobion** [comment]
The reason is that Http exception is console context would be pretty strange. I can totally see that it might happen due to people throwing http exceptions even in places that are not necessarily run in http context at all. But IMO we should not explicitly support this just to make the logging more similar.

So 👎

**Comment by Tobion** [comment]
Btw, why do you not want to log error logs?

**Comment by tkleinhakisa** [comment]
Hello and thanks for the answer, i agree about http exception in console context, i am not suggesting to check for them in console ErrorListener. I was more thinking about raising the log level to critical in console but it probably has some consequences i don't measure.

I use monolog for logging and defined a stack of handlers including a mailer which i want to report only critical (errors are still logged by other handlers in files)
If a service that throws a custom exception is used in a web context i will get my email, if it is used in console context i will not

**Comment by javiereguiluz** [comment]
@nicolas-grekas do you think is there something we could do to improve this ... or should we close it as "won't change"? Thanks.

**Comment by nicolas-grekas** [comment]
No opinion here, maybe we can close because this didn't get enough traction?

**Comment by javiereguiluz** [comment]
Yes, let's close. My own opinion was :-1: but not very strong ... so let's close. Thanks.
