### ISSUE TITLE
[FrameworkBundle][PropertyAccess][Cache] Use PhpFilesAdapter instead of ApcuAdapter

### ISSUE THREAD

**Issue by PabloKowalczyk** [symfony/symfony#29143]
**Description**  

Last 4.2.0-beta release includes PR https://github.com/symfony/symfony/pull/27549. 
Currently `FrameworkExtension` tries to build `PropertyAccessor` instance with APCu Adapter ([FrameworkExtension](https://github.com/symfony/symfony/blob/736f710805b940f3b588039534368aa680cd9950/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1666) which leads to [PropertyAccessor](https://github.com/symfony/symfony/blob/736f710805b940f3b588039534368aa680cd9950/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L787)), but maybe it is a good idea to use `PhpFilesAdapter` instead of APCu? IMO users without APCu can benefit from "cached version" of `PropertyAccessor` and `PhpFilesAdapter` on prod can be even faster than `APCu`, so for me there is no cons.
Of course i can provide PR, if you think that this change is reasonable.
WDYT?

**Comment by nicolas-grekas** [comment]
I'm not sure that's possible: the `PhpFilesAdapter` requires runtime write access to a PHP file. This is not always possible (and wouldn't even be recommended). APCu looks the best to me.

**Comment by PabloKowalczyk** [comment]
Runtime write access is required by Symfony anyway on first request, so permissions to `/project/root/var/cache/` should be granted.
Maybe we can use `ApcuAdapter` as a fallback to `PhpFilesAdapter`, in case`/project/root/var/cache/` is not writable?

**Comment by nicolas-grekas** [comment]
It's not when cache has been warmed up offline using ècache:clear` and/or `cache:warmup`.
The default should work also for people that have this workflow and mount their FS as readonly (yes, that's possible.)

**Comment by nicolas-grekas** [comment]
Oh, note that #27549 has been in #28805 for this exact reason.

**Comment by PabloKowalczyk** [comment]
Some time ago i was trying to run `bin/console cache:warmup` to generate container for https://github.com/phpstan/phpstan-symfony plugin, but container xml file was missing.
So, `ChainAdapter` is not an option?

**Comment by nicolas-grekas** [comment]
It would need a good enough reason. Being compatible by default with read-only fs looks more desirable to me than a minor perf gain (or maybe you have numbers showing it's not minor?)

**Comment by PabloKowalczyk** [comment]
I do not have numbers now but i can do some benchmarks tomorrow.

**Comment by nicolas-grekas** [comment]
Thanks for the numbers!
Closing then.
