### ISSUE TITLE
[RFC][Messenger] Buffered Message Bus Implementation Considerations

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#29157]
## Intro
First of all let me start by saying I'm creating this issue as a followup of https://github.com/symfony/symfony/pull/28983

## Background
Currently in our application we batch-process large sets of records. Some of the operations (e.g. geocoding or creation of thumbnails) are very resource-intensive and slow but not crucial for the application functionality. For these reasons every time we process a record we dispatch various messages handled by separate servers which execute these slow operations asynchronously.

However, there is a catch - none of the operations can be executed before records land in a database. We dispatch messages with IDs of entities, so that they are small and each worker fetches the records and processes it further. In order to make speed up the processing we flush data into database in chunks. This causes a problem where message is dispatched into a queue and entity is still sitting in memory waiting to be `flush()`-ed.

## Solution
The solution we developed was very simple - `BufferedMessageBus`. How it works it simply composes real bus and stores all messages passed on `dispatch()` in memory cache. It adds additional `flush()` which when called does `RealBus::dispatch()` on every message.

## BC consequence
Currently the return signature of `dispatch()` was changed from `void` to `Envelope`. This really does not allow buffering of messages, since they are not immediately processed by middlewares.

I cannot think about any sensible implementation of delayed-dispatch pattern here if `dispatch()` is to return `Envelope`.

1. Am I doing something horribly wrong?
2. Maybe the returned `Envelope` should be optional?
3. Any thoughts?

ping @nicolas-grekas @sroze

**Comment by nicolas-grekas** [comment]
I don't understand the conflict: what prevents you from returning the passed Envelope and be done with it?

**Comment by Tobion** [comment]
I also don't see why returning Envelope should not allow you to do the same buffering as before.

**Comment by sroze** [comment]
@kiler129 did these answer make sense to you? I agree with @nicolas-grekas & @Tobion, this has nothing to do with the return value indeed.

Also, my 5cts regarding your use-case would be to say that you should write your own middleware for this, not another implementation of the message bus.

**Comment by aurelijusrozenas** [comment]
@kiler129 long time, I know, but did you manage to implement middleware or did you go any other way with your implementation? We also need to send messages only after doctrine flush.

**Comment by ogizanagi** [comment]
@aurelijusrozenas : Would the [DispatchAfterCurrentBusMiddleware](https://symfony.com/doc/current/messenger/message-recorder.html) solve your use-case?

Messages dispatched with the `DispatchAfterCurrentBusStamp` stamp inside an handler would only be sent after the Doctrine middleware flushed the changes for this handler.

**Comment by aphex008** [comment]
@kiler129 @ogizanagi DispatchAftercurrentBusMiddleware would not help here because intension is to send messages to queue only after sending side has finished transaction. Problem is that flush in controller is not performed yet but handler has already started processing. And AFAIK DispatchAftercurrentBusMiddleware takes place on handling side and it does not know if sending side has finished flushing. Or am I wrong?
