### ISSUE TITLE
[WebServerBundle] Store pid file in project directory instead

### ISSUE THREAD

**Issue by nclavaud** [symfony/symfony#29160]
### Description

Commit 6f689d65979866659ff78a6ad25e36c105abadee introduced a pid file to keep track of the servers that have been started using command `server:start`. As stated in the pull request description:
> the web server now stores its address in a pid file stored in the current directory

The _current directory_ is the directory where the shell command was launched, and not necessarily the project directory. This can lead to wrong reports if the same command is run twice from different directories, or if different servers (from different apps) are started from the same directory.

For these reasons, I suggest using the project directory instead.

#### Before
```sh
php bin/console server:start  // [OK] Server listening on http://127.0.0.1:8000

cd bin
php console server:start      // [OK] Server listening on http://127.0.0.1:8001
```

#### After
```
php bin/console server:start  // [OK] Server listening on http://127.0.0.1:8000

cd bin
php console server:start      // [ERROR] The web server is already running (listening on http://127.0.0.1:8000).
```

#### Before
```
php /var/www/app1/bin/console server:start  // [OK] Server listening on http://127.0.0.1:8000
php /var/www/app2/bin/console server:start  // [ERROR] The web server is already running (listening on http://127.0.0.1:8000).
```

#### After
```sh
php /var/www/app1/bin/console server:start  // [OK] Server listening on http://127.0.0.1:8000
php /var/www/app2/bin/console server:start  // [OK] Server listening on http://127.0.0.1:8001
```

What do you think?

**Comment by ro0NL** [comment]
note you can use the `--pidfile` option. Not sure injecting the project dir etc. is worth it.

See https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php#L59

**Comment by nclavaud** [comment]
> note you can specify the `--pidfile` option

I know, but still, I think the default makes little sense. Bad DX to me.

**Comment by nicolas-grekas** [comment]
can't we store it in the cache dir?

**Comment by nclavaud** [comment]
> can't we store it in the cache dir?

I'm not sure we want the pid file to be deleted when running `cache:clear`, do we? The server will keep running after the cache has been wiped, but we would loose track of it.

This pid file holds server state, and in the linux philosophy this would belong to directory [`/run`](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html), I guess, but there is no such `run/` or `var/run/` directory in Symfony's default directory structure.

Any objection to use the project directory as the default pid file location?

**Comment by nicolas-grekas** [comment]
The cache dir is not deleted on cache:clear
My suggestion is to store the pid in var/cache/something.pid - not in var/cache/dev/something.pid

**Comment by nclavaud** [comment]
Would be fine, then!
Will open a PR. :-)

**Comment by gido** [comment]
I picked this issue when working during the #SymfonyConHackday2018 in Lisbon and I'm not sure if using the the root cache directory (`var/cache` and no `var/cache/dev` is ideal because you need to make a lot of assumption on how the cache directory structured.

The naive implementation could be just: `dirname($cacheDir)`  but you can put what you want into `Kernel::getCacheDir()`. This could lead to more issues that is solve.

Using the project directory (`%kernel.project_dir%`) to solve this looks just fine for me but maybe I miss something?

**Comment by Simperfit** [comment]
@nclavaud or @gido are you still working on this, do you want some help, if so could you please open a PR to see what needs to be done or if everything is OK.
Thanks :).
