### ISSUE TITLE
AnnotationReader conflict with Carbon external library

### ISSUE THREAD

**Issue by Cethy** [symfony/symfony#29161]
**Symfony version(s) affected**: 4.1.7

**Description**  
The [Carbon library](https://github.com/briannesbitt/Carbon/) contains some `@alias` annotations in the code (used by their documentation generator). When extending Carbon in a symfony app class,  I got an exception :
```
In AnnotationException.php line 54:

  [Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@alias" in method Carbon\CarbonImmutable::toDate() was never imported. Did you maybe forget to add a "use" statement fo
  r this annotation?
```

**How to reproduce**  
- vanilla symfony installation ;
- `composer require nesbot/carbon`
- add a class where it will parsed for routing (in my case) :
```php
use Carbon\CarbonImmutable;
class Foo extends CarbonImmutable{}
```

**Possible Solution**  
Found a way to [globally ignore an annotation](https://stackoverflow.com/a/50719075/2572988), but it feels too hacky for me :
```php
<?php
namespace App;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
class Kernel extends BaseKernel
{
    // ...
    protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
    {
        AnnotationReader::addGlobalIgnoredName('alias');
        // ...
    }
}
```
Is there a way to tell elegantly to the `annotation.reader` service to `addGlobalIgnoredName('alias)` ?

**Comment by Cethy** [comment]
@kylekatarnls This usage w/ `Carbon` is just really an example, the problem could arise from other sources.
I'm looking for a more general/permanent way to fix it.

**Comment by kylekatarnls** [comment]
If you doesn't need controller annotations, then then open **config/routes/annotations.yaml** and remove the `controllers` entry and its properties. Then you will be able to create any classes with annotations ignored inside Controller directory.

Still having such stuff inside a controller reminds a bad architecture you should avoid in my humble opinion.

**Comment by Cethy** [comment]
@kylekatarnls The solution you propose is "puting the problem under the rug" (hiding behind configuration convention), not useful to me.
@iltar As of the last lines of my issue suggest, I am aware of this doctrine documentation, **I'm looking to use it correctly in symfony**.

**Comment by nicolas-grekas** [comment]
Calling `AnnotationReader::addGlobalIgnoredName()` is the way to go. This method is a global static one, the hacky feeling you have might be legit: changing global state triggers this code smell to me also. But that's the way it is - unrelated to Symfony btw. (AFAIK, the Doctrine team is working on an improved annotation parser which might improve this.)

**Comment by Cethy** [comment]
@nicolas-grekas Thx a lot for the confirmation.
