### ISSUE TITLE
Encore - semantic-ui issue

### ISSUE THREAD

**Issue by Falseee** [symfony/symfony#29173]
Hello,

first of all i know normaly support questions are not allowed here.
But i already asked irc and Slack but there are to less users (so i got no answer)...
The issues are made for that, so why dont use it ?

I have the following webpack config
```
var Encore = require('@symfony/webpack-encore');

Encore
   .setOutputPath('public/build/')
   .setPublicPath('/build')

   .addEntry('app', [
       './assets/js/app.js',
       './node_modules/jquery/dist/jquery.min.js',
       './node_modules/semantic-ui/dist/semantic.min.js'
   ])
   .addEntry('login', './assets/js/login.js')
   .addEntry('html5shiv', './node_modules/html5shiv/dist/html5shiv.min.js')
   .addEntry('respond.js', './node_modules/respond.js/dest/respond.min.js')
   .disableSingleRuntimeChunk()

   .cleanupOutputBeforeBuild()
   .enableBuildNotifications()
   .enableSourceMaps(!Encore.isProduction())
   .enableVersioning(Encore.isProduction())

   .autoProvidejQuery({
       $: 'jquery',
       jQuery: 'jquery',
       'window.jQuery': 'jquery',
   })
;

module.exports = Encore.getWebpackConfig();
```
On the login page i include the app(.js) and login(.js) (from the build path).
My login.js looks like this
```
require('../css/login.css');

$(function () {
   $('.ui.form').form({
       fields: {
           username : 'empty',
           password : 'empty',
       }
   });
});
```
But i always get the error `$(...).form is not a function` (the form function is from the semantic-ui framework).
If i run the code manually its works fine.. where is the problem ?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
