### ISSUE TITLE
[WebProfiler] Error: Call to a member function getClientOriginalName() on null

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#29178]
**Symfony version(s) affected**: 4.2.0-beta1

**Description**  
In a form with an optional file input, when not sending a file, I get this Error:

> Call to a member function getClientOriginalName() on null

![screenshot 2018-11-11 13 36 58](https://user-images.githubusercontent.com/330436/48313042-47bacb00-e5b7-11e8-931f-a47137120730.png)

**Additional context**  
I think this error was introduced by https://github.com/symfony/symfony/pull/26946, ping @javiereguiluz

**Comment by ro0NL** [comment]
See #29183 

i wasnt able to reproduce `Call to a member function getClientOriginalName() on null`

Can you share your form settings?

**Comment by gharlan** [comment]
@ro0NL For me the error is reproducible with this change in symfony-demo:
https://github.com/gharlan/symfony-demo/commit/5ee255e5440e17a12b372783f5accc19a64937dd

![screenshot 2018-11-12 11 07 33](https://user-images.githubusercontent.com/330436/48340558-2e735680-e66b-11e8-8698-aeb9001b0d48.png)

**Comment by ro0NL** [comment]
Hm can you confirm #29183 fixes it..

**Comment by gharlan** [comment]
@ro0NL No, it does not fix my issue, the error still occurs.

`dump($request->files->all())` returns:

![screenshot 2018-11-12 12 47 22](https://user-images.githubusercontent.com/330436/48345743-29b59f00-e679-11e8-8c2a-0b02909a8cd7.png)

**Comment by ro0NL** [comment]
Bingo. It happens for a nested form.

**Comment by arbaazmulla13** [comment]
In your form tag  use
" enctype="multipart/form-data"  "
<form method='post' enctype="multipart/form-data">
