### ISSUE TITLE
php bin/console make:user use "json" as type for roles

### ISSUE THREAD

**Issue by Falseee** [symfony/symfony#29177]
**Symfony version(s) affected**: 4.1.7

**Description**  
If i declare the mysql version to 5.5.60 in the doctrine.yaml and run `php bin/console make:user` the roles will generated like
```
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
```
The Problem is that on that mysql version json as type not exists.

**How to reproduce**  
Just do the steps above

**Possible Solution**  
If the mysql version is smaller then the version since json exists as type use array or something else.

**Comment by dmaicher** [comment]
Doctrine column type "json" will work perfectly fine even on MySQL 5.5. Doctrine will handle json en/decoding the values and use type "text" internally.

**Comment by Falseee** [comment]
> Doctrine column type "json" will work perfectly fine even on MySQL 5.5. Doctrine will handle json en/decoding the values and use type "text" internally.

Okay then the problem is the `php bin/console make:migration` because its try to create a attribute with the type json in the database.

**Comment by Falseee** [comment]
> I guess you miss configured your server version in doctrine.yaml file

The first sentence of issue description starts with `If i declare the mysql version to 5.5.60 in the doctrine.yaml`...
So no i didnt miss configured it :o

**Comment by chalasr** [comment]
This should either be discussed on https://github.com/symfony/maker-bundle or doctrine migrations (since `make:migration` just calls `doctrine:migrations:diff` internally).

**Comment by xabbuh** [comment]
I am closing here as this is not something that needs to be changed in Symfony core as explained.
