### ISSUE TITLE
[RFC][Dotenv] Introduce DOTENV_OVERLOAD

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29170]
**Description**  
Now .env is the new .env.dist, im kinda stuck with local infrastructure.

The setup auto-detects .env and creates real envs as such in the container being spinned up. This totally breaks things as .env.local is not being loaded at this point.

To keep things simple (i cant really control this yet - https://github.com/lando/lando/issues/994) it would be nice to control overloading for now with a new `DOTENV_OVERLOAD=1` var.

It would be auto-detected in `Dotenv::loadEnv()` and toggles `load()` vs `overload()` as such.

Thoughts?

**Comment by nicolas-grekas** [comment]
Another idea: load .env.dist when .env is not found, in loadEnv(). Would it make sense?

**Comment by ro0NL** [comment]
hm :thinking: i need .env.local to be loaded :)

Currently flex still generates both .env and .env.dist with the same contents, and AFAIK for the same purpose - to be committed in VCS.

Im still stuck with the vars from .env being loaded as real envs / pre-bootstrap.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/29171 for an alternative. I think it solves the issue without introducing radically new idiomatism.

**Comment by ro0NL** [comment]
got ya, it would work yes. I simply remove .env then

is there some Flex WIP going on still? Or will it always generate both now *the same*, for the user to decide what to keep and what not.
