### ISSUE TITLE
DebugClassLoader : The file was found but the class was not in it

### ISSUE THREAD

**Issue by xsuntel** [symfony/symfony#29198]
**Symfony version(s) affected**: 4.1.7

**Description**  

I have a problem when I input a command

    $ php ./bin/console cache:clear

    In DebugClassLoader.php line 200:
                                                                                                                                                                               
        The autoloader expected class "Symfony\Bundle\WebProfilerBundle\WebProfilerBundle" to be defined in file "/var/www/???/vendor/composer/../symfony/web-profiler-bundle/WebProfilerBundle.php". The file was found but the class was not in it, the class name or namespace probably has a typo.                                                       
                                                                                                                              

**How to reproduce**  

    $ php ./bin/console cache:clear

**Additional context**  

file : [/vendor/symfony/debug/DebugClassLoader.php](https://github.com/symfony/symfony/blob/6eb5f93918d833954ca87c21900c5831e424f9a9/src/Symfony/Component/Debug/DebugClassLoader.php#L200)

file : composer.json

    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        ~
        "symfony/flex": "^1.0",                      // v1.1.7
        "symfony/web-profiler-bundle": "^4.1",       // v4.1.7
    },
    "require-dev": {
        ~
        "symfony/debug-bundle": "^4.0",              // v4.1.7
        "symfony/maker-bundle": "^1.9",
    },

Could you please give me an advice?

**Comment by ro0NL** [comment]
Did you try re-installing the dependencies?

Looking at https://github.com/symfony/web-profiler-bundle/blob/v4.1.7/WebProfilerBundle.php the should be defined :)

**Comment by xsuntel** [comment]
Thank you for your information. :)

I removed a directory and installed packages again 

    $ rm -Rf ./vendor/*

    $ composer install

Then I have just confirmed that It is normal
