### ISSUE TITLE
Optional select is coming with default value (the first choice)

### ISSUE THREAD

**Issue by wernovox** [symfony/symfony#29195]
I am adding a `select` field to my `Form`. This `select` is optional (not required) but it is coming with the first choice as the default option; however, I want it to come with empty or null value.

Am I doing it wrong?

```php
[
                'label' => $extraField->getName(),
                'choices' => $choices,
                'multiple' => false,
                'required' => false,
                'attr' => [
                    'class' => 'form-control chosen-select',
                    'data-component' => 'ComboboxSimple'
                ]
]
```

**Comment by yceruto** [comment]
The default behavior should displays an empty option `<option value="">` unless you're overriding the `{%- block choice_widget_collapsed -%}`. Is that the case?

**Comment by wernovox** [comment]
Hi @yceruto, thanks for fast answer. No, that is not the case, I am not overriding the `choice_widget_collapsed`.

**Comment by xabbuh** [comment]
@wernovox Can you create a small example application that allows to reproduce your issue?

**Comment by wernovox** [comment]
@xabbuh unfortunately I can't afford time to do that now, I apologize.

**Comment by xabbuh** [comment]
Okay, let's close for now then as we can't do anything about it without being able to reproduce. But we can of course reopen when we have a reproducible example.
