### ISSUE TITLE
[WebProfilerBundle] Incomplete dark themed components

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29194]
**Symfony version(s) affected**: 4.2

![image](https://user-images.githubusercontent.com/1047696/48366829-440a6f80-e6af-11e8-8ee6-3a1d0caaa612.png)

the active menu and toggles icon are a bit incompatible still.

**Comment by ro0NL** [comment]
Twig

![image](https://user-images.githubusercontent.com/1047696/48366951-9e0b3500-e6af-11e8-95ca-20134fb94884.png)

**Comment by ro0NL** [comment]
More problematic perhaps; Exception

![image](https://user-images.githubusercontent.com/1047696/48367078-ec203880-e6af-11e8-9d99-4bb797b8fb40.png)

**Comment by ro0NL** [comment]
Validator

![image](https://user-images.githubusercontent.com/1047696/48369798-d1ea5880-e6b7-11e8-869e-b7438a54517c.png)

**Comment by ro0NL** [comment]
Logs (i think the borders are off)

![image](https://user-images.githubusercontent.com/1047696/48369939-34435900-e6b8-11e8-95ba-101951e74fc0.png)

**Comment by ro0NL** [comment]
Time

![image](https://user-images.githubusercontent.com/1047696/48978786-72297f80-f0b1-11e8-9086-761995f2f3e7.png)

**Comment by ro0NL** [comment]
Debug

![image](https://user-images.githubusercontent.com/1047696/49433065-61fc5900-f7b1-11e8-947f-ea152ec5a449.png)

**Comment by lmlsna** [comment]
Also the `.word` and `.symbol` classes in use on the Doctrine tab are set to `#222` even when the `.theme-dark` is applied.
