### ISSUE TITLE
Dotenv doesn't unescape backslashes

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#29202]
Found in Symfony 4.2 but should exist in 3.4

When parsing a `.env` file containing `FOO=A\\B`, dotenv loads it as `A\\B`.
But it should remove one slash instead, and load value `A\B` (same as what the shell does when reading the same value).

**Comment by nicolas-grekas** [comment]
That's quite possible. Can you find the link please?

**Comment by nicolas-grekas** [comment]
Do you have a link?

**Comment by Taluu** [comment]
Here goes, but as I said, it's unrelated : #27594

**Comment by xabbuh** [comment]
see #29222
