### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by mwanglur** [symfony/symfony#29214]
https://github.com/symfony/translation/blob/master/Tests/fixtures/malformed.json

**Comment by xabbuh** [comment]
no bug

**Comment by xabbuh** [comment]
Based on your description I can only guess what you feel is a bug here, but as you can see from the filename this is a malformed JSON file which is used as a test fixtures file.

**Comment by dbrumann** [comment]
This json is intentionally malformed as it is used for testing how the loader will react to this kind of broken input. If you search for the usage in the tests it will probably become clearer.
