### ISSUE TITLE
[RFC] Allow different location for bundle assets

### ISSUE THREAD

**Issue by garak** [symfony/symfony#29213]
**Description**  
The [current behavior](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php#L136) for assets in bundles is looking for an hard-coded path named `Resources/public/` in bundle's path.
So, when developing a bundle, you're forced to use the "typical" directory structure, like the following example:
```
DependencyInjection/
FooBundle.php
Resources/ (with public, docs, etc.)
Tests/
```
It would be nice to allow to structure your bundle with a more modern (and more standard), like this:

```
assets
docs
src
templates
tests 
```
With the hard-coded path mentioned above, this is not possible, unless you symlink `src/Resources` to `asset` directory.

I found a similar RFC in #11051 but this is far simpler, since it only involves public paths for bundles.
Also, a solution would be much simpler and not BC-breaking (I guess that adding a new method to `Bundle` class would be enough)

**Comment by ro0NL** [comment]
`PublishingBundleInterface::getPublicPath(): string` could work :)

**Comment by yceruto** [comment]
I'd like to see a new structure for bundles too, but a bundle must be able to support several versions of Symfony. So, it must work with `Resources/public/` AND `assets/`, not one or the other. The clever solution should found an easy upgrade path.
