### ISSUE TITLE
Symfony\Bundle\FrameworkBundle\Test\WebTestCase class not found

### ISSUE THREAD

**Issue by tomaszturkowski** [symfony/symfony#29215]
I created fresh Symfony 4.1.x project, but when I'm trying to create and execute functional test I am getting error:

> PHP Fatal error:  Class
> 'Symfony\Bundle\FrameworkBundle\Test\WebTestCase' not found in
> /home/tomasz/my_project/tests/ExampleControllerTest.php on line 7

Steps to reproduce:

 1. Create project

    `composer create-project symfony/skeleton my_project`

 2. Install phpunit, functional tests components and maker for generating skeleton of functional test

    `composer req --dev symfony/phpunit-bridge symfony/css-selector symfony/browser-kit symfony/maker-bundle` 

 3. Create example functional test

    `bin/console make:functional-test ExampleControllerTest`

Content of created file:

    <?php
    
    namespace App\Tests;
    
    use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
    
    class ExampleControllerTest extends WebTestCase
    {
        public function testSomething()
        {
            $client = static::createClient();
            $crawler = $client->request('GET', '/');
    
            $this->assertSame(200, $client->getResponse()->getStatusCode());
            $this->assertContains('Hello World', $crawler->filter('h1')->text());
        }
    }

4. Run tests

    `bin/phpunit`

Output (after installing phpunit dependencies):

> PHP Fatal error:  Class
> 'Symfony\Bundle\FrameworkBundle\Test\WebTestCase' not found in
> /home/tomasz/my_project/tests/ExampleControllerTest.php on line 7

I checked and class `Symfony\Bundle\FrameworkBundle\Test\WebTestCase` does exist in `vendor/`. Any clues?

phpunit.xml.dist: https://pastebin.com/MYjgpFbA
composer.json: https://pastebin.com/WQaYFBq1
composer.lock: https://pastebin.com/pwRsmnY8
PHP Version: 7.2.12

**Comment by mmarton** [comment]
Either composer doesn't find the class or phpunit doesn't use phpunit.xml.dist.  
try running `composer dump-autoload` and/or `phpunit -c phpunit.xml.xsd`

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
I have no idea yet what is causing this issue, but I can confirm it.

**Comment by xabbuh** [comment]
seems to be caused by symfony/recipes#481

**Comment by nicolas-grekas** [comment]
Does symfony/recipes#491 fix it?

**Comment by khal3d** [comment]
@nicolas-grekas I'm not sure how to test the recipe, but changing the code of `bin/phpunit` in my project and removing the following lines like what you did solved the issue:

```
$classLoader = require dirname(__DIR__).'/vendor/autoload.php';
App\Kernel::bootstrapEnv('test');
$classLoader->unregister();
```
So, I think it does fix the issue.

**Comment by nicolas-grekas** [comment]
Thanks for the feedback.

**Comment by hsb1007** [comment]
Even after removing the 3 lines, it still doesn't solve the issue for me =(

**Comment by nicolas-grekas** [comment]
I don't have the issue when starting a new project from scratch.
You should compare your files with those of a new project and spot the diff.

**Comment by bilougit** [comment]
I had the same issue with a new project from scratch. However, I could get through it thanks to the answer below.

> @nicolas-grekas I'm not sure how to test the recipe, but changing the code of `bin/phpunit` in my project and removing the following lines like what you did solved the issue:
> 
> ```
> $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
> App\Kernel::bootstrapEnv('test');
> $classLoader->unregister();
> ```
> So, I think it does fix the issue.

**Comment by saminet** [comment]
In your class under tests folder, just replace this line
use Symfony\Bundle\FrameworkBundle\Tests\TestCase;
By this
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
And it will work fine
