### ISSUE TITLE
[Form] Move symfony/intl to require-dev

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29229]
In #28610 we've added exceptions to give better error messages in case one uses a form type that relies on symfony/intl. The problem is this can never happen, as sf/intl is a hard requirement per composer.json

https://github.com/symfony/symfony/blob/dbf053bc854f6768ddcd8ed39f7cbb2c21e500e6/src/Symfony/Component/Form/composer.json#L18-L21

This compared to the Validator component, where it's a soft requirement.

Is there any hassle-free approach for 4.x or 5.0 here? (in an effort to move it to require-dev instead).

**Comment by xabbuh** [comment]
I am not sure if we can possibly detect this case. We would need to determine whether `symfony/intl` is installed because the Form component required it or because another package added a requirement for it.

**Comment by ro0NL** [comment]
maybe it can be added as a default dep in the FW recipe? So at least the user is able to control it and remove if necessary.

**Comment by chalasr** [comment]
Suddenly removing the dependency would break at runtime. Given form is the only component having `intl` has an hard requirement, it's likely to happen. 
See #29720 for removing the availability checks. Nothing we can do here IMHO

**Comment by javiereguiluz** [comment]
Let's close this because of the reasons given by Robin (and the concerns expressed by Christian). Thanks.

**Comment by ro0NL** [comment]
@chalasr @xabbuh any thoughts on re-opening for 6.0? 

https://github.com/symfony/website-skeleton/pull/133 is merged on May 2019, wel'll release SF6 in Nov 2021

doing the math; new projects will have symfony/intl by default for 2,5 years :)
