### ISSUE TITLE
Encoding problem when I use Finder component on Windows File System

### ISSUE THREAD

**Issue by gcrispyn** [symfony/symfony#29227]
**Symfony version(s) affected**: 3.4.18
**Description**  
When I use Symfony Finder component on a Windows system to find a folder, I have a problem with the SplFileInfo Output.

The component find the folder with success but when I want to reuse the pathname of the SplFileInfo object to copy file into this folder, it doesn't work because folders with accents are completely broken.

Can you help me please ?

**Comment by gcrispyn** [comment]
Thank you for your answer ! 

My PHP version is 7.2.7... :(

**Comment by ro0NL** [comment]
> it doesn't work because folders with accents are completely broken

some context would be nice, what does the code look like? What does the path look like?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
