### ISSUE TITLE
Cannot execute a Symfony command after installing Symfony 4.2-dev

### ISSUE THREAD

**Issue by jlslew** [symfony/symfony#29221]
**Symfony version(s) affected**: 4.2-dev

**Description**  

> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 255
> !!  PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Bundle\FrameworkBundle\Console\Application::bootstrapEnv() in /home/user/www/symfony/src/Kernel.php:64
> !!  Stack trace:
> !!  #0 /home/user/www/symfony/bin/console(16): App\Kernel::bootstrapCli(Array)
> !!  #1 {main}
> !!    thrown in /home/user/www/symfony/src/Kernel.php on line 64
> !!  
> Script @auto-scripts was called via post-update-cmd

**How to reproduce**  
- `composer create-project symfony/website-skeleton test -s dev`
- `php bin/console`

**Additional context**  
related to PR #29197

**Comment by nicolas-grekas** [comment]
that's going to be fixed at the recipe level, see https://github.com/symfony/recipes/pull/491

**Comment by nicolas-grekas** [comment]
@symfony/deciders that's why we need symfony/recipes#491 ;)
