### ISSUE TITLE
NotNormalizableValueException should note which attribute failed to denormalize

### ISSUE THREAD

**Issue by tezvi** [symfony/symfony#29230]
Hello Symfony world!

I'm experiencing challenges debugging Symfony deserializer and I've particularly noticed this line of code:

> vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:263
>...
> throw new NotNormalizableValueException($e->getMessage(), $e->getCode(), $e);

It would be helpful if this exception contained reference to an attribute that failed to denormalize, either in message text or as NotNormalizableValueException property.

The current exception message is a bit vague and not really friendly when you try to deserialize rather complex objects and bug hunt the failing parts.

> Uncaught PHP Exception Symfony\Component\Serializer\Exception\NotNormalizableValueException: "Expected argument of type "string", "NULL" given." at ***/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php line 264

Perhaps someone can give me a hint if I'm doing something wrong or I should change the approach somehow?

Using Symfony 4.1.6

**Comment by tezvi** [comment]
It seems this is already handled properly when validating property type (v4.2.1)
https://github.com/symfony/symfony/blob/db6784bb095de2c6ef0ab424efd5b06e71e3feef/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L375

This could be reused somehow here: https://github.com/symfony/symfony/blob/db6784bb095de2c6ef0ab424efd5b06e71e3feef/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L281

**Comment by Simperfit** [comment]
We discussed that with @stof at the Hackathon, I think this is handy feature and it will close multiple issues.

I'm going to take this ;).

**Comment by tezvi** [comment]
Nice! That will come handy :)
