### ISSUE TITLE
Container aware migrations and private services

### ISSUE THREAD

**Issue by onEXHovia** [symfony/symfony#29238]
In some migrations need access to the container to ensure the proper update of data structure. 
In documentation [DoctrineMigrationsBundle](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#container-aware-migrations) there is a separate section describing this case, but default all services have private access and for migration give public access, this seems strange to me.

@nicolas-grekas implement [PR](https://github.com/symfony/symfony/pull/26499) which the allow fetching private services from test clients. Is it possible used in migrations and whether it is good practice?

Thanks!

**Comment by nicolas-grekas** [comment]
I confirm: migrations are just code snippets with very basic context (DB access). If you need services, you should write a command.
