### ISSUE TITLE
TwigBundle getAndCleanOutputBuffering can't extract  data from php buffer

### ISSUE THREAD

**Issue by mengzhisuoliu** [symfony/symfony#29244]
**Symfony version(s) affected**: x.y.z

**Description**  

\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Controller\ExceptionController.php

Hi, everyone, I want to pass data to use in the showAction method, becasue it will get data from php buffer,

```php
$currentContent = $this->getAndCleanOutputBuffering($request->headers->get('X-Php-Ob-Level', -1));
```

but,

```
\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php

public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)
 {
        $request->headers->set('X-Php-Ob-Level', ob_get_level()); 这里设置当前的ob 值
```

so ...,it can't extract the data by TwigBundle

**Comment by xabbuh** [comment]
I am actually not sure what you are trying to achieve. Can you explain the problem your try to solve in more details?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
