### ISSUE TITLE
`symfony/[website-]skeleton` aren't tagged to beta2

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#29242]
**Symfony version(s) affected**: 4.2.0-beta2

**How to reproduce**  
```
$ composer create-project symfony/skeleton . "4.2.*" -s beta
```

**Comment by nicolas-grekas** [comment]
we don't tag skeletons as beta.
Instead, you should use `composer create-project symfony/skeleton -s dev`
That way you won't experience bugs that have been fixed meanwhile.

**Comment by maidmaid** [comment]
Thanks for your answer. But according to the doc, it should work.
https://symfony.com/doc/current/setup/unstable_versions.html#creating-a-new-project-based-on-an-unstable-symfony-version

**Comment by nicolas-grekas** [comment]
it's a doc issue then!

**Comment by maidmaid** [comment]
Just for my information, could you explain to me why you don't tag the skeleton as beta ? It simply looks like one more easy step in your release process. I probably miss something.

**Comment by nicolas-grekas** [comment]
There are so many simple and easy things that just are not...
It's technical doable, but for a very limited usefulness, and a certain waste of time of maintainers. On behalf of them, me included, thanks for your understanding ;)
