### ISSUE TITLE
No output when we run bin/console in test env

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#29241]
**Symfony version(s) affected**: 4.2.0-beta2

**How to reproduce**  

```
$ APP_ENV=test bin/console
```

**Comment by j4nr6n** [comment]
I'm not able to reproduce the issue. If you run a command such as `APP_ENV=test bin/console about`, do you get any output? What about when you run your command in other environments (e.g. `APP_ENV=prod bin/console`)?

**Comment by Tobion** [comment]
It's probably because you have https://github.com/symfony/recipes/blob/86e2b6795c455f026e5ab0cba2aff2c7a18511f7/symfony/phpunit-bridge/4.1/.env.test#L4 which is equivalent to `bin/console -q`

**Comment by maidmaid** [comment]
What's the reason of this strange line ?

**Comment by maidmaid** [comment]
The reproducer:
```
$ composer create-project symfony/website-skeleton . -s dev
$ APP_ENV=test bin/console
```

**Comment by nicolas-grekas** [comment]
Let's move the line in phpunit.xml.dist files!

**Comment by maidmaid** [comment]
What's the purpose of `SHELL_VERBOSITY=-1` ? It looks weird.

**Comment by xabbuh** [comment]
This env var can be used to control the logger shipped with the HttpKernel component (see also #24425).
