### ISSUE TITLE
[DI] Maximum function nesting level of '9999' reached

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29246]
**Symfony version(s) affected**: 4.2

**Description**  
After #29078 there seems to be another regression now.

```
In getDoctrine_Orm_DefaultEntityManagerService.php line 9:
                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError
  Maximum function nesting level of '9999' reached, aborting!
```

**How to reproduce**  
See https://github.com/ro0NL/sf

Run `php -dxdebug.max_nesting_level=9999 bin/console c:c -vvv`

**Comment by nicolas-grekas** [comment]
See #29247 - no easy fix.
TL;DR, requiring `symfony/proxy-manager-bridge` works around the issue properly.

**Comment by xabbuh** [comment]
#25821 could be related too
