### ISSUE TITLE
[DoctrineBridge] Custom EntityRepository as service breaks EntityUserProvider

### ISSUE THREAD

**Issue by lrlopez** [symfony/symfony#29257]
**Description**  

After reading [this post by Thomas Votruba](https://www.tomasvotruba.cz/blog/2017/10/16/how-to-use-repository-with-doctrine-as-service-in-symfony/) about migrating Doctrine entity repositories into services in order to use them with DI, I started to apply it into a Symfony 3.4 project I'm working on.

Everything looked ok (it should really be considered as a best practice because the code is much cleaner) until I stumbled in a roadblock with the guard authentication. It seems that `EntityUserProvider` uses the Doctrine locator in order to find `EntityRepository` related to the User entity, but the `repositoryClass` parameter must be removed in order to avoid circular references. This implies that Doctrine locator doesn't work anymore (it just returns a generic `EntityRepository`) and `EntityUserProvider` fails because the generic class doesn't implement the `UserLoaderInterface` interface (even though the custom repository does).

So, I suggest adding a new config option to the `entity` user provider in `security.yml` called `repository` that can be stated to point to the right repository class. 

So I propose to change:
```php
    // src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php
    /**
     * {@inheritdoc}
     */
    public function loadUserByUsername($username)
    {
        $repository = $this->getRepository();
        if (null !== $this->property) {
            $user = $repository->findOneBy(array($this->property => $username));
        } else {
            if (!$repository instanceof UserLoaderInterface) {
                throw new \InvalidArgumentException(sprintf('You must either make the "%s" entity Doctrine Repository ("%s") implement "Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface" or set the "property" option in the corresponding entity provider configuration.', $this->classOrAlias, \get_class($repository)));
            }

            $user = $repository->loadUserByUsername($username);
        }

        if (null === $user) {
            throw new UsernameNotFoundException(sprintf('User "%s" not found.', $username));
        }

        return $user;
    }
```
to something similar to: 
```php
/**
     * {@inheritdoc}
     */
    public function loadUserByUsername($username)
    {
        if (null !== $this->repository) {
            $repository = $this->repository;
        } else {
            $repository = $this->getRepository();
        }
        if (null !== $this->property) {
            $user = $repository->findOneBy(array($this->property => $username));
        } else {
            if (!$repository instanceof UserLoaderInterface) {
                throw new \InvalidArgumentException(sprintf('You must either make the "%s" entity Doctrine Repository ("%s") implement "Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface", set "repository" to a custom repository that implements that interface, or set the "property" option,  in the corresponding entity provider configuration.', $this->classOrAlias, \get_class($repository)));
            }

            $user = $repository->loadUserByUsername($username);
        }

        if (null === $user) {
            throw new UsernameNotFoundException(sprintf('User "%s" not found.', $username));
        }

        return $user;
    }
```
And then allow the entity provider configuration to host the new "repository" option.

What do you think?

**Example**  
```yaml
    # config/packages/security.yaml
    # ...

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                repository: App\Repository\UserRepository
    # ...
```

Should it be backported to Symfony 3.4 I would make the PR myself in order to fix this annoying problem.

NOTE: I've submitted this as a bug report because it breaks a expected behavior with custom entity providers as services.

**Comment by Tobion** [comment]
Please provide a reproducer.

**Comment by lrlopez** [comment]
@Tobion, I'm willing to provide a reproducer, but I'm not sure how to do it.

I'll try to explain better:

If you follow the [link in the description](https://www.tomasvotruba.cz/blog/2017/10/16/how-to-use-repository-with-doctrine-as-service-in-symfony/) you'll see that you need to remove `(repositoryClass='App\Repository\ExampleRepository.php')` from the `@Entity` annotation in order to avoid circular dependencies when injecting the repository (the same would be applicable if configuring the entity via .xml or .yaml).

Problem is that `EntityUserProvider` gets the entity repository directly from Doctrine, which in turns return the information from the annotation (or whatever other configuration method used for the entity). So, it returns a generic entity repository instead of the one we want to use.

I can create a minimum Symfony project using HTTP authentication which exposes the problem if you want. Would that work for you?

**Comment by xabbuh** [comment]
This looks like an issue in the blog post then. If you want to register your repository as a service, you do not need to remove the `repositoryClass` attribute from the entity mapping. If I do not misunderstand your problem, you simply need to extend the `ServiceEntityRepository`class instead (see also https://symfony.com/doc/current/doctrine.html#querying-for-objects-the-repository).

**Comment by ro0NL** [comment]
I see, we're confusing 2 concepts actually. A decoupled repository from https://www.tomasvotruba.cz/blog/2017/10/16/how-to-use-repository-with-doctrine-as-service-in-symfony/ vs. a doctrine repository tied to (Service)EntityRepository.


I don't think we need to support decoupled repos in EntityUserProvider.php (just create your own provider then).

I reviewed the PR to allow for a custom Doctrine repository. I think @xabbuh is rigth.. if you switch to ServiceEntityRepository the current code should get  your custom Doctrine repo already.

**Comment by chalasr** [comment]
I confirm that making the repository extend `ServiceEntityRepository` + setting `repositoryClass` on the entity works fine and does not cause any circular reference on my side.  You should indeed use it instead.
I'm not convinced EntityUserProvider should support any other way to register doctrine repositories as services neither.

**Comment by lrlopez** [comment]
Thanks for pointing me to the right direction guys 😊

I didn't know about `ServiceEntityRepository` but it is definitely the way to go. I'm closing this issue and the related PR 👍

**Comment by javiereguiluz** [comment]
@lrlopez in case you don't know it, the Symfony Demo app is an application created as a learning resource and applies all the recommended Symfony best practices. The repositories of that app use `ServiceEntityRepository`. See https://github.com/symfony/demo/blob/master/src/Repository/PostRepository.php

**Comment by lrlopez** [comment]
Gracias Javier... It's been a long time since I've had a look into the Symfony Demo App. I think it's time to pay a visit to the app again 👍

**Comment by spackmat** [comment]
For the record: I wanted to stay with the fully decoupled repositories, so for me the solution was that I implemented a simple custom UserProvider getting my UserRepository injected. And now also the automatic password rehashing works fine.
