### ISSUE TITLE
Deserialising nested array of objects

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#29250]
**Symfony version(s) affected**: 4.1.4

**Installed**
symfony/serializer: v4.1.7
symfony/validator: v4.1.7
symfony/property-info: v4.1.7

**Description**  
Deserialising nested objects in arrays doesn't seem to be working or at least I am missing something so not sure if this is a bug or me. I've read [Handling Arrays](https://symfony.com/doc/current/components/serializer.html#handling-arrays) section but no clear help. It is talking about `ArrayDenormalizer` but didn't quiet get what to do with it in my config.

**How to reproduce**  

REQUEST

```
{
  "address": {
    "postcode": "ABC",
    "occupiers": [
      {
        "name": "Hello"
      },
      {
        "name": "World"
      }
    ]
  }
}
```

MODELS

```
namespace App\Model\;

use Symfony\Component\Validator\Constraints as Assert;

class User
{
    /**
     * @Assert\NotBlank
     * @Assert\Type("App\Model\Address")
     * @Assert\Valid
     */
    private $address;

    public function getAddress(): Address
    {
        return $this->address;
    }
}

-----------------------
namespace App\Model;

use Symfony\Component\Validator\Constraints as Assert;

class Address
{
    /**
     * @Assert\Type("string")
     * @Assert\NotBlank
     */
    private $postcode;

    /**
     * @Assert\NotBlank
     * @Assert\Type("iterable")
     * @Assert\Valid
     */
    private $occupiers;

    public function getPostcode(): string
    {
        return $this->postcode;
    }

    public function getOccupiers(): iterable
    {
        return $this->occupiers;
    }
}

-----------------------
namespace App\Model;

use Symfony\Component\Validator\Constraints as Assert;

class Occupier
{
    /**
     * @Assert\Type("string")
     * @Assert\NotBlank
     */
    private $name;

    public function getName(): string
    {
        return $this->name;
    }
}
```

RESULT

```
App\Model\User Object
(
    [address:App\Model\User:private] => App\Model\Address Object
        (
            [postcode:App\Model\\Address:private] => ABC
            [occupiers:App\Model\Address:private] => Array
                (
                    [0] => Array
                        (
                            [name] => Hello
                        )
                    [1] => Array
                        (
                            [name] => World
                        )
                )
        )
)
```

As you can see above nested `Address` section is deserialised as `array` which is normal because I used `@Assert\Type("iterable")` on `Address::$occupiers` property. However, trying to achieve the result below doesn't seem to be working. **Note**: If I add `Address::addOccupier` method, the problem is solved but my next step is to remove all getters from the models so adding `addOccupier` is not a solution.

```
App\Model\User Object
(
    [address:App\Model\User:private] => App\Model\Address Object
        (
            [postcode:App\Model\\Address:private] => ABC
            [occupiers:App\Model\Address:private] => Array
                (
                    [0] => App\Model\Occupier Object
                        (
                            [name:App\Model\Occupier:private] => Hello
                        )
                    [1] => App\Model\Occupier Object
                        (
                            [name:App\Model\Occupier:private]  => World
                        )
                )
        )
)
``` 

I tried `@Assert\Type("App\Model\Occupier")` and `@Assert\Type("App\Model\Occupier[]")` but this error `"address.occupiers":"This value should be of type App\\Model\\Occupier."}` etc. is occurring. If I used JMSSerializer it would be very easy e.g. `@Serializer\Type("array<App\Model\Occupier>")`!

**THIS IS MY SETUP**

**services.yaml**
```
services:
    ...

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~
    Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor: ~

    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        arguments:
            $nameConverter: '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
            $propertyTypeExtractor: '@Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor'
        tags: [serializer.normalizer]
```

**UserController**
```
namespace App\Util;

use App\Model\User;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
....

class UserController
{
    private $serializer;
    private $validator;

    public function __construct(SerializerInterface $serializer, ValidatorInterface $validator)
    {
        $this->serializer = $serializer;
        $this->validator = $validator;
    }

    // ....
    public function create(Request $request)
    {
        $request = $this->serializer->deserialize($request->getContent(), User::class, 'json');
        $errors = $this->validator->validate($request);

        if ($errors->count()) {
            throw new BadRequestHttpException(.....);
        }

        // ...
    }
}
```

**Comment by lyrixx** [comment]
You need to add PHPDoc on the property and to install the property info component and to enable it in the symfony configuration.
The normalizer will be configured automatically.

**Comment by BentCoder** [comment]
- symfony/property-info: v4.1.7 has already been installed.
- Adding `@var Occupier[]`, `@var \App\Model\Occupier` PHPDoc doesn't change anything.
- Adding `framework.property_info.enabled: true` to `framework.yaml` doesn't change anything either.

**Comment by BentCoder** [comment]
Problem solved by using `PhpDocExtractor` instead of `ReflectionExtractor `. Also to get rid of all the setters, getters etc. use `@var`.

**Comment by thePanz** [comment]
For the ones looking on how to "using PhpDocExtractor instead of ReflectionExtractor": refer to the SF documentation here: https://symfony.com/doc/4.4/components/property_info.html#phpdocextractor, 

> This extractor is automatically registered with the property_info in the Symfony Framework →**IF**← the dependent library is present

`composer req phpdocumentor/reflection-docblock`

**Comment by andrei-dascalu** [comment]
@thePanz in an optimised prod environment, opcache doesn't preserve comments. JMS serializer uses attributes for this. Feels like Symfony serializer might do the same.
