### ISSUE TITLE
[Form] Adding option 'hidden'

### ISSUE THREAD

**Issue by j** [symfony/symfony#2926]
Basically, I'm creating a new issue since PR #1951 got pretty out of hand and my proposal for this functionality differs completely from the PR itself.

Although the 'entity_id' type seemed like a good solution for just EntityType, I feel that merely ALL types should have the ability to be rendered as 'hidden'.

Then @RapotOR came up with this solution to be built into EntityType itself:

```php
<?php

// [...]

public function buildForm(FormBuilder $builder, array $options)
{
    if($options['widget'] === 'text') {
        $builder
            ->add($options['property'], 'text')
            ->add('id', 'hidden')
            ->prependClientTransformer(new EntityToArrayTransformer(
                $options['choice_list'], $options['property']
            ))
        ;
    } else {
        if ($options['multiple']) {
            $builder
                ->addEventSubscriber(new MergeCollectionListener())
                ->prependClientTransformer(new EntitiesToArrayTransformer($options['choice_list']))
            ;
        } else {
            $builder->prependClientTransformer(new EntityToIdTransformer($options['choice_list']));
        }
    }
}

// [...]

public function getParent(array $options)
{
    return $options['widget'] === 'text' ? 'form' : 'choice';
}
```

This looks like a great idea and everything too, but again, I feel that most types should be able to be rendered as hidden.

So, my proposal is to add the option `` 'hidden' => true `` in types that may need it.  This will fix all these issues everyone has when trying to add cool javascript functionalities. (javascript date/datetime pickers, entity auto-completion, etc).  I know I've needed this many times and it's a complete hack-job in order to do so.

For example:

**DateType:**

```php
<?php

// Would render:
//    <input type="hidden" name="my_form[publishedAt][year] value="" />
//    <input type="hidden" name="my_form[publishedAt][month] value="" />
//    <input type="hidden" name="my_form[publishedAt][day] value="" />

$builder->add('publishedAt', 'date', array(
    'widget' => 'choice', // or 'widget' => 'text'
    'hidden' => true
));
```

```php
<?php

// Would render:
//    <input type="hidden" name="my_form[publishedAt][date] value="" />

$builder->add('publishedAt', 'date', array(
    'widget' => 'single_text',
    'hidden' => true
));
```
**EntityType:**

```php
<?php

// Would render:
//    <input type="hidden" name="my_form[users][] value="" />

$builder->add('users', 'entity', array(
    'class' => 'AcmeHelloBundle:User',
    'query_builder' => function(EntityRepository $er) {
        return $er->createQueryBuilder('u')
            ->orderBy('u.username', 'ASC');
    },
    'hidden' => true
));
```

... and if developers want to add an extra non hidden text-field for the auto-completion part, they can just add a property in their form model object so that it can be populated on errors and such.

Anyway, to me, I feel that this would be the most clean and less confusing way of handling hidden fields.

What do you think? @bschussek @Gregwar @jmikola @RapotOR @fabpot ?

**Comment by webmozart** [comment]
Thank you again for proposing this issue! Unfortunately I don't see an easy way to implement the "hidden" option for any form type without adding lots of logic. On the other hand, every form has an ID, so doing something like:

```css
#my_form input {
    display: none;
}
```

is very easy to implement. I'd rather not add lots of logic if there is a simple alternative solution that works.
