### ISSUE TITLE
Error: Class App\Kernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Serializable::)

### ISSUE THREAD

**Issue by youssefbenhssaien** [symfony/symfony#29269]
**Symfony version(s) affected**: 4.1.7

**Description**  
Touching nothing ! I'm getting this error.
Error: Class App\Kernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Serializable::)
![image](https://user-images.githubusercontent.com/7301643/48830554-260ad200-ed75-11e8-8db6-ef79e2813317.png)

**How to reproduce**  
Nothing !

**Comment by youssefbenhssaien** [comment]
I restarted the server and worked again ! wired behavior !

**Comment by stof** [comment]
maybe a memory corruption of the opcache shared memory

**Comment by xabbuh** [comment]
let's close then as the issue seems to be resolved
