### ISSUE TITLE
[PhpunitBridge] Could not find https://github.com/sebastianbergmann/phpunit/archive/7.2.zip in /app/vendor/symfony/phpunit-bridge/bin/simple-phpunit:99

### ISSUE THREAD

**Issue by tonivdv** [symfony/symfony#29264]
Hi,

Since this morning tests are failing due to "Could not find https://github.com/sebastianbergmann/phpunit/archive/7.2.zip in /app/vendor/symfony/phpunit-bridge/bin/simple-phpunit:99" ... Is this a github issue or something wrong at @sebastianbergmann library side? Or did I completely miss something?

Cheers

**Comment by peterprochaska** [comment]
The same for me with version 5.7

**Comment by gellis** [comment]
Yes we are having the same issue with 5.7

**Comment by nicolas-grekas** [comment]
That's because the corresponding branches where deleted from https://github.com/sebastianbergmann/phpunit
@sebastianbergmann could you please bring them back?

**Comment by gellis** [comment]
To avoid this issue you can add this to phpunit.xml.dist:

```
<php>
<env name="SYMFONY_PHPUNIT_VERSION" value="7.4.4" />
</php>
```

**Comment by engagit** [comment]
I am using Symfony v2.8 for a project (cannot upgrade at this time), so I have assumed that the fix being pulled into Symfony is not going to be available to me.

I tried to use the suggested fix by gellis, setting the SYMFONY_PHPUNIT_VERSION in my phpunit.xml.dist file, but when I run my tests, it is being completely ignored.

I use the following command to run my test suite:  ./bin/simple-phpunit -c app/

Am I missing something?

**Comment by kblais** [comment]
@engagit The environment variable `SYMFONY_PHPUNIT_VERSION` only works with PHP >= 5.6.0 (see https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L51), you must be using an older PHP version. Try running your tests on PHP >= 5.6

**Comment by kblais** [comment]
@xabbuh the phpunit.xml file is evaluated by the binary (see https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L26)

**Comment by engagit** [comment]
I am using PHP 7.1  Also, I have the SYMFONY_DEPRECATIONS_HELPER set in that config file, which works, so I felt it was safe to assume that the config file isn't being completely ignored.

This is the block in the phpunit.xml file:
`<php>
        <env name="SYMFONY_PHPUNIT_VERSION" value="5.26" />
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak" />
    </php>`

If there is other information I can show you that would help, let me know.    Thank you so much for your replies.

**Comment by nicolas-grekas** [comment]
Please upgrade to latest versions that have just been released.

**Comment by stof** [comment]
@engagit the version of `symfony/phpunit-bridge` you use is independant from the rest of Symfony. So you could probably still update that package.

**Comment by engagit** [comment]
My apologies, I misunderstood and assumed you also meant to upgrade Symfony.  Thank you for the tips everyone, and I will try that!

**Comment by engagit** [comment]
Thank you, that solved the issue.  I believed I was pointing at the latest and greatest, but composer.json was pointing to @dev.  All of your help is very appreciated!
