### ISSUE TITLE
symfony/phpunit-bridge[v4.1.7] simple-phpunit exec error

### ISSUE THREAD

**Issue by helloooideeeeea** [symfony/symfony#29279]
**Symfony version(s) affected**: 2.8

**Description**  
symfony/phpunit-bridge[v4.1.7] simple-phpunit exec error
following error message.
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Could not find https://github.com/sebastianbergmann/phpunit/archive/5.7.zip'

https://github.com/sebastianbergmann/phpunit/archive/5.7.zip is not found.

master is fixed this.
but v4.1.7(tag) is old.
Please fix!

**Comment by raziel057** [comment]
It's releated to this:

https://github.com/symfony/symfony/commit/e166d96cf57c98f5db47d16a3c86669428b3eb7d
https://github.com/sebastianbergmann/phpunit/issues/3413
