### ISSUE TITLE
add option to auto generate random token

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony#29282]
**Description**  
add option to auto generate random token instead of default "ThisTokenIsNotSoSecretChangeIt"

**Comment by ro0NL** [comment]
Hi @erlangp, can you desribe what's happening more precisely?

Today the token should be randomized already on a fresh install, e.g. in `.env` you'll see

```
APP_SECRET=ca64960ac87a8f23146deac5b831c920 #random every time
```

**Comment by erlangp** [comment]
i have made a project using https://packagist.org/packages/symfony/framework-standard-edition, sir

**Comment by erlangp** [comment]
i'am sorry sir, i just read EOL of that package

**Comment by ro0NL** [comment]
Correct :) Also as of 3.4  you can use Symfony Flex already: https://symfony.com/doc/3.4/setup/flex.html

Which will automate the initial config for you and as such randomizes the secret on install.

**Comment by erlangp** [comment]
thanks sir :+1:
