### ISSUE TITLE
Tests fail on armhf

### ISSUE THREAD

**Issue by panlinux** [symfony/symfony#29281]
**Symfony version(s) affected**: 3.4.18

**Description**  
The test suite fails on armhf, and apparently on s390x too, but I only have the armhf output at hand.

**How to reproduce**  
Debian (and Ubuntu) run autopkgtests constantly:
- Ubuntu test matrix: http://autopkgtest.ubuntu.com/packages/s/symfony
- Debian test matrix: https://ci.debian.net/packages/s/symfony/

 This is the test script from Debian: https://salsa.debian.org/php-team/pear/symfony/blob/master/debian/tests/phpunit

Ubuntu just added a skip at the top if the architecture is s390x.

Some tests are disabled already, and most of the patches that are applied to the package are about fixing or disabling other tests.

Updating to 3.4.18 fixed the tests in all arches except armhf (s390x is skipped and the green result is a fake one). The armhf failure that remains with symfony version 3.4.18 and php 7.2.11 is:

http://paste.ubuntu.com/p/CBFFzP43Yk/

The test run starts on line 2337.

Summary of the tests that failed:

```
Symfony\Component\Form\Tests\Extension\Core\DataTransformer\IntegerToLocalizedStringTransformerTest::testReverseTransformDisallowsNaN2
Failed asserting that exception of type "\Symfony\Component\Form\Exception\TransformationFailedException" is thrown.

Symfony\Component\Form\Tests\Extension\Core\DataTransformer\NumberToLocalizedStringTransformerTest::testReverseTransformDisallowsNaN2
Failed asserting that exception of type "\Symfony\Component\Form\Exception\TransformationFailedException" is thrown.

...

Symfony\Component\VarDumper\Tests\Caster\SplCasterTest::testCastFileInfo with data set #0 ('/tmp/autopkgtest.WOPzjm/build...st.php', 'SplFileInfo {\n%Apath: "%sCas...e\n%A}')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
   aTime: 2018-11-21 19:07:54
   mTime: 2018-11-03 10:03:29
   cTime: 2018-11-21 19:07:45
-  inode: %d
+  inode: -1993734302
   size: 4986
   perms: 0100664
   owner: 1000

Symfony\Component\VarDumper\Tests\Caster\SplCasterTest::testCastFileObject
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
   aTime: 2018-11-21 19:07:54
   mTime: 2018-11-03 10:03:29
   cTime: 2018-11-21 19:07:45
-  inode: %d
+  inode: -1993734302
   size: 4986
   perms: 0100664
   owner: 1000
@@ @@
   csvControl: array:3 [
     0 => ","
     1 => """
-%A]
+    2 => "\"
+  ]
   flags: DROP_NEW_LINE|SKIP_EMPTY
   maxLineLen: 0
   fstat: array:26 [
-    "dev" => %d
-    "ino" => %d
-    "nlink" => %d
+    "dev" => 40
+    "ino" => -1993734302
+    "nlink" => 1
     "rdev" => 0
-    "blksize" => %i
-    "blocks" => %i
+    "blksize" => 4096
+    "blocks" => 16
      …20
   ]
   eof: false
   key: 0
 }

```

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR tweaking the offending line?
`inode: %d` should be `inode: %i` everywhere in the component

**Comment by panlinux** [comment]
Sure, np

**Comment by panlinux** [comment]
Sorry for the delay, I'm trying to validate the fix on armhf.

**Comment by panlinux** [comment]
I tried this, but it's very hard to reproduce the problem in a manual run in the hardware I have available, so I can't verify it's doing the right thing:
```diff
--- a/src/Symfony/Component/VarDumper/Tests/Caster/SplCasterTest.php
+++ b/src/Symfony/Component/VarDumper/Tests/Caster/SplCasterTest.php
@@ -35,7 +35,7 @@
   aTime: %s-%s-%d %d:%d:%d
   mTime: %s-%s-%d %d:%d:%d
   cTime: %s-%s-%d %d:%d:%d
-  inode: %d
+  inode: %i
   size: %d
   perms: 0%d
   owner: %d
@@ -85,7 +85,7 @@
   aTime: %s-%s-%d %d:%d:%d
   mTime: %s-%s-%d %d:%d:%d
   cTime: %s-%s-%d %d:%d:%d
-  inode: %d
+  inode: %i
   size: %d
   perms: 0%d
   owner: %d
@@ -105,7 +105,7 @@
   maxLineLen: 0
   fstat: array:26 [
     "dev" => %d
-    "ino" => %d
+    "ino" => %i
     "nlink" => %d
     "rdev" => 0
     "blksize" => %i

```

If you think a PR is still useful, I can do that of course. But I was unable to verify the patch.

**Comment by nicolas-grekas** [comment]
PR welcome yes, no pb to merge it on my side.

**Comment by panlinux** [comment]
I was so focused in trying to reproduce the error interactively that I think I missed something. What does `%i` format string do/mean? I couldn't find it described in http://php.net/manual/en/function.sprintf.php

**Comment by nicolas-grekas** [comment]
See https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertStringMatchesFormat
