### ISSUE TITLE
FileNotFoundException in the RequestDataCollector when the request contains uploaded files

### ISSUE THREAD

**Issue by fbourigault** [symfony/symfony#29284]
**Symfony version(s) affected**: 4.2.0-beta2

**Description**  
Since uploaded files are displayed in the profiler, each time a `Request` with at least one `UploadedFile` is profiled, a `FileNotFoundException` is thrown. This happens because the `UploadedFile` method was called and  was successful.

It's was probably introduced in #26946.

**How to reproduce** 
Create a new Symfony 4.2 project with the profiler and setup file upload like explained in the documentation (https://symfony.com/doc/current/controller/upload_file.html).

Then choose a file, submit the form.

**Additional context**  
![localhost_8000_product_new](https://user-images.githubusercontent.com/1116116/48907898-1f5d8700-ee69-11e8-82cb-84c4583a42ae.png)

**Comment by nicolas-grekas** [comment]
This isn't the case in 4.1? Are you able to investigate why? Maybe submit a fix?

**Comment by fbourigault** [comment]
It's https://github.com/symfony/symfony/pull/26946. ping @javiereguiluz.

**Comment by ro0NL** [comment]
So the tmp. file is deleted before the profiler collects? Which happens during the same request.. so im curious what exactly happens. As i didnt encounter it when playing/fixing the feature (see #29183)

**Comment by yceruto** [comment]
The controller runs before the request collector, so if the uploaded file path is changed during this process (it's moved to another dir) the collector breaks, relying on the initial request information. That's the problem.

**Comment by yceruto** [comment]
Also because the `$file->getMimeType()` method re-executes the process based on the initial information:
https://github.com/symfony/symfony/blob/b5143233d2273b6f32f8dcc5b07c71afd3613f85/src/Symfony/Component/HttpFoundation/File/File.php#L75-L80

**Comment by yceruto** [comment]
I found a solution for this, but could change the Javier's initial design, git pushing PR...

**Comment by fbourigault** [comment]
@yceruto it works
