### ISSUE TITLE
PHP 7.3 cache:clear issue

### ISSUE THREAD

**Issue by rantarou** [symfony/symfony#29288]
**Symfony version(s) affected**: 4.1.7

**Description**  
error when run ./bin/console cache:clear

**How to reproduce**  
run this command using PHP 7.3

**Possible Solution**  

**Additional context**  
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In UnitOfWork.php line 2718:
!!                                                                                 
!!    Warning: "continue" targeting switch is equivalent to "break". Did you mean  
!!     to use "continue 2"?                                                        
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by nicolas-grekas** [comment]
Hi, thanks for reporting.
`UnitOfWork` is a file that belongs to Doctrine (http://github.com/doctrine/doctrine2)
I think they already fixed the issue btw. Did you try updating it?
