### ISSUE TITLE
Correct trailing slash redirection behavior?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#29287]
We spotted the following:

Given two routes (in order):
- "a": `/foo/`
- "b": `/{name}`

for URL `/foo`, a redirectable router matcher:
- matches "a" before 4.1 when being dumped (with internal redirection of course)
- matches "b" before 4.1 when being *not* dumped
- matches "b" since 4.1 when being dumped *or not*

What is the correct behavior?

**Comment by fbourigault** [comment]
Since "a" is a kind of fallback to avoid a 404s, I thing the third option is the correct behavior.

**Comment by Tobion** [comment]
I agree with @Nyholm. This matches other redirection logic we have. First match exact matches, then fall back to redirect. Otherwise it would be inconsistent with

Given two routes (in order):

- "a": `/foo`
- "b": `/{name<.+>}`

for URL `/foo/` should match "b" first, before redirecting to "a"

**Comment by nicolas-grekas** [comment]
Interesting because on Slack I read opposite arguments and they make sense also:

> I'd say a), the slash being significant is error prone

> If you treat the trailing slash as non-significant, then that should apply here too, this would 100% confuse me if it happened

> I'd expect `/foo` and `/foo/` to behave the same if trailing slash redirects and this route is configured first
> If you have dynamic fallback routes, they should not match if a redirect is in place, this gives unexpected behaviour, especially if the configuration is defined elsewhere. Imagine a controller with annotations defining `/foo/`, but the `/{name}` route being matched despite being defined manually, as last, in the yml

The least surprise principle would hint me at "a" also. Technically, symfony.com would be affected by changing from "a" to "b".

But that not obvious, that's why I asked :)
@Nyholm @Tobion @fabpot does that make better sense to you now or not?

**Comment by dkarlovi** [comment]
The "correct behaviour" term is loaded here: does it mean "technically correct" or "correct as expected"?

If you want to be technically correct, I agree with @Nyholm, it's not a full match.

If you want to be working as (IMO) expected, then a) should match. Again, if you're saying the trailing slash is ignored, then it's perceived as non-significant and having `/foo` not match `^/foo/?$` is unexpected.

**Comment by javiereguiluz** [comment]
I disagree with @Nyholm. In Symfony apps, if your route is `/foo/`, both `/foo/` and `/foo` work. That's a well-known (and heavily relied upon) behaviour since day one. I don't care about the later catch-all `/{name<.+>}` route. In my opinion, `/foo` should redirect to `/foo/`.

**Comment by Wirone** [comment]
Imagine letter addressed with "street" prefix/suffix and without it - it's still the same address, deliverable (well, probably not always). Or maybe semicolons in Javascript - it's the same instruction whether you put `;` at the end or not. For me, trailing `/` isn't really part of the URL, it's UX detail, personal preference for displaying unique "web address". Even this issue can be accessed [with slash](https://github.com/symfony/symfony/issues/29287/) and [without it](https://github.com/symfony/symfony/issues/29287).

And IMO there shouldn't be any redirect, just display the same content under both URLs (like Github does).

**Comment by Tobion** [comment]
/foo/ and /foo are not the same URIs. For this reason it does not make sense to match a different route than the one that actually matches. Also if you generate a the uri for "b" with name=foo, you will get `/foo` BUT it won't actually match route "b" at all. This is totally unexpected.
Also if you give redirection a higher prio than actually matching, you also need to redirect schemes http <-> https before actually trying to find a route with the right scheme to be consistent.

**Comment by Wirone** [comment]
@Tobion If you define dynamic routes with params that conflict with other routes, it's your fault. Trailing slash doesn't matter. Look at this issue, it's displayed under both URIs because its namespace is unique.

**Comment by Nyholm** [comment]
Thank you for the discussion and the input.

**Comment by murnieza** [comment]
I have route `/foo/{bar<.*>}` and after this change `/foo/` does not match my route anymore.

**Comment by Tobion** [comment]
@murnieza please open a new issue
