### ISSUE TITLE
[Translator] Wrong formatter used

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#29290]
**Symfony version(s) affected**: 4.2-beta2

**Description**  
I'm using the new `+intl-icu` suffix for my translation files.
After clearing cache, everything is working fine in first page call.
But with existing cache, the messages (intl format) are not converted correctly.

It is reproducible with symfony-demo (you have to update to beta2).

First call with empty cache:

![screenshot 2018-11-23 11 57 24](https://user-images.githubusercontent.com/330436/48940162-f693cb00-ef16-11e8-9399-6e7c2872afc3.png)

With existing cache:

![screenshot 2018-11-23 11 57 44](https://user-images.githubusercontent.com/330436/48940186-06abaa80-ef17-11e8-86ec-31eabb864f2b.png)

**Additional context**  
I guess the bug is a result of #29220. (@nicolas-grekas)

**Comment by nicolas-grekas** [comment]
Thanks for trying and reporting.
Can you please confirm #29300 fixes the issue?
