### ISSUE TITLE
Rendering of the form panel of the profiler breaks due to data.id being undefined

### ISSUE THREAD

**Issue by stof** [symfony/symfony#29291]
**Symfony version(s) affected**: 3.4.18

**Description**  
The macro `form_tree_details` and `form_tree_entry` uses `data.id` in a lot of places. Some of them check for it to be defined, but some others don't. And I got a case where it fails:

```
Twig_Error_Runtime:
Neither the property "id" nor one of the methods "id()", "getid()"/"isid()"/"hasid()" or "__call()" exist and have public access in class "Symfony\Component\VarDumper\Cloner\Data".

  at vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/form.html.twig:429
```

**How to reproduce**  
I don't have a standalone reproducer for now.

**Comment by ro0NL** [comment]
Tried to reproduce, without any luck so far.

Looking at code there  should always be an id set :thinking: 

https://github.com/symfony/symfony/blob/d9f87b6f58f68c8e51ee3db4ecea1a0acf3fb475/src/Symfony/Component/Form/Extension/DataCollector/FormDataExtractor.php#L31

Do you have some hints about the form structure. Does it happen on the root- or a child-form?

**Comment by stof** [comment]
I have a CollectionType in this form. The missing id happens for the first element in this collection.

I think this is related to the fact that the fields are added in a PRE_SUBMIT listener. Maybe `extractConfiguration` is not called properly for dynamic fields, and so the data is incomplete.

**Comment by ro0NL** [comment]
For

```php
public function __invoke(FormFactoryInterface $f, Request $r)
{
    $form = $f->createBuilder();
    $form->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $e) {
        $e->getForm()->add('coll', CollectionType::class, ['data' => ['foo']]);
    });
    $form->add('submit', SubmitType::class);
    $form = $form->getForm();
    $form->handleRequest($r);

    return $this->render('index.html.twig', ['form' => $form->createView()]);
}
```

After submit i see `id=form_coll_0` for a view variable in the profiler.

Nevertheless, this code looks related:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/DataCollector/FormDataCollector.php#L307-L322

The first $output variable is ignored here.

**Comment by stof** [comment]
I'm not adding the collection type itself in a PRE_SUBMIT. But the collection type itself adds new children here.

**Comment by WubbleWobble** [comment]
We ran into this bug too. Not sure what's causing it, but this does reproduce this issue:  
https://github.com/WubbleWobble/symfony-issue-29291

**Comment by yceruto** [comment]
Fixed in https://github.com/symfony/symfony/pull/33999
