### ISSUE TITLE
[Bug][Templating][Twig] Impossible to override templates of bundles

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony#29299]
**Symfony version(s) affected**: 3.4/4.x

**Description**  
I am in the progress of updating an app to Symfony 4 and the new flex directory structure.
Therefore I was trying to override the FOSUserBundle login template. This was not working
even with the file in the proper location according to the docs.

**How to reproduce**  
I had templating enabled with twig as engine. The template was placed in /templates/bundles/FOSUserBundle/Security/login.html.twig and was not loaded.

While debugging I found out, that the functionality introduced in the TwigExtension to handle the proper loading as introduced in https://github.com/symfony/symfony/pull/24179 is not triggered.
It seems the TwigExtension is not loaded at all.

**Possible Solution**  
Disabling the templating configuration of the framework bundle solved the issue for me.
Is this intended that this does not work with having the templating component enabled?

**Comment by yceruto** [comment]
Could you check if this config https://github.com/symfony/symfony/issues/25811#issuecomment-440364723 solves your issue?

**Comment by yceruto** [comment]
> Is this intended that this does not work with having the templating component enabled?

As far as I know both (PHP templates and Twig templates) can have coexist in the same application.

**Comment by peterrehm** [comment]
That is the config I had, with this config the TwigExtension load method will not be called. Once I removed the config setting the load method is called and the proper template is located.

**Comment by yceruto** [comment]
I'm not able to reproduce the issue (at least for 3.4) with this config enabled:
```yaml
framework:
    templating:
        engines: ['twig']
```
Could you create a small application that reproduces the problem and shares it?

**Comment by peterrehm** [comment]
Thank you for your feedback, in my test application I could isolate the issue to be with an external bundle.

Apparently the issue is within the LiipThemeBundle, I have to dig deeper into that matter.
