### ISSUE TITLE
YamlEncoder produces JSON string

### ISSUE THREAD

**Issue by FaHuSchmidt** [symfony/symfony#29301]
**Symfony version(s) affected**: 4.1.7

**Description**  
The encode method of Symfony\Component\Serializer\Encoder\YamlEncoder produces a JSON string instead of a YAML string.

**How to reproduce**  

    $yamlEncoder = New YamlEncoder();
    var_dump($yamlEncoder->encode(['foo' => 'bar'], 'yaml'));

**Possible Solution**  
Not a solution, but an working alternative:

    var_dump(Yaml::dump(['foo' => 'bar']));

**Additional context**

**Comment by xabbuh** [comment]
Can you provide some more details? What result did you get and what did you expect instead?

**Comment by FaHuSchmidt** [comment]
@ro0NL you're absolutly right, thx! I didn't recognize this option at all.

I think the doc for this are not correct. The serializer docs refer to the yaml component and there it says 

> By default, the dumper uses the expanded representation

https://symfony.com/doc/current/components/yaml.html#array-expansion-and-inlining

`\Symfony\Component\Serializer\Encoder\CsvEncoder` and `\Symfony\Component\Yaml\Dumper` are using `0` as default setting, which is inline.

Or did i get sth wrong again?

**Comment by ro0NL** [comment]
At least Yaml::dump() uses inline=2 by default.

But the YamlEncoder is part of the Serializer component (which on itself uses the Yaml component), so here the docs dont apply, that be https://symfony.com/doc/current/components/serializer.html#the-yamlencoder

But those are very minimal and doesnt the describe the available context settings (e.g `yaml_inline`).

**Comment by FaHuSchmidt** [comment]
Oh ok, i looked directly at the dumper instead of the yaml component class itself.

Thanks for your help!
