### ISSUE TITLE
Returning HTTP 204 via JsonResponse sends content anyway (but with missing headers)

### ISSUE THREAD

**Issue by kxpvcr** [symfony/symfony#29326]
**Symfony version(s) affected**: 4.1

**Description**  

I originally reported a potential bug in [`nodejs`](https://github.com/nodejs/node/issues/24580), but  after some exploration it seems Symfony is partially to blame. To quote myself:

> We have a PHP API backend using Symphony, and the endpoints use `HttpFoundation\JsonResponse`. When a request is accepted, we return `HTTP 204 No Content`, via `new JsonResponse()` along with `JsonResponse::HTTP_NO_CONTENT`. This, however, returns a **content length of 2:** `{}`.

Switching to `HttpFoundation\Response` and returning that module's `HTTP_NO_CONTENT` works fine: no content is sent in the response, so `nodejs` can parse it properly. As per [a contributor's comment](https://github.com/nodejs/node/issues/24580#issuecomment-441517009):

> After digging in Symfony's code a bit it looks like what's actually happening is that it's removing Content-Type and Content-Length headers when the response code is 204, but sending the data anyway.

Do you consider this to be incorrect behaviour?

**How to reproduce**  

We have a route mapping to a controller with code:

```php
use Symfony\Component\HttpFoundation\JsonResponse;

...

$response = new JsonResponse();
$response->setStatusCode(JsonResponse::HTTP_NO_CONTENT);
return $response;
```

This yields the issue in `nodejs`, that it refuses/fails to parse a request with no Content-Length reported, but an actual length of 2 (`{}`).

**Possible Solution**  

Switching to the code below solves the issue:

```php
use Symfony\Component\HttpFoundation\Response;

...

$response = new Response();
$response->setStatusCode(Response::HTTP_NO_CONTENT);
return $response;
```

`HttpFoundation\Response` adequately sends an `HTTP 204` without content. Potentially, **making `JsonResponse` return a content-less empty response** would fix the problem and conform better to the spec?

Let me know if I can be of further help!

**Comment by ro0NL** [comment]
I think "a JSON response" vs. "no content" contradicts; it's not a JSON response anymore. AFAIK a 204 response does not need a content-type. Not sure we want to patch JsonResponse, effectively making it  a one-size-fits-all type.

Currently you can use json+204, there's no spec that forbids doing it. So using the regular `Response` seems OK.

**Comment by kaznovac** [comment]
i agree with ro0NL
implementing `createNoContentResponse` on `ControllerTrait` might help reduce confusion which Response class should be used

**Comment by ro0NL** [comment]
`new EmptyResponse()` is also nice to have
