### ISSUE TITLE
[RFC][Framework-Bundle] Make an Application available as a container service

### ISSUE THREAD

**Issue by edefimov** [symfony/symfony#29325]
Some use-cases require to inject an instance of `Symfony\Component\Console\Application` class into arbitrary service. 

Example use-case: there is a daemon based on symfony console component which can run workers. Each worker is a container service. Some workers can run arbitrary application commands inside the separated process (as an example of such a command is [consuming messages](https://github.com/symfony/symfony/blob/v4.1.6/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php)). To run a command worker needs an instance of Application.

```xml
<service id="App\Worker\SomeWorker">
    <argument type="service" id="Symfony\Component\Console\Application" />
</service>

<!-- or -->
<service id="App\Worker\SomeWorker">
    <argument type="service" id="application" />
</service>
```

This feature will also reduce complexity of adding custom helper sets by defining them as services and injecting them into Application service using CompilerPass.

```xml
<service id="App\Console\HelperSet\MyHelper">
    <tag name="console.helper_set" helper="my" />
</service>
```

**Comment by ro0NL** [comment]
I suggested "application as a service" once :D https://github.com/symfony/symfony/pull/23887#discussion_r133435380

But mostly to ease its wiring, not to be injected really. Im still not sure why one wants to inject a CLI application, only CLI commands might care (but those already have scope).

> reduce complexity of adding custom helper sets

See also #27647

> Some workers can run arbitrary application commands inside the separated process (as an example of such a command is consuming messages).

a) im not sure a "worker" should depend on something from CLI, let alone dispatch CLI commands. Unless the worker is an actual CLI command itself.
b) i dont see how `messenger:consume-messages` relies on other CLI commands

**Comment by edefimov** [comment]
> a) im not sure a "worker" should depend on something from CLI, let alone dispatch CLI commands. Unless the worker is an actual CLI command itself.

I mean the worker should act as console CLI application itself, as if it was called from CLI. The main task for such worker is running in a separate process and process given application command until explicitly stopped.

> b) i dont see how messenger:consume-messages relies on other CLI commands

It doesn't. This command in our use-case should run inside a worker.

**Comment by ro0NL** [comment]
Cant you create a new application service for that?

**Comment by edefimov** [comment]
In this case the isolation from framework is not required at all, since we need the same configured application, created in bin/console.

**Comment by lisachenko** [comment]
I also vote for this feature to have an ability in future to declare CLI `HelperSet` as an auto-registered and configured services for a console application instance. 

This will be one more step towards CLI stuff working with DI without writing code by hands.

**Comment by chalasr** [comment]
@lisachenko Could you describe your usage of `HelperSet`? 
There is a discussion about deprecating it, to me it is just a service locator which was useful before that commands as services were introduced. 
Also asking because the implementation proposed in #29669 won't help at all regarding custom `HelperSet`.
