### ISSUE TITLE
ClassNotFound exception emerged when using class from php extension

### ISSUE THREAD

**Issue by FrankCh-en** [symfony/symfony#29330]
**Symfony version(s) affected**: 3.4.18

**Description**  
When trying to use  classes  defined in php extension, ClassNotFound exception emerged.
For example, when trying to invoke a class named BFS which is defined in 'bfs.so' extension, symfony will try to load the class from current namespace in stead of loading class from php extension. As a result, symfony can not load the BFS class properly with ClassNotFound exception.

On the contrary, I can successfully use the class and its method mentioned above in an independent PHP script with PHP CLI commands.

**How to reproduce**  

```php
/**PHP code in an independent PHP file
* test.php
**/
$fs=new BFS();
$fs->init();
$fs->ls();
$fs->mkdir();
$fs->rmdir();
```

 The code above can be successfully executed using php command
./test.php
with the proper configuration of the php extension.
**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
This does not look like a Symfony issue, but like the PHP version used to execute the script is not the same as the one having the extension enabled.

Please refer to one of the [support channels](https://symfony.com/support) if you need any further help. I am going to close here as there is nothing to fix. Thank you for understanding.

**Comment by FrankCh-en** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/25506648/49016060-e5211c00-f1bf-11e8-803d-22bd49c61bff.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/25506648/49016021-bd31b880-f1bf-11e8-9691-5ca91c9fe9bc.png">

Would you please give me some help? I can not find a matched solution in the symfony support page. The BFS class is not in BFS/Core/BFS, but in the bfs.so extension. The code above can be successfully executed with php command.
Thank you very much!
Sincerely.

**Comment by nicolas-grekas** [comment]
You need to either use a `\` in front of the class name when using it (eg `new \FS();`)
or add a line like `use FS;` just after the namespace declaration.

**Comment by FrankCh-en** [comment]
I'm sorry that I just uploaded the wrong error info image. Symfony can not find the class \BFS(),but not FS().  BFS is the class that I declared in the php extension, and the code below can be successfully executed with PHP command in the same PHP environment that running symfony.

 $bfs=new \BFS();
 $bfs->init("/home/bfs/sandbox/bfs.flag");
$bfs->mkdir("/test");
//.....
Why symfony can not load the class BFS? 

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/25506648/49016697-d89dc300-f1c1-11e8-80ec-a350c9c1abf3.png">

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/25506648/49016822-3d591d80-f1c2-11e8-89e9-23b1a4ea6b59.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/25506648/49016914-6e395280-f1c2-11e8-8176-fd65bf3407c2.png">

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/25506648/49016964-988b1000-f1c2-11e8-8c15-a1bba3500989.png">

**Comment by nicolas-grekas** [comment]
This is unrelated to Symfony but to PHP namespaces.
I'd recommend you read the PHP doc about PHP namespaces and get familiar with them.
In your screenshot, you should remove the `\` in the second screen.

**Comment by FrankCh-en** [comment]
If I remove the \ in code $this->bfs=new \BFS(); you mentioned above, the error info emerges like the fist screenshot below. Symfony will try to load the  BFS class from BFS\Core
I'm still a freshman in PHP. Deeply appreciate your help.
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/25506648/49018150-a2624280-f1c5-11e8-8d95-4db1e17eb528.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/25506648/49018509-96c34b80-f1c6-11e8-8ed0-9dde6c151f22.png">
