### ISSUE TITLE
Bug 3.4.19 CollectionType persist

### ISSUE THREAD

**Issue by jbrat** [symfony/symfony#29348]
**Symfony version(s) affected**: 3.4.19

**Description**  
With the update from 3.4.18 to 3.4.19 the persistance of a CollectionType doesn't work. I'm using the prototype form with JS to add item in a CollectionType, in my Entity got a relation OneToMany with cascade persist and i have the add / remove methods. 

````php
/**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *    targetEntity="MyBundle\Entity\SellerMarketPeriod",
     *    mappedBy="sellerMarket",
     *    cascade={"persist", "remove"},
     *    orphanRemoval=true
     * )
     */
    private $periods;

    /**
     * @param SellerMarketPeriod $sellerMarketPeriod
     */
    public function addPeriod(SellerMarketPeriod $sellerMarketPeriod)
    {
        if(!$this->periods->contains($sellerMarketPeriod)) {
            $this->periods->add($sellerMarketPeriod);

            $sellerMarketPeriod->setSellerMarket($this);
        }
    }

    /**
     * @param SellerMarketPeriod $sellerMarketPeriod
     */
    public function removePeriod(SellerMarketPeriod $sellerMarketPeriod)
    {
        if($this->periods->contains($sellerMarketPeriod)) {
            $this->periods->removeElement($sellerMarketPeriod);
            $sellerMarketPeriod->setSellerMarket(null);
        }
    }
````

````php 
   /**
     * @var SellerMarket
     *
     * @ORM\ManyToOne(targetEntity="TCOOptimaBundle\Entity\SellerMarket", inversedBy="periods")
     */
    private $sellerMarket;
````

When i submit my form the CollectionType is not empty, i have the correct values and after the persist the sellerMarketPeriod doesn't have the foreign key link of the SellerMarket.

The persist and flush doesn't persist the foreign key of the item

Thank's for future answer.

**Comment by nicolas-grekas** [comment]
Related to #29340?

**Comment by jbrat** [comment]
Yes it's the same problem sorry

**Comment by nicolas-grekas** [comment]
No pb, thanks for reporting. Please continue the discussion there if you want to provide more details.
