### ISSUE TITLE
[DI] Incorrect service id report for non-existent services

### ISSUE THREAD

**Issue by edefimov** [symfony/symfony#29359]
**Symfony version(s) affected**: 4.0.14 and above

**Description**  
Imagine there are two services _A_ and _B_ in the container. The _A_ service depends on non-existent service _X_, the _B_ service depends on _A_. If the _A_ is declared as _public=false_, then container compilation reports, that service _B_ has requested non-existent service _X_. If the _A_ service is _public=true_, the report message will be correct.

**How to reproduce**  
Try to compile container with such definition:
```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="AppBundle\Service\Child" public="false">
            <argument type="service" id="serializer" /> <!-- Missed service -->
        </service>

        <service id="AppBundle\Service\ParentA" public="true">
            <argument type="service" id="AppBundle\Service\Child" />
        </service>
    </services>
</container>
```
Reproducing application: https://github.com/edefimov/symfony-reproduce/tree/eea1edabc1ab944603cf773d570e51ed0357f37d/

**Additional context**  
The output when service _AppBundle\Service\Child_ is _public=false_
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
                                                                                                    
  The service "AppBundle\Service\ParentA" has a dependency on a non-existent service "serializer".                                                                                                 
```

Correct output when service _AppBundle\Service\Child_ is _public=true_ 
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
                                                                                                  
  The service "AppBundle\Service\Child" has a dependency on a non-existent service "serializer".                                  
```

**Comment by xabbuh** [comment]
Does this also happen with 4.1.8?

**Comment by edefimov** [comment]
@xabbuh , Yes 4.1.8 also affected this behaviour

**Comment by nicolas-grekas** [comment]
That's normal behavior: when a service is private and is unused, it is removed. Throwing an error because it misses a dependency would make no sense. When the service is made public, this dependency must be defined so it throws.

**Comment by edefimov** [comment]
In this reproducing application all services are used: the final service `AppBundle\Service\ParentA` is public and requires a private service with missed dependency.

**Comment by nicolas-grekas** [comment]
OK, then the behavior maps to inlining: `Child` is inlined into `ParentA` so that `ParentA` ends up referencing `serializer`.

**Comment by edefimov** [comment]
In actual application the service chain is much more longer than this two services. And when the report says that missed dependency in the top-most service, to find out exact service causes an exception will look as hell.

**Comment by stof** [comment]
@nicolas-grekas would it make sense to split the logic into several passes ? First remove any unused private service (repeated pass, as today), then warn about invalid references, and then perform the inlining and another removal pass (simple pass, for services becoming unused because they were inlined, or maybe even removed by the inlining pass itself) ?
This way, warning about invalid references could still report the right id, as the inlining is not done yet, but we preserve the semantic of not warning for unused services.

Currently, removing unused services and inlining services is done by the same RepeatedPass IIRC, but I don't think that's necessary. Inlining won't create any new unused services (it will remove some service ids when inlining used services).

**Comment by mmoreram** [comment]
@nicolas-grekas then... https://github.com/symfony/symfony/blob/6d3f63d6f313faec3c102644bb2d2d7587bce30b/src/Symfony/Bundle/FrameworkBundle/Resources/config/test.xml
