### ISSUE TITLE
UndefinedMethodException on login after upgrade to 4.1.8

### ISSUE THREAD

**Issue by pulsesalessolutions** [symfony/symfony#29365]
**Version**
Symfony 4.1.8

**Description**
I am getting an UndefinedMethodException error when logging into 4.1.8 and wanted to highlight the issue.  I have reverted back to 4.1.7 and it's working fine but thought best to add it here to get explored.

"Attempted to call an undefined method named "getStorageKey" of class "Symfony\Component\Cache\DoctrineProvider"."

**How to reproduce**
It only happens if I log out and try to log back in again.  My login redirects the user to "@Route("/", name="dashboard")"

**Environments**
On 4.1.8 it's working fine on my local MAMP environment but not on my windows IIS8 PHP 7.1.14 environment, which has only appeared since the update.

Could be related to ticket "Routes with trailing slash broken after upgrade to 4.1.8"  #29363 

**Additional context**  
![screen shot 2018-11-28 at 14 49 29](https://user-images.githubusercontent.com/17827599/49159634-dd2abe80-f31c-11e8-90cd-0a093ba2a63c.png)

**Comment by nicolas-grekas** [comment]
Looks related to #29347 to me, fixed by #29349.

**Comment by pulsesalessolutions** [comment]
Thank you @nicolas-grekas, I can confirm that by disabling OPcache worked for me.

#29347 and @Sozialarchiv's answer.

**Comment by Sozialarchiv** [comment]
Thank you.
