### ISSUE TITLE
[PHPUnitBridge] Invalid default PHPUnit versions

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#29361]
**Symfony version(s) affected**: Many (under test suite for PHP 5.6-7.2)

**Description**  
PHPUnit maintainers probably changed tags convention and all tags in `X.Y` format were changed to `X.Y.0`. Since `symfony/phpunit-bridge` defines default PHPUnit versions in old format, we get such errors in CI pipelines (below for bridge `v3.2.0`):

```
$ ./vendor/bin/simple-phpunit $PHPUNIT_COVERAGE_FLAGS

Warning: fopen(https://github.com/sebastianbergmann/phpunit/archive/5.3.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 in /builds/<project>/vendor/symfony/phpunit-bridge/bin/simple-phpunit on line 41

Warning: stream_copy_to_stream() expects parameter 1 to be resource, boolean given in /builds/<project>/vendor/symfony/phpunit-bridge/bin/simple-phpunit on line 41
```

**How to reproduce**  
Use bridge <4.1.8 which download ZIP package instead creating project through Composer.

**Possible Solution**  
Change default versions to X.Y.Z format

**Additional context**  
Feel free to close it if you don't want to support older versions of bridge, but I think it wouldn't be BC break to make such fixed for each branch <4.1.

**Comment by xabbuh** [comment]
this was fixed by #29265 (which is part of 3.4.19 and 4.1.8)
