### ISSUE TITLE
symfony/console required symfony/debug with wrong version for composer

### ISSUE THREAD

**Issue by riconeitzel** [symfony/symfony#29379]
**Description**  

I'm working with a component that uses symfony/console and is running php5.6.

the component requires it via
```
    "require":{
        "php": ">=5.5",
        "eloquent/composer-config-reader": "2.*",
        "symfony/console": "^2.5|^3.0",
        "composer-plugin-api": "^1.0"
    },
```

symfony/console in [v3.4.19](https://github.com/symfony/console/blob/8f80fc39bbc3b7c47ee54ba7aa2653521ace94bb/composer.json#L21) requires symfony/debug

``` 
    "require": {
        "php": "^5.5.9|>=7.0.8",
        "symfony/polyfill-mbstring": "~1.0",
        "symfony/debug": "~2.8|~3.0|~4.0"
    },
```

while symfony/debug in it's latest [~4.0 Version](https://github.com/symfony/debug/blob/f9eea0cff99d14f97d69b24b17164098ece3fd32/composer.json#L18) requires at least php71

```
    "require": {
        "php": "^7.1.3",
        "psr/log": "~1.0"
    },
```

If you're working on a php56 project, it'll break.

`symfony/console` 3.x should require at max `symfony/debug 3.x`.

**How to reproduce**  

create a project, running php5.6, require symfony/console with `"symfony/console": "^2.5|^3.0",
`

**Possible Solution**  

`symfony/console` 3.x should require at max `symfony/debug 3.x`.

Best,
Rico

**Comment by xabbuh** [comment]
When you use PHP 5.6 to install dependencies and you did not explicitly configure a higher PHP version in the `platform` section of your project's `composer.json` file, Composer will take this into account and will not install the Debug component in version 4.

I guess that you either built the `composer.lock` file using a PHP version higher than 5.6 or that you have configured a higher PHP version using the `platform` config.

Anyway, there is nothing wrong in the dependencies here. So I am going to close. Thank you for understanding.

**Comment by riconeitzel** [comment]
You were (for sure) right about "built the composer.lock file using a PHP version higher than 5.6" … that file was rebuilt by someone else running a higher php version. Thanks again for your fast help :-)
