### ISSUE TITLE
[Config][YamlReferenceDumper] Dump reference configuration without comments

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#29372]
Hello everyone, I have already discussed with @ogizanagi about this on Slack and he recommended me to open an issue to get more input of Symfony core members and users.

**Description**  
Add an option to the `YamlReferenceDumper` to dump the configuration without any YAML comments.

**Use case**
I use the `YamlReferenceDumper` to dump a `Configuration` in a YAML file.
Then, I need to programmatically alter this dumped configuration (switching an `enabled` key from `true` to `false` for example) with a command.
The best way to do it I guess is to use the Symfony Yaml Component to parse the file, modify the value and then redump it.
The Yaml Component does not handle comments at all and will never do (cf https://github.com/symfony/symfony/issues/22516), so they are lost in the process.
They are useful but since they are going to be lost, I would rather not have them from the beginning for a better UX / DX => to not confuse the user.

**Questions**
Internally, this dumper is only used for the `config:dump-reference` command, is it intended to be used in user land ? Should it be maybe marked as internal ?
If it's not the case, is my case too specific to maintain a new option in this dumper ?

**Comment by stof** [comment]
Well, dumping comments is intended here, as the primary use case for this class is the `config:dump-reference`.
If you build your own workflow based on it and don't want the comment, you could do the Yaml parse/dump logic just after using it to strip the comments. I'm not sure it makes sense to introduce an option, as that use case seems quite specific here (in general, generating a config file based on the full reference is bad DX anyway, because most options have sensible defaults and so should no appear in the config file unless the project relies on non-default values due to an advanced use case)

**Comment by fancyweb** [comment]
> you could do the Yaml parse/dump logic just after using it to strip the comments

Thank you, that's a very good idea.

> generating a config file based on the full reference is bad DX anyway, because most options have sensible defaults and so should no appear in the config file

I disagree. IMHO, if a developer wants to modify a default config, it's easier to understand and to do it if the full file is already created with default values. This is what demand the minimum effort versus having to write the good keys structure and the value he/she wants to alter.

**Comment by stof** [comment]
@fancyweb but if they don't need to modify the config (which should be the common case for sensible defaults), having that config in their config file creates confusion, as they would still have to maintain their config file (and so to understand it).
Thus, it also means you cannot rely on smart defaults anymore (as you don't actually rely on defaults anymore, as all the config is specified in the config file). For instance, when installing Symfony component by component, FrameworkBundle auto-detects the `enabled` flags for most of its features based on the fact that the related component is installed. Copying the dumped reference to a config file would hardcode the enabled flags to the list of components installed at the time you ran the command, and any future component installation would not automatically enable it.

**Comment by fancyweb** [comment]
I must admit that you have changed my mind about the whole thing. Dumped defaults are not real defaults anymore.
I will reiterate on my use case.

I close the issue as I think having the behavior I have asked can be easily done with what you suggested in your first message.
