### ISSUE TITLE
Messenger Profiler throw error

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#29378]
**Symfony version(s) affected**: 4.2 RC1

**Description**  

Component profiler throws an error
**How to reproduce**  

Very simple message pushed to a rabbitMq bus, the debugger show activity, but clicking on it produces an error
![image](https://user-images.githubusercontent.com/619585/49264346-e6e71b80-f41b-11e8-9f39-f8df1fef0dda.png)

```

Neither the property "envelopeItems" nor one of the methods "envelopeItems()", "getenvelopeItems()"/"isenvelopeItems()"/"hasenvelopeItems()" or "__call()" exist and have public access in class "Symfony\Component\VarDumper\Cloner\Data".

    Exception Logs 1 Stack Trace 

Twig_Error_Runtime
in vendor/symfony/web-profiler-bundle/Resources/views/Collector/messenger.html.twig (line 139)
in var/cache/dev/twig/71/71049f60bf9f32be161806f2d9319efc25d64bddc3838247ea89717a15f25da5.phptwig_get_attribute (line 434)
in var/cache/dev/twig/71/71049f60bf9f32be161806f2d9319efc25d64bddc3838247ea89717a15f25da5.php->macro_render_bus_messages (line 254)
in vendor/twig/twig/lib/Twig/Template.php->block_panel (line 189)
in var/cache/dev/twig/53/5334e62e372079c0dcb78121a1ec27fcde1cb9ac47103dc66fbbef7e1c1a3a67.php->displayBlock (line 193)
in vendor/twig/twig/lib/Twig/Template.php->block_body (line 189)
in var/cache/dev/twig/51/51eb4662a50d48c78a6722299cede87fdbd4f1ef334dd97a19a7779f9b1ac933.php->displayBlock (line 51)
in vendor/twig/twig/lib/Twig/Template.php->doDisplay (line 390)
in vendor/twig/twig/lib/Twig/Template.php->displayWithErrorHandling (line 367) 
```
**Possible Solution**  

**Additional context**

**Comment by ogizanagi** [comment]
Hi @tacman, thanks for reporting.
This looks like you've got the 4.1 version of the `src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/messenger.html.twig` template.

I guess you just need to update the `symfony/web-profiler-bundle` as well to `4.2@RC`

**Comment by ro0NL** [comment]
should we add a conflict rule in webprofiler? Bumped into this as well :}

**Comment by xabbuh** [comment]
@ro0NL This won't help anymore, would it? If I don't miss anything, the conflict rule will only prevent you from updating to the next patch version of the WebProfilerBundle 4.1.

**Comment by ro0NL** [comment]
For updates done tomorrow it would prevent this no?

WDT 4.1: <4.2 messenger
WDT 4.2: >= 4.2 messenger

**Comment by xabbuh** [comment]
Hm indeed, anyone not having updated yet, could still benefit.
