### ISSUE TITLE
[Messenger] Feature request - Support for database transport

### ISSUE THREAD

**Issue by flackovic** [symfony/symfony#29388]
**Description**  
Feature Request - database (MySQL) as a messenger transport.
There are third party solutions ([Enqueue](https://github.com/php-enqueue/enqueue)) that introduce
database/doctrine-dbal transport, but it would be great if messenger had this by default.

**Comment by makasim** [comment]
Why would it be great?

**Comment by makasim** [comment]
There is a PR for a simple in hose solution - https://github.com/symfony/symfony/pull/29007

**Comment by flackovic** [comment]
@makasim because we could use database as queue? 
Oh, did not see that PR, was searching issues and saw there is no mention of it. 👍

**Comment by makasim** [comment]
Let me clarify it, Why would it be better to have something in-house instead of using already existing 3rd party solution?

**Comment by flackovic** [comment]
Because it would require one less package, and it would be inside symfony "ecosystem". At least it feels "cleaner" if it is built right into the component.

**Comment by flackovic** [comment]
Closing issue as there is already PR (#29007) introducing this feature, as @makasim pointed out.
