### ISSUE TITLE
Symfony 4.2 - Injecting security voter into another service type-hinting mismatch.

### ISSUE THREAD

**Issue by silverbackdan** [symfony/symfony#29385]
**Symfony version(s) affected**: 4.2

**Description**  
Since upgrading from Symfony 4.1 to 4.2, if I type hint a service argument as my security voter, I get a type-hint mis-match as what is actually injected is a `TraceableVoter`.

**How to reproduce**  
Inject a `voter` service (which is created using the following article: https://symfony.com/doc/current/security/voters.html#creating-the-custom-voter) into another service with auto-wiring.

**Possible Solution**  
Do not inject voters into other services - perhaps this is best practice - I wanted to use the same `supports` method from the voter in another `AccessSubscriber` event subscriber for ApiPlatform. I will instead extract the `supports` method to be used both the voter and the event subscriber for now.

**Comment by silverbackdan** [comment]
@ro0NL You're right really - it was a hack really, just nice not to have to redefine the `supports` check so I suppose I abused that. I'll close the issue, but at least there is this chain here if someone else comes across the issue. Thanks for the prompt response!

**Comment by silverbackdan** [comment]
Oh and also, thanks for the workaround! I decided not to inject the voter but instead just to put the `supports` checker in a new class for both services to use.

**Comment by maartendekeizer** [comment]
Same issue here.
We are injecting the Voter directly into a controller to check a specific voter decission. So we can give information to the user about specific restrictions and to start other application logic.

**Comment by johandouma** [comment]
Similar situation to @maartendekeizer; I have an app where I inject voters to get the particular restrictions, eg why something is granted or not granted.

**Comment by ro0NL** [comment]
See #29721

**Comment by florentdestremau** [comment]
I am a in the midst of migrating from 3.4 to 4.2 and decided to go up to 4.1.9 for this reason, very glad to see that I won't be forced too soon to refactor a dozen of controllers and services :smiley: 

@ro0NL what you mean is that one should only use the `AuthorizationCheckerInterface::isGranted` method for using voters and thus never injecting them directly anywhere in your code ? I guess I could export some handy methods out in a "VoterHelper" service or so, but I don't see why it's such a bad practice to simply inject the voter that is meant for this reason.

**Comment by florentdestremau** [comment]
Understood, so the bad practice here is considering the methods of a Voter other than `vote`, and because this method is called only through `AuthorizationCheckerInterface::isGranted`, the Voter should never be called, if I understand correctly. I am in a situation similar to @maartendekeizer where I redirect users to according pages depending on their access levels so I guess it's an edgy case...
