### ISSUE TITLE
[Profiler] Grouped deprecations from different packages hide useful info

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony#29392]
**Symfony version(s) affected**: 4.2.0

**Description**  

When there are deprecations with same message, they are all grouped into one even if they are caused by different packages.

![image](https://user-images.githubusercontent.com/353372/49300500-af7f7a00-f4c2-11e8-9103-91c8e33385f6.png)

I've already fixed two packages (https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/594 https://github.com/mhujer/JavaScriptErrorHandlerBundle/pull/7), but I would prefer to see all the deprecations at once instead of getting only one. The screenshot shows the third package that appeared only after I fixed the first and then the second.

**Possible Solution**  
Make the text _(5 times)_ clickable and it would unfold all deprecations that are grouped into this row.

**Comment by nicolas-grekas** [comment]
Hello, the reason why it's grouped is performance: if we collect individual items per deprecation, the memory will explode and performance in dev mode will be horrible. I know because we made it how it to fix such issues.

**Comment by mhujer** [comment]
@nicolas-grekas That makes sense, thanks for the explanation!
