### ISSUE TITLE
[DI] Override imported service in another file

### ISSUE THREAD

**Issue by ottaviano** [symfony/symfony#29402]
**Symfony version(s) affected**: 3.4.18

**Description**  
Hello, maybe it isn't a real bug, but the desired behavior, so sorry if that.
The services that are imported in main services.yaml file with `resource:` can't be overridden in another file.

**How to reproduce**  
Ex. `App\Foo\Bar` will be imported by services.yaml
```
# services.yaml
App\:
        resource: '../src/*'
```

and if I want to add a DI tag to my service in another config file, it will not work:
```
# bar_services.yaml

App\Foo\Bar:
  tags: [custom.tag]
```

`bin/console debug:container App\Foo\Bar` will display: `Tags: -`

**Comment by stof** [comment]
be careful about the order in which files are loaded.
If you use a glob resource to load all files from a directory, they are loaded in alphabetical order, so `bar_services` is loaded *before* `services`, not after it (and so it does not override the definition, but gets overridden).

**Comment by ottaviano** [comment]
indeed, in the good order, the service `Bar` is overridden, thank you @stof.
