### ISSUE TITLE
CollectionType with by_reference: false deletes all relations

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#29429]
Symfony version(s) affected: 4.1.8, not affected until 4.1.2 (I do not know about versions in between) also 4.2.0 is not affected

I use `CollectionType` in a form and it is configured with 
````
'allow_add' => true,
'allow_delete' => true,
'by_reference' => false,
````

When I submit the form all child entities are deleted!
The bug occurred with a OneToMany Relationship, I do not know whether ManyToMany relations are also affected or not.

[Reproducer](https://github.com/Shoplifter/Symfony-Issue-29429)

Another thing that changed is that I used to type cast the parameter for the setter method of a OneToMany relation with `ArrayCollection`, which also worked out in V.4.1.2 but fails in 4.1.8. The setter is getting a `PersistenCollection` and throws an error. Not a big thing, but maybe that's related to the bug?

**Comment by nicolas-grekas** [comment]
Thanks for the confirmation.
No ETA yet - in one month the latest - might happen earlier as there are some nasty issues into the wild :)

**Comment by David-Crty** [comment]
For info I'm having the exact same issue on `3.4.19`, rolling back to `3.4.18` solve it.
