### ISSUE TITLE
Segfault in development web server

### ISSUE THREAD

**Issue by agathver** [symfony/symfony#29423]
**Symfony version(s) affected**: 4.1.*

**Description**  
If there is a conflict between the path component in route annotations of two controllers (by error, or merge conflicts as in my case), the built-in server crashes with a SEGFAULT.

**How to reproduce**  
PHP: PHP 7.2.10-0ubuntu0.18.04.1 (installed from Ubuntu repository)
OS: Ubuntu 18.04.1

1. Create a new Symfony project
2. Make 2 new controllers
3. Edit them to have the same route (in my case both had "/{id}")
4. Start built-in web server `./bin/console server:run`
5. Send the request to 127.0.0.1:8000
6. Process crashes with signal 11

Whether it is a Symfony bug or PHP bug, I'm not sure.

**Comment by sstok** [comment]
Can you follow the instructions described here https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs and provide a ready to use project that produces this problem? this will make easier for anyone to test this and debug de problem. Thanks.

**Comment by nicolas-grekas** [comment]
There is a high chance this is the same issue that many people already reported in recent days.
The fix is already merged, please try `4.1@dev` if you want to confirm.
Closing meanwhile, thanks for reporting.
