### ISSUE TITLE
[Messenger] Introduce handle method on MessageBusInterface instead of Trait

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#29428]
**Description**  
This issue is related to the PR #29167 and #28983, which I believe does not solve the recent changes in the Messenger component.

There should be a `handle` method on the `MessageBusInterface` itself, which I believe is a better solution than introducing a Trait. Using said Trait comes with a set of limitations that I believe can be solved by adding previous functionality back to the `MessageBusInterface`.

- Using the Trait forces you to use `$messageBus` as the property name, before you were able to name it to your liking, such as `$commandBus` or `$queryBus`, which makes more sense from a semantical point of view.
- The Symfony Profiler component does no longer show the count of messages handled by a bus, due to binding now being impossible, thanks to the enforced property naming in the `handle()` method of the Trait.
- It seems odd to inject a `MessageBusInterface`, for instance in a Controller, which then also needs to use `HandleTrait`. It should be as simple as calling `$this->queryBus->handle(new Query());`
(Edit: Alternatively I have to create my own QueryBus that uses the `HandleTrait`, which should not be needed since my Framework already offers a working Bus and also causes confusion where that Trait should actually be used.)
- Introducing a Trait still does not resolve the issue of having no return type. The same issue still remains, but now more problems have resulted due to the change.

I understand the issue with return types, as discussed in the PR mentioned above, however the current implementation seems to be too focused on solving a specific issue, which might not need to be solved at all.
Regarding the [explanation of implementing your own QueryBus](https://github.com/symfony/symfony-docs/pull/10715/) from this PR, again, I believe this is going out of the way of how things should work. I think sacrificing not having a return type on the `handle` method is an acceptable trade-off here.

**Example**  
I propose to (re)introduce a `handle()` method on the `MessageBusInterface`, which will solve the issues mentioned above, as well as make it simpler to use. The `HandleTrait` can be removed again, and the logic from within the `handle` method would be moved back into the `MessageBus` implementation.

```php
interface MessageBusInterface
{
    /**
     * Dispatches the given message.
     *
     * @param object|Envelope $message The message or the message pre-wrapped in an envelope
     */
    public function dispatch($message): Envelope;

    /**
     * Handles the given message.
     *
     * @param object|Envelope $message The message or the message pre-wrapped in an envelope
     *
     * @return mixed The value returned by the handler
     */
    public function handle($message);
}
```

**Comment by luzivenom** [comment]
I have been struggling with the same problem. I thought the MessageBus was a great way to implement queries. I just found out today that I need to use a Trait now.

**Comment by hacked** [comment]
@luzivenom You're not forced to use the Trait, you could implement the logic yourself. For instance, you could do something like this (Which is similar to how it is implemented at the moment)
```php
$envelope = $this->queryBus->dispatch($message);
$handledStamps = $envelope->last(HandledStamp::class)->getResult();
```
I just think that it's a step backwards from previously being able to do
```php
$this->queryBus->dispatch($message);
```
which could now simply become
```php
$this->queryBus->handle($message);
```

**Comment by jvasseur** [comment]
Regarding points 2 and 3 (and maybe 1 to) if think your are not supposed to use the trait inside controllers, instead you should create your own `QueryBus` class by using the trait and then inject this class into your controllers.

**Comment by TomWotaWun** [comment]
@jvasseur Idk about creating my own Bus. I agree with @hacked that it seems odd to create my own bus which uses another bus to do what my framework should be doing in the first place. I saw that @ogizanagi mentioned in #29167 that he wants to add a base class. Would that help with this?

**Comment by nicolas-grekas** [comment]
@jvasseur got it 100% right. The job of a framework is to encourage maintainable practices. Having a public method that takes any object and that returns an unspecified value with a pluggable implementation doesn't belong to that description. What the trait provides is an implementation that may helps implement a query/command bus - you can copy/paste it if the exact details of its implementation don't fit your style. And in any way, in you code, you should *really* declare both a more specific argument type AND return type. The component cannot help here, only *you* know what to declare.

**Comment by nicolas-grekas** [comment]
Closing as explained.
