### ISSUE TITLE
[Bug][BC break][Form] getExtendedTypes is suddenly required

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#29426]
**Symfony version(s) affected**: 4.2.0

**Description**  
[The SonataAdminBundle build breaks](https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/462425809#L826) because we have form types that suddenly need to implement `getExtendedTypes()`. This lines seems to assume the method exists when it actually does not:

https://github.com/symfony/symfony/blob/010556239d9c597ed5fb5e71bf046e1eda7e4d5a/src/Symfony/Component/Form/Tests/Fixtures/TestExtension.php#L49

**How to reproduce**  

```
git clone git@github.com:sonata-project/SonataAdminBundle.git
cd SonataAdminBundle
git checkout 437ed2a9aa09fac6bef66abeaf1e5eeb9b32796d
composer install
wget -O phpunit https://phar.phpunit.de/phpunit-5.phar
chmod +x phpunit
./phpunit tests/Form/Type/AdminTypeTest.php
```

**Possible Solution**  
~~Provide a default implementation for that method, that would check if `getExtendedType()` is overriden in the child class, and trigger a deprecation if it is the case, call it and wrap the result in an array.~~

That cannot work since the new method has to be static…

**Comment by greg0ire** [comment]
cc @xabbuh

**Comment by jvasseur** [comment]
Classes inside `Tests` directories souldn't be used outside of Symfony tests so this isn't a BC break.

If this class is really useful for tests outside the framework it sould be moved to the `Test` namespace that contains testing utilities and the become part of the BC policy.

**Comment by greg0ire** [comment]
You're right! Maybe these shouldn't be part of the zip archives so as not to encourage such things?
