### ISSUE TITLE
[Cache] Memcached adapter clear() does nothing

### ISSUE THREAD

**Issue by raitocz** [symfony/symfony#29435]
**Symfony version(s) affected**: 4.*

**Description**  
Memcached adapter returns false on clear(). Does not actually do the cache clearing.

**How to reproduce**  
Use Cache component, create some cache keys in Memcached and then try to do clear() on Memcached adapter. Always returns false.

Actual code of memcached trait:
```php
protected function doClear($namespace)
{
    return false;
}
```

**Possible Solution**  
Add $this->getClient()->flush(); on Memcached adapter trait.

**Additional context**

**Comment by nicolas-grekas** [comment]
On clear, invalidation happens by incrementing the version number that is used to prefix the keys.
Old items stay in memory, but memcache's LRU will reclaim the memory in the end.
No bug here AFAIK.

**Comment by raitocz** [comment]
(sorry, dunno if we should discuss under PR or here):
@nicolas-grekas But if you pass option to not use versioning?

```php
$adapter = new MemcachedAdapter($client, $namespace);
$adapter->enableVersioning(false);
```

**Comment by nicolas-grekas** [comment]
(let's discussion on the PR)
