### ISSUE TITLE
Empty output for debug:autowiring

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#29442]
**Symfony version(s) affected**: 4.2

**Description**  
If I run `debug:autowiring` in the Symfony Demo app (which uses Symfony 4.2) I only see an empty output instead of something like https://github.com/symfony/symfony/pull/28970.

Other users on Symfony's Slack confirmed the same behaviour.

**Comment by chalasr** [comment]
Confirmed, the command outputs nothing because because you don't have `phpdocumentor/reflection-docblock` installed, which should not be a requirement for using the command. 
Looking at it.
