### ISSUE TITLE
[PropertyInfo][BC Break] Attempted to call an undefined method named "isInitializable" 

### ISSUE THREAD

**Issue by skalpa** [symfony/symfony#29440]
**Symfony version(s) affected**: 4.2.0

**Description**  
4.2.0 attempts to call `isInitializable()` on my extractor that doesn't implement `PropertyInitializableExtractorInterface`.
Probable caused by the @dunglas changes in #26997

**How to reproduce**  
I have a custom `ReflectionExtractor` service that decorates the default one:
```yaml
MyNamespace\ReflectionExtractor:
    decorates: property_info.reflection_extractor
```

```php
class ReflectionExtractor implements PropertyListExtractorInterface, PropertyTypeExtractorInterface, PropertyAccessExtractorInterface
{
}
```
It used to work before 4.2.0, but I now get an `UndefinedMethodException` because it doesn't have an `isInitializable()` method.

**Possible Solution**  
I haven't checked further, but it seems to be a problem with the configuration: my extractor is injected in the `$initializableExtractors` constructor argument of `PropertyInfoExtractor`, even though it doesn't implement `PropertyInitializableExtractorInterface`.

**Comment by skalpa** [comment]
It's called from [`PropertyInfoExtractor::extract()`](https://github.com/symfony/symfony/blob/974b98b17b02252064485da48238f1c1bbb5e199/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php#L98). 

As I said, the problem is that `$this->initializableExtractors` contains my service, while as far as I understand it shouldn't be here as it does not implement your new interface.
(Sorry, I'd fix it myself it I had time, but I'm too busy right now. Also it takes 30 seconds to work around it so it's not of the highest priority, even if it's still a bug).


Here's the relevant part of the trace:
```
in PropertyInfoExtractor.php line 109
--
at PropertyInfoExtractor->extract(object(RewindableGenerator), 'isInitializable', array('Company\\Domain\\User\\Command\\LenderRegisters', 'result', array()))in PropertyInfoExtractor.php line 98
at PropertyInfoExtractor->isInitializable('Company\\Domain\\User\\Command\\LenderRegisters', 'result', array())in PropertyInfoPropertyMetadataFactory.php line 72
at PropertyInfoPropertyMetadataFactory->create('Company\\Domain\\User\\Command\\LenderRegisters', 'result', array())in InheritedPropertyMetadataFactory.php line 40
at InheritedPropertyMetadataFactory->create('Company\\Domain\\User\\Command\\LenderRegisters', 'result', array())in AnnotationPropertyMetadataFactory.php line 46
at AnnotationPropertyMetadataFactory->create('Company\\Domain\\User\\Command\\LenderRegisters', 'result', array())in ExtractorPropertyMetadataFactory.php line 45
```

**Comment by gusdecool** [comment]
This issue happened to me while I'm using Symfony v6.4.7.
Running `composer update` and upgrade to Symfony v6.4.8 fixed the issue for me.
