### ISSUE TITLE
[messenger][DX] restart consumer when code changed in debug mode

### ISSUE THREAD

**Issue by mathroc** [symfony/symfony#29451]
Hi,

when working, it would be nice if the consumer would restart automatically when code (or configuration, etc.) has been updated

I've tried to write a middleware that would check if the cache is fresh and stop the command if not (in my case docker-compose would restart it) but I don't know how to check for that

here is what I tried:

```php
<?php declare(strict_types=1);

namespace App\Messenger;

use Symfony\Component\Config\ConfigCache;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Middleware\MiddlewareInterface;
use Symfony\Component\Messenger\Middleware\StackInterface;

class CodeChangedMiddleware implements MiddlewareInterface
{
    /** @var Kernel */
    private $kernel;

    public function __construct(KernelInterface $kernel)
    {
        assert($kernel instanceof Kernel);
        $this->kernel = $kernel;
    }

    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        if (!$this->cacheIsFresh()) {
            throw new \RuntimeException("Restarting consumer to update cache");
        }

        return $stack->next()->handle($envelope, $stack);
    }

    private function cacheIsFresh(): bool
    {
        // trying to mimick what's happening at the beginning of Kernel::initializeContainer
        $ro = new \ReflectionObject($this->kernel);
        $getContainerClass = $ro->getMethod("getContainerClass");
        $getContainerClass->setAccessible(true);

        $class = $getContainerClass->invoke($this->kernel);

        $warmupDirProperty = $ro->getParentClass()->getProperty("warmupDir");
        $warmupDirProperty->setAccessible(true);
        $cacheDir = $warmupDirProperty->getValue($this->kernel) ?: $this->kernel->getCacheDir();

        $debugProperty = $ro->getProperty("debug");
        $debugProperty->setAccessible(true);
        $cache = new ConfigCache("$cacheDir/$class.php", $debugProperty->getValue($this->kernel));

        return $cache->isFresh();
    }
}
```

but this cache is always fresh

Do you think this is something worth integrating into symfony ? (maybe directly into the consumer command instead)

and, any idea why the middleware I wrote does not detect code changes ?

**Comment by Simperfit** [comment]
@weaverryan is this fixed ?

**Comment by weaverryan** [comment]
It is not, but is interesting.

**Comment by fabpot** [comment]
I think this should happen outside the command, and so outside of Symfony. Could be an interesting feature of the Symfony CLI (adding to our backlog).

**Comment by ruudk** [comment]
You can run the consumer with supervisor and set-up a message limit with `--limit=1`. After every message, the consumer will be restarted. You can also use `--time-limit=10` to restart after 10 seconds :)

**Comment by mathroc** [comment]
I’m trying something new with a compiler pass that sends a restart signal to the consumers:

```php
<?php declare(strict_types=1);

namespace App\Infra\Messenger\DependencyInjection;

use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\Messenger\EventListener\StopWorkerOnRestartSignalListener;

class MessengerRestartConsumerCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        /** @var CacheItemPoolInterface */
        $cachePool = $container->get("cache.messenger.restart_workers_signal");

        $cacheItem = $cachePool->getItem(StopWorkerOnRestartSignalListener::RESTART_REQUESTED_TIMESTAMP_KEY);
        $cacheItem->set(microtime(true));
        $cachePool->save($cacheItem);
    }
}
```

this compiler pass is only registered in dev

**Comment by arjanfrans** [comment]
@mathroc How does that work?

When I register the CompilerPass I get the following error: `Constructing service "cache.messenger.restart_workers_signal" from a parent definition is not supported at build time.`

**Comment by WolfgangDrescher** [comment]
In case anyone is still looking for a solution to this problem: I just found out in the Symfony 5 book «The Fast Track» that this is now possible if you are using the `messenger:consume` command over the Symfony CLI:

```
$ symfony run -d --watch=config,src,templates,vendor symfony console messenger:consume async
```

Checkout https://symfony.com/doc/current/the-fast-track/en/18-async.html#running-workers-in-the-background for more informations and how to kill the daemon.

**Comment by curry684** [comment]
That should definitely be a part of the Messenger documentation.
