### ISSUE TITLE
[Lock] RedisStore TTL ignored

### ISSUE THREAD

**Issue by fpilee** [symfony/symfony#29458]
**Affected versions** 
"symfony/lock": "^4.2"
"symfony/lock": "4.1.8"
"symfony/lock": "4.0.*"
"symfony/lock": "3.4.*"
etc

**Description**  
I'm trying to pass a initial TTL to the RedisStore, I set to 1200 (20 minutes) but I can check that the default value (300 sec) is used. RedisStore is ignoring ttl argument. 

**How to reproduce**  

```php
<?php


require_once __DIR__ .'/vendor/autoload.php';

use Symfony\Component\Lock\Factory;
use Symfony\Component\Lock\Store\RedisStore;


$redis = new \Redis();
$redis->connect('localhost');

$store = new RedisStore($redis,1200); //20 minutes
$factory = new Factory($store);

$lock = $factory->createLock('pdf-invoice');

if ($lock->acquire()) {

    echo 'adquired' . PHP_EOL;
    // The resource "pdf-invoice" is locked.
    sleep ( 1200);
    $lock->release();
}else{
    echo 'unadquired' . PHP_EOL;
}
```

```sh
redis-cli
ttl pdf-invoice
(integer) 295
```

**Possible Solution**  
No Idea.

**Comment by fpilee** [comment]
memcached doesn't work neither

**Comment by fpilee** [comment]
The confusion is the __construct() method, why it accepts a TTL if is not used ? 
```php
public function RedisStore::__construct($redisClient, float $initialTtl = 300.0) : RedisStore
```

To set the TTL correctly it have to be added here

`$lock = $factory->createLock('pdf-invoice', 1200);
`

**Comment by walva** [comment]
Is it still relevant today ?
