### ISSUE TITLE
Issue After Upgrade Symfony 3.4 To Symfony 4.1

### ISSUE THREAD

**Issue by parthiv2585** [symfony/symfony#29460]
Hi All ,
I have upgrade my application in symfony3.4 To symfony 4.1. 
After up gradation below commands are not working.

(1) php bin/console generate:bundle
(2) php bin/console build:model

I have use Propel ORM.

Please help me to fixed this issue.

Thanks 

Parthiv Shah

**Comment by xabbuh** [comment]
What do you mean with "the commands are not working"? What happens? What errors do you get?

**Comment by parthiv2585** [comment]
Hi 
Thanks for reply. 
(1) php bin/console generate:bundle
Error : There are no commands defined in the "generate"  namespace.

Thanks 

Parthiv Shah

**Comment by xabbuh** [comment]
@mbabker is right. I am closing as explained. Thank you for understanding.
