### ISSUE TITLE
Is there a reason not to use escapeshellarg in Process

### ISSUE THREAD

**Issue by tomasfejfar** [symfony/symfony#29469]
I've noticed that `\Symfony\Component\Process\Process::escapeArgument` does not use php's native `escapeshellarg` function, but rather implements escaping in userland. That does not take advantage of potential security fixes in PHP itself. 

Is there a reason why it's not using it?

**Comment by apfelbox** [comment]
See discussion in https://github.com/symfony/symfony/pull/21347

**Comment by tomasfejfar** [comment]
Thx.
