### ISSUE TITLE
PHPUnit Bridge installs without using paralled downloader

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#29468]
**Symfony version(s) affected**: 4.1.8

**Description**  
Symfony Flex shipped with parallel  downloader which speed-up installation of the project https://github.com/symfony/flex/blob/master/src/ParallelDownloader.php . But when PHPUnit Bridge installs PHPUnit with dependencies - this parallel downloader not uses.

**How to reproduce**  
1. Install Symfony `composer create-project symfony/website-skeleton my-project` + test-pack
2. `php vendor/bin/simple-phpunit -c tests/phpunit.xml`
3. got some output like:
```
> php vendor/bin/simple-phpunit -c tests/phpunit.xml
Installing phpunit/phpunit (6.5.13)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.13): Downloading (100%)
Created project in phpunit-6.5
symfony/yaml is not required in your composer.json and has not been removed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 23 installs, 0 updates, 0 removals
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (2.0.2): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.3.2): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (5.0.10): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.1.3): Downloading (100%)
  - Installing symfony/phpunit-bridge (6.5.99): Symlinking from /var/www/service/vendor/symfony/phpunit-bridge
```

**Comment by nicolas-grekas** [comment]
When flex is installed globally, then the // downloader is used, isn't it?
If confirmed, I think we can close this PR.

**Comment by Koc** [comment]
Will check later, but setup doc doesn't say that Flex should be installed globally:
* https://symfony.com/doc/current/setup.html
> Create your new project by running: `composer create-project symfony/website-skeleton my-project`

* https://symfony.com/doc/current/setup/flex.html
> 1. Install Flex as a dependency **of your project**: `composer require symfony/flex`

**Comment by nicolas-grekas** [comment]
Installed globally, Flex will not install recipes, that's why you need it in your project.
But when installed globally, it will still provide the // downloader.

**Comment by KonstantinCodes** [comment]
I can confirm, that this interesting behaviour slows down the heroku test pipeline by 10+ seconds on every run.

**Comment by nicolas-grekas** [comment]
The solution has been provided: install flex globally.
