### ISSUE TITLE
Attempted to load class "ConstraintValidator" from namespace "Symfony\Component\Validator". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by engharb** [symfony/symfony#29470]
**Symfony version(s) affected**: v4.1.4

**Description**  
I tried to install packages using composer. The symfony/form_v4.1.4 and symfony/validator_v4.1.4 are installed successfully. Suddenly I got 
```
Attempted to load class "ConstraintValidator" from namespace "Symfony\Component\Validator".
```
I checked vendor file and I found that this class in not installed or exists at all.

**How to reproduce**  
in VM
```
$ composer install
```

** Environment **
Mac OS High Sierra 10.13.1,
Homestead and vagrant: latest versions

**Comment by engharb** [comment]
The problem is solved. I just upgrade MacOS to 10.13.6.
I'm not sure why such conflict happens time to time.

**Comment by xabbuh** [comment]
Let's close here then as there is nothing left to do.
