### ISSUE TITLE
[symfony/http-foundation] Request parse_url issue with double slashes

### ISSUE THREAD

**Issue by arku31** [symfony/symfony#29478]
**Symfony version(s) affected**: 3.4.19 (master  v4.2.0  v4.2.0-RC1 v4.1.8 v3.4.19 should be affected as well)

**Description**  
_This commit causes the problem - https://github.com/symfony/http-foundation/commit/fbf03645a8cc45aab9ffc75fff64741797b23ce4#diff-7edb274bc39ed8c493badba7dd278826_

In case of the wrong server configuration, REQUEST_URI could equal to "//api/v1/request"

The result of parse_url in this case is [path] => /v1/request, what is wrong ('/api' is missing).

From one point this is definitely the server misconfiguration but from another point - it works fine in 3.4.18. In most cases, it leads to 404 for routes what previously worked fine.
I think this problem could be popular and should be fixed even that it's not really a problem on your side.
**How to reproduce**  
Easy way is to temporarily hardcode $requestUri equal to "//api/v1/request" on line 1840 in Request.php (link below).
The hard way is to do wrong nginx setup :)

**Possible Solution**  

Do not use parse_url :)

**Comment by alquerci** [comment]
Thank you @arku31 for creating this bug report! This indeed looks
like a bug. I reproduced the bug with a fresh `symfony/website-skeleton` running with docker `php:7.1-apache`.

A `curl http://localhost//foo/bar` lead to `No route found for "GET /bar"`.

Status: Reviewed

**Comment by danijelk** [comment]
Have the same issue, took some time to dig down and find it, any ETA on release?

**Comment by alquerci** [comment]
Thank you @danijelk for your concern, to speed up further you can help to [code review][0] the PR #29494.

As I see for now it mostly depends on the availability of a merger.

[0]: https://symfony.com/doc/current/contributing/community/reviews.html#the-pull-request-review-process

**Comment by acacha** [comment]
Also affected by this issue
