### ISSUE TITLE
[Constraints] Valid does not work as expected

### ISSUE THREAD

**Issue by TerjeBr** [symfony/symfony#29484]
**Symfony version(s) affected**: 3.4

**Description**  
When you normally specify validation groups on a constraint, that defines which groups this constraint will be active under.

But the "Valid" constraint does not follow this pattern, here the groups instead defines which groups the sub-resource will be validated with.

This is two conflicting uses of the "groups" keyword.

What is more serious, and my real gripe, is that it is no way to specify both of these things for the "Valid" constraint.
Sometimes you want the groups that decides when the "Valid" constraint should be invoked to be different form the groups to be passed down as effective "groups" doing the sub-resource validation.

https://github.com/symfony/symfony/issues/17622 would have solved this but it was closed down.

https://github.com/fluoresceco/validate-embedded is also a solution to this problem.

Could we please have a way in the symfony core to both specify the groups that defines *when* the "Valid" constraint applies, and the groups that should be *used* when validating the sub-entity in question?

**Comment by xabbuh** [comment]
> When you normally specify validation groups on a constraint, that defines which groups this constraint will be active under.
>
> But the "Valid" constraint does not follow this pattern, here the groups instead defines which groups the sub-resource will be validated with.

Can you create a small example application that allows to reproduce this behaviour? If that's the case, this look like a bug to me. The `Valid` constraint should only be evaluated when validation happens in this/these group/s and should then forward the group being validated in to the nested validator calls.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
