### ISSUE TITLE
Running CLI command with twig cause extension error.

### ISSUE THREAD

**Issue by do-web** [symfony/symfony#29508]
**Symfony version(s) affected**: 4.1

**Description**  
If i run a cli command that renders a twig template with an added extension, i get an error that the extension is loaded.

```
Unable to register extension "Twig_Extension_Sandbox" as extensions have already been initialized.
```

This happend with all twig extensions i try to load and run on a cli command.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by do-web** [comment]
I have found the problem, i injecting another service that also uses twig.
