### ISSUE TITLE
Symfony 4.2 Deprecated configuration in maker bundle

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#29511]
**Symfony version(s) affected**: 4.2.1

**Description**  
I am gettinbg this deprecation message

> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

**How to reproduce**  
I guess that pops up if you have just installed the maker bundle

**Possible Solution**  
As described in the [docs](https://github.com/symfony/symfony/blob/4.2/UPGRADE-4.2.md#config) replace [L24,25](https://github.com/symfony/maker-bundle/blob/master/src/DependencyInjection/Configuration.php#L24) with
````
$treeBuilder = new TreeBuilder('maker');
$rootNode = $treeBuilder->getRootNode();
````

**Additional context**  
![image](https://user-images.githubusercontent.com/1181094/49685189-7c9b3e80-fadf-11e8-9cde-6dd26d37b50f.png)

**Comment by xabbuh** [comment]
The MakerBundle is not part of the Symfony core and has [its own repository](https://github.com/symfony/maker-bundle). It seems like the issue you describe is dealt with in symfony/maker-bundle#324. So I am going to close here in favour of that PR. Thank you for understanding.
