### ISSUE TITLE
[Symfony3.4] add 'property' tags to CacheItem comment

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#29524]
**Description**  
Protected properties in the CacheItem class may cause phpstorm (or some other IDEs) to display an error tip.

Every time I read the code of the CacheItem class, I must to restart phpstorm to eliminate those error tips.

**Example**  

    /**
     * @author Nicolas Grekas <p@tchwork.com>
     * @property $key
     * @property $value
     * @property $isHit
     * @property $defaultLifetime
     * @property ...
     */
    final class CacheItem implements CacheItemInterface
    {
        ...
    }

Thanks.

**Comment by xabbuh** [comment]
I don't see any such error in PhpStorm. Can you explain a bit what looks suspicious on your end?

**Comment by zacharyzh** [comment]
"Member has protected access"

My phpstorm looks like unable to recognize Closure.

**Comment by zacharyzh** [comment]
Those error tips are in AbstractAdapter's constructor.

    $item = new CacheItem();
    $item->key = ...

**Comment by chalasr** [comment]
Phpstorm does not play well with `\Closure::bind()` indeed, but we cannot add some hacks just to please IDEs (these properties aren’t public, IDEs must not consider them public since one could be tempted to access them from a different scope). This should be reported and fixed on phpstorm, not symfony :)

**Comment by nicolas-grekas** [comment]
Closing as explained. That's a phpstorm issue, not a Symfony one.

**Comment by nicolas-grekas** [comment]
But we are not using `__get`+`__set` here ;)

**Comment by zacharyzh** [comment]
https://youtrack.jetbrains.com/issue/WI-29871

The Closure issue has been submitted to JetBrains about 3 years ago and not been resolved so far (same issue may also exists in other IDEs). 

If you don't want phpstorm to prompt any private properties, you can use the magic methods instead. 

    class CacheItem implements CacheItemInterface
    {
        ...
        public function __get($n)
        {
            throw new CacheException( ... );
        }
        
        public function __set($n, $v)
        {
            throw new CacheException( ... );
        }
        ...
    }
