### ISSUE TITLE
What is the sense in the array check in ErrorHandler.php, Line 590?

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/symfony#29536]
**Symfony version(s) affected**: all

**Description**  
I can't understand the code

**How to reproduce**  
There is code in symfony/debug/ErrorHandler.php, Line 590 which I can not understand. Am I wrong or the code? The check !\is_array($handler) seems senseless to me because it can never be an array.

        $handler = self::$reservedMemory = null;
        $handlers = array();
        $previousHandler = null;
        $sameHandlerLimit = 10;
        while (!\is_array($handler) || !$handler[0] instanceof self) {
            $handler = set_exception_handler('var_dump');
            restore_exception_handler();
            if (!$handler) {
                break;
            }
            restore_exception_handler();
            if ($handler !== $previousHandler) {
                array_unshift($handlers, $handler);
                $previousHandler = $handler;
            } elseif (0 === --$sameHandlerLimit) {
                $handler = null;
                break;
            }
        }

**Comment by michaelKaefer** [comment]
@nicolas-grekas Thank you for an answer.

**Comment by Taluu** [comment]
From what I can understand, it tries to stack all the handlers (and their previous ones) until it gets the debug's error handler. So that it can act on all these handlers when reporting an error, but I don't remember the rest :D

**Comment by nicolas-grekas** [comment]
The handler can also be a closure or a string (a global PHP function).
Closing as there is no bug to keep track of.
