### ISSUE TITLE
[Form][RFC] Improve CollectionType Rendering

### ISSUE THREAD

**Issue by Shoplifter** [symfony/symfony#29540]
**Description**  

- Imo a collection type form row should rather be rendrered as a fieldset containing a legend, than as div containing a label. [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form-associated_content) lists these elments as "labelable": `<button>`, `<input>`, `<keygen>`, `<meter>`, `<output>`, `<progress>`, `<select>`, and `<textarea>.` So labels of CollectionTypes cannot be associated with any form element. Though this is not discouraged by the HTML5 specs, WCAG2.0 Specs seem to imply, that labels should always be associated with form controls, whereas it is the purpose fo fieldset and legend to privide a description for groups fo form controls. E.g. H90: [Indicating required form controls using label or legend](https://www.w3.org/TR/WCAG20-TECHS/H90.html)
- set the default value of `entry_options.label` to `false`. That's probably what you will do explicitly all the time anyways. (Instead fo having a humanized string of the loop index as default)

**RFC**
Should this be applied not only to collection types, but also to (other) compound types as  date/time widgets (if not rendered as single_widget)?
Note: I only know about `form_div_layout.html.twig`, maybe not an issue for bootstrap or foundation themes?

**Comment by fabpot** [comment]
There are many issues/PRs on this topic, let's close this one.
