### ISSUE TITLE
Multiple groups contraints dont work with Valid Contraint and OptionResolver

### ISSUE THREAD

**Issue by testcodeforme** [symfony/symfony#29554]
**Symfony version(s) affected**: 4.1.6

**Description**  
I try use multiples groups in Contraint Valid into CollectionType and select what groups apply in OptionResolver of Entity embedded.

**How to reproduce**  
I created it Project with minimum code and README file explaining how to reproduce Bugs
https://github.com/testcodeforme/symfonymultigroupvalid

**Additional context**  
I not sure if Contraint Valid only can valid with only a group  when it used into CollectionType or if need apply another code... and sorry for my bad English :(

I dont test it problem in others version of Symfony

**Comment by xabbuh** [comment]
@testcodeforme Can you check if #36216 fixes your issue too?

**Comment by xabbuh** [comment]
Let's close here as #36216 has been merged. Please comment if that doesn't solve the issue.
