### ISSUE TITLE
PHPUnit Bridge | Find a better way to download PHPUnit (404 error)

### ISSUE THREAD

**Issue by tburschka** [symfony/symfony#29559]
**Symfony version(s) affected**: 4.x

**Description**  
Every Time PHPUnit get a minor release the symfony/phpunit-bridge get an 404 since the archive of the defined release is not available anymore (happens currenty with phpunit 7.4 since phpunit 7.5 was released 4 days ago) 

**How to reproduce**  
Set SYMFONY_PHPUNIT_VERSION to 7.4 and run vendor/bin/simple-phpunit witch will result in this error: Fatal error: Uncaught RuntimeException: Could not find https://github.com/sebastianbergmann/phpunit/archive/7.4.zip

**Possible Solution**  
Try to use the releases api from github:
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository to fetch "older" versions

**Comment by nicolas-grekas** [comment]
This has been fixed already in recent versions, please upgrade.

**Comment by xabbuh** [comment]
Did you update the PHPUnit bridge to the latest version? We recently merged a fix that uses Composer to install PHPUnit instead of downloading the archive.
