### ISSUE TITLE
[Monolog] Create a Processor to add Debug-Token-Id

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#29567]
**Description**  
Create a Processor of Monolog to add the Debug-Token-Id or the full URL of the debug profiler.

This processor could be enabled only during debug mode ofc.

**Comment by stof** [comment]
Which token id are you talking about ?

**Comment by gmponos** [comment]
The same you add in the response as a `X-Debug-token` header

**Comment by stof** [comment]
this token is the identifier of the profile in the profiler. We cannot add it in the logs, because it is only available when the profiler runs (i.e. at the very end of the request).

**Comment by fabpot** [comment]
If you are talking about a unique token per request, there are some third-party bundle doing that. If you want the debug token, it's already part of the HTTP response. Not sure it makes sense in the logs as this is only available in the dev mode. I propose to close.

**Comment by Simperfit** [comment]
@fabpot I think we can close this too.
