### ISSUE TITLE
environment specific .env.local or .env.test not loaded when running command

### ISSUE THREAD

**Issue by PaddyLock** [symfony/symfony#29566]
**Symfony version(s) affected**: x.y.z

symfony/dotenv v4.1.4
symfony/framework-bundle v4.1.9

**Description**  
I have made the changes as advised in https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application

If I try and run a command such as

`APP_ENV=dev php bin/console doctrine:database:create -n`

It does not load the variables from .env.local it uses the ones from .env instead

**How to reproduce**  

Follow instructions in https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application
to create config/bootstrap.php and update public/index.php

create the following .env files
.env 
.env.local
.env.test

**Possible Solution**  

I also tried running as

`php bin/console doctrine:database:create -n --env=test`

but no joy

**Additional context**  

If I try and run this command

APP_ENV=dev php bin/console doctrine:database:create -n

It does not load the .env.local

I also tried

APP_ENV=local php bin/console doctrine:database:create -n

Also the .env.test is not used if I run

APP_ENV=test php bin/console doctrine:database:create -n

However, the following DO clear the caches for the correct environment

APP_ENV=dev bin/console cache:clear
APP_ENV=test bin/console cache:clear

I have tried restarting Apache

**Comment by xabbuh** [comment]
Did you also update the `bin/console` file?

**Comment by PaddyLock** [comment]
Yes, I updated bin/console, config/bootstrap.php and public/index.php
Where is env.local loaded? so I can debug with xdebug

**Comment by PaddyLock** [comment]
Also I had to make a change in bootstrap.php as loadEnv() method not available. I changed it to load()

**Comment by stof** [comment]
> Also I had to make a change in bootstrap.php as loadEnv() method not available. I changed it to load()

This makes me think that you haven't followed the upgrade instructions properly. The `.bootstrap.php` file in the updated version of the recipe already handles that properly.

**Comment by stof** [comment]
and just replacing `loadEnv` with `load` will not make `.env.local` work (otherwise, we would not have created a new API)

**Comment by PaddyLock** [comment]
I copied the contents of this file as advised in the instructions - https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php
I wasn't trying to fix the loading of .env.local by changing the method name. I was merely fixing the error in the file. If it should in fact be left as it it is then why is the method not in my version of Dotenv. I know this is probably a separate issue, but I just though I'd mention it.

**Comment by PaddyLock** [comment]
When you say the .bootstrap.php in the  updated version of the recipe -  in which recipe?

**Comment by PaddyLock** [comment]
@stof I have updated to Symfony 4.2.*
Everything is now working, and the correct loadEnv method is also now in Dotenv. So, should the instructions specify that Symfony 4.2.* is required? it says "these changes can be made to any Symfony 3.4 or higher app" or is it that Symfony 4.1.* has some other difference that means it does not work when following the instructions.

**Comment by xabbuh** [comment]
The `loadEnv()` method is indeed new in Dotenv 4.2. We should update the documentation to explain that you need this version.

**Comment by stof** [comment]
The `.bootstrap.php` file used in the recipe (and part of the diff linked in the instruction you mentioned previously) implements a fallback for versions of DotEnv without the `loadEnv` method. This is why I'm saying that you have *not* followed the instructions you linked.

**Comment by stof** [comment]
hmm, maybe you took the version of bootstrap.php applying only to Symfony 4.2+, which got cleaned from the fallback. See https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/bootstrap.php for the file applying to 3.3+

**Comment by stof** [comment]
hmm, the doc is indeed confusing, as it links to the 4.2+ version of the file here, while talking about upgrading a 3.4 application. /cc @javiereguiluz @weaverryan

**Comment by stof** [comment]
@PaddyLock the instruction links to a diff covering commits in which it is still named `.bootstrap.php`, because the commit range is too narrow. But the file was renamed in all versions of the recipe.

**Comment by stof** [comment]
https://github.com/symfony/recipes/issues/505 seems to be caused by the same issue.

**Comment by PaddyLock** [comment]
@stof I presume you are referring to the the link in point 2 and 3? there is no link in point 1 to the diff where it mentions bootstrap.php. Maybe it should be made clearer that the diff refers to all files in the recipe change? Just trying to help future readers of the instructions.

**Comment by xabbuh** [comment]
let's close here in favour of improving the documentation (see symfony/symfony-docs#10775)

**Comment by matheusgontijo** [comment]
> Did you also update the `bin/console` file?

@xabbuh Christian, is it necessary nowadays (6.1) to modify `bin/console` file? Or does Symfony perform it internally?

I'm also not getting `.env.local` automatically. I would need to edit the entry files to get it eventually working.
