### ISSUE TITLE
[DI] New config not being used in Passes, resulting in compile failure

### ISSUE THREAD

**Issue by nielsvermaut** [symfony/symfony#29563]
**Symfony version(s) affected**: 3.4.20

**Description**  

Given the following context: We are using an external package (moovly/access-bundle) that has a AccessClient.php. This client connects to one of our microservices. In a new version of this package we have added a argument in the constructor, and this seems to work well on other projects (which are on a newer Symfony version), but not the one on 3.4.20.

When I install and enable this package, I receive the following error:

```
Cannot autowire service "Moovly\AccessBundle\Client\AccessClient": argument "$origin" of method "__construct()" is type-hinted "string", you should configure its value explicitly. 
```

I've tried loosening the API, but I receive a similar error. I've also tried disabling autowiring for the Client classes, but to no effect.

I've also tried just defining them in the projects services.yml (ROOT/app/config/services.yml) itself, instead of the bundle (ROOT/vendor/moovly/access-bundle/src/Resources/config.yml) to make sure there is no problem with the bundle config. This with no effect.

Whatever I do, the service definition in the cache directory stays:

```
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// ROOT/var/cache/dev/ContainerXxqsbpi/getAccessClientService.php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Moovly\AccessBundle\Client\AccessClient' shared autowired service.

return $this->services['Moovly\AccessBundle\Client\AccessClient'] = new \Moovly\AccessBundle\Client\AccessClient($this->getEnv('ACCESS_API_URL'), $this->getEnv('API_TOKEN'), ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLoggerService.php')) && false ?: '_'});
```

When I manually edit this cache file, it does (obviously) work, but this is of course not a solution.

**How to reproduce** 

The + and - are to show the diff that breaks the config.

```php
<?php
// ROOT/vendor/moovly/access-bundle/src/Client/AccessClient
namespace Moovly\AccessBundle\Client;

class AccessClient
{
-    public function __construct(string $baseUrl, string $apiToken, LoggerInterface $logger)
+   public function __construct(string $baseUrl, string $apiToken, LoggerInterface $logger, string $origin)
}
```

```yaml
// ROOT/vendor/moovly/access-bundle/src/Resources/config/services.yml

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Moovly\AccessBundle\:
    resource: '../../{Service,Client,Factory,DataTransformer}'

  Moovly\AccessBundle\Client\AccessClient:
    arguments:
      $baseUrl: '%access_api_url%'
      $apiUrl: '%api_token%'
      $logger: '@logger'
+    $origin: '%service_name%'
```

```json
//truncated composer.json
//ROOT/vendor/moovly/access-bundle/composer.json
{
    "name": "moovly/access-bundle",
    "type": "symfony-bundle",
    "require": {
        "guzzlehttp/guzzle": "^6.3",
        "moovly/guzzle-client-middleware": "^1.1",
        "monolog/monolog": "^1.23",
        "symfony/security": "^3.4|^4.0",
        "symfony/http-kernel": "^3.4|^4.0",
        "symfony/config": "^3.4|^4.0",
        "symfony/dependency-injection": "^3.4|^4.0"
    },
    "require-dev": {
        "phpro/grumphp": "^0.14.1",
        "phpstan/phpstan": "^0.9.2",
        "phpstan/phpstan-doctrine": "^0.9.1",
        "sebastian/phpcpd": "^4.0",
        "sensiolabs/security-checker": "^4.1",
        "squizlabs/php_codesniffer": "^3.3",
        "phpspec/phpspec": "^5.0"
    },
    "autoload": {
      "psr-4": {
        "Moovly\\AccessBundle\\": "src"
      }
    },
    "license": "proprietary",
    "repositories": [
        {"type": "composer", "url": "https://repo.packagist.com/moovly/"},
        {"packagist.org": false}
    ]
}
```

**Possible Solution**  
N/A

**Additional context**  

I realise that the suggestion could come up to upgrade to a newer version of Symfony (as a work-around). This however is a bit difficult. This is a project that we are dismantling into separate projects. We've carried this from version 2.4, and we would have to do some real hours to resolve deprecations upwards.

In the light of a project that will be deprecated soon, but still needs this functionality for backwards compatibility for our API consumers, those would be hours lost.

I would have liked to attach a unit test, but I'm not familiar about how the DI container really works internally. I've done some debugging with XDebug, but I'm now at a point that I don't know how to resolve this in a timely manner.

Does anybody have an idea what I might be doing wrong or what is causing this?

**Comment by xabbuh** [comment]
Maybe there is another config file defining the service for this class (possibly through PSR-4 based service detection) that overrides your manual definition. Can you create a small example application allowing to reproduce the issue?

**Comment by nielsvermaut** [comment]
Hi @xabbuh, I forgot to check for new references that I didn't add or weren't in the bundles services.yml. There was a definition in another (local) bundle. I've changed it, and I have some other issues, but I'll manage to resolve it.

Sorry for the bother and thanks for the speedy insight!

This bug may be closed!
