### ISSUE TITLE
[Messenger] "The default AMQP transport is not available" error

### ISSUE THREAD

**Issue by aradoje** [symfony/symfony#29568]
**Symfony version(s) affected**: 4.y.z

**Description**  
I am running full framework (`4.2` updated from `3.4` without flex) and installed messenger component with it's dependencies. Installed amqp extensions and rabbitMQ server also. When trying to consume messages I get this error:

```
In FrameworkExtension.php line 1580:
                                                                                                                                                                                          
  The default AMQP transport is not available. Make sure you have installed and enabled the Serializer component. Try enabling it or running "composer require symfony/serializer-pack".  
```

After I checked and installed that component I still got the same error. 
After some debugging and exploring concluded that, even it says in docs that serializer will be enabled by default, it wasn't, the serializer in the bus was `null` and produced this exception.

**How to reproduce**  
Install and configure `messenger` component in full framework

**Possible Solution**  
The solution for me was to add default serializer in messenger config
```
framework:
  messenger:
    serializer:
      id: messenger.transport.symfony_serializer
```
After which I got error
```
In FrameworkExtension.php line 1521:
                                                                                                                                                                         
  The default Messenger serializer cannot be enabled as the Serializer support is not available. Try enabling it or running "composer require symfony/serializer-pack".  
```

and solved it in the framework configuration
```
framework:
    serializer: ~
```
**Additional context**  
I believe the error messages could be a bit clearer, in my case they weren't helpful much.
Ping @Nyholm

**Comment by Nyholm** [comment]
I can confirm that the exception message is very unclear and it requires some debugging in FrameworkExtension and Configutation.php to figure out the issue. 

The solution does also vary on which 4.x minor version you are running. 

I’m not sure there is a good fix for this. Maybe just rephrase the exception to something like “install this package and make sure the serialiser is enabled it used” (something along those lines). 

We could also argue that this is an issue only for the deprecated setup (composer req symfony/symfony) and we don’t support that.

**Comment by weaverryan** [comment]
Closing this as in 4.3, the default serializer will be the php serializer, and the Symfony serializer is not required (unless you *choose* to use it).
