### ISSUE TITLE
[RFC] Add HTTP Responder pattern

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29574]
I've recently polished my HomeController to, what i think, its most ultimate form:

```php
<?php
namespace App\Controller;

use App\Http\Responder;
use App\Http\RespondTemplate;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/", name="home")
 */
final class HomeController
{
    public function __invoke(Request $request, Responder $responder): Response
    {
        return $responder->respond(new RespondTemplate('home.html.twig'));
    }
}
```

I've used this technique more or less some time now, and as such implemented it in my demo app in a more standard way:

https://github.com/msgphp/symfony-demo-app/tree/master/src/Http

Now im curious if it could be core candidate concept. I think it's very flexible.

ref https://github.com/symfony/symfony/issues/21732#issuecomment-282235589 https://github.com/symfony/symfony/pull/21765#issuecomment-333391098

**Comment by ro0NL** [comment]
To clarify its capability, by default any Respond type can be like:

```php
(new RespondRouteRedirect('route_name', ['param' => 'x']))
// default API
  ->withStatus(3xx)
  ->withHeader(['X-Bar' => 'boo'])
  ->withFlashes(['success' => 'yay', 'error' => ['oh', 'noes']]);
```

**Comment by ro0NL** [comment]
@theofidry on high-level not so much. As the kernel is already our true HTTP responder, sort of speak. The controller is just an implementation detail of it.

However, on low-level, it's creates a way to unify controllers, and have them consise and decoupled. So this is basically an alternative (better IMHO) solution to AbstractController and its util responder methods.

If''s flexible, and can be used in e.g. an event listener as well.

So practically the benefit is above snippet from a standard point of view. Not juggling with url generators, twig envs, etc. to provide the response (which is the controller's true job).

**Comment by ro0NL** [comment]
Currently we add value to AbstractController: #28875

But we dont provide a low level API to things standalone. I dont like it.

Above PR could be done like `$respond->withLinks(...)` what works for everyone. At this point AbstractController would just leverage the responder.

**Comment by ostrolucky** [comment]
I also don't see benefit of this
```php
class HomeController
{
    public function __invoke(Request $request, Responder $responder): Response
    {
        return $responder->respond(new RespondTemplate('home.html.twig'));
    }
}
```

over current
```php
class HomeController
{
    public function __invoke(Request $request, Environment $twig): Response
    {
        return new Response($twig->render('home.html.twig'));
    }
}
```

**Comment by ro0NL** [comment]
I know. :) But it becomes boring to deal with it over&over again using the same services.

Im not into 'render this template' or 'generate this URL'. I just want to **respond**, quickly :)

Using pattern standardizes the approach, and avoids per-case solutions by inlining logic per controller.

**Comment by ostrolucky** [comment]
Having to inject Responder service over and over again is less DRY, where in current aproach sometimes you might need Twig service, sometimes not. 

This is precisely what are abstract controllers for. If you don't like them, there is also https://github.com/fervo-and-friends/controller-traits or things similar to https://github.com/kbond/ControllerUtil

> Im not into 'render this template' or 'generate this URL'. I just want to respond, quickly :)

You are, you have to specify which Responder object to use, in this case `RespondTemplate`

**Comment by ro0NL** [comment]
> This is precisely what are abstract controllers for

in the most pure way i agree with you. This is just a util service to standardize boring HTTP responding stuff. If it needs twig or routing is an implementation detail of the concept.

We should favor composition over inheritance no?

**Comment by ro0NL** [comment]
> you have to specify which Responder object to use

the difference is subtle, but there's only one "Responder", You provide it a "Respond" definition (no services involved here)

**Comment by iltar** [comment]
> I also don't see benefit of this
> [...]
> over current
> [...]

It lets you create a set of standard wrappers, but also pushes out the direct dependency on your templating engine. Even better though, it's a viable replacement of `@Template` _and_ it replaces the need of a `RedirectResponse` object to be created in your controller.

**Comment by ostrolucky** [comment]
`new RespondTemplate()` signifies direct dependency on templating engine. And I don't see how is replacing RedirectResponse with RespondRedirect different, nor where is the need to replace `@Template`

**Comment by iltar** [comment]
> And I don't see how is replacing `RedirectResponse` with `RespondRedirect` different, 

`RedirectResponse` requires a non-empty string as constructor argument, which makes it impossible to have _any_ form of lazy route generation for example. 

> nor where is the need to replace `@Template`

This is a dependency on the `SensioFrameworkExtraBundle`, it's not a core feature. On top of that, it's heavily restrictive. If you want to either render _or_ redirect, you have an `@Template` on your controller, while returning an array in scenario 1, but a `RedirectResponse` in scenario 2. This annotation also lacks support for things such as headers, cookies, multiple templates and probably some others that I forgot.

**Comment by nicolas-grekas** [comment]
The current design is simple and generic: you attach a callable to a route and it's been called when that route is requested.
What you do then is up to you and Symfony shouldn't provide more opinionated ways to map a route to some code IMHO.

AbstractController is just a collection of helpers. These helpers are shipped all together, providing one main benefit: easy discovery. If you don't want to use it, all is fine, it means you need to know what the framework provides you and cherry-pick the features you want by yourself.

Nothing to do here in core to me.

**Comment by GromNaN** [comment]
Convert the responder service into a listener for the `kernel.response` event and your controller will be even simpler.

**Comment by GromNaN** [comment]
Exact @HeahDude, I updated my comment.

**Comment by ro0NL** [comment]
i was more seeking a unified way to produce responses. Though i can see controllers returning special types (not a Response), to be handled upon kernel.view, being a valid approach; for regular HTTP controllers i aim to preserve `controller(Request $r, ...): Response`

The responder pattern also helps with e.g. `$event->setResponse(..)`. But i closed per @nicolas-grekas comment this an implementation detail of core-features.

**Comment by ro0NL** [comment]
For those interested: https://github.com/ro0NL/symfony-http-responder

**Comment by linaori** [comment]
Thanks @ro0NL !
