### ISSUE TITLE
[VarExporter] export failure when object requires a constructed object

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#29570]
**Symfony version(s) affected**: 4.2

**Description**  
Given a class implementing `\Serializable`, if the `serialize` is called on a badly constructed instance and throws a \TypeError, then the `Registry::getClassReflector` failed because of https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarExporter/Internal/Registry.php#L101 .

**How to reproduce**  
```php
class Foo implements \Serializable
{
  $foo;
  public function __construct(string $foo) {$this->foo = $foo;}

  public function getFoo(): string {return $this->foo;} // throws a TypeError if $this->foo is null
  
  public function serialize(): string { return [$this->getFoo()]; }

  public function unserialize(string $str): { [$this->foo] = \unserialize($str); }
}
```
**Possible Solution**  

Note that catching `\Throwable` in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarExporter/Internal/Registry.php#L105 could solve the issue, but would replace serialization by a PropertyAccess hydration which is much more slower

**Comment by nicolas-grekas** [comment]
Is that in any way different from what you get when using unserialize/serialize?
I'd be on the side of saying this is normal.
The issue is that an instance has been badly constructed - and that's the consequence of it.
We could replace that line with a catch for `Throwable` - but that might hide more nasty issues I fear.
Why did you expect anything different?

**Comment by jderusse** [comment]
There is a misunderstanding here. My previous message wasn't clear, sorry.

In my case, the original object passed to `VarExporter::export` was perfectly instantiated and valid. The issue is, that VarExport then call the Registry, which try to serialize a "clone" of my initial object created without constructor (I don't understand why it do that BTW).  See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarExporter/Internal/Registry.php#L105

here is a reproduct case https://gist.github.com/jderusse/d12b8bc39e8335c72332dc153da26000

You can test it locally with melody ;-)

```
$ melody run d12b8bc39e8335c72332dc153da26000 -t

object(Foo)#4 (1) {
  ["foo":"Foo":private]=>
  string(3) "bar"
}

PHP Fatal error:  Uncaught TypeError: Return value of Foo::getFoo() must be of the type string, null returned in /tmp/melody/bootstrap.php:27
Stack trace:
#0 /tmp/melody/bootstrap.php(29): Foo->getFoo()
#1 [internal function]: Foo->serialize()
#2 /tmp/melody/vendor/symfony/var-exporter/Internal/Registry.php(101): serialize(Object(Foo))
#3 /tmp/melody/vendor/symfony/var-exporter/Internal/Exporter.php(80): Symfony\Component\VarExporter\Internal\Registry::getClassReflector('Foo')
#4 /tmp/melody/vendor/symfony/var-exporter/VarExporter.php(55): Symfony\Component\VarExporter\Internal\Exporter::prepare(Array, Object(SplObjectStorage), Array, 0, true)
#5 /tmp/melody in /tmp/melody/bootstrap.php on line 27
```

**Comment by jderusse** [comment]
Thank you @nicolas-grekas
