### ISSUE TITLE
Doubt: are "long" php options allowed when using Symfony Process?

### ISSUE THREAD

**Issue by holtkamp** [symfony/symfony#29573]
**Symfony version(s) affected**: Symfony\Process 4.2

**Description**  
Not sure whether it is a bug or a limitation: it seems that the [Symfony\Process](https://symfony.com/doc/current/components/process.html) can not deal with "long" php options when executing a process, such as `--define`

**How to reproduce**  

```php
//info.php
<?php
var_dump(ini_get('memory_limit'));
```
now running it with the `php` command gives me:

```
php info.php  => string(2) "2G", which is my system setting
php -d memory_limit=1024M => string(5) "1024M", shortcut seems to work
php --define memory_limit=1024M => string(5) "1024M", long version seems to work
```

But when trying to set the memory_limit in a Process, the `--define` approach seems not to work.
```php
//run.php
<?php
use Symfony\Component\Process\PhpExecutableFinder;
use Symfony\Component\Process\Process;

require 'vendor/autoload.php';

$phpBinaryFinder = new PhpExecutableFinder();
$phpBinaryPath   = $phpBinaryFinder->find();

$process = new Process([$phpBinaryPath, 'info.php']);
$process->run();
if ($process->isSuccessful()) {
    echo $process->getOutput(); //string(2) "2G"
}

$process = new Process([$phpBinaryPath, '-d memory_limit=1024M', 'info.php']);
$process->run();
if ($process->isSuccessful()) {
    echo $process->getOutput(); //string(5) "1024M"
}

$process = new Process([$phpBinaryPath, '--define memory_limit=1024M', 'info.php']);
$process->run();
if ($process->isSuccessful()) {
    echo $process->getOutput(); //gives the "usage" documentation: Usage: php [options] [-f] <file> [--] [args...] etc etc
}
```
**Possible Solution**  
Not sure: maybe documenting this limitation that `-d` should be used instead of `--define` is already enough?

**Comment by nicolas-grekas** [comment]
you need to split each command line arguments, this should work:
`$process = new Process([$phpBinaryPath, '--define', 'memory_limit=1024M', 'info.php']);`

**Comment by stof** [comment]
Please open an issue on https://github.com/symfony/symfony-docs/issues for any documentation needing clarification (or even better a PR)
