### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by tvlooy** [symfony/symfony#29579]
Last year when PHP 7.2 was released a blogpost was written by @javiereguiluz https://symfony.com/blog/get-ready-for-php-7-2

The blogpost stated that Symfony was tested against 7.2 in Travis and what Symfony versions were compatible etc.

I miss this info now that PHP 7.3 is released. Can the builds be adjusted to include PHP 7.3 and a statement about supported versions would be very welcome.

**Comment by tvlooy** [comment]
Info from @nicolas-grekas "Symfony is already 7.3 compatible but someone needs to contribute a PR to enable it on Travis, without ignoring the issue with extensions."

**Comment by xabbuh** [comment]
FYI, that PR is #29000

**Comment by tvlooy** [comment]
Fantastic!

**Comment by tvlooy** [comment]
#29624

**Comment by ahundiak** [comment]
Just for info I installed a fresh website/skeleton (s4.2.1) with the development server using php7.3.  Worked fine until I browsed to the local site and got:

    This site can’t be reached 127.0.0.1 refused to connect.
    Try:
    Checking the connection
    Checking the proxy and the firewall
    ERR_CONNECTION_REFUSED

Same sort of message you get when no server is running.  But the server process is there.

I then stopped the server and started again with:

    /usr/bin/php7.2 bin/console server:start

And everything worked as expected.  Basic Ubuntu 16.04 development machine.  No docker or anything like that.  Just seems strange.

**Comment by danielrestrepo** [comment]
Same here, tried to start a new project under 7.3 but FPM crashes

**Comment by tvlooy** [comment]
@danielrestrepo if FPM crashes can you produce a corefile and gdb backtrace?

**Comment by sci3ma** [comment]
Same here as @ahundiak said. Ubuntu 16.04, PHP 7.3.1 and fresh website/skeleton (s4.2.2). Project created by composer.

**Comment by mjmeijerman** [comment]
Same here. Newly installed project website/skeleton, nginx webserver on a debian stretch virtual machine.
FPM crashes which causes an nginx bad gateway. This seems to happen somewhere during building the first bundle in Kernel.php on line 677 (`Symfony\Bundle\FrameworkBundle\FrameworkBundle`)

```tail -f php7.3-fpm.log
[20-Jan-2019 17:32:45] WARNING: [pool www] child 22019 exited on signal 11 (SIGSEGV) after 2053.225449 seconds from start```

**Comment by danielrestrepo** [comment]
@tvlooy deployed the project to heroku with `"php": ">=7.2.7"` on `composer.json` and it builded the container with 7.3 and everything worked fine. It means is an infrastructure issue and not symfony's

**Comment by mjmeijerman** [comment]
But when I deploy with the exact same infrastructure, only php 7.2 instead of 7.3, everything works as expected 🤔 
I can var_dump/die anywhere before building the first bundle, but after building the first bundle, php-fpm crashes.
So maybe it is something in php7.3?

**Comment by nicolas-grekas** [comment]
Looks like a PHP bug yes. Crashes always are by definition. Nothing we can do in Symfony unrortunately. Please report to the PHP bug tracker with a minimalist reproducer if you can.

**Comment by sudoash** [comment]
This appears to be caused by the latest version of Xdebug (2.7.0-beta1) — the problem disappears upon its removal/disabling (at least it does for me).

A bug can be tracked on php's bug tracker here: https://bugs.php.net/bug.php?id=77465

**Comment by danielrestrepo** [comment]
@sudoash it makes a lot of sense that the issue is `xdebug`, as `heroku` containers do not compile `php` with `xdebug`. I'll test remove it from my development virtual machine. Thanks!

**Comment by tvlooy** [comment]
I guess this issue can be closed as we have PHP 7.3 support now

**Comment by tecnologiabrasil2016** [comment]
> This appears to be caused by the latest version of Xdebug (2.7.0-beta1) — the problem disappears upon its removal/disabling (at least it does for me).
> 
> A bug can be tracked on php's bug tracker here: https://bugs.php.net/bug.php?id=77465 and on Xdebug's tracker here: https://bugs.xdebug.org/view.php?id=1583

Thanks, @sudoash ! I was looking for this answer! Problem solved!

**Comment by danielrestrepo** [comment]
@tecnologiabrasil2016 if you install xdebug with pecl it works, is just the ppa version that is broken: `pecl install xdebug-beta`
