### ISSUE TITLE
[Messenger] Unable to make handler only handle type-hinted class without parent class also getting handled.

### ISSUE THREAD

**Issue by kojiDev** [symfony/symfony#29578]
**Symfony version(s) affected**: 4.2.1

**Description**  
I have a message that extends another message and adds a field to it.
In Symfony 4.1 handlers didn't handle messages based on their parent class.
How do I avoid this behavior or explicitly list messages for a handler?

I tried to use: `handles` https://symfony.com/doc/current/messenger.html#registering-handlers
But it didn't make a difference, parent message still goes in both handlers.

**How to reproduce**  
```
<?php

namespace App;

class ParentMessage
{
}

class ExtendedMessage extends ParentMessage
{
}

class ParentMessageHandler
{
    public function __invoke(ParentMessage $message): void
    {
        // Both messages goes here, but I only need ParentMessage
    }
}

class ExtendedMessageHandler
{
    public function __invoke(ExtendedMessage $message): void
    {
        // No problems here
    }
}

```

```
App\ParentMessageHandler:
  tags:
  - { name: messenger.message_handler, handles: App\ParentMessage }

App\ExtendedMessageHandler:
  tags:
  - { name: messenger.message_handler, handles: App\ExtendedMessage }
```

**Comment by nicolas-grekas** [comment]
That's not a bug but the expected behavior.
Based on that, it's up to you to design your messages accordingly.
