### ISSUE TITLE
Maker Bundle fails to create ManyToMany relation

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#29580]
**Symfony version(s) affected**: 4.1.9 & 4.2.1

**Description**  
I tried to create a second ManyToMany relation on both mentioned symfony versions
PHP 7.2.13

**How to reproduce**  
`php bin/console make:entity`

 Class name of the entity to create or update (e.g. TinyGnome):
 > Members

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > maksim

 Field type (enter ? to see all types) [string]:
 > relation

 What class should this entity be related to?:
 > Ships

 Relation type? [ManyToOne, OneToMany, ManyToMany, OneToOne]:
 > ManyToMany

 Do you want to add a new property to Ships so that you can access/update Members objects from it - e.g. $ships->getMembers()? (yes/no) [yes]:
 >

 New field name inside Ships [members]:
 > maksim

**Error**  
[error] Error thrown while running command "make:entity". Message: "Syntax error, unexpected T_VARIABLE, expecting '(' on line 61"

```
In ParserAbstract.php line 314:

  Syntax error, unexpected T_VARIABLE, expecting '(' on line 61
```

**Comment by xabbuh** [comment]
The MakerBundle has [its own repository](https://github.com/symfony/maker-bundle). Can you report it over there please?

**Comment by cybernet** [comment]
added  :) https://github.com/symfony/maker-bundle/issues/329
