### ISSUE TITLE
[RFC] Should ControllerTrait really be internal?

### ISSUE THREAD

**Issue by tomtomau** [symfony/symfony#29588]
**Symfony version(s) affected**: 4.2

**Description**  

We use [vimeo/psalm](https://github.com/vimeo/psalm) and in the latest version they implemented a check to catch usages of `@internal` methods.

Our controllers extend [AbstractController](https://github.com/symfony/symfony/blob/da4019a4be54bc01f8e25532c9b3933b2633181e/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L39) which uses the `ControllerTrait` which is [now marked as internal](https://github.com/symfony/symfony/blob/da4019a4be54bc01f8e25532c9b3933b2633181e/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L41).

Psalm reports errors when we use these `@internal` methods:
ie.
```php
$this->render()
```

Psalm reports:
```
The method Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait::render has been marked as internal
```
As well as using any other methods defined in ControllerTrait.

From what I can tell the intention here was that we didn't want end users to apply the ControllerTrait themselves (and rather, use the AbstractController), but the methods on the trait are OK to use (but are final, so don't extend it).

I'm not sure exactly how the semantics of marking a class as `@internal` is properly defined but I would have thought that 'cascades' per-se to all the methods also being considered internal - thus these checks catch the usages of the trait methods.

I'm not really sure what the 'solution' would be and I certainly appreciate the intention behind making it internal.

At a stop gap, we can disable this check in our Psalm configuration to continue on but I figured it is worth having the conversation for other Symfony + Psalm users that come along.

Cheers!

cc @muglug

**Comment by muglug** [comment]
As a bit of background, `@internal` annotations propagate down to the methods defined inside the class/interface/trait. I imagine the thing that's internal is the trait, not the methods that trait contains, and I wouldn't mind making an exception (stopping the propagation of `@internal`) for traits

**Comment by stof** [comment]
The methods of `AbstractController` are indeed not `@internal`, only the trait.

**Comment by tomtomau** [comment]
What about the methods in the Trait? They're the ones end users would actually use.

**Comment by xabbuh** [comment]
> I imagine the thing that's internal is the trait, not the methods that trait contains, and I wouldn't mind making an exception (stopping the propagation of @internal) for traits

I think this makes more sense indeed. If I were using the trait myself, I would still get the error.

**Comment by nicolas-grekas** [comment]
Great thanks, that's definitely the correct behavior to me.
