### ISSUE TITLE
Add more IDE links in console output

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#29585]
With https://github.com/symfony/symfony/pull/29168, we now have an opportunity to improve DX by making some texts clickable.

Eg clicking on a route in the output of the `debug:router` could open the IDE to its controller if there is one.
I'm sure there are more outputs that could benefit from it.

**Comment by nicolas-grekas** [comment]
`debug:autowiring` & `debug:container` could also link to the source.

**Comment by yceruto** [comment]
+ `debug:twig <template_name>` & `debug:form` could also link to the source. :)

**Comment by mablae** [comment]
+ `debug:event-dispatcher` : Jump to listeners/subscribers

**Comment by ro0NL** [comment]
would like to see `<class>App\Link\This</class>` as well as `<file>/link/this.txt</file>` :heart_eyes:

**Comment by mablae** [comment]
@ro0NL You mean doing the actual lookup and resolving to ide links inside the OutputFormatter? 
Interesting idea!

**Comment by nicolas-grekas** [comment]
Side note: ClassStub and CliDumper already contain all the logic me might want to implement these improvements. I'm not suggesting we should use VarDumper - but copy/pasting some code might be fine.

**Comment by ostrolucky** [comment]
I would ideally want to see integration with FrameworkBundle's `ide` option

**Comment by nicolas-grekas** [comment]
Closing as there is nothing specific to keep track of.
Please send PRs adding links if you spot more places where it would make sense.

**Comment by vctls** [comment]
Just found out about this after all this time. :smile: 
Is there a native way of applying this to exception traces as the first PR suggested?
