### ISSUE TITLE
FormType doesn't fill params in subform

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#29592]
Hi all. I try to do a simple subform:
```
class LoginFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
...
        $builder->add($builder->create('author', FormType::class)
        ->add('path1', TextType::class)
        ->add('submit1', SubmitType::class))->getForm();
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MediaEntity::class,
        ]);
    }
}
```
But validator returns error, that params is not found. What am i doing wrong?
![image](https://user-images.githubusercontent.com/4490762/49944344-44d73100-fefb-11e8-87df-91554dd833b4.png)
Appreciate any help.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
