### ISSUE TITLE
[Router][Feature] Append new router to cache container without regenerating it.

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#29590]
**Description**  

I expose my case:

I'm generating dynamic URL through a **custom Loader**, the problem comes when you generate a new URL through a **CMS**, which to work that new dynamic URL must run the router cache clear again. Right now I have no problem because I have 10 URL and does it instantly with `$cache->warmUp()` -->(https://stackoverflow.com/a/35054345/2046442), but would be better a Method to add a new Router to the container without having to regenerate all cache again. I can't find that option/method anywhere.

**Example**  

It could be a good option to add it in `RouterInterface`

**Comment by chiqui3d** [comment]
I finally gonna does with `kernel.request` Subscriber 
thanks  :+1:

**Comment by chiqui3d** [comment]
I reopen the issue because I think it's necessary what I'm asking for. 
Also create a new question:
What is worse to ask for each URL to the database or consult a PHP file to get the URL, this case the file is the router cache container?

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/pull/28865 will "fix" this by allowing you to use a compiled matcher while providing a simple array for compiled routes (eg from a json loaded from the db)

**Comment by chiqui3d** [comment]
If that's how I think it'll be incredibly powerful, I'll be very alert.
Thank you very much .

**Comment by chiqui3d** [comment]
@nicolas-grekas Nothing new?

**Comment by chiqui3d** [comment]
@nicolas-grekas Do you have some example?, i don't  find in the router documentation .

**Comment by nicolas-grekas** [comment]
Would https://github.com/symfony/symfony-docs/pull/10790/files help?

**Comment by chiqui3d** [comment]
Hello @nicolas-grekas 

```php
 $compiledRoutes = (new CompiledUrlMatcherDumper($routes))->getCompiledRoutes();
 $context = new RequestContext();
 $context->fromRequest(Request::createFromGlobals());
 $matcher = new CompiledUrlMatcher($compiledRoutes, $context);
 dump($routes);
 dump($matcher);
 dd('$compiledRoutes =>',$compiledRoutes);
```

![Icompiled routers](https://image.prntscr.com/image/BpS7XSG_R5G0UGzghFfcrA.png)

I understand that what you have added is for one to make one's own system, if I want to continue using the Symfony system for the routes in a CMS I have to continue using the following command to regenerate the routes, Right?

` $router->warmUp($this->kernel->getCacheDir());`

Another doubt I have, `CompiledUrlMatcher`, should find the path inside the array, right? but it doesn't really find that routing or it doesn't show it when printing the object.  or didn't I get the meaning right?

Thank and great work

**Comment by nicolas-grekas** [comment]
> I have to continue using the following command to regenerate the routes, Right?

You still have to create that `$routes` collection and cache the resulting `$compiledRoutes` yes. `$router->warmUp()` is not the only way to do so, you can build any logic.

> `CompiledUrlMatcher`, should find the path inside the array, right?

when you call its `match()` method yes.

**Comment by chiqui3d** [comment]
Perfect, all understood, thank you very much again.

**Comment by nicolas-grekas** [comment]
If you feel like the doc can be improved, please submit a PR to https://github.com/symfony/symfony-docs/ ;)

**Comment by chiqui3d** [comment]
ok, I'll do it

**Comment by chiqui3d** [comment]
@nicolas-grekas Here I am again. I'm turning it around, and I think and still don't understand why there is no method to append a new router to the cache file that Symfony generates without having to generate these completely again. Really if it wasn't for the annotations that I use for backend, really dump the routing file wouldn't do me any good, because if I really have to apply it myself without use the router component, I can really generate the paths myself in a cleaner php file without empty array, as seen in the previous screenshot.

But now you have deprecated the options to know which files Symfony generates for the routing, so even I can't apply this method or extend the options.
