### ISSUE TITLE
Symfony - how to choose the right interface (type-hint) for symfony services?

### ISSUE THREAD

**Issue by ABSimon5** [symfony/symfony#29608]
**Description**  

I often struggle with including oder guessing the right interface to include a service. For Example, this is the recommend way to get a router. I do not understand the logic behind this. There should be an understandable and consistent logic

**Example**  

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class SomeService
{
    private $router;

    public function __construct(UrlGeneratorInterface $router)
    {
        $this->router = $router;
    }
}

I think, what I get here is "vendor\symfony\routing\Router.php". But class Router implements RouterInterface, RequestMatcherInterface. Not UrlGeneratorInterface!

**Comment by chalasr** [comment]
> I think, what I get here is "vendor\symfony\routing\Router.php". But class Router implements RouterInterface, RequestMatcherInterface. Not UrlGeneratorInterface!

https://github.com/symfony/symfony/blob/f2590d196f68006e0d46fca06bd0a63d87eb58fc/src/Symfony/Component/Routing/RouterInterface.php#L24

**Comment by ABSimon5** [comment]
debug:autowiring tells me

 ```
Symfony\Component\Routing\Generator\UrlGeneratorInterface (router.default)

 UrlMatcherInterface is the interface that all URL matcher classes must implement.
 Symfony\Component\Routing\Matcher\UrlMatcherInterface (router.default)

 Symfony\Component\Routing\RequestContext (router.request_context)

 Symfony\Component\Routing\RequestContextAwareInterface (router.default)

 RouterInterface is the interface that all Router classes must implement.
 Symfony\Component\Routing\RouterInterface (router.default)
```
so in total four "router.default" (Class Router?) and one "router.request_context" (Class RequestContext).

UrlGeneratorInterface
UrlMatcherInterface
RouterInterface 
RequestContextAwareInterface

will all give back "vendor\symfony\routing\Router.php"? Why not only RouterInterface?

@chalasr - yes, you are right

**Comment by ro0NL** [comment]
i think we need to update the interface descriptions to better convey its meaning.

if you only need to generate URLs: UrlGeneratorInterface
if you only need to match URLs: UrlMatcherInterface
if you need both, thus a router: RouterInterface

**Comment by ABSimon5** [comment]
this would be great!

**Comment by xabbuh** [comment]
@ABSimon5 Would you like to submit a pull request?

**Comment by ABSimon5** [comment]
I will try my best (will need some time)

**Comment by ABSimon5** [comment]
I have made some tests. Currently it looks like this, a "grouped view" option

![unbenannt-1](https://user-images.githubusercontent.com/36996195/50075696-e7cfc980-01df-11e9-880a-db4592418f71.jpg)

I am mainly interested in the object I get, so services are grouped by classes. I have skiped the interface description, it do not fit always to the class and the list is not so clear. With the classname I can easily search and jump to the symfony documentation.

**Comment by ro0NL** [comment]
> I have skiped the interface description

We're working towards adding those, IMHO i has significant value in `debug:autowiring`.

> With the classname I can easily search

AFAIK you'll only search the autowirable class names, not the service class per se (i.e. `Definition::getClass()`). IMHO it's wrong to use as a title here, as we imply it can be autowired.

Alternatively

```
service.id
=======

# description
use UrlGenerateInterface

# description
use RouterInterface
```
 But honestly, i think dont think we need grouping. Each service is  an independent definition.

**Comment by ABSimon5** [comment]
I do get the service class with Definition::getClass() (simular to debug:container)

**Comment by ro0NL** [comment]
> I test the Router with all four interfaces. I do get always the Router class back

But `Symfony\Bundle\FrameworkBundle\Routing\Router` is an implementation detail. If you hint for `UrlGenerateInterface` you dont care if it's a `Router` object or any other implementation.

> I dont think it make sense, if you print four different interface descriptions,
if you get back one (unlisted) object.

See https://github.com/symfony/symfony/issues/29608#issuecomment-447339613, each interface represents a standalone feature, sort of speak. So if you only need to generate URLs hinting for `UrlGeneraterInterace` is the best fit.

> I do get the service class with Definition::getClass() 

If you'll have, e.g.

```yaml
service_id:
  class: App\SomeClass
```

We cant autowire by type: `App\SomeClass`. That's not how autowiring works anymore.

**Comment by ABSimon5** [comment]
I think (for many) it is a nice information, to get also the classname 
of the object, which implements this or that interface.
Symfony classes are well documentated. To hide this is IMHO not a good idea. 
Many will struggle with this.

```
debug:autowiring router --grouped 

router.default (matches Symfony\Bundle\FrameworkBundle\Routing\Router)
=======
# description
use UrlGenerateInterface
# description
use RouterInterface
...
```

?

**Comment by ro0NL** [comment]
I think you should use `debug:container` for that

```
bin/console debug:container router

 // This service is a public alias for the service router.default                                                       

Information for Service "router.default"
========================================

 This Router creates the Loader only when the cache is empty.

 ---------------- --------------------------------------------------- 
  Option           Value                                              
 ---------------- --------------------------------------------------- 
  Service ID       router.default                                     
  Class            Symfony\Bundle\FrameworkBundle\Routing\Router      
  Tags             monolog.logger (channel: router)                   
                   container.service_subscriber (id: routing.loader)  
  Calls            setConfigCacheFactory                              
  Public           no                                                 
  Synthetic        no                                                 
  Lazy             no                                                 
  Shared           yes                                                
  Abstract         no                                                 
  Autowired        no                                                 
  Autoconfigured   no                                                 
 ---------------- --------------------------------------------------- 
```

**Comment by nicolas-grekas** [comment]
We definitely need better docblock titles to feed `debug:autowiring`.
Closing as I don't think this is actionable.
