### ISSUE TITLE
[Translation] Deprecation of transChoice

### ISSUE THREAD

**Issue by kylekatarnls** [symfony/symfony#29607]
**Symfony version(s) affected**: 4.2

**Description**  
I require symfony/translation^4.0 in my library (Carbon) assuming the public API of its main class `Translator` would not change until next major release and used `transChoice` (according to https://symfony.com/doc/current/contributing/community/releases.html). But by upgrading to 4.2, this method now `trigger_error` for deprecation and this will be turned into an exception (blocking the process) in most cases.

I now have the choice between:

- Lock to ~4.0 || ~4.1 (a very tiny range) that will prevent Carbon to be installed with Symfony < 4 or >= 4.2, so a very disappointing choice regarding the compatibility.
- Upgrade to 4.2, but this can break existing apps and for now it will be a very prohibiting requirements.

Both sound like terrible choices.

**How to reproduce**  
Install Symfony 4.2 and call Translator::transChoice().

**Possible Solution**  
Remove the trigger_error (the `@deprecated` comment is enough and let time to people to handle the change) and wait for 5.0 release before deprecating with an error.

**Comment by kylekatarnls** [comment]
The new trans() form does not work with symfony/translation 4.0 and 4.1 so I have to do for each transChoice call an ugly wrapping if symfony >= 4.2 then new form else old form. Do you honestly find this solution acceptable?

I think there is still a semantic problem, this can also happen with apps using the whole framework that can use `transChoice` now or any plug-able library.

I would try to discuss about the more appropriate solution to this. Obviously it would be easier for Symfony to throw away tools you no longer use and want no longer to maintain. But I will now have to support and maintain on my own project an heavy work-around to support both symfony/translation < 4.2 (where the new %count% system does not exist) and >= 4.2 (where transChoice is deprecated).

And I don't even talk about users who yet extend my translation files. And I don't even talk about supporting < 4 or >= 5. It's just 3 minor versions and already an incompatibility to support (with not even a warning before it's released such as adding `@deprecated` first, then only when developers would have the time to support it, really deprecate it). It makes me a bit anxious about next possible change/deprecation.

I would at least need a cross-compatible way to translate plurals.

And the main problem is users having libraries using symfony/translation will suddenly have exceptions thrown after upgrading while no change occurred in the libraries they used (just because 4.2 throw an exception for a method that still works well else). I don't think I used your library in a wrong way I followed the documentation (of 4.0/4.1) and the exposed public API. So it feels not right to me having to work around this deprecation, having all our existing versions broken and needed to release emergency new patches (for each versions we maintain) to make libraries installable and usable again with composer.

**Comment by xabbuh** [comment]
This looks like there is an issue in your error handler if it turns the deprecations into exceptions.

**Comment by kylekatarnls** [comment]
I do not, I do not develop an application, I develop a library. And it's pretty typical (for example with default dev config of Laravel) to get all deprecation notice to throw an exception. But it's pretty annoying for users of libraries who can do nothing about it. I should not have to ask them to globally mute deprecation errors to handle this, it's not at all a valid excuse to not handle the problem from the Symfony side.

It's fine to add deprecation notices in major releases and up to people to mute/ignore them or not because they know methods are deprecated when they upgrade or when they start to use them.

But it's not when you're told something is valid, start using it, then on a minor release, you no longer can use it.

**Comment by ro0NL** [comment]
>  And it's pretty typical (for example with default dev config of Laravel) to get all deprecation notice to throw an exception.

I tend to disagree. Does laravel really turn deprecations into exceptions by default? That fully defeats the purpose of deprecations.

**Comment by mbabker** [comment]
Laravel does have an error handler that gets set up by default when building apps, see https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php

I'm not quite sure what Laravel has to do with this though, to verify I took an app that's running Laravel 5.7 and updated with Symfony 4.2 components, put a `@trigger_error()` call into a couple of files I knew would be run in a request, and none of those deprecations were converted to Exceptions.

**Comment by nicolas-grekas** [comment]
Hello, I confirm this is an issue with the error handler used by the user that reported the issue.
Silenced errors should be ignored, [Laravel does that](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L59) and so does any not-broken error handler.

If you want to help the user on this issue, you can ask them their stack trace. That should hint them about the faulty error handler in the stack.

We've been triggering silenced deprecations since Symfony 2.7 (May 2015) without any issues - Laravel ecosystem included.

I'm therefore closing as there is nothing wrong here, thanks for asking.

**Comment by kylekatarnls** [comment]
Thanks guys. I hope it could be an error handler problem. @robbydooo Can you please check this and try to see if you have anything special in your error handling?

**Comment by kylekatarnls** [comment]
Thanks to everyone, sorry to trigger the alarm too soon. 🚒 I cleaned my posts so next users having similar issue could get faster to the solution.
