### ISSUE TITLE
Warning: ini_set(): Headers already sent | NativeFileSessionHandler

### ISSUE THREAD

**Issue by wuestkamp** [symfony/symfony#29605]
**Symfony version(s) affected**: 3.4.20
PHP 7.2.12

**Description**  
running a console command which retrieves an entity repository we get the following error:

```
In NativeFileSessionHandler.php line 52:
[Symfony\Component\Debug\Exception\ContextErrorException]                                                   
  Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
```

**Exception trace**
```
Exception trace:
 () at /path/project/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:52
 Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler->__construct() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:6972
 ContainerZzrawkm\appDevDebugProjectContainer->getSession_HandlerService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:7002
 ContainerZzrawkm\appDevDebugProjectContainer->getSession_Storage_NativeService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:3515
 ContainerZzrawkm\appDevDebugProjectContainer->getSessionService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:3921
 ContainerZzrawkm\appDevDebugProjectContainer->getCb_Security_WriteAccessHandlerService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:3891
 ContainerZzrawkm\appDevDebugProjectContainer->getCb_Listener_WriteAccessService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:3103
 ContainerZzrawkm\appDevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:4997
 ContainerZzrawkm\appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManager_DelegateService() at /path/project/var/cache/dev/ContainerZzrawkm/appDevDebugProjectContainer.php:4988
 ContainerZzrawkm\appDevDebugProjectContainer->ContainerZzrawkm\{closure}() at /path/project/var/cache/dev/ContainerZzrawkm/EntityManager_9a5be93.php:298
 Closure->__invoke() at /path/project/var/cache/dev/ContainerZzrawkm/EntityManager_9a5be93.php:298
 EntityManager_9a5be93->getRepository() at /path/project/var/cache/dev/jms_diextra/doctrine/EntityManager_5c1386890aa63.php:169
 EntityManager5c1386890aa63_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->getRepository() at /path/project/src/MyCompany/Bundle/ApiBundle/Services/RethinkService.php:137
 MyCompany\Bundle\ApiBundle\Services\RethinkService->fullSync() at /path/project/src/MyCompany/Bundle/ApiBundle/Command/RethinkDbCommand.php:71
 MyCompany\Bundle\ApiBundle\Command\RethinkDbCommand->execute() at /path/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /path/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /path/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /path/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /path/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/project/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
 JMS\JobQueueBundle\Console\Application->doRun() at /path/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /path/project/bin/console:27
```

**Additional context**  
This does not happen if I clear the cache and call the command. It only happens the 2nd and more times after that, so with pre-loaded cache.

Any idea what could cause this? A bundle that starts the session before NativeFileSessionHandler calls `ini_set('session.save_path', $savePath);`?

Thanks,
Kim

**Comment by xabbuh** [comment]
It looks like there is a service (some Doctrine listener?) that tries to access the session even when your application is executed on the command-line. You probably need to update it to check first, if the session can safely be used.

**Comment by wuestkamp** [comment]
That was it, thanks @xabbuh 

I was requesting a service during my command execution with autowiring of session:
`    public function __construct(SessionInterface $session)`
That started the session even in console command.

I changed this now to:

```
public function __construct(ContainerInterface $container)
{
 // $container->get('session');
}
```

Instead of passing the container I tried passing `RequestStack $stack` and then accessing the session via  `$stack->getCurrentRequest()->getSession()` but its always empty.

**Comment by xabbuh** [comment]
:+1: let's close here then

**Comment by enumag** [comment]
@xabbuh I ran into the same problem. In my case the dependencies are like this:

- The console command needs to render something to it requires Twig.
- Twig has \Symfony\Bridge\Twig\Extension\LogoutUrlExtension.
- LogoutUrlExtension requires \Symfony\Component\Security\Http\Logout\LogoutUrlGenerator.
- LogoutUrlGenerator requires \Symfony\Component\Routing\Generator\UrlGeneratorInterface which is the router service.
- router is `\Genedys\CsrfRouteBundle\Routing\Router\CsrfRouter` which we're using to generate links with csrf tokens
- CsrfRouter needs a storage where to save the csrf tokens - and of course these are saved in session which loads the Session service and the NativeFileSessionHandler.

All the dependencies are reasonable, I can't see anything where I can break the chain to not load session. Also none of the services are my own, it's all either symfony or the csrf bundle. Any ideas?

**Comment by xabbuh** [comment]
This seems logical. If the router needs the token when a URL is generated, it will of course start the session in the end to retrieve the token from the session.

**Comment by enumag** [comment]
I don't think we actually generate such link in this command. It's just that the dependency chain triggers `NativeFileSessionHandler::__construct()` which causes the error.

The only thing in the chain that should have lazy dependencies is the `LogoutUrlExtension` - it doesn't make sense to load all dependencies of all twig extensions whenever you use twig anywhere. It's unlikely that you will actually use all the extensions.

**Comment by enumag** [comment]
Why is the `ini_set()` in `NativeFileSessionHandler::__construct()` anyway? In my opinion it should only be called right before `session_start()`. (I don't think session is actually started in my setup.)

**Comment by fabpot** [comment]
I agree with @enumag, we could probably defer any `ini_set()` calls until just before the session start, right?

**Comment by xabbuh** [comment]
@enumag Sorry, I misunderstood your use case then. I thought you were actively using the `logout_url()` function in your Twig templates.

**Comment by xabbuh** [comment]
Isn't it too late to call `ini_set()` in `open()` as the path is an argument of that method?

**Comment by enumag** [comment]
Yeah, that is most likely too late. I don't think we can solve this correctly in a class that extends `\SessionHandler`. Is there a reason why it isn't handled in `NativeSessionStorage`?

**Comment by enumag** [comment]
Ah, the code with `ini_set` is only needed if the native `\SessionHandler` is used which is why it's in a class that extends it.

We could add our own interface extending `\SessionHandlerInterface` and containing an `onStart` method that would be called by the storage when starting the session. But I'm not sure if this is a good solution.

**Comment by enumag** [comment]
Another alternative is to add the ini_set calls to container initialization. This might be better in my opinion.
