### ISSUE TITLE
[Routing] HTTP-Foundation PrepareRequestUri() does not support multidomain anymore

### ISSUE THREAD

**Issue by charlesBochet** [symfony/symfony#29612]
**Symfony version(s) affected**: 4.2.1

**Description**  
Hello! Thanks for the great job on Symfony :)
I have an issue using Symfony Routing. I have a multidomain Laravel application with different routes grouped by domain. When trying to match routes, Routing/Matching/UriValidator is trying to compare **$request-path()** and a **route regex** containing the domain name.

```
public function matches(Route $route, Request $request)
    {
        $path = $request->path() == '/' ? '/' : '/'.$request->path();

        return preg_match($route->getCompiled()->getRegex(), rawurldecode($path));
    }
```

Problem is that when I request 'exampledomain.com/home', $request->path() value is **'/home'** and not **'exampledomain.com/home'** anymore. Root cause seems to be this new piece of code in **Request::prepareRequestUri()**:

```
$requestUri = $this->server->get('REQUEST_URI');

            // HTTP proxy reqs setup request URI with scheme and host [and port] + the URL path, only use URL path
            $uriComponents = parse_url($requestUri);

            if (isset($uriComponents['path'])) {
                $requestUri = $uriComponents['path'];
            }
```
that is overriding $requestUri :(

**How to reproduce**  
Laravel project with such configuration: 
`
        $router->group(['as' => 'domain.', 'domain' => 'exampledomain.com', function($router) {
            include base_path('app/CashFlow/Http/routes.web.php');
`

**Possible Solution**  
Rollback to previous behavior :)

**Comment by ro0NL** [comment]
Can you share some related server variables, e.g. REQUEST_URI. Im not sure i follow the BC break you describe.

**Comment by xabbuh** [comment]
@charlesBochet Happy new year. :) Can you provide the information @ro0NL asked for?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
