### ISSUE TITLE
How to implement a symfony4 containing multiple project modules？

### ISSUE THREAD

**Issue by acodercat** [symfony/symfony#29618]
How to implement a symfony4 containing multiple project modules？
like this！
![2018-12-15 17-23-48](https://user-images.githubusercontent.com/16076835/50041364-aa0f5b80-008e-11e9-8ff7-ae68b5cc1e65.png)
Can I use a Bundle?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by yceruto** [comment]
If it's a multi-kernel project based on Symfony4 maybe this skeleton can help https://github.com/yceruto/symfony-skeleton-vkernel.
