### ISSUE TITLE
[Swift] Swift_TransportException not displayed in console in LoginAuthenticator->authenticate 

### ISSUE THREAD

**Issue by guillaume-a** [symfony/symfony#29616]
**Symfony version(s) affected**: 3.3.18

**Description**  
I have configured my swiftmailer to send email through SMTP using TLS like that : 

 ```
parameters:
    mailer_transport: smtp
    mailer_host: smtp.xxx.com
    mailer_user: mail@xxx.com
    mailer_password: password
    mailer_port: 587
    mailer_encryption: tls
```

```
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode:  null
    spool:     { type: memory }
```

When the spool is flushed, we pass in this code (LoginAuthenticator->authenticate(...))

```
    public function authenticate(Swift_Transport_SmtpAgent $agent, $username, $password)
    {
        try {
            $agent->executeCommand("AUTH LOGIN\r\n", array(334));
            $agent->executeCommand(sprintf("%s\r\n", base64_encode($username)), array(334));
            $agent->executeCommand(sprintf("%s\r\n", base64_encode($password)), array(235));

            return true;
        } catch (Swift_TransportException $e) {
            $agent->executeCommand("RSET\r\n", array(250));

            return false;
        }
    }
```

When the Authenticator passes the password (3rd executeCommand) the smtp serveur reply this : 

`550 5.2.1 Mailbox cannot be accessed [xxxxx]`

In fact we don't care the exact message, we just care the code 550 is not in [235] so is throws a `Swift_TransportException`

Here : 
```
    /** Throws an Exception if a response code is incorrect */
    protected function _assertResponseCode($response, $wanted)
    {
        list($code) = sscanf($response, '%3d');
        $valid = (empty($wanted) || in_array($code, $wanted));

        if ($evt = $this->_eventDispatcher->createResponseEvent($this, $response,
            $valid)) {
            $this->_eventDispatcher->dispatchEvent($evt, 'responseReceived');
        }

        if (!$valid) {
            $this->_throwException(
                new Swift_TransportException(
                    'Expected response code '.implode('/', $wanted).' but got code '.
                    '"'.$code.'", with message "'.$response.'"',
                    $code)
                );
        }
    }
```

But this Exception is catched by the authenticate() method : 

```
[...]
catch (Swift_TransportException $e) {
        $agent->executeCommand("RSET\r\n", array(250));
        return false
}
```

The problem is the original `Swift_TransportException $e` is not rethrown.
And in my particular case, the RSET command is not recognized by the server so it throws a new `Swift_TransportException` with no code or message

In the console I got this result (second throw after RSET): 

`ERROR     [app] Exception occurred while flushing email queue: Expected response code 250 but got code "", with message "" [] []`

But I think it should be better to get this (first exception while trying to Auth): 

`ERROR     [app] Exception occurred while flushing email queue: Expected response code 250 but got code "550", with message "Mailbox cannot be accessed" [] []`

I had to spend an hour to deep dive in debug mode, line by line to display the original error message.
But I understand ths use of RSET command.

So I don't know how it can be enhanced.

Thank you for reading this LOOOOOOOng issue.

**Comment by xabbuh** [comment]
Swiftmailer and SwiftmailerBundle are not part of the Symfony core and both have their own repositories. So I am going to close here. Thank you for understanding.

**Comment by guillaume-a** [comment]
No problem, i didn't know. I'll find the correct repo :)

Regards.
