### ISSUE TITLE
AbstractController and non-shared service break in test environment

### ISSUE THREAD

**Issue by evs-xsarus** [symfony/symfony#29628]
**Symfony version(s) affected**: 4.2.x
**Description**  
Since v4.2.x, symfony shows a deprecation warning about not using the Symfony\Bundle\FrameworkBundle\Controller\AbstractController but Symfony\Bundle\FrameworkBundle\Controller\Controller. After changing all controllers to extend the abstract version, the test environment breaks when there is a non-shared service in use.

**How to reproduce**  
Create a service and configure it as non-shared.

```yaml
App\Service\Prismic\LinkResolverService:
    # not shared because of function setFullResolve
    shared: false
```
Inject the service in a controller:

```php
<?php
namespace App\Controller;

use App\Service\Prismic\LinkResolverServiceInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CareersController extends AbstractController
    /**
     *
     * @var LinkResolverServiceInterface
     */
    private $prismicLinkResolver;

    public function __construct(LinkResolverServiceInterface $prismicLinkResolver)
    {
    }
```
Now, when calling the console
```
./bin/console --env-test
```
 the following error is shown:

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
> The service "App\Controller\CareersController" has a dependency on a non-existent service "App\Service\Prismic\LinkResolverService".  

**Additional context**  
When I have 2 controllers, one which doesn't inject LinkResolverServiceInterface and one that does. The error is also triggered if only the controller without the injection extends the AbstractController.

**Comment by evs-xsarus** [comment]
@xabbuh done. While creating it, I discovered a connection with a custom Twig Extension in which the same non-shared service is injected. If you remove the 'PrismicExtension', the test environment shows no error.

The application is set to 'test' in .env. Change it to 'dev' to see a working one.

[29628.zip](https://github.com/symfony/symfony/files/2694843/29628.zip)

**Comment by xabbuh** [comment]
I managed to reproduce and try to debug your example application a bit. The issue seems to reside somewhere in the process of inlining services inside `InlineServiceDefinitionsPass`. However, I did not manage to find the actual cause.

**Comment by evs-xsarus** [comment]
@xabbuh is this issue waiting for my feedback or is someone else currently assigned to try to find the cause for this problem?

**Comment by xabbuh** [comment]
The bug is confirmed. But so far nobody cared enough (or at least didn't comment here) to look into the cause and try to fix it.
