### ISSUE TITLE
[Translator] LocaleAwareInterface not setting Locale in Command for path generation

### ISSUE THREAD

**Issue by Isengo1989** [symfony/symfony#29622]
**Symfony version(s) affected**: 4.2.1

**Description**  
When using the LocaleAwareInterface in my Mailservice it works fine when a Request comes from the Browser, all paths are set correctly and trans() in Twig also works. As soon as I am using the Mailservice from a Command it still translates the text, but fails by building the correct paths.

Not sure if this is a problem of SwiftMailer or Symfony and its new LocaleAwareInterface

**How to reproduce**  
As explained above. Use a Service, set the locale with the LocaleAwareInterface->setLocale('en') and try sending a Mail.

**Possible Solution**  
Giving the Twig file a locale and use it in the path like so -> {'_locale': locale}

**Additional context**  
ERROR     [app] An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "adress_edit_customer" as such route does not exist.")

**Comment by Isengo1989** [comment]
> I think that he expects the RouterContext to be locale-aware to configure the `_locale` parameter. Currently, it might not be the case (and the web works only because the locale is set based on the matched route, and the matching itself updates the value in the RouterContext)

Right. I thought setting the locale with:

`$this->locale->setLocale('en');`

will also imply that all routes will use the same locale.

Now I am getting the RouterContext and set the parameter **_locale**. I don't know if this is wanted - when I am setting the locale I am expecting the routes to do the same.

```
$context = $this->router->getContext();
$this->router->setContext($context->setParameter('_locale',$lang));
```

**Comment by xabbuh** [comment]
If I understand correctly what you are trying to achieve, setting the locale manually when in the CLI context is indeed what you have to do.
