### ISSUE TITLE
[Translation] debug:translation command does not show components translations

### ISSUE THREAD

**Issue by damienalexandre** [symfony/symfony#29633]
**Symfony version(s) affected**: 3.4 to 4.2 at least

**Description**  

When running `php ./bin/console debug:translation --all fr`, translation from all bundles are read (like FrameworkBundle, TwigBundle... ) **but** translations from components likes validators or security are not:

- vendor/symfony/form/Resources/translations/validators.fr.xlf
- vendor/symfony/security-core/Resources/translations/security.fr.xlf
- vendor/symfony/validator/Resources/translations/validators.fr.xlf

I think this is not the behavior I expected, it could be improved. 

The help message on the "all" option tells: 

> You can display information about translations in all registered bundles in a specific locale:

So it work as expected, but someone using those components will have hidden translation in his application, and no way to read them / debug them.

**How to reproduce**  

```
php ./bin/console debug:translation --all fr
# No message from the "validators" catalog is listed
```

**Possible Solution**  

Symfony should use the same path resolution for the debug command and the catalog loading in Translator. The Translator is capable of reading translations from the components, so this command should act the same way.

**Additional context**  

Happy holidays :christmas_tree: :santa:

**Comment by yceruto** [comment]
Hi @damienalexandre, I agree and it's a new feature that I'm trying to add for 4.3, see https://github.com/symfony/symfony/pull/29121, reviews are welcome :)

**Comment by damienalexandre** [comment]
Oh! That's exactly what I need, sorry I missed your PR :fearful: Thanks a lot, as I can see you use the discovery already done in the Framework, that's very nice :+1: 

https://github.com/symfony/symfony/blob/562448ad241889af0a116bcf0a9d8ddea9126545/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1004-L1020

_Should I close this issue?_

**Comment by lyrixx** [comment]
IMHO, this is a bug fix and not a new features.

**Comment by yceruto** [comment]
In that case, we can split #29121 adding these particular paths as a bugfix in 3.4?
```
The Resources/translations/ directory of Validation component (if installed).
The Resources/translations/ directory of Form component (if installed).
The Resources/translations/ directory of Security Core component (if installed).
```
Note that it'll requires anyway a new _constructor_ argument in commands to allow extra paths.

**Comment by fabpot** [comment]
a new constructor arg seems like a new feature to me :)

**Comment by lyrixx** [comment]
Hmm, indeed the help says:
>       --all              Load messages from all registered bundles
I thought `--all` means "all" :joy:
