### ISSUE TITLE
Debug toolbar, in combination with doctrine breaks serialization

### ISSUE THREAD

**Issue by jaapio** [symfony/symfony#29634]
**Symfony version(s) affected**: >= 2.8

**Description**  
This issue was already reported in https://github.com/symfony/symfony/issues/27901. But closed by the reporter. 
We are using a querybuilder in to create a query which is passed to a call to doctrine's `CreateNativeQuery` method. Since the query builder implements a to string method this works perfectly in production mode without the debug toolbar. 

When the debug toolbar is enabled symfony tries to serialize the `sql` index in the `Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector` But in case of an non serializable object this will break the execution. 

**How to reproduce**  
Code block below will trigger the error when used in a controller. 

```
$queryBuilder = $this->entityManager->getConnection()->createQueryBuilder();
$queryBuilder->select('id')->from('table');
$this->entityManager->createNativeQuery($queryBuilder, $rsm);
$query->getArrayResult();
```
**Possible Solution**  
In `Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector`  the `sanitizeQuery` method needs a simple extra cast to fix this issue.
```
    private function sanitizeQuery($connectionName, $query)
    {
        $query['sql'] = (string)$query['sql'];
```

We do agree that the code above is not the most usual code to write. But since doctrine allows it we would expect it to work in combination with the symfony bridge package.

**Comment by stof** [comment]
So, is DBAL passing the QueryBuilder object to its logger, while the documented type is `string` ? That would be a bug in DBAL itself.

**Comment by jaapio** [comment]
Could be a true story, although the `DoctrineDataCollector` in symfony is trying to serialize something that is not a string, which results in to very hard to track errors. 

I will make a PR for doctrine to fix this issue. in the end it is just about missing type hints, which didn't exist a the moment of writing. I would personally filter the results that are added to the profiler as well. You expect a string. So force it to be one :-).

**Comment by jaapio** [comment]
Doctrine won't fix this issue by now. It will be resolved in the future with stricter typehints. From a user point of view it would be nice to have a more descriptive error here but we will fix this issue on our side.
