### ISSUE TITLE
[DotEnv] .env.local should override existing defined variables

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#29647]
**Symfony version(s) affected**: 4.2.1

**Description**  
I'm following the new approach to .env files [as described here](https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions).

My `.env` file contains:
```ini
APP_ENV=dev
APP_DEBUG=1
STRIPE_KEY=
```

And my `.env.local` file contains:
```ini
STRIPE_KEY=MY_KEY
```

When I create a service that injects this `%env(STRIPE_KEY)%` it's always empty.

When I remove the `STRIPE_KEY=` placeholder from my `.env` file it suddenly works.

The issue is that it first loads the `.env` file, sets the `STRIPE_KEY` to blank, then loads the `.env.local` file and just skips the `STRIPE_KEY=MY_KEY` because it's already defined.

**Possible Solution**  
Always let `.env.local` override the environment variables defined in `.env`

**Comment by ro0NL** [comment]
Could it be e.g. docker detects up `.env` and creates real vars as such? Renaming it to `.env.dist` worked for me (#29170 + #29171)

**Comment by ruudk** [comment]
@ro0NL Thanks, but I'm not running this inside Docker.

**Comment by ro0NL** [comment]
So no "real env vars" are involved? I was unable to reproduce it actually, for me it seems to just work (i both tested .env OR .env.dist with AND without .env.local, and `bin/console about` confirms the right values.

**Comment by xabbuh** [comment]
@ruudk Can you create an example application that allows to reproduce?

**Comment by ruudk** [comment]
I'm sorry but I just checked out a new project, and it just works like you expect it to work. Then I retried on my own project and it worked. I feel really silly now :( Thanks for the fast help, not sure what was going wrong.

**Comment by ruudk** [comment]
Ok, it appears that the issue is related to Symfony Cloud CLI tool not reading the .env files. 

## How to reproduce?

```
$ composer create-project symfony/website-skeleton my-project
$ cd my-project/
$ symfony php bin/console about
# Doesn't output any environment variables

$ bin/console about
# Does print all the expected variables.
```

I guess I have to report this at https://github.com/symfonycorp/symfony-cli-issues?

**Comment by ruudk** [comment]
Found out that the issue is that Symfony CLI passes `APP_ENV=dev` to the commands it runs via `symfony php` causing the `.env.local` to be ignored.
