### ISSUE TITLE
boot kernel in test env make phpdbg crashing

### ISSUE THREAD

**Issue by Jerome1337** [symfony/symfony#29656]
**Symfony version(s) affected**: 4.2

**Description**  
I am trying to use phpdbg with phpunit for generate code coverage.
When I'm creating functional tests and need to boot Symfony kernel, phpdbg stop test execution when kernel is booting or booted.

**How to reproduce**  
Create a simple functional test extending `WebTestCase` and try to boot the kernel inside.

```
<?php

declare(strict_types=1);

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class FooTest extends WebTestCase 
{
    public function test() {
        static::bootKernel();

        $this->assertTrue(true);
    }
}
```

Then launch this test using 

```
phpdbg -qrr vendor/bin/phpunit tests/FooTest.php --debug --coverage-php coverage/coverage.php --colors=never
```

The test is started but never finished and phpdbg suddenly stop

```
jerome@c40bded3150d:/code$ phpdbg -qrr vendor/bin/phpunit tests/FooTest.php --debug --coverage-php coverage_parts/coverage_1588.php --colors=never

 // Clearing the cache for the test environment with debug true                                                         

 [OK] Cache for the "test" environment (debug=true) was successfully cleared.                                           

PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Test 'App\Tests\FooTest::test' started
```

**Additional context**  
I use:

- Symfony http kernel v4.2
- phpunit 7.5.1
- phpdbg 0.5.0

You can have exactly the same env I use with https://hub.docker.com/r/jerome1337/php-dev

**Comment by Jerome1337** [comment]
@stof I updated it

**Comment by nicolas-grekas** [comment]
A crash is a bug in phpdbg, nothing we can do on the PHP side...
