### ISSUE TITLE
Deprecated MessageSelector is being used by default in FrameworkBundle 3.4

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#29655]
**Symfony version(s) affected**: 3.4.*

**Description**  
In cross-component environment when FrameworkBundle is 3.4.* and Translation is 4.2.*, deprecated MessageSelector is being used by default, which triggers deprecation and fails the build

**How to reproduce**  
https://github.com/doctrine/DoctrineBundle/pull/892

**Possible Solution**  
Check from inside compiler pass in FrameworkBundle if default translator service is being used with default MessageSelector service and if so, replace it with identity translator?

**Comment by nicolas-grekas** [comment]
I didn't have a look at this specific case so see which deprecated code path is taken.
But in the generic case, we can't make any promises about running old versions deprecations free.

Only 4.2 components are covered.

**Comment by ostrolucky** [comment]
Yeah I know you can't, that would require you to test it and testing all the possible combination of components would be tough. These issues can still be fixed at least retroactively. Not fixing such issues might lead ecosystem to locking out installing component versions which introduce these deprecations or silencing the deprecations helper. Both would weaken the test suite.

**Comment by nicolas-grekas** [comment]
As far as I understood correctly, the doctrine bundle failure was due to a badly configured bridge: running the bundle's test suite with Symfony 3.4 should ignore deprecations for sure.
Only the matrix with Symfony 4.2 should fail on deprecations.
Closing as this is expected. Providing forward compat of 3.4 with 4.2 is out of maintenance work.
