### ISSUE TITLE
Response status code from start() of GuardAuthenticator is ignored

### ISSUE THREAD

**Issue by ant5** [symfony/symfony#29657]
**Symfony version(s) affected**: 4.1.6

**Description**  

Status code of response returned  from a start() method of AbstractGuardAuthenticator derived class somewhere later is overrided  to 403 Access Denied.

**How to reproduce**  

For such a Guard class

class MyAcator extends AbstractGuardAuthenticator 
{...
    public function start(Request $request, AuthenticationException $authException = null)
    {
      return  new Response("<html><body>Please, login somehow.</body></html>", 449);
    }
...
}

result is a 403 response code. Not 449.

**Possible Solution**  

**Additional context**

**Comment by ant5** [comment]
It is something related to  $event->allowCustomResponseCode(). May be if start() of Guard could reach $event then issue can be workarounded.

There was a similiar issue: https://github.com/symfony/symfony/issues/22019
The answer in the past was: 
"Basically, Symfony overrides the status code when there is an exception, but sometimes, we need another one. It's very rare. And by the way, I would not even talk about that on the blog post as end users should never use that."

But now there is a Guard start() and it is here to give a user custom response. It is technically treated as an Exception but logically it is for customizing. An Exception logic has overlapped the function application logic.

To fix this I suggest to insert $event->allowCustomResponseCode() before calling startAuthentication().
The closest position in stack I found where $event can be reached is in security/Http/Firewall/ExceptionListener.php in function handleAccessDeniedException().
The patch may look like:
    $insufficientAuthenticationException->setToken($token);
 +$event->allowCustomResponseCode();
   $event->setResponse($this->startAuthentication(...);

**Comment by ant5** [comment]
Patch fo symfony 4.2

**Comment by Simperfit** [comment]
@ant5 Could you please submit a pull request with this patch so we can look into and tell you if it's the right way to do this.
