### ISSUE TITLE
ErrorHandler missing for OutOfMemoryException

### ISSUE THREAD

**Issue by OneEyedSpaceFish** [symfony/symfony#29663]
**Symfony version(s) affected**:
All versions after the '`Kernel` -> `Debug` exception handling' migration, including latest master

**Description** 
It seems that after the `Kernel` -> `Debug` migration took place, there were no error handlers added to match the new exception being thrown.

This ultimately prevents any internal error handling / event capture being used for this scenario, and if this is thrown, that would result in a 500 response with no response body being returned.

Our application handled this exception prior to Debug component migration, and added our custom response body.

The exception:
[OutOfMemoryException.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php)

Missing ErrorHandler in folder:
[FatalErrorHandler](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/FatalErrorHandler)

**How to reproduce**  
Either throw this exception manually, or lower PHP mem limit to force this issue to occur naturally.

**Possible Solution**  
Add Error handler for `OutOfMemoryException` and ensure that no other Exceptions have been missed.

**Additional context**  
  [Response] 500
  [ResponseBody] -none-

**Comment by nicolas-grekas** [comment]
I'm closing this because the discussion on #30795 didn't conclude why this is needed.
Please provide more hints and we'll reconsider.

**Comment by OneEyedSpaceFish** [comment]
See comment https://github.com/symfony/symfony/pull/30795#issuecomment-509180267
