### ISSUE TITLE
[Messenger] Automatically clear the entity manager at each message consumption

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#29662]
**Description**  

@sroze Hi, do you think there is any good way to automatize the doctrine entity manager clear between message consumption? Do you think it could be a good idea to provide an embedded middleware to do this on `Received` stamped messages for example?

The use case is: when the worker is running (and not stopped between each messages), if an entity is fetched from the database, it may not be refresh between two messages handling. For example, in the case of an user account recovery process (email sent async with messenger and amqp), if the email address is updated after the first try, the second email is send to the old email address.

**Comment by ogizanagi** [comment]
Makes sense to me 😉

**Comment by sroze** [comment]
Makes sense to me as well to ship such a middleware within the DoctrineBundle 👍

**Comment by Spawnrad** [comment]
Need this fonctionnality too. :)

**Comment by fakenberg** [comment]
$this->entityManager->clear(); ?

**Comment by zmitic** [comment]
Shouldn't that happen with all resettable services?

**Comment by ogizanagi** [comment]
Resettable services are only reset on next kernel `boot()` call. Also, only for requests (`\Symfony\Component\HttpKernel\Kernel::handle`). So it won't happen in CLI. This feature request is about clearing the manager while the worker command is executing.
Clearing it between each handling inside a middleware will provide state isolation and save memory.
