### ISSUE TITLE
[Tests] Add internal annotation tag to all stubs used for tests

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#29677]
**Description**  
Hello,

I would like to create a PR adding the `@internal` annotation to all stub classes that are used for tests..

Would it be accepted something like this?

**Comment by nicolas-grekas** [comment]
I'd be OK, but why are you proposing this?
Related to https://github.com/symfony/symfony/pull/29602?

**Comment by gmponos** [comment]
It will be a clear indication if I use a wrong stub because PHPStorm highlights it with a strike through... also you never know.. one day PHPStorm might be able to distinguish those marked as internal or sort them lower...

**Comment by gmponos** [comment]
Furthermore it will make it even more clear to developers if they use one of these that they are not under the BC promise... except if they are...

**Comment by ogizanagi** [comment]
They're not. I was going to answer everything under `Tests` namespace is implicitly not covered by BC promise and should not be used anyway, hence no need to be marked `@internal`. 
But given that would make it explicit and appear in IDEs as being wrong, this suggestion makes sense to me.

**Comment by nicolas-grekas** [comment]
I'm not sure what you mean by "stub" btw. To me, all classes in any `*\Tests\*` could be marked as `@internal` (except when a test expects the annotation to be here of course).
It would be great to make it a php-cs-fixer rule btw.

**Comment by gmponos** [comment]
Closing let's continue the discussion [here](#29689)
