### ISSUE TITLE
Route variable with slash at the end makes redirect

### ISSUE THREAD

**Issue by dzamyatin** [symfony/symfony#29673]
**Symfony version(s) affected**: 4.2.1

**Description**  
I have a redirect problem with urls which contain variable with part of some path at the end, like this: 

>foo/somefolder/somefolder/

My route config for this looks like:

```
/**
     *@Route(
     *     "/some/{path}",
     *     methods={"GET"},
     *     requirements={"path"=".+"}
     * )
*/
```

The problem is when variable path contain slash at the end of string i get redirect to path without slash but the slash it is a part of variable

**Possible Solution**  
Check if the end of the route is a variable don't make a redirect

**Comment by nicolas-grekas** [comment]
Can you please check 4.2@dev? It's been fixed recently I think.

**Comment by dzamyatin** [comment]
Nope, it doesn't working for me. But when i commented out that place my problem was solved. 

somewhere here
vendor/symfony/routing/Matcher/Dumper/PhpMatcherTrait.php:133

```
if ('/' === $pathinfo || (!$hasTrailingSlash ? '/' !== $pathinfo[-1] || !preg_match($regex, substr($pathinfo, 0, -1), $n) || $m !== (int) $n['MARK'] : '/' === $pathinfo[-1])) {
    // no-op
} elseif ($this instanceof RedirectableUrlMatcherInterface) {
    return null;
} else {
    continue;
}
```

**Comment by nicolas-grekas** [comment]
Note that the redirection is expected. What's not expected is the slash being part of the var.

**Comment by Tobion** [comment]
The redirection is not expected. The requirement for the variable allows the slash (.+). How else would you achieve exactly what is asked here?

**Comment by nicolas-grekas** [comment]
The current logic is the following:
- when a route is declared with a trailing slash, the trimmed-slash url is redirected to the one with the slash
- when a route is declared with *no* trailing slash, the slashed url is redirected to the trimmed-slash one

That includes routes with slash-greedy requirements: when the same greedy requirement matches both the slashed and the trimmed-slash URLs, only one of them is considered the canonical one and a redirection happens.

So yes, the current behavior is expected.

We could fine tune this logic and make an exception when a trailing slash-greedy requirement is declared with no explicit trailing slash after it. (ie disable any redirections for `/foo/{.*}` but keep it for `/foo/{.*}/`. That would mean `/foo/bar` and `/foo/bar/` wouldn't trigger the redirection for route `/foo/{.*}`, breaking the "not-semantics" property of trailing slashes for catch-all routes. Which might be legit afterall.

**Comment by Tobion** [comment]
I'm pretty sure this redirection did not happen before and thus is a bc break. Your suggested solution seems necessary.
