### ISSUE TITLE
Entity not found but entity exists!

### ISSUE THREAD

**Issue by Anan5a** [symfony/symfony#29682]
**Symfony version(s) affected**: 4.2.x

**Description**  
Symfony says that ``` Entity ``` ``` App\Entity\File ``` Not found. But in reality the Entity exists.
When I use it in a ``` controller ``` named ``` FileViewController ``` this happens but when I use the same Entity in ``` FileController ``` everything works normal! The FileController does write operations and the FileViewController does read operations.
# Screenshots
![img_20181225_070822](https://user-images.githubusercontent.com/16373480/50408614-5d5a1c00-0816-11e9-85dd-d9612dc922ba.JPG)
![img_20181225_070756](https://user-images.githubusercontent.com/16373480/50408625-634ffd00-0816-11e9-8931-3376a7af16e1.JPG)

Now I'm so frustrated why this happens. :'(

**Comment by xabbuh** [comment]
The error message is not about the class not existing. It is telling you that there is no entity manager named the same as the entity's class name. I guess you rather want to use the `getManagerForClass()` method instead.

**Comment by Anan5a** [comment]
I mistyped this line
``` $em = $this->getDoctrine()->getManager() ```
Which should be
``` $em = $this->getDoctrine()->getRepository() ```
Sorry for the typo mistake
