### ISSUE TITLE
Constructor argument type typo in CustomUserMessageAuthenticationException

### ISSUE THREAD

**Issue by archi-tektur** [symfony/symfony#29687]
**Symfony version(s) affected**: 4.2.1

**Description**  
Hey, in `CustomUserMessageAuthenticationException` is an typo in constructor argument, message is required to be a `string`, not `\string` which may false inform IDE about argument type.

**How to reproduce**  
throw CustomUserMessageAuthenticationException with parameter `'anything'`, most IDE's will show error: 
`__ Expected Symfony\Component\Security\Core\Exception\string, got string`__.
AFAIK it may causes some weird bugs

**Possible Solution**  
Add slash before `string`

**Additional context**  
Error also exists in Symfony\Component\Security\Csrf\CsrfToken class, same problem: no slash.

**Comment by xabbuh** [comment]
The error message makes me think that you ran the code using PHP 5 where scalar type hints didn't exist and thus `string` would be interpreted as a class from the current namespace instead.

**Comment by archi-tektur** [comment]
Code is ran with PHP 7.2.12

**Comment by archi-tektur** [comment]
OK, sorry, PhpStorm read the version of interpreter from Composer where Symfony 4.2.1 requires PHP 7.1.3 which seems to not support scalar type hints.

**Comment by xabbuh** [comment]
@archi-tektur PHP 7.1.3 does support scalar type hints. There's probably something else (explicit interpreter config maybe) that's makes your PhpStorm use a PHP 5 parser.
