### ISSUE TITLE
[Tests] make all tests final

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#29689]
Reason of this:

1. Since tests are not under BC promise someone should not extend them.. You could ask "why someone to extend a test of symfony?"... I think we all have see an lot of weird stuff out there
2. PHPStorm improvements for autocompletion while typing `MyClass extends T.....` it will not show the tests..

This is a little bit different from https://github.com/symfony/symfony/issues/29677 ... because `internal` will be used only for stubs and will prevent them from be used in the actual code and hopefully at some point PHPStorm will improve search on this..

Let me know if I can submit a PR about this...

**Comment by gmponos** [comment]
ofc Abstract classes and `TestCases` that are meant for extending are not include in this..

**Comment by lyrixx** [comment]
I disagree with this move. It's useful to reuse symfony tests while extending symfony

**Comment by nicolas-grekas** [comment]
I agree with @lyrixx, this is too much. We already label tests as out of the BC promise, that's enough to me, no need to actively forbid extending if someone really what to.

**Comment by xabbuh** [comment]
#29677 sounds like a better approach to me

**Comment by gmponos** [comment]
OK.. let me elaborate both of the issues here.

@nicolas-grekas as a stub I describe classes like [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/Fixtures/common.inc#L54) or [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/PdoSessionHandlerTest.php#L365).. maybe my definition of stub is wrong... 

Now that we cleared out this.. my thinking is:

**Mark all tests and stubs as final.**

- Let's take the case of `SessionHandler`. By having stubs as final it is forcing into moving developers to submit a `TestSessionHandler` having it under if they need it instead of going with the easy solution of using a Mock that it is internal and should be highly avoided..
- No discoverability from PHPStorm... For me this is a huge thing.
- @lyrixx no reason to have a `Class A extends B` and also have a `class ATest extend BTest`. This will rerun tests of class `B`. Developers need to understand that things of Class `B` are already tested by symfony and there is no reason to re-test them. ofc there could be exceptions that should not be marked as final like `FormTypes`

**About `@internal` annotation.**

Internal annotation will be an indication that although symfony includes the `Tests` when requiring it they are not under BC promise as everyone would understand.
Benefits here are not great since the maintenance cost is huge and as I noticed the `strike-through` appears only on namespace or if you add `@internal` to the constructor.

To tell you the truth after some comments I had on other PR about maintenance cost my intention was not to proceed with `@internal` after all. If you guys disliked the maintenance cost on things like `$this->willThrowException` then certainly you will hate this... and @nicolas-grekas on this one I do agree that this is something that it is better to be handled from a `fixer`..

**Why having final and `@internal`

- Final solves the problem of not extending a class that should not be extended and removes it from auto-suggestion of PHPStorm.
- Internal solves the problem when I use/initialize an object.

For me `final` is more important...

**Comment by lyrixx** [comment]
> * @lyrixx no reason to have a `Class A extends B` and also have a `class ATest extend BTest`. This will rerun tests of class `B`. Developers need to understand that things of Class `B` are already tested by symfony and there is no reason to re-test them. ofc there could be exceptions that should not be marked as final like `FormTypes`

I disagree. Suppose I want to decorate the Symfony Router to add a new feature. My test will extends Symfony test. Like that I'm sure I did not break the existing feature of the Symfony Router thanks to existing test.

**Comment by chalasr** [comment]
Although I don't think we need to mark them final, I would strongly recommend to never extend a Symfony test class (the ones under the `*\Tests\` namespace). 
Extending them sounds super fragile as it's likely to break at some point. You don't have to unit test your vendors, that does not make sense.

> Suppose I want to decorate the Symfony Router to add a new feature.

Then the decorated router should just be mocked, and your decorator test should just assert that the good methods are called on the decorated. 
Your decorator is not responsible of the decorated behavior and as such, your unit tests does not have to cover it (and should not). And, if you really want to test your vendor, I'd suggest copy pasting rather than extending. Nobody should rely on vendor test classes, really.

**Comment by ro0NL** [comment]
> PHPStorm improvements for autocompletion while typing MyClass extends T..... it will not show the tests..

Note you can mark them as Tests folder or exclude the directories fully. But it's super tedious :P unless someone knows a workaround to use wildcards :sweat_smile:

**Comment by PabloKowalczyk** [comment]
What about `.gitattributes` file with `/Tests export-ignore` line? `zip` file generated by GitHub will exclude all files from `/Tests` directory, so when user installs Symfony's components by Composer with `--prefer-dist` switch there won't be any tests classes. This would also means smaller artifacts on production, because there are no, useless, tests classes.
WDYT?

**Comment by gmponos** [comment]
This has been suggested a lot of times... I was driven by that and that's why I suggested this alternative...

**Comment by PabloKowalczyk** [comment]
Why `.gitattributes` was rejected?

**Comment by gmponos** [comment]
> Why .gitattributes was rejected?

If I remember correctly there are a lot issues like this.. if you search you can find one and discuss it there.. no need to open this discussion here again :)

**Comment by nicolas-grekas** [comment]
Closing as adding `final` would be rejected, and adding `@internal` would duplicate what the doc already says (no BC promise on `Tests` namespaces).
