### ISSUE TITLE
'm' is not a time placeholder (isPatternDateOnly), it is for month. for time it is H, i, s.

### ISSUE THREAD

**Issue by hardikaspl** [symfony/symfony#29683]
**Symfony version(s) affected**: x.y.z

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
Can you provide some more details? What did you try? What happened? What did you expect instead?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by hardikaspl** [comment]
Its related to 

namespace Symfony\Component\Form\Extension\Core\DataTransformer

```
class DateTimeToLocalizedStringTransformer extends BaseDateTimeTransformer
{
    /**
     * Checks if the pattern contains only a date.
     *
     * @return bool
     */
    protected function isPatternDateOnly()
    {
        if (null === $this->pattern) {
            return false;
        }

        // strip escaped text
        $pattern = preg_replace("#'(.*?)'#", '', $this->pattern);

        // check for the absence of time-related placeholders
        return 0 === preg_match('#[ahHkKmsSAzZOvVxX]#', $pattern);
    }
}

As you can see the 'm' is present in preg_match function. it shouldn't be there to check 'Date' pattern.
```

**Comment by gharlan** [comment]
@hardikaspl it is a intl pattern (`IntlDateFormatter`), and there `m` is used for minutes: http://userguide.icu-project.org/formatparse/datetime
