### ISSUE TITLE
[DependencyInjection] Regression? - Serialization of 'Closure' is not allowed 

### ISSUE THREAD

**Issue by mantis** [symfony/symfony#29694]
**Symfony version(s) affected**: 4.?

**Description**  
Have just updated symfony and now getting an error "Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in symfony\dependency-injection\Compiler\RemoveUnusedDefinitionsPass.php"

I *believe* I may be hitting the issue due to the the following change:

https://github.com/symfony/dependency-injection/commit/465af9012190665606f1355c34f508b12faf1ad4#diff-4995ff3c23fc152e94bb1d845e198c62L73

However, the cause is as follows:

1. RemoveUnusedDefintions.php calls 'serialize' on a Definition object
2. Definition object stores a list of 'errors'. This is set in lines 885-888 of Definition.php in the addError function; which takes a string|\Closure
3. Trying to serialize a dependency with a previous error generates due to the \Closure argument

**Comment by nicolas-grekas** [comment]
This bug happens only when using the master branch of the DI component.
Thanks for reporting! And double check you don't use master in your project :)
