### ISSUE TITLE
Circular reference detected for service "doctrine.orm.default_entity_manager"

### ISSUE THREAD

**Issue by konshensx16** [symfony/symfony#29693]
**Symfony version(s) affected**: 4.2.1

**Description**  
ServiceCircularReferenceException is thrown when i try to inject a repository in a listener's constructor, one important note is that i have the same exact code that i'm posting right here in a 4.1.6 project and it works just fine, here are the important parts of the code:
PostListener (where seems to be the problem):
```php
<?php

namespace App\Listeners;

use App\Entity\Post;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use App\Repository\AttachmentRepository;

class PostListener
{
    private $attachmentRepository;

    public function __construct(AttachmentRepository $attachmentRepository)
    {
        $this->$attachmentRepository = $attachmentRepository;
    }

    public function preUpdate(Post $post, PreUpdateEventArgs $args)
    {
        dump($this->attachmentRepository->findAll());
    }
}
```
services.yaml:
```yaml
services:
    # default configuration for services in *this* file
    #...... default configuration removed for clarity 
    App\Listeners\PostListener:
        tags:
            - { name: doctrine.orm.entity_listener }
```
Post.php:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @ORM\EntityListeners({"App\Listeners\PostListener"})
 */
class Post
{

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Attachment", mappedBy="post")
     *
     * @var [type]
     */
    private $attachments;
}

```

Attachment.php:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttachmentRepository")
 */
class Attachment
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="attachments")
     *
     * @var [type]
     */
    private $post;
 
}

```

**How to reproduce**  
Git repository to recreate the problem: https://github.com/konshensx16/circular-reference
Navigating to localhost:8000/post should be enough since i can't even start the server because of the problem, but if that doesn't work, triggering the PostListener by updating a post's content field should 100% throw the exception.

**Additional context**  
As mentioned before i have the same exact code in version 4.1.6 and it works perfectly fine.

Thank you in advance :)

**Comment by eb22fbb4** [comment]
You shoud not inject ``App\Repository\AttachmentRepository`` in to ``App\Listeners\PostListener``，the ``EntityMangaer`` is included into ``Doctrine\ORM\Event\PreUpdateEventArgs``:

```
<?php

namespace App\Listeners;

use App\Entity\Post;
use App\Entity\Attachment;
use Doctrine\ORM\Event\PreUpdateEventArgs;

class PostListener
{
    public function preUpdate(Post $post, PreUpdateEventArgs $args)
    {
        $attachmentRepository = $args->getEntityManager()->getRepository(Attachment::class);
        dump($attachmentRepository->findAll());
    }
}
```

**Comment by konshensx16** [comment]
Hey there mate, thank you for the response,

Yes using the EntityManager that's in $args would work ,but the problem is i have the same exact code where i inject the AttachmentRepository in PostListener's construcor and it worksm which makes me think this is a bug with the new version because i can find any chnages log reporting any changes in terms of injecting Repositories in Listeners.

**Comment by javiereguiluz** [comment]
@konshensx16 thanks for reporting this issue. you said that this works in `4.1.6` but not in `4.2.1`. In order to debug this faster, we'd need to know the first version which breaks your app. Could you please try with `4.1.7`, `4.1.8`, `4.1.9` and `4.2.0` and tell us which is the first version that breaks your app? Thanks!

**Comment by xabbuh** [comment]
Maybe caused be the same change that causes #29637? Can you check if the commit mentioned there made the difference in your application too?

**Comment by konshensx16** [comment]
Hello @javiereguiluz  and @xabbuh thanks for replying to this, i just want to address one weird thing i just noticed like 5 minutes ago when i was doing more tests, the code i posted above isn't working obviously and throwing the exception, but this one WORKS and i cannot seem to undertand why:
```php
<?php

namespace App\Listeners;

use App\Entity\Attachment;
use App\Entity\Post; 
use App\Repository\AttachmentRepository; 
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Symfony\Component\Security\Core\Security;

class PostListener
{
    // i need to get the current logged in user
    /**
     * @var Security
     */
    private $security;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager; 
    /**
     * @var AttachmentRepository
     */
    private $attachmentRepository;
    
    public function __construct(Security $security,
                                EntityManagerInterface $entityManager,
                                AttachmentRepository $attachmentRepository
    )
    {
        $this->security = $security;
        $this->entityManager = $entityManager;
        $this->attachmentRepository = $attachmentRepository;
    }

    public function preUpdate(Post $post, PreUpdateEventArgs $args)
    {
    	dump($this->attachmentRepository->findAll()); die;
    }

}
```
You guys have any idea why this would work and the ther one won't? Does injecting the                               EntityManagerInterface has something to do with it ?
