### ISSUE TITLE
[FrameworkBundle] Incorrect dependency on BrowserKit 

### ISSUE THREAD

**Issue by leongersen** [symfony/symfony#29696]
**Symfony version(s) affected**: 2.8 - 4.2

**Description**  
FrameworkBundle has a direct dependency on the BrowserKit component in `framework-bundle/Client.php`. BrowserKit is only listed as a dev-dependency. If BrowserKit happens not to be installed, autoloading fails in `vendor/symfony/framework-bundle/Client.php:28`.

**How to reproduce**  
- Have an (indirect) dependency on `FrameworkBundle`
- Do not have `BrowserKit` installed
- Load `Client.php` in `FrameworkBundle`

**Possible Solution**  
- Move `BrowserKit` from the `require-dev` to the `require` section

**Comment by ro0NL** [comment]
it's part of the `test-pack`: https://github.com/symfony/test-pack/blob/1792b80cc2da5310e84afa983682b71dfc409d17/composer.json#L8

So with `composer require test-pack` the experience is better.

Looking at code we might cleanup the `test.client` service is browser-kit is unavailable, and throw a meaningful error message in WebTestCase (AFAIK it's the only instance using it).

**Comment by xabbuh** [comment]
Providing a meaningful error message sounds like a good idea to me.
