### ISSUE TITLE
Routing with slashes

### ISSUE THREAD

**Issue by bobahvas** [symfony/symfony#29706]
**Symfony version(s) affected**: 4.2.1

**Description**  
I am trying to make POST request to url
`POST http://localhost:3000/api`
and receive response like
```{"message":"No route found for \u0022POST \/api\u0022"}```

But `POST http://localhost:3000/api/` available

I have read this section too
https://symfony.com/doc/current/routing.html#redirecting-urls-with-trailing-slashes

How to remove slash from the end when I make POST requests?

**How to reproduce**  
`routes.php`
```
<?php

use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Routing\Route;

# Api
$routesApi = new RouteCollection();
$routesApi->add('api', (new Route(''))
    ->setDefault('_controller', [App\Controller\Api\DefaultController::class, 'index'])
    ->setMethods('POST')
);
$routesApi->addPrefix('api');
$routesApi->addNamePrefix('api_');

# Default app
$routes = new RouteCollection();
$routes->addCollection($routesApi);

return $routes;
```

Router debug
```
[vagrant@localhost htdocs]$ php bin/console debug:router
 ------------------ -------- -------- ------ --------------------------
  Name               Method   Scheme   Host   Path
 ------------------ -------- -------- ------ --------------------------
  api_api            POST     ANY      ANY    /api/
 ------------------ -------- -------- ------ --------------------------
```

**Comment by Tobion** [comment]
The solution to this problem is explained in https://symfony.com/blog/new-in-symfony-4-1-configurable-trailing-slash-on-imported-routes

If you prefer to build routes using php, you can use the php configurator, see https://github.com/nicolas-grekas/symfony/blob/af038a6067b03751aac09cef4545e29557e638ff/src/Symfony/Component/Routing/Loader/Configurator/ImportConfigurator.php#L44

In the future, in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by bobahvas** [comment]
@Tobion I have extended default `RouteCollection` and have added a new method.
Can something like my solution be as part of core?

Will be very useful something very simple, like trailing slash with yaml
https://symfony.com/blog/new-in-symfony-4-1-configurable-trailing-slash-on-imported-routes

Usage like
```
$routesApi = new RouteCollection();
$routesApi->add('root', (new Route('/'))
    ->setDefault('_controller', [App\Controller\Api\DefaultController::class, 'index'])
    ->setMethods('POST') // For tests
);
$routesApi->addPrefix('/api');
$routesApi->addNamePrefix('api_');
$routesApi->trailingSlashOnRoot(false, '/api');
```

Class
```
<?php

namespace App\Component;

use Symfony\Component\Routing\Route;

class RouteCollection extends \Symfony\Component\Routing\RouteCollection
{
    public function trailingSlashOnRoot($value = true, $prefix = ''): void
    {
        $rootPath = (new Route(trim(trim($prefix), '/') . '/'))->getPath();
        foreach ($this->all() as $route) {
            if ($route->getPath() === $rootPath) {
                $path = rtrim($route->getPath(), '/');
                if ($value) {
                    $route->setPath($path . '/');
                } else {
                    $route->setPath($path);
                }
            }
        }
    }
}
```

Instead of 
```
$routes = new RouteCollection();

$routesApi = new RouteCollection();
$routesApi->add('root', (new Route('/'))
    ->setDefault('_controller', [App\Controller\Api\DefaultController::class, 'index'])
    ->setMethods('POST')
);

(new ImportConfigurator($routes, $routesApi))->prefix('', false);

$routesApi->addPrefix('/api');
$routesApi->addNamePrefix('api_');

return $routes;
```
