### ISSUE TITLE
[VarDumper] fwrite(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#29709]
**Symfony version(s) affected**: master, may be more version

**Description**  

I'm working on buzz and when I try do dump something I got this theses warnings:

```
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in /home/gregoire/dev/github.com/symfony/var-dumper/Dumper/AbstractDumper.php on line 181

Warning: fwrite(): supplied resource is not a valid stream resource in /home/gregoire/dev/github.com/symfony/var-dumper/Dumper/AbstractDumper.php on line 181
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in /home/gregoire/dev/github.com/symfony/var-dumper/Dumper/AbstractDumper.php on line 181

Warning: fwrite(): supplied resource is not a valid stream resource in /home/gregoire/dev/github.com/symfony/var-dumper/Dumper/AbstractDumper.php on line 181
```

**How to reproduce**  

I have pushed to my fork some code to reproduce
https://github.com/lyrixx/Buzz/commit/f49e5877d031f3d8455c212058317df892315015
and the following script is needed to trigger the error:

```php
<?php

use Buzz\Client\MultiCurl;
use Nyholm\Psr7\Factory\MessageFactory;
use Nyholm\Psr7\Factory\Psr17Factory;
use Nyholm\Psr7\Request;

require __DIR__.'/vendor/autoload.php';

$client = new MultiCurl(new Psr17Factory(), [
    'timeout' => 4,
    'max_filesize' => 1024,
]);

$client->sendRequest(new Request('GET', 'http://httpbin.org/delay/1'));
```

**Comment by nicolas-grekas** [comment]
The reason is that this callback is run at destruction time, where dump's output stream has been closed by PHP shutdown sequence.
We could work around by doing this in AbstractDumper L181:
```php
            if ('Unknown' === get_resource_type($this->outputStream)) {
                echo str_repeat($indentPad, $depth).$line."\n";
            } else {
                fwrite($this->outputStream, str_repeat($indentPad, $depth).$line."\n");
            }
```

Then, you'll be left with `PHP Warning:  Unknown: Cannot call the CURLOPT_PROGRESSFUNCTION in Unknown on line 0`.

Maybe that's not something we should fix?

**Comment by lyrixx** [comment]
I don't know. This is the first time I hit this error. I may be the only-one too :/ We are doing weird things :)

**Comment by lyrixx** [comment]
> Maybe that's not something we should fix?

Let's close it.
