### ISSUE TITLE
[Validator][Profiler] No validator collected in case of Validation::createValidator

### ISSUE THREAD

**Issue by lerminou** [symfony/symfony#29700]
**Symfony version(s) affected**: 4.2.1

**Description**  
In the profiler, no informations are displayed in case of a failed validation if we build a fresh validator from Validation::createValidator();

**How to reproduce**  
I just tried to reproduce the example in the article from the official blog, and I facing an issue if a validation fails.

```php
    public function getApplicationAction(Request $request)
    {
        $emailConstraint = new Assert\Email();
        $emailConstraint->message = 'Invalid email address';

        // use the validator to validate the value
        $validator = Validation::createValidator();

        $errors = $validator->validate("totor", $emailConstraint);

        if (0 === count($errors)) {
            var_dump('valid');
            // ... this IS a valid email address, do something
        } else {
            var_dump('error');
            // this is *not* a valid email address

            // ... do something with the error
        }
        return new Response();
    }
```
With this controller, anything is logged in the profiler in the validation tab.

It works if we inject ValidatorInterface in the arguments instead of using Validation::createValidator()
is this method `createValidator` usefull ??

**Additional context**  
https://symfony.com/blog/new-in-symfony-3-4-validator-information-in-the-symfony-profiler

**Comment by xabbuh** [comment]
This method is only useful if you need to create your own validator instance. When using the framework, you rather want to use the service wired by the FrameworkBundle as that will ensure that a validator collecting data for the profiler is enabled in the dev environment. If you set up the validator yourself, you would also need to make sure that the collecting validator would be set up and so on.

I am closing here as there is no bug to fix.
