### ISSUE TITLE
IntlDateFormatter Notice when passing null as second or third parameter

### ISSUE THREAD

**Issue by flack** [symfony/symfony#29705]
**Symfony version(s) affected**: v3.4.20 (but the code looks the same in master)

**Description**  

According to the PHP documentation, the `$datetype` and `$timetype` parameter can be `null`:

http://php.net/manual/en/intldateformatter.create.php

So this is a valid call:

```
$formatter = new IntlDateFormatter('en', null, null)
```

however, this produces the following notice:

```
Undefined index: 
vendor/symfony/intl/DateFormatter/IntlDateFormatter.php:606
vendor/symfony/intl/DateFormatter/IntlDateFormatter.php:498
vendor/symfony/intl/DateFormatter/IntlDateFormatter.php:148
```

**How to reproduce**  

See above

**Possible Solution**  

I'm not sure, but a naive fix would be to do something like this:

```php
if (self::NONE !== $this->datetype && null !== $this->datetype) {
```

in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php#L604 (and similarly below)

**Comment by xabbuh** [comment]
@flack According to the documentation only the `$timezone`, `$calendar`, and `$pattern` argument are nullable:

<img width="852" alt="bildschirmfoto 2018-12-31 um 11 04 56" src="https://user-images.githubusercontent.com/1957048/50558152-f47a1480-0ceb-11e9-9b63-45a43785de46.png">

 So passing `null` for `$datetype` or `$timetype` looks like a mistake to me.

**Comment by flack** [comment]
@xabbuh From the signatures it looks that way, yes, but read the parameter description:

<img width="805" alt="bildschirmfoto 2018-12-31 um 11 43 18" src="https://user-images.githubusercontent.com/425166/50558792-57ba7580-0cf1-11e9-8b0a-a91b403ccdef.png">

**Comment by xabbuh** [comment]
@flack Thanks, can you check if the native `IntlDateFormatter` class actually works this way?

**Comment by flack** [comment]
@xabbuh Tested in PHP 5.6:

```php
$formatter = new IntlDateFormatter('en', null, null);
echo $formatter->format(new DateTime);
// Monday, December 31, 2018 at 12:09:43 PM Central European Standard Time
```

So at least on this machine, `null` seems to be equivalent to ` IntlDateFormatter::FULL`

**Comment by xabbuh** [comment]
https://3v4l.org/uM5qg confirms this observation
