### ISSUE TITLE
[Messenger] Analyze (and improve?) performance

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#29713]
**Description**  
A few days ago, a performance comparison was published between Symfony's Messenger and another project called "mmasiukevich-service-bus":

https://github.com/mmasiukevich/performance-comparison

Given that our Messenger component is very recent, it's possible that it contains sub-optimized code. Let's check it! Thanks.

**Comment by mmasiukevich** [comment]
Messenger looks worse due to synchronous operation. Even if you just take a file and write the task code in it, the result will be the same.

**Comment by stof** [comment]
this benchmark is indeed not comparing one component to the other, but synchronous code vs asynchronous code (where the next message can be handled while waiting for the DB to insert things for the previous message).

**Comment by nicolas-grekas** [comment]
Closing then.
