### ISSUE TITLE
[Cache] Improve some error messages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#29710]
**Description**  
When I run some commands that make use of the cache, I get this:

```bash
$ ./bin/console app:some-command

10:45:08 WARNING [cache] Failed to save key "... some key ..." (array)
["key" => "... some key ...", "type" => "array", "exception" => null]
["log_uuid" => "cf01082a-0f5f-4b36-86e9-3b5a5ee6832a"]
```

No additional info is provided on `dev.log` either, so this is tricky to debug. Thanks to @nicolas-grekas this was restricted to either a serialization problem of the cached content or the use of APCu-based cache. In this case it wasn't a serialization issue because the content was a simple array.

Let's check if we can add more error messages (or improve the existing ones) to explain the error in more detail and provide, if possible, solutions to fix them. Thanks!

**Comment by Simperfit** [comment]
That could be a nice first issue IMHO.

**Comment by Deuchnord** [comment]
Taking this for the EUFOSSA hackaton

**Comment by Deuchnord** [comment]
@javiereguiluz could you please provide a reproducer?

**Comment by nicolas-grekas** [comment]
E.g. when trying to cache a `Closure` I think.

**Comment by Simperfit** [comment]
So I made a little SF command to reproduce: 
```
```

**Comment by Deuchnord** [comment]
Thank you for these details @Simperfit, I'll take a look to this and make a PR :)
