### ISSUE TITLE
Using a parameterised boolean `false` for the `lazy` tag

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony#29717]
**Symfony version(s) affected**: Symfony 4.1.7

**Description**  
Using a parameterised boolean `false` for the `lazy` tag won't recognise it as boolean value. Hence reason, the service `hello.service.calculator` below is never "lazy". It becomes lazy only if explicitly set is to `false`.

**How to reproduce** 

my_bundle.yaml
```
my_bundle:
    parameter:
        is_lazy: false
```
services.yaml
```
services:
    hello.service.calculator:
        class: AppBundle\Service\Calculator
        lazy: '%my_bundle.parameter.is_lazy%'
```

**Test**
```
$ bin/console debug:container hello.service.calculator
 ---------------- ----------
  Option           Value                                                                                                                                                                   
 ---------------- ----------
  Service ID       hello.service.calculator
  Lazy             yes
  ....
```

When I inject `'%my_bundle.parameter.is_lazy%'` into a dummy service to see the type and content I get `bool(false)` which proves that it is indeed a boolean false.

First of all, is this a bug? Then how can I use a parameter as shown above?

Thanks

**Note:** That parameter is configured in my bundle as `->booleanNode('is_lazy')->defaultTrue()->end()`.

**Comment by xabbuh** [comment]
The loaders do not take into account parameters for the `lazy` attribute. The provided value is simply cast to a boolean value which is `true` in this case.

**Comment by BentCoder** [comment]
So what you are saying is that there is no solution to this issue.....

**Comment by BentCoder** [comment]
The reason what this is needed is because some user might and some might not want to use `lazy` services for a given custom bundle. e.g. If I do any changes to the bundle files in vendors folder (_for any reason_), I'll have to clear the cache in the case of `lazy` services but not in the case of non `lazy` services. Hence reason, this option is being provided to the user.

I tried with integer configuration values as well but no luck.

```
->enumNode('is_lazy')
    ->cannotBeEmpty()
    ->values([0, 1])
    ->defaultValue(1)
    ->beforeNormalization()
        ->ifInArray([true, false])
            ->then(
                function ($value) {
                    return (int) $value;
                }
            )
    ->end()
->end()
```

So with this, if I set `'my_bundle.parameter.is_lazy'` to `true` or `false` in parameters, they are cast to integer `0` or `1`. This didn't help either.

**Comment by ogizanagi** [comment]
If this is part of a bundle and you want to expose this as a bundle option, you don't need to use a parameter.
Juste use a booleanNode (`NodeBuilder::booleanNode`) in Configuration and get the Definition from the bundle extension to call `Definition::setLazy()` accordingly.
Call `$container->getParameterBag()->resolveValue()` on processed config item if you expect the user to use a parameter.

**Comment by BentCoder** [comment]
Sorry I am little bit lost here.

This is currently what I do.

```
# class Configuration implements ConfigurationInterface
->booleanNode('is_lazy')
    ->defaultTrue()
->end()
```

```
# class MyBundleExtension extends Extension
$container->setParameter('my_bundle.parameter.is_lazy', $config['parameter']['is_lazy']);
```

```
# my_bundle.yaml
my_bundle:
    parameter:
        is_lazy: false
```

```
# services.yaml
services:
    hello.service.calculator:
        class: AppBundle\Service\Calculator
        lazy: '%my_bundle.parameter.is_lazy%'
```

What exactly should I do in order to match your advice? Please remember that I have to give user an option to set it manually - i.e. `false` or `true`.

Thanks

**Comment by BentCoder** [comment]
This didn't solve too: `lazy: '@=container.getParameter("my_bundle.parameter.is_lazy")'`

**Comment by jvasseur** [comment]
@BentCoder what you have to do is in your extension do a `$container->getDefinition('hello.service.calculator')->setLazy($config['parameter']['is_lazy'])` instead.

**Comment by xabbuh** [comment]
https://symfony.com/doc/current/bundles/configuration.html may provide some useful information on how you can achieve that.

**Comment by BentCoder** [comment]
@jvasseur Thanks for the answer. However, I have many services in my bundle and only some of of them depend on `my_bundle.parameter.is_lazy` parameter so I need some kind of dynamic logic rather than a static one.

**Comment by ogizanagi** [comment]
No parameters nor expressions are evaluated by file loaders for the lazy flag.
@jvasseur's sample is the solution you're seeking, though I'm not sure to understand your concerns about "dynamic" vs "static" logic here?

```php
$container->getDefinition('hello.service.calculator')->setLazy($config['parameter']['is_lazy'])
```

 is the same as what you expect with:

```yml
services:
    hello.service.calculator:
        class: AppBundle\Service\Calculator
        lazy: '%my_bundle.parameter.is_lazy%'
```

but one exposed parameter less and working.

**Comment by BentCoder** [comment]
What I meant is, I have many service definitions, not only `hello.service.calculator`, so this `$container->getDefinition('hello.service.calculator')->setLazy....` "static" logic is not feasible for me.

**Comment by ogizanagi** [comment]
Either adding `lazy` on each service definition in yaml files or calling `->setLazy()` on each is the same level of "static" logic here, isn't it? What's the difference?
We're talking about services provided by the bundle, right?

> If you guys say what I am after for lazy tag is impossible then I'll have to ditch the idea. Just let me know please.

As explained, this is currently not possible through DI config indeed. Only through container extensions or compiler passes.

**Comment by BentCoder** [comment]
> Either adding lazy on each service definition in yaml files or calling ->setLazy() on each is the same level of "static" logic here, isn't it? What's the difference?

There is no difference that's why calling `->setLazy()` is not feasible for me. If I have 100 service definitions, I'll have to call `->setLazy()` 100 times on all service definitions. To get rid of such "manual/static" interaction I wanted to parameterize the logic.

Symfony currently does a lot of magic so I believe, one way or another, using a boolean parameter to set `lazy` tag will be possible one day - just like we use parameters everywhere else in service definitions. Much appreciated with your input guys 👍

**Comment by jvasseur** [comment]
If you don't want to list all your services in your extension you could tag them all with a tag and used `findTaggedServiceIds` and loop on them to set the lazy attribute.

Maybe we should deprecate setting `lazy` to something other than a boolean in the loaders to give a meaningful error message when people try to use parameters here instead of silently casting is to `true`.

**Comment by BentCoder** [comment]
Tagging was a last resort for me but would there be a performace penalty for that FOR EVER REQUEST? Or for once to build the cache? I guess it would loop only once and keep all in cache then never loop again? Is this correct?

I agree with your silent casting comment.

**Comment by ogizanagi** [comment]
Actually it accepts strings too since https://github.com/symfony/symfony/pull/27697.
Note it'll be quite straightforward in core to make the loaders resolve the parameters. I'm just not convinced of the use-cases.
One can still provide a PR and gather more opinions.

**Comment by jvasseur** [comment]
@BentCoder the code of the `Extension` class is only executed on container rebuild so it will only have a performance penalty when building the cache.

**Comment by BentCoder** [comment]
@jvasseur I decided to go with looping tagged services to solve this issue. Thanks for enlighten me on cache thing.

**General comment:** Silently casting `lazy` parameter to `true` doesn't sit right with me. It just makes debugging very hard. I would rather see an exception thrown or some kind of error.
