### ISSUE TITLE
Assets from src are not installed correctly

### ISSUE THREAD

**Issue by james-fruhbauer** [symfony/symfony#29730]
**Symfony version(s) affected**: v4.2.1

**Description**  
Command php bin/console assets:install not installed resources from src/Resources. List of assets locations for command is in config/bundles.php, but main aplication is not here.

**How to reproduce**  
* composer create-project symfony/website-skeleton test
* Create resources in src/Resources
* php bin/console assets:install

**Comment by xabbuh** [comment]
This is expected. The application source code is not located in a bundle with the Symfony 4 directory layout. You simply place your application assets somewhere in the `public` directory. I am closing here as there is nothing to fix.
