### ISSUE TITLE
[4.2] [Routing] Matching trailing slashes is not possible anymore

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#29734]
**Symfony version(s) affected**: 4.2.2-dev

**Description**  
We have certain routes that have a suffix that is passed as-is to the controller. If the suffix is just a singe slash, that slash is not matched anymore.

Since we strip the slash anyway, this only broke our integration tests. However, such a change is a bit unexpected between minor versions.

**How to reproduce**  
```php
use Symfony\Component\Routing\Matcher\UrlMatcher;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

$routeCollection = new RouteCollection();
$routeCollection->add('test', new Route(
    '/some/route{pathSuffix}',
    ['pathSuffix' => ''],
    ['pathSuffix' => '(|/.*)']
));

$matcher = new UrlMatcher($routeCollection, new RequestContext());

dump($matcher->match('/some/route/'));
```

Output with Routing 4.2.1 and below:
```
array:2 [
  "pathSuffix" => "/"
  "_route" => "test"
]
```

Output with Routing 4.2.2-dev:
```
array:2 [
  "pathSuffix" => ""
  "_route" => "test"
]
```

**Comment by digilist** [comment]
I experienced the same bug, but with a simple trailing slash in a route's path. These routes do not work anymore:

```yaml
some_route:
    path: /foo/
    controller: FooController
```

The bug was introduced with 4.1.9, 4.1.8 works fine, so it's already present in 4.1

**Comment by stloyd** [comment]
In fact we occur this down below in version `3.8.19`.

We have two routes (really legacy project) that listen on routes with & without `/`, both are set on different controllers & different actions.

Before mentioned version it worked as expected, now it reaches kinda randomly only one of those actions, could be (or in fact is) related to trailing `/` redirect added in minor version `3.8.19`.

**Comment by digilist** [comment]
I think it might be related to #29441
