### ISSUE TITLE
[RFC] Change gender choice types to be more inclusive

### ISSUE THREAD

**Issue by Mx-Glitter** [symfony/symfony#29737]
I saw [here](https://github.com/search?p=2&q=org%3Asymfony+male&type=Code) that we use the example of gender for choice forms often. There are a lot of instances where we list 2 genders male and female as the only options, I was wondering if we should perhaps change it to be more inclusive (I myself being non-binary would like to be included for example). I'm aware it sounds nitpicking, but with the diversity initiative I figure I should ask.

I see 3 solutions, sorted from the my most prefered first:

- Not using gender as an example of choice form, because it is most of the times unnecessary for websites to ask such information, so we should not give it as an example as it promotes a bad habit.
- Using a list with "male", "female" and "non-binary", to include more people.
- Using a list with "male", "female" and "other", what is currently done in several places already in Symfony code and docs, I prefer the previous one not to be refered as other which is a bit demeaning.

**Comment by derrabus** [comment]
If we pick option 1, what would be a better default example? Colors maybe?

For instance https://github.com/symfony/form/blob/63fb6bcbb38676958731da428007671b24963cec/Forms.php#L29-L31

```
->add('color', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', array(
    'choices' => array('Red' => 'r', 'Blue' => 'b'),
))
```

**Comment by Mx-Glitter** [comment]
I'll have a go at it this week-end
