### ISSUE TITLE
Disable var-dumper search

### ISSUE THREAD

**Issue by rudiedirkx** [symfony/symfony#29748]
The `CTRL + F` capture in Var-dumper keeps tripping me up. I don't want to use this weird search feature. I know where I'm looking, so I'll use the browser search function. It's very very hard-coded however. It'd be nice to

- disable it completely, or
- disable the `CTRL+F` capture (so open search with a button or something)

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/issues/20873

> Generally as long as the data structures are not expanded they are not searchable via the browser search.

That's the main reason for this feature at least :) personally im  very used to it.

Perhaps we can do something like #29528 and allow to disable custom search with e.g. `debug.search_dump: false`.

**Comment by nicolas-grekas** [comment]
instead of binding CTRL+F, a small magnifying glass could open the search feature?
let's save us from yet another config option is possible, please.

**Comment by rudiedirkx** [comment]
I like the magnifying glass button (or any button). The everywhere search can be useful, but usually I click open a few sections and then browser search. The var-dumper search then messes up the expansions and focus and scroll location etc.

I'd still like to use `dump()` and `dd()`. I don't how how config would be injected.

Where are all these config options? I couldn't find any on https://symfony.com/doc/current/components/var_dumper.html

**Comment by ogizanagi** [comment]
I won't be in favor of removing the <kbd>CTRL</kbd> + <kbd>F</kbd> binding unless more people express themselves about this being annoying by default. This is the natural way to trigger such a feature and the binding is only listened when having focus on the `pre.sf-dump` element. 
To use native browser search feature, you simply have to click outside or press tab if you had focus.

A small magnifying glass might be fine but is one more absolutely positioned thingy we could save us IMHO. Though it would ease discoverability.

I agree as well about saving us from another config option for this.

**Comment by fabpot** [comment]
I think @ogizanagi is right. Let's close for now.
