### ISSUE TITLE
[FrameworkBundle] [Routing] Add options to debug:router command to filter by method, scheme or host

### ISSUE THREAD

**Issue by kevin-verschaeve** [symfony/symfony#29757]
**Description**  
I propose to add some options to the `bin/console debug:router` command to be able to filter by the method, the scheme and the host, allowed by a route.

**Example**  
- `bin/console debug:router --method=GET` to retrieve all routes that allows the GET method (also, possibly `--method=GET --method=POST` to retrieve GET and POST routes at once ?)
- `bin/console debug:router --scheme=http` (or maybe `--http-only` and `--https-only` ?)
- `bin/console debug:router --host="*.example.com"` : the `host` could accept a regex (`--match-host`  ?)

What do you think ?

**Comment by kevin-verschaeve** [comment]
Any thoughts on this ?

I can work on the PR if you think it would be useful (I've already started, but don't want to continue for nothing :) )

**Comment by inmarelibero** [comment]
my 2cents:
- `--method=GET` can be useful, for multiple values I personally prefer `--method=GET|POST`
- `--scheme=http` filter is not useful for me
- `--host="*.example.com"` filter is not useful for me

as a proposal, implement a filter on:
- regex for route name, eg. `--name=admin`, `--name="^\/admin"`, `--name="^homepage$"`
- regex for path, eg. `--path=admin`, `--path="^\/admin"`, `--path="^\/"`

**Comment by kevin-verschaeve** [comment]
PR closed, so I'm closing this issue also.

Thanks for  feedback and reactions
