### ISSUE TITLE
Detection if Windows or UNIX

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/symfony#29756]
**Description**  
Symfony currently uses:

`if ('\\' !== DIRECTORY_SEPARATOR) { // PHP does not run in Windows }`

in many places. This could be changed to something like:

`if (OperatingSystem::WINDOWS !== $os->getType()) { // PHP does not run in Windows }`

Is it worth my time to try to build something small like https://packagist.org/packages/operating-system/operating-system into Symfony? But since this simple thing was not done yet I suppose there is a good reason for it?

My pros:
- Better readability
- One single place to change the detection (very unlikely that this will be needed)

My cons:
- Performance loss
- More complexity

**Example**  
see "Description"

**Comment by ro0NL** [comment]
> But since this simple thing was not done yet I suppose there is a good reason for it?

> One single place to change the detection (very unlikely that this will be needed)

given the unlikeliness of changes, i think that's the reason :) This way we dont need to require extra packages for a simple `'\\' !== DIRECTORY_SEPARATOR`, which is what your code still does IIUC.

There are other duplicated one-liners in SF as well; getenv()+globals, detecting color support

so it'll lead to a `symfony/common` package or so, which is rejected before.

**Comment by nicolas-grekas** [comment]
Adding a dependency is not a minor decision, see eg https://en.wikipedia.org/wiki/Package_principles or https://dunglas.fr/2018/11/about-the-dependencies-of-symfony/
In the particular case, your suggestion would a compile-time resolved conditions by runtime ones.
That's two string reasons not to do it.
Thanks for proposing!
