### ISSUE TITLE
Remove stopwatch from test environment

### ISSUE THREAD

**Issue by gmponos** [symfony/symfony#29768]
**Description**  
I have noticed some performance improvement when I run my tests without the stopwatch component.

I was wondering if the services could not be injected when the `env` is set on test.

I tried removing the `test` from the bundles file but if I do that this throws exception.

**Comment by xabbuh** [comment]
There are probably more performance impacting differences. IMO you should be able to change that by booting the kernel with the debug flag disabled. This flag is what drives the `kernel.debug` parameter which most part of the ecosystem rely on when deciding whether or not to enable debugging tools.
