### ISSUE TITLE
[Validator] Domain validation

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#29774]
**Description**  
There is already a URL constraint for validation.

What about adding a domain constraint using https://dunglas.fr/2014/11/php-7-introducing-a-domain-name-validator-and-making-the-url-validator-stricter/ ?

I can submit a PR if it's likely to be accepted

**Comment by xabbuh** [comment]
Thank you for proposing. I am closing here nonetheless as this duplicated #10088. Thank you for understanding.
