### ISSUE TITLE
Cannot execute phpunit after installing Symfony 4.3-dev

### ISSUE THREAD

**Issue by jlslew** [symfony/symfony#29771]
**Symfony version(s) affected**: 4.3-dev

**Description**  
> #!/usr/bin/env php
> PHPUnit 6.5.13 by Sebastian Bergmann and contributors.
> 
> Undefined index: APP_ENV

**How to reproduce**  
- `composer create-project symfony/website-skeleton test -s dev`
- `php bin/phpunit`

**Comment by ro0NL** [comment]
i failed to reproduce it

<details>
  <summary>Output</summary>

```
$ php bin/phpunit
#!/usr/bin/env php
Installing phpunit/phpunit (6.5.13)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.13): Downloading (100%)
Created project in phpunit-6.5
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
    1/28:       https://codeload.github.com/sebastianbergmann/php-file-iterator/legacy.zip/730b01bc3e867237eaac355e06a36b85dd93a8b4
    2/28:       https://codeload.github.com/sebastianbergmann/php-text-template/legacy.zip/31f8b717e51d9a2afca6c9f046f5d69fc27c8686
    3/28:       https://codeload.github.com/sebastianbergmann/code-unit-reverse-lookup/legacy.zip/4419fcdb5eabb9caa61a27c7a1db532a6b55dd18
    4/28:       https://codeload.github.com/sebastianbergmann/version/legacy.zip/99732be0ddb3361e16ad77b68ba41efc8e979019
    5/28:       https://codeload.github.com/sebastianbergmann/environment/legacy.zip/cd0871b3975fb7fc44d11314fd1ee20925fce4f5
    6/28:       https://codeload.github.com/webmozart/assert/legacy.zip/83e253c8e0be5b0257b881e1827274667c5c17a9
    7/28:       https://codeload.github.com/symfony/polyfill-ctype/legacy.zip/e3d826245268269cd66f8326bd8bc066687b4a19
    8/28:       https://codeload.github.com/phpDocumentor/ReflectionCommon/legacy.zip/21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6
    9/28:       https://codeload.github.com/sebastianbergmann/php-token-stream/legacy.zip/791198a2c6254db10131eecfe8c06670700904db
    10/28:      https://codeload.github.com/theseer/tokenizer/legacy.zip/cb2f008f3f05af2893a87208fe6a6c4985483f8b
    11/28:      https://codeload.github.com/phpDocumentor/ReflectionDocBlock/legacy.zip/94fd0001232e47129dd3504189fa1c7225010d08
    12/28:      https://codeload.github.com/sebastianbergmann/exporter/legacy.zip/234199f4528de6d12aaa58b612e98f7d36adb937
    13/28:      https://codeload.github.com/phpDocumentor/TypeResolver/legacy.zip/9c977708995954784726e25d0cd1dddf4e65b0f7
    14/28:      https://codeload.github.com/doctrine/instantiator/legacy.zip/8e884e78f9f0eb1329e445619e04456e64d8051d
    15/28:      https://codeload.github.com/phpspec/prophecy/legacy.zip/4ba436b55987b4bf311cb7c6ba82aa528aac0a06
    16/28:      https://codeload.github.com/sebastianbergmann/comparator/legacy.zip/34369daee48eafb2651bea869b4b15d75ccc35f9
    17/28:      https://codeload.github.com/phar-io/manifest/legacy.zip/2df402786ab5368a0169091f61a7c1e0eb6852d0
    18/28:      https://codeload.github.com/sebastianbergmann/diff/legacy.zip/347c1d8b49c5c3ee30c7040ea6fc446790e6bddd
    19/28:      https://codeload.github.com/sebastianbergmann/resource-operations/legacy.zip/ce990bb21759f94aeafd30209e8cfcdfa8bc3f52
    20/28:      https://codeload.github.com/phar-io/version/legacy.zip/a70c0ced4be299a63d32fa96d9281d03e94041df
    21/28:      https://codeload.github.com/myclabs/DeepCopy/legacy.zip/3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e
    22/28:      https://codeload.github.com/sebastianbergmann/object-enumerator/legacy.zip/7cfd9e65d11ffb5af41198476395774d4c8a84c5
    23/28:      https://codeload.github.com/sebastianbergmann/phpunit-mock-objects/legacy.zip/cd1cf05c553ecfec36b170070573e540b67d3f1f
    24/28:      https://codeload.github.com/sebastianbergmann/object-reflector/legacy.zip/773f97c67f28de00d397be301821b06708fca0be
    25/28:      https://codeload.github.com/sebastianbergmann/recursion-context/legacy.zip/5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8
    26/28:      https://codeload.github.com/sebastianbergmann/global-state/legacy.zip/e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4
    27/28:      https://codeload.github.com/sebastianbergmann/php-timer/legacy.zip/3dcf38ca72b158baf0bc245e9184d3fdffa9c46f
    28/28:      https://codeload.github.com/sebastianbergmann/php-code-coverage/legacy.zip/c89677919c5dd6d3b3852f230a663118762218ac
    Finished: success: 28, skipped: 0, failure: 0, total: 28
Package operations: 29 installs, 0 updates, 0 removals
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing symfony/phpunit-bridge (dev-master): Symlinking from /app/vendor/symfony/phpunit-bridge
Writing lock file
Generating optimized autoload files
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.



Time: 19.59 seconds, Memory: 4.00MB

No tests executed!
```
</details>

**Comment by ro0NL** [comment]
ouch. Confirmed after all :)

if `APP_ENV` does not exists as a real variable it crashes with undefined index yes.

**Comment by jlslew** [comment]
Here is my output.
<details>
<summary>Output</summary>
<pre>
$ composer create-project symfony/website-skeleton test -s dev
Installing symfony/website-skeleton (dev-master 718c695081a6dfdccfef81c321c070343adc06e8)
  - Installing symfony/website-skeleton (dev-master 718c695): Cloning 718c695081 from cache
Created project in test
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 98 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.3.0): Downloading (100%)         
  - Installing symfony/flex (dev-master 48438c2): Downloading (100%)         

Prefetching 96 packages 🎶 💨
  - Downloading (100%)
  - Installing symfony/routing (dev-master a4f986f): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/yaml (dev-master 6e8c0d1): Loading from cache
  - Installing psr/link (dev-master 131b5c3): Loading from cache
  - Installing fig/link-util (dev-master 1a07821): Loading from cache
  - Installing symfony/web-link (dev-master 81ad875): Loading from cache
  - Installing symfony/contracts (dev-master 1aa7ab2): Loading from cache
  - Installing symfony/translation (dev-master 547a484): Loading from cache
  - Installing doctrine/lexer (dev-master 4ab6ea7): Loading from cache
  - Installing doctrine/annotations (1.7.x-dev 232c5da): Loading from cache
  - Installing doctrine/reflection (dev-master 4a97a22): Loading from cache
  - Installing doctrine/event-manager (dev-master dbdc567): Loading from cache
  - Installing doctrine/collections (dev-master 73b0d9a): Loading from cache
  - Installing doctrine/cache (dev-master bdf3e32): Loading from cache
  - Installing doctrine/persistence (1.1.x-dev 559d323): Loading from cache
  - Installing doctrine/inflector (1.3.x-dev 45d9b13): Loading from cache
  - Installing doctrine/common (dev-master af54fea): Loading from cache
  - Installing symfony/validator (dev-master c4f7218): Loading from cache
  - Installing twig/twig (2.x-dev 139c752): Loading from cache
  - Installing symfony/twig-bridge (dev-master 55d96f1): Loading from cache
  - Installing symfony/http-foundation (dev-master 961b3fe): Loading from cache
  - Installing symfony/event-dispatcher (dev-master 249a31f): Loading from cache
  - Installing psr/log (dev-master c4421fc): Loading from cache
  - Installing symfony/debug (dev-master c0ed02a): Loading from cache
  - Installing symfony/http-kernel (dev-master 4a152a6): Loading from cache
  - Installing symfony/filesystem (dev-master b12244c): Loading from cache
  - Installing symfony/config (dev-master 67bf83b): Loading from cache
  - Installing symfony/inflector (dev-master bb7dc45): Loading from cache
  - Installing symfony/security-core (dev-master debbe94): Loading from cache
  - Installing symfony/property-access (dev-master 6fbea3d): Loading from cache
  - Installing symfony/twig-bundle (dev-master eb4c6fd): Loading from cache
  - Installing psr/container (dev-master 014d250): Loading from cache
  - Installing symfony/dependency-injection (dev-master e1c5d25): Loading from cache
  - Installing egulias/email-validator (2.1.7): Loading from cache
  - Installing swiftmailer/swiftmailer (dev-master e8c3ed7): Loading from cache
  - Installing symfony/swiftmailer-bundle (dev-master 3fc0cd7): Loading from cache
  - Installing symfony/serializer (dev-master 95e9c26): Loading from cache
  - Installing symfony/property-info (dev-master 0ca60c5): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing symfony/var-exporter (dev-master 346a6e1): Loading from cache
  - Installing psr/simple-cache (dev-master 408d5ea): Loading from cache
  - Installing psr/cache (dev-master 78c5a01): Loading from cache
  - Installing symfony/cache (dev-master c6d868e): Loading from cache
  - Installing symfony/serializer-pack (dev-master c5f18ba): Loading from cache
  - Installing symfony/security-http (dev-master 35f3ea2): Loading from cache
  - Installing symfony/security-guard (dev-master 841c28c): Loading from cache
  - Installing symfony/security-csrf (dev-master bd0e864): Loading from cache
  - Installing symfony/security-bundle (dev-master 6c0c716): Loading from cache
  - Installing symfony/process (dev-master 21eb923): Loading from cache
  - Installing symfony/finder (dev-master 462d940): Loading from cache
  - Installing symfony/framework-bundle (dev-master e6f9f58): Loading from cache
  - Installing zendframework/zend-code (dev-develop 8003f74): Loading from cache
  - Installing ocramius/proxy-manager (2.2.x-dev 14b137b): Loading from cache
  - Installing symfony/console (dev-master 471125d): Loading from cache
  - Installing doctrine/dbal (dev-master f28f3a8): Loading from cache
  - Installing symfony/stopwatch (dev-master 950e4c7): Loading from cache
  - Installing doctrine/migrations (1.8.x-dev 5476b88): Loading from cache
  - Installing symfony/doctrine-bridge (dev-master a711587): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (dev-master ea55012): Loading from cache
  - Installing jdorn/sql-formatter (dev-master 7ef9b85): Loading from cache
  - Installing doctrine/doctrine-bundle (dev-master ad278ef): Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (1.3.x-dev 49fa399): Loading from cache
  - Installing doctrine/instantiator (dev-master 8c8c1af): Loading from cache
  - Installing doctrine/orm (2.7.x-dev 266f0d7): Loading from cache
  - Installing symfony/orm-pack (dev-master 1b58f75): Loading from cache
  - Installing monolog/monolog (1.x-dev 4d5b7e6): Loading from cache
  - Installing symfony/monolog-bridge (dev-master d9911f6): Loading from cache
  - Installing symfony/monolog-bundle (dev-master 0ce1fb7): Loading from cache
  - Installing symfony/options-resolver (dev-master 3bc5c9e): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.10.0): Loading from cache
  - Installing symfony/intl (dev-master bc81d05): Loading from cache
  - Installing symfony/form (dev-master b841ea8): Loading from cache
  - Installing symfony/expression-language (dev-master 9883ec6): Loading from cache
  - Installing symfony/dotenv (dev-master 4b2d274): Loading from cache
  - Installing symfony/asset (dev-master abef76f): Loading from cache
  - Installing sensio/framework-extra-bundle (dev-master 1fdf591): Loading from cache
  - Installing symfony/polyfill-php72 (v1.10.0): Loading from cache
  - Installing symfony/var-dumper (dev-master c2748a6): Loading from cache
  - Installing symfony/web-profiler-bundle (dev-master 5cadf5f): Loading from cache
  - Installing symfony/profiler-pack (dev-master 99c4370): Loading from cache
  - Installing symfony/debug-bundle (dev-master 8644565): Loading from cache
  - Installing easycorp/easy-log-handler (v1.0.7): Loading from cache
  - Installing symfony/debug-pack (dev-master 09a4a1e): Loading from cache
  - Installing nikic/php-parser (dev-master 90ee36a): Loading from cache
  - Installing symfony/maker-bundle (v1.11.1): Loading from cache
  - Installing symfony/css-selector (dev-master cf1c211): Loading from cache
  - Installing symfony/dom-crawler (dev-master de43e70): Loading from cache
  - Installing symfony/browser-kit (dev-master b3f9934): Loading from cache
  - Installing facebook/webdriver (1.6.0): Loading from cache
  - Installing symfony/panther (dev-master 6a135dd): Loading from cache
  - Installing symfony/phpunit-bridge (dev-master 108a7ec): Loading from cache
  - Installing symfony/test-pack (dev-master 1792b80): Loading from cache
  - Installing symfony/web-server-bundle (dev-master 0224e6d): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 21 recipes (07e23cb979618ebe1177d1bcd1e85c11)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (>=4.2): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.2): From github.com/symfony/recipes:master
  - Configuring symfony/translation (>=3.3): From github.com/symfony/recipes:master
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/validator (>=4.1): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/swiftmailer-bundle (>=2.5): From github.com/symfony/recipes:master
  - Configuring symfony/security-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=3.3): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-cache-bundle (>=dev-master): From auto-generated recipe
  - Configuring doctrine/doctrine-bundle (>=1.6): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-migrations-bundle (>=1.2): From github.com/symfony/recipes:master
  - Configuring symfony/monolog-bundle (>=3.1): From github.com/symfony/recipes:master
  - Configuring sensio/framework-extra-bundle (>=5.2): From github.com/symfony/recipes:master
  - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/debug-bundle (>=4.1): From github.com/symfony/recipes:master
  - Configuring easycorp/easy-log-handler (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/maker-bundle (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/phpunit-bridge (>=4.1): From github.com/symfony/recipes:master
  - Configuring symfony/web-server-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

$ php bin/phpunit
#!/usr/bin/env php
Installing phpunit/phpunit (6.5.13)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.13): Downloading (100%)
Created project in phpunit-6.5
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 29 installs, 0 updates, 0 removals
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.1.3): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.10.0): Downloading (100%)
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Downloading (100%)
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (2.0.2): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.3.2): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (5.0.10): Downloading (100%)
  - Installing symfony/phpunit-bridge (dev-master): Symlinking from vendor/symfony/phpunit-bridge
Writing lock file
Generating optimized autoload files
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

Undefined index: APP_ENV 
</pre>
</details>
<details>
<summary>composer show symfony/*</summary>
<pre>
symfony/asset                dev-master abef76f Symfony Asset Component
symfony/browser-kit          dev-master b3f9934 Symfony BrowserKit Component
symfony/cache                dev-master c6d868e Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               dev-master 67bf83b Symfony Config Component
symfony/console              dev-master 471125d Symfony Console Component
symfony/contracts            dev-master 1aa7ab2 A set of abstractions extracted out of the Symfony components
symfony/css-selector         dev-master cf1c211 Symfony CssSelector Component
symfony/debug                dev-master c0ed02a Symfony Debug Component
symfony/debug-bundle         dev-master 8644565 Symfony DebugBundle
symfony/debug-pack           dev-master 09a4a1e A debug pack for Symfony projects
symfony/dependency-injection dev-master e1c5d25 Symfony DependencyInjection Component
symfony/doctrine-bridge      dev-master a711587 Symfony Doctrine Bridge
symfony/dom-crawler          dev-master de43e70 Symfony DomCrawler Component
symfony/dotenv               dev-master 4b2d274 Registers environment variables from a .env file
symfony/event-dispatcher     dev-master 249a31f Symfony EventDispatcher Component
symfony/expression-language  dev-master 9883ec6 Symfony ExpressionLanguage Component
symfony/filesystem           dev-master b12244c Symfony Filesystem Component
symfony/finder               dev-master 462d940 Symfony Finder Component
symfony/flex                 dev-master 48438c2 Composer plugin for Symfony
symfony/form                 dev-master b841ea8 Symfony Form Component
symfony/framework-bundle     dev-master e6f9f58 Symfony FrameworkBundle
symfony/http-foundation      dev-master 961b3fe Symfony HttpFoundation Component
symfony/http-kernel          dev-master 4a152a6 Symfony HttpKernel Component
symfony/inflector            dev-master bb7dc45 Symfony Inflector Component
symfony/intl                 dev-master bc81d05 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle         v1.11.1            Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge       dev-master d9911f6 Symfony Monolog Bridge
symfony/monolog-bundle       dev-master 0ce1fb7 Symfony MonologBundle
symfony/options-resolver     dev-master 3bc5c9e Symfony OptionsResolver Component
symfony/orm-pack             dev-master 1b58f75 A pack for the Doctrine ORM
symfony/panther              dev-master 6a135dd A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge       dev-master 108a7ec Symfony PHPUnit Bridge
symfony/polyfill-intl-icu    v1.10.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              dev-master 21eb923 Symfony Process Component
symfony/profiler-pack        dev-master 99c4370 A pack for the Symfony web profiler
symfony/property-access      dev-master 6fbea3d Symfony PropertyAccess Component
symfony/property-info        dev-master 0ca60c5 Symfony Property Info Component
symfony/routing              dev-master a4f986f Symfony Routing Component
symfony/security-bundle      dev-master 6c0c716 Symfony SecurityBundle
symfony/security-core        dev-master debbe94 Symfony Security Component - Core Library
symfony/security-csrf        dev-master bd0e864 Symfony Security Component - CSRF Library
symfony/security-guard       dev-master 841c28c Symfony Security Component - Guard
symfony/security-http        dev-master 35f3ea2 Symfony Security Component - HTTP Integration
symfony/serializer           dev-master 95e9c26 Symfony Serializer Component
symfony/serializer-pack      dev-master c5f18ba A pack for the Symfony serializer
symfony/stopwatch            dev-master 950e4c7 Symfony Stopwatch Component
symfony/swiftmailer-bundle   dev-master 3fc0cd7 Symfony SwiftmailerBundle
symfony/test-pack            dev-master 1792b80 A pack for functional and end-to-end testing within a Symfony app
symfony/translation          dev-master 547a484 Symfony Translation Component
symfony/twig-bridge          dev-master 55d96f1 Symfony Twig Bridge
symfony/twig-bundle          dev-master eb4c6fd Symfony TwigBundle
symfony/validator            dev-master c4f7218 Symfony Validator Component
symfony/var-dumper           dev-master c2748a6 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         dev-master 346a6e1 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link             dev-master 81ad875 Symfony WebLink Component
symfony/web-profiler-bundle  dev-master 5cadf5f Symfony WebProfilerBundle
symfony/web-server-bundle    dev-master 0224e6d Symfony WebServerBundle
symfony/yaml                 dev-master 6e8c0d1 Symfony Yaml Component
</pre>
</details>

**Comment by xabbuh** [comment]
This needs to be fixed in the recipe. Closing here in favour of symfony/recipes#512.
