### ISSUE TITLE
Controller requires that you provide a value for the \"$id\" argument

### ISSUE THREAD

**Issue by anboo** [symfony/symfony#29790]
**Symfony version(s) affected**: x.y.z
4.0.14

**Description**  
After update symfony/routing from v4.1.8 to v4.1.9 I have error:
`Controller \"App\\Controller\\ClientGroupController::getItemAction()\" requires that you provide a value for the \"$id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.`

**How to reproduce**  
```php
trait GetItemTrait 
{
    public function getItemAction(string $id): Response
    {}
}
```
Controller:
```php
class CustomController extends Controller
{
    use GetItemTrait;
}
```

**Possible Solution**  
Use fixed version symfony/routing v4.1.8

**Additional context**  
`
RuntimeException: Controller "App\Controller\ClientGroupController::getItemAction()" requires that you provide a value for the "$id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. in /var/www/leroy/lm-security/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:78 Stack trace: #0 /var/www/leroy/lm-security/vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php(38): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/leroy/lm-security/vendor/symfony/http-kernel/HttpKernel.php(141): Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #2 /var/www/leroy/lm-security/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /var/www/leroy/lm-security/vendor/symfony/http-kernel/Kernel.php(188): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/leroy/lm-security/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 {main}
`

**Comment by xabbuh** [comment]
How does your request look like? What is the configuration of your route?

**Comment by anboo** [comment]
*Trait*
```php
trait GetItemTrait
{
    /**
     * @Route("/{id}/", requirements={"id": "[a-z0-9\-\w+]{1,}"}, methods={"GET"})
     */
    public function getItemAction(string $id, Request $request, GetItemService $service, SerializationContextFetcher $serializationContextFetcher): Response
    {
    }
}
```

*Controller*
```php
/**
 * @Route("/api/client")
 */
class ClientController extends ApiController
{
    use GetItemTrait;
}
```

*config/routes/annotations.yaml*
```yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
```

Request with URL `/api/client/1/`

**Comment by anboo** [comment]
| name                         | version    | description                                                                                                                                |
|------------------------------|------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| symfony/asset                | v4.2.1     | Symfony Asset Component                                                                                                                    |
| symfony/browser-kit          | v4.2.1     | Symfony BrowserKit Component                                                                                                               |
| symfony/cache                | v4.2.1     | Symfony Cache component with PSR-6, PSR-16, and tags                                                                                       |
| symfony/config               | v3.4.20    | Symfony Config Component                                                                                                                   |
| symfony/console              | v4.2.1     | Symfony Console Component                                                                                                                  |
| symfony/contracts            | v1.0.2     | A set of abstractions extracted out of the Symfony components                                                                              |
| symfony/css-selector         | v4.2.1     | Symfony CssSelector Component                                                                                                              |
| symfony/debug                | v4.2.1     | Symfony Debug Component                                                                                                                    |
| symfony/dependency-injection | v4.0.15    | Symfony DependencyInjection Component                                                                                                      |
| symfony/doctrine-bridge      | v4.2.1     | Symfony Doctrine Bridge                                                                                                                    |
| symfony/dom-crawler          | v4.2.1     | Symfony DomCrawler Component                                                                                                               |
| symfony/dotenv               | v4.2.1     | Registers environment variables from a .env file                                                                                           |
| symfony/event-dispatcher     | v4.2.1     | Symfony EventDispatcher Component                                                                                                          |
| symfony/expression-language  | v4.2.1     | Symfony ExpressionLanguage Component                                                                                                       |
| symfony/filesystem           | v4.2.1     | Symfony Filesystem Component                                                                                                               |
| symfony/finder               | v4.2.1     | Symfony Finder Component                                                                                                                   |
| symfony/flex                 | v1.1.8     | Composer plugin for Symfony                                                                                                                |
| symfony/form                 | v4.2.1     | Symfony Form Component                                                                                                                     |
| symfony/framework-bundle     | v4.0.15    | Symfony FrameworkBundle                                                                                                                    |
| symfony/http-foundation      | v4.2.0     | Symfony HttpFoundation Component                                                                                                           |
| symfony/http-kernel          | v4.0.14    | Symfony HttpKernel Component                                                                                                               |
| symfony/inflector            | v4.2.1     | Symfony Inflector Component                                                                                                                |
| symfony/intl                 | v4.2.1     | A PHP replacement layer for the C intl extension that includes additional data from the ICU library.                                       |
| symfony/lts                  | dev-master | Enforces Long Term Supported versions of Symfony components                                                                                |
| symfony/maker-bundle         | v1.11.2    | Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code. |
| symfony/monolog-bridge       | v4.2.1     | Symfony Monolog Bridge                                                                                                                     |
| symfony/monolog-bundle       | v3.3.1     | Symfony MonologBundle                                                                                                                      |
| symfony/options-resolver     | v4.2.1     | Symfony OptionsResolver Component                                                                                                          |
| symfony/orm-pack             | v1.0.5     | A pack for the Doctrine ORM                                                                                                                |
| symfony/panther              | v0.2.0     | A browser testing and web scraping library for PHP and Symfony.                                                                            |
| symfony/phpunit-bridge       | v4.2.1     | Symfony PHPUnit Bridge                                                                                                                     |
| symfony/polyfill-ctype       | v1.10.0    | Symfony polyfill for ctype functions                                                                                                       |
| symfony/polyfill-intl-icu    | v1.10.0    | Symfony polyfill for intl's ICU-related data and classes                                                                                   |
| symfony/polyfill-mbstring    | v1.10.0    | Symfony polyfill for the Mbstring extension                                                                                                |
| symfony/polyfill-php72       | v1.10.0    | Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions                                                                  |
| symfony/process              | v4.2.1     | Symfony Process Component                                                                                                                  |
| symfony/profiler-pack        | v1.0.4     | A pack for the Symfony web profiler                                                                                                        |
| symfony/property-access      | v4.2.1     | Symfony PropertyAccess Component                                                                                                           |
| symfony/property-info        | v4.2.1     | Symfony Property Info Component                                                                                                            |
| symfony/routing              | v4.1.9     | Symfony Routing Component                                                                                                                  |
| symfony/security             | v4.2.1     | Symfony Security Component                                                                                                                 |
| symfony/security-bundle      | v4.0.15    | Symfony SecurityBundle                                                                                                                     |
| symfony/serializer           | v4.2.1     | Symfony Serializer Component                                                                                                               |
| symfony/stopwatch            | v4.2.1     | Symfony Stopwatch Component                                                                                                                |
| symfony/templating           | v4.2.1     | Symfony Templating Component                                                                                                               |
| symfony/test-pack            | v1.0.5     | A pack for functional and end-to-end testing within a Symfony app                                                                          |
| symfony/translation          | v4.2.1     | Symfony Translation Component                                                                                                              |
| symfony/twig-bridge          | v4.2.1     | Symfony Twig Bridge                                                                                                                        |
| symfony/twig-bundle          | v4.1.0     | Symfony TwigBundle                                                                                                                         |
| symfony/validator            | v4.2.1     | Symfony Validator Component                                                                                                                |
| symfony/var-dumper           | v4.2.1     | Symfony mechanism for exploring and dumping PHP variables                                                                                  |
| symfony/var-exporter         | v4.2.1     | A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code                                            |
| symfony/web-profiler-bundle  | v4.0.15    | Symfony WebProfilerBundle                                                                                                                  |
| symfony/web-server-bundle    | v4.2.1     | Symfony WebServerBundle                                                                                                                    |
| symfony/yaml                 | v4.2.1     | Symfony Yaml Component                                                                                                                     |

**Comment by iltar** [comment]
You have a lot of different symfony versions, I see at least 6 different symfony components with different versions, ranging from 3.4 to 4.0, 4.1 and 4.2. Have you tried updating all of them to the latest to see if that fixes the issue>

**Comment by anboo** [comment]
Nope.
Right now I need do `composer require "symfony/routing:!=4.1.9 !=4.1.10"` for fix this problem.
(4.1.10 release broken too). I use v4.2.2 and v4.1.8 for my projects with different symfony version.

**Comment by nicolas-grekas** [comment]
Maybe that's beacuse I tried with 4.2.5, but following the instructions posted above, I don't reproduce the issue. Please provide a full reproducer we could clone to see the problem and start working on it.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
