### ISSUE TITLE
Bootstrap - Radio style button toggling

### ISSUE THREAD

**Issue by guice12** [symfony/symfony#29795]
Hi,
With Form class and Bootstrap 4 Form theme, how render radio style button toggling ?

```html
<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Active
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option2" autocomplete="off"> Radio
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Radio
  </label>
</div>
```

Link : https://getbootstrap.com/docs/4.2/components/buttons/#checkbox-and-radio-buttons

Thanks :)

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
