### ISSUE TITLE
[Twig] Accept an array of template in the render method

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#29808]
**Description**  
Twig is able to select a template from an array of templates
(see https://github.com/twigphp/Twig/blob/735f266d72f253d59269f4cab38094070f3db22f/lib/Twig/Environment.php#L466 or  https://twig.symfony.com/doc/2.x/functions/include.html )

I could be nice to expose this feature in the abstract controller. What do you think ?

**Example**  

```php
$this->render(['cms/layout/$layout.html.twig', 'cms/layout/default.html.twig'])
```

**Comment by mickaelandrieu** [comment]
Hi,

it depends if you (ie the Symfony team) want to promote this practice or not... regarding what we do in the Grid component of PrestaShop (that initially relies on this nice feature), the impact on performances can be really big, so we manage to provide this a different way => https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Twig/Extension/GridExtension.php#L200

Also, outside of this scope, I've never met a use case for that when we already have so many ways to make templates dynamic, so I'm interested in your owns.

Mickaël

**Comment by lyrixx** [comment]
Actually, The response should be different according to the value of `$layout` (CSP-Headers).
So I finally added a real `if ($template)` in my controller. 
I don't need this feature anymore.
I'm closing this issue as I think this is not a really common need
