### ISSUE TITLE
Slack’s Web link no longer available

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/symfony#29806]
Hi all,

Following the link from this repo, I browsed Symfony’s website, that was including a link to [this Slack’s shared invite](https://symfony-devs.slack.com/join/shared_invite/enQtNDk1OTU2Mjc3NzkyLTg4OTFiMjE3OTA0NWU3ZDI2ODg1ZGJlNjExMDhiZjQ1OTZkMDBlYTY1ZjUyN2RkOGQ4YjJkZGJlYjcxZjIyYTA). However, it looks like the link is no longer working.

I would suggest removing that reference if is no longer available, or update the link using a new one.

Cheers,

**Comment by javiereguiluz** [comment]
Sorry for that! The new link will be deployed soon on symfony.com. Meanwhile, this will be the new link in case you want to share it now with some colleague: https://join.slack.com/t/symfony-devs/shared_invite/enQtNTE3MjM3Nzc5OTY5LWFmZDE4NTEzMjIxYTMwNTZiODkwNDVhY2I5YjM3YzY2OWNhNzYzN2I3Y2ZkZmRkZTE2ZDgzNzY3YzlhMmVlNWI
