### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.     3x in MyControllerTest::setUp from Tests\App\Controller

### ISSUE THREAD

**Issue by engharb** [symfony/symfony#29825]
Hello,
Currently I upgraded from Symfony 4.1 to Symfony 4.2.2. And by running phpunit test I used to get
```
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
    3x in MyControllerTest::setUp from Tests\App\Controller
```

Also
```
Templates directory "/home/vagrant/MyProject/src/Resources/views" is deprecated since Symfony 4.2, use "/home/vagrant/MyProject/templates" instead.
```

Where I'm using php template instead of twig. Do you have any suggestion?

**Comment by stof** [comment]
Well, for `A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`, you should identify which bundle is triggering that.

**Comment by xabbuh** [comment]
I am closing here as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
