### ISSUE TITLE
Argon2i encoder can validate BCrypt encoded passwords and vice versa

### ISSUE THREAD

**Issue by julienfalque** [symfony/symfony#29827]
`Argon2iPasswordEncoder` and `BCryptPasswordEncoder` both validate passwords using the `password_verify()` function without checking the hash type first. As the function can infer the type from the given hash, this means both encoders are able to validate any hash whose type can be infered.

In other words, `Argon2iPasswordEncoder` can validate BCrypt encoded passwords and `BCryptPasswordEncoder` can validate Argon2i encoded passwords. IMO this is not a bug but it's not really expected either. WDYT?

**Comment by stof** [comment]
I would say that we don't really care about that implementation detail.

**Comment by chalasr** [comment]
I agree with @stof.

**Comment by xabbuh** [comment]
I agree as well. Though one should not rely on it to always work in the future.

**Comment by PhilETaylor** [comment]
https://github.com/symfony/symfony/pull/29863#issuecomment-471973410
