### ISSUE TITLE
Dialog/Question helper stty settings broken after unexpected exit for console applciation

### ISSUE THREAD

**Issue by chrisRidgers** [symfony/symfony#29826]
**Symfony version(s) affected**: symfony-console 2.8.32

**Description**  
Killing an interactive terminal results in a broken stty configuration, prompts can no longer be completed due to nothing happening when you press the enter key.

**How to reproduce**  

Have these stty settings:

    speed 38400 baud; 25 rows; 150 columns;
    lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	    -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	    -extproc
    iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	    -ignbrk brkint -inpck -ignpar -parmrk 
    oflags: opost onlcr -oxtabs -onocr -onlret
    cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	    -dtrflow -mdmbuf
    cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	    eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	    min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	    stop = ^S; susp = ^Z; time = 0; werase = ^W;

Run a CLI application that utilises Symfony\Component\Console\Helper\DialogHelper to ask a question.  Before answering the question, kill the application using ^C.

Interactive prompts no longer work in other applications: possibly because my stty settings have been changed to `-iecho -icanon`.

**Possible Solution**  

The issue was caused by the code changing stty settings in the ask function of the DialogHelper.  Once my settings had been changed, I killed the application and it left my terminal broken.  I was able to fix this locally by storing my original stty settings the DialogHelper and restoring them as part of the classes destruct call.

    class DialogHelper extends InputAwareHelper
    {
        ...
        private $sttyMode;

        public function __destruct()
        {
            if(!$this->hasSttyAvailable()) {
                return;
            }

            //Restores default stty settings in clean/ unclean shutdown
            shell_exec(sprintf('stty %s', $this->sttyMode));
        }

        public function ask(OutputInterface $output, $question, $default = null, array $autocomplete = null)
        {
         ...
         $this->sttyMode = shell_exec('stty -g');
         ...
        }
    }

**Additional context**  

I'm aware the DialogHelper is deprecated, but I suspect the new QuestionHelper MAY be susceptible to the same behaviour.

The reason I noticed this in the first place is because our applications input was checking for Carriage Returns, while my stty settings were converting them to new line characters.  This meant I couldn't select any of the question answers.  So i killed the application resulting in my broken terminal, which would still have been sending new lines.  Perhaps that's part of why my input remained broken after the application had been killed.

**Comment by chrisRidgers** [comment]
Relates to #27786

**Comment by chalasr** [comment]
DialogHelper has been removed in 3.0 in favor of QuestionHelper, where the issue might be fixed. Closing here.
