### ISSUE TITLE
Kill running command?

### ISSUE THREAD

**Issue by BonBonSlick** [symfony/symfony#29823]
I have run generating fake data in cron command in vagrant box for 100 000 000 records :3 
After box and computer reload command still locked. 
Cleared cache, removed cache folder, tried to call 
`         $this->lock->release();
`
Which says
`[2019-01-08 21:18:38][18 MB][ERROR] Command `cron:test` is locked
`

Restarting php does not helped
```
vagrant@test:/srv/test$ sudo systemctl restart php7.2-fpm
vagrant@test:/srv/test$ sudo systemctl restart php7.2-fpm.service
vagrant@test:/srv/test$ php -v
PHP 7.2.....2018, by Zend Technologies

```

How to unlock it without recreating vagrant box? :)

**Comment by chalasr** [comment]
This is probably not a Symfony bug. 
The console `LockableTrait` uses `FlockStore` unless semaphore is installed (sysvsem PHP ext), and IIRC `flock` does not play well with NFS. So if you vagrant box use NFS for file sync, you may need to add semaphore to your VM provisioning.
Please continue on [our support platforms](https://symfony.com/support) if needed.

**Comment by BonBonSlick** [comment]
Ok, thanks, yeah, smth wrong with VBox, to kill command there I had to recreate box, php restart does not helped.
