### ISSUE TITLE
ConfirmationQuestion normalizer may behave unexpectedly for Y/N question

### ISSUE THREAD

**Issue by mrthehud** [symfony/symfony#29835]
**Symfony version(s) affected**: 4.2

**Description**  
When using the ConfirmationQuestion class to ask a yes / no question, if the default is true, and the answer regex is '/^y/i', then any value not starting with [yY] is considered false - except "0"

**How to reproduce**  
Create a console application, and in the execute method:
```
    $question = new ConfirmationQuestion("Yes or No?", true);
    $ans = $this->io->askQuestion($question); 
    echo $ans ? 'true' : 'false';
```
Then run it, and observe the output:
Input: "yes", "y", "YES", "Y", "" (empty string) etc
Output: "true"
Input "no", "No", "foo", "Bar", "1", "true" etc
Output: "false"
Input: "0"
Output: "true" <- I would expect false, as the string does not match the regex

**Possible Solution**
https://github.com/symfony/console/blob/4a5d48d2ca2422c5c02ed37e4146fb65591369d5/Question/ConfirmationQuestion.php
```
    private function getDefaultNormalizer()
    {
        $default = $this->getDefault();
        $regex = $this->trueAnswerRegex;
        return function ($answer) use ($default, $regex) {
            if (\is_bool($answer)) {
                return $answer;
            }
            $answerIsTrue = (bool) preg_match($regex, $answer);
            if (false === $default) {
                return $answer && $answerIsTrue;
            }
            return !$answer || $answerIsTrue;
        };
    }
```
Change [line 56](https://github.com/symfony/console/blob/4a5d48d2ca2422c5c02ed37e4146fb65591369d5/Question/ConfirmationQuestion.php#L56:) (last return) to:
```
return strlen($answer) === 0 ? $default : $answerIsTrue;
```

**Comment by mrthehud** [comment]
I'm happy to PR this and add some tests if It's the right solution.

**Comment by ro0NL** [comment]
looks reasonable :) `return $answerIsTrue || $default` would also work isnt it

**Comment by mrthehud** [comment]
> looks reasonable :) `return $answerIsTrue || $default` would also work isnt it, as a replacement for both returns currently.

That didn't quite work out, it broke one of the other test cases I added, but did remind me that `return '' == $answer | $answerIsTrue` was cleaner.

**Comment by ro0NL** [comment]
i find the first branch confusing :)

```
            if (false === $default) {
                return $answer && $answerIsTrue;
            }
```

$answerIsTrue implies $answer is truthy already

**Comment by mrthehud** [comment]
Hmm, looks like the Appveyor tests failed, so I'll have to take a look at that when I get some time.
