### ISSUE TITLE
Symfony Console: Exception Output always shows Exception Class

### ISSUE THREAD

**Issue by Bavragor** [symfony/symfony#29838]
**Symfony version(s) affected**: 3.3.10

**Description**  
While maintaining an exit code above 0 there is no way in not showing the exception class to the user.
The only way to not show the exception class is currently for Symfony 3.3.* to set the exit code to 0, which will then result in problems with e.g. correct cronjob handling.

**How to reproduce**  
Execute a command with missing parameters, the message output will always show the exception class no matter which verbosity is set.

**Possible Solution**  
File: symfony/console/Application.php
Function: renderException
Line in 3.3.10: 690

Instead of simply use `get_class($e)` take the verbosity into consideration like the line below for the actual exit code.

**Comment by xabbuh** [comment]
Do you observe the same behaviour on Symfony 3.4? Does it make a difference in which environment (`prod` vs. `dev`) you execute the command?

**Comment by Bavragor** [comment]
Code in 3.4 seems to fix this, as we will need to upgrade to 3.4 because 3.3 is End of Life I'l close this.
Thank you for your help!
