### ISSUE TITLE
4.2.2 release changed the way tagged service are injected

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#29836]
**Symfony version(s) affected**: 4.2.2

**Description**  
The framework changed the way tagged service are injected

**How to reproduce**  
We are using API Platform, and it uses the following code:
```xml
        <service id="api_platform.subresource_data_provider" class="ApiPlatform\Core\DataProvider\ChainSubresourceDataProvider">
            <argument type="tagged" tag="api_platform.subresource_data_provider" />
        </service>
```
https://github.com/api-platform/core/blob/c20b86cfa6def8f1921dd7e02280d283fcd80e8a/src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml#L25-L27

On 4.2.1 when I dump the injected service I have:
```
array:6 [▼
  0 => AggregatedLogDataProvider {#854 ▶}
  # ....
  5 => CollectionDataProvider {#1117 ▶}
]
```

```
array:6 [▼
  0 => CollectionDataProvider {#6297 ▶}
  1 => AggregatedLogDataProvider {#1071 ▶}
  # ...
]
```
Note: `CollectionDataProvider` is the default Data Provider from API Platform, and `AggregatedLogDataProvider`, `#...` are my Data Provider

**Possible Solution**  

Patch all third party relying on this feature or fix Symfony.
Note: I tried to change the priority of the default Data Provider in APIP, and it fixes my issue.

**Comment by lyrixx** [comment]
This is a bit hard to bisect because we merge older branch. 
git bisect tells me it 7a7165ee0d4802bb82ff70275230070bc8920a52 
but obviously it's not that :( 
I will try on a 3.4 project but I don't have such project.

If someone has this, I used the following script:
```php
<?php

require __DIR__.'/vendor/autoload.php';

exec('rm -rf '.__DIR__.'/var/cache');

try {
    $k = new AppKernel('dev', true);
    $k->boot();
    $c = $k->getContainer();
} catch (\Exception $e) {
    exec('rm -rf '.__DIR__.'/var/cache');
    exit (2);
}

$dataProviders = $c->get('api_platform.collection_data_provider');
if (iterator_to_array($dataProviders->dataProviders)[0] instanceof AppBundle\Api\DataProvider\AggregatedLogDataProvider) {
    exec('rm -rf '.__DIR__.'/var/cache');
    exit (0);
}

exec('rm -rf '.__DIR__.'/var/cache');
exit(1);
```

and in `vendor/symfony/symfony` folder:

```
git bisect start && git bisect good v4.2.1 && git bisect bad v4.2.2 && git bisect run php ../../../test.php
```

**Comment by stof** [comment]
well, is there a way to force bisect to identify the merge commit merging the issue ? All our changes happen through merges (from PR, or from older branches). That would restrict the list of impacted changes (if it is a branch merge, we would then have to check only the few PRs merged in by this particular merge)

**Comment by stof** [comment]
just found https://github.com/dealertrack/merge-bisect which might help here.

**Comment by lyrixx** [comment]
I took a fresh 3.4 website-skeleton and added APIP on it.
I created a stupid DataProvider and run git bisect on it.
It could be e07ad2b477

**Comment by stof** [comment]
Yeah, `setDefinition` now removes the old definition entirely before adding the new one. So replacing a definition (when resolving ChildDefinition or decoration for instance) will now change the order of services (the service will move to the end).

**Comment by lyrixx** [comment]
Is it considered as a BC Break ? IMHO it should be because it breaks so many application

**Comment by nicolas-grekas** [comment]
Yes, let's revert that PR, it doesn't correctly fix the issue it was supposed to anyway. PR welcome.

**Comment by bastnic** [comment]
Thanks @fabpot
