### ISSUE TITLE
Trusted proxies

### ISSUE THREAD

**Issue by cv65kr** [symfony/symfony#29845]
**Symfony version(s) affected**: 4.2.1

**Description**  

I use nginx as reversy-proxy, when i set up some headers eg.

```
proxy_set_header TRUSTED-PROXIES 10.255.0.2;
proxy_set_header X-Forwarded-Proto $scheme;
```

The `$_SERVER['TRUSTED_PROXIES'] ` declare in `index.php` doesn't exist.
The header setup from nginx has a prefix `HTTP_`,  so param is available as `$_SERVER['HTTP_TRUSTED_PROXIES'] `

**How to reproduce**  

See above

**Possible Solution**  

```
if ($trustedProxies = $_SERVER['HTTP_TRUSTED_PROXIES'] ?? $_ENV['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}
```
instead of:

```
if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? $_ENV['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}
```

**Additional context**  

--

**Comment by xabbuh** [comment]
I am not sure I understand your setup. Do you mean that the reverse proxy is setting a header that tells the application the IP address of the reverse proxy?

**Comment by cv65kr** [comment]
Sorry for my confused post, i will try explain :)

I have a docker container with simple app which I set up:
```
parameters:
    router.request_context.host: 'domain.example.com'
    router.request_context.scheme: 'https'
```
Also inside container is nginx who expose app on some port eg. 88
I have a global nginx who is proxy for containers.

Port 88 should be able on domain.example.com so i set up proxy and headers:

```
proxy_set_header TRUSTED-PROXIES 10.255.0.2;
proxy_set_header X-Forwarded-Proto $scheme;
```

The problem is with headers, `TRUSTED-PROXIES` will be available on `$_SERVER` as `HTTP_TRUSTED_PROXIES` not as `TRUSTED_PROXIES`. When I set up `https` schema is overrided as `http`. If I change `$_SERVER['TRUSTED_PROXIES']` into `$_SERVER['HTTP_TRUSTED_PROXIES']` is everything fine and schema is `https`.

**Comment by xabbuh** [comment]
But do I understand correctly that in your setup it is the responsibility of the proxy to send an HTTP header to the application to inform it about the reverse proxy's IP address?

**Comment by cv65kr** [comment]
Yes, that's right

**Comment by xabbuh** [comment]
I wouldn't set up your infrastructure that way. This basically comes down to tufting any host. In case your application is not requested through the proxy the client will be able to spoof the trusted host header.

The code from the front controller that you refer to is meant to be used to evaluate an environment variable that you could set in the vhost config of your application which means that it cannot be spoofed by an attacker.

Therefore, I am going to close here as there is nothing to fix.
