### ISSUE TITLE
[Finder] Implicit glob used with in()

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#29846]
**Description**  
Symfony Finder is suggested like:

```
"symfony/finder": "For using double-star glob patterns or when GLOB_BRACE portability is required"
```

However

https://github.com/symfony/symfony/blob/4ba6397c5b24662755f1f5c20f65370cc2e0473d/src/Symfony/Component/Finder/Finder.php#L578

defeats the portability.

**Example**  

`Finder::create()->in('/some/{a,b}/')` is not portable.

~Perhaps leverage some parts of the `Glob` utility, to resolve the dirs as nessecary.~
https://3v4l.org/fDtdG

**Comment by stof** [comment]
the GlobResource used by the DI component (which is where this suggestion happens) is **not** passing the glob directly to `Finder::in`.

It relies on the Glob utility of the Finder component.

So this suggestion is perfectly fine.

**Comment by ro0NL** [comment]
Ok fair :) i misinterpreted the purpose of the package.
