### ISSUE TITLE
[Cache] Undefined variable in PSR6 simple cache

### ISSUE THREAD

**Issue by Remo** [symfony/symfony#29843]
**Symfony version(s) affected**: Master-Branch

**Description**  
There's an undefined variable in the PSR6 simple cache.

**How to reproduce**  
I'm afraid, but I don't know where that would cause a problem, I've just noticed it when I was reading the code.

**Possible Solution**  
Rename `$value` to `$values`.

**Additional context**  
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Simple/Psr6Cache.php#L157

**Comment by nicolas-grekas** [comment]
Good catch, thanks.
