### ISSUE TITLE
[WebProfilerBundle] toolbar: invisible route name in Firefox

### ISSUE THREAD

**Issue by TomaszGasior** [symfony/symfony#29858]
**Symfony version(s) affected**: 4.2.2

**Description**  
In Firefox, when route name is too long, it's invisible on the debug toolbar. Screenshots from Chrome and from Firefox below. I did also additional check without any extra stylesheets, with the same effect.

**How to reproduce**  
Go to page with long route name. I used `user.my_account_settings` on my screenshot.

**Possible Solution**  
Remove `text-overflow: ellipsis;` from `.sf-toolbar-block .sf-toolbar-icon` in `toolbar.css.twig`.

**Additional context**  

![image](https://user-images.githubusercontent.com/243674/53302563-92f3a380-385f-11e9-9135-fd51ded1ee72.png)

**Comment by TomaszGasior** [comment]
There is no problem with it. Without text-ellipsis route name is rendered without breaking UI. Look at this screenshot: https://i.imgur.com/Emjno6G.png

**Comment by ro0NL** [comment]
removine

```
.sf-toolbar-block .sf-toolbar-info-piece-additional, .sf-toolbar-block .sf-toolbar-info-piece-additional-detail {
    display: inline-block;
}
```

seems to show the ellepsis both in chrome and FF, but it's colored blue.. so a bit hidden.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig#L517

should check for history, what this solved :)

**Comment by inmarelibero** [comment]
putting `display: inline;` instead of `display: inline-block;` seems working to me

so the proposed modification is:
```
    .sf-toolbar-block .sf-toolbar-info-piece-additional,
    .sf-toolbar-block .sf-toolbar-info-piece-additional-detail {
        display: inline;
    }
```

at https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig#L517

I can produce a PR if needed

**Comment by nicolas-grekas** [comment]
Please send a PR yes.

**Comment by inmarelibero** [comment]
@nicolas-grekas here you are: https://github.com/symfony/symfony/pull/30383
