### ISSUE TITLE
[Serializer] Add PSR-6 cache on $discriminatorCache

### ISSUE THREAD

**Issue by franek** [symfony/symfony#29878]
**Description**  
@fbourigault has done a great job in order to Reduce class discriminator overhead with Symfony 4 (https://github.com/symfony/symfony/pull/28889). Nevertheless, it would be nice if $discriminatorCache implements PSR-6 cache. Cache will be populate on the first request and all other requests, will use the cache.

```
class ObjectNormalizer extends AbstractObjectNormalizer
{
    protected $propertyAccessor;

/** Replace array by a PSR-6 implementation */
    private $discriminatorCache = array();

    public function __construct(ClassMetadataFactoryInterface $classMetadataFactory = null, NameConverterInterface $nameConverter = null, PropertyAccessorInterface $propertyAccessor = null, PropertyTypeExtractorInterface $propertyTypeExtractor = null, ClassDiscriminatorResolverInterface $classDiscriminatorResolver = null)
    {
...
    }
```

Do you think it is a good idea to work on this feature ?

**Comment by fbourigault** [comment]
Replacing the array by a PSR-6 implementation will re-add some overhead as PSR-6 is slow.

As metadata already use a PSR-6 cache,  I don't know if adding a PSR-6 cache for discriminator will improve the serializer performances.

**Comment by nicolas-grekas** [comment]
Closing as bold guess about performance are usually wrong (even claiming PSR-6 is slow is a bold guess without a profile).
Please provide metrics and we'll talk :)
Closing as this file is pretty well scrutinized for perf these days.
