### ISSUE TITLE
[Form][Date(Time)Type] Use a custom string date format

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#29883]
Currently there is no way to use a custom string date format (cf https://github.com/symfony/symfony/blob/508602d99503e7bd1d45b604fcb3024dbc0164c3/src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php#L179).

This is a problem if you already have data in another format than the default one. It becomes impossible to use these form types without a data migration.

Should we add a "string_format" option ? @xabbuh

**Comment by stof** [comment]
The data transformer already supports this setting. Exposing it in the form type for people using the `string` input makes sense to me.
What do you think @HeahDude ?

**Comment by xabbuh** [comment]
Adding a new option like `input_format` to be used in conjunction with the input being a string sounds reasonable to me.

**Comment by xabbuh** [comment]
implemented in #29887
