### ISSUE TITLE
Improve the way exceptions are listed in the error page

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#29891]
**Description**  
The order in which multiple exceptions are displayed in the error page is sometimes confusing.

**Example**  
If you make a mistake in the `config/services.yaml` file of the Symfony Demo app, you see this:

![exception](https://user-images.githubusercontent.com/73419/51179781-d7863980-18c6-11e9-8b2d-453d2327d1fb.png)

There is a perfect exception message that tells you exactly what happened ... but it's "buried" so low, that you probably won't see it.

If we reverse the order of exceptions in this case, the error page would be much better.

The above has happened to me several times with different errors ... but the opposite too: sometimes the current order is the best order. So:

* Should we reverse the order of exceptions in the error page in all cases?
* Is this a matter of tweaking some but not all exceptions?

Thanks!

**Comment by ro0NL** [comment]
UX-wise; what about collapsing the stack trace for all exceptions, except the last one by default ...

In case of a single exception nothing changes. In case of N exceptions, it might trigger the user to start debugging from the bottom.

Design-wise; i think we should better convey the meaning of "3/3", which really means "this error is caused by another error".

**Comment by javiereguiluz** [comment]
@ro0NL we already do that for the complex error page, but this one is the simple error page showed sometimes and we cannot add complex JS behavior.

**Comment by stof** [comment]
The YamlLoader should indeed probably carry over details about the ParseException instead of only saying `file contains invalid YAML`.
The LoaderLoadException already carries over the message with extra details about the location, but currently, it carries over a useless message.

**Comment by stof** [comment]
I would not reverse the order. The one on top today is the one you can catch if you need to catch something (others are wrapped), and is the one having the more info available to provide useful error message (as it has access to the wrapped message, plus to any extra info it can have in the place where the wrapping happens).

**Comment by jkufner** [comment]
Please keep in mind, that many people will send you a screenshot of such a page. Therefore the information useful to a developer should be visible without scrolling the page or clicking anything.

**Comment by zmitic** [comment]
Would it make sense that exceptions are ordered by severity? 

Example: exceptions extending ``RuntimeException`` are above those extending ``InvalidArgumentException``?

**Comment by nicolas-grekas** [comment]
Honestly, I'm fine with the order. Wrapping exceptions should do a better job at conveying the error message, that's where we should put effort.

But I think the priority of information is not correct on this page.
I don't care reading "Whoops, something went wrong" in big text: I seek for the error message.
Right now, it's nested as third level, below the class type. I think it should be first class info and should replace this "whoops".

**Comment by javiereguiluz** [comment]
I'm afraid it's up to date. I've just took this screenshot with Symfony Demo "master" and Symfony 4.2.2:

![symfony-demo-error](https://user-images.githubusercontent.com/73419/51913602-2bb90f80-23d7-11e9-9897-5db7b97fc4b7.png)

**Comment by nicolas-grekas** [comment]
We have two debug pages: one in the WebProfilerBundle and another one in the Debug component, for situations that fail before we can boot the bundle. Looks like that's where this page comes from.
PR welcome on the ExceptionHandler!

**Comment by javiereguiluz** [comment]
I'm going to try to improve this.
