### ISSUE TITLE
Setting empty_data on ChoiceType causes error

### ISSUE THREAD

**Issue by EmanuelOster** [symfony/symfony#29895]
**Symfony version(s) affected**: 3.4.21

**Description**  
When I set the empty_data option in a ChoiceType form field to `"-"`, and then actually select the empty field, I get the following validation error:
> This value is not valid.

**How to reproduce**  
```php
->add('test', ChoiceType::class, array(
                 'label' => 'Test',
                 'choices'     => ['test' => 'test'],
                 'placeholder' => "Please choose",
                 'empty_data'  => '-',
                 'required'    => false))
```

**Possible Solution**  
I debugged it down to the `ChoiceToValueTransformer` which accepts only `null` and `''` as empty values:
```php
if (1 !== \count($choices)) {
            if (null === $value || '' === $value) {
                return;
            }

            throw new TransformationFailedException(sprintf('The choice "%s" does not exist or is not unique', $value));
        }
```

Not sure though how to fix it.

**Comment by yceruto** [comment]
It seems expected for `ChoiceType`, data transformers apply to `empty_data` value and anyway you'll get a `null` value if we accept custom check `'-' === $value`.

> https://symfony.com/doc/current/reference/forms/types/choice.html#empty-data
> Form data transformers will still be applied to the empty_data value. This means that an empty string will be cast to null. Use a custom data transformer if you explicitly want to return the empty string.

You can do the following instead:
```php
->add('test', ChoiceType::class, [
    'label' => 'Test',
    'choices' => ['Please choose' => '-', 'test' => 'test'],
    'required' => true,
])
```

**Comment by yceruto** [comment]
This look a misuse of the `empty_data` option, I think can be closed.
