### ISSUE TITLE
Form Validation Error for Array input

### ISSUE THREAD

**Issue by lngphp** [symfony/symfony#29905]
After upgrading symfony/form to v4.2.2 from v4.2.1, I'm having form validation error. Actually, I think it's correct behavior now, because an input data is an Array while form element is of `TextType`. Not sure why it was working before though :) To solve the issue, I tried to use `Data Transformers`, however both transform callable arguments are empty for some reason. How can I resolve it?

**Comment by cvilleger** [comment]
I have the same error ! I lost hours to understand that... The only solution I have is to downgrade to `4.2.1`

**Comment by lngphp** [comment]
> I have the same error ! I lost hours to understand that... The only solution I have is to downgrade to `4.2.1`

I also rolled back to 4.2.1.

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/issues/29841

**Comment by xabbuh** [comment]
I just proposed #29911 which could hopefully mitigate the impact a bit.

**Comment by ThibDums** [comment]
> I have the same error ! I lost hours to understand that... The only solution I have is to downgrade to `4.2.1`

How did you downgrade to 4.2.1 ? You have to downgrade all packages versions too ?

**Comment by lngphp** [comment]
> > I have the same error ! I lost hours to understand that... The only solution I have is to downgrade to `4.2.1`
> 
> How did you downgrade to 4.2.1 ? You have to downgrade all packages versions too ?

`composer require symfony/form:4.2.1`

**Comment by nicolas-grekas** [comment]
Closing as not a bug, see linked issues.
