### ISSUE TITLE
[Messenger] Providing support for heartbeat & AMQP 0-9-1 ?

### ISSUE THREAD

**Issue by jtexier** [symfony/symfony#29908]
**Description**  
AMQP 0-9-1 came (a few years ago now) with a great feature to handle dead TCP connections which is called heartbeat : https://www.rabbitmq.com/heartbeats.html

As I understand it, Messenger uses \AMQPConnection which is only 0-8 AMQP compatible so heartbeat is not natively available on Messenger.

Is there any reason why Messenger relies on a outdated version of AMQP protocol ? 
Is an upgrade to 0-9-1 is currently planned, maybe using https://github.com/php-amqplib/php-amqplib in place of AMQPConnection ?

Regards

**Comment by jtexier** [comment]
Well,

Heartbeat is a AMQP 0-9-1 feature, https://www.rabbitmq.com/heartbeats.html.

By reading php doc, it looks like that \AMQPConnection is only 0.8 compatible http://php.net/manual/fa/intro.amqp.php

So as I understand it (but maybe I'm wrong) :  Messenger doesn't natively support heartbeat.
If not, maybe could you provide a example of that ?

Regards

**Comment by Tobion** [comment]
The doc you are referencing is very outdated. As you can see the doc does not exist in English.
For update to date info you need to check https://pecl.php.net/package-changelog.php?package=amqp and https://github.com/pdezwart/php-amqp

**Comment by jtexier** [comment]
You're right, my misunderstanding was coming from core PHP doc which is totaly outdated. 
Thanks
