### ISSUE TITLE
[Webpack Encore][Twig] include asset again into error pages

### ISSUE THREAD

**Issue by eschultz-magix** [symfony/symfony#29901]
**Symfony version(s) affected**: 4.2

**Description**  
The ```EntrypointLookup``` prevents including a file multiple times by default. But it prevents re-using a stylesheet in an error template if an error occurs during the rendering of a template that re-uses the layout. This is because the ```ExceptionController``` will clear the output buffers.

**How to reproduce**  
1. checkout symfony/demo
2. add a twig runtime error into the homepage template inside the body, f.ex. ```{{ 1 / 0 }}```
3. the error template will not embed the "css/app" stylesheet again as it has been already rendered before

**Possible Solution**  
The ```EntryPointLookup``` class must only return a template once *per request*.

**Comment by xabbuh** [comment]
The `EntryPointLookup` class is part of the WebpackEncoreBundle which hs [its own repository](https://github.com/symfony/webpack-encore-bundle). Can you please report the issue over there?

**Comment by eschultz-magix** [comment]
@xabbuh Sure, I thought the bundle is handled as a Symfony component. I have re-submitted the bug to https://github.com/symfony/webpack-encore-bundle/issues/31
