### ISSUE TITLE
[Translator] Decorator using new TranslatorInterface

### ISSUE THREAD

**Issue by ewaldvanderveken** [symfony/symfony#29915]
I'm not sure if I'm doing something wrong, or if this is a bug, but a while ago I created a TranslatorDecorator:

`class TranslatorDecorator implements TranslatorInterface, TranslatorBagInterface {}`

When I noticed the `Symfony\Component\Translation\TranslatorInterface` was deprecated, I replaced it with the new `Symfony\Contracts\Translation\TranslatorInterface` and implemented the LocalAwareInterface too:

`class TranslatorDecorator implements TranslatorInterface, TranslatorBagInterface, LocaleAwareInterface  {}`

I've defined the decorator in my services like this:

```
services:
    app.translator_decorator:
        class:     My\Bundle\TranslatorDecorator
        decorates: translator.default
        arguments:
            - '@app.translator_decorator.inner'
        public: false
```

Now, this all works on a **dev** environment, but on production (APP_ENV=prod), I'm always getting this fatal error:

```
Uncaught TypeError: Argument 1 passed to Symfony\Component\Validator\ValidatorBuilder::setTranslator() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of My\Bundle\TranslatorDecorator given
```

Am I doing something wrong? I can't seem to figure it out 😅

**Comment by xabbuh** [comment]
For the moment I see no other solution than still implementing the old interface too as there is still code relying on the legacy interface being injected.

**Comment by ro0NL** [comment]
Doesnt it use tge `Symfony\Component\Validator\Util\LegacyTranslatorProxy` to wrap the proper translator with. You shouldnt implement nor rely on the legacy interface IMHO.

**Comment by crayner** [comment]
I have had the same issue, but define both old and new Translator interfaces until appropriate code changes are made.  e.g.

    use Symfony\Component\Translation\TranslatorBagInterface;
    use Symfony\Contracts\Translation\LocaleAwareInterface;
    use Symfony\Contracts\Translation\TranslatorInterface;
    use Symfony\Component\Translation\TranslatorInterface as LegacyTranslatorInterface;

    class TranslationManager implements TranslatorInterface, TranslatorBagInterface, LocaleAwareInterface, LegacyTranslatorInterface

**Comment by ewaldvanderveken** [comment]
Ok, thanks for help! 😄
