### ISSUE TITLE
[Form] add hidden field to form when CSRF is disabled

### ISSUE THREAD

**Issue by wwwd3v** [symfony/symfony#29916]
**Description**  
Hi, sometimes you want to have a "dummy" or "empty" form just to force the HTML POST request, i.e.
```
class DeleteArticle extends AbstractType
{
}
```

This works perfectly with the CSRF turned on, as a hidden input field is added.

However, when for instance doing e2e testing, I found myself turning off the CSRF protection. This, however, breaks the empty form, as a form with no input is not a valid HTML form submission, therefore `$form->isSubmitted() // => false`;

What I ended up doing was sth like this:
```
if ($env !== 'prod') {
    $builder->add('make_form_submit', HiddenType::class)
}
```

I was wondering if this should not be the natural responsibility of the Form component - determine whether a form has any inputs at all, and if not, append a hidden field for the sole purpose of being able to submit the form.

Or would this not be desired? Does anyone actually take advantage of the fact that inputless forms cannot be submitted? I have always regarded it as an HTML bug/sth to normalize, rather than a useful feature.

Thanks for your answers :)

**Comment by xabbuh** [comment]
How do you submit a form that has no fields at all?

**Comment by wwwd3v** [comment]
Consider a delete button which should do a DELETE request.

You do POST to `/article/35` using a Form (perhaps even spoof it to DELETE using Form component).

Yes, you could do a JS asynchronous call, but I am talking "Pure HTML" way of doing it.

Then, your form is pretty much
<form method="post" name="article-delete-form">
<button type="submit">DELETE article!</button>
</form>

**Comment by ro0NL** [comment]
If you build the form using `SubmitType` only, it would be submittable isnt it?

**Comment by wwwd3v** [comment]
OK, I investigated.

If you use `SubmitType`, it works.

It did not come to my mind because it is [in violation with the best practices](https://symfony.com/doc/current/best_practices/forms.html#form-button-configuration). In my case, the practice is irrelevant (and, in fact, wrong), as a Delete button (or Logout, etc.) is a single-purpose form. 

I could expand the documentation if you wish, in order to make it more obvious/warn about this edge-case, because if you do not put a submit on the form class, you must **add the `name property`** to your button, and the name must **match the name of the form**.

```
<form method="post" name="yourform">
    <button type="submit" name="yourform">DELETE article!</button>
</form>
```
This knowledge is quite ephemeral, as the "best practices" article says nothing about the necessity, take a look at the docs code example:
```
{{ form_start(form) }}
    {{ form_widget(form) }}

    <input type="submit" class="btn" value="Create" />
{{ form_end(form) }}
```
From the docs, one gets the idea that nothing more is necessary in order to make the form submit.

**Comment by wwwd3v** [comment]
@xabbuh yes, that is a good point, however, sometimes you want a single-purpose POST.

My point, at this stage, is in fixing the docs, which are inconsistent :)

But thanks for pointing that out 👍

**Comment by ro0NL** [comment]
why not simply `$request->isMethod('POST')`, and avoid a form without fields. There's no real field definition anyway; i.e. you could just render a form+submit tag to trigger a post request.

**Comment by wwwd3v** [comment]
@ro0NL 

1. thanks for pointing that out, but as I already told @xabbuh, I am not looking for a solution at this stage - I have it solved already for me :) 

But the docs are, as I explained, inconsistent, they lead to false conclusions.

2. Your method is not, in fact, very valid if you have multiple single-purpose forms on the same page. You might have a Logout button on a page where you have a Delete article button.
