### ISSUE TITLE
Symfony onPreSubmit() update data then onSubmit() different data ??

### ISSUE THREAD

**Issue by ThibDums** [symfony/symfony#29917]
I update the data in my onPreSubmit() function :

```
 public function onPreSubmit(FormEvent $event) {
    $data = $event->getData();

    unset($data['test']);

    $event->setData($data);
}
```

When i dump `dump($event->getData())` at the end of my function preSubmit(), all data is ok. But when I try to get the data in my `onSubmit()` function, the data is reset...

```
public function onSubmit(FormEvent $event) {
    $data = $event->getData();
}
```

The key "test" is still present... I guess it is a bug ?

In my buildForm() function, the events are present :

```
public function buildForm(FormBuilderInterface $builder, array $options) {
    ...
    ...
    $builder->addEventListener(FormEvents::POST_SET_DATA, [$this, 'onPostSetData']);
    $builder->addEventListener(FormEvents::PRE_SUBMIT, [$this, 'onPreSubmit']);
    $builder->addEventListener(FormEvents::SUBMIT, [$this, 'onSubmit']);
}
```

**Comment by ThibDums** [comment]
I didn't change any code by the way, it worked before i upgrade composer.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce it?

And can you also tell us from which version you updated to which?

**Comment by ThibDums** [comment]
What do you need exactly for the example ? more code ?
I upgraded to 4.2.1 to 4.2.2.

How can i downgrade version ?

**Comment by xabbuh** [comment]
An application that we could just checkout and then run a test or a controller that demonstrates the issue would be the best.

You can, for example, add a conflict rule to your `composer.json` file and then run `composer update symfony/form`:

```json
{
    "conflict": {
        "symfony/form": "4.2.2"
    }
}
```

**Comment by ThibDums** [comment]
Maybe it's not a problem form the form bundle, i launched a full update, it updated a bunch of packages, included symfony 4.2.2, how can i go back on symfony global 4.2.1 with all packages ?

**Comment by xabbuh** [comment]
When using Symfony Flex, afaik you should be able to do something like this:

```json
{
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.2.1"
        }
    }
}
```

But maybe it's easier to not spend to much time on this and rather try to create a small example application. That could just be enough to let us investigate what happens and then figure out afterwards what caused the change in behaviour.

**Comment by xabbuh** [comment]
@ThibDums Any news? :)

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
