### ISSUE TITLE
Implicit param converter seems to not work anymore 4.2.2

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#29925]
**Symfony version(s) affected**: 4.2.2

Hello!

**Description**  
I'm in pain to make the well known implicit ParamConverter trick work with Symfony 4.2.2:

```
/**
 * @Route("/{id}", name="admin_post_show")
 */
public function show(Post $post)
```

It tells that the Post argument cannot be autowired.

**How to reproduce**  
Just follow the exemple given in [the best practices guide](https://symfony.com/doc/current/best_practices/controllers.html#using-the-paramconverter).

**Possible Solution**  
No idea, sorry!

**Additional context**  
Could relate to #29819 (not sure as the ticket is closed).

Thank you for your feedback!

**Comment by xabbuh** [comment]
Can you confirm that updating the DependencyInjection component to `4.2.3@dev` solves the issue?

**Comment by fabienlem** [comment]
OK, I will try as soon as possible and keep you updated. Thank you!

**Comment by Soullivaneuh** [comment]
@xabbuh I have a similar issue making entity creation impossible with API platform custom controllers.

Using the 4.2 dev branch seems to fix it indeed.

**Comment by xabbuh** [comment]
Let's close here then as the issue seems to be fixed by #29853.

**Comment by fabienlem** [comment]
Hello @xabbuh,

Sorry for my late reply.

I'm not able to update the dependency injection component.

```
$ php ../composer.phar req symfony/dependency-injection '4.2.3@dev'

  [InvalidArgumentException]
  Could not find package symfony/dependency-injection in a version matching 4
  .2.3@dev

```

What can I do?

**Comment by fabienlem** [comment]
Hello @xabbuh,

I found the solution by installing a vanilla Symfony 4.2 and comparing composer.json file with the one of my project. I saw that sensio/framework-extra-bundle was missing.

I don't remember how the project was initialised, so I don't know why this vendor was missing.

Thank you again for your help.

Regards!
