### ISSUE TITLE
[MIME component] Alternative effort

### ISSUE THREAD

**Issue by mondrake** [symfony/symfony#29938]
Hi, looks like we are up to similar goal:

https://github.com/FileEye/MimeMap and https://github.com/symfony/mime

Any opportunity to combine efforts?

**Comment by nicolas-grekas** [comment]
Hello,
given that MimeMap is LGPL2, we cannot adopt any of your code, unless you want to contribute some to Symfony under the MIT license?
If you feel like improving the component, feel free to submit PRs, and RFCs before in any doubt.
Closing meanwhile :)
Thanks for opening!
