### ISSUE TITLE
[WebProfiler] Add help link in WebProfiler

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#29943]
**Description**  
The first reflex for Symfony newcomers or developers when they get an error is to copy/past the Exception and search on (Documention, Google, Stackoverflow, Slack...)

The idea is to create these links in the webprofiler, under an `Help` section. All link will be displayed in the profiler and in the panel. If there is an exception an other link will **contains the error as a query**.
https://google.com/search?`q=TheErrorMessage
https://stackoverflow.com/search?`q=TheErrorMessage
You can try it here https://github.com/ismail1432/help-profiler-sandbox
just clone the repo, launch the webserver and you will get an error and see my proposition

I'm ready to develop the feature if the community is Ok :-)

**Exemple**
![capture d ecran de 2019-01-20 22-17-13](https://user-images.githubusercontent.com/13260307/51445236-2c7ce200-1d03-11e9-841a-2e673409f094.png)
![capture d ecran de 2019-01-20 22-32-22](https://user-images.githubusercontent.com/13260307/51445261-71a11400-1d03-11e9-847b-16e05a9882ea.png)

**Comment by stof** [comment]
Error messages can contain sensitive info (for instance, an exception coming from the database layer). So I'm not convinced either it is a good idea.

**Comment by ismail1432** [comment]
Thanks for your feedback I closed the issue :+1:
