### ISSUE TITLE
[Validator] UrlValidator and UTF8-NFD

### ISSUE THREAD

**Issue by ThauEx** [symfony/symfony#29953]
**Symfony version(s) affected**: 3.4+ (have not tested older versions)

**Description**  
It looks like the UrlValidator has issues with UTF-8-NFD encoded urls/filesnames. This encoding is used on macs and and when validating urls with umlauts in it's filesname, which have ben generated on macs, the validator will fail.
In my example it validates 
`https://example.com/köchin.html`
fine, but not
`https://example.com/köchin.html`
With UTF-8-NFD umlauts are saved as basicly two characters and not as a single one, like in the normal UTF-8.

**How to reproduce**  
Here is an example with the symfony url validator regex:
https://regex101.com/r/0OkiOJ/2

Leave only the first url and it will match, delete the first and leave the second will not match.

**Comment by sstok** [comment]
Some interesting background information: https://stackoverflow.com/questions/7931204/what-is-normalized-utf-8-all-about

According to https://serverfault.com/questions/397420/converting-utf-8-nfd-filenames-to-utf-8-nfc-in-either-rsync-or-afpd this can done be used using iconv with `UTF-8-MAC` to `UTF-8` or using http://php.net/manual/en/normalizer.normalize.php (requires ICU/Intl extension).

**Comment by gharlan** [comment]
> http://php.net/manual/en/normalizer.normalize.php (requires ICU/Intl extension).

.. or the polyfill: https://github.com/symfony/polyfill/blob/master/src/Intl/Normalizer/bootstrap.php#L16

**Comment by ro0NL** [comment]
I think after #26484 you could simply handle this case with `['normalizer' = > 'Normalizer::normalize']`. Not sure core should deal with any encoding other then UTF-8 :thinking:

**Comment by sstok** [comment]
Technically it's still UTF-8, but a version that is storage optimized and only used by macOS 🤷‍♂️

**Comment by ThauEx** [comment]
Looks like the normalizer did it, works fine now.
Sorry for the late response, we just upgraded to Symfony 4, so we had to wait until that, in order to use the normalizer.
