### ISSUE TITLE
Native PO and MO pluralization

### ISSUE THREAD

**Issue by Stadly** [symfony/symfony#29963]
The [PO translation file format](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) and [MO translation file format](https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html) natively support pluralization, making it easy to translate pluralizable strings using tools such as [Poedit](https://poedit.net).

The [PoFileLoader](https://github.com/symfony/translation/blob/master/Loader/PoFileLoader.php) and [MoFileLoader](https://github.com/symfony/translation/blob/master/Loader/MoFileLoader.php) support the native pluralization.

The [PoFileDumper](https://github.com/symfony/translation/blob/master/Dumper/PoFileDumper.php) and [MoFileDumper](https://github.com/symfony/translation/blob/master/Dumper/MoFileDumper.php), however, do not support the native pluralization. It would be really nice if this could be implemented.

The PO format is:
```
msgid untranslated-string-singular
msgid_plural untranslated-string-plural
msgstr[0] translated-string-case-0
...
msgstr[N] translated-string-case-n
```

For example:
```
msgid "found %d fatal error"
msgid_plural "found %d fatal errors"
msgstr[0] "s'ha trobat %d error fatal"
msgstr[1] "s'han trobat %d errors fatals"
```

This works very well when the untranslated language only has two pluralization forms (singular and plural). The translated language can have more complex rules. I don't think the native pluralization can be used when the untranslated language has complex pluralization rules, or when using [Explicit Interval Pluralization](https://symfony.com/doc/current/components/translation/usage.html#explicit-interval-pluralization).

Note: It seems that the [Qt format](http://doc.qt.io/qt-5/linguist-ts-file-format.html) also support pluralization natively (`numerusform`). The [QtFileDumper](https://github.com/symfony/translation/blob/master/Dumper/QtFileDumper.php) does not support this, and it doesn't seem that [QtFileLoader](https://github.com/symfony/translation/blob/master/Loader/QtFileLoader.php) does either.

**Comment by nicolas-grekas** [comment]
Would you like to send a PR to achieve so? That'd be welcome and the best way to make it happen if you need it.

**Comment by deguif** [comment]
I had a look a look at this issue for #eufossa
It's not possible to dump plural form for PO/MO file as plural form can't be determined from the translations catalogue, (plural and singular in PO/MO are different keys) that's why it's not implemented.

**Comment by nicolas-grekas** [comment]
Makes sense, please submit a PR if you think otherwise ;) I'm closing for now.

**Comment by Stadly** [comment]
I've now submitted a PR :) #31269
