### ISSUE TITLE
References in PO translation files

### ISSUE THREAD

**Issue by Stadly** [symfony/symfony#29962]
The [PO translation file format](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) supports references, so that one can easily see where the message is used in the source files. This can be very helpful when translating.

The [PoFileDumper](https://github.com/symfony/translation/blob/master/Dumper/PoFileDumper.php) does not support references. It would be really nice if this could be implemented.

The format is:
```
#: path\to\file:line
#: path\to\other\file:line
msgid untranslated-string
msgstr translated-string
```

For example:
```
#: lib/error.c:116
msgid "Unknown system error"
msgstr "Error desconegut del sistema"
```

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR to support this?
