### ISSUE TITLE
[Messenger] SerializerStamp is never used in decode

### ISSUE THREAD

**Issue by kunicmarko20** [symfony/symfony#29970]
**Symfony version(s) affected**: 4.2

**Description**  
SerializerStamp won't be used in decode.

https://github.com/symfony/symfony/blob/a9f8ca57af08c795f296cba14374d04900cca9c9/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L74-L76

This will never be `true` because [decodeStamps](https://github.com/symfony/symfony/blob/a9f8ca57af08c795f296cba14374d04900cca9c9/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L102-L117) returns:

```
array(1) {
      │   [0]=>
      │   object(Symfony\Component\Messenger\Stamp\SerializerStamp)#1012 (1) {
      │     ["context":"Symfony\Component\Messenger\Stamp\SerializerStamp":private]=>
      │     array(0) {
      │     }
      │   }
      │ }
```
And `isset($stamps[SerializerStamp::class])` is checking the key which is `0` here.

https://github.com/symfony/symfony/blob/a9f8ca57af08c795f296cba14374d04900cca9c9/src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php#L75-L96

This test never checked if the group is actually applied, it just checks if stamp is there and it will always be there, it just won't be used.

**How to reproduce**  
Install messenger with Symfony serializer, add SerializerStamp and see if it is used when you get a response.

**Comment by kunicmarko20** [comment]
I am writing JMS Serializer adapter and I run into this issue because I was trying to replicate the same implementation. 

How I fixed this:

When decoding stamps added the type as a key:
https://github.com/kunicmarko20/jms-messenger-adapter/blob/master/src/Serializer.php#L75

and removed:

https://github.com/symfony/symfony/blob/a9f8ca57af08c795f296cba14374d04900cca9c9/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L113


That solves the isset issue, but then there is an issue with unpacking stamps:

https://github.com/symfony/symfony/blob/a9f8ca57af08c795f296cba14374d04900cca9c9/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L80

Unpacking doesn't work with string keys and now the unpacking won't even help here as the structure of the array is different:

```
[ 'StampClassName' => [0 => Stamp object, 1 => Stamp object], 'StampClassName2' => ...]
```

So I added a new method that extracts the stamps for Envelope:

https://github.com/kunicmarko20/jms-messenger-adapter/blob/dc6a6f3b6e077ec38c3b4c0075a8b4575133d6e7/src/Serializer.php#L47-L61

Not sure if this is the best way, would love to get some feedback and see if you can find a better way so I can change it in my adapter.

**Comment by nicolas-grekas** [comment]
Is this something you would like to send a PR for?

**Comment by kunicmarko20** [comment]
I proposed a solution in the second comment if there are no better ideas I can provide a PR for that.

**Comment by sroze** [comment]
Thank you @xabbuh !
