### ISSUE TITLE
Progress bar verbosity

### ISSUE THREAD

**Issue by Nemo64** [symfony/symfony#29974]
**Description**  
The `ProgressBar` automatically determines the format. There are 4 different formats for different verbosities.

Is there a reason to not show the estimated time and memory? Having to go into very verbose mode adds all kind of logging to the console that i don't want to see. And while working with TYPO3 i'm not even able to go into very verbose.

**Comment by hjanuschka** [comment]
hey @Nemo64 


you can very easy provide a custom log format:


```php

ProgressBar::setFormatDefinition(
            'custom',
            " <fg=yellow>%percent%% (%current%/%max%) %elapsed:6s%</fg=yellow>\n[%bar%]\n<fg=yellow>*</fg=yellow> <fg=green>%message%</fg=green> <fg=cyan>%slug%</fg=cyan>"
        );
        $progressBar->setFormat('custom');



```


documentation:  https://symfony.com/doc/current/components/console/helpers/progressbar.html#custom-formats

**Comment by Nemo64** [comment]
I know and that's really nice.

But I'm mostly a user of commands and can't modify vendor code. In symfony I'll always have to run my commands with `-vv` to get the estimate but that can spam my console with logging information that i might not want. And in TYPO3 i'm not able to go into very verbose output mode.

And the fundamental question is why these informations are hidden in the first place. Other than logging informations, the stats like estimate and memory consumption don't clutter the console so there isn't a disadvantage of showing them even in normal mode.

But sure thing, i can just overwrite the defaults:
```PHP
ProgressBar::setFormatDefinition('normal', ProgressBar::getFormatDefinition('very_verbose'));
ProgressBar::setFormatDefinition('normal_nomax', ProgressBar::getFormatDefinition('very_verbose_nomax'));
ProgressBar::setFormatDefinition('verbose', ProgressBar::getFormatDefinition('very_verbose'));
ProgressBar::setFormatDefinition('verbose_nomax', ProgressBar::getFormatDefinition('very_verbose_nomax'));
```

**Comment by ostrolucky** [comment]
Maybe because of tests? This information is highly runtime dependent, not deterministic.

**Comment by Nemo64** [comment]
You mean tests of the progress component itself? That problem is currently solved by replacing the placeholder function. https://github.com/symfony/symfony/blob/v4.2.7/src/Symfony/Component/Console/Tests/Helper/ProgressBarTest.php#L779
But sure the tests would become more complicated. The equals operations could also be replaced with `StartsWith` or regex matches to have placeholders in the memory section.

Or do you mean if someone tests their own command that uses that component? I got to admit that i never tested my commands, only the services behind them.

**Comment by chalasr** [comment]
I'm going to close this issue as it did not bring much reactions from the community and I think the current default is good enough. Thanks for proposing.
