### ISSUE TITLE
[Form] placeholder HTML attribute throws warning and missing message translation in profiler

### ISSUE THREAD

**Issue by Havrin** [symfony/symfony#29972]
**Symfony version(s) affected**: 3.4

**Description**  
Using a translated value for the `placeholder` HTML-attribute in form builder, results in warnings and missing message errors in the profiler because the translated value is not found as a translation key.
Placeholder automatically translates the given value and interprets it as a translation key. But what if I want to use a translation domain? Different to the domain label uses? Or if I have variables filled in the translation?

**How to reproduce**  
given `another_domain_than_label_below`.yml:
```yaml
foo:
    bar: '%foo% placeholder'
```

given formbuilder:
```php
$builder->add(
            'foo',
            FooType::class,
            [
                'attr' => [
                    'placeholder' => $this->translator->trans(
                        'foo.bar',
                        [
                            '%foo%' => 'test'
                        ],
                        'another_domain_than_label_below'
                    ),
                ],
                'label' => 'foo.label',
                'translation_domain' => 'label_domain',
                ...
            ]
        );
```

This will result in a `Translation not found.` warning as well as a `Missing Message` where tries to find the message ID "test placeholder" (given the example above). He is translating the already translated values.

This also occurs if try to do this in Twig:
```twig
{{ form_widget(form.foo, {
                        "attr": {
                            ...
                            "placeholder": "foo.bar"|trans({
                                '%foo%' : test
                            })
                        }
                    }) }}
```

Also tried with `{% set foo ...` before and setting the value directly. Still the warning pops up in the profiler.

Sure it is possible if I just use the translation key `foo.bar` but that way I can't set the variables as well as the different translation domain.

**Possible Solution**  
Allow to not automatically translate the placeholder value. Let us enter a normal string instead of always trying to translate it.

By the way, the rendered html as well as the translation are correct, just the warnings and missing messages in the profiler are annoying

**Comment by Havrin** [comment]
@xabbuh This is a good and valid workaround I didn't think of. Sure, you have to manually translate the label but I think for that special case it is enough of a solution.

**Comment by xabbuh** [comment]
One thing I forgot: The same applies for the `title` attribute if you use that.
