### ISSUE TITLE
Started dev webserver and "symfony-scripts event terminated with an exception"

### ISSUE THREAD

**Issue by checcoux** [symfony/symfony#29973]
**Symfony version(s) affected**: 3.4.18

**Description**  
I was working on the frontend of a project with the development webserver and suddenly the terminal closes; re-opened it and restarted the web server but didn't worked. Tryed a composer install as well as a cache:clear with no success.

**How to reproduce**
I don't know what appened because I was only doing html stuff. As I said earlier I've done a composer install (wich ended with this error) and also a cache:clear (same error)

 ```
[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:


  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passe
  d to Http\HttplugBundle\Discovery\ConfiguredClientsStrategy::__construct() must implement interface Http\
  Client\HttpClient or be null, instance of Http\HttplugBundle\Collector\ProfileClient given, called in /Us
  ers/checcoux/galileo/var/cache/dev/ContainerZ5c9hzh/appDevDebugProjectContainer.php on line 2739 in /User
  s/checcoux/galileo/vendor/php-http/httplug-bundle/Discovery/ConfiguredClientsStrategy.php:34
  Stack trace:
  #0 /Users/checcoux/galileo/var/cache/dev/ContainerZ5c9hzh/appDevDebugProjectContainer.php(2739): Http\Htt
  plugBundle\Discovery\ConfiguredClientsStrategy->__construct(Object(Http\HttplugBundle\Collector\ProfileCl
  ient), NULL)
  #1 /Users/checcoux/galileo/var/cache/dev/ContainerZ5c9hzh/appDevDebugProjectContainer.php(2556): Containe
  rZ5c9hzh\appDevDebugProjectContainer->getHttplug_StrategyService()
  #2 /Users/checcoux/galileo/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.p
  hp(229): Co in /Users/checcoux/galileo/vendor/php-http/httplug-bundle/Discovery/ConfiguredClientsStrategy
  .php on line 34
```

The crazy thing is that 5 minutes earlier everithing was working, I changed some html and pushed to production environment (the prod. env is working)

**Comment by xabbuh** [comment]
This rather looks like an issue in the HTTPlug bundle to me. Can you please report it [there](https://github.com/php-http/HttplugBundle) (and best include some steps that allow to reproduce it)?
