### ISSUE TITLE
Installing symfony/stopwatch overrides custom event dispatcher service definition

### ISSUE THREAD

**Issue by eblanshey** [symfony/symfony#29976]
**Symfony version(s) affected**: 4.2.2

**Description**  
Installing the Symfony Stopwatch component overwrites a custom-defined Event Dispatcher.

**How to reproduce**  
We have a custom event dispatcher that was working fine, and defined like so:

```php
    event_dispatcher:
        class: App\Domain\Common\Components\EventDispatcher\EventDispatcher
        public: true
    App\Domain\Common\Components\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'
```

Our EventDispatcherInterface extends `Symfony\Component\EventDispatcher\EventDispatcherInterface`.

After installing the stopwatch component, `./bin/console debug:container event_dispatcher` confirms that `event_dispatcher` no longer points to our implementation, but another one:

```
  Service ID       debug.event_dispatcher
  Class            Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher
  Tags             monolog.logger (channel: event)
```

If I remove the stopwatch component, our custom dispatcher is correctly registered:

```
  Service ID       event_dispatcher
  Class            App\Domain\Common\Components\EventDispatcher\EventDispatcher
  Tags             -
```

I am not sure where `Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher` is being registered, but it should not overwrite what we have defined in our `services.yaml` file.

**Comment by eblanshey** [comment]
Upon further investigation, I found a decorator in `symfony/framework-bundle/Resources/config/debug.xml` that decorates the `event_dispatcher`. But this doesn't work because it does not implement our custom interface.

I overcame this issue by overriding the debug.event_dispatcher alias like so:

```
    debug.event_dispatcher:
        alias: '@event_dispatcher'
```

I'm not sure this is the best fix as it seems like a workaround. I'll leave the issue open just in case this is something that should be fixed.

**Comment by xabbuh** [comment]
Using a service id that is used by Symfony itself for your application services is not the best idea as that is likely to cause conflicts. I'd rather use a prefix like `app.` for your custom services to avoid that risk.

**Comment by nicolas-grekas** [comment]
Closing as the behavior is correct.

**Comment by eblanshey** [comment]
@xabbuh is correct, the best way to change override symfony's service IDs is to use custom service aliases. For future reference, in the case of a custom event dispatcher, the following line can be added to your Kernel's `configureContainer` method:

```php
$container->addCompilerPass(new RegisterListenersPass('custom.event_dispatcher'));
```
