### ISSUE TITLE
Collection of forms and unique contraint issue

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony#29991]
**Symfony version(s) affected**: 4.2.2

**Description**  
The unique constraint validation does not work when the form collection entry type is mapped with an entity that have an unique constraint.

**How to reproduce**  

Parent entity:
```
/**
 * @ORM\Entity()
 */
class Family
{
    /**
     * Many Families has Many Attributes
     * 
     * @var ArrayCollection
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\FamilyAttribute", mappedBy="family", orphanRemoval=true, cascade={"persist"})
     * @Assert\Valid()
     */
    private $familyAttributes;
}
```

Child entity:
```
/**
 * THIS IS A JOIN TABLE WITH ADDITIONAL ATTRIBUTES
 *
 * @ORM\Entity()
 * @ORM\Table(uniqueConstraints={@UniqueConstraint(name="family_attribute_idx", columns={"family_id", "attribute_id"})})
 * @UniqueEntity({"family", "attribute"}, errorPath="attribute");
 */
class FamilyAttribute
{
    /**
     * @var Family
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Family", inversedBy="familyAttributes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $family;

    /**
     * @var Attribute
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Attribute", inversedBy="familyAttributes")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $attribute;
}
```

The form type:
```
        $builder
            ->add('familyAttributes', CollectionType::class, [
                'entry_type' => FamilyAttributeType::class,
                'allow_add' => true,
            ])
        ;
```

The issue occurs when I add two "FamilyAttribute" with the same {$family; $attribute} pair.

The UniqueConstraint validation does not work if the duplicate collection entries are not already persisted in the database.

**Possible Solution**  
No idea.

**Comment by xabbuh** [comment]
That's indeed true. But I don't think we can solve this with the built-in `UniqueEntity` validator. What you have to do is right your own constraint which works on top of the collection and additionally to the `UniqueEntity` constraint ensures that no entries inside your collection are duplicated.

**Comment by fabienlem** [comment]
Hello @xabbuh,

I have been able to create my own validator as you suggested. 👍 

I think it would be nice to improve the [UniqueEntity documentation](https://symfony.com/doc/current/reference/constraints/UniqueEntity.html) to point out this use case isn't covered. However, I'm not sure about the wording that could make it easilly understandable.

Thank you for your help!

Fabien

**Comment by vudaltsov** [comment]
@fabienlem , as far as I see, the problem is that `@UniqueEntity` checks whether such an entity already exists in the database, while you want to check uniqueness within a non-persisted collection, right?

**Comment by xabbuh** [comment]
@fabienlem Thank you for the feedback. Would you like to open a new issue in the [documentation repository](https://github.com/symfony/symfony-docs) if you think it can be improved a bit?

**Comment by fabienlem** [comment]
@vudaltsov you're totally right!

@xabbuh welcome! Ok I will suggest an improvement.
