### ISSUE TITLE
FormTypeInterface wrong doc-block on method getBlockPrefix

### ISSUE THREAD

**Issue by drososanastasios** [symfony/symfony#30018]
**Symfony version(s) affected**: 3.4 and later.

**Description**  
Based on the doc-block getBlockPrefix method of FormTypeInterface returns string. On the AbstractType on the other hand, the result of StringUtil::fqcnToBlockPrefix can also return null. We should change the interface doc-block to return null as well.

**Comment by xabbuh** [comment]
I think a better fix would be to return an empty string instead of `null`.

**Comment by yceruto** [comment]
https://github.com/symfony/symfony/blob/a3b45eb03407773ee9e19e00cf93b98c22d28a65/src/Symfony/Component/Form/AbstractType.php#L53-L56
That shouldn't happen whereas `get_class($this)` returns a valid FQCN, and it should always do it in this case, though I'm agree with @xabbuh.
