### ISSUE TITLE
UniqueEntity custom error message with toString on entity does not work

### ISSUE THREAD

**Issue by kemicofa** [symfony/symfony#30029]
**Symfony version(s) affected**: 4.2.*

**Description**  

According to Symfony [UniqueEntity documentation ](https://symfony.com/doc/current/reference/constraints/UniqueEntity.html#message) if the constraint is violated then I can create a custom message error by implementing the `__toString()` method on my Entity.

I've attempted to create my custom message via the `validation.yaml` (which **works**) and I've implemented the `__toString()` method (which does **not** work)

According to the docs:

> Messages can include the {{ value }} placeholder to display a string representation of the invalid entity. If the entity doesn't define the __toString() method, the following generic value will be used: "Object of class __CLASS__ identified by <comma separated IDs>"

**How to reproduce**  

To reproduce, clone my project and follow README.md guide:
https://github.com/kemicofa/unique_entity_custom_message_tostring_bug

Once, the project is installed run the WebCaseTest that I've implemented.

Essentially my project will attempt to insert two users with the same email in the database.
The first works as expected and the second fails as expected. However, the second response doesn't have the expected `__toString()` return message sent, only the default message is sent:

> Object(App\\Entity\\User).email: /** more text here */

**Possible Solution**  

**Additional context**

**Comment by dmaicher** [comment]
Possibly this is an issue in the documentation :confused: 

I checked the code and `{{ value }}` is replaced with the first invalid `value` which in your case is not the entity but the duplicate email address itself.

It can also happen that the invalid `value` is an entity instance but only if the Constraint is configured in a way so that it uses fields that are relations to other entities.

**Comment by dmaicher** [comment]
well that happens because of your `(string)` casting of the `ConstraintViolationList`. 

With this diff its just the first message

```diff
diff --git a/src/Controller/UserController.php b/src/Controller/UserController.php
index 27d5b1f..9fdc08f 100644
--- a/src/Controller/UserController.php
+++ b/src/Controller/UserController.php
@@ -23,7 +23,7 @@ class UserController
          $errors = $validator->validate($user);
 
          if(count($errors) > 0){
-             return new JsonResponse(["message" => (string) $errors], 400);
+             return new JsonResponse(["message" => $errors[0]->getMessage()], 400);
          }
 ```

```
There was 1 failure:

1) App\Tests\Controller\UserControllerTest::testRegister
Failed asserting that '{"message":"The following \u0022test@email.com\u0022 is already in use"}' contains "User custom message should appear".

/var/www/unique_entity_custom_message_tostring_bug/tests/Controller/UserControllerTest.php:32

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

**Comment by kemicofa** [comment]
@dmaicher thanks I appreciate the help.
