### ISSUE TITLE
[Security] AuthenticationException logged as info

### ISSUE THREAD

**Issue by gyszucs** [symfony/symfony#30022]
**Symfony version(s) affected**: 3.4+

**Description**  
In `UsernamePasswordJsonAuthenticationListener` if there is an `AuthenticationException`, it is logged as `info` instead of `error`. [See here](https://github.com/symfony/security-http/blob/3.4/Firewall/UsernamePasswordJsonAuthenticationListener.php#L169) I assume `error` should be the right level to be used here.

**How to reproduce**  
Try to throw an exception somewhere during `\Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface::authenticate` process. The easiest might be is not to have proper settings to your db layer, a db related exception should be thrown.

**Possible Solution**  
Let's log this exception as an error.

**Comment by linaori** [comment]
It's not an error in the code or flow, it's like a form validation error. This is only executed with an AuthenticationException. Why do you expect this to be logged as error?

**Comment by xabbuh** [comment]
I agree with @linaori here. `AuthenticationException` is meant to be thrown when a user cannot be authenticated because they did not provide the needed data. That's not an error from the perspective of the expected application behaviour.

**Comment by gyszucs** [comment]
Sorry, I was mistaken regarding the exception name. So what I wanted to use is `AuthenticationServiceException`. It is thrown in `DaoAuthenticationProvider` when an authentication request could not be processed due to a system problem. In my case it was a database related exception (connection could not be established) which definitely an error to me. I agree with what has been said about `AuthenticationException`.

**Comment by linaori** [comment]
The `DaoAuthenticationProvider` is as far as I know only used by the `form_login` variant. I think you'll have more control over any of this by using the Guard authenticator instead.

**Comment by xabbuh** [comment]
I agree with this reasoning. We should probably check which other exceptions we have that extend `AuthenticationException` but also indicate application errors.

**Comment by fabpot** [comment]
Closing as there is no more activity.
