### ISSUE TITLE
[PHPUnit]  SYMFONY_DEPRECATIONS_HELPER var is in the wrong place (.env.test)

### ISSUE THREAD

**Issue by proArtex** [symfony/symfony#30047]
**Symfony version(s) affected**:
* symfony/test-pack: 1.0.5
* symfony/phpunit-bridge: 4.2.2

**Description**  
[Phpunit recipe](https://github.com/symfony/recipes/tree/master/phpunit/phpunit/4.7) contains SYMFONY_DEPRECATIONS_HELPER env var inside .env.test file. But it doesn't work here.

**How to reproduce**  
* write a WebTestCase that triggers deprecation warning
* set ```SYMFONY_DEPRECATIONS_HELPER=weak``` inside .env.test (or .env.test.local)
* run ```rm -rf var/cache```
* run ```bin/phpunit```
Then you will see the "Remaining deprecation notices ..." message and exit code 1

**Possible Solution**  
Put SYMFONY_DEPRECATIONS_HELPER variable inside phpunit.xml.dist file
```<env name="SYMFONY_DEPRECATIONS_HELPER" value="weak" />```

**Comment by ossinkine** [comment]
[`DeprecationErrorHandler::getMode()`](https://github.com/symfony/symfony/blob/v4.2.2/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L48) is called first time when error `include(/app/.env.local.php): failed to open stream: No such file or directory` is thrown in [`bootstrap.php`](https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/symfony/framework-bundle/4.2/config/bootstrap.php#L9). Mode is set to 0 and cached. After that [`.env.test` is loaded](https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/symfony/framework-bundle/4.2/config/bootstrap.php#L16) but it does not affect the mode anymore.

@nicolas-grekas What is the best way to fix this?

**Comment by nicolas-grekas** [comment]
I think we should try fixing this in the bridge if possible, by not resolving the mode until a deprecation is actually triggered. Doable?

**Comment by ossinkine** [comment]
@nicolas-grekas Yes, I'll create a PR.
Which branch should be target for this fix?

**Comment by nicolas-grekas** [comment]
3.4!

**Comment by zacharra** [comment]
@ossinkine @nicolas-grekas Hello there, sorry for writing in this closed issue for which a fix exists, but I see that although we have a merged fix for this, which is referenced in the new 4.2.4 release notes, it did in fact not land in the 4.2 branch at all. The issue still exists with the PHPUnit-Bridge in v4.2.4 . It seems the merge from the 3.4 branch to the 4.2 one wasn't done correctly or something, though I'm not sure about this. I can see at least that the fix in the DeprecationErrorHandler.php file is in the master branch (though looking slightly different there), so I wasn't sure if I should open a new issue or not.
I tried to get opinions on that matter in your Developer's Slack, but unfortunately no one answered there^^.
