### ISSUE TITLE
knpbundle down : when can I find all the bundles ? 

### ISSUE THREAD

**Issue by zskiredj** [symfony/symfony#30049]
Hello,

http://www.knpbundles.com/ is down.

2 questions : does anyone know why ? Where can I find all the bundles grouped in a same website ?

thanks

**Comment by AlexandrePavy** [comment]
Hello @zskiredj,

You can check flex packages here https://flex.symfony.com/ (not all bundles, and sometimes sf 4+).

With `symfony-bundle` github tag : https://github.com/topics/symfony-bundle

Or on packagist with `symfony` or `bundle` https://packagist.org/?tags=symfony~bundle 

but yeah should be nice to have unified interface

**Comment by XuruDragon** [comment]
Hello, you could look at : https://packagist.org/
