### ISSUE TITLE
Why not to create a symfony framework updater software from command line

### ISSUE THREAD

**Issue by adigoun2005** [symfony/symfony#30054]
Hello to Fabien Potencier and to all the symfony team. I am working with sf since a couple of years now. And i have to say that the framework helped me to be very productive on several project.
One of my greatest issue with the framework is how hard it is to update an existing project to a major version i.e 2.8->3 or 2.8->4
And in my humble opinion one of the greatest issues with that is that the community bundles are most of the time not compatible with the latest versions of symfony.
Is it possible to make the latests versions of symfony compatible with all legacy bundle or to create a software with dynamically solves depreciation issues within each bundle?

**Comment by TomasVotruba** [comment]
@nicolas-grekas Thanks for spreading the word :+1: 

@adigoun2005 You're request and need is legit!

This is for you: [How to Upgrade Symfony 2.8 to 3.4](https://www.tomasvotruba.cz/blog/2019/02/28/how-to-upgrade-symfony-2-8-to-3-4/)
