### ISSUE TITLE
Remove unused env vars exception

### ISSUE THREAD

**Issue by Tony-Esales** [symfony/symfony#30059]
This behavior is causing problem in the KnpSnappyBundle. If I set false to any of the resources i got this annoying exception.

Ex:
```
knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    false
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
```

I don't want to use the image one, but it's not possible since I got the following exception:
Environment variables "WKHTMLTOIMAGE_PATH" are never used. Please, check your container's configuration.

I think it's better remove this exception than handle the problems it brings. 

It's the same asked in the following issue:
https://github.com/symfony/symfony/issues/23520

**Comment by fabpot** [comment]
The error cannot be removed in general. Here, the recipe should be improved instead to provide a default value for these env vars (an empty value for instance), and the code should check for an empty value and throw an exception there.
