### ISSUE TITLE
Silence symfony framework deprecation

### ISSUE THREAD

**Issue by vasilvestre** [symfony/symfony#30070]
**Description**  
Symfony Framework internal vendors deprecation are shown in logs, even you do not have to deal with them for many reasons :
- They are gone when you upgrade
- You do not have to modify them
Having that in mind, they are just polluting logs.

This issue is about silencing them in Symfony Apps and ONLY symfony apps. People using component still have to receive these deprecations.
They could be safely silenced (maybe not?) using @ silent operator ?

**Example**  
```php
User Deprecated: Passing a "Symfony\Component\Translation\MessageSelector" instance into 
the "Symfony\Component\Translation\Translator::__construct" as a second 
argument is deprecated since Symfony 3.4 and will be removed in 4.0.  
Inject a "Symfony\Component\Translation\Formatter\MessageFormatterInterface" implementation instead.
```

**Comment by xabbuh** [comment]
Can you create an example application that would run into this deprecation? I cannot see where this could happen.

**Comment by vasilvestre** [comment]
> Can you create an example application that would run into this deprecation? I cannot see where this could happen.

I will, but just any application being 2 or 3 minor version behind has these deprecated messages.

**Comment by xabbuh** [comment]
I don't see how that should happen as the service definition passes a message formatter: https://github.com/symfony/symfony/blob/3d19fd98378d4f12e7dcd478faaeb49a89c23193/src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.xml#L10-L22

**Comment by vasilvestre** [comment]
It's not related to translation but to all component, if you are late on version and that there's a deprecation you get warning in logs

**Comment by xabbuh** [comment]
I'd still be interested in a real example because if I understand you correctly, these will be cases where the core code would need to be fixed instead.

**Comment by xabbuh** [comment]
@vasilvestre Any chance for such an example?

**Comment by xabbuh** [comment]
I am closing here for now. We can reopen once we have a real example.

**Comment by vasilvestre** [comment]
I actually have no time, I will try later
