### ISSUE TITLE
Wrong deprecation message related to PHP templates

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30088]
**Symfony version(s) affected**: 4.2

**Description**  
When using PHP templates instead of Twig templates, you must store them in `src/Resources/views/`. However, if you do that, you see a deprecation message telling you to store them in `templates/`.

Is this OK or should the deprecation message only be displayed for Twig templates?

Originally reported by @nyroDev in https://twitter.com/Nyr0/status/1092901535179255808

**Comment by linaori** [comment]
The deprecation message seems correct to me. Why are PHP templates to be stored in that directory, can't this be configured? Looks like something to be fixed in the PHP template configuration rather than the deprecation.

**Comment by nyroDev** [comment]
According to the [doc](https://symfony.com/doc/master/templating/PHP.html) this is where PHP templates have to be stored.

thanks @javiereguiluz for creating the issue

**Comment by linaori** [comment]
There has been word on deprecating the template component if I remember correctly. Regardless, it sounds like the templating component should support this structure as well and have the docs updated accordingly.

**Comment by yceruto** [comment]
I'm taking a look at this...

**Comment by yceruto** [comment]
Okey, the deprecation warning is about Twig templates only, so if you have PHP templates in `src/Resources/views` no problem, it's already supported for PHP templates, so you can ignore that deprecation message until 5.0 where it is gone as well as the support to load Twig templates from `src/Resources/views` directory.

I'm updating the deprecation message to be more clear about this. https://github.com/symfony/symfony/pull/30952
