### ISSUE TITLE
Inflector pluralize not present ??

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#30092]
https://github.com/symfony/inflector `Inflector converts words between their singular and plural forms (English only). https://symfony.com/`

https://github.com/symfony/inflector/blob/eb5c654f16c0e18d3a332984dc0ce44b0d218813/Inflector.php

Doesn't contain method to pluralize. No documentation on how pluralize functionality is supposed to work. Package is available on packagist.org as stand-alone package.

**Comment by xabbuh** [comment]
The class currently does only return singular forms of a word. If you want to, you can submit a PR that tweaks the comment. But still keep in mind that this is an internal component on which you shouldn't rely in your own projects.

**Comment by flip111** [comment]
AFAIK it's not possible to submit PR's to change github repository titles.

**Comment by xabbuh** [comment]
I thought you were referring to the readme and the class docblocks.

**Comment by nicolas-grekas** [comment]
See #26890 !! ;)
