### ISSUE TITLE
AccessDeniedException is converted to HTTP 302 even when request format is JSON

### ISSUE THREAD

**Issue by Jontsa** [symfony/symfony#30099]
**Description**  

When accessing a secured area using AJAX + JSON while not logged in, the ExceptionListener in Symfony Security component may convert AccessDeniedException to a HTTP 302 redirect to login page. The javascript can not really do anything with this since it is expecting JSON or HTTP error code.

Any other exception would be converted to JSON and passed back to browser with correct HTTP status code. But in this case, you need to create your own event listener to convert this exception in to JSON. This is the same issue as reported here: https://stackoverflow.com/questions/33240554/symfony2-security-annotation-turn-off-redirect-when-not-logged-in

See: [Symfony\Component\Security\Http\Firewall\ExceptionListener::handleAccessDeniedException() ](https://github.com/symfony/security-http/blob/b564efb51c5355bd83e3aad231a0d87a307002ad/Firewall/ExceptionListener.php#L130)

**How to reproduce**

- Setup controller that throws AccessDeniedException
- Setup controller that mocks a login page
- Configure route to login page in security.yaml form_login > login_path
- Try to access the first controller using AJAX + JSON
- You expect a HTTP 403 error but instead you get HTTP 200 with login page contents

If needed, I can provide an example project in Github.

**Comment by xabbuh** [comment]
I think a small example project would indeed be very helpful for anyone wanting to look into it.

**Comment by Jontsa** [comment]
[Here](https://github.com/Jontsa/security-http-example) is a simple project where you have two end points for ajax. Both throw exception but AccessDeniedException does not trigger HTTP error.

- `git clone git@github.com:Jontsa/security-http-example.git`
- `cd security-http-example/`
- `composer install && bin/console server:start`

**Comment by nicolas-grekas** [comment]
@Jontsa would you be able to debug why?

**Comment by dimabory** [comment]
@nicolas-grekas Do you aware something about this [`return`](https://github.com/symfony/symfony/blob/ff1727e2ee44d966a64379e90c58b5c54dc87140/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L134) statement? Looks like this produces an issue not only with redirecting, but also with custom access deniend handler (see #28229).

**Comment by dimabory** [comment]
@Jontsa Btw, you can just make `form_login: false` to prevent redirection https://github.com/Jontsa/security-http-example/blob/afee744e4b46e54275bfeee24adf66630024efd2/config/packages/security.yaml#L13

**Comment by curry684** [comment]
I reviewed this and I don't think there's an actual issue here. The XHR request itself contains no usable indication that the redirect response is not valid, so Symfony is correct in following up with the redirect based on its configuration. And as @dimabory said you can/should just remove that config line which fixes your issue correctly.

The `return` statement may be a real issue but it has its own dedicated issue already.

Status: reviewed
