### ISSUE TITLE
Denormalizers should not instantiate empty objects for null values

### ISSUE THREAD

**Issue by tezvi** [symfony/symfony#30105]
**Description**  
When ObjectNormalizer denormalizes null value for a class property that is type hinted as object of specific class it should not instantiate new object instance of that class. Instead, it should use null value, unless configured differently by denormalization context.

**Example**  
Let's assume we have a json payload as follows:

```
{
    "property1": "testValue",
    "property2": null
}
```

... and for the sake of argument these two php classes:

```
<?php
class Foo
{
    /**
     * @var string
     */
    public $property1;

    /**
     * @var Bar
     */
    public $property2;
}

class Bar
{
    /**
     * @var int
     */
    public $id = 0;
}
```

By deserializing json payload I get the following:

```
$payload = '{"property1": "testValue","property2": null}';
$data    = $this->serializer->deserialize($payload, Foo::class, 'json');
print_r($data);
```

Result:
```
\Foo Object
(
    [property1] => testValue
    [property2] => \Bar Object
        (
            [id] => 0
        )
)
```

Note that property2 has been deserialized as an empty object of class \Bar. Perhaps I'm mistaken but this was not asked from denormalizer explicitly.
I suppose this might be resolved by introducing \Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::SKIP_NULL_VALUES in the similar way as already implemented in normalizer updateData method.
https://github.com/symfony/symfony/blob/a6a1be803d7e757cbfdf43b7d819e4c8a9d4e7d9/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L434-L436

An idea that currently sounds feasible to me is to null check value in \Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::validateAndDenormalize for Type::BUILTIN_TYPE_NULL and make sure the skip_null_values denormalization value is true.

If you think this might be an acceptable solution let me know about potential PR.

Using symfony/serializer 4.2.2.
Sorry for long text :)

**Comment by ro0NL** [comment]
does it work with `@var Bar|null`? (just curious :))

**Comment by tezvi** [comment]
Yup, it does :)

However, I have intentionally posted code without setters and getters. It does not work for this example (notice ? type hint).

```
class Foo
{
    /**
     * @var string
     */
    public $property1;

    private $property2;

    /**
     * @return Bar
     */
    public function getProperty2(): ?Bar
    {
        return $this->property2;
    }

    /**
     * @param Bar $property2
     * @return void
     */
    public function setProperty2(?Bar $property2): void
    {
        $this->property2 = $property2;
    }
}
```

I guess I should dig into PropertyInfo extractors.

These lines have missed me, but the check is already there.
https://github.com/symfony/symfony/blob/a6a1be803d7e757cbfdf43b7d819e4c8a9d4e7d9/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L321-L323

**Comment by ro0NL** [comment]
does it work with `@param Bar|null $property2`? :stuck_out_tongue:

**Comment by tezvi** [comment]
A bit sneaky trick but it works :)

**Comment by tezvi** [comment]
Still, skip_null_values seems a reasonable configuration. At least as a possibility.

**Comment by ro0NL** [comment]
So the current behavior is correct, isnt it? If you submit null your contracts should allow it as such (and really `@param`, if declared, should be in sync with the actual type declaration).

Otherwise serializer tries to fulfill it, which it can as there are no required constructor arguments (assuming it would crash otherwise). Sounds legit :)

From the docs (https://symfony.com/doc/current/components/serializer.html#skipping-null-values) im not really sure how it's expected to behave when denormalizing, but i guess it disables this behavior.

**Comment by tezvi** [comment]
Thanks for your input. You're right. The thing that concerns me here is that phpdoc has a higher priority than PHP syntax in determining this behaviour. a bit inconsistent IMHO, but that's just me :)
Skipping null values option would completely ignore null values and as you said that is not really the source of problem here.

**Comment by ro0NL** [comment]
> phpdoc has a higher priority than PHP syntax

It's legit. It can either enhance a PHP type:

https://github.com/symfony/symfony/blob/7f3f75d85d6a63b8561d7ce44244b82e9fe63b9c/src/Symfony/Bundle/FrameworkBundle/Command/CachePoolPruneCommand.php#L32-L34

or document new API, whereas runtime allows both old+new API:

https://github.com/symfony/symfony/blob/8f29f56d67d4368e87e40953d37bf619236efc19/src/Symfony/Bundle/FrameworkBundle/Command/EventDispatcherDebugCommand.php#L35-L39
