### ISSUE TITLE
[Messenger] Better error messages when transport is not supported

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30118]
**Description**  
As reported in https://github.com/symfony/symfony-docs/pull/10755 when you configure an `amqp` transport but AMQP is not installed in your app, you see an error message.

We could improve the following code to introduce a check for the AMQP class and throw an error if it's not installed (with the usual *"Try running "composer require ..."* that we use in many other parts of the framework):

https://github.com/symfony/symfony/blob/5ed68eec7ea4d308970b8fd0742ea22cd12ca074/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1082

**Comment by Guikingone** [comment]
Maybe checking the given transport for a specific dsn could be even better? 

In this specific case, `amqp` is used but what about `redis`? 

I know that in this case, it could be a good idea to use EnqueueBundle but I think that using the `messenger-adapter` library, it could be a good idea to check if this library is installed and if not, noticing or throwing an error about installing it?

**Comment by sroze** [comment]
It's been fixed recently 🙌
