### ISSUE TITLE
[WDT][DX] Add timestamp to XHRs panel

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#30121]
### The problem
A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/1227834/52500366-6d9a4080-2ba3-11e9-9cfc-d545ed2cbc05.png)

Who can tell me which request is the newest one? ;)

### Solution
What about a column which shows a timestamp (`HH:MM:SS`) of the request? This should be pretty simple to add.

**Comment by yceruto** [comment]
Another solution could be display the request number.

**Comment by SatanGG** [comment]
This is an issue for me as well. Especially when I need to repeat test requests.

**Comment by byhaskell** [comment]
Now the last request - the last (bottom). Earlier in 3.4 it was the opposite. Confusion on the whole not, the order is saved.

**Comment by javiereguiluz** [comment]
I agree with @yceruto: displaying an auto-increment integer for the request number would be the most easy to understand solution to this problem.

**Comment by javiereguiluz** [comment]
Closing as fixed by #30130.
