### ISSUE TITLE
How to configure Symfony4 bundles based odm.

### ISSUE THREAD

**Issue by wajaja** [symfony/symfony#30127]
Hi!;
I've an issue when i upgrade my symfony3 app to symfony4 especialy on  odm configuration; 

that my doctrine_mongo.yaml:

`doctrine_mongodb:`
        `auto_generate_proxy_classes: true`
        `auto_generate_hydrator_classes: true`
        `connections:`
             `default:`
                `server: '%env(resolve:MONGODB_URL)%'`
                `options: {}`
                 `default_database: '%env(resolve:MONGODB_DB)%'`
        `document_managers:`
             `default:`
                `auto_mapping: true`
                 `mappings:`
                       `AppUserBundle:`
                       `is_bundle: true`
                       ` type: annotation`
                        `alias: User`

I get this message: 
`Could not find the manager name parameter in the container. Tried the follo  wing parameter names: "doctrine.default_entity_manager"`

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by xabbuh** [comment]
Though if you still think there is a misbehaviour that you encounter, I suggest to open a new issue in the [DoctrineMongoDBBundle repository](https://github.com/doctrine/DoctrineMongoDBBundle) as that one is maintained by a different team.
