### ISSUE TITLE
AbstractComparisonValidator gives TypeError with type hinted getter

### ISSUE THREAD

**Issue by nick-zh** [symfony/symfony#30133]
**Symfony version(s) affected**: symfony/valdiator 4.2.3

**Description**  
I am using the constraint Symfony\Component\Validator\Constraints\GreaterThanOrEqual
My getters have typehinted return values. So if i validate a string (expected to be int) i get a type error.
This is happening because the Symfony\Component\Validator\Constraints\AbstractComparisonValidator uses the PropertyAccessor (which calls the getter) unlike e.g. the RecursiveContextualValidator
which uses
```
$propertyValue = $propertyMetadata->getPropertyValue($object);
```

I haven't found a good solution besides changing my code or implementing an own property accessor.
Maybe i have overlooked something, but i think this should still work without custom additions.

EDIT: The constructcor of the AbstractComparisonValidator now uses the concrete class in the constructor, i think this should at least be:
```
public function __construct(PropertyAccessorInterface $propertyAccessor = null)
{
    $this->propertyAccessor = $propertyAccessor;
}
```

**Comment by xabbuh** [comment]
I could imagine that we could find a solution to get the value without calling the getter. But I am not convinced that this really is a good fix. In your case this will then mean that the following comparison is done with a value that may not be comparable at all. My guess is that you are better off by trying to perform the comparison only if the value to compare with is actually of the expected type (but I may be missing some important details of your use case). What do you think?

**Comment by nick-zh** [comment]
@xabbuh thanks for getting back to me on this. My actual use case is this:
I use the symfony validator, i do have two fields that i want to compare with the GreaterThanOrEqual constraint. I also have constraints to ensure the type of the fields (int), but since all constraints are evaluated, i never get the Type validation error, but rather the TypeError from GreaterThanOrEqual.
I do agree though that by fixing this, it might end up in values that aren't comparable, which of course is also not favorable.
I personally can live with how it is right now, since with #30136 i can now use my own PropertyAccessor.

**Comment by xabbuh** [comment]
Thank you for explaining me your use case. If I understand you correctly, this is a perfect example for using [group sequences](https://symfony.com/doc/current/validation/sequence_provider.html). So you would first check all the needed types and only if these checks succeed, the comparison validator will be executed.

**Comment by nick-zh** [comment]
@xabbuh thank you very much, i didn't know about that. I am closing this, i think the adjustment and group sequences covers this quite nicely.
