### ISSUE TITLE
PHPUnit test freezes when testing ChoiceCommand with multiSelect enabled

### ISSUE THREAD

**Issue by dugajean** [symfony/symfony#30138]
**Symfony version(s) affected**: Console 4.2.3

**Description**  
**This is a standalone Symfony Console project**. I have one simple test, to test a command that requires input. I use the `setInputs` method in the test on `$commandTester` and input 6 answers there for the 6 questions that will be asked. However, the test hangs at the `ChoiceQuestion` with multiSelect enabled (`$question->setMultiselect(true);`), causing PHP to use a lot of processing power (CPU usage) and the Terminal ends up using a lot of RAM.

**How to reproduce**  
Make a simple test like this one:

```
<?php

namespace Dockr\Tests\Command;

use MyApp\Commands\MyCoolCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class MyCoolCommandTest extends TestCase
{
    public function testExecute()
    {
        $application = new Application();
        $application->add(new MyCoolCommand);

        $command = $application->find('do_cool_stuff');

        $commandTester = new CommandTester($command);
        $commandTester->setInputs(['This', 'This', 'This', 'This', 'This', 'This']);
        $commandTester->execute(['command' => $command->getName()]);
    }
}
```

And make sure that there is one multiSelect question (`$question->setMultiselect(true);`). The question should hang at the `$questionHelper->ask($input, $output, $question)` call.

**Please note:** This command works perfectly fine when running the command manually, only fails when running it via a test like above.

**Comment by chalasr** [comment]
I confirm it hangs when *no input is given to the question* (that is a bug). 
However, it works as expected if you set the proper inputs.
Can you show the tested command ? Note that, as in a regular cli context, a multi-select input must be only one string with coma-separated values, i.e:

```
// command
$question = new ChoiceQuestion('Choice', ['a', 'b', 'c']);
$questionHelper->ask($input, $output, $question);

// test
$tester->setInputs('a, b');
```

And if your command asks multiple questions, an input string must be set for all of them (using an empty string for simulating `enter`).
I'm looking at fixing the issue when one or more inputs are missing.

**Comment by dugajean** [comment]
Good! Thank you!

Well, I provided wrong input - input that wasn't part of the `$choices`. That resulted in a hang as well.

Yes, I'm aware that you need to provide an answer for each question. Above you can see 6 answers (`This` x 6) for my 6 questions in the command. I will provide the command later today.

**Comment by chalasr** [comment]
Providing a wrong input to a choice question leads to the question being asked again, except if the question has no validator or if `$question->setMaxAttempts(1)` has been called, hence it behaves as a missing input (since no input is set for the second attempt). 
Still, tests should never hang. #30271 fixes it, would be nice to have your confirmation.

**Comment by dugajean** [comment]
@chalasr The test passes now. Thanks a lot!
