### ISSUE TITLE
Regex of UrlMatcher broken or my failure?

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/symfony#30147]
**Symfony version(s) affected**: x.y.z

**Description**  
When i run our tests on [symfony-cmf/routing](https://travis-ci.org/symfony-cmf/Routing/jobs/492021479) i  got the following issue:
```
3) Symfony\Cmf\Component\Routing\Tests\Unit\NestedMatcher\UrlMatcherTest::testMatchNoRouteObject
preg_match(): No ending delimiter '/' found
/home/travis/build/symfony-cmf/Routing/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php:155
/home/travis/build/symfony-cmf/Routing/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php:87
/home/travis/build/symfony-cmf/Routing/src/NestedMatcher/UrlMatcher.php:42
/home/travis/build/symfony-cmf/Routing/tests/Unit/NestedMatcher/UrlMatcherTest.php:145
```
When i debug into the code i see that our regex comming from the route `#\/foo\/bar#` is replaced through the follwoing `str_replace()` by a mechanism i do not understand `$pos (int) - $hasTrailingSash(bool)` to `/?$\/foo\/bar`

**How to reproduce**  
The easiest way would be to run the tests of that branch: 

https://github.com/symfony-cmf/Routing/blob/master/tests/Unit/NestedMatcher/UrlMatcherTest.php#L143

and follow from that line. That branch simply prepares a stricter php handling and opens for tests with SF 4.2. Otherwise i would try to reproduce it in an other way.

**Comment by nicolas-grekas** [comment]
Could you please submit a failing test case on `UrlMatcherTest` on the lowest branch where you can reproduce this? That should help (me) work on this. Thanks!

**Comment by ElectricMaxxx** [comment]
No worries, when pushing a test i would also provide a fix, i just need to know if it our fault. But .. yes, the best way is to write a test. I'll try it tonight.

**Comment by ElectricMaxxx** [comment]
While running Debugger on Routing tests i found that the compiled route in original got regexes like `#^/ ... /$#sD` which are fine. We mock the compiled route at all, which is an other issue (@dbu ping), cause for me the look like value objects. And a quick fix in our mocking: https://github.com/symfony-cmf/Routing/pull/232/commits/8b449f81e65227f48226a629149291fe2e55e0a3 fixed our tests. But at the end it means a regex like `#/ .../#` breaks in UrlMatcher, a regex with `#^/ ... /$#sD` does not. 
But i found no point where you also control that `CompiledRoute` from within a test. So my question is: is the Creation of the Class in the hand of the user (developer)? Is it done through the magic `compile_class` parameter i see first time today?

**Comment by nicolas-grekas** [comment]
The format of the compiled regexp is quite strict, supporting more fancy formats could be a lot of work for little benefit. As long as the proper format is generated, you can define it on your own. But here, mocks where wrong for sure. Closing then, thanks for the details.
