### ISSUE TITLE
[Serializer][RFC] Provide DateTimeZoneNormalizer

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#30145]
**Description**  
The Symfony Serializer contains support for `DateTimeInterface` objects which some projects rely on (e.g. API Platform - https://github.com/api-platform/core/issues/2509). However object being very close to the `DateTime` - `DateTimeZone` does not provide any serialization options out of the box.

**RFC**
If there was a reason to provide normalization for `DateTime` why not include `DateTimeZone` which is also a part of the `DateTime`?

**Comment by jewome62** [comment]
I take this #EUFOSSA
