### ISSUE TITLE
Critical PHP Encoding Error from JSON Response creation

### ISSUE THREAD

**Issue by SpiGAndromeda** [symfony/symfony#30146]
**Symfony version(s) affected**: v3.4.21

**Description**  
I am creating a JSON response to show a table in frontend by drawing the data via AJAX. The following DB field causes an error:
```
2mm & 3mm V2A; Rechnungsadresse: Maximilian Stanglmayr
Technische Universität Dresden
Institut für Automobiltechnik Dresden - IAD
Lehrstuhl Kraftfahrzeugtechnik
George-Baehr-Straße 1c
01069 Dresden
```
Enoding this into a the JSON response leads to a 
```
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /mnt/web302/d1/08/58522508/htdocs/spezle_app/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/JsonResponse.php line 168 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /mnt/web302/d1/08/58522508/htdocs/spezle_app/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/JsonResponse.php:168)"} []
```
So the error comes from the setData function:
```
/**
 * Sets the data to be sent as JSON.
 *
 * @param mixed $data
 *
 * @return $this
 *
 * @throws \InvalidArgumentException
 */
public function setData($data = array())
{
    if (\defined('HHVM_VERSION')) {
        // HHVM does not trigger any warnings and let exceptions
        // thrown from a JsonSerializable object pass through.
        // If only PHP did the same...
        $data = json_encode($data, $this->encodingOptions);
    } else {
        if (!interface_exists('JsonSerializable', false)) {
            set_error_handler(function () { return false; });
            try {
                $data = @json_encode($data, $this->encodingOptions);
            } finally {
                restore_error_handler();
            }
        } else {
            try {
                $data = json_encode($data, $this->encodingOptions);
            } catch (\Exception $e) {
                if ('Exception' === \get_class($e) && 0 === strpos($e->getMessage(), 'Failed calling ')) {
                    throw $e->getPrevious() ?: $e;
                }
                throw $e;
            }
        }
    }

    if (JSON_ERROR_NONE !== json_last_error()) {
        throw new \InvalidArgumentException(json_last_error_msg());
    }

    return $this->setJson($data);
}
```

The word which seems to cause the problems is "für" in the third line. But it's not the word itself. I could resolve this issue by adding a space infront of the word. It's also causing no problems in other fields or rows or even at a different position. Also "fuer" at that same position doesn't cause any problems.

**How to reproduce**  
The composer.lock file is attatched. [composer.lock.txt](https://github.com/symfony/symfony/files/2853451/composer.lock.txt)
PHP Version is 7.2
MySQL Version is 5.6.42

The table structure is attatched as a phpMyAdmin print. 
[DB3069299 : assignment | STRATO phpMyAdmin 4.8.5.pdf](https://github.com/symfony/symfony/files/2853425/DB3069299.assignment.STRATO.phpMyAdmin.4.8.5.pdf)

The text is located in the `comment` column.

The error doesn't occur with "fur" at the very same position but it also occurs with "för". So I guess its a combination of the umlaut and the specific position or surrounding chars.

**Possible Solution**  
As said: adding one space before "für" was enogh to solve the problem. I am nevertheless interested in how this could happen. Especially because the error seems to so overwhelming specific and strange to me.

**Comment by xabbuh** [comment]
Are you sure that your data is really UTF-8 encoded? Maybe it isn't but editing the data has it automatically being converted to UTF-8 by your browser/editor?

**Comment by SpiGAndromeda** [comment]
@xabbuh yes I am sure. I changed the value manually in the database by use phpMyAdmin. Changing it back to the trouble causing content reproduced the error.

**Comment by xabbuh** [comment]
Can you extract a test case that does include the string that causes this error without the need to set up a database. Otherwise it may be hard to reproduce the issue.

**Comment by SpiGAndromeda** [comment]
@xabbuh you mean setup an minimal application with hard coded test strings?

**Comment by nicolas-grekas** [comment]
I would trust the error message personally...
`preg_match('//u', $string)` is another way to check for utf8 correctness of you want to double check that.

**Comment by xabbuh** [comment]
I am closing here for now. We can reopen once we are able to reproduce though. Thank you for understanding.
