### ISSUE TITLE
ErrorHandler preserve our error handler

### ISSUE THREAD

**Issue by ondrab1** [symfony/symfony#30140]
**Symfony version(s) affected**: 3.4.22

**Description**  

We are temporary overwriting error handler to mute notices, warnings by our custom error handler for a while we need it. By the change in that commit it was killed, because our custom error handler is being overwritten in this place: https://github.com/symfony/symfony/blob/33145dae6242f23951fa2c3a18fa8c5f673ca3b6/src/Symfony/Component/Debug/ErrorHandler.php#L503

**How to reproduce**  

Revert commit b979fff6b8c3f2bff4faa46798e1c1dd5270b229

**Comment by nicolas-grekas** [comment]
ping @fancyweb

**Comment by fancyweb** [comment]
@ondrab1 Do you mean you are setting another error handler in your logger and then you don't restore it ?

**Comment by ondrab1** [comment]
@fancyweb there is full description of our problem: We need to temporarily override Symfony handler to avoid getting error reports on undefined varibles during templates rendering. We use Smarty templates. Now our temporary error handler get discarded on first symfony warning. Smarty error handler ignores all errors in Smarty code but passes all other errors to previous error handler (Symfony). On first non-Smarty error the Smarty error handler get discarded and next error in Smarty template get caught by Symfony.

**Comment by fancyweb** [comment]
Hmm yes there is a BC break for this particular case. Smarty manually calls the previous error handler (https://github.com/smarty-php/smarty/blob/v3.1.33/libs/sysplugins/smarty_internal_errorhandler.php#L100).

**Comment by fancyweb** [comment]
The `handleError` method is marked as `@internal`. It is not supposed to be called directly. However, Smarty cannot know about this. For the reasons I have listed in my original PR, it is impossible to know the current error handler in the `Debug` error handler itself so I don't see how we can handle both cases. Waiting for @nicolas-grekas opinion on my side.

**Comment by cuchac** [comment]
Hi,
if I understand the original issue correctly, there was problem with losing Symfony errorHandler for example in logger classes. It seems to me the problem should be solved in loggers, because code should always "clean-up" error handler to previous state.
If it is not possible to fix in Loggers (it is error in PHP if there is no such issue in HHVM), let's work around it by restoring error handler to the active error handler before calling loggers.
There are many examples of calls like `$handler = set_error_handler('var_dump');` to store current errorHandler and restore it afterwards.

**Comment by cuchac** [comment]
Following change can fix this issue https://github.com/symfony/symfony/commit/130d6f0717c54d9d6e84c3161cb2b0c7dc70765e

**Comment by fancyweb** [comment]
@ondrab1 Can you please apply this patch (https://github.com/symfony/symfony/commit/a8b34348e714395bf15c88299adae1779253bb67.patch) and confirm that it fixes the problem ? On my side, I confirm that the "logger problem" is still fixed with it.

**Comment by ondrab1** [comment]
@fancyweb Yep, it fixes the problem.
