### ISSUE TITLE
[Validator] Add the missing translations for the Danish ("da") locale

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30155]
If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken. Thanks!

-----

**Symfony version(s) affected**: 3.4

**Description**

The `src/Symfony/Component/Validator/Resources/translations/validators.da.xlf` file is missing the following translations compared to the original English file:

```xml
<trans-unit id="64">
    <source>This value is not a valid currency.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="65">
    <source>This value should be equal to {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="66">
    <source>This value should be greater than {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="67">
    <source>This value should be greater than or equal to {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="68">
    <source>This value should be identical to {{ compared_value_type }} {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="69">
    <source>This value should be less than {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="70">
    <source>This value should be less than or equal to {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="71">
    <source>This value should not be equal to {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="72">
    <source>This value should not be identical to {{ compared_value_type }} {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="73">
    <source>The image ratio is too big ({{ ratio }}). Allowed maximum ratio is {{ max_ratio }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="74">
    <source>The image ratio is too small ({{ ratio }}). Minimum ratio expected is {{ min_ratio }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="75">
    <source>The image is square ({{ width }}x{{ height }}px). Square images are not allowed.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="76">
    <source>The image is landscape oriented ({{ width }}x{{ height }}px). Landscape oriented images are not allowed.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="77">
    <source>The image is portrait oriented ({{ width }}x{{ height }}px). Portrait oriented images are not allowed.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="78">
    <source>An empty file is not allowed.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="79">
    <source>The host could not be resolved.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="80">
    <source>This value does not match the expected {{ charset }} charset.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="81">
    <source>This is not a valid Business Identifier Code (BIC).</source>
    <target>...</target>
</trans-unit>
<trans-unit id="83">
    <source>This is not a valid UUID.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="84">
    <source>This value should be a multiple of {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="85">
    <source>This Business Identifier Code (BIC) is not associated with IBAN {{ iban }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="86">
    <source>This value should be valid JSON.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="87">
    <source>This collection should contain only unique elements.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="88">
    <source>This value should be positive.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="89">
    <source>This value should be either positive or zero.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="90">
    <source>This value should be negative.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="91">
    <source>This value should be either negative or zero.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="92">
    <source>This value is not a valid timezone.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="93">
    <source>This password has been leaked in a data breach, it must not be used. Please use another password.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="94">
    <source>This value should be between {{ min }} and {{ max }}.</source>
    <target>...</target>
</trans-unit>
```

**Possible Solution**

A Pull Request must be sent to Symfony's 3.4 branch adding the missing translations.

Don't forget to take a quick look at the existing translations to use the same tone and style in the new translations.

**Additional context**

You have two ways to make this contribution:

**1)** Use the GitHub web interface to edit the translation and make the pull request.

  * It's recommended if you don't have any experience using Git in the terminal.
  * To do so, [click here](https://github.com/symfony/symfony/edit/3.4/src/Symfony/Component/Validator/Resources/translations/validators.da.xlf) to edit the translation file and follow the given steps to create the pull request.

**2)** Use your own editor to edit the translation file and use the Git commands in the terminal to make the pull request.

  * It's the most common way to contribute to Symfony.
  * You need to download Symfony's code to your computer and follow the steps explained [in this contribution guide](https://symfony.com/doc/current/contributing/code/patches.html)

-----

If you need any help during the contribution process, visit the `#contribs` channel on [Symfony Slack](https://symfony.com/slack) where we'll be happy to help you.

**Comment by mauran** [comment]
I would like to work on this :)

**Comment by mauran** [comment]
Seems like this issue is already done and needs to be closed if I'm right. :)

**Comment by javiereguiluz** [comment]
I'm reopening this because this is not fixed yet.

@mauran that Danish translation file exists (see https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.da.xlf) but it doesn't contain yet the translations listed in this issue. The work to do is to add only these missing translations to the existing file. Thanks for offering yourself to do it!

**Comment by javiereguiluz** [comment]
Sorry for the confusion ... these strings were indeed translated in #31499 .... but they were merged in the wrong file. They should go to Validator component, not Form component 🤔

**Comment by mauran** [comment]
Ohh 😅 - So should i just move them to their correct place to be?

**Comment by xabbuh** [comment]
@mauran Would you like to give it a try?

**Comment by mauran** [comment]
@xabbuh Yeah! But i'm still unsure if i just need to move the translation-files or not. :)

**Comment by xabbuh** [comment]
@mauran We do not need to move the files. The content that was present before can stay there. We only need to move the entries added in #31499.

**Comment by xabbuh** [comment]
see #33085
