### ISSUE TITLE
[Validator] Add the missing translations for the Dutch ("nl") locale

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30177]
**IMPORTANT**: this issue is reserved for new contributors, because we want to give the opportunity to people who want to contribute to Symfony but never found the right issue to do that.

If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken. Thanks!

-----

**Symfony version(s) affected**: 3.4

**Description**

The `src/Symfony/Component/Validator/Resources/translations/validators.nl.xlf` file is missing the following translations compared to the original English file:

```xml
<trans-unit id="79">
    <source>The host could not be resolved.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="84">
    <source>This value should be a multiple of {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="85">
    <source>This Business Identifier Code (BIC) is not associated with IBAN {{ iban }}.</source>
    <target>...</target>
</trans-unit>

```

**Possible Solution**

A Pull Request must be sent to Symfony's 3.4 branch adding the missing translations.

Don't forget to take a quick look at the existing translations to use the same tone and style in the new translations.

**Additional context**

You have two ways to make this contribution:

**1)** Use the GitHub web interface to edit the translation and make the pull request.

  * It's recommended if you don't have any experience using Git in the terminal.
  * To do so, [click here](https://github.com/symfony/symfony/edit/3.4/src/Symfony/Component/Validator/Resources/translations/validators.nl.xlf) to edit the translation file and follow the given steps to create the pull request.

**2)** Use your own editor to edit the translation file and use the Git commands in the terminal to make the pull request.

  * It's the most common way to contribute to Symfony.
  * You need to download Symfony's code to your computer and follow the steps explained [in this contribution guide](https://symfony.com/doc/current/contributing/code/patches.html)

-----

If you need any help during the contribution process, visit the `#contribs` channel on [Symfony Slack](https://symfony.com/slack) where we'll be happy to help you.

**Comment by reyostallenberg** [comment]
I like to pick this one

**Comment by curry684** [comment]
@javiereguiluz any idea how number 84 went missing? I suggested it [in the original PR](https://github.com/symfony/symfony/pull/28069#issuecomment-412506777) and it [was merged like that](https://github.com/symfony/symfony/pull/28069/files#diff-f3454c7ac1f23445fa184088ba6e1d2eR321). So I'm pretty surprised it got lost along the way as it was most recently missing before this issue today...?

**Comment by curry684** [comment]
Hang on I see, the feature went into `master` and this PR is targetting 3.4, why are we backporting translations to versions that don't contain their usage?

**Comment by javiereguiluz** [comment]
@curry684 yes, to make things easier to maintain, it's been decided to include all translations in the lowest maintained branch ... even if those are not used in that branch. Thanks.

**Comment by curry684** [comment]
Ah ok, wasn't aware of that, thanks for clarifying  👍
