### ISSUE TITLE
Wrong parameters at AbstractSessionHandler - destroy - setcookie 

### ISSUE THREAD

**Issue by moon-deer** [symfony/symfony#30211]
**Symfony version(s) affected**: 4.2.3

**Description**  
User authentication causing this error:
`request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: setcookie() expects parameter 3 to be int, array given" at /.../vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php line 133 {"exception":"[object] (ErrorException(code: 0): Warning: setcookie() expects parameter 3 to be int, array given at /.../vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php:133)"} []`

**How to reproduce**  
I'm following the docs (4.2 version of course) and wanted to create super simple skeleton with simple login/registration functionality. I did not implement any _experimental code_ and was just following the docs.

So for example. I've run the
`bin/console make:registration-form`
and chose the _yes_ for "Do you want to automatically authenticate the user after registration?" 
In the generated controller at the bottom of the _register_ action we have the
 `return $guardHandler->authenticateUserAndHandleSuccess(...)`
When this method is working, at some point, I believe, there is somewhere in the stack a call of the _destroy_ method in the _AbstractSessionHandler.php_ which is causing the error.

I can see exactly same error when I'm trying to proceed with login (providing correct credentials).

If we will look into the [AbstractSessionHandler.php](https://github.com/symfony/symfony/blob/b9b8f9da98ceb4438e12a0e60023a0af54f48d97/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php#L133)

we can see the issue:

```php
//this obviously returns an array
$params = session_get_cookie_params();
unset($params['lifetime']);
// and here we are passing this array to the setcookie in the 3rd parameter
// which is of course causing the error
setcookie($this->sessionName, '', $params);
```

**Additional context**  
I'm not sure if this can help, but additionally to generating login/registration forms I (following the [docs](https://symfony.com/doc/current/doctrine/pdo_session_storage.html)) configured my session to be stored in the db.
And session indeed successfully stored in the db, there's no issues with that.

P.S. Let me know if you need any other details.
But it looks to me that issue is pretty obvious when you just look on the code above.

P.S.2. I can see that this issue is present since [v4.2.0-BETA1](https://github.com/symfony/symfony/blob/v4.2.0-BETA1/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php)
In the [v4.1.11](https://github.com/symfony/symfony/blob/v4.1.11/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/AbstractSessionHandler.php)
that par of destroy method is fine

**Comment by nicolas-grekas** [comment]
That line 133 runs only on PHP 7.3, and on PHP 7.3, `setcookie()` accepts an array as 3rd argument.
Which means I don't get how this can happen. Can you try debugging further and check what is wrong here?

**Comment by moon-deer** [comment]
Yeah, I'm embarrassed.
Of course it's about the PHP version.

To someone else who could fool himself with such issue:
I was using docker and I was using the PHP(-FPM) 7.3.0-dev image, which was not updated for some time. Once I've upgraded to the latest stable 7.3.2 version, everything is working as expected.

**Comment by nicolas-grekas** [comment]
Great, thanks for the feedback.
