### ISSUE TITLE
[Cache] FilesystemAdapter cache uses different pool ids between console commands and executed via PHP-FPM

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#30226]
**Symfony version(s) affected**: At least 4.2.3

**Description**  
Using the `FilesystemAdapter` from a Symfony CLI command will write the cache to a different pool than doing so via PHP-FPM/your browser

**How to reproduce**  
Reproducer code: https://github.com/keichinger/symfony-filesystem-cache-issue

1. After installing the project as usual (`git clone`, `composer install`, local webserver configs if necessary, etc.)
2. Run `php bin/console cache:clear --env="dev"`
3. Open the file `vendor/symfony/cache/Traits/FilesystemCommonTrait.php` and add some debug code, which will come in handy while investigating this issue:

```php
    private function write($file, $data, $expiresAt = null)
    {
        // ===============
        // ADDED DEBUG CODE
        dump("writing cache file: " . $file);
        // END OF ADDED DEBUG CODE
        // ===============

        set_error_handler(__CLASS__.'::throwError');
        try {
            if (null === $this->tmp) {
                $this->tmp = $this->directory.uniqid('', true);
            }
            file_put_contents($this->tmp, $data);

            if (null !== $expiresAt) {
                touch($this->tmp, $expiresAt);
            }

            return rename($this->tmp, $file);
        } finally {
            restore_error_handler();
        }
    }

    private function getFile($id, $mkdir = false)
    {
        // Use MD5 to favor speed over security, which is not an issue here
        $hash = str_replace('/', '-', base64_encode(hash('md5', static::class.$id, true)));
        $dir = $this->directory.strtoupper($hash[0].\DIRECTORY_SEPARATOR.$hash[1].\DIRECTORY_SEPARATOR);

        if ($mkdir && !file_exists($dir)) {
            @mkdir($dir, 0777, true);
        }

        // ===============
        // ADDED DEBUG CODE
        if ($id === "something") { dump("reading cache file: " . $dir . substr($hash, 2, 20)); }
        // END OF ADDED DEBUG CODE
        // ===============

        return $dir.substr($hash, 2, 20);
    }
```
4. Run the following command: `php bin/console app:complex-data:build-cache --env="dev"` and make sure you get an output that tells you that clearing and building the cache was successful, along side the paths to the cache file (they're important!)
5. Open the site in your browser, under `/` you should get a bunch of debug output, alongside the paths to the cache file (they differ from the CLI!) with the cached object being null since the cache wasn't hit

**Additional context**  
The cache file names *do match*, however, the *pool ids* are different between the console command and the app being executed from the browser:

![image](https://user-images.githubusercontent.com/439899/52705295-d9edb900-2f82-11e9-9140-8f1b9d52bc30.png)
![image](https://user-images.githubusercontent.com/439899/52704941-06ed9c00-2f82-11e9-8cc0-09d0afc19916.png)

**Comment by keichinger** [comment]
I'm suspecting it's due to some service container misconfiguration, as PhpStorm offers me a few service definitions for the `FilesystemAdapter` class:

![image](https://user-images.githubusercontent.com/439899/52706007-a0b64880-2f84-11e9-9da1-a3594448f89a.png)

The first and second lead to:

```xml
    <service id="cache.adapter.filesystem" class="Symfony\Component\Cache\Adapter\FilesystemAdapter" public="false" abstract="true">
      <tag name="cache.pool" clearer="cache.default_clearer"/>
      <tag name="monolog.logger" channel="cache"/>
      <argument></argument>
      <argument>0</argument>
      <argument>/Users/kaieichinger/WebServer/symfony-cache-pool-issue/var/cache/dev/pools</argument>
      <argument type="service" id="cache.default_marshaller" on-invalid="ignore"/>
      <call method="setLogger">
        <argument type="service" id="monolog.logger.cache" on-invalid="ignore"/>
      </call>
    </service>

        <service id="cache.adapter.filesystem" class="Symfony\Component\Cache\Adapter\FilesystemAdapter" abstract="true">
            <tag name="cache.pool" clearer="cache.default_clearer" />
            <tag name="monolog.logger" channel="cache" />
            <argument /> <!-- namespace -->
            <argument>0</argument> <!-- default lifetime -->
            <argument>%kernel.cache_dir%/pools</argument>
            <argument type="service" id="cache.default_marshaller" on-invalid="ignore" />
            <call method="setLogger">
                <argument type="service" id="logger" on-invalid="ignore" />
            </call>
        </service>
```

But now the most interesting one, the third one:

```xml
    <service id="cache.app.recorder_inner" class="Symfony\Component\Cache\Adapter\FilesystemAdapter" public="false">
      <argument>MmEhmCBRXu</argument>
      <argument>0</argument>
      <argument>/Users/kaieichinger/WebServer/symfony-cache-pool-issue/var/cache/dev/pools</argument>
      <argument type="service" id="cache.default_marshaller" on-invalid="ignore"/>
      <call method="setLogger">
        <argument type="service" id="monolog.logger.cache" on-invalid="ignore"/>
      </call>
    </service>
```

The first argument is indeed the one matching our false (?) pool id, which causes the problems aforementioned. I tried digging a bit deeper but the large amount of services and traits used in there was a bit overwhelming, hence why I came here looking for help :)

**Comment by nicolas-grekas** [comment]
Can you try setting the `prefix_seed` option and see if that fixes it? See
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/packages/cache.yaml#L5

**Comment by keichinger** [comment]
@nicolas-grekas that has indeed fixed the issue! Is that expected behaviour then?

**Comment by nicolas-grekas** [comment]
That's why there is this setting :)
It's not required when the cli and fpm see the same path, but it looks like that's not your setup.
Closing then.

**Comment by keichinger** [comment]
Ah wow, after further investigation based on the config key, we've figured out that macOS's case-insesitive file system has trolled us (again): In Nginx's config I used `/Users/kaieichinger/WebServer/` instead of `/Users/kaieichinger/Webserver/`, which then resulted in a different Base64 hash.

Thanks for your time!
