### ISSUE TITLE
[Debug][DebugClassLoader] Reflect on the same vendor concept

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#30221]
The `DebugClassLoader` don't trigger deprecations for classes that are considered in the same vendor. The definition of being in the same vendor is hardcoded as both first namespaces parts (before the first `\`) being equals. However, this is not always true.

For example, in Drupal, you write your custom code in modules. Your custom module namespace **must** be `Drupal\your_module_name\`. Drupal core itself is under the `Drupal` namespace as well (eg `Drupal\Component\DependencyInjection`). That means that your module is considered as being in the same vendor, so extending a core Drupal `@internal` class in your module doesn't trigger any deprecation for example.

Proposed solutions : 
- Provide a way to specify how deep the check on the namespace comparison should be
- Or provide a way to specify namespaces that should trigger deprecations no matter what

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
That could be configured as an argument to the enable() method.
What should be the argument? I don't know exactly. A map maybe, with original namespace as key and remapped namespace as value - the check would be done on remapped values? All I know is that this should be fast :)

**Comment by fancyweb** [comment]
Providing a custom callable that does the comparison would be too slow I guess?

**Comment by nicolas-grekas** [comment]
Slow and more importantly too complex to use to me: it's not like there are thousands of ways to filter namespaces - or maybe there are but we should first seek for the simplest way to solve the issue, DX wise.

**Comment by stof** [comment]
another idea: rely on the file location of the class, and consider files from the same composer package ?
We would have to see how that affects Symfony (we might have cross-component deprecations getting hidden today due to that) but that might be good to solve that, especially as we want our components to allow installing next major of their deps when possible.

**Comment by fancyweb** [comment]
Can you explain your idea of passing an array with original namespace => remapped namespace with my example plz because I don't get what I would put as the remapped namespace.

Just passing an array of namespaces that always trigger the deprecations seems like the easiest way to me. In my example you would do `Debug::enable(['Drupal\your_module_name'])`

**Comment by nicolas-grekas** [comment]
@stof, unfortunately, that wouldn't fix the case of Drupal, which is the one this issue has been created for.

@fancyweb E.g. `['Drupal\your_module_name' => 'your_module_name']` - the right side doesn't need to exist - it would only be used to group prefixes together. In this case for moving a specific subnamespace out of a root one, but it could also allow for joining a subnamespace with a root one, e.g. `'Drupal\aggregator' => 'Drupal\Core'` would mark the aggregator module as sharing the same "deprecation namespace" as core (with not practical consequences for now, that's just an example.)

**Comment by fancyweb** [comment]
Thank you, I get your idea now. I like since it gives more flexibility. I will work on the implementation.
