### ISSUE TITLE
[4.1.7][Form] EntityType with choice_value not working if multiple set to true

### ISSUE THREAD

**Issue by youssefbenhssaien** [symfony/symfony#30228]
**Symfony version(s) affected**: 4.1.7

**Description**  
Overriding an EntityType value with **choice_value** works if `multiple => false`

        $builder->add('vlan', EntityType::class, [
                'class' => ConfigVlan::class,
                'label' => 'Vlan',  
               'choice_value' => 'name', 
               'required' => false
          ])

works fine and result name in value html attribute : 
![image](https://user-images.githubusercontent.com/7301643/52717619-d584c880-2fa1-11e9-9163-0f4c708fbe09.png)

Adding `multiple => true` to the same EntityType :

    $builder->add('vlan', EntityType::class, [
                'class' => ConfigVlan::class,
                'label' => 'Vlan',  
                'choice_value' => 'name', 
                'multiple' => true,
                'required' => false
          ])

Returning Id instead name !

![image](https://user-images.githubusercontent.com/7301643/52717855-60fe5980-2fa2-11e9-9e7e-aa44b4aa1b35.png)

**Comment by xabbuh** [comment]
I cannot confirm your issue. Can you please create a small example application that allows to reproduce it?

**Comment by ismail1432** [comment]
I can confirm on my side

**Comment by xabbuh** [comment]
@ismail1432 Can you upload the project somewhere?

**Comment by youssefbenhssaien** [comment]
I'm writing a small example I need some time :)

**Comment by ismail1432** [comment]
@xabbuh https://github.com/ismail1432/error-form

**Comment by youssefbenhssaien** [comment]
Cannot reproduce the bug !
@ismail1432  you forgot to mention choice_value instead choice_label

Closing this issue ..

**Comment by xabbuh** [comment]
Thanks for the confirmation @youssefbenhssaien!

**Comment by youssefbenhssaien** [comment]
still having this strange behaviour ..... 

I added die to the choice_value to test :
![image](https://user-images.githubusercontent.com/7301643/52780945-a7f45980-304b-11e9-871e-ddadaeab3287.png)

The function never called when having multiple true, and called when having multiple false !

Any idea !

**Comment by youssefbenhssaien** [comment]
Found the problem source :)
expanded is by default set to true, with `multiple = true` symfony render it as a choice or radio html element which doesn't need to set the value.....

I guess EntityType should have expanded by default set to false instead true !! as Entity select data from database and by default has key => value !

**Comment by xabbuh** [comment]
Maybe you have some form type extension changing the default behaviour. But `expanded` by default is `false`.
