### ISSUE TITLE
Var-dumper; easily copy text shown on hover

### ISSUE THREAD

**Issue by evs-xsarus** [symfony/symfony#30256]
When I use `dump()` to display a class, the full class name can be shown when hovering the first element. Copying this part isn't possible in a browser. Could an method be added so one can copy this text shown in the hover?

In the screenshot, it's the marked text.

![image](https://user-images.githubusercontent.com/44158071/52858674-18be7300-312b-11e9-9ea0-a5b908a4cb3c.png)

NB This request holds for all the data that's shown in a hover.

**Comment by nicolas-grekas** [comment]
Somewhat related: #30301
I don't know how we could achieve the described behavior.
What would be your proposal @evs-xsarus?

**Comment by evs-xsarus** [comment]
A possibility would be to use CSS tooltips instead of the 'text' attribute. This could be done completely in CSS.

- https://www.w3schools.com/howto/howto_css_tooltip.asp
- https://www.bitdegree.org/learn/css-tooltip
- https://cssreset.com/create-a-simple-yet-stylish-tooltip-using-css/

**Comment by nicolas-grekas** [comment]
I think https://github.com/symfony/symfony/pull/30301 provides a less intrusive solution: click to source then copy paste.

**Comment by evs-xsarus** [comment]
That's true I believe. Will have to see if that solution is suffice. The reason I want to copy the tooltip is so I can lookup the class in my IDE.

**Comment by nicolas-grekas** [comment]
Perfect, this is resolved then. Thanks for proposing.
