### ISSUE TITLE
Add variable name dumped to the `dump` result

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#30250]
**Description**  
I know that it can be done with X-debug or other tools but it will also good if the `VarDumper` can also provide the original `$var` name. 

**Example**  
```php
$message = 'Symfony is awesome';
$admin = (new User());
dd($message, $admin); 
// output 
"Symfony is awesome"
User {#570 ▼
  -id: 1
  -email: "user@email.fr"
 ...

with this feature

ddd($message, $admin);
//  output 
$message : "Symfony is awesome"
$admin : User {#570 ▼
  -id: 1
  -email: "user@email.fr"
 ...
```

**Comment by juuuuuu** [comment]
That's a great idea! Will you do the PR @ismail1432?

**Comment by ismail1432** [comment]
Yep I can give a try

**Comment by lyrixx** [comment]
Note for thoses who don't want to wait :
```php
dd(['message' => $message, 'admin' => $admin]);
```

I use this all the time

And the JS way:

```js
console.log({message, admin});
```

**Comment by nicolas-grekas** [comment]
`dump(compact('myVar'))` ;)

**Comment by ro0NL** [comment]
from `dd($var)` can we even detect the `"var"` part? In a sane way...

**Comment by nicolas-grekas** [comment]
> from `dd($var)` can we even detect the `"var"` part? In a sane way...

I don't think so. To me, this issue is impossible to implement in any "sane" way. Yes, we can inspect the trace then use token_get_all to extract the source code and then the variable name. But this is going to be quite complex and quite fragile I fear.

Not worth it to me. I may be wrong of course.

**Comment by ismail1432** [comment]
I tried many things without any success :cry: 
I will close this one in favor of @lyrixx tips :smile:
