### ISSUE TITLE
[Form] Date\TimeType marked as invalid on request with single_text and zero seconds

### ISSUE THREAD

**Issue by RevisionTen** [symfony/symfony#30253]
**Symfony version(s) affected**: 3.4 up to 4.2

**Description**  
Submitting a TimeType without seconds and with input option set to "string" causes an TransformationFailedException.

**Possible Solution**  
Change 'H:i:s' to $format in src/Symfony/Component/Form/Extension/Core/Type/TimeType.php at line 167

**Additional context**  
```Symfony\Component\Form\Exception\TransformationFailedException:
Data missing

  at vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:125
  at Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToStringTransformer->reverseTransform('13:00')
     (vendor/symfony/form/ReversedTransformer.php:36)
  at Symfony\Component\Form\ReversedTransformer->transform('13:00')
     (vendor/symfony/form/Form.php:1064)
  at Symfony\Component\Form\Form->modelToNorm('13:00')
     (vendor/symfony/form/Form.php:351)
  at Symfony\Component\Form\Form->setData('13:00')
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:49)

**Comment by xabbuh** [comment]
This is not a bug. When using a string as the input data it currently is expected to be in the format `hour:minute:seconds`. We could think about adding support for a new `input_format` option tough (similar to #29887).

**Comment by RevisionTen** [comment]
Or always add seconds if they are missing, similar to this:

```
// handle seconds ignored by user's browser when with_seconds enabled
// https://codereview.chromium.org/450533009/
if ($options['with_seconds']) {
    $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $e) {
        $data = $e->getData();
        if ($data && preg_match('/^\d{2}:\d{2}$/', $data)) {
            $e->setData($data.':00');
        }
    });
}

Fact is: 
When using html5 time input without seconds the returned value does not match the format.
Solution:
Correct the format

**Comment by RevisionTen** [comment]
I prefer your solution though, If I want to save the time as a string I want control of how the string looks.

**Comment by xabbuh** [comment]
Can you show how you currently build your form?

**Comment by RevisionTen** [comment]
Like this:
```
$builder->add('opens', TimeType::class, [
    'label' => 'Opens',
    'required' => false,
    'widget' => 'single_text',
    'html5' => true,
    'input' => 'string',
    'with_seconds' => false,
]);
```

**Comment by xabbuh** [comment]
Adding the above mentioned event listener when `with_seconds` is enabled or the input format is a string would solve the issue, right?

**Comment by RevisionTen** [comment]
In theory yes, but for some reason the event listener is not called.

Tried it with this:
```
if ($options['with_seconds'] || 'string' === $options['input']) {
    // executes...
    $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $e) {
        // does not execute...
        $data = $e->getData();
        if ($data && preg_match('/^\d{2}:\d{2}$/', $data)) {
            $e->setData($data.':00');
        }
    });
}
```

**Comment by xabbuh** [comment]
Rereading the initial description now: Are you sure this happens on submission of the form? This rather looks like it is related to passing the wrong format when the initial data is set.

**Comment by RevisionTen** [comment]
Yes, this happens when the form is submitted in the browser.

The value that is produced by the `<input type="time">` element is apparently supposed to be in the h:i format, which means that the missing seconds definitely need to be appended if the time types underlying data is always supposed to be in the h:i:s format.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Time_value_format

> The value of the time input is always in 24-hour format: **hh:mm**, regardless of the input format, which is likely to be selected based on the user's locale (or by the user agent). If the time includes seconds (see **Using the step attribute**), the format is always **hh:mm:ss**.

**Comment by xabbuh** [comment]
I am sorry, but I cannot reproduce this issue. Can you create a small example application that allows to reproduce?

**Comment by RevisionTen** [comment]
You were correct, this happened because the initial data was not in the expected format. Sorry for wasting everyones time.

**Comment by xabbuh** [comment]
Thank you for the feedback. 👍

**Comment by xabbuh** [comment]
For the records: with #30358 we will also be able to customise the input format for the `TimeType`.
