### ISSUE TITLE
404 sometimes ignored

### ISSUE THREAD

**Issue by nallias** [symfony/symfony#30263]
**Symfony version(s) affected**: 3.4

**Description**  
Some url are correctly handled to 404 error, some (having a dot at the end) doesn't.

**How to reproduce**  
1. extend fosuser. The login path is /login
2. handle error page on production: https://symfony.com/doc/3.4/controller/error_pages.html

Now the cases:

- `app_dev.php/login`: HTTP200, page displayed : as expected
- `app_dev.php/login1`: HTTP404, profiler details : as expected
- `app_dev.php/login.`: HTTP404, profiler details : as expected

- `app.php/login`: HTTP200, page displayed : as expected
- `app.php/login1`: HTTP404, custom error page is displayed : as expected
- `app.php/login.`: HTTP404, default error page is displayed : expecting the custom error page

Let me know if any additional stuff may help you?

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce the issue you experience?

**Comment by nallias** [comment]
@xabbuh I hoped that would not be necessary ; I will work on this on my leisure time and update tihs issue once it is ready

**Comment by xabbuh** [comment]
Can you in the meantime show the output of `bin/console debug:router login` (where `login` is the name of your route pointing to `/login`)?

**Comment by nallias** [comment]
Precision: the standard route works perfectly, it is the addition of a dot at the end that is problematic on app.php

Here it is:
```
>php bin/console debug:router fos_user_security_login
+--------------+-----------------------------------------------------------+
| Property     | Value                                                     |
+--------------+-----------------------------------------------------------+
| Route Name   | fos_user_security_login                                   |
| Path         | /login                                                    |
| Path Regex   | #^/login$#sD                                              |
| Host         | ANY                                                       |
| Host Regex   |                                                           |
| Scheme       | ANY                                                       |
| Method       | GET|POST                                                  |
| Requirements | NO CUSTOM                                                 |
| Class        | Symfony\Component\Routing\Route                           |
| Defaults     | _controller: fos_user.security.controller:loginAction     |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler   |
| Callable     | FOS\UserBundle\Controller\SecurityController::loginAction |
+--------------+-----------------------------------------------------------+
```

**Comment by Simperfit** [comment]
@nallias do you use api-platform or fosrestbundle ?

**Comment by nallias** [comment]
@Simperfit I know neither of them, nor do they appear in app/AppKernel.php nor in vendor/

**Comment by xabbuh** [comment]
@nallias I really have no idea how that could happen. Could you please create an application that we can use to debug what is going on?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
