### ISSUE TITLE
[Translation] replaceAttribute of not existing attribute (The index "6" is not in the range [0,4])

### ISSUE THREAD

**Issue by kgronkowski** [symfony/symfony#30260]
**Symfony version(s) affected**: 4.2.3

**Description**  
After latest deployment of our application we started to encounter issue with symfony/translation.
`composer install --no-dev`  triggers `cache:clear` which gives following error:
```
In Definition.php line 269:
                                             
  The index "6" is not in the range [0, 4].  
```
My own investigation determined following commit to be couse of this issue:
https://github.com/symfony/translation/commit/83008de5cdad1e014b4b3903309c611bc181d872
In tests provided in this commit arguments list is defined as having 7 or 8 items, while in default config there are 5 arguments

**How to reproduce**  
Just create new symfony app, replace `composer.json` file with content provided bellow. Clear composer cache and vendor dir to ensure new packages will be installed. After composer finish installing (most symfony/* packages will be used in `dev-master` versions including `symfony/translation`) run:
`bin/console cache:clear`

**Possible Solution**  
In `symfony/translation` `DependencyInjection/TranslatorPass.php` there should be condition checking if number of parameters allows for replacing before using `replaceAttribute(6, ...`. From what I was able to determine in default symfony configuration class which attributes are replaced takes only 5 but there is call for `replaceAttribute` with 6 and 7 as attribute index. Should there be 8 parameters in constructor or is there something that I do not understand?

**Additional context**  
For some reason composer installs 'dev-master' version. `composer why` output:
```
$ composer why symfony/translation
friendsofsymfony/user-bundle     dev-master  requires  symfony/translation (^2.8 || ^3.0 || ^4.0)  
liip/imagine-bundle              dev-master  requires  symfony/translation (^3.4|^4.0)             
sonata-project/admin-bundle      3.44.0      requires  symfony/translation (^2.8 || ^3.2 || ^4.0)  
sonata-project/core-bundle       3.12.0      requires  symfony/translation (^2.8 || ^3.2 || ^4.0)  
sonata-project/formatter-bundle  4.x-dev     requires  symfony/translation (^3.4 || ^4.0)          
sonata-project/user-bundle       4.x-dev     requires  symfony/translation (^2.8 || ^3.2 || ^4.0)
```
Minimum stability is set to "dev" due to the fact we use our own internall library that is developed in paralell.

`composer.json`
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "ext-curl": "*",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/console": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "4.2.*",
        "symfony/maker-bundle": "^1.9",
        "symfony/monolog-bundle": "^3.3",
        "symfony/orm-pack": "^1.0",
        "symfony/twig-bundle": "4.2.*",
        "symfony/webpack-encore-bundle": "^1.0",
        "symfony/yaml": "4.2.*",
        "sonata-project/admin-bundle": "^3.42",
        "sonata-project/doctrine-orm-admin-bundle": "^3.6",
        "sonata-project/core-bundle": "3.12",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/acl-bundle": "^1.0",
        "ramsey/uuid": "^3.8",
        "egeloen/ckeditor-bundle": "*",
        "liip/imagine-bundle": "dev-master"
    },
    "require-dev": {
        "symfony/dotenv": "4.2.*"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    }
}
```

**Comment by xabbuh** [comment]
Thank you for reporting, this will be fixed by #30261.
