### ISSUE TITLE
Container::set method description is wrong

### ISSUE THREAD

**Issue by speller** [symfony/symfony#30270]
**Symfony version(s) affected**: 4.2

**Description**  
The `Symfony\Component\DependencyInjection\Container::set` annotation states the following:

>     Setting a service to null resets the service: has() returns false and get()
>     behaves in the same way as if the service was never created.

But this is impossible to do because only synthetic services can be set to null. It is impossible to dispose a regular public or private service instance when using with app servers like PHP RoadRunner which doesn't finish scripts. In this case DB connections defined as regular services are not disposed and quickly wastes DB max connections.

**Possible Solution**  
Allow to null any service. 
Or define and document a legal way to do that.

**Comment by stof** [comment]
I think the phpdoc was not updated properly when deprecating that behavior.



> Or define and document a legal way to do that.

There is a `reset` method on the container, which resets all instances (resetting only a single instance does not work to release, as it might still be referenced by other instantiated services depending on it).

**Comment by speller** [comment]
Thank you for the answer. What about adding the `reset` method to the `Symfony\Component\DependencyInjection\ContainerInterface`?

**Comment by ro0NL** [comment]
@speller it's in `ResettableContainerInterface` already :)

**Comment by speller** [comment]
Yes, the only addition is:
>  * @deprecated since Symfony 4.2, use "Symfony\Contracts\Service\ResetInterface" instead.

Also, I've found I have two files implementing this interface: `c:\...\vendor\symfony\contracts\Service\ResetInterface.php` and `c:\...\vendor\symfony\symfony\src\Symfony\Contracts\Service\ResetInterface.php` (under Windows). Is it correct that files are duplicated?

**Comment by ro0NL** [comment]
oh, oops. It's `ResetInterface` now yes.

> Is it correct that files are duplicated?

Yes, `symfony/contracts` is a standalone composer package, but split from this repo. When autoloading it will be used from the first location.

**Comment by nicolas-grekas** [comment]
PR welcome: we should add the "synthetic" word at the beginning to improve that, isn't it?
`Setting a synthetic service [...]`
The PR should be submitted on branch 3.4, because that's the only non-deprecated behavior there also.
