### ISSUE TITLE
[TwigBridge] Suggestion: Add HTTP username and password to `absolute_url`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#30281]
**Description**  
Allow generating URL's containing username and password: http://foo:bar@example.com/

**Example**  
```twig
{{ absolute_url(path(...), {username:'foo', password: 'bar'}) }}
```

This would be useful in cases where the website is (still) hidden behind some basic HTTP auth, e.g. during development or on a staging server.

Should be easy to implement, just add two optional parameters to [HttpFoundationExtension::generateAbsoluteUrl()](https://github.com/symfony/twig-bridge/blob/master/Extension/HttpFoundationExtension.php#L58)

**Comment by OskarStark** [comment]
You need to be careful, as username and password could already be used as parameters... I know the chance is low but possible.

But for the idea itself 👍🏻👌🏻

**Comment by javiereguiluz** [comment]
According to [RFC 3986 - Uniform Resource Identifier (URI)](https://tools.ietf.org/html/rfc3986):

```
3.2.1.  User Information

   The userinfo subcomponent may consist of a user name and, optionally,
   scheme-specific information about how to gain authorization to access
   the resource.  The user information, if present, is followed by a
   commercial at-sign ("@") that delimits it from the host.

      userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )

   Use of the format "user:password" in the userinfo field is
   deprecated.  Applications should not render as clear text any data
   after the first colon (":") character found within a userinfo
   subcomponent unless the data after the colon is the empty string
   (indicating no password).  Applications may choose to ignore or
   reject such data when it is received as part of a reference and
   should reject the storage of such data in unencrypted form.  The
   passing of authentication information in clear text has proven to be
   a security risk in almost every case where it has been used.

   Applications that render a URI for the sake of user feedback, such as
   in graphical hypertext browsing, should render userinfo in a way that
   is distinguished from the rest of a URI, when feasible.  Such
   rendering will assist the user in cases where the userinfo has been
   misleadingly crafted to look like a trusted domain name
   (Section 7.6).
```

Considering that -> `"user:password" in the userinfo field is deprecated` I'm voting 👎 to this proposal.

**Comment by ThomasLandauer** [comment]
I know that it's a security risk.

My use case: When testing payment methods, you need to give an url to which they can send their payment notification (e.g. PayPal). When you run this on a (hidden) staging/testing server, what can you do? Right now, I'm passing it in the form `http://{{ stage_username }}:{{ stage_password }}@stage.example.com/notification-url`

**Comment by Guikingone** [comment]
I think that you should generate the URL in the controller/a dedicated service and send it to the view in the final "version", your view should not contain sensible information (as explained here: https://github.com/symfony/symfony/pull/30229)

So like @javiereguiluz, that's a 👎 for me.

**Comment by Guikingone** [comment]
Plus, if it's a external service like Paypal, you probably should consider building a local route which receive the user request/credentials and prepare the credentials before redirecting to this external service.

**Comment by ThomasLandauer** [comment]
Maybe I should have explained the use case better in my initial post ;-)

* I have a staging server with `.htaccess` `AuthType Basic`.
* I want to test PayPal Sandbox payments with it.
* PayPal requires that you pass your notification url as a hidden form field value upon payment initialization: `<input type="hidden" name="notify_url" value="http://foo:bar@stage.example.com/notification-url">`.  
@Guikingone: This is the "final" version of the url. And it needs to be in the view (cause that's the way this kind of PayPal interface works).
* The security risk is limited (or rather inexistent) because: If somebody ever gets to see this page, they have already "cracked" the `AuthType Basic` protection anyway ;-)

So the real question is not: "Is it a good idea to have a username/password in your web page sourcecode?" But rather: "Do we want to offer a better way to do it than `http://{{ stage_username }}:{{ stage_password }}@stage.example.com/notification-url`?"

@javiereguiluz regarding the RFC: Yeah, sure :-) But it does work with PayPal ;-)

**Comment by Guikingone** [comment]
_Even if Paypal do bad things, I continue to think that we shouldn't add this feature_ 😄 

Seriously, I think that this is something related to your internal logic and not to a missing feature, you can probably call a macro which generate the link (or even a twig block) not to mention that this type of usage is already possible by passing an array to the generated URL (the format isn't the one that you looking for but you can easily use the `format` filter in order to "format" it). 

Doc: https://twig.symfony.com/doc/2.x/filters/format.html. 

The main concern here is security and the number of project which use this feature, if it's only for 2-3 projects, it probably could be part of a separated bundle. 

_And now, I'm just looking at Paypal documentation trying to understand why Paypal developers use this type of broken URL_ 😄

**Comment by fabpot** [comment]
I'm closing this issue as this is not a feature I'd like to add to Symfony core. Thanks for proposing.

**Comment by ThomasLandauer** [comment]
> not to mention that this type of usage is already possible by passing an array to the generated URL

@Guikingone: Pass an array to what? To `absolute_url()`? How? Don't understand...

BTW: PayPal documentation is one big mess. Here's an example of the sort of PayPal button I'm talking about: https://stackoverflow.com/q/13415964/1668200

**Comment by Guikingone** [comment]
@ThomasLandauer 

You can pass an array to `path()`:

```twig
<a href="{{ path('route', {'id': 25}) }}"></a>
```

For Paypal, why not using Stripe?

**Comment by ThomasLandauer** [comment]
@Guikingone: Still don't get it :-( If I do:
```twig
{{ absolute_url(path('notification-url', {'username': 'foo', 'password': 'bar' })) }}
```
...I get:
> http://example.com/notification-url?username=foo&password=bar

How can I use `format()` to "move" `foo` and `bar` from the query string to between `//` and `example`?

> For Paypal, why not using Stripe?

Customer requirement ;-)

**Comment by Guikingone** [comment]
Maybe using something like this: 

```twig
<a href="{{ 'example.com' in absolute_url(path('notification-url')) }} ? absolute_url(path('notification-url'))|format('%s:%sexemple.com', username, password) : absolute_url(path('notification-url'))"></a>
```

**Comment by ThomasLandauer** [comment]
@Guikingone: I doubt that it will work this way cause `format()` expects the `%s` **before** the `|`.  
However, thanks to your insisting :-) I started to think about other ways and finally created a custom filter: https://stackoverflow.com/q/54830022/1668200

**Comment by Guikingone** [comment]
Sorry, could benefit from the `replace` function, `format` isn't adapted 😄
