### ISSUE TITLE
dotenv issue

### ISSUE THREAD

**Issue by GiacomoLaw** [symfony/symfony#30297]
**Symfony version(s) affected**: 4.2

**Description**  
Hi all, I am having an issue where .env is working on local host however not on my Hostwinds server.

**How to reproduce**  
`Fatal error: Uncaught TypeError: Return value of Symfony\Component\Dotenv\Dotenv::populate() must be an instance of Symfony\Component\Dotenv\void, none returned in /home/kjzotpry/public_html/server.com/vendor/symfony/dotenv/Dotenv.php:146 Stack trace: #0 /home/kjzotpry/public_html/server.com/vendor/symfony/dotenv/Dotenv.php(469): Symfony\Component\Dotenv\Dotenv->populate(Array, false) #1 /home/kjzotpry/public_html/server.com/vendor/symfony/dotenv/Dotenv.php(51): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array) #2 /home/kjzotpry/public_html/server.com/review/send_review.php(7): Symfony\Component\Dotenv\Dotenv->load('../.env') #3 {main} thrown in /home/kjzotpry/public_html/server.com/vendor/symfony/dotenv/Dotenv.php on line 146`

How can I fix this?

Thanks!

**Comment by dmaicher** [comment]
Seems like that server is not running php >= 7.1?

**Comment by GiacomoLaw** [comment]
@dmaicher hmmm, odd. I will contact support and see if they can sort it out on the server.

Thanks

**Comment by GiacomoLaw** [comment]
Nevermind, it is running 7.2

![image](https://user-images.githubusercontent.com/9038673/52975010-98627100-33bb-11e9-806f-625ba6891e0c.png)

Any other reason this could be happening?

**Comment by GiacomoLaw** [comment]
Upgraded to 7.2, now getting this error:

```
Warning: mysqli::__construct(): (HY000/1130): Host '142.11.205.46' is not allowed to connect to this MariaDB server in /home/kjzotpry/public_html/outsourcingdepotinc.com/review/send_review.php on line 24
Connection failed: Host '142.11.205.46' is not allowed to connect to this MariaDB server
```

**Comment by xabbuh** [comment]
This is a configuration is that needs to be solved on the server side. There is nothing we can do about that in Symfony.

**Comment by GiacomoLaw** [comment]
Seems like I have an issue with the user who is logging in. I’ll take a look in phpmyadmin and see what I can do.

**Comment by krishnaspace** [comment]
I also had the same issue when I tried to run Symfony 4 on Ubuntu 16.04 server. In my situation I forgot to enable the new php version in the Apache server after upgrading from v7.0 to v7.2 . I hope below details would help you to check on your server.

Run following command to see which php version is active.  
`ls /etc/apache2/mods-enabled/php*`

Disable previously installed php version.  
`sudo a2dismod php7.0`  

Enable new installed php version.  
`sudo a2enmod php7.2`

Do not forget to restart Apache server.
