### ISSUE TITLE
[Security] Validate IPs in Access Control

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#30299]
**Description**  
The feature to [use `access_control` for IP validation](https://symfony.com/doc/current/security/access_control.html#matching-access-control-by-ip) is very convenient. However it doesn't validate IPs, which may lead to confusing debugging scenarios (e.g. #30298)

**Example**  
Putting anything that it's not an IP or a subnet mask should result in an exception.

**Comment by chalasr** [comment]
👍 PR welcome

**Comment by kiler129** [comment]
I will happily deliver a PR :)
