### ISSUE TITLE
Messenger - Use different Serializer

### ISSUE THREAD

**Issue by versh23** [symfony/symfony#30293]
Hello

I have a 2 transports and i need own serializer for each transports. is it possible?  ( one in JSON format, one in XML for example)

**Comment by linaori** [comment]
Heya, for support questions, please check one of the support channels on: https://symfony.com/support, thanks!

**Comment by javiereguiluz** [comment]
As @linaori said, this looks like a support question, so we must close it. If you try to do this with the help provided by the community and it doesn't work, then we can reopen this as a possible Symfony bug. Thanks.
