### ISSUE TITLE
MariaDB with Symfony 3.4

### ISSUE THREAD

**Issue by picks44** [symfony/symfony#30291]
**Symfony version(s) affected**: 3.4.22

**Description**  
Trying to implement the `server_version` config of Doctrine DBAL as explained in the doc : _If you are running a MariaDB database, you must prefix the server_version value with mariadb- (e.g. server_version: mariadb-10.2.12)._ ([here](https://symfony.com/doc/3.4/reference/configuration/doctrine.html#doctrine-dbal-configuration))

```
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        server_version: 'mariadb-10.1.38'
```

Getting this error
`Invalid platform version "mariadb-10.1.38" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>".`

**Possible Solution**  
Shall we upgrade to doctrine/dbal v2.7? It is armless for the rest of the project? 
If yes, can I just do a `composer require doctrine/dbal:2.7`?

**Comment by derrabus** [comment]
> Shall we upgrade to doctrine/dbal v2.7?

You need at least DBAL 2.7 to use the `mariadb` prefix in `server_version`. You should upgrade to DBAL 2.9 if possible.

If for some reason you want to keep an old (and unmaintained!) version of DBAL, you can use `server_version: '5.6'` which should do just fine.

**Comment by stof** [comment]
`composer require doctrine/dbal:2.7` would require 2.7.0 exactly. You should use `^2.7` (or `2.7.*`) as constraint to allow a range.

**Comment by picks44** [comment]
@stof @derrabus thanks guys!
Hope this doesn't have side-effects, lt's try.

Could also be nice to update the doc about this ;)
