### ISSUE TITLE
[Debug] Actively discourage using Serializable by triggering a deprecation notice

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#30304]
When `DebugClassLoader` is registered, we could make it unconditionally trigger a deprecation notice when it loads a class that directly `implements Serializable`.

We should wait for https://wiki.php.net/rfc/custom_object_serialization to be resolved before.

**Comment by fancyweb** [comment]
unconditionally = for all PHP versions and not only for the buggy 7.3 right ?

**Comment by nicolas-grekas** [comment]
All PHP versions yes.

**Comment by fancyweb** [comment]
The RFC has been accepted. I will implement this feature today. #eufossa

**Comment by nicolas-grekas** [comment]
Too much work :)
Let's do it during reviews.
