### ISSUE TITLE
[Form] Improve the group_by option for choices

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30315]
**Description**  
In Symfony 2.7 (with `choices_as_values` set to `false`) it was possible to have choices in different choice groups that shared the same labels, this is not possible anymore.

Instead of [this hack](https://github.com/symfony/symfony-docs/issues/5905) proposed in Symfony Docs, @Tobion wondered [in this comment]() if this use-case be better solved by allowing `group_by` option to return an array of groups? This way people would just add the choices once and then could add them to multiple groups if needed.

**Comment by antonch1989** [comment]
@javiereguiluz I could try to handle this one

**Comment by javiereguiluz** [comment]
@antonch1989 great! Thank you.

If you estimate that this task will be very complex or if you think multiple different implementations are possible, you can ask here for advice to people like @vudaltsov @HeahDude and @xabbuh who are experts in Symfony Forms and are willing to help the community.

**Comment by antonch1989** [comment]
![it-works](https://user-images.githubusercontent.com/8297194/53157595-e1d8d900-35d2-11e9-8b58-4e068d834777.png)
The issue was create a long time ago. Does this problem still exist? I ask because I don't see with `"symfony/form": "4.2.*"` in my composer.json

**Comment by xabbuh** [comment]
@antonch1989 Can you share the configuration of your form type?

**Comment by antonch1989** [comment]
`$builder = $this->createFormBuilder();
        $builder->add('country', ChoiceType::class, [
            'choices' => [
                'Top' => [
                    'FR' => 'France',
                    'DE' => 'Germany',
                ],
                'All' => [
                    'AT' => 'Austria',
                    // ...
                    'DE' => 'Germany',
                    // ...
                ],
            ],
        ])
            ->add('submit', SubmitType::class)
        ;`

**Comment by xabbuh** [comment]
But you are not using the `group_by` option here at all. :)

**Comment by antonch1989** [comment]
@xabbuh sorry, I don't get it :) In the documentation diff created by @webmozart  was written that it doesn't work with this configuration. That's why the hack with `choice_label` was suggested. Afterwards a proper solution with adding more functionality to `group_by` was proposed by @Tobion. But if it works then why we need this? Could you clarify a bit, probably I missunderstood the situation.

**Comment by xabbuh** [comment]
@antonch1989 If I understand the request correctly, the goal would be that instead of

```php
$builder->add('country', 'choice', [
    'choices' => [
        'Top' => [
            'Top_France' => 'FR',
            'Top_Germany' => 'DE',
        ],
        'All' => [
            'Austria' => 'AT',
            // ...
            'Germany' => 'DE',
            // ...
        ];,
    ],
    'choice_label' => function ($choice, $key) {
        if ('Top_' === substr($key, 0, 4)) {
            // Strip "Top_"
            return substr($key, 4);
        }

        // Return unchanged
        return $key;
    },
]);
```

you could use this:

```php
$builder->add('country', 'choice', [
    'choices' => [
        'Austria' => 'AT',
        'France' => 'FR',
        'Germany' => 'DE',
        // ...
    ],
    'group_by' => function ($choice) {
        if (in_array($choice, ['DE', 'FR'], true)) {
            return ['Top', 'All'];
        }

        return ['All'];
    },
]);
```

**Comment by antonch1989** [comment]
oh, I see. I'll try again in this case, thanks for clarifying
