### ISSUE TITLE
Add X-Robots-Tag in header of response in dev mode

### ISSUE THREAD

**Issue by xaro93** [symfony/symfony#30318]
**Description**  
For security, you can automatically add the **X-Robots-Tag: noindex** header in developer mode. Sometimes it happens that someone will make such a website available on the Internet. I think it would be better for search engines to not index such websites.

[Robots meta tag and X-Robots-Tag HTTP header specifications](https://developers.google.com/search/reference/robots_meta_tag?hl=en#using-the-x-robots-tag-http-header)

**Comment by javiereguiluz** [comment]
I like this proposal a lot!

We already include `<meta name="robots" content="noindex,nofollow" />` for anything related to the profiler ... but I think it makes sense to add `X-Robots-Tag: noindex, nofollow` to the entire site if it's being run in dev environment. Anyone see any potential drawback?
