### ISSUE TITLE
[HttpFoundation] Ability to modify namespaced session

### ISSUE THREAD

**Issue by PlanetGamingGG** [symfony/symfony#30322]
**Background**
So I read the docs about Attributes and Namespaced Attributes which allows syntax like `test/c`.
https://symfony.com/doc/current/components/http_foundation/sessions.html#attributes
So I tried it to **modify** an existing key but it did not work, instead it creates a new session key.

Code : 
```php
$session = new Session(new NativeSessionStorage(), new NamespacedAttributeBag());
$session->start();
$session->set('test', ['a' => 'hello', 'b' => 'world']);
$session->set('test/a', 'John');
```
Running the code above will create this session keys : `test`, `test/a`.
This frustrates me for a while until someone points out that it will only add a new key but not modify.

**Description**  
The ability to modify existing session keys.

**Example**  
```php
$session = new Session(new NativeSessionStorage(), new NamespacedAttributeBag());
$session->start();
$session->set('test', ['a' => 'hello', 'b' => 'world']);
$session->set('test/a', 'John');
```
Output of `$session->get('test');` : `['a' => 'John', 'b' => 'world']`

**Comment by xabbuh** [comment]
This should already be the case. At https://github.com/xabbuh/symfony/tree/issue-30322 you can take a look at a test that shows the current behaviour which as far as I understand you is what you would like to have.

**Comment by PlanetGamingGG** [comment]
Dear @xabbuh, Now that I've tested it, it works as expected.. It changes the values as expected.
Sorry for this and thanks for the reply.

When I discovered this issue, it was around 2AM and I suspected that when I var_dump the SESSION which I did not cleared of previous construct with `AttributeBag` instead of `NamespacedAttributeBag`, and I mistook it as It does not modify the values.
