### ISSUE TITLE
[RFC][Monolog] Consider adding a hard limit on log buffered in dev

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#30333]
**Description**  

When running consumer / worker in dev env, they leaks a lot. Symfony buffer all logs (mainly for the profiler). In CLI I'm not sure it makes sens. 

So IMHO we could disable this feature in CLI or at least add an hard limit.

WDYT ?

**Comment by linaori** [comment]
Instead of not logging, what if we add a future to limit messages in memory and force a flush after X messages?

**Comment by lyrixx** [comment]
@linaori I'm sorry if I was not clear enough, but I'm not talking of not logging, but instead I would like to disable the buffering.

Anyway, I will have a look at this this morning

**Comment by lyrixx** [comment]
actually I have no issue with finger crossed since it is not enabled in dev by default :)
