### ISSUE TITLE
Typo in SimpleFormAuthenticationListener

### ISSUE THREAD

**Issue by nikic** [symfony/symfony#30341]
The check https://github.com/symfony/security/blob/baa22f665a7ea04c2bfb4d6236a2020a25979f10/Http/Firewall/SimpleFormAuthenticationListener.php#L100 should be one of

```
if (!\is_string($username))
// or
if (!\is_string($username) && !(\is_object($username) && !\method_exists($username, '__toString')))
```

As currently written, the second condition will always be false.

Noticed this while looking into an opcache optimization bug caused by this piece of code :)

**Comment by nicolas-grekas** [comment]
Thanks, the fix should be submitted on branch 3.4, with a test case if possible.
I'm labelling as "good first issue" if anyone wants to take it.

**Comment by chalasr** [comment]
Same for https://github.com/symfony/symfony/blob/848a83078cc4b3927d614c9497456193bf4f5cea/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php#L88

**Comment by cardillomarcelo** [comment]
I'd like to take it if possible. Should be able to do it over the weekend.

**Comment by xabbuh** [comment]
@cardillomarcelo I am sorry but someone already opened a pull request (see #30347).

**Comment by cardillomarcelo** [comment]
np :+1:
