### ISSUE TITLE
Disable security for routes using annotation

### ISSUE THREAD

**Issue by redayoub** [symfony/symfony#30369]
I have some urls in my API that doesnt need to be secure but they are under a secure firewall because of the patern, so instead of having to add each route to the security file and use security: false, I think it will be helpfull if I can just use an annotation inside my controller in order to disable the security for the route like this : @Security(enable="false").

**Comment by antonch1989** [comment]
I could take this one, in case this feature is needed

**Comment by oliverde8** [comment]
I don't agree with this, the security shouldn't be configured on the route.

**Comment by fabpot** [comment]
And anyway, this is not possible to implement. So, let's close.
