### ISSUE TITLE
Support boolean parameters in Route condition

### ISSUE THREAD

**Issue by quazardous** [symfony/symfony#30366]
**Description**  

Using parameter substitution with boolean is not allowed in route condition.

**Example**  

So this is not possible:

```php
/**
 * @Route("/test", condition="%kernel.debug%")
 */
class TestController extends AbstractController
{*
...
```

Exception is here :

```php
// symfony/framework-bundle/Routing/Router.php
// near line 176 : hard coded type test : add is_bool() ?
...

            if (\is_string($resolved) || is_numeric($resolved)) {
                $this->collectedParameters[$match[1]] = $resolved;

                return (string) $resolved;
            }
...
```

**Comment by nicolas-grekas** [comment]
Would you like to send a PR doing so? I'd suggest casting booleans to the `"0"/"1"` string.
That should target master as it's a new feature and it should come with test cases of course ;)

**Comment by quazardous** [comment]
I'll give it a shot but not in the next couple of weeks. Too much on my plate 😅

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/30379
