### ISSUE TITLE
Debug form type extensions in console 

### ISSUE THREAD

**Issue by markitosgv** [symfony/symfony#30394]
Debugging form in console 

```
php bin/console debug:form
```

Appears many times as type extensions configured with new getExtendedTypes method. May cause confusion thinking you've got this extension registered twice or something like that. I think a good option is to put nearby these lines the extended type.
What do you think?

Now

Type extensions
---------------

 * App\Form\Extension\HTMLPurifierTextTypeExtension
 * App\Form\Extension\HTMLPurifierTextTypeExtension

After

Type extensions
---------------

 * App\Form\Extension\HTMLPurifierTextTypeExtension [TextType::class]
 * App\Form\Extension\HTMLPurifierTextTypeExtension [ChoiceType::class]

**Comment by yceruto** [comment]
I'd suggest display an unique list there since the main page is about general information only.

It'll be good to have this one too for type extension information.
```bash
php bin/console debug:form HTMLPurifierTextTypeExtension
```

Status: Reviewed

**Comment by markitosgv** [comment]
@yceruto thats a good idea

**Comment by yceruto** [comment]
Tip: All you need to solve the problem is to move this line out of the `foreach`:
https://github.com/symfony/symfony/blob/c0323bd24be5e35c7209735732798edc63a994f8/src/Symfony/Component/Form/DependencyInjection/FormPass.php#L107

Would you like to make the change?

**Comment by yceruto** [comment]
The target branch is `4.2` where the `getExtendedTypes` method was introduced.

**Comment by markitosgv** [comment]
ok @yceruto I make the change
