### ISSUE TITLE
Symfony Form doesn't like special characters when expanded = true

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#30398]
**Symfony version(s) affected**: 4.2.3

**Description**  
Symfony Form doesn't like special characters when expanded = true in a EntityType field

**How to reproduce**  
```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('field', EntityType::class, [
                'class' => 'App:Category',
                'choice_name' => 'name',
                'placeholder' => 'Choose a Category',
                'multiple' => false,
                'expanded' => true,
            ])
            ->getForm();

.......
```

**Possible Solution**  
change expanded to false
it would work with the same data

**Additional context**  
I have a category name that contains " **!** "

**Comment by xabbuh** [comment]
What do you mean with "doesn't like special characters"? What's the behaviour you see? What did you expect instead? How can we reproduce it?

**Comment by cybernet** [comment]
![expanded](https://user-images.githubusercontent.com/125879/53508975-c37f4b80-3ab2-11e9-8ad2-59185cee6a4a.png)

1. Create a Form
2. Add a field ( EntityType )
3. make sure that what you choose to show has " **!** " in it's name ( like " **My F!rst Category** " )
4. set expanded = **false**

_it will work flawlessly_ 

go back to step number 4
change expanded = **true**
now you should see the screenshot above

**Comment by yceruto** [comment]
If expanded = true the name becomes the HTML `<input name />` attribute of the radio input (or checkbox if multiple) which deals with some ASCII limitations according to W3 standard and so this behavior is expected.

Probably what you wnat to use `choice_label` option instead?

**Comment by cybernet** [comment]
so i can' create radio buttons with special characters ? really ?

**Comment by yceruto** [comment]
> so i can' create radio buttons with special characters ? really ?

Yes, you can, try with `choice_label` option instead of `choice_name`.

**Comment by stof** [comment]
`choice_name` controls the name of the child Form object, and we indeed have restriction on valid form names.
You almost never need to customize that one for a ChoiceType. And you need to account for its restriction. Labels (`choice_label`) and values (`choice_value`) can be what you want though (but be careful that EntityType has some builtin optimization when you let it use the primary key for `choice_value`)

**Comment by xabbuh** [comment]
I am closing here as there is nothing to change in the code. But we are trying to clarify this a bit in the documentation (see symfony/symfony-docs#11082).
