### ISSUE TITLE
Cache error while using anonymous class inside controller

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#30395]
**Symfony version(s) affected**: 4.2.3

**Description**  
I got error **Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Cache key "@anonymous" contains reserved characters {}()/\@:**
In my controller action method I am using anonymous class

```
...
$form = $this->createForm(SomeType::class, $this->getDataWrapper($data));
...
protected function getDataWrapper($data)
    {
        return new class ($data) {
            protected $data;

            public function __construct($data)
            {
                $this->data = $data;
            }

            public function getData() {
                return $this->data->getQuery()->getResult();
            }

            public function setData($data) {
                $this->data = $data;
            }
        };
    }
```

I was able to fix this by using ordinary, not anonymous class, but I think it should be fixed somehow

**Comment by xabbuh** [comment]
Are you able to create a small example application that allows to reproduce this issue? That would probably help a lot in identifying the root cause for this.

**Comment by zim32** [comment]
The issue is specific. I was trying to provide data to form using anonymous class, which serves as a data wrapper. I think somewhere in form code, it is trying to work with cache, and throws this error. Only in prod env.

Please tell me if you need example application if you don't figure out how to reproduce.

**Comment by xabbuh** [comment]
Yes, please create such an example application.

**Comment by zim32** [comment]
Unfortunately I have no time to create separate application.
The problem is that Cache system can not work with anonymous classes. 

Maybe this is not a bug but just requirement not to use anonymous classes with cache system at all.

Screenshot
http://i67.tinypic.com/wcog1y.png

**Comment by nicolas-grekas** [comment]
Can you please share the full stack trace of the error?

**Comment by zim32** [comment]
Yeah. But only in image format, sorry.
https://ibb.co/fkhZg5h

**Comment by xabbuh** [comment]
Just looking at the stack trace I don't know what causes this error or how to prevent it. Will you be able to provide an application that allows us to reproduce? Otherwise I suggest we close here as there isn't much we can do right now.

**Comment by zim32** [comment]
Ok I'm closing due to very specific cache usage (anonymous classes)

**Comment by nicolas-grekas** [comment]
Reopening, I'd like to have a look.

**Comment by cadavre** [comment]
Confirmed this error.
