### ISSUE TITLE
[Console] Corrupt output

### ISSUE THREAD

**Issue by Nsbx** [symfony/symfony#30415]
First i'm sorry if an issue already exist i made research but i have found nothing about this. (And the problem is so strange that I didn't really know what to type to find something similar)

**Symfony version(s) affected**: 4.2.3

**Description**  
Sometime when i use the symfony console, the output is completly corrupt like this :
![image](https://user-images.githubusercontent.com/8930930/53628475-66e37400-3c0b-11e9-8bcc-84d5ecacf4c1.png)

**How to reproduce**  
I don't found a way to reproduce the bug any time, for now is very random.

**Additional context**  
I already have this bug on this console :
- hyper.is
- Default windows console
- Powershell console

**Comment by javiereguiluz** [comment]
As you have guessed, without a "bug reproducer" it's going to be very hard to try to fix this ... unless someone using Windows faced the same issue in the past and can provide a hint to us. Let's wait and see.

**Comment by Nsbx** [comment]
Yeah i know :(
I will try this week-end to find a way to replicate the bug.

**Comment by sstok** [comment]
I can remember a similar issue 🤔 are you using a different kind of encoding for your filesystem?

**Comment by sstok** [comment]
https://github.com/symfony/symfony/issues/22327

Try removing the vendor folder, and running composer install again. Clear the cache by removing the var/cache folder completely. I can't remember the original issue but I believe it had something to do with FTP binary mangling the file contents.

**Comment by chalasr** [comment]
Closing as no reproducer was provided. Feel free to reopen or submit a PR with test case if you hit this issue and have a fix for it.
