### ISSUE TITLE
Cannot use constructor dependency injection on autowired / lazy command

### ISSUE THREAD

**Issue by antfarmer** [symfony/symfony#30424]
**Symfony version(s) affected**: 3.4.22

**Description**  
I would like to use dependency injection of services (logger, entityManager, etc.) via the constructor of some of my commands. The problem is when I declare a constructor (with or without including the name argument), the command is no longer automatically auto-registered in the container. I expect that because I'm using auto-wiring, the container will both detect the commands and pass the appropriate service definitions to their constructors, without having to manually register the commands. It seems I must either define each command manually or have to make their dependencies public, as using the container to get to them within the `ContainerAwareCommand` throws an error about private services.

I believe having to define each command kind of defeats the purpose of auto-wiring and is a step back from symfony 2.x where commands were auto-registered and we were allowed to pull services directly from the container.

**How to reproduce**  
`services.yml`
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AppBundle\:
    resource: '../../../../../../src/AppBundle/*,../../../../../../src/AppBundle/Form/Type/*'
    exclude: '../../../../../../src/AppBundle/{DTO,Entity,Form,Listener,Logging,Repository,Resources,Tests,Util}'
```
`VersioningCommand.php`
```
namespace AppBundle\Command;
class VersioningCommand extends Command {
	protected static $defaultName = 'app:version';
	protected $logger;
	protected $em;

	public function __construct(LoggerInterface $logger, EntityManagerInterface $entityManager) {
		$this->logger = $logger;
		$this->em = $entityManager;
		parent::__construct();
	}

	protected function configure()
	{
		$this
			->setName('app:version')
			->setDescription('Rebuilds the asset version mapping class')
			->addOption('test', 't', InputOption::VALUE_NONE, 'Controls whether any operations will be persisted or simply tested as in a dry-run')
		;
	}

	protected function execute(InputInterface $input, OutputInterface $output)
	{
		$this->logger->notice("Starting ".$this->getName()."(".$this->getDescription().")...");
		// ...
		$this->logger->notice($this->getName()." complete");
	}

}
```

**Possible Solution**  
?

**Additional context**  
Error after overriding constructor and adding dependencies as arguments:
`ERROR.console: (6924) Error thrown while running command "app:version -e dev". Message: "Command "app:version" is not defined." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"app:version\" is not defined. at .../Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:618)","command":"app:version -e dev","message":"Command \"app:version\" is not defined."} {"path":"bin/console app:version -e dev"}`

Error after reverting to default constructor and retreiving dependencies from container:
`ERROR.console: (9785) Error thrown while running command "app:version -e dev". Message: "The "app.service.system_info" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead." {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The \"app.service.system_info\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. at .../Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:337)","command":"app:version -e dev","message":"The \"app.service.system_info\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."} {"path":"bin/console app:version -e dev"}`

**Comment by xabbuh** [comment]
Are your commands registered as services? Are they properly tagged as console commands? What output do you get when running `bin/console debug:container "AppBundle\Command\VersioningCommand`?

**Comment by antfarmer** [comment]
I get the no services found error, even when declaring the following in services.yml:
```
  app.command.asset_version:
    class: AppBundle\Command\VersioningCommand
    tags:
      - { name: 'console.command', command: 'app:version' }
```
From this doc, https://symfony.com/doc/3.4/console.html#registering-the-command and https://symfony.com/doc/3.4/console/commands_as_services.html , I don't believe I even have to manually register the command; it should be auto-tagged as the resource directive should tell the container to pick up the commands from the Command sub-package, no?

**Comment by xabbuh** [comment]
This doesn't look right to me. Can you create an example application that makes it possible to reproduce?

**Comment by antfarmer** [comment]
Agreed, and this also seems to affect the auto-tagging of Twig Extensions as well. The app was upgraded from symfony 2.8 while using the Ocramius/ProxyManager for lazy loading. There must be some artifact from that setup that is affecting this. Another point is my commands extend from my own AbstractCommand class to centralize common functions; not sure if that has anything to do with it. Do I need to remove the ProxyManager package now, or can they coexist? I did try to setup a bare-bones app, but I could not get it to misbehave. Obviously there is something different, but I will have to keep whittling it down. I'm almost at the point where I might just revert and live with the deprecation notices, but there is a lot of time involved in upgrading to the new autowired design with private services.

**Comment by xabbuh** [comment]
Would it be possible to get access to the code of your application?

**Comment by antfarmer** [comment]
I will have to discuss with the company I'm working for, but this is a lot of code to wade through. What's weird is it is also affecting twig extensions too. Do you have any other advice on where to look or a better way of debugging the service container code?

**Comment by xabbuh** [comment]
The only advice without knowing more about your application is that I would first check your service definitions. Maybe some resources overlap each other and the definition that you did expect to be used is actually overridden by another. The `debug:container` command may be helpful.

**Comment by antfarmer** [comment]
Finally found the issue: there were two problems: I broke down the AppBundle reference in services.yml into separate references for each sub-packages and then I found there were typos in the namespace of a sub-package. The error message was not helping in this case. I find that sometimes error messages can lead you off course, especially in cases where there are two issues. Thanks for your help.

**Comment by xabbuh** [comment]
I am glad you were able to solve your problem. If you have concrete cases where you think error messages could be improved, I suggest to open new issues with a description of where one can get easily stuck and what would have helped in those cases.
