### ISSUE TITLE
Comparing Users Manually with EquatableInterface

### ISSUE THREAD

**Issue by bravik** [symfony/symfony#30425]
**Symfony version(s) affected**: 4.2.3

**Description**  
Documentation for user providers in section ["Understanding how Users are Refreshed from the Session"](https://symfony.com/doc/current/security/user_provider.html#understanding-how-users-are-refreshed-from-the-session)  says:

> At the end of every request (unless your firewall is stateless), your User object is serialized to the session. At the beginning of the next request, it's deserialized and then passed to your user provider to "refresh" it (e.g. Doctrine queries for a fresh user).  
>   
> Then, the two User objects (the original from the session and the refreshed User object) are "compared" to see if they are "equal".

And then in next section:

> Or, if you need more control over the "compare users" process, make your User class implement EquatableInterface. Then, your isEqualTo() method will be called when comparing users.

However,
However the `UserInterface $user` passed to `isEqualTo()` comes not from seriallized entity stored in session but from already refreshed entity from database. Thus it's always equal to User from database against which I'm trying to compare saved in session one, which clearly contradicts documentation.

I was initially trying to force log out already logged in user on certain conditions:
* If administrator has disabled it's account 
* If user roles changed (I would prefer just update, but there are only hacks for now as described here: #https://github.com/symfony/symfony/issues/12025)

**How to reproduce**  
1. Create a simple security configuration with `entity` user provider and a few roles stored in User entity
2. Implement `EquatableInterface` with your User
3. Log in
4. Change a role for example
5. `dd($this->user, $user)` in `public function isEqualTo(UserInterface $user)`
They would be equal since both are loaded from database.

**Comment by xabbuh** [comment]
`$this->user` inside the token must be the old user when it calls `isEqualTo()`. Can you create an example application that allows to reproduce what you experience?

**Comment by bravik** [comment]
I'm sorry. After a couple of days I couln't reproduce it. Everything is working as expected. Please delete this issue (

**Comment by xabbuh** [comment]
Thank you for the feedback. If you are experiencing this again, we can still reopen.
