### ISSUE TITLE
OptionsResolver error message with string[] as allowedTypes

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#30432]
**Symfony version(s) affected**: 3.4, maybe other versions too (not tested)

**Description**  
Error message when allowedTypes is an array contains `[]` but should not:
`The option "testme" with value array is expected to be of type "string[]", but one of the elements is of type "integer[]".`
It should be:
`The option "testme" with value array is expected to be of type "string[]", but one of the elements is of type "integer".`

**How to reproduce**  
```php
$resolver = (new OptionsResolver())
    ->setDefault('testme', [])
    ->setAllowedTypes('testme', ['string[]'])
    ->resolve(['testme' => ['test', 12]]);
```

**Comment by xabbuh** [comment]
Good catch, would you like to send a PR?

**Comment by dimabory** [comment]
@xabbuh I took a look at **OptionsResolver** component. Can you or someone else confirm how an error message should look like?

For instance, the current implementation implies that this code
```php
(new OptionsResolver())
	->setDefined('foo');
	->setAllowedTypes('foo', 'int[][]');
	->resolve([
		'foo' => [
			[1, true, 'str', [2, 3]],
		],
	]);
```

will throw an exception with message `The option "foo" with value array is expected to be of type "int[][]", but one of the elements is of type "boolean[][]".`
If we are good to go with `..., but one of the elements is of type "boolean".` I can open PR right now as much work already done.

**Comment by xabbuh** [comment]
For the example from the PR description the correct error message IMO indeed should be:

> The option "testme" with value array is expected to be of type "string[]", but one of the elements is of type "integer".

**Comment by dimabory** [comment]
I got it. Confirm case when allowed types consist multidimensional array notation (e.g. `string[][]`) and message should look like:
> The option "testme" with value array is expected to be of type "string[][]", but one of the elements is of type "integer".

**Comment by xabbuh** [comment]
I would have expected an error message containing all invalid types:

> [...] is expected to be of type "integer[][]", but is of type "integer|boolean|string".

**Comment by dimabory** [comment]
Hm, seems like it requires a huge effort. But I will see what I can do with it.

**Comment by steevanb** [comment]
Thanks!
