### ISSUE TITLE
Translation File Generation

### ISSUE THREAD

**Issue by dtfafard** [symfony/symfony#30443]
Hi guys,

very small bug but that took me 4 hours to find the fix. When generating the files using : 

`php bin/console translation:update --dump-messages --force fr`

It generates the files with the extension "yml" by default. 

According to : [https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations](https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations), the translation component only recognizes files with the extension "yaml".

I think this could be fixed quite easily.

Also, since your documentation recommends to use XLF, I think the script should generate the files in XLF too. Or change the documentation to mention that the default should be YAML/YML (I personally prefer YAML/YML). This would make everything consistent.

**Comment by GaryPEGEOT** [comment]
Has been done on https://github.com/symfony/symfony/pull/27935 :)

**Comment by javiereguiluz** [comment]
@GaryPEGEOT in #27935 we made XLF the default format ... but here another bug has been reported too: the command generates a `.yml` file which Symfony doesn't load because it only loads `.yaml`
