### ISSUE TITLE
[Console] The Application all() method inconsistent results of two executions.

### ISSUE THREAD

**Issue by yb199478** [symfony/symfony#30458]
**Symfony version(s) affected**: 4.2.4

**Description**  

The Application all() method inconsistent results of two executions.
The instruction corresponding to the alias is not listed when it is executed for the first time.

> maybe `CommandLoaderInterface->getNames()` returns the command name and the command alias is the correct behavior? But this is very strange. There is also no description on the interface comment that you need to return an alias.

**How to reproduce**  

- Create an test file: `tests/Symfony/ConsoleApplicationTests.php`, and copied test code.
```php
<?php

namespace App\Tests\Symfony;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\CommandLoader\CommandLoaderInterface;
use Symfony\Component\Console\Command\Command;

class ConsoleApplicationTests extends TestCase
{
    public function testApplicationMethodAll(): void
    {
        $app = new Application();
        $app->add(new SimpleCommand());
        $app->setCommandLoader(new TestCommandLoader());

        $first = $app->all();
        $second = $app->all();
        $this->assertEquals(count($first), count($second));
    }
}

class TestCommandLoader implements CommandLoaderInterface
{
    public function get($name)
    {
        if($name === "bar")
            return new BarCommand();
        
        if($name === "foo")
            return new FooCommand();

        throw new Exception();
    }
    public function has($name)
    {
        return $name === "bar" || $name === "foo";
    }
    public function getNames()
    {
        return ["bar", "foo"];
    }
}

class SimpleCommand extends Command
{
    protected function configure()
    {
        $this->setName("simple")
             ->setAliases(["simple-alias-1", "simple-alias-2"]);
    }
}

class FooCommand extends Command
{
    protected function configure()
    {
        $this->setName("foo")
             ->setAliases(["foo-alias-1", "foo-alias-2"]);
    }
}

class BarCommand extends Command
{
    protected function configure()
    {
        $this->setName("bar")
             ->setAliases(["bar-alias-1", "bar-alias-2"]);
    }
}
```

```shell
php bin/phpunit tests/Symfony/ConsoleApplicationTests.php
```

**Results**

> The command name we got the result. For easy display.

```php
$first = [ "help" , "list", "simple", "simple", "simple", "bar", "foo"];
$second = [ "help", "list", "simple", "simple", "simple", "bar", "bar", "bar", "foo", "foo", "foo" ];
```

The alias corresponding to the command in `$first` is not listed.

**Possible Solution**  
- [src/Symfony/Component/Console/Application.php](https://github.com/symfony/symfony/blob/f8664e77033a642c851b7a5728fb5368f92b1231/src/Symfony/Component/Console/Application.php#L696) #L696 - all()

```php
if (!$this->commandLoader) {
    return $this->commands;
}
$commands = $this->commands;
foreach ($this->commandLoader->getNames() as $name) {
    if (!isset($commands[$name]) && $this->has($name)) {
        $commands[$name] = $this->get($name);
    }
}
```

When there is no `commandLoader`, the returned commands map contains aliases(Expanded the alias in the `add()` method).

However, when `commandLoader` exists, if the command is not added, but through `has()`(passively added) the returned list will not have an alias command.

**Additional context**  

Maybe it was because I did not use it correctly and caused this problem? But this makes me feel very strange. I hope someone can help answer the question of what the correct behavior of this method is.

**Comment by yb199478** [comment]
From the like `getNamespaces()` method, `all()` should not return the alias map of the command.
This makes me wonder. Combined with other related contexts, The `all()` method should I return a command alias mapping?

- [src/Symfony/Component/Console/Application.php#L543](https://github.com/symfony/symfony/blob/f8664e77033a642c851b7a5728fb5368f92b1231/src/Symfony/Component/Console/Application.php#L543)
```php
public function getNamespaces()
{
    $namespaces = [];
    foreach ($this->all() as $command) {
        $namespaces = array_merge($namespaces, $this->extractAllNamespaces($command->getName()));

        foreach ($command->getAliases() as $alias) {
            $namespaces = array_merge($namespaces, $this->extractAllNamespaces($alias));
        }
    }

    return array_values(array_unique(array_filter($namespaces)));
}
```

**Comment by yb199478** [comment]
I retrieved the test case and did not find a suitable use case to protect this behavior.

**Comment by chalasr** [comment]
`CommandLoaderInterface` does not know about the `aliases` concept. 
The motivation behind `CommandLoaderInterface` is lazy-loading, it only maps command names to command _factories_, which means it can't use `Command::getAliases()` as it does not deal with command instances. 
Thus, if you try to run a command by using `bin/console some:alias` where `some:alias` is defined via `$this->setAliases()` in the command, the command won't be resolved and you will get a `CommandNotFoundException`. 
Basically, the right way to have aliases for a command wired by a `CommandLoaderInterface` implementation is to map the alias as a name (as if if it was a different command, but wiring the same command using the same factory). Using `setAliases()` should be avoided when using `CommandLoaderInterface` since aliases cannot be resolved on the first run.
And `Application::all()` return value must include aliases, to allow command resolution by alias when not using a `CommandLoaderInterface` (the non-lazy way aka `Application::add(new SomeCommand())`).
Hope it's clear enough

**Comment by yb199478** [comment]
Thank you very much for your answer.

The hidden concept of `all` and `getNamespaces` is not uniform. The latter will return the included alias command namespace regardless of whether it is a lazy-loading command.

Is there a short comment in the "all" method to indicate whether this hidden concept is better?

> I am very embarrassed to take up your time, because I am trying to rewrite the console to the c# version, so I want to understand some concepts.
