### ISSUE TITLE
[VarDumper] Dump in php log

### ISSUE THREAD

**Issue by ilyachase** [symfony/symfony#30460]
**Description**  
Hi guys. It is a often use-case for me to send some data in PHP log for debug purposes. `dump()` is useful, but it prints data straight, therefore you can often crash your layout or get "Headers already sent" error. Just wondering, can we add similar function for sending data in log, for example using `error_log`?

**Example**  
`dump_log($var1, $var2, $var3);`

**Comment by antonch1989** [comment]
I could work on this one

**Comment by ilyachase** [comment]
I can work on it myself, just asking is it a good idea?

**Comment by nicolas-grekas** [comment]
I'm not sure we would merge that: Symfony provides integration with Monolog/PSR-3, which is a much better logging infrastructure than `error_log()`. Low chance to be accepted IMHO.

**Comment by ilyachase** [comment]
@nicolas-grekas Don't understand why you mentioned about Monolog: VarDumper is not a tool for *logging*, it's for *debugging*. And for debugging purposes I suggest to add echoing in STDERR (now it only uses STDOUT).

**Comment by Randriamitsiry** [comment]
What about using Mapped Diagnostic Context?
Very useful if information you want to write in log come from many place

**Comment by Simperfit** [comment]
@ilyachase The point is, why don't you use monolog for this ? since you can pretty much log anything ?
I don't see why it would be better to reimplement something that monolog is doing greatly with the vardumper and with error_log ?

**Comment by nicolas-grekas** [comment]
A global function won't ever be accepted. Use a logger object instead.

**Comment by ilyachase** [comment]
@nicolas-grekas oh really? Seems that you are completely out of context.
`https://github.com/symfony/var-dumper/blob/master/VarDumper.php#L19`
`https://github.com/symfony/var-dumper/blob/master/Resources/functions/dump.php#L14`

**Comment by ilyachase** [comment]
> @ilyachase The point is, why don't you use monolog for this ? since you can pretty much log anything ?
> I don't see why it would be better to reimplement something that monolog is doing greatly with the vardumper and with error_log ?

I don't use monolog for what? Follow carefully:
1. There is `symfony/var-dumper` exists for some reason and purpose (I assume for dumping some data during development).
2. I use it just for this purpose. I don't need it on production. I don't need monolog, I don't need `dump` functions in my source code. Having `symfony/var-dumper` in my `dev-requirements` in composer i just enough.
3. Right now `symfony/var-dumper` **allready have two global functions**: `dump` and `dd`. And **their behaviour depends on environment** (CLI or web). So in CLI mode you have all the data dumped in `STDERR` stream, and in Web in `STDIN` in HTML format: https://github.com/symfony/var-dumper/blob/master/VarDumper.php#L38
4. Therefore, from the box you only have an option to use `CliDumper` or `HtmlDumper` and it depends on environment. But it often useful to dump your data in Web mode like when you are in CLI mode, to prevent breaking your HTML markup. But there is no such function.

And what is your point? May be we should delete `symfony/var-dumper` from github at all and all use monolog during development?

**Comment by xabbuh** [comment]
@ilyachase It is not clear to me what this feature request is about. First you were talking about logging. In regard to this I agree with @nicholasgrekas that it's probably not going to happen that we will add a global function related to it as there already is PSR-3 and Monolog which is much more powerful. Now you were also talking about switching between `CliDumper` and `HtmlDumper`. Can you clarify a bit what exactly you would like to see implemented?

**Comment by ilyachase** [comment]
@xabbuh  I'm sorry that it wasn't clear from my initial message, but I described my idea more carefully in previous message.

**Comment by xabbuh** [comment]
Since #25125 you control the formatter to be used with the `VAR_DUMPER_FORMAT` environment variable. Doesn't that solve the issue?

**Comment by ilyachase** [comment]
@xabbuh no. From the box you have helper functions like "just dump", "dump and die", but for dumping in stderr you must `VAR_DUMPER_FORMAT` every time?

**Comment by xabbuh** [comment]
You can easily write one yourself a function that populates the environment variable and calls `dump()` or `dd()` then if you find yourself frequently needing it. But so far I haven't heard before that this is a common use case. So I don't think we will be adding support for it in core.
