### ISSUE TITLE
[WebServer] server:start failed (OSX, php 7.3.2)

### ISSUE THREAD

**Issue by Plopix** [symfony/symfony#30471]
**Symfony version(s) affected**: v4.2.3
**PHP version**: PHP 7.3.2 on OS X installed with Brew. (pcntl present)

**Description**  
```bash
bin/console server:start 127.0.0.1:1664
```
=> does not start anything on PHP 7.3 (on 7.2 it is working as expected)

- `server:start` is working.
- I debugged and when I remove the `fork` that is working too.

**How to reproduce**  
```bash
composer create-project symfony/website-skeleton my_project
cd my_project
composer require server --dev
bin/console server:start 127.0.0.1:1664
```
Then `netstat -an | grep LISTEN | grep 1664` and you will see nothing.

As soon as I switch to PHP 7.2.15, it is working again.

**Additional context**  

I have tried to debug, using "file_put_contents" in the child (after fork).
The further I can go is in `createServerProcess`
This is going to be weird:
```php
        file_put_contents("/tmp/plop", "--".PHP_EOL, FILE_APPEND);
        file_put_contents("/tmp/plop", "Before PhpExecutableFinder - ".__LINE__.PHP_EOL, FILE_APPEND);
        $finder = new PhpExecutableFinder();
        file_put_contents("/tmp/plop", "After PhpExecutableFinder - ".__LINE__.PHP_EOL, FILE_APPEND);
```

Result is:
```
--
Before PhpExecutableFinder - 149
```

Even weirder, if I add debug in `PhpExecutableFinder` constructor

```php
    public function __construct()
    {
        file_put_contents("/tmp/plop", "Before new ExecutableFinder(); - ".__LINE__.PHP_EOL, FILE_APPEND);
        $this->executableFinder = new ExecutableFinder();
        file_put_contents("/tmp/plop", "Before new ExecutableFinder(); - ".__LINE__.PHP_EOL, FILE_APPEND);
    }
```

The result is THE SAME, which does not make any sense to me:

```
--
Before PhpExecutableFinder - 149
```

So I pushed the debug, trying weird things, I have removed all the comments in `PhpExecutableFinder.php` and magically it progressed

```
--
Before PhpExecutableFinder - 149
Before new ExecutableFinder(); - 9
```
I did the same for `ExecutableFinder.php`

```
--
Before PhpExecutableFinder - 149
Before new ExecutableFinder(); - 9
After new ExecutableFinder(); - 11
After PhpExecutableFinder - 151
```

But the command is still now working, the `new Process` is failing

```php
    private function createServerProcess(WebServerConfig $config)
    {
        file_put_contents("/tmp/plop", "--".PHP_EOL, FILE_APPEND);
        file_put_contents("/tmp/plop", "Before PhpExecutableFinder - ".__LINE__.PHP_EOL, FILE_APPEND);
        $finder = new PhpExecutableFinder();
        file_put_contents("/tmp/plop", "After PhpExecutableFinder - ".__LINE__.PHP_EOL, FILE_APPEND);
        if (false === $binary = $finder->find(false)) {
            throw new \RuntimeException('Unable to find the PHP binary.');
        }

        $xdebugArgs = ini_get('xdebug.profiler_enable_trigger') ? ['-dxdebug.profiler_enable_trigger=1'] : [];

        file_put_contents("/tmp/plop", var_export($xdebugArgs, true).PHP_EOL, FILE_APPEND);
        file_put_contents("/tmp/plop", var_export($finder->findArguments(), true).PHP_EOL, FILE_APPEND);

        file_put_contents("/tmp/plop", var_export($config->getAddress(), true).PHP_EOL, FILE_APPEND);
        file_put_contents("/tmp/plop", var_export($config->getRouter(), true).PHP_EOL, FILE_APPEND);

        $process = new Process(array_merge([$binary], $finder->findArguments(), $xdebugArgs, ['-dvariables_order=EGPCS', '-S', $config->getAddress(), $config->getRouter()]));

        file_put_contents("/tmp/plop", "PROCESS CONSTRUCTED".PHP_EOL, FILE_APPEND);
...
```

So I continued, it does not enter into the constructor at all. So I removed all the comment of `Process.php`, and I went further... and further removing those comments from files:
- PipesInterface
- AbstractPipes
- UnixPipes
- Process

And it finally worked ... but I am lost... I think that is a PHP bug.
I tried removing OPcache, but no change.

I then tried on Docker

```bash
docker run -it --rm php:7.3.2 /bin/bash
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar composer
apt-get update
apt-get install git zlib1g-dev
docker-php-ext-install zip pcntl
docker-php-ext-enable pcntl
./composer create-project symfony/website-skeleton my_project
cd my_project
../composer require server --dev
bin/console server:start 127.0.0.1:1664
```
=> IT WORKS.. so definitely something on Mac OS X, or PHP Brew...

Does someone reproduce this?

**Comment by kix** [comment]
This is due to a bug introduced in newer PHP builds on Homebrew. See:
https://github.com/symfony/symfony/issues/30328
https://github.com/bobthecow/psysh/issues/540#issuecomment-445706731
https://github.com/Homebrew/homebrew-core/issues/35491

**Comment by fabpot** [comment]
Let's close then.

**Comment by Plopix** [comment]
thx @kix, I still don't get why it worked when I removed those comments but who cares, that will be fixed at some point ;) `symfony local:server:start` works much better anyway ;-)

**Comment by Plopix** [comment]
FYI: `7.3.3` does not fix the issue.

**Comment by andreybolonin** [comment]
+1 sever:start is not working on php 7.3.3 macos

**Comment by krzysostry** [comment]
+1 server:start still not working on brew php 7.3.4 macOs (built: Apr 19 2019 00:20:56)

**Comment by MrNicodemuz** [comment]
Still an issue on the following version:
PHP 7.3.5 (cli) (built: May  2 2019 12:40:36) ( NTS )

**Comment by fabpot** [comment]
I would recommend people to use the Symfony CLI instead: https://symfony.com/doc/current/setup/symfony_server.html

**Comment by MrNicodemuz** [comment]
Symfony CLI works well on 7.3.5! 👍
