### ISSUE TITLE
ConstraintValidatorTestCase not compatible with PHPUnit 8

### ISSUE THREAD

**Issue by julien-maurel** [symfony/symfony#30476]
**Symfony version(s) affected**: 4.2.4

**Description**  
Class Symfony\Component\Validator\Test\ConstraintValidatorTestCase  is not compatble with PHPUnit8 because setup and teardown methods have no return type hint

**Possible Solution**  
Just add void return type hint on these methods

**Comment by xabbuh** [comment]
see #30474

**Comment by xabbuh** [comment]
closing here as #30474 was merged a while back
