### ISSUE TITLE
[DependencyInjection] Cannot set a service to public through autoconfigure unless _defaults are set

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/symfony#30492]
### Symfony version(s) affected

- `v4.2.3.2`
- `v4.1.9.1`
- `v4.0.7`
- `v3.4.7`
- `v3.3.9`

> Affected versions of [`symfony/skeleton`](https://github.com/symfony/skeleton) (basically all of them) rather than [`symfony/dependency-injection`](https://github.com/symfony/dependency-injection) - have not tested individual versions of the Dependency Injection component.

Probably not noticed in previous versions because `public: false` was in `_defaults` when creating a project from certain versions.

### Description
When autoconfiguring a service via the interface it implements, the visibility (`public` true/false) cannot be changed unless `services._defaults.public: false` has been set.

### How to reproduce

- Create a project from the latest version of [`symfony/skeleton`](https://github.com/symfony/skeleton) (zanbaldwin/symfony@ae5de659846e2ce1df228d726692df7cade4df97). Current version is `v4.2.3.2` at the time of this issue.
- Setup container configuration (zanbaldwin/symfony@2cfe1635d64cf5d4dd9cbb4f3b5f877923ff1ca5).
   1. Create `App\MyInterface`.
   2. Create `App\MyService` which implements `App\MyInterface`.
   3. Autoconfigure the interface in `App\Kernel::build()` with `$container->registerForAutoconfiguration(MyInterface::class)->setPublic(true);`
- View service using `bin/console debug:container MyService` and note that `Public` is set to `no`.

However:

- Modify `config/services.yaml` and add a default value of `public` (zanbaldwin/symfony@76ec173889b697d3fc6dd5ace9bdb5720ad60c6a):
  ```yaml
  services:
      _defaults:
          public: false
  ```
- Rerun command `bin/console debug:container MyService` to see that `Public` is now set to `yes`.

### Additional context

See branch [`zanbaldwin/symfony@bug/service-visibility-autoconfigure`](https://github.com/zanbaldwin/symfony/tree/bug/service-visibility-autoconfigure) for bug reproduced in minimal amount of steps (2 commits not including installing Symfony).

**Comment by nicolas-grekas** [comment]
I confirm: autoconfiguration currently apply only to tags, setters and bindings. In 3.4, only tags are supported - then 4.2 adds the last two. The logic is in `ResolveInstanceofConditionalsPass`.
Adding support for "public" could be done as a new feature.
BUT, why don't you use service locators instead? `public` should really *not* be used - because using it means using the container as a locator, which is discouraged practice.
With this reasoning, I'd recommend being extra careful before adding autoconfiguration for "public".

**Comment by zanbaldwin** [comment]
> Tested with `symfony/skeleton` version `4.2.4.1`.

| `services._defaults.public: false` | Auto configure `setPublic(true)` | Resulting visibility on `MyService` |
|---|---|---|
| Not Set | Not Set | `Public no` |
| Not Set | Set | `Public no` |
| Set | Not Set | `Public no` |
| Set | Set | `Public yes` |

If auto configuration only applies to tags, setters and bindings, then how can the visibility of `App\MyService` be changed to `public: true` through auto configuration (but only when a value is set for `services._defaults.public`)?
Perhaps auto configuration shouldn't be allowed to modify a service's visibility, but the current behaviour is definitely inconsistent.

I agree that allowing services to be made public is not best practice for most projects - we only found this out because we make event processors public to be our entry points in our worker scripts, and removed the `services._defaults.public` setting in [`config/services.yaml` as per the `symfony/framework-bundle` recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/services.yaml) when upgrading to `4.2`.

They were written a while ago and will most likely rewritten using service locators when we migrate to the messenger component.  If the decision to not allow visibility changes via auto configuration, then that's fine - we'll just use service locators a little faster than when we would have eventually got round to it.

---

I had a quick glance through the compiler pass, but couldn't see how the visibility of the `.abstract.instanceof.` would be inherited depending on what defaults were already set - if I'm even understanding it correctly.

**Comment by iquito** [comment]
I was also hit by this. I wanted to set some services inheriting an interface to public via `_instanceof` to make sure they are not inlined/removed and always available in tests. Only through this issue and other similar reported issues (https://github.com/symfony/symfony/issues/32193 and https://github.com/symfony/symfony/issues/36782) did I figure out that setting public to false in `_defaults`  would solve it - this was very unexpected to me, I would have never figured it out myself.

**Comment by fancyweb** [comment]
I just try to reproduce the bug but it seems that it now works as expected on the master branch. Could you please test it on your side to confirm it? @zanbaldwin

**Comment by nicolas-grekas** [comment]
Since this is an old issue, I'm closing it as hopefully solved. Please report back if that's not the case.

**Comment by ludekbenedik** [comment]
Hi,
the problem still remains in Symfony 4.4.27. Symfony 5.3.4 is ok.

```php
$container->registerForAutoconfiguration(SomeInterface::class)
    ->setPublic(true)
;
```

```yaml
services:
    _defaults:
        autowire:       true
        autoconfigure:  true
        public:         false # sf bug - if not set then autoconfiguration does not set "public: true"!

    SomeService: ~ # service implements SomeInterface. No matter if the service is defined explicitly or through resource
```
