### ISSUE TITLE
debug:autowiring doesn't show classes when run without --all

### ISSUE THREAD

**Issue by disider** [symfony/symfony#30493]
**Symfony version(s) affected**: 4.2.4

**Description**  
When there is an autowirable class, that could be shown via debug:autowiring, an exception should be expected if the '--all' flag is not set and the passed argument doesn't match the alias.

**How to reproduce**  
Create a new project:

```
  symfony new test
  cd test
```

Create a simple class Test.php in src. This is autowired.

Executing 

```
  bin/console debug:autowiring Test
```

it doesn't show the class, nor it returns an exception. This is because, since the service has no alias, there is no text added to the output here: https://github.com/symfony/framework-bundle/blob/master/Command/DebugAutowiringCommand.php#L114

**Possible Solutions**  
Throw an exception in the line above.
Print something that says "There are matching services but without that exact match".
Print the class anyway.

**Comment by dbrumann** [comment]
I can't reproduce the issue. What does the content of the file look like?

```
➜  issue30493 git:(master) ✗ bin/console debug:autowiring Test --all

Autowirable Types
=================

 The following classes & interfaces can be used as type-hints when autowiring:
 (only showing classes/interfaces matching Test)

 App\Test
```

**Comment by soufianZantar** [comment]
I confirm the bug the command must return exception or the no aliased service.

I suggested to return the aliased and no aliased when adding the search argument and i have added the PR.
