### ISSUE TITLE
Use APP_ENV when running yarn encore

### ISSUE THREAD

**Issue by Isinlor** [symfony/symfony#30503]
Would it be possible to utilize `APP_ENV` variable when running `yarn encore`?

So instead of `yarn encore dev` or `yarn encore production` I would do `yarn encore`. 

More explicit option would be `yarn encore env` that selects dev or production based on `APP_ENV`.

This would avoid duplication of install/deploy configurations between production and development.

Rest of Symfony is doing that already.

**Comment by nicolas-grekas** [comment]
Can you open this issue on the https://github.com/symfony/webpack-encore repository please? I think that's a better place to do so.
