### ISSUE TITLE
[DI] Repository wiring problem in TEST environment

### ISSUE THREAD

**Issue by adrx** [symfony/symfony#30529]
**Symfony version(s) affected**: 4.2.4 and probably earlier versions.

**Description**  
Under certain conditions, a project running in the TEST environment throws an exception due to symfony incorrectly setting up a repository based on Service Entity Repository:

TypeError: Argument 1 passed to App\Repository\DummyARepository::__construct() must implement interface Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\ORM\EntityManager given, called in C:\xampp\htdocs\ser_bug\vendor\doctrine\orm\lib\Doctrine\ORM\Repository\DefaultRepositoryFactory.php on line 68.

**How to reproduce**  
It took a while to identify what it was in my real project that provided the conditions in which this bug appeared. I have created a simple demo project that triggers the bug reproduceably. It can be found at 

https://github.com/adrx/symfony_ser_bug.

I am not capable of finding the source of the problem in the symfony code. I hope this demo of the bug will assist more capable folks to fix the bug so that my project's code behaves the same way in the TEST environment as in dev or prod.

**Comment by colinedmz** [comment]
I think it is related to this bug => [#29810](https://github.com/symfony/symfony/issues/29810)

**Comment by kevinpostma** [comment]
I have a lot of webtestcases to test the input and output of my API. All my tests where running fine untill i started registering doctrine entitylisteners to my entities. After registering a entity listener i got the following message: 

```
1) App\Controller\TaskControllerTest::testCreate
TypeError: Argument 1 passed to App\Repository\ProjectRepository::__construct() must implement interface Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\ORM\EntityManager given, called in /Volumes/Data/Projects/php/sandbox/pplanner/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 68
```
I am on symfony version v.4.2.5

**Comment by adrx** [comment]
This bug is gone in sf 4.3.4 (see branches bundle_434 and no_bundle_434 in the demo project at 

[https://github.com/adrx/symfony_ser_bug](url)

So I am closing this issue.
