### ISSUE TITLE
BC break in MarkingStoreInterface

### ISSUE THREAD

**Issue by jenschude** [symfony/symfony#30524]
**Symfony version(s) affected**: 4.3.0-dev

With the PR #29146 the MarkingStoreInterface has been changed. This is a BC break according to https://symfony.com/doc/current/contributing/code/bc.html#using-our-interfaces

**How to reproduce**  

The issue can be seen here https://3v4l.org/ch3JX

**Possible Solution**  

A possible fix is to introduce a new MarkingStoreInterface extending the old one with the newly added parameter. See https://3v4l.org/8C8Gc

**Comment by xabbuh** [comment]
I suggest we instead trigger a deprecation when an implementation of this interface does not have the second argument so that we can add it in 5.0.

**Comment by lyrixx** [comment]
See: https://github.com/symfony/symfony/pull/30530

**Comment by lyrixx** [comment]
I choose to use the reflection to cover all cases.

@jenschude Thanks for your feedback :+1:

**Comment by jenschude** [comment]
Actually kudos to @nikossvnk for finding the issue ;)
