### ISSUE TITLE
[Messenger][RFC] Generic TransportConfig stamp

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#30558]
This relates to #30540, where we're pushing forward the last details to make Messenger really shine.

I think that a few transport-related options should be universally supported by all/whatever transports Symfony offers. For example:

* message priority
* number of retries
* delivery delay

The idea is to identify a few "features" that are *typically* standard in a transport (e.g. AMQP), and them create a `TransportConfiguration` stamp that allows you to configure those on a message-by-message basis. We would then work to make sure all transports support at least these features (or, if it's not possible/unreasonable, document which transports support which features, at least).

Thoughts?

**Comment by javiereguiluz** [comment]
Just for reference purposes: in Java's JMS 2.0, the clients using the `MessageProducer` interface can specify:

* a default delivery mode
* priority
* time to live
* delivery delay

https://docs.oracle.com/javaee/7/api/javax/jms/MessageProducer.html

**Comment by gggeek** [comment]
Not sure about "delivery delay", but message TTL is supported at least by RabbitMQ for AMQP, as well as AWS queues

**Comment by weaverryan** [comment]
delivery delay *can* be accomplished in AMQP by using a dead-letter exchange. So, we *can* do that - AMQP shouldn't be a problem with that - it'll be implemented in #30557

**Comment by nicolas-grekas** [comment]
add "routing_key"

**Comment by sroze** [comment]
This (retries and delays) has been implemented for the AMQP and Doctrine transports. I'm closing this RFC then. Let's open another one for more specific points :) Thank you @weaverryan!
