### ISSUE TITLE
[Validator] File constraint always violated when uploading multiple files

### ISSUE THREAD

**Issue by panda098** [symfony/symfony#30575]
**Symfony version(s) affected**: 4.2.3

**Description**  
Ubuntu 18.04
PHP 7.2.15

When 'multiple' option is enabled and `File` constraint is set, validation always ends with `ConstraintViolation`.

**How to reproduce**  
```
$uploadForm = $this->createFormBuilder()
        ->add('files', FileType::class, [
            'multiple' => true,
            'constraints' => [
                new File([
                    'mimeTypes' => 'application/pdf'
                ])
            ]
        ])
        ...
```
Following error message appears after submitting:
> This value should be of type string

**Comment by xabbuh** [comment]
The `File` constraint can only be applied to single objects. If you are validating an array, you need to wrap it in a [`Collection`](https://symfony.com/doc/current/reference/constraints/Collection.html) constraint.

**Comment by stof** [comment]
Well, you probably need a [`All`](https://symfony.com/doc/current/reference/constraints/All.html) constraint rather than a `Collection` one, if you want to apply the Field constraint on each element of the array.

**Comment by xabbuh** [comment]
indeed, I updated my comment above

**Comment by panda098** [comment]
Ok, i see. Thanks for a quick response!

**Comment by nuryagdym** [comment]
Here is how you configure in Form builder:

```php
//use Symfony\Component\Validator\Constraints\All;
$builder->add('files', FileType::class, [
    'label' => 'files',
    'multiple' => true,
    'constraints' => [
        new Count(['max' => 5]),
        new All([
            new File([
                'maxSize' => '2048k',
                'mimeTypes' => [
                    'image/jpeg',
                    'image/png'
                ],
            ])
        ])
    ],
    'attr' => [
        'accept' => '.jpg, .jpeg, .png'
    ],
]);
```

**Comment by JENNYPCHEN** [comment]
i had a similar problem that i forgot all use new All but now after adding it, it creates a problem. even though i have set it to require false, every time when i not upload a file; it said ' This value should be of type iterable.' could anyone so kind to give me a hint what to do please

**Comment by petr-panoska** [comment]
> i had a similar problem that i forgot all use new All but now after adding it, it creates a problem. even though i have set it to require false, every time when i not upload a file; it said ' This value should be of type iterable.' could anyone so kind to give me a hint what to do please

Hi, please, can you post your code and symfony version?
