### ISSUE TITLE
Cache: RedisAdapter doesn't support AWS ElastiCache with secure connection

### ISSUE THREAD

**Issue by alex-vasilchenko-md** [symfony/symfony#30573]
**Symfony version(s) affected**: 4.2

**Description**  
It's impossible to connect to AWS Elasticache using https://github.com/nrk/predis that supports rediss schema: http://www.iana.org/assignments/uri-schemes/prov/rediss
As a result you get an exception "Unsupported DSN: rediss://{aws-elasticache-uri}"

**How to reproduce**  
You need to set up cache in framework.yml like this:
```
cache:
        app: cache.adapter.redis
        default_redis_provider: 'rediss://{aws-elasticache-uri}'
```

As client you need to set up Predis\Client

On init app will throw InvalidArgumentException.

**Possible Solution**  
Add rediss dsn support here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L135

And here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Traits/RedisTrait.php#L83

**Comment by nicolas-grekas** [comment]
@alex-vasilchenko-md would you be able to submit a PR to add support for this?

**Comment by a-deeb** [comment]
Hi, can I help out and add the DNS support in those files?
