### ISSUE TITLE
[DI] Autowiring failures failing fatally with __toString exception

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#30571]
**Symfony version(s) affected**: I believe `master` branch only

**Description**  
Autowiring failures give this exception:

> Error: Method class@anonymous::__toString() must not throw an exception, caught Symfony\Component\DependencyInjection\Exception\AutowiringFailedException:

**How to reproduce**  

In a standard project, try to autowiring using an interface that doesn't exist - e.g.

```php
<?php

namespace App\MessageHandler;

use Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactoryInterface;

class FooHandler
{
    public function __construct(ArgumentMetadataFactoryInterface $foo)
    {
    }
}
```

**Possible Solution**  
I believe this is just an edge-case/bug from #29108

**Comment by nicolas-grekas** [comment]
Can you share a reproducer please?
Where is this "__toString" from?

**Comment by nicolas-grekas** [comment]
See #30589, please confirm because I don't have a reproducer :)

**Comment by weaverryan** [comment]
Here's a reproducer! https://github.com/weaverryan/symfony-autowiring-error-reproducer

**Comment by nicolas-grekas** [comment]
Sorry, cannot reproduce, all is fine with this repo on my machine.

**Comment by sadikoff** [comment]
Reproducer worked perfectly, I can confirm. PHP 7.2.15
<img width="636" alt="Screen Shot 2019-03-17 at 17 45 49" src="https://user-images.githubusercontent.com/213810/54493781-87365280-48dc-11e9-97d1-b67877ef2820.png">

**Comment by nicolas-grekas** [comment]
xdebug is at fault, looking for a workaround

**Comment by Toilal** [comment]
It seems the implemented workaround doesn't work with newly released xdebug 3, as I hit this exact issue after installing it on my Dockerfile. Locking the xdebug version to <3 is the current works as a workaround.

**Comment by stof** [comment]
@Toilal please open a new issue rather than commenting on an issue closed more than 1 year ago. Otherwise your report will be lost

**Comment by Toilal** [comment]
Thanks stof, but I'm still on v4.3.x which is not supported anymore, so I won't open a new issue. Time to upgrade to LTS :) (Another project on 4.4 LTS works properly).
