### ISSUE TITLE
[Security][RFC] Exception thrown on call to isGranted without token

### ISSUE THREAD

**Issue by mdeboer** [symfony/symfony#30609]
Years back there was a feature request regarding the AuthenticationCredentialsNotFoundException that was thrown when `is_granted` was used in Twig without an existing token. The workaround was to check for the token first, which was later fixed in PR #15953.

However instead of not throwing the exception at all the fix was Twig specific by catching the exception. Now we have inconsistent behaviour of `is_granted` in Twig and `isGranted` of the AuthorizationChecker.

Can't we just remove [the line that throws the exception](https://github.com/symfony/security-core/blob/d1cce491ad065715b5a5f9054e704700c6db2d7d/Authorization/AuthorizationChecker.php#L49) and return false instead? One, because the return type is a boolean and two because the method name is an "isser" and suggests a boolean return type instead. Exceptions are not expected to be thrown in this case, or is that just me?

I would gladly provide a PR but I want your thoughts on this why the exception gets thrown in the first place.

**Comment by linaori** [comment]
I'm in no strong opinion in either directly. I _am_ in favor of _moving_ the exception to `getToken()` instead.

**Comment by mdeboer** [comment]
> I'm of no strong opinion in either methods. I _am_ in favor of _moving_ the exception to `getToken()` instead.

Hmm, but that returns a nullable token. Null indicating that there is no token. So again, I see no reason why this exception exists. Sure you can catch it somewhere but the firewall already handles this when you access a page that requires authentication.

Could you explain why you would want to move it instead of [b]re[/b]moving it?

**Comment by linaori** [comment]
The idea is that a Token can be nullable, but what benefit does that bring? You want a token, otherwise you wouldn't be asking for it. If you don't have a token while asking for it, you have probably miss-configured your security config (most likely forgot `IS_AUTHENTICATED_ANONYMOUSLY`).

In which scenario is a token _really_ optional?

**Comment by mdeboer** [comment]
> The idea is that a Token can be nullable, but what benefit does that bring? You want a token, otherwise you wouldn't be asking for it. If you don't have a token while asking for it, you have probably miss-configured your security config (most likely forgot `IS_AUTHENTICATED_ANONYMOUSLY`).
> 
> In which scenario is a token _really_ optional?

In cases where you serve both authenticated and unauthenticated requests and want to check for roles. Say everyone gets result A (both authed and unauthed) and only authed users with ROLE_ADMIN get result B.

Moving the exception to getToken would mean the exception would still be thrown when checking for a role with isGranted and the problem just moved. Imho you should then catch the exception in isGranted because all you want to know is whether a certain role is granted, which can be intentional like in the situation above.

I rather see the exception removed as imho it's not the job of getToken nor isGranted to detect a possible misconfiguration. The definition of getToken can remain the same (nullable) and isGranted can return false instead of an exception. A small change :)

**Comment by linaori** [comment]
When the `getToken()` is null, you'll never figure out why, which hurts DX. The `getToken()` should always return a token in my opinion, but that's not feasible in the current setup. Perhaps this is another topic that can be discussed during the hackathon.

**Comment by curry684** [comment]
Agreed that, for DX, there should always be a token, and `is_granted` should never throw.

Perhaps @wouterj could integrate this request into https://github.com/symfony/symfony/issues/30765?

**Comment by javiereguiluz** [comment]
@linaori one use case for this (although not very common I must admit) is when your app works both with and without security enabled. In some bundle, [we had to create our own AuthorizationChecker](https://github.com/EasyCorp/EasyAdminBundle/pull/2829/files#diff-8829abd4a086fbc746623046e2afa1bc) to add a try...catch that avoids the exception.

**Comment by linaori** [comment]
@javiereguiluz there's always the possibility to define `anonymous: true`. In this scenario I would recommend to make a clear separation between: _"Security is present and (can be) enabled, thus require anonymous tokens"_ and _"Security is not enabled, thus replace the authorization checker by a dummy"_.

Making code that *might* have a token is imo the wrong solution, as it will make it unclear what the intention is and might cause bugs if indeed the security was supposed to be enabled.

**Comment by wouterj** [comment]
I think this one can be closed. When using the experimental security system, no exception is thrown when there is no token set (as anonymous tokens has been removed). See #36574
