### ISSUE TITLE
[Form] Missing error when value is submitted to a disabled field

### ISSUE THREAD

**Issue by enumag** [symfony/symfony#30613]
**Symfony version(s) affected**: all

**Description**  

When a form field is disabled but a value is submitted to it regardless, the value is silently ignored. This can be confusing to the user - when he opened the form the field was not disabled but something changed in the system while he was filling it so the field is disabled now. The value is then silently ignored but the user gets no notification about the problem.

**How to reproduce**  

Create a form field that has the `'disabled'` option active conditionally. Open the form in one window while the field is enabled, then do something in another window causing it to be disabled and then submit the form in the first window.

**Possible Solution**  

Submitting a value into a disabled field should cause a validation error on the form field in question so that the user knows about the change.

**Comment by xabbuh** [comment]
Thank you for reporting. I am closing here nonetheless as this was already reported in #27217. Thank you for understanding.

**Comment by enumag** [comment]
I'm not sure this is a duplicate. In my case it's not the entire form that is disabled, just one field. But maybe it's the same problem internally.

**Comment by xabbuh** [comment]
Yes, under the hood the Form component doesn't make a difference if a disabled form is the root form or one of its children.
