### ISSUE TITLE
Invalid mapping since upgrade 3.4.23 to 4.2.4

### ISSUE THREAD

**Issue by MWMathieu** [symfony/symfony#30627]
**Symfony version(s) affected**: 4.2.4

**Description**  
Since i upgrade only symfony/symfony 3.4.23 to 4.2.4, some entities (but not all) are not mapped.
When i try d:s:u --complete --dump-sql some tables flag for DROP.

**How to reproduce** 

Mapping entities with doctrine listener on event : loadClassMetadata.
Service tags : - { name: doctrine.event_subscriber, priority: 250 }

    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs)
    {
              $metadata = $eventArgs->getClassMetadata();
              $className = $metadata->getName();
              echo $className;
    }

I can see some entities but not all.

**Additional context**  
Related issue : https://github.com/symfony/symfony/issues/29289

**Comment by MWMathieu** [comment]
I tried to used symfony/depency-injection master version but nothing change.

**Comment by MWMathieu** [comment]
@xabbuh Can you help me please ?

**Comment by MWMathieu** [comment]
When i check with php bin/console doctrine:mapping:info all my classes present !

**Comment by xabbuh** [comment]
I have no idea what's happening there, but having an example application that allows to reproduce the issue may help others to understand it.

**Comment by MWMathieu** [comment]
It's impossible to do a project to reproduce this bug.

Doctrine yaml mapping inside bundle and eventListener on event loadClassMetadata.

Doctrine yaml mapping work perfectly but my class don't fire the loadClassMetadata event.

**Comment by xabbuh** [comment]
I am afraid that not being able to reproduce will probably mean that we won't be able to help.

**Comment by MWMathieu** [comment]
@xabbuh After long time search i found the source of my problem : 

If i put my event listener definition in services.yaml it work perfectly.
If i put my event listener definition in a listener.yaml and i import it in services.yaml it don't work perfectly, listener called but metadata class is not ok.
