### ISSUE TITLE
Make RedisAdapter TagAware by using native Redis Sets

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony#30624]
The only way to have a cache adapter with tagging features in symfony currently is to explicitly create a TagAwareAdapter backed by some other cache adapter.

However, redis does have **SETS**, see https://www.compose.com/articles/how-to-handle-tagged-data-with-redis-sets/ and the [official docs](https://redis.io/commands/#set)

Shouldn't it be possible to include this into the RedisAdapter just from the beginning? I'd expect massive performance improvements from this.

**Comment by dmaicher** [comment]
See https://github.com/symfony/symfony/pull/30370 ? :blush:

**Comment by nicolas-grekas** [comment]
You're not the only one wondering about this, see https://github.com/symfony/symfony/pull/30370
Would you mind reviewing and trying that PR and give feedback on your findings there?

**Comment by flaushi** [comment]
Ah wow, I did not search well enough...
I will try to do that
