### ISSUE TITLE
Authentication by external API

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#30623]
**Description**  
For an real world application im using an API to authenticate that is build in symfony as well and handles all the roles and al other security things for the frontend i want to use the symfony 4 framework as well and that it use the authentication over the API.
The API will provide the authentication user, token and roles so the frontend framework can use this to signin.
In the previous this is possible but since all class that could have do this is deprecated and uses guard which requires an user entity what i don't want because i don't want duplicate user databases because it's already in the API.

**Example**  
So my idea was an authenticator class to provide the support and authentication the authentication will returns the required userinterface with the username and roles to fake the user identity so it can log in the user and use all the security features like '@security'

**Comment by javiereguiluz** [comment]
Have you tried to solve this issue creating a custom authenticatiion provider? (https://symfony.com/doc/current/security/custom_authentication_provider.html) Or maybe even a "remote_user" based authentication? (https://symfony.com/doc/4.1/security/auth_providers.html#security-remote-user)  Not sure if possible in your case.

**Comment by dvdknaap** [comment]
@javiereguiluz yes i already tried but it's not what i'm looking for, i've created an created an workaround to make it work but it's not that pretty.

I've created an own class that extends 'AbstractFormLoginAuthenticator' 
`
class MyLoginAuthenticator extends AbstractFormLoginAuthenticator
{
    /** @var RouterInterface */
    private $router;

    /** @var CsrfTokenManagerInterface */
    private $csrfTokenManager;

    /** @var TokenStorageInterface */
    private $token;

    /** @var UserProvider */
    private $userProvider;

    /**
     * MyLoginAuthenticator constructor.
     *
     * @param RouterInterface           $router
     * @param CsrfTokenManagerInterface $csrfTokenManager
     * @param TokenStorageInterface     $token
     * @param UserProvider              $userProvider
     */
    public function __construct(
        RouterInterface $router,
        CsrfTokenManagerInterface $csrfTokenManager,
        TokenStorageInterface $token,
        UserProvider $userProvider
    ) {
        $this->router = $router;
        $this->csrfTokenManager = $csrfTokenManager;
        $this->token = $token;
        $this->userProvider = $userProvider;
    }

    /**
     * @param Request $request
     *
     * @return bool
     */
    public function supports(Request $request): bool
    {
        return $request->attributes->get('_route') === 'login'
            && $request->isMethod('POST');
    }

    /**
     * @param Request $request
     *
     * @return
     */
    public function getCredentials(Request $request)
    {
        $loginParams = $request->request->get('login');

        $credentials = [
            'email'      => $loginParams['emailAddress'],
            'password'   => $loginParams['password'],
            'csrf_token' => $loginParams['_token'],
        ];

        if ($request->hasSession() === false) {
            return new RedirectResponse($this->getLoginUrl());
        }

        $request->getSession()->set(
            Security::LAST_USERNAME,
            $credentials['email']
        );

        return $credentials;
    }

    /**
     * @param array                 $credentials
     * @param UserProviderInterface $userProvider
     *
     * @return UserProvider
     */
    public function getUser($credentials, UserProviderInterface $userProvider): UserProvider
    {
        $token = new CsrfToken('authenticate', $credentials['csrf_token']);

        if (!$this->csrfTokenManager->isTokenValid($token)) {
            throw new InvalidCsrfTokenException('Invalid token, refresh page and try again');
        }

        $user = null;
// This check is now hard codes but will be received by an external api
        if ($credentials['email'] !== 'demo@test.com') {
            // fail authentication with a custom error
            throw new AuthenticationException('Email could not be found.');
        }

        $this->userProvider
            ->setEmail($credentials['email'])
            ->setPassword($credentials['password'])
            ->setRoles(['ROLE_USER'])
            ->setSalt('')
        ;

        return $this->userProvider;
    }
`
The 'UserProvider' class implements UserInterface and saves the login in an session, symfony is not remember it on it's own so i had to create the session part to remember it

security.yaml
`security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        webservice:
            id: App\Security\User\WebserviceUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: webservice
            guard:
                authenticators:
                    - App\Security\MyPureLoginAuthenticator
`

The class 'WebserviceUserProvider' is required by symfony but is an empty class that implements 'UserProviderInterface'

**Comment by mdeboer** [comment]
> **Description**
> For an real world application im using an API to authenticate that is build in symfony as well and handles all the roles and al other security things for the frontend i want to use the symfony 4 framework as well and that it use the authentication over the API.
> The API will provide the authentication user, token and roles so the frontend framework can use this to signin.
> In the previous this is possible but since all class that could have do this is deprecated and uses guard which requires an user entity what i don't want because i don't want duplicate user databases because it's already in the API.
> 
> **Example**
> So my idea was an authenticator class to provide the support and authentication the authentication will returns the required userinterface with the username and roles to fake the user identity so it can log in the user and use all the security features like '@security'

I try to understand your problem but I find it very hard to read. It's not quite clear whether you've run into a problem (possibly a bug or BC break) or whether you propose an idea to simplify this authentication scenario (feature request).

As I see it you basically need to write your own user provider, just like it says in the documentation:

> Most applications don't need to create a custom provider. If you store users in a database, a LDAP server or a configuration file, Symfony supports that. However, if you're loading users from a custom location (e.g. via an API or legacy database connection), you'll need to create a custom user provider.

Also check whether you can use OAuth for your application purposes. It supports a few different authentication methods which might be of use.

**Comment by Simperfit** [comment]
@dvdknaap is it ok for you ?

**Comment by curry684** [comment]
I completely agree with @mdeboer that the scenario you describe sounds like something that should be handled using signed JWT tokens, best distributed using OAuth. Otherwise if you really want to hack it into your code directly implementing a user provider is indeed the way to go.

I don't really see a feature request here, the tools you need are already there in the framework.

**Comment by xabbuh** [comment]
Closing as explained, please refer to one of the [support channels](https://symfony.com/support) if you need further help. Thank you for understanding.
