### ISSUE TITLE
Forms, collection data transformers

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#30622]
**Symfony version(s) affected**: 3.4.23

**Description**  

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('arr', 'Symfony\Component\Form\Extension\Core\Type\CollectionType', [
                'entry_type' => TextType::class,
                'allow_add' => true
            ])
           ;

        $builder->get('arr')
            ->addModelTransformer(new CallbackTransformer(
                function ($value) {
                    return json_decode($value, true);
                },
                function ($value) {
                    return json_encode($value);
                }
            ));
    }

Expected argument of type "array or (\Traversable and \ArrayAccess)", "string" given

Why didn't convert the string to an array?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by mayro** [comment]
@xabbuh  Done https://github.com/symfony/symfony/issues/31041  Thank you
