### ISSUE TITLE
Call the __toString func from  Request, both the POST data  the request disappear

### ISSUE THREAD

**Issue by HongjiangHuang** [symfony/symfony#30644]
**Symfony version(s) affected**:4.0

**Description**  
After I called the __toString method in Request, I found that POST data disappeared.

**How to reproduce**  
ps: 
```
$symfony_request = SymfonyRequest::create(
    "http://test.wkcoding.com/common/member/login",
    "POST",
    [
      'username' => 'abc',
      'password' => 'xxasd%'
    ],
    [],
    [],
    $_SERVER,
    null
 );

echo ((string)$symfony_request);


result:


POST /common/member/login HTTP/1.1
Accept:          text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset:  ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Language: en-US,en;q=0.8
Content-Type:    application/x-www-form-urlencoded
Host:            test.wkcoding.com
Origin:          test.wkcoding.com
User-Agent:      Slim Framework
```

**Possible Solution**  
According to the PSR7 specification or HTTP RFC, the getBody function returns the data in the request including $POST or File stream ?

**Comment by xabbuh** [comment]
The `Request` class does not implement the PSR-7 `RequestInterface`.

**Comment by HongjiangHuang** [comment]
Does not implement the PSR specification, it should also comply with HTTP RFC

**Comment by xabbuh** [comment]
I don't understand how the `__toString()` method is related to any HTTP RFC.

**Comment by HongjiangHuang** [comment]
The generated string must satisfy the http protocol? Currently it will cause some data loss

**Comment by xabbuh** [comment]
Why should it? The method is not supposed to be used that way.

**Comment by ro0NL** [comment]
half though :)

https://github.com/symfony/symfony/blob/59f20ad8fdd4d261fe752302918102adf60e0fb9/src/Symfony/Component/HttpFoundation/Request.php#L513-L516

so if there's content it's included (as expected probably). To avoid the inconsistency... we could ditch __toString as well :/

**Comment by HongjiangHuang** [comment]
@xabbuh So what does this method do?

**Comment by xabbuh** [comment]
It still returns a string representation of the request. But it only returns the body if the content was set explicitly. I would simply not use this method at all and I rather tend to agree with @ro0NL that we may want to consider to remove it at some point.

**Comment by HongjiangHuang** [comment]
Thank you for your answer.
