### ISSUE TITLE
[MESSENGER] Worker fail in loop on handling empty message

### ISSUE THREAD

**Issue by SukachVitally** [symfony/symfony#30649]
**Symfony version(s) affected**: 4.2

**Description**  
Messenger worker fail after handling message with empty body (or headers) and restart this process in loop. Other messages in queue become blocked. 
No way to catch this exception in middleware or handler.

**How to reproduce**  
1. Start worker `php bin/console messenger:consume-messages some_transport`.
2. Add message with empty headers to queue.
3. Worker fail and restart handling invalid message in loop.

**Possible Solution**  
1. Add additional catch block for `Symfony\Component\Messenger\Exception\InvalidArgumentException`  to [reject message](https://github.com/symfony/messenger/blob/4.2/Transport/AmqpExt/AmqpReceiver.php#L63).
2. Add error handler for serializer in `Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceiver`

**Additional context**

**Comment by weaverryan** [comment]
I'm not sure if we should fix this or not in 4.2, but this is fixed in master (so, 4.3). In master, if a message fails to be decoded, we catch that and reject the message.

If we want to fix this temporarily in 4.2, in `AmqpSender`, we could catch `UnexpectedValueException` (which is what Symfony's serializer will throw if there is a problem decoding) and then reject.

But, as a mentioned, this is fixed in master :).

**Comment by SukachVitally** [comment]
Its looks broken even on master branch.

`InvalidArgumentException` exception will be thrown before Symfony serializer handling.
https://github.com/symfony/messenger/blob/master/Transport/Serialization/Serializer.php#L66

And this exception in not catchable in `AmqpReceiver`.
https://github.com/symfony/messenger/blob/master/Transport/AmqpExt/AmqpReceiver.php#L66

**Comment by weaverryan** [comment]
@SukachVitally You're right! We've covered the situation where the format of the message is invalid, but not the situation where the encoded data is empty. Those InvalidArgumentException should probably be MessageDecodingFailedException.
