### ISSUE TITLE
Add PropertyAccessor::getValues (array_column like)

### ISSUE THREAD

**Issue by soullivaneuh** [symfony/symfony#30647]
**Description**  

As [described in the documentation](https://symfony.com/doc/current/components/property_access.html#reading-from-arrays), we can pick a single property from an array.

What about a `getValues` method to pick an array of values from an array of data/objects?

Basically, what `array_column` does but with the powerful features of property-access. :+1: 

**Example**  

```php
class Example {
    private $test;

    public function __construct($test)
    {
        $this->test = $test;
    }

    public function getTest()
    {
        return $this->test;
    }
}

$examples = [
    new Example('foo'),
    new Example('bar'),
];

$propertyAccessor->getValues($examples, 'test'); // Will return ["foo", "bar"]
```

What do you think?

**Comment by jschaedl** [comment]
If we implement a `PropertyAccessor::getValues(...)`, I would suggest that we implement a `PropertyAccessor::getValues(...)` as well. WDYT?
