### ISSUE TITLE
Finder get filename without extension

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#30655]
Would be nice to add a method to this API here

https://api.symfony.com/3.1/Symfony/Component/Finder/SplFileInfo.html

like:
```php
public function getFilenameWithoutExtension() { // or whatever function name makes sense
  return $this->getBasename('.' . $this->getExtension());
}
```

Right now the situation is so that if you pass no argument to [`getBasename`](https://secure.php.net/manual/en/splfileinfo.getbasename.php) you get the same result as [`getFilename`](https://secure.php.net/manual/en/splfileinfo.getfilename.php). Which in my opinion is a mistake in SPL because when you look at [`pathinfo`](https://secure.php.net/manual/en/function.pathinfo.php) you can see that `filename` doesn't include the extension

**Comment by Albanyjoi** [comment]
https://zachariahmadam896.github.io/QCQbZxDvtu0/
