### ISSUE TITLE
[VarDumper] Dumping closure broke

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#30665]
**Symfony version(s) affected**: 4.3

given

```php
dd(function () { });
```

using `GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)`

4.2 (OK)

```
Closure() {#392
  class: "X"
  this: X {#383 …}
  file: "x"
  line: "186 to 186"
}
```

4.3 (KO)

```
Closure()]8;;file://x\^]8;;\ {#438
  class: "]8;;file://xX]8;;\"
  this: X {#429 …}
}
```

(ref #30384 :angel: )

**Comment by Simperfit** [comment]
@ro0NL can you add a failling test ?

**Comment by nicolas-grekas** [comment]
Can't reproduce.

**Comment by ro0NL** [comment]
See https://github.com/ro0NL/symfony-issue-30665

Run `bin/console boo`

![image](https://user-images.githubusercontent.com/1047696/59959771-e3050e80-94bd-11e9-80de-ff3ea325a539.png)

**Comment by ro0NL** [comment]
```
PHP 7.3.6 (cli) (built: Jun 11 2019 02:03:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies
```

For what it's worth :)

**Comment by nicolas-grekas** [comment]
Issue of your terminal, if it's phpstorm they're already working on it. Otherwise we can disable links if there is an env var that allows detecting your particular flavor.

**Comment by ro0NL** [comment]
Ah i see, 4.2 doesn't have links at all. Clear :)

Im using GNOME Terminal, regular Ubunutu 16.04 AFAIK :thinking:

**Comment by ro0NL** [comment]
`echo "https://symfony.com"` works :sweat_smile:

**Comment by ro0NL** [comment]
Reading https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda i think my terminal is too old :(

> GNOME Terminal 3.26

im using 3.18

Let me compare monday on ubuntu 18.04 :)

**Comment by Simperfit** [comment]
Ill check on mine this morning ;).

Le sam. 22 juin 2019 à 07:51, Roland Franssen <notifications@github.com> a
écrit :

**Comment by ro0NL** [comment]
updated to 1804 in the meanwhile :joy:  (i was planning to do so anyway)

looks all good now :+1: 

![image](https://user-images.githubusercontent.com/1047696/59962124-7d2a7e00-94e1-11e9-8c28-07560ed10b80.png)

(GNOME Terminal 3.28.2)

Closing for now, not sure there's anything worth to do here.
