### ISSUE TITLE
 Argument 4 passed to Symfony\Component\Security\Core\Event\VoteEvent::__construct() must be of the type integer, null given

### ISSUE THREAD

**Issue by Aerogirl10** [symfony/symfony#30675]
**Symfony version(s) affected**: x.y.z
4.2.3
**Description**  

I am following the tutorial and at the point of Voters my code is breaking.
I get the following error:

> Argument 4 passed to Symfony\Component\Security\Core\Event\VoteEvent::__construct() must be of the type integer, null given, called in /Applications/XAMPP/xamppfiles/htdocs/symfony-01/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php on line 40

The code is a bit messy now, because I tried to follow documentation and the tutorial (at least one should work, huh?). Changing "role" field type didn't work. I don't have idea for that.

**How to reproduce**  

Voter.php

    class MicroPostVoter extends Voter
    {
    const EDIT = 'edit';
    const DELETE = 'delete';

    protected function supports($attribute, $subject)
    {

        // if the attribute isn't one we support, return false
        if (!in_array($attribute, [self::DELETE, self::EDIT])) {
            return false;
        }

        // only vote on Post objects inside this voter
        if (!$subject instanceof MicroPost) {
            return false;
        }

        return true;

        // replace with your own logic
        // https://symfony.com/doc/current/security/voters.html
        // return in_array($attribute, ['POST_EDIT', 'POST_VIEW'])
        //     && $subject instanceof \App\Entity\BlogPost;
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        $user = $token->getUser();
        // if the user is anonymous, do not grant access
        if (!$user instanceof User) {
            return false;
        }

        /** @var MicroPost $microPost */
        $microPost = $subject;

        //... (check conditions and return true to grant permission) ...
        switch ($attribute) {
            case self::DELETE:
                // logic to determine if the user can EDIT
                // return true or false
                return $this->canDelete($microPost, $user);

                break;
            case self::EDIT:
                // logic to determine if the user can VIEW
                // return true or false
                return $this->canEdit($microPost, $user);
                break;
        }

        return false;
    }

    private function canEdit(MicroPost $microPost, User $user)
    {
        return $user === $microPost->getUser();
    }

    private function canDelete(MicroPost $microPost, User $user)
    {
        return $user === $microPost->getUser();
    }`

Entity/User.php

`
    class User implements UserInterface, \Serializable
    {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(min=5, max=50)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(min=8)
     */
    private $plainPassword;

    /**
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @ORM\Column(type="string", length=190, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="4")
     */
    private $fullName;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MicroPost", mappedBy="user")
     */
    private $microPosts;

    public function __construct()
    {
        $this->microPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    /**
     * String representation of object
     *
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password
        ]);
    }

    /**
     * Constructs the object
     *
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list($this->id,
            $this->username,
            $this->password) = unserialize($serialized);
    }

    /**
     * @return Collection|MicroPost[]
     */
    public function getMicroPosts(): Collection
    {
        return $this->microPosts;
    }

    public function addMicroPost(MicroPost $microPost): self
    {
        if (!$this->microPosts->contains($microPost)) {
            $this->microPosts[] = $microPost;
            $microPost->setUser($this);
        }

        return $this;
    }

    public function removeMicroPost(MicroPost $microPost): self
    {
        if ($this->microPosts->contains($microPost)) {
            $this->microPosts->removeElement($microPost);
            // set the owning side to null (unless already changed)
            if ($microPost->getUser() === $this) {
                $microPost->setUser(null);
            }
        }

        return $this;
    }
}
`
**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
It looks like for some reason the result of the voting process becomes `null` in your case. Can you create a small example application that allows to reproduce it?

**Comment by smart--petea** [comment]
Could you share the tutorial link?

**Comment by Aerogirl10** [comment]
> It looks like for some reason the result of the voting process becomes `null` in your case. Can you create a small example application that allows to reproduce it?

Yup, I realized it was exactly that, when everything started working after deleting another Voter which tutor used just to explain something. It was a file with function but **no return in it.** 
Surprisingly in his case (symphony 4.0.4) there was no problem.

**Comment by xabbuh** [comment]
Thank you for the feedback. I am closing here then.

**Comment by dipaksid** [comment]
Argument 4 passed to Symfony\Component\Security\Core\Event\VoteEvent::__construct() must be of the type integer, null given, called in D:\Dipak_Workplace\wamp64\www\study\php_frameworks\sf4\vendor\symfony\security-core\Authorization\Voter\TraceableVoter.php on line 40

I am getting same error by that tutorial I am using symfony 4.2 what should I do to fix and where it is passing null value to TraceableVoter class.

**Comment by xabbuh** [comment]
What does your code look like? Which tutorial did you follow?

**Comment by dipaksid** [comment]
Hello Chistian,
Thanks for reply. I am following below tutorial : 
Learn PHP Symfony 4 Hands-On Creating Real World Application

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Learn PHP Symfony 4 Hands-On Creating Real World Application

Learn PHP Symfony 4 Framework, write a full real world application and deploy it on DigitalOcean.
 |

 |

 |


In above tutorials there is section on security component first in memory configuration in security.yml and other is using form_login, while creating service that extends from voter class I am getting that error that I've posted. If you want more details of code-source code please let me know.
Actually my company want new project in symfony 4 so that I am learning from that course.  


Thanks and Regards,Dipak Acharya

    On Tuesday, 28 May, 2019, 7:03:49 pm IST, Christian Flothmann <notifications@github.com> wrote:  
 
 
What does your code look like? Which tutorial did you follow?

**Comment by dipaksid** [comment]
`https://www.udemy.com/learn-symfony-4-hands-on-creating-a-real-world-application/`

**Comment by xabbuh** [comment]
You need to show us some code that allows us to reproduce the issue. Linking to a non-free tutorial doesn't help us.

**Comment by piotrjura** [comment]
@dipaksid Inside the ExampleVoter (a class created early in the course) you need to return something, like:
```php
<?php

namespace App\Security;

use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;

class ExampleVoter implements VoterInterface
{
    public function vote(TokenInterface $token, $subject, array $attributes)
    {
        return false;
    }
}
```
In future, you can just ask on the Q&A section of the tutorial. Note, I'm an author of this course.

**Comment by r3ntg3n** [comment]
@piotrjura just to comply with `VoterInterface::vote` method signature, I would suggest to `return VoterInterface::ACCESS_ABSTAIN`

**Comment by yoesoff** [comment]
@piotrjura I am at the "Lecture 46" section I got same error.

> Argument 4 passed to Symfony\Component\Security\Core\Event\VoteEvent::__construct() must be of the type int, null given, called in /var/www/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php on line 41

I think it's because use of is_granted method.

I follows your course carefully and I am sure that's no Voter explanation from  Lecture 1 until Lecture 46?

**Comment by tamertama** [comment]
I think that there is overriding for VoterInterface in Security folder, there you have to check if there return int or not.

Something like below, can make a problem.

src/Security/ExampleVoter.php
```
public function vote(TokenInterface $token, $subject, array $attributes)
    {
        // TODO: Implement vote() method.
    }
```

**Comment by dipaksid** [comment]
Can any one full tutorials of videos descriptive as laracast for current symfony version.

**Comment by nicolas-grekas** [comment]
See https://symfonycasts.com
