### ISSUE TITLE
[HttpFoundation] Session::getBag($name) does not match Storage\SessionStorageInterface::getBag($name)

### ISSUE THREAD

**Issue by patgrudniewski** [symfony/symfony#30682]
**Symfony version(s) affected**: 3.4.0 and higher

**Description**  
There is `getBag` method at [`Symfony\Component\HttpFoundation\Session`](https://github.com/symfony/http-foundation/blob/v4.2.4/Session/Session.php) which calls `$this->storage->getBag($name)->getBag()`.

As defined in constructor `$this->storage` is instance of [`Symfony\Component\HttpFoundation\Session\Storage\SessionStorageInterface`](https://github.com/symfony/http-foundation/blob/v4.2.4/Session/Storage/SessionStorageInterface.php) which contains method `getBag(string $name)`. As defined in comment it is expected that `SessionStorageInterface::getBag(string $name)` should return instance of [`Symfony\Component\HttpFoundation\Session\SessionBagInterface`](https://github.com/symfony/http-foundation/blob/v4.2.4/Session/SessionBagInterface.php).

The problem is that `SessionBagInterface` does not contain `getBag` method so it's impossible to expect that `$this->storage->getBag($name)` will return object containing `getBag()` method. 

**How to reproduce**  
```php
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage;

$bag = new AtrributeBag();
$bag->setName('foo');

$storage = new MockArraySessionStorage();
$storage->registerBag($bag);

$session = new Session($storage);
$session->getBag('foo'); // this will effect with "Error: Call to undefined method Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag::getBag()
```

**Possible Solution**  
I'm not sure, probably removing second `getBag` call from `Session::getBag($name)`.

**Comment by ro0NL** [comment]
i think we should test for `SessionBagProxy` first :+1: 

probably it's intended to use `SessionInterface::registerBag()` as main entrypoint (which wraps the bag)

**Comment by Simperfit** [comment]
@ro0NL what do you mean ?

**Comment by ro0NL** [comment]
There's a difference between registering a bag on the storage vs. on the session.

When registering a bag on the session it get's wrapped:

https://github.com/symfony/symfony/blob/3bbf9da47bdf79d175f84a9a9c73a5d7d4f66beb/src/Symfony/Component/HttpFoundation/Session/Session.php#L246-L249

When you register thru `MockArraySessionStorage` it's not wrapped, however we call `getBag($name)->getBag()` from the `Session` which at this points expects a wrapped bag.

So i propose in `Session::getBag()` something like

```php
return $bag instanceof SessionBagProxy ? $bag->getBag() : $bag;
```

**Comment by Simperfit** [comment]
Ok I understand now ! I think that’s a good idea ! I think the only way to
be sure is by making a PR and see of people agree with you ;). ( I do)

Le sam. 22 juin 2019 à 06:00, Roland Franssen <notifications@github.com> a
écrit :

**Comment by xabbuh** [comment]
I agree with the reasoning here, see #32137
