### ISSUE TITLE
[HttpFoundation] Invalid redirect Location

### ISSUE THREAD

**Issue by vlobovikov** [symfony/symfony#30689]
The Bug is here again - https://github.com/symfony/symfony/pull/22518

I can it reproduce. (the same case like https://github.com/symfony/symfony/issues/22517)

for example here is a code.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L39
The Code is not available more in actual state of code.

**Comment by xabbuh** [comment]
Can you please be a bit more precise and show some example code that allows us to reproduce your issue?

**Comment by vlobovikov** [comment]
`    public function savePaymentInfo(Request $request, string $orderKey, string $status): Response
    {
        $queryParams = $request->query->all();
        ...
        $redirectUrl = 'http://test.com';
        //@codeCoverageIgnoreEnd

        //workaround (see symfony bug - https://github.com/symfony/symfony/issues/30689)
        //header('Location:'.$redirectUrl);
        //exit;


        return new RedirectResponse($redirectUrl);
    }`

I have the url in text on the page but not in header. (location is empty)

**Comment by xabbuh** [comment]
I don't see how that would not behave correctly. Can you create a small example application with the required code that allows us to reproduce the issue that you experience?

**Comment by vlobovikov** [comment]
sorry, I have currently a holiday 2 weeks :(

**Comment by xabbuh** [comment]
I am closing here for now. We can still reopen when we are able to reproduce. Thank you for understanding.
