### ISSUE TITLE
[Form] Form throws error (binary content)

### ISSUE THREAD

**Issue by CarlosCosmo** [symfony/symfony#30684]
**Symfony version(s) affected**: 3.4.23

**Description**  
I've updated from 3.4.18 to 3.4.23 and I have a form with Symfony\Component\Form\Extension\Core\Type\FileType as binaryContent. It was working well but now throws a field exception (it says on debuuger info, validation tab, the following "Submitted data was expected to be text or number"). I've downgraded to 3.4.18 and its working well as described before.

**Comment by xabbuh** [comment]
Can you show some example code that allows to understand how your form is configured and what the submitted data looks like?

**Comment by CarlosCosmo** [comment]
This is a Sonata Admin Class, which is rendering the Form:

protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->add('name', null, array('required' => false))
        ->add('binaryContent', FileType::class, array('required' => false))
    ;
}

Hope this can help you.

**Comment by xabbuh** [comment]
What is the data that you submit here?

**Comment by CarlosCosmo** [comment]
A JPEG or PNG image.

**Comment by xabbuh** [comment]
And how do you submit the data? Are you doing any manual transformation after the user submits the form? Do you submit the form manually?

**Comment by CarlosCosmo** [comment]
The form is submitted manually using submit button. The form has enctype="multipart/form-data" attribute.

**Comment by xabbuh** [comment]
Can you create a small example application that allows us to reproduce this behaviour?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
