### ISSUE TITLE
"Segmentation fault (core dumped)" when start.

### ISSUE THREAD

**Issue by sj8354661** [symfony/symfony#30698]
**Symfony version(s) affected**: symfony/process v2.8.49

**Description**  
"Segmentation fault (core dumped)" when start.
progress tracked:
symfony\process\Process.php
**Process->start ==> $this->updateStatus ==> $this->readPipes ==> $this->processPipes->readAndWrite**
symfony\process\Pipes\UnixPipes.php
**UnixPipes->readAndWrite**

after tracking, the error caused by function "readAndWrite", see below line :

**if (($r || $w) && false === stream_select($r, $w, $e, 0, $blocking ? Process::TIMEOUT_PRECISION * 1E6 : 0))**

focus on "**$blocking ? Process::TIMEOUT_PRECISION * 1E6 : 0**", if this value < 1,000,000, or is 0, then this throw the error: Segmentation fault (core dumped).

**Comment by nicolas-grekas** [comment]
2.8 is not maintained anymore. Segfaults are usually bugs in PHP, not Symfony. Try upgrading both.
