### ISSUE TITLE
[Filesystem] FilesystemTestCase is not compatible with PHPUnit 8

### ISSUE THREAD

**Issue by GaryPEGEOT** [symfony/symfony#30695]
**Symfony version(s) affected**: >= 3.4

**Description**  
the [FilesystemTestCase](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Filesystem/Tests/FilesystemTestCase.php) has the same issue that #30071 

**How to reproduce**  
Run a test extending FilesystemTestCase with PHPUnit 8 will produce:
`PHP Fatal error:  Declaration of Symfony\Component\Filesystem\Tests\FilesystemTestCase::setUpBeforeClass() must be compatible with PHPUnit\Framework\TestCase::setUpBeforeClass(): void `

**Possible Solution**  
Use the same solution that #30474

**Comment by dmaicher** [comment]
Is this a test class that is meant to be used in userland code? I mean a lot of internal Symfony tests are not PHPUnit 8 compatible.

**Comment by GaryPEGEOT** [comment]
Not sure in fact... but it's not marked as internal

**Comment by xabbuh** [comment]
All classes from the `Tests` namespaces are purely internal code and you should never rely on any of them.

**Comment by chalasr** [comment]
Closing as explained.
