### ISSUE TITLE
PhpunitBridge tags declaring wrong PHP support should to be dropped or changed

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#30709]
There are symfony/phpunit-bridge 4.2.4 and 3.4.23 versions which declare support for PHP 5.3 but use PHP 5.4 syntax. Even when new version which fixes this will be released, this will not fix the issue, because if you test on PHP 5.3/5.4 and have 
```json
"require-dev": {"symfony/phpunit-bridge": "^3.0|4.0"}
```

composer will skip installing 4.2.5/3.4.24 and keep installing faulty version.

I suggest to exceptionally drop these faulty tags. Fortunately, there are no significant changes:

https://github.com/symfony/phpunit-bridge/compare/v3.4.22...v3.4.23
https://github.com/symfony/phpunit-bridge/compare/v4.2.3...v4.2.4

**Comment by xabbuh** [comment]
I am not sure I understand. Why would Composer not install 3.4.24 or 4.2.4?

**Comment by ostrolucky** [comment]
Because php requirement was fixed in these versions. Composer doesn't install dependencies for which you don't fullfill platform criteria.

**Comment by xabbuh** [comment]
But we don't increase the required PHP version for these releases so there's no platform requirement preventing the installation. We only made the mistake in some releases to have PHP 5.4+ code in versions of the bridge that must be compatible with PHP 5.3.

**Comment by ostrolucky** [comment]
> there's no platform requirement preventing the installation

What I am reporting is opposite. Installation of 4.2.4+/3.4.23+ shlould be prevented on PHP 5.3 but it is not. Fixing requirement in new version will not fix it for already released tags.

**Comment by ostrolucky** [comment]
After discussion with @xabbuh on slack, what I didn't realize is that requirement was fixed in master only, not in 3.4, 4.2 branches. And <4.3 branches are supposed to have PHP 5.3 support (https://github.com/symfony/symfony/pull/29623#issuecomment-450400625), so seems solution should be to revert short array commits there, no need to change old tags.
