### ISSUE TITLE
phpunit command does not respect SYMFONY_PHPUNIT_VERSION in phpunit.xml/.env

### ISSUE THREAD

**Issue by martixy** [symfony/symfony#30700]
**Symfony version(s) affected**: phpunit 4.1

**Description**  
Based on how environment variables are read:

https://github.com/symfony/phpunit-bridge/blob/b3451fc442baaf9169e50491a059ef17582c4424/bin/simple-phpunit#L18-L46

the `phpunit` command flat out overrides the variables:
`SYMFONY_PHPUNIT_VERSION`  
`SYMFONY_PHPUNIT_REMOVE`  
`SYMFONY_PHPUNIT_DIR`

https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/4.1/bin/phpunit

E.g. it currently hardcodes phpunit to v6.5.

This seems like a bug, especially given that the docs explicitly say 

> PHPUnit is configured by the phpunit.xml.dist file in the root of your Symfony application.

You also can't define them in the `.env` files either.

**How to reproduce**  
Install the website-skeleton, try to define the `SYMFONY_PHPUNIT_VERSION` variable in your `phpunit.xml` (or any of the variables `./bin/phpunit` overrides) and see it fail.

**Possible Solution**  
Better logic in getting the env variables? (In `bin/simple-phpunit`.)
Maybe also start reading `.env` files? At which point also decide on a priority, e.g. env > phpunit.xml > phpunit.xml.dist. Don't have insight on this though.

**Additional context**

**Comment by nicolas-grekas** [comment]
There is no way to define the version of phpunit on a file that is read by phpunit.
Editing the bin/phpunit script is the way to go.

**Comment by eliecharra** [comment]
@nicolas-grekas Maybe I'm missing something, but could you explain why not ? Actually when running `vendor/bin/simple-phpunit`, env vars defined in phpunit.xml taken into account with following config :

```xml
<!-- phpunit.xml.dist -->
<php>
  <ini name="error_reporting" value="-1" />
  <server name="APP_ENV" value="test" force="true"/>
  <env name="SHELL_VERBOSITY" value="-1" />
  <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak_vendors"/>
   <env name="SYMFONY_PHPUNIT_VERSION" value="7.5"/>
</php>
```

```bash
$ bin/phpunit --version
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
$ vendor/bin/simple-phpunit --version
PHPUnit 7.5.8 by Sebastian Bergmann and contributors.
```

The problem here is a forced env override from `bin/phpunit` :

```php
if (false === getenv('SYMFONY_PHPUNIT_VERSION')) {
    putenv('SYMFONY_PHPUNIT_VERSION=6.5');
}
```

Maybe this "default" could be moved to `phpunit.xml.dist` in flex reciepe and removed from bin/phpunit wrapper script ?

**Comment by davidkmenta** [comment]
Hmmm... https://symfony.com/doc/current/components/phpunit_bridge.html

> Set the SYMFONY_PHPUNIT_VERSION env var to e.g. 5.5 to change the base version of PHPUnit to 5.5 instead of the default 5.3.
>
> It's also possible to set this env var in the phpunit.xml.dist file.

The documentation appears to be confusing (at least for me).

**Comment by ndench** [comment]
All the `bin/phpunit` script does is set environment variables and call `vendor/bin/simple-phpunit`which reads from `phpunit.xml` as expected. 
So just stop using `bin/phpunit` all together and problem solved.
