### ISSUE TITLE
[Property-Access] Can't handle setters with variadic arguments

### ISSUE THREAD

**Issue by beutelsend** [symfony/symfony#30703]
**Symfony version(s) affected**: 4.2

**Description**  
PropertyAccessor class does not check if a method has variadic arguments, and therefore doesn't call them with "...$value" as parameter, but as an array, which triggers an error.

**How to reproduce**  
Define a class with a setter with one variadic argument. Try to set the value via property-access.

**Possible Solution**  
There should be a type "ACCESS_METHOD_VARIADIC" which handles this case. ReflectionParameter has a method called "isVariadic" to check if a method / function parameter is variadic.

**Comment by beutelsend** [comment]
Associated Code fragment can be found here: https://github.com/symfony/property-access/blob/master/PropertyAccessor.php#L542

**Comment by beutelsend** [comment]
I would suggest this is a bug, since variadic arguments are a core php feature, where the use of which should not trigger a bug in a component which tries to cover all kinds of property reading / writing.

**Comment by drupol** [comment]
Hi @beutelsend,

I'm trying to replicate the issue but I'm unable to trigger an error, maybe I'm doing something wrong ?

Here's my very uber super basic test case:

```php
<?php

include 'vendor/autoload.php';

use Symfony\Component\PropertyAccess\PropertyAccess;

class Foo {
    private $property;

    public function setProperty(...$args) {
        $this->property = implode('', $args);
    }

    public function getProperty() {
        return $this->property;
    }
}

$foo = new Foo();

$propertyAccessor = PropertyAccess::createPropertyAccessor();

$propertyAccessor->setValue($foo, 'property', 'value');

var_dump($foo->getProperty());
```

Let me know if I missed something.

Thx

**Comment by dimabory** [comment]
@drupol Works well as well on my side.

But I think @beutelsend has mentioned about the following case:

```php
$propertyAccessor->setValue($foo, 'property', 'value', 'value1', 'valueN');
// or 
// $propertyAccessor->setValue($foo, 'property', ...['value', 'value1', 'valueN']);
```

In that case, only the first value will be set into the `property`.

**Comment by xabbuh** [comment]
@dimabory I am fine with adding support for this as a new feature.

**Comment by nicolas-grekas** [comment]
Setting multiple values to a *property* is undefined.
If you target a variadic setter, call it directly.
