### ISSUE TITLE
[Console] There is no way to non-interactively change answer of QuestionHelper

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#30726]
```php
$output->writeln(
    (int) (new QuestionHelper())->ask(
         $input, $output, new ConfirmationQuestion('yes or no?', false)
    )
);
```

I expect running this as `yes | ./bin/console foo` will output `1`, but outputs `0`. Problem is QuestionHelper [slaps there always default value when it detects noninteractive mode](https://github.com/symfony/symfony/blob/8f995e6c07e1d50d6d66a84fae0a1adf75f1fc1c/src/Symfony/Component/Console/Helper/QuestionHelper.php#L50-L66).  

Maybe non interactive mode detection could be improved, since `yes` command clearly interacts with application.

**Comment by antonch1989** [comment]
@ostrolucky if you don't plan to implement this, I could work on this issue

**Comment by ostrolucky** [comment]
@antonch1989 feel free to work on this. I would eventually get around working on this, but I don't know when.

**Comment by antonch1989** [comment]
ok then, I'm on it

**Comment by teohhanhui** [comment]
> Maybe non interactive mode detection could be improved, since yes command clearly interacts with application.

But that's not what (non-)interactive means. Interactive means the user is able to interactively provide an input, which in the case of a piped-in STDIN is clearly not possible.

**Comment by ostrolucky** [comment]
User and tools like `yes` are both using stdin, so semantics for considering command interactive needs to be same.

**Comment by teohhanhui** [comment]
What I mean is, (non-)interactive has nothing to do with whether STDIN is being used or not, but has to do with whether there is a (pseudo-)TTY.

**Comment by ostrolucky** [comment]
That's your definition. I say interaction happens when passing input through stdin as well.

Even if you are right with definition of interactive, it doesn't change the problem that Symfony uses interactive flag for determinig if it accepts stdin input. So we can rollback this flag to old definition, but we then also need to change Console component to stop treating this flag as deciding factor for ignoring stdin input, to go in line with other standard tools such as `readline`. In the end not much would be changed for users.

**Comment by teohhanhui** [comment]
Respectfully, this is not my definition. I refer you to

https://www.tldp.org/LDP/abs/html/intandnonint.html

and

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html

which define quite clearly what's meant by an interactive shell.

> it doesn't change the problem that Symfony uses interactive flag for determinig if it accepts stdin input. So we can rollback this flag to old definition, but we then also need to change Console component to stop treating this flag as deciding factor for ignoring stdin input, to go in line with other standard tools such as readline.

Indeed, this bug is still valid. #33897 is not the correct fix because it makes incorrect assumptions, and also because it breaks many things.

**Comment by ostrolucky** [comment]
> Let us consider an interactive script to be one that requires input from the user, usually with read statements

`read` accepts stdin:
```
$ echo foo | (read a; echo $a)
foo
```

In second link I didn't see anything about interactive command/script, just interactive shell
