### ISSUE TITLE
asynchronous message handler can not save the cache

### ISSUE THREAD

**Issue by lichnow** [symfony/symfony#30727]
**Symfony version(s) affected**: 4.2.0

**Description**  
I dispatch message in a controller function and after asynchronous message been send, handler which receive message from rabbitMQ will handling the message.but when I save a cache in handler,
and I want to check if exists the cache by the key to decide to send message in this controller again,it can not found any cache which been saved in handler before.

the code like this
```
   // controller
    public function index(\Swift_Mailer $mailer)
    {
        $message = (new SendRegMailRequest())
            ->setEmail('jack9029@gmail.com');
        $cache = new FilesystemAdapter('app.cache');
        if ($cache->hasItem($message->getKey())){
            throw new HttpException(400,'you can not send validation email in 30 minutes again');
        }
        $this->bus->dispatch($message);
        return $this->render('blog/default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
```

```
// message
final class SendRegMailRequest extends MailerMessage
{
    /**
     * @var string
     */
    private $email;
    private $keyPrefix = 'auth.code.register.validator';
    private $code;
   public function getEmail():string
    {
        return $this->email;
    }

    public function getCode()
    {
        return $this->code;
    }

    public function getKey()
    {
        return $this->keyPrefix.'.'.preg_replace("/[^a-z0-9]+/i","-", $this->email);
    }
...
```
and handler
```
 public function __construct(\Swift_Mailer $mailer,Templating $templating)
    {
        $this->cache = new FilesystemAdapter('app.cache');
        $this->templating = $templating;
        parent::__construct($mailer);
    }

  public function __invoke(SendRegMailRequest $regMail)
    {
        $regMail->setMessage($this->templating);
        $validate = $this->cache->getItem($regMail->getKey());
        $validate->set($regMail->getCode());
//        $validate->expiresAt(Carbon::now()->addMinute(30));
        $this->cache->save($validate);
       $this->sendMail($regMail);
    }
```

Is it a bug,or Is my owner wrong?

**Comment by xabbuh** [comment]
Quickly looking at your code I think your mistake is to create your own cache adapter. I think you will probably rather want to configure the cache in your application and then inject the cache as any other service.

**Comment by lichnow** [comment]
@xabbuh yeah,I test to inject cache service `Symfony\Component\Cache\Adapter\AdapterInterface`,and it work fine.so,I think when what I injected in `controller`,`handler` and any other place is always the same instance of `FilesystemAdapter`,but when use `new` to create instance,the cache is not same instance,so it invalid, is it?

and why not write a document for `symfony's cache` in guide,now I only see a document of `cache component`,so this prevents me from using it properly in the symfony app.
