### ISSUE TITLE
[Finder] InvalidArgumentException for non-existing directory

### ISSUE THREAD

**Issue by xelan** [symfony/symfony#30723]
**Symfony version(s) affected**: all supported versions

**Description**  
`Finder::in()` throws an `InvalidArgumentException` when one of the directories is not found. However, a valid directory name for a directory which does not exist is IMHO a normal case for the `Finder` and not an invalid argument. Therefore, non-existing directories should throw an dedicated Exception of the `Finder` component instead of the generic `InvalidArgumentException`.
This would also simplify catching such exceptions.

**How to reproduce**  
```php
require_once('vendor/autoload.php');
$f = new Symfony\Component\Finder\Finder();
$f->directories()->in('no');
```

Throws `InvalidArgumentException` although the argument is a valid directory name. A dedicated exception which can be specifically caught would be more useful and improve DX.

**Possible Solution**  
Create a dedicated `DirectoryNotFoundException`, which extends `InvalidArgumentException` for BC. Later it would probably make more sense to extend `RuntimeException` instead.

**Comment by xelan** [comment]
@xabbuh If you want, I can submit a PR for this small feature (based on master?).

**Comment by xabbuh** [comment]
I am not sure this change is necessary, but it's probably small enough that we could discuss it in a PR without having you wasted too much time in case it won't be merged.

**Comment by xelan** [comment]
PR submitted :)
