### ISSUE TITLE
[Symfony/Finder] Add support for mercurial version controls in ignoreVCSIgnored

### ISSUE THREAD

**Issue by amaabdou** [symfony/symfony#30738]
in Symfony/Finder component , ignoreVCSIgnored uses .gitignore        
It will be nice to have support for [mercurial](https://www.mercurial-scm.org/wiki/.hgignore 
) .hgignore file

https://github.com/symfony/symfony/pull/30448#issuecomment-477120150

**Comment by hkdobrev** [comment]
`.gitignore`

**Comment by fabpot** [comment]
Apparently, mercurial is not popular enough. Let's close as nobody took care of implementing it. Should be easy enough though.
