### ISSUE TITLE
[BUG][Profiler][Timeline] JS error with custom events/sections

### ISSUE THREAD

**Issue by ovrflo** [symfony/symfony#30745]
**Symfony version(s) affected**: 4.3-DEV

**Description**  

Looks like #30450 broke the Timeline panel in profiler with sections other than standard symfony ones. I have a custom caching bundle that uses the Stopwatch to measure (and also display in profiler) cache call duration. When the Timeline page loads, it throws JS error because the category `ovrflo_cache` does not exist (as it is not one of the hardcoded ones).

**How to reproduce**  
This controller will reproduce the problem:
```
    public function index(Stopwatch $stopwatch)
    {
        $stopwatch->start('some_name', 'some_category');
        sleep(1);
        $stopwatch->stop('some_name');

        return new Response('</body>');
    }
```
Click on the debug toolbar, go to Timeline, open Dev Tools and you'll see the error.

**Possible Solution**  
I fiddled with the JS in `@WebProfiler/Collector/time.js` and I got it to work. I am ready to submit a PR with my code, but I'm not proud of it. I'm a bit rusty with JS/ES6. If you want me to submit a PR with my fix, let me know. If someone else wants to take a stab at it, the issues I found are with 2 calls
- `Legend.add` cannot find the category in `this.categories`
- `Legend.getClassname` cannot find the category in `this.classnames`
My fix detects those undefined values and adds the category in both places with default values.

**Edit**: I just pushed my fix if anyone wants to take a look at it: https://github.com/ovrflo/symfony/commit/17be20a38614ebdd06238d00726a58d182d035cd

This probably affects any third party bundle that uses the Stopwatch. We should fix this ASAP.

**Comment by ovrflo** [comment]
Found another bug in `@WebProfiler/Collector/time.html.twig`.
It tries to transform the events in the profile into a format usable by JavaScript. When doing that, it uses `{{ "%F"|format(someFloatValue) }}`.

Randomly, my page had `event.starttime = -0.1`, which caused that sprintf to print -0.1. That would be fine (kinda) if it wouldn't be printed with some unicode dash (`starttime: \u002D0.100000,`) causing the page to throw `Uncaught SyntaxError: Invalid or unexpected token`.

I'm not sure how to fix this. I would probably get rid of those sprintf calls, but that would mean assuming that I really get floats/integers. If something else gets there it may fail.

Another solution may be to just move that code to the Collector, handle it properly in PHP (will all the needed casts) and then dump it in Twig with `|json_encode|raw`. It's a bit more work, but I would go with this. Should I open a separate issue for this one ? And/or a PR ?

Please advise. Thanks !

**Comment by curry684** [comment]
Picking this up at EUFOSSA.

**Comment by curry684** [comment]
I fixed the first issue in https://github.com/symfony/symfony/pull/30973

The second issue just sounds like GIGO to me - you're "corrupting" the data to something it shouldn't ever contain. Not something I really think we can make the profiler resistant to.

**Comment by ovrflo** [comment]
@curry684 thank you very much for your fix :)
Also, you're probably right on the second issue. It also seems to reproduce randomly. I actually don't think I saw it happen after reporting it here. If I manage to reproduce it and get to the bottom of it, I'll open a new issue.

Thanks again !
