### ISSUE TITLE
Database AWS Endpoint URL

### ISSUE THREAD

**Issue by adityarai** [symfony/symfony#30746]
**Symfony version(s) affected**: 4.2.4

**Description**
symfony does not accept AWS RDS endpoint URL. 
eg.    test.ctekhgnt6wpc.ap-south-1.rds.amazonaws.com 

In my .env file
DATABASE_URL=mysql://aditestuser:hello123@test.ctekhgnt6wpc.ap-south-1.rds.amazonaws.com/testdb

but the same works if i access through mysql workbench.

if i dump schema or run any query, it throws error:
SQLSTATE[HY000] [1045] Access denied for user 'adirai1122'@'172.31.4.155' (using password: YES)

the url displayed in exception does not match.

**Comment by xelan** [comment]
What do you mean with "symfony does not accept"? Can you please post the exact error message or other output you get? How is the environment variable used in your code?

**Comment by adityarai** [comment]
php bin/console doctrine:schema:update --dump-sql

11:14:41 ERROR     [console] Error thrown while running command "doctrine:schema:update --dump-sql". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'adirai1122'@'172.31.4.155' (using password: YES)" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "doctrine:schema:update --dump-sql","message" => "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'adirai1122'@'172.31.4.155' (using password: YES)"]

**Comment by xelan** [comment]
Somehow your exception message doesn't match the value in your configuration at all - different user and host. Are you sure the correct file or environment is loaded?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by LaraGastaldi** [comment]
I am having this issue as well, the database IP that symfony is returning in the exception is the IP of my internet router.
I tried using the aws rds hostname and its IP, and both return the same exception
