### ISSUE TITLE
[Serializer] Object_To_Populate ignores data attribute types when deserializing

### ISSUE THREAD

**Issue by lbayerl** [symfony/symfony#30750]
**Symfony version(s) affected**: 4.2

**Description**  
Using Symfony Framework Bundle Serializer as configured per default data denormalization is behaving different depending on whether context has an Object_To_Populate set.

**How to reproduce**  
Json:

`{name: 'MyName', birthDate: '2000-01-01T00:00:00+01:00'}`

Class:

`public $name; /** @var \DateTime */ public $birthDate;`

`$this->serializer->deserialize($data, MyObject::class, 'json', [AbstractObjectNormalizer::OBJECT_TO_POPULATE => $object]);`

is resulting in an error as the DateTimeNormalizer isn't used.

`$this->serializer->deserialize($data, MyObject::class, 'json');`

returns a new working object.

**Possible Solution**  
AbstractNormalizer->instantiateObject immediately returns the object when context is set with OBJECT_TO_POPULATE, probably it shouldn't in any case?

**Comment by Raulnet** [comment]
Can you get more details ?
after several tries, everyone worked for me.
on project from scratch 4.2 and php7.2
object:
```php 
class Dto
{
    public $name;
    /** @var DateTime */
    public $birthDate;
}
```
-1 test without overide datetime
```php 
        $object = new Dto();
        $object->name = 'fab';
        $object->birthDate = new \DateTime('now');

        $data = '{"name": "MyName"}';
        $this->serializer->deserialize($data, Dto::class, 'json', [AbstractObjectNormalizer::OBJECT_TO_POPULATE => $object]);

        dump($object);
        // App\Command\Dto {#330
        //  +name: "MyName"
        //  +birthDate: DateTime @1554454707 {#131
        //    date: 2019-04-05 10:58:27.588532 Europe/Berlin (+02:00)
        //  }
        //}
```
2- test with overide datetime
```php
$object = new Dto();
        $object->name = 'fab';
        $object->birthDate = new \DateTime('now');

        dump($object);
        //App\Command\Dto {#474 <== Object
        //  +name: "fab"
        //  +birthDate: DateTime @1554454999 {#330
        //    date: 2019-04-05 11:03:19.651679 Europe/Berlin (+02:00)
        //  }
        //}

        $data = '{"name": "MyName", "birthDate": "2000-01-01T00:00:00+01:00"}';
        $this->serializer->deserialize($data, Dto::class, 'json', [AbstractObjectNormalizer::OBJECT_TO_POPULATE => $object]);

        dump($object);
        //App\Command\Dto {#474 <== Same Object
        //  +name: "MyName"
        //  +birthDate: DateTime @946681200 {#468
        //    date: 2000-01-01 00:00:00.0 +01:00
        //  }
        //}
```
3- test without objectPopulate
```php
$data = '{"name": "fab", "birthDate": "1980-02-01T01:00:00+01:00"}';
        $newObject = $this->serializer->deserialize($data, Dto::class, 'json');

        dump($newObject);
        // App\Command\Dto {#475
        //  +name: "fab"
        //  +birthDate: DateTime @318211200 {#422
        //    date: 1980-02-01 01:00:00.0 +01:00
        //  }
        // }
```

**Comment by Simperfit** [comment]
@lbayerl Can you please check what  @Raulnet said ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
