### ISSUE TITLE
[HttpClient] Setting both json and body shouldn't be allowed

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony#30769]
Setting both body and json in the HttpOptions is allowed, but it will result in having the json encoded data set in 'body'. See https://github.com/symfony/symfony/blob/37b616fefbd27807a5b14fccb63fcb65dd149c0e/src/Symfony/Component/HttpClient/HttpClientTrait.php#L44
I think an exception should be thrown when having this options both set. That might improve DX.

I'm happy to provide a PR. What exception should be thrown?

**Comment by nicolas-grekas** [comment]
I'm always reticent about creating correlations between options as it adds complexity (the correlation *is* complexity) and restricts use cases that might be legit.
But I don't see any blocker here. I won't oppose if more ppl agree.

**Comment by javiereguiluz** [comment]
👍 I agree with Nicolas comment ... but also agree that this is a case where we could make an exception and add that "correlation" between options.
