### ISSUE TITLE
ClassNotFoundException: Attempted to load class "TwigBundle" 

### ISSUE THREAD

**Issue by EresDev** [symfony/symfony#30782]
**Symfony version(s) affected**: 4.2.4

**Description**  
When create project using composer for just skeleton and later you also require symfony/profiler-pack for dev only, it has dependency on TwigBundle. 
But in config/Bundles.php you get following:
```php
return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
];
```

Web profiler is required for for dev and test only, but twig is required for all. The problems arises when you want to deploy this application with composer install --no-dev

```
.
.
.
  - Installing symfony/cache (v4.2.4): Loading from cache
  - Installing symfony/framework-bundle (v4.2.4): Loading from cache
  - Installing symfony/yaml (v4.2.4): Loading from cache
Generating autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "TwigBundle" from namespace "Symfony\Bundle\TwigBundle".
!!  Did you forget a "use" statement for another namespace? in /home/arslvsec/public_html/eresnote/src/Kernel.php:23
!!  Stack trace:
!!  #0 /home/arslvsec/public_html/eresnote/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 /home/arslvsec/public_html/eresnote/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /home/arslvsec/public_html/eresnote/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /home/arslvsec/public_html/eresnote/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 /home/arslvsec/public_html/eresnote/bin/console(38): Symfony\Component\Console\Application->run(Objec in /home/arslvsec/public_html/eresnote/src/Kernel.php on line 23
!!  
Script @auto-scripts was called via post-install-cmd

```

**How to reproduce**  
- create project in current directory
`composer create-project symfony/skeleton .`

- add profiler
`composer require --dev symfony/profiler-pack`

- Now, you have to deploy it for production. You can use different folder or different server. Make it ready for deployment for production by changing the .env file for `APP_ENV=prod`

- finally, perform 
` composer install --no-dev`

You will get the above error for twig dependency.

**Possible Solution**  
I can't guide you the solution but one thing I want to mention is this is going to be complicated. Because in website-skelton, you need need TwigBundle for all, but in skeleton, you need it for dev and test only if required with profiler. 

**Additional context**  
I faced this problem yesterday while deploying my application. And now, I tried to reproduce this bug and I was able to reproduce it. [Here is stakeoverflow thread](https://stackoverflow.com/questions/55426427/symfony-deployment-error-code-255-with-composer-install-no-dev) of this problem that was solved by manually editing config/bundles.php for TwigBundle for dev and test only and then moving twig.yaml files to appropriate folders.

**Comment by Raulnet** [comment]
**context:**
symfony/profiler-pack and his dependencies "twig\Bundle" are loaded
`"require-dev": {
        "symfony/profiler-pack": "^1.0"
    }`
And could not be installed on context "prod"

**solution:**
If you want to use "Twig\Bundle" in other context you sould load separately with:
`composer require symfony/twig-bundle`.
Now TwigBundle is in "require" and symfony/profiler-pack in "require-dev"

**Comment by EresDev** [comment]
> symfony/profiler-pack and his dependencies "twig\Bundle" are loaded
"require-dev": { "symfony/profiler-pack": "^1.0" }
And could not be installed on context "prod"

I understand it and this is how it should be. But it is not.  config/bundles.php is generated with `Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],` instead of `Symfony\Bundle\TwigBundle\TwigBundle::class => ['dev' => true, 'test' => true],` When you only require-dev profiler. 

I don't need Twig. My app is a Rest API. I just use profiler on dev and test env. But when I deploy on prod, where I neither need profiler nor the twig, the above error pops up about attempting to load

**Comment by stof** [comment]
Well, you can edit the bundles.php file to change when TwigBundle gets registered.

Currently, Flex does not try to detect whether the package got installed due to a dev requirement (which is far from being trivial) when registering the bundle. But it will preserve any modification you do.

**Comment by chalasr** [comment]
As explained, this is a flex limitation. Closing.

**Comment by Rubinum** [comment]
For those who have the same issue and want a summary:

Just check your bundles.php inside of your project. The error occurs, because a bundle is loaded in prod but its registered for composer as "dev dependency". Therefore symfony loads the bundle but its not there because you did a "composer install --no-dev" before. Dev dependencies are not installed in prod environments. 
![image](https://user-images.githubusercontent.com/5645798/155515703-34c9902d-7bb3-4192-aa68-d4485160c798.png)

![image](https://user-images.githubusercontent.com/5645798/155515876-4b3f05af-29f6-455b-8f2f-efad235d737f.png)

**Comment by ffurbo** [comment]
In my symfony 6.1 rest project I have to modify `config/packages/twig.yaml` 
```
when@dev:
    twig:
        default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        default_path: '%kernel.project_dir%/templates'
        strict_variables: true
```
simply deleting twig.yaml works as well. 
Otherwise I'm still getting error running `composer install --no-dev` when it's executing  script cache:clear
