### ISSUE TITLE
Allow manipulation of base path when warming cache

### ISSUE THREAD

**Issue by samuelvogel** [symfony/symfony#3079]
It makes sense to allow a manipulation of the base path for cache warming for several reasons:

* You use php-fpm in production and have it configured to run inside a chroot, since CLI used for cache warming does not have the chroot, paths will differ
* You checkout new versions of your application and warm your cache before transfering it to the actual docroot to make the upgrade process atomic

The problem is when you warm the cache in a directory that is later moved or only accessible by a different path, then paths in `app/cache/prod/templates.php` for example will be wrong, and Twig imports will break.

**Comment by kostiklv** [comment]
@fabpot, @nicolas-grekas, this issue was not fully fixed by #12784. Specifically, `app/cache/*/templates.php` still contains absolute paths

**Comment by timdierolf** [comment]
I agree. Currently we're running into problems having absolute paths in `app/cache/*/templates.php`.

We're building release packages during a Jenkins build on a dedicated build machine which we then deploy to production machines. But the cache file `app/cache/*/templates.php` contains the absolute paths from the build on the Jenkins machine.

We can omit the `TemplatePathsCacheWarmer` with the `--no-optional-warmer` option as it is an optional warmer. However, having correct templates paths cached in production would still be a significant performance boost.

**Comment by FaKeller** [comment]
I agree, too. There are still absolute paths in `app/cache/*/templates.php`. We are currently running Symfony 2.7.2.

**Comment by pasdeloup** [comment]
It should be possible to adopt the same strategy than @nicolas-grekas on #12784 : after generating absolute path, match the result with __DIR__ to make it relative.
Did anyone try it? Is there a problem like a BC break? I can try but I don't want to waste time if it has already been done and doesn't work.

**Comment by tgalopin** [comment]
Should be fixed now, if you have an issue don't hesitate to report it here.

**Comment by timdierolf** [comment]
Why has #19687 not been released yet?

**Comment by nicolas-grekas** [comment]
It is merged into master, and master will be tagged as 3.2 by the end of november, according to [the release policy.](https://symfony.com/roadmap)

**Comment by timdierolf** [comment]
Ah ok, I see. Thank you very much!
