### ISSUE TITLE
Application option to only try exact found commands, not similars

### ISSUE THREAD

**Issue by rudiedirkx** [symfony/symfony#30804]
I don't like `Application` 'smart-finding' a command that's similar to what I typed, and executing it without any notification, even though that's not what I typed. Currently that behavior is hard-coded in `Application::find()`. I would love an option to disable that behavior. A public method, or a protected property (to disable in a child application class).

With that option enabled (or the smart-find disabled, whichever way you want to name it) it would just throw an error. Something like:

> Command "%s" not found.\nDid you mean "%s"?

And then the user can choose what to do.

I would make a PR, but all class properties are private, and I would make a `protected $enableSmartFind = true;` (which is probably not allowed), so any subclass can disable it.

----

It'd also be lovely to use some of that private info in a child class. A child class can't even do:

    $allCommands = $this->commandLoader ? array_merge($this->commandLoader->getNames(), array_keys($this->commands)) : array_keys($this->commands);

(like in `find()`) to find all registered commands. Why so private..?

**Comment by CharlotteDunois** [comment]
In my opinion, whether similar commands should be executed or net, should be exclusively opt-in, or at least configurable.

The probably easiest way is to add a constructor argument to `Application` with a default value and adjust line 237 to either use `get` or `find`, depending on the configured behaviour.
https://github.com/symfony/symfony/blob/50c22b3d58e3d96ecb5015b01462af84e66acbe9/src/Symfony/Component/Console/Application.php#L234-L238

**Comment by curry684** [comment]
This issue report is incorrect, I think you're confusing a few of the mechanisms. It most certainly does not execute a random command based on similarity:
```
$ bin/console cache:claar
                            
  Command "cache:claar" is not defined.  
                                         
  Did you mean one of these?             
      cache:clear                        
      cache:pool:clear                   
      cache:pool:delete                  
      cache:pool:prune                   
      cache:warmup                       
```
It will autocomplete a command if there is *no ambiguity*:
```
$ bin/console cache:cl

 // Clearing the cache for the dev environment with debug                       
 // true                                                            
```
It will however not even autocomplete when there is:
```
$ bin/console redis:f
                                
  Command "redis:f" is ambiguous.  
  Did you mean one of these?       
      redis:flushall               
      redis:flushdb                
```
The current behavior makes sense and is depended on by many Symfony Console applications out there. I don't really see a reason to change anything as it's not broken.

**Comment by lyrixx** [comment]
I agree with @curry684 here

**Comment by rudiedirkx** [comment]
Who said anything about random or ambiguity..? Not me.

The issue report IS correct. Exactly what @curry684 said. If ONE 'matching' alternative is found, it's run WITHOUT question. That's what I don't like, and would want to make optional.

> The current behavior makes sense

I disagree, hence the issue. Any console app shouldn't do something you didn't ask for literally. How freaky would it be if Bash did this? If you do like that, fine, nothing will change for you, but please let me disable it.

@CharlotteDunois I'm talking about the find mechanism in `find()`, which jumps to the alternative IF there is exactly 1. I wouldn't change the default, for bc.

**Comment by rudiedirkx** [comment]
Would a PR with a protected property be seriously looked at, or just closed if someone doesn't understand the issue?

Could someone please answer my protected vs private questions? Is protected frowned upon, or acceptable?

**Comment by chalasr** [comment]
Changing properties/methods visibility require a strong motivation because of the maintenance cost it has, not every methods/properties are meant to be extension points.
About the proposed feature, I can imagine that the automatic resolution is not desirable for everyone (you might want strictness).
I think this one deserves a bit more time/discussion, reopening if you don't mind.

**Comment by curry684** [comment]
> I don't like Application 'smart-finding' a command that's similar to what I typed, and executing it without any notification, even though that's not what I typed. 

The way you wrote this implies through the word "similar" that `cache:claar` would work, as it's similar. The similarity search is only performed when an existing command could not be autocompleted. Autocomplete and similarity checks are different mechanisms in this.

Autocomplete itself is a vital functionality - everybody uses that, from `bin/console doctrine:schema:upd` to `composer upd`. That's why I said you can't break this functionality, at least not change anything about its defaults.

I **do** see merits in being able to mark a command as "not executable through autocomplete". That's a marker that would make sense for highly dangerous commands like `redis:flushall` and `doctrine:schema:drop`. A PR to that end would be taken seriously, although personally I think it's more up to the command implementor (invasive Doctrine commands require a `--force` parameter to make you think twice).

**Comment by curry684** [comment]
Best implementation methinks would be to just add it to the command configuration, something like:
```
    protected function configure()
    {
        $this
            ->setDescription('This is my invasive command')
            ->disallowAutocomplete('Optional reason')
```
And it would then do something like:
```
$ bin/console redis:flusha

   Command "redis:flusha" does not exist. The command "redis:flushall" looks similar but has
   to be typed out explicitly (reason here if one was given)
```

**Comment by rudiedirkx** [comment]
Yes, "strictness" is a much better word.

> I think it's more up to the command implementor

A command can't choose to be strict, can it? Or should that be the new option? I like it, BUT it's still not giving the power to the app developer who uses (others people's) commands. The person who makes the application (who selects/combines the commands) should be able to choose how strict the app is.

I would NOT change the default. But the option doesn't even exist now. Hence the protected property that can be set in the subclass. Or just a public method if protecteds are dirty.

I want to make a PR to make the entire app strict, not per command. Both are useful IMO, but I need the app-wide strictness. If that wouldn't get in, I won't make the PR.

**Comment by curry684** [comment]
That seems like an esoteric requirement, but is actually already possible by listening for `ConsoleEvents::COMMAND` events. The event contains both the resolved Command and the `InputInterface`, so you can check in there and disable the execution to your liking.

See the docs here https://symfony.com/doc/current/components/console/events.html

**Comment by xabbuh** [comment]
@rudiedirkx Can you confirm that the approach outlined by @curry684 does work? In this case, I'd say we can close here. At least as of now we haven't received any more requests to make this happen and I think we then don't need to add this feature in the core if it can be easily implemented in userland code.

**Comment by chalasr** [comment]
I agree as well.

**Comment by nicolas-grekas** [comment]
Thanks for exploring the topic.

**Comment by rudiedirkx** [comment]
I haven't checked yet, but I believe @curry684. And agree that's a nicer solution. IF it's possible to get the list of commands from the very private `Application`.

The command specific strictness is still a cool idea, but that's another (new, not mine) issue.

**Comment by curry684** [comment]
You wouldn't need the command list as you have the Command and the original input, so you would only need to compare name to what was entered.
