### ISSUE TITLE
The router.options.generator_base_class  removed in 4.0

### ISSUE THREAD

**Issue by githublirui** [symfony/symfony#30833]
Hi
The Class parameters have been deprecated and will be removed in 4.0.

   * router.options.generator_class
   * router.options.generator_base_class

I want to custom generateUrl   ,How Can I configure The generator_class

Thanks

**Comment by stof** [comment]
What kind of customization do you want to do ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by yellow1912** [comment]
Hello,

My question also relates to these class parameters. Before in symfony 3.x I used to override the router.class parameter to use my own Router class. That way I can set the defaultLocale dynamically within the getGenerator method. I wonder how I should do this now in the new version of symfony.

**Comment by sstok** [comment]
@yellow1912 The best way to handle this is through service decoration 👍 
https://symfony.com/doc/current/service_container/service_decoration.html

Make sure to decorate the `router` service.
