### ISSUE TITLE
[Symfony/Form] Tag 3.4.23 (latest) not up2date with branch 3.4 / PHPUnit 8 Fix

### ISSUE THREAD

**Issue by mikemeier** [symfony/symfony#30832]
**Symfony version(s) affected**: 3.4.23

**Description**  
It looks like the PHPUnit 8 Version is now compatibel with all Symfony Versions. On the Branch 3.4 for example https://github.com/symfony/form/blob/3.4/Test/FormIntegrationTestCase.php the TestCaseSetUpTearDownTrait is already used.
On the other hand for the tag v3.4.23 (latest on 3.4 branch at the moment) is this code not released yet: https://github.com/symfony/form/blob/v3.4.23/Test/FormIntegrationTestCase.php

**How to reproduce**  
composer.json with `"symfony/symfony": "3.4.*"` and `"phpunit/phpunit": "^8.0"` can not run phpunit 8 tests for symfony form.

**Possible Solution**  
Create a new tag v3.4.24 with the actual code already existing in branch 3.4 for symfony/form.

**Comment by dmaicher** [comment]
`3.4.24` was released just now :wink: 

https://github.com/symfony/form/blob/v3.4.24/Test/FormIntegrationTestCase.php
