### ISSUE TITLE
May not inherit from final class

### ISSUE THREAD

**Issue by Igor9n** [symfony/symfony#30834]
**Symfony version affected**: 4.2

**Description**  
Can't use PHPUnit 8.0, because this error appears

"PHP Fatal error: Class Symfony\Bridge\PhpUnit\Legacy\TestRunnerForV7 may not inherit from final class (PHPUnit\TextUI\TestRunner) in /home/NIX/kruhliak/Projects/second/vendor/symfony/phpunit-bridge/Legacy/TestRunnerForV7.php on line 22"

**Comment by stof** [comment]
The PHPunit bridge is not yet compatible with PHPUnit 8. This is tracked in https://github.com/symfony/symfony/issues/30055 (and https://github.com/symfony/symfony/pull/30085 is a WIP for this particular issue)

**Comment by Igor9n** [comment]
Thank you for answer.
