### ISSUE TITLE
Deprecated message with the PantherTestCase

### ISSUE THREAD

**Issue by GILMorgan** [symfony/symfony#30835]
**Symfony version(s) affected**: x.y.z

**Description**  
Deprecated message : The "Symfony\Component\Panther\Client::submit()" method will require a new "array $serverParameters" argument in the next major version of its parent class "Symfony\Component\BrowserKit\Client", not defining it is deprecated.

**How to reproduce**  

<?php

namespace App\Tests\Functional;

use Symfony\Component\Panther\PantherTestCase;

class AControllerTest extends PantherTestCase
{

    public function testLogin()
    {
        $client = static::createPantherClient();

        $crawler = $client->request('GET', "http://127.0.0.1:800/connexion");
    }
}

**Possible Solution**  

Remove the @param array  $serverParameters from the phpdoc in the Symfony\Component\BrowserKit\AbstractBrowser line 315

**Additional context**

**Comment by deguif** [comment]
#eufossa
