### ISSUE TITLE
Access denied even after new role added

### ISSUE THREAD

**Issue by git00000** [symfony/symfony#30841]
**Symfony version(s) affected**: 4.2

**Description**  
I am building an affiliation system in my app. After user registered as an affiliate a new ROLE_AFFILIATE is added to the user. But user is denied access to route even after updating the isEqualeTo method. I have to logout first then login again in order to get things work.
Thanks you !

**Comment by sstok** [comment]
This seems more like a support question. https://symfony.com/support

Note that roles are stored in the Authentication Token and that if you add new roles to a User entity this will not automatically update the token, if you added the `isEqualTo` method you also need to implement the `Symfony\Component\Security\Core\User\EquatableInterface` for this to take effect.

**Comment by xabbuh** [comment]
This looks like a duplicate of #12025.
