### ISSUE TITLE
A dot in the name of an environment causes problems

### ISSUE THREAD

**Issue by davidkmenta** [symfony/symfony#30845]
**Symfony version(s) affected**: 4.2.5

**Description**  
A dot in the name of an environment causes problems with cache loading.

```bash
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined constant 'Container7x1NQ4E\srcApp_KernelTest' in /symfony-project/var/cache/test.dev/srcApp_KernelTest.devDebugContainer.php:5
```

**How to reproduce**  
Set the APP_ENV to the `test.env` for example... or run console with `--env=test.dev`.

**Comment by Raulnet** [comment]
the Cache use the environnement for create the name of Class cache. An the name of class is broken by the dot. Change the dot with an underscore `test.dev` => `test_dev`
`class srcApp_KernelTest.devDebugContainer extends Container`
 `class srcApp_KernelTest_devDebugContainer extends Container` and that fix the problème

**Comment by drupol** [comment]
I just reproduced the issue.

Log: https://pastebin.com/azNGLLiG
