### ISSUE TITLE
[DI] Bug with services declared in separated file

### ISSUE THREAD

**Issue by odolbeau** [symfony/symfony#30854]
**Symfony version(s) affected**: 4.2.4 (not tested on previous versions)

**Description**
Services declared in a separate file imported in `services.yaml` are not initialized correctly.
It looks like the `autowire: false` is not taken into account? :thinking: 

**How to reproduce**
See relevant commit in this dedicated repository:
https://github.com/odolbeau/symfony_dic_bug/commit/97d710645efae62d0fe1c50b586b96f46a6f8767

I have the following error:
```
Circular reference detected for service "App\Storage\CacheStorage", path: "App\Storage\CacheStorage -> App\Storage\CacheStorage".
```

If you move the configuration from `custom_services.yaml` to `services.yaml` & remove the `imports` at the beginning of the file, it works as expected.
If you remove the `imports` at the beginning of the `services.yaml` and include `custom_services.yaml` from the Kernel (method: `configureContainer`) it works as expected as well.

**Comment by mbabker** [comment]
This is expected behavior.  As the note says on [this line](https://github.com/odolbeau/symfony_dic_bug/blob/97d710645efae62d0fe1c50b586b96f46a6f8767/config/services.yaml#L12) the `_defaults` node only applies to the current file.  So you'd have to redeclare that in each file.

**Comment by nicolas-grekas** [comment]
@mbabker is right, that's why things are robust: they're local.

**Comment by odolbeau** [comment]
You can add:
```
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
```
in the imported file, the problem remains the same.

As I said it works when I include the given file from the Kernel instead of from the existing `services.yaml` file. Which means, the `_defaults` is not the problem here I guess?

ping @nicolas-grekas

**Comment by odolbeau** [comment]
BTW, declared services do not use autowiring at all.

**Comment by nicolas-grekas** [comment]
That's because the last declared service wins, which happens to be the one that the `App\` line loads in services.yaml - after the import.

Here is an idea that should solve the issue:
```diff
diff --git a/config/services.yaml b/config/services.yaml
index d470180..e851dc5 100644
--- a/config/services.yaml
+++ b/config/services.yaml
@@ -6,25 +6,5 @@
 parameters:
 
 imports:
+    - { resource: 'services_defaults.yaml' }
     - { resource: 'custom_services.yaml' }
-
-services:
-    # default configuration for services in *this* file
-    _defaults:
-        autowire: true      # Automatically injects dependencies in your services.
-        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
-
-    # makes classes in src/ available to be used as services
-    # this creates a service per class whose id is the fully-qualified class name
-    App\:
-        resource: '../src/*'
-        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
-
-    # controllers are imported separately to make sure services can be injected
-    # as action arguments even if you don't extend any base controller class
-    App\Controller\:
-        resource: '../src/Controller'
-        tags: ['controller.service_arguments']
-
-    # add more service definitions when explicit configuration is needed
-    # please note that last definitions always *replace* previous ones
diff --git a/config/services_defaults.yaml b/config/services_defaults.yaml
new file mode 100644
index 0000000..573336d
--- /dev/null
+++ b/config/services_defaults.yaml
@@ -0,0 +1,17 @@
+services:
+    # default configuration for services in *this* file
+    _defaults:
+        autowire: true      # Automatically injects dependencies in your services.
+        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
+
+    # makes classes in src/ available to be used as services
+    # this creates a service per class whose id is the fully-qualified class name
+    App\:
+        resource: '../src/*'
+        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
+
+    # controllers are imported separately to make sure services can be injected
+    # as action arguments even if you don't extend any base controller class
+    App\Controller\:
+        resource: '../src/Controller'
+        tags: ['controller.service_arguments']
```

**Comment by odolbeau** [comment]
OK, makes sense!
Sorry for this useless issue and thanks for your explanations! :)

**Comment by Taluu** [comment]
Then shouldn't in the generated appkernel from the recipe include the services.yml *first* and then only the ones included in `config/packages` ?

**Comment by proArtex** [comment]
@nicolas-grekas but it works fine if I declare the service inside services_dev.yaml for example. Does it win by declaring last? Changing Kernel's loading order doesn't make sense, so it works fine even if services_dev.yaml goes first.

**Comment by proArtex** [comment]
I would expect autowiring has less priority than services defined by hands independently from the declaration order.
