### ISSUE TITLE
Can't install http-foundation on a new symfony 2.8

### ISSUE THREAD

**Issue by dTrimon** [symfony/symfony#30855]
**Symfony version(s) affected**:2.8.49

**Description**  

On my way to upgrade a 2.7 project, I first migrate it to 2.8
Then I encounter a problem with http-foundation so I tried a project from scratch...

**How to reproduce**  
php composer.phar create-project symfony/framework-standard-edition my_project_name "2.8.*"
php  -d memory_limit=-1 composer.phar require symfony/http-foundation

The result issues a "Your requirements could not be resolved to an installable set of packages."
"

**Comment by Raulnet** [comment]
Symfony 2.8 require ` "php": ">=5.3.9" ` but the last version "4.2.5" of symfony/http-foundation require `"php":" ^7.1.3"`
add the version for your requirement can solve it.
`composer require symfony/http-foundation:2.8.49`

**Comment by stof** [comment]
if you make `composer require symfony/http-foundation`, it will probably apply a requirement on version 4.2 of the component. But a project based on the standard edition already depends on `symfony/symfony`, which contains symfony/http-foundation. So you won't be able to install a different version (btw, the composer error message would probably mention that, but you truncated it when providing it)

**Comment by nicolas-grekas** [comment]
Closing as there is no bug here.

**Comment by dTrimon** [comment]
In fact It try to install version 3.4 of http-foundation. 
I can't find any http-foundation on a standard project after installation!
:
Using version ^3.4 for symfony/http-foundation
 - Installation request for symfony/http-foundation ^3.4 -> satisfiable by symfony/http-foundation[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Installation request for symfony/symfony 2.8.* -> satisfiable by symfony/symfony[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].

**Comment by xabbuh** [comment]
The `symfony/symfony` package already provides the HttpFoundation component. Older Composer versions accidentally allowed to install a replaced package in a different version but this bug has been fixed in Composer and this is not possible anymore. You either need to keep using HttpFoundation 2.8 for now, update the `symfony/symfony` to 3.4 or require all components explicitly in the version you need to be able to mix 2.8 and 3.4 components.
