### ISSUE TITLE
[HttpClient] + [BrowserKit] wrong ContentType 

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#30867]
**Symfony version(s) affected**: 4.3

**Description**  
When using BrowserKit with the new HTTP client, form submited don't use the `application/x-www-form-urlencoded` anymore.

**How to reproduce**  
```
$browser = new HttpBrowser();
$crawler = $browser->request('GET', '...');
$form = $crawler->filter('#loginForm')->form([
  'foo' => 'bar',
]);
$crawler = $browser->submit($form);
```

Using goute:
```
header: Content-Type: application/x-www-form-urlencoded
body: foo=bar
```

Using HttpClient
```
header: "content-type: multipart/form-data; boundary="_=_symfony_1554420844_51f5d9435f5d60a6325e892d77e3d1f2_=_""
body: 
--_=_symfony_1554420844_51f5d9435f5d60a6325e892d77e3d1f2_=_
Content-Type: text/plain; charset=utf-8; name=Foo
Content-Transfer-Encoding: 8bit
Content-Disposition: form-data; name=foo

bar
```

The requested server (an 3rd party app behind a Microsoft IIS) accept the first one, but reject the second

**Comment by fabpot** [comment]
Both are valid. What does "reject" mean? What is the error message?

**Comment by jderusse** [comment]
indeed, both are valid, but the second one does not act like a real browser. When using BrowserKit to crawl a 3rd party website, this one does not recognize the submited form.

Here is a reproduct case:
```php
$call = function($client) {
  $crawler = $client->request('GET', 'https://sts.eursc.eu/adfs/ls/?lc=2057&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline');
  $form = $crawler->filter('#loginForm')->form([
    'UserName' => 'foo',
    'Password' => 'bar',
  ]);
  $crawler = $client->submit($form);
  return $crawler->html();
};
\file_put_contents('/tmp/a', $call(new \Goutte\Client()));
\file_put_contents('/tmp/b', $call(new \Symfony\Component\BrowserKit\HttpBrowser()));
```

diff /tmp/a /tmp/b
```diff
--- /tmp/a
+++ /tmp/b
@@ -184,15 +184,15 @@
     <div id="loginArea">
         <div id="loginMessage" class="groupMargin">Sign in with your organizational account</div>

-        <form method="post" id="loginForm" autocomplete="off" novalidate="novalidate" onkeypress="if (event &amp;&amp; event.keyCode == 13) Login.submitLoginRequest();" action="/adfs/ls/?lc=2057&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;client-request-id=2f1f763b-1fd4-43b4-1100-008000dc0190">
+        <form method="post" id="loginForm" autocomplete="off" novalidate="novalidate" onkeypress="if (event &amp;&amp; event.keyCode == 13) Login.submitLoginRequest();" action="/adfs/ls/?lc=2057&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;client-request-id=00000000-0000-0000-3600-008000b00070">
             <div id="error" class="fieldMargin error smallText">
-                <span id="errorText" for="">Incorrect user ID or password. Type the correct user ID and password, and try again.</span>
+                <span id="errorText" for=""></span>
             </div>

             <div id="formsAuthenticationArea">
                 <div id="userNameArea">
                     <label id="userNameInputLabel" for="userNameInput" class="hidden">User Account</label>
-                    <input id="userNameInput" name="UserName" type="email" value="foo" tabindex="1" class="text fullWidth" spellcheck="false" placeholder="someone@example.com" autocomplete="off">
+                    <input id="userNameInput" name="UserName" type="email" value="" tabindex="1" class="text fullWidth" spellcheck="false" placeholder="someone@example.com" autocomplete="off">
                 </div>

                 <div id="passwordArea">
@@ -211,7 +211,7 @@
         </form>

              <div id="authOptions">
-        <form id="options" method="post" action="https://sts.eursc.eu:443/adfs/ls/?lc=2057&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;client-request-id=2f1f763b-1fd4-43b4-1100-008000dc0190">
+        <form id="options" method="post" action="https://sts.eursc.eu:443/adfs/ls/?lc=2057&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;client-request-id=00000000-0000-0000-3600-008000b00070">
             <script type="text/javascript">
                 function SelectOption(option) {
                     var i = document.getElementById('optionSelection');
```

The request with `HttpBrowser` didn't trigger the "invalid username/password" meaning that the server (sorry, I don't have logs) did not recognize the posted form.

**Comment by fabpot** [comment]
Without any more information, I would not change anything to the current implementation.

**Comment by jderusse** [comment]
Agreed with you, that both content-type should be handled by the servers. 
But fact is, it's not the case, and given I don't own theme, I can't fix theme. Here are a liste of other services that don't handle the BrowerKit's payload.

* newrelic.com // Ignore input
* stackoverflow.com // TIMEOUT
* connect.symfony.com // 503

> The BrowserKit component simulates the behavior of a web browser

Combining BrowserKit with HttpClient, does not **truly** "emulate" a web browser and cannot be used anymore to scrap external web site. :-(

**Comment by nicolas-grekas** [comment]
Can you send a PR? It should be possible to use multipart only when a file upload is needed.

**Comment by fabpot** [comment]
@jderusse Fair enough.Let's only use the multipart enctype only when dealing with files. The patch should be quite easy. Up for a PR?

**Comment by jderusse** [comment]
sure!

BTW testing symfony connect is a good use-case because it also return a 503 when the request is chunked

**Comment by dandumit** [comment]
How did you fixed it ?  I was making good use of Goutte. now any site that's hosted on IIS returns 503...
Thank you,
Daniel

**Comment by gggeek** [comment]
I think I'm still afflicted by this bug - using the components at 6.4.24.

When a form has a file field, setting the value of the field to `null` in a call to `submitForm` still results in the form being sent with `multipart/form-data` content type.
On the receiving end of the submit there is a PHP script, and it does not grok the request enough to populate the `$_POST` array.

The workaround I found is to manually do the same work as in the `submitForm` method, and in the middle of it sneak in a `$form->remove('MyFileField');` call.

I think the issue might be that, in the code introduced in #30876, there is a loop checking for file fields - but it should skip any such field which has no file being sent...
