### ISSUE TITLE
[Console] broken terminal after running tests

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#30861]
On 3.4, 4.2, master:

When I run the tests of the Console component, my terminal ends up being broken.
Running this is enough to reproduce:
`./phpunit src/Symfony/Component/Console/ --filter testCommandWithQuestionsButNoInputs`

If I revert #30271, the issue is gone.
ping @chalasr if you have any idea why

**Comment by chalasr** [comment]
Test green on my side (OSX), same on travis/appveyor. 
Looks like a platform issue, is there anything special in your setup? e.g. non stable php version?

**Comment by Simperfit** [comment]
I'm taking this one for the euchackaton
