### ISSUE TITLE
[mailer] S/MIME Support

### ISSUE THREAD

**Issue by liberpater** [symfony/symfony#30875]
**Description**  
It would be great if the symfony/mailer component supported S/MIME.

**Example**  
SwiftMailer currently supports it, to provide an example: https://swiftmailer.symfony.com/docs/messages.html#signed-encrypted-message

**Comment by sstok** [comment]
I will try to work on this :+1: I did the initial work for this feature.

#eu-fossa

**Comment by sstok** [comment]
I guess this should be part of the Mime component instead 🤔
