### ISSUE TITLE
How to use NotCompromisedPasswordValidator in tests/dev?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#30871]
Asked on https://symfony.com/blog/new-in-symfony-4-3-compromised-password-validator
What's the recommended way to test/dev with the validator added on entities via annotations?

**Comment by stof** [comment]
Maybe we could register a no-op ConstraintValidator for that constraint in testing mode (not sure about dev mode though)

**Comment by nicolas-grekas** [comment]
Using a MockHttpClient could do it also, not sure how easy it would be though.

**Comment by lyrixx** [comment]
It would be nice to be able to use DIC parameter:
```php
/**
 * Assert\NotPwnedValidator(disabled="%kernel.debug%")
 */
private $email
```

**Comment by stof** [comment]
Well, this `enabled` option is in the Validator, not in the constraint. So you would not apply it in the annotation.
But FrameworkBundle could indeed have a configuration option to disable the validation logic (similar to what we do for the strict mode of the email validator)

**Comment by curry684** [comment]
Given that this issue will come up more frequently now that we have an HTTP client - shouldn't we introduce some global setting that disables all external dependencies, that defaults to `framework.testing`?
