### ISSUE TITLE
[http-client] pending request throws exception on __destruct and hide the original exception

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#30954]
**Symfony version(s) affected**: 4.3

**Description**  
When starting 2 async requests, and ignoring the second request for instance because the first request fails and we are dealing with it.
Then, if the 2nd request fails too, it triggerrs an exception that hide the previous one.

**How to reproduce**  
```php
        $client = HttpClient::create();
        $a = $client->request('GET', 'http://www.symfony.com/404');
        $b = $client->request('GET', 'http://www.symfony.com/404');

        try {
            $a->getContent();
        } catch (ClientExceptionInterface $e) {
            // no need to go further
            throw new \RuntimeException('boom');
        }
```
Here, the caller get a `ClientExceptionInterface` related to the 2 request. Wheras the `boom` exception were expected.

**Possible Solution**  
Hacky solution from a developper point of view: swallowing all pending requests and ignoring errors
```php
        $client = HttpClient::create();
        $a = $client->request('GET', 'http://www.symfony.com/404');
        $b = $client->request('GET', 'http://www.symfony.com/404');

        try {
            $a->getContent();
        } catch (ClientExceptionInterface $e) {
            // finish $b
            $b->getStatusCode();

            // no need to go further
            throw new \RuntimeException('boom');
        }
```

**Comment by lyrixx** [comment]
I already had this bug. I can confirme it. Thanks for the reproducer

**Comment by nicolas-grekas** [comment]
To reproduce the code above needs to run in a method/closure. I don't there is anything we can do here: if you hit endpoints that return 4xx/5xx, you must deal with them yes. The fact that technically this has more precedence over the userland exception is also legit as it saves you from accidentally missing a call that you might have expected to succeed otherwise.

You can take over this by checking the status code yourself, and passing `false` as argument when calling getContent()/getHeaders()

**Comment by jderusse** [comment]
I don"t get any use-case where user forsake a reponse but expect it to trigger exceptions. :-(

IMHO Checking the statusCode (either manually with `getStatusCode()` or automatically with `getContent(true)`/`getHeaders(true)` should be the only way to deal with server's response.

**Comment by jderusse** [comment]
closing as `$client->request(..)` is also a valid way to perform a request without taking care about the response BUT expecting to be notified in case of issue.
