### ISSUE TITLE
[HttpClient] CurlHttpClientTest::testHttp2Push is not executed

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#30975]
**Symfony version(s) affected**: 4.3-dev

**Description**  
The unit test `Symfony\Component\HttpClient\Tests\CurlHttpClientTest::testHttp2Push()` is never executed. The reason for that is that the used annotation `@requires extension curl 7.61` targets the version of the curl _extension_ (which is usually equal to the php version) and not (as it probably was intended) the version of the libcurl library.

**How to reproduce**  
Run the test suite with php 7.3.4 and libcurl 7.61

**Possible Solution**  
Remove the annotation (and fix the red test).

**Comment by nicolas-grekas** [comment]
let's remove the annotation then and replace it with a runtime check (see the one in CurlHttpClient)
the test is green locally :)

**Comment by derrabus** [comment]
At least it was red when I tried to run it without the annotation. I'll make the change and see what Travis says.

**Comment by gharlan** [comment]
I can confirm the error after removing the annotation:

![Screenshot 2019-04-10 18 58 17](https://user-images.githubusercontent.com/330436/55898371-b9c52980-5bc2-11e9-9a03-6204f98889db.png)

**Comment by chalasr** [comment]
Seems like the runtime check is not good enough (for both test and implementation)

```
1) Symfony\Component\HttpClient\Tests\CurlHttpClientTest::testHttp2Push
Failed asserting that Array &0 (
    0 => 'Request: "GET https://http2-push.io/"'
    1 => 'Response: "200 https://http2-push.io/"'
    2 => 'Request: "GET https://http2-push.io/css/style.css"'
    3 => 'Request: "GET https://http2-push.io/js/http2-push.js"'
    4 => 'Response: "200 https://http2-push.io/css/style.css"'
    5 => 'Response: "200 https://http2-push.io/js/http2-push.js"'
) is identical to Array &0 (
    0 => 'Request: GET https://http2-push.io/'
    1 => 'Queueing pushed response: https://http2-push.io/css/style.css'
    2 => 'Queueing pushed response: https://http2-push.io/js/http2-push.js'
    3 => 'Response: 200 https://http2-push.io/'
    4 => 'Connecting request to pushed response: GET https://http2-push.io/css/style.css'
    5 => 'Connecting request to pushed response: GET https://http2-push.io/js/http2-push.js'
    6 => 'Response: 200 https://http2-push.io/css/style.css'
    7 => 'Response: 200 https://http2-push.io/js/http2-push.js'
).
```

`echo curl_version()['version_number'];`  gives me `472576` locally
