### ISSUE TITLE
setCircularReferenceHandler() is deprecated

### ISSUE THREAD

**Issue by dhaarbrink** [symfony/symfony#30998]
**Symfony version(s) affected**: 4.2.5

**Description**  
When I enable a circular reference handler in my framework.yaml, I get a deprecation warning in my logs

**How to reproduce**  
Enable a circular reference handler in your framework.yaml:

```
serializer:
  enabled: true
  circular_reference_handler: Cbp\Utils\CircularReferenceHandler
```

**Possible Solution**  
The FrameworkExtension reads the config, and calls `setCircularReferenceHandler()` on `AbstractNormalizer`, but instead it should set it as a default context.

**Additional context**

**Comment by Raulnet** [comment]
@dhaarbrink the argument `circular_reference_handler` should be define on the `$context` params
not on the config;
ex: 
```php 
    $defaultContext = [
            'circular_reference_handler' => new CircularReferenceHandler(),
        ];

        $normalizer = new GetSetMethodNormalizer(null, null, null, null, null, $defaultContext);
...

        $customContext = [
            'circular_reference_handler' => new MyCustomCircularReferenceHandler(),
        ];        
        $normalizer->denormalize($data, $class, $format, $customContext);
```
Status: Waiting feedback

**Comment by dhaarbrink** [comment]
Well, according to the [docs](https://symfony.com/doc/current/components/serializer.html#handling-circular-references), you should use `setCircularReferenceHandler()`. So, there's a mismatch between the code and the docs. One of them contains a bug.

And then there's the 'circular_reference_handler' config option in the FrameworkBundle, which is passed to the `setCircularReferenceHandler()` method. So, there's another bug there.

**Comment by xabbuh** [comment]
We need to update the docs and fix the code.

**Comment by dhaarbrink** [comment]
Okay, so the docs are fixed. Thanks for that @javiereguiluz!

Now I think there is one bug left: calling `setCircularReferenceHandler()` from the `FrameworkExtension`.
