### ISSUE TITLE
[VarDumper] Internal state of the HTTP client should not be dumped when dumping a response

### ISSUE THREAD

**Issue by stof** [symfony/symfony#31009]
The dump of the response is huge currently, as it contains the internal state of the client.

This should probably wait for #30967 as that changes the internals.

**Comment by nicolas-grekas** [comment]
I already added a caster for responses, that cut the "multi" property. What else do you mean?

**Comment by stof** [comment]
This was based on a discussion in the train yesterday when going back from Brussels. Maybe the feedback I got came from someone using the HttpClient before you patch :smile:

**Comment by nicolas-grekas** [comment]
Or using VarDumper <=4.2 yes, see https://github.com/symfony/symfony/blob/4e1244ecdbada0d29cdec412e4d01621dc88cae6/src/Symfony/Component/VarDumper/Caster/SymfonyCaster.php#L44

I'm closing then, please tell if there is something wrong.
