### ISSUE TITLE
[BrowserKit] BC-break since Client has been renamed to Browser

### ISSUE THREAD

**Issue by Devristo** [symfony/symfony#31039]
**Symfony version(s) affected**: 4.3.x-dev

**Description**  
Since https://github.com/symfony/symfony/pull/30541 the inheritance hierarchy of `\Symfony\Component\BrowserKit\Client` has changed. Notably the `test.client` no longer is an instance of `\Symfony\Component\BrowserKit\Client`. 

This breaks breaks at least https://github.com/FriendsOfBehat/SymfonyExtension and https://github.com/minkphp/MinkBrowserKitDriver and most probably other bundles using `test.client`.

**How to reproduce**  

On Symfony 4.2 the following test case succeeds, on the master (4.3) branch this fails:

```php
class TestClientTest extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase {
    public function testIsAClient()
    {
        $browser = static::createClient();
        $this->assertInstanceOf(\Symfony\Component\BrowserKit\Client::class, $browser);
    }
}
```

**Possible Solution**  
Use a `class_alias` solution as described in https://github.com/symfony/symfony/pull/30541.

**Comment by nicolas-grekas** [comment]
Deprecating the test.client service in favor of test.browser might work also
PR welcome

**Comment by stof** [comment]
Well, deprecating the service will not solve the BC break, where the different Client BC classes are not child of each other anymore.

**Comment by Devristo** [comment]
@stof see the discussion in https://github.com/symfony/symfony/pull/31040. We have concluded the same and came with a different approach.

**Comment by stof** [comment]
yeah, I saw it after commenting here.
