### ISSUE TITLE
MimeType for symfony twig template

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#31045]
**Description**  
Do you think that twig template should deserve a place in MimeType extensions guesser ?
One might want to upload a twig template...

At the moment [MimeTypeExtensionGuesser](https://github.com/symfony/symfony/blob/74ca91deaa014a4e776671bfc523bd10077a52eb/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php) doesn't "support" uploading Twig templates

**Suggestion**  
```'application/twig' => 'twig'``` might be a good example

**Comment by nicolas-grekas** [comment]
>  One might want to upload a twig template...

do you have a use case for that yourself?
why would this be required to allow twig files to be uploaded?

**Comment by cybernet** [comment]
it’s exactly that !
you can either accept the pull request or you don’t.
you are the maintainers of the app, so you should do what you think it’s best
after all, it’s “your” MimeType. 
... that’s all folks:)

**Comment by fabpot** [comment]
I agree with both https://github.com/symfony/symfony/pull/31109#discussion_r275458302 and https://github.com/symfony/symfony/pull/31086#issuecomment-483010007, so let's close.
