### ISSUE TITLE
Missing stopwatch component gives inaccurate message in profiler

### ISSUE THREAD

**Issue by linaori** [symfony/symfony#31056]
**Symfony version(s) affected**: 3.4+

**Description**  
When you are missing the stopwatch component, you can't see the timings in the webdeveloper toolbar. When you navigate through the WDT via the "n/a" timings, you will arrive at a page saying: _"No timing events have been recorded. Are you sure that debugging is enabled in the kernel?"_. While this message is a good hint, my application _is_ running in debug, so it's only one of a few cases. Luckily I knew a missing stopwatch could cause missing timings, but I can imagine this to be very difficult to find for a developer with less Symfony experience.

**How to reproduce**  
1. Ensure the stopwatch component is not installed (no indirect dependencies either).
2. Ensure your application is running in debug
3. Load a page and verify the timing is saying "n/a": 
![image](https://user-images.githubusercontent.com/1754678/55871142-51f2ec80-5b8a-11e9-9534-6591120eb86d.png)
4. Open this specific WDT link
5. You will see the following:
![image](https://user-images.githubusercontent.com/1754678/55871195-7058e800-5b8a-11e9-8dd0-b14625e59fca.png)

**Possible Solution**  
I think the easiest solution would be to detect whether or not the stopwatch component is installed. If not, pass that information to the collected data, so we can show a different message: https://github.com/symfony/symfony/blob/fd1408b13869a381fbebf9b9967f7a80e8b141d3/src/Symfony/Component/HttpKernel/DataCollector/TimeDataCollector.php#L38-L51

```php
# TimeDataCollector would look like this
use Symfony\Component\Stopwatch\Stopwatch;

$this->data = [
    'token' => $response->headers->get('X-Debug-Token'),
    'start_time' => $startTime * 1000,
    'events' => [],
    'stopwatch_installed' => class_exists(Stopwatch::class, false),
];
```

```twig
{% if not collector.stopwatch_installed %}
    <div class="empty">
        <p>The stopwatch component is not installed. If you want to see timing events, run <code>composer require symfony/stopwatch</code></p>.
    </div>
{% else if collector.events is empty %}
    <div class="empty">
        <p>No timing events have been recorded. Are you sure that debugging is enabled in the kernel?</p>
    </div>
{% else %}
    {{ block('panelContent') }}
{% endif %}
```

**Additional context**
Current location of the template code triggered:
https://github.com/symfony/symfony/blob/fd1408b13869a381fbebf9b9967f7a80e8b141d3/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.html.twig#L98-L104

**Comment by stof** [comment]
@linaori can you send a PR with your patch ?

**Comment by linaori** [comment]
I'll make a PR
