### ISSUE TITLE
[BCBreak][DoctrineBridge] Listeners lazy loading is not transparent

### ISSUE THREAD

**Issue by malarzm** [symfony/symfony#31051]
**Symfony version(s) affected**: 4.2.5

**Description**  
If some listeners are removed from `ContainerAwareEventManager` before being initialized they can not be added back if any event was dispatched in the meantime. This happens because [`dispatchEvent` marks specific groups of events as initialized](https://github.com/symfony/symfony/blob/2243bf5bc11e3908f975f92551bd869a61211999/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L63) BUT `addEventListener` checks [whether anything was intialized](https://github.com/symfony/symfony/blob/2243bf5bc11e3908f975f92551bd869a61211999/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L102)

**Possible Solution**  
Maybe if a listeners is a string the container should be always checked whether it has a service defined under that name? That should allow adding lazy loaded listeners after construction. Other option might be to initialize listeners in `getListeners` but I don't know how it is used internally by Symfony.

**Additional context**  
In our app we're disabling and re-enabling Doctrine events mostly to disable FosElastica events for batch operations. This is no longer possible.

**Comment by malarzm** [comment]
Actually the fact that `ContainerAwareEventManager::getListeners` may return an array of strings breaks original `EventManager::getListeners` return type which is `object[]|object[][]`. I'm leaning towards intializing listeners during `getListeners` call.

**Comment by malarzm** [comment]
This actually might have been an issue hidden for a longer time and exposed by making all listeners lazy as a default in https://github.com/symfony/symfony/issues/27661

**Comment by dmaicher** [comment]
@malarzm I agree that this seems a bit odd.

Can you try this patch? Does it make sense to you?

```diff
diff --git a/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php b/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php
index 66b99ecf62..659c478619 100644
--- a/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php
+++ b/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php
@@ -93,16 +93,10 @@ class ContainerAwareEventManager extends EventManager
      *
      * @param string|array  $events   The event(s) to listen on
      * @param object|string $listener The listener object
-     *
-     * @throws \RuntimeException
      */
     public function addEventListener($events, $listener)
     {
         if (\is_string($listener)) {
-            if ($this->initialized) {
-                throw new \RuntimeException('Adding lazy-loading listeners after construction is not supported.');
-            }
-
             $hash = '_service_'.$listener;
         } else {
             // Picks the hash code related to that listener
@@ -113,6 +107,10 @@ class ContainerAwareEventManager extends EventManager
             // Overrides listener if a previous one was associated already
             // Prevents duplicate listeners on same event (same instance only)
             $this->listeners[$event][$hash] = $listener;
+
+            if (\is_string($listener)) {
+                unset($this->initialized[$event]);
+            }
         }
     }

**Comment by malarzm** [comment]
@dmaicher I can give it a spin on Monday although my tests may still fail. I noticed that we also have logic for blocking chosen listeners, for which an `instanceof` check is performed on listeners returned by `ContainerAwareEventManager::getListeners`  and those can fail if service returns strings instead of actual objects. I think that listeners should be initialized in the `getListeners` method to adhere to parent method's return type.
