### ISSUE TITLE
UrlMatcher BC break

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#31066]
**Symfony version(s) affected**: 4.1.11 

**Description**  
With version `4.1.2`, urls with trailing slash were not matched, in `4.1.11` they are. I guess it's related to https://symfony.com/doc/4.1/routing.html#routing-trailing-slash-redirection, but it's a BC break.

**How to reproduce**  

I created demo project https://github.com/umpirsky/SUMT which makes it easy to prove this two versions are not behaving the same way while using Symfony public API which should be stable across minor upgrades:

```
git clone git@github.com:umpirsky/SUMT.git
composer install
git checkout master
./vendor/bin/phpunit src/Umpirsky/SUMT/UrlMatcherTest.php
PHPUnit 8.1.2 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 28 ms, Memory: 4.00 MB

OK (2 tests, 2 assertions)

git checkout 4.1.11
composer install

./vendor/bin/phpunit src/Umpirsky/SUMT/UrlMatcherTest.php
PHPUnit 8.1.2 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 33 ms, Memory: 4.00 MB

There was 1 failure:

1) Umpirsky\SUMT\UrlMatcherTest::testDontMatch
Failed asserting that exception of type "Symfony\Component\Routing\Exception\ResourceNotFoundException" is thrown.

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

**Comment by nicolas-grekas** [comment]
Please upgrade to 4.2 as 4.1 is not maintained anymore and this might have been fixed already.

**Comment by umpirsky** [comment]
Reproduced with `4.2.5`:

```
git checkout 4.2
composer install

./vendor/bin/phpunit src/Umpirsky/SUMT/UrlMatcherTest.php
PHPUnit 8.1.2 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 24 ms, Memory: 4.00 MB

There was 1 failure:

1) Umpirsky\SUMT\UrlMatcherTest::testDontMatch
Failed asserting that exception of type "Symfony\Component\Routing\Exception\ResourceNotFoundException" is thrown.

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

**Comment by nicolas-grekas** [comment]
Is this the same as https://github.com/symfony/symfony/issues/30863?

**Comment by umpirsky** [comment]
This does not have to do anything with redirection, but route matching. This can be related to https://github.com/symfony/symfony/issues/30863, but I'm not sure if it is.

**Comment by nicolas-grekas** [comment]
I think we're not going to change the current behavior. There have been many back and forth on the topic and things are pretty stable right now around the current behavior. Sorry to ask you to do so, but please update/reorder your routes to make them work.

**Comment by umpirsky** [comment]
I'm using `UrlMatcher` directly, I built a tool around it and relied on stable API. I need trailing slash urls to behave differently then regular ones, like they did in the old versions, no route reorder can prevent matching trailing slash urls.

If I define route with path `/foo/{bar}`, I expect it to match `/foo/bar` and not `/foo/bar/`.

**Comment by nicolas-grekas** [comment]
With #31107, `/foo/{bar}` will `/foo/bar/` redirect to `/foo/bar`, unless a preceding route takes over.

**Comment by umpirsky** [comment]
Yes, and that is a BC break.

If it's not going to be fixed I have two options:

1. Stick with `4.1.2`
1. Add some ugly workaround like this in my code:

```diff
+ if (ends_with($url, '/') && $url === rtrim($url, '/')) {
+     throw new ResourceNotFoundException();
+ }

$urlMatcher->match($url);
```

**Comment by nicolas-grekas** [comment]
Or updating the routes you define I believe. Without knowing more about your use case and your route collection, I'm not sure I can help you more, but the behavior change is likely not going to be reverted..

**Comment by umpirsky** [comment]
OK, let's imagine https://github.com/umpirsky/SUMT/blob/master/src/Umpirsky/SUMT/UrlMatcherTest.php is my use case. How can route update keep the tests pass?

**Comment by nicolas-grekas** [comment]
With #31107, tests pass on my machine.

**Comment by umpirsky** [comment]
What version of Symfony?

**Comment by umpirsky** [comment]
Great, thanks!

But it will never be perged into `4.1`, right?

**Comment by nicolas-grekas** [comment]
Nope: https://symfony.com/roadmap/4.1

**Comment by umpirsky** [comment]
:(
