### ISSUE TITLE
PHPUnit exception with WebTestCase and HttpException

### ISSUE THREAD

**Issue by bohdanyurov-gl** [symfony/symfony#31079]
**Symfony version(s) affected**: 4.2.5

**Description**  
![image](https://user-images.githubusercontent.com/47155283/55973465-4daff780-5c8e-11e9-8e4a-c23197daa5a4.png)
![image](https://user-images.githubusercontent.com/47155283/55973497-602a3100-5c8e-11e9-99d4-0ce0c8ccd40c.png)

Instead of correct test passing I observe this:
There was 1 error:
1) ......\OauthProxy\Tests\Controller\ProxyControllerTest::testToken
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Token is not present

**How to reproduce**  
Call an action that throws HttpException from phpunit test case.

**Possible Solution**  
ExceptionListener from framework bundle might be incorrectly handling http exceptions for virtual requests.

**Additional context**  
$client->catchExceptions() method seems to be not affecting anything.

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by bohdanyurov-gl** [comment]
Additional info: this only affects symfony/skeleton, not symfony/webapp-skeleton

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
