### ISSUE TITLE
remove phpunit/phpunit

### ISSUE THREAD

**Issue by 12rambau** [symfony/symfony#31081]
**Symfony version(s) affected**: 4.2.3

**Description**  
following the courses of [openClassroom](https://openclassrooms.com/fr/courses/4087056-testez-et-suivez-letat-de-votre-application-php/4419436-mise-en-place-dun-outil-pour-implementer-ses-tests-unitaires) I've starting using PHPUnit but at the end of the installation of the dependencies the framework throw a warning and strongly suggest to use PHPUnit bridge instead. 

But the suggested command `composer remove --dev phpunit/phpunit` lead to the following error 
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
Script @auto-scripts was called via post-update-cmd
```

It's look like a bug to me, is there any solution to start testing my application ?

**Comment by williamjehanne** [comment]
Can you try
`composer remove --dev phpunit/phpunit --no-scripts`

**Comment by 12rambau** [comment]
It works but that was only hiding the problem because any time I send the `composer update` command I get the error again. 

I've search and the problem was coming from the installation. The course suggest to use the `composer require phpunit/phpunit` so the command `composer require --dev phpunit/phpunit` was unable to remove everything. I installed it again and use the command without the `--dev` option and it work like a charm. 

Conclusion, it was no bug just me ;-)
