### ISSUE TITLE
Infinite loop in BundleEntryReader after updating php7.2-intl to 7.2.17 which installs libicu64

### ISSUE THREAD

**Issue by megawilddaddy** [symfony/symfony#31089]
PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
SYMFONY: Symfony 4.2.4

locale_parse('root') now return an empty array as opposed to previos php versions which makes the Symfony\Component\Intl\Data\Bundle\Reader loop through fallback locales as 

"en" => "root" => "" => "root" => "" and so on without it becoming null to break the loop

when reading from the regions because in the Symfony\Component\Intl\Locale::getFallback()
we never get inside the if (1 === \count($localeSubTags))

![testedLocales](https://user-images.githubusercontent.com/1647204/56029378-e8f2ac80-5d22-11e9-9b2f-6a88e0d6e934.png)

**Comment by ro0NL** [comment]
confirmed :+1: PR welcome i guess :)

**Comment by enricog84** [comment]
I just had the same issue after upgrading to php version 7.1.28 from 7.1.27.
Using latest symfony 3.4.24 fixed the issue. Imo the additional check in Location.php in the pull request #30781 fixed the issue.

**Comment by ro0NL** [comment]
So this is fixed in 4.2.5, @megawilddaddy can you try upgrading to see if it solves your issue as well?

**Comment by megawilddaddy** [comment]
Yes, upgrading to 4.2.5 fixed the issue. 
Thanks guys!

**Comment by vkhramtsov** [comment]
@ro0NL Do we have any chance to get this fix for 2.8 version?

**Comment by jakzal** [comment]
@vkhramtsov no, [2.8 only receives security fixes](https://symfony.com/roadmap) at this point.

**Comment by vkhramtsov** [comment]
@jakzal I agree that it is not security fix, but this bug makes symfony completely unusable in some cases

**Comment by vkhramtsov** [comment]
@fabpot  What do you think?

**Comment by vkhramtsov** [comment]
Anyway I've forked and fixed intl

**Comment by vkhramtsov** [comment]
@fabpot Thank you for clarification

**Comment by alexander-schranz** [comment]
We had the same problem on some projects so we did overwrite the Locale.php class of the symfony/intl. The package is available under https://github.com/sulu/symfony-intl-fix. But I really would recommend to update to 3.4 and only use it as a temporary solution.

EDIT: See also @TomasVotruba comment if you want to use vendor patches composer plugin: https://github.com/symfony/symfony/issues/31089#issuecomment-1157488106

**Comment by TomasVotruba** [comment]
@alexander-schranz Thanks for sharing the solution :clap: 
 We're just upgrading from Symfony 2.8 and this is one infinite loop blocker.

**Note for similar legacy upgrades**: exact commit that fixes it: https://github.com/symfony/intl/commit/d2ac83703951bc3206e9ea3f6114b355de14e3ce
Then use [vendor patches](https://github.com/symplify/vendor-patches) or similar to apply to your `/vendor`. Works like a charm :+1:
