### ISSUE TITLE
Symfony uninstall not working

### ISSUE THREAD

**Issue by joeyhub** [symfony/symfony#31096]
When I try to uninstall symfony using composer it doesn't work.

Steps to reproduce:

```composer remove symfony/symfony```

**Comment by juuuuuu** [comment]
@joeyhub What is the error reported when you execute this command?

**Comment by joeyhub** [comment]
```Error: Not uninstall working, exiting.```

**Comment by Simperfit** [comment]
@joeyhub Could you please post the whole stacktrace ?

**Comment by xabbuh** [comment]
And please also show the complete output you get.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
