### ISSUE TITLE
cannot executing php bin/phpunit

### ISSUE THREAD

**Issue by 12rambau** [symfony/symfony#31098]
**Symfony version(s) affected**: 4.2.3

**Description**  
following the courses of [openClassroom](https://openclassrooms.com/fr/courses/4087056-testez-et-suivez-letat-de-votre-application-php/4419436-mise-en-place-dun-outil-pour-implementer-ses-tests-unitaires) and following your advice I've starting using PHPUnit-bridge. At the end of the installation, the shell suggest me to use the command `php bin/phpunit` to start my only test but after the installation of dependencies (phpunit 6.5) it stops. 

And if I relaunch the command the only output is `#!/usr/bin/env php`

Is it a normal behavior ? did I miss something ?

**Comment by juuuuuu** [comment]
Could you give more information about what you mean when you say `it stops`?
Also, can you give us all the steps that lead you to this point (which commands did you use)?

**Comment by 12rambau** [comment]
**Symfony Version affected:** 4.2.3 
**php version:** 7.1.2

**command executed so far:** 
`composer require --dev symfony/phpunit-bridge` (installation of the version 4.2)
`php bin/phpunit`

**output:**  
``` bash
#!/usr/bin/env php
Installing phpunit/phpunit (5.7.27)
Plugins have been disabled.
  - Installing phpunit/phpunit (5.7.27): Loading from cache
Created project in phpunit-5.7
composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 25 installs, 0 updates, 0 removals
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing sebastian/exporter (2.0.0): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.3.2): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/environment (2.0.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (2.0.1): Loading from cache
  - Installing symfony/phpunit-bridge (5.7.99): Symlinking from /Users/pierrickrambaud/Sites/team-manager/vendor/symfony/phpunit-bridge
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
```
Test report from phpUnit should be following (according to the documentation) but for me `it stops` (I have no other words to describe it). 

I've dig into the `simple-phpunit` file  and what I found is that it doesn't execute php unit test because I don't have `$components` [here](https://github.com/symfony/phpunit-bridge/blob/7083ed25d46a9680ec41d6da70f6d32f7ac593df/bin/simple-phpunit#L197). This [comment](https://github.com/symfony/phpunit-bridge/blob/7083ed25d46a9680ec41d6da70f6d32f7ac593df/bin/simple-phpunit#L172) makes me wonder if I am supposed to enter this conditional (I'm on a MacOs station) but if It's the only way to have `$component` then my problem is in the definition of `$_server[argv]` and I have no clue where it's defined....

**Comment by Tobion** [comment]
I fear you need to debug what it "stops". Maybe some permission error when trying to generate the autoload files.

**Comment by nicolas-grekas** [comment]
Would you be able to provide e.g. a ZIP file we could use to reproduce the behavior you experience?
Otherwise, we might close this issue as there is nothing actionable right now.

**Comment by 12rambau** [comment]
I've tried on another computer before doing the ZIP file and it worked perfectly. My conclusion is that the removal of phpUnit to install phpUnit-bridge procedure didn't work properly. To conclude I don't know what happen but I cannot reproduce the behavior on another computer. I'll try to debug my computer and if I find what doesn't work I'll post an answer.

**Comment by xabbuh** [comment]
Let's close here for now then. We can still reopen anyway once we are able to reproduce it.

**Comment by 12rambau** [comment]
Now it was realy impossible to continue working on my project without runnig some tests. I'm more experienced with php and find the error. There were a typo in my `class` definition 
```php 
use PHPUnit\Framework\WebTestCase;

class BlogControllerTest extends WebTestCase
{
    public function firstTest()
    {
        $this->assertEquals(0,0);
    }
}
```

by changing it to :
```php
use PHPUnit\Framework\TestCase;
```
which actually exist make everything just fine. So it was just a typo and saddly no error message was triggered. thx for your time and sorry for my mistake.
