### ISSUE TITLE
[Mailer] stream_socket_enable_crypto php warning about crypto type

### ISSUE THREAD

**Issue by scuben** [symfony/symfony#31105]
**Symfony version(s) affected**:
4.3-dev

**Description**  
When using the `EsmtpTransport` transport with `tls` encryption I receive a PHP warning:
````
PHP Warning:  stream_socket_enable_crypto(): When enabling encryption you must specify the crypto type in .../vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php on line 156
````

**How to reproduce**  
````
$transport = (new EsmtpTransport('example.com', 587, 'tls'))
    ->setUsername('...')
    ->setPassword('...');
````

**Possible Solution**  
Honestly I have no clue on how `stream_socket_enable_crypto` should work, sorry.

**Comment by scuben** [comment]
After reading the documentation and doing a test the third parameter should be `STREAM_CRYPTO_METHOD_ANY_CLIENT`.

**Comment by sstok** [comment]
Some background:

https://wiki.php.net/rfc/improved-tls-defaults
https://github.com/zendframework/zend-http/issues/105

## New Constants

`STREAM_CRYPTO_METHOD_ANY_CLIENT`

Crypto method interpreted as “any client crypto method we can possibly support.” Applications may use this method for maximum compatibility with SSLv2, SSLv3, TLSv1, TLSv1.1 and TLSv1.2 servers.

`STREAM_CRYPTO_METHOD_ANY_SERVER`

Crypto method interpreted as “any server crypto method we can possibly support.” Applications may use this method for maximum compatibility with SSLv2, SSLv3, TLSv1, TLSv1.1 and TLSv1.2 clients.

`STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT`

Crypto method flag allowing specific TLSv1 usage in encrypted client streams.

`STREAM_CRYPTO_METHOD_TLSv1_0_SERVER`

Crypto method flag allowing specific TLSv1 usage in encrypted server streams.

------

**`STREAM_CRYPTO_METHOD_ANY_CLIENT` basically accepts any client which is extreme risky as this makes it possible to perform downgrade attacks.**

Better to use `STREAM_CRYPTO_METHOD_TLS_CLIENT` or even `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` (which however may not be supported everywhere).

**Comment by fabpot** [comment]
My reasoning for not passing the third parameter is that it allows one to configure it from the outside via the SSL context options.

**Comment by bpolaszek** [comment]
@fabpot it looks like the 3rd parameter is mandatory as soon as `$enabled` is ` true`, or an ErrorException will be raised because of the warning, and the message won't be sent. 

I'm not an expert at this level but is there a way to ensure it's properly configured from the outside before calling the function?

**Comment by fabpot** [comment]
@bpolaszek Looks like you're right. Let's find the "best" option here. Would you like to work on a PR for this?

**Comment by bpolaszek** [comment]
@fabpot something like this?
