### ISSUE TITLE
User Deprecated: The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead

### ISSUE THREAD

**Issue by methodeprog** [symfony/symfony#31104]
**Symfony version(s) affected**: 4.2.5
Dear value member, i need help !
**Description**  

Try to deploy on Heroku by Bitbucket.
After the Build on Bitbucket, i'm facing issue on the deployement on Heroku.

ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]        
// Clearing the cache for the prod environment with debug 
// false 
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /tmp/build_33aa4e2c419827c17c13238050291573/vendor/twig/twig/src/Node/Expression/FunctionExpression.php on line 21
[2019-04-14 07:36:41] php.INFO: User Deprecated: The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead. at /tmp/build_33aa4e2c419827c17c13238050291573/vendor/twig/twig/src/TokenParser/SpacelessTokenParser.php:33)"} [] 

**How to reproduce**  

**Possible Solution**  

![Sans titre-1](https://user-images.githubusercontent.com/18600282/56089967-c67fa100-5e92-11e9-917e-411b9edb2791.jpg)

**Additional context**

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
