### ISSUE TITLE
Configuring framework.ide when xdebug.file_link_format is set causes exception.

### ISSUE THREAD

**Issue by j4nr6n** [symfony/symfony#31119]
**Symfony version(s) affected**: 4.2

**Description** 
I did this:
```yaml
framework:
    ide: '%env(IDE_PATH)%'
```
and this:
```ini
xdebug.file_link_format = "phpstorm://open?url=file://%f&line=%l"
```
and got this:
![image](https://user-images.githubusercontent.com/3661151/56157087-a59b7680-5f8c-11e9-9768-ae8ca683b793.png)

I'm not sure what I expected to happen. I didn't expect an exception by overriding an environment variable though.

**How to reproduce** 
The good news is, there's a [reproducer app](https://github.com/j4nr6n/reproducer-app).
The bad news is you have to set `xdebug.file_link_format` to get the error.

**Possible Solution** 
¯\\\_(ツ)_/¯

**Comment by nicolas-grekas** [comment]
you can work around this by either adding `IDE_PATH=` in your `.env` file or defining a parameter named `env(IDE_PATH)` in you `services.yaml` file.

Otherwise, the behavior is consistent with the behavior of env vars, no bug here.

**Comment by j4nr6n** [comment]
The exception is still thrown both when the `IDE_PATH` env var is defined/in `.env` and when the parameter is defined in `services.yaml`.

**Comment by nicolas-grekas** [comment]
Got it, see #31302
