### ISSUE TITLE
Split the logic of Response::isNotModified()

### ISSUE THREAD

**Issue by ktherage** [symfony/symfony#31111]
**Description**  
Just a short question about `Response::isNotModified()` (https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/HttpFoundation/Response.php#L1059), can we split his logic into two differents functions and use them in it?

I mean that, IMO, it is confusing with HTTP Specification to have on method checking `If-Modified-Since` request headers which is associated with `Last-Modified` response header AND at the same time checking `ETag` response header which is associated to  `If-None-Match` request header in the same function.

**Example**  
Maybe we could do (draft code, could be invalid):
```php
    /**
     * Determines if the Response validators (ETag, Last-Modified) match
     * a conditional value specified in the Request.
     *
     * If the Response is not modified, it sets the status code to 304 and
     * removes the actual content by calling the setNotModified() method.
     *
     * @return bool true if the Response validators match the Request, false otherwise
     *
     * @final
     */
    public function isNotModified(Request $request): bool
    {
        $notModified = $this->isModifiedSince($request) || $this->isNoneMatch($request);
        if ($notModified) {
            $this->setNotModified();
        }

        return $notModified;
    }

    public function isModifiedSince(Resquest $request): bool
    {
         if (!$request->isMethodCacheable()) {
            return false;
        }
        $lastModified = $this->headers->get('Last-Modified');
        $modifiedSince = $request->headers->get('If-Modified-Since');

        return $modifiedSince && $lastModified ?? strtotime($modifiedSince) >= strtotime($lastModified);
    }

    public function isNoneMatch(Resquest $request): bool
    {
         if (!$request->isMethodCacheable()) {
            return false;
        }
        $etags = $request->getETags()
        
        return !$etags ||  \in_array($this->getEtag(), $etags) || \in_array('*', $etags);
    }
```

WDYT?

**Comment by derrabus** [comment]
What would be the use-case of such a change?

**Comment by Simperfit** [comment]
I would like to see a real case that needs this to be changed. Could you explain why you would need it ?

**Comment by ktherage** [comment]
@derrabus @simperfit That change will be to offer the possibility to only check ETag or Last-Modified if you only got one of them. 

Maybe it is not needed or it is a kind of micro optimization but IMO this would stick more to the HTTP doc and so getting the things less complicated when looking at the Symfony code. 

Have a good weekend.

**Comment by fabpot** [comment]
I don't get the use case. When would you want to check ETags without Last-Modified or the other way around? Splitting the method does not really make sense to me as the `isNotModified()` method allows to set the method to 304 when needed:

```php
        if ($response->isNotModified($request)) {
            return $response;
        }
```
