### ISSUE TITLE
generate:bundle adding incorrect syntax to example into ./Bundle/Resources/config/services.yml file

### ISSUE THREAD

**Issue by sterichards** [symfony/symfony#31116]
**Symfony version(s) affected**: 3.4

**Description**  
When using `bin/console generate:bundle` the example entry that gets added to ./Bundle/Resources/config/services.yml is using double quotes where is should be single quotes. Double quotes are deprecated for use in services.yml in Symfony 3.4

**How to reproduce**  
`php bin/console generate:bundle`

**Possible Solution**  

**Additional context**

**Comment by dmaicher** [comment]
Actually the generator functionality is provided by this bundle: https://github.com/sensiolabs/SensioGeneratorBundle
