### ISSUE TITLE
Duplicated attributes while rendering form with null block prefix

### ISSUE THREAD

**Issue by secit-pl** [symfony/symfony#31127]
**Symfony version(s) affected**: 4.2.6

**Description**  
Rendering form with null block prefix duplicates the form default attributes in rendered html. This is major problem if we'd like to add id attribute to it as id should be unique in whole HTML document.

**How to reproduce**  

Create form as follows

```php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BugType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'attr' => [
                'id' => 'duplicate',
                'foo' => 'bar',
            ],
        ]);
    }

    public function getBlockPrefix()
    {
        return null;
    }
}
```
Pass it to the twig as follows:

```php
<?php

namespace App\Controller;

use App\Form\BugType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $form = $this->createForm(BugType::class);

        return $this->render('index/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}
```
And than render it using Twig

```twig
{{ form(form) }}
```

The result will be:

```html
<form method="post" id="duplicate" foo="bar">
    <div id="duplicate" foo="bar">
        <input type="hidden" id="_token" name="_token" value="psSwaT9qr427m_jWqmu7qo1cgbsZ5f-lxcHEcTpeGcY"/>
    </div>
</form>
```
as you can see form and div have the same attributes.

**Comment by stof** [comment]
`null` is not a valid block prefix. The signature of the method in the interface is `@return string`. So this cannot be considered as a bug in Symfony.

If you want to have a form with an empty root name, the solution is to use `\Symfony\Component\Form\FormFactory::createNamed`, not to use `null` as the block prefix (the block prefix is used the the *default* name, but it controls much more than that, as its main goal is to control the form theming).

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because of the reasons given by @stof. Thanks.
