### ISSUE TITLE
[3.4.25][BC Break] 403 instead of 401 for unauthorized users

### ISSUE THREAD

**Issue by JarJak** [symfony/symfony#31136]
**Symfony version(s) affected**: 3.4.25

**Description**  
Symfony now returns 403 instead of 401 for unauthorized users.

**How to reproduce**  
1. Create controller with a security voter like `$this->denyAccessUnlessGranted(...)`
2. Try to access this route with an unauthorized user
3. Observe different status codes (401 in 3.4.24 vs 403 in 3.4.25)

**Possible Solution**  
Undo this change, or at least provide instructions how to revert to old behavior, or at least mention it explicitly in the changelog / upgrade files.
Even if the change is good (IMO 403 is better, see http://www.dirv.me/blog/2011/07/18/understanding-403-forbidden/index.html) this is a BC Break for apps that react on 401 status but not on 403.

**Comment by curry684** [comment]
It's most certainly more correct according to protocol.

**Comment by JarJak** [comment]
But it's a BC break and not a security issue.

**Comment by curry684** [comment]
I agree, I [even mentioned it before](https://github.com/symfony/symfony/pull/30423#issuecomment-480510058) that it's a BC break because of the behavioral change. I didn't foresee it would cause the other return code though, nor did any of the other reviewers apparently.

I'd say revert it in 3.4 an 4.2 and ship the change with documentation for 4.3.

**Comment by nicolas-grekas** [comment]
A BC break wouldn't be more acceptable in 4.3 than in 3.4.25.
And any bug fix in a BC break for someone.
We have to decide where we stand between these two lines.

**Comment by JarJak** [comment]
@nicolas-grekas it depends what you define by bug fix... this one was only about status code change from 403 to 401 and definitions of these codes are soft... it is more an improvement than a bug fix

**Comment by fabpot** [comment]
I think it should have been merged in master instead.

**Comment by curry684** [comment]
> And any bug fix in a BC break for someone.

Yes we decided then to ignore the behavioral break per the "it's a break for everyone" argument, but nobody correctly foresaw the functional break. 403 instead of 401 could cause far greater breakage, ie. in external API clients etc.

**Comment by JarJak** [comment]
@fabpot can it be reverted in 3.4.26 ?

**Comment by nicolas-grekas** [comment]
Please send PRs

**Comment by JarJak** [comment]
@nicolas-grekas It's just about reverting https://github.com/symfony/symfony/commit/fd1408b13869a381fbebf9b9967f7a80e8b141d3 on 3.4 branch. @curry684 do you agree?

**Comment by chalasr** [comment]
See #30423.
