### ISSUE TITLE
[HttpKernel] Invalid VERSION_ID in Kernel

### ISSUE THREAD

**Issue by jeromegamez** [symfony/symfony#31149]
**Symfony version(s) affected**: 2.8.50

**Description** 

`Symfony\Component\HttpKernel\Kernel::VERSION_ID` is an unquoted `2.8.50` instead of `20850`, causing a PHP Syntax error.

**How to reproduce**  

```bash
php -l src/Symfony/Component/HttpKernel/Kernel.php
```

**Possible Solution**  

```diff
- const VERSION_ID = 2.8.50;
+ const VERSION_ID = 20850;
```

:octocat:

**Comment by fabpot** [comment]
fixed now
