### ISSUE TITLE
symfony/routing: "Notice: Undefined offset: 1"

### ISSUE THREAD

**Issue by AbdelilahJbr** [symfony/symfony#31158]
**Symfony version(s) affected**: 4.2.7

**Description**  
When I updated to 4.2.7, I can't access to my routes if I add a '/', it gives me a Notice: Undefined offset: 1.
I cleared the cache using : bin/console cache:clear, doesn't work
then I deleted the folder var/cache : doesn't work

**How to reproduce**  
If I access to "/api/collaborators" it works but accessing to "/api/collaborators/" gives the error

**Additional context**  
![image](https://user-images.githubusercontent.com/44052672/56346269-a6652000-61b9-11e9-8720-7f67144c74d2.png)

**Comment by nicolas-grekas** [comment]
Thanks for the report, fixed in #31167
