### ISSUE TITLE
Update to 4.2.7 - Fatal error: Interface 'TranslatorInterface' not found 

### ISSUE THREAD

**Issue by greenphp** [symfony/symfony#31152]
**Symfony version(s) affected**: 4.2.7

**Description**  
After my composer update from 4.2.6 to 4.2.7 I get the following fatal error.

```
Fatal error: Interface 'Symfony\Component\Translation\TranslatorInterface' not found 
in testarea_symfony_api\vendor\symfony\validator\Util\LegacyTranslatorProxy.php
 on line 21

In LegacyTranslatorProxy.php line 21:

  Attempted to load interface "TranslatorInterface" from namespace "Symfony\Component\Translation".
  Did you forget a "use" statement for "Symfony\Contracts\Translation\TranslatorInterface"?
```

**How to reproduce**  

Upgrade from  4.2.6 to 4.2.7 via composer update.

**Comment by jsamouh** [comment]
same error

**Comment by jmunozco** [comment]
same error

**Comment by fdbatista** [comment]
does anyone have a solution for this? update seems fine, but i´m getting this problem when trying to issue php bin/console doctrine:cache:clear

**Comment by TomaszGasior** [comment]
> does anyone have a solution for this? update seems fine, but i´m getting this problem when trying to issue php bin/console doctrine:cache:clear

https://github.com/symfony/symfony/pull/31108#issuecomment-484184993

**Comment by fdbatista** [comment]
> > does anyone have a solution for this? update seems fine, but i´m getting this problem when trying to issue php bin/console doctrine:cache:clear
> 
> [#31108 (comment)](https://github.com/symfony/symfony/pull/31108#issuecomment-484184993)

thanks!

**Comment by dqblanco** [comment]
Same error. For the moment we go back to version 4.2.6.

**Comment by TomaszGasior** [comment]
Mailbox spammed by thousands of "same error" mails won't help them to fix it up. ;)

**Comment by nicolas-grekas** [comment]
> temporary add to requirements "symfony/translation": "4.2.*", to fix this

Thanks @Gemorroj for providing this workaround.
I'll have a look tomorrow, unless someone submits a PR meanwhile.

**Comment by goetas** [comment]
I have the same issue. 

The problem here is that `LegacyTranslatorProxy` exits, but it implements `Symfony\Component\Translation\TranslatorInterface` and `Symfony\Contracts\Translation\TranslatorInterface` that can be not available`, thus a fatal error is triggered in that case since is not possible to load the interfaces to complete `LegacyTranslatorProxy` defintions.

**Comment by jsamouh** [comment]
class_exist(LegacyTranslatorProxy::class) is the problem :-D.

**Comment by notrix** [comment]
Same error here

**Comment by xabbuh** [comment]
see #31156

**Comment by greenphp** [comment]
Hi. This bug report is closed but I still get this exception after updating to 4.2.7. 

Is this already fixed, or how can I apply a workaround to update to the latest version?

```
Fatal error: Interface 'Symfony\Component\Translation\TranslatorInterface' not found in "\testarea_symfony_api\vendor\symfony\validator\Util\LegacyTranslatorProxy.php on line 21

In LegacyTranslatorProxy.php line 21:

  Attempted to load interface "TranslatorInterface" from namespace "Symfony\Component\Translation".
  Did you forget a "use" statement for "Symfony\Contracts\Translation\TranslatorInterface"?
```

**Comment by TomaszGasior** [comment]
Something like this can help: https://github.com/TomaszGasior/RadioLista-v3/commit/1c8170df7f027e29ba7d9c5f9145e93a31aca590

**Comment by RikudouSage** [comment]
Or you can use this patch: https://github.com/symfony/symfony/commit/f49881d24a6d1483a054ce473e36bc0722cd8846.patch

For example with this patch package: https://github.com/cweagans/composer-patches

**Comment by chokrijobs** [comment]
`composer req symfony/translation`

**Comment by Spomky** [comment]
So the idea to solve that issue is to require something we don't need...
Prefer not to do that and wait for a better solution.

**Comment by stof** [comment]
the other solution is to install the dev version of FrameworkBundle, which already contains the patch, which will be part of the 4.2.8 release.

**Comment by RikudouSage** [comment]
@Spomky @stof Or use the `cweagans/composer-patches` package to patch it for you before they release it.

Then in composer.json:

```json
{
  "extra": {
    "patches": {
      "symfony/framework-bundle": {
        "Fix translator": "https://github.com/symfony/framework-bundle/commit/9c3f47e28e0ea66b762b99a8573d6d7acaa43244.patch"
      }
    }
  }
}
```

**Comment by featuriz** [comment]
I'm not using "symfony/translation" in my project, But I'm using symfony validator. Up to now it worked fine. Do I have to install "translation" eventhough I'm not using it? Is it so?

**Comment by xabbuh** [comment]
@featuriz You can do that for the moment as a workaround until the fix from #31156 is released with Symfony 4.2.8.

**Comment by featuriz** [comment]
@xabbuh "symfony/framework-bundle": "^4.2,!=4.2.7",
Do I have to do this?

**Comment by TomaszGasior** [comment]
@featuriz Just install translator and update framework bundle.

**Comment by RikudouSage** [comment]
@featuriz or use the patch approach:

https://github.com/symfony/symfony/issues/31152#issuecomment-485780174
