### ISSUE TITLE
Serializer object with ReflectionClass throws ReflectionException: does not have a prototype. 

### ISSUE THREAD

**Issue by bambucha4** [symfony/symfony#31157]
**Symfony version(s) affected**: 4.2.7, maybe later versions

**Description**  
Any array of objects with methods (getters and setters) passed to ControllerTrait::json as $data, throws a PHP ReflectionException: does not have a prototype.

**How to reproduce**  
Stacktrace points to the problem in PropetyAccess used in Symfony Serializer and finally in ControllerTrait::json.

**Possible Solution**  
I made a temporary function and I changed the serializer to JMS and working. 

**Additional context**  
```
{
    "class": "ReflectionException",
    "message": "Method App\\DTO\\KontrahentPocztaSerializer::getId does not have a prototype",
    "code": 0,
    "file": "/var/www/html/symfony/vendor/symfony/property-access/PropertyAccessor.php:372",
    "trace": [
        "/var/www/html/symfony/vendor/symfony/property-access/PropertyAccessor.php:372",
        "/var/www/html/symfony/vendor/symfony/property-access/PropertyAccessor.php:295",
        "/var/www/html/symfony/vendor/symfony/property-access/PropertyAccessor.php:90",
        "/var/www/html/symfony/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:132",
        "/var/www/html/symfony/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:132",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:152",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:162",
        "/var/www/html/symfony/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:157",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:152",
        "/var/www/html/symfony/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:157",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:152",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:162",
        "/var/www/html/symfony/vendor/symfony/serializer/Serializer.php:125",
        "/var/www/html/symfony/vendor/symfony/framework-bundle/Controller/ControllerTrait.php:127",
        "/var/www/html/symfony/src/Controller/WypisywaniePocztyController.php:207",
        "/var/www/html/symfony/vendor/symfony/http-kernel/HttpKernel.php:150",
        "/var/www/html/symfony/vendor/symfony/http-kernel/HttpKernel.php:67",
        "/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php:198",
        "/var/www/html/symfony/src/Kernel.php:1159",
        "/var/www/html/symfony/src/Kernel.php:1149",
        "/var/www/html/symfony/src/Kernel.php:453",
        "/var/www/html/symfony/src/KernelFactory.php:35",
        "/var/www/html/symfony/public/app.php:20"
    ]
}
```

In WypisywaniePocztyController:207 line I used: 
`return $this->json($arrayOfObjectsDTO);`

**Comment by stof** [comment]
Can you share a reproducing case ?

**Comment by bambucha4** [comment]
I found a problem on my side, but I do not know why he depends on inheritance. TestClass inherits from the AbstractDTO class, in which there is one of many methods: getReflectionClass. This method indicates **static::class** and so the call on the TestClass object will retrieve the **ReflectionClass** of this object. I need a method to avoid duplicating the code to check some data. Not important - deleting or commenting on this method solves the problem. Below is a description of two classes.

Weird Issue.

TestClass:
[https://pastebin.com/5Jq82hwk](https://pastebin.com/5Jq82hwk)

AbstractDTO:
[https://pastebin.com/hQywZhzF](https://pastebin.com/hQywZhzF)

Controller:
[https://pastebin.com/vh2B12iQ](https://pastebin.com/vh2B12iQ)

**Comment by stof** [comment]
hmm, maybe the serializer is trying to serializer the ReflectionClass too, by calling the public `getReflectionClass` method ? By default, the ObjectNormalizer will look at all public getters

**Comment by bambucha4** [comment]
It looks like it, but it should not change the state of the object in a significant way. Changing the visibility to the protected one has solved the problem.

**Comment by stof** [comment]
well, the thing is, ReflectionClass has a bunch of getter itself, and your error message seems to come from such chain: `ReflectionMethod::getPrototype` will throw if the method does not have a prototype (i.e. a definition in a parent class), which is what happens here.
So you would need to exclude the `getReflectionClass` from your serialization.

**Comment by bambucha4** [comment]
Okay, so everything is clear. Thank you for your answer and explanation.
