### ISSUE TITLE
[TWIG] File input, visible but no text

### ISSUE THREAD

**Issue by jean-gerard** [symfony/symfony#31159]
**Symfony version(s) affected**: x4.2.7

**Description**  

The bootstrap file input field is visible but has no text in it.

![image](https://user-images.githubusercontent.com/49748492/56350654-935b4b80-61cb-11e9-8261-121985399fee.png)

But if I add 

```css
.custom-file-input {
  opacity: 1!important;
}
```
The text is visible but the ugly button is too.

![image](https://user-images.githubusercontent.com/49748492/56350760-ca316180-61cb-11e9-9247-126b0ae40e1d.png)

**How to reproduce**  

I am using the bootstrap 4 template.
```yaml
#config/packages/twig.yaml
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
```

Generating the form like so : 
```php
$builder->add(
                'datafile',
                FileType::class,
                [
                    'label' => 'main.form.file',
                ]
);
```

And displaying it like so : 
```html
<div class="col-md-12 col-lg-6" id="main-form-holder">
    <div class="row form-group">
        <div class="col-md-3">{{ form_label(form.datafile) }}</div>
        <div class="col-md-9">{{ form_widget(form.datafile) }}</div>
    </div>
</div>
```

This problem appeared after updating from Symfony 4.0 to symfony 4.2 .

**Comment by stof** [comment]
It looks like the label inside the Bootstrap 4 custom-form-file is set based on the `placeholder` attr in the form theme. As you don't set one, this is why it is empty

**Comment by jean-gerard** [comment]
Thanks for your answer.
So, it seems that the `placeholder` attribute is needeed, So it display something when I do this : 

```twig
<div class="col-md-9">{{ form_widget(form.datafile, {'attr': {'placeholder': 'Choose a file'} }) }}</div>
```

Other option : 

```php
$builder->add(
                'datafile',
                FileType::class,
                [
                    'label' => 'main.form.file',
                    'attr' =>
                        [
                            'placeholder' => 'Choose a file',
                        ]
                ]
);
```

But the placeholder is not updated with the filename.
I guess i need to copy the JS from https://github.com/symfony/symfony/pull/27919#issuecomment-404163495 ?

**Comment by fabpot** [comment]
Closing as we are not using Github for support.
