### ISSUE TITLE
[Routing] Allow optional route parameters to not be at end of route

### ISSUE THREAD

**Issue by jrbarnard** [symfony/symfony#31166]
**Description**  
Currently optional parameters are restricted to being at the end of routes, docs here: https://symfony.com/doc/current/routing/optional_placeholders.html
However looking into the RouteCompiler and the generated regex it's relatively trivial to generate regex which would allow for optional parameters before the end of the route to work and match correctly.

E.g {optionalparameter}/world
/hello/world and /world would match.

The use case was actually found when working on a laravel project and getting locale prefixes to work optionally (as I'm using some middleware to detect if the locale is missing and then forcing a redirect to the locale specific route if none is present, however this currently doesn't work.

I could override the laravel route compiler potentially however I figured this would be a useful core feature of the symfony routing component.

**Example**  
Usage would be identical to currently, just with the possibility of having optional parameters before the end of the route.

**Specific info**
Example current regex being compiled:
```
#^/(?P<optionalparameter>[^/]++)/world$#sDu
```
Regex for this would be changed to:
```
#^(?:/(?P<optionalprefix>[^/]++))?/world$#sDu
```

I'm happy to do a PR for this, I just wanted to guage the interest in this feature

**Comment by Tobion** [comment]
Ref. #5424

**Comment by nicolas-grekas** [comment]
Right now, you can achieve this using two routes, right?
I think the matcher is complex enough: if adding a 2nd route works, we'd better not implement this.
If you think we can achieve this without adding significant complexity, we'd be happy to review a PR.

**Comment by jrbarnard** [comment]
You're definitely right for a few routes this can be achieved with multiple, however the use case that found me digging in to the matcher was a locale prefix.

Basically I wanted to be able to match routes with and without the locale so I could properly redirect to the locale prefixed versions based on the system / current user locale. For this case the prefix is a route group around the entire web routes so duplication wasn't really the best option.

I think the changes shouldn't add too much complexity to the matcher as it should only be targetting the first segment if it's optional.

I'll put together a PR and some tests

**Comment by nicolas-grekas** [comment]
For such use cases, I see two solutions:
- either register a listener that runs before RouterListener and extracts the locale before
- or import the routes twice, with and without a prefix.
That should do the job in a few lines for a bunch of routes.

**Comment by jrbarnard** [comment]
No worries, I can look at setting up a listener prior to the router to force a locale prefix instead.

**Comment by nicolas-grekas** [comment]
@jrbarnard note that if you want to give it a try, PRs are always welcome.

**Comment by jrbarnard** [comment]
@nicolas-grekas Thanks, I've been meaning to but haven't had an opportunity yet, I'll put something together this week.

**Comment by jrbarnard** [comment]
Closed PR
