### ISSUE TITLE
FrameworkBundle v4.2.7 assumes "translator" service implements the contract's translator interface

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#31161]
**Symfony version(s) affected**: 4.2.7

**Description**
SyliusThemeBundle overrides default `translator` service with the one that implements `Symfony\Component\Translation\TranslatorInterface` but not `Symfony\Contracts\Translation\TranslatorInterface`. This causes `Symfony\Component\Validator\Util\LegacyTranslatorProxy` to fail because it expects `translator` service to implement the contract's translator interface. It is a BC break AFAIK.

https://travis-ci.org/Sylius/Sylius/jobs/521619940#L834

**How to reproduce**  
Override `translator` service not to implement `Symfony\Contracts\Translation\TranslatorInterface` but `Symfony\Component\Translation\TranslatorInterface` instead.

**Possible Solution**  
 - make `Symfony\Component\Translation\TranslatorInterface` extend `Symfony\Contracts\Translation\TranslatorInterface`
 - allow `Symfony\Component\Translation\TranslatorInterface` instance to be passed to `Symfony\Component\Validator\Util\LegacyTranslatorProxy`

**Comment by nicolas-grekas** [comment]
Please check #31164
