### ISSUE TITLE
ESI , Follow the document but not work as expected

### ISSUE THREAD

**Issue by ascholar** [symfony/symfony#31180]
I had followed the document(https://symfony.com/doc/current/http_cache/esi.html),
but can not work
https://stackoverflow.com/q/55757707/11382376

**Comment by Simperfit** [comment]
Please provide more information in the issue, what is not working ? did you try to use the render_esi method in twig ?

If you read the documentation again, you can see that you can send query param with `render_esi` see:

```twig
{{ render_esi(controller('App\\Controller\\NewsController::latest', { 'maxPerPage': 5 })) }}
```

I'm using ESI in my real life application and it's working properly.

**Comment by ascholar** [comment]
Yes the code you show is right, but  if use this  code
`<!DOCTYPE html>
<html>
    <body>
        

        
        <esi:include src="http://..."/>

        
    </body>
</html>
`
it's never working as expected,

**Comment by Simperfit** [comment]
it's an exemple, you should not use that, you should use twig :p.

**Comment by ascholar** [comment]
a reason I use this style `<esi:include src="http://..."/>`  is I need  send some custom params
but `{{ render_esi(controller('App\\Controller\\NewsController::latest', { 'maxPerPage': 5 })) }}` cannot help

**Comment by ascholar** [comment]
like `<esi:include src="http://www.test.com/a/b?c=c1"/>`

**Comment by stof** [comment]
do you have an ESI-capable reverse proxy in front of your app ?

The `render_esi` function detects that and fallbacks to a subrequest if there is no reverse proxy. But if you render the ESI tag yourselves, you have to ensure that there is always such proxy.

Note that you can use `render_esi` with any URL, not only with the special `controller` function.

**Comment by ascholar** [comment]
in the document ,I cannot find a way to take  custom params with 'render_esi'

**Comment by stof** [comment]
And the `controller()` Twig function also supports passing query string parameters to the request, thanks to its third argument: https://symfony.com/doc/current/reference/twig_reference.html#controller

**Comment by ascholar** [comment]
I will try it.Thank a lot.

**Comment by ascholar** [comment]
It works properly !  `{{ render(controller('App\\Controller\\DefaultController::latestArticles', {num: 5})) }}` 
I should read more document.
Many thanks !
