### ISSUE TITLE
[HttpClient] Uncatchable fatal error on class destruction

### ISSUE THREAD

**Issue by Dcoutelle** [symfony/symfony#31187]
**Description**  
I use http-client in multimode, around with 20 parallel threads, around 1/10000 request running into a fatal error which is triggered by `CurlResponse` __destruct()

In ` __destruct()`, `$this->doDestruct()` is called, which can throw error with `$this->checkStatusCode();`

**How to reproduce**  
No idea... :/

**Possible Solution**  
at https://github.com/symfony/http-client/blob/master/Response/ResponseTrait.php#L233 remove `$this->checkStatusCode();`  ... why check code on destruct ?

**Comment by nicolas-grekas** [comment]
What's the error like? If the endpoint returns non 2xx status code, you should maybe add some logic to deal with it explicitly? I'd be interested you n having a look at some code is example if possible.
Thanks for playing with the client :)

**Comment by Dcoutelle** [comment]
Finally, error was catchable... but I don't think this behavior was intended when we use the client in multi mode.

## Original Code : 
```php
        /** @var \Symfony\Component\HttpClient\Response\CurlResponse $response */
        foreach ($client->stream($responses) as $response => $chunk) {
            $info = unserialize($response->getInfo()['user_data']);
            try {
                $isLast = $chunk->isLast();
                if ($isLast === true) {
                    $body = $response->getContent();
                } else {
                    usleep(50);
                }
            } catch
            (Exception $e) {
                $body = '';
                $isLast = true;
                ....
            }
            if ($isLast === true) {
                ....
            }
        }
```

## Error from Log : 
### initiated into ResponseTrait

```
PHP Fatal error: Uncaught Symfony\\Component\\HttpClient\\Exception\\ServerException: HTTP/1.1 502 Bad Gatewa returned for URL "http://....... ". in /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/ResponseTrait.php:211\nStack trace:
#0 /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/ResponseTrait.php(231): Symfony\\Component\\HttpClient\\Response\\CurlResponse->checkStatusCode()
#1 /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/CurlResponse.php(169): Symfony\\Component\\HttpClient\\Response\\CurlResponse->doDestruct()
#2 /home/algoadm/public_html/admin/script/class/update_vol_collection_manager.class.php(198): Symfony\\Component\\HttpClient\\Response\\CurlResponse->__destruct()
#3 /home/algoadm/public_html/admin/script/class/update_ in /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/ResponseTrait.php on line 211
```

### initiated into ErrorChunk
```
PHP Fatal error: Uncaught Symfony\\Component\\HttpClient\\Exception\\TransportException: Reading from the response stream reached the inactivity timeout. in /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Chunk/ErrorChunk.php:105\nStack trace:
#0 /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/CurlResponse.php(111): Symfony\\Component\\HttpClient\\Chunk\\ErrorChunk->__destruct()\n#1 /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/ResponseTrait.php(229): Symfony\\Component\\HttpClient\\Response\\CurlResponse::Symfony\\Component\\HttpClient\\Response\\{closure}(Object(Symfony\\Component\\HttpClient\\Response\\CurlResponse))
#2 /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Response/CurlResponse.php(169): Symfony\\Component\\HttpClient\\Response\\CurlResponse->doDestruct()
#3 /home/algoadm/public_html/admin/script/class/update_vol_collection_manager.class.php(198): Symfony\\Component\\HttpClient\\Response\\CurlResponse->__destruct()
#4 /home/algoadm/public_html in /home/algoadm/public_html/admin/composer/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 105
```

I think the error is thrown only if there is a problem in the last response or into the last chunk

The solution I found, is add below code before the end of my class to deconstruct "manually" each class and catch error :  
```php
        try {
            if (isset($response)){
                $response->__destruct();
            }
            if (isset($chunk) && $chunk instanceof \Symfony\Component\HttpClient\Chunk\ErrorChunk) {
                $chunk->__destruct();
            }
        } catch (Throwable $e) {

        }
``

**Comment by nicolas-grekas** [comment]
> $info = unserialize($response->getInfo()['user_data']);

You don't need to serialize the data here ;)

> usleep(50);

this should not be needed

About the errors, they are expected to me: you must deal with errors - only you know how you want to deal with 502 or timeouts.
The current logic in your examples simply ignores them. You might want to log them at the very least.

**Comment by alexschwarz89** [comment]
@nicolas-grekas I ran into the same issue and don't think it's a support issue. I have complete try...catch blocks over all functions - that should be enough. But as the exception is thrown on __destruct, they do not get catched. Calling some __destruct manually shouldnt be required?

Error only occurs if multiple responses are involved.

**Example code to reproduce**

`        $responses = [];

        $httpClient = HttpClient::create();

        try {
            $responses[] = $httpClient->request('GET', 'https://httpstat.us/500');
            $responses[] = $httpClient->request('GET', 'https://httpstat.us/404');
            $responses[] = $httpClient->request('GET', 'https://httpstat.us/503');
            $responses[] = $httpClient->request('GET', 'https://httpstat.us/500');
        } catch (\Exception $e) {
            print $e->getMessage();
        }

        // Async stream the responses
        try {
            foreach ($httpClient->stream($responses) as $response => $chunk) {
                try {

                    if ($chunk->isLast()) {
                        // some program logic
                    }
                } catch (\Exception $e) {
                    print $e->getMessage();
                }
            }
        } catch (\Exception $e) {
            print $e->getMessage();
        }`

**Error message**

`In ResponseTrait.php line 235:
                                                                  
  [Symfony\Component\HttpClient\Exception\ClientException (404)]  
  HTTP/1.1 404 Not Found returned for "https://httpstat.us/404".  
                                                                  

Exception trace:
  at /home/wwwroot/sf4/vendor/symfony/http-client/Response/ResponseTrait.php:235
 Symfony\Component\HttpClient\Response\CurlResponse->checkStatusCode() at /home/wwwroot/sf4/vendor/symfony/http-client/Response/ResponseTrait.php:251
 Symfony\Component\HttpClient\Response\CurlResponse->doDestruct() at /home/wwwroot/sf4/vendor/symfony/http-client/Response/CurlResponse.php:207
 Symfony\Component\HttpClient\Response\CurlResponse->__destruct() at /home/wwwroot/sf4/src/Command/CronUptimeCommand.php:83
 App\Command\CronUptimeCommand->execute() at /home/wwwroot/sf4/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/wwwroot/sf4/vendor/symfony/console/Application.php:952
 Symfony\Component\Console\Application->doRunCommand() at /home/wwwroot/sf4/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/wwwroot/sf4/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /home/wwwroot/sf4/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/wwwroot/sf4/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /home/wwwroot/sf4/bin/console:42`

**Versions**

Symfony 4.3.3
Http Client 4.3.3

**Comment by nicolas-grekas** [comment]
Still a support issue, the reason here is that you don't deal with the status code in the foreach loop.
Dealing with the status code must be done when `$chunk->isFirst()`.
What happens right now is that the first 500 throws on the foreach line, is caught by the very last catch block, then all remaining responses complete up to receiving headers, and throw again because they're not successful either. Thus they are not caught.
Dealing with the status code is a must :)

**Comment by alexschwarz89** [comment]
@nicolas-grekas Ok, lets call it a support issue, but you could maybe save some time if the documentation would tell about it? https://symfony.com/doc/4.3/components/http_client.html#multiplexing-responses

There is no word about the must of exception handling in a $chunk->isFirst thingy.

But solved my issue, thank you!
