### ISSUE TITLE
Expression language, define ENUM

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony#31191]
**Description**
In my app users can create their own rules with a wysiwyg editor.
For example they can write `article_status in ('DRAFT, 'PUBLISHED','randomValue')`

I want allow only `DRAFT` and `PUBLISHED` value. I think today is not possible with this component. We can extend Expression Language with an ExpressionFunction but I can't add restriction.

In this case define an ENUM of allowed values could be great.  

What do you think about this case ?

**Comment by fabpot** [comment]
I think the best it to create your own function to achieve this.
