### ISSUE TITLE
[Feature idea] Add ControllerInterface

### ISSUE THREAD

**Issue by dborsatto** [symfony/symfony#31206]
**Description** 
A pattern I've been seeing is to try and avoid implementing controllers by extending the base `AbstractController` class, and instead use simple classes which rely on DI instead. However, this makes you opt-out of having the container treat the class as a _controller_ and thus being able to request one-off parameters in action methods, therefore forcing you to request everything in the constructor. Currently Symfony is smart enough to looks for classes in `src/Controller` and treat everything in there as a controller, but if you're using an unconventional directory structure (for instance with DDD or CQRS projects) this will stop working.

A solution I've been thinking about is to introduce an empty `ControllerInterface`, which basically will act as a marker for the container to recognize controller classes. The current `AbstractController` will implement the new interface, therefore it should be a 100% backwards-compatible change.

I didn't want to go forward with an actual PR yet because I wanted to ask first whether this would be something worth doing. In case the answer to this is positive, I'll create the PR soon.

**Example**
```php
// Before
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MyController extends AbstractController
{
    public function someAction(Request $request, EntityManagerInterface $entityManager)
    {
        // ...
    }
}

// After
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\ControllerInterface;
use Twig\Environment;

class MyController implements ControllerInterface
{
    public function __construct(Environment $twig)
    {
        // ...
    }

    public function someAction(Request $request, EntityManagerInterface $entityManager)
    {
        // ...
    }
}

```

**Comment by derrabus** [comment]
You can already use any public service as a controller. What would be the added benefit of such an interface?

**Comment by dborsatto** [comment]
You don't get service injection in methods with regular services. With a controller, you can. This is a feature you can already use by extending `AbstractController`, but there are legitimate use cases where you might not want to do that.

What I'm proposing is basically to make a currently-available feature less strict and more flexible. You would be able to simply tag a class using the interface, and then action injection would be available regardless of where your controller is stored and whether you're extending the abstract class or not.

**Comment by jakzal** [comment]
> You don't get service injection in methods with regular services. With a controller, you can. This is a feature you can already use by extending AbstractController

You don't need to extend the AbstractController to get argument injection. You need to tag your controllers with `controller.service_arguments`. 

It's possible to achieve what you need in userland. Define your own interface and register a compiler pass that would tag all your controllers automatically.

**Comment by derrabus** [comment]
> You don't get service injection in methods with regular services.

No, you would need to tag them with `controller.service_arguments`. This happens via auto-configuration if you use the abstract controller. So, your suggestion would be a marker interface to trigger that same auto-configuration mechanism?

**Comment by dborsatto** [comment]
Yes. It's basically what already is happening with event subscribers, where you can use an interface and completely skip any container configuration.

**Comment by yceruto** [comment]
It seems that your proposal can be achieved through `_instanceof`? e.g:
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Controller\ControllerInterface:
            tags: ['controller.service_arguments']
```
wherever your controller is placed, you'll get this feature.

**Comment by derrabus** [comment]
Alternatively, with auto-configuration:

```php
class Kernel
{
    protected function build(ContainerBuilder $container): void
    {
        $container->registerForAutoconfiguration(\App\Controller\ControllerInterface::class)
            ->addTag('controller.service_arguments');
    }
}
```

**Comment by derrabus** [comment]
So apparently the patch for the framwork bundle would be easy as well: Add the empty interface to the codebase and add the two lines from my `build` method to `FrameworkExtension`.

The question is: Do we want that feature in the framework? Personally, I wouldn't add yet another way to define controllers to the core.

**Comment by dborsatto** [comment]
This is probably something I should have made clearer in my initial post: the goal of this change would be to improve DX. I know you can achieve this in userland by configuring the container (using instanceof, compiler passes, etc), but the goal would be to have a simple option which does not require you to know how the container works and how to tweak it.

As I said, this is something that is already happening somewhere else:

- when implementing `EventSubscriberInterface` you don't need to configure the container, because Symfony will know that your class is an event subscriber.
- `AbstractController` already lets you do this, but it has a tradeoff of forcing you to inherit from a big base class which does a lot and is container aware.

The proposed change will allow users to avoid having to extend a huge class such as `AbstractController` and instead just implement a marker interface, with no extra configuration required.

To be honest I'm quite surprised of the resistance I'm seeing. This helps DX, has zero impact on current users, removes the need for container-aware controllers, and has zero costs in terms of configuration required...

**Comment by xabbuh** [comment]
I am 👎 on adding this interface. This adds just another way to be able to register controllers which can soon become confusing for users. Also if you follow the standard directory structure and and config of a Symfony application your controllers located in the `Controller` namespace are automatically tagged without having to extend the `AbstractController` class (and as shown above if you have a different structure adding such an interface in userland can also be done to achieve the same).

This is by the way a bit different from the `EventSubscriberInterface` from the EventDispatcher component which is more than a marker interface as the `getSubscribedEvents()` method is needed to extract all the needed information (but we do not have an `EventListenerInterface` for example).

**Comment by dborsatto** [comment]
@xabbuh the recently-introduced `MessageHandlerInterface` is just an empty marker, though :slightly_smiling_face: 

Anyway, it seems that the consensus is that people don't want this, which I must say is a bit surprising considering the benefit of dropping the required inheritance from `AbstractController`. I'll leave this open for a little longer, but unless overwhelming support arrives, I'll close this later today/tomorrow :+1:

**Comment by derrabus** [comment]
> * `AbstractController` already lets you do this, but it has a tradeoff of forcing you to inherit from a big base class which does a lot and is container aware.

The `AbstractController` is not container-aware. It receives a service locator to lazy-load services that `AbstractController` uses internally. But that is by far not the entire service container.

But I fully understand that you don't want to extend that class. This is fine. I don't use that class either, tbh. 😉 

> To be honest I'm quite surprised of the resistance I'm seeing. This helps DX, has zero impact on current users, removes the need for container-aware controllers, and has zero costs in terms of configuration required...

If a feature is added, it needs to be documented, tested, maintained for several years etc. So before a feature is added, we should as ourselves how we could achieve the same goal without that feature and if that alternative is really worse that adding that feature to the core. Especially, when a userland implementation would be pretty easy.

> which I must say is a bit surprising considering the benefit of dropping the required inheritance from `AbstractController`.

Neither extending `AbstractController` nor having the container in your controller is a requirement. Your alternatives are:
* Tag your controller services with `controller.service_arguments`.
* Use constructor injection and make your controller service public.

Personally, I use the latter in my projects and it works pretty well.

**Comment by fabpot** [comment]
Closing as I agree with all commenters. Thanks for proposing.
