### ISSUE TITLE
[Form] Default value for choice_loader option in custom FormType with dynamically modified form

### ISSUE THREAD

**Issue by zefrog** [symfony/symfony#31209]
**Symfony version(s) affected**: 4.2.7

**Description**  
I am using a default choice_loader option in the `configureOptions` method of a custom `FormType` (extending `AbstractType`, having `ChoiceType` as a Parent).
That `choice_loader` option is an instance of `CallbackChoiceLoader` that takes as a constructor argument a callback returning the result of the call of a custom method of the FormType using a dependency injected in its constructor.

The problem is that sometimes my custom type depends on another field. Using the tutorial in the docs https://symfony.com/doc/current/form/dynamic_form_modification.html results in a problem on the `POST_SUBMIT` event, because the CallbackChoiceLoader has already been populated in the `PRE_SET_DATA` event.

**How to reproduce**  
Example of a FormType having that problem:

```php
namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\

class CustomType extends AbstractType
{
    private $service;

    private $customOption;

    public function __construct($service) 
    {
        $this->service = $service;
    }

    public function getChoices()
    {
        return $this->service->getChoices($this->customOption);
    }

    public function configureOptions(OptionsResolver $resolver) 
    {
        $resolver->setDefaults([
            'choice_loader' => new CallbackChoiceLoader([$this, 'getChoices']),
            'custom_option' => '123',
        ]);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->customOption = $options['custom_option'];
    }

    public function getParent()
    {
        return ChoiceType::class;
    }
}
```
In the FormType using the `CustomType`:

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('field', ChoiceType::class, [
            'choices' => ['123' => '123', '456' => '456'],
        ]);
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $e) {
            $e->getForm()->add('custom', CustomType::class); 
        });

        $builder->get('field')->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $e) {
            $e->getForm()->getParent()->add('custom', CustomType::class, [
                'custom_option' => $e->getData(), // the option is passed but never used afterwards.
            ]);
        });
    }
```
The `getChoices` method is called once for the `PRE_SET_DATA` event but then the result is cached by the `CallbackChoiceLoader` instance and never called for the `POST_SUBMIT` event.  As a result the choices populated in the `custom` field are not those depending on the `field` value.

**Possible Solution**  
I made a workaround by implementing a `ResettableCallbackChoiceLoader` that is the exact same as the original `CallbackChoiceLoader` but implements a public reset method that sets the `$choiceList` private property to null. I call that method in the `buildForm` method of the `CustomType` (making sure the type of the choice_loader option is the right one).

I might be missing something here but I want to make that `CustomType` as easy as possible to use for other developers, and I can't find some better options or examples. It might not be a good idea to use a default `choice_loader` option in a FormType but it is the case for `CountryType` for example.

**Additional context**

**Comment by xabbuh** [comment]
This looks expected to me as the default value only needs to be resolved once. Do you see a difference when you use a normalizer?

I would expect something like this to behave as you expected it:

```php
public function configureOptions(OptionsResolver $resolver) 
{
    $resolver->setNormalizer('choice_loader', function () {
        return new CallbackChoiceLoader([$this, 'getChoices']);
    });
}
```

**Comment by zefrog** [comment]
Thank you for your review. 

I tested your proposal, and indeed it seems to behave as I was expecting. I'm not familiar with the normalizer part of the OptionsResolver component, I suppose that the choice_loader option value is a new object when replacing the field in the POST_SUBMIT event.

I close the issue since my problem is resolved. Thank you again!
