### ISSUE TITLE
validator fails on LegacyTranslatorProxy when using without translation component

### ISSUE THREAD

**Issue by bitgandtter** [symfony/symfony#31216]
**Symfony version(s) affected**: 4.2.7

**Description**  
Using form and validation components without translation component leads to Fatal error: Interface 'Symfony\Component\Translation\TranslatorInterface' not found in /var/www/framework/vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21 when running composer install -o -a --no-dev

**How to reproduce**  

- symfony new my_project
- cd my_project/
- composer req symfony/validator

neither on [official documentation](https://symfony.com/doc/current/components/validator.html) or component [composer.json](https://github.com/symfony/validator/blob/master/composer.json) shows a direct dependency from the translator component.

**Comment by xabbuh** [comment]
See €31152 which was fixed by #31156 and will be part of the next release. You can install 4.2.8@dev or require the Translation component in the meantime.

**Comment by bitgandtter** [comment]
Any ETA on next version release?
