### ISSUE TITLE
[Validator] Translation Component dependency not met

### ISSUE THREAD

**Issue by JarJak** [symfony/symfony#31212]
**Symfony version(s) affected**: 4.2

**Description**  
After `composer require validator` on fresh project I get:
```
!!  PHP Fatal error:  Interface 'Symfony\Component\Translation\TranslatorInterface' not found in vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21
!!  
!!  In LegacyTranslatorProxy.php line 21:
!!                                                                                 
!!    Attempted to load interface "TranslatorInterface" from namespace "Symfony\C  
!!    omponent\Translation".                                                       
!!    Did you forget a "use" statement for "Symfony\Contracts\Translation\Transla  
!!    torInterface"?                                                               
!!                               
```
However I don't need Translator in my project.

**How to reproduce**  
1. Init fresh project (from symfony/skeleton)
2. Require Validator Component

**Possible Solution**  
Remove dependency or add `symfony/contracts` as a dependency of Validator.

**Comment by xabbuh** [comment]
See #31152 that was fixed in #31156 and will be part of the 4.2.8 release. I am closing here as a duplicate. Thank you for understanding.
