### ISSUE TITLE
[Routing] Trailing slash issue with `_format` parameter

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#31225]
**Symfony version(s) affected**: 4.2.7

**Description**  
When using routes parameters (like `format`), there is an issue when using a trailing slash:
![Sélection_598](https://user-images.githubusercontent.com/2103975/56649345-36f1a380-6685-11e9-91c8-80ddc9a8d3c1.png)

**How to reproduce**  
I've created [a reproduction repo](https://github.com/Kocal/symfony-4-2-7-trailing-slash-issue) that contains two routes:
  - `/foo`
  - `/bar.{_format}` where `_format = html` by default 

Reproduction steps:
  - run `php bin/console server:start`
  - open "http://127.0.0.1:8000/foo"
  - open "http://127.0.0.1:8000/foo/"
  - open "http://127.0.0.1:8000/bar"
  - open "http://127.0.0.1:8000/bar/"   <-- only this one fails
  - open "http://127.0.0.1:8000/bar.html" 
  - open "http://127.0.0.1:8000/bar.html/"

**Additional context**  
I first thought it was because of API Platform (I'm faced this issue on a URL generated by API Platform), but after some investigations it seems the issues is due to parameters.

Note this has been working fine in Symfony 4.2.4, 4.2.5 and 4.2.6.

Thanks!

**Comment by nicolas-grekas** [comment]
Please check 4.2.8@dev this might be fixed already.

**Comment by Kocal** [comment]
I wasn't able to update to 4.2.8@dev because of some issues (`mmap() failed: [12] Cannot allocate memory`), but I've applied your patch from #31182 and it's working fine.

Thanks! :)
