### ISSUE TITLE
[Serializer] SerializedName isn't working on getters and issers

### ISSUE THREAD

**Issue by slebrequier** [symfony/symfony#31227]
**Description**  
When using annotation `Symfony\Component\Serializer\Annotation\SerializedName` on getters and issers, the property name isn't changed to serialized name.

I'm not opening an issue because maybe the behaviour isn't coded yet.

**Example**  
If I put the following lines in my entity class :
```php
    /**
     * @SWG\Property(type="string")
     *
     * @Symfony\Component\Serializer\Annotation\SerializedName("faa")
     */
    public function getFoo(): string
    {
        return 'bar';
    }
```

Serialization result will be : 
```json
{
    ...
    "foo": "bar"
}
```

When it should be : 
```json
{
    ...
    "faa": "bar"
}
```

**Possible resolution?**

I have found that adding the following lines : 
```php
            ...

            $attributeMetadata = $attributesMetadata[$attribute];
            if ($attributeMetadata->getSerializedName()) {
                $attribute = $attributeMetadata->getSerializedName();
            }

            ...
```

Here : 
https://github.com/symfony/serializer/blob/master/Normalizer/AbstractObjectNormalizer.php#L138

Was doing the trick but... I don't really know if anything else might be broken...

**Comment by Raulnet** [comment]
i have test your issues and everything works for me.
Entity:
``
use Symfony\Component\Serializer\Annotation\SerializedName;

class Blog
{
    private $label = 'my label';

    private $description = 'my description';

    /** @SerializedName("customer_name") */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
}``
Controller:
``public function index()
    {
        $blog = new Blog();

        $classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));

        $metadataAwareNameConverter = new MetadataAwareNameConverter($classMetadataFactory);

        $serializer = new Serializer(
            [new ObjectNormalizer($classMetadataFactory, $metadataAwareNameConverter)],
            ['json' => new JsonEncoder()]
        );


        $response = new JsonResponse();
        $response->setContent($serializer->serialize($blog, 'json'));
        return $response;
    }``

Can you get more details about your serializer config ?

**Comment by slebrequier** [comment]
Hi there, you are right, there is no problem with symfony/serializer, we have a custom Normalizer that isn't working properly with the annotation.
This issue can be closed.
Thank you.
