### ISSUE TITLE
[Validator] Comparison constraints are not applicable for the array context

### ISSUE THREAD

**Issue by berrymore** [symfony/symfony#31224]
**Symfony version(s) affected**: 4.2

**Description**  
I use the _Validator_ component separately from the Symfony framework. In my case I need to validate a piece of a request parameters. So a data under the validation is [raw values](https://symfony.com/doc/current/validation/raw_values.html).

I have faced a problem when I tried to use _comparison constraints_ with the `propertyPath` option. The [AbstractComparisonValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L51) uses a context object which is obviously `null` in the my case.

It will be very useful if this kind of validators would have a comparison capability in arrays too.

**How to reproduce**  
```php
/// ....

$input      = ['password' => 'myPass', 'confirm_password' => 'anotherValue'];
$validator  = Validation::createValidator();
$constraint = new Collection(
    [
        'password'         => [new NotBlank()],
        'confirm_password' => [new IdenticalTo(['propertyPath' => 'password'])],
    ]
);

$violations = $validator->validate($input, $constraint);

return $violations->count(); // It will return 0 right now
```

**Possible solution**

As I know the `PropertyAccessor` works with arrays as well as with objects. Is it possible to use it with the `root` of the context?

**Comment by xabbuh** [comment]
see also #30302

**Comment by berrymore** [comment]
@xabbuh

In the @ktherage example https://github.com/symfony/symfony/issues/30302#issuecomment-474247319 `$errors1` and `$errors2` are the empty violation lists.

The problem is [AbstractComparisonValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L51) uses `context->getObject()`. But it seems like `object` inside context would be provided only when you use `validate()` without the second parameter.

When we set the second parameter for `validate` we fall to [this condition](https://github.com/symfony/validator/blob/master/Validator/RecursiveContextualValidator.php#L101), otherwise [to this](https://github.com/symfony/validator/blob/master/Validator/RecursiveContextualValidator.php#L135) where `validateObject` calls `validateClassNode` and the latter method will use `$context->setNode($object, $object, $metadata, $propertyPath)` to specify the object to the context.

Example
```php
class Test
{

    public $password = "1234";
    public $passwordConfirm = "4321";

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('password', new NotBlank());
        $metadata->addPropertyConstraint('passwordConfirm', new IdenticalTo(['propertyPath' => 'password']));
    }
}

//....

$validator  = Validation::createValidatorBuilder()
    ->addMethodMapping('loadValidatorMetadata')
    ->getValidator();

$validator->validate(new Test()); // This value should be identical to string "1234".
$validator->validate(new Test(), ['passwordConfirm' => new IdenticalTo(['propertyPath' => 'password'])]); // empty
```

**Comment by berrymore** [comment]
An `object` in the context is "The currently validated object.", but the `root` is "The root value of the validated object graph.". I think it is ok to use `PropertyAccessor` at [AbstractComparisonValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L56) with the `context->getRoot()` instead of `context->getObject()`, isn't it?

**Comment by lanrenbulan** [comment]
I use callback.

$arrayData = $context->getRoot();

**Comment by michanismus** [comment]
Still not possible to use `EqualTo`, `IdenticalTo` with `array` context... :(

**Comment by xabbuh** [comment]
With the current architecture of the Validator component I do not see how we can improve the situation here. That's why I am going to close here. Thank you for understanding. Though if someone of you has a good idea how to improve the handling of arrays, please do not hesitate to open a PR.

**Comment by sunchuo** [comment]
same problem
