### ISSUE TITLE
Symfony browser Kit - Client.php function error

### ISSUE THREAD

**Issue by kirantejp** [symfony/symfony#31228]
**Symfony version(s) affected**: All

**Description**  
In Client.php class in BrowserKit library of Symfony, the function getMetaRefreshUrl() definition is throwing error.

**How to reproduce**  
`private function getMetaRefreshUrl(): ?string` defined in BrowserKit library. The definition is defined wrong.

**Possible Solution**  
Correction needed in defining the `getMetaRefreshUrl()` function

**Additional context**  
This is not accepted during testing on CircleCI environment.

**Comment by jakzal** [comment]
@kirantejp would you mind to be more specific about the error you're getting? 

Why do you think the `getMetaRefreshUrl()` definition is wrong?

**Comment by kirantejp** [comment]
Sorry, my mistake. I was trying this with PHP 5.6 version.
