### ISSUE TITLE
[Cache] SF 4.3 PSR Simple cache interface not found

### ISSUE THREAD

**Issue by raresserban** [symfony/symfony#31238]
**Symfony version(s) affected**: 4.3

**Description**  
In SF 4.3 cache component, the psr/simple-cache is no longer required, instead the symfony/contracts is required which does not require psr/simple-cache.
So when using Simple Cache with the cache component in SF 4.3 there will be dependencies problems.

**Possible Solution**  
Add psr/simple-cache as a dependency to the symfony/contracts.

**Comment by nicolas-grekas** [comment]
Hello, yes, that's on purpose: if you need psr16-related features, you need to install psr/simple-cache explicitly because these features are optional.

**Comment by nicolas-grekas** [comment]
Closing as explained. 4.3 will require adding psr/simple-cache explicitly.
