### ISSUE TITLE
[DoctrineBridge] Notice: Undefined index: length

### ISSUE THREAD

**Issue by topwebstudio** [symfony/symfony#31239]
**Symfony version(s) affected**: 4.3.0-dev

**Description**  
File Symfony\Bridge\Doctrine\Validator\DoctrineLoader;

Lines: 
`     if (null === $mapping['length']) {
                continue;
            }
`

**Notice: Undefined index: length**

print_r on $mapping

[fieldName] => enabled
[type] => boolean
[columnName] => enabled
[declared] => FOS\UserBundle\Model\User
 

 
**Possible Solution**  

`            if (!isset($mapping['length']) || null === $mapping['length']) {
                continue;
            }`

**Comment by Raulnet** [comment]
Can you get more details for reproduce the Bug and Create the UnitTest
Ty

Status: Waiting feedback

**Comment by nicolas-grekas** [comment]
PR welcome, with a reproducer test case ideally.
