### ISSUE TITLE
[Messenger] Serializer should be used even for sync transport

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#31235]
**Symfony version(s) affected**: 4.2+ (or 4.1+?)

**Description**  
The serializer should be used even when the transport is synchronous. This allows the producers through to the handlers to be transport-agnostic (of course it does not apply if you set a transport-specific serializer).

**How to reproduce**  
1. Add `SerializerStamp` with some serialization groups to an envelope, and dispatch.
2. In the handler, check the message received. The result differs when using sync/async transport.

**Possible Solution**  
Use the serializer even for sync transport.

**Comment by sroze** [comment]
What's the actual use-case you are trying to solve here? There are obvious performance implications in using the serializer for handling messages locally so what would be the reason to do so? [It might help for debugging purposes.](https://github.com/symfony/symfony/issues/29163).

**Comment by teohhanhui** [comment]
The problem is that the Serializer groups are not respected, which could leak data to the handlers.

**Comment by Tobion** [comment]
I can see the potential problem. But I don't think always serializing messages is the right solution. First of all it adds a performance penalty for an edge case and secondly it just does not make sense technically to serialize synchronous messages.
What might make sense it to make serialization optional in the new SyncTransport: https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Messenger/Transport/Sync/SyncTransport.php
Or you simly implement this behavior in your custom transport based on the SyncTransport.

In the end, some behavior is always context dependent. The same applies to the SerializerStamp you mention. If you change the serializer to the native php serializer, then the serialization groups you configured will also be ignored.

**Comment by Tobion** [comment]
Also one thing to think about: I don't know the use-case of the serialization groups. But maybe using different messages instead of serialization groups would also solve your problem.

**Comment by sroze** [comment]
@teohhanhui what's your use-case? 🤔

**Comment by teohhanhui** [comment]
@sroze We set a `User` object in the message. I thought the Serializer in Messenger allowed us to control which attributes are exposed to the handlers. But if indeed it's not designed for that, we can't rely on it.

This is relevant in API Platform too, I believe.

**Comment by Tobion** [comment]
You can write a custom sync transport that serialized messages. But I don't think it belongs in core.

**Comment by pounard** [comment]
If your objects leak context information, it's a problem with your domain objects implementation or your software design, not with the bus itself. I think that, even thought a part of me agree with having a reproducible behaviour in both sync and async would be nice, that it's not practicable, serializer component is (sometime very) slow, and it will be a huge performance penalty for sync transport.

**Comment by ToshY** [comment]
> You can write a custom sync transport that serialized messages. But I don't think it belongs in core.

I'm kind of bumped out that it is not documented that the sync transport does not use the supplied (custom) serializer to begin with. Like stated by @pounard, you won't have reproduceable behavior, so you cannot simply switch from async to sync without creating a custom sync transport to handle the serialization.

@Tobion You've initially stated that it's possible to add the serializer as optional argument, is this still something that can be considered?
