### ISSUE TITLE
Process gets SIGPIPE signal

### ISSUE THREAD

**Issue by bluppfisk** [symfony/symfony#31234]
**Symfony version(s) affected**: Process v 2.5.0

**Description**  
I've come here from https://github.com/klaussilveira/gitlist/issues/839, which is a description of the same problem with Gitlist, a software that depends on Gitter which in turn relies on some Symfony components, among others Process 2.5.0. I think the problem might lie with the Symfony Process component in general, hence I'm posting here.

The issue is that when the process -- in this case `git ls-tree` -- produces over ~8000 bytes of output, something happens which causes a SIGPIPE signal to be sent (13), which puts the exit code at 141 and therefore causes `isSuccessful()` to return false.

Note that I was only able to test this on HP UX on Itanium64, which admittedly is not a very common system. Also note that HP UX' version of PHP is not compiled with sigchild support, meaning they cannot do anything with process control.

**How to reproduce**  
* In this case, install the latest version of Gitlist on a server which hosts git repositories with a few hundred files in a directory (so that `git ls-tree -l master` will output >8000 bytes of data)
* Use the web interface to browse to that directory
* See the Runtime Error being thrown (which is due to the exit code of the `git ls-tree` command not being 0) 

**Possible Solution**  
I was able to work around this problem (read: botch into submission) by replacing

```
    $process->run();

    if (!$process->isSuccessful()) {
          throw new ProcessFailedException($process);
    }

    return $process->getOutput();
```

by

```
$oldCwd = getCwd();
chdir($repository->getPath());
$output= exec($this->getPath().' '.$command, $data);      
chdir($oldCwd);
return implode("\n", $data);
```

But clearly this is not an acceptable solution :)

**Comment by xabbuh** [comment]
Is this also an issue when using a version of the Process component that is still supported (i.e. 3.4, 4.2 or 4.3)?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
