### ISSUE TITLE
[Messenger] SF 4.3 RedeliveryStamp requires not null $senderClassOrAlias

### ISSUE THREAD

**Issue by raresserban** [symfony/symfony#31231]
**Symfony version(s) affected**: 4.3

**Description**  
The RedeliveryStamp, used for handling retrying of messages, requires in the constructor the $senderClassOrAlias argument.
However, in the Worker.php class, on line 148, a new instance of the object is created, and the $senderClassOrAlias argument can be null according to the code there, so the application crashes when trying to handle a message whose handler returned an error.

**How to reproduce**  
Publish a message to a queue. Try to handle that message but return an exception in the handler. Notice the exception.

**Possible Solution**  
Allow $senderClassOrAlias argument to be null.

**Comment by weaverryan** [comment]
I discovered this as well - it's fixed in #30970 :)

**Comment by raresserban** [comment]
What you did is great, but I think I may have also a slightly different problem than that.
I am publishing messages from a SF 4.2 application, but consume them from SF 4.3, and it seems like the SF 4.2 app does not put the SentStamp on the envelope saved in the queue, so when trying to consume it and an exception is thrown, the message can not be re-added to the queue since that stamp is missing.
However, if I publish from a SF 4.3 app, then everything works fine (apart from the part that you fixed just now).
So not sure what the actual problem is, from looking at the code, the SentStamp should also be put by the SF 4.2 application but it is not...

**Comment by weaverryan** [comment]
To get redelivery to work on 4.3, we slightly changed things so that the SentStamp is sent with the message to the queue. In 4.2, the message is sent to the queue without that, then it’s added after (so you can see the stamp from the middleware, but it’s not on the message in the queue - so it’s not there when the message is consumed).

For 4.3, there are BC breaks. However, we want the migration path to be feasible for existing messages. In your situation (taking into account the changes in my linked PR), doesn’t your message simply fail to redeliver? Or does this cause a more fatal error? The behavior for a 4.2 message handled on 4.3 should be that is is processes correctly. And in case of error, it’s simply not retired (matching 4.2 behavior).

**Comment by raresserban** [comment]
There is an error when trying to create the RedeliveryStamp in the Worker class since the sender alias is null.
I managed to fix it for the time being by creating this middleware that adds the SentStamp if it does not already exist: (the $messengerRouting parameter from the constructor is the actual messenger routing configuration, I use a compiler pass to add it as a parameter to the container)

```php
<?php

declare(strict_types=1);

namespace App\Middleware;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Middleware\MiddlewareInterface;
use Symfony\Component\Messenger\Middleware\StackInterface;
use Symfony\Component\Messenger\Stamp\SentStamp;
use Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp;
use Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransport;

class MissingSentStampMiddleware implements MiddlewareInterface
{
    /** @var array */
    private $messengerRouting;

    /**
     * @param array $messengerRouting
     */
    public function __construct(array $messengerRouting)
    {
        $this->messengerRouting = $messengerRouting;
    }

    /**
     * {@inheritDoc}
     */
    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        if ($envelope->last(AmqpReceivedStamp::class) && !$envelope->last(SentStamp::class)
            && isset($this->messengerRouting[\get_class($envelope->getMessage())])
        ) {
            $envelope = $envelope->with(
                new SentStamp(AmqpTransport::class, $this->messengerRouting[\get_class($envelope->getMessage())])
            );
        }

        return $stack->next()->handle($envelope, $stack);
    }
}
```

**Comment by weaverryan** [comment]
@raresserban thanks for sharing :).

I have a question - and it's important to know if we need to do more work or not. If you remove your middleware AND if you "hack" in a temporary fix in `Worker` to avoid the sender alias null part (basically, you patch in the relevant changes from here: https://github.com/symfony/symfony/pull/30970/files#diff-c70c1ae97ec46e0eb3ffe00a7e565af3) - what is the behavior? Does the system fail in some undesired way? Or, when the message fails to handle, is it simple discarded and not retried?

**Comment by raresserban** [comment]
Hello @weaverryan, I have managed to test it eventually and if the message does not have the SentStamp, it will fail and be discarded because no SentStamp was set on it so it can not be retried.
I guess I will still need the middleware I made to add the SentStamp if it is missing since I am guessing this can not be done any other way by Symfony since the stamp is only put in SF 4.3.

**Comment by weaverryan** [comment]
That’s perfect. So, your messages created in the 4.2 way are handled like in 4.2. And yes, if you want the retry behavior of 4.3, you’ll need your middleware :).

Cheers!
