### ISSUE TITLE
[HttpFoundation] File does not support backslashes in filenames

### ISSUE THREAD

**Issue by gohai** [symfony/symfony#31236]
**Symfony version(s) affected**: 4.2.7

**Description**  
The `File` class, which is e.g. used for moving files to a new location, strips all backslash characters in the filename - due to the line

    $originalName = str_replace('\\', '/', $name);

in the `getName` method. ([see here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/File.php#L126))

**How to reproduce**  
Backslashes are valid as part of filenames on Unix systems. Running `touch \\` (two back-slashes because of escaping in bash) will e.g. create a file `\`.

**Possible Solution**  
Don't replace those slashes, or if needed for Windows only do it on this platform.

**Comment by nicolas-grekas** [comment]
I think not supporting backlashes is OK. This character is incompatible with Windows anyway.
Linux supports too many chars in file names, e.g. `\r` or `\n`.

**Comment by gohai** [comment]
Thank you for taking the time to respond, @nicolas-grekas.

Let me share a different opinion with you: we're end up using `http-foundation` as a dependency of Laravel's Lumen framwork. Our users upload files with arbitrary names to our servers, which we need to to preserve.

While I agree that this warrants _some_ validation of the file names (to prevent directory traversal vulerabilites etc), this seems to me to be the wrong place to be _opinionated_ about file names in my opinion: On Linux there is nothing particularly wrong about having a filename include a literal backslash, and we have hit this in practice, because macOS also similarly allows you to create files named in such a way.

Could this file handling not be made to follow the semantics of the underlying operating system? (i.e. strip the backslash on Windows only)

**Comment by nicolas-grekas** [comment]
@gohai can you please send a PR against branch 3.4 (I think the issue exists there also)
Please also check the full code base for similar logic, so we can discuss them in batch.

**Comment by gohai** [comment]
@nicolas-grekas I sent a PR

**Comment by fabpot** [comment]
Keeping the name for an uploaded file name as the local file name sounds like a bad idea to me. As @nicolas-grekas first initial reaction, I'm also against such support.
