### ISSUE TITLE
Composer don't install symfony/symfony any version

### ISSUE THREAD

**Issue by checcoux** [symfony/symfony#31250]
**Symfony version(s) affected**: 3.4.x

**Description**  
Tried to install tbetool/google-drive-manager with composer and suddenly got 
"Conclusion: don't install symfony/symfony v3.4.x". Reverted to last commit but same behaviour. Tried also every possible combination (composer update, self-update, delete vendor, removed lines from composer.json)

**How to reproduce**  

> Problem 1
    - Conclusion: don't install symfony/symfony v3.4.26
    - Conclusion: don't install symfony/symfony v3.4.25
    - Conclusion: don't install symfony/symfony v3.4.24
    - Conclusion: don't install symfony/symfony v3.4.23
    - Conclusion: don't install symfony/symfony v3.4.22
    - Conclusion: don't install symfony/symfony v3.4.21
    - Conclusion: don't install symfony/symfony v3.4.20
    - Conclusion: don't install symfony/symfony v3.4.19
    - Conclusion: don't install symfony/symfony v3.4.18
    - Conclusion: don't install symfony/symfony v3.4.17
    - Conclusion: don't install symfony/symfony v3.4.16
    - Conclusion: don't install symfony/symfony v3.4.15
    - Conclusion: don't install symfony/symfony v3.4.14
    - Conclusion: don't install symfony/symfony v3.4.13
    - Conclusion: don't install symfony/symfony v3.4.12
    - Conclusion: don't install symfony/symfony v3.4.11
    - Conclusion: don't install symfony/symfony v3.4.10
    - Conclusion: don't install symfony/symfony v3.4.9
    - Conclusion: don't install symfony/symfony v3.4.8
    - Conclusion: don't install symfony/symfony v3.4.7
    - Conclusion: don't install symfony/symfony v3.4.6
    - Conclusion: don't install symfony/symfony v3.4.5
    - Conclusion: don't install symfony/symfony v3.4.4
    - Conclusion: don't install symfony/symfony v3.4.3
    - Conclusion: don't install symfony/symfony v3.4.2
    - Conclusion: don't install symfony/symfony v3.4.1
    - Conclusion: don't install symfony/symfony v3.4.0
    - Conclusion: don't install symfony/symfony v3.4.0-RC2
    - Conclusion: don't install symfony/symfony v3.4.0-RC1
    - Conclusion: don't install symfony/symfony v3.4.0-BETA4
    - Conclusion: don't install symfony/symfony v3.4.0-BETA3
    - Conclusion: don't install symfony/symfony v3.4.0-BETA2
    - Conclusion: don't install symfony/symfony v3.4.0-BETA1
    - don't install symfony/templating 4.1.x-dev|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating 4.2.x-dev|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating 4.3.x-dev|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.0|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.0-BETA1|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.0-BETA2|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.0-BETA3|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.1|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.10|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.11|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.12|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.2|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.3|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.4|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.5|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.6|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.7|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.8|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.1.9|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.0|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.0-BETA1|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.0-BETA2|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.0-RC1|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.1|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.2|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.3|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.4|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.5|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.6|don't install symfony/symfony 3.4.x-dev
    - don't install symfony/templating v4.2.7|don't install symfony/symfony 3.4.x-dev
    - Installation request for symfony/symfony 3.4.* -> satisfiable by symfony/symfony[3.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Installation request for symfony/templating ^4.1 -> satisfiable by symfony/templating[4.1.x-dev, 4.2.x-dev, 4.3.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7].

**Additional context**  
**composer.json**

> {
    "name": "ux/galileo",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
        ]
    },
    "require": {
        "php": ">=5.5.9",
        "doctrine/common": "^2.7",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "2.5.6",
        "friendsofsymfony/user-bundle": "~2.0",
        "hwi/oauth-bundle": "^0.6.3",
        "incenteev/composer-parameter-handler": "^2.0",
        "php-http/guzzle6-adapter": "1.1.1",
        "php-http/httplug-bundle": "dev-master",
        "php-http/socket-client": "^1.0",
        "sensio/distribution-bundle": "^5.0.22",
        "sensio/framework-extra-bundle": "^5.0.0",
        "sonata-project/admin-bundle": "^3.40",
        "sonata-project/doctrine-orm-admin-bundle": "^3.6",
        "symfony/filesystem": "^2.3", **I also removed this line**
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "symfony/templating": "^4.1",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}

**Comment by xabbuh** [comment]
The `symfony/symfony` package already contains the Templating component (the `symfony/templating` package). Thus, you try to install the component in two different versions. This used to work in older Composer versions, but was fixed in 1.7.2. You either need to remove the `symfony/templating` package and use the component in version 3.4 or drop the `symfony/symfony` dependency and require all components explicitly in the version that you need.

I am closing here as there is no bug to fix. Thank you for understanding.
