### ISSUE TITLE
[Translation] Add Mozilla Fluent support to Translation component

### ISSUE THREAD

**Issue by neluzhin** [symfony/symfony#31268]
**Description**  

Recently Mozilla released stable version of Fluent - it's specification for storing and managing translations in human-readable format. The main benefits of Fluent:

1. It does not require any special software to manage translations because of pretty and clean syntax.
2. It's standard.
3. Pluralization is supported by standard.

Links:

* Website: [projectfluent.org](https://projectfluent.org)
* Repository with specification: [github.com/projectfluent/fluent](https://github.com/projectfluent/fluent)
* Official implementations: [JavaScript](https://github.com/projectfluent/fluent.js), [Python](https://github.com/projectfluent/python-fluent), [Rust](https://github.com/projectfluent/fluent-rs)

**Example**  

Fluent syntax looks pretty similar to YAML format used by symfony/translation, but much more flexible.

Symfony example:

```yaml
apples_count: {0} There are no apples.|{1} There is one apple.|]1,Inf[ There are %count% apples.
```

Fluent example:

```fluent
apples_count =
    { $apples_count ->
        [0] There are no apples
        [one] There is one apple
       *[other] There are { $apples_count } apples
    }.
```

**Comment by stof** [comment]
We will have several things to consider here:

- Fluent defines some file-level references between translations, which won't map cleanly to what Symfony Translator can do.
- Fluent has its own syntax, so this would require loading translations in a separate catalogue to apply a special formatter on them (we already built something like that to migrate to the ICU MessageFormat in 4.2, but that one at least did not suffer from the previous point)
- Fluent supports many formatters, as well as custom ones. The Intl formatters will provide implementations for some of them, but that would still require lots of work.

The hardest point is probably the first one. The next points are adding complexity to Symfony that we would have to maintain, but are not impossible to solve.

**Comment by javiereguiluz** [comment]
My guess (not based on any objective data) is that nobody uses Fluent except Mozilla. I'd wait to see if it gains more popularity before considering to add support for it or not (keeping in mind @stof's comments too about the technical challenges of this format).

**Comment by stof** [comment]
@javiereguiluz that's a double-edge argument though. Nobody will start using Fluent in the Symfony community because the Translation component does not support it.
But I agree about waiting to see whether Fluent starts getting used outside Mozilla (they only announced it publicly 2 weeks ago)

**Comment by nicolas-grekas** [comment]
Is there any comparison with the intl-icu format somewhere?

**Comment by nicolas-grekas** [comment]
Justification of the new format here: https://github.com/projectfluent/fluent/wiki/Fluent-and-ICU-MessageFormat

**Comment by Simperfit** [comment]
2 month later, do we want to implement it ?

**Comment by fabpot** [comment]
Let's close for now. If more people ask for it, we will reconsider.
