### ISSUE TITLE
[Autowiring] Service aliases don't support the non existing/optional @? service id notation

### ISSUE THREAD

**Issue by ureimers** [symfony/symfony#31264]
**Symfony version(s) affected**: 4.2.7 (no others tested, possibly all with autowiring/alias support)

**Description**  
When defining an alias for a non existing / optional service using the `?@` notation (e.g. `?@profiler`) the `?` is ignored and the `ContainerBuilder` tries to locate the service `?profiler` which fails.

**How to reproduce**
I found out about that when I was trying to use the service alias code from https://symfony.com/doc/current/profiler.html#enabling-the-profiler-conditionally and accidentally put the alias in `services.yaml` instead of `services_dev.yaml`:

``` yaml
# config/services.yaml (whoops, not services_dev.yaml)
services:
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'
```

As the Profiler service isn't registered in the prod environment this led to the error:

```
 You have requested a non-existent service "profiler".
```

I did what's being teached and used the `?`-notation to mark the dependency as optional:

``` yaml
# config/services.yaml
services:
    Symfony\Component\HttpKernel\Profiler\Profiler: '@?profiler'
```

But this lead to the error:

```
 You have requested a non-existent service "?profiler".
```

**Possible Solution** 
Defining the alias in the `bind` section of `services.yaml` actually worked as the `?` notation is being processed correctly here:

``` yaml
# config/services.yaml
services:
    _defaults:
        bind:
            Symfony\Component\HttpKernel\Profiler\Profiler: '@?profiler'
```

As an actual service alias seems to involve `ContainerBuilder::setAlias()` and the `bind` section doesn't, solving this might be more complicated then the benefit of it. In fact in my case it only appeared because I put the alias in the wrong service yaml.

In the end this might be a DX issue, but nonetheless from a developer standpoint using the `?` notation should always behave the same, where applicable and I don't see why a service alias shouldn't allow its service to be optional. The statement from https://symfony.com/doc/current/service_container/optional_dependencies.html#ignoring-missing-dependencies at least doesn't include service aliases as an exception to its rule:

> In YAML, the special @? syntax tells the service container that the dependency is optional. [...]

**Comment by stof** [comment]
this `?` is a special syntax of the Yaml loader, to configure the type of reference being created. But aliases don't rely on references at all. There is no way to have aliases pointing to non-existent services in the DI component (and how would that behave then ?)

**Comment by xabbuh** [comment]
I am closing here as there is no bug as explained. Thank you for understanding.
