### ISSUE TITLE
[Form DateTimeType Field] - model timezone value is ignored and replaced with system default timezone

### ISSUE THREAD

**Issue by Housik** [symfony/symfony#31263]
**Symfony version(s) affected**: 4.2.3

**Description**  
Our data model is read from remote API and its DateTime attribute object has `UTC` timezone. Our PHP has `Europe/Prague` timezone. When displaying the model in Symfony Form as `DateTimeType`, timezone is stripped from source model `DateTime` object and replaced with `model_timezone`, which is system default timezone. As result, wrong (shifted) time is displayed.

**How to reproduce**  
Form model, lets say `PriceData` has `validFrom` attribute with following `DateTime` object having explicitly defined UTC timezone:

```
object(DateTime)[500]
  public 'date' => string '2019-02-07 05:34:00.000000' (length=26)
  public 'timezone_type' => int 1
  public 'timezone' => string '+00:00' (length=6)
```

System timezone is `Europe/Prague` - this value returns `date_default_timezone_get()`

**Currently displayed date and time displayed in HTML5 form select boxes is:**
**7** (day) **2** (month) **2019** (year) **5** (hours) **34** (minutes)

**Expected date and time displayed in HTML5 form select boxes is:**
**7** (day) **2** (month) **2019** (year) **6** (hours) **34** (minutes)

**Possible Solution**  
Default value for DateTimeType -> model_timezone should be a timezone defined in a model DateTime object, not system default timezone.

**Additional context**  
Main reason is that DateTime object is **a variable**, including timezone, so it is unpredictable. 

For example, when you are reading data from remote API, you can not predict, which timezone will be defined in DateTime object. So we can not define `model_timezone` value when building form with `$builder` of type `FormBuilderInterface`, because it is unpredictable.

Next, when you display above declared `DateTime` object with `UTC` timezone with Twig `{{ price.validFrom | date("d.m.Y H:i") }}`, correct time is displayed (6:34).

**Comment by xabbuh** [comment]
Can you please show the configuration of your form type?

**Comment by Housik** [comment]
> Can you please show the configuration of your form type?

Our form type has no any special configuration and `DateTimeType` has defined just the labels:

```php
$builder->add('validFrom', DateTimeType::class, [
    'label' => 'entity.handsetPrice.attr.validFrom.label',
    'help' => 'entity.handsetPrice.attr.validFrom.help',
])
```

**Comment by Housik** [comment]
**How Symfony code works now:**
If `$options['model_timezone']` is `null`, get timezone via `date_default_timezone_get()`.

**Suggested solution:**
If `$options['model_timezone']` is `null`, try to get timezone from DateTime object, if it contains timezone definition. If not, get timezone via `date_default_timezone_get()`. 

Anyway, current model timezone should not be ignored.

Related files for my example:
- `symfony/form/Extension/Core/Type/DateTimeType.php`
- `symfony/form/Extension/Core/DataTransformer/BaseDateTimeTransformer.php`

**Comment by xabbuh** [comment]
So you mean when explicitly configuring the `model_timezone` everything works as expected?

**Comment by Housik** [comment]
> So you mean when explicitly configuring the `model_timezone` everything works as expected?

yes

**Comment by xabbuh** [comment]
Thank you for the confirmation. I am going to close here then. The current behaviour is documented and changing that would be a BC break. Thank you for understanding.
