### ISSUE TITLE
Why the command "php bin/console server:run" gives such results ?

### ISSUE THREAD

**Issue by zizou19** [symfony/symfony#31274]
={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔
In DefinitionErrorExceptionPass.php line 54:

  Invalid service "security.authentication.rememberme.services.simplehash.main":
  class Symfony\Component\Security\Http\Logout\LogoutHandlerInterface not found.

PS C:\wamp64\www\gestion_formation_continue> php bin/console server:run
={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔={{╔#          <╔  ╝& ╗   =║   ╗
 ╗=   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 6 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ >╗
 ╚>   ╔╝@╔╔╚     ║║   ╔   e╝ ╔ ?╗
 ╗?   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 7 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ @╗
 ╚@   ╔╝@╔╔╚     ║║   ╔   ╔'╝ ╔ A╗
 ╗A   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b 9 _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ B╗
 ╚B   ╔╝@╔╔╚     ║║   ╔   xW╝ ╔ C╗
 ╗C   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b a _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ D╗
 ╚D   ╔╝@╔╔╚     ║║   ╔   ╝ ╔ E╗
 ╗E   ╔╝@╔s v c . o w n p r o c . s 0 . u c 0 . h o s t e b c _ 1 . 0 . 0 . 0 _ n e
 u t r a l _ _ 1 2 3 4 5 6 7 8 9 0 a b c   ╝ ╔ F╗
 ╚F   ╔

**Comment by xabbuh** [comment]
Can you create a small example application that allows us to reproduce this issue?

**Comment by zizou19** [comment]
Everything was working perfectly, i just restarted the server, and a got
this error, here is a screen shot

**Comment by chalasr** [comment]
We won't be able to help without a reproducer.

**Comment by zizou19** [comment]
I solved the problem, i had some classes containing errors

Le sam. 27 avr. 2019 à 18:35, Robin Chalas <notifications@github.com> a
écrit :
