### ISSUE TITLE
[DI] Anonymous public service makes no sense

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#31272]
**Symfony version(s) affected**: 4.2.5

**Description**  
Anonymous services shall not be allowed to be public because we cannot reference them and it does not make sense.

**How to reproduce**  

`````php
$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();
$service = $container->autowire(null, DummyService::class)
    ->setPrivate(false);
$dumper = new PhpDumper($c);
file_put_contents('DummyContainer.php', $dumper->dump());
`````

The generated container then contains a service with an empty name `""`:

`````php
class ProjectServiceContainer extends Container {
    public function __construct() {
        $this->methodMap = [
            '' => 'get2Service',
            // ...
        ];
    }
    protected function get2Service() {
        return $this->services[''] = new DummyService(/*...*/);
    }
}
`````

This happens because of `(string) null === ""`.

If the service gets optimized away, then you can see the `""` id in removed services.

This may happen to multiple services; the particular behavior of the container depends on the order of the service definitions.

**Possible Solution**  

Container should throw an exception when such a silly configuration is detected.

**Comment by stof** [comment]
your usage does not respect the contract of the method. `null` is not an allowed id.

**Comment by stof** [comment]
what you are doing here is defining a service with the empty string as id (which is a valid id in the ContainerBuilder, even though it is weird, and may not work fine in the XML or Yaml file loader when creating references).
And doing that several times would override the previous service. Services are always named in the DI component (the XMLFileLoader used to support that by actually giving them generated names, but that is deprecated in 3.4 and gone in 4.0).

**Comment by jkufner** [comment]
Good point. I have no idea where I've got this.
