### ISSUE TITLE
[RFC][Controller] Make query argument nullable when forwarding requests

### ISSUE THREAD

**Issue by mdeboer** [symfony/symfony#31276]
When forwarding requests internally within controllers using `$this->forward()`, the third argument `$query` defaults to an empty array, effectively forwarding the request with no query parameters. To forward **with** the original query parameters (as would seem the most logical to me), you are required to call it like this `$this->forward('FooController::bar`, [], $request->query->all());`.

The `forward()` method invokes `$request->duplicate()` and then asks the HTTP kernel to handle that request. However, the duplicate method accepts null for `$query` in which case it won't override but uses the query parameters from the original request. So making the `$query` parameter nullable and preferably default to null, one could simply write `$this->forward('FooController::bar`);` instead. Again, this would make much more sense to me when reading the code.

I am happy to submit a PR if people agree.

**Comment by ro0NL** [comment]
im wondering if

```
$this->forward('FooController::bar, [], null)
vs.
$this->forward('FooController::bar, [], $request->query->all())
```

is really better :/ it's an implicit step

> one could simply write $this->forward('FooController::bar);` instead. Again, this would make much more sense to me when reading the code.

im not sure default inheriting of query params makes more sense :/ it sounds like an edge case where there is a relation between the main- and sub-request operating based on the same query string.

**Comment by mdeboer** [comment]
> im wondering if
> 
> ```
> $this->forward('FooController::bar, [], null)
> vs.
> $this->forward('FooController::bar, [], $request->query->all())
> ```
> 
> is really better :/ it's an implicit step

Well no, but that's not what I meant, the default should be null and the type should therefore be nullable (`?array`).

> > one could simply write $this->forward('FooController::bar);` instead. Again, this would make much more sense to me when reading the code.
> 
> im not sure default inheriting of query params makes more sense :/ it sounds like an edge case where there is a relation between the main- and sub-request handling the same query params.

To me `forward` only makes sense if it really forwards the request. The term makes you assume it forwards it 1:1 to another controller/method. This is not what happens however. Most of the things do get forwarded except for the query. This seems arbitrary to me, why everything else except the query parameters? They seem like an essential part of the request to me, much like any POST data.

So my suggestion is to make the third parameter (query parameters) `null` by default (and therefore `?array`) instead of the default `array` it is now. This would only break BC with applications that expect and rely on the forward not to include the query parameters. But then again, if your logic relies on it not passing on the parameters, can't hurt to explicitly pass `[]` instead of relying on the default value. Possibly a deprecation(?) warning can be thrown?

**Comment by ro0NL** [comment]
> So my suggestion is to make the third parameter (query parameters) null

given it modifies the behavior; it's a BC break ... not sure we want to go down this road.

> Most of the things do get forwarded except for the query.

they way i see it, only the request "environment" is duplicated, and NOT its current context. We don't want to replay the current context using a different controller (URL). That's what i considered an edge case.

**Comment by nicolas-grekas** [comment]
To me, query parameters should not be forwarded: each URLs has its specific set of arguments and these parameters are not like Cookie.

**Comment by fabpot** [comment]
I agree with Nicolas.
