### ISSUE TITLE
UrlType are always changed to text types

### ISSUE THREAD

**Issue by lmlsna** [symfony/symfony#31283]
**Symfony version(s) affected**: 4.1.11 +

**Description**  
Both of these PRs were merged:
#29926 = Changed UrlType input type to text when default_protocol is not null
#3879 = Force default_protocol to generate an url input

So now we are forcing a default protocol, AND changing the type to text if there's a default protocol (which there always is, because we force it).

So this element never renders as a type="url" now. And because it writes to the $view var "type", we have no way to override that.

It doesn't make much sense to change a UrlType to a TextType, and the inputmode attribute was obsoleted in the WC5.2. If you just remove that bit, it works like all the other extended text types. 

**How to reproduce**  
Create a UrlType form element.

**Possible Solution**  
I can send a PR fixing this by not forcing a `type="text"` anymore in `Symfony\Component\Form\Extension\Core\Type\UrlType`

**Additional context**

**Comment by MatTheCat** [comment]
Where did you see `inputmode` was obsoleted? https://html.spec.whatwg.org/dev/interaction.html#attr-inputmode doesn't seem to mention it.

Also why are you saying

> It doesn't make much sense to change a UrlType to a TextType

Did you read https://github.com/symfony/symfony/issues/29690 at all?

**Comment by lmlsna** [comment]
@MatTheCat `inputmode` is not mentioned in 5.2 of the spec, so I presume it's not going to be used, but you're correct that it's not currently obsoleted.

I was just confused as to why the type was being changed to "text", my mistake.

**Comment by stof** [comment]
We are not forcing a default protocol. We are *defaulting* to have one.
