### ISSUE TITLE
Rename !tagged to !tagged_iterator

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31289]
In #30348 we introduced `!tagged_locator`, that complements the previously existing `!tagged`.
I feel like it would be more clear to rename `!tagged` to `!tagged_iterator`.
WDYT? Anyone willing to give it a try? That'd mean triggering a deprecation when `!tagged` is used.

**Comment by chalasr** [comment]
makes sense

**Comment by jschaedl** [comment]
I'd like to work on this.

**Comment by emodric** [comment]
If I'm missing something, please excuse me, but won't this complicate definition of services for no real benefit, if one would want to support multiple versions of Symfony and at the same time fix deprecations? In my opinion, it is kinda similar to what happened to deprecating single colon notation for route controllers, which was later reversed, due to complicating support for multiple Symfony versions.

**Comment by nicolas-grekas** [comment]
@emodric that's a valid point to consider. Thinking about it:

- this point applies to bundles; bundles can replace the syntax by a compiler pass as they do already when supporting 2.x. This is the difference key with the colon notation, that had no alternatives.
- the clear benefit is DX, by mean of consistency and easier understanding/discoverability.

With this analysis in mind, I'm on the side the objection shouldn't prevent the improvement to happen.

Makes sense?

**Comment by emodric** [comment]
Maybe. But the whole point of using `!tagged` for me was to get rid of compiler passes. You now have to introduce them again, which defeats the purpose.

But okay, it's true that in this case, there's a migration path.

**Comment by emodric** [comment]
@nicolas-grekas Can you give a few pointers on how to replace `!tagged` with `!tagged_iterator` with a compiler pass? In my tests, short of using a different set of config files, it is not possible to replace the syntax with a compiler pass because the argument is already converted to the instance of `TaggedIteratorArgument`.

**Comment by nicolas-grekas** [comment]
> the argument is already converted to the instance of TaggedIteratorArgument

This is the part that should be dropped on your side: don't use the syntax, use a regular argument instead and you'd do in SF2

**Comment by emodric** [comment]
I can't do that :/ The code in question is not a standalone app, but a product that can be installed on multiple apps (eZ Platform, Sylius) with multiple versions of Symfony (currently 3.4 and 4.3), but in 6 months it will be 3.4 (lts), 4.4 (lts) and 5.0.

This is the reason for my original comments. There's no way to programatically get rid of the deprecation and still support multiple Symfony versions (especially LTS ones).

**Comment by emodric** [comment]
For those facing a similar issue, I found a non-intrusive way (meaning, it is only ran once, on container compile) by overriding `YamlFileLoader` and using it in my DI extension instead the original one:

```
<?php

declare(strict_types=1);

namespace MyApp;

use Symfony\Component\DependencyInjection\Loader\YamlFileLoader as BaseYamlFileLoader;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Yaml\Tag\TaggedValue;

final class YamlFileLoader extends BaseYamlFileLoader
{
    protected function loadFile($file): array
    {
        $content = parent::loadFile($file);

        if (Kernel::VERSION_ID < 40400 || !array_key_exists('services', $content)) {
            return $content;
        }

        foreach ($content['services'] as $serviceId => $service) {
            foreach ($service['arguments'] ?? [] as $key => $argument) {
                if ($argument instanceof TaggedValue && $argument->getTag() === 'tagged') {
                    $content['services'][$serviceId]['arguments'][$key] = new TaggedValue('tagged_iterator', $argument->getValue());
                }
            }
        }

        return $content;
    }
}
```
