### ISSUE TITLE
[HttpFoundation] Missing ext-session in composer.json

### ISSUE THREAD

**Issue by Antoine87** [symfony/symfony#31305]
**Symfony version(s) affected**: ^4.0

**Purpose**:  Reconsider #27955 taking into account [Docker containers (especially php:cli-alpine)](https://hub.docker.com/_/php)

**Description**  

Missing [PHP session extension](https://www.php.net/manual/en/session.installation.php) requirements in composer.json of [symfony/http-foundation](https://github.com/symfony/http-foundation/blob/master/composer.json)

**How to reproduce**  
```shell
$ composer create-project symfony/skeleton
$ composer req debug
```

![1](https://user-images.githubusercontent.com/21277377/56863903-92d96680-69bc-11e9-95d4-97c66104ae24.jpg)

**Possible Solution**  
```json
"require": {
    "ext-session": "*",
```
**Additional context**  

@fabpot said :
> (http://php.net/manual/en/session.installation.php: Session support is enabled in PHP by default.).

The next sentence of the doc is :
>  If you would not like to build your PHP with session support, you should specify the --disable-session option [...]

```shell
$ php -m
 [PHP Modules]
 Core
 ctype
 date
 dom
 filter
 hash
 iconv
 json
 libxml
 mbstring
 openssl
 pcre
 PDO
 pdo_sqlite
 Phar
 Reflection \
 SimpleXML   | no session
 SPL        /
 sqlite3
 standard
 tokenizer
 xml
 xmlwriter
 zlib
``` 
Please consider the waste of time building docker images with a symfony distribution without any error fetching the composer packages but which finally end up with a 500 starting the server.

**Comment by javiereguiluz** [comment]
It's very boring to do ... but I agree that we should list all the required PHP extensions for each component. Other projects such as Drupal already do it:

![image](https://user-images.githubusercontent.com/73419/56882166-1ea5ce00-6a63-11e9-8d38-e34309285434.png)

https://github.com/drupal/drupal/blob/8.8.x/core/composer.json

**Comment by fabpot** [comment]
ok, let me think about the best way to do it.

**Comment by fabpot** [comment]
I think this needs to be a manual process as we don't want to add extensions that are not required for the main features of each component. So, we need someone who would take care of carefully see which extensions are needed for every component. That's tedious but doable with some scripting.

**Comment by ro0NL** [comment]
@fabpot see https://github.com/llaville/php-compat-info ... this seems to work pretty well

```
php phpcompatinfo-5.1.0.phar ana:run src/Symfony/Component/Asset/

Data Source Analysed

Directories                                          7
Files                                               24
Errors                                               0


Extensions Analysis

    Extension Matches REF      EXT min/Max PHP min/Max PHP all 
    Core              Core     5.3.0       5.3.0               
    hash              hash     1.1         4.0.0               
    json              json     5.5.0       5.5.0               
    spl               spl      5.1.0       5.1.0               
    standard          standard 4.3.0       4.3.0               
    Total [5]                              5.5.0           
```

(for Asset component in 3.4)

> we don't want to add extensions that are not required for the main features of each component

this makes things hard ...

- `ext-hash` for `UrlPackage`: should we include it?
- `ext-json` for `JsonManifestVersionStrategy`: should we include it?
- `ext-SPL` for any spl exception: should we include it?

Then we need to re-apply per branch :/

Perhaps we can first add them all to `require-dev` (automated), then move some per case (for the main entrypoints) to `require`

**Comment by Antoine87** [comment]
As i posted the issue, i think i might help a bit.

The point i tried to achieve was, following Alpine's philosophy, to run an application with maximum security by minimizing the number of installed linux packages in a dedicated environment through Docker with an own build of PHP with minimum extensions.

I agree with @fabpot that it is important to add only extensions that are required for the main feature of a package, but as i see the Drupal's composer.json above, they are doing it wrong. And i don't think that [php-compat-info](https://github.com/llaville/php-compat-info) will help because it will look for every functions used in every files not taking into account the mandatory ones for this purpose.

Here is what would be interesting to consider:

- Building PHP without any extension is possible using switches like [--disable-all](http://www.phpinternalsbook.com/build_system/building_php.html). For all recent PHP7.* versions including 8.0 from master branch leads to: 
```shell
[PHP Modules]
Core
date
hash
pcre
Reflection
SPL
standard
```

So it is absolutely not required to list them like Drupal did for some.

- As it is unthinkable to run Symfony without Composer i think that it might be not necessary to list their ones. Following [their script to check platform dependencies](https://github.com/composer/getcomposer.org/blob/ffdc3c7fcb7c0f2a806508a868a35d13177a5a51/web/installer#L226-L411) i was only able to run the installer by incrementally adding the minimal ones; which are: json, phar, filter, iconv|mbstring, openssl, zlib:
```shell
[PHP Modules]
Core
date
filter
hash
iconv
json
openssl
pcre
Phar
Reflection
SPL
standard
zlib
```

So i think all of the above PHP extensions shouldn't be necessary to add.

From this point we have a working PHP+Composer installation

![6](https://user-images.githubusercontent.com/21277377/57156152-8fd7df00-6ddd-11e9-9131-72118e4707a2.jpg)

- The [symfony/skeleton composer.json](https://github.com/symfony/skeleton/blob/master/composer.json#L9-L10) asks for iconv and ctype. That's ok, let's list them to the build.

- Creating the symfony/skeleton from Composer i got a strange error [similar to someone else on stackoverflow](https://stackoverflow.com/questions/24574616/iconv-wrong-charset-conversion-from-auto-to-utf-8-ignore-is-not-allowed#)

![5](https://user-images.githubusercontent.com/21277377/57156586-a03c8980-6dde-11e9-903d-d5b1a73c57c9.jpg)

I don't know which Symfony component require it (polyfill ?) but let's include mbstring...

- The next one comes from symfony/config

![3](https://user-images.githubusercontent.com/21277377/57156814-3b356380-6ddf-11e9-83cc-ead0a1ae4c66.jpg)

I think you can safely add ext-dom to [symfony/config](https://github.com/symfony/config/blob/master/composer.json#L18-L20)

- Compiling with ext-dom i got another error (this time from PHP itself)

![4](https://user-images.githubusercontent.com/21277377/57157013-d0385c80-6ddf-11e9-8a86-cf7883565c72.jpg)

So ext-xml shouldn't be necessary unless you think that symfony/config is not required everywhere.

- Next, as i already mentioned, ext-session to symfony/http-foundation. We are now with this PHP :
```shell
[PHP Modules]
Core
ctype
date
dom
filter
hash
iconv
json
libxml
mbstring
openssl
pcre
Phar
Reflection
session
SPL
standard
zlib

[Zend Modules]
```

This one let's create the skeleton with composer, require debug, start the built-in php server and access the first page without error, even the profiler : 

![2](https://user-images.githubusercontent.com/21277377/57157411-ed215f80-6de0-11e9-8512-f32590b11321.jpg)

![1](https://user-images.githubusercontent.com/21277377/57157415-eeeb2300-6de0-11e9-86ce-247ac26ddd3f.jpg)

I uploaded the resulting image [here](https://github.com/Antoine87/minimal-php-ext-symfony) so you can check the process by yourself.

Of course testing with PHP 8.0 in May 2019 is a bit hardcore but it is interesting to know it works.

**Personal conclusion**

- Don't add Core, date, filter, hash, iconv, json, openssl, pcre, Phar, Reflection, SPL, standard, zlib
- Add ext-dom to symfony/config
- Add ext-session to symfony/http-foundation
- Add ext-mbstring somewhere ? or try to figure out why it failed.

If you really wants to check all the other component the only way i can think is to dedicate a special [phpunit group](https://phpunit.readthedocs.io/en/latest/annotations.html#group) on each component and, as i did above, test each one from a scratch environment incrementally building the mandatory extensions.
I am ok to help you with this last point, but i can't tell you which unit tests on each component are required for "the main feature"...

**Comment by derrabus** [comment]
How would composer resolve this, if we would add `ext-session` to the requirements of `symfony/http-foundation` now? Would someone who runs composer on such a minimal container really get proper feedback or would composer just pin `symfony/http-foundation` forever to 4.2.8 (aka the last version that didn't demand `ext-session`)?

**Comment by derrabus** [comment]
> I think you can safely add ext-dom to symfony/config

Not sure about that. Outside of the full-stack framework context, I could use `symfony/config` to solely parse YAML files if I'm not mistaken.

**Comment by derrabus** [comment]
Also, if we added `ext-session` to the dependencies of `symfony/http-foundation`: If I only wanted to build a stateless API and thus disabled session support in Symfony, HttpFoundation should work fine without `ext-session`, shouldn't it? Maybe we should rather add a check to the `FrameworkExtension` and throw a meaningful exception if someone tries to enable sessions with the native storage without having `ext-session` enabled.

**Comment by Antoine87** [comment]
> How would composer resolve this, if we would add `ext-session` to the requirements of `symfony/http-foundation` now? Would someone who runs composer on such a minimal container really get proper feedback or would composer just pin `symfony/http-foundation` forever to 4.2.8 (aka the last version that didn't demand `ext-session`)?

- Not sure about this case, i will try it to see how it react.

> Not sure about that. Outside of the full-stack framework context, I could use `symfony/config` to solely parse YAML files if I'm not mistaken.

- https://github.com/symfony/config/blob/master/Util/XmlUtils.php#L47-L52

> Also, if we added `ext-session` to the dependencies of `symfony/http-foundation`: If I only wanted to build a stateless API and thus disabled session support in Symfony, HttpFoundation should work fine without `ext-session`, shouldn't it? 

- https://github.com/symfony/http-foundation/blob/master/Session/Storage/NativeSessionStorage.php#L104-L114

A session function is used in this class without a check extension_loaded(). I don't know how it works when you already have it in your vendor directory but you can't actually create the symfony/skeleton without ext-dom.

Generally speaking, the point is not say "How about all the already installed symfonys ?" but "Is it possible to simply install symfony without those dependencies ?". 

The main problem is :

> we don't want to add extensions that are not required for the main features of each component.

But before digging into each component, the post i did above was simply to list mandatory extensions for a simple `composer create-project` installation.

**Comment by derrabus** [comment]
> > Not sure about that. Outside of the full-stack framework context, I could use `symfony/config` to solely parse YAML files if I'm not mistaken.
> 
>     * https://github.com/symfony/config/blob/master/Util/XmlUtils.php#L47-L52

My point exactly. That class is not executed if you used `symfony/config` for YAML files only which is a valid use-case if you use that component standalone. Making `ext-dom` a mandatory requirement for `symfony/config` would not be right, imho. We could add it to `symfony/framework-bundle` though, as it uses XML for the service configuration which doesn't work without `ext-dom`.

> > Also, if we added `ext-session` to the dependencies of `symfony/http-foundation`: If I only wanted to build a stateless API and thus disabled session support in Symfony, HttpFoundation should work fine without `ext-session`, shouldn't it?
> 
>     * https://github.com/symfony/http-foundation/blob/master/Session/Storage/NativeSessionStorage.php#L104-L114

Again, if you disable session support in your Symfony application, that class is not loaded. `ext-session` is an optional, but not a mandatory dependency of `symfony/http-foundation`.

Of course, it is not nice that you run into a fatal error when the native session storage is enabled on a system without `ext-session`. That's why I suggested to check for this case and throw an exception with a better error message.

I understand your concern, but I don't think that adding non-mandatory php extensions to the composer requirements of certain components is the right way to address this issue.

**Comment by fabpot** [comment]
On top of what has already been said, we also have polyfills that can replace some extensions (iconv, mbstring, ...).

**Comment by javiereguiluz** [comment]
After reading this discussion looks like it's impossible to implement this feature. Too many extensions depend on what your app actually uses, so it's impossible to anticipate the requirements.

Instead of this, people would need a tool that executes locally and introspects your app (both your code and vendors code) and gives you the list of PHP extensions needed to run it.

**Comment by ro0NL** [comment]
Do any main/required extension points remain in the current code base?

E.g. looking at https://github.com/symfony/ldap/blob/master/composer.json#L21 it seems we try to maintain this list to its best effort already :)

**Comment by nicolas-grekas** [comment]
Given the discussion, I'm on the side we should throw an exception when e.g. `session_start` is not found in `FrameworkExtension` and a similar one in `NativeSessionStorage`.
PR welcome.

**Comment by derrabus** [comment]
> Given the discussion, I'm on the side we should throw an exception when e.g. `session_start` is not found in `FrameworkExtension` and a similar one in `NativeSessionStorage`.
> PR welcome.

I can work on this.

The issue that will remain is that you cannot use a php container without `ext-session` to bootstrap the project because https://github.com/symfony/recipes/blob/fab597914d661c49a06870b92fdbd6978a8b1d7e/symfony/framework-bundle/4.2/config/packages/framework.yaml#L7-L12

But I'm not sure if we should do something about that.

**Comment by nicolas-grekas** [comment]
> cannot use a php container without ext-session to bootstrap the project

not sure I get why: the FrameworkExtension could throw when these options are set, isn't it?
we could also add ext-session to skeletons if you think it's worth.

PR welcome.

**Comment by derrabus** [comment]
I tried to build an environment to reproduce your issue. But even the cli-alpine container is built with session support.
