### ISSUE TITLE
cache.WARNING: Failed to fetch key

### ISSUE THREAD

**Issue by Rmy5** [symfony/symfony#31315]
**Symfony version(s) affected**: 4.2.0

**Description**

I have a service that I call from a command. The command is working ok in dev env, but when in prod env I'm getting cache.WARNING: failed to fetch key errors:

> cache.WARNING: Failed to fetch key "{key}" {"key":"%5B9f9f8d915bcedabd75536e2f6fa966b7%5D%5B1%5D","exception":"[object] (Symfony\\Component\\VarExporter\\Exception\\NotInstantiableTypeException(code: 0): Type \"Doctrine\\ORM\\Query\\Exec\\AbstractSqlExecutor\" is not instantiable. at /htdocs/vendor/symfony/var-exporter/Internal/Registry.php:76)"} []>

I have cleared the cache (`cache:clear`) and warmed the cache (`cache:warmup`).

**Comment by xabbuh** [comment]
There have been some patches after 4.2.0 was released. Do you experience the same issue with 4.2.7?

**Comment by Rmy5** [comment]
@xabbuh Updating symfony to 4.2.7 solved the problem. Tx !  👍

**Comment by xabbuh** [comment]
Thank you for the confirmation. I am closing here then.
