### ISSUE TITLE
[VarDumper] Leverage PDO::activeQueryString

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31319]
Should we use this in PdoCaster somewhere?
https://wiki.php.net/rfc/debugging_pdo_prepared_statement_emulation

**Comment by stof** [comment]
Adding this as a virtual field of the PDOStatement caster might make sense.

**Comment by thib92** [comment]
Well, after trying to implement it, my local PHP version cannot run this, saying the `PDOStatement::activeQueryString` method doesn't exist.

I'm running `PHP 7.3.4 (cli) (built: Apr 19 2019 00:20:56) ( NTS )`

[The PR for this RFC on the official PHP Git](https://github.com/php/php-src/pull/2159) has been closed, and it seems like [the commit was reverted](https://github.com/php/php-src/search?q=activeQueryString&type=Commitsrl). I couldn't find anything related to cancelling this proposal though.

**Comment by nicolas-grekas** [comment]
Oups, sorry. Thanks for digging.
