### ISSUE TITLE
The template X doesn't exists

### ISSUE THREAD

**Issue by Randriamitsiry** [symfony/symfony#31316]
**Symfony version(s) affected**: 4.2.5

**Description**  
I'm creating a service for email management
Before, I only use the default configuration of symfony until I need to add 'fromEmail' for swift_mailer as a dependency

`
My service definition looks like this
Since, every time I try to send an email, I receive the error message 'The template X doesn't exists'

If I set the 'fromEmail' in the hardcoded way, everything works perfects but this is not I want

**How to reproduce**  
Just add 'fromEmail' of swift_mailer as service dependency like:
` App\Service\MailerManager:
arguments: ['@templating.engine.php', '@swiftmailer.mailer.default', '@app\Repository\UserRepository', '%env(MAILER_SENDER_ADDRESS)%']

**Possible Solution**  
Looks like reference namespace keeps the old way of previous version

**Additional context**  
![image](https://user-images.githubusercontent.com/16187196/56890777-7bb57a00-6a8b-11e9-879f-f310f9853de6.png)

**Comment by xabbuh** [comment]
Which versions of the Templating component and of the FrameworkBundle do you use? Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
Hm, I just noticed that you are explicitly using the PHP templating engine, but try to render a Twig template. This cannot work. So I am going to close here as there is no bug. Thank you for understanding
