### ISSUE TITLE
File upload in functional test not working after #30895

### ISSUE THREAD

**Issue by jeroendk** [symfony/symfony#31329]
**Symfony version(s) affected**: 3.4.25

**Description**  
According to the docs you can test a form with a file field as follow:

    // uploads a file
    $form['photo']->upload('/path/to/lucas.jpg');

In Symfony 3.4.24 this works, in 3.4.25 it does not because the form errors are added & isValid on the UploadedFile returns false.
```
elseif ($requestHandler->isFileUpload($event->getData()) && method_exists($requestHandler, 'getUploadFileError') && null !== $errorCode = $requestHandler->getUploadFileError($event->getData())) {
    $form->addError($this->getFileUploadError($errorCode)); 
}
```  
The related change is added in #30895 in the file `src/Symfony/Component/Form/Extension/Core/Type/FileType.php` on line **80**

Not sure why this worked before this change and how to get it working again..
   

**How to reproduce**  
Create a functional test with an upload form and submit it
```
$form['photo']->upload('/path/to/lucas.jpg');
$client->submit($form);
```

**Comment by xabbuh** [comment]
Can you debug which error code the request handler returns (and maybe also why)?

**Comment by jeroendk** [comment]
`getUploadFileError` in the request handler checks if the UploadedFile is valid with: `$data->isValid()`
`isValid` in UploadedFile returns false because neither `$this->test = true` or `is_uploaded_file()` is true
```
public function isValid()
{
    $isOk = UPLOAD_ERR_OK === $this->error;

    return $this->test ? $isOk : $isOk && is_uploaded_file($this->getPathname());
}
```

isValid always returned false but this was not a problem before.

**Comment by xabbuh** [comment]
I think a proper fix would ensure that the test flag is set to true in these cases. I am going to check how we could achieve that.

**Comment by jeroendk** [comment]
Great! from within the test case it seemed impossible to set the test flag, the upload & setValue both don't allow that in: `Symfony\Component\DomCrawler\FieldFileFormField`.

If I can be of assistance, let me know!

**Comment by xabbuh** [comment]
If you have some time to create a small application containing such a test that I could use to play with, that would be wonderful. :)

**Comment by jeroendk** [comment]
While setting up a demo project I can't replicate the problem, both `$this->test` and `is_uploaded_file($this->getPathname())` return true now...

Some other bundle might be involved in the bug, will get back on this.

**Comment by xabbuh** [comment]
let's close here then for now until we now how to reproduce it
