### ISSUE TITLE
[DomCrawler] A new use case arise a problem

### ISSUE THREAD

**Issue by shahariaazam** [symfony/symfony#31322]
```html
<div class="col-xs-12 packages-wrapper">
   <h4>Pack Size &amp; Price:</h4>
   <div class="package-container">
      250 mg vial
      :
      <span class="package-pricing">
      ৳ 55.00
      </span>
   </div>
   <div class="package-container">
      500 mg vial
      :
      <span class="package-pricing">
      ৳ 95.00
      </span>
   </div>
</div>
```

In this case, I can't extract only `250 mg vial`. Because when I am going to extract it, it's immidiate sibling node ` :
      <span class="package-pricing">
      ৳ 55.00` interrupt. What approach should I take?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by stof** [comment]
note that I don't even thing `250 mg vial` is a text node on its own in the DOM. The `:` on next line is probably part of the same text node.

DomCrawler does not have an API to work with each text node separately. It works with DOM children, not with DOM child nodes (based on the 2 different names available in the JS DOM API for these 2 concepts). If you want to do that, you will need to extract the DOMElement node for your `div` (using the `Crawler::getNode` method) and use the native APIs to get the DOMText child node you need
