### ISSUE TITLE
[Validator] type constraint with multi-types is not handled

### ISSUE THREAD

**Issue by lofk** [symfony/symfony#31330]
**Symfony version(s) affected**: 4.2.1

**Description**  
When I define a constraint type with multi-types (array of types), PHP returns a warning on line : `symfony/validator/Constraints/TypeValidator.php:36`, (`strtolower()` function with an array).

**How to reproduce**  
Create an object with a property having the following type constraint : 
```php
    /**
     * @var string|array
     * @Assert\Type(type={"string", "array"})
     */
    private $name;
```
**Possible Solution**  
- option 1 : throws a `InvalidMultiTypesException`
- option 2 : handle the multi-types constraint, by looping on the optional types, and validate if one of them is valid.

**Additional context**  
```sh
"message":"{"type":"api_exception","code":0,"message":"Warning: strtolower() expects parameter 1 to be string, array given","stack_trace":"#0 /var/www/html/vendor/symfony/validator/Validator/RecursiveContextualValidator.php(804): Symfony\Component\Validator\Constraints\TypeValidator->validate('2', Object(Symfony\Component\Validator\Constraints\Type))
```

**Comment by ro0NL** [comment]
That be a new feature, it's documented to be a string currently: https://symfony.com/doc/current/reference/constraints/Type.html#reference-constraint-type-type

**Comment by theoarena** [comment]
For those who are using an old **validator** version and cannot upgrade it, you can use `Assert\CallBack` to simulate "multiple types" (or whatever you need).

For example, if you want to validate your data as ` new Assert\Type('numeric')` and ` new Assert\Type('array')` simultaneously:


```

public function assertIsArray($object, ExecutionContextInterface $context, $payload){

      if( !is_array($object) )
          throw new \Exception( "Field '". $context->getPropertyPath() . "': should be of type array", 400 );

      $errors = $this->validator->validate($object, $payload);

      if (count($errors) > 0)
          throw new \Exception( "Field '". $context->getPropertyPath() . "': ". $errors->get(0)->getMessage(), 400 );

  }

//Now declare your constraint

$constraint = new Assert\Callback([
    'callback' => [$this, 'assertIsArray'], 
    'payload' => new Assert\Type('numeric')
]);

```

You could even have 'payload' as an array and iterate over it to apply your validations one at a time.
