### ISSUE TITLE
Yaml component can't parse JSON

### ISSUE THREAD

**Issue by ylixir** [symfony/symfony#31333]
**Symfony version(s) affected**: 4.2.4

**Description**  
Yaml component can't parse simple JSON. JSON is valid Yaml.

**How to reproduce**  
```php
\Symfony\Component\Yaml\Yaml::parse("{\n \n}");
```

**Additional context**  
I believe this has to do with bad whitespace assumptions.

Error message is
```
Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 1 (near "{").
```

**Comment by crayner** [comment]
Expected return is ?  "{\n \n}"

**Comment by ylixir** [comment]
Expected result is an empty array. That string is nothing special, just some empty brackets separated by some whitespace

**Comment by crayner** [comment]
Thanks.  It appears to be a mutli-line issue.

**Comment by crayner** [comment]
if accepted, #31369 returns an empty array for "{\n \n}" and "[\n    \n]"

**Comment by xabbuh** [comment]
Can you confirm that #33658 will solve your issue?
