### ISSUE TITLE
[DIC] !tagged tag list not showing with --show-arguments in debug:container

### ISSUE THREAD

**Issue by linaori** [symfony/symfony#31340]
**Symfony version(s) affected**: 3.4+

**Description**  
When using `bin/console debug:container my_service --show-arguments` and this service contains an argument as `!tagged my_tag`, it will not properly show the arguments being passed. The XML will only contain a "tagged" element and doesn't tell you which services will be injected. The command line output will tell you there are 0 elements in the iterator.

**How to reproduce**  
```yaml
services:
    my_service:
        class: stdClass
        arguments: [!tagged my_tag]

    my_tagged_service_1:
        class: stdClass
        tags: [my_tag]

    my_tagged_service_2:
        class: stdClass
        tags: [my_tag]
```
To verify the services are actually there:
```
bin/console debug:container --tag=my_tag

Symfony Container Public Services Tagged with "my_tag" Tag
==========================================================

 --------------------- ------------ 
  Service ID            Class name  
 --------------------- ------------ 
  my_tagged_service_1   stdClass    
  my_tagged_service_2   stdClass    
 --------------------- ------------ 
```

Missing argument information:
```
bin/console debug:container my_service --show-arguments 
Information for Service "my_service"
====================================

 ---------------- ------------------------- 
  Option           Value                    
 ---------------- ------------------------- 
  Service ID       my_service               
  Class            stdClass                 
  Tags             -                        
  Public           yes                      
  Synthetic        no                       
  Lazy             no                       
  Shared           yes                      
  Abstract         no                       
  Autowired        yes                      
  Autoconfigured   yes                      
  Arguments        Iterator (0 element(s))  
 ---------------- -------------------------
```

**Possible Solution**  
I would personally already be satisfied if it properly displayed the actual count, and it would be even better if it could display the list of service_ids it would inject.
```
Iterator (2 element(s))
# or
Tagged Iterator (2 element(s)) [
    my_tagged_service_1
    my_tagged_service_2
]
```

This is currently making it a bit troublesome to see if your `!tagged` works and in a more complex system (autoconfigure), if all the services are picked up correctly.

**Comment by jschaedl** [comment]
In `debug` mode the `ContainerDebugCommand` uses a non compiled container. So services injected in iterable arguments are not resolved and the `IteratorArgument::getValues()` returns an empty array which is the reason for showing `Iterator (0 element(s))`.

However if you use `./bin/console debug:container my_service --show-arguments --env=prod` the used container will be compiled and the number of Iterator elements are shown correctly:

```bash
Information for Service "my_service"
====================================

 ---------------- -------------------------
  Option           Value
 ---------------- -------------------------
  Service ID       my_service
  Class            stdClass
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
  Arguments        Iterator (2 element(s))
 ---------------- -------------------------
```

I tried to introduce a compiled container also in debug mode, but got a lot of failing tests. Fixing all the related fixtures and tests feels not like a small bugfix to me and I doubt that something,like this will get merged. So I suggest we remove the number of elements information, when someone executes the command in debug mode.

WDYT?

**Comment by linaori** [comment]
Would it be an idea to show the name of the tagged iterator instead? That information is available if I recall correctly. If you can see which tag you insert, you can do a `--tag=my_tag` to see the actual services.
```

Information for Service "my_service"
====================================

 ---------------- -------------------------------
  Option           Value
 ---------------- -------------------------------
  Service ID       my_service
  Class            stdClass
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
  Arguments        Tagged Iterator for "my_tag"
 ---------------- -------------------------------
```
