### ISSUE TITLE
[Console] No way to set custom question helper for SymfonyStyle

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#31359]
**Description**  
Currently the SymfonyStyle sets the question helper [this way](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Style/SymfonyStyle.php#L290).

```
if (!$this->questionHelper) {
    $this->questionHelper = new SymfonyQuestionHelper();
}
```
This implies that there should be a way to set the helper however `questionHelper` is a private property and has no setter. So that the condition seems useless.

**Possible Solution**  
Provide a way to set an arbitrary question helper for the  `SymfonyStyle`.

**Comment by Chi-teck** [comment]
> This implies that there should be a way to set the helper however

Well, probably it's just for reusing existing instance of the question helper.

**Comment by YaFou** [comment]
> 
> 
> > This implies that there should be a way to set the helper however
> 
> Well, probably it's just for reusing existing instance of the question helper.

Yes, it is I think. The issue can be close @Chi-teck?
