### ISSUE TITLE
phantom tag 2.8.51

### ISSUE THREAD

**Issue by remicollet** [symfony/symfony#31357]
Lastest is 2.8.50 but a 2.8.51 tag exists and is listed on packagist (78d86f8516ea82fa809c0289a01d04f5aa3c0cd0)
https://packagist.org/packages/symfony/symfony#v2.8.51

**Comment by fabpot** [comment]
This is not a phantom tag. The following tags "v4.1.13", "v2.8.51", "v2.7.52" exist for symfony/symfony and symfony/http-kernel but not for the other components. They were created as this component was broken after the security releases for versions that were not maintained anymore.

**Comment by remicollet** [comment]
But 2.8.51 have no information in the changelog

This is very confusing

**Comment by nicolas-grekas** [comment]
Hi Remi, there's no changelog: this is just a tag to fix a previously broken one, see diff at
https://github.com/symfony/symfony/compare/v2.8.50...v2.8.51

**Comment by remicollet** [comment]
Isn't "fix VERSION_ID not an number" a real change ?

**Comment by mpdude** [comment]
Ouch. This caused me some headache today, as I simply grabbed the "2.8.51" as the latest 2.8 release and tried to install `symfony/this` and `symfony/that` as `2.8.51`.

The result was that Composer always happily installed `symfony/symfony`, yet never giving a reason for it. It's that `symfony/symfony` Composer-`replace`s the other components and so virtually there *is* a `2.8.51` for them.
