### ISSUE TITLE
[Security] Allow firewalls to match routes

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#31362]
**Description**  
I never really liked firewalls `pattern` configuration because URLs rarely are grouped by firewall, which mean you either have to write an increasingly complex regex (does someone like writing regexes?) or duplicate the firewall with a different pattern.

My proposal is to make possible selecting a firewall from a route's `_firewall` default.

**Example**  
Given the following configuration

```yaml
security:
    firewalls:
        some_firewall:
            # ?
```

I want it to match a route whose `_firewall` default is `some_firewall`.

Does it make sense?

**Comment by stof** [comment]
I don't understand what you mean by `URLs rarely are grouped by firewall`.

And btw, how many firewalls do you have ?

**Comment by MatTheCat** [comment]
> I don't understand what you mean by `URLs rarely are grouped by firewall`.

I mean you can't always match a firewall by a simple URL path prefix.

> how many firewalls do you have

I had four (five with the profiler's).

**Comment by stof** [comment]
@MatTheCat could you share an example where this would be needed (and what your 4 firewalls are) ?

**Comment by MatTheCat** [comment]
I don't have access to the repo anymore. But there were

- anonymous
- anonymous or logged
- logged
- logged under an organization

Using `pattern` would have been a real headache (we didn't even know the final URLs at this time) so I implemented this proposal myself by using a `request_matcher` per firewall.

BTW it seems `request_matcher` is no longer documented?

**Comment by linaori** [comment]
This sounds like it should be a single firewall with different permissions. You can have multiple users under the same firewall, especially when using guard.

**Comment by stof** [comment]
using a `request_matcher` is precisely meant to cover more advanced use cases.
Not documenting anymore looks like a doc issue to me.

Regarding your cases, the places allowing anonymous access or only logged access indeed looks like something which should be handled by the authorization layer rather than using separate firewalls (which are about configuring the authentication layer).

**Comment by MatTheCat** [comment]
Okay now could we judge my proposal instead of a specific configuration? It exists because of multiple specific reasons which I won't detail because it is not the point.

Configuring the firewall a route must match in its default is the best I ever felt while using the SecurityBundle. The only downside was I had to create one service per firewall myself, which was cumbersome.

If you're telling me everybody loves writing regexes in `pattern` then let's just close this.

**Comment by linaori** [comment]
I don't understand your proposal, can you elaborate a bit more? I've never needed a complex regex for my firewalls, as the approach is top to bottom and stops when it matches one of them.
```
# first one
pattern: ^/_dev(.*whatever)
security: false

# any explicit firewalls
pattern: ^/oauth/for/example
anonymous: true

# the actual area where you need to be authenticated
pattern: ^/
anonymous: true
guard: ~
```

> Okay now could we judge my proposal instead of a specific configuration? It exists because of multiple specific reasons which I won't detail because it is not the point.

Those specific reasons are exactly what's important to know. Any (big) changes to the security component can impact a lot in complexity. If we know _why_ a certain setup is done, we can look into simplifying this. If there's no reason to set it up like that, we can advice how to do it differently, preventing possibly complex but unused features from entering the component.

**Comment by MatTheCat** [comment]
It is not required for paths to have the same prefix to match the same firewall.

Say the user have to be logged everywhere except on 10 pages whose URL is arbitrary. Are you going to create a regex matching these 10 pages or checking if the user is logged everywhere else?

My proposal is to make it possible for a route to tell which firewall it will match. That way you would tell the 10 anonymous routes to match the anonymous firewall, and the default one would require the user to be logged.

This wouldn't be a big change nor a complex one.

**Comment by linaori** [comment]
I would put everything on the `^/` firewall and regulate this with access control. `IS_AUTHENTICATED_ANONYMOUSLY` on those 10 pages, `IS_AUTHENTICATED_FULLY` on the others. Routes/controller should be unaware of the firewall, it's not their responsibility. If you don't want to decide this with access control, you can always use an `@IsGranted` or  `@Security` annotation instead.

**Comment by MatTheCat** [comment]
So let's say it's now 50 pages because your URLs are translated. Does that mean 50 lines under `access_control` or hundreds of `@isGranted`?

**Comment by linaori** [comment]
Depending on the complexity of the urls, maybe. If you have everything in a single controller, not so much. If it's database content, you can also use the `AuthorizationChecker` and store the permissions in the database to see if a login is required, there are a lot of possibilities. 

Firewalls are for authentication, not authorization. Being anonymous or not, is part of the firewall. A firewall can indicate whether or not anonymous users are permitted. Authorization (either access control, annotations, `AuthorizationChecker` etc) are to determine whether the current resource allows anonymous users, remember me (cookie) users or requires a fully authenticated user. Putting all this on a second firewall is more effort than it's worth and makes the authentication a lot more complex, especially if you want to allow fully authenticated users on that anonymous page.

Do you have a full example to show what you mean for your suggestion? It makes it easier to grasp the RFC if the example is complete.

**Comment by MatTheCat** [comment]
Here is how I implemented it in the userland:

```php
<?php

namespace Symfony\Bundle\SecurityBundle;

use Symfony\Component\HttpFoundation\RequestMatcherInterface;

class FirewallRequestMatcher implements RequestMatcherInterface
{
    private $name;

    public __construct(string $name)
    {
        $this->name = $name;
    }

    public function matches(Request $request)
    {
        return $request->attributes->get('_firewall') === $this->name;
    }
}
```

For each firewall I create a service passing its name as parameter. Then I configure these as the corresponding firewall's `request_matcher`. Now I just have to add a `_firewall` default to any route for it to be handled by the corresponding firewall.

Given this configuration

```yaml
security:
    firewalls:
        test:
            request_matcher: security.request_matcher.test
            # ...
        main:
            # ...
````
this route

```yaml
route:
    path: /whatever
    controller: Whatever::youWant
    defaults:
        _firewall: test
```

would match the `test` firewall.

It's really just a way to avoid `pattern` when it's not practical so I guess my examples were misleading.

**Comment by MatTheCat** [comment]
> Routes should be unaware of the firewall

Then WDYT about a `routes` options under firewalls?

**Comment by MatTheCat** [comment]
Following https://github.com/symfony/symfony/pull/31485#issuecomment-494030965 I replaced `routes` with `route_params`.
