### ISSUE TITLE
Lock component behaviour different when called from command and controller 

### ISSUE THREAD

**Issue by Rmy5** [symfony/symfony#31363]
**Symfony version(s) affected**: 4.2.7

**Description**  
I want to make a service available both through a custom command and an HTML page (admin page). 
I want to prevent the service to be executed multiple times in parallel. 
I'm using the lock in the service. 

When I call the service through my custom command, if the service is already in use (locked), the service exits (returning: 'SERVICE_RUNNING'), the code protected by the lock is not executed.

When I call the service through the controller (HTML page), if the process is already running from the command the service exits ('SERVICE_RUNNING' is displayed) and the code protected by the lock is not executed from the HTML page (controller).

When I call the service through the controller (HTML page),  if the process is already running from the controller (two HTML pages with same route), the service does not return 'SERVICE_RUNNING' the controller "waits" for the lock to "available" and the code protected by the lock is "stacked" and executed after the first controller request is finished.

In this case the service is not locked, requests to the service are stacked and executed in a queue.

Am I misusing the Lock Component ?

**How to reproduce**  
[https://github.com/Rmy5/testLock](https://github.com/Rmy5/testLock)

Open a tab in browser, go to route `test`, click `run service`.
Open a CLI call: `php bin/console call:service`.
=> CLI exists with 'SERVICE_RUNNING'

Open a CLI call: `php bin/console call:service`.
Open another CLI call: `php bin/console call:service`.
=> CLI exists with 'SERVICE_RUNNING'

Open a tab in browser, go to route `test`, click `run service`.
Open another tab in browser, go to route `test`, click `run service`.
=> second tab "waits" for first tab to be "finished".
=> Service doesn't exit, requests are stacked.

**Comment by stof** [comment]
are you running the 2 tabs with the same PHP session ? I'm wondering whether this "waiting" is related to the locking of your service (which would be weird to me) or to the locking of the PHP session.

**Comment by Rmy5** [comment]
I'm using two different browsers, it's setting different REMEMBERME cookies, so I guess they're two different PHP sessions ? I am using the built in dev server though.

**Comment by stof** [comment]
the built-in dev server is single-threaded, so it does not support concurrent requests. Use PHP-FPM instead (you can use the [Symfony local server](https://symfony.com/doc/current/setup/symfony_server.html) to handle that easily locally).

**Comment by Rmy5** [comment]
You are right the issue was the single-thread. Using the command locally is multi-threaded so parallel execution is working ok, when the symfony built in server is single thread. I tested on a server it's working ok ! Tx. 👍
