### ISSUE TITLE
Messenger - Impossible to retrieve the Datetime object in the Handler

### ISSUE THREAD

**Issue by numerogeek** [symfony/symfony#31361]
**Symfony version(s) affected**: 3.4.24

**Description**  
I dispatch a message which contains a \Datetime field. When the consumer consumes the message, it crashes because the constructor expect to receive a \datetime, but a string is given.

**How to reproduce**  

```
class Message implements MessageInterface
{
    private $randomId;
    private $createdAt;

    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function __construct(string $randomId, \Datetime $createdAt)
    {
        $this->randomId = $randomId;
        $this->createdAt = $createdAt
    }
```

Then, dispatch the message to rabbitMQ and consume the message.
The payload in rabbit is : `{"randomId ":"39","createdAt":"2019-05-02T10:49:10+02:00"}`

and it fires an error: `"Argument 2 passed to Message::__construct() must be an instance of DateTime, string given. `

**Additional context**  

I use the Symfony serializer

```
_messenger.yaml_

 Symfony\Component\Messenger\Transport\Serialization\Serializer:
    arguments:
      $serializer: '@Symfony\Component\Serializer\SerializerInterface'
Symfony\Component\Messenger\Transport\Serialization\SerializerInterface: '@Symfony\Component\Messenger\Transport\Serialization\Serializer'
```

Any suggestion ? 

thank you !

**Comment by chalasr** [comment]
I can't manage to reproduce.
Also there is no 3.4 version of Messenger. Can you paste the output of `composer show` and the full stack trace of your error (run the consume command with `-vvv`)?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Kazadri** [comment]
@numerogeek I have the same issue, did you, by any chance, found a solution ?
