### ISSUE TITLE
Form ERROR when use FormData with ARRAYS

### ISSUE THREAD

**Issue by pittersnider** [symfony/symfony#31368]
**Symfony version(s) affected**: 3.4.23

### Description  
When I submit an AJAX with an array **(picture below)**, I got an error: “**This value is not valid.**.”

### How to reproduce  

**Use a formulary type like this one:**  
![image](https://user-images.githubusercontent.com/13719228/57101889-9d676900-6cf8-11e9-99c1-f9cd24a0fc5b.png)

**Use a controller like this one:**
![image](https://user-images.githubusercontent.com/13719228/57102040-e9b2a900-6cf8-11e9-984a-4fed16651ede.png)

The code above specified in images are available here, respectively:
- **Form type:** https://oneclickpaste.com/3636/
- **Controller:** https://oneclickpaste.com/3635/

### The sent data in FormData was:
![image](https://user-images.githubusercontent.com/13719228/57102453-e53ac000-6cf9-11e9-9f7d-0b88146e43db.png)

**Comment by ro0NL** [comment]
You can use the profiler to see which field is invalid, and maybe a cause. This report is to vague.

Also realize, you rely on type guessing ... so maybe it's guessed wrong/different causing the confusion on your side.

**Comment by ro0NL** [comment]
Does the same error occur without the event listener? Can you check the profiler which field is causing it?

**Comment by xabbuh** [comment]
This looks like it could be the same as #29809. @pittersnider Can you confirm this?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
