### ISSUE TITLE
[Console] Store the Input and Output as Command properties

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#31360]
**Description**  
The current approach is passing the Input and Output back and force like follows.

```
/**
  * {@inheritdoc}
  */
protected function interact(InputInterface $input, OutputInterface $output) :void {
  $this->getHelper('question')->ask($input, $output, new Question('Some question'));
}
```
This makes the method signatures quite long as you often have to reserve first two parameters for Input and Output. This is especially annoying when you call methods of custom helpers that
accept many own arguments besides required Input and Output.

**Proposed solution**
Store the Input and Output in command properties. Supply command helpers with Input and Output  in `Application` class (for Input it's already [done](https://github.com/symfony/symfony/blob/v4.2.8/src/Symfony/Component/Console/Application.php#L901)).
```
/**
  * {@inheritdoc}
  */
protected function interact() :void {
  $this->getHelper('question')->ask(new Question('Some question'));
}
```

**Comment by RonanSauvage** [comment]
IMO it's usefull for 95% of use cases but I think we must keep the possibility to define other $input or $output. 
For example, we may wish to add one decorator to define one more stream (like file system) to output our result. 

What do you think ?

**Comment by TomasVotruba** [comment]
I actually use Input and Output as services like this since 2015. It saves much trouble with passing them around.

**Comment by chalasr** [comment]
This would require to deprecate all existing methods that take the input and output as arguments as we cannot remove arguments (BC break), so we would need to find an equivalent name for each one.
Given that renaming is painful for everyone and you can create those properties on your own to avoid the redundant method arguments, I think it's not worth the hassle.

**Comment by TomasVotruba** [comment]
@chalasr I think the main point is to move to the service and constructor injection. Same trend Controller has, e.g. with `RequestStack` and other services

**Comment by chalasr** [comment]
@TomasVotruba There is not point in allowing constructor injection if you are still forced to pass them as arguments for method calls, which would be the case if we don't change signatures to at least make these arguments optional (which is a BC break).

**Comment by Chi-teck** [comment]
The possible way to avoid BC break is creating a new base Command class which implements `InputOutputAware` interface. Legacy commands can still use existing (deprecated) Command class.

**Comment by chalasr** [comment]
Same would be needed for e.g.`QuestionHelper`. Still -1 for me

**Comment by Simperfit** [comment]
I think this is not worth the changes, and the whole deprecation that will be maintain until 5.0 and all the libs that will be mandatory to upgrade. 
-1 for me too.

**Comment by Chi-teck** [comment]
Here is workaround I use. It is suitable for those who maintain a large set of console commands.
1. Create a new abstract class based on `Command` class.
2. Within the class create a protected property that wraps input and output using `SymfonyStyle`. This could be done like follows.
```
protected function initialize(InputInterface $input, OutputInterface $output) :void {
    $this->io = new SymfonyStyle($input, $output);
}
```
3. Optionally,  create `IOAwareInterface` and pass the IO object to helpers that need it.
```
foreach ($this->getHelperSet() as $helper) {
    if ($helper instanceof IOAwareInterface) {
        $helper->io($this->io);
    }
}
```
4. Declare additional abstract method and invoke it from execute state.
```
protected function execute(InputInterface $input, OutputInterface $output) :?int {
    return $this->doExecute();
}
```


This will make commands that deal with input and output a way less verbose.

Before:
```
protected function execute(InputInterface $input, OutputInterface $output) :?int {
    $anwser = $this->getHelper('question')->ask($input, $output, new Question('Some question'));
}
```
After:
```
protected function doExecute() :?int {
    $anwser = $this->io->ask('Some question');
}
```

Also this will allow to use consistent output style across all commands and helpers.

The only tricky part here is finding a good name for the new method. Because both names that come to mind `run` and `execute` are already taken by `Command` class.

**Comment by Chi-teck** [comment]
Closing as it seems to require too much work to preserve backward comparability.
