### ISSUE TITLE
framework.session.cookie_secure does not default to 'auto'

### ISSUE THREAD

**Issue by cilefen** [symfony/symfony#31376]
**Symfony version(s) affected**: 4.2.7

**Description**  
[framework.session.cookie_secure option](https://symfony.com/doc/current/reference/configuration/framework.html#cookie-secure), when unset, does not default to 'auto'.

**How to reproduce**  
1. Do not set framework.session.cookie_secure option.
2. Start a session on an app that is on https.
3. Observe the resulting cookie. The secure option is not set.
1. Set framework.session.cookie_secure option to 'auto'.
2. Start a session on an app that is on https.
3. Observe the resulting cookie. The secure option is set.

The documentation reads that cookie_secure defaults to 'auto' but in the testing I have done, cookies are secure only if cookie_secure is set to 'auto'.

**Possible Solution**  

**Additional context**

**Comment by nicolas-grekas** [comment]
It's set to "auto" by default in the recipe: https://github.com/symfony/recipes/pull/452
Changing the default in the code would be a BC break we cannot do without a painful upgrade path.

**Comment by cilefen** [comment]
I see. Perhaps a documentarian update would sort it out.

**Comment by nicolas-grekas** [comment]
Sure, would you mind opening a doc issue, or better: a PR?

**Comment by cilefen** [comment]
I’m on it.

**Comment by nicolas-grekas** [comment]
Thanks, closing here then.
