### ISSUE TITLE
Dynamic transport creation

### ISSUE THREAD

**Issue by DruGity** [symfony/symfony#31373]
What i need is to create several queues right in code with different names, not in `messenger.yaml`. I have tried to do it with TransportFactory, but it is not what i need.
So the question is - **Can i create queues dynamically?** Does such opportunity exists in Messenger component?

**Comment by chalasr** [comment]
>  I have tried to do it with TransportFactory, but it is not what i need.

Then can you explain what you mean by "creating queues dynamically"?
If what you want is to create the queue on the transport (`doctrine:database:create` like) then the  `SetupableTransportInterface` coming in Symfony 4.3 might be the solution.

```php
$transport = $transportFactory->createTransport('dsn');
$transport->setup();
```

It is implemented by all built-in transports.

**Comment by DruGity** [comment]
What i need is to create several queues with different names, something like this:
```
foreach($array as $item) {
    $channel = $bunny->channel();
    $channel->queueDeclare($item['name']); 
}
```
Like in https://packagist.org/packages/bunny/bunny library
Can i do so in **The Messenger Component**? Because what i see now - that i can only create one transport with one queue.

**Comment by chalasr** [comment]
The low-level [AmqpFactory](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpFactory.php) seems to be what you are looking for.
Please check the class and its usages to see what you can do with it and tell us if you think there is something more to do in Symfony. 
If you need help for experimenting, please try our [support platforms](https://symfony.com/support) and close this issue.
Thank you

**Comment by DruGity** [comment]
Thanks, you are absolutely right about  low-level AmqpFactory. I used another library for my needs. I wish The Messenger had such opportunity, but its great even without it)

**Comment by oleg-andreyev** [comment]
@DruGity  Ideally queues are created by consumers, so for each "dynamic" queue you need to create a consumer with correct bindings and publisher just uses AmqpStamp with binding and publish should declare only exchange.
