### ISSUE TITLE
'symfony/console' 3.x: 'symfony/debug' is in require-dependencies

### ISSUE THREAD

**Issue by kalessil** [symfony/symfony#31379]
**Symfony version(s) affected**: 3.*

**Description**  
The dev-components should not be part of production dependencies.

**How to reproduce**  
n/a, we found the issue after introducing kalessil/production-dependencies-guard with `check-lock-file`. The dependency got into production-dependencies, we had to white-list it but that's doesn't look right IMO.

**Possible Solution**  
Moving the dependency to require-dev section

**Additional context**  
n/a

**Comment by nicolas-grekas** [comment]
Despite its name, the debug component is used in prod setups actually.

**Comment by kalessil** [comment]
Oh, that sounds interesting =) What about `var-dumper`? Is it also production-safe?

**Comment by nicolas-grekas** [comment]
Yes it is safe for prod too, although I'm not sure anyone uses it for prod things.

**Comment by kalessil** [comment]
Apparently, it appears in the prod-dependencies in a project my company is working on (didn't dig through which OSS library bring it). On my end, I'll whitelist both packages then. Thanks for the fast response!
