### ISSUE TITLE
[HttpFoundation] about add cache size limit in IpUtils

### ISSUE THREAD

**Issue by phpor** [symfony/symfony#31388]
**Description**  
In src/Symfony/Component/HttpFoundation/IpUtils.php , static variables are used to optimize the performance of the cache, but without limiting the size of the cache, the size of the cache can become large over time, will it would be better to adding cache size limits？

**Comment by nicolas-grekas** [comment]
> will it would be better to adding cache size limits？

only if it provides something useful in practice. PR welcome if you think so (ie have a use case ;) )

**Comment by Simperfit** [comment]
@nicolas-grekas I don't see the use case either.

**Comment by fabpot** [comment]
Closing as there is no more activity here.
