### ISSUE TITLE
[Mailer] Allow create custom transports and register DSN for it

### ISSUE THREAD

**Issue by Koc** [symfony/symfony#31385]
For the now [there is no extension](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Transport.php) point for registering custom DSN for adding own Mailer Transport. Would be nice allow create custom transports like already done in Messenger.

**Comment by javiereguiluz** [comment]
We can't provide official integrations for all mailer services, only for the most popular/used ones ... so I guess this is something we should implement to let the community create their own mailer integrations. Thanks.

**Comment by Koc** [comment]
See #31946 with some ideas about implementation
