### ISSUE TITLE
[Serializer] YAML config not working

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#31391]
**Symfony version(s) affected**: x4.2.8

**Description** 
According to the documentation you could configure the serializer by putting either `*.yaml` or `*.xml` files into the `config/serializer` directory.
But this does not work.
None of the `attributes` config is respected.

**How to reproduce**  
I have prepared a repo with demo code under:
[https://github.com/crtl/symfony-serializer-not-working](https://github.com/crtl/symfony-serializer-not-working)

**Comment by mdeboer** [comment]
Have you tried removing `config/serialization.yaml`? Could be conflicting as you both specify rules for the same entity.

**Comment by Simperfit** [comment]
@crtl could you try what @mdeboer suggested ?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Darksheep42** [comment]
I am having the same issue with Symfony 4.3
Maybe the doc should be updated to explain how you can load yaml metadata automatically ?
or is it supposed to work out of the box ?

crtl provided a code sample

**Comment by Gus19** [comment]
Hello, nothing new about this issue ?

**Comment by xabbuh** [comment]
This issue is closed as there was no further feedback from the reporter. If you think there is an issue that needs to be fixed, please open a new one and provide a small example application that allows to reproduce it.
