### ISSUE TITLE
[HttpClient] Invalid callback error on HTTP/2 preload headers

### ISSUE THREAD

**Issue by GawainLynch** [symfony/symfony#31404]
Version(s)
----------

  - **Symfony**: 4.3@dev
  - **PHP**: 7.3.5 & 7.2.18
  - **Webserver**: Nginx 1.16.0 (Fedora 30 package)

## Description

cURL throws an `E_WARNING`: ` Invalid callback , no array or string given` when calling `CurlHttpClient#request()` on a HTTP/2 address that includes preload `Link` headers.

## How to reproduce

**Controller** 

```php
$response = new Response();
// …
$response->headers->set('Link', '</assets/app.js>; rel="preload"; as="script"; crossorigin="anonymous"; integrity="sha384-abc123");
```

**Client**

```php
use Symfony\Component\HttpClient\CurlHttpClient;
// …
$client = new CurlHttpClient(['http_version' => '2.0']);
$client->request('GET', 'https://my-http2-host');
```

## Additional context

Relevant:
  - [PHP bug #77535](https://bugs.php.net/bug.php?id=77535)
  - [Fix for 7.3.5 & 7.2.17](https://github.com/php/php-src/commit/97f9fd6949a52d1eb30c3e1c90f0789b57c29468)

**Comment by nicolas-grekas** [comment]
What's the line of the warning? This is supposed to be fixed in PHP 7.2.17/7.3.4, isn't it?
Can you run the test suite, especially the test case for HTTP/2?
Can you try this patch in `CurlHttpClient`?
```diff
-        curl_multi_setopt($this->multi->handle, CURLMOPT_PUSHFUNCTION, static function ($parent, $pushed, array $requestHeaders) use ($multi, $maxPendingPushes, &$logger) {
+        curl_multi_setopt($this->multi->handle, CURLMOPT_PUSHFUNCTION, $multi->push = static function ($parent, $pushed, array $requestHeaders) use ($multi, $maxPendingPushes, &$logger) {
```

**Comment by nicolas-grekas** [comment]
friendly ping @GawainLynch

**Comment by GawainLynch** [comment]
I have this queued for when I get back from Berlin, after Maintainerati on Friday, @nicolas-grekas :smile:

**Comment by GawainLynch** [comment]
Same problem, @nicolas-grekas 

```
In CurlResponse.php line 244:
                                                        
  [ErrorException]                                      
  Warning: Invalid callback , no array or string given  
                                                        

Exception trace:
 () at [snip]/http-client-sandbox/vendor/symfony/http-client/Response/CurlResponse.php:244
 Symfony\Component\HttpClient\Response\CurlResponse::perform() at [snip]/http-client-sandbox/vendor/symfony/http-client/Response/ResponseTrait.php:261
 Symfony\Component\HttpClient\Response\CurlResponse::stream() at n/a:n/a
 Generator->current() at [snip]/http-client-sandbox/vendor/symfony/http-client/Response/CurlResponse.php:117
 Symfony\Component\HttpClient\Response\CurlResponse::Symfony\Component\HttpClient\Response\{closure}() at [snip]/http-client-sandbox/vendor/symfony/http-client/Response/ResponseTrait.php:231
 Symfony\Component\HttpClient\Response\CurlResponse->doDestruct() at [snip]/http-client-sandbox/vendor/symfony/http-client/Response/CurlResponse.php:177
 Symfony\Component\HttpClient\Response\CurlResponse->__destruct() at [snip]/http-client-sandbox/src/Sandbox.php:58
 App\Sandbox->run() at [snip]/http-client-sandbox/src/Command/SandboxHttpClientCommand.php:35
[snip]
```

For completeness, the test-case requires (plus patch in `CurlHttpClient`):
```
    "require": {
        "php": "^7.2.17",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "^4.2",
        "symfony/dotenv": "^4.2",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "^4.2",
        "symfony/http-client": "^4.3",
        "symfony/web-server-bundle": "^4.2",
        "symfony/yaml": "^4.2"
    },
```

**Comment by nicolas-grekas** [comment]
Just tested HTTP/2 push with php 7.3.5 & 7.2.18 and curl 7.64 using Fedora 30 + Remi's repo, all green
Also the linked bug is fixed AFAIK in said php versions so that it might be something else.
Or maybe the report is invalid?
I would now need a full reproducer. Could be a VM or similar. I can't do more sorry.

**Comment by GawainLynch** [comment]
Just tested with 4.3.0 and the problem is no longer present, so calling this one fixed. 

Thank you very kindly for a superb effort looking into this one @nicolas-grekas :+1:
