### ISSUE TITLE
Doctrine.yaml dbal options ssl certificates always error : Expected scalar, but got array.

### ISSUE THREAD

**Issue by GreenLeewayDesignCastle** [symfony/symfony#31408]
**Symfony version(s) affected**: 4.2.8

**Description**  
I want to connect to my database, but for this I need to use 3 different .pem files. I've tried connecting to the mysql database through CLI and had luck, could do anything and everything (crud). Now I want to use the same .pem files to access the database from my Symfony project. I've read the symfony dbal documentation : https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

This is my current configuration (doctrine.yaml): 
`
parameters:
  env(DATABASE_URL): ''
  private_key: App\Resources\certificates\client-client-key_slave.pem
  public_cert: App\Resources\certificates\client-serv-cert_slave.pem
  ca_cert: App\Resources\certificates\server-ca_slave.pem

doctrine:
  dbal:
    default_connection:       default
    connections:
      default:
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
          driver: pdo_mysql
          server_version: '5.7'
          url: '%env(resolve:DATABASE_URL)%'
          options:
            1010: '%private_key%'
            1011: '%public_cert%'
            1012: '%ca_cert%'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    filters:
      softdeleteable: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
      product_generation_filter: App\Doctrine\ProductGenerationFilter
      product_data_filter: App\Doctrine\ProductDataFilter
      product_price_filter: App\Doctrine\ProductPriceFilter
      product_minutes_filter: App\Doctrine\ProductMinutesFilter
      product_subscription_length_filter: App\Doctrine\ProductSubscriptionLengthFilter
      product_sms_filter: App\Doctrine\ProductSmsFilter
      product_category_filter: App\Doctrine\ProductCategoryFilter
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
`

To test if it actually works and makes connection the database i run this command : 
bin/console debug:config DoctrineBundle

And every single time I run this command I get an InvalidTypeException with this message :
Invalid type for path "doctrine.dbal.connections.default.default_table_options.options". Expected scalar, but got array.

The reason I added 1010, 1011 and 1012 as option_name in options is because these are the constants used for the params that I want to send: 
PDO::MYSQL_ATTR_SSL_KEY :1010
PDO::MYSQL_ATTR_SSL_CERT :1011
PDO::MYSQL_ATTR_SSL_CA :1012

**How to reproduce**  
1. Create your own database
2. Make it only available for users that have these 3 .pem files
3. Verify connection by running the next command in your cli : mysql --ssl-ca=server-ca_slave.pem --ssl-cert=client-serv-cert_slave.pem --ssl-key=client-client-key_slave.pem  -hIP_HOST -uUSERNAME -pPASSWORD DB_NAME

**Comment by GreenLeewayDesignCastle** [comment]
@xabbuh Have you experienced this problem ?

**Comment by stof** [comment]
a bunch of your options should not be nested inside `default_table_options`, but be part of the connection config. that's probably the root cause of your issue.

**Comment by GreenLeewayDesignCastle** [comment]
Hey Stof, thank you for your reply ! I figured the problem out, it was indeed not correctly nested, to help others I will post my current working configuration. 
parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''
  private_key: '%kernel.project_dir%/certs/client-client-key_slave.pem'
  public_cert: '%kernel.project_dir%/certs/client-serv-cert_slave.pem'
  ca_cert: '%kernel.project_dir%/certs/server-ca_slave.pem'

doctrine:
  dbal:
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    driver: pdo_mysql
    server_version: '5.7'
    url: '%env(resolve:DATABASE_URL)%'
    options:
       !php/const:PDO::MYSQL_ATTR_SSL_CA: '%ca_cert%'
       !php/const:PDO::MYSQL_ATTR_SSL_KEY: '%private_key%'
       !php/const:PDO::MYSQL_ATTR_SSL_CERT: '%public_cert%'
       !php/const:PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: false
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    filters:
      softdeleteable: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
      product_generation_filter: App\Doctrine\ProductGenerationFilter
      product_data_filter: App\Doctrine\ProductDataFilter
      product_price_filter: App\Doctrine\ProductPriceFilter
      product_minutes_filter: App\Doctrine\ProductMinutesFilter
      product_subscription_length_filter: App\Doctrine\ProductSubscriptionLengthFilter
      product_sms_filter: App\Doctrine\ProductSmsFilter
      product_category_filter: App\Doctrine\ProductCategoryFilter
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
