### ISSUE TITLE
[symfony/lock] Lock always expired 

### ISSUE THREAD

**Issue by slince** [symfony/symfony#31426]
**Symfony version(s) affected**: 3.4.27

**Description**  

When multiple processes get a lock, the [lock expired exception](https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L70) will always appear, no any processes can successfully acquire the lock.

**How to reproduce**  

```php
$store = new RedisStore($redisInstance, 20);
$store = new RetryTillSaveStore($store);
$factory = new Factory($store);
  
$lock = $factory->createLock('foo', 10); 
$lock->acquire(true);
   // do something
$lock->release(); 
```

**Additional context**  

RedisStore  `$initialTtl  =  20`

Assuming the current time is `10:00s`, the process "A" and the process "B" are ready to acquire the lock "foo", "foo" will be released at 10:20;

### At 10:20s:
`A` successfully acquires the lock,   accourding to [https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L57](https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L57)

The expire time of the key in the redis will be modified to `10:40s` ; but since the key expire time in memory is `10:20s`, the `A` will exit because the program does not capture [`LockExpriedException`](https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L70) and then `A` will be restart by the supervisor;

### At 10:40s:

The `B` acquires the lock, and the redis expire time will be modified to `11:00s`, but also because the expire time in memory (`10:20s`) timeout,  `B` will also exit and restart;

After that, `A` and `B` get the locks in turn, and extend the expiration time by  `$initialTtl  =  20s`. but since the the expiration time in  memory is not updated,  no process can successfully acquire the lock.

![image](https://user-images.githubusercontent.com/3785826/57387229-85a44f00-71e8-11e9-8b86-3ce9e7cda5cf.png)

**Comment by slince** [comment]
Maybe we should remove the expire time check from here.
[https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L70](https://github.com/symfony/symfony/blob/a9bb1182151d81054800aa4fa2680d92a5928a6a/src/Symfony/Component/Lock/Store/RedisStore.php#L70)

**Comment by Simperfit** [comment]
cc @jderusse

**Comment by jderusse** [comment]
Thanks @slince for the reproduct case and the clear and deep investigation!

I'm working on a fix.
