### ISSUE TITLE
[WebProfilerBundle] Allow customizing "maxTries" option in debug toolbar

### ISSUE THREAD

**Issue by czechmarcin** [symfony/symfony#31422]
**Symfony version(s) affected**: 3.4.x

**Description**  
The hardcoded `maxTries` option disables the profiler toolbar with longer requests. It should be configurable.
ref:https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig#L124

**How to reproduce**  
Load a page which embeds another controller in the template. The embedded controller should be slow and respond after ~10-15 seconds. After loading the page, `maxTries` limit will disable the web profiler.

**Comment by Simperfit** [comment]
@czechmarcin do you want to work on this ?

**Comment by fabpot** [comment]
We decided to not make this configurable when we implemented it. I still think that we should not expose this. I don't have the issue/PR right now as I'm on my phone, but it should be easy to find it.

**Comment by czechmarcin** [comment]
https://github.com/symfony/symfony/pull/15670 - this conversation makes it clear that it won't be implemented. If I have the regarded solution, I will create the PR.
I'm closing this issue. Thank you for the feedback
