### ISSUE TITLE
Incorrect signature of Symfony\Component\Serializer\Normalizer\DataUriNormalizer::__construct()

### ISSUE THREAD

**Issue by Perf** [symfony/symfony#31433]
**Symfony version(s) affected**: 4.3@dev

**Description**  
According to https://github.com/symfony/symfony/blob/master/UPGRADE-4.3.md#httpfoundation class `Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface` is deprecated, but class `Symfony\Component\Serializer\Normalizer\DataUriNormalizer` is still using it. Having it in `__construct()` signature, while `Symfony\Component\Mime\MimeTypes` is passed into.

```php
    public function __construct(MimeTypeGuesserInterface $mimeTypeGuesser = null)
    {
        if (null === $mimeTypeGuesser && class_exists('Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser')) {
            $mimeTypeGuesser = MimeTypeGuesser::getInstance();
        }

        $this->mimeTypeGuesser = $mimeTypeGuesser;
    }
```

**How to reproduce**  
1. execute
```bash
bin/console
```
2. get an Exception
> In DataUriNormalizer.php line 39:
> Argument 1 passed to Symfony\Component\Serializer\Normalizer\DataUriNormalizer::__construct() must be an instance of Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface or null, instance of Symfony\Component\Mime\MimeTypes given

**Possible Solution**  
Refactor of `Symfony\Component\Serializer\Normalizer\DataUriNormalizer` should help to resolve this issue.

**Comment by xabbuh** [comment]
Can you explain you ended up there? In the `4.3` branch the constructor looks different: https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Serializer/Normalizer/DataUriNormalizer.php#L41-L57

**Comment by Perf** [comment]
Hi @xabbuh 
I were on SF 4.2 and upgraded to 4.3, after that this issue appeared.
In `composer.json` I have `: "^4.3"` after all symfony packages, and also have:
```json
"minimum-stability": "dev",
  "extra": {
    "symfony": {
      "id": "***",
      "allow-contrib": "true",
      "require": "^4.3"
    }
}
```

**Comment by xabbuh** [comment]
Can you show the full stack trace of the error that you get please as well as the output of `composer show`?

**Comment by Perf** [comment]
It's seems i found why it's happening

```
$ composer why symfony/serializer
api-platform/core        dev-master  requires  symfony/serializer (^4.2)
```
so I have `symfony/serializer  v4.2.8` instead of v4.3
