### ISSUE TITLE
[HttpFoundation] UrlHelper: non-existent service "url_helper".

### ISSUE THREAD

**Issue by bambucha4** [symfony/symfony#31450]
**Symfony version(s) affected**: 4.3.0-BETA1

**Description**  
Before update from 4.2.8 to 4.3.0-BETA1 I changed a parameter in arguments of service from HttpFoundation to url_helper but get:

**The service "App\Service\SomeService" has a dependency on a non-existent service "url_helper".**

**How to reproduce**  
before 4.3.0-BETA1:
```
    App\Service\SomeService:
        public: true
        arguments: ['@twig.extension.httpfoundation']
```
after to update 4.3.0-BETA1:
```
    App\Service\SomeService:
        public: true
        arguments: ['@url_helper']
```

The alias was created in PR in [https://github.com/vudaltsov/symfony/blob/388d8f548c6bc78890021e4c9b5f9fadc8759b3a/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml#L66](https://github.com/vudaltsov/symfony/blob/388d8f548c6bc78890021e4c9b5f9fadc8759b3a/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml#L66)

**Comment by xabbuh** [comment]
I cannot reproduce this issue. Can you create a small example application that allows to reproduce it?

**Comment by bambucha4** [comment]
I will try reproduce tomorrow, today I'm busy.

**Comment by bambucha4** [comment]
Weird issue. I create new project with the same composer.json and It's worked. IDK what going on, so I close.
