### ISSUE TITLE
500 error in Web Debug Toolbar

### ISSUE THREAD

**Issue by j4nr6n** [symfony/symfony#31476]
**Symfony version(s) affected**: 4.3.0-BETA1, 4.4.0-dev

**Description**  
When running the latest dev code, a 500 error is thrown in `/_wdt/{identifier}`.

![Screenshot from 2019-05-10 15-51-07](https://user-images.githubusercontent.com/3661151/57553807-a9c57480-733d-11e9-82cc-baa2cef036d4.png)

**How to reproduce**  
* `composer create-project symfony/website-skeleton`
* add `"minimum-stability": "beta"` to `composer.json`
* change `extra.symfony.require` to `^4.2` in `composer.json`
* `composer update`

See reproducer app here: https://github.com/j4nr6n/reproducerApp

**Possible Solution**  

**Additional context**  
![Screenshot from 2019-05-10 16-04-03](https://user-images.githubusercontent.com/3661151/57553778-94504a80-733d-11e9-8d81-be65ff0d0851.png)

**Comment by Simperfit** [comment]
I can reproduce this and confirm the issue:
It seems that the generated twig is properly calling the object to get the errors, but this object has been serialized (I didn't found why):

```
  dump($context["collector"] );
        echo ((twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, (isset($context["collector"]) || array_key_exists("collector", $context) ? $context["collector"] : (function () { throw new RuntimeError('Variable "collector" does not exist.', 31, $this->source); })()), "data", [], "any", false, false, false, 31), "nb_errors", [], "any", false, false, false, 31)) ? ("error") : (""));
        echo " ";

```

it dumps: 

```
6c09583e532550a4b8998db060b8e5ee1657e79eb109632ad1215ffad785babe.php on line 142:
FormDataCollector^ {#883 ▼
  -dataExtractor: null
  -dataByForm: null
  -dataByView: null
  -formsByView: null
  #data: "O:39:"Symfony\Component\VarDumper\Cloner\Data":6:{s:45:"\x00Symfony\Component\VarDumper\Cloner\Data\x00data";a:2:{i:0;a:1:{i:0;a:1:{i:1;i:1;}}i:1;a:3:{s:5:"form ▶"
  -cloner: null
}
```

The collector in the controller have non serialized data.

**Comment by Simperfit** [comment]
I found the rootcase and I'm going to send a PR !

**Comment by Simperfit** [comment]
Tested with the reproducer, the linked bugfix is fixing the bug properly ;)
