### ISSUE TITLE
Does an cache:warmup have expiration time?

### ISSUE THREAD

**Issue by aweelex** [symfony/symfony#31489]
I faced with an issue. After changes deployment and executing `cache:clear`, page loading speed is 0.2ms. But after couple hours it takes 1.5s, to recreate cache. So the question is "Does an `cache:warmup` have expiration time? Is it bug or a feature?"

Ver: 4.3

Thanks!

**Comment by aweelex** [comment]
*vendor/symfony/config/ConfigCache.php* - answers this question.

`public function isFresh()
    {
        if (!$this->debug && is_file($this->getPath())) {
            return true;
        }

        return parent::isFresh();
    }`

Dev cache is validated by some checker, but for prod environment cache is always fresh. Thats why dev cache is recreated sometimes and prod is not.

Am I right?

**Comment by xabbuh** [comment]
Do you experience the increased time in the `prod` or in the `dev` environment?

**Comment by aweelex** [comment]
No, it seems like both environmets have this behavior. I logged this data:

> 2019-05-14 11:58 dev   3807 ms.
2019-05-14 11:58 dev   122 ms.
2019-05-14 12:12 dev   1140 ms.
2019-05-14 12:17 dev   119 ms.
2019-05-14 12:36 dev   4091 ms.
2019-05-14 12:36 dev   161 ms.
2019-05-14 12:36 dev   125 ms.
2019-05-14 12:37 prod  5035 ms.
2019-05-14 12:37 prod  83 ms.
2019-05-14 12:38 prod  77 ms.
2019-05-14 12:41 prod  80 ms.
2019-05-14 12:42 prod  77 ms.
2019-05-14 12:44 prod  81 ms.
2019-05-14 12:55 prod  78 ms.
2019-05-14 13:08 prod  3431 ms.
2019-05-14 13:09 prod  70 ms.

**Comment by aweelex** [comment]
Ok, now I know, that freezes are not affiliated with cache. But they are still appearing.

**Comment by xabbuh** [comment]
I am afraid you will need to debug this a bit or provide us with some reproducible scenario. Otherwise we will probably not be able to help you.

**Comment by aweelex** [comment]
It's ok. I think it's a problem with PHP. I'll try to find out for solution, and give some recommendations.

**Comment by Simperfit** [comment]
@aweelex did you find something ?

**Comment by aweelex** [comment]
Yep. The reason wasn't related to Symfony. Sometimes server was overloaded and needed couple seconds to run FCGI. You can solve it temporary. by setting bigger `FcgidProcessLifeTime`, but it's just a crutch until you get better server optimisation.
