### ISSUE TITLE
RFC: Remove the main `composer.json` file in Symfony 5

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#31484]
As of Symfony 4, using individual components is recommended. When using Flex, this is the only way to work with Symfony. Using individual components helps with auto-configuration and avoids the need to install all the components you don't need.

One crazy idea would be to remove the possibility to require `symfony/symfony` as of Symfony 5. I don't see any valid use case anymore.

WDYT?

**Comment by Nek-** [comment]
This will break on many old applications while upgrades were always smooth until now (on composer side I mean).

I still have a bunch of them in production. If the cost of this global composer is not too high (you don't mention it anywhere in this post). Keeping it sounds good to me.

**Comment by mickaelandrieu** [comment]
@Nek- , you could already replace "symfony/symfony" by the current composer.json file content of this repository [right now](https://github.com/symfony/symfony/blob/master/composer.json#L18).

It sounds healthier than requiring a meta-package, even more for old applications in maintenance, don't you think?

**Comment by soukicz** [comment]
Does that mean that if someone installs symfony/symfony based on some old stackoverflow answer, he will get old version without realising it?

**Comment by linaori** [comment]
@soukicz depends on the version you'd define. If they define `5.0`, it would not install because that version does not exist. If they try to install the latest stable of `symfony/symfony`, they'd end up having `4.4.x`.

**Comment by nicolas-grekas** [comment]
Hum I think we need to keep it: flex relies on symfony/symfony for its extra.symfony.require checks...

**Comment by lyrixx** [comment]
> One crazy idea would be to remove the possibility to require `symfony/symfony` as of Symfony 5. I don't see any valid use case anymore.

@fabpot: As @Nek- said, there is still some applications with `symfony/symfony: 4.*`. I'm working on such application, and everything is fine. If we do this, This will lead to extra work for end user. Not so much, but still. But I understand for new application this should be discouraged. So I'm +/-0 on this one :)

> @Nek-:, you could already replace "symfony/symfony" by the current composer.json file content of this repository [right now](https://github.com/symfony/symfony/blob/master/composer.json#L18).

@mickaelandrieu: I think you linked the wrong repository. It should be replaced by something similar to the content of the [website-skeleton](https://github.com/symfony/website-skeleton)

**Comment by jvasseur** [comment]
I'm :+1: for removing it but if we want to reduce the BC breakage we could instead replace it with a meta-package that require the individual packages (with `self.version`). This would allow to keep the package while removing the need to maintain requirements in the root `composer.json` and make `symfony/symfony` work with flex (not sure if it is a good thing).

**Comment by docteurklein** [comment]
@Nek- @lyrixx are you sure it would break existing applications? If so, in which scenario?
My guess is that existing applications would still work as soon as they constraint to a version `< 5.0`.

**Comment by Pierstoval** [comment]
What about forcing the autoload of the `Fullstack` class on app startup and display a deprecation in `5.0` to be sure and remove it in `6.0` to be sure old apps upgrading only `symfony/symfony` are warned soon enough, as well as documentations and old tutorials?

**Comment by fabpot** [comment]
I don't get the BC break. Applications using `symfony/symfony` won't break. There is no need to do anything or add a constraint `< 5.0` as there won't be any 5.0 version for `symfony/symfony`. Part of migrating to Symfony 4 is to switch to using Flex, which does not support `symfony/symfony` already. So, new apps (creating as of 4.0) won't have any issues. For apps created before, again, they should migrate to Flex.

**Comment by X-Coder264** [comment]
> Part of migrating to Symfony 4 is to switch to using Flex, which does not support `symfony/symfony` already.

@fabpot I don't agree with this. When SF 4 was released (along with Flex) it was always "advertised" that Flex is completely optional which is in direct contradiction with your statement.

In order to do this I think we should first "deprecate" `symfony/symfony` for SF 5, clearly communicate that Flex is going to be the only way to use the framework and then remove the possibility to require `symfony/symfony` as of Symfony 6. Removing it for SF 5 all of a sudden and especially since we are so close to its release will just block a lot of people from upgrading to SF 5 (because switching the entire application folder structure to Flex isn't a small task, especially for bigger apps).

**Comment by respinoza** [comment]
@fabpot I think removing it will also indirectly fix an issue when using private packagist. When a package depends on symfony/symfony it will add mirroring to packages at current version because of the composer replace but later it won't update those dependencies unless you remove from your packagist symfony/symfony (triggering a forced update) or add packages manually.
I know this is more a composer issue but still, it will save some headaches for devs.

**Comment by fabpot** [comment]
@X-Coder264 It will not block anyone. You will need to require individual packages in your `composer.json` file instead of requiring `symfony/symfony` (which is about copy/pasting the current `require` section if the `composer.json` of `symfony/symfony`). There is no need to change the directory structure at all if you don't want to do it.

**Comment by lyrixx** [comment]
@fabpot not the require, but the replace section 😁

**Comment by yceruto** [comment]
This will also remove the possibility of "creating *easily* demo apps from complex PRs" when there are many components involved (sometimes it is necessary to try big changes).

For contributions, I use the [`link`](https://github.com/symfony/symfony/blob/master/link) script; which is a good approach from the DX point of view. But for installable applications it does not work.

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/yceruto/symfony"
        }
    ],
    "require": {
        "symfony/symfony": "dev-new-feature-with-many-components-involved as 4.4.0"
    },
}
```

What would be the recommended alternative to achieve it?
 * could https://github.com/splitsh/lite be one?
 * can symfony/flex do something to improve this task?

**Comment by fabpot** [comment]
Why not use `symfony/website-skeleton`?

**Comment by yceruto** [comment]
> Why not use symfony/website-skeleton?

Well, the thing is, I would not like to submit the changes for each individual cloned repo, it would be a very boring task.

**Comment by lyrixx** [comment]
@yceruto I guess you missed https://github.com/symfony/symfony/blob/master/link :)

**Comment by yceruto** [comment]
@lyrixx I guess not :) https://github.com/symfony/symfony/issues/31484#issuecomment-491848825, it wouldn't work with just two steps: `git clone demo` and `composer install`.

You'll need also clone my yceruto/symfony repo and then execute the `link` script.

**Comment by mickaelandrieu** [comment]
> (Your are two to make this error. The move might not be so easy :troll:)

Isn't both `require` and `replace` sections? I don't think that relying on the skeleton is a good idea as the skeleton doesn't contain all the components, bundles and bridges available in the meta package: so we could lose some required dependencies during the migration.

I can be wrong, of course: I've never made the move for now :smile: (but this is something we will do when we will migrate PrestaShop to Symfony 4).

**Comment by yceruto** [comment]
To be clear, I'm talking about two scenarios in https://github.com/symfony/symfony/issues/31484#issuecomment-491848825

 1. I'm developing a new PR, it is okay, I use the `link` script to try it in real apps.
 2. Exposing a demo app for your PR, I use `repositories` section approach because it is easy for other: clone + install, done. If we remove the possibility to require `symfony/symfony` this task will need two steps more: clone the author repo/branch + run the `link` script.

That's what I want to say, but it's probably not a big deal and these last two steps can be automated in the `scripts` section.

**Comment by derrabus** [comment]
If we removed the main composer.json file, will that make contributing to Symfony harder? I still use that file for installing dependencies when working on the repository.

**Comment by ro0NL** [comment]
i think the question is if symfony/symfony should be de-published from packagist ... AFAIK the current CI process also heavily relies on the root composer.json.

**Comment by xelan** [comment]
De-publishing symfony/symfony would break (re-)installs of any existing symfony 2.x/3.x app which is built upon the full-stack framework. IMHO one variant would be to provide symfony/symfony up to v4 and only individual components/bundles/... after that (as proposed in this issue), or to keep symfony/symfony for simplicity also for v5, although discouraged for general usage.

**Comment by lyrixx** [comment]
Note: We never said we will de-publish symfony/symfony. It's all about **not** tagging symfony/symfony v5.0.0

**Comment by TomasVotruba** [comment]
I'm happy the title is missleading (took few comments to figure out). `composer.json` will stay, only the `symfony/symfony` on packagist will not continue to be published with new versions.

If that's the case, it's common monorepo pattern no to publish monorepo itself, so :+1:

**Comment by fabpot** [comment]
First step here: symfony/flex#499

**Comment by tsantos84** [comment]
Maybe I didn't understand the entire strategy, but the idea is to keep `symfony/symfony` as central repo?

**Comment by teohhanhui** [comment]
You can still choose to not use Flex even when there's no `symfony/symfony` `5.0`. It just means you need to `require` the packages separately, and carry on as before.

**Comment by fabpot** [comment]
To keep things simple, we will 'just' not tag `symfony/symfony` anymore as of 5.0 (the main `composer/json` is at the heart of our tests, and nobody wants to spend time rewriting this).

**Comment by gmponos** [comment]
> To keep things simple, we will 'just' not tag symfony/symfony anymore as of 5.0

So is this true? I still see tags on the main repo.. and on packagist...

**Comment by Pierstoval** [comment]
Will probably be true as of 6.0 then 

Gives more time to people to migrate their dependencies I guess 😄
