### ISSUE TITLE
[Messenger] Symfony Serializer: Cannot create instance of BusNameStamp

### ISSUE THREAD

**Issue by raresserban** [symfony/symfony#31490]
**Symfony version(s) affected**: 4.3-beta1

**Description**  
The exact error that I receive from the console:
Cannot create an instance of Symfony\Component\Messenger\Stamp\BusNameStamp from serialized data because its constructor requires parameter "busName" to be present.

To me this error makes no sens, I have published a message using a SF 4.3 application and tried to consume it in another SF 4.3 application. For some reason the deserialization of the BusNameStamp fails in Symfony\Component\Messenger\Transport\Serialization\Serializer class in the `decodeStamps` function, which really makes no sense since the JSON that is used for the deserialization of this stamp is this: `[{"busName":"messenger.bus.default"}]`

**How to reproduce**
Publish a message from a SF 4.3 application using the `messenger.transport.symfony_serializer` service as the messenger default serializer and then try to consume it.

**Comment by weaverryan** [comment]
Hmm. Weren’t you having success serializing and deserializing messages for other issues you created? Indeed, I agree that this is odd. I thought that because the constructor arg is “$busName” and the key is “busName” in JSON, that it would know to construct it using that key. Many other stamps follow this convention and I believe are serializing and deserializing fine. I remember even testing the full process using the Symfony serializer a few days ago.

Is there any other special setup you have?

**Comment by raresserban** [comment]
No special setup, the same that I used for the other issues.
I have a publisher app which is written in SF 4.1, 4.2 and 4.3 to see if old versions of the Messenger are compatible with a second consumer app written in SF 4.3.
I tested before beta1 and the publishing and consuming worked fine with all 3 SF versions (aside from other issues I posted but that were solved in the mean time).
Now the publishing does not work from the SF 4.3 app (were the BusNameStmap was added).

**Comment by chalasr** [comment]
The issue should be gone after running `composer require symfony/property-access`. 
The reason is that `ObjectNormalizer` is required for normalizing the stamp object, and that normalizer is only wired when the property-access component is installed. 

We can probably improve DX by detecting that it is not available before trying to serialize the stamp, and throw a meaningful exception.

**Comment by weaverryan** [comment]
Ah! Wait, so if property access isn’t available, object normalizer isn’t available? What normalizer is used then? Or is it just that his normalizer is less powerful?

Anyways, if I understand correctly, pretty much none of the core stamps are serializable with the Symfony serializer unless property access is available as many have constructor arguments without setters, which I think is what works only with property access.

I think we should throw an exception in the Symfony serializer for messenger that property access is required if not installed.

**Comment by chalasr** [comment]
> Wait, so if property access isn’t available, object normalizer isn’t available

Yes!
https://github.com/symfony/symfony/blob/24af4c5c929e7ccc196e8e83132b768fbdc9ad7f/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L39-L41

> What normalizer is used then?
Here is the full list of default norsmalizers injected in the `serializer` service when you don't have `property-access` installed:
```
"Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer"
"Symfony\Component\Serializer\Normalizer\DateTimeNormalizer"
"Symfony\Component\Serializer\Normalizer\ConstraintViolationListNormalizer"
"Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer"
"Symfony\Component\Serializer\Normalizer\DataUriNormalizer"
"Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer"
"Symfony\Component\Serializer\Normalizer\DateTimeNormalizer"
"Symfony\Component\Serializer\Normalizer\ConstraintViolationListNormalizer"
"Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer"
"Symfony\Component\Serializer\Normalizer\DataUriNormalizer"
```

Which obviously don't support normalization for any other type than the one they are prefixed by.
So yes, it should definitely throw. 

But actually, the error I get is not exactly the same as the one described here (which I can't manage to reproduce). Mine is:

 > Could not normalize object of type Symfony\Component\Messenger\Stamp\BusNameStamp, no supporting normalizer found.

So we still need @raresserban to confirm that my solution also fixes his issue.

**Comment by raresserban** [comment]
Hello, I have the property-access component, so I don't think the problem is related to yours. Here is the stack trace:

`In AbstractNormalizer.php line 510:
                                                                                 
  [Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException]  
  Cannot create an instance of Symfony\Component\Messenger\Stamp\BusNameStamp    
   from serialized data because its constructor requires parameter "busName"     
  to be present.                                                                 
                                                                                 

Exception trace:
 () at /app/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:510
 Symfony\Component\Serializer\Normalizer\AbstractNormalizer->instantiateObject() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:231
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->instantiateObject() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:332
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize() at /app/vendor/symfony/serializer/Serializer.php:191
 Symfony\Component\Serializer\Serializer->denormalize() at /app/vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php:60
 Symfony\Component\Serializer\Normalizer\ArrayDenormalizer->denormalize() at /app/vendor/symfony/serializer/Serializer.php:191
 Symfony\Component\Serializer\Serializer->denormalize() at /app/vendor/symfony/serializer/Serializer.php:142
 Symfony\Component\Serializer\Serializer->deserialize() at /app/vendor/symfony/messenger/Transport/Serialization/Serializer.php:118
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decodeStamps() at /app/vendor/symfony/messenger/Transport/Serialization/Serializer.php:73
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decode() at /app/vendor/symfony/messenger/Transport/AmqpExt/AmqpReceiver.php:66
 Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceiver->getEnvelope() at /app/vendor/symfony/messenger/Transport/AmqpExt/AmqpReceiver.php:47
 Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceiver->get() at /app/vendor/symfony/messenger/Worker.php:92
 Symfony\Component\Messenger\Worker->run() at /app/vendor/symfony/messenger/Worker/StopWhenRestartSignalIsReceived.php:54
 Symfony\Component\Messenger\Worker\StopWhenRestartSignalIsReceived->run() at /app/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:224
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:930
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/console:38`

I also updated the apps to 4.3-beta2, but still the same problem...

**Comment by raresserban** [comment]
I think I found the problem, it is because the name of the constructor argument is not correct. The `$key` parameter that the name converter provides on line 479 from the AbstractNormalizer class is `bus_name` not `busName`, hence the error... Might be because the publishing app uses ApiPlatform, which uses camelCase, but the subscribing app does not use ApiPlatform, hence the other deserialization format...

And if publishing from the same ApiPlatform app with SF 4.2, it works because the constructor variable on line 468 of AbstractNormalizer is null.

Not sure how to fix it, or if something should be changed on the publishing or on the consuming side...

**Comment by raresserban** [comment]
Finally found the issue, it was because of a configuration option set in one of our internal bundles. There we set the serializer name converter to be the CamelCaseToSnakeCaseNameConverter for some weird reason, and that bundle was only used in the consuming application, so the publishing app was not affected by it.

Also publishing from SF 4.2 was not affected since there the BusNameStamp is not serialized in the envelope...

So finally fixed this by setting this in the framework config:
```
serializer:
        name_converter: false
```

Closing this ticket now.

**Comment by barell** [comment]
I know it is old issue but I encountered the same error message and thought it is worth to put my comment here for the future.

In my case I have installed Symfony Serializer compontent as `composer require symfony/serializer` but uninstalling and installing as `composer require symfony/serializer-pack` solved the issue.

**Comment by faizanakram99** [comment]
@chalasr This is still a problem,

The issue is `TransportNamesStamp` has `$transports` as ctor parameter but a getter with name `getTransportNames` which is serialized to `transportNames`.

When denormalizing it again, it is unable to map `transportNames` key to `transports` ctor parameter

The fix would be to rename the ctor parameter to `$transportNames` (to make serialization + deserialization interoperable)

**Comment by faizanakram99** [comment]
I'll try create another issue/PR with a reproducer. The fix is simple.
