### ISSUE TITLE
[VarDumper] BC break in 4.2.4 in Stub serialization

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony#31491]
**Symfony version(s) affected**: 4.2.4

**Description**  
This commit has introduced a BC break: https://github.com/symfony/var-dumper/commit/ee0ee773a4855fec46f92a10fafa9ff4e660a118

The way Stub objects are serialized has changed. This has introduced a BC break when the app running the server:dump command is not the same app emiting dump messages. We use a "centralized" dump server, which received dump messages from differents Symfony app (of different Symfony versions). updating a single app to 4.2.4 require now that all the apps are also updated to 4.2.4.

**How to reproduce**  
Create an app with Symfony 4.2.3 which emit a dump message.
Create an app with Symfony 4.2.4 or higher which runs a servr:dump command.
--> Objects are displayed as `null`

**Comment by nicolas-grekas** [comment]
Unfortunately, there are no ways around, as we want to escape from `Serializable` which causes other bad issues. See https://wiki.php.net/rfc/custom_object_serialization for details about these issues.

**Comment by Vinorcola** [comment]
Yes I understand. Is there no way to keep:

```php
public function __wakeup()
    {
        if (isset($this->serialized) {
            list($this->class, $this->position, $this->cut, $this->type, $this->value, $this->handle, $this->refCount, $this->attr) = $this->serialized;
            unset($this->serialized);
        }
    }
```

By the way, shouldn't it have been better to specify a language agnostic message format for communicating between Dumper and ServeDump command?  
For example, JSON rather than PHP serialization. That way, we could have sent dumps from e.g. a Node app to a Symfony Server Dump... Or we could have consumed dump message from Symfony App in a Node service...

**Comment by nicolas-grekas** [comment]
The error is triggered before we have any opportunity to hook and do custom things, so no sorry.
About the protocol: because defining one is extremely hard, so this could not be the first step...
