### ISSUE TITLE
UniqueEntity overwrites ManyToOne entity set to null when EAGER loaded

### ISSUE THREAD

**Issue by c0ntax** [symfony/symfony#31500]
**Symfony version(s) affected**: 3.4.27

**Description**  
For non-mandatory form elements that are ManyToOne (this may also be a bug for OneToOne and ManyToMany), if you try to set them to null, and the containing entity is using the UniqueEntity Validator, if you have set that relationship to EAGER load, the original value (before setting it to null) will overwrite the null value, thus making it impossible to set the element to null.

**How to reproduce**  
Check out the example codebase and run: https://github.com/c0ntax/symfony_unique_entity_bug

Setup instructions:
```bash
git clone https://github.com/c0ntax/symfony_unique_entity_bug.git
cd symfony_unique_entity_bug
composer install
./bin/console doctrine:database:create
./bin/console doctrine:migrations:migrate --no-interaction
./bin/console doctrine:fixtures:load --no-interaction
./bin/console server:run
```

Now, visit http://localhost:8000/grumpy/elephant and attempt to set the Tiny Puppy field to 'Nothing'. (Nothing is the placeholder and empty_data has been set to null so that selecting this will attempt to set the tinyPuppy property to null).

What happens is that it is set to null as part of the handleForm() method, but then it gets to this [line of code](https://github.com/symfony/doctrine-bridge/blob/master/Validator/Constraints/UniqueEntityValidator.php#L139). If you have set the property to EAGER loading (e.g. [here](https://github.com/c0ntax/symfony_unique_entity_bug/blob/master/src/Entity/GrumpyElephant.php#L28)) then the null value set will now be stamped over with the original value. If you set the fetch to LAZY, it will work as expected.

**Possible Solution**  
The only work around is to set the the fetch for all nullable relationships to LAZY, which isn't ideal.

**Additional context**  
None

**Comment by xabbuh** [comment]
This is a known limitation that we cannot workaround. You either need to not use eager loading here or provide a custom repository method that works around it (see #23961 for more information). Thus I am going to close here. Thank you for understanding.

**Comment by c0ntax** [comment]
I'm assuming that the obvious solution of turning the query into a SELECT COUNT (*) has been tried and rejected?

**Comment by xabbuh** [comment]
@c0ntax If you want to give it a try to solve it that way, I will happily review such a PR.

**Comment by c0ntax** [comment]
I might just give it a quick go. Code-wise, two possible solutions present themselves
1. Hydrate to an array instead of an object
2. Use a count instead of a query

Annoyingly neither will 'just work' as there isn't a default Doctrine Repository query to do this. Would it be too 'awkward' for an end user to be provided a Trait to add to their Repository class that provides a different query? It just doesn't feel all that 'clean'...

**Comment by c0ntax** [comment]
So, the only half way decent fix I could come up for this results in a breaking change and therefore I doubt is acceptable.Basically, you remove the `repositoryMethod` and build a COUNT query inside the Validator. E.g.

```php
        $queryBuilder = $em->createQueryBuilder()
            ->select(sprintf('COUNT(e.%s)', $identifierId));
        if (null !== $constraint->entityClass) {
            /* Retrieve repository from given entity name.
             * We ensure the retrieved repository can handle the entity
             * by checking the entity is the same, or subclass of the supported entity.
             */
            $repository = $em->getRepository($constraint->entityClass);
            $supportedClass = $repository->getClassName();

            if (!$entity instanceof $supportedClass) {
                throw new ConstraintDefinitionException(sprintf('The "%s" entity repository does not support the "%s" entity. The entity should be an instance of or extend "%s".', $constraint->entityClass, $class->getName(), $supportedClass));
            }
            $queryBuilder->from($supportedClass, 'e');
        } else {
            $queryBuilder->from(get_class($entity), 'e');
        }

        $queryBuilder->where(sprintf('e.%s != :identifier', $identifierId))
            ->setParameter('identifier', $this->getPropertyAccessor()->getValue($entity, $identifierId));
        foreach ($criteria as $field => $value) {
            $queryBuilder->andWhere(sprintf('e.%s = :%s_value', $field, $field))
                ->setParameter(sprintf('%s_value', $field), $value);
        }

        $result = (int) $queryBuilder->getQuery()->getSingleScalarResult();

        if ($result < 1) {
            return;
        }
```

I'm assuming that this kind of breaking change is a bit of a no-no, right?

**Comment by c0ntax** [comment]
Actually, what you can do with this change is set the default value of `repositoryMethod` to null and if it's null fork off into this method for finding the uniqueness of an entity, which would then allow all other users that currently us the repositoryMethod to have their code still work. I think I'll do that and submit a pull for it.

(Because currently, the solution for the project I'm working on is to just copy and rename the validator and apply my own changes, which will obviously drift out over time.
