### ISSUE TITLE
create:user  then doctrine:migrate SQL syntax problems with MariaDB

### ISSUE THREAD

**Issue by juandevteloro** [symfony/symfony#31508]
Symfony version 4.2.8
**Description**  
I am using mariaDB as a database,when i use php bin/console make:user it creates the user entity and the repository , then i create the migration, but when i run
`php bin/console doctrine:migrations:migrate` 
i get
```
  An exception occurred while executing 'CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, compa
  ny_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(180) NOT NULL, last_nam
  e VARCHAR(180) NOT NULL, age INT NOT NULL, gender VARCHAR(8) NOT NULL, phone VARCHAR(10) NOT NU
  LL, provider VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, title VARCHAR(32) DEFAULT NULL,
   assigned_to VARCHAR(180) DEFAULT NULL, created_by VARCHAR(180) DEFAULT NULL, date_created DATE
  TIME DEFAULT NULL, modified_by VARCHAR(180) DEFAULT NULL, date_modified DATETIME DEFAULT NULL,
  roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email)
  , INDEX IDX_8D93D649979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLA
  TE utf8mb4_unicode_ci ENGINE = InnoDB':

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; c
  heck the manual that corresponds to your MariaDB server version for the right syntax to use nea
  r 'JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C7' at line 1
```

**How to reproduce**  
I have already added:
`server-version: 'mariadb-10.0.38' `

**Possible Solution**  
I think the issue is that mariadb 10.0.38 does not allow for JSON-type fields, i am not sure what the proper type of the field should be in this case but this should be the ORM annotation added  for the `$roles` attribute

**Comment by andrew-demb** [comment]
It's https://github.com/symfony/maker-bundle/ issue.

**Comment by Rom1deTroyes** [comment]
The JSON Data Type commes with [MariaDB 10.2.7](https://mariadb.com/kb/en/library/json-data-type/)...
Upgrading to a newer MariaDB server solved the issue for me.

In the User Entity, the `roles[]` has a json type, may be something to tweak as a workaround ? 
```
/**
* @ORM\Column(type="json")
*/
private $roles= [];
```

**Comment by juandevteloro** [comment]
@Rom1deTroyes I am going to try to change the type to text and use json_decode/json_encode in the getter/setter as a workaround.

**Comment by xabbuh** [comment]
In any case, this needs to be resolved either in the MakerBundle by choosing a different type or in Doctrine by generating different queries for the migration. Both projects have their own repositories. So I am closing here as there is nothing we can do here. Thank you for understanding.

**Comment by adryyy10** [comment]
I've changed the type of "roles" in User entity from json to string and then change it in my migration from JSON NOT NULL to VARCHAR(180) NOT NULL too, and it worked

**Comment by stof** [comment]
DBAL should already adapt itself to the right version of MariaDB. So make sure that the configured `serverVersion` in your project is the right one (be careful that if you specify a server version inside your url, it wins over the specific field).
