### ISSUE TITLE
[symfony/filesystem] Cannot copy() to php://

### ISSUE THREAD

**Issue by zearg** [symfony/symfony#31501]
**Symfony version(s) affected**: 4.2.5

**Description**  
With PHP we can send content of a file to a PHP I/O stream.
For example like this : 
 ```php
copy('myfile.xxx', 'php://output');
```
But it doesn't works with 
 ```php
$filesystem = new Symfony\Component\Filesystem\Filesystem();
$filesystem('myfile.xxx', 'php://output');
```

**How to reproduce**  
In a Controller : 
```php
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Filesystem\Filesystem;
[...]
$response = new StreamedResponse();
$response->setCallback(function () {
    $filesystem = new Filesystem();
    $filesystem->copy('https://symfony.com/images/logos/sf-positive.svg', 'php://output');
});
$response->send();
[...]
```
Then you get the IOException : `Failed to create "php:": mkdir(): Permission denied.`

**Possible Solution**  
Add the ability to use copy() method in **Filesystem** component with **php://xxxx** as second argument
For all PHP I/O streams : https://www.php.net/manual/fr/wrappers.php.php (they all starts with _php://_)

**Additional context**  
I've this problem with a callback on a StreamedResponse. Maybe it does not work anymore in a basic action.

**Comment by engmohammedyehia** [comment]
I couldn't produce this on 4.2.8 

I just copied your code in a controller's action and instead I got an IOException thrown 

> Failed to copy "https://symfony.com/images/logos/sf-positive.svg" to "php://output".

**Comment by zearg** [comment]
Yes i have IOException too, but the message is :
`Failed to create "php:": mkdir(): Permission denied.`

I tried again in symfony 4.2.8 and there is still same exception and message

**Comment by fabpot** [comment]
The Filesystem component only works when using filesystem. So `php://` is not supported.

**Comment by zearg** [comment]
Thanks
I'll continue to use copy() of PHP for that.
