### ISSUE TITLE
[Dotenv] $_ENV superglobal is incomplete

### ISSUE THREAD

**Issue by stucki** [symfony/symfony#31504]
**Symfony version(s) affected**: 4.3, 4.2, ..., 3.3

**Description**  
If `variables_order` does not contain `E` then the `$_ENV` superglobal is not set when the parser starts. The result is that any value that is updated in `$_SERVER` will also be set in `$_ENV`, but all other (untouched) values exist in `$_SERVER` but they will be missing in `$_ENV`.

Note: This is a reworked description of the problem that was first mentioned in #24332 (see also PR #24333).

**How to reproduce**  
* Make sure that `variables_order` does not contain `E`.
* Export `VAR1=1` to PHP (e.g. using Apache `SetEnv`) and verify that it is set in`$_SERVER`.
* Verify that it is not set in `$_ENV` (which is correct according to `variables_order`).
* Add `VAR1=2` to your `.env` file
* Add `VAR2=2` to your `.env` file
* `VAR1` will not be set in `$_ENV` but it's set in `$_SERVER` (with a value of `1`).
* `VAR2` will be set as expected in both superglobals (with a value of `2`).

**Possible Solution**  
Check if `variables_order` contains `E`, otherwise set all variables in `$_ENV`.

**Comment by nicolas-grekas** [comment]
We shouldn't try to trick the config. I don't think there is anything wrong here on our side. That's a PHP  issue.
