### ISSUE TITLE
[Maker] generate migration with many databases / entityManager fails

### ISSUE THREAD

**Issue by lerminou** [symfony/symfony#31517]
**Symfony version(s) affected**: 4.2.5

**Description**  
make:migrations argument to select the db and entity are not filled to the doctrine:migrations:diff command , always the default db is used.

**How to reproduce**  
Have a doctrine config with  2 dbal / orm in the same project.
The first one is the default and the second one is another manager as described in the official doc here: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html
I use yaml config.

When using the make:migration command, even if I fill the argument --em=XXX, the default one is always evaluated, the migration is always performed against the default DB.

If I launch the doctrine:migrations:diff command with the same argument em=XXX, the migration is correct.

**Possible Solution**  
Change the argvInput in the Symfony\Bundle\MakerBundle\Maker\makeMigration or something similar to fill maker argument to doctrine arguments

**Additional context**

**Comment by crayner** [comment]
Building a test container for this.  Will let you know.

**Comment by Simperfit** [comment]
@lerminou this is more linked to the maker bundle, than the symfony framework. cc @weaverryan

**Comment by weaverryan** [comment]
Sounds legitimate. Can you re-open the issue over here? https://github.com/symfony/maker-bundle

Thanks!
