### ISSUE TITLE
[SF4][Form][Prototype] Replace prototype variable

### ISSUE THREAD

**Issue by Pizgu** [symfony/symfony#31512]
Hi,

If I create a dynamic form based on which I have 2 Listener, which remove or add some fields, and in Twig I check whether an element from the form exists works ok, I need the prototype property to dynamically add parameters.

Unfortunately, it adds the form as it was generated, this is the correct operation, but how to edit this prototype? Is there a simple way to change its value?
Unfortunately, I have to remove some values from the form from this property.

Can you indicate the correct path as a support? If necessary, I will show all the codes that use this and I will drop the screenshot.

Thanks in advance!

Best regards,
Gregory

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
