### ISSUE TITLE
[Validator][DoctrineBridge] Automatic data validation doesn't ignore GeneratedValue

### ISSUE THREAD

**Issue by GaryPEGEOT** [symfony/symfony#31523]
**Symfony version(s) affected**: 4.3.0-beta1

**Description**  
Automatic validation doesn't ignore `@ORM\GeneratedValue` annotation, and add the `NotNull` constraint on auto-generated values.

**How to reproduce**  
Using the beta version of Symfony + API pack,
Create an entity like so:
```php
class Vehicle
{
    /**
     * @var string
     *
     * @ORM\Column(name="id", type="int")
     * @ORM\Id
     * @ORM\GeneratedValue()
     */
    private $id;

    /**
     * Vehicle designation.
     *
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=60)
     *
     * @Assert\NotBlank()
     * @Assert\Length(min="2", max="60")
     */
    private $name;

    /**
     * Max fuel tank capacity.
     *
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $fuelCapacity;
}
```
Try to create an entity using the doc (`/doc` by default). You should see an error message:
```
1) App\Tests\Functional\API\VehicleResourceTest::testCreate
Expected 2XX response, got 400 with body: {"@context":"\/contexts\/ConstraintViolationList","@type":"ConstraintViolationList","hydra:title":"An error occurred","hydra:description":"id: This value should not be null.\ncreatedAt: This value should not be null.","violations":[{"propertyPath":"id","message":"This value should not be null."},{"propertyPath":"createdAt","message":"This value should not be null."}]}
Failed asserting that false is true.
```
In my case the `createdAt` is handled by a lifecycle event, so it triggers an error too. I don't know if there is a way to disable automatic validation for specific fields.

**Possible Solution**  
Don't add validation on properties with `@ORM\GeneratedValue` annotation, maybe create an "AutoValidationIgnore" annotation as well to ignore specific classes / properties.

**Comment by BoShurik** [comment]
Should be:
```php
/**
 * @var string|null
 *
 * @ORM\Column(name="id", type="int")
 * @ORM\Id
 * @ORM\GeneratedValue()
 */
private $id;
```
because generated value will be set only after flush.

Following code will also produce an exception (if you have `string` return value for `getId` method)
```php
$vehicle = new Vehicle();
$vehicle->getId();
```

**Comment by GaryPEGEOT** [comment]
Was indeed linked to a wrong PHPDoc, thansk @BoShurik
