### ISSUE TITLE
Is it possible to dynamically generate choices in form collections?

### ISSUE THREAD

**Issue by maarten-shop4** [symfony/symfony#31521]
**Is it possible to dynamically generate choices in form collections?**

The situation:

- ItemEntity

- PropertyEntity

These entities can be added and edited through the **Item Form**. 

When you add a type to the **Item Entity** the status on the property entities will be loaded through an ajax request.
Each **type** of item has different status choices that are provided by a service. 

This service is injected into the **PropertyFormType**  to provide the available choices.

Everything works fine, except submitting the form keeps returning errors. It appears the choices are not loaded.

On the **Property Entity** the provided **status** options are empty.
I know the service provides the right data (an array with all the status choices for a type of item). 

Debugging this tells me that during the **POST_SUBMIT** event, the data is not set.
`dump($event->getForm()->getData());` shows me that the type property of the *Item Entity* is still null, even though it has been set in the form.

Is it possible to read submitted data from the parent Form object to determine which choices have been loaded through ajax to fix the ConstraintViolation errors?

**Symfony docs:**

- [Dynamic Generation for Submitted Forms][1]

- [Form Events][2]

- [Collection Form Type][3]

**Form Errors:**
```
Caused by:
ConstraintViolation {#2314 ▶}
TransformationFailedException {#1587 ▼
  #message: "Unable to reverse value for property path "status": The choice "test" does not exist or is not unique"
  #code: 0
  #file: "/home/vagrant/shop4raad2/vendor/symfony/form/Form.php"
  #line: 1150
  trace: {...}
   …1
}
TransformationFailedException {#1598 ▼
  #message: "The choice "test" does not exist or is not unique"
  #code: 0
  #file: "/home/vagrant/shop4raad2/vendor/symfony/form/Extension/Core/DataTransformer/ChoiceToValueTransformer.php"
  #line: 48
  trace: {...}
}
```

**Item Form:**
```
namespace App\Form;

use App\Entity\ItemEntity;
use App\Form\Type\PropertyFormType;
use App\Service\Provider\ItemTypeProvider;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Item Form
 */
class ItemForm extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
    {
		$item = $builder->getData();
	
		$builder->add("type", ChoiceType::class, [
            "choices"            => ItemEntity::getTypeChoices(),
            "disabled"           => null !== $dataImportMapping->getId(),
            "required"           => null === $dataImportMapping->getId(),
			/* ... */
		]);
	
		$builder->add("properties", CollectionType::class, [
            "entry_type"         => PropertyFormType::class,
            "entry_options"      => [PropertyFormType::OPTION_ITEM => $item],
            "prototype"          => true,
            "allow_add"          => true,
            "allow_delete"       => true,
            /* ... */
        ]);
	}
	
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ItemEntity::class,
        ]);
    }
}
```

**Property Form Type:**
```
namespace App\Form\Type;

use App\Entity\PropertyEntity;
use App\Service\Provider\PropertyStatusProvider;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Property Form Type
 */
class PropertyFormType extends AbstractType
{
	const OPTION_ITEM = "data_item";
	
	private $statusProvider;
	
	public function __construct(PropertyStatusProvider $statusProvider)
	{
		$this->statusProvider = $statusProvider;
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
    {
		$item = $options[self::OPTION_ITEM];
		
		$formModifier = function(FormInterface $form, ItemEntity $item) {
			
			// load choices from service - this service returns an array of available choices by 
			$statusChoices = $this->statusProvider->getAvailableChoices($item->getType());
			
			$form->add("status", ChoiceType::class, [
				"choices"  => $statusChoices,
                "required" => true,
				/* ... */
			]);
		};

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier) {
                /* @var PropertyItem $property */
                $property = $event->getData();

                $formModifier($event->getForm(), $property->getItem());
            }
        );
		
        $builder->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                
                // It's important here to fetch $event->getForm()->getData(), as
                // $event->getData() will get you the client data (that is, the ID)
                /* @var PropertyItem $property */
                $property = $event->getForm()->getData();

                // since we've added the listener to the child, we'll have to pass on
                // the parent to the callback functions
                $formModifier($event->getForm()->getParent(), $property->getItem());
            }
        );
	}
	
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => PropertyEntity::class,
        ]);
    }
}


```

Choices are loaded dynamically into the properties select via ajax using the select2 library

**item-form.js:**

```
	$("select[id^='item_form_properties_'][id$='_status']").select2({
        ajax: {
            type: "GET",
            url: Routing.generate("async-item-properties"),
            dataType: "json",
            data: function(params) {
                var query = {
                    term: params.term,
                };

                var mapping_type = $("select#item_form_type").val();

                if (null !== mapping_type && "" !== mapping_type) {
                    query['type'] = mapping_type;
                }

                return query;
            },
            processResults: function(data) {

                var properties = [];

                $.each(data, function(key, item) {
                    properties.push({
                        id: item.id,
                        text: item.value,
                    });
                });

                return {
                    results: properties
                };
            },
        },
		/* ... */
    });
```

**Item Entity:**
```
/**
 * @ORM\Entity(/* ... */)
 * @ORM\Tabele(/* ... */)
 */
class ItemEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(name = "item_id", type = "integer")
	 */
	private $id;
	
    /**
     * @ORM\Column(type = "string", length = 64)
	 */
	private $type;
	
	/**
     * @ORM\OneToMany(targetEntity = "PropertyEntity", mappedBy = "item", cascade={"persist", "remove"})
	 */
	private $properties;
	
	/* ... */
	
	/**
     * @param PropertyEntity $property
     *
     * @return self
     */
    public function addProperty(PropertyEntity $property)
    {
        $property->setItem($this);

        $this->properties[] = $property;

        return $this;
    }

    /**
     * @param PropertyEntity $property
     */
    public function removeProperty(PropertyEntity $property)
    {
        $this->properties->removeElement($property);
    }
}
```

**Property Entity:**
```
/**
 * @ORM\Entity(/* ... */)
 * @ORM\Tabele(/* ... */)
 */
class PropertyEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(name = "property_id", type = "integer")
	 */
	private $id;
	
	/**
     * @ORM\ManyToOne(targetEntity = "ItemEntity", inversedBy = "properties")
     * @ORM\JoinColumn(name = "item_id", referencedColumnName = "item_id")
	 */
	private $item;

    /**
     * @ORM\Column(type = "string", length = 64)
	 */
	private $status;
	
	/* ... */
}
```

The templates are very straight forward and not relevant to this problem so I'm omitting them from this question.

  [1]: https://symfony.com/doc/current/form/dynamic_form_modification.html#form-events-submitted-data
  [2]: https://symfony.com/doc/current/form/events.html
  [3]: https://symfony.com/doc/current/reference/forms/types/collection.html

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by maarten-shop4** [comment]
> I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

How do you know this behavior is not caused by a bug? If this issue tracker is not meant for support requests, why is it an option on creating an issue?

If this is not possible at the moment, the specification of this problem might even lead to a feature request.  if it is possible to configure my problem, this could also lead to improvements in documentation. I hope you can reconsider opening this issue. It might be worth the while for other developers.

**Comment by xabbuh** [comment]
Maybe I misunderstood what you were asking for. If you think there is a bug, can you please explain what exactly you tried, what happened and what you did expect instead? If this is a feature request, can you please clarify what exactly you would like to see implemented (how to use it, what would be the effect and so on)?

**Comment by xabbuh** [comment]
@maarten-shop4 Do you have some more information for us?

**Comment by maarten-shop4** [comment]
I'll try to explain it differently.

[The guide about dynamic form modification](https://symfony.com/doc/current/form/dynamic_form_modification.html#form-events-submitted-data) tells me how to work with variable choices. you can see how I applied this in the **PropertyFormType** class provided above.

This all works great, except when it's inside a "sub" form. The **PropertyFormType** class is used inside a Collection in it's parent **ItemForm** because an **Item** entity can have multiple **Property** entities as configured with a OneToMany association.

The **status** Choices that should be selected inside the **PropertyFormType** are dependent of the selected **type** in the **ItemForm**

What I want to achieve is checking which `Item->type` is selected when the choices for the `Property->status`. To do this I need to get the data from the parent form. That's what I'm doing with the $formModifier closure inside the POST_SUBMIT event.

It seems to be impossible to read the selected **type** of the parent **ItemForm**. So the question is, is this at all possible? If it is.. can you tell me what I'm going wrong inside the provided code samples? I'd like to add this solution to the existing documentation.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to play with it?

**Comment by maarten-shop4** [comment]
I can do that, give me some time

**Comment by xabbuh** [comment]
@maarten-shop4 Do you have any news for us?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
