### ISSUE TITLE
[VarDumper/Console] Option for CliDumper to accept OutputInterface as it's output

### ISSUE THREAD

**Issue by Sarke** [symfony/symfony#31520]
Currently I can implement this functionality like this:

```php
use Symfony\Component\{Console, VarDumper};

$output = new Console\Output\ConsoleOutput;
$section = $output->section();

$cloner = new VarDumper\Cloner\VarCloner();
$dumper = new VarDumper\Dumper\CliDumper();
$dumper->setColors(true);
$dumper->setOutput(function($line, $depth) use ($section) {
	$section->write($line);
});

$dumper->dump($cloner->cloneVar($m->attributes));
```

However, I think it would be a good addition if the `CliDumper` could also accept a `Console\Output\OutputInterface` as one of the options for it's `setOutput()` or constructor.  It currently accepts `callable|resource|string|null`, of which I use the callable above.

So what I am after is for it to be able to accept `Console\Output\ConsoleOutput` or `Console\Output\ConsoleSectionOutput`, both of which extend `Console\Output\StreamOutput`, which in turn is very close to what the `resource|string` options are for the `VarDumper` output. I think they could be made inter-operable.

**Comment by Sarke** [comment]
I would submit a pull request, but I am unsure of how I would implement between two otherwise independent Symfony packages.

**Comment by nicolas-grekas** [comment]
Hi, can you please describe the use cases that are not achieved by current ways?

**Comment by Sarke** [comment]
Well, to me it seem that one Symfony component that accepts an stream output would be able to accept a different Symfony component that is called `StreamOutput`.

To me it seems that the `OutputInterface` from the Console package can have much wider uses, for example logging and var dumping.

**Comment by Simperfit** [comment]
Do we want to implement this ?

**Comment by nicolas-grekas** [comment]
If there is no real world use case, I don't think so, especially because it's pretty reasonable to do it already.
