### ISSUE TITLE
Primary key always returns 0

### ISSUE THREAD

**Issue by GreenLeewayDesignCastle** [symfony/symfony#31529]
**Symfony version(s) affected**: 4.2.8

**Description**  
When I retrieve the primary key of my customer entity it always returns 0. In my customer entity i do have an id property and userid property. On the table I also have an Id column and an user_id column. On the mysql table the primary key is the user_id column. Also on the entity I added the @Id annotation on the userid property.

Customer.php
`<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Table(name="`users`", uniqueConstraints={@ORM\UniqueConstraint(name="userid", columns={"userid"})}, indexes={@ORM\Index(name="phone", columns={"phone"}), @ORM\Index(name="id_check", columns={"id_check"}), @ORM\Index(name="firstname", columns={"firstname"}), @ORM\Index(name="email", columns={"email"}), @ORM\Index(name="name", columns={"lastname"})})
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 */
class Customer
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned"=true})
     */
    private $id;

    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(name="userid", type="string", length=28, nullable=false)
     */
    private $userid;

    /**
     * @var string|null
     *
     * @ORM\Column(name="phone", type="string", length=255, nullable=true)
     */
    private $phone = '';

    /**
     * @var string|null
     *
     * @ORM\Column(name="phone_country", type="string", length=255, nullable=true)
     */
    private $phoneCountry;

    /**
     * @var string|null
     *
     * @ORM\Column(name="firstname", type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="lastname", type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @var string|null
     *
     * @ORM\Column(name="birthday", type="string", length=255, nullable=true)
     */
    private $birthday;

    /**
     * @var string|null
     *
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @var string|null
     *
     * @ORM\Column(name="iban", type="string", length=255, nullable=true)
     */
    private $iban = '';

    /**
     * @var string|null
     *
     * @ORM\Column(name="bank_owner", type="string", length=255, nullable=true)
     */
    private $bankOwner = '';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="bank_verified", type="boolean", nullable=true)
     */
    private $bankVerified = '0';

    /**
     * @var int|null
     *
     * @ORM\Column(name="bank_time", type="integer", nullable=true)
     */
    private $bankTime = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="kyc_verified", type="boolean", nullable=true)
     */
    private $kycVerified = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="level", type="smallint", nullable=true)
     */
    private $level = '0';

    /**
     * @var int|null
     *
     * @ORM\Column(name="created", type="integer", nullable=true)
     */
    private $created;

    /**
     * @var int|null
     *
     * @ORM\Column(name="updated", type="integer", nullable=true)
     */
    private $updated;

    /**
     * @var int|null
     *
     * @ORM\Column(name="online", type="integer", nullable=true)
     */
    private $online = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="blocked", type="boolean", nullable=true)
     */
    private $blocked = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="otp", type="boolean", nullable=true)
     */
    private $otp = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="searchable", type="boolean", nullable=true, options={"default"="1"})
     */
    private $searchable = '1';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="newsletter", type="boolean", nullable=true, options={"default"="1"})
     */
    private $newsletter = '1';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="notifcation_email", type="boolean", nullable=true, options={"default"="1"})
     */
    private $notifcationEmail = '1';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="notification_push", type="boolean", nullable=true, options={"default"="1"})
     */
    private $notificationPush = '1';

    /**
     * @var string|null
     *
     * @ORM\Column(name="ip", type="string", length=255, nullable=true)
     */
    private $ip;

    /**
     * @var string|null
     *
     * @ORM\Column(name="profile", type="string", length=36, nullable=true)
     */
    private $profile = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="idcard", type="string", length=36, nullable=true)
     */
    private $idcard = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="id_front", type="string", length=36, nullable=true)
     */
    private $idFront = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="id_back", type="string", length=36, nullable=true)
     */
    private $idBack = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="id_type", type="boolean", nullable=true)
     */
    private $idType = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="id_check", type="boolean", nullable=true)
     */
    private $idCheck = '0';

    /**
     * @var int|null
     *
     * @ORM\Column(name="id_count", type="integer", nullable=true)
     */
    private $idCount = '0';

    /**
     * @var int|null
     *
     * @ORM\Column(name="referral", type="integer", nullable=true)
     */
    private $referral = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="lang", type="boolean", nullable=true)
     */
    private $lang = '0';

    /**
     * @var int|null
     *
     * @ORM\Column(name="language", type="integer", nullable=true)
     */
    private $language = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="intranet", type="boolean", nullable=true, options={"default"="1"})
     */
    private $intranet = '1';

    /**
     * @var string|null
     *
     * @ORM\Column(name="kyc_id", type="string", length=36, nullable=true)
     */
    private $kycId = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="verify_id", type="string", length=36, nullable=true)
     */
    private $verifyId = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="document_id", type="string", length=36, nullable=true)
     */
    private $documentId = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="screen_id", type="string", length=36, nullable=true)
     */
    private $screenId = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="risk", type="boolean", nullable=true)
     */
    private $risk = '0';

    /**
     * @var bool|null
     *
     * @ORM\Column(name="trusted", type="boolean", nullable=true)
     */
    private $trusted = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="percentage_wallet", type="decimal", precision=10, scale=2, nullable=true, options={"default"="0.00"})
     */
    private $percentageWallet = '0.00';

    /** @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="customer") */
    private $orders;

    /**
     * @var CustomerData
     * @ORM\OneToOne(targetEntity="App\Entity\CustomerData")
     * @JoinColumn(name="userid", referencedColumnName="id")
     */
    private $customerData;

    /** @ORM\OneToMany(targetEntity="App\Entity\Job", mappedBy="customer") */
    private $jobs;

    /**
     * Customer constructor.
     */
    public function __construct() {
        $this->orders = new ArrayCollection();
        $this->jobs = new ArrayCollection();
    }

    public function getUserid()
    {
        return $this->userid;
    }

    public function setUserid(string $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhoneCountry(): ?string
    {
        return $this->phoneCountry;
    }

    public function setPhoneCountry(?string $phoneCountry): self
    {
        $this->phoneCountry = $phoneCountry;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(?string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function getBankOwner(): ?string
    {
        return $this->bankOwner;
    }

    public function setBankOwner(?string $bankOwner): self
    {
        $this->bankOwner = $bankOwner;

        return $this;
    }

    public function getBankVerified(): ?bool
    {
        return $this->bankVerified;
    }

    public function setBankVerified(?bool $bankVerified): self
    {
        $this->bankVerified = $bankVerified;

        return $this;
    }

    public function getBankTime(): ?int
    {
        return $this->bankTime;
    }

    public function setBankTime(?int $bankTime): self
    {
        $this->bankTime = $bankTime;

        return $this;
    }

    public function getKycVerified(): ?bool
    {
        return $this->kycVerified;
    }

    public function setKycVerified(?bool $kycVerified): self
    {
        $this->kycVerified = $kycVerified;

        return $this;
    }

    public function getLevel():int
    {
        return $this->level;
    }

    public function setLevel(?int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getCreated(): ?int
    {
        return $this->created;
    }

    public function setCreated(?int $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?int
    {
        return $this->updated;
    }

    public function setUpdated(?int $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getOnline(): ?int
    {
        return $this->online;
    }

    public function setOnline(?int $online): self
    {
        $this->online = $online;

        return $this;
    }

    public function getBlocked(): ?bool
    {
        return $this->blocked;
    }

    public function setBlocked(?bool $blocked): self
    {
        $this->blocked = $blocked;

        return $this;
    }

    public function getOtp(): ?bool
    {
        return $this->otp;
    }

    public function setOtp(?bool $otp): self
    {
        $this->otp = $otp;

        return $this;
    }

    public function getSearchable(): ?bool
    {
        return $this->searchable;
    }

    public function setSearchable(?bool $searchable): self
    {
        $this->searchable = $searchable;

        return $this;
    }

    public function getNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(?bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }

    public function getNotifcationEmail(): ?bool
    {
        return $this->notifcationEmail;
    }

    public function setNotifcationEmail(?bool $notifcationEmail): self
    {
        $this->notifcationEmail = $notifcationEmail;

        return $this;
    }

    public function getNotificationPush(): ?bool
    {
        return $this->notificationPush;
    }

    public function setNotificationPush(?bool $notificationPush): self
    {
        $this->notificationPush = $notificationPush;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getProfile(): ?string
    {
        return $this->profile;
    }

    public function setProfile(?string $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getIdcard(): ?string
    {
        return $this->idcard;
    }

    public function setIdcard(?string $idcard): self
    {
        $this->idcard = $idcard;

        return $this;
    }

    public function getIdFront(): ?string
    {
        return $this->idFront;
    }

    public function setIdFront(?string $idFront): self
    {
        $this->idFront = $idFront;

        return $this;
    }

    public function getIdBack(): ?string
    {
        return $this->idBack;
    }

    public function setIdBack(?string $idBack): self
    {
        $this->idBack = $idBack;

        return $this;
    }

    public function getIdType(): ?bool
    {
        return $this->idType;
    }

    public function setIdType(?bool $idType): self
    {
        $this->idType = $idType;

        return $this;
    }

    public function getIdCheck(): ?bool
    {
        return $this->idCheck;
    }

    public function setIdCheck(?bool $idCheck): self
    {
        $this->idCheck = $idCheck;

        return $this;
    }

    public function getIdCount(): ?int
    {
        return $this->idCount;
    }

    public function setIdCount(?int $idCount): self
    {
        $this->idCount = $idCount;

        return $this;
    }

    public function getReferral(): ?int
    {
        return $this->referral;
    }

    public function setReferral(?int $referral): self
    {
        $this->referral = $referral;

        return $this;
    }

    public function getLang(): ?bool
    {
        return $this->lang;
    }

    public function setLang(?bool $lang): self
    {
        $this->lang = $lang;

        return $this;
    }

    public function getLanguage(): ?int
    {
        return $this->language;
    }

    public function setLanguage(?int $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getIntranet(): ?bool
    {
        return $this->intranet;
    }

    public function setIntranet(?bool $intranet): self
    {
        $this->intranet = $intranet;

        return $this;
    }

    public function getKycId(): ?string
    {
        return $this->kycId;
    }

    public function setKycId(?string $kycId): self
    {
        $this->kycId = $kycId;

        return $this;
    }

    public function getVerifyId(): ?string
    {
        return $this->verifyId;
    }

    public function setVerifyId(?string $verifyId): self
    {
        $this->verifyId = $verifyId;

        return $this;
    }

    public function getDocumentId(): ?string
    {
        return $this->documentId;
    }

    public function setDocumentId(?string $documentId): self
    {
        $this->documentId = $documentId;

        return $this;
    }

    public function getScreenId(): ?string
    {
        return $this->screenId;
    }

    public function setScreenId(?string $screenId): self
    {
        $this->screenId = $screenId;

        return $this;
    }

    public function getRisk(): ?bool
    {
        return $this->risk;
    }

    public function setRisk(?bool $risk): self
    {
        $this->risk = $risk;

        return $this;
    }

    public function getTrusted(): ?bool
    {
        return $this->trusted;
    }

    public function setTrusted(?bool $trusted): self
    {
        $this->trusted = $trusted;

        return $this;
    }

    public function getPercentageWallet()
    {
        return $this->percentageWallet;
    }

    public function setPercentageWallet($percentageWallet): self
    {
        $this->percentageWallet = $percentageWallet;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function getBuyOrders()
    {
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->gt('type', Order::ORDER_TYPE_BUY))
            ->andWhere(Criteria::expr()->gt('status', 2))
        ;

        return $this->orders->matching($criteria);
    }

    public function getSellOrders()
    {
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->gt('type', Order::ORDER_TYPE_TRANSFER_SELL))
            ->andWhere(Criteria::expr()->gt('status', 2))
        ;

        return $this->orders->matching($criteria);
    }

    public function getCustomerData(): CustomerData { return $this->customerData; }

    public function getFullName()
    {
        return [$this->firstname, $this->lastname];
    }

    public function getFullPhoneNumber()
    {
        return [$this->phoneCountry, $this->phone];
    }
}
`

**How to reproduce**  
Create a Customer entity, add an id property and userid property. Set @Id annotation to the userId column. Try to retrieve the id by using a getter on the entity.

**Comment by GreenLeewayDesignCastle** [comment]
@xabbuh  @stof Have you experienced this, do you see anything weird on my entity  ?

**Comment by crayner** [comment]
Perhaps https://medium.com/@galopintitouan/auto-increment-is-the-devil-using-uuids-in-symfony-and-doctrine-71763721b9a9 could be of help to you to work out if your id's are integers or strings.  It appears to me that the userid is NEVER set in the information that you have given here, so an answer of '0' may be expected. (You never use the id, so not required.)

**Comment by Simperfit** [comment]
@GreenLeewayDesignCastle could you please reformat the issues properly ?

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
