### ISSUE TITLE
[RFC][Validator][Security] Add Role validation or Voter on property

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#31538]
**Description**  
I would more feedback about the fact of Add a **"Role" Validator.**
The goal is to check if a User can or not edit a property.
I know that it's more related to Security than the Validation of a value but for API Builder It's an helpful tool to validate action on ressource and the Validator help us to do this quickly.
We can validate, Role or Action like Voter.
I wrote an article with a working exemple https://medium.com/@smaine.milianni/user-permission-and-symfony-validator-12b2c31d7817 

**Example**  

```php
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Role(role="ROLE_PUBLISHER", action="EDIT")
     */
    private $title;

**Comment by jvasseur** [comment]
How would this work ? The validator component doesn't have access to the previous value of the field to check if it was modified.

**Comment by ismail1432** [comment]
I tougth that the ˋproperty` should not be submitted. It’s a strange use case for traditional form but valid for api

**Comment by jvasseur** [comment]
But if your property is already set before the submitting, you can't differentiate that case with the case of someone setting it.

**Comment by xabbuh** [comment]
I tend to agree with @jvasseur and I don't see being implemented in the Symfony core. That's why I am closing here.
