### ISSUE TITLE
[Dotenv] Fatal error for valid environment variable syntax.

### ISSUE THREAD

**Issue by dspiegel** [symfony/symfony#31530]
**Symfony version(s) affected**: 4.2.8

**Description**  
Dotenv returns error for valid environment variable syntax.

**How to reproduce**  

1. Add variable to .env like `FOOBAR="${FOOBAR:=production}"`
2. Run `./bin/console cache:clear`

**Error**:
`Script cache:clear --no-warmup --env %PUBLIC_DIR% returned with error code 255`
`Fatal error: Uncaught Symfony\Component\Dotenv\Exception\FormatException: Unclosed braces on variable expansion in "/export/home/dave/Projects/iprd/4.2/iprd-tools/.env"
...${SYMFONY_ENV:=dev}
`

**Bash test of .env file works as expected**
$ unset FOOBAR
$ . .env
$ echo $FOOBAR 
production

**Comment by juuuuuu** [comment]
Interesting.
Can you tell why do you need to use this kind of assignment? (instead of simply doing `FOOBAR=production`)

**Comment by juuuuuu** [comment]
ping @dspiegel

**Comment by javiereguiluz** [comment]
We're closing because we don't have more feedback about this. Feel free to reopen with more information. Thanks.

**Comment by xabbuh** [comment]
Could be solved after #31546, right?

**Comment by juuuuuu** [comment]
I'm not sure. I think that #31545 is solving default value **used on expansion time** (`:-`) not in a **parameter assignment** way (`:=`).
Updating the regex to manage this case could solve this issue.

**Comment by xabbuh** [comment]
see #32980

**Comment by nicolas-grekas** [comment]
`FOOBAR="${FOOBAR:-production}"` is supported now (and is a better way to express what was intented)
