### ISSUE TITLE
[SensioFrameworkExtraBundle] @IsGranted with array type subject

### ISSUE THREAD

**Issue by va5ja** [symfony/symfony#31534]
**Description**  
Inside a Controller, it's possible to do something like this:
```
    /**
     * @Route("/test/{site_id}/{project_id}", name="app_test")
     */
    public function test($site_id, $project_id)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', ['site_id' => $site_id, 'project_id' => $project_id]);
    }
```
**Feature Request**  
As far as I know, using @IsGranted annotation it is currently not possible to use an array type subject. At least I couldn't find any documentation about it. So it is not possible to do something like this:
```
    /**
     * @Route("/test/{site_id}/{project_id}", name="app_test")
     * @IsGranted("POST_SHOW", subject={"a"="site_id", "b"="project_id"})
     */
```
It would be useful to allow the same functionality using annotations.

**Comment by chalasr** [comment]
This is for https://github.com/sensiolabs/SensioFrameworkExtraBundle. 
Please consider reopening there. Thanks

**Comment by va5ja** [comment]
Sorry and thanks.
