### ISSUE TITLE
Atomic deployment error with shared cache

### ISSUE THREAD

**Issue by florianajir** [symfony/symfony#31558]
**Symfony version(s) affected**: 4.2.7

**Description**  
Unable to reuse var/cache directory if it's a symbolic link shared between releases 

**How to reproduce**  

Create a symbolic link for var directory that will be used for all current releases

**Possible Solution**  

We use the CacheKernel as explained here https://symfony.com/doc/current/http_cache.html

**Additional context**  
Error thrown on cache:clear `PHP Fatal error: Cannot declare interface Symfony\Component\HttpKernel\HttpKernelInterface`

I have to visit the homepage to get the error 500 and then execute this command server-side: `rm -f var/cache/prod/srcApp_KernelProdContainer*`

After that all is ok but if I don't visit a webpage getting the 500 error, just removing cache files is not working..

**Comment by dmaicher** [comment]
Why would you share the cache between different releases? This is super error prone. I mean there can be drastic changes between two releases so it cannot be guaranteed that a shared cache will work.

Also to allow "zero downtime" deployments actually every release should have its own cache. So you can warm-up the cache of a new release before actually serving any traffic on it.

**Comment by nicolas-grekas** [comment]
If you figure our why and can submit a PR we'd be happy to review, but otherwise I agree with @dmaicher: this should not be supported as making the promise this strategy would work is impossible from a maintenance pov I fear.
