### ISSUE TITLE
Am I able to specify route dynamicaly by it's name in security.yaml?

### ISSUE THREAD

**Issue by shumichenko** [symfony/symfony#31555]
In my `security.yaml` I want to refer to `login` route name which is declared in `routes.yaml` :
```
login:
    path: /anyurlyouwant
    controller: App\Controller\SecurityController::login
```
Because I want to specify route URL dynamicaly. Am I able to do this?

**Comment by nicolas-grekas** [comment]
See #31485 and #31362 (this could be considered a duplicate.)

**Comment by xabbuh** [comment]
Are we talking about the path of a firewall or is this a question about how to reference the controller that renders the login form?

**Comment by shumichenko** [comment]
`access_control:
        - { path: ^/login, allow_if: 'is_anonymous()'}
`

I mean how to refer to `path` indirectly, because if I have:

 `login:
    path: /login
`

in my routes.yaml and if I will change path to smth different it will cause an 404 error since there's no path, which security.yaml refers to

**Comment by shumichenko** [comment]
For example, I can inject Router component into my Authenticator and then do this:

`public function getLoginUrl() : string<br/>
    {
        return $this->router->generate('login');
    }
`

Then I dont need to edit this method everytime I change login route, because it refers to route name.
It would be cool if I can do the same thing in my `security,yaml`, but with its own way.

**Comment by shumichenko** [comment]
No, I'm not
