### ISSUE TITLE
Split contracts into separate interface packages

### ISSUE THREAD

**Issue by samdark** [symfony/symfony#31567]
**Description**  

The proposal it to split [symfony/contracts](https://github.com/symfony/contracts) into multiple contract repositories:

- contracts-cache
- contracts-event-dispatcher
- contracts-http-client
- contracts-service
- contracts-translation

I have read https://github.com/symfony/contracts#why-isnt-this-package-split-into-several-packages and still do not think that it is correct for the case when I am not using Symfony as a whole but want to use one of its components.

For example, I want to use https://github.com/symfony/translation/ only. I am using PSR-16 for cache, PSR-14 event dispatcher and PSR-18 HTTP client. With the current package IDE would suggest wrong `CacheInterface` and would "spam" me with other interfaces that I am not using confusing project developers.

More formally speaking, it violates all the package cohesion principles: REP, CRP, and CCP.

**Comment by nicolas-grekas** [comment]
No objections on my side, we can do it now with v1.1.

**Comment by nicolas-grekas** [comment]
Here you are: https://github.com/symfony/symfony/pull/31571
One slight different: I named packages as `symfony/*-contracts`

**Comment by samdark** [comment]
Any naming is fine. Will check the pull request.

**Comment by samdark** [comment]
Are you going to apply it to packages as well? Any timeframe for that?

**Comment by nicolas-grekas** [comment]
> Are you going to apply it to packages as well? Any timeframe for that?

Once the split is merged we can apply to components. Can be done before 4.3.0.

**Comment by thewilkybarkid** [comment]
Is there any possibility of separate version numbers? I imagine these individually will rarely need new versions, so a version bump is currently likely to just be the addition of an unrelated package (ie existing ones don’t have any changes so the new version is redundant).

**Comment by nicolas-grekas** [comment]
@thewilkybarkid I don't think so, because the release processes are complex enough. The downside is very limited compared to the overhead this would incur on maintainers.

**Comment by samdark** [comment]
How about separate packages without subsplit?

**Comment by nicolas-grekas** [comment]
we're going to check if we can instruct the splitter to not tag twice the same commit
that would fix the issue
(not using the splitter is no-go: we really want to automate as much as possible to be able to scale our processes)

**Comment by fabpot** [comment]
I've finished the work: created the repositories for each contract, split each repository, tagged version 1.1.1, and published the packages on Packagist. Should be ready to use :)
