### ISSUE TITLE
[intl] Get all language names with the country language

### ISSUE THREAD

**Issue by lsv** [symfony/symfony#31562]
**Description**  

Lets say you have a language selector, now you are on the english site, so all the languages are in english fx
- Danish
- French
- Russian

Now you select Russian, now the dropdown will look something like this

- английский
- датский
- французский

Instead it would be lovely to have a dropdown that always look something like this

- Dansk
- Français
- Pусский

**Example**  

```
$locales = Intl::getLocaleBundle()->getLocaleNamesNotTranslated();
dump($locales);
```

```
....
"ru" => "русский",
"da" => "dansk",
"fr" => "français",
....
```

It would be exactly like doing this

\Locale::setDefault('fr');
$locales = Intl::getLocaleBundle()->getLocaleNames();
$french = $locales['fr'];

\Locale::setDefault('ru');
$locales = Intl::getLocaleBundle()->getLocaleNames();
$russian = $locales['ru'];

\Locale::setDefault('da');
$locales = Intl::getLocaleBundle()->getLocaleNames();
$danish = $locales['da'];

**Comment by ro0NL** [comment]
I tend to believe the current API allows to built such a list already.

Using forms it's simply as

```php
$form = $this->createForm(LanguageType::class, null, [
    'choice_label' => function ($lng) {
        return Intl::getLanguageBundle()->getLanguageName($lng, null, $lng);
    },
]);
```

**Comment by javiereguiluz** [comment]
I'm not sure this feature is common enough to provide it as a feature. Moreover, when the alternative is only a couple of lines of code. I'm 👎 about the proposal unless someone comes with some compelling reasons.

**Comment by javiereguiluz** [comment]
Since I published the above comment I've changed my mind around this. The feature proposed is not that uncommon. In fact, even the Symfony Demo app now displays each language into its own language:

![image](https://user-images.githubusercontent.com/73419/60709908-cdf29b80-9f11-11e9-83c8-8ee939c0de3a.png)

So, I've created #32388 to implement this feature.
