### ISSUE TITLE
[symfony/cache] Possibility to save item without getting it first

### ISSUE THREAD

**Issue by ilyachase** [symfony/symfony#31575]
**Description**  
It seems that there's no way to save item using for example `MemcachedAdapter` without getting it. There is no way to create `CacheItem` and set key for it. I understand that In PSR cache interface there is no such method as `setKey()` (only `getKey()`), but imagine situation when you want to just save one Mil items in cache. Using 'symfony/cache' wrapper you will do 2 Mil operations instead of 1 Mil.

**Possible solution**
Allow `CacheItem`'s constructor to set key.

**Example**  
```php
$cacheClient = MemcachedAdapter::createConnection(['memcached://localhost:11211']);
$cache = new MemcachedAdapter($cacheClient);

$item = (new \Symfony\Component\Cache\CacheItem('foo'))->set('bar');
$cache->save($item);
```

**Comment by jvasseur** [comment]
The cache PSR explicitly says that users must not create `CacheItem` instances themselves and that `save` could refuse to work with an item that wasn't retrieved with `getItem`.

I think this use case is supposed to work by making the `getItem` method lazy by making the value retrieved from the backend only when either `isHit` or `get` is called. This means doing `$pool->save($pool->getItem('key')->set('bar'));` will only do one call to the backend.

**Comment by nicolas-grekas** [comment]
It's true, there's no generic way to do so in the PSR, which means you must rely on a specific implementation to do so. The strategy @jvasseur describes would work but it not required by the PSR, so it would still be implementation specific. e.g. Symfony Cache items are not lazy, which means this would work with it.

For Symfony Cache, the way to achieve this is to create items using the `NullAdapter`, and then save them using the MemcachedAdapter one.
