### ISSUE TITLE
[symfony/cache] `add` method for MemcachedAdapter

### ISSUE THREAD

**Issue by ilyachase** [symfony/symfony#31574]
**Description**  
In Memcached there is `add` operation: https://www.php.net/manual/ru/memcached.add.php
And it's very useful since it's atomic and safe from race condition operations. It can be used as a locks mechanism, for example.
But we don't have this method in MemcachedAdapter for some reason. I understand that there is no such method in PSR cache interface but still since it's MemcachedAdapter why can't we add it here? And then if it's okay for some applications to rely on MemcachedAdapter class and not on PSR interface, `add` method will be available for them.

**Example**  
```php
$cacheClient = MemcachedAdapter::createConnection(['memcached://localhost:11211']);
$cache = new MemcachedAdapter($cacheClient);

$item = $cache->getItem('foo');
$item->set('bar');
$check = $cache->add($add);
if (!$check) {
  echo 'Item was already added!';
}
```

**Comment by nicolas-grekas** [comment]
If you're OK to code against not abstract interfaces, then you should use the connection object directly as it already provides everything.
I don't think it makes sense to provide `add` on the cache component.

**Comment by ilyachase** [comment]
I don't understand. You wrap out Memcached's methods like `set` and `get` already, but you don't want to wrap `add`. Why?

**Comment by nicolas-grekas** [comment]
Because of what you said in the description: this is not part of any interface.

**Comment by ilyachase** [comment]
Okay I see.
