### ISSUE TITLE
[Console] Accessing the command name

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#31578]
A command `$defaultName` is protected

vendor/symfony/console/Command/Command.php
![image](https://user-images.githubusercontent.com/3177556/58168641-77afee80-7c2a-11e9-8779-754439acdf13.png)

=> It prevents to use it as a reference somewhere else in the code and thus make us duplicate content.

Why not make it public or a constant?

**Comment by chalasr** [comment]
You can use `Command::getDefaultName()` to access it, the constructor  or the `setName()` method can be used to set a (non-default) name.

**Comment by sylfabre** [comment]
@chalasr nice one! Thanks!

**Comment by msmuenchen** [comment]
FYI, for anyone coming here from Google. This solution does not work in SF 8 onwards, the method got removed, you need to go via Reflection: https://github.com/symfony/symfony/pull/59565#issuecomment-5011875150
