### ISSUE TITLE
php bin/console make:crud cannot create relations between tables

### ISSUE THREAD

**Issue by nouraellm** [symfony/symfony#31581]
**Symfony version(s) affected**: x.y.z
4.2.8
**Description**  

Entities contain relations (OneToMany, ManyToOne) and when running php bin/console make:crud  it doesn't recognize relations. when trying to access the route /new it throws an error.
The view also doesn't return a form with related fields 

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by bmendonca** [comment]
Hi there, @nouraellm ! You may want to consider raising the issue in https://github.com/symfony/maker-bundle

**Comment by nouraellm** [comment]
@bmendonca  thank you I will raise it there

**Comment by MouadZIANI** [comment]
@nouraellm ha solution fhad lvideo
