### ISSUE TITLE
[Form] Recall for choice group_by ordering

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#31593]
When the choice_loader is built-in / out of scope, working with the choices can be a real pain. As such i'd like to recall for #21717 / #22136

Given

```php
$form = $this->createForm(TimezoneType::class, null, [
    'intl' => true,
    'group_by' => function ($tz) {
        return Timezones::getGmtOffset($tz);
    },
]);
```

The UX is completely off due default ordering;

![image](https://user-images.githubusercontent.com/1047696/58240477-5abf0c80-7d4b-11e9-906d-476b059c5c1c.png)

Perhaps this should be solved per type, but i tend to believe having some generic solution is nice. Or maybe there's a better way?

Moreover, as we deprecated the `region/zone` option; there's currently no sane alternative to apply such a filter. Consider #28624 for this :)

**Comment by ro0NL** [comment]
from https://github.com/symfony/symfony/issues/21717#issuecomment-480512825)

> I'm -1 on this feature. The problem solved here can easily be solved by sorting the choices before passing them to the `choices` option (either with `usort()` or - better - in the database).

i figure the feature im seeking is a `choice_order` option.

**Comment by xabbuh** [comment]
I am not convinced we need this. The issue laid out in the initial description seems specific to some of the core types, isn't it? So solving the ordering there (as a bug fix) looks like the solution to me.

**Comment by ro0NL** [comment]
You're right, if we can do something for the core intl types that be great. Though i agree we probably want a generic `choice_filter/order` option. Solving it with choice_loader seems the better practice.

What about specific `filter / order` options for the intl types only?

**Comment by xabbuh** [comment]
Related to #11847 and #28624 then?

**Comment by ro0NL** [comment]
#11847 is solved by  #28624 actually. But #28624 introduces a global `choice_filter` option, so perhaps something we don't want (as we've concluded here). Adding `choice_filter` only the intl choice types could work (i tend to believe a "callable" option is more powerful then a "list of values").

Another thing is (hence i've created this issue) the ordering of choices. If we use "group_by" we might need a different ordering to comply with the grouping (as demonstrated here with timezones)

So perhaps `intl_filter + intl_order` are the better options (tied to intl choice types).

**Comment by xabbuh** [comment]
Regarding your timezone example: Why would we want the choices to be ordered differently when they are grouped then without the grouping?

**Comment by ro0NL** [comment]
because for UX they should be ordered by GMT offset (from low to high)

**Comment by xabbuh** [comment]
But this order is fine for either case, isn't it?

**Comment by ro0NL** [comment]
not sure i understand, technically/semantically it doesnt matter (the same choices remain available)

however looking at

![image](https://user-images.githubusercontent.com/1047696/61641848-2a8ae000-aca0-11e9-80d5-32c3a4fcaf49.png)


for UX the optgroups should go from `-12` to `+12`. That's what im trying to solve now :)

**Comment by yceruto** [comment]
The `choice_order` or `choice_sort` option for intl types only sounds good to me.
