### ISSUE TITLE
Script cache:clear returned with error code -1073741819

### ISSUE THREAD

**Issue by ivanovnickolay** [symfony/symfony#31602]
Symfony version(s) affected**: ^4.1
php `PHP 7.3.4 (cli) (built: Apr  2 2019 21:56:52) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans
`
`Composer version 1.9-dev (1.9-dev+dd40d74bf6041ddcefa1ebe46fb9117d031b1ccd) 2019-04-10 11:11:57
`
```
composer.phar update --no-interaction --ansi
 Loading composer repositories with package information
 Updating dependencies (including require-dev)
 Nothing to install or update
 Generating autoload files
 ocramius/package-versions:  Generating version class...
 ocramius/package-versions: ...done generating version class
 Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code -1073741819
 !!
 Script @auto-scripts was called via post-update-cmd
 Failed to update packages for  ./composer.json.
```
`php.exe phpunit --configuration \phpunit.xml.dist Test.php --teamcity
Process finished with exit code -1073741819 (0xC0000005)`

`bin\console --version
Process finished with exit code -1,073,741,819 at 01:00:27.
Execution time: 2,550 ms.`

**How to reproduce**  

**Possible Solution**  

**Additional context**  
This project in PHP 7.1.7 does not have such problems. When you switch to the new version (copying the project folder, not repository cloning), it immediately shows errors when running tests.

**Comment by mhujer** [comment]
@ivanovnickolay Have you tried disabling Xdebug?

There is also a newer version of PHP 7.3.5 and Xdebug 2.7.2, so try if upgrading fixes the problem.

**Comment by ivanovnickolay** [comment]
> @ivanovnickolay Вы пытались отключить Xdebug?
> 
> Существует также более новая версия PHP 7.3.5 и Xdebug 2.7.2, поэтому попробуйте, если обновление решит проблему.

But on this php sites on other frameworks successfully work. Here the case is most likely in the command "cache: clear" - it leads to the collapse of Symfony

**Comment by ivanovnickolay** [comment]
I created a new project Symfony 4.2.8. The zero system works - the Symfony page is displayed.
I deployed my project on a clean system - again this error (((

**Comment by xabbuh** [comment]
Do you use the exact same setup locally where it works and on the system where it doesn't work?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by m2broth** [comment]
I've faced with the same issue when clearing cache on the windows server. I suppose that there is some circular reference in the symfony object (don't know exactly the real object). I'm continue investigating the issue
