### ISSUE TITLE
Trim in parameterbag get

### ISSUE THREAD

**Issue by MPablo** [symfony/symfony#31605]
**Description**  
A get method in parameterbag ( or covered in the existing get)  as many parameters are from forms you usually dont want trailing whitespaces, also avoid using callable of filter() 

**Example**  
$request->request->get('name', null, 'trim'), where trim can also be ltrim or rtrim
or 
$request->request->tGet('name', null, 'trim'), where trim can also be ltrim or rtrim, if value is omitted standard would be trim

**Comment by linaori** [comment]
What would be the benefit of this as opposed to dealing with this in the form type? If you use forms, you'll probably be using this instead. I see why you would want a shortcut, but I'm not sure this is a scenario that should happen often :thinking:

**Comment by MPablo** [comment]
In our case we are not using symfony-forms, I have no idea how many are using only parts of symfony thus cant say how often this scenario happens

**Comment by fabpot** [comment]
Would it be better than `trim($request->request->get('name'))`?

**Comment by linaori** [comment]
I could imagine that `trim(null)` could be an issue, assuming the intention is to leave `null` as `null` instead of transforming it to and empty string

**Comment by ro0NL** [comment]
Not a header bag concern IMHO. I agree with @fabpot; use `trim($request->request->get('name', ''))`, preserving null if needed.

**Comment by fabpot** [comment]
And for forms, everything is a string anyway when coming from an HTTP request.

Let's close as we won't implement it.
