### ISSUE TITLE
[DI][Config] Can not use environment variables when using the PrependExtensionInterface

### ISSUE THREAD

**Issue by Spea** [symfony/symfony#31608]
**Symfony version(s) affected**: >= 4.2

**Description**  
We recently upgraded from 3.4 to 4.2 and are now in the process of using environment variables instead of simple parameters.

While doing so, I got an error like this: 

> Invalid type for path "bundle.port". Expected int, but got string.

Here is the config:

```yaml
bundle:
    port: '%env(SOME_PORT)%'
```

After some searching, I found [this issue](https://github.com/symfony/symfony/issues/25868) so I changed my config to the following:

```yaml
bundle:
    port: '%env(int:SOME_PORT)%'
```

But even then it did not work. So after some more debugging I saw that the error actually comes from one of my prepends for another bundle, and as [documented here](https://symfony.com/doc/current/bundles/prepend_extension.html) it looks like  this:

```php
public function prepend(ContainerBuilder $container)
{
    $configs = $container->getExtensionConfig($this->getAlias());
    $config = $this->processConfiguration(new Configuration(), $configs); # Error occurred after this line
    
    // ... more code
}
```

So it seems at this time the `EnvVarProcessor` (documented [here](https://symfony.com/doc/current/configuration/environment_variables.html#environment-variable-processors)) is not yet configured properly.

I tried different "hacky" ways of configuring the `EnvVarProcess` in this place, but always failed.

So I guess this leads to the question: Is this intended behaviour or is this a bug and somehow fixable?

**How to reproduce**  

I created a reproduction repository here: https://github.com/Spea/symfony-prepend-issue

Simply running `composer install` already shows the error when trying to clear the cache after installing the dependencies.

The failing part is [this method](https://github.com/Spea/symfony-prepend-issue/blob/master/src/Bundle/AdvancedBundle/DependencyInjection/AdvancedExtension.php#L24-L29). 

Removing the `implements PrependExtensionInterface` will "fix" the error, but will also result in no more prepending a config (in a real world scenario)

**Comment by ro0NL** [comment]
I figure we need this block

https://github.com/symfony/symfony/blob/63d730920b43ee5355c6ff3a730fc67a8c325db7/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L54-L61

before calling `prepend()` above as well, currently the env placeholders are missing when calling it.

**Comment by ro0NL** [comment]
@Spea can you try #31609

**Comment by ro0NL** [comment]
Actually this is a bit harder as the env placeholders are not resolved yet, meaning from the error message a string is literally `"%env(...)%"` and not its placeholder string which i expected first.

**Comment by Spea** [comment]
@ro0NL Tested your changes in #31609 and it works, thank you for the quick reply/fix :)

**Comment by nicolas-grekas** [comment]
Closing this is looks rare enough and nobody else reported the issue.
@ro0NL gave it a try in #31609 so if some that actually needs this and want to work on the fix, they can take over.
