### ISSUE TITLE
Warning: spl_object_hash () expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by sulaman0** [symfony/symfony#31617]
**Symfony 4.2.8:**: 

**Description**  
I would like to show a unique dropdown of category in Symfony forms.

Codes sample is:

`$builder
->add( 'niceOne', EntityType::class, [

		        'class'         => BlogPosts::class,
			'choice_label'  => 'bp_category'
			'query_builder' => function ( BlogPostsRepository $blog_posts_repository ) {
		            $dd = $blog_posts_repository->createQueryBuilder( 'bp' )
				                            ->select( 'bp.bp_category' )
				                            ->distinct( true )
				                            ->orderBy( 'bp.bp_category', 'ASC' );
				dump( $dd );
				return $dd;
			},
	] );`

When I remove select parameter form Query builder than It works fine.
When I put the select parameter with them in the query builder error comes up.
This same query works if I put it in the Repository class and use in twig template but It's not working in the form class.

**Comment by Simperfit** [comment]
Could you please create a reproducer ?

**Comment by xabbuh** [comment]
Can you show the Doctrine mapping of your blog class?

**Comment by sulaman0** [comment]
Here is Doctrine Mapping,


<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\BlogPostsRepository")
 */
class BlogPosts {

	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\OrderBy({"id"="DESC"})
	 */
	private $id;

	/**
	 * @ORM\Column(name="bp_name", type="string", length=255)
	 */
	private $bp_name;

	/**
	 * @ORM\Column(name="bp_description", type="text")
	 */
	private $bp_description;

	/**
	 * @ORM\Column(name="bp_tag", type="string", length=50)
	 */
	private $bp_tag;

	/**
	 * @ORM\Column(name="bp_archived", type="boolean", nullable=true)
	 */
	private $bp_archived;

	/**
	 * @ORM\Column(name="bp_authour", type="string", length=50, nullable=true)
	 */
	private $bp_authour;

	/**
	 *
	 * @var \DateTime $bp_posted_at
	 * @ORM\Column(name="bp_posted_at", type="datetime")
	 * @Gedmo\Timestampable(on="create")
	 *
	 */
	private $bp_posted_at;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	private $bp_img;

	/**
	 * @ORM\Column(type="string", length=50)
	 */
	private $bp_category;

	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 */
	private $slug;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\BlogPostComments", mappedBy="blogPost",fetch="EXTRA_LAZY")
	 * @ORM\OrderBy({"id"="ASC"})
	 */
	## fetch=Extra_lazy only get count query instead  of full query.
	private $blogPostComments;

	/**
	 * @var $bp_updated_at \DateTime
	 * @ORM\Column(type="datetime", nullable=true)
	 * @Gedmo\Timestampable(on="create")
	 *
	 */
	private $bp_updated_at;

	/**
	 * @ORM\ManyToMany(targetEntity="App\Entity\BlogPostTags", mappedBy="BlogPosts")
	 */
	private $yes;

	public function __construct() {
		$this->blogPostComments = new ArrayCollection();
		$this->yes              = new ArrayCollection();
	}

	public function getId(): ?int {
		return $this->id;
	}

	public function getBpName(): ?string {
		return $this->bp_name;
	}

	public function setBpName( string $bp_name ): self {
		$this->bp_name = $bp_name;

		return $this;
	}

	public function getBpDescription(): ?string {
		return $this->bp_description;
	}

	public function setBpDescription( string $bp_description ): self {
		$this->bp_description = $bp_description;

		return $this;
	}

	public function getBpTag(): ?string {
		return $this->bp_tag;
	}

	public function setBpTag( string $bp_tag ): self {
		$this->bp_tag = $bp_tag;

		return $this;
	}

	public function getBpArchived(): ?bool {
		return $this->bp_archived;
	}

	public function setBpArchived( ?bool $bp_archived ): self {
		$this->bp_archived = $bp_archived;

		return $this;
	}

	public function getBpAuthour(): ?string {
		return $this->bp_authour;
	}

	public function setBpAuthour( ?string $bp_authour ): self {
		$this->bp_authour = $bp_authour;

		return $this;
	}

	public function getBpPostedAt(): ?\DateTimeInterface {
		return $this->bp_posted_at;
	}

	public function setBpPostedAt( \DateTimeInterface $bp_posted_at ): self {
		$this->bp_posted_at = $bp_posted_at;

		return $this;
	}

	public function getBpImg(): ?string {
		return $this->bp_img;
	}

	public function setBpImg( ?string $bp_img ): self {
		$this->bp_img = $bp_img;

		return $this;
	}

	public function getBpCategory(): ?string {
		return $this->bp_category;
	}

	public function setBpCategory( string $bp_category ): self {
		$this->bp_category = $bp_category;

		return $this;
	}

	public function getSlug(): ?string {
		return $this->slug;
	}

	public function setSlug( ?string $slug ): self {
		$this->slug = $slug;

		return $this;
	}

	/**
	 * @return Collection|BlogPostComments[]
	 */
	public function getBlogPostComments(): Collection {
		return $this->blogPostComments;
	}

	public function addBlogPostComment( BlogPostComments $blogPostComment ): self {
		if ( ! $this->blogPostComments->contains( $blogPostComment ) ) {
			$this->blogPostComments[] = $blogPostComment;
			$blogPostComment->setBlogPost( $this );
		}

		return $this;
	}

	public function removeBlogPostComment( BlogPostComments $blogPostComment ): self {
		if ( $this->blogPostComments->contains( $blogPostComment ) ) {
			$this->blogPostComments->removeElement( $blogPostComment );
			// set the owning side to null (unless already changed)
			if ( $blogPostComment->getBlogPost() === $this ) {
				$blogPostComment->setBlogPost( null );
			}
		}

		return $this;
	}

	public function getBpUpdatedAt(): ?\DateTimeInterface {
		return $this->bp_updated_at;
	}

	public function setBpUpdatedAt( \DateTimeInterface $bp_updated_at ): self {
		$this->bp_updated_at = $bp_updated_at;

		return $this;
	}

	/**
	 * @return Collection|BlogPostTags[]
	 */
	public function getYes(): Collection {
		return $this->yes;
	}

	public function addYe( BlogPostTags $ye ): self {
		if ( ! $this->yes->contains( $ye ) ) {
			$this->yes[] = $ye;
			$ye->addBlogPost( $this );
		}

		return $this;
	}

	public function removeYe( BlogPostTags $ye ): self {
		if ( $this->yes->contains( $ye ) ) {
			$this->yes->removeElement( $ye );
			$ye->removeBlogPost( $this );
		}

		return $this;
	}


	/**
	 *
	 * This method will capture slug of all records and keep them in an array
	 *
	 * @return string|null
	 */
	public function __toString() {
		// TODO: Implement __toString() method.
		return $this->getBpName();
	}
}

**Comment by xabbuh** [comment]
Well, you are only selecting the `bp_category` of your blog posts, but you need to select objects. What exactly did you want to achieve by doing this?

**Comment by sulaman0** [comment]
I would like to get Unique categories list from the Blog Post table.

**Comment by sulaman0** [comment]
Look at this screenshot - this is database structure of the blog post table.
![image](https://user-images.githubusercontent.com/30592487/58366755-82030e80-7ef0-11e9-908c-3e16ba806305.png)
In this table blog post categories are repeatable, I would like to get Un-repeatable(unique) category list.

**Comment by sulaman0** [comment]
@Simperfit reproducer is:

**Purpose:**

I would like to create a form using the Symfony form component.
Using that form admin can add new blog Post.
In the Blog Post table, there is a field whose name is Category.
I would like to extract all unique (un-repeatable) categories from existing records & want to show in a dropdown.


**Reproducer**

When select single field from the table blog post object then error comes up.

`$builder
->add( 'niceOne', EntityType::class, [
	        'class'         => BlogPosts::class,
		'choice_label'  => 'bp_category'
		'query_builder' => function ( BlogPostsRepository $blog_posts_repository ) {
	            $dd = $blog_posts_repository->createQueryBuilder( 'bp' )
			                            ->select( 'bp.bp_category' )
			                            ->distinct( true )
			                            ->orderBy( 'bp.bp_category', 'ASC' );
			dump( $dd );
			return $dd;
		},
] );`


The question is, If this is not the right method so, How can I get the Unique categories from the Blog Post table or show in a dropdown.

**Comment by xabbuh** [comment]
In your example the category is not an entity so you cannot use it to populate the list of choices. You either need to extract the category as an entity and use that to populate the `EntityType` or create the list of choices based on this query, but use the normal `ChoiceType` instead.

Anyway, this is not a bug in Symfony. Since we are using GitHub only for feature requests and bug reports I am going to close here. Please use one of the [support channels] (https://www.symfony.com/support) if you need further help. Thank you for understanding.
