### ISSUE TITLE
Why not add a return type declaration for HttpKernelInterface?

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/symfony#31628]
**Question**  
Since 7.1 is the required PHP version why not add a return type declaration to HttpKernelInterface? Is it because refactoring is generally not wanted or are there other reasons? Reading the doc blocks the handle() implementation must return a Response object anyway. Or can we implement the handle method and return whatever we want?

**Comment by chalasr** [comment]
Adding a return type is not backward compatible: if you have your own implementation of `HttpKernelInterface`, you will suddenly get a fatal error at time to upgrade: https://3v4l.org/FAhnl.
See also our BC promise: https://symfony.com/doc/current/contributing/code/bc.html

**Comment by nicolas-grekas** [comment]
Note that we should be able to do it for 5.0.
Closing as explained for now.
