### ISSUE TITLE
[Messenger] Require default_bus with multiple buses

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#31624]
**Symfony version(s) affected**: 4.3

**Description**  
At least in 4.3, if you have multiple messenger buses, you need to specify `framework.messenger.default_bus`. If you do not, you'll get:

> The service "messenger.routable_message_bus" has a dependency on a non-existent service "messenger.default_bus"

**How to reproduce**  
Add `framework.messenger.buses` with two entries below, but do not specify `framework.messenger.default_bus`.

**Possible Solution**  
In the FrameworkBundle [Configuration class](https://github.com/symfony/symfony/blob/5dba412d30f09fed1c895eed3fc23e78a16defed/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1104), we should probably add validation to throw a better message.

**Comment by vincenttouzet** [comment]
@weaverryan Maybe we can also just modify this line : 
https://github.com/symfony/symfony/blob/5dba412d30f09fed1c895eed3fc23e78a16defed/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1648

Changing the condition from :
```php
        if (null === $config['default_bus'] && 1 === \count($config['buses'])) {
            $config['default_bus'] = key($config['buses']);
        }
```

to 
```php
        if (null === $config['default_bus']) {
            $config['default_bus'] = key($config['buses']);
        }
```

Then the default bus will be the first declared. WDYT :thinking:  ?

**Comment by weaverryan** [comment]
Hmm... I kinda like the idea of forcing the user to be explicit - an exception would almost be a built-in README to communicate that the user needs to choose one bus as their main bus, instead of not realizing that it's happening.

**Comment by chalasr** [comment]
Same as @weaverryan. We deprecated a similar behavior for security user providers which was to take the first defined provider in favor of explicitly defining the provider on a single firewall/listener.

**Comment by vincenttouzet** [comment]
Ok I understand. I've made the PR to add a validation
