### ISSUE TITLE
[Validator] Valid constraint with GroupSequence and explicit group is not executed

### ISSUE THREAD

**Issue by ashikhman** [symfony/symfony#31639]
**Symfony version(s) affected**: =>4.2.6, <=4.2.8

**Description**

In our Symfony API projects we use Validator component with GroupSequence feature in order to implement Constraint execution ordering. For example, root JSON object has property of type array of objects:

    {
        "items": [
            {
                "key": "val"
            }
        ]
    }

First, we validate if `items` property is of type `array`, then we validate every object inside this `array`.
This task is implemented using GroupSequence feature:

    <?php
    
    /**
     * @GroupsSequence({{"First"}, "Root", {"Last"}})
     */
    class Root {
        /**
         * @var Item[]
         
         * @Assert\Type("array", groups={"First"})
         * @Assert\Valid(groups={"Last"})
         */
        protected $items = [];
    }

Starting from `symfony/validator:4.2.6` `Valid` constraint with explicit group never executes.

**How to reproduce**

Repository with ready to run tests: https://github.com/ashikhman/symfony-valid-constraint-bug

This test passes in `4.2.5` and fails in `=>4.2.6`

```
    public function testValidArrayPropertyValidExecuted(): void
    {
        $entity = new Entity();
        $entity->reference = [new Reference()];

        $this->metadata->setGroupSequence(new GroupSequence([['First'], 'Entity', ['Last']]));

        $this->metadata->addPropertyConstraint('reference', new Type(['value' => 'array', 'groups' => ['First']]));
        $this->metadata->addPropertyConstraint('reference', new Valid(['groups' => ['Last']]));

        $this->referenceMetadata->addPropertyConstraint('value', new NotBlank());

        $violations = $this->validate($entity);

        $this->assertCount(1, $violations);
        $this->assertSame('reference[0].value', $violations->get(0)->getPropertyPath());
        $this->assertSame('This value should not be blank.', $violations->get(0)->getMessage());
    }
```

**Possible Solution**

You can make `Valid` constraint to skip validation in case if value is of scalar type like other validators skip execution if value is null. This way you can omit setting group to `Valid` constraint.

**Comment by bmxpapr** [comment]
Test `testValidArrayPropertyValidExecuted` also fails on `symfony/validator` `4.2.11`. I also checked most recent `4.3.8` - it still fails there.

**Comment by zsdamian** [comment]
Have same problem here.

**Comment by xabbuh** [comment]
Thank you for the example application. This is the same as #32900. So I am going to close this issue as a duplicate.

To make your example work you need to add the `Last` group to the `NotBlank` constraint of the `value` property.
