### ISSUE TITLE
[DoctrineBridge] Trigger a proper error when injection a service containing the entity manager in a doctrine listener

### ISSUE THREAD

**Issue by Simperfit** [symfony/symfony#31636]
**Description**  

This is mainly for DX but I think if we throw a proper message when injecting a service that contains the entity manager into a doctrine listener (because this is not working) and the only errors we get is some flush errors that are linked but not really the root cause.

**Example**  

Today something like this is thrown by Doctrine directly: 
```
Doctrine\ORM\ORMInvalidArgumentException: Entity Pack\Domain\Model\Pack@000000001668b6260000000058419870 is not managed. An entity is managed if its fetched from the database or registered as new through EntityManager#persist
```
Maybe we could throw an special error like this one:
```
Injecting a service that contains `EntityManagerInterface` into a service that as a listener tag is not allowed.
```

Tell me if this is this has more it's place into doctrinebundle.

**Comment by dmaicher** [comment]
I think actually this is a bug :wink: There are multiple different EntityManager instances created - which should never happen really.

See
https://github.com/symfony/symfony/issues/28869
https://github.com/symfony/symfony/issues/30091
https://github.com/symfony/symfony/issues/30465

I think it should be resolved on DI level. If there is no proxy-bridge available then it should probably end up with a circular-reference exception or so.

**Comment by Simperfit** [comment]
@dmaicher That's the fix I though of, handle this at the DI level and throw a circular-reference exception specify which service is injecting is which listener.

**Comment by dmaicher** [comment]
@Simperfit I think the fix is not necessarily EntityManager specific though. I think this scenario should be detected as a circular reference on DI level independent of Doctrine and the EntityManager if possible.

**Comment by Simperfit** [comment]
cc @weaverryan You are working on this right ?

**Comment by nicolas-grekas** [comment]
This should be fixed. Please report back if not.
