### ISSUE TITLE
symfony/web-link require http-kernel 4 in dev instead of 3

### ISSUE THREAD

**Issue by CocoJr** [symfony/symfony#31634]
**Symfony version(s) affected**: 3.4.27

**Description**  
When you try to install `symfony/web-link` with composer in dev, the component require the `symfony/http-kernel` component in version `^4.3`, instead of `^3.0` to be compatible with symfony 3.4

**How to reproduce**  
Create a new symfony 3.4 project and require `symfony/web-link` with dev-dependencies.

**Possible Solution**  
symfony/web-link need to require the version 3.4 to be compatible with 3.4

**Additional context**  
I think everythink is clear, i have no more information.

Thanks for your time.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/WebLink/composer.json
Any versions of HttpKernel is allowed from 2.8 to 4.*, including 4.*
It's your responsibility to restrict transitive dependecies if you want to.
Note that symfony/flex allows doing so for all components at once, with the extra.symfony.require option in composer.json

**Comment by CocoJr** [comment]
Yes I had seeing that but the problem is here for the version 4 of the component. In require we have a dependencies to foundation 3.4 and 4 but in dev we have the conflict with the http-kernel in 4.3 minimum. 
So I thinks it's better If u restrict to http-foundation 4 mini or you allow the version 3.4 of the kernel.

I hope it's clear...

Thanks for your times.

**Comment by CocoJr** [comment]
Any news about my last comment ?

**Comment by xabbuh** [comment]
I do not understand your last comment. Can you provide an example that allows to reproduce?

**Comment by CocoJr** [comment]
There are no example here, it's just a dependencies requirment conflict.
You allow the `symfony/http-foundation` in ^3||^4 in the require, but you mark a conflict with `symfony/http-kernel` in version <4.3, but if you take the `symfony/http-kernel` in 4.3, you can't have the  ̀symfony/http-foundation`.

The only way for me to solve this problem is to restrict the require to `symfony/http-foundation` in ^4 OR accept in the require-dev the `symfony/http-kernel` under 4.3.

Today if you are in dev environment for composer and use symfony 3, you can't require this component du the require-dev restriction & conflict (you have to specify the version 3 for this one, but you can't use the version 4 due to the require-dev conflict with the require).

**Comment by xabbuh** [comment]
If your other components are in version 3.4, you can still use the WebLink component in version 3.4. That's the only solution I see for you if you can't upgrade.
