### ISSUE TITLE
Cannot get the Security service in the tests

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#31647]
**Symfony version(s) affected**: 4.2.4

**Description**  

```php
class AuthorizationTest extends WebTestCase
{
    public function testXxx(): void
    {
        self::bootKernel();
        $security = self::$container->get(Security::class);
        // ...
    }
}
```

Throws:

> ServiceNotFoundException : The "Symfony\Component\Security\Core\Security" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

The `self::$container` is the test container, it should let us access private services.

Am I missing something?

**How to reproduce**  

```php
class AuthorizationTest extends WebTestCase
{
    public function testXxx(): void
    {
        self::bootKernel();
        self::$container->get(Security::class);
    }
}
```

**Comment by xabbuh** [comment]
see #30104

**Comment by mnapoli** [comment]
@xabbuh thank you for the link, that helps to have a workaround.

Maybe there could be a way to improve the experience here? The current solution is unfortunately not obvious at all (I tried to do it manually but even if it's a few YAML lines those are not obvious at all to write).

I'm not sure what would be the ideal solution though, but would you agree it's worth trying to fix?

**Comment by xabbuh** [comment]
IIRC there were affords to provide a better error message in the tests. But sadly I do not recall if that was finally merged.

**Comment by weaverryan** [comment]
I agree that giving a better error message in the test environment would indeed but a good idea.

**Comment by javiereguiluz** [comment]
It's been almost a year since this issue was reported. Is this still a common issue? Should we still add or improve some error message? Thanks.

**Comment by mnapoli** [comment]
If you ask me, `self::$container->get(Security::class)` should just work.

If you want to groom the backlog, since I was the only one suggesting that I would understand if you closed the issue.

**Comment by xabbuh** [comment]
IMO this is the same as #30104 and symfony/symfony-docs#12647 should help, right?

**Comment by mnapoli** [comment]
It is indeed a duplicate of #30104.

IMO symfony/symfony-docs#12647 is a false solution (this is so complex and confusing, it is really frustrating when dealing with that in tests), but I will close this as a duplicate of #30104.

Thanks for the links.

**Comment by chiqui3d** [comment]
The same thing happened to me. It was when I stopped using `Security` service by the `[CurrentUser]` attribute in the controllers. It was removed from the container, even putting as public has not helped, it kept deleting, I do not know if there is something else behind it, but I have used other services such as the following for the logged in user checks:

```
 $this->assertSame(
            $testUser->getUsername(),
            self::getContainer()->get(TokenStorageInterface::class)->getToken()->getUser()->getUserIdentifier()
        );
$this->assertTrue(self::getContainer()->get(AuthorizationCheckerInterface::class)->isGranted('ROLE_USER'));
```
