### ISSUE TITLE
symfony/templating 4.3 throws deprecation warnings

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#31645]
**Symfony version(s) affected**: 4.3-beta2

**Description**  
symfony/twig-bundle loads a service definition for `Symfony\Bundle\TwigBundle\Loader\FilesystemLoader` if symfony/templating is installed and FilesystemLoader throws deprecation warning on kernel compile.

https://github.com/symfony/twig-bundle/blob/6d2fe7133785da982197fe632009162b114e45f9/DependencyInjection/TwigExtension.php#L46

https://github.com/symfony/twig-bundle/blob/6d2fe7133785da982197fe632009162b114e45f9/Resources/config/templating.xml#L9

https://github.com/symfony/twig-bundle/blob/master/Loader/FilesystemLoader.php#L14

**How to reproduce**  
have a dependency on symfony/templating and symfony/twig-bundle

**Comment by fabpot** [comment]
That's expected. You should not use `symfony/templating` anymore with Twig.

Do you have `symfony/templating` as a depedency because this is a project that was upgraded to 4.2/4.3 or because of another dependency (like Sonata)?

**Comment by mmarton** [comment]
The second one. It is a dependency of a vich/uploader-bundle.

**Comment by fabpot** [comment]
Unfortunately, the only solution is to upgrade the dependency to not use `symfony/templating` anymore.

**Comment by fabpot** [comment]
There is an issue there mentioning that issue: https://github.com/dustin10/VichUploaderBundle/issues/625

**Comment by mmarton** [comment]
thanks
