### ISSUE TITLE
[Intl] forCountryCode() method requires uppercase locale codes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#31656]
**Symfony version(s) affected**: 4.3

**Description**  

This code will fail:

```php
Timezones::forCountryCode('es')
```

```
Couldn't read the indices [CountryToZone][es] for the locale "meta"
in "symfony-demo/vendor/symfony/intl/Resources/data/timezones".
```

But this code will work:

```php
Timezones::forCountryCode('ES')

// [
//   0 => "Africa/Ceuta"
//   1 => "Atlantic/Canary"
//   2 => "Europe/Madrid"
// ]
```

We allow using lowercase codes everywhere in Intl. Why require uppercase here? Or am I missing something? Thanks.

**Comment by ro0NL** [comment]
I'm not sure we should do this, mostly because of https://3v4l.org/b3vqJ

Country codes are uppercase per spec.

> We allow using lowercase codes everywhere in Intl. Why require uppercase here? Or am I missing something? Thanks.

AFAIK we don't ... language code is lowercase, country code is uppercase. A locale is mixed (language_COUNTRY)

**Comment by javiereguiluz** [comment]
@ro0NL yes, you are right that country code != locale code ... however, for DX, could we do what @GaryPEGEOT is proposing in #31663? Would that introduce unexpected behavior somehow? Thanks.

**Comment by ro0NL** [comment]
i dont think one should mix&match e.g. `fr` and `FR`. Based on case you know if it's a language code or a country code. Using a lowercase country code (thus looks like a language code) might be confusing / error prone.

Moreover, `Countries::exists()` & co also don't account for lowercased codes.

**Comment by ro0NL** [comment]
inferring country codes from language codes (`country=upper(language)`), or vice versa, is plain wrong technically (http://www.flagsarenotlanguages.com) waiting for mismatches to happen.

In this case im curious where the lowercase value comes from, and why it's considered a country code. Any why symfony should account for that :P (violating the spec) ... not worth it IMHO.

If anything, `strtoupper/lower` is a user normalization concern.

**Comment by javiereguiluz** [comment]
@ro0NL I understand my mistake now. Thanks!

Would you agree merging #31677 to improve the error message? Thanks.
