### ISSUE TITLE
[Mailer] Make Round-robin algorithm persistent between requests

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony#31659]
**Description**  
What about to make Failover/Round-robin algorithms in Mailer Component persistent between requests? Does it make sense? I want to discuss it first before start working on it

**Example**  
Right now if I send one email per request with e.g. Round-robin it will always use the 1st transport from my list. But if we stored the current cursor in cache - it would be persistent between requests, and no matter if I send a few emails or only one per request - Round-robin will share the load between registered transports correctly instead of just constantly using the 1st one

**Comment by bullder** [comment]
What about not bringing state to that service and just shuffle order of transports? https://github.com/symfony/symfony/pull/31930

**Comment by fabpot** [comment]
As discussed with @bocharsky-bw, I don't think we need to change anything here. If one really cares about round-robin, I think they need to use the messenger integration and send emails with a consumer. Adding a state should be avoided in my opinion, especially as it needs to be "global" across all machines if you have more than one frontend. The added complexity is not worth it as we already have a solution: using the messenger. For these reasons, I'm closing as a won't fix.

We should add a note about this limitation in the docs though (https://github.com/symfony/symfony-docs/issues/11701).
