### ISSUE TITLE
[HttpKernel] Add Config as a dependency for HttpKernel?

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/symfony#31666]
**Question**
Should the Config component be added as a dependency for HttpKernel package? If I run:

```php
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
class Kernel extends BaseKernel
{
    public function registerBundles() { return []; }
    public function registerContainerConfiguration(LoaderInterface $loader) {}
}
$kernel = new Kernel('foo', false);
$kernel->handle(Request::createFromGlobals();
```

I get:

`"PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Config\ConfigCache' not found in [...]/vendor/symfony/http-kernel/Kernel.php:477"`

So I cannot implement the abstract Kernel without installing the Config component. Is that enough to add it to HttpKernel's composer.json?

The same applies to the DependenyInjection component which is also required to implement the class Kernel.

(If this is the wrong place for questions like this, then please tell me :)

**Comment by fabpot** [comment]
But you can use HttpKernel without the Config component (like in Drupal or Silex)
