### ISSUE TITLE
Session Handling: Redis or File Handler Configuration

### ISSUE THREAD

**Issue by kickthemooon** [symfony/symfony#31687]
I am trying to setup/configure my session like this:

```
$options = [
  'gc_maxlifetime'  => 14 * 24 * 60 * 60,
  'name'            => 'MySession',
  'cookie_lifetime' => 14 * 24 * 60 * 60,
]

$sessionStorage = new NativeSessionStorage($options);

if ($config['session']['storage'] == 'redis') {
  // client in my case predis
  $client = new MyClient();
  $sessionStorage->setSaveHandler(new RedisSessionHandler($client));
} else {
  // I added the else statement because I dont know what happens if a session handler
  // is not provided, if there is a default behaviour.
  $fileSaveHandler = new NativeFileSessionHandler($docRoot . '/temp/sessions');
  $sessionStorage->setSaveHandler($fileSaveHandler);
}

$session = new Session($sessionStorage);

$session->start();
```

Few questions:

1. Do I need setup `NativeFileSessionHandler` in case I dont want to use Redis session handler or is there a default?

2. Can I delete the framework.yml session part and initialize the session in my code?

```
framework:
    session:
        handler_id: ~
```

3. Where is the best place to initialize my session so my application can use it?

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!
