### ISSUE TITLE
Compatible with php 7.2

### ISSUE THREAD

**Issue by shital7mahajan** [symfony/symfony#31686]
Hi,

I have run following PHPCS command and getting following error & warning:

`$ phpcs --standard=PHPCompatibility --extensions=php,module,inc,install,test,profile,theme --runtime-set testVersion 7.2 .`

FILE: project\yaml\Inline.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

  WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 
FILE: project\yaml\Parser.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

  WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

FILE: project\yaml\Tests\InlineTest.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES

ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x4D2'
ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x4D2'

 Any plan to fix this?

**Comment by xabbuh** [comment]
There is nothing to fix. We still need to get the option value as the user might still have it configured (see also #28256). The second one is a false report. We are actually using it as a string here. So I am closing here. Thank you for understanding.
