### ISSUE TITLE
Doctrine Listener not loaded lazily doctrine-bridge

### ISSUE THREAD

**Issue by zghosts** [symfony/symfony#31683]
**Symfony version(s) affected**: 3.4.28

**Description**  
Since symfony 3.4.28 a "Circular reference detected for service" exception is thrown on cache warmup.

**How to reproduce**  
This seems to be tied to doctrine eventlisteners which get Repository services injected, which should be lazy loaded, but arn't.

comment beforehand: I know listeners should only listen to one event, but I have my reasons for doing this.

my configuration is something similar to:
```
class EventListener {
    private $repository;

    public function __construct(SomeRepositoryService $repository)
    {
         $this->repository = $repository;
    }

    public function postPersist(LifecycleEventArgs $event)
    {
        //Do something
    }
    public function preRemove(LifecycleEventArgs $event)
    {
        //Do something
    }
}
```
ServiceDefinition:
```
EventListener:
    tags:
        - { name: doctrine.event_listener, connection: default, event: postPersist, priority: 10, lazy: true }
        - { name: doctrine.event_listener, connection: default, event: preRemove, priority: 10, lazy: true }
```

**Possible Solution**  
I've trace this back to recent changes in the doctrine-bridge, specifically [line 72-75](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L72) which seems to always initialize all listeners even if they should be lazy loaded.

Restoring old behaviour by removing the foreach loop fixes the issue.

**Comment by Koc** [comment]
Do you call `ContainerAwareEventManager::getListeners()` without arguments anywhere in your code? This method not executed anywhere in Symfony IFIK, so listeners shouldn't be initialized all the time.

I'd suggest to use [Service Locator](https://symfony.com/doc/current/service_container/service_subscribers_locators.html) for cases when Doctrine's repository is dependency of the Doctrine's event listener.

**Comment by Koc** [comment]
relates to #31636

**Comment by zghosts** [comment]
You are correct that it's not being called anywhere in Symfony, however I'm using the gedmo/doctrine-extensions this does indeed call ContainerAwareEventManager::getListeners() without arguments
[see example in the sortable repository](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Sortable/Entity/Repository/SortableRepository.php#L32)

So this is either a BC break or the doctrine extensions are doing it wrong.

**Comment by Koc** [comment]
I'm suggest make call to `getConfiguration` lazy + instead of getting and iterating all request listener call special event. Something like

```php
<?php

    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->meta = $this->getClassMetadata();
    }

    private function getConfiguration()
    {
        if (null === $this->config) {
            $event = new InhectConfigEvent();
            $this->_em->getEventManager()->dispatch('gedmo.inject_sortableConfiguration', $event);

            if (null === $this->config = $event->getConfiguration()) {
                throw new \Gedmo\Exception\InvalidMappingException('This repository can be attached only to ORM sortable listener');
            }

        }

        return $this->config;
    }
```

**Comment by zghosts** [comment]
@Koc your suggestion requires changing the base repositories in gedmo/doctrine-extensions, which for a minor release I should not have to do.

As it stands, as of 3.4.28, it's now very much impossible to inject any service into a doctrine eventlistener or subscriber which depends on a repository being injected or any service having a repository injected, where that repository extends any of the doctrine-extensions base repositories (in my case sortable, blameable and translatable).

I could inject the eventmanager and fetch the repositories from there, this would work, however that defeats the whole idea of having the repositories injected (which is easier for testing).

I comes down to the fact that this change breaks having repositories extending any gedmo/doctrine-extensions repository injectable as a service.

**Comment by nicolas-grekas** [comment]
This should be fixed. Please report back if not.
