### ISSUE TITLE
[Messenger] Long task after receiving the message - message is not removed from queue

### ISSUE THREAD

**Issue by Valantir007** [symfony/symfony#31707]
**Symfony version(s) affected**: 4.2.9

**Description**  
I have one handler who receives a message - limit 1. This handler should gets ids from database and send messages to another queue. This task is very long - 15k messages. When task is very long, messenger calls ack function of "Connection" object but message is not deleted from queue.

**How to reproduce**  
Create handler and send 15k messages to another queue.

**Comment by weaverryan** [comment]
@Valantir007 Which transport are you using? Does the `messenger:consume` finish successfully?

**Comment by Valantir007** [comment]
Hi @weaverryan - I'm using Amqp. Yes, it does - the "messenger:consume" command has ended successfully but message is still with status "ready"... :/ 
Another thing I saw is that message is "unacknowledged" but after some time the message returns to "ready" but command is still working and processes the message.

**Comment by Tobion** [comment]
When the message processing in the handler takes too long, it can be that rabbitmq regards it as failed and puts the message with a redelivered header back into the queue. You could check if that is the case.

**Comment by Valantir007** [comment]
That's right. Do you know how to fix that?

**Comment by Valantir007** [comment]
We took a look on this problem and we found issue with rabbitmq configuration on our server where rabbitmq is. I'm sorry for unnecessary task.

**Comment by Tobion** [comment]
What was the issue?

**Comment by Valantir007** [comment]
Sorry for long time answers but I had to ask our administrator. We have RabbitMq with load balancing and our administrator added option:

`
backend rabbitmq_backend:
    option          clitcpka
`
and 
`timeout client 3h`

to configuration. Now everything works perfect.
