### ISSUE TITLE
[RFC][Messenger] Redis Delay Implementation

### ISSUE THREAD

**Issue by ragboyjr** [symfony/symfony#31711]
**Description**  

Currently, the Messenger Redis Implementation doesn't support the delay property of the DelayStamp. It's a bit tricky because redis streams doesn't support the delay natively.

I think we could probably implement something similar to Laravel where they basically put jobs with a delay into a sorted set sorted by the timestamp and when the consumer runs to pull a job, we first check the sorted set for jobs that are now available by the current timestamp, and if so, then we insert them into the queue.

**Example**

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Queue/LuaScripts.php#L109
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Queue/RedisQueue.php#L134

**Comment by weaverryan** [comment]
Ping @alexander-schranz!

He and I had talked about this - I believe he also had a vision for how it should work, it just didn't get done in time. Could you share with us Alexander?

**Comment by alexander-schranz** [comment]
I would implement it the following way to have both delayed message and still have the redis stream features available and I think @ragboyjr did describe it the same way.

In case of no delay we just push the message directly to the stream. But in case when it is a delayed message we push the message into a redis sorted set where the key of the sorted set is the timestamp when it should be executed. 

```php
// Connection::add($message, $delay = 0)
if ($delay) {
     // push the message to a sorted set where the timestmap when to execute it is the sort key
     $redis->zadd($this->stream . '_queue', time() + $delay, $message);

     return;
}

// current implementation of the add ...
$redis->xadd(...);
```

In the get function we need first check the queue and push them then to stream if messages exist between 0 and current timestamp:

```php
// Connection::get

// ...

// check if there are any messages which come from the queue
$messages = $redis->zrangebyscore($this->stream . '_queue', 0, time());

foreach ($messages as $message) {
    // push the messages to the stream
    $this->add($message, 0);
}

// following the current implementation with xreadgroup ...
$redis->xreadgroup(...)
// ...
```

The only disadvantage is that the consumer need to handle the delayed queue so if your consumer is not a symfony application he need to implement the get logic with sorted set read and push to the stream itself aslong as redis does not support delayed messages itself.

**Comment by ragboyjr** [comment]
@alexander-schranz y, that's exactly what I was thinking.

**Comment by weaverryan** [comment]
Someone want to open a PR?

**Comment by alexander-schranz** [comment]
@weaverryan will try to have a look at it at the weekend, but if somebody else want to start work on it before just let me know here.
