### ISSUE TITLE
[Console] Potential regression in `Aplication::doRun()` in 4.3.0

### ISSUE THREAD

**Issue by bobdenotter** [symfony/symfony#31735]
**Symfony version(s) affected**: 4.3.0-stable

After updating to 4.3.0 stable, one of our tests started failing: 

```
There was 1 error:

1) […]\FrontendMenuBuilderTest::testNonExistingMenu
Error: Call to a member function get() on null

/[…]/vendor/symfony/framework-bundle/Console/Application.php:71
/[…]/vendor/symfony/console/Application.php:149
/[…]/tests/php/DbAwareTestCase.php:42
/[…]/tests/php/DbAwareTestCase.php:63
```

I traced it back to the kernel not being 'booted' anymore. My problem was introduced in this commit: https://github.com/symfony/framework-bundle/commit/2c0499210e365bdfe81ae2c56a5a81c5ec687532

On our end, I can fix it by calling `self::$application->getKernel()->boot();` manually, but that feels icky. Am I doing something wrong, or is this a regression in the Console component? 

pinging @chalasr for visibility.

**Comment by chalasr** [comment]
`Kernel::boot()` should still be called by https://github.com/symfony/symfony/blob/299b6264cbf30a7696a821b91f055d6a8835a4bc/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L65. 

Could you try to investigate why, in your test case, the kernel is not booted by this call? 
Maybe your test case shutdowns the kernel between tests while reusing the same application instance across tests?

**Comment by bobdenotter** [comment]
> why, in your test case, the kernel is not booted by this call?

I'm not sure.. You make a valid point that it _should_ be. 

Our code is here: https://github.com/bolt/four/blob/master/tests/php/DbAwareTestCase.php#L45-L59 

The class extends `WebTestCase`, which in turn extends `KernelTestCase`. Eventually, it gets to here, in `symfony/framework-bundle/Test/KernelTestCase.php`: 

```
    protected static function ensureKernelShutdown()
    {
        if (null !== static::$kernel) {
            $container = static::$kernel->getContainer();
            static::$kernel->shutdown();
            if ($container instanceof ResetInterface) {
                $container->reset();
            }
        }
        static::$container = null;
    }
```

So, either the kernel should not shutdown, or if it does, it should also be set to `null`, so in the next test a new one will be created. Apparently, it doesn't do that correctly in my usecase, but i'm not sure why.

**Comment by dpinheiro** [comment]
I'm facing the exact same problem after updating to 4.3, the first test pass but all the other fails. Any update on this?

**Comment by xabbuh** [comment]
@bobdenotter If I don't miss anything, after the first call to `getApplication()` which boots the kernel (through the `createClient()` call) the `$application` property is never set to `null` (which means no further calls to `createClient()` happen). However, inside `tearDown()` the kernel will be shut down. I would have expected that you reset your property to `null` inside `tearDown()`.

**Comment by xabbuh** [comment]
I am closing here as I think that the issues lies in what I wrote in https://github.com/symfony/symfony/issues/31735#issuecomment-511138769. Please comment with a reproducible example application if you disagree. Thank you for understanding.

**Comment by bobdenotter** [comment]
@xabbuh Thanks! And apologies for my non-responsiveness. After I applied the workaround, I hadn't invested more time into this. Seeing there's only one other report, I think we can assume it's no big deal. 😇
