### ISSUE TITLE
[Messenger] messenger:consume command does not use the fallback bus

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony#31741]
**Symfony version(s) affected**: <=4.3.0

**Description**  

Messages coming from non-symfony producers are rejected by the `messenger:consume` command:

```
2019-05-30T16:12:46+00:00 [warning] Message will not be retried because the SentStamp is missing and so the target sender cannot be determined.
2019-05-30T16:12:46+00:00 [critical] Rejecting App\Message\Foo  (removing from transport).
```

The error is a result of the `Symfony\Component\Messenger\Exception\InvalidArgumentException` thrown by `RoutableMessageBus`: 

`Envelope is missing a BusNameStamp and no fallback message bus is configured on RoutableMessageBus.`

My expectation was the message would be routed to the fallback message bus.

**How to reproduce**  

Publish a message outside of Symfony (i.e. from another system, or directly with RabbitMQ admin interface).

Run the `messenger:consume` command without specifying the `--bus` option.

**Possible Solution**  

Either pass the routable message bus which is already registered on the service container, or pass the default message bus to the routable message bus that's created in the `ConsumeMessagesCommand`.

**Additional context**  

The routable message bus is created directly by the `ConsumeMessagesCommand`:

https://github.com/symfony/symfony/blob/94fd42c39652cebb3a2539ac302187ea548b5ac3/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php#L180-L184

It's inconsistent with the way the message bus is registered on the container:

https://github.com/symfony/symfony/blob/2c9a1960a164a857cd551881b580266bc77bdafa/src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml#L107-L111

**Comment by weaverryan** [comment]
Yea, valid. It's annoying that, to support both use-cases of passing `--bus` and *not* passing `--bus`, we kind of need to pass in both the `$busLocator` (as we are now) *and* `messenger.routable_message_bus` to `ConsumeMessagesCommand`.

But, yea, probably we need to add `RoutableMessageBus` as an argument to `ConsumeMessagesCommand`. It's straightforward, but it makes that huge constructor even bigger. One option would be to do it via a setter, and fallback to what we're doing now (instantiating it manually) if it's not set. That would be easy, not break any BC.

**Comment by chalasr** [comment]
See #31748
