### ISSUE TITLE
[FrameworkBundle] Translator not longer available in CompilerPass 

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#31745]
**Symfony version(s) affected**: 4.3.0

**Description**  

I tried to upgrade to symfony 4.3.0 but after that I did got a strange error when it tries to construct to translator service. Instead it give the FrameworkBundle Translator the $container it gives it an empty string so it ends up with a `Symfony\Bundle\FrameworkBundle\Translation\Translator::__construct() must implement interface Psr\Container\ContainerInterface, string given`

After debugging I found out that this come from: https://github.com/symfony/symfony/commit/31d7a09bf5c423ad2003d6863d7372e49a195af1#diff-687bdbb38a4dc672ca2a79f23e764892R110. So the `translator` service seems not longer be available in a custom compiler pass. Maybe this can not be changed but if maybe other run into this error check your compilerpasses. And you need to register it with a lower priority, basically I think it should be avoided accessing of services in compilerpasses:

**How to reproduce**  

Register a compilerpass with default priority which uses the translator service:

```php
    public function process(ContainerBuilder $container)
    {
         $this->container->get('translator');
    }
```

**Possible Solution**  

Currently not sure if this can be changed.

*For the people run into this issues* quickfix change the priority of the compilerpass

```php
$container->addCompilerPass(new YourCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, -33); // Translator should be available here
```

**Additional context**  

<details><summary>Stack Trace</summary>

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Translation\Translator::__construct() must implement interface Psr\Container\ContainerInterface, string given in /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/framework-bundle/Translation/Translator.php:76
Stack trace:
#0 [internal function]: Symfony\Bundle\FrameworkBundle\Translation\Translator->__construct('', Object(Symfony\Component\Translation\Formatter\MessageFormatter), 'en', Array, Array)
#1 /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/dependency-injection/ContainerBuilder.php(1145): ReflectionClass->newInstanceArgs(Array)
#2 /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/dependency-injection/ContainerBuilder.php(612): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'translator.defa...')
#3 /Users/alexand in /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/framework-bundle/Translation/Translator.php on line 76

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Translation\Translator::__construct() must implement interface Psr\Container\ContainerInterface, string given in /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/framework-bundle/Translation/Translator.php:76
Stack trace:
#0 [internal function]: Symfony\Bundle\FrameworkBundle\Translation\Translator->__construct('', Object(Symfony\Component\Translation\Formatter\MessageFormatter), 'en', Array, Array)
#1 /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/dependency-injection/ContainerBuilder.php(1145): ReflectionClass->newInstanceArgs(Array)
#2 /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/dependency-injection/ContainerBuilder.php(612): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'translator.defa...')
#3 /Users/alexand in /Users/alexanderschranz/Documents/Sulu/sulu-develop.localhost/vendor/symfony/framework-bundle/Translation/Translator.php on line 76
```

</details>

**Comment by xabbuh** [comment]
Is your compiler pass calling the `get()` method of the container?

**Comment by alexander-schranz** [comment]
@xabbuh yes `get` is called in the compilerpass function. I know its a bad to access services in the compilerpass and should be avoided. As its possible I think I'm not the only one running in that issue.

I'm also thinking about a new feature in that case having something:

```xml
<service id="translator" class="...">
     <argument type="abstract" />
     <!-- ... -->
</service>
```

So in case a service is accessed which has abstract argument should fail with a better error message instead of trying to call the constructor with empty string.

**Comment by xabbuh** [comment]
I am afraid there is not much we can do here. Using `get()` inside a compiler pass is not supported.

**Comment by alexander-schranz** [comment]
@xabbuh with not supported you mean it should not be done? Because currently it works to access services in compilerpass. So maybe in 5.x it should be changed that the container builder throw an exception when trying to access a service instead of trying to build and return it?

**Comment by xabbuh** [comment]
> with not supported you mean it should not be done?

yes

> So maybe in 5.x it should be changed that the container builder throw an exception when trying to access a service instead of trying to build and return it?

Calling `get()` would be fine if the container has been compiled before or if you know that it's not necessary to compile it and you don't want to do that afterwards. If we can separate that nicely, this looks like a good option to me.

**Comment by linaori** [comment]
@alexander-schranz what do you need the translator service for during a compiler pass? If you want to add resources, you can also configure method calls to configure this instead.

**Comment by alexander-schranz** [comment]
@linaori the compilerpass did generate some meta data from a custom xml's where the translations can be used. So there was nothing added to the translator itself the translator was really used in that compilerpass.

**Comment by xabbuh** [comment]
Doesn't that rather fit in a cache warmer of you are only using a service, but do not modify it?

**Comment by alexander-schranz** [comment]
@xabbuh the metadata is set as a parameter for a service.

**Comment by alexander-schranz** [comment]
@xabbuh a cache warmer would definitly be a better way for this. Feel free to close the issue. My main reason for the issue was that the error is documented here so maybe if somebody else fall into it, they know better what is going wrong and don't need to debug like me. And maybe in future we could get here a better error message for similiar errors when implementing something like abstract arguments (#31769).

**Comment by xabbuh** [comment]
Let's close here then. We already have #31769 to keep track of improving the error. Thank you for your input. :+1:
