### ISSUE TITLE
[Mailer] NullTransport: store messages for verification in tests

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#31747]
**Description**  
When testing, the `NullTransport` in mailer is an attractive thing to use... because it completely disables delivery. But, if it *stored* the messages that were sent to it, then, in functional tests, we could easily fetch the transport from the container and verify its contents. This is what we do for the similar `InMemoruyTransport` in Messenger (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Messenger/Transport/InMemoryTransport.php).

Another option would be to add info to the profiler and use that. I'm not sure which is better - it's always felt a bit awkward to need to enable the profiler whenever I needed to check if emails were sent, but that *is* also its job...

Relates to symfony/symfony#31592

**Comment by derrabus** [comment]
I wouldn't expect a class called `NullTransport` to store anything, tbh. I'd rather introduce another class, something like `BufferingTransport`.

That naming would be consitent with classes we have for logging: Symfony has a `BufferingLogger` that stores log messages in an array while PSR-3's `NullLogger` is just a black hole with a logger interface.

**Comment by weaverryan** [comment]
That’d be fine with me. The larger questions is: is this the way we want to enable testing emails? Or should we use the profiler.

I think we should do this way, as people will already be needing to use this “buffered” or “in memory” transport for their test environments anyways.

**Comment by Kocal** [comment]
Would it be possible to save emails in the filesystem, like SwiftMailer does with [`spool: { type: file }`](https://symfony.com/doc/2.5/cookbook/email/spool.html#spool-using-a-file) ?

**Comment by ajgarlag** [comment]
I've written a quick SwiftMailer bridge for Symfony Mailer using https://github.com/goetas/to-swift-mime-parser, so I can store emails in spools, check them in the profiler, etc., using the standard SwiftMailer integration.

It's available in https://github.com/ajgarlag/AjglSwiftmailerMailer. The problem now is that I cannot add custom transports to the mailer component (#31385), so enabling it is a bit hackish. Any help is welcome.

**Comment by PabloKowalczyk** [comment]
IMO enabling profiler to test e-mails is weird and i really don't like it, also `SwiftMailer`(Bundle) doesn't allow custom transports so it is really pain-in-the-back to test emails in functional tests.
Any attempts to make testing e-mails easier are very welcomed. public `BufferingTransport` service in test environment sounds good to me.

**Comment by ajgarlag** [comment]
@PabloKowalczyk It looks like there is a way to allow custom transports in SwiftMailer, but I've not tested it: https://github.com/symfony/symfony/issues/2460#issuecomment-297853881

**Comment by PabloKowalczyk** [comment]
@ajgarlag if i remember correctly `SwiftMailerBundle` rejects custom transports, also there is no access to transport instance by DI-container.

I would like to do:
```
$bufferedTransport = $container->get(BufferedTransport::class);
$this-assertCount($bufferedTransport->getEmails());
```
and thats it, without any magic, enabling profiler or other weird things.

BTW is there any way to functional test emails sent in `CLI` commands?

**Comment by fabpot** [comment]
I think that testing emails is orthogonal to the transport. See #32930 for an implementation that allows to receive the email AND test it at the same time in functional tests.
