### ISSUE TITLE
Validator recipe includes invalid disable_not_compromised_password option

### ISSUE THREAD

**Issue by jrjohnson** [symfony/symfony#31756]
**Symfony version(s) affected**: 4.3

**Description**  

When creating a new 4.3 application (or updating the recipes in an existing app) `disable_not_compromised_password` gets added to `config/packages/test/validator.yml`, if a functional test is run in that app it will fail with the error:

```
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "disable_not_compromised_password" under "framework.validation". Available options are "auto_mapping", "cache", "email_validation_mode", "enable_annotations", "enabled", "mapping", "not_compromised_password", "static_method", "strict_email", "translation_domain".
```

**How to reproduce**  
Option 1: 
1. Create a new app `composer create-project symfony/website-skeleton new-symfony-43` 
2. add a functional test
3. run `bin/phpunit`.

I created a reproduction of this new app state at:
https://github.com/jrjohnson/symfony-43-validator-reproduction
This looks like a valid and correct 4.3 app to me, but I'm not very familiar with the new app blueprint or process.

Option 2: 
1. Add this configuration to an existing symfony app with functional tests
2. run `bin/phpunit`.

**Additional context**  
This option was added in https://github.com/symfony/symfony/pull/30932
Validator recipe was added in https://github.com/symfony/recipes/pull/567

**Comment by chalasr** [comment]
See https://github.com/symfony/recipes/pull/600.
Thanks for the report. Closing as it needs to be fixed in the recipes repository.
