### ISSUE TITLE
Running simple-phpunit crashes due to autoload.php missing

### ISSUE THREAD

**Issue by Inari-Whitebear** [symfony/symfony#31750]
**Symfony version(s) affected**: 4.x, maybe more

**Description**  
Trying get phpUnit to run I just get a crash:
```
PS E:\Dev\web\phpunit-test> ./vendor/bin/simple-phpunit
INFO: Could not find files for the given pattern(s).
Installing phpunit/phpunit (7.4.5)
Plugins have been disabled.
  - Installing phpunit/phpunit (7.4.5): Loading from cache
Created project in phpunit-7.4
composer.json has been updated
PHP Warning:  proc_open(): CreateProcess failed, error code - 2 in E:\Dev\Web\phpunit-test\vendor\symfony\phpunit-bridge\bin\simple-phpunit.php on line 131
PHP Warning:  proc_close() expects parameter 1 to be resource, bool given in E:\Dev\Web\phpunit-test\vendor\symfony\phpunit-bridge\bin\simple-phpunit.php on line 131
PHP Warning:  require(E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4/vendor/autoload.php): failed to open stream: No such file or directory in E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4\phpunit on line 4
PHP Fatal error:  require(): Failed opening required 'E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4/vendor/autoload.php' (include_path='.;C:\php\pear') in E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4\phpunit on line 4
```

It doesn't seem to actually run a "composer update" or something in `E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4/`, so I have to do that myself.

**How to reproduce**  
Create a new project from website skeleton. Install the phpunit bridge bundle as per https://symfony.com/doc/current/components/phpunit_bridge.html . Try to run `./vendor/bin/simple-phpunit`

Might only happen in Windows/PowerShell or with some composer shell wrapper.

**Possible Solution**  
cd to `E:\Dev\Web\phpunit-test\vendor\bin\.phpunit\phpunit-7.4/` and do `composer update`

**Additional context**  
Might only happen in Windows/PowerShell or with some composer shell wrapper.

**Comment by nicolas-grekas** [comment]
I cannot reproduce but I didn't try on Windows/PowerShell, help wanted from someone that has the issue. Otherwise we'll have to close.

**Comment by misterx** [comment]
I have same error, on Windows 7, PHP 7.2.8
Steps to reproduce:
```
composer create-project symfony/skeleton testunit
cd testunit
composer require --dev symfony/phpunit-bridge
php bin\phpunit
```
Result:
```
INFO: Could not find files for the given pattern(s).
Installing phpunit/phpunit (6.5.14)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.14): Loading from cache
Created project in phpunit-6.5
composer.json has been updated

Warning: proc_open(): CreateProcess failed, error code - 2 in E:\web\_hosts\test.local\symfony\testunit\vendor\symfony\phpunit-bridge\bin\simple-phpunit.php on line 131
Warning: proc_close() expects parameter 1 to be resource, boolean given in E:\web\_hosts\test.local\symfony\testunit\vendor\symfony\phpunit-bridge\bin\simple-phpunit.php on line 131
Warning: require(E:\web\_hosts\test.local\symfony\testunit\bin\.phpunit\phpunit-6.5/vendor/autoload.php): failed to open stream: No such file or directory in E:\web\_hosts\test.local\symfony\testunit\bin\.phpunit\phpunit-6.5\phpunit on line 4
Fatal error: require(): Failed opening required 'E:\web\_hosts\test.local\symfony\testunit\bin\.phpunit\phpunit-6.5/vendor/autoload.php' (include_path='.;C:\php\pear') in E:\web\_hosts\test.local\symfony\testunit\bin\.phpunit\phpunit-6.5\phpunit on line 4
```

**Comment by misterx** [comment]
Looks like problem in `bypass_shell` option in vendor\symfony\phpunit-bridge\bin\simple-phpunit.php  on line 131. Composer runs from composer.bat file and located in some directory on my PC. That directory added into PATH env to execute composer anywhere, but proc_open with bypass_shell option don't know about this directory.  When i set this option to false, phpunit-bridge working fine. 

simple-phpunit use different exec ways, that probably a part of problem. Initially simple-phpunit trying to locate composer by backtick operator (that use cmd.exe and PATH env) on line 94 after that trying run composer by proc_open and bypassing cmd.exe env variables.

**Comment by Rebolon** [comment]
Same problem on windows 10, PHP7.2
It almost works with a WSL (Windows Subsystem Linux)

**Comment by nicolas-grekas** [comment]
@misterx thanks for the hints. Would you be able to submit a patch fixing the issue?

**Comment by antsagithub** [comment]
> Looks like problem in `bypass_shell` option in vendor\symfony\phpunit-bridge\bin\simple-phpunit.php on line 131. Composer runs from composer.bat file and located in some directory on my PC. That directory added into PATH env to execute composer anywhere, but proc_open with bypass_shell option don't know about this directory. When i set this option to false, phpunit-bridge working fine.
> 
> simple-phpunit use different exec ways, that probably a part of problem. Initially simple-phpunit trying to locate composer by backtick operator (that use cmd.exe and PATH env) on line 94 after that trying run composer by proc_open and bypassing cmd.exe env variables.

**Comment by zapo1234** [comment]
c'est chaud je cherche a faire des test unitaire via gitlab ci cd avec docker vendor/bin/phpunit ne se lance pas

**Comment by yanndeo** [comment]
Hi zapo1234 , j'ai le même soucis impocis de jouer les test unitaire via gitlab ci cd avec docker. As tu trouvé une solution depuis lors svp?

**Comment by mfrosch** [comment]
Error 404 - French not found ;)
I also get following on composer update:
```
In BinaryInstaller.php line 207:
                                                                                                                
  file_put_contents(/var/www/html/vendor/bin/simple-phpunit): failed to open stream: No such file or directory  
```
Is there some solution?

Cheers
