### ISSUE TITLE
[Security] 4.3 Always "Bad credentials." with algorithm "auto"

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#31758]
**Symfony version(s) affected**: 4.3.0

**Description**  
Previosly encoded password becomes invalid. All of them started with "$2y$13$" which means "bcrypt wit cost 13" I think.

**How to reproduce**  
Create user with "bcrypt" password encoder, change encoder to "auto" and try to login.

**Additional context**  
I use doctrine entity user provider.
PHP 7.2.17 no sodium installed

**Comment by kralos** [comment]
I can confirm.

call stack:

* `Symfony\Component\Security\Core\Encoder\EncoderFactory::getEncoderConfigFromAlgorithm`
* `Symfony\Component\Security\Core\Encoder\EncoderFactory::createEncoder`
* `Symfony\Component\Security\Core\Encoder\EncoderFactory::getEncoder`
* `Symfony\Component\Security\Core\Authentication\Provider\*AuthenticationProvider::checkAuthentication`'s
* ....


`EncoderFactory::getEncoderConfigFromAlgorithm`
```php
if ('auto' === $config['algorithm']) {
$config['algorithm'] = SodiumPasswordEncoder::isSupported() ? 'sodium' : 'native';
}
/**/
```

so if your `user.password` is hashed with `sha256` or `bcrypt` or whatever, it will be validated against either `sodium` or `native`

**Comment by kralos** [comment]
I would suggest everyone ignores the deprecations like:

> Configuring an encoder with "xxx" as algorithm is deprecated since Symfony 4.3, use "auto" instead.

Instead just leave your actual algorithm configured. Once this issue is fixed you should be able to switch to "auto".

**Comment by zorn-v** [comment]
"native" works fine. Maybe change deprecation text to `use "auto" or "native" instead` ?
Seems `SodiumPasswordEncoder::isSupported()` does not work as expected

**Comment by kralos** [comment]
I have `sha512` passwords and `native` doesn't work for me.
I also have `bcrypt` passwords and `native` does work.

**Comment by nicolas-grekas** [comment]
sodium can't validate bcrypt passwords, that's the issue.
of course you can't move from sha512 to auto/native/sodium without a migration plan (one will be provide in 4.4)

**Comment by schefpet** [comment]
And what about to fix it here? https://github.com/symfony/security/blob/master/Core/Encoder/SodiumPasswordEncoder.php

Do you fix everything also in separated components? Because right now it seems to be dangerous to use separated componenst. They maybe miss more than this fix. Thank you

**Comment by rbaarsma** [comment]
@chalasr Why close this issue? It's extremely annoying to have a deprecation that you can't fix. Either it should not yet be deprecated in Symfony 4.3 (but rather in deprecated in Symfony 4.4, when a solution is present to migrate passwords), or the UPGRADE doc should offer some solution to do the migration of passwords manually.

I wouldn't know where to start migrations the passwords and am stuck with this deprecation, which is breaking my automated tests.. I think it's a valid issue that needs some kind of solution.

**Comment by rbaarsma** [comment]
Oh I missed your commit at first. Perhaps it's because the `bcrypt` issue was solved. But I'm using `argon2i`, the Symfony 4.2 standard. Would it perhaps be as simple as add a similar commit for argon2i hashed password?

**Comment by tomasfejfar** [comment]
Was adding bcrypt to SodiumPasswordEncoder the correct way to fix things? Now you create SodiumPasswordEncoder in expectation that it either validates the hash using sodium or fails. But alas! It will also validate bcrypt hashes. That MAY result in unexpected behavior. Imagine that there are legacy users that are not supposed to log in as their passwords may be compromised. I did that by changing hashing to libsodium. But now with 4.3.1 they magically can login again even though SodiumPasswordEncoder is still used. It's fine as "hotfix", but if anyone is using the encoder in isolation they would be quite surprised at the new behavior. 

I think the correct behavior would be to add a "BestPasswordEncoder" encoder that would have the selection algorithm baked in. It would just use what's currently best AND appropriate for the current password. Instantiating all the encoders should not be much of a problem as password validation is supposed to be slow anyway.
