### ISSUE TITLE
getenv return false with symfony/dotenv 4.3

### ISSUE THREAD

**Issue by juanantoniomosquera** [symfony/symfony#31765]
Symfony version(s) affected: 4.3

Description
I upgrade symfony to 4.3 and getenv('APP_ENV') return false. If I downgrade only dotenv component works fine.

How to reproduce
Upgrade to 4.3

How can I fix this?

Thanks!

**Comment by juanantoniomosquera** [comment]
Solved: 

Change behavior of Dotenv

> Dotenv
> First parameter of Dotenv::__construct() will be changed from true to false in Symfony 5.0. A deprecation warning is triggered if no parameter is provided. Use $usePutenv = true to upgrade without breaking changes.

I need to change in bootstrap.php

`(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');  `
for
`(new Dotenv(true))->loadEnv(dirname(__DIR__).'/.env');  `

_By default in new installations is FALSE_ 

Thanks.

**Comment by nicolas-grekas** [comment]
Note that doing so is not recommended.
You'd better inject the values using %env()%

**Comment by MarcDiaz** [comment]
@nicolas-grekas 
I am not a Symfony expert yet. Can you tell me where we must put the %env()% for the `usePutenv` argument? In a `config/dotenv.yaml` file?

Thank you in advance.

**Comment by nicolas-grekas** [comment]
Dotenv is configured in config/bootstrap.php
For using references to env vars, see https://symfony.com/doc/current/configuration.html#config-env-vars

**Comment by viion** [comment]
Sorry to bump, but why is this not recommended and how are you supposed to get environment variables now? Before all I had to do was `get_env('APP_ENV')` or whatever else.

The linked document is absolutely useless I'm sorry to say, it doesn't explain at all how to retrieve those env variables in your services (especially when auto wired)

**Comment by kinucris** [comment]
> Solved:
> 
> Change behavior of Dotenv
> 
> > Dotenv
> > First parameter of Dotenv::__construct() will be changed from true to false in Symfony 5.0. A deprecation warning is triggered if no parameter is provided. Use $usePutenv = true to upgrade without breaking changes.
> 
> I need to change in bootstrap.php
> 
> `(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env'); `
> for
> `(new Dotenv(true))->loadEnv(dirname(__DIR__).'/.env'); `
> 
> _By default in new installations is FALSE_
> 
> Thanks.

Hello I change my _bootstrap.php_ but does working ::sad::

change this:
    `(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');`
for then:
    `(new Dotenv(true))->loadEnv(dirname(__DIR__) . '/.env');`

**Comment by leocavalcante** [comment]
@kinucris,
newer versions of the library does not receive the `$usePutenv` argument on the constructor anymore, you have to call the `usePutenv()` method.

```php
(new Dotenv())->usePutenv()->loadEnv(__DIR__ . '/.env');
```
