### ISSUE TITLE
Symfony 4.3 "test.client" service is not an instance of Symfony\Bundle\FrameworkBundle\Client

### ISSUE THREAD

**Issue by pamil** [symfony/symfony#31762]
**Symfony version(s) affected**: 4.3.0

**Description**  

Prior to 4.3.0, `test.client` used to be an instance of `Symfony\Bundle\FrameworkBundle\Client`.
In 4.3.0, it becomes `Symfony\Bundle\FrameworkBundle\KernelBrowser` which does not extend `Symfony\Bundle\FrameworkBundle\Client` anymore.

Because of the lack of interfaces, there was no other possibility to typehint it than to use the class name.

I saw `Symfony\Component\BrowserKit\Client` has been deprecated but it's still used, is it possible to do the same with FrameworkBundle's Client?

**Comment by alexislefebvre** [comment]
See also #31653

**Comment by lyrixx** [comment]
And BTW, the return value of `self::createClient();` has changed in the same way. I think this is a BC break too

**Comment by alexislefebvre** [comment]
This looks similar to #31653: type hint and return values of the `client` property have changed.

**Comment by nicolas-grekas** [comment]
See #31881
