### ISSUE TITLE
[RFC] [DI] Abstract arguments

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony#31769]
**Description**  

As run into an issue #31745 I come with an idea of adding a new type for arguments called `abstract`. The idea is to have a better error message when a compilerpass need to replace an argument and it did not happened. 

**Example**  

For example the `translator.default` service:

https://github.com/symfony/symfony/blob/9934252f2fae7794f623e9032c67e1512a729716/src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.xml#L10-L13

has a argument which need to be replaced. So service definition would look like the following:

```xml
 <service id="translator.default" class="Symfony\Bundle\FrameworkBundle\Translation\Translator"> 
     <argument type="abstract">Should be defined by TranslatorPass</argument>
     <!-- ... -->
```

So when there exist an abstract argument it should error with e.g. `Argument "0" is not replaced for service "translator.default" yet: Should be defined by TranslatorPass`.

**Comment by linaori** [comment]
I like this, it ensures nothing is missed, changing the error from run-time to compile-time

**Comment by nicolas-grekas** [comment]
@alexander-schranz up for a PR?
