### ISSUE TITLE
[HttpClient] Support invalid Location header

### ISSUE THREAD

**Issue by mleczakm** [symfony/symfony#31776]
**Symfony version(s) affected**: 4.3.0

**Description**  
Curl http client try to parse `Location` header even if no redirects allowed, which makes unable to get response/headers value from endpoint which returns invalid url in `Location` header.

**How to reproduce**  
```
use Symfony\Component\HttpClient\CurlHttpClient;

// uses the cURL PHP extension
$httpClient = new CurlHttpClient();
$response = $httpClient->request('HEAD', 'http://test.mleczko.waw.pl', ['max_redirects' => 0]);
```
Results in `InvalidArgumentException Malformed URL ...`, no way to use value of this header.

**Possible Solution**  
Simply check if we are gonna use `Location` value as redirect target - https://github.com/mleczakm/symfony/commit/5c27013e6b1c8f710821019f1ec64fc29f034d3b

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR with the change and a test case please? Please check the result of calling getInfo(redirect_url)
Also, what's the point of replying with invalid location headers?

**Comment by mleczakm** [comment]
It's not me who are replying, it is api which works like that, probably to make it works with HEAD request - but I still don't know why someone choose `Location` header instead of something custom. Anyway, throwing error on invalid location when you don't gonna use it still seems buggy to me.

**Comment by mleczakm** [comment]
I've decided to close this issue, since implementing it is definitely not worth it - I've used plain curl requests for this edge-case and got confirmed what I've been thinking before - http standards should never be broken :)

**Comment by nicolas-grekas** [comment]
I decided to fix it :)
See #31834
