### ISSUE TITLE
Switching security algorithm from bcrypt to auto breaks existing passwords

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#31770]
**Symfony version(s) affected**: 4.3.0

UPGRADE-4.3 says:
> Configuring encoders using argon2i or bcrypt as algorithm has been deprecated, **use auto instead.**

After changing to auto, all the existing users (with the password starting with "$2y$13$..." can't login anymore. 

Shouldn't `auto` accept also previously stored passwords?

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/issues/31758#issuecomment-497632492

**Comment by yceruto** [comment]
Also seems related to https://github.com/symfony/symfony/pull/31763

**Comment by fmonts** [comment]
Yep. So it's already fixed in 4.3.1. Thank you
