### ISSUE TITLE
[Messenger] Redis Transport does not create a stream

### ISSUE THREAD

**Issue by desmax** [symfony/symfony#31791]
**Symfony version(s) affected**: 4.3

**Description**  
Redis transport does not create a stream and when messenger tries to consume messages it fails with `NOGROUP No such key 'msgssls' or consumer group 'symfony' in XREADGROUP with GROUP option`

although line `$this->connection->xgroup('CREATE', $this->stream, $this->group, 0, true);` is executed in Symfony\Component\Messenger\Transport\RedisExt\Connection
no command is issued in redis.

If I create stream manually like this `"XGROUP" "CREATE" "msgssls" "symfony" "0" "MKSTREAM"` it processes 1 message and then gives Segmentation fault.

This works fine on my mac, but fails on debian server.

**Comment by desmax** [comment]
if I remove last argument from `$this->connection->xgroup('CREATE', $this->stream, $this->group, 0, true);` segmentation goes away. But I still have to create stream manually.

what does that argument mean? I don't see it in the arguments list

**Comment by chalasr** [comment]
What is the version of redis and phpredis installed on your debian server?

**Comment by desmax** [comment]
@chalasr redis is 5.0.3, php and php-redis extension is 7.3.6

**Comment by chalasr** [comment]
Ok, same issue, unable to upgrade to 4.3 in production. Probably related to https://github.com/oerdnj/deb.sury.org/issues/1184

**Comment by chalasr** [comment]
Confirmed, the transport works fine with phpredis 4.3 but produces segfault with phpredis 4.2. I'm going to add a conflict rule to the component composer.json.
And we will need to wait for oerdnj/deb.sury.org#1184, +1 welcome there.
