### ISSUE TITLE
[PropertyInfo] [Validator] the new auto mapping is not working with non found property

### ISSUE THREAD

**Issue by elhadraoui** [symfony/symfony#31796]
**Symfony version(s) affected**: 4.3.0

**Description**  
When we are using a function like `public function addSomething()` and no property with name: `something` not existing the exception "The entity has no field with name ..." is thrown.

**How to reproduce**  
Create an entity with function `addSomething()` without property `something` and enable the auto mapping for validation.

**Possible Solution**  

**Additional context**

**Comment by cronk1986** [comment]
Today I updated Symfony 4.2 to 4.3 and now I can't save entities that implement Interfaces or use traits, Mapping/PropertyMetadata class try to find a property in a interface and throw an error, my code snippet:

```php
interface GetterIdInterface
{
  public function getId();
}
```

```php
class MyEntity implements GetterIdInterface
{

    /**
     * @var string
     *
     * @ORM\Column(name="id", type="guid", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     */
    protected $title;

    public function getId()
    {
        return $this->id;
    } 

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return MyEntity
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    } 
 
}
```
```php
//When I try to save MyEntity throw an exception:
...
$entity = new MyEntity();
$em->persist($entity);
$em->flush();
...
```

```
Property "title" does not exist in class "GetterIdInterface"

Symfony\Component\Validator\Exception\ValidatorException in vendor/symfony/validator/Mapping/PropertyMetadata.php (line 40)
 /* @throws ValidatorException     */    
public function __construct(string $class, string $name)    
{        
    if (!property_exists($class, $name)) {            
        throw new ValidatorException(sprintf('Property "%s" does not exist in class "%s"', $name, $class));        
    }        
    parent::__construct($class, $name, $name);    
}
```

any idea?

**Comment by linaori** [comment]
Is this issue related to #31715?

**Comment by cronk1986** [comment]
I don't know if it's exactly the same, because I can save all my entities if they not  implement an Interface o use Traits... 
At the end maybe is the same issue.

**Comment by Aerendir** [comment]
The `PropertyInfo` causes a lot of troubles: it tries to guess properties starting from methods: this causes a lot of strange behaviors. Not strictly related to this, this is another example: https://github.com/php-translation/symfony-bundle/issues/309

**Comment by weaverryan** [comment]
I can confirm this, here is a simple reproducer: https://github.com/weaverryan/symfony-automapper-reproducer - you can see the simple steps in the history:

1) install validator & property-info 
2) Create a public setter method in `src/Entity` without a corresponding property
3) Try to validate it (e.g. go to `/` in the reproducer):

<img width="768" alt="Screen Shot 2019-06-07 at 11 13 06 AM" src="https://user-images.githubusercontent.com/121003/59114482-40715b00-8915-11e9-8000-169fd27ae70b.png">

**Comment by cronk1986** [comment]
Perfect, now works! 
Thank you!
