### ISSUE TITLE
[DotEnv] Env Vars per environment Priority

### ISSUE THREAD

**Issue by DavG** [symfony/symfony#31808]
**Symfony version(s) affected**: 4.2.9

**Description**  
Hello, this issue is not exactly the same than #31579 because I will not use "real environment variable" here. I will use 100% dotenv only.
Just following the order in https://symfony.com/blog/new-in-symfony-4-2-define-env-vars-per-environment

**How to reproduce**  
.env.dev.local : MY_VAR=1
.env.local : MY_VAR=2
.env.dev : MY_VAR=3
.env : MY_VAR=4

In PHP, I will see "MY_VAR=1", ok, perfect.
Then If I comment/remove the line in .env.dev.local, I would expect to see MY_VAR=2
But I see MY_VAR=3

**Comment by nicolas-grekas** [comment]
The blog post is wrong /cc @javiereguiluz 
See https://github.com/symfony/recipes/blob/master/symfony/flex/1.0/.env for correct order.
If you see the same mistake in the doc, please open a PR to fix it.

**Comment by DavG** [comment]
Ok I see.
Thank you !
