### ISSUE TITLE
[Security] Should an encoder be mandatory?

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony#31806]
Hello there,

In the case of:

- An implementation of `Symfony\Component\Security\Core\User\UserInterface` where `getPassword()` always returns `null` (because users are stored outside of the app without exposing the password, even hashed)
- A guard is able to check the password validity through the `checkCredentials()` method (thus performing a request to a 3rd-party API with the provided credentials)

Then why is an encoder mandatory?

In my use case:
- Users cannot be created from the app, they can only be retrieved, so I don't need the `PasswordEncoderInterface::encodePassword()` logic
- The guard is responsible to check the password validity through the `checkCredentials()` method, so I shouldn't need to implement `PasswordEncoderInterface::isPasswordValid`(which is not user-aware, by the way).

Despite all of this, `DaoAuthenticationProvider` keeps getting called and throws a `No encoder has been configured for account App\Entity\User` exception, although my guard successfully handled authentication success / failure.

Shouldn't we allow the case of an User not having an encoder? Or should we provide a `none` encoder, which would do nothing on `encodePassword()` and always return `true` on `isPasswordValid()`?

Thank you,
Ben

**Comment by linaori** [comment]
> Despite all of this, DaoAuthenticationProvider keeps getting called and throws a No encoder has been configured for account App\Entity\User exception, although my guard successfully handled authentication success / failure.

I will advice to stay away from the DaoAuthenticator for reasons as such.

> Shouldn't we allow the case of an User not having an encoder?

An encoder is only required when a password needs hashing. The name is wrong, probably something to pick up for 4.4/5.0 while working on the security component /cc @chalasr

Not all users have passwords, public/private keys or API keys/tokens are not passwords and thus this should be optional.

**Comment by bpolaszek** [comment]
> I will advice to stay away from the DaoAuthenticator for reasons as such.

It looks like I just can't: even if I successfully handled the authentication by myself, it's getting called just afterwards. Or am I missing something?

> Not all users have passwords, public/private keys or API keys/tokens are not passwords and thus this should be optional.

When a user doesn't need a password, the encoder doesn't have to be defined and it's fine. The problem is, when a user needs a password, but password encoding/checking can't be done through the application itself (when connecting the security component to a Saas software, which is my use case).

**Comment by bpolaszek** [comment]
After investigating further:

* Setting up something like a `NullPasswordEncoder` (`algorithm: none`) is actually a very bad idea because some services like `DaoAuthenticationProvider` rely on `PasswordEncoderInterface::isPasswordValid` after the user has been retrieved, to assert that the provided credentials are valid. If we set up a `NullPasswordEncoder::isPasswordValid` which always returns `true`, we're going right into the wall.

So let's give up this.

Let's sum up the issue differently.
When I send a POST request to `/api/login` containing `{"username":"foo", "password": "123456"}` 

- Symfony's `AuthenticationProviderManager` inits the authentication chain and loops through authentication providers.
    - Symfony's `GuardAuthenticationProvider` iterate over guards.
        - My own `ApiAuthenticator` retrieves the correpsonding user through `ApiAuthenticator:: getUser()` 
        - My own `ApiAuthenticator` checks the password validity through `ApiAuthenticator:: checkCredentials()`
   - Symfony's `DaoAuthenticationProvider` is getting called
   - The loop continues

The problem is that `DaoAuthenticationProvider` relies on _encoders_ to tell whether or not the provided password is valid, despite the fact that my `ApiAuthenticator` was called earlier and already asserted that the credentials were right or wrong. How can I prevent this behavior?

**Comment by linaori** [comment]
> It looks like I just can't: even if I successfully handled the authentication by myself, it's getting called just afterwards. Or am I missing something?

You can replace the `DaoAuthenticator` by the guard one.

**Comment by bpolaszek** [comment]
When using a `json_login` authentication, the `DaoAuthenticator` gets called despite the presence of the guard (it gets called just afterwards).
I ended in not using `json_login` at all and rewrote the whole thing to make it work. Thank you @linaori!
