### ISSUE TITLE
symfony/contracts v.1.1.1 incompatible with Symfony 4.3

### ISSUE THREAD

**Issue by keulinho** [symfony/symfony#31801]
**Symfony version(s) affected**: 4.3, symfony/contracts 1.1.1

**Description**  
symfony/translation v4.3 requires the translation-contracts in v1.1.2, 
this is problematic if you require the contracts via the general package symfony/contracts,
because that is only available in v1.1.1.

**How to reproduce**  
Try to install the translation component in v.4.3 and symfony contracts in v.1.1.1.

**Possible Solution**  
As a workarounf you can install symfony/contracts in v1.1.0, but this gives you multiple ambigiuous class resolution warnings.
The real solution would be to bump the symfony/contracts to v1.1.2.

**Comment by nicolas-grekas** [comment]
v1.1.2 now taggued thanks @fabpot 
Btw, you'd better reference individual contracts no I think.
