### ISSUE TITLE
MissingResourceException Locales::getName

### ISSUE THREAD

**Issue by Audax23** [symfony/symfony#31817]
Hello,
Obviously when I use Locales::getName($value) instead of Intl::getLocaleBundle()->getLocaleName($value) on symfony 4.3, I get an Intl exception when the value is empty.
example with Locales::getName('ar_001')
did I miss something? is this a bug?
thank you for your answer.

$builder
     ->add('locale', ChoiceType::class, array(
         'label' => 'label.locale',
         'choices' => Locales::getLocales() ,
         'choice_label' => function ($value) {
             return Locales::getName($value);
         }
     ))

Couldn't read the indices [Names][ar_001] for the locale "fr" in "/var/www/mysite/vendor/symfony/intl/Resources/data/locales". The indices also couldn't be found for the fallback locale(s) "en", "root".

**Comment by pierredup** [comment]
Can you try with

```
$builder->add('locale', ChoiceType::class, array(
    'label' => 'label.locale',
    'choices' => array_flip(Locales::getNames())
))
```

`Locales::getNames()` should return you a list of all the valid locales, including the corresponding name (so that you don't need to do the `Locales::getName($value)` name)

**Comment by Audax23** [comment]
no, I did not think about it.
error has disappeared, thank you very much.
thanks again!
