### ISSUE TITLE
symfony 4.2.9 with test-pack will not upgrade to phpunit 7.5

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#31816]
**Symfony version(s) affected**: 4.*

**Description**  
Although the documentation is very scarce (possibly feature request), I found that I should add `SYMFONY_PHPUNIT_VERSION=7.5` to my `.env.test`, so that phpunit bridge automatically updates the phpunit version.

Unfortunately this does not work.

**How to reproduce**  
```
(inside docker-compose with php 7.2)
bash$ composer create-project symfony/website-skeleton my-project
bash$ cd my-project
bash$ echo 'SYMFONY_PHPUNIT_VERSION=7.5' >> .env.test
bash$ bin/phpunit
```
--> expected to install 7.5, but installs 6.5 instead.

**Possible Solution**  
?

**Additional context**  
see https://stackoverflow.com/questions/55272513/how-to-upgrade-symfony-phpunit-bridge-to-use-phpunit-7

Strangely it does seem to work to add SYMFONY_PHPUNIT_VERSION=7.5 as a global env var in docker-compose. That may lead you to the problem, but of course is not a real solution.

**Comment by nicolas-grekas** [comment]
`.env.test` doesn't work as it is loaded to late in the bootstrapping process.
Using a real env var should work (please debug why if not)
setting the version in phpunit.xml.dist should work too.

**Comment by rbaarsma** [comment]
@nicolas-grekas As stated in the report, a real ENV var (such as directly in docker container) does indeed work. Unfortunately it doesn't work in the `phpunit.xml.dist`. Since we have env config for different parts of the CI, it feels dirty to put this env var in several different Dockerfile's.. if it's supposed to work from the `phpunit.xml.dist`, then there's clearly some problem.

```
        <env name="SYMFONY_PHPUNIT_VERSION" value="7.5" />
```

**Comment by nicolas-grekas** [comment]
Because it creates real env vars, the `bin/phpunit` script disables reading `phpunit.xml.dist` files:
https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/4.3/bin/phpunit

https://github.com/symfony/symfony/blob/926ded8ea5017cb8aaba834f418d1c8d8337dabc/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L18

Dunno how/if/where this should be tweaked.

**Comment by rbaarsma** [comment]
Since it's already a phpunit-bridge from symfony, what about actually loading `.env.test` in the `bin/phpunit` file?

**Comment by rbaarsma** [comment]
BTW in `/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php` the default version of phpunit for php version > 7.1 is actually 7.4, which would suit me just fine. However it's overwritten to 6.5 by the recipe you posted. So if that default wasn't there, all would be well too.

**Comment by nicolas-grekas** [comment]
This file is yours, you can and should update it. Loading .env files is already done, but cannot be used for this specific env var because it is needed way earlier.

**Comment by rbaarsma** [comment]
Right then, if there's no easy solution, it could possibly be a documentation tweak to make clear you should edit the `bin/phpunit` file OR provide an env variable outside of the `.env.test` and `phpunit.xml` (because both are apparently too late).

So perhaps change the status to clarify documentation? Or simply close.. I have a solution now. Thanks!

**Comment by nicolas-grekas** [comment]
Understood, see https://github.com/symfony/recipes/pull/606!

**Comment by patrickvale** [comment]
Hi, I'm just updating the docs for this. Can I clarify that the situation is:

- You cannot set the phpunit version by adding or altering the `SYMFONY_PHPUNIT_VERSION` variable in phpunit.xml.dist eg `<server name="SYMFONY_PHPUNIT_VERSION" value="6.5" />` 
- You can set the phpunit version by setting a real (not dotenv) Environment variable, for example by passing `SYMFONY_PHPUNIT_VERSION=6.5` in a docker-compose file
- You can set the phpunit version by editing `bin/phpunit` (could you clarify how to do this as `$PHPUNIT_VERSION` seems to be explicitly set in `/vendor/symfony/phpunit-bridge/bin/simple-phpunit`?)

Thanks :+1:

**Comment by nicolas-grekas** [comment]
* you CAN set the version using phpunit.xml files, that's how recipes do it
* real env var yes
* it's been removed from bin/phupnit, so no for this item (see linked PR above)

**Comment by rbaarsma** [comment]
@nicolas-grekas if you CAN set the version using the phpunit.xml files, then how come I am unable to do that? Setting `<env name="SYMFONY_PHPUNIT_VERSION" value="7.5" force="true" />` in the `<php>` section does not work, nor does it work if I use `force="true"`. Can you clarify?

@patrickvale  The way you can override this in the `bin/phpunit` - the way I fixed my issue - is by simply setting `putenv('SYMFONY_PHPUNIT_VERSION=7.5');` (or any other version) in that file somewhere before the `require` of the simple-phpunit from phpunit-bridge

**Comment by nicolas-grekas** [comment]
try with `<server>` instead of `<env>`?

**Comment by rbaarsma** [comment]
Nope it's now:

```
    <php>
        <server name="SYMFONY_PHPUNIT_VERSION" value="7.5" />
    </php>
```

Still installs the default version

**Comment by rbaarsma** [comment]
It makes sense, since phpunit.xml(.dist) is not loaded yet in simple-phpunit at this point, right?

**Comment by nicolas-grekas** [comment]
It should because of these lines:
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L17-L48

But this code doesn't honor the "force" attribute so that might be the reason. PR welcome if you want to fix this, branch 4.2.

**Comment by patrickvale** [comment]
@rbaarsma thanks - that makes sense re. where to set the version in `bin/phpunit`.

I've created a sandbox repo with just symfony/website-skeleton and docker instructions to change and test the version installed by phpunit bridge here https://github.com/patrickvale/set-phpunit-version which does seem to be working as expected (changing the value of `<server name="SYMFONY_PHPUNIT_VERSION" value="7.5" />` does change the version installed.

**Comment by fahimbinkhair** [comment]
It was not very nice but I have deleted bin/.phpunit and bin/phpunit then it installed the v7.5
