### ISSUE TITLE
RoleHierarchyInterface doesn't contain any methods.

### ISSUE THREAD

**Issue by polyakov84** [symfony/symfony#31814]
**Symfony version(s) affected**: 4.3

**Description**  
RoleHierarchyInterface doesn't contain any methods.

Comment said "The getReachableRoles(Role[] $roles) method that returns an array of all reachable Role objects is deprecated
  since Symfony 4.3."
And we should use method "getReachableRoleNames" or something else.

BUT RoleHierarchyInterface is empty.
I couldn't make a mock from it.

**Comment by polyakov84** [comment]
So for now old method removed instead of to be marked as deprecated.
And no any new methods available until 5.0

I've got the next error in PHPUnit tests.
"Trying to configure method "getReachableRoles" which cannot be configured because it does not exist, has not been specified, is final, or is static"

And, as I understand, there is no other methods that could be used and exists in this interface.
And this interface is useless until version 5.0

**Comment by polyakov84** [comment]
Why this method has been already removed.
Comment in implementation said that it should be removed in version 5.0, but not in 4.3.

**Comment by xabbuh** [comment]
https://github.com/symfony/symfony/pull/30388#discussion_r260733287 contains some more information

**Comment by teohhanhui** [comment]
Removing a method from an interface is a BC break. It causes exceptions such as:

> Prophecy\Exception\Doubler\MethodNotFoundException: Method `Double\RoleHierarchyInterface\P19::getReachableRoles()` is not defined.

**Comment by nicolas-grekas** [comment]
That's only an issue for mocks, not for real code.
You might need to create a `TestRoleHierarchyInterface` that extends the native one with the added method.
I did something similar in https://github.com/symfony/symfony/pull/31597/files#diff-13b6c6ea7cdaba73a859c38af4231fd6R70 (for another reason)
That could as well be considered an issue with mocking libraries. It would actually be great if they could handle `@method` annotations or similar.

No bug here to me.

**Comment by lyrixx** [comment]
For what it worth, I stop mocking `RoleHierarchyInterface` and start using `RoleHierarchy` without mock. Simpler!
https://github.com/symfony/symfony/pull/31824/files#diff-953a0eb8ac77c56ed64c155b3c5789feR45

**Comment by teohhanhui** [comment]
Mocking is just one of the ways that the problem would manifest itself.

Consider this, it was a real method defined on the interface before, as far as PHP is concerned. In other words, causing the return value of `method_exists` to be changed is a BC break.

**Comment by teohhanhui** [comment]
Adding a new method that only exists in PHPDoc `@method` is fine. Removing an existing defined "real" method is not.

**Comment by Tobion** [comment]
According to https://symfony.com/doc/current/contributing/code/bc.html#changing-interfaces @teohhanhui is right.

**Comment by Tobion** [comment]
I think we can close this as it's solved in 5.0 and people shouldn't need to mock the interface as explained in https://github.com/symfony/symfony/issues/31814#issuecomment-498758158
