### ISSUE TITLE
[mailgun-mailer] support EU-endpoint

### ISSUE THREAD

**Issue by cklm** [symfony/symfony#31810]
Currently `symfony/mailgun-mailer` supports only the US-enpoint, but not the EU-endpoint.

Basically, the endpoint needs to be changed from `api.mailgun.net` to `api.eu.mailgun.net` (see [regions in mailgun-documentation](https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions). There should be an option in the dsn to switch from us to eu.

**Comment by fabpot** [comment]
Can you report the same on symfony/symfony instead? Also, would you want to work on a pull request to introduce such a feature?

**Comment by 1bastien1** [comment]
I'm beginner on github's issue but i "know" how symphony works because i used it sometimes. Can i have a indication ?

**Comment by bullder** [comment]
> Would you want to work on a pull request to introduce such a feature?

https://github.com/symfony/mailgun-mailer/pull/1

**Comment by 1bastien1** [comment]
> > Would you want to work on a pull request to introduce such a feature?
> 
> [symfony/mailgun-mailer#1](https://github.com/symfony/mailgun-mailer/pull/1)

already done ?

**Comment by bullder** [comment]
> already done ?

kinda done

**Comment by 1bastien1** [comment]
> > already done ?
> 
> kinda done

alright

**Comment by xabbuh** [comment]
@bullder Can you recreate the PR in this repository? The other one is just a subtree split that is automatically synchronised with this repository.

**Comment by bullder** [comment]
> @bullder Can you recreate the PR in this repository? The other one is just a subtree split that is automatically synchronised with this repository.

https://github.com/symfony/symfony/pull/31897
