### ISSUE TITLE
WorkerMessageReceivedEvent is not triggering

### ISSUE THREAD

**Issue by hamidudc** [symfony/symfony#31826]
**Symfony version(s) affected**: 4.3

**Description**  
I'v try to set a WorkerMessageReceivedEvent subscriber but never dispatch.

```
class UniqueRoleAliasCheckerService implements EventSubscriberInterface {

    public function handle( $message ) {
        var_dump('111111');
    }

    public static function getSubscribedEvents() {
        return [ 'WorkerMessageReceivedEvent' => 'handle' ];
    }
}

**Comment by Tobion** [comment]
You need to subscribe to the FQCN of `Symfony\Component\Messenger\Event\WorkerMessageReceivedEvent`

**Comment by hamidudc** [comment]
Tnx 

> You need to subscribe to the FQCN of `Symfony\Component\Messenger\Event\WorkerMessageReceivedEvent`

Thanks . Does symfony has any pre handler event?

**Comment by Tobion** [comment]
You might want to look at the messenger middleware concept.
