### ISSUE TITLE
SyncTransport dosent meet Messenger Events

### ISSUE THREAD

**Issue by hamidudc** [symfony/symfony#31830]
**Symfony version(s) affected**: 4.3

I want to call a service after dispatching a command and before handling same command and try to use sync transport but event dose not trigger . (something like preHandler hook)

```
class TestMessageSubscriber implements EventSubscriberInterface {

    public function handle( $message ) {
        var_dump('11111111111');
        die();
    }

    public static function getSubscribedEvents() {
        return [ WorkerMessageReceivedEvent::class => 'handle' ];
    }
}```


            sync: 'sync://'
        routing:
            'App\Domain\Shared\Aggregate\DomainEventInterface': amqp
            'App\Domain\Shared\Aggregate\CommandInterface': sync

```

**Comment by Tobion** [comment]
The events are only triggered by the worker. If you don't run a worker, there are no events. I would also recommend to solve your case with middlware as I said in #31826

Also for support questions please use one of the methods in https://symfony.com/support
