### ISSUE TITLE
Twig extensions are loaded in an uncertain order // App services are loaded after bundles ones

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#31841]
**Symfony version(s) affected**: 3.4+ to 4.3

**Description**  

In older version of symfony, It was easy to override a twig function or twig filter. We had to create a new extension, register it as a service, override a filter/function, and it was done.

It worked because services were registered bundles per bundles, then the tag extraction kept the same order. And since the "AppBundle" was usually the last bundle to be registered, its services were registered lastly. And so the overriding works as expected.

**How to reproduce**  

1. create a new project
2. `composer req jbouzekri/phumbor-bundle`
3. `composer make:twig Phumbor`
    ```php
    class PhumborExtension extends AbstractExtension
    {
        public function getFilters(): array
        {
            return [
                new TwigFilter('thumbor', [$this, 'thumbor']),
            ];
        }

        public function thumbor($value)
        {
            return 'from MY ext';
            // ...
        }
    }
    ```
4. use the `thumbor` filter in a template
5. observe that `form MY ext` it not displayed

**Possible Solution**  

I did not check
Register app service after bundle ones?

**Additional context**  

Everything is done on https://github.com/symfony/symfony/blob/491c0d549e61b0667841e7e49fd2b6fcc130f1ab/src/Symfony/Component/HttpKernel/Kernel.php#L549-L550

The microkernel does not "lazy load" definition. `Kernel::buildContainer()` -> `Kernel::registerContainerConfiguration()` -> `AppKernel::configureContainer()` -> register directly the services. And during then the container compilation occurs, and bundle services's are loaded.

**Comment by apfelbox** [comment]
A `priority` value would be really great for the tag, as this is useful even for third party bundles to overwrite the core functions.

**Comment by fabpot** [comment]
Overriding functions/filters/tags is a really bad idea. It can have consequences on third-party bundles/libs and it can be a nightmare to debug.

**Comment by lyrixx** [comment]
@apfelbox I thought the same thing :D We it does not exist (yet?)

@fabpot I tend to agree, but in our case, it was for adding more feature with decoration. And the previous twig filter was really simple:

https://github.com/jbouzekri/PhumborBundle/blob/2b43f5d02123189c9b84f0ba840e2f879ad543d8/Twig/PhumborExtension.php#L58-L61

More over, overloading is [documented](https://twig.symfony.com/doc/2.x/advanced.html#overloading)

**Comment by apfelbox** [comment]
Yeah, regardless of recommendations, the documented way from Twig doesn't work reliably in Symfony. That seems to be the issue here.

**Comment by dmaicher** [comment]
I think priorities on `twig.extension` tags should be working already?

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/TwigEnvironmentPass.php#L42

**Comment by fabpot** [comment]
@lyrixx Don't forget to mention the tip "Note that overloading the built-in Twig elements is not recommended as it might be confusing.". I'm going to remove this part of the documentation. I think this is anyway too dangerous to override an existing Twig filter/tag/function (and what if more than one third-party bundle override something?). You'd better create a new one.

**Comment by fabpot** [comment]
The more I think about this, the more I think we should forbid doing overloading and throw an exception. Do you have a real use case for overloading which cannot be solved by creating a new filter/tag/function?

**Comment by apfelbox** [comment]
I can solve my use case as well via `conflict` in composer / renaming it.

But I would prefer disallowing it instead of this undefined/unpredictable behavior.

**Comment by lyrixx** [comment]
> Do you have a real use case for overloading which cannot be solved by creating a new filter/tag/function?

We are using [thumbor](https://github.com/thumbor/thumbor) to resize our picture "on the fly". This is quite powerful. So almost everywhere in our application we have suce code:
```jinja
img src="{{ thumbor(media.path) }}" alt="{{ media.alt }}" />
```

We added a new feature in ou backoffice: user can now upload SVG and use them anywhere. But thumbor does not support SVG (this make sens). 

So i have overload the twig function to handle both case:
```php
    public function transform($origin, $transformation = null, $overrides = [])
    {
        if (is_string($origin) && '.svg' === substr($origin, -4)) {
            return $this->router->generate('public_media_svg', [
                'path' => substr($origin, 0, -4),
            ]);
        }
        return $this->transformer->transform($origin, $transformation, $overrides);
    }
```

**Comment by fabpot** [comment]
So, you can keep your code but name the function differently. That looks saner to me.

**Comment by lyrixx** [comment]
Wep, Basically, this is all about lazyness :)

**Comment by fabpot** [comment]
see https://github.com/twigphp/Twig/pull/3053/files for the deprecations of Twig overloading.

**Comment by stof** [comment]
@fabpot regarding overloading, DebugBundle overloads the `dump` function (registered initially by Twig's DebugExtension) to make it use VarDumper instead of using `var_dump`. What would be the solution there (we cannot avoid registering Twig's DebugExtension as Twig Environment is doing it automatically)

**Comment by iboved** [comment]
Is it possible to override **|raw** Twig filter?
This filter for some reason can not be overloaded (this is despite the fact that for example the |date filter overload works)

**Comment by stof** [comment]
Well, the `|raw` filter is a special one: it has no runtime behavior at all. It only influences the auto-escaping. I guess that's why overriding it does not work (and I see no reason to override it either btw)
