### ISSUE TITLE
[PhpUnitBridge] DeprecationErrorHandler should read from $_SERVER/ENV

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31857]
Right now, it reads `SYMFONY_DEPRECATIONS_HELPER` using only `getenv()`, but this will soon become incompatible with `Dotenv`, since we switcher it to not use `putenv()` by default in new projects.

(note that I wouldn't change reading the other env vars in the class - only `SYMFONY_DEPRECATIONS_HELPER` makes sense for Dotenv)

/cc @greg0ire if you want to give it a try :)

**Comment by greg0ire** [comment]
Added to my todo list :)
