### ISSUE TITLE
[HttpFoundation] 301 RedirectResponse ignores passed in cache-control header.

### ISSUE THREAD

**Issue by mrbaileys** [symfony/symfony#31862]
**Symfony version(s) affected**: >= 3.2
**Description**  

The constructor for `\Symfony\Component\HttpFoundation\RedirectResponse` [removes the cache-control header for 301 responses](https://github.com/symfony/symfony/blob/fc9f9470e81e6fb59bd826d8040b961f7ed30f94/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L45), _unless_ the caller explicitly provides a cache-control header through the `$headers` parameter (introduced in #17139.) However, the check on `$headers['cache-control']`in the constructor is case sensitive, so if the caller passes in `$headers['Cache-Control']`, the cache-control header is still being removed.

This was discovered in the Drupal issue queue (<a href="/comment/13117581#comment-13117581" title="Status: Reviewed &amp; tested by the community">#3054821-10: Include Cache-Control header on 301 redirects.</a>).

**How to reproduce**  

```
$response = new RedirectResponse('foo.bar', 301, ['cache-control' => 'max-age=86400']);
$this->assertFalse($response->headers->hasCacheControlDirective('no-cache'));

$response = new RedirectResponse('foo.bar', 301, ['Cache-Control' => 'max-age=86400']);
$this->assertFalse($response->headers->hasCacheControlDirective('no-cache'));
```

The first unit test succeeds, the second one fails.

**Possible Solution**  

Perform a case insensitive check on the user-supplied headers.

**Additional context**  

This issue was raised earlier in #27574, but that issue was closed, although a comment by @curry684 said:

> It's dodgy code for sure that could use some comments and improvements...

**Comment by curry684** [comment]
https://github.com/symfony/symfony/issues/27574#issuecomment-396212815 is more relevant than my comment. The assumption that user input is normalized is the dodgy part causing your issue.

I'm not even sure whether there is some kind of documented best practice to avoid caps in headers. If not we certainly should enforce it (more) in code.
