### ISSUE TITLE
[RFC][EventDispatcher] Expose component versions

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#31877]
**Description**  

When implementing a library/bundle which is compatible with several version of dependencies, we have to write code that must adapt to the version of the dependency.
For instance exposing a bundle that is compatible with `symfony/event-dispatcher: ^4.0|^5.0` (or even being compatible with 4.3 without triggering deprecation) we have to code something like
```php
if (class_exists(LegacyEventDispatcherProxy::class)) {
  $this->dispatcher->dispatch($event);
} else {
  $this->dispatcher->dispatch(get_class($event), $event);
}
```

same issue with `treeBuilder->root()` that trigger deprecation, solved by everybody with something like
```php
if (method_exists(TreeBuilder::class, 'getRootNode')) {
  $rootNode = $treeBuilder->getRootNode();
} else {
  $rootNode = $treeBuilder->root('myBundle');
}
```

The issue is in the `if` part, I don't like using arbitrary class to guess the version of the component and the behavior to use.

To solve that issue, I suggest to expose constants (similar to `Symfony\Component\HttpKernel\Kernel`) in every components. 

Given every component don't have a normalized "root" class/interface, I suggest to declare those constants in the namespace (included in the files loaded by composer)

**Example**  

```php
<?php
# symfony/event-dispatcher/Resources/version.php

namespace Symfony\EventDispatcher;

const VERSION = '4.3.0';
const VERSION_ID = 40300;
const MAJOR_VERSION = 4;
const MINOR_VERSION = 3;
const RELEASE_VERSION = 0;
const EXTRA_VERSION = '';
```

```php
# MyBundleCode

if (\Symfony\EventDispatcher\VERSION_ID >= 40300)) {
  $this->dispatcher->dispatch($event);
} else {
  $this->dispatcher->dispatch(get_class($event), $event);
}
```

**Comment by fabpot** [comment]
I would not like to add files loaded by Composer on each request. We could standardize a `Version` class at the root of each component though to benefit from autoloading.

**Comment by nicolas-grekas** [comment]
one could use https://github.com/Ocramius/PackageVersions ?
but honestly, feature-testing has always worked and the added maintenance burden is not worth it.

**Comment by jderusse** [comment]
Indeed, using  https://github.com/Ocramius/PackageVersions could fit. I didn't know the tool, and have to check the performance impact (ie. in dev mode or when user didn't optimize autoload)

> feature-testing has always worked

I may have missed something, how would you test feature with new eventDispatcher's dispatch signature?

Regarding the maintenance, what's about using a script to automatically update those file/class, create git tag, github release, publish composer version? Wouldn't it be the same version everywhere? (I don't know how it work, just asking)

**Comment by javiereguiluz** [comment]
@jderusse I disagree with this part: *"I don't like using arbitrary class to guess the version"*  In my opinion it's the opposite: instead of guessing versions or dealing with version numbers which mean nothing ... you check for the existence of some file/class/method that you want to use or add support to. For that reason, I wouldn't add version per component.

**Comment by nicolas-grekas** [comment]
> feature with new eventDispatcher's dispatch signature?

class_exists(LegacyEventDispatcherProxy::class) or similar

**Comment by nicolas-grekas** [comment]
Or $ed instanceof Contracts\EventDispatcher\EventDispatcherInterface

**Comment by jderusse** [comment]
@javiereguiluz I agree with you, and I misspoke myself. What I call `arbitrary class` is a class/interface/method that is absolutely not related to the feature (yeah, `treeBuilder` was a bad example): for instance when checking `LegacyEventDispatcherProxy` to guess the signature of `dispatch($event/*, string $eventName = null*/)` vs `dispatch($eventName, Event $event)`: there is no relation between the feature and the Marker, moreover such hack is temporary: The feature (swap the `dispatch`'s arguments) is still here, but the Marker is already planned to be removed.

Anyway closing the issue thank to the last comment of @nicolas-grekas , I didn't noticed that the `feature (swap the `dispatch`'s arguments)` have it own Marker with the new contract's `Contracts\EventDispatcher\EventDispatcherInterface`. 
I don't know if it's have been done on purpose (if the `symfony/contract` wasn't a thing, or if the `Symfony\Component\EventDispatcher\EventDispatcherInterface` were already migrated to the `symfony/contract`, one could just have updated the original `EventDispatcherInterface`).
I hope it'll always be the case, and that's something we try to keep in mind: when deprecating a feature, developers should have a way to follow the migration path
