### ISSUE TITLE
[HttpClient] add an ArtaxHttpClient

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31884]
I think https://github.com/amphp/artax has everything that might be required to implement a fully async client in pure PHP. That would nicely fit between CurlHttpClient (better portability) and NativeHttpClient (really async).

That non-trivial for sure, but maybe someone would like to give it a try?

**Comment by andreia** [comment]
Looks interesting!

**Comment by nicolas-grekas** [comment]
Low priority, I'm not sure anybody is interested in implementing this. Thus closing.
(please prove me wrong :) )
