### ISSUE TITLE
[HttpClient] "auto" mode for option "buffer"

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31883]
the "buffer" option is required to allow accessing the content several times, but it should really be turned to false when downloading large files. We discussed with @joelwurtz about an "auto" mode, which could be the default one, and which would look at the content-type of the response to auto-enable buffering for some content types only. If anyone wants to take that task.

**Comment by rjwebdev** [comment]
Would like to give this one a try.

Are we going to decide the content types now for which the buffer should be enabled automatically?

**Comment by nicolas-grekas** [comment]
It should be configurable for sure. Maybe a [no_buffer => regexp] option at the implementation level?
To decide, having a real world use case is always great. If we don't have one, maybe we should wait or close?

**Comment by joelwurtz** [comment]
IMO, automatic buffering should be done for "textual" content types (html / text / xml / json / ....) and there should be no buffer for "binary" content types
