### ISSUE TITLE
[PhpDumper\ProxyDumper] I've got a problem with private lazy services like doctrine EntityManager

### ISSUE THREAD

**Issue by henrikvolmer** [symfony/symfony#31891]
**Symfony version(s) affected**: 4.3

**Description**  
I made an update from Symfony 3.4 to 4.3. After that I had a problem with lazy services in the console. 

The following error occurred:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "staticProxyConstructor" of class "EntityManager_9a5be93"`

I was able to trace this error back to the file `vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php`

If I replace the code of the file with the code from Symfony 3.4, everything works again.

Line 63:
```
 return <<<EOF
        if (\$lazyLoad) {
            $instantiation \$this->createProxy('$proxyClass', function () {
                return \\$proxyClass::staticProxyConstructor(function (&\$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface \$proxy) {
                    \$wrappedInstance = $factoryCode;

                    \$proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

```
replaced with:

```
$hasStaticConstructor = $this->generateProxyClass($definition)->hasMethod('staticProxyConstructor');
        $constructorCall = sprintf($hasStaticConstructor ? '%s::staticProxyConstructor' : 'new %s', '\\'.$proxyClass);

        return <<<EOF
        if (\$lazyLoad) {
            $instantiation \$this->createProxy('$proxyClass', function () {
                return $constructorCall(function (&\$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface \$proxy) {
                    \$wrappedInstance = $factoryCode;

                    \$proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

```
Sorry for the bad description. This is one of my first tickets in GitHub :)

**Comment by nicolas-grekas** [comment]
can you remove the cache manually and try again? still an issue?
(`rm var/cache -Rf`)

**Comment by henrikvolmer** [comment]
yes, the issue is still there

**Comment by nicolas-grekas** [comment]
Can you share a reproducer please? Typically a repo we could clone?

**Comment by henrikvolmer** [comment]
Hello,

thanks for your help, but I found the bug now. It seems that the `symfony/symfony `bundle has a wrong dev-requirement for the `ocramius/proxy-manager` package. Here at least version 0.4 is required, but the missing method `public static staticProxyConstructor` is only available since version 2.0.

See: https://github.com/Ocramius/ProxyManager/releases?after=2.0.0

**Comment by nicolas-grekas** [comment]
Good catch, would you mind sending a PR to branch 4.2 to fix it?
it should be `^2.1`, as in the bridge's composer.json

**Comment by henrikvolmer** [comment]
Sure
