### ISSUE TITLE
A placeholder name must be a string

### ISSUE THREAD

**Issue by Romaxx** [symfony/symfony#31892]
**Symfony version(s) affected**: 4.3.0

**Description**  
Symfony log show me:
-User Deprecated: A placeholder name must be a string (0 given). Did you forget to specify the placeholder key for the requirement "id" of route ..
-User Deprecated: A placeholder name must be a string (1 given). Did you forget to specify the placeholder key for the requirement "idaccount" of route ..

**How to reproduce**  
```
/**
 * @Route(
 *     "/{idaccount}/",
 *     requirements={"idaccount"},
 *     )
 */
class mycontroller extends AbstractController{ 
/**
* @Route(
     *     {"en": "view/{id}", "fr": "voir/{id}"},
     *     name="_view",
     *     requirements={"id","idaccount"},
     *     defaults={"id"=""},
     *     methods={"GET","POST"}
     *     )
*/
public myfunctionincontroller($id,$idaccount):Response{
}
}
```

**Comment by nicolas-grekas** [comment]
requirements must be a map of name to regexp, see https://symfony.com/doc/3.2/routing/requirements.html
