### ISSUE TITLE
PHPUnit Bridge

### ISSUE THREAD

**Issue by waeyy** [symfony/symfony#31917]
**Symfony version(s) affected**: 4.3.x

**Description**  

Impossible de run test

**How to reproduce**  

When calling `./bin/phpunit`
We go this error `sh: composer: command not found
PHP Warning:  chdir(): No such file or directory (errno 2) in /vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 112

Warning: chdir(): No such file or directory (errno 2) in /vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 112
sh: composer: command not found
sh: composer: command not found
sh: composer: command not found`

**Possible Solution**  

**Additional context**

**Comment by InputOutput** [comment]
Have you tried running `vendor/bin/simple-phpunit` instead?

**Comment by lyrixx** [comment]
@waeyy In order to run the phpunit bridge, you need composer [installed globally](https://getcomposer.org/doc/00-intro.md#globally) on your system.

**Comment by Simperfit** [comment]
Running simple-phpunit does not changes anything as it' already launch. I think this can be closed.

**Comment by waeyy** [comment]
Thank you for help guys. As @lyrixx said, i needed to install composer globally.
