### ISSUE TITLE
Messenger doctrine transport does not decode message headers properly 

### ISSUE THREAD

**Issue by ojrzenski** [symfony/symfony#31916]
**Symfony version(s) affected**: 4.3.x

**Description**  
*Symfony\Component\Messenger\Transport\Doctrine\Connection* does not _json_encode_ headers when using **::all()** and **::find()** methods of *DoctrineReceiver*.

This leads to *MessageDecodingFailedException* when using *Symfony\Component\Messenger\Transport\Serialization\Serializer*

**How to reproduce**  
* use doctrine transport
* use *messenger.transport.symfony_serializer* 
* fetch envelopes with *ListableReceiverInterface* methods 

**Possible Solution**  
* separate *message type* from *headers* in table schema
* or simply *json_encode* headers when using *find()* and *all()* 

**Additional context**  
PhpSerializer  would do the work, but it fails on serializing of *Closure* object.
This issue occured when trying to transport *[Sentry](https://sentry.io/)* events with message bus.

**Comment by TimoBakx** [comment]
I can reproduce this using a `ServiceProviderInterface $receivers` (binding that to `@messenger.receiver_locator` and performing the following code:
```
        $all = $this->receivers->get('messenger.transport.async')->all();

        foreach ($all as $item) {
            dump($item);
        }
```

This results in:
```
  [Symfony\Component\Messenger\Exception\MessageDecodingFailedException]  
  Encoded envelope does not have a "type" header.                         

Exception trace:
 () at /vendor/symfony/messenger/Transport/Serialization/Serializer.php:71
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decode() at /vendor/symfony/messenger/Transport/Doctrine/DoctrineReceiver.php:147
 Symfony\Component\Messenger\Transport\Doctrine\DoctrineReceiver->createEnvelopeFromData() at /vendor/symfony/messenger/Transport/Doctrine/DoctrineReceiver.php:108
 Symfony\Component\Messenger\Transport\Doctrine\DoctrineReceiver->all() at /src/Command/TestCommand.php:35
 App\Command\TestCommand->execute() at /vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/console/Application.php:939
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /bin/console:42
```

This does not happen when the `get()` method is used instead of `all()`. I think this happens because the `get()` method does `$doctrineEnvelope['headers'] = \json_decode($doctrineEnvelope['headers'], true);`, where `all()`, `find()` and `findAll()` do not (they imediately return the `fetch()` or `fetchAll()` from the query statement.
