### ISSUE TITLE
[Form] Inconsistent behavior of empty_data with an unchecked checkbox field

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#31927]
**Symfony version(s) affected**: all

**Description**  
When a form type is used as a sub form, the default `empty_data` behavior (with a `data_class`) is inconsistent whether the form has a `CheckboxType` field or not.

cf : https://github.com/symfony/symfony/blob/37ee3695aede3bbd3231549e634188febd5e4a2b/src/Symfony/Component/Form/Extension/Core/Type/FormType.php#L141

If the checkbox field is here, the form is not considered empty if the checkbox is unchecked, so `new $class()` is returned as the empty data (as expected).

If the checkbox field is not here, the form is considered empty, so `null` is returned.

IMHO, it should also returns `new $class()` in this case.

**How to reproduce**  
```php
final class LinkType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('url', UrlType::class);

        if ($options['with_blank']) {
            $builder
                ->add('blank', CheckboxType::class);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Link::class,
            'with_blank' => true,
        ]);

        $resolver->setAllowedTypes('with_blank', 'bool');
    }
}
```

```php
final class FooType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('link', Link::class, [
                'label' => false,
                'with_blank' => false, // toggle with true
            ]);
    }
}
```

**Current solution**
Manually add the `empty_data` option on every form type I make to avoid this case ^^
```php
// LinkType
'empty_data' => function(): Link {
    return new Link();
}
```

**Possible Solution**  
An unchecked checkbox shoud be considered empty.

Before submitting a patch, is it a valid bug ?

**Comment by xabbuh** [comment]
Same as #31572?

**Comment by fancyweb** [comment]
This is highly related but my initial demanding was not exactly the same. However, I just reviewed my case and it is not a bug. 

> If the checkbox field is not here, the form is considered empty, so `null` is returned.

This is actually logical.

> IMHO, it should also returns new $class() in this case.

This is wrong.
