### ISSUE TITLE
[RFC]Adding command up - down for maintenance

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony#31921]
**Description**  
Like Laravel, Symfony doesn't have a command to activate and desactivate a maintenance mode. 

**Example**  
php bin/console down <-- Maintenance active
php bin/console up <--- Maintenance not active.

**Comment by xabbuh** [comment]
What would you expect the command to do?

**Comment by TheGarious** [comment]
Like Laravel, redirect to a maintenance page.

**Comment by fabpot** [comment]
We had something similar in Symfony 1. But I decided to not have the same in Symfony 2 as it is better managed by the web server directly (there are many cases where doing it in the project itself does not work when you are updating deps for instance).

**Comment by TheGarious** [comment]
It's ok, then my idea is not ok. Thanks :)
