### ISSUE TITLE
Entity injection without ParamConverter results in strange behaviour

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#31934]
**Symfony version(s) affected**: 4.3.0, 4.3.1, maybe < 4.3

**Description**  
In a URL, two IDs from different entities must be passed. I forgot in the annotation to deposit the second @ParamConverter hint.

This is what i used in my controller:
```php
/**
 * @Route("/member/ad-activation/success/{ad_id}/{schedule_id}", name="member_ad_activation_success")
 *
 * @ParamConverter("ad", class="App\Entity\Ad", options={"id" = "ad_id"})
 */
public function index(Request $request, Ad $ad, PublicationSchedule $schedule)
```
Note that I forgot to specify the second parameter (schedule_id).

**Expected result**
An exception is thrown, informing me that Symfony does not know how to resolve $schedule variable.

**Actual result**
The action is rendered successfully, but the {schedule_id} param is somehow resolved to "1". For example, if i use the following URL `/member/ad-activation/success/42/3`, the second id (2) will not result in the PublicationSchedule with id 3, but in id 1. I do not know why the framework will server the ID#1 instead of ID#3 for this entity. The same happens if i use bogus values for the second url parameter, e.g. `/member/ad-activation/success/42/iDoNotExist`.

Even weirder, if i add the following annotation, the same will happen:
```php
/**
 * @ParamConverter("ad", class="App\Entity\Ad", options={"id" = "ad_id"})
 * @ParamConverter("scheule", class="App\Entity\PublicationSchedule", options={"id" = "schedule_id"})
```
Note the typo for the second @ParamConverter annotation (`scheule` instead of `schedule`). In this case, the `ParameterBag` contents (dumped via `$request->attributes->all()`) will result in the following result:

![screenshot](https://i.imgur.com/GguufgE.png)

Of course, if i provide the correct annotation values, everything work as expected:

```php
/**
     * @Route("/member/ad-activation/success/{ad_id}/{schedule_id}", name="member_ad_activation_success")
     *
     * @ParamConverter("ad",       class="App\Entity\Ad",                  options={"id" = "ad_id"})
     * @ParamConverter("schedule", class="App\Entity\PublicationSchedule", options={"id" = "schedule_id"})
```
So, the URL  `/member/ad-activation/success/42/3` will fetch the PublicationSchedule entity with id #3 and throws an exception if i use bogus value as `/member/ad-activation/success/42/iDoNotExist`.

**How to reproduce**  
Create a controller and annotate the action to receive two different entities and omit (or missspell the first value) for the second @ParamConverter annotation.

**Possible Solution**  
I even do not know why the ID 1 is used for the second Entity, so i guess this can happen in the @ParamConverter or DI component.

**Comment by derrabus** [comment]
Can you create a small repository that reproduces this issue?

**Comment by dsentker** [comment]
Yes, I will try to setup a reproducable repo for that in the next few days.

**Comment by linaori** [comment]
The parameter converter is from here: https://github.com/sensiolabs/SensioFrameworkExtraBundle

**Comment by xabbuh** [comment]
@dsentker Do you have some update for us? :)

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
