### ISSUE TITLE
[event-dispatcher-contracts]: missing dependency

### ISSUE THREAD

**Issue by tvdijen** [symfony/symfony#31960]
Affects event-dispatcher >=4.3.0

**Description**  
As of `event-dispatcher` 4.3.0, some code was moved to `event-dispatcher-contracts`, which [relies ](https://github.com/symfony/event-dispatcher-contracts/blob/05f4e03ad3ec1b7c071a9b4807b0ecdce568d7f3/EventDispatcherInterface.php#L14)on the package `psr/event-dispatcher`. It is however not listed in the [composer](https://github.com/symfony/event-dispatcher-contracts/blob/master/composer.json)-file.. 

**Possible Solution**  
Add the proper dependency to the composer-file.

**Additional context**  
I rely on the event-dispatcher for my project [here](https://github.com/simplesamlphp/simplesamlphp/blob/psalm/lib/SimpleSAML/HTTP/Router.php#L9).. The issue was reported thanks to Psalm: https://travis-ci.org/simplesamlphp/simplesamlphp/jobs/543327756#L822
I've confirmed that adding the dependency solves the issue.

**Comment by xabbuh** [comment]
The `use` statement is not an issue as PHP handles if the referenced class or interface does not exist. As you can see in that file two lines below we first check whether the interface exists to decide whether or not our `EventDispatcherInterface` from the contracts extends the PSR interface.

**Comment by tvdijen** [comment]
I see, so in runtime it will not cause any issues..
