### ISSUE TITLE
EventSubscriber: Subscribe with a parent event class

### ISSUE THREAD

**Issue by ndench** [symfony/symfony#31969]
**Description**  
With the [changes to the EventDispatcher in 4.3](https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching) we now subscribe to events using the FQCN of the event. It would be awesome if you could use the FQCN of a parent class in order to subscribe to all it's children events.

This comes up because we're using events to power our audit trail. Every controller action dispatches an event which is a subclass of `AuditEvent` using the same event name. We then have a single subscriber that catches each event and writes it to the database. That can then be accesses to see what actions a user has taken.

While this is still supported (we just have to reorder the arguments), I really like the idea of using FQCN's as it removes a lot of boilerplate and is generally much cleaner.

**Example**  

```php
class VehicleEvent {
}

class MotorcycleEvent extends VehicleEvent 
{
}

class SedanEvent extends VehicleEvent 
{
}

class BicycleEvent extends VehicleEvent 
{
}

class PlaneEvent extends VehicleEvent 
{
}

class VehicleSubscriber extends EventSubscriberInterface 
{
    public function getSubscribedEvents(): array
    {
        return [
            VehicleEvent::class => 'handleVehicleEvent',
        ];
    }

    public function handleVehicleEvent(VehicleEvent $event): void
    {
        // Do vehicle related things
    }
}
```

**Comment by Tobion** [comment]
You could use the Messenger component which supports this.

**Comment by linaori** [comment]
> You could use the Messenger component which supports this.

The goal of messages/command is not the same as an event. It would make sense to add this functionality to the event dispatcher imo.

**Comment by Simperfit** [comment]
I like the idea too ! @ndench do you want to implement this feature ?

**Comment by ndench** [comment]
@Simperfit yeah I could take a run at it :+1:

**Comment by ndench** [comment]
I've submitted a [PR for this](#32079), please review it and let me know if there are any change you'd like me to make :smile:

**Comment by xabbuh** [comment]
Do we need to consider to add support for this as a bugfix? PSR-14 declares that listener providers (event subscribers in the EventDispatcher component) must treat parent types identically to child classes:

> Listener Providers MUST treat parent types identically to the Event’s own type when determining listener applicability.

see https://www.php-fig.org/psr/psr-14/#listener-provider

**Comment by nicolas-grekas** [comment]
We don't implement ListenerProviderInterface

**Comment by nicolas-grekas** [comment]
(and I'm not sure this sentence in PSR 14 means that also - it's more about LSP to me)

**Comment by nicolas-grekas** [comment]
Closing as the linked PR has been closed.

**Comment by tomasfejfar** [comment]
Just for reference i link my PR comment here: https://github.com/symfony/symfony/pull/32079#issuecomment-880532195

> We have a usecase for this exactly the same as OP. We have many audit log events that are all treated the same and are handled with the same listener that just serializes them and passes them to the audit log. In the current situation we'll need to subscribe maybe a hundred of different event names/classes.
>
> So far we'll try to work around this using DIC, tagging the events, pulling them in a compiler pass and registering them there. That way it will be cached in the compiled container. But I feel bit dirty registering event classes to DIC for no other reason than discovery :)
