### ISSUE TITLE
Rendering Forms without Translators and Validators

### ISSUE THREAD

**Issue by PF4Public** [symfony/symfony#31968]
**Symfony version(s) affected**: 4.3.1

**Description**  
When a form is to be rendered, the following code in Twig runs:

```
{%- if translation_domain is same as(false) -%}               
{{- label -}}            
{%- else -%}
{{- label|trans(label_translation_parameters, translation_domain) -}}
```

By default `translation_domain` from `validation` "is __not__ same as(false) ", which results in calling `trans`. Which in turn gives an exception 

>An exception has been thrown during the rendering of a template ("You cannot use the "Symfony\Bridge\Twig\Extension\TranslationExtension" if the Translation Contracts are not available. Try running "composer require symfony/translation".").

Trying to override `translation_domain` from `validation` implicitly enables `validation` and gives another error:

>Validation support cannot be enabled as the Validator component is not installed. Try running "composer require symfony/validator".

**How to reproduce**  
Try to render a Form without Translators and Validators

**Possible Solution**  
`translation_domain` should be `false` if `validation` is disabled

**Comment by dFayet** [comment]
I'm not sure to have fully understood the `validation` part, for me if you pass some config to `validation` Symfony is right to ask you to install the `Validator` component.

Beside that I think that setting the `translation_domain` to `false` in the `Form` component if there is no translator installed would be correct. I doubt we want the form component to require `symfony/translation`

Any thoughts? @javiereguiluz

**Comment by javiereguiluz** [comment]
The Form component doesn't require Translation at the moment (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/composer.json) and recently we also decoupled the Validator component from Translation (https://github.com/symfony/symfony/pull/28210).

**Comment by stof** [comment]
but the Twig form theme needs at least the translation contracts to be installed.

**Comment by nicolas-grekas** [comment]
I missed that. Then we should add translation-contracts to require, right?

**Comment by PF4Public** [comment]
@dFayet It is absolutely fine to require `translation` when `trans` function is used. It is absolutely fine to require `validation`, when it  _is_ used. But at present, I'm willing to use neither. And it worked fine until 4.3.1. It probably broke after 4.3

Having `translation_domain` set to `validators` under `validation` when `validation` itself isn't used makes twig require `translations`. Trying to set `translation_domain` to `false` implicitly enables `validation`.

 In the end, because of this default setting `translation_domain: validators`, it is a deadlock: either `translation` should be enabled, or `validation`. I am however planning to use neither of them.

**Comment by xabbuh** [comment]
@PF4Public Can you confirm that #31988 fixes this?
