### ISSUE TITLE
[FrameworkBundle][Mailer] Introduce a global_from_address configuration option for Mailer integration

### ISSUE THREAD

**Issue by jschaedl** [symfony/symfony#31961]
**Description**  

It would be nice to have a configuration option for the mailer component integration provided by the FrameworkBundle to configure a global from address, like we had with the SwiftMailerBundle: https://symfony.com/doc/current/reference/configuration/swiftmailer.html#sender-address

The current way to do it atm, as described in the docs, is to implement a listener which is listening on the `MessageEvent`: https://symfony.com/doc/master/mailer.html#global-from-address

Shall we introduce a configuration option for that?

**What needs to be done**  

* introduce a config option for the mailer component in FWB (maybe: `global_from_address`)
* if the mailer is enabled and the `global_from_address` is set, register a listener on `MessageEvent` and change the from address
* adjust the docs

**Comment by fabpot** [comment]
Discussion started in #31592. Let's close to have only one thread about this topic.
