### ISSUE TITLE
Failed opening bootstrap

### ISSUE THREAD

**Issue by BernardA** [symfony/symfony#31973]
**Symfony version(s) affected**:4.2.1

**Description**  
Symfony is somehow appending a /src directory on the path to bootstrap and thus generating 
error
`Compile Error: Symfony\Component\Debug\DebugClassLoader::main(): Failed opening required '/Users/bernardo/Sites/pdutel/src/config/bootstrap.php' (include_path='.:/Applications/MAMP/bin/php/php7.2.1/lib/php')`
`in index.php line 17`

On index.php the code is

`var_dump(dirname(__DIR__)); // outputs string(28) "/Users/bernardo/Sites/pdutel" `
`line 17-> require dirname(__DIR__).'/config/bootstrap.php';`

I also tried to run `cache:clear` on terminal but it will also fail with the same error on accessing bootstrap.

Same failure if I try `php bin/console server:run`

I have other project with the same stack and it works fine. 
This one worked fine as recent as yesterday as well. 

**How to reproduce**  

**Additional context**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce?

**Comment by BernardA** [comment]
Never mind. Somehow a /public folder was created within .../pdutel/src and in spite that MAMP server was directed to .../pdutel/public it still threw the error.
