### ISSUE TITLE
[5.0] replace return-type annotations by real type declarations on final classes

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31981]
For master only, PR welcome.

**Comment by dFayet** [comment]
I would be glad to work on this, except if you think this task is more for a person with deep knowledge of the Sf code.

**Comment by nicolas-grekas** [comment]
Please give it a try, we're here to help!

**Comment by dFayet** [comment]
:+1: 
Just to be sure, do we consider also the `@final` classes as final?

**Comment by nicolas-grekas** [comment]
Yes!
