### ISSUE TITLE
ini_set after session is active

### ISSUE THREAD

**Issue by saravpreet** [symfony/symfony#31987]
**Symfony version(s) affected**: master

**Description**  
After updating my PHP version to 7.3 I am getting following error:

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:201

**Comment by Tobion** [comment]
Can you create a small example application that allows to reproduce?

**Comment by xabbuh** [comment]
@saravpreet Did you find some time to create an example application?

**Comment by hacktivista** [comment]
Same error for me. Indeed you are expecting to have the session active on line 203 and setting an ini file on line 212.

https://github.com/symfony/symfony/blob/3ed6f51b12ef91e87efb90379250f6b3d3a7da60/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L203-L212

**Comment by saravpreet** [comment]
Calling migrate method in https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/HttpFoundation/Session/Session.php

also throws this error. Migrate method call $this->storage->regenerate($destroy, $lifetime);

**Comment by saravpreet** [comment]
My php -v 
`PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies`

For sample application:

composer create-project symfony/http-foundation test
cd test
make a test.php with following content:
`
<?php
use Symfony\Component\HttpFoundation\Session\Session;

require 'vendor/autoload.php';

$session = new Session();
$session->set('loggedIn', '~SignedIn');
$session->migrate(true, 2592000);

`
then run it as php test.php should give you the error.

`PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/sarav/test/Session/Storage/NativeSessionStorage.php on line 212

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/sarav/test/Session/Storage/NativeSessionStorage.php on line 212
PHP Warning:  session_regenerate_id(): Cannot regenerate session id - headers already sent in /home/sarav/test/Session/Storage/NativeSessionStorage.php on line 219

Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /home/sarav/test/Session/Storage/NativeSessionStorage.php on line 219
`

**Comment by saravpreet** [comment]
Create a new file test2.php with the following code and run it php test2.php also produce the  above error
```
<?php
use Symfony\Component\HttpFoundation\Session\Session;

require 'vendor/autoload.php';

$session = new Session();
$session->set('loggedIn', '~SignedIn');
$session->invalidate(23423);
```

**Comment by mwidner** [comment]
I'm running into a similar problem when trying to set a save path in framework.yaml instead of php.ini.

**Comment by siemendev** [comment]
+1 receiving this warning when setting `framework.session.save_path` after a 3.4 -> 4.4 upgrade. Removing the setting from framework.yaml clears up issue.

**Comment by oleg-brizy** [comment]
I have a custom command to create a development session and I can't implement it because of this error

```php
private SessionInterface $session;

...

$lifetime = new \DateTime('+1 month');

$this->session->set("custom_key", $customValue);
$this->session->migrate(true, $lifetime->getTimestamp()); // Warning: ini_set() ...

$io->success([
    "Session ID: {$this->session->getId()}",
    "Lifetime: {$lifetime->format(DATE_ATOM)}"
]);
```

**Comment by andrii-pez** [comment]
The same for me :(

**Comment by naitsirch** [comment]
I got the same error, when I tried to invalidate the session after the user deleted his own account. Here's the code (an action in a controller):

```php
public function delete(Request $request, TokenStorageInterface $tokenStorage)
{
    $user = $this->getUser();
    // some validation
    $em = $this->getDoctrine()->getManager();
    $em->remove($presenter);
    $em->flush();
    
    $tokenStorage->setToken(null);
    $request->getSession()->invalidate(0);

    return $this->redirectToRoute('app.login.login');
}
```

But after updating Symfony from v4.4.7 to v4.4.8 the issue seemed to be solved.

**Comment by dpeite** [comment]
Same solution, upgrading from Symfony v4.4.4 to v4.4.10 solved the issue.

**Comment by xabbuh** [comment]
let's close then

**Comment by nicodemuz** [comment]
I run into a similar issue in an automation test:
```
1) App\Tests\Controller\Api\LoginApiTest::testApiLoginShouldGiveJWT
ini_set(): Session ini settings cannot be changed after headers have already been sent

/path/to/symfony/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php:49
/path/to/symfony/var/cache/test/ContainerOT5ayd2/getSession_Handler_NativeFileService.php:25
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:1107
/path/to/symfony/var/cache/test/ContainerOT5ayd2/getDoctrine_Orm_Listeners_PdoSessionHandlerSchemaListenerService.php:24
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:1107
/path/to/symfony/vendor/symfony/dependency-injection/Container.php:403
/path/to/symfony/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40
/path/to/symfony/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:181
/path/to/symfony/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:92
/path/to/symfony/vendor/gedmo/doctrine-extensions/src/SoftDeleteable/Filter/SoftDeleteableFilter.php:122
/path/to/symfony/vendor/gedmo/doctrine-extensions/src/SoftDeleteable/Filter/SoftDeleteableFilter.php:64
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:533
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:1082
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:1315
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:902
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:878
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:553
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php:23
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:302
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:398
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:276
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:288
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1212
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1166
/path/to/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:913
/path/to/symfony/vendor/lexik/translation-bundle/Entity/TransUnitRepository.php:30
/path/to/symfony/vendor/lexik/translation-bundle/Storage/AbstractDoctrineStorage.php:158
/path/to/symfony/vendor/lexik/translation-bundle/EventDispatcher/GetDatabaseResourcesListener.php:33
/path/to/symfony/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116
/path/to/symfony/vendor/symfony/event-dispatcher/EventDispatcher.php:220
/path/to/symfony/vendor/symfony/event-dispatcher/EventDispatcher.php:56
/path/to/symfony/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139
/path/to/symfony/vendor/lexik/translation-bundle/Translation/Translator.php:28
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:1873
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:1914
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:7355
/path/to/symfony/var/cache/test/ContainerOT5ayd2/getValidator_Mapping_CacheWarmerService.php:25
/path/to/symfony/var/cache/test/ContainerOT5ayd2/App_KernelTestDebugContainer.php:1107
/path/to/symfony/var/cache/test/ContainerOT5ayd2/getCacheWarmerService.php:31
/path/to/symfony/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:99
/path/to/symfony/vendor/symfony/http-kernel/Kernel.php:545
/path/to/symfony/vendor/symfony/http-kernel/Kernel.php:763
/path/to/symfony/vendor/symfony/http-kernel/Kernel.php:126
/path/to/symfony/vendor/bref/symfony-bridge/src/BrefKernel.php:62
/path/to/symfony/vendor/symfony/framework-bundle/Test/KernelTestCase.php:73
/path/to/symfony/vendor/symfony/framework-bundle/Test/WebTestCase.php:44
/path/to/symfony/tests/Controller/Api/LoginApiTest.php:26
```

Updating my test configuration seemed to have solved the issue. From:
```
framework:
    session:
        storage_factory_id: 'session.storage.factory.mock_file'
```

To:
```
framework:
    session:
        storage_factory_id: 'session.storage.factory.mock_file'
        save_path: ~
```
