### ISSUE TITLE
Bad service name on not-autowirable controller

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31997]
**Symfony version(s) affected**: 4.3.1

When I type-hint a not-existing type on a controller, I get an error message that contains an id I know nothing about:

> Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": argument "$twig" of method "__construct()" has type "App\Environment" but this class was not found.

This should be this instead:

> Cannot autowire service "App\Controller\HelloController": argument "$twig" of method "__construct()" has type "App\Environment" but this class was not found.

**Comment by Simperfit** [comment]
I've got that too this morning, fixing it right now.
