### ISSUE TITLE
Preload not working with .enableVersioning()

### ISSUE THREAD

**Issue by Ninos** [symfony/symfony#31995]
4.0

**Description**  
`{{ preload( 'your.css') }}` is not working on production environment, if `.enableVersioning()` is enabled. Seems `preload()` is using the normal file url instead of the versioned (your.css instead of your.random.css).

**How to reproduce**  
1. Use preload-twig function
2. Enable Versioning & productive env
3. Check site link & also http header link

**Possible Solution**  
Use return of `asset()` for preload link.

**Additional context**  
On dev-environment all is working fine, because links are always your.css instead of your.random.css.

**Comment by ro0NL** [comment]
i think you need to transfer your issue to https://github.com/symfony/webpack-encore

**Comment by javiereguiluz** [comment]
@Ninos you mentioned that this doesn't work in 4.0. Sadly we don't support that version. do you know if the bug persists in 4.2, which is the oldest 4.x version maintained? Thanks.

**Comment by Ninos** [comment]
@javiereguiluz my bad, we're using v4.2.8 atm

**Comment by Simperfit** [comment]
You should use the return of asset(), preload will preload what you want to be preload, for exemple:
if you preload something that's ajax based it will send a preload request to that script either it exist or not.
```
  {% stylesheets
  "src/Resources/V2/objects/utilities.less"
	"src/Resources/V2/front/location/common/location.less"
  output = 'css/piece.css' %}
  <link rel="stylesheet" href="{{ preload(asset(asset_url), {as:'style'}) }}" media="screen" type="text/css"/>
  {% endstylesheets %}
```
Like this is working properly. I don't think there anything to do here ;).
