### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by JL2014** [symfony/symfony#32005]
**Symfony version(s) affected**: 
Changelog.md in "vendor/symfony/property-access" directory say : 2.7.0

**Description**  
When use with a validator, this error occurs ;

> Parse error in ...\vendor\symfony\property-access\Tests\Fixtures\ReturnTyped.php at line 19 - syntax error, unexpected ':', expecting ';' or '{'

**How to reproduce**  
with specific tools

**Possible Solution**  
adapt the source code !?

**Additional context**  
used with PHP 5.6.40

**Comment by stof** [comment]
well, even in 2.7, we have some test fixtures which are using PHP 7 return types, to ensure that PropertyAccess 2.7 supports them properly. But this code will never be used on PHP 5.6 (the tests using this fixture file are skipped).
Which validator are you talking about ?

**Comment by xabbuh** [comment]
closing here as there is nothing to fix as explained by @stof
