### ISSUE TITLE
[Messenger] Can't use DispatchAfterCurrentBusStamp for async messages

### ISSUE THREAD

**Issue by brpauwels** [symfony/symfony#32009]
**Symfony version(s) affected**: 4.3.1

**Description**  
When trying to consume a message with a `DispatchAfterCurrentBusStamp`, you always get the following exception:
```
[LogicException]
You can only use a "Symfony\Component\Messenger\Stamp\DispatchAfterCurrentBusStamp" stamp in the context of a message handler.
```

**How to reproduce**  
Like described in https://symfony.com/doc/current/messenger/message-recorder.html, I dispatch an event from inside a handler with the `DispatchAfterCurrentBusStamp` stamp:

```
$this->eventBus->dispatch(
    (new Envelope($event))
        ->with(new DispatchAfterCurrentBusStamp())
);
```

The event is configured to goto an async transport. When there are no exceptions, the event is pushed to the queue as expected. 

Now when I try to consume the event

```
bin/console messenger:consume async
```

The `DispatchAfterCurrentBusMiddleware` will always throw the following exception

```
[LogicException]
You can only use a "Symfony\Component\Messenger\Stamp\DispatchAfterCurrentBusStamp" stamp in the context of a message handler.
```

This is because the message is now dispatched to the bus from the Worker instead of my handler. This will cause `isRootDispatchCallRunning` to be false inside `DispatchAfterCurrentBusMiddleware`.

**Possible Solution**  
Should the `DispatchAfterCurrentBusStamp` be stripped from the envelope when sending a message in the `SendMessageMiddleware`?

**Comment by weaverryan** [comment]
Ping @Nyholm - could you take a look?

**Comment by Nyholm** [comment]
Thank you for a very detailed bug report. 
You are correct. When the message comes back from the queue we still have the `DispatchAfterCurrentBusStamp` and we are trying to process the message. 

I agree with your solution. "dispatch after current" is not a valid stamp when we changed "current".

I'll provide a PR shortly. 

(Thank you @weaverryan for the ping)

**Comment by weaverryan** [comment]
@brpauwels @wtorsi - this now has a PR - https://github.com/symfony/symfony/pull/32027 - if you can verify it fixes the issue and comment there, it will help (it's a one-liner you could "hack" into your vendor easily to test)

**Comment by ahmed-bhs** [comment]
Hello Guys I'm facing the same issue, this is a quick look about my dependencies:

**Symfony version(s) affected: 4.4.13**
**symfony/messenger                            v4.4.10**

I tried with this 2 syntaxes:

```
$event = new Invitation(..)
$this->bus->dispatch((new Envelope($event))->with(new DispatchAfterCurrentBusStamp()));
```
```
$this->bus->dispatch($event, [new DispatchAfterCurrentBusStamp()]);
```

@Nyholm @weaverryan   Any help would be appreciated!!
