### ISSUE TITLE
symfony/service-contracts missing required dependency on psr/container

### ISSUE THREAD

**Issue by mbessolov** [symfony/symfony#32016]
**Symfony version(s) affected**: 4.3, 4.4 symfony/service-contracts <=1.1.3

**Description**  
"symfony/service-contracts" package is misssing required dependency on "psr/container" and cannot be used by itself. 

**How to reproduce**  
```
composer require symfony/service-contracts
```
test.php:
```
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Contracts\Service\ServiceProviderInterface;

class Test implements ServiceProviderInterface {}

$t = new Test();
```

```
$ php -f test.php

PHP Fatal error:  Interface 'Psr\Container\ContainerInterface' not found in /home/michael/tmp/symfony-contracts-test/vendor/symfony/service-contracts/ServiceProviderInterface.php on line 22

Fatal error: Interface 'Psr\Container\ContainerInterface' not found in /home/michael/tmp/symfony-contracts-test/vendor/symfony/service-contracts/ServiceProviderInterface.php on line 22
```

**Possible Solution**  

Add explicit dependency on `"psr/container": "^1.0"` in symfony/service-contracts package, same as it's already done in [symfony/contracts meta-package here](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Contracts/composer.json#L23)

**Comment by nicolas-grekas** [comment]
Same for cache-contracts about psr/cache
I kinda agree this is a mandatory requirement for the both of them, despite the fact that some contracts don't *neeeed* it (e.g. ResetInterface)
I'm OK to add them to the individual contracts (this means symfony/contracts you move them from "require-dev" to "require", and we should remove them from "suggest")
Up for a PR @mbessolov?

**Comment by mbessolov** [comment]
Created #32017 

To run tests on individual contracts with only that contract's dependencies installed I split (locally) phpunit.xml per contract.
@nicolas-grekas would you like me to 1) add individual phpunit.xml per contract to this PR,
2) create a separate PR, or 3) do nothing as it would be too much an overkill?

**Comment by nicolas-grekas** [comment]
Thanks. No need to do anything for tests, they are on the contracts package only actually.
