### ISSUE TITLE
Toolbar : Impossible to access an attribute ("nb_errors") on a string variable

### ISSUE THREAD

**Issue by dark-matter-matters** [symfony/symfony#32018]
**Symfony version(s) affected**: 4.3.0

**Description**  
The web profiler tollbar is throwing an error "An error occurred while loading the web debug toolbar." on every page, when getting http://127.0.0.1:8000/_wdt/xxxxxx.

**How to reproduce**  
I'm not sure what triggered this, but I suspect upgrading to 4.3. I use vue..js and an API.
The bundle "symfony/profiler-pack": "*" is probably up to date since I ran the dependencies update with composer.

**Additional context**  
Google doesn't know this error! 
Here's a part of the stack trace shown on http://127.0.0.1:8000/_wdt/xxxxxx :
```
(1/3) RuntimeErrorImpossible to access an attribute ("nb_errors") on a string variable ("O:39:"Symfony\Component\VarDumper\Cloner\Data":6:{s:45:"Symfony\Component\VarDumper\Cloner\Datadata";a:2:{i:0;a:1:{i:0;a:1:{i:1;i:1;}}i:1;a:3:{s:5:"forms";a:0:{}s:13:"forms_by_hash";a:0:{}s:9:"nb_errors";i:0;}}s:49:"Symfony\Component\VarDumper\Cloner\Dataposition";i:0;s:44:"Symfony\Component\VarDumper\Cloner\Datakey";i:0;s:49:"Symfony\Component\VarDumper\Cloner\DatamaxDepth";i:20;s:57:"Symfony\Component\VarDumper\Cloner\DatamaxItemsPerDepth";i:-1;s:54:"Symfony\Component\VarDumper\Cloner\DatauseRefHandles";i:-1;}").
--
in form.html.twig line 6
at twig_get_attribute([...]
```
base.html.twig :
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
        <link [...]
    {% endblock %}
</head>
<body>
<div id="app">
    {% block body %}
        <div id="app" class="error">Hello</div>
    {% endblock %}
</div>

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
{% endblock %}

</body>
</html>
```

**Comment by linaori** [comment]
Heya, can you check if this issue is what you're experiencing? #31476

**Comment by dark-matter-matters** [comment]
Thanks, it was indeed the same problem.
I solved it by changing the version of symfony/console, which used to be set to 4.2.* : 
`"symfony/console": "4.3.*"`

**Comment by Oryss** [comment]
I have the same issue and I can't fix it

My composer.json : 
`{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.3.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.6",
        "elasticsearch/elasticsearch": "6.0.1",
        "exercise/htmlpurifier-bundle": "^2.0",
        "fzaninotto/faker": "^1.8",
        "intervention/image": "^2.4",
        "knplabs/knp-paginator-bundle": "^3.0",
        "sensio/framework-extra-bundle": "^5.2",
        "symfony/asset": "4.2.*",
        "symfony/dotenv": "4.2.*",
        "symfony/filesystem": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.2.*",
        "symfony/framework-bundle": "4.2.*",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "4.2.*",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/twig-bundle": "~4.2",
        "symfony/validator": "4.2.*",
        "symfony/webpack-encore-bundle": "^1.0",
        "symfony/yaml": "4.2.*",
        "tinymce/tinymce": "^5.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.3.*"
        }
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "symfony/console": "^4.3",
        "symfony/maker-bundle": "^1.10",
        "symfony/profiler-pack": "^1.0"
    }
}
`

composer show :
`doctrine/annotations                v1.6.1  Docblock Annotations Parser
doctrine/cache                      v1.8.0  Caching library offering an object-oriented API for many cache b...
doctrine/collections                v1.6.2  PHP Doctrine Collections library that adds additional functional...
doctrine/common                     v2.10.0 PHP Doctrine Common project is a library that provides additiona...
doctrine/data-fixtures              v1.3.1  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.9.2  Powerful PHP database abstraction layer (DBAL) with many feature...
doctrine/doctrine-bundle            1.11.2  Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5   Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.2.2   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v2.0.0  Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0  Doctrine Event Manager component
doctrine/inflector                  v1.3.0  Common String Manipulations with regard to casing and singular/p...
doctrine/instantiator               1.2.0   A small, lightweight utility to instantiate objects in PHP witho...
doctrine/lexer                      1.0.2   PHP Doctrine Lexer parser library that can be used in Top-Down, ...
doctrine/migrations                 v2.1.0  PHP Doctrine Migrations project offer additional functionality o...
doctrine/orm                        v2.6.3  Object-Relational-Mapper for PHP
doctrine/persistence                1.1.1   The Doctrine Persistence project is a set of shared interfaces a...
doctrine/reflection                 v1.0.0  Doctrine Reflection component
egulias/email-validator             2.1.8   A library for validating emails against several RFCs
elasticsearch/elasticsearch         v6.0.1  PHP Client for Elasticsearch
exercise/htmlpurifier-bundle        V2.0.4  HTMLPurifier integration for your Symfony project
ezyang/htmlpurifier                 v4.10.0 Standards compliant HTML filter written in PHP
fzaninotto/faker                    v1.8.0  Faker is a PHP library that generates fake data for you.
guzzlehttp/psr7                     1.5.2   PSR-7 message implementation that also provides common utility m...
guzzlehttp/ringphp                  1.1.1   Provides a simple API and specification that abstracts away the ...
guzzlehttp/streams                  3.0.0   Provides a simple abstraction over streams of data
intervention/image                  2.4.2   Image handling and manipulation library with support for Laravel...
jdorn/sql-formatter                 v1.2.17 a PHP SQL highlighting library
knplabs/knp-components              v1.3.10 Knplabs component library
knplabs/knp-paginator-bundle        v3.0.0  Paginator bundle for Symfony to automate pagination and simplify...
nikic/php-parser                    v4.2.2  A PHP parser written in PHP
ocramius/package-versions           1.4.0   Composer plugin that provides efficient querying for installed p...
ocramius/proxy-manager              2.2.2   A library providing utilities to generate, instantiate and gener...
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/http-message                    1.0.1   Common interface for HTTP messages
psr/log                             1.1.0   Common interface for logging libraries
ralouphie/getallheaders             2.0.5   A polyfill for getallheaders.
react/promise                       v2.7.1  A lightweight implementation of CommonJS Promises/A for PHP
sensio/framework-extra-bundle       v5.3.1  This bundle provides a way to configure your controllers with an...
swiftmailer/swiftmailer             v6.2.1  Swiftmailer, free feature-rich PHP mailer
symfony/apache-pack                 v1.0.1  A pack for Apache support in Symfony
symfony/asset                       v4.2.9  Symfony Asset Component
symfony/cache                       v4.3.1  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.3.1  Symfony Config Component
symfony/console                     v4.3.1  Symfony Console Component
symfony/contracts                   v1.1.5  A set of abstractions extracted out of the Symfony components
symfony/debug                       v4.3.1  Symfony Debug Component
symfony/dependency-injection        v4.3.1  Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.2.9  Symfony Doctrine Bridge
symfony/dotenv                      v4.2.9  Registers environment variables from a .env file
symfony/event-dispatcher            v4.3.1  Symfony EventDispatcher Component
symfony/filesystem                  v4.2.9  Symfony Filesystem Component
symfony/finder                      v4.3.1  Symfony Finder Component
symfony/flex                        v1.2.7  Composer plugin for Symfony
symfony/form                        v4.2.9  Symfony Form Component
symfony/framework-bundle            v4.2.9  Symfony FrameworkBundle
symfony/http-foundation             v4.3.1  Symfony HttpFoundation Component
symfony/http-kernel                 v4.3.1  Symfony HttpKernel Component
symfony/inflector                   v4.3.1  Symfony Inflector Component
symfony/intl                        v4.3.1  A PHP replacement layer for the C intl extension that includes a...
symfony/maker-bundle                v1.11.6 Symfony Maker helps you create empty commands, controllers, form...
symfony/mime                        v4.3.1  A library to manipulate MIME messages
symfony/options-resolver            v4.3.1  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.6  A pack for the Doctrine ORM
symfony/polyfill-intl-icu           v1.11.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn           v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring           v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP...
symfony/polyfill-php73              v1.11.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP...
symfony/profiler-pack               v1.0.4  A pack for the Symfony web profiler
symfony/property-access             v4.3.1  Symfony PropertyAccess Component
symfony/routing                     v4.3.1  Symfony Routing Component
symfony/security-bundle             v4.2.9  Symfony SecurityBundle
symfony/security-core               v4.3.1  Symfony Security Component - Core Library
symfony/security-csrf               v4.3.1  Symfony Security Component - CSRF Library
symfony/security-guard              v4.3.1  Symfony Security Component - Guard
symfony/security-http               v4.3.1  Symfony Security Component - HTTP Integration
symfony/stopwatch                   v4.3.1  Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.8  Symfony SwiftmailerBundle
symfony/translation                 v4.3.1  Symfony Translation Component
symfony/twig-bridge                 v4.2.9  Symfony Twig Bridge
symfony/twig-bundle                 v4.2.9  Symfony TwigBundle
symfony/validator                   v4.2.9  Symfony Validator Component
symfony/var-dumper                  v4.3.1  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v4.3.1  A blend of var_export() + serialize() to turn any serializable d...
symfony/web-profiler-bundle         v4.2.9  Symfony WebProfilerBundle
symfony/webpack-encore-bundle       v1.6.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                        v4.2.9  Symfony Yaml Component
tinymce/tinymce                     5.0.8   Web based JavaScript HTML WYSIWYG editor control.
twig/twig                           v2.11.3 Twig, the flexible, fast, and secure template language for PHP
zendframework/zend-code             3.3.1   provides facilities to generate arbitrary code using an object o...
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application`
