### ISSUE TITLE
[Workflow] State machine svg dumper should generate arrow for transitions

### ISSUE THREAD

**Issue by bastnic** [symfony/symfony#32010]
**Symfony version(s) affected**: 4.3.1

**Description**  
Previously, state machine svg dump had arrows as transition, while workflow had square. Since ?? (I'm using 4.3.1) the transition is now a square, just like workflow.
The doc show the "correct" form: https://symfony.com/doc/current/workflow/introduction.html

It seems to not be intentional (poke @lyrixx).

**How to reproduce**  
See here: https://symfony-workflow-demo.herokuapp.com/task/

**Comment by lyrixx** [comment]
Thanks you for noticing.
Actually, there are no bugs in Symfony:
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php#L80-L84

But I made a typo on the demo. I fixed it https://github.com/lyrixx/SFLive-Paris2016-Workflow/pull/28
