### ISSUE TITLE
symfony/http-client missing function cancel() from Symfony\Contracts\HttpClient\ResponseInterface

### ISSUE THREAD

**Issue by jfsenechal** [symfony/symfony#32031]
**Symfony version(s) affected**: 4.3.1

**Description**  
In symfony/http-client-contracts/ResponseInterface.php has public function cancel()
But /var/www/wordpress/vendor/symfony/http-client/Response/CurlResponse.php doesn't implement it

**Possible Solution**  
Add thi function for CurlResponse and NativeResponse

**Additional context**  
PHP Fatal error:  Class Symfony\Component\HttpClient\Response\CurlResponse contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Contracts\HttpClient\ResponseInterface::cancel) in vendor/symfony/http-client/Response/CurlResponse.php on line 25

**Comment by nicolas-grekas** [comment]
You must have missed upgrading the component, v4.3.1 does have the method, see ResponseTrait.
