### ISSUE TITLE
[Mailer] JsonException is thrown when calling `send()` method

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#32043]
**Symfony version(s) affected**: 4.3.1

**Description**  
I'm using the new Symfony Mailer, on a real app production environment some of this issue has happened:

```
Symfony\Component\HttpClient\Exception\JsonException

Response content-type is "text/html; charset=utf-8" while a JSON-compatible one was expected.
```

This error has been thrown by `$this->mailer->send($email)`

I'm also using `symfony/mailgun-mailer`
 
**How to reproduce**  
I don't know, sorry :(

**Possible Solution**  
Wrap the `$this->mailer->send($email);` in a try/catch block, but not sure how this error happens, and how to prevent it, or deal with it.

**Additional context**  
![mailer_JsonException](https://user-images.githubusercontent.com/346010/59498388-a0c44780-8e95-11e9-8b6a-447402ef471b.png)

**Comment by Simperfit** [comment]
@tristanbes could you please test the linked PR ? it will not be a strange error but something more linked to what really happen, maybe you could add a log on the response content to see what is the html returned by mailgun ?

**Comment by nicolas-grekas** [comment]
I think it's important to understand what this HTML is about before improving the exception type.
Could you please try to understand this better?

**Comment by tristanbes** [comment]
Hello,

Unfortunately @nicolas-grekas I cannot understand this better since I got no means to reproduce. The condition were: live application, real traffic, randomly getting this error which was blocking the rest of the process because of the fatal error.

Maybe the mailgun API did timeout ? Maybe the recipient wasn't correct from the mailgun point of view ? 

@Simperfit it's very risky to test your PR since I got no means to reproduce the issue. The only way would to test it on the prod application and i'm not a very good fan of this idea :D

**Comment by Simperfit** [comment]
@tristanbes maybe something that could be done is to add a logger and log the result of the mailgun API to see if it's a problem from the mailgun api directly ?

**Comment by tristanbes** [comment]
Maybe yes. It's in the vendor side right ? 
I think the `send()` method should never stop the execution of the remaining code if there's a problem.

Or if it's not something we want, then, in the doc, wrap each occurence of `send()` inside a try catch, to show that this method is not safe and it could prevent the remaining code from being executed.

**Comment by Simperfit** [comment]
@nicolas-grekas what do you think of this ? should we move forward with the PR ?

**Comment by fabpot** [comment]
@tristanbes Which mailgun transport are you using? API, HTTP, or SMTP?

**Comment by fabpot** [comment]
I've re-read the Mailgun docs and the response should always be JSON.

**Comment by tristanbes** [comment]
I'm using the API.

**Comment by tristanbes** [comment]
@fabpot `MAILER_DSN=http://key-xxxxxxxxxxxxxxxx:domain.com@mailgun`

**Comment by h3llr4iser** [comment]
I have same problem with 4.3.3. Using also mailgun. I just migrate my code to "symfony/mailer" and "symfony/mailgun-mailer". Using api

```
MAILER_DSN=http://$MAILGUN_API_KEY:$MAILGUN_DOMAIN@mailgun
```

Response content-type is "text/html; charset=utf-8" while a JSON-compatible one was expected.

**Comment by fabpot** [comment]
@h3llr4iser Can you tell us what the HTML page says?

**Comment by h3llr4iser** [comment]
I had not rebooted my docker containers, new env vars are not setted. After reboot works correctly. the exception wasnt clear,  I guess it was an authentication problem with mailgun or something similar because env vars not setted.

thx.

**Comment by fabpot** [comment]
I'm going to close as we cannot do anything without more info.

**Comment by fabpot** [comment]
Just had the issue, here is the fix: #33432

**Comment by TomasVotruba** [comment]
Any feedback how to fix this? I mean not in Symfony, but the app. I have the same issue and miss the solution

**Comment by TomasVotruba** [comment]
This takes to install the fixed version:

`composer.json`

```json
"require": {
    "symfony/mailer": "4.4.x-dev as 4.3",
    "symfony/mailgun-mailer": "4.4.x-dev as 4.3",
    "symfony/mime": "4.4.x-dev as 4.3",
}
```

Then update those:

```
composer update symfony/mailgun-mailer symfony/mime symfony/mailer --with-dependencies
```

So I could got the error message:

> The "http" scheme is not supported.

(solution wip)
