### ISSUE TITLE
[Form] Double file size validation when file is beyond the 'upload_max_filesize' parameter

### ISSUE THREAD

**Issue by COil** [symfony/symfony#32045]
**Symfony version(s) affected**: 4.3.1

**Description**  
I have a double file size validation when file is beyond the 'upload_max_filesize' parameter.
In this case the max size is set to 500ko in the form and the max size allowed by php 2mo. Additionally the error message isn't translated.

![sf-bug](https://user-images.githubusercontent.com/177844/59505691-6c0cbc00-8ea6-11e9-82c7-84759135c9de.png)

**How to reproduce**  

    /**
     * Add or edit the avatar.
     */
    class AvatarFormType extends AbstractType
    {
        private const IMAGE_MAX_SIZE = 512000;  
        public function buildForm(FormBuilderInterface $builder, array $options): void
        {
            $builder->add('avatar', FileType::class, [
                'required' => true,
                'constraints' => [
                    new NotBlank(),
                    new Image([
                        'maxSize' => self::IMAGE_MAX_SIZE,
                    ]),
                ],
            ]);
        }
    }

and php setting : 
upload_max_filesize | 2M | 2M

**Possible Solution**  
Detect if a maxSize constraint already exists and is below the upload_max_filesize value?

See you. COil.

**Comment by xabbuh** [comment]
The fact that the message is not translated looks like a bug to me. Can you check in the profiler if it reports any missing translation?

Though I wonder why the size constraint is triggered at all. If the file cannot be uploaded, this shouldn't happen.

**Comment by COil** [comment]
Hi Xabbuh, well it's weird, look at this, in the validator panel I can only see my constraint : 

![bug02](https://user-images.githubusercontent.com/177844/59601878-a758f600-9105-11e9-8fb4-e8c23a8ff572.png)

But in the form panel, I can see the second message but there isn't constraint violation associated to it (at least in the debug panel)

![bug01](https://user-images.githubusercontent.com/177844/59601658-fd796980-9104-11e9-888f-25f1038b589c.png)

There isn't i18n warning in the debug bar regarding the message.

**Comment by xabbuh** [comment]
That the filesize check is not listed in the validator panel is expected as that error is caught on the form level and attached as an error to the form without using the validator component.

I am not sure how we would solve the `Image` constraint validation though. We could skip validation if the file is an `UploadedFile` instance whose error is not 0. However, that would require hardcoding knowledge about the HttpFoundation in the validator component.

**Comment by COil** [comment]
hi Xabbuh. So, what's your suggestion? I can try to debug this tomorrow.

Why FileType doesn't use the public constants of File for translations? 

How to pass the translator object to the file type? The translator object is null, that's why the message isn't translated.

Someone had the same the same problem : 

* https://stackoverflow.com/q/56463087/633864

**Comment by COil** [comment]
Why FileType doesn't use the public constants of File for translations?

**Comment by COil** [comment]
https://stackoverflow.com/questions/56463087/use-translator-with-filetype

**Comment by xabbuh** [comment]
@COil I found out why the translation didn't happen (see #32116).

Though I have no idea yet how to prevent the double error message.

**Comment by COil** [comment]
@xabbuh  there is also an error in the translation domain : 

Sould be : 

    $message = $this->translator->trans($messageTemplate, $messageParameters, 'validators');

in FileType.php.

**Comment by o-alquimista** [comment]
@COil  Did you find a workaround for the duplicated error message? I can reproduce this.

**Comment by COil** [comment]
Just a comment, obviously we can't change change upload_max_filesize ini setting at runtime so this trick will not function.

**Comment by lugosium** [comment]
Hello,

Got duplicate error message too.

This is confusing for the user i think, If i limit the image to 2mo, users does not have to know my upload_max_filesize value. 

The only case is when the upload_max_filesize value is lower than maxSize.

**Comment by xabbuh** [comment]
Can you please check if #39119 fixes this?
