### ISSUE TITLE
Multiple Symfony Projects with one vendor directory

### ISSUE THREAD

**Issue by abderrahimoukhrib** [symfony/symfony#32064]
**Description**  
I need to start more than one symfony projects with the same requirements 
but i have vendor directory with size => 110 MB
3 Projects => 330 MB
**Example**  
```
// I need to change this :
my-project1/
└─ vendor/
 my-project2/ 
└─ vendor/ 
 my-project3/ 
└─ vendor/ 

// To this :
vendor/
my-project1/
my-project2/
my-project3/
```

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
