### ISSUE TITLE
[symfony/lock] doesn't work while called via method

### ISSUE THREAD

**Issue by deepika-maj** [symfony/symfony#32062]
**Symfony version(s) affected**: 4.3.1

I have following test command and when I run the command multiple times at the same time, both process acquire the lock. It is supposed to acquire the lock by only one process.

```
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Lock\Factory;
use Symfony\Component\Lock\Store\FlockStore;

class TestLockCommand extends Command
{
    protected static $defaultName = 'app:test-lock';

    protected function configure()
    {
        $this->setDescription('Test Command');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if (!$this->lockInstance()) {
            print 'lock not acquired' . PHP_EOL;
            return false;
        }

        print 'lock acquired' . PHP_EOL;

        sleep(20);

        print 'complete' . PHP_EOL;
    }

    private function lockInstance()
    {
        $lockStore = new FlockStore();
        $lockFactory = new Factory($lockStore);

        $lock = $lockFactory->createLock('test-lock');
        if ($lock->acquire()) {
            return true;
        }

        return false;
    }
}
```

**Comment by jderusse** [comment]
This snippet don't use lock in the right way: The instance of `$lock` should live as long as you need to work within the lock. By delegating the creation of the `$lock` instance in a separate method, the lock is automatically released once the instance is destruct (when exit the method `lockInstance`) (see https://symfony.com/doc/current/components/lock.html#usage and the last tips at the end of the section)

Looking at the documentation, you'll notice that every use of locks are similar to
```php
$lock = $factory->createLock('test-lock', 30);
$lock->acquire();
try {
    // WORK HERE
} finally {
    $lock->release();
}
```

by delegating call to acquire in a separate method, your code looks more like
```php
$lock = $factory->createLock('test-lock', 30);
$lock->acquire();
$lock->release();

// WORK HERE
```

**Comment by xabbuh** [comment]
So I am closing here as there is no bug.
