### ISSUE TITLE
Can't extend base template

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#32063]
**Symfony version(s) affected**: 4.2.9

**Description**  
I can't extend base.html.twig

**How to reproduce**  
Create a Basic Controller

```php
/**
     * @return Response
     * @Route("/", name="show_home")
     */
    public function index()
    {
        return $this->render('index.html.twig');
    }
```
**index**
```twig
{% extends base.html.twig %}
{% block body %}
blown :)
{% endblock %}
```

**Additional context**  
You can use [this project](https://github.com/cybernet/symfony-32058) to test.
![blown](https://user-images.githubusercontent.com/125879/59562606-73f36a00-9026-11e9-9f3e-a9e24b239c00.png)

**Comment by onEXHovia** [comment]
@cybernet path to extend template must he string
```twig
{% extends 'base.html.twig' %}
```

**Comment by cybernet** [comment]
> 
> 
> @cybernet path to extend template must he string
> 
> ```
> {% extends 'base.html.twig' %}
> ```

how did i not see this 😞
