### ISSUE TITLE
Routing cache is broken with multi-kernel setup on 4.3

### ISSUE THREAD

**Issue by eXtreme** [symfony/symfony#32069]
**Symfony version(s) affected**: 4.3.0, 4.3.1

### Description

I upgraded my app (which is set up with [multiple kernels](https://symfony.com/doc/current/configuration/multiple_kernels.html)) to 4.3 and the routing is broken. In previous versions a cached UrlMatcher (and UrlGenerator) had a filename that depended on kernel name (like `apiApiKernelProdContainerUrlMatcher.php`). Right now it is always `UrlMatcher.php` and comes from the first kernel that was booted after clearing the cache. Which means that running a different kernel will have a wrong route configuration.

I know that using multiple-kernels is "no longer recommended" but it wasn't when I started the project and it was working perfectly fine before 4.3.

### How to reproduce

https://github.com/eXtreme/symfony-multikernel-bug

Simple app set up with symfony binary, and simplest multi-kernel setup like in the docs. Two front controllers: index.php and api.php and they should run different controllers but run the one that was from the first cached kernel.

**Additional context**  

```bash
jacek@jacek-zenbook:~/Work/symfony-multikernel-bug$ ls var/cache/dev/ | cat
annotations.map
ContainerMbPNwx5
ContainerWs8RPPA
doctrine
pools
profiler
srcApp_ApiKernelDevDebugContainerCompiler.log
srcApp_ApiKernelDevDebugContainerDeprecations.log
srcApp_ApiKernelDevDebugContainer.php
srcApp_ApiKernelDevDebugContainer.php.meta
srcApp_ApiKernelDevDebugContainer.xml
srcApp_ApiKernelDevDebugContainer.xml.meta
srcApp_KernelDevDebugContainerCompiler.log
srcApp_KernelDevDebugContainerDeprecations.log
srcApp_KernelDevDebugContainer.php
srcApp_KernelDevDebugContainer.php.meta
srcApp_KernelDevDebugContainer.xml
srcApp_KernelDevDebugContainer.xml.meta
twig
UrlGenerator.php
UrlGenerator.php.meta
UrlMatcher.php
UrlMatcher.php.meta
```

**Comment by yceruto** [comment]
I think this can be considered as a BC break.

Related to PR https://github.com/symfony/symfony/pull/30249 where the `router.cache_class_prefix` was removed from the router options in https://github.com/symfony/symfony/pull/30249/files#diff-a54ffdcb2ee5f6c0c06492fabab70827L69.

Friendly ping to @Tobion

**Comment by eXtreme** [comment]
By looking at https://github.com/yceruto/symfony-skeleton-vkernel/blob/master/src/VirtualKernel.php (from a "virtual kernel" sketelon app) the solution could be to just add a kernel name prefix directory for cache (so `var/cache/app/...` and `var/cache/api/...`) which solves the problem by separating kernel caches. I'm fine with that TBH. 

And when I look at the docs now, I see that the same thing is used there. So yeah, my app was "broken" from the beginning but I've never encountered any problems with that. And it is a large app with a separate api, separate client panel, admin, backend processing etc. :) I guess, everything worked fine because every kernel-dependent file had a unique name before 4.3.

**Comment by nicolas-grekas** [comment]
I'm wondering if apps that use a single cache directory for multiple kernel aren't broken to begin with.
They should always override the getCacheDir instead, right?
If yes, then we should close this as invalid. It not, I don't how we can preserve BC :)

**Comment by eXtreme** [comment]
@nicolas-grekas 

By looking at the docs, yes, they should always have a separate cache dir. I've setup the project the current way (shared cache) back in Sf3.0 when I started it and never had a single issue with this approach until 4.3. :) 

Probably if they were completely separate projects this could be a problem, but it's just a shared codebase with different kernels running different routes/controllers and security.

**Comment by fabpot** [comment]
I think overriding `getCacheDir()` is the way to go here.

**Comment by eXtreme** [comment]
Thanks for confirming, closing then.
