### ISSUE TITLE
APP_ENV definition

### ISSUE THREAD

**Issue by ShuyqcK** [symfony/symfony#32067]
| Q        | A  |
| ------------- |:-------------:|
|  Symfony version ?     | 4.3.1 |

Hi,
```
$env = $_SERVER['APP_ENV']  ?? 'dev';
$debug = (bool) ($_SERVER['APP_DEBUG'] ?? ('prod' !== $env));
```
In this section why  Symfony is using only `$_SERVER` to define the environment ?

_Why not using something like that ? :_
```
$env = $_SERVER['APP_ENV'] ?? $_ENV['APP_ENV']  ?? 'dev';
$debug = (bool) ($_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? ('prod' !== $env));
```
My question is related to this issue [https://bugs.php.net/bug.php?id=67808](https://bugs.php.net/bug.php?id=67808) which initialy refers to Symfony.

**Comment by nicolas-grekas** [comment]
It is now, isn't it?
https://github.com/symfony/recipes/blob/b8dc91a1564755e0b606a9f9919debbd8d04ba82/symfony/framework-bundle/3.3/config/bootstrap.php#L51

**Comment by ShuyqcK** [comment]
Ok, the symfony/flex part of my project wasn't up-to date.
Thanks you.
