### ISSUE TITLE
[Serializer] Groups not working on AbstractQuery::getArrayResult()

### ISSUE THREAD

**Issue by GregRbs92** [symfony/symfony#32072]
**Symfony version affected**: 4.3.0

## Description
When getting a result in my Object Repository thanks to **getArrayResult()**, I was not able to apply the **groups** option in the context of the serializer. The result was indeed serialized, but all the properties of the objects fetched from the database were visible.

## How to reproduce
```php
# src/Controller/ThingController.php

public function getThings(SerializerInterface $serializer) : Response
    {
        /** @var Thing[] $things */
        $things = $this->em->getRepository(Thing::class)->getThings();

        $response = $serializer->serialize($things, 'json', [
            'groups' => [
                'full_thing',
                'user',
            ],
        ]);

        return new Response($response);
    }
```

```php
# src/Repository/ThingRepository.php

$qb = $this->createQueryBuilder('t')
            ->addSelect('t')
            ->leftJoin('t.user', 'u');

        $query = $qb->getQuery();
        $query->useResultCache(true, 7200); // Save the result for 2 hours

        return $query->getResult();
```

```php
# src/Entity/Thing.php

class Thing {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @Groups({"full_thing"})
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     *
     * @Assert\NotBlank()
     *
     * @Groups({"full_thing"})
     *
     * @var string
     */
    private $name;

/**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="thing", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     *
     * @Groups({"full_thing"})
     *
     * @var User
     */
    private $user;
}
```
```php
# src/Entity/User.php

class User {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @Groups({"user"})
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     *
     * @Assert\NotBlank()
     *
     * @Groups({"user"})
     *
     * @var string
     */
    private $username;


    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Thing", mappedBy="user", cascade={"persist", "remove"})
     *
     * @var Thing
     */
    private $thing;
}
```

## Possible Solution
I fixed this problem using *AbstractQuery::getResult()* instead of *AbstractQuery::getArrayResult()*, but this behavior surprised me. I'm not sure if it is a bug or not.

**Comment by xabbuh** [comment]
The groups are associated with your `Thing` class. But when you make use of the `getArrayResult()` method, there are no instances of `Thing` involved and thus the serializer does not know that there are groups to be considered.

**Comment by GregRbs92** [comment]
Thanks for the quick answer !

So if I get it, ```getArrayResult()``` returns an array but do not take care of what is inside this array, right?
This is what I thought when I solved this issue by replacing ```getArrayResult()``` with ```getResult()``` but I still don't get why it works like this. It seems to me that we are losing an important information here when using ```getArrayResult()```, no?

**Comment by xabbuh** [comment]
Can you explain which difference you expected by using `getArrayResult()` instead of `getResult()` which is usually used?

**Comment by GregRbs92** [comment]
I was not actually expecting a huge difference between ```getArrayResult()``` and ```getResult()```. I just gave a try to ```getArrayResult()``` for typing pupose, thinking that it would type my variable as an array and that it would contain the instances of the object as ```getResult()``` would.

**Comment by xabbuh** [comment]
I suggest to stick with `getResult()` then. `getArrayResult()` is actually different in that it does not return an array of objects but an array of arrays (see also https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html#hydration-modes). I am closing here as there is nothing to fix. Thank you for understanding.

**Comment by GregRbs92** [comment]
Ok I did not know that ```getArrayResult()``` was using a different hydratation mode indeed. Thank you for your quick answer and your explanation.
