### ISSUE TITLE
[Debug] TraceableEventDispatcher throws exception with Symfony\Contracts Event

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#32085]
**Symfony version(s) affected**: 4.3.1

**Description**  
When using the legacy dispatch ($eventName, $event) with a Symfony\Contracts\EventDispatcher\Event, the exception is thrown: `Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event, Symfony\Contracts\EventDispatcher\Event given.`

**How to reproduce**  
```
    public function test(EventDispatcherInterface $dispatcher)
    {
        $dispatcher->dispatch('test', new \Symfony\Contracts\EventDispatcher\Event());
    }
```

**Possible Solution**  
in https://github.com/symfony/event-dispatcher/blob/4.3/Debug/TraceableEventDispatcher.php#L153
replace `if (!$event instanceof Event) {` with `if (!$event instanceof Event || $event instanceof ContractsEvent) {`

**Comment by xabbuh** [comment]
This usage looks wrong. When using the legacy signature (i.e. passing an event name as the first argument), the second argument always must have been an object that is an instance of the `Event` class from the EventDispatcher component.
