### ISSUE TITLE
[HttpClient] Can not set json default option

### ISSUE THREAD

**Issue by lugus** [symfony/symfony#32091]
**Symfony version(s) affected**: 4.3.1

**Description**  
As i understand the documentation, it should be possible to create a http client with a default json parameter, and then make a request with others json parameters. But it's actually throwing an error: `Unsupported option "json" passed to Symfony\Component\HttpClient\CurlHttpClient` (Symfony\Component\HttpClient\HttpClientTrait::prepareRequest, line 52, option json is unset). 

The idea behind is to have a service with common json parameters. Example: a google recaptcha http client which will always send the same secret parameter.

**How to reproduce**  
```
$client = HttpClient::create(['json' => ['param1' => 'foo']);
$client->request(
    'POST',
    'https://www.google.com/',
    ['json' => ['param2' => 'bar']]
);
```

**Possible Solution**  
Maybe we could set the body value (json or normalized) when sending the request.

**Additional context**  
None

**Comment by stof** [comment]
This would not help anyway, even if CurlHttpClient would support `json` as a default options, because options are not deep merged with the defaults (which would be a pain if you actually want to override an option). So your example would still send only the `param2` in the JSON.

**Comment by nicolas-grekas** [comment]
I'm :-1:, this would be confusing (see @stof's comment)
