### ISSUE TITLE
[HttpFoundation] Mistyped Request forwarded headers config?

### ISSUE THREAD

**Issue by speller** [symfony/symfony#32095]
**Symfony version(s) affected**: HttpFoundation component, current master branch.

**Description**  
The `Request` class has the following definition:
```
    private static $forwardedParams = [
        self::HEADER_X_FORWARDED_FOR => 'for',
        self::HEADER_X_FORWARDED_HOST => 'host',
        self::HEADER_X_FORWARDED_PROTO => 'proto',
        self::HEADER_X_FORWARDED_PORT => 'host',
    ];
```

I'm curious about the last array element HEADER_X_FORWARDED_PORT. The constant name is **PORT**, but its value is **host**. Is it a mistake?

**Comment by nicolas-grekas** [comment]
I understand it's surprising, but that's on purpose.
