### ISSUE TITLE
[BC][Config][Security] No ability to use env variables in security config after update to SF 4.3

### ISSUE THREAD

**Issue by mleczakm** [symfony/symfony#32108]
**Symfony version(s) affected**: 4.3

**Description**  
After update to SF 4.3 apps with environment variables use in security config part stops working, because of this https://github.com/symfony/symfony/commit/857ac9519e1e5545de4d2eef81af52f6fde62d7e

**How to reproduce**  
Use env variable in security access control, for example:
```
security:
    ...
    access_control:
        - { path: '^/app', roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: '%env(APP_IP)%' }
```
For versions below 4.3 it works as expected, on 4.3 exception is thrown:
`The given "%env(APP_IP)%" value in the "access_control" config option is not a valid IP address.`

**Possible Solution**  
Do not validate env variables

**Comment by mleczakm** [comment]
Looks like this validation added https://github.com/symfony/symfony/commit/857ac9519e1e5545de4d2eef81af52f6fde62d7e disabled env support, even when default env value is provided.

**Comment by Simperfit** [comment]
@mleczakm do you want to look on how you can re-enable env support but still validating this ? maybe with something that will transform the env value before it being denormalized ?

**Comment by xabbuh** [comment]
I am already working on a fix.

**Comment by xabbuh** [comment]
Does #32115 help?

**Comment by mleczakm** [comment]
I'm pretty sure it will, big thanks to You :+1: :1st_place_medal:, but I have no idea how to try it with current code without editing vendors manually.

**Comment by xabbuh** [comment]
@mleczakm You can try `4.3.*@dev` now. :)
