### ISSUE TITLE
User gets into dead end when following basic tutorials

### ISSUE THREAD

**Issue by awdwad45456** [symfony/symfony#32118]
**Symfony version(s) affected**: 4.3.1

**Description**  
User runs into `Integrity constraint violation: 1048 Column 'api_token' cannot be null` when following 3 tutorials.

**How to reproduce**  
1. https://symfony.com/doc/current/setup.html end at `symfony server:start`
2. https://symfony.com/doc/current/security/guard_authentication.html end after filling in security.yaml
3 .https://symfony.com/doc/current/doctrine/registration_form.html end at `php bin/console make:registration-form`, you need to create the user while making sure user gets authenticated this is why we are doing the guard.

**Possible Solution**  
I've managed to fix it by generating the token of user's instance in the `RegistrationController` because it was empty but then you get thrown into another error, I believe this isn't a correct way to fix this.

**Comment by linaori** [comment]
For documentation issues you can use https://github.com/symfony/symfony-docs

I don't see anything referencing to `api_token` in the 3 pages you've linked though.

**Comment by xabbuh** [comment]
I am closing here as this repository is indeed only for the Symfony code. Thank you for understanding.

On a side note, I think the confusion comes from mixing both articles. The first one is for protecting an API, the second one is about traditional login forms. If you want to combine both approaches, you will need to make some adjustments I guess. But please leave some feedback in the [documentation repository](https://github.com/symfony/symfony-docs) with some things you would like to see improved.
