### ISSUE TITLE
[Messenger] Create a MessageEncodingFailedException

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#32117]
We currently have a `MessageDecodingFailedException` when the messenger's serializer fails decoding message. But we have not exception thrown when encoding fails. 

I suggest to create a `MessageEncodingFailedException`. 

(btw, Im currently writing a serializer)

**Comment by Tobion** [comment]
The purpose of the MesseDecodingFailedException is clear at the moment, see https://github.com/symfony/symfony/issues/32055#issuecomment-502687461
What's the purpose of a `MessageEncodingFailedException`

**Comment by Nyholm** [comment]
If my custom serializer fails to encode a message, then I have only `\RuntimeException` that I can throw. 
Then transports can catch `MessageEncodingFailedException` to maybe try handle it. Ie, try a different serializer.

**Comment by Tobion** [comment]
You can throw any exception. Currently SF messenger does not handle any exception when encoding. We should only add explicit exceptions if they are actually used in some way for a certain behavior. So I'm 👎 at the moment.

**Comment by Tobion** [comment]
Closing as explained.
