### ISSUE TITLE
[Form][BC break] Decimal fields cannot be type-hinted as float

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony#32124]
**Symfony version(s) affected**: 4.3

**Description**  
I have the follow entity and field definition:
```php
class Product
{
    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price = 0;

    public function getPrice(): float
    {
        return $this->price;
    }

    public function setPrice(float $price)
    {
        $this->price = $price;
    }
}
```
and a form field whose "type" is being guessed by `DoctrineOrmTypeGuesser`:
```php
$builder->add('price');
```
this works well before 4.3, but after upgrade this app, when the form is being built, this error appears:
> Unable to transform data for property path "price": Expected a numeric string.

**Possible Solution**
It will depend on the right way of type-hinting `decimal` fields.

Even if https://github.com/symfony/symfony/pull/30893 helps to solve a real problem with Doctrine's change detection, I think we must fix the BC break, either relaxing the transformation constraint allowing numeric values:
https://github.com/symfony/symfony/blob/030396ada463cabc352cc63665dded16d7a43526/src/Symfony/Component/Form/Extension/Core/DataTransformer/StringToFloatTransformer.php#L37-L39
```diff
-if (!\is_string($value) || !is_numeric($value)) {
-    throw new TransformationFailedException('Expected a numeric string.');
+if (!\is_numeric($value)) {
+    throw new TransformationFailedException('Expected a number or a numeric string.');
}
```
or reverting the change in `DoctrineOrmTypeGuesser`:
https://github.com/symfony/symfony/blob/030396ada463cabc352cc63665dded16d7a43526/src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php#L77-L78
deprecating this default, for later change in 5.0 to `input = string`.

WDYT?

**Comment by xabbuh** [comment]
This looks like the same as #31905. While I still think that using `float` as the type here is a mistake I think it does not hurt if we relax the `StringToFloatTransformer` (see #32125).

**Comment by yceruto** [comment]
Is this the right way to work around the Doctrine's change detection issue in the model side? '8.000' -> '8.000':
```php
class Product
{
    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price = '0';

    public function getPrice(): string
    {
        return $this->price;
    }

    public function setPrice(string $price)
    {
        $this->price = $price;
    }
}
```
If we use `float` would incur in the same problem '8.000' -> 8, 
but then it looks like a wrong type from the design point of view.

**Comment by xabbuh** [comment]
@yceruto Yes, that looks good. If you debug your former code, you should be able to see that the `$price` property is a string and not a float when the object is populated by Doctrine based on the data stored in the database.
