### ISSUE TITLE
[HTTPClient] 20+ seconds delay on getContent()

### ISSUE THREAD

**Issue by fabstei** [symfony/symfony#32127]
**Symfony version(s) affected**: 4.3.1

**Description**  
I'm calling an external API to get accounts. With HTTPClient the request takes 25+ seconds - running it with [Paw](https://paw.cloud/) (a Postman alternative) takes less than a second, so I'm rather sure that it's my code and not the API. This is my code:

Controller
```
if(isset($accessToken)) {
    $response = $service->getAccounts($accessToken);
    $response = json_decode($response->getContent());
}
```

Service
```
public function getAccounts($accessToken)
{
    $httpClient = HttpClient::create();
    $response = $httpClient->request('GET', self::HOST.'/URL', [
        'headers' => [
            'Content-Type' => 'application/json',
            'authorization' => 'Bearer '.$accessToken
        ],
    ]);

    return $response;
}
```

Checking with XDebug it "hangs" when I run ->getContent() which makes sense, but I'm not sure how to debug further.

**Comment by Simperfit** [comment]
Are you using curl ?
Could you maybe make a blackfire profile ?

**Comment by nicolas-grekas** [comment]
Can you please describe the outcome? What does "it hangs" mean in the end? It works but it's slow? It throws an exception? Would you be able to provide a reproducer? The code excerpt above are just normal code so there's zero hint right now.

**Comment by fabstei** [comment]
It works but it's slow - minimum 20 seconds. There's no exception and the expected result gets returned. I'll try to set up blackfire and will report back.

**Comment by nicolas-grekas** [comment]
It would be useful also to share the result of dumping $response->getInfo() and getInfo('debug') too. Thanks.

**Comment by fabstei** [comment]
The output of getInfo and getInfo('debug') is here: https://gist.github.com/fabstei/d4c18453454690d5ccb921ba15648ce9

**Comment by nicolas-grekas** [comment]
Please call these *after* the response completed.

**Comment by fabstei** [comment]
Silly - sorry about that. Here's the updated gist: https://gist.github.com/fabstei/d4c18453454690d5ccb921ba15648ce9

**Comment by fabstei** [comment]
I also tried to run Blackfire, but it does not seem to include this lengthy API call somehow:

![Screenshot 2019-06-22 07 30 52](https://user-images.githubusercontent.com/1098434/59959965-db933480-94c0-11e9-8485-4dac77f123ea.png)

**Comment by nicolas-grekas** [comment]
Did you redact the IP?
But the issue is pretty clear:
 "namelookup_time" => 22.063046

Your local DNS resolver is slow.

**Comment by fabstei** [comment]
Yes, I redacted URLs and IPs.

Shouldn't the local DNS resolver also affect my lookups with Paw? They are <1s.

I'll try to look into debugging the DNS resolver.

**Comment by Simperfit** [comment]
Maybe Paw has it's own dns resolver or does not use the same dns servers ?

**Comment by nicolas-grekas** [comment]
It's strange that Blackfire doesn't measure the issue. Can you check the info timings when Blackfire is used?

**Comment by fabstei** [comment]
I think I accidentally did it wrong. I retried it right now and the issue now gets measured (22 seconds at curl_multi_select).

I also just deployed the code and the issue disappears on the server, so it definitely is my local machine.

Thanks for the help! I'll try to debug my local dns resolver

**Comment by fabstei** [comment]
If anyone else encouters the issue, an easy work-around is to use the Public DNS provided by Google: 8.8.8.8

**Comment by Simperfit** [comment]
Prefer OpenDNS ;)
