### ISSUE TITLE
UPGRADE to Symfony 4.3 missing helpful documentation

### ISSUE THREAD

**Issue by rbaarsma** [symfony/symfony#32120]
I had lots of deprecation warnings for twig engine being deprecated and other twig-related stuff that I wasn't using in my code. I have a pretty simple Symfony 4.2 (standardly installed with symfony flex) project and had a hard time locating the source of the problem.

Turns out that in the `framework.yaml` file (`config/packages` dir), from Symfony 4.2 there's still this part:

```
    templating:
        engines:
            - 'twig'
```

Removing that solved lots of deprecation issues.

Would be great if this can be added to the `UPGRADE-4.3.md` document

**Comment by Simperfit** [comment]
@rbaarsma I think this is missing from #21035 do you want to add it ?

Status: Reviewed

**Comment by robob4him** [comment]
> I had lots of deprecation warnings for twig engine being deprecated and other twig-related stuff that I wasn't using in my code. I have a pretty simple Symfony 4.2 (standardly installed with symfony flex) project and had a hard time locating the source of the problem.
> 
> Turns out that in the `framework.yaml` file (`config/packages` dir), from Symfony 4.2 there's still this part:
> 
> ```
>     templating:
>         engines:
>             - 'twig'
> ```
> 
> Removing that solved lots of deprecation issues.
> 
> Would be great if this can be added to the `UPGRADE-4.3.md` document

Many thanks, @rbaarsma. That was driving me crazy.
