### ISSUE TITLE
False-positive ServiceCircularReferenceException is thrown with Decorator

### ISSUE THREAD

**Issue by Art4** [symfony/symfony#32132]
**Symfony version(s) affected**: 3.4.28

**Description**  
I'm building a Decorator for an existing class that needs to implement an interface. In the `__construct()` method I'm typehinting for the same interface.

This leads to a `Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException`.

**How to reproduce** 

Create two files with the decorator and the interface:

```php
<?php
// src/AppBundle/TestInterface.php
namespace AppBundle;

interface TestInterface {}
```

```php
<?php
// src/AppBundle/Decorator.php
namespace AppBundle;

class Decorator implements TestInterface
{
    public function __construct(TestInterface $orig)
    {
        $this->orig = $orig;
    }
}
```

Now try to use the decorator:

`$decorator = new \AppBundle\Decorator($testInterfaceImplementation);`

This will throw a Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException.

### 1. Install Symfony 3.4.28

```
$ php -r "file_put_contents('symfony', file_get_contents('https://symfony.com/installer'));"
$ chmod 744 symfony 
$ ./symfony new my_project_name 3.4

 Downloading Symfony...

    6.4 MiB/6.4 MiB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 3.4.28 was successfully installed. Now you can:

    * Change your current directory to ./my_project_name

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php bin/console server:start command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at https://symfony.com/doc
```

### 2. Create two files with the decorator and the interface:

```
$ cd my_project_name/
$ cat > src/AppBundle/TestInterface.php <<EOL
> <?php
> // src/AppBundle/TestInterface.php
> namespace AppBundle;
> 
> interface TestInterface {}
> EOL
$ cat > src/AppBundle/Decorator.php <<EOL
> <?php
> // src/AppBundle/Decorator.php
> namespace AppBundle;
> 
> class Decorator implements TestInterface
> {
>     public function __construct(TestInterface $orig)
>     {
>         $this->orig = $orig;
>     }
> }
> EOL
$ ls -a src/AppBundle/
.  ..  AppBundle.php  Controller  Decorator.php  TestInterface.php
```

### 3. Now start the server...

```
$ php bin/console server:start

                                                                                                                        
 [OK] Server listening on http://127.0.0.1:8000                                                                         
                                                                                                                        

```

### 4. ... and open http://127.0.0.1:8000 in the browser.

This will throw a  `Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException`.

**Possible Solution**  
n.A.

**Additional context**  

![Screenshot_2019-06-21 Screenshot](https://user-images.githubusercontent.com/2162994/59929117-6c75fb80-9440-11e9-977f-a454d581120c.png)

**Comment by xabbuh** [comment]
How did you set up your service config? Did you add any custom config? Is this the only class implementing the interface?

**Comment by Art4** [comment]
> How did you set up your service config? Did you add any custom config? Is this the only class implementing the interface?

I've updated the issue description. I can reproduce this issue with a fresh symfony installation without any config changes. And yes, this is the only class implementing the interface.

**Comment by Art4** [comment]
As a workaround I have to remove the type hinting:

```php
// src/AppBundle/Decorator.php

class Decorator implements TestInterface
{
    public function __construct(/*TestInterface*/ $orig)
```

I assume the problem is in the autowiring.

**Comment by xabbuh** [comment]
If the service cannot be built, you need to exclude it from the PSR-4 resource loader:

```yaml
services:
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Decorator.php,Entity,Repository,Tests}'
```

**Comment by Art4** [comment]
Small update for my workaround if someone finds this problem via google:

This problem is also present in Symfony 4.4

Instead of removing the typehint in the constructor or exclude all of the affected classes from the PSR-4 resource loader I've found another solution:

I've set the `__construct()` method to private and created a new static factory method.

```php
// src/AppBundle/Decorator.php

class Decorator implements TestInterface
{
    public static function create(TestInterface $orig) {
        return new self($orig);
    }

    private function __construct(TestInterface $orig) {
        //...
    }
}
```

Now the ServiceCircularReferenceException is no longer thrown and one doesn't have to maintain an exclude list in the config.
