### ISSUE TITLE
[HttpClient] Getting responses asynchronously as soon as they ready

### ISSUE THREAD

**Issue by TiGR** [symfony/symfony#32142]
Here is the deal: I use Symfony and HttpClient in telegram bot. Bot sends various requests to Telegram's API, and most of these I don't really care to get the response in main bot logic (I want to run the code as fast as possible). However, I'd like to add requests and responses to Sentry breadcrumbs for reporting. Adding requests is easy. Adding responses is tricky.

I don't want actually to call `Response->getContent()`, so that it would stop main logic execution until I get the response. However, I'd like to somehow get notified as soon as response is ready. Then, I'd like to add the response to breadcrumbs, and then if there were errors in responses - send a notification.

I've tried subscribing to `on_progress`, but that didn't work, since responses were not ready when I tried using them from that callback.

So, I couldn't find anything about some sort of event system, so that I could subscribe and get responses _as soon as they get ready_. Is it really possible? And if not, then it's a feature request, I guess...

**Comment by nicolas-grekas** [comment]
Thanks for sharing your use case. In the doc, I tried to explain what the contracts provide to fit this use case:
https://symfony.com/doc/current/components/http_client.html#multiplexing-responses

This allows building what you're describing without much complexity. Can you figure out how?
I'm interested to know before giving you more hints, to challenge the doc :)

**Comment by TiGR** [comment]
So, it seems that there is no way to achieve this without interrupting main program flow for this (you have to switch to that foreach cycle, and be there until the very last request is finished). I just thought it might be possible to get it somehow out of `on_progress` callback, or to have another callback for that (say, `on_complete`).

But it seems that at some point I have to switch to analyzing all responses, maybe on kernel exception event, currently I do it on kernel terminate event.

**Comment by nicolas-grekas** [comment]
Somehow :)
See https://github.com/symfony/symfony/pull/32174

**Comment by nicolas-grekas** [comment]
Will be fixed by #33743
