### ISSUE TITLE
Return value of Symfony\Component\Debug\ExceptionHandler::setFileLinkFormat() must be of the type string, null returned

### ISSUE THREAD

**Issue by jlslew** [symfony/symfony#32150]
**Symfony version(s) affected**: master

**Description**  

The variable `fileLinkFormat` is initialized everywhere in the class `Symfony\Component\Debug\ExceptionHandler` to null but here it is asking for a string
```
public function setFileLinkFormat($fileLinkFormat): string
{
    $old = $this->fileLinkFormat;
    $this->fileLinkFormat = $fileLinkFormat;
    return $old;
}
```

**How to reproduce**  

- `git clone git@github.com:symfony/website-skeleton.git .`
- `composer install`

**Additional context**  

The return type was added in PR #31996

**Comment by fancyweb** [comment]
Status: reviewed

Yes, the comment and the strict return type is wrong. Can you send a PR?
