### ISSUE TITLE
[Console] CommandTester not dispatching console events

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#32158]
**Version**
3.4 - master(?)

**Description**  
In my app I'm using a monolog console handler (see https://symfony.com/doc/current/logging/monolog_console.html) that works by using Symfony console events.

While testing a command with the `CommandTester` I noticed that there is no logging output available from the command's output. That is because the `CommandTester` does not dispatch any console events. This makes functional testing a bit tricky and causes different behavior.

So my question: would it not make sense to dispatch events?

In the meantime I changed my tests in the following way which works as expected:

```diff
         $this->application = new Application($this->getKernel());
         $this->application->setCatchExceptions(false);
         $this->application->setAutoExit(false);

         $this->application->add($command);

-        $commandTester = new CommandTester($command);
-        $commandTester->execute(array_merge(['command' => $command->getName()], $options), [
-            'interactive' => false,
-        ]);
+        $input = new ArrayInput(array_merge(['command' => $command->getName()], $options));
+        $input->setInteractive(false);
+        $output = new BufferedOutput();
 
-        return $commandTester->getDisplay();
+        $this->application->run($input, $output);
+
+        return $output->fetch();

**Comment by mbabker** [comment]
The CommandTester is basically a wrapper around `Command::run()`, which doesn't trigger any events (all of the events come from the application).  So if you're doing a functional test that relies on the events before/after a command is run, it seems like the way you changed your test would be the right way to do it (alternatively you could use the ApplicationTester to run the application).

**Comment by dmaicher** [comment]
Yeah actually I see your point. For functional tests including events the `ApplicationTester` is probably more suitable.

I think this should be documented here: https://symfony.com/doc/current/console.html#testing-commands

I will create a docs issue and will try to work on it soon.
