### ISSUE TITLE
Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event, MyBundle\Event\QbCartLoadEvent given.

### ISSUE THREAD

**Issue by cronk1986** [symfony/symfony#32189]
**Symfony version(s) affected**: 4.3.1

**Description**  
I have an exception when I try to dispatch an event from event dispatcher service, the current exception is:

**Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event, MyBundle\Event\MyEvent given.**

PhpStorm shows "Symfony\Component\EventDispatcher\Event" as deprecated and suggest to use "Symfony\Contracts\EventDispatcher\Event" class but throw the previous exception. 

My event class
```php
<php
use Symfony\Contracts\EventDispatcher\Event;

class MyEvent extends Event
{
   //my custom code
}

```

**How to reproduce**  
Follow the steps below in order to reproduce the exception:
```php
//this code is in a controller class
$this->get('event_dispatcher')->dispatch('myevent', new MyEvent(/*constructor parameters if proceed*/));
```
If inheritance if changed for "Symfony\Component\EventDispatcher\Event" instead of "Symfony\Contracts\EventDispatcher\Event" works like charm.

I'm not sure if is really a bug or is my code.

Any idea?
Thank you! in advance.

**Comment by xabbuh** [comment]
When not using the legacy event class, you also need to drop the name argument. The following should work as expected:

```php
$this->get('event_dispatcher')->dispatch(new MyEvent(/*constructor parameters if proceed*/));
```

**Comment by cronk1986** [comment]
@xabbuh I want to use event name what can I do?

**Comment by xabbuh** [comment]
You need to pass the name as the second argument now.

**Comment by cronk1986** [comment]
@xabbuh, what's happen  with my previous dispatched events in other projects, have I to migrate to the new syntax or have I change only the inheritance?

I mean: 
```php
 $this->get('event_dispatcher')->dispatch('myevent', new MyEvent());
```
Should be changed to:
```php
//this works like charm
 $this->get('event_dispatcher')->dispatch(new MyEvent(), 'myevent');
```
or can I keep the below syntax and change MyEvent inheritance
```php
 $this->get('event_dispatcher')->dispatch('myevent', new MyEvent());
```

After update my SF to 4.3.2 with this commit https://github.com/symfony/symfony/commit/e55978ada897f4e037c11772341bcae8bdb8ceb6 
the bug is still alive, if the below syntax if kept:
```php
 $this->get('event_dispatcher')->dispatch('myevent', new MyEvent());
```
Throw an exception:

**Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event, MyBundle\Event\MyEvent given.**

Henceforth should use the below syntax and migrate all my dispatchers?
```php
//this works like charm
 $this->get('event_dispatcher')->dispatch(new MyEvent(), 'myevent');
```
Thank you! for your time an your support.

**Comment by xabbuh** [comment]
@cronk1986 As soon as your event class does not extend `Symfony\Component\EventDispatcher\Event` anymore, you must pass it as the first argument to `dispatch()` to not run into this error. But to make the upgrade a bit smoother I would actually first update the `dispatch()` calls and swap the arguments. And only once you have updated all the calls you can safely stop extending the `Event` class from the EventDispatcher component.

**Comment by cronk1986** [comment]
Ok, thank you!

**Comment by xabbuh** [comment]
You're welcome. :)

**Comment by ngtranthanhtoan** [comment]
Smae problem here !
