### ISSUE TITLE
[Profiler] It crash from symfony 4.2 to 4.3

### ISSUE THREAD

**Issue by tutosfaciles48** [symfony/symfony#32191]
**Symfony version(s) affected**: 4.3

**Description**  
The profil cannot be launch about a twig error

**How to reproduce**  
upgrade symfony 4.2.9 to 4.3

See log and file [web-profiler-bundle/Resources/views/Collector/form.html.twig](https://github.com/symfony/web-profiler-bundle/blob/503a96edd9ed6b2b4833a5a8b64eed2c3dff8d8b/Resources/views/Collector/form.html.twig#L11)

**Possible Solution**  
Edit: it's seems of collector.data is null in the twig template

**Additional context**  
[..]line 6 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Impossible to access an attribute (\"nb_errors\") on a string variable [...]

**Comment by xabbuh** [comment]
Can you show the output of `composer show`?

**Comment by tutosfaciles48** [comment]
[composer_show.txt](https://github.com/symfony/symfony/files/3330942/composer_show.txt)

**Comment by xabbuh** [comment]
This looks like it could be related to #31476 and #32018.

**Comment by tutosfaciles48** [comment]
oh effectively, but only #32018
