### ISSUE TITLE
[Validator] CountryValidator uses deprecated Intl interface

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#32204]
**Symfony version(s) affected**: 4.3+

**Description**  
The https://github.com/symfony/symfony-docs/pull/11443 introduced new Intl interface. It looks like the `\Symfony\Component\Validator\Constraints\CountryValidator` wasn't updated.

**How to reproduce**  
Use the validator on a DTO and try to validate it in a functional test.

**Possible Solution**  
Use new interface, PR will be delivered soon ;)

**Additional context**  
*none*

**Comment by Simperfit** [comment]
@kiler129 did you has time to push the PR ?

**Comment by ro0NL** [comment]
I don't see anything wrong...

https://github.com/symfony/symfony/blob/f59bc48850c89d0e2cd9ca0e27891fbe7fef651c/src/Symfony/Component/Validator/Constraints/CountryValidator.php#L51

conflicts were updated as such:

https://github.com/symfony/symfony/blob/f59bc48850c89d0e2cd9ca0e27891fbe7fef651c/src/Symfony/Component/Validator/composer.json#L46

> introduced new Intl interface

there's no "interface" :)

**Comment by xabbuh** [comment]
Closing as explained by @ro0nl.
