### ISSUE TITLE
Allow to set private services in TestContainer

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#32224]
**Description**  
Since Symfony 4.1 (https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) we can get private services in our tests.

It would be really nice to be able to set private services too.
Actually, we receive an error `service is private, you cannot replace it.`

**Example**  
It would be useful for functional tests.
```
$client->request(...);
$this->assertEquals(200, $client->getResponse()->getStatusCode());
```

```
$mailer = $this->createMock(Mailer::class);
$mailer->expects($this->once())
            ->method('sendConfirmationEmail')
            ->will($this->throwException(new \Exception()));

$client->getContainer()->set(Mailer::class, $mailer);

$client->request(...);
$this->assertEquals(500, $client->getResponse()->getStatusCode());
```

```
$mailer = $this->createMock(Mailer::class);
$mailer->expects($this->once())
            ->method('sendConfirmationEmail')
            ->will($this->throwException(new \SpecialException()));

$client->getContainer()->set(Mailer::class, $mailer);

$client->request(...);
$this->assertEquals(200, $client->getResponse()->getStatusCode());
```

**Comment by stof** [comment]
This won't work, as the TestContainer does not actually manage any instance. It only has access to a ServiceLocator to read stuff from the main container.

Setting a service instance would require support from the container itself (and this never worked fine if you do it after some services got instantiated already, which is why this feature got deprecated in the past).

**Comment by VincentLanglet** [comment]
> This won't work

This code was working in Symfony 3 and broke when I upgraded to Symfony 4.3.
Since it was working in Symfony 3, it should be possible to make it work, isn't it ?

It seems weird to me that we can't mock services in functional tests now...

**Comment by Simperfit** [comment]
Why don't you mock an interface ?

**Comment by VincentLanglet** [comment]
> Why don't you mock an interface ?

I mock a custom service that I implemented. I won't create Interface everytime I need to mock a service in a functional test.

Others solutions I found was
- to set this service as public. But if I do this, I modify my code to please my test, that's not a good practice.
- to set all services in test as public. But if I do this, I will not test the real config of the project. And if I have an error because some bundle need some service to be public, it won't be catched.
