### ISSUE TITLE
Memory leak when using route annotation

### ISSUE THREAD

**Issue by goetas** [symfony/symfony#32220]
**Symfony version(s) affected**: v4.3.2 (tested also 3.4 and 4.2, same issue)

**Description**  
When a route is defined using annotations, there is a memory leak. 
If the route is defined using YAML, there is no memory leak.

**How to reproduce**  
I have created a basic symfony app available in https://github.com/goetas/symfony-mem-leak
The travis build showing the memory leak https://travis-ci.org/goetas/symfony-mem-leak/jobs/551313488

The test app has a basic controller as follows:

```php
class DefaultController
{
    /**
     * @Route("/leak",name="getss")
     * @return Response
     */
    public function leak()
    {
        return new Response('hello');
    }

    public function noleak()
    {
        return new Response('hello');
    }
}

```

Requests to `leak` will result in a memory leak, requests to `noleak` will have no leaks.

The repo includes 2 scripts `bin/runner-no-leak` and `bin/runner-no-leak` that call 5000 times the two routes. 

When `bin/runner-leak` is called, memory goes up.

In larger application memory goes up faster... apparently depending on the output of the method..

**Comment by stof** [comment]
Well, your no-leak case is actually using more than 2x the memory from the start, so maybe it leaked everything even faster (and then stopped leaking more)...

**Comment by goetas** [comment]
> Well, your no-leak case is actually using more than 2x the memory from the start, so maybe it leaked everything even faster (and then stopped leaking more)...

That is just because the first command warms up the cache

**Comment by goetas** [comment]
I have committed right now a warmup command too

**Comment by goetas** [comment]
Tacked down the issue to the `PhpFilesAdapter`, used but the annotation reader.

Replacing it with a `ArrayAdapter` the leak disappears.

**Comment by goetas** [comment]
I have reduced it to a minimal version that leaks on my machine, but does not on travis.

**Comment by goetas** [comment]
Found the issue... https://bugs.php.net/bug.php?id=76982 :sob: 

PhpFilesAdapter uses exactly this technique to load files from the cache

**Comment by goetas** [comment]
I think symfony `PhpFilesAdapter` should avoid using closures in the cached file

**Comment by goetas** [comment]
Introduced in symfony with https://github.com/symfony/symfony/pull/27543 (but it is a PHP bug rather than symfony)

**Comment by nicolas-grekas** [comment]
Thanks for the details, I found a work around in https://github.com/symfony/symfony/pull/32236
Could you please confirm it's fixing the mem leak?

**Comment by goetas** [comment]
Thanks for working on this! 
I have verified your PR and seems working. 
[Here](https://travis-ci.org/goetas/symfony-mem-leak/builds/551668219) is the build on Travis  and [here](https://github.com/goetas/symfony-mem-leak/tree/leak-fix) the branch that uses your `cache-fix` branch

**Comment by goetas** [comment]
Can somebody with the right privileges change the label on this issue from "routing" to "cache"?

**Comment by goetas** [comment]
Unfortunately it seems the PHP bug (https://bugs.php.net/bug.php?id=76982) has opened some pandora box of memory leaks.... 

Here ([build](https://travis-ci.org/goetas/symfony-mem-leak/jobs/551699445) and [code](https://github.com/goetas/symfony-mem-leak/tree/di-leak)) the same type of memory leak applied to the symfony dependency injection container... that recently started to use closures and includes quite intensively.

Can somebody prove me wrong please?

**Comment by goetas** [comment]
It seems I'm not wrong... hoped to be...

Here ([code](https://github.com/goetas/symfony-mem-leak/tree/di-compiled-leak) and [build](https://travis-ci.org/goetas/symfony-mem-leak/builds/551710669)) of a compiled container leaking memory....

**Comment by nicolas-grekas** [comment]
I had a look at your reproducers, my opinion right now is that we don't care: to hit the bug, one needs to create a container instance in a loop. This is not a realistic use case to me: the container should be booted once and reused as often as possible. That's what php-pm and similar strategies do. Swoole integrations should to if they don't.

**Comment by goetas** [comment]
>  my opinion right now is that we don't care: to hit the bug, one needs to create a container instance in a loop. This is not a realistic use case to me: the container should be booted once and reused as often as possible.

[In this case](https://github.com/goetas/symfony-mem-leak/blob/9a991cf2e64966bfe5b4a9a669c6fc3504a6436a/leak-non-shared.php#L37) (with non shared services), the leak happens with one single instance on the container.

I understand that in this case symfony can not do much, it is more a general PHP issue. 
My learning from this is that PHP closures are not that perfect as they seem, and that they should be used with care until some issues are not fixed.

**Comment by nicolas-grekas** [comment]
I don't see any memory leak with this case.
Note that using `range()` is allocating a big array. Not sure it's the best in a script that wants to track memory side effects of other parts.

**Comment by goetas** [comment]
> I don't see any memory leak with this case.

You are right... I got lot in the last hours of debugging. It seems the issue is only when creating multiple containers. Things not common in PHP-FPM applications, but a common thing for lambda, swoole or reactphp


> Note that using range() is allocating a big array. Not sure it's the best in a script that wants to track memory side effects of other parts.

I'm not testing memory usage, but memory leaks. It does not matter now much memory is using, it should not increase on each iteration. But that is another topic

**Comment by nicolas-grekas** [comment]
> but a common thing for lambda, swoole or reactphp

If that's true, that's a bug in the integration of SF with those: the same kernel is reused in e.g. php-pm, which does it correctly, using reactphp.

I think we can close this issue, thanks again for investiguating!

**Comment by goetas** [comment]
I agree that this can be closed.

Hope just that somebody will start to work on https://bugs.php.net/bug.php?id=76982 

I think that there is a lot of RAM world-wide just because of that bug :smiley:

**Comment by zmitic** [comment]
@goetas 

> Things not common in PHP-FPM applications, but a common thing for lambda, swoole or reactphp

I am using https://github.com/k911/swoole-bundle and didn't notice memory leaks in production mode, dev does have some but not a big problem.

Do you know how to replicate memory leak under swoole?

**Comment by goetas** [comment]
I do not know how you handle requests in swoole. 
Do you get a fresh kernel on each request (or call boot/shutdown)? If yes, then your app should be affected. If you have a single global di container for the whole app, then you can consider yourself safe. 

Regarding the cache issue, it was introduced with symfony 4.2, if you have an older version, you are safe from this too
