### ISSUE TITLE
symfony/debug 4.4.x-dev requires symfony/error-handler ^4.4 -> no matching package found.

### ISSUE THREAD

**Issue by emodric** [symfony/symfony#32222]
**Symfony version(s) affected**: 4.4

**Description**  

Installing `symfony/debug` in 4.4 version fails because `symfony/error-handler` package is missing from packagist.org.

**How to reproduce**  

`composer require "symfony/debug:^4.4-dev"`

**Possible Solution**  

Add the `symfony/error-handler` package to Packagist.

**Comment by fabpot** [comment]
fixed now

**Comment by emodric** [comment]
Thank you @fabpot !
