### ISSUE TITLE
[Routing] deprecate RouteCollectionBuilder

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#32240]
I'm proposing to deprecate the RouteCollectionBuilder added in #15778 for several reasons:

1. it does not support any of the newer features of all the other loaders like i18n routes (#26143) or imports without trailing slash (#26284)
2. it's not documented anywhere in the symfony docs
3. it seems obsolete since introducing RoutingConfigurator (#24180) which covers the same use-cases
4. It's only used by the MicroKernelTrait forcing people two learn another API but at the end developers don't care much because they likely only import routes from files with a glob pattern as provided by flex/reciepes

To solve 4) we can deprecate the `Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait::configureRoutes` and provide a different method that accepts a `RoutingConfigurator` instead.

**Comment by fabpot** [comment]
@Tobion Looks fine to me. Can you work on a PR?

**Comment by Tobion** [comment]
I probably won't have time for this. I'm focusing on the messenger component currently and also have the secrets encryption on my todo.
