### ISSUE TITLE
"HTTPS" Boolean Header Value in  Browserkit/Client

### ISSUE THREAD

**Issue by solverat** [symfony/symfony#32292]
**Affected file**: `Symfony\Component\BrowserKit\Client`

**Description**  
guzzle/psr7 1.6 [has been released](https://github.com/guzzle/psr7/releases/tag/1.6.0) which does no longer support any header values except numeric or string:

https://github.com/guzzle/psr7/blob/dc784032a3f6f4e7a4b882e272b771f6fe4c37cf/src/MessageTrait.php#L189

From now on, the request object will throw an exception because of this line:

https://github.com/symfony/symfony/blob/38b9b951a42b908fd7e7e9651e41209bc7e620d1/src/Symfony/Component/BrowserKit/AbstractBrowser.php#L385

Error:
```
"Header value must be a string or numeric but boolean provided."
```

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR to fix it? Branch 3.4 I suppose.

**Comment by nicolas-grekas** [comment]
Alternatively, this could be reported as a BC break on Guzzle's side, and fixed as a bug there.
Could you please open an issue on the Guzzle repo to ask them to consider?

**Comment by solverat** [comment]
For reference: https://github.com/guzzle/psr7/issues/282

**Comment by GrahamCampbell** [comment]
> guzzle/psr7 1.6 has been released which does no longer support any header values except numeric or string

I think this was a bug fix surely, in that it just wasn't enforcing it before and it was meant to?

**Comment by sagikazarmark** [comment]
For the record: this is not a BC break in terms of following PSR-7 and enforcing types documented by it.

That being said, we are going to revert the change in the 1.x release branch and reapply it in 2.x, so fixing it in Symfony would probably also make sense.

**Comment by sagikazarmark** [comment]
1.6.1 has been tagged with the reverted change.
