### ISSUE TITLE
Symfony annotations doesn't work with a single quotes

### ISSUE THREAD

**Issue by aleksiuno** [symfony/symfony#32296]
**Symfony version(s) affected**: 4.3.2

**Description**  
The new annotations doesn't work if the path argument is passed with a single quotes.

**How to reproduce**  
Use new Route class "use Symfony\Component\Routing\Annotation\Route;" and insert argument into a single quotes.
![Screenshot from 2019-06-30 21-57-31](https://user-images.githubusercontent.com/17498592/60400831-51169900-9b82-11e9-915b-84995d886e9e.png)
When you refresh the page it throws an error:
![Screenshot from 2019-06-30 22-00-34](https://user-images.githubusercontent.com/17498592/60400868-a0f56000-9b82-11e9-9e5e-07adb21e0550.png)

**Possible Solution**  

**Additional context**

**Comment by xabbuh** [comment]
All annotations are parsed using the Doctrine annotations package which requires to use double quotes instead of single quotes. There is nothing we can do about that. So I am closing here as there is nothing to fix.

**Comment by givihuda** [comment]
I suppose you could submit a PR to the Doctrine annotations package to allow reading single-quotes... I suppose I could too... but I suppose that could be a steep hill to climb.
