### ISSUE TITLE
[Messenger] Redis transport: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by aaitimov** [symfony/symfony#32304]
**Symfony version(s) affected**: 4.3.0

**Description**  
Hi,

we have our redis server configured with requirepass option. 
I get NOAUTH error when dispatching messages to Redis.

**How to reproduce**  

So I read this docs page: 
https://symfony.com/doc/current/messenger.html#redis-transport

It is not really documented how to specify connection password.

I started googling and found the docs page for redis cache: https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

They have the following DSN format for redis cache:

`redis://[pass@][ip|host|socket[:port]][/db-index]
`
I thought redis message transport DSN format might be consistent with redis cache DSN format. So I tried the following:

`MESSENGER_TRANSPORT_DSN="redis://redispass@redishost:6379"
`
That did not work.

I also tried passing options in config file:

```
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auth: redispass
                    password: redispass
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            'App\Message\AsyncMessageInterface': async
```

That also did not work.

Similarly, I could not find a way to specify db-index.

**Comment by weaverryan** [comment]
Ping @alexander-schranz :)

**Comment by alexander-schranz** [comment]
@aaitimov It seems really to be missing need to have a look at https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html so its implemented the same way.

**Comment by weaverryan** [comment]
That's an excellent idea - having those parse the DSN, in the same way, makes perfect sense.
