### ISSUE TITLE
[Messenger] Allow dispatcher to choose the transport

### ISSUE THREAD

**Issue by wizacedric** [symfony/symfony#32312]
**Description**  
Given a Message, a Handler and 2 Transports configured to route Message to Handler, allow the dispatcher to choose which of the transports to use.

My use case is simple : I need to be able to dispatch every message either synchronously or asynchronously, depending on the choice of the user (dispatcher).

The alternative is to duplicate every Message to have a sync version and an async version extending it.

**Example**  
```
$transport = $async ? 'async' : 'sync';
$envelope = $this->bus->dispatch($message, $transport);
```

**Comment by Tobion** [comment]
You can create a custom transport and a stamp. The user adds a stamp to the envelope to specify sync or async. You transport reads the stamp and forwards to one or the other transport. Seems very simple to achieve and nothing symfony needs to provide by default.

**Comment by xabbuh** [comment]
@wizacedric Does the solution @Tobion suggested solve the issue you have?

**Comment by Tobion** [comment]
You could even create two buses. One sync and one async with a middleware that does the stamp+transport logic I mentioned above. So users wouldn't need to add the stamp but just chose the right bus.

**Comment by michaelbagrov** [comment]
Suggested solution works well when you both transports where to send message are known and can be injected into this custom transport and then in routing section is configured only one, that custom transport.
But imagine situation, when app has multiple asynchronous transports configured.
For instance "notifications" and "events". And sync transport as well.
Then app have multiple commands with different asynchronous senders configured.
For instance:
CommandA: notifications
CommandB: [events, notifications]

Advised solution will not work with given configuration and with any configuration with more than two transports, one synchronous and one asynchronous. Potentially it can be scaled by adding more transports to this custom transport and adding logic which transports to choose, but I believe I found better solution.

You still will need stamp, which indicates that message should be processed synchronously, it can be added both manually or by some other middleware as @Tobion suggested, and additionally:
Create custom middleware, very similar to Symfony\Component\Messenger\Middleware\SendMessageMiddleware but with the difference, that it will skip call of $sender->send() method call for envelopes, which has this stamp and $sender is not sync. After all senders are processed, if this stamp was set and there was no sync senders - manually trigger sending envelope to sync transport.

This middleware should be registered for you bus.

So it will allow to process messages both synchronously both asynchronously. If stamp is set - will be processed only asynchronously, if not set - by all other transports.

But it still would be nice to have such functionality out of the box.

**Comment by GSpecDrum** [comment]
I need that functional in my project, and I made custom Stamp & SendersLocator. Locator wraps and replaces Symfony\Component\Messenger\Transport\Sender\SendersLocator and checks this stamp whether transports coming from wrapped vendor's SendersLocator might process a message in conrete context.

**Comment by xserrat** [comment]
After reviewing your proposals I would like to share with you this approach suggested by @GSpecDrum :

```php

// Custom Sender Locator
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\Sender\SendersLocatorInterface;

final class SpecificTransportStampAwareSenderLocator implements SendersLocatorInterface
{
    private SendersLocatorInterface $symfonySenderLocator;
    private ContainerInterface $container;

    public function __construct(SendersLocatorInterface $symfonySenderLocator, ContainerInterface $container)
    {
        $this->symfonySenderLocator = $symfonySenderLocator;
        $this->container = $container;
    }

    public function getSenders(Envelope $envelope): iterable
    {
        /** @var SendToSpecificTransportStamp $stamp */
        $stamp = $envelope->last(SendToSpecificTransportStamp::class);
        if (null === $stamp) {
            return $this->symfonySenderLocator->getSenders($envelope);
        }

        $senderAlias = $this->senderAlias($stamp);
        if (!$this->container->has($senderAlias)) {
            return [];
        }

        yield $senderAlias => $this->container->get($senderAlias);
    }

    private function senderAlias(SendToSpecificTransportStamp $stamp): string
    {
        return sprintf('messenger.sender.%s', $stamp->transport());
    }
}

// Stamp:

use Symfony\Component\Messenger\Stamp\StampInterface;

final class SendToSpecificTransportStamp implements StampInterface
{
    private string $transport;

    public function __construct(string $transport)
    {
        $this->transport = $transport;
    }

    public function transport(): string
    {
        return $this->transport;
    }
}
```

I need to fix an issue related to the instantiation of the custom sender locator but I think it should work. Feel free to suggest any improvement!

**Comment by GSpecDrum** [comment]
Ok, let me show my solution. It works in real project. It is better, for my opinion. It is less coupled with messenger config and doesn't inject container.
```
// CustomSendersLocator

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\Sender\SendersLocatorInterface;

class SendersLocator implements SendersLocatorInterface
{
    private SendersLocatorInterface $sendersLocator;

    public function __construct(SendersLocatorInterface $sendersLocator)
    {
        $this->sendersLocator = $sendersLocator;
    }

    public function getSenders(Envelope $envelope): iterable
    {
        /** @var TransportNameStamp[] $transportNameStamps */
        $transportNameStamps = $envelope->all(TransportNameStamp::class);
        if (!$transportNameStamps) {
            return yield from $this->sendersLocator->getSenders($envelope);
        }
        foreach ($this->sendersLocator->getSenders($envelope) as $senderAlias => $sender) {
            foreach ($transportNameStamps as $stamp) {
                // Pass sender if it's name in stamp.
                if ($stamp->getTransportName() === $senderAlias) {
                    yield $senderAlias => $sender;
                    break;
                }
            }
        }
    }
}

// Stamp

use Symfony\Component\Messenger\Stamp\StampInterface;

final class TransportNameStamp implements StampInterface
{
    private string $transportName;

    public function __construct(string $transportName)
    {
        $this->transportName = $transportName;
    }

    public function getTransportName(): string
    {
        return $this->transportName;
    }
}

//config
    CustomSendersLocator:
        bind:
            $sendersLocator: '@messenger.senders_locator'
```
Also, in compiler pass it needs to add
```
        $container
            ->getDefinition('messenger.middleware.send_message')
            ->replaceArgument(0, new Reference(CustomSendersLocator::class))
        ;
```

**Comment by xserrat** [comment]
> Ok, let me show my solution. It works in real project. It is better, for my opinion. It is less coupled with messenger config and doesn't inject container.
> 
> ```
> 
> // CustomSendersLocator
> 
> 
> 
> use Symfony\Component\Messenger\Envelope;
> 
> use Symfony\Component\Messenger\Transport\Sender\SendersLocatorInterface;
> 
> 
> 
> class SendersLocator implements SendersLocatorInterface
> 
> {
> 
>     private SendersLocatorInterface $sendersLocator;
> 
> 
> 
>     public function __construct(SendersLocatorInterface $sendersLocator)
> 
>     {
> 
>         $this->sendersLocator = $sendersLocator;
> 
>     }
> 
> 
> 
>     public function getSenders(Envelope $envelope): iterable
> 
>     {
> 
>         /** @var TransportNameStamp[] $transportNameStamps */
> 
>         $transportNameStamps = $envelope->all(TransportNameStamp::class);
> 
>         if (!$transportNameStamps) {
> 
>             return yield from $this->sendersLocator->getSenders($envelope);
> 
>         }
> 
>         foreach ($this->sendersLocator->getSenders($envelope) as $senderAlias => $sender) {
> 
>             foreach ($transportNameStamps as $stamp) {
> 
>                 // Pass sender if it's name in stamp.
> 
>                 if ($stamp->getTransportName() === $senderAlias) {
> 
>                     yield $senderAlias => $sender;
> 
>                     break;
> 
>                 }
> 
>             }
> 
>         }
> 
>     }
> 
> }
> 
> 
> 
> // Stamp
> 
> 
> 
> use Symfony\Component\Messenger\Stamp\StampInterface;
> 
> 
> 
> final class TransportNameStamp implements StampInterface
> 
> {
> 
>     private string $transportName;
> 
> 
> 
>     public function __construct(string $transportName)
> 
>     {
> 
>         $this->transportName = $transportName;
> 
>     }
> 
> 
> 
>     public function getTransportName(): string
> 
>     {
> 
>         return $this->transportName;
> 
>     }
> 
> }
> 
> 
> 
> //config
> 
>     CustomSendersLocator:
> 
>         bind:
> 
>             $sendersLocator: '@messenger.senders_locator'
> 
> ```
> 
> Also, in compiler pass it needs to add
> 
> ```
> 
>         $container
> 
>             ->getDefinition('messenger.middleware.send_message')
> 
>             ->replaceArgument(0, new Reference(CustomSendersLocator::class))
> 
>         ;
> 
> ```

Totally agree, it's much more elegant your solution. Also, I think we can implement the `NonSendableStampInterface` instead of the generic because we don't need to send this stamp.

**Comment by GSpecDrum** [comment]
Yea, sure. It would be better.

**Comment by xserrat** [comment]
@GSpecDrum , checking your solution I think you can directly tell to the container that the new `CustomSenderLocator` decorates the original:

```yaml
CustomSenderLocator:
        decorates: messenger.senders_locator
        # pass the old service as an argument
        arguments:
            - '@CustomSenderLocator.inner'
```

Then, you don't need a compiler pass because the final `SenderLocator` injected to anywhere, will be your custom one instead of the original.

**Comment by GSpecDrum** [comment]
Yes, it's the same result made other way.

**Comment by JanMikes** [comment]
As of today, it can be done via:
```php
$bus->dispatch($message, [
    new TransportNamesStamp('transport-name'), // Accepts string or array of strings (name of transport(s)
]);
```

> The [TransportNamesStamp](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Messenger/Stamp/TransportNamesStamp.php) stamp was introduced in Symfony 6.2.

Source: https://symfony.com/doc/current/messenger.html#dispatching-the-message

**Comment by Str3cX** [comment]
@JanMikes using this stamp you will be sending the message both to 'transport-name' and default transport(s) configured under messenger routing. finally, you will have the same message stored in more than one transport, which is a duplicate message. 
another way is to send the message using the appropriate transport service, but then you need to  implement the logic from MessageBuss::dispatch(), which implies middlewares. so, I didn't find a way to do it cleaner, yet.

> As of today, it can be done via:
> 
> ```
> $bus->dispatch($message, [
>     new TransportNamesStamp('transport-name'), // Accepts string or array of strings (name of transport(s)
> ]);
> ```
> 
> > The [TransportNamesStamp](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Messenger/Stamp/TransportNamesStamp.php) stamp was introduced in Symfony 6.2.
> 
> Source: https://symfony.com/doc/current/messenger.html#dispatching-the-message


LATER UPDATE:

the TransportNamesStamp works as expected and as explained in the documentation, overriding the routing config.

seams that my issue was related to custom  symfony/ampq-messenger configuration:

```
# .env

RABBITMQ_DSN=amqp://user:password@localhost:5672
```

```
# config/packages/messenger.yaml
framework:
	messenger:
		transports:
                        custom_priority_medium:
                                dsn: '%env(RABBITMQ_DSN)%'
                                options:
                                        queues:
                                                'mycustom_priority_medium:messages': ~
                        
                        custom_priority_high:
                                  dsn: '%env(RABBITMQ_DSN)%'
                                  options:
                                          queues:
                                                  'mycustom_priority_high:messages': ~
```

when setting custom queues names for RabbitMQ inside configuration file, the exchange name defaults to 'messages' if not specified in the DSN. this means that a message is redirected to all queues with the same 'messages' bindings.


```
# Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection


$useAmqps = 0 === strpos($dsn, 'amqps://');
$pathParts = isset($parsedUrl['path']) ? explode('/', trim($parsedUrl['path'], '/')) : [];
$exchangeName = $pathParts[1] ?? 'messages';
parse_str($parsedUrl['query'] ?? '', $parsedQuery);
$port = $useAmqps ? 5671 : 5672;

$amqpOptions = array_replace_recursive([
    'host' => $parsedUrl['host'] ?? 'localhost',
    'port' => $parsedUrl['port'] ?? $port,
    'vhost' => isset($pathParts[0]) ? urldecode($pathParts[0]) : '/',
    'exchange' => [
        'name' => $exchangeName,
    ],
], $options, $parsedQuery);
```

maybe the default values should be updated in the documentation:

https://symfony.com/doc/current/messenger.html#amqp-transport

`exchange[name] => default: messages`
