### ISSUE TITLE
TextDescriptor throws exception when _controller is defined as an array in a route

### ISSUE THREAD

**Issue by Kyoushu** [symfony/symfony#32324]
**Symfony version(s) affected**: 4.3.2

**Description**  
If a route collection contains a route where `_controller` is an array (e.g. `[FooController::class, 'bar']`), `Symfony\Bundle\FrameworkBundle\Console\Descriptor\TextDescriptor::formatControllerLink` will throw an exception.

**How to reproduce**  
I've created a reproducer

https://github.com/Kyoushu/symfony-text-descriptor-bug

Relevant code can be found in `bug.php`

**Possible Solution**  
Catching `TypeError` will silence the exception, but won't really solve the underlying problem

**Comment by Kyoushu** [comment]
For some reason `$controller` is being deliberately passed to `ReflectionMethod::__construct()` if it's an array.

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php#L543

**Comment by Kyoushu** [comment]
Related merge request

https://github.com/symfony/symfony/pull/30520

**Comment by Kyoushu** [comment]
I think maybe this was the intended code

```php
if (\is_array($controller)) {
    $r = new \ReflectionMethod($controller[0], $controller[1]);
}
```

**Comment by yceruto** [comment]
@Kyoushu would you like to create a PR to fix that? I think converting it to string format before reflection could work.

**Comment by Kyoushu** [comment]
@yceruto sure thing

**Comment by Kyoushu** [comment]
@yceruto I'm afraid I'm having some problems updating the unit tests. This change has an effect on other classes which implement `Symfony\Component\Console\Descriptor\DescriptorInterface`, and I'm not entirely sure how I should change `Symfony\Bundle\FrameworkBundle\Tests\Console\Descriptor\ObjectsProvider` to test the change properly.

**Comment by Kyoushu** [comment]
@yceruto if you don't mind, I'd like to leave the implementation of this fix with you

**Comment by yceruto** [comment]
@Kyoushu send the PR, don't worry, then I can help you solve it, thanks!

**Comment by Kyoushu** [comment]
@yceruto sorry, I'm not going to have time to work on a PR with my current workload
