### ISSUE TITLE
Error when inserting failed message in database

### ISSUE THREAD

**Issue by m-cosquer** [symfony/symfony#32321]
**Symfony version(s) affected**: 4.3.2

**Description**  
When inserting a utf8mb4 message into the failure queue, it returns an error. This is a table created automatically by the messenger component.

**How to reproduce**  
```
php bin/console messenger:consume async
```
after 3 retries when message is handled by Doctrine

**Additional context**  
```
  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x91\  
  x8B J...' for column 'body' at row 1                                         
```

**Comment by sroze** [comment]
Interesting. Can you confirm that you are using MySQL as the database engine? Can you tell us more about how you create this "utf8mb4 message"?

**Comment by Tobion** [comment]
The table does not specify the charset and collation to be utf8mb4 in https://github.com/symfony/symfony/blob/7bd0a2720f51f8e13538ceb23c02eb82c89c5476/src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php#L306-L331 so it probably uses 3 byte urf8 by default. So when you insert a 4 byte utf8 character which can be part of the message, it will break.
We need to see how we can apply https://github.com/symfony/symfony-docs/issues/5526#issuecomment-344033956 to the schema above while still being database independent. Or people need to configure DBAL outside messenger correctly.

**Comment by m-cosquer** [comment]
> Interesting. Can you confirm that you are using MySQL as the database engine? Can you tell us more about how you create this "utf8mb4 message"?

Yes, 5.7.25 version. I defined a `EmailNotification` message which contains an emoji in the subject.

**Comment by weaverryan** [comment]
Ping @vincenttouzet!

We should first experiment to see if setting the table charset and collation inside `Connection.php` fixes the issue. @m-cosquer if you still have your setup handy, could you try that? I think it might be `$schema->setDefaultTableOptions(['charset' => 'utf8mb4', 'collate' => 'utf8mb4_unicode_ci'])` - but that could be slightly off.

Then, assuming it does, we can think about how to do this in a database independent way. `new Schema()` does have a missing 3rd argument `SchemaConfig`, which I believe is what contains the default table options... I'm just not sure exactly where in the container to get this thing from. Or we could fetch this stuff off of the connection params to create this stuff manually - https://github.com/doctrine/dbal/blob/ea92d5602028676d06021bebe8b806e24aa99f58/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L1058-L1077

Cheers!

**Comment by m-cosquer** [comment]
There is not `setDefaultTableOptions` method in `Schema` class.
But by hacking as follows:
```
$schema = new Schema([], [], (new SchemaConfig())->setDefaultTableOptions(['charset' => 'utf8mb4', 'collate' => 'utf8mb4_unicode_ci']));
```
it works

**Comment by vincenttouzet** [comment]
>  I'm just not sure exactly where in the container to get this thing from.

@weaverryan I think we can do this in the DoctrineExtension : https://github.com/doctrine/DoctrineBundle/blob/1.12.x/DependencyInjection/DoctrineExtension.php#L873

**Comment by weaverryan** [comment]
@vincenttouzet could you give it a try? I’m just not sure of this SchemaConfig is a service (or we can get some service that has this as a getter). If it’s not... and it instead seems like it’s just “created” whenever it’s needed, we could also create it manually by using the Connection, like I described above (using AbstractSchemaManager as a guide)
