### ISSUE TITLE
Symfony 4.3 upgrade note lacks upgrade path for AbstractAuthenticationListener

### ISSUE THREAD

**Issue by XWB** [symfony/symfony#32339]
In addition to https://github.com/symfony/symfony/issues/32120

Symfony 4.3 throws the following deprecation notice:

> The "Symfony\Component\Security\Http\Firewall\AbstractAuthenticationListener" class is considered internal since Symfony 4.3. It may change without further notice. You should not use it from "HWI\Bundle\OAuthBundle\Security\Http\Firewall\OAuthListener".

However, the [upgrade document](https://github.com/symfony/symfony/blob/4.3/UPGRADE-4.3.md) doesn't list the AbstractAuthenticationListener. What would be the best approach to get rid of this deprecation notice? Do we really need to copy all functionality from AbstractAuthenticationListener into our [custom OAuthListener](https://github.com/hwi/HWIOAuthBundle/blob/master/Security/Http/Firewall/OAuthListener.php)?

**Comment by linaori** [comment]
This is not a deprecation as far as I can see, it's changed to an internal class. My best guess to solve this is for that bundle to create their own version of this class and ship it along. It wouldn't surprise me if this class would be removed at some point as the `SimpleFormAuthenticationListener` and `UsernamePasswordFormAuthenticationListener` implementations are not the recommended way of configuring authentication anymore. (`simple_form` and `form_login` respectively I believe).

I think this upgrade note would be beneficial though.

**Comment by chalasr** [comment]
The flag has been removed in #32662, upgrading to 4.3.3 should make the notice disappear.
