### ISSUE TITLE
Case sensitive routes on IIS

### ISSUE THREAD

**Issue by gcrispyn** [symfony/symfony#32333]
**Symfony version(s) affected**: 3.4.28

**Description**  
When I want to access to my application, using Symfony and IIS, with a lower case address instead of upper case, I only access to the route page. All the other routes are broken (404 HTTP Code)

**How to reproduce**  
Set up a symfony application with a IIS environment inside a folder called TOTO. Try to access it with http://mywebsite/toto. All the other routes except "/" route are broken.

**Comment by javiereguiluz** [comment]
There are two things to consider:

* URLs are case sensitive (/FOO and /foo are different URLs)
* Windows filesystem was traditionally case insensitive (FOO.html and foo.html are the same)

But this is configurable in modern Windows versions, so maybe your system is case sensitive. If all the above is true, I'd say this is not strictly related to Symfony.

**Comment by xabbuh** [comment]
Is `/toto` a part of the path of your route or is that the path in which your application is stored on the filesystem?

**Comment by gcrispyn** [comment]
@xabbuh : Both !!

My application is stored on a folder called TOTO and I access to my application with this uri : http://mywebsite/TOTO.

When I use http://mywebsite/TOTO and http://mywebsite/toto, it works. No problem.

The problem is for all the other routes.

For example :  http://mywebsite/TOTO/list works and http://mywebsite/toto/list doesn't work (404 error).

**Comment by xabbuh** [comment]
How can it be both? Can you show the config of the route that matches `/TOTO/list`?

**Comment by gcrispyn** [comment]
`    /**
     * @Route("/toto", name="get_form_data", methods={"GET"})
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     * @throws \ReflectionException
     */`

**Comment by xabbuh** [comment]
I don't see how this route could match the path `/TOTO/list` (the `/list` part is not in the route path).

**Comment by gcrispyn** [comment]
Arf. I made a mistake and updated my comment. Sorry!!

**Comment by xabbuh** [comment]
But here, `TOTO` is not part of your route definition. This rather looks like you somehow need to tell your IIS to normalise the path fragment that is not handled by the Routing component.

**Comment by Tobion** [comment]
/toto is the base url. The base url is not used for matching. So for symfony routing it shouldn't matter if it's /toto or /TOTO. So there seems to be a configuration problem of your server. Otherwise please provide a failing test case.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
