### ISSUE TITLE
[Mailer] Missing images when attaching a file

### ISSUE THREAD

**Issue by rjwebdev** [symfony/symfony#32349]
**Symfony version(s) affected**: 4.3.2 (and earlier?)

**Description**  
When I am sending an email with a PDF file attached, created by the KnpSnappyBundle, my images are lost in the email.

**How to reproduce**  
I created a small project to show the bug:
https://github.com/rjwebdev/mailer-bug

After cloning the repo, run `composer install`, `docker-compose up -d` and `symfony server:start -d`. Then go to the homepage of the url given by the symfony server.

Note: you will also need wkhtmltopdf installed to be able to create a pdf file.

**Possible Solution**  
Haven't been able to find a good solution yet.

**Additional context**  
Mailhog screenshot from mail with attachment
![image](https://user-images.githubusercontent.com/12196579/60624565-e4033d80-9de5-11e9-8fd3-96ee0d4ff0c1.png)

Mailhot screenshot from mail without attachment
![image](https://user-images.githubusercontent.com/12196579/60624607-039a6600-9de6-11e9-951e-529702a137d4.png)

**Comment by rjwebdev** [comment]
Note: when I download the email and open it with Mac Mail or Mozilla Thunderbird, everything looks just fine.

**Comment by Simperfit** [comment]
maybe it's an error in mailhog ?

**Comment by rjwebdev** [comment]
Let us hope it is. I would like to try this one with Gmail for example.

**Comment by rjwebdev** [comment]
U just tested my small codebase to let it send an email to a gmail account, and there images and attachments are loaded correctly so I guess it is a mailhog issue and this ticket can be closed.
