### ISSUE TITLE
Symfony security-bundle regression error

### ISSUE THREAD

**Issue by BakoBako** [symfony/symfony#32342]
**Symfony version(s) affected**: 4.*.*

**Description**  
I have issue with latest update for symfony/security-bundle and symfony/config. Error message is:

```
ReflectionException: Class Symfony\Component\Templating\Helper\Helper
not found in /usr/share/nginx/html/vendor/symfony/security-
bundle/Templating/Helper/LogoutUrlHelper.php:23
```

This works well before last update and i see there was issue last year similar to this with explanation that templating is required, but i thath package is not in composer.json required packages of security-bundle.

**How to reproduce**  
Update security-bundle to latest 4.2.3 version

**Possible Solution**  

**Additional context**

**Comment by zspine** [comment]
symfony/security-bundle: (v4.2.10)

I am having the same problem with the latest update. As a temporary solution I have installed the templating component manually with composer.

```
composer require symfony/templating
```

**Comment by BakoBako** [comment]
@zspine  thanks for temporary solution. Maybe this package need to be in require section of security-bundle not in require-dev, because i am installing dependencies without dev packages for production.

**Comment by xabbuh** [comment]
Can you both confirm that #32379 fixes the issue?

**Comment by BakoBako** [comment]
Works for me!

**Comment by xabbuh** [comment]
Thanks for the confirmation. 👍
