### ISSUE TITLE
[Validation] Add a new PostalCode constraint

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#32356]
**Description**  
Today, via [Commerceguys Addressing project](https://github.com/commerceguys/addressing) I found that Google publishes some useful information about countries which is not available in ICU project: https://chromium-i18n.appspot.com/ssl-address

Among the given data, there's a `zip` value with a regexp validating the ZIP codes of each country. So, I proposing to parse that data to add a ZIpCode constraint.

**How to proceed?**

First, let's wait until the community and Core Team approves this proposal. Please, don't send a pull request unless this is approved.

If this gets approved, this is how it could be solved:

* This file tells you which countries have data defined: https://chromium-i18n.appspot.com/ssl-address/data
* Then you must parse each file with this pattern: `https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/<COUNTRY_CODE>` and look for the `zip` option.

**How to use it**

```php
    /**
     * @Assert\ZipCode(
     *     countries={"ES", "FR", "DE"},
     *     message="This is not a valid ZIP code."
     * )
     */
    protected $zipCode;
```

**Comment by ro0NL** [comment]
Do you suggest to compile this info in Intl?

Im thinking `Countries::getZipCodeFormat('NL')`

**Comment by ro0NL** [comment]
Also see https://github.com/google/libaddressinput/issues/155 / https://github.com/google/libaddressinput/wiki/AddressValidationMetadata

while i like the intend, im not sure about the source of the data nor its reliability :/ or put different; address validation/parsing/standardization is complex and comes with dedicated services to do it. Im not sure SF should get involved in this domain (and implicitly rely on google to do so)

**Comment by javiereguiluz** [comment]
@ro0NL quick comments:

* The information is in the public domain, so it's OK to parse it.
* About the reliability, I'm pretty sure it's OK for the ZIP code (other parts of addresses are more complex or can change frequently). Also, this being used in Chrome means that billions of addresses are validated each day with this information.

But it's OK to disagree with this proposal. So, let's wait for more opinions.

**Comment by ro0NL** [comment]
I was just thinking if one relies on some address (autofill) service already, then validation might be implied (i.e "no api result" = invalid), in this case Symfony should not conflict with the external constraints.

I like the proposal in general, but in above scenario im not  sure it's needed.

**Comment by ro0NL** [comment]
So answering my own question.. :sweat_smile:, with ZipCode + Country you should have a valid combination without any external services involved, while still generating consistent/valid data to feed e.g. autofill services in the feature.

:+1:

**Comment by Seb33300** [comment]
> [A ZIP Code is a postal code used by the United States](https://en.wikipedia.org/wiki/ZIP_Code)

So you should call it `postal code` if it's a feature we can use worldwide.

**Comment by sylfabre** [comment]
@ro0NL Following-up on #34108 we have an already parsed list at AssoConnect so I can write the first version with our list to release the PostalCode constraint and validator, and then the code behind the scene can be later updated with intl data from Google / Symfony/Intl. What do you think?

**Comment by ro0NL** [comment]
i would prefer compatibility with `commerceguys/addressing` and have an external source / some defined standard. Im not sure how much it differs from "your list" :)

we can take some code from https://github.com/commerceguys/addressing/blob/master/scripts/generate_address_data.php

**Comment by sylfabre** [comment]
@ro0NL I didn't know this lib, looks amazing. I needed a constraint to check an Address entity but I may go for their validator without building something just for the postal code

**Comment by javiereguiluz** [comment]
Even if I still like this idea a bit ... the needed data is not in a source repository as reliable as ICU ... so I think it's better if we stick to only using ICU data and close this as "won't fix for now". Thanks!
