### ISSUE TITLE
[Local web server] Incorrect db name 

### ISSUE THREAD

**Issue by Surfoo** [symfony/symfony#32355]
**Symfony version(s) affected**: 4.3.2

**Description**  
On my dev environment, `DATABASE_URL` is: `DATABASE_URL=mysql://root:example@127.0.0.1:3306/fla`

If I use `symfony server:start --no-tls`, I get this error:
```
An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'main'
```
After a quick search, the `DATABASE_URL` used by DBAL is:
```
mysql://root:example@127.0.0.1:3306/main?sslmode=disable&charset=utf8mb4
```

If I run `php -S localhost:8000 -t public`, I have the correct database name `fla`, not `main`

I don't understand where the db name is chosen, in the symfony binary?

**Comment by javiereguiluz** [comment]
@Surfoo thanks for reporting this problem. for issues related to the local server we have a dedicated repository. So, I've moved this issue to https://github.com/symfony/cli/issues/108  and that's why I'm closing this one. Thanks.

**Comment by Surfoo** [comment]
:+1:
