### ISSUE TITLE
Can't install symfony/dom-crawler on symfony 3.4

### ISSUE THREAD

**Issue by lowki** [symfony/symfony#32350]
**Symfony version(s) affected**: 3.4

**How to reproduce**  
symfony new my_project_name 3.4
cd my_project_name
composer require symfony/dom-crawler

Problem 1
    - Conclusion: don't install symfony/dom-crawler v4.3.2
    - Conclusion: don't install symfony/dom-crawler v4.3.1
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.0
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.1
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.10
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.11
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.12
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.13
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.14
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.15
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.16
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.17
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.18
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.19
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.2
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.20
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.21
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.22
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.23
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.24
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.25
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.26
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.27
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.28
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.29
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.3
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.4
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.5
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.6
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.7
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.8
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.9
    - don't install symfony/dom-crawler v4.3.0|remove symfony/symfony v3.4.29
    - don't install symfony/dom-crawler v4.3.0|don't install symfony/symfony v3.4.29
    - Installation request for symfony/dom-crawler ^4.3 -> satisfiable by symfony/dom-crawler[v4.3.0, v4.3.1, v4.3.2].
    - Installation request for symfony/symfony 3.4.* -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].

**Additional context**  
Php7.2.16 on Debian 9.8

**Comment by xabbuh** [comment]
What is the output of `composer show`?

**Comment by derrabus** [comment]
You are using the old Symfony Installer, which installs Symfony using the `symfony/symfony-standard` distribution. This is deprecated, but you may still do that. However, the Symfony installation you get depends on Symfony's monorepo (`symfony/symfony`) which already includes the DomCrawler component. There is no need to install it.

Please consider migrating away from the old Symfony Installer to the Symfony Client. See https://symfony.com/download for details.

**Comment by GromNaN** [comment]
You are trying to install `symfony/dom-crawler: 4.3` with the fullstack `symfony/symfony: 3.4`. These packages conflicts because `symfony/symfony` already provides `symfony/dom-crawler` : https://github.com/symfony/symfony/blob/3.4/composer.json#L48

If you run this command `composer require  symfony/dom-crawler:^3.4` it should work but will not install anything.
