### ISSUE TITLE
[Ldap] Allow newer LDAP options

### ISSUE THREAD

**Issue by binarious** [symfony/symfony#32362]
**Description**  
Similar to https://github.com/symfony/symfony/issues/18448, but [new options](https://php.net/manual/fr/function.ldap-get-option.php) have been added to php since then (`LDAP_OPT_X_TLS_REQUIRE_CERT` for example).

**Comment by Simperfit** [comment]
Do you want to implement the new options ?

**Comment by Simperfit** [comment]
closed by #32447

**Comment by binarious** [comment]
@Simperfit 
> Do you want to implement the new options ?

Sorry, forgot to answer. Thanks for your work.
