### ISSUE TITLE
PHP 7.4 - Allowed memory size exhausted in MergeExtensionConfigurationPass

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#32368]
(I know I know, PHP 7.4 has not been released, but Im logging this as Im testing PHP 7.4 alpha 2 with my production app - feel free to comment and then close if you want :))

On a (large) production Symfony 4.3.2 app running PHP 7.3.6 - No issues :-) 

Switch to PHP 7.4 alpha 2 (fpm, all dockerized) then I get the following message. I tried pushing all the memory limits higher but ultimately nothing allows this to work. 

(1/1) OutOfMemoryExceptionError: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 140176491831296 bytes)
--
in MergeExtensionConfigurationPass.php line 125

<img width="1087" alt="Screenshot 2019-07-04 at 14 04 50" src="https://user-images.githubusercontent.com/400092/60668807-bb6e5880-9e64-11e9-82ff-6898c15dad11.png">

**Comment by linaori** [comment]
Perhaps a serialization bug? https://github.com/symfony/symfony/blob/e3927b62942057bc45e88798134589f72b761ca7/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L125

**Comment by derrabus** [comment]
For the record: php tries to allocate ~128 Terabyte on that line. 😮

**Comment by nicolas-grekas** [comment]
I'm closing because this is premature: let's first make tests pass on 7.4.
And meanwhile, hope that PHP bugs will be fixed.
Having a mix of possible reasons doesn't make this actionable.
Thanks for trying again later, when #32289 is merged a least :)

**Comment by PhilETaylor** [comment]
No worries - good enough for me. So far now we just say Symfony 4 is not compatible with PHP 7.4 :) yet... :)
