### ISSUE TITLE
[Messenger] Remove deprecated call to ReflectionType::__toString() for PHP 7.4 support

### ISSUE THREAD

**Issue by brunowowk** [symfony/symfony#32397]
This call is throwing a deprecation warning on php 7.4:
https://github.com/symfony/symfony/blob/09e3cef7a0ab17b71e8b10f108c652bd5fc9271b/src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php#L222

```
Deprecated: Function ReflectionType::__toString() is deprecated in /var/www/app/vendor/symfony/messenger/DependencyInjection/MessengerPass.php on line 222
```
The alternative is to use `getName()`:
```
         return [$parameters[0]->getType()->getName()]; 
```

**Comment by Simperfit** [comment]
@Tobion this can be closed
