### ISSUE TITLE
[DoctrineBridge] Remove RegistryInterface

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#32394]
The doctrine bridge contains the interface `Symfony\Bridge\Doctrine\RegistryInterface`.

* The only implementation of that interface that I know of is `Doctrine\Bundle\DoctrineBundle\Registry` which has been triggering deprecation errors for each method defined by the interface for 6.5 years now: https://github.com/doctrine/DoctrineBundle/commit/89c7e1486dcf162ef0b5848209748fcc556e1486

* Its parent interface `Doctrine\Common\Persistence\ManagerRegistry` is an equal replacement.

* I haven't found a single reference to the interface in the symfony codebase (except for the one I've removed in #32354).

I find the very existence of this interface highly confusing and suggest to deprecate the interface in 4.4 and remove it with Symfony 5.

**Comment by fabpot** [comment]
Let's do it!
