### ISSUE TITLE
Type hinting new Event class in EventDispatcherInterface::addListener causes FatalThrowableError

### ISSUE THREAD

**Issue by alxndrbauer** [symfony/symfony#32403]
**Symfony version(s) affected**: since 4.3

**Description**  
Using the new `\Symfony\Contracts\EventDispatcher\Event` as type hint in `\Symfony\Component\EventDispatcher\EventDispatcherInterface::addListener`
causes an FatalThrowableError when listening to an `\Symfony\Component\HttpKernel\Event\KernelEvent`.

**How to reproduce**  
```
$eventDispatcher->addListener(KernelEvents::TERMINATE, function (Event $event) {
           // some code
});
```
I´m not sure if this behavior is intended and we should just use the exact Event we expect. 
Using the deprecated class `\Symfony\Component\EventDispatcher\Event` works.

**Possible Solution**  

**Additional context**  
Error Message
> Argument 1 passed to App\Controller\BlogController::App\Controller\{closure}() must be an instance of Symfony\Contracts\EventDispatcher\Event, instance of Symfony\Component\HttpKernel\Event\TerminateEvent given

**Comment by xabbuh** [comment]
This looks logical to me as the `TerminateEvent` is not a subclass of the `Event` class from the contracts.

**Comment by alxndrbauer** [comment]
Do u think it´s worth to be mentioned in the docs or in the upgrade guide to 4.3 that u cant just replace the old with the new event class in such cases?

**Comment by xabbuh** [comment]
Not sure, I mean implicitly that's logical because the new dispatcher signature accepts any object argument. But if more people are confused about it, adding an extra note doesn't really hurt.

**Comment by alxndrbauer** [comment]
ok, then i close this. if more people report this, we can add a note.
