### ISSUE TITLE
PHPunit Bridge - Installation process is non standard and can cause problems with other tools like PHPStam

### ISSUE THREAD

**Issue by brpaz** [symfony/symfony#32405]
Hello.

Right now, PHPUnit bridge only effectively installs PHPUnit package, when running vendor/bin/simple-phpunit for the first time.

This process is non-standard and it can cause some problems and confusion.

For example, I am using PHPStan to analyze my code in my CI Pipeline, including test code.

PHPStan requires me to specify the path to the PHPunit autoload file in its configuration, which doesn't exist unless I ran the simple-phpunit command before, which I don't want to do, since these are two different stages on my Pipeline. 

Also, this behavior of installing other packages at runtime is also not common regarding other composer packages and can lead to some confusion.

Why can´t PHPUnit cant be installed as a regular composer package? Or maybe using some "post-install" script to handle the PHPUnit installation instead of doing it at runtime.

Thank you.

**Comment by derrabus** [comment]
> Why can´t PHPUnit cant be installed as a regular composer package?

It can. Just do it. 😃 

Related: #31948

**Comment by ro0NL** [comment]
> PHPStan requires me to specify the path to the PHPunit autoload file in its configuration, which doesn't exist unless I ran the simple-phpunit command before, which I don't want to do, since these are two different stages on my Pipeline

PHPStan requires it for analyzing, installing PHPUnit first belongs to this stage IMHO

```
vendor/bin/simple-phpunit install && phpstan ...
```

**Comment by xabbuh** [comment]
The `install` command looks like the solution to the initial issue to me. I am closing here as it doesn't seem that there is anything to be done. But please leave a comment if you disagree and we can consider to reopen.
