### ISSUE TITLE
Multiple @Routes Annotations  completely break caching

### ISSUE THREAD

**Issue by echonox** [symfony/symfony#32406]
**Symfony version(s) affected**: 4.3.2

**Description**  
Using Multiple Route Annotation for the same method in a controller completely breaks the cache, and `cache:clear` or `cache:warmup` always generates the old cache

**How to reproduce**  
1. Create simple console symfony:
symfony new app
2. install annotation
consumer require annotations
3. create a controller
4. add 2 route annotation to the index method
   ```
    /**
     * @Route("/hello/world", name="first")
     * @Route("/not/working", name="second")
     */
    public function index(){
        return $this->json(['username2' => 'jane2.doe']);
    }
   ```
3. list all routes in the app with debug:router
Note: Both routes are listed
4. Run symfony Server
- symfony server:start
NOTE: App works fine
5. Stop server
6. Make any change in the controller
- Change Route paths
- OR Remove one of the Router or both
- OR change the return response data of the index method
7. Clear Cache with clear:cache or clear:warmup or event rm -vf var/cache/*
8.  list all routes in the app with debug:router
NOTE: no mather what changes I did to the routes the old route config is still shown
9. Run Symfony Server
NOTE:
1. Old route still work 
2. The response data in the old route is still old
3. The new Routes don't work!

**Possible Solution**  
The Only solution that worked for me is renaming the Controller and that somehow triggered a proper rebuild of the cache...

**Additional context**  
NOTE: nor cache:clear, cache:warmup, rm -rf var, rm -vf var/cache/* worked, also I am using Windows 10 latest build for this with PHP 7.3.6

**Comment by Zowac** [comment]
Hi,

I did all steps and everything was good

**Comment by echonox** [comment]
@Zowac  tnx for testing, I can't repro anymore, closing issue..

P.S: for anyone having the same issue try rebooting windows.. it worked for me..
