### ISSUE TITLE
There are no commands defined in the "translation" namespace.

### ISSUE THREAD

**Issue by tutosfaciles48** [symfony/symfony#32414]
**Symfony version(s) affected**: 4.3.2

**Description**  
php bin/console translation:update --dump-messages produce error in title, even by installing the component

**How to reproduce**  
run `php bin/console translation:update --dump-messages` or `php bin/console translation:update --dump-messages --force fr` (for example)

**Possible Solution**  
Symfony don't seems to recognize this package

**Additional context**  
Windows 10
![command error](https://scontent.tutosfaciles48.com/i/6e0d0093a33ef179f26a11305141eb31.png)

**Comment by xabbuh** [comment]
Did you enable translations in the framework config? If so and the error doesn't go away, can you please create a small example application that allows to reproduce?

**Comment by Simperfit** [comment]
Maybe it could be nice to add a little type-hint to say to enable it in the framework config.

**Comment by tutosfaciles48** [comment]
this work on a new symfony skeleton project but not work at all in the previous project

**Comment by ro0NL** [comment]
@Simperfit i think we're missing all core commands in https://github.com/symfony/symfony/blob/d27c5307f0e7b74c1d369a51fe65938a1f39ea3f/src/Symfony/Bundle/FrameworkBundle/EventListener/SuggestMissingPackageSubscriber.php#L27-L45 :)

**Comment by xabbuh** [comment]
@tutosfaciles48 Please show the output of `bin/console debug: config framework`.

**Comment by tutosfaciles48** [comment]
[debug_framework.txt](https://github.com/symfony/symfony/files/3366087/debug_framework.txt)

**Comment by tutosfaciles48** [comment]
`
Current configuration for extension with alias "framework"
==========================================================

framework:
    router:
        resource: 'kernel::loadRoutes'
        type: service
        enabled: true
        strict_requirements: true
        utf8: true
        http_port: 80
        https_port: 443
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_redis_provider: 'redis://localhost'
        default_memcached_provider: 'memcached://localhost'
        default_pdo_provider: database_connection
        pools: {  }
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        enabled: true
        storage_id: session.storage.native
        cookie_httponly: true
        gc_probability: 1
        save_path: '%kernel.cache_dir%/sessions'
        metadata_update_threshold: 0
    php_errors:
        log: true
        throw: true
    translator:
        enabled: false
        default_path: F://Developpement/WebApp/translations
        fallbacks:
            - fr
        logging: false
        formatter: translator.formatter.default
        paths: {  }
    assets:
        version_strategy: App\Asset\VersionStrategy\DateVersionStrategy
        enabled: true
        version: null
        version_format: '%%s?%%s'
        json_manifest_path: null
        base_path: ''
        base_urls: {  }
        packages: {  }
    default_locale: fr
    validation:
        email_validation_mode: html5
        enabled: true
        enable_annotations: true
        static_method:
            - loadValidatorMetadata
        translation_domain: validators
        mapping:
            paths: {  }
    profiler:
        only_exceptions: false
        enabled: true
        collect: true
        only_master_requests: false
        dsn: 'file:%kernel.cache_dir%/profiler'
    http_method_override: true
    ide: null
    trusted_hosts: {  }
    csrf_protection:
        enabled: null
    form:
        enabled: true
        csrf_protection:
            enabled: null
            field_name: _token
    esi:
        enabled: false
    ssi:
        enabled: false
    fragments:
        enabled: false
        path: /_fragment
    workflows:
        enabled: false
        workflows: {  }
    request:
        enabled: false
        formats: {  }
    templating:
        enabled: false
        hinclude_default_template: null
        form:
            resources:
                - 'FrameworkBundle:Form'
        engines: {  }
        loaders: {  }
    annotations:
        enabled: true
        cache: php_array
        file_cache_dir: '%kernel.cache_dir%/annotations'
        debug: true
    serializer:
        enabled: true
        enable_annotations: true
        mapping:
            paths: {  }
    property_access:
        magic_call: false
        throw_exception_on_invalid_index: false
    property_info:
        enabled: true
    web_link:
        enabled: true
    lock:
        enabled: false
        resources:
            default:
                - flock
    messenger:
        enabled: false
        routing: {  }
        serializer:
            id: messenger.transport.symfony_serializer
            format: json
            context: {  }
        transports: {  }
        default_bus: null
        buses:
            messenger.bus.default:
                default_middleware: true
                middleware: {  }

`

**Comment by xabbuh** [comment]
According to the output translation support is disabled in your application. You need to enable it to be able to use the `translation:*` command. I am closing here as there is no bug. If you need help in configuring translation support, I suggest to use one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by ro0NL** [comment]
@xabbuh we could still patch `SuggestMissingPackageSubscriber` to hint for this..

**Comment by Simperfit** [comment]
I agree

Le lun. 8 juil. 2019 à 09:02, Roland Franssen <notifications@github.com> a
écrit :
