### ISSUE TITLE
Blank page on first time open website [Nginx(PHP-FPM), Symfony2.8, PHP 5.5]

### ISSUE THREAD

**Issue by mzarain08** [symfony/symfony#32412]
Hi All, 

I'm getting blank on first time when i open my website and after if i refresh that page again then it loads perfectly, I'm using NGINX web server with following my website configuration: 

PHP 5.5.38
NGINX with PHP-FPM
Centos7
Symfony 2.8.4-DEV

However I have enabled all errors every where in php, nginx, php-fpm but unluckily i didn't get any error anywhere in my server. Always when i first time load my website showing blank page in production (app.php) and its working fine in Development (app_dev.php) even in first load. 
I have applied all rules, permissions but no any luck, full access 777 rights to app/cache/* & app/logs/* . Page is blank & there is nothing also in view soures its all blank with no any error. 

Thanks in advance for any kind of help....
Any help appreciated
@fabpot @fabian @FabienD

**Comment by linaori** [comment]
Heya, for support please check https://symfony.com/support and please don't ping people directly like that.

Also please be aware that your PHP version is not supported, and your Symfony versions is out of date (by far).

**Comment by mzarain08** [comment]
Thanks @linaori. 
Actually this version is working fine with apache server everthing is fine, i have moved from apache to nginx  & getting this problem.

**Comment by tutosfaciles48** [comment]
Hello, in the future (and now) this version of php is out of date. Please consider upgrading you version even if it's working with you. This version contain security leaks (and probably this symfony version).

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by slince** [comment]
```bash
php app/console cache:clear --env=prod
```
May be you should warm runtime cache

**Comment by mzarain08** [comment]
**[SOLVED]** I solved myself there was session + cookie issue creation problem which was not giving error. Thanks all for your support
