### ISSUE TITLE
[DependencyInjection] Do we support scalar services?

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#32411]
While working on #32266, I noticed that adding `object` type declarations for services [breaks the test suite](https://github.com/symfony/symfony/pull/32266#issuecomment-508941073).

Supporting scalar services would be legal according to PSR-11, but it violates the contract documented by the docblocks of our `ContainerInterface`.

I suggest to either…
* Document the possibility of scalar services and cover this behavior with tests inside the DI component or…
* deprecate scalar services in 4.4 and add `object` type declarations to master.

**Comment by nicolas-grekas** [comment]
Option 3: statu quo. We won't add types because it won't provide anything but break special situations that are sometimes needed, but we don't want to advertise.

**Comment by derrabus** [comment]
Mmmh, but if that needed functionality is not documented, I probably won't be the last to break it accidentally.

**Comment by nicolas-grekas** [comment]
Did you break it? Or did the test suite prevent doing so ? But anyway, we're not going to break existing behaviors, unless alternatives exists, right?

**Comment by derrabus** [comment]
> Or did the test suite prevent doing so ?

A test from HttpKernel prevented it. The DI test suite was all green. To me this looks like HttpKernel is relying on coincidences. This is why I’ve opened this ticket in the first place. If this a feature DI provides for HttpKernel, at least one test in DI should indicate that this feature was broken by the change.

I mean, those type-hint PRs have already uncovered quite a few broken tests and odd execution paths, which is a good thing, imho. And since @Tobion and I were both confused by scalars being stored in the container, I did not want to bury this oddity with my PR and opened this ticket for investigation.

**Comment by fabpot** [comment]
A service should be an object :)

**Comment by nicolas-grekas** [comment]
Did the test suite catch this?
https://github.com/symfony/symfony/blob/6811aaa8e087665769dd66c69fb3109d002196ef/src/Symfony/Bundle/WebProfilerBundle/Resources/config/profiler.xml#L63-L68
This definition is from real world ;)

**Comment by derrabus** [comment]
> A service should be an object :)

I notice how you chose the work "should" instead of "must". 😃 

@nicolas-grekas This is the test I was talking about.

https://github.com/symfony/symfony/blob/6811aaa8e087665769dd66c69fb3109d002196ef/src/Symfony/Component/HttpKernel/Tests/DependencyInjection/RegisterControllerArgumentLocatorsPassTest.php#L319-L349

> This definition is from real world ;)

Good example. 🤔 

So scalar services might not be an official feature, but they're possible and we rely on them occasionally. That puts option 2 off the table. Option 1 then (add a test, update docblocks)?

**Comment by nicolas-grekas** [comment]
Option 3. Because updating a docblock defeats the "should" by providing too much visibility.
Adding a specific test case why not :)

**Comment by derrabus** [comment]
Opened #32432
