### ISSUE TITLE
[Messenger] - formatDateTime is not correct in oracle

### ISSUE THREAD

**Issue by roukmoute** [symfony/symfony#32427]
**Symfony version(s) affected**: 4.3.1

**Description**  
`ORA-01858: a non-numeric character was found where a numeric was expected`

**How to reproduce**  
Implement Messenger with Oracle

**Possible Solution**  
If we remove `\T` from `$dateTime->format('Y-m-d\TH:i:s');` in `\Symfony\Component\Messenger\Transport\Doctrine\Connection::formatDateTime`, it works.
I think it is a special things from Oracle, is there any specifity for format datime in relation to the database?

Could we use `\Doctrine\DBAL\Types\DateTimeType` instead?

**Additional context**  
![image](https://user-images.githubusercontent.com/2140469/60811457-94c75f00-a18f-11e9-9aeb-4d0a1d47cb15.png)

**Comment by weaverryan** [comment]
Ping @vincenttouzet! What is the `\T` in the date string for? Is that a tab character? Doctrine DBAL seems to just use a space character for most platforms (https://github.com/doctrine/dbal/blob/ea92d5602028676d06021bebe8b806e24aa99f58/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L3313-L3316)... but it is true that using `DateTimeType` (or `$this->driverConnection->getDatabasePlatform()->getDateTimeFormatString()` would be better.

**Comment by vincenttouzet** [comment]
@weaverryan Hum It's an old habit that I have. The T is part of the ISO 8601 DateTime format. But I think we can get rid of it in that case.

**Comment by weaverryan** [comment]
If we use the database platform, I think we can entirely allow doctrine to handle this anyways :)

**Comment by roukmoute** [comment]
Closed this in https://github.com/symfony/symfony/pull/32456
