### ISSUE TITLE
RepeatedType mapping doesn't work

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#32445]
**Symfony version(s) affected**: 4.3.2

**Description**  
Hi. I would like to show error for both field. But it's showing for the first  field or if do error_mapping, error completly disappears for the first field.

**How to reproduce**  
```
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        return $builder
            ->add('plain_password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat Password'],
                'error_mapping' => [
                    'plain_password[first]' => 'first',
                    'plain_password[second]' => 'second'
                ],
            ])
            ->add('submit', SubmitType::class);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        return $resolver->setDefaults([
            'error_mapping' => [
                'plainPassword' => 'plain_password'
            ]
        ]);
    }
```

**Possible Solution**  
No solution for me.

**Additional context**  
~

**Comment by xabbuh** [comment]
If I don't miss anything, that's not possible right now and would require a new option in the `RepeatedType`. I am not sure if that's something, developers would use frequently (#7359 reported the exact same opposite).

**Comment by RSalo** [comment]
Yeap. Maybe this is individual case. Thanks for help! @xabbuh
