### ISSUE TITLE
Docker build: Symfony 4.2.8 class PdoSessionHandler does not exist

### ISSUE THREAD

**Issue by legalvisio-schillermann** [symfony/symfony#32459]
If I've default bind in the services.yaml and framework.yaml includes the handler id for PdoSessionHandler then I get a error after composer install and cache clear.

> Invalid service ... class ... PdoSessionHandler does not exist.

Without docker I've no problem to install composer packages and clear cache.
[There is already a stackoverflow entry. ](https://stackoverflow.com/questions/56936776/docker-build-symfony-4-class-pdosessionhandler-does-not-exist)

**Comment by xabbuh** [comment]
We will need some more concrete example to allow to reproduce and debug this.

**Comment by legalvisio-schillermann** [comment]
If the `PdoSessionHandler` is registered in the session config under `handler_id`, the cache clear will establish a connection to the database. However, there is no database for the docker image build process. As a result, the service can not be loaded.
