### ISSUE TITLE
[Bundles] Allow to customize the entire dir structure

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#32453]
**Description**  
I'd love to allow bundles to have the exact same dir structure as full Symfony apps. It's such a concise, beautiful and self-explanatory structure!

So, now that we've added `getPublicDir()` in #31975 ... what about adding the rest of methods needed to customize the dir structure?

* `getConfigDir()`
* `getTemplatesDir()`
* `getTranslationsDir()`

`src/` and `tests/` can be customized in other ways (Composer, PHPUnit, etc.)

**Comment by yceruto** [comment]
A big :+1: for directory customization.

According to https://github.com/symfony/symfony/pull/31975 all methods should be called `...Path()`, they are relative paths to the bundle path.

I can take `getTemplatesPath()` and `getTranslationsPath()` so far.

**Comment by javiereguiluz** [comment]
We may rename `getPublicPath()` as `getPublicDir()` (see #32452) because all dirs are paths but not all paths are dirs (and here we always need a dir).

**Comment by linaori** [comment]
Configuration over convention, I like it!

**Comment by ro0NL** [comment]
while i like the intend, should we really assume all bundles have such concepts? Is there any downside for, let's say, low-level library bundles?

Not sure, but maybe a global framework `PathProvider` concept might work, to let both kernel and bundles provision paths as needed (e.g. interface based).

Ultimately this already applies to the "public dir", not all bundles have this concept.

**Comment by derrabus** [comment]
I like the idea of having a configurable directory structure! Just a small question:

> * `getConfigDir()`

Is this really a hardcoded convention right now? This should be configurable via the extension already.

https://github.com/symfony/symfony/blob/d3c17f2aded0fa92f938eb9e0dc56ee9902d558a/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L38

**Comment by emodric** [comment]
> Is this really a hardcoded convention right now?

Some code uses the hardcoded path, I think. Doctrine ORM mappings and validator component config (`validation.yml`) come to mind.

**Comment by ro0NL** [comment]
But then overriding `getConfigDir` in your bundle requires another change in your extension, and we're not really solving anything for the user :}

**Comment by javiereguiluz** [comment]
@ro0NL if this proposal is approved, we'll update all the first-party bundles and the most important third-party bundles to be sure that they are using the new methods.

**Comment by ro0NL** [comment]
@javiereguiluz how will an extension retrieve the bundle or the path? I think we're hitting a design limitation at this point, but i may miss it... haven't looked into it in depth.

**Comment by nicolas-grekas** [comment]
We cannot get rid of conventions unless we change the design completely.
I also think standardization is a useful property of the current system.
If we think a different layout would be better, let's make it work in `FrameworkExtension` and done.
Bundles are meant to be shared, and shared means the more standards the better.

**Comment by yceruto** [comment]
Here we go -> https://github.com/symfony/symfony/pull/32845 :crossed_fingers:
