### ISSUE TITLE
[Form] Implement the persistent file type

### ISSUE THREAD

**Issue by vicb** [symfony/symfony#3246]
It would be good to (re-)introduce the persistent file type.

The support was dropped [here](https://github.com/symfony/symfony/commit/852a4c9c6a4103fcbc87e99135db4dadbc7ce2a4).

My work on this is available in some branches of my fork: 

- [splfileinfo](https://github.com/vicb/symfony/tree/splfileinfo),
- [storage-api](https://github.com/vicb/symfony/tree/storage-api),
- [temp-storage-9747](https://github.com/vicb/symfony/tree/temp-storage-9747)

Corresponding PR are #748, #674.

Issues to be solved:

- See [the commit message](https://github.com/symfony/symfony/commit/852a4c9c6a4103fcbc87e99135db4dadbc7ce2a4) from fabpot when support has been dropped,
- Invalid files were also persisted
- ?

**Comment by jakzal** [comment]
Closing as it's been over four years since this issue was created, and no one seems to be eager to pick it up.
