### ISSUE TITLE
UniqueEntity constraint not working properly with 2 fields

### ISSUE THREAD

**Issue by erethilclaw** [symfony/symfony#32477]
Symfony version4.3.2

I want to constraint the creation of a register by date and user, so in class i have declared

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\ButlletiRepository")
 * @UniqueEntity(
 *     fields={"user", "dataButlleti"},
 *     errorPath="dataButlleti",
 *     message="Ja has creat un butlleti per aquesta data")
 */
class Butlleti
```

```php
/**
     * @ORM\Column(type="datetime")
     */
    private $dataButlleti;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="butlletins")
     */
    private $user;
```

But is not working, I can create infinite register with the same date but when i try to edit works because detect there are already a register with the same date and use.

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by erethilclaw** [comment]
my controller
`public function butlletiAdd(Request $request, EntityManagerInterface $em)
    {

        $form = $this->createForm(ButlletiFormType::class);
        $form->handleRequest($request);

        $today = new \DateTime();
        /**
         * @var User $user
         */
        $user = $this->getUser();
     
        if ($form->isSubmitted() && $form->isValid()  ) {
          
            $this->addFlash('success', 'Butlleti creat!');
            /**
             * @var Butlleti $butlleti
             */
            $butlleti = $form->getData();

            $butlleti->setCreat($today);
            $butlleti->setUser($user);

            foreach ($butlleti->getLiniesButlleti() as $lineaButlleti){
                $this->newLinieaButlletiSetData($lineaButlleti, $user, $today);
            }

            $em->persist($butlleti);
            $em->flush();

            return $this->redirectToRoute('butlletiView', array('id' => $butlleti->getId()));
        }

        return $this->render('butlleti/butlletiForm.html.twig', [
            'butlletiForm' => $form->createView(),
            'actionText'=> 'Crear Butlleti',
        ]);
    }

    /**
     * @Route("/edit/{id}", name="butlletiEdit")
     */
    public function butlletiEdit(Request $request, EntityManagerInterface $em, Butlleti $butlleti)
    {

        $form = $this->createForm(ButlletiFormType::class, $butlleti);
        $form->handleRequest($request);

        $user = $this->getUser();

        if ($form->isSubmitted() && $form->isValid() && $user->getId()== $butlleti->getUser()->getId()) {
            $this->addFlash('success', 'Butlleti modificat!');
            /**
             * @var Butlleti $butlleti
             */
            $butlleti = $form->getData();
            $today = new \DateTime();
            $butlleti->setCreat($today);
            /**
             * @var User $user
             */
            $user = $butlleti->getUser();

            foreach ($butlleti->getLiniesButlleti() as $lineaButlleti){
                if (!$lineaButlleti->getUser()){
                    $this->newLinieaButlletiSetData($lineaButlleti, $user, $today);
                } else {
                    $lineaButlleti->setModificat($today);
                }
            }

            $em->persist($butlleti);
            $em->flush();

            return $this->redirectToRoute('butlletiView', array('id' => $butlleti->getId()));
        }

        return $this->render('butlleti/butlletiForm.html.twig', [
            'butlletiForm' => $form->createView(),
            'actionText'=> 'Editar Butlleti',
        ]);
    }`

i call 2 form types one inside the other

`class ButlletiFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dataButlleti', DateType::class, [
                'attr' => [
                    'class' => 'datePicker',
                    'autocomplete' => 'off'
                ],
                'widget' => 'single_text',
                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,
            ])
            ->add('liniesButlleti', CollectionType::class, [
                'entry_type' => LiniaButlletiFormType::class,
                'entry_options' => [
                    'label' => false,
                ],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'label' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Butlleti::class,
        ]);
    }
}`

`class LiniaButlletiFormType extends AbstractType
{
    /**
     * @var CodeToOrdreTransformer
     */
    private $transformer;

    public function __construct(CodeToOrdreTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('hores', NumberType::class)
            ->add('observacions')
            ->add('ordre', TextType::class, [
                'invalid_message' => 'No existeix aquesta ordre'
            ])
        ;
        $builder->get('ordre')
            ->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => LiniaButlleti::class,
        ]);
    }
}`

is a classic crud, doesn't have anything special beside some hand setData.

**Comment by xabbuh** [comment]
I'd appreciate if you could set up some real application that one can just clone, install all dependencies and execute it. This will highly increase the chance that someone is going to try to debug this.

**Comment by erethilclaw** [comment]
I understand, i have uploaded all the project at https://github.com/erethilclaw/UniqueEntity
the entity with  i have the problem is /src/entity/butlleti.php, fixtures are created so with
 php bin/console doctrine:fixtures:load
you will have some dummy data.

thanks for your time

**Comment by erethilclaw** [comment]
Found the error, as i don't pass the user in the form when it validates always gets a null user, so never restricts the creation of the register, that's why create didn't work and edit yes because the entity had the date and the user.

I close this, my mistake, sorry.

**Comment by xabbuh** [comment]
@erethilclaw I am glad that you were able to solve this. 👍
