### ISSUE TITLE
BC-break ExceptionListener and FlattenException

### ISSUE THREAD

**Issue by Devristo** [symfony/symfony#32473]
**Symfony version(s) affected**: 4.4 branch

**Description**  

Some third-party libraries / bundles depend on `\Symfony\Component\HttpKernel\EventListener\ExceptionListener` and `\Symfony\Component\Debug\Exception\FlattenException`. In Symfony 4.4 a `\Symfony\Component\ErrorCatcher\Exception\FlattenException` is thrown instead.

An example of a third-party project is Api-platform. See https://github.com/api-platform/core/blob/8b9203436c162e82ce42515f8e6eacd7077e705b/src/Action/ExceptionAction.php#L62 for the dependency on `Debug\Exception\FlattenException`.

Probably the way Api-Platform uses the ExceptionListener is not so common amongst other projects. Should I open an issue there instead?

**How to reproduce**  

Try exception handling on api-platform on Symfony 4.4

**Possible Solution**  

 * Make the FlattenException in ErrorCatcher-component inherit the one in Debug ? Only possible if there is a dependency between the two components.
 
Somewhat related issues:

https://github.com/symfony/symfony/issues/32371

**Comment by javiereguiluz** [comment]
@Devristo the problem is that you are using Symfony 4.4, which hasn't been released yet (it will release on November 2019) and it's making lots of changes these days related to Debug, exceptions and the new components introduced about this.

**Comment by Devristo** [comment]
Thank you, I am aware of that. I often try unreleased versions to see what is ahead and if there are issues I can avoid while developing my projects.

See this issue as a heads up, not more than that ;)

**Comment by fabpot** [comment]
@Devristo And we really appreciate people testing new versions before the official release. That helps a LOT. Thank you for that.

**Comment by stof** [comment]
A solution here could be that when we use a legacy controller for the error rendering, TwigBundle might convert the exception to a Debug one before creating the subrequest.
This depends whether we have a way to differentiate whether the exception controller is written for the old system or the new one.

**Comment by yceruto** [comment]
Another solution might be to create an alias for each legacy class (as we did on https://github.com/symfony/symfony/pull/32665/files), so after the upgrade to 4.4, the code doesn't break if you're using `Symfony\Component\Debug\Exception\FlattenException` or any other legacy class. WDYT?

**Comment by nicolas-grekas** [comment]
Aliases provide no upgrade path so we might be stuck, unable to remove them smoothly in the future I fear...

**Comment by yceruto** [comment]
@Devristo could you check please if 4.4-dev is now working as you expect?

**Comment by Devristo** [comment]
This fixed my issue :)
