### ISSUE TITLE
validation of upload_max_filesize

### ISSUE THREAD

**Issue by kernig** [symfony/symfony#32479]
**Symfony version(s) affected**: seems to be in every version since an old 2.x. I did use 3.4

**Description**  
Not sure if this is a bug or should be a feature request.
The validation(function normalizeBinaryFormat) in symfony/src/Symfony/Component/Validator/Constraints/File.php doesn't work with gigabyte values in php.ini.
In the PHP documentation it says "PHP allows shortcuts for byte values, including K (kilo), M (mega) and G (giga). " so in my opinion these values should work.

**How to reproduce**  
Set upload_max_filesize in php.ini to 1G. I noticed this problem in prestashop, but you can just call this function to get the error.

**Possible Solution**  
I found a fix on this website:
https://kijam.com/tienda/reparar-error-1g-is-not-a-valid-maximun-size-en-prestashop-1-7/

Quote:
You need to edit this file "/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/File.php"

Replace this part:
$factors = array(
'k' => 1000,
'ki' => 1 << 10,
'm' => 1000000,
'mi' => 1 << 20,
);

with this
$factors = array(
'k' => 1000,
'ki' => 1 << 10,
'm' => 1000000,
'mi' => 1 << 20,
'g' => 1000000000,
'gi' => 1 << 30,
);

If you need more details, just let me know.

**Comment by javiereguiluz** [comment]
@kernig thanks for reporting this problem and for all the details. It looks like something Symfony is missing so, would you be willing to contribute this change yourself? If you don't have time or don't want to, it's OK. Thanks.

**Comment by kernig** [comment]
Hi @javiereguiluz, ok, i'll try to send a pull request. Should i do it for a specific version or one for each?
Thank you

**Comment by javiereguiluz** [comment]
As you said, this can be both a feature and a bug. If it's a feature, the PR should be committed against 4.4 branch; if it's a bug, against 3.4 branch.

Personally I think this is more a bug, so I'd try to create the pull request against 3.4 (we only need one PR because once merged, we merge in all the other branches ourselves). Thanks!
