### ISSUE TITLE
[HttpClient] toArray is a bad and wrong name for json

### ISSUE THREAD

**Issue by zorn-v** [symfony/symfony#32481]
Imagine that I got `true` response from API. That method do it right and return PHP `true` (coz json_decode). But... TO ARRAY ? Is `true` IS ARRAY ? Or maybe `123` is array also ? :smile: 

Also someone want to get PHP object instead array (preferences).

Maybe one more method like `getJson($throw = true, $asArray = true)` and deprecate `toArray` ? :smile_cat:

**Comment by ro0NL** [comment]
See #31913 and https://github.com/symfony/symfony/pull/30499#discussion_r264011075 for some more info

**Comment by nicolas-grekas** [comment]
JSON stands for JavaScript *Object* Notation. No API should respond with anything else than an object and/or an array. Yes, this is a should. toArray work with conforming APIs, and will throw a well defined exception when something else is returned. When this happens, one should use getContent() instead.
The links @ro0NL shared are relevant to get a better understanding of why/how things are designed this way.

**Comment by javiereguiluz** [comment]
Also, we're adding more `->to...()` methods, such as `->toStream()` added in #32290.

**Comment by zorn-v** [comment]
Maybe `getJson` is bad name also, but better then `toArray` for method that can return NOT ARRAY.
e.g `var_dump(json_decode('true', true));`

**Comment by zorn-v** [comment]
I'm about naming. not else. (but parameter for return object will be fine too :smile: )

**Comment by ro0NL** [comment]
> but better then toArray for method that can return NOT ARRAY.

it will always return an array, or error as such. That's exactly the main-feature of this method.

**Comment by zorn-v** [comment]
Nope. It just do `json_decode` on ANY DATA
https://github.com/symfony/symfony/blob/d3c17f2aded0fa92f938eb9e0dc56ee9902d558a/src/Symfony/Component/HttpClient/Response/ResponseTrait.php#L151

Data can be simple "json encoded" string for example.

**Comment by ro0NL** [comment]
see a few lines below :)

https://github.com/symfony/symfony/blob/d3c17f2aded0fa92f938eb9e0dc56ee9902d558a/src/Symfony/Component/HttpClient/Response/ResponseTrait.php#L160-L162

**Comment by zorn-v** [comment]
Oooops, missed it )
