### ISSUE TITLE
Symfony Process fails when commandline is too long (>= 2^17 [131072] characters)

### ISSUE THREAD

**Issue by paslandau** [symfony/symfony#32493]
**Symfony version(s) affected**: 4.3.2
`symfony/process                       v4.3.2                   Symfony Process Component`

**Description**  
A `Process` defined with a `$commandline` length of >= 2^17 (131072) characters fails with the exit code 127 ("Command not found")

**How to reproduce**  
```php
// normal process
$commandline = "echo 'hello'";
$p           = new Process($commandline);
$p->run();
sleep(1);
var_dump($p->getExitCode(), $p->getOutput());
// Output:
// int(0)
// string(6) "hello
//"

// process with total length of 2^17 - 1 (= 131071)
$str         = implode("", array_fill(0, 2 ** 17 - mb_strlen("echo ''") - 1, "a"));
$commandline = "echo '$str'";
$p           = new Process($commandline);
$p->run();
sleep(1);
var_dump($p->getExitCode());
// Output:
// int(0)

// process with total length of 2^17 (= 131072)
$str         = implode("", array_fill(0, 2 ** 17 - mb_strlen("echo ''"), "a"));
$commandline = "echo '$str'";
$p           = new Process($commandline);
$p->run();
sleep(1);
var_dump($p->getExitCode());
// Output:
// int(127)
// => "Command not found"

// using an array instead of the "legacy" string yields the same behavior
$str         = implode("", array_fill(0, 2 ** 17 - mb_strlen("echo ''"), "a"));
$commandline = ["echo", $str];
$p           = new Process($commandline);
$p->run();
sleep(1);
var_dump($p->getExitCode());
// Output:
// int(127)
// => "Command not found"
```

**Additional context**  
```
$ php -v
PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.26.2~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```
Test was run from within docker on a Windows host.

**Comment by nicolas-grekas** [comment]
See https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit/19355351
This limit is set by the OS, nothing we can do about.
If you need to pass longer values, you should use env vars.

**Comment by paslandau** [comment]
Was afraid so :(

Would it still make sense to:
- put this somewhere in the docs so that people are aware that this might be an issue?
- change the response code to something more appropriate (not sure if that's possible, though)

Our case:
We've hit this limit thtough a tool (grumphp) that uses git to retrieve a list of changed files to pass them to some code quality tools (php linting, phpstan, ...) and this list of files got "so big" that the underyling symfony process failed without any indication of why.

**Comment by nicolas-grekas** [comment]
Adding doc about this looks worth it, would you mind sending a doc PR?
I'm closing here since we cannot do anything...

**Comment by guruas3** [comment]
@paslandau have you found a workaround for this limit? 
the problem you've described and the one i got is the limit for a single argument and not entire command line length. (MAX_ARG_STRLEN is a Linux-specific constant which was introduced in the 2.6.25 kernel. As of the 2.6.25 kernel, MAX_ARG_STRLEN is defined as 131072 bytes=32 pages of memory)
https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument#120842

i've tried using env vars as suggested above but that still fails with 127 exit code.
