### ISSUE TITLE
[Url validator] Returns false for valid (and existing) url

### ISSUE THREAD

**Issue by kptLucek** [symfony/symfony#32506]
**Symfony version(s) affected**: 4.3.2 (propably earlier versions too)

**Description**  
Url validator returns false (invalid url) on valid, and existing url - pattern issue

**How to reproduce**  
Simply get an validator instance, and validate string/model with Url validator.
Url **must** contain underscores `_` (im amazed to see them in url tho)

```php
$url        = 'http://www.cku_zsr_glubczyce.wodip.opole.pl';
$violations = $this->validator->validate(['url' => $url], [
    new Collection([
        'fields' => [
            'url' => [new Url()]
        ]
    ])
]);
if ($violations->count() > 0) {
/** @var ConstraintViolation $violation */
foreach ($violations as $violation) {
    echo $violation->getPropertyPath() . ' :: ' . $violation->getMessage() . "\n";
}
```

**Possible Solution**  
Update pattern in validator :)

**Additional context**

**Comment by Tobion** [comment]
Can you resolve the url?

https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by kptLucek** [comment]
@Tobion what do you mean?

The url i have provided is a string i want to validate, i have service that does collect alot of data by school-type facilities, and url (like one above) is one of properties i do collect.

Everything is verified, and given url is valid, exists, and may be visited (GET to this url returns valid 200 HTTP response).

All i need is to verify if given "string" is "url" (which should be done by Url validator, but is not in given case).


Link from above shows that subdomain(s) with underscore (_) in their name are very common, however for those validator returns violation.

**Comment by javiereguiluz** [comment]
There are several things to consider:

* If you visit the given `http://www.cku_zsr_glubczyce.wodip.opole.pl/` URL, you can browse the website ... so "it doesn't matter" if some RFC says this is not valid. It is a "valid" URL. At least it's a working URL.
* The custom pattern used by Symfony's UrlValidator.php says it's not a valid URL.
* The PHP URL filter also says that it's not valid: https://3v4l.org/uJ6WX
