### ISSUE TITLE
[Messenger] Cannot specify multiple entity managers for Doctrine middleware

### ISSUE THREAD

**Issue by benr77** [symfony/symfony#32507]
**Symfony version(s) affected**: 4.3.2

**Description**  
I'm working with multiple entity managers. I realised that using the default configuration of the Doctrine middleware only uses the default entity manager

`- doctrine_transaction`

In order to specify which entity manager to use, according to the docs, you can use:

`- doctrine_transaction: ['othermanager']`

However, I initially tried to specify all my entity managers, as the array syntax implies this should be possible - e.g.

`- doctrine_transaction: ['othermanager', 'secondmanager', 'thirdmanager']`

In this last case, I'd expect queries to be placed in to their respective transaction for each entity manager, but what actually happened is three empty transactions were created, containing no queries.

**How to reproduce**  
Set up multiple entity managers and try and use the middleware for a non-default entity manager. See an empty transaction executed.

Specify multiple entity managers for the middleware, all transactions are empty of queries.

I could only get queries to be executed by specifying a single entity manager
`- doctrine_transaction: ['othermanager']`

**Possible Solution**  

Is the correct solution to use the middleware multiple times to accommodate each entity manager?
```
- doctrine_transaction: ['othermanager']
- doctrine_transaction: ['secondmanager']
- doctrine_transaction: ['thirdmanager']
```
This does not seem like a logical configuration to me.

**Comment by Tobion** [comment]
Using multiple entity managers is not supported AFAIK. Defining doctrine_transaction several times as you suggested could work. I would not recommend to use the doctrine_transaction middleware for anything more complex as it's too much magic. You want your transactions to be as short as possible. So just create your transactions manually in your case. I don't think there is anything to do here.

**Comment by benr77** [comment]
I'm not sure I agree. If I'm using a single entity manager and then implementing the Doctrine middleware then it's a valid use case, but if I'm using multiple entity managers suddenly it's not a valid use case? 

If I want transactions to be automatically applied in my command handlers, it's not important which entity manager is being used. Of course the ability to configure this per-EntityManager is handy.

In any case, I do think the docs and configuration are misleading by using an array syntax when specifying the entity manager as it implies that multiple values are supported when in fact they are not.

**Comment by Koc** [comment]
I'm afraid, that multiple transactions from different entity managers wouldn't work as you expect and we got inconsistent state.

1. start transaction for entity manager a
2. start transaction for entity manager b
3. handle command
4. commit transaction for entity manager a
5. commit transaction for entity manager b, but something goes wrong (network lag, mysql has gone away, etc)
6. transaction for entity manager a was already committed, no way to rollback it

Instead of opening multiple transactions for single command we can provide new stamp: `$bus->dspatch($command, [new DoctrineTransactionalStamp($entityManager = 'custom')])` and tweak current middleware to process this stamp. WDYT?

**Comment by xabbuh** [comment]
@benr77 Does @Koc's comment help?

**Comment by benr77** [comment]
Sorry my understanding of @Koc 's comment was that it was a suggestion on how to improve the Messenger component in general, rather than a solution to my particular issue.

In general, I have a command handler processing a command which commits a single transaction on an aggregate root entity, so only 1 of the various entity managers is ever involved at any one time. I just want the Doctrine middleware to auto-flush for ALL of my entity managers. 

Also surely it's bad practice to open multiple transactions on multiple entity managers that depend on each other - this is essentially distributed transactions which has its own set of complexity and problems.

**Comment by Tobion** [comment]
I'm closing this. There is a solution even if it's not nice. But I don't think we need to complicate the middleware for an edge case like this.
