### ISSUE TITLE
absolute_url in twig template missed path of request (only schema hostname asset-link)

### ISSUE THREAD

**Issue by patrickbussmann** [symfony/symfony#32505]
**Symfony version(s) affected**: 4.3.2

**Description**  

    {{ absolute_url(asset('assets/images/header.png')) }}

results in

    http://localhost/assets/images/header.png

But even the settings as the request url contains a path.

    POST http://localhost/example/web/public/api/resetting/request

I expect something like:

    http://localhost/example/web/public/assets/images/header.png

**How to reproduce**  

```php
	<?php
	
	use App\Kernel;
	use Symfony\Component\Dotenv\Dotenv;
	
	require_once __DIR__.'/vendor/autoload.php';
	
	if (!class_exists(Dotenv::class)) {
		throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
	}
	
	(new Dotenv())->load(__DIR__.'/.env');
	
	$kernel = new Kernel('dev', true);
	$kernel->boot();
	
	/** @var \Twig\Environment $twig */
	$twig = $kernel->getContainer()->get('twig');
	$template = $twig->createTemplate("{{ absolute_url(asset('assets/images/header.png')) }}");
	echo $template->render();
	
	/**
	 * Call script via: http://localhost/example/web/public/test.php
	 * Result: http://localhost/assets/images/header.png
	 * Expected: http://localhost/example/web/public/assets/images/header.png
	 */
```

**Additional context**  
Related from the past:
https://github.com/symfony/symfony/issues/15448
https://github.com/symfony/symfony/pull/17503

**Comment by Tobion** [comment]
look like absolute_url does not use the base url of the request (or it's not set correctly)

**Comment by danigv** [comment]
This is solved and documented in https://symfony.com/doc/current/routing.html#generating-urls-in-commands. You have to define the `router.request_context.scheme` and `router.request_context.host` parameters.
