### ISSUE TITLE
[Workflow] No hard dependency to expression language component

### ISSUE THREAD

**Issue by rmikalkenas** [symfony/symfony#32512]
**Symfony version(s) affected**: 4.3.2

**Description**  
Running `composer require workflow` on a project which doesnt have expression language component throws exception `The "Symfony\Component\Security\Core\Authorization\ExpressionLanguage" class requires the "ExpressionLanguage" component. Try running "composer require symfony/expression-language".`

**How to reproduce**  
https://github.com/rmikalkenas/workflow-issue

**Possible Solution**  
Move `symfony/expression-language` dependency in workflow component from `require-dev` to `require`

**Additional context** 
`PHP 7.3.2`

![Screenshot from 2019-07-17 09-02-08](https://user-images.githubusercontent.com/14221532/61350962-fbc0d400-a871-11e9-84a8-6f2c6b11e851.png)

**Comment by rmikalkenas** [comment]
Looks like it might be related to #32395

**Comment by xabbuh** [comment]
I am not able to reproduce this issue. Can you create a small example application that allows us to do so?

**Comment by lyrixx** [comment]
I guess you are using a guard expression ?

**Comment by rmikalkenas** [comment]
I'm not using expressions, bus the project uses fos rest bundle, maybe it uses.. I will try to investigate and create an example app.

**Comment by rmikalkenas** [comment]
Ok, I have managed to reproduce the exception: https://github.com/rmikalkenas/workflow-issue

Looks like the problem is in `Symfony\Component\DependencyInjection\Compiler\AutowirePass::createTypeNotFoundMessageCallback` which uses container which has `workflow.security.expression_language` service.

Correct me if I'm wrong..

**Comment by lyrixx** [comment]
@nicolas-grekas I don't really understand this issue. This is not really related to the workflow. Could you have a look? Thanks

**Comment by rmikalkenas** [comment]
Indeed, its more related to security bundle and DI. At first i thougt it was related to workflow, because exception started when i installed workflow component and created models

**Comment by lyrixx** [comment]
Yes, it's really weird. It occurs when Symfony try to load this file
```

namespace Symfony\Component\Workflow\EventListener;

use Symfony\Component\Security\Core\Authorization\ExpressionLanguage as BaseExpressionLanguage; // HERE
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Workflow\Exception\RuntimeException;

class ExpressionLanguage extends BaseExpressionLanguage
{
```php

If I comment the line with `// HERE`, it works well

So I have two questions:

* Why does symfony try to load this file ?
* Why is there an exception when loading this other file ?

IMHO, there is 2 issues to fix here

**Comment by xabbuh** [comment]
Can you show the full stack trace? Maybe the same root cause as #32395?

**Comment by rmikalkenas** [comment]
![Screenshot from 2019-07-17 09-02-08](https://user-images.githubusercontent.com/14221532/61350905-c916db80-a871-11e9-8711-93388df67d9f.png)

**Comment by nicolas-grekas** [comment]
Duplicate of#32395

**Comment by lyrixx** [comment]
Thanks @nicolas-grekas and @xabbuh
