### ISSUE TITLE
Web Server, config default port

### ISSUE THREAD

**Issue by tebaly** [symfony/symfony#32524]
**Description**  
I have a lot of microservices, for development I need to run them and each time specify the port for each in the command `bin/console server start *: 8005` for example. This is for everyone. Why it is impossible to save these values in a configuration?

**Example**  
```
web-server:
    port: 8005
```

Or a separate file in the root _.web-server_

**Comment by Arman-Hosseini** [comment]
Starting a server through the console for the developer environment, and each time you need to run the command on the console. For real use, you must run your project on a server with port 80 or 443.

**Comment by tebaly** [comment]
Of course. But it seems there is nothing difficult in being able to configure webServerBundle like other Bundles in Symfony

**Comment by xuanquynh** [comment]
We shouldn't write hard-code in configuration files. Using environment variables is more suitable and they still depends on each computer system. For example, 8005 is available on your computer but it has been already used in my one. We always have to specify our local ports.

**Comment by javiereguiluz** [comment]
You can pass the IP and port to the web server:

```
$ php bin/console server:start 127.0.0.1:8005
```

I know this is boring to type all the time ... so you can create a makefile or a quick script (e.g. `start.php`) and run instead `php start.php` to start the server in the `8005` port and run all the other tasks you need to run.

By the way, the WebServerBundle is deprecated and it will be removed in Symfony 5.0. The replacement, called [Symfony local web server](https://symfony.com/doc/current/setup/symfony_server.html), it's better at everything ... and it has an option to set the port:

```
$ symfony server:start --port=8005
```

So, given the available options, I'm closing this as "fixed". Thanks.
