### ISSUE TITLE
[Messenger] pass the transport name to the factory

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#32526]
**Description**  
We have a lot of exchanges/queues and need to create a custom transport for each one using the `Symfony\Component\Messenger\Transport\TransportFactoryInterface`. It would be very useful to receive the configured transport name as a parameter to `\Symfony\Component\Messenger\Transport\TransportFactoryInterface::createTransport(string $dsn, array $options, SerializerInterface $serializer)`. We could just forward the transport name as an option which does not require a signature change.
The current solution is to manually add the transport name to the options for each transport which is prone to copy-paste errors.

**Comment by Koc** [comment]
Can you provide config examples how you can define multiple transports now and how it would be after proposed improvement?

**Comment by Tobion** [comment]
It allows to use the transport name as a lookup value in the factory to make decisions. For example chose a certain serializer based on the transport. It would make #31230 easier for example. Otherwise I have to add an option for this manually to each transport config. See PR #32567
