### ISSUE TITLE
[Routing] Condition boolean lost performance

### ISSUE THREAD

**Issue by bambucha4** [symfony/symfony#32545]
**Symfony version(s) affected**: 4.3.2

**Description**  
Hey. I wanted to test the new functionality of transferring the bool parameter to the condition in Route Annotation implemented in 4.3 release. 

Unfortunately, I noticed that it does not work too fast ... I looked at Profiler and it turned out that RouterListener definitely has a problem.

There is not problem in prod envinroment, but the problem occurs in the dev environment.

**If at least ONE route has a condition parameter the project is slowing down.**

**How to reproduce**  
Before:

```
    /**
     * @Route("/test", name="test", methods={"GET"})
     *
     * @return Response
     */
    final public function test(): Response
    {
        return $this->response('TestowyKontroler.');
    }
```
![Without](https://user-images.githubusercontent.com/16488888/61202274-5bd73f00-a6e7-11e9-81fb-325e6461e829.PNG)

After:
```
    /**
     * @Route("/test", name="test", methods={"GET"}, condition="%kernel.debug%")
     *
     * @return Response
     */
    final public function test(): Response
    {
        return $this->response('TestowyKontroler.');
    }
```
![With](https://user-images.githubusercontent.com/16488888/61202282-609bf300-a6e7-11e9-84d1-b2014269521f.PNG)

**Possible Solution**  
Remove a condition with bool parameter solve this 'performance' problem.

**Additional context**  
In addition, my project is huge, has a lot of controllers and Route annotations.

```
        var_dump($this->get('router')->getRouteCollection()->count());
        exit;
```
I get:
`E:\PROJEKTY\intranet\src\Controller\Test\TestController.php:40:int 1081`

in ~270 controllers.

**Comment by er1z** [comment]
Does the same situation occurs on Linux platform?

**Comment by bambucha4** [comment]
Yes. I tested on dockerized project (which is slowly with volume with Windows directory), but same situation exists on Linux like in a Windows platform.

Without parameter:
![without](https://user-images.githubusercontent.com/16488888/61617380-ddd8e200-ac6a-11e9-9295-91332153745e.PNG)

With parameter:
![with](https://user-images.githubusercontent.com/16488888/61617394-e29d9600-ac6a-11e9-90bf-0454a49b9829.PNG)

**Comment by stof** [comment]
`$router->getRouteCollection()` is bad for performance, as it triggers the loading of routing files. `match` and `generate` are running based on compiled code kept in the cache. So make sure to not have such call in your code when you look at performance.

**Comment by nicolas-grekas** [comment]
Could you share a blackfire comparison with/without this condition parameter?
But what @stof said: getRouteCollection is not for runtime, because it compiles things and thus isn't expected to be fast.

**Comment by fabpot** [comment]
see #32915 for a PR adding a warning to make people aware of the slowness of `RouterInterface::getRouteCollection()`
