### ISSUE TITLE
Services ids from the ContainerBuilder can be integers

### ISSUE THREAD

**Issue by mathroc** [symfony/symfony#32549]
`ContainerBuilder::getServiceIds()` can return integers. It tries to cast all ids to string on input but because they're used as array keys, they are converted to integer if they are numeric

related issue : https://github.com/sonata-project/SonataAdminBundle/pull/5638

It was easier to to a PR against sonata-admin-bundle but I think it should be fixed in Symfony too

**Comment by ro0NL** [comment]
at least we have a potential type violation here: https://github.com/symfony/symfony/blob/2c9a1960a164a857cd551881b580266bc77bdafa/src/Symfony/Component/DependencyInjection/Dumper/GraphvizDumper.php#L173-L178

Casting to string on-call sounds reasonable.

**Comment by stof** [comment]
@ro0NL there is no type violation here, as GraphizDumper doesn't run in strict mode.

**Comment by ro0NL** [comment]
@stof , fair .. i meant a conceptual violation.

**Comment by stof** [comment]
Well, the violation is more in the implementation of `getServiceIds` IMO. As we expect service ids to be strings, we should return an array of strings there to avoid issues.
