### ISSUE TITLE
AuthenticationServiceException thrown instead of PDOException

### ISSUE THREAD

**Issue by LucileDT** [symfony/symfony#32547]
**Symfony version(s) affected**: 3.4.29

**Description**  
Using a custom LoginController (not the FOSUserBundle one), in loginAction, when there is a problem with PDO, the `$authenticationUtils->getLastAuthenticationError();` returns a `AuthenticationServiceException` instead of a `PDOException`.

See what kind of exception is returned here:

![image](https://user-images.githubusercontent.com/23707217/61205466-69dd8d80-a6f0-11e9-8c58-6d8a25b8ce90.png)

**How to reproduce** 
- create a symfony 3.4 project with a connection to a MySQL database
- create a login form
- create a LoginController:
```php
<?php
namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;

/**
 * Login controller
 */
class LoginController extends Controller
{

    /**
     * @Route("/login", name="login")
     * @param Request $request The request.
     * @param AuthenticationUtils $authenticationUtils Error.
     * @param UserInterface $user The user.
     * @return views
     */
    public function loginAction(Request $request, AuthenticationUtils $authenticationUtils, UserInterface $user = null)
    {
        $lastError = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();
        if (is_null($user))
        {
            if (!is_null($lastError))
            {
                if (is_a($lastError, 'Symfony\Component\Security\Core\Exception\BadCredentialsException'))
                {
                    $this->addFlash(
                            'danger', 'Nom d\'utilisateur ou mot de passe invalide.'
                    );
                }
                else
                {
                    $this->addFlash(
                            'danger', $lastError->getMessage()
                    );
                }
            }

            $response = $this->render('@App/Login/login.html.twig', []);
        }
        else
        {
            $response = $this->redirectToRoute('home');
        }

        return $response;
    }

    /**
     * @Route("/logout", name="logout")
     */
    public function logoutAction($param)
    {
        throw new \RuntimeException('This should never be called directly.');
    }

}
```
- stop the MySQL service
- try to submit the login form

*(sorry I'm in a hurry, if needed I will create a bug reproducer)*

**Comment by xabbuh** [comment]
I am afraid I do not understand the issue here. `AuthenticationUtils::getLastAuthenticationError()` is expected to return an `AuthenticationException` which `AuthenticationServiceException` is, but not any arbitrary exception as you do not want to present them to your users. Can you explain why you expected the `PDOException` here?

**Comment by linaori** [comment]
The code that sets the exception, can only set an `AuthenticationException`, because that's the type that comes in, this is working as intended.

Also please don't *ever* use `$exception->getMessage()` as output for the user. Showing the exception message to the end-user is considered a security risk.

**Comment by LucileDT** [comment]
@xabbuh I expect a PDOException because in this case, that's a PDOException that is thrown, which the Authentication service is catching then rethrowing user a new type.

@linaori I'm fully ok with your statement. **But** `$authenticationUtils->getLastAuthenticationError()` does not use a name explaining that it's an exception that is returned (`$authenticationUtils->getLastAuthenticationException()` would do, for example). Also my code is not ready for production environment and we use it only on dev env and check all errors we can currently encounter. Thanks anyway.

So, how can I do if I want to test what kind of exception is thrown to create a custom message? Do I need to do something like that: 
```php
if ($authenticationUtils->getLastAuthenticationError()->getMessage() === 'An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused')
{
    $this->addFlash(
        'danger', 'A problem have been encountered, please contact your administrator (error code: 487 125).'
    );
}
```

**Comment by linaori** [comment]
> So, how can I do if I want to test what kind of exception is thrown to create a custom message? Do I need to do something like that

You can probably throw a `CustomUserMessageAuthenticationException` at some point, but that means you have to try/catch/throw the exception manually. `AuthenticationException` has a `getMessageKey` created for this purpose, referencing to the translation key, or the sentence if you don't want to translate.

> But `$authenticationUtils->getLastAuthenticationError()` does not use a name explaining that it's an exception that is returned 

It's an authentication error and the return type specifies what you can do with it, I think this is fine as it is.

If you want to find out what the actual error is, you will probably be able to find it in your logs.

**Comment by xabbuh** [comment]
I am closing here as the current behaviour is expected this way as explained.
