### ISSUE TITLE
[Messenger] Message id must be passed when in non-interactive mode 

### ISSUE THREAD

**Issue by TheRatG** [symfony/symfony#32559]
**Symfony version(s) affected**: 4.3

**Description**  
I run command ```messenger:failed:retry --force -q``` in my crontab, but have a fatal  **Message id must be passed when in non-interactive mode.**

**How to reproduce**  
```messenger:failed:retry --force -q``` 

**Possible Solution**  

Do not throw exception because  **--force** flag provided. Or create another flag, which move all failed messages without confirmation. Otherwise, if ```-q``` is dropped crontab system send error email because there is an output from command.

**Additional context**  
```
bin/console messenger:failed:retry  --force
 // Quit this command with CONTROL-C.                                                               
 // Re-run the command with a -vv option to see logs about consumed messages.                       
There are 0 messages pending in the failure transport.
To retry all the messages, run messenger:consume failed
```

**Comment by Tobion** [comment]
What are you trying to achieve? The `messenger:failed:retry` is for manual retry of failed messages. I don't see why you'd run that in a cron tab. If you want to retry automatically just use the normal retry functionality or as the message says `messenger:consume failed`

**Comment by TheRatG** [comment]
```messenger:failed:retry``` move message to other queue, if run ```messenger:consume failed``` after unsuccessful retry message will be destroy automatically. We have monitoring of failed messages and remove them manually.

**Comment by TheRatG** [comment]
> What are you trying to achieve? The `messenger:failed:retry` is for manual retry of failed messages. I don't see why you'd run that in a cron tab. If you want to retry automatically just use the normal retry functionality or as the message says `messenger:consume failed`

messenger:failed:retry move message to other queue, if run messenger:consume failed after unsuccessful retries the message will be destroy automatically. We have monitoring of failed messages and remove them manually.

**Comment by Tobion** [comment]
> if run messenger:consume failed after unsuccessful retries the message will be destroy automatically

The message is also dropped when you use `messenger:failed:retry`. There is no difference. So that can't be the argument.

**Comment by TheRatG** [comment]
> > if run messenger:consume failed after unsuccessful retries the message will be destroy automatically
> 
> The message is also dropped when you use `messenger:failed:retry`. There is no difference. So that can't be the argument.

One more example:

1. normal_queue -> failed (```messenger:failed:retry  --force```)-> normal_queue -> failed -> ... crontab loop ... -> normal_queue -> failed ....
2. normal_queue -> failed (```messenger:consume failed```). As I understand that's the end or ```messenger:consume failed``` after retries move message to failed queue again?

**Comment by Tobion** [comment]
As I said, after `messenger:failed:retry --force` messages do not get back into the failed transport. Your assumptions seems to be wrong here.

**Comment by Tobion** [comment]
Ok I was wrong as explained in https://github.com/symfony/symfony/pull/32341#issuecomment-515525301

Failed messages in messenger:failed:retry go back into the failed transport due to the normal retry mechanism which is enabled by default. But after the retry count is reached, they will also be discarded. This is the same as with `messsenger:consume failed`. I would not recommend to create a cron with the failed transport because they already got retried. What's the point of creating a cron for that? That's exactly what the automatic retry should achieve. The failed messages is just a collection of messages that cannot be processed for inspection. If you want to do that in a cron, use messenger:consume. So I'm closing this issue.
