### ISSUE TITLE
[Messenger] Custom method argument $onHandledCallback for worker with command messenger:consume

### ISSUE THREAD

**Issue by B-Galati** [symfony/symfony#32560]
**Description**  
At the moment it does not look possible to have a custom `$onHandledCallback` on the `Worker` used by `messenger:consume` command.

See -> https://github.com/symfony/symfony/blob/52e9fb91ff7664e9eecf924df255e8ec323748ca/src/Symfony/Component/Messenger/Worker.php#L93

My use case is that I would like to `reset` monolog buffered handler at this very moment to send my error logs in batch to Sentry.

I thought about using `WorkerMessageFailedEvent` but then I would miss important logging messages such as :
- https://github.com/symfony/symfony/blob/52e9fb91ff7664e9eecf924df255e8ec323748ca/src/Symfony/Component/Messenger/Worker.php#L145
- https://github.com/symfony/symfony/blob/52e9fb91ff7664e9eecf924df255e8ec323748ca/src/Symfony/Component/Messenger/Worker.php#L159

**Possible solution**  
Perhaps by replacing the callable with an interface that could be autowired in the command, not sure.

**Comment by lyrixx** [comment]
IMHO, the Symfony should be reset after each message. I do that in my custom worker and I Opened an [issue in swarrot](https://github.com/swarrot/swarrot/issues/193) to do the same.

The status of the message should not be taken in consideration.

**Comment by B-Galati** [comment]
@weaverryan one idea would be to dispatch an event to replace the callback, WDYT?

**Comment by Tobion** [comment]
> I thought about using WorkerMessageFailedEvent but then I would miss important logging messages

Why would you miss them? They would get sent with the next batch of messages, wouldn't they?

**Comment by B-Galati** [comment]
@Tobion You're right, but they would be sent with unrelated logs records like:

```
---- Nothing before because it's been flushed ----
ERROR related to my message
Handling a new message unrelated to my error
```

**Comment by B-Galati** [comment]
trying to address that issue #32614

**Comment by Tobion** [comment]
> they would be sent with unrelated logs records

If you sent messages in batches there are always messages in one batch that might not belong together. But what is the problem you have? Logs are time based not group based.

**Comment by B-Galati** [comment]
> > they would be sent with unrelated logs records
> 
> If you sent messages in batches there are always messages in one batch that might not belong together. But what is the problem you have? Logs are time based not group based.

I would like to send all logs that are related to the same HTTP request or handled message in one batch. For instance I am using this monolog config. The problem I have is that I cannot achieve this behavior right now with messenger worker while it's perfectly fine with HTTP request. 

Another solution that works would be to reset the kernel after each message the worker handled.

```yaml
monolog:
  handlers:
    sentry_buffer:
      type: fingers_crossed
      action_level: warning
      handler: buffer
      channels: ["!event", "!security"]
    buffer:
      type: buffer
      handler: sentry
    sentry:
      type: service
      id: 'sentry_handler'
```
