### ISSUE TITLE
[Cache] PDO Adapter table auto creation issues

### ISSUE THREAD

**Issue by ChristianRiesen** [symfony/symfony#32569]
**Description**  
Currently the autocreation only happens on save(). There is the createTable() method, which is internally called by save if the table doesn't exist, but this seems backwards. Most caches I've ever used or implemented do `lookup -> hit -> return` and `lookup -> miss -> generate data -> save -> return`. The PDO adapter already fails horribly at lookups so in a general logic, the save never get's called as it always fails on the lookup.

To make matters slightly worse, the createTable() function creats the table blindly and if it already exists is bound to faceplant as well, so it can't even be used properly for that.

Another hurdle is that the actual adapter is wrapped in `Symfony\Component\Cache\Adapter\TraceableAdapter` which doesn't forward the createTable function, not allow access to the injected pool, so getting to it has so far eluded me.

I thought of just having a cache warmer create the table, but not being able to access the createTable function and it making a mess if the table already exists sort of stiffles that.

**Example**  
My only work around I found so far is to blindly save one item in a cache warmer:
```
        $item = $this->cache->getItem('1');
        $item->set(true);
        $this->cache->save($item);
```
with `$this->cache` being injected as a configured cache instance using the pdo adapter from the framework config, typed as `Psr\Cache\CacheItemPoolInterface`.

I would expect it to generate the table if needed, also on lookups, or allow for generation in a warmer without a fake entry being needed.

The documentation also could use an example on how to actively access the option visible in Symfony\Component\Cache\Traits\PdoTrait so one could change the table name, which I think would be a very common case for many.

**Comment by ChristianRiesen** [comment]
As a small addition: I mean the docs mainly in the framework config area. The adapter itself has mentions, but the config docs is not obvious to me how to accomplish changing the table.

**Comment by nicolas-grekas** [comment]
A tentative solution is being discussed in #33166, I invite you to join it.
Thanks for the report.

**Comment by lazka** [comment]
Still seeing this today with 5.4, endless logs like this, until the first cache is saved:

> cache.WARNING: Failed to fetch key "workers.restart_requested_timestamp": An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: cache_items {"key":"workers.restart_requested_timestamp","exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: cache_items at /application/vendor/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:55)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1): SQLSTATE[HY000]: General error: 1 no such table: cache_items at /application/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: cache_items at /application/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:60)","cache-adapter":"Symfony\\Component\\Cache\\Adapter\\DoctrineDbalAdapter"} []
