### ISSUE TITLE
[FrameworkBundle] Rename internal WebTestCase to avoid confusion

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#32577]
**Description**  
FrameworkBundle has two classes called `WebTestCase`:

* https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php
* https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Tests/Functional/WebTestCase.php

The second is only meant for our internal tests. But because it has the same-name, it's easy for a user to extend the wrong one from their own tests. There is also another internal `WebTestCase` inside SecurityBundle.

Has this been discussed before? It seems like an easy win to rename this internal testing class to something else.

**Comment by fabpot** [comment]
As this is an internal class, renaming is not a BC-break. We should find a new name though. What about `FunctionalWebTestCase`?

**Comment by ro0NL** [comment]
isnt any "web test case" is a functional concern already :thinking: 

https://github.com/symfony/symfony/blob/25f180416eb58dbd2a0d72016c660a1aee9d0a66/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L18

for the `Functional` namespace it could be a `AbstractTestCase`

**Comment by fabpot** [comment]
`AbstractWebTestCase` works for me.

**Comment by janvt** [comment]
The same is the case in the `SecurityBundle` - `\Symfony\Bundle\SecurityBundle\Tests\Functional\WebTestCase`. Currently working on a PR, should I rename this as well? Seems to be internal, same as the `FrameworkBundle` class.

**Comment by xabbuh** [comment]
Sounds reasonable to me.

**Comment by Tobion** [comment]
Can we reconsider #20057 please? `WebTestCase` is just one of the problems. There are alot of fixtures in tests that can easily be picked up by accident. And even the test files itself can cause confusion. If you look for WebTestCase you will also get suggested `WebTestCaseTest`. It's the test testing WebTestCase. Definitely not what you were looking for.
