### ISSUE TITLE
Two submits and dynamically building form

### ISSUE THREAD

**Issue by Skyoddler** [symfony/symfony#32574]
Hello. 
I have a question: I'm building my form dynamically using Form Events. 
I need to achieve next: after hitting submit button for the first time my form is rebuilding accordingly to data(adding some fields e.t.c from $event->getData()). 
And on the second submit(same button) I need to, actually validate/persist/flush my changes.
How can I achieve that? With two submit buttons replacing each other or filter submits somehow?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
