### ISSUE TITLE
Misleading Access Check from SecurityChecker::isGranted with unanimous Access Decision Strategy

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#32594]
**Symfony version(s) affected**: 4.3, probably older versions are affected as well

**Description**  
It is not uncommon to check the access rights via is_granted in twig templates. Internally, `SecurityChecker->isGranted($role, $object)` is called for this. The [documentation states](https://symfony.com/doc/current/reference/twig_reference.html#is-granted) that
> If several roles are passed in an array, true is returned if the user **has at least one of them**.

However, this is not correct in all cases. Either there is an inaccuracy in the documentation, or the behavior of `SecurityChecker->isGranted($role, $object)` is unintentionally dependent on [the Access Decision Strategy](https://symfony.com/doc/current/security/voters.html#changing-the-access-decision-strategy). If the access decision strategy is set to `unanimous` , then `is_granted` will only return `true` if **ALL** of the given roles are assigned to the user.

**How to reproduce**  
For example, use this security configuration
```
[...]
access_decision_manager:
    strategy:             unanimous
    allow_if_all_abstain: false
```

If a user as the role "ROLE_A" (without ROLE_B)

```twig
{% if is_granted(['ROLE_A', 'ROLE_B']) %}
    <p>Current user has ROLE_A or ROLE_B</p>
{% endif %}
```
then the paragraph is not shown.

**Possible Solution**  
The simplest solution is to point out in the documentation that in a given configuration setting, multiple roles in is_granted are checked with AND (instead of OR).

Nevertheless, it would make sense to also perform an OR query on the unanimous strategy (to check whether the user has one of these roles)

**Comment by stof** [comment]
This is a documentation mistake. It should indeed not assume the default config for the strategy.

**Comment by javiereguiluz** [comment]
Yes ... the documentation explains it right in this page: https://symfony.com/doc/current/security/access_control.html#access-enforcement but not in the one you linked. So, we're going to fix this in the symfony-docs repository. Thanks.

**Comment by javiereguiluz** [comment]
This is being fixed in https://github.com/symfony/symfony-docs/pull/11988

**Comment by xabbuh** [comment]
@stof I fail to see why this is an issue of the configured access decision strategy. The strategy is important when there are several voters involved, but in this particular case, all roles to be checked are passed to the `RoleVoter` and the result is not depending on the access decision strategy.

**Comment by dsentker** [comment]
Sorry for the question, but why was the documentation clarification reverted? The original issue (and my problem) was that `isGranted()` with array argument only returns `true` if **all** roles match (with unanimous strategy). This is not mentioned in the docs and is confusing.
