### ISSUE TITLE
Values of variables that depend on APP_ENV change according to its position

### ISSUE THREAD

**Issue by MGatou** [symfony/symfony#32595]
**Description**
In my `.env` file, I have a variable `TEST` that depends on the `APP_ENV` variable like this:

```
# .env file

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=2eb810c79fba0dd5c029a2fa53bfdb51
###< symfony/framework-bundle ###

TEST=foo_${APP_ENV}
```
I run `composer dump-env dev` command to generate my `.env.locale.php`, everything works fine, the value of my variable `TEST` is correct.

```php
// .env.locale.php

return array (
  'APP_ENV' => 'dev',
  'TEST' => 'foo_dev',
  'APP_SECRET' => '2eb810c79fba0dd5c029a2fa53bfdb51',
);
```
Then I run the same command with prod environment (`composer dump-env prod`), the value of `TEST` is wrong (it is same as for `dev`)

```php
// .env.locale.php

return array (
  'APP_ENV' => 'prod',
  'TEST' => 'foo_dev',
  'APP_SECRET' => '2eb810c79fba0dd5c029a2fa53bfdb51',
);
```
But when I put my variable `TEST` before the `APP_ENV` like this:

```
# .env file

TEST=foo_${APP_ENV}

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=2eb810c79fba0dd5c029a2fa53bfdb51
###< symfony/framework-bundle ###
```
And I run `composer dump-env prod` again, the value of `TEST` is correct

```php
// .env.locale.php

return array (
  'APP_ENV' => 'prod',
  'TEST' => 'foo_prod',
  'APP_SECRET' => '2eb810c79fba0dd5c029a2fa53bfdb51',
);
```

How can we explain that ?

**How to reproduce**
- Create a new Symfony project `composer create-project symfony/skeleton bug_app`
- Add new variable `TEST` in your `.env`
- Run `composer dump-env prod`
- Take a look at `.env.locale.php`
- In your `.env` file, put your `TEST` variable before the `APP_ENV`
- Then run `composer dump-env prod` again
- Take a look at `.env.locale.php` again

**Comment by nicolas-grekas** [comment]
The issue lies in the Dotenv component: we have two separate loading step: 1. parse() 2. populate().
Parse() doesn't account for existing env vars when calling resolveVariables or resolveCommands.
The solution would be to load files line by line and populate while parsing.
That's a pretty significant change, but it would make sense to me.

**Comment by soufianZantar** [comment]
I have try to fix the issue.
i think we must just searching the value of variables (in parse method)  first in $_ENV to get the value from the command `composer dump-env prod` then search in .env.

Now we searching in .env file first for that we get the value from .env not updated.
