### ISSUE TITLE
What about the server:log command ?

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#32602]
#31217 deprecated the server bundle.
But it also deprecated the `server:log` command. The `symfony server:log` is really less powerful. So we are removing some feature from symfony :/ 

How could we move the feature that will be removed to the symfony CLI ?

In symfony 5.* some commands will still exists in the `server:` namespace. Like the [`server:dump`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/VarDumper/Command/ServerDumpCommand.php) command. So having some commands in this NS seems fine.

Another solution could be to move this command to the MonologBridge. WDYT ?

**Comment by Simperfit** [comment]
I think we can move it like you suggested in #31217 and be able to parse the logs anyway! :).

**Comment by nicolas-grekas** [comment]
We're working on improving the command for the Symfony binary.

**Comment by lyrixx** [comment]
Nice to hear that. Can wait to see it released ;)
