### ISSUE TITLE
Cannot read property "name" from an array. Maybe you intended to write the property path as "[name]" instead.

### ISSUE THREAD

**Issue by salimmejdoub** [symfony/symfony#32628]
Hello,
i'm working in a symf 3.4 project and i'm having this error in my server php 5.6.38 mode Cannot read property "name" from an array. Maybe you intended to write the property path as "[name]" instead.

but in the server of client the error don't appear

thanks for the help

**Comment by xabbuh** [comment]
The error message seems quite clear to me. If you think that shouldn't happen given the data that you use, we would need a scenario that allows us to reproduce it.

**Comment by javiereguiluz** [comment]
See https://symfony.com/doc/current/components/property_access.html#reading-from-arrays  You need to add the `[ ... ]` to read a property from an array.

**Comment by salimmejdoub** [comment]
Hello, thanks for the reply
my the error come from  'form' => $form->createView(),

i will post my two files controller/form

`<?php

namespace AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use AdminBundle\Form\MediaType;
use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProductType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('translations',TranslationsType::class,[
                        'label'=>'Choix de langue',
                        'fields' => [  
                            'name' => [     
                                'label' => 'Titre *', 
                                'attr'=>[
                                    'class'=>'form-control theSlugInutWilTakeThisInputValue',
                                   
                                ]                    
                            ],
                            'slug' => [     
                                'label' => 'Slug *', 
                                'attr'=>[
                                    'class'=>'form-control slugInputFromOriginalTextInput',
                                    
                                ]                    
                            ],  

                            'textGauche' => [     
                            'field_type' => TextareaType::class,  
                            
                            'label' => 'Légende pour premier texte', 
                            'attr' => array(
                                        'class' => 'tinymce',
                                        'data-theme' => 'simple' // Skip it if you want to use default theme
                         ),
                         'required'=>false,                
                        ],  
                        'image' => [     
                            'field_type' => FileType::class,  
                            'data_class' => null,
                            'required'=>false,
                            'label' => 'Choisissez un picto', 
                            'attr'=>[
                                'class'=>'form-control inputTestIfEmpty'
                            ]                   
                        ], 
                       
                        ]
                    ])
                 
                ->add('categories',null,array(
                                    'label'=>'Catégorie',
                                    'required'=>true,
                                    'attr'=>array('class' => 'form-control' )
                               ))
               ->add('published', CheckboxType::class, array(
                                'label'    => 'On / offline?',
                                'required' => false,
                ))
                   ->add('imageProduct',  FileType::class, array(
                                'label'    => 'Choisissez une image - 251 x 251 px',
                                'data_class' => null,
                                'required'=>false,
                                'attr'=>array('class' => 'form-control' )
                               
                ))
           
              
                ->add('seo', SeoType::class,array(
                            'label'=>' '))
             
                ->add('bloctitre', CollectionType::class, array(
                    'entry_type' => BlocTitreType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'titres-box')
                    ),
                ))
                ->add('blocsoustitre', CollectionType::class, array(
                    'entry_type' => BlocSousTitreType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'soustitres-box')
                    ),
                ))
                
                ->add('bloctext', CollectionType::class, array(
                    'entry_type' => BlocTextType::class,
                   
                    'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'textes-box')
                    ),
                ))
                ->add('blocquote',CollectionType::class, array(
                    'entry_type'   => BlocQuoteType::class,
                  'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'quotes-box')
                    ),
                ))
                ->add('blocsupport',CollectionType::class, array(
                    'entry_type'   => BlocSupportType::class,
                  'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'support-box')
                    ),
                ))
                ->add('blocimage',CollectionType::class, array(
                    'entry_type'   => BlocImageType::class,
                  'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'blocimage-box')
                    ),
                ))

        
               ->add('blocvideo',CollectionType::class, array(
                    'entry_type'   => BlocVideoType::class,
                  'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty'=>true,
                    'by_reference' => false,
                    'prototype' => true,
                    'entry_options'  => array(
                        'attr'      => array('class' => 'videos-box')
                    ),
                ))
            
                ;

    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AdminBundle\Entity\Product'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'adminbundle_product';
    }


}
`


`<?php

namespace AdminBundle\Controller;

use AdminBundle\Entity\Seo;
use AdminBundle\Entity\Product;
use AdminBundle\Entity\Image;
use AdminBundle\Entity\Media;
use AdminBundle\Entity\JoinTable;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use AdminBundle\Entity\JoinTableSupport;

/**
 * Product controller.
 *
 * @Route("product")
 */
class ProductController extends Controller
{



/**
     * Deletes all product checked.
     *
     * @Route("/product-delete-all", name="product_delete_all")
     * @Method("POST")
     */
    public function deleteAllAction(Request $request) {     
        if($request->isXmlHttpRequest()){
            $Ids= $request->request->get('id');
            $productIds=  json_decode($Ids);
          
            $em=$this->getDoctrine()->getManager();
            foreach($productIds as $id){
                $product = $em->getRepository('AdminBundle:Product')->find($id);
                if($product){
                    $em->remove($product);
                    $em->flush();
                }
                else{
                    'aucune produit sélectionnée';
                }
            }
        return new JsonResponse( array( 'data'=>$request->request->get('id') ) );
        }
    }

    private function tesType($allData,$id,$type){
        
        $result = 0;
        foreach ($allData as $data => $value) {
          $pieces = explode("-", $value);
         
          if ( $pieces[0] == $type && $pieces[1] == $id){
          //  dump($data);
             $result  = $data;
          }
         

        }
        return $result;
    }

    /**
     * Lists all product entities.
     *
     * @Route("/", name="admin_product_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $products = $em->getRepository('AdminBundle:Product')->findAll();

        return $this->render('AdminBundle:product:index.html.twig', array(
            'products' => $products,
        ));
    }

    /**
     * Creates a new product entity.
     *
     * @Route("/new", name="admin_product_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    { $product = new Product();
      $em = $this->getDoctrine()->getManager();
        $form = $this->createForm('AdminBundle\Form\ProductType', $product);
        $form->handleRequest($request);
     
    
        if ($form->isSubmitted() && $form->isValid()) {

            $product->setCreatedAt(new \DateTime('now'));
            
            $em->persist($product);
            foreach ($product->getCategories() as $category) {
                $newJoin = new JoinTable();
                $product->addProductJoin($newJoin);
                $category->addCategoryJoin($newJoin);
                $em->persist($newJoin);
                $em->flush();
            }  
            if($product->getBlocsupport()!=null){
    
            foreach ($product->getBlocsupport() as $blocSupport) {

              foreach ($blocSupport->getSupportProduct() as $produit) {
                $newJoin = new JoinTableSupport();
                $newJoin->setProduct($produit);
                //dump($produit->getId());
                $newJoin->setBlocsupport($blocSupport);
                $newJoin
                ->setPosition(
                  $this->tesType(
                    $request->request->get('ordered_support_with_positin'),$produit->getId(),'product'
                  )
                );
             
               
                $em->persist($newJoin);
                $em->flush();
              }
 

           
              foreach ($blocSupport->getSupportCategory() as $categorie) {
                $newJoin = new JoinTableSupport();
                $newJoin->setCategoryoffer($categorie);
                $newJoin->setBlocsupport($blocSupport);
                $newJoin
                ->setPosition(
                  $this->tesType(
                    $request->request->get('ordered_support_with_positin'),$categorie->getId(),'category'
                  )
                );  
                $em->persist($newJoin);
               // dump($newJoin);
              $em->flush();
              }
            
        }

       
    }
     
    return $this->redirectToRoute('admin_product_index');
    }

      //$fileMedia = $em->getRepository('AdminBundle:FileMedia')->findAll();

           $qb = $em->createQueryBuilder();
        $fileMedia =$qb->select('f')
           ->from('AdminBundle:FileMedia', 'f')
            ->OrderBy('f.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

        return $this->render('AdminBundle:product:new.html.twig', array(
            'product' => $product,
            'form' => $form->createView(),
            'fileMedia'=>$fileMedia
        ));
    
}

    /**
     * Finds and displays a product entity.
     *
     * @Route("/{id}", name="admin_product_show")
     * @Method("GET")
     */
    public function showAction(Product $product)
    {
        $deleteForm = $this->createDeleteForm($product);

        return $this->render('AdminBundle:product:show.html.twig', array(
            'product' => $product,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing product entity.
     *
     * @Route("/{id}/edit", name="admin_product_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Product $product)
    {
        $deleteForm = $this->createDeleteForm($product);
        $editForm = $this->createForm('AdminBundle\Form\ProductType', $product);
        $editForm->handleRequest($request);
          $em=$this->getDoctrine()->getManager();
        $blocSupport=$em->getRepository('AdminBundle:BlocSupport')->findBy(array('product'=>$product));
        $fileMedia = $em->getRepository('AdminBundle:FileMedia')->findAll();

          if ($editForm->isSubmitted() && $editForm->isValid()) {
          /****/

          $em = $this->getDoctrine()->getManager();
        
          //die;
          /****/
          if($product->getBlocsupport()!=null){
              foreach ($product->getBlocsupport() as $blocSupport) {

               if($blocSupport->getSupportJoins() != null){
                foreach ($blocSupport->getSupportJoins() as $support) { 

                          $em->remove($support);
                    
                          $em->flush();
                  }
                }
               
                foreach ($blocSupport->getSupportProduct() as $produit) {
                  $newJoin = new JoinTableSupport();
                  $newJoin->setProduct($produit);
                  $newJoin->setBlocsupport($blocSupport);
                  $newJoin
                    ->setPosition(
                      $this->tesType(
                        $request->request->get('ordered_support_with_positin'),$produit->getId(),'product'
                      )
                  );               
                  $em->persist($newJoin);
                  $em->flush();
                }
                foreach ($blocSupport->getSupportCategory() as $categorie) {
                  $newJoinCat = new JoinTableSupport();
                  $newJoinCat->setCategoryoffer($categorie);
                  $newJoinCat->setBlocsupport($blocSupport);
                  $newJoinCat
                    ->setPosition(
                      $this->tesType(
                        $request->request->get('ordered_support_with_positin'),$categorie->getId(),'category'
                      )
                  );  
                  $em->persist($newJoinCat);
                  $em->flush();
                }
              }
            }

            $em->flush();
               if(null != $product->getId()) {
                  $request->getSession()
                  ->getFlashBag()
                  ->add('success', 'Modification effectuée avec succès');
                  }

            return $this->redirectToRoute('admin_product_edit', array('id' => $product->getId()));
        }    
  $fileMedia = $em->getRepository('AdminBundle:FileMedia')->findAll();

 $dataArray = array(
            'product' => $product,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );

        if( $blocSupport != null){
       $JoinTableSupport=$blocSupport=$em->getRepository('AdminBundle:JoinTableSupport')
       ->findBy(array('blocsupport'=>$blocSupport[0]),
        array('position'=>'ASC'));
        $dataArray['JoinTableSupport']=$JoinTableSupport;
      
    }
      
    
        if($product->getBlocquote() == true){
            foreach ($product->getBlocquote() as $quote) {
                $dataArray['contents'][] =  array(
                    'type' => 'quote', 
                    'entity' => $quote, 
                    'position' => $quote->getPosition() 
                );
            }
        }
        if($product->getBloctitre() == true){
            foreach ($product->getBloctitre() as $titre) {
                $dataArray['contents'][] =  array(
                    'type' => 'titre', 
                    'entity' => $titre, 
                    'position' => $titre->getPosition() 
                );
            }
        }
        if($product->getBlocsoustitre() == true){
            foreach ($product->getBlocsoustitre() as $soustitre) {
                $dataArray['contents'][] =  array(
                    'type' => 'soustitre', 
                    'entity' => $soustitre, 
                    'position' => $soustitre->getPosition() 
                );
            }
        }
        if($product->getBlocsupport() == true){
            foreach ($product->getBlocsupport() as $blocsupport) {
                $dataArray['contents'][] =  array(
                    'type' => 'blocsupport', 
                    'entity' => $blocsupport, 
                    'position' => $blocsupport->getPosition() 
                );
            }
        }
        if($product->getBloctext() == true){
            foreach ($product->getBloctext() as $bloctext) {
                $dataArray['contents'][] =  array(
                    'type' => 'bloctext', 
                    'entity' => $bloctext, 
                    'position' => $bloctext->getPosition() 
                );
            }
        }
        if($product->getBlocvideo() == true){
            foreach ($product->getBlocvideo() as $blocvideo) {
                $dataArray['contents'][] =  array(
                    'type' => 'blocvideo', 
                    'entity' => $blocvideo, 
                    'position' => $blocvideo->getPosition() 
                );
            }
        }

           if($product->getBlocimage() == true){
            foreach ($product->getBlocimage() as $blocimage) {

          
                     $dataArray['contents'][] =  array(
                    'type' => 'blocimage', 
                    'entity' => $blocimage, 
                    'position' => $blocimage->getPosition() ,
                   
                    
                );
             
               
            }
           
        }
        
        $sortArray = array(); 
        if(isset($dataArray['contents'])  ){
            foreach($dataArray['contents'] as $person){ 
                foreach($person as $key=>$value){ 
                    if(!isset($sortArray[$key])){ 
                        $sortArray[$key] = array(); 
                    } 
                    $sortArray[$key][] = $value; 
                } 
            } 
            $orderby = "position";
            array_multisort($sortArray[$orderby],SORT_ASC,$dataArray['contents']); 
        }

        $dataArray['fileMedia']=$fileMedia;
        //dump($dataArray);die;
        return $this->render('AdminBundle:product:edit.html.twig',$dataArray);


/*
    

    return $this->render('AdminBundle:product:edit.html.twig', array(
            'product' => $product,
            //'media' => $media,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));*/
    }

    /**
     * Deletes a product entity.
     *
     * @Route("/{id}/delete", name="admin_product_delete")
     * @Method("GET")
     */
    public function deleteAction(Request $request, Product $product)
    {
        $form = $this->createDeleteForm($product);
        $form->handleRequest($request);

        //if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($product);
            $em->flush();
        //}

        return $this->redirectToRoute('admin_product_index', array('action' => 'suppression'));
    }

    /**
     * Creates a form to delete a product entity.
     *
     * @param Product $product The product entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Product $product)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_product_delete', array('id' => $product->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}
`

**Comment by salimmejdoub** [comment]
`Form->createView()
in src/AdminBundle/Controller/ProductController.php (line 168)
            ->getQuery()             ->getResult();         return $this->render('AdminBundle:product:new.html.twig', array(             'product' => $product,             'form' => $form->createView(),             'fileMedia'=>$fileMedia         ));      }
ProductController->newAction(object(Request))`

**Comment by xabbuh** [comment]
Please create an example application based on your code that we can check out. Otherwise we won't be able to reproduce.

**Comment by salimmejdoub** [comment]
> Please create an example application based on your code that we can check out. Otherwise we won't be able to reproduce.

this s the error only in this part

**Comment by xabbuh** [comment]
I am sorry but if you want us to look into the issue, you will need to help us a bit more which means that we need an application that we can just clone and execute. To be honest I don't have the time to guess the code that is around the classes that you showed without knowing if I would then be able to reproduce.

**Comment by salimmejdoub** [comment]
Thanks for your help , it was issue with php version
