### ISSUE TITLE
Built-in webserver, PHPSESSID, and security component

### ISSUE THREAD

**Issue by debach** [symfony/symfony#32621]
**Symfony version(s) affected**: 4.3.2

**Description** 
The problem occurs when running two different websites on the built-in server with `php bin/console server:run`. The root problem is that multiple instances of the server use the same PHPSESSID, even for different websites. I describe here one particular consequence of this phenomenon.

The first website, call it site “Auth”, uses the security component as described [in the docs](https://symfony.com/doc/current/security.html) in order to authenticate users of the website for the admin backend. For this, an entity `App\Entity\User` is used.

The second website, call it site “Anon”, does not use authentification explicitly (only default configuration). As it happens, it also has an entity `App\Entity\User`, but this entity models something completely unrelated to the users of the website.

If I run both websites with the built-in webserver on the same local machine – say Auth goes to localhost:8000 and Anon goes to localhost:8001 – then an exception is thrown for Anon:

    Catchable Fatal Error: Object of class App\Entity\User could not be converted to string

The top of the stack trace being

    in AbstractToken.php line 78
    at AbstractToken->getUsername()
    in SecurityDataCollector.php line 146
    at SecurityDataCollector->collect(object(Request), object(Response), object(ErrorException))
    in Profiler.php line 167
    at Profiler->collect(object(Request), object(Response), object(ErrorException))
    in ProfilerListener.php line 93
    at ProfilerListener->onKernelResponse(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
    in WrappedListener.php line 126

Note that none of the users entities has a function `__toString()`. The webservers do not have to be run at the same time. It suffices that Auth is run before Anon. The problem persists until the PHPSESSID cookie is deleted (the other solution would be to implement `App\Entity\User::__toString()` but let’s ignore this); only then Anon works again. Both websites use the same PHPSESSID.

Is there something we can do to prevent this unexpected behavior?

**How to reproduce**  

If need be, I can make this more explicit. For now let’s settle with: I created both sites with `composer create-project symfony/website-skeleton project-name` and then added an entity `App\Entity\User`, one following [https://symfony.com/doc/current/security.html](https://symfony.com/doc/current/security.html), the other a simple empty class.

**Additional context**  
Software used:

1. Ubuntu 16.04.6 LTS (Xenial Xerus) 64bit 
2. official Chromium 74.0.3729.169
3. PHP 7.3.2 (cli) (built: Feb 12 2019 10:11:43) ( NTS )

**Comment by linaori** [comment]
I'm not entirely sure, but could it be that the session cookie is set for `localhost` and thus conflicts because only the port is different?

If this is the case, could a custom cookie name solve this conflict?

**Comment by stof** [comment]
The name of the session cookie is already configurable.

I see several solutions here:

- use the symfony local server rather than the WebServerBundle, which allows using different domains for  each project (and so separate cookies). WebServerBundle is deprecated in Symfony 4.4 anyway in favor of the local server
- configure an custom name for the session cookie instead of relying on the default `PHPSESSID` (and of course, use *different* custom names for each project)

**Comment by debach** [comment]
I see. I was unaware of the configuration `framework.session.name` (I googled for “symfony PHPSESSID” and didn’t find anything quickly). [From the docs:](https://symfony.com/doc/current/reference/configuration/framework.html#name)

> This specifies the name of the session cookie. By default, it will use the cookie name which is defined in the php.ini with the session.name directive.

Let me know if you want me to enhance the documentation — though I wouldn’t know where a good place would be to hint at potential problems of this kind.

**Comment by stof** [comment]
This kind of problem is not specific to Symfony. It is what happens when you run several project on the same host during development (your browser does not know that they are separate projects, and so does not isolate the cookies).

**Comment by debach** [comment]
You’re right. I was mislead by the fact that I was interacting only with the Symfony console.

**Comment by stof** [comment]
well, your issue also involved you interacting with the browser :smile:
