### ISSUE TITLE
Error with composer install Symphony

### ISSUE THREAD

**Issue by yaroslavsinchenko** [symfony/symfony#32630]
I've started to collaborate with one project and to setup it I need to run composer install but it shows me such error. What should I do?

Your requirements could not be resolved to an installable set of packages.

Problem 1 
- Installation request for symfony/symfony v3.4.25 -> satisfiable by symfony/symfony[v3.4.25].
- don't install symfony/var-dumper v4.2.6|don't install symfony/symfony v3.4.25 
- Installation request for symfony/var-dumper v4.2.6 -> satisfiable by symfony/var-dumper[v4.2.6].

**Comment by xabbuh** [comment]
The `symfony/symfony` package already provides the VarDumper component in the same version. Earlier versions of Composer errorneuosnly allowed to install to different versions of the same version of a component, but this bug has been fixed meanwhile. You either need to stick with VarDumper 3.4 or replace the `symfony/symfony` package with the individual components. I am closing here as there is nothing we need to fix. Thank you for understanding.
