### ISSUE TITLE
Matched route triggering "No route found" error

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#32635]
**Symfony version(s) affected**: 3.4.29

**Description**  

app_about:
&ensp;&ensp;path:         /about/{id}
&ensp;&ensp;controller:   FrameworkBundle:Template:template
&ensp;&ensp;defaults:
&ensp;&ensp;&ensp;&ensp;template: AppBundle:t1:about.html.twig
&ensp;&ensp;requirements:
&ensp;&ensp;&ensp;&ensp;id: '\d+'

It works when I open “http://localhost/about/1?query"

But matched route triggering "Not Found"
```
        try {
            $r = $this->get('router');
            $s = $r->match('/about/1?query');
            dump($s);
        } catch (ResourceNotFoundException $e) {
            dump('Not Found');   
        }
```

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by imsheng** [comment]
@xabbuh 
https://www.mmood.com/my_project.zip

**Comment by xabbuh** [comment]
Oh, I am sorry. I misread your initial description. In fact, this does not look like a bug to me, but a misunderstanding of how the request matcher is supposed to be used:

```php
    /**
     * Tries to match a URL path with a set of routes.
     *
     * If the matcher can not find information, it must throw one of the exceptions documented
     * below.
     *
     * @param string $pathinfo The path info to be parsed (raw format, i.e. not urldecoded)
     *
     * @return array An array of parameters
     *
     * @throws NoConfigurationException  If no routing configuration could be found
     * @throws ResourceNotFoundException If the resource could not be found
     * @throws MethodNotAllowedException If the resource was found but the request method is not allowed
     */
    public function match(string $pathinfo);
```

As you can see here the interface expects that you pass it the path info of the URL (which does not include the URL parameters).

Adapting your code like this should work as you expect it:

```php
try {
    $r = $this->get('router');
    $s = $r->match(parse_url('/about/1?query', PHP_URL_PATH));
    dump($s);
} catch (ResourceNotFoundException $e) {
    dump('Not Found');   
}
```

**Comment by imsheng** [comment]
@xabbuh 
I think the matching function is incomplete.
I want to match routing like a framework. how to match routing with a complete URL path, If routing is conditioned, it doesn't work.

`@Route("/about/{id}", name="about" , requirements={"id"="\d+"} , condition="request.query.has('query')"）`

**Comment by nicolas-grekas** [comment]
For this use case, you should use `RequestMatcherInterface` instead of `UrlMatcherInterface`
You could also use the `setContext` method of `UrlMatcher`.
I'm closing as there is no bug here.
