### ISSUE TITLE
[BUG] Cannot load service from bundle

### ISSUE THREAD

**Issue by RSalo** [symfony/symfony#32633]
**Symfony version(s) affected**: 4.3.2

**Description**  
Service doesn't load from bundle service

**How to reproduce**  
init bundle:
```
<?php
...

class InitBundle extends Bundle
{
}
```
DI:
```
<?php
...

class BundleExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/../config/'));
        $loader->load('services.yaml');
    }
}
```
services.yaml:
```
services:
  test_service:
    class: App\Bundles\MyBundle\Services\TestService
    public: true
```
Test Service:
```
class TestService
{
}
```
Add our bundle to the bundles:
```
<?php

return [
.....
    App\Bundles\MyBundle\InitBundle::class => ['all' => true]
];
```
And any action in a controller for call service:
```
class LolController extends AbstractController
{
    /**
     * @Route(...)
     */
    public function index(): Response
    {
        $anyVar = $this->container->get('test_service');

        return $this->render('index.html.twig');
    }
}
```

Throw exception:

> Service "test_service" not found: the container inside "App\Controller\AdminController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "templating" and "twig" services.

**Possible Solution**  
IDK

**Additional context**  
Related https://github.com/stwe/DatatablesBundle/issues/857

**Comment by xabbuh** [comment]
The `AbstractController` class doesn't give you access to the full service container, but only to a restricted one (see https://symfony.com/doc/current/controller.html#fetching-services). I am closing here as the observed behaviour is expected and there is nothing to fix. Thank you for understanding.

**Comment by debo** [comment]
@xabbuh nothing to fix in the framework maybe but surely the documentation does need a good rewrite. I already opened a issue with the docs team.
