### ISSUE TITLE
[Profiler] The routing panel is wrong on redirects

### ISSUE THREAD

**Issue by vicb** [symfony/symfony#3264]
As it go through the matching process where it should get the `_route` attribute only.

**Comment by javiereguiluz** [comment]
I think we can close this 4 years old issue. The solution is to set this config for the profiler:

```yaml
web_profiler:
    intercept_redirects: true
```

Then redirections are intercepted:

![intercept_redirect](https://cloud.githubusercontent.com/assets/73419/12444153/65f0f712-bf5d-11e5-8278-6175d9cf0b82.png)

And you can open the profile for the redirection:

![redirect_info](https://cloud.githubusercontent.com/assets/73419/12444160/6d778d98-bf5d-11e5-94f7-e324babb5be4.png)
