### ISSUE TITLE
Option to filter choices

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony#32657]
This is a global feature request replacing several more specific requests in the past. Basically the idea is to have a new `choice_filter` option that allows to filter the list of choices.

see #11847, #14072 for example

**Comment by ro0NL** [comment]
so we need a decision for #28624, which exactly implements this `choice_filter` :sweat_smile: 

i sense some skepticism to handle this in memory, compared to providing an optimized `choice_loader`. However for the "intl choice types" the choice_loader is predefined and hard to modify.

Also i'd argue one should ever pass a choice loader to the intl types, given those types should manage the data/choices for us. We only want want modify this list with filters and ordering.

**Comment by yceruto** [comment]
I think this `choice_filter` option makes sense only for intl types.

**Comment by fancyweb** [comment]
+1 to @yceruto. Having this filter option makes sense, but only on form types that forces the choices. Adding it to `ChoiceType` would be contradictory since you already control the choices.

**Comment by ro0NL** [comment]
> Adding it to ChoiceType would be contradictory since you already control the choices.

well, Intl types are also `ChoiceType`, but with a managed `choice_loader`. Conceptually this situation can apply to many predefined choice types; a generic `choice_filter` could be useful for any of those.

But i agree providing the right `choices/choic_loader` is best, while adding a type specific `choice_filter` option per case (in case the choice loader is managed).
