### ISSUE TITLE
[Var dumper] Add link only when terminal supports it

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#32653]
**Symfony version(s) affected**: 4.4

**Description**  
This probably was introduced in https://github.com/symfony/symfony/pull/30301. Links in CLI is a great thing by it should fail gracefully when not supported.

**How to reproduce**  
Run the following script in Gnome Terminal 3.6.2.
```
<?php

use Symfony\Component\VarDumper\VarDumper;

require __DIR__ . '/vendor/autoload.php';

class Foo {}
VarDumper::dump(new Foo());
```
The output would be like follows:
![dump](https://user-images.githubusercontent.com/673139/61624476-1c35c780-ac92-11e9-8342-e16c1753f2ad.png)

**Possible Solution**  
Render links only if user terminal supports it.

**Comment by ro0NL** [comment]
looks similar to https://github.com/symfony/symfony/issues/30665

i updated from 3.18 to 3.28, so i've no reference anymore how to detect it. Is it simple?

**Comment by nicolas-grekas** [comment]
There's already a check for this in the code. It looks like it doesn't work with your setup.
I think you're the best person to improve the check and detect the situation.
Can you please send a PR doing so?

**Comment by Chi-teck** [comment]
> There's already a check for this in the code.

Do you mean [this line](https://github.com/symfony/symfony/blob/v4.3.3/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L437)? I am afraid there is no reliable way to determine terminal capabilities. On my host i found COLORTERM variable which is set to "gnome-terminal" but it's not enough because gnome terminal does support hyperlinks since version 3.26. And besides that variable is empty in Docker sessions.
I can only think of supporting some custom environment variable that VarDumper would use. Something link `VAR_DUMPER_LINKS`.

For now, I am using `export KONSOLE_VERSION=1` to work around the issue.

**Comment by nicolas-grekas** [comment]
> For now, I am using export KONSOLE_VERSION=1 to work around the issue.

Thanks for the details. I think you've found the best option. This issue will disappear over time. I've no better idea. Disabling link by default would be a disservice to the majority that has a recent enough OS...

**Comment by Chi-teck** [comment]
Agree.
