### ISSUE TITLE
Define host-based Routes in the UrlMatcher BEFORE regular Routes?

### ISSUE THREAD

**Issue by brianfreytag** [symfony/symfony#32666]
**Symfony version(s) affected**: 3.4/29

**Description**  
I have two routes that point to "/". One of them is based on a host, the other is not. They are in different controller classes.

The first:
`DefaultController::dashboard` with the route `/` which is simply a redirect to a non-symfony legacy location.

The second:
`PublicController::safetyDataSheets` with the route `/{machineName}` where `machineName` is an optional parameter that is tied to a parameter in our Department entity. This also has a `host` section that points to `sds.{domain}`. 

If I attempt to go to `https://sds.test` it will redirect me to `DefaultController::dashboard`. However, if I go to `https://sds.test/electrical` it will take me to the PublicController::safetyDataSheets route. Going to `https://app.test/electrical` returns a 404 as it should.

What I'm seeing happening is that the UrlMatcher loads up routes in the order that they appear in the `Controller` namespace. Since `DefaultController` comes before `PublicController` it finds `"" === $trimmedPathinfo` and returns the `dashboard()` method without ever evaluating the host. It's not until we get to the `PublicController` routes that `$host = $context->getHost();` is defined. Then it does its preg_match on the hosts and then paths. 

**How to reproduce**  
```php
// AppBundle\Controller\DefaultController
class DefaultController extends Controller
{
    /**
     * @Route("/", name="default")
     *
     * @return Response
     */
    public function dashboard()
    {
        return $this->redirect($this->getParameter('app.url') . '/dashboard.php');
    }
}

// AppBundle\Controller\PublicController
class PublicController extends Controller
{
    /*
     * @Route(
     *     "/{machineName}",
     *     name="public_sds",
     *     host="sds.{domain}",
     *     defaults={"machineName"=null, "domain"="%domain%"},
     *     requirements={"domain"="%domain%"},
     *     methods={"GET"}
     *  )
     *
     * @param Department|null $department
     *
     * @return JsonResponse|Response
     */
    public function safetyDataSheets(Department $department = null) {}
}
```

The URL matcher class that is generated by routing finds the dashboard method in DefaultController on line 268 and returns it:

```php
// default
if ('' === $trimmedPathinfo) {
    $ret = array (  '_controller' => 'AppBundle\\Controller\\DefaultController::dashboard',  '_route' => 'default',);

    if ('/' === substr($pathinfo, -1)) {
        // no-op
     } elseif ('GET' !== $canonicalMethod) {
         goto not_default;
     } else {
         return array_replace($ret, $this->redirect($rawPathinfo.'/', 'default'));
     }
     
     return $ret;
}
```

However, it doesn't even define the host until 669:

```php
$host = $context->getHost();

if (preg_match('#^sds\\.(?P<domain>[^\\.]++)$#sDi', $host, $hostMatches)) {
    // public_sds
    if (preg_match('#^/(?P<machineName>[^/]++)$#sD', $pathinfo, $matches)) {
        $ret = $this->mergeDefaults(array_replace($hostMatches, $matches, ['_route' => 'public_sds']), array (  'domain' => 'test',  '_controller' => 'AppBundle\\Controller\\PublicController::safetyDataSheets',));
    
        if (!in_array($canonicalMethod, ['GET'])) {
            $allow = array_merge($allow, ['GET']);
            goto not_public_sds;
        }

        return $ret;
    }
    
    not_public_sds:
}
```

This ordering returns the wrong result when grabbing it with the matcher in `app.php` it returns the dashboard route even if I hit it with `sds.test`.

My `app.php` functions as a legacy wrapper that will first evaluate for Symfony routes. If it can't find one, it will look to see if the request matches a legacy procedural php script. If it does, it renders that script. If not, it returns the original 404:

```php
$matcher = $router->getMatcher();
$matcher->setContext($context);

try {
    $attributes = $matcher->match($request->getPathInfo());
} catch (ResourceNotFoundException $e) {
    // The route can't be found, so lets look for the legacy script, if that's not found throw the 404
}

foreach ($attributes as $key => $attribute) {
    $request->attributes->set($key, $attribute);
}

if (!isset($kernel)) {
    $kernel = new AppKernel($_SERVER['APP_ENV'], $debug);
}

if ($debug) {
    Debug::enable();
}

$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```

**Possible Solution**  
I'm wondering if it is possible to determine whether there are routes that are defined with hosts and adding those to the matcher first so that they can be evaluated by host first, and then loading the rest of them afterward.

**Additional context**  
The only way I could find to workaround this issue was to remove the annotations format and move the routing to my `app/config/routing.yml` file BEFORE the annotation-based routes:

```yaml
public_sds:
  path : /{machineName}
  host: "sds.{domain}"
  controller: AppBundle\Controller\PublicController::safetyDataSheets
  defaults:
    domain: '%domain%'
    machineName: null
  requirements:
    domain: '%domain%'

app:
  resource: "@AppBundle/Controller/"
  type:     annotation

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
```

**Comment by Tobion** [comment]
This is the expected behavior currently. Routes are check in the order they are defined. For annotations that means routes are defined in the order controllers are sorted by name. So DefaultController comes before PublicController.
If a route has no host requirement, any host will match. So if you want "default" route not to match `sds.test`, you need to define a different host requirement on it so it gets skipped. The alternative is, as you found out, to define routes in a different order.

> I'm wondering if it is possible to determine whether there are routes that are defined with hosts and adding those to the matcher first so that they can be evaluated by host first, and then loading the rest of them afterward.

That would be a BC break and complicate things and make it less predictable. The route priority is defined by the developer.
