### ISSUE TITLE
A long-term phper (symfony) advice on the symfony/api platform

### ISSUE THREAD

**Issue by lichnow** [symfony/symfony#32668]
As we all know, [php](https://php.net/) has a great ecosystem compared to the [golang](https://golang.org/) and [https://nodejs.org](https://nodejs.org/), but go does not (node.js is slightly better than go, but not compared to php). [symfony](https://symfony.com/)/[api platform](https://api-platform.com/) contrast [spring](https://spring.io/)/[spring boot](https://spring.io/projects/spring-boot)/ [spring cloud](https://spring.io/projects/spring-cloud), it is based on dynamic php implementation, and the development is very simple and fast.
But no matter golang, node, java-based spring, they can perfectly implement tcp, socket, parallel, coroutine, resident memory, micro-service and other functions, and php does it hard, and the former has higher than once Execute and then destroy a lot of php-fpm performance, but symfony is an enterprise-level framework, but can only develop backends of small apps with low concurrency. If you want to develop applications with slightly better performance, you need to add opcache, php-pm, varnish, etc. The only [Mercure component](https://symfony.com/doc/current/components/mercure.html) that can achieve the above functions is real-time communication. Microservices, parallelism, cannot be implemented.
Swoole is a very fast PHP server with c extension, support socket protocol, high concurrency, coroutine, resident memory, TCP protocol. And symfony is a great and even the best framework in the PHP world. The api platform is based on symfony's backend platform for quickly writing restful and graphql.
If you use swoole purely, you can't enjoy the sound ecology and perfect design pattern brought by api platform/symfony. But if you let api platform/symfony run in php-fpm, it will run very slowly, even if you add opcache or use php-pm, varnish and other additional applications, the effect is not very obvious. The speed of swoole is close to the go language, it is worth trying.
However, it is a pity to see that the symfony/api platform official does not have any integration plan for swoole. So make this suggestion: It is recommended that the official symfony or api platform plus how to integrate the swoole component documentation to improve the overall usage of PHP and reverse the trend of the decline in the number of PHP users.
And there is a small suggestion: symfony official documentation can be written a little more concise, like laravel, and if you can do some international maintenance, such as Chinese documents, Japanese documents, etc., this will be in the majority of Asia The country gets more support and gets more users, and there will be more communities in different languages, which is very helpful for the prosperity of PHP. Although laravel is slow, the architecture can't be compared with the beautiful symfony/api platform. Than, however, its good Chinese/Japanese community has enabled people from many countries such as China, Taiwan, Japan to contribute their own expansion packs and communities with many different languages, so the usage rate is high, and even there are swoole deep integration laravel laravels Such a very perfect package, and most of the phpers in China/Taiwan do not think that symfony can really develop the system. The understanding of symfony is only based on laravel based on symfony, and the php framework is equal to laravel. But laravel's design is not very good and spring bootmgo, node and other enterprise level And the asynchronous coroutine framework or language preemption share, resulting in the overall php usage rate has been declining in East Asia, the only possibility to change the trend is the symfony / api platform, but the use of native php perfect support tcp, socket, jit, parallel, etc. need a long time The way to go, swoole has been fully supported, but so far did not see any symfony / api platform integrated swoole any solution, only some of the community-only non-deep integration package maintained by almost no one. I haven't seen any complete Chinese/Japanese documentation for symfony official or community, all four suggestions are made here.

And with the popularity of vue, react, react native, flutter and other frameworks and mobile usage, today's website development is less and less, most of the work done by back-end languages such as php is the writing of api, so it is highly recommended to let symfony Use the api platform package as the default mode, and make mvc as an option, just like [https://docs.nestjs.com](https://docs.nestjs.com/).

1. Improve the official documentation, try to be as concise as possible, put various implementation examples into the document, do not have a separate external link (only for symfony)
2. Add official multi-language documents, such as Simplified Chinese/Japanese, etc.
3. Symfony or api platform provides an official integration of swoole solutions or extensions, and even provides an integration framework like laravels/laravel-swoole
4. use the api platform package as the default mode(only for symfony)

Finally, thanks to the great symfony and api platform for making our backend development so easy, the program is so robust, thank you.

**Comment by linaori** [comment]
> Improve the official documentation, try to be as concise as possible, put various implementation examples into the document, do not have a separate external link (only for symfony)

If you have concrete examples, you can propose changes for the docs here: https://github.com/symfony/symfony-docs/

> Add official multi-language documents, such as Simplified Chinese/Japanese, etc.

This is extremely difficult to maintain. This was done in the past for several EU languages and ended up being removed due to the complexity of maintaining it. If I'd make a change in the English documentation, all the other languages are out-of-date.

> use the api platform package as the default mode(only for symfony)

I don't think this way of creating applications should be forced on people by default. You have the choice of using Symfony this way and it should remain a choice.

**Comment by lichnow** [comment]
@linaori But I still think multi-language documentation is very useful, even if it has expired as the program changes, but the community will help update it. For example, if a Chinese document is provided, then even if the program is upgraded to 4.3 and the document stays at 4.2, the community can be encouraged to update to 4.3, but it does not have to be officially updated. Since I started using symfony from 1.2, there was no github or such a large number of users even though there were multi-language documents at that time. Many things may be more suitable with the time. As for swoole hope symfony official can provide a perfect solution, it is very necessary, it can solve micro service, a long connection, TCP, IO asynchronous coroutines, and so on the function of PHP does not bring, thus not only can the PHP and go contrast, can even compete with spring, don't know symfony official have the considerations?

**Comment by xabbuh** [comment]
There have been translations of the Symfony documentation in the past maintained by people from the community. However, we decided to not advertise them anymore since they were continuously outdated and then people started to open issues in the documentation repository about that. People can still translate the documentation, but for the reasons given they will not be treated as "official" translated nor be promoted on the Symfony website.

**Comment by linaori** [comment]
> But I still think multi-language documentation is very useful

It most certainly is, especially from the diversity perspective, see https://github.com/symfony/diversity/issues/20 for more information.

If you have any ideas on how to improve this, you're more than welcome to share them:
 - You can add localized resources here: https://github.com/symfony/diversity/issues/77
 - The issue related to the localized resources: https://github.com/symfony/diversity/issues/51

Sadly we are only with a few people that try to actively work on diversity and there so many topics to cover, so any help with this is always welcome!

**Comment by lichnow** [comment]
@linaori and Is there any official consideration about symfony's plan to integrate swoole?

**Comment by linaori** [comment]
I have no idea to be honest. I think it would be really nice to have official integration for a bunch of those tools, like we have the apache-pack (using flex to install this).

**Comment by lichnow** [comment]
@linaori In fact, PHP doesn't have any good solutions to support high concurrency, coroutines, asynchronous ios, TCP, etc. On this aspect of the mobile Internet era demand is far greater than the development site, perhaps this is the PHP user gradually reduce an important reason, of the same design patterns with symfony spring has spring boot and spring cloud implements these, and the node and go have supported these natural hope symfony also can pass the swoole extension support these functions, such as not just development site。

**Comment by lichnow** [comment]
@xabbuh Because symfony's documentation is so large, it is difficult to complete the translation after trying out a personal translation. Perhaps the correct pattern would be for the official translation to be a long-term maintenance version, such as 4.4, and for the community to be responsible for updating changes, such as 4.1, 4.2, 4.3,5.0... What are the authorities thinking about swoole or micro services, asynchronous IO, coronation?

**Comment by xabbuh** [comment]
> Perhaps the correct pattern would be for the official translation to be a long-term maintenance version, such as 4.4, and for the community to be responsible for updating changes, such as 4.1, 4.2, 4.3,5.0...

I am not sure if I understand what you mean with that. Could you provide some more input?

**Comment by lichnow** [comment]
@xabbuh  What I mean is that symfony official can only maintain the multi-language documentation of LTS and does not need to be updated. Leave the new version of the multilingual document or any changes of document updates to the community. This can be very efficient

**Comment by linaori** [comment]
That implies that all documentation still has to be written for the next LTS, meaning it's still written and the current version is always behind.

**Comment by lichnow** [comment]
@linaori  You might try translating the first version, such as 4.1 or 4.0 or later 5.0

**Comment by stof** [comment]
And this also assume that the translation for a given version is a frozen document. This assumption is wrong. The documentation for the active LTS is still constantly improved.

**Comment by lichnow** [comment]
@stof  Document translation is not the most important, and tools such as micro services, asynchronous coroutines, and others that improve PHP performance are

**Comment by Gemorroj** [comment]
Just want to note https://github.com/spiral/roadrunner. It will not give such a performance gain as swool. But it's really easy to integrate. And in relation to labor and productivity, roadrunner is very attractive.

**Comment by lichnow** [comment]
@Gemorroj Now I'm going to use springboot and spring cloud to build my current application, because it like symfony, and java have a better performance than PHP,  and Java has  multi-thread asynchronous features, and spring has the friendly Chinese documents, as for the roadrunner I might to will developing a personal application to try use in combination with symfony, and I've always been paid close attention to this project, or maybe may use go directly, thank you for your answer

**Comment by javiereguiluz** [comment]
@lichnow thanks for sharing these comments. We agree with most of them, even if we can't fix some for reasons out of our control (e.g. we want multi-lingual documents ... but we can't pay for them and the community can't maintain an up-to-date translation only with volunteers).

About the performance, the right solution would be that PHP add support for async/await. Meanwhile, we could explore other solutions, although is complicated. I know that @mmoreram is proposing something like that in #31314.

In any case, thanks again for your comments and we're going to close this issue as "fixed". If you have further comments about this, please consider joining the Symfony Slack (https://symfony.com/slack). Thanks!
