### ISSUE TITLE
Regex validation throw warning for :

### ISSUE THREAD

**Issue by bjgajjar** [symfony/symfony#32675]
# Bug Report
Not able to validate `:` in regex validation

## Steps to Reproduce

1. Trying to validate regex `/(?=^.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{':;'?>.<,])(?!.*\s).*$/`
2. It is throwing warning preg_match(): No ending delimeter '/' found in RegexValidator.php

**Comment by linaori** [comment]
Can you share how you create the constraint? If I look at the RegexValidator it will do `preg_match($constraint->pattern, $value)`, and that string looks valid.

**Comment by bjgajjar** [comment]
Hey @linaori 

Thanks for a quick response. It is really appreciable :)

Below is my constraint detail.
` $constraint = new Regex(['pattern' => '/(?=^.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{':;'?>.<,])(?!.*\s).*$/']);`

Let me tell you that this regex works perfectly when I tried to test this it with `preg_match` directly.

**Comment by xabbuh** [comment]
I don't see how your example could actually work at all since you have unescaped quotes inside the regex string. However, if I escape them with backslashes, I do not get the mentioned error.

Can you please create a small example application that allows to reproduce it?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by bjgajjar** [comment]
@xabbuh 

Apologize for the delay in response.

> I don't see how your example could actually work at all since you have unescaped quotes inside the regex string.

I required this in `Slim`  framework and I provided you a simple example as a quick response. Let me provide you a better one to help you out for tracking the issue. Below is my code please check that.  

 ```
$fieldObject = [
      'options'   => ['choices' => ['' => 'None', '/^.{8,}$/' => 'Weak', '/(?=^.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{\':;\'?>.<,])(?!.*\s).*$/' => 'Strong']]
];  

$conn->quote(json_encode($fieldObject['options']))
```

Which is throwing the error warning preg_match(): No ending delimiter '/' found in RegexValidator.php

Let me know if you require anything else.

**Comment by xabbuh** [comment]
I am sorry but I do not see how that snippet is related to the `Regex` constraint.
