### ISSUE TITLE
[HttpClient] Stream throws sometimes

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#32673]
**Symfony version(s) affected**: 4.3.*

**Description**  

According to the [Symfony docs](https://symfony.com/doc/current/components/http_client.html#dealing-with-network-errors), `HttpClientInterface::stream()` is not supposed to throw any errors but it seems like under some circumstances that's still the case.

**How to reproduce**  

It's pretty hard to reproduce because for me it seems to happen when I get a `502` server response but I wasn't able to mock it to create a test case. But maybe the stack trace can already help.
So this is the code I used:

```php
namespace MyProject;

class MyClass
{
    public function processResponses(array $responses): void
    {
        foreach ($this->getClient()->stream($responses) as $response => $chunk) {
            try {
                // Whatever is not 200 OK is not going to be processed any further
                if (200 !== $response->getStatusCode()) {
                    $response->cancel();
                    continue; // TODO: is that even needed? Does cancel() always turn into a TransportException?
                }
 
                if ($chunk->isLast()) {
                    // Process
                    $this->processResponse($response);
                }
            } catch (TransportExceptionInterface | RedirectionExceptionInterface | ClientExceptionInterface | ServerExceptionInterface $e) {
                // I should land here
            }
        }
    }
}
```

Stacktrace:

```
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\ServerException: HTTP/2 502  returned for "https://demo-url.com/foobar.html". in /project/vendor/symfony/http-client/Response/ResponseTrait.php:229
Stack trace:
#0 /project/vendor/symfony/http-client/Response/ResponseTrait.php(86): Symfony\Component\HttpClient\Response\CurlResponse->checkStatusCode()
#1 /project/vendor/symfony/http-client/Response/ResponseTrait.php(333): Symfony\Component\HttpClient\Response\CurlResponse->getHeaders(true)
#2 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, NULL)
#3 /project/vendor/symfony/http-client/Response/ResponseStream.php(44): Generator->next()
#4 /project/src/MyClass.php(262): Symfony\Component\HttpClient\Response\ResponseStream->next()
#5 /project/src/MyClass.php(256): MyProject\MyClass->processResponses(Array)
```

**Possible Solution**  

Depending on what I do I also get this sometimes during `CurlResponse::__destruct()` so I think the issue here is that under some circumstances (I kind of think when just no chunk arrives) `stream()` still throws which should not happen. So it's also related to https://github.com/symfony/symfony/issues/31187 because as you can see I'm actually trying to catch the `ServerExceptionInterface` inside my loop :)

**Comment by nicolas-grekas** [comment]
That's a bug, fixed in #32699
The try/catch should not be required, you can remove it (once #32699 is merged)

> also related to #31187

not possible: #31187 is a support issue

**Comment by Toflar** [comment]
> (but it would be useless for the other types, once #32699 is merged)

Because I'm checking for `200` myself and then `cancel()` which always throws a `TransportExceptionInterface`?

**Comment by Toflar** [comment]
Oh, forgot the most important thing: Thanks for fixing the bug! ❤️

**Comment by nicolas-grekas** [comment]
> Because I'm checking for 200 myself and then cancel() which always throws a TransportExceptionInterface?

cancel does throw (maybe it does with the bug, but that's ... a bug :)

**Comment by Toflar** [comment]
Okay, looking forward to the new bugfix releases then 😄 Thank you very much, Nicolas!

**Comment by GlobalWhite** [comment]
Looks like it is not fixed. Stream still throws, and in initial example - you can see, that it is 'ServerException: HTTP/2 502', which is thrown by the $response->getHeaders(true); here: https://github.com/symfony/http-client/blob/master/Response/ResponseTrait.php#L359 
So, stream will always throw, if server answers something other than 200.

**Comment by nicolas-grekas** [comment]
@GlobalWhite passing `true` means "do throw", see https://symfony.com/doc/current/components/http_client.html#handling-exceptions

**Comment by GlobalWhite** [comment]
Yep. And this is passed inside $client->stream. So, $client->stream will always throw, when server answers something other than 200. Take a closer look, where exactly this 'true' is passed.

**Comment by nicolas-grekas** [comment]
Oh, that's because you must read the status code when the first chunk arrives.

**Comment by GlobalWhite** [comment]
Yes, i found this "hack" already, but this is not obvious, because - in my case - i don't care about response status code here. So, looks like manual should be updated. :)

**Comment by nicolas-grekas** [comment]
> looks like manual should be updated. :)

I agree, I'm it on my list :)
