### ISSUE TITLE
[Translator] Command to compile translator cache

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#32686]
**Description**  
According to https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations, as a developper, I have to clear the whole cache every time I update a translation file.

Clearing the cache may take some time, so I would like a command to only clear the translation part of the cache.

**Example**  
For instance, the bundle https://github.com/overblog/GraphQLBundle creates a command `graphql:compile` (https://github.com/overblog/GraphQLBundle/blob/master/src/Command/CompileCommand.php) to manually compile the part of the cache it creates.

**Comment by pierredup** [comment]
Clearing the cache should only be necessary if you add new translation files (The doc also states `Each time you create a new translation resource (or install a bundle that includes a translation resource)...`

You can also just manually delete the `var/cache/dev/translations` directory then it should rebuild the translation cache

**Comment by linaori** [comment]
This is asking for cache stampedes because developers will call this on running websites.

**Comment by javiereguiluz** [comment]
@sylfabre thanks for opening this issue. First, what @pierredup is true ... you don't need to clear the cache when adding new translation strings ... only when adding a whole new translation file (which is very rare).

Also, in Symfony 4.3 we finally fixed that too (see #28937) so you don't have to clear the cache anymore even if you create new files. So, we're closing this as "fixed". However, if you are using Symfony 4.3 and this is not working for you, please reopen the issue with more details about the error. Thanks!

**Comment by sylfabre** [comment]
@javiereguiluz I am using Symfony 4.3 and this is not working for me. I have opened this issue: https://github.com/symfony/symfony/issues/32706
