### ISSUE TITLE
[Form] Form theme showing wrong method

### ISSUE THREAD

**Issue by andosteinmetz** [symfony/symfony#32687]
**Symfony version(s) affected**: 3.4.17

**Description**  
With a form whose method is set to `GET` in the Form Builder, the `FormView`'s method still appears as `POST` to the form theme, while appearing correctly as `GET` in the final template file.

**How to reproduce**  

Create a form and set the method to `GET`. Check `form.vars.method` in both the form theme and the twig template. In the template, the method will be 'GET' but in the form theme it will be 'POST'.
TestType.php:
```
class TestType extends AbstractType
{
    public function buildForm (FormBuilderInterface $builder, array $options)
    {
            $builder
                ->setAction('/search')
                ->setMethod('GET')
                ->add('search', TextType::class, array('label' => 'Search', 'required' => true));
    }
}
```

fields.html.twig:
```
{% block text_row %}
    {{ dump(form.vars.method) }} // 'POST'
    <label>{{ label }}</label>
    <input id="{{ id }}" type="text" 
      {%- if required %} required="required"{% endif -%}
      class="form__text-input {% if not valid %}form__text-input--error{% endif %}" 
      placeholder="{{ label }}" name="{{ form.vars.method == 'GET' ? name : full_name }}" value="{{ value|raw|escape }}" />
{% endblock %}
```

view.html.twig:
```
{{ dump(form.vars.method) }} // 'GET'
{% form_theme form with ['form/theme/fields.html.twig'] %}
    {{ form_row(form.search) }}
    <div class="desktop-flex">
        {{ form_row(form.locationName) }}
        {{ form_row(form.placeListedUnder) }}
        {{ form_row(form.country) }}
    </div>
    <div class="desktop-flex" style="width: 400px">
        {{ form_row(form.publishStart) }}
        {{ form_row(form.publishEnd) }}
    </div>
    {{ form_rest(form) }}
{{ form_end(form) }}
```

**Possible Solution**  

It appears that `form.vars.method` maybe applies only to the individual form field in the context of the theme, but if so why does  "form" refer to the form field and the field not inherit its parent form's method? What does it mean for a field to have its own method? How do I access the form's method in a form theme?

**Additional context**  

I am trying to get a clean url string for a search form, so I want to use the `name` property for form fields instead of `full_name` to set the html `name=` attribute. To do this, instead of creating an entire separate form theme with only this one difference, I thought I would check the form's method when setting that attribute in the form theme, but I'm unable because the form theme sees the method as `POST` regardless of how it's set in the form builder.

**Comment by yceruto** [comment]
In fact, the variable `form` refers to each individual field, including the root form. All of them are called `form` in their own context.

You have two options:
 * Pass the `GET` method to the `search` field directly.
 * Use `form.parent.vars.method` in the template

**Comment by yceruto** [comment]
On the other hand, whatever you want to do with `name` instead of `full_name` will make the form inoperative when you submit it, unless you are not using `$form->handlerRequest($request)` in your controller and have a custom logic to map (manually) each field to the form.

**Comment by andosteinmetz** [comment]
Thanks @yceruto. I realized that seemed to be the case as I was writing out the issue. That naming pattern (calling a field a form) seems a bit misleading and I'm still not sure what it means for an individual form field to have a method. But, `form.parent.vars.method` seems like it should do the trick.

We are in fact not using `$form->handleRequest()`, so using `name` will work fine for our purposes. Thanks again!
