### ISSUE TITLE
[HTTP foundation] performances of Request->getHost()

### ISSUE THREAD

**Issue by belinde** [symfony/symfony#32709]
**Description**  
As I'm writing a multi-domain application, I'm heavily relying on `Request->getHost()` method, and I noticed that the result is not cached; every time the method is called we have some array searches, two `preg_replace()`, at least one `array_count()`, and one to three `ServerBag->get()`. I think the result of the method could be safely cached in a private property, but maybe there's some use case I don't know about.
I think that this optimization should break only if someone is juggling with `$_SERVER` values, and this shoulb be considered a bad habit - but maybe is a common practice, out there?
On the other hand, maybe my use case is an example of bad coding, because I ask for Request in almost every controller's method and also in 5 event subscribers.

Feel free to tell me that it's an horrible idea! (but tell me why :smiley:)

**Example**  
```php
private $host = null;

public function getHost()
{
    if (is_null($this->host)) {
        // Current method's code, setting $this->host instead of returning
    }
    return $this->host;
}
```
If this should be consedered an improvement, I can surely provide a real PR.

**Comment by nicolas-grekas** [comment]
A PR against branch 4.4 would be great for sure.

**Comment by lbassin** [comment]
Does anyone work on this issue? I have some free time and I can provide a PR this week

**Comment by belinde** [comment]
I had some problems at work, so I didn't work on in. Go ahead, and thank you!

**Comment by nicolas-grekas** [comment]
I just had a look at the code and at the linked PR: this cannot work because in order to reset the cached host, we'd need to track changes to headers and server variables. That's not possible.

I'd recommend getting the host once and reusing the return value instead.
