### ISSUE TITLE
Setting SYMFONY_PHPUNIT_VERSION does not work correctly for simple-phpunit

### ISSUE THREAD

**Issue by pmishev** [symfony/symfony#32704]
**Symfony version(s) affected**: 4.3.2 (with PHP 7.3)

**Description**  
phpunit 8 has a breaking change in the `PHPUnit\Framework\TestCase::setUp(): void` signature.
So, in order to keep my tests working in both Symfony ^3.4 and ^4.0, I try to limit the phpunit version by putting:
`<env name="SYMFONY_PHPUNIT_VERSION" value="7.5" />` in `phpunit.xml.dist`

but I get:
```
PHP Fatal error:  Declaration of Sineflow\ElasticsearchBundle\Tests\Unit\DependencyInjection\Compiler\RegisterDataProvidersPassTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void
```
So it looks like, although the 7.5 version of phpunit is downloaded, it still autoloads the 8.* version of phpunit from the initial install.

**How to reproduce**  

Full test results can be seen at: https://travis-ci.org/sineflow/ElasticsearchBundle/builds/562707455. but in short:

In composer.json:
```
    "require-dev": {
        "symfony/phpunit-bridge": "^3.4 || ^4.0",
```

**working: php7.1 + Sf4.0:**
```
  ...
  - Installing symfony/phpunit-bridge (v4.3.2): Downloading (100%)
  - Installing phpunit/phpunit (7.5.14): Downloading (100%)
  ...

$ vendor/bin/simple-phpunit

  ...
  - Installing phpunit/phpunit (7.5.14): Loading from cache
  - Installing symfony/phpunit-bridge (7.5.99): Symlinking from /home/ElasticsearchBundle/vendor/symfony/phpunit-bridge
  ...

Writing lock file
Generating optimized autoload files
PHPUnit 7.5.14 by Sebastian Bergmann and contributors.
```

---------------

**not working: php7.3 + Sf4.0:**
```
  ...
  - Installing symfony/phpunit-bridge (v4.3.2): Downloading (100%)
  - Installing phpunit/phpunit (8.2.5): Downloading (100%)
  ...

$ vendor/bin/simple-phpunit

  ...
  - Installing phpunit/phpunit (7.5.14): Downloading (100%)
  - Installing symfony/phpunit-bridge (7.5.99): Symlinking from /home/ElasticsearchBundle/vendor/symfony/phpunit-bridge
  ...


Writing lock file
Generating optimized autoload files
PHP Fatal error:  Declaration of Sineflow\ElasticsearchBundle\Tests\Unit\DependencyInjection\Compiler\RegisterDataProvidersPassTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/sineflow/ElasticsearchBundle/Tests/Unit/DependencyInjection/Compiler/RegisterDataProvidersPassTest.php on line 175
PHP Stack trace:
PHP   1. {main}() /home/travis/build/sineflow/ElasticsearchBundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit:0
PHP   2. require() /home/travis/build/sineflow/ElasticsearchBundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit:13
PHP   3. include() /home/travis/build/sineflow/ElasticsearchBundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:258
PHP   4. PHPUnit\TextUI\Command::main() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/phpunit:17
PHP   5. Symfony\Bridge\PhpUnit\Legacy\CommandForV6->run() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/TextUI/Command.php:162
PHP   6. Symfony\Bridge\PhpUnit\Legacy\CommandForV6->handleArguments() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/TextUI/Command.php:173
PHP   7. PHPUnit\Util\Configuration->getTestSuiteConfiguration() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/TextUI/Command.php:912
PHP   8. PHPUnit\Util\Configuration->getTestSuite() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/Util/Configuration.php:1003
PHP   9. PHPUnit\Framework\TestSuite->addTestFiles() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/Util/Configuration.php:1137
PHP  10. PHPUnit\Framework\TestSuite->addTestFile() /home/travis/build/sineflow/ElasticsearchBundle/vendor/phpunit/phpunit/src/Framework/TestSuite.php:439
PHP  11. PHPUnit\Util\FileLoader::checkAndLoad() /home/travis/build/sineflow/ElasticsearchBundle/vendor/phpunit/phpunit/src/Framework/TestSuite.php:347
PHP  12. PHPUnit\Util\FileLoader::load() /home/travis/build/sineflow/ElasticsearchBundle/vendor/bin/.phpunit/phpunit-7.5/src/Util/FileLoader.php:45
```

**Comment by pierredup** [comment]
Your project already includes phpunit 8, which is installed as part of `jchook/phpunit-assert-throws` which is included in your dependencies. When running your test suite, the composer autoloader picks up this version of the classes to use, and not the ones installed by the phpunit-bridge

**Comment by pmishev** [comment]
Thank you, this seems to solve the problem. However the documentation around "prepend-autoloader" is pretty scarce, so I'm not entirely sure could this potentially lead to any other unwanted side-effects with the project?

Ideally I would expect `phpunit-bridge` to take care of such situations, because any project with an inherited dependency on phpunit would have such problem. Especially as now using phpunit directly is discouraged in the symfony docs.

**Comment by pierredup** [comment]
> so I'm not entirely sure could this potentially lead to any other unwanted side-effects with the project?

If you don't use any other autoloaders or custom autoloaders, then there shouldn't be any other effects on the project.

> Ideally I would expect phpunit-bridge to take care of such situations, because any project with an inherited dependency on phpunit would have such problem

I'm not sure if there are other ways around this, but I agree `phpunit-bridge` should take care of this, I'm just not sure how yet

**Comment by nicolas-grekas** [comment]
Closing as there's nothing we can do here. Please send a PR if you don't agree :)
