### ISSUE TITLE
[PHPUNIT-BRIDGE] Unable to install phpunit cause of composer dependencies

### ISSUE THREAD

**Issue by letordj** [symfony/symfony#32702]
**Symfony version(s) affected**: 4.3
**Description**  
getting the following error executing bin/phpunit command :

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - phpunit/phpunit-mock-objects 5.0.10 conflicts with phpunit/phpunit[No version set (parsed as 1.0.0)].
    - phpunit/phpunit-mock-objects 5.0.9 conflicts with phpunit/phpunit[No version set (parsed as 1.0.0)].
    - Installation request for phpunit/phpunit No version set (parsed as 1.0.0) -> satisfiable by phpunit/phpunit[No version set (parsed as 1.0.0)].
    - Installation request for phpunit/phpunit-mock-objects ^5.0.9 -> satisfiable by phpunit/phpunit-mock-objects[5.0.10, 5.0.9].

**How to reproduce**  
after phunit-bridge install
```bin/phpunit```

**Possible Solution**  
Add this line to simple-phpuni.php (122 or elsewhere) to add a vesrion in composer.json file

```file_put_contents('composer.json', preg_replace('/"type": "library"/', '"version": "'.$PHPUNIT_VERSION.'",'."\n".'    "type": "library"', file_get_contents('composer.json')));```

**Comment by xabbuh** [comment]
Do you have a `SYMFONY_PHPUNIT_VERSION` environment variable set?

**Comment by letordj** [comment]
It's not the problem, version is set but not on the  phpunit composer file,
and composer cannot get dependencies

**Comment by letordj** [comment]
```
php bin/phpunit 
Installing phpunit/phpunit (6.5.14)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.14): Downloading (100%)
Created project in phpunit-6.5
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit-mock-objects 5.0.10 conflicts with phpunit/phpunit[No version set (parsed as 1.0.0)].
    - phpunit/phpunit-mock-objects 5.0.9 conflicts with phpunit/phpunit[No version set (parsed as 1.0.0)].
    - Installation request for phpunit/phpunit No version set (parsed as 1.0.0) -> satisfiable by phpunit/phpunit[No version set (parsed as 1.0.0)].
    - Installation request for phpunit/phpunit-mock-objects ^5.0.9 -> satisfiable by phpunit/phpunit-mock-objects[5.0.10, 5.0.9].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

**Comment by nicolas-grekas** [comment]
I don't reproduce the issue, could you please share a repositories that does? Of step by step instructions one could run locally maybe?
