### ISSUE TITLE
[Cache] Purging takes forever with new FilesystemTagAwareAdapter

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#32701]
**Symfony version(s) affected**: 4.3.*

**Description**  

With the new optimized `FilesystemTagAwareAdapter` tags are now stored as symlinks.
See https://github.com/symfony/symfony/pull/30370.

Now when you have a considerable number of cache entries or especially tags, `$cache->prune()` will take forever because there's no special `prune()` implementation in that new adapter. It just uses the `prune()` of the `FilesystemTrait` which loops over all the files and is doing an `fopen()` (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Cache/Traits/FilesystemTrait.php#L31).

So imagine you have 10 000 cache entries and 100 000 tags, that's going to take quite a while.
I'm not even sure if tags can expire? So maybe we should implement `prune()` in such a way that it excludes the `tags` folder?

**How to reproduce**  

1. `mkdir test && cd test`
2. `composer require symfony/cache symfony/filesystem`
3. `mkdir cache`
4. Add the following `test.php` and run it using `php test.php`:

```php
<?php

use Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter;
use Symfony\Contracts\Cache\ItemInterface;

require_once 'vendor/autoload.php';

$cache = new FilesystemTagAwareAdapter('', 0, __DIR__ . '/cache');

for ($i = 0;$i < 10000; $i++) {
    $value = $cache->get(bin2hex(random_bytes(4)), function (ItemInterface $item) {
        $item->expiresAfter(3600);

        for ($j = 0;$j < 10; $j++) {
            $item->tag(bin2hex(random_bytes(4)));
        }

        return 'foobar';
    });
}

echo 'Generated entries and tags. Now pruning...' . "\n";

$cache->prune(); // now you should be feeling how long it takes
```

**Possible Solution**  

Maybe just exclude the `tags` folder from pruning. But if we can, we should also clean up tags that do not point to any valid cache entry anymore so we don't have any orphan tag symlinks.

Gonna cc @andrerom here because he implemented the new optimized adapter which is otherwise working perfectly so thanks again! 😄

**Comment by nicolas-grekas** [comment]
I think that's an expected limitation. Maybe we can improve the pruning process to delete links/files faster, but in the end this is always going to be the drawback of this adapter, and the moment where you'll need to use the generic `TagAwareAdapter`, which is free from this issue.
See `https://github.com/symfony/symfony/issues/26178#issuecomment-365678036` for some background on how it works.

**Comment by Toflar** [comment]
Yeah sure, I just wanted to point out that the new adapter is looping over all the tags as well which does not seem to make sense to me :)

**Comment by andrerom** [comment]
Is prune supposed to deal with race conditions?

**Comment by Toflar** [comment]
I don't think it needs to. I just wonder if we cannot improve the purging mechanism or make it smarter somehow for the `FilesystemTagAwareAdapter`. Right know it generates thousands of symlinks so it takes forever to clean up by looking at every file/link.

**Comment by andrerom** [comment]
Well, what if it atomically removes the tag folder and afterwards passes on to parent::prune which iterates (actuall) cache files to delete all? _(it will have to skip tag folder at this point thought in case of parallel processes)_ Or did you have something else in mind?

**Comment by Toflar** [comment]
`prune()` only removes **expired** cache entries :) So I guess we cannot just delete the whole tags folder :) In fact, we would need to delete all the actual expired cache entries and then delete orphan symlinks or so. Does that make sense what I'm saying?

**Comment by andrerom** [comment]
> prune() only removes expired cache entries :) 

true, explains the iteration..

> we would need to delete all the actual expired cache entries and then delete orphan symlinks or so

yes, or read which tags cache entries has before removing it and implicit then now which relationships to drop, whichever way is faster.

**Comment by nicolas-grekas** [comment]
@Toflar any PR you'd like to try? Maybe just some documentation/docblock, explaining the limitation?

**Comment by Toflar** [comment]
I'm off for the next 4 weeks so I won't be able to do anything atm. But imho we should somehow document which adapters are faster on read and which ones are faster on prune :)
It's not really a limitation, it's just optimized for a different use case imho.
