### ISSUE TITLE
Container building performance with lazy autowire error messages

### ISSUE THREAD

**Issue by bsod85** [symfony/symfony#32711]
**Symfony version(s) affected**: 4.3.*

**Description**  
Performance of container building has been degraded after 4.3 update

**How to reproduce**  
https://github.com/bsod85/sf_autowire_performance
By switching the symfony/dependency-injection between 4.2.* and 4.3.*, after a composer update I obtain these results with the command "time bin/console cache:clear":
Version 4.3 -> 107,57s user 0,49s system 99% cpu 1:48,07 total
Version 4.2 -> 24,77s user 0,45s system 99% cpu 25,233 total

**Additional context**  
After a bisect I came to the conclusion that the problem has been introduced in commit https://github.com/symfony/symfony/commit/3b3a1bd3cce9eddcf42f95e2a5a3872ee1253927
The AutowirePass::createTypeNotFouldMessageCallback() method creates a new copy of the entire container for each encountered error.
This severely hinders the performance on big projects if many non-autowirable classes are processed by the "resource" option.

**Comment by nicolas-grekas** [comment]
Can you please provide a blackfire.io comparison before/after the commit you mention?

**Comment by nicolas-grekas** [comment]
Can you please also check if #32715 improves the situation?

**Comment by bsod85** [comment]
Had to apply this fix to make the specific commit work
https://github.com/symfony/symfony/commit/b0925025f8dce5a4b38f9403976c1c6180cf69ff

Here are the profiles:
before: https://blackfire.io/profiles/232b3e72-f8cf-4438-b8b7-798bc6004e83/graph
after: https://blackfire.io/profiles/8c90e987-3e20-4762-9f6d-ed9f4ac2b959/graph
with fix: https://blackfire.io/profiles/3c0b255e-7bdd-499b-8013-e99f46751592/graph

The fix seems to improve the situation but still much time is spent in the setDefinitions method.
Shouldn't the lazy message callback be called only when the error is to be displayed? Looking at the profile it doesn't seem so.

Let me know if there's anything else I can do

**Comment by nicolas-grekas** [comment]
Thanks for the profile, that's really eliminating the guesswork!
Can you try the updated patch in the PR and post the resulting profile, please?

**Comment by bsod85** [comment]
https://blackfire.io/profiles/76a5be15-be03-4f5b-9d38-af355f647355/graph

Now it seems much better

**Comment by nicolas-grekas** [comment]
Thanks, problem solved then. PHP 7.3 will provide an additional perf improvement by reducing the pressure on the GC I think.

**Comment by bsod85** [comment]
Thank you very much
