### ISSUE TITLE
Contracts ResetInterface not found in Console component

### ISSUE THREAD

**Issue by vuras** [symfony/symfony#32716]
**Symfony version(s) affected**: 4.3.2

**Description**  
 Script cache:clear returned with error code 255
  !!  PHP Fatal error:  Interface 'Symfony\Contracts\Service\ResetInterface'
  not found in /vendor/symfony/console/Formatte
  r/OutputFormatterStyleStack.php on line 20
  !!
  Script @auto-scripts was called via post-install-cmd

**How to reproduce**  
run composer install  --no-interaction --no-dev --optimize-autoloader --no-suggest

**Comment by xabbuh** [comment]
I don't see how this could be happening as the `symfony/service-contracts` package is a dependency of the Console component. Can you create a small example application that allows to reproduce this?

**Comment by vuras** [comment]
I thought the same. I don't know what was the exact problem, but I have updated Composer from 1.7.2 to 1.8.6 and the problem is gone, no errors now.

**Comment by nicolas-grekas** [comment]
OK, no bug on our side then. Thanks for reporting back.

**Comment by martijnhartlief** [comment]
Same thing happened to me when moving from Symfony 4.2 to 4.3. Updating composer resolved the issue for me aswell.

**Comment by raoulwegat** [comment]
Getting the same error for Symphony 4.4.2 on composer install. Updating composer from 1.8.5 to 1.9.1 does nothing.

**Comment by xabbuh** [comment]
Please open a new issue and provide a small example application that allows to reproduce.

**Comment by jarrettj** [comment]
Same error when I tried running my codeception tests lately. Updating composer did not work. My fix was to explicitly require the symfony/service-contracts package.
