### ISSUE TITLE
[DoctrineBridge] By default cannot use @UniqueEntity constraint

### ISSUE THREAD

**Issue by kniziol** [symfony/symfony#32743]
**Symfony version(s) affected**:
4.3.2

**Description**

`symfony/doctrine-bridge` does not require explicitly `symfony/validator` and raises exception while using `Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity` annotation

**How to reproduce**

1. Install minimalistic Symfony (for a microservice, console application or API):
`symfony new my_project`

2. Install Doctrine ORM:
`composer require symfony/orm-pack`

3. Create an entity (the default `id` property is enough):
`console make:entity --no-interaction JustTesting`

Here is the generated entity:

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\JustTestingRepository")
 * @UniqueEntity({"family", "edition"})
 */
class JustTesting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```
4. Add `@UniqueEntity` constraint to the entity:

- `use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;`
and
- `@UniqueEntity({"id"})`

Here is full code of the entity:

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JustTestingRepository")
 * @UniqueEntity({"id"})
 */
class JustTesting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

5. Cannot generate another entity
Result of `console make:entity` command:

```bash
$ console make:entity                             

Fatal error: Class 'Symfony\Component\Validator\Constraint' not found in /vendor/symfony/doctrine-bridge/Validator/Constraints/UniqueEntity.php on line 24
2019-07-25T14:14:32+00:00 [critical] Fatal Error: Class 'Symfony\Component\Validator\Constraint' not found

In UniqueEntity.php line 24:

  Attempted to load class "Constraint" from namespace "Symfony\Component\Validator".                                       
  Did you forget a "use" statement for e.g. "Doctrine\DBAL\Schema\Constraint" or "Composer\Semver\Constraint\Constraint"?  

make:entity [-a|--api-resource] [--regenerate] [--overwrite] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]
```

**Question**

Package `symfony/validator` is placed in `require-dev` section, so it's not installed after installation of `symfony/doctrine-bridge`.

Maybe should it be moved to the `require` section?

**Comment by xabbuh** [comment]
Having the Validator component not listed as a required dependency is intended as the bridge can be used totally fine as long as you do not need to use the `UniqueEntity` constraint.

**Comment by kniziol** [comment]
@xabbuh I understand. I'm afraid if there is more issues like this, related to other implicitly required Symfony components.

**Comment by derrabus** [comment]
How do you evaluate the `UniqueEntity` constraint without a validator?

You probably want to define a unique constraint for the database schema. This is **not** what this annotation does.

**Comment by kniziol** [comment]
@derrabus Thank you for the suggestion and link to documentation. IMHO, it looks strange when class `UniqueEntity` extends `Symfony\Component\Validator\Constraint`:

```php
<?php

namespace Symfony\Bridge\Doctrine\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

class UniqueEntity extends Constraint
{
// ...
```

but there is no such class, because `symfony/doctrine-bridge` package suggests to install `symfony/validator` package only. If the `symfony/validator` package will be required, everything will be clear, I think, and will work out of the box.

**Comment by derrabus** [comment]
> If the `symfony/validator` package will be required

… everybody who installs the bridge would have a full-blown validator installed even though they might never need it. The bridge is a lose collection of glue code between Doctrine and various Symfony components. For instance, there are extensions to the Messenger components as well in that package. Should we add the messenger as a direct dependency as well? That would just bloat your vendors folder.

* You don't need the validator to use the Doctrine bridge.
* It doesn't make sense to use extensions to the validator without a validator.
* And *if* you want to use the validator in your project, the validator should be a direct dependency of your project.

**Comment by xabbuh** [comment]
I am closing here as the current tree of dependencies is done on purpose as explained above. Thank you for understanding.

**Comment by Pictor13** [comment]
Just a note: the third point mentioned from @derrabus is implicit, if one pays attention to the composer install log.
[On the current master](https://github.com/symfony/doctrine-bridge/blob/6753f87b44c1a4aff09f9a35f3f33f911192f074/composer.json#L62) the *doctrine-bridge* tells the user that the *validator* **might** be necessary, via Composer's `suggest`.
