### ISSUE TITLE
Better error messages in failing tests

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#32752]
**Description**  
Recently, when running some PHPUnit tests in a CI service, I saw these failing tests:

```
1) App\Tests\Controller\SomeControllerTest::testSomething with data set #0 ('...', '..', '...')
Failed asserting that the Response has header "Content-Type" with value "application/pdf".
```

I spent some time debugging the problem because I recently fixed this feature and I knew it worked on my local computer, on the server, etc. So, why was it failing only in the CI service? I had to SSH-login into it, debug things manually, etc. At the end, a simple `dd($this->client->getResponse())` showed the real problem:

```
<title>An exception has been thrown during the rendering of a template
("file_get_contents(/home/circleci/project/public/build/some-file.css):
failed to open stream: No such file or directory"). (500 Internal Server Error)</title>
```

As you can see, the Symfony exception message is perfect and tells you the problem instantly .. while the PHPUnit error message only confuses you.

**Possible solution**

All these would have been solved if PHPUnit failing tests showed the real exception message from Symfony. Could we add that to the error messages shown by PHPUnit? Thanks!

**Comment by Pierstoval** [comment]
For that, we would need to get access to the Symfony Profiler, get the exception collector and find a way to display them in the PHPUnit's output, like by throwing them again (but PHPUnit will say `E` for "error in test" instead of `F` for "test failed", even though it's okay for me).

A custom assertion such as `assertResponseHasNoException()` would probably do the trick, WDYT?

**Comment by fancyweb** [comment]
What about a `WebTestCase` dedicated PHPUnit result printer?

**Comment by stof** [comment]
@fancyweb I don't see how that would help. not all failures in a WebTestCase are related to receiving a Symfony error page.

**Comment by dmaicher** [comment]
How we are doing it on our big Symfony work project:

We use a special kernel just for the `test` environment that remembers kernel exceptions:

```php
class TestAppKernel extends \AppKernel
{
    /**
     * @var \Exception|null
     */
    protected $lastKernelException = null;

    public function boot(): void
    {
        parent::boot();
        $this->registerAsExceptionListener();
    }

    public function shutdown(): void
    {
        $this->lastKernelException = null;
    }

    protected function registerAsExceptionListener(): void
    {
        $this->lastKernelException = null;

        $this->getContainer()->get('event_dispatcher')->addListener(
            KernelEvents::EXCEPTION,
            [$this, 'onKernelException']
        );
    }

    public function onKernelException(GetResponseForExceptionEvent $event): void
    {
        $this->lastKernelException = $event->getException();
    }

    public function getLastKernelException(): \Exception
    {
        return $this->lastKernelException;
    }
}
```

And then we have a helper for WebTestCases

```php
    protected function assertResponseStatusCode(int $code, Client $client): void
    {
        $response = $client->getResponse();
        $this->assertNotNull($response, 'Cannot assert on StatusCode when Response is null!');
        $status = $response->getStatusCode();
        if ($status !== $code) {
            $msg = "Failed asserting that the HTTP status code is $code! Actual status code is ".$status;
            /** @var \Exception $exception */
            if ($exception = $client->getContainer()->get('kernel')->getLastKernelException()) {
                $msg .= PHP_EOL.$exception->getMessage().PHP_EOL.$exception;
            } elseif ($response->headers->get('content-type') === 'application/json') {
                $msg .= PHP_EOL.$response->getContent();
            }
            $this->fail($msg);
        }
    }
```

I would love to see some easier out-of-the-box solution though :blush:

**Comment by nicolas-grekas** [comment]
We could have the ErrorHandler component put the message in a dedicated HTTP header (debug mode only of course) and make functional tests aware of it.

**Comment by dmaicher** [comment]
> We could have the ErrorHandler component (its renderers?) put the message in a dedicated HTTP header (debug mode only of course) and make functional tests aware of it.

@nicolas-grekas yeah that's better than nothing but a stack trace would be really helpful for debugging :blush:

**Comment by nicolas-grekas** [comment]
@dmaicher you're asking for the functional test system to implement the client side part of the firephp prototol :)

**Comment by guillbdx** [comment]
Having the ErrorHandler forward the Exception code/message in debug mode sounds efficient.

Hard thing is to display properly this message in the bug report. Ideally we would want something like:

```
1) App\Tests\Controller\SomeControllerTest::testSomething with data set #0 ('...', '..', '...')
Failed asserting that the Response has header "Content-Type" with value "application/pdf".
An exception occured: message...
```

I tried to add the message thanks to the TestListener, but it seems not feasible: there's no way to add or modify a message in the Test Result at this point. And even if we could, we would still have to retrieve the client response, which is not possible: no way to get an existing client if it exists, and there can be multiple clients in a test case, etc.

But i think we could do this: All assertions, be them from BrowserKitAssertionsTrait or from the PHPUnit\Framework\Assert itself, drive to the assertThat() method. So we could override this method in WebTestCase for something like that (draft to improve):

```
    public static function assertThat($value, Constraint $constraint, string $message = ''): void
    {
        if ($value instanceof Response) {
            $exceptionHeader = $value->headers->get('X-Exception');
            $message .= $exceptionHeader;
        }
        parent::assertThat($value, $constraint, $message);
    }
```

Of course, that will check for an exception only when the assertion is done on a Response object. But that is the case for almost all assertions in BrowserKitAssertionsTrait.

What do you think?

**Comment by nicolas-grekas** [comment]
Hi all, please check #36003
