### ISSUE TITLE
SwitchUserToken incompatible with always_authenticate_before_granting

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony#32756]
**Symfony version(s) affected**: 4.3

**Description**  
If a user is impersonating another user, the `Symfony\Component\Security\Core\Authentication\Token\SwitchUserToken` is created. But then, a Authentication Provider cannot be found for this token if the [`always_authenticate_before_granting` configuration option](https://symfony.com/doc/current/reference/configuration/security.html#always-authenticate-before-granting) is set to `true`. This is  causing a redirect loop as printed in the logfile:

> security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. [...] ProviderNotFoundException: No Authentication Provider found for token of class SwitchUserToken at [...]AuthenticationProviderManager.php:107)"

This exception is not thrown if `always_authenticate_before_granting` is removed from the security.yaml file.

**How to reproduce**  

1. Set `always_authenticate_before_granting` to true
1. Impersonate a user
1. Visit a URL that is behind a firewall

**Possible Solution**  
I have no idea how to fix this. This issue #8974 is very similar to this one, but this is six years old.

**Comment by xabbuh** [comment]
Would the `NullToken` introduced in #37620 help here?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by ndoulgeridis** [comment]
I have this same behavior on 5.3.7, any idea how to fix it?
