### ISSUE TITLE
[CONSOLE] PHP 7.4: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by mfn** [symfony/symfony#32750]
**Symfony version(s) affected**: 4.3.2

**Description**  
The tests of https://github.com/rebing/graphql-laravel break on 7.4 due to this error, here's the most recent travis log:

https://travis-ci.org/rebing/graphql-laravel/jobs/563742611#L321-L335

```
1) Rebing\GraphQL\Tests\Database\MutationValidationUniqueWithCustomRulesTests\MutationValidationUniqueWithCustomRulesTest::testUniquePassRulePass
ErrorException: Trying to access array offset on value of type int
/home/travis/build/rebing/graphql-laravel/vendor/symfony/console/Input/ArrayInput.php:135
/home/travis/build/rebing/graphql-laravel/vendor/symfony/console/Input/Input.php:55
/home/travis/build/rebing/graphql-laravel/vendor/symfony/console/Application.php:208
/home/travis/build/rebing/graphql-laravel/vendor/symfony/console/Application.php:149
/home/travis/build/rebing/graphql-laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php:90
/home/travis/build/rebing/graphql-laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php:182
/home/travis/build/rebing/graphql-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:275
/home/travis/build/rebing/graphql-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:136
/home/travis/build/rebing/graphql-laravel/vendor/orchestra/testbench-core/src/Database/MigrateProcessor.php:73
/home/travis/build/rebing/graphql-laravel/vendor/orchestra/testbench-core/src/Database/MigrateProcessor.php:44
/home/travis/build/rebing/graphql-laravel/vendor/orchestra/testbench-core/src/Concerns/WithLoadMigrationsFrom.php:27
/home/travis/build/rebing/graphql-laravel/tests/TestCaseDatabase.php:15
```

**How to reproduce**  
Run the test suite of https://github.com/rebing/graphql-laravel with PHP 7.4

The project only has an implicit dependency on symfony/console but the version installed is also in the logs => https://travis-ci.org/rebing/graphql-laravel/jobs/563742611#L280 :
```
  - Installing symfony/console (v4.3.2): Loading from cache
```

Seems the error happens here: https://github.com/symfony/console/blob/7662535c9c9840dc103da7174a8c4064d876fe84/Input/ArrayInput.php#L135

**Comment by xiaohuilam** [comment]
https://github.com/xiaohuilam/laravel-admin-select2/issues/38 is the same

**Comment by nicolas-grekas** [comment]
Please send PRs on branch 3.4 with a patch fixing as many of those as possible.
Support for PHP7.4 is still in early WIP stage, see e.g.  #32289 
Any contributions to reach the goal is welcome.

**Comment by mfn** [comment]
I've never contributed to symfony so far and I'm already too dumb to run the tests for symfony/console ; without working on the code so far I closed the symfony/console repo.

1. Problem: no phpunit in composer; do I need to use a global installation or download the phar?
2. No Problem! Downloaded it from https://phpunit.de/getting-started/phpunit-8.html
3. Bummer: `PHP Fatal error:  Declaration of Symfony\Component\Console\Tests\ApplicationTest::setUpBeforeClass() must be compatible with PHPUnit\Framework\TestCase::setUpBeforeClass(): void in /src/symfony-console/Tests/ApplicationTest.php on line 1782`
4. Tried to fine something in the docs, no luck at https://symfony.com/doc/current/contributing/code/tests.html at least
5. So I guess not phpunit 8.2.5 but ... which version? 7?
6. No Problem! Downloaded it from https://phar.phpunit.de/phpunit-7.phar
7. 💥 
  ```
  phpunit-7.5.14.phar 
  Class "Symfony\Bridge\PhpUnit\SymfonyTestsListener" does not exist
  ```
  I did run composer install before all that…

Also tried the 3.4 branch, no luck.

I start to get the feeling it's not supposed to run only in the isolated repository.

I give up :-( I think I totally missed the correct docs on Step 0), any links appreciated!

**Comment by nicolas-grekas** [comment]
This page might help:
https://symfony.com/doc/current/contributing/code/tests.html

**Comment by xabbuh** [comment]
@mfn Do the steps described at https://symfony.com/doc/current/contributing/code/pull_requests.html help? Basically, you need to clone the `symfony/symfony` repository and the use the `phpunit` wrapper script to run the tests.

**Comment by mfn** [comment]
Ah, umbrella project structure like Laravel 🤦‍♂️ Should have realized this.

> This page might help:
> https://symfony.com/doc/current/contributing/code/tests.html

Yeah, that's same link I pasted above, however …

>  Basically, you need to clone the symfony/symfony repository and the use the phpunit wrapper script to run the tests.

The missing link 🔗! Hole 32k tests…

Working now, thanks and sorry for the noise here. Tried my best to get there on my own but alas it wasn't good enough. Thanks

**Comment by nicolas-grekas** [comment]
Fixed in #32806

**Comment by Synida** [comment]
I've got the exact same error with php 7.4.0
symfony/console                             v4.4.1             Symfony Console Component

**Comment by xabbuh** [comment]
@Synida Can you please open a new issue and provide a small example application that allows to reproduce it?

**Comment by Synida** [comment]
Solved, the issue was on my side. False alarm. Sorry

**Comment by notflip** [comment]
What was the issue? @Synida

**Comment by thelfensdrfer** [comment]
@notflip For me a `composer selfupdate` was enough.

**Comment by Matheo7** [comment]
ContextErrorException: Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\zScolarix\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php line 879

Your help please....
