### ISSUE TITLE
[HttpClient] Configure total timeout of request

### ISSUE THREAD

**Issue by pyrech** [symfony/symfony#32765]
**Symfony version(s) affected**: 4.3.x

**Description**  
Symfony's HTTP CURL Client supports a `timeout` option that will set the option `CURLOPT_CONNECTTIMEOUT_MS` of curl. This parameter only configures the timeout for the connect phase.

But in some use cases (like a crawler f.e) we need to limit the maximum time a request is allowed to take, not only the connect duration. This is what the curl options `CURLOPT_TIMEOUT` and `CURLOPT_TIMEOUT_MS` do.

Unless I'm wrong, there is no way to configure the curl client with some custom config. Is that really intended? If yes, how can we change this timeout behavior?

**How to reproduce**  
```php
$httpClient = new CurlHttpClient();
$httpClient->request('GET', 'http://example.com/a-page-that-takes-a-long-time-to-render',  [
    'timeout' => 1,
]);
```

**Possible Solution**  
Either add a way to override curl option or change the timeout behavior of the curl client

**Comment by nicolas-grekas** [comment]
Hi, that's intended yes: timeout is an *idle* timeout. Having a transfer timeout could be possible.

It's also possible to implement it in PHP using the stream function (checking the duration in the foreach loop)

Allowing to pass the curl option as is is no-go on my side: I'd really like the component to *not* leak the underlying implem. Said another way: we might add a new `transfer_timeout` option, but then it should be implemented by both curl and native clients.

Up for a PR?

**Comment by pyrech** [comment]
I do not have the time to give it a try at the moment, sorry

**Comment by fancyweb** [comment]
I'll have a look at it.

**Comment by fancyweb** [comment]
@nicolas-grekas curl `CURLOPT_TIMEOUT_MS` is actually a "max execution time" timeout. It includes the connection time. Shouldn't we use something like `total_timeout` for the new option name (since it's not only transfer time).
