### ISSUE TITLE
[RFC][DX] Subscribe on Event through Annotation

### ISSUE THREAD

**Issue by grachevko** [symfony/symfony#32779]
**Description**  
Introduce annotation for adding listeners to event dispatcher.

**Example**  
```php
/**
 * @Listen
 **/
public function onRequest(RequestEvent $event): void {}
```
```php
/**
 * @Listen(priority=2)
 **/
public function onRequest(RequestEvent $event): void {}
```
```php
use Symfony\Component\HttpKernel\Event\RequestEvent;
/**
 * @Listen(RequestEvent::class)
 **/
public function onRequest(KernelEvent $event): void {}
```

**Comment by garak** [comment]
Typo on all three "function" (copy & paste disaster, I guess)

**Comment by grachevko** [comment]
Before vote :-1: maybe anyone can explain his position?
What the principal difference between `@Route` and this?

Maybe symfony should add `RouteSubscriberInterface` to make possible define route in controller just like define subscribers through `EventSubscriberInterface`? Why not if you think it more convinient.

**Comment by Tobion** [comment]
The problem with annotating `@Listen(RequestEvent::class)` is that it does not provide autocomplete and discovery which is what we wanted to achieve with class-named events in the first place.

**Comment by grachevko** [comment]
Example with `@Listen(RequestEvent::class)` is mean how you can override event name if type hint is a parent class of a real event. I think it's rare case, especially in user code.
In string event we also don't have autocompletion, earlier it did not cause problems.

And, btw, in `@ORM\Entity(repositoryClass="")` autocomplete work well, why not it work in this? Short example `RequestEvent::class` is a just pseudo code for discuss.

**Comment by nicolas-grekas** [comment]
Without discussing the merit of using annotations for this, the root technical issue is that we wouldn't be able to discover which classes have the annotations of not.
Parsing the whole code base is not something we might consider.
And adding a labeling interface neither, as we already have `ServiceSubscriberInterface`.

**Comment by grachevko** [comment]
@nicolas-grekas yeap, I really missed this moment.

**Comment by fabpot** [comment]
Let's close for the reasons explained by @nicolas-grekas
