### ISSUE TITLE
LoggingTranslator->log missing id, domain, locale in message 

### ISSUE THREAD

**Issue by rharzer** [symfony/symfony#32780]
**Symfony Translator version(s) affected**: 4.3.2

**Description**  
i installed the packages symfony/translation and monolog/monolog. i want the translation component to give me a log-message about missing translations through monolog. 
after setting up monolog & loggingtranslator (both work as expected), i just tested the translation logging by adding a key to the template which cannot be translated. 
the loggingtranslator put a message to the debug.log file but i miss the id of the key.
after inspecting the loggertranslator, i found the problem: 

LoggingTranslator line 154:
`$this->logger->warning('Translation not found.', ['id' => $id, 'domain' => $domain, 'locale' => $catalogue->getLocale()]);`

the context of the message is set, but never used (or do i miss something?)
the solution of this problem couldn't be easier:

**Possible Solution**  
`$this->logger->warning('Translation not found: key: {id}, domain: {domain}, locale: {locale}.', ['id' => $id, 'domain' => $domain, 'locale' => $catalogue->getLocale()]);`

**Comment by dmaicher** [comment]
It depends how monolog is configured and which handlers you have active. The logging context can for sure be output to a log file with every record if that's what you want. So I don't think this needs fixing.

How does your monolog config look like? And how does such a log record look like after writing it to the logfile?

**Comment by rharzer** [comment]
this is my monolog config:

`if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r'));
        if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
        if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));
        $streamCommon = new StreamHandler($this->logCommon, LOGGER::INFO, false);
        $streamIssues = new StreamHandler($this->logIssues, LOGGER::ERROR, false);

        $processor = new PsrLogMessageProcessor();
        $streamCommon->pushProcessor($processor);
        $streamIssues->pushProcessor($processor);

        $dateFormat = "d-m-Y H:i:s";
        $formatter = new LineFormatter("[%datetime%] %level_name%: %message%".PHP_EOL, $dateFormat, true);
        $streamCommon->setFormatter($formatter);
        $streamIssues->setFormatter($formatter);

        $this->pushHandler($streamCommon);
        $this->pushHandler($streamIssues);
        if (APP_DEBUG) {
            $streamDebug = new StreamHandler($this->logDebug, LOGGER::DEBUG, false);
            $streamStdout = new StreamHandler(STDOUT, Logger::DEBUG);

            $streamDebug->pushProcessor($processor);
            $streamStdout->pushProcessor($processor);

            $streamDebug->setFormatter($formatter);
            $streamStdout->setFormatter($formatter);

            $this->pushHandler($streamDebug);
            $this->pushHandler($streamStdout);
        }`

example output: 
`[29-07-2019 14:12:19] WARNING: Translation not found.`

i'd appreciate if you could tell me what i need to change.

**Comment by dmaicher** [comment]
Can you try `new LineFormatter(null, $dateFormat, true);`?

There is a default/simple format which should include the context:

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L26

**Comment by rharzer** [comment]
yes, thank you. it fixes the problem. 
i dropped the %context%-part of the default-format-string, this is why i didn't get the context.
