### ISSUE TITLE
Seems like bug in 4.4 branch in LdapBindAuthenticationProvider service

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#32808]
**Symfony version(s) affected**: 4.4 branch

**Description**  
This commit introduces new parameters to LdapBindAuthenticationProvider

https://github.com/symfony/symfony/commit/cb2d97f92b37e097d58c81556c0f12ffc3ec97b8#commitcomment-34494186

But there is a bug in Security factories (JsonLoginLdapFactory, HttpBasicLdapFactory and JsonLoginLdapFactory).

```
->replaceArgument(5, $config['search_dn'])
->replaceArgument(6, $config['search_password'])
```
but actual LdapBindAuthenticationProvider arguments are

5 - $hideUserNotFoundExceptions = true
6 - $searchDn
7 - $searchPassword

See:
https://github.com/symfony/symfony/blob/cb2d97f92b37e097d58c81556c0f12ffc3ec97b8/src/Symfony/Component/Security/Core/Authentication/Provider/LdapBindAuthenticationProvider.php

**Possible Solution**  
Fix arguments

**Comment by Simperfit** [comment]
Thanks for the catch, this has not been seen when the review was done and I did not saw it !
see https://github.com/symfony/symfony/pull/32825

**Comment by zim32** [comment]
I thought, is it possible to do type checking while compiling container. F.e. add optional type specifier
->addArgument($config['name'], 'string')..
->replaceArgument(5, $config['search_dn'], string)...

and then do reflection and check parameters in cimpiler pass. It could prevent some bugs.
