### ISSUE TITLE
[HttpClient] Headers are lowercased

### ISSUE THREAD

**Issue by numerogeek** [symfony/symfony#32819]
Hello guys ! 

I'm submitting you the following issue: 

**Symfony version(s) affected**: 4.3.x

**Description**  
When I set some headers to a curl POST request, the keys are lowercased. This is a problem for some API's

```php
        $this->httpClient = HttpClient::create(['headers' => [
            'X-Apple-Header1' => 'someSecretKey',
            'X-Apple-Header2' => 'someSecretKey',
            'X-Apple-Header3' => 'someSecretKey',
            'Content-Type' => 'application/json',
            'Accept' => 'application/json',
        ]]);

```

And it's converted by HttpClient to : 

```
POST /api/endpoint/1 HTTP/1.1
   Host: api.apple.com
   Accept-Encoding: deflate, gzip
   x-apple-header1: someSecretKey
   x-apple-header2: someSecretKey
   x-apple-header3: someSecretKey
```

**Additional context**  
I'm using the Curl extension

thanks for helping !

**Comment by nicolas-grekas** [comment]
Hi, that's correct and expected;

**Comment by numerogeek** [comment]
Hi @nicolas-grekas 

thank you for your help ! 
I was digging into the [normalizeHeaders](https://github.com/symfony/http-client/blob/master/HttpClientTrait.php#L209) and I found out that it's indeed a feature 😄 

It's a problem for my use case: Apple is using some case sensitive headers to authenticate on a Business API. With lowercased headers, I get a 403 Forbidden, and with the 'normal' case I get a 200. 

Do you think that I can work on a workaround ? Like an option to avoid the lowercasing ?

**Comment by nicolas-grekas** [comment]
That's really bad.
HTTP defines headers as case insensitive.
And HTTP/2 enforces this by allowing only lower case headers.
We could normalize to camel case when writing the header...
PR welcome.

**Comment by numerogeek** [comment]
Just to be clear: I was thinking about an option like "lowercaseHeader" set to `true` by default, but when `false` is passed we just let the key that was set by the user. 
WDYT ?

**Comment by nicolas-grekas** [comment]
We shouldn't add an option for this. Instead, I'm proposing to add uppcase to first letters just before setting them to the transport layer.

**Comment by clemherreman** [comment]
How about removing normalization altogether, excepted in an HTTP 2 request. 

I feel normalizing, be it uppercase or ucfirst, does not bring value, especially given there are APIs that are not treating headers as case-insensitive.

**Comment by nicolas-grekas** [comment]
Normalization is critical for merges. Removing it would be wrong.

**Comment by nicolas-grekas** [comment]
Please check #32823, does it solve your issue?

**Comment by numerogeek** [comment]
I was going to do that tomorrow, but thank you for your PR.
I've just tested, I'm sorry, but it's not good for my specific use case. 
One of the header I need to pass is called `X-Device-ShipTo`. As you solution lowercase everything and then upcase the first word, it become `X-Device-Shipto` which throw me an error. 

I think the workaround would be to use the lowercase internally for the merges, but in the end, use the header setted in the options by the developer.

**Comment by nicolas-grekas** [comment]
Is there any public documentation for this API? I'd like to have a look please.

**Comment by numerogeek** [comment]
No public doc, but I've sent you a DM on twitter with some details.

**Comment by nicolas-grekas** [comment]
Patch in #32823 updated, better?

**Comment by numerogeek** [comment]
All good ! thank you @nicolas-grekas 😃
