### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#32813]
Core-team members can manage a list of issues each of them thinks would make Symfony move forward in a useful way. They are seeking help to close them all and are willing to help in return. Thanks in advance for anything you can do!

Please check https://github.com/orgs/symfony/projects/1 if you would like to contribute.

**Comment by Simperfit** [comment]
Nice !
This has been shared internally at @izisolutions so people can try to contribute and get some help.

**Comment by fabpot** [comment]
Let's close this issue as it will be lost in the sea of others.

**Comment by nicolas-grekas** [comment]
Not really :)

![image](https://user-images.githubusercontent.com/243674/62515834-b9ad0180-b823-11e9-83fd-c8f12c06b192.png)

**Comment by fabpot** [comment]
But we already have a project, seems like something redundant.
