### ISSUE TITLE
DataPart::fromPath can cause a notice

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony#32816]
**Symfony version(s) affected**: 4.3.3

**Description**  
This mime type definition [0] cause notice (Notice: Undefined offset: 1) here [1] because of this [2].
[0]
https://github.com/symfony/mime/blob/e543521a5566dc2be7b675f50500f4ed8feadc60/MimeTypes.php#L2439
[1]
https://github.com/symfony/mime/blob/c71b839cc39d446f14afaef771c16f221d85c331/Part/DataPart.php#L38
[2]
https://github.com/symfony/mime/blob/c71b839cc39d446f14afaef771c16f221d85c331/Part/DataPart.php#L56

The auto mime type detection pick ups the first mime type without slash and the explode function results in a 1 item length array.
You can send the mime type on the 3rd argument, but i don't think this is a best solution.
We should do a better error reporting at the explode function.

**How to reproduce**  
DataPart::fromPath('somefile.odt');

**Comment by rjwebdev** [comment]
Would like to work on this one. As how I see it, there are multiple solutions:

- Check if there's a slash in the content type. If there's one, keep using the existing code. If not, assign the given contentType variable to the subtype in the Datapart constructor
- Filter the array of given contentTypes until one's found with a slash character in it

Question: why are there multiple mimetypes defined for the odt extension?

**Comment by fabpot** [comment]
It looks like some content types are missing their `application/` prefix. @rjwebdev Can you. investigate why this is the case? If the content types are valid, let's fix them by adding the missing `application/`. If they are not, let's remove them.

**Comment by rjwebdev** [comment]
@fabpot On what conditions should I decide if the content types are valid or not? 

At first sight, it looks like only the open document extensions do have multimple mimetypes defined. Can I just remove the ones without slash or not?

**Comment by fabpot** [comment]
@rjwebdev Let's remove all content types that do not have the `application/` prefix.

**Comment by garak** [comment]
I just stumbled on this bug, and it looks like nothing has been done to prevent it.
Still now, there's an assumption that `[$this->mediaType, $subtype] = explode('/', $contentType);` will always produce two strings, and so `$subtype` is used even if it can be null (causing a critical error).

IMHO an additional check should be added, to ensure that `$subtype` is a string.

**Comment by stof** [comment]
@garak but a proper mime type should always have a `/` in it

**Comment by garak** [comment]
> @garak but a proper mime type should always have a `/` in it

It should, but there's no check here. If it's a constraint, it should be enforced.
