### ISSUE TITLE
Bug: Attempted to load interface "ResetInterface"

### ISSUE THREAD

**Issue by tabbi89** [symfony/symfony#32820]
**Symfony version(s) affected**: 4.3.3

**Description**  
!!
!!  Fatal error: Interface 'Symfony\Contracts\Service\ResetInterface' not found in /var/www/html/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php on line 20
!!

**composer.json output**
[output.txt](https://github.com/symfony/symfony/files/3448472/output.txt)

**Comment by chalasr** [comment]
Running `composer selfupdate` should help, see https://github.com/symfony/symfony/issues/32716.
