### ISSUE TITLE
Auto Password Encoder generate different passwords for fixtures

### ISSUE THREAD

**Issue by dabagab** [symfony/symfony#32822]
**Symfony version(s) affected**: 4.3.2

**Description**  
I use the recommended configuration for the password encoder. I changed the `argon2i` to `auto` because of `argon2i` marked as deprecated.
```
 encoders:
        # use your user class name here
        App\Entity\User:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: auto
```
In this case the encoded password will not work during the login process! (It will get invalid credentials error message)! The encoded `password` will not valid during login!

**How to reproduce**  
Use the configuration with `algorithm: auto` and then just call this line:
```
 $user->setPassword($this->passwordEncoder->encodePassword($user, 'password'));
```
where the `passwordEncoder` is `UserPasswordEncoderInterface`

**Possible Solution**  
It is easy, I had to change `auto` value to `argon2i` or `bycript` so this is the solution. It must not use the `auto` for fixtures!

**Additional context**

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce your issue?

**Comment by nicolas-grekas** [comment]
Maybe unrelated to the reported issue, but using crypto-resistant for testing is maybe a bad idea: they're slow by design. We should recommend setting the hashing costs to the minimum. Can e do this in a recipe?

**Comment by xabbuh** [comment]
@dabagab Did you manage to create an example that allows us to reproduce?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
