### ISSUE TITLE
Symfony framework always using system php, cannot change to homebrew installed version

### ISSUE THREAD

**Issue by TangMonk** [symfony/symfony#32830]
**Symfony version(s) affected**: 4.3.3

**Description**  
I am in macOS 10.14, it default php is 7.1, I am use homebrew to installed the 7.3 version on my mac, and php7.3 is works fine in my terminal, it is my default php version in terminal now, however when I using symfony framework with `symfony server:start`, it still use the 7.1 as the default version, seems it force choice /usr/sbin/ as the php directory

my local environment :
```
$php -v
PHP 7.3.7 (cli) (built: Jul  5 2019 12:44:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies

$php-fpm -v
PHP 7.3.7 (fpm-fcgi) (built: Jul  5 2019 12:44:11)
```

message when I run `$ symfony server:start`:

```
$symfony server:start
Jul 31 20:32:21 |DEBUG| PHP    Using PHP version 7.1.23 (from default version in $PATH)
Jul 31 20:32:21 |INFO | PHP    listening path="/usr/sbin/php-fpm" php="7.1.23" port=63720
Jul 31 20:32:21 |DEBUG| PHP    started
Jul 31 20:32:22 |INFO | PHP    'user' directive is ignored when FPM is not running as root
Jul 31 20:32:22 |INFO | PHP    'group' directive is ignored when FPM is not running as root
Jul 31 20:32:22 |INFO | PHP    fpm is running, pid 38105
Jul 31 20:32:22 |INFO | PHP    ready to handle connections

 [OK] Web server listening on http://127.0.0.1:8000 (PHP FPM 7.1.23)

```

the message shows it using `/usr/sbin/php-fpm` as default php fpm, So i am try to remove it with`sudo rm /usr/sbin/php-fpm``, but it error down:

```
Jul 31 20:33:54 |DEBUG| PHP    Using PHP version 7.1.23 (from default version in $PATH)
Jul 31 20:33:54 |INFO | PHP    listening path="/usr/sbin/php-fpm" php="7.1.23" port=64106
Jul 31 20:33:54 |INFO | SERVER shut down, bye!

  fork/exec /usr/sbin/php-fpm: no such file or directory

Error reported as #2fcaf45f8bef41f7b69384d73ddf53d7
```

actually I have the php-fpm 7.3 in /usr/local/sbin/php-fpm PATH, but symfony turn a blind eye, symfony ignore the path.

And i try to copy /usr/local/sbin/php-fpm to /usr/sbin/php-fpm, but the message show still using 7.1

**How to reproduce**  
mac10.14 and brew install the latest php

**Comment by TangMonk** [comment]
Now it using php 7.3, but the terminal still shows me 7.1

picture in web console:
![image](https://user-images.githubusercontent.com/3498786/62215319-4f3a3280-b3d9-11e9-875e-55123e89614f.png)

picture in terminal:
![image](https://user-images.githubusercontent.com/3498786/62215347-5f521200-b3d9-11e9-9967-be26ea45a518.png)

**Comment by TangMonk** [comment]
using .php-version to fix that

**Comment by andrewnclark** [comment]
Having had a quick look through the source code I think you can add `PHP_BINARY=/usr/local/sbin/php` to change the default. I've not been able to check it properly though I'm afraid.
