### ISSUE TITLE
Sodium password encoder doesn't fall back to password_hash()

### ISSUE THREAD

**Issue by BenMorel** [symfony/symfony#32834]
**Symfony version(s) affected**: 4.3.3

# Background

*Although the [PHP doc](https://www.php.net/manual/en/sodium.installation.php) says that "as of PHP 7.2.0 the sodium extension is bundled with PHP", it is actually an optional dependency on Fedora 30, where one has to install the `php-sodium` package to get it.*

*Nevertheless, even without the extension installed, `password_hash()` **does** accept `PASSWORD_ARGON2I` on PHP 7.2+ and `PASSWORD_ARGON2ID` on PHP 7.3+.*

# Issue

`SodiumPasswordEncoder` does not currently have a fallback on `password_hash()`, and only attempts to use libsodium directly through `sodium_crypto_pwhash_str()` and `Sodium\crypto_pwhash_str()`.

The result is an exception when I attempt to use `algorithm: sodium` on a fresh PHP 7.3 installation on Fedora:

> Libsodium is not available. Install the sodium extension or use "auto" instead.

Switching to `algorithm: auto` does generate `argon2id` hashes, so this one is OK.

But currently `algorithm: sodium` does not work on all PHP 7.2+ installations, although it could.

Before I submit a PR, **is there any reason why `algorithm: sodium` does not have a fallback on `password_hash()` as well?**

**Comment by ro0NL** [comment]
i believe the rationale is to have independent password encoders, composed at the configuration level.

`password_hash` is implemented in `NativePasswordEncoder` and picks the best algorithm by default, so `algorithm: native` is what you need right?

**Comment by nicolas-grekas** [comment]
The configuration key targets the implementation, not the algorithm. "auto" is the way to go.

**Comment by BenMorel** [comment]
I guess this makes sense, although this is not what I understood when I read the docs.

At first glance, `auto` does not make me confident that I'll get an argon2 encoder under the hood when deploying. I hoped `sodium` would give me the guarantee that argon2 *encoding* would be used, whatever the *library* used, or I'd get an exception if not available.

**Comment by nicolas-grekas** [comment]
Could you please have a look at a PR to improve the doc maybe?
Meanwhile, I'm closing here as there's no bug. 
Thanks for reporting.
