### ISSUE TITLE
OutputInterface is missing section() definition

### ISSUE THREAD

**Issue by LeanderFS** [symfony/symfony#32855]
**Symfony version(s) affected**: 4.*

**Description**  
OutputInterface is missing the section definition, therefore IDE's incorrectly mark section() as undefined and automated tests fail when using OutputInterface in a console command.

**How to reproduce**  
Create a new `Command` and typehint the `execute` method with `InputInterface $input, OutputInterface $output` (As per documentation). 

Add a new section to the `execute` method with `$output->section()`.

**Possible Solution**  
Either implement the definition for `section()` inside `OutputInterface`, which will cause BC breaks. Or add `@method ConsoleSectionOutput section() Creates a new output section.` to the class' phpdoc.

**Comment by chalasr** [comment]
Not all `OutputInterface` implementations can implement `section()`, you need a `ConsoleOutputInterface` instance for using it:
https://github.com/symfony/symfony/blob/20adf46a2cd3a611a131ca176820e7e7732ee4e1/src/Symfony/Component/Console/Output/ConsoleOutputInterface.php#L20
We know it's a bit unfortunate, but you need an `instanceof` check before using it.

**Comment by chalasr** [comment]
Closing as explained.
