### ISSUE TITLE
Xdebug enabled but profiler configuration page shows not 

### ISSUE THREAD

**Issue by TangMonk** [symfony/symfony#32863]
**Symfony version(s) affected**: 4.3.3

**Description**  
in phpinfo() page:

![image](https://user-images.githubusercontent.com/3498786/62290327-b4525e80-b493-11e9-93d1-36068c31ffa4.png)

 profiler configuration page:

![image](https://user-images.githubusercontent.com/3498786/62290411-e6fc5700-b493-11e9-902d-ab54a0f2bc28.png)

Is it the problem of symfony using php-fpm as develop server?

**Comment by xabbuh** [comment]
Is the `phpinfo()` screenshot from the same page that you see when you follow the "View full PHP configuration" link in the profiler?

**Comment by TangMonk** [comment]
@xabbuh  yes!

**Comment by TangMonk** [comment]
I remove the cache it works
```
./bin/console cache:clear
```
![image](https://user-images.githubusercontent.com/3498786/62293233-b0760a80-b49a-11e9-8db7-de25602b6c62.png)

**Comment by javiereguiluz** [comment]
I'm closing this issue as "fixed" because it looks like it worked as expected after clearing the cache. If the problem still persists, please tell us and we'll reopen. Thanks!

**Comment by TangMonk** [comment]
thanks!
