### ISSUE TITLE
Exception on cache:clear from TwigBundle Cache Warmer

### ISSUE THREAD

**Issue by stevro** [symfony/symfony#32860]
**Symfony version(s) affected**: 4.4.0-DEV

**Description**  
Exception during cache warmup thrown from TwigBundle

**How to reproduce**  
Install Symfony 4.4.0-DEV and run cache:clear on DEV environment.

**Additional context**  

 php.CRITICAL: Argument 1 passed to php.CRITICAL: Argument 1 passed to Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer::findTemplatesInFolder() must be of the type string, null given, called in /home/vagrant/code/intima_admin/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheCacheWarmer.php on line 71 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Symfony\\Bundle\\TwigBundle\\CacheWarmer\\TemplateCacheCacheWarmer::findTemplatesInFolder() must be of the type string, null given, called in /home/vagrant/code/intima_admin/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheCacheWarmer.php on line 71 at /home/vagrant/code/intima_admin/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheCacheWarmer.php:108)"}

TwigBundle version from composer.lock:
"name": "symfony/twig-bundle",
            "version": "4.4.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/twig-bundle.git",
                "reference": "8eb2f661a5ef0dd00bfd66043040db30d6e0a03b"
            },

**Comment by yceruto** [comment]
Fixed in https://github.com/symfony/symfony/pull/32867
