### ISSUE TITLE
[PHPUnit-Bridge] DeprecationErrorHandler incompatibility with PHPUnit 8.3

### ISSUE THREAD

**Issue by TomBerriot** [symfony/symfony#32879]
**Symfony version(s) affected**: 4.3

**Description**  
https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-8.3.md
Since PHPUnit 8.3, PHPUnit\Util\ErrorHandler::handleError() is not available anymore.

DeprecationErrorHandler.php relied on this method in DeprecationErrorHandler::handleError().

**How to reproduce**  
This error is triggered by executing `is_array($env = @include dirname(__DIR__) . '/.env.local.php')` in our `bootstrap.php` file when it is included by `FiledLoader`, when launching our tests with PHPUnit.

**Comment by karser** [comment]
I'm also getting `Call to undefined method PHPUnit\Util\ErrorHandler::handleError()#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError` after updating to phpunit 8.3

**Comment by nicolas-grekas** [comment]
Can someone please investigate and figure out a patch to fix the issue?

**Comment by karser** [comment]
The PHPUnit method  [handleError](https://github.com/sebastianbergmann/phpunit/blob/8.2.5/src/Util/ErrorHandler.php#L38) was renamed to [__invoike](https://github.com/sebastianbergmann/phpunit/blob/8.3/src/Util/ErrorHandler.php#L71) in v8.3

So we should check in Symfony [DeprecationErrorHandler](https://github.com/symfony/symfony/blob/v4.3.3/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L78) if method `handleError` exists, otherwise call `__invoke`

**Comment by karser** [comment]
Looking into it now

**Comment by karser** [comment]
Test my branch, please https://github.com/karser/symfony/tree/phpunit83-errorhandler-fix

**Comment by AymDev** [comment]
I'm still having this issue. Upgrading to **Symfony 4.3.3** fixed it for local work but it fails in CI.

As I understood, **phpunit-bridge** installs a **PHPUnit** project inside `bin/.phpunit`. Locally, it uses the one I have for a moment. As I added this directory to the `.gitignore`, it installs during CI.
The error appears during the **phpunit**'s dependencies installation:
```
$ docker exec app bin/phpunit
#!/usr/bin/env php
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing phpunit/phpunit (8.3.3)
Plugins have been disabled.
  - Installing phpunit/phpunit (8.3.3): Downloading (100%)
Created project in phpunit-8
Do not run Composer as root/super user! See https://getcomposer.org/root for details
composer.json has been updated
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Package operations: 29 installs, 0 updates, 0 removals
  - Installing myclabs/deep-copy (1.9.1): Downloading (100%)
  - Installing phar-io/version (2.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.3): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing doctrine/instantiator (1.2.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing sebastian/diff (3.0.2): Downloading (100%)
  - Installing sebastian/comparator (3.0.2): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.12.0): Downloading (100%)
  - Installing webmozart/assert (1.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.3.1): Downloading (100%)
  - Installing phpspec/prophecy (1.8.1): Downloading (100%)
  - Installing theseer/tokenizer (1.1.3): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (4.2.2): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-token-stream (3.1.0): Downloading (100%)
  - Installing phpunit/php-file-iterator (2.0.2): Downloading (100%)
  - Installing phpunit/php-code-coverage (7.0.7): Downloading (100%)
  - Installing phpunit/php-timer (2.1.2): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/global-state (3.0.0): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/resource-operations (2.0.1): Downloading (100%)
  - Installing sebastian/type (1.1.3): Downloading (100%)
  - Installing symfony/phpunit-bridge (dev-master): Symlinking from /var/www/html/vendor/symfony/phpunit-bridge
Writing lock file
Generating optimized autoload files
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit\Util\ErrorHandler::handleError() in /var/www/html/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:127
Stack trace:
#0 /var/www/html/config/bootstrap.php(9): Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(2, 'include(/var/ww...', '/var/www/html/c...', 9, Array)
#1 /var/www/html/config/bootstrap.php(9): include()
#2 /var/www/html/bin/.phpunit/phpunit-8/src/Util/FileLoader.php(59): include_once('/var/www/html/c...')
#3 /var/www/html/bin/.phpunit/phpunit-8/src/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load('/var/www/html/c...')
#4 /var/www/html/bin/.phpunit/phpunit-8/src/TextUI/Command.php(1074): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/html/c...')
#5 /var/www/html/bin/.phpunit/phpunit-8/src/TextUI/Command.php(868): PHPUnit\TextUI\Command->handleBootstrap('/var/www/html/c...')
#6 /var/www/html/bin/.phpunit/phpunit-8/src/TextUI/Command.php(168): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /var/www/html/bin/.phpunit/phpunit in /var/www/html/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php on line 127
```

I see it installs **phpunit-bridge** with `dev-master` version. Is it correct ?
Should the `bin/.phpunit` directory be removed from the `.gitignore` ? That's what I'll do for now.

**Comment by nicolas-grekas** [comment]
This is what L127 looks like in master:
https://github.com/symfony/symfony/blob/d65189fb811f6301e33bcf54d4a224afbfffeafd/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L127

You must have a different version of the bridge.

**Comment by nicolas-grekas** [comment]
You must have v4.3.3:
https://github.com/symfony/symfony/blob/v4.3.3/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L127

**Comment by AymDev** [comment]
You are right, I had **v4.3.3** in the main dependencies. Using **dev-master** for now. I guess the fix will be available in the next patch version. Thanks again.
