### ISSUE TITLE
Unrecognized option "entity" under "security.providers.app_user_provider"

### ISSUE THREAD

**Issue by ElvaRivle** [symfony/symfony#32881]
**Symfony version(s) affected**: 4.3.3

**Description**  
After php bin/console make:user this problem arises: << In ArrayNode.php line 331 (normalizeValue): Unrecognized option "entity" under "security.providers.app_user_provider". Available options are "chain", "id", "ldap", "memory".   >>

**How to reproduce**  
After simple installations of doctrine, security-bundle, orm-pack, twig, maker-bundle, running php bin/console make:user creates all files and updates security.yaml successfully, but the problem arises. Followed https://symfony.com/doc/current/security.html but can't move past Creating User class
PHP version: 7.3.7

**Comment by ElvaRivle** [comment]
Managed to "fix" this issue by creating custom user provider: https://symfony.com/doc/current/security/user_provider.html#creating-a-custom-user-provider and modifying security.yaml: 
app_user_provider:
    #entity:
    #    class: App\Entity\User
    #    property: email
    id: App\Security\UserProvider

For some reason src/Security folder is never created with make:user even though docs say that it is: "If you used the make:user command to create your User class (and you answered the questions indicating that you need a custom user provider), that command will generate a nice skeleton to get you started: src/Security/UserProvider.php". I don't understand why default entity provider doesn't work. Error looks like entity provider isn't even implemented in Symfony.

**Comment by xabbuh** [comment]
Could you create a small example application that allows to reproduce the initial issue?

**Comment by ElvaRivle** [comment]
To be honest, I have no idea how to create simple application to show you the error. All I can tell you that make:user command succeeds, creates Entity/User.php and modifies security.yaml, but in security.yaml, under providers option entity provider is used. That entity provider from security.yaml is causing this issue

**Comment by ElvaRivle** [comment]
@xabbuh To be honest, I have no idea how to create simple application to show you the error. All I can tell you that make:user command succeeds, creates Entity/User.php and modifies security.yaml, but in security.yaml, under providers option entity provider is used. That entity provider from security.yaml is causing this issue.

Just figured out, maybe I can create my repo with exact code that creates exact issue. Will post link here

**Comment by ElvaRivle** [comment]
By all means I cannot recreate problem. After installing twig, doctrine, security and maker-bundle on clean skeleton project, problem disappeared. make:user and make:auth work flawlessly. Closing issue, but if I find initial reason for this issue I will post it here.

**Comment by forsetius** [comment]
I had the sama situation with Symfony 5.0 and PHP 7.4. At first Symfony returned exactly the same error. Then after another revert and reinstall every bundle it started to work. Baffling. 

Anyway, I can confirm the issue doesn't exist when you: 
1. start from git commit with clean Symfony installation (I created branches and installed various bundles in them, then switched, deleted and so forth before returning to "safe" state) 
2. clean the cache (`var/` is out of git so changes are not tracked, when you revert its content persists)
3. delete everything from `vendor/` and re-install it (`vendor/` is out of git too)
4. install maker, orm and security - I did it in that order, but I don't think it matters. Twig is not required

**Comment by rayrigam** [comment]
I have this issue as well. Although it may be due to me using Propel rather than Doctrine? I was trying to use the entity provider rather than using my own custom provider, but was not able to due to this error. I'm guessing entity provider only works if you use Doctrine to generate the base User class, and if you have the User class under the Entity folder?

**Comment by andrconstruction** [comment]
Problem still here. I try to update via composer and get error


Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 319:
!!  

!!    Unrecognized option "entity" under "security.providers.users". Available o
p
!!    tions are "chain", "id", "ldap", "lexik_jwt", "memory".



yaml:
 providers:
    users:
      entity:
        class: App\Entity\User
        property: username

**Comment by andrconstruction** [comment]
The Problem was in a missing doctrine orm pack. If it will help sombody

**Comment by jersoe** [comment]
> The Problem was in a missing doctrine orm pack. If it will help sombody

It helped me. I had another issue and removed doctrine. Then I got this error. 

`composer require doctrine`

fixed it. Thanks!

**Comment by hjardines** [comment]
Just add this pack. 

1. Add this to composer.  "symfony/orm-pack": "^1.0.8",
2. Delete composer.lock, var/cache 
3. composer install.

Enjoy!
