### ISSUE TITLE
[Messenger] durable delay exchange and queues

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#32891]
**Symfony version(s) affected**: 4.3

**Description**  
The default for normal exchanges and queues is AMQP_DURABLE, see https://github.com/symfony/symfony/blob/215ba8a47ca63bc936772adf8fbec2b9e6ebe839/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L84
But the delay exchange and queues are not created as durable by default. This is inconsistent and problematic because delayed messages are can stay for long the in queue. So when the server restarts those delayed messages are lost. For this reason it would also make sense to send messages to the delay exchange by default with delivery_mode=persistent.

**Comment by dbu** [comment]
if i understand rabbitmq correctly, i think there would be a problem with durable message exchanges: a temporary exchange stops existing when it has no messages in it anymore. a durable one would stay forever even when empty. we would then need some sort of cron command to cleanup empty durable delay exchanges... or am i missing something?

if that is the case, i think it could be a config option to make the delay exchanges durable and offer a cleanup command to be run by a cron job.

**Comment by Tobion** [comment]
@dbu you must have misunderstood something. exchanges have no messages in them. that's what queues are for. so there is no such thing as an "empty exchange". and non-durable queues are not temporary and get auto-deleted. I don't know where you have that info from.

**Comment by dbu** [comment]
i had been reading this: https://www.cloudamqp.com/blog/2015-09-03-part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html

so if i get your right, that would mean if the exchange is auto-delete and the queue temporary, the exchange would go away as soon as the last message has been consumed? that would still leave us with the problem that we spam rabbitmq with durable exchanges and queues that stay around. (at least when the user adds variable delays to messages)

**Comment by Tobion** [comment]
See #33127. Persistent delivery_mode of the messages can be set in user-land using the AmqpStamp. We don't necessarily need to make this the default or add an option in SF.
We already have a decorator for the amqp transport to add custom headers etc. It's easy to also make all the messages persistent this way.
