### ISSUE TITLE
[Event-dispatcher] Reimplement LegacyEventDispatcherProxy and don't deprecated it

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#32926]
**Description**  
For project supporting both `Symfony2` (?) `Symfony3`, `Symfony4`, and soon `Symfony5`, there is an issue with the `dispatch` function definition.

```
$this->eventDispatcher->dispatch($eventName, $event);
```
Works for `Symfony3` and `Symfony4` but returns deprecation in `Symfony4` (and I think won't work in `Symfony5`).

```
$this->eventDispatcher->dispatch($event, $eventName);
```
Works for `Symfony4` and `Symfony5` but don't work for `Symfony3`.

**Example**  
```
$dispatcher = LegacyEventDispatcherProxy::decorate($this->eventDispatcher);
$dispatcher->dispatch($event, $eventName);
```

Would be the solution.

You did it.
You used it.
Don't removed it, please.

**Comment by VincentLanglet** [comment]
That's a stupid suggestion.
The LegacyEventDispatcherProxy won't exist in older symfony version...

**Comment by xabbuh** [comment]
@VincentLanglet If I don't misunderstand what you are trying to solve, checking if the dispatcher implements the `EventDispatcherInterface` from the contracts looks like a cleaner solution to decide whether to use the old or the new signature.

**Comment by VincentLanglet** [comment]
@xabbuh 
But since the class `Symfony\Contracts\EventDispatcher\EventDispatcherInterface` does not exist in `symfony2` and `symfony3`, I will get an error if I try to use it, no ?

Could you give me the sample of code you have in mind ? Thank you
