### ISSUE TITLE
Nested FormType submitButton propagation

### ISSUE THREAD

**Issue by Romaxx** [symfony/symfony#32932]
**Symfony version(s) affected**: 4.3

**Description**  
CustomFormType composed of:
- a nested CustomFormType named "sub"
- a search Field SearchType named "search"
- a submit button named "searchbtn"

Top Level CustomFormType
-| searchfield: SearchType
-| searchbtn: SubmitType
-| sub: CustomFormType Level 2
--| -searchfield: SearchType
--| -searchbtn: SubmitType
--| -sub: CustomFormType Level 3
----| -searchfield: SearchType
----| -searchbtn: SubmitType
----| -sub: ...

When submit Form using the top-level searchbtn button, Top level Form contain clickedButton=searchbtn, but level 2 and 3 Form (nested sub) contain clickedButton=searchbtn too

**Additional context**  
POST data are:
CustomFormType[searchfield]: mysearchtoplevel
CustomFormType[searchbtn]:

but bug do as if POST data was:
CustomFormType[searchfield]: mysearchtoplevel
CustomFormType[searchbtn]:
CustomFormType[sub][searchbtn]:
CustomFormType[sub][sub][searchbtn]:

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Romaxx** [comment]
oh I've found the problem in getClickedButton():758
clickedbutton child is override by parent button..
it's not a name issue
`if ($this->parent && method_exists($this->parent, 'getClickedButton')) {
            return $this->parent->getClickedButton();
        }`
why we override clickedbutton of child by parent clickedbutton ?
Imagine you have subform with button (ButtonType are not handled by clickedbutton, so SubmitType is necessary used)

**Comment by xabbuh** [comment]
I am sorry, but I still do not understand the issue you have. Can you please create a small example application and explain what you expected and what happened instead?

**Comment by Romaxx** [comment]
here a simple exemple of the problem
https://github.com/Romaxx/etc-issues-SFSubmitType

**Comment by xabbuh** [comment]
Thank you for the example. I think I understand now what you are trying to achieve. I think you could solve what you are trying to solve by not comparing the name, but by checking for the concrete instance instead like this:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('searchfield', SearchType::class, array(
        'required' => true
    ));
    $submitButton = $builder->create('searchbutton',SubmitType::class,array(
        'label'=>'Search'
    ));
    $builder->add($submitButton);

    $builder->addEventListener(
        FormEvents::SUBMIT,
        function (FormEvent $event) use ($options, $submitButton) {
            $form = $event->getForm();
            if ($submitButton === $form->getClickedButton()){
                // do whatever is necessary
            }
        }
    );
}
```

**Comment by Romaxx** [comment]
@xabbuh I have tested your solution but it's not working, $form->getClickedButton contain sub form submitButton, it replace the main submitButton during submitting.

**Comment by xabbuh** [comment]
Ah sorry, the `$submitButton` in my example above is not a button but still a builder instance. But the following works:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('searchfield', SearchType::class, array(
        'required' => true
    ));
    $builder->add('searchbutton',SubmitType::class,array(
        'label'=>'Search'
    ));
    $builder->add('sub',Custom2FormType::class, array(
        'label' => 'subsearch',
    ));
    $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
            $form = $event->getForm();

            if ($form->getClickedButton() === $form->get('searchbutton')){
                // button is clicked
            }
        }
    );
}
```

**Comment by Romaxx** [comment]
Good it's working now.
I have created a PR in documentation
https://github.com/symfony/symfony-docs/pull/12089
