### ISSUE TITLE
[RFC][ErrorHandler] Add a simple error handler for the userland

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#32936]
Now that we have a separate component named `ErrorHandler`, I have an idea.

It's quite common to do this in the userland code:

```php
$handle = @fopen('file.txt', 'rb');

if (false === $handle) {
    throw new FileNotFoundException();
}
```

I think it would be nice to have a DSL for better handling of such cases:

```php
$handle = errorHandler()
    ->try(static function() {
        return fopen('file.txt', 'rb');
    })
    // or ->try('fopen', 'file.txt', 'rb')
    ->catchWarning(static function(string $message) {
        throw new FileNotFoundException();
    })
    // ->catchNotice()
;
```

Or with some reusability options:

```php
$fopen = errorHandler('fopen')
    ->catchWarning(static function(string $message) {
        throw new FileNotFoundException();
    })
;

$fopen('file.txt', 'rb');
$fopen('another.xml', 'wb');
```

This mechanism could replace error handling in the `Filesystem` and other components across the framework.

@yceruto , WDYT?

**Comment by linaori** [comment]
Not exactly sure about the exact DSL, but I really like the idea behind it! Additionally, would it be possible to provide more information to `catchWarning` depending on the error received using [error_get_last()](https://www.php.net/manual/en/function.error-get-last.php)?

This would provide a nice toolkit for specialized scripts or even vendor packages that want to provide more accurate error handling without messing around with error handlers manually.

**Comment by javiereguiluz** [comment]
I don't understand why the "after" is better than the "before". It has many more lines of code and looks less readable to me. What do we gain from the "after" code?

**Comment by linaori** [comment]
@javiereguiluz I believe @vudaltsov was referring to code like this, where the error handler can be (temporarily) replaced: https://github.com/symfony/symfony/blob/3e523ddd512986ab324334ac2e7a748b966e364a/src/Symfony/Component/Filesystem/Filesystem.php#L745-L759

**Comment by vudaltsov** [comment]
@linaori , I like using `set_error_handler` / `resore_error_handler` a bit more. The `set_error_handler` accepts a callable which then gets `int $level, string $message, string $file, int $line`, [see](https://github.com/vudaltsov/exceptionally/blob/b99514c1a663fb4b4bc594b8d167ee5a242ba016/src/Exceptionally.php#L103).

@javiereguiluz , I actually started playing with this a couple of days ago when I needed to `fopen` and `flock` files a lot. I could not use `Filesystem` because the logic was much more complicated. So I quickly realized that I need a uniformed mechanism of handling the annoying PHP errors. I drafted a package which you can use already: https://github.com/vudaltsov/exceptionally.

But now I think this might fit well the new ErrorHandler component.

**Comment by vudaltsov** [comment]
My package currently does not support convenient "catch" callbacks for different error levels, it just throws subclasses of the [`ErrorException](https://www.php.net/manual/en/class.errorexception.php) designed exactly for this case, btw. So in case you need custom exception class, you have to try-catch yourself. That's why I propose a different DSL here. 

But that's debatable, of course. @linaori , how do you see that? Why don't you like the proposed one?

**Comment by linaori** [comment]
You could also do something like this in general:

```php
try {
    $handle = box(static function () use ($file) {
        return fopen($file, 'rb+');
    });
} catch (SomeException $e) {
    throw new SomeOtherException($e);
}
```

One minor problem that I see, is that it's really hard to properly box all exceptions and properly handle them all correctly. It does feel more of a hack around the lack of exceptions and error handling in php though. 

With a more explicit example:
```php
try {
    box(static function () use ($file, $dataIterator) {
        $handle = fopen($file, 'rb+');
        foreach ($dataIterator as $row) {
            fputcsv($handle, $row);
        }
        fclose($handle);
    });
} catch (SomeException $e) {
    throw new SomeOtherException($e);
}
```
It would need some proper "guessing" on which function was triggered and what the possible error was. I would really like if it were possible for the boxing to detect "oh the error was on `fclose()` because the handle was already closed", with special exceptions per case.

These are going to be a boatload of specialized edge-cases, but would be really awesome to have as a sort of generic "polyfill", if this is even possible.

**Comment by nicolas-grekas** [comment]
Nice idea, there is my proposal:

It allows also `ErrorHandler::box('fopen', '/some/file', 'r');`, which saves the closure around (but the closure wrapper is also possible, while less strict)


```php
class ErrorHandler
{
    // [...]

    /**
     * Calls a function and turns any PHP warnings into \ErrorException
     *
     * @return mixed Return $function(...$arguments)
     */
    public static function box(callable $function, ...$arguments)
    {
        set_error_handler(function (int $type, string $message, string $file, int $line) {
            if (__FILE__ === $file) {
                $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3);
                $file = $trace[2]['file'] ?? $file;
                $line = $trace[2]['line'] ?? $line;
            }

            throw new \ErrorException($message, 0, $type, $file, $line);
        });

        try {
            return $function(...$arguments);
        } finally {
            restore_error_handler();
        }
    }

    // [...]
}
```

**Comment by vudaltsov** [comment]
@nicolas-grekas , exactly how it works in the package I referenced!

**Comment by vudaltsov** [comment]
Except that my package allows some opt-in tuning as well. But that's probably not needed in fact.

**Comment by vudaltsov** [comment]
May I do a PR on this? Should it be a part of the `ErrorHandler` class? 
`ErrorHandler` is really a huge piece of code now, feels like it's not the best place for the `box`...

**Comment by nicolas-grekas** [comment]
Please proceed with a PR yes (with tests) :)

> Should it be a part of the ErrorHandler class?

that would ease discovery, don't you think?

**Comment by nicolas-grekas** [comment]
This is a complete alternative to https://github.com/thecodingmachine/safe btw, nice :)

**Comment by linaori** [comment]
One concern I have, is the function inspection, as we lose all information about `fopen`. What's the recommended way for this?

**Comment by nicolas-grekas** [comment]
> we lose all information about fopen. What's the recommended way for this?

I don't know if would recommend it, but this would work:
`ErrorHandler::call(function () { return fopen('/some/file', 'r'); });`

**Comment by nicolas-grekas** [comment]
On PHP 7.4 :)
`ErrorHandler::call(fn () => fopen('/some/file', 'r'));`

**Comment by Tobion** [comment]
I wish php 8 would not return false on failure anymore. Similar to https://wiki.php.net/rfc/consistent_type_errors but that one is only for parameter error unfortunately.
