### ISSUE TITLE
[DI] Configuring services via "configurator" does not report circular dependencies

### ISSUE THREAD

**Issue by kamilwylegala** [symfony/symfony#32959]
**Symfony version(s) affected**: 4.3.3

**Description**  
Using configurator mechanism to "configure" services in container does not report problems with circular dependencies. 

**How to reproduce**  
I describe this problem in repository: https://github.com/kamilwylegala/symfony-configurator-circular-dependency

Code from repository above contains the same "feature" achieved via factory and configurator. Factory way throws fatal error, configurator is causing infinite loop.

**Additional context**  
I described this behavior in [stackoverflow](https://stackoverflow.com/questions/57099988/symfony-dependency-injection-maximum-function-nesting-level) question.

**Comment by pierredup** [comment]
@kamilwylegala In your example repository, there is no circular reference. I think the issue you are experiencing is due to the entity and the validator causing an infinite loop because it references each other.

```

// Entity::validate() calls EntityValidator::validate() which calls  Entity::validate() etc

class Entity {
    public function validate() {
        $this->validator->validate();
    }
}

class EntityValidator {
    public function validate(){
        $this->entity->validate();
    }
}
```

If you remove one of those calls (E.g removing `$this->entity->validate();` from the `EntityValidator`), then you won't get the infinite loop

**Comment by nicolas-grekas** [comment]
Closing as explained, @pierredup is right.

**Comment by kamilwylegala** [comment]
@pierredup Thanks for response! I'll need to improve my example. 

But on the other hand dependencies graph looks following:

**Factory:**
```
Entity -> EntityFactory -> EntityValidator -> Entity -> ...
```
It throws fatal error about circular dependency.

**Configurator:**
```
Entity -> EntityConfigurator -> EntityValidator -> Entity
```
The latter `Entity` is not configured in that case? Tha'ts why circular dependency is not reported?

As I mentioned before I will need to improve my example and model better situation from SO question with `APP_ENV=test`.
