### ISSUE TITLE
[Security] [Feature] Introduce firewall names in the Security class

### ISSUE THREAD

**Issue by Arman-Hosseini** [symfony/symfony#32967]
Hello to all Symfony lovers.

I have 3 firewalls in my project for different users and tonight I noticed that the username I enter in the admin login form also appears in the user login form.
I noticed that the security class does not use the current firewall name for last username (that the user sent the request) into the following constants:

    const LAST_USERNAME = '_security.last_username';

Tell me if there is a way. Otherwise let me submit a pull request.
Thanks.

**Comment by Arman-Hosseini** [comment]
@fabpot Please review this.
Thanks.

**Comment by Arman-Hosseini** [comment]
@javiereguiluz  Please check this issues. Thank You.

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas Please review and comment on this issue. thank you.

**Comment by nicolas-grekas** [comment]
I don't know sorry, but please check the code and send a PR if you spot if/how this should be improved.

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas I reviewed it but it has many dependencies.

**Comment by Arman-Hosseini** [comment]
@weaverryan  Can you look into the matter and comment on it? Thank you.

**Comment by wouterj** [comment]
Feel free to start a pull request changing this. I don't know the full code behind this/all implications, but from a usage point of view I think it makes sense to change this (even a not-working small PR showing the main idea is a good start for discussion).

**Comment by chalasr** [comment]
I'm not sure to be aware of the full DX impact and BC considerations for this change.
So, as said, please feel free to start a PR so we can discuss the implementation.
Closing as the discussion seems to be staling now.
