### ISSUE TITLE
[Mailer] Sendmail support

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/symfony#32962]
**Description**  
I'm missing the possibility to use the locally available sendmail configuration with the new Mailer component (which is awesome). Many shared hosts offer a fully configured local sendmail, which can be used without further application configuration, taking care of retries and authentication already.

With SwiftMailer this was as simple as setting the mailer url to 'sendmail' (`MAILER_URL=sendmail`).

**Example**  
```
# Send using sendmail on system
MAILER_DSN=smtp://@sendmail
```

**Comment by Rockstar04** [comment]
This would also be useful for dev tools like [Mailhog](https://github.com/mailhog/MailHog) with mhsendmail

**Comment by derrabus** [comment]
Using `smtp://sendmail` as DSN didn't work for you?

**Comment by bobvandevijver** [comment]
Oops! I was pretty sure I tried almost anything, and that it didn't work. But this does work indeed 😄  

Would still be a point of improvement for the documentation though: the mailers that are supported and how to configure them correctly.

**Comment by chalasr** [comment]
Would you mind opening a doc issue (or even better, a PR) on https://github.com/symfony/symfony-docs? Closing here.

**Comment by bobvandevijver** [comment]
@chalasr Sure, done!
