### ISSUE TITLE
[HttpClient][RFC] Handle 'null' value in JSON

### ISSUE THREAD

**Issue by Zarcox** [symfony/symfony#32975]
Hey :) !

Last day, I was working on one of my projets and was surprised to see that one of the API I was using returned a `'null'` response in plain string without any `{}` :O !

I read this article which tends to corroborate this idea : https://benohead.com/null-valid-json-text/#Changes_in_RFC_7159

Here is the link to the aforementioned RFC : https://tools.ietf.org/html/rfc7159

The problem is that using the `toArray()` method of the `HttpClient` on such a response triggers a `JSON content was expected to decode to an array, NULL returned.` error, despite the fact that its content seems to be RFC compliant :/.

I spoke with @nicolas-grekas about this case and he suggests to add a boolean parameter which would allow the `toArray()` method to handle this kind of response by returning `null` if it encounters a `'null'` response :).

What do you guys think about it x) ?

Thanks ;) !

**Comment by nicolas-grekas** [comment]
It could be worth it to change the return type of `ResponseInterface::toArray()` to `?array`
an empty json body or an explicit null json would return `null`.
Up for a PR? It could help the discussion I believe.

**Comment by Zarcox** [comment]
Well, I gave it a try, but I am more than unsure as to how I am supposed to handle the `$this->jsonData` property of the `ResponseTrait` class. I don't know how to handle its cycle of life once it has become `null`.

**Comment by ro0NL** [comment]
this is an extra cost for implementation that always expect arrays, they now need to account for possible `null`. Im not sure that's the common case, based on how we design `toArray` in the first place.

The alternative is as simple as `$response->getContent() === 'null'` isnt it?

**Comment by derrabus** [comment]
I agree with @ro0NL here: A `null` response is a special case that your application logic needs to handle either way. So, without any change, that logic would look like this:

```php
if ($response->getContent() === 'null') {
    // Do something
}
```

If we add a boolean parameter and change the return type to nullable array, the code would look like this:

```php
if ($response->toArray(true) === null) {
    // Do something
}
```

This does not look like an improvement to me.

**Comment by nicolas-grekas** [comment]
I think this has been resolved :) thanks for suggesting

**Comment by stof** [comment]
but this would also break for other cases. A JSON response could also be a string, a boolean or a number, not only `array|null`.
There is nothing in the JSON spec enforcing that the top-level value is an array or object.

**Comment by nicolas-grekas** [comment]
then use getContent() :)
this still covers almost all realworld use cases

**Comment by stof** [comment]
Well, what I mean is that changing the return type of `toArray()` to `?array` to account for non-array JSON would not make sense.
So we should keep `toArray` returning an array all the time, and APIs returning other kind of JSON should be processed using `getContent`. We should not make a special case for `null` but not for other types.
