### ISSUE TITLE
[RFC]Symfony - Mailer with Gmail Transport

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony#32978]
**Description**  
I see in a doc from Mailer : https://symfony.com/doc/current/components/mailer.html#transport, a small vulnerability error if it is used in public projects. Let me explain, swiftmailer uses environment files directly to configure the smtp transport. However, for Mailer with GmailTransport, when you instantiate GmailTransport, you can directly put user and password, and therefore put credentials in the source code that are visible to everyone (if it is public).

**Example**  
Added in config package a gmail-transport.yml
In .env configuration added : 
```yaml
gmail:
    user: ~
    password: ~
```

**Comment by fabpot** [comment]
Configuration for the mailer is done via env vars, not via specific settings like user or password. In any case, it's up to the developer to not store any sensitive information in their config (that's not related to the mailer).
