### ISSUE TITLE
[Mailer] Sometimes we got `Relaying denied`, what should we do?

### ISSUE THREAD

**Issue by Kocal** [symfony/symfony#32987]
**Symfony version(s) affected**: 4.3.2

**Description**  
When using the new Mailer component with the Mailgun transport, we have the following issue when sending an email (`$mailer->send(...)`):
```
Symfony\Component\Mailer\Exception\TransportException: 
Expected response code "250/251/252" but got code "550", with message "550 5.7.1 Relaying denied".
```

Our Mailer's url looks like this: `smtp://smtp.mailgun.org:587?username=<username>&password=<password>`.

Also note that we didn't have any issues when using SwiftMailer.
I will try to update the project to the last version of Symfony and see if it solve our issue.

Thanks

**Comment by fabpot** [comment]
It looks like we are trying to send an email without being authenticated. Probably happens when reusing an SMTP session after some time.

**Comment by fabpot** [comment]
@Kocal Is it a permanent issue or does it happen only randomly?

**Comment by Kocal** [comment]
It's a permanent issue. 
I will try to use the `http://...@mailgun` DSN as a temporary workaround.

**Comment by fabpot** [comment]
Just notice that your DSN is wrong: smtp://smtp.mailgun.org:587?username=<username>&password=<password> is not valid (that's a Swiftmailer DSN, not a Symfony Mailer one).

**Comment by fabpot** [comment]
https://symfony.com/doc/current/components/mailer.html#use-a-dsn

**Comment by Kocal** [comment]
Oh sorry, I didn't think about changing it.

Also thanks for the link, I wasn't able to find anything for helping me [here](https://github.com/symfony/mailgun-mailer) or [here](https://symfony.com/doc/current/mailer.html).
