### ISSUE TITLE
Inconsistent password types for User

### ISSUE THREAD

**Issue by simPod** [symfony/symfony#32983]
Here in the User  implementation there are missing types for properties and the `$password` is defined as `?string` https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/User.php#L32

Here in interface as `string` https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/UserInterface.php#L57

What's source of truth? Thanks!

**Comment by chalasr** [comment]
The password must be a string. Are you willing to submit a PR against the 3.4 branch to fix the typehint?

**Comment by simPod** [comment]
Yup, but will be BC for implementation. Is that k?

**Comment by chalasr** [comment]
Fixed by #33257
