### ISSUE TITLE
Symfony Asset JsonManifestVersionStrategy doesn't work with UrlPackage. 

### ISSUE THREAD

**Issue by ognarb** [symfony/symfony#33001]
**Symfony version(s) affected**: 4.3 Symfony Asset component

**Description**  

Symfony Asset JsonManifestVersionStrategy doesn't work with UrlPackage. 

**How to reproduce**  

I'm creating a MediaWiki Skin and the CSS is generated from https://invent.kde.org/websites/aether-sass using Symfony Encore. The code is:

```php

$urlPackage = new UrlPackage(
    'https://cdn.kde.org/',
    new JsonManifestVersionStrategy('https://cdn.kde.org/aether-devel/version/manifest.json')
);

$out->addStyle( $urlPackage->getUrl('aether-devel/version/bootstrap.css'), 'all' );
 ```

**Possible Solution**  

I created a potential patch: https://invent.kde.org/websites/aether-mediawiki/blob/master/JsonManifestNetworkStrategy.php that remove the check that the file exist and instead check if `file_get_contents($this->manifestPath)` returned something. If this solution is good enough to be accepted, I will create a pull request :)

PS: I hope it's the right place to report a bug in Symfony component

**Comment by GromNaN** [comment]
I like your idea of using remote manifest. It makes it possible to deploy some assets independently from the website. I have a typical use-case for it: my company edits many news websites, each one is a distinct Symfony application. The advertising team works on a script `ads.js` that needs to be deployed on every websites very quickly ; we cannot make a commit and a deployment of every application. The easy solution is to reduce the TTL of the script to something, but we have to find a good balance between the time-to-deployment and the performance alerts ([Google recommends 1 year](https://web.dev/uses-long-cache-ttl/)). This feature would be a great benefit for performances and could result in better performances overall.

In your proposed patch, `file_get_contents` is used to download the file. This has some drawback like not being able to configure a cache, no error management, no timeout, no custom HTTP headers ... I think we should use Symfony's HttpClient to benefits from all its cache features.
