### ISSUE TITLE
[Profiler] no prune profiler result in no space left on disk

### ISSUE THREAD

**Issue by lerminou** [symfony/symfony#33006]
**Symfony version(s) affected**: 4.2.11

**Description**  
Is there any procedure to prune the profiler cache ? or an option in configuration?
I have a DEV environment with the profiler activated and the cache grows without limit.
after some days, my server turns into no space left on disk.

The cache has a prune command, maybe the same thing can be implemented here 

**How to reproduce**  
Activate the profiler with default options and launch requests in the DEV environment

**Additional context**  
```
[root@test dev]# pwd
/var/www/symfony/var/cache/dev
[root@test dev]# du -hs * | sort -rh | head -5
4,0G	profiler
2,1M	twig
1,9M	pools
1,6M	translations
1016K	ContainerRCuO9Ig

```

**Comment by linaori** [comment]
For development purposes, a button to purge _might_ be nice, however, `rm -rf var/cache/*` also does the trick. I've never ran into this problem in my development environment though.

**Comment by fabpot** [comment]
`rm -rf` is the way to go.
