### ISSUE TITLE
[Filesystem] Add $suffix argument to tempnam()

### ISSUE THREAD

**Issue by jdufresne** [symfony/symfony#33002]
**Description**  

The `tempnam()` interface is:

```php
tempnam($dir, $prefix)
```

I suggest adding a third argument, `$suffix`, that is added to the filename after the random component. This can default to `''` or `null` for backwards compatibility. This is quite useful when the temporary file is consumed for a specific purpose that expects a suffix.

**Example**  

```php
$filesystem->tempnam('/tmp', 'prefix_', '.png');
```

Would create a file like: `/tmp/prefix_abcd1234.png`.

**Comment by yceruto** [comment]
I don't understand why the third parameter is needed... why not do this instead:
```php
$filesystem->tempnam('/tmp', 'prefix_').'.png';
```
