### ISSUE TITLE
[Messenger] TLS/SSL support for Redis Transport 

### ISSUE THREAD

**Issue by matas-valuzis** [symfony/symfony#33025]
**Description**  
New redis transport for messages works great, unfortunately it appears it has no TLS/SSL support. 

**Example**  
If we would pass DNS string `rediss://xxxx/messages` we would get an error: `"No transport supports the given Messenger DSN "rediss://xxxx/messages"`. 

I propose implementing TLS/SSL support similar to [predis ](https://github.com/nrk/predis), where `rediss` would be an alias for `tls` protocol.

**Comment by Nyholm** [comment]
Could you elaborate why you need this?

Your application are (should!) share the same private network as the Redis server. Ie, your Redis server should never be exposed to the internet. So encryption is not really needed. 

Also note: A TLS handshake can take up to 200ms.

**Comment by matas-valuzis** [comment]
I completely agree that in production Redis should be in the same network as the app to achieve minimum latency if Redis is being used as a cache. When Redis is being used as a message queue for some batching tasks, read/write time is not that important and TLS would give higher flexibility for deployments. For example app that produces messages could be on a different network from app that consumes messages.

**Comment by Nyholm** [comment]
Hm.. Fair, but Im still hesitant. =)

Do you know (it is okey if you dont) how one should implement this? Is TLS supported in the ph redis extension?

**Comment by matas-valuzis** [comment]
I'm not sure how Redis transport in symfony is implemented. But if it uses phpredis, looks like tls is  [supported](https://github.com/phpredis/phpredis#connect-open)

**Comment by Nyholm** [comment]
A few days of thinking and I changed my mind. I believe you are correct. It is valid to have TLS support. 

I've created [a PR](#35503) for this. Could you test it to make sure it is working in your application?
