### ISSUE TITLE
[Form validation] isValid() isn't catching violations from properties not set through the form

### ISSUE THREAD

**Issue by o-alquimista** [symfony/symfony#33028]
My project is similar to Symfony Demo. I have a Post entity, and it has the properties `title`, `summary`, `body` and `slug`.

`Title`, `summary` and `body` have their own fields in the form. The slug doesn't. It is generated from the title in the controller by calling a Slugger utility.

The slug must be unique. The Post class is configured with the `UniqueEntity` annotation:
```
/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @UniqueEntity(fields={"slug"}, message="constraint_unique.slug")
 */
class Post
{...}
```

My expectation was that the UniqueEntity violation would be caught by the isValid() method and its message would show up in the form as a form error. It does not.

```
    public function createPost(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = new Post;
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $post = $form->getData();

            $slug = Slugger::slugify($post->getTitle());
            $post->setSlug($slug);

            if ($form->isValid()) {
                $entityManager->persist($post);
                $entityManager->flush();

                $this->addFlash(
                    'success',
                    'flash.published'
                );

                return $this->redirectToRoute('blog_post', ["slug" => $post->getSlug()]);
            }
        }

        return $this->render('blog/new_post/create_post.html.twig', [
            'form' => $form->createView(),
        ]);
    }
```

Instead of catching the UniqueEntity violation, the form data is stored successfully in the database with a duplicated slug, which is supposed to be forbidden.

My current workaround is to call the validator in the controller and pass its `$errors` to the template. The violation is then caught and I can show its message. This, however, creates many complications that I would prefer to avoid.

My intention is to display the slug violation message in the label of the title field, for consistency and for accessibility reasons. I haven't accomplished that yet, and I have no idea if it's even possible.

Why I believe this is a bug?
This is what the [documentation](https://symfony.com/doc/current/forms.html#form-validation) says:

> In other words, the question isn't whether the "form" is valid, but whether or not the $task object is valid after the form has applied the submitted data to it. Calling $form->isValid() is a shortcut that asks the $task object whether or not it has valid data.

To me, this means that isValid() is supposed to be validating **the entire Post entity**, not just the properties you set on the form. Is that right?

**Comment by xabbuh** [comment]
Could you please create a small example application that allows to reproduce your issue?

**Comment by o-alquimista** [comment]
@xabbuh Here it is: https://github.com/o-alquimista/symfony-test

I grabbed the latest Symfony Demo and applied the necessary changes to `/src/Entity/Post` and `/src/Controller/Admin/BlogController.php`, at the new() method. Then I tested it. It is reproducible. You can submit multiple posts with the same slug and no violations are caught.

**Comment by xabbuh** [comment]
@o-alquimista Thanks for the application. In fact, this does not look like a bug to me. The issue here lies in the way the application is implemented. When the form is submitted, the slug isn't set yet, but its value is `null`. This means that the validation inside the `UniqueEntityValidator` is skipped and no `ConstraintViolation` is actually raised. The slug is only generated after handling the form submission by the explicit `$post->setSlug(Slugger::slugify($post->getTitle()));` call in the controller. If that were moved into the form, validation should behave as expected.

**Comment by xabbuh** [comment]
Something like this in the `PostType` works:

```php
$builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
    $post = $event->getData();

    if (null !== $post->getTitle()) {
        $post->setSlug(Slugger::slugify($post->getTitle()));
    }
});
```

**Comment by o-alquimista** [comment]
@xabbuh  That works perfectly. I didn't even know Form Events was a thing. Thanks for the help!
