### ISSUE TITLE
 300 Multiple Choices redirect

### ISSUE THREAD

**Issue by StApostol** [symfony/symfony#33075]
**Description**  
In RFC exists 300 status for redirect response, but when I try send this code I get error "The HTTP status code is not a redirect"

**Example**  
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300
https://tools.ietf.org/html/rfc7231#section-6.4.1

**Comment by derrabus** [comment]
This happens, if you use `RedirectResponse` with a 300 status, right? I am unsure if that class is a good fit for a HTTP 300. Usually, that status is used together with a payload that presents the available choices to the client.

`RedirectResponse` however just generates generic HTML code with a JavaScript redirect to a single URL as payload. So you would either need to change the payload after creating the response (which makes using `RedirectResponse` a little pointless) or you would send a payload with only one choice (which is a contradiction to the semantics of HTTP 300).

I would recommend to use the generic `Response` class to send a HTTP 300 which should work just fine.

**Comment by StApostol** [comment]
@derrabus Yes, I try to use `RedirectResponse` for 300 redirects. But I don't understand:
- `300` -is redirecting status in RFC, 
- `RedirectResponse` - is class to create redirects. 

so why `RedirectResponse` not support 300? The only logical answer is that 300 status is rarely used

**Comment by derrabus** [comment]
> The only logical answer is that 300 status is rarely used

That or the fact that it is simply the wrong tool for a 300 response. It also does not support the status codes 304 and 305 for the same reason.
