### ISSUE TITLE
[WebServerBundle] Server not starting in test environment

### ISSUE THREAD

**Issue by redstar504** [symfony/symfony#33073]
**Symfony version(s) affected**: 4.0^

**Description**  
Symfony's built in web server starts properly in the dev environment but command is not available in test environment when using console command.

**How to reproduce**  
Run `bin/console server:start --env=test` after installing a fresh copy of Symfony 4.3.  This will return `Command "server:start" is not defined.`.  However, when you don't include the environment argument, it starts as expected in the dev environment.

The expected behavior would be for the built in web server to serve the application in the intended environment when accessing it via the server URL.  This is required when running User Interface tests.  It is possible to start PHP's built in web server with the following command achieving the same results:

`APP_ENV=test php -d variables_order=EGPCS -S 127.0.0.1:8000 -t public`

**Comment by fabpot** [comment]
Is the web server bundle available in the test env?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
