### ISSUE TITLE
Session is not started when FlashbagInterface is injected by DI and written to

### ISSUE THREAD

**Issue by warslett** [symfony/symfony#33084]
**Symfony version(s) affected**: Observed in 4.3.3

**Description**  
The session does not seem to be started on actions that return redirect responses. This issue comes to surface rarely because most of the time you will have loaded other pages before you visit an action that needs to both write to the session and redirect to another page.

One example is when someone might be following a link in an email (for example a reset password link or automatic login link) and the link has expired so we would need to redirect to another page and display a flash message.

The scenario above will work if you already have an active session but if you visit the site directly by the link the session isn't started and the flash messages don't get displayed. You can get around this by manually starting the session.

**How to reproduce**  

Session does not automatically start:
```
<?php

namespace App\Controller\User;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;

class ResetPasswordController
{

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    public function __construct(
        FlashBagInterface $flashBag
    ) {
        $this->flashBag = $flashBag;
    }

    public function __invoke(Request $request): Response
    {

            if (/* link is invalid */) {
                $this->flashBag->add('danger', 'Your reset link has expired or is invalid');
                return new RedirectResponse("/"); //redirects, no flash messages displayed unless session already started
            }
    }
}
```

Manually starting the session:
```
<?php

namespace App\Controller\User;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;

class ResetPasswordController
{

    /**
     * @var SessionInterface
     */
    private $session;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    public function __construct(
        SessionInterface $session,
        FlashBagInterface $flashBag
    ) {
        $this->session = $session;
        $this->flashBag = $flashBag;
    }

    public function __invoke(Request $request): Response
    {
            $this->session->start(); //start the session manually

            if (/* link is invalid */) {
                $this->flashBag->add('danger', 'Your reset link has expired or is invalid');
                return new RedirectResponse("/"); //works fine now with flash messages
            }
    }
}
```

**Comment by Shkarsardar** [comment]
do you want session started on every page?

**Comment by warslett** [comment]
@Shkarsardar I want the session started whenever it is written to which is the behaviour described in the documentation which doesn't seem to be the behaviour in practice:
https://symfony.com/doc/current/components/http_foundation/sessions.html

> While it is recommended to explicitly start a session, a session will actually start on demand, that is, if any session request is made to read/write session data.

**Comment by derrabus** [comment]
I doubt that the redirect is the problem here. 🤔

**Comment by warslett** [comment]
@derrabus I presumed it was because that's the only thing I could see that was different. I'll run some more tests

**Comment by maitre-hibou** [comment]
I have the same issue but it's not related to the `RedirectResponse` for me. My code :
```php
<?php

declare(strict_types=1);

namespace App\Action\Security;

use App\Form\Type\Security\RegisterType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\RouterInterface;
use Twig\Environment;

final class RegisterAction
{
    private $twig;

    private $formFactory;

    private $flashBag;

    private $router;

    public function __construct(Environment $twig, FormFactoryInterface $formFactory, FlashBagInterface $flashBag, RouterInterface $router)
    {
        $this->twig = $twig;
        $this->formFactory = $formFactory;
        $this->router = $router;
        $this->flashBag = $flashBag;
    }

    public function __invoke(Request $request, Session $session)
    {
        $registerForm = $this->formFactory->create(RegisterType::class);
        
        // This doesn't do anything in flashbag
        $this->flashBag->add('success', 'It works with $this->flashBag->add()');

        //This displays the message twice
        $session->getFlashbag()->add('success', 'It works with $this->flashBag->add()');
        $this->flashBag->add('success', 'It works with $this->flashBag->add()');

        return new Response(
            $this->twig->render('security/register.html.twig', [
                'registerForm' => $registerForm->createView(),
            ])
        );
    }
}
```

**Comment by warslett** [comment]
@maitre-hibou that's interesting. We are both getting the flashbag by dependency injection which might be relevant although I am doing this all over my application and only seem to have this problem on one particular action. I will run some more tests when I get a chance to better isolate the source of this problem.

**Comment by stof** [comment]
injecting the flashbag directly in the service rather that getting it from the session makes a big difference: in the first case, you never call any code on the Session object, and so lazy-start does not trigger.

**Comment by warslett** [comment]
@stof thank you I just came back here to say this after reading through the code. For me this raises the question "is it ever right to inject the Flashbag as a service?" because in principle it means that if we are accessing the flashbag in this way we should always also inject the session so that we can manually start it. Therefor we might as well just inject the Session and get the Flashbag through that. In which case, maybe the FlashbagInterface should not be defined as a service at all?

Or could we change the way FlashbagInterface service is defined so that it uses Session as a factory and getFlashbag() as a factory method. This way when FlashbagInterface in injected with DI it will always trigger the lazy load process?

**Comment by DjangoZorro** [comment]
Replace your "__invoke" public function with this code:

`public function __invoke(Request $request, Session $session)
    {
        $registerForm = $this->formFactory->create(RegisterType::class);
        
        $session->getFlashbag()->add('success', 'It works with $this->flashBag->add()');

        return new Response(
            $this->twig->render('security/register.html.twig', [
                'registerForm' => $registerForm->createView(),
            ])
        );
    }`

It will work perfectly, thank me later :)

**Comment by Tobion** [comment]
So the problem here really seems to be that people should not inject the FlashBag directly but only get it through the session. Otherwise the bag is not registered with the session at all and writes do not start the session.
So the PR https://github.com/symfony/symfony/pull/24200 seems wrong as it encoured using the flash bag service when it shouldn't be at all in user-land.

**Comment by DjangoZorro** [comment]
@Tobion Yes that's correct. In simple terms: FlashBag is only to be used with session so therefore use it like this:

```
<?php

namespace App\Controller;

use App\Entity\...;
use App\Form\...;
use App\Repository\...;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * @Route("/...")
 */
class ...
{
    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    public function __construct(FlashBagInterface $flashBag)
    {
        $this->flashBag = $flashBag;
    }

    /**
     * @Route("/...", name="...")
     */
    public function ...(... $..., Session $session)
    {
        ...

        $session->getFlashbag()->add('type', 'message');

        return new RedirectResponse(
            $this->router->generate('...')
        );
    }
}
```

**Comment by warslett** [comment]
I did have another thought which is that we could use session as a factory to get the flashbag using the usual method
```
services:
    Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface:
        factory: ['@Symfony\Component\HttpFoundation\Session\Session', 'getFlashBag']
```

**Comment by nicolas-grekas** [comment]
@warslett up for a PR? We shouldn't change the alias, but the `session.flash_bag` service, otherwise looks interesting to me.

**Comment by warslett** [comment]
@nicolas-grekas sure I can do that

**Comment by nicolas-grekas** [comment]
friendly ping @warslett so that we don't forget about it :)

**Comment by warslett** [comment]
PR open @nicolas-grekas
