### ISSUE TITLE
[Mime] Add NamedAddress::fromString

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony#33086]
**Description**  
I'm about to build a feature to convert an encoded address to a NamedAddress instance, but thought it might be interesting adding it in the mime component by default. This makes it easier and more readable to use addresses in configuration for example.

**Example**  
```php
use Symfony\Component\Mime\NamedAddress;

$address = NamedAddress::fromString("Giso Stallenberg <gisostallenberg@example.com>"); // instance of NamedAddress
$address->getName(); // Giso Stallenberg
$address->getAddress(); // gisostallenberg@example.com
```

**Comment by fabpot** [comment]
Great! That looks like a good addition.

**Comment by gisostallenberg** [comment]
Cool, I'll try to create a PR
