### ISSUE TITLE
[VarDumper] ImageCaster lacks tests

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#33107]
**Symfony version(s) affected**: 4.4

**Description**  
https://github.com/symfony/symfony/pull/32683 introduced a new ImageCaster on top of `imagine/image`. 
Problem is that the feature is not tested at all, and optional features that rely on external vendors must particularly be tested (allows for early detection of incompatible versions etc..).

**How to reproduce**  

**Possible Solution**  
Add `imagine/image` to the VarDumper dev-requirements and write a unit test for the ImageCaster (see other caster test cases for inspiration).

**Additional context**

**Comment by nicolas-grekas** [comment]
I don't think we want to test the ImagineCaster as it's pure glue, and not worth the additional (even dev) dependency when testing (if we start doing so, are we going to do it for all other casters? I don't think it would be useful).

But it'd be great to test the new logic in `HtmlDumper` in combination with `ImgStub`
