### ISSUE TITLE
Real environment variable APP_ENV does not win over .env

### ISSUE THREAD

**Issue by Sheepwall** [symfony/symfony#33118]
EDIT: Using docker environment variables (e.g. via the `environment` key in the .yml-file) **does** work, it is just using `export` that does not.
(Edit 2: typo)

**Symfony version(s) affected**: 4.3.3 

**Description**  

Real environment variables do not seem to win over the .env "APP_ENV" value when it is set to "dev", contrary to the comment generated in the .env-file.

**How to reproduce**  

In **.env** (overridden by .env.local as explained by the comment here):
```
# In all environments, the following files are loaded if they exist,
# the later taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=060a88455e303327ed566ed078fa6ad0
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS='^localhost|example\.com$'
###< symfony/framework-bundle ###
```

In **.env.local** (not overridden by environment variable, see further below):
```
###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=060a88455e303327ed566ed078fa6ad0
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS='^localhost|example\.com$'
###< symfony/framework-bundle ###
```
Note that `APP_ENV` is set to `dev` above.

In **bundles.php**:
```
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];

```

Inside the docker container with php and apache where I run it, I check `php -i | grep APP_ENV` after `export APP_ENV=prod`:
```
root@7e7c70f58582:/var/www/html# php -i | grep APP_ENV
APP_ENV => prod
$_SERVER['APP_ENV'] => prod
```
...where `APP_ENV => prod` is under the headlines
```
Additional Modules

Module Name

Environment
```
upon looking in the full `php -i`.

In the same container also directly after setting `export APP_ENV=prod` I produce the `php bin/console about`:
```
root@7e7c70f58582:/var/www/html# php bin/console about
 -------------------- --------------------------------- 
  Symfony                                               
 -------------------- --------------------------------- 
  Version              4.3.3                            
  End of maintenance   01/2020                          
  End of life          07/2020                          
 -------------------- --------------------------------- 
  Kernel                                                
 -------------------- --------------------------------- 
  Type                 App\Kernel                       
  Environment          prod                             
  Debug                false                            
  Charset              UTF-8                            
  Cache directory      ./var/cache/prod (475 KiB)       
  Log directory        ./var/log (0 B)                  
 -------------------- --------------------------------- 
  PHP                                                   
 -------------------- --------------------------------- 
  Version              7.3.8                            
  Architecture         64 bits                          
  Intl locale          n/a                              
  Timezone             UTC (2019-08-12T01:38:34+00:00)  
  OPcache              false                            
  APCu                 false                            
  Xdebug               false                            
 -------------------- --------------------------------- 
```

The resulting error is

> Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle". Did you forget a "use" statement for another namespace?
> 
>  (1/1) ClassNotFoundException
> 
> Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
> Did you forget a "use" statement for another namespace?
> 
> 
> in Kernel.php line 23
> --
> at Kernel->registerBundles()in Kernel.php line 424
> at Kernel->initializeBundles()in Kernel.php line 130
> at Kernel->boot()in Kernel.php line 193
> at Kernel->handle(object(Request))in index.php line 25

If I remove the WebProfilerBundle, it complains instead over the MakerBundle which is the other dev-only bundle in bundles.php. 

Also noteworthy is that with only the `.env` file, (no `APP_ENV=prod` from the `export` command), the `bin/console about` command doesn't work. But after `export APP_ENV=prod`, `bin/console about` works. The app does not, however.

**If I set the `APP_ENV` in .env.local to `prod`, the app works again!**

**Possible Solution**  

The workaround I will probably use in production is to set a .env.local file in the CI/CD or otherwise make sure that .env doesn't contain APP_ENV=dev, since that overrides environment variables.

**Additional context**  

Please ask for more info or clarification. Maybe I have just misunderstood the comment about "Real environment variables win over .env files."

Thanks

**Comment by xabbuh** [comment]
Can you create a small example project that allows to reproduce your issue?

**Comment by Sheepwall** [comment]
> Can you create a small example project that allows to reproduce your issue?

Yes, I just did so. It is over at https://github.com/Sheepwall/bug_demo
Read the README.md to reproduce. (Requires docker)

**Comment by ThibaultVlacich** [comment]
Having the same issue here. None of the real environment variables are used by Symfony. Only what's in the .env* files.

For example, here's what PHP returns for the DATABASE_URL var:
```
~ $ php -i | grep DATABASE_URL
DATABASE_URL => mysql://***:***@***.***.us-east-1.rds.amazonaws.com:3306/***
$_SERVER['DATABASE_URL'] => mysql://***:***@***.***.us-east-1.rds.amazonaws.com:3306/***
$_ENV['DATABASE_URL'] => mysql://auguqc7ifc4vx6xj:mysql://***:***@***.***.us-east-1.rds.amazonaws.com:3306/***
```

But Symfony still tries to connect to `DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name` like defined in the default .env file

**Comment by xabbuh** [comment]
@Sheepwall I suspect this is related to your Docker setup that for some reason doesn't export the env var properly. I just gave your project a quick try without Docker and there the application behaves as expected:

```
$ APP_ENV=prod bin/console cache:clear

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared. 
```

**Comment by Sheepwall** [comment]
@xabbuh
I just tried with the same bug_demo code and I can do the same in the docker container with the same message:
```
root@006c5bd6e6bf:/var/www/html# APP_ENV=prod php bin/console cache:clear

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                                                    
```

**Comment by xabbuh** [comment]
> EDIT: This is the expected behaviour of course, but the app is still throwing an error about MakerBundle even if the APP_ENV is exported to prod, while the .env that is supposed to be overridden is APP_ENV=dev.

@Sheepwall Where is this exception being thrown? On the command-line or through HTTP requests?

The command `APP_ENV=prod php bin/console cache:clear` shows that the env var is not overridden by Symfony. Otherwise the `cache:clear` command would have failed with the MakerBundle not being found.

**Comment by Sheepwall** [comment]
@xabbuh
Yes the override works for that command and some other bin/console commands (I tried `about`). But the Exception is still thrown by the app in other cases, such as when connecting with it on localhost or some server, through HTTP requests as you say. That shows that the override does not happen, since the APP_ENV environment variable is set to `prod` on the server when the connection is happening.

**Comment by xabbuh** [comment]
If you just serve the output of `phpinfo()` without any Symfony code involved through your webserver, is he `APP_ENV` variable exposed with the value `prod`?

**Comment by Sheepwall** [comment]
@xabbuh
No it doesn't! So it is Docker then? I can run `php -i` inside the docker container that has the web server and find `APP_ENV` there, but `phpinfo()` doesn't seem to care about it when requesting through HTTP.

**Comment by Sheepwall** [comment]
Okay I just tested to set it properly through Docker and then it overrides as it should. I did not know this about Docker and I'm still not sure what is actually happening behind the scenes, but Symfony has no blame in this!

Thanks for your patience @xabbuh.

**Comment by xabbuh** [comment]
I am not an expert in configuring Docker. But you probably need to export the env var for the process that actually starts the web server (there may also be a config file where you could place it).

**Comment by nicolas-grekas** [comment]
Closing then.

**Comment by harzallah** [comment]
If someone stumble upon this the solution is here : https://stackoverflow.com/a/55634277/3594361
You have to configure Apache to make env variables available to php

**Comment by legionth** [comment]
Thank you @harzallah, I was just able to fix this in my `docker-compose.yml`
```yaml
  php:
    image: php:7.4-fpm
    environment:
      APP_ENV: prod
      DATABASE_URL: ...
```
