### ISSUE TITLE
[Mailer] SentMessageEvent

### ISSUE THREAD

**Issue by acassan** [symfony/symfony#33121]
**Description**  
When using round_robin or fail_over strategy, we cannot know which provider is used
Dispatch an event with transport used once message sent successfully

**Example**  
In " Symfony\Component\Mailer\Transport\AbstractTransport" in method send()

```php
$event = new SentMessageEvent($message, $transport);
$this->dispatcher->dispatch($event);
```

Never contribute but can do it if feature is voted

**Comment by fabpot** [comment]
The good news is that it's been added in 4.4 already (`$event->getTransportName()`).
