### ISSUE TITLE
[PhpUnitBridge] 3.4.30 incompatible with PhpUnit 8.3.*

### ISSUE THREAD

**Issue by sawmurai** [symfony/symfony#33143]
**Symfony version(s) affected**: 3.4.30

**Description**  

Version 3.4.30 of PhpUnitBridge is not compatible with phpunit 8.3.* because https://github.com/symfony/phpunit-bridge/blob/v3.4.30/DeprecationErrorHandler.php#L111 calls a method that has been removed in 8.3

A workaround is to stick to PhpUnit 8.2

**Comment by nicolas-grekas** [comment]
Or to wait for the next version: https://github.com/symfony/symfony/pull/32933

**Comment by sawmurai** [comment]
Awesome! Thanks a lot :)
