### ISSUE TITLE
Should Symfony translate security exception messages?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33168]
**Description**  
Symfony includes the translation of Security exception messages ... but they are not used automatically.

For example, if you build a custom Guard-based login mechanism ... `UsernamePasswordJsonAuthenticationListener` can return `return new JsonResponse(['error' => $failed->getMessageKey()], 401);` and you get `Bad credentials.` message in English, regardless of the current application locale.

Is this correct? Look at PHPdoc:

```php
   /**
     * Message key to be used by the translation component.
     *
     * @return string
     */
    public function getMessageKey()
```

So, this is *meant* to be translated. Should we do it?

In the [login form docs](https://symfony.com/doc/current/security/form_login_setup.html) we translate this manually:

```twig
   {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}
```

Should this message come translated instead?

**Comment by javiereguiluz** [comment]
Some people said on Slack that the current behavior is correct. The returned value is the translation key because "you can translate it" ... not because "it's translated by Symfony automatically".

And we use real messages instead of message keys to make messages readable when you don't have the Translation component installed.

**Comment by linaori** [comment]
Could make this behavior configurable in the authenticator, as there can be valid cases where you don't want to translate it yet.

**Comment by wouterj** [comment]
I just looked at the translation integration of the Form component and I don't think there is anything to do here. The form component integrates with translation only in their default Twig templates.

The Security component is "translation ready", we ship translations (`src/Symfony/Component/Security/Core/Resources/translations/`) and the exceptions have `getMessageKey()`/`getMessageData()` methods.

Automatically translating them would mean we have to catch them somewhere, translate them (if translator is enabled) and then rethrow it. That would also require an option to opt-out/in of this feature. I don't think it's worth it.

**Comment by xabbuh** [comment]
I agree with Wouter.

**Comment by ro0NL** [comment]
UsernamePasswordJsonAuthenticationListener not translating the security exception looks like a bug to me btw :)

**Comment by wouterj** [comment]
> UsernamePasswordJsonAuthenticationListener not translating the security exception looks like a bug to me btw :)

I think this is an interesting idea and quite simple to implement. We can add some `setTranslator()` method to the json authenticator and translate the error if it's set:
https://github.com/symfony/symfony/blob/6d521d40721104ac684565fe6d1ca2bb0372127e/src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php#L117-L121

**Comment by malteschlueter** [comment]
Is it a bug or new feature? At the moment i changed it in _master_.

**Comment by ro0NL** [comment]
technically a new feature, behavior-wise a bug. Let's be safe and target master :)

**Comment by malteschlueter** [comment]
I know this issue is already merged and closed but i added some tests now. See #38044.
