### ISSUE TITLE
[DI] Tagged Service Locator empty when used in a binding

### ISSUE THREAD

**Issue by guillaumesmo** [symfony/symfony#33174]
**Symfony version(s) affected**: 4.3.3

**Description**  
When using a !tagged_locator in a binding (ServiceLocatorArgument with TaggedIteratorArgument), I expect the service locator to be injected in my services with all tagged services. Unfortunately, the injected service locator is empty. 

**How to reproduce**  
https://github.com/guillaumesmo/symfony_tagged_locator_issue/blob/master/config/services.yaml
I uploaded a test project which used a service locator in an argument, a binding and a default binding. 
output:
`array:2 [▼
  "App\Service\MyServiceOne" => "App\Service\MyServiceOne"
  "App\Service\MyServiceTwo" => "App\Service\MyServiceTwo"
]
[]
[]`

**Possible Solution**  
Not sure what is expected, since the documentation is very unclear about this
https://symfony.com/doc/current/service_container/service_subscribers_locators.html -> nothing about configuration here, only PHP subscribers
https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services -> only tagged is briefly discussed here, no tagged_locator
https://symfony.com/blog/new-in-symfony-4-3-indexed-and-tagged-service-collections -> best documentation so far

To solve the issue in my demo, in DI Component PassConfig.php, I put the ServiceLocatorTagPass after the ResolveBindingsPass, but not sure if it breaks other things and if that could be an accepted solution

Another "solution" is to document the limitation of using the tagged_locator in bindings. Even better if we could throw an exception on container build when this case occurs. Now, it silently passes you an empty service locator which is very odd. 

**Additional context**  
The reason I consider this a bug is because it works as expected (in the 3 cases) when you use !tagged instead of !tagged_locator. In my opinion, someone should be able to switch from one to another type without breaking everything.

**Comment by nicolas-grekas** [comment]
Can you please check with `4.3@dev`? I think this has been fixed already (but not tagged yet)

**Comment by guillaumesmo** [comment]
It has been fixed in PR 32722 indeed, not sure why I didn't find that one before

Sorry for the confusion, it works on 4.3@dev
