### ISSUE TITLE
[Form] Cannot use object of type Closure as array

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#33188]
**Symfony version(s) affected**: 4.2.11

**How to reproduce**  

Have type defined like this:

```php
class MyDateAndTimeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('time', TimeType::class, $options);

        $builder->addModelTransformer(new MyDateAndTimeToDateTimeTransformer());
    }

    public function getBlockPrefix()
    {
        return 'data_and_time';
    }
}
```

You get this error when creating the form:

```
Cannot use object of type Closure as array

  at vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php:80
```

The problem is passing options to `$builder->add('time', TimeType::class, $options)` which carries:

```
  "empty_data" => Closure(FormInterface $form) {#2763 ▼
    class: "Symfony\Component\Form\Extension\Core\Type\FormType"
    this: FormType {#2569 …}
    parameters: {▶}
    file: "vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php"
    line: "140 to 142"
  }
```

This used to work in 4.1

**Additional context**  
Suspected changeset https://github.com/symfony/symfony/pull/29182.

**Comment by xabbuh** [comment]
Does this happen with 4.3 too? If so, could your create a small example application that allows to reproduce?

**Comment by umpirsky** [comment]
According to code I guess it does. I will try to create a reproducer when I have time.

**Comment by derrabus** [comment]
Why do you pass the `$options` array on to the `add()` method? That looks odd to me.

**Comment by umpirsky** [comment]
Yes, I fixed that, but it still feels like BC break.

**Comment by yceruto** [comment]
Even if passing the parent/resolved `empty_data` option to the TimeType field would be wrong here, I think TimeType is not taking into account the feasible Closure value that is allowed/documented for this `empty_data` option:

https://symfony.com/doc/current/reference/forms/types/form.html#empty-data:
> If a form is compound, you can set empty_data as an array, object or **closure**. See the [How to Configure empty Data](https://symfony.com/doc/current/form/use_empty_data.html) for a Form Class article for more details about these options.

https://symfony.com/doc/current/form/use_empty_data.html#option-2-provide-a-closure:
> **Using a closure is the preferred method**, since it will only create the object if it is needed.
> The closure must accept a FormInterface instance as the first argument:
> ```
> 'empty_data' => function (FormInterface $form) {
>     return $form->getConfig()->getCompound() ? ['hour' => 0, 'minute' => 0] : '00:00';
> },
> ```

So the above example should also work for TimeType, isn't it?

**Comment by umpirsky** [comment]
Yeah, seems so.

**Comment by yceruto** [comment]
https://github.com/symfony/symfony/blob/ef0119a2d40f1a5930b4fd9146b1569b17d849ea/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php#L77-L81

As we can't invoke the `$emptyData()` closure directly in the build process (because the form instance is not ready to be passed to the closure at that point) theoretically something like this can fix the error (unproven):
```php
if ($emptyData instanceof \Closure) {
    $hourOptions['empty_data'] = static function (FormInterface $form) use ($emptyData) {
        $emptyData = $emptyData($form->getParent());

        return isset($emptyData['hour']) ? $emptyData['hour'] : '';
    };
} // elseif ...
```
@umpirsky would you like to give it a try? (bugfix in 3.4 branch)

**Comment by umpirsky** [comment]
Sorry, can't work on it now, it must wait.

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/34123
