### ISSUE TITLE
Unnecessary typecasting of unused variable

### ISSUE THREAD

**Issue by david-binda** [symfony/symfony#33206]
**Symfony version(s) affected**: [4.3](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1173), [4.4](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1211)

**Description**  
There seems to be an extra statement in the last foreach loop in the `\Symfony\Component\DependencyInjection\Dumper\PhpDumper::addMethodMap`

See https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1211

```
$id = (string) $id;
```

Since the `$id` is not used below this point, the typecasting, IMHO, does not really do much.

**How to reproduce**  
N/A

**Possible Solution**  
Removing the affected line. It's not breaking any PHPUnit tests on my machine.

**Additional context**

**Comment by Tobion** [comment]
Do you want to create a PR?

**Comment by david-binda** [comment]
Sure!
