### ISSUE TITLE
[RFC][Mailer][MonologBridge] Missing symfony/mailer handler

### ISSUE THREAD

**Issue by BoShurik** [symfony/symfony#33209]
Hello!

I don't know where is the right place for this handler.

@Seldaek [suggests](https://github.com/Seldaek/monolog/issues/1354) to place it in `symfony/monolog-bridge`. 
Maybe we need to create a separate package to use it with projects where `symfony/mailer` can be the single `symfony` dependency and in this case `monolog-bridge` will be too cumbersome

**Comment by fabpot** [comment]
Adding it to symfony/monolog-bridge sounds fine to me. Would you like to give it a try?

**Comment by BoShurik** [comment]
I'll try
