### ISSUE TITLE
[TwigBridge] Profiler __unserialize throws TypeError exception

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#33214]
**Symfony version(s) affected**: 4.3.3

**Description**  
On PHP7.4beta-2, twig profiler fails with this message:

``
Uncaught PHP Exception TypeError: "Argument 1 passed to Twig\Profiler\Profile::__unserialize() must be of the type array, unknown given" at /mnt/Development/reconnect/vendor/twig/twig/src/Profiler/Profile.php line 186 
``

**How to reproduce**  
Not sure, it doesn't happen on all pages. The site I am making has 70+ forms; some fail, some not. I disabled all my custom form themes, no changes.

The error stack I got:

![image](https://user-images.githubusercontent.com/1964158/63191838-d9d19180-c069-11e9-92dc-fbd18bd65cf9.png)

![image](https://user-images.githubusercontent.com/1964158/63191880-f5d53300-c069-11e9-8471-76e8665e094e.png)

**Additional context**  
Sometimes, still can't figure why and when, I get this error instead

```
unable to fetch the response from the backend: unexpected EOF
```

There is no difference if using Nginx vhost or symfony/cli (version v4.6.4).

---

This is probably some PHP bug. Is there a way I can simply remove ``data_collector.twig`` without breaking ``profiler``?

**Comment by nicolas-grekas** [comment]
Are you using preloading? This looks definitely like a PHP bug. Please try to isolate the issue and open a ticket on bugs.php.net

**Comment by zmitic** [comment]
No preloading, just installed it today and it's value is blank in phpinfo(). 

I also put ``opcache_reset()`` at top of ``public/index.php`` file, just in case there is again opcache issue but no changes.

I still think it has something to do with Symfony because the bug happens only on pages with forms. So I will try to make reproducer and publish the link here.

**Comment by Devristo** [comment]
I hit the same bug a month ago (On PHP 7.4 beta 1 and 2) but was not able to create a reproducer. Am curious what is causing this. Might give it another go.

**Comment by Devristo** [comment]
I have created a reproducer at https://gist.github.com/Devristo/878f4dbd9e30ee3a3c235f0d2ef3431d and filed a bug here https://bugs.php.net/bug.php?id=78438 .

**Comment by Devristo** [comment]
They made a fix! I tested it by manually compiling the PHP 7.4 branch and all seems fine again!

**Comment by xabbuh** [comment]
Let's close here then. Thanks for checking @Devristo.
