### ISSUE TITLE
sf3.4.30 cache:clear runs out of 64G of memory

### ISSUE THREAD

**Issue by n3o77** [symfony/symfony#33213]
**Symfony version(s) affected**: 3.4.30

**Description**  
When I run the cache:clear (cache:warmup) command the ReflectionClassResource::generateSignature method allocates a huge amount of memory and runs out at 64G (my max. setting). I attached the blackfire profiles. Everything else of the project runs fine.

**How to reproduce**  
Sorry so far I couldn't figure out exactly what's causing this. Any suggestions what I can provide to solve this are appreciated. Unfortunately I can't share the source of the project.

<img width="1419" alt="Screenshot 2019-08-16 at 20 15 00" src="https://user-images.githubusercontent.com/321891/63188771-9f182b00-c062-11e9-8584-5dea85eebed6.png">
<img width="1331" alt="Screenshot 2019-08-16 at 20 14 45" src="https://user-images.githubusercontent.com/321891/63188773-9f182b00-c062-11e9-8dd4-b14316ac2b78.png">

**Comment by derrabus** [comment]
Can you somehow share a Symfony application that reproduces the problem?

**Comment by linaori** [comment]
Can you check if #32809 solves your issue?

**Comment by n3o77** [comment]
It actually does @linaori 

Thank you very much.
