### ISSUE TITLE
Forcing route parameter with alternative syntax

### ISSUE THREAD

**Issue by dbrumann** [symfony/symfony#33224]
**Symfony version(s) affected**: 4.3.3

**Description**  
I am trying to force a parameter being set in a route using`!`. It is working with the following annotation:

```
@Route("/titles/{!page}", name="list", methods={"GET"}, defaults={"page": 1})
```

When I generate the route without specifying a parameter (`{{ path('list') }}`) the following path is generated: `/titles/1`.

Unfortunately when combining `!`with other short syntax elements it does not work as expected:

* Specifying a default value using `?1`:
    ```
    @Route("/titles/{!page?1}", name="list", methods={"GET"})
    ```
    produces: `/titles/%7B!page%3F1%7D`

* Specifying default as part of method signature:
    ```
    /**
     * @Route("/titles/{!page}", name="list", methods={"GET"})
     */
    public function list(int $page = 1) { ... }
    ```
    throws `Twig\Error\RuntimeError`:
    > Some mandatory parameters are missing ("page") to generate a URL for route "list".

* Specifying requirements for `page` using short syntax `<\d+>`:
    ```
    @Route("/titles/{!page<\d+>}", name="list", methods={"GET"}, defaults={"page": 1})
    ``` 
    produces: `/titles/%7B!page%3C%5Cd+%3E%7D`

**How to reproduce**  
1. Install annotations
    ```
    composer require annotations
    ```
1. Create a template with a link to the route using the force parameter: `{{ path('...') }}`
1. Create a controller action rendering the template with the route link
1. Create a controller action with one of the above route definitions containing `!`
1. Go to the initially defined route (template with link)

**Comment by nicolas-grekas** [comment]
Up for a PR to fix that @dbrumann?

**Comment by dbrumann** [comment]
I will have a look at it. :+1:

**Comment by Tobion** [comment]
@dbrumann is this still on your agenda?

**Comment by dbrumann** [comment]
I remember playing with the regex and trying a few things out, but it broke tests left and right. I gave up after a while as it's not that important to me.

Good news: tests around this are rock solid
Bad news: task is a tough cookie 😄

**Comment by Tobion** [comment]
Haha, well explained :)

**Comment by nicolas-grekas** [comment]
I'm putting the "help wanted" label here. Anyone up to having a look?

**Comment by nicolas-grekas** [comment]
See #38372
