### ISSUE TITLE
Mailer does not work with HostEurope Account

### ISSUE THREAD

**Issue by mwe1** [symfony/symfony#33231]
I am trying to get Symfony Mailer to work on my Apache Web Server, and added the credentials to my Hosteurope mailing account in my .env file in the following format:

'MAILER_DSN' => 'smtps://username:password@hosteuropeserver:465'

I don't know why it wouldn't work

**Comment by fabpot** [comment]
You should use `smtp` instead of `smtps` and add `?encryption=tls` at the end.
