### ISSUE TITLE
[Validator] Add hasViolation method to ConstraintViolationListInterface

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#33230]
I know that is not the PR of the century but I would like to add an helper to check if a ConstraintViolationList contains or not violation.

At the moment we have to do this to check if ConstraintViolationList has some errors,

```php
if (0 !== count($violations)) {
```
This is what is done in [doc](https://symfony.com/doc/current/components/validator.html#usage) and [Api Platform](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Validator/Validator.php#L62) and I would like to replace it by
```php
if($violations->hasViolation())
```
It's better to reading and easier to be implemented with IDE autocompletion for newcomers that are not familiar with the Validator API

To avoid BC break I would like to target Symfony 5.
I will update documentation if code is merged.

WDYT ?

**Comment by fabpot** [comment]
Adding a method in an interface is not simple. I mean, adding it in 5.0 without an upgrade path from 4.4 is not possible. So, I think it's not worth it. The new method is less powerful than what we already have. Let's close.

**Comment by ostrolucky** [comment]
I think it's worth it, since this is highly requested feature
