### ISSUE TITLE
[Yaml] Syntax error not detected in first line of object

### ISSUE THREAD

**Issue by SamMousa** [symfony/symfony#33243]
**Symfony version(s) affected**: v4.3.3

**Description**  
A syntax error is ignored by the parser.

**How to reproduce**  
This code:
```
paths:
  abc
  abc: def
```
is successfully parsed but it is not valid YAML.

**Additional context**  
The following online parsers identify the error
- https://codebeautify.org/yaml-validator
- http://www.yamllint.com/

I have found several others that also identify the error correctly.

**Comment by stof** [comment]
what is the result of the parsing ?

**Comment by SamMousa** [comment]
```
php > var_dump( \Symfony\Component\Yaml\Yaml::parse($config, \Symfony\Component\Yaml\Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE));
array(1) {
  ["paths"]=>
  string(12) "abc abc: def"
}

```

```
php > var_dump( \Symfony\Component\Yaml\Yaml::parse($config));
array(1) {
  ["paths"]=>
  string(12) "abc abc: def"
}

```

Hmm, when reporting a parser bug it obviously makes sense to put in the parse result.. ^^

**Comment by SamMousa** [comment]
For completeness' sake:
```php
php > echo strtr($config, ["\r" => '#13', "\n" => '#10']);
paths:#10  abc#10  abc: def#10
```

**Comment by xabbuh** [comment]
Since #27898 which is part of Symfony 4.3 the given example should trigger a deprecation warning ("Support for mapping keys in multi-line blocks is deprecated") and will fail with a `ParseException` in Symfony 5.

@SamMousa Can you confirm that's the case or create a small reproducible example application otherwise?

**Comment by SamMousa** [comment]
Added to my todo.!

**Comment by xabbuh** [comment]
@SamMousa Did you manage to check for the deprecation?

**Comment by SamMousa** [comment]
Yes, just confirmed it.
```php
require 'vendor/autoload.php';

use Symfony\Component\Yaml\Yaml;
$yaml = <<<YAML
paths:
  abc
  abc: def
YAML;
set_error_handler(function($code, $message, $file, $line, $context) {
    throw new \Exception($message);
});
Yaml::parse($yaml);

```
