### ISSUE TITLE
[HttpCache] Does not modify the headers

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony#33249]
**Symfony version(s) affected**: 4.2.11 - 4.3.3

**Description**  
The problem is that it does not work, I do not see the status  code or response headers being changed. I'm using Symfony default proxy.

**How to reproduce** 

src/CacheKernel.php
 
```php
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache;

class CacheKernel extends HttpCache
{

  protected function getOptions(): array
  {
    return [
      'default_ttl' => 0,
      'trace_level' => 'full',
      'trace_header' => 'X-Symfony-Cache-New'
    ];
  }

}
```

public/index.php

```php

<?php

use App\CacheKernel;
use App\Kernel;
use Symfony\Component\Debug\Debug;
use Symfony\Component\HttpFoundation\Request;


require dirname(__DIR__).'/config/bootstrap.php';

if ($_SERVER['APP_DEBUG']) {
    umask(0000);

    Debug::enable();
}

if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? $_ENV['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}

if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? $_ENV['TRUSTED_HOSTS'] ?? false) {
    Request::setTrustedHosts([$trustedHosts]);
}

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
if ('prod' === $kernel->getEnvironment()) {
  $kernel = new CacheKernel($kernel,'./cache');
}
Request::enableHttpMethodParameterOverride(); // <-- add this line

$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```
src/Controller/Front/PageController.php

```php
<?php

namespace App\Controller\Front;

use App\Entity\Page;
use App\Entity\Seo;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\EventListener\AbstractSessionListener;


class PageController extends BaseFrontController
{

    /**
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $em       = $this->getDoctrine()->getManager();
        $idseo    = $request->get('id');
        $seo      = $em->getRepository(Seo::class)->find($idseo);
        /* @var Page $page */
        $page     = $seo->getPage();

        $response = new Response();
        $response->headers->set(AbstractSessionListener::NO_AUTO_CACHE_CONTROL_HEADER, 'true');
        $response->setLastModified($page->getUpdatedAt());
        $response->setEtag(md5('page-'.$page->getId()));
        $response->setPublic();
        if($response->isNotModified($request)) {
          return $response;
        }

        $template = $page->getTemplate();
        $metas    = $this->getMetas($seo,$page,$request);

        return $this->renderFront($template, [
          'metas'    => $metas,
          'entity'   => 'page',
          'page'     => $page,
          'seo'      => $seo
        ]);
    }

}
```
Response from browser:
![Response from browser](https://image.prntscr.com/image/c7ztGY1qQtWDCJWPAbGSHg.png)

As you can see the Cache-control is not modified, nor is Etag tag added, I think that the only thing I have got was to show the label 'X-Symfony-Cache-New', and only when I had upgrading to version 4.3.3, because in version 4.2.11 was not show.

One thing I've noticed is that if I add the cache annotations, it looks like it works, or at least it is what it looks like.

```php
 /**
     * @param Request $request
     * @Cache(expires="tomorrow", public=true)
     * @return Response
     */
    public function index(Request $request): Response
    {
```
Response from browser:
![Response from browser with annotations](https://image.prntscr.com/image/LKUwQjmnSZ6wJCRvQsO5tA.png)

**But I really need you to work through the controller because that's how I'm really going to get the true date of the last modification.**

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by chiqui3d** [comment]
Yes, done in https://github.com/chiqui3d/test-http-cache

**Comment by xabbuh** [comment]
The created `Response` object is never used when the template is rendered. If you update the controller like this, everything works as expected:

```php
return $this->render('without_annotations/index.html.twig', [
    'controller_name' => 'WithoutAnnotationsController',
], $response);
```

**Comment by chiqui3d** [comment]
I will check, a moment

**Comment by chiqui3d** [comment]
Yes, it works correctly. I feel the confusion.
Just one more doubt, when a 304 returns I don't get the header 'X-Symfony-Cache-New', I guess that's normal, right?

**Comment by xabbuh** [comment]
@chiqui3d You mean there is not `X-Symfony-Cache` header at all in the response?

**Comment by chiqui3d** [comment]
In the **first access** to generate the cache, yes! all the hearders are correct, but when I access by **second** that is when it shows me the cache and with **a response code 304**, no! I show you the image for you to see, but not really if it is normal.

![Response 304 from browser](https://image.prntscr.com/image/87yaWfHsQ16IFfJBcJPcQw.png)

**Comment by chiqui3d** [comment]
@xabbuh ,Should  I open other issue?

**Comment by xabbuh** [comment]
Are you sure the `CacheKernel` class is executed at all? Or is that header filtered out by your Apache config? I only tried your example application using PHP's built-in web server and there I can see the headers.

**Comment by chiqui3d** [comment]
The cache works **correctly**, and removal of header only happens with the **validation cache strategy**  when the **304 Not Modified** is return, I suppose that will be the functionality own remove headers. 

Well my main problem was that the cache didn't work and now it works great.

I'll just stay with the doubt of who removes that, if the `Browser, Symfony or Apache`. I tried to do a little research, but I didn't get it, maybe @nicolas-grekas  can make it clear to me.

Equally really thank you very much
