### ISSUE TITLE
Ease mocking the HttpClient

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#33274]
### Description

I find it hard to mock the HttpClient when it is used with state. Let me give you an example:

```php
class MyService
{
    public function doSomething()
    {
        $token = ...;

        $httpClient = HttpClient::create([
                'base_uri' => $this->apiUrl,
                'headers' => [
                    'Authorization' => 'Bearer ' . $token,
                ],
        ]);

        $httpClient->...
    }
}
```

Here the client is stateful because it contains a runtime-generated value (the token) in the default headers.

Because of that, I don't want to store the HTTP client in the container. Another reason on top of that is that I want to encapsulate that HTTP client's config inside my service, not expose it outside the class and spread it in the project.

**And because of that, I can't easily inject a `MockHttpClient` in tests.**

### Possible solutions

- **a `HttpClientFactory` to complement/replace `HttpClient::create()`**

```php
class MyService
{
    public __construct(HttpClientFactory $httpClientFactory)
    {
        $this->httpClientFactory = $httpClientFactory;
    }

    public function doSomething()
    {
        $token = ...;

        $httpClient = $this->httpClientFactory->create([
                'base_uri' => $this->apiUrl,
                'headers' => [
                    'Authorization' => 'Bearer ' . $token,
                ],
        ]);

        $httpClient->...
    }
}
```

Then I can inject a factory that creates the mock.

Pros : proper dependency injection

Cons : more classes, more complexity: yet another Factory to make an interface and have 2 implementations: the one that creates real clients, and the one that creates mock clients

- **add `HttpClient::clone()` to create a configured HTTP client from another one**

```php
class MyService
{
    public __construct(HttpClient $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    public function doSomething()
    {
        $token = ...;

        $httpClient = $this->httpClient->clone([
                'base_uri' => $this->apiUrl,
                'headers' => [
                    'Authorization' => 'Bearer ' . $token,
                ],
        ]);

        $httpClient->...
    }
}
```

This a way to add configuration to a client without affecting the global client configured in the container.

And in tests, if I inject a mock HTTP client, then the copy will still be a mock.

Pros : simpler, and can encourage registering a global HTTP client as a service, while still allowing services to inject it and configure it however they want

Cons : maybe less of a standard design pattern? (might be more confusing)

- **other solution?**

**Comment by nicolas-grekas** [comment]
I think you can already do this using `ScopingHttpClient`:

```php
public __construct(HttpClientInterface $client)
{
    $this->client = ScopingHttpClient::forBaseUri($client, $this->apiUrl, [
        'headers' => [
            'Authorization' => 'Bearer ' . $token,
        ],
    ]);
}
```

It will be even better than what you describe because then bearer will be sent only when the requested URL matches the base uri, whereas your example will send the bearer to any other URL too, if this happens in the class for any reasons.

**Comment by mnapoli** [comment]
Thanks. I have to admit this is not very obvious what is happening. I don't really want to scope settings to a specific URL, which is why I'm not sure people reviewing that code will understand why I did this.

What I want to say is that probably technically it works, but it's hard to figure out and I'm sure it will be hard to re-understand later. Maybe we can come up with a more explicit solution?

**Comment by nicolas-grekas** [comment]
If you don't want to scope by base URI, you can then do:
`$this->client = new ScopingHttpClient($client, ['.*' => $defaultOptions], '.*');`

This will apply the default options to any URL.

This could deserve some more doc I agree, would you mind giving a PR a try?

**Comment by tgalopin** [comment]
I like how the scoping client works personally, I find it much more convenient than a factory or another technique. It gives the scoping responsibility to the user of the client, not the developer of the factory, which is great IMO.

I think by reading `ScopingHttpClient::forBaseUri` it is easy to understand what it does. The notation with regular expressions is a bit more complex though, perhaps could we introduce a `ScopingHttpClient::forAnyUrl` static method?

**Comment by mnapoli** [comment]
```php
$this->client = new ScopingHttpClient($client, ['.*' => $defaultOptions], '.*');
```

TBH again this may work, but this is cryptic. And documentation could help, but it would just be copy-pasting. I imagine a junior or mid-level developer reading this in the code would be confused.

> `ScopingHttpClient::forAnyUrl`

Scoping without any URL isn't really scoping anymore though 😉 But I totally see what you mean, maybe we are moving onto a concept of "decorating a client with settings" more than just scoping settings to a URL?

Maybe the ScopingHttpClient could be phased out in favor of a more generic:

```php
// applies to all URLs
$authenticatedClient = new DecoratingClient($client, [ /* options */ ]);

// URL-specific configs
$scopedClient = DecoratingClient::scope($client, [
    'url1' => /* options */,
    'url2' => /* options */,
]);
```

Or another route to go would be to create a duplicate of `ScopingHttpClient` without URL-based scoping (i.e. the first line in the example above) and keep both classes.

Of course a 3rd option is to not do anything.

**Comment by tgalopin** [comment]
Could you be more precise about the exact bit that you don't think is clear? I really don't understand why you think it's crpytic :) .

**Comment by nicolas-grekas** [comment]
> Maybe the ScopingHttpClient could be phased out in favor of a more generic:

I wouldn't recommend adding a non-scoped decorator to add only options. It would be less generic actually, and it would help spread a potential security risk: the very one you made in your initial description, where a bearer could too easily leak to any hosts.
We could add a `::forAnyrUrl()` factory helper.
Why don't you want to scope by base_uri by the way? Would it break your use case if it does?

**Comment by mnapoli** [comment]
> Could you be more precise about the exact bit that you don't think is clear? I really don't understand why you think it's crpytic :) .

Let's imagine I am a developer that does not know the internals of Symfony, neither the specifics of the HTTP client component by heart. Here is what I see:

```php
$this->client = new ScopingHttpClient($client, ['.*' => $defaultOptions], '.*');
```

- `ScopingHttpClient`: What does "scoping" mean in the context of HTTP? What are we scoping? It seems we are scoping another client, but why? ("scoping" a http client is not a concept we encounter every day)
- `'.*'`: what does that mean?
- `'.*' => $defaultOptions`: why are we indexing HTTP options by this string?
- `, '.*'`: why are we adding it again here?

All of this can be overcome of course. But this is adding a lot of surprises just for mocking a HTTP client.

> Why don't you want to scope by base_uri by the way? Would it break your use case if it does?

I am using my HTTP client immediately, in a 10 lines function. Adding a concept of scoping here is unnecessary and I hope to keep the code as simple as possible. `HttpClient::create()` is that simple, but now I have to loose that simplicity just to make it mockable.

Again, I can do that (and I am doing it right now), but I hope we can find a way to make it simpler.

**Comment by nicolas-grekas** [comment]
OK, thanks for the feedback. I think `ScopingHttpClient::forBaseUri()` is the way to go then, as it is as simple as it can be technically and cover the need.
Then, we can talk about naming for years, but better do something else instead :)

**Comment by nicolas-grekas** [comment]
Doc PR here: https://github.com/symfony/symfony-docs/pull/12221

**Comment by OskarStark** [comment]
I merged the docs PR, so we can close here! Thanks.
