### ISSUE TITLE
[Messenger]Inconsistency between Symfony Messenger and framework-bundle configuration

### ISSUE THREAD

**Issue by cgaunet** [symfony/symfony#33284]
**Symfony version(s) affected**: 4.3.3

**Description**  
In the ```MultiplierRetryStrategy.php``` class of Symfony Messenger, the phpdoc specifies that a null value for maxRetries means indefinitely

![bug1](https://user-images.githubusercontent.com/19763200/63448765-ef1a3780-c43e-11e9-93e5-a58ca5be3724.png)

It can also be seen in the code of this class in the isRetryable method:
![bug2](https://user-images.githubusercontent.com/19763200/63448797-06592500-c43f-11e9-8d1e-fc742bd0583c.png)

However, in the framework-bundle dependency injection ```framework-bundle/DependencyInjection/Configuration.php``` class, l1215 the default value is set to 3 when max-retries is not set
![bug3](https://user-images.githubusercontent.com/19763200/63449236-f8f06a80-c43f-11e9-8bfe-4f8e16d13b2a.png)

**How to reproduce**  
![bug4](https://user-images.githubusercontent.com/19763200/63449297-23dabe80-c440-11e9-9846-2e7241fb75d3.png)

**Possible Solution**  
In ```framework-bundle/DependencyInjection/Configuration.php```:
Set the minimum values to -1 instead of 0

Pull Request: https://github.com/symfony/symfony/pull/33286

In ```Retry/MultiplierRetryStrategy.php```:
Instead of the null values to check whether or not having infinite retry, check that the value is equal to -1

**Comment by tienvx** [comment]
@cgaunet I almost create new issue that will duplicate your issue. I think the reason is I find the issues in the backlog using the keyword `max` and `max_retries` that does not match your issue title. I found this issue because I googled `MultiplierRetryStrategy`.

I suggest to change the title to include 'about max_retries' at the end
