### ISSUE TITLE
[RFC][Bundles] Add a system to manage app & bundle resources

### ISSUE THREAD

**Issue by sukei** [symfony/symfony#33293]
**Description**  
Add a system to let third-party bundles to declare its needed resources and "conventional" path to them. While reading the thread of https://github.com/symfony/symfony/pull/32845, I was thinking about a way to abstract this.

We are OK to say that bundles are opinionated in theirs structures. We stated that `*.twig` templates should be in `templates/` and translations files in `translations/`, but every bundle may add its own conventions over it.

What about adding a way to let bundles declare the "conventional" path for its needed resources and give it tools to locate them across the app and the registered bundles ?

**Example**  
```php
<?php

namespace My\Bundle\DBALBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use My\Bundle\DBALBundle\DependencyInjection\CompilerPass\SqlResourcesCompilerPass;

class MyDBALBundle extends Bundle
{
    public function build(ContainerBuilder $container);
    {
        $container->defineResourcesPaths('sql', 'res/sql/**/*.sql');

        $container->addCompilerPass(new SqlResourcesCompilerPass());
    }
}
```

When declared, the framework expects to finds the `sql` resources in the `res/sql` folders of the app and bundles.

```
config/
src/
tests/
res/
    └─ sql/
        └─ ...everything here
vendor/
    └─ organization/
        └─ lib/
            ├─ src/
            ├─ tests/
            └─ res/
                └─ sql/
                    └─ ...everything here
```

```php
<?php

namespace My\Bundle\DBALBundle\DependencyInjection\CompilerPass;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class SqlResourcesCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        /** @var SplFileInfo[] $list */
        $list = $container->locateResources('sql');

        // do something useful with the list of resources located in `res/sql` 
        // of app and registered bundles (like building a locator/loader for your
        // libs, etc.)
    }
}
```

On the other hand, I suggest to add a new directory called `res` to share user defined resources and to avoid the overload of the project root.

```
config/
src/
tests/
vendor/
templates/
translations/
sql/
...
gql/
```

VS

```
config/
src/
tests/
vendor/
res/
    ├─ templates/
    ├─ translations/
    ├─ sql/
    ├─ ...
    └─ gql/
```

Every bit of this RFC is subject to discussion, but you get the idea.

WDYT ?

**Comment by sstok** [comment]
Something like http://docs.puli.io/en/latest/ ? 😊 

And the `FileLocator` (HttpKernel and Config) already provides something similar 😛 
https://symfony.com/doc/current/components/config/resources.html#locating-resources

You can locate any resource of a bundle using `$container->get('file_locator')->locate('@BundleName/path-relative-to-bundle-directory');` in the examples above this would be something like:

`@BundleName/res/sql`.

Technically everything you are looking for is already available 👍

**Comment by sukei** [comment]
Puli was an amazing idea... Sadly it's abandonned. And yes, it's something like this I hope to see coming.

The `Symfony\Component\HttpKernel\Config\FileLocator` is not the right thing to use for this IMO. It does not handle glob paths and needs the full path of the resource to work. Moreover, it doesn't locate resources at the project level.

This RFC is more about aggregating these resources across the app & bundles without knowing anything about them. The simple fact to install a bundle that share resources in a `convention based` folder make them available to the project. Your solution is based on the fact that you know where to look.

**Comment by Tobion** [comment]
I don't understand what problem this RFC is trying to solve? Could you explain please.

**Comment by sukei** [comment]
The main idea is to ease the integration of libraries that needs resources provided by third-party bundles.

Maybe it would be more clear with an example.

Let's consider that I want to create a bundle which integrate a GraphQL library. This GraphQL library needs `*.graphql` files to build its schema. You may have installed bundles such as :
- `UserBundle`;
- `AclBundle`.

Each of them may provide their own `*.graphql` files that completes the final schema of the GraphQL endpoint. For now, I have to find a way by myself to locate those files and build services with these found paths. This RFC is about building a solution to make the framework locate those files for me at DI compilation time.

Instead of writing a homemade crawler to find `*.gql` resources through the project and installed bundles, I think it would be useful to have a convention based resource locator to help doing this. The `GraphQLBundle` may define that `graphql` resources may be found through the `res/gql/**/*.graphql` glob path and the framework will locate them for me. 

At DI compile time (CompilerPass and co.), I may get the following paths to help me building dedicated loader/locator/whatever:
- `/res/gql/schema.graphql`
- `/vendor/my/user-bundle/res/gql/user.graphql`
- `/vendor/my/acl-bundle/res/gql/acl.graphql`

If we can generalize this, every bundle that load resources may be simplified a lot. The second part of the RFC advises to add a `res/` folder into the project and the bundles to help keeping a `clean` structure. For now, there are `templates`and `translations` folders as first-class citizen resources. Tomorrow we may find `sql`, `gql`,  etc. that may pollute the project and bundles structure as shown there:

```
config/
src/
tests/
vendor/
var/
public/
templates/
translations/
sql/
gql/
```

VS

```
config/
src/
tests/
vendor/
var/
public/
res/
    ├─ templates/
    ├─ translations/
    ├─ sql/
    └─ gql/
```

**Comment by stephpy** [comment]
The biggest benefits is than we no more deal with file structure convention to find files. Any bundle, any library can store its files anywhere ... they just have to tag them as it's already done with services.

**Comment by Tobion** [comment]
So this is basically a convention-based Puli. Instead of configuring resource locations as in Puli, it forces everyone to use `res/{name}` for their resources. So your GraphqlBundle requires that every other bundle/library uses res/gql to store files. If they don't, it won't work.

I don't know why Puli died, but considering this, I think this RFC is a dead end.
The template, translation locations are standarized in Symfony because the framwork needs those resources itself. But it does not need other resources like graphql. So to me there is no point in trying to force a convention there for something that the framework does not care about.
In it's simple form, such feature can be easily implemented in user-land like a recursive directory iterator that finds certains files in bundles. If it get's more complex/general, I would refer to Puli,

**Comment by sukei** [comment]
> So this is basically a convention-based Puli.

You nailed it!

> I don't know why Puli died

From what I know (from @tgalopin), @webmozart stop doing PHP things and didn't found a maintainer.

>  So your GraphqlBundle requires that every other bundle/library uses res/gql to store files. If they don't, it won't work.

Thats what I mean when I talk about declaring "conventional paths".

> So to me there is no point in trying to force a convention there for something that the framework does not care about.

This is something that third-party bundles may declare, not the framework. The framework may just provide the tools.

> such feature can be easily implemented in user-land like a recursive directory iterator that finds certains files in bundles.

Tedious, but you are right.

> If it get's more complex/general, I would refer to Puli

I would love to 😢

**Comment by Tobion** [comment]
Closing as there hasn't been any activity and I don't think this is something for symfony core.
