### ISSUE TITLE
[HttpClient] No way to get Body of FormDataPart::bodyToIterable() in request

### ISSUE THREAD

**Issue by adamkelso** [symfony/symfony#33290]
**Symfony version(s) affected**: HttpClient Component

**Description**
First off, thanks so much for being a very active and friendly community.

I'm working on porting [Guzzler](https://guzzler.dev) to HttpClient and hitting an issue I'm not sure how to get around. When POSTing a request with the body as `'body' => $formDataPart->bodyToIterable()`, my mock client handler is given a closure back as the body. That would be fine, but invoking that closure only ever returns an empty string.

If I'm not using the request as intended, I will gladly adjust, but as of this point I'm not sure how the body would ever be returned.

**How to reproduce**  
Below is my mock handler, the instantiation of the `MockHttpClient`, and the actual call performed in my test.

Mock Handler

```php
class MockQueue implements MockHandler
{
    /** @var \Closure */
    public $history;

    public $responses = [];

    public $options = [];

    public function __construct(array &$history, array $options = [])
    {
        $this->options = $options;

        $this->history = function ($request, $ops, $response) use (&$history, $options) {
            $history[] = [
                'request' => $request,
                'response' => $response,
                'options' => array_merge($this->options, $ops),
                'error' => []
            ];
        };
    }

    public function append($response): void
    {
        $this->responses[] = $response;
    }

    public function count(): int
    {
        return count($this->responses);
    }

    public function __invoke($method, $url, $options)
    {
        if (empty($this->responses)) {
            throw new \OutOfBoundsException("Mock queue is empty");
        }

        $h = $this->history;
        $h([
                'method' => $method,
                'url' => $url
            ] + $options,
            $options,
            $response = array_shift($this->responses)
        );

        return $response;
    }
}
```

MockHttpClient instantiation

```php
public function getClient(array $options = [])
{
   $this->mockHandler = new MockQueue($this->history, $options);

   return new MockHttpClient($this->mockHandler, $options['base_uri'] ?? null);
}
```

Call in test

```php
$formData = new FormDataPart(
    [
        'first' => 'value',
        'second' => 'another',
        'third' => DataPart::fromPath('./tests/helpers/text-file.txt')
    ]
);

$this->client->request('POST', '/woeiw', [
    'headers' => $formData->getPreparedHeaders()->toArray(),
    'body' => $formData->bodyToIterable()
]);
```

**Possible Solution**  

It looks like the `normalizeBody($body)` method of the `HttpClientTrait` is wrapping the generator in a closure with the following:

```php
if ($body instanceof \Traversable) {
    $body = function () use ($body) { yield from $body; };
}
```

More or less, I'm not sure the traversable is reachable now, inside this closure.

**Additional context**  

If the returned closure is `var_dump`ed, the following is shown:

```bash
class Closure#3284 (1) {
    public $static =>
      array(1) {
        'body' =>
          class Generator#3282 (0) {
        }
    }
}
```

If the closure is invoked it always returns a blank string.

Thanks

**Comment by nicolas-grekas** [comment]
Are you trying to read the body after the request has been sent?
If yes, this couldn't work, because the body is not rewindable.
What you might want to do is iterate over the request body before passing it to the request method.
To help, you can call `HttpClientTrait::prepareRequest()` to normalize the `body` option, then take inspiration from `NativeHttpClient::getBodyAsString()` to turn closures into strings.

**Comment by adamkelso** [comment]
I have been trying to use the body after the request, because that's when the mockResponseCallback (the mock handler above) is called by the `MockHttpClient`. However, I can try wrapping the `MockHttpClient` in an anonymous class to override the `request` method. In the override, I can clone the generator for later use and then pass it off to the provided `request` method.

I only do this because I want users to be able to use the mock client returned from my library exactly like is recommended in the docs. So, it needs to be able to be used like the last example in [this section](https://symfony.com/doc/current/components/http_client.html#uploading-data).

**Comment by adamkelso** [comment]
Ok, overriding the `request` method seems to do the trick. Closing this issue as solved.
