### ISSUE TITLE
[Messenger] Dynamically subscribe to message on bus

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#33304]
It would be great if I could dynamically subscribe to a message that is dispatched on a bus.

In my current project, we use [SimpleBus](https://github.com/SimpleBus). SimpleBus supports a way to dynamically add middlewares on an already constructed MessageBus ([MessageBusSupportingMiddleware](https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/MessageBusSupportingMiddleware.php)).

It allows me to subscribe to a specific message in runtime, just before I trigger something.

```php
final class SimpleBusEventBus
{
    /**
     * @var EventBus
     */
    private $eventBus;

    public function __construct(EventBus $eventBus)
    {
        $this->eventBus = $eventBus;
    }

    public function onEvent(string $event, callable $callable) : void
    {
        $this->eventBus->appendMiddleware(new class($event, $callable) implements MessageBusMiddleware {
            private $event;
            private $callable;

            public function __construct(string $event, callable $callable)
            {
                $this->event = $event;
                $this->callable = $callable;
            }

            public function handle($event, callable $next) : void
            {
                if (get_class($event) === $this->event) {
                    call_user_func($this->callable, $event);
                }

                $next($event);
            }
        });
    }
}

$this->eventBus->onEvent(SomethingHappened::class, function (SomethingHappened $event) {
    echo "Something happened";
});

$this->commandBus->handle(new DoSomething());
```

Would it be possible to do the same for Symfony Messenger?

Either by allowing to alter the middlewares on a constructed bus, or to provide a way to dynamically listen to certain messages on a bus.

**Comment by Tobion** [comment]
Why do you need it to be dynamic? What's the use-case?

**Comment by ruudk** [comment]
For example in a console command. I want to loop over a list of items, and trigger a command that creates 0 or 1-10 entities for that item. On the top I want to subscribe to the event that is emitted every time that entity is created, so that I can log whenever something is created.

**Comment by ro0NL** [comment]
why wouldnt you log from a handler? Im not sure coupling with dynamic runtime is a smart move :thinking:

**Comment by ruudk** [comment]
I can add logs to the handler, but when I'm in a Console command, I want to write a custom message with `OutputInterface`.

I will create my own Middleware that deals with this :) Thanks.

**Comment by ro0NL** [comment]
you can tag the handler also a console command listener, then you can obtain the current command.
