### ISSUE TITLE
WebTestCase: a 500 error doesn't make the PHPUnit test to fail

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony#33305]
**Symfony version(s) affected**: 4.3 (at least)

**Description**  

In the context of a functional test, if the tested page throws an exception, it is silenced by Symfony. Instead of having a failing PHPUnit test, the error page (with the ghost) is generated and no exceptions are thrown. This lead to uncaught exceptions, or cryptic errors at the following assertion. 

**How to reproduce**  

```php
<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ItemControllerTest extends WebTestCase
{
    public function testCreateItem(): void
    {
        $client = static::createClient();
        $client->request('GET', '/page-throwing-an-exception');
        // This test is green, but shouldn't
}
```

**Possible Solution**  

Throw instead of generating the error page when in the context of a functional test.

**Comment by stof** [comment]
Well, `$client->request` does not perform any assertion. So what you have here is a test verifying nothing.

the WebTestCase already has a method to assert that the response is successful.

**Comment by dunglas** [comment]
Yes, but it shouldn't return a response at all, that's the issue. The PHP exception thrown by the controller or whatever other part should (and was in previous versions IIRC) not be silenced.

**Comment by stof** [comment]
Why shouldn't it return a response at all ? You ask for an HTTP response, and a 500 response is one such response. some projects may want to perform assertions on non-successful responses too, and throwing would forbid that as they would never get access to the response.

Note that this is not new in 4.3. this was already the case in 3.x (and maybe even in 2.x but I don't remember)

**Comment by fabpot** [comment]
I don't understand the issue. The client simulates a browser, so you get the same thing. You should test for a 500 status code here. I doubt that the behavior changed recently.

**Comment by dunglas** [comment]
Indeed you get the same thing than with a browser, but you're in the context of a functional test: except in the very specific case of testing the generated error page, your server should never return a 500 (or it's a bug).
Also:

* consequently it's very difficult to access to the stack trace to figure what's the underlying issue
* the analogy with a real environment is not exact in this context because the ghost page is only displayed in debug mode, it will never be displayed in production, so a real browser should never see it

In term of Developer Experience, it's a weird behavior, making debugging less easy.
Hasn't this behavior changed with #27519?

**Comment by xabbuh** [comment]
@dunglas This definitely has been the way it is even in 2.x.

**Comment by javiereguiluz** [comment]
Let's close this because the current behavior is the expected one and most contributors agree with it. Thanks!
