### ISSUE TITLE
Unable to decorates router services

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#33303]
**Symfony version(s) affected**: 4.3

**Description**  

**How to reproduce**  

I'm trying to decorate the UrlMatcher to do some custom matching. My xml looks like this:
```
<service id="app.localization.routing.url_matcher" class="App\LocalizationBundle\Routing\UrlMatcher" decorates="Symfony\Component\Routing\Generator\UrlGeneratorInterface">
            
</service>
```
I tried a number of variations and could not get it to work at all. Symfony still falls back to the `Symfony\Component\Routing\Matcher\UrlMatcher` class.

I even tried to add the inner argument as instructed on [Stackoverflow](https://stackoverflow.com/questions/55468435/symfony-4-2-how-to-decorate-the-urlgenerator) but that doesn't work as well.

**Comment by maxhelias** [comment]
The decorates service `Symfony\Component\Routing\Generator\UrlGeneratorInterface` must be `Symfony\Component\Routing\Matcher\UrlMatcherInterface`.

And you can inject the original service like this :
```
<argument type="service" id="app.localization.routing.url_matcher.inner"/>
```

**Comment by yellow1912** [comment]
Hello @maxhelias,

It was a typo when I posted the question, sorry. I double checked and the configuration in the xml is correct but it still doesn't seem to work. Is there any way I can debug it?

**Comment by stof** [comment]
that's because the router service is named `router` in FrameworkBundle. `Symfony\Component\Routing\Generator\UrlGeneratorInterface` is only an autowiring alias. Decorating that one will not impact at all the many places referencing the router by its main name (including all places using the router in the core).

**Comment by xabbuh** [comment]
closing here as explained by @stof

**Comment by yellow1912** [comment]
@stof thank you very much. One thing that gets me really confused is that the router is aliased like this:

```
<service id="router" alias="router.default" public="true" />
<service id="Symfony\Component\Routing\RouterInterface" alias="router" />
<service id="Symfony\Component\Routing\Generator\UrlGeneratorInterface" alias="router" />
<service id="Symfony\Component\Routing\Matcher\UrlMatcherInterface" alias="router" />
<service id="Symfony\Component\Routing\RequestContextAwareInterface" alias="router" />
```

Does it mean I can only decorate the router and not the generator and matcher separately? I'm always confused about this alias concept.

**Comment by stof** [comment]
well, `router.default` is an internal private alias, not something that gets referenced outside (probably a legacy from early days of Symfony without `decorates` support to make manual decoration easier).

But the matcher and generator don't exist separately anyway. We use the same object implementing both interfaces.

**Comment by yellow1912** [comment]
@stof thank you for your explanation. So after looking at the code is it right to assume that:

1. To decorate the router when using with the framework bundle I should decorate 'router' service.
2. To use a custom url matcher I should replace/override the 'router' service definition since the url matcher class is passed in the definition as a full class name.

**Comment by multifinger** [comment]
@stof In symfony 4.4 I'm trying to extend router functionality by decorating it like this:
```
#config/services.yaml
services:
...
    app.router:
        class: App\Service\Router
        decorates: 'router'
        arguments: ['@app.router.inner']
```
Where App\Service\Router decorates given router interface in constructor and uses it in all implemented methods. But with such configuration I got "No route found for ..." none of my previously configured and working routes. So, how can I decorate router? I've spent all day looking for examples and documentation, digging the code, etc. Still nothing worked for my. 
I realy want to add some features from symfony1.4 (object-properties-based url generation)

**Comment by chiqui3d** [comment]
same problem! :(

**Comment by yellow1912** [comment]
@multifinger I didn't see your message till now, but I ended up overriding the route loader:

```
<service id=my_router" class="MyApp\LocalizationBundle\Routing\Router" decorates="router">
            <tag name="monolog.logger" channel="router" />
            <tag name="container.service_subscriber" id="routing.loader" />
            <argument type="service" id="Psr\Container\ContainerInterface" />
            <argument>%router.resource%</argument>
            <argument type="collection">
                <argument key="cache_dir">%kernel.cache_dir%</argument>
                <argument key="debug">%kernel.debug%</argument>
                <argument key="generator_class">MyApp\LocalizationBundle\Routing\UrlGenerator</argument>
                <argument key="generator_dumper_class">Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper</argument>
                <argument key="generator_cache_class">null</argument>
                <argument key="matcher_class">MyApp\LocalizationBundle\Routing\UrlMatcher</argument>
                <argument key="matcher_dumper_class">Symfony\Component\Routing\Matcher\Dumper\CompiledUrlMatcherDumper</argument>
            </argument>
            <argument type="service" id="router.request_context" on-invalid="ignore" />
            <argument type="service" id="parameter_bag" on-invalid="ignore" />
            <argument type="service" id="logger" on-invalid="ignore" />
            <argument>%kernel.default_locale%</argument>
            <call method="setConfigCacheFactory">
                <argument type="service" id="config_cache_factory" />
            </call>
        </service>
```
