### ISSUE TITLE
[Messenger] Auto register all public method on handler

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#33316]
In the SimpleBus project we have a [AutoRegister compiler pass](https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/AutoRegister.php) that you can enable by adding `register_public_methods: true` to the tag.

It will then search for all public methods (next to `__invoke`) and tries to register them.

Right now, Symfony only supports either `__invoke` or the usage of `MessageSubscriberInterface`. 

I don't want to use anything from Symfony in my domain handlers and subscribers. Therefore, it's hard for me to create a handler that handles multiple commands.

Is there a specific reason to not implement [AutoRegister compiler pass](https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/AutoRegister.php)? If not, would you be OK if I would create a PR to add this functionality? Better to discuss first before I write the code :)

**Comment by Tobion** [comment]
I don't see the value of this. You can just use separate handler classes which the better practice in my eyes anyway.

**Comment by ruudk** [comment]
I agree that a handler should only do one thing. But there are cases where it's extremely convenient to subscribe to 2 or 3 events. For example, you have a WebhookSubscriber that notifies an external system on certain events. 

I guess I will create my own compiler pass for this behavior :)

**Comment by ro0NL** [comment]
you could handle multiple message from `__invoke` ... and tag them manually.

**Comment by ruudk** [comment]
True, but the downside of that is that you loose type-hinting on the parameter.

**Comment by ro0NL** [comment]
i find that flexible :) (note you can still rely on `object` or a shared contract of your own)

```php
function __invoke(object $msg): void {
    if ($msg instanceof Some) {
        $this->handleSome($msg);
    }
}
```

you'll get the idea :)

**Comment by jwillp** [comment]
@ruudk Really curious how did you ended up doing it? I would like to achieve a similar thing

**Comment by ruudk** [comment]
I gave up on the idea, and removed the few handlers that subscribed to multiple messages.

**Comment by jwillp** [comment]
@ruudk, Alright thank you. I ended up implementing it using a compiler pass and a custom MessageHandlerMiddleware.
