### ISSUE TITLE
[Mailer] string variable named 'email' becomes WrappedTemplatedEmail object

### ISSUE THREAD

**Issue by AgenturSofa** [symfony/symfony#33310]
**Symfony version(s) affected**: 4.3.3

**Description**  
I'm trying to pass a variable named 'email' to Twig via ->context(). Causing preg_match() in Generator/UrlGenerator.php:179 to fail with "Warning: preg_match() expects parameter 2 to be string, object given"
Debugging the email var shows, that it somehow became a WrappedTemplatedEmail object.

**How to reproduce**  
```php
$message = (new TemplatedEmail())
                ->subject('...')
                ->from('...')
                ->to($user->getEmail())
                ->textTemplate('...')
                ->context([
                    'email' => $user->getEmail(),
                    'identifier' => urlencode($identifier),
                ])

            $mailer->send($message);
```

**Possible Solution**  
Renaming the variable 'email' to 'mail' fixes the issue.

**Comment by michaljusiega** [comment]
Before your Twig context will be merged, the email variable already exists in available variables. This is not issue but it is a creation's intension. Instead this use like in doc: https://symfony.com/doc/current/mailer.html#html-content

**Comment by fabpot** [comment]
`email` is indeed a special variable that you must not override. See #33323, we will throw an exception in 4.4 in such a situation to make debugging easier.

**Comment by AgenturSofa** [comment]
Thank you both for your comment.
I had the docs open on the right page, but still managed to miss the crucial part.

Throwing an exception would help a lot, as using the variable name 'email' in an email context seems like a good idea... :)
