### ISSUE TITLE
Symfony coding standard & PSR-12

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#33324]
**Description**  
[PSR-12](https://www.php-fig.org/psr/psr-12/) just got accepted.

Is there a will from Symfony to respect this standard ? Cause actually Symfony does not.

I think, for example, about the following rule from the [Symfony coding standard](https://symfony.com/doc/current/contributing/code/standards.html)
```
Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator;
```
In conflict for the concatenation with the `PSR-12` rule
```
All binary arithmetic, comparison, assignment, bitwise, logical, string, and type operators MUST be preceded and followed by at least one space:
```

**Comment by fabpot** [comment]
We won't change our way. That does not make any difference and would be huge pain to fix, merge, resolve conflicts, ...

**Comment by gmponos** [comment]
Well basically @fabpot the main question is if there is any intention of updating your coding standard to match the new features of the language.

Some:
- typehints, 
- declare strict types. Do we use it and where?
- anonymous classes etc etc.. 
- use statements (like `use const` or `use function`) are they grouped or not

Maybe some of these new things could be in line with PSR-12 to help in a better transition from one project to the other

WDYT?

**Comment by Jean85** [comment]
PHP CS Fixer does not support yet PSR-12: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502

Maybe it's a good occasion to get some PR done for the Hacktoberfest? :smile:
