### ISSUE TITLE
[Messenger] Fanout message per handler to the transport

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#33328]
Given you have 4 handlers that are interested in `SomethingHappenedEvent`. 
All 4 handlers use the `async` transport (e.g. RabbitMQ)
You have a retry strategy enabled.
The `SomethingHappenedEvent` is dispatched onto the `event.bus`
When a consumer consumes the message it will invoke all 4 handlers. 
Handler number 3 throws an exception.
The message will be marked as failed and automatically retried some time later.
The same 4 handlers are invoked.
Handler 1, 2 and 4 already did the work but are invoked again.
Handler number 3 throws an exception.
Repeat...

I think the problem is that there is only 1 message published to the transport. In my opinion, there should be 4 messages published to the transport. For every handler one specific message. They can even be on separate queues. 

At my company, we're using SimpleBus with RabbitMQ and we've had the same broken behavior in our production application. That lead to many weird situations where things were invoked multiple times. Then we found out that it was related to failure handling and retries. We fixed that by changing the producer's side. It now looks at all handlers that are interested and creates specific messages for each of them.

**Comment by ruudk** [comment]
It seems that the invocation of all 4 handlers is wrapped inside 1 single `DoctrineTransactionMiddleware` transaction. That works fine when your handler is only touching the database. But what if it connected to Stripe and created a refund via the API? The handler responsible for that was successful, but the database modifications are now rolled back completely.

Next time the message gets retries, the same thing will happen.

Solution: `DoctrineTransactionMiddleware` should be wrapped around a single handler invocation.

**Comment by Tobion** [comment]
The DoctrineTransactionMiddleware is added by you. It should not be there by default. It's up to you what you do with it.

**Comment by ruudk** [comment]
Interesting... the `DoctrineTransactionMiddleware` is the cause of this weird behavior! When I disable it, it will only retry the failed one. But I feel that DoctrineTransactionMiddleware is a must have to enable on my bus. 

Turns out this behavior is actually how it's meant to be: 
https://github.com/symfony/symfony/blob/610a4e978f081eba3ba34f4b48181711f5eedfd2/src/Symfony/Bridge/Doctrine/Messenger/DoctrineTransactionMiddleware.php#L39-L43
It was added by you in https://github.com/symfony/symfony/pull/32154.

I think this doesn't work as middleware, and that it should be wrapped around https://github.com/symfony/symfony/blob/610a4e978f081eba3ba34f4b48181711f5eedfd2/src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php#L72-L73

Scenario: if one of your handlers connects triggers actions on an external API, and an unrelated handler crashes, you get really weird things.

**Comment by ruudk** [comment]
The `getSenders` method could return handlers wrapped in a transactional closure:
https://github.com/symfony/symfony/blob/610a4e978f081eba3ba34f4b48181711f5eedfd2/src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php#L88-L97

**Comment by B-Galati** [comment]
A handler behavior should be idempotent no? So that it does not cause any issue to have the same message multiple times.

**Comment by ruudk** [comment]
> A handler behavior should be idempotent no? So that it does not cause any issue to have the same message multiple times.

That's easier said than done when you are working with external systems. Why should the failure of an unrelated handler be the cause of a retrying of a successful message?

**Comment by B-Galati** [comment]
>Why should the failure of an unrelated handler be the cause of a retry of a successful handler?

@ruudk I do agree with you on that point.

But IMHO, idempotency is something required when working with async processing (Or WebHook for example). If it's external you cannot be sure of the remote system behavior. 

Even if internal you cannot be sure you will not have to replay some messages some day because, for example, your RabbitMQ infra crashed and you lost messages along the way.

**Comment by ruudk** [comment]
@B-Galati You are totally right on that and we do use idempotency keys to mitigate this. But imho, the failure of 1 handler should not impact the other handlers outcome. Also, if you think about an event, with multiple subscribers, the failure of 1 subscriber shouldn't impact the rest of the subscribers.

**Comment by Tobion** [comment]
I think this issue can be closed and seems highly related to #32436. Or are there some concrete todos?
In general I would not recommend to use the DoctrineTransactionMiddleware when you have several handlers for the same message and some don't use doctrine at all. Just do the transaction inside the handler that is relevant. Then the retry will only execute the failed handlers as expected.
