### ISSUE TITLE
[Cache] RedisTrait in 3.4 doesn't allow to override dbindex=0 with query

### ISSUE THREAD

**Issue by marforon** [symfony/symfony#33337]
**Symfony version(s) affected**: v3.4.*

**Description**  
RedisTrait in 3.4 doesn't allow to override dbindex=0 with query

**How to reproduce**  
Try to create a connection to Redis through [RedisTrait](https://github.com/symfony/cache/blob/3.4/Traits/RedisTrait.php). 
Use dsn which contains dbindex parameter. (e.g. `redis://localhost:6379?dbindex=5`).
Connection is always created with select to db index 0.

**Possible Solution**  
https://github.com/symfony/cache/blob/3.4/Traits/RedisTrait.php#L100-L108 in this part using `array_merge` would resolve the issue.
Proposal:
```
$params += [
            'host' => isset($params['host']) ? $params['host'] : $params['path'],
            'port' => isset($params['host']) ? 6379 : null,
            'dbindex' => 0,
        ];
        if (isset($params['query'])) {
            parse_str($params['query'], $query);
            $params = array_merge($params, $query);
        }
```

**Comment by nicolas-grekas** [comment]
can you try `redis://localhost:6379/5`?

**Comment by marforon** [comment]
@nicolas-grekas it doesn't help, it just creates connection with incorrect parameter.
![image](https://user-images.githubusercontent.com/19769026/63691943-d8922880-c810-11e9-8b40-8d64c911e99f.png)

**Comment by nicolas-grekas** [comment]
Great, so it's been implemented as a new feature. Thanks for the feedback.
