### ISSUE TITLE
[Feature Request]Redirect back in controller

### ISSUE THREAD

**Issue by TangMonk** [symfony/symfony#33338]
You can redirect back to previous url in controller, just like in Ruby On Rails:

```
def show
   redirect :back
end
```

In symfony maybe can archive same way:

```
public function show(){
  return $this->redirectBack();
}
```

**Comment by ABGEO07** [comment]
Hello,

I will try to start if we need this feature :)

**Comment by linaori** [comment]
How would this feature work? Because there's no reliable way of determining where to send back to as the referrer header is not foolproof

**Comment by ABGEO07** [comment]
@linaori we can get it from `$_SERVER['HTTP_REFERER']`.

**Comment by linaori** [comment]
That's not reliable. If you expect a return to the previous page, you'd need something reliable. That value can be spoofed or hidden.

**Comment by ABGEO07** [comment]
We can save the previous URL in the session and, if `HTTP_REFERER` is empty, get it from there.

**Comment by linaori** [comment]
If you do this, make sure it's behind a feature flag, as it would make the session a requirement on each page, while it might not be necessary. It's also important to not save it on requests that had a non 2xx status.

**Comment by stof** [comment]
the session is not working for that either: if you open 2 tabs, they will share the same server session, but not the same browser history.

Note that Rails (suggested as inspiration for the feature) implements it based on the Referer header, with a fallback location and an optional filtering of the allowed host for the Referer (using the fallback location if the filter rejects the referer).

**Comment by nicolas-grekas** [comment]
Closing as the corresponding PR has been rejected.

**Comment by mapodev** [comment]
Are you kidding me? Laravel has that already.
