### ISSUE TITLE
[Form] Pre-selecting values in nested forms no longer works

### ISSUE THREAD

**Issue by keichinger** [symfony/symfony#33346]
**Symfony version(s) affected**: 4.3.3

**Description**  
The Form component will no longer correctly set the current/selected/active data for form elements nested under a `FormType` element.

**How to reproduce**  
With the given entity structure

```php
// Entities

class EntityA
{
    /**
     * @var EntityB
     *
     * @ORM\ManyToOne(targetEntity="EntityB", inversedBy="entityAs")
     */
    private $entityB;

	// more fields…
}

class EntityB
{
	/**
     * @var EntityA[]|Collection
     *
     * @ORM\OneToMany(targetEntity="EntityA", mappedBy="entityB")
     * @ORM\OrderBy({"…": "ASC"})
     */
    private $entityAs;

	// more fields…

	public __construct ()
	{
		$this->entityAs = new ArrayCollection();
	}
}
```

The following will no longer work as in previous versions (or without nesting):

```php
class EntityAForm extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm (FormBuilderInterface $builder, array $options) : void
    {
        $builder
            ->add("_someUnmappedProperty", FormType::class, [
                "label" => "…",
                "required" => false,
                "inherit_data" => true,
            ]);

        $category = $builder->get("_someUnmappedProperty");
		// …and adding other fields…

        $builder
            ->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) : void
            {
                /** @var EntityA $entityA */
                $entityA = $event->getData();
                $category = $event->getForm()->get("_someUnmappedProperty");

                $category
                    ->add("entityB", EntityType::class, [
                        "label" => "…",
                        "class" => EntityB::class,
                        "placeholder" => "…",
                        "help" => "…",
                        "query_builder" => function (EntityRepository $repository) use ($entityA)
                        {
                            return $repository->createQueryBuilder("entityB")
                                ->andWhere("entityB.entityA = :entityA")
                                ->setParameter("entityA", $entityA->getEntityB());
                        },
                        "choice_label" => "…",
                    ]);
            });
    }

    /**
     * @inheritDoc
     */
    public function configureOptions (OptionsResolver $resolver) : void
    {
        $resolver
            ->setDefaults([
                "data_class" => EntityA::class,
            ]);
    }
}
```

Now if we slightly change the form nesting, it'll work without any additional changes:

```php
class EntityAForm extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm (FormBuilderInterface $builder, array $options) : void
    {
        $builder
            ->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) : void
            {
                /** @var EntityA $entityA */
                $entityA = $event->getData();

                $event->getForm()
                    ->add("entityB", EntityType::class, [
                        "label" => "…",
                        "class" => EntityB::class,
                        "placeholder" => "…",
                        "help" => "…",
                        "query_builder" => function (EntityRepository $repository) use ($entityA)
                        {
                            return $repository->createQueryBuilder("entityB")
                                ->andWhere("entityB.entityA = :entityA")
                                ->setParameter("entityA", $entityA->getEntityB());
                        },
                        "choice_label" => "…",
                    ]);
            });
    }

    /**
     * @inheritDoc
     */
    public function configureOptions (OptionsResolver $resolver) : void
    {
        $resolver
            ->setDefaults([
                "data_class" => EntityA::class,
            ]);
    }
}
```

This has happened to me now multiple times with different form types, so it's definitely not a problem where I might accidentally filter out the active value using the `query_builder` property. This is reproducible with a `CheckboxType` as well. I'm pretty sure that it's unrelated to the form types but an unintentional breaking change.

**Comment by xabbuh** [comment]
Could you please create a small example application that allows to reproduce your issue so we are able to debug the cause?

**Comment by keichinger** [comment]
@xabbuh Thanks for your quick reply. Sure, I'll create an example repo first thing in the morning.

**Comment by keichinger** [comment]
Good morning :) I've created https://github.com/keichinger/symfony-forms-pre-select-issue 

In the process of creating this reproducer, I've added a third entity (`EntityC`) in order to better reflect my current project that I was originally having these issues with. In the migration I've added some test data so you don't have to add them yourself.

When you've set up the project, just navigate to `/` and then on either the broken or the working form variant. Both routes and forms are working with the very same entity. The only difference between the two of them is the extra level of nesting that is provided by something like this:

```php
        $builder
            ->add("_someUnmappedPropertyThatIsBreakingFormsDataBindingInPostSetData", FormType::class, [
                "label" => false,
                "inherit_data" => true,
            ]);

		$nestedForm = $builder->get("_someUnmappedPropertyThatIsBreakingFormsDataBindingInPostSetData");
		$nestedForm->add("…");
```

If we remove the nested form, it's working as intended. Another workaround would be to explicitly set the `data` property to your current value.

If you're having any additional questions or problems with my reproducer, please let me know.

**Comment by xabbuh** [comment]
I fail to see how this could have worked before. Do you know in which version the exact same code has been worked before?

Anyway, if you update your `BrokenEntityAForm` to add the listener for the `PRE_SET_DATA` event, it will work as you expect it:

```php
$builder->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event) : void
{
    // ...
}
```

**Comment by keichinger** [comment]
We've been doing these kind of forms for many years. It may have been even possible in 2.x — 3.x and <4.3.3 for sure. I'd have to have a closer look at it tomorrow morning to pin down the exact breaking version.

Quickly searching in our (private) GitHub organisation for `POST_SET_DATA` shows 154 results with some files not touched for years (2016 and older).

**Comment by keichinger** [comment]
I might need to correct an earlier statement of mine: This particular scenario may have never properly worked, at least not in 4.3.0, 4.2.*, 4.1.* and 3.4.* (these were the versions that I was testing locally). In all of these versions `BrokenEntityAForm` was not working inside a `FormEvents::POST_SET_DATA` handler. However, `WorkingEntityAForm` was working fine — as expected.

From this point on I'm not longer sure whether this is an actual bug. Reading through https://symfony.com/doc/current/form/events.html#pre-populating-the-form-formevents-pre-set-data-and-formevents-post-set-data you may naturally expect it to work.

How do we want to proceed here?

**Comment by xabbuh** [comment]
That's not a bug, but how data mapping works when the `inherit_data` option is used. If you feel like that can be clarified in the docs, please open a PR in its repository. Thank you for understanding.
