### ISSUE TITLE
Cannot install symfony/translation:4.3.4

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#33347]
**Symfony version(s) affected**: 4.3.4
**Description**  

```bash
  Problem 1
    - Installation request for symfony/translation 4.3.4 -> satisfiable by symfony/translation[v4.3.4].
    - symfony/translation v4.3.4 requires symfony/translation-contracts ^1.1.6 -> satisfiable by symfony/translation-contracts[1.1.x-dev] but these conflict with your requirements or minimum-stability.
```

**How to reproduce**  

Try to update to latest `4.3.4` Symfony, after update `symfony/translation` is still on `4.3.3` version.

**Possible Solution**  

Seems like there need to be new tag for https://packagist.org/packages/symfony/translation-contracts

**Comment by nicolas-grekas** [comment]
should be good, thank you @fabpot

**Comment by tarlepp** [comment]
nice, thanks to you both @nicolas-grekas and @fabpot !
