### ISSUE TITLE
ServiceSubscriberTrait is incompatible with AbstractController

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/symfony#33355]
**Symfony version(s) affected**: 4.3.3

**Description**  
On PHP 7.3 fatal error occurs on using Symfony\Contracts\Service\ServiceSubscriberTrait in controller class that extends Symfony\Bundle\FrameworkBundle\Controller\AbstractController:

> PHP Fatal error:  Symfony\Bundle\FrameworkBundle\Controller\AbstractController and Symfony\Contracts\Service\ServiceSubscriberTrait define the same property ($container) in the composition of App\Controller\Api\v1\Project\DvrChannelController. However, the definition differs and is considered incompatible.

**How to reproduce**  
```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\Service\ServiceSubscriberTrait;

class TestController extends AbstractController
{
    use ServiceSubscriberTrait;
}

```
Then run cache:clear command.

**Possible Solution**  
Make $container property **protected**.

**Comment by nicolas-grekas** [comment]
The property is private in the trait but protected in the abstract class, isn't it?
I think we should make the one in the abstract class private instead.
Since this would be a BC break, we should first deprecate the property in 4.4
If that makes sense to you, would you be up for a PR?

**Comment by nicolas-grekas** [comment]
>  I think we should make the one in the abstract class private instead.

Hum, actually this would affect too much code out there. Better rename the property in the trait then? It's not supposed to be used directly anyway.

**Comment by a-menshchikov** [comment]
I agree that making the property in abstract class as private will affect much code, but then decision to rename the property in the trait looks like temporary patch and not solves the root cause.

I think that we should solve current problem by the shortest way (rename property looks like that) and create a new issue for make container property in the abstract class as private. In the distant future, when it will be done, trait property will be able to be renamed back.
