### ISSUE TITLE
Class name conflict with Symfony Bridge proxy manager and Ocramius ProxyManager

### ISSUE THREAD

**Issue by crmpicco** [symfony/symfony#33364]
**Symfony version(s) affected**: 3.4.31

**Description**  
I am experiencing a warning when running `composer dump-autoload --optimize` in my application and it is happening because of my apparent use of the proxy manager along with the Symfony bridge.

**How to reproduce**  
```
$ composer dump-autoload --optimize
Generating optimized autoload files

Warning: Ambiguous class resolution, "ProxyManager\Generator\Util\ProxiedMethodReturnExpression" was found in both "/private/var/www/crmpicco/symfony/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression.php" and "/private/var/www/crmpicco/symfony/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/Legacy/ProxiedMethodReturnExpression.php", the first will be used.

Generated optimized autoload files containing 8939 classes 
```
I am using Proxy-Manager 2.2.3:

```
$ composer show -i | grep proxy
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
ocramius/proxy-manager               2.2.3                 A library providing utilities to generate, instantiate and generally operate with Object Proxies
```

**Additional context**  
I reported this on Ocramius' Github account, however he suggested it is a Symfony issue and pointed me in this direction. https://github.com/Ocramius/ProxyManager/issues/489#issuecomment-525166301

**Comment by stof** [comment]
this is related to https://github.com/symfony/symfony/pull/32992

**Comment by stof** [comment]
@Ocramius any chance to backport the PHP 7.4 compat fix (avoiding the deprecation warning) to older ProxyManager versions (which tell composer they support PHP 7.4) instead of forcing to implement such hack in Symfony to workaround the issue ?

**Comment by Ocramius** [comment]
@stof newer ProxyManager releases already support PHP 7.4 in the stable 2.x releases
