### ISSUE TITLE
[RFC][Idea]Console doctrine:schema:update fallback

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony#33367]
**Description**  
I would like to create an alternative to fallback of this command if the database is not created. For example by putting the command to create it or directly ask if you want to create it. This avoids wasting time. 

What do you think of that? 

**Example**  
![image](https://user-images.githubusercontent.com/10236869/63837396-b36df900-c97b-11e9-97c0-f6db46a9c265.png)
Replace By 
Unknown database `symfony`
Do you want to run "doctrine:database:create" instead?  (yes/no) [no]:
OR 
You need use this command `php bin/console doctrine:database:create` or create your database in a different way.

**Comment by fancyweb** [comment]
The discussion should be opened on https://github.com/doctrine/DoctrineBundle. Symfony does not manage the Doctrine bundle anymore.

About the subject, you can eventually always use `php bin/console doctrine:database:create --if-not-exists` before using the schema update command to ensure the database exists.

But actually don't use the schema update command. Drop / recreate the database in the early stage of development and then use migrations.

**Comment by stof** [comment]
Actually, this even belongs to Doctrine DBAL itself, as that's where the command is implemented.

**Comment by TheGarious** [comment]
Oh ok, sorry i create this issue in a right repository. I want just review this fallback.

**Comment by TheGarious** [comment]
Following [issue](https://github.com/doctrine/DoctrineBundle/issues/1012)
