### ISSUE TITLE
i18n routing

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#33366]
**Description**  
I miss some routing functionality in symfony for i18n.
I've got an website that got routing based on the locale but you can't add an different host for example 'en' that it then needs to redirect to an .com domain

At the moment only the following annotation is possible:
```
    /**
     * @Route({
     *     "en": "/",
     *     "nl": "/nl"
     *    },
     *    methods={"GET"},
     *    name="homepage",
     *   schemes={"https"},
     * )
     * @Template("homepage/index.html.twig")
     */
```

When i add the host property it counts on all locale routes.

**Example**  
The locale route values are now only expecting an string but it would be create if you could add an array there like:

```
    /**
     * @Route({
     *     "en": {,
     *     "/",
     *      host="domain.com",
     *      redirect=true
     *     }
     *     "nl": "/nl",
     *      host="domain.nl",
     *      redirect=true
     *     }
     *    },
     *    methods={"GET"},
     *    name="homepage",
     *   schemes={"https"},
     * )
     * @Template("homepage/index.html.twig")
     */
```
The values that are given in the local value will overwrite the main settings so you could have different hosts or maybe requirements for each locale route.

The redirect setting would be an new one that will redirect the user with an 301 to the correct host so when someone goes to domain.com/nl it will redirect to domain.nl/nl or when the path is empty for 'nl' it would just go to domain.nl

Another case that would be great that you can stack multiple locales in just one annotation for example dutch has multiple official locales which is for many languages so the following would be nice as well when you can add multiple same routes for different locales:
```

    /**
     * @Route({
     *     "en": {,
     *     "/",
     *      host="domain.com",
     *      redirect=true
     *     }
     *     "nl|nl_NL|nl_BE": "/",
     *      host="domain.nl",
     *      redirect=true
     *     }
     *    },
     *    methods={"GET"},
     *    name="homepage",
     *   schemes={"https"},
     * )
     * @Template("homepage/index.html.twig")
     */
```

In this case you can have one code for multiple websites

**Comment by XWB** [comment]
Good suggestion. JMSI18nRoutingBundle has support for different host names and it is a really useful feature.

**Comment by dvdknaap** [comment]
@XWB I saw this bundle as well but in my opinion this should be in symfony as default.

**Comment by Guite** [comment]
refs #30617

**Comment by Tobion** [comment]
Closing as duplicate.
