### ISSUE TITLE
[RFC][HttpFoundation][DX] JsonResponse "noContent" factory method

### ISSUE THREAD

**Issue by kunicmarko20** [symfony/symfony#33371]
**Description**
Not sure about other users but I have been copy-pasting this a lot:

```
return JsonResponse::create(null, JsonResponse::HTTP_NO_CONTENT);
```

I was thinking if it would be useful if we had an additional factory method that would cover this:

```
return JsonResponse::noContent();
```

Wanted to ask before doing a PR, also this could be a good first contribution for someone.

**Comment by linaori** [comment]
Sounds like a good idea to me, especially because I didn't consider the existence of `HTTP_NO_CONTENT`. Meaning I've always done `new JsonResponse(null)`, not correcting the status code.

**Comment by faizanakram99** [comment]
@linaori same :joy:

**Comment by ostrolucky** [comment]
Concept is fine, but naming is not resolved, suggested name is not good one for factory methods

**Comment by ro0NL** [comment]
Do you rely on 204 AND a json content type? not sure its related :/

**Comment by stof** [comment]
well, returning a 204 will not send the `content-type` header, as there is not content anyway (see `Response::prepare`). So using a JsonResponse rather than a Response here is misleading anyway.

And I'm not sure we need to named constructor to create a 204 response (why for 204 and not for others then ?)

**Comment by Pierstoval** [comment]
I don't see the value of adding this to `JsonResponse`. Why not in `Response` instead?

**Comment by ro0NL** [comment]
ref #29326 and #30435 :)

**Comment by kunicmarko20** [comment]
>>> suggested name is not good one for factory methods

Agree.

Didn't think about the difference between JsonResponse and Response, it should be Response then.

>>> And I'm not sure we need to named constructor to create a 204 response (why for 204 and not for others then ?)

Was thinking about this one, it is a nice DX for developers, but it will open a door to this question "why don't other codes have it". The only answer I have is that 204 is special, the body of the response will always be `null`.

Since seeing this was already rejected 2 times, we can close this, no need to waste time again.
