### ISSUE TITLE
[Validator] Improve PropertyMetadata to allow dynamic properties

### ISSUE THREAD

**Issue by WolfgangDrescher** [symfony/symfony#33374]
**Description**  
When using a custom `MetadataFactory` where a model is passed as value, it is currently not possible to use the validator for dynamically generated properties that are accessed with the magical `__get()` method.

**Setup**
```php
// SomeController.php
$validator = Validation::createValidatorBuilder()
    ->setMetadataFactory(new CustomMetadataFactory())
    ->getValidator();
$validator->validate(new Model());
```

```php
use Symfony\Component\Validator\Constraints\NotBlank;
class CustomMetadataFactory implements MetadataFactoryInterface
{
    public function getMetadataFor($value)
    {
        $metadata = new ClassMetadata(ApplicationData::class);
        foreach($value->fields as $field) {
            $metadata->addPropertyConstraints('dynamicProp', [new NoBlank()]);
            // throws currently Symfony\Component\Validator\Exception\ValidatorException
            // in symfony/validator/Mapping/PropertyMetadata.php:40
        }
        return $metadata;
    }
    // ...
}
```

**Example** 
Neighter of the two following examples are currently possible:

```php
class Model
{
    public function __construct()
    {
        $this->dynamicProp = 'value';
    }
}
```

```php
class Model
{
    private $obj;
    public function __construct($obj)
    {
        $this->obj = $obj;
    }
    public function __get($name)
    {
        return $this->obj->prop[$name] ?? null;
    }
}
```

**Suggestion**
A possible solution could be to use `isset()` as well in the condition in `PropertyMetadata` to allow in the model an implementation with the magic `_isset` method. But since `PropertyMetadata` is using the `$class` name as a string instead of an object maybe this is the wrong approach.

```php
// symfony/validator/Mapping/PropertyMetadata.php
class PropertyMetadata extends MemberMetadata
{
    public function __construct(string $class, string $name)
    {
        if (!property_exists($class, $name) AND !isset($OBJECT->{$name})) {
            throw new ValidatorException(sprintf('Property "%s" does not exist in class "%s"', $name, $class));
        }
        // ...
    }
}
```

**Comment by stof** [comment]
metadata are stored per class, not per instance (which would forbid any caching, as it would miss in 100% of real cases). So we cannot look at which magic properties exist on a particular instance to validate the mapping..

**Comment by xabbuh** [comment]
I am closing here as this is likely not going to be happening for the reasons given by @stof. Thank you for suggesting it anyway @WolfgangDrescher.

**Comment by WolfgangDrescher** [comment]
Thank you @stof for processing this issue that fast and your explanation about the caching.

So it seems like there is currently no other way to validate *magic* classes than to validate each property individually on-the-fly. E.g. like @webmozart explained in https://github.com/symfony/symfony/issues/11895#issuecomment-55188164.
