### ISSUE TITLE
Reusable bundles service definition not used

### ISSUE THREAD

**Issue by kwinne** [symfony/symfony#33379]
**Symfony version 3.4.31**

**Description**
For my projects I have a lot of reusable bundles, these bundles all have services, subscribers, .. defined in an yml file and injected trough dependency injection. This all worked fine until the latest update (3.4.31). The services do not get injected into my project anymore (not visible with php bin/console debug:container).
This issue is resolved when I downgrade to 3.4.30

**How to reproduce**
Create an reusable bundle that contains an service (defined in an .yml file and injected trough DI). Include this bundle into your project and run _php bin/console debug:container_. the service will not be included in this list, even if it should be.

**Comment by xabbuh** [comment]
Are you sure your your services are public and that you do not need to pass the `--show-private` option to the `debug:container` command to see your services? Otherwise, can you please create a small example application that allows to reproduce the issue?

**Comment by xabbuh** [comment]
@kwinne Do you have any news for us?

**Comment by kwinne** [comment]
Hi,

Sorry for the late response, I had a few days off. 

I tried creating a new 3.4.31 project with some example structure with this problem, but everything seems to work fine.. 
So at this moment I cannot reproduce the problem, I will look further into my configurations etc to check if there is an problem there, its just strange I did not have any issues on .30

Anyways thanks for your time, if I find a way to reproduce it, I will let you know, but this project is also scheduled for an update to Symfony 4, so this issue will also be gone.

**Comment by xabbuh** [comment]
Thank you for the feedback. 👍 I am closing here for now. But please just leave a comment when you can reproduce and I will reopen here.
