### ISSUE TITLE
When pulling 4.3 branch and running composer install, symfony/contracts is pulled

### ISSUE THREAD

**Issue by pounard** [symfony/symfony#33372]
Isn't it a duplicate ?

Steps to reproduce:

```sh
git clone git@github.com:symfony/symfony.git
cd symfony
composer install
```

While installing, `symfony/contracts` is pulled in vendor dir, but is also present in `src/Contracts`, I think that `symfony/contracts`  should be registered in the `composer.json`'s `replace` section ?

I opened this as a support request and not an issue, because I'm not really sure this is a bug.

**Comment by nicolas-grekas** [comment]
That's on purpose, because contracts has a different versioning scheme.

**Comment by pounard** [comment]
Ok, thanks for the answer. Out of curiosity, how can you version differently with the code being in the same repository and following the same branches than Symfony itself ? Are you just rising the symfony/contacts version whenever you change it ? Are you spliting it like the component namespace but creating the releases from the split repo ?

**Comment by nicolas-grekas** [comment]
We version the split repository separately.

**Comment by pounard** [comment]
Ok, thanks for your answers, I don't see any reason to leave this opened.
