### ISSUE TITLE
[FunctionalTest] Client loosing mock service on form submit

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#33389]
**Symfony version(s) affected**: 4.3.4

**Description**  

If you set a service on a client in a functional test that was created using ```self::createClient()``` it will loose the mock service during form submission, causing the original client to be loaded.
From my understanding it should not do that.

**How to reproduce**  

I created a minimal test setup to replicate that behaviour here: https://github.com/KDederichs/container_test
Just run ```bin/phpunit```

**Comment by xabbuh** [comment]
By default, the kernel is rebooted for each request being performed. If you compare the different container instances that you obtain in your service (using `$client->getContainer()`), you should be able to see that they are actually different objects.

You could register a custom service replacing the original one in the `test` environment only (maybe disabling rebooting the kernel is only an option for you).

**Comment by KDederichs** [comment]
Ahh that explains it, I didn't know the rebooting happened, disabling it fixed my particular use case.
Thanks a lot!

**Comment by kamilwylegala** [comment]
@KDederichs How did you disable booting before every request of test client?

I wonder if it could speed up tests. I'm switching in my project from real http tests to tests based on `WebTestCase`. It takes 3 times longer to execute tests.

Deactivating boot before every test is considered a good practice?

**Comment by KDederichs** [comment]
@kamilwylegala I didn't disable the kernel booting completely, just the rebooting that occurs on between single client requests (to simulate different requests I assume) in that particular test to keep my mock object.
You can disable that particular behaviour by calling ```$client->disableReboot();``` 

You can't fully disable kernel booting in test cases though since you need an instance of the system to run your tests against.
In my case I found it helps when you boot the kernel once per test class (by overwriting the ```setUpBeforeClass```, ```tearDownAfterClass``` and ```tearDown``` methods but if that's useful in your case is something you have to decide.
