### ISSUE TITLE
Hidden console commands appear in "Did you mean .." list

### ISSUE THREAD

**Issue by m-vo** [symfony/symfony#33398]
**Description**  
Setting a command to `hidden` does not remove it from the list of suggested commands when the input is ambiguous. ("Did you mean one of these?"). That's of course a side effect of the command still being accessible and allowing commands to be shortened. 

It feels a bit inconsistent but I'm actually not sure what to change about this. So maybe add a note to the docs?
> Hidden commands behave the same as normal commands but they are no longer displayed in command listings, so end-users are not aware of their existence.

> Note: In case a user enters an ambiguous command that matches the name of a hidden command it will still get shown in the list of suggestions.

**How to reproduce**  
1. create a command `some:visible-command`
1. create second command `some:hidden-command` but configure it with `$this->setHidden(true)`
1. run `bin/console` &rarr; only the first command is visible in the list of commands ✓
1. run `bin/console some:` &rarr; 
  ``` Command "immoscout:" is ambiguous.  
  Did you mean one of these?          
      some:visible-command                
      some:hidden-command
```

**Comment by fabpot** [comment]
@m-vo To me, this is a bug, hidden should not leak anywhere. Would you like to work on a patch and submit a pull request to fix it?

**Comment by chalasr** [comment]
I guess this impacts lazy-loaded commands only, calling isHidden() requires instantiating the command. We probably need a new `hidden` attribute for the `console.command` tag.

**Comment by m-vo** [comment]
@fabpot Sure, I can give it a try. :+1: 

So we probably shouldn't allow hidden commands to be shortened at all (so that there is no ambiguity). Wdyt?

If we only strip them from a list of suggestions, we would get a strange behaviour (and indirectly also leak information):

```
$ console list
  Available commands:
    some
       some:visible-command  
    another
       [...]


$ console some:
  Command "some:" is ambiguous.  
  Did you mean one of these?          
      some:visible-command                
```

**Comment by fabpot** [comment]
Disallowing hidden commands to be shortened sounds like a good idea to me.
