### ISSUE TITLE
Ability to unset a default header added by HttpKernelBrowser / Client

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony#33393]
**Symfony version(s) affected**: 3.4+

**Description**  
There is currently no way to unset a HTTP request header through the BrowserKit `AbstractBrowser` / `Client`. This was requested before in https://github.com/symfony/symfony/issues/20306, but actually implementing an `unsetServerParameter` method would not help in our case.

The problem we're facing here (in API Platform) is that when we send a request using `HttpKernelBrowser` / `Client`:

https://github.com/symfony/symfony/blob/f1edae020d4109fcad3bd57810180a460aa4f20f/src/Symfony/Component/HttpKernel/Client.php#L136-L138

it calls (HttpFoundation) `Request::create` which adds some default request headers:

https://github.com/symfony/symfony/blob/f1edae020d4109fcad3bd57810180a460aa4f20f/src/Symfony/Component/HttpFoundation/Request.php#L309-L324

This includes the `Accept` header, which we need to be able to remove in order to test content negotiation scenarios where the client doesn't send the `Accept` header, thereby resulting in the use of the default media type.

**How to reproduce**  
We had been using a workaround to unset the `Accept` header in our test suite, basically:

```php
$client->setServerParameter('HTTP_ACCEPT', null);
```

The end result in the `HeaderBag` is:

```
array(1) {
  ["accept"]=>
  array(1) {
    [0]=>
    NULL
  }
}
```

However, fixes in `HeaderBag::get`, specifically the change made to this line:

https://github.com/symfony/symfony/blob/f1edae020d4109fcad3bd57810180a460aa4f20f/src/Symfony/Component/HttpFoundation/HeaderBag.php#L124

means that we get an empty string now instead of `null`.

**Possible Solution**  
So this breaks our test suite. We could find new workarounds, including checking for the case where the `Accept` header is an empty string (weird!), or overriding / extending some parts of the chain which sends the request in our test suite.

However, we're wondering if there might be a better way of fixing this for everyone. It was an ugly workaround in the first place.

This problem also affects `ApiTestCase` in API Platform, as the user would be unable to send a request without any of the default headers.

**Additional context**

**Comment by nicolas-grekas** [comment]
> However, fixes in HeaderBag::get, specifically the change made to this line [...] means that we get an empty string now instead of null.

this behavior change has been fixed, so that API Platform tests should now be alright, isn't it?
If confirmed, I think we can close as the use case is covered.

**Comment by teohhanhui** [comment]
Our test suite is fixed, yes, as we've implemented further workarounds.

However, the design problem remains. There is no way for the user to unset any of these default headers when they're using the `HttpKernelBrowser` / `Client` (from the `HttpKernel` component). It's a problem with our `Client` class in API Platform too, as it extends from the `HttpKernel` one.

It's very bad for DX when you don't have full control over the HTTP client you're using.

**Comment by nicolas-grekas** [comment]
"Very bad" is very subjective. What you can use today is the best the community achieved so far, thanks to them. About the future: PR welcome as usual :)

**Comment by teohhanhui** [comment]
Sorry if my comment came off as diminishing the work of the community. That was not my intention.

What I mean is, this is a feature request. :smile:

**Comment by dunglas** [comment]
For the record, API Platform is bite by this problem again. Our workaround doesn't work anymore because typehints have been added: https://github.com/api-platform/core/blob/89c0f30d188b0ff4f15302d1ee901353417663e3/features/bootstrap/HttpHeaderContext.php#L35
