### ISSUE TITLE
[Finder] [Iterator] [SortableIterator] closure causes unintended file lock in Windows

### ISSUE THREAD

**Issue by jspringe** [symfony/symfony#33400]
**Symfony version(s) affected**: 4.*

**Description**  
When using the `sortByName` on `Finder` there is an unintended file lock in Windows. This
does not release until the application ceases execution. This is due to the `__construct` building
an anonymous function and storing at as a property on `$sort`.

This gets in the way when doing a recursive directory deletion and causes a `Permission Denied` on Windows.

**How to reproduce**

    class FinderBug
    {
        public function unsortedFiles($path)
        {
            return iterator_to_array(Finder::create()->files()->ignoreDotFiles(true)->in($path)->depth(0), false);
        }
    
        public function sortedFiles($path)
        {
            return iterator_to_array(
                Finder::create()->files()->ignoreDotFiles(true)->in($path)->depth(0)->sortByName(),
                false
            );
        }
    
        public function deleteDirectoryRecursive($directory, bool $sorted = false)
        {
            $items = $sorted ? $this->sortedFiles($directory) : $this->unsortedFiles($directory);
    
            foreach ($items as $item) {
                if ($item->isDir()) {
                    $this->deleteDirectoryRecursive($item->getPathname(), $sorted);
                } else {
                    @unlink($item->getPathname());
                }
            }
    
            @rmdir($directory);
        }
    }
    
    $tempDir = __DIR__ . '/temp';
    mkdir($tempDir);
    mkdir($tempDir . '/foo');
    touch($tempDir.'/foo/1.txt');
    $bug = new FinderBug;
    $bug->deleteDirectoryRecursive($tempDir . '/foo', false);
    $bug->deleteDirectoryRecursive($tempDir, false);
    dump(is_dir($tempDir)); // Returns false as expected
    
    mkdir($tempDir);
    mkdir($tempDir . '/foo');
    touch($tempDir.'/foo/1.txt');
    $bug->deleteDirectoryRecursive($tempDir . '/foo', true);
    $bug->deleteDirectoryRecursive($tempDir, true);
    dump(is_dir($tempDir)); // Return true due to errors.

**Possible Solution**  
Don't store the closure as a property on `SortableIterator`. Instead make it a method. It's already noted that this is a potentially slow operation, and I don't believe making this a calculated on the fly value would really make any difference.

**Additional context**  
This is [related to a bug](https://github.com/laravel/framework/issues/27004) that has been chased for months in the Laravel Test Suite for Windows. I'm like 1 of 5 people who develop in PHP on Windows.. so it's been slow moving.

**Comment by jspringe** [comment]
[Here](https://github.com/jspringe/symfony/commit/ec47eed7ef8ea60310256fece215a16161fa186d) is what I had in mind.

**Comment by nicolas-grekas** [comment]
Please submit a PR so we can process the proposal :)

**Comment by jspringe** [comment]
Any particular branch?

**Comment by stof** [comment]
would using a static closure (binding the order as a variable) solve the issue ?

**Comment by jspringe** [comment]
Possibly. The "quick-fix" is to unset `$this->sort`, but the root of the problem, I believe, has to do with the reference to `$iterator` which actually holds the `SplFileInfo` references. If I'm understanding your proposal properly the static closure wouldn't have a reference to `$this` which should solve the issue.

**Comment by jspringe** [comment]
I've re-opened my PR. I hope I followed the guidelines properly. The one glaring omission are new tests. I explained the reasoning within the PR, but to reiterate, trying to make a failing test to prove this issue would require a Travis CI Windows instance, and I know from experience this will open a whole host of new issues.

I have a baseline that I can use if this is something is desired.

**Comment by jspringe** [comment]
For the record - the AppVeyor check self-cancelled and did not actually fail.

**Comment by nicolas-grekas** [comment]
Good catch, thanks for reporting and sending a PR!
