### ISSUE TITLE
BUG while using `symfony new`

### ISSUE THREAD

**Issue by annoying258** [symfony/symfony#33407]
**Symfony version(s) affected**: `Symfony CLI version v4.6.4 (Tue Aug 13 19:44:53 IST 2019)
`
**Description**  

Its really hard to create a new project with `symfony new`. As it tries to be `smart` when it needs to be `dumb` and vice versa. Also, lacks an option that it needs to hide its flaws from new users.

**How to reproduce**  

This issue surprised me when I tried to create a new project using symfony. First create the folder for the project, say `student`.
Then inside it initialize a git repo. Set up git config for that project only. Then from the parent directory do
`symfony new student` , it doesn't work. Then try `symfony new student --force` that also desn't work.

then I tried `symfony new -h` to see the options. Found that there is no --force option but `--no-git` option seemed useful.  But `symfony new student --no-git` also doesn't work.
Then I moved the .git folder to the parent directory, even though it might cause issues with git, and tried `symfony new student --no-git` and
`symfony new student` , but it didn't work.

Then I deleted the directory, and after that created it. `symfony new student --no-git` still didn't work.

**Possible Solution**  

See what laravel does with its `laravel new --force`  option and what `laravel new` does. Its more intuitive, and has less friction, no myopic premature optimizations.

I'm not sure, but maybe this is the starting point for laravel/installer https://github.com/laravel/installer/blob/master/src/NewCommand.php

**Additional context**  

Everything I tried, the output was `Project directory student is not empty`, even when the directory was empty.

**Comment by nicolas-grekas** [comment]
Closing as this is not related to symfony/symfony. Please submit on https://github.com/symfony/cli instead.

> [...] hide its flaws from new users [...] myopic premature optimizations [...]

Honestly, the language you're using is mixing useful feedback and unconstructive adjectives. When submitting the new issue, please try to keep only the constructive part.

**Comment by annoying258** [comment]
I guess the transfer issue feature is not working. so, I manually transferred it and removed stuff that may be unconstructive for developers that get distracted easily. Thanks for the tip.

**Comment by nicolas-grekas** [comment]
Easily, or constantly...
