### ISSUE TITLE
User logged out upon hitting a constraint violation in a form that updates the user entity

### ISSUE THREAD

**Issue by o-alquimista** [symfony/symfony#33418]
**Symfony version(s) affected**:
4.3.4

**Description**  
I have an entity User that contains information such as username and password. I have a Symfony Form that allows me to change such information. When there are @Assert annotations in them, the errors are caught and shown on the form fields, but on subsequent requests, the authentication is lost.

When I attempt to change the username to one that has been taken already (UniqueEntity violation), the error appears on the form field, and everything is as expected.

If now I go to another page on this site, I am logged out. If I submit the same form again, no matter what value is in it, I am logged out. That is, I am logged out on the next request.

**How to reproduce**  

1 - Login as any user
2 - Use a form to update information from the User entity (make sure the field you're updating does validation such as NotBlank or UniqueEntity)
3 - Trigger a constraint violation, watch the error message appear on the related field.
4 - Now trigger any other request, such as clicking on any link to the same website or sending the form again.

The user will then be logged out and taken to the logout target route.

This is the Symfony project I can reproduce this on: https://github.com/o-alquimista/devdungeon/tree/security

**Comment by o-alquimista** [comment]
I now understand this a little better.

The username is being changed in the authentication token, even if I hit a violation. I can see the username changing to the invalid one, which then causes me to logout. On the database, this change never happens.

I don't know of a way to prevent this.

**Comment by stof** [comment]
and this is exactly the reason why the EntityUserProvider is reloading the user by primary key, and not by username (you can still have issues with remember me though: mutable security username is hard).
