### ISSUE TITLE
Feature Request / Console / ConsoleEvents::STOP

### ISSUE THREAD

**Issue by dillingham** [symfony/symfony#33411]
**Description**  

For console commands that produce temporary files, a means to hook into the early exit of a command to properly cleanup would be extra useful. Otherwise, the files linger on.

**Example**  
```php
$dispatcher->addListener(ConsoleEvents::STOP, function ($event){
    $event->getCommand()->fileManager->removeTempFiles();
});
```

**Comment by BoShurik** [comment]
You can use TERMINATE events for this

**Comment by dillingham** [comment]
@BoShurik I hit control + z & `TERMINIATE` didn't fire 🤔

**Comment by marie** [comment]
Hello! Can I take the issue?

**Comment by dillingham** [comment]
@marie yes please :)
