### ISSUE TITLE
Deprecate Validator's CacheInterface in favor of PSR-6

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#33414]
We don't need the `Symfony\Component\Validator\Mapping\Cache\Interface` nor any of its implementations, isn't it?

Let's deprecate them all and use PSR-6 directly instead.

**Comment by fancyweb** [comment]
`Symfony\Component\Validator\ValidatorBuilder::setMetadataCache()` (public method from a not internal / final class) use it as its mandatory argument type. How to stay backward compatible and still be able to be "deprecation free" on 4.4 in such a case? 🤔

**Comment by nicolas-grekas** [comment]
deprecate the method in favor of a new `setMappingCache()`?

**Comment by fancyweb** [comment]
This trick again 😬 My concern with it is that the current method name is just good, there is no benefit in changing it (like for a better understanding for example). However, if it's the only solution...

**Comment by derrabus** [comment]
> deprecate the method in favor of a new `setMappingCache()`?

Just `setCache()`? After all, the metadata cache is the only cache that the builder knows about. Also, `ValidatorBuilder` should be finalized, imho. That would make future changes to that class easier and people could still decorate the class if they feel the need for extending its functionality.

**Comment by nicolas-grekas** [comment]
the cache operates in the `Mapping` namespace, I think it's better to hint about the intent with the name
making the class `@final` LGTM

**Comment by derrabus** [comment]
#33459
