### ISSUE TITLE
php is not recognized with process component

### ISSUE THREAD

**Issue by Micaelamelo** [symfony/symfony#33417]
I'm doing web scraping using Laravel Dusk and I want to run the test in a route of web.php, I read that the process component of symfony should help me with that.

I tried this: 

```
Route::get('/scraping', function () {
    $process = new Process('cd pathtoartisan && php artisan dusk');
    $process->setPTY(true);
    $process->run();

    if (!$process->isSuccessful()) {
        throw new ProcessFailedException($process);
    }

    echo '<pre>'.$process->getOutput();
});

```
but i get this error:

> 'php' is not recognized as an internal or external command operable program or batch file.

I would like to mention that the command php artisan dusk of course works from cmd and that I have php in PATH environment variable. Does anyone have an idea what could be?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
