### ISSUE TITLE
[4.3][Security] BC break in Role class deprecation

### ISSUE THREAD

**Issue by althaus** [symfony/symfony#33438]
**Symfony version(s) affected**: 4.3.4

**Description**  
I'm trying to upgrade our 4.2.* Symfony version to the current 4.3.*. Our code currently relies on the newly deprecated Role class. This class was extended with a toString method to support conversion from Role object to role name:

~~~php
    public function __toString(): string
    {
        return $this->role;
    }
~~~

This introduced a BC break for us as we're currently rely on our own toString method.

~~~php
    public function __toString()
    {
        return $someMagicDust;
    }
~~~

I'm not not able to sort this our as either our code or the security ones breaks as I cannot change the behaviour of `getRoles()` in our User class directly as we rely on return our Role entity there. :(

Dropping the deprecated Role class doesn't work either as the AbstractToken expectes strings or Role objects.

**How to reproduce**  
1. Create a custom role class with custom toString.
2. Extend deprecated Role class.
3. Login and BOOM.

**Possible Solution**  
Don't use magic toString to resolve deprecation of the Role class. Introduce some custom name which probaby won't conflict with exsting ones or a new intermediate interface to be able to drop the role class directly.

Cheers
Matthias

**Comment by stof** [comment]
Adding methods in a child class of one of our classes is *not* something for which we provide backward compatibility (as that would forbid us to ever add a method in our own classes): https://symfony.com/bc

So I don't see this being changed.

**Comment by althaus** [comment]
Ok. It's still a pity as it'd be easiliy avoided. :/

**Comment by stof** [comment]
*any* method name we choose can create such kind of BC break, if you add a method name in the child class. This is exactly the reason why we excluded that from our BC policy (it would force us to put `no` in most rows of what you are allowed to change in classes when contributing).

**Comment by althaus** [comment]
Yes, I understand your point, but integration isn't that easy every now and then with the strict handling of private/final stuff in abstract classes and so forth. Nothing which is relevant here.

Some kind of optional RoleInterface as a intermediate solution for the string vs Role class would have been nice... but I guess that antique Role class was a bad idea in the beginning.

**Comment by stof** [comment]
> but I guess that antique Role class was a bad idea in the beginning.

yes, exactly.
