### ISSUE TITLE
[DX][Twig] Lint all templates when no argument is passed to lint:twig

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33443]
**Description**  
If you run this command, you'll see an error:

```bash
$ php bin/console lint:twig
```

You need to pass the directory to lint:

```bash
$ php bin/console lint:twig templates/
```

This is boring so ... could we change this to lint all the templates stored in all the configured `twig.paths` of the application when no argument is passed? And if you add the `-vvv` option, you see the details:

```bash
$ php bin/console lint:twig

  [OK] All 30 Twig files contain valid syntax.


$ php bin/console lint:twig -vvv

  // Checked 15 Twig files in templates/
  // Checked 5 Twig files in vendor/acme/ (namespace @acme)
  // Checked 10 Twig files in email/templates/

  [OK] All 30 Twig files contain valid syntax.
```

**Comment by yceruto** [comment]
That would make sense to me :+1:

**Comment by stof** [comment]
Note that we should keep the possibility to specify a target explicitly, as that may still be useful (for instance, a `precommit` hook might lint the modified templates)

**Comment by yceruto** [comment]
done in https://github.com/symfony/symfony/pull/33446
