### ISSUE TITLE
AnnotationException while creating auth

### ISSUE THREAD

**Issue by slowww** [symfony/symfony#33441]
Hi, Symfony newbie here.
I'm just trying to create an auth with the make:auth command, but an AnnotationException is thrown:

> [Semantical Error] The class "Symfony\Component\Validator\Constraint" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then you need to add @Annotation to the _class_ doc comment of "Symfony\Component\Validator\Constraint". If it is indeed no annotation, then you need to add @IgnoreAnnotation("Assert") to the _class_ doc comment of property App\Entity\Post::$Title  

Can someone explain me what does it mean?
Thanks.     

edit: Before this I created a form and (I'm following a tutorial) I added:

use Symfony\Component\Validator\Constraint as Assert;

and then:

     *@Assert|NotBlank

to my entity class.
I removed these lines, tried again making auth and it worked!

..I still can't understand what is going on.

**Comment by javiereguiluz** [comment]
Please, check that this:

```
*@Assert|NotBlank
```

Is written like this:

```
/**
 * @Assert\NotBlank
 */
```

Do you see the same error message?

**Comment by slowww** [comment]
Not anymore! Thank you!

**Comment by javiereguiluz** [comment]
I'm glad! Closing as fixed then.

PS: consider joining the Symfony Slack (https://symfony.com/slack) where we have a dedicated `#support` channel to help developers. Cheers!
