### ISSUE TITLE
[Mime] Allow overriding of Email::embedFromPath

### ISSUE THREAD

**Issue by jkabat** [symfony/symfony#33448]
**Description**

At the moment when image file being embedded does not exist, exception is thrown and message is not sent.

Thrown exception:
```
Unable to find template "@media_images/thumb_tiny/13/13a677f192eaea7fc7675725ed0346871b0e2355eba04260539fb3d25a5ef931.jpg" (looked into: /home/vagrant/sites/test/public).
```

Idea of not sending a message when some (dynamic) image is missing does bother me. However I did not find possibility to decorate a service in order the catch this exception. Is that even possible or I'm missing something?

**Example**  
```
<img width="50" height="50" src="{{ email.image('@images/nonexistent.gif') }}" alt="payment" />
```

**Comment by fabpot** [comment]
If you want to do that, you should create your own Twig function.
