### ISSUE TITLE
[BC Break] HttpClientTrait: changed structure of headers option

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#33450]
**Symfony version(s) affected**: 4.3.4

**Description**  
Here's a description of the issue: https://github.com/api-platform/core/issues/3043

The PR was #32823 

Basically, API Platform uses `HttpClientTrait::prepareRequest()`. The `$options['headers']` key in the return value changed from 4.3.3 to 4.3.4.

**How to reproduce**  
You can try using `HttpClientTrait::prepareRequest()` on 4.3.3 vs 4.3.4 and pass a `headers` key to the first argument (with one or more headers in it). The returned `$options` will differe on both versions.

**Possible Solution**  
It's a really minor thing... but it broke BC on the patch release. We could revert and change #32823 to be only 4.4... but that would change the behavior again on 4.3.5.

**Comment by nicolas-grekas** [comment]
API Platform should be patched instead, the linked PR is a bug fix, the kind that fit an experimental component at least :)

**Comment by weaverryan** [comment]
Got it. So, BC breaks are not typically allowed in patch releases for experimental components, but there are some exceptions for bug fixes.
