### ISSUE TITLE
Debug toolbar not working because template is missing

### ISSUE THREAD

**Issue by stevro** [symfony/symfony#33465]
**Symfony version(s) affected**: 4.4.x-dev

**Description**  
WebProfiler crashes because of the following exception

> PHP Exception UnexpectedValueException: "The profiler template "@WebProfiler/Collector/mailer.html.twig" for data collector "mailer" does not exist. at [...]/vendor/symfony/web-profiler-bundle/Profiler/TemplateManager.php:90

**Comment by yceruto** [comment]
It looks weird :/ because the template is there: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/mailer.html.twig

**Comment by stof** [comment]
could it be that you have web-profiler-bundle 4.3 installed, and not a full 4.4 setup ?

**Comment by stevro** [comment]
This is the composer.json which can reproduce the error. https://gist.github.com/stevro/dd16d9230eb4c081448ffbe69a158661

The project was initially on symfony 4.3 but upgraded to 4.4 a few months ago. The issue came up 1 week ago, and I run composer update almost daily.

**Comment by stof** [comment]
please show us the output of `composer show -i 'symfony/*'`. A composer.json does not tell us what is installed exactly in your project.

**Comment by stevro** [comment]
symfony/asset                      4.4.x-dev 3000a46  Symfony Asset Component
symfony/browser-kit                v4.3.1             Symfony BrowserKit Co...
symfony/cache                      4.4.x-dev 583e740  Symfony Cache compone...
symfony/cache-contracts            v1.1.5             Generic abstractions ...
symfony/config                     4.4.x-dev 4430cd5  Symfony Config Component
symfony/console                    4.4.x-dev bc32b73  Symfony Console Compo...
symfony/css-selector               v4.3.1             Symfony CssSelector C...
symfony/debug-bundle               v4.3.1             Symfony DebugBundle
symfony/debug-pack                 v1.0.7             A debug pack for Symf...
symfony/dependency-injection       4.4.x-dev 956708b  Symfony DependencyInj...
symfony/doctrine-bridge            v4.3.1             Symfony Doctrine Bridge
symfony/dom-crawler                v4.3.1             Symfony DomCrawler Co...
symfony/dotenv                     4.4.x-dev 9426b9d  Registers environment...
symfony/error-handler              dev-master 4d5c37c Symfony ErrorHandler ...
symfony/error-renderer             dev-master c1154e9 Symfony ErrorRenderer...
symfony/event-dispatcher           v4.3.1             Symfony EventDispatch...
symfony/event-dispatcher-contracts v1.1.5             Generic abstractions ...
symfony/expression-language        4.4.x-dev 43f9056  Symfony ExpressionLan...
symfony/filesystem                 v4.3.1             Symfony Filesystem Co...
symfony/finder                     v4.3.1             Symfony Finder Component
symfony/flex                       v1.4.5             Composer plugin for S...
symfony/form                       4.4.x-dev b8cb612  Symfony Form Component
symfony/framework-bundle           4.4.x-dev cbddae1  Symfony FrameworkBundle
symfony/http-foundation            4.4.x-dev 4646e1d  Symfony HttpFoundatio...
symfony/http-kernel                4.4.x-dev a954d84  Symfony HttpKernel Co...
symfony/inflector                  v4.3.1             Symfony Inflector Com...
symfony/intl                       v4.3.1             A PHP replacement lay...
symfony/mailer                     4.4.x-dev c03c68c  Symfony Mailer Component
symfony/maker-bundle               v1.13.0            Symfony Maker helps y...
symfony/mime                       4.4.x-dev e769949  A library to manipula...
symfony/monolog-bridge             v4.3.1             Symfony Monolog Bridge
symfony/monolog-bundle             v3.4.0             Symfony MonologBundle
symfony/options-resolver           v4.3.1             Symfony OptionsResolv...
symfony/orm-pack                   v1.0.6             A pack for the Doctri...
symfony/phpunit-bridge             v4.3.4             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu          v1.12.0            Symfony polyfill for ...
symfony/polyfill-intl-idn          v1.12.0            Symfony polyfill for ...
symfony/polyfill-mbstring          v1.12.0            Symfony polyfill for ...
symfony/polyfill-php72             v1.12.0            Symfony polyfill back...
symfony/polyfill-php73             v1.12.0            Symfony polyfill back...
symfony/process                    4.4.x-dev 0c03768  Symfony Process Compo...
symfony/profiler-pack              v1.0.4             A pack for the Symfon...
symfony/property-access            v4.3.1             Symfony PropertyAcces...
symfony/property-info              v4.3.1             Symfony Property Info...
symfony/routing                    4.4.x-dev 08b9ce3  Symfony Routing Compo...
symfony/security-bundle            4.4.x-dev d8fed22  Symfony SecurityBundle
symfony/security-core              4.4.x-dev e8484c7  Symfony Security Comp...
symfony/security-csrf              v4.3.1             Symfony Security Comp...
symfony/security-guard             v4.3.1             Symfony Security Comp...
symfony/security-http              v4.3.1             Symfony Security Comp...
symfony/sendgrid-mailer            4.4.x-dev 06ac3dc  Symfony Sendgrid Mail...
symfony/serializer                 v4.3.1             Symfony Serializer Co...
symfony/serializer-pack            v1.0.2             A pack for the Symfon...
symfony/service-contracts          v1.1.6             Generic abstractions ...
symfony/stopwatch                  v4.3.1             Symfony Stopwatch Com...
symfony/swiftmailer-bundle         v3.2.8             Symfony SwiftmailerBu...
symfony/templating                 v4.3.1             Symfony Templating Co...
symfony/test-pack                  v1.0.6             A pack for functional...
symfony/translation                4.4.x-dev 51b2577  Symfony Translation C...
symfony/translation-contracts      v1.1.6             Generic abstractions ...
symfony/twig-bridge                4.4.x-dev 5ccf3e1  Symfony Twig Bridge
symfony/twig-bundle                4.4.x-dev 370730e  Symfony TwigBundle
symfony/validator                  4.4.x-dev a9fd1a7  Symfony Validator Com...
symfony/var-dumper                 v4.3.1             Symfony mechanism for...
symfony/var-exporter               v4.3.1             A blend of var_export...
symfony/web-link                   4.4.x-dev e95ba10  Symfony WebLink Compo...
symfony/web-profiler-bundle        v4.3.1             Symfony WebProfilerBu...
symfony/web-server-bundle          dev-master 3e84c64 Symfony WebServerBundle
symfony/webpack-encore-bundle      v1.6.2             Integration with your...
symfony/yaml                       4.4.x-dev 3ef0425  Symfony Yaml Component

**Comment by xabbuh** [comment]
The installed version of `symfony/web-profiler-bundle` is 4.3.1. Does the issue resolve if you update the WebProfilerBundle to 4.4 too?

**Comment by stof** [comment]
well, `prefer-stable` explains me why Composer would prefer installing a 4.3 release rather than the 4.4 dev version. But it is weird that Flex does not restrict things to install only 4.4 versions.
@stevro Have you run `composer update` from a setup where Flex was not installed yet ?

**Comment by stevro** [comment]
@stof , no, flex was installed from the beginning.
@xabbuh, yes, if I explicitly put symfony/web-profiler-bundle: "4.4.*" in composer.json then it works.

**Comment by xabbuh** [comment]
I guess there's not much we can do about it then, right?

**Comment by stevro** [comment]
I'm closing the issue as it solves itself if we specify explicitly symfony/web-profiler-bundle: "4.4.*" in composer.json
