### ISSUE TITLE
Tests fail because expected exceptions are intercepted by ExceptionController

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#33478]
**Symfony version(s) affected**: 4.4-dev

**Description**  
#33271 introduced an error controller that renders error pages for exceptions. Before that, TwigBundle rendered error pages and if that bundle was missing, the exception bubbled up to the code that called `Kernel::handle()`.

The new behavior might be more consistent, however it breaks tests that relied on the old behvior, like this one from SecurityBundle 4.3:

https://github.com/symfony/symfony/blob/828e5a4ae3ca979ec358d82338147f1b79555c34/src/Symfony/Bundle/SecurityBundle/Tests/Functional/MissingUserProviderTest.php#L16-L26

The test fails if FrameworkBundle 4.4 is installed and if I downgrade FrameworkBundle to 4.3, the test is green.

PR #33271 patches the test on the 4.4 branch to parse the error page instead of catching the exception, but we cannot do that on 4.3 because then the test would not work with FrameworkBundle 4.3 anymore.

Also, this kind of looks like a BC break to me. Userland tests might run into similar issues.

ping @yceruto

**How to reproduce**  
https://travis-ci.org/symfony/symfony/jobs/580647626

**Comment by derrabus** [comment]
Thanks @yceruto, PR #33479 fixes the issue for the Symfony test suite. Would this also be the recommended way to fix userland tests that fail because of this issue? Is this documented somewhere?

**Comment by yceruto** [comment]
To me, test cases like this one (`$client = $this->createClient(...)` + `$client->request(...)`) shouldn't be tested againts `$this->expectException(...)` that's not the real live, you should expect a real error response instead. That's why I think it is not a BC break. 

It works in 4.3 because the error handler is replaced by PHPUnit and the response instance is never instantiated.

To fix this in your project you can to add the TwigBundle or activate the HttpKernel's ExceptionListener service for your tests suite with a proper exception controller.

**Comment by yceruto** [comment]
> To fix this in your project you can to add the TwigBundle or activate the HttpKernel's ExceptionListener service for your tests suite with a proper exception controller.

The last, is what we have by default now as of 4.4

**Comment by yceruto** [comment]
I faced this issue in https://github.com/symfony/symfony/pull/31398#issuecomment-490081769, but the other way around. See for example these tests in 4.3 https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/SecurityBundle/Tests/Functional/JsonLoginTest.php

**Comment by derrabus** [comment]
> To me, test cases like this one (`$client = $this->createClient(...)` + `$client->request(...)`) shouldn't be tested against `$this->expectException(...)` that's not the real live, you should expect a real error response instead. That's why I think it is not a BC break.

Well, tests aren't real live. And for functional tests like this one, a developer might want to check what exception specifically is raised. That's a bit complicated when parsing a human-readable error page. So, I can to a certain point understand why in general tests like this one have been built. For this specific test, the error page is fine though.

Anyway, I'm rather concerned about test suites breaking when people start upgrading to Symfony 4.4. A documented migration path would be helpful.

**Comment by yceruto** [comment]
If a developer wants to check which exception is specifically raised, it is likely that they will not create a functional test with a request/response approach, but a unit-specific test.

I'm not really convinced why we would need a migration path for this kind of Functional test that in first place shouldn't happen.

**Comment by yceruto** [comment]
> That's a bit complicated when parsing a human-readable error page.

It doesn't seem so complicated IMHO, see https://github.com/symfony/symfony/pull/33479/files#diff-e84e5e830de34b1539d8bf85ed6042b5R27

**Comment by yceruto** [comment]
And related to the title: "Tests fail because expected exceptions are intercepted by ExceptionController", I can say that "Tests pass because expected exceptions are not intercepted by ExceptionController" ;) that would be the correct behavior expected for these functional tests. 

The question now is: does it deserves a patch?

**Comment by derrabus** [comment]
> And related to the title: "Tests fail because expected exceptions are intercepted by ExceptionController", I can say that "Tests pass because expected exceptions are not intercepted by ExceptionController" ;) that would be the correct behavior expected for these functional tests.

Yes, the old behavior was rather an accident than documented behavior. I really like the new behavior because `Kernel::handle()` with `$catch = true` now consistently catches exceptions as one might expect. That's a very good change and I thank you a lot for having implemented that!

But the old behavior had been there since 2.x. My concern is that this very well crafted feature might break tests and leave developers clueless about what's wrong. Yes, those tests should maybe have been written differently in the first place.

> The question now is: does it deserves a patch?

No, but it deserves documentation, imho.

**Comment by yceruto** [comment]
> No, but it deserves documentation, imho.

Completely agreed, thanks!

I just added a comment in https://github.com/symfony/symfony-docs/issues/12273 to not to forget it.

**Comment by derrabus** [comment]
I think we can close here. The "broken" test has been fixed and upgrade path will be documented with symfony/symfony-docs#12273.
