### ISSUE TITLE
 Serialization for the format json is not supported

### ISSUE THREAD

**Issue by madhuri20m** [symfony/symfony#33498]
**Symfony version(s) affected**: 3.4.28

**Description**  
 Serialization for the format json is not supported

**How to reproduce**  
1. I have integrated symfony messenger for queuing. message is getting detached and send it for encoding in envelop. While sending it to encoding its giving above error.

Same thing was working with symfony 3.4.4 and current symfony version is 3.4.28.

**Possible Solution**  
I have tried debugging in symfony serialzer component, It seems that jsonEncoder is not getting initialized in serilizer

**Additional context**

**Comment by xabbuh** [comment]
I fail to see how this is related to the Messenger component which doesn't exist in 3.4. Anyway, can you please create a small example application that allows to reproduce the issue?

**Comment by madhuri20m** [comment]
symfony messenger works with 3.4. Here is example:
//messenger.yml
`messenger:
  transports:
    # DSN: doctrine://$repository_alias/$queue_name
    # most likely we do not need more repositories (unless there's a need for splitting MySQL table with messages)
    main: "doctrine://default/test"
  routing:
    # message type to transport routes
    Bundle\QueueBundle\Message\TestMessage: [ main ]
  serializer:
    enabled: true`

//doctring Transport sender:
`<?php

namespace Bundle\QueueBundle\Transport\Doctrine;

use Akeneo\Tool\Component\StorageUtils\Detacher\ObjectDetacherInterface;
use Bundle\QueueBundle\Repository\MessageRepositoryInterface;
use Bundle\QueueBundle\Message\MessageOptionsAwareInterface;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\SenderInterface;
use Symfony\Component\Messenger\Transport\Serialization\EncoderInterface;

/**
 * @author Piotr Lewandowski <lewandowski.piotr@johndeere.com>
 */
class DoctrineTransportSender implements SenderInterface
{
    /**
     * @var MessageRepositoryInterface
     */
    private $messageRepository;
    /**
     * @var EncoderInterface
     */
    private $encoder;
    /**
     * @var string
     */
    private $queueName;

    /**
     * @var ObjectDetacherInterface
     */
    private $detacher;

    /**
     * DoctrineTransportSender constructor.
     *
     * @param MessageRepositoryInterface $messageRepository
     * @param EncoderInterface $encoder
     * @param string $queueName
     * @param ObjectDetacherInterface $detacher
     */
    public function __construct(
        MessageRepositoryInterface $messageRepository,
        EncoderInterface $encoder,
        string $queueName,
        ObjectDetacherInterface $detacher)
    {
        $this->messageRepository = $messageRepository;
        $this->encoder = $encoder;
        $this->queueName = $queueName;
        $this->detacher = $detacher;
    }

    /**
     * Sends the given envelope.
     *
     * @param Envelope $envelope
     */
    public function send(Envelope $envelope)
    {
        $options = ($envelope->getMessage() instanceof MessageOptionsAwareInterface) ? $envelope->getMessage()->getMessageOptions() : [];
        $encodedMessage = $this->encoder->encode($envelope);
        $message = $this->messageRepository->createAndPush($this->queueName, $encodedMessage['body'], $encodedMessage['headers'], $options);
        $this->detacher->detach($message);
    }
}`

**Comment by madhuri20m** [comment]
Its breaking while sending it to encode

**Comment by Tobion** [comment]
Your text is not correctly formatted and I don't understand the issue. Please clarify or create an a small app that reproduces the issue.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
