### ISSUE TITLE
Allow overriding Url Generator hostname and scheme

### ISSUE THREAD

**Issue by ericjacolin** [symfony/symfony#33501]
**Description**  
I recently migrated a SF4 application to kubernetes. The scheduling is now external, as is the recommended kubernetes way: the SF4 batch component no longer receives PHP CLI commands from a cron scheduler within docker container but receives API calls from a kubernetes cron job workload.
This messes up with URL generation (typically for sending emails).
UrlGeneratorInterface::ABSOLUTE_URL generates URLs using the SF4 application's internal hostname and scheme to the kubernetes cluster, as one would expect.
It would be nice to be able to override the URL generator hostname and scheme with the same values as defined in configuration for commands (router.request_context.host/ router.request_context.scheme)

**Example**

**Comment by Fonata** [comment]
You can already use an event subscriber for this purpose:

````php
<?php

namespace App\EventSubscriber;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Routing\RequestContextAwareInterface;

/**
 * Override the detected domain, scheme and port with the information from config/services.yaml.
 *
 * To find out more about the "parameters:" key, read
 * https://symfony.com/doc/4.1/console/request_context.html#configuring-the-request-context-globally
 */
class DomainChangingRouterContextSubscriber implements EventSubscriberInterface
{
    private $router;
    private ParameterBagInterface $params;

    public function __construct(RequestContextAwareInterface $router, ParameterBagInterface $params)
    {
        $this->router = $router;
        $this->params = $params;
    }

    public static function getSubscribedEvents()
    {
        return [
            'kernel.request' => 'onKernelRequest',
        ];
    }

    public function onKernelRequest(RequestEvent $event)
    {
        if (!$event->isMasterRequest()) {
            return;
        }

        if (!$this->params->has('router.request_context.host')) {
            return;
        }

        $context = $this->router->getContext();
        $context->setHost($this->params->get('router.request_context.host'));
        $scheme = $this->params->get('router.request_context.scheme');
        if ($scheme) {
            $http_port = $this->params->get('request_listener.http_port');
            $https_port = $this->params->get('request_listener.https_port');
            if ('http' === $scheme && $http_port) {
                $context->setHttpPort($http_port);
            } elseif ('https' === $scheme && $https_port) {
                $context->setHttpsPort($https_port);
            }
            $context->setScheme($scheme);
        }
    }
}
````

**Comment by alexkingdom** [comment]
> 
> 
> You can already use an event subscriber for this purpose:
> 
> ```
> <?php
> 
> namespace App\EventSubscriber;
> 
> use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
> use Symfony\Component\EventDispatcher\EventSubscriberInterface;
> use Symfony\Component\HttpKernel\Event\RequestEvent;
> use Symfony\Component\Routing\RequestContextAwareInterface;
> 
> /**
>  * Override the detected domain, scheme and port with the information from config/services.yaml.
>  *
>  * To find out more about the "parameters:" key, read
>  * https://symfony.com/doc/4.1/console/request_context.html#configuring-the-request-context-globally
>  */
> class DomainChangingRouterContextSubscriber implements EventSubscriberInterface
> {
>     private $router;
>     private ParameterBagInterface $params;
> 
>     public function __construct(RequestContextAwareInterface $router, ParameterBagInterface $params)
>     {
>         $this->router = $router;
>         $this->params = $params;
>     }
> 
>     public static function getSubscribedEvents()
>     {
>         return [
>             'kernel.request' => 'onKernelRequest',
>         ];
>     }
> 
>     public function onKernelRequest(RequestEvent $event)
>     {
>         if (!$event->isMasterRequest()) {
>             return;
>         }
> 
>         if (!$this->params->has('router.request_context.host')) {
>             return;
>         }
> 
>         $context = $this->router->getContext();
>         $context->setHost($this->params->get('router.request_context.host'));
>         $scheme = $this->params->get('router.request_context.scheme');
>         if ($scheme) {
>             $http_port = $this->params->get('request_listener.http_port');
>             $https_port = $this->params->get('request_listener.https_port');
>             if ('http' === $scheme && $http_port) {
>                 $context->setHttpPort($http_port);
>             } elseif ('https' === $scheme && $https_port) {
>                 $context->setHttpsPort($https_port);
>             }
>             $context->setScheme($scheme);
>         }
>     }
> }
> ```

What about Dev Env ? Profiler still is on localhost

**Comment by jderusse** [comment]
I'm voting for closing this issue for 2 reasons:

1. clients (ie. the cron job) that call internal endpoints (ie. the k8s service) should send the `x-forwarded-host` header to provide information about the real public host.

2. this is already possible via `router->setContext` method
