### ISSUE TITLE
[DX][Stopwatch] Assign colors to custom categories

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33514]
**Description**  
I'm playing with the Stopwatch component and I used something like this:

```php
$this->stopwatch->start('export-data', 'export');
```

In the profiler I can see this ... but the `export` custom category is not assigned a color, so it looks like a bug and it complicates understanding the different events:

![image](https://user-images.githubusercontent.com/73419/64523394-80712100-d2fc-11e9-9977-5e9466281f42.png)

**Proposed solution**  
Let's assign a different color for each custom category.

In practice:

1) We select 5 to 10 beautiful colors which are not already associated with Symfony things (the event's blue, the doctrine's orange, the twig's green, etc.)
2) We assign a color randomly to each custom category.

Instead of pure randomness, we could apply the same strategy of the Asset component, which uses this code to always assign the same base URL for each path. This way we'd always select the same "random" color for the same category name:

```php
protected function chooseBaseUrl($path)
{
    return (int) fmod(hexdec(substr(hash('sha256', $path), 0, 10)), \count($this->baseUrls));
}
```

**Comment by ro0NL** [comment]
Somewhat related to the final bullet in https://github.com/symfony/symfony/issues/27262

**Comment by fabpot** [comment]
Sounds like a great idea? @javiereguiluz  Up for a PR?
