### ISSUE TITLE
[Serializer] JSON-LD support

### ISSUE THREAD

**Issue by maarten-shop4** [symfony/symfony#33528]
**Description**  
It could be a (great) addition to the Serializer component to be able to encode your data in [JSON-LD](https://www.w3.org/TR/json-ld-api/) format.

**Example**  

by simple instructing your serializer to generate JSON-LD content
```php
$jsonLdContent = $serializer->serialize($product, 'json-ld');
```

The output could be:
```json
{
  "@context": "https://www.schema.org",
  "@type": "product",
  "brand": "Acme",
  "name": "Example",
  "category": "Awesome Stuff",
  "image": "http://www.example.com/image.jpg",
  "description": "This is an awesome product",
}
```

**Comment by stof** [comment]
@dunglas API-Platform is already able to serialize to JSON-LD. Is it something that could be upstreamed here, or does it depend on metadata to be able to know the JSON-LD structure to use ?

**Comment by dunglas** [comment]
It depends of the metadata System of API Platform. JSON-LD is "just" plain JSON with mapping and hypermedia (URL generation) capabilities. The serializer is already perfectly able to serialize raw JSON-LD document like this one using the built-in JSON encoder.

Maintaining the mapping etc is IMO out of scope for Symfony, but it's entirely supported by API Platform (it's actually the main feature of the framework).

**Comment by javiereguiluz** [comment]
@maarten-shop4 we're closing this for the reasons given by Kévin ... but thanks for proposing features to improve Symfony!
