### ISSUE TITLE
[DI] Handling decorations on non existent services

### ISSUE THREAD

**Issue by pascalheidmann-bedarf** [symfony/symfony#33522]
**Description**  
It would be nice to handle decorations on non existent services by either throwing the service not found exception or just silently ignoring the service all together, similar to how missing services as parameters are handles.

**Example**  
Imagine having an `OptionalBundle` with a service `OptionalBundle\Services\OptionalService` and another Bundle `DecoratorBundle` that has to decorate the `OptionalService` if present:
```xml
<service id="OptionalBundle\Services\OptionalService" class="OptionalBundle\Services\OptionalService" />
<!-- ... -->
<service id="DecoratorBundle\Service\Decorator\OptionalServiceDecorator" decorates="OptionalBundle\Services\OptionalService" class="DecoratorBundle\Service\Decorator\OptionalServiceDecorator" on-invalid="ignore" />
```

Now in my example I don't have `OptionalBundle` installed and the `DecoratorBundle` would be broken. With the new attribute `on-invalid` with values `exception`, `ignore`, `null` you can control the handling:
- `exception`: default, throw exception
- `ignore`: don't create decoration service at all
- `null`: create decoration service but if `service.inner` gets passed as a parameter it will be null -> might need explicit `on-invalid` attribute on parameter itself.

For YAML declaration I would suggest using the `@?` syntax as for arguments.

**Comment by eschultz-magix** [comment]
Just an idea:
- make the decorator service abstract and give it a suffix (f.ex. ".abstract")
- write an extension that will
-- check if the optional bundle is installed
-- create the decorator service with an alias to the abstract service

**Comment by nicolas-grekas** [comment]
That would make sense to me. Anyone for giving it a try?

**Comment by mtarld** [comment]
Yes I'll :)
