### ISSUE TITLE
Process killed at symfony/console (v4.2.7) installation

### ISSUE THREAD

**Issue by nrayann** [symfony/symfony#33534]
**Symfony version(s) affected**: symfony/console (v4.2.7)

**Description**
  
The symfony/console installation proccess is being killed when I run `composer install` of my Laravel project.

**How to reproduce**  

- Ubuntu 18.04 with WSL on Windows 10 Pro
- PHP 7.2.19
- Laravel 5.8

**Additional context** 

 Bash output:
```
- Installing symfony/console (v4.2.7): Loading from cache

Failed to execute unzip -qq  '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/symfony/console/d5e2f7700964cd8960261b5750040990' -d '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/composer/76f787b7'

Killed

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
Unzip with unzip command failed, falling back to ZipArchive class
```

![image](https://user-images.githubusercontent.com/5538985/64618308-66941480-d3b6-11e9-879c-3e5fa1a1296e.png)

Thank you in advance for any help :D

**Comment by stof** [comment]
This `Killed` generally means that your system ran out of memory.

**Comment by nrayann** [comment]
Yes, I have read about it, but there is an error message pointing some specific:

```
The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
Unzip with unzip command failed, falling back to ZipArchive class
```
I am running it on intel core i7 7th Gen with 16gb RAM, I Did not set up custom RAM for the Ubuntu WSL, is there any way to increase the memory for it?

cc: @stof

**Comment by stof** [comment]
> Did not set up custom RAM for the Ubuntu WSL, is there any way to increase the memory for it?

That's something to ask to the WSL support channel, not to the Symfony one.

Plus, this is an error happening when running composer, not when running Symfony, so this is the wrong place to report it anyway. So I'm closing this issue.
