### ISSUE TITLE
Controller getUser function returns null after successful login

### ISSUE THREAD

**Issue by iron2414** [symfony/symfony#33538]
**Symfony version(s) affected**: 4.0

**Description**  
I've tried to create a simple json authentication with app_user_provider. I can successfully login, and on my login action if i call "$this->getUser()" then it gives back my current user. However if right after i call another action (in my case its profile action which should give back the currently logged in user) the getUser() method returns null. I've read the documentation and it says i have a stateless session, or it's some serialization problem.  I implemented the serializaiton interface too, and generated the user with the command shown in the ducumentation.

I've attached my security.yaml, my entity class and the controller.
[login_empty_error.zip](https://github.com/symfony/symfony/files/3596590/login_empty_error.zip)

Is it a bug or is something wrong with the documentation?

**Comment by henry2778** [comment]
You are probably not sending the PHPSESSID cookie which is returned to client in `Set-Cookie` response header after request to the /api/login

**Comment by iron2414** [comment]
I'm pretty sure i'm doing something wrong, but my login answer looks like this:
![image](https://user-images.githubusercontent.com/10381571/64646509-8871b380-d417-11e9-9a6d-573354d5c8e6.png)

![image](https://user-images.githubusercontent.com/10381571/64646537-97586600-d417-11e9-924f-ad17a1ba26c9.png)


After that if i call the profile with "PHPSESSID" header and "085434f6-50cf-4758-9860-210592ca2d26" value it's still blank. What am i missing?

**Comment by linaori** [comment]
This sounds like a support question and doesn't look like an issue with Symfony. Please check https://symfony.com/support for the appropriate support channels.

**Comment by iron2414** [comment]
The issue is, it does not give me back a cookie. I've tried to resolve the problem, no success so far.
