### ISSUE TITLE
Parse error: syntax error, unexpected '?' in Translator.php Line 89

### ISSUE THREAD

**Issue by Eksilente** [symfony/symfony#33542]
**Symfony version(s) affected**: symfony for laravel 5.5.48

**Description**  
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_PARSE)
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

**How to reproduce**  
Translator.php Line 89 extra "?"

**Possible Solution**  
remove the "?" character

**Comment by fancyweb** [comment]
Looks like the PHP version you use is lower than 7.1 (or lower than 7.0 actually) and that your project uses the Symfony Translation component in a version above 4.0 (where the minimum required PHP version is 7.1, so where the component uses nullable scalar type declarations).

This is not a Symfony issue.
