### ISSUE TITLE
[Mailer] Adding a "file" transport

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#33563]
Hello,

I would like to have a "file" transport for Symfony Mailer. 
It would write messages to a configurable folder, as serialized files (using PHP `--serialize`).

The main use case I see if for testing: when testing a Symfony application through Behat/Selenium or Symfony Panther, you can't access the kernel or the profiler[^1]. 
Such files could easily be counted and read, it would offer a good DX for a popular use case ([previously in documentation](https://symfony.com/doc/4.2/email/testing.html)).

Other use cases I see would be for spooling and log/backups, someone may want a copy of every email sent. Symfony Messenger is a better solutions for those use case, but I could imagine scenario when it is not available.

RFS, DSN would be something like this:
`file://var/mail` for a path relative to project dir
`file:///tmp/mail` for absolute path

Files would be named randomly (or should it be configurable?).

Right now I'm implementing this in a work project, later I could extract the code & open a corresponding PR.

^1: technically, I could enable and access profiler UI, but it feels hacky - plus there are some performances downside

**Comment by xabbuh** [comment]
There are some assertions provided by the `MailerAssertionsTrait` from FrameworkBundle. Is that something in the direction that you have in mind?

**Comment by romaricdrigon** [comment]
Yes! I saw those, they are much needed. But they are limited to tools which share the same Symfony kernel.

I looked this morning, I discovered it was proposed before (#31947), and it sounds much needed (#31747, #32409).

**Comment by sstok** [comment]
I think using a listener is a better solution (for testing at least) as you can name your own messages. Which is much more difficult when a file transporter is used.

**Comment by fabpot** [comment]
I agree with @sstok. The more I think about it, the more I think that a listener is the way to go. Full flexibility and just a few lines of code.

**Comment by romaricdrigon** [comment]
Ok then. 

I guess the code is not that very different from a transport, [here](https://gist.github.com/romaricdrigon/4a7c9d5af79f6cee4ac15566505c36c2) is my implementation of a `FileTransport`, and the corresponding `FileHelper` to read serialized messages. Code is not as easy as it seems, we have to rely on some internal methods.  
So I still think it should be included with the component - something like a `TestListener` or `ToFilesListener`. Any thoughts on that?

**Comment by fabpot** [comment]
`RawMessage` instances are serializable. Why do you exclude them?
I also don't understand why you are unserializing emails yourself (by storing the class name). Can you explain?

**Comment by romaricdrigon** [comment]
> `RawMessage` instances are serializable. Why do you exclude them?

[L39](https://gist.github.com/romaricdrigon/4a7c9d5af79f6cee4ac15566505c36c2#file-filetransport-php-L39) is not really useful at the moment, I may be extra cautious.

About serializing `$message->getMessage()`, I'm getting an exception:
![image](https://user-images.githubusercontent.com/919405/65051080-b8b1d880-d968-11e9-96d0-e0b9e7d71f5a.png)

> I also don't understand why you are unserializing emails yourself (by storing the class name). Can you explain?

`Email` and `TemplatedEmail` are serialized as arrays, I needed to know which class I should instantiate when unserializing data. Moreover, their serialization formats are incompatible (cf. [Email](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mime/Email.php#L587)  and [TemplatedEmail](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php#L75), they are array with a different number of elements).
Overall, the whole process feels pretty heavy indeed.

**Comment by fabpot** [comment]
Are you using JSON serialization?

**Comment by romaricdrigon** [comment]
No, just PHP `serialize()`

**Comment by fabpot** [comment]
Can you give me some examples that do not work?

**Comment by romaricdrigon** [comment]
Sure, here's a crashing app, based on Symfony 4.3:
https://github.com/romaricdrigon/demo-mailer

Just visit "/", you will see errors. And actually I realize that issue is Transport specific. Event subscriber can serialize message correctly (and class is included).

**Comment by sstok** [comment]
Some message parts use the Generator to make their content loading lazy, in the SMimePart I solved this by explicitly checking if the body is an iterable and forcing it to a string. 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mime/Part/SMimePart.php#L99

Maybe something similar can be done for the whole MIME component Message parts as well.

**Comment by romaricdrigon** [comment]
It looks like you are on spot. Thanks for the snippet.
In my previous example, I could do `$message->getMessage()->toString()`, but then it means you need to parse the string representation in tests :(

**Comment by fabpot** [comment]
That's a problem that has been fixed in 4.4.

**Comment by romaricdrigon** [comment]
Thats great! Thanks, it will simplify code.

About what I was saying about `TestListener` or `ToFilesListener`. Any opinions on adding it into Mailer component? Is it worth working on it?

**Comment by fabpot** [comment]
Have a look at 4.4, I think  we have all you need via `MessageEvents` and `MessageLoggerListener`

**Comment by romaricdrigon** [comment]
Indeed they will make testing easier with Symfony default testing client. That's great.
It won't help when using Symfony Panther with Chrome (the default), as you can't access the Symfony kernel of the current HTTP request.

Maybe that second scenario is not that common, there's not much feedback on this issue. Then I'm fine with closing it.

**Comment by fabpot** [comment]
For the second scenario, you have the "infrastructure" to "easily" store the messages the way you want. I think that's enough for now.
