### ISSUE TITLE
$_ENV and $_SERVER sometimes differ

### ISSUE THREAD

**Issue by Barbaro** [symfony/symfony#33566]
Hi everybody.

**Symfony version(s) affected**: 4.3.4

**Description**  
I'm using dotenv component.
Everything is fine when starting a console command manually ( or when using the website with routes, templates and controllers) but when calling the given command through pclose(popen("php ..\bin\console mycommand")), a service isn't able to use env loaded in $_ENV. But $_SERVER and getenv() are totally OK, with the whole file loaded in them.
Shouldn't $_ENV and $_SERVER works the same, with the parsed file loaded in both of them ?

**How to reproduce**  
I have a service calling a command through pclose(popen("start /B ".$cmd, "r")).
The command calls a service that does the following :
use Symfony\Component\Dotenv\Dotenv;

In the constructor :

```php
$dotenv = new Dotenv();
$dotenv->load($this->appKernel->getProjectDir() .'\.env');
```

I log the values in the constructor like this :

```php
$this->logger->info('Env variables : '.serialize($_ENV));
$this->logger->info('Server variables : '.serialize($_SERVER));
$this->logger->info('Getenv variables : '.serialize(getenv()));
```

When calling the command through the console, everything is fine.
When calling the command in background through php code, the first logger info doesn't have the .env file content. It shows this : 
```
a:3:{s:7:"APP_ENV";s:3:"dev";s:9:"APP_DEBUG";s:1:"1";s:15:"SHELL_VERBOSITY";i:3;}
```
 The two next logger are both ok.

This is first my issue, sorry if I forgot things, or if I'm doing something wrong :)

**Comment by danielszwarc** [comment]
Hey @Barbaro, maybe different PHP configuration is loaded. Please read about https://www.php.net/manual/en/ini.core.php#ini.variables-order and check value of `variables_order` option.

**Comment by nicolas-grekas** [comment]
Can you try setting your `variables_order=EGPCS` in your php.ini file and run that again?
Same issue? If not, then that's not on Symfony side, but "normal" php behavior, related to this setting.

**Comment by Barbaro** [comment]
Weird situation but I can't reproduce the problem right now. I tried to use $_ENV in my code instead of $_SERVER and it works like a charm. I didn't edit the php.ini for it to work, and I even tried to define variables_order to the default value EGPCS, it still works.

**Comment by xabbuh** [comment]
Let's close here then. Thanks for the feedback.
