### ISSUE TITLE
[Messenger] Run CommandBus in Async

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony#33572]
**Symfony version(s) affected**: 4.3.4

**Description**  
I can't run a CommandBus in async, i have this error when i dispatch the command: 
Message of type "App\Application\Command\TestCommand" was handled zero times. Exactly one handler is expected when using "App\Infrastructure\CommandBus::handle()".

**How to reproduce**  
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Application\Command\TestCommand': async

**Additional context**  
I dispatch  several times the same command  with a loop in the Symfony's command.

**Comment by xabbuh** [comment]
Can you please create a small application that allows to reproduce your issue?

**Comment by xfifix** [comment]
Example of task: 
`
$i = 0;
while($i<5){
$commandBus->handle(new TestCommand());
$++;
}`

i just want execute a command in async ...

**Comment by xfifix** [comment]
@sroze need your help :)

**Comment by xfifix** [comment]
I still can not run a Command in Async... There is this LogicException...
```php
  $handledStamps = $envelope->all(HandledStamp::class);
if (!$handledStamps) {
            throw new LogicException(sprintf('Message of type "%s" was handled zero times. Exactly one handler is expected when using "%s::%s()".', \get_class($envelope->getMessage()), \get_class($this), __FUNCTION__));
        }

`

**Comment by Spomky** [comment]
Note for people coming here with the same message: the exception is thrown by `Symfony\Component\Messenger\HandleTrait::handle`, but this trait is not meant to be used by buses that run asynchronously.
If you need to run CommandBus in an Async way, you should not use that trait.
