### ISSUE TITLE
[TwigBundle] twig.exception_listener relies on deprecated templating.engines FrameworkBundle configuration

### ISSUE THREAD

**Issue by killerwolf** [symfony/symfony#33577]
**Symfony version(s) affected**: 4.3

**Description**  
The TwigBundle to register its own ExceptionListener `twig.exception_listener` relies on the container framework-bundle parameter `templating.engines` which is deprecated 

`            $engines = $container->getParameter('templating.engines');
            if (!\in_array('twig', $engines)) {
                $container->removeDefinition('twig.exception_listener');
            }
`

`The "framework.templating" configuration is deprecated since Symfony 4.3. Configure the "twig" section provided by the Twig Bundle instead.`

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by killerwolf** [comment]
here is the offending code:
https://github.com/symfony/twig-bundle/blob/4.3/DependencyInjection/Compiler/ExceptionListenerPass.php#L33

**Comment by Tobion** [comment]
What's the problem when you do not enable framework.templating? What's the bug?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
