### ISSUE TITLE
multiple entity managers

### ISSUE THREAD

**Issue by voodoomg** [symfony/symfony#33581]
1. I follow this manual
https://symfony.com/doc/current/doctrine/multiple_entity_managers.html
2. And this
https://symfony.com/doc/current/security/guard_authentication.html#step-2-create-the-authenticator-class
3. In TokenAuthenticator I changed **use App\Entity\User** to **use App\Entity\Customer\User**
4. When I try to login, method **$this->entityManager->getRepository(User::class)** in TokenAuthenticator throw mapping error
`The class 'App\Entity\Customer\User' was not found in the chain configured namespaces App\Entity\Main`

I need authenticate user by customer entity manager and find him in customer connection

**Comment by michaljusiega** [comment]
You must to tell to entity manager, which prefix to use. 
I think in configuration you have exactly `App\Entity\Main` instead `App\Entity\Customer`

**Comment by voodoomg** [comment]
> You must to tell to entity manager, which prefix to use.
> I think in configuration you have exactly `App\Entity\Main` instead `App\Entity\Customer`

how?

**Comment by michaljusiega** [comment]
Sorry, I didn't understand before. I assume you have many entity managers, but one of them must always be set as default. 

How do you get and assign to `$this->entityManager` ? DI ? From Container ?

If the entity prefix will be associated with another entity manager, then of course the error is understandable here because he knows nothing about such a namespace.

**Comment by voodoomg** [comment]
from manual (second url)
public function __construct(EntityManagerInterface $em)
```
{
    $this->em = $em;
}
```

**Comment by javiereguiluz** [comment]
@voodoomg you may need to define the `manager_name` option in your user provider to tell the name of the entity manager used for customers.

Anyway, this question looks like a support question. However, in this repository we only discuss about Symfony's bugs and new features. For support about using Symfony, please join Symfony Slack at https://symfony.com/slack and add your question in the #support channel. Thanks!
