### ISSUE TITLE
[HttpFoundation] Allow to configure PdoSessionHandler with DATABASE_URL like DSN

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33589]
**Description**  
`PdoSessionHandler` requires a custom configuration format different from the traditional `DATABASE_URL` DSN. See https://symfony.com/doc/current/doctrine/pdo_session_storage.html

Should we change this? Should we accept DSN-only? Should we accept both formats? Thanks!

**Comment by javiereguiluz** [comment]
@dkarlovi suggested on Symfony Slack to maybe don't do this ... but create a `DoctrineSessionHandler` instead?

**Comment by javiereguiluz** [comment]
I'm closing this because @stof told us that PDOSessionHandler already supports this feature since Symfony 3.4 ... so the problem is that the docs were outdated. Sorry!

**Comment by stof** [comment]
Note that raw PDO DSNs are still supported. So the doc is not wrong (what it shows is working) but it is incomplete.
