### ISSUE TITLE
[Var dumper] incorrect work in PHPStorm console with php7.3

### ISSUE THREAD

**Issue by nepster-web** [symfony/symfony#33594]
**Symfony version(s) affected**: used without symphony (latest version)

**Description**  
I updated php to version 7.3 and getting a problem with Symfony VarDumper.
When I try to debug any class in the console (CLI), I see only class name and console freezes.

![изображение](https://user-images.githubusercontent.com/5681979/64956016-55ee0d80-d892-11e9-83a8-88f0320317f3.png)

However, for a web application, everything works correctly.

![изображение](https://user-images.githubusercontent.com/5681979/64956521-779bc480-d893-11e9-9674-e99453e0ccb8.png)

**How to reproduce**  

So, I create file: test.php
```php
<?php declare(strict_types=1);

$autoload = require __DIR__ . '/vendor/autoload.php';

$class = new class {
    private $array = [0, 1, 2, 3];
    public function test(string $value)
    {
        return $value;
    }
};

dd($class);
```

**Result:**
![изображение](https://user-images.githubusercontent.com/5681979/64956016-55ee0d80-d892-11e9-83a8-88f0320317f3.png)

And the console freezes.

**Comment by fancyweb** [comment]
Status: works for me.

Please provide the exact PHP version + the result of a `composer show` + which terminal you use. I think that would help.

**Comment by nepster-web** [comment]
So, this strange situation.
I use docker and php7.3.9.

For test:

**docker-compose.yml**
```
version: '3.7'

services:
    php:
        container_name: test_dump_php
        build: ./
        restart: always
        volumes:
            - ./www:/www
```

**Dockerfile**

```
FROM php:7.3.9-fpm-alpine

RUN apk add --no-cache \
    curl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /www
```

**composer.json**
```
{
  "name": "test",
  "description": "Test",
  "keywords": [],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=7.3",
    "symfony/var-dumper": "4.3.4"
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}
```

Run
```
docker-compose build
docker exec -it test_dump_php /bin/sh
composer install
php test.php
```
-------------------------

okey, it works correctly for the default Linux console:
![изображение](https://user-images.githubusercontent.com/5681979/65023283-20e9c580-d93b-11e9-839e-880a9bbd501f.png)

but, the same for PHPStorm console (and freezes):
![изображение](https://user-images.githubusercontent.com/5681979/65023423-76be6d80-d93b-11e9-8bf5-e904ad4c60b3.png)

As I understand it, this problem can be reproduced in a PHPStorm.

My PHPStorm data:
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
Licensed to Anatoliy Pritulskiy
You have a perpetual fallback license for this version
Subscription is active until April 16, 2020
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-60-generic

**Comment by stof** [comment]
Can you try with the latest PHPStorm version too ? This looks like a bug in their terminal, as it only impacts the PHPStorm console, but we should report it only if it happens in the latest version (they might have fixed it already).

**Comment by nepster-web** [comment]
Yes, you are right. In PHPStorm  2019.2.2 everything works correctly. Thank you very much.
