### ISSUE TITLE
Undefined class constant 'RESERVED_CHARACTERS'

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#33593]
**Symfony version(s) affected**: latest 4.x

**Description**  

Yesterday, after upgrading SF to the latest version, I start to get the following error:

> Undefined class constant 'RESERVED_CHARACTERS' 

![image](https://user-images.githubusercontent.com/374134/64955530-aaa18080-d8b2-11e9-9cf4-a8b4fd1cfae0.png)

**How to reproduce**  
My project is huge, I'm still trying to get the minimal code to regenerate this error. For now, add back to constant to the class will fix it.

**Possible Solution**  

It seems like the constant is moved now to the Interface which causes the error?

**Additional context**  

My PHP is on 7.2 if that makes any difference.

**Comment by yellow1912** [comment]
I think the error may have something to do with this PR: https://github.com/symfony/symfony/pull/33516

**Comment by xabbuh** [comment]
@yellow1912 Can you show the output of `composer show` when having this issue?

**Comment by yellow1912** [comment]
@xabbuh 

I have created a gist with the output of composer here

https://gist.github.com/yellow1912/dcdf1905a6e6837a928a3571231100f3

**Comment by xabbuh** [comment]
@yellow1912 Thank you 👍 This should work again once #33597 is merged
