### ISSUE TITLE
[HttpClient]  Prevent curl from sending its default Accept and Expect headers

### ISSUE THREAD

**Issue by numerogeek** [symfony/symfony#33596]
Hello,

I am currently dealing with a big account's API, and I figured out that when I send a specific request from POSTMAN it was working, but the very same request failed through the httpClient. 

After hours of investigating, I figured out that the httpClient was setting default value for accept and except headers. (cf https://github.com/symfony/http-client/blob/master/CurlHttpClient.php#L245) 

 Adding the following lines fixed my problem:      
```
 'headers' => [
                'Accept' => '*',
                'Expect' => '*',
]

```

But I'm wondering why have you coded this in the first place ? 

Thank you

**Comment by nicolas-grekas** [comment]
The lines you linked too are about NOT sending those headers by default.
Maybe postman sends them for you if you don't, that's why you didn't notice?
You can use `$response->getInfo('debug')` to see what's been really sent.

**Comment by numerogeek** [comment]
Indeed they're not sent if I don't send them manually. 
I've added these headers manually and it's working. 

From my understanding, it was checking if "accept" and "expect" was in the headers, and if they're not, you were adding them manually : 
```
        foreach (['accept', 'expect'] as $header) {
            if (!isset($options['normalized_headers'][$header])) {
                $curlopts[CURLOPT_HTTPHEADER][] = $header.':';
            }
```

For my personnal culture, could you please tell me the purpose of theses lines ? 

Thank you !

**Comment by nicolas-grekas** [comment]
what the comment tells :)

> Prevent curl from sending its default Accept and Expect headers

by default, curl sends `Accept: *` (and `Expect: 100 continue` for post requests)

**Comment by nicolas-grekas** [comment]
Should we send `Accept: *` by default too if not provided?

**Comment by numerogeek** [comment]
@nicolas-grekas Maybe, because it was confusing for me that a manual PHP Curl request worked, a postman request worked, but, with the very same configuration it wasn't working with httpClient. 
I spent few hours to discover that this was coming from there.

On the other side, maybe that a 403 Forbidden response wasn't a nice response from the API for not providing an accept header 😅

**Comment by nicolas-grekas** [comment]
+ it's considered a limitation in postman actually :)
https://github.com/postmanlabs/postman-app-support/issues/1673

**Comment by numerogeek** [comment]
> Should we send `Accept: *` by default too if not provided?

@nicolas-grekas I think we should. 
Is it expected that the 2 followings examples behave differently ?

First :


```

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => $attachment->getUploadUrl(),
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => "image_binary",
            CURLOPT_HTTPHEADER => array(
                "Content-Type: application/x-www-form-urlencoded",
                "X-Brand-AppToken: ".$attachment->getAppToken(),
                "X-Brand-Gigafiles-Cid: ". $attachment->getGigaFileCid(),
            ),
        ));

        $response = curl_exec($curl);
        $http = curl_getinfo($curl, CURLINFO_RESPONSE_CODE);
        $err = curl_error($curl);

        curl_close($curl);
```


Second :


```
        $client = HttpClient::create([
            'max_redirects' => 10,
            'http_version' => 1.1,
            'headers' => [
//                'Accept' => '*',
//                'Expect' => '*',
                'X-Brand-AppToken' => $attachment->getAppToken(),
                'X-Brand-Gigafiles-Cid' =>  $attachment->getGigaFileCid(),
                'Content-Type' => 'application/x-www-form-urlencoded'
            ]
        ]);
        $response = $client->request('POST', $attachment->getUploadUrl(),[
            'body'    => $contents,
            'http_version' => CURL_HTTP_VERSION_1_1,
        ]);
        $content = $response->getContent(false);

```

**Comment by nicolas-grekas** [comment]
PR welcome then, this should go in HttpClientTrait I think, branch 4.3.
