### ISSUE TITLE
[Form/Twig] Dynamic Form Modification crashes in Template::displayWithErrorHandling when Entity->__toString() throws an exception.

### ISSUE THREAD

**Issue by DubbleClick** [symfony/symfony#33591]
**Symfony version(s) affected**: 4.3.4

**Description**  
When setting a ManyToOne association of an entity in the database to null for dynamically modified forms (https://symfony.com/doc/current/form/dynamic_form_modification.html) this subsequently causes a crash in the Template::displayWithErrorHandling `try { $this->doDisplay(...); }` block. The ManyToOne in question is unidirectional and nullable. Instead of crashing, this should display the error message that it's attempted to call a method on null.
This even crashes the webserver.
This does NOT happen on entities that are not in the database.

**How to reproduce**  
Entity.php
```
/**
 * Entity
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="App\Repository\EntityRepository")
 */
class Entity
{
    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    public $id;

    /**
     * @var OtherEntity
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\OtherEntity", cascade={"persist"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="other_entity_id", referencedColumnName="id", nullable=true)
     * })
     */
    protected $other;

    public function __toString()
    {
        return $this->other->someMethod(); // <---- this should throw Error: Method App\Entity\Entity::__toString() must not throw an exception, but when used in dynamic form modifiers it instead crashes Symfony in twig render.
    }
}
```
EntityController.php
```
/**
     * @Route("/{id}", name="entity_show")
     */
    public function showAction(Request $request, Entity $entity)
    {
        $form = $this->createForm(EntityType::class, $entity);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->persist($entity);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('entity/edit.html.twig', [
            'form' => $form->createView(),
            'entity' => $entity
        ]);
    }
```
EntityType.php
```
$formModifier = function (FormInterface $form, Entity $entity = null) {
            if ($entity == null) {
                return;
            }
            $form->add('unmappedchoices', EntityType::class, [
                'mapped' => false,
                'class' => ThirdEntity::class,
                'placeholder' => false,
                'query_builder' => function (ThirdEntityRepository $repository) use ($entity) {
                    $qb = $repository->createQueryBuilder('s');
                    if ($entity->getOther()) {
                        $qb = $qb
                            ->andWhere($qb->expr()->eq('s.other', ':other'))
                            ->setParameter('other', $entity->getOther());
                    }
                    //$results = $qb->getQuery()->getResult(); // works fine, just to check
                    return $qb;
                },
                'required' => false
            ]);
        };
$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($formModifier) {
                $data = $event->getData();
                if ($data && $data instanceof Entity)
                    $formModifier($event->getForm(), $data);
            });
        $builder->get('seminar')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                $entity= $event->getForm()->getParent()->getData();
                $id = array_keys($event->getData())[0] ?? null;
                if ($id) {
                    $other = $this->getRepository(Other::class)->find($id);
                    $waitList->setOther($other);
                }
                else {
                    $entity->setOther(null); // crashes the webserver completely
                }
                $formModifier($event->getForm()->getParent(), $entity);
            }
        );
```
templates/entity/edit.html.twig
```
{% block content %}
    form(form)
{% endblock %}

{% block javascripts %}
    <script>    
    $(document).ready(() => {
        $('#form_other').change(function () {
            let $form = $(this).closest('form');
            let data = {};
            data[$('#form_other').attr('name')] = $('#form_other').val();
            $.ajax({
                url: $form.attr('action'),
                type: $form.attr('method'),
                data: data,
                success: function (html) {
                    let choices = $(html).find('#form_unmappedchoices');
                    $('#form_unmappedchoices').empty().val('').change().append(choices.get(0).options);
                }
            });
        });
    });
    </script>
{% endblock %}
```

**Possible Solution**  

**Additional context**  
https://i.imgur.com/gXqJcUo.png
Webserver: Apache 2.4.6
CentOS 7
PHP 7.1.23 and PHP 7.3.9

**Comment by xabbuh** [comment]
IMO this is a bug in your implementation of the `__toString()` method. I am not sure that there is much we can do about it.

**Comment by DubbleClick** [comment]
Yes, this is happens because of the error in the __toString() implementation, however, it should usually render a page similar to this:

![image](https://user-images.githubusercontent.com/7896469/64964335-2a235580-d89b-11e9-9f90-17abd611fae1.png)

If, however, this happens in a modified form event, it crashes the webserver instead of rendering the page.

**Comment by linaori** [comment]
Could it be related with doctrine proxies? I'd expect some kind of infinite loop based on:

> or well, keeps occupying it until timed out or killed

and

> This does NOT happen on entities that are not in the database

Please note though that [in php 7.4 and up](https://wiki.php.net/rfc/tostring_exceptions) you can throw exceptions in `__toString()`

**Comment by DubbleClick** [comment]
Possibly, I couldn't track down the issue further because the IDE couldn't open the document where $this->doDisplay() is implemented.

**Comment by xabbuh** [comment]
@DubbleClick Could you create a small example application allowing to reproduce it so someone could see if the error reporting could somehow be improved?

**Comment by DubbleClick** [comment]
I'll try this evening once I'm off work.

**Comment by DubbleClick** [comment]
I've created a project to showcase the problem, but can't currently reproduce the error as php 7.2.9 on windows with the webbundle server seems to behave way differently with exceptions in __toString(). I'll test it tomorrow and then give the ok when I'm able to reproduce it. https://github.com/DubbleClick/symfony-bug33591

**Comment by DubbleClick** [comment]
Sorry that it took a while, but I can replicate the issue with the project I created above at work. It must be with the Apache or php version, as it doesn't happen at home, where it correctly throws the status 500 that __toString mustn't throw Exceptions.

If you'd like, I could try to set up a small VM that's able to reproduce the issue.

**Comment by DubbleClick** [comment]
Okay, it must be an issue in Xdebug after all, that somehow only happens in this specific case. When I load xdebug but set remote_autostart to 0 (and don't set the xdebug cookie) it no longer crashes. Looks like xdebug gets stuck somewhere when the exception is thrown. I have no idea how I'd go about debugging xdebug though and at this point can't even be completely sure if the issue is symfony specific, so I'd say this issue may be closed. It's still very strange to me that this only happens with a dynamic form modifier in an ajax request with entities persisted in doctrine.
