### ISSUE TITLE
[phpunit-bridge] Allow "--ignore-platform-reqs" to install phpunit 

### ISSUE THREAD

**Issue by mazarini** [symfony/symfony#33592]
Allow install phpunit/phpunit without  platform-req to test PHP8 by exemple.

Add a new command (install-no-req / install) or add a new variable or add a new option.
Can be do in "simple-phpunit.php" :  
1) Add a vars $COMPOSER_CONFIG = $COMPOSER; (for config action)
2) add when needed : $COMPOSER .= ' --ignore-platform-reqs';
3) change : passthru("$COMPOSER**_CONFIG** config --unset platform"); (2 times)

**Comment by nicolas-grekas** [comment]
In https://github.com/symfony/symfony/pull/33642#issuecomment-535697007 I commented with:

> there is an alternative since this is for early experimentations:
>    run simple-phpunit install on PHP 7.*
>    run it again with proper arguments on PHP 8

I'd like to know if that would work for you.
The "PHP8 problem" is temporary, we'd better think twice before adding features for temporary needs.
