### ISSUE TITLE
Bug https://symfony.com/doc/current/doctrine/common_extensions.html

### ISSUE THREAD

**Issue by isopen** [symfony/symfony#33604]
**Symfony version(s) affected**: 4+

**Description**  
https://github.com/Atlantic18/DoctrineExtensions
Works poorly...
Partial tree transfer works poorly...Does not change root...
Bad changes made since 2016...

**How to reproduce**  
https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17
This is where Nestedset works.

**Possible Solution**  
https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17

**Additional context**  
thanks for the quick response.

**Comment by xabbuh** [comment]
`gedmo/doctrine-extensions` is not part of the Symfony core. Please report issues with that library in [their repository](https://github.com/Atlantic18/DoctrineExtensions). Thank you for understanding.

**Comment by isopen** [comment]
@xabbuh This applies to the official Symfony 4 documentation.
People use unstable packages as recommended by Symfony.
Thanks for understanding.

**Comment by xabbuh** [comment]
I am sorry, but then I do not understand what you meant with your initial issue description. Can you clarify that a bit?

**Comment by isopen** [comment]
Play steps:
- Go https://symfony.com/doc/current/doctrine/common_extensions.html
- Next, the person installs the package
- Gets bugs in the project. Because the algorithms in the current implementation are not implemented correctly.

My experience struggled with them for 2 weeks.
As a result, having looked at the vendor code, it became clear to me that stable 2.4 is unstable.
The problem is that there is not a word in the documentation(symfony) about the need to use development packages.

**Comment by xabbuh** [comment]
I am not aware of the fact that the extension is not working as expected. I do not use it myself though. Are you sure that you did not only encountered a bug in that extension?

**Comment by isopen** [comment]
Now I'm testing the Timestampable mechanism. It does not work on the default method `@Gedmo\Timestampable (on = "update")`
