### ISSUE TITLE
bootstrap cache requires ClassCollectionLoader which does not exist

### ISSUE THREAD

**Issue by yellow1912** [symfony/symfony#33615]
**Symfony version(s) affected**: 4.x latest

**Description**  

I'm running into this weird issue on my production environment with the latest code:

> 2019/09/17 18:23:48 [error] 21935#21935: *1135077 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/path_to/app/../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php): failed to open stream: No such file or directory in /path_to/app/bootstrap.php.cache on line 1418
> PHP message: PHP Fatal error:  require(): Failed opening required '/path_to/app/../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php' (include_path='.:/usr/share/php') in /path_to/app/bootstrap.php.cache on line 1418" while reading response header from upstream, client: x.x.x.x, server: x.x.com, request: "GET /backend/party_notification/summary HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-xx.sock:", host: "x.x.com"
> 

**How to reproduce**  

This happens on our current app which is being migrated from version 3 to the latest 4. The dev version runs fine (I guess because it does not require the bootstrap cache file)

**Possible Solution**  

I'm going to update my composer to see if this helps.

**Additional context**  

I'm running on php 7.2

**Comment by stof** [comment]
`bootstrap.php.cache` is something that your project should not use anymore. It was a 2.x feature, which was dropped from Symfony 3.x skeletons years ago because it would not bring any performance improvement on PHP 7 (and could even have a negative impact on performance in some cases).

**Comment by yellow1912** [comment]
Roger that, thank you @stof
