### ISSUE TITLE
[Messenger] Autoroute consumed message to correct bus by message handler configuration

### ISSUE THREAD

**Issue by dvc** [symfony/symfony#33627]
**Description**  

https://symfony.com/doc/current/messenger/multiple_buses.html

I can configure multiply buses, and i can attach message handler to single bus.

So, i can use "add_bus_name_stamp_middleware " in such cases. By message type + its message handler bus.

Without this functionality, i need to create custom queue+transport for every bus and configure routing on MQBroker side. And i need to run multiply consumers with custom transport and bus key.

**Example**  

Transport: async
Messages types: CommandA (async), QueryB (async), EventC(async)
Buses: command_bus (default), query_bus, event_bus
Handlers: CommandAHandler(command_bus), QueryBHandler(query_bus), EventCHandler(even_bus)

bin/console messenger:consume <-- QueryB

Expected: QueryB hadled by BHandler -> BHandler attached to query_bus -> add_bus_name_stamp_middleware (query_bus) -> success

Actual: fail because of routing QueryB to command_bus

**Comment by dvc** [comment]
Hello everybody!

May be i don't understand some details... 
I have an idea about unification messaging handling process.  My issue is about difference between handling internal messages and consumed outside.

May be "right" chain always should be start with transport:  
publisher -> to transport -> send to MessageBrocker
publisher -> to transport -> message bus -> handler
consumer -> from transport -> message bus -> handler

Some "internal://" or "sync://" transport have to be configured as MessageBusLocator. Another "async" transport should send message directly outside (after serialization). Dispatching messages to bus should be internal detail. User will sent it to transport.

```php
class DefaultController extends AbstractController
{
    public function index(MessagerTransportInterface $transport)
    {
        $transport->sent(new SmsNotification('Look! I created a message!'));
    }
}
```

**Comment by dvc** [comment]
Hello everybody!

Any ideas required! I really don't understand how to use official documentation for multiply buses with this "bug".

`Symfony\Component\Messenger\RoutableMessageBus`  looks like place for autoresolving right bus. 
Also it could be custom middleware with `BusNameStamp` adding... It's too complex for me :(

**Comment by Tobion** [comment]
From what I understood, you wonder how to route consumed messages to the right bus. By default they are routed to the bus, they got published on using the BusNameStamp as you mentioned. But you can also consume messages from a certain transport and forward them to a specific bus ussing the --bus option. See https://github.com/symfony/symfony/blob/b54997d1dfbbd7afabced9dbc3b3544448f02ca9/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php#L97

Btw, to me this looks like a support question. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by dvc** [comment]
Hello, @Tobion! Thanks for answer.

I disagree, with your point of view. It looks like a bug.

My use case: single remote queue with multiply message types. I can't start multiply consumers with custom target bus. It's not a solve.
