### ISSUE TITLE
Symfony4 form File upload field is not working

### ISSUE THREAD

**Issue by MarkoM91** [symfony/symfony#33624]
Using Symfony 4.0, I made a Form with a VichImageType (with FileType gives the same problem) file it generates the field in the view but when I click the Browse Button it doesn't open my document folder(in order to search the picture), it remains stucked,  what could be the problem?

I'll post the view, the form, and the entity:

//view

```twig
{% extends 'bundles/FOSUserbundle/views/base.html.twig' %}
{% block body %}
    <div class="row mt-5">
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Register first</h4>
            {# <form method="POST" action="#" class="needs-validation" novalidate> #}
            {{ form_start(form,{'attr': {'class':'needs-validation'}}) }}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="user_name">First name</label>
                    {# <input type="text" class="form-control" id="name" placeholder="" value="" 
                    required> #}
                    {{ form_widget(form.name) }}
                    <div class="invalid-feedback">
                        Valid first name is required.
                        {{form_errors(form.name)}}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="user_last_name">Last name</label>
                    {# <input type="text" class="form-control" id="lastName" placeholder="" value="" 
                    required> #}
                    {{ form_widget(form.lastName) }}
                    <div class="invalid-feedback">
                        Valid last name is required.
                        {{form_errors(form.lastName)}}
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="user_email">Email</label>
                {# <input type="email" class="form-control" id="email" placeholder="you@example.com" 
              required> #}
                {{ form_widget(form.email) }}
                <div class="invalid-feedback">
                    Please enter a valid email address.
                    {{form_errors(form.email)}}
                </div>
            </div>

            <div class="mb-3">
                <label for="user_username">Username</label>
                {# <input type="text" class="form-control" id="user_username" required> #}
                {{ form_widget(form.username) }}

            </div>
            <div class="mb-3">
                <label for="user_level">Level</label>
                {# <input type="text" class="form-control" id="user_level" required> #}
                {{ form_widget(form.level) }}

            </div>

            <div class="mb-3">
                <label for="user_dateOfBirth">Date Of Birth</label>
                {# <input type="text" class="form-control" id="user_dateOfBirth" required> #}
                {{ form_widget(form.dateOfBirth) }}

            </div>
            <div class="mb-3">
                <label for="users_imageFile_file" class="custom-file-label">Date Of Birth</label>
                {# <input type="file" name= "users[imageFile][file]" class="custom-file-input" 
               id="users_imageFile_file" required> #}
                {{ form_widget(form.imageFile) }}

            </div>

            {{ form_end(form) }}

        </div>
    </div>
{% endblock %}
```
//form

**Comment by MarkoM91** [comment]
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Vich\UploaderBundle\Form\Type\VichImageType;



class UsersType extends AbstractType
{
    public function buildForm( FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class )
            ->add('lastName', TextType::class)
            ->add('level', ChoiceType::class, [
              'choices'  => [
                    'operator' => 'Operator',
                    'supervisor' => 'Supervisor',
                    'admin' => 'Admin'
                  ]
                ])
            ->add('username', TextType::class)
            //->add('password', PasswordType::class)
            ->add('email', TextType::class)
            ->add('dateOfBirth', BirthdayType::class, [
              'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
                  ]
                ])
            ->add('imageFile',VichImageType::class)
            ->add('save', SubmitType::class, [
              'attr' => [
                'class' => 'btn btn-primary float-right'
              ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
